### ISSUE TITLE
Savegame

### ISSUE THREAD

**Issue by Williwillswisse** [Stephan-S/FS19_AutoDrive#1]
Hallo Stephan,
das mit der Maus und den Cursortasten hat sich erledigt. Ist so wie von dir beschrieben.
Folgendes ist mir aber noch aufgefallen:
1. Wenn ich mein Savegame einmal mit deaktiviertem AutoDrive starte wird die Autodrive Config gelöscht?
2. Wenn AutoDrive aktiv ist dauert das Speichern des Spielstandes im FS19 sehr lange. Habe ich Autosave im FS19 aktiv dauert es jedes mal ewig wenn ich ins ESC Menü wechsel. FS19 speichert ja nicht alle 5 min, sondern das nächste mal nach 5 min wenn das Menü geöffnet wird. Ich vermute AutoDrive berechnet beim Speichern die Routen noch mal neu?

Sonst läuft AutoDrive für mich schon mal super.
Bedienung und Verhalten sind viel flüssiger als im FS17. Auch ist es super das ich, während die Routen berechnet werden, weitermachen kann. Im FS17 war dabei ja alles blockiert.
Super Arbeit und vielen Dank von mir schon mal für das Erreichte.
Ich habe jetzt auf der NF Marsch alle Stationen und alle Felder eingefahren. Das Fahrverhalten der Fahrzeuge ist auch um Welten besser als im FS17.
Was mir noch aufgefallen ist:
Stehe ich mit dem Fahrzeug senkrecht zum Kurs und starte, fährt es zur Linie, biegt in die richtige Richtung ein und dreht dann Kreise. Das ist nicht immer so. Hat das mit dem Wendekreis des Fahrzeugs zu tun? Wenn es dichter an der Linie ist als der eigene Wendekreis?
Knicklenker und Fahrzeuge mit Hinterradlenkung sind wahrscheinlich noch ein spezieller Fall?

**Comment by Stephan-S** [comment]
Hallo,

zu 1: Ja, da der Savegame Ordner immer komplett überschrieben wird soweit ich weiß. Sprich wenn AutoDrive nicht aktiv ist und die xml Datei speichert, wird sie überschrieben. Aber das schau ich mir nochmal genauer an.

zu 2: Das sollte eigentlich in der aktuellen Version nicht mehr der Fall sein. Nur wenn du etwas an der Strecke verändert hast, wird einmalig beim nächsten Speichern die komplette xml Datei neugeschrieben und dass dauert je nach Anzahl Wegpunkten dann eben ein paar Sekunden. Bei weiteren Autosaves sollte das allerdings aktuell nicht mehr passieren. Falls doch, schreib mir das bitte nochmal. Ich bin derzeit sehr mit dem Thema Multiplayer beschäftigt und teste kaum andere Features.

Senkrecht zum Kurs starten ist noch ein grundsätzliches Problem, da das Fahrzeug dann ja eine 90° Kurve auf einer sehr kurzen Strecke fahren muss. Das geht meistens schief. Ich probiere mich demnächst mal daran ob sich das noch etwas optimieren lässt und er an solchen Stellen etwas 'weiter vorrausschauend' fahren kann um sicher auf den Kurs zu kommen.

Knicklenker habe ich tatsächlich noch gar nicht testen können. Hinterradlenkung habe ich zumindest bei ein paar Testfahrten mit dem kleinen Mähdrescher keine Auffälligkeiten bemerkt und er ist ans Ziel gekommen, solange die Strecke breit genug wahr :D

**Comment by Williwillswisse** [comment]
Hallo Stephan,
ich habe noch mal die letzte Version runtergeladen und rumgespielt.
Punkt 2 hat sich nach ersten Tests erst einmal erledigt. Ich werde das mal weiter beobachten.
Eine Frage noch: Beim LS17 konnte man aufgrund des Farbverlaufs der Verbindungslinien die Fahrtrichtung erkennen. Das ist jetzt nicht mehr so?

**Comment by Stephan-S** [comment]
Der Farbverlauf ist so ohne weiteres nicht mehr möglich. Ich überlege noch das möglicherweise anders zu lösen. Aber bin noch zu keine zufriedenstellenden Lösung gekommen. Pfeile würden nicht schön aussehen, wären aber die einfachste Lösung. Das möchte ich eigentlich umgehen.
