### ISSUE TITLE
Problem mit der Befüllung des Zubringfass mit Gärresten 

### ISSUE THREAD

**Issue by FarmingPower** [Stephan-S/FS19_AutoDrive#100]
Hallo, 
erstmal Danke für die Arbeit von diesem Mod, nutze ihn sehr sehr gerne doch leider habe ich ein Problem Mit dem Befüllen von Gärresten an der BGA.

Wollte eben Gärreste abholen lassen von der BGA und diese zu einem Feldrandcontainer an einem Feld bringen lassen.
Das Gespann fährt  zur BGA befüllt sich nur leider nicht von selber.

Das gleiche habe ich dann ausprobiert an einem Kuhhof dort klappt der ablauf einwandfrei. 
Gespann fährt hin lädt am Behälter und fährt dann zum Feld.

**Comment by OnkelH0tte** [comment]
das Problem habe ich auch. in der log taucht dann eine Meldung auf das irgendwelche Buchstaben äää… (vermutlich wegen Gärreste) nicht erkannt werden, oder so ähnlich. habe leider keine aktuelle log, bzgl. des fehlers.
