### ISSUE TITLE
Mod does not show up at all or shows up as Courseplay v300

### ISSUE THREAD

**Issue by Flashsolutions** [Stephan-S/FS19_AutoDrive#1000]
AutoDrive Version: 1.0.0.7
Release or custom zip: Release
Map (if applicable): All
Vehicle / type (applicable):

**Describe the bug**
Using version 1.4.0.1 of Farm Sim 19, placing the latest AD mod in the mod folder with the courseplay mod, produced two coursplay mods showing up when you open a map.

Placing the mod in an empty folder produced no mod showing up at all.  In fact, using the mod in an existing map with other mods totally corrupted my savegame.

After applying patch 1.5 of farm sim, I finally got it to work.

I checked the moddesc.xml file and found the mod version had changed between 1.0.6.9 and 1.0.7.0 from value of 43 to the value of 49.

Repeating this on a second computer, I changed the moddesc.xml value back to 43 and got it to work with patch level 1.4.

**If applicable - Steps to reproduce the behavior**

**Screenshots**

**Comment by TyKonKet** [comment]
Yes version 49 works only with patch 1.5, but we have to keep version 49, this are the rules of ModHub.
