### ISSUE TITLE
AD unterstüst nicht den 2 Anhänger

### ISSUE THREAD

**Issue by RudiBergfeld** [Stephan-S/FS19_AutoDrive#1007]
AutoDrive Version: 1.0.
Release or selbsterstelltes zip: Release
Karte (falls relevant): Alle
Fahrzeug(art) (falls relevant):

**Beschreibe den Bug**
AD unterstüst nich den 2 Anhänger  ich möchte mit 2 Anhäner und eine Tacktor als zugfahrzeug fahren ist das mit AD irgentwie möglich?

**Falls anwendbar - Schritte mit denen ich den Bug nachstellen kann**

**Screenshots**
Falls relevant, bitte Screenshots beifügen

**Comment by TobiHH78** [comment]
AutoDrive Version: 1.0.??
Nutzt du eine aktuelle Github Vresion? Zwei Anhänger funktionieren schon länger problemlos.

**Comment by RudiBergfeld** [comment]
ich habe die actuelle version 1.0.7.33 von Github ich nutze die Multimap ls19 wie muss ich das einstellen das es geht habsächlich die abfahrer  vom drescher 
[log.txt](https://github.com/Stephan-S/FS19_AutoDrive/files/3946119/log.txt)

**Comment by Iwan1803** [comment]
AD unterstützt 2 Anhänger, aber es kann je nach Kombi und wohl bei manchen Triggern noch zu Problemen kommen.
Ohne ausführliche Infos ist es allerdings eine Suche nach der Nadel im Heuhaufen.
Siehe: https://github.com/Stephan-S/FS19_AutoDrive/issues/1071
