### ISSUE TITLE
hazard lights can be turned on like the beacons

### ISSUE THREAD

**Issue by joshvzeyl** [Stephan-S/FS19_AutoDrive#1009]
I would love to see an option that AD drive turns on the warn signals on by tractors when they are driving on the road

**Comment by TyKonKet** [comment]
What do you mean with 'warn signals'?

**Comment by Justice-Molton** [comment]
I guess he's talking about the rotating lights

**Comment by joshvzeyl** [comment]
i mean the hazard lights

**Comment by TyKonKet** [comment]
Hey @joshvzeyl I'm back to that issue, but i still can't understand what kind of lights you are asking for.

**Comment by joshvzeyl** [comment]
![InkedfsScreen_2020_04_06_19_33_02_LI](https://user-images.githubusercontent.com/26695249/78587917-02e3a400-783e-11ea-9447-952ac7eedc29.jpg)

i mean both the turnsignals that are hazards also i mean the orange lamps i circled in the pitcture

**Comment by Justice-Molton** [comment]
That’s different in the US and the EU 
In the US this lights are always on in the EU they are not there or they’re used as direction indicators.

**Comment by TyKonKet** [comment]
Ouch now I can finally understand, yes in EU those kind of lights are used only as direction indicators.
But yes, if you say that in US you turn them on while driving on streets, we can add a setting to enable that.

**Comment by Stephan-S** [comment]
no, I really don't want a setting for that. This just clutters the menu even more
