### ISSUE TITLE
No feature request, no problem with AD, only question because of the momentary silence here -  Kein Feature request, Keine Problem mit AD, nur Frage wegen der momentanen Stille hier

### ISSUE THREAD

**Issue by haamic** [Stephan-S/FS19_AutoDrive#1010]
Everything okay here? Otherwise I had a lot of messages/replies/comments every day and since a few days nothing more? Is it just me, or do you get nothing more? 
Greetings Micha
++++++++++++++++++++++++++++++++++++++
Alles okay hier? Sonst hatte ich täglich viele Meldungen/Antworten/Kommentare und seit paar Tagen nichts mehr? Geht das nur mir so, oder bekommt ihr auch nichts mehr? 
Gruss Micha

**Comment by geo-luchs** [comment]
Hello Micha and all the others

For one thing, I can only assume that Stephan and the other programmers might spend a little more time on other nice things during the Christmas season.
They deserved it. Thanks for all the programming lessons and the great mod.

On the other hand I have to emphasize positively. At the moment the system is very stable.
In the evening I let several helpers drive with CP and AD for hours, and work fields.
Harvest, sow, collect grass and hay,

And I never really have to intervene.

Therefore I have no reason to open a new issue at the moment.

Translated with www.DeepL.com/Translator (free version)

++++++++++++++++++++++++++++++++++++++++++++++++++

Hallo Micha und alle anderen

Zum einen kann ich nur vermuten, dass Stephan und die anderen Programmierer in der Weihnachtszeit vielleicht auch etwas mehr ZEit für andere schöne Dinge aufwenden.
Verdient haben sie es. Danke für die vielen Programmierstunden und den tollen Mod.

Zum Anderen muss ich auch mal positiv hervorheben. Aktuell ist das System bei mir sehr stabil.
Ich lasse abends nebenbei stundenlang mehrere Helfer mit CP und AD fahren, und Felder abarbeiten.
Ernten, sähen, Gras/Heu einsammeln,

Und muss eigentlich nie eingreifen.

Daher habe ich aktuell auch keinen Grund, ein neues Issue zu öffnen.

Gruß
Carsten

**Comment by haamic** [comment]
Ja das wäre eine Erklärung. Ist ja auch nicht schlimm, hatte mich nur gewundert.
Leider hab ich eben erst bemerkt, das bei mir der "Abholen" Modus nicht mehr geht, seit version -33.
Kann meinen Düngerstreuer nicht mit AD auffüllen lassen, da es zuerst immer zum Feld will und nicht zum Silo.  da übergibt AD gleich wieder an CP und es geht von vorn los.
Mal sehen ob ich noch andere Versionen hab, wo es noch geht.
++++++++++++++++++++++++++++++++++++++++++++++++
Yes, that would be an explanation. It's not bad either, I had only wondered.
Unfortunately I just noticed that the "pickup" mode doesn't work anymore, since version -33.
Can't let my fertilizer spreader fill up with AD, because it always wants to go to the field first and not to the silo. There AD hands it over to CP again and it starts from the beginning.
Let's see if I still have other versions where I can.

Translated with www.DeepL.com/Translator (free version)

**Comment by Stephan-S** [comment]
Hey guys,
I had pretty busy work weeks or rather months lately and didn't get to work on AutoDrive as much as I used to. And then I was on vacation last week :-)

But now I'm back and I will work on the last pressing issues with load/unload/pickup mode vehicles not properly continuing.

Greetings,
Stephan
