### ISSUE TITLE
Parkplätze werden nicht mehr erkannt. parkingplaces get lost

### ISSUE THREAD

**Issue by ArWeGer** [Stephan-S/FS19_AutoDrive#1017]
AutoDrive Version: 1.0.6.9 und 1.0.7.0 Release und 1.0.7.0-34 MasterBranch
Release or selbsterstelltes zip: Release und selbst erstellstes Master-Zip
Karte (falls relevant): Alle
Fahrzeug(art) (falls relevant): alle

**Beschreibe den Bug**
Vermutung: Parkplätze werden beim laden nicht mehr ermittelt (parkDestination).

**Falls anwendbar - Schritte mit denen ich den Bug nachstellen kann**
Ich weiß nicht, ob es eine Relevanz hat. Ich war auf Version 1.0.6.8 und hatte auf 1.0.7.0 aktualisiert. Da die Probleme mit dem automatischen Laden/Entladen und die Kursermittlungsprobleme bei Fahrzeugen mit kurzem Radstand für mich so nicht spielbar waren, bin ich zurück auf 1.0.6.9.
Reproduzierbarkeit:
Wenn einem Fahrzeug ein Parkplatz zugewiesen wird, wird dieser korrekt in der vehicles.xml im parkDestination-Tag eingetragen. Soweit ok. Wird der Spielstand jetzt neu geladen, ist beim jeweiligen Fahrzeug der Parkplatz im HUD nicht mehr aktiv, so als ob er nicht geladen worden wäre. In der vehicles.xml steht er aber nach wie vor drin.
Beim erneuten Speichern überschreibt AD nun die (immer noch) korrekten Werte in der vehicles.xml mit -1, da AD die Werte nicht geladen hatte und somit (aus Sicht von AD) -1 ja korrekt ist.

**Screenshots**
Falls relevant, bitte Screenshots beifügen

**Comment by ArWeGer** [comment]
Ich habe versucht den Fehler einzugrenzen. Es scheint sich hierbei um irgendwelche Seiteneffekte zu handeln, die ich ohne Debugging-Log nicht näher eingrenzen kann.
Ich habe ein neues Spiel ohne Mods (außer AD) begonnen - selbes Problem. Die log.txt ist fehlerfrei - trotzdem werden die Parkplätze nicht geladen :(

**Comment by ArWeGer** [comment]
Leider gibt es hier auch 6 Wochen nach meiner Melsung keine Reaktion. Echt schade :(

**Comment by TyKonKet** [comment]
**Hello, Thank you for opening this issue!**
Since we have just released [the new refactored version of AutoDrive](https://github.com/Stephan-S/FS19_AutoDrive/releases/tag/1.1.0.0), we can no longer provide any feedback or support for open bug reports related to the old code base.
If the problem persists, please reopen a new issue with all the required details.
Thank you for understanding and we hope you continue enjoying our mod 😄
