### ISSUE TITLE
AD editor loading map image

### ISSUE THREAD

**Issue by Escrimatics** [Stephan-S/FS19_AutoDrive#1018]
I am trying to use the course editor in java but every time a try to load a map i get this small map panel and even if i start maximized or stretch the window the map image is still small.  Not sure what to do with this

![AD1](https://user-images.githubusercontent.com/59119720/71310354-38749680-23e1-11ea-9719-38fabfbaaac9.PNG)
![AD2](https://user-images.githubusercontent.com/59119720/71310355-3b6f8700-23e1-11ea-9093-fce6f68a48df.PNG)

**Comment by betrox007** [comment]
first you must record course for entire map edge, so all map can open in editor, if you just record partial course of map map cannot open full at editor.. thanks

**Comment by 51stHD** [comment]
I have the same issue as Escrimatics now, but this was not always the case as I have successfully used the editor many times in the past.

I'm going to take the advice and record a course around the map, but I don't think that is going to solve the issue...we will see :)

**Comment by 51stHD** [comment]
So I just tested this again.

1st test was with the stock files included with the Autodrive editor for Felsbrun & Ravensport. Both work as they should no problem.

2nd test was with Ellerbach, a mod map rated 
"Top" (I think for good reason) on the Giants modhub[https://farming-simulator.com/mod.php?lang=en&country=us&mod_id=143941&title=fs2019](url)

I applied the above advice and recorded a huge course on just about every road on the map, updated & saved the game. Still the same issue as described by Escrimatics in the opening post.

Please advise, as I find the Editor an essential tool and I really like the Ellerbach map.

**Comment by DreXtrime** [comment]
1. Load the Config
2. Load the Map
3. Make the window bigger
4. Use the scrollwheel to zoom or click and drag anywhere with the mouse

That should make the image bigger.

**Comment by 51stHD** [comment]
Normally that's how it works. But not in this case.

**Comment by 51stHD** [comment]
After a bit more testing, I have managed to get this to work as it should. What was missing was a location. It appear that you need to not only record some pathway, but also add a location to it before the editor recognizes the config.xml

Thanks to all who helped, I'm sorted now.

**Comment by power1jj** [comment]
Is there a thread or a read-me somewhere that tells exactly what files to upload?

**Comment by Efratror** [comment]
@Escrimatics have a look at issue #544. If it still isn't working try to open the editor trough the cmd file that comes with it. It makes a log of the editors action. When you open the config file there shouldn't be any exceptions.

I discoverd that the default course config files miss a group tag in the destination tags. That's why the editor fails when trying to open them.

**Comment by Iwan1803** [comment]
As nothing happened in ~2 weeks... > closed.
