### ISSUE TITLE
Wieso fährt AutoDrive nicht Weiter

### ISSUE THREAD

**Issue by RudiBergfeld** [Stephan-S/FS19_AutoDrive#1019]
AutoDrive Version: 1.0.7.0.34

Der Fahrer von AutoDrive fährt nach dem Laden nicht weiter und zar in dem Modus Abholen und Abliefern läd er am silo Voll und fährt nicht zum abladepunkt er bleibt einfach stehen . Bei der 1.0,6.9 Version tut er es. Was mache ich falsch?
[log.txt](https://github.com/Stephan-S/FS19_AutoDrive/files/3991804/log.txt)

**Comment by Despopanda** [comment]
Ich habe das gleiche Problem wie du, ist ein bug denke ich, es lief alles so toll aber jetzt nicht mehr leider

**Comment by Matze9876** [comment]
Bei mir das gleiche Problem,
er beläd den Trailer stoppt aber dann.
Version 1.0.7.033

**Comment by ratze68** [comment]
Hallo zusammen,

ich Spiele auf der Multimap und kann das Problem oben nicht bestätigen.

Aber: wird der Fahrer am Zielort nicht komplett beladen, weil nicht mehr genügend Material da ist, kommt das spiel ins Stocken. Die FPS rauschen in den Keller, ich kann kaum noch das spiel betätigen. 
Erst wenn ich den Fahrer im AD ausschalte, dann läuft das Spiel wieder normal.
Version 1.0.7.034
Lg Stefan

**Comment by Berzerk70** [comment]
Hallöle

Auf Dedi Server läuft so gut wie nix richtig... nur von A nach B schicken...mehr geht leider nicht....schade....war mal anderst aber seit hier mehr an AD rumwerkelt um so schlimmer wirds

Lg Stefan und Frohe Weihnachten

**Comment by Despopanda** [comment]
Hallo Berzerk

Da muss ich dir total recht geben man will mehr, aber dabei geht das was schon geht nicht mehr, es ist Total schade, und dann dauert alles wieder so lange und das problem ist ja seit der Version 1.0.7.0

**Comment by Lars-LS17** [comment]
ich kann das leider nicht bestätigen. Ich kann alle Schüttgüter einwandfrei beladen und abladen. 
Womit ich mit der neusten Version 1.0.7.0-34 Probleme habe ist mit dem Flüssigkeiten Transport. Wasser oder Gülle funktioniert nicht mehr einwandfrei. Ansonsten kann ich alles einwandfrei Beladen und Entladen.

**Comment by RalfGorden** [comment]
> 
> 
> ich kann das leider nicht bestätigen. Ich kann alle Schüttgüter einwandfrei beladen und abladen.
> Womit ich mit der neusten Version 1.0.7.0-34 Probleme habe ist mit dem Flüssigkeiten Transport. Wasser oder Gülle funktioniert nicht mehr einwandfrei. Ansonsten kann ich alles einwandfrei Beladen und Entladen.

hab die selben Probleme wie du mit den Flüssigkeiten ,mit Schüttgüter läuft es prima

**Comment by Knowen** [comment]
Ich kann mich meinen vorrednern nur anschließen. Im Modus Abholen und Abliefern füllt er SChüttgut auf und bleibt dann stehen. Spiele auf der NF Marsch 4fach mit der aktuellsten Version von AD: 1.0.7.034

**Comment by DrGreene1981** [comment]
Ich möchte mich diesem Issue auch anschließen. Die abholen und abliefern Funktion bei Schüttgut funktionert meistens, aber leider nicht immer...  Bei der Flüssigkeitsverteilung habe ich leider immer Probleme. Er lädt am Ladepunkt auf, fährt zum Abladepunkt, lädt ab und bleibt stehen. Erst, wenn ich manuell auf den "weiterfahren" Button drücke, gehts weiter.

**Comment by GeorgK1988** [comment]
> 
> 
> Ich möchte mich diesem Issue auch anschließen. Die abholen und abliefern Funktion bei Schüttgut funktionert meistens, aber leider nicht immer... Bei der Flüssigkeitsverteilung habe ich leider immer Probleme. Er lädt am Ladepunkt auf, fährt zum Abladepunkt, lädt ab und bleibt stehen. Erst, wenn ich manuell auf den "weiterfahren" Button drücke, gehts weiter.

Bei mir das gleiche! Er lädt, fährt zum abladen, lädt ab und fährt nicht mehr weiter..
