### ISSUE TITLE
Using OSM Java editor with autodrive. A tool for augmentation reality 

### ISSUE THREAD

**Issue by PromGames** [Stephan-S/FS19_AutoDrive#102]
Hi stephan, did you through y about The possibility of exporting the XML in such a format to be able to be read by the OSM for Java. In this GitHub   https://github.com/yankee42/courseplay-osm-converter
is very well explained to use it with courseplay and the export to CP will be already done.

we can use if you want my cp editor to transform routes from CP to autodrive, using the splines defined in the map.

We can also import real roads as autodrive courses, then convert to CP, then convert to splines and using it with spline terrain deformation script, trees and vegetation placement scripts, etc... give the possibility to map makers and real farmers to create real and accurate terrain maps in FS19. It could be used in real active farming through a simple game. Seasons and SoilMod methodology complete the wheel.

A new table of geographic coordinates and dem from lidar and other source information are also available as it is based on real coordinates, and could be used as augmentation reality to active farmers, real weather, soil situation, planning, finance, cp managing vehicles autonomously in a defined field with camera view transmission overlay in the game , with a maximum of 16x size where my editor is able to manage. However I think OSM will be able to manage 64x size.

Dreams for IOT is our future and we have developed by "hobbie" and amazing tool where big multinationals invest a lot. Thanks Giants for the tool, thanks community for the work.

Any feedback will be appreciated and collaboration to stephan will be needed if he think is possible to achieve such a goal. I think at least can be funny and didactic.

Prom

**Comment by Stephan-S** [comment]
Hey,

the AutoDrive course editor is my preferred tool for editing the road network outside of the game.
If anyone wishes to use the configuration otherwise, feel free to create your own parser.
The xml file is easy to read and everything is open source.
You can either look into the lua source code or into the java source code of the editor to understand the internal structure of the xml file :-)
