### ISSUE TITLE
When driving downhill, without a visible obstacle, the collision box brakes and stops the vehicle, same distance uphill, no problem. - Bei Berg-Ab/Talfahrt, ohne erkennbares Hindernis, wird durch Kollisions-Box das Fahrzeug abgebremst und gestoppt, gleiche Strecke Bergauf, kein Problem.

### ISSUE THREAD

**Issue by haamic** [Stephan-S/FS19_AutoDrive#1020]
AutoDrive Version: 1.0.7.0-34
Release or selbsterstelltes zip: selfzip
Karte (falls relevant): Alle
Fahrzeug(art) (falls relevant):

**Beschreibe den Bug**
Karte "HoT online F4rm 2k19", da gibts Feldwege, die schon recht Steil verlaufen.
Bei Berg-Ab/Talfahrt, ohne erkennbares Hindernis, wird durch Kollisions-Box das Fahrzeug abgebremst und gestoppt, gleiche Strecke Bergauf, kein Problem.
Ich möchte nicht ohne Kollissionserkennung fahren, Kann da bitte etwas angepasst werden?
Weshalb denkt AD es wäre ein Hindernis da?
+++++++++++++++++++++++++++++++
Map "HoT online F4rm 2k19", there are dirt roads that are quite steep.
When driving downhill, without a visible obstacle, the collision box brakes and stops the vehicle, same distance uphill, no problem.
I don't want to drive without collision detection, can something be adjusted?
Why does AD think there is an obstacle?

**Falls anwendbar - Schritte mit denen ich den Bug nachstellen kann**

**Screenshots**
![box](https://user-images.githubusercontent.com/28841989/71318681-66ff7980-2494-11ea-8aba-94b5ec1a0798.jpg)

**Comment by ArWeGer** [comment]
Das Selbe Verhalten zeigt sich auf der Dondiego-Map bei allen Brücken, allerdings hier auch bei der Auffahrt auf die Brücke.
Same problem with all bridges on Dondiego map.

**Comment by RalfGorden** [comment]
hallo, vielleicht hilft das ein wenig
https://www.youtube.com/watch?v=EHcOKzutK3U

**Comment by haamic** [comment]
> hallo, vielleicht hilft das ein wenig
> https://www.youtube.com/watch?v=EHcOKzutK3U

Ich kann nur das Terrain selbst bearbeiten, die feldwege sind ja direkt auf dem Boden, das Problem im Video ist da ein separates Objekt, die Brückenauffahrt. Auch hab ich nur bei der Talfahrt das Phänomen. Leider bekomm ich das mit den bordmitteln von Ls19 nicht so richtig dem Weg ein sanft abfallendes Gefälle zu verleihen. Ist ja auch nicht der Sinn eine Karte umzubauen, damit die kollionsbox von AD damit klar kommt. Hier sind die Entwickler gefragt, das AD ein Hindernis erkennt, wenn auch wirklich eins da ist.
