### ISSUE TITLE
AD signaling "end of reload route" to CP too early

### ISSUE THREAD

**Issue by Opa-Andre** [Stephan-S/FS19_AutoDrive#1022]
AutoDrive Version: 1.0.7.0

Release or selbsterstelltes zip: Release
Karte (falls relevant): Alle
Fahrzeug(art) (falls relevant): Verschiedene Düngerstreuer oder Flüssig-Dünger / Herbizid Spritzen 

Problem besteht auch bei Standard-Equipment aus dem Spiel (ohne zusätzliche Mod-Fahrzeuge / Trailer). 
getestete Beispieltrailer aus dem Basis-Spiel: 
- Hardi Navigator 6000 (Spritze für Fl.-Dünger / Herbizid)
oder auch
- Kuhn Axis 40.2 M-EMC-W (Streuer für Kalk / Dünger

Vorgehensweise:
1. Feldkurs zum Düngen / Kalken oder Spritzen auf dem Feld mit CP erstellen. In CP die Option "Use AD for Unload/Refill" aktivieren.
2. Im AD Menü den Modus 4 (Abholen) einstellen 
   - Oberste Zeile: Feldrandzielpunkt
   - Mittlere Zeile: passendes Silo zur Befüllung des Streuers / der Spritze
   - untere Zeile: Füllgut

3. CP starten...
4. Wenn CP erkennt, dass der Tank leer ist, aktiviert es AD zum Befüllen.
5. AD fährt zum Feldrandzielpunkt und dann weiter zum angegebenen Silopunkt (mittlere Zeile in "grüner Schrift")
6. Trailer wird in der Nähe zum Silozielpunkt beim Erreichen des Triggers beladen
7. Gespann fährt wieder los - bis es den eigentlichen Silozielpunkt erreicht (~1 Meter)
8. AD schaltet um auf Fahrt zum Feldzielpunkt (Obere Zeile "grüne Schrift", mittlere Zeile "weisse Schrift")
9. AD fährt zum Feldrandzielpunkt
10. AD "signalisiert" CP dass das Ziel erreicht wurde
11. CP deaktiviert AD und übernimmt das Gespann zur weiteren Feldarbeit

Diese 11 Punkte sind das "erwartete Verhalten" - dies funktionierte auch bis AD Version 1.0.5.x

Hier nun der AD Fehler bei Nutzung Version 1.0.7.0:

Beim Übergang von Punkt 7 zu Punkt 8 signalisiert AD bereits, dass das Ziel erreicht wurde. D.h. an dieser Stelle schaltet CP das AD ab und übernimmt... was natürlich falsch ist, denn das Gespann ist ja noch gar nicht am Feld angekommen.
 
durchgeführter Gegentest:
Schaltet man beim Erreichen des Silos AD manuell ab, belädt den Trailer und aktiviert danach AD wieder, so fährt AD wieder wie geplant zum Feld und übergibt erst dann an CP. Dies bedeutet, dass der Fehler (Sinalisierung an CP) an AD liegen muss.

weitere Info: schaltet man AD manuell aktiv (ohne Nutzung von CP), so wird der AD Kurs vollständig abgefahren.

**Comment by Lars-LS17** [comment]
Hallo,

das Problem hatte ich mit der Version 1.7.0 auch. 
Mit der Entwicklerversion 1.7.0-34 funktioniert es wieder einwandfrei.
Einfach mal die neuste Zwischenversion herunterladen und selber Zippen. Dann solltest du das Problem nicht mehr haben.

**Comment by Opa-Andre** [comment]
Cool, Danke Dir für die Info. Das werde ich dann kurz vor Silvester probieren, wenn ich von meiner Rundreise wieder zurück bin.

**Comment by Opa-Andre** [comment]
Sorry für die späte Rückmeldung, war länger unterwegs als geplant ... habs jetzt auch 1.7.0-34 getestet. Damit funktioniert es wieder ! Ich mach daher mein Ticket gleich zu.
