### ISSUE TITLE
Drescher-Distanz

### ISSUE THREAD

**Issue by GulliGriff** [Stephan-S/FS19_AutoDrive#1024]
Hi und schöne Weihnachten erst mal.
wäre es möglich entweder die Distanz im HUD zu ändern oder anzugeben auf welchem Feld der Drescher abgetankt werden soll? 
Nachdem sich meine Abfahrer nicht bewegt haben, habe ich die Distanz von 300 auf 500 erhöht und dann lief es. Das Problem ist dabei nur, dass er sich ja auch eventuell zu anderen Dreschern auf anderen Feldern machen könnte.

**Comment by ArWeGer** [comment]
Da es ja eine Art Kooperation zwischen den Entwicklern von AD und CoursePlay gibt, und Deine Problemstellung unter Verwendung von CP komplett behoben ist, glaube ich nicht, dass die Entwickler von AD hier so schnell was dran ändern werden ;)
Hast Du schonmal über die Kombi AD + CP nachgedacht? Das funktioniert nämlich wirklich prima :)

**Comment by Iwan1803** [comment]
Da kein weiteres Feedback -> geschlossen.
_Since no further feedback -> closed._
