### ISSUE TITLE
Problem with Trigger

### ISSUE THREAD

**Issue by GulliGriff** [Stephan-S/FS19_AutoDrive#1025]
Mir scheint, dass Autodrive mit einigen Triggern Probleme hat und diese als Hindernis ansieht.
Beispiel:
auf der HotOnlineFarm bleibt er an aktiven Blitzer-Triggern (der mobilen Blitzer) stehen oder auf der Harsefeld gibt es einen Trigger im Hof (bei dem mann "schlafen" gehen kann) bei dem er auch stehen bleibt. Bei deaktivierter Kollisionserkennung hält er nicht an.
Auch fahren Farzeuge nicht los wenn bestimmte Anbaugeräte vorn am Fahrzeug angebracht sind. Bspw. fahrt der Trex600 nicht los.
Ach ja, auch ein zu steiel aufgängen (z.B. Brückenauffahrten) bleibt er stehen.
Vielleicht kann da noch mal nachjustiert werden.

**Comment by haamic** [comment]
Mit den blitzertriggern hab ich keine Probleme. Da rasselt er durch und wird geblitzt. Hab aber jetzt mittels AD eine Verlangsamung eingebaut (kleine Schlenker vorm Blitzer) damit es nicht so teuer wird beim blitzen bzw. Gar nicht geblitzt wird. Dafür hab ich auf der Karte dort an manchen Feldwegen die ziemlich steil verlaufen beim herabfahren das Problem das AD das Fahrzeug stoppt.
Das Problem Konnte ich aber auch durch Änderung des Geländes relativ gut beheben. Vielleicht wird ja an der kollissionsbox noch was verändert. Mal schauen. Ansonsten muss man sich selber irgendwie helfen.

**Comment by Axel32019** [comment]
Ich habe für die Brücken auf der NF 4-fach mal die Kollisions-Box etwas angehoben. Jetzt fährt alles die Brücken hoch und runter auch ohne Geländeanhebung. Wers probieren möchte:
In der Datei AutoDriveFunc.lua nach "boxCenter.y = math.max(getTerrainHeightAtWorldPos(g_currentMission.terrainRootNode, boxCenter.x, 300, boxCenter.z), y) + 1.5 + offsetCompensation" suchen und die 1.5 durch 2 ersetzen. Aber Achtung wenn man es höher setzt werden möglicherweise die KI-Autos nicht mehr erkannt!

**Comment by GulliGriff** [comment]
Verkehr mache ich eh aus, wenn der vernünftig wäre würde ich ihn an lassen aber fahrzeuge die stumpf auf der spline fahren und 1000 mal stärke sind als mein schlepper... dann lieber ohne
ok, die box anzuheben ist ne Möglichkeit, probier ich gleich mal, danke

**Comment by RalfGorden** [comment]
vielleicht hilft das ein wenig
https://www.youtube.com/watch?v=EHcOKzutK3U&t=120s

**Comment by TyKonKet** [comment]
**Hello, Thank you for opening this issue!**
Since we have just released [the new refactored version of AutoDrive](https://github.com/Stephan-S/FS19_AutoDrive/releases/tag/1.1.0.0), we can no longer provide any feedback or support for open bug reports related to the old code base.
If the problem persists, please reopen a new issue with all the required details.
Thank you for understanding and we hope you continue enjoying our mod 😄
