### ISSUE TITLE
MP: No saving of vehicle settings (Keine Speicherung der Fahrzeugeinstellungen)

### ISSUE THREAD

**Issue by kurtlohnunternehmen** [Stephan-S/FS19_AutoDrive#1027]
AutoDrive Version: 1.0.7.0
Release or selbsterstelltes zip: Release

Nach dem Beenden des Spieles werden die Einstellungen für das jeweilige Fahrzeug nicht gespeichert. Man muss dann nach dem Neustart alle Einstellungen für jedes Fahrzeug komplett neu eingeben (also alle Zielpunkte und des weiteren).

After finishing the game, the settings for the respective vehicle are not saved. After restarting the game you have to enter all settings for each vehicle completely new (i.e. all destinations and so on).

**Comment by Iwan1803** [comment]
Single- oder Multiplayer?

**Comment by kurtlohnunternehmen** [comment]
Multiplayer! Singleplayer ok. Hätte ich mir eigentlich auch denken können, dass es auf dem Server nicht gesichert wird. Schade.

**Comment by kurtlohnunternehmen** [comment]
Jetzt speichert er doch. Seltsam. Naja. Hiermit schliesse ich.

**Comment by mdbguy** [comment]
update in case anyone is searching with similar issue - my habit was to name the mod zip folder like ZZZ_FS19_AutoDrive1070.zip.  This interfered with loading vehicle specific setting.  After renaming mod zip folder to FS19_AutoDrive.zip AD settings will save and load properly.

**Comment by Dzi4d3k** [comment]
That may by useful if you know what mod have to be loaded first, as Giants engine loads mods alphabetically, so some mods that add specializations to vehicles have to be loaded last. However I doubt that this is needed for AD mod.
