### ISSUE TITLE
Create a routine to connect autodrive targets with courseplay recorded field works

### ISSUE THREAD

**Issue by PromGames** [Stephan-S/FS19_AutoDrive#103]
Hello stephan,

A good feature for autodrive could be the benefits for the player to be able to have a routine to have targets as commands executing a pre-recorded courseplay course, you know they are text indexed, and run it using the console commands 

I think this can be use for field work courses like harvesting or plowing, seeding, with specific width and not increasing the autodrive XML file size because we benefit from courseplay that has own commands defined at console level.

 Autodrive can be used as a task programmer of consecutive targets that is really missed in course play.

Could be a nice integration.

Prom

**Comment by Stephan-S** [comment]
Hey, 
the courseplay devs and I are in contact now and are looking for feedback on how to best integrate some features.
Could you post your thoughts over here, so we can discuss them and plan which features should be implemented? I will close this issue over here and it might result in a new project if you post a good explanation of your thought here:
https://github.com/Courseplay/courseplay/issues/3820

Best regards,
Stephan
