### ISSUE TITLE
Autodrive?

### ISSUE THREAD

**Issue by seeske123** [Stephan-S/FS19_AutoDrive#1030]
What is going with Autodrive? Is there a clash in the team? Or is it just there is no time anymore. It has been a month before a new update. Or we are going to be surprisied by a complete  new Autodrive. Furthermore thanks for a almost perfect Mod. Happy New Year to all and many nice houres with the play. Hans

**Comment by Merrlin** [comment]
The last changes in the code was on Dec 18th. So nothing to worry about.

**Comment by Iwan1803** [comment]
Holiday, Christmas, New Year,... time to relax 😎
