### ISSUE TITLE
Feature Request: Possibility to control the train, train to silos - Möglichkeit den Zug zu steuern, Zug Silos anfahren

### ISSUE THREAD

**Issue by haamic** [Stephan-S/FS19_AutoDrive#1031]
**Is your feature request related to a problem? Please describe.**

**does not concern a problem, feature request:**
Will it be possible to control the train in the future? It only has to be able to stop at the different destination silos. Or can I somehow activate the AD HUD when I am on the train?
Greets Micha
++++++++++++++++++++++++++++++++++
**betrifft kein Problem, Feature Anfrage:**
Wird es zukünftig mal möglich sein, den Zug anzusteuern? Er muss ja nur an den verschiedenen Ziel Silos halten können. Oder kann ich irgendwie den AD HUD aktivieren, wenn ich im Zug sitze?
Gruss Micha

**Comment by Iwan1803** [comment]
https://github.com/Stephan-S/FS19_AutoDrive/issues/1296

**Comment by Iwan1803** [comment]
Sorry, but no, not possible.
