### ISSUE TITLE
pipe offset more options

### ISSUE THREAD

**Issue by crimso** [Stephan-S/FS19_AutoDrive#1032]
Hello,

I would like to ask If its possible to make pipe offset option more adjustable? I mean now the max is 5m and -5, but for example, I am using the combine from JHHG modding team and somehow the automatic recognization of the pipe its not working. The offset I can increase to 5m but its not enough If the combine pipe is 6.9m or 7.9m long. So it is possible to somehow put more offset options?

Thank you

**Comment by Mannie313** [comment]
Ich glaube du must vom rohr ausgehen nicht vom drescher.
Ich hab bei mir Rohrversatz 0m stehen und es klappt.

MFG Mannie313

**Comment by crimso** [comment]
Hello,

If I put 0 the tractor will directly drive to the harvester from backside.

**Comment by Lars-LS17** [comment]
Hello,

then is this a bug in the harvester. That isn´t a Problem of AutoDrive.

**Comment by Iwan1803** [comment]
If the mod of the harvester is not correct, AD is not responsible for that.
