### ISSUE TITLE
FS19_AutoDrive/scripts/HudElements/PullDownList.lua:571: attempt to compare number with nil

### ISSUE THREAD

**Issue by Blackjack155** [Stephan-S/FS19_AutoDrive#1033]
Ich habe das Problem das ich AD garnicht verweden kann da bei mir dieser ERROR kommt 
Ich kann kein Kurs laden  vlt kann man mir helfen 
[log.txt](https://github.com/Stephan-S/FS19_AutoDrive/files/4017428/log.txt)

**Comment by Iwan1803** [comment]
Single- oder Multiplayer?
Lad dir mal die aktuellste Version (Release, nicht ZIP) und versuch es dann noch mal.
Du solltest auch mal einen Blick auf die Warning und Error im Log werfen.

**Comment by Blackjack155** [comment]
ist die Aktuelle

**Comment by Mannie313** [comment]
Welche Version hast du. Schreib die mal bitte hier rein. Ich hab die Version 1.0.7.0-34.

Aus ein paar kleinen Fehler kann ich nichts sagen ausser das es ohne Errors läuft.

MFG Mannie313

**Comment by Blackjack155** [comment]
@Mannie313  1.0.7.0 das is die letze version....

**Comment by Mannie313** [comment]
Wen du meinst.

**Comment by Mannie313** [comment]
Hier ein Screenshot mit der aktuellen Version.

![fsScreen_2020_01_05_22_05_53](https://user-images.githubusercontent.com/3021040/71786055-a9ce5f00-3007-11ea-8241-b4a998f31b1e.png)

**Comment by Blackjack155** [comment]
weiß nicht was du jetzt hier klugscheißern willst aber lass es lieber du hilft keinen damit

das ist die gleiche version die ich habe ....

**Comment by Iwan1803** [comment]
Er will dir helfen, die richtige Versionsnummer anzugeben.
1.0.7.0 ist die letzte Release-Version, aber "intern" sind wir ggfs. schon ein bisschen weiter (1.0.7.0-xx).
Welche Version wird dir also ingame angezeigt?

**Comment by Justice-Molton** [comment]
Der Kollege ist bei Courseplay auch unerwünscht, da er immer nur Terror gemacht hat. Lass es doch einfach sein @Blackjack155.

**Comment by Blackjack155** [comment]
> Er will dir helfen, die richtige Versionsnummer anzugeben.
1.0.7.0 ist die letzte Release-Version, aber "intern" sind wir ggfs. schon ein bisschen weiter (1.0.7.0-xx).
Welche Version wird dir also ingame angezeigt?

wie schon mehrfach erwähnt die aktuellste version 1.0.7.0-34

**Comment by Blackjack155** [comment]
> Der Kollege ist bei Courseplay auch unerwünscht, da er immer nur Terror gemacht hat. Lass es doch einfach sein

was willst du hampelman :D Wenn man keine ahnung hat einfach mal die F..... Halten nä.!

**Comment by Iwan1803** [comment]
@Blackjack155 
So ein Benehmen ist hier nicht erwünscht. Betrachte dich als verwarnt.
