### ISSUE TITLE
MP: cant edit routes

### ISSUE THREAD

**Issue by Loradan** [Stephan-S/FS19_AutoDrive#1037]
AutoDrive Version: 1.0.7.0
Release or selbsterstelltes zip: Release
Karte (falls relevant): Saxonia
Fahrzeug(art) (falls relevant):

**Beschreibe den Bug**
Beim Einfahren sowie besonders beim Editieren von Routen scheint es im MP noch Probleme zu geben. Das Einfahren funktioniert zwar grundsätzlich, wenn von den anwesenden Spielern nur einer einfährt und nicht mehrere gleichzeitig. Möchte ich dann allerdings den Kurs abändern, Kurven besser gestalten etc., kann ich die Wegpunkte zwar löschen und das Kurvenstück neu aufnehmen, aber sobald ich das kurze neue Kurvenstück mit dem vorhandenen Streckennetz verbinden will, findet AD irgendwelche Verbindungspunkte irgendwo in der Strecke und nicht die des neuen Kurventeils.
Ich habe das Gefühl, dass im MP, sobald ich ein Netz editieren will, diese neuen Teile nicht erkannt werden und deshalb auch nur Teile der bereits vorher vorhandenen Strecke als Punkte erkannt werden.. Als ob es nicht richtig aktualisiert wird. Im SP funktioniert alles wunderbar.

Wir spielen auf einem Dedi Server von Nitrado. Es macht auch keinen Unterschied, ob ich als Admin Kurse ändere oder als normaler User auf der MP Karte.

**Comment by kurtlohnunternehmen** [comment]
Haben auf dem Dedi Server das Indentische Problem.

**Comment by jspring0811** [comment]
Same problem.  Editing and then trying to connect two adjacent points connects to some point way off in the distance and as a reverse line.  Also pressing neighbors button appears to do nothing.  Also pressing recalculate restores all of the points that I deleted while editing (resulting in both the old points and the new messed up points all existing).

**Comment by Loradan** [comment]
@jspring0811 100% the same behavior on our server :-)

**Comment by StuartLivings** [comment]
Duplicate/directly related to #1021, I think.

**Comment by TyKonKet** [comment]
**Hello, Thank you for opening this issue!**
Since we have just released [the new refactored version of AutoDrive](https://github.com/Stephan-S/FS19_AutoDrive/releases/tag/1.1.0.0), we can no longer provide any feedback or support for open bug reports related to the old code base.
If the problem persists, please reopen a new issue with all the required details.
Thank you for understanding and we hope you continue enjoying our mod 😄
