### ISSUE TITLE
Don't load silo

### ISSUE THREAD

**Issue by Blackjack155** [Stephan-S/FS19_AutoDrive#1038]
Multimap 2.3

Grass should be loaded which does not happen 

![20200105160735_1](https://user-images.githubusercontent.com/26688591/71782046-cc478480-2fd5-11ea-81ea-802051cd870a.jpg)

**Comment by Bandesss** [comment]
Du bist im falschen Modus.... du brauchst Pfeil nach unten und Laden nicht entladen 
Gruß

**Comment by Blackjack155** [comment]
wie er soll doch dort laden?

**Comment by Iwan1803** [comment]
Es gibt leider ingame 3x Gras in der Auswahl: 1x für Ballen, 1x für Gras auf dem Feld und 1x für Gras in einem Silo. Leider heißen alle 3 einfach nur "Gras" in der Auswahl.
Daher kann es sein, das du den "falschen" Gras-Eintrag zum Beladen ausgewählt hast.
Bei mir ist meistens der 1. Eintrag in der Liste der fürs Gras aus dem Silo.

**Comment by Blackjack155** [comment]
Daran liegt es nicht Ad bleibt egal wie  einfach stehen habe es acu mit einem anderen mod silo Probiert es geht nicht bzw hat was vlt mit dem Fermenter der Map zu tun aber da kann ich nix machen wenn der modder die map so schlecht gebaut hat

**Comment by Blackjack155** [comment]
![20200105203047_1](https://user-images.githubusercontent.com/26688591/71827700-1a758a00-30a1-11ea-9214-342bf5d0e3f2.jpg)
![20200105203513_1](https://user-images.githubusercontent.com/26688591/71827692-19445d00-30a1-11ea-97eb-ebe3b54ba319.jpg)
![20200105182245_1](https://user-images.githubusercontent.com/26688591/71827693-19dcf380-30a1-11ea-9708-4391f5f5785e.jpg)
![20200105201619_1](https://user-images.githubusercontent.com/26688591/71827696-19dcf380-30a1-11ea-92fe-b4a97b449c49.jpg)
![20200105201621_1](https://user-images.githubusercontent.com/26688591/71827697-19dcf380-30a1-11ea-91af-ad7020d96f3e.jpg)
![20200105202826_1](https://user-images.githubusercontent.com/26688591/71827699-1a758a00-30a1-11ea-9ac8-24a35eeb4ed7.jpg)

**Comment by Blackjack155** [comment]
AutoDrive Version: 1.0.7.0.
Karte (falls zutreffend): MutliMap
Fahrzeug / Typ (zutreffend): Case  Standart Fzg. und Fliegl TMK266 Bull https://www.farming-simulator.com/mod.php?lang=de&country=de&mod_id=143739&title=fs2019

** Beschreibe den Bug **
Transport von Gras vom Silo zu dem Fermentierer nicht möglich da AD nicht richtig beläd und los fährt

**Screenshots**
Siehe Oben

**Comment by Blackjack155** [comment]
Hilft der fehler vlt?
dataS2/character/humans/pedestrians/pedestrianAnimation.i3d (26.28 ms)
Error: Failed to open xml file 'C:/Users/chris/Documents/My Games/FarmingSimulator2019/mods/FS19_AutoDrive/modDesc.xml'.
Load mod: FS19_AutoDrive (Hash: 95b24e5ffadc51cf0cc9f5f48ac67280)
Error: Missing descVersion attribute in mod FS19_AutoDrive

**Comment by Iwan1803** [comment]
Klingt nach einem fehlerhaften Download.

**Comment by Blackjack155** [comment]
Fehler wurde immer noch nicht behoben?

**Comment by Iwan1803** [comment]
Sorry, aber meine Glaskugel ist in der Reinigung und normalerweise beantworte ich so provokante Beiträge auch nicht, denn der Ton macht die Musik.
Außerdem sitzt hier niemand rum und wartet nur darauf, das der kleine Jack mit einem Problem um die Ecke kommt und wir ihm alles an notwendigen Infos aus der Nase ziehen....

Lt. deinem Beitag von vor 16 Tagen scheint der Mod auf deinem Rechner nicht sauber vorhanden zu sein, denn solche Fehlermeldungen habe ich bei mir nicht. Hast du ihn zwischenzeitlich noch mal neu runtergeladen und dann auch kontrolliert, das er wirklich ordnungsgemäß und auch nicht doppelt vorhanden ist?
Wenn das der Fall **und** das Log fehlerfrei ist, dann solltest du die Entnahme von Gras mal mit einem Standardanhänger versuchen, falls es mit dem Modanhänger immer noch nicht klappt.

Der Fehler ist übrigens nicht immer bei AD zu suchen, denn es gibt so einige Mods (Fahrzeuge, Anhänger, Gebäude,...), die nicht so ganz sauber erstellt worden sind und somit vom Standard abweichen. Soll Stephan nun wirklich für jeden "fehlerhaften" Mod irgendwelche Krüken in AD einbauen?

**Comment by Iwan1803** [comment]
Da kein weiteres Feedback -> geschlossen!
