### ISSUE TITLE
problems with trigger / Wäre toll Trigger zu fixen

### ISSUE THREAD

**Issue by Blackjack155** [Stephan-S/FS19_AutoDrive#1039]
AD erkennt trigger bzw wege nicht richtig er fährt an ein silo heran beläd fährt aber nicht weiter das wär wichtig mal zu fixen

**Comment by Bandesss** [comment]
Ja geht uns auf dem Server auch so ... aktuellste Version von AD

**Comment by Iwan1803** [comment]
Das tritt bei mir meistens bei Non-Standardgebäuden auf (z.Bsp. Gebäude von GlobalCompany).
Wie ist das bei euch?

**Comment by Blackjack155** [comment]
is aber merkwürdig das es aber bei anderen geht das is ja das ganz große Problem. Ich weis einfach nicht mehr weiter was ich noch testen soll  mir vergeht einfasch ko plett die laune LS zu spielen da ich ein einzigen tag bis jetzt durch weg spielen konnte ohne das irgendwas nicht funktioniert hat

**Comment by Iwan1803** [comment]
Für was hat Stephan eigentlich diese schönen Templates kreiert, wenn sie nicht genutzt werden?
Sollen wir eine Hellseherin beauftragen oder woher sollen die notwendigen Infos für die Dev kommen?

**Comment by Blackjack155** [comment]
#1038

**Comment by Iwan1803** [comment]
Ok, also ist das Issue hier ja doppelt und dann mach ich das mal zu,
