### ISSUE TITLE
Silos mode autodrive fs19

### ISSUE THREAD

**Issue by Starburger511** [Stephan-S/FS19_AutoDrive#104]
Hello. 
Currently implemented autodrive mod silage?

**Comment by Anonymous-any** [comment]
Yup I wanted to ask the question too :)

**Comment by Stephan-S** [comment]
Sorry, this mode won't make it back into the FS19 version as it simply doesn't really fit to the rest of the mod. At least in my opinion :-)
And in FS19, I never really had to compact the silo as I used to in FS17.
All the compacting is mostly done when unloading the chaff into the silo anyhow
