### ISSUE TITLE
Fährt Häxler Falsch ab

### ISSUE THREAD

**Issue by Blackjack155** [Stephan-S/FS19_AutoDrive#1040]
AutoDrive Version: 1.0.7.0
Er fährt hinter denn Häxler  So das er kaum los fahren kann und der AD fahrer nur schneckentepo fährt
Eilg solte er daneben fahren was er nicht tut 
![20200107172810_1](https://user-images.githubusercontent.com/26688591/71911009-3cd7d800-3173-11ea-9a0a-64a373d79603.jpg)

**Comment by Knowen** [comment]
Muss ja nicht mal neben dem Häcksler fahren, es reicht wenn er näher dran ist so dass der Hänger befüllt wird.

**Comment by Blackjack155** [comment]
Wie man aber sieht geht das nicht da er zu weit weg ist im diesen zu füllen. Er stockt nur und kommt nicht in fahrt, weswegen ich ihn dann druch CP austaschen musste. Angeblich solte das aber geht laut eines Tuts aber scheinbar nur bei einen Maisgebiss und nicht bei Schwad ablage.

**Comment by Knowen** [comment]
Mit meinem Beitrag wollte ich den Entwicklern eine andere mögliche Alternative vorschlagen. 

Beim Maisgebiss kommt es aber auch zu einem Stockenden fahrverhalten. Der Drescherabfahrmodus von CP wird gerade überarbeitet und in der momentanen, verfügbaren Version kommt es mehr zu fehlern als alles andere.

**Comment by Iwan1803** [comment]
Das Problem hatte ich auch. Eine (temporäre) Lösung war ein Häcksler mit einem langen Rohr.

**Comment by Blackjack155** [comment]
> Das Problem hatte ich auch. Eine (temporäre) Lösung war ein Häcksler mit einem langen Rohr.

Naja ehr ist es doch ein Fehler da er Normal neben Ihn fährt und nur hinter Ihm wenn er eine Schneise durchs Feld Macht (Im Realen ist es so) Versteh aber nicht warum er das hir nicht macht?

**Comment by RK54** [comment]
vielleicht sollte man mal seine Einstellungen überprüfen im CP.
Ich fahre mit 2 Abfahrer und einem Hächsler, ohne Probleme.
Meine Abfahrer fahren neben dem Hächsler, wie es sein soll.
Ich sage immer, nicht nur bei der Arbeit denken, beim Spielen auch

Gruß RK54

**Comment by Iwan1803** [comment]
@RK54 
Steuerst du deine Abfahrer rein per CP oder per AD?
Wenn nur per CP, dann bist du hier falsch.
Wenn per AD, dann sag doch einfach welche Einstellung man kontrollieren sollte anstatt uns mit dummen Sprüchen zu kommen.

**Comment by Justice-Molton** [comment]
@RK54 wie sind den deine Einstellungen? Magst Du mal einen Screenshot hochladen?

**Comment by RK54** [comment]
@ Iwan1803,
ich hatte das AutoDrive übersehen, kann doch passieren, oder?
von mir kommen nie dumme Sprüche, im gegensatz zu anderen Usern hier

**Comment by Blackjack155** [comment]
> ich hatte das AutoDrive übersehen, kann doch passieren, oder?
von mir kommen nie dumme Sprüche, im gegensatz zu anderen Usern hier 

:D Wir sind im AD issues Logisch das es um AD geht ....

**Comment by RK54** [comment]
zu anderen Usern hier, warst du gemeint

**Comment by Blackjack155** [comment]
Also einstellung sind Korekt, und AD kann man auch nicht einstellen wie er Abfahren soll wie bei CP. Ad macht das also selber ergo fehler bei der Erkennung der Positzion. es giebt auch keine einstellung im AD dafür nur. Daher die frage @Iwan1803  Warum fährt er denn so

**Comment by Blackjack155** [comment]
> zu anderen Usern hier, warst du gemeint
geh einfach ganz werlich du nervst und bist nicht Hilfreich Tschüß!!!

**Comment by Iwan1803** [comment]
@RK54 
> Ich sage immer, nicht nur bei der Arbeit denken, beim Spielen auch

Das ist schon ein dummer Spruch, in meinen Augen 😉
Es bleibt also bei der temporären Lösung: Häcksler mit langem Rohr.

**Comment by Blackjack155** [comment]
> Das ist schon ein dummer Spruch, in meinen Augen 😉
Es bleibt also bei der temporären Lösung: Häcksler mit langem Rohr.

Das aber nicht die Lösung? Erklär mir doch bitte Warum der beim Maisgebiss seitlich fährt und dort nicht? Wie erkennt er denn die Posi. das er sich dort einfindet?

**Comment by Iwan1803** [comment]
Es ist eine temporäre Lösung, bis @Stephan-S & Co. das Problem geprüft haben, um es dann auch hoffentlich zu fixen.
Wenn ich das programmiert hätte, könnte ich es vielleicht erklären.

**Comment by Blackjack155** [comment]
Na wie fahren die Faherer bei dir mit schwad und Häxler?

**Comment by Iwan1803** [comment]
Beim letzten mal habe ich einen Claas-Häcksler mit dem längsten Rohr gehabt und Ablader ohne Frontgewicht und keinem all zu langen Anhänger.
https://www.youtube.com/watch?v=2EW5jVGQjIQ&t=270s
Da erkläre ich mein Vorhaben und was mir im LP am Vortag passiert ist. 
https://www.youtube.com/watch?v=2EW5jVGQjIQ&t=5209s
Hier sieht man dann das Ergebnis.

**Comment by Iwan1803** [comment]
Falls sich jemand traut, auf seinem Rechner die Sourcen zu manipulieren:
.\FS19_AutoDrive\scripts\AutoDriveCombineMode.lua
Zeile 635, am Ende aus der 6 einfach mal eine 5 machen:
![image](https://user-images.githubusercontent.com/47528836/72183262-c98dca80-33ed-11ea-9de2-683fb09856fe.png)
Bei mir klappt es nun mit einem langen Anhänger und dem Claas-Drescher mit sehr langem Rohr problemlos.

**Comment by Iwan1803** [comment]
@Stephan-S hat nun eine Option für den Abstand in AD integriert. Vielen Dank dafür!

**Comment by Justice-Molton** [comment]
Fährt der Abfahrer denn jetzt auch auf der Seite? Kann es gerade nicht testen, würde mich aber interessieren :)

**Comment by Iwan1803** [comment]
Das macht er auch jetzt schon. Ich habe das gestern getestet und bin gerade mit der neuen Version auch dran.

**Comment by Justice-Molton** [comment]
Also mit der Anpassung die Du gemacht hast?

**Comment by Iwan1803** [comment]
Er hat es gestern schon vor und nach meiner Änderung gemacht als auch mit der heutigen AD-Version.

**Comment by Justice-Molton** [comment]
Cool, danke für deine Auskunft

**Comment by Iwan1803** [comment]
Version 1.07.0-35:
Abstand Abfahrer zu Häcksler kann nun in AD eingestellt werden.
_The distance from the driver to the chopper can now be set in AD._

**Comment by Blackjack155** [comment]
Danke Schön :)
