### ISSUE TITLE
Youre still here Stephan?

### ISSUE THREAD

**Issue by C43AMG** [Stephan-S/FS19_AutoDrive#1043]
Nothing heard from you nearly 2 months, all fine for you?

**Comment by Despopanda** [comment]
yes I agree with you, it would be nice if somehow information was given here again

**Comment by Iwan1803** [comment]
2 months? Last update is only 24 days old.... 🙄
I wrote @Stephan-S on Discord, but no feedback till now.

**Comment by Stephan-S** [comment]
Hey, yeah I'm still here guys :-) I just hadn't had much time lately to develop AutoDrive. And now that I'm sort of out of the game for that long I find it a bit hard to jump back in.

So for now you are stuck with the version that works best for your needs and I will start working on AutoDrive again when I can get myself motivated again :D 
I've spent about a full year's worth of freetime on AutoDrive and I'm a bit worn out. But I'm sure I'll be back soon enough, don't worry.

If anyone is interested, I currently play a little bit of Screeps when I'm at my PC (https://screeps.com/)
An MMO for programmers, where I can watch my little programmed ant farm keep working and fighting away :D

**Comment by PromGames** [comment]
Hi, Stephan, you created such a nice program and integration with courseplay and global company that now fs is a much better game. Thank you and let’s expect you get new challenges over here and have your interest back.

**Comment by enisbr** [comment]
sou muito agradecido por autodrive obrigado Stephan-S
