### ISSUE TITLE
Viele Warnungen

### ISSUE THREAD

**Issue by Bandesss** [Stephan-S/FS19_AutoDrive#1044]
AutoDrive Version: Neuste
Release or selbsterstelltes zip: selber gepackt
Karte (falls relevant): Alle
Fahrzeug(art) (falls relevant):

**Beschreibe den Bug**
Bekommen viele Warnungen hoff es kann mir jemand Helfen.
[log.txt](https://github.com/Stephan-S/FS19_AutoDrive/files/4044784/log.txt)

**Falls anwendbar - Schritte mit denen ich den Bug nachstellen kann**

**Screenshots**
Falls relevant, bitte Screenshots beifügen

**Comment by ArWeGer** [comment]
Die Warnings haben ja alle nichts mit AutoDrive zu tun.
Vielleicht solltst Du das beim entsprechenden Modder melden. 
Die meisten Deiner Warnings hängen mit nicht bekannten Fruchttypen zusammen.

**Comment by Bandesss** [comment]
2020-01-10 10:56 Error: Running LUA method 'update'.
2020-01-10 10:56 C:/users/ronny/Meine Dokumente/My Games/FarmingSimulator2019/mods/FS19_AutoDrive/scripts/AutoDriveCombineMode.lua:827: attempt to index a nil value
2020-01-10 10:58   Error: [AutoDrive] Encountered a problem during initialization - shutting down

Das ist doch aber Autodrive oder

**Comment by rgoe** [comment]
Und wo ist dieser Fehler (das ist keine Warnung) in Deinem Logfile zu finden? In dem, das Du hochgeladen hast jedenfalls nicht...
Im Zusammenhang mit dem o.g. Fehler solltest Du noch ergänzen wann genau unter welchen Bedingungen, mit welchem Gerät usw. er aufgetreten ist - je präziser Deine Angaben, umso eher kann Dir das AD-Team dann ggf. auch weiterhelfen und der Fehlerursache auf die Spur kommen.

**Comment by Axel32019** [comment]
Zu "Error: [AutoDrive] Encountered a problem during initialization - shutting down"
Der wird geloggt wenn das eingestellte Ziel im Streckennetz nicht erreichbar ist (Ziel wird nicht grün). Dann bitte Strecke zum Ziel auf Unterbrechungen, vergessene Verbindungen, zu große Winkel (>90°) beim Abbiegen prüfen und anpassen!

**Comment by Bandesss** [comment]
Jepp das wars vielen dank
