### ISSUE TITLE
Trailer starts to unload to early

### ISSUE THREAD

**Issue by Knowen** [Stephan-S/FS19_AutoDrive#1045]
AutoDrive Version: 1.0.7.0-35
Release or custom zip: Release
Map (if applicable): NF Marsch 4fach
Vehicle/type (applicable): Axion 990 with a Cargos trailer

**Describe the bug**
The trailer starts to early to unload. I haven't used this AD feature in a while, so I can't say if it is because of the distance options that broke something or something else.

**If applicable - Steps to reproduce the behaviour**

**Screenshots**
![fsScreen_2020_01_11_13_09_50](https://user-images.githubusercontent.com/47173160/72204037-f7b5ed80-3473-11ea-96d6-fb3d363508f2.png)

Log: 
[log.txt](https://github.com/Stephan-S/FS19_AutoDrive/files/4049301/log.txt)

**Comment by Iwan1803** [comment]
The screenshot shows 1.0.7.0-34, you wrote 1.0.7.0-35...
There are a some warnings in the log, which you should fix first (autoload, trailer, ...).
Did you try a different tractor or trailer?

**Comment by Knowen** [comment]
It was the newest version. I downloaded it today before Stephan updated the version number. I haven't tested with a different trailer/tractor combination. gotta do it now.

**Comment by mauma123** [comment]
It makes me too sameking behavior. When i unload grass to the bunker silo, it start unloading in right time, but when tractor is at halfway it start increase speed and unload last ones outside front of bunkersilo.
This happen in every map what i have tryed with mods or without.

**Comment by Iwan1803** [comment]
I have tried it on NFM 4x and Felsenbrunn, with default and modded tractors and trailers, with default and modded silos, with GC fermenter and other productions. It has worked all the time without any error or problem.
Maybe you are using a mod which is causing these problems (f.e. a speed control mod).

Try a new game on a default map (Ravenport, Felsenbrunn) without any mod except AD and maybe EasyDevControl. Don't change anything in AD and then try to unload something in a default silo.
If this works, then add 1 mod and try again.
If it doesn't work, then we need more informations (log, activate debug in AD and make screenshots, etc.).

**Comment by Iwan1803** [comment]
If you need a working download of AD:
[FS19_AutoDrive-1.0.7.0-35.zip](https://github.com/Stephan-S/FS19_AutoDrive/files/4050790/FS19_AutoDrive-1.0.7.0-35.zip)

**Comment by Knowen** [comment]
Hello,
wasn't able to test it yet. Quite bussy atm.
hopefully im able to make a quick test run this weekend.

**Comment by Knowen** [comment]
Played a few hours today. 
There is no issue anymore.

**Comment by Iwan1803** [comment]
Great and thx. for the feedback!
