### ISSUE TITLE
V. 1.0.7.0.-35  Fehlende Einstellung Häxler Abfahren 

### ISSUE THREAD

**Issue by Blackjack155** [Stephan-S/FS19_AutoDrive#1046]
V. 1.0.7.0.-35 
Man kann immer noch keine Angaben ändern für denn Häxler Abfahren obwohl gesagt wurde es wurde gefixt bzw. gezeigt.

![20200111230431_1](https://user-images.githubusercontent.com/26688591/72211159-d03c4080-34c6-11ea-9a63-2e0f774ab0ba.jpg)

und anzeige fehler beim Display 
![grafik](https://user-images.githubusercontent.com/26688591/72211235-0cbc6c00-34c8-11ea-9da1-91660c4cb07b.png)

[log.txt](https://github.com/Stephan-S/FS19_AutoDrive/files/4049943/log.txt)

Edit.
Mir is aufgefallen das er die aktuelle Version nicht Läd. Ich kann diese 100x Herunterladen und hinzufügen er bleibt bei 34. Scheinbar läd dort was nicht richtig in Euren Mod.

**Comment by Iwan1803** [comment]
Seltsam, bei mir hat es funktioniert:
![fsScreen_2020_01_11_14_42_47](https://user-images.githubusercontent.com/47528836/72211941-121fb380-34d4-11ea-8a81-8afd2290bcbd.jpg)
![fsScreen_2020_01_11_15_00_38](https://user-images.githubusercontent.com/47528836/72211952-43987f00-34d4-11ea-863f-1b7236869d1b.jpg)

**Comment by Mannie313** [comment]
@Iwan1803 mir ist aufgefallen das bei ihm 2 mal autodrive registriert wird. Kannst du damit was anfangen.

MFG Mannie313

**Comment by Iwan1803** [comment]
Ich sehe es nur einmal im Log...
Dennoch scheint der Download nicht ganz sauber funktioniert zu haben. Daher habe ich meinen Download mal angehangen.
[FS19_AutoDrive-1.0.7.0-35.zip](https://github.com/Stephan-S/FS19_AutoDrive/files/4050790/FS19_AutoDrive-1.0.7.0-35.zip)

**Comment by Blackjack155** [comment]
Nein Ändert nichts. Weis nicht warum das neue Update so Probleme macht.

Aber man hat ja gelesen das Stefan eh mom nicht an denn Mod dran sitzt bzw eine lust hat drauf. 
Dann kann man ja ne weile warten auf eine behebung.

**Comment by Iwan1803** [comment]
Starte mal eine neue Map (Ravenport, Felsenbrunn) ohne Mods, außer AD natürlich.
Kauf dir dann einen Trecker und prüf es noch mal.

**Comment by Blackjack155** [comment]
Fehler besteht weiter hin. Warum zeigt der aus diesen fehler mit 34-35 an das die zahlen sich überlappen?

**Comment by Iwan1803** [comment]
Kontrollier mal bitte, ob du AD nicht zufällig mehrfach im mods-Ordner hast (1x als Ordner, 1x als Zip,...).

**Comment by Blackjack155** [comment]
gut habe denn fehler aus irgend einen grund hatte ich 2x AD drin aber dies hies anders warum auch immer :D 
Ich weis nicht wie der da rein kamm vlt Mapmod mit drin denn ich damals hatte wer weiß.
Ich schließe dann das ganze wenn es okay ist.

**Comment by Mannie313** [comment]
@Iwan1803 hatte ich doch recht gesehen das AD 2 mal registriert worden ist.

MFG Mannie313
