### ISSUE TITLE
Wegpunkte ohne Fahrzeug bearbeiten / Edit waypoints without vehicle

### ISSUE THREAD

**Issue by MadDocLP** [Stephan-S/FS19_AutoDrive#1049]
Hallo.

Ich habe eigentlich nur eine kurze Frage. Ist es möglich die Wegpunkte auch ohne in einem Fahrzeug zu sitzen zu bearbeiten oder zu erstellen? Würde denke ich um einiges schneller teilweise gehen wenn man sehr nah beieinander liegende bedenkt. Vielleicht auch wenn man was an der modDesc ändert?

Danke schon mal. Gruß.

---

_Hi there._

_I actually only have one quick question. Is it possible to edit or create the waypoints without sitting in a vehicle? I think I would go a lot faster at times if you consider that they are very close together. Maybe even if you change something at the modDesc?_

_Thanks in advance. Greeting.
**_Translated with Google Translator_**

**Comment by betrox007** [comment]
for me i use Autodrive course editor... outside of game for editing course or add course, add destination,add node etc..

**Comment by MadDocLP** [comment]
Hört sich interessant an. Werde ich mal ausprobieren. Kannte so ein Programm bisher nur für CoursePlay. Danke.

___

_Sounds interesting.  I'll try it out.  Known such a program so far only for CoursePlay.  Thank you._

**Comment by andreasthu** [comment]
in autodrive enthalten,z.b. hier:
https://github.com/Stephan-S/FS19_AutoDrive/tree/master/AutoDrive%20Course%20Editor
lg
andreas

**Comment by Iwan1803** [comment]
Damit sollte die Frage beantwortet sein.
Falls nicht, dann das Thema einfach noch mal öffnen 😉
