### ISSUE TITLE
AD nutzt die blauen Linien zum Wenden

### ISSUE THREAD

**Issue by OnkelH0tte** [Stephan-S/FS19_AutoDrive#105]
Blaue Linien die an grüne Linien angeschlossen sind nutzt AD zum Wenden. Dadurch fährt der Fahrer sich fest oder dreht sich dauerhaft im Kreis.

Lässt sich das unterbinden?

**Comment by Stephan-S** [comment]
Leider derzeit nicht möglich.
Hier muss die Kursauslegung so gewählt werden, das es nicht vorkommen sollte. Sprich immer eine 'bessere' Möglichkeit zum Wenden einbauen.

Im aktuellen Kursformat ist es leider kaum möglich das bei der Kursberechnung zu berücksichtigen.
