### ISSUE TITLE
Fehler Dedi

### ISSUE THREAD

**Issue by Bandesss** [Stephan-S/FS19_AutoDrive#1050]
AutoDrive Version: Aktuellste Version
Release or custom zip: Selber gepackt
Map (if applicable): All
Vehicle / type (applicable):

Hallo  habe auf der Hot Online, das Problem, das er am Hof beim Lohntunternehmen keinen Weg findet
Und es kommt Shooting Down Autodrive
Anbei Log und Kurse für die Hot.
Könnt ihr mir sagen, was ich falsche mache ?

Gruß Bandes

[AutoDrive_HoT_online_F4rm_config.zip](https://github.com/Stephan-S/FS19_AutoDrive/files/4070112/AutoDrive_HoT_online_F4rm_config.zip)
[log.txt](https://github.com/Stephan-S/FS19_AutoDrive/files/4070114/log.txt)

**Comment by Mannie313** [comment]
Hast du mal geschaut ob die wege dorthin verbunden sind. 

MFG Mannie313

**Comment by Bandesss** [comment]
Wege sind verbunde, das war mein Gedanke.
Darum habe ich euch beides hoch geladen, manchmal sehen vier augen mehr .
Danke für die Hilfe

**Comment by Iwan1803** [comment]
Da ich die Map nicht habe, kann ich es nicht testen, sorry.
Bist du dir wirklich 100%ig sicher, das du die Wege auch wirklich verbunden hast?
Ich habe mich auch schon oft gewundert und dann war doch irgendwo ein kleiner Abschnitt nicht verbunden.

Warum ist Debug 5 für CP aktiv? Hat das einen besonderen Grund, außer das es das Log zumüllt und unübersichtlich macht?
Außerdem werden einige der Mods Fehler raus, um die du dich mal kümmern solltest....

**Comment by Stephan-S** [comment]
Hallo, da wir gerade die neue restrukturierte Version von AutoDrive released haben, können wir leider keine Bugs und Issues die sich noch auf die alte Codebasis beziehen mehr bearbeiten.
Wenn das Problem bzw. dein Anliegen in der atkuellen Version weiterhin besteht, mache doch bitte ein neues Issue mit allen benötigten Informationen auf.
Oder melde dich bei kleineren Themen und Fragen auch gerne direkt im Discord:
https://discord.gg/sUQtKhB

Vielen Dank für dein Verständniss und ich hoffe du hast weiterhin Spaß am AutoDrive Mod :-)

Und hier noch ein Link zur aktuellen Version:
https://github.com/Stephan-S/FS19_AutoDrive/releases/tag/1.1.0.0
