### ISSUE TITLE
AD is using shorter not working route instead of longer working route.

### ISSUE THREAD

**Issue by NexX0** [Stephan-S/FS19_AutoDrive#1051]
Hey there, 

i'm not sure if i'm doing something wrong or if this is a bug.
So i just started on the "Irgendwo in Thueringen" map and did some basic routes to existing fields, sell points etc. 
My problem now if i try to get a AD Driver to go to Field 36 it chooses the shortest way "red line", witch would be fine but as you can see in the Picture it is not accessible from that direction,
in order to get there he would have to use the "green line".
![FarmingSimulator2019Game_2fifgfONXb](https://user-images.githubusercontent.com/30878460/72609988-920baa80-3926-11ea-8c74-56204817b4f7.jpg)

I tried to use/not use the fastest way option, and/or the detour option set to max or 0.
I would love to know if he should behave like that or i'm just to dumb to find the problem in this situation. :D

**Comment by Iwan1803** [comment]
Warum sollte AD eine Route wählen, die augenscheinlich 5x so lang ist?
Beim Aufzeichnen sollte man darauf achten, das kein Wegpunkt abzweigt, welcher größer als 90° Grad ist.

_Why would AD choose a route that is apparently 5 times as long?
When recording you should make sure that no waypoint branches off which is greater than 90° degrees._

**Comment by NexX0** [comment]
Wie man sieht habe ich mit Absicht keinen weg zu Feld 36 aus der Richtung aus der der Traktor kommt gemacht um eben jene scharfe kurve zu vermeiden.
Ich denke AD berechnet den kurzen bis zu dem punkt an dem die Abzweigung zu dem Feld kommt und will dort eine 180 Grad Drehung machen, was natürlich nicht funktioniert und dadurch gar nicht erst startet.

**Comment by Iwan1803** [comment]
Ich mag blaue Linien nicht und wenn es geht, dann vermeide ich sie.
Was wäre denn, wenn den kurzen Weg zu dem Punkt doch ermöglichst?
![image](https://user-images.githubusercontent.com/47528836/72628075-e413f680-394d-11ea-8994-376a9da4c829.png)

**Comment by NexX0** [comment]
Grundsätzlich würde das gehen ich könnte den grünen weg auch einfach umdrehen das die stelle auf dem Bild die ausfahrt vom Feld ist und nicht die einfahrt.

Mir geht es ehr darum das AD selber merkt "ey das ist zwar kürzer aber da komm ich nicht rum" und sucht sich dann einen anderen Kurs der besser passt aber evtl länger ist.
Aber wie du schon sagtest AD checkt nicht die winkel der Verbindungen was in meinem Fall notwendig wäre.

**Comment by Iwan1803** [comment]
Ich meine mich erinnern zu können, das da was mit der 90°-Prüfung war, aber ich finde es gerade nicht.
Selbst wenn er feststellen würde, das er die Route nicht fahren kann, kann niemand vorhersagen, welche Route er dann nehmen würde, denn viele Wege führen nach Rom 😎
Wie gesagt: ich würde blaue Routen vermeiden und wenn das nicht geht, muss man halt sehen, wie man Zufahrtspunkte so aufzeichnet, das sie von beiden Richtungen aus problemlos erreichbar sind.

**Comment by KCHARRO** [comment]
In my case I make a single entry/exit to the field (blue), and then connect to the main network with (green), to force to enter and exit in one way, so they do not get stuck, and everything works very well...

**Comment by Iwan1803** [comment]
So this issue can be closed?

**Comment by NexX0** [comment]
No it can't be closed,
the problem still arises as of AutoDrive not finding the proper Way to the Location.
The Example i provided was just one of multiple Situations where AD won't find a way because it is not the shortest one.

My Solution would be that AD treys to get the shortest route and if that is not possible it's Pathfinding kicks in and searches for another route.
From my understanding AutoDrive has a working Pathfinding that is perfectly capable of the task (avoiding Crops on the field, AD goes a long way around instead of through the Crops).


As of these two comments:




> In my case I make a single entry/exit to the field (blue), and then connect to the main network with (green), to force to enter and exit in one way, so they do not get stuck, and everything works very well...

1st. I would like to see a picture of what your describing, because i think what your describing in your comment won't have any effect of the Situation in my Example.

> Ich meine mich erinnern zu können, das da was mit der 90°-Prüfung war, aber ich finde es gerade nicht.
> Selbst wenn er feststellen würde, das er die Route nicht fahren kann, kann niemand vorhersagen, welche Route er dann nehmen würde, denn viele Wege führen nach Rom 😎
> Wie gesagt: ich würde blaue Routen vermeiden und wenn das nicht geht, muss man halt sehen, wie man Zufahrtspunkte so aufzeichnet, das sie von beiden Richtungen aus problemlos erreichbar sind.

2nd. Meiner Meinung nach ist diese Situation ein perfektes Beispiel für die AutoDrive gemacht wurde, es ist egal wo ich auf der Map bin ich möchte zu Punkt X und solange dieser Punkt am "Netzt" angeschlossen ist findet AD einen weg dorthin.
Es ist mir letztendlich egal wo lang gefahren wird Hauptsache das Fahrzeug kommt am ziel an, die Geschwindigkeit ist nur ein Bonus (natürlich um so schneller um so besser), aber lieber die lange Route fahren als gar nicht erst versuchen einen Weg zu finden.

**Comment by Iwan1803** [comment]
Jede Abzweigung müsste anhand von Regeln auf Nutzbarkeit geprüft werden, denn sie könnte ja evtl. zum Ziel führen.
Dies führt zu hoher CPU-Auslastung (= FPS-Einbrüche) und längeren Berechnungszeiten, mal abgesehen vom Programmieraufwand und möglichen anderen Nebeneffekten.
Da wäre wohl eine bessere Streckenaufzeichnung deutlich leichter zu realisieren...

**Comment by TyKonKet** [comment]
**Hello, Thank you for opening this issue!**
Since we have just released [the new refactored version of AutoDrive](https://github.com/Stephan-S/FS19_AutoDrive/releases/tag/1.1.0.0), we can no longer provide any feedback or support for open bug reports related to the old code base.
If the problem persists, please reopen a new issue with all the required details.
Thank you for understanding and we hope you continue enjoying our mod 😄
