### ISSUE TITLE
Fahrer/Fahrzeug umbenennen funktioniert nicht - renaming of vehicle/driver is impossible

### ISSUE THREAD

**Issue by ws1967** [Stephan-S/FS19_AutoDrive#1052]
AutoDrive Version: 1.07.0 (download 14.1.2020).
Release or selbsterstelltes zip: Release
Karte (falls relevant): Alle maps (Singleplayer)
Fahrzeug(art) (falls relevant): alle

**Beschreibe den Bug**
das Vergeben von Namen für Wegpunkte funktioniert einwandfrei, allerdings ist es mir vollkommen unmöglich irgendein Fahrzeug umzubenennen. Weder mit der Maus noch mit der Tastatur.

the renaming of waypoints is working fine, the renaming of vehicles/drivers is absolutely impossible. I tried it with the mouse and the keybvorad - no reaction at all. 

**Falls anwendbar - Schritte mit denen ich den Bug nachstellen kann**

**Screenshots**
Falls relevant, bitte Screenshots beifügen

**Comment by Iwan1803** [comment]
Was passiert, wenn du es versuchst? Ein Log wäre nicht schlecht.

**Comment by ws1967** [comment]
Es passiert genau garnichts. Ich gebe den neuen Namen ein, klicke auf "ok" - und das war`s - absolut keine Reaktion. Werde es morgen wieder probieren und ein Log hochladen.

**Comment by Kobe8** [comment]
Es passiert doch auch erstmal nichts, oder? Nur wenn man das Fahrzeug auf eine Route schickt und dann die Meldung kommt, dass es angekommen ist! Dann steht nicht der Name des Fahrzeug sondern der eigens eingegebene Name dort!

**Comment by Iwan1803** [comment]
Bleibt der Name denn geändert oder wird er wieder zurückgeändert?

**Comment by ws1967** [comment]
Da der "neue" Name nicht übernommen wird breche ich die Aktion mit "zurück" ab und lebe mit den Originalnamen des Fahrzeugs. Bei 3 Dreschern auf einem großen Feld wird das halt dann ein wenig unübersichtlich - aber damit werde ich wohl leben müssen und können. In der log tauchen viele mods auf die zwar im mods-Ordner liegen (weil sie ev auf anderen Maps in Verwendung sind) aber in der aktuellen Map NICHT aktiviert sind. In früheren Versionen von AD (vor 1.0.7) war das nie ein Problem.
[log.txt](https://github.com/Stephan-S/FS19_AutoDrive/files/4097637/log.txt)

**Comment by Stephan-S** [comment]
Hallo, da wir gerade die neue restrukturierte Version von AutoDrive released haben, können wir leider keine Bugs und Issues die sich noch auf die alte Codebasis beziehen mehr bearbeiten.
Wenn das Problem bzw. dein Anliegen in der atkuellen Version weiterhin besteht, mache doch bitte ein neues Issue mit allen benötigten Informationen auf.
Oder melde dich bei kleineren Themen und Fragen auch gerne direkt im Discord:
https://discord.gg/sUQtKhB

Vielen Dank für dein Verständniss und ich hoffe du hast weiterhin Spaß am AutoDrive Mod :-)

Und hier noch ein Link zur aktuellen Version:
https://github.com/Stephan-S/FS19_AutoDrive/releases/tag/1.1.0.0
