### ISSUE TITLE
When is the new release?

### ISSUE THREAD

**Issue by rhaiamz** [Stephan-S/FS19_AutoDrive#1053]
Hello guys, I just found this mod and it helped me out bunches! I'm using version 1.0.6.9 because for some reason 1.0.7.0 freezes my game ( it "sticks" a key and I`m unable to take back control). When can you guys get a new version out? I see some fixes for the auger wagon that I really really want.

Keep up the good work!

**Comment by Kobe8** [comment]
Use developer Version 1.0.7.0-36!

**Comment by rhaiamz** [comment]
I'm not sure on how to get the dev release.

**Comment by Iwan1803** [comment]
I zipped the latest dev release:
[FS19_AutoDrive-1.0.7.0-36.zip](https://github.com/Stephan-S/FS19_AutoDrive/files/4082753/FS19_AutoDrive-1.0.7.0-36.zip)

**Comment by Kobe8** [comment]
Is it possible to get the zipped file everytime? Courseplay did that for every increased version number!

**Comment by ArtV-Nef** [comment]
> I zipped the latest dev release:
> [FS19_AutoDrive-1.0.7.0-36.zip](https://github.com/Stephan-S/FS19_AutoDrive/files/4082753/FS19_AutoDrive-1.0.7.0-36.zip)

not work button "on/off", work after restart game.
