### ISSUE TITLE
Unloader doesnt drive under the pipe

### ISSUE THREAD

**Issue by Knowen** [Stephan-S/FS19_AutoDrive#1054]
AutoDrive Version: 1.0.7.0-36
Release or custom zip: Release
Map (if applicable): Western Australia
Vehicle/type (applicable): BigBud 747 with HaulMaster Bulk

**Describe the bug**
The AD unloader doesn't drive under the pipe of the combine. It stops too early. My first thought was that the distance harvester option could be a problem, but no. I set the distance to 0m and still the same problem.

Here is the log: [log - Kopie.txt](https://github.com/Stephan-S/FS19_AutoDrive/files/4082747/log.-.Kopie.txt)
**If applicable - Steps to reproduce the behaviour**

**Screenshots**
![fsScreen_2020_01_19_14_58_31](https://user-images.githubusercontent.com/47173160/72682373-a9849800-3acc-11ea-92e2-96a313aa1e30.png)
![fsScreen_2020_01_19_15_05_05](https://user-images.githubusercontent.com/47173160/72682417-20219580-3acd-11ea-851c-99a874ed9822.png)

**Comment by Iwan1803** [comment]
Das ist das Problem von manchen Mods: sie sind nicht 100%ig "sauber". Somit kann die Berechnung und Ermittlung von AD nicht korrekt funktionieren und das Ergebnis davon siehst du gerade bei dir im Spiel.
Kannst ja mal probieren, ob auf einer Standardkarte und nur mit AD, BigBud und dem Haulmaster das Problem auch auftritt. Das soll nur dabei helfen, ob nicht irgendwas anderes da mit reinspielt.

**Comment by Knowen** [comment]
Hab jetzt mal den Xerion aus dem DLC vor dem HaulMaster geschnallt. Damit funktioniert das. 
Der BigBud ist der von Giants aus dem ModHub. Komisch das es damit nicht funktioniert

**Comment by andreasthu** [comment]
ist der bigBud eventuell "zu hoch"?
d.h. das die kabine nicht unter das rohr passt (oder eine colli mask)  
kannst ja mal die console aktivieren und mit F5 die kollisionen anzeigen lassen
lg
andreas

**Comment by Knowen** [comment]
Der BigBud ist etwas größer als der Xerion. Hab mir die Colli mask anzeigen lassen (davon auch ein Screenshot gemacht, aber darauf erkennt man das leider nicht so gut) und beide Traktoren sind "klein" genug um nicht mit dem Abladerohr zu kollidieren.
Ist jetzt auch kein weltbewegendes Problem, nutze ich halt ein anderen Traktor zum abfahren. Ist eher was fürs feintuning.

Grüße,
Knowen

**Comment by Iwan1803** [comment]
Hast du mal mit dem Abstand zum Rohr rumgespielt?

**Comment by Knowen** [comment]
Nein noch nicht. Kann ich bei der nächsten ernte (dieses Wochenende) mal machen und gebe dann ein Feedback.

**Comment by KCHARRO** [comment]
Dies passiert bei einigen Mods, hauptsächlich Anhängern und Lastwagen, selten bei Erntemaschinen, aber es sind immer Mods-Probleme, die Einstellung des Rohrabstands wird gelöst.

Es ist kein AutoDrive-Problem

**Comment by TyKonKet** [comment]
**Hello, Thank you for opening this issue!**
Since we have just released [the new refactored version of AutoDrive](https://github.com/Stephan-S/FS19_AutoDrive/releases/tag/1.1.0.0), we can no longer provide any feedback or support for open bug reports related to the old code base.
If the problem persists, please reopen a new issue with all the required details.
Thank you for understanding and we hope you continue enjoying our mod 😄
