### ISSUE TITLE
Driver drive on only stops one second

### ISSUE THREAD

**Issue by Phippsi** [Stephan-S/FS19_AutoDrive#1057]
AutoDrive Version: 1.0.7.0
Release or selbsterstelltes zip: Release
Karte (falls relevant): Hof Bergmann 
Fahrzeug(art) (falls relevant): 

Der Kurs hat zwischen durch ein Ziel wo er eigtl halten sollte damit ich dann den Anhänger entladen kann, da ich das selber machen möchte. Doch der AD bleibt ne Sekunde stehn und fährt dann wieder zum Feld, weil er ja auf "Drescher abtanken" steht?! 

Ich hoffe jemand kann mir helfen! 

LG

**Comment by Iwan1803** [comment]
Es gibt keine "Park"-Funktionalität in AD, wo ein Fahrzeug dann so lange stehen bleibt, bis es jemand wieder auf die Reise schickt.

**Comment by Phippsi** [comment]
Alles klar, danke trotzdem

Am 21.01.2020 17:18 schrieb Iwan1803 <notifications@github.com>:

Es gibt keine "Park"-Funktionalität in AD, wo ein Fahrzeug dann so lange stehen bleibt, bis es jemand wieder auf die Reise schickt.
