### ISSUE TITLE
Downhill rider problems

### ISSUE THREAD

**Issue by Blackjack155** [Stephan-S/FS19_AutoDrive#1058]
EN:
I was able to test the version with the Häxler distance. That works well BUT not driving away because the downhill drivers drive back to the point where we started. So where the field point is like mine e.g. Field 9. Around the field is a blue line with both sides that has several exits. But the driver ignores them and, as I said, drives back to the starting point. Why?

DE:
Ich konnte nun mal die version testen mit dem Häxler abstand. Das funktioniert schon gut ABER das wegfahren nicht denn die Abfahrer Fahren zu dem punkt zugrück wo wie gestartet sind. Also dort wo der Feldpoint ist wie bei mir z.b. Feld 9. Um das feld herum is eine Beidseid Befahrende Blaue Line die auch mehre Ausfahren hat. Aber der Abfahrer Ignoriert diese und fährt wie gesagt zum Startpunkt zurück.  Warum?

**Comment by Iwan1803** [comment]
Die blaue Linie rundherum im Feld wurde schon immer ignoriert, nur mal so nebenbei.
Wie ist denn deine Einstellung für die Suche nach der Ausfahrt?

**Comment by Blackjack155** [comment]
warum das? dann macht es ja kein sinn diese zu ziehn??? und Alle tutorials zeigen das er die line anfährt?

**Comment by Iwan1803** [comment]
Stell mal die Ausfahrt auf "Nähester Punkt" oder so ähnlich um und dann möchte ich die Tutorials gerne mal sehen, wo die blaue Linie ohne zutun vom Spieler genutzt wird.

**Comment by Blackjack155** [comment]
https://www.youtube.com/watch?v=5xvt6owNaCQ

**Comment by Blackjack155** [comment]
Schau an wenn man es auf  Nächsten Punkt stellt fährt er auf die feldlinie bzw auf die Blaue

**Comment by Iwan1803** [comment]
Du solltest dir das Video von Holger selber noch mal genau anschauen. Er erklärt das richtig gut.
Kleiner Tip: schau mal auf die Linie vom Abfahrer und wo sie mit der blauen Linie im Feld verbunden ist.
Warum AD meistens diese blauen Linie quasi ignoriert und auch mal drüber hinwegfährt, kann ich nicht sagen.

Das mit dem Häcksler früher anfahren kannst du gerne mal als Vorschlag posten, denn das hat jetzt erstmal nichts mit dem Problem zu tun, das der Abfahrer zum Abfahrerpunkt zurückkehrt anstatt über die blaue Linie direkt die nächste Ausfahrt anzusteuern.

**Comment by Blackjack155** [comment]
okay aber nun kommt gleich das nächste die Abfahrer sehn denn Häxler nicht mehr. Haben die nur ein Bestimmten Radius wo sie ihn suchen oder wie ist das?

**Comment by Iwan1803** [comment]
Das passiert bei mir ab und zu mal, wenn der Drescher/Häcksler an einer ungünstigen Stelle steht und die Abfahrer ihn da nicht erreichen können (meistens an Feldecken).

**Comment by Blackjack155** [comment]
naja er steht recht in der Feld Mitte :D

**Comment by Blackjack155** [comment]
CP erkennt und Scant ja das Feld. Macht das AD nicht?

**Comment by Blackjack155** [comment]
> Das mit dem Häcksler früher anfahren kannst du gerne mal als Vorschlag posten

Mom bringt das ja nicht viel denn der Modder hat ja momentan keine lust zu Modden.

**Comment by Blackjack155** [comment]
ok es geht nicht denn ab einen bestimmten radius finden die fahrer denn häxler nicht mehr 

das müsste mal gefix werden

**Comment by Iwan1803** [comment]
Stephan gönnt sich eine Pause, aber vielleicht verkürzt er die, wenn er gute Verbesserungsvorschläge bekommt?

Die Abfahrer suchen den Drescher/Häcksler auf dem Feld, wenn denn beide in AD gleich eingestellt sind. Ich wüsste nicht, das die Entfernung da eine Rolle spielt. Das Problem ist wohl eher die Wegfindung.

**Comment by Blackjack155** [comment]
> Stephan gönnt sich eine Pause, aber vielleicht verkürzt er die, wenn er gute Verbesserungsvorschläge bekommt?

Er kann ja mit seinem Mod machen was er will ob er weiter macht oder nicht ist ja seine sache das schreibt ihm ja keiner vor :)

`Die Abfahrer suchen den Drescher/Häcksler auf dem Feld, wenn denn beide in AD gleich eingestellt sind. Ich wüsste nicht, das die Entfernung da eine Rolle spielt. Das Problem ist wohl eher die Wegfindung.`

Ist aber komisch das es bis zu einer bestimmten Enfernung geklappt hat auch wenn er in der Ecke stand. Daher frage ich mich wo das Problem liegen könnte?

**Comment by Iwan1803** [comment]
Vielleicht macht Stephan gerade etwas Pause, weil einige mit ihren Beiträge nicht gerade für die nötige Motivation sorgen?

Hast du mal versucht, die Berechnungszeit etwas höher zu setzen oder den Abfahrer im Feld parken zu lassen?

**Comment by Blackjack155** [comment]
> Vielleicht macht Stephan gerade etwas Pause, weil einige mit ihren Beiträge nicht gerade für die nötige Motivation sorgen?

Ja das ist seine sache aber das ist nun mal Support damit muss man klar kommen und es ist besser so als wenn keiner irgendwelche fehler melden würde 

> Hast du mal versucht, die Berechnungszeit etwas höher zu setzen oder den Abfahrer im Feld parken zu lassen?

Ich werde dies mal testen

**Comment by Blackjack155** [comment]
Hast du solche Probleme nicht? Ich schätze ab einer enfernung von 300-400 m findet er es nichr mehr.

**Comment by Iwan1803** [comment]
Du solltest meine Beiträge mal richtig lesen. Es geht mir nicht darum, was jemand postet sondern eher um den Tonfall dabei.

Ich habe es so selten auf der NFM 4x, das ich es an einer Hand abzählen kann. Allerdings besitze auch noch nicht die größten Felder, aber der nächste Kauf steht bevor.
Auf welcher Map bist du unterwegs?

**Comment by Blackjack155** [comment]
Ich bin auf der Mutimap unterwegs. Ja habe ich aber auch das Deaktiveren bringt nicht dann findet er ihn auch nicht. Vlt ist es einfach ein Setting Problem? Ich kenn mich ja nicht mit denn Scripten aus

**Comment by Blackjack155** [comment]
Also beim Dreschen ist es jetzt auch so der Abfahrer fährt nicht los und bleibt einfach stehn wenn er zu weit weg ist.

**Comment by Iwan1803** [comment]
Beendet sich dann AD beim Abfahrer?
Hast du die Berechnungszeit von 1x auf was höheres umgestellt?

**Comment by Blackjack155** [comment]
Nein er bleibt einfach am Feld stehen und ja sie steht auf x2
![20200124134737_1](https://user-images.githubusercontent.com/26688591/73070260-2a1e0c80-3eb0-11ea-88e7-3411a41e6090.jpg)

**Comment by Blackjack155** [comment]
![20200124135100_1](https://user-images.githubusercontent.com/26688591/73070433-9731a200-3eb0-11ea-9b56-e8b7d4f4cb43.jpg)

**Comment by Iwan1803** [comment]
AD hat sich beim Abfahrer aber nicht ausgeschaltet und steht noch auf "Warten auf Drescher".
Heißt für mich, das der Drescher den Abfahrer nicht anspricht oder nicht ansprechen kann.
Wie sind denn die Einstellungen beim Drescher und beim Abfahrer?

**Comment by Blackjack155** [comment]
![20200124135755_1](https://user-images.githubusercontent.com/26688591
Das Richtig, gewartet haben sie auch beik Häxler

/73070794-8c2b4180-3eb1-11ea-9a05-885575607b1e.jpg)
![20200124135750_1](https://user-images.githubusercontent.com/26688591/73070795-8cc3d800-3eb1-11ea-8b99-5a7aa945dfee.jpg)
![20200124135753_1](https://user-images.githubusercontent.com/26688591/73070796-8cc3d800-3eb1-11ea-8b4b-bc5369c09faf.jpg)

**Comment by Iwan1803** [comment]
Stell beim Drescher mal "Abfahrer finden" auf "Nein", da er ansonsten den nähesten Abfahrer ruft und nicht den, welcher dem Feld zugeordnet ist.

**Comment by Blackjack155** [comment]
nein auch nichts er fährt nur dann los wenn der Drescher nah genug dran ist

**Comment by Blackjack155** [comment]
und wenn ich abfahrer finden aus mache kann der Drescher neben ihn stehn er fährt nicht los

**Comment by Blackjack155** [comment]
es muss also ein Radius geben denn er absucht ansonsten würde er ihn finden. Aber dann nur der modder sagen und der ist leider mom nicht da

Wenn die Settings wirklich richtig sind dann ist es so zu sagen ein mengel der behoben werden solte und wo man vlt die Suche erweitern könnte das er mehr schaut wo ein Enter stehn könnte.

**Comment by Iwan1803** [comment]
> und wenn ich abfahrer finden aus mache kann der Drescher neben ihn stehn er fährt nicht los

Dann läuft bei dir aber was falsch. Hast du beim Drescher in AD den gleichen Startpunkt wie beim Abfahrer eingetragen?

**Comment by Blackjack155** [comment]
oky hab denn fehler ich hab es vergessen beim drescher ein zu stellen weches feld er ist...... Danke 
Darauf wäre ich nie gekommen

**Comment by Iwan1803** [comment]
Na super... 😁
Das erklärt dann auch, warum "Abfahrer finden" = "Ja" ihn ab und zu gefunden hat, weil es da wohl einen gewissen Radius für die Suche gibt. Ansonsten würde er ja die Abfahrer von sonst wo holen.

**Comment by Blackjack155** [comment]
so ein dummer fehler :D Aber erstaunlich was AD alles kann wen ein depp davor sitz xD er konnte wenigtes ein teill abfahren  
Solte man sich echt mal merken..
 
Stefan solte mal ein tut für Dummis machen wie man AD bedient :P

**Comment by Iwan1803** [comment]
Da das Problem ja nun vor dem Bildschirm saß, mach ich mal hier zu 😋


PS: nur ein Joke 😎

**Comment by Blackjack155** [comment]
Ja man Lernt nie aus :D
