### ISSUE TITLE
Probleme mit dem Editor

### ISSUE THREAD

**Issue by HGReaper** [Stephan-S/FS19_AutoDrive#106]
Irgendwie will bei mir der Course Editor nicht so wirklich. Wenn ich eine Map Datei öffne, bleibt das Fenster so "schmal" wie beim Start.

![01](https://user-images.githubusercontent.com/29012368/57178780-0de7c480-6e76-11e9-9517-9750107870e3.jpg)

Auch wenn ich auf "Maximieren" klicke oder das Fenster größer ziehe bleibt die "Map" so klein und der Rest des Bildes wird einfach grau. Wenn ich das Fenster erst vergrößere und dann die Map lade, sieht es wieder aus, wie auf Bild 1

![02](https://user-images.githubusercontent.com/29012368/57178779-0de7c480-6e76-11e9-9372-de59eaddbdb9.jpg)

**Comment by haamic** [comment]
ist bei mir leider auch so, ich muss den umweg machen und in der XML den Kartennamen auf z.b. Felsbrunn ändern, dann im editor laden, da kommt automatisch die felsbrunn Karte mit meinen Wegpunkten, dann kann ich meine eigentliche Map.png laden,. nur so gehts bei mir, nach verändern und speichern, wieder den Kartennamen anpassen.

**Comment by HGReaper** [comment]
Bei mir funktioniert leider nichtmal das.

**Comment by ploughedfieldman123** [comment]
> Unfortunately not even that works for me.

What map and what version of AD are you using as latest is v1.0.1.9   also do you have the pda image file of your map inside folder  mapImages

I had this happen to me a few times, also try this go into the game just break a waypoint re-join it again then click on update way button. like a refresh save game exit then try editor

Stephan did this when I had same problem

**Comment by haamic** [comment]
Schau mal in deiner XML ob die Namen der gespeicherten Ziele richtig sind.
Bei mir war auch der Fehler, das ich versehentlich Umlaute benutzte (ä/ü/ö), der Name dadurch in der xml komische Zeichen enthielt und deswegen nicht geladen wurde.

**Comment by Stephan-S** [comment]
Aufgrund Inaktivität schließe ich hier mal. Bei Bedarf bitte wieder öffnen
