### ISSUE TITLE
Frage zur Einstellung

### ISSUE THREAD

**Issue by Blackjack155** [Stephan-S/FS19_AutoDrive#1060]
Sry wenn ich nocb mal nerv aber ich bekomm diese Line nicht weg @Iwan1803  weißt du weche Einstellung das ist?
![20200124173053_1](https://user-images.githubusercontent.com/26688591/73085745-79276a00-3ecf-11ea-965a-f564c23630fa.jpg)

**Comment by Iwan1803** [comment]
In der Config = "Zeige nächsten Pfad" -> auf "Nein" einstellen.

**Comment by Blackjack155** [comment]
Danke
