### ISSUE TITLE
Kann AD nicht Fliegend Abfahren

### ISSUE THREAD

**Issue by Blackjack155** [Stephan-S/FS19_AutoDrive#1061]
@Iwan1803  Sag mal der Abefahrer hat Starke Probleme denn Drescher zu folgen. Kann es sein Das AD nur Stehende Descher Abtanken kann? Habe ein wenig herum gestellt aber besser wird es nicht. Er brauch sehr lange bis her inter in ist und dann fährt er ne weile langsam hinter beschleunig und tuckert hinter und kommt dann nicht mal unter dem Rohr an sondern zu nah dran was dazu führt das er nicht Abtankt.

Is da was bekannt?

https://drive.google.com/file/d/1_IAOTjfudVJc3xC0rYObDjTeTbGMsOO2/view?usp=sharing

**Comment by Iwan1803** [comment]
Ich lass meine Drescher per CP immer zum Abladen anhalten.
Der Abfahrer könnte sonst an einem Feldrand mit Bäumen nicht an den Drescher rankommen oder halt in den Bäumen hängenbleiben. Mit eingeschalteter Fruchtumfahrung macht der Drescher so passend Platz, damit der Abfahrer problemlos an ihn rankommen kann.

**Comment by Iwan1803** [comment]
Du solltest dir vielleicht mal meine Letsplays anschauen (http://yt.vu/+iwan1803) oder auch die von Cairo Amun (https://www.youtube.com/channel/UCqQhmo7yyaKDsXQDLgNV39A).
Die könnten sehr hilfreich sein, um zu verstehen, wie man AD & CP einsetzen kann und auf was man achten sollte.
