### ISSUE TITLE
Autodrive interfering with Courseplay ability to start implements

### ISSUE THREAD

**Issue by mdbguy** [Stephan-S/FS19_AutoDrive#1062]
AutoDrive Version: 1.0.70
Release or custom zip: custom
Map (if applicable): All
Vehicle / type (applicable):

**Describe the bug**
One of the 89 commits since release 1.0.7.0 has introduced a mod conflict with Courseplay that results in Courseplay not starting/stopping implements.  Example start courseplay course at first waypoint should start combine and header then lower the header and begin driving.  Observed behavior is the header gets lowered but is not active and combine does not drive.

No problem with only courseplay mod enabled or with both courseplay and AD release 1.0.7.0 but when AD is upgraded to current custom version, courseplay will not start driving unless implement is manually started before starting courseplay.

I have verified same behavior with an earlier version of courseplay to test that the change was not introduced there.

[log_CPworking.txt](https://github.com/Stephan-S/FS19_AutoDrive/files/4110141/log_CPworking.txt)
[log_CPbroken.txt](https://github.com/Stephan-S/FS19_AutoDrive/files/4110142/log_CPbroken.txt)

**Comment by Iwan1803** [comment]
Ich weiß nicht, welcher Übersetzer hier am Werk war, aber irgendwie verstehe ich das Problem nicht so ganz.
Der Drescher soll per Courseplay starten, senkt das Schneidwerk aber schaltet es nicht ein?
Ist der Drescher ein Mod?

*english by deepl.com*
I don't know which translator was at work here, but somehow I don't quite understand the problem.
The thresher is supposed to start by courseplay, lowers the cutterbar but does not switch it on?
Is the tresher a mod?

**Comment by mdbguy** [comment]
steps to reproduce

1. Playing on default Ravenport map new farmer mode.  Only 2 mods installed

2. In this example Courseplay is set to start at nearest waypoint mode. Does not make a difference

3. using AD 1.0.7.0-36

4. Courseplay is started

5. header gets lowered but tool is not started.  combine does not move

6. now using AD release 1.0.7.0

7. Courseplay is started

8. tool is started, header is lowered and combine drives as expected


Schritte zur Reproduktion

1. Spielen auf der Standard-Ravenport-Karte neuer Bauernmodus.  Nur 2 Mods installiert

2. In diesem Beispiel ist die Kursspiel-Funktion so eingestellt, dass sie im nächstgelegenen Waypoint-Modus startet. Das macht keinen Unterschied.

3. unter Verwendung von AD 1.0.7.0-36

4. Das Kursspiel wird gestartet

5. Kopf wird abgesenkt, aber das Werkzeug wird nicht gestartet. Mähdrescher bewegt sich nicht

6. jetzt mit AD-Release 1.0.7.0

7. Das Kursspiel wird gestartet

8. das Werkzeug wird gestartet, der Header wird abgesenkt und die Laufwerke wie erwartet kombiniert

Übersetzt mit www.DeepL.com/Translator (kostenlose Version)
![1](https://user-images.githubusercontent.com/32879507/73112428-ae8a8280-3ee4-11ea-91be-840ef306dcf1.png)
![23](https://user-images.githubusercontent.com/32879507/73112433-b2b6a000-3ee4-11ea-9cc8-fc5f4ceb302d.png)
![45](https://user-images.githubusercontent.com/32879507/73112442-b77b5400-3ee4-11ea-9434-d68c27a5ffff.png)
![678](https://user-images.githubusercontent.com/32879507/73112445-ba764480-3ee4-11ea-8d7f-32efa5966711.png)

**Comment by Bobster82** [comment]
I am using the same version of CP and using the same AD-36 release.... I never saw that problem u are describing above.... 

Is it also on other combines? or other tools?
U tried different map?

Maybe u need to activate some debug channels on CP, maybe they telling more in the log ;)

**Comment by jala15** [comment]
![image](https://user-images.githubusercontent.com/52028079/73119366-12529100-3f61-11ea-82f9-bad641a90dcb.png)
Tried to reproduce but worked properly with AD 1.0.7.0-36
Could you find which commit makes it don´t work anymore?
Anyway, you are using an old 1.3.0.1 version of the game. Currently I am on v 1.5.1.0
You should try to update your farming simulator to avoid conflicts with newer mods, and test again

**Comment by Bobster82** [comment]
> 
> Anyway, you are using an old 1.3.0.1 version of the game. Currently I am on v 1.5.1.0
> You should try to update your farming simulator to avoid conflicts with newer mods, and test again

This could be the issue, didnt see that... good point

**Comment by mdbguy** [comment]
Yes I did forget that I was several game version updates behind.  Now after upgrading to 1.5.1 (troubleshooting basics - ensure all components are up to date) I confirm that was the source of the problem.  Thank you all for your help.

Ja, ich habe vergessen, dass ich mehrere Aktualisierungen der Spielversion hinter mir habe.  Jetzt, nach dem Upgrade auf 1.5.1 (Grundlagen der Fehlerbehebung - stellen Sie sicher, dass alle Komponenten auf dem neuesten Stand sind) bestätige ich, dass das die Ursache des Problems war.  Ich danke Ihnen allen für Ihre Hilfe.
