### ISSUE TITLE
AD Läst Drescher nicht los fahren + Fahr fehler von AD

### ISSUE THREAD

**Issue by DerBauer2** [Stephan-S/FS19_AutoDrive#1064]
AD sagt dem CP Drescher Fahrer nicht das er wieder los fahren kann.
![20200126151251_1](https://user-images.githubusercontent.com/60297613/73136927-558d2c80-4053-11ea-87af-caf0a9dc623e.jpg)
![20200126150622_1](https://user-images.githubusercontent.com/60297613/73136928-558d2c80-4053-11ea-98cd-5fadce642f42.jpg)

hier sieht man auch die Fahrfehler des AD
https://drive.google.com/file/d/1_IAOTjfudVJc3xC0rYObDjTeTbGMsOO2/view?usp=sharing

**Comment by DerBauer2** [comment]
hier sieht man auch die Fahrfehler des AD
https://drive.google.com/file/d/1_IAOTjfudVJc3xC0rYObDjTeTbGMsOO2/view?usp=sharing

**Comment by Tensuko** [comment]
Bin nicht sicher ob es an AD liegt.
Macht AD in dem Moment denn etwas mit dem CP Drescher Fahrer, das dieser an Ort und Stelle stehen bleibt ?
Was passiert, wenn du den Drescher jetzt noch einmal anfährst und ihn komplett leer machst, fährt der Drescher dann weiter ?

**Comment by DerBauer2** [comment]
Nein er kann dann nichts mehr machen nur wenn ich ihn wieder hin stelle und es wiederholt sich immer weider 
Ich habe heraus gefunden das an diesen Mod liegt denn ohne ihn geht es

https://www.farming-simulator.com/mod.php?lang=de&country=ch&mod_id=138280

**Comment by Tensuko** [comment]
Ok das erklärt einiges.

**Comment by Tensuko** [comment]
Kannst du das mit der Mod noch mal bei uns im GitHub hinschreiben ? Das wir die Info auch dort haben.

**Comment by Iwan1803** [comment]
Also kein Problem von AD. Wenn es dort gepostet worden ist, dann würde ich hier zu machen.

**Comment by DerBauer2** [comment]
@Iwan1803  Kann aber auch von AD komm das beide halt nicht hamonieren

**Comment by Iwan1803** [comment]
Wenn der Mod sich am Standard orientieren würde, würden CP & AD damit klar kommen.
Da dies nicht der Fall ist... 😉

**Comment by DerBauer2** [comment]
vlt geht nicht immer der Standart um einen guten Mod zu Pogramieren.

**Comment by Tensuko** [comment]
Wenn der Mod probleme macht, kann er nicht gut sein...

**Comment by DerBauer2** [comment]
Kommt denn kein AD Patch mehr? Wird der Mod nicht mehr weiter Endwikelt ?

**Comment by Iwan1803** [comment]
Da der Fehler scheinbar im Mod und nicht in AD liegt, mach ich hier erstmal zu.
