### ISSUE TITLE
Multimap2019 Bagg with a course

### ISSUE THREAD

**Issue by Kaljitos** [Stephan-S/FS19_AutoDrive#1065]
AutoDrive Version: 1.0.7.0-36
Release or selbsterstelltes zip: Release
Karte : Multimap2019
Fahrzeug:Alle

When using the "Download and Delivery" mode, arriving at the download point, a terrible freeze-up begins, I tried a new save, with and without mods, with loaded courses, and I created all the courses myself, one result, a 2-fold reduction in FPS. As soon as I turn off following the route, the FPS returns to normal.

[log.zip](https://github.com/Stephan-S/FS19_AutoDrive/files/4113991/log.zip)

![fsScreen_2020_01_27_01_03_16](https://user-images.githubusercontent.com/59848183/73139648-2d1c2700-4081-11ea-9128-5b0a8f2d9daf.png)
![fsScreen_2020_01_27_01_03_20](https://user-images.githubusercontent.com/59848183/73139649-2d1c2700-4081-11ea-966b-8d754e0c0eaf.png)
![fsScreen_2020_01_27_01_03_25](https://user-images.githubusercontent.com/59848183/73139650-2db4bd80-4081-11ea-8f2f-88d587875a43.png)
![fsScreen_2020_01_27_01_03_30](https://user-images.githubusercontent.com/59848183/73139690-a4ea5180-4081-11ea-9652-aebdebf2ef5e.png)

**Comment by DerBauer2** [comment]
If you have live mode in it then the FPS will drop because it then calculates the course and in between I think that it calculates the course

**Comment by Kaljitos** [comment]
> Если у вас есть живой режим в нем, то FPS упадет, потому что он затем рассчитывает курс, и между ними я думаю, что он рассчитывает курс

"Real-time calculation" and "Automatic recalculation" are disabled

**Comment by Kaljitos** [comment]
I downloaded other maps, Saxony 2019, the same problem, but first started using AutoDrive, on the Fenton Forest 4X By Stevie map, and everything works fine on this map.

**Comment by Iwan1803** [comment]
I see in the log some errors and warnings for different mods, but none for AutoDrive. You should maybe fix them first.
Also having different maps in the mod folder could cause problems.
Please try the map without any mod, except AD.

**Comment by Kaljitos** [comment]
> Я вижу в журнале некоторые ошибки и предупреждения для разных модов, но ни одного для AutoDrive. Возможно, вам следует сначала исправить их.
> Также наличие разных карт в папке мода может вызвать проблемы.
> Пожалуйста, попробуйте карту без каких-либо модов, кроме AD.

I tried to start the game, only with AutoDrive modo and a card, the problem remains, today I will try to delete other cards from the folder with the modifications.

**Comment by Iwan1803** [comment]
I checked the screenshots again and can't see a high GPU or CPU load.
If this happens only on some maps, maybe they are causing the problems.
Did you fix the problems and error from the log?
Maybe you should try a problem map with an empty mod folder, except AD.

**Comment by Kaljitos** [comment]
Ich habe die widersprüchlichen Modifikationen gelöscht, im "Mods" -Ordner gibt es einen Kartenmodus und Autodrive, das Problem bleibt bestehen.

**Comment by Kaljitos** [comment]
> I checked the screenshots again and can't see a high GPU or CPU load.
> If this happens only on some maps, maybe they are causing the problems.
> Did you fix the problems and error from the log?
> Maybe you should try a problem map with an empty mod folder, except AD.

Ich habe die widersprüchlichen Modifikationen gelöscht, im "Mods" -Ordner gibt es einen Kartenmodus und Autodrive, das Problem bleibt bestehen.

**Comment by TyKonKet** [comment]
**Hello, Thank you for opening this issue!**
Since we have just released [the new refactored version of AutoDrive](https://github.com/Stephan-S/FS19_AutoDrive/releases/tag/1.1.0.0), we can no longer provide any feedback or support for open bug reports related to the old code base.
If the problem persists, please reopen a new issue with all the required details.
Thank you for understanding and we hope you continue enjoying our mod 😄
