### ISSUE TITLE
Error: combine mode not working

### ISSUE THREAD

**Issue by Phantom742** [Stephan-S/FS19_AutoDrive#1066]
AutoDrive Version: 1.0.7.0.36
Release or custom zip: zip
Map (if applicable): Hofbrunn V1.9.0
Vehicle / type (applicable): almost all

Hi,
I have some issues with the combine mode. On almost every tractor when I use combine mode to unload the harvester the tractor will always start to drive to the unload point and then he will wait at the filed. But the tractor is noch waiting for the combine, instead he will just stay there. The unload point it then already highlighted in green - as if he is already driving to the unload point.
I just added a picture as he is waiting forever...

Hope someone will help.
![Error](https://user-images.githubusercontent.com/11431031/73274547-05929f00-41e6-11ea-808e-c66576be288e.jpg)

**Comment by Iwan1803** [comment]
Kann es sein, das das ein Mod-Anhänger ist?
Manchmal erkennt AD bei solchen nicht, ob er auch wirklich leer bzw. voll ist und fährt dann zum Entladepunkt.

**Comment by Phantom742** [comment]
Ja das ist ein Mod Anhänger, das tut aber nichts zur Sache. Es ist kein Unterschied ob es ein Mod Anhäger ist oder nicht. Es funktioniert mal und mal nicht, egal ob Mod Anhänger oder Original.

**Comment by Iwan1803** [comment]
Hast du es immer noch mit den kleinen Anhängern probiert (bis 16k Liter)?
Mit denen habe ich auch ab und zu das Problem, das er erst zum Abladen fahren will, obwohl der Anhänger lt. Anzeige eigentlich leer ist.

**Comment by Phantom742** [comment]
Hi, habe meist kleine Anhänger aber das Problem tritt auch bei großen auf.

**Comment by Iwan1803** [comment]
Ab und zu habe ich auch so ein Phänomen, aber das ist wirklich eher selten.
Hier müssten wir auf @Stephan-S warten, da ich nicht weiß, wie die Füllrate des Anhängers ermittelt wird und ob es da ggfs. ein Problem gibt.

**Comment by jala15** [comment]
Have you tried to close edit mode? Sometimes using pathfinding doesn't start driving if editor mode is active

**Comment by Phantom742** [comment]
No Change with EDIT mode.

**Comment by Phantom742** [comment]
Hi have played arround a bit trying to isolate the problem. If the problem exits, it is possible to 'fix' it. How to do it? The combine has to full, ready to unload. If the tractor arrives for the firtst time when the combine is full, then the tractor will unload the combine normally. After the first successfull unload of the combine the problem does not exits anymore! The next time the tractor arrives he will wait like he is supposed wait without directly switching to the unload station and wait at the field forever. I hope it will help trying to isolate the problem.

Thx. 

By the way, how do I extract the log?

**Comment by Phantom742** [comment]
Ich found the problem.  If the tractor was set to 'Unload with 0%' the tractor will not work. After the setting was raised above 0% it works fine as shown in the pictures below. Can the sourcecode be updated so the problem is eleminated?

Greets
![Unload greater to zero](https://user-images.githubusercontent.com/11431031/74138499-fc480000-4bf1-11ea-9f59-5443e338fa77.jpg)
![Unload with setting to zero](https://user-images.githubusercontent.com/11431031/74138509-ffdb8700-4bf1-11ea-8347-e6ebf6074738.jpg)

**Comment by guitarheel** [comment]
Having this issue also.  The tractor just waits and waits and doesn't move.

**Comment by guitarheel** [comment]
> Ich found the problem. If the tractor was set to 'Unload with 0%' the tractor will not work. After the setting was raised above 0% it works fine as shown in the pictures below. Can the sourcecode be updated so the problem is eleminated?
> 
> Greets
> ![Unload greater to zero](https://user-images.githubusercontent.com/11431031/74138499-fc480000-4bf1-11ea-9f59-5443e338fa77.jpg)
> ![Unload with setting to zero](https://user-images.githubusercontent.com/11431031/74138509-ffdb8700-4bf1-11ea-8347-e6ebf6074738.jpg)

What setting are you referring to?  My "Unload Fill Level" is set at 70 percent and this issue persists.

**Comment by guitarheel** [comment]
**UPDATE**

My issue appears to have been caused by the modded potato harvester I was using, specifically the **Holmer Terra Dos T4-40 Multifruit**.  It seems that for whatever reason, AD could not locate the combine and the trucks would not drive to it and unload.  I replaced the Holmer with the default potato harvester and AD works as intended.

**Comment by Iwan1803** [comment]
These are my settings and i've got no problems:
![fsScreen_2020_02_13_08_31_27](https://user-images.githubusercontent.com/47528836/74411399-669fb100-4e3b-11ea-87a4-67bbed45e14c.jpg)
![fsScreen_2020_02_13_08_31_37](https://user-images.githubusercontent.com/47528836/74411403-68697480-4e3b-11ea-89e5-85d17bef3c19.jpg)

**Comment by Iwan1803** [comment]
@guitarheel 
that's why i posted this: https://github.com/Stephan-S/FS19_AutoDrive/issues/1071 

> ... try to recreate the problem on a standard map without any mods except AD ...

So the problem was a "bad" or "dirty" mod. Thx. for the update!

@Phantom742 
wie sieht es bei dir aus?

**Comment by guitarheel** [comment]
> @guitarheel
> that's why i posted this: #1071
> 
> > ... try to recreate the problem on a standard map without any mods except AD ...
> 
> So the problem was a "bad" or "dirty" mod. Thx. for the update!
> 
> @Phantom742
> wie sieht es bei dir aus?

Forgive me - I did not see this.

It appears I was wrong anyway.  The issue is still present.

**Comment by Phantom742** [comment]
Gents,

das Problem ist mehr oder weniger gelöst. in den VEHICLE settigs das 'Abladen ab Level' nicht 0% stehen. Wenn dieses setting auf 0% steht dann fährt der Abfahrer im Modus 'Drescher abfahren' am Feld und springt sofort auf die Abladestelle. Das Problem ist aber er fährt nicht ab. Er wartet dort für immer. 
Des weiteren habe ich herausgefunden das im Modus 'Abholen und Abliefern' das Fahrzeug immer erst zur Abladestelle fährt anstatt zu Ladestelle. Wenn man hier auch wieder einen anderen Wert als 0% einstellt dann fährt das Fahrzeug als erstes zu Ladestelle und nicht zu Abladestelle. 
Mann könnte sagen dann muss man halt die settings immer umstellen aber der default Werte is 0% bei 'Abladen ab Level' - das ist unpraktisch da jeder das immer umstellen muss und daher von Haus aus in die Probleme läuft.
Mein Lösungvorschlag:
Neht die mögliche Einstellung von 0% raus. Damit sollte sich alles erledigt haben. Nehmt als kleinste Einstellung 1% oder 10% aber nicht 0%.

Thx for the support....

Phantom

**Comment by guitarheel** [comment]
> Gents,
> 
> das Problem ist mehr oder weniger gelöst. In den VEHICLE settigs darf 'Abladen ab Level' nicht auf 0% stehen. Wenn dieses setting auf 0% steht dann fährt der Abfahrer im Modus 'Drescher abfahren' an das Feld und springt sofort auf die Abladestelle wenn er keinen Drescher findet Das Problem ist aber er fährt nicht ab. Er wartet dort für immer.
> Des weiteren habe ich herausgefunden das im Modus 'Abholen und Abliefern' das Fahrzeug immer erst zur Abladestelle fährt anstatt zu Ladestelle. Wenn man hier auch wieder einen anderen Wert als 0% in 'Abladen ab Level' einstellt dann fährt das Fahrzeug als erstes zu Ladestelle und nicht zu Abladestelle.
> Mann könnte sagen dann muss man halt die Settings immer umstellen aber der default Wert ist 0% bei 'Abladen ab Level' - das ist unpraktisch da jeder das immer umstellen muss und daher von Haus aus in die Probleme läuft.
> Mein Lösungvorschlag:
> Nehmt die mögliche Einstellung von 0% raus. Damit sollte sich alles erledigt haben. Nehmt als kleinste Einstellung 1% oder 10% aber nicht 0%.
> 
> Thx for the support....
> 
> Phantom

The default for that setting is 70 not 0. Who would set it at zero anyway? At zero the settings would be telling the truck to unload constantly with nothing inside. That means it’s working correctly and the error is with the user. 

My “unload fill level” was set to 85% and still the trucks don’t move.

**Comment by Stephan-S** [comment]
@guitarheel 
If the status says 'Drive to combine', then the driver is actively searching for a path to the combine.
For debugging purposes, you can select the pathfinder debug setting and make sure you enable the edit mode in the HUD. Then you will see some lines drawn, which show you the process of the pathfinder and might explain where it get's stuck

**Comment by guitarheel** [comment]
I turned off "Avoid Fruit" and now everything seems to be working fine.
