### ISSUE TITLE
2 Anhänger

### ISSUE THREAD

**Issue by DerBauer2** [Stephan-S/FS19_AutoDrive#1067]
Kann man mit AD 2 Anhäger fahren und auch Befüllen?

**Comment by TobiHH78** [comment]
Ja, wurde vor langer Zeit gefixt.

https://github.com/Stephan-S/FS19_AutoDrive/issues/872#issuecomment-554771546

**Comment by DerBauer2** [comment]
und wie? bei mir läd er denn 2 Anhänger nicht?

**Comment by DerBauer2** [comment]
lol doch nur hat er wohl ein paar probleme mit einigen Triggern

**Comment by Iwan1803** [comment]
Evtl. den Zielpunkt zu dicht am Trigger?

**Comment by Iwan1803** [comment]
Da es generell zu funktionieren scheint, ist es wohl eher kein Problem von AD.
Von daher mache ich hier erstmal zu.
