### ISSUE TITLE
Running LUA method 'draw'

### ISSUE THREAD

**Issue by Knowen** [Stephan-S/FS19_AutoDrive#1068]
AutoDrive Version: 1.0.7.0-36
Release or custom zip: Release
Map (if applicable): Western Australia
Vehicle / type (applicable):

**Describe the bug**

I was shifting through the different modes and then the UI went off.
This error appears in the log:
```
2020-01-31 19:23 Error: Running LUA method 'draw'.
2020-01-31 19:23 D:/LS19 Mods/FS19_AutoDrive/scripts/HudElements/PullDownList.lua:499: attempt to index a nil value
```

**If applicable - Steps to reproduce the behaviour**

**LOG**
[log - Kopie.txt](https://github.com/Stephan-S/FS19_AutoDrive/files/4140812/log.-.Kopie.txt)

Greetings,
Knowen

**Comment by Iwan1803** [comment]
Before thinking AD is causing the problem, maybe you should fix first the error and warnings from the other mods.
