### ISSUE TITLE
Fahren ohne Diesel - Driving without diesel

### ISSUE THREAD

**Issue by haamic** [Stephan-S/FS19_AutoDrive#107]
Hallo,
mir ist aufgefallen, das ein Fahrzeug, trotzdem der Tank leer ist, mit AD fährt.
Ohne AD kommt die Meldung das es aufgetankt werden muss und bleibt stehen,weil ja nix mehr drin ist. Man kann also theorethisch mit AD eine Tankstelle anfahren und auffüllen. Was sonst unmöglich wäre. Ist aber sicher nicht Sinn und Zweck.
Gruss Micha
-----------------------------
Hello,
I noticed that a vehicle is still empty, with AD drives.
Without AD comes the message that it must be refueled and stops, because there is nothing more in it. So you can theoretically drive to a gas station with AD and fill it up. Which would otherwise be impossible. But it is certainly not sense and purpose.
Greetings Micha

**Comment by Scaracuila** [comment]
me too, very eco-friendly...
;-)
