### ISSUE TITLE
AD Sämaschiende Beladen

### ISSUE THREAD

**Issue by DerBauer2** [Stephan-S/FS19_AutoDrive#1070]
Ich AD kann leider eine Saatlegemaschiene nicht Beladen die Dünger und Saat enthelt. Ich habe auch schon eingestellt das er weiterre Trigger suchen soll leider ohne erfolgt. Vlt könnte man das mal fixen.

![20200201114326_1](https://user-images.githubusercontent.com/60297613/73590906-82749000-44e8-11ea-9f5c-5af3f938feb3.jpg)

**Comment by Mannie313** [comment]
nimm mal zwei einzelne und stell diese weiter auseinander dann gehen diese auch.
Außerdem müssen die Bits richtig sein.

MFG Mannie313

**Comment by Iwan1803** [comment]
Keine 5 Sekunden auf Youtube gesucht:
https://www.youtube.com/watch?v=xVhFVJIhHCw

**Comment by DerBauer2** [comment]
Tzja kluge Sprüche kann ich auch Klopfen ;) Schade nur wenn es genauso gemacht wurde und es nicht geht ;) es ging mal aber nun nicht mehr. Silo enfernung ist 100m und die sind nicht mal 40m auseinader wie man sieht

**Comment by DerBauer2** [comment]
> nimm mal zwei einzelne und stell diese weiter auseinander dann gehen diese auch.
Außerdem müssen die Bits richtig sein. 

das sind 2 einzelne

**Comment by DerBauer2** [comment]
Noch mal Bildlich zu zeigen

![20200201190245_1](https://user-images.githubusercontent.com/60297613/73596772-a99d8280-4525-11ea-8570-a6be6545e9a6.jpg)
![20200201190246_1](https://user-images.githubusercontent.com/60297613/73596773-a99d8280-4525-11ea-82a4-b1c990c0d20c.jpg)

**Comment by DerBauer2** [comment]
Das ging auch mal bei mir die Frage ist sucht er in einem radius oder was für trigger auf der fahrline sind`?

**Comment by Iwan1803** [comment]
Versetz den Zielpunkt mal etwas nach hinten auf der Linie.

**Comment by DerBauer2** [comment]
würde ich ja gerne testen aber ad raft es nicht das er Saat tanken soll er fäher immer wieder zu feld 17 dreht also endlosschelifen....

**Comment by Iwan1803** [comment]
Vielleicht weil es da beides an einem Trigger gibt?
In dem Video hat Cairo ja 2 Silo: 1x Saat & 1x Dünger.

**Comment by DerBauer2** [comment]
Nein das sind 2 silos, das sieht man ja

**Comment by Iwan1803** [comment]
Mit "2 Silos" meinte ich 2 voneinander unabhängige Gebäude.

**Comment by DerBauer2** [comment]
wie unabhängig? Sieht du doch das 2 verschiedene Silos sind eins mit dünger das andere mit Saat

**Comment by Iwan1803** [comment]
2 einzeln gekaufte Gebäude. Dein Silo ist ja 1 Gebäude, was halt Saat & Dünger zusammen beherrscht.

**Comment by DerBauer2** [comment]
nein wie oft noch das ist GETRENNT  das sind 2 SILOS

**Comment by Iwan1803** [comment]
Ah, beim 2. mal genauer hinsehen, sehe ich nun auch 2 und genau deshalb verweise ich noch mal auf das Video von Cairo. Er hat doch genau erklärt, wie man das hinbekommt.
Kleiner Tip: sie sind zu weit auseinander.

**Comment by Iwan1803** [comment]
Da dies kein Fehler von AD ist, mach ich hier mal zu.
