### ISSUE TITLE
Question: Two way line

### ISSUE THREAD

**Issue by Twetch** [Stephan-S/FS19_AutoDrive#1072]
Sorry for dumb question ,but pls how to record two way line in new version?

**Comment by Iwan1803** [comment]
The ultimate tool: right click 😎
Also described in the wiki:
https://github.com/Stephan-S/FS19_AutoDrive/wiki/5-Record-and-edit-the-network

**Comment by Twetch** [comment]
I have some key issues and didnt work ,cuz i tested right click and shift+click etc. :D also i didnt even know, there is updated wiki :) but thx mate!
