### ISSUE TITLE
Hohe FPS einbuse bei Silo/ ÜLW abunkern

### ISSUE THREAD

**Issue by DerBauer2** [Stephan-S/FS19_AutoDrive#1073]
Ich habe mal testen wollen das CP abtankt als ÜLW und das zum AD fahrer bingt. Problem das AD 20-30 FPs zieht wenn er wartet das er am Startpunkt beladen wird. Könnte man dies fixen?

**Comment by Iwan1803** [comment]
Die Wegberechnung zieht natürlich CPU-Leistung, was sich auch auf die FPS auswirken kann, aber bist du dir sicher, das es nur am wartenden AD-Fahrer liegt und an nichts anderem?

PS: warum hast du das Template nicht benutzt? Kann doch nicht so schwer sein....
Werf auch mal einen Blick hierein: https://github.com/Stephan-S/FS19_AutoDrive/issues/1071

**Comment by DerBauer2** [comment]
Warum log posten wenn keine fehler vor liegen???

Ja es liegt an AD. Nein das ist ja richtig das wenn er denn weg berecht is das ja halbwegs verständlich was man sicher noch reduzieren könnte. Es geht dadrum das die FPS unten bleiben nur weil er steht und wartet beladen zu werden.

**Comment by Tensuko** [comment]
> Warum log posten wenn keine fehler vor liegen???

Weil in einer Log mehr Informationen stehen als nur Fehler...

**Comment by Axel32019** [comment]
Die Wegberechnung im Live-Mode benötigt weniger als 1/10 sec - sehe ich daher nicht als Ursache für die FPS-Einbrüche. Das Einbrechen der FPS / Ruckeln kenn ich schon länger, leider gibt's im log keine Anzeichen woran das liegt, meist steht ein Fahrzeug beim Beladen und wartet... Ziel ist dann weiss, fährt aber nicht weiter.

**Comment by Iwan1803** [comment]
Im Standard berechnet AD ca. 1.000 Wegpunkte pro Sekunde, was eigentlich nicht zu spürbaren FPS-Einbußen führt - außer man hat einen absoluten Kartoffelrechner.
Leider ist die Unterstützung von Mutlicore-CPUs eher bescheiden und DirectX 11 mehr oder weniger veraltet. Ich hoffe, es wird hierfür mal ein Update geben oder wir müssen auf LS21 hoffen.

Zum Thema....
Ohne notwendige Infos kann keiner helfen. Dazu gehört das Log, Screenshots, welche Map, Fahrzeuge, etc.
Die Templates gibt es nicht zum Spaß und wer die nicht nutzen möchte, muss halt mit den Konsequenzen leben.

**Comment by DerBauer2** [comment]
Denn live mode neheme ich nicht mehr da er fehlerhaft ist 
denn ohne neu berechnung erkennt er die ziele nicht und fährt dort nicht hin daher habe ich das abgeschalten

beine berechnung liegt bei 1x

und AD brauch länger zum berechnen min. 5-15 sec. also kommt es eh schon von AD

**Comment by Iwan1803** [comment]
Der Live-Mode funktioniert bei mir und vielen anderen problemlos. Voraussetzung sind hierfür natürlich einwandfrei eingefahrene Kurse. 
AD hat bei mir ohne Live-Modus für die Berechnung einer Strecke quer über die Karte definitiv noch nie so lange gerechnet wie bei dir. Das deutet für mich auf eine schwache CPU hin oder andere Prozesse, welche im Hintergrund dem Spiel Power mopsen.

Manchmal habe ich übrigens auch FPS-Einbrüche (1-5 Sekunden lang), ohne das auch nur 1 Fahrzeug per AD oder CP unterwegs ist. Keine Ahnung, was das Spiel da zu der Zeit macht. Zumindest kann ich ausschließen, das irgendwas anderes dem Spiel Resourcen klaut.

Ich weiß nicht, wie verfrickelt dein PC oder dein Spiel ist, aber aufgrund der hohen Anzahl an Meldungen von dir scheint da ja irgendwas nicht ganz korrekt zu laufen.

**Comment by DerBauer2** [comment]
AMD 3600 Ist sicher kein Schlechte CPU
Wie definierst  du sauber eingefahrene Karte?

Mein PC ist denke ich ehr nicht das Problem der läuft bei allen anderen spielen  sauber es ist nur LS was ständig mit Mods probleme macht. AD ist aber immer moch eine Beta daher kann man das teilweise noch verzeihen. Mir sind schon viele dinge auf gefallen was AD noch nicht gut macht gerade so Zwischen AD & CP wenn der eine an denn anderen übergiebt. Aber leider werden wir ja keine neue version erhalten. AD ist genial im zusammenhang mit CP.

AD brauch einfach mom nich zu viel Rechenleistung was man vlt noch minimieren könnte denn die Engine von Giants is auch nicht die beste und gibt AD halt nicht genügend leistung so das die FPS fallen.

**Comment by Iwan1803** [comment]
Sauber eingefahren heißt für mich z.Bsp. 
- das ich jede Kurve mit jeder Fahrzeugkombi problemlos fahren kann
- das sich Wege nicht unnötig oft überschneiden und ich auf blaue Linien so gut es geht verzichte
- das Zielpunkte an Entnahme- & Abladetriggern so gesetzt sind, das sie mit (fast) jeder Fahrzeugkombi funktionieren
- und vieles mehr
So einige machen grundlegende Fehler bei der Kursgestaltung und schieben auftretende Probleme dann aber natürlich gerne mal auf AD.

Hast du schon mal drüber nachgedacht, das vielleicht ein paar der genutzten Mods Probleme bereiten oder du vielleicht einfach zu viele nutzt?
Ein Problem von LS19 ist übrigens die für Mods benutzte LUA-Skriptsprache, welche halt nicht Multithread-fähig ist (wie es LS19 scheinbar selber auch nicht). Dadurch wird auftretende CPU-Last einfach nicht sauber verteilt und es entstehen dann halt schon mal Engpässe.
Gestern in meinem Stream hatte ich auch massive FPS-Einbußen und selbst der Trigger für den Kärcher war plötzlich verschwunden, aber das hatte nichts mit AD zu tun. Mein Spiel lief gestern ca. 8-9 Stunden problemlos und von einem Moment auf den anderen ging dann so gut wie nichts mehr. Alle Probleme waren nach einem Spielneustart komplett verschwunden.

Im übrigen dauert ohne den Live-Modus die Berechnung einfach mal länger. Es gibt da also nicht mehr all zu viel Optimierungsspielraum.

**Comment by DerBauer2** [comment]
> Sauber eingefahren heißt für mich z.Bsp.

    das ich jede Kurve mit jeder Fahrzeugkombi problemlos fahren kann
    das sich Wege nicht unnötig oft überschneiden und ich auf blaue Linien so gut es geht verzichte
    das Zielpunkte an Entnahme- & Abladetriggern so gesetzt sind, das sie mit (fast) jeder Fahrzeugkombi funktionieren
    und vieles mehr
    So einige machen grundlegende Fehler bei der Kursgestaltung und schieben auftretende Probleme dann aber natürlich gerne mal auf AD.


oky darauf achte ich schon


> Hast du schon mal drüber nachgedacht, das vielleicht ein paar der genutzten Mods Probleme bereiten oder du vielleicht einfach zu viele nutzt?

Ja das halte ich ständig im auge aber das passert aber bei jeden Fahrzeug was AD fährt daher schlecht zu sagen das es an Mod´s liegt 

Beim Livemode is bei mir so das er nicht schneller ist ich habe es getestet und er brauch eben genaus so lang was halt komisch war

**Comment by Iwan1803** [comment]
Irgendwelche Mods im Einsatz, welche Einfluss auf die Fahrzeuge haben?
Mir fällt da z.Bsp. Real Manual Transition ein.

**Comment by DerBauer2** [comment]
Ich habe ich gearbox von Mogli12 drin

**Comment by Iwan1803** [comment]
Ich verweise jetzt noch mal hierauf: https://github.com/Stephan-S/FS19_AutoDrive/issues/1071
und auf das Log warten wir auch immer noch.

**Comment by DerBauer2** [comment]
[log.txt](https://github.com/Stephan-S/FS19_AutoDrive/files/4159899/log.txt)
