### ISSUE TITLE
lua error with RMT active

### ISSUE THREAD

**Issue by mrPassion78** [Stephan-S/FS19_AutoDrive#1074]
hi there, as soon as i have RMT mod in the folder, and i want to let a helper drive via AutoDrive, the game trows me a lua error.
even if in the tractor the RMT is disabled, the error accours 

I have no idea if this is RMT reladed or AD related, going to post this to on the AD github.

i`ll attach the log here, and that has just the bare minimum of mods enabled.
[log.txt](https://github.com/Stephan-S/FS19_AutoDrive/files/4153475/log.txt)

after that the hud is gone and i cannot get that back.

**Comment by Iwan1803** [comment]
Real Manual Transmission (RMT) seems to be incompatible with AD.
It looks like it has changed needed parameter for AD.

**Comment by mrPassion78** [comment]
thnx Iwan, i`m currently adding in mod by mod with AD active to see if some other mod causes problems, sins even without RMT in the mod folder i got the same LUA error.. if i find what it is, i`ll let you know here.
i will try the RMT mod again as last one, sins its currently not in the mod folder.

**Comment by mrPassion78** [comment]
*****UPDATE*****

found the problem, and it was Helper Advanced by BPG.
the RMT mod works perfect again with AD..

I am very sorry to have opened this topic before further investigation..
sorry guys.. keep up the good work

**Comment by Iwan1803** [comment]
Good job and nice to know, what has cause the problem.
