### ISSUE TITLE
Question about node folder

### ISSUE THREAD

**Issue by po456asd** [Stephan-S/FS19_AutoDrive#1075]
i want to know how to make this roll up folder (blue text)
![image](https://user-images.githubusercontent.com/13596788/73774285-4d04c680-47b6-11ea-9ed6-f25259f7d3ba.png)
or is there a documentation for autodrive mod somewhere? i can't find it anywhere.

already search on google for answer still no luck. so i decide to leave my question here.

thank you.

**Comment by Iwan1803** [comment]
The easiest way: check the Wiki here at 6.1.15 😉 
https://github.com/Stephan-S/FS19_AutoDrive/wiki/6-Settings#6115-usefolders

**Comment by po456asd** [comment]
wow thank you. maybe add a link to wiki folder in readme.md can be a great idea.

**Comment by po456asd** [comment]
one more question in wiki he say that enable in autodrive hud. but i can't find it in this hud. is there another hud or where is need to be click? 
![image](https://user-images.githubusercontent.com/13596788/73777122-7d9b2f00-47bb-11ea-9fe4-f3ef4f5c4dce.png)

**Comment by po456asd** [comment]
don't know if im doing it right way or not but im changing an option by config file in save folder from 1 to 2 but it working now.
![image](https://user-images.githubusercontent.com/13596788/73779965-2ba8d800-47c0-11ea-8fcd-3fd719490544.png)

**Comment by Iwan1803** [comment]
The wiki is based on an older version of AD. If you you CTRL + ALT + 0 (zero) ingame, you will get to the settings and please do changes only there.

**Comment by Stephan-S** [comment]
I guess this issue can be closed now. Thank you @Iwan1803
