### ISSUE TITLE
AD Beläd Säemaschiene wieder nicht 

### ISSUE THREAD

**Issue by DerBauer2** [Stephan-S/FS19_AutoDrive#1076]
Wieder der gleiche fehler. Ich habe das Silo extra umgemoddet das es näher zussammen stehn kann und es geht immer noch nicht. Der mod von Mogli12( https://github.com/Mogli12/VehicleControlAddon )  ist auch drausen mehr besitze ich nicht was auf die Fahrzeuge zugreift 

https://drive.google.com/file/d/13NXem-yXwkJcozbANVMJ4lQvorFm8LNG/view?usp=sharing

[log.txt](https://github.com/Stephan-S/FS19_AutoDrive/files/4161910/log.txt)

**Comment by DerBauer2** [comment]
Es ist ein fehler von AD 
Die Saatdrille wird nicht beladen wenn bei Silo leer steht warten  es geht nur bei weiterfahren

**Comment by Iwan1803** [comment]
Es liegt nicht wirklich an AD, sondern an den Silos. Ich habe letztens auch damit gekämpft und dann Silos gefunden, welche dann funktioniert haben.
https://youtu.be/Gu4ggIh1zG0

**Comment by DerBauer2** [comment]
Warum? Ich habe alle mir bekannten informationen weiter gegben und sogar ein Video erstellt das man alles nachvollziehen kann? plus Log also ist mein Threand Korekt

BlackJack155?  Ich habe nur diesen Account ? Was ist das denn jetzt für ein verhalten und unterstellung? Also dein Verhalten ist sehr unpassend  Bitte zügele dich Danke 


Vlt kann man sich ja noch mit dem Modder vom Hofpack in Kontakt setzten das dort der fehler behoben wird damit AD besser fahren kann.

**Comment by Iwan1803** [comment]
Mein Verhalten ist der Situation entsprechend und ich wüsste nicht, warum ich mich zügeln soll.

1. das Template hast du wieder mal ignoriert und ich wiederhole mich einfach nicht so gerne
2. ebenso wieder ignoriert: https://github.com/Stephan-S/FS19_AutoDrive/issues/1071
3. eine Lösung inkl. Anleitung habe ich dir genannt - probier sie aus oder lass es
4. dein Log und dein Verhalten ist seltsamerweise identisch zu dem von BlackJack155 und das ist nicht nur mir aufgefallen

Du könntest bei der Problemsuche vielleicht einfach mal aktiver werden anstatt hier ein Issue nach dem anderen zu öffnen, AD ständig irgendwelche Fehler zu unterstellen und darauf zu hoffen, das hier irgendjemand für dich die Arbeit erledigt.

**Comment by DerBauer2** [comment]
Wie unfreundlich die LS community geworden ist erschreckend !
Ich habe gesagt ich werde die Silos testen ob es damit besser geht dann kann man ja bescheid geben
Wo is das Problem das man ein Fehler meldet und schauen kann an was es liegt? Mal ehrlich ich sitze und Teste schon bevor ich eine Issue Schreibe. Aber ich habe auch  nichts besseren zu tun als Ständig Fehler zu suchen und meine zeit hier zu investieren ich kann das auch lassen. 

In Gegensatz zu dir! Kontaktiere ich die Moder der betreffenden Mods und weise sie darauf hin damit wenn sie daran Interesse haben dies zu fixen. Das liegt im Interesse von allen das Mods harmonieren also investiere ich mehr zeit rundherum als nur die Issue zu schreiben. Da kann man doch auch mal von euch ein wenig Unterstützung erwarten. Es bringt nichts zu sagen der Mod geht mit AD nicht und lädt was anders DAS is für mich Faulheilt! 

Also wenn du daran interessiert bist AD mit weiter zu verbessern dann kannst du mir auch helfen damit ich die Daten an denn Moder herantragen kann und es vlt zu einer Lösung kommen kann denn es sind kaum läute wie ich die sich so viel mühe machen und jeden tag daran sind die moder an zu schreiben die Fehler zu klären und damit Sachen gefixt werden.

Ich erwarte auch mal Dankbarkeit das Leute sich mühe machen und so viel zeit hinein stecken das LS besser wird.

Das is meine Meinung zu dem Thema. Entweder man Arbeitet zusammen oder gegen einander....

**Comment by Iwan1803** [comment]
Ich finde es erschreckend, das du es dir herausnimmst, die gesamte LS-Community als "unfreundlich" zu bezeichnen.

> Ich bin nur verantwortlich für das, was ich schreibe und nicht dafür, was du verstehst....

Hast du dir eigentlich schon mal selber durchgelesen, was du so schreibst? Das Problem ist einfach, das man zu den Wörtern kein Gesicht sieht und nie weiß, wie jemand etwas nun genau meint.
Fakt ist aber, das du sowohl hier, aber auch bei CP und VCA schon angeeckt bist. Zufall? Ich denke eher nicht...

Vielleicht mal eine Info: ich programmiere hier nicht mit, sondern manage lediglich die Issues und versuche überall zu helfen, wo ich kann. Das mache ich alles freiwillig und opfere gerne meine Zeit, um damit AD zu unterstützen und voran zu bringen.
Um aber adäquate Hilfe leisten zu können, ist es notwendig, das man auch ALLE Infos zu einem Problem mitgeteilt bekommt und nicht nur ein paar Brocken, so das man immer und immer wieder nachfragen muss.
Dazu gehört u.a. eine ausführliche Problembeschreibung inkl. verwendeter Mods und auf welcher Map mit welchen Fahrzeugen und/oder Gebäuden das Problem auftritt. Hilfreich ist dann u.a. auch das Log, ggfs. Screenshots und/oder Videos und auch eine Info, was man denn schon alles probiert hat. Auch eine Info, wenn andere Modder bereits informiert worden sind, könnte mehr als hilfreich sein.
Vieles davon hast du einfach nicht geliefert, so das wir häufiger nachfragen mussten und dann erwartest du von uns, das wir dir helfen und/oder dir auch noch dankbar sind?
Sorry, aber langsam frage ich mich echt, wo die versteckte Kamera hier ist....

**Comment by DerBauer2** [comment]
gut wenn das so gesehn wird stelle ich meine aktivitäten bezüglich der unterstüzung der mods ein 
ich werde nicht mehr meine zeit verschwenden um fehler zu melden und deren uhrsache zu untersuchen 
wenn daran kein intresse besteht das jemand bemüht ist die moder an zu schreiben und damit mehr kompatibilität in denn mods zu bekommen das kannst du nun stoltz auf dich sein

> Ich finde es erschreckend, das du es dir herausnimmst, die gesamte LS-Community als "unfreundlich" zu bezeichnen.

und es ist so!!! ich bin seid dem 15er dabei und es wurde immer schlimmer   mod klau übele nachrede ect ls is nur noch müll  man sieht es auch an modhoster   aber ihr wold das wir user uns die zeit nehem und alles durch testen und dann eine detalierten fehlerbericht zu senden?
Ich kann alle die versteh die kein bock mehr haben sich die mühe zu machen und dann so behandelt werden kein wuder warum so viele mods privat bleiben 

Mir ist es nun egal solte AD fehler vorwesen teste ich die solte es an einen mod liegen knall ich dir hier die Log und denn fehlerbericht mit Video dazu und fass dann die Issue nicht mehr an dann könnt ihr damit machen was ihr wolt  Ich bin doch nicht so blöd und vergeude meine lebnenzeit damit zu kritisiert zu werden wenn ich ein mod untersütze zumal du nicht verstaden hast was ich in dem Text geschrieben habe sowas von 0!  Es ist dir scheiß egal das dort stehn haubtsache deine meinung durch zu setzten  weil hier alle Admins gott spielen können und jeder machen kann was er will ! Mir ist das zu blöd glaub was du wilst denk von mir was du willst is mir schnuppe wenn du keinen Supporte willst dann Sperrt die Issus dann habt Ihr Ruhe!

damit wäre alles gesagt und mach damit was du willst   wie gesagt macht AD fehler supporte ich es nicht mehr 

Schönen Tag noch

**Comment by Iwan1803** [comment]
Wie sollen wir ein Problem analysieren, wenn wir nicht alle notwendigen Infos von demjenigen bekommen, welcher das Problem hat? 
Wie oft wurde AD schon ein Fehler vorgeworfen, welcher dann aber nur aufgrund von irgendwas anderem aufgetreten ist (z.Bsp. ein fehlerhaft gemoddeter Drescher, ein scheinbar inkompatibler Mod oder eine fehlerhafte Installation)? Da ist es jawohl nicht zu viel verlangt, das eine oder andere Testszenario auszuführen, um mögliche Probleme gleich auszuschließen oder aber dadurch die Ursache einzugrenzen oder etwa doch?
Wenn sich jemand dann so dermaßen uneinsichtig zeigt und völlig beratungsresistent ist wie du, die notwendigen Infos auch nach mehrfacher Nachfrage nicht vollständig rausgibt und dann auch noch beleidigt, was sollen wir dann bitte deiner Meinung nach noch machen? Zu dir nach Hause kommen, das Köpfchen streicheln und dir immer wieder sagen, was für ein Held du doch bist?
Ich spiele hier weder "Gott" noch halte ich mich für was besseres und ich habe oft genug versucht, dir zu helfen, aber wenn du so penetrant ignorierst, was man dir so schreibt, dann kann man dir einfach nicht helfen und irgendwann ist auch meine Geduld mal zu Ende.

Wenn du ein Problem mit AD hast, dann nutz es einfach nicht mehr und erspar uns weitere Meldungen, solange du nicht bereit bist, vollständige Infos abzuliefern und die eine oder andere Sache auszuprobieren. Jemandem hinterher zu laufen, welcher dann doch keine wirkliche Infos und Antworten liefert, kostet nämlich unsere kostbare Zeit.

In diesem Sinne.... schönes Leben noch!
