### ISSUE TITLE
Vehicle Type Checkpoint/Gate

### ISSUE THREAD

**Issue by cyberndj** [Stephan-S/FS19_AutoDrive#1078]
**Is your feature request related to a problem? Please describe.**

I would like only certain vehicle types to travel beyond a certain way points.
I have some fields where I have diagonal lines across them to help with combine unloading/fieldwork with different entrances/exits. I don't want trucks and cars to drive across the field because its the shortest path. Its also annoying when a truck drives across a field because its shorter than driving around on the road (and crashes/destroys crops).

Another observation. Combines have a hard time driving down some narrow roads, but there is some wide headlands that they could drive down parallel to the road without crashing.

**Describe the solution you'd like**

In edit mode, have the option to edit a way point to allow vehicles by their type to pass. Have a check box style selection to select vehicle type (or inverse it to make it restrict vehicle type). Make the default option "all vehicle types."

I was thinking vehicle types would mimic the in game categorization, but . Vehicle types could be the following:
Tractors (possibly expand it to S-M-L categories based on size/width)
Trucks
Combines
Cars
Harvesters (Beets/Potatoes etc)
Sprayers
Mowers

**Describe alternatives you've considered**

Create separate networks for different vehicle types.

**Additional context**

-Have an advanced option in the full screen menu to enable the Checkpoint/Gate screen when edit mode is open?
-Also have a new error message that is similar to can't reach destination, but has some verbiage in it like  "can't reach destination because of a checkpoint. 
-I don't know how this would work with Dijkstra's calculation for vehicle types....

**Comment by cyberndj** [comment]
Didn't see #862 until after I submitted...

**Comment by Iwan1803** [comment]
Holger-70 hatte hier eine gute Idee zu, wie man es mit der aktuellen AD-Version lösen kann. Ich habe mal auf die schnelle etwas gemalt und hoffe, man versteht das Prinzip dahinter.
Das Feld hier hat 4 Zufahrten: im Norden, Osten, Westen und Süden.
Die Zufahrt zum Feld im Norden ist nur in eine Richtung auf das Feld befahrbar, die anderen 3 Möglichkeiten sind durch die Linie nur als Ausfahrt benutzbar.
Innerhalb des Feldes ist die in beide Richtungen befahrbare blaue Linie gezogen worden. Diese darf keine Verbindung zur Linie am Startpunkt im Norden haben. Durch die grüne Linie ist die blaue Linie wieder den Wegen auf der Straße verbunden, was entsprechend auch nur in eine Richtung geht.
Somit können Fahrzeuge im Norden an das Feld heranfahren, aber es hierüber nicht mehr verlassen. Sie müssen sich über die blaue Linie eine andere Ausfahrt suchen.
Dadurch ist es nicht möglich, über das Feld eine Abkürzung zu fahren.

_Holger-70 had here a good idea how to solve it with the current AD version. I painted something on the fast one and hope you understand the principle behind it.
The field here has 4 approaches: north, east, west and south.
The access to the field in the north can only be used in one direction on the field, the other 3 possibilities can only be used as an exit by the line.
Inside the field the blue line, which can be driven in both directions, has been drawn. This line must not have any connection to the line at the starting point in the north. The green line connects the blue line with the roads, which means that it only goes in one direction.
This means that vehicles in the north can approach the peloton, but cannot leave it via this line. They have to find another exit via the blue line.
It is therefore not possible to take a shortcut across the field._

![grafik](https://user-images.githubusercontent.com/47528836/73930517-e9be8580-48d6-11ea-9ffe-54f9463bc7c8.png)

**Comment by Axel32019** [comment]
@Iwan1803 The picture is very useful, also to explain other issues. I would suggest to add it to the wiki!
Small hint (peanut collector am I :-) ): add the outgoing arrow also to Eeast.
