### ISSUE TITLE
AutoDrive und Knicklenker

### ISSUE THREAD

**Issue by ZeroxxBoy** [Stephan-S/FS19_AutoDrive#108]
Servus,
Mit ist letztens aufgefallen, als ich den Radlader vom Hof zum Shop fahren lassen wollte, dass Autodrive schwirigkeiten hat zu lenken bzw gar nicht lenkt.
Lg

**Comment by Scaracuila** [comment]
Hi,

in der Version vom LS17 konnte AD auch nicht mit Hecklenkern umgehen, das funktioniert ja jetzt super! Ich könnte mir vorstellen, dass der Code da noch nicht so weit ist!

Grüße Scara

**Comment by BerndUwe** [comment]
also mit dem radlader und dem forstgerät scorpion king hab ich probleme da gehts nicht
