### ISSUE TITLE
Default course configs can't be opend in the editor 

### ISSUE THREAD

**Issue by Efratror** [Stephan-S/FS19_AutoDrive#1080]
AutoDrive Version: 1.0.7.0
Release or custom zip: Release

When opening a config from the courses folder in the editor. The cmd interface trows an exception. Only the eihersholt config opens fine. The exaption is caused by line 202 in AutoDrive Editor.java and line 59 in EditorListener.java compairing the files I discoverd that the eihershold config has a group tag with in the mapmarkers tags. 

I will try to update the other config files tomorrow

**Comment by Stephan-S** [comment]
Thank you for your work, I will merge them now
