### ISSUE TITLE
"Choose next Waypoint" isnt working

### ISSUE THREAD

**Issue by Kamiikaze** [Stephan-S/FS19_AutoDrive#1083]
AutoDrive Version: 1.0.7.0
Release or selbsterstelltes zip: Release
Karte (falls relevant): Felsbrunn
Fahrzeug(art) (falls relevant): Alle

**Beschreibe den Bug**
Es lassen sich keine Wegpunkte verbinden, da die gelbe Linie immer auf einen Wegpunkt ist und sich nicht ändern lässt. Beim drücken des Buttons passiert nichts. Ich habe die .xml im savegame-Ordner schon gelöscht und den Mod neu runtergeladen.

**Falls anwendbar - Schritte mit denen ich den Bug nachstellen kann**

**Screenshots**
https://i.imgur.com/G4HhQDs.png
![image](https://user-images.githubusercontent.com/13954000/74139452-ac6a3880-4bf3-11ea-8ceb-e7dc198fb938.png)

**Comment by Iwan1803** [comment]
Versuch es mal mit der Dev-Version:
https://www.crazy-iwan.de/mods/FS19_AutoDrive.zip

**Comment by Kamiikaze** [comment]
Funktioniert nun, danke :)
Was mir aber noch aufgefallen ist...

2 Traktoren hatten zB "Silo" als Ziel, den 1. Traktor habe ich auf Hafen gestellt und hinfahren lassen. Dann bin ich in den 2. Eingestiegen und dort war dann automatisch Hafen ausgewählt, aber er ist dann zu Silo gefahren. Also es war wohl in der Liste dann Hafen als "ausgewählt" drinnen aber ansich war er noch auf Ziel Silo.

**Comment by Michael170978** [comment]
> Versuch es mal mit der Dev-Version:
> https://www.crazy-iwan.de/mods/FS19_AutoDrive.zip

Hi Iwan. Mich verwirt dein Link ein wenig. Kümmerst du dich zur Zeit alleine um Autodrive?

**Comment by Iwan1803** [comment]
Ja und Nein, ich habe halt immer eine fertig gepackte Dev-Version auf meinem Webserver liegen.
Ist einfacher als jemandem zu erklären, wie er das selber runterladen und packen muss, wobei ich dafür auch eine Anleitung hätte:
https://youtu.be/LfR0ZkFjMWI

**Comment by Michael170978** [comment]
> Ja und Nein, ich habe halt immer eine fertig gepackte Dev-Version auf meinem Webserver liegen.
> Ist einfacher als jemandem zu erklären, wie er das selber runterladen und packen muss, wobei ich dafür auch eine Anleitung hätte:
> https://youtu.be/LfR0ZkFjMWI

Meinst du Autodrive hat noch eine Zukunft? Es sieht so aus, als ob der Stefan ausgebrannt wäre. Vielleicht hat er sich übernommen. Und bei dem Ton von manchen Usern, hätte ich aber auch keinen Bock mehr.

**Comment by Iwan1803** [comment]
Es wäre mehr als unschön, sollte Stephan aufhören, aber wie soll er das alleine stemmen? Es haben ihn ja mal 2 oder 3 Dev unterstützt, aber wo sind die hin?
User mit schlechten Manieren gibt es überall, aber die kann man ja loswerden.

Ganz ehrlich? Aktuell sehe ich nicht, das es mit AD weitergehen wird, obwohl es eine super Sache ist.
