### ISSUE TITLE
Autodrive stops at weighbridge Emerald Coast

### ISSUE THREAD

**Issue by jgrimshaw01** [Stephan-S/FS19_AutoDrive#1085]
AutoDrive Version: 1.0.7.0.36
Release or custom zip: Dev 
Map (if applicable): Emerals Coast v3.0
Vehicle / type (applicable): MF7719 + TKD 302 Trailer

**Describe the bug**
Course stops at weighbridge coming in or out of Southern Ag crop sales

**If applicable - Steps to reproduce the behavior**

**Screenshots**
![20200210122101_1](https://user-images.githubusercontent.com/45140772/74150915-db3bdb00-4c02-11ea-8e2a-6ed7ad90937e.jpg)

![20200210122346_1](https://user-images.githubusercontent.com/45140772/74150927-e2fb7f80-4c02-11ea-8e1e-b86f9c2ee331.jpg)

**Comment by Axel32019** [comment]
@jgrimshaw01 What happens if you disable collision detection in AD?

**Comment by jgrimshaw01** [comment]
Never thought of that will try in the morning

**Comment by Axel32019** [comment]
@jgrimshaw01 This is just to figure out if there might be something wrong with the trigger of the weight station. I will have a look at this map tomorrow.

**Comment by jgrimshaw01** [comment]
@Axel32019 Turning off collision detection does indeed work going to check the map in the editor

**Comment by Axel32019** [comment]
@jgrimshaw01 The issue are the collisionmasks of the weightTrigger where all bits are set. So it is an issue of the map, not AD. You may report this to the map creator.
If you are able to change something in the i3d file, you can apply the following fix:
In file mapEC.i3d search for "weightTrigger". Replace collisionMask="2147483647" in this line with collisionMask="14680064". I found it 3 times in that file. After that AD and the weigth display are working as expected :-)

**Comment by jgrimshaw01** [comment]
@Axel32019  Thanks for the info, I tried to look for the collision but being as I'm new to the editor I didn't know where to look once I'd selected the weighbridge trigger, I only installed the editor this morning.
Regards
John Grimshaw
