### ISSUE TITLE
Mod Konflikt mit Global Company

### ISSUE THREAD

**Issue by DerBauer2** [Stephan-S/FS19_AutoDrive#1086]
AutoDrive Version: 1.0.7.0-37 

Hallo es besteht ein konflikt mit Autodrive das wenn AD Kurse Berechnet das dadurch die Berechnugn verlängert und es zu PFS abfall kommt.
Getestet auf der Multimap und nur mit der Notwendigen Mods.

Die Errors sind von Modmanage der die Mods Deaktiviert hat und sie dadruch nich lesen kann. Für mich was es so Leichter zu Testen.

Bei weiteren Fragen stehe ich gerne zur verfügung.

PS. ich wurde von kevin98 hier her verwiesen das AD das Problem seih
![grafik](https://user-images.githubusercontent.com/60297613/74153623-55735c00-4c11-11ea-98af-b87e029934cf.png)

[log.txt](https://github.com/Stephan-S/FS19_AutoDrive/files/4180866/log.txt)

**Comment by Iwan1803** [comment]
Bauer_Heins, DerBauer2 oder welche Nicks du auch sonst noch auf den div. Plattformen nutzt:
du lernst es einfach nicht und ignorierst auch weiterhin penetrant, was andere schreiben.
1. GC hat mit AD nichts zu tun, aber wenn dein Rechner überlastet ist, wirkt sich das auf alles aus
2. die Probleme liegen wohl nicht an AD, denn viele andere spielen damit problemlos auf der Multimap
3. dein Log hat etliche Warning und Error, welche du ignorierst
Somit ist es kein Supportfall für AD, denn das Problem sitzt in diesem Spezialfall wohl eher vor dem Bildschirm.
