### ISSUE TITLE
#1086

### ISSUE THREAD

**Issue by DerBauer2** [Stephan-S/FS19_AutoDrive#1087]
@Iwan1803 Ich habe langsam die schnauze gestrichen voll von diesen scheiß hier!!!! ES LIEGT AM FUCKING AD!!! 
Ich habe mich an  kevin gewant da nur die beiden mods aktiv waren und ich das Problem auf trat als ich GC deakivierte! Heißt es liegt an AD!  von kevin98 kam das er nichts machen kann was ich dir verdammt noch mal auch als screen geschickt habe! und die log errors waren vom mod manage was ich extra geschrieben habe aber du kannst wohl nicht lesen!!! Wenn du als Admin hier zu übervodert bist ad zu supporten dann lass es einfach  du hilft einfach nimanden!!! Wie dumm is bitte die ausage Nimand anders hat das ???!! Junge du regst mich so dermassen auf das ich kein bock mehr habe ls zu spielen  wie kann man nur so egoisttisch sein und nur seine iteressen durch zu setzten !! ich habe denn ganzen tag damit verschwendet raus zu finden welcher mod das ist dann GC es gemeldet da wurde ich an AD vervisen und nun kommst du mir wider so Dämlich! Noch mal für dumme ES LIEGT AN AD!!! und eine bekloppte aus sage zu tätigen das mein pc schuld wäre oder ich ist beleidugend du was du dir eigl raus nimmst !!! 2070  Ryzen 3600 32 gb DDR4 3000Mhz ist wohl nich low für fucking AD! Was du überhaubt willst!? Ich habe dir alle notwenigend daten geschickt die log und die beschreibung an welchen mod es liegt  dann kannst du mal dein Job machen und das supporten denn mehr infos kann man nicht dazu geben wenn nur die mods an sind und mehr fehler quellen aus geschlossen wurden 

frag mich wie alt du eigl. bist 18-20? das würde erklären weswegen das mit dir nichts wird

Denkste ich stecke in das save 2 monate zeit hinein um mir dann sagen zu lassen das ich schuld an einem mod fehler bin ? wie dumm muss man eigl sein?! Ganz erlich lass es sein wenn du es nicht schafst vernüftig mit supporter um zu gehn   aber du bekommst es ja nicht gebacken mal nach zu fragen wieso oder weshalb nein du bildest dir ein gott zu spielen und schließt einfach issue weil du zu faul bist dich durch wohlmögliche fehler zu arbeiten aber ich soll meine freien tage dazu verschweden dir jeden einzelen fehlercode vor die nase zu legen weil ich ja auch moder bin und das auch kann !! NEIN kann ich nicht dazu seid ihr zu ständig um fehler zu finden die user können nur helfen denn fehler einzu kreisen 

ABER scheiß auf AD mir reichts meine kostbare lebenzeit für scheiß fehlersuche zu verschwenden um dann nicht mal hilfe zu bekommen!!  Danke das du mir lebenzeit stillst! 
mir rechts ich scheiß auf mods  wenn man so behandelt würd  Supporten denn dreck alleine ich bin raus ich werde keine einzige secunde mehr daran verschwendne fehler zu suchen   geht er nicht wird er gelöscht und allen erzählt das der mod scheiße ist so wie dieser  
Bin fertig mit dir und LS  Ciao!

**Comment by Tensuko** [comment]
Dafür das du hier nichts mehr melden wolltest schreibst du aber ganz schön lange Texte.

**Comment by Justice-Molton** [comment]
Und bitte achte mal auf deine Rechtschreibung. Man kann diese langen Aneinanderreihungen kaum lesen.

**Comment by Iwan1803** [comment]
Du bekommst keine Hilfe? Zu den Beleidigungen kommen nun also auch noch Lügen dazu, bravo!
Wie oft habe ich dir geschrieben, was du machen sollst, aber nein, lieber auf den Putz hauen und dann wilde Schimpftiraden ablassen.
Du würdest (mehr) Hilfe bekommen, wenn du endlich mal Lesen und vor allem Machen würdest, was man dir so schreibt, aber du ignorierst penetrant alles und von jedem - nicht nur von mir und nicht nur hier bei AD, sondern auch woanders (z.Bsp. bei VCA und LS-Modcompany).
Da frag ich mich, warum du deine ach so kostbare Lebenszeit mit sinnlosen und unnützen Tests verschwendest, welche der Ursachenforschung einfach nicht dienlich sind. Dazu kommt dann noch die Zeit, in der du diese langen und schwer lesbaren Texten schreibst, die nur so von "ihr seit Schuld" strotzen.
Aber es ist ja immer einfacher, den Fehler bei anderen zu suchen anstatt sich selber mal welche einzugestehen, gell?
Du bist sowas von beratungsresistent, das man dir einfach nicht helfen kann.


PS: ich kann deine Beiträge hier und auch deine Kommentare auf Youtube schneller löschen als du sie schreiben kannst oder möchtest du noch mehr Zeit in deinem Leben verschwenden?

**Comment by seeske123** [comment]
Bravo Team

**Comment by jgrimshaw01** [comment]
What an absolute disgraceful rant, did this guy pay for AD ? I think not people who use there time and skill to provide a mod to make the game more enjoyable for the rest of us should be applauded for there efforts this is an ongoing project and there will be bugs, all we can do as users is to let the devs know and hope that together we can make the bugs less likely to appear.

**Comment by Dzi4d3k** [comment]
Spamming personal frustration doesn't help at all. These kind of demanding post are kind of worst class hate in my opinion. I we get something for free we should be graceful to givers, as we al not force to take (and use) the gift. And the same here no one force anybody to use AD mod, so I suggest to be more helpful or leave this part of FS community for the peace sake of the rest that stay here..

**Comment by Iwan1803** [comment]
He will continue to ignore everything that is written here and elsewhere. Some learn from their mistakes, but not him.
There's been enough writing, so i'll just close up here...
