### ISSUE TITLE
FPS loss on "Unload Combine" & "Pickup and Deliver"

### ISSUE THREAD

**Issue by Iwan1803** [Stephan-S/FS19_AutoDrive#1089]
AutoDrive Version: 1.0.7.0-37
Release or selbsterstelltes zip: selbsterstellt
Karte (falls relevant): NFM 4x
Fahrzeug(art) (falls relevant): diverse

**Beschreibe den Bug**
Bei "Abholen und Liefern" sowie "Drescher abtanken" kommt es ab und zu vor, das die CPU-Last enorm hoch geht und die FPS entsprechend drastisch einbrechen. Stoppe ich das Fahrzeug, normalisiert es sich quasi sofort wieder. Starte ich das Fahrzeug ohne Änderung wieder, geht es vorne los. Ein 2. Fahrzeug, was den selben Kurs drin hat, macht hingegen keine Probleme.
Im Log tauchen zu diesem Zeitpunkt keinerlei Fehler auf. Die Berechnungsgeschwindigkeit steht auf 1x, eine Änderung hat aber dank aktivem Live-Modus keine Auswirkung.

**Falls anwendbar - Schritte mit denen ich den Bug nachstellen kann**
Das Problem taucht sporadisch auf, aber je länger ein Spiel läuft, desto häufiger tritt er auf.

**Screenshots**
Anbei Screenshots von einem Abfahrer (keine Mods):
-  vor Aktivierung:
![fsScreen_2020_02_13_14_44_11](https://user-images.githubusercontent.com/47528836/74442315-923d8e00-4e71-11ea-9c73-5d179b41e259.png)
- nach Aktivierung:
![fsScreen_2020_02_13_14_44_16](https://user-images.githubusercontent.com/47528836/74442341-9ff31380-4e71-11ea-872a-9458b15ec4c2.png)
- nach Änderung Modus:
![fsScreen_2020_02_13_14_45_00](https://user-images.githubusercontent.com/47528836/74442372-af725c80-4e71-11ea-8837-c763a8806610.png)

**Comment by Iwan1803** [comment]
Ein Neustart des Spiels behebt das Problem, aber nach unbestimmter längerer Spieldauer fängt es wieder an.

**Comment by Tensuko** [comment]
Die Erntemaschine hat unter Advanced Settings aber nicht 'Self Unload' auf aktiviert stehen oder ?

**Comment by Iwan1803** [comment]
Nein, ist bei allen Fahrzeugen in CP deaktiviert.
Da die Fahrzeuge per AD unterwegs sind, würde es mich auch wundern, wenn CP da mit reinspielt.
Außerdem ist es ja nicht nur bei Abfahrern, sondern auch bei Abholen&Liefern.
Es ist halt sehr sporadisch. Vorhin trat es nach ca. 4 Stunden auf, Spiel neugestartet, 30 Minuten Ruhe gehabt, dann der gleiche Terror. Also wieder Spiel neu gestartet und jetzt läuft es seit ca. 3 Stunden problemlos.
Bisher habe ich aber auch nichts in die Nähe von meinen Tierställen oder eine Frucht von der NFM transportiert. Die nächsten Touren werde ich mir mal notieren, ob es da irgendeine Auffälligkeit gibt.

**Comment by Stephan-S** [comment]
Moin Iwan, kannst du mal alles Debugsettings einstellen wenn so etwas vorkommt? Bzw. siehts ja so aus als hättest du das schon.
Wird dabei wirklich nichts geloggt, was auf einen Fehler hindeutet?
Springen die Zustände in der Infotabelle die du dir anzeigen lässt wild hin und her?
Könnte mit der Erkennung der Beladung zusammen hängen. Er zeigt den vollen Hänger ja nicht als volles Gespann an.

**Comment by Iwan1803** [comment]
Das Problem trat nicht nur mit den Karotten auf diesem LKW auf. Die Screenshots sind nur da entstanden, als das Problem wieder mal auftrat. Die meiste Zeit klappte das Abfahren problemlos und das auch mit 2 LKWs an diesem Ernter.
Ich hatte es z.Bsp. auch beim Abholen & Abliefern von Stroh.
Da es sehr sporadisch auftrat, kann ich da keine genaue Aussage zu machen und werde es weiter beobachten, vor allem wohin bei mir gefahren werden soll. Ich vermute nämlich, das es da irgendein Problem in dem "Zielgebiet" gibt, was aber eben nicht immer auftritt.

**Comment by Iwan1803** [comment]
Heute ist das Problem auch wieder aufgetreten:
- Trecker 1 mit Wasseranhänger, Entnahme am Wassertank, Auslieferung an die Ziele in einem Ordner
- Trecker 2 mit Anhänger, Entnahme Rübenschnitzel aus Zuckerfabrik, Entladen an BGA
Folgendes ist in der Konsole aufgetaucht und hat sich ständig wiederholt:
![fsScreen_2020_02_17_20_01_03](https://user-images.githubusercontent.com/47528836/74680422-d9ed4e00-51c0-11ea-970b-8252d2753398.jpg)

**Comment by Iwan1803** [comment]
Die FPS loss sind nicht mehr aufgetaucht und es gab ja auch ein Update in Verbindung mit GC.
Sollte es noch mal auftauchen, werde ich ein neues Issue öffnen.
