### ISSUE TITLE
Zielpunkte löschen?

### ISSUE THREAD

**Issue by sdl112** [Stephan-S/FS19_AutoDrive#109]
Hallo, gibt es eine Möglichkeit, Zielpunkte zu löschen? Also Lade und Abadepunkte etc.

schöne Grüße, Simmal

**Comment by Scaracuila** [comment]
Hi, ja geht!

der Button obere Reihe, zweiter von rechts. Danach musst du aber die Wegpunkte neu verbinden, wenn der Zielpunkt in einer Kurve war evtl. noch einen einzelnen Wegpunkt setzen und diesen dann mit der Strecke wieder verbinden! Es wird der Punkt gelöscht, auf den die rote Linie zeigt!

Grüße Scara

![grafik](https://user-images.githubusercontent.com/34663971/57246891-ab8df000-703e-11e9-83ac-6d1a51a424b3.png)

**Comment by Stephan-S** [comment]
Es gibt auch eine belegbare Tastenbelegung um wirklich nur "Das Ziel" zu löschen.
Musst du dir selber in den Tastaturoptionen belegen. Dann wie gewohnt mit der roten Linie an den Punkt fahren und eben diese Taste drücken. Dann bleibt der Punkt erhalten, aber das Ziel verschwindet

**Comment by sdl112** [comment]
Danke,
 das werd ich so nochmal versuchen.

**Comment by Scaracuila** [comment]
Sorry, bin Lenkradspieler, aber danke für den Tip!

**Comment by Stephan-S** [comment]
Ich nehme an, mit der Bedienung gab es kein Problem. Falls doch, bitte das Issue wieder öffnen :-)
