### ISSUE TITLE
AutoDriveDijkstra.lua:169

### ISSUE THREAD

**Issue by spielera** [Stephan-S/FS19_AutoDrive#1090]
AutoDrive Version: 1.0.7.0 - 037
 selbsterstelltes zip
Karte MultiMap2019
Keine

Info: [AutoDrive] 19:36:15 Recalculating started
2020-02-13 19:46 Error: Running LUA method 'update'.
2020-02-13 19:46 C:/Users/admin/Documents/My Games/FarmingSimulator2019/mods/FS19_AutoDrive/scripts/AutoDriveDijkstra.lua:169: attempt to get length of a number value
2020-02-13 19:46 Error: Running LUA method 'update'.

Neuen Kurs eingefahren, und dann auf Aktualisierung gedrückt 
Bei 96% ist das gesamte Spiel abgestürzt.

Ich danke dir für deine viele Arbeit, das Programm ist echt Spitze. Mach weiter so.
Kommt eventuell mal ein Rückwärtsgang rein, wegen einparken?
mfg Dom :D

**Comment by Iwan1803** [comment]
Hast du den Live-Modus deaktiviert, das du eine Berechnung (Aktualisierung) durchführen lässt?

**Comment by spielera** [comment]
Du meinst, alle AD Fahrzeuge ausgeschaltet?
Nein, das habe ich nicht gemacht.
Einige CP Fahrzeuge liefen auch noch.

**Comment by Stephan-S** [comment]
Vielen Dank für die Meldung.
Ich probiere gerade nachzuvollziehen, wie das passieren kann.

Kannst du es reproduzuieren, wenn du noch einmal auf Berechnen klickst oder funktioniert es dann erstmal wieder?

**Comment by spielera** [comment]
Reproduzieren, lässt es sich. Diesemal bei 42 %.
Nach spiel-Neustart, läuft AD wieder ohne Probleme. Der Kurs, der bei der Aktualisierung eingetragen werden sollte, ist komischer, trotzt Abbruch bei 96% mit drin.

**Comment by Stephan-S** [comment]
alles klar. Dann schick mir doch bitte mal deine AD config. Da könnte sich ein Fehler eingeschlichen haben.

Nur als kurze Erklärung. Dein Kurs ist so oder so in der config sobald du speicherst. Aber nur die Position und Verbindungen des neuen Kurs.
Da die Neuberechnung abgebrochen ist, fehlen also die vorgerechneten Routen um diese Strecke zu nutzen.
Wenn du aber den Live-Modus nutzt, der inzwischen ja standardmäßig eingeschaltet ist, brauchst du diese Berechnung sowieso nicht mehr, da so nur bei Bedarf genau die benötigte Route schnell errechnet wird.

**Comment by Stephan-S** [comment]
Und die nächste Frage noch, nur um das auszuschließen:
Hast du während die Berechnung lief noch weitere Dinge am Kurs geändert. Also neu aufgenommen, wegpunkte/ziele entfernt oder Verbindungen erstellt/gelöscht?

**Comment by spielera** [comment]
Beim ersten mal, habe ich nur einen Weg hinzugefügt, 2 Straßen mit einander verbunden.
Bei der Reproduzierung, habe ich nix neues hinzugefügt, einfach nur aktualisiert

Wo finde ich die AD config, die du haben willst??

.

**Comment by Blithe89** [comment]
Das dürfte die AD Config sein, oder?:
C:\Users\[Profil]\Documents\My Games\FarmingSimulator2019\savegameX

AutoDrive_[Kartenname]_config.xml


Zumindest stehen da die Einstellungen drin.

**Comment by spielera** [comment]
Hi Blithe89,
ich kann hier leider keine xml - Datei Posten, und sie ist 59 MB groß.
Ich kopiere mal den Anfang, und das Ende rein.
`<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<AutoDrive>
    <Version>1.0.7.0-37</Version>
    <Recalculation>true</Recalculation>
    <HudX>0.861067</HudX>
    <HudY>0.549815</HudY>
    <HudShow>true</HudShow>
    <lastSetSpeed>50.000000</lastSetSpeed>
    <exitField>3.000000</exitField>
    <guiScale>1.000000</guiScale>
    <autoConnectEnd>1.000000</autoConnectEnd>
    <useFastestRoute>2.000000</useFastestRoute>
    <parkInField>1.000000</parkInField>
    <lookAheadBraking>5.000000</lookAheadBraking>
    <avoidMarkers>1.000000</avoidMarkers>
    <driverWages>1.000000</driverWages>
    <unloadFillLevel>10.000000</unloadFillLevel>
    <autoConnectStart>2.000000</autoConnectStart>
    <smoothField>2.000000</smoothField>
    <findDriver>1.000000</findDriver>
    <continueOnEmptySilo>1.000000</continueOnEmptySilo>
    <mapMarkerDetour>7.000000</mapMarkerDetour>
    <showHelp>2.000000</showHelp>
    <lookAheadTurning>4.000000</lookAheadTurning>
    <pipeOffset>24.000000</pipeOffset>
    <Multimap_2019>
        <waypoints>`
</waypoints>
        <mapmarker>
`</Multimap_2019>
    <recalculationSpeed>8.000000</recalculationSpeed>
    <pathFinderTime>1.000000</pathFinderTime>
    <shovelWidth>1.000000</shovelWidth>
    <refillSeedAndFertilizer>2.000000</refillSeedAndFertilizer>
    <enableTrafficDetection>1.000000</enableTrafficDetection>
    <allowConsoleStyle>1.000000</allowConsoleStyle>
    <trailerOffset>21.000000</trailerOffset>
    <showNextPath>2.000000</showNextPath>
    <avoidFruit>1.000000</avoidFruit>
    <lineHeight>1.000000</lineHeight>
    <useFolders>2.000000</useFolders>
    <preCallLevel>7.000000</preCallLevel>
    <chaseCombine>2.000000</chaseCombine>
    <preCallDriver>2.000000</preCallDriver>
    <distributeToFolder>1.000000</distributeToFolder>
    <maxTriggerDistance>3.000000</maxTriggerDistance>
    <restrictToField>1.000000</restrictToField>
    <useBeaconLights>1.000000</useBeaconLights>
    <showTooltips>2.000000</showTooltips>
    <autoRefuel>2.000000</autoRefuel>
    <autoRecalculate>1.000000</autoRecalculate>
    <shovelHeight>26.000000</shovelHeight>
    <followDistance>21.000000</followDistance>
    <fuelSaving>2.000000</fuelSaving>
    <useLiveMode>2.000000</useLiveMode>
    <showMarkersOnMap>2.000000</showMarkersOnMap>
    <experimentalFeatures>
        <smootherDriving enabled="true"/>
        <redLinePosition enabled="false"/>
    </experimentalFeatures>
</AutoDrive>`

**Comment by Iwan1803** [comment]
Dann ZIP die Datei doch mal.

**Comment by spielera** [comment]
Gute Idee, mit der Zip.
[AutoDrive_Multimap_2019_config.zip](https://github.com/Stephan-S/FS19_AutoDrive/files/4205597/AutoDrive_Multimap_2019_config.zip)

**Comment by Stephan-S** [comment]
Danke für die config.

Zuerst einmal, ist deine so rießig, weil du scheinbar Ziele definiert hast, die nicht von überall aus erreichbar sind. Du hast also vermutlich irgendwo eine Lücke in deinem Streckennetz und dadurch einen Teil davon losgekoppelt vom Rest. Dann greifen die Optimierungen beim Speichern leider nicht mehr.

Aber, ich habe mit deiner config eine Neuberechnung durchlaufen lassen und dabei gar keine Fehler oder Probleme bekommen. Bist du sicher, dass du genau mit dieser config und ohne dabei Änderungen vorzunehmen diesen Fehler bekommst/bekommen hast?

Danke für die Infos

**Comment by Stephan-S** [comment]
Ich habe die alte Berechnungsmethode gerade aus dem Code genommen, also kann der Fehler auch vorerst nicht mehr auftauchen. Also einmal updaten bitte :-) Dann mache ich hier erstmal zu :-)
