### ISSUE TITLE
AutoDrive Course Editor Editing Problem

### ISSUE THREAD

**Issue by RUGhost** [Stephan-S/FS19_AutoDrive#1091]
AutoDrive Version: 1.0.7.0
Release or custom zip: Release
Map (if applicable): Eiersholt
Vehicle / type (applicable):

**Describe the bug**
In AutoDrive Course Editor I load the "AutoDrive_Eiersholt_config" file and it automatically load the map image but the way point does not match with the map road. I had tried with 4x, 16x option but non of those work.

 
Sorry for my bad English. I attached a map photo and the config file in a zip for better understanding.
Thanks.
[Config and PDA image.zip](https://github.com/Stephan-S/FS19_AutoDrive/files/4206559/Config.and.PDA.image.zip)

**Screenshots**
![Untitled](https://user-images.githubusercontent.com/48012198/74563260-9adbb480-4f96-11ea-991a-65cf4036d452.png)

**Comment by Stephan-S** [comment]
You have to select the 4x/16x buttons before opening/loading the config file. This should do the trick
