### ISSUE TITLE
AD auf dem dedi Server

### ISSUE THREAD

**Issue by nicki0705** [Stephan-S/FS19_AutoDrive#1092]
Hallo!!!!

Haben hier den AD heruntergeladen, die neueste Version. Haben die Kurse unserer Karte die wir spielen mit in den AD Ordner gelegt und auf den Server aufgespielt. Jeder mitspieler hat dieses ebenfalls in seinem Ordner. Wenn wir auf den Server gehen synchronisiert der AD und lädt die Kurse hoch, beim ersten funktioniert dies ohne Probleme. Sobald der nächste auf den Server kommt fängt der AD erneut an zu synchronisieren und bleibt dann irgendwann stehen, hat aber die Kurse nicht komplett geladen.  Bitte um eure mithilfe ob wir etwas falsch packen oder wo liegt der Fehler. Oder kann ich den AD nicht auf dem Server nutzen.
Wir spielen die Oberthal, sind dort auch MP Tester
Kurse wurden von einem LS Mapping Team Mitglied dort erstellt. Im Singleplayer funktioniert dieser einwandfrei.

Hoffe ihr könnt mir helfen.

MFG Nicki0705

Hello!!!!

Have downloaded the AD here, the latest version. We have put the courses of our card we play into the AD folder and uploaded them to the server. Every player has this in his folder as well. When we go to the server, the AD synchronizes and uploads the courses, the first time this works without problems. As soon as the next player arrives on the server, the AD starts to synchronize again and then stops at some point, but has not completely loaded the courses.  Please help us if we pack something wrong or where is the error. Or can I not use the AD on the server.
We play the Oberthal, are there also MP testers
Courses were created by a LS Mapping Team member there. In the Singleplayer it works perfectly.

Hope you can help me.

MFG Nicki0705

**Comment by Stephan-S** [comment]
Hallo,

ich bräuchte mal die Logs (Server und Client) um zu sehen ob es irgendwelche Fehlermeldungen gab

**Comment by nicki0705** [comment]
Wir sind vom LS Mapping Team, sind keine Fehler in der Server log und auch nicht in der client log.
Heute abend ist der Admin da, da kann er sie mir dann schicken und ich leite sie dann weiter.
[log.txt](https://github.com/Stephan-S/FS19_AutoDrive/files/4214829/log.txt)
zumindest schon mal client log

**Comment by nicki0705** [comment]
[serverlog.txt](https://github.com/Stephan-S/FS19_AutoDrive/files/4214912/serverlog.txt)

das andere ist die Gamelog 
[message.txt](https://github.com/Stephan-S/FS19_AutoDrive/files/4214918/message.txt)

**Comment by Blithe89** [comment]
Hi,


ich hatte ein paar Tage vorher einen ähnlichen Issue (1088) gestartet. 
Seid ihr sicher, dass es der Mod wirklich aktuell ist?

Seit diesem WE funktioniert es nämlich bei uns(davor nicht). (Danke nochmal an Stephan-S! und Axel für die Umarbeitung) Also lieber nochmal die aktuelle Version hier nehmen und bei allen drauf spielen. 

(Sorry, wenn ich hier irgendwas falsches gesagt habe)

**Comment by nicki0705** [comment]
welche version habt ihr drauf? @Blithe89

**Comment by Blithe89** [comment]
Bin ich mir selbst nicht ganz sicher (siehe letzter Beitrag vom Issue 1088).1.0.7.0; Dev 40 oder 46.

Aber der Stephan-S hat ja jetzt nochmal eine 1.0.7.1. released (die auch schon wieder ein Hotfix hat). Wir waren eins vorher glaube.

Ich würde aber bei Update immer die Dev Version nehmen. Also sprich den Code(master) runterladen und den "eigentlichen" Mod(ordner) FS19_AutoDrive zippen und im Modornder einfügen.

**Comment by nicki0705** [comment]
wir versuchen es mal, danke schon mal

**Comment by Iwan1803** [comment]
Wo und wie lädt und installiert man AutoDrive? 
Außerdem erkläre ich die Unterschiede zwischen der Release- und der Dev-Version 😎
https://youtu.be/LfR0ZkFjMWI

**Comment by Blithe89** [comment]
Also ich habe mal in das Video geguckt vom Iwan. Habe mich jetzt hauptsächlich nur auf den Installpart beschränkt und muss sagen: "Top"! Schön erklärt, One-Shot, ohne große Schnörkel.
Genau das richtige für den Start.

[Offtopic:
@Iwan1803 
Vielleicht mehrere Videos machen, mit entsprechenden Verweisen? 1,5h ist immer bissl kritisch mit einmal angucken. Und dann will man nochmal was wissen und skipped wie blöd. 
Oder in der Beschreibung Links die an die entsprechende Stelle skippen. 

War grade bei einer Stelle wo du gesagt hast, nicht mehr als 90Grad beim abbiegen für die Wegpunkte. Ich glaube bei mir muss ich den Winkel noch viel geringer ansetzen. Habe einige Überlange Fahrzeuge, die bleiben dann hinten irgendwo hängen, und schwere Fahrzeuge, die schiebt es über die Punkte hinaus. Versuchen aber immer den nächsten Punkt zu erreichen. Was passiert? Bleiben stecken, oder drehen im Kreis. Vielleicht irgendein Profitipp?  ]

**Comment by Iwan1803** [comment]
[offtopic]
Danke schön! 
Da es Livestreams sind, können die auch schon mal länger dauern, aber ich werde deine Vorschläge berücksichtigen, wobei das mit den Sprungpunkten ein bisschen problematisch ist, da man gerne mal vom einem zum anderen Thema wechselt.
Ich zeichne meine Strecken eigentlich immer mit einem großen Trecker und einem großen Anhänger auf. Das funktioniert eigentlich soweit einwandfrei. Vielleicht mache ich noch mal ein Howto bzgl. Strecken aufzeichnen.

**Comment by nicki0705** [comment]
Es gibt halt recht wenig Material zum einrichten beim MP, da wir bei uns im Forum auch mithelfen müssen, falls Probleme mit AD auftauchen, sollten wir schon wissen wie es funktioniert.

Sage da schon mal vielen lieben Dank für die Hilfe

**Comment by Iwan1803** [comment]
Eigentlich gibt es da nicht viel zu beachten:
- alle müssen die gleiche AD-Version haben
- die Strecken müssen auf dem Server liegen (savegame-Ordner)
- nur Admins können neue Strecken hinzufügen/aufzeichnen

Falls ich was falsch verstanden habe, dann bitte korrigieren.

**Comment by Stephan-S** [comment]
Hallo, da wir gerade die neue restrukturierte Version von AutoDrive released haben, können wir leider keine Bugs und Issues die sich noch auf die alte Codebasis beziehen mehr bearbeiten.
Wenn das Problem bzw. dein Anliegen in der atkuellen Version weiterhin besteht, mache doch bitte ein neues Issue mit allen benötigten Informationen auf.
Oder melde dich bei kleineren Themen und Fragen auch gerne direkt im Discord:
https://discord.gg/sUQtKhB

Vielen Dank für dein Verständniss und ich hoffe du hast weiterhin Spaß am AutoDrive Mod :-)

Und hier noch ein Link zur aktuellen Version:
https://github.com/Stephan-S/FS19_AutoDrive/releases/tag/1.1.0.0
