### ISSUE TITLE
Probleme mit Courseplay Editor

### ISSUE THREAD

**Issue by Mannie313** [Stephan-S/FS19_AutoDrive#1094]
AutoDrive Version: 1.0.7.1
Release or selbsterstelltes zip: Release
Karte (falls relevant): Alle
Fahrzeug(art) (falls relevant):

**Beschreibe den Bug**
Eine klare Beschreibung des Bugs.
Mit der Version 1.0.7.0-38 Konte mann den CP Editor noch abspeichern.
Mit der neuen Version geht dies nicht mehr.
**Falls anwendbar - Schritte mit denen ich den Bug nachstellen kann**
Kurs erstellen
Kurs speichern
Editor starten
Editieren
Strg+F6 zum edit speichern
und mann bekommt einen Error vom CP
**Screenshots**
Falls relevant, bitte Screenshots beifügen

MFG Mannie313

**Comment by Stephan-S** [comment]
Was genau hat AD denn mit dem CP Editor zu tun?
Was für einen Fehler bekommst du?
So kann ich doch keine Unterstützung bieten, du musst mir hier schon mehr Infos bringen.
Geht es um einen Ingame editor oder um ein externes Programm?

**Comment by Tensuko** [comment]
Beim speichern des Kurs mit dem Editor:
Error: Running LUA method 'draw'.
F:/LS19_Mods/mods/FS19_courseplay/course_management.lua:782: bad argument #1 to 'pairs' (table expected, got nil)

**Comment by Mannie313** [comment]
Es geht um den Ingame Editor von Courseplay. mit der Version 6.01.00384
Mit der Version 1.0.7.0-38 Von AD Konnte ich die Courseplay kurse ingame bearbeiten und speichern.

Mit der Version 1.0.7.1 von AD konnte ich die Courseplay kurse ingame bearbeiten aber nicht mehr speichern.

Da kam dann immer dieser fehler:
Error: Running LUA method 'draw'.
F:/LS19_Mods/mods/FS19_courseplay/course_management.lua:782: bad argument #1 to 'pairs' (table expected, got nil)

Hoffe das hilft dir weiter.

MFG Mannie313

**Comment by Stephan-S** [comment]
Kannst du mal in CP die Debugchannel aktivieren wenn du das machst?
Vielleicht steht da ja genauer drin was ihm fehlt.

An und für sich macht AD nichts neues. Die Strecken werden jetzt zwar alle live berechnet, die CP fordert aber das klappt und sollte nichts an den gelieferten Daten ändern. Also auf Anhieb seh ich erstmal nicht wo da was schief läuft

**Comment by Tensuko** [comment]
Ich wüsste spontan nicht, das wir dafür nen debugchannel haben...
@pvaiko könnte eventuell eine Idee haben.

**Comment by Mannie313** [comment]
Welche CP Debugchannel wären das.

**Comment by Stephan-S** [comment]
Naja beim 8er kommen zumindest Infos raus wenn ein AD Kurs angefragt und zurückgegeben wird. Das wäre mal ein Anfang

**Comment by Mannie313** [comment]
Kann ich dann machen

**Comment by Stephan-S** [comment]
Aber ehrlich gesagt sieht mir das aktuell eher nach einem kaputten Kurs aus, auf den CP da zugreift.
Erstellst du den Kurs neu oder lädst du ihn aus den bestehenden CP Kursen?

**Comment by Mannie313** [comment]
Hab nen neuen Spielstand angefangen bis jetzt ging es wieder. mal sehen was die zeit bringt.
Und es werden auch die alten kurse ohne fehler bearbeitet. 

MFG Mannie313
