### ISSUE TITLE
Vehicles drive into corners too quickly

### ISSUE THREAD

**Issue by Blackjack155** [Stephan-S/FS19_AutoDrive#1095]
AutoDrive Version: 1.0.7.0.1
Release or selbsterstelltes zip: Release
Karte (falls relevant): Multimap
Fahrzeug(art) (falls relevant):

**Beschreibe den Bug**
Fahrzeuge Fahren zu schnell in die Kurven hinein und Brechen aus. Auch in der kurve selber beschleunigen sie zu zeitig was das das ausbrechen begünstigt.
In dem Link ist ein video damit man sich ein bild machen kann. Wenn was fehlen solte reiche ich es gerne nach.
https://drive.google.com/file/d/1ouucDa0SnZLU3P77Py3YoMnYMYO8zMQT/view?usp=sharing
Live mode nun fest verbaut @Stephan-S ?

Neuer spieltand, Original Map
[log.txt](https://github.com/Stephan-S/FS19_AutoDrive/files/4219228/log.txt)

**Comment by Blackjack155** [comment]
Auch bei denn Beladen von Silos fährt AD zu schnell heran was er früher nicht gemacht hatte. Das video ist ein beispiel das man dort auch sehen kann das er über das Zeil hinaus schießt.
https://drive.google.com/file/d/1EAOJg4R8_0UtbruJSQ_Ov9WlnHKNvGQy/view?usp=sharing

**Comment by Iwan1803** [comment]
Beim Überfliegen des Logs sehe ich Mods, welche für die Probleme sorgen könnten.
Daher weise ich mal auf etwas hin, was jeder sich anschauen und auch durchführen sollte: https://github.com/Stephan-S/FS19_AutoDrive/issues/1071

**Comment by Blackjack155** [comment]
2020-02-18 12:21 Error: Can't load resource 'C:/Users/chris/Documents/My Games/FarmingSimulator2019/mods/FS19_VehicleControlAddon/vehicleControlAddonScreen.lua'.
 Das ist der einzigste mod der ein fehler hat

**Comment by Iwan1803** [comment]
Ach, Chris, Blackjack155 und DerBauer2, du lernst es einfach nicht, oder?

**Comment by Blackjack155** [comment]
Das Problem mit dem Vorbeifahen konnte behoben werden aber nun bleib der Helfer an Silo stehen wenn er Dünger geladen hat. Solte aber mit diesen Silos gehn da sie für CP und AD ein sript verbaut haben.
 Broblem mit zu schnellen heranfahen an Kurven steht weiter hin wurde nur minimal reduziert

**Comment by Blackjack155** [comment]
Ich kann in nicht reproduzieren auf der Standart Karte. Wede nur mit AD, Standartfahrzeugen und Saat Silos noch mit Allen Aktiven Mods.

**Comment by Blackjack155** [comment]
Ich kann in nicht reproduzieren auf der Standart Karte. Wede nur mit AD, Standartfahrzeugen und Saat Silos noch mit Allen Aktiven Mods.

**Comment by Iwan1803** [comment]
Klone das Savegame mal auf einen anderen Spielstand und dann deaktivier mal alle Mods, welche das Fahrzeugverhalten verändern, wie z.Bsp. VCA.
Bezügl. Saatgut & Dünger per AD & CP einladen: https://youtu.be/1EfsL-h3-zw

**Comment by Blackjack155** [comment]
Wie klonen? Auf Standart oder Mod Map?

**Comment by Iwan1803** [comment]
Das Savegame klonen (oder sichern), wo die Probleme auftreten.

**Comment by Blackjack155** [comment]
Frage: 1 Video Soll am 1. Silo so schnell heran gefahren werden?
https://drive.google.com/file/d/1At2SHn8iaujo-A0NkD3e9fDgDRax0EQO/view?usp=sharing

2. Video FPS Einbrüche, Tritt bei Komplexen Strecken Netzt auf. Ist das einfach normal das AD so viel leistung zieht wenn die ganze karte mit Strecken eingefahren ist?
https://drive.google.com/file/d/1K4hW5l0fDZQuDWriVyTIYBJ1LT3x-KbC/view?usp=sharing

**Comment by Blackjack155** [comment]
Save geklont und fehler ist weg auch mit allen Aktiven Mods. Entweder der fehler schleicht sich weren des spielen eins oder ist abhänig vom save.

**Comment by Blackjack155** [comment]
Also ich habe jetzt einges Probiert z.B. die scheune auf denn bild enfernt und gegen ein giants Scheune getauscht. Auch wenn ich von denn verbauten Schüttgut Silos ihn fahre lasse fallen die FPS auf 30 fps bei der Routen Berechung. 
Was könnte noch die uhrsache sein bzw was könnte ich noch tun?

**Comment by Iwan1803** [comment]
#1089 sieht so aus wie bei dir.
Woran es genau liegt, konnte ich noch nicht ermitteln.

**Comment by Blackjack155** [comment]
>  Woran es genau liegt, konnte ich noch nicht ermitteln.

Also ich habe einiges getestet und mom bleiben nur Season und GC übrig die drauf einfluss haben können alle anderen mods habe ich druch getestet.

**Comment by Blackjack155** [comment]
vlt hilft es ja, ich habe mal die Debug channels eingeschalten  

https://drive.google.com/file/d/1UpFANAaT0AQYaPgTxRYiL6J5boYD4r-M/view?usp=sharing
