### ISSUE TITLE
Suggestion: Autodrive manueller Abladepunkt

### ISSUE THREAD

**Issue by sdl112** [Stephan-S/FS19_AutoDrive#1096]
Hi Stephan, wäre es machbar, bei Autodrive, ähnlich wie in Courseplay, einen manuellen Abladepunkt an beliebiger Stelle zu erstellen? Also wie mit dem "strg links + i" Befehl?

Ich habe gerade auf der Multimap an einigen Triggern das Problem, dass ich diese nicht so anfahren kann, dass Sie erkannt werden. Ich würde hier gerne davor abladen können und dann mit einem Förderband oder Radlader o. ä. die Ware weiterbefördern.

schöne Grüße, Simmal

**Comment by Iwan1803** [comment]
Werden die Trigger denn erkannt, wenn du manuell drüber fährst? Also kommt die Info zum manuellen Abladen?

**Comment by sdl112** [comment]
Nein, die trigger sind im febäude/Silo und reichen nicht weit genug raus

Iwan1803 <notifications@github.com> schrieb am Di., 18. Feb. 2020, 16:57:

**Comment by Iwan1803** [comment]
Ah, ok, das Problem kenne ich von der Lizard BGA.
Man könnte natürlich per Giants Editor versuchen, den Trigger zu vergrößern oder aber ein Gebäude bauen, wo AD abladen kann (Trigger vorausgesetzt), z.Bsp. Silagebunker (falls das geht).

**Comment by sdl112** [comment]
Ja mit dem Editor bin ich zu blöd, hab das schon versucht.
Eine manuelle abkadefunktion als course play ist nicht möglich einzubauen?


Iwan1803 <notifications@github.com> schrieb am Di., 18. Feb. 2020, 18:15:

**Comment by Iwan1803** [comment]
In CP geht das auf jeden Fall, in AD leider (noch) nicht.

**Comment by sdl112** [comment]
Dass es in CP geht ist mir klar, daher ja die Frage ob es möglich wäre, das ganze auch in AD zu implemetieren...

**Comment by Iwan1803** [comment]
Es würde Vorteile bringen, z.Bsp. wenn man seine Ladung vor einem Silo oder einer BGA abladen möchte oder halt an Punkten, wo es keinen Trigger gibt.
