### ISSUE TITLE
After edit of courses detection problems/Nach Strecken Bearbeiten fehler kurs erkennung 

### ISSUE THREAD

**Issue by Blackjack155** [Stephan-S/FS19_AutoDrive#1099]
AutoDrive Version: 1.0.7.1
Release or selbsterstelltes zip: Release
Karte (falls relevant): Alle
Fahrzeug(art) (falls relevant):

**Beschreibe den Bug**
Es besteht ein Problem mit der Kombi Kurse bearbeiten und erweitern im Spiel mit abgeschaltenten Helfer. Wenn ich eine Route erweitere oder neu erstelle dann kommt es dazu das Abladepunke nicht  mehr erkannt werden und Startpunkte gelöscht werden im AD Menü. Man muss das Spiel neu starten damit AD wieder Abläd.
Hoffe konnte es verstädlich erklären.

**Falls anwendbar - Schritte mit denen ich den Bug nachstellen kann**
Strecke Bearbeiten oder Erweitern

[log.txt](https://github.com/Stephan-S/FS19_AutoDrive/files/4224339/log.txt)

**Comment by Iwan1803** [comment]
Echt seltsam, was für Fehler bei dir immer auftreten. Ich habe mit der Dev-Version von gestern vorhin noch Strecken auf der NFM gelöscht, erstellt und bearbeitet und hatte keinerlei Probleme.
Das es auf allen Karten auftritt, kann ich nicht wirklich so ganz glauben....

**Comment by Blackjack155** [comment]
An was soll es denn liegen? An mir sicher nicht und es sind ja auch keine neuen mods dazu gekomm. Beheben kann ich denn fehler nicht.

**Comment by haamic** [comment]
Merkwürdig ist das schon, das du so viele Meldungen absetzt. Hattest du nicht die Sch... voll von AD?  Warum haben andere nicht die selben Probleme? Ist deine Tastatur kaputt, weil du nicht mal einen Vierzeiler ohne Rechtschreibfehler hinbekommst? Aber das hat alles nichts mit deinem gemeldeten Fehler zu tun, sorry. 
Vielleicht kannst du ja das alles mal auf einen anderen PC testen, um zu sehen, ob da die gleichen dubiosen Fehler auftreten? 
Oder deinstalliere mal LS19 komplett. Und mach nochmal alles neu, wer weiß was in den Tiefen deines Systems mit dem Spiel schiefläuft.

**Comment by Blackjack155** [comment]
@haamic Das ist beleidigteng! Ich erwarte das es gelöscht oder geändert wird !

Sag mal ist das alles hier ein witz oder was? Jetzt soll ich das auf ein anderen PC testen? Denkst du ich habe so viel Geld und Zeit das ich das ICH die Test so weit ausweiten kann? Und langsam reichts mit bei anderen wird nach der uhrache gesucht und bei mir wird nur mein pc oder sonst was die schuld gegeben. Vlt mal dran gedacht  das einfach AD das Problem ist und keiner weis wer noch alles das gleiche Problem hat da nicht jeder hier das hineinschreibt also an statt hier die leute zu Kritisieren solte man mal damit anfangen nach lösungen zu suchen damit fehler behoben werden.
Und bei jemden spiel ode Mods giebt es einzell felle wo fehler vorkommen da kann noch so viel testen wenn da nix gefixt wird bleibt der Fehler.

Und noch was an dem PC wird es nie liegen und kann es nicht denn bei keinem anderen spiel giebt es solche Probleme und das kann ich berugt sagen es sind 1000 schon drauf gelaufen.

**Comment by Blackjack155** [comment]
> Ich habe mit der Dev-Version von gestern vorhin noch Strecken auf der NFM gelöscht, erstellt und bearbeitet und hatte keinerlei Probleme.

Auserdem war dieser Fehler von AD voher nicht da konnte ich ja Strecken bearbeiten und erstellen im Game. Das geht ja nun mit der 1.0.7.1 ja nicht mehr. Warum soll das also dann nicht an AD liegen? Auch wenn es auf denn Standart Karten psassirt das ich diese auch neu Starten muss. Daher habe ich die #1071 befolgt und konnte Mods als Fehlerquelle aus schliesen.

**Comment by Iwan1803** [comment]
@haamic 
Nicht jeder ist der deutschen Sprache in vollem Umfang mächtig und unterlass daher in Zukunft bitte solche Kommentare, danke!

@Blackjack155 
> Auserdem war dieser Fehler von AD voher nicht da
Vielleicht hast du zwischenzeitlich irgendwas geändert oder Mods hinzugefügt oder aktualisiert?
Mal abgesehen davon, das du dich ja eigentlich mit AD nicht mehr auseinandersetzen wolltest:
Findest du es nicht seltsam, das du so massive Probleme hast und andere hingegen nicht? Daraus schließe ich jetzt mal, das der Fehler mit den genutzten Mods, dem Spiel, dem PC oder dir zu tun hat und nicht zwingend bei AD zu suchen ist.
Und lass mich raten: du hast die Tests zwar mit deaktivierten Mods gemacht, aber diese nicht aus dem Mod-Ordner rausgenommen, richtig? Falls ja, dann probier das bitte noch mal aus, denn z.Bsp. von einigen Maps weiß man, das sie sich gegenseitig "behindern", auch wenn sie deaktiviert sind.

**Comment by Blackjack155** [comment]
> Nicht jeder ist der deutschen Sprache in vollem Umfang mächtig und unterlass daher in Zukunft bitte solche Kommentare, danke!


Soll das eine Beleidigung an meine Rechtschreibschwäche sein!?

@Iwan1803 
Natürlich ohne mods im ordner das weis ich auch das diese Trozdem mit geladen werden.

**Comment by haamic** [comment]
@Iwan1803 
Ich hatte mich bereits in meiner Antwort entschuldigt und auch nicht unterstellt das jemand der deutschen Sprache nicht mächtig ist. Man kann auch vieles falsch interpretieren. Egal jetzt, ist ja nun editiert/gelöscht. 

@Blackjack155 
Du solltest ja auch keinen neuen PC kaufen, sondern das du eventuell bei Freunden/Bekannten mal testen könntest ob da alles besser läuft, oder auch die Probleme auftauchen. Keiner zweifelt an der Leitungs deines PC. 
Ich kann jetzt nun für mich sprechen und habe zum Glück keine Probleme mit AD. 
Es macht was ich möchte und bin zufrieden. Wenn doch mal was nicht so läuft wie erwartet, was solls... man kann nicht alles haben.  
Ich danke Stephan und sonstigen Beteiligten für diesen tollen Mod.

**Comment by Blackjack155** [comment]
@haamic Das max was ich machen könnte wäre es auf denn Leppy meiner freundin zu testen aber der is nun nicht gerade gut. Was das Ergebniss vlt verfälschen würde.
Es sind ja nur max 2 dinge die mit AD nicht laufen das sind die FPS einbrüche und dieses hier. Diesen könnte ich auch hinweg sehn denn er tritt ja nur beim bearbeiten vor.
Keine Frage das AD ein super mod ist in der kombie mit CP ist das einfach genial keine frage.

Der meisten schuld gebe ich ja Giants da die Engine schrott ist und zu veraltet ist um die ganzen brozesse zu Berechnen. Stephan und co. können ja dafür nichts das ist ja fakt.

**Comment by Iwan1803** [comment]
@haamic 
Leider ist nicht jeder im Stande, Texte korrekt zu interpretieren und es gibt halt Leute, die alles gerne mal falsch interpretieren. Ich wollte nur deeskalierend eingreifen 😉

@Blackjack155 
Du fragst mich, ob das eine Beleidigung sein soll, wenn ich andere um Nachsicht bitte? Geht's noch?
Ich kenne genug Leute, welche Probleme mit dem Verfassen von Texten haben und habe mich noch nie darüber lustig gemacht. Mir ist es egal, ob jemand eine Rechtschreibschwäche hat, der deutschen Sprache nicht mächtig oder einfach nicht in der Lage ist, lange Sätze fehlerfrei zu schreiben.
Deine Schlüsse bzgl. anderer AD-Nutzer sind einfach nur (um es in deinen Worten und nett zu sagen) "bullshit". Gemäß deiner Meinung müsstest du doch auch AD löschen, wobei du AD ja sowieso den Rücken kehren wolltest.
Ich kenne haufenweise Spieler, welche AD auf verschiedenen Karten und mit etlichen unterschiedlichen Mods nutzen und das ganze soweit problemlos. Hier und da hakt immer mal was und auch ich habe ab und zu mal Probleme, wie z.Bsp. die FPS-Loss, die ich nicht reproduzieren kann. Allerdings habe ich bisher keinen kennengelernt, der so viele Probleme hatte wie du und wo es nicht einen Faktor abseits von AD gab, warum diese auftraten.
Daraus ziehe ich für mich den Schluss, das da irgendwas bei dir vermurkst ist. Trotz der (nicht nachvollziehbaren) Tests sehe ich aber leider keinen Anhaltspunkt. Die Problemsuche schließt daher die genutzten Mods und Maps, dem Spiel, Windows und selbst die Hardware mit ein. Es wurden haufenweise Vorschläge gemacht, um das Problem einzugrenzen, da wir es so nicht reproduzieren können.

Mir ist es mittlerweile egal, ob du das Problem finden wirst oder wem du mit deinem letzten Beitrag hier Honig um die Schnute schmieren oder die Schuld für die Probleme in die Schuhe schieben willst, aber ich sehe den Fehler einfach nicht in AD begründet.
Ich bin ein geduldiger Mensch, aber da du dich wiederholt hier hinstellst, als ob du der Mittelpunkt der Erde bist und mir dein Verhalten so langsam reicht, werde ich mich wohl nicht länger an der Detektivarbeit beteiligen.

**Comment by Blackjack155** [comment]
Ich gebs auf mit DIR über die Probleme zu schreiben du bist einfach zu unprofessionell für denn Posten hier. Das würde ich nicht Hilfe nennen denn man stänig kritisieren. Es ist ja nicht so das ich Andere issues hier nicht gelesen hätte und gelsen habe das du die schuld immer denn Leuten vor wirfst. Und ganz erlich du bist diskriminierend denn du stellt mich für Dumm da ein Pc und ein Spiel zu bedienen was aus allen Issue heraus gelsen werden kann. Mal nach gedacht das dass einfach verletzt ist und ich deswegen dir gegenüber so reagiere??!! Troz der gannzen sachen bemühe ich mich mit zur mitarbeit und fehlersuche. 
Es würde einfach mal MASSIV helfen wenn du ruhg und sachlich bleiben würdest dann könnte man gemeinsam denn fehler finden. Denk doch mal nach warum ich so reagiere? Ich mach es nicht aus lw oder weil ich dich Trollen will, denn davon hat keiner was und deine zeit will ich auch nicht verschwerden. 

Ich möchte wie jeder andere das dass ganze funkzioniert mehr nicht ich erwarte nicht das es mir aus scheiße gold Produziert.
Ich sage dir das du mich angegriffen hast schon schon lange vor dem ganzen hir und es sich deswegen hochgschaukelt hat.
Endweder du verstehst was ich damit sagen will oder läst es deine sache. Ich will dich weder ärgern noch Trollen nur diesen scheiß fehler finden damit ich ruhe spielen kann. 
Was du jetzt damit machst ist deine sache denke was von mir wie du willst, ändern kann ich das nicht. Wenn du denkst ich bin zu dumm für AD dann lass es eben mir zu helfen ich werde niemand zwingen entwas zu tun was er nicht will. Ich weis das ich kein perfekter mensch bin aber wenigtes gebe ich mir mühe auch wenn es leider nicht so oft klapt und ich deswegen an jeder ecke hänge bleibe das ist mit **ADHS** nun mal so das man damit als ausenseiter gebrant markt ist.

Macht mit der info nun was du wilst deine sache ich werde sehn ob du es verstanden hast oder nicht.

**Comment by Iwan1803** [comment]
Nur zur Info: ich leiste Support im IT-Bereich seit ca. 25 Jahren und kann mit problematischen und vor allem beratungsresistenten Leuten bestens umgehen, aber irgendwann erreicht man bei jedem einfach mal eine Grenze, an der es nicht weiter geht - wie bei dir jetzt.

Ich habe von Anfang an versucht, dir zu helfen, aber wenn jemand einfach trotz mehrfacher Hinweise nicht macht, was man ihm sagt, wie soll man da noch helfen?
Nach den ersten Beiträgen von dir wusste ich schon von anderen Seiten, das du dich dort auch nicht ganz korrekt verhalten hast, aber dennoch habe ich versucht, dir zu helfen.
Du hast penetrant drauf bestanden, das AD Schuld ist und mich dann auch wiederholt angegriffen, obwohl ich versucht habe, dir zu helfen.
Dann tauchst du hier mit einem 2. Nick auf und hast verneint, das es ein 2. Nick ist und dennoch habe ich versucht zu helfen, obwohl ich mir verarscht vorkam. Das Ergebnis war das gleiche wie vorher: du hast nicht gemacht, was man dir gesagt hat.
Dann kommst du mit dem 1. Nick hier weder her obwohl du mit AD nichts mehr zu tun haben wolltest und ich dachte mir, das ich dir noch eine Chance gebe, aber leider hast du nichts, aber auch gar nichts gelernt. Für dich sind immer die anderen Schuld und immer böse zu dir, aber dein Verhalten ist einfach mal sowas von unangemessen, was du aber scheinbar nicht merkst.

Es ist mir sowas von egal, welche körperlichen oder geistigen Probleme jemand hat - wenn ich helfen kann, dann tue ich das. Leider drehst du dir aber alles so um, das es für dich passt und findest es scheinbar auch noch ok, die Leute dumm anzumachen, welche dir eigentlich helfen wollen.
Du unterstellst mir hier Sachen, die einfach nicht der Wahrheit entsprechen und benimmst dich wie ein kleines bockiges Kind. Sorry, aber denk mal über dich und dein Verhalten nach bevor du andere zu unrecht kritisierst.

**Comment by Blackjack155** [comment]
Ok du hast nichts verstaden was ich geschrieben habe daher werde ich nicht mehr auf dich ein gehen und warten bis der Moder sich der sache an nimmt wenn er zeit hat.

**Comment by Iwan1803** [comment]
Ich verstehe schon, was du schreibst, aber du verstehst einfach nicht, das dir deine Uneinsichtigkeit, deine Engstirnigkeit und vor allem deine Lügen einfach nicht helfen werden.
Ob Stephan dir noch helfen wird/kann/will, steht auf einem anderen Blatt...

**Comment by Stephan-S** [comment]
So, zu allererst einmal vielen Dank an alle Beteiligten hier für das rege Interesse und die Mithilfe am Mod.
Aber, für solche Diskussionen ist das Github Repository nicht gedacht. Nutzt doch für solche Gespräche den Discord Server: https://discord.gg/sUQtKhB

Nur kurz zum eigentliche Issue:
Ich konnte das leider nicht nachstellen. Ich habe mehrmals probiert Strecken zu entfernen, zu ändern, neue Punkt hinzugefügt, etc. Danach konnte ich immer erfolgreich an Triggern be/entladen.
Wenn es bei dir immer an der selben Stelle auftritt, dann beschreib mit bitte ganz genau die Schritte, mit denen du es nachstellen kannst und schicke mir dann dazu deine config vor und nach der Streckeneditierung. Dann probiere ich das gerne nochmal nachzustellen.
Da mir dieses Issue hier aber zu weit vom Thema weg gelaufen ist, mache ich hier dicht. Wenn es dazu noch Erkenntnisse oder Gesprächsbedarf gibt, meld dich auf dem Discord bei uns :-)

**Comment by Blackjack155** [comment]
@Stephan-S  Danke für deine nette antwort ich werde verschen was zusammen zu stellen.
