### ISSUE TITLE
Andere Maschinen

### ISSUE THREAD

**Issue by spielera** [Stephan-S/FS19_AutoDrive#110]
Hallo,
danke erst für das schöne Programm. Mach bitte weiter so.
So nun zu meiner Frage.
Mit den Abfahren von Mähdrescher funktioniert ja zu 99% sehr gut.
Ich habe es heute mit einer Kartoffelerntemaschine getestet.  
Mein LKW blieb da stehen, wo ich ihn abgestellt habe, er hat keinen Schritt, Richtung Erntemaschine getan.
Ist dies in Zukunft vorgesehen, daß man auch andere Maschinen abfahren kann?

Wie gesagt, super Mod, macht weiter so.

**Comment by Stephan-S** [comment]
Der Kartoffelernernter ist tatsächlich noch nicht unterstützt. Die Rübenernter hingegen schon.
Das muss ich bei Gelegenheit noch einbauen :-)

**Comment by spielera** [comment]
Danke für deine schnelle Antwort.
