### ISSUE TITLE
Unloading Case Ausoft 8800 problem

### ISSUE THREAD

**Issue by Nyggen81** [Stephan-S/FS19_AutoDrive#1101]
AD ver 1.0.7.1

When trying to set up a tractor to unload the Ausoft sugarcane machine the tractor first drive behind the ausoft, then in some cases backs up a litle bit and drive to the side of it. 
When the tractor comes underneath the pipe it will just move slightly back and the harverster is not able to unload. I guessed this was easy to fix just by adjusting the vehicle pipe offset settings, but nomatter how I adjust them I cant se any difference in behaviour or placement of the vehicle.

Ive tried several tractors and several tippers, but not able to get this to work. 

Please look into it. If you need more info or log, please ask :)

**Comment by Blackjack155** [comment]
The log is missing so that the boys can help you here

**Comment by Nyggen81** [comment]
[log.txt](https://github.com/Stephan-S/FS19_AutoDrive/files/4235740/log.txt)

**Comment by hectordc5** [comment]
> AD ver 1.0.7.1
> 
> When trying to set up a tractor to unload the Ausoft sugarcane machine the tractor first drive behind the ausoft, then in some cases backs up a litle bit and drive to the side of it.
> When the tractor comes underneath the pipe it will just move slightly back and the harverster is not able to unload. I guessed this was easy to fix just by adjusting the vehicle pipe offset settings, but nomatter how I adjust them I cant se any difference in behaviour or placement of the vehicle.
> 
> Ive tried several tractors and several tippers, but not able to get this to work.
> 
> Please look into it. If you need more info or log, please ask :)

This is a well known bug. A temporary fix that works for me is to set the pipe offset to 0 in your loading/unloading trailer (not the combine). Remember that each tractor has it's own settings, so make sure you adjust your tractor/trailer settings and not the combine settings.

**Comment by TyKonKet** [comment]
**Hello, Thank you for opening this issue!**
Since we have just released [the new refactored version of AutoDrive](https://github.com/Stephan-S/FS19_AutoDrive/releases/tag/1.1.0.0), we can no longer provide any feedback or support for open bug reports related to the old code base.
If the problem persists, please reopen a new issue with all the required details.
Thank you for understanding and we hope you continue enjoying our mod 😄
