### ISSUE TITLE
AD unloads wrong side

### ISSUE THREAD

**Issue by RalfGorden** [Stephan-S/FS19_AutoDrive#1103]
AutoDrive Version: 1.0.7.1
Release or selbsterstelltes zip: Release
Karte (falls relevant): Alle
Fahrzeug(art) (falls relevant):

**Beschreibe den Bug**
hallo 
Wenn als Abkippseite "hinten" eingestellt ist am Hänger, nimmt Autodrive selbstständig den Kornschieberoder auch seitlich abladen
zB bei abholen und abliefern
 das Problem haben andere auch

**Comment by Blackjack155** [comment]
Kann er dadruch nicht abladen wenn es auf der Falschen seite ist?

**Comment by Stephan-S** [comment]
AD testet beim Anfahren an einen Trigger alle Abladepunkte des Hängers, ob sie gerade abladen können und wählt den ersten bei dem das zutrifft.
Wenn ich dieses Suchen ausschalte, kann es durchaus passieren, dass er an einigen Stellen nicht mehr abladen kann, da schlicht nicht eine der möglichen Abladeseiten eingestellt war.
Und ich möchte auch ungern warten, ob noch die eingestellte Abkippseite in den Trigger kommt. Möglicherweise passiert das nie und die möglichen Seiten sind schon alle vorbeigefahren.

**Comment by RalfGorden** [comment]
vielen Dank Stephan für deine Antwort , da weis ich bescheid das es anders nicht geht , mach weiter so super Hilfe das AD
