### ISSUE TITLE
Can't open ad editor (java version error after update all lastest java i can find on internet and restart pc)

### ISSUE THREAD

**Issue by po456asd** [Stephan-S/FS19_AutoDrive#1104]
AutoDrive Editor Version: lastest download from github

![image](https://user-images.githubusercontent.com/13596788/75044777-c90c4780-54f4-11ea-8afb-c648db076244.png)
and this is what i try to install but still can't open the ADE
![image](https://user-images.githubusercontent.com/13596788/75044862-e50fe900-54f4-11ea-8c97-874a4f21a2f9.png)
here is my java version rn that i can't open ADE
![image](https://user-images.githubusercontent.com/13596788/75044933-040e7b00-54f5-11ea-85bb-e38929339fc6.png)

**Comment by raupach** [comment]
You need to install java 11 or greater.

**Comment by po456asd** [comment]
i install one from this 
https://www.oracle.com/java/technologies/javase-jdk11-downloads.html
still doesn't work
![image](https://user-images.githubusercontent.com/13596788/75046588-fa3a4700-54f7-11ea-913b-8f6774cff33e.png)

**Comment by raupach** [comment]
I guess you are using still the old version. Did you deinstall Version 8? Then you have to add the Java/bin directory to your windows PATH-Evironment manually.
Have a look at: https://tubemint.com/install-java-jdk/

**Comment by po456asd** [comment]
i got it open somehow thank to you.
but got another problem is when i try to open map image it open like this can't move and zoom
![image](https://user-images.githubusercontent.com/13596788/75048273-d75d6200-54fa-11ea-8d6b-ae8033ce73b9.png)
even when maximize it still show that bit of map
![image](https://user-images.githubusercontent.com/13596788/75048313-e6441480-54fa-11ea-8118-39effa2820d5.png)

**Comment by po456asd** [comment]
actually a thing is i try to translate "welcome to felsbrunn" map to english but when i open the game AD automatically wipe the xml file.
but when i try to delete from waypoint number 111 to last waypoint. ad can work with it and not delete xml file somehow. so i try to use ADE to make a new waypoint from useable file.

here is the file that when loaded into game AD will wipe the file. but ad will not wipe if you delete waypoint no 111 to last waypoint from file first.

[AutoDrive_Welcome_to_Felsbrunn_config.txt](https://github.com/Stephan-S/FS19_AutoDrive/files/4236813/AutoDrive_Welcome_to_Felsbrunn_config.txt)

**Comment by raupach** [comment]
Yes, it's a bug.

**Comment by raupach** [comment]
Can you test with the AD.jar from my repository?
https://github.com/raupach/FS19_AutoDrive/tree/fix/NPE_at_saveMap/AutoDrive%20Course%20Editor

**Comment by po456asd** [comment]
sure, a minute.

**Comment by po456asd** [comment]
not working
here a video.
https://www.dropbox.com/s/hnz6lc12cvdjygn/6ZNSTSTukd.mp4?dl=0

**Comment by raupach** [comment]
As a workaround can you zoom the map by mouse-wheel after loading and resizing the window? This works for me. But I try to do a fix right now.

**Comment by po456asd** [comment]
yes, i already use mouse wheel in video. still not working somehow.

**Comment by hectordc5** [comment]
> i got it open somehow thank to you.
> but got another problem is when i try to open map image it open like this can't move and zoom
> ![image](https://user-images.githubusercontent.com/13596788/75048273-d75d6200-54fa-11ea-8d6b-ae8033ce73b9.png)
> even when maximize it still show that bit of map
> ![image](https://user-images.githubusercontent.com/13596788/75048313-e6441480-54fa-11ea-8118-39effa2820d5.png)

Is the map 2048x2048 pixels? it has to be that size or else the image will show like the image you posed?

**Comment by raupach** [comment]
I have already fixed the problem. You can get the AD.jar from my repository for testing purposes: https://github.com/raupach/FS19_AutoDrive/tree/fix/resize_after_mapLoad/AutoDrive%20Course%20Editor

 I have already made a pull-request for Stephan. But at the moment it is not yet processed.

**Comment by po456asd** [comment]
> > i got it open somehow thank to you.
> > but got another problem is when i try to open map image it open like this can't move and zoom
> > ![image](https://user-images.githubusercontent.com/13596788/75048273-d75d6200-54fa-11ea-8d6b-ae8033ce73b9.png)
> > even when maximize it still show that bit of map
> > ![image](https://user-images.githubusercontent.com/13596788/75048313-e6441480-54fa-11ea-8118-39effa2820d5.png)
> 
> Is the map 2048x2048 pixels? It has to be that size or else the image will show like the image you posted.

yes 2048x2048 
![image](https://user-images.githubusercontent.com/13596788/75113583-bbd09380-5681-11ea-97ed-b2a98deefd22.png)

> I have already fixed the problem. You can get the AD.jar from my repository for testing purposes: https://github.com/raupach/FS19_AutoDrive/tree/fix/resize_after_mapLoad/AutoDrive%20Course%20Editor
> 
> I have already made a pull-request for Stephan. But at the moment it is not yet processed.
> (Remember: at least Java 11 is required.)

tested it. still mouse wheel doesn't seem to work.

https://www.dropbox.com/s/6ia4z4jdj5te9lh/HB4H11FgoO.mp4?dl=0

**Comment by raupach** [comment]
That's funny. It only happens when you open the map first (or alone). I have till now always opened the config first and then the map...

**Comment by po456asd** [comment]
ok got it work by load config first. 
maybe make program load some default blank config if open map before config?

**Comment by webwibo** [comment]
I use AD for LS 19 since is was available for the game. It is a great expansion of the game.
I also had error messages after updating to the latest editor version like in the first post in this comment. I updated my Java installation as stated in the post above.
Then I checked the Java installation as you can see in the picture below.
![fehler AD Editor](https://user-images.githubusercontent.com/61359685/75182645-1c72d580-5741-11ea-8037-807304288f70.png)
When I start AD via "Open Editor with Console to see errors.cmd" I get the error messages shown in the first comment.
But when I start the editor via "AD.jar" then I can open a configuration, edit courses and save them.
Ingame the changes are visible an AD works withuot errors.
It is possible that the problem are caused from using the .cmd File?

**Comment by raupach** [comment]
You have both Java versions installed. This is technically possible under certain conditions. But it is often not a good idea. So simply uninstall the old version cleanly. Furthermore you have to make sure that the java/bin directory is included in the search path. This is also well explained here: https://tubemint.com/install-java-jdk/

**Comment by andreasthu** [comment]
where can  i download the free java11 for private use?
in the links above i only find terms for comercial use
lg
andreas

**Comment by webwibo** [comment]
I think you can download it from that site, it´s free for private use:

> **_The new license permits certain uses, such as personal use and development use, at no cost_** >

**Comment by raupach** [comment]
You can also use OpenJDK: https://openjdk.java.net/

**Comment by andreasthu** [comment]
> You can also use OpenJDK: https://openjdk.java.net/

ok, have downlaoded it,
how can i install this now?

**Comment by andreasthu** [comment]
> I think you can download it from that site, it´s free for private use:
> 
> > **_The new license permits certain uses, such as personal use and development use, at no cost_** >

ok, i found the download here:
https://www.oracle.com/java/technologies/javase-jdk13-downloads.html
lg
andreas
