### ISSUE TITLE
Invisible MapHotspots clickable and option do deaktivate "set as target"

### ISSUE THREAD

**Issue by Rumspringa90** [Stephan-S/FS19_AutoDrive#1108]
AutoDrive Version: 1.0.7.1
Release or selbsterstelltes zip: Release
Karte (falls relevant): Alle
Fahrzeug(art) (falls relevant):

**Beschreibe den Bug**
Wenn man die Zeile auf der Karte ausblendet, kann man sie immer noch anklicken. Was mich theoretisch nicht stört. Was mich daran stört ist, dass das Ziel dann Automatisch als Ziel eingetragen wird, Kann man das irgendwo deaktivieren das er das Ziel übernimmt? Habe kein Einstellung dazu gefunden

**Screenshots**
![Unbenannt](https://user-images.githubusercontent.com/50840355/75095623-222cb780-5597-11ea-8cc4-ddb6d387ac51.png)

**Comment by Iwan1803** [comment]
Sitzt man in einem Fahrzeug und klickt auf einen Zielpunkt auf der Kartenansicht zum Besuchen, dann wird das Ziel vom Fahrzeug geändert.
Das ist eher "suboptimal", wie auch ich nun festgestellt habe. Eine Option zum Ein-/Ausschalten wäre schön, da vermutlich keine weitere Option auf die Kartenansicht gebracht werden kann, oder?

**Comment by Justice-Molton** [comment]
Das funktioniert im Mulitplayer übrigens nicht. Da kann man es anklicken, wird auch im AD angezeigt. Aber sobald man auf los klickt ist wieder das alte Ziel aktiv.

**Comment by Iwan1803** [comment]
Das wurde ja jetzt eingebaut und funktioniert bei mir fehlerfrei.

**Comment by Rumspringa90** [comment]
Ich werde es heut nachmittag testen und dann das Thema schließen

**Comment by Rumspringa90** [comment]
Hab es eben getestet. Sie sind zwar immernoch in der Map anklickbar wenn sie nicht angezeigt werden, aber sie werden nicht mehr als Ziel gesetzt. Wenn man das anzeigen aktiviert hat, dann werden sie weiterhin als ziel gesetzt. 

Für mich ist das so OK da ich diese nicht nutzen werde.
