### ISSUE TITLE
Error if not Def as Fillunit

### ISSUE THREAD

**Issue by RickBlackLabele** [Stephan-S/FS19_AutoDrive#1109]
AutoDrive Version: 1.0.
Release or selbsterstelltes zip: Release
Karte (falls relevant): Alle
Fahrzeug(art) (falls relevant):

**Beschreibe den Bug**
wenn ich mit meinem mod mit Auto drive fahren lasse und ich nicht den filltype Diesel eingetragen habe sondern mein filltype für die Maschine (KW)

**Falls anwendbar - Schritte mit denen ich den Bug nachstellen kann**

**Screenshots**
https://prnt.sc/r6bbn9

**Comment by Iwan1803** [comment]
Bitte AD-Version ergänzen, danke!
