### ISSUE TITLE
Kurven und Kreuzungen

### ISSUE THREAD

**Issue by spielera** [Stephan-S/FS19_AutoDrive#111]
Hallo,
wenn man die Strecken einfährt, sieht alles Super aus, bis auf Kreuzungen.
Kann man kein Tool machen, daß man bis zu einen gewissen punkt zur Kreuzung vor fährt und dann, per Tool, die Kreuzung erzeugen kann?

Macht weiter so.

**Comment by Stephan-S** [comment]
Servus,
du kannst einerseits in den AutoDrive - Einstellungen (alt+strg + 0 (Nummernblock) ) einstellen, das Start und Endpunkte automatisch verbunden werden.
Außerdem gibt es den Kurseditor mit dem du das Streckennetz auch außerhalb des Spiels bearbeiten kannst. Dieser liegt hier mit im Repository.
Dort einfach die config.xml laden und falls es keine Standard Map ist, auch noch das pda Bild der Karte (als .png nicht als .dds).

Viele Grüße,
Stephan
