### ISSUE TITLE
MP: invisible lines in course recording

### ISSUE THREAD

**Issue by Billy5haw** [Stephan-S/FS19_AutoDrive#1110]
AutoDrive Version: 1.0.7.1
Release or selbsterstelltes zip: Release
Karte (falls relevant): 4-fach Marsch
Fahrzeug(art) (falls relevant): alle
- Multiplayer/ Server

**Beschreibe den Bug**
Bei der Kursaufzeichnung werden die Linien nicht dargestellt.
Diese erscheinen erst nach einer Neuberechnung. Dies ist ebenfalls der Fall beim Verbinden von Linien. Hatte bereits die letzte 4 Versionen ausprobiert und immer wieder den gleichen Fehler gehabt.  

**Falls anwendbar - Schritte mit denen ich den Bug nachstellen kann**
-
**Screenshots**

![Screen_LS19](https://user-images.githubusercontent.com/61431016/75183459-e0407480-5742-11ea-9bba-72513fee3c36.JPG)

**Comment by Stephan-S** [comment]
@TyKonKet Can you confirm this behaviour with the current version? I don't have any MP Server to test on right now.

@Billy5haw Is this a dedicated server? Or are you the host or one of the joining players?

**Comment by Iwan1803** [comment]
Last time i saw that problem was on hosted game of a friend. I also don't have a dedicated server.

**Comment by Billy5haw** [comment]
It is a rented dedicated server.
I am both admin and player. If necessary, you are welcome to view the problem directly on the server. Including access to the server logs.

Maybe it's also a collision with another mod. I have to admit, I haven't tested it yet. I'm more of a user than a modder or something like that.

**Comment by Justice-Molton** [comment]
I have a dedi root and couldn’t confirm it.

**Comment by TyKonKet** [comment]
Yes, I'm not able to reproduce this issue on my dedicated server
Anyway is that a problem of the last version or is a long time problem

**Comment by Justice-Molton** [comment]
We’ve had this issue weeks ago. But I couldn’t remember which version it was. May you could double check that you have the actual dev version and no old ones in the Mod folder..

**Comment by TyKonKet** [comment]
Yes, I have the latest version.

**Comment by Billy5haw** [comment]
Good evening, I tested something around and deactivated all mods and deleted the config from autodrive. Now it also works with entering the courses. After I import the courses again, the problem occurs again. Is more data imported than just the waypoints? Or are there maybe too many waypoints? (38,000)

**Comment by Billy5haw** [comment]
I have now again created a new config in which the lines are still displayed when entering. After that I just copied the waypoints and mapmarkers from the existing config using Note ++. After that, the same problem occurs again, the lines are no longer displayed when entering. The lines can only be seen after the waypoints have been recalculated.

**Comment by AngeloMerte** [comment]
got the same problem. You got any solution for this by now?

**Comment by Stephan-S** [comment]
Don't worry about this too much. MP rework is currently being done for the refactored codebase. So stay patient for now :-)
We will only react to MP issues that are related to the new code base which will hopefully be released soon. Maybe next weekend.

**Comment by AngeloMerte** [comment]
Ok, thx for the answer. You are doing a great job <3

**Comment by TyKonKet** [comment]
**Hello, Thank you for opening this issue!**
Since we have just released [the new refactored version of AutoDrive](https://github.com/Stephan-S/FS19_AutoDrive/releases/tag/1.1.0.0), we can no longer provide any feedback or support for open bug reports related to the old code base.
If the problem persists, please reopen a new issue with all the required details.
Thank you for understanding and we hope you continue enjoying our mod 😄
