### ISSUE TITLE
AutoDrive Course Editor

### ISSUE THREAD

**Issue by Blackjack155** [Stephan-S/FS19_AutoDrive#1111]
Ich wolte gerne mal denn Editor ausprobieren aber es geht nicht da kommt diese fehlermeldung. Java ist logischerweiße vorhanden.
 
![grafik](https://user-images.githubusercontent.com/26688591/75194956-5bad2080-5759-11ea-984f-56f36f0f6bfd.png)

**Comment by Iwan1803** [comment]
Die Suche bringt mir folgendes Ergebnis: https://github.com/Stephan-S/FS19_AutoDrive/issues/1104
Scheinbar wird eine bestimmte Version benötigt.

**Comment by Blackjack155** [comment]
also so wirklich versteh ich nicht was das dort gesagt wird troz übersetzter und die java versionen scheinen ja nicht von der original webseite zu sein da stehe ich pessimistisch gegenüber.

weiß ja nicht warum das für unbedingt eine extra version gebraucht wird

**Comment by raupach** [comment]
Wie hast du den Editor gestartet? Das sieht nach einem Start-Fehler aus. Am einfachsten ist der Start mit Doppelklick auf die cmd-Datei "Open Editor with Console to see errors.cmd"
Es muß Java Version 11 oder größer installiert sein.

**Comment by Blackjack155** [comment]
naja wie man halt ein Pogramm startet schäze ich mal
![grafik](https://user-images.githubusercontent.com/26688591/75245967-22af9300-57cf-11ea-9c1d-228bad20a28e.png)
das ist die version die ich habe und auch offizell von javer herunterladbar ist

**Comment by Iwan1803** [comment]
Das ist die "normale" Java-Version. In dem verlinkten Issue wird aber vom JDK 11 (Java Development Kit) gesprochen.
Und noch was: du lernst es einfach nicht, Chris, oder?
Mach doch einfach mal, was raupach empfohlen hat (cmd-Datei starten) und poste das Ergebnis.

**Comment by raupach** [comment]
JRE oder JDK ist egal. Beide funktionieren. Die JRE ist die Laufzeitumgebung und JDK ist die Entwicklungsumgebung, die die JRE enthält. Da ich Java-Entwickler bin, nehme ich aus Gewohnheit gerne das JDK.
Die Version muß nur größer 11 sein. Das ist wirklich wichtig.

**Comment by Blackjack155** [comment]
@raupach  okay danke ich bin nur vorsichtig was mir unbekannt ist, Danke. Ich teste mal das einfach und sag dir bescheid :)

@Iwan1803 Sry aber mir egal was du sagst du bist mir einfach zu unhöflich und kannst einfach nicht mit leuten um gehn so wie raupach soltest dir mal eine scheibe von ihm abschneiden, ender der diskosion mit dir!

**Comment by Iwan1803** [comment]
@Blackjack155 
so lange du Lösungsansätze (egal von wem) nicht annimmst und/oder befolgst, solltest du dir ab sofort woanders Hilfe suchen.
Da wird dir auch das nachträgliche Löschen nichts.

**Comment by Blackjack155** [comment]
was bildest du dir eilg ein wer du bist du .....
Ich habe seine anweißg bevolgt also komm mal klar kollege!

**Comment by Iwan1803** [comment]
Er hat dir geschrieben:

> Am einfachsten ist der Start mit Doppelklick auf die cmd-Datei "Open Editor with Console to see errors.cmd"

Hast du das gemacht? Nein, weil du ein Sturkopf bist und solche Leute sind hier fehl am Platz. Entweder nimmst du die Hilfe an und machst auch mal was man dir schreibt oder du suchst dir woanders Hilfe.
Möchtest du mir noch was sagen? Dann komm in den Discord-Chat und wir können da gerne weiter schreiben. Falls nicht, dann spar dir weitere Kommentare.
