### ISSUE TITLE
AutoDrive Course Editor

### ISSUE THREAD

**Issue by Blackjack155** [Stephan-S/FS19_AutoDrive#1112]
Spiel weiter gott und ich melde das Steffan das du unangebracht Post löscht!! Lass es!!
#1111
@raupach also ich habe das nun so gemacht wie du gesagt hattest und nun kommt es auch dazu das der Editor Läd. Aber das mit dem vergrößern klappt leider nicht so ganz wie es soll 

![grafik](https://user-images.githubusercontent.com/26688591/75257640-89d84200-57e5-11ea-92a9-acd66e656399.png)

Kann der Editor nur eine Begrenze größe ereichen? Und wie verhälst sich das denn mit so einer Endwickler version?

**Comment by Iwan1803** [comment]
Unterlass deine Beleidigungen und Unterstellungen, denn ich lösche nichts - ich schließe nur. Wie schon mal angeboten: wir können uns auf Discord weiter unterhalten....

Zum Thema:
benutz doch bitte mal die Suchfunktion, denn dazu gibt es schon mind. 1 Issue.

**Comment by Iwan1803** [comment]
Hier gibt es übrigens die Lösung: https://github.com/Stephan-S/FS19_AutoDrive/issues/1091
Bitte testen und dann ein Feedback posten, danke!

**Comment by Mannie313** [comment]
@Iwan1803 welchen Discord habt ihr. Könnt ihr mir eine einladung schicken?

MFG Mannie313

**Comment by Iwan1803** [comment]
Hat hier zwar nichts zu suchen, aber: https://discord.gg/sUQtKhB
