### ISSUE TITLE
Problem beim Zusammenspiel von CP und AD speziell auf der "Slowakisches Dorf" Map

### ISSUE THREAD

**Issue by Andy2612** [Stephan-S/FS19_AutoDrive#1113]
![2](https://user-images.githubusercontent.com/61479274/75296656-14dd2a80-582e-11ea-86ad-bf20640295fd.jpg)
[log.txt](https://github.com/Stephan-S/FS19_AutoDrive/files/4252636/log.txt)

AutoDrive Version: 1.0.7.1-1
Release or custom zip: Release
Map (if applicable): Slovakisches Dorf
Vehicle / type (applicable): überwiegend Claas DLC

**Describe the bug**
Hallo, ich spiele zZ auf der Map Slovakisches Dorf, leider kann ich auf dieser Map eine Funktionen von CP und AD nicht nutzen wenn diese zusammen ausgeführt werden sollen. Das betrifft vor allen wenn CP Stroh oder Gras mit einem Ladewagen sammelt und dann an AD übergeben soll zum Transport in die Scheune oder zum Verkauf.
Zum Test habe ich  auf der Felsbrunn Standert Map getestet , auch mit dem Claas. Zusätlich habe ich jetzt auch mit allen Mod´s  getestet die ich im Game verwende und es funktioniert. Auch habe ich versucht die Abfahrer zu einen Silo zu schicken wo er eigentlich nicht abladen kann, aber er ist dennoch hingefahren.

Der Fehler sieht wie folgt aus( im Bild kann man sehen das nicht das Silo bzw Scheune aktiv ist), wenn CP an AD übergeben soll nimmt er den Feldpunkt und nicht die Scheune. Aus meiner Sicht scheint die Map verantwortlich zu sein. Aber warum , liegt es am Kurs selbst, der aber auch funktioniert wenn man nur AD benutzt(er finden den Wegpunkt und erkennt den Trigger zum entladen)?
Wo kann der Fehler liegen?

**If applicable - Steps to reproduce the behavior**

**Screenshots**

**Comment by Andy2612** [comment]
Hallo, ich spiele zZ auf der Map Slovakisches Dorf, leider kann ich auf dieser Map eine Funktionen vod CP und AD nutzen wenn diese zusammen ausgeführt werden sollen. Das betrifft vorallen wenn CP Stroh oder Gras mit einem Ladewagen sammelt und dann an AD übergeben soll zum Transport in die Scheune oder zum Verkauf.
Das es funktioniert habe ich zum Test auf der Felsbrunn Map getestet , auch mit dem Claas.

Der Fehler sieht wie folgt aus, wenn CP an AD übergeben soll nimmt er den Feldpunkt und nicht die Scheune.
Wo kann der Fehler liegen?

**Comment by jala15** [comment]
Have you set unload fill level to 100%? If so, set it lower because AD doesn´t fill trailer to 100%
![image](https://user-images.githubusercontent.com/52028079/75353367-91621e80-58ab-11ea-810f-c76e3f7733e7.png)
![image](https://user-images.githubusercontent.com/52028079/75353557-e9008a00-58ab-11ea-8964-6004975d5904.png)

**Comment by Blackjack155** [comment]
der verdacht liegt er bei denn 99%. Bei mir war das auch so das er ab und zu wenn der ladewagen nicht 100% hatte wieder zum Start gefahren ist. Teste mal was Passiert wenn du ihn zu 100% füllst ob er dann Abfährt?

**Comment by Andy2612** [comment]
@jala15  @Blackjack155  Danke für die Lösung, das mit den 99% war der Fehler. Bei mir waren bei AD 100% eingestellt, die Grundeinstellung liegt wohl bei 85%, daher hat es wohl auch auf der Testmap geklappt.

**Comment by Andy2612** [comment]
Lösung gefunden Problem gelöst
