### ISSUE TITLE
cant delete crosses in game 

### ISSUE THREAD

**Issue by ploughedfieldman123** [Stephan-S/FS19_AutoDrive#1115]
![2020-02-27_115643](https://user-images.githubusercontent.com/37042106/75443266-f031a180-5958-11ea-89cd-c4263788ff22.jpg)
Hi all I have just updated AD to 1.0.7.1  but some X  in game wont delete like the red line wont link to them so you cant delete them. so now cannot load up editor  there must be some X crosses in the game on routes what need to be deleted but I cant see any at all in game 

![2020-02-27_122643](https://user-images.githubusercontent.com/37042106/75445209-de51fd80-595c-11ea-8c43-d89133c88fee.jpg)

**Comment by ploughedfieldman123** [comment]
the crosses seem to have gone after a reboot. but the refresh icon is not there no more but it seems ok

**Comment by jala15** [comment]
Refresh not needed since last update because of live mode.
Deleted lines are a bit buggy for me sometimes too, they keep drawn but are not really there and in other tractors or when game reloaded they have disappeared correctly.

**Comment by ploughedfieldman123** [comment]
> Refresh not needed since last update because of live mode.
> Deleted lines are a bit buggy for me sometimes too, they keep drawn but are not really there and in other tractors or when game reloaded they have disappeared correctly.

Hi yes I didn't realise about the refresh icon. but its all sorted now
