### ISSUE TITLE
Trigger recognition to unload in global market building

### ISSUE THREAD

**Issue by PromGames** [Stephan-S/FS19_AutoDrive#1119]
I have tried to unload with autodrive in global market triggers, but they are not recognized as triggers. Also is not working in courseplay.

Prom

**Comment by Tensuko** [comment]
If you find a solution for AD, let us (CP) know pls.
I contacted the Modder about this, but we will see what can be done.

**Comment by Stephan-S** [comment]
I will look into it tomorrow.
@Tensuko If you have a solution before, feel free to let me know :-)

**Comment by Mannie313** [comment]
Hallo Autodrive Team und Tensuko.
Das abladen an Global Markt geht.
https://www.youtube.com/watch?v=U-WBmu_J6R8

Der Trigger ist zu weit unten deshalbn erkennt Autodrive oder Courseplay den nicht.

MFG Mannie313

**Comment by Justice-Molton** [comment]
Aber das Beladen funktioniert bei mir nicht. Das abladen ist kein Problem.

**Comment by Mannie313** [comment]
Das beladen ok geht nicht. abladen nachdem ich den trigger höher gemacht habe ja.

MFG Mannie313

**Comment by Mannie313** [comment]
Danke @Stephan-S läuft einwandfrei.

MFG Mannie313

**Comment by Stephan-S** [comment]
Beladen am Global Market sollte ab jetzt auch funktionieren.

@Tensuko Der Pull-Request von @kevin98 im Courseplay repository war ein guter Start. Dadurch werden die Trigger erstmal erkannt.
Da aber die Trigger nicht standardkonform sind, musste ich noch ein paar weitere Änderungen im AutoDrive Code vornehmen, damit der Füllstand korrekt ausgelesen wird. Falls das bei CP auch so oder ähnlich nötig ist, könnt ihr ja auf den letzten commit schauen.

**Comment by Justice-Molton** [comment]
Danke @Stephan-S 👍

**Comment by Iwan1803** [comment]
Wäre es nicht sinnvoller, wenn die von GC die Trigger entsprechend anpassen?

**Comment by Stephan-S** [comment]
Naja GC fügt ja eine ganze Menge Logik zu den Triggerstrukturen hinzu. Da ist es schon verständlich, dass die Strukturen sich etwas ändern. Aber schön wäre es natürlich wenn das dabei kompatibel zu den Standardtriggern bleiben könnte.
Aber da es jetzt schon angepasst ist, ist das eher ein Thema für die Zukunft, dass man sicherlich mit den Modder Kollegen besprechen kann :-)
Hier auf Github würde ich das Thema aber dann vorerst mal als erledigt ansehen.

**Comment by kevink98** [comment]
Die Trigger wurden doch nur erweitert. Es basiert doch auf den Standardtriggern.
