### ISSUE TITLE
Was kann ich...

### ISSUE THREAD

**Issue by spielera** [Stephan-S/FS19_AutoDrive#112]
Hallo,
was kann ich alles mit den gedownloaden Datei anfangen?
Bis jetzt habe ich sie brav, entpackt.
Habe den Ordner FS19_AutoDrive geöffnet und alles zu FS19_AutoDrive.zip gepackt, und dann ab in den Mod-Ordner.
Aber da sind ja noch viel mehr Ordner und Dateien drin.
Die werden ja nicht aus Langeweile da rein gemacht.
Falls einer ein Youtube-Video kennt, wo daß erklärt wird, würde ich mich freuen.
Schriftliche Form geht auch, kann lesen .;)

Macht weiter so.

**Comment by Stephan-S** [comment]
Servus spielera,

zu erst einmal, schön das dir der MOd gefällt :-)
Du musst keine zip Datei selber erstellen.
Schau einfach in den 'releases' Ordner, dort liegt immer die aktuellste Version als .zip Datei ab.

Die restlichen Dateien sind ein paar veraltete Kursdateien, die vermutlich nichr gebraucht werden und ein Kurseditor, den du bei installiertem Java einfach öffnen kannst um außerhalb des Spiels deine config/Strecken zu bearbeiten.

**Comment by spielera** [comment]
Danke für deine schnelle Antwort.
Wie kann man mit den Kurseditor, seine Dateien, bzw. die Strecken bearbeiten?
Ich habe noch kein Tutorial  gefunden.
