### ISSUE TITLE
[New Feature] Routes Manager

### ISSUE THREAD

**Issue by TyKonKet** [Stephan-S/FS19_AutoDrive#1120]
Hey guys, with the latest commits we have released the first preview of a new feature called **Routes Manager**
It will go to replace the old (and odd) way to export/import routes, currently we are still not supporting routes upload in multiplayer but we plan to enable that in the next future.

So what, give it a test and let as know what do you think.
Obviously bug reports are always welcome!

![image](https://user-images.githubusercontent.com/7534621/75545704-4ec55100-5a27-11ea-8471-90dc13d207d8.png)

**Comment by Blackjack155** [comment]
und was macht der?

**Comment by Onkel2000** [comment]
Do you have to retrace your routes?

**Comment by Bandesss** [comment]
Meine Strecke wird nicht importiert.
Macht ihr dafür ein Tutorial ? DIe Idee ist Klasse

**Comment by ploughedfieldman123** [comment]
Where is this routes manager then

**Comment by TyKonKet** [comment]
@ploughedfieldman123 you can open it from the AutoDrive hud

**Comment by ploughedfieldman123** [comment]
> @ploughedfieldman123 you can open it from the AutoDrive hud

you mean in the game the AD HUD  or do you mean ctrl+Lalt+0

**Comment by TyKonKet** [comment]
@ploughedfieldman123  In the HUD you have to go in "edit mode" to show the route manager button, otherwise you can use the shortcut (by default it's CTRL + ALT + KeyPad 1.
But as far as I can see from your screenshot, you are using the latest release, you have to manually zip the latest files if you want to get access to this new feature or just wait for the next release.

**Comment by ploughedfieldman123** [comment]
> @ploughedfieldman123 In the HUD you have to go in "edit mode" to show the route manager button, otherwise you can use the shortcut (by default it's CTRL + ALT + KeyPad 1.
> But as far as I can see from your screenshot, you are using the latest release, you have to manually zip the latest files if you want to get access to this new feature or just wait for the next release.

what do you mean manually zip what files can you help me

**Comment by ploughedfieldman123** [comment]
It's ok I have done it now. But can you edit a route or routes while in the game with using the AD editor then import back

**Comment by TyKonKet** [comment]
Yes that's the main goal of the feature, you can save and import as many time as you wish, so if you are scared to blow up your routes, you can always save them before you start to edit

**Comment by Stephan-S** [comment]
> It's ok I have done it now. But can you edit a route or routes while in the game with using the AD editor then import back

No, you cannot.
@TyKonKet I think you misunderstood @ploughedfieldman123 . Or did I miss a code change. The files created by your route manager are completely separate from the config files AutoDrive creates when you save your game and from the same file, the external AD Editor creates.

For now, the Routes Manager is basically a versioning tool for your network. You can save the current state and reload that at any time. But importing routes from the Editor can now only happen when you start the game with a replaced config file

**Comment by TyKonKet** [comment]
@Stephan-S yes, you are right, I misunderstood @ploughedfieldman123 😄

**Comment by ploughedfieldman123** [comment]
so its not same then as  nodes in the editor. as I am a bit lost what this can be used for then

**Comment by TyKonKet** [comment]
It can be used, as I said before, for backup purposes or for sharing routes between savegames.
Anyway i plan to expand his features in the next future.

**Comment by ploughedfieldman123** [comment]
> It can be used, as I said before, for backup purposes or for sharing routes between savegames.
> Anyway i plan to expand his features in the next future.

ok thanks for helping. will be handy anyway

**Comment by TyKonKet** [comment]
I'm also planning to make it useful to quickly upload routes on multiplayer servers and for sharing routes with friends, but that update will come in the next weeks.

**Comment by ploughedfieldman123** [comment]
> I'm also planning to make it useful to quickly upload routes on multiplayer servers and for sharing routes with friends, but that update will come in the next weeks.

That sounds good, But is this anything to do with Routes Manager as never seen this before. I have noticed if you click on bottom of lines the red part turns blue But I am puzzled what it does

<a href="https://ibb.co/1XWw8b9"><img src="https://i.ibb.co/pKF9Jn3/2020-03-04-101833.jpg" alt="2020-03-04-101833" border="0"></a>

**Comment by TyKonKet** [comment]
That's nothing about routes manager, it's the new "in game" editor, with it you can create, connect and move way points.

**Comment by Bandesss** [comment]
Wie aktiviert man diesen ? @TyKonKet

**Comment by ploughedfieldman123** [comment]
> That's nothing about routes manager, it's the new "in game" editor, with it you can create, connect and move way points.

Oh I see as in AD menu on bottom left of snap It says about Lshift create and Lalt to delete  so maybe i dont have those keys set up. I will give it a go

**Comment by TyKonKet** [comment]
@ploughedfieldman123 you can drag&drop way points with right mouse button

**Comment by ploughedfieldman123** [comment]
> @ploughedfieldman123 you can drag&drop way points with right mouse button

So you mean once you have made a node with say Lctrl  you just use rmb  to move it

**Comment by TyKonKet** [comment]
yes, and you can also move existing nodes.

**Comment by ploughedfieldman123** [comment]
> yes, and you can also move existing nodes.

yeah its great.  just been trying.  did you also know a trick when you are recording a 2 way line in blue. and you stop recording.  but then realise you want to make blue line longer. soon as you record next node point its a green line, but here is the trick, if you drive to 1st arrow end of green line. then make sure yellow line is linked to other end of arrow, then click join it will change to blue line. its very handy

**Comment by ABCD104970** [comment]
Hallo habe eine Frage .wo bekomme ich AD1.0.7.1-14  zum runterladen her. Danke

**Comment by TyKonKet** [comment]
From the homepage of this project.
![image](https://user-images.githubusercontent.com/7534621/75971544-34c9b980-5ed2-11ea-859b-4cac94646455.png)

**Comment by ABCD104970** [comment]
besten Dank

**Comment by ploughedfieldman123** [comment]
> Hallo habe eine Frage .wo bekomme ich AD1.0.7.1-14 zum runterladen her. Danke

https://github.com/Stephan-S/FS19_AutoDrive/blob/master/releases/1.0.7.1/FS19_AutoDrive.zip

**Comment by MaLouPa** [comment]
Habe das Update auf die neue Version auch gemacht. Gibt es einen Trick die vorhandenen Kurse in den neuen Routen Manager zu laden? Spielen aktuell auf einem Dedi.

**Comment by Bandesss** [comment]
Der nimmt die normale datei nicht.
Wir haben die Punkte in die neu erstellte Datei per Editor eingebaut

**Comment by MaLouPa** [comment]
Scheinbar hat es bei uns gereicht eine gesicherte Config neu ins Savegame verzeichnis zu schieben 🤷🏼‍♂️

**Comment by Stephan-S** [comment]
Will be reopened when new functionality is finished :-)
