### ISSUE TITLE
To do list (suggestion)

### ISSUE THREAD

**Issue by Twetch** [Stephan-S/FS19_AutoDrive#1121]
Hi,is it possible to add something like "to do list" ,where i can set multiple transport routes or other jobs? This feature can be handy, with courseplay for example, if i want seed or spray multiple fields in row (Start:Farm->Field 1->Field 2->Go back to farm).Or if you have more dairy farms around map ,so you can set multiple loading poins for one truck.

**Comment by Stephan-S** [comment]
The first feature won't make it into the mod(s) since it 
a) sort of completely removes the player from doing anything :D and
b) would always require a combination from both mods

The second one is already implemented with the feature 'Multiple targets'.

**Comment by Twetch** [comment]
Sorry i didn't know about that multiple target feature...and about doing anything, is just my profesion degeneration and lazyness :D

**Comment by Iwan1803** [comment]
Don't be lazy - it's a simulator and not a manager game 😎

Seeding and spraying with refill of both at a silo for **1** field is allready possible with CP & AD.
For unloading at several goals you can use "Multiple targets".

If you speak German -> https://www.youtube.com/playlist?list=PL5cOkXj5iscpEZSnI-w1jv3p304IRzZZP
