### ISSUE TITLE
Tractor wont fill up at the Silo

### ISSUE THREAD

**Issue by Vega56** [Stephan-S/FS19_AutoDrive#1122]
AutoDrive Version: 1.0.7.1
Release or selbsterstelltes zip: Release
Karte (falls relevant): Alle
Fahrzeug(art) (falls relevant):

**Beschreibe den Bug**
Der Kurs lädt nicht wie gewünscht am Silo.
Er bleibt kurz vor dem eigentlichen Tricker stehen.

**Falls anwendbar - Schritte mit denen ich den Bug nachstellen kann**

**Screenshots**
![20200229214020_1](https://user-images.githubusercontent.com/55054246/75614794-b6b98b80-5b3c-11ea-9a87-6985b3e3e0a1.jpg)
![20200229214024_1](https://user-images.githubusercontent.com/55054246/75614797-b7eab880-5b3c-11ea-9052-92cd9afb2891.jpg)
![20200229214032_1](https://user-images.githubusercontent.com/55054246/75614798-b7eab880-5b3c-11ea-9d48-d4c030f55096.jpg)

Kann es evtl. am Silo liegen?

**Comment by Iwan1803** [comment]
Für mich sieht das so aus, als ob er den Zielpunkt "Hofsilo" zu früh erreicht und daher nicht mehr lädt.
Setz den Zielpunkt einfach mal auf den nächsten Wegpunkt, am Ende der Laderampe.

**Comment by Vega56** [comment]
Hallo,
danke für den Tipp!
Hab ihn selbst schon ein Stück nach vorne versetzt, aber anscheinend nicht genug. 

Jetzt funktioniert es natürlich. Danke :)

**Comment by Iwan1803** [comment]
Gern geschehen, ist mir am Anfang auch immer häufiger passiert 😊
Kleiner Tip: such dir das längste Gespann (z.Bsp. LKW mit 3-Achsen-Auflieger o.ä.) und fahr es manuell so hin, das du Laden/Entladen kannst. Den nächsten Wegpunkt vor der Fahrzeugfront (mit mind. 1-2m Abstand) nimmst du dann als Zielpunkt.
Das sollte dann eigentlich für alle Gespanne passen.
