### ISSUE TITLE
Harvester Unload doesnt work

### ISSUE THREAD

**Issue by Vega56** [Stephan-S/FS19_AutoDrive#1123]
AutoDrive Version: 1.0.7.1
Release or selbsterstelltes zip: Release
Karte (falls relevant): NF_Marsch_2.7_OG
Fahrzeug(art) (falls relevant):

**Beschreibe den Bug**
Der Drescher wird nicht abgetankt. Es funktioniert nur wenn ich den Autodrive Abfahrer deaktiviere und wieder aktiviere. Sobald er aber einmal auf dem Feld abgetankt hat bleibt er beim nächsten mal stehen und der Drescher wird nicht abgetankt. 

Courseplay Version : .389

**Screenshots**
![20200301113422_1](https://user-images.githubusercontent.com/55054246/75624068-09cd2600-5bb1-11ea-94dd-b258e439da23.jpg)

![20200301113826_1](https://user-images.githubusercontent.com/55054246/75624085-3b45f180-5bb1-11ea-807d-3c2c79dcb9bb.jpg)

[log.txt](https://github.com/Stephan-S/FS19_AutoDrive/files/4271649/log.txt)

**Comment by Iwan1803** [comment]
Ich wage zu bezweifeln, das dieses Problem auf allen Maps auftaucht. Daher wäre diese Info schon interessant, genauso welche Fahrzeuge (Mods oder Standart?) bei dem Problem genutzt worden sind, als es auftrat.
Lt. Log hast du mehrere Maps im mods-Ordner liegen, was man nicht machen sollte (u.a. NFM oG, Rade, Holzer Map). 
Außerdem stehen da etliche Warnings und Error drin, um die dich als erstes mal kümmern solltest.

PS: bitte auch hier mal einen Blick rein werfen: https://github.com/Stephan-S/FS19_AutoDrive/issues/1071

**Comment by Stephan-S** [comment]
Hey,
bist du sicher, dass im Drescher das selbe Ziel 'F1' eingestellt ist?

Auf dem Screenshot sieht es so aus als würde das Fahrzeug einfach nicht zum/vom Drescher gerufen. Wenn das Ziel richtig eingestellt ist, probier erstmal den Standardhelfer auf dem Drescher aus, ob es damit funktioniert.

**Comment by Vega56** [comment]
@Iwan1803 

Das mit den Maps ist doch normal? Ich schiebe ja nicht jedes mal die Map in den Mods Ordner die ich spielen möchte.

Ich werde jetzt mal ein paar Mods entfernen mit entsprechenden Warnings.

@Stephan-S 

Meinst du beim Drescher Autodrive auf F1 ?

Als der Abfahrer jetzt das letzte mal abgetankt hat, gab es ziemliche FPS Drops. Ähnlich wie #1089

![20200301123922_1](https://user-images.githubusercontent.com/55054246/75625003-215cdc80-5bba-11ea-8299-7ff587065647.jpg)

**Comment by Stephan-S** [comment]
kannst du mal bitte auf die aktuellste Entwicklerversion updaten?
Also auf die 1.0.7.1-13



> Meinst du beim Drescher Autodrive auf F1 ?

Ja genau.

**Comment by Iwan1803** [comment]
Drescher und Abfahrer müssen das gleiche Ziel (Feld) eingestellt haben, damit es funktioniert.

**Comment by Vega56** [comment]
Danke für die Hilfe.

Das mit der Zieleinstellung wusste ich nicht. Werde mir jetzt nochmals alle Tutorials durchschauen, sodass ich euch hier nicht gleich belästigen muss ;)

Momentan funktioniert alles.
