### ISSUE TITLE
Fehler mit in Game Editor

### ISSUE THREAD

**Issue by Blackjack155** [Stephan-S/FS19_AutoDrive#1124]
AutoDrive Version: 1.0.7.1-13

So bald ich die Karte starte bekommt ein Error und wenn der in Game Editor öffne Schreibt er die Log voll.

[log.txt](https://github.com/Stephan-S/FS19_AutoDrive/files/4272191/log.txt)

**Comment by RalfGorden** [comment]
hab auch die AutoDrive Version: 1.0.7.1-13 
bekomme keine Errors

**Comment by Blackjack155** [comment]
@RalfGorden  Wie schlau dein Kommentar war echt Kollege *Kopf schütteln*
