### ISSUE TITLE
Tractor drives to the wrong gas station

### ISSUE THREAD

**Issue by Rumspringa90** [Stephan-S/FS19_AutoDrive#1125]
AutoDrive Version: 1.0.7.1
Release or selbsterstelltes zip: Release
Karte (falls relevant): NF Marsch 4-fach 1.4
Fahrzeug(art) (falls relevant): alle

**Beschreibe den Bug**
Wenn ein Schlepper nurnoch wenig Sprit hat, fährt er, wenn in den Einstellungen von AutoDrive aktiviert, automatisch zur "nächsten" Tankstelle. Da ist es mir schon häufig passiert, das er nicht zu einer Tankstelle fährt, sondern zu dem Flüssigkeitslager (von der NF Marsch). Dort kann er aber nicht getankt werden und bleibt dort stehen.

**Lösungsvorschlag 1:**
Man prüft, ob man an der Position nachtanken kann. (falls es so eine Funktion überhaupt gibt?!)

Nach ein bisschen googlen bin ich auf den "[GasStationTrigger](https://gdn.giants-software.com/documentation_scripting.php?version=script&category=67&class=3382)" gestoßen. Da ich mich leider nicht wirklich damit auskenne, weiß ich nicht ob dieser weiterhilft. 

**Lösungsvorschlag 2:**
Man nimmt einen definierten Wegpunkt als Tankstelle dann hat man aber nur eine Tankstelle was für mich ok wäre

**Lösungsvorschlag 3:**
Tankstellen müssen einen bestimmten Text haben anhand der AutoDrive weiß, das dies eine Tankstelle ist

**Comment by Iwan1803** [comment]
**Lösungsvorschlag 4:**
Dani sollte auf der NFM mal prüfen, ob das Flüssigkeitslager einen Tank-Trigger hat und diesen dann rausnehmen.
Am Donnerstag wird wohl die neue Version erscheinen.

**Comment by Rumspringa90** [comment]
Naja wenn dort der Tank-Trigger drin wäre, dann würde er dort ja auch tanken oder nicht?

**Comment by Iwan1803** [comment]
Nicht, wenn er da keinen Diesel bekommen 🤔

**Comment by Rumspringa90** [comment]
Ich habe das eben mal getestet. Er kann bei dem Lager getankt werden. Allerdings mit Auswahl des FillTypes (also Diesel) ich vermute das er (AutoDrive) deswegen nicht automatisch tankt?

**Comment by Iwan1803** [comment]
Muss man an dem Trigger denn bezahlen, um etwas zu bekommen und steht was im Lag, wenn er da ankommt und nicht tanken kann?

**Comment by Rumspringa90** [comment]
Ne bezahlen muss man nicht, ist ja mein Hof Flüssiglager. Ein Eintrag im Log kann ich jetzt nicht sagen. Glaube aber nicht, sobald ich ein Fahrzeug hab was tankt, achte ich darauf.

Das wäre auch eine Möglichkeit.

Wie gesagt, ich vermute das er da nicht tankt, weil es ein "Multi" Silo ist und er dann nicht weiß was er dort auffüllen soll. Eine normale Tankstelle hat ja nur ein FillType -> Diesel

**Comment by Rumspringa90** [comment]
So ich hatte eben einen der zum tanken an das Lager gefahren ist. Hier die [log.txt](https://github.com/Stephan-S/FS19_AutoDrive/files/4293442/log.txt). Dabei ist mir aufgefallen, der Trecker hatte eine Düngespritze angehängt, das er Diesel gar nicht zur Auswahl hatte sondern nur Flüssigdünger als ich manuell "R" gedrückt hatte. 

Version ist inzwischen **1.0.7.1-18**

**Comment by Rumspringa90** [comment]
Ich hatte jetzt mal den ganzen Diesel aus dem Lager entnommen mit der Hoffnung das er dann dort nicht mehr zum tanken hinfährt. Leider fährt er dann trotzdem zum Lager anstatt zur Tankstelle.

**Comment by TyKonKet** [comment]
**Hello, Thank you for opening this issue!**
Since we have just released [the new refactored version of AutoDrive](https://github.com/Stephan-S/FS19_AutoDrive/releases/tag/1.1.0.0), we can no longer provide any feedback or support for open bug reports related to the old code base.
If the problem persists, please reopen a new issue with all the required details.
Thank you for understanding and we hope you continue enjoying our mod 😄
