### ISSUE TITLE
It's not a bug, it's fascinating

### ISSUE THREAD

**Issue by Williwillswisse** [Stephan-S/FS19_AutoDrive#1128]
Hallo Stephan und Team,
ich hatte dich ja am Anfang des LS19 mal angeschrieben ob du den Mod nach LS19 konvertieren würdest. Da warst du dir noch nicht sicher.
Jetzt muss ich dir mal sagen, dass es der reine Wahnsinn ist was du mit AutoDrive so machst.
Unvorstellbar den LS ohne zu Spielen!
Vielen Dank dafür an dich und Alle die dabei helfen von mir und unserem LS-Team (Mario Hrischfeld)
(Lass dir den Kaffee schmecken ;-) )
![image](https://user-images.githubusercontent.com/47098121/75774928-4899e200-5d51-11ea-8055-f94bf2e64811.png)

**Comment by Stephan-S** [comment]
Danke dir Willi :-)
Ich mach hier mal zu
