### ISSUE TITLE
Feature Request: Make Pipe Offset Steps Smaller

### ISSUE THREAD

**Issue by aletheist** [Stephan-S/FS19_AutoDrive#1131]
**Is your feature request related to a problem? Please describe.**
I consistently have issues with collisions with the combine pipe on certain harvesters, particularly root crop harvesters.

**Describe the solution you'd like**
For pipe offsets between 0±1m I suggest changing the pipe offset increments to tenths of meters instead of quarters. I have done this locally with success.

**Describe alternatives you've considered**
One can of course make different prudential decisions on what increments to include; I have found the suggestion above to work for me for this need.

**Additional context**
I have only explored with respect to the combine offset. not the other offsets related to combine unloading. This would, unfortunately, make the pipe offsets inconsistent with other offsets. However, I think the pipe offsets are significantly more sensitive to small changes in distance to avoid collisions or to activate the pipe at all.

**Comment by aletheist** [comment]
With some trailers I seem to have difficulty getting consistency out of the distance the trailer winds up from the pipe almost no matter what.

**Comment by Stephan-S** [comment]
Sounds very reasonable :-)
The problem is that changing the values ususally leads to problems when the 'old' config is loaded and the resulting values are different then expected.
So I have to make sure those values are migrated correctly.

And the inconsistency is especially a problem when you work on rather uneven fields. And the approach accuracy also depends somewhat on the vehicle/trailer combination and the chosen approach path of the pathfinder algorithm

**Comment by aletheist** [comment]
Upon first load after the changes I did have to reset the per-vehicle values but that was a price I was willing to pay.

I have also had some success setting the trailer offset to cause the unloader to park under the pipe closer to the front of the trailer instead of the middle.

**Comment by aletheist** [comment]
Does the game engine provide sufficient elevation information for the harvester and approaching vehicle to make the uneven field approach more accurate with the right trigonometry? I'd be willing to look into that section of the code as well. I just ran into that exact issue.

I think the relevant math is one or both of these places? It also looks like I may have been a few commits behind so you may have already fixed some of the inconsistency was seeing.

https://github.com/Stephan-S/FS19_AutoDrive/blob/master/FS19_AutoDrive/scripts/AutoDriveCombineMode.lua#L738

https://github.com/Stephan-S/FS19_AutoDrive/blob/master/FS19_AutoDrive/scripts/AutoDrivePathFinder.lua#L24

**Comment by Stephan-S** [comment]
Included in refactor process
