### ISSUE TITLE
game Crash 

### ISSUE THREAD

**Issue by RickBlackLabele** [Stephan-S/FS19_AutoDrive#1132]
AutoDrive Version: die von Github aktuelle 
Release or selbsterstelltes zip: Release
Karte (falls relevant): Alle
Fahrzeug(art) (falls relevant): Futter Mischer (Mein Lely Vector)

**Beschreibe den Bug**
ich möchte den fahrer einstellen spiel friert ein und schließt sich
![Screenshot (947)](https://user-images.githubusercontent.com/41070781/75888071-1492ef80-5e2b-11ea-937b-ec9c39365faf.png)

**Comment by Blackjack155** [comment]
Log Fehlt.

**Comment by Iwan1803** [comment]
@Blackjack155 
du solltest dich an deine eigene Nase fassen 😉

@RickBlackLabele 
tritt das nur bei diesem Mod auf oder auch bei anderen? Ist die eingestellte Route eher eine kurze oder lange?
Und ja, das Log könnte hilfreich sein.

**Comment by RickBlackLabele** [comment]
die log sagt nichts aus und ja es ist eine kurz strecke ,bei futter selbstfahrer und ja

**Comment by RickBlackLabele** [comment]
ok habe mal neues savegame gemacht da geht alles komisch

**Comment by Tensuko** [comment]
Wenn ich hier mal kurz einhaken dürfte... nur weil du in der log nichts erkennst, heist es nicht, dass die log nichts aussagt :)
In einer log steckt mehr drin als mancher glauben mag.
Sei es ein User der Reinguckt und bereits selber einen Modkonflikt kennt, oder in einer Liste an Meldungen genau den entscheidenen Hinweist erkennt.
Eine log hilft fast immer! :)
