### ISSUE TITLE
Bug gefunden oder Problem

### ISSUE THREAD

**Issue by Blackjack155** [Stephan-S/FS19_AutoDrive#1134]
AutoDrive Version: 1.0.7.1-18
Release or selbsterstelltes zip: Release
Karte (falls relevant): Alle
Fahrzeug(art) (falls relevant):

**Beschreibe den Bug**
Nach start der Karte wenn ich ihn einschalte will er zu seinem Parkplatzt. Springt also von zb. Laden & Abladen direkt zu Fahre Parkplatz.

**Comment by Iwan1803** [comment]
"1.0.7.1-18" ist keine Release-, sondern eine Dev-Version, aber egal.
"Alle" Maps kann nicht, denn ich habe das Problem weder auf der NFM 4x noch Südhemmern. Alle Fahrzeuge haben nach dem Laden noch ihre alte AD-Route drin und ich kann sie sofort wieder starten, ohne das sie ihre Route ändern.
Um welches Fahrzeug handelt es sich bei dem Problem und tritt das mit jedem auf und was war vorher eingestellt?
Vielleicht könnte auch das Log dazu helfen.

**Comment by Blackjack155** [comment]
Du Nervst erlich Warum Kommentierst du überhaubt und Klugscheißert hier rum lass es doch einfach.

Ich hab es nur Hier gepostet für andere die vlt das gleiche Problem haben.
