### ISSUE TITLE
Inconsistent Combine Pipe Pathfinding on Inclines

### ISSUE THREAD

**Issue by aletheist** [Stephan-S/FS19_AutoDrive#1135]
AutoDrive Version: d7a011b
Release or custom zip: Custom
Map (if applicable): Ravenport (but probably all)
Vehicle / type (applicable): All combine/harvester combinations

**Describe the bug**
When a harvester rests on an incline it is difficult to set the pipe offset correctly because the pathfinding destination node does not take into account the effect of harvester's rotation with respect to level when determining node placement. Once you find an offset that works in one direction, the same offset may not work in the other as the harvest works rows.

**If applicable - Steps to reproduce the behavior**
Run east-west rows on field 5 in Ravenport using the 470 Terra-Trac and SB II 30/1070 trailer. The margin for error on this combination is very small because the 'pipe' and the trailer are almost the same height.

**Potential Remediation**
I believe [this function](https://github.com/Stephan-S/FS19_AutoDrive/blob/master/FS19_AutoDrive/scripts/AutoDrivePathFinder.lua#L24) can be modified such that the calculation of the [destination node](https://github.com/Stephan-S/FS19_AutoDrive/blob/master/FS19_AutoDrive/scripts/AutoDrivePathFinder.lua#L71) takes into account the difference of the harvester/pipe from level. I'll have to think about the geometry of the problem some more to produce a solution.

As a first approximation, I changed `y = worldY` to `y = nodeY` where [nodeY is added here](https://github.com/Stephan-S/FS19_AutoDrive/blob/master/FS19_AutoDrive/scripts/AutoDrivePathFinder.lua#L63). This got me a marginally better path calculation but is far from a full solution, particularly when the harvester is on an incline such that the pipe is pointed uphill.

Caveat emptor: This is the first time I've ever looked at lua, much less a Farming Simulator mod. Any PR from me should be looked at with extreme suspicion.

**Comment by Stephan-S** [comment]
Hey @aletheist 
I like that you are trying to contribute :-) Keep it up!
We will check any PR carefully. Don't worry about that.

You are right about everything above, except probably with you change to the y value.
Since this is just the height of the world, it doesn't influence the vehicle at all, so any change you noticed was probably coincidental.

If you have the geoemtry figured out, feel free to share it. Leaves me the trouble of working it out for now :D 
I just noticed that problem this week when pöaying on the Wild Wild West Map. So yeah, we should work on that!

**Comment by aletheist** [comment]
Been thinking about this more and I think there might be a simpler method, although it may turn out to suffer from imprecisions as well. However, I suspect you've already thought of this and therefore there's a good reason it isn't done.

At the moment, the pathfinder attempts to put the center of the vehicle on the `dischargeNode`, plus or minus the `pipeOffset`. However, one could make a default value of `pipeOffset = 0.0` if you knew which side of the combine the pipe is on and the width of the unloader. I was thinking something like this, in pseudocode.

```
if dischargeNodeOnLeft then 
    driverOffset = driver.sizeWidth/2.0
elseif dischargeNodeOnRight then
    driverOffset = -driver.sizeWidth/2.0

offset = driverOffset + pipeOffset
```

However, I can't figure out how to determine if the `dischargeNode` is on the left or the right of the combine.

**Comment by aletheist** [comment]
This code is absolutely awful and I'm pretty sure terribly wrong, but I want to share my notes as I look into this so that you or others can tell me where I might be missing something easy. I admit my vector arithmetic skills are so rusty I kind of just gave up and started doing trial and error.

After some quick testing I can set a single offset that works as the implement goes both directions. I just think I've got the right behavior for the wrong reasons, and it looks extremely fragile.

```
local nodeX, nodeY, nodeZ = getWorldTranslation(dischargeNode)
        local distX, distY, distZ, distance = AutoDrive.getWorldDirection(worldX, 0, worldY, nodeX, 0, nodeZ)
        -- Assumptions (intended to be) introduced:
        -- Positive pipe offset values pipe is on the left. We go as far to the left/right as possible, so
        -- The only reason to set an offset is on the same side and to get closer. 
        local pipeOffset = AutoDrive.getSetting("pipeOffset", driver)
        -- This value should be a constant modulo changes caused by elevation
        local elevationCorrection = math.abs((combine.sizeWidth / 2) - math.abs(distance))
        local driverOffset = ((driver.sizeWidth / 2.0) - elevationCorrection) * AutoDrive.sign(AutoDrive.getSetting("pipeOffset", driver))
        pipeOffset = driverOffset + pipeOffset
```

**Comment by aletheist** [comment]
I think I'm way in over my head on the vector transformations. I could certainly refresh my vector skills, but even if I did that the information is stored in the variables is opaque to me so I don't know what they represent. For example, this kind of setup is throughout the code and I don't know why it's done, much less how to use it properly to achieve my goals.

```
local worldX, worldY, worldY = getWorldTranslation(combine.components[1].node)
    local rx, _, rz = localDirectionToWorld(combine.components[1].node, 0, 0, 1) -- Seems to be a system API call. No idea what this returns or why the arguments are what they are.
    local combineVector = {x = rx, z = rz} -- Don't know what these represent.
    local combineNormalVector = {x = -combineVector.z, z = combineVector.x} -- At least I know what a normal vector is.
```

I also think I'm wrong about the geometry of the problem to some extent. I think the issue is actually the `driver`s tilt with respect to level -- the lip of the trailer changes position depending on the slope of the ground. We know exactly where the pipe is via `dischargeNode` so it can't be the combine's rotation away from level that's the problem. I don't know of any way to determine what incline the trailer will be on upon arrival at the `dischargeNode`.

Perhaps the `combine`'s rotation could be used as a heuristic, making the assumption that the ground right next to the combine is similar to the situation the combine is currently in, but a situation where the combine and driver are on opposite sides of a small hump (`c/\d`) would probably lead to issues.

Hopefully this brainstorming is useful. I will continue to think about this and share code if I come up with anything that works, but I suspect you will solve it before me.

**Comment by aletheist** [comment]
In some very limited testing the following code seems to work. Please forgive the rather bland variable names. This is the first time I've done trigonometry in a lot of years so I had to be very explicit about it :-)

My goal here is to treat the distance between ground under the combine node and the ground under the pipe node as the hypotenuse of a right triangle (`hyp`). I treat the difference in height between the ground under the combine and the ground under the pipe as another side of that right triangle (`dh`). I solve for the third side, which gives what the distance would be on level ground (`run`). Next, I solve for the angle between the combine and the right angle in the triangle (or, put another way, the angle of the slope of the ground) (`theta`).  Finally, I solve for what the new X coordinate of the the pipe would be if it underwent a rotation of `theta`. Here, I am using the pipe as a proxy variable for the lip of the trailer. Finally, I find the difference between the X coordinate of the unrotated vs. rotated node and use it as a correction factor to the pipe offset.

```
local worldX, worldY, worldZ = getWorldTranslation(combine.components[1].node)
...
local nodeX, nodeY, nodeZ = getWorldTranslation(dischargeNode)
        local heightUnderCombine = getTerrainHeightAtWorldPos(g_currentMission.terrainRootNode, worldX, worldY, worldZ)
        g_logManager:info("heightUnderCombine: " .. heightUnderCombine);
        local heightUnderPipe = getTerrainHeightAtWorldPos(g_currentMission.terrainRootNode, nodeX, nodeY, nodeZ)
        g_logManager:info("heightUnderPipe: " .. heightUnderPipe);

        -- want this to be negative if the ground is lower under the pipe
        local dh = heightUnderPipe - heightUnderCombine
        g_logManager:info("dh: " .. dh);
        local _, _, _, hyp = AutoDrive.getWorldDirection(worldX, heightUnderCombine, worldZ, nodeX, heightUnderPipe, nodeZ)
        g_logManager:info("hyp: " .. hyp);
        local run = math.sqrt(hyp * hyp - dh * dh)
        g_logManager:info("run: " .. run);
        local theta = math.asin(dh/hyp)
        g_logManager:info("theta: " .. theta);
        g_logManager:info("nodeY: " .. nodeY);
        local elevationCorrection = run - (run * math.cos(theta) + (nodeY - heightUnderPipe) * math.sin(theta))
        g_logManager:info("elevationCorrection: " .. elevationCorrection);

        local pipeOffset = AutoDrive.getSetting("pipeOffset", driver)
        pipeOffset = pipeOffset + elevationCorrection
        local trailerOffset = AutoDrive.getSetting("trailerOffset", driver)
        local lengthOffset = 5 + driver.sizeLength / 2
        if firstBinIsOnDriver then
            lengthOffset = 0
        end

        if lengthOffset ~= 0 or trailerOffset ~= 0 then
            wpAhead = {x = (nodeX + (lengthOffset + trailerOffset) * rx) - pipeOffset * combineNormalVector.x, y = nodeY, z = nodeZ + (lengthOffset + trailerOffset) * rz - pipeOffset * combineNormalVector.z}
        end
        wpCurrent = {x = (nodeX - pipeOffset * combineNormalVector.x), y = nodeY, z = nodeZ - pipeOffset * combineNormalVector.z}
        wpBehind_close = {x = (nodeX - AutoDrive.PATHFINDER_TARGET_DISTANCE_PIPE_CLOSE * rx - pipeOffset * combineNormalVector.x), y = nodeY, z = nodeZ - AutoDrive.PATHFINDER_TARGET_DISTANCE_PIPE_CLOSE * rz - pipeOffset * combineNormalVector.z}

        wpBehind = {x = (nodeX - (lengthOffset + trailerOffset + AutoDrive.PATHFINDER_TARGET_DISTANCE_PIPE) * rx - pipeOffset * combineNormalVector.x), y = nodeY, z = nodeZ - (lengthOffset + trailerOffset + AutoDrive.PATHFINDER_TARGET_DISTANCE_PIPE) * rz - pipeOffset * combineNormalVector.z} --make this target
```

**Comment by aletheist** [comment]
As expected, there is a north-south route on RP field 5 that has a slight hump in it such that the harvester and trailer are on opposite signed slopes and this results in the correction going the wrong direction. However, since you can set the offset tolerance tighter with the corrections, it did not result in a missed unload.

I think this situation could be made less likely by using the instantaneous slope based on `getTerrainNormalAtWorldPos`. However, that is a global slope and I don't know how to correct it to be relative to the combine. With the available information, however, I cannot think of a solution that never encounters this issue.

**Comment by Iwan1803** [comment]
-> https://github.com/Stephan-S/FS19_AutoDrive/releases/tag/1.1.0.4

**Comment by pvaiko** [comment]
I know this is an old one but when looking for a solution for a similar problem, this was one of the few hits for `getTerrainNormalAtWorldPos()` so I thought it is probably worth sharing my experience with it.

I came up with a different solution to consider terrain incline in https://github.com/Courseplay/courseplay/commit/ad70faefba9f81314c262a21222b677a220c2940, see the function `setWorldPositionAndRotationOnTerrain()` at: https://github.com/Courseplay/courseplay/blob/ad70faefba9f81314c262a21222b677a220c2940/course-generator/PathfinderUtil.lua#L284
