### ISSUE TITLE
Shuttle control randomly stays "turned off" after arriving destination

### ISSUE THREAD

**Issue by PHansen940** [Stephan-S/FS19_AutoDrive#1136]
AutoDrive Version: 1.0.7.1
Release or custom zip: Custom
Map (if applicable): Hof Bergman 1.0.0.6 Beta2
Vehicle / type (applicable): Different, but all standard vehicles

**Describe the bug**
After driving and successfully arriving with Autodrive, "Shuttle control" from FS19_VehicleControlAddon (Version 1.0) is turned off. This happens sometimes, sometimes it does not. I haven't found out a pattern until now. Different vehicles, different destinations. It's confusing
I GUESS Autodrive is turning it off somehow when activated but only sometimes reactivate it, sometimes it just forgets to do so.

**Comment by Stephan-S** [comment]
hm, AutoDrive doesn't specifically interact with VCA. The only reason I see for it to be turned off, is when the Fuel saving option is enabled in AutoDrive and the motor is turned off at the arrival point. This does not happen when you are inside the vehicle, so I guess it's hard to see for yourself if you didn't know that :-)
Can you check of that's the case?

**Comment by PHansen940** [comment]
Hi Stephan,

sorry I'm blind - where do I find the "Fuel saving option" in Autodrive? It is activated tough, engine turns off evertime

My Test so far.

#1 Shuttle control on, driving with Autodrive, staying in the Tractor
The moment I activate AD, the VCA Shuttle control symbol disappears. The moment AD arrives the destination - VCA Shuttle control symbol appears

#2 Shuttle control on, driving with Autodrive, **leaving the tractor right after starting with key "E"**
The moment I activate AD, the VCA Shuttle control symbol disappears. Entering the tractor after he has arrived at destination  - VCA Shuttle control symbol displayed

#3 Shuttle control on, driving with Autodrive, **leaving the tractor right after starting with key "Tab"** The moment I activate AD, the VCA Shuttle control symbol disappears. Entering the tractor after he has arrived at destination  - VCA Shuttle control symbol IS NOT displayed (1 out of 6 test runs)
 
#4 Same as #3 BUT: VCA Shuttle control symbol displayed; This is quite confusing since it reflects my experience in the past that I do not see a pattern, but sometimes it does work, sometimes it does not (5 out of 6 test runs)

**Comment by TyKonKet** [comment]
**Hello, Thank you for opening this issue!**
Since we have just released [the new refactored version of AutoDrive](https://github.com/Stephan-S/FS19_AutoDrive/releases/tag/1.1.0.0), we can no longer provide any feedback or support for open bug reports related to the old code base.
If the problem persists, please reopen a new issue with all the required details.
Thank you for understanding and we hope you continue enjoying our mod 😄
