### ISSUE TITLE
pickup and delivery section error Axel: AutoDrive:dijkstraLiveShortestPath ERROR count > 50000

### ISSUE THREAD

**Issue by Iab72** [Stephan-S/FS19_AutoDrive#1138]
AutoDrive Version: 1.0.7.1
[log.txt](https://github.com/Stephan-S/FS19_AutoDrive/files/4297645/log.txt)

Release or custom zip: Release
Map (if applicable): Eiersholt
Vehicle / type (applicable):

**Describe the bug**
feeding the animal 

**If applicable - Steps to reproduce the behavior**

**Screenshots**

**Comment by Axel32019** [comment]
Hello,
This is an error exit which usually should not happen.
A screenshot where I can see the current vehicle (and it's position) and the target selected in AD would help very much.
Could you please zip the file "Autodrive...config.xml" and attach it in a comment here, so I can have a look.
Thanks

**Comment by Stephan-S** [comment]
Hey @Axel32019 I haven't checked the log yet and I'm really busy with some refactoring, but I just wanted to say that I recently (between 1.0.7.1 and 1.0.7.2) fixed a bug where we had MapMarkers in the array which could point to an already deleted waypoint. So this might be a cause for something like that.

**Comment by Iab72** [comment]
hi @Axel32019  Thanks for respond to the bug.  This is the "AutoDrive xml , and the screenshot how it freez" 
[AutoDrive_Eiersholt_config.zip](https://github.com/Stephan-S/FS19_AutoDrive/files/4300222/AutoDrive_Eiersholt_config.zip)
![fsScreen_2020_03_06_21_47_39](https://user-images.githubusercontent.com/11736318/76118951-098cba80-5ff7-11ea-9dc2-62888e39eb4c.png)
![fsScreen_2020_03_06_21_48_59](https://user-images.githubusercontent.com/11736318/76118977-14474f80-5ff7-11ea-88c8-fa1019768937.png)
![fsScreen_2020_03_06_21_51_30](https://user-images.githubusercontent.com/11736318/76119006-21643e80-5ff7-11ea-839d-a1cadebb9278.png)

**Comment by Axel32019** [comment]
@Iab72 The is a one blue connection on the way to "Feeding Pigs" before the gate to the pig husbandry. If you change this to a green connection it will work.

**Comment by Iab72** [comment]
Thanks i will try it. But I think it's two ways . If I change it will work?

**Comment by Iab72** [comment]
Thanks  @Axel32019  it works
