### ISSUE TITLE
Ad nimm nicht die trigger sobald er sie von server lädt

### ISSUE THREAD

**Issue by Opminol** [Stephan-S/FS19_AutoDrive#1139]
moin ich wollte mal fragen warum der AD auf den Server nicht richtig funktioniert,
da er nicht die Trigger erkennt und dadurch nicht selbstständig ablädt oder lädt.
Im offline oder wenn ich den Multiplayer erstelle aber schon. 
Würde das gerne behoben bekommen.

Schon mal im voraus danke an das Mod Team

[Log.txt](https://github.com/Stephan-S/FS19_AutoDrive/files/4298163/Log.txt)

**Comment by Blackjack155** [comment]
Ohne Mod´s auf denn Server getestet? Nur mit AD?

**Comment by Opminol** [comment]
Nein habe ich noch nicht kann das aber gerne testen

**Comment by Opminol** [comment]
So habe es jetzt ausgiebig getestet und herausgefunden das der AD die Trigger vom Globalmanager nicht erkennt was kann ich dagegen tun, und warum erkennt er sie im offline oder wenn ich die Sitzung erstelle

**Comment by Axel32019** [comment]
Was ist denn "Globalmanager" ?
Ich würde empfehlen mal mit der aktuellen AD Version zu testen - aktuell Release 1.0.7.2.
Da wurden zwischen 1.0.7.1. Release und 1.0.7.2. einige Verbesserungen an den Ab- / Lade-Triggern gemacht. Wenn ich das richtig sehe läuft bei Dir 1.0.7.1. Release .

**Comment by Opminol** [comment]
ok lade die aktuelle Version runter und teste sie.
kann sein das du ihn unter GlobalCompany kennst.

**Comment by Opminol** [comment]
So habe mir das jetzt angeschaut und testet, er hat Probleme mit der Erkennung der Trigger von Global Companie.
Das Problem tritt nur auf wenn ich den Dedi Server betrete.
Jetzt hat er schonmal den Trigger von der Grastrocknung auf der multimap zum Beladen und den enlade Trigger beim Heulager gefunden.

Kann es sein das ihn ein Datei Fehlt damit er die Trigger findet.

Ihr könnt gerne einen Gastzugang bekommen zum Server damit ihr euch das mal anschauen könnt oder den Server Betreten.

Ich kann es mir auf jeden fall nicht erklären warum es im offline funktioniert und auf den Server nicht.

MfG Opmi

**Comment by Opminol** [comment]
kann es sein das der drive ein Problem mit den Produktionen hat wenn die nicht alle auf einer farm habe, da es ja fuktioniert im wenn ich es hoste

**Comment by OliWit82** [comment]
Das gleiche Problem haben wir auch auf der Nordfriesischen Marsch 4 Fach.
Offline ohne Probleme, auf dem Server erkennt er die Trigger nicht.

**Comment by Stephan-S** [comment]
Hallo, da wir gerade die neue restrukturierte Version von AutoDrive released haben, können wir leider keine Bugs und Issues die sich noch auf die alte Codebasis beziehen mehr bearbeiten.
Wenn das Problem bzw. dein Anliegen in der atkuellen Version weiterhin besteht, mache doch bitte ein neues Issue mit allen benötigten Informationen auf.
Oder melde dich bei kleineren Themen und Fragen auch gerne direkt im Discord:
https://discord.gg/sUQtKhB

Vielen Dank für dein Verständniss und ich hoffe du hast weiterhin Spaß am AutoDrive Mod :-)

Und hier noch ein Link zur aktuellen Version:
https://github.com/Stephan-S/FS19_AutoDrive/releases/tag/1.1.0.0
