### ISSUE TITLE
Vorschlag für Wegpunkte

### ISSUE THREAD

**Issue by mnicklisch** [Stephan-S/FS19_AutoDrive#114]
Hi,

erstmal vielen Dank für die Mod und deine Arbeit daran, selten so eine gut durchdachte Mod gesehen =)

Ich hatte da eine Idee für die Wegpunkte von AD. Ich spiele meistens auf Mod-Maps, d.h. ich verbringe sehr viel Zeit damit Kurse einzufahren. Habe jetzt gesehen dass es auch einen Editor gibt, den werde ich heute mal direkt ausprobieren.
Aber die meiste Zeit geht dafür drauf die Routen in beide Richtungen zu generieren und dann natürlich auch Kreuzungen zu verbinden.
Ich dachte mir, es wäre doch sicherlich möglich es so umzubauen dass die Routen in beide Richtungen befahrbar wären indem die Fahrzeuge sich dann immer in Fahrtrichtung rechts von der Route halten. 
So bräuchte man auf seinen Maps nur knapp die Hälfte der Wegpunkte. Das würde Ressourcen sparen und natürlich auch Zeit beim einfahren der Kurse.
Ist natürlich eine ziemlich große Anpassung, das weiß ich, aber wäre doch für ein späteres Release eventuell denkbar, oder?

Auf jeden Fall nochmal Danke für deine Arbeit.

Grüße

**Comment by Stephan-S** [comment]
Hey,

erstmal danke für den Vorschlag! Die Idee hat einige interessante Aspekte.
Wenn ich so etwas einbaue, würde ich es allerdings als dritten Streckentyp hinzufügen. Also gäbe es dann:
    1. Normale Strecken (eine Richtung)
    2. Strecken die in beiden Richtungen befahren werden. Dort warten Fahrzeuge bis das jeweils andere aus der Strecke heraus ist.
   3. Dein Vorschlag, mit Offset, rechts zur Fahrtrichtung.

Auf Straßen, die auch tatsächlich zwei Spuren haben, kann ich mir das gut vorstellen. Dort würde es tatsächlich den Aufwand der Streckenerstellung deutlich reduzieren.

Aber spätestens bei den Ein/Ausfahrten von/zu dieser Straße sehe ich die ersten Probleme. Bisher probiert man ja diese in einer gewissen sanften Kurve an die Straße anzuschließen. Wenn die Strecken aber in beiden Richtungen befahren werden. müssten man hier eigentlich immer 90° Winkel nehmen, die man so weder einfach aufzeichnen kann, noch kann der Fahrer diese vernünftig abfahren.
 
Also wie gesagt, als Ergänzung zu den bisherigen Typen auf jeden Fall interessant. Nur muss man die Probleme auch betrachten.

Und um ehrlich zu sein wird es das Feature vermutlich nicht mehr in der LS19 Version geben.
Derzeit kümmere ich mich eigentlich fast nur noch um Bugs, nicht mehr um Feautureerweiterung. Aber für LS21 kann ich das direkt mit ins Konzept einbauen, wenn es soweit ist.

Viele Grüße,
Stephan

**Comment by ThisPf** [comment]
Um das Problem der Kreuzungen zu lösen, würde ich nicht mit einem Offset sondern mit zwei gleichzeitig generierten Kursen arbeiten. So kannst du am Anfang und Ende mit den gewohnten Verbindungen weiter arbeiten. Auch irgendwelche Inseln oder ähnliches lassen sich dann einfach umfahren. Wenn die Distanz zwischen den Kursen Einstellbar wäre, könnte man auf Map-Gegebenheiten reagieren und optimieren. Schematisches Bild:
![image](https://user-images.githubusercontent.com/25609067/63922478-0d86c100-ca45-11e9-8342-34ca9f78284a.png)

**Comment by Bandesss** [comment]
Das wäre super und würde viel Zeit sparen

**Comment by Stephan-S** [comment]
Cleaning up old issues.
