### ISSUE TITLE
Teleporting to an AutoDrive waypoint resets the pickup location for vehicles

### ISSUE THREAD

**Issue by StuartLivings** [Stephan-S/FS19_AutoDrive#1140]
AutoDrive Version: 1.0.7.1
Release or custom zip: Release
Map (if applicable): Sussex Farms
Vehicle / type (applicable): All tested (tractors, UTV, Man truck)

**Describe the bug**
When you teleport to an AD waypoint using the main map the target locations change for vehicles which are already following AD paths.

**If applicable - Steps to reproduce the behavior**
* Set a vehicle doing a pickup/deliver and check that it is following the correct route.
* Press Escape to go to the main map, click on an AD waypoint and teleport there using Space.
* Press Escape to go to the main map, click on the previous vehicle and teleport there using Space.
* The vehicle target has changed to the AD waypoint teleported to in step 2.

**Comment by Iwan1803** [comment]
Use the the actual dev version as it was fixed. You can set now the change option in the AD config menu.

**Comment by StuartLivings** [comment]
Is this fixed as part of #1077 ?
