### ISSUE TITLE
Reverse along path if in a dead-end/cul-de-sac

### ISSUE THREAD

**Issue by StuartLivings** [Stephan-S/FS19_AutoDrive#1142]
**Is your feature request related to a problem? Please describe.**
Several maps and placeables have triggers located in places where you can only drive in one way and have to reverse out again.  These triggers are unusable using Autodrive because it does not currently know how to reverse out.

**Describe the solution you'd like**
I could see two possible ways of routing the reverse path:
* Reverse driving direction when the angle between paths is greater than 180 degrees.  This would allow the user to define specific 'reversing' routes by deliberately creating paths with forward-and-reverse nodes.  This solution allows the user to define the exact path taken to reach the destination.
* Automatically detect paths which do not have any 'outward' paths.  In these cases the path should be driven to the final node (probably a waypoint) forwards and then the path should be reversed until the next junction (node with multiple outward paths), where the vehicle should then drive forwards to continue to its final destination.  This solution would allow more autonomous resolution, however it does not accommodate complex one-way paths well.

Completing either of the above in reverse with a trailer is complex, however:
* There is trailer reversing code available in CoursePlay which may be portable for these uses.
* Solving the problem only for vehicles without trailers (e.g. trucks) would at least allow users to experiment before solving the larger problem of trailers, especially multiple trailers.

**Comment by Iwan1803** [comment]
As reverse driving was allready implemented -> closed.
