### ISSUE TITLE
It's more of a question... Collisions

### ISSUE THREAD

**Issue by auddie2015** [Stephan-S/FS19_AutoDrive#1144]
**AutoDrive Version:** 1.0.7.1   
**Release or Custom Zip:** Release  
**Map (If applicable):** All  
**Vehicle / Type (If applicable):**   
**Multiplayer or Singleplayer:** Singleplayer  

**Describe the bug**  
On combine unload mode, the chaser, almost without fail, drives directly into the back of the combine like it is ignoring the pipe offset. It hits the combine directly in the center of the back end.

Do I need to manually set the offset or should it be automatic?

**Comment by Iwan1803** [comment]
You can change the distance and also the distance to the pipe for an unloader/follower in the AD menu of that unloader.

**Comment by auddie2015** [comment]
Thanks!
