### ISSUE TITLE
INFO: EN: Refactoring ongoing / ------- DE: Code wird umstrukturiert 

### ISSUE THREAD

**Issue by Stephan-S** [Stephan-S/FS19_AutoDrive#1146]
Hey guys, just to let you know. We are doing some heavy overhauling of the codebase to make it more readeale, more stable and easier to debug and most importantly to make it easier to add new features without breaking something else unintentionally.
We hope to be finished until the next weekend, but  it's hard to approximate how long it will take to rip the whole codebase apart and organize in a better structure.
So the 1.0.7.2 release should stay untouched for that time and I will not include any bugfixes or small feature request in that time, since the code is already being transformed right now and is not stable.

When we have something to present or rather to test out :-) please be aware that there could be a lot of things broken in the first iterations of the refactoring. I will test all basic functions before the first dev release but I can't cover every use case :-)

Thank you for your patience in the next days or rather weeks!

----------------------------------------------------------------------------------------------

Hey Leute, nur um es euch wissen zu lassen. Wir überarbeiten derzeit die Code-Basis, um sie lesbarer, stabiler und leichter zu debuggen und vor allem, um das Hinzufügen neuer Funktionen zu erleichtern, ohne dass etwas anderes unbeabsichtigt zerstört wird.
Wir hoffen, dass wir bis zum nächsten Wochenende fertig sind, aber es ist schwer zu schätzen, wie lange es dauern wird, die gesamte Codebasis auseinander zu reißen und in einer besseren Struktur zu organisieren.
Daher sollte die Version 1.0.7.2 für diese Zeit unberührt bleiben, und ich werde in dieser Zeit keine Bugfixes oder kleine Feature-Anforderungen einbauen, da der Code bereits jetzt transformiert wird und nicht stabil ist.

Wenn wir etwas zu präsentieren oder besser gesagt zu testen haben :-), dann seit euch bitte bewusst, dass in den ersten Iterationen des Refactorings eine Menge Dinge kaputt gehen könnten. Ich werde alle grundlegenden Funktionen vor der ersten Entwicklerversion testen, aber ich kann nicht jeden Anwendungsfall abdecken :-)

Vielen Dank für Eure Geduld in den nächsten Tagen bzw. Wochen!

**Comment by Justice-Molton** [comment]
Take the time that it needs.
