### ISSUE TITLE
triggers

### ISSUE THREAD

**Issue by ploughedfieldman123** [Stephan-S/FS19_AutoDrive#1147]
**AutoDrive Version:** 1.0.7.2   
**Release or Custom Zip:** Release  
**Map (If applicable):** GreenWich Valley
**Vehicle / Type (If applicable):**   tractor/trailer
**Multiplayer or Singleplayer:** Singleplayer  

why dont trailers move to destination name  then tip loads at triggers, as it always unload as in screenshot.  not pull up to where arrow points to. then unload so trailer is on the tip place in middle 

<a href="https://ibb.co/zbDK5cn"><img src="https://i.ibb.co/rMNntP7/2020-03-07-082718.jpg" alt="2020-03-07-082718" border="0"></a>

**Comment by Stephan-S** [comment]
This is not a bug.
It's more of a cosmetic problem.
The truck unloads as soon as it reaches the trigger point.
To solve this, I would have to do some complicated calculations to see if this trigger will still be there when I reach the target point. 
This way, all combinations of vehicles and trailers can unload at your trigger as long as the destination is sufficiently in front of the trigger

**Comment by ploughedfieldman123** [comment]
> This is not a bug.
> It's more of a cosmetic problem.
> The truck unloads as soon as it reaches the trigger point.
> To solve this, I would have to do some complicated calculations to see if this trigger will still be there when I reach the target point.
> This way, all combinations of vehicles and trailers can unload at your trigger as long as the destination is sufficiently in front of the trigger

Oh ok I will check to see in Giants Editor if I can make trigger box closer to destination point

I dont really know where to post questions on here regarding any help. where is best place

**Comment by Stephan-S** [comment]
If you want general help or discuss things, get over on our Discord server, which is linked on the homepage here.
Just don't expect 24/7 service from us developers there :D

**Comment by ploughedfieldman123** [comment]
> If you want general help or discuss things, get over on our Discord server, which is linked on the homepage here.
> Just don't expect 24/7 service from us developers there :D

ok thanks for that I tend to keep forgetting that discord server
