### ISSUE TITLE
Keine Möglichkeit Haltepunkt ohne Wegpunkt zu erstellen

### ISSUE THREAD

**Issue by XPiRiJenZ** [Stephan-S/FS19_AutoDrive#115]
Hallo Stephan,
mit der Modhub-Version ist es nicht möglich einen Haltepunkt zu erstellen, ohne dass vorher ein Wegpunkt aufgezeichnet wurde.
Versucht man dies, kann man die Haltepunkt-Bezeichnung nicht mehr beenden und das Eingabefeld bleibt dauerhaft aktiv, so dass man die Tastatur nicht mehr benutzen kann und nur noch mit ALt+F4 aus dem Spiel kommt.

2 Vorschläge:
1. Beim erstellen eines Haltepunkts wird automatisch ein Wegpunkt erzeugt, so dass man die Eingabe bei der Bezeichnung des Haltepunkts abschließen kann oder
2. Mit Hilfe von ESC die Eingabe abbrechen, so dass man die Tastatur wieder nutzen kann.

**Comment by Stephan-S** [comment]
Hey,

wie du schon schreibst betrifft der Bug nur die Modhub Version und wurde schon behoben.
Eine automatische Erstellung von Kurspunkten halten ich nicht für besonders gut, da ein einzelner Punkt ohne Verbindungen nicht viel Nutzen hat und man ja danach eh Strecken verbinden muss.
Da würde ich eher direkt das "Autoconnect" Feature aktivieren und an der entsprechendne Haltestelle kurz anhalten, erstellen und man ist fertig.

Der zweite Punkt, mit ESC abzubrechen ist aber berechtigt. Aber da das mehr im Code ist, als es sein sollte, lasse ich das vermutlich. Wenn ein Punkt versehntlich erstellt wurde, kann er ja mit einem Tastendruck gleich wieder entfernt werden :-) (Wenn in den Optionen belegt).

Aber danke für den Input und viele Grüße,
Stephan
