### ISSUE TITLE
Kurvengeschwindigkeit selber anpassen

### ISSUE THREAD

**Issue by Michael170978** [Stephan-S/FS19_AutoDrive#1150]
Hi

Ich hab da eine Frage zu der Geschwindigkeit.

Gibt es eine Möglichkeit die Kurvengeschwindigkeit selber anzupassen?

Ich finde die Fahrzeuge bremsen zu stark vor einer Kurve ab. Ich würde nicht motzen wenn es um 90 Grad Kurven gehen würde. Aber ich finde schon übertrieben wenn ein Fahrzeug z. B. vor einer 15 Grad Kurve von 90 Km/h auf 30 Km/h abbremst, die Kurve nimmt und danach wieder beschleunigt. Vor langer Zeit konnte man die Bremswirkung selber einstellen aber das wurde leider raus genommen. In der neuen Version kann man jetzt den Kurs selber editieren. Vielleicht kann man zu dem Editor die Geschwindigkeit hinzufügen. Dann könnte man selber entscheiden welches Fahrzeug mit welcher Geschwindigkeit in der Kurve fahren soll, in dem man vor der Kurve z.B ein Verkehrszeichen über der grünen Linie setzt. Autodrive hat ja schon eingebauten Geschwindigkeitsregler. Man könnte so man man stellt sich gewünschte Geschwindigkeit ein, drückt einmal drauf und diese Geschwindigkeit merkt sich der Kurs Editor. Dadurch könnte man den Fahrzeugen untersagen auf eigenem Hof, im Feld oder im Wald mit hoher Geschwindigkeit zu fahren.

**Comment by Iwan1803** [comment]
Das würde das Configfile enorm vergrößern, was wiederum bei MP zu Ärger und Problemen führen würde.
Deaktivier doch mal das Smoother Driving, ob er dann schneller um die Kurven fährt.

**Comment by Michael170978** [comment]
Smoother Driving ? kannst du mir bitte sagen wo ich das finden kann? Noch nie gehört bzw. gesehen diese Option?

**Comment by Iwan1803** [comment]
Drück STRG + ALT + 0 (Null), um ins AD-Konfigurationsmenü zu kommen. Unter dem letzten Menübutton ist es versteckt, wenn ich mich nicht täusche.

**Comment by Michael170978** [comment]
Hab's gemacht wie du beschrieben hast. Hab einmal mit Fend Schlepper und dann mit Scania LKw probiert. Bei dem Schlepper ist es nicht so extrem. Bei dem LKW sieht man leider keine Veränderung.
Schade aber so ist es halt wenn du sagst es ist zu umfangreich sowas zu programmieren.

**Comment by roland45** [comment]
Mache das derzeit so: Geschwindigkeitsreduzierung zb vor Kreuzugen usw. Die AD Leitlinie wird kurz davor als eine Zick-Zack Linie gebildet. Das Fahrzeug gleicht dies aus und bleibt gerade auf Kurs, aber die Geschwindigkeit wird stark reduziert. Dies ist mein Tip der Geschwindigkeitsreduzierung mit derzeit vorhandenen Mittel.

**Comment by Michael170978** [comment]
Du hast mein Problem falsch verstanden. Mir geht es nicht darum, dass die Fahrzeuge zu langsam abbremsen bzw. überhaupt nicht abbremsen. Mir geht es darum, dass die Fahrzeug nicht bei jeder Kurve in die Eisen gehen sollen. Wenn ich z.B meinen LKW mit der Milch zum Verkauf schicke und er mit 80 km/h fährt, dann will ich nicht, dass er bei der nächsten kleinen Kurve auf 30 km/h abbremst. Ich spiele gerne auf 4-Fach Maps und ich empfinde das als störend. Genauso stört es wenn ein Schlepper auf dem Hof mit 40 km/h zum Silo fährt. Mein Wunsch wäre selber die Geschwindigkeit zu regeln. In alten Version war da eine Option wo man die Bremskraft selber einstellen konnte. Das hat super funktioniert. Leider haben die Jungs von Autodrive die Funktion raus genommen.

Um mein Problem zu verstehen hab ich ein kurzes Video hochgeladen. Der Lkw ist nicht beladen.

https://youtu.be/Lqsyw9hYoeE

**Comment by roland45** [comment]
Stimmt, es ist nicht genau dein Problem, es sollte nur die Beeinflussung der AD Geschwindigkeit auf geraden Strecken (zB. bei Radarbox LS17, ) behandeln, wo der LKW mit 70 oder 80 dahinrauscht und an einem gewissen Punkt langsamer vorbeifahren soll. Habe dies nur hier geschrieben, weil es das Thema Geschwindigkeit betrifft. Sorry.

**Comment by Michael170978** [comment]
Alles gut. Ich bin nicht sauer oder so. Mit den Radarboxen hast du auch recht. Gott sei Dank sind die Dinger auf der Multimap nicht verbaut. Wie viel kostet eigentlich so ein Ticket fürs zu schnelles Fahren?

**Comment by roland45** [comment]
Gabs nur im LS17. Für LS19 glaube ich noch nicht. Habe aber die punktuelle Geschwindigkeitsreduzierung in der MAP Porta Westfalica bei einer Brücken-Abfahrtsrampe eingesetzt, da dort durch unsaubere Anbindung einer  Rampe (beim Zirkus) ein Katapulteffekt und Rauswurf bei zu hoher Geschwindigkeit entstand. Nun kann ich die gesamte MAP mit AD ohne Probleme mit voller Geschwindigkeit befahren lassen.  AD ist ein super MOD!! Daumen hoch!!

**Comment by Stephan-S** [comment]
Hallo, da wir gerade die neue restrukturierte Version von AutoDrive released haben, können wir leider keine Bugs und Issues die sich noch auf die alte Codebasis beziehen mehr bearbeiten.
Wenn das Problem bzw. dein Anliegen in der atkuellen Version weiterhin besteht, mache doch bitte ein neues Issue mit allen benötigten Informationen auf.
Oder melde dich bei kleineren Themen und Fragen auch gerne direkt im Discord:
https://discord.gg/sUQtKhB

Vielen Dank für dein Verständniss und ich hoffe du hast weiterhin Spaß am AutoDrive Mod :-)

Und hier noch ein Link zur aktuellen Version:
https://github.com/Stephan-S/FS19_AutoDrive/releases/tag/1.1.0.0
