### ISSUE TITLE
refueling seeders in convoy

### ISSUE THREAD

**Issue by Serge63230** [Stephan-S/FS19_AutoDrive#1151]
AutoDrive Version : 1.0.7.2
Release or Custom Zip : Release
Map : Marwel Manor
Vehicle / Type : seeder Kuhn BTF 4000 with Kuhn TF 1512
Multiplayer or Singleplayer : Singleplayer  
Version Courseplay : 6.01.00392 

**Describe the bug**  
I use 2 tractors to sow the fields in convoy. the convoy option is activated on both tractors.

I created the race with courseplay using the autodrive reload option.
I configure autodrive in loading mode.

when the seed drill of the first tractor is empty, the tractor goes to the refueling point, he fills the tank with seeds, then he returns to the field and continues his work.

when the tank of the second tractor is empty, the tractor goes to the refueling point, it passes in front without stopping and it returns to the field. courseplay detects that the tank is empty and sends it back to refueling 

**Screenshots**  
no screenshots.

**Comment by Stephan-S** [comment]
Hm, that is indeed strange. Are you using the same vehicle and tool(s) on both drivers?
The fact that they work in a convoy should not have any effect on AutoDrive's ability to refuel as long as the fill level is sufficiently low so that AutoDrive detects that it should load.

Can you double check that you haven't set any AutoDrive option to a strange value? Such as the 'Unload fill level'

**Comment by Serge63230** [comment]
Hi Stephen.

I use  the same vehicle and tool on both drivers.

I made screenshots of the 2 vehicles. I did not think I had changed the settings on any of the 2 because I bought these 2 tractors to use them with the seeders directly.

I will adjust the 2nd tractor like the first and do some tests.

I will post the result as soon as possible.

![vehicule1_1](https://user-images.githubusercontent.com/46240465/76358921-95b22100-631a-11ea-9eb4-4e97f9767d5c.PNG)
![vehicule1_2](https://user-images.githubusercontent.com/46240465/76358931-9cd92f00-631a-11ea-81c8-36966c2c9c02.PNG)
![vehicule1_3](https://user-images.githubusercontent.com/46240465/76358944-a06cb600-631a-11ea-9e45-6cf07bda492f.PNG)
![vehicule1_4](https://user-images.githubusercontent.com/46240465/76358948-a2cf1000-631a-11ea-8978-b32c3d5e92e4.PNG)
![vehicule2_1](https://user-images.githubusercontent.com/46240465/76358954-a498d380-631a-11ea-9f6f-ab1d4ab9bd32.PNG)
![vehicule2_2](https://user-images.githubusercontent.com/46240465/76358977-acf10e80-631a-11ea-90e5-e4307dda341b.PNG)
![vehicule2_3](https://user-images.githubusercontent.com/46240465/76358987-afebff00-631a-11ea-82cb-a89d2a64dd97.PNG)
![vehicule2_4](https://user-images.githubusercontent.com/46240465/76358990-b1b5c280-631a-11ea-8a6d-5744e343a9d0.PNG)

**Comment by Serge63230** [comment]
I set the 2 tractors with the same parameters as on the vehicle1_x images

I always get the same result

- the first vehicle opens the seed drill cover and stops to refuel

- the second vehicle does not open the cover of the seed drill and passes in front of the refueling without stopping

I checked the courseplay settings which are identical for the 2 tractors; the only difference is that the first is shifted to the right and the 2nd is shifted to the left

maybe this bug is due to courseplay ...

**Comment by Serge63230** [comment]
I just did the same test deactivating the convoy option of the courseplay

I still have the same result

the 1st tractor stops refueling and the 2nd does not stop

**Comment by Serge63230** [comment]
I just did one last test

I have equipped vehicle A with tank B and vehicle B with tank A
In this configuration, vehicle A no longer refuels and vehicle B now stops for refueling

So I sold the seed drill B and the tank B to buy new equipment
and there, miracle, my 2 tractors stop at the refueling

Sorry to have questioned self-drive. I should have started by doing these tests. But I never thought that an original game tool could have a problem.

Thank you very much for the work accomplished, the autodrive mod has become essential for me. I can no longer play Farming Simulator without this mod.

I hope that Giant will integrate the autodrive in the next version of FS.

Good luck for the further development of this little gem ...

You cn close this issue

**Comment by Stephan-S** [comment]
Hey, I'm glad it's working for you now :-)

But I'm still interested to find the root cause of this issue, if possible.
So just to clarify this point again:
The tool (seeder) and the tank you were using on vehicle A and B were the exact same type? And you bought the exact same types again?
If not, I would be glad if you could give me the exact models of all, if it wasn't only these two: 

> seeder Kuhn BTF 4000 with Kuhn TF 1512

Were any of the tools rented by a contract or store bought?

Thank you for your feedback!

**Comment by Serge63230** [comment]
Good evening Stephen.

I bought 2 Massey Ferguson MF 770 tractors with 2 Kuhn BTF4000 seeders and 2 Kuhn TF 1500 tanks.

It is not a rental, it is a purchase.

Here is the copy of the contents of my vehicles.xml file. What is strange is that the 2 tanks are not defined in the same way, and there are differences in the values :

<vehicle id="40" filename="data/vehicles/kuhn/kuhnTF1500/kuhnTF1500.xml" isAbsolute="true" age="3.000000" price="11000.000000" farmId="1" propertyState="1" operatingTime="47051.718750">
        <component1 position="-9.6839 28.2423 -138.1525" rotation="170.3391 -15.6456 -179.7664"/>
        <configuration name="cover" id="1"/>
        <configuration name="wheel" id="1"/>
        <configuration name="fillUnit" id="1"/>
        <configuration name="fillVolume" id="1"/>
        <boughtConfiguration name="cover" id="1"/>
        <boughtConfiguration name="wheel" id="1"/>
        <boughtConfiguration name="fillUnit" id="1"/>
        <boughtConfiguration name="fillVolume" id="1"/>
        <washable>
            <dirtNode amount="1.000000"/>
            <dirtNode amount="1.000000"/>
        </washable>
        <wearable>
            <wearNode amount="0.003388"/>
        </wearable>
        <attacherJoints comboDirection="-1"/>
        <foldable foldAnimTime="1.000000"/>
        <fillUnit>
            <unit index="1" fillType="SEEDS" fillLevel="30.000000"/>
        </fillUnit>
        <cover state="1"/>
    </vehicle>
    <vehicle id="41" filename="data/vehicles/kuhn/kuhnTF1500/kuhnTF1500.xml" isAbsolute="true" age="3.000000" price="11000.000000" farmId="1" propertyState="1" operatingTime="41780.015625">
        <component1 position="-14.8751 27.6954 -129.2796" rotation="164.7562 -64.9979 -172.1297"/>
        <configuration name="fillUnit" id="1"/>
        <configuration name="wheel" id="1"/>
        <configuration name="cover" id="1"/>
        <configuration name="fillVolume" id="1"/>
        <boughtConfiguration name="cover" id="1"/>
        <boughtConfiguration name="wheel" id="1"/>
        <boughtConfiguration name="fillUnit" id="1"/>
        <boughtConfiguration name="fillVolume" id="1"/>
        <washable>
            <dirtNode amount="1.000000"/>
            <dirtNode amount="1.000000"/>
        </washable>
        <wearable>
            <wearNode amount="0.003263"/>
        </wearable>
        <attacherJoints comboDirection="-1"/>
        <foldable foldAnimTime="0.000000"/>
        <fillUnit>
            <unit index="1" fillType="SEEDS" fillLevel="30.000000"/>
        </fillUnit>
        <cover state="1"/>
    </vehicle>

**Comment by Serge63230** [comment]
`<vehicle id="40" filename="data/vehicles/kuhn/kuhnTF1500/kuhnTF1500.xml" isAbsolute="true" age="3.000000" price="11000.000000" farmId="1" propertyState="1" operatingTime="47051.718750">
        <component1 position="-9.6839 28.2423 -138.1525" rotation="170.3391 -15.6456 -179.7664"/>
        <configuration name="cover" id="1"/>
        <configuration name="wheel" id="1"/>
        <configuration name="fillUnit" id="1"/>
        <configuration name="fillVolume" id="1"/>
        <boughtConfiguration name="cover" id="1"/>
        <boughtConfiguration name="wheel" id="1"/>
        <boughtConfiguration name="fillUnit" id="1"/>
        <boughtConfiguration name="fillVolume" id="1"/>
        <washable>
            <dirtNode amount="1.000000"/>
            <dirtNode amount="1.000000"/>
        </washable>
        <wearable>
            <wearNode amount="0.003388"/>
        </wearable>
        <attacherJoints comboDirection="-1"/>
        <foldable foldAnimTime="1.000000"/>
        <fillUnit>
            <unit index="1" fillType="SEEDS" fillLevel="30.000000"/>
        </fillUnit>
        <cover state="1"/>
    </vehicle>
    <vehicle id="41" filename="data/vehicles/kuhn/kuhnTF1500/kuhnTF1500.xml" isAbsolute="true" age="3.000000" price="11000.000000" farmId="1" propertyState="1" operatingTime="41780.015625">
        <component1 position="-14.8751 27.6954 -129.2796" rotation="164.7562 -64.9979 -172.1297"/>
        <configuration name="fillUnit" id="1"/>
        <configuration name="wheel" id="1"/>
        <configuration name="cover" id="1"/>
        <configuration name="fillVolume" id="1"/>
        <boughtConfiguration name="cover" id="1"/>
        <boughtConfiguration name="wheel" id="1"/>
        <boughtConfiguration name="fillUnit" id="1"/>
        <boughtConfiguration name="fillVolume" id="1"/>
        <washable>
            <dirtNode amount="1.000000"/>
            <dirtNode amount="1.000000"/>
        </washable>
        <wearable>
            <wearNode amount="0.003263"/>
        </wearable>
        <attacherJoints comboDirection="-1"/>
        <foldable foldAnimTime="0.000000"/>
        <fillUnit>
            <unit index="1" fillType="SEEDS" fillLevel="30.000000"/>
        </fillUnit>
        <cover state="1"/>
    </vehicle>`

**Comment by Serge63230** [comment]
![image](https://user-images.githubusercontent.com/46240465/76475770-4c3c0180-6400-11ea-8ae9-67ff928ea96b.png)

**Comment by TyKonKet** [comment]
**Hello, Thank you for opening this issue!**
Since we have just released [the new refactored version of AutoDrive](https://github.com/Stephan-S/FS19_AutoDrive/releases/tag/1.1.0.0), we can no longer provide any feedback or support for open bug reports related to the old code base.
If the problem persists, please reopen a new issue with all the required details.
Thank you for understanding and we hope you continue enjoying our mod 😄
