### ISSUE TITLE
Häxeln Grasschwad geht nichts

### ISSUE THREAD

**Issue by DerBauer2** [Stephan-S/FS19_AutoDrive#1153]
Die Abfahrer fahren auf denn Häxler hinten auf und Fahren Rückwärs dann bleiben sie stehn und drehen um und fahren wieder heran und das spiel geht von vorne los.  Ich habe schon 8m eingestellt es bringt nichts. Ich weiß nicht was gemacht wurde aber voher haben die nicht so rum gezickt.

vlt kam man ein schnelles Hotfix raus hauen :)

**Comment by Iwan1803** [comment]
@DerBauer2 
warum benutzt du nicht das Template und warum gibst du nicht alle relevanten Infos raus?
Welche Map, welche Fahrzeuge, Screenhots (bes. der AD-Einstellungen), Log?
Wir haben keine Glaskugel und keine Hellseherin und nur weil es bei dir nicht funktioniert, muss es noch lange nicht an AD liegen und ein Bug sein.

**Comment by DerBauer2** [comment]
Weitere Infos sind nicht Nötig. Add wieder Bug! Log nicht nötig kein Fehler. Du hast es noch nicht begriffen das ich alles Teste. Es ist ein Fehler oder Fehlerhafte erknnung nenne es wie du willst ist mir egal. Der fehler soll auch NICHT an DICH gehn sondern Steffan. Mehr sage ich nicht zu dir.

**Comment by Iwan1803** [comment]
Da du nicht bereit bist, wie gefordert dein Problem zu melden, mache ich hier zu.
