### ISSUE TITLE
error shutting down

### ISSUE THREAD

**Issue by ploughedfieldman123** [Stephan-S/FS19_AutoDrive#1154]
**AutoDrive Version:** 1.0.7.2
**Release or Custom Zip:** Release  
**Map (If applicable):** All  
**Vehicle / Type (If applicable):**   
**Multiplayer or Singleplayer:** Singleplayer  

why do I keep getting this error when i try to start to drive a route

**Encountered a problem during initialization shutting down**

<a href="https://ibb.co/jHB4VXV"><img src="https://i.ibb.co/KmRyNvN/2020-03-10-092610.jpg" alt="2020-03-10-092610" border="0"></a><br />

**Comment by Nokiamen** [comment]
Hi. I get errors when I try to run AutoDrive Course Editor

---------------------------
Java Virtual Machine Launcher
---------------------------
Error: A JNI error has occurred, please check your installation and try again



---------------------------
Java Virtual Machine Launcher
---------------------------
A Java Exception has occurred.

**Comment by chaze117** [comment]
> 
> 
> Hi. I get errors when I try to run AutoDrive Course Editor
> ## Java Virtual Machine Launcher
> 
> Error: A JNI error has occurred, please check your installation and try again
> ## Java Virtual Machine Launcher
> 
> A Java Exception has occurred.

Download [JavaSE](https://www.oracle.com/java/technologies/javase-downloads.html)

**Comment by Iwan1803** [comment]
@ploughedfieldman123 
check your route as this is maybe causing this error.

**Comment by ploughedfieldman123** [comment]
> @ploughedfieldman123
> check your route as this is maybe causing this error.

Yes It seems to be a link from a blue line to green line as its working again now
