### ISSUE TITLE
Kurspunkte

### ISSUE THREAD

**Issue by marihe70** [Stephan-S/FS19_AutoDrive#116]
Hallo,

dein Mod ist spitze, danke dafür. Ich spiele auf der Porta Westfalica mit der neusten Version von AD. Da sind jetzt schon etliche Kurspunkte zustande gekommen. Deinen Tipp mit der Eingabe des KP wie du es unter der Nr. #45 erklärt hast habe ich probiert. Leider friert dann jedesmal das komplette Spiel ein, sodass ich es nur mittels Taskmanager beenden kann. Gibt es vielleicht die Möglichkeit so eine Art Aufklappliste zu integrieren, wo man z.B. auf einen kleinen Pfeil neben dem Zielnamen klickt und sich eine Liste öffnet aus der man sich das Ziel auswählt? Das würde das klicken der Maus erheblich reduzieren.

Aber nochmals vielen Dank für den coolen Mod.

**Comment by Stephan-S** [comment]
Hey,

könntest du wenn du Gelegenheit hast, die Eingabe wie in #45 nochmal probieren und mir dann das Logfile schicken? Dann könnte ich den Fehler zumindest beheben. Ich nehme an du spielst mit einer aktuellen Version, da du hier im Github unterwegs bist :-) In der ersten Release Version war diesbezüglich noch der ein oder andere Bug enthalten.

Spielst du nur mit Maus und Tastatur, oder auch mit einem Gamepad?
Auf dem Joystick (+Lenkrad) bzw. dem Gamepad habe ich mir extra Tasten belegt um die Ziele vor und zurück zu schalten, so dass ich die Maus eigentlich nie benutze um AutoDrive zu bedienen, außer beim Aufzeichnen der Kurse (und selbst das würde theoretisch mit belegten Buttons funktionieren). Nur falls du das noch nicht probiert hast.

Viele Grüße,
Stephan

**Comment by marihe70** [comment]
Hallo,

ich spiele mit Maus, Tastatur und Gamepad. Ich habe die Ziele auf eine Taste des Gamepad gelegt, das funktioniert. Nach einem Neustart des Spiels hat komischerweise auch die Zieleingabe ohne Absturz funktioniert. Danke für deinen Hinweis mit der Tastenbelegung. Aber m.E. ist die Zieleingabe die Komfortabelste Lösung, da bei einer 4 Fach Map es ein ewiges geklicke oder gedrücke ist.

Danke noch mal.

Viele Grüße
Mario

**Comment by Stephan-S** [comment]
Aufklappliste wurde als Ziel aufgenommen und wird fortan im Issue #149 bearbeitet
