### ISSUE TITLE
Frage zur abfahrer mechanik

### ISSUE THREAD

**Issue by nimanox** [Stephan-S/FS19_AutoDrive#1164]
hallo ist es möglich den abfahrer von drescher genaus so wie courseplay neben dem drescher herfahren zu lassen und währendesen abzutanken?

und so als feature anfrage was toll wäre vllt das man bestimmte streckn nur für bestimmte fahrzeuge frei geben kann zb den weg über manche trigger für lkws sperren könnte  oder andere wege nur für lkws frei geben. oder traktor

**Comment by Bobster82** [comment]
This should be possible, as autodrive also works with a forage harvester. But i think its a lot of scripts to write to make it work.

For the 2nd question I would like to see different line colors:

Green line: Every vehicle can use this line
Red Line: Vehicles "prefer" this line if set in options that it uses it when available on the route, else  u cant use that line

Something like that, so when drawing a red line in the center of a road, a vehicle with a big seeder and setted to use the red line if available on route, can only use that, cuz its using the whole road.

U can expand it with more color lines if needed. Every vehicle uses the normal green and purple lines, but uses different if available for them... u can make shortcuts that only trucks can take or whatever ;)

**Comment by Iwan1803** [comment]
Der Abfahrer eines Dreschers fährt doch daneben. Wo sollte er auch sonst fahren, da das Rohr auf der Seite ist?
Du meinst wohl eher den Häcksler, wobei der Abfahrer nur daneben fährt, wenn er denn da auch Platz hat.

Zu dem Feature bzgl. wer darf wo fahren:
in AD kann man generall Fahrzeugen schon eingestellen, das sie Zielpunkte vermeiden bzw. umfahren sollen. 
Von der Idee, das bestimmte Fahrzeuge auf bestimmten Wege fahren dürfen, halte ich persönlich nichts, weil es das ganze nur unnötig kompliziert macht und es dann wieder haufenweise Anfragen geben wird, warum ein LKW nicht ans Silo rankommt oder ein Drescher aufs Feld fahren kann.

**Comment by Bobster82** [comment]
I thought we would comment more in english?

**Comment by Iwan1803** [comment]
The title should be in english 😉

**Comment by nimanox** [comment]
nein ich meine den drescher ... einmal kommt der erst wen der voll ist als 95% bezieungsweise will dann erst abholen wenn der drescher steht.  ab und an habe ich das die neben dme drescher fahren und abtanken was gut ist allerdings dauerhaft neben dem fahren und nicht zum nächsten fahren wen der aktuelle leer ist.

und was die fahrrichtungen angeht ist es besser, da man sich einiges an babysitten sparen kann, genauere strecken einfahren kann  und achten muss das da alle lang kommen könnten. beispiel habe ich ein weg für meine kuhställe als futter wegen der recht eingefahren ist zwischen den gebauden aber somit am effecktivsten ist leider ist der weg auch für andere fahrzeuge effecktiv und somit will jedes mal mein 40t lkw auch ab und an da lang obwohl der da nicht wirklich durchpasst. darum finde ich das man manche strecken nur für bestimmte fahrzeuge zulassen können sollte.

and for my english friend in english but only with the google translate ^^

no, I mean the thresher ... once the person who is full is 95% or only wants to pick up when the thresher is standing. from time to time I drive and unload the thresher next to the thresher, which is good, however, permanently next to the drive and not to the next drive if the current one is empty.

And as far as the driving directions are concerned, it is better because you can save some babysitting, drive in more precise distances and have to be careful that everyone could get there. for example, i have a way for my cowshed as feed because of the fact that it is well run in between the buildings but therefore the most effective is unfortunately the way is also effective for other vehicles and so my 40t truck always wants to go from time to time even though it is not there really fits. that's why i think that some routes should only be allowed for certain vehicles.

**Comment by Stephan-S** [comment]
Hallo, da wir gerade die neue restrukturierte Version von AutoDrive released haben, können wir leider keine Bugs und Issues die sich noch auf die alte Codebasis beziehen mehr bearbeiten.
Wenn das Problem bzw. dein Anliegen in der atkuellen Version weiterhin besteht, mache doch bitte ein neues Issue mit allen benötigten Informationen auf.
Oder melde dich bei kleineren Themen und Fragen auch gerne direkt im Discord:
https://discord.gg/sUQtKhB

Vielen Dank für dein Verständniss und ich hoffe du hast weiterhin Spaß am AutoDrive Mod :-)

Und hier noch ein Link zur aktuellen Version:
https://github.com/Stephan-S/FS19_AutoDrive/releases/tag/1.1.0.0
