### ISSUE TITLE
strange lines 

### ISSUE THREAD

**Issue by ploughedfieldman123** [Stephan-S/FS19_AutoDrive#1166]
**AutoDrive Version:** 1.0.7.2
**Release or Custom Zip:** Release  
**Map (If applicable):** All  
**Vehicle / Type (If applicable):**   
**Multiplayer or Singleplayer:** Singleplayer  

**Describe the bug**  

**If applicable - Steps to reproduce the behavior**  

**Screenshots**  

has anyone 
experienced  this happening in game  strange lines appears nothing to do with lines you are making in the game   if so what can be done about them      

<a href="https://ibb.co/X3Sbbqz"><img src="https://i.ibb.co/pRJxxS3/2020-03-14-151128.jpg" alt="2020-03-14-151128" border="0"></a>

In the editor  they are coming from field 14 and the field I am on is field 13  this is on GreenWhich Valley map  

<a href="https://ibb.co/k8FxcX5"><img src="https://i.ibb.co/d2yrKDj/2020-03-14-153155.jpg" alt="2020-03-14-153155" border="0"></a>

**Comment by Bobster82** [comment]
Tried the ingame editor?? easy to add and remove points/lines ;)

**Comment by ploughedfieldman123** [comment]
> Tried the ingame editor?? easy to add and remove points/lines ;)

Yes i know what you mean, and yes its fixed now. but why did it select a node from field 14, when I am on field 13 on GreenWhich Valley map  and dragged it to that field as I never selected it

**Comment by Bobster82** [comment]
Maybe the node was still selected when u edited at field14... maybe the bug is that the node selection is remembered when u open the editor again and then u select a new node and then it makes the connection?
I know it is a small issue that can be undone easily :P

**Comment by ploughedfieldman123** [comment]
> Maybe the node was still selected when u edited at field14... maybe the bug is that the node selection is remembered when u open the editor again and then u select a new node and then it makes the connection?
> I know it is a small issue that can be undone easily :P

No I wasn't even in field 14 I was in field 13.  But I was deleting some lines, and moving with yellow line to select next nodes etc. so maybe the red line went right over to field 14. But is there no way of making the red line shorter. as I think thats what caused problem. as I was  selecting nodes to delete.  and obvious it landed on a node on F14.   its easy to fix anyway. but if the red line can be made shorter it would be great
