### ISSUE TITLE
Question: Pink button in newest version

### ISSUE THREAD

**Issue by gec100** [Stephan-S/FS19_AutoDrive#1170]
Hi all.

This is my first attempt in AD and while watching tutorial videos i see the option to make dual way recording with a second click on the rec button.
How is this done in the new version of the AD?
thx

**Comment by Stephan-S** [comment]
https://github.com/Stephan-S/FS19_AutoDrive/wiki/4-AutoDrive-HUD#41-hud-buttons

**Comment by gec100** [comment]
Thx for the answer. I did read that before I asked the question.
Maybe i'm little thick but I really have no idea what that chapter 5.2 say... Record in one direction an than what? If the route is long, a can not reach point A from point B

**Comment by Stephan-S** [comment]
alright. If there are any questions left, the Wiki can't answer, feel free to jump into our discord server and ask general questions there. The github is for bugs and feature requests :-)
