### ISSUE TITLE
Specification of different maximum line speeds for a route trip:

### ISSUE THREAD

**Issue by roland45** [Stephan-S/FS19_AutoDrive#1172]
Die Eigenschaft, daß Fahrzeuge in gewissen Streckenabschnitten nur eine gewünschte max. Geschw. Fahren wäre ein Wunsch für AD. 
Dabei darf jedoch die „config“ Datei NICHT größer werden.
 
Vorschlag: Einführung einer 2.Datei  „xyz“ in der NUR jene Wegpunkte gespeichert werden, die eine neue max. Geschwindigkeit vorgeben. (Wegkoordinate + max.Geschw.)

Bei der Abfahrt einer Route wird ja kontinuierlich der nächste Wegpunkt berechnet. Dabei soll in der neuen Datei überprüft werden ob dieser aktuelle Wegpunkt (mit einer max.Geschw.)  in der „xyz“ gespeichert ist, wenn ja wird dem Fahrzeug die neue max.Geschwindigkeit vorgegeben. Es sind ja nur 2 Wegpunkte in der Datei „xyz“. pro definierter Strecke.

Die Eingabe solcher max.Geschw. Wegpunkte kann genauso erfolgen, wie der Zielpunktname.

Routen-Wegpunkt anfahren der eine neue max. Geschw. bekommen soll, Anwahl und max. Geschw. eintragen, (wird in „xyz“ gespeichert). Wenn gewünscht, weiteren Routen Wegpunkt anfahren und genauso verfahren. Dieser Punkt ist Ende der Vorgabe bzw. neue Vorgabe, usw. Eine Streck ist somit mit maximal  2 gespeicherten Daten  in der „xyz“ definiert.

Die in AD vorhandene dynamische Geschwindigkeitsvorgabe (funktioniert super) bleibt vom Vorschlag der „max. Stecken-Geschw.“ unberührt und ist in ihrer Funktion immer übergeordnet.

Da ich den wahren Ablauf der AD Berechnung nicht kenne, kann mein Vorschlag auch völliger Unsinn sein, dann bitte Sorry.

**Comment by Iwan1803** [comment]
Es wird nicht der nächste Wegpunkt berechnet, sondern direkt die gesamte Route inkl. aller Wegpunkte zu einem Zielpunkt. Dank dem Live-Modus kannst du sogar Streckenpunkte löschen, welche ein Fahrzeug gerade nutzt, ohne das etwas passiert.

Es ist übrigens egal, ob man die Info nun in 1 oder 2 Dateien speichert, wobei bei 2 Dateien zumindest die Anzahl an Wegpunkten verdoppelt werden würde.

Sind dir die Fahrzeuge zu schnell oder zu langsam oder welchen Sinn macht es, Geschwindigkeitsvorgaben zu hinterlegen? In meinen Augen würde es mehr Sinn machen, wenn Giants verschiedene Straßentypen integrieren würde und dadurch die max. Geschwindigkeit festgelegt werden würde.

**Comment by roland45** [comment]
OK.  Wenn gleich die gesamte Route berechnet wird, ist mein Vorschlag so nicht machbar-
Eine Verdoppelung der Daten ist keinesfalls wünschenswert, ich dachte nur in der 2. Datei einzelne relevante Wegpunkte zu  speicher.
Die Geschwindigkeit der Fahrzeuge mit der dynamischen Fahrweise ist super und funktioniert auch im AD bei mir bestens.
Wo wäre es sinnvoll: . Nur auf geraden Strecken wo max. Geschwindigkeit gefahren wird:  vor einer Radarbox, (gabs  im LS17, bei LS19 glaube ich noch nicht) , im Stadtgebiet (unschön wenn mit 80 durchgefahren wird), bei extremen Stellen auf einer MAP  zB. Brücken Abfahrrampen (Tankwagen wird zum Flieger)
Warum fahr ich so schnell?  Bei 4 fach MAPs  als Singleplayer  und mit SeasonMod ist Zeit ein wichtiger Faktor.
Mehrere Straßentypen: Würde mir in oben geschilderten Fällen vermutlich nicht helfen, da meine Abfahrer auf Hauptstraßen mit max. Geschwindigkeit fahren sollen. 
Ansonsten sicher eine schöne Erweiterung, schränkt aber die Verwendung des gesamten Straßennetzes etwas ein. Kannn dann ein LKW Abfahrer auch auf Feldstraßen zu seinem Beladeplatz fahren? Zu wenig Information um dazu eine Meinung zu haben.

**Comment by roland45** [comment]
Sorry, wenn ich nochmals auf meinen Vorschlag zurück komme. 
Ok, die Route wird gesamt berechnet. Wenn nun das Fahrzeug die schon berechnete Route befährt, ist (so nehme ich an) dem Programm der vom Fahrzeug aktuell befahrene Wegpunkt bekannt (oder?). In diesem Moment wird nun abgeglichen ob dieser Wegpunkt  in Datei 2 definiert wurde um die Aktion einzuleiten.
Die 2.Datei soll keinesfalls alle Wegpunkte enthalten (Verdoppelung der Datenmenge) sondern nur die Definition des aktuell angefahrenen Wegpunktes., der eine Vorgabe ändern soll.

Möglicherweise ist aber programmtechnisch der aktuelle Vergleich der Dateien im aktuellen angefahrenen Wegpunkt  für einen kontinuierlichen  Ablauf zu zeitaufwendig. Dann ist es zu vergessen. Besten Dank für Deine  Rüchantworten.

**Comment by Stephan-S** [comment]
@roland45 Programmtechnisch wäre es beim Fahren vermutlich nicht allzu schwer zu verfolgen. 
Aber ich sehe es nicht als umsetzbar an. Man müsste ja quasi Verkehrszeichen aufstellen, die dann ja auch irgendwo wieder aufgelöst werden müssten. Werden Sie automatisch bei jeder Abzweigung aufgelöst oder gilt auf beiden Seiten dann das Limit?

Das ganze Konzept ist ein interessanter Ansatz, sagt mir bis jetzt aber leider gar nicht zu. Tut mir Leid. Zu wenig Anforderung/Nutzen für zuviel Aufwand beim Erstellen und vor allem auch zusätzlicher CPU Last beim Berechnen der schnellsten Strecke und dem befahren eben dieser.

**Comment by roland45** [comment]
OK, alles klar, war nur so eine Idee von mir.

**Comment by mrPassion78** [comment]
i would love this idea to.. like in CP, it takes over the driven speed in recording..
that would be great to have in AD to, so that on the Kandalin map in singleplayer, you dont get that many fines for speeding with 53 in a 30kmh zone. 
and that way, you can have a tractor drive slower on very bumpy dirt roads, so it looks more realistic. 

but regardless of this all, thnx a million for the awesome AD mod..

**Comment by roland45** [comment]
Geschwindigkeit wie beim Einfahren ist aus meiner Sicht nicht zielführend, da die Datei für jeden Wegpunkt auch eine Geschwindigkeit abspeichern müßte. Die Config wird viel zu groß.

Stephan meinte Verkehrszeichen.  Nein, mein Vorschlag betrifft die Eingabe direkt am Wegpunkt, der die Maximalgeschwindigkeit ändern soll. Vorgang wie Eingabe Zielpunkt oder Parkposition. (Wegpunkt ist ausgewählt, Button drücken, in einem Eingabefeld neue Maximalgeschw. Eingeben, abschicken).
Es gibt jetz auch im LS19 bereits mehrere Maps, die Radarboxen eingebaut haben. (Strafe über 300 Euro). Kurz vor Radarbox den Wegpunkt mit neuer max. Geschw. definieren, nach der Radarbox  mit einen Wegpunkt mit reduzierter max. Geschw. diese wieder aufheben bzw. neue max. Geschw. eingeben. Das würde in der 2.Datei „xyz“ nur 2 Datensätze ergeben.  Natürlich sind mehrere solche Vorgaben möglich.
Bei Ortschaften kann man auf der Einfahrtsstecke mit einer Wegpunktdefinition   auf zb: 50 kmh reduzieren, bei den Ausfahrtsstrecken mit einer Wegpunktdefinition   wieder max. Geschw. zb. 80 kmh freigeben. 
OK, damit wollte ich nur noch meinen Grundgedanken  präzisieren.

**Comment by Opa-Andre** [comment]
Wie wäre es denn mit dieser Idee:
Man nutzt einen oder zwei reservierte "Spezialnamen" für einen Zielpunkt - z. Bsp. "Begin_SpeedLimit" und "End_SpeedLimit". Diese erscheinen in einer eigenen "Spezial" Kategorie und werden  im Gegensatz zu normalen Zielpunkten nicht mit für das "Umfahren / Umweg" ausgewertet. Anstelle dessen stellt man eine globale "SpeedLimit" Geschwindigkeit im AD Voreinstellungs-GUI ein. Fährt nun ein Fahrzeug über einen "Begin_SpeeLimit" Punkt wird die Geschwindigkeit auf den Limitwert heruntergesetzt. Bei Erreichen eines "End_SpeedLimit" Punktes, wird die ursprüngliche Einstellung des Fahrzeuges wieder herangezogen. Fahrzeuge, welche definitionsmäßig langsamer sind als das angegebene Limit, behalten ihre Einstellung.

Alternativ könnte man auch nur einen "SpeedLimit" Punkt definieren, ab welchem die in der GUI unter "Speedlimit max:" definierte Maximalgeschwindigkeit für die nächsten "x" Wegpunkte gilt und anschließend automatisch wieder aufgehoben wird.

Beispiel: Lange gerade Straße mit Bahnübergang: Ein paar Wegpunkte vor dem Bahnübergang setzt man den "Speedlimit" Wegpunkt. Fahrzeuge werden automatisch (obwohl keine Kurve etc), auf die globale Speedlimit Begrenzung herabgebremst. Nach Passieren des Bahnübergangs erfolgt die Aufhebung der Begrenzung - entweder durch einen "End_SpeedLimit" Zielpunkt, oder automatisch nachdem auf der Strecke z. Bsp. 5 Streckenpunkte nach diesem Speedlimit Punkt durchfahren wurden.

**Comment by roland45** [comment]
Wie ich sehe bist Du auch der Meinung, daß eine Reduzierung der Max. Geschw., ausgelöst durch einen speziell definierten Wegpunkt sinnvoll wäre. Wie die Definierung solcher Wegpunkte erfolgt sind sicher mehrere Möglichkeiten gegeben.  Letztendlich entscheidet die geringste zusätzliche Datenbelastung bzw. notwendige Rechenzeit. 
Beispiele für die Sinnhaftigkeit so einer Geschwindigkeitsreduzierung auf geraden Strecken haben sich hier bereits ergeben: Radarboxen, Bahnschranken, Kreuzungen, Ortsdurchfahrten, Brückenabfahrten usw…
Kurzer Tip von mir: Ich gestalte derzeit die Fahrzeuglinie vor einer Radarbox als Zick,Zack Linie, wodurch die Fahrzeuggeschwindigkeit reduziert wird.

**Comment by Opa-Andre** [comment]
Hmmm @roland45 , wundert mich jetzt, warum du Dein Ticket, was ja ein Feature Request ist, schließt. Somit werden es die AD-Dev's ggf. nicht mehr weiter betrachten hinsichtlich möglicher Ansätze in der weiteren Entwicklung von AD.

**Comment by roland45** [comment]
Muß mir irrtümlich passiert sein.

**Comment by roland45** [comment]
Hab den falschen Button gedrückt. 
Möchte Gelegenheit nutzen allen Programmierern von AD und CP für diese Programmentwicklungen Hochachtung auszusprechen. Nur damit ist mit LS19 als Singleplayer die 4x Maps mit Produktionen voll auszuspielen.

**Comment by Iwan1803** [comment]
Genau wie Stephan sehe ich hier einen enorm hohen Zeitaufwand, um so etwas zu programmieren und auch nur halbwegs Idiotensicher zu machen. Wenn das nicht geht, würden wir mit Anfragen gerade zu überschüttet werden, z.Bsp. warum XY mal wieder nur 50km/h fährt.
Es würde das ganze nur noch (unnötig) komplizierter machen als es für die meisten eh schon ist.

Besser würde ich es finden, wenn Giants hier tätig werden würde (vielleicht in LS21?). Sie könnten z.Bsp. verschiedene Straßentypen für unterschiedliche Geschwindigkeiten implementieren oder halt entsprechende Schilder, welche dann aber abfragbar sein müssten.

**Comment by roland45** [comment]
Schilder wären eine Lösung.  Wenn sich Modder fänden, die Schilder mit „Funktion“ für AD erstellen würden, so wie zB. Ampeln die den Verkehr anhalten, wäre super. Leider bin ich so einer nicht.
