### ISSUE TITLE
Newest version editor launching error

### ISSUE THREAD

**Issue by Pscx1** [Stephan-S/FS19_AutoDrive#1173]
Hello, 
I have error when trying to launch newest editor version
"Error:  A JNI error has occured, please check your installation and try again"
"Java exception has occured"

I have newest java updated today, also updated editor cuz old was not able to save edited courses

**Comment by Kuunlan01** [comment]
> Hello,
> I have error when trying to launch newest editor version
> "Error: A JNI error has occured, please check your installation and try again"
> "Java exception has occured"
> 
> I have newest java updated today, also updated editor cuz old was not able to save edited courses

go download this version:
https://www.oracle.com/java/technologies/javase-jdk13-downloads.html

**Comment by Pscx1** [comment]
Thanks, now it works perfectly :)
