### ISSUE TITLE
Kann man Autodrive bei Kartoffelernte einsetzten?

### ISSUE THREAD

**Issue by Michael170978** [Stephan-S/FS19_AutoDrive#1175]
Frage: 

Mich interresiert ob man Autodrive bei der Kartoffelernte einsetzen kann?

Wenn ja wie müsste ich Autodrive einstellen damit der Trecker neben der Kartoffelmaschine mitfährt.
Mir geht es jetzt nicht um den große Kartoffelvollernter. Mir geht es haupsächlich um die Erntenmaschine, die der Trecker zieht.

**Comment by markussinner** [comment]
Hallo Michael. Ich habe das schon gemacht. Man muss nur höllisch aufpassen, dass die Anhänger nicht zu hoch sind, weil man sonst an der Überlade-Konstruktion des Erntes hängen bleibt.

**Comment by Michael170978** [comment]
Hi Markussinner. Vielen Dank für die Info.Die Anhänger wären nicht das Problem. Ich hab das vor langer Zeit mit Courseplay probiert und da war es so, dass das Spiel abgestürzt ist. Laut Modderteam vom Courseplay geht das immer noch nicht. Deshalb möchte ich mit AD probieren, weil Kartoffel ernten schon ziemlich lange dauert. Da würde ich gerne den Helfer einsetzten wollen.
Wenn wir schon bei dem Thema sind. Hast du nur mit AD oder mit AD & CP gearbeitet?

**Comment by markussinner** [comment]
Hi

Sorry, hab ich nicht erwähnt. Ich hab CP und AD eingesetzt. Bin aktuell auf Felsbrunn auch wieder an einem Auftrag dran, kann dir dann noch mal bestätigen, ob es geht.

**Comment by Michael170978** [comment]
Da ich mit Seasons Mod spiele wird es bei mir ebenfalls dauern. Ich hab AD & CP bei Feldhäcksler eingesetzt. Und ich muss dir sagen, dass es recht fummelige Arbeit ist. Wider rum ohne AD geht es auch nicht , weil man schon will, dass der Schlepper die Ernte zum Silo bringt. Und CP alleine kann die Aufgabe nicht erledigen. Eigentlich schon aber du muss zwei Kurse miteinander verbinden und das ist recht zeitaufwendig. Da läuft es bei Mähdrescher viel besser. Ich finde, dass AD bessere Kollisionswarnsystem als CP hat. Deshalb CP Kurs für Mähdrescher einstellen und AD für die Schlepper benutzen. Es macht richtig Spaß beim Zuschauen und man hat Zeit für andere Dinge.

**Comment by markussinner** [comment]
Also, wie ich in Discord schon erwähnt hatte, hattest Du recht. 
Kartoffel-Ernte mit einem Ernte-Anhänger funktioniert nicht. Weder Standard, AI oder CP Helfer triggern das Abladen korrekt. Die AD Fahrer reagieren nicht auf den Ruf. Die Kartoffel-Ernte war dadurch ziemlich anstrengend :-)

Ich bin mir fast sicher, dass es mit den Erntemaschinen funktioniert. Konnte ich nicht ausprobieren, weil ich mir keine leisten kann ;-)

**Comment by Michael170978** [comment]
Ich hab deinen Kommentar auf Discord schon gelesen. Aber trotzdem danke nochmal für deine Info.
Aber wie sagt man so schön. Die Not macht erfinderisch. Ich teste gerade AiVehicle Extension. Dieser Assistent scheint echt der Hammer zu sein. Hmm....Ai & AD? Höre ich da etwa die Hochzeitsglocken bimmeln?

**Comment by Mike1977** [comment]
Ich bin mir ziemlich sicher das das vor ein paar Monaten noch funktioniert hat. Ich habe selbst keine Kartoffel oder Rüben Maschinen, aber ich mache immer die Aufträge und leihe die Maschinen dazu aus. Bei den Rübenerntern fährt Autodrive immer direkt hinten an die Maschiene ran und bleibt dort stecken. Bei Kartoffelerntern passiert garnichts. Da reagiert AD nicht auf den ruf der Erntemaschine...
Aber wie gesagt... ich weis das das mal funktioniert hat, wenn auch nicht perfekt.

**Comment by Iwan1803** [comment]
Bitte 1.1.0.5-RC3 ausprobieren. Sollte das Problem dann noch bestehen, einfach ein neues Issue aufmachen.
