### ISSUE TITLE
Vehicles drives max 57km/h

### ISSUE THREAD

**Issue by Rumspringa90** [Stephan-S/FS19_AutoDrive#1176]
AutoDrive Version: 1.1.0.0
Release or selbsterstelltes zip: Release
Karte (falls relevant): Alle
Fahrzeug(art) (falls relevant):

**Beschreibe den Bug**
Fahrzeuge fahren maximal 57km/h obwohl eine höhere max Geschwindigkeit eingestellt ist.

**Comment by Iwan1803** [comment]
Kann ich leider bestätigen.

**Comment by Stephan-S** [comment]
Fixed :-)
