### ISSUE TITLE
if silo empty "wait" does not work

### ISSUE THREAD

**Issue by Rumspringa90** [Stephan-S/FS19_AutoDrive#1177]
AutoDrive Version: 1.1.0.0
Release or selbsterstelltes zip: Release
Karte (falls relevant): Alle
Fahrzeug(art) (falls relevant):

**Beschreibe den Bug**
Beim Modus Laden und Entladen wartet er nicht wenn das Silo leer ist, sondern fährt dann los obwohl der Anhänger noch nicht voll ist. In den Einstellungen ist "Warten" eingestellt.

**Comment by Stephan-S** [comment]
Yeah for now it is interpreted like if silo was completely empty. So if he loaded something, it wasn't empty :D
