### ISSUE TITLE
Error: Running LUA method 'update'. (ExternalInterface)

### ISSUE THREAD

**Issue by Rumspringa90** [Stephan-S/FS19_AutoDrive#1178]
AutoDrive Version: 1.1.0.0
Release or selbsterstelltes zip: Release
Karte (falls relevant): Alle
Fahrzeug(art) (falls relevant):

**Beschreibe den Bug**
Fehlermeldung in der Log:
2020-03-19 16:23 Error: Running LUA method 'update'.
2020-03-19 16:23 D:/Documents/My Games/FarmingSimulator2019/mods/FS19_AutoDrive/scripts/ExternalInterface.lua:140: attempt to compare nil with number

Bin leider nicht ganz sicher vorher der kam. Aber vermute im zusammenspiel mit Courseplay der AutoDrive zum nachfüllen der Düngerspritze benutzen wollte.

**Comment by jala15** [comment]
Courseplay uses the old "self.vehicle.ad.mapMarkerSelected" which is not used anymore in the refactored AutoDrive.
A fix is needed either on the Courseplay side (no backwards compatibility) or on the AutoDrive side (no problems with older Courseplay versions or updated Courseplay with outdated Autodrive)


BTW, great to see this huge refactory, thanks for your effort

PS: Line 142 in external interface not needed anymore
https://github.com/Stephan-S/FS19_AutoDrive/blob/1078f4d0555679eacafa46380e5d337e5a55d31d/FS19_AutoDrive/scripts/ExternalInterface.lua#L142

**Comment by Stephan-S** [comment]
Fixed :-)

**Comment by Stephan-S** [comment]
Oh and @jala15 
Maybe this refactor makes you wanna contribute even more since it's now so much easier to change something :D
