### ISSUE TITLE
Move target to folder not working

### ISSUE THREAD

**Issue by iljarogoff** [Stephan-S/FS19_AutoDrive#1179]
AutoDrive Version: 1.1.0.0.
Release or selbsterstelltes zip: Release
Karte (falls relevant): Alle
Fahrzeug(art) (falls relevant):

**Beschreibe den Bug**
Kann Ziele nicht mehr in einen anderen Ordner verschieben. Die Aktion wird nicht gespeichert. Im ersten Moment sieht es aus als wäre es geglückt, aber wenn man die Liste nochmal anschaut ist das Ziel wieder an der alten Position

**Falls anwendbar - Schritte mit denen ich den Bug nachstellen kann**

**Screenshots**
Falls relevant, bitte Screenshots beifügen

**Comment by AngeloMerte** [comment]
Kann ich bestätigen, habe dasselbe Problem.

**Comment by Stephan-S** [comment]
Fixed :-)
