### ISSUE TITLE
Abtanken bei Couseplay Helfer

### ISSUE THREAD

**Issue by klauskleber14** [Stephan-S/FS19_AutoDrive#118]
Hallo,

ich habe vor ein paar Tagen bei Courseplay nachgefragt ob man Ihren Helfermodus so abändern könnte das der Drescher bei erreichen seines Füllstandstandes das Abtankrohr automatisch ausfährt, sodass man den Abfahrermodus von Autodrive nutzen kann.

Einer der Entwickler schrieb, dass Sie sich dies bezüglich mal besprechen müssen und schauen ob es dort eine Lösung gibt.
Dabei wurde auch angeboten, eine gemeinsame Lösung zusammen mit dem/den Autodrive Entwickler/n zu erarbeiten sofern dort interesse besteht.
 
Vielleicht bist du/ seid Ihr ja daran interessiert eure Mods aufeinader Abzustimmen wovon alle profitieren würden.

Viele Grüße

**Comment by Stephan-S** [comment]
Hallo @klauskleber14 

ich habe mich deinem Issue auf der CP Github Seite mal angeschlossen. Das Thema ist also grundsätzlich mal in Bearbeitung :-)

**Comment by pvaiko** [comment]
https://github.com/Courseplay/courseplay/issues/3792

**Comment by klauskleber14** [comment]
Hi @Stephan-S 

Vielen Dank schonmal das ist schön zu hören :)

**Comment by haamic** [comment]
mir ist in der aktuellen Version aufgefallen, das der Abfahrer nach dem Drescher abtanken, nur noch ganz wenig rückwärts fährt, war schon mal besser gelöst. 
So kommt es wieder zu starken Remplern des Drescher, beim wieder einlenken zur Frucht.
Bitte wieder korrigieren, danke
