### ISSUE TITLE
Pickup&Deliver: not switching targets

### ISSUE THREAD

**Issue by Iwan1803** [Stephan-S/FS19_AutoDrive#1180]
AutoDrive Version: 1.1.0.0
Release or selbsterstelltes zip: Release
Karte (falls relevant): NFM 4x
Fahrzeug(art) (falls relevant): Trecker mit Wassertank

**Beschreibe den Bug**
Bei Abholen&Abliefern werden die Ziele in einem Ordner nicht gewechselt. Es wird wiederholt das eingestellte Ziel angefahren.

**Falls anwendbar - Schritte mit denen ich den Bug nachstellen kann**

**Screenshots**

**Comment by Stephan-S** [comment]
Fixed :-)
