### ISSUE TITLE
neue Kurvengeschwindigkeitsfunktion

### ISSUE THREAD

**Issue by Michael170978** [Stephan-S/FS19_AutoDrive#1181]
Hi.

Könnt ihr mir bitte genauer erklären wie die Kurvengeschwindigkeitsfunktion  geht?

Was bedeutet 50% bzw 200%? Ich merke leider keinen Unterschied.

**Comment by Stephan-S** [comment]
Da hat noch ein anderer Wert mit rein gespielt der das ganze wieder ausgebremst hat

**Comment by Michael170978** [comment]
Also durch den Hotfix ist die Kurvengeschwindigkeit um einiges besser geworden. Aber wenn ich  Kurvengeschwindigkeit auf 50% einstelle fährt egal welches Fahrzeug auf geraden Strecken mit 50% von seiner Endgeschwindigkeit. 

Ich denke ihr wolltet so machen, dass die Fahrzeuge bei 50% mit halber Geschwindigkeit in der Kurve fahren und nicht nonstop.

Widerrum bei 200% fahren die Fahrzeuge nonstop doppelt so schnell als die eingestellte Endgeschwindigkeit

**Comment by Stephan-S** [comment]
Bitte auf 1.0.7.2 bleiben oder den neuesten Release-Candidate 1.1.0.3-1 nutzen :-)
