### ISSUE TITLE
Error: Running LUA method 'onSaveStartComplete'

### ISSUE THREAD

**Issue by crimso** [Stephan-S/FS19_AutoDrive#1182]
**AutoDrive Version:** 1.1.0.0.   
**Release or Custom Zip:** Custom ZIp
**Map (If applicable):** Ellerbach

**Multiplayer or Singleplayer:** Singleplayer  

**Describe the bug**  
If I want to save the game I get this error. Without AutoDrive I can save the game.

In the LOG file I have this error after I want to save the game:

Error: Running LUA method 'onSaveStartComplete'.
2020-03-19 20:47 E:/ModsFS19/mods/FS19_AutoDrive/scripts/Modules/StateModule.lua:103: attempt to index field 'firstMarker' (a nil value)

After this error I can only exit from the game with Alt+F4 or I need to end the process.

Thank you

**Comment by Stephan-S** [comment]
Fixed. Thank you :-)
