### ISSUE TITLE
Java Version falsch

### ISSUE THREAD

**Issue by Denkra** [Stephan-S/FS19_AutoDrive#1183]
Habe das Problem, das er mir immer einen Java Fehler anzeigt wenn ich den Course Editor öffnen will. Habe es auf 3 verschiedenen PC probiert. Gibt es da eine bestimmte Version die installiert sein muss?

**Comment by raupach** [comment]
Ja, es muß Java Version 11 sein.

**Comment by raupach** [comment]
Naja, es muß mindestens 11 sein....

**Comment by Denkra** [comment]
Ah okay perfekt. Wäre vielleicht dann nicht schlecht wenn man es in die Doku mit rein schreiben würde sofern ich es nicht überlesen habe

**Comment by raupach** [comment]
Ja, auf jeden Fall. Beim externen Editor ändert sich im Moment allerdings recht viel....

**Comment by raupach** [comment]
Welche Doku eigentlich? Wo suchst du da nach Infos?

**Comment by Justice-Molton** [comment]
@raupach dachte genau das gleiche. Hast Du mittlerweile eine Antwort auf die Frage warum die 4x Config so groß ist bekommen?

**Comment by raupach** [comment]
Nee, die Sache verstehe ich im Momant noch gar nicht.

**Comment by Justice-Molton** [comment]
Die maps sind ja normal, 4x so groß wie normal und 16x so groß wie normal. Da würde ich denken das alleine durch diese Umstände die Configs größer werden

**Comment by raupach** [comment]
Ich bin ja totaler LS19 Anfänger und kenne eigentlich nur Felsbrunn. Wo bekommt man denn diese großen Maps?

**Comment by Justice-Molton** [comment]
Schau mal bei Forbidden Mods, oder LS modcompany. Wir spielen momentan auf der Kandelin. Die ist 4x. Eine 16fach wäre soweit ich weiß die Wild West oder so ähnlich

**Comment by Justice-Molton** [comment]
Hast Du discord? Dann können wir auch da schreiben.

**Comment by raupach** [comment]
Ah, habe sie schon gefunden. Bin auf Discord als "OliverR" unterwegs. Heute aber nicht mehr.
