### ISSUE TITLE
tresher unload problem

### ISSUE THREAD

**Issue by OliWit82** [Stephan-S/FS19_AutoDrive#1184]
Version: 1.1.0.0
Release or selbsterstelltes zip: Release
Karte (falls relevant): Multimap
Fahrzeug(art) (falls relevant):

**Beschreibe den Bug**
Wir haben das Problem das der Schlepper (Ablader) wenn er den Drescher abtankt unters Rohr fährt und dann rückwärts setzt. Ein komplettes Abtanken ist so nicht möglich. Der Drescher fährt 100m weiter dann kommt der Ablader wieder und alles passiert von neu. Und immer wieder bis der Ablader 100% voll ist und das Feld verlässt. 

**Falls anwendbar - Schritte mit denen ich den Bug nachstellen kann**

**Screenshots**
Falls relevant, bitte Screenshots beifügen

**Comment by Iwan1803** [comment]
Fährt der Drescher mit CoursePlay?

**Comment by OliWit82** [comment]
Ja der Drescher fährt mit CoursePlay. 
Haben weiter fahren und stehenbleiben beim Abtanken eingestellt und ausprobiert. Ergebnisse bei beiden gleich.

**Comment by Stephan-S** [comment]
Bitte auf 1.0.7.2 bleiben oder den neuesten Release-Candidate 1.1.0.3-1 nutzen :-)
