### ISSUE TITLE
 Automatic seed and fertilizer refills no longer work / Automatisches Saatgut und Dünger nachfüllen funktioniert nicht mehr

### ISSUE THREAD

**Issue by Fuzzy86** [Stephan-S/FS19_AutoDrive#1185]
AutoDrive Version: 1.1.0.1
Release or selbsterstelltes zip: Release
Karte (falls relevant): Alle
Fahrzeug(art) (falls relevant):

**Beschreibe den Bug**
Fahrzeug belädt nicht mehr automatisch das Saatgut oder Dünger wenn es leer wird. 
Habe es ohne Mods versucht jedoch das selbe Ergebnis. Mit der version 1.0.7.2 hat es noch funktioniert.

lg

**Comment by Stephan-S** [comment]
Bitte ein Log beifügen. Danke

**Comment by Fuzzy86** [comment]
[log V1.1.0.1.txt](https://github.com/Stephan-S/FS19_AutoDrive/files/4358225/log.V1.1.0.1.txt)
[log V1.0.7.2.txt](https://github.com/Stephan-S/FS19_AutoDrive/files/4358227/log.V1.0.7.2.txt)

Hab dir ne Log mit V1.0.7.2 und einmal mit V1.1.0.1 angehängt. Brauchst du Screenshots auch?

**Comment by Stephan-S** [comment]
Ja das Log ist ja sauber. Aber erzähl doch mal was genau das Problem ist.
Nutzt du CP und hast refille eingestellt?
Bleibt er stehen? Aktiviert er AD?
So sehe ich ja gar nicht was das Problem ist :-)

Habe gerade nochmal einen Test laufen lassen, der problemlos nachgefüllt hat, nachdem CP den Dünger leer hatte

**Comment by Fuzzy86** [comment]
Ja ich nutze CP und habe auch das refill eingestellt. Er fährt dann auch zur Ausgabe, bleibt jedoch dann stehen und bewegt sich nicht mehr. Es geht auch der Deckel nicht auf

Das sind die Screenshots von der funktionierenden Version 1.0.7.2
![fsScreen_2020_03_20_07_31_35](https://user-images.githubusercontent.com/53813734/77142787-80a76180-6a81-11ea-9b70-10ee263c6442.png)
![fsScreen_2020_03_20_07_33_18](https://user-images.githubusercontent.com/53813734/77142798-84d37f00-6a81-11ea-8fdc-94cc53f2f6ec.png)
![fsScreen_2020_03_20_07_33_39](https://user-images.githubusercontent.com/53813734/77142802-8735d900-6a81-11ea-95be-975a040df0cd.png)
![fsScreen_2020_03_20_07_33_58](https://user-images.githubusercontent.com/53813734/77142810-8ac96000-6a81-11ea-9fae-04d9abd424f4.png)

... und das die von der neuen V1.1.0.1 wo es nicht funktioniert
![fsScreen_2020_03_20_07_40_11](https://user-images.githubusercontent.com/53813734/77142859-b1879680-6a81-11ea-8ba7-4ad90be458c4.png)
![fsScreen_2020_03_20_07_40_38](https://user-images.githubusercontent.com/53813734/77142861-b4828700-6a81-11ea-82bf-302a94994e01.png)
![fsScreen_2020_03_20_07_41_44](https://user-images.githubusercontent.com/53813734/77142864-b8160e00-6a81-11ea-87e4-2496baf1bfaf.png)

**Comment by Stephan-S** [comment]
Alles klar. Was sind das genau für Gebäude bzw. Trigger? Sieht so aus als gäbe es damit Probleme. Er hält ja an und probiert zu laden aber die Trigger geben nichts raus :D

**Comment by Fuzzy86** [comment]
Das sind die Produktionen vom Fed von der NF Marsch. Habe aber bei meinem eigentlichen Spielstand ein Silo stehen wo nur Saatgut und Dünger drinnen ist und da hat es mit der 1.0.7.2 auch geklappt nur mit der neuen nicht

**Comment by Stephan-S** [comment]
Warte mal. Der erreicht ja seinen 'Dünger laden' Punkt bevor er im Trigger steht. Schick ihn zu Saatgut laden und achte darauf, dass die Zielpunkte immer soweit hinterm Trigger gesetzt sind, dass er diese vorm Ziel erreicht!

**Comment by Fuzzy86** [comment]
Hab ich ja. Es ist bei beiden das selbe Streckennetz. Das einzige was ich getauscht habe ist der Autodrive.zip

**Comment by RalfGorden** [comment]
hallo habe auch das Problem , bei der der V 1.0.7.2 konnte ich Saatgut und Dünger mit einmal aufladen ,jetzt bei der V 1.1.0.1 läd er Saatgut aber fährt beim Dünger durch ohne zu laden

**Comment by Stephan-S** [comment]
Der Unterschied ist, dass er nicht mehr im Radius des Triggers auflädt sondern nur auf dem Weg zu den Triggern. Also bevore er sein Ziel erreicht. Wenn ihr dieses wie beschrieben deutlich hinter die Trigger verschiebt (Ingame Editor sei dank, ja schnell gemacht) sollte alles wie gewohnt funktionieren

**Comment by Fuzzy86** [comment]
Leider Nein! Funktioniert trotzdem nicht
1. Fährt er auch beim Dünger durch wo er laden sollte 
2. Sind die Zielpunkte jetzt deutlich weiter hinter den Triggern

Er bleibt  beim Zielpunkt stehen und rührt sich nicht


![fsScreen_2020_03_20_08_37_02](https://user-images.githubusercontent.com/53813734/77144373-00cfc600-6a86-11ea-8923-e0af0a062d9c.png)

**Comment by Fuzzy86** [comment]
PS. Er öffnet auch nicht den Deckel

**Comment by Stephan-S** [comment]
Könntest du mir ein minimales Savegame fertig machen mit den Triggern und Fahrzeugen mit denen es nicht klappt? Also nur die Mods enthalten die wirklich nötig sind für den Test?
Danke für deine Mitarbeit :-)

**Comment by Fuzzy86** [comment]
Hab da nur Alle DLC drinnen und die NF Marsch mit seinen dazugehörigen Mods und natürlich CP (aktuelle Version) und AD. Kann dir die mods aber auch schicken wenn du mir sagst wie. 
Savegame kannst haben und ist Minimal weil ich es extra nur für das jetzt erstellt habe

Falls du Teamspeak hast könnten wir auch reden das wäre evtl. einfacher als hin und her zu schreiben

**Comment by Stephan-S** [comment]
Komm doch bei uns auf dem Discord vorbei :-) Da kannst du mir auch gerne das minimale Savegame schicken und dann kriegen wir das sicher schnell gelöst :-)

**Comment by Fuzzy86** [comment]
Ok. wie komme ich auf euren Discord

**Comment by Stephan-S** [comment]
Ist doch auf der Startseite verlinkt ;-)
https://github.com/Stephan-S/FS19_AutoDrive

**Comment by Fuzzy86** [comment]
Bin on

**Comment by Bobster82** [comment]
And again... I thought we would type english?? I see it a lot lately.... Its not a german game ;) And I also have a problem with the new version and auto refilling, but I really dont know what u guys are talking about :P So i cant really contribute....

**Comment by RalfGorden** [comment]
https://www.deepl.com/translator

**Comment by hathor1411** [comment]
Ich hab so ein ähnliches Phänomen.
Er fährt beim nachladen von Kalk ans Silo läd nach und weiß dann nicht weiter. 
Bildrate geht auf 6 FPS runter und nach 20 sec etwa, fährt er einfach geradeaus weiter.
Hab das Problem gestern nicht gehabt. 
Log ist sauber.

**Comment by Fuzzy86** [comment]
Moin moin! Habe soeben das Autodrive mit dem Hotfix (selbst gezipt) getestet. Er fährt jetzt zwar beladen und macht das auch, jedoch fährt er dann nicht über das AD Streckennetz zum Startpunkt sondern direkt. Sieht so aus als würde er zu früh an CP übergeben.

**Comment by Stephan-S** [comment]
Fixed
