### ISSUE TITLE
the tarpaulin on the trailer remains closed & unloader stays at the tresher if full

### ISSUE THREAD

**Issue by IcemanGSXR** [Stephan-S/FS19_AutoDrive#1186]
AutoDrive Version: 1.1.0.1
Release or selbsterstelltes zip: Release
Karte (falls relevant): Alle
Fahrzeug(art) (falls relevant):

In dieser Version bleibt der Abfahrer beim Drescher einfach stehen, obwohl Hänger zu 100% voll ist, und fährt nicht automatisch weiter. Drescher fährt als normaler Helfer, kein CP.

Folgende Methode funktioniert auch nicht mehr.
Drescher mit CP, Überladewagen als Abfahrer, Traktor mit 2 Hänger als Abholen und Abliefern zum Verkauf. (hat bis 1.0.7.2 einwandfrei funktioniert)
Überladewagen bleibt nach Abtanken einfach stehen (Abfahrmenge 95% erreicht)
Abholen und Abliefern lässt leider die Plane geschlossen, kein Überladen möglich.

**Comment by Stephan-S** [comment]
Fixed
