### ISSUE TITLE
CP communication issue

### ISSUE THREAD

**Issue by RedMonster-HUN** [Stephan-S/FS19_AutoDrive#1187]
**AutoDrive Version:** 1.1   
**Release or Custom Zip:** 1.1.0.1
**Map (If applicable):** Fenton Forest 4x map (1.50 ver.)
**Vehicle / Type (If applicable):** Tatra Phoenix 6x6 and Case IH 9240 (both base game machines)
**Multiplayer or Singleplayer:** Singleplayer  

**Describe the bug**  
Combine unloading mode does not work with courseplay worker. The combine is operated by CP and truck does not follow it even if the combine is full.

**If applicable - Steps to reproduce the behavior**  

**Screenshots**

**Comment by RedMonster-HUN** [comment]
[log.txt](https://github.com/Stephan-S/FS19_AutoDrive/files/4359503/log.txt)

**Comment by RedMonster-HUN** [comment]
Please fix this as soon as you can. I'd like to play the game but without automation it is not so funny.

**Comment by Iwan1803** [comment]
If you can't wait, then switch back to the old version at the moment.

**Comment by RedMonster-HUN** [comment]
From one flawy version to an other flawy? No thx

**Comment by Iwan1803** [comment]
1.0.7.x was working fine for me and also now 1.1.0.1, but ok, then you must wait for a feedback.
Maybe the problem is only on your site (mods, wrong settings, ...), but no, users never make mistakes....

**Comment by RedMonster-HUN** [comment]
I have tired it on base game map only with AD and CP activated but didn't work. So no need to be boastful.

**Comment by Iwan1803** [comment]
You said that AD is "flawy"...
As it works for me and others maybe your settings are wrong or something else is causing the problems you've got.
In the log i can't see any error for the path finding. Please try it again at the base map and save the map after the error occurs. Then post the log again.

**Comment by RedMonster-HUN** [comment]
https://youtu.be/4uM1N0yXFuQ
[log.txt](https://github.com/Stephan-S/FS19_AutoDrive/files/4361509/log.txt)

**Comment by Stephan-S** [comment]
Your video doesn't show the settings of the combine. I'm sure that you forgot to set the same destination 'M12' in the AutoDrive Hud there

**Comment by RedMonster-HUN** [comment]
Yeah, it was the soultion. Thanks for the tip.
