### ISSUE TITLE
Version 1.1.0.1: support of 2nd trailer?

### ISSUE THREAD

**Issue by RudiBergfeld** [Stephan-S/FS19_AutoDrive#1189]
AutoDrive Version: 1.1.01
Release or selbsterstelltes zip: Selbst 
Karte (falls relevant): NF Marsch o.G. Version 1.5
Fahrzeug(art) (falls relevant):

Die Version 1.1.01 belät den 2 Anhänger aber Entlät ihn nicht ?
 Im Modus Derscher Abtanken. Am Verkaufstrigger.  Die anderen Modi habe ich noch nicht getestet
Eine klare Beschreibung des Bugs.

**Falls anwendbar - Schritte mit denen ich den Bug nachstellen kann**

**Screenshots**
Falls relevant, bitte Screenshots beifügen

**Comment by Iwan1803** [comment]
Hast du den Zielpunkt einfach mal 1-2 Wepunkte weiter weg vom Trigger gesetzt?

**Comment by Stephan-S** [comment]
Genau. 2 Hänger werden unterstützt, der Zielpunkt darf aber nicht erreicht werden, bevor der zweite Hänger am Ablade/auladepunkt angekommen ist.
