### ISSUE TITLE
Wegfindung - schnelle Strecken bevorzugen

### ISSUE THREAD

**Issue by mnicklisch** [Stephan-S/FS19_AutoDrive#119]
Ein cooles Feature wäre wenn Fahrer erkennen könnten wie schnell sie eine Strecke fahren können. 
Ich habe auf meiner Map fast das komplette Streckennetz abgebildet und er findet auch den kürzesten Weg zum Ziel. Allerdings ist das nicht immer die schnellste Strecke.
Beispielsweise gibt es von dem einen Verkaufspunkt zwei Wege zu einem Feld. Er fährt den kürzeren Weg, der hat allerdings sehr viele enge Kurven, der längere Weg hat nur eine recht lange Kurve, d.h. er könnte den Weg fast komplett mit maximaler Geschwindigkeit fahren anstatt den kürzeren Weg größtenteils mit Schrittgeschwindigkeit. Natürlich könnte ich den kurvigen Weg raus nehmen, den brauch ich aber für andere Stationen im Netz.
Keine Ahnung ob man das abbilden kann, aber cool wäre es auf jeden Fall =)

**Comment by Stephan-S** [comment]
Hallo @mnicklisch ,

prinzipiell lässt sich das schon einbauen. Das würde allerdings auch zu einer längeren Berechnungsdauer führen, wenn die Strecken neu berechnet werden. Dort wird derzeit die Entfernung zwischen den Knoten als "Gewichtung" genommen. Es wäre also relativ einfach dies auf Geschwindigkeit zu beziehen (wenn man den Winkel zum vorherigen Punkt mit einbezieht).

Ich überlege mal ob ich das einbaue und dann im Optionsmenü anwählbar mache, ob die schnellste oder kürzeste Verbindung bevorzugt wird.

In der Zwischenzeit kannst du dir aber relativ leicht Abhilfe schaffen, indem du einfach die Option "Zielpunkte vermeiden" in den Optionen aktivierst, mit dem entsprechend gewünschten maximalen Umweg. 
Dann kannst du einfach ein 'Dummy'-Ziel auf die langsamere Strecke legen und die Wege neuberechnen lassen.

Mit dieser Option gewichtet er alle Strecken die durch Ziele fahren mit + x-Metern (x hier die Meter Anzahl in den Optionen).

Ich hoffe ich habe mich damit nicht zu undeutlich ausgedrückt :-)

Viele Grüße,
Stephan

**Comment by Stephan-S** [comment]
Hey @mnicklisch , ich habe die Option eingebaut. 
Kannst du das mal bei dir testen?
Ich habe allerdings kein release .zip File hinzugefügt, da ich die Option vorher noch etwas testen möchte.
Kannst du dir die selber aus den Dateien erzeugen oder brauchst du dabei Unterstützung?
Danke für deine Mitarbeit :-)

**Comment by mnicklisch** [comment]
Hi, cool dass das so schnell funktioniert hat, Daumen hoch =)
Ich habs gerade mal getestet und es scheint gut zu funktionieren, abgesehen davon dass ich mich geirrt habe was die schnellste Strecke ist. Ich habs jetzt mal genau getestet und zwei gleiche Trecker mit gleichem Anhänger an die Stelle gestellt wo er sich meiner Meinung nach anders entscheiden sollte. Sie kommen fast beide gleichzeitig an, aber die Strecke mit den Kurven ist tatsächlich ein bis zwei Sekunden langsamer. Er nimmt dann auch die kurvigere Strecke wenn er dort hin soll. Soll ich mal mein Savegame mit der Map und dem Streckennetz hochladen?

**Comment by Stephan-S** [comment]
Hey @mnicklisch 

alles gut. Ich denke das Issue hat sich hiermit erledigt. Falls nicht, einfach melden :-)
