### ISSUE TITLE
AD does not handover to CP after unloading

### ISSUE THREAD

**Issue by sdl112** [Stephan-S/FS19_AutoDrive#1190]
**AutoDrive Version:** 1.0.1.1

Szenario: Gras sammeln mit Ladewagen und CP, wenn ladewagen voll, Übergabe an AD zum entladen, dann zurück an CP.

Problem: CP macht alles wie gehabt, übergibt an AD, AD entlädt Ladewagen, fährt zurück zum Feldrand. Hier nun der Fehler: AD gibt nicht mehr an CP über. Gespann bleibt am Feldrand stehen.

**Comment by Stephan-S** [comment]
Fixed :-)
