### ISSUE TITLE
AD driver does not unload at mod silo

### ISSUE THREAD

**Issue by masneoquil** [Stephan-S/FS19_AutoDrive#1191]
AutoDrive Version: 1.1.0.1
Release or Custom Zip: Release  
Map (If applicable): Alszoszeg Agri
Vehicle / Type (If applicable): Loading Wagon
Multiplayer or Singleplayer: Singleplayer  

**Describe the bug**  
AD reach Silo and does not unload Loading Wagon with Straw. It was working on version 1.0.7.2.
In fact I saved mid work, update AD to 1.1.0.1 and after loading the game again and activating AD on the same vehicle, it reaches the Silo and continues without unloading. Is a mod Silo for multifruit.

**If applicable - Steps to reproduce the behavior**  
Basicaly, CP doing the field work and AD doing the transport route.

Please tell me if you need anything else.

Sorry if it was already reported and thanks for a great mod!!

**Comment by Iwan1803** [comment]
Which mod silo is it? From the map itself or an other one?

**Comment by masneoquil** [comment]
This one.
[](https://www.farming-simulator.com/mod.php?lang=en&country=us&mod_id=139297&title=fs2019)

**Comment by Iwan1803** [comment]
Some month ago i had a silo mod where not all fruits could be stored in.
I read that it had worked with 1.0.7.2, but could you try it with a default fruit? Wheat or barley maybe.
Is it a default or modding waggon?

**Comment by masneoquil** [comment]
Sure I will try and report back.
The waggon is a modded one.
https://www.farming-simulator.com/mod.php?lang=en&country=us&mod_id=137182&title=fs2019

**Comment by Iwan1803** [comment]
Then please try also with a non-mod. Try & error to find the problem...

**Comment by jala15** [comment]
Have you tried moving the destination point forward? Since 1.1 unloading trigger has to be reached before reaching destination waypoint (start unloading before reaching destination)

**Comment by Iwan1803** [comment]
That's not new. The destination should be allways a little bit behind the trigger.

**Comment by masneoquil** [comment]
I will try that also. The thing is, if that was always the case, don't understand why it was working on 1.0.7.2 and now it's not

**Comment by Stephan-S** [comment]
earlier it depended on the mode and on the 'on silo empty' settings.
Now the trigger has to be reached before arriving at the destination.

If that was the problem, please close this issue :-)
Otherwise, please make sure you use the latest dev version and if the problem persitst, let me know.

**Comment by masneoquil** [comment]
I can confirm that the problem was that the target waypoint location was the problem.
I moved it forward and it worked

Thanks again!!!
