### ISSUE TITLE
camera freezes if unloader is searching for corn chopper

### ISSUE THREAD

**Issue by steven1134** [Stephan-S/FS19_AutoDrive#1192]
AutoDrive Version: 1.1.0.1
Release or selbsterstelltes zip: Release
Karte (falls relevant): Alle
Fahrzeug(art) (falls relevant):

**Beschreibe den Bug**
kamara hängt sich beim Häcksler suchen auf

**Falls anwendbar - Schritte mit denen ich den Bug nachstellen kann**
Abfaher zum häcksler schicken
**Screenshots**

**Comment by Iwan1803** [comment]
Jedes mal oder nur sporadisch? Wirklich auf jeder Map mit jedem Drescher und jedem Abfahrer?
Tritt es auch nach einem Spielneustart auf? Poste bitte das Log dazu.
