### ISSUE TITLE
Pfad findung zu häcksler nicht möglich

### ISSUE THREAD

**Issue by steven1134** [Stephan-S/FS19_AutoDrive#1193]
AutoDrive Version: 1.1.0.1
Release or selbsterstelltes zip: Release
Karte (falls relevant):NFmarsch 4 fach
Fahrzeug(art) (falls relevant):

**Beschreibe den Bug**
abfaher kann keinen weg zu Häcksler finden

**Falls anwendbar - Schritte mit denen ich den Bug nachstellen kann**

**Screenshots**
![fsScreen_2020_03_20_18_36_28](https://user-images.githubusercontent.com/62439666/77192406-d0674680-6adc-11ea-95a8-11a633990a11.png)

**Comment by Stephan-S** [comment]
Sehr gut Steven, da sind etwa ein Drittel der benötigten Informationen vorhanden :D Was für Einstellungen hast du? Wo steht der Big X rum? Hast du mal per Debug Settings überprüft woran es liegen könnte?

Ist dir bewusst dass es im Vorgewende generell porblematisch sein könnte?

**Comment by steven1134** [comment]
also der abfahrer färt 1 mal zum häcksler hin und danach findet er keinen pfadmehr

**Comment by Iwan1803** [comment]
Beim nächsten Screenshot auch ruhig mal die AD-Linien anzeigen lassen. Ich werde mir das Feld aber gleich mal anschauen und wie Holger die Linien da gesetzt hat.
Ich lass Drescher und Häcksler auf den Feldern immer im Uhrzeigersinn fahren. Vielleicht solltest du das auch mal probieren.

**Comment by steven1134** [comment]
![fsScreen_2020_03_20_19_13_14](https://user-images.githubusercontent.com/62439666/77193767-0f969700-6adf-11ea-8b62-38795d9734f2.png)
![fsScreen_2020_03_20_19_12_52](https://user-images.githubusercontent.com/62439666/77193780-13c2b480-6adf-11ea-9d2a-616cc18498a4.png)
![fsScreen_2020_03_20_19_12_13](https://user-images.githubusercontent.com/62439666/77193795-16bda500-6adf-11ea-926c-c4927286ca88.png)
![fsScreen_2020_03_20_19_12_03](https://user-images.githubusercontent.com/62439666/77193798-19b89580-6adf-11ea-90f0-12a0a177550f.png)

**Comment by steven1134** [comment]
Sobald der abfaher am Häcksler angekommen und die sensoren für denn abfaher erscheie ist fährt er Wort wörtlich nur noch im Schneckentempo

**Comment by Iwan1803** [comment]
Abstand Häcksler nur auf 0,5m statt dem Standard von 1,75m?
Abstand Rohr auf 1,5m statt dem Standard von 0,75m?
Stell mal bitte den Standard wieder ein und poste auch mal die Einstellungen vom Häcksler.

**Comment by steven1134** [comment]
wo ich jetzt im Uhrzeigersinn mache findet er ihn ganz normal

**Comment by steven1134** [comment]
aber der föhrt nur bis der sensor an geht und macht dann nichts mehr

**Comment by Iwan1803** [comment]
Hast du den Standard mal wieder eingestellt und was ist nun das Problem: Pfadfindung oder Geschwindigkeit?

**Comment by steven1134** [comment]
![fsScreen_2020_03_20_20_22_23](https://user-images.githubusercontent.com/62439666/77199086-8b491180-6ae8-11ea-8742-3970176a8068.png)
das er einfach aufhört dem Häcksler zu folgen und ja ich hab die standart Einstellungen
![fsScreen_2020_03_20_20_26_15](https://user-images.githubusercontent.com/62439666/77199419-17f3cf80-6ae9-11ea-8c00-082c39c83497.png)
dazu kommt noch das er jetzt schon wieder keinen Pfad mehr findet

**Comment by Iwan1803** [comment]
Der Abfahrer steht aber auch sehr ungünstig und kann vermutlich deshalb keinen Weg finden.

**Comment by steven1134** [comment]
dann fahre ich ihn mal vor und schau ob er ihn wiederfinden kann

**Comment by Iwan1803** [comment]
Fruchtumfahrung hast du ja aus. Fahr den Häcksler einfach mal 15-20m nach vorne.

**Comment by steven1134** [comment]
hab ich jetzt is das problem das er auf ruf wartet

**Comment by Stephan-S** [comment]
Ich mach dann mal zu steven :-)
