### ISSUE TITLE
Priorität bei Abtankern / Priority for tankers 

### ISSUE THREAD

**Issue by JulesPapillon** [Stephan-S/FS19_AutoDrive#1194]
Discord: Billy_Balloon_Head

AutoDrive Version: 1.1.0.1
Release or selbsterstelltes zip: GIT ba9786792671e98b0136c5e7b397e94af25e29eb

**Beschreibe den Bug**
Werden mehrere Abfahrer eingesetzt wird immer der Nähste gerufen, statt der, mit dem größten Füllstand. Das kann dazu führen, dass alle Abfahrer fast zeitgleich voll werden und unnötige Wartezeiten entstehen.

**Comment by Iwan1803** [comment]
Wenn die am Startpunkt alle hintereinander stehen: wie sollen die hinteren nach vorne kommen?
Da es in AD die Möglichkeit gibt, die Abfahrer früher kommen zu lassen, sehe ich keinen wirklichen Sinn darin. Wartezeit sehe ich daher nicht als Kriterium, um eine solche Funktion einzubauen.

**Comment by JulesPapillon** [comment]
Wenn der Abtanker auf dem Feld parkt, steht er nach dem Abtanken natürlich irgendwo rum. Gerade bei größeren Feldern, kann es eben leicht passieren, dass #2 und ggf. #3 näher am Drescher stehen und somit vorgezogen werden.

In meinem konkreten Fall hatte ich zwei Abfahrer eingesetzt, weil die Strecke zum Ablieferort sehr weit war und ein einzelner länger gebraucht hat, als der Drescher um wieder voll zu werden. Werden im ungünstigsten Fall jetzt aber beide Abfahrer durch die Priorisierung relativ kurz hintereinander voll, sind beide unterwegs und der Drescher steht wieder voll rum und kann nicht weitermachen.

Natürlich ließe sich das Problem mit weiteren Abfahrern erschlagen, was aber schlicht in mehrerer Hinsicht ineffizient ist.

Die Abfahrer früher kommen zu lassen kann helfen, führt aber leider auf sehr verwinkelten Feldern gerne mal zu Kollisionen, wenn der Abfahrer versucht dem Drescher zu folgen.

**Comment by Iwan1803** [comment]
Wenn der Drescher nun den nächsten Abfahrer ruft, spart das Zeit. Es würde in meinen Augen keinen Sinn machen, einen Abfahrer mit fast vollem Tank zu bevorzugen, wenn dieser am Ars** der Welt steht.
Es wird sich durch keinen Mechanismus vermeiden lassen, das der Drescher u.U. mal auf einen Abfahrer warten muss - außer man setzt ausreichend Abfahrer ein oder greift händisch ein.

**Comment by Stephan-S** [comment]
Da muss ich ich Iwan recht geben. Ich sehe es auch eher so dass wir den nahegelegensten Abfahrer bevorzugen sollten.
Generell sollte auch das aktive Verfolgen des Dreschers gut laufen. Also frühe rufen einstellen und laufen lassen :-)
Wenn es (abgesehen vom Vorgewende)  Probleme beim Abtanken gibt, bebildere das Geschehen gerne mal mit ein paar Screenshots, damit wir da noch feintunen können :-)

**Comment by Iwan1803** [comment]
Ein 2. Abfahrer kann in den aktuellen Versionen früher gerufen werden.
An der Priorität der Abfahrer werden wir nichts ändern.
