### ISSUE TITLE
Courseplay diesel refill call fail

### ISSUE THREAD

**Issue by fcelsa** [Stephan-S/FS19_AutoDrive#1195]
**AutoDrive Version:** 1.1.0.1   
**Release or Custom Zip:** Last build
**Map (If applicable):** All  
**Vehicle / Type (If applicable):**   
**Multiplayer or Singleplayer:** Singleplayer  

**Describe the bug**  
When CP call for diesel refill nothings happen
This is the errors in log:
Error: Running LUA method 'update'.
...mods/FS19_AutoDrive/scripts/ExternalInterface.lua:149: attempt to call field 'getClosestRefuelDestination' (a nil value)

**If applicable - Steps to reproduce the behavior**  

**Screenshots**

**Comment by Stephan-S** [comment]
Thanks. Will be fixed soon :-)
