### ISSUE TITLE
Probleme mit Abholen und Abliefern / Problems with Pickup and Deliver

### ISSUE THREAD

**Issue by HerrchenChris** [Stephan-S/FS19_AutoDrive#1196]
AutoDrive Version: 1.0.1.1
Release or selbsterstelltes zip: Selbsterstellte Zip 
Karte (falls relevant): Oberthal
Fahrzeug(art) (falls relevant): Traktor mit Ladewagen Strautmann Aperion 3401

**Beschreibe den Bug**
Ich lasse mit Courseplay Stroh auf einem Feld einsammeln und anschließend soll CP das Fahrzeug an Autodrive im Modus "Abholen und Abliefern "übergeben. Dies funktioniert auch, mein Fahrzeug fährt das Stroh ins Lager und kehrt zum Feld zurück.
Dort bleibt das Fahrzeug jedoch mit aktiven AD stehen (im oberen Auswahlfeld bleibt das Ziel grün) und beginnt nicht mit dem weiter sammeln
[log.txt](https://github.com/Stephan-S/FS19_AutoDrive/files/4361816/log.txt)

**Falls anwendbar - Schritte mit denen ich den Bug nachstellen kann**

**Screenshots**
Falls relevant, bitte Screenshots beifügen

![20200320220646_1](https://user-images.githubusercontent.com/52828429/77206488-6019ee80-6af7-11ea-8124-cd291b359ad9.jpg)

**Comment by Stephan-S** [comment]
Sollte jetzt wieder problemlos möglich sein :-) Einfach den aktuellen Build von der Startseite laden.
Danke für die Meldung

**Comment by HerrchenChris** [comment]
Das mit dem automatischen weiter sammeln klappt jetzt, aber dafür kommt es jetzt öfters vor, dass der  Traktor dann nachdem er den Ladewagen voll hat, stehen bleibt und versucht, einen Pfad zu berechnen. Irgendwann kommt dann die Meldung, dass der Abfahrer den Pfad nicht berechnen konnte.
Auf dem Screenshot sieht man den Anfang vom CP-Kurs, wo auch der Wegpunkt F23 liegt.

![20200321101739_1_LI](https://user-images.githubusercontent.com/52828429/77223558-f7b22800-6b5d-11ea-893f-22472e89c7b2.jpg)
