### ISSUE TITLE
Soundbug by blocking vehicle

### ISSUE THREAD

**Issue by Wongkaying** [Stephan-S/FS19_AutoDrive#1197]
AutoDrive Version: 1.1.0.1
Release or selbsterstelltes zip: Build
Karte (falls relevant): Alle
Fahrzeug(art) (falls relevant): Alle

**Beschreibe den Bug**
Hab in der aktuellen Version ( Build ) das Problem / Phänomen, dass wenn ein Fahrzeug blockiert / nicht mehr weiterfahren kann es zu Soundbugs kommt. 
Optisch wird das Fahrzeug sekündlich neu gestartet.

**Falls anwendbar - Schritte mit denen ich den Bug nachstellen kann**
Beispiel: 2 Fahrzeuge zu Feld 1 Fahren lassen. Resultat: einer muss hinter dem zu erst angekommenen warten. Nun startet der wartende den Motor sekündlich neu.

Beispiel: Blockiere den Weg, sodass das Fahrzeug nicht mehrt weiterfahren kann.

**Screenshots**
Da Soundtechnischer Bug nicht möglich!

**Comment by Stephan-S** [comment]
Fixed
