### ISSUE TITLE
How can I use AutoDrive Course Editor?

### ISSUE THREAD

**Issue by Fabietto996** [Stephan-S/FS19_AutoDrive#12]
I saw that there is the AutoDrive Course Editor
and it is in jar, so I installed java when I start it I go to load the map but nothing loads only a small part and then it crashes, what program should I use to be able to use the course editor?

many thanks in advance

**Comment by Stephan-S** [comment]
Hey, sorry. The Editor is currently not at the level of the mod. That is because I changed the way, the route network is stored in the xml file to save on storage and time consumption.
This change has not yet found it's way into the course editor.
When I get to it, I will close this issue. Thank you for your input and patience.

**Comment by Fabietto996** [comment]
ok thanks, anyway great mod, much simpler than others, I'm trying these days for the first time since I use farming and I find it very easy and intuitive, the only flaw, if we want to call it that, it's a bit complicated to connect the paths for this I asked you about the editor, congratulations for the work you are doing, if I can give you a hand in the Italian translation I would like it, you will have noticed it from my bad English :)

hello and thanks again

**Comment by Stephan-S** [comment]
hey, italian translation would be nice. So if you feel comfortable with github. feel free to upload a translation and I will include it in the next update. All translations are in the moddesc.xml file. If you don't use github you can also send me an email with the translations. Thank you!

**Comment by Fabietto996** [comment]
ok i'm going to work in the afternoon, come on i try if i can't do it through github i send you the files by email

**Comment by RedOhne** [comment]
Same as #23.
