### ISSUE TITLE
Alternative Eingabemöglichkeit bei Frucht bzw. Transportgütern

### ISSUE THREAD

**Issue by rondo24xx** [Stephan-S/FS19_AutoDrive#120]
Ersteinmal besten Dank für die super Mod.
Ist in sehr vielen Punkten eine prima Ergänzug zu Courseplay. Bei der Nutzung von Transportaufgaben ist die Auswahl der Frucht/Transportgut z.Zt aber schon recht viel
Klicken mit der Maus. Gerade auf Maps mit seht vielen Früchten oder die Ergänzung durch
die nächsten Erweiterungen des "Fabrik-Script" auf den Maps, wird sich dieses Problem weiter
verschlechtern. Man Klickt dann gefühlte 30 Fruchttypen durch bis das Tranportgut in der
Liste auftaucht. Hast Du dafür evtl. eine Lösung (evtl. in Form einer PullDownListe o.ä.)? Ansonsten von den Funktionen einfach und funktionell. Sehr guter Ansatz. Erinnert mich manchmal etwas an die Helferfunktion bei "Cattle und Crops", nur ohne Taskplaner. 
Aber auch so schon sehr gut funktionierend.
Danke nochmals und erhalte Dir die Freude am kreativen Schaffen...
VG Rondo24xx

**Comment by Stephan-S** [comment]
Servus,

eine PullDownListe wurde hier schon öfter gewünscht.
So langsam muss ich mir wohl wirklich Gedanken machen, so etwas umzusetzen,
Für den Anfang kannst du aber auch mal versuchen ob die Bedienung mit dem Mausrad dir nicht auch weiterhilft.
Ziele und Transportgut können durch das Scrollen gewählt werden.
1.Zeile des Huds für das Ziel
2.Zeile: Linke Hälfte : Abladeziel, rechte Hälfte Transportgut

Viele Grüße,
Stephan

**Comment by Mannie313** [comment]
Mann kommt mit den Doppelnamen von den Tieren und auch bei den Früchten manchmal durcheinander.
Könnte man da was machen. 

MFG Mannie313

**Comment by Stephan-S** [comment]
@Mannie313 
Die Transportgüter ergeben sich rein durch Spielinterne Variablen.
Die Mehrfachaufzählung von Tieren ist daruch gegeben, dass es ja von jedem Tier verschiedene Typen (Farben) gibt. Bei Früchten sollte es nicht vorkommen bzw. nur wenn es diese auch in verschiedenen Formen geben kann.

Was stellst du dir hier als Verbersserung vor? Abgesehen von der gewünschten Pulldown Liste in der diese doppelten Namen allerdings auch wieder auftauchen, habe ich spontan keine Lösung im Kopf.

Beste Grüße,
Stephan
