### ISSUE TITLE
No unloading in drive-through-silo at BGA

### ISSUE THREAD

**Issue by SledgeHammer75** [Stephan-S/FS19_AutoDrive#1200]
**AutoDrive Version:** 1.1 (aktuell aus git)   
**Release or Custom Zip:** custom
**Map (If applicable):** All  
**Vehicle / Type (If applicable):**  1050 with Aperion 3401
**Multiplayer or Singleplayer:** Singleplayer  

**Describe the bug**  
Driver doesn't unload chaff in BGA drive-through-silo (no stopping, no unload-animation, just drives straight through the silo). Marker is aprox. 2-3m in the silo. 
(thought of possible modconflict with maizeplus/ccm at first but happens also with vanilla)

**Comment by SledgeHammer75** [comment]
the not-unloading seems directly related to the placement of the marker. When I move the marker about lenght of tractor+trailer into the silo, unloading works. 

Sadly, the driver accelerates to normal speed after passing the marker while still unloading, resulting in partially unload outside the silo.

**Comment by Stephan-S** [comment]
Please retry with the lastes build version.
But yeah, you have to place the marker behind the silo not in front and not inside :-)

**Comment by SledgeHammer75** [comment]
another day, another lesson :)
