### ISSUE TITLE
AutoDrive 1.1.0.1 problem with 2 trailers 

### ISSUE THREAD

**Issue by Opa-Andre** [Stephan-S/FS19_AutoDrive#1201]
AutoDrive Version: 1.1.0.1
Release or selbsterstelltes zip: Release
Karte (falls relevant): Alle
Fahrzeug(art) (falls relevant):

Standard Traktor mit 2 Standard Anhängern (keine Mods).

Beladung an einem Standard Silo Trigger mit Stroh, Abladen am Standard-Schweinestall. (ist aber unabhängig vom Füllgut - nur spezifiziert für das Repro).

Problem: Autodrive belädt nur den ersten, am Fahrzeug (Traktor) angehängten Anhänger. Danach wird direkt zur Abladestelle gefahren. Belädt man den zweiten Anhänger manuell, dann wird bei der Abladestelle auch nur der erste Anhänger hinter dem Fahrzeug entladen - d.h. Autodrive erkennt / nutzt den zweiten Anhänger nicht mehr. Das Problem ist auch unabhängig von der AD Einstellung des Trigger-Radius, ab wann er nach dem Trigger suchen soll.

Dabei ist auch noch aufgefallen, dass der Motor komplett des Traktors "ausgeschaltet" z. Bsp. beim Entladen komplett ausgeschaltet wird - und nicht im Leerlauf ist.

Problem besteht erst seit der 1.1.0.1. - bei der vorherigen AD-Version 1.0.7.2 funktionierte dies noch ohne Probleme.

**Comment by Stephan-S** [comment]
Der Zielpunkt muss soweit nach dem Trigger liegen, dass auch der zweite Anhänger am Trigger steht, bevor das Ziel erreicht wird

**Comment by Mannie313** [comment]
Kann man das nicht ändern so wie in 1.0.7.2. Sonnst müsste mann alles neu machen. wegen platz usw.

MFG Mannie313

**Comment by Stephan-S** [comment]
Nein, das wird ab dieser Version so gehalten.
Durch das Neuschreiben des Mods, macht es so mehr Sinn, da das Fahrzeug jetzt mit klar definierten Aufgaben unterwegs ist. Auf dem Weg zum Abladepunkt kann er demnach abladen. Danach ist er aber beispielsweise schon im 'Fahre zum Aufladepunkt' Zustand und kann so keine Abladetrigger mehr akzeptieren.

Aber mit dem neuen Ingame-Editor sollten eventuelle Änderungen ja blitzschnell gemacht sein. Einfach den Zielpunkt greifen und ein paar Meter nach hinten schieben ;-)
