### ISSUE TITLE
Keine Abtankung mit verbindung CP / No unloading with connection CP

### ISSUE THREAD

**Issue by Meditos77** [Stephan-S/FS19_AutoDrive#1202]
AutoDrive Version: 1.1.0.1
Release or selbsterstelltes zip: Release
Karte (falls relevant): Alle
Fahrzeug(art) (falls relevant): Drescher,Häcksler, Abfahrer

**Beschreibe den Bug**
Wenn CP beim Drescher/Häcksler aktiv ist,  wird der Abfahrer nicht mehr gerufen. Beim Drescher wird kein Rohr ausgefahren und alles steht. Mit alter Version 1.1.0.0 funktioniert es wieder.

**Falls anwendbar - Schritte mit denen ich den Bug nachstellen kann**
Drescher mit CP Kurs generieren, AD Feld einstellen, Abfahrer Drescher Abtanken einstellen
**Screenshots**
Falls relevant, bitte Screenshots beifügen

**Comment by Tadeloach** [comment]
I also have this issue.

**Comment by geo-luchs** [comment]
I've same issue with AD 1.1.0.1

**Comment by Stephan-S** [comment]
Hey, könnt ihr mal bitte auf die aktuelle Build Version wechseln und berichten ob ihr damit noch Probleme habt?
Ich werde morgen das nächste Release dann offiziell nachschieben

**Comment by Tadeloach** [comment]
> Hey, can you please switch to the current build version and report whether you still have problems with it?
> I will officially postpone the next release tomorrow

I didn't have that issue with the current build version, but on the current build version, the unloader wouldn't circle far enough behind the combine to line the trailers up correctly.  I am not sure if the OP had that issue or not.  I did mention it on the Discord channel.

**Comment by geo-luchs** [comment]
now , it looks better.
Unloader is now driving to harvester.
But I've to check more the hint from @Tadeloach  , that the circle is not far enough.
I had also 1 time the problem, the unloader was coming in front of harester, and was blocked by the harvester. But maybe this was because  I had disabled the kollision check some weeks before.

**Comment by Meditos77** [comment]
Nein das ist es nicht. Jedesmal wenn ich mit dem Häcksler fahre wird er Blockiert vom Abfahrer. Er bekommt den Befehl, das er stehen bleiben soll viel zu spät und dann will der Häcksler wenden und fährt zurück und wird vom Abfahrer Blockiert. Auch wenn ich die Reichweite auf Max stelle funktioniert es nicht. 
AD Version 1.1.0.1
