### ISSUE TITLE
AD übergibt zu früh an Cp

### ISSUE THREAD

**Issue by RudiBergfeld** [Stephan-S/FS19_AutoDrive#1203]
AutoDrive Version: 1.1.01
Release or selbsterstelltes zip: Selber
Fahrzeug(art) (falls relevant):

Autodrive übergibt zu früh an Cp im modus Abholen. Ad über gibt diereck nach dem Laden an Cp und fährt nicht zurück zum Feld map NF Marsch oG Version 1.5. 
[log.txt](https://github.com/Stephan-S/FS19_AutoDrive/files/4362730/log.txt)

Eine klare Beschreibung des Bugs.

**Falls anwendbar - Schritte mit denen ich den Bug nachstellen kann**

**Screenshots**
Falls relevant, bitte Screenshots beifügen

**Comment by RudiBergfeld** [comment]
ich korrigre nich immer Heute nicht

**Comment by Stephan-S** [comment]
Ist schon gefixed
