### ISSUE TITLE
AD Fährt nicht mehr und bleibt bei der Strecken berechnung hängen 

### ISSUE THREAD

**Issue by DerBauer2** [Stephan-S/FS19_AutoDrive#1204]
AutoDrive Version: 1.1.0.1
Karte (falls relevant): nicht Relevant
Fahrzeug(art) (falls relevant):Standart so wie Mods

**Beschreibe den Bug**
Ich Aktivieren AD und es passiert nichts. Man muss nah an der Fahrline (ca. 5m) sein damit er los fährt. Steht man weiter weg schaft er es nicht zu line zu finden.
Dazu kommt das wieder die FPS fallen also schein der fehler wieder ausversehn wieder eingeschlichen zu haben

**Falls anwendbar - Schritte mit denen ich den Bug nachstellen kann**
FZG weiter als 5-15 m weg stellen und AD Aktivieren.
**Screenshots**
![fsScreen_2020_03_21_13_44_46](https://user-images.githubusercontent.com/60297613/77226721-bc722200-6b7a-11ea-962a-348c7116b47d.png)

[log.txt](https://github.com/Stephan-S/FS19_AutoDrive/files/4362881/log.txt)

**Comment by iljarogoff** [comment]
Gleiches Problem hier, im discord hab ich erfahren dass an einer Lösung gearbeitet wird.

**Comment by DerBauer2** [comment]
Ah okay schön zu hören.

**Comment by Stephan-S** [comment]
Da wird versucht einen Pfad zum nächstgelegenen Punkt zu suchen. Da er mitten in der Frucht steht, wird das natürlich recht schwer. Und wenn am Ziel so etwas wie Bäume im Weg sind oder ein Hang dazwischen, wird es quasi unmöglich.
Solltest du einfach bedenken, wenn du AD mitten im Feld startest

**Comment by DerBauer2** [comment]
What? 1.0.7.2 geht das alles also liegt es an der Aktuellen version?

**Comment by Stephan-S** [comment]
In 1.0.7.2 macht der keine Pfadplanung sondern fährt ohne auf irgendwas zu achten in einer geraden Linie zum nächstgelegenen Punkt

**Comment by DerBauer2** [comment]
ja aber da geht es noch also liegt es an der Aktuellen Version und ist ein fehler?!
Logisch oder? Sonst würde es ja auch jetzr geht wennn ich diese version drin habe

**Comment by DerBauer2** [comment]
Wenn es noch nicht behoben wurde dann solte dies wieder geöffnet werden

**Comment by iljarogoff** [comment]
> 
> 
> Da wird versucht einen Pfad zum nächstgelegenen Punkt zu suchen. Da er mitten in der Frucht steht, wird das natürlich recht schwer. Und wenn am Ziel so etwas wie Bäume im Weg sind oder ein Hang dazwischen, wird es quasi unmöglich.
> Solltest du einfach bedenken, wenn du AD mitten im Feld startest

Meist wird AD ja auf dem Feld stehend eher unwillkürlich gestartet, will sagen: CP schaut nicht vorher nach, wo der Trecker steht, wenn es an AD übergibt :)

**Comment by iljarogoff** [comment]
> 
> 
> Wenn es noch nicht behoben wurde dann solte dies wieder geöffnet werden

Das sehe ich auch so. Zumal lt. Discord baloo an der Sache dran ist

**Comment by Stephan-S** [comment]
@iljarogoff Das CP Thema ist ein ganz unabhängiges und bereits behoben. Ich bin übrigens baloo auf Discord :-)

@DerBauer2 Da du offensichtlich nicht Willens oder nicht in der Lage bist, meine Erklärung zu verstehen, werde ich dich nun blocken, so dass ich keine von dir geöffneten Issues mehr sehen werde und auch deine Kommentare bei mir nicht mehr angezeigt werden. Aus dem Discord Server habe ich dich ja bereits entfernen müssen. Dann wohl auch hier
