### ISSUE TITLE
Problem mit überladewagen

### ISSUE THREAD

**Issue by steven1134** [Stephan-S/FS19_AutoDrive#1205]
AutoDrive Version: 1.1.0.1
Release or selbsterstelltes zip: Release
Karte (falls relevant): Alle
Fahrzeug(art) (falls relevant):Überladewagen

**Beschreibe den Bug**
Sobald der traktor mit überlaadewagen einen triger zum überladen gefunden hat bleib er stehen und macht nichts mehr (fährt nicht weiter eagl ob hänger voll lehr, überladewagen lehr

**Falls anwendbar - Schritte mit denen ich den Bug nachstellen kann**

**Screenshots**
![fsScreen_2020_03_21_14_55_12](https://user-images.githubusercontent.com/62439666/77228031-cac53b80-6b84-11ea-8414-48934757a2d4.png)
![fsScreen_2020_03_21_14_59_43](https://user-images.githubusercontent.com/62439666/77228035-d153b300-6b84-11ea-96e8-65d85756d80f.png)

**Comment by Stephan-S** [comment]
Fixed
