### ISSUE TITLE
Zugewiesene Parkpositionen für Fahrzeuge werden nach kurzer Zeit wieder entfernt

### ISSUE THREAD

**Issue by AngeloMerte** [Stephan-S/FS19_AutoDrive#1206]
AutoDrive Version: 1.1.0.1
Release or selbsterstelltes zip: Release
Karte (falls relevant): Alle
Fahrzeug(art) (falls relevant):

**Beschreibe den Bug**
Wenn ich meinen Fahrzeugen feste Parkplätze mit rechtsklick zuweise, werden diese zunächst übernommen, es wird auch die Meldung angezeigt und die Punkte werden auch korrekt angefahren, wenn ich auf das P klicke. Nach einiger Zeit resettet sich aber scheinbar alles, sodass die Zuweisungen wieder verschwinden und der "P" Button ausgegraut ist, als wenn nichts zugewiesen wurde.

**Falls anwendbar - Schritte mit denen ich den Bug nachstellen kann**
Parkplatz zuweisen - warten

**Screenshots**
Falls relevant, bitte Screenshots beifügen

**Comment by Stephan-S** [comment]
Ohja, ich habe mir den Code gerade nochmal angesehen.

Das Parkziel wird zurückgesetzte/gelöscht, wenn du irgendeinen anderen Zielpunkt auf der Karte löschst.
Fix kommt sofort :-)

**Comment by AngeloMerte** [comment]
Nebenbei mal ein großes Kompliment und Dankeschön! Seit dem letzten Update läuft AD so gut wie nie zuvor. Macht wieder richtig Spaß damit zu arbeiten. Mach/t weiter so und tausend Dank fürs zur Verfügung stellen. <3

**Comment by Stephan-S** [comment]
Immer gerne doch :-)
Dann kann ich hier ja zu machen
