### ISSUE TITLE
Im Ingame Editor versinken Wegpunkte im Boden /Waypoints sink in the ground

### ISSUE THREAD

**Issue by TobiHH78** [Stephan-S/FS19_AutoDrive#1207]
**AutoDrive Version:** 1.1.0.1.   
**Release or Custom Zip:** Customs Zip
**Map (If applicable):** All  
**Vehicle / Type (If applicable):**   
**Multiplayer or Singleplayer:** Singleplayer  

**Describe the bug**  
Bei Verschiebung von Wegpunkten mit dem Ingame-Editor versinken die Punkte teilweise im Boden. Das passiert z.B. bei Steigungen oder bei Wegpunkten über Brücken oder Überführungen  Die unteren Punkte sind dann nicht mehr erreichbar und lassen kein weitere Bearbeitung zu.

When using the ingame editor to move some waypoints, they disappear partly in the ground when doing it at an incline or on a bridge.

**Screenshots**  

![1_LI](https://user-images.githubusercontent.com/56259322/77247844-3ebf1c80-6c35-11ea-96e8-0294ced867d5.jpg)

**Comment by Stephan-S** [comment]
Yeah that is a problem that I do not have a solution for.
Just to clarify what's happening there. During recording of a route, I can use the current height value of the vehicle's position to properly place the node at the right height.
But when you drag it with the mouse, I have no other option but to rely on the data the game engine returns for that location via:
    node.y = getTerrainHeightAtWorldPos(g_currentMission.terrainRootNode, node.x, 1, node.z)
So if this is on a bridge or some misplaced streets such as in your screenshot, the terrainheight is often below the street level and I have yet to figure out whether I can actually get the height some other way there :(

**Comment by alex2ruote** [comment]
You can raise the terrain in GE, but it's quite the hassle if the road is inclined, and probably the reason why map modders don't bother fixing it. I remember a Goldcrest map for FS17 with a very long stretch of road with the terrain a couple of meters underneath the asphalt.

**Comment by Stephan-S** [comment]
Hey, I just had an idea to check for collision until i reach the correct height. This might impact perfomance a little when moving nodes but it should be fine.
So this is now pushed to the Todo List :D
