### ISSUE TITLE
Anfahrt zum Drescher abtanken

### ISSUE THREAD

**Issue by Andre-76** [Stephan-S/FS19_AutoDrive#121]
Moin,
erstmal ein Lob für diesen klasse Mod!!!
Nun zu meinem kleinen Anliegen...
Wenn der Drescher von hinten links angefahren wird, dann zieht AP das Zugfahrzeug mit Anhänger erst spät parallel zum Drescher. Wenn nun der Abtankpunkt erreicht wird, dann steht der Anhänger noch leicht schräg und der Trigger zum abtanken im Drescher wird nicht ausgelöst. Er steht wirklich nur ein klein wenig außerhalb des Bereichs.
Wir der Drescher von hinten rechts angefahren, dann besteht das Problem nicht, weil der Anhänger dann zwar auch etwas schräg steht, aber mehr Richtung Drescher.
Version nutze ich die 1.0.1.9 und ist bei verschiedenen Dreschern und Anhängern gleich.
Vielleicht kannst Du das Zugfahrzeug früher parallel ziehen??
Schönen Gruß
André

**Comment by Stephan-S** [comment]
Servus André,

ich habe die Strecke etwas angepasst, so das der Abfahrer nun ca 5 Meter früher probiert exakt zu positionieren.
Über eine kleine Rückmeldung würde ich mich freuen, da ich selber kaum zum Testen komme derzeit :-)

Viele Grüße,
Stephan

**Comment by Andre-76** [comment]
Hallo Stephan,
das nenne ich mal eine schnelle Umsetzung...TOP.
Die ersten Versuche waren wirklich erfolgreich...brauche auch ein wenig Zeit zum testen, da die Frucht ja auch erstmal wachsen muß und der Drescher nicht immer reproduzierbar von links angefahren wird :-) Aber wie gesagt...es schaut schon ganz gut aus! Ich werde das noch ein wenig weiter testen und Dir dazu nochmal Rückmeldung geben ;)
Vielen Dank und beste Grüße
André

**Comment by BerndUwe** [comment]
haiho

Wie genau funzt das mit dem Abtanken eigentlich? was muss man da machen das das geht?

mfg bernd

**Comment by Andre-76** [comment]
Hi Stephan,
nach ein wenig laufen lassen und so, kann ich sagen, daß es wesentlich besser läuft, aber es kommt noch vor, daß der Anhänger so gerade eben außerhalb des Bereiches ist, wie Du an dem Screenshot sehen kannst. Ich weiß nicht, wie es allgemein ist, aber bei mir könnte er noch etwas näher an den Drescher fahren, dann könnte das passen.

Schönen Gruß
André
![abtanken](https://user-images.githubusercontent.com/50804434/58192029-22beb780-7cc0-11e9-8e1b-75146e49979a.jpg)

@BerndUwe 
Ist jetzt ein wenig anderes Thema und ich möchte hier nicht zu weit ausholen. Du findest ne gute Anleitung unter: https://www.youtube.com/watch?v=cC50lfNVmxs

**Comment by Stephan-S** [comment]
Hey André,

den Abstand kannst du in den AutoDrive Einstellungen selber noch anpassen.
Falls du das Menü noch nicht gefunden hast:
  Linke Strg + linkes Alt + Numpad 0

Beste Grüße,
Stephan

**Comment by Andre-76** [comment]
Hi Stephan,
damit scheint es endgültig gelöst zu sein ☺️ musste den Abstand allerdings auf 0 stellen. Jetzt läuft bisher alles glatt durch. Dann kannst Du das Thema auf erledigt setzen 😉
Vielen Dank für Deine schnelle Hilfe 👍
Beste Grüße 
André
