### ISSUE TITLE
Warum fährt AD nicht an den Triggern vorbei / Why doesn't AD drive past the triggers 

### ISSUE THREAD

**Issue by Mannie313** [Stephan-S/FS19_AutoDrive#1210]
AutoDrive Version: 1.1.0.1
Release or selbsterstelltes zip: Release
Karte (falls relevant): Alle
Fahrzeug(art) (falls relevant):
Ich hab manchmal nicht die möglichkeit einen abstand von 10 oder 25 metern zu einem Trigger abstand zu halten. Aber trotzdem sobald AD an einem trigger vorbeikommt fährt dieser nur 15 bzw 5 khm. aber es ist ein anderer trigger wo ich abladen möchte. Kann mann da irgend was tun. aber nur wen ich volgeladen habe. wen er leer ist fährt er einfach an den anderen trigger vorbei.
**Beschreibe den Bug**
Eine klare Beschreibung des Bugs.

**Falls anwendbar - Schritte mit denen ich den Bug nachstellen kann**

**Screenshots**
Falls relevant, bitte Screenshots beifügen

MFG Mannie313

**Comment by Mannie313** [comment]
https://youtu.be/PDfWTW-LkjM

in diesem Viedeo seht ihr was ich meine. 
Er lädt am Hofsilo fährt dann los. ok Hoftankstelle ist ja noch ok.
Dann auf der strasse fährt er an den Saatvorbereitungssilos vorbei mit nicht mehr als 15 km/h.
Danach gibt er wieder gas und an der ranch fährt er wieder nur mit 15 km/h vorbei.

Kann mann da was noch machen oder geht da nix mehr.

MFG Mannie313

**Comment by Meditos77** [comment]
Ich kenne das Problem. Aber bei mir fährt er sogar durch ohne zu halten wenn ich es ihm nicht gesagt habe. Ich glaube deinen Einstellungen sind falsch. Ich habe im Menü bei Zielpunkte vermeiden - JA und bei Wenn Silo leer ist  - Weiterfahren. Das müsste eigentlich das Problem lösen. Das einzige wo es bei mir noch scheitert ist, wenn ich an einem Licht trigger fahre. Da bleibt er sogar stehen. Aber der ist nicht groß und kann leicht umfahren werden. Wie gesagt ein wenig im Menü herum spielen und dann geht es.

**Comment by RalfGorden** [comment]
hallo ich glaube in der 1.1.0.1 gibt es  Zielpunkte vermeiden nicht, mehr oder hab es übersehen

**Comment by Mannie313** [comment]
Zielpunkte vermeiden gibt es in der 1.1.0.1 nicht finde es da auch nicht mehr.

MFG Mannie313

**Comment by Mannie313** [comment]
Danke @Stephan-S funtioniert soweit super. bis auf ein paar kleine ausnahmen. Aber was ich mich frage ist wieso bleibt AD nicht stehen bis sich der Container wieder gesenkt und geschlossen hat. AD kippt aus und sobald er leer ist fährt er los.

MFG Mannie313

**Comment by Meditos77** [comment]
Ja syr. Ich wechsle immer hin und her weil ich mit Cp auch Probleme hatte. Aber ich schau mir das mal mit dem Aktuellen an. Was ich beim Video gesehen habe, du hast sehr viele Überschneidungen. Und jedesmal wird er langsamer, weil er wieder rechnet. Ich mach das ganz Simpel und habe es mir von der Standard Map abgeschaut und das funkt super. Ich fahre einen rund Kurs ohne einen Punkt zu setzten. Und dann fahre ich zb zum Feld, und mache mir eine Blaue Linie. Also beiderseitig befahrbar. Dann öffne ich den super Editor und verbinde sie. Der vorteil, sobald sich ein Fahrzeug auf diesem Punkt befindet und du einen 2 hin schickst bleibt er so lange stehen bis der andere weg ist und der 2 fährt rein. Somit nicht so viele Punkte, und die Rundungen fährt er von selber. Das zweite was ich gesehen habe. Du hast bei den Kauf Sachen
 bei jedem einen Haltepunkt gesetzt. das mache ich auch nicht. Ich fahre einfach durch und und setzte dann am Schluss einen gemeinschafts Halte punkt. nur damit er weiß wohin er fahren soll. Gebe ich jetzt zb. Pflanzenschutz ein und er soll das holen, dann fährt er bei allen vorbei und haltet beim Trigger. AD erkennt das absolut super. Somit wieder weniger zu Berechnen und es geht schneller.
![KursVerbinden](https://user-images.githubusercontent.com/48370207/77255106-61692980-6c65-11ea-849b-55141c429202.JPG)
![Befüllung](https://user-images.githubusercontent.com/48370207/77255188-f66c2280-6c65-11ea-8ffa-d2e912bd49dd.JPG)
