### ISSUE TITLE
Bin am Häckseln und AD Fährt nach der wende nicht weiter / I am chopping and AD does not continue after the turn

### ISSUE THREAD

**Issue by Mannie313** [Stephan-S/FS19_AutoDrive#1211]
AutoDrive Version: 1.1.0.1
Release or selbsterstelltes zip: selbsterstelltes zip letzter Version 
bdb2810
Karte (falls relevant): Alle
Fahrzeug(art) (falls relevant):
Ich bin am Häckseln und die erste reihe macht AD sehr gut. Sobald auch CP rumdreht bleibt AD stehen fährt aber dann nicht weiter. Der Erste abfahrer ist fast voll und der zweite wartet.
**Beschreibe den Bug**
Eine klare Beschreibung des Bugs.

**Falls anwendbar - Schritte mit denen ich den Bug nachstellen kann**

**Screenshots**
Falls relevant, bitte Screenshots beifügen
![fsScreen_2020_03_22_19_28_24](https://user-images.githubusercontent.com/3021040/77257329-d6dbf680-6c73-11ea-8dbc-2c7b9cfcbb9d.png)

MFG Mannie313

**Comment by Stephan-S** [comment]
Liegt vermutlich an deinen Feldausfahrt Einstellungen. Der plant wohl einen Weg zurück zum Startpunkt. Kann dort aber keinen Weg finden, weil der zweite Abfahrer dort die Pfadplanung blockiert

**Comment by Mannie313** [comment]
Der ist auf 100 % eingestellt abeim abfahren.

**Comment by Stephan-S** [comment]
Feldausfahrt Einstellungen auf Standard  oder hinterm start oder nahegelegen?

**Comment by Mannie313** [comment]
![fsScreen_2020_03_22_19_36_43](https://user-images.githubusercontent.com/3021040/77257425-7ac5a200-6c74-11ea-81e8-57b1cbb88a40.png)
Das sind meine einstellungen für die abfahrer

**Comment by Mannie313** [comment]
So ich habe CP mal ausgemacht und dann kommt beim LKW dies:
![fsScreen_2020_03_22_19_39_29](https://user-images.githubusercontent.com/3021040/77257492-f45d9000-6c74-11ea-96eb-6ab172cd9800.png)

Sobald ich CP wieder starte kommt dies:
![fsScreen_2020_03_22_19_39_44](https://user-images.githubusercontent.com/3021040/77257495-02131580-6c75-11ea-83ca-db999b8a268b.png)

MFG Mannie313

**Comment by Stephan-S** [comment]
Dann scheint ihn irgendwas an der aktuellen Häckslerposition zu stören. Kann ich so nicht sagen, woran es scheitert. Vielleicht eine seltsame Kollisionsbox an der Straße

**Comment by Mannie313** [comment]
Das rohr ist auf der Linken seite.

![fsScreen_2020_03_22_19_46_29](https://user-images.githubusercontent.com/3021040/77257631-d80e2300-6c75-11ea-8e75-16c24642fa0d.png)

und weit und breit nix ausser der strasse.

Ich hab ne blaue linie ums feld herum eingefahren.

MFG Mannie313

**Comment by Mannie313** [comment]
Ich hab mir mal das neue Update gezogen. Ich werde das mal im auge behlten.

**Comment by Mannie313** [comment]
Fals du es dir mal ansehen möchtest.

Es ist diese map: https://www.farming-simulator.com/mod.php?lang=de&country=de&campaignIndex=21&mod_id=128803&title=fs2019

und hier meine Kurse: 
[AutoDrive_Hagenstedt_init_config.zip](https://github.com/Stephan-S/FS19_AutoDrive/files/4366059/AutoDrive_Hagenstedt_init_config.zip)

MFG Mannie313

**Comment by Iwan1803** [comment]
Fahr mal mit einigen Vorgewenden. Ich vermute einfach mal, das er den Weg zum Häcksler aufgrund der Steine/Felsen neben der Strasse nicht berechnen kann.

**Comment by Mannie313** [comment]
Ok kann ich mal machen

**Comment by Mannie313** [comment]
Ich hab noch ein kleines problem beim Häckseln festgestellt. Wen er hinter den Häcksler fahern soll und auf der rechten seite ist will er linksrum fahren.

![fsScreen_2020_03_23_09_34_47](https://user-images.githubusercontent.com/3021040/77297558-c36b7280-6ce9-11ea-828a-65d0dcb4147c.png)

**Comment by Iwan1803** [comment]
Er versucht vermutlich den Pfad übers Feld neu zu berechnen. Da der Häcksler weiter abladen und somit auch weiterfahren kann, kommen sie sich dann an der Stelle in die Quere.
Ob man das abfangen kann, muss @Stephan-S prüfen, aber es wird wohl immer wieder mal Situationen wie diese geben.

**Comment by Stephan-S** [comment]
Bitte auf 1.0.7.2 bleiben oder den neuesten Release-Candidate 1.1.0.3-1 nutzen :-)
