### ISSUE TITLE
Vermutlicher fehler mit überladewagen

### ISSUE THREAD

**Issue by steven1134** [Stephan-S/FS19_AutoDrive#1212]
AutoDrive Version: 1.0.
Release or selbsterstelltes zip: 1.1.0.1
Karte (falls relevant): Alle
Fahrzeug(art) (falls relevant):
überladewagen
**Beschreibe den Bug**
abfahrer mit überladewagen wartet nicht beim überladen sondern fährt strickt zum abladepunkt wie man unten im screenshot sieht (weis nicht ob das gewolt is)

**Falls anwendbar - Schritte mit denen ich den Bug nachstellen kann**

**Screenshots**
![fsScreen_2020_03_22_21_02_30](https://user-images.githubusercontent.com/62439666/77259527-4ce75a00-6c82-11ea-8293-dc93f79892b6.png)

**Comment by Stephan-S** [comment]
Wenn er auf dem Weg zum Zielpunkt ist, achtet er nicht darauf was der Hänger macht.
Der Abladepunkt sollte also so gesetzt sein, dass er nach deinem wartenden Sattelschlepper kommt
