### ISSUE TITLE
in Load/Unload mode check the level before continuing

### ISSUE THREAD

**Issue by Maarkreidi** [Stephan-S/FS19_AutoDrive#1216]
In load/unload mode, the tractor returns to the loading point between each target of a folder even if the trailer is not empty. 
I use an 8000L tank and each unloading target can hold 2000L. After each delivery it reloads back to the tank. This makes the loading capacity of the tank useless and wastes a lot of time for the system.

**Describe the solution you'd like**
I would like the tractor to check if the trailer/tank is empty. If it is empty then it will reload before continuing its circuit, otherwise it will go to the next target on the list.

**Comment by TyKonKet** [comment]
@Stephan-S I think that could be a good feature, what do you think boss?

**Comment by Stephan-S** [comment]
Done :-) Haven't had a chance to test it though. So if you get the chance, please report feedback.
And make sure to use the latest dev build from the repo's homepage :-)

**Comment by Maarkreidi** [comment]
Test OK. It's working as expected.
But the function doesn't take into account the desired number of loops.
I specified to go around once, but it keeps on going round and round.

**Comment by TyKonKet** [comment]
@Stephan-S

**Comment by Iwan1803** [comment]
Was fixed in the meantime.
