### ISSUE TITLE
Be able to create subfolders

### ISSUE THREAD

**Issue by Maarkreidi** [Stephan-S/FS19_AutoDrive#1217]
As I run a server with 8 farms, there are a large number of destinations. The folder system helps to organize the destinations but is a bit limited for a large number of farms.

**Describe the solution you'd like**
Being able to create subfolders would complete the organization of destinations for each farm.

**Comment by F-Patsch** [comment]
Auch ich würde mich über die Möglichkeit Unterordner in der Ordnerstruktur zu erstellen freuen. Mit dem Einbau der Funktion des Rotierenden Be-und Entladens wird es nötig viele neue Ordner zu erstellen und die Übersichtlichkeit beginnt zu leiden. 
Keinesfalls versäumen will ich hier ein großes Danke auszusprechen für einen großartigen Mod.

**Comment by Hans-Ulrich** [comment]
Ich denke auch das Unterordner unbedingt notwendig sind. Zumindest sollte das Ordnerfenster größer werden, da bei mir nicht alle Ordner angezeigt werden und so das Sortieren nur sehr umständlich möglich ist. Aber natürlich auch von mir ein DANKE für die tolle Arbeit an diesem Super-Mod.

**Comment by XPiRiJenZ** [comment]
Ich schließe mich hier mal und und unterstütze den Wunsch nach Unterordnern.
Dadurch, dass auf vielen Karten Produktionen verbaut sind bieten sich gerade hier viel bessere Möglichkeiten durch die Abladestellen zu navigieren, wenn man zB einen Hauptordner "Produktionen" und dann die entsprechenden Unterordner anlegen kann.
