### ISSUE TITLE
Driver drives too diagonally at thresher

### ISSUE THREAD

**Issue by RalfGorden** [Stephan-S/FS19_AutoDrive#1219]
AutoDrive Version: 1.1.0.2-1
Release or selbsterstelltes zip: Release
Karte (falls relevant): Alle
Fahrzeug(art) (falls relevant):

**Beschreibe den Bug**
hallo hab das Problem das der Abfahrer sehr schräg an den Drescher fährt,so das er oft nicht beladen wird ,er müsste ein größeren Bogen machen und gerade dann ranfahren , in der 1.0.7.2 ging es noch super
![fsScreen_2020_03_23_17_01_16](https://user-images.githubusercontent.com/56214377/77337989-f9304b80-6d29-11ea-833e-070237836a96.png)

![fsScreen_2020_03_23_17_01_03](https://user-images.githubusercontent.com/56214377/77337913-e3228b00-6d29-11ea-90e9-83f0c4e613f5.png)

**Falls anwendbar - Schritte mit denen ich den Bug nachstellen kann**

**Screenshots**
Falls relevant, bitte Screenshots beifügen
![fsScreen_2020_03_23_17_00_59](https://user-images.githubusercontent.com/56214377/77337861-cb4b0700-6d29-11ea-954c-aac5f313a0a8.png)

**Comment by Iwan1803** [comment]
Spiel mal ein wenig mit dem Rohrabstand, ob es dann besser wird. Standard ist ja 0,75m.

**Comment by RalfGorden** [comment]
hab schon immer den Rohrabstand auf 0,75m

**Comment by Iwan1803** [comment]
Dann probier es doch einfach mal mit 0,50 oder 0,25m, ob es dann besser läuft.

**Comment by RalfGorden** [comment]
hab schon immer den Rohrabstand auf 0,75m 
hab auch schonmal mehr und weniger aber immer das gleiche Ergebnis
bei der 1.0.7.2 ging es noch super, soll jetzt keine Kritik sein

**Comment by RalfGorden** [comment]
aber teste noch ein wenig weiter

**Comment by Iwan1803** [comment]
Habe ich auch nicht so aufgefasst 😉
Aktivier mal in CP und AD die Fruchtumfahrung. Dann müsste der CP-Drescher ja etwas von der Frucht wegfahren und der AD-Abfahrer anders ranfahren.

**Comment by RalfGorden** [comment]
ok danke erstmal werde weiter testen

**Comment by Gariot** [comment]
Aehnliches konnte ich auch feststellen. Der Abfahrer lenkt einfach zu frueh hinter dem drescher ein und steht dann relativ schraeg, wie auf den bildern, beim drescher unterm rohr. Bisher hat das abtanken trotzdem geklappt, aber es koennte schon kritisch werden. Bei mir ist allerdings kein courseplay im einsatz, vielleicht hatte ich deshalb bisher glueck :D

**Comment by RalfGorden** [comment]
morgen hab noch ein wenig getestet ,jetzt mit Fruchtumfahrung bei CP und AD,ich bin der Meinung das er zu zeitig wendet so das er nie gerade an das Rohr ranfährt, was bei der 1.0.7.2 noch super ging , hab jetzt die AutoDrive Version: 1.1.0.2-2 
![fsScreen_2020_03_24_09_39_59](https://user-images.githubusercontent.com/56214377/77406656-4c9bab80-6db5-11ea-888a-f95cf76a389c.png)
![fsScreen_2020_03_24_09_40_09](https://user-images.githubusercontent.com/56214377/77406673-50c7c900-6db5-11ea-86be-33ea944a4987.png)
![fsScreen_2020_03_24_09_41_44](https://user-images.githubusercontent.com/56214377/77406687-532a2300-6db5-11ea-96c4-bca4ae8c556b.png)

**Comment by RalfGorden** [comment]
hallo bin jetzt erstmal wieder auf die1.0.7.2 zurück ,da geht es super

**Comment by Iwan1803** [comment]
Super, denn -> https://github.com/Stephan-S/FS19_AutoDrive/issues/1238
