### ISSUE TITLE
[BUG] AD ignoriert höchstgeschwindigkeit / AD ignores speedlimit

### ISSUE THREAD

**Issue by Gariot** [Stephan-S/FS19_AutoDrive#1220]
AutoDrive Version: 1.1.0.2
Release or selbsterstelltes zip: Release
Karte (falls relevant): Alle
Fahrzeug(art) (falls relevant): Alle / all (Vanilla) and tested with Autodrive mod Only.

**Beschreibe den Bug**
AD ignoriert welche geschwindigkeit mal einstellt. Es faehrt einfach so schnell es kann. / AD ignores the speedlimit. It just drives as fast as it can.

Update:
AD "ignoriert" die geschwindigkeitseinstellung die man in seinem UI einstellt nicht, sondern setzt sie schlicht anders um. Wenn man 50km/h einstellt, faehrt er ~63km/h und wenn man 40km/h einstellt faehrt er ~50km/h. Vielleicht ein umrechnungsfehler oder sowas.
/
AD doesnt ignore the speed limit setting set in the AD UI, it just "interprets" or "understands" it different. If you set 50km/h for example, it drives about ~63km/h and if you set 40km/h it drives ~50km/h. Maybe a conversion error or something.

![20200324025428_1](https://user-images.githubusercontent.com/18175983/77381330-dcbdfe80-6d7d-11ea-888f-00f5c3ea2be8.jpg)

**Comment by Iwan1803** [comment]
-> https://github.com/Stephan-S/FS19_AutoDrive/issues/1238
