### ISSUE TITLE
[QUESTION] Why does AutoDrive not load seeds and fertilizer?

### ISSUE THREAD

**Issue by Zottel33** [Stephan-S/FS19_AutoDrive#1221]
AutoDrive Version: 1.1.0.2
Release or selbsterstelltes zip: Release
Karte : Felsbrunn (Original Karte)
Fahrzeug: Claas Axion 920, Horsch Pronto 9 DC 

Ich möchte mit dem Claas Axion 920 und der Sämaschine Horsch Pronto 9 DC ein Feld bestllen.
Hierbei soll gleichzeitig gedüngt und gesät werden.

Mit Courseplay (V 6.01.00395) habe ich den einen Feldkurs generiert. 
In Courseplay ist unter der AutoDrive Funktion „For unload/refill“ eingestellt.

AutoDrive (Modus Abholen) ist bei Ziel das entsprechende Feld eingetragen. In meinem Fall ist es Feld 27. Als Ziel ist ein Punkt angegeben welcher direkt hinter meinem Saatgut Silo liegt. Vor dem Saatgutsilo steht ein Düngersilo. Beide Silos sind von hier https://www.modhoster.de/mods/befullbare-lager-kalk-dunger-saatgut (in der Version 1.1).

Zum Test habe ich etwas Dünger und Saatgut in die Sämaschine geladen. Nachdem der Dünger leer war hat der Claas sich auf den Weg zu den Silos gemacht. 
Leider lädt AutoDrive Dünger und Saatgut nicht automatisch nach.

Ich weiß leider nicht wo der Fehler ist.
Kann es sein das die Silos inkompatibel zu AutoDrive sind?
Falls ja, gibt es platzierbare Silos welche einwandfrei mit AutoDrive funktionieren?

**Comment by Iwan1803** [comment]
Die Silos nutze ich auch und das ganze problemlos. Vielleicht hilft ein Screenshot mit AD-Linien, um das Problem einzugrenzen.

**Comment by flattergaul** [comment]
Hallo Zottel33,

wo ist den das AutoDrive-Ziel? Ich glaube, seid V1.1.0.1 muss das Ziel NACH den Triggern platziert werden, damit das Befüllen funktioniert.

Gruß

**Comment by Iwan1803** [comment]
Mit 1.1. musste ich den Zielpunkt etwas nach vorne schieben und den Abstand zum Silo von 25 auf 50m erhöhen, aber es lüppt.
![fsScreen_2020_03_24_13_29_09](https://user-images.githubusercontent.com/47528836/77426599-1837e780-6dd5-11ea-8647-4e7c3c0d7082.jpg)

**Comment by Zottel33** [comment]
Erst mal vielen Dank für die schnellen Antworten.
Ich habe mir das Video angesehen und noch ein bisschen getestet.

Folgendes habe ich herausgefunden:
- Es ist wichtig das die Silos möglichst nah zusammenstehen
- Die Distanz in Autodrive zu den Silos muss auf 50m gestellt werden
- Wenn man den Kurs einfährt sollte man dies auf jeden Fall mit einer Sämaschine machen, welche man auch verwenden möchte. Dabei ist darauf zu achten das das Einfüllrohr genau unter dem Saat- bzw. Düngebehälter der Sämaschine ist. Wie beschrieben sollte der Wegpunkt zu den Silos etwas hinter dem letzten Silo liegen
- Sämaschinen, welche ausgeklappt werden müssen zum befüllen lassen sich nicht befüllen
- Sämaschinen, welche Separate Klappen für Dünger und Saatgut haben lassen sich nicht befüllen

PS: Die Horsch Pronto 9 DC lässt sich einwandfrei befüllen, wenn die Wegstrecke korrekt eingefahren ist.

Danke noch mal für die Hilfe!
(Das Thema kann nun gerne geschlossen werden)

**Comment by Iwan1803** [comment]
`Sämaschinen, welche Separate Klappen für Dünger und Saatgut haben lassen sich nicht befüllen`
Schau dir meinen Screenshot an. Es sind separate Klappen für Dünger & Saatgut und beide werden vor dem Erreichen des ersten Silos bereits hochgeklappt. Du meinst vermutlich Saatmaschinen, wo die Abdeckung nur im Wechsel aufklappt, oder?

**Comment by Zottel33** [comment]
Ganz genau. Ich meine die Abdeckungen welche im Wechsel aufgeklappt werden.
