### ISSUE TITLE
[BUG] AutoDrive 1.1.0.2 problem with 2 trailers

### ISSUE THREAD

**Issue by Opa-Andre** [Stephan-S/FS19_AutoDrive#1222]
AutoDrive Version: 1.1.0.2
Release or selbsterstelltes zip: Release
Karte (falls relevant): Alle
Fahrzeug(art) (falls relevant): Traktor mit 2 Trailern.

Hi Stefan, 
nachdem Du mein Issue #1201 mit der Bemerkung geschlossen hast, dass die Ursache am zu nahen Ladepunkt liegt, habe ich das ganze nochmal getestet - jetzt mit der Version 1.1.0.2. Dazu habe ich auch den Triggerpunkt etwas weiter verschoben. 
Ergebnisse:
1. Der Traktor schaltet immer noch während der Beladung / Entladung den Motor aus.
2. Der 2. Trailer wird nur unvollständig beladen.
3. Entladung funktioniert soweit, allerdings wird hier ebenfalls der Motor abgeschaltet.

Ich habe daher den Beladevorgang mal mit eingeschaltetem Dev-Mode aufgezeichnet. 
-> Der Traktor fährt zum Silo, um Stroh zu laden und belädt den ersten Anhänger.
-> Fährt ein Stück vor und fängt an, den zweiten Anhänger zu beladen - stoppt aber plötzlich den Beladevorgang.
- > Nach etwas Wartezeit habe ich dann AD deaktiviert und danach den 2. Hänger manuell beladen.

Anbei das Video und meine Log.txt. Der Traktor ist aus dem Claas DLC und der Hänger vom Modhub (tritt aber auch mit anderem Equipment auf.) Habe auch die Liinien aktiviert, damit Du den Triggerpunkt sehen kannst.

Tip: Wenn Du Dir die Videodatei herunterlädst und lokal abspielst, sind die Texte auf dem Screen besser lesbar - bei Verwendung des OnlinePlayers sieht das ganze ziemlich verschwommen aus.

Link zu meinem OneDrive (Video & Log.txt). Anbei auch die Log,txt hier schon mal angehängt.

https://1drv.ms/v/s!AJAS1kHbd61LhPNs

[log.txt](https://github.com/Stephan-S/FS19_AutoDrive/files/4372141/log.txt)

**Comment by Stephan-S** [comment]
Alles klar. Das sieht jetzt interessant aus :-) Ich schau mir das dann morgen abend mal genauer an.

**Comment by Vega56** [comment]
Das gleiche habe ich bei mir auch beobachtet.

**Comment by Iwan1803** [comment]
-> https://github.com/Stephan-S/FS19_AutoDrive/issues/1238

**Comment by Opa-Andre** [comment]
Bestätigt. In 1.0.0.4 funktioniert es wieder korrekt.
