### ISSUE TITLE
[BUG] Geschwindigkeit kalibrieren /speed of the cruise control is wrong

### ISSUE THREAD

**Issue by Michael170978** [Stephan-S/FS19_AutoDrive#1223]
**AutoDrive Version:** 1.1.0.2x   
**Release or Custom Zip:** Release  
**Map (If applicable):** All  
**Vehicle / Type (If applicable):**   
**Multiplayer or Singleplayer:** Singleplayer  

**Describe the bug**  

Hallo Stephan/Iwan

Könntet ihr bitte die Geschwindigkeit vom Tempomat kalibrieren?

Die tatsächliche Geschwindigkeit ist 13 km/h höher als am Tempomaten eingestellt (s. Foto)

![Unbenannt](https://user-images.githubusercontent.com/53015927/77368067-c606b000-6d5b-11ea-9e94-f7e028888af1.png)

**Comment by Iwan1803** [comment]
Klingt nach dem gleichen Problem wie hier: https://github.com/Stephan-S/FS19_AutoDrive/issues/1220

**Comment by Michael170978** [comment]
Naja nicht ganz. Ich kann mir die Geschwindigkeit schon einstellen. Das Fahrzeug fährt halt  13km/h  schneller als eingestellt

**Comment by Gariot** [comment]
Es ist das gleiche Problem ;) Egal was im AD eingestellt ist, die Geschwindigkeit wird nicht eingehalten. Selbst wenn man im spieleigenen Tempomat die Geschwindigkeit runterregelt fahrt der AD Fahrer trotzdem so schnell er kann.

**Comment by Michael170978** [comment]
komisch also das Problem hab ich nicht: bei dem Holztransporter musste ich die Geschwindigkeit reduzieren da er sonst in den Kurven evtl. umkippen würde. Aber wenn du schreibst, dass die Geschwindigkeit noch nicht mal mit  spiel eigenen Tempomat einstellbar ist dann würde ich sagen dass irgendwas mit deinem Fahrzeug bzw. Mod  nicht stimmt.

**Comment by Gariot** [comment]
Natuerlich ist sie EINSTELLBAR, meine guete. Der AD fahrer haelt sich schlicht nicht dran. Egal was du in welchen tempomat einstellst. Meine Fahrzeuge sind Vanilla und ich habs auch mit Autodrive only getestet ;)

Wir haben den gleichen Fehler .... 
Ich haeng dir zu liebe sogar mal einen aehnlichen Screenshot dran ;) Er beschleunigt dann uebrigends auch auf ~62/63, hab nur nen augenblick frueher das foto geknippst. Kommt mir vor als wuerde da irgendwie die Geschwindigkeit komisch be- oder umgerechnet. Wenn man naemlich im AD 40 einstellt, haelt er ziehmlich genau 50km/h
![20200324025428_1](https://user-images.githubusercontent.com/18175983/77380384-37a22680-6d7b-11ea-9f4b-9dd59c829ad6.jpg)

**Comment by Iwan1803** [comment]
Ich habe das gleiche Problem mit Standardfahrzeugen. Ein Trecker ist in AD auf 60km/h begrenzt, aber er beschleunigt dennoch auf sein max. von 63km/h.
In AD habe ich nichts verändert.

**Comment by Michael170978** [comment]
@Gariot siehe ich genau so zu Zeit gibt bei allen Fahrzeugen eine kleine Abweichung.

**Comment by Iwan1803** [comment]
-> https://github.com/Stephan-S/FS19_AutoDrive/issues/1238
