### ISSUE TITLE
[BUG]MP kein löschen und umbennen mehr möglich

### ISSUE THREAD

**Issue by Bandesss** [Stephan-S/FS19_AutoDrive#1224]
**AutoDrive Version:** 

AutoDrive | 1.1.0.2
**Release or Custom Zip: von der Zip gepackt
**Map (If applicable):** Oberthal
**Vehicle / Type (If applicable):**   
**Multiplayer or Singleplayer:**Mp

Hallo zusammen, leider lassen sich die Zielpunkte auf dem Server nicht umbennen oder löschen.
Ich kann neue erstellen aber keine vorhanden löschen.
Wir spielen auf einem Dedi Server.

[AutoDrive_Oberthal_config.zip](https://github.com/Stephan-S/FS19_AutoDrive/files/4374387/AutoDrive_Oberthal_config.zip)

**Comment by Justice-Molton** [comment]
Das geht auf unserem Dedicated Root ohne Probleme.

**Comment by Bandesss** [comment]
Schade ist das ich euch keine Log stellen kann.
Es sind keine Fehler vorhanden

**Comment by Iwan1803** [comment]
Willi und ich haben uns das vorhin live angesehen. 
Das Löschen und Erstellen von Wegpunkten sowie das Erstellen von Zielpunkten funktioniert fehlerfrei. Allerdings können Zielpunkte nicht gelöscht oder umbenannt werden. Dabei ist es auch egal, ob der Ziel nach dem Serverneustart schon vorhanden war oder ein neuer erstellt worden ist.
Die Console war zu jeder Zeit fehlerfrei.

**Comment by Stephan-S** [comment]
@TyKonKet Can you please check the renaming and deletion of destinations in MP?
The remaining functions are reported to work fine, but these two apparently don't work yet.
Thank you :-)

**Comment by Bandesss** [comment]
Vielleicht am besten mit der Config von mir ?
Vielleicht liegt dort der Fehler ?

**Comment by TyKonKet** [comment]
@Stephan-S @Bandesss 
I'm sorry, I can't reproduce this issue.
I tried on a dedicated server and everything works for me.

**Comment by Iwan1803** [comment]
Maybe it's because of that "special" map or as somebody else has created that XML?

**Comment by Bandesss** [comment]
Hmm bei mir geht's immer noch nicht komplett neu gemacht. Kurse runtergeladen entpackt und hoch geladen

**Comment by Iwan1803** [comment]
Problem war übrigens ein Schreibschutz auf dem Savegame-Ordner.
