### ISSUE TITLE
[FEATURE REQUEST] 2nd park button/option

### ISSUE THREAD

**Issue by Bobster82** [Stephan-S/FS19_AutoDrive#1225]
Hi devs,

I would like to see a 2nd parking button if this is not a big deal/problem.

Why?:
Im using a lot of vehicles and park them a lot in different places, I also park tools/trailers in different locations. 

My request: 1 button for the destination where i store my tools/trailers and 1 button for the vehicle park place. 
When courseplay is done working and the option parking is enabled, the vehicle drives to the 1st parking place(1st button), tools/trailer parking place, then i manually reverse or put them in place... then click the 2nd button for the vehicle park place, so i dont have to scroll down the menu all the time and I cant remember all park places :P 

This would help me organize big time, thanks ;)

**Comment by NurPech** [comment]
I also want to use this function. I also parking my trailers and tools at another place than my vehicles. Currently I send them to the parking place for the attachment and then I let AutoDrive driving the vehicle to the desired vehicle's parking place.

As this is a workaround for me, I would be very happy to implement this proposal.

**Comment by Iwan1803** [comment]
With 1.1.0.5-RC5 you can assign parking slots to attachments and trailers.
