### ISSUE TITLE
problem with unloader / Problem mit Abfahrern

### ISSUE THREAD

**Issue by steven1134** [Stephan-S/FS19_AutoDrive#1226]
AutoDrive Version: 1.1.0.2
Release or selbsterstelltes zip: Release
Karte (falls relevant): Alle
Fahrzeug(art) (falls relevant):Alle abfahrer beim mais häcksel

**Beschreibe den Bug**
wenn ein abfahrer die spur nicht mehr findet bzw berechenet fährt der abfahrer zum zielpunkt aber löscht sich nicht aus dem häcksler, also häcksler oder abfahrer weis nicht genau wehr. er behält immer noch denn selben abfahrer oder häcksler eingelesen, kann man aber auch an meinen screenshots sehen. der claas wartet und wartet und waret auf ruf, und der john dir der abgebrochen hat und denn zielpunkt nochmal neu angefahren hat, fährt er direkt los zum häcksler

**Falls anwendbar - Schritte mit denen ich den Bug nachstellen kann**

**Screenshots**
![fsScreen_2020_03_24_13_34_00](https://user-images.githubusercontent.com/62439666/77426827-93999900-6dd5-11ea-884a-0018ea3bd638.png)
![fsScreen_2020_03_24_13_34_37](https://user-images.githubusercontent.com/62439666/77426838-985e4d00-6dd5-11ea-8c31-0036047c8e20.png)

**Comment by Iwan1803** [comment]
Auf gut deutsch:
Wenn ein Abfahrer den Weg zum Drescher oder Häcksler nicht finden konnte und daher zum Startpunkt zurückkehrt, möchte der Drescher oder Häcksler immer noch diesen rufen anstatt einen anderen, welcher bereit steht.

Abfahrer fahren nicht von alleine zum Startpunkt zurück, wenn sie den Weg nicht finden/berechnen konnten. Also hast du AD beendet und neugestartet, so das er nun zum Startpunkt zurückgekehrt ist. Und soll der Häcksler oder Drescher immer noch den falschen Abfahrer rufen?

**Comment by steven1134** [comment]
der abfahrer hat keinen weg mehr zum häcksler gefunden (john deere) dann fuhr er zurück zum anfang in demm zeitraum sollte eigentlich der axion an der reihe sein aber der drescher sagt demm john deere warscheinlich immer noch das er kommen soll sobald er wieder am abfahrpunkt ankommt anstadt denn axion zu rufen

**Comment by steven1134** [comment]
ich vermute das ein Fehler in der datei is das der häcksler sobald der abfahrer weg fährt und noch nicht voll is also zurück zum abfahpunkt fährt der häcksler keinen neuen unloader anfängt zu rufen weil der john deere noch nicht voll is bzw seib abfahrlevel ereicht hat

**Comment by Iwan1803** [comment]
Du hast AD also nicht beendet?

**Comment by steven1134** [comment]
doch

**Comment by Iwan1803** [comment]
-> https://github.com/Stephan-S/FS19_AutoDrive/issues/1238
