### ISSUE TITLE
[BUG][MP] Ablade Punkt mit Fass wird ignoriert

### ISSUE THREAD

**Issue by Crykor90** [Stephan-S/FS19_AutoDrive#1227]
AutoDrive Version: 1.1.0.2
Release or selbsterstelltes zip: Release
Karte (falls relevant): Oberthal
Fahrzeug(art) (falls relevant): LKW mit Fassauflieger / Traktor mit Fass

**Beschreibe den Bug**
Bei mir wird der Abladepunkt ignoriert und es wird einfach drüber gefahren beim Modus Abholen und Abliefern

**Falls anwendbar - Schritte mit denen ich den Bug nachstellen kann**
Gerne mich im Discord kontaktieren kann es per Stream zeigen
Crystep / Manu#7882

**Screenshots**
Falls relevant, bitte Screenshots beifügen

**Comment by Iwan1803** [comment]
-> https://github.com/Stephan-S/FS19_AutoDrive/issues/1238
