### ISSUE TITLE
[BUG] Pickup and Delivery mod Warning (script): Unknown entity id 270609 in method 'getWorldTranslation'.

### ISSUE THREAD

**Issue by Iab72** [Stephan-S/FS19_AutoDrive#1228]
AutoDrive Version: 1.1.0.2 
 Release  
Map : Eiersholt   

Singleplayer  

**Describe the bug**  
when i want to let the tractor to load and delivery it don't go to load i load it by myself and let it to delivery it stop before  the unloading target 

**Screenshots**  
![fsScreen_2020_03_24_17_26_27](https://user-images.githubusercontent.com/11736318/77450657-44b32a00-6dfc-11ea-847f-76926e72413f.png)

[log.zip](https://github.com/Stephan-S/FS19_AutoDrive/files/4376414/log.zip)
![fsScreen_2020_03_24_17_26_27](https://user-images.githubusercontent.com/11736318/77450834-82b04e00-6dfc-11ea-8aa8-4e442229e7f5.png)

**Comment by Iwan1803** [comment]
-> https://github.com/Stephan-S/FS19_AutoDrive/issues/1238
