### ISSUE TITLE
Fahrzeug fährt durch Umwege zum Ziel

### ISSUE THREAD

**Issue by Michael170978** [Stephan-S/FS19_AutoDrive#1229]
Hi

Ich stehe vor einem Problem den ich alleine nicht lösen kann.

Könnt ihr mir bitte sagen warum mein Fahrzeug durch Umwege zum Ziel fährt

![Unbenannt](https://user-images.githubusercontent.com/53015927/77452214-f7cc5500-6df5-11ea-92e9-be61db6f4dac.png)

Roter Pfad ist wo mein Fahrzeug zur Zeit fährt.
Blauer Pfad ist wo er eigentlich fahren sollte.

Kann es sein, dass meine Einstellungen falsch sind?

![1](https://user-images.githubusercontent.com/53015927/77452258-0450ad80-6df6-11ea-8f1b-177f55d1bd2c.png)

**Comment by Michael170978** [comment]
Irgendwie kann ich keine Bilder einfügen

**Comment by Iwan1803** [comment]
Sind auf der blauen Linie vielleicht Zielpunkte? Immerhin hast du ihm gesagt, das er 1.000m Umweg fahren darf (um Zielpunkte nicht überfahren zu müssen).

**Comment by Stephan-S** [comment]
Und Schnellste Strecke bevorzugen kann je nachdem auch zu längeren Strecken führen, wenn er davon ausgeht, dass er dort schneller (weniger scharfe Kurven) fahren kann.
Mal ganz abgesehen davon, dass die Strecken ja wirklich nicht so weit auseinander liegen, was ihre Länge angeht :D

**Comment by Michael170978** [comment]
@Stephan-S  da hast du recht. Nur im Moment fährt über  Waldwege Milch holen. Und das ist komplett sin befreit. Das ist ein Milchtransporter. Deshalb möchte ich, dass er die Hauptwege benutzen soll.

@Iwan1803 Ich schau dass ich 1.000m lösche und mehre Zielpunkte aktiviere. Dann hoffe ich das es dann klappt

**Comment by kaufm30** [comment]
@Iwan1803 Bei mehrere Zielpunkte fährt er alle Ziele im jeweiligen Ordner an

**Comment by Iwan1803** [comment]
Das weis ich und ich habe auch nicht vorgeschlagen, das er das aktivieren soll.

**Comment by kaufm30** [comment]
> 
> 
> Das weis ich und ich habe auch nicht vorgeschlagen, das er das aktivieren soll.

Ich habe nicht dich gemeint. Die Zitierung deines Namens war nur ein Hinweis für Michael170978

**Comment by Michael170978** [comment]
Ich hab keine Ziele im Ordner. Der Lkw hat die Anweisung bekommen Milch vom Kuhstall in die Milchwerke zu bringen. Und er macht die Sache auch gut. Das einige was mich stört das ist, dass er über Waldwege fährt. Aber Iwan hat schon oben ein paar Tipps gegeben. Die werde ich auch umsetzten und schau ob es besser geworden ist.

**Comment by Zerberrus** [comment]
Setzte einfach ein Zielpunkt in die Feldwege! Da ich mal davon ausgehe, das auf den Hauptstrecken keine Zielpunkte sind, wird er die dann bevorzugen! solange er unter dem 1Km Umweg bleibt! Klappt bei mir bestens, keine Hauptstraße mehr mitten auf dem Hof!
