### ISSUE TITLE
auto drive and ai traffic

### ISSUE THREAD

**Issue by fudoido** [Stephan-S/FS19_AutoDrive#123]
Hello stephan.
wondering if it could be implemented a way to detect traffic and make vehicles running auto drive to slow down behind traffic?
since auto drive is a tool mostly used for single player games, most like me like to use traffic for a litle more realism, and i noticed that a vehicle running auto drive hits the back of traffic in the roads.
would this be something possible to do?

**Comment by Experience95** [comment]
Also if you take control over a vehicle again which was controlled by Autodrive, AI Traffic thinks that the vehicle which was controlled by autodrive still is in that position, which leads to massive traffic jams.

![fsScreen_2019_05_21_13_37_34](https://user-images.githubusercontent.com/44814879/58095957-4f95a080-7bd4-11e9-9f85-f72fa116834f.png)

**Comment by fudoido** [comment]
noticed on a diferent map that traffic stops near the vehicles with autodrive. when i posted initially, using autodrive on the previous map (both mod maps), they were running and autodrive was hiting them on the back. dont know what makes these differences.
I do know that traffic also stops with vehicles under courseplay control, even if the controlled machinery is behind the ai traffic.
Seems to be a issue from giants, not sure if it can be solved, posted tis kind of issue on courseplay github and they marked the issue as postponed, unsure if there is a solution for ai traffic stopping for autodrive/courseplay controlled vehicles.
On fs17, courseplay would detect ai traffic speed and slow down to adjust to ai traffic, ai traffic would not stop like it does now on fs19.

**Comment by Anonymous-any** [comment]
https://github.com/Stephan-S/FS19_AutoDrive/issues/79

**Comment by Stephan-S** [comment]
Hey everybody,

once again, I can only state that there is really not much I can do.
@fudoido already has the right conclusion. Giants ai traffic system doesn't work with helper controlled vehicles on the road.
And if i switch of the  simulated helper, I run into many other difficulties.
So, no solution for now.
I keep this issue open with the hope that it stops new issues being opened on the same topic for now.
