### ISSUE TITLE
 unload the thresher and drive off mode / driver with transfer vehicle[BUG]

### ISSUE THREAD

**Issue by steven1134** [Stephan-S/FS19_AutoDrive#1230]
AutoDrive Version: 1.1.0.2
Release or selbsterstelltes zip: Release
Karte (falls relevant): Alle
Fahrzeug(art) (falls relevant):drescher abfahren überladewagen

**Beschreibe den Bug**
1.überlade abfahrer wartet nicht am zielpunkt sondern fährt die ganze zeit weiter gradeaus
2.nach demm abladen macht er nichts mehr

**Falls anwendbar - Schritte mit denen ich den Bug nachstellen kann**

**Screenshots**
1.
![fsScreen_2020_03_24_19_32_37](https://user-images.githubusercontent.com/62439666/77465229-995ca200-6e08-11ea-859f-f08016ca50d3.png)
2.
![fsScreen_2020_03_24_19_50_43](https://user-images.githubusercontent.com/62439666/77465495-fd7f6600-6e08-11ea-8a74-a273b9516e0c.png)

**Comment by Iwan1803** [comment]
-> https://github.com/Stephan-S/FS19_AutoDrive/issues/1238
