### ISSUE TITLE
[BUG] Abfahrer bleibt nach entladen stehen -  Driver stops after unloading; 

### ISSUE THREAD

**Issue by Pipel19** [Stephan-S/FS19_AutoDrive#1232]
AutoDrive Version: 1.1.0.2
Release or selbsterstelltes zip: selbsterstelltes zip (heute um 20:00 Uhr)
Karte (falls relevant): NF oG 2.7 glaube aber auf allen
Fahrzeug(art) (falls relevant): alle

 Abfahrer bleibt nach entladen stehen

Abholen und Abliefern einstelln, nach dem entleeren fährt der Fahrer zum Wegpunkt und bleibt dort stehen anstelle nocheinmal neu zum Abholen zu fahren
<img width="1152" alt="Farming Simulator 19 24 03 2020 20_08_05" src="https://user-images.githubusercontent.com/54800262/77469978-3969f980-6e10-11ea-948e-7ce83ab2768c.png">

**Comment by markussinner** [comment]
Selbes Problem hier, nur im Modus "Abladen". Autodrive bleibt aktiviert, Meldung kommt nicht.

**Comment by Marko230** [comment]
Gleiches Problem wie bei Pipel19 /  markussinner

**Comment by steven1134** [comment]
selbes problem bei drescher abtanken und abfahren

**Comment by Pipel19** [comment]
Funktioniert im letzten build, danke nochmal :-)
