### ISSUE TITLE
Combine Offload issue, Truck not driving to combine[BUG]

### ISSUE THREAD

**Issue by Tadeloach** [Stephan-S/FS19_AutoDrive#1233]
**AutoDrive Version:** 1.1.0.2-3 
**Release or Custom Zip:** Release  
**Map (If applicable):** All  
**Vehicle / Type (If applicable):**   Any Combine and Truck and trailer setup
**Multiplayer or Singleplayer:** Singleplayer  

**Describe the bug**  
When the combine calls for offload, the truck receives the call, but sticks with the message above the HUD, planning path.  Pathfinder set to .25.  I cant get him to go to the combine.

**If applicable - Steps to reproduce the behavior**  
Setup a combine and unloader for a field, watch when unloader is called.  
**Screenshots**  
![image](https://user-images.githubusercontent.com/56048034/77496210-733efe00-6e18-11ea-9226-82427c4a7dbc.png)

**Comment by Iwan1803** [comment]
-> https://github.com/Stephan-S/FS19_AutoDrive/issues/1238
