### ISSUE TITLE
Problems with automatic refueling in connection with CP/ Probleme mit automatischen Tanken des in Verbindung mit CP

### ISSUE THREAD

**Issue by Fuzzy86** [Stephan-S/FS19_AutoDrive#1234]
AutoDrive Version: 1.1.0.2
Release or selbsterstelltes zip: Release
Karte (falls relevant): Alle
Fahrzeug(art) (falls relevant):

**Beschreibe den Bug**
Wenn bei der Feldarbeit (mit CP) der Diesel ausgeht übergibt er an AD und fährt zur nächsten Tankstelle. Das funktioniert perfekt und er füllt den Tank auch auf jedoch übergibt er gleich nach der Befüllung an CP und kommt somit nicht mehr zurück ins Feld.

**Comment by Iwan1803** [comment]
-> https://github.com/Stephan-S/FS19_AutoDrive/issues/1238
