### ISSUE TITLE
[BUG] [MP] Waypoint sort

### ISSUE THREAD

**Issue by Crykor90** [Stephan-S/FS19_AutoDrive#1235]
AutoDrive Version: 1.1.0.2
Release or selbsterstelltes zip: Release
Karte (falls relevant): Oberthal
Fahrzeug(art) (falls relevant):

**Beschreibe den Bug**
Zielpunkte lassen sich nicht in Ordner verschieben.

Rückfragen gern per Discord Crystep / Manu#7882 kann es euch auch im Livestream zeigen

**Falls anwendbar - Schritte mit denen ich den Bug nachstellen kann**

**Screenshots**
Falls relevant, bitte Screenshots beifügen

**Comment by Bandesss** [comment]
Soviel ich weiss geht das im Multiplayer nicht

**Comment by Iwan1803** [comment]
-> https://github.com/Stephan-S/FS19_AutoDrive/issues/1238
