### ISSUE TITLE
Unloading Case Ausoft 8800 problem

### ISSUE THREAD

**Issue by masneoquil** [Stephan-S/FS19_AutoDrive#1236]
**AutoDrive Version:** 1.1.0.2   
**Release or Custom Zip:** Release  
**Map (If applicable):** All  
**Vehicle / Type (If applicable):**  Case Ausoft 8800 
**Multiplayer or Singleplayer:** Singleplayer  

**Describe the bug**  
Don't know if it is a Bug, but the driver don't get close enough to "unload" de sugarcane harvester.
I tried different settings for the pipe offset option without success.

**Screenshots**  
![AD1](https://user-images.githubusercontent.com/53353740/77541842-04978a00-6e84-11ea-9c01-64adf7c41738.jpg)
![AD2](https://user-images.githubusercontent.com/53353740/77541844-05c8b700-6e84-11ea-8147-d1161d10ef07.jpg)
![AD3](https://user-images.githubusercontent.com/53353740/77541849-07927a80-6e84-11ea-8652-85ca367dde8e.jpg)

**Comment by Iwan1803** [comment]
-> https://github.com/Stephan-S/FS19_AutoDrive/issues/1238
