### ISSUE TITLE
[BUG] Trailers not unloading

### ISSUE THREAD

**Issue by Krzemien97** [Stephan-S/FS19_AutoDrive#1237]
**AutoDrive Version:** 1.1.0.2-3   
**Release or Custom Zip:** Release  
**Map (If applicable):** All  
**Vehicle / Type (If applicable):**   Trailers
**Multiplayer or Singleplayer:** Singleplayer  

**Describe the bug**  
Hi, I have problem with unloading any trailers. When I tell AD to deliver crops to Railroad silo (Felsbrunn), driver just goes there and sits at waypoint. He can be manually offloaded and then AD finishes course.  I had the same problem with 1.1.0.2 but updated hoping it will solve this issue.

- No errors in console.
- Tested that on new save with only AD enabled - same result. 
- Tested on normal sellpoint - same result.
- Tested multiple trailers (from vanilla) - same result.

**If applicable - Steps to reproduce the behavior**
-

**Screenshots**  
-

**Comment by Iwan1803** [comment]
-> https://github.com/Stephan-S/FS19_AutoDrive/issues/1238
