### ISSUE TITLE
[BUG][MP] Trailers cannot be loaded 

### ISSUE THREAD

**Issue by Crykor90** [Stephan-S/FS19_AutoDrive#1239]
AutoDrive Version: 1.1.0.2
Release or selbsterstelltes zip: Release
Karte (falls relevant): Alle
Fahrzeug(art) (falls relevant): Anhänger mit Plane

**Beschreibe den Bug**
Durch Autodrive lassen sich Anhänger mit Plane manchmal nicht beladen (Plane geöffnet) - man muss die Plane schließen und wieder öffnen um den Fehler zu beheben.

**Falls anwendbar - Schritte mit denen ich den Bug nachstellen kann**

**Screenshots**
Falls relevant, bitte Screenshots beifügen

**Comment by Iwan1803** [comment]
-> https://github.com/Stephan-S/FS19_AutoDrive/issues/1238
