### ISSUE TITLE
Vehicle cannot find its way in the middle of the field even though the field is surrounded by a road network  - Fahrzeug findet mitten auf dem Feld keinen Weg. obwohl das Feld von einem Streckennetz umgeben ist

### ISSUE THREAD

**Issue by haamic** [Stephan-S/FS19_AutoDrive#1240]
AutoDrive Version: 1.1.0.2-3
Release or selbsterstelltes zip: zip
Karte (falls relevant): Alle
Fahrzeug(art) (falls relevant):

**Beschreibe den Bug**
Ich hatte ein Feld gedüngt und stand mitten im Feld. Wollte zum nächsten Feld starten, aber das Fahrzeug findet keinen Weg. Obwohl das Feld von einem Streckennetz umgeben ist. Zum Test hab ich mal das Massband angeschalten und bis zu ca. 30m Entfernung zum Streckennetz wird **kein** Weg gefunden.  Nur unterhalb dieser ca. 30m findet er seinen Weg. Kann der Suchradius vergrössert werden, vielleicht als änderbarer Menüeintrag?
++++++++++++++++++++++++++++++++
I had fertilized a field and was standing in the middle of the field. I wanted to start to the next field, but the vehicle couldn't find a way. Even though the field is surrounded by a network of tracks. For the test I turned on the tape measure and up to a distance of about 30m to the track network **no** way is found.  Only below this approx. 30m distance it finds its way. Can the search radius be enlarged, maybe as a changeable menu item?

**Falls anwendbar - Schritte mit denen ich den Bug nachstellen kann**

**Screenshots**
![abstand](https://user-images.githubusercontent.com/28841989/77630102-d0d36780-6f4a-11ea-97f9-e6732b23373b.jpg)

**Comment by Iwan1803** [comment]
-> https://github.com/Stephan-S/FS19_AutoDrive/issues/1238
