### ISSUE TITLE
[BUG] Vehicle finishes journey during automatic refuelling at the petrol station, with the message Destination reached - Fahrzeug beendet Fahrt beim automatischen Tanken an der Tankstelle, mit der Meldung Ziel erreicht.

### ISSUE THREAD

**Issue by haamic** [Stephan-S/FS19_AutoDrive#1241]
AutoDrive Version: 1.1.0.2-3
Release or selbsterstelltes zip: Release
Karte (falls relevant): Alle
Fahrzeug(art) (falls relevant):

**Beschreibe den Bug**
Fahrzeug beendet Fahrt beim automatischen Tanken an der Tankstelle, mit der Meldung Ziel erreicht.
In meinem Fall wollte ich ein Fahrzeug zu seiner Parkposition schicken.  EVtl. selbes Verhalten bei anderem Ziel. Das Fahrzeug fuhr auf die Parkposition, es erfolgte keine Meldung , Ziel erreicht. Es hielt aber nicht an. Es fuhr weiter.... Warum war mir erst nicht klar, dann sah ich aber das der Treibstoff knapp war. Das Fahrzeug fuhr also zur Tankstelle. Der Hinweis im AD-HUD hatte ich nicht wahrgenommen. Dort angekommen, kam die Meldung das es an der Parkposition angekommen wäre und tankte auf. Drehte noch eine Runde zur Tankposition ,dann war Schluss. (siehe video)
Also eine unübersehbare Meldung, das der Weg jetzt zur Tankstelle gestartet wurde, wäre schön wenn das irgendwie realisiert werden könnte. Vielleicht so wie beim Ziel erreicht, solange bis aufgetankt wurde auf dem Hauptbildschirm.  Ausserdem sollte es nach dem Auftanken zum eigentlichen Ziel zurückfahren und nicht an der Tankstelle die Fahrt mit der falschen Meldung beenden. Habe es nochmal nachgestellt und anbei Screenshot + 
Video (Wiedergabe im Player unscharf, heruntergeladen ok) und log mit debug-informationen.  (unnötige **"Info: nil"** gekürzt, da Fahrt zum Tanken 6min)
++++++++++++++++++++++++++++++++++++++++
Vehicle finishes journey during automatic refuelling at the petrol station, with the message Destination reached.
In my case I wanted to send a vehicle to its parking position.  Maybe the same behaviour at another destination. The vehicle drove to the parking position, there was no message , destination reached. But it did not stop. It drove on... Why I did not understand at first, but then I saw that the fuel was scarce. So the vehicle drove to the gas station. I had not noticed the notice in the AD-HUD. When I arrived there, the message came that it had arrived at the parking position and refuelled. Turned another round to the fueling position, then it was over. (see video)
So a conspicuous message that the way to the gas station has now been started would be nice if this could be realized somehow. Maybe like the destination reached, as long as the main screen is filled up.  Furthermore it should drive back to the actual destination after refuelling and not end the journey with the wrong message at the petrol station. I have readjusted it again and attached screenshot + 
Video (playback in player blurred, downloaded ok) and log with debug information.  (unnecessary **"Info: nil "** shortened, because drive to refuel 6min)

**Falls anwendbar - Schritte mit denen ich den Bug nachstellen kann**

**Screenshots**
![Tankt auf](https://user-images.githubusercontent.com/28841989/77640146-2bc08b00-6f5a-11ea-9c41-7e1501d4338d.jpg)

![nochmal zum Tankpunkt](https://user-images.githubusercontent.com/28841989/77640170-35e28980-6f5a-11ea-8a8c-2432148e62c6.jpg)

![Ende](https://user-images.githubusercontent.com/28841989/77640228-50b4fe00-6f5a-11ea-9e40-9b9189fe3504.jpg)

https://www.dropbox.com/s/v26iqbtbpgk38cy/Farming%20Simulator%2019%202020-03-26%2011-41-56.mp4?dl=0

[tanken-log.txt](https://github.com/Stephan-S/FS19_AutoDrive/files/4386770/tanken-log.txt)

**Comment by Iwan1803** [comment]
-> https://github.com/Stephan-S/FS19_AutoDrive/issues/1238
