### ISSUE TITLE
[BUG]driver does not drive to the combine harvester

### ISSUE THREAD

**Issue by GE-Mapping** [Stephan-S/FS19_AutoDrive#1242]
AutoDrive Version: 1.1.0.1
Release or selbsterstelltes zip: Release
Karte (falls relevant): Alle
Fahrzeug(art) (falls relevant):

**Beschreibe den Bug**
Seit Version 1.1.0.1 fährt der Abfahrer nicht mehr zum Drescher auf dem Feld.
KrampeKS 950 mit Plane kommt nur Meldung: "Fahrer wird gerufen"
Wenn man die Plane schließt und wieder öffnet kommt Meldung: "Pfad wird berechnet"
Diese Meldung geht nicht mehr weg.
Bei Auflieger ohne Plane (Fliegl ASS 298) bleibt die Meldung: "Pfad wird berechnet"
Auch mit Traktor und Anhänger fährt er nicht zum Drescher,nachdem er gerufen wird.

Zum anderen sind ab der Version alle Einträge verschoben, bzw nicht mehr sortiert. Lassen sich auch nicht verschieben, dass wiederalles sortiert ist

**Falls anwendbar - Schritte mit denen ich den Bug nachstellen kann**

**Screenshots**
Falls relevant, bitte Screenshots beifügen

**Comment by Bandesss** [comment]
Ihr sollt wenn ihr keine Probleme haben wollt diese Version nutzen 1.0.7.2

**Comment by GE-Mapping** [comment]
Diese Version 1.0.7.2 Funktioniert. Ist wieder als Mod im Moment im Ordner

**Comment by Iwan1803** [comment]
-> https://github.com/Stephan-S/FS19_AutoDrive/issues/1238
