### ISSUE TITLE
[FEATURE REQUEST] Vehicles meeting on two lane road and stopping work around.

### ISSUE THREAD

**Issue by Tadeloach** [Stephan-S/FS19_AutoDrive#1243]
**Is your feature request related to a problem? Please describe.**
When vehicles meet on two lane roads with seperate green ad lines, they sit there with no notification that they are in traffic.

**Describe the solution you'd like**
1.  Could autodrive be programed that when vehicles meet head to head to offset to one side or the other to make room to pass each other?
2.  If option one is impossible, can we have a pop up message that they are in traffic?

**Describe alternatives you've considered**
I usually jump in one of the vehicles, turn ad off, drive around the other vehicle, then restart ad.

**Additional context**

**Comment by Stephan-S** [comment]
Why are you not using blue lines for this purpose?
A pop up message is a bit tricky since you might get a lot of false positives when there is legitimate blocking due to high traffic at loading triggers/field waypoints etc.

**Comment by Tadeloach** [comment]
I thought the purpose of blue lines was for small roads that do not have
two lanes, not high ways....  I have noticed so far in the newest release
that they are not stopping when meeting on two lane roads.  (IE: One lane
of green lines going north, one lane south)

**Comment by Iwan1803** [comment]
Maybe a message after 2 or 3 minutes, if an AD driver is blocked....
