### ISSUE TITLE
[FEATURE REQUEST] Wider vehicle offset while driving down roads

### ISSUE THREAD

**Issue by Tadeloach** [Stephan-S/FS19_AutoDrive#1244]
**Is your feature request related to a problem? Please describe.**
Wider vehicles like combines and wide implements hit objects on the side of roads and hang with no notification that they are stuck.

**Describe the solution you'd like**
1. Could an offset from the green lines be introduced to be set for each vehicle that will run slightly to one side or the other of the green lines to keep from hitting objects on the side of roads?
2. If option 1 is impossible, can we get a message letting us know vehicles are stuck?

**Comment by Bobster82** [comment]
Or use the multiple color line and set what lines can be used in settings per vehcile as requested before... but I dont think the devs see a added value to that ;) So every "improvement" to use "bigger" vehicles or tools is a welcome feature.

**Comment by Tadeloach** [comment]
Like drive all roads down the middle with purple lines, even the two lanes,
and restrict the combines etc to purple lines?

**Comment by Iwan1803** [comment]
Dodging is complicated, but perhaps a message would suffice if an ad driver is blocked: https://github.com/Stephan-S/FS19_AutoDrive/issues/1243
