### ISSUE TITLE
Synchro Version 1.0.7.2; Synchronisation [FEATURE REQUEST]

### ISSUE THREAD

**Issue by Moitzbert** [Stephan-S/FS19_AutoDrive#1245]
How can I snchronise the routes in the new version ??
Wie kann ich die Kurse in der neuen Version synchronisieren ?

**Comment by TyKonKet** [comment]
Routes are automatically synchronized in MP.

**Comment by Moitzbert** [comment]
In singleplayer as well ? 
I'm playing solo.

**Comment by TyKonKet** [comment]
what do you mean with "snchronise the routes"

**Comment by Moitzbert** [comment]
in the older version: right beside the record butten was the "recalculate" button, or synchronise..

**Comment by TyKonKet** [comment]
oh, now I can understand what do you mean, you don't have recalculate anymore.

**Comment by Moitzbert** [comment]
ok recalculate was the word.

**Comment by Moitzbert** [comment]
thanks for the quick support!
