### ISSUE TITLE
[BUG] Problems with speed in curves

### ISSUE THREAD

**Issue by Matzenie** [Stephan-S/FS19_AutoDrive#1248]
AutoDrive Version: 1.1.0.2
Release or selbsterstelltes zip: Pre-Release
Karte (falls relevant): Alle (Nf Marsch 4fach)
Fahrzeug(art) (falls relevant): Alle Fahrzeuge mit hohem Schwerpunkt 

Trotz reduzierter Kurvengeschwindigkeit auf 50% fahren die Fahrzeuge mit recht hoher Geschwindigkeit in die Kurven. Und abhängig vom Schwerpunkt fliegen sie häufig aus der Kurve. Sie fallen auch gerne mal auf die Seite.

Nachstellung z.b. MAN Sattelauflieger mit Holzanhänger. Den halt voll auf eine Gerade mit einer Kurve am Ende.

**Screenshots**
Nicht vorhanden

**Comment by Stephan-S** [comment]
Bitte auf 1.0.7.2 bleiben oder den neuesten Release-Candidate 1.1.0.3-1 nutzen :-)

**Comment by Iwan1803** [comment]
Bitte auf Release-Candidate 1.1.0.3-2 aktualisieren und erneut probieren.

**Comment by Michael170978** [comment]
Das Problem besteht nach wie vor. Nur mit der hohen Geschwindigkeit stimmt nicht so ganz. Wenn man die Kurveneschwindigkeit auf 50% reduziert dann reduziert man gleichzeitig die Höchstgeschwindigkeit. Somit erreichen die Fahrzeuge auf geraden Strecken Ihre Höchstgeschwindigkeit nicht mehr.

**Comment by Flashmaster23** [comment]
Ich kann den Fehler bestätigen. Auch mit dem RC 1.1.0.3-2
Gerade LKW mit hoher Geschwindigkeit fliegen regelrecht aus der Kurve :)

P.S. Danke für Eure Arbeit. AD finde ich großartig und ich freue mich auf die nächsten Versionen

**Comment by Michael170978** [comment]
Also das Problem lies mich nicht in Ruhe und hab in der Nacht ein bisschen experimentiert. Und tatsächlich es tut sich was wenn man an der Kurvengeschwindigkeit dreht. Und zwar wenn man die Kurvengeschwindigkeit auf 75% reduziert dann merkt man, dass die Fahrzeuge vor Kreuzungen stärker abbremsen. Lässt man die Kurvengeschwindigkeit auf 100% stehen dann steuert das Fahrzeug fast ungebremst auf die Kreuzung zu. Weiter runter bin ich mit der Einstellung nicht gegangen weil dann fahren die Fahrzeuge auf gerader Strecke langsamer. Bei 75% merkt man den unterschied nicht so stark.

**Comment by Iwan1803** [comment]
-> https://github.com/Stephan-S/FS19_AutoDrive/releases/tag/1.1.0.4
