### ISSUE TITLE
[BUG] Harvester unloading impossible

### ISSUE THREAD

**Issue by Matzenie** [Stephan-S/FS19_AutoDrive#1249]
AutoDrive Version: 1.1.0.2
Release or selbsterstelltes zip: Pre-Release
Karte (falls relevant): Alle (NF-Masch 4fach)
Fahrzeug(art) (falls relevant): 

https://farming-simulator.com/mod.php?lang=de&country=be&mod_id=144878

**Beschreibe den Bug**
Ich weiß nicht warum,  aber der Rohr Abstand bezieht sich nicht mehr auf den Auslass sondern auf die Mitte vom Drescher. damit reichen die max. 5m nicht. Bei 1.0.7.2 geht es ohne Probleme

**Falls anwendbar - Schritte mit denen ich den Bug nachstellen kann*
Einfach nur normal den Drescher anfahren lassen. Habe leider nur den Drescher im Spiel. Aber habe es mit LKW und Traktor Abfahrern getestet, je gleiches Verhalten.

Keine Snips.

**Comment by Stephan-S** [comment]
Bitte auf 1.0.7.2 bleiben oder den neuesten Release-Candidate 1.1.0.3-1 nutzen :-)

**Comment by klth** [comment]
Moin, 

1.1.0.3-1 zeigt ebenfalls das Verhalten was Matzenie beschrieben hat. 

Der Abfahrer fährt nicht mehr unter das Abladerohr des Dreschers. Er fährt an eine Position nahe neben den Drescher. Diese Position ist für ein Häcksler korrekt ist aber nicht für ein Drescher.

**Comment by Stephan-S** [comment]
Dann könnt ihr Mal in den Einstellungen nach dem Rohrabstand schauen. Vermutlich hat sich dieser durch das Update verschoben, da man nun in 5cm Schritten einstellen kann.
Sollte auf ca. +75cm stehen, aber kann je nach Gespann und Drescher natürlich auch anders sein.
Wichtig ist, dass der Wert eingestellt ist, bevor sich der Abfahrer auf den Weg macht

**Comment by klth** [comment]
Ja das war es! Der Wert stand bei mir auf -4,75m. Auf +75cm bzw. auf 0m funktioniert es. 

Wurde das früher anders berechnet? Habe an dem Wert nie etwas eingestellt, oder habe ich gar immer nur Glück gehabt? 

Vielen Dank für deine Super Arbeit.

**Comment by Matzenie** [comment]
Dann teste ich mal mit 1
