### ISSUE TITLE
zwei fragen

### ISSUE THREAD

**Issue by andreasthu** [Stephan-S/FS19_AutoDrive#125]
Hallo Stephan
da hast du aber einen Schönen mod gebaut, habe den in LS17 irgendwie verpasst, aber seit gestern verwende ich ihn in LS19.
zwei fragen hätte ich aber:
1. kann man das autodrive HUD in der größe skalieren?
          ich spiele mit 60% LS19 hud-skalierung und da ist das autodrive kästchen etwas klein.
2. wenn ich beginne einen Kurs aufzuzeichnen, beginnt der nicht irgendwo im nichts, sondern verbindet sich sofort mit dem nächstgelegenen autodrive punkt.

lg
andreas

**Comment by Experience95** [comment]
Ich bin zwar nicht Stephan, aber ich probier mal zu helfen :D
Mit STRG Links, ALT Links und "0" auf dem Numblock kannst du ein Menü aufrufen indem du einstellen kannst ob Start und Endpunkte sich automatisch verbinden sollen.

LG
Experience95

**Comment by Stephan-S** [comment]
Hallo

@Experience95 Danke für das Beantworten von Punkt 2 :-)

zu 1.: Das ist derzeit nicht vorgesehen. Genau dafür gibt es ja die HUD-Skalierung :D 
Alternativ kann ich die sagen wie du es im Skript selber änderst. Eine Option die Skalierung zu ignorieren würde ich aber vorerst nicht intergrieren wollen.
Im Prinzip musst du nur die 4 Zeilen in einer Datei anpassen:

https://github.com/Stephan-S/FS19_AutoDrive/blob/cd55f5cfdf25478f5a3359b1c2490bdeefbff194/FS19_AutoDrive/scripts/AutoDriveHud.lua#L13

jeweils statt dem Aufruf, einfach eine '1' setzen und dann wird die Skalierung ignoriert.
Also
local uiScale = 1

Viele Grüße,
Stephan

**Comment by andreasthu** [comment]
spitze, 
danke an @Experience95 xperience95, hab die optionen nun gefunden
danke an @Stephan-S für die info von "local uiScale = 1"
wenn ich nun z.b. local uiScale = 0.9 oder so setze könnte ich die quasi individuell anpassen?
lg
andreas
super mod
