### ISSUE TITLE
Sloping fields

### ISSUE THREAD

**Issue by krambc** [Stephan-S/FS19_AutoDrive#1252]
I've several problems in sloping fields with the unloading combi mode. I think it's because the field exceeds the max slope for the pathfinding. It's posible to increase this value. Maybe manualy?
I've look several scripts but i've not been able to find the variable slope to change it.

Thanks.

**Comment by aletheist** [comment]
I got you covered #1135. I've got a PR in testing.

**Comment by krambc** [comment]
Ops. Sorry. i've not seen this issue...
Thanks.
I'll wait for the solution.

**Comment by Stephan-S** [comment]
It's actually two very different things you are talking about.
You are correct, that the pathfinder is limiting the allowed slope to about 150% of what the GIANTS AI used in their helper vehicles.
If you want to play around with it, it's actually easy to change in the PathfinderModule.lua.
Just look for the slopeAngle function at the bottom and you will see the 1.5x factor there.

**Comment by krambc** [comment]
Hi @Stephan-S ,
i've looked the PathfinderModule.lua as you sugest. As my programming knowledge is limited, a question arises.
When you talk of the 1.5x factor in the slopeAngle function, do you refer to this? (is the only 1.5 i've found in the PathfinderModule.lua)

`                local shapes = overlapBox(worldPos.x + vectorX / 2, y + 3, worldPos.z + vectorZ / 2, 0, angleRad, 0, length / 2 + 2.5, 2.85, sideLength + 1.5, "collisionTestCallbackIgnore", nil, AIVehicleUtil.COLLISION_MASK, true, true, true)
                hasCollision = hasCollision or (shapes > 0)
`

After reading the code i've suposed that the function that  determinates if a slope is a collision is the following.

`                    if angleBetween > AITurnStrategy.SLOPE_DETECTION_THRESHOLD then
                        hasCollision = true
                    end
`

I think i've to increase the AITurnStrategy.SLOPE_DETECTION_THRESHOLD so that the variable hasCollision = false.

Am I on the right track? In that case you have to modify the code like this  . it is right?

`                    if angleBetween > AITurnStrategy.SLOPE_DETECTION_THRESHOLD * 2 then
                        hasCollision = true
                    end
`

Thanks for all your work with this mod. It's fantastic.

**Comment by aletheist** [comment]
I may have a related issue: On field 11 of Ravenport, there is a steep slope up the eastern side. My unloader frequently thinks this is the best route to get to the AD network for its destination, but it gets stuck going up the hill. When doing this kind of pathfinding, is the slope limiter engaged?

It seems like I need the slope limiter to be more cautious while krambc needs it to be less.

**Comment by Iwan1803** [comment]
Please update to 1.1.0.5-RC5, try again and if the problem still exists, then open a new issue.
*Bitte aktualisiere auf 1.1.0.5-RC5, versuche es erneut und und wenn das Problem weiterhin besteht, erstelle ein neues Issue.*
