### ISSUE TITLE
[BUG] Unloader crashes into back of combine

### ISSUE THREAD

**Issue by aletheist** [Stephan-S/FS19_AutoDrive#1253]
**AutoDrive Version:** 1.1.0.3   
**Release or Custom Zip:** Custom
**Map (If applicable):** All  
**Vehicle / Type (If applicable):**   Large semi with large grain trailer, and a combine.
**Multiplayer or Singleplayer:** Singleplayer  

**Describe the bug**  

When pathfinding to the pipe, the algorithm seem to choose some very tight turns near the combine. This can cause the unloader to jackknife or crash into the back of the combine.

**If applicable - Steps to reproduce the behavior**  

**Screenshots**  

**Proposed Solution**

In a previous iteration of my pipe path-finding patch, I forced a node to be created a full vehicle + trailer length behind the pipe, giving plenty of room for the unloader to complete its turn and get its trailer straight. In the refactor I have not yet been able to find similar variables.

**Comment by aletheist** [comment]
In the old code, I think [this is the relevant portion](https://github.com/aletheist/FS19_AutoDrive/blob/pipe-offset/FS19_AutoDrive/scripts/AutoDrivePathFinder.lua#L97)

**Comment by Stephan-S** [comment]
The problem is that this also makes it harder for the algorithm to find a suitable path when you work on fields with little free room around, since the target is then so far away behind the combine. I already increased the value a bit with the 1.1.0.3 release, so I am a bit surprised that it's such a problem to be honest. Maybe the turn radius isn't properly calculated for the vehicle/trailer combination you are using

**Comment by aletheist** [comment]
I"m going to kick around a heuristic that (I hope) will alleviate that concern. If I can get it working I'll paste it here. Basically, I only want to use the hard coded values as threshold maximums instead of guidelines. Just trying to wrap my head around [this function](https://github.com/Stephan-S/FS19_AutoDrive/blob/master/FS19_AutoDrive/scripts/Modules/PathFinderModule.lua#L76).

**Comment by Stephan-S** [comment]
I always have an open ear on the discord if you want to get some in depth explanations :-) Your input is always welcome

**Comment by aletheist** [comment]
For the record, I'm using the Lizard Hulk and Wilson Pacesetter. it might be that the turn radius is just off, because I'm just getting generally odd pathfinding behavior out of this combo. Can't confirm or deny that it exists elsewhere.

**Comment by aletheist** [comment]
[Here is the diff of what I cooked up](https://github.com/Stephan-S/FS19_AutoDrive/compare/beta-testing...aletheist:length-offset?expand=1).

This is purely gee-whiz and doesn't fix a bug. Maybe it adds some 'flavor' to different vehicles/combos but that's about it.

**Comment by Iwan1803** [comment]
-> https://github.com/Stephan-S/FS19_AutoDrive/releases/tag/1.1.0.4
We can discuss this in Discord 😉
