### ISSUE TITLE
[FEATURE REQUEST] coordinating Combine Unloading with the combine

### ISSUE THREAD

**Issue by BloodyRain2k** [Stephan-S/FS19_AutoDrive#1254]
I don't know why now suddenly, but the combine unloading started working for me and has been very impressive.
But I've noticed an issue that arises with your own fields if you happen to play with crop damage (aka steamrolling them) which is that there's only one direction in which the unloader can reach the combine's pipe without damaging the to-be-harvested crops.

So I was wondering if it'd be possible to make the combine wait with it's pre-call for an unloader, until it reaches a turn where the pipe is on the harvested side on the field (left side for most except the Potato Harvester I think) and then calls the unloader, so there's no risk for crop damage.

As far as I've seen is the crop avoiding working nice, but if the pipe's over not-yet-harvested crops then it would still drive into the crops to get there, damaging them in the process.

**Comment by Iwan1803** [comment]
If you use CP the tresher will be driven to the next line in a parking position so that an unloader can reach him without driving through the fruits.

**Comment by Stephan-S** [comment]
He will only drive into the crop when unloading a 100% filled harvester. He won't do side by side unloading in the fruit. If this is happening, please reopen this and show us screenshots and exactly which fruit in which growthstate is not being treated correctly :-)

**Comment by BloodyRain2k** [comment]
So I assume that means this won't be implemented and I'll be left with it either chasing the harvester forever or driving into the field because the harvester is full and be in the way, and stay there, on the next pass.

**Comment by Iwan1803** [comment]
Without requested informations: how should we support you?

**Comment by BloodyRain2k** [comment]
For starters, where that part of the AD logic is residing, there's a damn lot of script files and not having to look through all of them would already be a help.

**Comment by Iwan1803** [comment]
I'm confused.... 
You started a featuere request, which actually looks more like a question and now you want us to help you understand the scripts?
I don't quite understand your point right now. If I understand it correctly, it's about defuelling the thresher and driving it to an accessible place to unload, isn't it?
