### ISSUE TITLE
[BUG] Abfahrer lädt nicht ab am Silo beim Multiplayer.Sind bei G-Portal also kein gehosteter.Discord Name LS19200PS

### ISSUE THREAD

**Issue by LS19ZM200PS** [Stephan-S/FS19_AutoDrive#1255]
[log.txt](https://github.com/Stephan-S/FS19_AutoDrive/files/4398582/log.txt)

![fsScreen_2020_03_29_11_07_40](https://user-images.githubusercontent.com/62832913/77846251-07acb600-71b5-11ea-98ad-e42152031636.png)
![fsScreen_2020_03_29_11_07_45](https://user-images.githubusercontent.com/62832913/77846253-0c716a00-71b5-11ea-8989-5b27bc426a0f.png)
![fsScreen_2020_03_29_11_16_10](https://user-images.githubusercontent.com/62832913/77846257-12ffe180-71b5-11ea-8191-74b0da4a09f8.png)
![fsScreen_2020_03_29_11_16_15](https://user-images.githubusercontent.com/62832913/77846261-198e5900-71b5-11ea-8006-df8f2f2f5690.png)

Dann fährt er zum Feld zurück und bleibt da stehen und er steht fahre abfahren.
Egal mit welcher Version ich das mache ob 1.0.7.1-13 oder 1.0.7.2 oder 1.1.0.3-2

**Comment by Iwan1803** [comment]
-> https://github.com/Stephan-S/FS19_AutoDrive/releases/tag/1.1.0.4
