### ISSUE TITLE
[BUG] AD stops at Weight Trigger

### ISSUE THREAD

**Issue by andreasthu** [Stephan-S/FS19_AutoDrive#1256]
AutoDrive Version: 1.1.0.3-2
Release or selbsterstelltes zip: selbsterstelltes zip
Karte (falls relevant): Minibrunn
Fahrzeug(art) (falls relevant): alle eigentlich

**Beschreibe den Bug**
Hallo Stephan
ich habe auf der Karte Minibrunn das Problem das der AD-Fahrer vorm Waagentrigger stehenbleibt, wenn "Kollisionserkennung AN" ist. das ist erst seit version 1.1.0.2 oder 1.1.0.3 so.
(bis AD 1.0.7.2 funktionierte es so mit Kollisionserekennung AN)
![fsScreen_2020_03_29_18_24_20](https://user-images.githubusercontent.com/24860501/77854525-2fb70c00-71eb-11ea-93a4-7961a018f2af.png)

hier der Trigger im editor:
![Trigger](https://user-images.githubusercontent.com/24860501/77854534-3e052800-71eb-11ea-95a2-6d6505640dc8.png)
das war am anfang irgendwann auch schon mal, dann habe ich beim waagentrigger den channel5 der collisionsmask entfernt, dann ging es wieder.

**Falls anwendbar - Schritte mit denen ich den Bug nachstellen kann**
mit AD durch den WaageTrigger bei der BGA, Map Minibrunn fahren, Kollisionserkennung AN

**Screenshots**
Falls relevant, bitte Screenshots beifügen
screenshots im Text

lg
andreas

**Comment by Iwan1803** [comment]
Das einfachste wäre: deaktivier die Collision, wenn du den Trigger eh schon im Giants Editor offen hast 😋
Warum da überhaupt eine vorhanden ist, weiß wohl nur der Modersteller, den man natürlich auch kontaktieren könnte, um es generell zu ändern.

**Comment by andreasthu** [comment]
Okay danke, hab nun alle collisions deaktiviert, 
Außer 20, 21 u 22.
Hab das bei  einem anderen waage trigger gesehen.
Funktioniert nun soweit mit Kollisionserkennung an.
Lg
Andreas

**Comment by luxstef** [comment]
Hatte das gleiche Problem auf der Holzer Map. Nach Änderung der Kollision hat es auch hier funktioniert! Danke für den Tip! Stefan
