### ISSUE TITLE
[BUG] Pathfinder Timeout

### ISSUE THREAD

**Issue by aletheist** [Stephan-S/FS19_AutoDrive#1257]
**AutoDrive Version:** 1.1.0.3   
**Release or Custom Zip:** Custom
**Map (If applicable):** Ravenport (probably all)
**Vehicle / Type (If applicable):**   Tractor & Trailer Unloader
**Multiplayer or Singleplayer:** Singleplayer  

**Describe the bug**  
On field 11 of Ravenport, if a combine unload happens on the eastern portion of the field, and I have the unloader set to park at a point on the southwestern portion, the pathfinder for parking frequently times out. Moving closer to the parking point manually clears the condition.

**Comment by Iwan1803** [comment]
-> https://github.com/Stephan-S/FS19_AutoDrive/releases/tag/1.1.0.4
