### ISSUE TITLE
[BUG]"Could not calculate path" combined with Courseplay

### ISSUE THREAD

**Issue by Rumspringa90** [Stephan-S/FS19_AutoDrive#1259]
AutoDrive Version: 1.1.0.3-2
Release or selbsterstelltes zip: Release candidate
Karte (falls relevant): NF Marsch 4-fach
Fahrzeug(art) (falls relevant):

**Beschreibe den Bug**
Wenn Courseplay einen leeren Miststreuer oder Düngerstreuer o.ä. meldet, und dort eingestellt ist, das er mit AD auffüllen soll, dann kommt eine meldung das kein Pfad berechnet werden konnte. 
2020-03-30 18:01   Error: [AutoDrive] Could not calculate path - shutting down
2020-03-30 18:01   Error: [AutoDrive] Could not calculate path - shutting down
2020-03-30 18:01   Error: [AutoDrive] Could not calculate path - shutting down

Wenn ich CP ausschalte und AD manuell aktiviere, dann findet er allerdings einen Pfad.

Dazu muss ich sagen, das mir das bisher so ungefähr nur in der Mitte eines etwas größeren Feldes (Feld 02 der NF Marsch 4-Fach)aufgefallen ist. Um das Feld habe ich eine AD Strecke eingefahren und eingestellt "Feldausfahrt nächstgelegener".

**Comment by Stephan-S** [comment]
Kommt dann wohl darauf an wo der nächstgelegene Punkt liegt. Also der auch im Editor Modus mit der roten Linie angezeigt wird. Da will er hin wenn du ihn manuell startest. Über CP fährt er allerding den Feldzielpunkt an der oben eingestellt ist. Ist der nicht gut erreichbar über die Pfadplanung? Inbesondere muss von dort auch ein Weg zum Abladeziel direkt führen.

**Comment by Rumspringa90** [comment]
tut mir leid, das hab ich jetzt nicht ganz verstanden. 
Wenn ich ihn manuell starte, fährt er zu dem Punkt der mit der riten Linie markiert ist. Da wird ja vermutlich auch kein Pfad berechnet sonder da fährt er direkt drauf zu.

Was ist denn aber der Feldzielpunkt? Ist das der den ich in AD einstellen muss? Also in meinem Fall der, der zu Feld 02 führt z.b. "Abf.Feld02"? (dann meinst du mit oben eingestellt im AD Fenster das obere Auswahlfeld) 

Und wenn ich das jetzt doch richtig verstanden habe, versucht er nach CP dann einen Pfad zu diesem Punkt "Abf.Feld02" zu berechnen? Un dieser Punkt muss dann auch mit dem Ziel (also der im mittlerem Auswahlfeld eingestellt ist z.b. das Silo) auch verbunden sein?

Hab ich das so korrekt verstanden?
Wenn ja dann:
Ja der Punkt "Abf.Feld02" ist schwer zu erreichen vom Feld aus und dies ist auch ein Endpunkt, also von dort geht es nicht weiter. siehe Bild. Aber warum funktioniert es mal ja und mal nicht?
![Unbenannt](https://user-images.githubusercontent.com/50840355/77940633-488df300-72b9-11ea-98de-96ab3e567b52.jpg)

**Comment by Iwan1803** [comment]
Bitte auf die aktuelle Version 1.1.03-3 aktualisieren und bezüglich Feldanbindung empfehle ich folgendes:
https://youtu.be/mOVxkIkU6og
Vielleicht einfach mal anschauen und dann mal die Kurse bei dir auf Optimierungspotential hin prüfen.

**Comment by Rumspringa90** [comment]
Moin, hab mir dein Video eben angeguckt. Super erklärt, hier auch nochmal danke dafür.

auf die aktuellste Version hatte ich gestern schon aktualisiert nachdem ich das Issue erstellt hatte.

In deinem Video klang es jetzt so, das es **kein muss** ist hinter dem, in meinem Fall "Abf.Feld 02", an das normale Streckennetz wieder anzubinden. In dem Fall auch nicht wirklich möglich, außer ich würde eine Strecke über das Feld ziehen. Außerhalb des Feldes kann ich den Punkt eigentlich nicht setzen, da in diesem Fall das Feld komplett von Gräben umgeben ist. Somit muss der Punkt ja auf der Brücke enden. (siehe erstes Bild oben)

Und ich bin bisher davon ausgegangen, wenn nächste Feldausfahrt eingestellt ist das er dann generell den nächsten Punkt nimmt, auch wenn der von CP zum auffüllen geschickt wird.

**Comment by Iwan1803** [comment]
Es ist kein muss und ich meine, ich habe das in meinem Video auch erklärt.
Der Abfahrerpunkt für Feld 02 ist doch gut gesetzt. Eventuell solltest du ihn noch ein Stück näher ans Feld verschieben, aber nicht soweit, das ein dort stehender Abfahrer mit z.Bsp. dem Schneidwerk eines Dreschers kollidiert, wenn er dort vorbei fährt.
Und ganz wichtig: evtl. die Kurve zum Punkt etwas weiter ausholen, damit ein großer oder langer Hänger nicht von der Brücke rutscht 😉

Das mit CP und der Übergabe an AD ist momentan so eine Sache, die die Voreinstellung vom Abfahrer aktuell ignoriert wird. Wir reden gerade intern darüber, dies zu ändern.

**Comment by Iwan1803** [comment]
-> https://github.com/Stephan-S/FS19_AutoDrive/releases/tag/1.1.0.4
