### ISSUE TITLE
Einbau von ballen abladen vom ballen sammel wagen

### ISSUE THREAD

**Issue by steven1134** [Stephan-S/FS19_AutoDrive#1262]
**Is your feature request related to a problem? Please describe.**
.

**Describe the solution you'd like**
A.

**Describe alternatives you've considered**
.

**Additional context**
könnte man im späteren verlauf noch einbauen das AD auch ballen von ballen sammel wagen abladen kann mus auch nicht jetzt direkt sein kann ruihg gemacht werden wenn zwischenduich mal zeit is

**Comment by Iwan1803** [comment]
Sorry, nicht realisierbar.
