### ISSUE TITLE
Missing Buttons  in HUD V1.1.0.3

### ISSUE THREAD

**Issue by rellek82** [Stephan-S/FS19_AutoDrive#1263]
AutoDrive Version: 1.1.0.3-3
Karte (falls relevant): Alle
Fahrzeug(art) (falls relevant): Alle

**Beschreibe den Bug**
Eine klare Beschreibung des Bugs.
Guten Morgen. Ich finde die neue Version von AD echt Klasse (Wide HUD, neue Buttons im HUD). Aber leider vermisse ich beim Wegebau die Buttons für "Nachbarpunkt wählen", "nächsten Nachbarpunkt wählen" und "Verbindung An/Aus". Ich werde daher erstmal weiter die V 1.1.0.2 nutzen. Trotzdem Danke für diesen super Mod..

**Comment by Rumspringa90** [comment]
Ich glaube die sind absichtlich weggelassen worden. Wenn du im EditerModus die STRG-Taste gedrückt lässt, kommst du in den erweiterten Modus (mit den Roten großen Punkten). Hier kannst du den Punkt anklicken(in meinem Fall den oberen) der dann glaube ich Blau oder Grün wird und dann den 2. anklicken der damit verbunden werden soll. Ob es die Linke oder die rechte Maustaste war kann ich grad nicht aus dem Kopf beantworten.

**Comment by Iwan1803** [comment]
Die Buttons mussten weichen, da wir das HUD neu organisiert haben 😎
Mit der linken Maustaste wählt man einen Wegpunkt aus.
Linksklick auf Wegpunkt A -> Wegpunkt wird grün -> Linksklick auf Wegpunkt B = grüne Linie wird erstellt
Linksklick auf Wegpunkt B -> Wegpunkt wird grün -> Linksklick auf Wegpunkt A = grüne Linie wird erstellt oder falls eine grüne Verbindung bereits besteht, wird diese in eine blaue umgewandelt

**Comment by rellek82** [comment]
Danke.  Iwan1803 hat mir im Discord schon den zurückgeschrieben und mir sein Video verlinkt. Darin ist ja alles genau erklärt. Danke nochmal. Funktioniert jetzt alles.
