### ISSUE TITLE
[FEATURE REQUEST] Edit folder in MP

### ISSUE THREAD

**Issue by Crykor90** [Stephan-S/FS19_AutoDrive#1266]
**Is your feature request related to a problem? Please describe.**
please add a function to edit folders with waypoints 

**Describe the solution you'd like**
just like in the singleplayer

**Describe alternatives you've considered**
an external editor - if i edit the config in notepad+ it is incorrupt

**Comment by Iwan1803** [comment]
Normally there is no difference in folder and target handling between single and multiplayer.

**Comment by Crykor90** [comment]
i showed baloo the problem - i have problems on the dedi server as admin

**Comment by TyKonKet** [comment]
@Stephan-S @Crykor90 any additional suggestions?
I would like to fix it but I really can't understand/reproduce that issue.

**Comment by Crykor90** [comment]
I can show it via livestream if u want 
Discord Crystep / Manu#7882

**Comment by Iwan1803** [comment]
Please try 1.1.0.5-RC3. If the problem still exists, just open a new issue.
