### ISSUE TITLE
Kollisionserkennung automatisch deaktivieren bei plötzlich ansteigender Strecke.[FEATURE REQUEST]

### ISSUE THREAD

**Issue by roland45** [Stephan-S/FS19_AutoDrive#1267]
Problem: Steigt die Strecke plötzlich an (zB: Brückenauffahrten, Auffahrten zu Produktionen usw.) bleibt der LKW stehen, da er vermeintlich eine Kollision erkennt.
Ohne Kollisionserkennung fährt er durch, aber ein Betrieb mit aktiven KI Verkehr wird problematisch, da die Fahrzeuge bei hoher Geschwindigkeit auf den Vordermann auffahren und meist aus der Bahn geworfen werden.
Vorschlag: Abfrage der kommenden Wegpunkte und deren Ansteigewinkel zueinander. Überschreitet die Steigerung der kommenden Wegpunkte einen gewissen Wert, wird die Kollisionserkennung automatisch deaktiviert. 
Wird der Steigerungswinkel kommender Wegpunkte zum aktuellen Wegpunkt wieder kleiner  wird die Kollisionserkennung wieder aktiv. 
(Gerade ebene Stecken haben ja zueinander den Winkel 0, ebenso gleichbleibende Steigerung zueinander ebenfalls 0)
Damit wäre ein Betrieb von AD mit aktivierter Kollisionserkennung durchgehend möglich.

**Comment by Iwan1803** [comment]
Die Idee mit dem Winkel finde ich gar nicht so schlecht, aber ab wieviel Grad soll sich was ändern?
Was ist mit Wegpunkten, welche in der Luft schweben oder unter der Karte versunken sind (was leider vorkommen kann)?
Man kann natürlich was programmieren, aber das kostet verdammt viel Zeit. 
Vielleicht sollte man einfach mal den Mapersteller kontaktieren, ob ihm das Problem mit der Kollision bekannt ist und ob er da was machen kann.

Um welche Map geht es hier eigentlich und kannst du mal Screenshots von den Stellen inkl. Debug-Infos posten?

**Comment by roland45** [comment]
Zu „wieviel Grad“: Hängt von der Funktion „Kollisionserkennung“  ab. Ab welcher Steigung vor ihr erkennt sie ein Hindernis zum Stehenbleiben? Das müsst Ihr ermitteln können.
Zu „Wegpunkte in der Luft“: Sind mir derzeit keine bekannt. Aber wenn ich richtig gelesen habe,  hat Stephan eine Möglichkeit erwähnt, die richtige Höhe von Wegpunkten ermitteln zu können.
Zu“welche Map“: Dieses Problem tritt mit LKW zB.  bei jeder Brückenauffahrt  über den Kanal  in der Map: „Porta Westfalica“ auf. 
Zu „Screenhots“ : Sorry, momentan (auch nicht in den nächsten Tagen)  leider nicht möglich, da ich derzeit nicht bei meinem Spielcomputer bin. Meldungen treten keine auf, mit Kollisionserkennung bleibt Fahrzeug vor Brückenauffahrt stehen, bei  Deaktivierung der Kollisionserkennung fährt es sofort weiter. Kann daher nur ohne Kollisionserkennung und ohne KI Verkehr  automatische Abläufe ohne händischen Eingriff fahren lassen. (ist nicht von AD Version abhängig, war immer schon so seit diese Funktion zur Verfügung steht).

**Comment by roland45** [comment]
Sorry, noch ein Nachtrag.  Sollte wirklich dieser Vorschlag in nähere Überlegung genommen werden könnte auch eine enge rechts oder links Abbiegung zu einer automatischen Kollisionserkennungs-Deaktivierung (Überprüfung wie oben mit Winkel zu nächste Wegpunkte) führen .zB. nützlich bei engen Abbiegungen in Hallen oder Fabriksgelände oder Einparken zwischen Fahrzeugen bei engen Zufahrten. Lieber eine kurzeitige Deaktivierung zu viel, als ein Hängenbleiben des Fahrzeuges.

**Comment by roland45** [comment]
Zum Nachtrag noch ein Vorschlag:  Bei engen Kurven wird sowieso von AD die Geschwindigkeit stark reduziert. Hier könne bei unterschreiten von zB .10kmh die Kollisionserkennung automatisch mit deaktiviert werden. (kann ja nichts mehr passieren) bei höheren Geschwindigkeiten  wieder automatisch aktiviert werden.

**Comment by roland45** [comment]
Würde das autom. Deaktivieren der Kollisionserkennung  bei Unterschreitung einer Geschwindigkeit (zB:10 kmh) nicht auch das Problem bei Steigungen lösen! (siehe oben) Fährt das Fahrzeug wieder schneller wird die Funktion wieder aktiviert. (glaube, ein geringer Programmieraufwand)

**Comment by Iwan1803** [comment]
Genau, weil bei Geschwindigkeiten unter 10km/h Schilder, Bäume, Leitplanken, Fahrzeuge & Co. ja eh keine Gefahr mehr darstellen.... 🤪

Sorry, aber wenn Karten so gestaltet sind, das Auffahrten & Co. eine Kollision darstellen, sollte entweder der Ersteller was anpassen oder man muss halt den KI-Verkehr ausschalten und Kollision deaktivieren.
Ansonsten müssten wir x Ausnahmen definieren, nur damit sowas eben keine Probleme darstellt und das haben wir hier wieder haufenweise fragen, warum wieder Fahrzeug X irgendwo im Zaun hängt.

**Comment by roland45** [comment]
Ok, hab sowas erwartet und mit den vielen Fragen hast Du recht. Aber  warum ein Fahrzeug das ohne Kollisionserkennung langsam  (zB 10kmh) mit AD geführt fährt,  an Schilder, Bäume, Leitplanken, Fahrzeuge & Co irgendwo im Zaun hängen bleiben soll, ist mir nicht klar. Wenn ich ohne Kollision fahre lasse hab ich ja auch keine Probleme, nur dann ist halt der KI-Verkehr das Problem. Mit Kollision ist auch dieses Problem weg. 
Ist denn das aktivieren/deaktivieren geschwindigkeitsabhängig so ein Problem?
Ok, das Abschalten und nicht verwenden dieser Funktionen ist sicher der einfachste Weg.

**Comment by Iwan1803** [comment]
Die Kollisionserkennung greift nicht nur auf der Straße sondern auch auf Feldern und plötzlich krachen die Fahrzeuge alle ineinander, nur weil sie Geschwindigkeit X unterschritten haben. Für all das müsste man dann Ausnahmen definieren und so einige Faktoren berücksichtigen.
Das alles würde AD einfach nur unnötig kompliziert und auch fehleranfälliger machen.

**Comment by roland45** [comment]
Entschuldigung, nur zu meinem besseren Verständnis obiger Aussage.
Wenn also der AutoDrive Anwender im Hautmenü (Einstellungsmenü) des Programms den dort angebotenen Menüpunkt „Kollisionserkennung EIN/AUS“ auf „AUS“ stellt, hat das zur Folge, daß die Fahrzeuge auf den Feldern „unkontrolliert ineinander krachen“??  Diese Aussage kann ich nicht ganz ernst nehmen, und als AD Anwender in ihrer Richtigkeit auch nicht bestätigen.

**Comment by Iwan1803** [comment]
Ich habe nicht gesagt, das man die Kollisionserkennung für Felder mit den Einstellungen ausschaltet.
Dein Vorschlag war, die Kollisionserkennung ab Geschwindigkeit X auszuschalten und konsequenterweise müsste man das dann auch auf Felder anwenden. Um aber Chaos zu vermeiden, bräuchte man dann aber wiederum Ausnahmen (wie sie jetzt schon existieren).
Sorry, aber das macht in meinen Augen nicht wirklich Sinn.

**Comment by eric4072** [comment]
Hi Iwan1803!

Ein kleiner Gedanke zu dem Thema: Ich benutze AD mit den Linien ober dem Fahrzeug. Bei Steigungen sind die Punkte immer genau die gleiche Höhe über den Boden. Ist es nicht möglich die Kollisionserkennung an dieser Linie zu fixieren? wenn dann eine Steigung kommt würde sich die Kollisionserkennung automatisch heben und die Brücke (oder ähnliches) wird nicht mehr als Objekt erkannt.

Möchte euch mal ganz groß loben: Gestern die aktuelle Version geladen und gleich mal 6std Maishäckseln ins Fahrsilo getestet: TOP!!! Das Ganze läuft auch mit 2 Häcksler und 8 Abfahrer meiner Meinung nach Fehlerfrei ;-)

LG
Eric

**Comment by Opa-Andre** [comment]
@roland45 Kenne das Problem auch und musste dabei feststellen, dass das Thema mit bei stärkeren Anstiegen bei Brücken etc. auch noch fahrzeugspezifisch ist. Probleme zeigen hier eher die Trucks, wo die Kollisionserkennung näher in Bodennähe ist - bei Traktoren tritt das eher selten auf, da dort die Kollisionsbox weiter oben ist. Man kann das Verhalten gut mit "F5" und eingeschaltetem AD betrachten. Dann sieht man vor dem Fahrzeug einen "schwarzen Quader". Kommt man an ein Kollisionsobjekt, wird dieser in der Länge gestaucht, was dazu führt, das das Fahrzeug abgebremst wird. Erfolgt die Stauchung über einen gewissen Schwellwert, wird die Box dann langsam orange und wenn es zu "eng" wird, bleibt das Fahrzeug dann stehen. 

Die Idee, hier auf einen Steigungswinkel der nächsten x Streckenpunkte zu prüfen und ggf. die Kollisionsbox ebenfalls auf diesen Steigungswinkel "auszurichten", finde ich nicht schlecht - weiss aber nicht, wie kompliziert da die Berechnung wird. Die andere Idee mit der Deaktivierung bei niedriger Geschwindigkeit macht nicht wirklich Sinn, da geb ich @Iwan1803 Iwan1803 seinen Begründung Recht.

**Comment by Stephan-S** [comment]
Ich nehms auf. Ist auf jeden Fall ein interessanter Ansatz, der sich mal lohnt zu verfolgen!

**Comment by Iwan1803** [comment]
Mit RC4 kann man die Höhe der Kollisionsbox vor dem Fahrzeug selber einstellen.
