### ISSUE TITLE
No BUG - just a question regarding the two speed displays

### ISSUE THREAD

**Issue by TobiHH78** [Stephan-S/FS19_AutoDrive#1268]
I really like the new designed Hud. Just a question, as I have no clue.
There are now two different speed displays. For what is the one in the upper line? I changed that speed on tracks and on fields, but nothing happened.

**Comment by Iwan1803** [comment]
The first is for the max. speed on fields, the 2nd for max. speed on roads.

**Comment by seeske123** [comment]
Works perfect.
