### ISSUE TITLE
Can I use Autodrive on fields I have created myself?

### ISSUE THREAD

**Issue by Aceone1** [Stephan-S/FS19_AutoDrive#1269]
Ich spiele gerne auf Karten wie die "Flatmap" oder die "No man's land" wo alle Felder selbst erstellt werden müssen. Ist Autodrive auf solchen Karten uneingeschränkt nutzbar, besonders Mähdrescher abtanken?

I like to play on maps like the "Flatmap" or the "No man's land" where all fields have to be created by myself. Is it possible to use Autodrive on such maps without any restrictions, especially when discharging combine harvesters?

**Comment by Iwan1803** [comment]
Ich habe schon Felder erstellt, mit Courseplay die Felder "eingerahmt" und dann bearbeitet. Der Abfahrer wurde von AD gesteuert und das hat soweit problemlos geklappt.

**Comment by Aceone1** [comment]
Geht das denn auch ohne Courseplay, da ich dieses nicht nutze? Wenn ich z.B. große Felder habe, würde der Abfahrer nicht gerufen werden können, da beim Drescher keine Feldnummer eingetragen werden kann, weil nicht vorhanden.
Vielleicht kann man das mit geschickt gesetzten Parkpositionen setzen, sofern man mehr als eine pro Feld setzen und nutzen kann. Ich werde heute mal etwas damit experimentieren.

feature-request:
Es wäre schön wenn es eine kleine Liste gäbe mit allen derzeit genutzten Maus + Tastatur Kombinationen.
Ich habe z.B. vergessen wie man den Pfeil zwischen zwei Wegpunkten in die andere Fahrtrichtung drehen kann und es ist sehr schwierig in Tutorial Videos genau diese Stelle wo das erklärt wird nochmal zu finden. Manche Aktionen stehen ja direkt im Menü, wenn man die Maus darüber bewegt, aber andere nicht.

**Comment by haamic** [comment]
Man setzt doch aber in AD im Drescher nur den selben "Zielpunkt", den der Abfahrer als Wartepunkt hat. Mit der Feldnummer, ob vorhanden oder nicht, hat das nichts zu tun.

**Comment by Aceone1** [comment]
Hab auf der Niemandsland Karte getestet und es funktioniert mit eigenen Feldern. Der Grund, dass es erst nicht funktionierte lag an dem VCA Mod. Autodrive kann den Abfahrer nicht zurücksetzten wenn in VCA der Shuttle Modus für manuellen Richtungswechsel aktiviert ist. Daher blieb der Abfahrer an diesem Punkt wo er zurücksetzen sollte immer hängen.
Fragen sind beantwortet. Danke an alle Beteiligten und vorallem an die Macher für diesen exzellenten Mod. Bleibt alle gesund!
