### ISSUE TITLE
Umlaute in Zielpunkten

### ISSUE THREAD

**Issue by Experience95** [Stephan-S/FS19_AutoDrive#127]
Mir ist aufgefallen, dass wenn man im Namen eines Zielpunktes einen Umlaut (Ä, Ö, Ü) eingeben möchte, das Spiel komplett einfriert. Einzig Alt+F4 oder Console "q" funktioniert noch. Ärgerlich wenn der letzte Autosave schon eben her ist.

**Comment by Stephan-S** [comment]
Hey,
danke für die Rückmeldung.
Ich werde mich darum kümmern, sobald ich Gelegenheit habe.

Beste Grüße,
Stephan
