### ISSUE TITLE
[BUG] Error Displays dont disappear

### ISSUE THREAD

**Issue by Knowen** [Stephan-S/FS19_AutoDrive#1270]
**AutoDrive Version:** 1.1.x.x   
**Release or Custom Zip:** Release  
**Map (If applicable):** All  
**Vehicle / Type (If applicable):**   
**Multiplayer or Singleplayer:** Singleplayer  

**Describe the bug**  
Two displays are reporting an error. They keep popping up, even AD is turned off for the vehicle. Also, it is not possible to restart AD for that specific vehicle. No matter what. Even if the vehicle is right in front of the destination. I have to quit the game and restart it to disable the poping error displays. 

**If applicable - Steps to reproduce the behavior**  

**Screenshots**  
![fsScreen_2020_03_31_21_42_33](https://user-images.githubusercontent.com/47173160/78068363-92013f80-7398-11ea-9818-e6e0fd13fd1f.png)

**Comment by Iwan1803** [comment]
Prüf mal die Verbindungen zwischen den Wegpunkten und verbind sie ggfs. neu.

**Comment by Knowen** [comment]
Ich hatte zwei Abfahrer aktiv. Einer hat tadellos funktioniert. Der zweite ebenfalls, bis auf einmal der Fehler aufkam. 
An den Wegpunkten kann es nicht liegen, denn der verbleibende Abfahrer hat weiterhin perfekt gearbeitet.

**Comment by Iwan1803** [comment]
-> https://github.com/Stephan-S/FS19_AutoDrive/releases/tag/1.1.0.4
Bitte aktualisieren, die Strecke überprüfen und dann noch mal probieren.
