### ISSUE TITLE
[FEATURE REQUEST] Hide driving mode when not useful

### ISSUE THREAD

**Issue by Serge63230** [Stephan-S/FS19_AutoDrive#1271]
Good evening.

First of all, well done for the work accomplished. it's really a great mod.

Could you add an automatic detection of the tool hanging behind the tractor in order to hide the driving modes which are not useful at the time?

Let me explain :

The mod offers 5 driving modes:
1) drive to
2) loading and delivery
3) delivery
4) loading
5) unload

- When there is no tool, you display only mode 1 for example.

- When there is a seed drill or a spreader, you only display modes 1 and 4.

- When it is a trailer, you display only modes 1, 2, 3 and 5

You must already have a similar option because the mode to empty the bga (driving mode 6) is displayed only for wheel loaders

The goal is to avoid having to click to scroll through each driving mode when some are not useful at the time.

**Comment by Iwan1803** [comment]
Looks like you are not using the newest version as the BGA mode was removed. If it was active for a vehicle, you can still see the button for it.

**Comment by Stephan-S** [comment]
I'm a bit torn with this idea.
It sounds useful but for my personal usage it's not really :D 
For example I like to setup AD while I'm on the way to pickup new tools. You would remove that option by not allowing the different modes at all times.

But let's keep this issue open and see if other users also have thoughts on that :-)

**Comment by TobiHH78** [comment]
I agree with Stephan and would not change the actual setting.

**Comment by Maarkreidi** [comment]
perhaps a toggle option tu use or not this feature.

**Comment by Serge63230** [comment]
> 
> 
> Looks like you are not using the newest version as the BGA mode was removed. If it was active for a vehicle, you can still see the button for it.

I had seen the option on version 1.0.7 but I was not using it.
I have not checked if it is still present on the latest version

**Comment by Serge63230** [comment]
> For example I like to setup AD while I'm on the way to pickup new tools. You would remove that option by not allowing the different modes at all times.

I also use courseplay and autodrive.

1) I prepare the work to be done with courseplay
2) I change the settings on autodrive so that it drives the tractor on the right field
3) I click on the button so that it starts courseplay when arriving

I just have to start autodrive

=> at this time, the tool is already hung behind the tractor.

From what I know, neither courseplay nor autodrive allows to hang a tool automatically

as suggested by Maarkreidi, you could put an option which allows to activate or not this facility

**Comment by Iwan1803** [comment]
Cost/benefit calculation: negative
In the meantime the cooperation between AD and CP was further improved
