### ISSUE TITLE
 Zeichenerklärung / Explanation of symbols

### ISSUE THREAD

**Issue by scandal65** [Stephan-S/FS19_AutoDrive#1272]
Hallo, 

gibt es schon irgendwo eine Erklärung für die neuen Symbole/Funktionen von Version 1.1.0.3 ??
PS: Ich persönlich fand das manuelle Verbinden der Strecken besser!

Hello,
is there somewhere an explanation for the new symbols / functions of version 1.1.0.3 ??
PS: I personally found it better to manually connect the routes!

lg BJ

**Comment by Iwan1803** [comment]
Ja, gibt es:
https://youtu.be/6xlezQgQ3q8

**Comment by scandal65** [comment]
Danke ;-)
