### ISSUE TITLE
[FEATURE REQUEST]add old  course editor  as optional mode 

### ISSUE THREAD

**Issue by nimanox** [Stephan-S/FS19_AutoDrive#1273]
wäre toll wne man die alte editor optionen als optionale funktion wieder einbauen könnte das man nicht immer die strg tasten gedrückt halten muss um den kurs zu ändern

 fande das system mit strg gedrückt halten nur um neue zu erstellen und zu löschen angenehmer als jetzt dauerhaft  die taste gedrückt zu halten. da ich gerne meine aktuellen kurse im vollen editor modus abfahre und im fahren die punkte anpasse  

alleine dafür benutze ich lieber die ältere version als die aktuelle

**Comment by Iwan1803** [comment]
-> https://github.com/Stephan-S/FS19_AutoDrive/releases/tag/1.1.0.4
