### ISSUE TITLE
[BUG] HUD ragt beim Umschalten zwischen Wide HUD und normalem HUD über den Bildschirmrand hinaus /  HUD protrudes over the edge of the screen when switching between Wide HUD and normal HUD

### ISSUE THREAD

**Issue by flattergaul** [Stephan-S/FS19_AutoDrive#1275]
AutoDrive Version: 1.1.0.4
Release or selbsterstelltes zip: Release
Karte (falls relevant): Alle
Fahrzeug(art) (falls relevant):

Ist das HUD nahe dem Bildschirmrand platziert, ragt das HUD über den Bildschirmrand hinaus, wenn die HUD-Ansicht von Normal auf Wide bzw. umgekehrt umgeschaltet wird.

Oberer Bildschirmrand: beim Umschalten von Wide auf Normal
Rechter Bildschirmrand: beim Umschalten von Normal auf Wide

**Comment by Iwan1803** [comment]
Und wo ist der Bug? Man kann das HUD doch an die Stelle verschieben, wo man möchte.

**Comment by flattergaul** [comment]
Nur bedingt ;-)

Wenns am oberen Bildschirmrand passiert nicht, weil ich dann die Titelzeile des HUD nicht mehr sehe.

![AD-HUD_1](https://user-images.githubusercontent.com/62457740/78156875-a64c4780-743f-11ea-9214-0e0243cd508a.jpg)

Man muss dann wieder auf das Wide HUD umschalten, um das HUD verschieben zu können.

Am rechten Bildschirmrand ist's zugegebenermaßen nur ein Schönheitsfehler, weil "nur" die Buttons verschwinden und ich das HUD verschieben kann.

![AD-HUD_2](https://user-images.githubusercontent.com/62457740/78157347-22df2600-7440-11ea-888c-9ba6b3b1a90b.jpg)

**Comment by Iwan1803** [comment]
Dann wäre eine Änderung hieran aber eher ein Feature Request und nicht wirklich ein Bug 😉

**Comment by flattergaul** [comment]
OK, darüber können wir diskutieren ;-)
Ich sehe halt so Sachen, wo ich an der GUI was umstelle und ich danach das Ding nicht mehr bedienen kann, ohne wieder etwas umzustellen, eher als Bug..

Aber zugegeben: es ist Jammern auf sehr hohen Niveau - das was AD leistet ist absolut top!
Danke für das Tool

**Comment by Stephan-S** [comment]
Ich nehms als Bug auf und werd das auf jeden Fall noch abfangen. Aber dann im nächsten Release.
Muss ja noch Ziele geben :D

**Comment by Stephan-S** [comment]
Erledigt. Kommt ins nächste Release
