### ISSUE TITLE
When will it be possible to install driving backward with autodrive ? [FEATURE REQUEST]

### ISSUE THREAD

**Issue by Moitzbert** [Stephan-S/FS19_AutoDrive#1276]
Ab wann wird es denn die Funktion mit dem rückwärts fahren geben ? Oder gibt es die bereits und ich hab es noch nicht mitbekommen ? 

When will it be possible to install driving backward ? 

PS: Awesome release ! :D

**Comment by Iwan1803** [comment]
Ist weder vorhanden noch geplant.

**Comment by Tadeloach** [comment]
> Is neither available nor planned, but I will leave it as a suggestion.

It would be awesome addition for parking Tractors with implements into spaces that have to be backed into.

**Comment by Iwan1803** [comment]
Implemented in 1.1.0.5-RC1.
