### ISSUE TITLE
[QUESTION] recording streets

### ISSUE THREAD

**Issue by scandal65** [Stephan-S/FS19_AutoDrive#1277]
Hallo (nochmal),

@Iwan1803
erstmal vielen Dank für den Link und das TOP Video ( bist schon aboniert! ;-) )
ABER....
wie verbinde ich, ohne manuelle Möglichkeit diese zwei Wegstrecken?!
...und wie hast du in deinem Video die Strecken so gerade hinbekommen und die Kurven alle (das was ich sehen konnte) auf 45°?
![fsScreen_2020_04_01_17_23_50](https://user-images.githubusercontent.com/49526721/78156433-173f2f80-743f-11ea-8bb1-7cad44a1962a.png)

lg und Dank im voraus
BJ

**Comment by Iwan1803** [comment]
Wie man mit dem neuen Editor umgeht, habe ich auch in einem Video erklärt: 
https://youtu.be/MC9ATiHTOOg
Es basiert zwar noch auf einer älteren AD-Version, aber die notwendigen Tasten (STRG & ALT) sind ja immer noch aktuell 😉
Um gerade Linien hinzubekommen, kann man z.Bsp. den GPS-Mod benutzen. Um Wegpunkte schön gerade zu setzen, kann man sich per Landschaftsbau schöne Quadrate hinmalen. Dann ist die Ausrichtung ein Klacks 😎
![image](https://user-images.githubusercontent.com/47528836/78158117-245d1e00-7441-11ea-9785-d4408919c3f5.png)

**Comment by scandal65** [comment]
Danke!

**Comment by Iwan1803** [comment]
Hier ein aktuelles Video zu diesem Thema:
https://youtu.be/Utchz5scDaA
