### ISSUE TITLE
Question to new editor  handling

### ISSUE THREAD

**Issue by webwibo** [Stephan-S/FS19_AutoDrive#1278]
AutoDrive Version: 1.1.0.4
Release or selbsterstelltes zip: Release
Karte (falls relevant): Alle
Fahrzeug(art) (falls relevant):

Ich habe die neueste Version von AD geladen und wollte ein paar Wegpunkte löschen und anders verbinden.
Zum Verbinden der Kurse habe ich die Option automatisches verbinden am Endpunkt ausgestellt.
In dem neuen HUD ist aber der Knopf zum Durchschalten der möglichen Wegpunkte an die ich anknüpfen kann ist nicht mehr vorhanden.
Wie kann man den entsprechenden Wegpunkt wählen mit dem ich den Kurs verbinden möchte?
Geht es nur noch über automatisch verbinden des Endpunktes?

Ich muss aber noch sagen das diese Ergänzung zu LS hervorragend ist. Toole Arbeit.

Iloaded the latest version of AD and wanted to delete a few waypoints and connect differently.
To connect the courses, I issued the option to connect automatically at the end point.
In the new HUD, however, the button to choose the possible waypoints to which I can connect is not visible.
How can I choose the appropriate waypoint with which I want to connect the course?
Is it only possible to connect the end point automatically?

But I have to say that this supplement to LS is excellent. Toole work.

**Comment by Iwan1803** [comment]
Basiert zwar nicht auf der neuesten AD-Version, aber die Tasten sind immer noch die gleichen:
https://youtu.be/MC9ATiHTOOg

**Comment by webwibo** [comment]
Danke für die schnelle Hilfe.
Diese Funktionen waren mir bisher so nicht bekannt. Funktioniert prima.
Die Funktionen in AD  werden immer besser!  Ihr Entwickler macht das prima.

**Comment by Iwan1803** [comment]
Bei weiteren Fragen sind wir auch in Discord erreichbar: 
https://discord.gg/9D4B5hX
