### ISSUE TITLE
[BUG] Abholen und Anliefern Modus. Der Schlepper liefert ab wo er abgeholt hat

### ISSUE THREAD

**Issue by Michael170978** [Stephan-S/FS19_AutoDrive#1279]
Hi

Ich spiele zur Zeit auf der Map Hopfach wo die Silos den Befülstützen über den Entleeren Trigger haben. Wenn ich den Modus Abholen und Anliefern aktiviere wird der Anhänger befüllt und sobald voll ist, wird sofort wieder entleert. 

Anbei ein Beispiel video:

https://youtu.be/d6CRLZUV7Es

**Comment by Iwan1803** [comment]
Wie sieht das AD-Netz aus und ist die Mühle relativ nah dran?
Wie groß ist max. Silo-Abstand eingestellt?

**Comment by Michael170978** [comment]
Die Mühle ist in einem anderen Ortsteil. Laut Tacho ca 2km von dem Silo entfern. Zuerst war der Abstand auf 25m eingestellt. Dann habe ich auf 50m erhöht aber ohne Erfolg.

Was man auf dem Video nicht mehr sieht. 

Ich ließ ihn eine extra Runde drehen, mit der Hoffnung, dass es doch klappen wird. Beim zweiten Versuch ist mir aber aufgefallen, dass weder der Abholpunkt  noch Anlieferpunkt grün markiert waren. Ich ließ den Schlepper dennoch fahren um zu qucken was er vor hat. Er fuhr zum Hofsilo bis er den Triger erreicht hat. Danach hat er den Motor abgestellt und nicht geladen. Also wieder AD aus und wieder an. Danach war Anlieferpunkt grün markiert und er fuhr leer zur Mühle. Beim dritten Versuch habe ich zu 50% manuell geladen und ließ ihn zur Mühe fahren um zu schauen ob er überhaupt entladen wird. Leider hat er nicht entladen. Er hat den Triger bei der Mühle passiert, ist zum Hofsilo gefahren, hat voll gemacht und anschließend sofort wieder entladen.

**Comment by Maarkreidi** [comment]
Same prob with load/unload mode for me.
i tried with different trailer and different points. Always the same result.

**Comment by kaufm30** [comment]
Ich hatte dasselbe Problem. Du brauchst nur den Zielpunkt soweit nach vorne setzen, dass Ende des Anhängers bereits aushalb des Entladetriggers ist, sobald der tatsächliche Zielpunkt erreicht ist.

**Comment by Michael170978** [comment]
@kaufm30  Das bring nichts, weil dann wird der Anhänger nicht geladen wird.

**Comment by Iwan1803** [comment]
@kaufm30 du kannst den auch 50 oder 80m weiter weg machen, wenn man denn den Sila-Abstand entsprechend groß einstellt.

**Comment by Stephan-S** [comment]
Aber nur schon mal um die Gemüter zu beruhigen.
Bug ist gefunden und behoben :-)
Aber bis zum nächsten Release, sollte Iwan's Tip helfen, das Problem zu umgehen.
Aufladen kann er ja auf dem Weg zum Zielpunkt, wenn der Radius groß genug gewählt ist. Und so lange er ab Erreichen des Zielpunkts nicht mehr an den Trigger kommt, kann er ja erstmal nicht falsch abladen.

Beste Grüße und danle für den Bug-Report :-)
P.S: Ab jetzt muss bei uns dringend ein Beladepunkt in den Testzyklus, an dem man auch gleichzeitig abladen kann :-)

**Comment by Stephan-S** [comment]
Erledigt. Kommt ins nächste Release
