### ISSUE TITLE
Abholen und Abladen V1.0.2.0

### ISSUE THREAD

**Issue by BerndUwe** [Stephan-S/FS19_AutoDrive#128]
hallo

irgendwie kann ich nichts wählen bei der Funktion Abladen und Abholen da steht nur weizen da... wenn ich klicke zum wechseln steht nichts mehr da und wenn ich nochmal klicke dann ist weizen wieder da :(

mfg bernd

**Comment by Stephan-S** [comment]
Hallo Bernd,

du musst nicht klicken sonder das Mausraud nutzen, dann sollte es problemlos gehen.
Wenn du in das Feld klickst, kannst du einen Zielpunkt mit der Tastatur eingeben (mit der Tab-Taste vervollständigen und mit Return bestätigen).
Ich hoffe das klärt das Problem :-)

Viele Grüße,
Stephan

**Comment by BerndUwe** [comment]
hai

zeilpunkte ist kein problem was nicht geht sind die Fruchtsorten..... mache es jetzt per ALT+STRG+4

aber es ging doch mit klicken auch... zumindest in 1.0.0.0 :)

mfg Bernd

**Comment by Stephan-S** [comment]
Das Problem ist ja behoben, also schließe ich hier mal :-)
