### ISSUE TITLE
[FEATURE REQUEST] Option to turn OFF messing with the trailer covers

### ISSUE THREAD

**Issue by BloodyRain2k** [Stephan-S/FS19_AutoDrive#1282]
I don't know why but with 1.1.0.3-4 AD started messing with my trailer covers even when I only use the "drive to" command.

I was used to it doing that on modes that involve doing something with the trailer like loading and unloading, but now even just for normal driving, that's too much.

Please add an option to make it not automatically open and close the covers, I just wanna have my trailers open ok? : (

**Comment by TyKonKet** [comment]
@BloodyRain2k that's strange, I have any issues with covers...

**Comment by BloodyRain2k** [comment]
@TyKonKet so your vehicles don't close the covers for all commands?

**Comment by TyKonKet** [comment]
Yes, covers get closed but that's because some triggers requires covers to be in a given state so we need to keep control over them.

**Comment by BloodyRain2k** [comment]
Triggers yeah, but I'm talking about the normal _Drive_ command.
And can't the covers just stay open? <.<

**Comment by TyKonKet** [comment]
Yes but if during normal drive, it drives under a trigger with `autoLoad` and the cover is open, you will find your trailer filled with something you don't want inside...
And if this trigger is a buy trigger, you will also spend your money for nothing 😄

**Comment by TyKonKet** [comment]
So we can even try to add this kind of option but is that really worth?
Let's hear some other opinions 😄 
@Stephan-S 
@Iwan1803

**Comment by BloodyRain2k** [comment]
I have no auto triggers in my map and I've never driven accidentally under a harvester either, especially not since the helpers permanently retract the damn pipe...

So yeah, I don't see the issue, even if the examples might be valid in other people's cases.

**Comment by Iwan1803** [comment]
Snow can't be collected in closed trailer if you are using snow or Seasons mod 😎

**Comment by Iwan1803** [comment]
Cost/benefit calculation: negative
Also opening/closing covers was improved in the meantime.
