### ISSUE TITLE
[FEATURE REQUEST] option to turn off all the messages

### ISSUE THREAD

**Issue by krambc** [Stephan-S/FS19_AutoDrive#1283]
First of all congratulate you for the excellent work you are doing with this mod.

My request, I think it would be simple to implement. It would only be necessary to include a new option in the configuration that allows disabling all the messages displayed on the screen ...

Thanks in advance, you may or may not attend to my suggestion.

**Comment by Iwan1803** [comment]
... or to set a timer from 0 to x seconds.

**Comment by Iwan1803** [comment]
Will be included in the next version 😎
