### ISSUE TITLE
Fahrzeit Berechnung wird nicht Angezeigt MP Dedi / Travel time calculation is not displayed MP Dedi

### ISSUE THREAD

**Issue by Gyffes** [Stephan-S/FS19_AutoDrive#1286]
AutoDrive Version: 1.1.0.4
Release or selbsterstelltes zip: Release
Karte (falls relevant): Alle
Fahrzeug(art) (falls relevant):

**Beschreibe den Bug**
Oben im Hud wird bei mir aufm Dedi Server die Berechnete Fahrzeit nicht angezeigt im Singel oder MP ohne Dedi geht es. 

Super Arbeit. Weiter so :)

Google Translator 
At the top of the Hud, the calculated travel time is not shown on Dedi Server in Singel or MP without Dedi.

**Comment by Bandesss** [comment]
Ja das Problem haben wir auch

**Comment by Gyffes** [comment]
Hallo und guten Tag, 
Ich weiß Ihr seit damit beschäftigt größere Bugs zu beheben und jede menge neuer super Features (zu rückwärts einparken) einzubauen. 

Wollte auch nur mal kurz nachfragen ob mit einer Behebung im nächsten  Release gerechnet werden kann?

Vielen Dank. 
Bleibt gesund.

**Comment by Gyffes** [comment]
Grüße hier ein kleines Udate auch mit Version 1.1.0.5-RC2 wird die Fahrzeit im MP mit Dedi Server nicht angezeigt.

Bleibt gesund

![grafik](https://user-images.githubusercontent.com/51527134/79590247-03e6c200-80d7-11ea-8e27-dcc480c44899.png)

**Comment by Iwan1803** [comment]
-> https://github.com/Stephan-S/FS19_AutoDrive/issues/1510

**Comment by Iwan1803** [comment]
Da in 1.1.0.6 gefixt, mach ich hier mal zu // Since fixed in 1.1.0.6, i'll close here 😎
