### ISSUE TITLE
Neue Strecke in Ordner schieben

### ISSUE THREAD

**Issue by Marko230** [Stephan-S/FS19_AutoDrive#1287]
![Bild 1](https://user-images.githubusercontent.com/51233639/78283129-a458b600-751d-11ea-9955-53505fb233e6.png)
AutoDrive Version: 1.1.0.4
Release or selbsterstelltes zip: Release
Karte (falls relevant): Alle
Fahrzeug(art) (falls relevant):

**Beschreibe den Bug**
Eine klare Beschreibung des Bugs.

**Falls anwendbar - Schritte mit denen ich den Bug nachstellen kann**

**Screenshots**
Falls relevant, bitte Screenshots beifügen
Hallo, ich habe eine Frage,
wie schiebt man jetzt in der neuen Version einen Kurs vom Standart-Ordner in einen selbst erstellten Ordner?

Vorher mußte man ja auf überführung stellen und die bearbeitungstaste Drücken ( komme gerade nicht auf den Namen)  :) 
aber jetzt steh ich auf dem schlauch , und bekomm es nicht hin 

Gruß Marko

**Comment by Iwan1803** [comment]
Editor-Modus aktivieren und dann einfach ein Ziel aus der Liste per Drag&drop in einen Ordner verschieben.

**Comment by Marko230** [comment]
Ei supi , habs gerade probiert. Danke
Ich schließe hier dann wieder.
