### ISSUE TITLE
[BUG] Automatic Diesel refueling not working / Automatisch Diesel nachtanken nicht moeglich

### ISSUE THREAD

**Issue by Gariot** [Stephan-S/FS19_AutoDrive#1288]
AutoDrive Version: 1.1.0.4
Release or selbsterstelltes zip: Release
Karte (falls relevant): Getestet mit standart Felsbrunn und Saxonia
Fahrzeug(art) (falls relevant): Nur mit Traktoren getestet

**Beschreibe den Bug**
AD kann ja automatisch Diesel auftanken wenn im Betrieb der Tank etwas zu leer wird. Es klappt soweit das er den niedrigen tankstand bemerkt und zur naechsten Tankstelle faehrt. Das problem ist dann aber das er einfach nur im Trigger steht und nicht auftankt. Ich muss dann manuell einmal "R" druecken, dann tankt er, selbst wenn AD noch an ist.
Beobachtet habe ich das gestern und heute bei meinem beiden Drescher abfahrern - d.h. der Drescher abfahren Modus war aktiv. Ich habs erst auf die Map geschoben, aber heute nochmal auf der Felsbrunn getestet und das gleiche ergebnis erzielt.
Zum testen habe ich alle mods deaktiviert und nur AD genutzt.

**Falls anwendbar - Schritte mit denen ich den Bug nachstellen kann**
Warten bis z.b. ein Abfahrer niedrigen Tank hat (oder halt manipulieren) und warten das er zur naechsten Tanke faehrt. Dort angekommen bleibt er im tank trigger stehen und tankt nicht.

**Screenshots**
Falls relevant, bitte Screenshots beifügen

**Comment by jala15** [comment]
Should be fixed in next release as I saw it is already changed in beta-testing
