### ISSUE TITLE
Question/suggestion - Unload to the floor? (Previously made crop mount on floor)

### ISSUE THREAD

**Issue by fudoido** [Stephan-S/FS19_AutoDrive#129]
Hello Stephan.
i am wondering if i create a heap of any crop in the floor, and then make autodrive go through it with the unload function, will autodrive unload in that position?
Or does autodrive only unload in the selling/silo points?
If it doesnt unload into the previous made mount of crop, would it be possible to create a new "unload" target for manual unload?
Idea behind this question comes with support with courseplay. Courseplay allows us to create reverse courses, but autodrive does not. As i imagine that implementing reverse autodrive is hard, the idea of creating a "forced/manual unload" target would help on hard to acess unload triggers. We would use autodrive to force unload in a nearby area to that trigger, and then use courseplay "shovel mode" (when it gets back to active in fs19 version, until then we can do it manually but would be nice to have autodrive dropping it nearby) to pick up what autodrive unloads in the floor into the nearby unload trigger.
If you manage to find a way to implement reverse autodrive, learning from courseplay maybe, it would be even better.
Any of these things would be possible?

**Comment by TyKonKet** [comment]
#749

**Comment by Stephan-S** [comment]
Cleaning up old issues.
