### ISSUE TITLE
Fehler bei Drescherabtanken

### ISSUE THREAD

**Issue by TripleX1978** [Stephan-S/FS19_AutoDrive#1290]
Hallo!

Ich habe versucht die Drescher mit CP und AD abzutanken.
Es läuft auch soweit alles bis zu dem Zeitpunkt an dem der Drescher abgetankt werden soll.
Der Abfahrer funktioniert, aber der Drescher hält an, klappt das Mähwerk ein und versucht zurück zum Startpunkt (z.B. Feld 30) zurück zu fahren.
Ich habe es auch schon mit verschiedenen Drescher-Mähwerk-Kombinationen versucht.
Immer mit dem gleichen Ergebnis.
Ich nutze CP 6.01.00394 und AD 1.1.0.4.
Aber auch mit einer früheren Version von CP (6.01.00335) passiert immer das gleich.

Gruß
André

**Comment by Tensuko** [comment]
Warum nicht CP 397 ? https://github.com/Courseplay/courseplay/releases
Hast du zufällig am Startpunkt Enden eingeschaltet ?

**Comment by TripleX1978** [comment]
Hab CP jetzt auf 397.
Immer noch das gleich Problem. 
Am Startpunkt enden hatte ich aktiviert und deaktiviert ausprobiert.

**Comment by Tensuko** [comment]
Was mir noch einfällt: Drescher fährt selber abtanken an/aus und mit welcher Einstellung hast du den Drescher gestartet, am ersten wegpunkt oder nächsten, etc. Ansonsten fällt mir keine Option mehr ein die von CP für das Problem verantwortlich sein könnte.

**Comment by TripleX1978** [comment]
Wo kann man das denn einstellen Drescher fährt selber abtanken?
Hatte beiden Varianten beim Drescherstart schon ausprobiert.

**Comment by Tensuko** [comment]
Unter den Advanced Settings, aber das ist standartmäßig ausgeschaltet, von daher wenn du das nicht kennst gehe ich nicht davon aus das es eingeschaltet ist :)

Aber dann gehen mir für CP auch die Ideen aus, warum er dies tut.
Ein logfile solltest du trotzdem mal anhängen. (Drag and Drop in die Kommentarbox)

**Comment by Stephan-S** [comment]
Kann es sein dass du die Einstellung in CP aktiviert hast, dass er 
AutoDrive - For unload/refill
nutzen soll?

**Comment by TripleX1978** [comment]
Ja...das habe ich so eingestellt.

**Comment by Stephan-S** [comment]
Da ist der Fehler versteckt :-)
Lass das weg. Sonst probiert er auf dem Drescher AD zu starten. Das soll nicht passieren.

**Comment by TripleX1978** [comment]
Hat sich das geändert?
Habe in diversen Videos auf Youtube gesehen dass man das so machen soll damit der Drescher den richtigen Abfahrer ruft.

**Comment by Tensuko** [comment]
Du willst doch nicht das der Drescher weg fährt, sondern der Abfahrer hin, warum sollte also der Drescher AD benutzen ? Auf die Idee wäre ich nie gekommen :)

**Comment by TripleX1978** [comment]
Wofür ist denn die Einstellung use AD for unload/refill?

**Comment by Tensuko** [comment]
Genau das was da steht, unload und refill.
Wenn du mit CP ein Feld düngst oder bestellst, kannst du die Option einschalten und es wird AD benutzt um Saatmaschine/Düngerstreuer wieder auf zu füllen. Oder ein Sammelwagen der Gras/Stroh sammel wird dann von AD zum Silo gefahren und wieder zum Feld. Eben entladen/auffüllen.

**Comment by TripleX1978** [comment]
Danke für die Hilfe.
Bin noch nicht sooo lange im LS unterwegs.
War fest der Meinung ich hätte das mal gesehen dass man das so einstellen muss.
Werde es gleich mal ausprobieren.

**Comment by TripleX1978** [comment]
Hab gerade mal getestet.
Jetzt läufts...ich Depp!!!🙈
Beim Versuch abzutanken ist es jetzt aber so, dass er viel zu nach an den Drescher ranfährt und das Rohr nicht erwischt obwohl ich den Abstand zum Rohr schon von 0-5m ausprobiert habe. 
Habe aktuell einen Drscher im Einsatz mit 7,9m haltbaren Rohr.
Dann das die Ursache sein?

**Comment by TripleX1978** [comment]
Problem gelöst.
Es lag an dem Drescher-Mod ansich...egal welche Rohrkonfiguration genommen wurde.
Danke nochmal für die Unterstützung.
