### ISSUE TITLE
[BUG] Target point invisible in hud

### ISSUE THREAD

**Issue by Opa-Andre** [Stephan-S/FS19_AutoDrive#1292]
AutoDrive Version: 1.1.0.4
Release or selbsterstelltes zip: Release
Karte (falls relevant): Alle
Fahrzeug(art) (falls relevant): fahrzeugunabhängig

Problem: Zielpunkte im Bereich "erster Zielpunkt" werden im Hud nicht mehr angezeigt

Repro Schritte:
1. Auf einer Karte AD Streckennetzwerk verwenden, wo alle Ziele in Ordnern verteilt sind (Standardordner ist leer)
2. Streckennetzwerk exportieren mit der neuen Exportfunktion.
3. Neues Spiel / Savegame starten für die genutzte Karte
4. AD Hud aufrufen (ist per "default" ja aus).
5. Streckennetzwerk importieren.
6. Zielfeld anklicken - ist leer 
7. In das AD Optionsmenü gehen und "Ordner nutzen" aktivieren.

Ergebnis:
- Wenn man jetzt ins Zielfeld klickt, kann man die Ordner / Zielpunkte sehen. 
Fehler: Wählt man einen Zielpunkt aus, bleibt jedoch anschließend das Zielfeld immer noch leer. Es erfolgt keine Anzeige des gewählten Zieles. 

Schaltet man den Debug Modus ein, kann man sehen, dass der gewählte Zielpunkt gesetzt ist. Startet man AD, fährt es auch zum Ziel. Bei Modi, welche 2 Zielpunkte haben, tritt der Fehler nur im ersten Zielpunkt (obere Zeile) auf. 

Das Verhalten (leeres 1. Zielfeld) bleibt nun bis zum Beenden / Neustart / laden des Savegames bestehen. Desweiteren findet man einen einmaligen Eintrag in der Log.txt, welcher auf einen LUA Fehler in einem der AD Scripte verweist.

**Comment by Iwan1803** [comment]
Nur noch mal zum Verständnis:
wenn man per Routen Manager ein Streckennetz importiert, dann wird dies zwar gemacht, aber die Zielpunktliste bleibt leer, bis man das Savegame neu lädt. Korrekt?
Könntest du vielleicht das Log noch anhängen, wo die Fehlermeldung drin ist?

**Comment by Opa-Andre** [comment]
@Iwan1803 : Hatte gestern mit baloo darüber im Discord geschrieben, er meinte ich solle es hier auch nochmal posten, damit es nicht in Vergessenheit gerät. Log bräuchte er nicht, er schaut sich es direkt selbst nochmal an. 
Ich nehme an, dass der Fehler dadurch auftritt, da ja standardmäßig die Einstellung "Ordner verwenden" ausgeschaltet ist. Wenn man also bei neuem Savegame die Streckendatei lädt, gibt es nichts zum Anzeigen, da ja alle Zielpunkte in Ordnern liegen - beim prüfen kommt es also zum Fehler und die Routine schlägt fehl. Dadurch läuft dieses Script für die Anzeige im Hud nicht mehr - was erst durch einen Neustart des Spiels behoben wird. Ich kann das aber gern nochmal machen und den Fehler aus der Log posten.

**Comment by Opa-Andre** [comment]
So, hier nun mit log & Bilder, ab Start eines neuen Savegames :)
Vielleicht noch wichtig: Nutze dazu die Map Oberthal, damit hat AD keine vorkonfigurierte "init" Kursdatei, da diese nicht in AD enthalten sind. 

Schritte: 
1. Neues Savegame gestartet
2. Spiel-Einstellung geändert "automatischer Motorstart" => "aus"
3. In Traktor eingestiegen, zu einem Trailer gefahren, angekuppelt.
4. Savegame erstellt, Screenshot 1
![Farming Simulator 19 04 04 2020 11_46_29](https://user-images.githubusercontent.com/38733952/78424463-045e7200-766e-11ea-9bc3-4250202b32c5.png)
5. Edit Button angeklickt, danach das Diskettensymbol zum Laden des Streckennetzwerkes, Streckennetzwerk geladen
![Farming Simulator 19 04 04 2020 11_47_21](https://user-images.githubusercontent.com/38733952/78424571-d7f72580-766e-11ea-8277-1e10b221e816.png)
6. Streckennetzwerk wurde geladen, ist nun sichtbar
7. Zieldialog im AD angeklickt -> reagiert nicht (da die Zielpunkte in Ordnern sind)
8. AD Optionsmenü aufgerufen -> "Ordner verwenden" von "Nein" auf "Ja" umgestellt
9. Zieldialog aufgerufen, im Ordner "Hof" den Zielpunkt "H-Stroh&Futterlager" ausgewählt.
![Farming Simulator 19 04 04 2020 11_51_06](https://user-images.githubusercontent.com/38733952/78424733-ce21f200-766f-11ea-95ac-d6e4666dd699.png)
10. Auch nach der Auswahl bleibt im Hud das Ziel leer.
11. Savegame erstellt
12. AD aktiviert - Traktor fährt zum Zielpunkt (-> im HUD immer noch leer)
![Farming Simulator 19 04 04 2020 11_52_31](https://user-images.githubusercontent.com/38733952/78424791-222cd680-7670-11ea-90a5-62dbe369d411.png)
13. Traktor am Ziel angekommen, Screenshot & Savegame erstellt.
![Farming Simulator 19 04 04 2020 11_53_28](https://user-images.githubusercontent.com/38733952/78424850-66b87200-7670-11ea-81ca-a631bceff129.png)
14. Modus gewechselt (Liefermodus), Abladepunkt gesetzt -> dieser wird im HUD angezeigt
![Farming Simulator 19 04 04 2020 11_54_51](https://user-images.githubusercontent.com/38733952/78424872-9bc4c480-7670-11ea-9987-479523759dce.png)
15. Nochmals versucht, die Zieleingabe für den Beladepunkt einzustellen - keine Änderung, diese HUD Zeile bleibt leer.
16. Savegame erstellt, Spiel beendet.
[log-alt.txt](https://github.com/Stephan-S/FS19_AutoDrive/files/4431167/log-alt.txt)
17. Savegame geladen und in Traktor eingestiegen -> HUD zeigt nun bei beiden Zielpunkten "Hof Parken 01" - dies ist der erste Zielpunkteintrag in der Streckennetzwerkdatei.
![Farming Simulator 19 04 04 2020 12_01_03](https://user-images.githubusercontent.com/38733952/78424945-3de4ac80-7671-11ea-81c1-7963c67c117f.png)
18. Zielpunkte geändert - > funktioniert, Spiel gespeichert und beendet.
![Farming Simulator 19 04 04 2020 12_07_14](https://user-images.githubusercontent.com/38733952/78424990-94ea8180-7671-11ea-84e1-67560f26e9c5.png)
[log-neu.txt](https://github.com/Stephan-S/FS19_AutoDrive/files/4431175/log-neu.txt)
19. Savegame geladen -> Zielpunkte aus dem vorherigen Savegame wurden übernommen, d.h. alles OK.

Hoffe, das hilft Euch weiter bei der Eingrenzung. :)

**Comment by Opa-Andre** [comment]
P.S. Die häufige "Savegame" Speicherung hab ich gemacht, damit ihr in der Log sehen könnt, wann was auftritt.
