### ISSUE TITLE
[BUG] Truck with Tandem Trailer and Combine Colission

### ISSUE THREAD

**Issue by Tadeloach** [Stephan-S/FS19_AutoDrive#1295]
**AutoDrive Version:** 1.1.0.4, but this has happened in all version for me.   I just haven't done a ticket yet.
**Release or Custom Zip:** Release  
**Map (If applicable):** All  
**Vehicle / Type (If applicable): Truck with Tandem Trailer and any combine   
**Multiplayer or Singleplayer:** Singleplayer  

**Describe the bug**  
When a truck has tandem trailers and a combine calls to offload, if the first trailer is filled BEFORE the Combine is empty, the truck will pull up and in front of the combine for some reason.

**If applicable - Steps to reproduce the behavior**  
Almost positive that courseplay has to be running combine (I have courseplay set for combine to stop during unloading)  First trailer has to be at a level that combine can fill it then truck have to pull forward to let him dump into second trailer.
**Screenshots**  
![image](https://user-images.githubusercontent.com/56048034/78416357-dfc2b580-75ed-11ea-9300-9bb0bd950691.png)

**Comment by Tadeloach** [comment]
Another screen shot
![image](https://user-images.githubusercontent.com/56048034/78459188-ea785b80-767c-11ea-8126-e60aa6d799df.png)

**Comment by Tadeloach** [comment]
I can not confirm that this happens EVERY time with the setup I mentioned in first post.  The only thing I can think of that might fix, and i don't know if this is possible, is somehow set that a truck can never pull forward and then in front of a combine if possible... I don't know.   I wish I could catch video of it happening, but I always find it after it's happened.

**Comment by BloodyRain2k** [comment]
Sadly a case where you have to watch the kettle and hope you can catch proof that it's boiling, aka baby sit the thing.

**Comment by Iwan1803** [comment]
Please update to latest RC and try again.
