### ISSUE TITLE
AD for trains / AD für Züge

### ISSUE THREAD

**Issue by Berios** [Stephan-S/FS19_AutoDrive#1296]
Hallo Stephan!

Erst einmal erneut ein dickes Lob für Deine / eure gute Arbeit. AD ist im LS19 zusammen mit GC und Seasons das absolute Top Script. Vielen Dank, daß ihr uns dieses tolle Script zur Verfügung stellt.

Ich habe eine vielleicht etwas ungewöhnliche Frage / Idee:

Momentan spiele ich die Oberthal (eine echt super schöne 4x Map) wie üblich vollautomatisiert im Singelplayer. Die Oberthal verfügt über ein ausgeklügeltes Zugsystem, welches man eigentlich sehr gut nutzen könnte. Allerdings fehlt in den Züge eine Automatisierung. Sprich, wenn sie fahren, dann fahren sie. Wenn Du sie nicht manuell steuerst, dann fahren sie halt immer ohne Stop im Kreis. Hier würde eine Option "Autodrive" sehr schön sein. Dann könnte man auch die Zugsysteme automatisieren. 
Es würde auch schon reichen, wenn die Züge nur im "Modus 1" (also "fahre zum Zielort") fahren würden. Abladen kann man manuell, das ist zeitlich unproblematisch. Aber wenn man Zielorte (also Außenläger oder Überladepunkte) automatisiert anfahren könnte, dann wäre das echt Klasse. :-)

Ich freue mich schon auf eure Feedback zu dieser Idee / Frage. 

Vielen Dank für eure Mühe und weiter so. :-) Ich bin euer Fan.
Bleibt gesund und munter.

Berios

**Comment by Iwan1803** [comment]
Sorry, aber nein, leider gametechnisch nicht möglich.
