### ISSUE TITLE
Different Problems with Version 1.1.0.4 (Trigger and CP)

### ISSUE THREAD

**Issue by Berios** [Stephan-S/FS19_AutoDrive#1297]
Hallo zusammen!

Erst einmal vielen Dank für eure Mühe und Arbeit. 

Bei der neuen Version sind mir einige "Bugs" aufgefallen - ich denke zumindest, daß es an der neuen Version liegt:

1.) Wenn ich den Modus "Laden und am Zielpunkt abladen" wähle und eine Fracht x aufnehme, dann lädt AD die Ware auf dem nächsten "legalen" Trigger ab und nicht wie eingestellt am Zielpunkt. In meinem Fall kaufe ich Mist auf der Oberthal ein und überfahre den Verkaufstrigger am Dünger- und Saatguthandel direkt im Anschluß. Mein Ziel ist eigentlich die Düngerfabrik, wo ich den Mist abladen will. AD stoppt aber sofort an dem besagten Verkaufstrigger des Düngerhandels und entlädt dort die gesamte Ladung Mist um dann zu dem einstellten Punkt "Mist Düngerfabrik" weiterzufahren. Alles andete funktioniert dann zwar, aber der LKW ist natürlich leer. Das war bei AD 1.1.0.2 so nicht der Fall. Hier fuhr er anstandslos über die nicht ausgewählten Trigger weg und lud wie gewünscht erst am Zielpunkt ab.

2.) Wenn ich mit AD ein Feld anfahre und dann die neue Funktion "CP" wähle (oder CP am Zielpunkt aktiviere), dann "hängt" sich das Fahrzeug auf und bleibt stehen. Wenn ich das Fahrzeug manuell auf das Feld mit der jeweiligen CP Strecke fahre, dann kann ich CP aktivieren "Start am ersten Wegpunkt" und das Fahrzeug reagiert wie gewohnt (Fährt den ersten Punkt an, aktiviert die Werkzeuge und beginnt die Arbeit). Da ich in den letzten Tagen mit der gleichen CP version (0397 . letztes Release) reibungslos gespielt habe und dazu mit AD 1.1.0.2, müßte es eigentlich an der Version 1.1.0.4 liegen.

Vielleicht bringt euch das ein wenig weiter. :-)

Vielen Dank für euer Engagement. 

Berios

**Comment by Iwan1803** [comment]
Zu 1.: ein Fix ist in Arbeit, soweit ich mich erinnere.

Zu 2.: das ist wohl ein Problem von CP, was ich auch ohne AD-Aktivierung festgestellt habe. 
CP macht momentan häufiger "lustige" Sachen, welche ich nicht nachvollziehen kann. 
Bsp. 1: ich stelle die Saatmaschine aufs Feld und sie sollte mit "Start am ersten Wegpunkt" loslegen, aber nichts passiert. Stattdessen zieht CP enorme CPU-Leistung, bis ich es beende. Fahre ich dann ein Stück vor, klappt es sofort und problemlos.
Bsp. 2: ich entlade mit einem gespeicherten CP-Kurs mein Durchfahrsilo. Die ersten Runden klappen problemlos, doch dann wartet er nicht mehr darauf, das er die ca. 8k Liter reinkippen kann, sonst entlädt einfach auf den Trigger und kippt dort ein ums andere mal ab. Ich hab den Kurs auch schon mehrfach neu aufgezeichnet, aber es führte immer zum gleichen Ergebnis: Silagehaufen auf dem Trigger.

**Comment by Berios** [comment]
Das mit der enormen Berechnungsdauer und hohen CPU - Leistung von CP habe ich auch festgestellt. Bisher habe ich auf der Michamp gespielt, da kam das scheinbar nicht raus. Erst jetzt auf der Oberthal stelle ich das gleiche Phänomen fest. Hatte gedacht, es läge evntuell an der Schnittstelle zwischen AD und CP die es jetzt gibt.

Danke für die Info. :-) Damit können wir Punkt 2 dann streichen.

**Comment by Iwan1803** [comment]
Aufgrund meiner Beobachtungen würde ich zu Punkt 2. eigentlich auch ausschließen, das es an AD liegt, da AD zu dem Zeitpunkt keine Rolle gespielt hat, aber wer weiß...

**Comment by Axel32019** [comment]
Probiert mal die Fruchtumfahrung in CP zu deaktivieren, dann werden die Berechnungspausen von CP gefühlt weniger.

**Comment by Iwan1803** [comment]
Fruchtumfahrung deaktivieren für eine Saatmaschine, welche auf einem gegrubberten Feld steht oder für einen Radlader an der BGA? 😂
Es wird Zeit, das CP endlich wieder ein paar Entwickler zu laufen....

**Comment by RedMonster-HUN** [comment]
Why can't you just write in english? That way more poeple could understand you.

**Comment by Axel32019** [comment]
Für die Feldarbeiten - Ernte- und Saatmaschinen

**Comment by Iwan1803** [comment]
@RedMonster-HUN not everybody can speak English 😉

@Axel32019 wenn da Frucht wäre, dann würde ich es ja verstehen, aber auf einem leeren Feld?
Zumal das Problem ja auch verschwand, als ich ca. 1m vorgefahren bin. Damit war ich immer noch ca. 30-40m vom Startpunkt entfernt.

**Comment by Tensuko** [comment]
Weitere Entwickler werden nicht das Problem beheben, dass die GIANTS Engine aufgibt bei der Wegberechnung...
Je komplexer der Weg zum ersten Startpunkt, desto länger dauert die Berechnung.

Wenn man mit CP so starten kann, aber über AD nicht, liegt es vlt daran wie AD CP starten lässt.

**Comment by Iwan1803** [comment]
@Tensuko lies noch mal genau, wo meine Probleme liegen/lagen, denn an der Stelle war AD (eigentlich) in keinster Weise involviert. Auf dem Feld stand die Saatgutmaschine so, das der Trecker mit seiner Schnauze gerade auf den Zielpunkt schaute.
Es ist mir schon klar, das Giants an einigen Problemen auch nicht ganz unschuldig ist, aber wenn einige Modi plötzlich "verrückt" spielen, welche mal problemlos funktioniert haben....
Ich kontrolliere nicht permanent, ob es LS19-Updates gibt, aber zumindest in den letzten Wochen ist mir nichts aufgefallen.

**Comment by Tensuko** [comment]
Wenn dir sachen Auffallen die du dir nicht erklären kannst, hätte ich eine gute Adresse für dich wo du dich mit so etwas melden kannst ;)

Dein Beispiel eins ist mir noch nicht untergekommen, das zweite ja ist richtig der Schaufelmodus läuft noch nicht gut. Aber das soll hier jetzt nicht das Thema sein.

Ich habe jedenfals eben ein 3:13min langes und 710MB großes Video aufgenommen wo AD vom Shop zum Feld fährt und seine Arbeit vollrichtet, das gleiche nochmal mit den richtigen Einstellungen *hust* CP am ersten Wegpunkt starten... und auch das ging ohne Laderuckler und gestotter.

Für das Thema hier, dass AD 1.1.0.4 und CP 397 so nicht funktioneiren, gibt es von mir ein klares 'can't reproduce' (Video folgt, muss nur sehen wo ich es am besten hochlade).

**Comment by Berios** [comment]
Wenn ich mit AD meinen Zielpunkt außerhalb des Feldes erreiche (also den Punkt "Feldanfahrt" und AD sich deaktiviert hat, dann macht CP leider Zicken in Bezug auf die Anfahrt zum ersten Wegpunkt.
Ich versuche das Gerät stehend auf dem letzten AD - Punkt (AD ist dann bereits aus) zu aktivieren um den ersten Wegpunkt des gewählten CP - Kurses anzufahren. Das macht CP nicht. Das Gerät bleibt einfach da stehen, wo es ist. Wenn ich es aber auf das Feld fahre, dann macht es CP auf einmal wieder.
Ich muß allerdings ehrlicher Weise dazu sagen, daß ich mit der Kombo CP 0397 und AD 1.1.0.2 auf der Michamp dieses Problem nicht hatte. Da hat CP ganz normal gearbeitet und hat den ersten Wegpunkt auch von außerhalb des Feldes angefahren. Ich denke in diesem Fall, daß es tatsächlich an der Schnittstelle zwischen AD und CP liegt. Allerdings berechnet CP wirklich die Kurse ewig (auch wenn man diese Speichern möchte, dauert das ewig). Vielleicht aber auch eine Folge der Schnittstelle - ich weiß es einfach nicht. In Bezug auf die Scripte kann ich einfach nicht mitreden. Daher habe ich es mal beschrieben. Vielleicht ist das Feedback für beide Entwicklerteams interessant und nützlich. :-)

**Comment by rmn18** [comment]
was das ruckeln angeht  kann ich von mir so viel schreiben das es nicht CP und auch nicht AD ist die das verursachen ,ich hatte Mods drin die ohne Fehler waren zumindest in der Log Datei ,aber im Game ne Menge Ruckler verursachten , auch 4x Maps miot viel Produktionen ruckeln gerne mal ,hab nen Ryzen 5 3600 mit ner RX 5700 und 32GB Ram ,also an der Hardware liegt das sicher nicht ,ich spiele nur noch Vanilla hier im LS zusammen mit AD und CP ,und das ruckeln hat ein Ende gefunden .

**Comment by Tensuko** [comment]
CP Kurese laden kannst du auf 2 Arten machen:
Am Start alle Laden (advanced settings, 2te Seite) oder nur wenn du sie brauchst.
Also hast du entweder beim laden deines Savegames eine sehr lange ladezeit oder eine kürzere für den Kurs den du brauchst. Je nach größe des Feldes (und der Arbeitsbreite) sind das eine gewisse Menge Wegpunkte die geladen werden müssen. Das hat aber nichts mit dem angesprochenen Problem zu tun, da der Pathfinder den Weg on the fly berechnet.

@rmn18 
Das sollte auch so sein :)
Es kann durchaus zu rucklern kommen bei der Berechnung des Pathfindings, wenn man z.B. um ein Feld und durch Bäume hindurch fahren müsste, dann wird mit Berücksichtigung des Fahrzeugs ein weg gesucht. Je komplexer, desto länger kann es dauern. Sobald mehr Platz da ist, ist es nurnoch ein kurzer einbruch bei den FPS und der Kurs ist da (wenn man den überhaupt bemerkt).

Fertig und Perfekt ist das noch lange nicht, aber es bremst zu 100% nicht die CPU.

**Comment by rmn18** [comment]
Das bischen Ruckeln im berechnen merke ich garnicht ,mit 50 sind meine Auge eh nicht mehr so fit *lach ,ihr macht da alle einen guten job :-) ohne AD und CP macht LS eh keine mehr .

**Comment by Tensuko** [comment]
So, YT hat es endlich gefressen.
Im ersten Teil habe ich etwas verkackt, weil ich bei CP 'nächsten Wegpunkt' statt den ersten drin hatte, aber egal, funktioniert beides.
Für CP braucht ihr nur den Feldkurs laden, den Modus einstellen, auf ersten Wegpunkt einstellen und eventuell Spurreißer an oder aus je nachdem was ihr wollt. Mehr ist an sich nicht nötig. Bei AD den CP Knopf einschalten und AD starten.

Wenn das bei dir @Berios nicht funktioniert, liegt es an etwas anderem. Ein logfile könnte hierbei hilfreich sein. Für CP wären die Debugchannel 7 12 und 14 interessant.

Video:
https://www.youtube.com/watch?v=OLap4OxnEUs

**Comment by Berios** [comment]
@Tensuko 
Vielen Dank für die Info. Eben noch eine Frage:
Hast Du mit vorgegebenen Geräten oder mit Mods getestet?
Ich habe den Tag über mal einige Sachen probiert und festgestellt, daß die spieleigenen Maschinen tatsächlich das Ganze ohne Mucken machen. Bei Mods hingegen funktioniert es scheinbar nicht - ich habe einige Mod Drescher und Mod Traktoren versucht, welche alle am Ausgangspunkt vor dem Auffahren auf das Feld einfach stehen bleiben und nicht den ersten Wegpunkt anfahren. Solltest Du eine andere Feststellung gemacht haben, dann muß ich mir meine Log mal näher anschauen. Diese ist aber eigentlich soweit sauber in Bezug auf die verwendeten Mods, Courseplay und AD. 

Aber super, daß Du den Test gemacht hast. Vielen Dank nochmals dafür. :-)

**Comment by GitTomahawk** [comment]
Fehler 1 macht mir auch Probleme, wenn z.B. auf dem Weg zum Ziel der Abfahrer an einem meiner anderen Silos vorbei kommt. 
@Iwan1803: Du hast geschrieben Fix ist ievtl. in Arbeit - gibts dafür einen separaten Issue? (Ich finde keinen)

**Comment by Iwan1803** [comment]
Da viele Probleme in Discord gemeldet werden, gibt es nicht für alles ein Issue 😉
