### ISSUE TITLE
[BUG] Mouse Over - Wrong German Discription on Targetedit

### ISSUE THREAD

**Issue by Tensuko** [Stephan-S/FS19_AutoDrive#1298]
AutoDrive Version: 1.1.0.4
Release or selbsterstelltes zip: Release
Karte (falls relevant): Alle
Fahrzeug(art) (falls relevant):

**Beschreibe den Bug**
Es gibt beim Editor 2 Buttons für Ziele, das eine mit dem Bleistift scheint eine Editierfunktion für den aktuell gewählten Zielpunkt zu sein, wenn man mit der Maus drauf hält, wird aber 'neues Ziel erstellen' angezeigt.

**Falls anwendbar - Schritte mit denen ich den Bug nachstellen kann**

**Screenshots**
Mauszeiger wird leider nicht angezeigt.
![Ziel bearbeiten](https://user-images.githubusercontent.com/27344744/78444878-58228880-7679-11ea-8ab1-7360695af974.png)

**Comment by Iwan1803** [comment]
Fixed in the meantime....
