### ISSUE TITLE
[BUG] seeders and fertilizer spreaders no longer refuel alone

### ISSUE THREAD

**Issue by Serge63230** [Stephan-S/FS19_AutoDrive#1299]
**AutoDrive Version:** 1.1.0.4   
**Release or Custom Zip:** Release  
**Map (If applicable):** Marvel manor 1.2.0.0  
**Vehicle / Type (If applicable):**   all the tools used are those of the game.
     - massey fergusson 7719 tractor with kuhn btf 4000 seed drill and kuhn tf1512 tank
     - john deere 6230 r tractor with hari mega 2200 sprayer
     - ih 7210 pro case tractor with kuhn axis 40.2 spreader
**Multiplayer or Singleplayer:** Singleplayer  

**Describe the bug**  
Good evening
I do not know if it is a bug or if it comes from my game, but since the release of version 1.1.x.x of autodrive, my seeders and my fertilizer spreaders no longer refuel alone.
they are waiting in front of the silo and I have to start the refueling.
With previous versions of autodrive 1.0.x.x, it worked
I haven't changed any mod, I just updated autodrive.

since the beginning of my game, I use the seed and fertilizer huts of the MF building pack [https://www.farming-simulator.com/mod.php?lang=fr&country=fr&mod_id=129738&title=fs2019](url)

does anyone have the same concerns ?

[log.txt](https://github.com/Stephan-S/FS19_AutoDrive/files/4432285/log.txt)

**Comment by Crinouche** [comment]
Hello,

I also have the same problem.
My seed drill is equipped with the fertilizer function and autodrive fills up with fertilizer but not with seed.

**Comment by Stephan-S** [comment]
As long as you apply the golden rule of the 1.1.x versions, most triggers work fine:
Make sure your trailers reach the load/unload triggers before your vehicle reaches the destination point.

There are some exceptions right now when it comes to loading both seed and fertilizer but that will be fixed with the next release.

**Comment by patch110** [comment]
Has this issue been fixed as i am having this problem still?

**Comment by Serge63230** [comment]
sometimes the tractor reloads the seeder by itself and sometimes it waits for me to manually start the reloading

**Comment by Iwan1803** [comment]
Same problem like here: https://github.com/Stephan-S/FS19_AutoDrive/issues/1421

**Comment by Iwan1803** [comment]
Please download 1.1.05.-RC4, try again and then post a feedback.
Bitte lade 1.1.05.-RC4 herunter, versuch es erneut und poste dann ein Feedback.

Changelog: https://github.com/Stephan-S/FS19_AutoDrive/wiki/Release-Notes

**Comment by patch110** [comment]
I am using the RC4 version on my current map (Hunter Farm) and it seems to work without issue. No matter if the seeder has Fertilizer or Seeds left in AutoDrive fills both reagardless.

Richard

**Comment by Iwan1803** [comment]
Great and thanks for the feedback.
