### ISSUE TITLE
Trafic problem

### ISSUE THREAD

**Issue by RUGhost** [Stephan-S/FS19_AutoDrive#130]
I'm weak in English and German. So I drop a video. Please solve this problem.
https://youtu.be/8SpqLSMfRVY

**Comment by Anonymous-any** [comment]
https://github.com/Stephan-S/FS19_AutoDrive/issues/79

**Comment by Stephan-S** [comment]
Hey @RUGhost 
I stand by my previous comment:
https://github.com/Stephan-S/FS19_AutoDrive/issues/79#issuecomment-485284958

So as long as Giant`s default AI traffic behavior is to stop if a helper controlled vehicle is nearby, there is not much I can do. Even if I detect traffic (which I already tried), then the ai traffic will just stop in the middle of the road and create a total traffic jam.

Best regards,
Stephan
