### ISSUE TITLE
Agro Masz Salvis 3800  doesen´t refill Fertilizer and Seeds

### ISSUE THREAD

**Issue by Astanorr** [Stephan-S/FS19_AutoDrive#1300]
AutoDrive Version: 1.1.0.4

Karte: Ravenport
Fahrzeug :Agro Masz Salvis 3800

**Beschreibe den Bug**
Ich habe versucht bei einer Feldmission, mit Leihmaschienen, meine Sähmaschiene automatisch befüllen zu lassen. (Dünger und Saatgut) Obwohl ich die Reihenfolge beachtet habe, also das letzte Silo als Filltype ausgewählt habe, öffnet sich nur die vordere  Klappe für den Dünger welcher auch prima befüllt wird. Unter dem Trigger für Saatgut fährt er allerdings duch, vermutlich da sich die Klappe nicht öffnet. 
Jetzt stellt sich für mich natürlich die Frage ob das ein Maschienenspezifisches Problem ist, oder ob das Problem mal wieder vor dem Bildschirm sitzt?

Grüße 
Asta

**Comment by Iwan1803** [comment]
Ist das eine Saatmaschine, wo nacheinander die Luken zum Befüllen geöffnet werden müssen?

**Comment by Iwan1803** [comment]
Bitte auf aktuellste RC aktualisieren und erneut probieren.
Sollte das Problem noch bestehen, dann bitte ein neues Issue aufmachen.
