### ISSUE TITLE
[BUG]Abfahrer startet, obwohl Abtanken noch läuft / Driver starts, although unloading is still running

### ISSUE THREAD

**Issue by Christoph1978** [Stephan-S/FS19_AutoDrive#1301]
AutoDrive Version: 1.1.0.4
Release or selbsterstelltes zip: Release
Karte (falls relevant): Alle
Fahrzeug(art) (falls relevant): Mähdrescher

**Beschreibe den Bug**
Wenn ich einen Drescher selber fahre, stelle ich den Abfahrer im Modus „Abholen und Abliefern“ an den Feldrand. Beim Abtanken des Dreschers fährt der Abfahrer bei der eingestellten Füllhöhe des Hängers los, obwohl das Abtanken des Dreschers noch läuft.

Vielleicht wäre hier eine Wartezeit sinnvoll.

Darüber hinaus, vielen Dank an die Modder für die wirklich tolle Arbeit! Wünsche einen schönen Sonntag und bleibt gesund!

**Comment by RalfGorden** [comment]
du musst   den Abfahrer im Modus „Drescher abfahren“ an den Feldrand stellen

**Comment by Christoph1978** [comment]
Ok dann ist da mein Fehler. Hatte das vorher mit dem Modus "Drescher abtanken" und manueller Anforderung gemacht und das hatte mir nicht gefallen. Daher hab ich dann den Modus geändert und nicht das manuelle Anfordern.

Vielen Dank für den Denkanstoß!
