### ISSUE TITLE
[BUG] Parking spot isn't saved?

### ISSUE THREAD

**Issue by jvalst** [Stephan-S/FS19_AutoDrive#1302]
**AutoDrive Version:** 1.1.0.4 
**Release or Custom Zip:** Custom Zip
**Map (If applicable):** Oberthal
**Vehicle / Type (If applicable):** All  
**Multiplayer or Singleplayer:** Singleplayer  

**Describe the bug**  
I thinkt he parking spots of the vehicles isn't saved? Is that right, or is this a bug? If so, it should be nice to save those spots as well, so after a reload, we can just put the vehicles back to their original parking spots. 

**If applicable - Steps to reproduce the behavior**  
Just save some parking spots for vehicles, save the game, on return the spots are gone.

**Comment by Iwan1803** [comment]
Assigned parking lots will be saved in the vehicles.xml.
Please check this and also check the log.txt for error or warnings.

**Comment by TyKonKet** [comment]
Yes, I agree with @Iwan1803 
Parking spots are saved (on vehicles.xml)
The only reason why they would not be saved, is some error during the savegame writing, so please check the log.

**Comment by jvalst** [comment]
Hmm weird, my log just said, game succesfully saved. And in the vehicles.xml I see the parkDestination correctly: "parkDestination="2"". Unfortunately if I restart my savegame, the P icon isn't white anymore but greyed out. The Vehicles.xml still shows the parkDestination="2". Looks like the loading of that part isn't correct or something?

**Comment by Iwan1803** [comment]
Please update to latest RC and try again.
If the problem still exists, please open a new issue.
