### ISSUE TITLE
Unloading doesnt work 1.1.0.4 MP

### ISSUE THREAD

**Issue by GitTomahawk** [Stephan-S/FS19_AutoDrive#1304]
**AutoDrive Version:** 1.1.0.4
**Release or Custom Zip:** Release  
**Map (If applicable):** All  
**Vehicle / Type (If applicable):**   
**Multiplayer or Singleplayer:** MP

Unloading does not work in several modes. (Deliver, Puckup&deliver, Combine Unloader)
It drives to the unloading point and stops there.
Disabling and enabling AD then instantly starts the unloading.
Next circle exactly the same issue.
I tried changing "Siloabstand" to different values but it had no effect.

P.S. Konversation gerne auch in Deutsch

**Comment by Iwan1803** [comment]
Zielpunkt zu dicht am Trigger?
Ein Screenshot inkl. AD-Linien wäre vielleicht hilfreich.

**Comment by GitTomahawk** [comment]
Die Wegpunkte/Trigger haben in der 1.0.7.2 noch funktioniert (haben unserern Server direkt auf die 1.1.04 geupdated)
![2020-04-06 11_27_40-Window](https://user-images.githubusercontent.com/55877391/78544043-d86ff780-77f9-11ea-94fb-2e91f2652f7a.png)

**Comment by Iwan1803** [comment]
Seit der 1.1.x.x hat sich da was geändert. Zieh den Zielpunkt weiter nach vorne und schon sollte es wieder klappen.

**Comment by GitTomahawk** [comment]
Ich habe den Marker jetzt deutlich nach vorne geschoben und den "max. Siloabstand" vorsorglich auf 100m gesetzt - keine Verbesserung. Die Fahrzeuge stoppen an exakt der gleichen Stelle wie vorher (betrachtet man bei unterschiedlich langen Zügen die Position der Abladeklappe).

![2020-04-06 22_24_46-Farming Simulator 19](https://user-images.githubusercontent.com/55877391/78644732-a07aba00-78b6-11ea-91d6-f8e158c93677.png)
![2020-04-06 22_38_20-Farming Simulator 19](https://user-images.githubusercontent.com/55877391/78644734-a2447d80-78b6-11ea-839e-761c53e35640.png)

**Comment by Iwan1803** [comment]
Könntest du an der Stelle manuell abladen?
Ist das ein Mod-Auflieger und klappt mit dem das Abladen an anderen Stellen?

**Comment by Napoleon231187** [comment]
funny you mention that problem. I had that Problem until 1.1.0.4 after 1.1.0.4 it has started working again :-)

**Comment by GitTomahawk** [comment]
Ja die beiden Anhänger (im Screenhot) sind gemodded, aber lediglich ein paar angepasste Parameter (z.B. Abladegeschwindigkeit).
Mit einem Originalen habe ich aber das gleiche Problem.
Manuell abladen an der Stelle wo er stehen bleibt funktioniert.
Wenn ich ihn de- und wieder aktiviere läd er auch sofort ab. Bei nem Zug mit Ladefläche und Anhänger (wie im 2. Screenshot) lädt er dann nur das auf der Ladefläche ab und fährt dann wieder zum Drescher,

**Comment by kostakanista** [comment]
Muß GitTomahawk leider zustimmen. Bei mir das gleiche. Alles mit original Fahrzeugen getestet. Nur ist es bei mir nicht bei jedem Trigger. Manche gehen noch vom alten Stand, bei manchen mus ich nur den Marker vorschieben und ander gehen überhaupt nicht.

**Comment by GitTomahawk** [comment]
Ich habe jetz auch ein Abladestellen entdeckt, bei der es zu funktionieren scheint.
Ich kann da allerdings keine Besonderheit entdecken. Der Marker sitzt dort direkt hinter der Abladestelle, so dass der Zug komplett auf der Abladestelle steht. 
Der Abstand des Markers zum Abladetrigger scheint hier keine Rolle zu spielen.

**Comment by GitTomahawk** [comment]
Hi, 
mir ist jetzt aufgefallen, dass es nach einem Serverneustart bei (fast) allen Abladestellen funktioniert, so lange, bis andere Spiele beitreten.

**Comment by Iwan1803** [comment]
Bitte auf aktuellste RC aktualisieren und erneut probieren.
Sollte das Problem noch bestehen, dann bitte ein neues Issue aufmachen.
