### ISSUE TITLE
Probleme bei Zuckerrübenernte / Problems during harvest of sugar beets

### ISSUE THREAD

**Issue by TobiHH78** [Stephan-S/FS19_AutoDrive#1306]
**AutoDrive Version:** 1.1.0.4 
**Release or Custom Zip:** Custom Zip

**Describe the bug**  
Habe bei der Ernte von Zuckerrüben ein paar Probleme.

1. Der Abfahrer fährt trotz 100% Beladung nicht zum Entladen. Im Fenster steht der Hinweis "Zurücksetzen vom Drescher" Der Rübenroder ist aber eine komplette Bahn abgefahren ohne das sich der Abfahrer in Bewegung gesetzt hat.

2. Trotz aktivierter Fruchtumfahrung fährt der Abfahrer in die Frucht und kommt dadurch auch dem Roder bei dem Wendemanöver in die Quere.

Bei parallel laufender Getreideernte treten diese Probleme nicht auf.

***
Some issues occured during the harvest of sugar beets

1. The unloader doesn`t drive to the silo after emptying the harvester although he reached 100% fillvolume (and I set it to 80%)

2. The unloader is driving into the fruit, although fruit-bypass is activated on this vehicle. This causes also crashes after the turning manoeuvre of the harvester.

**Screenshots**  

![1_LI](https://user-images.githubusercontent.com/56259322/78505120-900cf700-7771-11ea-8047-c714b3e7647b.jpg)

![2](https://user-images.githubusercontent.com/56259322/78505123-98fdc880-7771-11ea-9516-880eff861f34.JPG)

![3](https://user-images.githubusercontent.com/56259322/78549915-7916e500-7803-11ea-85b5-9f241fc44305.JPG)

![4](https://user-images.githubusercontent.com/56259322/78549943-8207b680-7803-11ea-8e08-4e569640008e.JPG)

![5](https://user-images.githubusercontent.com/56259322/78549963-892ec480-7803-11ea-85fc-a9e719a3c6fd.JPG)

**Comment by BloodyRain2k** [comment]
Some of these problems were why I proposed https://github.com/Stephan-S/FS19_AutoDrive/issues/1254

**Comment by Iwan1803** [comment]
Bitte auf aktuellste RC aktualisieren und erneut probieren.
Sollte das Problem noch bestehen, dann bitte ein neues Issue aufmachen.
