### ISSUE TITLE
Abfahrer fährt beim Gras häckseln immer hinter dem Häcksler

### ISSUE THREAD

**Issue by TripleX1978** [Stephan-S/FS19_AutoDrive#1309]
Egal welche Einstellungen ich vornehme fährt der Abfahrer immer hinter dem Häcksler.
Wenn ich die Geschwindigkeit nicht manuell an die des Häckslers anpasse fährt der Abfahrer immer wieder auf und bremst ab. Mit der Zeit schaukelt sich der Abfahrer dann auf und fährt immer größere Schlangenlinien bis er den Kontakt zum Häcksler verliert.
Bei Wendemanövern bleibt die Kolonne sehr oft stecken weil der Abfahrer den Häcksler wenden lassen möchte, obwohl das schon geschehen ist und der Häcksler fährt nach dem Wendemanöver nicht weiter weil er vermutlich darauf wartet dass der Abfahrer wendet.
Hat jemand nen Tip?
AD: 1.1.0.4
CP: 6.01.00397

Gruß
André

**Comment by Iwan1803** [comment]
Abstand zum Häcksler vergrößern, keine Abfahrer mit Frontgewichten benutzen,...

**Comment by Raven868** [comment]
Habe so ein ähnliches Problem. Mein Abfahre fahrt hinter dem Drescher und bleibt stehen statt unter das Rohr zu fahren. 
AD: 1.1.0.4 
NF 4fach Map

**Comment by TripleX1978** [comment]
@Iwan1803 : Abstand hatte ich von 3-8m getestet, Frontgewichte habe ich keine montiert.

**Comment by TripleX1978** [comment]
@Raven868 : Das Problem hatte ich such mal...lag an dem Drescher-Mod. Und Abstand zum Rohr kontrollieren.

**Comment by Raven868** [comment]
Drescher-Mod habe ich keins drauf. Der Drescher ist einer aus dem Spiel. Abstand zeigt er mir was von -4,25m an in den Einstellungen.

**Comment by TripleX1978** [comment]
Stell mal +0,75 ein.

**Comment by TripleX1978** [comment]
Problem mit dem seitlich Abfahren gerade gelöst.
Nur wie muss ich das einstellen dass bei den Wendemanövern der Kontakt zwischen den Fahrzeugen nicht abreisst? Nachdem der Häcksler gewendet, versucht der Abfahrer das auch. Wenn er dann an den Häcksler ranfährt steht im AD "Drescher wenden lassen" obwohl das schon passiert ist und der Häcksler wartet auf den Abfahrer.

**Comment by Lars-LS17** [comment]
Hallo Zusammen,

ich habe fast das gleiche Problem. Ich habe jedoch Schwadreihen und will diese dann mähen. Auch da habe ich das Problem, dass der Trecker nach dem Wenden des Häckslers nicht wendet, sondern weiterhin den Status hat "Drescher wenden lassen". 

HIer Zwei Screenshot:
![fsScreen_2020_04_09_19_02_42](https://user-images.githubusercontent.com/31773176/78921269-f016dc80-7a94-11ea-98db-b64e75be4203.png)
![fsScreen_2020_04_09_19_04_56](https://user-images.githubusercontent.com/31773176/78921328-0c1a7e00-7a95-11ea-887d-cfcb443f5177.png)

Anbei zusätzlich meine Log.
[log.txt](https://github.com/Stephan-S/FS19_AutoDrive/files/4457599/log.txt)

**Comment by Lars-LS17** [comment]
Heute habe ich nochmal das Mais häckseln getestet, da scheint alles perfekt zu funktionieren.
Kann es Probleme geben mit dem Status des Feldes beim Gras, wo "Geerntet" ist und wo nicht?
Das er das nicht sauber erkennt?

**Gruß und Vielen Dank für eure Tolle Arbeit!!**

**Comment by eric4072** [comment]
Ich glaube dass das Problem bei CP zu suchen ist... Der Häcksler hebt weder die Pickup beim wenden noch senkt er sie beim start...

Hatte einen post im CP-Forum aufgemacht deswegen aber sehr schnell die Lust daran verloren, so wie mit einem da umgegangen wird wenn man Fehler oder ähnliches meldet...

**Comment by TripleX1978** [comment]
Hab es auch nochmal mit Mais probiert.
Da läuft es zwar auch nicht perfekt, aber deutlich besser. Die Abfahrer stehen manchmal auf Berechne Kurs wenn sie an der Reihe sind und fahren dann aber nicht los. AD muss dann deaktiviert, ggf. der Abfahrer ein Stück bewegt und AD dann wieder aktiviert werden.

**Comment by Sp0rTB4cK** [comment]
Hallo,
ich habe ebenfalls das Problem, dass der Abfahrer beim **Gras** Abfahren vom Häcksler an Feldecken unendlich auf das Wenden des Dreschers wartet. Der Häcksler fährt aber nicht weiter, da das Rohr keine Verbindung zum Abfahrer hat. Passiert sowohl mit AI Vehicle Extension Helfer als auch wenn ich den Häcksler selbst fahre.
Bei Mais hab ich es bisher nicht getestet.

AD: 1.1.0.4
Map: Nordfriesische Marsch 4fach

**Comment by rmn18** [comment]
Vllt mal den Beta Zweig von AD testen ,kann ja nicht schaden ;)

**Comment by Matzenie** [comment]
Hallo Leute, ich habe es nun mit den 3 Häckslern aus dem Spiel und 2 Mods getestet. Ich habe das Probleme bei Gras, bei Mais und bei der Schwad. Mit drei verschiedenen Abfahrer Kombis. 
Bei allen drei bleibe ich bei jeder Kurve stehen der Häcksler würde drehen verliert aber den Kontakt in der Kurve. 
Bei Schwad und Gras kommt dazu, dass der Abfahrer mal hinter, mal innen, mal außen fährt es ist aber nicht reproduzierbar. 
Die Häcksler habe ich immer mit CP fahren lassen, habe CP 397 und 399 getestet, mit alle Kurven Varianten und soviel wie möglich im Kreis. Immer das gleiche Bild. 
Bei AD habe ich 1.0.7.4 und 1.1.0.4 getestet, am besten hat die 7.4 beim Mais funktioniert.
Wenn die Experten eine Lösung hätten wäre echt schön. Bin bei 3 Karten am häckslen  und müsste alles von Hand machen.

**Comment by fischi3016** [comment]
> 
> 
> @Iwan1803 : Abstand hatte ich von 3-8m getestet, Frontgewichte habe ich keine montiert.
> Was muss man einstellen damit der Abfahrer seitlich am Häcksler fährt

eigentlich nur bei den Traktoreinstellung Feldbegrenzung auf aus

**Comment by fischi3016** [comment]
![fsScreen_2020_04_25_11_54_57](https://user-images.githubusercontent.com/63921968/80276868-aad8e880-86eb-11ea-9b9b-2c636c8e111c.png)


also bei mit gehts jetzt. Einstellung bei drescher und Traktor standard gelassen Außer Abfahrer automatisch finden auf aus gestellt. Einmal Hächsler AD aktiviert das er den Pfad berechnet und nun kann ich den selber fahren und abfahrer kommt bei drücken bei der Taste abfahrer rufen (bei mir Taste komma)

**Comment by Matzenie** [comment]
Bei mir in Kombi mit CP geht es nicht. Aktuell kann ich kein Häckler mit CP und AD betreiben.

**Comment by fischi3016** [comment]
Cp nutzen wir nicht da wir auf Server spielen.

**Comment by Iwan1803** [comment]
CP für den Häcksler & AD für den Abfahrer funktioniert bei mir einwandfrei. Es wird in RC3 aber noch mal eine Verbesserung kommen.
Bekanntes Problem: Gras, denn durch einen Häcksler geerntet wird es wohl nicht als Frucht erkannt.

**Comment by TripleX1978** [comment]
> CP für den Häcksler & AD für den Abfahrer funktioniert bei mir einwandfrei. Es wird in RC3 aber noch mal eine Verbesserung kommen.
> Bekanntes Problem: Gras, denn durch einen Häcksler geerntet wird es wohl nicht als Frucht erkannt.

Welches ist denn die aktuelle AD-Version?

**Comment by Iwan1803** [comment]
Steht auf der ersten github-Seite 😉

**Comment by Matzenie** [comment]
Kann man denn bei Grass die Abfahrseite beeinflussen?

**Comment by fischi3016** [comment]
> CP für den Häcksler & AD für den Abfahrer funktioniert bei mir einwandfrei. Es wird in RC3 aber noch mal eine Verbesserung kommen.
> Bekanntes Problem: Gras, denn durch einen Häcksler geerntet wird es wohl nicht als Frucht erkannt.

Keine Probleme mehr mit.

**Comment by fischi3016** [comment]
> Kann man denn bei Grass die Abfahrseite beeinflussen?

Bei mir kommt er immer zur linken Seite.

**Comment by Matzenie** [comment]
Bei mir ist es Random, mal da mal ...
