### ISSUE TITLE
F1 - Menü verschwindet - nix geht mehr

### ISSUE THREAD

**Issue by andreasthu** [Stephan-S/FS19_AutoDrive#131]
Hallo Leute
fahre nun gerade meine ersten Kurse ein, dabei ist mir nu nschon mehrfach passiert, das beim drücken einer der drei Tasten zum Kursverbinden (diese mit den Punkten und Linien) plötzlich mein F1-Menü Links oben verschwunden ist, kann nichtmehr die sicht bewegen und der Mauscoursor ist am screen.
kann dann nurmehr mit dem taskmanager das Game beenden und neu Starten.
ist etwas ärgerlich.
in der log datei steht überhaupt nix, keine errors oder warnings
hattet ihr das auch schon?
edit: 
[log.txt](https://github.com/Stephan-S/FS19_AutoDrive/files/3207093/log.txt)
logdatei angehängt

lg
andreas

**Comment by Stephan-S** [comment]
Hey Andreas,

kann es sein das du beim Bedienen des HUDs in das Feld kommst in dem das Abladeziel steht? Dann erwartet er eine Tastatureingabe von dir, um ein neues Ziel auszuwählen.
Ansonsten ist im log File ja tatsächlich kein Fehler auszumachen der das Verhalten erklären könnte.

Die Eingabe kannst du immer mit der "Return"-Taste beenden.
Ich hoffe das löst dein Problem.

Beste Grüße,
Stephan

**Comment by andreasthu** [comment]
Ok, danke,
Werde das das nächstemal versuchen.
Lg
Andress

**Comment by BigUser8888** [comment]
I had something similar, and found it to be when clicking on the destination description or unload point description in the HUD with the mouse.

Clicking one of these hid the description words, and caused the symptoms described above.  Clicking again in the space where the (now hidden) description would be unhid the description and brought back f1 menu and full control.

**Comment by Stephan-S** [comment]
Hey,

sind die Probleme inzwischen gelöst oder besteht hier noch Handlungsbedarf?

**Comment by andreasthu** [comment]
@Stephan-S 
Von meiner Seite schon, danke für deine Hilfe.
Echt toll.
K.a. wieviele dutzend mal ich da Spiel per alt-tab  beendet und neugestartet hatte.
Naja, der fehler lag ganz klar auf meiner Seite. 
Nun klappt es wunderbar.
Wie es bei @BigUser8888 aussieht weiß ich nicht.
Lg
Andreas

**Comment by Stephan-S** [comment]
Ich seh den Fehler auch bei mir.
Offensichtlich sind die Funktionen nicht immer intuitiv zu bedienen.
Eine bessere Einführung bzw. Doku wäre an vielen Stellen sicher auch angebracht :-)

Ich mach dann erstmal zu hier.

Beste Grüße,
Stephan

**Comment by andreasthu** [comment]
Kein problem.
Bin ja erst ein pasr Tage bei diesem mod.
Und ich finde er ist relativ einfach und gut zu bedienen.
Den rest schaut man sich eh bei youtube ab.
Mein fehler war anfangs sicher auch das zu kleine hud. Hab ja ingame die giants huds auf 60% skaliert.
Aber mit deiner Beschreibung von 
https://github.com/Stephan-S/FS19_AutoDrive/issues/125
Hab ich die ui scale auf 75% gestellt
local uiScale = 0.75
Nun kann ich alles wunderbar einstellen und lesen, und verklick mich nicht dauernd.
Btw, seit der v 1.o.2.2, ist es 6x in der lua zu ändern, 
Lg
Andreas

**Comment by Stephan-S** [comment]
Ich habe eine GUI Skalierung zu den Einstellungen hinzugefügt, damit das in Zukunft nicht mehr nötig ist, das du/ihr diese Werte manuell anpasst.
Wird beim nächsten Release dabei sein, aber die lua ist schon geupdated, falls du dir das selber packen möchtest.

**Comment by andreasthu** [comment]
jup,
getestet und funktioniert.
danke @Stephan-S 

lg
andreas
