### ISSUE TITLE
Veränderungen in den neuen Updates

### ISSUE THREAD

**Issue by altbier1** [Stephan-S/FS19_AutoDrive#1310]
It would be nice if the changes would be told in some short sentences. If it is not able to do this on the fist side PLEASE make a link to the page where the chages are shown. It is f**king anoying to watch two or three videos to learn how to connect new courses to the existing corses.

Es wäre schön wenn die Veränderungen in einigen Sätzen erklärt würden. Da das auf der ersten Seite nicht möglich ist bitte einen Link zu Erklärung setzen wo die Veränderungen erkärt werden. Es ist einfach nur nerven bzw. ätzend wenn man "kurz" was ändern möchte und sich dazu dann mehrere Videos suchen muss um die Änderung in der entsprechenden Version durchführen zu können!!

**Comment by Iwan1803** [comment]
Also take a look here: https://github.com/Stephan-S/FS19_AutoDrive/releases
Enough? No? Join Discord and take a look at #announcements
