### ISSUE TITLE
Probleme mit Drescher Abfahrer [BUG]

### ISSUE THREAD

**Issue by Kalle639** [Stephan-S/FS19_AutoDrive#1311]
AutoDrive Version: 1.1.0.4
Release or selbsterstelltes zip: Release
Karte (falls relevant): Alle
Fahrzeug(art) (falls relevant):
Multiplayer or Singleplayer: MP auf Dedi Server

Ich habe Probleme mit dem Drescher Abfahrer er kommt nicht von selbst ist auf 80% eingestellt er muss immer manuell Gerufen werden. Wenn er dann kommt Dreht er nur Kreise hinter dem Drescher. Wenn er dann voll ist Faehrt er nicht von allein zum Abladen. Habe es im Singleplayer Getestet läuft alles wie es soll. Was kann das sein?
Bitte um Hilfe!
Danke!

**Comment by Kalle639** [comment]
Habe jetzt die Version 1.1.0.5 RC1 jetzt fährt er neben den Drescher her obwohl er fertig ist mit Abtanken und es steht Fange Drescher linke Seite. Kannst du nicht einfach einen weiteren Modus zum Häckseln hinzufügen um Dreschen und Häckseln zu trennen.

**Comment by Iwan1803** [comment]
Bitte auf aktuellste RC aktualisieren und erneut probieren.
Sollte das Problem noch bestehen, dann bitte ein neues Issue aufmachen.
