### ISSUE TITLE
Autodrive Einstellung „Abstand zum Rohr“

### ISSUE THREAD

**Issue by BastiHRO** [Stephan-S/FS19_AutoDrive#1313]
Hallo.

Ich spiele seid neuestem LS19 und habe auch schon in der normalen MAP NF Marsch autodrive genutzt. Heute habe ich mir die 4fach MAP geladen und auch dein Streckennetz mit eingefügt. Leider haut mir AD in den Einstellung immer wieder bei „Abstand zum Rohr“ eine „- 4,75 m“ rein. Natürlich bestätigenden Mine Änderungen immer ordentlich. Trotzdem, auch nach Neustart des Spiels, stellt er mir immer wieder den Wert ein. Woran liegt das und wie schaffe ich das Problem aus der Welt.

Danke fürmdie Hilfe...
Basti

**Comment by Stephan-S** [comment]
Hast du die .zip Datei des Mods umbenannt?
Dann findet er die Einstellungen nicht mehr in der vehicles.xml

**Comment by FunFarmer1** [comment]
Hallo,
Also ich habe das gleiche Problem und ich habe den Namen nicht geändert.

Gruß

**Comment by BastiHRO** [comment]
Ich habe nur die .config Datei angeglichen.

**Comment by Stephan-S** [comment]
Dann bräuchte ich mal die .lof Datei, ob es irgendwelche Probleme beim Speichern/Laden gab.

**Comment by BastiHRO** [comment]
Wie sende ich dir die am besten?

**Comment by BastiHRO** [comment]
Ach ja 😬 wo finde ich die Datei?

**Comment by Iwan1803** [comment]
Dokumente\My Games\FarmingSimulator2019

**Comment by BastiHRO** [comment]
Danke.....
