### ISSUE TITLE
[BUG] unloader shuts off

### ISSUE THREAD

**Issue by kwguk** [Stephan-S/FS19_AutoDrive#1314]
**AutoDrive Version:** 1.1.0.5RC1
**Release or Custom Zip:** Release  
**Map (If applicable):** EIERSHOLT
**Vehicle / Type (If applicable):**   Vanilla tractor and trailer
**Multiplayer or Singleplayer:** Singleplayer  

**Describe the bug**  
Great mod. I dont know if its a bug but im using AD on unload combine and whenit leaves field and drives to the unload point the tractor stops and shuts down. If i press continue the tracotor restarts then tips then carries on its way

**If applicable - Im running sugar bet from field 21 to Garden Center sell

**Screenshots**

**Comment by Iwan1803** [comment]
A screenshot with the AD lines maybe could help, also the log file.

**Comment by Morkhan** [comment]
i had the same problem i moved the unload marker light forward and it worked

**Comment by Iwan1803** [comment]
That's correct.
