### ISSUE TITLE
[BUG] button Route Manager doesn't work

### ISSUE THREAD

**Issue by BastiHRO** [Stephan-S/FS19_AutoDrive#1315]
AutoDrive Version: 1.1.0.5-RC1
Release or selbsterstelltes zip: Release
Karte (falls relevant): Alle
Fahrzeug(art) (falls relevant):

**Beschreibe den Bug**
Nach einfahren der neuen Strecke wollte ich die Strecke wie gewohnt speichern. Leider öffnet sich beim Klick auf das Speichersymbol der Routenmanager nicht wie gewohnt. Ist das so gewollt, bzw. ist die Strecke jetzt gespeichert?

Basti

**Comment by Iwan1803** [comment]
Problem ist bekannt, ein Fix in Arbeit.

**Comment by BastiHRO** [comment]
Vielen Dank. angesichts der Tatsache das AD automatisch die Änderungen speichert, vergisst man ja gern mal, finde ich es gar nicht schlecht. eben nur das sich der Route Manager halt nicht öffnet.
