### ISSUE TITLE
[BUG] Kartoffel Abfahrer parken in der Frucht / Potato unloader parks in crop

### ISSUE THREAD

**Issue by Gariot** [Stephan-S/FS19_AutoDrive#1317]
AutoDrive Version: 1.1.0.4
Release or selbsterstelltes zip: Release
Karte (falls relevant): Alle
Fahrzeug(art) (falls relevant):

**Beschreibe den Bug**
Die Abfahrer fuer Kartoffeln parken einfach mitten im Feld und in der Frucht. Die entsprechenden Optionen habe ich natuerlich eingestellt. Bei anderen Fruechten (Zuckerruebern hab ich nicht getestet) funktioniert alles und der Abfahrer parkt nicht in der Frucht.

**Falls anwendbar - Schritte mit denen ich den Bug nachstellen kann**

**Screenshots**
![20200408185934_1](https://user-images.githubusercontent.com/18175983/78812454-bc23b480-79cb-11ea-8486-f41d56e5b059.jpg)

**Comment by TobiHH78** [comment]
Bei Zuckerrüben tritt das Problem ebenfalls auf.
Beim Dreschen von Getreide passiert es nicht, es scheint also irgendwie mit den Erdfrüchten zu tun zu haben.

https://github.com/Stephan-S/FS19_AutoDrive/issues/1306#issue-594565648

**Comment by Iwan1803** [comment]
Bitte auf aktuellste RC aktualisieren und erneut probieren.
Sollte das Problem noch bestehen, dann bitte ein neues Issue aufmachen.
