### ISSUE TITLE
Releases veröffentlichen

### ISSUE THREAD

**Issue by sschlauss** [Stephan-S/FS19_AutoDrive#132]
Hallo Stephan,

zunächst einmal danke für deine großartige Arbeit! Es ist sehr erfreulich, dass du dich CP öffnest und ihr neue Wege der Zusammenarbeit ausprobiert.

Eine Bitte hätte ich, wäre es möglich, dass du deine Releases auch als solche in Github kennzeichnest? Hat den charmanten Nebeneffekt, dass man sich über neue Releases informieren lassen kann (vgl. [https://github.com/Courseplay/courseplay/releases](https://github.com/Courseplay/courseplay/releases)) und nicht täglich vor der abendlichen LS Session ins repository schauen muss ob es Neuigkeiten gibt.
Die Klickanleitung gibt es hier ;) [https://help.github.com/en/articles/creating-releases](https://help.github.com/en/articles/creating-releases)

Herzlichen Dank und besten Gruß

**Comment by Experience95** [comment]
@sschlauss Als Workaround empfehle ich hierfür die GitHub Desktop App. Dort kannst du auf einen Blick sehen ob es Änderungen gibt oder nicht. Alle 2-3 Tage Mal reingucken und du hast immer die aktuellste Version der ganzen GitHub Mods (Auto-Drive, Coursplay, GPS, etc.)

LG Experience95

**Comment by stueja** [comment]
Das hieße, ich muß mir eine Software installieren und starten, um eine Software herunterzuladen und zu installieren? Das ist vielleicht nicht für jeden der geeignete Weg. Ich persönlich würde mich @sschlauss' Wunsch nach gezippten Releases anschließen.

**Comment by Experience95** [comment]
@stueja Du müsstest dir eine Software runterladen und installieren (geschlagene 80mb) um die aktuellste Version eines Mods zu haben.
Diese 2 Minuten Aufwand sind ja wohl nichts im Vergleich zu den Stundenlangen arbeiten die die Modder für unseren Spielspaß opfern.
Wenn dir dieser Aufwand schon zu groß ist, sind die experimentellen mods aus dem GitHub (die ja auch immer Fehler beinhalten können) vielleicht nicht das richtige für dich und du solltest dich auf die offiziellen releases aus dem ModHub beschränken.

**Comment by sschlauss** [comment]
@Experience95 zunächst mal danke für deinen gut gemeinten Hinweis. Ich bin schon seit einigen Jahren auf Github unterwegs und mir ist auch die Desktop App bekannt. Diese ist aber eher für aktive Coder gedacht (push-pull, etc.), habe sie zwar selbst nie verwendet, hat aber ihre Daseinsberechtigung. Github bietet die Release-Funktion nicht ohne Grund und sie wird auch meistens benutzt. Mich würde es freuen, wenn Stephan sich das mal anschaut und evtl. sogar umsetzt.

**Comment by Stephan-S** [comment]
Hey,

vielen Dank für deine Anmerkung @sschlauss 
Das werde ich für den nächsten Release mit einbeziehen. Ist ja wirklich keine Arbeit :-)

Viele Grüße,
Stephan

**Comment by stueja** [comment]
@Experience95, all das, was Du über meine Motivation mutmaßt, gepaart mit einem hinkenden Vergleich zu Stephans guter Arbeit trägt nicht wirklich zur Sache bei. Insofern entschuldige bitte, wenn ich Dich in meinem letzten Kommentar verletzt haben sollte.
