### ISSUE TITLE
[BUG] Reactivation of AD results in strange route detection

### ISSUE THREAD

**Issue by Opa-Andre** [Stephan-S/FS19_AutoDrive#1321]
AutoDrive Version: 1.1.0.5 - RC1
Release or selbsterstelltes zip: Release
Karte (falls relevant): Alle
Fahrzeug(art) (falls relevant):

In AD 1.0.0.4 gab es das Problem, das ein Abholer Kurs (gestartet durch CoursePlay) nach Unterbrechung dazu führte, dass AD bei manueller Unterbrechung durch den User (Deaktivierung / Aktivierung) beim Zurückkehren an den Feldzielpunkt nicht mehr das Ende der Fahrt an CP zurück signalisierte, sodass CP nicht die Feldarbeit fortsetzte. Dies funktioniert jetzt in 1.1.0.5-RC1, führt aber zu einem Logik Problem zur Fortsetzung des Kurses. Hier der Unterschied:

Verhalten in 1.1.0.4:
Wenn man während der CP Fahrt (z. Bsp. Befüllung der Sämaschine) den Kurs unterbrach, das Fahrzeug manuell bewegte (um z. Bsp. eine Kollision mit KI Verkehr zu beheben) und dann AD wieder gestartet hat, dann fuhr AD sofort weiter - je nachdem, ob die Sämaschine bereits wieder gefüllt wurde oder nicht, zum passenden Füllsilo / Trigger, oder auch zum Feldzielpunkt. Die Arbeit wurde also "sofort" fortgesetzt.

Verhalten in 1.1.0.5: 
Schaltet man hier AD aus und wieder ein, wird ebenfalls der korrekte Zielpunkt (grün) aktiviert. Allerdings fährt AD nicht los, sondern meldet "Berechne Pfad". Nach wenigen Sekunden wird der Motor abgeschaltet. Nach ~1 Minute schaltet AD das Ziel (grüne Zielschrift) ab und meldet "Verlasse Feld" - obwohl er schon weit vom Feld entfernt ist. Nun fährt das Gespann, selbst wenn es  bereits auf einer Straße ist, einmal eine vollständige Kreisfahrt´(360°) Anschließend aktiviert AD den Auffüll-Zielpunkt, selbst wenn die manuelle Unterbrechung durch den Anwender erst erfolgte, nachdem das Gespann wieder aufgefüllt wurde und es sich bereits zurück auf dem Weg zum Feldzielpunkt befand. Danach erfolgt die weitere Kursabarbeitung ohne Probleme und AD übergibt am Ende auch korrekt die Steuerung wieder an CP.

D.h. AD funktioniert eigentlich so weit (nimmt also die Arbeit nach manueller De- / Reaktivierung durch den User wieder auf), springt aber bei der Reaktivierung in eine länger andauernde Pfad-Berechnungsroutine und positioniert sich neu, anstelle vom am nächstliegenden Streckenpunkt im AD Kursnetzwerk direkt weiterzufahren.

**Comment by Iwan1803** [comment]
Das Problem ist bekannt und wird im nächsten RC gefixt sein.
