### ISSUE TITLE
Folder and Saving issues with Autodrive[BUG]

### ISSUE THREAD

**Issue by japkleine** [Stephan-S/FS19_AutoDrive#1323]
**AutoDrive Version:** 1.1.0.4   
**Release or Custom Zip:** Release  
**Map (If applicable):** All  
**Vehicle / Type (If applicable):**   
**Multiplayer or Singleplayer:** Singleplayer  

**Describe the bug**  
I have some problems with creating folders to organize my different points on the map. Everytime I load the saved Autodrive Courses I don't get the typical Standard folder with the search icon and the plus icon to create another folder. Instead I get a folder with the name of an already existing folder. Also, I only can save the routes with autodrive when I have started a completely new game. As soon as I have saved a game and restarted it, I still can create courses but I can't save them any longer in the Routes Manager. I would appreciate some help in this. I am using the Dondiego Map ".1.1. right now. I am sending a screenshot of my autodrive HUD with the folders I am using. I hope you can help me. I eagerly await your answer.

![Screenshot (1)](https://user-images.githubusercontent.com/63405720/78896846-81745780-7a71-11ea-9574-2c51edddf0e4.png)

**If applicable - Steps to reproduce the behavior**  

**Screenshots**

**Comment by Opa-Andre** [comment]
Please attach your logfile to your report. Otherwise it's just guessing what might be wrong.

**Comment by japkleine** [comment]
Can you explain to me what the logfile is? I am sorry, I am new to this. Thank you.

**Comment by japkleine** [comment]
Here is the logfile. I figured it out. I am sorry for the inconvenience. 
[log.txt](https://github.com/Stephan-S/FS19_AutoDrive/files/4457720/log.txt)

**Comment by Opa-Andre** [comment]
If you look through your log.txt you'll find several lines starting with "Error: " ... 
You should remove all of those mod-files which are mentioned in those error lines.
Also you should remove all other maps from the folder besides the one you want to play.

Then please try again... if AD is still behaving wrongly, then it might be that your AD routes file in your savegame might be broken as well. 

Unfortunately more cannot be found in your log.txt because it looks as if you only started FS19 and ended it after being in the welcome screen without loading a savegame. To find out more details you'll need to start your savegame as well...

**Comment by japkleine** [comment]
Thank you. I tried to remove all the mods that stated an error, but the problem still exists. I have the logfile with the savegame now. Maybe that can help? Thank you for your help.
[log.txt](https://github.com/Stephan-S/FS19_AutoDrive/files/4458659/log.txt)

**Comment by Opa-Andre** [comment]
You're still having mods producing errors according to your log. Please do a test and remove all mods which are not really needed for a test. For example just let the map mod, AD & CP in your modfolder. Then try to reproduce your problem to see if it generally works or if it even might be a problem with the specific map.

Also the log.txt file is still not a complete one. Delete it, start the game, start the savegame, try to reproduce the problem, save the game, exit the game and then upload the log.txt file. Currently it looks like if you were copying the log file while the game was still running...

**Comment by japkleine** [comment]
Thank you for your answer and your help. I tried everything you suggested and have now come to the conclusion that unfortunately my AD routes file is broken. So I guess I have to restart everything. But thank you again.
