### ISSUE TITLE
Problems with let Tractors drive [BUG]

### ISSUE THREAD

**Issue by MuffinHeiler240** [Stephan-S/FS19_AutoDrive#1325]
AutoDrive Version: 1.1.x.x
Release or selbsterstelltes zip: Release
Karte (falls relevant): Geiselsberg V1.1
Fahrzeug(art) (falls relevant): Alle(Mod/DLC/Standart)

Ich habe mir fertige Kurse heruntergeladen.. Allerdings können Die Fahrzeuge nicht zu irgendeinem Punkt finden! Ich habe keine Ahnung ob es etwas mit den Kursen oder mit AD zu tun hat... 

Hier der Link zu den Kursen und der Map:
https://www.farming-simulator.com/mod.php?lang=de&country=at&mod_id=135669
https://www.modhoster.de/mods/autodrive-kurse-fur-geiselsberg2019

**Comment by Opa-Andre** [comment]
@MuffinHeiler240 - wenn Du den AD vom Giants Modhub geladen hast, wundert mich nicht, dass die Kurse nicht funktionieren. Lade Dir von hier einfach die aktuelle Release Version herunter. Die vom ModHub ist total veraltet.

**Comment by MuffinHeiler240** [comment]
@Opa-Andre Es scheint mit der Länge der Lila / Blauen streken zu liegen ! Die Map ist ja sehr eng ... Hab grade selber einen eingefahren und es will einfach nicht

**Comment by MuffinHeiler240** [comment]
@Opa-Andre Hab den Bug selbst gefixed bekommen neustarten und Kurse Neuladen hat geholfen ... Trotzdem Danke und macht genau so weiter !
