### ISSUE TITLE
[BUG] Sometimes AD can't reach a field

### ISSUE THREAD

**Issue by rogeriodec** [Stephan-S/FS19_AutoDrive#1326]
**AutoDrive Version:** 1.1.0.2   
**Map (If applicable):** Felsbrunn
**Multiplayer or Singleplayer:** Singleplayer  

**Describe the bug**  
Although I think the routes are ok, sometimes, AD says that it can't reach some field. 
This example shows a route to field 9:
![image](https://user-images.githubusercontent.com/11199752/78928107-6c4df780-7a76-11ea-8e04-7e1c4bf44f3d.png)

There is a warning about the unreachable field.

But if the tractor moves a little further, the field is now reachable:
![image](https://user-images.githubusercontent.com/11199752/78929152-3e69b280-7a78-11ea-8639-2e0a4d54e9ea.png)

Here's my XML:
[AutoDrive_Felsbrunn_config.zip](https://github.com/Stephan-S/FS19_AutoDrive/files/4458006/AutoDrive_Felsbrunn_config.zip)

What's wrong?

**Comment by Stephan-S** [comment]
It's most likely due to that weird 'Field 10' point you have there.
When you start AD over there, he might want to start at that point, but this one is not really driveable in both directions due to your high angles at this connection in the opposite lane.

**Comment by rogeriodec** [comment]
You are right.
Softening the angles, the field was reachable.
Thanks!
