### ISSUE TITLE
Double chamber seeder refill issue

### ISSUE THREAD

**Issue by RedMonster-HUN** [Stephan-S/FS19_AutoDrive#1328]
**AutoDrive Version:** 1.1.0.4
**Release or Custom Zip:** Release  
**Map (If applicable):** Fenton Forest 4x map (1.50 version)
**Vehicle / Type (If applicable):**   
**Multiplayer or Singleplayer:** Singleplayer  

**Describe the bug**  
When a double chanber seeder (seed and fertilizer) gets empty, the tractor goes to the marked refill point (multisilo at farm). After seed gets refilled the worker goes further to refill fertilizer, but after a little amount goes into the seeder, refill process stops and engine switches off as well. And the worker stucks there.

Screenshot/video and logfile later.

**If applicable - Steps to reproduce the behavior**  

**Screenshots**

**Comment by RedMonster-HUN** [comment]
https://youtu.be/IbrY1EPKI70

[log.txt](https://github.com/Stephan-S/FS19_AutoDrive/files/4462044/log.txt)

**Comment by Iwan1803** [comment]
Same problem like here: https://github.com/Stephan-S/FS19_AutoDrive/issues/1421

**Comment by Iwan1803** [comment]
Please download 1.1.05.-RC4, try again and then post a feedback.
Bitte lade 1.1.05.-RC4 herunter, versuch es erneut und poste dann ein Feedback.

Changelog: https://github.com/Stephan-S/FS19_AutoDrive/wiki/Release-Notes

**Comment by RedMonster-HUN** [comment]
Can you pls send a link for RC4 download? I didn't find it. Thx

**Comment by Iwan1803** [comment]
Look at the bottom of the AD github startpage 😉
