### ISSUE TITLE
Upload not work...

### ISSUE THREAD

**Issue by Anonymous-any** [Stephan-S/FS19_AutoDrive#133]
Hi @Stephan-S  I know or imagine you have lots to do but I would help your AD work very well, so what I report I tried many many times is
To client of course:
```
2019-05-22 17:14 User is no admin and is not allowed to upload course <- then login ok
2019-05-22 17:15 User is admin and allowed to upload course
2019-05-22 17:17 User is admin and allowed to upload course
```
I have access to dedicated FTP server that why I see nothing upload go nowhere too.
Br

**Comment by Stephan-S** [comment]
If you upload a course file, it will replace the current course in the game session. After you save the game again, it will save this file to the standard savegame folder. You will not see an additional course file if that is what you are expecting.
But I haven't tried the feature lately and I currently have no AD server running to test it on.
So are you sure the course is not uploaded correctly?

**Comment by Anonymous-any** [comment]
Yes just been tried as your explain, my step to be sure:
1) Added destinations and new paths in solo then saved done.
2) Joined the server and admin login then edit mode to AD then uploading then save the server (I see too, this not enabling the option for recalculating nowhere in these steps) and then that no change the session file server it the same size as it do nothing... sorry.
3) Another thing I tried too from the client savegame0 path it was a disaster, recalculating option has been appear but after saved the server the AD file disappeared from session game :/
