### ISSUE TITLE
[FEATURE REQUEST] BGA mode

### ISSUE THREAD

**Issue by Napoleon231187** [Stephan-S/FS19_AutoDrive#1330]
**Is your feature request related to a problem? Please describe.**
Hello in one of the provisions version was the silo function available but a few version ago this function has vanished. Any chance to get it back.

With the Version I have at the moment is a filling of the silage silo or an automatic emptying with a bulldozer not possibly

**Comment by Iwan1803** [comment]
The BGA mode was disabled as it has caused many problems.
The mode will come back in a future release, but in an improved form.
It is not yet clear when that will be.

**Comment by Napoleon231187** [comment]
Ah Ok I was assuming something like that has happened:-).well I will that sit and wait for it :-) thx for the reply

**Comment by Axel32019** [comment]
The mode is enabled again since 1.1.1.2
