### ISSUE TITLE
[FEATURE REQUEST] 2nd park button for attachments

### ISSUE THREAD

**Issue by eric4072** [Stephan-S/FS19_AutoDrive#1331]
**Describe the solution you'd like**
Hi!
Ich hätte da noch eine Idee für die Zukunft. Sage gleich nochmal dazu: Ich bin weder ein Scripter noch Modder, habe absolut keine Ahnung davon. Bin aber fleißiger Nutzer von AD... Nun zu meiner Idee:

ist es möglich einen 2. Parkbutton einzufügen, der sich nach dem angehängten Gerät richtet? Die neue Funktion "Rückwärts" öffnet uns ja viele Möglichkeiten die Parkpositionen zu nutzen. Sinnvoll wäre es jetzt natürlich, wenn ich z.B. dem Grubber eine Parkposition ergeben kann (und nicht dem Traktor). Ev. dass man den P-Button entweder auf das Zugfahrzeug oder dem gezogenen Gerät umschalten kann...

Kann euch/dich wirklich nur loben... AD wird immer besser und ein LS ohne AD ist mittlerweile undenkbar... TOP

Danke
Eric

**Comment by Michael170978** [comment]
Soweit ich weiß wurde schon mal der Vorschlag vorgeschlagen. Ich glaube damals lag es an der Umsetzung. Die Idee ist gut aber wie willst du den das umsetzten?  Man könnte auf den gewünschten Anhänger gehen und mit der rechten Maustaste die Parkposition bestimmen. Man müsste halt nur aufpassen wen man zum Parken hinschickt. Den Schlepper oder den Anhänger. Eine kleine Unaufmerksamkeit und man hat anstatt den Anhänger den Schlepper zum Parken hingeschickt. Und dann steht der Schlepper samt mit dem Anhänger da.

**Comment by haamic** [comment]
Den Vorschlag hatte ich damals schon gemacht, auch für angehängte Geräte eine Parkplatz zuzuweisen. Egal ob jetzt rückwärts fahren ermöglicht wurde oder nicht. Es ist einfach logisch, das man erst das angehängte Gerät parkt und dann den Schlepper. Man hat ja schließlich nicht für jedes Gerät ein eigenes "Zugpferd". Aber nicht nur das Gerät parken , auch die Möglichkeit des ankuppelns eines Gerätes wäre Vielleicht auch machbar. Vielleicht  ist das Feature ja zukünftig auch möglich. Rückwärts fahren war ja auch nie angedacht. Und nun es es möglich.
Lassen wir uns überraschen. 
Ein weiteres Feature wäre, eine Art Routen-/Arbeitsplanung zu realisieren. Man gibt eine Reihenfolge von Zielen an und was dort gemacht werden soll (Wahl gespeicherter CP Kurse)
zb 1. fahre zum Pflug- ankoppeln
2. zu Feld x fahren und Courseplaykurs x starten. 
Danach müsste courseplay wieder an AD übergeben um evtl weitere Aufgaben zu beginnen.
3. fahre zu Feld y - courseplaykurs x
4. parke pflug -abkoppeln
5. fahre zu düngerstreuer -ankuppeln
6. fahre zu Feld x -- CP Kurs z starte
7. parke düngerstreuer-abkoppeln
8. parke Traktor
Usw....Möglichkeiten gibts sicherlich viele. 
Ist die Frage, da CP ja auf die AD Wegpunkte Zugriff hat, ob AD auf die CP Kurse Zugriff hätte. 
Mancher fände es gut, so eine Planung machen zu können , mancher nicht.
Ist hat Geschmacksache, aber evtl mal eine  Überlegung des AD-Teams wert.  

Vielen Dank für den tollen Mod, weiter so
Gruß Micha

**Comment by Iwan1803** [comment]
See https://github.com/Stephan-S/FS19_AutoDrive/issues/1225
