### ISSUE TITLE
Bremsbaustein zum bremsen

### ISSUE THREAD

**Issue by manuelgbel** [Stephan-S/FS19_AutoDrive#1332]
Meine Idee basiert auf dem Problem das die Fahrzeuge z.B. das Auto mit 120 km/h auf der Nordfrisischen Marsch 4fach über die Straße(Die Straße zwischen Feld 16,17 zu Feld 52,54) fährt wo ein Hügel ist und da die Straße gerade ist somit nicht runterbremst. Wenn er über den Hügel fährt fliegt das Auto quer über die Straße.

Als Lösungsansatz hätte ich die Idee, das man ein Bremsblock/-punkt(So wie bei den Zielen) einfügt, wo er auf die eingestellte Geschwindigkeit abbremst und somit nicht fliegt.

Ich habe keine Alternativen

![Problemstelle](https://user-images.githubusercontent.com/63503552/79045026-3d1bbf80-7c09-11ea-9e98-20a675833530.jpg)

**Comment by Axel32019** [comment]
Einfach ein paar Wegpunkte im Zickzack einbauen, das ist dann wie eine Kurve und er bremst ab...

**Comment by Michael170978** [comment]
@manuelgbel Ich finde die Idee genial. Ich würde noch anders machen. Z.B. Eine gewünschte Geschwindigkeit einstellen und dann mit dem gesetzten Punkt bestätigen. Somit wird dieses Fahrzeug ab dem Punkt nur mir der eingestellten Geschwindigkeit fahren. Es sei denn man setzt noch einen Punkt wo die Geschwindigkeit aufgehoben wird. Somit weißt dieses Fahrzeug bis wohin die Geschwindigkeitsbegrenzung gilt.  Dies Geschwindigkeitsbegrenzung würde aber dann für alle Fahrzeuge gelten. Ich meine mittlerweile können wir etliche einzelne Punkte auf den Karten setzen. Warum kann man diese Punkte nicht nach Bedarf mit der Geschwindigkeit verbinden?

**Comment by wallsingham** [comment]
@manuelgbel und @Michael170978 
das was @Axel32019 schreibt ist die Lösung für dieses Anliegen. 
Mit der Winkelgröße lässt sich die Geschwindikeit prima regeln. Das ist z.B. auch sehr gut praktikabel bei Kreuzungen.
Wenn man möchte dass die Fahrzeuge langsam durch Kurven fahren, sollte man die Kurve nicht einfahren sondern sie möglichst aus wenigen  Punkten "zusammenklicken" die zumindest an einer Stelle einen engeren Winkel bilden. Natürlich nicht kleiner al 91° sonnst fährt da gar nix mehr durch ;-)
manuelgbel
![grafik](https://user-images.githubusercontent.com/56741972/83358526-71dc0580-a374-11ea-81b1-a04e9516a1fe.png)

**Comment by Iwan1803** [comment]
Max. Geschwindigkeit kann pro Fahrzeug eingestellt werden.
Wenn man Bremsen möchte, kann man einen kleinen Zickzack-Kurs einbauen, um ein künstliches Bremsen zu erwirken.
Ansonsten würden Merkmale auf Wegpunkten das ganze unnötig kompliziert machen.
