### ISSUE TITLE
[FEATURE REQUEST]Einstellung für max. Siloabstand

### ISSUE THREAD

**Issue by TripleX1978** [Stephan-S/FS19_AutoDrive#1333]
Umstellung des max. Siloabstandes von allg. Einstellungen auf fahrzeugbezogene Einstellungen.
Ich habe gerade das "Problem", dass je nachdem welchen Abstand ich einstelle immer irgendein anderer Kurs Probleme bei den Triggern hat. Und evtl. auch umbenennen in Triggerabstand. Gilt ja nicht nur fürs Silo.

**Comment by Iwan1803** [comment]
Wie groß hast du den Abstand denn eingestellt und welche "Probleme" treten denn auf?

**Comment by TripleX1978** [comment]
Habe von 10m - 100m eingestellt...je nachdem was ich gerade brauche. Wenn man mehrere gleiche Produktionen hintereinander hat, kann es sein, dass man mal alle Trigger abfahren möchte oder halt nur einen bestimmten. Wenn das bei verschiedenen Produktionketten zur gleichen Zeit unterschiedlich sein soll hat man bei einer allg. Einstellung immer das Problem, dass ein Kurs nicht funktioniert.

**Comment by TripleX1978** [comment]
Hallo nochmal.
Habe jetzt nochmal ein bisschen mit dem Siloabstand experimentiert und noch ein Beispiel bei dem es Sinn macht den Siloabstand individuell für jedes Fahrzeug einstellbar zu machen.

Ich lasse Gras oder Häckselgut in einem Durchfahrsilo abladen. Damit das optimal funktioniert befindet sich der Abladepunkt hinter dem Silo und der Siloabstand ist auf 100m eingestellt.
Gleichzeitig lass ich vom Hofsilo mit mehreren Traktoren verschiedene Materialien zu den einzelnen Produktionen auf dem Hof bringen. Dadurch dass der Siloabstand auf 100m eingestellt ist, fangen die Traktoren bei jedem Trigger, den sie nur ansatzweise passieren, an zu buckeln bis der Triggerbereich verlassen wurde.
Bei den Traktoren müsste man den Siloabstand auf einen kleineren Wert einstellen um das zu vermeiden. Dann hätten aber die Fahrer im Durchfahrsilo wieder ein Problem und erkennen den Silotrigger nicht richtig.

Ich hoffe ich habe mich verständlich ausgedrückt.

**Comment by Iwan1803** [comment]
Ich habe meinen Abstand auf 50m eingestellt und keine derartigen Probleme bei einem 40m langen Durchfahrsilo, aber das liegt vermutlich daran, das ich meine Produktionen nicht alle auf einer Linie habe, sondern alle quasi fast einzeln anfahre.
Ein Screenshot der Problemstellen inkl. Wegnetz wäre vielleicht von Vorteil, um das Optimierungspotenzial ermitteln zu können.

**Comment by TripleX1978** [comment]
Hier mal ein Screenshot.

![image](https://user-images.githubusercontent.com/63108228/82759111-66746180-9deb-11ea-9403-fc4a1738f207.png)

Wenn ich den Siloabstand auf einen höheren Wert einstelle und ein Traktor auf der Route des weißen Fahrzeugs die Trigger passiert, dann fängt er an zu ruckeln weil er vermutlich die Abladetrigger erkennt obwohl er dort nicht abladen oder beladen soll.

**Comment by Iwan1803** [comment]
Das er vor erkannten Triggern langsamer wird, ist vollkommen normal.
Dies hat auch nichts mit dem max. Siloabstand zu tun, der die Strecke zwischen Trigger und Zielpunkt angibt.
