### ISSUE TITLE
[BUG] Reverse driving with implements

### ISSUE THREAD

**Issue by alex2ruote** [Stephan-S/FS19_AutoDrive#1334]
**AutoDrive Version:** 1.1.0.5
 
 Hi, I'm very excited about the reverse driving feature and I want to use it to park the vehicles, but I noticed that implements that are not trailed cause the tractors to stop where the reverse course begins. I tried with different implements but anything that doesn't have wheels has the same effect. 
Alex

**Comment by Iwan1803** [comment]
Thanks, problem is known and we are working on a solution.

**Comment by BloodyRain2k** [comment]
Ah, so this is why it was completely derping out when I wanted it to park with my sprayer.
I was already wondering.

I'd also like to voice my joy and thanks for adding this as it's great for neatly parking vehicles btw.

**Comment by Iwan1803** [comment]
_Please download 1.1.05.-RC4, try again and then post a feedback._
Bitte lade 1.1.05.-RC4 herunter, versuch es erneut und poste dann ein Feedback.

Changelog: https://github.com/Stephan-S/FS19_AutoDrive/wiki/Release-Notes

**Comment by Iwan1803** [comment]
https://github.com/Stephan-S/FS19_AutoDrive/issues/1479
