### ISSUE TITLE
[BUG] Route recording with editor deactivated / Streckenaufzeichnung bei deaktiviertem Editor

### ISSUE THREAD

**Issue by JulesPapillon** [Stephan-S/FS19_AutoDrive#1336]
AutoDrive Version: 1.1.0.5-RC2
Release or selbsterstelltes zip: Github a505ca4

**Beschreibe den Bug**
Vergisst man, die Streckenaufzeichnung zu deaktivieren, deaktiviert aber den Editor, werden weiterhin Wegpunkte generiert und gespeichert. Dies ist für den Nutzer aber nicht mehr ersichtlich.

**Comment by Axel32019** [comment]
Sollte mit 75f2070 gelöst sein.

**Comment by Iwan1803** [comment]
_Please download 1.1.05.-RC4, try again and then post a feedback._
Bitte lade 1.1.05.-RC4 herunter, versuch es erneut und poste dann ein Feedback.

Changelog: https://github.com/Stephan-S/FS19_AutoDrive/wiki/Release-Notes
