### ISSUE TITLE
[BUG]  When a vehicle approaches a corner on route it will just stop

### ISSUE THREAD

**Issue by kwguk** [Stephan-S/FS19_AutoDrive#1340]
**AutoDrive Version:** 1.1.0.5 RC
**Release or Custom Zip:** Release  
**Map (If applicable):** Eiersholt
**Vehicle / Type (If applicable):**  All 
**Multiplayer or Singleplayer:** Singleplayer  

**Describe the bug**  
I m playing this map as it came with extensive AD routes included. It doesnt happen all the time say 80% of the time when a vehicle approaches a corner on route it will just stop. Pressing continue has no effect. The only way to get it running along the route again is to manually start the vehicle and move it slight;y before rengaging AD and off it goes again. It happens no matter what mode im in or what kind of vehicle be it a mod or not. Its damn annoying!

**If applicable - Steps to reproduce the behavior**  

**Screenshots**

**Comment by schuelli238** [comment]
Same on my side on Map Rade. 
AD 1.1.0.5 RC 2
But just on 1 point right in front of the workshop trigger next to the diesel station. 
I‘ve to move the vehicle 2m forward manually. 
With 1.1.0.4 and earlyer the course worked fine.

**Comment by Iwan1803** [comment]
Sounds like a collision problem. Maybe you need to edit the network a bit or try it without collision detection.

**Comment by Iwan1803** [comment]
Please try 1.1.0.5-RC3. If the problem still exists, just open a new issue.
