### ISSUE TITLE
[FEATURE REQUEST] Second "Favorit" (similar to Parking button)

### ISSUE THREAD

**Issue by kroddn** [Stephan-S/FS19_AutoDrive#1341]
### Describe the solution you'd like
First of all, I want to say I love the Parking function. Espcecially with my multiplayer partners, the mess on the yard stopped (at least for vehicles :-) ).
**I would like to have a "Favorit" Button like Parking.** 
For many vehicles I have a target that I drive to very often (Fertilizer tractor to the Silo, Truck to the Shop, car to the gas station...). A tooltip should state the name of the Point (when you saved it).
Even cooler would be a button bar like many games have, from 1 to 9 with an option in the settings to add this button line to the HUD. That option would avoid a discussion, how to name the button :-)

Zunächst möchte ich sagen, dass ich die Parken-Funktion liebe. Gerade im Multiplayer für meine Partner geeignet, endlich ist die Unordnung auf dem Hof sortiert. Zumindest für Fahrzeuge
**Ich wünsche mir einen "Favorit" Button, so wie die Park-Funktion.**
Für vielen Fahrzeuge habe ich regelmäßig ein Ziel neben dem Parkplatz, das ich intensiv mit Ihnen verwende (Der Streuer-Traktor zum Silo, der LKW zum Shop, den PKW zur Tankstelle...). Ein Tooltip zum Button sollte den gespeicherten Namen des Ziels zum Zeitpunkt des Speicherns anzeigen.
Noch besser wäre eine Button-Leiste mit Favoriten von 1 bis 9, die man in den Settings als Zeile für die HUD einstellen kann. Das würde dann auch die Diskussion ersparen, wie man den Favoriten nennt.

**Describe alternatives you've considered**
One vehicles I "park" at the Shop ;-) - but I would like to send them back to the yard after filling.

Bei einem Fahrzeugen habe ich als Parkplatz den Shop eingestellt, es ärgert mich dann aber, dass er nicht auf dem Hof ist :-)

**Additional context**
Not needed I think

**Comment by Iwan1803** [comment]
Die Idee mit den Favoriten-Button an sich finde ich gut. 
Reparatur fällig? Zack, Favorit 1 gedrückt, wo der Werkstattpunkt hinterlegt ist.
Im normalen HUD müsste dann aber eine 4. Buttonleiste einbauen, im Wide-HUD sollte sie anstelle der Edit-Button angezeigt und im Editor-Modus ausgeblendet werden.
Man sollte die Anzahl aber auf 7 begrenzen, da aktuell ja auch 7 Button pro Reihe vorhanden sind.

**Comment by markussinner** [comment]
Auch gut. Mir würde ja schon ein weiterer Favorit reichen (pro Fahrzeug)

**Comment by Iwan1803** [comment]
Some more informations:
https://github.com/Stephan-S/FS19_AutoDrive/wiki/Buttons-with-short-description
https://github.com/Stephan-S/FS19_AutoDrive/wiki/Release-Notes

**Comment by Iwan1803** [comment]
Falschen Beitrag geschlossen....

**Comment by Iwan1803** [comment]
Um die Größe des HUD nicht zu strapazieren, könnte man einfach alle Favoriten in einen Ordner packen, welcher ganz oben einsortiert wird.
Somit sind keine Button notwendig.
