### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by PromGames** [Stephan-S/FS19_AutoDrive#1342]
**AutoDrive Version:** 1.1.0.5   
**Release or Custom Zip:** Release  
**Map (If applicable):** Hot 2020 Farm  
**Vehicle / Type (If applicable):**   
**Multiplayer or Singleplayer:** Singleplayer  

**Describe the bug**  
I got an error in /FS19_AutoDrive/scripts/Utils/UtilFuncs.lua:620: attempt to index field 'stateModule' (a nil value)
2020-04-13 17:03 Error: Running LUA method 'update'.
2020-04-13 17:03 dataS/scripts/AchievementManager.lua(257) : attempt to index local 'farm' (a nil value)
Trying to exit the game is when the error is produced

**If applicable - Steps to reproduce the behavior**  
Exit the game from Hot 2020 Map SP Career mode. When exit, the system crashes

That part of the code semms to be related to sprayer.

The error didn't appear from starting the savegame, only start to happend after I bought some material for herbicides, like hoses form manure system, and sprayers (vanilla game)

Also the autodrive course get corrupt and dissapears from savegame, I have to reload from backupsavegame

**Comment by Iwan1803** [comment]
Are you using 1.1.0.5-RC2?
The Manure system is also not supported at the moment.

**Comment by PromGames** [comment]
Yes is manure system who is doing the bug, but after your words, is not a bug, simply is not adapted yet. We use intensively autodrive in the map and we do not want to install it if autodrive is going to create big crashes.

**Comment by PromGames** [comment]
This problem is because the work around Stephan did when trying to manage sprayer problem he had in November, see issue looking for sprayer, where he used the trick used by deckerMV in his follow me. I suppose is related to the achievements records the vanilla game has to maintain and the correct state is not working properly.

**Comment by TyKonKet** [comment]
Hey @Stephan-S 
I took a look at that issues, but that seems pretty senseless, on this line (UtilFuncs.lua:620), stateModule is checked for nil...

**Comment by TyKonKet** [comment]
This issue have been fixed by @aletheist  with df587f7d74e1e025423c1b8f49ba48062273d704
