### ISSUE TITLE
[BUG] Routenplanung bei "einspurigen" Strecken / Route planing with two way routes

### ISSUE THREAD

**Issue by HGReaper** [Stephan-S/FS19_AutoDrive#1343]
AutoDrive Version: 1.1.7.1
Release or selbsterstelltes zip: Release

Wenn man längere "einspurige" Strecken erstellt (blaue Linie), wartet ein Fahrer an seinem Ende der Strecke, obwohl unterwegs Ausweichmöglichkeiten / alternative Routen vorhanden sind.

**Comment by Iwan1803** [comment]
Wenn ein Fahrer auf einer blauen Linie unterwegs ist, warten andere Fahrer darauf, das der erste von der blauen Linie runter ist. Dabei spielen Ausweichrouten keine Rolle.

PS: veraltete Version -> kein Support.

**Comment by HGReaper** [comment]
Ok, dann muss ich die Route an den Ausweichstellen also komplett splitten, quasi eine lange einspurige Strecke in mehrere kleine unterteilen. Danke für die Info!
