### ISSUE TITLE
[BUG] Combine Unloader - Drive to combine Pipe - infinite loop

### ISSUE THREAD

**Issue by rogeriodec** [Stephan-S/FS19_AutoDrive#1344]
**AutoDrive Version:** 1.1.0.2 
**Release or Custom Zip:** Release  
**Map (If applicable):** All  
**Vehicle / Type (If applicable):**   
**Multiplayer or Singleplayer:** Singleplayer  

See this video: https://youtu.be/zlFSnb6DGz0

Combine Unloader is extremely clever, however, I saw this bug. Due to the distance between the unloader and the combine (based on the sharp angle maneuver), the unload never reaches the combine.
In this situation, the unloader is in an infinite loop.

How to solve this?

**Comment by Iwan1803** [comment]
Outdated version -> no support.
Please try again with the latest version.

**Comment by rogeriodec** [comment]
Actually I'm using the latest version, 1.1.0.4, however, the AD HUD insists in showing 1.1.02...

**Comment by Iwan1803** [comment]
If the HUD shows 1.1.0.2, then you are using 1.1.0.2
Please update with the latest Release candidate from here or update ingame from modhub.

**Comment by Blacksnake51** [comment]
@rogeriodec Check the pipe distance in the driver settings. The value should be set to + 0.5m. The "problem" looks familiar to me.

Update from ingame modhub is a bad idea, the version is years old (1.0.9.x).

**Comment by Iwan1803** [comment]
@Blacksnake51 why is updating to 1.1.0.4 from the ingame modhub a bad idea? 😉

**Comment by rogeriodec** [comment]
> If the HUD shows 1.1.0.2, then you are using 1.1.0.2
> Please update with the latest Release candidate from here or update ingame from modhub.

Ok, I'm trying to download but the download link (https://host-my-bits.com/cdn/files/2/FS19_AutoDrive.zip) is offline.

![image](https://user-images.githubusercontent.com/11199752/79280272-5ed5aa80-7e86-11ea-8be7-489b1148e2e5.png)
![image](https://user-images.githubusercontent.com/11199752/79280356-8dec1c00-7e86-11ea-92ad-77aecc478c4d.png)


Is there another way?

**Comment by Iwan1803** [comment]
You can download it here:
https://github.com/Stephan-S/FS19_AutoDrive/releases
or you can use the ingame modhub.

**Comment by rogeriodec** [comment]
Thanks @Iwan1803.
@Blacksnake51, lowering the pipe distance in the driver settings looks like it solved the problem... thank you.
