### ISSUE TITLE
[BUG] HOT Dynamic grain silo drive through with collision detection not possible

### ISSUE THREAD

**Issue by Zimty86** [Stephan-S/FS19_AutoDrive#1345]
AutoDrive Version: 1.1.0.5 RC2
Release or selbsterstelltes zip: Release
Karte (falls relevant): Alle
Fahrzeug(art) (falls relevant):

**Beschreibe den Bug**
Ich Benutze vom HoT Team das Dynamische Getreidesilo, Autodrive Fahrt bei der Einfahrt und im Getreidesilo nicht.
Er bleibt einfach stehen.
Wenn ich die Kollisionserkennung ausschalte funktioniert es

**Comment by Iwan1803** [comment]
Dann wende dich bitte an HoT, das sie die Kollisionsmaske mal bitte prüfen.

**Comment by BloodyRain2k** [comment]
Ich habe allerdings ein aehnliches Problem mit dem GlobalCompany Market.
Bisher hat AD mit diesem super funktioniert, aber 1.1.0.5 hat irgendwas mit der Erkennung von Hitboxen geaendert, denn sowohl die Nodes verhalten sich jetzt ueber der Heuballen-Entladeecke merkwuerdig und gehen meistens auf Hoehe des Dachs, als auch AD selber was sich verhaelt als ob dort eine Wand waere.




Mit der letzten Version davor 1.1.0.3-4 ging alles noch ohne diese Probleme und fuer den Market gab es seit dem auch kein Update, dort hat sich also nichts geaendert.

Was sich bei AD geaendert hat, was mir zumindest aufgefallen ist, ist dass die Nodes weniger leicht durch die Strassen auf das Gelaende darunter flutschen. Vor 1.1.0.5-RC2 war das richtig nervig, jetzt geht es die meisste Zeit, aber dieses Problem ist halt nebenbei mit aufgetaucht.

**Comment by Zimty86** [comment]
Ja das ist mir auch aufgefallen die Nodes zu weit unten sind durch den Boden gehen eventuell liegt es daran, ich bin mir zwar nicht zu 100%ig sicher aber bin der Meinung das Getreidelager ging vorher.

Ich habe die Nodes auch auf unter den Fahrzeug geändert wenn ich es über Fahrzeug Stelle komme ich nicht an den unteren weil er in der Map versunken ist.

**Comment by BloodyRain2k** [comment]
Bin mir nicht ganz sicher, aber war AD vor 1.1.0.5 auch in der Lage den 16x Ballentransporter in der jetzt verwandeten Flaeche zu entladen? Weil das geht nicht (mehr?) : (

**Comment by Iwan1803** [comment]
Es ist kein AD-Problem, wenn Modder die Kollisionsmasken falsch setzen.
