### ISSUE TITLE
Lua Fehler 265 und 386

### ISSUE THREAD

**Issue by Berios** [Stephan-S/FS19_AutoDrive#1346]
AutoDrive Version: 1.1.0.4   
Release or Custom Zip: Release von GitHub  
Map (If applicable): Oberthal 1.2.2.0  / Oberthal 1.2.0.0
Vehicle / Type (If applicable) - in Betrieb / in Besitz zum Zeitpunkt des Bugs:
   
Axial Flow 9240 (Mod) - in Betrieb per CP
DX6.61 Warrior Special (Mod) - nicht in Betrieb 
7250 TTV Warrior Chip (Mod) - nicht in Betrieb
9340 TTV Chip (FSM Mod) - 3 Stück in Betrieb per CP
Arocs (Mod) - nicht in Betrieb
Rubicon 9000 by Stevie (Mod) - in Betrieb per CP
Pickup 2014 (Standart) - nicht in Betrieb
CR10.90 (Standart) - in Betrieb per CP
MAN 18.500 4x4 (Standart) - in Betrieb per AD 
Dazu kommen ein paar Anhänger - Kroeger Förderband, Joskin Dakkar und Fliegel AS286 (der Abschiebesattel von Fliegel)

Standart = Bereits im Grundspiel enthalten
Mod = gemoddete, spielexterne Modelle

Multiplayer or Singleplayer: Singleplayer  

Bugreport:
2020-04-14 11:30 D:/LS19/LS19 Modordner/FS19_AutoDrive/scripts/Hud/PullDownList.lua:265: attempt to index field 'ad' (a nil value)
2020-04-14 11:30 Error: Running LUA method 'mouseEvent'.
2020-04-14 11:30 D:/LS19/LS19 Modordner/FS19_AutoDrive/scripts/Hud.lua:386: attempt to index field 'ad' (a nil value)
2020-04-14 11:30 Error: Running LUA method 'mouseEvent'.

Autodrive wirft LUA Fehler, welche sich im Laufe der Zeit verschlimmern und am Ende zum Spielabsturz führen. Die Fehler tauchen im Laufe des Spieles auf und können von mir nicht reproduziert werden. Bei voller Auslastung meiner Abfahrer und Drescher (3 Drescher (CP), 3 Überladefahrer (CP), 3  Abfahrer (AD) und x andere Fahrzeuge (AD), welche als Zubringer für Gerät unterwegs waren), passierte gar nichts (gleiche Modelle wie oben angegeben). Das Spiel lief ohne Probleme und ohne haken. Aus dem Nichts tauchen dann diese Fehler auf - das Spiel beginnt zu haken. 
Teilweise beginnt auch CP nach meinem Gefühl "zu spinnen" - das Fahrverhalten und die Pfadfindung der Überladewagenfahrer scheint sich zu verändern (kann ich nicht belegen, ist nur ein Gefühl).
Ich hänge mal noch meine log.txt mit an - zu diesem Zeitpunkt treten die Fehler "zum ersten Mal" auf und sind nur mit einem Haken des Spiels verbunden. Fatal werden sie dann erst später.

[log.txt](https://github.com/Stephan-S/FS19_AutoDrive/files/4474588/log.txt)

Vielleicht könnt ihr mir ja einen Tip geben. :-)

Danke,

Berios

**Comment by Iwan1803** [comment]
Veraltete Version -> kein Support. 
Versuch es bitte mit der neuesten Version noch mal.

**Comment by Berios** [comment]
Hallo Iwan!
Was meinst Du mit "veraltete Version"?
Autodrive 1.1.0.4 ist doch der aktuelle Release, oder?
Und Farming Simulator 1.5.1 ist der aktuelle LS Patch.

Meiner Meinung nach ist alles bei mir aktuell. Übrigens tritt der selbe Fehler auch mit AD 1.1.0.5 auf. 
Gleiche Lua Fehler.

Berios

**Comment by Iwan1803** [comment]
Wir sind bereits bei 1.1.0.5-RC2 😉
Den Download findest du auf der Startseite weiter unten: "Latest Release Candidate"

**Comment by Berios** [comment]
Closed - siehe #1348
