### ISSUE TITLE
[FEATURE REQUEST]Neue Abfahrfunktion

### ISSUE THREAD

**Issue by 60erjonny** [Stephan-S/FS19_AutoDrive#1347]
Hallo sorry, ich versuche es mal auf diesem Wege. Es ist doch möglich mit AD mehrere Ziele die in einem Ordner sich befinden an fahren und abladen zu lassen. Könnte man nicht auch AD dazu bringen, mehrere Abholtrigger  ( z.B. Gülle ) die sich in einem Ordner befinden anfahren zu lassen und dann abholen zu lassen ? Wäre praktisch...absolut tolle, super Arbeit von euch...!!!

**Comment by Iwan1803** [comment]
Also zusätzlich zu mehrere Ziele auch mehrere Startorte, dann aber nur mit 1 Ziel oder auch mit mehreren?
Die Idee an sich finde ich gut. So könnte ich z.Bsp. Gülle von meinen Ställen entnehmen und an ein oder mehrere Ziele liefern lassen.

**Comment by 60erjonny** [comment]
Hallo @Iwan1803 
Vielen Dank für die Antwort.
Mein Hintergedanke war natürlich hier, von mehreren Startorten ( z.B. Milch,Gülle oder Mist...) zu einem Ziel.
Aber zu mehreren Zielen wäre natürlich hier auch denkbar, es muss eben "nur" umsetzbar sein...:-)
Nochmals gute Arbeit, was hier geleistet wird...!!!

**Comment by BloodyRain2k** [comment]
Wenn wir schon dabei sind: Silo Transfer waere fuer GC Market Spieler nicht uninteressant, so das man einfach ein (oder mehrere) Silos angibt und es wird halt nacheinander alles Transportiert was das Fahrzeug kann.

**Comment by Iwan1803** [comment]
Wurde in RC4 implementiert:
mehrere Ladestellen aus einem Ordner, mehrere Abladestellen aus einem Ordner und beides kombiniert.
