### ISSUE TITLE
[FEATURE REQUEST] - Written documentation

### ISSUE THREAD

**Issue by realskudd** [Stephan-S/FS19_AutoDrive#1349]
**Is your feature request related to a problem? Please describe.**
There seems to be a very distinct lack of written documentation for AutoDrive. Nearly everything is a video on YouTube with really hard to understand speech. 

**Describe the solution you'd like**
Some written documentation with screenshots, definitions, descriptions, terms, etc. would go a really long way, especially for people who have trouble with auditory processing and/or are unable to read captions on videos and keep up with what's happening in the video.

**Describe alternatives you've considered**
The only thing that I can think of is to analyze the code myself and try to decode it from there, but that's just not feasible. 

**Additional context**
I am coming from a strictly CoursePlay usage in the game.

**Comment by Iwan1803** [comment]
It's not the newest version, but should help:
https://github.com/Stephan-S/FS19_AutoDrive/wiki

**Comment by realskudd** [comment]
Hmm, that does help. I think it should be updated to match current features and function though.

**Comment by ZerwasMOD** [comment]
> Hmm, that does help. I think it should be updated to match current features and function though.

Go ahead and give your contribution to the docs :)

**Comment by Iwan1803** [comment]
Some more informations:
https://github.com/Stephan-S/FS19_AutoDrive/wiki/Buttons-with-short-description
https://github.com/Stephan-S/FS19_AutoDrive/wiki/Release-Notes
