### ISSUE TITLE
Kleine problem nach dem Abtanken

### ISSUE THREAD

**Issue by Mannie313** [Stephan-S/FS19_AutoDrive#135]
Hallo @Stephan-S 
Ich habe ein kleines problem mit dem Terra Dos T40.

![fsScreen_2019_05_22_21_04_42](https://user-images.githubusercontent.com/3021040/58201528-96b78a80-7cd5-11e9-85e4-25052fe964ae.png)

Der Abfahrer will gleich nach dem abtanken vor dem Terra zum Startpunkt Fahren. Nich so wie bei den Dreschern.

MFG Mannie313

**Comment by Stephan-S** [comment]
Hey @Mannie313 
kannst du die Situation noch kurz weiter beschreiben?
Ist der Terra Dos mit normalem Helfer unterwegs oder bereits mit CP?
Ist der Terra Dos nach dem der Anhänger voll ist sofort losgefahren?
Der AutoDrive Abfahrer sollte normalerweise einige Sekunden nach dem Abladen warten und erst dann losfahren, so dass selbst bei solch eine Pfadfindung möglichst keine Blockungen auftreten, da er den bereits vorgefahrenen Terra Dos dann rechtzeitig erkennen sollte und davor bremst.

Ein kurzes Feedback wäre super, damit ich das Problem besser eingrenzen kann und um zu wissen an welcher Stellschraube ich hier am Besten optimiere :-)

Beste Grüße,
Stephan

**Comment by Mannie313** [comment]
Hallo @Stephan-S . Ich hatte zwei Abfahrer. Der Terra nimmt 60000 Liter Kartoffeln auf und war mit CP unterwegs. hab aber bei dem Terra gesagt bleib stehen während entladen wird.der Hänger im bild nimmt 21000 liter auf und der nächste 39800 liter.  ich hatte auf dem bild schon 5 minuten gewartet aber da tat sich nix.

MFG Mannie313

**Comment by Stephan-S** [comment]
Alles klar, dann sieht es so aus als würde bei der Kommunikation zwischen CP und AD noch etwas nicht stimmen, da CP ja eigentlich den Terra Dos weiterfahren lassen könnte
