### ISSUE TITLE
[FEATURE REQUEST] Make ADHarvestManager.MAX_SEARCH_RANGE configurable in game

### ISSUE THREAD

**Issue by realskudd** [Stephan-S/FS19_AutoDrive#1351]
**Is your feature request related to a problem? Please describe.**
On large fields, the combine unload feature doesn't work well. For example, field 5 on the County Line map. If a target is set at the northeast corner and at the southeast corner, but the combine is dead in the middle of the field, the runner can't find the combine to unload.

**Describe the solution you'd like**
As the title suggests, `ADHarvestManager.MAX_SEARCH_RANGE` being configurable in the game/addon settings would be one solution.

**Describe alternatives you've considered**
The ability to designate an entire field as the search area would be another option. Scan the field for active combines, check fill level, if at or above the designated call level, flag as an available target and run.

**Additional context**
If there's another way to combine the Combi Unload feature of CoursePlay with the Combine Unload feature of AD, a description of how to accomplish that would be helpful. Otherwise, as I have stated in another feature request, I am (up until this point) pretty settled with CoursePlay, but am trying to see what the hype of AD is. So far, I like it, though I'm finding some things not exactly working as advertised. I may require some FM to R. :)

**Comment by Iwan1803** [comment]
In AD set the same target on the thresher or forage harvester as the unloader was set to. Then deactivate in the AD settings the search for an unloader.
If this was done, the max. search range will be ignored.

**Comment by schuelli238** [comment]
@Iwan1803 When i do that often "Vehicle XY can not find a path to Harvester YZ" on slightly "larger" fields. For exmaple field 1 on Gemeinde Rade map.

**Comment by Iwan1803** [comment]
The map is not really AD friendly and the pathfinding problems are not necessarily due to the field size.
What are the settings for the unloader?

**Comment by schuelli238** [comment]
![2020-04-15 (4)](https://user-images.githubusercontent.com/20584917/79338752-1ff83100-7f28-11ea-82f1-c5a02c2b6ec6.png)
![2020-04-15 (1)](https://user-images.githubusercontent.com/20584917/79338760-21295e00-7f28-11ea-9180-c0b6ad29da2a.png)
![2020-04-15 (2)](https://user-images.githubusercontent.com/20584917/79338766-22f32180-7f28-11ea-9d48-70e37121dc77.png)
1&2 unloader, 3 harvester

**Comment by realskudd** [comment]
Ah, an undocumented feature! 

I did this and it works. Thanks. I do think that this issue should be kept open though to consider improvements to either the mod itself or to the documentation.

**Comment by Iwan1803** [comment]
1 should be the settings for the harvester, 3 for the unloader 😉

**Comment by schuelli238** [comment]
Of course! GitHub changed the upload order ;-) Thanks

**Comment by Iwan1803** [comment]
Forgotten to close...
