### ISSUE TITLE
[FEATURE REQUEST] ctrl + alt click to 'dissolve' nodes

### ISSUE THREAD

**Issue by BloodyRain2k** [Stephan-S/FS19_AutoDrive#1353]
It would be really nice if the in-game editor would allow the removal of nodes without breaking up the connection, this is what I learned as 'dissolving' from Blender.

Let's say you have the nodes A -> B -> C and now 'dissolve' B, the result would be A -> -> -> C.
The path is preserved, it's just like A was directly connected to C and B never existed.
This would make cleaning up routes a lot easier.

Maybe even go as far and add the opposite feature too: select node A and then ctrl alt click somewhere it will insert a node there that goes from A to __new B__ to C.
In case A has more than one connection going out compare it's paths and choose the one that's closer?

**Comment by BloodyRain2k** [comment]
--> #1368

**Comment by Iwan1803** [comment]
Not working and because of the 2nd edit mode not needed.
