### ISSUE TITLE
[BUG]downer does not drive unloading-abfahrer fährt nicht abladen

### ISSUE THREAD

**Issue by Morkhan** [Stephan-S/FS19_AutoDrive#1357]
AutoDrive Version: 1.1.0.5
Release or selbsterstelltes zip: Release
Karte (falls relevant): Alle
Fahrzeug(art) (falls relevant):

**Beschreibe den Bug**
ich möchte einen drescher abtanken er ist zu 95% gefüllt abfahrer kommt tankt ihn ab drescher fährt weiter aber der abfahrer bleibt mit diesen 95% ladevolumen gefüllt stehen und fährt nicht abladen er wartet weiter auf den ruf des dreschers...der drescher ist weider mit etwa 95% ladung gefüllt ruft den mit 95% gefüllten abfahrer und der tankt die restlichen 5% ab und fährt ERST DANN abladen warum ist das so hab ich was falsch eingestellt wobei ich nichts verändert habe ausser das neue update draufzumachen

**Falls anwendbar - Schritte mit denen ich den Bug nachstellen kann**

**Screenshots**
Falls relevant, bitte Screenshots beifügen

**Comment by schuelli238** [comment]
warum geschlossen?
