### ISSUE TITLE
[BUG] Combine Unloader mode only unload when combine is full (with Course Play)

### ISSUE THREAD

**Issue by rogeriodec** [Stephan-S/FS19_AutoDrive#1358]
**AutoDrive Version:** 1.1.0.4   

**Describe the bug**  
I use Course Play for the combine. I have already tried several settings, but I have noticed that within Combine Unloader mode, it is only unloading when the combine is full (when it stops).
Doesn't AD unload while the combine is moving?

Here my current settings:
![image](https://user-images.githubusercontent.com/11199752/79490292-040d9180-7ff3-11ea-8a97-3fd15d19b1d3.png)

![image](https://user-images.githubusercontent.com/11199752/79490312-0c65cc80-7ff3-11ea-8b3b-65af9c5d3a59.png)

![image](https://user-images.githubusercontent.com/11199752/79490325-112a8080-7ff3-11ea-8ba5-4abea8d4f83d.png)

**Comment by Iwan1803** [comment]
Tresher settings must be set while sitting in the tresher.
What is set up in CP for the unloader?

**Comment by rogeriodec** [comment]
> Tresher settings must be set while sitting in the tresher.

What???

> What is set up in CP for the unloader?

Which of the above configurations are for all vehicles and which are for each vehicle individually?

**Comment by Iwan1803** [comment]
In the AD settings menu every setting has a symbol:
world symbol = valid for all vehicles
tractor = valid for the selected none-combine
combine = valid for the selected combine

**Comment by rogeriodec** [comment]
> In the AD settings menu every setting has a symbol:
> world symbol = valid for all vehicles
> tractor = valid for the selected none-combine
> combine = valid for the selected combine

Thanks!

> What is set up in CP for the unloader?

Why once in this case only the harvester is begin guided by CP?

**Comment by Iwan1803** [comment]
In CP you can set up, if the harvester should stop for unloading or bypass fuits.

**Comment by rogeriodec** [comment]
In CP, the harvester is configured:
stop for unloading  = disabled
![image](https://user-images.githubusercontent.com/11199752/79670665-1fb39c00-819b-11ea-9160-a25540549a2a.png)

bypass fruits (don't know which setting is):
![image](https://user-images.githubusercontent.com/11199752/79670718-6608fb00-819b-11ea-84c5-6eca1f29aecc.png)

**Comment by Iwan1803** [comment]
Let him stop for unloading (just a test) and update to the latest AD-RC.

**Comment by Iwan1803** [comment]
Please try 1.1.0.5-RC3. If the problem still exists, just open a new issue.
