### ISSUE TITLE
[BUG] Not detecting collision with objects

### ISSUE THREAD

**Issue by rogeriodec** [Stephan-S/FS19_AutoDrive#1359]
**AutoDrive Version:** 1.1.0.4   

**Describe the bug**  
As shown in the image below, in Combine Unloader mode, the unloader collided with a pole.
How can this be prevented?

![image](https://user-images.githubusercontent.com/11199752/79490120-c27ce680-7ff2-11ea-9f5f-a34009096a94.png)

**Comment by Iwan1803** [comment]
Could you please check if collision detection is activated?
Maybe you could also try the latest release candidate.

**Comment by BloodyRain2k** [comment]
If you want to prevent that you could just record a path around the field, after it left the field it will just follow that then.

**Comment by rogeriodec** [comment]
> Could you please check if collision detection is activated?

It was not, sorry. 

> Maybe you could also try the latest release candidate.

Where can I get it?

**Comment by Iwan1803** [comment]
Here on github, at the bottom of the start page are the download links.

**Comment by rogeriodec** [comment]
Thanks!
