### ISSUE TITLE
Automatisieren von Aufgaben

### ISSUE THREAD

**Issue by st1nger1980** [Stephan-S/FS19_AutoDrive#136]
Hallo,

ich fände es toll wenn man Fahrer Selbstständig arbeiten lassen könnte.

Das hat mich immer an CP gestört. Man kann zwar für alles Kurse erstellen. Aber man muss diese immer per Hand aktivieren, manchmal sogar mehrere hintereinander bis man das gewünschte Ergebnis hat.

Ich weiß nicht welche Möglichkeiten man mit LS19 hat. Aber wenn man Abhängigkeiten einbauen könnte wäre das ein riesen schritt.

Was ich damit meine:
Zum Beispiel Aufgaben die sich ständig wiederholen. Nehmen wir einen Fahrer der Wasser zum Schweinestall Transportiert und abkippt. Das könnte man Automatisieren indem man den Wasserstand im Schweinestall prüft und ab einen eingestellten Wert fährt der Fahrer los. Er Fährt seinen Kurs zum Wasser befüllen und anschließend zum Schweinestall zum abkippen. Danach fährt er wieder in seine Park Position und wartet erneut bis der Wasserstand gesunken ist.

Gibt noch viele andere Einsatzmöglichkeiten. Kommt eben drauf an welche werte man in LS19 abfragen kann. Ich würde das Feature sehr begrüßen falls möglich, und ich denke andere ebenfalls.

Eintönige und endlos wiederholende Aufgaben können so Automatisiert werden durch einen Bezahlten Fahrer. Als Nebeneffekt hätte man so auch mehr eigenen Verkehr auf dem Hof und den Straßen. Man kann sich so mehr auf die Wichtigen Aufgaben konzentrieren, und muss nicht permanent Kurse starten und beenden was mit der zeit auch den Spielfluss stört.

Lieben Gruß
st1nger

**Comment by stueja** [comment]
Ein Spiel, das sich quasi automatisch von selbst spielt? Das ist eine hervorragende Idee. Aber jetzt muß ich erstmal wieder zurück vor den Fernseher, Wing Commander weiter gucken.

Und im Ernst, ja, ich würde mir auch wünschen, daß ich z. B. einen Kurs "Wasser" starten kann, und der Fahrer fährt dann sämtliche Wasserstellen von selber ab. Aber nicht komplett ohne mein Zutun. Ich will erstens noch entscheiden können, wo und wann ich welches Gespann einsetze. Und wenn ich nur einen Traktor habe und ein Wasserfaß, und der Traktor ist gerade beim Mähen, dann ist eh kein Fahrzeug frei, was das Wasserfaß ziehen könnte.

**Comment by st1nger1980** [comment]
Hehe, ja verständlich.
Ich meinte auch nicht das Fahrer das selber tun. Ich vergleiche das mal mit dem Abtanken von Dreschern. Der Abfahrer wartet an einer Position darauf das der Drescher einen bestimmten füllstand hat und fährt dann seinen kurs ab. Den kurs hat man selber erstellt und auch selber alles eingestellt und aktiviert. Das selbe prinzip lässt sich auf alle anderen dinge übertragen wo man füllstände abfragen kann. Mein beispiel war der Wassertransport. Man fährt seinen Kurs ein, wählt dann ein ziel und den wert wann der kurs aktiviert werden soll. Dann läuft der Kurs von selbst ohne das man es immer im Auge behalten muss und von Hand starten/beenden muss jedesmal.

Hatte mich wohl nicht klar genug ausgedrückt.

LG
st1nger

**Comment by Tensuko** [comment]
Alle 6 Ingame Tage mal einen Fahrer einstellen der Wasser holt und die Tiere versorgt wird wohl nicht so schlimm sein oder ? ;)
CP kann das im Grunde.. nur im 19er noch nicht (habs ehrlich gesagt noch nicht probiert).

Aber so geht wirklich der Sinn des spielens kaputt, wenn ich auf nichts mehr achten muss, sondern nurnoch entscheide, welche Frucht auf welches Feld kommt...
Weis nicht ob das so eine gute Idee ist...

**Comment by Stephan-S** [comment]
Ich muss Tensuko hier absolut zustimmen.
Aus Spielersicht halte ich es für nicht besonders sinnvoll, es so umzusetzen.

Aus Programmierersicht, ist es natürlich ein interessantes Projekt :-D

Aber nein, das werde ich nicht in AutoDrive verfolgen.
Man müsste eine Art konfigurierbare 'Regelkette' umsetzen, die dann auf die verschiedenen Gebäude Felder, Courseplay Kurse, AutoDrive Ziele, Fahrzeuge etc. zurückgreifen kann.
Wer so etwas haben möchte, muss es wohl selber umsetzen. Denn ich denke der größte Spaß daran ist das Erstellen eines solchen Mods. Denn danach ist im Spiel nichts mehr zu tun..

Ich schließe das Issue hier mal noch nicht direkt, vielleicht folgt ja noch eine interessante Diskussion aus der sich ja vielleicht doch die ein oder andere realistische Anforderung ergibt :-)

**Comment by andreasthu** [comment]
Ich kann hier mal meine erfahrungen/vorgehensweise aus LS17 einbringen;
Ich hatte zwei CP wasserkurse,
Einer führte vom Hydrant - Kühen - Schweinen - Schafen wieder zum Hydrant. 
Und der fahrer fuhr den kurs öfter ab, bis alles voll war, brauchten die Kühe viel Wasser,  fuhr er mehrmals leer an den Schweinen u Schafen vorbei zum Hydrant auffüllen, bis auch die Schweine u Schafe voll waren,
Dasselbe mit den Produktionsgebäuden, mein cp Kurs führte da ebenso vom Hydrant weg , nacheinander zu den einzelnen produktionsgebäuden wieder zum hydrant zurück. Der cp fahrer fuhr auch hier den kurs mehrmals ab, bis jedes Gebäude mit Wasser versorgt war.
Ich bin diese kurse meistens mit demselben Gespann gefahren, aber manchmal war der Traktor nicht frei, da nahm ich eben einen anderen.
Das ist eigentlich das hauptargument weswegen ich das nicht brauche, weil bei dem automatischen Kursstart, wie hier vorgeschlagen, müsste ich eigentlich immer diesen bestimmten Traktor mit dem Wasserfass in kursnähe rumstehen haben, und könnte ihn quasi für sonst nix verwenden.
Ich hab es so als praktisch empfunden wie ich es in Ls17 hatte, ich musste nicht für jedes gebäude einen einzelnen wasserkurs aufzeichnen,  und nach jedem vollen Wassertrog den kurs wechseln.
Das ging alles mit einem bzw zwei kursen

Lg
Andreas
