### ISSUE TITLE
[BUG] Unload Combine does unneccessary / weird things

### ISSUE THREAD

**Issue by BloodyRain2k** [Stephan-S/FS19_AutoDrive#1360]
**AutoDrive Version:** 1.1.0.5-RC2
**Release or Custom Zip:** Custom but replicated with unmodified zip too
**Map (If applicable):** All
**Multiplayer or Singleplayer:** Singleplayer  

**Describe the bug**  
When the _Unloader_ reacts to a combine it goes into the mode where it's _catching up with combine_, so far everything is as expected, except that it's set to (by default) keep 5m distance to it's rear while doing so, if I've read the tooltip of said setting right, except it doesn't and keeps 50m distance.

But here's the more annying part about that: it's creeping up to the combine after getting 'close' as **if** it was 5m away. Worse of all, it then switches states to _letting combine pass_ despite being 50m behind it.

After that it finally goes into _chasing combine side_, which btw has a typo as it's saying something about _cha**i**sing combine side_. At this point everything works as expected again, it pulls up next to it to trigger the unfolding of the pipe, unloads and then buggers off again.
Most of the time anyways.

Here's a video of the mentioned issue with it letting the combine pass for no reason as well as keeping way more distance to it than the 5m from the settings.
https://youtu.be/x-aIPx4UgGU

Another small issue with certain trailer types is that those with a steering front axle will get screwed up when it's driving backwards because it's not trying to prevent the steering from jamming up.

Oh, and for whatever annoying reason are ALL new vehicles set to _pipe offset_ -0.65m with 1.1.0.5-RC2, didn't have that problem before.
And while on this, why is this setting even saved in the unloader? Shouldn't it be saved in the harvester as that thing is the varying factor for that?

PS: sometimes when chasing the combine while it's doing it's turn it tries to get infront of the combine for some reason and blocks it. Which is annoying combined with the fact that AD doesn't notify you when it should be moving but can't because it's waiting for something to get out of it's way, and the helper being in that phase just as stupid and not saying crap <_<

But I can't reproduce this situation yet so this is just a sidenote.

**Comment by MicaelJarniac** [comment]
I totally agree with you on the pipe offset setting, it makes a lot more sense to have it saved to the combine, instead of the unloader.

If this setting does get moved to the combine, maybe having a tooltip on the pipe offset setting informing that the offset should be set on the combine instead of the unloader would help clarifying it.

And for the unloader getting in front of the combine, I've had it happen to me all the time (though I'm on 1.1.0.4) in one of the contracts I was doing. It didn't happen after that, I think, but for some reason, during that contract, the unloader just kept running straight to the combine and parking right in front of it.

**Comment by AlmostEaster** [comment]
Have the same problem where the unloader gets in front of the combine. Stuck in Clearing crop.

**Comment by Iwan1803** [comment]
We cannot intercept every possible case that could lead to a problem. 
The thresher just keeps on driving and the driver needs a destination. So it can happen that both get in each other's way.
In the next RC there will be some 'enhancement' to this.
