### ISSUE TITLE
[BUG] No way to join waypoints

### ISSUE THREAD

**Issue by blue-painted** [Stephan-S/FS19_AutoDrive#1362]
**AutoDrive Version:** 1.1.0.4   
**Release or Custom Zip:** Release  (Modhub)
**Map (If applicable):** All  
**Vehicle / Type (If applicable):**   
**Multiplayer or Singleplayer:** Singleplayer  

**Describe the bug**  
There seems to be no way to join two specific waypoints. The Wiki and Youtube videos both refer to "Show neighbour" which seems to be missing.

**Comment by BloodyRain2k** [comment]
Click one so it's green, click the next.

**Comment by blue-painted** [comment]
OK I see ... middle click - but that then frees the camera so getting the to next waypoint is more awkward than it should be.

And on second thoughts, what I really was looking for was to merge two waypoints together; I've seen the feature request for that.

**Comment by BloodyRain2k** [comment]
I know that request, 'cause I wrote it, for a reason xD
And middleclick is actually something I was wondering too, because why does it actually react to that?
I've had it a few times in between where I accidentally hovered a node while middleclicking to get the camera back and that really messed up the node of course, because it thought it was being moved.

**Comment by blue-painted** [comment]
It's a very fine request! xD

I'm having a terrible time getting the waypoint to go green. It seems that middle-click and a bit of drag works, some of the time, but often not before the waypoint is moved.

**Comment by BloodyRain2k** [comment]
And left click isn't working? Are you using the mode where you have to hold ctrl for editing?
Maybe try switching to the 2nd editor mode so it stays on instead of having to hold ctrl.
It's somewhere in the settings, 1st panel I think lower right.

**Comment by blue-painted** [comment]
It's (almost) entirely user-error!
Left-click works perfectly ... but the node doesn't turn green until the mouse pointer moves.

**Comment by Iwan1803** [comment]
Not a bug....
If you need further help, join our Discord.
