### ISSUE TITLE
Connect marker titles and folders titles to l10n map files

### ISSUE THREAD

**Issue by PromGames** [Stephan-S/FS19_AutoDrive#1363]
**Is your feature request related to a problem? Please describe.**
In these days, almost every mod map published is by giants rules to have at least translations included for English and German. Spanish, french and Italian are also mandatory.

Then, in the maps, hotspots appears in English in a German map, but autodrive titles are fixed in the language created, normally German. Then, as English speaking person, this is really hard.

We can edit in the xml the titles, but this autodrive sets of courses are updated due to map updates, the you have to start edit again

**Describe the solution you'd like**
I would like to have the possibility of adding any field text in the l10n of the map as title of the course.

**Describe alternatives you've considered**
We can get that with some lúa code that could see the table of l10n and use it as text to display.
When we create the text of the destination we can include the same code that is used in the game.

I know that this has been requested previously, but I would like @Stephan-S to consider the possibility to add some code knowing that you already have l18n also under control.

Thanks in advance

**Comment by Iwan1803** [comment]
Renaming of any target point can be done while in edit mode.
Reading the l10n of the map doesn't make sense.
