### ISSUE TITLE
[BUG] unload a root crop harvester

### ISSUE THREAD

**Issue by dreyvn** [Stephan-S/FS19_AutoDrive#1364]
**AutoDrive Version:** 1.1.0.4
**Release or Custom Zip:** Release  
**Map:** Emerald Coast
**Vehicle / Type:** Any tractor/tipper combination and root crop harvesters
**Multiplayer or Singleplayer:** Singleplayer  

When using a tractor/tipper combo to unload a root crop harvester (in this case the holmer terra dos t4-40) the driver gets stuck on calculating a path and will sit there indefinitely.  I do not have this issue when using a semi and trailer to unload the harvester.
![iOqHAQL](https://user-images.githubusercontent.com/63569665/79633219-c2333700-8129-11ea-9a46-45ef693f6d17.jpg)

**Comment by Iwan1803** [comment]
You should update to a newer version (Release 1.1.0.4 or RC 1.1.0.5-RC2).

**Comment by dreyvn** [comment]
> You should update to a newer version (Release 1.1.0.4 or RC 1.1.0.5-RC2).

Sorry this was occuring in 1.1.0.4. I had downgraded to 1.1.02 before i took the screenshot.

**Comment by Iwan1803** [comment]
Try the latest RC and don't downgrade to older versions....
If the problem still exists, please create a new issue.
