### ISSUE TITLE
[FEATURE REQUEST] Highlight dead ends

### ISSUE THREAD

**Issue by BloodyRain2k** [Stephan-S/FS19_AutoDrive#1365]
While AD tries it best to show which direction a segment goes, it can still happen that you have one in between that's facing the wrong way.
Finding this somewhere can be a bothersome task, if you even **know** that this is what you're looking for.

So I thought it would be nice if dead ends could get a small orange triangle or something above them, just to draw your attention. If they're intentionally done, you can still ignore them anyways.

And by dead ends I mean both, those where two segments point toward each other without a way to go as well as unconnected ends, for the case you have 2 overlapping nodes which **look** connected but aren't.

A third case might be where segment has no path option that's below 90 deg, because that's not rarely what AD gives me when I record a new route while having _auto connect start_ on.

**Comment by Iwan1803** [comment]
Imlemented in 1.1.0.5-RC3.

**Comment by BloodyRain2k** [comment]
https://drive.google.com/uc?id=11ZIkT2iakWkPVsIy28vM_OxDstCEA4Va

"Das denke ich nicht, Tim."

**Comment by Iwan1803** [comment]
> - ADDED: neuer Debug-Channel für das Streckennetz
> - ADDED: Markierung von offenen Strecken und nicht verbundenen Wegpunkten durch ein Sackgassen-Schild (können als Ziel angefahren werden)

**Comment by haamic** [comment]
Ihr solltet vielleicht dazuschreiben, das das sackgassenschild nur angezeigt wird, wenn in den Debug Einstellungen auch das steckennetz angehakt ist. Das erschließt sich nicht so direkt aus den rausgehauenen Textbrocken zu den Neuerungen. 

Kleine Frage zusätzlich, seit RC3 fällt mir auf, das ich nach Spielstand laden bei jedem Fahrzeug immer das AD HUD mit LALT+Keypad0 wieder einblenden muss. Wurde da was geändert oder ist das ein Bug?

**Comment by BloodyRain2k** [comment]
> Kleine Frage zusätzlich, seit RC3 fällt mir auf, das ich nach Spielstand laden bei jedem Fahrzeug immer das AD HUD mit LALT+Keypad0 wieder einblenden muss. Wurde da was geändert oder ist das ein Bug?

Das Problem habe ich zB nicht, Bug?

**Comment by haamic** [comment]
Jetzt gehts komischer weise, hatte nochmal gespeichertun Spielstand neu geladen. 
betrachte ich als erledigt.

**Comment by Iwan1803** [comment]
Das passiert manchmal nach einem RC-Update, warum auch immer.
Einmal wieder einschalten, speichern und fertig.
