### ISSUE TITLE
[FEATURE REQUEST] Mode menu

### ISSUE THREAD

**Issue by BloodyRain2k** [Stephan-S/FS19_AutoDrive#1366]
Because I believe that AD will only get more modes as time goes by: could a small button grid open when you click the Mode Button instead of cycling them?
Just have a button for each mode in there so you can choose the one you want directly.

And for the keybind: a radial menu would be amazing, but no idea if that's doable easy, or at all. I only know that the Console version has one, maybe the PC can use it too? No idea, but lots of hopes xD

**Comment by Bobster82** [comment]
> Because I believe that AD will only get more modes as time goes by: could a small button grid open when you click the Mode Button instead of cycling them?
> Just have a button for each mode in there so you can choose the one you want directly.
> 

I vote for this ;)

**Comment by Iwan1803** [comment]
There is no plan to implement such amount of modes that this is needed.
