### ISSUE TITLE
[BUG] Abfahrer auf dem Server 

### ISSUE THREAD

**Issue by fischi3016** [Stephan-S/FS19_AutoDrive#1367]
AutoDrive Version: 1.1.0.5 RC2
Release or selbsterstelltes zip: entpackt und autodrive neu gezippt
Karte (falls relevant): Alle
Fahrzeug(art) (falls relevant):

**Beschreibe den Bug**
Wenn ich den Hächsler selber fahre kommt der Abfahrer nicht. Schalte ich allerdings den Helfer an wird auch der Abfahrer gerufen. Helfer und Hächsler sind auf Wiese 1 gestellt und der Abfahrer hat den Zielpunkt silo. Im Singleplayer klappt das ohne Probleme. Hat einer ein Tipp?

**Comment by Valentohallon** [comment]
Gehe in die Drescher Einstellungen und klicke dann zweimal auf den obersten
Pfeil Abfahrer finden danach müsste es wieder funktionieren
Falls du das noch nicht weißt du musst den Wegpunkt auswählen wo dein
Abfahrer startet.

Am Samstag, 18. April 2020 schrieb fischi3016 <notifications@github.com>:

**Comment by fischi3016** [comment]
Ok teste ich nachher mal. Wegpunkt meinst du etwa im Hud wiese 1 und wo er hin soll richtig?  Also Ziel Wiese 1 und abkippen silo und beim Hächsler im Hud Wiese 1

**Comment by fischi3016** [comment]
![fsScreen_2020_04_18_22_35_54](https://user-images.githubusercontent.com/63921968/79670775-be54f280-81c5-11ea-8433-8a109e0bb70a.png)
![fsScreen_2020_04_18_22_36_06](https://user-images.githubusercontent.com/63921968/79670779-c14fe300-81c5-11ea-9431-a015099b0000.png)
![fsScreen_2020_04_18_22_38_42](https://user-images.githubusercontent.com/63921968/79670781-c3b23d00-81c5-11ea-81eb-4b128b2f4214.png)


Will trotzdem nicht

**Comment by bizzybone88** [comment]
Guck mal in deinen Tastenbelegungen, dort gibt es "AD: Abfahrer rufen", vielleicht hilft dir das wenn du selber Dreschen möchtest.

**Comment by fischi3016** [comment]
Oh danke teste ich nachher gleich mal. Nur komisch das es im sp und mp normal alleine kommt nur auf dem Server nicht. Aber danke ich teste nachher mal. Daran hab ich noch gar nicht gedacht

**Comment by fischi3016** [comment]
klappt wunderbar vielen dank für deine Hilfe. Top. Sag ja es sind die kleien dinge auf die es ankommt ^^
