### ISSUE TITLE
[FEATURE REQUEST] Key binding for parking

### ISSUE THREAD

**Issue by MaxTechCode** [Stephan-S/FS19_AutoDrive#1369]
**Describe the solution you'd like**
It would be great if there would be the possibilty to asign a shortcut to park the vehicle. So just like the editor mode, etc.

Thanks in advance
MaxTech
PS. Your doing an excelent job.

**Comment by Bobster82** [comment]
@MaxTechCode , I dont know how long u have been using autodrive, but a parking button is part of it a long time now ;)

**Comment by MaxTechCode** [comment]
@Bobster82 I'm aware of the button in the GUI. But I would like to have the possibility to press for instance ALT+P and the vehicle is automtically going to park. So I do not have to activate the mouse and press the button.
My description might have been a little unprecise. Sorry

**Comment by Iwan1803** [comment]
Wurde eingebaut / was integrated -> 1.1.05.-RC5.

**Comment by MaxTechCode** [comment]
Vielen Dank/Thanks a lot :-)
