### ISSUE TITLE
Settings/GUI won't open

### ISSUE THREAD

**Issue by Soilaq** [Stephan-S/FS19_AutoDrive#137]
Left alt + numpad 0 doesn't open settings for me. Can't find a way to change keybinds in xml either.

**Comment by Soilaq** [comment]
It's all my fault! Got told the wrong keybind. CTRL+ALT+Num0 worked perfect. I would love to be able to change this in the settings/xml tho. Personally I only play with a small wireless keyboard that doesn't have numpad, so I need to use windows on-screen keyboard.
Sorry for the bother!

**Comment by Stephan-S** [comment]
Hey, you can Change all keybindings in the Standard menu of Farming Simulator. All Key mappings of AutoDrive start with AD:,
So they should be easy to find

**Comment by Soilaq** [comment]
I checked multiple times, the one for opening the GUI doesn't show for me at least. I can make a gif or video if you'd like. Couldn't find it in the xml with the other binds either.

**Comment by Stephan-S** [comment]
Hey,
yeah I guess the name is not well chosen:

<text name="input_ADOpenGUI">
	<en>AD: Open GUI</en>
	<de>AD: Menü öffnen</de>
	<it>AD: Apri menu</it>
	<fr>AD: Ouvrir GUI</fr>
	<es>AD: Mostrar menu</es>
</text>

You should see one of those texts, depending on your language settings.

**Comment by Stephan-S** [comment]
Since I got no more feedback, I am closing this issue. If any problems are left unresolved, please reopen
