### ISSUE TITLE
Keine Schnittlängenverstellung bei Baumfällmaschine[BUG]

### ISSUE THREAD

**Issue by Solid82** [Stephan-S/FS19_AutoDrive#1371]
![fsScreen_2020_04_19_18_37_44](https://user-images.githubusercontent.com/63969860/79693772-f9f6c780-826c-11ea-90f2-129f912cc937.png)

Kann beim Harvester keine Länge der Bäume mehr verstellen. Das HUD von AD überdeckt die Einstellmöglichkeiten Z für die Länge einzustellen.

**Comment by BloodyRain2k** [comment]
1. Man kann einstellen das AD keine Hilfe anzeigt, musste ich aus dem selben Grund machen.
2. Giants hat das verbockt. Ich weiss nicht mehr wann und wie, aber meine Hilfeliste ging mal bis zum unteren Bildschirmrand, aber in diesem Fall tut sie das nicht, warum auch immer.

Es gibt auch eine Mod die solche Info "Hilfetasten" separat anzeigt, aber leider zeigt diese auch nur das an was ueberhaupt erst in der Liste auftaucht, bringt also bei diesem Problem leider absolut garnichts.

**Comment by Axel32019** [comment]
Kein AD spezifisches Problem, kommt auch mit anderen Mods daher...
Einfach zur Innenansicht wechseln. Auf dem Armaturenbrett steht die aktuelle Länge - jetzt mit Z die gewünschte Länge einstellen und go...

**Comment by Iwan1803** [comment]
Es ist echt schade, was Giants da mit uns macht und das man die Länge des Hilfemenüs nicht einstellen kann.
Wie schon beschrieben, am besten die AD-Hilfe für das Menü ausblenden und schon sollte es wieder soweit passen:
![image](https://user-images.githubusercontent.com/47528836/79732898-97e1a500-82f4-11ea-94eb-35dede780174.png)
