### ISSUE TITLE
[FEATURE REQUEST] Trailers' Parking Assignment

### ISSUE THREAD

**Issue by alex2ruote** [Stephan-S/FS19_AutoDrive#1373]
It would be nice to assign a parking spot (with its own button) not only to the tractors/trucks, but to the various implements and trailers as well so that they can find their way home no matter what's pulling them, especially now that the reverse parking is possible. My dropdown list looks like a Chinese menu.
Thanks, Alex

**Comment by MicaelJarniac** [comment]
Reverse parking? :o How? I've been searching for that and couldn't find it.

And I totally agree with having an option to park a trailer too.

Maybe even having a button on the HUD that, when pressed, checks what's your current trailer's parking spot, then drives there, detaches the trailer, then drives to your truck's parking spot and stops there. That way both get parked, both on their own spot. And it doesn't even need reversing to work (though it'd be awesome).

Even cooler (though this one would require reversing I think) would be to do the opposite too. You head into a truck, then clicks a menu, choose the trailer you want (probably choose the trailer parking spot that trailer is in), then your truck drives there and attaches the trailer for you.

**Comment by alex2ruote** [comment]
The reverse driving feature is in the release candidate version 1.1.0.5 
You have to activate it in the settings menu.

**Comment by MicaelJarniac** [comment]
Now I'm excited! I'll make sure to try it ASAP (just hoping the release candidate is also fully compatible with Courseplay).

Thanks! :D

**Comment by Iwan1803** [comment]
See https://github.com/Stephan-S/FS19_AutoDrive/issues/1225
