### ISSUE TITLE
Berechne Pfad dauert ewig[BUG]

### ISSUE THREAD

**Issue by Moitzbert** [Stephan-S/FS19_AutoDrive#1374]
Woran könnte das liegen wenn die Berechnung der Pfade, zb beim wenden des Häckslers oder wenn der Abfahrer zum Feld zurück kommt, ewig dauert ??

**Comment by rmn18** [comment]
Ich tippe mal das hat mit der Pfadfindung zu tun ,das mus der Dev. wohl noch mal ran ,vllt Debuging mit Pathfinding oder so mit anmachen und die Log hier posten wenn das Berechnen anfängt und nix weiter mehr passiert.

**Comment by rmn18** [comment]
Was mir hier aufgefallen ist das wenn ich eine andere Drescherkombi und Abfahrer nutze klappt das Berechnen wie gewohnt wieder ,vllt mal einen anderen Drescher nehmen wie auch Abfahrer nutzen bis AD wieder einen stabilen Zweig hat .

**Comment by schuelli238** [comment]
@rmn18 Kannst du mal eine funktionierende Kombi hier posten?

**Comment by rmn18** [comment]
Jop Case Drescher  ,und Class 960 Traktor mit Joschkin Drakkar Anhänger ,Map hab ich die Opberthal nur CP und AD drin ,keine weiteren Maps oder Mods

**Comment by BloodyRain2k** [comment]
Was mir aufgefallen ist, ist dass der Pathfinder manchmal ein bissel deppert ist.

Das eine mal stand mein Unloader vom Combine in Feld 13 von Ravenport und zeigte zum Abhang, hinter ihm war aber ein sehr leicht erreichbarer Pfad.
Die Dummsau hat lieber nach 15 sec oder wasweisich Aufgegeben statt es offenbar mal Rueckwerts zu probieren.
Hab ihn dann manuell gewendet und nochmal suchen lassen: zack nach etwa 1 Sekunde schon auf dem Weg zum Pfad <_<

Was er allerdings am liebsten macht wenn ich ihn einschalte ist einen U-Turn statt die andere "Strassenseite" des Pfades zu nehmen.

Beispiel: Unloader steht neben einer Strasse die fuer beide Richtungen jeweils eine "Spur" hat.
Das Ziel liegt etwa in der Richtung in die er gerade zeigt, aber die entgegenkommende Spur der Strasse ist zwischen ihm und der "Spur" die er nehmen soll.
Er macht in diesem Fall fast immer einen U-Turn statt einfach ueber die entgegenkommende Spur in seine zu fahren -_-

**Comment by Iwan1803** [comment]
Besteht das Problem noch?
