### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Moitzbert** [Stephan-S/FS19_AutoDrive#1375]
Woran könnte das liegen wenn die Berechnung der Pfade, zb beim wenden des Häckslers oder wenn der Abfahrer zum Feld zurück kommt, ewig dauert ??

**Comment by Iwan1803** [comment]
Kein vernünftiger Titel, das Formular nicht ausgefüllt...
Sorry, aber unsere Hellseher können wir aufgrund von Corona nicht kontaktieren und die Glaskugeln sind in der Reinigung.
