### ISSUE TITLE
collision after unloading combine[BUG]

### ISSUE THREAD

**Issue by alku50** [Stephan-S/FS19_AutoDrive#1376]
**AutoDrive Version:** 1.1.0.5.RC2  and  1.1.0.4     CP:...... 398
**Release or Custom Zip:** Releases  from guithub 
**Map (If applicable): Nebraska Lands USA 
**Vehicle / Type (If applicable):  CLAAS LEXION DLC  / CLAAS CIRION DLC
**Multiplayer or Singleplayer:** Singleplayer  

**Describe the bug**  
combine collides with tractor after unloading, tested with different Lexions and tractors,
 (reverse driving allowed: ja). In earlier versions the tractor did drive back after unloading. 
Sometimes "Drescher zurücksetzen" stays on. The tractor does move after on and off of AD. ?

Nevertheless - AutoDrive is a miracle. Without - I would not play FS !  Thanks.

![Kollision](https://user-images.githubusercontent.com/53400721/79771662-63d7a580-832f-11ea-9ca7-d1633cb151ce.jpg)

**Comment by schuelli238** [comment]
Looks like you have the "Vehicle Control Addon (VCA)" mod enabled. If you disable it, it will work as expected.

**Comment by alku50** [comment]
Thank you, Andre. Of course you are right. I like to use two features of VCA: constant speed and the compass bearing. Do you know an alternative for this two functions?  Thanks.

**Comment by schuelli238** [comment]
What does constant speed? What's the difference to the already implemented cruise control?

Guidance Steering from Wopster is a very good mod for GPS controlled steering.
https://github.com/stijnwop/guidanceSteering

**Comment by alku50** [comment]
Dear Andre

Thank you for your support. 
> What does constant speed? What's the difference to the already implemented cruise control?
> 
> Cruise control only works in forward.
> VCA „keep speed constant  /Geschwindigkeit permanent halten“ :  with W or S you change the speed (reverse is negative speed). The speed stays constant at the same level until changed with W or S. 
   This is gives a very convenient driving much easier  then in-game FS19 procedure were you have to manually keep the speed at the desired level.

> Guidance Steering from Wopster is a very good mod for GPS controlled steering.
> https://github.com/stijnwop/guidanceSteering <https://github.com/stijnwop/guidanceSteering>
> I do see the compass bearing on the map. Thats all I need. I like the guidance with CP very much and want to use this.



I did some investigation  on the problem because in my opinion both Mods AD and VCA are basic and very essential for FS19. 

There are others having the same problem with the conflict  AD/VCA  ( GitHub/ VCA / #303). 
It seams that the problem could be solved on your side with putting the vehicle into the „hired worker mod“.  ??

Maybe you could check this on your side.

Thank you Andre and stay healthy.
Alex

**Comment by alku50** [comment]
Dear Andre

Did you already have time to consider a solution for the conflict with VCA:

> There are others having the same problem with the conflict  AD/VCA  ( GitHub/ VCA / #303). 
> It seams that the problem could be solved on your side with putting the vehicle into the „hired worker mod“.  ??


Kind regards
Alex



> Am 21.04.2020 um 11:38 schrieb Alex Kugler <kuglerah@bluewin.ch>:
> 
> Dear Andre
> 
> Thank you for your support. 
>> What does constant speed? What's the difference to the already implemented cruise control?
>> 
>> Cruise control only works in forward.
>> VCA „keep speed constant  /Geschwindigkeit permanent halten“ :  with W or S you change the speed (reverse is negative speed). The speed stays constant at the same level until changed with W or S. 
>    This is gives a very convenient driving much easier  then in-game FS19 procedure were you have to manually keep the speed at the desired level.
> 
>> Guidance Steering from Wopster is a very good mod for GPS controlled steering.
>> https://github.com/stijnwop/guidanceSteering <https://github.com/stijnwop/guidanceSteering>
>> I do see the compass bearing on the map. Thats all I need. I like the guidance with CP very much and want to use this.
> 
> 
> 
> I did some investigation  on the problem because in my opinion both Mods AD and VCA are basic and very essential for FS19. 
> 
> There are others having the same problem with the conflict  AD/VCA  ( GitHub/ VCA / #303). 
> It seams that the problem could be solved on your side with putting the vehicle into the „hired worker mod“.  ??
> 
> Maybe you could check this on your side.
> 
> Thank you Andre and stay healthy.
> Alex

**Comment by Iwan1803** [comment]
Does the problem still exist?

**Comment by alku50** [comment]
There is no answer from the AutoDrive Team jet. It still existed a few days ago. But I haven’t updated AD for wile. Now I’m done harvest. I’ve been using CP for the headlands only and did the back and forth with the helper and manual input. If there is no solution for the conflict, I will ask the CP team to extend the backup distance of the combine - for next season 🙂.

**Comment by Iwan1803** [comment]
The tractor normally drives backwards after unloading a combine. So they can't collide.
If VCA blocks backward driving, then this is not a problem of AD or CP.
In VCA you can try to set helper transmission to "allways" as this known as problem or disable VCA for testing.

**Comment by Williwillswisse** [comment]
Problem solved.
Tested with
CP 00029
AD 1.1.0.5-RC4
VCA 171

**Comment by alku50** [comment]
Thank you very much. I’m doing winter chores in my gameplay at the moment. Looking forward to harvest in few weeks.

I would not play FS without AD, CP and VCA. Enjoy the coffees is sent you :-)).

Best regards
Alex
