### ISSUE TITLE
[BUG] the new update does not contain the tools that I need to set my guides I cannot figure out this new update help me please

### ISSUE THREAD

**Issue by madlesley** [Stephan-S/FS19_AutoDrive#1377]
**AutoDrive Version:** 1.1.x.x   
**Release or Custom Zip:** Release  
**Map (If applicable):** All  
**Vehicle / Type (If applicable):**   
**Multiplayer or Singleplayer:** Singleplayer  

**Describe the bug**  

**If applicable - Steps to reproduce the behavior**  

**Screenshots**

**Comment by madlesley** [comment]
The problem I am having with the new update I started a new map and I could make my network around I figured out how to do the auto start in the auto and connect in the last version you would be able to click a button that would update the system and allow you to go different places I cannot figure out how to get this one to update so I want to go off of my main line to my garage it says it cannot reach that location how do I get it to do that

**Comment by madlesley** [comment]
![15874340819138337297655275758252](https://user-images.githubusercontent.com/64051114/79816664-5fb88180-8349-11ea-82f3-72383f78ebe7.jpg)
It has changed and I cannot figure out how to do it

**Comment by Iwan1803** [comment]
1st: very long and stupid title, which doesn't help
2nd: the form is not only there to look at, but to fill it in
3rd: the sentences are too long and without punctuation marks, so i won't try to read it or understand it

**Comment by corbors** [comment]
Same here I cant find were update network button

**Comment by Iwan1803** [comment]
If I understand it correctly, he has a network problem and you're looking for a button.
Where is it the same thing, please?

**Comment by blue-painted** [comment]
I *think* he means that there used to be a "Refresh network" button that you had to click after changes, it's certainly in the video.

**Comment by Iwan1803** [comment]
The "calculate network" button is gone since some versions as it is no longer needed.

**Comment by blue-painted** [comment]
That's what I thought. Is there a change-log I (and others?) should be looking at?

**Comment by Iwan1803** [comment]
For the latest RC you can find it on Disord.
