### ISSUE TITLE
[BUG] okay I've been trying to figure out Auto drive ever since I did the update I can create a network but I cannot get it to connect and work it keeps saying cannot reach location I want the old version of auto drive back how do I delete the update out otherwise I'm just going to turn off auto drive and not use it what a waste I love that feature

### ISSUE THREAD

**Issue by madlesley** [Stephan-S/FS19_AutoDrive#1378]
**AutoDrive Version:** 1.1.x.x   
**Release or Custom Zip:** Release  
**Map (If applicable):** All  
**Vehicle / Type (If applicable):**   
**Multiplayer or Singleplayer:** Singleplayer  

**Describe the bug**  

**If applicable - Steps to reproduce the behavior**  

**Screenshots**

**Comment by madlesley** [comment]
You probably won't do it but if you could email me at ColeJulie@yahoo.com explain to me how to fix my issue I would appreciate it my name is Leslie Cole

**Comment by TobiHH78** [comment]
There are a lot of good videos on YouTube. Just take a few minutes time, AutoDrive is really great and easy to use.

**Comment by alex2ruote** [comment]
BTW, you can download an older release and just substitute the zip file in the mod folder.
https://github.com/Stephan-S/FS19_AutoDrive/releases

**Comment by Iwan1803** [comment]
Same like in https://github.com/Stephan-S/FS19_AutoDrive/issues/1377
