### ISSUE TITLE
[BUG] auto Collision does not work

### ISSUE THREAD

**Issue by BANO72** [Stephan-S/FS19_AutoDrive#1379]
AutoDrive Version: 1.1.0.4
Release or selbsterstelltes zip: Release
Karte (falls relevant): Ravenport
Fahrzeug(art) (falls relevant):

Bin neu mit autodrive unterwegs, großes Kompliment an euch.
Mein Problem ist folgendes ( vieleicht unterstüzt Autodrive das auch nicht , was schade wäre)
Ich habe mehre Routen erstellt, alles funktoniert einwandfrei, außer das alle Fahrzeuge immer mit dem Zug ( bzw. der Schranke ) kollidieren und auch alle AI Fahrzeuge werden nicht erkannt.
In den Settings habe ich Auto Collision aktiviert.

Wenn ich Courseplay verwende dann werden die Schranken sauber erkannt und die Fahrzeuge warten bei geschlossener Schranke 

VG
Norbert

**Comment by Iwan1803** [comment]
Bitte mal mit dem aktuellen RC testen.

**Comment by BANO72** [comment]
Hi
ich hab jetzt die aktuelleste version drauf:

AI Auto und andere Fahrzeuge checkt er jetzt
aber bei den Schranken hat er immer noch ein problem, wenn die Schranke zu geht dann bremst er nicht und fährt volle wucht in die Schranke, und steht dann da mit vollgas solang bis die Schranke öffnet,

**Comment by Iwan1803** [comment]
_Please download 1.1.05.-RC4, try again and then post a feedback._
Bitte lade 1.1.05.-RC4 herunter, versuch es erneut und poste dann ein Feedback.

Changelog: https://github.com/Stephan-S/FS19_AutoDrive/wiki/Release-Notes
