### ISSUE TITLE
Zielpunkte - Reihenfolge ändern?

### ISSUE THREAD

**Issue by andreasthu** [Stephan-S/FS19_AutoDrive#138]
HAllo @Stephan-S 
habe nun mitlerweile alles so hinbekomme nmit Autodrive,
jedoch, hab ich überlegt, da die Zielpunkte in der Reihenfolge dutchgescrollt werden, wie gespeichert, diese in der AutoDrive_my_Felsbrunn_MF_config.xml zu sortieren.
naja, klappt nciht so wie ich es mir vorgestellt hatte.
das ist die originale xml:
[AutoDrive_my_Felsbrunn_MF_config - original.xml.txt](https://github.com/Stephan-S/FS19_AutoDrive/files/3215591/AutoDrive_my_Felsbrunn_MF_config.-.original.xml.txt)

darin habe ich die zwei zeilen zwischen alles zwischen <mm...> und </mm...>
rauskopiert und in die sortierte reihenfolge verschoben, also aus:
`        <mapmarker>
            <mm1>
                <id>2.000000</id>
                <name>1.HauptHOF</name>
            </mm1>
            <mm2>
                <id>800.000000</id>
                <name>2.Burghotel</name>
            </mm2>
            <mm3>
                <id>220.000000</id>
                <name>2.TransportFirma</name>
            </mm3>
            <mm4>
                <id>258.000000</id>
                <name>3.BaStMuehle</name>
            </mm4>
            <mm5>
                <id>1069.000000</id>
                <name>2.BahnsiloWest</name>
            </mm5>
            <mm6>
                <id>2128.000000</id>
                <name>1.Shop</name>
            </mm6>
            <mm7>
                <id>2338.000000</id>
                <name>2.Hafen Sued</name>
            </mm7>
            <mm8>
                <id>3015.000000</id>
                <name>2.BauerHans</name>
            </mm8>
            <mm9>
                <id>3061.000000</id>
                <name>4.Tanken West</name>
            </mm9>
`

wurde:
`        <mapmarker>
            <mm1>
                <id>2.000000</id>
                <name>1.HOF.Mitte</name>
            </mm1>
            <mm2>
                <id>2128.000000</id>
                <name>1.Shop</name>
            </mm2>
            <mm3>
                <id>1069.000000</id>
                <name>2.Bahnsilo.West</name>
            </mm3>
            <mm4>
                <id>3015.000000</id>
                <name>2.Bauer.Hans</name>
            </mm4>
            <mm5>
                <id>800.000000</id>
                <name>2.Burghotel</name>
            </mm5>
            <mm6>
                <id>3695.000000</id>
                <name>2.Gasthaus</name>
            </mm6>
            <mm7>
                <id>5305.000000</id>
                <name>2.Hafen.Nord</name>
            </mm7>
            <mm8>
                <id>2338.000000</id>
                <name>2.Hafen.Sued</name>
            </mm8>
            <mm9>
                <id>4326.000000</id>
                <name>2.Ranch</name>
            </mm9>`

also "id" und "name" bleiben gleich, wurden nur in ein anderes "mm" verschoben,
schaut dann so aus:
[AutoDrive_my_Felsbrunn_MF_config.xml.txt](https://github.com/Stephan-S/FS19_AutoDrive/files/3215603/AutoDrive_my_Felsbrunn_MF_config.xml.txt)

wenn ich nun aber zu "mm9 - id: 4326, name: ranch," will, fährt autodrive aber zur Tanken West, was in der originalen datei mm9 war (mm9 id 3061, name: Tanken west)
Bild:
![fsScreen_2019_05_24_09_16_27](https://user-images.githubusercontent.com/24860501/58310383-cd40f280-7e06-11e9-8f3d-b194ea22548c.png)

was habe ich da übersehen,, funktioniert das überhaupt?

lg
andreas

**Comment by Stephan-S** [comment]
Hey,
da fehlt nur noch mal eine Neuberechnung, um das 'Mapping' wieder zu korrigieren.
Danach sollte es wie du es dir vorgestellt hast funktionieren

**Comment by andreasthu** [comment]
Danke dir.
Funktioniert nun nach einer Neuberechnung wunderbar.
Lg
Andreas

**Comment by Stephan-S** [comment]
Wunderbar :-) Dann mache ich hier mal zu.
