### ISSUE TITLE
Setting the unloading side

### ISSUE THREAD

**Issue by Matzenie** [Stephan-S/FS19_AutoDrive#1380]
At some unloading points you cannot unload with every possible unloading side of the trailer. Some of the trailers and tractors get wedged.

A possible solution would be to restrict the unloading side of the trailer or to explicitly select the unloading side.

**Comment by Iwan1803** [comment]
Examples, where you can't unload because of the wrong side?

**Comment by Matzenie** [comment]
The problem is particularly with silos and points of sale. Mechanical collisions require a special unloading side to be selected. Examples: A roof over the unloading point, then bad in the back. a wall on the side is then unfavorable on the side. On the Rade, the tractor and trailer wedged in the entrance to the silo.

**Comment by Iwan1803** [comment]
F.e.: if you select several targets for unloading with different sides for unloading, how should this work?
We could detect if there's a wall or a roof, but that would make things very complicated.
Choosing an other trailer (with a sliding floor) could be the best option. Also Rade is not really AD friendly....
