### ISSUE TITLE
[BUG] problem moving waypoints

### ISSUE THREAD

**Issue by Berndi** [Stephan-S/FS19_AutoDrive#1381]
AutoDrive Version: 1.1.x.x
Release or selbsterstelltes zip: Release
Karte (falls relevant): Alle
Fahrzeug(art) (falls relevant):

Moin ich versuche den streckenpunkt zu verschieben mit gehaltener rechtenmaus taste aber es geht nicht in einem viedo wurde es so gesagt das man es so macht aber geht bei mir nicht und bei einem kolegen auch nicht.
Aber sonnst suoer arbeit von euch danke dafür

**Comment by vertigoogle** [comment]
Hi Berndi,

habt ihr die Wegpunkte über dem Traktor oder auf dem Boden? Wenn ersteres, dann versucht mal die roten Kugeln am Boden zu verschieben, nicht die über dem Traktor.

Außerdem sei zur Sicherheit erwähnt, dass das natürlich nur im Editormodus 2 funktioniert (STRG gedrückt halten).

Wenn unklar, dann meld dich nochmal :)

**Comment by BloodyRain2k** [comment]
Das ist auch so eine Sache die ich an dem Modus mit den schwebenden Linien nicht verstehe: **alles** geht mit denen, ausser verschieben...

**Comment by vertigoogle** [comment]
Rechte Maustaste halten und die **unteren** Kugeln ziehen. Sollte wunderbar funktionieren.
Schickt doch mal ein Bild wie der Editormodus bei euch aussieht :)

**Comment by Iwan1803** [comment]
Besteht das Problem noch?

**Comment by Iwan1803** [comment]
Bitte 1.1.0.5-RC3 ausprobieren. Sollte das Problem dann noch bestehen, einfach ein neues Issue aufmachen.
