### ISSUE TITLE
[FEATURE REQUEST] Smart targets with attributes

### ISSUE THREAD

**Issue by MicaelJarniac** [Stephan-S/FS19_AutoDrive#1382]
There are times a road is too narrow for a combine harvester, but wide enough for a tractor. Other times, there are turns too sharp for a truck with a trailer, but a car can take them just fine.

My suggestion is to have the possibility to add smart attributes to targets, and those attributes being considered when planning routes or going through those smart targets.

For example, if a road is too narrow for a combine, we could add a target at the beginning and end of said road, then add to that target the "narrow" attribute, that would prevent combines from taking that road, forcing them to plan a different route, but allow narrower vehicles to go through.
And maybe even add a specific size limit to that attribute, like "2m", that would only allow vehicles under 2m wide to go through. This would be similar to real life and how we have signs before bridges, stating how high they are, and that you should only go under them if you're below that height.

Another example would be for difficult turns. If a road has turns that a long vehicle can't take, we could add a target at the beginning and end of that road with the "difficult turns" attribute, and vehicles that can't take difficult turns will always prefer a different path.

And having custom attributes would be cool too. Like, if I create a target I can add a custom attribute named "apple", and have that be a whitelist or a blacklist. If it's a whitelist, only vehicles that also have the "apple" attribute can go through, but if it's a blacklist, any vehicle can go through, except the ones that have the "apple" attribute.

A different kind of attribute to smart targets could be for speed limits. This one wouldn't act as a "barrier" like the other ones, but instead it would simply prompt all vehicles that go through it to limit their speed to its setting, and then having another target with an attribute to clear the speed limit after that segment.

A perhaps more useful attribute would be for tipping side. Some unload spots are tricky to get in, and might require having the tipping side of your trailer set correctly in order to be able to unload there automatically. With this attribute, vehicles that go through this target will have their tipping side changed automatically, to match the required tipping side for a tricky unloading.

And for those attributes that act like a barrier, we could have the option to either make them mandatory, as in if a vehicle doesn't meet its requirements, it will be blocked no matter what, or flexible, as in if a vehicle doesn't meet its requirements, it'll prefer a different route, but if there's no other route possible, then it'll be allowed to go through the barrier.

Having these features would, in my opinion, make creating routes an easier process, as we wouldn't have to worry about every single turn being possible for long trucks and large combines, for example.
We would be able to create routes going through every single possible road, even the hardest ones, but then limit what kind of vehicles can take those routes, instead of having to keep our routes to only easy ones to avoid future problems.

Example of attributes:

| Type | Name | Effect | Arguments |
|--|--|--|--|
| Barrier | Width | Blocks vehicles based on their width | width, higher/lower, mandatory |
| Barrier | Turns | Blocks vehicles based on their turn radius | turn radius, higher/lower, mandatory |
| Barrier | Custom | Filters vehicles based on custom attributes | name, white/blacklist, mandatory |
| Info | Speed | Limits speed of vehicles that go through it | start/end |
| Info | Tip side | Informs vehicles that go through it which tipping side they should use for unloading | tipping side, after/before target (so it can be added to existing unload targets) |
| Info | Avoid | Acts like a weight, so routes that go through this target receive a lower priority | weight |
| Info | Attach | Going through this target will tell the vehicle to, for a set distance, trigger any attach prompt (like when reversing to a spot where a tool was parked), detach the tool on the spot, or any (detach if it has a tool, otherwise try to attach one) | effect distance, attach/detach/any |
| Info | Collision Detection | Going through this target will tell the vehicle to enable/disable collision detection, or reset it to what it was before | enable/disable/reset |
| Hotspot | Refill | Marks a refill spot | type of refill (multiple), load/unload, parent target/group |
| Hotspot | Silo | Marks a silo loading/unloading spot | type of silo (multiple), load/unload, parent target/group |
| Hotspot | Parking | Allows vehicles to park, remembers (or checks) if it's available or occupied, and can filter vehicles that can park by their size | optional size (min/max), parent target/group |
| Hotspot | Tool Storage | When a vehicle is requested to park at a parent target/group that contains this target, if the vehicle has a tool that matches the filter of this Hotspot, it'll first go to it, then detach the tool, and then proceed | tool, parent target/group |

Types:

| Type | Description |
|--|--|
| Barrier | If a vehicle fits into its filter, it'll see that target as being a missing waypoint, and that segment of the road will be ignored by it, unless it's not a mandatory barrier and there's no other possible path |
| Info | I couldn't think of a better name for this type, but it's basically informing vehicles that go through it about a certain setting that they should follow, or clearing such setting |
| Hotspot | Acts as a normal target, but it's selected automatically by its type and distance when targeting its parent target or group, and if targeting a parent target, the vehicle will go to the parent first, then make its way to the hotspot |

**Comment by Martinnygaard** [comment]
I like this idea very much!

**Comment by Bobster82** [comment]
That is a great idea! , I always struggle with diff size vehicles on roads, so I posted a request (as many did) about multiple color lines where vehicles can or cant go over ... So I dont mind how its gonna be implemented, I hope it would be implemented.

**Comment by MicaelJarniac** [comment]
@Bobster82
I thought about doing it using targets as I think it's easier to implement and would be more user friendly, easier to configure and to keep track of.

But now that you mentioned it, I think that it would be cool to have the lines change color to reflect the smart targets in them, like if somewhere in a road there's a smart target limiting width, the entire road could turn into a different color up to the point where there are junctions with other roads, and that could make it easier to tell which road segments are affected by the smart targets.

**Comment by bastib1205** [comment]
@MicaelJarniac You're picking up my idea [(in](https://github.com/Stephan-S/FS19_AutoDrive/issues/1413) the same way, but more elaborate. If everything were to be implemented in this way, I would be very happy!

**Comment by Iwan1803** [comment]
As discussed in earlier requests like this one: cost/benefit factor is not given.
