### ISSUE TITLE
[FEATURE REQUEST] Quick way to convert single way road to dual way road

### ISSUE THREAD

**Issue by MicaelJarniac** [Stephan-S/FS19_AutoDrive#1384]
On some maps, a road network is already provided with the mod, and that's awesome, but I've encountered some roads that were created as single way ones, and would like to change them to dual way roads.

Currently, we either have to delete it entirely then record our own path using the dual way recording mode (right-click record), or go to each and every single waypoint and assign it the other way as well. Both processes do get the job done, but they also take a bit more effort.

The feature I'm suggesting (and I think I've seen it suggested on another issue but couldn't find it again) is to have an option to select a start and end waypoint, then turn all the network connections between them into dual way connections, or vice-versa.

So it'd work like this, if we have a single way road and want to turn it into a dual way one, we go to the beginning of it, select a point (probably using a special tool for it), then go to the end and select a point there too. The selected route is then highlighted with a different color to make it clear if we have selected the desired road correctly, and if so, we can proceed to tell it to turn every existing single way connection into a dual way one. And if the road is already a dual way road and we want it to be single way only, we can repeat the same process, and it'll cycle between being a single way facing the start, a single way facing the end, and a dual way road.

That'd simplify the process of editing existing routes a whole lot.

**Comment by MicaelJarniac** [comment]
PS. I found the other issue I mentioned, it's #631.

**Comment by Axel32019** [comment]
see Release 1.1.1.4
