### ISSUE TITLE
[FEATURE REQUEST]Use a tractor with trailered harvester as "combine"

### ISSUE THREAD

**Issue by Martinnygaard** [Stephan-S/FS19_AutoDrive#1385]
Im using the Krone Premos5000 from straw harvest to make straw pellets.
Will it be possible to have AD to recognize that kind of attachments as a combine, to use AD unload feature? 
I guess this could also be relevant for trailered beet and potato equipment.

![image](https://user-images.githubusercontent.com/26490587/80140188-e8345d80-85a7-11ea-87d9-0af817d9fb82.png)

**Comment by Iwan1803** [comment]
-> https://github.com/Stephan-S/FS19_AutoDrive/issues/1422
