### ISSUE TITLE
Max Siloabstand/Silorange [QUESTION]

### ISSUE THREAD

**Issue by Moitzbert** [Stephan-S/FS19_AutoDrive#1386]
**Additional context**
Könnte mir jemand die Funktion "maximaler Siloabstand" erklären ? bzw wie man diese einsetzt und von wo weg der Abstand berechnet wird ?

Can someone explain the function "Max Silorange" and how to use it ? 

Tolles Projekt und toller Support!

**Comment by Sp0rTB4cK** [comment]
Hallo,
die Funktion wird hier ganz gut erklärt:

[https://youtu.be/h3mAOe0IJeE?t=589](https://youtu.be/h3mAOe0IJeE?t=589)

**Comment by Iwan1803** [comment]
Max. Siloabstand = Abstand zwischen Trigger/n und Zielpunkt in Metern
Alle Trigger, welche auf der Strecke VOR dem Erreichen des Zielpunktes liegen, werden benutzt (wenn möglich).
Reicht das als Erklärung?
