### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by fischi3016** [Stephan-S/FS19_AutoDrive#1387]
AutoDrive Version: 1.1.0.5 RC2
Release or selbsterstelltes zip: Release
Karte (falls relevant): Alle
Fahrzeug(art) (falls relevant):

**Beschreibe den Bug**
Abfahrer wartet nach Ruf auf wenden drescher/Häcksler.

**Comment by Iwan1803** [comment]
... und sollen wir raten, wo wie was warum?
Wenn du bereit bist, das Template vollständig auszufüllen und mehr Infos zu teilen, dann darfst du gerne ein neues Issue öffnen.
