### ISSUE TITLE
[BUG] Abfahrer wartet das drescher oder Häcksler wendet

### ISSUE THREAD

**Issue by fischi3016** [Stephan-S/FS19_AutoDrive#1388]
AutoDrive Version: 1.1.0.5 RC2
Release or selbsterstelltes zip: AutoDrive master entpackt und neu gezipped
Karte (falls relevant): Alle
Fahrzeug(art) (falls relevant):

**Beschreibe den Bug**
Eine klare Beschreibung des Bugs.

Wenn ich auf meinen Server Abfahrer rufe dann steht immer warten bis drescher oder Häcksler gewendet hat. Erntemaschiene fahre ich selbst

**Comment by Sp0rTB4cK** [comment]
Duplicate of #1309
