### ISSUE TITLE
[FEATURE REQUEST] hightlight folder when moving a targetpoint

### ISSUE THREAD

**Issue by flattergaul** [Stephan-S/FS19_AutoDrive#1389]
Hi,

wenn man Zielpunkte in einen anderen Ordner verschieben möchte, ist es manchmal nicht einfach, den 'richtigen' Ordner zu treffen, wenn der Zielordner nicht gerade aufgeklappt ist.

Wäre es möglich, beim Verschieben den Ordner, über dem sich der Mauszeiger gerade befindet, farblich anders darzustellen?

lg & danke für eure Arbeit 👍

**Comment by Iwan1803** [comment]
Wird im nächsten Release vorhanden sein.
