### ISSUE TITLE
Big M 450 dreht sich im Kreis

### ISSUE THREAD

**Issue by stueja** [Stephan-S/FS19_AutoDrive#139]
Ich habe Kurse eingefahren, die mit den gewöhnlichen Traktoren gut funktionieren. Der Big M 450 dreht sich kurz nach dem Start eines solchen Kurses sehr lange oder ausschließlich im Kreis. Liegt das an der Hecklenkung? Läßt sich das unterbinden?

**Comment by Stephan-S** [comment]
Hey,

ich probiere es demnächst aus. Aber es kann durchaus an der Lenkung liegen.
AutoDrive unterstützt derzeit noch nicht alles Fahrzeugtypen.
Ich nehme es auf die Liste auf, allerdings als Langzeitziel, da ich derzeit noch andere Prioritäten habe.

Viele Grüße,
Stephan

**Comment by stueja** [comment]
Sehr gerne.
Als Workaround kann ich empfehlen, ein von AD unterstütztes Fahrzeug den Kurs fahren zu lassen, und den Big M 450 (oder auch viele Drescher) mit FollowMe folgen zu lassen.
Viele Grüße,
Jan

**Comment by Knowen** [comment]
Also ich hatte gestern Abend mit der aktuelsten Version kein Problem mit einem Case IH 9240 (Hecklenker). Den konnte ich ohne Probleme quer über die Map schicken. 
Vielleicht wurde das Problem schon behoben?
