### ISSUE TITLE
Driver can't reach destination

### ISSUE THREAD

**Issue by Martinnygaard** [Stephan-S/FS19_AutoDrive#1390]
1.1.0.5_RC2
**Map (If applicable):** All  
**Vehicle / Type (If applicable): Vanilla tractor with seeder
**Multiplayer or Singleplayer:** Singleplayer  

**Describe the bug**  
Lately i've seen a lot of "driver can't reach destinations. 
I thought it was my network where maybe a connection was facing the wrong direction or something like that, but:
Today i went looking after that error, and noticed that if i tried to start the driver on a two way connection, it can't calculate the path. Then i drove like 50cm furter ahead (the red arrow from the tractor still points on the same point as before - litterly almost didnt move the tractor) - but now he can calculate the path.

Ant idea why?

![cant reach](https://user-images.githubusercontent.com/26490587/80283557-b393e380-8718-11ea-9d84-f205e31efc6d.png)

**Comment by fischi3016** [comment]
1 point is not connect to the Field.

**Comment by Martinnygaard** [comment]
But how would that make a difference? On the picture it cant reach the field. If i drive 10cm more forward, it works just fine.

It is not even moved to another closest point. Still the same point (just behind the tractor)

**Comment by fischi3016** [comment]
![Screenshot_20200427_105503](https://user-images.githubusercontent.com/63921968/80353399-9aed1000-8875-11ea-9e86-a0db6007f571.jpg)

Try to connect this line new

**Comment by DumpsterDave** [comment]
If the distance between two points is too great, you will get this error.  In these cases, adding an additional point between them to shorten the distance has resolved this error in my experience.

**Comment by Iwan1803** [comment]
Does that help to solve the problem?
Less waypoints are nice, but could cause problems.

**Comment by LS15-17-19Farmer** [comment]
Hallo Martinnygaad und Iwan1803

Habe das gleiche Problem wie Martinnygaad mit Version 1.1.0.5_RC2 das AD Zielpunkte nicht anfahren kann, kommt die gleiche Meldung wie vom Foto.

Habe jetzt mal die FS19_AutoDrive-beta-testing runtergeladen und ausprobiert, und die 1.1.0.5_RC3 funktioniert Wegpunkte und Ziele werden wieder angefahren.
In einem von euren Fixes in der beta testing Version zwischen 25.04.2020 17:52 – 19.05.2020 22:11 ist der Fehler behoben worden 

Also Martinnygaad bitte lade dir mal die Beta testing 1.1.0.5_RC3 un Probier es nochmal aus, bei mir ging dann alles wieder.

Gruß
LS15-17-19Farmer

Hello Martinnygaad and Iwan1803

If the same problem as Martinnygaad with version 1.1.0.5_RC2 cannot reach the AD target points, the same message comes as from the photo.

Have now downloaded the FS19_AutoDrive-beta-testing and tried it, and the 1.1.0.5_RC3 works waypoints and targets are approached again.
The bug was fixed in one of your fixes in the beta testing version between April 25th, 2020 05:52 pm - May 19th, 2020 10:11 pm

So Martinnygaad please download the beta testing 1.1.0.5_RC3 and try again, with me everything went fine.

greeting
LS15-17-19 Farmer

**Comment by mertchri** [comment]
1.1.0.5_RC3
Map (If applicable): HOF 2020
**Vehicle / Type (If applicable): habe mehrere, auch Standart probiert, bei allen das Gleiche
Multiplayer or Singleplayer: Singleplayer

Describe the bug: 
Ich habe das gleiche Problem mit der Version 1.1.05_RC3. Die Kurse wurden mit der 1.1.05_RC2 eingefahren und die ZIP-Datei dann auf RC3 geupdatet. Bei RC2 funktionierten die Kurse ohne Probleme, jetzt leider sporadisch nicht immer. Ich habe mal probiert den Punkt zu finden ab dem es nicht mehr geht, es ist aber soweit alles in Ordnung wie gesagt bei RC2 funktionierte der Kurs auch. Es kommt jetzt erst die Meldung "Der Fahrer von ... hat keinen Weg gefunden zu ...", dann dauert es etwas und dann kommt die Meldung "Der Fahrer von ... ist angekommen bei ..." obwohl der Zielpunkt noch weit entfernt ist. Bilder davon sind im Anhang. 

I have the same problem with version 1.1.05_RC3. The courses were brought in with 1.1.05_RC2 and the ZIP file was then updated to RC3. With RC2 the courses worked without problems, now with the RC3 unfortunately not always sporadically. I once tried to find the point from which it was no longer possible, but as far as everything was ok, as I said with RC2, the course also worked. Now the message "The driver from ... has not found a way to ...", then it takes some time and then the message "The driver from ... has arrived at ..." although the destination is still there is far away. Pictures of it are attached.
![Screenshot_5](https://user-images.githubusercontent.com/48655908/84547027-f169bd00-ad02-11ea-87b3-ce46b8f93994.jpg)
![Screenshot_1](https://user-images.githubusercontent.com/48655908/84547046-fa5a8e80-ad02-11ea-9e0a-6680f4db9f81.jpg)

**Comment by Iwan1803** [comment]
Wenn ich diese ganzen blauen Linien sehe.... 🙄
Ja, ich weiß, an engen Stellen geht es wohl nicht anders und dafür sind die blauen Linien ja auch gedacht, aber auf manchen Screenshots sieht es einfach nur gruselig aus und man hätte das bestimmt "optimaler" lösen können.
Aus eigener Erfahrung weiß ich, das es verdammt viel Zeit kostet, die ganzen Strecken aufzuzeichnen, aber wenn man die schon aufwendet, dann sollten die Strecken auch logisch aufgebaut sein und nicht so wirken, als ob da jemand 2-3 Linien einsparen wollte und dafür ein paar blaue "hingeklatscht" hat.
Die Wegfindung in RC3 ist eine andere als in RC2 und wer Probleme hat, sollte erstmal auf die RC2 zurückgehen. Mit RC4 werden einige Optimierungen kommen.

**Comment by mertchri** [comment]
Wie wäre es denn optimal und zukunftssicher? Für jeden Weg und jede Abbiegung einen Kurs einfahren und die blauen Linien am Besten ganz weg lassen? Ich habe jedenfalls das Gefühl, als würden die blauen Linien die Probleme verursachen, warum auch immer. Habe jetzt auf meiner Strecke alle Verbindungen zu blauen Linien gekappt und es funktioniert. Scheinbar kommt das Pathfinding mit den blauen Linien irgendwie nicht mehr klar. Das soll hier wirklich kein Nörgeln oder Meckern sein, es ist nur ärgerlich wenn man stundenlang Kurse eingefahren hat und diese in der RC2 auch problemlos liefen und jetzt alle Kurse geändert werden müssen und bei der RC4 evtl dann wieder geändert werden müssen, daher die Frage nach der optimalsten Lösung. Ich habe die RC3 geladen, da ich viel Gras häckseln möchte und dies jetzt mit der RC3 problemlos funktioniert bis auf eben das Pathfinding.

**Comment by Iwan1803** [comment]
Wie oben bereits geschrieben:
"Die Wegfindung in RC3 ist eine andere als in RC2 und wer Probleme hat, sollte erstmal auf die RC2 zurückgehen."
Die RC4 wird aber nicht mehr lange auf sich warten lassen, so das man jetzt nicht unbedingt alles neu zeichnen sollten.
Generell würde ich aber auf all zu komplexe blaue Strecken verzichten. Auf dem Screenshot sind ja 3 blaue Linien in verschiedene Richtungen miteinander verbunden und evtl. führt das zu den Problemen.

**Comment by Iwan1803** [comment]
_Please download 1.1.05.-RC4, try again and then post a feedback._
Bitte lade 1.1.05.-RC4 herunter, versuch es erneut und poste dann ein Feedback.

Changelog: https://github.com/Stephan-S/FS19_AutoDrive/wiki/Release-Notes

**Comment by mertchri** [comment]
Hi @Iwan1803 habe die RC4 jetzt 3h getestet, es läuft wieder alles wunderbar, Autodrive findet wieder alle Ziele und es klappt bisher alles (Häckselbetrieb mit 3 Abfahrern) 
Vielen Dank nochmal an euch, dass ihr die Fehler und Bug's so schnell behebt. Riesen Lob und großartige Leistung! Macht weiter so!
