### ISSUE TITLE
[FEATURE REQUEST] Streamline with Courseplay, controls

### ISSUE THREAD

**Issue by angulion** [Stephan-S/FS19_AutoDrive#1391]
It would be very nice if autodrive could adopt controls closer to courseplay.
Proposals for change:
- change middle-click to right-click like in Courseplay to release cursor (additionally helps Mac users w/o middle button on laptop)
-  change alt-0 to either control-0 (which I believe GPS uses) or preferably control-End, which would be next to Courseplays ctrl-Del.
Alternatively in settings a way to change control style between "default" and "courseplay-style".

**Comment by MicaelJarniac** [comment]
I agree that it's very odd having to pop up the cursor in two different ways to control each mod, but changing it to right-click I'm not sure if is a good idea, as right-click is actually already used by AutoDrive to perform a few actions on the HUD, like switching backwards in the modes and to start recording a dual way route in the record button.

But maybe it wouldn't conflict, not quite sure. I know that Courseplay conflicts with that, like if I have only AD showing, and I want to start recording a dual way route, for example, it opens Courseplay, and then if it's already open, my cursor disappears when trying to use those functions on AD, so I have to always change Courseplay to use CTRL+DEL to prevent this conflict.

What is the strangest thing IMO is that if you pop up your cursor with CP (right-click, for example), AD detects it and allows you to click AD HUD as well, even though you used CP's shortcut for the cursor, but not the other way around, so if you middle-click to use the cursor in AD, it only works in AD.

Having both share the same cursor key would be very handy, meaning less key assignments and quicker access to both.

**Comment by Iwan1803** [comment]
A lot of mods are using the equal key bindings and that is causing problems.
For all the mods we need >500 keys and dozen of mouse buttons 😂

If CP reserves the right mouse click, that's not a problem of AD.
