### ISSUE TITLE
Radladerfunktion - ist die noch vorhanden?

### ISSUE THREAD

**Issue by kleba78** [Stephan-S/FS19_AutoDrive#1393]
AutoDrive Version: 1.1.0.4
Release or selbsterstelltes zip: Release
Karte (falls relevant): Alle
Fahrzeug(art) (falls relevant):

**Beschreibe den Bug**
Gibt es den Radladermodus noch? Bekomme ihn nicht mehr aktiviert, habe ihn bisher auch noch nicht selber gesehen, hab allerdings diverse youtube videos gesehen die ihn beschreiben.

Hab es mit normalen StandardRadladermodellen und Schaufeln getestet

**Falls anwendbar - Schritte mit denen ich den Bug nachstellen kann**

**Screenshots**
Falls relevant, bitte Screenshots beifügen

**Comment by Iwan1803** [comment]
Der Modus wurde deaktiviert, da er nicht so gut funktioniert hat wie er sollte.

**Comment by kleba78** [comment]
Seht ihr noch eine Chance das er zurückkehrt? Die Idee dahinter, war ja wirklich sehr erstrebenswert. Gruss

**Comment by Iwan1803** [comment]
Ja, ist angedacht, aber hat aktuell keine Priorität.

**Comment by Alkoholix** [comment]
Wenn Du den Radladermodus wieder haben willst, musst Du zurück zu Version 1.0.7.2

Ich bin deswegen erstmal bei der genannten Version geblieben, da ich mit dem Radladermodus meine Biogasanlage automatisch füttere.
