### ISSUE TITLE
[BUG] Error XML.lua:280: invalid value (nil) at index 1 in table for 'concat'

### ISSUE THREAD

**Issue by bastib1205** [Stephan-S/FS19_AutoDrive#1394]
AutoDrive Version: 1.1.0.4
Release or selbsterstelltes zip: Release
Karte (falls relevant): GreenRiver 2019
Fahrzeug(art) (falls relevant):

**Beschreibe den Bug**
Wenn ich Kurse einfahre bzw. erstelle und das Spiel nach einiger Zeit speichere, wird keine *.xml Datei im Savegame-Ordner erstellt. Wenn ich schließlich das Spiel schließe und erneut lade, ist alles weg.
Der Fehler fiel mir erstmals im Multiplayer auf. 

**Falls anwendbar - Schritte mit denen ich den Bug nachstellen kann**
Neuer Spielstand mit der oben genannten Map wird erstellt.
Mit einem Fahrzeug wird ein Kurs eingefahren, der auch funktioniert.
Spiel wird gespeichert (manuell, keine autosave).
Im Savegame-Ordner befindet sich keine Autodrive-XML-Datei.
Trotzdem funktionieren die Kurse einwandfrei.
Nach einem Neustart des Spiels sind schließlich alle Kurse weg.
 

Der Fehler, der mit in der log.txt angezeigt wird, lautet:

(Modordner-Pfad)/FS19_AutoDrive.zip/scripts/XML.lua:280: invalid value (nil) at index 1 in table for 'concat'

Dieser Fehler erscheint in der log.txt nach jedem Spiel-Speichern mindestens 3x sofort nacheinander. Manchmal öfter.

**Comment by Iwan1803** [comment]
Versuch es mal mit dem letzten Release Candidate 1.1.0.5-RC2.

**Comment by bastib1205** [comment]
Herzlichen dank für die schnelle Hilfe. Jedoch hat sie leider nicht den gewünschten Erfolg erzielt:
Soeben habe ich auf die aktualisierte Version (1.1.0.5-RC2) geupdatet, doch leider tritt der Fehler nahezu unverändert auf.
Ich habe soeben nur einen Spielstand mit einer bestehenden xml-Datei mit Wegpunkten geladen. Nachdem ich einen Punkt nur minimal verschoben habe und das Spiel anschließend gespeichert habe, trat der bekannte Fehler direkt vor der Zeile 
"Game saved successfully."
erneut auf. Diesmal aber nur einmal. Die xml-Datei inklusive aller Wegpunkte wurde gelöscht.

[Modordner]/mods/FS19_AutoDrive/scripts/XML.lua:281: invalid value (nil) at index 1 in table for 'concat'

**Comment by Iwan1803** [comment]
Besteht das Problem noch und ist zufällig VCA im Einsatz?

**Comment by bastib1205** [comment]
Das Problem besteht seit dem ich in der 1.1.0.5-RC2 die Kurse komplett neu eingefahren habe, nicht mehr, VCA hatte ich allerdings noch nie installiert

Ich vermute, dass ich bei dem Erstellen meiner Kurse eine unplausible Kombination in einer Routen übersehen habe.

Nun funktioniert alles einwandfrei.

**Comment by Iwan1803** [comment]
Super, dann mach ich hier mal zu 😉
