### ISSUE TITLE
Abfahrer fährt in Frucht und kollidiert mit Drescher / tractor crashes with combine harvester

### ISSUE THREAD

**Issue by MacMoore** [Stephan-S/FS19_AutoDrive#1395]
AutoDrive Version: 1.1.0.5-RC2
Release or selbsterstelltes zip: Release Candidate
Fahrzeug(art) (falls relevant):
Karte: NF Marsch 4fach ohne Gräben, kommt auf anderen Maps auch vor.

**Beschreibe den Bug**
Drescher ruft Abfahrer (bei 80%); Abfahrer fährt von vorne auf den Drescher zu, fährt halb in der Frucht und kollidiert letzendlich mit dem Drescher. 
Es gibt keinerlei Anzeichen das der Abfahrer dem Drescher ausweichen würde.
Dies geschieht eigentlich recht häufig wenn der Abfahrer, in einer geraden Linie, von vorne zum Drescher fährt.

**Falls anwendbar - Schritte mit denen ich den Bug nachstellen kann**

**Screenshots**
![fsScreen_2020_04_28_07_38_10](https://user-images.githubusercontent.com/55612461/80453806-47d49500-8929-11ea-9749-82626269cb30.jpg)
![fsScreen_2020_04_28_07_38_17](https://user-images.githubusercontent.com/55612461/80453824-4f943980-8929-11ea-90e4-3ba02af7bf10.jpg)

**Comment by MacMoore** [comment]
Habe nochmal gestestet wie sich der Abfahrer nach dem Ruf verhält. Drescher fährt mit CP.

Er fährt ganz normal neben der Frucht los und bleibt auch ein Stück weit auf dieser Spur:
![fsScreen_2020_04_28_09_34_04](https://user-images.githubusercontent.com/55612461/80461129-1bbf1100-8935-11ea-8f74-c59852ffcfc5.jpg)
Er schwenkt dann in die Frucht:
![fsScreen_2020_04_28_09_34_26](https://user-images.githubusercontent.com/55612461/80461179-2d081d80-8935-11ea-827b-6fd690e46e23.jpg)
Fährt in der Frucht weiter:
![fsScreen_2020_04_28_09_34_39](https://user-images.githubusercontent.com/55612461/80461214-398c7600-8935-11ea-9013-93de4103023a.jpg)
Bis er dann beim Drescher ansteht bzw kollidiert:
![fsScreen_2020_04_28_09_34_58](https://user-images.githubusercontent.com/55612461/80461255-48732880-8935-11ea-9551-d3953a0e12a6.jpg)
Im HUD steht jetzt sogar "Frucht verlassen" aber dazu ist es zu spät bzw. kein Platz mehr. 
Kann sein dass er das Aufgrund des ausgefahrenen Entladerohrs machen möchte. 
Das Rohr wurde genau zum Zeitpunkt der Kollisiion ausgefahren.

Mit AD V1.1.0.4 läßt sich bei mir die NF Marsch 4fach ohne Gräben V1.7 nicht mal starten, darum die V1.1.0.5

**Comment by rmn18** [comment]
Auf für einen Abstand haste denn den Abfahrer eingestellt ?? Wenn der Abfahrer im Minusbereich liegt ist das logisch das er zu nah zum Drescher kommt ,kuck mal in den Einstellungen von AD nach ,hab meine auf 0,75m  ,bei -0,75m wäre das fatal .

**Comment by MacMoore** [comment]
Abfahrer steht definitiv auf 0,7m.
Drescher fuhr vorher schon 2 Vorgewende und Rohrabstand paßte und mit AD V1.1.0.5 muß ich bei jedem Neustart des Spiels die Fahrzeugspezifischen Einstellung in Autodrive neu einstellen, die werden bei mir nämlch nicht gespeichert. Und beim Start steht der Abstand auf -0,65m.
Glaube nicht das dieses Nichtspeichern bei einer Developer Version normal ist.
Aber gut, eines nach dem anderen.

**Comment by Iwan1803** [comment]
Von 1.1.0.5-RC2 ist nicht bekannt, das Einstellungen nicht gespeichert werden. Vielleicht solltest du hier erstmal ansetzen, denn da passt ja scheinbar was bei dir nicht.
Du spielst nicht zufällig auf einem Dedi-Server?

**Comment by MacMoore** [comment]
Kein Dedi-Server, Singleplayer ganz normal am PC.
Ich häng mal die log an vom Zeitpunkt wo das mit dem Abfahrer war. 
Das nicht speichern ist schon seit dem ersten Versuch mit 1.1.0.5
[log.txt](https://github.com/Stephan-S/FS19_AutoDrive/files/4546676/log.txt)

**Comment by TobiHH78** [comment]
Es scheint, als hättest du zwei Versionen von AutoDrive im Modordner??

Load mod: FS19_AutoDrive (Version: 1.0.7.1) (Hash: 7c5d5ab70e3f235f7389a2b2057fd3e5)
Load mod: FS19_AutoDrive_beta (Version: 1.1.0.5) (Hash: bb0c7756fd05da969f110958acdd7003)

**Comment by MacMoore** [comment]
Richtig, zu dem Zeitpunkt waren beide Versionen im Modordner, 1071 war deaktiviert,1105 war aktiviert.
Hab dann die 1071 aus dem Ordner entfernt, ergab aber keinerlei Änderung, weder beim Abfahrer noch beim Speichern der Einstellungen.
Werde jetzt mal alles aus dem Modordner entfernen, ein neues Savegame beginnen und einen Mod nach dem anderen wieder einfügen, mal sehen ob das etwas bringt.

**Comment by fischi3016** [comment]
ist der drescher nicht eine Mod?

**Comment by Iwan1803** [comment]
Wie ist denn der Stand der Dinge?

**Comment by Iwan1803** [comment]
Bitte 1.1.0.5-RC3 ausprobieren. Sollte das Problem dann noch bestehen, einfach ein neues Issue aufmachen.
