### ISSUE TITLE
1104 wont load with CP but 1105 will.

### ISSUE THREAD

**Issue by kwguk** [Stephan-S/FS19_AutoDrive#1396]
**AutoDrive Version:** 1.1.0.4?1.1.0.5RC
**Release or Custom Zip:** Release  
**Map (If applicable):** Eiersholt 
**Vehicle / Type (If applicable):**   
**Multiplayer or Singleplayer:** Singleplayer  

I dont know if its a bug or not
[log.txt](https://github.com/Stephan-S/FS19_AutoDrive/files/4544883/log.txt)

Ive tried using 1104 but the game wont load when CP is in the mod file. However when i have 1105RC in my mod file with CP the game loads with no problem. Im using CP ver.397

**Comment by Iwan1803** [comment]
You can't downgrade vom 1.1.0.5-RC2 to 1.1.0.4, if you recorded drive back routes.
As CP & AD exist in newer versions, i'll close here.
