### ISSUE TITLE
[BUG] Can't toggle UI On or Off on John Deere  CP690 Cotton Harvester

### ISSUE THREAD

**Issue by RIONDRON** [Stephan-S/FS19_AutoDrive#1397]
**AutoDrive Version:** 1.1.0.4 and 1.1.0.5 - RC2
**Release or Custom Zip:** Release  
**Map (If applicable):** All  
**Vehicle / Type (If applicable):**   John Deere CP690 Cotton Harvester from the official Cotton Addon DLC
**Multiplayer or Singleplayer:** Singleplayer  

**Describe the bug**  
At the initial purchase of the vehicle, the UI is visible, but there is no key option to toggle UI on\off. If the UI is closed, it cannot be brought back up again. After saving and restarting game, the UI is gone and cannot be brought up, and still no option\way to toggle UI. The behavior happens on any map, with any mod combination, including Only having AutoDrive and Cotton Addon turned on.

**If applicable - Steps to reproduce the behavior**  
Buy the harvester, NO option to toggle on\off. Close the AutoDrive UI, still no option.
Save and reload, AD UI is missing, and cannot toggle on\off.

**Screenshots**  
![fsScreen_2020_04_28_12_10_55](https://user-images.githubusercontent.com/64487723/80512078-fb01b600-894a-11ea-8d00-aaa6b402b088.png)
![fsScreen_2020_04_28_12_11_33](https://user-images.githubusercontent.com/64487723/80512114-0523b480-894b-11ea-8919-afce80f5ad15.png)

**Comment by Axel32019** [comment]
Did you try ALT + Numpad 0 (zero)?
https://github.com/Stephan-S/FS19_AutoDrive/wiki/Buttons-with-short-description

**Comment by RIONDRON** [comment]
Yes, on several different maps, bot with and without other mods in the folder. As you can see in the pics, ALT NUM 0 isn't even highlighted as an option in the F1 help pane.

**Comment by Axel32019** [comment]
Did you change the key-binding? Please attache the log file.

**Comment by RIONDRON** [comment]
I have never changed any keybinds in this game. The attached pics and logs are on a fresh save of Ravenport original game map, with only the Cotton Addon and AutoDrive. The 'Toggle UI' works on all vehicles Except the JD CP690.
[log (2).zip](https://github.com/Stephan-S/FS19_AutoDrive/files/4547936/log.2.zip)
![fsScreen_2020_04_28_14_48_35](https://user-images.githubusercontent.com/64487723/80526494-d4e71080-8960-11ea-9022-ae42aa30bf35.png)
![fsScreen_2020_04_28_14_39_38](https://user-images.githubusercontent.com/64487723/80526504-d7e20100-8960-11ea-968a-66327879cde6.png)
![fsScreen_2020_04_28_14_39_36](https://user-images.githubusercontent.com/64487723/80526509-d9abc480-8960-11ea-9ceb-3d42e4841749.png)
![fsScreen_2020_04_28_14_39_35](https://user-images.githubusercontent.com/64487723/80526512-dadcf180-8960-11ea-9ef5-b3820340f1ca.png)
![fsScreen_2020_04_28_14_39_33](https://user-images.githubusercontent.com/64487723/80526518-dca6b500-8960-11ea-918b-4d0264ebe2e2.png)

**Comment by Axel32019** [comment]
Hm, then I only can suggest to assign a new key combination. May be the standard AD key binding is used / blocked by your DLC. I do not have the Cotton DLC, so I cannot look into it furthermore - Sorry.

**Comment by RIONDRON** [comment]
So.....after taking a break, re-adding all my mods back into the mod folder, and launching the game....It's now working! Didn't change any key binds, didn't update\add\remove\alter anything, and now it is suddenly working. I have absolutely no clue whatsoever of what happened. If I have any other problems with this, I'll return with any new info to add.

**Comment by Axel32019** [comment]
From my understanding this not an issue from AD - please close the issue.
