### ISSUE TITLE
[BUG] Cann't use the .xml configuration file

### ISSUE THREAD

**Issue by MrMatttw** [Stephan-S/FS19_AutoDrive#1399]
**AutoDrive Version:** 1.1.0.4   
**Release or Custom Zip: Release  
**Map (If applicable): AutoDrive_Ravenport_init_config
**Vehicle / Type (If applicable):**   
**Multiplayer or Singleplayer:** Singleplayer  

**Describe the bug**  
Couldn't open the AutoDrive_Ravenport_init_config.xml file in the compressed file. Both the mod and the AD.

I moved the .xml file into the savegame folder but nothing happened. Later I tried to change the content of the xml file in savedgame, but also didn't work
**If applicable - Steps to reproduce the behavior**  

**Screenshots**

**Comment by Iwan1803** [comment]
If you start a new game on Ravenport and activate AD, save the game once and then quit.
The XML will be "copied" automatically to the savegame folder.
There is no need to unzip them.

**Comment by Iwan1803** [comment]
No feedback -> closed.
