### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by Williwillswisse** [Stephan-S/FS19_AutoDrive#14]
Hallo Stephan,
wäre es möglich die Geschwindigkeit für jedes Fahrzeug in den vehicle.xml abzuspeichern?
In der letzten Version ist diese auf 60 voreingestellt. Bei der Geschwindigkeit fliegen meine Fahrzeuge auf kleinen Straßen von der Piste ;-). Ich habe in der .lua jetzt erst mal 40 eingestellt. Schöner wäre es wenn für jedes Fahrzeug der eigene Wert abgespeichert werden könnte.
Mit deiner letzten Version hier von Github habe ich auch ein paar Probleme im Zusammenhang mit dem Vehicle Control Addon. Dort kann bei den Fahrzeugen dann nicht immer mit der Leertaste die Fahrtrichtung umgestellt werden (Shuttle Control)

Aber sonst schon echt genial: Modhub geschaft, wieder Pfeile :-) und dazu die Berechnung der Routen im Hintergrund und das noch Lichtjahre schneller als im FS17.

Vielen Dank dafür.

**Comment by Stephan-S** [comment]
Also als schnellen Fix könnte ich sie zumindest global abspeichern. Das heißt der letzte eingestellte Wert würde beim Neustart als Standard für alle Fahrzeuge gelten. Pro Fahrzeug wird es wieder etwas aufwendiger. Aber vielleicht sollte ich auch generell lieber wieder auf 50 zurückschrauben. Ich überlege wie ich es am sinnvollsten umsetze. Danke für dein Feedback auch schon am Anfang der Entwicklung!

**Comment by Williwillswisse** [comment]
Wäre es sonst erst mal möglich den Wert in die config.xml zu schreiben? Dann wäre er schon mal für jede Karte getrennt gespeichert.
