### ISSUE TITLE
Tractor does not always find combine

### ISSUE THREAD

**Issue by aviator64** [Stephan-S/FS19_AutoDrive#140]
In unload combine mode - when working one field, the tractor unloaded the combine twice OK, but the third time they were at opposite corners of a large field and the tractor did not detect that the combine needed to be unloaded. I guess the distance was a factor? Tractor was parked inside the field.

**Comment by Stephan-S** [comment]
Hey,
the combine should call drivers in range (300m) if the setting is set in the options menu and if the distances are bigger, you should set the same destination in the AD HUD for the combine and the driver (first row).
If the field is very large and there is a lot of fruit in the path, then the pathfinding algorithm may time out and this should be noted in the log.txt and the Autodrive mod in the tractor should switch off.

Have you selected the destination in the combine?

**Comment by aviator64** [comment]
No, the combine is running with Courseplay. I will try that though next time that same field is ready to harvest. Is there a doc file somewhere that I should be reading? Didn't find anything on here. Thanks!

**Comment by Stephan-S** [comment]
No, no doc file. Just my tutorial video on it:
https://www.youtube.com/watch?v=uOO4tBcBKAs&t=1s

**Comment by aviator64** [comment]
That was helpful, thanks. Maybe put a link to the videos in your readme file?
