### ISSUE TITLE
[BUG] Collision detection prevents skid steer loader when 

### ISSUE THREAD

**Issue by kezarjg** [Stephan-S/FS19_AutoDrive#1400]
**AutoDrive Version:** 1.1.0.5 RC2   
**Release or Custom Zip:** Release  
**Vehicle / Type (If applicable):**   New Holland C232 with Bale Spear
**Multiplayer or Singleplayer:** Singleplayer  

**Describe the bug**  
When the vehicle has a bale loaded and "Collision detection" is on, the vehicle does not auto drive. When "Collision detection" is off, the vehicle drives as expected.

**Comment by Iwan1803** [comment]
The bale has a collision mask. It also happens with some pallets.
Maybe it will be solved in the future...

**Comment by Iwan1803** [comment]
_Please download 1.1.05.-RC4, try again and then post a feedback._
Bitte lade 1.1.05.-RC4 herunter, versuch es erneut und poste dann ein Feedback.

Changelog: https://github.com/Stephan-S/FS19_AutoDrive/wiki/Release-Notes
