### ISSUE TITLE
Manure Refill [BUG]

### ISSUE THREAD

**Issue by patch110** [Stephan-S/FS19_AutoDrive#1401]
**AutoDrive Version:** 1.1.0.5 rc2   
**Release or Custom Zip:** Release  
**Map (If applicable):** Lakeland Vale by Stevie 
**Vehicle / Type (If applicable):  Massey Ferguson 8727 - Begmann TSW 6240 W from the Giants Modhub
**Multiplayer or Singleplayer:** Singleplayer  

**Describe the bug**  
Basically the above setup wont return to field after refilling with manure. ( I get a message saying driver cant find a route to field) even though if i switch the mode to Drive he will then return to field. This is using courseplay for the fieldwork. In the picture the driver would take the route to the immediate left to return to the field 22.  

**If applicable - Steps to reproduce the behavior**Load Manure from the Cow Zone using the Grimme SL 80-22 Quantam
![fsScreen_2020_04_30_02_05_07](https://user-images.githubusercontent.com/32200890/80662048-3eae0a00-8a88-11ea-9ea9-6fe0a256d1ad.jpg)

**Screenshots**

**Comment by Iwan1803** [comment]
Any error in the network?
Which way should the vehicle use? If it should drive on the blue line, please add some more waypoints between the target point and the blue line.

**Comment by patch110** [comment]
I believe it was an issue where he was to close to waypoint marked Cows Manure/Slurry Load. The vehicle should of taken the route closest to the white pickup.

**Comment by Iwan1803** [comment]
So the problem is gone?

**Comment by Axel32019** [comment]
User sees no issue anymore -> closed
