### ISSUE TITLE
Thank for new Feature-Reverse Driving

### ISSUE THREAD

**Issue by betrox007** [Stephan-S/FS19_AutoDrive#1403]
Hello. all the developer team of auto drive, i have try new feature from candidate release and its look working good so far for me.

so this is actually not a bug report but i just want to say tanks for the effort and hard work to develop this mod, till now release new feature reverse driving.
for its its work fine for me,especially when collaborating this feature with courseplay compact mode,its work almost perfect..
great achievement, big appreciated for your hard work

video of my try in here https://youtu.be/M-lnK5z73Mc
sorry for my bad English

**Comment by Iwan1803** [comment]
😎
