### ISSUE TITLE
[FEATURE REQUEST] Copy / Paste Button in AD HUD.

### ISSUE THREAD

**Issue by Opa-Andre** [Stephan-S/FS19_AutoDrive#1404]
Problemstellung:
Ich benutze oft mehrere Fahrzeuggespanne, welche gemeinsam zu einem Zeitpunkt die gleiche Arbeit erledigen sollen. Zum Beispiel mehrere Abfahrer bei großen Feldern, vor allem bei Erdfrüchten, welche hohe Liter-Erträge bei der Ernte erzeugen. Oder bei Transportaufgaben, um Produktionen mit viel Rohstoffkapazitäten ausreichend zu befüllen / entleeren.

Für diese Tätigkeiten müssen dann die Fahrzeuggespanne "gleich" konfiguriert werden. Dazu zählen alle Einstellungen, welche für die benötigte Tätigkeit gleich sind. Das sind grundlegend: "Zielpunkte (z. Bsp. Abhol- und Lieferziele), zu transportierendes Gut (filltype), aber bei Abfahrern beispielsweise auch die Einstellung der Rohrposition vom Drescher, welche z. Bsp. je nach verwendeten Drescher mal "0.25" - bei Getreidedreschern, oder auch "0.75" bei Rübenerntern sein kann. Oder auch weitere fahrzeugspezifischen Einstellungen, wie z. Bsp. die für die Aufgabe Feldausfahrt (Standard, Hinterm Start, Nächstgelegen) sowie, ob die Abfahrer während des Abtankens das Feld verlassen dürfen oder nicht. Also im Grunde genommen alle Ziel-spezifischen und Fahrzeugspezifischen Einstellungen.

Je nach zu erledigender Tätigkeit, sind hier also pro Fahrzeuggespann jeweils eine Menge Konfigurationseinstellungen vorzunehmen. Daher würde sich in diesem Falle eine Copy / Paste Funktionalität anbieten, die wie folgt funktionieren könnte:

Für die geplante Tätigkeit konfiguriert man sich ein Fahrzeuggespann passend zu den Anforderungen. Nun klickt man mit der rechten Maustaste den Copy-Paste Button an. Dadurch wird das Gespann bzw. dessen Einstellungen als "Mastervorlage" definiert. Wechselt man nun zu einem anderen Fahrzeug (-Gespann), dann klickt man nun mit der linken Maustaste auf den Copy / Paste Button. Dabei werden sämtliche ziel- und fahrzeugspezifischen Einstellungen vom Master auf das aktuelle Fahrzeug übertragen. 

Die Mastervorlage (Einstellungen) bleibt solange erhalten, bis man diese wieder durch eine neue Konfiguration (andere Einstellungen) mit einer neuen Vorlage überschreibt. 
Zum Zeitpunkt "Spielstart" oder neues Spiel, bei welchem noch keine Mastervorlage existiert, nimmt AD Standardeinstellungen an, wie sie bisher auch bei neuen Spielen vorhanden sind.

Als Button könnte man sich symbolisch wie üblich zwei übereinanderliegende Papierblätter vorstellen (wie bei anderen Computer Copy Buttons) oder "LS spezifisch" anstelle von zwei Papierblättern auch zwei schematisch übereinanderliegende Traktoren / Fahrzeuge...

**Comment by SledgeHammer75** [comment]
Alternativ könnte ich mir auch gut die Einführung einer "Jobliste" vorstellen. Job speichern nach Konfiguration beim ersten Abfahrer, bei allen anderen nur noch Job laden.

**Comment by Opa-Andre** [comment]
Theoretisch schon - nur wird das ganze bei einer Jobliste m. Erachtens nach ziemlich schnell unübersichtlich. Mal als Beispiel 50 Felder... auf denen kannst Du dann, sagen wir mal 20 verschiedene Früchte haben - um da jede "Jobkonfig" abzulegen, hast Du schon mal theoretisch 1000 Jobs, wo du dann im Nachhinein durch die Liste scrollen musst, um den richtigen wiederzufinden. Da man ein Fahrzeug eh entsprechend der aktuellen Bedingungen im Menü passend konfiguriert, bist du mittels Copy/Paste wesentlich schneller... und brauchst Dich nicht um die Verwaltung von Listen zu kümmern. Wäre wahrscheinlich auch weniger Aufwand für das AD Team - aber das kann ich nicht beurteilen.  Aber warten wir mal ab, was Stefan und seine Mitstreiter dazu für eine Meinung haben - vielleicht kommt ja auch gar nichts, da Aufwand zu groß.

**Comment by Iwan1803** [comment]
Die Idee ist nice, aber vermutlich sehr aufwändig umzusetzen.

**Comment by Iwan1803** [comment]
Sehr aufwändig, da Konsistenzen geprüft werden müssten - egal ob per Copy&Paste oder einer Jobliste.
