### ISSUE TITLE
[BUG]Abfahrer kollidiert mit Drescher/tractor collidates with harvester

### ISSUE THREAD

**Issue by HerrchenChris** [Stephan-S/FS19_AutoDrive#1405]
AutoDrive Version: 1.1.0.5-RC2
Release or selbsterstelltes zip: Release
Karte (falls relevant): Oberthal
Fahrzeug(art) (falls relevant): 

**Beschreibe den Bug**
Ich habe öfters das Problem, dass die Abfahrer frontal auf den Drescher zuhalten, wenn diese gerufen werden. Als Resultat steht der volle Mähdrescher im Feld und wartet auf seinen Abfahrer, der aber nicht weiter kommt, weil er vor dem Drescher steht (siehe Screenshot). 
Die Feldgeschwindigkeit habe ich nach dem Screenshot dann auch noch mal runter geschraubt, aber das brachte auch keine Verbesserung. Das Problem tritt allerdings nicht immer auf, oft funktioniert es auch, dass die Drescher abgeladen werden.

**Falls anwendbar - Schritte mit denen ich den Bug nachstellen kann**
Ich bin mir nicht sicher, aber ich meine, dass Problem entsteht dann, wenn der Abfahrer von vor dem Drescher gerufen wird.

**Screenshots**
![20200505090025_1](https://user-images.githubusercontent.com/52828429/81046864-8930eb80-8eb9-11ea-8ba7-45a571362dca.jpg)

**Comment by OnkelH0tte** [comment]
Das gleich Problem habe ich auch. Gleiche Version, andere Map Multimap. Sowohl Traktor als auch LKW.

**Comment by Iwan1803** [comment]
Das Problem passiert, wenn der Drescher per CP in diese Ausweichposition fährt, damit das Rohr nicht in der Frucht ist.
Da es eher selten auftritt, hat es erstmal keine Prio.

**Comment by Iwan1803** [comment]
_Please download 1.1.05.-RC4, try again and then post a feedback._
Bitte lade 1.1.05.-RC4 herunter, versuch es erneut und poste dann ein Feedback.

Changelog: https://github.com/Stephan-S/FS19_AutoDrive/wiki/Release-Notes

**Comment by Iwan1803** [comment]
-> https://github.com/Stephan-S/FS19_AutoDrive/issues/1479

**Comment by Iwan1803** [comment]
Please update to 1.1.0.5-RC5, try again and if the problem still exists, then open a new issue.
*Bitte aktualisiere auf 1.1.0.5-RC5, versuche es erneut und und wenn das Problem weiterhin besteht, erstelle ein neues Issue.*
