### ISSUE TITLE
[BUG] Sprayer with extra tank not being refilled

### ISSUE THREAD

**Issue by aviator64** [Stephan-S/FS19_AutoDrive#1406]
**AutoDrive Version:** 1.1.0.4   
**Vehicle / Type (If applicable):**   Amazone FT1001, Amazone UX5200
**Multiplayer or Singleplayer:** Singleplayer  

Towed crop sprayer, plus auxiliary tank on tractor's front hitch.
When passing a refill trigger (herbicide or liquid fertilizer) the auxiliary tank is refilled but the main sprayer is not.

**Comment by Iwan1803** [comment]
Additional attachments like extra tanks are not supported. 
Maybe in the future...

**Comment by iljarogoff** [comment]
CP seems to support it now, maybe you can import their code to AD?

**Comment by Axel32019** [comment]
Have you tested with 1.1.0.5-RC5 already?
In my games it is working with this version.

**Comment by iljarogoff** [comment]
yes, tested but not working with deltis 2 and kuhn pf1500. not refilling the front tank

**Comment by Axel32019** [comment]
Hello @iljarogoff ,
Is this issue still present in the lateste Release version 1.1.0.7?

**Comment by Axel32019** [comment]
no update -> closed
