### ISSUE TITLE
[BUG?] Missing the drive mode 'chase combine' 

### ISSUE THREAD

**Issue by ZerwasMOD** [Stephan-S/FS19_AutoDrive#1407]
**AutoDrive Version:** 1.1.0.4 
**Release or Custom Zip:** Release  
**Map (If applicable):** Irgendwo in Thüringen II
**Vehicle / Type (If applicable):**   
**Multiplayer or Singleplayer:** Singleplayer  

**Describe the bug**  
I am missing the drive mode 'chase combine' as desribed in the wiki [here](https://github.com/Stephan-S/FS19_AutoDrive/wiki/3-AutoDrive-modes:#355-precalldriver--chase-combine)
I am not sure if this feature has been removed again,  but it does not appear to be selected ingame in the settings menus. I have searched this project but haven't found evidence that this feature has been dropped again.

![fsScreen_2020_05_05_19_27_26](https://user-images.githubusercontent.com/5484590/81096418-9f18cd80-8f06-11ea-9a34-0949be3e1ed5.png)

**Comment by BloodyRain2k** [comment]
_Pre-Call_ is meant to trigger the chase mode while a vehicle is waiting with the _Unload Combine_ task.

**Comment by ZerwasMOD** [comment]
Alright, understood.
