### ISSUE TITLE
Fehler beim Abfahren von Gras

### ISSUE THREAD

**Issue by TripleX1978** [Stephan-S/FS19_AutoDrive#1408]
AutoDrive Version: 1.1.0.5-RC2

Eine Gras-Schwad soll mit einem Sammelwagen eingesammelt und zum Abladepunkt gebracht werden. Im ersten Durchgang wird, wenn der Sammelwagen voll ist, von CP an AD übergeben und der Fahrer fährt zum eingestellten Ziel und lädt ab.
Anschließend kehrt er zum Abfahrerpunkt am Feld zurück.
Dann wird aber nicht mehr von AD an CP übergeben.
AD bleibt aktiv und der Fahrer verharrt am Abfahrerpunkt.
Bei AD 1.1.0.4 hat es noch mit Stroh funktioniert.

**Comment by TobiHH78** [comment]
Bei mir funktioniert das fehlerlos. Häng mal deine Log dran.

**Comment by TripleX1978** [comment]
Hier die Logdatei.
Sind wohl einige Meldungen drin habe ich gerade gesehen.
Kann aber nicht mit allen etwas anfangen.
Heute scheint es zumindest auf einigen Feldern zu funktionieren, auf den meisten jedoch nicht.
[log.txt](https://github.com/Stephan-S/FS19_AutoDrive/files/4593990/log.txt)

**Comment by TripleX1978** [comment]
Nachtrag!

Habe die meisten Fehler beseitigen können.
Hier nochmal die neue Log.
Jetzt ist es aber so, dass der Häcksler plötzlich das Grassammeln einstellt und so über das Feld fährt.

Keine Ahnung warum.
Ich habe absolut nichts geändert und mit der Versio AD 1.1.0.4 lief alles reibungslos.

[log.txt](https://github.com/Stephan-S/FS19_AutoDrive/files/4594426/log.txt)

**Comment by Iwan1803** [comment]
Der Häcksler wird aber nicht per AD gesteuert, oder?
Vielleicht wäre hier eine genaue Beschreibung, welches Fahrzeug was und wie gesteuert macht.

**Comment by TripleX1978** [comment]
Habe es heute nochmal den Häcksler fahren lassen. Das Problem tritt nur auf dem Feld auf wo ich auch schonmal Heu gemacht habe.
Könnte es sein, dass sich noch "Mikropartikel" vom Heu auf dem Feld befinden und er deswegen durcheinander kommt? Wenn ich kurz danach wieder neu ansetzen fährt er erst mal wieder für ne Zeit.

**Comment by Iwan1803** [comment]
Könnte gut möglich sein. Deswegen gehe ich nach einer Ernte immer mit einer Scheibenegge über die Felder (per CP, scharfes Vorgewende), damit da nichts mehr drauf ist.

**Comment by TripleX1978** [comment]
Hallo nochmal!
Seit gestern läuft bei mir das Abfahren auf den Feldern wieder nicht richtig.
AD-Version: 1.1.0.5-RC3
CP-Version: 6.01.00397.dev
Map: NF-Marsch 4fach
Felder: 36 + 40

Feld 36:
Grasschwad wird mit Häcksler eingesammelt und an 10 identische Abfahrergespanne übergeben. Bei ca. jedem 2. Abfahrer kommt die Meldung, dass er den Weg zum Ziel nicht berechnen konnte, nachdem er zu 100% gefüllt ist und bleibt auf dem Feld stehen. Nachdem ich diesen dann ein paar Meter bewegt habe und AD wieder einschalte klappt es wieder. Ein anderer Abfahrer, der sich direkt daneben befindet, konnte zur gleichen Zeit einen Weg berechnen.

Feld 40:
Heuschwad soll mit 6 identischen Traktor-Sammelwagen-Kombis eingesammelt und autom. zum Hof gebracht werden. Auch hier ein ähnlicher "Fehler". Manche Gespanne switchen bei 100% um und fahren zum Hof. Andere bleiben stehen und machen nichts mehr. AD ausgeschaltet, das Gespann vom Feld runtergefahren und AD wieder eingeschaltet und es funktioniert wieder.

**Comment by Iwan1803** [comment]
Bitte lade 1.1.05.-RC4 herunter, versuch es erneut und poste dann ein Feedback.

**Comment by TripleX1978** [comment]
Ich habe mir die neue Version nun installiert.
Der "Fehler" ist immer noch da.
Bei Stroh läuft es ohne Probleme.
Der einzige Unterschied zwischen den Feldern ist, dass ich das Grasfeld mehrfach gemäht habe bevor ich es eingesammelt habe.
Könnte es unter Umständen etwas mit der Schadhöhe zu tun haben?

**Comment by Iwan1803** [comment]
Gras ist keine wirkliche Frucht und Grasfelder werden auch nicht wirklich als Felder erkannt.
Ich habe auf der NFM auf einem Grasfeld Gras gehäckselt und das funktionierte soweit problemlos. Leider haben aber einige der Abfahrer dann den Weg vom Feld runter meistens nicht gefunden.
Das ganze Abfahrerthema steht aber noch auf unser Todo-Liste und ist nicht so einfach zu lösen, da dort 2 Leute rumgewerkelt haben.

**Comment by TripleX1978** [comment]
Das Abfahrerproblem existiert aber nicht nur bei Gras.
Seit der Umstellung auf RC4 habe ich auch Probleme beim Maishäckseln und bei Dreschern.

Die Abfahrer werden zwar aufs Feld gerufen, auf dem Weg zum Drescher/Häcksler bleiben diese oft stehen und switchen wieder in den Modus "Berechne Pfad" oder es erscheint an dem Abtanken die Meldung das der Pfad zum Ziel nicht gefunden wurde.
Wenn man dann AD nochmal aktiviert klappt es ab und zu mal dass er dann doch den Weg findet.

Ein andere Sache die mir noch aufgefallen ist, ist, dass häufig mehrere Abfahrer aufs Feld gerufen werden, obwohl ich die Option "2. Abfahrer rufen" ausgeschaltet habe. Habe dann teileweise 5 leere Abfahrer und mehr auf dem Feld rumstehen und keiner fährt zum vollen Drescher/Häcksler.

**Comment by TobiHH78** [comment]
Das Problem beim dreschen kann ich bestätigen. Bei mir berechnet der Abfahrer auf dem Feld auch mehrfach den Pfad neu. Ich brauche ihn allerdings nicht nochmal aktivieren, sondern nur ein paar Sekunden warten, dann fährt er nach Neuberechnung weiter zum Drescher.

Durch die Dauer, die der Abfahrer zur Berechnung braucht, schafft es der Abfahrer auch nie rechtzeitig den Drescher noch im Fahrbetrieb zu erreichen. Der hat dann schon immer die 100% erreicht.

**Comment by Iwan1803** [comment]
2 Drescher per CP auf einem Feld und dazu 4 Abfahrer = bis auf 2 oder 3 Kleinigkeiten keine Probleme.
Kleiner Hinweis: https://github.com/Stephan-S/FS19_AutoDrive/issues/1479

**Comment by TobiHH78** [comment]
Mag sicher auch an der Map und Feldgröße liegen. Bin auf der Fenton Forest 4x unterwegs, und da sind die Felder teilweise 20-30 ha groß. da dauert die Berechnung sicher auch länger als bei einem 0,8 ha Feld auf der Stappenbach (nur um ein Beispiel zu nennen).

**Comment by TripleX1978** [comment]
Habe das Problem sowohl auf kleineren und größeren Feldern.
Ist denn schon ein Datum für die nächste Version in Aussicht?

**Comment by Iwan1803** [comment]
Die Pfadberechnung ist das komplexeste, was es in AD gibt und jede Änderung kann zu anderen Problemen führen. Einen Termin zu nennen wäre daher "unprofessionell".
So, it's done when it's done...
