### ISSUE TITLE
[BUG] LUA Error: PathFinderModule.lua:208: attempt to index a nil value With new CP version

### ISSUE THREAD

**Issue by masneoquil** [Stephan-S/FS19_AutoDrive#1409]
**AutoDrive Version:** 1.1.0.5 RC   
**Release or Custom Zip:** Custom  
**Map (If applicable):** Nebraska Lands
**Vehicle / Type (If applicable):**   
**Multiplayer or Singleplayer:** Singleplayer  

**Describe the bug**  
I'm running several workers:
4 combines working on a field,
6 unloaders for those 4 combines, but with AD in command
2 balers on 2 different field, (only CP)
3 CP drivers collecting and unloading bales on different fields (only CP).

The new version of CP has the first version of combi mode. This mode it is used to unload the combines. This first version only unload the combines when they are full,so since AD does the same I'm using AD because is easier due to the network already have.
There must be something different with both mod communication because it wasn't happening before CP update.
I already open an Issue on CP github also
After the AD LUA Error, CP start with continuos Callstack Errors, freezing up my game.
I'm attaching the log file, but I had to edit it because it was 35MB

[log.txt](https://github.com/Stephan-S/FS19_AutoDrive/files/4583690/log.txt)

**Comment by Iwan1803** [comment]
https://github.com/Courseplay/courseplay/issues/5305

**Comment by masneoquil** [comment]
Yeap, I opened that issue.

**Comment by Iwan1803** [comment]
Does this problem still exist?

**Comment by masneoquil** [comment]
Yes, it does.
Unfortunately, it also happens with CP version 399.
This CP version does not have the new Unloader functions of the latest versions.
I opened this issue thinking it had something to do with that fact, but it is happening with version 399, and this version doesn't have it.
If it happens again I make sure to upload a log again. But the error it is the same.

**Comment by Iwan1803** [comment]
Did you try the latest RC of AD?

**Comment by masneoquil** [comment]
Yes, so far I didn't have the problem again.
If it come up againg I open another issue.
Thanks again!!!
