### ISSUE TITLE
[BUG] CP <-> AD issue loading generated courses

### ISSUE THREAD

**Issue by iljarogoff** [Stephan-S/FS19_AutoDrive#1410]
**AutoDrive Version:** 1.1.0.5   
**Release or Custom Zip:** latest git
**Map (If applicable):** All
**Vehicle / Type (If applicable):**   all
**Multiplayer or Singleplayer:** Singleplayer  

**Describe the bug**  
CP gets courses from AD destinations, but CP fails to load them. Already mentioned that in CP git, Tensuko asked me to ask for more information here, e.g. additional log data. 

**If applicable - Steps to reproduce the behavior**  

Load AD generated course in CP
![fsScreen_2020_05_06_16_29_00](https://user-images.githubusercontent.com/21023840/81192774-e5c7ff80-8fba-11ea-955b-d7063bc8b739.png)
[log.txt](https://github.com/Stephan-S/FS19_AutoDrive/files/4587569/log.txt)

**Screenshots**

**Comment by Tensuko** [comment]
Some Data from the log:
2020-05-06 16:38 :21 [info lp4272] N134: AutoDrive could not give us a course from the current position to Am Hofsilo beladen
2020-05-06 16:38 :21 [info lp4272] N134: id 10000 -> course not found, return

Issue at CP GitHub
https://github.com/Courseplay/courseplay/issues/5315

**Comment by Williwillswisse** [comment]
It is not really a bug. To load AD courses into CP the position of your vehicle has to be close to an AD course.

**Comment by Iwan1803** [comment]
If you use AD for unload, CP is not involved.
It looks like you are using CP for unloading the tresher and AD to unload the unloader.
Am i right?

**Comment by iljarogoff** [comment]
yes, the combine is driven by CP. the idea was, the tractor should use an AD course within CP to unload at the silo and drive back to the field.

**Comment by Iwan1803** [comment]
The tractor should only use AD for unloading, not CP.

**Comment by iljarogoff** [comment]
Ok, I thought I could make a CP course out of the AD generated courses to have the tractor driven by CP unloading the combine, transport the grain to the silo and move back to the field. CP is more reliable for unloading than AD, me is having lots of issues and I have to babysit the AD unloader all the time...

**Comment by Iwan1803** [comment]
For me everything is running fine. Please try the latest RC3.
