### ISSUE TITLE
[BUG] RC2 ignores pipe offset

### ISSUE THREAD

**Issue by SteelRodent** [Stephan-S/FS19_AutoDrive#1411]
**AutoDrive Version:** 1.1.0.5 RC2
**Release or Custom Zip:** Release  
**Map (If applicable):** Nowa Bruzda 
**Vehicle / Type (If applicable):**   any
**Multiplayer or Singleplayer:** Singleplayer  

**Describe the bug**  
With CP driving the combine harvesters I let AD drive the tractors to unload. Only with RC2 it completely ignores the pipe offset and drives up right next to the combine and collides with the header,  much too close to get under the  pipe.  Tried increasing the pipe offset further left, and tried with different tractors and trailers, but the result  is the same.

**If applicable - Steps to reproduce the behavior**  
Set combine to  harvest any field.
Set  AD driver to empty combine mode.
When combine is full AD fails to line up correctly to empty.

I haven't updated AutoDrive in months, so decided I probably should with the new CP out, but with RC2 I now can't use it  for the one thing I mainly use AD for.

**Comment by BloodyRain2k** [comment]
Have you checked / adjusted the offset? For me the issue is that it just defaults to -0.65m for every new vehicle.

**Comment by betrox007** [comment]
you should try pipe offset, for combine with unload pipe at left side, set it 0,75 minimum also with the the tractor set the same, for combine with right side unload pipe(for example grimmie potato harvester), set it to -075 minimum do the same for the tractor, for me, it is working..

**Comment by SteelRodent** [comment]
Been busy the last few days, but are you saying positive is left and negative is right? Assumed it'd be opposite, but I've never had to change that value before so haven't paid attention to what it used to be.

**Comment by betrox007** [comment]
yes, what i ever try like that,for combine with unload pipe at left side, at the tractor you must set positif and for combine with pipe at right side you must use negatif value for offset

**Comment by SteelRodent** [comment]
Had to solve a game crash (caused by other mods), but discovered the offset defaults to 0.75 for any new save, but for existing saves it's set to -0.61 for all vehicles, so had to go through them all and change it to 0.75. But in the end it does work this way, even with the extra long pipe on the Case combine. So thanks. Got it solved :)
