### ISSUE TITLE
[BUG] Abfahrer bleibt nach abtanken stehen - tractor stops after unloading

### ISSUE THREAD

**Issue by timmi4026** [Stephan-S/FS19_AutoDrive#1412]
AutoDrive Version: 1.1.0.5 RC2
Release or selbsterstelltes zip: Release
Karte (falls relevant): NF Marsch

Mein Abfahrer kommt zum Feld fährt auch zum Drescher und tankt ab. Dann kommt in der Statusleiste Zurücksetzen von Drescher und der Schlepper schleicht ganz langsam vorwärts. Nach ein paar Meter bleibt er stehen aber er kommt nicht mehr aus dem zurücksetzen Modus raus, also es steht anschließend nicht da warte auf Ruf. Ab diesem Moment passiert nichts mehr bis ich den Auftrag stoppe und neu starte. Dann fährt er wieder zum Drescher und das gleiche passiert wieder.

Passiert im Multiplayer in Kombination mit CP und AI Vehicle Extension. Standard Helfer aus dem Spiel gehen. 

![Screenshot_19](https://user-images.githubusercontent.com/46847594/81263000-279a8980-903f-11ea-9dd8-700bc5bc0094.png)

LG TIMMI

**Comment by geo-luchs** [comment]
Hallo

Ich habe das gleiche Problem.
Es sieht so aus, als ob es zusammenhängt mit VCA (VehicleControlAddon)

Ich habe es jetzt exakt eingrenzen können auf die VCA Version 0.1.0.0

VCA 0.0.9.9 : AD funktioniert.
VCA 0.1.0.0 : AD funktioniert nicht mehr.

Hier ist der Link zu Mogli's Commit:
https://github.com/Mogli12/VehicleControlAddon/commit/87af6f432c13f14183fefabff150519b36545862

**Comment by Mogli12** [comment]
Hi,

ich vermute, dass AutoDrive den Traktor steuert, ohne ihn korrekt auf Helfer umzustellen. Dann wird ShuttleControl nicht abgestellt und das Fahrzeug fährt nicht zurück.

Vielleicht kann man in AutoDrive dazu self:getIsVehicleControlledByPlayer() umbiegen?

Viele Grüße,
Stefan

**Comment by geo-luchs** [comment]
Danke Stefan für die schnelle Antwort.

 Gruß
Carsten

**Comment by leo32128** [comment]
Ich habe mich hier nur durch Einschalten des automatischen Motorstarts in den Spieleinstellungen entschieden, aber es wäre gut, ihn wie zuvor ohne diesen Fehler zu verwenden. Entschuldigen Sie die Übersetzung, da ich aus Brasilien komme und den Google-Übersetzer verwende

**Comment by Iwan1803** [comment]
Existiert das Problem noch mit der letzten VCA-Version?

**Comment by leo32128** [comment]
Ich habe heute mit der neuesten Version von VCA getestet und das Problem besteht weiterhin, wenn der automatische Start einwandfrei funktioniert. Wenn der automatische Start deaktiviert ist, tritt das Problem erneut auf, REVERSSING FROM COMBINE, und verlässt es erst, wenn Sie die Anzeige deaktivieren und erneut aktivieren

**Comment by leo32128** [comment]
Heute habe ich mit der neuesten Version von VACA getestet und das Problem besteht weiterhin, wenn die automatische Zündung des Geräts deaktiviert ist
Die Meldung REVERSSE FROM COMBINE wird angezeigt

**Comment by Iwan1803** [comment]
Wenn automatische Zündung aktiviert ist, dann geht es?
Was passiert, wenn VCA deaktiviert wird?

**Comment by leo32128** [comment]
Wenn der VCA deaktiviert ist, fährt das Fahrzeug langsam rückwärts

**Comment by Iwan1803** [comment]
Also ist VCA bzw. eine falsche Einstellung Schuld am Problem. Stell mal das Helfer-Getriebe auf "allways".

**Comment by leo32128** [comment]
ok ,, ich werde es versuchen, danke

**Comment by leo32128** [comment]
Das gleiche Problem, der Traktor oder LKW hält nach dem Entladen an, aber es ist gut, ihn bis zu einem zukünftigen Update zu verwenden, danke für diesen unglaublichen Mod

**Comment by Iwan1803** [comment]
Mit dem nächsten RC kommen etliche Fixe und Verbesserungen. Möglicherweise ist dieses Problem dann auch verschwunden.
Ich schließe hier erstmal und sollte das Problem mit dem neuen RC auftauchen, dann kannst du dieses Issue einfach wieder öffnen.
