### ISSUE TITLE
[FEATURE REQUEST] Black-/Whitelist -  vehicle-specific routes - Fahrzeugspezifische Routen

### ISSUE THREAD

**Issue by bastib1205** [Stephan-S/FS19_AutoDrive#1413]
**Is your feature request related to a problem? Please describe.**
Often the short way isn't the best way. So many time my Trucks want to use short ways, but they are too long. 

Es kommt öfters vor, dass LKW's zu lang sind oder unpassende Lenkradien haben, sodass diese bei Traktor-Pfaden öfters hängen bleiben.

**Describe the solution you'd like**
Now it would be great if i could change settings of one way so that only tractors should use this and the other only by trucks.

Es wäre hier super, wenn ich die Pfade möglicherweise gruppieren könnte. Die Gruppe 'X' darf bspw. nur durch Traktoren genutzt werden, während die Gruppe 'Y' nur von Trucks genutzt werden darf und die Gruppe 'Z' darf wiederum von allen genutzt werden.

**Describe alternatives you've considered**
Blacklist - Whitelist: Another solution would be if I only can block one line (or waypoint) for a specific vehicle.

Blacklist - Whitelist: Eine Alternative dazu wäre, wenn ich eine Linie, bzw. einen Wegpunkt für ein Fahrzeug sperren könnte, sodass dieses Fahrzeug hier nicht mehr lang fährt.

**Additional context**
Often other vehicles want to use reverse-lines of parkings from other vehicles which are already blocked. Here i would block this line for all vehicles and only this one can use it.

Oft wollen Fahrzeuge bei mir Rückwärts-Pfade nutzen. Diese nutze ich aber meist nur beim Parkplätzen, weshalb diese Pfade oft bereits belegt sind. Dann würde ich diesen Pfad für alle Fahrzeuge blocken und nur der das eine dürfte diesen Pfad befahren.

**Comment by MicaelJarniac** [comment]
@bastib1205, take a look at #1382, I think you might like the ideas there.
I've suggested smart targets that can have filters, so what you're wanting would totally be possible with that, and even a lot more things!

**Comment by Iwan1803** [comment]
Correcting the waypoints could help to avoid problems.
As discussed in earlier requests like this one: cost/benefit factor is not given.
