### ISSUE TITLE
[Feature Request] oberste Leiste im Zielauswahlmenü fixieren

### ISSUE THREAD

**Issue by BrunoMoser13** [Stephan-S/FS19_AutoDrive#1414]
Ich bin ein großer Fan von AD !!!

Ich hätte noch eine kleine Anregung was die Übersichtlichkeit angeht.
Wäre es möglich, dass man im Auswahlfenster die oberste Zeile wo man die Lupe hat und die Ordner als gesamtes zuklappen kann IMMER eingeblendet lässt? Jetzt ist es so, dass ich immer ganz nach oben scrollen muss um die Ordner zu schließen und den gewünschten Zielpunkt zu finden.....

Wäre ganz toll. 

Super support - by the way !!

**Comment by TobiHH78** [comment]
Das würde ich ebenfalls begrüssen.

**Comment by Axel32019** [comment]
Ist in Version 1.1.0.5-RC6 (23.09.2020) enthalten.
