### ISSUE TITLE
[FEATURE REQUEST] Deleting Courses

### ISSUE THREAD

**Issue by kwguk** [Stephan-S/FS19_AutoDrive#1415]
There already be a simple way of deleting saves courses but i i haventworked it out yet if there is.

At the moment wheni want to delete a course i have to delete it node by node, which is firstly a pain and secondly time consuming.

Is there a simpler way??

**Comment by Iwan1803** [comment]
Maybe in the future....

**Comment by Axel32019** [comment]
see Release 1.1.1.4
