### ISSUE TITLE
Autodrive 

### ISSUE THREAD

**Issue by ppeell** [Stephan-S/FS19_AutoDrive#1416]
guten tag mein problem ist  das das abfüllen nicht funktioniert an hof silo und zwar er füllt den hänger voll und bleibt dann stehen also beim Ton hört sich das an ob der nen Motorschaden hat und fährt dann nur Millimeter für Millimeter vor bis er irgend wann nach 5 Minuten einen Punkt erreicht wo er weiter fährt .

**Comment by vertigoogle** [comment]
Satzzeichen retten Leben!
Außerdem solltest du beim Erstellen eines Bug Reports das Template verwenden (Version, Karte, Fahrzeug, etc..)

Beste Grüße

**Comment by Iwan1803** [comment]
Problem sollte im nächsten RC gefixt sein.
Bitte zukünftig das Template nutzen, danke!
