### ISSUE TITLE
[BUG] GlobalCompany liquid output trigger not being detected

### ISSUE THREAD

**Issue by MicaelJarniac** [Stephan-S/FS19_AutoDrive#1417]
| Technical Information ||
|--|--|
| AutoDrive Version | `1.1.0.5-RC2` |
| Release or Custom Zip | Release Candidate |
| Map (if applicable) | All |
| Vehicle / Type (if applicable) | Any vehicle that can take liquid or has a trailer that can |
| Multiplayer or Singleplayer | Singleplayer (probably multiplayer too) |

## Bug description
[GlobalCompany | ModHub](https://www.farming-simulator.com/mod.php?lang=en&country=us&mod_id=137078&title=fs2019) `v1.5.0.0` liquid output triggers (where you take liquid from the storage to your vehicle) aren't being detected, at least not with the [Large Liquid Storage | ModHub](https://www.farming-simulator.com/mod.php?lang=en&country=us&mod_id=153022&title=fs2019) `v1.0.0.1` mod.

## Steps to reproduce the behavior
1. Install [AutoDrive](https://github.com/Stephan-S/FS19_AutoDrive) `v1.1.0.5-RC2` from GitHub
1. Install [GlobalCompany | ModHub](https://www.farming-simulator.com/mod.php?lang=en&country=us&mod_id=137078&title=fs2019) `v1.5.0.0`
1. Install [Large Liquid Storage | ModHub](https://www.farming-simulator.com/mod.php?lang=en&country=us&mod_id=153022&title=fs2019) `v1.0.0.1`
1. Create a new save with **AutoDrive**, **GlobalCompany** and **Large Liquid Storage** all activated
1. Buy and place the **Large Liquid Storage** building from **Placeables** > **AgraZ** > **Large Liquid Storage**
1. Load the **Large Liquid Storage** with some liquid (liquid fertilizer, for example)
1. Create a course on **AutoDrive** that goes through the output area (behind the **Large Liquid Storage** building)
1. Create a target on **AutoDrive** slightly after the output area
1. Assign a vehicle (tractor with liquid fertilizer sprayer, for example) to load a liquid (liquid fertilizer, for example) on the target, and start **AutoDrive**
1. Notice the vehicle will drive over the output trigger and park on the target, but it won't take any liquid
1. Turn off **AutoDrive**, press the load key (default <kbd>R</kbd>) and notice you can load the desired liquid manually, so the vehicle was indeed in the output trigger
1. ~~Write a bug report on [AutoDrive's GitHub issues](https://github.com/Stephan-S/FS19_AutoDrive/issues)~~

## Video, log and save file
- Log: https://pastebin.com/jDPjV02n
  - I believe my testing run started at **line 7285** (I forgot to reset the log before testing)
- Video: [watch on Google Drive](https://drive.google.com/file/d/1NwDCFj02msrB8FyA-De2VX-YQGH5RjgK/view?usp=drivesdk)
  - Timestamps (they click!):
    - [`00:00`](https://drive.google.com/file/d/1NwDCFj02msrB8FyA-De2VX-YQGH5RjgK/view?t=0m) steps 1 to 3
    - [`00:09`](https://drive.google.com/file/d/1NwDCFj02msrB8FyA-De2VX-YQGH5RjgK/view?t=0m9s) step 4
    - [`00:31`](https://drive.google.com/file/d/1NwDCFj02msrB8FyA-De2VX-YQGH5RjgK/view?t=0m31s) step 5
    - [`01:00`](https://drive.google.com/file/d/1NwDCFj02msrB8FyA-De2VX-YQGH5RjgK/view?t=1m) step 6
    - [`01:33`](https://drive.google.com/file/d/1NwDCFj02msrB8FyA-De2VX-YQGH5RjgK/view?t=1m33s) steps 7 and 8
    - [`02:15`](https://drive.google.com/file/d/1NwDCFj02msrB8FyA-De2VX-YQGH5RjgK/view?t=2m15s) steps 9 and 10
    - [`03:30`](https://drive.google.com/file/d/1NwDCFj02msrB8FyA-De2VX-YQGH5RjgK/view?t=3m30s) step 11
    - [`03:40`](https://drive.google.com/file/d/1NwDCFj02msrB8FyA-De2VX-YQGH5RjgK/view?t=3m40s) repeating steps 9 to 11
    - [`05:17`](https://drive.google.com/file/d/1NwDCFj02msrB8FyA-De2VX-YQGH5RjgK/view?t=5m17s) enabling all **AutoDrive** debug options
    - [`05:55`](https://drive.google.com/file/d/1NwDCFj02msrB8FyA-De2VX-YQGH5RjgK/view?t=5m55s) repeating steps 9 to 11 with debug and log visible
- Save: [download from Google Drive](https://drive.google.com/file/d/16QPTNYYrlb_aKS0G72jz9VGPFtIvGJiW/view?usp=drivesdk)
  - Also used [Store Deliveries | ModHub](https://www.farming-simulator.com/mod.php?lang=en&country=us&mod_id=134594&title=fs2019) and [Easy Development Controls | ModHub](https://www.farming-simulator.com/mod.php?lang=en&country=us&mod_id=138864&title=fs2019) to simplify testing

**Comment by MicaelJarniac** [comment]
I'm having a lot (trust me, a LOT) of problems getting Windows 10's built-in video editor thingy to render the video. I'll try it again tomorrow, but I might have to upload the full length video if I can't get that to work (the edited video had a lot of sped-up parts to make it shorter and less frustrating to watch).

And I got in contact with the creator of **Large Liquid Storage**, and they said they'd be looking into this issue and seeing if it's fixable from their part (or something like that), so that's awesome!

So if it's actually an issue with **Large Liquid Storage**, and not **AutoDrive**, they'll probably get it fixed!

I love so much the modding community around FS19! Thanks to all of you!

**Comment by MicaelJarniac** [comment]
Finally! A day, 3 render attempts, 2 reboots and 1.54 GB later, the video is rendered!
I'll update the issue with the link and timestamps.

**Comment by MicaelJarniac** [comment]
As I just uploaded the video, it might take a while for Google Drive to allow high definition playback, but it should shortly be available in full HD.

**Comment by LS-Alex4884** [comment]
hi i looked at your video and tested it and as I thought it and saw in your video your target is wrong, it is too close to the trigger. The target point should be set at least so far forward that the tractor or truck has pulled out of the trigger. So, for example, like in your test video two points further forward then it goes. Since I also use the GC version 1.5.0.0 and the AD version 1.1.0.5-RC2 and the same Large Liquid Storage from Zoddel and I can do it without problems on the standard card and on the mod map I play. Please test it again with my suggestion to set the target points by at least two tractors length behind the trigger so that the tractor would pull the syringe out of the trigger, then it should work. that should solve your problem. 

translated with google since my english is not so good

hi ich hab mir mal dein video angeschaut und es getestet und so wie ich es mir dachte und in deinem video schon gesehen habe ist dein ziel punkt falsch gesetzt , er ist zu nah dran an dem trigger . der ziel punkt sollte mindestens so weit nach vorne gesetzt werden das ,dass der Trecker oder der Lkw aus dem Trigger gefahren ist. Also zum Beispiel wie in deinem test video noch zwei punkte weiter nach vorne dann geht es. Da ich auch die GC version 1.5.0.0 und die AD version 1.1.0.5-RC2  benutze und das gleich Large Liquid Storage von Zoddel und es geht bei mir ohne probleme auf der Standart Karte und auf der Mod Map die ich spiele. Bitte teste es noch mal mit meinem Vorschlag den ziel punkte um mindestens zweit Trecker längen hinter dem Trigger erst zu setzen so das der Trecker die Spritze mit aus dem trigger ziehen würde dann sollte es klappen. das müsste dein Problem lösen.

**Comment by MicaelJarniac** [comment]
Hi @LS-Alex4884, thanks for the reply. I'll try moving the target around as you suggested, and will report back with results. Thanks again for the suggestion.

Translated to German:
> Hallo, danke für die Antwort. Ich werde versuchen, das Ziel so zu bewegen, wie Sie es vorgeschlagen haben, und mit Ergebnissen berichten. Nochmals vielen Dank für den Vorschlag.

**Comment by MicaelJarniac** [comment]
@LS-Alex4884, your suggestion totally worked! Thank you very much.

So it turns out setting the actual target further forward from the trigger does solve the problem. I'm not sure how far forward it has to be, but I'd suggest for anyone trying to get it to work to just test it, set the target just outside the trigger area, then if it doesn't work, move it forward a bit, and repeat this until it works.

Well, it feels like a hacky workaround, but as long as it works, I'm fine with it!

I'll leave this issue open for now, as I did contact the creator of **Large Liquid Storage**, and they might take a look in here and who knows, maybe even come up with a cleaner solution that allows the target to be on top of the trigger and still work.

But I'm happy there's actually a simple workaround for this. Thanks again for suggesting it!

**Comment by Iwan1803** [comment]
Was there any reply from the creator of Large Liquid Storage?

**Comment by MicaelJarniac** [comment]
This is what they replied:
> I think the reason for the trigger is simply that diesel can be stored in the warehouse and when the tractor is in the trigger Autodrive tries to fill the tractor.

**Comment by Iwan1803** [comment]
Does the problem still exists? Did you tried it with AD 1.1.0.6?

**Comment by MicaelJarniac** [comment]
I haven't played in ages (got a new job), so I haven't tried yet. I'll try to test it in the next few days and reply back.

**Comment by Iwan1803** [comment]
Ok, i'll close this issue. If the problem still exists, then please open a new issue.
