### ISSUE TITLE
[BUG] "Can't calculate a path" on unloaders in large fields

### ISSUE THREAD

**Issue by realskudd** [Stephan-S/FS19_AutoDrive#1420]
**AutoDrive Version:** 1.1.0.4   
**Release or Custom Zip:** Release  
**Map (If applicable):** All  
**Vehicle / Type (If applicable):**   Unloader combination (8400R + Asperion, for example)
**Multiplayer or Singleplayer:** Singleplayer  

**Describe the bug**  
When having a deal set up between a harvester of any kind plus any sort of unloader, in the middle of a medium to large field the unloader will frequently give up on trying to find a route to the unload point immediately after unloading. It doesn't matter if I have the pathfinder max time cranked up, restrictions enabled/disabled, if I have the field exit set to default, behind start, or nearest point, or even if I have a route around the perimeter of the field.

**If applicable - Steps to reproduce the behavior**  
I've experienced it on multiple maps, but most recently with County Line and Lazy Acres. Just today, I started seeing it happen on field 6 and 12 on Lazy Acres. 

**Screenshots**  
N/A

**Comment by rmn18** [comment]
test Beta Version ;)

**Comment by realskudd** [comment]
No dice. Here are a couple screenshots. First one showing the thing giving up. Second showing where the path is.

![fsScreen_2020_05_15_12_57_16](https://user-images.githubusercontent.com/4642150/82081325-b5afe900-96ab-11ea-9834-84649684bd92.png)
![fsScreen_2020_05_15_12_57_09](https://user-images.githubusercontent.com/4642150/82081330-b8124300-96ab-11ea-958d-b1283fb81c4f.png)

**Comment by Iwan1803** [comment]
Please try with the lastest RC and then give us a feeback.

**Comment by tanordheim** [comment]
I'm on the latest RC2 release on Eiersholt and I'm seeing the same issue.

**AutoDrive Version:** 1.1.0.5-RC2   
**Release or Custom Zip:** Release  
**Map (If applicable):** Eiersholt
**Vehicle / Type (If applicable):** Case IH 9240 / Man TGS 18.500 4X4  - but happens on all of my setups
**Multiplayer or Singleplayer:** Singleplayer  

Combine unload settings:

![FarmingSimulator2019Game 2020-05-19 22-05-26](https://user-images.githubusercontent.com/49933/82372973-285af480-9a1d-11ea-93d3-c660e7d3908d.png)

Unload vehicle settings:

![FarmingSimulator2019Game 2020-05-19 22-08-11](https://user-images.githubusercontent.com/49933/82373062-49bbe080-9a1d-11ea-935f-cee7d6c3aaa9.png)

It doesn't even really have to be a big field or be far away from the unloader as far as I can tell. The behavior with these settings is that it gets called by the combine (running latest Courseplay release) which quite quickly trigger an "Can't calculate path"-message, some waiting period until it starts moving to the combine and unloading successfully. This also prevents things like chasing the combine as it seems to give up quite quick when trying to start chasing at 60% - only when the combine is actually full and it has given up on calculating path once does it start successfully navigating to the combine. I'll try to produce some screenshots with debugging enabled later.

**Comment by realskudd** [comment]
> Please try with the lastest RC and then give us a feeback.

Dumb question: Where is the RC branch? All I see is the master branch, beta, and the most recent releases.

**Comment by Iwan1803** [comment]
At the bottom of the page: https://github.com/Stephan-S/FS19_AutoDrive

**Comment by realskudd** [comment]
No dice. Same symptoms.

**Comment by BastiHRO** [comment]
Ich habe ebenfalls dieses Problem und nutze die RC3... 
Auf großen Feldern findet der Abfahrer kein Pfad zum Ziel/Abladeort. Dieses Problem habe ich in bisher allen Versionen vorgefunden.

Als Test: Ich habe bereits mehrere Zusatzpfade in das Feld gesetzt um es dem Abfahrer zu erleichtern einen Pfad zu finden. Dieses hat mäßig geklappt, denn der Abfahrer musste immer gleich neben dem gesetzten Pfad stehen um das Feld verlassen zu können. Also habe ich die Pfade IM Feld auch wieder gelöscht...

**Comment by realskudd** [comment]
Off Topic: @BastiHRO - I was able to self-translate the first part of your message there, but ultimately had to resort to Google Translate to read the whole thing.  I need to get back to learning German.

On Topic: I've tried similar things, defining alternate exit paths through the fields, but as you said, it doesn't always work. The unloader can be 20m away from the path and still not immediately see it as a valid path. After it aborts, if I turn AD back on right away, it will find that path and all will be well (though sometimes it is confused and wants to go back to the field entry point with a full trailer).

**Comment by Iwan1803** [comment]
@BastiHRO wie sehen deine Einstellungen für den Abfahrer aus? Welche Strategie für die Feldausfahrt hast du eingestellt?
_What are your settings for the unloader? What strategy for the field exit have you set?_

**Comment by realskudd** [comment]
I've been playing again on County Line with the RC build and it actually seems to be worse. My setup is relatively simple. 

- Combine (modded Ideal 9T)
- Tractor (8400R Southern Boy mod)
- Aperion 3401 trailer

I have a network built in such a manner that there's a perimeter around field 11, for example, split on the northwest border in the middle, paths joined but going opposite directions around to an exit near the windmill on the southwest border. Then from there, around through the farm property to a multifruit silo on the south side of the property, and a route back to the southwest border of the field near the exit. The exit and entry are both joined in a weird form as part of trying to get away from "can't calcaulate a path to field 11", but it didn't help.

This same pattern is on other fields with other workers, and this message pops up frequently. I even had it happen once when the helper was sitting RIGHT ON a path exiting the field and connected to the farm. When it said it couldn't find a path, I hit the enable button again right away and it had no issue.

Something else that seems to happen occasionally is nodes on the path get invalidated for some reason. If I move to the next node, it has no issue whatsoever. I can even stop and go back to the previous node that was erroring in this manner and it seems to be valid again.

I don't mind helping to debug this further, but I need a little bit of guidance. Specifically, how do I enable logging to monitor what's happening in more detail? I'd like to roll my own build with some additional logging to see if I can track it down and submit a PR to fix it, as it's a rather annoying bug.

**Comment by realskudd** [comment]
Here's another attempt with a different unloader, describing the same behavior in my previous post.
![fsScreen_2020_06_01_19_29_24](https://user-images.githubusercontent.com/4642150/83589183-b902fb80-a518-11ea-9339-505b5c1e24bd.png)

**Comment by realskudd** [comment]
Here's another.
![fsScreen_2020_06_02_21_42_27](https://user-images.githubusercontent.com/4642150/83589905-311df100-a51a-11ea-81a1-a541d427aaf4.png)

**Comment by realskudd** [comment]
@Iwan1803  - Do y'all need anything from me on this still?

**Comment by Iwan1803** [comment]
Please download 1.1.05.-RC4 and try again.

**Comment by tanordheim** [comment]
I'm getting this still on the latest commit on the `beta-testing`-branch. My settings are the same as in my [previous comment](https://github.com/Stephan-S/FS19_AutoDrive/issues/1420#issuecomment-631056529).

The combine settings are set to pre-call at 60%, and any waiting unloader does start spitting the "Can't calculate path"-error when the combine is at 60% even if the pipe is not in fruit and it keeps showing the message a few more times until the combine is 100% full and stops for unloading. Then the unloader finds a path to the combine, drives to it, unloads gracefully and drives away like it's born to do it.

I'll provide a screenshot with full debugging enabled next time it happens for me. I don't think I'll have time to play any tonight but I'll try to fix tomorrow.

**Comment by realskudd** [comment]
Still happening with RC4, @Iwan1803 .

![fsScreen_2020_06_17_09_24_42](https://user-images.githubusercontent.com/4642150/84910368-6aa73e00-b07c-11ea-92ef-7a3d78c42fc9.png)

**Comment by Iwan1803** [comment]
A screenshot is nice, but we need the settings of the unloader and the combine.
If fruit bypass is active, how could the unloader reach the beet harvester?

**Comment by realskudd** [comment]
Unloader:
![fsScreen_2020_06_17_17_56_35](https://user-images.githubusercontent.com/4642150/84958942-06a86800-b0c4-11ea-90a3-c7580876adb4.png)
![fsScreen_2020_06_17_17_56_49](https://user-images.githubusercontent.com/4642150/84958958-10ca6680-b0c4-11ea-82c3-665fbba89da9.png)

Beet harvester:
![fsScreen_2020_06_17_17_57_01](https://user-images.githubusercontent.com/4642150/84958986-19bb3800-b0c4-11ea-926b-589059ee48d1.png)
![fsScreen_2020_06_17_17_57_03](https://user-images.githubusercontent.com/4642150/84958987-1b84fb80-b0c4-11ea-8b8a-438bd4e0918f.png)

In this particular field, the beet harvester cut the headland rows 3 wide and is now working on the up/down rows. This field has an AD perimeter around it, leading back to the field exit. Exit strategy is set to closest point. CoursePlay is running the harvester, AD for everything else.

**Comment by realskudd** [comment]
This behavior is reproducible with any harvester and unloader combo.

**Comment by Iwan1803** [comment]
-> https://github.com/Stephan-S/FS19_AutoDrive/issues/1479

**Comment by Iwan1803** [comment]
Da 1.1.0.6 released wurde, mach ich hier mal zu // As 1.1.0.6 was released, i'll close here 😎

**Comment by Th301** [comment]
Ich nutze 1.1.0.7 und habe nach wie vor das Problem :(

**Comment by Anonymous-any** [comment]
Hello @Iwan1803 ,

I get too no path for reach the combine by CP drived, I try to search what is not correct, I use a dl AD file that I've not made myself for a map who contain blue line's inside and around all fields is it this culprit of the problem ?
So I saw you say about Field exit so what is must set for avoid this please ?

Br
