### ISSUE TITLE
[BUG]Wont fill drill to 100%

### ISSUE THREAD

**Issue by kwguk** [Stephan-S/FS19_AutoDrive#1421]
**AutoDrive Version:** 1.1.0.5RC2
**Release or Custom Zip:** Release  
**Map (If applicable):** Eiersholt
**Vehicle / Type (If applicable):**   Horsch drills from Horsch pack
**Multiplayer or Singleplayer:** Singleplayer  

Ive got a course set up tp refill my drills froman overhead silo. Theyll all go to the silo no problem. They then stop and i have to instigate the refill, im guessing this because of the drill cover?
Thats not a real problem to be honest. The problem is the tracor will move off before the drill is refilled 100%. I cant see anywhere to instruct how much to fill the drill with. 

Am i missing something or is it a bug?

**Comment by kwguk** [comment]
As an update, AD will fill Slurry tankers and fert spreaders to 100% but not any seed drill ive tested. The seed drill always goes to about 60% and then moves off

**Comment by Axel32019** [comment]
Could you please provide a screenshot of the load area with enabled road network and target markers.
This would help much to understand the situation!
Background is the Horsch drills are combined seed and fertilizer.

**Comment by kwguk** [comment]
I think youre theory is correct. The silo fills fert spreaders and sprayers to 100% with a single product. The issue is only with drills with seed and fert.

**Comment by Axel32019** [comment]
So it is more a topic of the setup of the fill (empty) level?

**Comment by Iwan1803** [comment]
Which Horsch is it and which silo?

**Comment by kwguk** [comment]
Its this silo...https://www.farming-simulator.com/mod.php?lang=en&country=gb&mod_id=123890&title=fs2019

and its the two grain drills from the Horsch Agrovation pack, the Evo and the Serto

**Comment by Iwan1803** [comment]
So it's only 1 silo to load both? That doesn't work (very well) actually.

**Comment by kwguk** [comment]
Basically yes.

**Comment by Iwan1803** [comment]
_Please download 1.1.05.-RC4, try again and then post a feedback._
Bitte lade 1.1.05.-RC4 herunter, versuch es erneut und poste dann ein Feedback.

Changelog: https://github.com/Stephan-S/FS19_AutoDrive/wiki/Release-Notes
