### ISSUE TITLE
[BUG] Optimizing overloader functionality - Premos unloader belt collision

### ISSUE THREAD

**Issue by Martinnygaard** [Stephan-S/FS19_AutoDrive#1422]
**AutoDrive Version:** 1.1.0.5-RC2
**Release or Custom Zip:** Custom Zip
**Map (If applicable):** All  
**Vehicle / Type (If applicable):**   Straw harvest Premos (Overloader)
**Multiplayer or Singleplayer:** Singleplayer  

I am using CP to drive the same course as the harvester. When the Premos is full, it sendt AD to unload. 
AD is set to "Pickup and deliver"-mode.

The problem is when the premos overloads to a trailer, it folds down the unloading conveyor in the same second it starts driving - and because it folds down (and not up like a normal overloader) it collide with the trailer and replace it.

When the trailer is moved by the collision, next time AD is comming to unload, it's path is blocked by the trailer the it moved just before. I have to reposition the trailer at every unload trip.

I suggest to add a 5 (or 10) second delay before it unfolds the unloading unit.

On this picture it is coliding:
![overloader-auger](https://user-images.githubusercontent.com/26490587/81674078-ee9e5280-944c-11ea-9c42-077af7970f77.png)

The red line is the correct position - blue is the new position after collision:
![overloader-augercollission](https://user-images.githubusercontent.com/26490587/81674082-efcf7f80-944c-11ea-9338-50b39a36644b.png)

**Comment by Iwan1803** [comment]
We will check this later as this is a special situation.

**Comment by Iwan1803** [comment]
Did you try latest AD and CP versions?

**Comment by Martinnygaard** [comment]
Hi,

I am in the middle of a mow, so I sadly don't have access to my game at the moment..

**Comment by Stephan-S** [comment]
Cleaning up old issues.
