### ISSUE TITLE
Ladewagen bleibt stehen/Loader wagon stops

### ISSUE THREAD

**Issue by ratze68** [Stephan-S/FS19_AutoDrive#1423]
AutoDrive Version: 1.1.0.5 RC2
Release or selbsterstelltes zip: Release
Karte Obertahler
Fahrzeug(art) (falls relevant):

Der Sammler fährt auf dem Couresplay kurs, Stelle im Couresplay den lade den Kurs stelle "auf erste wegepunkt ein" Im AD siehe Foto. Der Sammler fährt los, findet auch der erste wegepunkt, läd den Ladewagen Voll und bleibt stehen, und nichts passiert mehr.

Ich muss ihn im Courseplay ausschalten und AD an, dann fährt er los lädt ab.

![srohsammler](https://user-images.githubusercontent.com/53152008/81726948-81101780-9488-11ea-9eb0-27335bc5beff.jpg)

[log.txt](https://github.com/Stephan-S/FS19_AutoDrive/files/4617498/log.txt)

**Comment by game455** [comment]
Wichtig wäre noch die Info, ob du dem Abfahrer auf Seite 4 auch gesagt hast, ob er AD für unload/refill nutzen soll !?

**Comment by Iwan1803** [comment]
Ohne genaue Infos können wir das nicht verifizieren.
Wie ist die Einstellung für AD in CP und wie ist die AD-Feldausfahrtstrategie?

**Comment by Iwan1803** [comment]
Bitte 1.1.0.5-RC3 ausprobieren. Sollte das Problem dann noch bestehen, einfach ein neues Issue aufmachen.
