### ISSUE TITLE
[BUG] Duplicate Fruits/Crops

### ISSUE THREAD

**Issue by rooymans** [Stephan-S/FS19_AutoDrive#1424]
**AutoDrive Version:** 1.1.0.5_RC2
**Release or Custom Zip:** Custom Zip from Github  
**Map (If applicable):** Hof Bergmann 1.0.0.6  
**Vehicle / Type (If applicable):**   All
**Multiplayer or Singleplayer:** Singleplayer  

**Describe the bug**  
Why am I seeing duplicate fruit/crop types in the Loading/Unloading dropdown list?
And how do I know which one to select? For example, in the screenshot I see 4 Grass.
Nowhere else do I get 4 Grass. Not in any sell point, not in any silo.

Even if I l load the map without any other mods (except autodrive off course).
I assume it has to do with the filltypes.xml file. But I cannot find out exactly what the problem is.

**Screenshots**  
Attached
![Annotation 2020-05-13 205739](https://user-images.githubusercontent.com/56227140/81816377-d2d6a180-955d-11ea-9f33-02f0c33131f6.png)

**Comment by vertigoogle** [comment]
I think it's an issue of the Map, not AD.

**Comment by patch110** [comment]
Yes i believe it to be a map issue too

**Comment by Iwan1803** [comment]
It's a problem of the map, not of AD.
Same problem with the grass on the Nordfriesische Map.

**Comment by Iwan1803** [comment]
Please update to 1.1.0.5-RC5, try again and if the problem still exists, then open a new issue.
*Bitte aktualisiere auf 1.1.0.5-RC5, versuche es erneut und und wenn das Problem weiterhin besteht, erstelle ein neues Issue.*
