### ISSUE TITLE
[BUG]Anhänger entlädt nicht im Keilsilo beim rückwärts einfahren

### ISSUE THREAD

**Issue by Kerbisch89** [Stephan-S/FS19_AutoDrive#1425]
AutoDrive Version: 1.1.0.5 RC2
Release or selbsterstelltes zip: Release
Karte (falls relevant): NF Marsch 4 fach
Fahrzeug(art) (falls relevant): Häcksler abfahren mit Mais und Krone Ladewagen an Fendt 1050

**Beschreibe den Bug**
Beim Rückwärts abladen im Keilsilo (mod von FedAction) fährt der Traktor rückwärts ein, bleibt am Ende des Silos stehen aber entlädt den Anhänger nicht. 

Es ist möglich dann Manuel zu entladen, jedoch fährt der Traktor nicht weiter wenn nichts mehr aus dem Anhänger fällt.

**Falls anwendbar - Schritte mit denen ich den Bug nachstellen kann**

**Screenshots**
Falls relevant, bitte Screenshots beifügen

**Comment by Michael170978** [comment]
Verschiebe bitte den Enladehaltepunkt ein bisschen nach vorne bzw. nach hinten. Manchmal muss man nachjustieren damit der Tracktor entlädt.

Schau bitte  wie ich das mache

![fsScreen_2020_05_17_01_24_51](https://user-images.githubusercontent.com/53015927/82132195-797ca580-97dd-11ea-989c-860886892616.png)

**Comment by Knowen** [comment]
Moin,

ich habe das gleiche Problem.
Der Abladepunkt ist nicht ganz am Ende. Habe auch damit schon rumgespielt. Ganz egal wo der Punkt ist oder ob es der letzte Punkt vor der geradeausfahrt ist, er lädt nicht ab.

Er bleibt einfach so stehen, wie auf diesem Screenshot zu sehen:
![fsScreen_2020_05_21_16_19_22](https://user-images.githubusercontent.com/47173160/82568311-e5189700-9b7e-11ea-8af8-523e6503eab9.png)

Auch in der log wird kein fehler ausgegeben.

Grüße

**Comment by Michael170978** [comment]
Es kann sein dass da kein Trigger verbaut ist. Wenn AD aus ist, erscheint bei dir ein "I" fürs Abladen?

**Comment by Knowen** [comment]
Es ist ebenfalls die Nordfrisische Marsch.
Und nein, es taucht kein "i" fürs abladen aus. Hatte ich bisher bei keinem Keilsilo, egal ob Mod-Silo oder vom Spiel. Wenn ich einmal F5 drücke, sehe ich aber ein Rahmen um den Silobereich. Ich kann aber selbst dort abladen über strg+i. 
 
![fsScreen_2020_05_21_17_28_22](https://user-images.githubusercontent.com/47173160/82575252-7f310d00-9b88-11ea-9990-9142e69ebd30.png)

**Comment by Michael170978** [comment]
Wenn ein "I" nicht auftaucht, dann wird AD auch nicht entladen, weil kein Trigger erkannt wird.
Es wäre neu für mich, dass AD in der Lage ist überall zu entladen.

**Comment by Knowen** [comment]
Ich glaube in keinem einzigen Keilsilo oder Fahrsilo ist ein abladetrigger verbaut, der über "i" angesteuert wird.

**Comment by Michael170978** [comment]
Probiere bitte 1.1.0.5-RC3 aus

**Comment by Knowen** [comment]
Okay, mit der RC3 lädt er immerhin ab. Jedoch startet der Abladevorgang, sobald der Anhänger die "box" vom Silo berührt. Sieht dann so aus:
![fsScreen_2020_05_23_10_54_30](https://user-images.githubusercontent.com/47173160/82726350-d8618380-9ce3-11ea-84d2-444450ec8aef.png)

Nachm abladen fährt er dann noch rückwärts ins silo und dann zurück zum Hächsler.

**Comment by Michael170978** [comment]
Ich gebe es zu. Die neue Beta Version ist verbugt. Da läuft einiges nicht rund. Hab auch so meine Probleme.

**Comment by Kerbisch89** [comment]
Mit der RC3 Version funktioniert es nun...
Wie bei Knowen entlädt AD jedoch schon beim anfahren vor dem Silo. 

Nachdem ich den Bogen vor dem Rückwärtsfahren vom Silo weggeschoben habe funktioniert es. Er fährt an ohne den Trigger zu berühren, fährt dann rückwärts ins Silo und entlädt wie gewünscht.

An dieser Stelle auch tausend Dank für den Support, und sehr großes Lob für den, meiner Meinung nach, coolsten Mod im LS

**Comment by Knowen** [comment]
Dann werde ich das auch mal probieren und den Bogen anpassen.

**Comment by Iwan1803** [comment]
Ich habe gestern mit RC3 das große Doppelkeilsilo auf der NFM 4x angefangen zu befüllen und das ohne Probleme.
Vielleicht einfach mal hier reinschauen, wo ich es erkläre: https://youtu.be/RmgjiE58Vt8

**Comment by Williwillswisse** [comment]
Da Problem gelöst....
