### ISSUE TITLE
[BUG] Mode Pick up and deliver, wrong 1. target - Modus Abholen und Abliefern, falsches 1. Ziel

### ISSUE THREAD

**Issue by haamic** [Stephan-S/FS19_AutoDrive#1426]
AutoDrive Version: 1.1.0.5 RC 2
Release or selbsterstelltes zip: ReleaseCandidate
Karte (falls relevant): Alle
Fahrzeug(art) (falls relevant):

**Beschreibe den Bug**
Modus Abholen und Abliefern, beim Start von AD wird das Abladeziel angefahren, nicht der Abholpunkt

**Falls anwendbar - Schritte mit denen ich den Bug nachstellen kann**

**Screenshots**
Falls relevant, bitte Screenshots beifügen
![fehler abholen](https://user-images.githubusercontent.com/28841989/82112259-97012f00-974b-11ea-8a42-4017dc2f0cf5.jpg)

**Comment by Michael170978** [comment]
Das kommt manchmal vor. Schalte bitte Autodrive aus und wieder an dann sollte korrekt angezeigt werden. Den Fehler hab ich manchmal auch. Lässt sich aber damit leben.

**Comment by haamic** [comment]
was glaubst du, habe ich getan, bevor ich das gemeldet habe? Ohne Aus- und Einschalten hätte ich die screenshots nicht machen können.
leider funktioniert das bei mir nicht so wie bei dir. da ändert sich nichts. Werde mal ältere versionen bzw. die Beta testen, vielleicht finde ich ja eine bei mir noch funktionierende Version.

**Comment by 60erjonny** [comment]
@haamic 
Evtl. will hier AD vehement den kürzeren Weg wählen und fahren. Und der Abladepunkt eben näher zum Fahrzeig wie der Abholpunkt ist.
Klar ist das nicht optimal. 
Wie hoch hast du den Wert bei "Maximaler Umweg" eingestellt? 
Den Button "Weiterfahren" anklicken bringt auch nichts...?

**Comment by Michael170978** [comment]
@haamic Ist ja gut. Chill mal bißchen. Ich nutze die Version 1.1.0.5 RC 2 und da geht es. Und das nächste Mal versuch es mal bißchen netter zu schreiben. 

@60erjonny  In seinem Fall hat das nichts mit kürzeren Weg zu tun. AD denkt der Anhänger ist beladen, deshalb wird der Schlepper zum Abladeort anstatt zum Beladeort geschickt. Das kommt oft vor, Mann kann aber beheben, wie du geschrieben hast, entweder mit Weiterfahren Button oder ON/Off Button.

**Comment by Iwan1803** [comment]
Dies ist kein Bug von AD, sondern von Giants selber.
Da ist vermutlich an der 87. Nachkommastelle noch etwas im Hänger von der letzten Ladung drin.
Wenn es auftritt, dann versuch den Anhänger einfach mal zu entladen und starte dann AD.

**Comment by Iwan1803** [comment]
Please update to 1.1.0.5-RC5, try again and if the problem still exists, then open a new issue.
*Bitte aktualisiere auf 1.1.0.5-RC5, versuche es erneut und und wenn das Problem weiterhin besteht, erstelle ein neues Issue.*
