### ISSUE TITLE
[FEATURE REQUEST] Tipper type setting

### ISSUE THREAD

**Issue by SunkenL** [Stephan-S/FS19_AutoDrive#1427]
**Is your feature request related to a problem? Please describe.**

When i choose a "pickup and deliver" route with a tipper that have 2 different dumpchoices. In my case "back" and "grain door". If i choose to tip from graindoor and start the route, autodrive always changes it to "back" instead. This makes that when it comes to the salepoint the tipper hits the roof and gets stuck.

**Describe the solution you'd like**

I want to see that autodrive know that i choose the alternative "graindoor" instead.

**Describe alternatives you've considered**

I dont know if this problem maybe is the trailer or not but seems like it belongs here.

**Additional context**
no pictures.

**Comment by Iwan1803** [comment]
If you use a tipper, it raises the loading area even when using the grain slide.
So this sounds like nonsense....

**Comment by SunkenL** [comment]
Yes that is true, but it raises in different hights.. Point being, autodrive should remember what setting i selected.

**Comment by Iwan1803** [comment]
Same like here: https://github.com/Stephan-S/FS19_AutoDrive/issues/1380

**Comment by SunkenL** [comment]
yes seems like it yeah!

**Comment by Axel32019** [comment]
@SunkenL See here / Wenn Interesse hier entlang: #1663

**Comment by Iwan1803** [comment]
Da in 1.1.0.6 integriert, mach ich hier mal zu // Since integrated in 1.1.0.6, i'll close here 😎
