### ISSUE TITLE
[BUG] CP ->AD Filling up fertilizer-> Fertilizing on the way back to the field / CP ->AD Dünger auffüllen-> Düngen auf dem Weg zurück zum Feld

### ISSUE THREAD

**Issue by haamic** [Stephan-S/FS19_AutoDrive#1429]
AutoDrive Version: 1.1.0.5 RC 2
Release or selbsterstelltes zip: Release C
Karte (falls relevant): Alle
Fahrzeug(art) (falls relevant):

**Beschreibe den Bug**
CP düngt Feld, übergibt zum Auffüllen des Düngers an AD, AD fährt zum Auffüllen. Gleich nach dem Auffüllen wird schon wieder gedüngt, man verliert also Dünger auf dem Weg zurück zum Feld.
AD oder CP Fehler?
+++++++++++++++++++++++++++++++++++++++++++++++++++
CP fertilises field, transfers to AD for fertiliser filling, AD drives to fill up. Fertiliser is applied again immediately after filling, so you lose fertiliser on the way back to the field.
AD or CP error?

**Falls anwendbar - Schritte mit denen ich den Bug nachstellen kann**

**Screenshots**
Falls relevant, bitte Screenshots beifügen

**Comment by haamic** [comment]
Tensuko commented 21 minutes ago
Wenn AutoDrive auf dem weg zurück zum Feld den Düngerstreuer anmacht, ist das ein AD Fehler.

**Comment by Iwan1803** [comment]
Bitte auf den aktuellen RC3 aktualisieren und erneut probieren.

**Comment by haamic** [comment]
scheint jetzt zu funktionieren
