### ISSUE TITLE
[QUESTION] Multiple Targets

### ISSUE THREAD

**Issue by masneoquil** [Stephan-S/FS19_AutoDrive#1430]
I'm having a little problem unloading 2 combines on the same field.
I have 3 AD workers unloading both combines, but they almost always unload the first combine and only when the first one it is not waiting to unload, they go to the second one, to the point that the first one is already working on the up and down rows and the second is still on the headlands.
I think it has something to do with the setting Multiple Targets.
I have a folder with the target for that field, on both combines the same target is selected.
Multiple Targets is activated on all three unloaders.
Any help would be appreciated.  I'm with version 1.1.0.5 RC2

**Comment by Iwan1803** [comment]
Multiple Targets is only for changing the unload target. It has nothing to do with the thresher unloading.

Btw. in the new RC3 you can synchronize the multiple targets between the unloader.

**Comment by masneoquil** [comment]
Thanks Iwan. Will try RC3.
