### ISSUE TITLE
[FEATURE REQUEST] "FUELING Info" better perception/ separate display possible? - "TANKEN- Info" bessere Wahrnehmung/ gesonderte Einblendung möglich?

### ISSUE THREAD

**Issue by haamic** [Stephan-S/FS19_AutoDrive#1431]
**Is your feature request related to a problem? Please describe.**
no

**Describe the solution you'd like**

Hello, is it possible to make the information "Fill up the car" more visible?
Possibly a petrol pump logo or a display, like when you reach a destination, until you have filled up?
The information in the hud title bar is somehow very easy to miss.
E.g. the tractor was close to its destination and wanted to turn around, I was looking for something missing from the route network or if a destination name is wrong or double.
The hint that it only wants to refuel, I unfortunately saw only later.
++++++++++++++++++++++++++++++++++
Hallo, ist es möglich die Information "Fahre tanken" besser sichtbar zu machen?
Evtl. ein Zapfsäulen-Logo oder eine Einblendung, wie beim Erreichen eines Zieles, bis aufgetankt wurde?
Die Information in der Hud-Titelzeile ist irgendwie sehr leicht zu übersehen.
Z.b. stand der Traktor kurz vorm Ziel und wollte wenden, ich habe gesucht, ob irgendwo etwas am Streckennetz fehlt oder ein Zielname falsch oder doppelt ist.
Den Hinweis das er nur zum Tanken will, hab ich leider erst später gesehen.

**Describe alternatives you've considered**

**Additional context**

**Comment by Iwan1803** [comment]
Die Größe des HUD lässt sich in den AD-Einstellungen anpassen.
Wenn meine Flotte (>40 Fahrzeuge) mich alle Nase lang mit Tanken-Meldung zubomben würde, wäre das eher "suboptimal".

**Comment by haamic** [comment]
Es geht NICHT um die Größe des HUD und auch NICHT um die Größe DEINER Flotte, von der du sicher nicht alle gleichzeitig einsetzt und diese auch Nicht gleichzeitig tanken würden. Wenn ein Fahrzeug einen Zielpunkt erreicht hat , bekommt man doch auch eine Meldung gesondert angezeigt, das selbe ist doch sicher bei Beginn eines Tankkurses machbar. In deiner Schilderung kommt es auf ein paar Mehr Meldungen wegen Tankens nicht an. Ob nun 40 Meldungen erscheinen, das Fahrzeuge irgendwo angekommen sind, oder vielleicht 5 mehr,weil mal der der Kurs wegen Tankens unterbrochen wird, macht keinen Unterschied. 
Ich fände die Info extra zu zeigen, besser als nur in der Titelzeile des HUD. Das geht zu leicht unter, auch wenn das HUD noch so vergrößert wird. 
Wenn ich der einzige bin, der das nützlich findet, okay damit komm ich klar. Aber es könnten auch andere Nutzer das als hilfreicher empfinden. 
++++++++++++++++++++++++++++++
It is NOT about the size of the HUD and also NOT about the size of YOUR fleet, of which you certainly would not use all at the same time and would not refuel them all at the same time.  If a vehicle has reached a destination, you will also get a separate message, the same is certainly possible at the beginning of a refueling course.  In your description it does not depend on a few more messages because of refueling.  Whether 40 messages appear, that vehicles have arrived somewhere, or maybe 5 more, because the course is interrupted because of refueling, makes no difference. 
 
I think it would be better to show the information separately, better than just in the title of the HUD.  It goes under too easily, even if the HUD is enlarged. 
 
If I'm the only one who finds it useful, okay, I can handle that.  But other users might also find it more helpful.

**Comment by Iwan1803** [comment]
Warum gleich so erregt? Kannst du die Meinung anderer etwa nicht akzeptieren?
Es macht einen Unterschied, ob 5 oder 50 Fahrzeuge gleichzeitig oder in sehr kurzem Abstand tanken müssen. Jede Fahrt zum Tanken würde (nach deinem Wunsch) eine Einblendung erzeugen und in dieser Flut könnten ggfs. wichtigere Infos einfach übersehen werden.
Da AD das Tanken von Hause aus beherrscht, wäre vielleicht eine Info "wichtiger", wenn das schief laufen sollte, z.Bsp. weil die Tanke blockiert ist oder nicht mehr erreicht werden konnte.

**Comment by haamic** [comment]
Ich bin gar nicht erregt. du gehst einfach von dir und deiner Flotte aus. Wenn du es nicht brauchst, könntest du die Tank-Einblendung in den Einstellungen ausschalten, wenn es vielleicht doch so mal umgesetzt würde.  
Welche wichtige Information würde denn durch die zusätzliche Einblendung Deiner Meinung verloren gehen? 
Es war eine einfache Feature Anfrage an die Entwickler dies evtl mal zu überdenken. Jeder kann seine Meinung äußern, auch du. Alles gut.

**Comment by Axel32019** [comment]
Ist in Version 1.1.0.5-RC6 (23.09.2020) enthalten.
