### ISSUE TITLE
CombineUtil.lua:109: attempt to index local 'spec' (a nil value)

### ISSUE THREAD

**Issue by Mannie313** [Stephan-S/FS19_AutoDrive#1434]
AutoDrive Version: 1.1.0.5 RC3
Release or selbsterstelltes zip: selbsterstelltes zip:
Karte (falls relevant): Alle
Fahrzeug(art) (falls relevant):
Grimme FT300 und Rootster604 Kartoffelernte mit dem script FruitPreparerExtended.lua
**Beschreibe den Bug**
Eine klare Beschreibung des Bugs.

Wen ich auf Feld 23 den Fendt300 mit Grimme FT300 und Rootster604
über Couseplay starten will zum ernten von Kartoffeln kommt dieser fehler:

Error: Running LUA method 'update'.
F:/LS19_Mods/mods/FS19_AutoDrive/scripts/Utils/CombineUtil.lua:109: attempt to index local 'spec' (a nil value)

wen ich CP ausschalte geht es wieder.

mit der Version 1.1.0.5 RC2 klappt es.
**Falls anwendbar - Schritte mit denen ich den Bug nachstellen kann**

**Screenshots**
Falls relevant, bitte Screenshots beifügen
[log.txt](https://github.com/Stephan-S/FS19_AutoDrive/files/4662292/log.txt)

MFG Mannie313

**Comment by Mannie313** [comment]
https://ls-modcompany.com/filebase/file/736-multifruit-harvester-pack/

Da ist die lua mit drin.

MFG Mannie313

**Comment by Mannie313** [comment]
Ich hab nochmals getestet es liegt am Grimme Rootster604. egal ob original oder als mod. sobald ich CP ernten lassen will kommt der obere fehler.

MFG Mannie313

**Comment by Iwan1803** [comment]
Bitte lade 1.1.05.-RC4 herunter, versuch es erneut und poste dann ein Feedback.

Changelog: https://github.com/Stephan-S/FS19_AutoDrive/wiki/Release-Notes

**Comment by Mannie313** [comment]
[log.txt](https://github.com/Stephan-S/FS19_AutoDrive/files/4788374/log.txt)
ist leider immernoch der fehler drin

Error: Running LUA method 'update'.
F:/LS19_Mods/mods/FS19_AutoDrive/scripts/Utils/CombineUtil.lua:109: attempt to index local 'spec' (a nil value)

MFG Mannie313

**Comment by Iwan1803** [comment]
Ich konnte mit CP & AD gerade fehlerfrei Kartoffeln mit dem Vanilla-Ernter vom Feld holen.
Kann es an diesem "FruitPreparerExtended.lua" liegen, was du oben erwähnt hast?
Oder vielleicht an einem der anderen Mods, welche in die Fahrzeuge direkt eingreifen?

Hier hilft wohl nur ein Test mit dem Minimum an Mods, z.Bsp. nur mit CP & AD auf Felsbrunn.
Wenn das klappt, dann mal den Mod-Ernter dazu nehmen und testen.
Klappt das auch, dann den nächsten Mod, welcher irgendwie ins Fahrzeug eingreift.
Anders wird man dem Übeltäter wohl nicht auf die Schliche kommen....

**Comment by Mannie313** [comment]
Welchen enter hast du genommen.
Ich benutze den Grimme FT300 und Rootster604.

MFG Mannie313

**Comment by Iwan1803** [comment]
Wie oben geschrieben: den Vanilla-Ernter = Varitron 470

**Comment by Mannie313** [comment]
nimm mal den Grimme FT300 und Rootster604. und ernte zuckerrüben geht leider mit dem net. die anderen ernter gehen ja nur bis auf die zwei net. kann ja mal die anderen auch testen.

MFG Mannie313

**Comment by Iwan1803** [comment]
Please update to 1.1.0.5-RC5, try again and if the problem still exists, then open a new issue.
*Bitte aktualisiere auf 1.1.0.5-RC5, versuche es erneut und und wenn das Problem weiterhin besteht, erstelle ein neues Issue.*
