### ISSUE TITLE
Dedi-Server

### ISSUE THREAD

**Issue by JayT40** [Stephan-S/FS19_AutoDrive#1435]
AutoDrive Version: 1.1.0.5
Release Release
Karte (falls relevant): Alle
Fahrzeug(art) (falls relevant):

Hallo, wollten mal fragen, ob der mod für den dedi server ausgelegt ist, bei uns startet der Abfahrer nicht zum Drescher wenn der Füllstand erreicht ist, geh ich ins SP game funktioniert der Spielstand mit allen wie gewollt, auf dem Dedi-Server fährt der Abfahrer keinen Meter zum Drescher, egal was man in den settings wählt, ob 300m oder Feld auf der ganzen Karte finden. Am Abfahrer steht warten auf Ruf. Mfg

**Comment by Iwan1803** [comment]
Warum geben wir euch ein Template an die Hand, wenn es dann nicht ausgefüllt wird?

Ja, AD funktioniert auf Dedi-Servern, aber es scheint irgendwelche "Sonderfälle" zu geben, wo dies nicht der Fall ist.
