### ISSUE TITLE
Mehrere Trigger beladen / Load on multiple trigger

### ISSUE THREAD

**Issue by TripleX1978** [Stephan-S/FS19_AutoDrive#1437]
Es wäre hilfreich wenn man bei mehreren Triggern beladen könnte um bei einem Trigger abzuladen.
Also die Funktion "Mehrere Ziele" nur umgekehrt. 
Vielleicht sogar eine Kombination von "Mehrere Ziele" mit "Mehrere Startpunkte".

**Comment by Iwan1803** [comment]
Doppelter Request: https://github.com/Stephan-S/FS19_AutoDrive/issues/1347
