### ISSUE TITLE
Parkposition verlassen klappt nicht einwandfrei

### ISSUE THREAD

**Issue by TripleX1978** [Stephan-S/FS19_AutoDrive#1438]
**AutoDrive Version:** 1.1.0.5-RC2

Ich lassen z.B. einen Traktor mit Ladewagen rückwärts in eine Halle einparken. Wenn ich die Parkposition wieder verlassen möchte, fährt der Traktor erst wieder geradeaus bis zu dem Punkt wo er anfängt rückwärts in die Halle zu fahren, parkt dann nochmal rückwärts ein und verlässt anschließend auf dem richtigen Kurs die Halle.
Das passiert egal mit welcher Fahrzeuggröße oder -kombi. Jemand ne Idee wo der Fehler liegt?

Nachtrag:
Auch beim Einparken gibt es Probleme.
Versucht man einen Traktor mit Mähkombi einparken zu lassen, fährt dieser bis zu dem Punkt vor an dem er den Rückwärtsgang einlegt, fährt dann einen 90°-Bogen rückwärts und gibt an, dass es das Ziel erreicht hat.

![image](https://user-images.githubusercontent.com/63108228/82758948-fe714b80-9de9-11ea-92bb-9c433689d6d9.png)

**Comment by Michael170978** [comment]
Versuch nochmal bitte mit Version 1.1.0.5-RC3

**Comment by TripleX1978** [comment]
Danke für den Tipp. 
Beides funktioniert jetzt.
Jetzt habe ich aber das Problem, dass ich manuell nicht mehrere Wegpunkte mit Linien hintereinander setzen kann. Ich muss nach jedem Punkt den Modus kurz verlassen und dann den nächsten setzen.
Oder ist das jetzt so gewollt?

**Comment by Michael170978** [comment]
Du meinst, dass die Punkte miteinander  verbunden werden? Das hab ich auch. Ob das so gewollt ist das weiß ich nicht. Vielleicht gibt es eine neue Tastenkombination von der ich noch nicht weißt. In den Einstellungen hab ich nichts gefunden ob man umstellen kann.

**Comment by TripleX1978** [comment]
Ich vermute dass sich das mit der Version geändert hat.
Jetzt einfach im Editormodus Strg gedrückt halten und die Punkte der Reihe nach setzen.
Sind dann automatisch verbunden.

**Comment by TripleX1978** [comment]
Hab mich wohl zu früh gefreut.
Seit ein paar Tagen wieder das alte Problem.
Die Fahrer finden entweder gar nicht den Weg aus der Garage (fahren ein Stück vor und wieder zurück) oder sie fahren wieder geradeaus, dann wieder zurück in die Garage und dann erst den korrekten Weg.

**Comment by Michael170978** [comment]
Versuch es Mal die grüne Line außerhalb der Garage zu verbinden. Die grüne Line muss nicht mit dem Endpunkt verbunden sein. Also mit dem Endpunkt der Rückwärtslinie. Ich hoffe du verstehst was ich meine.

**Comment by TripleX1978** [comment]
Habs mal ausprobiert.
Leider ohne Erfolg.
Ich habe mittlerweile gegenüber ebenfalls Parkplätze eingefahren.
Jetzt ist es sogar so, dass der Fahrer bis in den gegenüberliegenden Parkplatz einfährt, anschließend rückwärts raus und die Strecke, die er eigentlich vorwärts fahren sollten (grüne Pfeile) komplett rückwärts fährt.

**Comment by Michael170978** [comment]
Das "hatte" ich auch mal. Ich überlege die ganze Zeit wie ich es gelöst hab. Ich glaube wenn du Anhänger dran machst dann ist es weg. Ist aber nicht die Lösung für das Problem. Komischerweise alle meine Schlepper fahren brav in die Garage rein. Was  ist dir noch vorschlagen könnte. Schau bitte daß die hell blaue Linie nicht auf der grünen Linie ist sondern ein bißchen versetzt.

**Comment by TripleX1978** [comment]
Hab es schon mit Anhänger ausprobiert. 
Die Position der Linien hatte ich auch schon geändert.
Es lief ja letztens ohne Probleme.
Nur jetzt nicht mehr und ich habe auch kein Update durchgeführt.

**Comment by Michael170978** [comment]
Schau dir bitte Issue #1461 an

**Comment by TripleX1978** [comment]
Wie soll mir das weiterhelfen?
Außer einer Fehlerbeschreibung steht da doch noch garnichts.

**Comment by Iwan1803** [comment]
Ich würde die Linen etwas auseinanderziehen, so das zwischen der grünen und hellblauen Linie etwas Luft ist. Auf den Screenshot sieht es zumindest so aus, als ob sie direkt übereinander liegen.
Bitte lade 1.1.05.-RC4 herunter, versuch es erneut und poste dann ein Feedback.

Changelog: https://github.com/Stephan-S/FS19_AutoDrive/wiki/Release-Notes

**Comment by TripleX1978** [comment]
Hatte die Linien vorher schon auseinandergezogen gehabt...da wurden die aber auch nicht angefahren. Werde die Tage mal die RC4 installieren und berichten.

**Comment by TripleX1978** [comment]
Habe RC4 installiert. 
Immer noch das Problem, dass die Fahrer zwar sauber in die Parklücke fahren aber diese nicht mehr verlassen. 
Ich habe mit den Linien folgendes ausprobiert:
- Vorwärtslinien direkt am Parkpunkt angeschlossen und diese mit den Rückwärtslinien überdeckend und auch nebeneinander angeordnet. 
- Die Vorwärtslinien außerhalb der Parkbucht an die Rückwärtslinien angeschlossen.

**Comment by Michael170978** [comment]
Ist es ein bestimmter Mod der zickt oder sind es auch Standardfahrzeuge?

**Comment by Iwan1803** [comment]
Am besten mal nur mit einem "nackten" Traktor (ohne jegliche Anbauten) testen.

**Comment by TripleX1978** [comment]
Ich habe jetzt mal folgende Konfigurationen mit Standardequipment ausprobiert.
1.) Traktor mit Anhänger - Ausfahrkurs außerhalb der Parkbucht an Rückwärtskurs angeschlossen
     --> Traktor fährt sauber rein, beim Verlassen aber geradeaus in die gegenüberliegende 
     Parkbucht.
2.) Traktor ohne Anhänger - Ausfahrkurs außerhalb der Parkbucht an Rückwärtskurs angeschlossen
     --> Traktor fährt sauber rein, beim Verlassen macht er direkt eine 180°-Drehung und fährt gegen 
     die Hallenwand
3.) siehe 2.) nur vor dem Verlassen den Traktor manuell ein Stück vorgefahren --> Traktor verlässt 
     die Parkbucht auf dem richtigen Kurs
4.) Traktor mit Anhänger - Ausfahrkurs an Parkposition in der Parkbucht angeschlossen
     --> Traktor fährt sauber rein, beim Verlassen aber geradeaus in die gegenüberliegende 
     Parkbucht.
5.) Traktor ohne Anhänger - Ausfahrkurs an Parkposition in der Parkbucht angeschlossen
     --> Traktor fährt sauber rein, verlässt die Parkbucht auf dem richtigen Kurs

Getestet wurde die linke Seite.
Es hatte vorher auch mal eine ganze Zeit mit der Konfiguration 4 funktioniert.
Ohne dass sich was geändert hat ging es dann plötzlich nicht mehr.

![LS19 - Screenshot 1](https://user-images.githubusercontent.com/63108228/85369767-00841280-b52e-11ea-81de-415eabb8ee49.jpg)
.

**Comment by Iwan1803** [comment]
Setz die Ausfahrt-Linie nicht am Ende der hellblauen Linie an, sondern an der Hallenausfahrt.
Dann sollte AD die Ausfahrt besser erkennen.

**Comment by TripleX1978** [comment]
Hatte ich auch schon erfolglos getestet...siehe 2.) und 3.)

**Comment by TripleX1978** [comment]
Hab jetzt die neue RC5 drauf.
Auch hier immer noch das gleiche Problem.
Könnte es evtl. damit zusammenhängen, dass ich die Parkenkurse nicht mit einem Fahrzeug eingefahren habe sondern manuell erstellt habe?
Habe z.B. beim Rückwärtskurs max. 4 Punkte gesetzt.
Am Wendepunkt, am Parkpunkt und dazwischen 2 um eine möglichst gerade Strecke zubekommen.
Dementsprechend sind natürlich die einzelnen Wegpunkte weiter voneinander entfernt.

**Comment by Iwan1803** [comment]
Kannst du noch mal einen aktuellen Screenshot posten?
Irgendwo scheint da einen Kinken drin zu sein.
Schau mal in mein Kompost-Video, denn da hatte ich das gleiche Problem:
https://www.youtube.com/watch?v=rPG37kTh_Z4

**Comment by TripleX1978** [comment]
Hab mir dein Video angesehen und meine Kurse sind eigentlich ähnlich aufgebaut.
Trotzdem fährt er immer wieder den falschen Kurs.
Hier nochmal ein Screenshot.

![LS19 - Screenshot 7](https://user-images.githubusercontent.com/63108228/87243723-97aafe80-c438-11ea-8568-cb480679d3dd.jpg)

**Comment by Iwan1803** [comment]
Versuch mal die erste grüne Linie etwas paralleler zur hellblauen zu machen.
AD sucht den Pfad mit dem "besten" Winkel.
![image](https://user-images.githubusercontent.com/47528836/87246442-e1521400-c44d-11ea-9802-e410a04bddb9.png)

**Comment by TripleX1978** [comment]
Hat leider auch nicht funktioniert.

**Comment by TripleX1978** [comment]
Hab jetzt nach längerer Pause nochmal neue Kurse inkl. Rückwärtsfahrt bei Produktionen eingefahren. 
Bei allen tritt das gleiche Problem auf dass der Traktor beim Verlassen der Ladeposition geradeaus fährt bis zu dem Punkt wo er von Vorwärts- auf Rückwärtsfahrt wechselt und sich von da irgendeinen Weg zum eigentlichen Kurs sucht.

**Comment by Iwan1803** [comment]
Da nun doppelt -> geschlossen.
