### ISSUE TITLE
[FEATURE REQUEST] For road network check, display route network on overview map (PDA-Map/ESC Menu Map)??? - Zum Strassennetz-check, Anzeige Streckennetz auf Übersichtskarte (PDA-Map/ESC-Menü Karte)???

### ISSUE THREAD

**Issue by haamic** [Stephan-S/FS19_AutoDrive#1439]
**Is your feature request related to a problem? Please describe.**

no

**Describe the solution you'd like**

Would it be possible to integrate a function to make the network of routes visible on the overview map?  It would help to complete the route network, as it would enable you to identify roads that have not yet been used.
+++++++++++++++++++++++++++++++++
Wäre es möglich eine Funktion einzubauen, das eingefahrene Streckennetz auf der Übersichtskarte sichtbar zu machen?  Es würde helfen, das Streckennetz zu komplettieren, da man so evtl. noch nicht eingefahrene Strassen identifizieren könnte.

**Comment by Iwan1803** [comment]
Gibt es doch schon und nennt sich Course Editor 😉

**Comment by haamic** [comment]
Sollte diese Antwort, ein schlechter Scherz sein, oder hast Du nur nicht richtig gelesen?
Im Titel steht worauf sich meine Anfrage bezieht. 
Zeig mir doch bitte mal einen Screenshot, wo auf der pda Map oder der großen Kartenansicht, mittels Course editor, das GESAMTE Straßennetz zu sehen ist, um evtl vergessene Straßen schnell zu identifizieren und noch einzufahren. Ohne alles nochmal selbst mühselig abzufahren.

**Comment by Iwan1803** [comment]
Ein schlechter Scherz? 🤨
Du weißt aber schon, was der Course Editor ist und wie er funktioniert, oder?

**Comment by raupach** [comment]
![Screenshot_20200526_221702](https://user-images.githubusercontent.com/490601/82946567-d9720980-9f9e-11ea-96d3-9e0b8b74eb38.png)

**Comment by haamic** [comment]
Meine Anfrage bezog sich auf die Möglichkeit im Spiel selbst das Netz nur anzeigen zu lassen. Nicht über eine externe Anwendung. 
Ohne Editiermöglichkeit, quasi nur ein ingame- "Viewer". So wie man sich die Zielpunkte auf der Karte anzeigen lassen kann. Nur mit allen Wegpunkten bzw. zusammengefassten Wegpunkten die innerhalb von X Metern liegen um nicht zu viele anzeigen zu müssen. 
Ähnlich der zuschaltbaren kursansicht in CP ("Auge"-Button), mit Kartenausschnitt und Kursverlauf

**Comment by Iwan1803** [comment]
Die Zielpunkte kann man ja eh sehen und nun kann man sich auch Sackgassen anzeigen lassen.
Davon abgesehen weiß ich nicht, ob die Ingame-Map so eine Möglichkeit überhaupt bietet oder ob man hier etwas extra programmieren müssen.
Welchen enormen Vorteil sollte das also bringen, das sich der Programmieraufwand lohnen würde?

**Comment by Axel32019** [comment]
No update -> Closed.
