### ISSUE TITLE
Include editing destinations in Course Editor

### ISSUE THREAD

**Issue by aviator64** [Stephan-S/FS19_AutoDrive#144]
How do I change the location of a target, other than deleting the node and recreating it?

Target markers also don't appear in the Editor or am I missing something?

**Comment by Bobster82** [comment]
@aviator64 , How do u mean change the location? Rename it or you want ur vehicle to another location?

Renaming the location can be done in the xml file located in ur savegame folder. (I dont know other way)

**Comment by aviator64** [comment]
I meant changing the target to a different node, not renaming it. 

It would be very helpful if you could see the named locations in the Editor and drag/drop them onto a different node.

**Comment by Bobster82** [comment]
So u have as example "Farm" as a waypoint (node?), but you want that one (name) replaced to another waypoint?
Only I know now is that i delete that waypoint and thus the name and create a new one where I want it

**Comment by aviator64** [comment]
OK thanks, I was hoping there was an easier way!

**Comment by Stephan-S** [comment]
Hey, thanks for your Input.
Ich will try to include destinations in the Editor soon.
If you Want to Change the Location in Game, you could map a Key in the Game menu Options to the function 'delete mapmarker' or something similiar (sorry, Not at my PC right now). This deletes the Destination but keeps the node.

**Comment by Soilaq** [comment]
Bound it to SHIFT + CTRL + ALT + DEL, makes it really neat.

**Comment by aviator64** [comment]
Thanks, I will try that!
