### ISSUE TITLE
Question: Where are the default routes stored?

### ISSUE THREAD

**Issue by MicaelJarniac** [Stephan-S/FS19_AutoDrive#1440]
For both of the default maps, Ravenport and Felsbrunn, there seem to be default routes included with AutoDrive, which is awesome.

But for some reason, yesterday when I created a new multiplayer game in Felsbrunn, the default route didn't appear, so I wanted to manually add it.

I tried searching in the mod files, even searching for the map names here in the repo, and I couldn't find where those default routes are.

So what I wanted to know is, where can I find those default route files inside the mod?

**Comment by eddiem54** [comment]
I think they were removed a few days ago.

**Comment by MicaelJarniac** [comment]
Oh, that would explain why the new save had no routes, and why I couldn't find them on the files. Thanks for the hint, I'll try downloading an older version to grab them, I guess.

**Comment by Mike1977** [comment]
But why would they remove them? It was a good example of how to lay out a network with both one way and two way lines. I learned a lot faster just by looking at how they did the crossroads and things like that...

**Comment by MicaelJarniac** [comment]
Maybe they plan to add it back? I mean, yeah, they were pretty useful, so I wonder whether they've removed them for now because they might be working on something before bringing them back.

**Comment by Iwan1803** [comment]
The routes were deprecated because they wre created with an very old AD version.
So we decided to remove them to avoid problems.

**Comment by MicaelJarniac** [comment]
> The routes were deprecated because they wre created with an very old AD version.

That answers my question, thanks!

> So we decided to remove them to avoid problems.

Is there something specific about them compatibility-wise that concerns the devs?

I mean, I'll most likely be copying them to my new saves manually, they're a pretty solid start IMO, so it'd be helpful to know about possible problems that may arise from this.

And I believe if there are major changes to the way routes are saved, it'd be possible to have a script that converts between the old and the new routes, something like the Course Editor, but that's capable of opening old routes and saving as new routes.

Anyways, thanks again for replying, and huge thanks for the awesome mod.

I've already been running around the map trying to "enhance" the no longer included routes. I'll see if I can create a repo for them and continuously enhance them to share with others. I think it'd help people that want a nice starting point, and that's about all I can do to help out for now, since my coding knowledge isn't quite there yet.

**Comment by Iwan1803** [comment]
There were a lot of changes in AD, especially in path finding and calculation.
Some of the routes were made with a car and so not usable with a wider or bigger vehicle.
We do not have the time to correct or recreate them all and using a script to do that is not possible.

F.e. i started to optimize the tracks on Felsbrunn. Just driving and correcting most of the routes took several hours + the time for deleting and re-recording (over 30 hours).

**Comment by MicaelJarniac** [comment]
Oh, I thought the changes were to how the routes are saved, that's why I suggested a script. But since that's not the case, my suggestion makes no sense.

I'll close this issue, thanks for the reply.
