### ISSUE TITLE
[FEATURE REQUEST] Local Traffic only node option

### ISSUE THREAD

**Issue by turtlbrdr** [Stephan-S/FS19_AutoDrive#1442]
I would like to request the ability to mark any specific node as a sub-priority or "local traffic only" node. The purpose of this marking would be to prevent traffic from passing that node unless there is no other way to access the destination behind it. 

I'm finding that as I'm setting up networks on maps (specifically GreenRiver and Fenton Forest), that I have some fields that are only accessible via smaller, dirt trail roads that do not have the ability to handle a separated two-way traffic network, thus I'm using a combined two-way network for these routes. 

However, because of the sheer amount of these roads, and more so due to the fact that they bridge between major roads, I'm finding that my other traffic (product hauling, etc.) is using these roads, instead of the traffic just to the fields. 

I want to recommend the idea of these local-only nodes as a way to still have these thinner farmer's roads, but not have to worry about intercepting traffic. 

I could see two ways of doing this.

First, the node designation would force the navigation algorithm to choose different routes when they are available, and only allow traffic past when it is the only way to get to the destination. The local-only routes would need nodes on all ends of that network portion for this to work, otherwise true local traffic would only route through the sides that are not local-only.

Alternatively, one could place the local-only nodes and then directly assign them to a specific destination (or destinations), and only traffic traveling to that destination would be allowed to pass.

**Comment by Iwan1803** [comment]
And then the non-field traffic might have to take huge detours?

**Comment by turtlbrdr** [comment]
Which is the intent. To keep non-field traffic off the small dusty roads which are only wide enough to be networked for single-lane traffic. Both to keep traffic from colliding, but also to keep, for example, my extremely large grain trucks from taking the small circuitous roads, and potentially wrapping themselves around a tree or falling off the side.

**Comment by Iwan1803** [comment]
Cost/benefit calculation: negative
It needs to much time to implement and makes the whole network unnecessarily complex.
