### ISSUE TITLE
Path nodes keep going underground.

### ISSUE THREAD

**Issue by Kringa** [Stephan-S/FS19_AutoDrive#1443]
![Yard at 6 1](https://user-images.githubusercontent.com/65901297/82810770-4b423a00-9e5d-11ea-929f-e4d49da445e1.jpg)
**AutoDrive Version:** 1.1.0.4   
**Release or Custom Zip:** Release  
**Map (If applicable):** All  
**Vehicle / Type (If applicable):**   
**Multiplayer or Singleplayer:** Singleplayer  

**Describe the bug**  
When I move nodes with the right mouse button, sometimes the nodes go deep underground, some can be deleted and some are just gone forever. And why are some nodes way above ground and some are at ground level?
Here is an equipment yard I made at Field 6. Is this too complicated for AutoDrive to handle?
![Yard at 6 1](https://user-images.githubusercontent.com/65901297/82810740-3665a680-9e5d-11ea-9438-bcb06cbe6dd6.jpg)
![Yard at 6 2](https://user-images.githubusercontent.com/65901297/82810743-36fe3d00-9e5d-11ea-9133-d3f393704aa2.jpg)
![subterranean Node](https://user-images.githubusercontent.com/65901297/82811611-2cdd3e00-9e5f-11ea-82c9-170b104f5d64.jpg)
![Sunken Nodes](https://user-images.githubusercontent.com/65901297/82811754-82194f80-9e5f-11ea-9153-a512850bb2a3.jpg)
![Uneven Nodes](https://user-images.githubusercontent.com/65901297/82811761-86456d00-9e5f-11ea-8fd0-92186432e513.jpg)

**If applicable - Steps to reproduce the behavior**  

**Screenshots**

**Comment by Iwan1803** [comment]
That was allready fixed in the RC which were released after 1.1.0.4.
So the problem should be gone if you update AD.
