### ISSUE TITLE
Mein Autodrive hat keine Rückwärts fahr Funktion

### ISSUE THREAD

**Issue by Crascher88** [Stephan-S/FS19_AutoDrive#1444]
Hallo

Ich wollte mal in meinem Aktuellen Spielstand eine Rückwärtsfahrroute einfahren aber.
Aber leider bleiben die Pfeile grün und nicht wie in den Video Tutorials blau. 
Auch wenn ich ein komplett neues Spiel starte mit nur dem AD Mod geht es nicht?
Woran kann es liegen?

Vielen Dank schon mal

**Comment by rmn18** [comment]
Haste die letzte Betaversion mal probiert ??

**Comment by Crascher88** [comment]
Ja mit der beta funktioniert es wieder danke
