### ISSUE TITLE
[BUG] AD doesnt unload Multiple Trailers

### ISSUE THREAD

**Issue by Mike1977** [Stephan-S/FS19_AutoDrive#1445]
**AutoDrive Version:** 1.1.x.x   
**Release or Custom Zip:** Release  
**Map (If applicable):** All  
**Vehicle / Type (If applicable):**   
**Multiplayer or Singleplayer:** Singleplayer  

**Describe the bug**  

Whenever i try to use multiple trailers it doesn't work. For example if i use CP for the combine and AD for unloading, the unloader actually fills every trailer, but it only unloads the first one and then stays there forever. Also when i use the load/unload mode for selling everything from my storage. The moment the first trailer reaches the pipe it load the first trailer, but then just drives away with all the other trailer beeing empty. If i remember right this was working once. But since i dont play very often, i can't remember wich version i had before i updated to the latest one.

**If applicable - Steps to reproduce the behavior**  

**Screenshots**

**Comment by Mannie313** [comment]
Kannst du mal ein bild mit eingeblendetem Streckennetz machen wo du entladen willst.

 MFG Mannie313

**Comment by Mike1977** [comment]
![AD-Bugreport](https://user-images.githubusercontent.com/5852750/82844905-92bed980-9ee2-11ea-8423-ff967647d3b1.jpg)
Hier sind beide Hänger leer, da ich gerade in der Nähe war, aber so bleibt der sonst immer stehen mit dem ersten Hänger leer und dem zweiten noch voll...

**Comment by TobiHH78** [comment]
Setz den Abladepunkt mal etwas weiter nach hinten. Ich vermute, du bist nach abladen des ersten Anhängers zu dicht daran, oder schon darüber hinaus.

**Comment by Mannie313** [comment]
Der Abladepunkt muss so weit weg sein das der zweite dtrailer im trigger steht dann geht es.

MFG Mannie313

**Comment by Mike1977** [comment]
Das heist, mit mehr als zwei Trailern geht das dann nicht? Denn ich kann den Abladepunkt ja nicht unbegrenzt hinter schieben...
Und ich schätze das gleiche gilt dann auch für das beladen am Silo?

**Comment by Michael170978** [comment]
Doch du kannst  unbegrenzt nach hinten schieben.  Beim Beladen ist es genau so. Je  weiter der Punkt vom Trigger entfernt ist desto besser.

**Comment by Iwan1803** [comment]
"unbegrenzt" ist falsch, denn es gibt in den AD-Einstellungen ja extra die Option für den Silo-Abstand (=Abstand zwischen Trigger und Zielpunkt).
Wie schon richtig angemerkt, muss der Zielpunkt soweit vom Trigger entfernt sein, das der 2. Anhänger dort entladen kann, ohne das der Zielpunkt schon erreicht wird.

**Comment by Mike1977** [comment]
Also sehe ich das richtig, das der Abladepunkt eigentlich garnichts mit dem Trigger zu tun  hat, sondern nur als Navigationsziel dient, wo halt einfach irgendwo zwischen Feld und dem Abladepunkt dann mal der Trigger kommen muss damit er die Hänger beim drüberfahren entleert, und wenn er an dem Ziel angekommen ist und feststellt das die Hänger leer sind, das er danneinfgach wieder auf das nächste Ziel umschaltet?
Theoretisch kann der Abladepunkt also auch 100 Meter hinter dem Trigger sein, falls man mal mit 4 Hängern abfahren muss?

**Comment by Iwan1803** [comment]
Zielpunkt - nicht "Abladepunkt" 😉
Aber ja, ist soweit korrekt.

**Comment by TobiHH78** [comment]
> Also sehe ich das richtig, das der Abladepunkt eigentlich garnichts mit dem Trigger zu tun hat, sondern nur als Navigationsziel dient, wo halt einfach irgendwo zwischen Feld und dem Abladepunkt dann mal der Trigger kommen muss damit er die Hänger beim drüberfahren entleert, und wenn er an dem Ziel angekommen ist und feststellt das die Hänger leer sind, das er danneinfgach wieder auf das nächste Ziel umschaltet?
> Theoretisch kann der Abladepunkt also auch 100 Meter hinter dem Trigger sein, falls man mal mit 4 Hängern abfahren muss?

Vorausgesetzt du hast in den Optionen den Siloabstand auf 100m eingestellt...

**Comment by Iwan1803** [comment]
Da kein weiterer Kommentar -> geschlossen.

**Comment by GitTomahawk** [comment]
> 
> 
> Ich habe den Fehler auch seit v1.1.0.4
> siehe #1304 und #1472
> Die max Siloabstand-Option oder der Abstand des Zielwegpunkts zum Abladetrigger spielt dabei keine Rolle.
> Der Fahrer hällt exakt am Abladetrigger an, aber er kippt nicht ab.

Wie ich schon erwähnt hatte habe ich den Fehler auch, Abstand zum Zielpunkt und Länge des Zuges spielen dabei keine Rolle.
Auch in der RC5 ist es nicht besser geworden.
