### ISSUE TITLE
Ausweichbucht  -  alternative bay - Nebenstrecken

### ISSUE THREAD

**Issue by wallsingham** [Stephan-S/FS19_AutoDrive#1449]
@Stephan-S
Hallo Stephan,

auf Karten mit engen, einspurigen Strassen wären **Ausweichbuchten** die Autodrive selbst als solche erkennt und **nur bei Bedarf** nutzt, eine sehr nützliche Sache.
Folgendes schwebt mir vor:
Von Punkt A zum Punkt B ist eine Blaue-Strecke eingefahren.
Die Strecke ist aber so lang dass bei viel Verkehr, Fahrzeuge an den Eingängen zu lange warten müssten bis die Strecke vom Gegenverkehr frei wird. 
Ist es möglich an einer oder mehreren Stellen im Verlauf der blauen Strecke A <---> B Ausweichbuchten anzulegen? Die Fahrzeuge nutzen diese dann nur bei Bedarf, ansonsten fahren sie die A <---> B  direkt durch, ohne Zeitverlust. Das Fahrzeug dass zuerst die Stelle mit der Ausweichbucht erreichen kann, plant seinen weg darüber und wartet dort bis das entgegenkommende Fahrzeug die Stelle passiert hat. 
Der Verkehr würde so deutlich schneller fliessen, vergliechen mit grünen Zwischenstücken. 

Bin mal gespannt was du davon hältst.

Viele Grüße
Hektor

![grafik](https://user-images.githubusercontent.com/56741972/82912389-5a181200-9f6d-11ea-9c54-012f54862e1f.png)

on maps with narrow, single-lane streets, alternative bays that Autodrive recognizes as such and uses only when needed would be a very useful thing.
I have the following in mind:
A blue route has been created from point A to point B.
However, the route is so long that if there is a lot of traffic, vehicles at the entrances would have to wait too long until the route is clear of oncoming traffic.
Is it possible to create alternative bays at one or more points along the blue route? The vehicles then only use them when necessary, otherwise they drive through the A <---> B directly, without wasting time. The vehicle that can first reach the alternative bay plans its way over it and waits there until the oncoming vehicle has passed the point.
The traffic would flow much faster, compared to green sections between the blue sections of A <---> B.

**Comment by Mike1977** [comment]
hast du schonmal probiert die buchten in jeweils beide richtungen als grüne strecke zu machen? dann fährt dort der verkehrt erstmal in jede richtung jeweils auf der rechten seite und die blaue strecke ist an der stelle unterbrochen so das beide teilstücke einzeln berechnet werden was den gegenverkehr angeht. zumindest in der theorie...

**Comment by Iwan1803** [comment]
Sehr kompliziert und extrem zeitaufwändig zu programmieren = der Zeitaufwand übersteigt deutlich den Nutzen und das um vielleicht 30-60 Sekunden Fahrzeit einzusparen anstatt vielleicht eher mal das Straßennetz zu optimieren?
Ja, ich bin kein Freund von blauen Linien (außer sie sind hellblau), da sie meistens mehr Probleme machen als zu helfen.

**Comment by wallsingham** [comment]
@Mike1977: so mache ich es ja zur Zeit und das funktioniert auch. Aber es ist eben nicht wiklich optimal wenn die Fahrzeuge an bestimmte Stellen Zickzackkurs fahren obwohl die Strasse leer ist. Daher dachte ich mir, ich frage mal Stephan ob das in seinem Konzept passt und sich dann auch mit dem jetzigen Berechnungsalgorithmus machen lässt.  Wir Nutzer und vor allem die Programierer sind ja wegen des Spasses und der Herrausforderung dabei. Zeit sparren könnten wir alle am besten durch's Deinstallieren des Spiels. ;-}
Bei Kreuzungen z.B. lässt sich der Verkehr mittels Kreisverkehr aus grünen Linien wunderbar regeln. Das entspricht dann auch Real-Verhältnissen. 

![grafik](https://user-images.githubusercontent.com/56741972/82939255-644d0700-9f93-11ea-9a1c-4ace1b6d5e97.png)

Bei engen Wegen wäre halt so eine Abzweigung die nur bei Bedarf genutzt wird, eine coole Sache.
Ich erstelle gerade ein Streckennetz für die Pagarusha map. Da sind die engen, schönen Waldwege überall und über lange Strecken zu finden. 
![grafik](https://user-images.githubusercontent.com/56741972/82941101-15ed3780-9f96-11ea-92c9-845b40e7684d.png)

**Comment by wallsingham** [comment]
@Iwan1803 tja die hellblauen sind wohl wirklich ein Highlight. da bin ich auch bei dir.
Apropos hellblauen Linien: Dein Promoting(leak)Video aus dem Fahrsilo zu der Rückfahrfunktion war insgesamt sehr gut platziert und sehr gut gemacht. Kompliment dazu 🥇

**Comment by wallsingham** [comment]
hier habe ich z.B. so eine Grüne-Linen-Unerbrechung eingebaut. 
Ich weis nicht wie ihr das findet aber ich finde es halt noch nicht optimal. 
![grafik](https://user-images.githubusercontent.com/56741972/82942290-04a52a80-9f98-11ea-9100-c1f0040c4230.png)

**Comment by Iwan1803** [comment]
Nicht schön und vielleicht noch etwas verbesserungswürdig, aber wenn es funktioniert....

**Comment by Matze9876** [comment]
An so eine Lösung dachte ich auch schon mal. Hat es denn funktioniert? 
Würde mich sehr interessieren.
👍

**Comment by wallsingham** [comment]
@Matze9876  Stephan hat dazu noch nicht's geschrieben.

**Comment by masneoquil** [comment]
I'm doing it that way and it works for the most part.
Some time if a traffic from both end happen to enter at the same time into the blue line they get stuck with each other, But a rare cases.

**Comment by Justice-Molton** [comment]
Ich fänd das auch super wenn man es wie beschrieben umsetzten könnte. Zu schreiben man soll sein Wegenetz optimieren ist wenig zielführend. Auf manchen Karten geht das einfach nicht.

**Comment by Iwan1803** [comment]
Ich übertreibe mal ein wenig:
weil Modder ihre Karten so komisch gestalten, soll das AD-Team Lösungen programmieren, obwohl es schon Möglichkeiten gibt, die Probleme zu umgehen?

> Sehr kompliziert und extrem zeitaufwändig zu programmieren = der Zeitaufwand übersteigt deutlich den Nutzen...

**Comment by Justice-Molton** [comment]
Merke schon, deine Aversion gegen Blaue Linien macht eine Sinnvolle Diskussion unmöglich. Manchen Leuten sind Karten wie NFNMarsch oder was auch immer Du gerade spielst, halt einfach zu langweilig. Wenn eine Karte schmale Wege hat, ist das mit Sicherheit kein Fehler, sondern gehört dahin. Aber anyways, dann nutzen wir halt AD nicht weiter und die Sache ist auch in Ordnung.

**Comment by Iwan1803** [comment]
Ja, ich mag blaue Linien nicht, aber das habe ich oben ja schon
geschrieben. Dennoch bin ich auch an einer Lösung interessiert, da es immer
wieder solche (speziellen) Karten geben wird, wo man Lösungen für braucht
und dabei spielt für mich im AD-Team keine Rolle, welche Karte ich spiele
oder bevorzuge. Für mich zählt nur, ob etwas für die breite Masse sinnvoll
und der Programmieraufwand gerechtfertigt ist. Also komm mir bitte nicht
mit "mit dir kann mir nicht diskutieren" und wenn du wegen der Ablehnung
dieser Umsetzung oder mir kein AD mehr nutzen möchtest, ist das deine
Entscheidung
AD hat auf jeden Fall schon eine Möglichkeit parat und das ist nun mal die
blaue Linie = beidseitig befahrbar. Wenn es da auf der Map nun einen Weg
gibt, welcher halt sehr lang ist, dann ist halt auch die blaue Linie so
lang. Auf dem ersten Screenshot von wallsingham
<https://github.com/wallsingham> ist ja eine Möglichkeit, so eine
Ausweichbucht mit grünen Linien zu erstellen. In der Realität würde man das
vermutlich auch so machen, ggfs. auch ein paar Bäume fällen wenn notwendig.

 Am Sa., 30. Mai 2020 um 17:39 Uhr schrieb Justice-Molton <
notifications@github.com>:

> Merke schon, deine Aversion gegen Blaue Linien macht eine Sinnvolle
> Diskussion unmöglich. Manchen Leuten sind Karten wie NFNMarsch oder was
> auch immer Du gerade spielst, halt einfach zu langweilig. Wenn eine Karte
> schmale Wege hat, ist das mit Sicherheit kein Fehler, sondern gehört dahin.
> Aber anyways, dann nutzen wir halt AD nicht weiter und die Sache ist auch
> in Ordnung.
>

**Comment by Justice-Molton** [comment]
Weil ich keine Zeit an etwas verschwenden will, was zu nichts führt. Ich aktzeptiere deine Meinung zu dem Thema und mache für mich einen Haken dran. Du bist ja schliesslich Stefan am nähstem und weisst was er vor hat und was nicht. Jedoch stelle ich mir eine Abfrage die das oben gewünschte erledigt, deutlich leuchter vor umzusetzten, als wie das rückwärts Silos befüllen. Aber da ich nicht tief genug im code stecke kann es auch sein das ich mich irre.

**Comment by wallsingham** [comment]
> 
> 
>  Am Sa., 30. Mai 2020 um 17:39 Uhr schrieb Justice-Molton: 
Merke schon, deine Aversion gegen Blaue Linien macht eine Sinnvolle
 Diskussion unmöglich. Manchen Leuten sind Karten wie NFNMarsch oder was
 auch immer Du gerade spielst, halt einfach zu langweilig. Wenn eine Karte
 schmale Wege hat, ist das mit Sicherheit kein Fehler, sondern gehört dahin.
 Aber anyways, dann nutzen wir halt AD nicht weiter und die Sache ist auch
 in Ordnung. 
.... Weil ich keine Zeit an etwas verschwenden will, was zu nichts führt. Ich aktzeptiere deine Meinung zu dem Thema und mache für mich einen Haken dran. Du bist ja schliesslich Stefan am nähstem und weisst was er vor hat und was nicht. Jedoch stelle ich mir eine Abfrage die das oben gewünschte erledigt, deutlich leuchter vor umzusetzten, als wie das rückwärts Silos befüllen. Aber da ich nicht tief genug im code stecke kann es auch sein das ich mich irre.


Ich bezweifele eigentlich dass Iwan selbst tief genug im Code steckt um Machbarkeit und Aufwand auch nur annähernd einzuschätzen.
An ihn habe ich eine ganz große persönliche Bitte:  
Für viele von uns die hier bei Github mitmachen, geht es eigentlich und den Reiz eines solchen Tools wie Autodrive in technischer Hinsicht. Man macht hier mit, sei es mit Bug-Meldungen, feature-request, Code, Grafik, Diskussionen um die Funktionalität usw. Fühle dich bitte nicht genötigt Antworten zu geben, wenn andere gefragt sind, bzw. wenn es halt um Fachfremde Inhalte geht.
Und bitte degradiere die Diskussionen nicht gleich in so eine Art Discounter Mentalität. Ein feature-request ist keine Aufforderung an niemand. Es ist ein Vorschlag den man sachlich diskutieren kann.

**Comment by Iwan1803** [comment]
Ich vergleiche diesen Request mit ähnlichen und ziehe daraus den Schluss, das es sicherlich machbar ist aber eine enormen Zeitaufwand benötigt. Mein Job hier ist auch keine endgültige Entscheidung, sondern eher eine Art Vorauswahl und Sichtung.
Davon abgesehen betrachte ich jeden Request neutral und führe die Diskussion sachlich. Wer Spaß nicht versteht oder Sarkasmus nicht erkennt: sorry, aber das geschriebene Wort kann man nun mal leicht missverstehen, was nicht meine Absicht ist.
Allerdings scheinen einige hier der Meinung zu sein, das Vorschläge sofort umgesetzt werden sollen/müssen und wenn dann eine Gegenstimme oder andere Meinung kommt, wird dies nicht akzeptiert. 
Sorry, aber wir sind hier nicht bei "wünsch dir was" und der Request bzw. das Problemchen kann ja auch anderweitig gelöst werden.
Der Request bleibt natürlich weiterhin offen.

**Comment by wallsingham** [comment]
Wenn man auch das Anliegen des issue #1442 mit einbezieht, wäre vielleicht auch folgendes denkbar:
1.	Bestimmte Strecken werden als „Neben-Strecken“ eingefahren.
2.	Aus der jetzt bereits vorhanden Option „Zielpunkte vermeiden“ wird „Zielpunkte und Nebenstrecken vermeiden“.
3.	Beim Pathfinding wird auch mit einer Teilreservierung einer blauen Linien gearbeitet und nicht wie bislang nur mit einer Vollreservierung. Also nicht wie bislang bis zum Ausgang der jeweiligen blauen Linie, sondern nur bis zur nächsten Ausweichbucht.

Wenn dann entlang einer blauen Linie solche Ausweichbuchten (eingefahren als Nebenstrecken) existieren, würde eines der Fahrzeuge sie nur dann benutzen wenn der direktere Weg zur Laufzeit besetzt ist. Die sich entgegenkommenden Fahrzeuge würden an den Ein- und Ausgängen der Nebenstrecken auf den Gegenwehr warten und nicht wie bislang an den Ein- und Ausgängen der Blauen Linien.

Ein weiterer Gedanke wäre dass Fahrzeuge sich eine Alternativroute versuchen zu errechnen, wenn sie wegen Gegenverkehr den Stop-Befehl bekommen.

**Comment by Iwan1803** [comment]
Aufwand-/Nutzenrechnung: negativ
Es kostet deutlich zu viel Progammieraufwand, um dies umzusetzen, zu mal es auch anders gelöst werden kann.

**Comment by wallsingham** [comment]
Hallo @Axel32019  erstmal danke dass du hier weiter entwickelst und das Projekt am laufen hälst. 
Ich habe heute die Map Dalberg angespielt und dort sind bei den engen Strassen überwiegend nur blaue Linen möglich. Daher möchte ich das Anliegen aus diesem issue noch mal hervorheben. Kannst du dir das mal bitte anschauen? 
Im Prinzip würde auch reichen wenn die Streckenreservierung, sofern sie über blaue Linien geht, immer nur bis zum ersten Streckenpunkt mit mehr als zwei Linien (Winkelunabhängig) gemacht wird. 

Wenn im Setup die Umfahrung für  "Zielpunkte" aktiviert ist wird dann die dort eingestellte Umfahrungsstreckenlänge für die berechnung der alternativen Routen verwendet, Bzw die beiden sich entgegenkommenden Fahrzeuge verständigen sich im Bedarfsfall.

Das ist jetzt nur ein grober Konzept. Ich kenne nicht die konkrette Funktionsweise des pathfinding Algorithm.
Ausweichmöglichkeinten für lange blaue Streckenabschnitte wären aber eine tolle Sache. Sie sind in real live auch unerlässlich. 

---------------------

Hello @ Axel32019 first of all thank you for developing further here and for keeping the project going.
Today I played the map Dalberg and there are mostly only blue lines possible on the narrow streets. Therefore I would like to emphasize the concern of this issue again. Can you take a look at that, please?
In principle, it would also be sufficient if the route reservation, provided it goes over blue lines, is only ever made up to the first route point with more than two lines (regardless of the angle).

If the bypass for "target points" is activated in the setup, the length of the bypass route set there is used to calculate the alternative routes, or the two oncoming vehicles communicate if necessary.

Now that's just a rough concept. I don't know how the pathfinding algorithm actually works.
Alternative options for long blue sections of the route would be a great thing. They are also essential in real live.
