### ISSUE TITLE
cornering speed

### ISSUE THREAD

**Issue by kwguk** [Stephan-S/FS19_AutoDrive#1450]
**AutoDrive Version:** 1.1.0.5RC2
**Release or Custom Zip:** Release  
**Map (If applicable):** All  
**Vehicle / Type (If applicable):**   All
**Multiplayer or Singleplayer:** Singleplayer  

I dont think its a bug its just whenever a vehicle approaches a junction or field entry or something similar the vehicle speed drops down to low single figures. I dont know wether this is deliberate or you can adjust the speed somehow but im finding it highly annoying.

Can you adjust the speed or is it actaully deliberate?

**Comment by Iwan1803** [comment]
The speed depends on the angles of the waypoints to each other and also if there is a targetpoint to be reached.
Driving too fast can cause problems, so driving slower as maybe possible should avoid this.
Can you post a screenshot to see the waypoints?

**Comment by Iwan1803** [comment]
As 1.1.0.5-RC4 was released and no further feedback was posted -> closed.
