### ISSUE TITLE
[BUG] Stuck in 'planning path' when unloading combine

### ISSUE THREAD

**Issue by kezarjg** [Stephan-S/FS19_AutoDrive#1451]
**AutoDrive Version:** 1.1.0.5 RC3   
**Release or Custom Zip:** Release  
**Vehicle / Type (If applicable):**   Various
**Multiplayer or Singleplayer:** Singleplayer  

**Describe the bug**  
When in unload combine mode, stuck in 'Planning path' mode. Path appears to be plotted, but the tractor never starts on the path.

**Screenshots**  
![2020-05-26](https://user-images.githubusercontent.com/6875139/82965639-ae83b780-9f96-11ea-96c0-b5aedcab5929.png)

**Comment by wallsingham** [comment]
@kezarjg Just deactivate the editor modus. Then the Vehicle will start driving

**Comment by kezarjg** [comment]
I only turned on editor to see the path. Deactivating the editor made no change. 

I have a similar instance in the Remote Debugger now. I'll try and collect more information.

**Comment by kezarjg** [comment]
Here's another.

![2020-05-27 (1)](https://user-images.githubusercontent.com/6875139/83168033-e564e500-a0de-11ea-9056-1cd8fa65748a.png)

It seems the isFinished is not set True (PathFinderModule.lua line 406), however the Debugger crashed on line 401 so I couldn't see why.

**Comment by kezarjg** [comment]
If I move ahead a bit, and restart AutoDrive, the path planning works as expected...

Is there a brief description of how currentCell & targetCell are used in this context? (PathFinderModule.lua lione 400 & 405).

**Comment by kezarjg** [comment]
It seems like a problem with this condition in line 400;
distanceFunc(self.targetCell.x - self.currentCell.x, self.targetCell.z - self.currentCell.z) < 1.5

From my observations, the difference in 'z' values will never allow that to be true.
targetCell(x,z) = targetCell(-32, -6) and the currentCell has z values 1,2, or 3.

**Comment by Iwan1803** [comment]
_Please download 1.1.05.-RC4, try again and then post a feedback._
Bitte lade 1.1.05.-RC4 herunter, versuch es erneut und poste dann ein Feedback.

Changelog: https://github.com/Stephan-S/FS19_AutoDrive/wiki/Release-Notes

**Comment by Iwan1803** [comment]
-> https://github.com/Stephan-S/FS19_AutoDrive/issues/1479

**Comment by Iwan1803** [comment]
Da 1.1.0.6 released wurde, mach ich hier mal zu // As 1.1.0.6 was released, i'll close here 😎
