### ISSUE TITLE
[QUESTION] Route Managers

### ISSUE THREAD

**Issue by Pyrjo** [Stephan-S/FS19_AutoDrive#1453]
Hi.

  I just wonder what the main function with save and load different routes. Because its possible to save one or more routes but why? The newer saves will always contain all of the old paths, if not deleted manually before save another one, if you know what I mean. 
  I would like to have the option to save the current network of waypoints and lines I have done on a map, then start from scratch again. Like if there was a "create new" function in Route Managers that clear all current lines and points.

  The main reason for this is that I often feel the need of an alternative set of routes on some maps where there is really tight corners. It would have been lovely to easy load another set of routes adapted for Trucks and other long vehicles and use the default set of routes with tractors and cars.
  Today I create parallell networks and destinations with the name "truck" in it so it takes that specific parallell routes, not the short-corner ones. But that way I need to do the job twice and get ALOT of lines messing corners up.

Thanks in advance for all info about this.

**Comment by Iwan1803** [comment]
If you save a route in the Route Manager, you can load it in every savegame of the same map.
If you load a route, you've need to restart the game.
There is no plan to include routes for "special" vehicles.

**Comment by Pyrjo** [comment]
Ah ok, now I got it, thanks alot. I can then start a new game of the same map, make a totaly new layout, save that as a new route, then have the possibility to chose when and if I start a 3rd game with same map. Or as you mentioned, load another route into an old saved game. To bad it needs a restart, but I think I get why it needs, because its in the map/save folder, not in the players local documents. Thanks again, but it would be awsome to be able to tag routes as "normal" and "extra long vehicles"

**Comment by Iwan1803** [comment]
Sorry, but we will not add waypoint markers for special vehicles or something like that.
