### ISSUE TITLE
[BUG] AD hands over to CP too early, after refueling at gas station - AD übergibt zu früh an CP, nach auftanken an Tankstelle

### ISSUE THREAD

**Issue by haamic** [Stephan-S/FS19_AutoDrive#1457]
AutoDrive Version: 1.1.0.5 RC3
Release or selbsterstelltes zip: Release C
Karte (falls relevant): Alle
Fahrzeug(art) (falls relevant):

**Beschreibe den Bug*
-Fahrzeug wurde mit AD zur feldarbeit geschickt (CP Button aktiv)
-da Tank fast leer fuhr es erstmal zur Tankstelle
-nach auftanken Startet AD direkt an der Tankstelle den CP Kurs. 
-AD übergibt also zu früh an CP, das sollte erst am eingestellten zielfeld passieren. 

**Falls anwendbar - Schritte mit denen ich den Bug nachstellen kann**

**Screenshots**
Falls relevant, bitte Screenshots beifügen

**Comment by Axel32019** [comment]
Should be fixed with de87a5c

**Comment by Iwan1803** [comment]
_Please download 1.1.05.-RC4, try again and then post a feedback._
Bitte lade 1.1.05.-RC4 herunter, versuch es erneut und poste dann ein Feedback.

Changelog: https://github.com/Stephan-S/FS19_AutoDrive/wiki/Release-Notes

**Comment by Iwan1803** [comment]
-> -> https://github.com/Stephan-S/FS19_AutoDrive/issues/1479

**Comment by Iwan1803** [comment]
Please update to 1.1.0.5-RC5, try again and if the problem still exists, then open a new issue.
*Bitte aktualisiere auf 1.1.0.5-RC5, versuche es erneut und und wenn das Problem weiterhin besteht, erstelle ein neues Issue.*
