### ISSUE TITLE
[BUG] AutoDrive doesn't hand over to Courseplay after finishing unloading course

### ISSUE THREAD

**Issue by tanordheim** [Stephan-S/FS19_AutoDrive#1458]
**AutoDrive Version:** 1.1.0.5-RC3   
**Release or Custom Zip:** Release (RC)  
**Map (If applicable):** Eiersholt
**Vehicle / Type (If applicable):** Fent 939 Vario with Fent Tigo XR 75 D loading wagon   
**Multiplayer or Singleplayer:** Singleplayer  

**Describe the bug**  

I have Courseplay set up with a mowing/loading course on field 6 on the map, and Courseplay is configured to use AutoDrive for unload/refill. AutoDrive  is in Pickup & Deliver-mode with Field 6 as the loading point and one of the BGA bunkers as the unloading point.

Everything is working fine; Courseplay is handing over to AutoDrive when the loading wagon is full, AutoDrive  is taking the tractor to the BGA where its unloading as expected and its returning to field 6. However, it seems to stop a tiny bit short of the actual Field 6 waypoint (see screenshots) and doesn't hand over to Courseplay to resume its course once its there.

**If applicable - Steps to reproduce the behavior**  

- Configure Courseplay with AutoDrive for unload/refill.
- Create Courseplay course on the field and use it for loading the loading wagon.
- Set up AutoDrive with the field entrance as the load point, a valid unloading point and grass as the 
fill type.
- Start the Courseplay worker, observe that it gets stuck after returning from unloading and that "Field 6" is still green in the AutoDrive HUD, implying its still on course I guess?

This is 100% reproducible with this course and the map I'm using. I'm taking a copy of the save game now just in case, before trying to tweaks things to see if I can get it running.

**Screenshots**  

Stuck at Field 6 waypoint without handing over to Courseplay:

![image](https://user-images.githubusercontent.com/49933/83260568-4e6d5b00-a1ba-11ea-9b83-5812ef9da620.png)

It might need to go a tiny bit more forward to reach the actual waypoint, or?

![image](https://user-images.githubusercontent.com/49933/83260952-e79c7180-a1ba-11ea-925e-95a55a5467bd.png)

The waypoints near the field in detail. AutoDrive is using "Closest Point" as field exit, and I have a two way track circling the field on the inside of the field border. At the field entrance waypoint I have entrances and exits from the main network ending up in a small part of two way track. The track circling the field has exits pointing toward the field entrance waypoint.

![image](https://user-images.githubusercontent.com/49933/83261408-8f19a400-a1bb-11ea-8b7a-0bef8eaf0226.png)

**Comment by tanordheim** [comment]
I did some tweaks on the field entrance by giving the tractor more space to turn and approach the waypoints from straight ahead. I also added another chunk of two way course after the waypoint before the exit paths come in, in the hope that it would allow the tractor to pull far enough forward that it could properly reach the waypoint:

![image](https://user-images.githubusercontent.com/49933/83263919-a064af80-a1bf-11ea-9999-304a3483dc52.png)

This had the effect that the tractor passed the field entrance waypoint and steered off to the right, doing a circle and coming back to the field entrance waypoint but this time a bit off center to the right.

![image](https://user-images.githubusercontent.com/49933/83264121-efaae000-a1bf-11ea-8c2e-1e3f20b88f31.png)
![image](https://user-images.githubusercontent.com/49933/83264155-fafe0b80-a1bf-11ea-93ce-2865287dfc2d.png)
![image](https://user-images.githubusercontent.com/49933/83264197-0b15eb00-a1c0-11ea-8b14-df1457dad6a8.png)

It kept doing this, each time it passed the field entrance waypoint it was more off center to the right than the previous until finally just crashing into a random tree:

![image](https://user-images.githubusercontent.com/49933/83264288-27b22300-a1c0-11ea-9b5b-1a024f3c35c3.png)
![image](https://user-images.githubusercontent.com/49933/83264349-3ac4f300-a1c0-11ea-8f10-24bac37ca98e.png)

Have I done something wrong by the way I've set up this junction at the entrance of the field here? My goal with setting it up like this is:

- The twoway path around the field allows me to connect multiple exits to a field and have the tractor choose the nearest and most sensible one using the "Closest" field exit.
- Only having exits connecting the path circling the field to the main network instead of twoway paths is done to avoid vehicles taking shortcuts over fields. I've had some problems on other fields on the map where I had twoway paths from the main network into the loop around the field which of course caused trailers and such to use those shortcuts across fields when calculating paths.

**Comment by tanordheim** [comment]
Some more testing in case any of this feedback is even remotely relevant:

- Changing connection from the loop around the field to the main network from exit only to two way had no effect, same behavior as before with driving in circles.
- Setting AutoDrive to the same mode (Load and Deliver), setting it to drive to Field 6 and starting Courseplay when it gets there work just fine; it arrives at the Field 6 waypoint and CP takes over. I'm running Courseplay v6.02.00023.
- Tried with a different tractor (Massey Ferguson  7726), same behavior.

**Comment by tanordheim** [comment]
With the latest 1.1.0.5-RC4.0 (as of 810d5bcdc94437acbc4fb5a0f22b786e905d4bf3) this seems to work just fine. Would you want this issue open for tracking in case it has any relevance, or should I close it?

**Comment by Bernardf57** [comment]
J'ai le même probléme.

**Comment by Iwan1803** [comment]
If problem is gone, then please close it.

**Comment by tanordheim** [comment]
I'd say this is resolved in 1.1.0.5-RC4.0, at least for my use-case - I don't know about @Bernardf57. I'll just close this and reopen another if I encounter the problem again later.
