### ISSUE TITLE
[BUG] Reverse driving to Trigger (multiple Targets) / Trigger rückwärts anfahren (mehrere Ziele)

### ISSUE THREAD

**Issue by Nealswiss96** [Stephan-S/FS19_AutoDrive#1459]
AutoDrive Version: 1.1.0.5-3
Release or selbsterstelltes zip: Release
Karte (falls relevant): NF 4x
Fahrzeug(art) (falls relevant): Universal Pack

Wenn der Trigger voll ist und "mehrere Ziele" ausgewählt, wird das nächste Ziel nicht angesteuert.  

Wie im Screenshot zu sehen fahre ich den Trigger rückwärts an. Trigger wird erkennt und es wird ausgeladen. Jedoch wird kein nächstes Ziel angewählt und er bleibt am vollen Trigger stehen, im gleichen Ausladeziel. 

![IMG_0137](https://user-images.githubusercontent.com/66141267/83301894-b2b00f00-a1fa-11ea-8072-d64ce329de7d.JPG)

**Comment by Axel32019** [comment]
Sollte mit 02bdf94 behoben sein.

**Comment by Iwan1803** [comment]
_Please download 1.1.05.-RC4, try again and then post a feedback._
Bitte lade 1.1.05.-RC4 herunter, versuch es erneut und poste dann ein Feedback.

Changelog: https://github.com/Stephan-S/FS19_AutoDrive/wiki/Release-Notes

**Comment by Nealswiss96** [comment]
Habe es gerade wieder getestet. Problem ist leider immer noch vorhanden. 

Ich meine im vergleich zum letzten mal bleibt er nicht mehr beim vollen Trigger stehen sondern fährt zum Abladepunkt. Dort angekommen wechselt er aber nicht zum nächsten Ziel.

**Comment by Iwan1803** [comment]
Immer noch die exakt gleichen Einstellungen wie auf dem Screenshot?

**Comment by Nealswiss96** [comment]
Ja habe immer noch die gleichen Einstellungen.

**Comment by Iwan1803** [comment]
Please update to 1.1.0.5-RC5, try again and if the problem still exists, then open a new issue.
*Bitte aktualisiere auf 1.1.0.5-RC5, versuche es erneut und und wenn das Problem weiterhin besteht, erstelle ein neues Issue.*
