### ISSUE TITLE
course play and AutoDrive

### ISSUE THREAD

**Issue by ploughedfieldman123** [Stephan-S/FS19_AutoDrive#146]
is there a problem when harvesting  with Course Play and AutoDrive  as when combine gets to 100%  the pipe wont open so there-fore tractor wont go to empty it

**Comment by Stephan-S** [comment]
Which version of Courseplay are you using? Please use the latest version and if the issue remains, feel free to talk about this issue in the responsible issue: 
https://github.com/Courseplay/courseplay/issues/3792
Thank you

**Comment by ploughedfieldman123** [comment]
Hi Stephan-S   I have latest version of course play  version 6.01.00224  which I believe is the latest, but still when combine gets to 100% it just seems silly as it reverses back weird. and stops but no pipe comes out then it just turns off as you can see in the picture

<a href="https://ibb.co/chzvG8b"><img src="https://i.ibb.co/gZs75Wv/CPAD.jpg" alt="CPAD" border="0"></a>
