### ISSUE TITLE
[BUG] Issue with unloading if you use more than one trailer

### ISSUE THREAD

**Issue by Mike1977** [Stephan-S/FS19_AutoDrive#1460]
Wenn man mehr als einen Anhänger nutzt, berechnet AD den Pfad nicht so, das der zweite, dritte ect Hänger überhaupt unter das Rohr kommen, und fährt so immer in einer Schleife.
Idealerweise sollte AD erkennen wie viele Anhänger am Abfahrer dran sind, und dann entsprechend weiter hinter dem Combine wenden.
![AD_Bugreport 1](https://user-images.githubusercontent.com/5852750/83340280-7e118580-a2d6-11ea-920d-f4678fbcf542.jpg)
![AD_Bugreport 2](https://user-images.githubusercontent.com/5852750/83340282-823da300-a2d6-11ea-998e-31b90585ce7c.jpg)
![AD_Bugreport 3](https://user-images.githubusercontent.com/5852750/83340283-84076680-a2d6-11ea-8381-36cb2dbfb8a2.jpg)
![AD_Bugreport 4](https://user-images.githubusercontent.com/5852750/83340284-8964b100-a2d6-11ea-9b03-589ea08442fd.jpg)

**Comment by Iwan1803** [comment]
_Please download 1.1.05.-RC4, try again and then post a feedback._
Bitte lade 1.1.05.-RC4 herunter, versuch es erneut und poste dann ein Feedback.

Changelog: https://github.com/Stephan-S/FS19_AutoDrive/wiki/Release-Notes
