### ISSUE TITLE
Rückwertsfahren mit IT-Runner[BUG]

### ISSUE THREAD

**Issue by Hanslimaa** [Stephan-S/FS19_AutoDrive#1461]
AutoDrive Version: 1.1.0.5-RC3
Release or selbsterstelltes zip: Release
Karte (falls relevant): Multimap
Fahrzeug(art) (falls relevant): LKW mit Abrollcontainer (Verschieden Mods, MAN und Scania)

**Beschreibe den Bug**
Der LKW Fährt nicht Rückwärts wenn ein Abrollcontainer geladen ist, er wendet. Wenn das Fahrzeug keinen Abrolcontainer geladen hat, fährt es korrekt Rückwärts. 
![fsScreen_2020_05_30_22_37_56](https://user-images.githubusercontent.com/66185982/83340383-7e5e5080-a2d7-11ea-9796-1ccc2dbe2378.png)
Hier fährt der LKW korrekt rückwärts.

![fsScreen_2020_05_30_22_39_38](https://user-images.githubusercontent.com/66185982/83340385-81594100-a2d7-11ea-893a-f527dc99b123.png)
Hier versucht der LKW zu wenden.

**Falls anwendbar - Schritte mit denen ich den Bug nachstellen kann**

**Screenshots**
Falls relevant, bitte Screenshots beifügen

**Comment by Iwan1803** [comment]
_Please download 1.1.05.-RC4, try again and then post a feedback._
Bitte lade 1.1.05.-RC4 herunter, versuch es erneut und poste dann ein Feedback.

Changelog: https://github.com/Stephan-S/FS19_AutoDrive/wiki/Release-Notes

**Comment by Iwan1803** [comment]
-> https://github.com/Stephan-S/FS19_AutoDrive/issues/1479
