### ISSUE TITLE
[QUESTION] Wheels don't leave tracks:)

### ISSUE THREAD

**Issue by ArtV-Nef** [Stephan-S/FS19_AutoDrive#1462]
**AutoDrive Version:** 1.1.0.5-RC3

Good day! The question is not significant, but why does AutoDrive not leave traces? And is there any way to fix it?:)
p.s. I don't know how to fix the label, sorry.

**Comment by Iwan1803** [comment]
AD only drives the vehicle and has no influence on tracks/traces.

**Comment by ArtV-Nef** [comment]
I certainly understand that this function is cosmetic, is it possible to enable it? Or you can add it to the settings menu. I want to make the game more realistic, although of course, AutoDrive is the best mod for FS 19.

**Comment by Iwan1803** [comment]
Again: this is nothing AD is responsible for.
It's a map or terrain feature.

**Comment by masneoquil** [comment]
Hello Iwan.
I did the same question CP github as a suggestion.
I think it have to do with the fact the crop destruction is turned off when an AI is in control of the vehicle. Correct me if i'm wrong.
I tested with CP, AD and de default AI on a default map an none leaves tire tracks on the ground.
I suggested an option to turn crop destruction on if it is possible and if it is in facto the reason for this issue.

**Comment by Iwan1803** [comment]
My AD driven vehicles are leaving traces on the road and elsewhere, crop destruction is off.
So again this seems to be not an AD, CP or AI problem.
Do you see tyre traces if you drive by yourself?

**Comment by Iwan1803** [comment]
I can't this entry in any of my XML.

**Comment by ArtV-Nef** [comment]
Yes, if I'm driving on my own-the tracks are visible, if I'm driving AD-there are no tire tracks.
