### ISSUE TITLE
[BUG] MP: Probleme mit dem Editor Modus 2

### ISSUE THREAD

**Issue by Easton97-Jens** [Stephan-S/FS19_AutoDrive#1463]
AutoDrive Version:1.1.0. 5R3
Map: NF_Marsch4fach oG
Multiplayer 

 Problem mit dem zweiten Editor Modus extrem habe wenn er eingeschaltet ist kann ich nicht in den Modus wechseln
Was in diesem Video gezeigt wurde https://www.youtube.com/watch?v=fLwklR1SERA&t=1989s 
Und ich muss die STRG Taste gedrückt halten Das ganze ist mir bei 4players (server Anbieter) und auf einem privat gehosteten Server aufgefallen. Das Phänomen dass ich  den Editor Modus nur rein komme , wenn der  zweiten Editor Modus ausgeschaltet ist. Ich muss strg Taste gedrückt halten um die Punkte zu verschieben.

Mich kann mann auf Discord unter Easton97 vinden. Ich könnte euch generell auf den Server lassen privat kein Problem mit dem anderen müsste ich das abklären
über eine Antwort würde ich mich freuen.

**Comment by TobiHH78** [comment]
Das ist doch genau so gedacht, dass man die STRG-Taste gedrückt halten muss. Finde ich gut so, wie es ist.

**Comment by Easton97-Jens** [comment]
Mir ist aufgefallen dass der zweite Editor Modus sich nicht mehr ausschalten lässt wenn man inden normalen Singel Player gearbeitet hat kann man ihn auf dem Server nicht mehr ausschalten da ist es egal ob mann in den Einstellungen an oder aus geschaltet hatt

**Comment by Iwan1803** [comment]
siehe: https://github.com/Stephan-S/FS19_AutoDrive/issues/1510

**Comment by Axel32019** [comment]
Neuer Editor-Modus in 1.1.0.5-RC6
