### ISSUE TITLE
[BUG] Several drivers on one tractor

### ISSUE THREAD

**Issue by Gonimy-Vetrom** [Stephan-S/FS19_AutoDrive#1464]
**AutoDrive Version:** 1.1.0.0 
**Release or Custom Zip:** Release  
**Map (If applicable):** All  
**Vehicle / Type (If applicable):**   
**Multiplayer or Singleplayer:** Singleplayer  

I use the HelperAdvanced mod https://github.com/BlackyBPG/FS19_HelperAdvanced. With it, I noticed that when the driver I hired through AutoDrive got stuck, AutoDrive again tries to hire a new driver, but does not dismiss the previous one. And so there can be several drivers on one tractor. As I understand it, they get a few salaries. This does not happen with Courspley and the ordinary employee. Only with Auto Drive.

**Comment by Axel32019** [comment]
Could you please test it with a newer version than yours: https://github.com/Stephan-S/FS19_AutoDrive 
If issue still exist please feedback here - Thanks.

**Comment by Gonimy-Vetrom** [comment]
Yes. I am using the latest version 1.1.0.5. The problem has not been resolved.

**Comment by wallsingham** [comment]
Hello @Axel32019 i have just tested with the actual Beta Branch 1.1.0.5-RC5 (Latest commit 6b765ed ) The issue still exist. 
If you need any specific details let me know
![grafik](https://user-images.githubusercontent.com/56741972/84815221-03a16f00-b013-11ea-804a-ebc54bbcf9ea.png)

**Comment by wallsingham** [comment]
Ich habe gerade auch folgendes beobachtet 
Es sind 18 Helfer eingestellt.
Ich schalte bei einem Fahrzeug AD aus. > Es kommt die Meldung: "Autodrive hat eine neuen Hlefer eingestellt". Die Gesamtzahl der Helfer bleibt gleich und auch deren beschäftigungsstatus.
Dieses Verhalten lies sich beleibig offt reproduzieren.
Soeben habe ich einen 19. Helfer eingestellt und obiges kommt jetzt nicht mehr vor.

**Comment by wallsingham** [comment]
Wo wir schon bei HelperAdvanced sind.
Falls die beiden Mods sich austauschen könnten, könnte AD immer den jenigen Helfer einstellen der die höchste Erfahrung bei "Andere" besitzt und die Niedrigste Durschnitserfahrung bei allen anderen Feldarbeiten. So würde sozusagen vermieden werden, dass ein erfahrender Drescher-Fahrer im LKW sitzt und der LKW-Fehrer im Drescher sich neu erfindet.

**Comment by Axel32019** [comment]
Aus meiner Analyse ist die Meldung "Autodrive hat eine neuen Helfer eingestellt" kein Fehler, nur das ein neuer freier Helfer beschäftigt wurde, jedoch bin ich nicht der Experte für diesen Mod.
Siehe:
		HelperAdvanced:hireHelper(newSelectedHelperId,true,g_helperManager.indexToHelper[newSelectedHelperId].isLearning,g_helperManager.indexToHelper[newSelectedHelperId].isLearnSpec,startedFarmId,noEventSend)
				g_helperManager.showAutoEmployed = true

**Comment by Axel32019** [comment]
Falls die beiden Mods sich austauschen könnten, könnte AD immer den jenigen Helfer einstellen der die höchste Erfahrung bei "Andere" besitzt und die niedrigste Durschnitserfahrung bei allen anderen Feldarbeiten.
Wie soll das gehen? AD unterscheidet nicht zwischen Drescher und LKW, wenn soetwas gemeint ist.

**Comment by wallsingham** [comment]
Hallo @Axel32019 

> ist die Meldung "Autodrive hat eine neuen Helfer eingestellt" kein Fehler. 

Die Meldung kam bei mir als ich **Autodrive ausgeschaltet haben**. Beim Einschalten ist die Meldung sicherlich kein Fehler. 

Aber um ehrlich zu sein, konnte ich nicht genau feststellen unter welchen Umständen genau die Fehlkommunikation beider Mods beginnt. Wenn jemand aber jemand sich mal die Sache vormihmt, helfe ich gern und teste intensiver. 

> Falls die beiden Mods sich austauschen könnten, könnte AD immer den jenigen Helfer einstellen der die höchste Erfahrung bei "Andere" besitzt und die niedrigste Durschnittserfahrung bei allen anderen Feldarbeiten.
> Wie soll das gehen? AD unterscheidet nicht zwischen Drescher und LKW, wenn soetwas gemeint ist.

Eine Unterscheidung zwischen Drescher und LKW ist nicht notwendig. Bei Autodrive gehts ja immer um's Fahren und in keinem Modus um irgendwelche Feldarbeiten. Das Ziel ist also die Spezialisten für Feldarbeiten möglichst frei zu lassen.

**Comment by Gonimy-Vetrom** [comment]
We deviated from the main problem!

wallsingham your offer is very interesting, but even Coursplay (but only a standard employee) cannot cope with the choice of an employee with high experience.

**Comment by wallsingham** [comment]
Hello @Gonimy-Vetrom 
yes you are correct. First, it has to work properly. Then the range of functions can be expanded.
My "offer" related to both concerns. But certainly primarily on fulfilling the error-free function. There is still no reaction from the developer of the HelperAdvanced :-(


> even Coursplay cannot ....

I've been using often AIVE instead of CP in the last time. In AIVE (by the way) you can manually select one of the helpers from the pool.

**Comment by Axel32019** [comment]
Hello @Gonimy-Vetrom,
Back to topic:
I looked into AD and CP how the drivers are hired and see no big difference.
How do you figure out that there are several drivers on one tractor?
Do you not see several drivers on one tractor with CP?

**Comment by Gonimy-Vetrom** [comment]
This happens when the driver does not see the collision and encounters it. It starts to slip. And at that moment AD is hiring new drivers. After that, I can fire only the last driver. Now I can control the tractor myself, but somehow, other workers are also sitting on it (they are not visible visually), and probably each of them gets a salary.
This does not happen with the CP. If the driver is stuck, he reports this but does not call others to help :), only me. Therefore, I decided that in AD there was some way to hire drivers.

PS: Can a notification be added to the AD that the driver is stuck?

**Comment by wallsingham** [comment]
I have isolated a case where the error can easily be reproduced. Simply place a vehicle in front of an obstacle and activate AD.
3 helpers were hired within 2 minutes. > See the corresponding excerpt from the log.

> 2020-06-24 23:30   Info: AutoDriveStartStopEvent
2020-06-24 23:30   Info: TX 32: [AD] ADTrailerModule:isActiveAtTrigger self.isLoading false self.isUnloading false
2020-06-24 23:30   Info: nil
2020-06-24 23:30   Info: nil
2020-06-24 23:31   Info: TX 32: handleBeingStuck
2020-06-24 23:31   Info: TX 32: [AD] PickupAndDeliverMode:reset set STATE_INIT
2020-06-24 23:31   Info: AutoDriveStartStopEvent
2020-06-24 23:31   Info: AutoDriveStartStopEvent
2020-06-24 23:31   Info: TX 32: [AD] ADTrailerModule:isActiveAtTrigger self.isLoading false self.isUnloading false
2020-06-24 23:31   Info: nil
2020-06-24 23:31   Info: nil
2020-06-24 23:31   Info: TX 32: handleBeingStuck
2020-06-24 23:31   Info: TX 32: [AD] PickupAndDeliverMode:reset set STATE_INIT
2020-06-24 23:31   Info: AutoDriveStartStopEvent
2020-06-24 23:31   Info: nil
2020-06-24 23:31   Info: AutoDriveStartStopEvent
2020-06-24 23:31   Info: TX 32: [AD] ADTrailerModule:isActiveAtTrigger self.isLoading false self.isUnloading false
2020-06-24 23:31   Info: TX 32: [AD] PickupAndDeliverMode:reset set STATE_INIT
2020-06-24 23:31   Info: AutoDriveStartStopEvent
2020-06-24 23:31   Info: nil
2020-06-24 23:31   Info: nil

Attached below the log and a small screenshot for illustration.
[log - Kopie.txt](https://github.com/Stephan-S/FS19_AutoDrive/files/4828050/log.-.Kopie.txt)
![grafik](https://user-images.githubusercontent.com/56741972/85630189-8a89c380-b673-11ea-89e3-15bd739b6190.png)

**Comment by Axel32019** [comment]
@wallsingham Danke für das Szenario zum Nachstellen - hat mir einiges an Zeit gespart um am Fix zu arbeiten!
Now I switch back to english, so @Gonimy-Vetrom could also follow.
This issue is the missing of the function calls helperManager:useHelper / helperManager:releaseHelper, which I will add according to the Giants Interface, see https://gdn.giants-software.com/documentation_scripting_fs19.php?version=script&category=26&class=10067
It will solve the message "Autodrive hat eine neuen Helfer eingestellt", which will not appear.
In my tests there are still a number of helpers listed as hired in the HelperAdvanced mod.
This mod overrides many / all standard Giants API functions and has to take care of the correct handling of the hired / not hired helpers.
So please also contact the modder(s) of HelperAdvanced mod to fix this.
There is nothing more we can do from AD side.

**Comment by wallsingham** [comment]
👍 @Axel32019 Klasse Arbeit und super schnell umgesetzt. *Schulterklopf 👍 
Ich habe AD ab dem Commit noch mal runtergeladen und werde testen.

**Comment by wallsingham** [comment]
Hello @ Axel32019
for me the commit a9a7da0 doesn't seem to solve the problem. It is of course also possible that HelperAdvanced does not correctly read the current status and present a wrong overview ....
The "error" occurs only when AD realizes that it is hanging somewhere and then a kind of FallBack function runs.
What I haven't tested yet, is what happens when AD passes to CP or AIVE.

Speaking of AIVE; can you see in which way AIVE hires the helpers or in which file the call is?

**Comment by wallsingham** [comment]
Ich habe jetzt auch die Übergabe AD>CP und AD>AIVE
In beiden Fällen entlässt AD fehlerfrei seinen Helfer und CP oder AIVE stellen dann selber ihren Helfer ein.
Es muss also an die Reihenfolge der Aktionen die ablaufen wenn AD nicht weiterkommt. 

> **2020-06-26 15:58   Info: 1300DT: handleBeingStuck**
2020-06-26 15:58   Info: 1300DT: [AD] PickupAndDeliverMode:reset set STATE_INIT
2020-06-26 15:58   Info: AutoDriveStartStopEvent
2020-06-26 15:58   Info: AutoDriveStartStopEvent
2020-06-26 15:58   Info: 1300DT: [AD] ADTrailerModule:isActiveAtTrigger self.isLoading false self.isUnloading false
**2020-06-26 15:58   Info: 1300DT: handleBeingStuck**
2020-06-26 15:58   Info: 1300DT: [AD] PickupAndDeliverMode:reset set STATE_INIT
2020-06-26 15:58   Info: AutoDriveStartStopEvent
2020-06-26 15:58   Info: AutoDriveStartStopEvent
2020-06-26 15:58   Info: 1300DT: [AD] ADTrailerModule:isActiveAtTrigger self.isLoading false self.isUnloading false
**2020-06-26 15:58   Info: 1300DT: handleBeingStuck**
2020-06-26 15:58   Info: 1300DT: [AD] PickupAndDeliverMode:reset set STATE_INIT
2020-06-26 15:58   Info: AutoDriveStartStopEvent
2020-06-26 15:58   Info: AutoDriveStartStopEvent
2020-06-26 15:58   Info: 1300DT: [AD] ADTrailerModule:isActiveAtTrigger self.isLoading false self.isUnloading false
**2020-06-26 15:59   Info: 1300DT: handleBeingStuck**
2020-06-26 15:59   Info: 1300DT: [AD] PickupAndDeliverMode:reset set STATE_INIT
2020-06-26 15:59   Info: AutoDriveStartStopEvent
2020-06-26 15:59   Info: AutoDriveStartStopEvent
2020-06-26 15:59   Info: 1300DT: [AD] ADTrailerModule:isActiveAtTrigger self.isLoading false self.isUnloading false
2**020-06-26 15:59   Info: 1300DT: handleBeingStuck**
2020-06-26 15:59   Info: 1300DT: [AD] PickupAndDeliverMode:reset set STATE_INIT
2020-06-26 15:59   Info: AutoDriveStartStopEvent
2020-06-26 15:59   Info: AutoDriveStartStopEvent
2020-06-26 15:59   Info: 1300DT: [AD] ADTrailerModule:isActiveAtTrigger self.isLoading false self.isUnloading false
2020-06-26 15:59   Info: 1300DT: [AD] PickupAndDeliverMode:reset set STATE_INIT
2020-06-26 15:59   Info: AutoDriveStartStopEvent

**Comment by Axel32019** [comment]
handleBeingStuck is the normal situation if AD can not go ahead. So it stops AD and restarts the mode again. As already told the only thing to do from AD, helperManager:useHelper / helperManager:releaseHelper, is done. So at the moment I don't know what your problem with AD is @wallsingham

**Comment by wallsingham** [comment]
@Axel32019 The feedback was only for completeness. I myself can only make an empirical assessment. If you say that nothing is possible on the AD side, then that's OK. AD is a great tool, that's why I am active here.

**Comment by Gonimy-Vetrom** [comment]
Unfortunately, the problem persists.

**Comment by Gonimy-Vetrom** [comment]
Now this problem manifests itself when the driver arrives at the download trigger, but it is already empty and the driver is waiting. While waiting, AutoDrive is hiring new drivers.
