### ISSUE TITLE
[BUG] AD Driver Doesn't refill fertilizer when seeder is above the refill level

### ISSUE THREAD

**Issue by cosmin-margarit** [Stephan-S/FS19_AutoDrive#1465]
**AutoDrive Version:** 1.1.0.4
**Release or Custom Zip:** Release  
**Map (If applicable):** Ravenport
**Vehicle / Type (If applicable):** HTZ 17221-21 (mod)
**Multiplayer or Singleplayer:** Singleplayer  

**Describe the bug**  
I have set up a refill course. I have a seeder that accepts seeds and fertilizer. It's from a mod: Vaederstadt Rapid A600-800S Tramline  Edition version 1.0.0.1 from Jens Ejvinsson and installed from the ingame modhub. 
Now, I tried the same course from the same spot with the sower empty (seeds and fertilizer) and it stopped at the refill station and filled both containers to full and return to the destination. When only the fertilizer was empty and the seeds were full, the AD driver didn't want to go to the refill station at remained at the destination, as if it was looking only at the seeds level and saw them full and taught he doesn't need to refill ( I selected Fertilizer from the material dropbox in AD menu).

I also tested with fertilizer full, and seeds empty, and also all containers empty, and the course worked perfectly, no matter if I selected seeds or fertilizer in refill dropbox in AD menu, it refilled to full and returned to destination.

So, when the primary container is full (Seeds), and the secondary container is empty (fertilizer) AD doesn't go to a refill because he thinks that it's full because primary container is full and doesn't consider secondary container.

**If applicable - Steps to reproduce the behavior**  

**Screenshots**  

[log.txt](https://github.com/Stephan-S/FS19_AutoDrive/files/4724620/log.txt)
Video (I uploaded in on youtube as unlisted because google drive compressed it to much): https://youtu.be/O67hS3lTN0U
Video Working: https://youtu.be/HQwELmYEqlg

**Comment by Iwan1803** [comment]
You try to unload the seeder completly. And also please try again with the actual RC3.

**Comment by Iwan1803** [comment]
_Please download 1.1.05.-RC4, try again and then post a feedback._
Bitte lade 1.1.05.-RC4 herunter, versuch es erneut und poste dann ein Feedback.

Changelog: https://github.com/Stephan-S/FS19_AutoDrive/wiki/Release-Notes

**Comment by cosmin-margarit** [comment]
I've managed to test it and it works, thanks! 😊
