### ISSUE TITLE
[BUG] AD Tractor Unloader crashes into the back of the combine when trying to unload

### ISSUE THREAD

**Issue by cosmin-margarit** [Stephan-S/FS19_AutoDrive#1466]
**AutoDrive Version:** 1.1.0.4  
**Release or Custom Zip:** Release  
**Map (If applicable):** Ravenport
**Vehicle / Type (If applicable):**   Fendt Favorit 511c
**Multiplayer or Singleplayer:** Singleplayer  

**Describe the bug**  
Hello people, I was trying to use CoursePlay and AutoDrive to automate some work around my farm. In this use-case, I was harvesting a field with a CoursePlay combine that was set to open it's pipe when needing to unload and set to stop and not move while unloading. The combine did its normal course and at the trigger pre-call level(85% in AD settings), it called the tractor. The tractor went in the back of the combine as expected and kept the distance while the combine was still harvesting to reach full. When the time came the combine trigger the unload event and the tractor driver started to calculate the path to drive to the combine's pipe, but every time it went straight into its back and got stuck.

The CP combine was set to extend it's pipe when waiting for unloading and the CP's Combine self unload was off.

I'll attach a video and the log file for you guys.

Is it possible, that this is caused because when the CP Combine was full, the extended pipe and then it called the driver, so when the AD driver was called the tip of the pipe was still in the back of the combine (because it just started extending) and the ad driver registered that initial position and not the final extended one? And so it tried to go in the back of the combine?

[log - ADTractorDrivesInBackOFHarvester.txt](https://github.com/Stephan-S/FS19_AutoDrive/files/4725003/log.-.ADTractorDrivesInBackOFHarvester.txt)

**If applicable - Steps to reproduce the behavior**  

**Screenshots**  

I'll attach a google drive link for the video as Github doesn't support video formats.
Video1: https://drive.google.com/file/d/1XH2gKYBUz5z3OdviYNuyaT1tFVul1M8D/view?usp=sharing
Video2: https://drive.google.com/file/d/1_VkRPul8eDCKCuEBCIPXFVqnRIEyNkDH/view?usp=sharing

Sorry, I hope you can extract some info from the videos as I was late to recording them...

**Comment by seeske123** [comment]
Check your off set for thr pipe. Is it at -0,55?

**Comment by cosmin-margarit** [comment]
It's at 0.75m.

**Comment by cosmin-margarit** [comment]
I've changed the pipe offset to maximum (5m) and now instead of driving in the back of the combine it drives straight in the header, 5m to the left

https://drive.google.com/file/d/1_VkRPul8eDCKCuEBCIPXFVqnRIEyNkDH/view?usp=sharing
https://drive.google.com/file/d/1XH2gKYBUz5z3OdviYNuyaT1tFVul1M8D/view?usp=sharing

**Comment by cosmin-margarit** [comment]
Also the combine I'm using is the John Deer S680i(2012)

**Comment by Iwan1803** [comment]
_Please download 1.1.05.-RC4, try again and then post a feedback._
Bitte lade 1.1.05.-RC4 herunter, versuch es erneut und poste dann ein Feedback.

Changelog: https://github.com/Stephan-S/FS19_AutoDrive/wiki/Release-Notes

**Comment by cosmin-margarit** [comment]
I've tested again with the RC5 version and with the same modded combine and now works fine! Thank you very much for being responsive!
