### ISSUE TITLE
Kombination AD und CP im Bereich BGA

### ISSUE THREAD

**Issue by Berios** [Stephan-S/FS19_AutoDrive#1467]
Hallo Stephan!

Ich habe mir nicht alle Issue durchgelesen, weshalb ich nicht weiß ob dies schon einmal ein Thema war:

Ist eine Optimierung zwischen AD und CP im Bereich der BGA möglich? AD ist das absolute Transportsystem für eine Silo Beladung, CP ist wiederum das System um innerhalb des Silo "Ordnung" zu machen (schieben, verdichten, etc.). Leider kommunizieren aber die AD - Abfahrer nicht mit dem Schieber / Verdichter von CP. Wenn die AD - Abfahrer von dem Schieber ebenfalls den Befehl "Halten wenn im festgelegten Radius" (siehe Radius - Funktion von CP bei Schieben und Verdichten) akzeptieren würden, dann könnte man beide System einsetzen und eine absolute Synergie zwischen beiden Scripts in Bezug auf die Befüllung / Nutzung der BGA erzielen.

Vielleicht könnt ihr hier etwas machen. Leider muß man sich momentan für eines der beiden Systeme entscheiden (vor allem bei großen Karten mit große Silos - siehe Oberthal oder Multimap extrem lästig). Nimmt man AD muß man immer mit einem Traktor zwischen den Abfahrern verdichten / verteilen, da diese sonst an ihren eigenen, aufgeschütteten Bergen hängen bleiben. Nimmt man CP muß man die halbe Karte einfahren (ist übertrieben, aber man muß ein eigenes CP - Streckennetz anlegen). Beide Lösungen sind im Bereich Singelplayer auf den größeren Maps nicht optimal (ist die FSK 0 Version :-)). Bei einer Korrespondenz der beiden Scripts würde den Anwendern eine Menge Mühe (und auch eine Menge Kopfschmerzen :-)) erspart bleiben.

Vielleicht hast Du hier für die zukünftigen Versionen Möglichkeiten.  Wäre eine super Sache, quasi ein Sahenhäubchen auf ein ohnehin super gerniales Script. Vielen Dank für AD - als Sinngelplayer für mich unverzichtbar. :-)

Berios

**Comment by Iwan1803** [comment]
Ich habe auf der NFM 4x sowohl ein Doppelkeil- als auch Doppeldurchfahrsilo und die meisten Probleme macht eigentlich eher CP.

Beim Durchfahrsilo passiert es ganz selten, das mein CP-Verdichter sich mit dem AD-Abfahrer ins Gehege kommt. Dies liegt vermutlich daran, das der CP-Verdichter immer in der gleichen Richtung durch das Silo durchfährt wie der AD-Abfahrer und außen rum halt zurück. Dadurch konnte ich die Probleme so gut wie beseitigen: https://youtu.be/5Kw2P0vxPeQ

Beim Keilsilo passiert es trotz entsprechender Einstellung in CP (automatisch anhalten für = alle mit laufendem Motor, Umkreis auf 150m) häufiger mal, das sich beide in die Quere kommen - besonders, wenn mehrere Abfahrer unterwegs sind. Der CP-Fahrer verlässt dann teilweise einfach nicht schnell genug den Bunker, um auf seine Parkposition zu fahren.
Mittlerweile lager ich Häckselgut & Co. erst in mein Silo ein und lasse von da aus dann 1 AD-Abfahrer die Silos befüllen, um unnötige Kollisionen zu vermeiden.

Ich denke, das die Probleme größtenteils bei CP in der Erkennung der AD-Abfahrer liegen, besonders die Kollisionserkennung lässt hier zu wünschen übrig. Wenn ich CP so auf github verfolge, dann scheint die BGA-Funktionalität aber eher selten genutzt zu werden (zumindest lt. deren Meinung).

Wir werden mal schauen, ob und wie wir das verbessern können.

**Comment by Iwan1803** [comment]
Es wird im nächsten AD-Release eine automatisierte Pause-Funktion geben. CP hat dafür von uns schon ein Update erhalten.
