### ISSUE TITLE
course 1.1.0.4 and RC 1.1.0.5[BUG]

### ISSUE THREAD

**Issue by cabmac** [Stephan-S/FS19_AutoDrive#1468]
Hallo,

ich hatte die Autodrive-Kurse auf der Ellerbach alle eingefahren, die funktionierten alle top mit 1.1.0.4. Sobald ich auf die 1.1.0.5 gehe, scheint er weitere oder weite Entfernungen nicht mehr berechnen zu wollen. Er bleibt ca. 10 sekunden haengen, um mir dann mitzuteilen, dass er keinen Kurs gefunden haette ;)...auf kuerzeren Wegen gehts.
Ich habe die 1.1.0.4 wieder reingehauen mit meiner Kurse-xml und es geht nun wieder einwandfrei auf allen Strecken und ohne Verzoegerung (Berechnung des Kurses).

Kommt die neuere Version evtl nicht klar mit den auf aelteren Versionen eingespielten Kursen oder stimmt da etwas mit der neuen nicht?

Schoene Gruesse,

cabmac

**Comment by Axel32019** [comment]
Hallo, Es gibt mehrere Versionen 1.1.05, ich empfehle mal die Version 1.1.05 RC2 zu testen:
Im Discord https://discord.gg/9D4B5hX unter #announcements zu finden.

**Comment by cabmac** [comment]
Hallo, stimmt...1.1.05 RC2 geht einwandfrei, die RC3 war das, die nicht funktionierte...thx...

Schoene Gruesse
