### ISSUE TITLE
Skalierung HUD ändern

### ISSUE THREAD

**Issue by RobbyDead** [Stephan-S/FS19_AutoDrive#147]

**Comment by RobbyDead** [comment]
Hallo, 
Zunächst einmal vielen Dank für diesen Mod. Nachdem ich mich schwer getan habe im LS17, habe ich nun meine Freunde an diesem Mod gefunden.
Aber ich habe ein kleines Problem.
Das HUD besteht ja aus 4 Reihen. Bei mir bekomme ich nur 3 zu sehen weil die Zeile 2 und 3 ineinander übergehen.
Gibt es eine Möglichkeit die Skalierung zu ändern?
Ich spiele an 3 Monitoren und habe eine Auflösung von 5760x1080.

**Comment by Stephan-S** [comment]
Hey,
Könntest du mir einen Screenshot zukommen lassen?
Im Prinzip passt er sich an die Auflösungen an und es sollten nur Probleme mit zu langem Text auftreten bei zu außergewöhnlichen Auflösungen.

Wenn du mir einen Screenshot zeigst, schau ich aber auf jeden Fall Mal woran es liegt.
Vielen Dank und beste Grüße,
Stephan

**Comment by RobbyDead** [comment]
Hi Stephan,
danke für Deine Antwort...

Würde Dir gerne einen Screenshot senden.
Habe es über iCloud versucht hat aber nicht geklappt...
Wie kann ich am besten ein Bild hochladen?

**Comment by Stephan-S** [comment]
Hier beispielsweise:
https://de.imgbb.com/

**Comment by RobbyDead** [comment]
So, hab es doch herausgefunden :)
Hier also der Screenshot.

https://s17.directupload.net/images/190525/k24g7v89.png

**Comment by RobbyDead** [comment]
Danke :) 

Bin ja hartnäckig denn geht nicht gibts nicht ^^

**Comment by RobbyDead** [comment]
Hallo Stephan,

inzwischen ist ja schon eine neue Zeile im Menü erschienen um die Skalierung vom HUD selbst zu verändern.
Leider hilft mir das bei meinem Problem nicht weiter weil nur die gesamte Größe verändert wird.
Bei mir sind aber 2 Reihen übereinander geschoben.
Da meine Auflösung in der Höhe aber nicht anders ist als bei andere, also 1080, kann es daran nicht liegen. Was ich mir da eher vorstellen kann ist das es ein Problem gibt bei der Breite 1980 x 3 wegen 3 Monitoren.

Es gibt ja eine Datei für das HUD, welche Werte kann ich da ändern, damit es sich auf die einzelnen Zeilen auswirkt? 
Würde das dann selbst mal probieren und dich über Erfolg oder Misserfolg informieren 😊

Wünsche dir noch einen schönen Abend 
LG
RobbyDead

**Comment by Stephan-S** [comment]
Probier doch mal die neueste Version aus. Dort sollte es besser aussehen. Konnte es bei mir leider nur mit 1920x360 simulieren, wobei dann alles etwas arg unscharf wirkt :-D

**Comment by RobbyDead** [comment]
Hi Stephan,

Hast du sehr gut hinbekommen.
Nun sieht es wieder aus wie es sich gehört.

Vielen Dank 🙏
