### ISSUE TITLE
Fewer curves in courses - Weniger Kurven in Kursen

### ISSUE THREAD

**Issue by gfa4711** [Stephan-S/FS19_AutoDrive#1470]
I am currently playing the Wild West map (16x map). Some of the courses are really long and I noticed a problem. The courses that AD calculates always look like the red line in the screenshot. These zigzag courses have the disadvantage that the trucks have to brake and accelerate all the time and that takes forever, especially for road-trains. If I drive the blue route by hand I am up to 3x faster than the AD driver with the red route.

So my suggestion would be to add a switch that gives tight curves worse edges costs than straight paths. Alternatively the path with the highest average speed could be taken.

Ich spiele zur Zeit die Wild West Karte (16x Map). Die Fahrstrecken sind teilweise echt riesig lang und dabei ist mir ein Problem aufgefallen. Die Kurse, die AD berechnet sehen immer wie die rote Linie im Screenshot aus. Diese Zickzackkurse haben den Nachteil, dass die LKWs andauernd abbremsen und beschleunigen müssen und das dauert besonders bei Roadtrains ewig. Wenn ich die blaue Route von Hand fahre bin ich bis zu 3x schneller als der AD-Fahrer mit der roten Route.

Mein Vorschlag wäre daher, dass man einen Schalter hinzufügen könnte, der enge Kurven eine schlechtere Kantengewichtung bekommen als gerade Pfade. Alternativ könnte man auch den Kurs mit der höchsten Durchschnittsgeschwindigkeit nehmen.

Macht weiter so!
Viele Grüße
gfa4711

![Wild West (2)](https://user-images.githubusercontent.com/53525488/84259381-ad1ac900-ab18-11ea-87b6-86da16431b55.jpg)

AutoDrive Version 1.1.0.5-RC3

**Comment by Mike1977** [comment]
Very nice idea, and i would also love so see that. 
It might be the shortest path, but it takes definitely way longer to drive because of the slow down in the corners...

**Comment by masneoquil** [comment]
If I remember correctly, in previous versions there was an option to choose between faster or shorter routes.
I wonder why they removed the option.

**Comment by Michael170978** [comment]
Du kannst dem Fahrzeug sagen bis wie viel Km er Umweg machen soll. wenn du 0 km stehen hast dann berechnet er die kürzesten weg. Somit wäre für AD die rote Linie der kürzeste Weg

Ach ja es wäre gut zu wissen welche Version du benutzt.

**Comment by gfa4711** [comment]
> Du kannst dem Fahrzeug sagen bis wie viel Km er Umweg machen soll. wenn du 0 km stehen hast dann berechnet er die kürzesten weg. Somit wäre für AD die rote Linie der kürzeste Weg

Die Option kenne ich und laut Tooltips bezieht sich das nur auf das Umfahren von Zielpunkten.
Zur Sicherheit habe ich den Wert auf 10000m (max) gestellt und habe es nochmal getestet. Gleiches Ergebnis, die Fahrzeuge wählen einen Zickzackkurs.

I know this option and according to the tooltips it only refers to bypassing destination points.
To be on the safe side I set the value to 10000m (max) and tested it again. Same result, the vehicles choose a zigzag course.

> Ach ja es wäre gut zu wissen welche Version du benutzt.
Steht unten: AutoDrive Version 1.1.0.5-RC3

Viele Grüße
gfa4711

**Comment by Michael170978** [comment]
Bei RC3 funktioniert der Unweg nicht. Das Problem hab ich auch. Du musst bedenken das ist eine Beta Version. Also keine Release Version.

**Comment by gfa4711** [comment]
Die Option "Schnellste Route" war ausschlaggebend. Diese funktioniert in der RC3 nicht mehr, obwohl in der XML Datei die Option noch aktiviert ist. K.a warum die nicht mehr da ist.
Allerdings ist die Wegfindung auch in der Version 1.1.0.4 nicht optimal. Es gibt zwar deutlich weniger Kurven im Kurs, aber es sind immer noch einige da.

The option "Fastest Route" was crucial. This no longer works in the RC3, although the option is still activated in the XML file. I don't know why it is no longer there.
But the route finding is not optimal in version 1.1.0.4. There are much less curves in the course, but there are still some.

**Comment by Iwan1803** [comment]
The option "fastest route" was no longer needed as the path calculation was completely renewed.
There will always be situations where something is not as we expected it to be.
AD is a quite intelligent script collection, but not an AI 😉

**Comment by gfa4711** [comment]
So the new algorithm does not consider the speed anymore?

**Comment by Iwan1803** [comment]
"fastest route" has never considered the travel time, but only max. attainable speed on the route.
If a high speed was reached on a short section, he drove that way, even if the total driving time became longer.

**Comment by Iwan1803** [comment]
Please download 1.1.0.5-RC4, try again and then post a feedback.

Changelog: https://github.com/Stephan-S/FS19_AutoDrive/wiki/Release-Notes

**Comment by gfa4711** [comment]
I have tested the new version and the courses are much better. 👍 
Is the detour setting taken into account during path finding?

**Comment by Iwan1803** [comment]
If there is a destination point on the route, then a detour is made if it is greater than 0m.
