### ISSUE TITLE
[BUG]Unloading does not work properly in MP

### ISSUE THREAD

**Issue by GitTomahawk** [Stephan-S/FS19_AutoDrive#1472]
**AutoDrive Version:** 1.1.0.5  
**Release or Custom Zip:** RC3, RC4, RC5   
**Map (If applicable):** Porta Westfalica (issue not map related)
**Vehicle / Type (If applicable):**   modded and stock
**Multiplayer or Singleplayer:** MP (Dedicated Server)

**Describe the bug**  
Unloading does not work im MP <del>(especially when other Players are connected)</del>
Since RC5 unloading doesnt'work even when I'm alone at the server.
I described the issue details and provided screenhots in #1304 
The behavior did not change in current RC.

I already tried to remove waypoints around the unloading station and created them from scratch.
I tried to move the target waypoint into serveral distances from the unloading trigger.
I tried to change max distance setting to different values (up to 100m)

<del>When alone at the server I noticed that often only the first trailer is emptied.
The driver then stops with second trailer at unloading trigger but does not unload.</del>

**Workarounds available**
a) Disable and enable AD when it stops at unloading Trigger
b) Click "Weiterfahren" twice when it stops at unloading Trigger
(Workarounds do not apply for 2nd trailer - needs to be unloaded manually)
c) Issue is solved in "beta-testing" branch commit 1c1611e

**Comment by Iwan1803** [comment]
As several player are using 2 trailer this seems be not a general problem.
Maybe a screenshot could help.

But what is the problem now: MP or unloading?

**Comment by GitTomahawk** [comment]
The unloading issueis mainly related to MP.
When more than one player is connected the unloading issues get worse.
I provided Screenshots in #1304.

**Comment by Iwan1803** [comment]
_Please download 1.1.05.-RC4, try again and then post a feedback._
Bitte lade 1.1.05.-RC4 herunter, versuch es erneut und poste dann ein Feedback.

**Comment by GitTomahawk** [comment]
Hi, das Verhalten hat sich in RC4 nicht verändert.
Übrigens der Button "Anzahl Wiederholungen" funktioniert im MP auch seit einigen Releases nicht mehr- das hat mich bisher nicht gestört, aber vielleicht hat es ja etwas damit zu tun.

**Comment by GitTomahawk** [comment]
Das Verhalten hat sich im RC5 nicht verbessert

**Comment by Iwan1803** [comment]
Zur Info für uns verlinkt: https://github.com/Stephan-S/FS19_AutoDrive/issues/1510

**Comment by Obelixm** [comment]
Den  Bug kann ich bestätigen. 
Info:
AD deaktivieren und sofort wieder aktivieren dann startet der entladevorgang.

Grüsse as München 
Obelixm

**Comment by GitTomahawk** [comment]
Übrigens - bei Zügen mit 2 Anhängern entlädt er immer nur den ersten Anhänger (siehe auch #1445).
Beim 2. Anhänger funktioniert der Workaround mit dem Weiterfahren button nicht - der muss immer manuell entladen werden.

Ich habe mittlerweile auch ausprobiert ob andere Fahrzeug/Helper-Mods die wir installiert haben das Verhalten beeinflussen: Courseplay, Advanced Vehicle, Hired Helper Tool, EnhancedVehicle.
Der Fehler tritt auch auf, wenn sie deaktiviert sind.

**Comment by txmazing** [comment]
Mit der 1.1.05.-RC4 hatten das Problem nie. Wir spielen auch MP auf einem dediServer und können gar nicht mehr abladen lassen ohne jedes Mal AD an und wieder aus zu stellen.

**Comment by GitTomahawk** [comment]
@Iwan1803: 
An dieser Stelle möchte ich noch mal anbieten -Wenn du mir nen Tipp gibtst wie/wo ich nen debug output einbauen kann, versuche ich die Umstände genauer zu analysieren.

**Comment by Axel32019** [comment]
@GitTomahawk Es würde helfen kurz vor Erreichen des Abladeziels die Debug-Kanäle Fahrzeuge und Anhänger zu aktivieren bis es zum Stillstand kommt. Nicht empfehlenswert ist diese ständig zu aktivieren da sie das log füllen!

**Comment by Easton97-Jens** [comment]
Mir ist aufgefallen dass es nur an einem Schüttgut Anhänger nicht funktioniert das Abladen bei einem Tankauflieger oder ein Tankwagen funktioniert komplett einwandfrei das abladen und aufladen

**Comment by GitTomahawk** [comment]
@Axel32019: Welche Debug Kanäle sind das bzw. was ist das Kommando dafür?

Ich hab mal das "normale" debugging aktiviert.
In dem Moment wo er stehen bleibt kommt die Meldung "Info: EVENT_SET_DISCHARGE_STATE size 6.75 Bytes"

![2020-07-24 21_57_55-Farming Simulator 19](https://user-images.githubusercontent.com/55877391/88430749-4405c100-cdf9-11ea-8505-a0bbcfd31e93.png)

**Comment by Axel32019** [comment]
Kein Kommando. Im AD Menü -> Debug Einstellungen -> Haken bei Fahrzeuge und Anhänger kurz vor Erreichen des Ziels setzen.
Dann sollten reichlich Meldungen im log erscheinen, die mir helfen.

**Comment by Easton97-Jens** [comment]
Bei mir wenn ich das aktiviere wie du das beschrieben hast wird bei mir nicht der log vollgespamt mit irgendwelchen Meldungen.  mir ist gerade aufgefallen wo ich es gemacht habe das ich mit I manuell Abladen musst( ADIst dabei an) und dann fährt sogar at weiter

**Comment by GitTomahawk** [comment]
Wen ich über das Menü die Settings Fahrzeuge und Anhänger an schalte kommen überhaupt keine Meldungen im log.
Denn ich noch zusätzlich Netzwerk anschalte kommt die Meldung
"Info: EVENT_SET_DISCHARGE_STATE size 6.75 Bytes"

**Comment by GitTomahawk** [comment]
Ich habe unser MP Savegame mal lokal gehosted - dann schreibt er einige in die log.
Das Fahrzeit mit dem Abladeproblem ist der T_TGS3-
[T_TGS3_log.txt](https://github.com/Stephan-S/FS19_AutoDrive/files/4977764/T_TGS3_log.txt)

Nach ~10s habe ich dann den Workaround mit AD aus und wieder an gemacht

**Comment by GitTomahawk** [comment]
Ich habe mal in UnloadAtDestinationTask.lu Zeile 95 "self.vehicle.ad.specialDrivingModule:stopVehicle()" auskommentiert und stattdessen einen debug output (print) an diese Stelle gesetzt.
Das führt zu folgendem Verhalten: 
- In SP und lokal gehostetem MP fährt er nun auch beim Abladen weiter. 
- Im dedicated MP stoppt er nach wie vor am Trigger und lädt nicht ab.

Das eingefügte Debug output im log belegt aber in beiden Fällen dieser Teil ausgeführt wird.

**Comment by GitTomahawk** [comment]
Ich habe mal in UnloadAtDestinationTask.lu Zeile 95 "self.vehicle.ad.specialDrivingModule:stopVehicle()" auskommentiert und stattdessen einen debug output (print) an diese Stelle gesetzt.
Das führt zu folgendem Verhalten: 
- In SP und lokal gehostetem MP fährt er nun auch beim Abladen weiter. 
- Im dedicated MP stoppt er nach wie vor am Trigger und lädt nicht ab.

Das eingefügte Debug output im log belegt aber in beiden Fällen dieser Teil ausgeführt wird.

Ich habe mir also weiter das Anhalten des Fahrzeugs angesehen.
Wenn ich statt das Fahrzeug komplett zu stoppen im SpecialDrivingModule Line 58ff
  local finalSpeed = 0.1
  local allowedToDrive = true
setze, dann fährt er nach ab dem Abladetrigger rückwärts.

**Comment by Axel32019** [comment]
@GitTomahawk Was bringen Deine Änderungen im MP?

**Comment by GitTomahawk** [comment]
Bis jetzt habe ichs nur geschafft dass er rückwärts fährt oder stehen bleicbt und dann wieder im status "blocking" ist.
Ich hab auch schon probiert ob es hilft sanfter zu bremsen (acc zu verrringern).
Er geht immer sobald er steht auf "blocking" - und in diesem Zusand lädt er nicht ab.
Welches Script das "blocking" auslöst konnte ich noch nicht rausfinden.

**Comment by txmazing** [comment]
> Bis jetzt habe ichs nur geschafft dass er rückwärts fährt oder stehen bleicbt und dann wieder im status "blocking" ist.
> Ich hab auch schon probiert ob es hilft sanfter zu bremsen (acc zu verrringern).
> Er geht immer sobald er steht auf "blocking" - und in diesem Zusand lädt er nicht ab.
> Welches Script das "blocking" auslöst konnte ich noch nicht rausfinden.
> Definitiv ist das Verhalten zwischen SP, lokalem MP und dedicated MP unterschiedlich.

Guck mal im Beta-Merge, dort ist es schon gefixed ;)

**Comment by GitTomahawk** [comment]
Ich habe grade Commit 7e15ae3 von Axel32019 auf unseren Server geladen.
Die ersten Tests sind allerdings negativ.

**Comment by Axel32019** [comment]
Hallo, Das ist ein Beta - also noch in Arbeit.

**Comment by Easton97-Jens** [comment]
mir ist aufgefallen das er kurz for dem entlade punkt angekommen ist ein Fehler erzeugt nicht jedes mahl 

es geht um disen fehler 
Error: Running LUA method 'packetReceived'.
dataS/scripts/gui/hud/HUD.lua(559) : attempt to index local 'moneyType' (a nil value)

der ist entstande beim abladen wo er noch im modus Info: EVENT_MONEY_CHANGE gewesen ist
ihr ist der log dazu
[log.txt](https://github.com/Stephan-S/FS19_AutoDrive/files/5022108/log.txt)

**Comment by fischi3016** [comment]
1.1.5.0 RC5
also ich kann mit keinem Originalanhänger abladen Hab den Hawe ausm Modhub alle Fruchtypen reingeballert der funzt

**Comment by Axel32019** [comment]
@GitTomahawk @txmazing @fischi3016 @Obelixm @Easton97-Jens 
Ihr seid herzlich eingeladen den aktuellen beta-Stand im MP zu testen!

Wer es noch nicht gemacht hat, hier eine kurze Anleitung:
https://github.com/Stephan-S/FS19_AutoDrive/tree/beta-testing

Code -> Download ZIP
Extract the downloaded zip "FS19_AutoDrive-beta-testing.zip"! Do not put it into the mod folder, this will not work !!!
In the extract you find the folder "FS19_AutoDrive" -> zip and put to mod folder -> start the game

Code -> Download ZIP
Die herunter geladene zip-Datei "FS19_AutoDrive-beta-testing.zip" auspacken! Nicht in den mod Ordner verschieben/kopieren, das funktioniert nicht !!!
In der entpackten Datei den Ordner "FS19_AutoDrive" neu als zip packen -> zip in mod Ordner kopieren -> Spiel starten

**Comment by Easton97-Jens** [comment]
moin AD Team ich habe wie von @Axel32019  geschrieben wurde,  habe ich mir die Beta für den MP heruntergeladen und sie gestern und heute ausbrobirt und bein sehr zu frieden mit dem ergebniss die Fahrzeuge laden sehr offt ab am trigger wo sie sollen 

es gibt nur das Problem wonn 2 Fahrzuge oder mehr bei ein und den selben trigger abladen mochten das der erste nicht ablädt weil die fahrzeuge zu dicht auffahren  habt ihr da tips oder kont ihr da noch wass machen?

Gruß Jens
Icch bedanke miche für die große mühe die ihr in den Mod reinsteckt das es für alle ein tolles Spiel erlebniss würd

**Comment by Axel32019** [comment]
Hallo Jens,
Danke für die Rückmeldung. Kann es daran liegen das das erste Fahrzeug eine Heckklappe zum Abladen hat? Bitte mal beobachten.

**Comment by Easton97-Jens** [comment]
ja es ist einer mit einer heckklappe mir passiert es auch bei anderen mit heckklappe wie der von  Onkelyogi bei dem Krone TX560D und auch andere die nach hinten ausladen

**Comment by fischi3016** [comment]
Dann versuch mal ein Seiten Kipper zuerst

**Comment by GitTomahawk** [comment]
Bei mir laden auch die Anhänger mit Heckklappe nicht ab.

**Comment by Easton97-Jens** [comment]
Wie weit sind deine Punkte vom Ablade trigger entfernt bei uns habe sie fast eine komplette anhänger Länge noch vone gesetzt. Zur Info die Fahrzeuge sollten gerade über dem trigger stehen. Wenn du ein Bild hast wo mann den Ad Punkt beim trigger sie kann es auch weiter helfen.

**Comment by GitTomahawk** [comment]
Der Abstand vom  Trigger zum Ziel spielt keine Rolle - habe Trigger, die weit weg sind und welche die dicht dran liegen. 
(habe ich zu Anfang dieses Posts auch schon ausführlich getestet)
Das Verhalten ist überall gleich.

**Comment by SEETechWolf** [comment]
Das entladen scheint jetzt in der Beta von heute auch wieder zu funktionieren.

**Comment by GitTomahawk** [comment]
Ich kann ebenfalls bestätigen dass es in der beta an den meisten Entladestellen funktioniert - Getestet commit 1c1611e.
Ich habe noch nicht getestet ob es funktioniert wenn andere Spieler auf dem Server sind (gestern hatte keiner Zeit).
Das einzige was nicht funktioniert, ist wenn mehrere Silos hintereinander angeordnet sind, dann entlädt er nur beim ersten.
Ist das Silo irgendwann voll bleibt er dort stehen. Er fährt nicht (wie früher) zum nächsten weiter und entlädt ... bis er den Ziepunkt erreicht hat.

**Comment by Axel32019** [comment]
Es war schon immer so das bei vollen Silos angehalten wurde, es sei denn man hat die Einstellung "mehrere Ziele" aktiviert (die nicht im Standard-Ordner sind).

**Comment by Easton97-Jens** [comment]
Wie sieht es aus mit dem Abstand zu den Fahrzeugen auf den Ablade stellen wegen dem blockieren das angefangen Ablade Fahrzeug? Gibt es die Möglichkeit das Fahrzeug einen gewissen Abstand zu einander einhalten auf den Strecken netz?

**Comment by Axel32019** [comment]
@Easton97-Jens 
In der beta wurde bereits ein "Sicherheitsabstand" von 2m hinzugefügt um genau dies zu vermeiden. Wenn Du möchtest probier es mal aus. bbca610

**Comment by fischi3016** [comment]
Kann ich nur bestätigen und klappt super 👍

Axel32019 <notifications@github.com> schrieb am So., 6. Sept. 2020, 17:19:

**Comment by Axel32019** [comment]
Sollte alles mit 1.1.0.5-RC6 funktionieren.
