### ISSUE TITLE
[Question]How do i use CP in field thenAD to unload?

### ISSUE THREAD

**Issue by kwguk** [Stephan-S/FS19_AutoDrive#1474]
**Question:**   
I've got a question...

I find CP is best for unloading combines etc but ive got ready made AD courses from fields to unloading silo. I cant workout how to set it up so CP does the field then AD takes over. What mode do i have AD in and how do i use CP just for unloading?

Many thanks

**Comment by sistem442** [comment]
Hello, 
this worked for me:
1. Park your vehicle over AD route near the field you will harvest
2. Set CP to mode 2, from autodrive folder in CP folders select destination to unload silo and back, CP should generate course for unloading. If course is not generated try moving vehicle so it is exactly over AD route and in correct direction.
3. Start CP driver. CP is using AD only to generate course, you don't need AD for nothing else.

**Comment by Iwan1803** [comment]
In short words: CP is for fieldwork and AD is for driving.
The explanation of sistem442 is one possibility, but not the best.

The combine should run with CP to do the field work. In AD you set the same waypoint like for the unloader, but don't start AD - only CP. In the AD settings you should deactivate to search for an unloader as the combine and the unloader find each other via then by same set target.
The unloader should be set then to unload combine mode. The 1st target should be same like the combine, f.e. a target point at the field. The 2nd is the unload target, f.e. a silo.
Then you only need to start AD and that's it.

**Comment by Iwan1803** [comment]
Has the question been answered? 
If not, you can reopen it.

**Comment by antler22** [comment]
For Overload Mode, CP requires a wait point to be set. Is there an easy way for this too?
