### ISSUE TITLE
[Question] Abfahrerprobleme in Pfadfindung

### ISSUE THREAD

**Issue by FireMartinZZ** [Stephan-S/FS19_AutoDrive#1476]
Hey sorry wenn ich hier was falsch mache aber bin hier zum ersten Mal....
Ich habe das Problem beim Drescher abtanken das der LKW zwar abtankt aber das abgetankte dann nicht wegfährt er sagt mir jedesmal Pfad nicht gefunden

**Comment by sistem442** [comment]
Du kannst den Drescher mit Courseplay abfahrer  abtanken. Den Courseplay abfahrer kann AD Route verwenden.

**Comment by Iwan1803** [comment]
@sistem442 
hör bitte auf, alles mit "nutz CP" lösen zu wollen. Das hilft keinem und ist dazu völlig unnötig.

@FireMartinZZ 
Welche AD-Version? Falls nicht RC4, dann bitte erst aktualisieren, erneut prüfen und dann ein Feedback posten.
Falls das nicht hilft: welche Map, welche Fahrzeuge und nach Möglichkeit Screenshots vom Feld und der Abfahrer-Einstellungen

**Comment by FireMartinZZ** [comment]
Jungs war mein Fehler hatte eine Lücke in Pfad 😂 Ruhe bewahrn bei Fliegeralarm ich danke euch trotzdem 💪

**Comment by Iwan1803** [comment]
Immer wieder gerne und da das Problem gelöst wurde, mache ich hier mal zu 😉
