### ISSUE TITLE
[BUG] after automatic refuelling at a petrol station, mode remains on "Drive", does not switch back to previously set - nach automatischen Tanken an einer Tankstelle bleibt Modus auf "Fahren", wechselt nicht zurück auf vorher eingestellten

### ISSUE THREAD

**Issue by haamic** [Stephan-S/FS19_AutoDrive#1477]
AutoDrive Version: 1.1.0.5 RC 4
Release or selbsterstelltes zip: Release C
Karte (falls relevant): Alle

Fahrzeug(art) (falls relevant):

Fahrzeuge mit Geräten, die aufgefüllt werden können (Dünger,Kalk,Herbizid....)

**Beschreibe den Bug**
-Fahrzeug verrichtet Feldarbeit per CP, Einstellung für AD auf "Auffüllen" (falls z.b. Dünger leer)
-während Feldarbeit wird aber Diesel knapp, AD fährt zum Tanken, stellt dabei den Modus auf "Fahren"
-aufgetankt, zurück am Feld startet die Feldarbeit am letzten Punkt, soweit so gut....
 nur bleibt der Modus auf "Fahren" und wechselt nicht zurück auf "Abholen", wie vorher eingestellt.
Wenn also nun der Dünger oder ähnliches leer wird, kann es nicht mehr zum Auffüllen fahren.

**Falls anwendbar - Schritte mit denen ich den Bug nachstellen kann**
siehe oben

**Screenshots**
Falls relevant, bitte Screenshots beifügen

**Comment by Iwan1803** [comment]
-> https://github.com/Stephan-S/FS19_AutoDrive/issues/1479

**Comment by Iwan1803** [comment]
Problem wurde mit 1.1.0.5-RC5 gefixed.

Please update to 1.1.0.5-RC5, try again and if the problem still exists, then open a new issue.
*Bitte aktualisiere auf 1.1.0.5-RC5, versuche es erneut und und wenn das Problem weiterhin besteht, erstelle ein neues Issue.*
