### ISSUE TITLE
[Feature Request] Überladefunktion auf dem Feld, wenn man ohne CP oder AIVE spielt

### ISSUE THREAD

**Issue by Brombee42** [Stephan-S/FS19_AutoDrive#1478]
![fsScreen_2020_06_17_00_56_45](https://user-images.githubusercontent.com/30389219/84836813-d070d700-b036-11ea-8cb9-8d0555a0cf1d.png)
![fsScreen_2020_06_17_00_58_56](https://user-images.githubusercontent.com/30389219/84836822-d666b800-b036-11ea-9584-57597ba9c0be.png)

Kann man AD sagen das der AD Fahrer mit Gärreste auf das Feld kommt und überlädt.Man könnte  neuen Modus machen das wenn man mit Güllefass das Feld düngt das der Fahrer wie beim Drescher abtanken aufs Feld fährt.Habe mal 2 Bilder dazu gepackt wie ich das Meine.Ich spiele auf Dedi Server aber ohne CP und AiVE.Jetzt muss ich immer mit Güllefass vom Feld fahren und zum Feldrand Container und wieder zurück um weiter zu machen.Am Tag mag das noch gehen aber in der N8 sieht man meistens nicht wo man war.Es hätte ein Vorteil das ich mit Fass auf dem Feld stehen bleiben könnte wo ich leer geworden bin. Zum Beispiel auf der NF Marsch wenn ich auf Feld 66 bin was 100 ha groß ist und immer wegfahren muss dauert das seine Zeit bis ich wieder an der Stelle bin wo ich als letztes .Mit diesen Vorschlag von mir könnten mehrere Spieler zb mehrere Felder gleichzeitig bearbeiten.Die Zeit Ersparnis habe ich jetzt nicht gestoppt aber ich fände es Super wenn es die Überlade Funktion geben würde.Ist nur ein Vorschlag wenn das zu Zeitaufwendig ist wäre das auch ok.

**Comment by Brombee42** [comment]
Was ist aus dem Vorschlag geworden?

**Comment by Stephan-S** [comment]
No :-)
