### ISSUE TITLE
1.1.0.5-RC4: known problems / Bekannte Probleme

### ISSUE THREAD

**Issue by Axel32019** [Stephan-S/FS19_AutoDrive#1479]
**AutoDrive Version: 1.1.0.5-RC4**

- drivers do not find their way to the combine or collide
- drivers can't find their way off the field (especially in grass fields)
- reverse driving does not work correctly with the HoT transport pack -> fixed in next RC
- tractors cannot reverse with different implements -> fixed in next RC
- the AIVE button disappears if CP was removed or deactivated -> fixed in next RC
- on driving to refuel the original mod was overwritten -> fixed in next RC
- "only Pickup" and "Pickup and Deliver" -> fixed in next RC
  When reach an already emty pickup target the vehicle will stop and wait.
  Workaround: set "Unload fill level" of that vehicle to 0%
- "only Deliver" and "Pickup and Deliver" -> fixed in next RC
  When reach an already full deliver target in reverse driving the vehicle will stop and wait.
  NO Workaround right now, press Continue so the vehicle goes ahead with the next deliver target as intended
 
**D E U T S C H** 

- Abfahrer finden den Weg zum Drescher & Co. nicht oder kollidieren
- Abfahrer finden den Weg nicht vom Feld runter (bes. bei Grasfeldern)
- Rückwärtsfahren funktioniert mit dem HoT-Transportpack nicht korrekt > gefixed im nächsten RC
- Trecker können mit verschiedenen Geräten nicht rückwärts fahren > gefixed im nächsten RC
- der AIVE-Button verschwindet, wenn man CP entfernt oder deaktiviert > gefixed im nächsten RC
- fährt AD zum Tanken, wird der vorherige Modus überschrieben > gefixed im nächsten RC 
- "nur Beladen" und "Be- und Entladen" > gefixed im nächsten RC
Bei Erreichen eines leeren Beladeziels bleibt das Fahrzeug stehen.
Workaround: Einstellung "Abladen ab Level" des Fahrzeuges auf 0% setzen
- "nur Entladen" und "Be- und Entladen" > gefixed im nächsten RC
Bei Erreichen eines schon vollen Entladeziels in Rückwärtsfahrt bleibt das Fahrzeug stehen.
Derzeit keine Lösung möglich, durch Betätigen von Weiterfahren wird mit dem nächsten Ziel fortgesetzt

**Comment by Iwan1803** [comment]
1.1.0.5-RC5 was released.
