### ISSUE TITLE
AD fährt nicht mit bestimmten Anhängern

### ISSUE THREAD

**Issue by stueja** [Stephan-S/FS19_AutoDrive#148]
Habe gerade versucht, AD mit dem Kröger Autoload-Anhänger (https://www.modhoster.de/mods/autoload-pack) fahren zu lassen. 
Ohne diesen Anhänger kein Problem, mit diesem Anhänger: Klick auf den Abfahren-Button: keine Reaktion, Spielabsturz bei Abkoppeln des Anhängers bei geladenem Kurs.

**Comment by Stephan-S** [comment]
Hey,
Vielen Dank für die Meldung. Könntest du mir ein Log File mit der Fehlermeldung schicken?
Dann kann ich möglicherweise direkt das Problem lösen ohne es selber zu laden und zu testen.
Vielen Dank!

**Comment by Mannie313** [comment]
@Stephan-S  mit der Neuesten version müsste es gut klappen. hatte nur AD und das https://www.modhoster.de/mods/autoload-pack drin.

MFG Mannie313

**Comment by Stephan-S** [comment]
@Mannie313 Vielen Dank für dein Feedback und  deine Testarbeit!

Eigentlich hätte die Thematik schon seit #22 erledigt sein sollen. Daher gehe ich mal davon aus das @stueja möglicherweise zu der Zeit mit einer alten Version unterwegs war.

Wenn ich bis morgen nichts neues dazu von ihm höre, mache ich dann auch hier zu :-)

**Comment by stueja** [comment]
... vielleicht schaffe ich es noch bis morgen, will aber nichts garantieren, da gerade viel anderes um die Ohren :)

**Comment by stueja** [comment]
Also, nachdem ich die Map nicht mehr spiele und den Mod nicht mehr drauf habe, kann das wahrscheinlich geschlossen werden.
