### ISSUE TITLE
[Feature Request] Tandem trailer support

### ISSUE THREAD

**Issue by realskudd** [Stephan-S/FS19_AutoDrive#1481]
**Is your feature request related to a problem? Please describe.**  
At present, AD doesn't seem to support tandem trailers in a road train configuration. If you have such a configuration, it will only honor the first trailer, and the others will be ignored.

**Describe the solution you'd like**  
If possible given the plugin API, it would be nice for the additional trailers to be recognized, even if not selected.

**Describe alternatives you've considered**  
The only alternative is to run multiple vehicles pulling single trailers, leading to road congestion.

**Additional context**  
None.

**Comment by ArtV-Nef** [comment]
in the latest version of AD everything works, I have a tandem carrying cargo and a tractor and a truck

**Comment by realskudd** [comment]
Orly? I honestly haven't tried it in the latest RC. 

I'll go hang my head in shame now.

**Comment by TobiHH78** [comment]
It works already long time. I guess, that your target point is too close. The point must be a few meters in front also of the 2nd trailer. I usually have the target points approx 50 meter beyond the loading pipe and it works for 100%

**Comment by realskudd** [comment]
Yep, just tested it in that fashion. Closing the issue.

**Comment by realskudd** [comment]
Actually, reopening to ask a question: does the unload target need to follow the same?

**Comment by realskudd** [comment]
And validated.

Yes, both load and unload targets need to be spaced out sufficiently for the rear-most trailer to be loaded.
