### ISSUE TITLE
Button zum Schließen aller Ordner fixieren

### ISSUE THREAD

**Issue by TripleX1978** [Stephan-S/FS19_AutoDrive#1482]
Es wäre schön wenn der Button zum Schließen aller Ordner in der oberen Zeile immer zu sehen wäre und nicht beim Runterscrollen verschwindet.

**Comment by Iwan1803** [comment]
Warum machst du kein Feature Request sondern eine Frage auf?
Den Request gibt es übrigens schon und daher schließe ich diesen doppelten hier:
https://github.com/Stephan-S/FS19_AutoDrive/issues/1414

**Comment by TripleX1978** [comment]
Konnte nur eine Frage eröffnen. Feature Request wurde bei mir nicht angeboten bzw. konnte ich nicht finden.
