### ISSUE TITLE
[Feature Request] Frei belegbarer Button (Werkstatt Button)

### ISSUE THREAD

**Issue by GitTomahawk** [Stephan-S/FS19_AutoDrive#1483]
Ich fände es super wenn man einen weiteren Button (wie den Parkbutton) pro Fahrzeug per Rechtsklick belegen könnte.
Diesen könnte man dann z.B. als Werkstattbutton verwenden. 
Da man mit allen Fahrzeugen ja genauso oft zur Werkstatt wie zum Parkplatz muss wäre das aus meiner Sicht sehr nützlich.

Wenn der Button frei belegbar wäre könnte ihn natürlich jeder so nutzen wie es ihm gefällt.

**Comment by Iwan1803** [comment]
Warum machst du kein Feature Request sondern eine Frage auf?
Um die Größe des HUD nicht zu strapazieren, könnte man einfach alle Favoriten in einen Ordner packen, welcher ganz oben einsortiert wird.
Somit sind keine Button notwendig.
https://github.com/Stephan-S/FS19_AutoDrive/issues/1341

**Comment by GitTomahawk** [comment]
Der Button "Feature Request" öffnet eine Frage. - Geht also nicht anders

**Comment by Iwan1803** [comment]
Seltsamkeiten.... ich habe es korrigiert.
