### ISSUE TITLE
Autom. Kalk nachfüllen funktioniert nicht mehr/Automatic lime refill does not work anymore

### ISSUE THREAD

**Issue by TripleX1978** [Stephan-S/FS19_AutoDrive#1485]
AutoDrive Version: 1.1.0.5-RC4
Karte: NF-Marsch 4fach (Feld 14)

Traktor fährt beladen zum Feld und startet mit der Arbeit.
Bei 0% fährt er zurück zum Abfahrer und verlässt das Feld.
Anstatt zum Silo zu fahren dreht er auf der Karte eine Runde um die Felder, fährt dann wieder zum Abfahrer.
Dann fährt er ein paar Meter aufs Feld und die Prozedur beginnt von vorne.
Wenn man ihn manuell auf die Straße stellt und AD wieder einschaltet, visiert er direkt wieder den Abfahrer an und nicht das Silo, als ob er nicht mitbekommt, dass der Anhänger leer ist.

Diese Einstellung und die Fahrzeugkombi hat in einer der vorigen Versionen (RC2) definitiv noch funktioniert. Mit RC3 bin ich nicht zum Kalken gekommen.

![LS19 - Screenshot 2](https://user-images.githubusercontent.com/63108228/85379592-3af4ac00-b53c-11ea-99c5-8033907d0d3e.jpg)

**Comment by Iwan1803** [comment]
Sorry, aber das Problem ist schon älter und über die Suche zu finden: der Zielpunkt ist zu nah am Trigger.
Setz den einfach mal weiter vom Trigger weg und schon wird es wieder klappen.
Und wenn ich das so auf dem Screenshot sehe, solltest du das gleich auch bei allen anderen Zielpunkten machen.

Kleiner Tip: wenn du den Trecker mit dem Anhänger manuell in den Trigger fährst und manuell beladen/abladen könntest, dann fährst du noch mind. 1 ganze Traktorlänge weiter, bevor du den Zielpunkt setzt.

**Comment by TripleX1978** [comment]
Danke für den Tip.
Werde es mal testen.
Zum Verständnis...das ein falscher Abstand zwischen Zielpunkt und Trigger dafür verantwortlich sein kann dass nicht befüllt wird verstehen ich, aber was hat der Abstand  damit zu tun, dass der Traktor garnicht erst vom Feld zum Zielpunkt fährt sondern einen Rundkurs über das Straßennetz fährt und wieder am Feld auskommt.
Wundert mich halt dass es vorher ohne Probleme funktioniert hat.

**Comment by TripleX1978** [comment]
Hab die Zielpunkte jetzt nochmal neu gesetzt.
Wie ich schon befürchtet habe, hat sich nichts verändert.
Der Traktor fährt vom Feld zum Abfahrer, dann ein Runde über das Streckennetz zurück zum Abfahrer, dann aufs Feld und dann gehts wieder von vorne los.
Da es ja mit RC2 noch funktioniert hat und sich an meinen Fahrzeugen nichts geändert hat, scheint es wohl doch was mit der neuen Version zu tun zu haben oder muss man in der RC4 das jetzt anders einstellen?

**Comment by Iwan1803** [comment]
Ich konnte auf der NFM 4x problemlos düngen und kalken, ohne das er irgendwelche unnützen Schleifen gefahren ist. Feld 14 ist zudem ja auch kein besonderes Feld.
Ist der Anhänger ein Mod oder Vanilla? Irgendwas an dem Streckennetz verändert?

**Comment by TripleX1978** [comment]
Der Anhänger ist ein Mod.
Das Problem liegt auch nicht am Feld, tritt bei jedem Feld auf was ich getestet habe.
Ich habe absolut nichts an den Fahrzeugen oder am Streckennetz geändert. Die einzige Änderung war das Update von RC2 auf RC3 auf RC4

**Comment by Iwan1803** [comment]
... und du nutzt einen Mod-Anhänger. Probier bitte mal einen Standard-Anhänger.

**Comment by TripleX1978** [comment]
Wie gesagt...als es vorher die ganze Zeit funktioniert hat, hatte ich den gleichen Mod-Anhänger. Von daher denke ich nicht dass es daran liegt. Werde es mal testen und berichten.

**Comment by Mike1977** [comment]
Keiner weis so richtig warum es nötig war, aber das Verhalten beim be und entladen bezüglich der Zielpunkte und Trigger wurde geändert. Wenn man zu nahe am Zielpunkt steht entlädt der Hänger nicht oder wird nicht beladen. Der Zielpunkt muss weiter nach vorne geschoben werden, dann funktioniert das wieder. Es gibt dazu auch eine Einstellung - irgendwas mit "entfernung zum abladetrigger" oder so... weis nicht genau. Das musst du dann höher stellen, je nachdem wei weit dein zielpunkt vom trigger entfernt is.
Habe bei mir alle abladestellen ändern und den gesamten Hof neu einfahren müssen nach dem update. Jetzt geht alles wieder.

**Comment by TripleX1978** [comment]
Es hat nichts mit dem Abstand des Zielpunkts zum Trigger zu tun. Er fährt erst garnicht zum Zielpunkt und das auch nur wenn es um Kalk geht. Bei Dünger funktioniert die gleiche Kombi ohne Probleme.

**Comment by Iwan1803** [comment]
Hast du denn jetzt mal einen Vanilla-Anhänger probiert?

**Comment by TripleX1978** [comment]
Nach langem Suchen habe ich den "Fehler" gefunden.
Im AD-Menü stand die Einstellung "Abladen ab Level" auf 0%.
Nachdem ich das geändert hatte lief wieder alles.
Wusste nicht, dass der Wert Einfluss darauf hat.
Dachte der wäre nur relevant bei Arbeiten mit Sammel- und Überladewagen.

**Comment by Iwan1803** [comment]
"Abladen ab Level" wird bei vielen Sachen herangezogen, aber wer ahnt auch schon, das dies jemand auf 0% stellt? 🤪
Vanilla = die im Spiel enthaltenen Sachen und keine Mods 😉

Wenn damit alles geklärt ist, dann mach ich hier mal zu. Ansonsten kannst du jederzeit ein neues Issue öffnen 😎
