### ISSUE TITLE
[BUG] AD says It cant find a route to the field when existing the field.

### ISSUE THREAD

**Issue by masneoquil** [Stephan-S/FS19_AutoDrive#1486]
**AutoDrive Version:** 1.1.0.5 RC4
**Release or Custom Zip:** Custom
**Map (If applicable):** Nebraska Lands
**Vehicle / Type (If applicable):**   
**Multiplayer or Singleplayer:** Singleplayer  

**Describe the bug**  
I'm planting with CP, and refilling with AD. When AD is executing the exit field course and it reaches the target fields it says it can't find a path to the field, when it should be going to the refill waypoint, and stops.
I don't know, but maybe it is the way I recorded the paths. The problem is that sometimes it works, but often it doesn't.
It also seems to work with some tractors but not with others. In this case I'm using the default Fendt 300 Vario
Don't know if the option field exit has anything to do with it. Sometimes by choosing behind start works better.

**If applicable - Steps to reproduce the behavior**  

**Screenshots**  
![Screen1](https://user-images.githubusercontent.com/53353740/85568254-e9195800-b607-11ea-958d-9db9925947e3.jpg)
![Screen2](https://user-images.githubusercontent.com/53353740/85568264-eae31b80-b607-11ea-8ff8-1af23f907086.jpg)

**Comment by masneoquil** [comment]
Just wanted to say that by selecting "Behind Start" on the field exit option worked. But don't know if it should work on any option

**Comment by masneoquil** [comment]
Update: After selecting Behind Start, the first time it went to refill it worked, but after that it didn't anymore.
When trying to exit it seems to not find it, turn inside the field and then CP enables and both workers try to drive resulting in a conflict because one is trying to exit and the other is trying to go back to planting.
here is a video showing the problem:
[https://youtu.be/WuxgLpm2n8g](url)

**Comment by masneoquil** [comment]
I think I managed to "solved" the problem by creating an target in a place where there isn't  any other routes crossing or anything too convulsed.
I still don't understand why it says that it can't find a route to the exit point when it should be calculating a route to the loading point.
I will leave this open. You can close it if you think that it is working as expected and I should be recording better routes.
Thanks all for you hard work!!!

**Comment by masneoquil** [comment]
I'm sorry to say that by creating a target in a place where there isn't any other routes crossing didn't work either

**Comment by Axel32019** [comment]
@masneoquil From your YT video I would say there is an issue with your network. If you discover this message from AD you should check if the vehicle can drive to destination in normal Drive-To mode.

**Comment by masneoquil** [comment]
@Axel32019 Thanks Axel. It is a network issue, but if I start AD at the field, it finds a route without problem.
What I found out is that the problem is, when AD reaches the field exit then tries to find a route (like deactivating and activating AD) and if there is several crossing lines at that point, sometimes it chooses a line without a route to the destination.
In this case for example, those blue lines are right in front, and I bet that sometimes chooses one of those lines, and because they go both direction, it tries to go to the wrong side.
Short answer is, the field exit should be as easy as posible. Without too many options to choose from.
I'm playing on a new map, and the fields exists are simple one direction routes, and so far everything is working great.
