### ISSUE TITLE
Search & Folder 

### ISSUE THREAD

**Issue by dennisblack777** [Stephan-S/FS19_AutoDrive#1487]
Hallo,

mir ist gerade mit der aktuellen AD-Version aufgefallen, dass wenn ich einen Streckenpunkt suche und mehrer Ordner habe, muss ich jeden einzelnen Ordner manuell öffnen und schauen ob der Punkt darin liegt.

Wäre es möglich autom. die Ordner zu öffnen wo die Suche einen Treffer gefunden hat?

Danke und Grüße

**Comment by Lars-LS17** [comment]
Die Idee finde ich auch super.

Oder man macht es so wie im Courseplay. Da verschwinden alle Ordner, wo die Suchfunktion kein Treffer hat.

**Comment by Axel32019** [comment]
Ist in Version 1.1.0.5-RC6 (23.09.2020) enthalten.
