### ISSUE TITLE
[BUG]Apostrophe getting mishandled on opening config file at map/mod loading.

### ISSUE THREAD

**Issue by Thorn177** [Stephan-S/FS19_AutoDrive#1488]
**AutoDrive Version:** 1.1.0.4   
**Release or Custom Zip:** Release  
**Map (If applicable):** No Man's Land
**Vehicle / Type (If applicable):**   
**Multiplayer or Singleplayer:** Singleplayer  

**Describe the bug**  
When the map loads, the existing autodrive config file AutoDrive_No_Man's_Land_config.xml gets deleted and replaced with an empty file that only has an open close tag of <AutoDrive/>.  A review of the log file reveals an error from a file named 

AutoDrive_No_Man's_Land_config.xml. 's_Land>

Saving the game at this stage will only save AD settings.  Copying a backup copy of the config file in to replace does not fix it.  It still saves just the AD settings the next time the game saves. I have as a result been keeping a copy of my network on Routes Manager.  Loading this restores the network, but none of the map markers work.  Driving to one of the map markers, selecting Create from the HUD, and then reset, will restore the network to a working state.  Which map marker will trigger this is a bit random.  Until the network is restored properly, any game saves still only save the AD settings.  Once it restores the map markers, AD works as reliably as ever and saves properly.

**If applicable - Steps to reproduce the behavior**  
Load the map No Man's Land
[log.txt](https://github.com/Stephan-S/FS19_AutoDrive/files/4832575/log.txt)

**Screenshots**

**Comment by Iwan1803** [comment]
https://github.com/Stephan-S/FS19_AutoDrive/wiki/Release-Notes#changelog-1105-rc4-16062020
> FIX: save game error if the map name has a ' in the name

If you restore a backup, you've got to rename the file and also check the map name inside of it.

**Comment by Thorn177** [comment]
Apologies for missing the original issue.  I went looking for the word apostroph (I believe that is the German for apostrophe) only, not a literal '.  

The backup copy was just a copy, not a version that had been through any backup software, so apart from the time stamp, should be the same.  It was done in the hope that AD would read it at map start, but it clearly doesn't.

Is the behavior of the Route Manager load a separate bug then?  It loads in the way points and the map markers into memory, but not the config file.  Changing into edit mode, you can clearly see it's all there, but none of the map markers are available to the AD HUD drop down list, and saving the game at this point does not add the network into the config file.  That only starts happening once I've got the network working again.

**Comment by Iwan1803** [comment]
If you import a config with Route manager, you need to save and restart the map. The config will only be loaded by that way.

**Comment by Iwan1803** [comment]
As the questions should be answered -> closed.
If you need further help, please open a new issue.
