### ISSUE TITLE
[Question] Release informations

### ISSUE THREAD

**Issue by paul-dotcom** [Stephan-S/FS19_AutoDrive#1489]
Hi, ich kann leider keine Punkte mehr per Maus in Ordner verschieben. Ist das ein Bug oder gibt es eine neue Funktion? Auch kann ich keine neuen Ordner erstellen

EDIT: War meine Schuld, habe den Editormodus nicht angehabt^^

Und noch eine Frage: gibt es irgendwo so etwas wie eine Legende, in der neue Funktionen beschrieben werden? Habe gesehen, es gibt jetzt neben mehreren Zielen auch mehrere Startpunkte, nur weiß ich nicht, was es damit auf sich hat

**Comment by Iwan1803** [comment]
Release Notes findest du hier: https://github.com/Stephan-S/FS19_AutoDrive/wiki/Release-Notes
Ein Video dazu: https://youtu.be/fsQn6p7ASWo
