### ISSUE TITLE
[BUG]Probleme mit der Innenkamera / Problems with Indoor Cam

### ISSUE THREAD

**Issue by timmi4026** [Stephan-S/FS19_AutoDrive#1490]
AutoDrive Version: 1.1.0.5 RC4
Release 
Karte (falls relevant): Alle
Fahrzeug(art) (falls relevant): Alle

**Beschreibe den Bug**
Wenn ich im Spiel VCA und AD aktiviere habe ich sobald ich in einem Global Company Trigger fahre der in höhe der Indoor Cam ist Kollision Probleme, die Kamera kippt in der Innenperspektive nach unten. Stelle ich die Kollisionshöhe über Grund runter auf 1,25 m passiert das nicht mehr.
Passiert in allen Fahrzeugen.

LG Timmi

**Comment by Iwan1803** [comment]
Kleiner Hinweis, welcher extra oben als erstes angepinnt ist: https://github.com/Stephan-S/FS19_AutoDrive/issues/1071
Ich zitiere dich mal aus Discord:

> Wenn ich Ad oder VCA nicht ins Spiel lade passiert das nicht

Was denn nun: AD oder VCA oder beides zusammen?
Wenn es durch die Einstellung der Kollisionshöhe regeln konntest, wo ist denn dann jetzt bitte der Bug?
Außerdem glaube ich nicht, das es auf allen Karten passiert.

**Comment by Iwan1803** [comment]
Da ja schon Hilfe in Discord gegeben worden ist -> geschlossen.
