### ISSUE TITLE
Maximum trigger distance[Question]

### ISSUE THREAD

**Issue by Scania1983** [Stephan-S/FS19_AutoDrive#1492]
**Question:**   
I've got a question...

Maybe it is possible to extend the maximum trigger distance? With large fields the loader can't reach the unloader to start driving.

edit: or link the unloader to a loader somehow, loader is driving with CP and unloader with AD.

**Comment by Iwan1803** [comment]
If combine is set to "search for unloader" = yes, then the distance is ~300m.
Set it to no, set the same target point for the combine as the unloader has and then there is no limit.

**Comment by Scania1983** [comment]
If i set it to no the combine doesn't call and the unloader doesnt start driving even if it is next to the combine

**Comment by Iwan1803** [comment]
Sounds like you didn't set the same target point for the combine and the unloader.
Are you using CP in a newer version? In the settings you should set that the pipe allways should be open for unloading.

**Comment by Scania1983** [comment]
Sorry for the late reply, it looks like it works better now, when a big field is ready to harvest i will try again and report back

**Comment by Iwan1803** [comment]
No further feedback -> closed.

Also please update to 1.1.0.5-RC5, try again and if the problem still exists, then open a new issue.
