### ISSUE TITLE
An mehreren Zielen entladen / unload at several targets

### ISSUE THREAD

**Issue by TripleX1978** [Stephan-S/FS19_AutoDrive#1496]
Habe auf meinem Hof einen Wassertransporter, der nacheinander alle Wasserentladetrigger abfahren soll.

Folgendes passiert:
- Traktor fährt zum Silo und belädt
- Traktor fährt zum 1. Ziel und entlädt komplett
- Traktor fährt trotz 0% zum 2. Ziel
- Traktor fährt zum Silo und belädt
- Traktor fährt zum 1. Ziel usw.

Wenn ich auf dem Weg zum 2. Ziel AD kurz deaktiviere und wieder aktiviere switcht er direkt auf das Silo zum beladen.

Ist das jetzt ein BUG oder muss ich irgendwas anders einstellen.
Hab schon einige Einstellungen ausprobiert ohne wirklichen Erfolg.

**Comment by Iwan1803** [comment]
Ich hab 2 Wassertransporter und 1 mit Diesel am Laufen. Alle haben jeweils nur 1 Ladeort und x Abladeorte. Das ganze funktioniert schon seit Monaten soweit fehlerfrei.
Welche AD-Version nutzt du und wie sind deine Einstellungen?

**Comment by TripleX1978** [comment]
Hier die Screenshots meiner Einstellungen.

![LS19 - Screenshot 3](https://user-images.githubusercontent.com/63108228/86222227-3fe1dd00-bb86-11ea-95fc-775bb48cd386.jpg)
![LS19 - Screenshot 4](https://user-images.githubusercontent.com/63108228/86222230-407a7380-bb86-11ea-8484-bbfb495c6e37.jpg)
![LS19 - Screenshot 5](https://user-images.githubusercontent.com/63108228/86222235-407a7380-bb86-11ea-83f1-46fa9b5029c6.jpg)
![LS19 - Screenshot 6](https://user-images.githubusercontent.com/63108228/86222236-41130a00-bb86-11ea-898e-398ab7df6279.jpg)

**Comment by Iwan1803** [comment]
Stell mal testweise "Abladen ab Level" auf 85%.

**Comment by Iwan1803** [comment]
Please update to 1.1.0.5-RC5, try again and if the problem still exists, then open a new issue.
*Bitte aktualisiere auf 1.1.0.5-RC5, versuche es erneut und und wenn das Problem weiterhin besteht, erstelle ein neues Issue.*
