### ISSUE TITLE
Tankstelle Vorgeben

### ISSUE THREAD

**Issue by Wolle1976** [Stephan-S/FS19_AutoDrive#1497]
Hallo,
gibt es die Möglichkeit AD zu sagen an welcher Tankstelle er zum Tanken soll?
Ich habe das Problem das mir immer wieder einer entwischt und dann durch die halbe Karte fährt um zu Tanken, obwohl auf dem Hof eine Tankstelle steht und auch ein Kurs dran vorbei führt.

**Comment by Iwan1803** [comment]
Mein Hof liegt ziemlich zentral und ich habe nur eine Tankstelle dort, direkt hinter dem Werkstatt-Trigger und dem Kärcher.
Könnte man eine Tankstelle bzw. einen Zielpunkt vorgeben, wäre das schon nice, aber was wenn man mehrere hat?

**Comment by Easton97-Jens** [comment]
Kann man das nicht viel so wie mit der parkplatzvergabe machen mit den Tankstelle Zuordnung weil ich habe das auch auf unseren Server, das Problem das wir mehrere Tankstellen habe. Jedes Mal fahren die LKWs im Kreis und teilweise bleiben die Sogar liegen wegen Spritmangel. Da wir viele Fahrzeuge auf Tour schicken und denken nicht daran nach zu schauen ob sie getankt werden müssen da wir viele andere Sachen machen.

**Comment by Axel32019** [comment]
Das geht gewissermaßen jetzt schon:
1. AD sucht im Umkreis von 15m (Luftlinie!) um Zielpunkte nach Tankstellen
2. Wenn getankt werden soll wird die nächst gelegene (Luftlinie!) Tankstelle mit Zielpunkt angefahren, siehe 1.
3. Weiter ist eine Benachrichtigung hinzugekommen wenn ein Fahrzeug zum Tanken fährt #1431

**Comment by Axel32019** [comment]
@Easton97-Jens 
Hast Du o.g. mal ausprobiert?
Aus meiner Sicht ist das damit gelöst.

**Comment by Iwan1803** [comment]
Da 1.1.0.6 released wurde, mach ich hier mal zu // As 1.1.0.6 was released, i'll close here 😎
