### ISSUE TITLE
[BUG] Can't drive when starting from a node, but can when starting one node closer to destination

### ISSUE THREAD

**Issue by ValokAsura** [Stephan-S/FS19_AutoDrive#1499]
**AutoDrive Version:** 1.1.0.5-RC4   
**Release or Custom Zip:** Release  
**Map (If applicable):** Fenton Forest 4x by Stevie 1.50.1, Lakeland Vale by Stevie 1.50.1.11, Oakfield Farm 1.1.1.0
**Vehicle / Type (If applicable):**   Any vehicle
**Multiplayer or Singleplayer:** Singleplayer  

**Describe the bug**  
Edit: Seems to work fine on one-way paths now, but I don't know what changed. Also included a better video to demonstrate my changes: https://www.youtube.com/watch?v=Dfh0k-5lQ64

Probably easiest to watch the short video instead of read: https://www.youtube.com/watch?v=fYebszMfPhs

I created a two-way route, with a few offshoots, with a "Home" and "Shop" point at distant locations. The first time I tried to drive the route from Home -> Shop, I got the error "Driver can't reach Shop." This is pretty standard for me and is always because I forgot to link nodes at a turn or intersection. I manually drove along the paths I created while occasionally clicking the Start button until it started working so I could find the break. When it did start to work, I noticed there was no break in the node path, it just simply wouldn't work until I reached a certain point. I could see the nodes were connected, and I even broke/rebuilt them but Autodrive wouldn't work until I moved up to a certain node.

I deleted the nodes, re-linked them, tried making them one-way/two-way, but nothing would work. It seems like there is a maximum path length Autodrive is willing to follow in this instance. I don't believe this to be the case because I've created much longer and complicated paths and Autodrive always worked fine with them.

**If applicable - Steps to reproduce the behavior**
I don't know how reproducible it is, but it has happened to me on 3 separate maps in the last week or so. I thought it was a fluke so this time I put in some extra effort to determine if the error was mod or user. The log file linked below is after a fresh Steam file verification, and with the only mods enabled being the map Fenton Forest 4x by Stevie and Autodrive.

In the video, all of my mods are enabled, but I was able to reproduce it with only the map and Autodrive enabled.

**Screenshots**  
https://www.youtube.com/watch?v=fYebszMfPhs
https://www.youtube.com/watch?v=Dfh0k-5lQ64
Log: https://controlc.com/052a4efb
Routes.xml: https://controlc.com/95c8c4c0
Route File: https://controlc.com/3e887e69

I love this mod so much! Thank you for taking so much time and effort to create it. It greatly enhances the FS experience.

**Comment by Axel32019** [comment]
Could you please provide the AutoDrive_...config.xml from your savegame. The exported routes does not help.
Thanks for your support in advance!

**Comment by Axel32019** [comment]
@ValokAsura Any update?

**Comment by ValokAsura** [comment]
Oh, jeez. I'm so sorry. I didn't see a response until today. I haven't touched FS in a while but I still have those files. I've uploaded them for you.

Lakeland Vale: https://pastebin.com/JufVfGQT
Fenton Forest: https://pastebin.com/aQYqW1xx
Oakfield Farm: https://pastebin.com/Abk8SSwh

**Comment by Axel32019** [comment]
Hello @ValokAsura 
I tried to reproduce the issue from you YT video at Fenton Forest, but at the same position the truck tries to drive in the reverse direction, not like in your video in front direction. The truck always finds the route to the shop.
Might there be a change in the road network between the video and the AD config you posted?

**Comment by Iwan1803** [comment]
Da 1.1.0.6 released wurde, mach ich hier mal zu // As 1.1.0.6 was released, i'll close here 😎
