### ISSUE TITLE
Keine Kurse nach erneutem Spielstand laden, Ursache Mapname

### ISSUE THREAD

**Issue by haamic** [Stephan-S/FS19_AutoDrive#15]
Hallo Stephan, ich hatte das Problem, das nach dem Neustart des Spielstandes keine Kurse mehr da waren.
Die Ursache hab ich gefunden und behoben.
Der Fehler war, das mein Mapname Satzzeichen enthielt, die die generierte XML nicht verarbeiten konnte. der Mapname darin war nicht mehr identisch mit dem eigentlichen Namen.
Durch Änderung es Mapnamens und anpassen des Namens in  der XML mit dem bereits eingefahrenen Streckennetz, steht mir nun nach dem Laden alles wieder zur Verfügung.
Super Mod, bin gespannt auf evtl. noch neue Sachen die implementiert werden.
Wie ich gelesen habe, wäre eine Speicherung der Geschwindigkeit für jedes Fahrzeug aufwändig.
Das ist mir auch aufgefallen, das man da immer von 60 runterregeln muss. oder man stellt in der Lua seinen bevorzugten wert selber ein. Aber das ist nur ein kleines Übel, damit kann man leben.
Viele Grüsse Micha

**Comment by Stephan-S** [comment]
Hallo Micha, danke für die Rückmeldung. An welchen Satzzeichen scheitert es denn aktuell noch? Ich bin dabei alle Zeichen nach und nach zu verarbeiten. Aber ich möchte keine entfernen die kein Problem sind, da ich damit möglicherweise bereits erfolgreich eingefahrene Kurse und xml Files unbrauchbar mache.

Die Geschwindigkeit werde ich erstmal auf 50 runter regeln. Welchen Wert stellst du denn typischerweise ein? Ansonsten muss ich den Bremsweg besser anpassen, damit er rechtzeitig abbremst

**Comment by haamic** [comment]
ich glaube bei mir hat er aus einem Punkt einen unterstrich gemacht und das Komma hat er übernommen, aber daraufhin war der Text in der XML (notepad++) dahinter rot.
da war dann irgendwas verquer...Geschwindigkeit nehm ich eigentlich nur 35, macht halt jeder wie er möchte.
Andere Frage, wenn ich Wegpunkte lösche, kann es sein das trotzdem noch etwas zurückbleibt und ich dann fälschlicher weise, wenn diese zu nahe an anderen punkten liegen,diese Stellen mit dem Kurs verbinde? Hab grad das problem, das ich eigentlich optisch scheinbar alles verbinden hab, aber trotzdem findet er keine Route zum Ziel.
Ist es Zukünftig evtl. möglich umfangreichere Routen mit mehreren Zielen zu erstellen?
z.b. vom Hof zu Feld X, dann auf Feld X arbeiten, dann zurück zum Hof....evtl. auch am feld die Geräte einschalten zu lassen und wieder aus beim Verlassen......
Gruss Micha

**Comment by Stephan-S** [comment]
Das Komma habe ich eben in einer Version gefixed. Lad dir einfach die 1.0.0.2 herunter, damit sollten dort keine Probleme mehr entstehen. Dort wird auch die letzte gesetzte Geschwindigkeit gespeichert und beim Neustart auf alle verteilt.

Wenn du Wegpunkte löschst, kann es sein das du den letzten übersiehst, da ja von dort aus keine wege mehr wegführen. Den siehst du nur wenn du nah dran bist und dein Traktor eine rote Linie dahin anzeigt.

Wenn du möchtest kannst du mir gerne deine Datei hochladen wenn du den Fehler nicht findest und ich schau mir mal an was da schief läuft.

Umfangreichere Routen werde ich nicht einführen. Dafür ist Courseplay viel geeigneter. Sprich Feldarbeiten wird es mit AutoDrive nie geben.

Viele Grüße,
Stephan

**Comment by haamic** [comment]
Feldarbeit war auch ein blödes Beispiel.
Ich meinte eher sowas, wie "Fahre zu Ziel B über Zwischenziel A".
Schönes Wochenende
Micha

**Comment by haamic** [comment]
Hallo Stephan. Welcher Eintrag ist für die Höhe über dem Boden des angezeigten Streckennetzes verantwortlich? Ich möchte die Höhe ein bisschen erhöhen, da manchmal im hohen dichten Gras es etwas kniffelig ist, fehlende Verbindungen zu identifizieren.  Evtl. Wäre Integration der Höhenregulierung im editormodus mittels Tasten möglich?

**Comment by haamic** [comment]
Hallo Stephan, hatte jetzt wieder das Problem, das nach beenden eines Spieles auf einer neuen Karte, keine Kurse nach dem laden mehr da waren. 
der ursprüngliche name enthielt ein "x"     "8xmap" , nach umbennen geht es nun.
Ist mir unerklärlich, aber kann das wirklich am "x" gelegen haben?
Gruss Micha
