### ISSUE TITLE
Issue für "einsame" wegpunkte

### ISSUE THREAD

**Issue by andreasthu** [Stephan-S/FS19_AutoDrive#150]
Hallo stephan.

Mir ist nun aufgefallen, das wenn man Kurspunkte oder Kurslinien löscht, öfter mal einzelne Kurspunkte übrigbleiben, die nicht sichtbar sind, weil sie eben nicht mit einer blauen Linie oder einer pPfeillinie an einem anderen hängen.
Man kann sie zwar finden wenn man mit dem Traktor daneben steht, da dann die rote Linie darauf "ins nichts" zeigt.
Könnte man solche einsamen Punkte ev mittels Kreuzchen X oder Kreis O kenntlich machen?
Lg
Andreas

**Comment by andreasthu** [comment]
Danke, funktioniert

**Comment by Stephan-S** [comment]
Gerne,
war ja ein sinnvoller Vorschlag :-)
Danke dir
