### ISSUE TITLE
Move option for folders

### ISSUE THREAD

**Issue by wilbertlandry** [Stephan-S/FS19_AutoDrive#1500]
**Question:**   
I've got a question...New recorded routes are saved in default folder. V 1.1.0.3  has the option to move to different folder. V 1.1.0.4 and .5 do not have a move option. Is this an oversite or am I missing something?

**Comment by 60erjonny** [comment]
Hallo
In the new versions, the points just created can be moved to the newly created folder in editor mode by holding down the mouse button. Sorry for vor my english...

**Comment by Iwan1803** [comment]
To avoid "problems" in normal play, you need to activate the edit mode. 
Then you can create, move, delete and rename target points.

**Comment by wilbertlandry** [comment]
Thanks, Figured it was something simple. Tried everything except that

**Comment by Iwan1803** [comment]
For short questions like this one you could also ask in Discord: https://discord.gg/9D4B5hX
