### ISSUE TITLE
Drecher Abtanken/Drech tanking

### ISSUE THREAD

**Issue by John-Deere89** [Stephan-S/FS19_AutoDrive#1502]
Warum kann AD denn Drescher nicht wärend der Fahrt abbunkern sondern nur wenn er voll ist 100%. Ich kann einstellen was ich will ober nun bei 80 oder 60% starten soll er fährt erst dann los wenn er 100% hat und steht. Warum?
Kann man das heben?

Viele YT Videos an gesehn aver keins dabei wo AD neben denn Drescher her Fährt.
Tut auch an gesehn ich mach genau das selber geht leider auch nicht :/

Why can't AD thresh bunkers while driving but only when it is full 100%. I can set what I want or should start at 80 or 60%, it only starts when it is 100% and has stopped. Why?
Can you lift that?

Many YT videos on aver seen none where AD drives alongside the thresher.
Also looks good, I'm doing exactly that myself, unfortunately, also not: /

**Comment by Iwan1803** [comment]
AD kann während der Fahrt abtanken und das ist keine Einstellung vom Abfahrer.
Die Frage, die sich mir stellt: wer steuert deinen Drescher?

**Comment by John-Deere89** [comment]
mein Drescher?  CP   Warum?

**Comment by Iwan1803** [comment]
CP ist an der Stelle seltsam. Ich hatte heute 2 Drescher auf einem Feld unterwegs. Beide waren in CP eingestellt, das sie während dem Abtanken nicht anhalten sollen.
Bei dem einen hat es mal geklappt und mal nicht, bei dem anderen klappte es nie.
Da AD an der Stelle beim Drescher nicht eingreift sondern CP das alleine macht, wird der "Fehler" wohl eher in CP zu suchen sein.

**Comment by John-Deere89** [comment]
also AD hat noch nie wärden der fahrt Abgebunkert bei mir
Ich habe mich deswegen auch schon mit anderen Unterhalten und die meinen auch AD Bunkert nur im stehn und wenn der Drescher voll ist ab daher scheint das noch nicht zu zu gehn 
habe auch noch kein Video gesehn wo AD daneben her fährt :/

**Comment by Styla84** [comment]
Ich hab bei mir im Drescher bei CP eingestellt das er weiterfahren soll beim entladen und in AD  Abfahrer rufen bei x% 0 angegeben. Klappt auch stellenweise mehr oder weniger. Kann Zufall sein oder auch nicht aber stellenweise fährt er dem Drescher wie beim Häcksler daneben her.

**Comment by John-Deere89** [comment]
Wie schon gesagt bei mit fährt er auch los wenn ich ihn ehr komm lasse aber er fährt dann nur zum letzten Punkt wo der Drescher Stand wo der Drescher dann schon weiter ist und so gehts so lange weiter bis der Drescher voll ist

**Comment by John-Deere89** [comment]
ich habe es mal aufgenommen 
https://drive.google.com/file/d/1VbvNgTp4ueDiNjrb2llEwOoKwg-qjMO6/view?usp=sharing

Welchen helfer nutzt Ihr denn? AI Mod?
Bei mir Fährt er auf net weiter beim Abbunkern obwohl ich eingestellt habe das er das tun soll

**Comment by haamic** [comment]
hier ein "Beweisvideo", das es geht. 
Der Abfahrer fährt neben Drescher her und übernimmt die Ernte.
Abfahrer fährt mit AD, Drescher macht Feldarbeit mit CP und hat als AD-Einstellung, "Abfahrer rufen bei 0%"

https://www.magentacloud.de/lnk/LOCAHkbA

**Comment by haamic** [comment]
hier ein "Beweisvideo", das es durchaus funktioniert.
Drescher macht Feldarbeit mit CP und hat in den AD-Einstellungen "Abfahrer rufen bei 0%".
Abfahrer fährt mit AD neben her und tankt brav den Drescher ab, bis der Anhänger voll ist

https://www.magentacloud.de/lnk/lLCgnOkY

**Comment by John-Deere89** [comment]
Intressiert ja keinen
geht drum das es nicht geht?!

**Comment by haamic** [comment]
> habe auch noch kein Video gesehn wo AD daneben her fährt :/

klar geht das drum hab ich das video ja gemacht

**Comment by John-Deere89** [comment]
@Iwan1803   Warte noch auf eine Rückmeldung???

**Comment by Iwan1803** [comment]
@John-Deere89 
welche Rückmeldung willst du haben? Das es bei einigen geht und bei anderen nicht oder das wir nun nichts anderes untersuchen als deinen Fall?
Sorry, aber es gibt gerade Probleme, welche in der Prio deutlich wichtiger sind als deins.
Vielleicht verrät @haamic ja seine Einstellungen, mit denen es ja zu klappen scheint.

**Comment by haamic** [comment]
so läufts bei mir wunderbar

![einstellung-abtanken](https://user-images.githubusercontent.com/28841989/87339188-8819db80-c546-11ea-93ac-509888e473a9.jpg)

**Comment by John-Deere89** [comment]
@Iwan1803  Musst ja nicht gleich so unfreudnlich werden
vlt hättest du ja auch sagen können wie es geht aber naja...

**Comment by Iwan1803** [comment]
Sorry falls das unfreundlich rüberkam, aber ich mag es einfach nicht, wenn Leute auf eine Rückmeldung warten, die nicht zugesagt wurde.

**Comment by John-Deere89** [comment]
@haamic Also bei mir ist alles das gleiche aber er macht es einfach nicht   also kann es nicht an mir Persönlich liegen das er Falsch eingestellt ist

Dann kommen AD & CP nicht mit einader klar was das neben her fahren an geht  alles andere geht ja wunder bar   
Wär schön wenn man da das noch hin bekommen würde dann wärden die beide super mods die perfekt hamonieren :)

**Comment by Iwan1803** [comment]
Spielst du zufällig auf einem Server?

**Comment by DiTechRacer** [comment]
Im MP macht das Abtanken generell große Probleme wie ich festgestellt habe. Für den Admin weniger als für den Mitspieler. Hoffe da wird bald etwas getan..

LG Tim

**Comment by Axel32019** [comment]
No update -> Closed.
