### ISSUE TITLE
[BUG] Can't refill Horsch Maestro 12SW Planter with fertilizer

### ISSUE THREAD

**Issue by cosmin-margarit** [Stephan-S/FS19_AutoDrive#1503]
**AutoDrive Version:** 1.1.0.5.RC4   
**Release or Custom Zip:** RC4
**Map (If applicable):** Tested on Ravenport and Green River
**Multiplayer or Singleplayer:** Singleplayer  

**Describe the bug**  
Can.t refill the planter with fertilizer no matter what combination of fillType I try. It refills just the seeds.
Tried to reset the tractor and planter but didn't work.
Tractor and planter are game default, no mods.
The seeder can refill no problem but seems that the planter with the tank type of reservoir doesn't refill properly.

Can't refill planter: https://drive.google.com/file/d/113oxkk__jzFipEIbcEKU1KPCRbRr6vCs/view?usp=sharing

Seeder is refilled ok: https://drive.google.com/file/d/1ndZFv04Jk6PGrzisGk9Oolsky2ck6J7V/view?usp=sharing

The logs are clean, thank you! :)

**Comment by Iwan1803** [comment]
Why would it be a bug from AD and not from this container?

**Comment by cosmin-margarit** [comment]
> Why would it be a bug from AD and not from this container?

Because I tried with the multi silo one too and still deosn't refill the planter and also tried with pallets from the store (but here I'm not sure if it's supposed to work or not).

**Comment by Iwan1803** [comment]
Please update to 1.1.0.5-RC5, try again and if the problem still exists, then open a new issue.
*Bitte aktualisiere auf 1.1.0.5-RC5, versuche es erneut und und wenn das Problem weiterhin besteht, erstelle ein neues Issue.*
