### ISSUE TITLE
[Feature Requests] several

### ISSUE THREAD

**Issue by Rikkavidu** [Stephan-S/FS19_AutoDrive#1504]
Hi all!
Ich habe mehrere Vorschläge:
1) Den "intelligenten Helfer" oder auch "AI Vehicle Extension" integrieren oder was dies bezüglich eigenes schreiben, damit man auch im AD Feldarbeiten machen kann (wie im Courseplay).
2) Das Menü IMMER aufrufen können, AUCH zu Fuss. Ich habe bemerkt, dass ich gerne Fahrer auch aus der Ferne heraus gerne unter Kontrolle habe. AD ist ja auch zum "automatischen Fahren" gedacht, ohne das man in Fahrzeug sizt.
3) Anpassbare Fahrzeugnamen: Man kauft ein FZ, ok. Die Meldung heisst dann sowas wie "Der Fahrer von Phoenix...". Was ist, wenn ich 10 Phoenixe habe? I size in einem FT, und beim Trecker-TAB, also da wo man die spezifischen Fahrzeugeinstellungen für jedes einzelne FZ einstellt, den Kaufnamen einfügen, den man dann ändern kann in "Mais abfahrer 1" oder was auch immer.
4) Punkte in Kurven verschieben: Wenn ich beispielsweise eine Linkskurve fahre, dann wird das korrekt aufgezeichnet. Wenn ein Fahrer mit dem selben FZ mit dem das aufgezeichnet wurde, die Strecke abfährt fällt mir auf, das der Fahrer häufig nicht so einlenkt, wie ich es tat, wodurch er dann bei schmalen Strassen hängen bleibt. Vorschlag dazu: Bei einer scharfen Linkskurve (meistens abbiegen) die Aufzeichnungspunkte automatisch ein Stück links am FZ plazieren, damit wenn AD fährt das wieder ausgeglichen ist.

Ich wäre Dankbar über Statusmeldung, ob meine Vorschläge, wenn ja, wie, angenommen wurden oder nicht.
Ich sende hiermit die besten und freundlichsten Grüsse!

**Comment by Iwan1803** [comment]
zu 1.: gibt es schon seit 1.1.0.5-RC3
Per Rechtsklick auf den CP-Button kann man zu AIVE wechseln

zu 2.: sorry, aber so etwas wird es nicht geben
Nicht falsch verstehen, aber wer alles "fernsteuern" möchte, sollte wohl eher einen Manager statt einem Simulator spielen.

zu 3.: gibt es schon sehr lange
Man muss nur in den LS19-Einstellungen eine Tastenkombi für "AD: Vergebe Fahrer Namen" eintragen, über welche man dann dem Fahrzeug einen Namen geben kann. Dieser wird allerdings nur von AD und nicht von anderen Mods benutzt.

zu 4.: das sind die Tücken der Technik 😉
Es wäre ein enormer Aufwand, so ein "vorausschauendes" Aufzeichnen zu programmieren und so lange wir keine KI in AD einbauen können, muss man wohl seine Strecken selber korrigieren oder bei Kurven einfach weiter außen oder innen fahren.

**Comment by Rikkavidu** [comment]
Hallo, und vielen Dank für deine Antworten! Das mit den Kurven kann ich nachvollziehen und verstehe ich. Das mit den Fahrzeugnamen wusste ich nicht. Bitte vergiss nicht, dass ich bis gestern noch die Version im modhub benutzt habe. Ich kenne die 1.0.0. 5 Versionen also alle nicht. Ursprünglich habe ich Autodrive ja wie gesagt verwendet weil es im modhub verfügbar ist, und courseplay nicht. Kennengelernt habe ich den Mod durch Mario hirschfeld. Was er in seine Tutorials nicht gezeigt hat, kenne ich dementsprechend leider auch nicht. Ich habe zur Erhöhung des Realismus Grades Mods installiert, die das teleportieren auf der Map und in Fahrzeuge verhindern. Es wäre durchaus realistisch wenn man einem Fahrer eines bestimmten Fahrzeuges aus der Entfernung Befehlen kann zu einem bestimmten Ziel zu fahren. Das wäre so, als wenn man ein Funkgerät oder Walkie-Talkie benutzen würde. Wenn ich beispielsweise am Hof vorne, und ich dort leider kein Fahrzeug habe könnte ich einen Fahrer Befehlen dorthin zu fahren und mich gewissermaßen abzuholen. Oder auch bei der Forstarbeit: ich kann dem LKW befehlen Holz verkaufen zu fahren, und kann währenddessen mit dem Scorpion King schon mal weiterarbeiten. Du hast ja geschrieben, dass du den AD ja auch sehr viel im Singleplayer verwendest. So läuft also jedes Mal zum Fahrzeug, startest die Fahrt, und steigt dann wieder aus? Ich persönlich finde das ziemlich umständlich, und das ist jetzt in keinster Weise schlecht, negativ oder böse gemeint! Wenn es gewisse von mir vorgeschlagene Funktionen schon wie du sagst sehr lange gibt, dann sollte man vielleicht eine aktuellere Version im Spiel internen modhub hochladen? Denn wie gesagt, ich kenne nur die 1.0.0. 4. Noch mal die besten und herzlichsten Grüße! Ich werde mich mit den neuen Funktionen des mots heute auf jeden Fall beschäftigen.

**Comment by Iwan1803** [comment]
Im Modhub ist der Release 1.1.0.4 vorhanden, den Releasekandidaten 1.1.0.5-RC4 gibt es nur hier auf github.
Wenn der RC ausgereift ist, wird es auch eine neuere Version im Modhub geben.
Auf meinem Youtube-Kanal gibt es Videos zu den Release-Versionen und auch div. Anleitungen:
https://www.youtube.com/watch?v=RmgjiE58Vt8&list=PL5cOkXj5iscpEZSnI-w1jv3p304IRzZZP

Wir sollen also eine Lösung dafür finden, weil du nicht zu den Fahrzeugen hinfahren willst und das Tabben deaktiviert hast? 🤨
Sorry, aber der Aufwand-/Nutzenfaktor wäre vermutlich nicht gerechtfertigt.

**Comment by Rikkavidu** [comment]
Hallo nochmal: Ich habe den AIVE aber KEIN Courseplay installiert. Ich habe also KEINEN CP-Button, den ich drücken könnte. Beste Grüsse.

**Comment by Iwan1803** [comment]
-> https://github.com/Stephan-S/FS19_AutoDrive/issues/1479

**Comment by Iwan1803** [comment]
Da schon älter und 1.1.0.6 released wurde -> closed 😎
