### ISSUE TITLE
[BUG] Wrong Truck Position

### ISSUE THREAD

**Issue by Rikkavidu** [Stephan-S/FS19_AutoDrive#1505]
Hallo,
mir fiel schon vorher auf, das Fahrzeuge Kurven zu weit nehmen. Jetzt fand ich heraus, dass es nur um LKWs geht.
Trecker und Autos fahren gut. Ich weiss, woran es bei den LKWs liegt: An der roten Positionslinie. Die Positionslinie ist genau in der Mitte vom LKW, also kurz vor den Hinterrädern. Deshalb fährt der LKW Kurven zu weit.
Nötige Korrektur: Die Positionslinie muss genau über dem Fahrerhaus, also viel weiter vorne bei der Lenkachse (Vorderachse) sein, dann könnte es klappen.
Vielen Dank und beste Grüsse.

**Comment by Iwan1803** [comment]
Dies ist kein Bug, sondern liegt an Giants bzw. den Fahrzeugen selber. Hierauf haben wir keinen Einfluss.
Einzige Möglichkeit: pass deine Kurven an.

**Comment by Rikkavidu** [comment]
Ok, danke.
