### ISSUE TITLE
[Question/Request] Option to toggle on/off AD controls in "Controls" Window

### ISSUE THREAD

**Issue by DreadPirateLynx** [Stephan-S/FS19_AutoDrive#1506]
After installing this mod, my controls window takes up too much screen real-estate. I would like to be able to disable this mod's keybindings from said window. If toggling the option is not possible for some reason, could you at least tell me which file includes this information so I can edit it myself to remove them?

**Comment by Iwan1803** [comment]
Controls window? 
Try unbinding the keys in the LS settings itself.

**Comment by DreadPirateLynx** [comment]
> 
> 
> Controls window?
> Try unbinding the keys in the LS settings itself.

I don't want to unbind the keys though; I just don't want to see them the whole time I'm driving.

**Comment by Iwan1803** [comment]
Ah, the help menu 😉
There is allready an option for that in the AD settings:
![image](https://user-images.githubusercontent.com/47528836/87124894-d6e71d00-c289-11ea-8792-20702af1cdb0.png)

**Comment by DreadPirateLynx** [comment]
> Ah, the help menu wink
> There is allready an option for that in the AD settings:

Hmm... I tried that and it didn't seem to do anything. I'll give it another shot. Thanks

**Comment by Iwan1803** [comment]
No problem 😉
