### ISSUE TITLE
[BUG] No AIVE-Button

### ISSUE THREAD

**Issue by Rikkavidu** [Stephan-S/FS19_AutoDrive#1507]
Version 1.0.0.5 RC4

Ich habe beides installiert und in den Spielständen gewählt. Ich benuze das breite HUD mit mehr Einstellungen. Der AIVE-Knopf passt nicht mehr in die untere Reihe, aber wenn ich den Editor starte, dann ist oben ganz rechts noch ePlatz für einen Knopf frei.
Beste Grüsse.

**Comment by Iwan1803** [comment]
Rechtsklick auf den CP-Button wechselt zum AIVE-Button.

**Comment by Rikkavidu** [comment]
Da ich kein CP installiert habe, habe ich auch keinen CP knopf. Ich habe weder einen CP, noch einen AIVE Knopf.
In einem deiner Videos hieß es mal, dass wenn eines von beiden installiert wäre, der Knopf dann auch da wäre.
Abermals beste und freundlichste Grüße.

**Comment by Rikkavidu** [comment]
Ich habe aber auch mal hart auf 200% eskaliert, das habe ich doch geschrieben, oder? Ich gehe davon aus dass dieser Knopf links ausgeblendet wird, weil er nicht mehr hin passt. Deswegen habe ich ja vorgeschlagen, den Knopf nach oben rechts zu versetzen. Ich brauche diese hohe Skalierung, weil ich stark sehbehindert bin. Auch noch mal einen Vorteil von Autodrive gegenüber Cosplay. Nochmals beste Grüße.

**Comment by Iwan1803** [comment]
siehe: https://github.com/Stephan-S/FS19_AutoDrive/issues/1479
Installiere die heute erschiene RC5 und das Problem ist verschwunden 😉

**Comment by Rikkavidu** [comment]
Ah, ich habe GERADE EBEN ein Video auf YouTube gemacht, um Euch das zu beweisen. Ok, versuche ich mal, danke. Beste Grüsse, ich melde mich.

**Comment by TobiHH78** [comment]
Was bitte ist ein AIVE-Button? Habe ich etwas wichtiges verpasst?

**Comment by Rikkavidu** [comment]
AI Vehicle Extension, der "intelligente Helfer" ist das.
Problem tatsächlich gefixed, danke. Aber TROTZ DEM:
https://youtu.be/Q1XKkCXe0CY
Bitte ansehen. Nächstes mal bitte NICHT gleich auf NOBUG schalten, es WAR nähmlich ein BUG. Vielen Dank, Thema kann zu.
PS: Video ist leider sehr leise, weil auf schwachem nicht eingestelltem PC, sorry dafür.
Beste und freundlichste Grüsse.

**Comment by TobiHH78** [comment]
Ah ok. danke für die Erklärung. Den nutze ich nicht, daher habe ich da auch nix vermisst...:)

**Comment by Iwan1803** [comment]
Bei mir taucht der Button oben rechts über dem Zahnrad-Button auf:
![image](https://user-images.githubusercontent.com/47528836/87153367-a61ddc80-c2b7-11ea-94df-534a3b895ce0.png)
Breites HUD, getestet von min. bis max. %

**Comment by Rikkavidu** [comment]
Hallo, ja bei mir jetzt auch mit der RC5. Vergiss bitte nicht, dass die Meldung schon gestern mit der Version RC4 geschrieben wurde. Jetzt ist es gefickt, gestern war es noch ein Bug. Beste Grüße.

**Comment by Iwan1803** [comment]
"Jetzt ist es gefickt"? 😂
Dann mach ich hier mal zu....
