### ISSUE TITLE
Auto Drive Course Editor[Question]

### ISSUE THREAD

**Issue by John-Deere89** [Stephan-S/FS19_AutoDrive#1509]
Welche Java Version brauch ich damit er läuft?

**Comment by Iwan1803** [comment]
Für den AutoDrive Course Editor wird mindestens das JDK 11 benötigt. Die Version 8 der Runtime ist nicht ausreichend.
https://www.oracle.com/java/technologies/javase-downloads.html

**Comment by John-Deere89** [comment]
Danke :)

**Comment by Iwan1803** [comment]
Bitte :)

**Comment by John-Deere89** [comment]
frag das hier drunter mal  wie geht denn der Editor? ich habe die AD xml ausgewählt und die map aber beides sehe ich net im fenster :(

**Comment by raupach** [comment]
Mach mal ein Screenshot.
