### ISSUE TITLE
translations to a separate file

### ISSUE THREAD

**Issue by Gonimy-Vetrom** [Stephan-S/FS19_AutoDrive#151]
Hey. I moved all translations to a separate file, because it is so convenient to work with a large amount of text. And added a translation into Russian. If you like this option of organizing files, you can add it. If not, then do not add.
[FS19_AutoDrive.zip](https://github.com/Stephan-S/FS19_AutoDrive/files/3221062/FS19_AutoDrive.zip)

**Comment by Gonimy-Vetrom** [comment]
Added updated translation to[ French](https://github.com/Stephan-S/FS19_AutoDrive/pull/154). 
[FS19_AutoDrive.zip](https://github.com/Stephan-S/FS19_AutoDrive/files/3224486/FS19_AutoDrive.zip)

**Comment by Anonymous-any** [comment]
thx mf

**Comment by Gonimy-Vetrom** [comment]
I did not understand what you wrote. 
But I made your changes to the file so that they are not lost if my proposal is approved.

**Comment by Stephan-S** [comment]
Thank you very much for your effort!
I will happily merge this :-)
I never got around to splitting them up again. Thank you very much!
