### ISSUE TITLE
[Question] rückwärtsfahrt, zwei punkte verbinden?

### ISSUE THREAD

**Issue by andreasthu** [Stephan-S/FS19_AutoDrive#1514]
**Question:**   
I've got a question...
Hallo Leute?
Man kann ja ingame im wegpunkte Editor zwei Punkte miteinander verbinden, einseitig oder beidseitig befahrbar.
Kann man das auch für rückwärts-fahrstrecken?
Lg
Andreas

**Comment by Iwan1803** [comment]
Ja, indem man einfach die Shift-Taste gedrückt hält.

**Comment by andreasthu** [comment]
Danke

**Comment by Iwan1803** [comment]
Bitte :)
