### ISSUE TITLE
[Feature Request] nach Abscluß der Tour auf Stop-/Parkposition fahren

### ISSUE THREAD

**Issue by Obelixm** [Stephan-S/FS19_AutoDrive#1515]
Hallo zusammen:

(Mein) Problem:
nach getaner Arbeit (z.. B. 3x Silo anfahren und befüllen) endet die Tour kurz nach dem Beladepunkt. Er blockiert dabei andere Fahrer die beladen wollen.

Lösungsidee:

Nach Beendigung der Tour fährt der Fahrer auf eine definierte Position (oder Parkposition) und stört so andere Fahrer nicht beim Be oder Entladen.

Ich hoffe ich konnte mich einigermassen deutlich ausdrücken.

Danke
Obelixm

**Comment by Axel32019** [comment]
@Obelixm Hallo,
See here / Wenn Interesse hier entlang: #1663

**Comment by Iwan1803** [comment]
Da in 1.1.0.6 integriert, mach ich hier mal zu // Since integrated in 1.1.0.6, i'll close here 😎
