### ISSUE TITLE
[BUG] Some vehicles cannot be assigned a parking position, only attached devices - manchem Fahrzeug kann keine Parkposition zugewiesen werden, nur angehängten Geräten

### ISSUE THREAD

**Issue by haamic** [Stephan-S/FS19_AutoDrive#1516]
AutoDrive Version: 1.1.0.5.-RC5
Release or selbsterstelltes zip: Release C
Karte (falls relevant): Alle
Fahrzeug(art) (falls relevant): Traktoren und LKW z.b. Kategorie Kompakttraktoren Original Fiat 1300 DT

**Beschreibe den Bug**
Fahrzeug kann keine Parkposition zugewiesen werden, nur angehängten Geräten
Schön das meine Anfrage von früher, ob man für angehängte Geräte eine Parkfunktion einbauen kann, nun funktioniert.
Leider musste ich feststellen, das manchem Hauptfahrzeug keine Parkposition zugewiesen werden kann. Das Fahrzeug Symbol ist grau, nicht weiss (wie bei aktiviertem angehängtem Gerät).  
![symbol](https://user-images.githubusercontent.com/28841989/87225837-1566ff80-c390-11ea-963d-455faa7d14e5.jpg)

Original Giants Fahrzeuge und auch Mod-Fahrzeuge betroffen. 
Das war vorher wohl nicht so aufgefallen, als es keine Parkposition für Geräte gab, da ich das Komplette Gespann zum Parken schickte.
Scheint fast alle Traktoren + LKW zu betreffen, soweit ich testen konnte.
Ein mod fand ich, der wird mit weissen Symbol angezeigt und da geht das zuweisen auch. (Güldner G75)
getestet habe ich mit nur der Karte und AD im Modordner, es kann also kein anderer Mod dazwischen funken.
Bitte mal checken, Danke

**Falls anwendbar - Schritte mit denen ich den Bug nachstellen kann**
Traktor oder LKW wählen und versuchen, Parkposition festzulegen

**Screenshots**
Falls relevant, bitte Screenshots beifügen

**Comment by haamic** [comment]
Ich vergass, zu erwähnen, das es sich bei der Karte um "Kandelin" handelt.
Habe nun mal Felsbrunn getestet und da scheint es zu funktionieren.
Schade, dann liegts an der Map, warum auch immer.

**Comment by unlimited78** [comment]
hab auf der NFM 4fach SP dasselbe Problem... mit RC4 hat noch alles wunderbar funktioniert...
Fahrzeuge welchen ich vorher problemlos Parkpositionen zugeordnet habe lassen sich jetzt leider nicht mehr zuordnen :-(
wie komm ich eigentlich wieder zurück auf RC4?

**Comment by Iwan1803** [comment]
Ich kann im SP auf der NFM 4x diversen Vanilla- als auch Mod-Fahrzeugen, -anbaugeräten und -anhängern Parkplätze zuweisen. Es scheint also kein generelles Problem zu sein. Ggfs. funkt auch irgendein Mod dazwischen.

Oder geht es eher um das Problem, das man per Taste G nicht zwischen Anbaugeräten, Anhängern & Co. und Fahrzeug wechseln kann?
siehe: https://github.com/Stephan-S/FS19_AutoDrive/issues/1510

AutoDrive 1.1.0.5-RC kann übrigens hier geladen werden:
https://github.com/Stephan-S/FS19_AutoDrive/tree/967eb7e6f0ae102dac3747284b2d706ebce3ae3b

**Comment by Clouseau219** [comment]
Ich konnte zwar ein Parkplatz zuweisen, aber er konnte danach nicht mehr geändert werden bzw einer neuen Position zugwiesen werden

**Comment by unlimited78** [comment]
wie gesagt... mit RC4 hat das alles noch einwandfrei funktioniert
hab inzwischen keinen neuen Mod geladen und auch nichts verändert, nur die RC5 geladen und upgedatet

**Comment by haamic** [comment]
Also wie schon geschrieben ist der einzige zusätzlich je Mod die Mod-Karte Kandelin bei mir. Auf standard Felsbrunn funktionieren die Fahrzeuge die auf kandelin nicht funktionieren. Und ja man kann nicht mit G Umschalten , ohne Anbaugerät bleibt das Fahrzeugsymbol grau. Auf felsbrunn aber weiß und lässt sich zuweisen.

**Comment by haamic** [comment]
nochmalige testreihe, verschiedene maps, Standard und mod.
-neuer Spielstand begonnen mit RC4 , Parkplatzziel erstellt, zuweisen Hauptfahrzeug möglich. Spielstand gespeichert
  - RC4 durch RC5 ersetzt, gleicher Spielstand geladen, Parkplatz nicht mehr zugewiesen und kann auch nicht 
    zugewiesen werden (Traktoren/LKW), bei angehängten Geräten funktioniert es, weil da das Gerätesymbol weiss ist
   -Wechsel zurück auf RC4, Spielstand geladen, Parkplatzziel auf Fahrzeug noch vorhanden, kann 
     auch geändert werden

Bitte versucht das mal nachzustellen. Ich habe keine anderen Mods im Verzeichnis, bis auf AD und einer Mod Karte,aber selbst mit Standardmaps ist dies Verhalten bei mir zu beobachten.

Aufgefallen ist mir, das z.b. auf Felsbrunn, das Fahrzeugsymbol bei mir immer Grau ist und es mit RC4 funktioniert,
auf zb. Kandelin ist das Symbohl mit RC4 weiss und mit RC 5 Grau, 

![Symbolkandelinrc4-rc5](https://user-images.githubusercontent.com/28841989/87239411-22770380-c40f-11ea-9c39-a7815e6078f9.jpg)

scheint aber keine Auswirkung zu haben, da überall mit RC5 der Parkplatz vom Hauptfahrzeug bei mir nicht nicht mehr funktioniert.

**Comment by haamic** [comment]
> Oder geht es eher um das Problem, das man per Taste G nicht zwischen Anbaugeräten, Anhängern & Co. und Fahrzeug wechseln kann?
> siehe: #1510
> 

das ist erstmal unrelevant, da ohne angehängtes Gerät ein wechseln mit G nicht erforderlich ist.
mit RC5 kann bei mir kein Parkplatz dem Fahrzeug zugewiesen werden , was mit RC4 aber noch funktionierte

**Comment by Iwan1803** [comment]
Problem ist erkannt und wir arbeiten an einer Lösung
*problem is known and we are working on a solution*
-> https://github.com/Stephan-S/FS19_AutoDrive/issues/1510

**Comment by Axel32019** [comment]
In 1.1.0.5-RC6 enthalten
