### ISSUE TITLE
ItRunner unloading combine issue

### ISSUE THREAD

**Issue by zcaalock** [Stephan-S/FS19_AutoDrive#1517]
Truck with itrunner trailer does`t stop under combine pipe, it goes far forward to the field stop and again wait for call (on picture i stopped the truck manually). 
I have tried same case with regular trailer and it works fine.
![01](https://user-images.githubusercontent.com/24411061/87230713-0002cd00-c3b2-11ea-816c-e236b18da4b5.png)

**Comment by Iwan1803** [comment]
Did you check the settings with a working unloader?

**Comment by zcaalock** [comment]
settings on itrunner and regular trailer are same, i also did check on other map and this bug repeat itself. Is there any log file for AD? I think AD don`t recognise itrunner as trailer and it just keep going forward.

**Comment by GitTomahawk** [comment]
I noticed the same issue

**Comment by Axel32019** [comment]
Hello @zcaalock , @GitTomahawk ,
Is the issue still observed in the latest Release-Version 1.1.0.7?

**Comment by GitTomahawk** [comment]
Yes, its still an issue

**Comment by Axel32019** [comment]
@GitTomahawk I tested the IT Runner truck and trailer without problem. Could you please provide a link to the ones you use?

**Comment by Axel32019** [comment]
No further info / update -> closed
