### ISSUE TITLE
Wegpunkte für Vorwärts- und Rückwärtskurse unterscheiden/Different waypoints for foward and backward courses

### ISSUE THREAD

**Issue by TripleX1978** [Stephan-S/FS19_AutoDrive#1518]
Wäre hilfreich wenn man die Wegpunkte für Vorwärts- und Rückwärtskurse besser unterscheiden könnte, durch Farbe, Form oder sogar beides.
Habe oft das Problem, dass bei der Kombination von Vorwärts- und Rückwärtskursen die Punkte nah beieinander liegen und man häufig den falschen zum Bearbeiten erwischt.

**Comment by Iwan1803** [comment]
Man sollte grundsätzlich keine Linien übereinander oder viel zu dicht nebeneinander erstellen.
Dann ergeben sich solche Probleme auch so gut wie nicht und vor allem "verführt" es AD dann nicht dazu, einen vermeintlich falschen Weg zu benutzen.
Das mit den Farben werden wir mal prüfen.

**Comment by Axel32019** [comment]
@TripleX1978 Hallo,
Vielleicht hilft das schon mal: See here / Wenn Interesse hier entlang: #1663

**Comment by Iwan1803** [comment]
Da in 1.1.0.6 integriert, mach ich hier mal zu // Since integrated in 1.1.0.6, i'll close here 😎
