### ISSUE TITLE
Abladen mehrere Ziele / Unload multiple targets

### ISSUE THREAD

**Issue by TripleX1978** [Stephan-S/FS19_AutoDrive#1519]
**AutoDrive Version:** 1.1.0.5-RC5   
 
Habe, wie vorgeschlagen, den Wert für "Abladen ab Level" auf 85% gesetzt (siehe #1496).
Immer noch das gleiche Problem.

AD wählt, nachdem es an Ziel 1 komplett abgeladen hat, Ziel 2 zum abladen aus und nicht das Ziel zum Beladen.
Das selbe passiert wenn an Ziel 2 komplett abgeladen wurde.
AD wählt wieder Ziel 1 aus und nicht das Ziel zum Beladen.

Nachdem dann das jeweilige Ziel leer angefahren wurde, wird das Ziel zum Beladen angefahren.

**Comment by Iwan1803** [comment]
Screenshots von vor und nach dem 1. Abladen und vor allem der Einstellungen wären vielleicht hilfreich.

**Comment by TripleX1978** [comment]
Ich weiß nicht was jetzt anders ist als vor ein paar Tagen, aber jetzt gerade läuft wieder alles.
Werde es die Tage mal weiter beobachten.

**Comment by TripleX1978** [comment]
Also die letzten Tage scheint es ohne Probleme zu laufen.
Denke wir können das vorerst mal abhaken
