### ISSUE TITLE
Abladen in BGA Silo

### ISSUE THREAD

**Issue by mnicklisch** [Stephan-S/FS19_AutoDrive#152]
Ich weiß nicht ob es ein Bug oder fehlendes Feature in AD ist, aber ich habe eben mal ein wenig damit herum experimentiert mit AD meine BGA zu betreiben.
Leider habe ich es nicht hinbekommen das Gehäckselte in das Silo zu entladen. Ich habe ihn auf Entladen gestellt und er fährt einfach nur zum Abladepunkt und sagt er ist angekommen und macht dann nichts mehr, egal ob der Entladepunkt am Anfang oder am Ende des Silos liegt.
Es wäre super wenn AD das auch könnte, idealerweise so dass er seine Ladung gleichmäßig über die ganze Länge des Silo verteilt.
Eventuell verbunden mit #129

**Comment by Trigger87** [comment]
Yes, that would be great. Is it possible that autodrive knows the lenght of the bga-silo and drives through it while unloading the trailer???

I'm currently using autodrive to drive the tractor to the BGA. After that i switch to courseplay where i have done a small course for unloading the trailer into the BGA. At the exit i switch back to autodrive to go back to the field. Maybe a bit complicated but it works great :)

**Comment by Stephan-S** [comment]
Hey,

I'm still struggling with myself whether this should be handled by Courseplay and we should work on integrating AD roadnetwork into CP courses or if this should be a standalone feature of AutoDrive.

So, I'm not ignoring you, I am just not sure yet, whether it's quite worth it to invest the effort :-)

Best regards,
Stephan

**Comment by Trigger87** [comment]
Hi Stephan,  Courseplay is a bit more advanced and it would be awesome to **implement your Autodrive roadnetwork into courseplay. That would make the best out of both mods.** Courseplay AND Autodrive.

But i can totally understand you. Autodrive Roadnetwork is a unique feature and is very easy to understand. I was using Courseplay for a very long time before i found your AD-Roadnetwork. :D Currently i switch constantly between CP and AD and let the mods do what they can do best.

**Comment by fudoido** [comment]
it would be great if courseplay guys ditched their waipoint course marking and opt for how stephan does with autodrive. much simplier to record courses, speed control in curves that courseplay doesnt have, ability to conect the routes and it will assume the conections straight away with a refresh........
just wish giants would do something to prevent traffic stopping in the roads when it detects a "helper" (either game, courseplay or autodrive halper) from the back and still stops.
Considering both mods are greatly used for singleplayer games, alot of people like to keep traffic on for a bit more realism. Meh, giants could do like in the mobile version of the game, we honk the tractor/truck and traffic just pulls over off the road :P
