### ISSUE TITLE
Frontlader Modus

### ISSUE THREAD

**Issue by Heubube** [Stephan-S/FS19_AutoDrive#1521]
Hallo zusammen,
ich liebe Autodrive, das ist der nützlichste Mod überhaupt! Aber ich vermisse den Frontlader Modus, den es in einer älteren Version gab. Bei mir hat der super funktioniert! Warum ist der weg? Kommt der wieder? 
Grüsse
Heubube

**Comment by Iwan1803** [comment]
Der ist weg, da er nicht so zuverlässig funktioniert hat, wie er eigentlich sollte.
Ob und wann er noch mal wieder kommt, steht nicht fest.

**Comment by Heubube** [comment]
Schade, aber danke für sie schnelle Antwort...!
