### ISSUE TITLE
[BUG] some traktors start AD itself.

### ISSUE THREAD

**Issue by andreasthu** [Stephan-S/FS19_AutoDrive#1523]
AutoDrive Version: 1.1.0.5.rc5
Release or selbsterstelltes zip: selbsterstelltes zip
Karte (falls relevant): Alle, Minibrunn
Fahrzeug(art) (falls relevant): Traktore

**Beschreibe den Bug**
Eine klare Beschreibung des Bugs.
Wenn ich mit Traktor A einen kurs fahre und dieser fertig ist, d.h. steht und den Motor abgestellt hat, und ich mit Traktor B einen kurs starte, fährt Traktor A selbstständig los, und fährt eine kursschleife zu seinem eingestellten WP
**Falls anwendbar - Schritte mit denen ich den Bug nachstellen kann**
Siehe oben
**Screenshots**
Falls relevant, bitte Screenshots beifügen
Lg
Andreas

**Comment by Iwan1803** [comment]
Sicher, das Traktor A fertig und AD auch beendet ist?
Und was bitte ist ein WP?

**Comment by andreasthu** [comment]
Ach ja sorry, etwas spät. 
Ja, der Traktor ist fertig,  motor abgestellt, AD nicht aktiv, der Traktor steht z.b. auf dem WP ( =Wegpunkt, Zielpunkt) mit Name "Hof.Scheune".
Wenn ich nun in einen anderen traktor einsteige, diesen mit AD wegfahren lasse, beginnt sich der erstgenannte Traktor zu bewegen, fährt eine Runde wieder zu seinem WP "Hof.Scheune" und bleibt wieder stehen.
Kann ich nicht reproduzieren, habs auch eher zufällig entdeckt,  ist jedes mal ein anderer Traktor.
Ist mir auch schon mal passiert das ich einen Traktor per AD zu Feld.15 geschickt habe, dort mit dem giants Helfer zu grubbern begonnen habe, AD war nicht aktiv, 
Als ich dann bei einem anderen Traktor AD aktivierte,  ist in dem vorher erwähnten Traktor (grubbern mit giants Helfer) ebenfalls AD aktiv geworden und der Traktor mit gesenktem Grubber per AD quer übers Feld und dann zum wegpunkt Feld.15 gefahren.
Lg
Andreas

**Comment by Axel32019** [comment]
Das kann unter einer ungünstigen Kombination vom gespeicherten Spielstand mit aktiven AD Fahrzeugen passieren - wird mit nächstem Release gefixed.

**Comment by andreasthu** [comment]
D.h. vorerst alle AD drive Fahrer entlassen, 
Dann speichern und beenden?
Lg
Andreas

**Comment by Axel32019** [comment]
Nein, es passiert nur sehr selten - einfach mal weiter beobachten...

**Comment by Axel32019** [comment]
@andreasthu Sollte nicht mehr auftreten mit 1.1.0.5-RC6
