### ISSUE TITLE
How to set a parking position for the implement / Wie Parkposition für Gerät einrichten und auswählen?

### ISSUE THREAD

**Issue by TobiHH78** [Stephan-S/FS19_AutoDrive#1524]
Hallo,

eine Frage, wie funktioniert das mit der Parkposition für Geräte? Wie kann man das einrichten, und wie wählt man anschließend aus, ob man das Fahrzeug oder das angehängte Gerät parken möchte?

How does it work with the parking position for an implement? How can I set the parking posution for it, and how do I afterwards choose, if I park the vehicle or the implement?

**Comment by Iwan1803** [comment]
Wenn du in einem Traktor mit z.Bsp. einem Anhänger sitzt, dann hast du oben links ja eine entsprechende Anzeige dafür:
![image](https://user-images.githubusercontent.com/47528836/87390579-6bfb5600-c5a9-11ea-8a0e-29e838ca68cf.png)
- der Trecker ist hellgrau, da er nicht selektiert ist
- der Anhänger ist weiß, da er ausgewählt ist
Wähle in AD nun ein Ziel aus, rechtsklicke das P und schon ist dem Anhänger dieses Ziel als Parkplatz zugewiesen.

Aktuell gibt es aber noch 2 Probleme (https://github.com/Stephan-S/FS19_AutoDrive/issues/1510):
- auf Dedi-Servern klappt es für Anhänger/Anbaugeräte noch nicht
- im SP kann einem "nackten" Traktor kein P zugewiesen, wenn dieser nicht selektiert ist (danke, Giants, für diesen Unsinn)
Wir arbeiten gerade an einer Lösung.

Ein weiteres Problem, welches wir aber vermutlich nicht lösen können:
mit der Taste "G" kann man (normalerweise) zwischen Fahrzeug und Anhängern/Anbaugeräten wechseln, was aber bei bestimmten Fahrzeugen nicht möglich ist.

**Comment by TobiHH78** [comment]
Vielen Dank für die Erklärung.

**Comment by Iwan1803** [comment]
Gerne.
