### ISSUE TITLE
[BUG] Modus "Abholen" crasht dediServer / Modus "collect" crashes dediServer

### ISSUE THREAD

**Issue by txmazing** [Stephan-S/FS19_AutoDrive#1527]
AutoDrive Version: 1.1.0.5-RC5
Release or selbsterstelltes zip: Release
Karte (falls relevant): Alle
Fahrzeug(art) (falls relevant):

**Beschreibe den Bug**
Auf dem dediServer mit CP und AD crasht der Server (in so fern, dass sobald in den jeweiligen Traktor eingestiegen wird alles stehen bleibt und sobald ausgestiegen wird alles "vorgespult wird") wenn der CP-Fahrer an AD übergeben hat, dieser die Sämaschine aufgefüllt hat und wieder an dem Feldpunkt angekommen ist.

**Falls anwendbar - Schritte mit denen ich den Bug nachstellen kann**
siehe oben

**Screenshots**
Falls relevant, bitte Screenshots beifügen

**Comment by Iwan1803** [comment]
Wann genau "crasht" der Server? Wenn CP an AD übergibt oder AD zurück an CP?
Btw. ist CP nicht gerade bekannt dafür, das es auf Dedis "super" läuft.

**Comment by txmazing** [comment]
AD zurück an CP

**Comment by Axel32019** [comment]
@txmazing Welche CP Version?

**Comment by txmazing** [comment]
> @txmazing Welche CP Version?

1.1.0.5-RC5

**Comment by Axel32019** [comment]
Gibt es Fehlermeldungen in den log's?

**Comment by txmazing** [comment]
Nein, nichts.

**Comment by Axel32019** [comment]
Passiert das direkt beim ersten Mal oder nach einigen Durchläufen?
Hast Du den Server mal neu gestartet und dann probiert ob es direkt auftritt?

**Comment by txmazing** [comment]
> Passiert das direkt beim ersten Mal oder nach einigen Durchläufen?
Das kann ich dir garnicht sagen. Ich meine, es war jedes Mal.
> Hast Du den Server mal neu gestartet und dann probiert ob es direkt auftritt?
Ja es war direkt wieder das selbe.

**Comment by Axel32019** [comment]
@txmazing Bitte mal 1.1.0.5-RC6 weiter beobachten und wenn es wieder auftritt hier wieder aufmachen.
