### ISSUE TITLE
Ordner umbenennen / Rename folders

### ISSUE THREAD

**Issue by TripleX1978** [Stephan-S/FS19_AutoDrive#1528]
Ist es möglich die Ordner umzubenennen und wenn ja wie?

**Comment by Iwan1803** [comment]
Ja und nein 😉
1. Möglichkeit = ingame
- Editor aktivieren und Ordner mit korrektem Namen anlegen
- alle Zielpunkte in den neuen Ordner verschieben
- falsch benamten Ordner löschen

2. Möglichkeit = "extern"
Im Savegame-Ordner die Datei AutoDrive__Mapname__config.xml mit einem Editor öffnen und per Suchen&Ersetzen den falschen mit dem richtigen Ordnernamen ersetzen.

**Comment by Axel32019** [comment]
No update -> Closed.
