### ISSUE TITLE
pathing issue

### ISSUE THREAD

**Issue by docgaming** [Stephan-S/FS19_AutoDrive#153]
hi thanks for this mod i do love it but i have some problems with the paths the drivers take IE going a very long way around i will use the course editor to show you the path it takes.
![Screenshot_5](https://user-images.githubusercontent.com/48932718/58421493-f8864480-8087-11e9-8597-9df6fc5f145d.png)

this is a T junction outside My main fram, in yellow is the path the AD driver takes and in blue is the fastest and shortest route to get to any destination with in my fram.
![Screenshot_7](https://user-images.githubusercontent.com/48932718/58422106-a5ad8c80-8089-11e9-88d8-67f951002850.png)
as you can see the path the ad driver takes is very long it looks like something to do with the 2way waypoints cuz when i had that bottom road with 1way waypoints going both ways it was ok.
this is a oakfield map if you need more info i will get it for you 
[AutoDrive_Oakfield_Farm_19_config.zip](https://github.com/Stephan-S/FS19_AutoDrive/files/3223906/AutoDrive_Oakfield_Farm_19_config.zip)

**Comment by Stephan-S** [comment]
![Settings](https://user-images.githubusercontent.com/5493976/58433250-8547f700-80b6-11e9-9e8b-ecff036dc706.png)
Hey,
your setting were causing the pathing issue.
Don't select the 'avoid target' option in your case. This will make the pathfinding algorithm avoid every destination which is not the one you are currently trying to reach and accept a detour of, in your case 10km !!.
Also the 'use fastest route' option might not always lead to the desired results as it tries to avoid sharp turns and in your case sometimes leads to bad paths.

Just use the settings as I set them in the screenshot.
Also the lookahead distances were way too extreme and caused undesired driving behaviour (yellow marker).

Best regards,
Stephan

**Comment by docgaming** [comment]
thanks for that i will change them and see.
for the detour i don't know why that was at 10km I must have hit the arrow my mistake.
avoid other targets i did not know that avoided  destinations.
for the look ahead was set like that cuz i use the weight mods and i was trying on getting the vehicles to slow down in time.

**Comment by Stephan-S** [comment]
the lookahead turn might cause him to 'cut corners' if it is set too high.
The Lookahead braking can be useful to set a little higher when using the weight mod, yeah.
I will also increase the braking speed again in the next release, so you won't have to set it too high

**Comment by docgaming** [comment]
ok it will be good if you can thanks
