### ISSUE TITLE
Entferung Abfahrer-Drescher[Question]

### ISSUE THREAD

**Issue by Dschowy** [Stephan-S/FS19_AutoDrive#1530]
Hallo! Gibt es einen maximalen Abstand, den der Anfahrer zum Drescher haben darf? Ich benutze AD um Drescher abzutanken und habe auf einem sehr grossen Feld das Problem, dass der Abfahrer nicht zum Drescher fährt bzw. nicht gerufen wird.
Eine Einstellung dazu finde ich auch nicht. Der Drescher fährt seinen Kurs mit CP - Feldarbeit.

**Comment by Dschowy** [comment]
Hab die Einstellung gefunden

**Comment by xFranky78x** [comment]
Hey kannst du mir sagen wo diese Einstellung ist?? Habe das gleiche Problem!
