### ISSUE TITLE
[BUG] Cannot Switch AIVE button back to CP

### ISSUE THREAD

**Issue by NurPech** [Stephan-S/FS19_AutoDrive#1531]
AutoDrive Version: 1.1.0.5-RC5
Release or selbsterstelltes zip: Release
Karte (falls relevant): Alle
Fahrzeug(art) (falls relevant):

**Beschreibe den Bug**
Ich habe bei einem Traktor aus dem Claas-DLC aus Versehen den CP-Button mit einem Rechtsklick zu einem AIVE-Button gemacht. Da ich aber kein AIVE nutze, will ich wieder den CP-Button herstellen. Dies funktioniert aber nicht.

**Falls anwendbar - Schritte mit denen ich den Bug nachstellen kann**
AIVE-Button aktivieren und versuchen CP-Button wieder zu bekommen.

**Screenshots**
https://t.kst.re/0da970ff837a

**Comment by Iwan1803** [comment]
Ist das nur bei diesem einem Traktor? Normalerweise wechselt man per Rechtsklick hin- und her.

**Comment by NurPech** [comment]
Hallo,

Bei allen anderen Geräten kann ich per Rechtsklick auch nicht von CP auf AIVE wechseln. Es tut sich einfach gar nix. Getestet bei Traktoren, Autos, LKWs, Mähdreschern, eben alles was fahren kann.

**Comment by Axel32019** [comment]
@NurPech In der ersten Meldung ist CP vorhanden AIVE jedoch nicht, richtig?
Im letzten Kommentar möchtest Du von CP auf AIVE wechseln, also ist AIVE vorhanden / aktiv?

**Comment by NurPech** [comment]
Hallo,

Nein, ich nutze nur CP. Ich hatte AIVE noch nie im Einsatz.

Ich habe den entsprechenden Traktor nun verkauft und einen neuen gekauft.

**Comment by MiraculixBCA** [comment]
Hallo

Ich habe das Problem auch hin und wieder.
Kein AIVE vorhanden sondern nur CP. Kann daher mit der rechten Maustaste, seit RC5?, auch nicht mehr auf AIVE wechseln.
Das Problem tritt mit Mod- und Standard-Traktoren bei mir auf.  Allerdings steht wieder alles auf CP wenn ich das Savegame neu lade.

Bei mir springt der Button auf AIVE um wenn:
1. AD steht auf Modus "Abholen"
2. CP nutzt AD zu entladen/befüllen
3. CP aktiviert AD (weil Gerät leer)
4. AD verlässt das Feld (Ziel im HUD ist grün)
5. AD fährt zur Beladestation (Beladestation ist grün im HUD)
6. wenn ich jetzt im laufenden Betrieb das Ziel ändere springt der CP Button auf AIVE und der Traktor fährt gerade aus.

**Comment by Iwan1803** [comment]
> Kein AIVE vorhanden sondern nur CP. Kann daher mit der rechten Maustaste, seit RC5?, auch nicht mehr auf AIVE wechseln.

Warum sollte man auf AIVE wechseln können, wenn gar kein AIVE vorhanden ist? 🤨

**Comment by MiraculixBCA** [comment]
Soll man ja gar nicht können. Wozu auch.
Es geht doch darum dass man auch nicht auf CP zurück wechseln kann wenn der Button auf AIVE wechselt.
Ich wollte damit eigentlich nur sagen dass ich nicht selbst auf AIVE wechseln kann. Der Button beim gleichen Traktor aber schon wechseln kann.

**Comment by Iwan1803** [comment]
Ok, dann hast du dich einfach etwas missverständlich ausgedrückt 😉

**Comment by NurPech** [comment]
Das war bei mir auch so (oder so ähnlich). Einer meiner Traktoren war plötzlich auf AIVE, ohne jemals bewusst AIVE aktiviert zu haben. Wie ich das geschafft habe, weiß ich nicht. Wichtig ist jedenfalls das ich diesen Traktor nicht wieder auf CP setzen konnte. Jedes andere selbstfahrende Gerät stellt den CP Button zur Verfügung.
