### ISSUE TITLE
[Question] Load - Unload not working properly

### ISSUE THREAD

**Issue by GibsonGaming** [Stephan-S/FS19_AutoDrive#1532]
**Question:**   
I've got a question...
I have set one full route on my map from Silo to Central Grain Elevator sell point.
I started at My farm silo, then drove to the Grain Elevator and back to my farm Silo while recording.
I set it to Load/Unload and set the points to Farm Silo / Grain Elevator / Wheat.
This is what it does when I press Go.
The tractor drives to Silo and loads the trailer with Wheat.
The tractor then Unloads the wheat in the same Silo.
The tractor then drives to the Grain Elevator.
The tractor then drives to the Silo and loads Wheat.
The tractor then Unloads the wheat in the same Silo.

I can't figure out why it's doing this. It just loads then immediately unloads at the silo. I've made the route multiple times and it does the same thing. Could this possibly be another mod or the seasons mod causing this?

**Comment by Iwan1803** [comment]
Sounds like the loading and unloading trigger of the silo (a mod?) are at the same position.
So maybe a screenshot of the silo and the route there could be helpful.

**Comment by fischi3016** [comment]
Also ich kann es mit keinem Original Fahrzeug abladen. Hab den Hawe ausm Modhub alle Fruchtypen reingeballert der funzt

**Comment by Axel32019** [comment]
No update -> Closed.
