### ISSUE TITLE
Welchen Wert bei Abstand zum Rohr für Abfahrer?

### ISSUE THREAD

**Issue by TripleX1978** [Stephan-S/FS19_AutoDrive#1533]
Könnte mir jemand bitte nochmal erklären in welche Richtung ein positiver bzw. ein negativer Wert den Abfahrer verschiebt und welchen Wert man am besten nimmt?

Ich habe gerade 5 identische Drescher laufen, die von 5 identischen Abfahrer-Kombis entladen werden. Ich muss aber bei fast jedem Paar eine komplett anderen Wert einstellen damit der Anhänger richtig unter dem Rohr steht, angefangen von -1,25 über 0 bis 1,25.

**Comment by 60erjonny** [comment]
Hallo
Ich habe da einen positiven Wert von 0,75m eingestellt...

**Comment by Iwan1803** [comment]
Der Abstand zum Rohr muss immer pro jeden Abfahrer eingestellt werden.
Meine (bestehend aus unterschiedlichen Kombis) habe ich alle auf 0,50m eingestellt, um meine Drescher (alle 100% identisch) abzutanken und keinerlei Probleme.
Sollte es also bei der Erkennung des Rohrendes zu keinen Problemen kommen, sollte auch ein einheitlicher Wert bei dir möglich sein (niemals negativ).

**Comment by TripleX1978** [comment]
Hatte den Wert beim ersten Feld auch auf 0,75m eingestellt.
Beim nächsten Feld musste ich dann schon 1,25m einstellen, obwohl die Drescher und Abfahrer gleich konfiguriert waren.

**Comment by BomBastiK-de** [comment]
Zu Problemem kann es kommen, wenn es unterschiedliche Höhen im Feld gibt, da muss der Abstand oft verändert werden.

**Comment by Iwan1803** [comment]
Wie sollte der seitliche Abstand zwischen Anhänger(-längsachse) und Rohr(-ende) durch Höhenunterschiede beeinflusst werden?
Da müsste Feld schon eine enorme Hanglage haben, damit man 0,5m Unterschiede hat.
Hier helfen wohl nur Screenshots, welche sowas zeigen.

**Comment by Axel32019** [comment]
No update -> Closed.
