### ISSUE TITLE
trucks unload to other ones when driving by

### ISSUE THREAD

**Issue by docxgames** [Stephan-S/FS19_AutoDrive#1534]
I use a few trucks that transport liquids around my map. when they pass each other th full one stops and starts unloading in the empty one. after this happens i have to manually click continue on the truck to get it going again.

**Comment by ilian000** [comment]
i'm using v 1.1.0.4

**Comment by Iwan1803** [comment]
Sounds like wrong settings or special vehicle as this doesn't happen on my savegames.
Maybe screenshots and more informations could help.

**Comment by GitTomahawk** [comment]
I noticed that liquid transporters start overloading from time to time. 
It often happend when the full truck alost reached the unloading trigger.
Reducing the value of "max Siloabstand" helps to reduce that area.
Other option is to build paths in a manner that full and empty vehicles do not meet ech other near the Silo.

**Comment by ilian000** [comment]
autodrive settings: https://imgur.com/a/Pmjv9ou
and they are nowhere close to the unload point and the structure of the map makes itr impossible to never cross other trucks

**Comment by Axel32019** [comment]
No update -> Closed.
