### ISSUE TITLE
[Feature Request] Select Next and Previous Target with keyboard should follow the order of the Destinations list.

### ISSUE THREAD

**Issue by Dennizzzzz** [Stephan-S/FS19_AutoDrive#1535]
I use the keyboard (and game controller) to select the Next or Previous Target, and I'm seeing that the list when using the keyboard is not in alphabetical order. The list of destinations in the HUD is in alphabetical order.

The solution would be when using the 'select next' or 'select previous' target keys, the list where you're going through should be in alphabetical order.

I think there is no alternative...

**Comment by Dennizzzzz** [comment]
Did some digging in the xml files. As an alternative I sort the destinations when not in the game by sorting them in the xml file. Issue with this is that the park destinations of the vehicles is based on the location of the destination in the list. So after 'sorting' the park destinations for the vehicles are wrong. 

Something to consider when dealing with this feature-request.

**Comment by Iwan1803** [comment]
You should this here: https://github.com/JustDen1234/FS19_AutoDrive_Sort

**Comment by Axel32019** [comment]
No update -> Closed.
