### ISSUE TITLE
Abfahrer beim Häckseln fährt zu weit weg

### ISSUE THREAD

**Issue by JimmyBeam1990** [Stephan-S/FS19_AutoDrive#1538]
Moin, 

Ich habe folgendes Problem und zwar versuche ich auf der aktuellen Stappenbach mit AD den Häcksler abzufahren und das Ganze zur BGA zu fahren. soweit klappt es einigermaßen, noch nicht perfekt aber irgendwie gehts, ich kann aber leider den abstand zum Häcksler nicht einstellen, warum nicht??? warum fährt der immer so weit weg, egal bei welchem Häcksler?

https://prntscr.com/tmt96r
https://prntscr.com/tmt9gu
https://prntscr.com/tmt9k4
https://prntscr.com/tmt9om
https://prntscr.com/tmt9t5
https://prntscr.com/tmt9y1

Falsch eingestellt?? Log ist sauber, da werden von AD keine Fehler generiert.

**Comment by John-Deere89** [comment]
Stell mal abfahrer auf 0m Abstand oder sogar im minus vlt geht es dann

**Comment by JimmyBeam1990** [comment]
leider kein erfolg, habe es sogar komplett in den negativen bereich gedreht, keiner Veränderung

**Comment by Axel32019** [comment]
Sieht nach Problem mit mod-Drescher aus, kein AD Problem -> Closed.
