### ISSUE TITLE
[Feature Request] Mark previous and next points of selected one with another color.

### ISSUE THREAD

**Issue by Dennizzzzz** [Stephan-S/FS19_AutoDrive#1539]
I'm always frustrated when in edit mode I want to clean up some routes and not knowing which points are linked to the one i've selected.

It would be nice to mark the next and previous point of the selected one with another color.
See image below:

![2020-07-22 23_34_52-Farming Simulator 19](https://user-images.githubusercontent.com/10248136/88231349-5c989e80-cc74-11ea-8c32-5707ab171ccd.jpg)

**Comment by Axel32019** [comment]
@Dennizzzzz Hello,
We just "advanced" this idea a little bit: See here / Wenn Interesse hier entlang: #1663

**Comment by Iwan1803** [comment]
Da in 1.1.0.6 integriert, mach ich hier mal zu // Since integrated in 1.1.0.6, i'll close here 😎
