### ISSUE TITLE
[Question] AutoDrive wont dump both hoppers but did at sellpoint?

### ISSUE THREAD

**Issue by JohnDeere3** [Stephan-S/FS19_AutoDrive#1541]
**Question:**   
I've got a question...
So I had semi with a Wilson hopper setup to haul from field to a sellpoint and it dumped both hoppers, but now when I’m hauling off the farm yard(not in field or under a silo) and hauling it into my bin setup, it will not dump.

**Comment by Axel32019** [comment]
Have you set the destination point at least >1 length of the complete hopper setup?

**Comment by Axel32019** [comment]
No update -> Closed.
