### ISSUE TITLE
[Question] Doppelbelegung der rechten Maustaste mit dem HUD vom CP

### ISSUE THREAD

**Issue by SEETechWolf** [Stephan-S/FS19_AutoDrive#1542]
**Question:**   
Gibt es eine Möglichkeit entweder bei CursePlay die HUD aktivierung auf der rechten Maustaste abzuschalten oder das Verschieben von Wegpunkten im AD anders zu konfigurieren?

Wenn beide Mods installiert ist nervt das sehr wenn immer das CP HUD auf geht und die sicht versperrt.

**Comment by Easton97-Jens** [comment]
Das einzige was ich weiß ist in den normalen Tastatureinstellungen die Taste für CP hud Öffnung auf eine andere zu legen

**Comment by SEETechWolf** [comment]
Da ist aber gar keine Maustaste zugewiesen bei HUD öffnen/schließen. Selbst wenn ich da zB Maustaste 4 zuweise geht es immer noch auf der rechten Maustaste auf.. scheint dann ein CP Bug zu sein. 
Danke dann muss ich da mal schauen.

**Comment by SEETechWolf** [comment]
Habs gefunden... in den Erweiterten Einstellungen vom CP gibt es die Einstellung "Rechtsklick HUD" ja/nein
