### ISSUE TITLE
Beim Einfahren vom Streckennetz: Abstand zwischen den einzelnen Wegpunkten [Question]

### ISSUE THREAD

**Issue by BastiHRO** [Stephan-S/FS19_AutoDrive#1544]
Hallo liebes AD-Team!
Ich schaue mir gerade die TuT-Videos von Iwan auf YT an, was teilweise echt amüsnat aber auch lehrreich ist, um die Komplexen Möglichkeiten von AD auch richtig und fehlerfrei zu nutzen.
Auch ich fahre meine Streckennetze in Zusammenarbeit mit GPS ein, damit alles Sauber und ordentlich ist. Jetzt aber zu meiner eigentlichen Frage:

Besteht die Möglichkeit, bei Streckenaufzeichnung, die Abstände zwischen den Neu erstellten Wegpunkten auf GERADEN Strecken zu verkleinern?  Ich nutze (noch) das Streckennetz von Holger-70 auf der NFM (NF Marsch 4-Fach) und bei Ihm sind, auf geraden Strecken, die Abstände zwischen den Wegpunkten wesentlich kleiner als bei mir.

Über eine Antwort würde ich mich freuen ;)

P.S. Ich liebe AD und will es auch nicht missen. Macht bitte bitte weiter so! Ihr macht eine Klasse Arbeit. Vielen lieben Dank dafür... #modderloben

**Comment by andreasthu** [comment]
Hallo Basti
Ich denke das ist eine performancefrage.
Halbierte abstand wären dann die doppelte Anzahl an wegpunkten, zum Beispiel.
Geht es dir um die Kreuzungen?
Das stimmt, da sind die Abstände teilweise ungünstig lange um saubere einbiegemöglichkeiten zu bauen.
Du kannst es aber so wie ich machen:
Wenn du inzwischen mal einen Punkt brauchst, einfach eine Verbindung löschen,  dazwischen einen punkt reinsetzen und mit den zwei anderen verbinden,  fertig.
Lg
Andreas

**Comment by BastiHRO** [comment]
Hallo Andreas,
na so mache ich es ja auch ;) Aber ich dachte soetwas kann man irgendwo einstellen. Egal ;) aber danke für dein Commi ;)
