### ISSUE TITLE
[Feature Request] Flasher

### ISSUE THREAD

**Issue by ArtV-Nef** [Stephan-S/FS19_AutoDrive#1546]
Hi! Guys, a request or suggestion - could you transfer the settings of the flashing beacon individually to the transport. And thank you so much for the turn signals-super cool!

**Comment by Axel32019** [comment]
@ArtV-Nef See here / Wenn Interesse hier entlang: #1663

**Comment by Iwan1803** [comment]
Da in 1.1.0.6 integriert, mach ich hier mal zu // Since integrated in 1.1.0.6, i'll close here 😎
