### ISSUE TITLE
tractors no longer stand to the side

### ISSUE THREAD

**Issue by Crinouche** [Stephan-S/FS19_AutoDrive#1547]
**AutoDrive Version:** 1.1.0.5 RC5
**Release or Custom Zip:** Release  
**Map (If applicable):** All  
**Vehicle / Type (If applicable):**   
**Multiplayer or Singleplayer:** Singleplayer  

**Describe the bug**  

416/5000
First of all, well done for this work. AD is awesome.
I use AD with forage harvesters, because CP mode 2 is not working at all.
With version 1.1.0.5 RC5, tractors no longer stand to the side, but continually follow behind, in grass fields. It still works, but it's not too real. (With CP the problem is the same) Looks like AD and CP are using the same system ...

**If applicable - Steps to reproduce the behavior**  

**Screenshots**  
![image](https://user-images.githubusercontent.com/36656729/88548929-ff0fa380-d01f-11ea-97fc-79bdeba7ae80.png)
![image](https://user-images.githubusercontent.com/36656729/88548952-06cf4800-d020-11ea-85ef-9db056156046.png)
[log.txt](https://github.com/Stephan-S/FS19_AutoDrive/files/4982337/log.txt)

**Comment by Axel32019** [comment]
Hello @Crinouche,
The issue is that gras could not be distingished between on field and outside of a field.
Thats why the tractor is following the harvester behind. But isn't this better than not working at all?
Might be AD and CP are using a similar detection method, and so also CP can not detect field / outside field with gras on field.
Sorry to say but at the moment we have no better way to handle gras field(s).

**Comment by Crinouche** [comment]
Hello Axel,
Thank you for your reply. Indeed, it is better than nothing, but with the earlier version RC4, There was no problem, the tractors followed the forage harvester to the side, even in a field of grass.
Therefore, I thought that with the RC5 version, there was a problem.
On the other hand, now, I find that the tractors wait a little less before to find their way to the forage harvester and that it detects it more quickly.
Thank you for your work...

**Comment by ArtV-Nef** [comment]
![2020-07-28_12-41-21](https://user-images.githubusercontent.com/59769343/88650700-9f71d080-d0d1-11ea-8875-3a082416f1bf.jpg)

With these settings, everything works perfectly for cleaning fields with any harvesters. When harvesting silage, the tractor stands on the left side of the combine and even tries to avoid trees!) (for example, the "wild wild west" map") The AD version is the latest, and CP is the latest.

**Comment by Crinouche** [comment]
Indeed, it works with your setting.
Thanks for the info, ArtV-Nef,  and sorry for the inconvenience.
