### ISSUE TITLE
[BUG] Thresh tanker only with admin rights?

### ISSUE THREAD

**Issue by DiTechRacer** [Stephan-S/FS19_AutoDrive#1548]
AutoDrive Version: 1.1.0.4
Release or selbsterstelltes zip: Release
Karte (falls relevant): Multimap 2019
Fahrzeug(art) (falls relevant): Drescher und Abfahrer

**Beschreibe den Bug**
Ich Spiele mit meiner Frau. Ich hoste das Game (bin also der Admin). Bei mir Kommt der Fahrer um den Drescher abzutanken. Bei meiner Frau kommt er nicht. Woran liegt das? Unsere Settings sind exakt gleich..

LG Tim

**Comment by Axel32019** [comment]
Hallo,
Bitte mal mit der aktuellen Version 1.1.0.5-RC5 versuchen. Eure Version ist stark veraltet und wird nicht mehr bearbeitet.
Es wurden mittlerweile viele Änderungen vorgenommen.

**Comment by DiTechRacer** [comment]
Ich werde es die Tage testen. Danke für die Antwort!

LG Tim

**Comment by DiTechRacer** [comment]
Hey,

gerade getestet mit der aktuellsten Version. 

Ergebnis:

Bei mir Tankt er ab, **bei meiner Frau nach wie vor nicht.**
Habe ich einen Helfer eingestellt fährt er erst los wenn Drescher voll und rohr ausgefahren obwohl ab 85% gerufen werden soll.

**Comment by DiTechRacer** [comment]
Hey nochmal,

kann es sein, dass das Problem darin besteht, dass in der AutoDriveUsersData.xml nur eine uniqueID steht und das meine ist?
Kann ich da meine Frau auch hinzufügen? Wenn ja, wie finde ich ihre ID raus?

`<AutoDriveUsersData>
    <users>
        <user uniqueId="HixH4IALpZJR+a/n2TsAUs8K73Z+2WUXO1fNlq2Gm44=" hudX="0.869271" hudY="0.285926" showMarkersOnMap="2" guiScale="14" showTooltips="2" switchToMarkersOnMap="1" notifications="3" showNextPath="2" lineHeight="2" addSettingsToHUD="2" wideHUD="1" showHelp="1" iconSetToUse="1" secondEditorModeAllowed="2"/>
    </users>
</AutoDriveUsersData>`

**Comment by Axel32019** [comment]
Hey,
Mach bitte mal eine Sicherungskopie der Datei, lösch sie und starte das Spiel neu. Ist das Verhalten noch immer vorhanden?

**Comment by DiTechRacer** [comment]
Hey,
gesagt, getan. Neue AutoDriveUsersData.xml wurde erstellt mit dem gleichen Inhalt.
Problem besteht nach wie vor. Wenn meine Frau den Drescher zu 100% voll hat passiert nichts. Sobald ich in den Drescher einsteige fährt der Abfahrer los.

**Comment by DiTechRacer** [comment]
> Hey,
> Mach bitte mal eine Sicherungskopie der Datei, lösch sie und starte das Spiel neu. Ist das Verhalten noch immer vorhanden?

Hast du noch eine idee oder einen Tipp für mich? Das ist echt nervig..

**Comment by Axel32019** [comment]
Wie ist das denn mit dem Lohner-Status?

**Comment by DiTechRacer** [comment]
Was meinst du mit Lohner-Status?

**Comment by DiTechRacer** [comment]
?
Das Problem besteht immer noch

**Comment by Axel32019** [comment]
@DiTechRacer Gibt es hier noch etwas Neues?

**Comment by DiTechRacer** [comment]
Ne, spiele aktuell nicht.. kannst erst mal zu machen, danke dir
