### ISSUE TITLE
Verbesserungsvorschlag / Erweiterung

### ISSUE THREAD

**Issue by oldmicha** [Stephan-S/FS19_AutoDrive#1549]
Hallo zusammen
Wir spielen als virtueller Agarservice Preetz sehr gerne mit AD. Hauptsächlich z.Z. auf 4 fach Maps - gerade die MVP 19. Bei Nacht ist uns aufgefallen, das das Abblendlicht der Fahrzeuge recht spät an geht. Meistens zusammen mit der Map Beleuchtung. 

**Verbesserung/Erweiterung:**

- die Möglichkeit in AD die Beleuchtung der Fahrzeuge personalisiert pro Fahrzeug einzuschalten oder sogar Uhrzeit bezogen (z.B. ab 18 Uhr). Vorteil hierbei wäre nicht im dunkeln der Geisterfahrer auf der Map und mehr Realismus.

- Die Rundumkennleuchte / Warnleuchte der Fahrzeuge von global auf personalisiert zu ändern, so das große oder nur bestimmte Fahrzeuge damit fahren. Ist auch realistischer zu betrachten.

LG oldmicha

**Comment by Axel32019** [comment]
@oldmicha Hallo,
Das Beleuchtungsthema ist ein größerer Brocken - mal schauen wann das zeitlich machbar ist....
Rundumleuchte demnächst umgesetzt, oder BETA Test: See here / Wenn Interesse hier entlang: #1663

**Comment by Axel32019** [comment]
Sammlung hier #1820
