### ISSUE TITLE
Mit der neuen Version fahren die AD helffer zu schnell in Kurven

### ISSUE THREAD

**Issue by Mannie313** [Stephan-S/FS19_AutoDrive#155]
Hallo @Stephan-S 

Die Fahrzuege fahren mit (65KM/H hab ich so eingestellt) in die kurve und bremsen ziemlich spät. mit der Vorherigen version hat alles geklappt.

MFG Mannie313

**Comment by Mannie313** [comment]
![fsScreen_2019_05_27_19_57_35](https://user-images.githubusercontent.com/3021040/58433982-bd046e00-80b9-11e9-8b12-982d97b97220.png)
 
das Sind meine Einstellungen

**Comment by Stephan-S** [comment]
Hi,
ich habe in der aktuellen Version versucht das Kurvenfahren etwas 'sanfter' zu gestalten, so dass die Geschwindigkeitswechsel nicht ganz so abrupt wirken.
Kannst du mal mit der Einstellung "Distanz Vorausschauen (Bremse)" spielen. Möglicherweise reicht es den Wert zu erhöhen.
Wenn nicht, lasse ich ihn in der nächsten Version wieder etwas extremer abbremsen.

**Comment by Mannie313** [comment]
ok ich hab mal auf 60 meter gestellt und geb dann bescheid

**Comment by Mannie313** [comment]
Hier mal ein Video:
https://youtu.be/jd0p-nQjUeg

**Comment by Stephan-S** [comment]
Sieht ja an sich nicht verkehrt aus.
Aber was ist denn da am Ende passiert?
Liegt die Route da nach rechts weg?

**Comment by Mannie313** [comment]
Nein Geradeaus weiter. aber er verfährt sich da immer wieder. Mit der Alten version fuhr er normal weiter.

MFG Mannie313

**Comment by franky-b08** [comment]
Hallo Stephan-S,
das was Mannie313 beschreibt hatte ich gestern auch auf der NF Marsch an der Molkerei.
Eigentlich geht der Kurs nach dem Ablade Trigger ein Stück gerade aus und dann links herum durch die Einfahrt/Ausfahrt wieder auf die Straße, der LKW mit Tankauflieger ist nach dem entladen kurz nach dem Trigger nach rechts abgebogen und das 2mal (ich war in einem anderen Fahrzeug zu der Zeit). 
Beim 3ten Mal bin ich mit gefahren und der LKW hat dann den gespeicherten Kurs abgefahren ohne nach rechts abzubiegen.  
Nutze AD in der Version 1.0.2.2
MFG franky--b08

**Comment by Mannie313** [comment]
Ha Ha Ha. wie willste bei mir mit dabei sein im Singleplayer spiel. Sehr Lustig.

MFG Mannie313

**Comment by docgaming** [comment]
ye i have had this before as well, the driver gos into the sell point to fast/don't stop in time then when it's done unloading (if it still can unload) instead of it's next way point being in front or under the  vehicle it's  behind it so the driver turns around to get to it.
