### ISSUE TITLE
Externe Schnittstelle für Bessere Performance?

### ISSUE THREAD

**Issue by ole22143** [Stephan-S/FS19_AutoDrive#1550]
Ich denke viele werden das Problem kennen, dass der LS 19 leider nicht wirklich Multicore fähig ist, sobald man 10 Helfer laufen hat sind 60fps nicht mehr möglich. Das liegt ja anscheinend daran das der LS weitestgehend auf LUA Script besteht welches Multithreading nahezu unmöglich macht. Könnte man nicht in C oder Java ein externes Programm schreiben welches die Helfer Steuert welches Natürlich mehr als einen CPU Kern benutzt welches nur immer die Steuerungsbefehle an den LS Sendet und vom LS die Position bekommt, oder würde das zu einer Ähnlichen Auslastung führen.

Gruß Ole.
Und vielen Dank für diese Großartige Modifikation.

**Comment by Axel32019** [comment]
Hallo Ole, Vielen Dank das Du Dir Gedanken machst wie man die Performance verbessen kann!
Leider kommt man aus der LS Lua Umgebung nicht heraus, d.h. man kann kein externen Programme aufrufen und Ergebnisse zurückliefern. Ich hab das Thema Performance noch auf meiner Liste, da ich noch Ansatzpunkte sehe, kann aber dauern... Mach das alles ja schließlich in der Freizeit.

**Comment by ole22143** [comment]
Wenn ihr bei teilen mal Hilfe benötigt dann sagt bescheid.  
Ich hatte nur die Überlegung, denn Global Market schafft es ja auch mit dem Spiel zu interagieren. Also quasi eine LS Mod als client baut und der Verbindet sich mit dem Server. So wären auch im MP bessere Syncro möglich.

**Comment by Axel32019** [comment]
Hilfe wird immer gebraucht!
Kannst Dir ja mal ansehen was in den Funktionen onUpdate, onUpdateTick,onDraw in Specialization.lua (nicht) notwendig ist, für Client und / oder Server relevant ist. Weiter dann in AutoDrive.lua -> update, draw....
Bist herzlich eingeladen :-)

**Comment by ole22143** [comment]
Ich werde mich mal daran versuchen erstmal überhaupt ein Client Mod zu schreiben der es ermöglicht über externe Eingabe eine Maschine zu steuern.  Gruß.

**Comment by Axel32019** [comment]
Ich würde eher mit den o.g. Funktionen anfangen was zu optimieren - komme momentan zeitlich nicht so dazu.
Die vielen AD Funktionen in ein externes Programm zu implementieren würde m.E. zu viel Aufwand bedeuten, ganz abgesehen das dann im MP zu realisieren.

**Comment by Axel32019** [comment]
No update -> Closed.
