### ISSUE TITLE
suggestion: 1 time pickup deliver.

### ISSUE THREAD

**Issue by convict-vx** [Stephan-S/FS19_AutoDrive#1551]
hi,

i started playing autodrive a few days back and loving it so far. But i would suggest a 1 time pickup and deliver.

Now it works: pickup point, deliver point and type to load and it keeps doing that route and loading.. 
i would love to see the same but then below the type an end point so i can send the tractor to pickup stuff, deliver it to shop and then park back in its spot and does not keep going and going. so basically: Pickup, go to sell it and park again.

i know i can do a delivery but then it stays at sell point and still need to load it manually.

sincerely, 

convictvx

**Comment by Axel32019** [comment]
Hi, Right now it is clear to me what you need. Is it something diffent to https://github.com/Stephan-S/FS19_AutoDrive/wiki/Buttons-with-short-description Button 5?

**Comment by Obelixm** [comment]
Hi, 
he means the same like me (I think):
https://github.com/Stephan-S/FS19_AutoDrive/issues/1515

after the Tour the Driver goes to a different (Parking) Position and do not block other driver from loading/unloading

Best wishes 

Obelixm

**Comment by convict-vx** [comment]
hi,

yes, thats basically what i mean as Obelixm has posted. (as non german i needed google translate)

So it would be that i can tell my driver to:
1: go to silo and load
2: go to sell point and unload
3: go to a defined spot and park.

Right now if i'm not wrong it's like this:
1: go to silo and load
2: Go to sell point and unload
3: go back to silo.

alltough that loopcounter i can use to do this X times (i guess, never really used loopcounter) he will still park under or at my loading silo while other drivers that i sent away will be blocked by the one at the silo.

**Comment by Axel32019** [comment]
@convict-vx @Obelixm See here / Wenn Interesse hier entlang: #1663

**Comment by Iwan1803** [comment]
Da in 1.1.0.6 integriert, mach ich hier mal zu // Since integrated in 1.1.0.6, i'll close here 😎
