### ISSUE TITLE
[BUG] Connecting Waypoints creates route from last editing possition - Verbinden von Wegpunkten erstellt eine Route von der letzten possition an der man editiert hat

### ISSUE THREAD

**Issue by SEETechWolf** [Stephan-S/FS19_AutoDrive#1553]
AutoDrive Version: 1.1.0.5RC5
Release or selbsterstelltes zip: Release
Karte (falls relevant): Alle? Habe nur Felsbrunn getestet im MP
Fahrzeug(art) (falls relevant):

**Beschreibe den Bug**
Wenn ich mit STRG - rechts Klick Wegpunkte erstelle werden die letzten beiden automatisch mit einer Route verbunden. 
Also ich setze drei Wegpunkte 1,2,3 dann werden die Punkte 1 und 2 mit einer Route verbunden wenn ich Wegpunt 3 setze.
Das ist hoffentlich nicht so gewollt denn es ist sehr irritierend.

Wenn ich dann einen Wegpunkt auswählen will um von dort eine Route beginnen zu lassen wird der Wegpunkt zum Ziel einer Route, die ihren Ursprung an der Position hat wo ich das letzte mal Wegpunkte gesetzt habe.
Es scheint so, als würde der letzte aktive Wegpunkt aktiv sein.
Am besten wäre beim setzen eines neuen Wegpunktes entweder diesen zu selektieren oder garkeinen.

Ich vermute das das verhalten dieser beiden beschiebenen Erscheinungen zusammenhängt.

Momentaner Workaround ein paar Wegpunkte setzen und verbinden so das die Route aus dem Off entsteht, dann den Wegpunkt löschen und dann weiter machen.

Leider habe ich kein Tool um ein Video davon zu machen, wenn ihr eins empfehlen könnt versuche ich das gerne.

**Comment by SEETechWolf** [comment]
Wenn im MP zwei gleichzeitig Wege infahren gibt es zwischen beiden Wegen unvorhersehbare verbindungen im Zickzack muster.

**Comment by Axel32019** [comment]
Einzelne Screenshots reichen auch, muss kein Video sein. Immer nach jedem Klick einen Screeshot damit man die Reihenfolge sieht.
Kannst die Bilder dann bei Bedarf mit Paint (in Windows dabei) etwas kleiner schneiden...
Momentan kann ich laut Deiner Beschreibung z.B. nicht verstehen warum bei Setzen von WP 3 die WP 1 und 2 verbunden werden.
Über das gleichzeitige Aufzeichnen durch 2+ Spieler hab ich schon mal nachgedacht, hat aber einiges an Aufwand und möglicherweise Einschränkungen zur Folge - ist aber noch nicht vergessen....

**Comment by SEETechWolf** [comment]
Ich denke ich habe die telle im code gefunden wo dies passiert.
hud.lua Zeile 495ff
local createdId = ADGraphManager:getWayPointsCount()
if vehicle.ad.selectedNodeId ~= nil then
	ADGraphManager:toggleConnectionBetween(ADGraphManager:getWayPointById(vehicle.ad.selectedNodeId), ADGraphManager:getWayPointById(createdId), AutoDrive.leftLSHIFTmodifierKeyPressed)
end
vehicle.ad.selectedNodeId = createdId

Dadurch macht er eine Verbindung zwischen dem zuletzt selektierten punkten.
Meineserachtens können die Zeilen entweder ganz raus oder man müsste noch einen schalter in den einstellungen haben mit dem man diese Funktion ein und aus schalten kann

**Comment by SEETechWolf** [comment]
https://www.dropbox.com/s/xe2axa7bv6cjz4b/Farming%20Simulator%2019%202020-08-16%2018-52-34.mp4?dl=0

Hier konnte ich ein Video machen in dem das Verhalten zu sehen ist.
Die Punkte links habe ich zuerst gesetzt, man sieht das die Ersten Punkte verbunden sind.

Nach dem ich die Aufnahme starte und neue Wegpunkte setze sieht man wie er beim setzen des 2. Wegpunktes anfängt Verbindungen zu den vorherigen zu ziehen.. beginnen bei dem letzten Wegpunkt links... dieser könnte jetzt aich irgend wo anders sein. nur zur veranschaulichung hatte ich das jetzt direkt daneben gemacht.

**Comment by Axel32019** [comment]
Auto-Verbinden in MP deaktiviert in 1.1.0.5-RC6
