### ISSUE TITLE
Abladen an einem Silotrigger auf dem Dediserver geht nicht / Unloading on a silo trigger on the Dediserver does not work[BUG]

### ISSUE THREAD

**Issue by Mannie313** [Stephan-S/FS19_AutoDrive#1555]
AutoDrive Version: 1.1.0.5
Release or selbsterstelltes zip: selbsterstelltes zip
Karte (falls relevant): Alle
Fahrzeug(art) (falls relevant):

**Beschreibe den Bug**
Eine klare Beschreibung des Bugs.
Wir können auf dem Dediserver egal an welchem Silotrigger ob eigenes silo oder Zugsilo nicht mit AD automatisch abladen.
ich muß den kurs kurz unterbrechen und gleich nach dem ich I drücke den kurs wieder starten damit er seine tour weiterfahren kann. Fals nötig mache ich morgen ein Video.
**Falls anwendbar - Schritte mit denen ich den Bug nachstellen kann**

**Screenshots**
Falls relevant, bitte Screenshots beifügen

MFG Mannie313

**Comment by Madox61** [comment]
Genau dieses Problem haben wir auch was schade ist immer zwischen Drescher und Abfahrer hin und her zu springen damit entladen wird.

**Comment by fischi3016** [comment]
Zeig mir mal bitte einbild wo er vorm silo steht

**Comment by fischi3016** [comment]
Also ich kannes mit keinem Original Fahrzeug machen. Hab den Hawe ausm Modhub alle Fruchtypen reingeballert der funzt

**Comment by Steffen878** [comment]
Wir haben auch das Problem, das es mit dem Entladen auf dem Dedi nicht geht. Haben es auch mal mit dem Hawe getestet und können nur sagen, das es damit auch nicht geht.

**Comment by Axel32019** [comment]
@Mannie313, @fischi3016, @Steffen878, @Madox61 
Ihr seid herzlich eingeladen den aktuellen beta-Stand im MP zu testen!

Wer es noch nicht gemacht hat, hier eine kurze Anleitung:
https://github.com/Stephan-S/FS19_AutoDrive/tree/beta-testing

Code -> Download ZIP
Extract the downloaded zip "FS19_AutoDrive-beta-testing.zip"! Do not put it into the mod folder, this will not work !!!
In the extract you find the folder "FS19_AutoDrive" -> zip and put to mod folder -> start the game

Code -> Download ZIP
Die herunter geladene zip-Datei "FS19_AutoDrive-beta-testing.zip" auspacken! Nicht in den mod Ordner verschieben/kopieren, das funktioniert nicht !!!
In der entpackten Datei den Ordner "FS19_AutoDrive" neu als zip packen -> zip in mod Ordner kopieren -> Spiel starten

**Comment by fischi3016** [comment]
> 
> 
> @Mannie313, @fischi3016, @Steffen878, @Madox61
> Ihr seid herzlich eingeladen den aktuellen beta-Stand im MP zu testen!
> 
> Wer es noch nicht gemacht hat, hier eine kurze Anleitung:
> https://github.com/Stephan-S/FS19_AutoDrive/tree/beta-testing
> 
> Code -> Download ZIP
> Extract the downloaded zip "FS19_AutoDrive-beta-testing.zip"! Do not put it into the mod folder, this will not work !!!
> In the extract you find the folder "FS19_AutoDrive" -> zip and put to mod folder -> start the game
> 
> Code -> Download ZIP
> Die herunter geladene zip-Datei "FS19_AutoDrive-beta-testing.zip" auspacken! Nicht in den mod Ordner verschieben/kopieren, das funktioniert nicht !!!
> In der entpackten Datei den Ordner "FS19_AutoDrive" neu als zip packen -> zip in mod Ordner kopieren -> Spiel starten



was bist du denn für ein geiler Typ ^^ 

danke dir klaapt bestens aufn dedi Server. schönes Wochenende =)

**Comment by Steffen878** [comment]
Jetzt klappt es super. Super Arbeit und ebenfalls ein schönes Wochenende =)

**Comment by Madox61** [comment]
Super Arbeit läuft Wunderbar. Danke

**Comment by SEETechWolf** [comment]
Auch bei uns klappt es wunderbar mit der aktuellen Beta.
Nur der Baumwoll Anhänger wird nicht abgeleden. Ich vermute das liegt daran, dass der mechanismuss hier anders ist. Man mus den Hänger erst in einen Arbeitsmodus schalten und kann dann erst abladen.

**Comment by SEETechWolf** [comment]
Wäre für mich trotzdem gefixt, weil der Hänger eine Besonderheit darstellt.

**Comment by CmdrTiri** [comment]
Die aktuelle Beta läuft bisher wunderbar! Keine Komplikationen mit VCA oder ähnlichen Mods bisher, die Triggerpunkte klappen einwandfrei!
Vielen Dank für Eure Arbeit!!

Wenn es jetzt noch ne Version von CoursePlay geben würde, die auf Dedi-Servern laufen würde wäre alles perfekt (Ihr könnt da ja nichts für) - im Singleplayer klappt das ja einwandfrei.

**Comment by Tensuko** [comment]
> Wenn es jetzt noch ne Version von CoursePlay geben würde, die auf Dedi-Servern laufen würde wäre alles perfekt (Ihr könnt da ja nichts für) - im Singleplayer klappt das ja einwandfrei.

Aktuelle Version läuft laut einiger User recht gut...

**Comment by Mannie313** [comment]
@Axel32019 kannst du dir das mal anschauen 

https://github.com/Courseplay/courseplay/issues/6084

ob es vielleicht was mit AD zu tun hat Version 1.1.0.5 RC6

MFG Mannie313

**Comment by Axel32019** [comment]
@Mannie313 @fischi3016 @Madox61 @SEETechWolf @CmdrTiri @Steffen878  Bitte mal mit 1.1.0.5-RC6 probieren.

**Comment by Iwan1803** [comment]
Da 1.1.0.6 released wurde, mach ich hier mal zu // As 1.1.0.6 was released, i'll close here 😎
