### ISSUE TITLE
Black screen on horse ride

### ISSUE THREAD

**Issue by Dueesberch** [Stephan-S/FS19_AutoDrive#1556]
Since 2 days we get a black screen when we go to ride horses.
After reinstall FS19, removing all mods and adding mods one by one I found the problem with AD. If AD isn't installed / enabled riding works as expected. Adding AD 1.1.0.5-RC and enable it the application crash when we start riding.
I can't test with version 1.1.0.4. Download is currently not possible due to HTTP error.
I tested with GIANTS version and Steam version of application. Also with 2 different HW setups (Workstation and Lenovo Legion Laptop). Always the same result. So I add only the logs from Legion.

Without AD:
[log_wo_AD.txt](https://github.com/Stephan-S/FS19_AutoDrive/files/5006200/log_wo_AD.txt)

With AD:
[log_w_AD.txt](https://github.com/Stephan-S/FS19_AutoDrive/files/5006204/log_w_AD.txt)
Error at line 269 happens already at start.

**Comment by Axel32019** [comment]
Hallo, Wird im nächsten Release gefixt sein, siehe #1526.

**Comment by Iwan1803** [comment]
Da schon integriert, mach ich hier mal zu // Since integrated, i'll close here 😎
