### ISSUE TITLE
[Feature Request] Ballenladewagen abladen?

### ISSUE THREAD

**Issue by andreasthu** [Stephan-S/FS19_AutoDrive#1557]
**Is your feature request related to a problem? Please describe.**  
Ich verwende CP als Feldarbeit um z.b. mit dem Ladewagen den Heu bzw Strohschwad aufzusammeln und nutze AD dazu dieses zum Hayloft bzw zur Verkaufsstelle zu bringen. 
Soweit funktioniert es, aber:
Das ganze funktioniert nur eingeschränkt  bei Ballen mit z.b. dem arcusin autostack:
1. Wenn der arcusin voll ist, wird die Arbeit nicht von CP nach AD übergeben.
2. Starte ich AD manuell, hält der Traktor mit dem arcusin nicht beim Verkaufspunkt an und lädt ab, sondern fährt einfach voll durch, wieder zurück zum Feld.

**Describe the solution you'd like**  
AD sollte 1. den vollen arcusin erkennen und den abfahrkurs starten, und 2. am Zielpunkt halten und die Ballen entladen.

**Describe alternatives you've considered**  
Das sollte natürlich auch mit den ursus rundballensammlern funktionieren.

**Additional context**  

Lg
Andreas

**Comment by Axel32019** [comment]
Hallo Andreas,
Ballen abladen funktioniert mit AD leider (noch) nicht. Du kannst maximal im Modus "Fahren" zur Abladestelle fahren lassen und nach Zielwechsel zurück zum Feld.

**Comment by Axel32019** [comment]
Mit Release 1.1.1.6 wird EAL gesteuert, damit ist die Kombi CP + AD realisiert.

**Comment by andreasthu** [comment]
Ja danke,
Das ist ja schon ein uralter Beitrag.
Es funktioniert schon sehr gur, Danke
Lg
Andreas
