### ISSUE TITLE
Trigger erkennen nenne ich es mal so.

### ISSUE THREAD

**Issue by spielera** [Stephan-S/FS19_AutoDrive#1558]
Hallo,
ich habe Saatgut und Dünger Abfüllstationen nahe zusammen stehen.
früher habe ich der Sähmaschine gesagt, er soll Dünger auffüllen.
Da er an der  über den Trigger des Saatgut gefahren ist, hat er da angehalten und hat erst einmal Saatgut aufgefüllt, und dann zum Dünger aufladen gefahren.
Nun lässt er das Saatgut links liegen und fährt nur zum Dünger auffühlen.
Habe ich was falsch eingestellt, oder ist das(in meinen Auge) ein Bug im Programm?

Es ist aber immer noch eins der besten Programme, was es jemals für LS gegeben hat.
Macht weiter so.

mfg Dom :)

**Comment by Axel32019** [comment]
Hallo,
AD Version? Screeshot wäre auch hilfreich.

**Comment by spielera** [comment]
Hallo,
sorry.
ich habe die Version Latest Release Candidate: 1.1.0.5-RC5

mfg Dom :D

**Comment by Axel32019** [comment]
Bitte mal den Zielpunkt min. >1 Gespannlänge hinter die letzte Füllstation setzen und den max. Siloabstand erhöhen.

**Comment by spielera** [comment]
Hi Axel,
danke für deine Antwort.
Ich habe den Siloabstand hoch genommen, und schon funktioniert es wieder.
Mach weiter so.
mfg Dom :D
