### ISSUE TITLE
Patato harvest with CP and AD [BUG]

### ISSUE THREAD

**Issue by tomy852** [Stephan-S/FS19_AutoDrive#1559]
AutoDrive Version: 1.1.0.5 
Release or selbsterstelltes zip: RC 5
Karte (falls relevant): Felsbrunn

Fahrzeug(art) (falls relevant): Ropa Keiler 2

**Beschreibe den Bug**
Hallo zusammen,
das Kartoffelernten mit Courseplay  funktioniert nicht wenn Autodrive im Modordner ist. Ich kann den Kurs nicht starten der Traktor bleibt einfach stehen. Entfernt man AD läuft es problemlos.

Hello everybody,
Potato harvesting with Courseplay does not work if Autodrive is in the Mod folder. I can't start the course, the tractor just stops. If you remove AD it runs without problems.
 
**Falls anwendbar - Schritte mit denen ich den Bug nachstellen kann**
Standart Map und Maschinen

**Screenshots**
[log.txt](https://github.com/Stephan-S/FS19_AutoDrive/files/5014937/log.txt)

**Comment by Axel32019** [comment]
Hallo @tomy852, Ist schon bearbeitet mit #1543.

**Comment by tomy852** [comment]
ah ok :) danke und macht weiter so 👍

**Comment by Axel32019** [comment]
Fix enthalten in 1.1.0.5-RC6
