### ISSUE TITLE
Frage zwecks Abfahrer

### ISSUE THREAD

**Issue by Mannie313** [Stephan-S/FS19_AutoDrive#156]
Ich hab da mal nur eine Frage.

Wäre es möglich AD nicht am Startpunkt abfahren zu lassen sondern ein oder zwei wegpunkte später. wen man zwei abfahrer hat kommen die sich immer in die quere wen die abladestellen nicht zu weit weg sind.

MFG Mannie313

**Comment by Stephan-S** [comment]
Hi,
grundsätzlich eine gute Idee.
Ich denke wenn ich es einbaue, dann als Option, da es sicher auch Felder/Situationen gibt in denen das als Standardverhalten zu Problem führen kann.

Beste Grüße,
Stephan

**Comment by Mannie313** [comment]
![fsScreen_2019_05_28_12_53_58](https://user-images.githubusercontent.com/3021040/58472936-b58ba600-8147-11e9-8f82-d2b1fd9544e1.png)

Und hier die problematik mit zwei abfahrern. der Fordere wartet auf den Drescher und der Hindere will abladen fahren.

**Comment by Knowen** [comment]
Mal eine andere Überlegung: 
Wenn der Abfahrer voll ist und abladen will, kann er dann nicht einen nahen Wegpunkt finden und zum Abladeort fahren ohne über den Startwegpunkt fahren zu müssen? 
Beispiel: Ich habe ein Feld und drumherum ein Wegenetzt durch Feldwege oder Hauptstraßen. Mein Startpunkt ist auf der Nordseite vom Feld. Der Drescher befindet sich am südlichen Rand und muss abgeladen werden, der Ablader kommt und nimmt nach dem Abtanken ein Wegpunkt südlich des Feldes um zum Abladeort zukommen, anstatt quer über das Feld zum Startpunkt zu fahren und dann zum Abladeort. 

Wäre das möglich?

**Comment by Mannie313** [comment]
Möchte er ja machen. das Bild dient nur als Hinweiß wie es zur zeit Passiert mit den Abfahrern.

**Comment by Knowen** [comment]
> 
> 
> Möchte er ja machen. das Bild dient nur als Hinweiß wie es zur zeit Passiert mit den Abfahrern.

So wie ich dich verstehe will er immer über den Startpunkt, den benannten Wegpunkt, fahren um zum Abladeort zu kommen. Ich habe vorgeschlagen einfach einen nahen Wegpunkt zu nehmen OHNE über den Startpunkt zu fahren. Nach dem Abladen fährt er wieder normal zum Startpunkt und wartet dann auf den Drescher.

**Comment by Mannie313** [comment]
Hallo @Stephan-S 
Bis jetzt läuft es bei mir mit den Abfahrern. Aber mit den Rübenrodern muß ich noch testen.

MFG Mannie313
