### ISSUE TITLE
[BUG]Fruchtzerstörung / fruit destruction 

### ISSUE THREAD

**Issue by Ralf08** [Stephan-S/FS19_AutoDrive#1560]
AutoDrive Version: 1.1.0.5-RC5
Release or selbsterstelltes zip: Release
Karte (falls relevant): Alle
Fahrzeug(art) (falls relevant): Güllefässer, Miststeuer, Düngerstreuer, Sämaschinen (gezogen)

**Beschreibe den Bug**
Vielleicht ist es in Feature, kein Bug, aber ich konnte keine Informationen darüber finden.
Einige  Anhänger (Güllefässer, Miststreuer, Düngerstreuer, Sämaschinen) zerstören die Frucht während AD selbstständig fährt, aber nur der Anhänger. Der Traktor selber macht keine Fruchtzerstörung, Dieselben Gespanne mit dem Giants-Helfer verursachten keine Fruchtschäden, bei User-Contolled hatte der Traktor und der Anhänger die Frucht zerstört (AD controlled)
Kipper, Ladewagen, Überladewagen und auch der Tieflader haben im selben Test keine Frucht zerstört.

**Falls anwendbar - Schritte mit denen ich den Bug nachstellen kann**
Gespann in ein Feld mit gewachsener Frucht stellen und per AD aus dem Feld fahren.

*******************************************************************************
AutoDrive version: 1.1.0.5-RC5
Release or self-made zip: Release
Card (if relevant): All
Vehicle (type) (if relevant): liquid manure drums, dung control, fertilizer spreaders, seeder (pulled)

** Describe the bug **
Maybe it's in feature, not a bug, but I couldn't find any information about it.
Some trailers (liquid manure drums, manure spreaders, fertilizer spreaders, seeder) destroy the fruit while AD drives independently, but only the trailer. The tractor itself does not destroy the fruit, the same tractor set with the Giants helper did not cause any fruit damage, with user-controlled the tractor and the trailer had destroyed the fruit.
Tippers, loader wagons, overloader wagons and even the low loader did not destroy any fruit in the same test (AD controlled)

** If applicable - steps with which I can readjust the bug **
Place the team in a field with grown fruit and drive them out of the field using AD.

**Comment by Axel32019** [comment]
Hallo @Ralf08 , AD steuert keine Fruchtzerstörung. Das Fahrzeug wird über AIVehicle gesteuert - da können wir nichts dran ändern.
