### ISSUE TITLE
[Question]AutoDriveEditor - Editor has no map file for map: Ravensberg_

### ISSUE THREAD

**Issue by andreasthu** [Stephan-S/FS19_AutoDrive#1562]
**Question:**   
I've got a question...

Hallo Leute
wenn ich mit dem Autodrive-Editor die  AutoDrive_Ravensberg_config.xml öffnen möchte, funktioniert das nicht:

`[INFO ] 2020-08-04 07:24:28.915 [AWT-EventQueue-0] AutoDriveEditor - AutoDrive start.............................................................................................
[INFO ] 2020-08-04 07:24:30.522 [AWT-EventQueue-0] EditorListener - ActionCommand: Load
[INFO ] 2020-08-04 07:24:40.614 [AWT-EventQueue-0] AutoDriveEditor - loadFile: C:\Users\anthu\Documents\My Games\FarmingSimulator2019\savegame1\AutoDrive_Minibrunn_config.xml
[INFO ] 2020-08-04 07:24:40.655 [AWT-EventQueue-0] AutoDriveEditor - Root element :AutoDrive
[INFO ] 2020-08-04 07:24:40.662 [AWT-EventQueue-0] AutoDriveEditor - Current Element :waypoints
[INFO ] 2020-08-04 07:24:41.158 [AWT-EventQueue-0] AutoDriveEditor - Loaded config for map: Minibrunn
[INFO ] 2020-08-04 07:24:41.378 [AWT-EventQueue-0] AutoDriveEditor - loadFile end.
[INFO ] 2020-08-04 07:26:13.747 [AWT-EventQueue-0] AutoDriveEditor - AutoDrive start.............................................................................................
[INFO ] 2020-08-04 07:26:15.486 [AWT-EventQueue-0] EditorListener - ActionCommand: Load
[INFO ] 2020-08-04 07:26:25.602 [AWT-EventQueue-0] AutoDriveEditor - loadFile: C:\Users\anthu\Documents\My Games\FarmingSimulator2019\savegame7\AutoDrive_Ravensberg_(Beta)_config.xml
[INFO ] 2020-08-04 07:26:25.615 [AWT-EventQueue-0] AutoDriveEditor - Root element :AutoDrive
[INFO ] 2020-08-04 07:26:25.617 [AWT-EventQueue-0] AutoDriveEditor - Current Element :waypoints
[INFO ] 2020-08-04 07:26:25.680 [AWT-EventQueue-0] AutoDriveEditor - Loaded config for map: Ravensberg_
[INFO ] 2020-08-04 07:26:25.683 [AWT-EventQueue-0] AutoDriveEditor - Editor has no map file for map: Ravensberg_
[INFO ] 2020-08-04 07:26:25.684 [AWT-EventQueue-0] AutoDriveEditor - loadFile end.
[INFO ] 2020-08-04 07:26:29.012 [AWT-EventQueue-0] EditorListener - ActionCommand: Load Image
[INFO ] 2020-08-04 07:26:46.737 [AWT-EventQueue-0] EditorListener - ActionCommand: Load
[INFO ] 2020-08-04 07:26:53.893 [AWT-EventQueue-0] AutoDriveEditor - AutoDrive start.............................................................................................
[INFO ] 2020-08-04 07:26:55.928 [AWT-EventQueue-0] EditorListener - ActionCommand: Load
[INFO ] 2020-08-04 07:27:05.322 [AWT-EventQueue-0] AutoDriveEditor - loadFile: C:\Users\anthu\Documents\My Games\FarmingSimulator2019\savegame7\AutoDrive_Ravensberg_(Beta)_config.xml
[INFO ] 2020-08-04 07:27:05.341 [AWT-EventQueue-0] AutoDriveEditor - Root element :AutoDrive
[INFO ] 2020-08-04 07:27:05.344 [AWT-EventQueue-0] AutoDriveEditor - Current Element :waypoints
[INFO ] 2020-08-04 07:27:05.429 [AWT-EventQueue-0] AutoDriveEditor - Loaded config for map: Ravensberg_
[INFO ] 2020-08-04 07:27:05.432 [AWT-EventQueue-0] AutoDriveEditor - Editor has no map file for map: Ravensberg_
[INFO ] 2020-08-04 07:27:05.433 [AWT-EventQueue-0] AutoDriveEditor - loadFile end.
[INFO ] 2020-08-04 07:27:06.462 [AWT-EventQueue-0] EditorListener - ActionCommand: Load Image
[INFO ] 2020-08-04 07:30:37.183 [AWT-EventQueue-0] AutoDriveEditor - AutoDrive start.............................................................................................
[INFO ] 2020-08-04 07:30:39.027 [AWT-EventQueue-0] EditorListener - ActionCommand: Load
[INFO ] 2020-08-04 07:30:49.510 [AWT-EventQueue-0] AutoDriveEditor - loadFile: C:\Users\anthu\Documents\My Games\FarmingSimulator2019\savegame7\AutoDrive_Ravensberg_config.xml
[INFO ] 2020-08-04 07:30:49.530 [AWT-EventQueue-0] AutoDriveEditor - Root element :AutoDrive
[INFO ] 2020-08-04 07:30:49.532 [AWT-EventQueue-0] AutoDriveEditor - Current Element :waypoints
[INFO ] 2020-08-04 07:30:49.610 [AWT-EventQueue-0] AutoDriveEditor - Loaded config for map: Ravensberg_
[INFO ] 2020-08-04 07:30:49.613 [AWT-EventQueue-0] AutoDriveEditor - Editor has no map file for map: Ravensberg_
[INFO ] 2020-08-04 07:30:49.614 [AWT-EventQueue-0] AutoDriveEditor - loadFile end.
`
bei anderen maps, Minibrunn bzw DonDiego funktioniert es.
der pfad ist in der mapDE.xmlrichtig hinterlegt
<map width="2048" height="2048" imageFilename="maps/pda_map_H.png">
und ingame funktioniert es auch
lg
andreas

**Comment by Axel32019** [comment]
Hallo @andreasthu ,
Der externe Editor wird derzeit wohl nicht bearbeitet.
Mache hier demnächst zu.

**Comment by andreasthu** [comment]
Hallo Axel.
Mittlerweile funktioniert es bei.mir wieder im
 externen Editor .
Lg
Andreas
