### ISSUE TITLE
Project Stopped?

### ISSUE THREAD

**Issue by Podvorie** [Stephan-S/FS19_AutoDrive#1565]
Sorry.

I understand that the project is stopped?
Stefan hasn't shown up for over three months. There is no progress in updates either.

I don't swear. I'm worried if something bad happened to Stefan or other developers. Covid could have negatively affected the situation. This would not be desirable.

**Comment by Iwan1803** [comment]
In the last months there was always at least one release candidate per month. 
Just because Stefan is no longer so active, the project is far from being shut down.
Also it's summer and holiday time 😎
