### ISSUE TITLE
Feld verlassen - AD Programmierung

### ISSUE THREAD

**Issue by Berios** [Stephan-S/FS19_AutoDrive#1566]
Hallo zusammen!

Ich habe mal eine Frage:

eigentlich funktionieren AD und CP sehr gut zusammen. Allerdings kommt es beim Verlassen von Feldern immer zu sehr komischen "Lufkreisen",  welche auf einigen Karten ein echtes Problem darstellen.

Eben zur Veranschaulichung:

Ich arbeite auf einem Feld, welches ich mit AD komplett eingefahren und umrandet habe. Das ganze Feld ist mit einer AD - Strecke eingefaßt, welche an bestimmten Stellen das jeweilige Fahrzeugt zurück auf die Straße bringt.
Meine Fahrzeuge sind alle auf Feldbegrenzung eingestellt und nutzen als Abfahrtseinstellung "Nächstgelegen", da ich sie so sehr effizient auf meinen "Feldring" und von dort geordnet auf die jeweiligen Straßen führen kann. 
Nunmehr lasse ich ein Fahrzeug z, B. Stroh sammeln und nutze AD zur Abfahrt (Einstellung in CP). CP füllt den Ladewagen korrekt. Wenn dieser voll ist, wird das Fahrzeug gemäß Einstellung auch korrekt in Richtung des "Feldrings" (dem umgebenenden AD - Streckenring) geleitet. Sobald aber die Ringstrecke erreicht wird, fängt das Fahrzeug an einen vollkommen unnötigen Kreis zu drehen und fährt nicht direkt auf den besagten Strecknring. Da das Fahrzeug bei dieser merkwürdigen Kreisbewegung über die Feldbegrenzung / den AD - Ring hinaus fährt, kommt es immer wieder zu Problemen. Gerade an Stellen, wo in der Nähe Fellswände oder Klippen sind, wird es echt ärgerlich. Ich denke, daß diese Kreisbewegung von AD und nicht von CP verursacht wird. Iwan hat dieses auch schon häufiger in seinen Videos bemängelt - aber bei ihm auf der NF - Marsch können die Fahrzeuge nur im Graben landen. ;-) 

Wäre es möglich, dieses Problem (ist ja kein wirklicher BUG) eventuell zu lösen?

Ich würde mich sehr darüber freuen.

Danke,

Berios

**Comment by Axel32019** [comment]
Hallo @Berios ,
Besteht das Problem in der aktuellen Release-Version noch immer?

**Comment by Axel32019** [comment]
no update -> closed
