### ISSUE TITLE
 No response / call stack problem with AD version 1.1.0.5 RCxx

### ISSUE THREAD

**Issue by DeltaOmikron** [Stephan-S/FS19_AutoDrive#1567]
Ich habe seit der AD version 1.1.0.5 das Problem das mein spiel nach gefühlten zwanzig Minuten einfach einfriert (Keine Rückmeldung😑). In der AD version 1.1.0.4 läuft alles Problemlos, das Problem in 1.1.0.5 tritt immer auf wenn ich nach diesen zwanzig Minuten in ein Fahrzeug steigen will das AD aktiviert hat. In dem Szenario sind es 4 Abfahrer und zwei Feldhäcksler (kann aber auch jeder andere standard und dlc Drescher sein) die soweit funktionieren bis besagter Fehler eintritt.
Dieser Fehler tritt in jeder 1.1.0.5-RC version auf. Es ist auch egal auf welcher map ich spiele es tritt trotzdem auf.
Ich hab leider nicht so viel Ahnung von der Giants Engine, ich hab hier zwei Logs für euch.
Zwei logs daher da ich test weise den Mod Fend Vario 1000 raus genommen habe der im log einen Error/warning zeigte.

[log with Fend vario 1000.txt](https://github.com/Stephan-S/FS19_AutoDrive/files/5062550/log.with.Fend.vario.1000.txt)
[log without fend vario 1000.txt](https://github.com/Stephan-S/FS19_AutoDrive/files/5062552/log.without.fend.vario.1000.txt)

Ich bedanke mich schon mal für eure Bemühungen. 😊

**Comment by Williwillswisse** [comment]
Hallo DeltaOmikron,
in deiner Log finde ich eigentlich nur Errors zu Courseplay.
Hast du schon mal eine andere CP Version getestet oder ohne CP?

**Comment by DeltaOmikron** [comment]
@Williwillswisse In der Version 1.1.0.4 funktioniert AD mit CP so wie es soll, nur in allen versionen der 1.1.0.5-RCxx gibt es probleme. Ich hab die neueste CP version v6.02.00047 aber auch ohne CP oder mit älteren CP versionen gibt es Probleme wenn ich die AD 1.1.0.5-RC03, RC05 benutze. wenn ich halt zurück auf die 1.1.0.4 gehe funktionieren halt die Rückwärts Kurse nicht mehr, was ich gern vermeiden würde wenn es möglich ist.

**Comment by Axel32019** [comment]
Waren der Fendt 1000 (erster  log) und der AXION 960 (zweiter log) eventuell Missions-Fahrzeuge?

**Comment by DeltaOmikron** [comment]
@Axel32019 Der Fendt 1000 und der Axion 960 sind mods wobei es beim Axion auch sein kann das der aus dem Claas dlc ist, zumindest steht bei giants auf der seite das da einer drinnen ist.
Der Fendt 1000 war in dem video der top 10 Traktoren von Mario Hirschfeld. Ich hab noch nie gehört das Mod Fahrzeuge in Missionen zum Einsatz kommen, eine Mission habe ich auch nicht am laufen. Der Callstack beginnt auch immer erst wenn ich  nach einer bestimmten zeit in ein Fahrzeug einsteigen will und dabei ist egal welches Fahrzeug.
Bei anderen scheint die 1.1.0.5-RCxx ja zu funktionieren mit CP, auch auf der NF Marsch 4fach.
Neuer Spielstand auf dem ersten platz hat auch nicht geholfen und wenn der Freeze passiert erstellt er immer einen Spielstand 6 aber auch nur zur hälfte. 🤔 LS habe ich auch schon mehrmals neuinstalliert.
Ich gehe mittlerweile davon aus das alles daran liegt das die 1.1.0.5-RC noch eine Entwickler version ist.

**Comment by Axel32019** [comment]
No update -> Closed.
