### ISSUE TITLE
[Question] Get back a previous version

### ISSUE THREAD

**Issue by Chico0008** [Stephan-S/FS19_AutoDrive#1568]
**Question:**   
Hi, is there any way to get back the previous RCx versions ?
the last 1.1.0.5-RC5 is way to buggy for me, i'd like to get back the RC4 or RC3, but i can't find how to download them again

Thx for help

**Comment by Axel32019** [comment]
Did you had a look on Discord: https://discord.gg/9D4B5hX ?

**Comment by Chico0008** [comment]
Didn't know there was a discord
thanks
