### ISSUE TITLE
[BUG] just for your information, in beta version RC6 the mode "pickup/delivery" does not work correctly anymore - nur zur Info, in Beta version RC6 funktioniert der modus "Abholen/abliefern" nicht mehr korrekt.

### ISSUE THREAD

**Issue by haamic** [Stephan-S/FS19_AutoDrive#1569]
AutoDrive Version: 1.1.0.5
Release or selbsterstelltes zip: beta ReleaseC 6
Karte (falls relevant): Alle
Fahrzeug(art) (falls relevant):

**Beschreibe den Bug**
Ich weiss, das es keinen Support für die Beta gibt, möchte nur eine info geben das mit dem Modus "Abholen/Abliefern" etwas bei mir nicht mehr stimmt.
Per CP lade ich den Schwad mit einem Sammelwagen von einem Feld auf. Wenn der Anhänger voll ist, übergibt CP an AD, nur fährt er nicht zum Abladen sondern zum Feldanfang (Aufladepunkt) zurück und übergibt wieder an CP. so gehts immer im Kreis.
Wenn ich auf den "Weiterfahren-button" klicke, wechselt er zum Abladeziel. und macht das, was er eigentlich sonst immer automatisch getan hat.

**Falls anwendbar - Schritte mit denen ich den Bug nachstellen kann**

**Screenshots**
Falls relevant, bitte Screenshots beifügen

**Comment by Axel32019** [comment]
Hallo @haamic , Bitte mal einen Screenshot mit Einstellung "mehr Einstellungen im HUD" einfügen. Danke.

**Comment by haamic** [comment]
Habs geschlossen. Komischerweise klappt das nun wieder. Hab nichts verändert. Ich beobachte weiter und melde mich, Falls es Wieder auftritt.
