### ISSUE TITLE
Wo gibt es gute Tututorials für LUA Skript?

### ISSUE THREAD

**Issue by SEETechWolf** [Stephan-S/FS19_AutoDrive#1570]
Hi, ich würde gerne die Grundlagen von LUA mir anschauen.

Welche Tools könnt ihr empfehlen und welche Tutorials so das man euch dann auch gut unterstützen kann.

**Comment by Axel32019** [comment]
Hallo @SEETechWolf, Schön das Du Dich dafür interessierst. Ich schaue häufig hier rein:
https://www.lua.org/pil/contents.html
https://gdn.giants-software.com/index.php

**Comment by SEETechWolf** [comment]
Habe gesehen das es ein Plugin für IntelliJ git da fühle ich mich zuhause :)

Habt ihr einen Discord Chanel oder so wo ihr euch austaucht? dann muss ich nicht alle FRagen hierüber stellen, das die meisten vermutlich eh nicht interessiert.

**Comment by Axel32019** [comment]
https://discord.gg/9D4B5hX

**Comment by Bobster82** [comment]
> Habe gesehen das es ein Plugin für IntelliJ git da fühle ich mich zuhause :)
> 
> Habt ihr einen Discord Chanel oder so wo ihr euch austaucht? dann muss ich nicht alle FRagen hierüber stellen, das die meisten vermutlich eh nicht interessiert.

I am interested ;) Discord aint working for me though...

**Comment by Axel32019** [comment]
No update -> Closed.
