### ISSUE TITLE
[Question] How can I get AD to unload on any trigger that is on the way to the target? - Wie kann ich AD dazu bringen, an jedem Trigger abzuladen, der sich auf der Strecke zum Ziel befindet?

### ISSUE THREAD

**Issue by haamic** [Stephan-S/FS19_AutoDrive#1571]
**Question:**   
I've got a question...
How can I get AD to unload on any trigger that is on the way to the target?
This is supposed to be avoided otherwise, but in my case it is desired.
Maybe this can be made selectable as an option in the menu.
I am testing with the new GC fruit trees. These border a willow. I have created a round course. AD should unload on this circuit at every tree trigger.
If I let AD drive in the "pickup/delivery" mode, it will drive to the destination (last tree) and unload there, not on the way at any other triggers (trees) that take the filltype.
Now I have each tree as a rotating target in a folder, which is quite complex.
So far it works, but I can never start again at a target of my choice. AD remembers the last target and continues at the next target. 
For example, AD unloads at 50 out of 100 trees. There were problems with target 40 and I want to start again. But AD starts at 51. Is it possible in the future to set in the menu whether the next destination in the folder or the one in the selected folder is used? Or have I overlooked an already existing possibility?

Greetings Micha

+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

Wie kann ich AD dazu bringen, an jedem Trigger abzuladen, der sich auf der Strecke zum Ziel befindet?
Das soll ja sonst eigentlich vermieden werden, in meinem Fall ist es aber erwünscht.
Vielleicht kann das als Option im Menü anwählbar gemacht werden.
Ich teste gerade mit den neuen GC-Obstbäumen. Diese umsäumen eine Weide. Ich habe einen Rundkurs erstellt. AD soll auf diesem Rundkurs bei jedem Baum-trigger abladen.
Lasse ich AD im "Abholen/Abliefern" modus fahren, fährt er zum Ziel (letzter Baum) und lädt dort ab, nicht unterwegs an evtl. anderen Triggern (Bäumen), die den Filltype annehmen.
Habe jeden Baum jetzt als rotierendes ziel in einem Ordner, was relativ aufwendig ist.
Soweit funktioniert das, aber ich kann nie selber wieder an einem Ziel meiner Wahl beginnen. AD merkt sich das letzte ziel und macht am darauffolgenden Ziel weiter. 
Also z.b. AD lädt an 50 von 100 Bäumen ab. bei Ziel 40 gabs probleme und ich möchte da nochmal beginnen. AD beginnt aber bei 51. Kann das evtl. zukünftig auch im Menü einstellbar gemacht werden, ob das nächste Ziel im Ordner oder das im eingestellte verwendet wird? Oder hab ich eine bereits vorhandene Möglichkeit übersehen?

Gruss Micha

**Comment by Iwan1803** [comment]
Es wird keine Sonderlösungen für "Spezialfälle" (und Einzelschicksale) geben, aber beschreib doch mal das "Problem" an Baum 40. Ein Fehler kann es ja nicht gewesen sein, sonst hätte AD "gemeckert" 😉
Bei mir sind gut 10-12 Fahrzeuge im 24h-Dauereinsatz "Abholen & Abliefern", mal mit mehreren Zielen oder Ladepunkten oder beidem. Ich habe zwar nicht die Masse an Zielpunkten in den Ordnern, aber wenn man diese korrekt setzt, kann jedes Fahrzeug dort problemlos laden/abladen. Allerdings würde ich auch nicht so viele in einen Ordner packen, sondern mehrere Ordner erstellen und dann halt auch mehrere Fahrzeuge nutzen.

**Comment by haamic** [comment]
Also gibt es keine Möglichkeit, an allen triggern, denen AD auf einer Strecke begegnet, zu entladen, ausser am Ziel. 
Es sei denn man macht die aufwendigere Variante mit einzelnen Zielen für jeden Baumtrigger.
Das mit Baum 40 war nur ein Beispiel. Es ging mir darum, das man die rotierenden Ziele nicht resetten kann, so das AD wieder mit dem ziel 1 im Ordner, bzw. mit einem eingegeben Ziel aus dem "Rotations-Ordner" beginnt, sondern das AD immer mit dem nächstfolgenden fortsetzt.
Hätte ja sein können es wäre vielleicht zukünftig möglich, AD per Option zu sagen, das nur am Ziel oder und an allen Triggern auf dem Weg zum Ziel abgeladen werden soll.
Trotzdem danke für die Rückmeldung.

**Comment by Axel32019** [comment]
Das geht mit dem rotierenden Entladen -> Closed.
