### ISSUE TITLE
[BUG] Abfahrer lädt nicht automatisch ab

### ISSUE THREAD

**Issue by labamichnetvoll** [Stephan-S/FS19_AutoDrive#1572]
AutoDrive Version: 1.1.0.5
Release or selbsterstelltes zip: Release
Karte (falls relevant): Hof Bergmann V 1.0.0.62
Fahrzeug(art) (falls relevant): (Fliegl Transportpack)

**Beschreibe den Bug**
Abfahrer im modus "Drescher abtanken" lädt nicht automatisch ab abladetrigger ab. Hier manuelles Eingreifen notwendig.
Zudem auf dem Feld nach dem Ruf des Dreschers, bleibt der abfahrer immer wieder stehen bevor er den drescher erreicht.
da die position des Dreschers sich zu sehr geändert hat in der zwischenzeit

ausprobiert auf der Map Hof Bergmann V1.0.0.62 mit dem Streckennetz von crykor
[https://www.lsfarming-mods.com/wbb/index.php?thread/1066-download-autodrive-profil-f%C3%BCr-1-0-0-6-support-updates/&pageNo=1](url)

**Comment by Iwan1803** [comment]
Beschreibe "manuelles Eingreifen notwendig". Einfach nur AD stoppen und I fürs Entladen drücken oder vorfahren und dann I drücken?

**Comment by labamichnetvoll** [comment]
Also das Silo ist zum rückwärts einparken, ( das macht AD echt gut, fährt dann soweit zurück, dass der Hänger im abladetrigger steht, aber nicht automatisch überlädt, sodass man kurz abbrechen muss um selbst „i“ zu drücken 

Ginge das theoretisch, dass AD nach dem hänger abladen noch weiter zurück fährt, dass der lkw auch entleert  wird?

**Comment by Iwan1803** [comment]
Kannst du mal einen Screenshot vom AD-Netz an der Stelle posten?

**Comment by Mannie313** [comment]
Ist es das gleiche wie #1555 

MFG Mannie313

**Comment by labamichnetvoll** [comment]
![image](https://user-images.githubusercontent.com/58562415/90384032-3f8f9980-e081-11ea-82e3-ca8ff2bf68ce.png)

der abfahrer hat den hänger jetzt automatisch abgeladen und ist weiter zurückgefahren, der LKW selbst sollte so schon im trigger stehen, da ich beim deaktiveren von AD, selbst überladen kann.

**Comment by Mannie313** [comment]
Beim hänger sind meist Collisionen drin wo das abladen vom LKW verhindern.

Das ist mir auch schon passiert.

MFG Mannie313

**Comment by Iwan1803** [comment]
Genau deswegen sollte man seine Trigger, welche Probleme machen, einfach mal einem Non-Mod-Fahrzeug testen.

**Comment by labamichnetvoll** [comment]
danke, hab ich verstanden.. weiß ich nun fürs nächste mal
