### ISSUE TITLE
Better AutoDrive vehicle speed adaption to vehicles running in front 

### ISSUE THREAD

**Issue by harleymac** [Stephan-S/FS19_AutoDrive#1573]
Problem: Currently the AutoDrive vehicles almost crash other vehicles on the road in front of them , then they stop, accelerate and the process repeats.

Solution: measure the speed of the vehicle in front or the distance to it and adapt the speed to the same level or keep the distance at a fixed value so the AutoDrive vehicle runs smoothly behind it instead of oscillating.

Kind regards,
harleymac

**Comment by Iwan1803** [comment]
Did you deactivate the collision detection?

**Comment by harleymac** [comment]
Hi,

collision detection is on.

Regards

**Comment by Iwan1803** [comment]
Maybe you must raise or lower the collision detection and set look ahead to max.

**Comment by harleymac** [comment]
Thanks – where can I do this?
It seems this cannot be found in the AutoDrive option menu.

Kind regards

**Comment by Iwan1803** [comment]
It was added in 1.1.0.5-RC4:

> ADDED: setting "Collision heigth over ground" to adjust collision detection

and can be found in the AD options.

**Comment by harleymac** [comment]
Thanks, found.
But that does not change the behavior of the vehicles with AutoDrive.
They keep distance to the car in front by braking, accelerating and so on. That looks  unrealistic and is why I proposed to copy or measure the speed of the car in front in order to get a smooth driving behavior of the vehicles under AutoDrive.

Best regards

**Comment by Iwan1803** [comment]
That means a lot of measuring and calculations, which could decrease FPS.

**Comment by harleymac** [comment]
Understood – thanks for the insight.

**Comment by Stephan-S** [comment]
I agree with Iwan here. This is too much work for an inherently cosmetic feature.
