### ISSUE TITLE
Drescher findet Abfahrer nicht (Abfahrer wartet auf Ruf)

### ISSUE THREAD

**Issue by xFranky78x** [Stephan-S/FS19_AutoDrive#1574]
Ich benutze AD um Drescher abzutanken und habe auf einem sehr großen Feld das Problem, dass der Abfahrer nicht zum Drescher fährt bzw. nicht gerufen wird.
Kann man da was an den Einstellungen ändern??

**Comment by Dschowy** [comment]
Dem Drescher muss man im AD Menu den Wegpunkt vom Abfahrer zuweisen. Nicht aktivieren, sondern nur den Wegpunkt anwählen, dann sollte das klappen.

**Comment by xFranky78x** [comment]
Hey super hat geklappt danke
