### ISSUE TITLE
My driver doesn't drive under the unloading pipe but collides with the combine harvester.[Question]

### ISSUE THREAD

**Issue by OstseeFarmer** [Stephan-S/FS19_AutoDrive#1575]
**Question:**   
I've got a question...
My driver doesn't drive under the unloading pipe but collides with the combine harvester.

**Comment by Iwan1803** [comment]
Mods?

**Comment by OstseeFarmer** [comment]
Yes

**Comment by Iwan1803** [comment]
Then please try with normal vehicles.

**Comment by Mannie313** [comment]
@Iwan1803 Ich hab auch Moddrescher und wen ich den versatz auf 0 stelle klappt es im SP und Dedi.

MFG Mannie313

**Comment by Axel32019** [comment]
No update -> Closed.
