### ISSUE TITLE
[Feature Request] Make Tipside selection configurable

### ISSUE THREAD

**Issue by GitTomahawk** [Stephan-S/FS19_AutoDrive#1576]
AD often chooses wrong Tipside. e.g. "Kornschieber" is benn used very often.

Why not make Automatic Tipside selection configurable?
Enabled:  AD automatically choses tipside at trigger
Disabled: Current selected Tipside will be used and not changed by AD

**Comment by Axel32019** [comment]
@GitTomahawk See here / Wenn Interesse hier entlang: #1663

**Comment by Iwan1803** [comment]
Da in 1.1.0.6 integriert, mach ich hier mal zu // Since integrated in 1.1.0.6, i'll close here 😎
