### ISSUE TITLE
Feature Reqeust: Roads with lower priority / higher cost

### ISSUE THREAD

**Issue by minyman60** [Stephan-S/FS19_AutoDrive#1577]
Hello,

Please could you implement a road with a higher path finding cost, or a lower priority?

I find it annoying that my tractor wants to drive through the silo, instead of on my main road around it. 

Also, I have another silo mod that acts as an auger wagon, and i cant have my tractors path finding past it without accidentally taking seeds in it's trailer. Having a lower priority on that path would help me greatly, as it would ensure the tractor would use the main roads i want, not path find through silos.

Kind regards,

Minyman60

**Comment by Iwan1803** [comment]
Sorry, but we will not add attributes to waypoints. 
To avoid driving on roads with target points, you should raise "Maximum detour" in the AD settings.
