### ISSUE TITLE
Extending Call Request Distance[Question]

### ISSUE THREAD

**Issue by mudgw2** [Stephan-S/FS19_AutoDrive#1578]
**Question:**   
Greetings, awesome plug btw! been enjoying it allot...makes the game much more playable IMHO.  I'm currently on a map with very LARGE fields (Honey Dew map), and I noticed that the unload/combine method dosnt work as the trucks are too far away from the harvesters/combines.  I went into the mod XML and added 500 and 1000 distances to the call request, but it dosnt seem to really do anything.

Is there a way to extend the call distance for large fields or another trick?  What I have done now is I have 4 trucks (north,soiuth,east,west) and hope one of them is close enough.

Thanks

**Comment by Axel32019** [comment]
Hello, Have you set the first target in Harvester and Unloader to the same?
In Harvester do not activate AD!

**Comment by alepinci** [comment]
same here. working great on small fields but on large ones I need to drive the tractor near the combine

**Comment by Iwan1803** [comment]
For the harvester deactivate the search for an unloader in the AD settings. Then set in AD for the harvester the same target as for the unloader. AD will then search across the whole map 😉

**Comment by mudgw2** [comment]
Sounds interesting, will give it a try today and report back.  I assume the "target" is the navigation point used by the unloader.  Currently my unloaders go to a "wait" nav near the field...and then have a "unload" nav at my silo.

**Comment by alepinci** [comment]
> For the harvester deactivate the search for an unloader in the AD settings. Then set in AD for the harvester the same target as for the unloader. AD will then search across the whole map 😉

worked for me, thanks!

**Comment by mudgw2** [comment]
Yeah I think its working for me too..definately different behavior.  I didnt know that if a combine has a destination selected in AD thats the same as the collector..that they will work.  Figured if combine was not "ON" and AD was running it did nothing..interesting!

**Comment by Iwan1803** [comment]
So everybody is happy and i'll close here 😎
