### ISSUE TITLE
[Question] Frage zur nutzung auf Dedicated Server

### ISSUE THREAD

**Issue by smarx0ne** [Stephan-S/FS19_AutoDrive#1579]
**Question:**   
Hallo,
Ich bin ein grosser Fan der Mod, super Arbeit
Vielen dank für die Mod :-)
Jetzt zu meiner Frage:
Wir haben einen Dedicated Server, auf dem wir gerne Autodrive nutzen würden. 
Wir haben es auch schon getestet, nur ist uns aufgefallen, dass zb 2 Spieler nicht gleichzeitig einen Kurs erstellen können, weil sich da die Wegpunkte irgendwie ineinander "buggen"
Das selbe passiert, wenn man einen seiner wegpunkte löschen möchte, da passiert es, dass plötzlich ein ganz anderer wegpunkt gelöscht wird.
Gibt es da irgendeinen Trick oder ein Video, wo beides erklärt wird?
Oder ist das einfach nur eine einstellungssache?

Vielen dank im voraus für Antworten oder Hilfe:-)

**Comment by GitTomahawk** [comment]
- Ich editiere Pfade möglichst nur wenn ich grad alleine auf dem Server bin, da ich auch schon über diverse bugs gestolpert bin.
- Wenn doch andere Mitspieler online sind ist es am besten erst den Pfad anzulegen und als letzten Schritt die Zielmarkierungen - dann werden auch alle Wegpunkte sauber zu den Mitspielern synchronisiert.
- Außerdem ist es von Vorteil als Admin angemeldet zu sein und direkt im Anschluss zu speichern.
- Beim Hinzufügen neuer Wegpunkte im Editor mode2 muss man aufpassen, da teilweise zufällig einer der letzten Punkte "selektiert" wird und mann dann schnell ungewollte Verbindungen schafft.

**Comment by Axel32019** [comment]
No update -> Closed.
