### ISSUE TITLE
Abfahrer fährt durch Frucht

### ISSUE THREAD

**Issue by haamic** [Stephan-S/FS19_AutoDrive#158]
Hallo,
wie im Beispielvideo [https://www.youtube.com/watch?v=5VX1F4wPPgo&t=705](url) , ab etwa 00:11:50, vom User Cairo zu sehen, fährt der Abfahrer durch die Frucht, obwohl der Drescher ja Platz gemacht hat. Ist das ein Fehler, oder geht das nicht anders? Er könnte doch dem Drescherweg folgen und endet ja dann am ausgefahrenen Rohr, zumal das Rohr ja eigentlich nicht in der Frucht stünde, da ja nebenan Wiese ist.
Gruss Micha

**Comment by Stephan-S** [comment]
Hey haamic,
Cairo erklärt es ja ganz gut in seinem Video.
Aber hier mal noch etwas weitergehend:

Durch die Frucht fährt der Abfahrer nur als Backuplösung, also quasi der Notfallplan, wenn er es nicht geschafft hat einen fruchtfreien Weg in vernünftiger Zeit (je nach PC, ca 0.5-1.5 Minuten) zu berechnen.

Dabei musst du auch wissen, das er sich das Feld bzw die Welt während dieser Suche in kleine Quadrate aufteilt und diese auf verschiedene Kollisionen und vor allem auch auf die Frucht hin überprüfen muss.
In meinem ersten Video dazu, siehst du eine kurze Visualisierung von dieser Einteilung wenn du genau hinsiehst: https://youtu.be/cC50lfNVmxs?t=186

Dann wird immer das Quadrat untersucht, dass gerade am nächsten zum Drescher(rohr) liegt und noch nicht überprüft wurde. Wenn ich mir das Video von Cairo ansehe, kann ich mir gut vorstellen, wie er sich da kaputt rechnet. Er weiß ja nicht, das er 'einfach den Drescherweg nachfahren kann', sondern startet mit 0 Vorwissen. Er will ja auch immer den schnellsten und kürzesten Weg finden.
Das heißt er sucht quasi abwechselnd in allen Richtungen verzweifelt nach einem Weg. Und der einzige fruchtfreie und kollisonsfreie ist einmal um das Ganze Feld herum. Bis er den erkannt hat, hat er bereits tausende andere 'Quadrate' überprüf, bis ihm schließlich die Zeit abgelaufen ist und er den Notfallhammer auspackt und quer übers Feld fährt.

Im schlimmsten Fall liegen die Quadrate die er übers Feld liegt auch nicht genau mit dem bereits geerntetem Vorgewende überein, sondern so das ein Teil immer links neben dem Feld und in den begrenzenden Bäumen landet und die andere Seite halb in der Frucht, und schon ist der Weg ums Feld für seine Pfadfindung ganz aus dem Spiel. Das ist auch der wahrscheinlichste Fall in dem Beispielvideo.

TL,DR:
Pfadfindung ist alles andere als trivial :-D 
Ich hoffe du hast trotzdem deine Freude am Spiel und am AutoDrive Mod

**Comment by haamic** [comment]
Na klar hab ich Freunde am Spiel und an Autodrive. Mach weiter so, super Mod.
Also theoretisch müssten die Quadrate kleiner sein, damit die nicht in einem Bereich landen der nicht ganz abgeerntet ist, damit AD nicht denkt es ist Frucht bzw. ein Hindernis? Dann rechnet er noch länger, ist logisch. Mir würde es nichts ausmachen, noch etwas länger zu warten, anstatt das er mir die Frucht zerstört.
Vielleicht wäre es möglich, in den Einstellung das als Option wählbar zu machen. ob er wirklich erst alle Möglichkeiten abchecken kann/darf oder man ihn doch nach einem Zeitintervall den Notfallplan ausführen lässt. Aber man kann ja die Fruchtzerstörung ausschalten, dann umgeht man das ganze.
Wird CP noch etwas angepasst, damit der Drescher nach Abladen nicht den Abfahrer seitlich wegschiebt, wie im Video zu sehen? eigentlich müsste er nur noch ein Stück weiter vorfahren und dann auf seine Bahn lenken. oder Könntest du den Abfahrer nach dem abtanken ein  kleines Stück zurücksetzen lassen?
Auch fährt der Drescher das Rohr nicht aus, wenn die Arbeit beendet ist. Wenn dies mal von CP umgesetzt wird, würde der Abfahrer dann trotzdem wieder angefahren kommen, wenn der Drescher z.b. nur 10% im Korntank hat? Kann AD erkennen das das die "letzte Fuhre" wäre und fährt dann zum abladen und evtl dann sogar die Fahrt dort beenden, da ja das Feld nicht mehr angefahren werden muss

**Comment by haamic** [comment]
Oh, der Abfahrer fährt ja jetzt ein stück zurück, super, danke.

**Comment by Stephan-S** [comment]
hey, 
hier noch ganz kurz ein paar Bemerkungen zu deinen Vorschlägen:

Rückwärts fahren nach entladen: Check ;-)

Kleinere Quadrate -> nicht möglich, da sie so groß gewählt sind, das der Traktor durchpasst und platz zum Einlenken ins Nachbarfeld hat.

Fruchtumfahrung: Solange ein Helfer aktiv am Steuer ist, wird ja eigentlich keine Frucht zerstört, es ist also von vornherein ein kosmetisches bzw. immersives Feature

Nach FeldEnde von CP:
Wenn CP rufen würde (Drescher muss entleert werden), dann würde AD unabhängig vom Füllgrad anfahren. Aber eine Kommunikation, das es jetzt die letzte Ladung vom Feld war, wird nicht an AD weitergegeben. Aber ich denke es ist nicht tragisch wenn AD dann nach dem Abladen wieder bis ans Feld fährt oder? Ansonsten eben auf die CP Meldung warten, dass die Arbeit erledigt ist.
Selbst wenn ein CP Drescher sagt er ist fertig, weiß ich ja nicht ob nicht noch andere in der Nähe entladen werden sollen.

Beste Grüße,
Stephan

**Comment by haamic** [comment]
Hallo Stephan,
ich nutze immer die aktuellen Version von AD+CP.
Heute im Drescher Abtanken Modus, passierte es, das der Abfahrer voll wurde, aber der Drescher noch nicht leer war. ich bin mir nicht mehr sicher ob der Abfahrer ein Stück zurück setzte, egal.... jedenfalls dauerte es ein paar Sekunden und beide (Drescher und Abfahrer) fuhren gleichzeitig los, und natürlich ineinander. Normalerweise, wenn der Drescher wirklich leer wird, fährt er auch zuerst los. Da sollte evtl. mit CP noch was angepasst werden. 
Der Drescher fuhr 2 Vorgewende und dennoch bretterte der Abfahrer voll durch die Frucht. Das klappt also immer noch nicht so gut. Ja, Ich weiss, das keine Frucht zerstört wird. Vielleicht findet er ja trotzdem irgendwann mal einen Weg auf dem abgeernteten Feld. Ist keine Kritik nur eine Feststellung.
Andere Frage, da AD quasi ja ein Navi ist, wäre es möglich theoretisch evtl. eine Rest-Fahrtzeit zum Ziel im HUD einzublenden?
Prima Arbeit Stephan, weiter so...
Gruss Micha

**Comment by haamic** [comment]
ich muss dazu sagen, es handelte sich um den Ropa Panther (zuckerrübe). heute mit einem normalen Drescher ging das abtanken und wegfahren und Fruchtumfahren (Gerste) ohne Probleme. Allerdings fuhr der Abfahrer als er voll war zum Start und nicht zum Abladeort.

**Comment by Stephan-S** [comment]
Hey,
gibt es hier noch Handlungsbedarf oder klappt es bei dir mit den neuesten Versionen besser?

Die Fahrtzeitanzeige habe ich in ein neues Issue verfrachtet (#213 )

Ansonsten mache ich hier demnächst zu :-)

**Comment by haamic** [comment]
Kann erstmal zu. Bis  auf ein paar Rempler des Dreschers mit dem Abfahrer funktioniert es
