### ISSUE TITLE
[BUG] AD to unload straw with CP

### ISSUE THREAD

**Issue by alepinci** [Stephan-S/FS19_AutoDrive#1580]
**AutoDrive Version:** 1.1.0.5 RC5   
**Release or Custom Zip:** Release     
**Multiplayer or Singleplayer:** Singleplayer  

**Describe the bug**  
Hi, I'm using courseplay to collect straw with a loading wagon along with autodrive to unload it. When the trailer is full, AD starts automatically and the tractor goes to the exit point of the field but when it reaches it CP start again and the tractor returns into the field. Is it a known bug?

**Comment by Iwan1803** [comment]
Maybe your settings are wrong as i could collect straw without any problems.
Are you using a mod waggon and can you post your settings for it?

**Comment by Axel32019** [comment]
No update -> Closed.
