### ISSUE TITLE
[BUG] MP: nodes disappear

### ISSUE THREAD

**Issue by Zaneboy** [Stephan-S/FS19_AutoDrive#1581]
**AutoDrive Version:** 1.1.0.4   
**Release or Custom Zip:** Release  
**Map (If applicable):** Stone Valley x4
**Vehicle / Type (If applicable):** N/A
**Multiplayer or Singleplayer:** Multiplayer

**Describe the bug**  
After relogging in multiplayer either one or multiple node connections or multiple nodes **can** dissapear. When loading a previously made AD save the nodes do not reappear. I don't know if a node or connection dissapears each time or what may be the trigger for this. No warnings or errors in log folder. It's also very time consuming to recheck everything, especially if you have nodes overlapping on an existing connection it's much more difficult to spot missing items. Unknown if server restarts can affect this issue.

**If applicable - Steps to reproduce the behavior**  
Relog in the MP server.

**Comment by Iwan1803** [comment]
> Unknown if server restarts can affect this issue.

Restart and you will know it 😉

**Comment by Zaneboy** [comment]
I fixed one of the missing connections, saved and restarted the server. The fixed connection didn't dissapear again. I looked around but didn't notice anything else missing after the restart.

I don't know when the first time happened that some of the connection nodes got removed, this could be going on for a little while without us noticing it since we're not extensively using AD yet but already had the road network laid out. Now that we're aware of the issue we'll try to follow up on it much closer. And just to be clear, the missing nodes weren't something I forgot to finish when creating our road network. Last dissappearance was a complete left turn on a four-way junction to a sell point..

**Comment by Iwan1803** [comment]
FYI: the AD config is only saved when the game is saved.
Maybe that has caused the lost of some waypoints.

To avoid this you should take a look at the mod "Dedi save", which is a small script every player needs:
> As soon as the last player leaves the server the game will be automatically saved.

**Comment by SEETechWolf** [comment]
This Bug sounds like [1554](https://github.com/Stephan-S/FS19_AutoDrive/issues/1554) this is Fixed in current Beta.

**Comment by Axel32019** [comment]
Fixed in 1.1.0.5-RC6
