### ISSUE TITLE
[Feature Request]: Kann beim Namen der Autodrive_....._config.xml nicht auf den Mapnamen verzichtet werden?

### ISSUE THREAD

**Issue by F-Patsch** [Stephan-S/FS19_AutoDrive#1582]
Hallo liebes AD-Team, 
zuerst ein großes Danke für diesen tollen Mod und die Möglichkeiten die dieser eröffnet. Nun zu meinem "Problem" / zu meiner Anfrage: 
In der AD Config Datei die sich im Savegame erzeugt wird 2x der Name der Map inkl. Versionsnummer hinterlegt, ebenso im Dateinamen. Wenn es nun ein Update der Map gibt muss man diese Einträge und den Dateinamen manuell bearbeiten, weil ansonsten beim Start der Map alle Strecken und Zielpunkte verschwunden sind.

Ist es möglich auf diese Einträge zu verzichten? Ich lese öfters nach Mapupdates von einigen Nutzern "Hilfe mein AD-Netz ist verschwunden" und auch mir selbst ist es schon einige male passiert. Zum Glück gibt es die Savegamebackups aus denen man das wieder herausziehen kann, aber schöner wäre es wenn dies nicht nötig wäre.

Im Falle das dies hier schon einmal angefragt wurde und ich nur zu doof war dies zu finden bitte ich um Schließung / Löschung dieser Anfrage.

Grüße und bitte macht noch lange weiter
Frederike  Patsch

**Comment by Iwan1803** [comment]
Hallo Frederike,
frag doch mal Dani, ob er die Versionsnummer im Maptitle nicht einfach weglassen kann. Dann müsste man auch nicht die AD-Datei "manipulieren", wenn es ein Update gibt 😉
Es gibt nun mal ein paar Sachen, welche man in der Progammierung/Modding nicht machen sollte und dazu gehört z.Bsp. die Versionsnummer (oder Sonderzeichen) im Maptitle. Viele Mapper halten sich zum Glück dran, aber einige wenige leider nicht und das führt immer wieder zu Problemen oder Doings, an die nicht jeder User beim Update denkt.
Ich bin daher der Meinung, das das "Problem" nicht von uns irgendwie umgangen oder ausgehebelt werden sollte. Würden wir das nämlich umbauen, dann hätten vermutlich ganz viele andere User Probleme, weil ihre Configs nicht mehr gefunden werden.
Die Mapper/Modder müssten hier mal um- & mitdenken. Wenn die sich nämlich an die Grundlagen halten, hätten wir so einige Anfragen und Probleme erst gar nicht.

Nicht falsch verstehen, aber wir können AD nicht jedes mal verbiegen, nur weil irgendwer der Meinung ist, sich nicht an die Spielregeln halten zu müssen.

**Comment by Mike1977** [comment]
@Iwan1803 Manchmal habe ich echt das Gefühl, das dein einziger Job hier ist, die Leute zu vergraulen. Deine Antworten sind sehr oft weder kompetent, noch hilfreich. 
Die Versionsnummern der Maps dienen der Übersichtlichkeit. Wie sonst soll jemand wissen, welche Version einer Map auf einem Server läuft, wenn mir nur die Namen der Mods angezeigt werden die sort laufen? Das wäre sicher alles kein Problem wenn alle Mods über den Steam Workshop laufen würden, wo jeder User immer die jeweils aktuelle Version hat. Das ist hier aber nicht der Fall, und so hat jeder die Version drauf, die er als letzte geladen hat. Und ein Mod, der mit anderen Mods zusammenarbeitet, sollte das Berücksichtigen. Deshalb ist die Anfrage von Frederike durchaus berechtigt.

Die Frage hier war, ob der Name der Map im Namen der config unbedingt sein muss, oder ob man den nicht auch weglassen kann. Deine Antwort war irrelevant, weil sie auf die Frage überhaupt nicht eingegangen ist. Wenn es aus Programmiertechnischer sicht eine Notwendigkeit gibt, kann man das auch sagen, und nicht eine Schuldfrage beantworten, die niemand gestellt hat.

**Comment by F-Patsch** [comment]
Wenn es nicht geht, geht es nicht - dann mach ich hier wieder zu

**Comment by Iwan1803** [comment]
@Mike1977 
ich nehme deine seltsame Meinung über mich mal so hin, auch wenn ich nicht weiß, wie du dazu kommst. Meine Intention ist es jedenfalls, allen hier zu helfen und dazu gehört auch, Probleme zu erkennen deren Ursache nicht zwingend in AD liegen.
Falls es dir nicht gefällt, wie ich das hier mache oder dir irgendwas nicht passt, dann steht es dir natürlich frei, dich mit Stephan in Verbindung zu setzen.

Zurück zum Thema....
Hast du dir schon mal die modDesc.xml näher angesehen und dich mal schlau gemacht, wo und welche Infos man da reinschreiben kann und vor allem, wo und wie diese Infos dann überall im Spiel angezeigt und verwendet werden?
Es gibt entsprechende Variablen, welche man bei jedem Mod auch entsprechend füllen sollte: 
- author = Ersteller/Mapper/Modder
- title = Name der Map/des Mods
- version = Versionsnummer
- description = (kurze) Beschreibung
Diese Infos kann man Ingame sehen, z.Bsp. beim Spielstand laden (und natürlich auch anderen Stellen):
![image](https://user-images.githubusercontent.com/47528836/91971766-05c5c080-ed1a-11ea-887b-abe346ada618.png)
Bei Maps ist _title_ und _description_ auch noch ein mal zusätzlich in extra _maps_-Tags vorhanden und hier liegt der Fehler, den einige Mapper/Modder machen, indem sie dort an den _title_ auch noch die Version mit dran schreiben. Dies führt dann bei uns zu den Problemen, das wir die Configs nicht mehr finden, welche wir darüber identifizieren.
Ist keine Configdatei auffindbar, wird beim Speichern proforma eine mit Defaultwerten abgespeichert. So verhindern wir im übrigen auch, das was falsches geladen wird, was neben Fehlern auch zu Abstürzen führen könnte.

Mein Post beinhaltet neben der Erklärung für das Problem, dessen Ursprung nicht in AD liegt, auch eine Antwort, warum eine Änderung keinen Sinn macht:
> Ich bin daher der Meinung, das das "Problem" nicht von uns irgendwie umgangen oder ausgehebelt werden sollte. Würden wir das nämlich umbauen, dann hätten vermutlich ganz viele andere User Probleme, weil ihre Configs nicht mehr gefunden werden.
Auf gut deutsch: ändern wir das jetzt in AD, betrifft diese Änderung alle AD-User und die Anfragen würden drastisch hochgehen, weil die Configs ja nicht mehr gefunden werden. Korrigieren die Mapper das einfach in ihren nächsten Versionen und weisen darauf hin, dann wäre nur ein Bruchteil der gesamten AD-User davon betroffen.
 
Die "Spielregeln" sollten übrigens Programmierer kennen und es sind quasi ungeschriebene Gesetze, welche man einfach berücksichtigt, um die größtmögliche Kompatibilität zwischen verschiedenen Systemen zu erreichen. 
Allein die Logik sagt einem aber doch schon, das man in eine Variable auch nur das einträgt, was gefordert ist oder schreibst du in Formularen bei "Nachname" auch noch deinen Geburtstag mit rein?

Und falls du es noch nicht wusstest: dem Modhub sind die Infos aus der modDesc.xml völlig egal, um nach Updates zu suchen.
Das Spiel bzw. der Modhub vergleich nämlich nur die Namen und Hashwerte der Dateien im mods-Ordner, um Unterschiede zu finden, was in meinen Augen ein Fail von Giants ist.
Dies kannst du selber testen, indem du einfach die Versionsnummer eines Mods aus dem Modhub erhöhst. Theoretisch sollte das Spiel kein Update für diesen Mod finden, aber aufgrund des unterschiedlichen Hashwertes meldet es dennoch ein verfügbares Update.

**Comment by Mike1977** [comment]
Ich habe keinen Grund Stephan anzuschreiben, denn mit ihm habe ich ja kein Problem. Ich kläre das direkt mit den Leuten die das betrifft. 
Ich bekomme alles was hier geschrieben wird, per Email, und habe so im laufe der Zeit schon des öfteren feststellen müssen, das sich die Antworten von Stephan sehr von deinen Unterscheiden. Deine Antworten wirken meist unfreundlich und inkompetent und das wurde auch schon sehr oft von diversen Leuten festgestellt. 
Das soll kein persönlicher Angriff sein, sondern ein konstruktives Feedback. Du kannst das negativ bewerten und ansonsten ignorieren, oder du kannst es annehmen und versuchen besser zu werden. Das ist deine eigene Entscheidung.
Ich habe selbst vor einigen Jahren im Support eines Software Projektes gearbeitet und weis daher wovon ich rede. 

Du sagst das die "Spielregeln" bei Programmierern bekannt sein sollten, wirst aber doch wohl nicht ernsthaft behaupten, das jeder Mapper auch ein Programmierer ist, oder?
Mal davon abgesehen das es aufgrund der unzähligen Downloadseiten unmöglich ist, ohne Versionszahl im Namen zu erkennen, welche Version der Map man da vor sich hat, sehe ich nicht das Problem wieso die Leute die config nicht finden sollten. Denn es gibt pro savegame immer nur eine Map und auch nur eine Config. Und wer clever genug ist, die Map im Savegame zu tauschen, der wird auch noch die Config dazu tauschen können...

nochmal... eine Antwort ala: "den Namen der Map im Namen der config weg zu lassen, geht programmiertechnisch nicht, weil dazu der gesamte Mod umgeschrieben werden müsste" von jemandem der tatsächlich etwas von der Materie versteht, wäre hier definitiv besser als "das ist nicht unser Problem, beschwere dich bei den unfähigen Mappern".

**Comment by Iwan1803** [comment]
Leg mir nicht Worte in den Mund, die ich nicht gesagt habe und hör bitte auf, Aussagen zu verdrehen.
Ich bin nur verantwortlich für das, was ich schreibe - nicht für das, was und wie andere es verstehen oder auffassen. Das geschriebene Wort lässt halt immer sehr viel Spielraum für Interpretationen.
"Konstruktives Feedback" sieht aber definitiv anders aus, denn ohne Beispiele fehlt mir da irgendwas, um es auch "greifen" zu können.
Und komm mir bitte nicht mit "ich weiß wovon ich rede, weil ich habe mal im Support gearbeitet", denn da kann ich über 20 Jahre IT-Supporterfahrung gegenhalten. Man wird sich nie mit allen Menschen "grün" sein, aber muss man auch nicht, denn das Ergebnis zählt am Ende.

Deine Aussage bzgl. der Version und der diversen Downloadseiten kann ich nicht ganz nachvollziehen, zumal dies ja auch nichts mit dem Problem der Versionsinfo in der _title_-Variable innerhalb der _maps_-Tags zu tun hat.
Ich erwarte nicht, das jeder Modder oder Mapper auch Programmiererfahrung hat, aber jeder sollte sich vorher informieren, was man wie und wo machen oder einstellen muss und nicht einfach drauf los frickeln (übertrieben ausgedrückt). Das Ergebnis sind dann z.Bsp. Infos in Variablen, wo sie nicht hingehören oder halt fehlerhafte Mods, auch wenn diese nicht sofort offensichtlich sind. Hier müssen die Ersteller halt informiert werden, damit sie nachbessern können.
Ich behaupte nirgends, das die Mapper unfähig sind, denn sonst wären die Maps nicht so gut wie sind, aber es gibt halt Sachen, die man besser machen kann und dazu gehört auch der Maptitle, welcher halt keine Version mitführen sollte. 

Den Grund für den Dateinamen & Co. habe ich in meinem ersten und zweiten Post bereits ausreichend erklärt. Warum du diese Aussage in jedem Beitrag verdrehst oder ignorierst... naja, mir egal.

Das Thema ist damit für mich erledigt, weil es keinen Sinn macht mit jemanden zu diskutieren, wenn Worte und Aussagen verfälscht werden, um jemanden schlecht dastehen zu lassen.

**Comment by Mike1977** [comment]
Deine gekränkte Eitelkeit und dein Stolz lassen es einfach nicht zu, das du dich auf das Problem konzentrierst. 
Du drehst dich hier im Kreis. Du wirst es nicht schaffen das die Mapper sich alle an Deinen Standart halten, und das ist auch nicht deine Aufgabe. Hier geht es darum, diesen Mod nutzerfreundlicher zu machen, mit einer kleinen Änderung die in nichtmal 10 Sekunden gemacht ist. 
Die Config ist im Savegame gespeichert. Das heist, daß diese Config zu diesem Savegame gehört und eben zu der Map die man in dem Savegema spielt. Wieso sollte man diese Config jetzt nicht mehr finden, wenn man sie sucht? 

All deine Argumente gehen völlig am Thema vorbei und deshalb entsteht beim Leser der Eindruck als wärst du hier nur so eine art Türsteher, der völlig untransparent entscheidet welche Themen "rein" dürfen und welche nicht.

Du hast dich hier groß und breit über alles ausgelassen außer dem eigentlichen Thema. Deine einzige halbherzige "Begründung" warum das nicht geht, war: Weil andere User die Config dann nicht finden. Das war schon alles. Aber wieso das so sein soll, das erklärst du nicht, denn dann würdest du sehen das das Quatsch ist.

**Comment by Iwan1803** [comment]
Ich drehe mich nicht im Kreis, bin voll fokussiert und du verstehst einfach nicht die Tragweite:
AD-Anpassung = alle AD-User sind davon betroffen, denn nun wird nach einer Configdatei mit neuem Namen gesucht, welche aber nicht da ist
Anpassung Maptitle von ein paar wenigen Mappern = ein kleiner Bruchteil aller AD-User ist betroffen, welche aber in Releasenotes informiert werden könnten, aber das Problem und vor allem die Ursache wäre auf Dauer verschwunden
Daher die Frage: warum sollen wir die Fehler anderer ausbügeln?
Würden wir diese Änderung machen, wäre das dann "nutzerfreundlich"? Wohl eher nicht...
Und das ist nicht mein Standard, sondern ein allgemeiner und eine korrekte Code-Änderung dauert deutlich länger als 10 Sekunden, denn der Code wird hier nicht mit der heißen Nadel gestrickt und einfach bereitgestellt sondern auch entsprechend getestet.

Ich weiß nicht, wo dein Problem genau liegt, aber Aussagen zu verdrehen und nicht zu verstehen oder sogar zu ignorieren scheint deine große Leidenschaft zu sein.

Thema erledigt.

**Comment by Mike1977** [comment]
Ich vertshe nicht die Tragweite? Ich glaube du hast einfach keine Ahnung wovon du da redest. 
Bisher besteht das Problem das man bei einem Mapwechsel auch den Namen der Config ändern muss. Eine kleine Änderung im Code würde die alte Config laden und unter neuem Namen, eben ohne den Mapnamen im Titel, wieder speichern. Das gibt weder ein Problem für irgendjemanden, noch ist es umständlich zu implementieren. Wahrscheinlich währe diese kleine Änderung schneller gemacht, als es dauert diesen ganzen Krampf hier zu lesen.
Der Mapname im Titel ist ein altes Relikt aus einer früheren Version, als die Config Dateien noch alle zusammen in einem Ordner geliefert wurden. Da das jetzt nicht mehr der Fall ist, ist der MapName im Titel Obsolet. Diese Kleine Änderung fällt unter QoL und ich verstehe einfach nicht, wieso du dich hier so wehement dagegen wehrst. Bzw habe ich schon so ne Ahnung warum, aber das habe ich bereits im zweiten Satz geschrieben.

Vielleicht kann irgendwann mal Stephan oder jemand anderes antworten, der Kompetent statt ignorant ist.

**Comment by Iwan1803** [comment]
Sorry, aber ich wehre mich nicht gegen Änderungen und deine Anfeindungen mir gegenüber sind nicht hilfreich, zumal du vollkommen ignorierst, was ich schreibe und meine Aussagen weiter verdrehst.  
Daher habe ich den ganzen Post gelöscht, denn es waren nur 2 Sätze enthalten, die es wert waren, erhalten zu bleiben:
> Bisher besteht das Problem das man bei einem Mapwechsel auch den Namen der Config ändern muss. Eine kleine Änderung im Code würde die alte Config laden und unter neuem Namen, eben ohne den Mapnamen im Titel, wieder speichern.

Wir haben also einen Ansatz, auf dem man aufbauen könnte, auch wenn er noch nicht bis zu Ende gedacht ist.
Beim Laden eines neuen Savegames müsste geprüft werden, ob eine AutoDriveConfig.xml vorhanden ist:
+ falls ja: Laden
+ falls nein: prüfen, ob eine alte Config _AutoDrive_*_config.xml_ vorhanden ist
 - falls vorhanden -> mit neuem Namen abspeichern
 - falls nicht: leere Config mit neuem Namen erstellen

Dennoch bin ich kein Freund davon, die Ursache nicht zu beheben sondern eine "Weiche" einzubauen, damit es zu keinen Problemen oder Fehlern führt.

@Axel32019 
Kannst du das mal prüfen? Dann bräuchten wir das Ersetzen von Sonderzeichen im Mapnamen nicht mehr und wären an der Stelle wieder sauber.

**Comment by Mike1977** [comment]
Du unterstellst mir ich würde dein Aussagen verdrehen, obwohl das nicht stimmt. Und wenn ich zu dem Schluss komme, das du keine Ahnung hast wovon hier überhaupt geredet wird, dann löschst du den Kommentar. Das zeigt wieviel Klasse du hast. Da kannst du stolz drauf sein.

> Dennoch bin ich kein Freund davon, die Ursache nicht zu beheben sondern eine "Weiche" einzubauen, damit es zu keinen Problemen oder Fehlern führt.

Wenn du keinen Einfluss auf die Ursache hast, und das hast du in diesem Falle eindeutig nicht, dann bist du als Entwickler gezwungen Geeignete Maßnahmen zu treffen um einen Negativen Einfluss auf dein Projekt zu vermeiden.
Das macht jeder Entwickler so, und das solltest du aufgrund deiner "20 Jahre IT-Supporterfahrung" eigentlich wissen.

Übrigens siehst du hier an dem Thread sehr deutlich warum ich deine Arbeit kritisiert habe. Anstatt nach einem Lösungsansatz zu fragen, hast du das ganze sofort als Unsinnig abgetan. Und ich habe die ganze Zeit versucht heraus zu finden wo genau dein Problem damit liegt, denn ich habe recht schnell erkannt, das du wohl nicht verstanden hast, worum es geht, bzw was das eigentliche Ziel ist.

Deshalb mag ich es eigentlich lieber mit dem Chef zu reden, anstatt mit dem Türsteher.

**Comment by Iwan1803** [comment]
Anstatt dich zu freuen, das es ggfs. erstmal doch zur Prüfung kommt und daher nun einfach die Finger von den Tasten zu lassen, wirfst du weiter mit Anschuldigungen und Beleidigungen um dich. Hast du sonst kein Leben oder im RL nichts zu melden, das du hier nun versuchst einen auf dicke Hose zu machen oder versuchst du einfach gerne den Lehrer oder Erzieher zu spielen?
Ich habe nirgendswo geschrieben, das es unsinnig ist oder das Mapper unfähig sind oder das es mein Standard ist oder oder oder, aber du unterstellst es mir hier laufend. Na, merkst du es selber oder soll ich dir Zitate von deinen Texten posten, wo du dir irgendwas zusammenreimst und mir unsinnigerweise haltlose Tatsachen vorwirfst?
Hast du vielleicht zu viel Pipi Langstrumpf gehört, denn die singt ja auch "Ich mach' mir die Welt, Widdewidde wie sie mir gefällt..."?

So, und nun kannst du gerne weiter behaupten, das ich unfreundlich und inkompetent wäre, aber bedenke:
ich habe dir nur Fragen gestellt (auch wenn es mich nicht interessiert) und keine Behauptungen aufgestellt, denn sowas mache ich nicht 🤪


PS: wir machen das hier alle ohne Bezahlung in unserer Freizeit und dein Verhalten ist einfach nur respektlos.

**Comment by Axel32019** [comment]
@F-Patsch @Mike1977 See here / Wenn Interesse hier entlang: #1663

**Comment by F-Patsch** [comment]
@Axel32019 , klingt super, freue mich auf die nächste Version. Bis diese von Euch freigegeben wird werde ich mit der bisherigen weiterarbeiten. Vielen Dank für die tolle Arbeit an das komplette AD-Team

**Comment by Anonymous-any** [comment]
Hi @Mike1977 because I was not really understand what was really concerned only after observed the result as now.
I was think the request was about inside the file (mapname somewhere)...and I did not want talk in this thread.
To my opinion because it is so idiot to do this to have a standard savename is less good than the original code.
Because I use it as long but pretty sure lots peoples that have been make his AD reputation I think too, import export function can solve AD save file, too I save all my routes files inside the same like  AD save folder in my computer (save games)...

- If you use AD from old version like FS17 (as example) import export like this one (route manager) can backup your routes. Of course it has now a generated name file inside the manager but it's good, the same job can be do with load button. And because they are generated in a manager now I always rename like the same map name for backup them !!! but I do that with my all important docs of course same as conscientious peoples right ?

- To my view only an AD newbie or (user non load ADsavedFile) can talk a such a request like this or maybe a man who must leave his computer to back go in a console game. I mean if you tired or incriminate or a program or a developer to do every rename that you need into a computer then you have to think to STOP to use it @Mike1977. (it's one of a basic fundamental of informatics)...

- The save file go in the savegame dir/folder so where is the utility to have a standard name ??? I want to mean if it's already named you already know what map go with your saved file ! If not you can go overwrite by mistake a route file from another map route right ?

- By this request, you have to manually change the filename if you want to store all in same folder so what the real needed for have a standard name if the file stay alone inside the savegame dir ? (remember the GIANT engine delete all file before save all new...) so that have no cense for me.

- Dare to doubt about the comprehensive to a developer and be insolence by transforming these words Yes ! I can not ear that shit. @Mike1977 you had lots of other ways to do.

- Then finally, I vote for I REALLY HOPE this request never go in the master branch for the public...after been tried it to know what is about.

Regard

**Comment by Mike1977** [comment]
> 
> 
> @F-Patsch @Mike1977 See here / Wenn Interesse hier entlang: #1663

Das klingt sehr gut. Ebenso wie die anderen Vorschläge die umgesetzt wurden. Werde das mal testen und berichten, falls mir was negativen auffällt.

@Anonymous-any Since you mentioned my name, i kinda feel compelled to reply. But even though i'm actually rather fluid in english, i have no idea what you wanted to convey to us / me and so I hope @Axel32019 is able to substract any useful information out of your post.

**Comment by F-Patsch** [comment]
Da diese Feature Request in der neuesten Version umgesetzt wurde mache ich hier mal zu. Vielen Dank für das Aufgreifen und Umsetzen dieser Vereinfachung.
