### ISSUE TITLE
[Question]

### ISSUE THREAD

**Issue by Julian638** [Stephan-S/FS19_AutoDrive#1583]
Hi, Ich habe AutoDrive für die Nordfrisische Marsch installiert ich habe bloß immer das porblem das der Abfahrere nie den New Holland CR10.90 Revelation nie ablädt

**Comment by Iwan1803** [comment]
Und nun? Sollen wir in die Glaskugel schauen oder eine Hellseherin beauftragen?
Sorry, aber ein paar mehr Infos solltest du schon liefern, vor allem welche Einstellungen der Abfahrer hat.

**Comment by Axel32019** [comment]
No update -> Closed.
