### ISSUE TITLE
[Question] Wird Stroh auf dem Feld als Kollision erkannt ?

### ISSUE THREAD

**Issue by rmn18** [Stephan-S/FS19_AutoDrive#1584]
**Question:**   
I've got a question...
Moin zusammen 

Kurze Frage wie oben ,Wird Stroh auf dem Feld als Kollision erkannt und fliest bei der Berechnung des Kurses mit ein oder wird das ignoriert bei der Berechnung und Pfadfindung ?

**Comment by Iwan1803** [comment]
Da meine Strohsammler über das Stroh drüber fahren, wenn sie das Feld verlassen, wird es wohl nicht als Hindernis erkannt.
