### ISSUE TITLE
[BUG] Truck drives into harvester when going to empty him

### ISSUE THREAD

**Issue by DnbSTEb** [Stephan-S/FS19_AutoDrive#1585]
AutoDrive Version: 1.1.0.4
Release or selbsterstelltes zip: Release
Karte (falls relevant): NF Marsch 4fach
Fahrzeug(art) (falls relevant): Agco Ideal 9t mit New Holland 3162 Dripper 45FT, MAN TGS 18.500 4x4 mit Benalu Optiliner 133 ( Mod )

Wenn der LKW vor dem Mähdrescher in gleicher Fahrtrichtung steht, wendet dieser in einem Halbkreis um, um diesen anzufahren. Dabei fährt dieser den zweiten Wendekreis auf kürzesten Weg an wobei er dann aber mit dem Mähdrescher mit ihm kollidiert da dieser an Weg gut gemacht hat.

Auf dem sehr professionell erstelltem Bild nochmal nachgestellt was mein Problem ist. Der LKW steht dabei ca 400 bis 500 Meter entfernt auf dem selben Feld in selber Fahrtrichtung wie der Mähdrescher. Falls es programmierbar wäre, wäre eine Lösung den LKW in engeren Kreis wenden zu lassen und diesen dann auf gleicher Höhe wie er vorher stand Richtung Mähdrescher fahren zu lassen.

NACHTRAG: Habe das ganze nochmal nachgestellt und nun beobachtet, dass der LKW ganz bewusst sich eine Spur sucht die an der Kante von geerntet und noch zu ernten liegt. Videolink im Anhang.

![LS19 AD](https://user-images.githubusercontent.com/65016145/92308531-8268d100-ef9e-11ea-8ea0-9f10d5b9ebd6.png)

https://1drv.ms/v/s!ArzL0MoQB_0QhUoxY2Km3b2Zvd70

**Comment by Mannie313** [comment]
Mal bitte AD updaten.
du hast 1.1.0.4 
aktuell 1.1.0.5 RC5
MFG Mannie313

**Comment by DnbSTEb** [comment]
Hat bis jetzt keine Probleme mehr gegeben nach Update auf 1.1.05. 
Somit in meinem Fall erledigt Danke!!
MFG Pascal
