### ISSUE TITLE
Assign park destination to vehicle not working (anymore)

### ISSUE THREAD

**Issue by Dennizzzzz** [Stephan-S/FS19_AutoDrive#1586]
**AutoDrive Version:** 1.1.0.5-RC5
**Release or Custom Zip:** Release
**Map (If applicable):** All  
**Vehicle / Type (If applicable): All**   
**Multiplayer or Singleplayer:** Singleplayer  

**Describe the bug**  
Assigning a park destination (rightclick on P), does not work for vehicles.

Tried removing all mods (empty the mod folder), only added AD and started a new game on a vanilla map, and i cannot assign a parking destination to a vehicle. 

Tried resetting the inputbinding.xml. Also removed all RIGHT mouse click assignments from the inputbinding.xml. No luck...

When i attach a worktool (trailer of weight), it works fine. So it is not a mouseclick issue or something (my conclusion). 

I even changed the parkDestination in the vehicles.xml file to reflect the number of the destination point, but still in game, the park destination is not set.

In the past it was no issue with same version. Now only on savegames where I in the past assigned parking destinations it works.
Log.txt file is not telling me anything about this.

Yes... this is really strange.. I do not know what to do about this.

**Comment by Dennizzzzz** [comment]
Wow... I found the issue. If I set the game setting 'Automatically start engine' to On, and save the game, exit the game and load it again. I cannot set the parking destination of a tractor (without any worktools attached).
If I turn the setting OFF, save the game, and start it again, I CAN set the parking destination !!!

**Comment by Bobster82** [comment]
> **AutoDrive Version:** 1.1.0.5-RC5
> **Release or Custom Zip:** Release
> **Map (If applicable):** All
> **Vehicle / Type (If applicable): All**
> **Multiplayer or Singleplayer:** Singleplayer
> 
> **Describe the bug**
> Assigning a park destination (rightclick on P), does not work for vehicles.
> 
> Tried removing all mods (empty the mod folder), only added AD and started a new game on a vanilla map, and i cannot assign a parking destination to a vehicle.
> 
> Tried resetting the inputbinding.xml. Also removed all RIGHT mouse click assignments from the inputbinding.xml. No luck...
> 
> When i attach a worktool (trailer of weight), it works fine. So it is not a mouseclick issue or something (my conclusion).
> 
> I even changed the parkDestination in the vehicles.xml file to reflect the number of the destination point, but still in game, the park destination is not set.
> 
> In the past it was no issue with same version. Now only on savegames where I in the past assigned parking destinations it works.
> Log.txt file is not telling me anything about this.
> 
> Yes... this is really strange.. I do not know what to do about this.

This is known with the developers... They made the parkfunction for active selection. So u need to attach a trailer or whatever and assign a park spot... every trailer/tool has his own park spot.
The problem why u cant assign a park spot to a tractor/truck is that u cant select it (active selection) with 'q' (the switch between trailers/tools)
I hope this clarifies it for u

**Comment by Dennizzzzz** [comment]
Sorry Bobster, but you CAN assign a parking destination to a tractor without any tool. 
I can assign a parking destination to a tractor only (see my previous comment). 
If you also look in the vehicles.xml file, there is a xml-tag parkDestination if the autodrive element for every tractor (vehicle).

If you have a tool/trailer attached, you assign a destination to a tool, in the vehicles.xml there is a WorkToolParkDestination set to the worktool.

The problem is that for some reason you cannot assign a park dest to a tractor if you have the game setting 'automatically turn on engine' set to on...

**Comment by Bobster82** [comment]
> Sorry @Bobster82, but you CAN assign a parking destination to a tractor without any tool or trailer attached.
> 
> I can assign a parking destination to a tractor only (see my previous comment).
> If you also look in the vehicles.xml file, there is a xml-tag parkDestination if the autodrive element for every tractor (vehicle).
> 
> If you have a tool/trailer attached, you assign a destination to a tool, in the vehicles.xml there is a WorkToolParkDestination set to the worktool.
> 
> The problem is that for some reason you cannot assign a park dest to a tractor if you have the game setting 'automatically turn on engine' set to on...

Maybe if ur starting ur savegame with a started  vehicle, the vehicle is "selected" ? But i know it was asked a while back and they gave me this answer

**Comment by Dennizzzzz** [comment]
@Bobster82 

I did assign parking destinations over and over again playing FS19 in the last months when using AutoDrive. I always had the game setting 'Automatically Start Engine' set to OFF. So I needed to manually start the engine of every vehicle. But a few days ago I did set this setting to ON. And after a while playing, I noticed that I could not assign a parking dest to a tractor anymore.

So I tried everything to make it work again, removed all mods (only AD), vanilla maps etc. etc. etc. and finally after a few hours I found the solution.

Just try it. Turn the game setting OFF, save your game, quit your game, quit FS19, start it again, load the game, and assign a park destination to a tractor...

**Comment by Dennizzzzz** [comment]
![2020-09-07 22_42_58-Window](https://user-images.githubusercontent.com/10248136/92416040-e1c01000-f15b-11ea-8090-e00f3faa28fb.jpg)
![2020-09-07 22_44_44-Farming Simulator 19](https://user-images.githubusercontent.com/10248136/92416043-e4bb0080-f15b-11ea-803f-98de8c1499c0.jpg)

**Comment by Bobster82** [comment]
I just tested this and yes that works. @Dennizzzzz , nice catch!

So its a giants bug with the automatic start function, vehicles cant be selected (icon not active). If u need to manually start the vehicle, the vehicle icon is active.

Thanks again for sharing

**Comment by Dennizzzzz** [comment]
> 
> 
> I just tested this and yes that works. @Dennizzzzz , nice catch!
> 
> So its a giants bug with the automatic start function, vehicles cant be selected (icon not active). If u need to manually start the vehicle, the vehicle icon is active.
> 
> Thanks again for sharing

Aha, now I see it too, the active icon I mean. So for some reason if you manually start the engine, the tractor gets 'active' !

**Comment by Dennizzzzz** [comment]
@Bobster82 What I do now, is before saving and exiting the game, i set the 'start engine' to off. 
And when I play the game again, set the 'start engine' to on. And I can assign a parking destination the whole time...

**Comment by JustDen1234** [comment]
I think this ticket can be closed. There seems to be an issue with the basegame that makes it impossible btonfix this.

Parking vehicles only work when option 'auto start' is turned off.

Or am I wrong and can it be fixed?

**Comment by Axel32019** [comment]
This is fixed in 1.1.0.5-RC6
