### ISSUE TITLE
Autodrive 

### ISSUE THREAD

**Issue by Zappy75** [Stephan-S/FS19_AutoDrive#1587]
Guten Abend ich habe auf der Halle Tornau Autodrive Kurse eingefahren, lief alles super. Dann habe ich abgespeichert. Nun wollte ich das Savegame wieder starten aber es lädt nicht fertig. Nehme ich Autodrive raus lädt es fertig und ich kann spielen. Ich nutze die aktuelle Version von dieser Seite. Woran könnte es liegen? MfG

**Comment by Axel32019** [comment]
Hallo,
Bitte mal die Datei AutoDrive_..._config.xml in ein zip packen und hier anhängen.

**Comment by Zappy75** [comment]
Hallo, im Anhang ist die gewünschte Datei

________________________________
Von: Axel32019 <notifications@github.com>
Gesendet: Montag, 7. September 2020 16:35
An: Stephan-S/FS19_AutoDrive <FS19_AutoDrive@noreply.github.com>
Cc: Zappy75 <dirkz1975@live.de>; Author <author@noreply.github.com>
Betreff: Re: [Stephan-S/FS19_AutoDrive] Autodrive (#1587)


Hallo,
Bitte mal die Datei AutoDrive_..._config.xml in ein zip packen und hier anhängen.

**Comment by Axel32019** [comment]
Hallo @Zappy75 , So funktioniert das leider nicht. Bitte mit Drag&Drop hier einfügen!

**Comment by Axel32019** [comment]
No update -> Closed.
