### ISSUE TITLE
[BUG] Reopening issue "Several drivers on one tractor #1464"

### ISSUE THREAD

**Issue by Gonimy-Vetrom** [Stephan-S/FS19_AutoDrive#1588]
Please reopen this thread as the problem is not resolved. 
https://github.com/Stephan-S/FS19_AutoDrive/issues/1464

**Comment by Axel32019** [comment]
Are you using the same setup or did something changed?

**Comment by Gonimy-Vetrom** [comment]
What do you have in mind?

**Comment by Axel32019** [comment]
Are you still using the same version of FS19_HelperAdvanced?

**Comment by Gonimy-Vetrom** [comment]
yes. Otherwise, I would not have seen this problem.

**Comment by Axel32019** [comment]
From AD side all possible was done. Are you using AD Version RC5?
Did you raised the issue also to FS19_HelperAdvanced?

**Comment by Gonimy-Vetrom** [comment]
1. Yes
2. Yes https://github.com/BlackyBPG/FS19_HelperAdvanced/issues/2

**Comment by Gonimy-Vetrom** [comment]
```
		if self.cp ~= nil and self.cp.isDriving ~= nil and self.cp.isDriving == true then
			helper.lastVehicleAiStarted = false
			self.courseplayDrive = true
			self.followMeDrive = false
			self.autoDriveDrive = false
		elseif self.spec_followMe ~= nil and self.spec_aiVehicle.mod_ForcedDrivingStrategyName == "FollowMe" then
			helper.lastVehicleAiStarted = false
			self.courseplayDrive = false
			self.followMeDrive = true
			self.autoDriveDrive = false
		elseif self.ad ~= nil and self.ad.isActive then
			helper.lastVehicleAiStarted = false
			self.courseplayDrive = false
			self.followMeDrive = false
			**self.autoDriveDrive = true**
		else
			**helper.lastVehicleAiStarted = true**
			self.courseplayDrive = false
			self.followMeDrive = false
			self.autoDriveDrive = false
		end
```
If helper.lastVehicleAiStarted after AD then this problem/message appears.
```
		if g_helperManager.indexToHelper[index].lastVehicleAiStarted == false then
			textAddition = " (MOD)"
```
I wish I could understand all this, but I don't understand it yet :(

**Comment by Axel32019** [comment]
Do you mean you see "(MOD)" if AD active instead of "(AD)"?

**Comment by Gonimy-Vetrom** [comment]
Not certainly in that way.
I hire an employee - he becomes AD - the employee is stuck - a new employee of AD has been hired (if I this is not stopped, all employees can "sit" in this tractor as AD :)) - I personally come and fire an employee of AD, but only the last one leaves, the rest go into the state MOD and they can no longer be used (only restart the game).

**Comment by Gonimy-Vetrom** [comment]
FM and CP have a third parameter, but AD does not. Maybe he is missing?
```
self.cp ~= nil and self.cp.isDriving ~= nil and self.cp.isDriving == true

self.spec_followMe ~= nil and self.spec_aiVehicle.mod_ForcedDrivingStrategyName == "FollowMe"

self.ad ~= nil and self.ad.isActive
```

**Comment by Axel32019** [comment]
Thanks for the investigation, but it is not related to a third parameter - this is how you have to program in LUA:
Step by step check if you not have "nil" until you reach the real value you want.
Means CP and FM also check only 1 value, the last in the line of code.

**Comment by Justice-Molton** [comment]
Is it working now working?

**Comment by Gonimy-Vetrom** [comment]
The problem in 1.1.1.2 remained.
