### ISSUE TITLE
[BUG] LS19 stürzt ab beim Starten eines Fahrzeugkurses mit Rückwärtsfahrt

### ISSUE THREAD

**Issue by ark471** [Stephan-S/FS19_AutoDrive#1589]
AutoDrive Version: 1.1.0.5-RC5
Release or selbsterstelltes zip: Release
Karte (falls relevant): Alle
Fahrzeug(art) (falls relevant): Alle

**Beschreibe den Bug**
Beim Starten eines Fahrzeuges mit einem Kurs, der eine Rückwärtsfahrstrecke mit anschließender dunkelblauer Linie zum Zielpunkt enthält und an der noch KEINE grüne Fanglinie zur Vorwärtsfahrt angeschlossen ist, stürzt der LS19 ab.

**Falls anwendbar - Schritte mit denen ich den Bug nachstellen kann**
---> Iwan1803 hat so seine Silo's auf der NF Marsch neu eingefahren nach einem Tipp vom Xerox auf Discord.

Grüße

Ark

**Comment by Iwan1803** [comment]
Hast du die Kurse exakt so wie ich eingefahren? Benutzt du Mod-Fahrzeuge oder -Anhänger?
Ich glaube nicht, das es an der Methode selber liegt, das LS19 abstürzt.

**Comment by ark471** [comment]
Ich hatte mir Rückfahr-Parkkurse eingefahren und bei einem Parkplatz die grüne Vorwärtslinie zum wieder raus fahren vergessen. Als ich dann diesen Parkplatz anfahren wollte, ist der LS abgestürzt. Mit Hinzufügen der grünen Linie war dann alles in Ordnung.
Ich denke, dass das so nun nicht richtig ist, wenn diese grüne Linie vergessen wird, dass der LS abstürzt.
Kannst du ganz einfach nachstellen, indem du eine grüne Ausfahrlinie von der dunkelblauen Linie, die zum Zielpunkt führt,  abtrennst. Dann den Zielpunkt auswählen und das Fahrzeug losschicken.
Am Besten vorher Speichern, wie du ja weißt 😊.

Gruß

Ark

**Comment by Iwan1803** [comment]
Nur zum Verständnis:
- das Fahrzeug fährt über die hellblaue auf die blaue Linie (rückwärts) und lädt ab
- wenn er vorwärts fahren möchte und keine Verbindung zu einer grünen Linie besteht, schmiert LS ab
Soweit korrekt?

**Comment by ark471** [comment]
Genau so!

**Comment by Iwan1803** [comment]
Eigentlich werden die Strecken ja nicht gem. ihren eigentlich Bestimmungen genutzt, denn eigentlich sollen die dunkelblauen Linien ja nur vorwärts befahren werden 😉
Daher würde ich es eigentlich nicht Bug ansehen und das Issue eigentlich schließen wollen, wenn du einverstanden bist.

PS: als ich die grüne Abfahrlinie vergessen hatte, ist mein Spiel zumindest nicht abgestürzt sondern der Fahrer konnte das Ziel erst gar nicht anfahren.

**Comment by ark471** [comment]
Tja, was soll ich sagen...
Ich habe es noch einmal mit meinem Testspielstand auf der Felsbrunn ohne Mods, nur mit Autodrive nachgestellt.
Habe mir eine kurze Strecke eingefahren so wie oben beschrieben und das Fahrzeug fährt ohne Probleme zum Ziel.
Da wird wohl mit meinem Spielstand, bei dem das Problem auftrat, etwas nicht stimmen.
Ich denke mal, das wir das hier schließen können.

Gruß

Ark

**Comment by Iwan1803** [comment]
Alles klar. Falls du Hilfe brauchst, dann meld dich einfach mal auf Discord.
