### ISSUE TITLE
Autodrive kippt im Multipayer nicht ab

### ISSUE THREAD

**Issue by RudiBergfeld** [Stephan-S/FS19_AutoDrive#1590]
AutoDrive Version: 1.1.05RCS
Release or selbsterstelltes zip: Release
Karte (falls relevant):NF Marsch 4 Fach Version 2.2
Fahrzeug(art) Alle
Sobald eine 2 Person den Server betrit kippt AD am Trigger nicht ab, was mache ich Falsch.

**Falls anwendbar - Schritte mit denen ich den Bug nachstellen kann**

**Screenshots**
Falls relevant, bitte Screenshots beifügen

**Comment by DiTechRacer** [comment]
Hab das gleiche Problem..

**Comment by CreepPhil** [comment]
Ich habe das Problem auf der Karte auch und spiele auf einem gemieteten Server, da funktioniert es auch nicht, wenn nur eine Person auf dem Server ist. :(

**Comment by Mannie313** [comment]
schaut mal bei #1555 nach.

MFG Mannie313

**Comment by Axel32019** [comment]
Duplicate of #1555
