### ISSUE TITLE
[BUG] The MAN TGS 18.500 4x4 cannot find its way to unload.

### ISSUE THREAD

**Issue by SirAdams** [Stephan-S/FS19_AutoDrive#1592]
**AutoDrive Version:** 1.1.0.5RC   
**Release or Custom Zip:** ReleaseC  
**Map (If applicable):** Ravenport  
**Vehicle / Type (If applicable):MAN TGS 18.500 4x4
**Multiplayer or Singleplayer:** Singleplayer  

**Describe the bug**  
When I use this vehicle for unloading during contract work, the vehicle, after being parked in the crop, in this case sugar beet, cannot find its way to the combine, in this case the Gimme Variton 470 terra-trac. However, when I use my tractor for unloading, it finds its way to unloading without any problems.
Changing the "avoid crops" option does not help.
[log.txt](https://github.com/Stephan-S/FS19_AutoDrive/files/5200952/log.txt)

**If applicable - Steps to reproduce the behavior**  
In order to reproduce the problem, contract work with beet cultivation and a MAN vehicle to be unloaded must be undertaken.
I'm at the beginning of the game so I can't say if this problem will occur with my own vehicles

**Comment by Iwan1803** [comment]
If it works with with a tractor and not with the MAN, then check the AD settings for both. Maybe there is something different.

**Comment by Axel32019** [comment]
@SirAdams Could you please try with version 1.1.0.5-RC6.

**Comment by Iwan1803** [comment]
Da 1.1.0.6 released wurde, mach ich hier mal zu // As 1.1.0.6 was released, i'll close here 😎
