### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by RudiBergfeld** [Stephan-S/FS19_AutoDrive#1594]
AutoDrive Version: 1.106RCS
Release or selbsterstelltes zip: Release
Karte (falls relevant): Alle
Fahrzeug(art) (falls relevant):

**Beschreibe den Bug**
Wenn ich AD nutze im modus Abholen und abliefern habe ich nach einiger zeit fognes problem es kommt folgenes Fenster 

und das Spiel lässt sich nur noch über den Tasgmanager beenden

**Falls anwendbar - Schritte mit denen ich den Bug nachstellen kann**

**Screenshots**
Falls relevant, bitte Screenshots beifügen

**Comment by Iwan1803** [comment]
Doppelt gemeldet -> https://github.com/Stephan-S/FS19_AutoDrive/issues/1595
