### ISSUE TITLE
[BUG] Fruchtauswahlfenster bei Abholen&Abliefern

### ISSUE THREAD

**Issue by RudiBergfeld** [Stephan-S/FS19_AutoDrive#1595]
AutoDrive Version: 1.106RCS
Release or selbsterstelltes zip: Release
Karte (falls relevant): Alle
Fahrzeug(art) (falls relevant):

**Beschreibe den Bug**
Wenn ich AD nutze im modus Abholen und abliefern habe ich nach einiger zeit fognes problem es kommt folgenes Fenster 
Wahle aus was ins Farzeug geladen werden soll

und das Spiel lässt sich nur noch über den Tasgmanager beenden
leider kann ich keine Bilder und keine Log einfügen 

**Falls anwendbar - Schritte mit denen ich den Bug nachstellen kann**

**Screenshots**
Falls relevant, bitte Screenshots beifügen

**Comment by RudiBergfeld** [comment]
ich habe das noch mal getestet der bug ist in AD denke ich

**Comment by Mannie313** [comment]
Spielt ihr mit Cp wen ja kann es auf davon kommen.

MFG Mannie313

**Comment by Iwan1803** [comment]
In Discord hatte das Problem auch jemand und hat es damit gelöst, GlobalCompany in Version 1.6 zu nutzen.
Leider verrätst du uns ja nicht, auf welcher Map oder an welchen Gebäude/Trigger das Problem auftritt.

**Comment by Mannie313** [comment]
Das passiert nicht nur bei GC mods sondern auch bei den Originaltriggern. 

und ich hab die GC Version 1.7.1.0

MFG Mannie313

**Comment by RudiBergfeld** [comment]
ich Spiele auf der NF Marsch 4 Fach og version 2,2 das problem titt bei allen Abholtiggern auf egal wo. Kann mir einer sagen wo ich die orginal Version von 1.6.0 bekomme von Gobal Compenie

**Comment by Iwan1803** [comment]
Auf github bekommt man auch die älteren Versionen:
https://github.com/Ls-Modcompany/FS19_GlobalCompany/tree/master/_versions/1.6.0.1

**Comment by Mannie313** [comment]
@Iwan1803 ich spiele GC Version 1.7.1.0 und AD Version 1.1.0.5 RC6 und CP Version 6.02.00048 und habe seit 3 stunden keinen fehler.

MFG Mannie313

**Comment by Maigus-r** [comment]
Hi,
das im Discord neulich war ich. 
Seit gestern ist das Problem allerdings wieder da - auch mit GC 1.6.0.
Ich hatte damals wild AD, CP und GC Versionen durchprobiert bis es letztendlich funktioniert hat. Eventuell hat das irgendwelche Randbedingungen so verändert das es wieder eine Zeit lang funktioniert hat bei mir. 

Rein subjektiver Eindruck:
- Das Problem scheint durch Autodrive zu kommen denn ich konnte das Phänomen bisher sowohl beim Auffüllen von Sämaschinen als auch beim reinen "Abholen und Abladen" von einem Produkt von A nach B beobachten (ohne CP aktiv).
- Es scheint (steinige mich nicht für die Vermutung) irgendwo einen "hängenden" Auffüllen-Befehl zu geben, da man das Fruchtauswahlfenster für Millisekunden schließen kann (man kann sogar das Fahrzeug per Tab wechseln wenn man schnell ist) und es dann wieder auftaucht
- Manchmal geht das Fruchtauswahlfenster auf, das Gerät wird tatsächlich beladen und man sieht den Fruchtbestand im Silo geringer werden. Sobald der Aufladevorgang abgeschlossen ist kann man das Fruchtauswahlfenster schließen. Beim nächsten Gerät das allerdings irgendwo aufgefüllt werden soll geht dann gar nichts mehr und das Fenster geht nur noch auf, aufgefüllt wird allerdings nichts.
- Ich habe das Problem jetzt in einem Spielstand in dem ich es innerhalb weniger Minuten reproduzieren kann. Gibt es irgendeine erweiterte Logfunktion die ich aktivieren kann um bessere Infos zur Verfügung zu stellen?

**Comment by Axel32019** [comment]
@Maigus-r 
Bezug nehmend auf:
Ich habe das Problem jetzt in einem Spielstand in dem ich es innerhalb weniger Minuten reproduzieren kann. Gibt es irgendeine erweiterte Logfunktion die ich aktivieren kann um bessere Infos zur Verfügung zu stellen?
Wenn dem so ist, bitte mal ohne CP im Mod-Ordner probieren. Die Kollegen von CP überschreiben gerade die Ladefunktion, diese wird jedoch dann auch verwendet wenn CP nicht aktiv, jedoch als Mod vorhanden ist

**Comment by Maigus-r** [comment]
Das wird leider schwierig, da ich es (derzeit) nur reproduzieren kann wenn ich vom Courseplay säen zum Wiederauffüllen von Saatgut/Dünger fahre. Sobald ich das Problem wieder bei einem reinen Abholen & Abladen Fahrer habe werde ich es aber ausprobieren!

**Comment by Iwan1803** [comment]
Versuch es mal mit der aktuellsten Version von CP.
Das Issue 6084 zu diesem Thema wurde zumindest geschlossen und man kann in den Commits was von "fix loading/unloading" lesen.

**Comment by Axel32019** [comment]
@RudiBergfeld @Mannie313 @Maigus-r Tritt das immer noch auf?

**Comment by RudiBergfeld** [comment]
Das kann ich nicht sagen ich habe die Map gewechelt bei der Suedhemmern bis lang nicht

**Comment by Iwan1803** [comment]
Da 1.1.0.6 released wurde, mach ich hier mal zu // As 1.1.0.6 was released, i'll close here 😎
