### ISSUE TITLE
Abfahrer bleibt im Feld und blockiert Drescher 

### ISSUE THREAD

**Issue by prehnj112** [Stephan-S/FS19_AutoDrive#1596]
Wir haben ein Problem auf unserem Server. Immer wen das Rohr vom Drescher im Feld steht bleibt der Abfahrer im Bestand stehen und blockiert den Drescher dadurch. Kann man das anders einstellen oder muss man damit leben?
Zudem ist es bei uns so, wenn man den Häcksler selber fährt sagt der abfahrer immer nur warte auf umdrehen vom Drescher statt neben zu fahren.

Haben die neuste Beta iwas mit 0.5 RC.

Mit freundlichen Grüßen prehnj112.

**Comment by Iwan1803** [comment]
Hierzu gab es doch in Discord schon Hilfe:
> Fruchtumfahrung aktivieren wäre eine Maßnahme und eine andere, das der Drescher niemals so erntet, das sein Rohr zum Entladen in der Frucht hängt

> Parken im Feld deaktivieren

und dafür sorgen, das der Drescher nur so erntet, das das Rohr eben nicht zum Entladen über der Frucht hängt.
Der Drescher sollte also im Uhrzeigersinn ernten und wenn der Standardhelfer nichts taugt, solltet ihr euch mal CoursePlay oder AIVE anschauen.

**Comment by prehnj112** [comment]
CoursePlay macht auf dem Server leider Fehler.

**Comment by Iwan1803** [comment]
Dann versucht es mal mit AIVE: https://github.com/Mogli12/AIVehicleExtension

**Comment by Tensuko** [comment]
Also ich kenne jemanden, der CP .00064 und AD (RC5 oder sogar höher) sehr erfolgreich im MP einsetzt.

**Comment by Axel32019** [comment]
@Tensuko Würdest Du uns erleuchten?

**Comment by Tensuko** [comment]
@Axel32019 
Also erstmal ist die Aussage 'CoursePlay macht auf dem Server leider Fehler' ziemlich ungenau, von daher was soll ich dazu nun weiteres sagen ?
Welche Version wird denn da genutzt ? Welcher Fehler bei was ?

**Comment by Axel32019** [comment]
@Tensuko Meine Frage bezog sich auf Deinen Kommentar davor:
Also ich kenne jemanden, der CP .00064 und AD (RC5 oder sogar höher) sehr erfolgreich im MP einsetzt.

**Comment by andremeyer123** [comment]
>  CP .00064 und AD (RC5 oder sogar höher) sehr erfolgreich im MP

Was möchtest denn wissen @Axel32019  helfer nutzen wir nur cp  und abfahrer ad ohne probleme  
bei AIVehicleExtension kommt es auf die Felderform an war für unsere Karte nicht zugebrauchen ist (hat lauter Quatsch gemacht)

**Comment by andremeyer123** [comment]
![cp](https://cdn.discordapp.com/attachments/751365697996587063/7525116231383777/fsScreen_2020_09_07_14_42_54.png) 
Mp mit 2 Grubber z.b
wichtig wäre aber eine Log was für Fehler kommen 
 und wie @Iwan1803 schon schrieb den abfahrer erlauben durchs feld zufahren

**Comment by Axel32019** [comment]
Wollte aus Interesse wissen bei wem die Kombination gut läuft. Hilft ja vielleicht auch dem Themenstarter...
