### ISSUE TITLE
Abfahrer hängt bei "Zurücksetzen von Drescher"[BUG]

### ISSUE THREAD

**Issue by CmdrTiri** [Stephan-S/FS19_AutoDrive#1597]
**AutoDrive Version:** 1.1.0.4   
**Release or Custom Zip:** Release  
**Map (If applicable):** legend_usa  
**Vehicle / Type (If applicable):**  TGS 18.500 4x4 , Fendt 936 Vario 
**Multiplayer or Singleplayer:** Multiplayer  

**Describe the bug**  
Ich teste gerade für ein Multiplayer-Setup verschiedene Mods auf Nutzbarkeit auf einem gemieteten Dedi-Server von gamed.de
Wenn ich Ernte-Missionen fahre bleiben meine Abfahrer jedes mal im Modus "Zurücksetzen von Drescher" stehen, sobald der Drescher/Ernter fertig abgeladen hat. Der Abfahrtrigger (Abladen abe Level) hat keinen Einfluss.
Ist der Abfahrtrigger erreicht kann ich mit dem Button "Weiterfahren" die Abfahrt zum Entladepunkt starten, soll der Abfahrer weitere Ladungen aufnehmen, so muss AD neu aktiviert werden.
![fsScreen_2020_09_13_22_42_02](https://user-images.githubusercontent.com/70349981/93028374-e3824b80-f613-11ea-997c-0f0853a7ce04.png)
![fsScreen_2020_09_13_22_41_26](https://user-images.githubusercontent.com/70349981/93028871-3c071800-f617-11ea-927c-27e9766a3739.png)
![fsScreen_2020_09_13_22_42_02](https://user-images.githubusercontent.com/70349981/93028884-504b1500-f617-11ea-8243-fc0f9b2a8ec0.png)
![fsScreen_2020_09_13_22_41_38](https://user-images.githubusercontent.com/70349981/93028891-5c36d700-f617-11ea-8a8e-74ee13a9a580.png)
![fsScreen_2020_09_13_22_41_52](https://user-images.githubusercontent.com/70349981/93028912-6ce74d00-f617-11ea-9d8a-504d04331158.png)
![fsScreen_2020_09_13_22_42_21](https://user-images.githubusercontent.com/70349981/93028918-7a9cd280-f617-11ea-950e-044034afa398.png)

**If applicable - Steps to reproduce the behavior**  

**Screenshots**

**Comment by Iwan1803** [comment]
Sind das alles Vanilla-Fahrzeuge oder Mods? Zudem können REA und VCA zu seltsamen Verhalten führen.

**Comment by CmdrTiri** [comment]
VCA scheint auf jeden Fall etwas damit zu tun zu haben.
Habe das eben mal deaktiviert und schon laufen die Abfahrer!
REA hab ich nicht drauf, aber EV (Enhanced Vehicle) - das wäre mein zweiter Ansatzpunkt, den das konkurriert bei der Shuttle-Control mit VCA...
Werde ich auch noch ausprobieren!

**Comment by Iwan1803** [comment]
Das Vehice Control Addon von mogli muss mind. Version 0.1.2.5 sein, denn vorherige Versionen sorgen für massive Probleme. Außerdem sollte man das Helfer-Getriebe auf "allways" stellen, da sonst z.Bsp. die AD-Fahrer nicht rückwärts fahren können.

**Comment by CmdrTiri** [comment]
Version 0.1.2.5 ??
VCA aus dem LS19 Modhub ist doch bei 1.0.0.0 oder muss ich mir von Github noch was anderes organisieren?
Im Zweifelsfall bleibt VCA halt deaktiviert. Auf das Getriebe lässt sich im Notfall verzichten und für den Spur-Assistenten gibt es auch Alternativen.
Aber meinst Du das mit dem "Helfer-Getriebe" nicht vielleicht andersherum? Also dass man das deaktiviert, wenn man nicht selbst im Gerät ist? Weil das wäre ja die logischere Version, dass in dem Fall das Standardgetriebe genutzt wird...
