### ISSUE TITLE
Deutsch ?

### ISSUE THREAD

**Issue by Bandesss** [Stephan-S/FS19_AutoDrive#160]
Hallo Stephan vielen dank für das geile Programm.
Leider sehe ich den Text, wenn ein Fahrzeug angekommen ist nur noch auf Englisch.
Wie stelle ich das um ❔
Ist das so richtig ❔
<l10n filenamePrefix="translations/translation" />

2; Frage, wie kann ich die Help Tasten bei F1 ausschalten? 
3; Frage, was sind das für X auf dem Bild =✔
https://abload.de/img/20190529075405_1xrke3.jpg
Gruss Bandes

**Comment by andreasthu** [comment]
hallo Bandes
pkt.3 kann  ich dir beantworten:
das sind vereinzelte punkte, also solche die an kein netz angebunden sind.
 https://github.com/Stephan-S/FS19_AutoDrive/issues/150
lg
andreas

**Comment by Bandesss** [comment]
Hallo vielen dank, jetzt hoffe ich für die anderen sachen auch Antworten zu bekommen ;)

**Comment by Stephan-S** [comment]
Hey,
hast du eine offizielle Release Version (.zip) genutzt?
Bei mir wird hier alles auf Deutsch angezeigt, insofern das Spiel auf Deutsch steht.

Beste Grüße,
Stephan

**Comment by Bandesss** [comment]
Ja hatte das aktuelle ....

**Comment by Stephan-S** [comment]
Wenn das Problem weiterhin besteht, mach das Issue gerne wieder auf.
Ich habe es nur geschlossen, da ich gerade einen commit zu Punkt 2.) hochgeladen habe :-)

**Comment by Bandesss** [comment]
Hallo also Menu ist Deutsch, aber wenn die Fahrer ankommen.
Dort ist der kurze Text über die Meldung in Englisch.,...
Das meinte ich
