### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by CmdrTiri** [Stephan-S/FS19_AutoDrive#1600]
**AutoDrive Version:** 1.1.0.4   
**Release or Custom Zip:** Release  
**Map (If applicable):** legend_usa  
**Vehicle / Type (If applicable):**  TGS 18.500 4x4 , Fendt 936 Vario 
**Multiplayer or Singleplayer:** Multiplayer  

**Describe the bug**  
Ich teste gerade für ein Multiplayer-Setup verschiedene Mods auf Nutzbarkeit auf einem gemieteten Dedi-Server von gamed.de
Wenn ich Ernte-Missionen fahre bleiben meine Abfahrer jedes mal im Modus "Zurücksetzen von Drescher" stehen, sobald der Drescher/Ernter fertig abgeladen hat. Der Abfahrtrigger (Abladen abe Level) hat keinen Einfluss.
Ist der Abfahrtrigger erreicht kann ich mit dem Button "Weiterfahren" die Abfahrt zum Entladepunkt starten, soll der Abfahrer weitere Ladungen aufnehmen, so muss AD neu aktiviert werden.
Einstellungen:
![fsScreen_2020_09_13_22_42_02](https://user-images.githubusercontent.com/70349981/93028374-e3824b80-f613-11ea-997c-0f0853a7ce04.png)
Abfahrer wird beladen, Modus gerade auf "Zurücksetzen" umgesprungen:
![fsScreen_2020_09_13_22_41_26](https://user-images.githubusercontent.com/70349981/93028871-3c071800-f617-11ea-927c-27e9766a3739.png)
Modus Zurücksetzen, Drescher fährt ab:
![fsScreen_2020_09_13_22_41_38](https://user-images.githubusercontent.com/70349981/93028891-5c36d700-f617-11ea-8a8e-74ee13a9a580.png)
Drescher ist weg, immer noch Modus Zurücksetzen:
![fsScreen_2020_09_13_22_41_52](https://user-images.githubusercontent.com/70349981/93028912-6ce74d00-f617-11ea-9d8a-504d04331158.png)
nach Drücken von "Weiterfahren"
![fsScreen_2020_09_13_22_42_21](https://user-images.githubusercontent.com/70349981/93028918-7a9cd280-f617-11ea-950e-044034afa398.png)

**Comment by Iwan1803** [comment]
Doppelt gemeldet -> https://github.com/Stephan-S/FS19_AutoDrive/issues/1597
