### ISSUE TITLE
[BUG] Keine Kursaufzeichnung möglich

### ISSUE THREAD

**Issue by Confusedman74** [Stephan-S/FS19_AutoDrive#1601]
**AutoDrive Version:** 1.1.0.5 RC6 aktuell aus dem Beta-Branch   
**Release or Custom Zip:** Custom Zip 
**Map (If applicable):** All  
**Vehicle / Type (If applicable):**   
**Multiplayer or Singleplayer:** Multiplayer Dedi Server

**Describe the bug**  
Kann keine Kurse aufzeichnen, der Rec-Button ist ohne Funktion.
Kurse per "Hand" zeichnen, indem man die Wegpunkte malt, funktioniert, ist aber mühsehlig.

**If applicable - Steps to reproduce the behavior**  
Drücke Rec-Button, bleibt grau

**Screenshots**  

![image](https://user-images.githubusercontent.com/69455732/93130214-826d7d00-f6d2-11ea-8a29-b867075eae46.png)

**Comment by Iwan1803** [comment]
Das ist halt das Risiko, wenn man die Beta nutzt, welche dem AD-Team vorbehalten ist 😉
Geh bitte auf die aktuelle RC5 zurück, denn für die Beta gibt es kein Support.
