### ISSUE TITLE
Can the helper drive while unloading the Combine?

### ISSUE THREAD

**Issue by SeriouZ12** [Stephan-S/FS19_AutoDrive#1602]
Im playing around lately with multiple combines. The unloading should go with AD but the driver stops everytime the combine is full, then drives up, then stops until its empty. 

Can it drive besides the Combine while unloading?

**Comment by Iwan1803** [comment]
Are you driving the combine or CP, AIVE or something else?

**Comment by tuzlo** [comment]
I know for a fact if the combine is using CP and reaches 100% when the tractor unloads the combine it does not continue combining until empty

**Comment by Axel32019** [comment]
No update -> Closed.
