### ISSUE TITLE
[Question] CP + Autodrive + GlobalCompany Trigger bug

### ISSUE THREAD

**Issue by schwiti6190** [Stephan-S/FS19_AutoDrive#1603]
**Question:**   
I've got a question...
Hi there,
I've been working at courseplay recently and it seems there is bug with CP + Autodrive while refilling seeds and so on with autodrive and global company triggers(https://github.com/Courseplay/courseplay/issues/6027 or https://github.com/Courseplay/courseplay/issues/6018). Is there a way to check if autodrive is driving from the courseplay code. For example `vehicle.spec_autodrive:isDriving() or vehicle.spec_autodrive:isActive()` ?

sincerly 
David

**Comment by Axel32019** [comment]
Hi @schwiti6190 / David
I am not clear what you mean. If AD is active in control a vehicle the button 1 is active (white) https://github.com/Stephan-S/FS19_AutoDrive/wiki/Buttons-with-short-description
If leaving a field, status should show "leaving field", after that AD will also show the remaining driving time in the top HUD in SP.
Please let me know what you are looking for - I am currently still using CP 0039 and not clear from CP issues what is really the issue.
Regards Axel

**Comment by schwiti6190** [comment]
@Axel32019 It seems I didn't express myself correctly, I am currently one of the dev at courseplay and was the one responsible for the trigger rework that broken this with courseplay. I have directly overwritten code from g_company and giants to lose all the trigger raycast and so on. Now I need a way to check if autodrive is reaching the trigger or courseplay, as you guys don't need the new trigger code overwritten code.

David

**Comment by Axel32019** [comment]
Question first: English better or German?
In AD you may enable Debug pathfinding and trailer to see if AD is approaching a trigger, an indication is a slow speed before a trigger of ~ 5kmh.

**Comment by schwiti6190** [comment]
So wie erklär ich das am besten. Wie ich bereits gesagt habe, hab ich ich das Triggersystem von Courseplay überarbeitet. Courseplay simuliert jetzt ein knopfdruck, sagen wir mal er fährt in eine ladestelle rein und sobald giants code sagt ich kann den activierung Knopf "R" drücken, weiß courseplay bescheid und mach das gleich nur ohne das Auswahlmenü zb. Weizen oder Gerste etc. , das problem ist jetzt nur wenn Autodrive fährt klappt der overwritten code nicht zb.
 `LoadTrigger.onActivateObject = Utils.overwrittenFunction(LoadTrigger.onActivateObject,TriggerHandler.onActivateObject)`,
besonders problematisch scheint es mit global company trigger zusein, da diese nochmal ihren eigen code haben den ich seperate mit `TriggerHandler:onActivateObjectGlobalCompany(superFunc)` abändern musste. Die frage wäre wie wir das Triggersystem von euch mit dem von Courseplay auf einen Nenner bringen könnten.

Gruß David

**Comment by Axel32019** [comment]
Wir überschreiben die Funktion auch, siehe hier: https://github.com/Stephan-S/FS19_AutoDrive/blob/master/FS19_AutoDrive/scripts/Utils/UtilFuncs.lua -> AutoDrive:onActivateObject Kannst Du Dir ja mal ansehen...
Fehlt Dir da evtl. der Aufruf der superFunc?
Das Laden ist hier implementiert: https://github.com/Stephan-S/FS19_AutoDrive/blob/master/FS19_AutoDrive/scripts/Modules/TrailerModule.lua
In updateLoad gehts los, tryLoadingAtTrigger schaut ob der gewählte Fülltype gefunden / vorhanden ist, startLoadingAtTrigger hier wirds vielleicht auch für Dich interessant:
    trigger.autoStart = true
    trigger.selectedFillType = fillType
    trigger:onFillTypeSelection(fillType)
    trigger.selectedFillType = fillType
    g_effectManager:setFillType(trigger.effects, trigger.selectedFillType)
    trigger.autoStart = false
Bist Du schon bei uns im Discord? Dann können wir uns auch gerne direkt unterhalten...
Gruß Axel

**Comment by schwiti6190** [comment]
Komm morgen mal in den discord und könn vlt. mal schaun wie Cp und autodrive bis jetzt mit einander arbeiten. Evtl könn wa da ein zwei sachen anpassen.

gruß David
