### ISSUE TITLE
[BUG] Absturz bei Parkplatz Zuweisung - PC-Crash when assigning parking space

### ISSUE THREAD

**Issue by chroboss** [Stephan-S/FS19_AutoDrive#1604]
AutoDrive Version: 1.1.05.RCS
Release or selbsterstelltes zip: Release
Karte (falls relevant): LS19 Wild West 16x
Fahrzeug(art) (falls relevant): Alle

Hallo Stefan,

sobals ich einem Fahrzeug einen Pakplatz zuweisen möcht, stürzt das Spiel ab. Ich kannnur noch per Task-Manager das Spiel beenden.
Log-Fehler:
C:/Users/rudi/Documents/My Games/FarmingSimulator2019/mods/FS19_AutoDrive/scripts/Manager/GraphManager.lua:497: attempt to index local 'startNode' (a nil value)

LOG
[log.txt](https://github.com/Stephan-S/FS19_AutoDrive/files/5251695/log.txt)

**Screenshots**
Falls relevant, bitte Screenshots beifügen

**Comment by Iwan1803** [comment]
Ist es egal, welches Fahrzeug das ist oder passiert das nur bestimmten?
Gilt das für alle Zielpunkte oder vielleicht nur für bestimmte?

**Comment by Axel32019** [comment]
@chroboss Sollte mit 1.1.0.5-RC6 nicht mehr auftreten - bitte mal probieren und hier berichten.

**Comment by Iwan1803** [comment]
Da 1.1.0.6 released wurde, mach ich hier mal zu // As 1.1.0.6 was released, i'll close here 😎
