### ISSUE TITLE
[BUG] LS nicht nutzbar während AD Fahrt mit Anderson Hybrid X Xtractor

### ISSUE THREAD

**Issue by martin8522** [Stephan-S/FS19_AutoDrive#1605]
AutoDrive Version: 1.1.0.5
Release or selbsterstelltes zip: Release
Karte (falls relevant): Wild West
Fahrzeug(art) (falls relevant): Selbstfahrender (Eigener Motor und bewegung aber Anhängbar)

**Beschreibe den Bug**
Wenn ich meinen Traktor mit dem Angehängten Hybrid X Xtractor aus dem Anderson Pack auf die Reise schicke, ist der LS nicht mehr nutzbar. ICh kann aus dem Fahrzeug raus, aber mich dann nicht mehr bewegen, erst wenn AD die Route abgefahren hat, ist der LS wieder bedienbar.

Bei anderen Mods wie z.B dem Eigenbau Stationär Motor tritt dies aber nicht auf.

**Falls anwendbar - Schritte mit denen ich den Bug nachstellen kann**

**Screenshots**
Falls relevant, bitte Screenshots beifügen

**Comment by Iwan1803** [comment]
Ich musste erstmal schauen, was das überhaupt für ein Teil ist, weil ich das DLC nicht habe:
https://www.youtube.com/watch?v=3IbQWw0mvE0

@Axel32019 
Vielleicht kannst du dir das mal ansehen. Ich vermute ein Problem darin, das es angehangen als auch selber gefahren werden kann.

**Comment by Axel32019** [comment]
Hab dieses DLC auch nicht. Hab mal ein Förderband probiert, da kann man auch einsteigen und fahren - kein Problem.
