### ISSUE TITLE
Autodrive course lines turning black

### ISSUE THREAD

**Issue by fnpgeorge** [Stephan-S/FS19_AutoDrive#1606]
I just figured out that when using a 2000x time boost to go quickly through night time the autodrive course lines will be black when the sun comes up the next morning. Going to go through night time at a slower pace and see if this fixes it, otherwise does anyone know how to reset the lighting or shading of the autodrive course lines?

**Comment by Iwan1803** [comment]
Why did you not use a template when creating this issue? Now a lot of informations are missing...
AD-version, map, screenshots, logs, other infomations,....?

I did that several times and my lines had allways the correct color after a night.

**Comment by Axel32019** [comment]
No update -> Closed.
