### ISSUE TITLE
 Problem with augerWagon with multiple trailers

### ISSUE THREAD

**Issue by Playlord75** [Stephan-S/FS19_AutoDrive#1609]
Version 1.1.0.5 RC6 
Es gibt noch ein Problem bei denn abfahrern mit Überladewagen, sie fahren nicht weiter sobald der erste Anhänger voll ist. Ablaufen tut es so 
![fsScreen_2020_09_23_21_40_54](https://user-images.githubusercontent.com/71101944/94061840-37481e00-fde6-11ea-9e15-4b2254487521.png)
Der abfaher fährt sobald er voll ist zum Überladepunkt Und fährt das Rohr aus Silo Abstand auf 50m eingestellt Sobald er denn ersten Anhänger erreicht fängt er an zu Überladen 
![fsScreen_2020_09_23_21_41_02](https://user-images.githubusercontent.com/71101944/94061958-6068ae80-fde6-11ea-8a84-5003bcecb7a9.png)
Sobald der erste Anhänger voll ist macht er nichts mehr und wartet an der Position
![fsScreen_2020_09_23_21_41_37](https://user-images.githubusercontent.com/71101944/94062016-71b1bb00-fde6-11ea-9454-4adc975888da.png)
Wehre es möglich AD eine Einstellung zu geben das man auswählen kann wenn Silo voll ist oder wie bei mir jetzt Anhänger etc. voll ist er kurz warten soll und dann weiter fahren soll wenn der punkt nicht in Sagen wir mal 15 sec frei ist bzw. wieder etwas reingeladen werden kann weiter fahren soll bis er ganz normal das abladeziel erreicht hat

**Comment by rohne83** [comment]
Das ist ein sehr ähnlicher Fall wie bei dem Courseplay Issue https://github.com/Courseplay/courseplay/issues/6046
Dort hatte ich diese Wartezeit ebenfalls für den CP-ULW vorgeschlagen. Die Idee des DevTeams dort ist jetzt allerdings, dass nicht der ULW weiter fahren soll zum nächsten Trailer, sondern der Abfahrer vorrücken soll, bis auch der nächste Trailer voll ist - also das gleiche Verhalten zeigt wie an einem festen Silo. Beim Silo klappt das ja schon ohne Probleme. Wäre daher sehr hilfreich, wenn solch ein Feature auch in die AD Abfahrer eingebaut würde.
Überladewagen selbst lässt man ja meist am sinnvollsten sowieso von CP steuern, da eh nur auf dem Feld unterwegs, und dafür die Abfahrer aber vorrangig mit AD (Warten am Feldrand-Wegpunkt auf ULW und sobald voll über das Straßennetz zum Silo abladen). Wäre schon cool wenn man das auch bei mehreren Trailern weiterhin so handhaben könnte.
Weiterer Anwendungsfall, wo wirklich definitiv nicht der ULW sondern der Abfahrer vorrücken sollte, ist der Einsatz einer Mother Bin, wie bei https://github.com/Courseplay/courseplay/issues/5799
