### ISSUE TITLE
[Question]

### ISSUE THREAD

**Issue by Schmalhans68** [Stephan-S/FS19_AutoDrive#1610]
Ich habe eine Frage.
Kann es sein das Autodrive bei Aufträgen nicht funktioniert?
Karte NF Marsch 4fach oG V2.2 auf Dediserver (Nitrado)
Courseplay Und AutoDrive.
Fahre Drescher selbst und Abfahrer über Autodrive (1.1.0.5 RC6)
wenn ich den Abfahrer rufe (Rohr ausklappen) passsiert nichts
(Feld gehört mir nicht - Aufträge/Verträge aktiv)
Abfahrer fährt wenn er voll beladen ist den seine Strecke ab und kippt auch ab.

Übersetzung mit Google:

418/5000
I have a question.
Can it be that the Autodrive does not work with orders?
Map NF March 4-fold oG V2.2 on Dediserver (Nitrado)
Courseplay and AutoDrive.
Drive thresher and downhill drivers via Autodrive (1.1.0.5 RC6)
when I call the driver (unfold the pipe) nothing happens
(Field does not belong to me - orders / contracts active)
When he is fully loaded, the downer drives off his tracks and also tips over.

**Comment by Iwan1803** [comment]
Wenn du selber fährst, dann solltest du eine Tastenkombi zum Rufen des Abfahrers in den Einstellungen von LS belegen.

**Comment by Schmalhans68** [comment]
Hallo IWAN1803 ich hab das in einer deiner letzten Videos auf youtube
geshen und getestet jetzt funzt alles 

Danke für deine hilfe 

Am 2020-09-28 08:04, schrieb Iwan1803: 

> Wenn du selber fährst, dann solltest du eine Tastenkombi zum Rufen des Abfahrers in den Einstellungen von LS belegen. 
> 
> --
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub [1], or unsubscribe [2].

 

Links:
------
[1]
https://github.com/Stephan-S/FS19_AutoDrive/issues/1610#issuecomment-699791962
[2]

**Comment by Iwan1803** [comment]
Immer wieder gerne 😎
