### ISSUE TITLE
multiplayer friends report incompatible version Auto driver version 1.1.0.5-RC6

### ISSUE THREAD

**Issue by leo32128fs** [Stephan-S/FS19_AutoDrive#1611]
Auto Drive Version 1.1.0.5-RC6

when I enter the server, my friends report that the version they are using is not the same as mine, since I uploaded the same file I use, am I doing something wrong or could it be a bug in the new version?

**Comment by Iwan1803** [comment]
Giants update routines are stupid as they only compare the file name and the hash sum of it.
He should download the file from the server although it's the same version.

**Comment by leo32128fs** [comment]
OK thank you i will try this today

**Comment by Axel32019** [comment]
@leo32128fs Hello,
Do you still have an issue with this?

**Comment by Axel32019** [comment]
No update -> Closed.
