### ISSUE TITLE
[Question] Mouse and camera no compatible

### ISSUE THREAD

**Issue by Step72** [Stephan-S/FS19_AutoDrive#1613]
Hello
When displaying the mouse, why does the camera rotation no longer work?
Thank you

**Comment by Iwan1803** [comment]
This has always been the case and is nothing new.

**Comment by Step72** [comment]
Ok sorry I'm new to AutoDrive.
Is it possible to activate the camera when activating the mouse?

**Comment by Iwan1803** [comment]
No, sorry, maybe by keyboard shortcuts?

**Comment by Tensuko** [comment]
#6128

**Comment by Step72** [comment]
Ok thank you Tensuko

**Comment by Tensuko** [comment]
Just came along here and thought I make it a bit easier :)
