### ISSUE TITLE
[Question] Why is the RCTRL active in AD when there is now the RMB click for the editor mode without bubbles? Or, why does it switch off the bubbles without being in editor mode?-Warum ist die RCTRL in AD aktiv, wenn es doch jetzt den RMB-Klick für den Editormodus ohne Bubbles gibt? Oder, warum schaltet er ohne das man sich im Editormodus befindet, die Bubbles aus?

### ISSUE THREAD

**Issue by haamic** [Stephan-S/FS19_AutoDrive#1614]
**Question:**   
I've got a question 
Why is the RCTRL active in AD RC6 when there is now the RMB click for the editor mode without bubbles? Or, why does it switch off the bubbles without being in editor mode?
With RCTRL I switch the bubbles on or off, I do the same with LMB or RMB.
What makes sense ? It happened to me that I pressed RCTRL by mistake in the game without working in AD. So the bubbles were hidden now. I could never again enter the editor mode with LMB and bubbles. 
Try it, don't switch on the editor mode and press RCTRL. Now try to enter the editor mode with LMB -> nothing, only lines without bubbles.
+++++++++++++++++++++++++++++++++++++++++++++
Warum ist die RCTRL in AD RC6 aktiv, wenn es doch jetzt den RMB-Klick für den Editormodus ohne Bubbles gibt? Oder, warum schaltet er ohne das man sich im Editormodus befindet, die Bubbles aus?
Mit RCTRL schalte ich die "Bubbles" an oder aus, gleiches mache ich mit LMB oder RMB.
Welchen Sinn macht das ? Mir ist es nämlich passiert, das ich im Spiel mal versehentlich RCTRL gedrückt habe, ohne im AD zu arbeiten. Dadurch waren die Bubbles nun ausgeblendet. ich konnte nie mehr mit LMB den Editormodus mit bubbles aufrufen. Darauf muss man erstmal kommen.....
Probierts mal aus, schaltet keinen Editor modus an und drückt mal RCTRL. nun versucht mal mit LMB den Editor modus aufzurufen -> nichts, nur Linien ohne Bubbles.

**Comment by Axel32019** [comment]
@haamic Mit dem Ein- / Ausschalten wenn Editor nicht aktiv ist gebe ich Dir Recht - gefixt.
Die übrige Bedienung ist wie beschrieben: https://github.com/Stephan-S/FS19_AutoDrive/wiki/Edit-Mode
RMB ist nicht der Editor-Modus, sondern zeigt nur das Netz ohne Möglichkeit etwas zu ändern!
