### ISSUE TITLE
[BUG] Autodrive game hangs after writing and use Alt + F4

### ISSUE THREAD

**Issue by SirAdams** [Stephan-S/FS19_AutoDrive#1615]
**AutoDrive Version:** 1.1.0.5-RC6   and previus
**Release or Custom Zip:** Release  
**Map (If applicable):** All  
**Vehicle / Type (If applicable):**   
**Multiplayer or Singleplayer:** Singleplayer  

**Describe the bug**  
Enter using ESC, go to the save tab, then save the game and after the message about saving disappears use the ALT + F4 keys.
The game crashes so badly that it is not possible to switch to windows. The only way to close the game is to use ALT + L and then log in to a different user account and close the Taskmanager process.

**Comment by Anonymous-any** [comment]
Hi @SirAdams ,

It's one thing I think every mods users must set the console for avoid theses sort of issues, to simply look what happen sometime , or the game itself when it detect that it must load mods (but not in dreams).
Maybe you don't know or have it it seem for that you can:
open your game.xml in documents/FarmingSimulatorXXXX game folder
edit it with an text editor program and found the line to set it "true" not "false" like this`
        <console enable="true"/>`
do not load the game in same time modify this... !
² is the key button used for open it in game for me it's the one above the tab key...(all commands will be available only after your save game loaded).
Use it one time for show the log, 2 time to you enable active cursor for enter/write some text command. (There is auto-completion inside using tab and case sensitive), and/or a 3rd time for close it.
The Pageup and Pagedown key can scroll up'n down all your text console file.log.
For back to your story, use q command or quit (long word) and enter for simply quit your game immediately without save it. (the last save will be used next time you load unless you set gsAutoSaveInterval XX (in minutes) command and enable gsAutoSave, or via game interface.
I hope that you have all and I forgot nothing, for the rest you have to discover :)

Br

**Comment by Axel32019** [comment]
@SirAdams , @Anonymous-any Helllo,
Do you think Alt + F4 is really an issue only with AutoDrive?

**Comment by Anonymous-any** [comment]
@Axel32019 sure not, I just say him "THE" alternative for avoid it for a guy it seem he difficult situation with that to hang his computer, you certainly know what about he talk and already meet this sort of situation for u dev :) I'm pretty sure...
But his real subject is why he must do Alt+F4 no ? that why you say him to provide his log file.

Br

**Comment by Axel32019** [comment]
As mentioned - not an AD specific issue -> closed
