### ISSUE TITLE
I want to assign parkingplace only in editor mode[Question]

### ISSUE THREAD

**Issue by Bobster82** [Stephan-S/FS19_AutoDrive#1616]
**Question:**   
Can u guys adjust the code so that in editor mode i can assign a parking spot to a vehicle or tool and not in normal mode? 
As u assign parking spot with the right mouse button and u also use the right mouse button to activate the mouse... so it happens that the mouse (not visible yet) is in the hud area over the parking button when i want to activate the mouse and assigning a new parking spot....

I use it a lot and everytime finding out my vehicle has a different parking spot is a bit annoying ;)
Thanks in advance!

**Comment by Axel32019** [comment]
The default mouse button to activate the mouse in AD is the middle button.
To change the parking assignment would make the use more difficult to understand, which we always try to avoid.
Suggest you use the default button instead of right button.

**Comment by Bobster82** [comment]
I use courseplay too and that one uses right button too to activate the mouse. I use the RMB for years now. 
Is it that difficult to change if ur in editor mode or not? Cant that flag being added to the park function? If it is, I just need to live with it.
Thanks for ur reply @Axel32019

**Comment by Bobster82** [comment]
@Axel32019 , I used your testing script and its working great! many thanks.
Closing this now for me.

https://github.com/Stephan-S/FS19_AutoDrive/commit/b2c4765bebf8ea4217804a86883561b922938645
