### ISSUE TITLE
[BUG]Can´t move or delete waypoints in editor mode

### ISSUE THREAD

**Issue by TMac063** [Stephan-S/FS19_AutoDrive#1618]
AutoDrive Version: 1.1.0.5
Release or selbsterstelltes zip: RC6
Karte (falls relevant): NF Marsch 4-fach 2.1
Fahrzeug(art) (falls relevant): alle
Multiplayer mit dedi Server

**Beschreibe den Bug**
Wenn Editor Modus aktiviert ist, lassen sich Wegpunkte weder verschieben (auswählen und mit RMB festhalten und verschieben) noch löschen (auswählen LALT + LMB). Neue Wegpunkte setzten funktioniert jedoch einwandfrei, ebenso wie das manuelle Verbinden vom Wegpunkten

**Falls anwendbar - Schritte mit denen ich den Bug nachstellen kann**

**Screenshots**
Falls relevant, bitte Screenshots beifügen

**Comment by Bobster82** [comment]
Do u also use courseplay?
I know i need to press the middle mouse btn to drag points. The alt+lft btn is removing my points... Maybe u have the caps lock on or off?

**Comment by PatrickW1992** [comment]
Hello,
same problem here...settings:
AutoDrive Version 1.1.0.5. RC6
Map: Wild West Version 1.1
It does not help to deselect all other mods, when opening the savegame.
Courseplay has also never been activated for this map.
I got the same Problem, when i start on a new map without any mods except AutoDrive.
Today in the Morning, everything was fine. But after an pc-restart i got this problem.

**Comment by TMac063** [comment]
Hi Folks
Yup, we also use Courseplay and the Seasons-Mod. But up until now, there hasn't been an issue with the waypoints.
Regards
TMac63

**Comment by PatrickW1992** [comment]
Hi TMac,
I got this Problem actually only in one savegame. When starting a new game (it doesnt matter, if CP ist activated or not), evrything is fine.
Regards

**Comment by TMac063** [comment]
Hi Patrick
that would be a bummer. But we`ll try this.
Thx 
Regards

**Comment by TMac063** [comment]
Hi Folks,
I´d like to roll back to RC5 for testing purposes. But I can't seem to find it anywhere. Is it still available for download?
I´ve tried version 1.1.0.4 but with that, my savegame wouldn't even start.
We´ve already invested so much time and effort into this savegame that starting from scratch is not an option.
Thx in advance
Regards

**Comment by Axel32019** [comment]
@TMac063 @PatrickW1992 
Hi all,
I can not explain the difference why some key combinations are working and the same time the other ones not.
All are handled in the same routine.
One idea is to backup the key bindings, and start with an empty.
Are you all playing on a dedi server or is this also observed in a single play without any server?

**Comment by TMac063** [comment]
We use a dedi server for our MP. I‘ve tried a savegame from our server in SP. Same symptoms. Now I‘m trying to do rollbacks of CP and AD, but I‘m not able to find the AD 1.1.0.5 RC 5. And 1.1.0.4 doesn‘t work at all with the savegame (it doesn‘t start).Thx for your help.Regards


Gesendet von Yahoo Mail für iPad


Am Sonntag, Oktober 25, 2020, 7:53 PM schrieb Axel32019 <notifications@github.com>:




@TMac063 @PatrickW1992
Hi all,
I can not explain the difference why some key combinations are working and the same time the other ones not.
All are handled in the same routine.
One idea is to backup the key bindings, and start with an empty.
Are you all playing on a dedi server or is this also observed in a single play without any server?

**Comment by Axel32019** [comment]
@TMac063 Is this still an issue or a topic of how-to-use?

**Comment by TMac063** [comment]
Hi Axel32019,
no, this issue is solved
Thx again
Regards
