### ISSUE TITLE
[BUG] Pick up and deliver mode, AD does not switch off and not back to CP- Modus Abholen und Abliefern, AD übergibt nicht zurück an CP

### ISSUE THREAD

**Issue by haamic** [Stephan-S/FS19_AutoDrive#1619]
AutoDrive Version: 1.1.0.5 RC6
Release or selbsterstelltes zip: ReleaseC 6
Karte (falls relevant): Alle
Fahrzeug(art) (falls relevant):

**Beschreibe den Bug**
Modus Abholen und Abliefern, Fahrzeug fährt mit Sammelwagen per CP über das Feld, wenn Wagen voll, übergibt CP an AD.
Nach abladen am Silo und Rückkehr zum Feld, bleibt AD aktiv (grün) und übergibt nicht wieder an CP.

[log.txt](https://github.com/Stephan-S/FS19_AutoDrive/files/5358672/log.txt)

**Falls anwendbar - Schritte mit denen ich den Bug nachstellen kann**

**Screenshots**
Falls relevant, bitte Screenshots beifügen

![Farming Simulator 19 10 10 2020 11_19_20](https://user-images.githubusercontent.com/28841989/95651407-85e5ff80-0aea-11eb-858f-a9c6a674465d.jpg)

**Comment by Pioner912** [comment]
Ich schließe mich hier mal an manchmal funktioniert es und dann wieder nicht!

**Comment by Axel32019** [comment]
Screenshot und log schonmal sehr hilfreich!
Bitte noch einen Screenshot mit CP HUD hinzufügen, da sieht man ob CP noch aktiviert ist. CP Version?
Hinweis: Wird während dem Abfahren durch AD das Abholen-Ziel geändert wird CP deaktivert und macht nicht weiter - das ist beabsichtigt damit nicht auf falschem Feld CP gestartet wird.

**Comment by haamic** [comment]
CP ist immer aktiv während AD zum Entladen fährt und es ist die aktuellste  .66
ich mach noch Screenshot zum Beweis. Während der Fahrt zum Abladen und dann am Feld.
Das ziel wird zwischendurch nicht geändert.

kleiner hinweis, im log steht "[AD] LoadAtDestinationTask:update Wait to be loaded manally", soll sicher manually heissen ;-)

**Comment by haamic** [comment]
![CP](https://user-images.githubusercontent.com/28841989/95653661-969e7180-0afa-11eb-9d39-13c86bf120d9.jpg)

**Comment by Pioner912** [comment]
[log.txt](https://github.com/Stephan-S/FS19_AutoDrive/files/5358937/log.txt) 

Wie bei meinem Vorredner zu sehen sieht es bei mir auch aus, siehe letztes Bild. 
Ich habe aktuell wie folgt die Versionen Autodrive aktuelle R6 und Courseplay 066

**Comment by Pioner912** [comment]
Zum besseren Verständnis bei mir ist es der 916 welcher am Feldrand steht und nicht wieder an Courseplay übergibt.

**Comment by Axel32019** [comment]
Bitte mal Debug "Externe Schnittstelle" aktivieren.

**Comment by haamic** [comment]
Hatte ich bei meinem ersten Post gemacht
im log tauchte nichts weiter auf, als das was ich geschickt habe

**Comment by haamic** [comment]
da tauchen nur 2 Zeilen im log auf, wenn er von CP auf AD schaltet und zum abladen fährt

2020-10-10 21:44   Info: 340 CVX: AutoDrive:StartDrivingWithPathFinder(23, 26, table: 0x028d41e9aa90, function: 0x028c0cb0cdb0, nil)
2020-10-10 21:44   Info: 340 CVX: AutoDrive:StartDriving(23, 26, table: 0x028d41e9aa90, function: 0x028c0cb0cdb0, nil)

mehr passiert nicht, bis er am feld wieder ankommt und wie beschrieben stehen bleibt

**Comment by Pioner912** [comment]
@Axel32019 brauchst du von mir ggf. noch etwas?

**Comment by Axel32019** [comment]
@haamic Das sieht OK aus.
Ist noch anderer Verkehr unterwegs, KI-, CP- andere AD-Fahrzeuge?
War der o.g. Abfahrer zwischenzeitlich tanken -> LCTRL+ALT+M ?
Ursachenfindung ist halt nicht so einfach....

**Comment by haamic** [comment]
@Axel32019 
nein nichts dergleichen, kein KI verkehr und das einzige Gespann war der Fahrer mit dem Sammelwagen.(Feld=CP, Strasse=AD)
auch wollte bzw. war er nicht zum tanken.
ich versteh es auch nicht. 
schicke ich das Gespann per AD zum Feld mit aktivierten "C" (Coursplay starten bei Zielerreichung) dann übergibt er ordsnungsgemäss an CP,  und beginnt die Arbeit. nur eben nicht bei Erreichen des Feldes nach dem Abladen.

**Comment by Axel32019** [comment]
@haamic "schicke ich das Gespann per AD zum Feld mit aktivierten "C" (Coursplay starten bei Zielerreichung)" Das ist nur bei der 1. Anfahrt notwendig, nicht wenn schon von CP an AD übergeben wurde!
Suche noch weiter...

**Comment by 3lronMcBong** [comment]
Hallo,

habe fast das selbe Problem.

Aktuellste CP und AD Version.

Bei mir ist es anders, Feldarbeit CP auf dem Feld mit Ladewagen.
Ladewagen ist voll, übergibt an AD, AD hat dann den Auflade Punkt drinnen und springt an dem Punkt nicht auf den Abladekurs um.
So geht das als im Kreis....

Bis sich das ganze Spiel aufhängt.....
[log.txt](https://github.com/Stephan-S/FS19_AutoDrive/files/5361176/log.txt)
[log - Kopie (2).txt](https://github.com/Stephan-S/FS19_AutoDrive/files/5361177/log.-.Kopie.2.txt)
[log.txt](https://github.com/Stephan-S/FS19_AutoDrive/files/5361210/log.txt)

https://www.youtube.com/watch?v=vZk2H09d4H0

**Comment by haamic** [comment]
Das weiß ich. Wollte es nur erwähnen, da es da ja funktioniert mit dem beenden von AD und Übergabe an CP. 
Ich kann erstmal damit leben, du hast bestimmt andere Prioritäten, die wichtiger sind. 
Scheint ja bei anderen wohl zu funktionieren.
Aber trotzdem Danke für deine Mühe. 
Daumen hoch.

**Comment by Axel32019** [comment]
@3lronMcBong Bitte nicht Abladen ab Level auf 100% stellen - CP macht nicht zu 100% voll. Somit versucht AD immer wieder das fehlende 1% vom Feld zu holen!

**Comment by 3lronMcBong** [comment]
> @3lronMcBong Bitte nicht Abladen ab Level auf 100% stellen - CP macht nicht zu 100% voll. Somit versucht AD immer wieder das fehlende 1% vom Feld zu holen!

echt jetzt?
ist ja lustig
gleich mal ausprobieren.

Danke :-)

**Comment by Axel32019** [comment]
@haamic Bei Interesse / Gelegenheit bitte mal die beta-Version testen.

**Comment by haamic** [comment]
@Axel32019 
Wird gemacht, spätestens morgen Abend

**Comment by haamic** [comment]
@Axel32019 
hat bisschen gedauert, aber der Test war erfolgreich mit der beta. nun stoppt das Gespann nicht mehr am Feld ,sondern setzt die Arbeit fort, so wie es sein soll. Super, ich danke dir.

kurze Frage nebenbei... es kommt vor, das der Anhänger voll ist , sich aber ziemlich am Feldrand befindet, (beim Abtanken eines Dreschers oder beim Sammeln vom Schwad). Das Gespann wendet und fährt Richtung Feldausfahrt, leider wendet es meist in ein Hindernis, das sich zu nah neben dem Feld befindet (Bäume/Wald , Zaun...) also wenn sich AD im Uhrzeigersinn auf dem Feld bewegt, wendet es entgegen des Uhrzeigersinnes. Wäre es möglich, das AD den Feldrand erkennt und IMMER auf dem Feld wendet und zurück fährt? oder man es als Option einstellen kann? Hab schon alle Abfahrtmodi versucht, aber es endet immer gleich im "Gestrüpp".

Über eine Antwort diesbezüglich ,von dir Axel, würde ich mich freuen.
dann kann hier geschlossen werden.
Schönen Abend und nochmals Danke, Gruss Micha

**Comment by Axel32019** [comment]
@haamic Halllo Micha, 
Erstmal Danke für die Rückmeldung!
Bitte nicht zwei verschiedene Dinge vermischen / davon abhängig machen den ursprünglichen issue zu schließen ;-)
Hast Du schon die Einstellung "Pfadplanung begrenzt" ausprobiert? Damit sollte der Abfahrer das Feld nicht verlassen wenn er darauf steht. Ich stecke jedoch noch nicht in den Details der Pfad-Planung drin - kann daher nur vermuten, Tips geben...

**Comment by marc950** [comment]
hallo,
bei mir sammelt das Gras fährt zum Silo und bleib stehen lädt nicht ab. Und wenn ich ihn entleere und anschalte fährt er wiedr zum Silo und bleid wieder stehn

**Comment by Axel32019** [comment]
@marc950 Hallo, Bitte mal den Zielpunkt in Fahrtrichtung weiter verschieben.

**Comment by marc950** [comment]
@Axel32019 Hallo, habe es mit einem anderem Mods hin bekommen. Den Zielpunkt verschiebe ich oft in Fahrrichtung

**Comment by Axel32019** [comment]
Keine weiteren Anmerkungen hier -> Closed.
