### ISSUE TITLE
pulldown list - scrollen

### ISSUE THREAD

**Issue by andreasthu** [Stephan-S/FS19_AutoDrive#162]
hallo Stephan
nun gibt es ja die möglichkeit, die kurspunkte per pull down liste anzeigen zu lassen
https://github.com/Stephan-S/FS19_AutoDrive/issues/149

wenn nun aber die liste sehr lange ist, kann man sie per mausrad durchscrollen (rauf/runter)
wenn man das macht, zoomt man auch gleichzeitig die Fahrzeugkamera rein bzw. raus.
scrollt man hingegen nur in dem einzelnen Feld ohne pull down liste (wie früher) zoomt der Fahrzeugzoom nicht mit

lg
andreas

**Comment by haamic** [comment]
also mir kams so vor, das der mauszeiger in der zeile bei geöffneter Liste bleiben muss und man dann durch die liste scrollt, ohne den zoom zu betätigen. verrutscht  der Mauszeiger minimal, wird gezoomt

**Comment by Stephan-S** [comment]
hi,

das Zoomen muss ich aktiv unterbinden und habe das noch nicht auf die Pulldown liste erweitert.
Bisher ist es genau wie nach eurem Eindruck nur in den Textfeldern enthalten.

Ich kümmere mich heute/die Tage darum.

Beste Grüße,
Stephan

**Comment by Flyingfufu** [comment]
Hi Stephan,

I would like to add one suggestion for this pulldown list : get it sorted by name. I think it would make life easier to find and select the destination we are looking for.

All the best,
Fabien

**Comment by andreasthu** [comment]
HAllo stephan
habe die neue version (mit dem Helferlohn), und der zoom ist behoben.
Danke dir dafür
btw, stimme flyingfufu da zu, eine sortierung der ziele wäre hilfreich, aber nicht vordringlich, kann das aber weiterhin über die xml im savegame machen
lg
andreas

**Comment by Stephan-S** [comment]
Alphabetische Sortierung ist im neuesten Commit enthalten. Wird im nächsten Release auch im .zip File landen :-)

**Comment by Flyingfufu** [comment]
Working top ! Thanks a lot.

**Comment by andreasthu** [comment]
eine kleinigkeit ist mir aufgefallen:
[URL=https://www.directupload.net/file/d/5470/r2bjq3vu_png.htm][IMG]https://s17.directupload.net/images/190601/temp/r2bjq3vu.png[/IMG][/URL]
