### ISSUE TITLE
[BUG] Loading in the trigger/ Beladung im Trigger

### ISSUE THREAD

**Issue by SAM24986** [Stephan-S/FS19_AutoDrive#1620]
AutoDrive Version: 1.1.0.5 RC6
Release or selbsterstelltes zip: Release
Karte (falls relevant): Alle
Fahrzeug(art) (falls relevant): MAN Sattelzugmaschine mit Gülleauflieger

Hallo,
ich habe zum Transport für Gärreste einen Gülleauflieger im Einsatz, der bei der GlobalCompany BGA mit Grimme Beetbeater Gärreste abholen und in einen Feldrandcontainer überladen soll. Das funktioniert auch, solange sich eine Restmenge im Tank befindet. Ist der Tank aber leer so wird angefragt was geladen werden soll und der Screen friert ein und lässt sich nicht schließen, auch kann man die Beladefunktion weder starten noch abbrechen/ schließen.
Ich muss das Spiel dann über die Console beenden.
Jemand eine Idee? 
Gruß
SAM
![fsScreen_2020_10_10_15_03_49](https://user-images.githubusercontent.com/59346694/95660879-12181700-0b2b-11eb-9afd-362010197aba.png)

**Falls anwendbar - Schritte mit denen ich den Bug nachstellen kann**

**Screenshots**

**Comment by Axel32019** [comment]
CP im mod-Ordner - aktiviert oder nicht spielt erstmal keine Rolle?

**Comment by SAM24986** [comment]
Ja, hat aber bisher immer sehr gut funktioniert.

**Comment by Axel32019** [comment]
Welche Version?

**Comment by SAM24986** [comment]
6.02.00049

**Comment by Axel32019** [comment]
Keine Ursache :-) Schließen darfst Du auch gerne.
