### ISSUE TITLE
[Feature Request] Beladen/Entladen mehrerer FillUnits

### ISSUE THREAD

**Issue by rohne83** [Stephan-S/FS19_AutoDrive#1621]
Hi,

AutoDrive ist wirklich geil, es gibt aber noch ein paar Probleme bei mehreren FillUnits im selben Gespann. Die drei folgenden Themen brennen mir da auf den Nägeln:
1. im Durchfahrsilo (zumindest dem Standardsilo der BGA auf der Felsbrunn) wird immer nur der erste Anhänger (bzw beim LKW die Pritsche) entladen. Alle weiteren Trailer werden nicht abgekippt. Screenshots
![fsScreen_2020_10_10_19_59_47](https://user-images.githubusercontent.com/71030138/95681481-66c99980-0be0-11eb-9169-8d73184d3ba4.png)
![fsScreen_2020_10_10_20_12_44](https://user-images.githubusercontent.com/71030138/95681535-9c6e8280-0be0-11eb-9238-7bd0651436e8.png)

2. [SOLVED] bei mehreren FillUnits innerhalb des selben Trailers (zB der Standard Sattelauflieger Wilson PaceSetter) wird am Silo immer nur die erste FillUnit richtig befüllt. Bei der zweiten fließen nur ein paar hundert Liter rein, und der Fahrer bleibt dann an Ort und Stelle stehen. Ist im Screenshot (Zielpunkt wird vom HUD verdeckt) zwar fast ein RoadTrain, aber das gleiche Phänomen hat man auch wenn man auf den zweiten Trailer verzichtet. Bzw wenn man den Abfahrer entlässt und neu einstellt, tritt am zweiten Trailer genau das gleiche auf. Wenn dagegen jeder Trailer nur eine fillUnit hat (zB Abfahrgespanne wie in den Screenshots vom Durchfahrsilo) klappt alles jetzt schon wunderbar.
![fsScreen_2020_10_07_18_23_30](https://user-images.githubusercontent.com/71030138/95681753-e6a43380-0be1-11eb-8e9e-8a8d55ff7aea.png)

1 und 2 tritt auf egal wie groß der maximale Siloabstand eingestellt ist. Bei CP klappt beides schon jetzt mit dem normalen Mode 1/2. Allerdings ist CP halt für die entsprechenden Straßentransport-Strecken weniger gut geeignet als AutoDrive. Und was bezüglich Punkt 1 richtig frustriert: nur AD-Abfahrer lassen sich vom Häcksler beide Anhänger beladen, CP kann genau dieses wiederum nicht...

3. [SOLVED] recht verwandt mit Punkt 2: ist es irgendwie möglich sich von AD gesteuerte Gespanne mit mehreren FillUnits an zB einer MotherBin komplett beladen zu lassen? Ist ja ähnlich wie am Silo, nur dass keine R-Taste nötig ist, sondern automatisch überladen wird. Aber die MotherBin selbst bleibt ja während der gesamten Ernte an Ort und Stelle stehen. Zur Zeit muss man hier offenbar ebenfalls immer manuell eingreifen.
Hier wie auch bei Punkt 2 könnte es evtl auch helfen, wenn man dem Abfahrer mehrere Aufladepunkte (so dass sich an jedem eine andere FillUnit unter dem Entladerohr des Silos / der MotherBin befindet) zuweisen kann, die er der Reihe nach anfährt bevor er zum Ablieferpunkt weiterfährt. Aber schöner wäre es natürlich wenn er von selbst voll laden lässt und weiter vorrückt.
![fsScreen_2020_10_10_18_10_09](https://user-images.githubusercontent.com/71030138/95681968-0ee06200-0be3-11eb-8a30-4de5745a883d.png)

**Comment by Anonymous-any** [comment]
Hi :) Truck sim :p

**Comment by Axel32019** [comment]
@rohne83 Hallo,
Zu 1.
Das zweite Bild verdeutlicht die Schwierigkeit schon mal: Die beiden Anhänger sind unterschiedlich groß. Die Geschwindigkeit beim Abladen wird aus Abladegeschwindigkeit des Anhängers und Länge des Silos ermittelt. Das auf 2 oder mehr Anhänger, dann noch mit unterschiedlicher Füllmenge zu erweitern stellt einen ganz schönen Aufwand dar.
Mein Empfehlung ist der TAW 30: kein übertriebenes Füllvolumen, breite Ablage -> gut zu verteilen / verdichten
Zu 2. 
Kann ich mit RC6 nicht nachvollziehen, es sei denn das Silo ist leer geworden - ist das der Fall?
Zu 3.
AD sucht nur nach festen Ab- / Lade-Triggern. Das Überladen funktioniert nur mit dem "Trick" den Zielpunkt so zu setzen das der Zielpunkt da ist wo Beladen "irgendwie" erfolgt. Genau deshalb bleiben Abdeckungen von Anhängern auch bis zum Ziel offen.

**Comment by rohne83** [comment]
1. Dass es mit nur einem Anhänger geht und es da auch regelrecht fürs Häckseln entwickelte Tandem/Tridem-Trailer gibt weiß ich, nur ist das nicht unbedingt meine bevorzugte Kombo für die Abfahrer ;) Ganz besonders nicht in Ostalgie-Szenarios: da hat man entweder Traktor mit zwei HW80-Anhängern, oder eben LKW W50 ebenfalls mit angehängtem HW80. Also definitiv immer zwei Aufbauten abzukippen. Funktioniert zZ für Fahrsilo aber halt leider nur mit Courseplay, das aber die erwähnten Schwachpunkte/Probleme an anderer Stelle hat.
So perfekt (und damit aufwändig) wie gewohnt müsste man das in meinen Augen auch gar nicht umsetzen. Hauptsache es wird überhaupt die ganze Ladung abgekippt. Dass bei unterschiedlicher Kapazität der fillUnits das Silo dann nicht so super gleichmäßig befüllt wird wie sonst kann man doch sehr gut verschmerzen.
2. hab ich mit der RC6 noch nicht probiert. Werd ich die Tage mal schauen.
3. also zur Zeit keine Möglichkeit/Trick und auch nichts geplant das irgendwie zu ermöglichen? Die Version im obigen Screenshot mit zweitem Zielpunkt funktioniert auch nicht gerade prickelnd, da die Planen auch auf diesen paar Metern schon wieder zugemacht werden, und somit der zweite und dritte Behälter gar nicht erst befüllt werden können.

**Comment by rohne83** [comment]
Wegen 3.: Gibt es denn in der API die Möglichkeit abzufragen, ob eine der angehängten FillUnits gerade befüllt wird? Wenn ja, dann müsste man halt bereits in der eingestellten Siloabstand-Entfernung die Abdeckung öffnen, sie auf der restlichen Strecke die ganze Zeit offen lassen, und jedes Mal anhalten wenn wieder Ladung in einen Trailer fließt. Wenn nach Abschluss dieses Beladevorgangs (zB weil MotherBin leer) die FillUnit noch nicht voll ist, wird gewartet, ansonsten weitergefahren bis erneut ein Beladevorgang startet. Kann man aber vielleicht auch noch abhängig von der Einstellung "Wenn Silo leer" machen.

Was bei Fahrsilos aber auch mit mehreren Trailern gut funktioniert ist das seitliche Abladen mehrerer FillUnits im Keilsilo, zumindest wenn man nur vorn am Eingang ablädt (rückwärts bis ans Ende fahren versuche ich mit Drehschemel-Anhängern eh möglichst zu vermeiden). Das gefällt mir bei AD sogar besser als bei CP, weil es der Realität ziemlich nahe kommt (so viel wie möglich auf die selbe Stelle). Keine Ahnung ob das überhaupt so bezweckt war, aber mir gefällts ;) Hier nochmal ein Screenshot um zu verdeutlichen was ich meine
![fsScreen_2020_11_13_15_51_42](https://user-images.githubusercontent.com/71030138/99091903-ca285c00-25d0-11eb-8f6c-da3d38e7b7b1.png)

**Comment by Tensuko** [comment]
@Axel32019 Beladen an einem Punkt, das was ich dir im Discord geschrieben habe :)

**Comment by Axel32019** [comment]
Zu 3. siehe #1625

**Comment by rohne83** [comment]
Hi, ich habs mir eben mal angeschaut. Sieht soweit schon ziemlich gut aus. Sucht er da wie bei CP erst hinter dem Beladepunkt nach einer Pipe oder auch schon davor?
Hab direkt mal wieder die große Variante probiert, mit MotherBin und RoadTrain ;) und das lief ziemlich gut soweit. Das einzige ist, der Abfahrer scheint beim Beladen während der Fahrt den eingestellten Füllstand zum Abfahren zu ignorieren. Wenn also in den letzten Trailer nur ein paar Liter gefüllt wurden, und er zB nur 80% Füllstand hat, dann fährt er nach Beenden des Überladevorgangs trotzdem direkt weiter zum Abladepunkt, selbst wenn er per Einstellung erst bei 90% losfahren soll.

**Comment by Axel32019** [comment]
Hallo @rohne83 ,
Das Abladen beginnt sobald festgestellt wird das Ladegut abgeladen wird, hier wird nicht auf den Füllstand geachtet sondern nur das Fahrzeug angehalten. Wird nichts mehr abgeladen geht's erstmal weiter, entweder zur nächsten FillUnit oder bis zum Ziel. Erst am Ziel wird der Füllstand geprüft - lässt sich erstmal nicht anders machen.
Sollte insgesamt aber schon mal ein Fortschritt sein, oder nicht?

**Comment by rohne83** [comment]
Hi @Axel32019 , sorry für die späte Rückmeldung. Ja natürlich, der Fortschritt ist gewaltig. VA für das Szenario mit MotherBin und RoadTrain ist das schon richtig geil mittlerweile. Wenn man es weiß, dass der Füllstand dann nicht mehr beachtet wird, kann man sich auch entsprechend drauf einstellen, und notfalls den Abfahrer erstmal anhalten, bis am Überladepunkt genug Füllmenge zusammengekommen ist.
Was nur mich bettrift, bei normalen ULWs nutze ich je nach Bedarf gern auch weiterhin mehrere CP-Wartepunkte (klappt mit dem neuen CP-Mode 3 eigentlich hervorragend), womit meine AD-Abfahrer in dem Fall ohnehin nicht selbst ihre FillUnits vorbewegen müssen. Von daher habe ich selbst da bisher auch keinerlei Probleme. Aber bei Leuten die mit zig Fahrzeugen mehrere Felder gleichzeitig bearbeiten, und da nicht immer ein Auge auf die Abfahrer haben können, kann das natürlich schon öfter mal auftreten, dass der Abfahrer trotz anderer Einstellung schon bei zB 30% Füllstand wieder zum Silo abladen fährt ;)

**Comment by rohne83** [comment]
Sehr schade finde ich allerdings, dass seit der 1.1.0.7 das seitliche Abkippen im Keilsilo nicht mehr machbar ist, wie es noch mit der 1.1.0.6 (vgl den Screenshot vom [13. November](https://github.com/Stephan-S/FS19_AutoDrive/issues/1621#issuecomment-726842530)) möglich war. Dahingehend scheint AD jetzt generell nur noch einen einzigen Trailer zuzulassen...

**Comment by rohne83** [comment]
also das Abladen mehrerer fillUnits im Durchfahrsilo funktioniert mittlerweile auch schon fast - aber nur fast. Der Abfahrer kippt sauber nacheinander beide (mit mehr hab ichs nicht getestet) Trailer ab. Es gibt dabei nur ein Problem noch: nachdem der erste Trailer abgekippt wurde, wird dieser zwar dann wieder in die Ruheposition zurückbewegt, dann allerdings direkt wieder gemeinsam mit dem zweiten Trailer erneut abgekippt. Und nach Verlassen des Fahrsilos wird dann nur der zweite Trailer zurückbewegt, während der vordere in Abkippstellung verbleibt. Zumindest mit LKWs ist das derzeit noch so.
![fsScreen_2021_04_23_11_54_16](https://user-images.githubusercontent.com/71030138/115955465-d6f19a00-a4f6-11eb-91e4-a221df1ae3d2.png)

**Comment by Stephan-S** [comment]
Closed due to duplication
