### ISSUE TITLE
deliver/load-unload changes tip

### ISSUE THREAD

**Issue by Tarzool** [Stephan-S/FS19_AutoDrive#1622]
When using either the "deliver" or "load & deliver" the mod changes how the early green tipper wagons ( forget the names 302 something?). Which is normally an easy fix, dragging the line. Unless you need them to tip due to collision issues, for example they always change to tip right, and i only have clearance to tip back, or grain door. It would be nice to have an option, either to tip a specific way, or to just use how its set ( aka ignore the tip direction).

**Comment by Axel32019** [comment]
@Tarzool  See here / Wenn Interesse hier entlang: #1663

**Comment by Iwan1803** [comment]
Da in 1.1.0.6 integriert, mach ich hier mal zu // Since integrated in 1.1.0.6, i'll close here 😎
