### ISSUE TITLE
[Question] "komische" bzw umständliche Kursberechnung

### ISSUE THREAD

**Issue by andreasthu** [Stephan-S/FS19_AutoDrive#1623]
**Question:**   
I've got a question...
Hallo Leute
ich habe auf meiner map bemerkt, das AD komische kursführungen berechnet:
![fsScreen_2020_10_13_16_35_50](https://user-images.githubusercontent.com/24860501/95876609-88a75580-0d73-11eb-8b95-01163db95b9a.png)
hier z.b. wäre der logische weg, (von links nach rechts) der rote Kurs, lange geraden und 1 kurve
AD berechnet bzw führt die fahrzeuge aber auf dem weißen kurs entlang
Kurze geraden und drei Kurven in diesem Stück machen diesen Abschnitt zeitaufwendiger.
der rote kurs funktioniert, wenn ich vom weißen ein stück rausnehme fährt AD ganz normal den roten kurs entlang
Edit: habe die v 1105-rc6
lg
andreas

**Comment by Axel32019** [comment]
Hallo "andreas", oder Andreas,
Der weiße Kurs ist kürzer als der rote und wird somit bevorzugt. Das ist ganz normal so!
Wenn Du unbedingt möchtest das der rote gefahren wird, setze ein Ziel im weißen und stelle max. Umweg >= 50 ein.

**Comment by andreasthu** [comment]
Hallo Axel,
Grundsätzlich sollten beide Strecken gleichlang sein. AD ist,  gestoppte Zeit, an der roten Strecke schneller als an der weißen. Kann sein das die weiße trotzdem ein paar Meter kürzer ist, aber AD bremst ja 3x vor den Kurven ab und kann auf den kurzen geraden nicht voll beschleunigen. 
In einer früheren Version gab es mal die Option kürzere oder schnellere Strecke bevorzugen. Diese Option gibt es in rc6 nicht mehr?
Ich hab als Lösung nun aber das Streckennetz überarbeitet, somit kann AD nunmehr über rot fahren.
Lg
Andreas

**Comment by Axel32019** [comment]
@andreasthu 
Hallo Andreas,
Ich denke mal die Frage ist damit geklärt, oder nicht?

**Comment by andreasthu** [comment]
Ja klar, danke
Lg
Andreas
