### ISSUE TITLE
Trouble moving my routes into folders

### ISSUE THREAD

**Issue by drich2211** [Stephan-S/FS19_AutoDrive#1626]
Do you have anything to show how to move the many routes into folders, some videos show clicking on the file to go in folder but when i click on a file it does nothing.

**Comment by Axel32019** [comment]
I do not really understand what you mean. Ingame just drag and drop with left mouse.

**Comment by rohne83** [comment]
And you have to be in Edit mode.

**Comment by Axel32019** [comment]
@drich2211 Do you still have an issue with this?

**Comment by drich2211** [comment]
No I it is fixed, been in hospital Sent from my Verizon, Samsung Galaxy smartphone
-------- Original message --------From: Axel32019 <notifications@github.com> Date: 10/25/20  5:06 PM  (GMT-05:00) To: Stephan-S/FS19_AutoDrive <FS19_AutoDrive@noreply.github.com> Cc: drich2211 <drich2211@yahoo.com>, Mention <mention@noreply.github.com> Subject: Re: [Stephan-S/FS19_AutoDrive] Trouble moving my routes into folders (#1626) 
@drich2211 Do you still have an issue with this?

**Comment by Axel32019** [comment]
@drich2211 Wish you all the best!
Closing here.
