### ISSUE TITLE
Detect premos 5000 as a thresher to drive off

### ISSUE THREAD

**Issue by Quattroschmidei** [Stephan-S/FS19_AutoDrive#1627]
**Question:**   
Hallo, ist es möglich das Autodrive auch gezogene Arbeitsmaschienen (z.B. Premos 5000) als Drescher erkennt, und sie Sebstständig Abtank und abfährt?
Oder liegt das am der Premos?

MFG Quattro

**Comment by Stephan-S** [comment]
Cleaning up old issues.
