### ISSUE TITLE
[BUG]Holmer TV585 with MB35 unload Pipe

### ISSUE THREAD

**Issue by Revolution1302** [Stephan-S/FS19_AutoDrive#1628]
AutoDrive Version: 1.1.0.5 RC6
Release or selbsterstelltes zip: Release
Karte (falls relevant): Alle
Fahrzeug(art) (falls relevant): Holmer Terra Variant 585 mit MB35

**Beschreibe den Bug**
Der Holmer klappt leider immer wieder das Rohr ein. Bei diesem Fahrzeug muss es jedoch ausgeklappt sein um richtig beladen werden zu können. Ich benutze ihn als ÜLW beim Mais Häckseln und des funktioniert nur durch ständige manuelle eingriffe um das Rohr zu öffnen.
Cool wäre hier evtl. eine Funktion die Rohrsteuerung auszuschalten.

**Falls anwendbar - Schritte mit denen ich den Bug nachstellen kann**

**Screenshots**
Falls relevant, bitte Screenshots beifügen

**Comment by Axel32019** [comment]
@Revolution1302 Hallo,
Mit Rohr einklappen meinst Du das Aufklappen des Aufbaus MB35 mit Taste "X"?
Rohr ausklappen ist, wenn ich es richtig sehe, mit Taste "O".
Das Aufklappen des Aufbaus MB35 zum Beladen ("X") ist leider eine Sonder-Funktion von diesem, also kein Bug sondern eher Feature-Request.
Funktioniert das Beladen wenn Du vor AD Start den Aufbau aufklappst?

**Comment by Revolution1302** [comment]
Hallo Axel,
Das Problem bei diesem ÜLW Aufsatz ist das das Rohr eigentlich ein Förderband ist was dann den Trigger verdeckt. Somit muss das Rohr („O“) immer ausgeklappt sein. Das Gerät an sich habe ich vorher schon ausgeklappt.

**Comment by Stephan-S** [comment]
Cleaning up old issues.
