### ISSUE TITLE
Autodrive läd Kurse aus dem SP nicht/ Autodrive doesn't load course data fom SP

### ISSUE THREAD

**Issue by chroboss** [Stephan-S/FS19_AutoDrive#1629]
Hallo Stefan und Kollegen,

ich möche gerne meine AD-Kurs aus dem SP auch im MP nutzen.
Ich habe also die Datei aus dem SP in das Savegame des MP kopiert.

Im MP-Spiel wird mir jedoch kein einzger Haltepunkt angezeigt, auch keine Strecken.
Neue Strecken und Haltepunkte kann ich anlegen, diese stehen dann auch zur Verfügung.

Im SP habe ich nochmals kontrolliert, da ist alles o.k.

Was habe ich falsch gemacht? 

[log_server.txt](https://github.com/Stephan-S/FS19_AutoDrive/files/5408521/log_server.txt)

Hello,
Id like to use my SP-courses in MP.
So I copied my SP-File ito the MP Savegame. But no courses and no points are shown in MP.
But I can create new couses and points and use them.

I'd control the SP Game, everything is fine there.

What did I wrong?

Danke/ Thanks
Charlie

**Comment by Williwillswisse** [comment]
Hallo Charlie, hast du deine Kurse mit der deutschen Version eingefahren und steht der Server vielleicht auf EN ?
Dann passt der Kartenname nicht.

**Comment by Iwan1803** [comment]
Laut Log:
`Farming Simulator 19 (Server)
  Version: 1.6.0.0 b9289
  Available Languages: en
  Language: en`
und Map müsste Altkirch sein.
Wird auf dem Server denn eine neue leere AD-Config erstellt? Falls ja, dann die einfach mal mit deiner lokalen Datei vergleichen.

**Comment by Axel32019** [comment]
Hallo Charlie, Wie ist der aktuelle Stand?

**Comment by chroboss** [comment]
Hallo Axel.
Danke für Deine Rückmeldung. Der Stand ist leider unverändert. Deinen Vorschlag habe ich befolgt, konnte aber keine Unterschiede zwischen Server u. lokalen Dateien feststellen.
Ja, der Server erstellt beide AD-Dateien im Savegame. Zur Probe habe ich es auch mit einer anderen Map versucht, hier der gleiche Effekt. Ich habe bis dato keine Lösung gefunden. 
Ich denke, das der Server das Problem ist. Der Server-Support weist jedoch alle Verantwortichkeit zurück (klar, es ist immer der User - oder der Modder ) . Was mich stutzig macht, das die auf dem Server erstellte AD Datei auch im Singleplay "versagt". 
Na ja, vielleicht gibt es ja noch eine Lösung.
Gruß Charlie

**Comment by Williwillswisse** [comment]
Hallo Charlie,
wenn du mir deine Config zu Verfügung stellen würdest und mir einen DL-Link zur Karte schickst würde ich das mal auf meinem eigenen Server testen.

**Comment by chroboss** [comment]
Link zur Map: 
http://89.163.192.64:11400/mods.html

Sorry, musste die config umbenennen, sonst kein Upload
[AutoDrive_Altkirch_in_Elsass_config.txt](https://github.com/Stephan-S/FS19_AutoDrive/files/5621906/AutoDrive_Altkirch_in_Elsass_config.txt)

**Comment by Williwillswisse** [comment]
Hallo Charlie,
dann versuche mal bitte diese Config.
Nochmal die Frage: Läuft dein Dedi auf DE oder EN ?
Das ist bei dieser Karte nicht so schön, weil sich der Dateiname nur in einem Buchstaben unterscheidet (im oder in).
DE Altkirch_im_Elsass
EN: Altkirch_in_Elsass

Ich habe deine Config mit dem passenden Buchstaben auf meinem Dedi so ans Laufen bekommen.

[AutoDrive_Altkirch_im_Elsass_config.txt](https://github.com/Stephan-S/FS19_AutoDrive/files/5623502/AutoDrive_Altkirch_im_Elsass_config.txt)

**Comment by chroboss** [comment]
Tausend Dank. Es lag wirkich nur an diesem Buchstaben. Verry tricky :)
Darauf wäre ich niemals gekommen.
Freudige Grüße aus der Pfalz

**Comment by Williwillswisse** [comment]
Immer gerne, dann mache ich hier zu ?

**Comment by chroboss** [comment]
O.K. Danke für den Hinweis.
Gann geschlossen werden.
