### ISSUE TITLE
[Feature Request "Continue"]

### ISSUE THREAD

**Issue by Anonymous-any** [Stephan-S/FS19_AutoDrive#1631]
**Is your feature request related to a problem? Please describe.**  
Hello, no problem here :) I was thinking to myself if in old versions there was not an input_binding function for the action "continue" like start/stop ?
A clear and concise description of what the problem is. Ex. I'm always frustrated when (I see CP bugs...:p)[...]

**Describe the solution you'd like**  

**Describe alternatives you've considered**  

**Additional context**

**Comment by Axel32019** [comment]
@Anonymous-any Welcome back ! :-)
As far as I can remember (back to 1.1.0.4) there was no binding, but it is not a big deal to add...
I would add it with not pre-defined key, so the user may select a suitable / not already used key.

**Comment by Anonymous-any** [comment]
Hi there ;)
Thanks to the Magicians here, in fact I was thinking to old previous version like FS17 in my head...or so started versions with this one fs19.
Thank for think to this add.

Ps: I hope too Giant company will have a look to think a day to buy this project/or rights and theirs authors like as they did with Seasons dev as example, because my view point it's unbelievable to see how the AD editor has been evolved like this to be more friendly usage it was very good already !, slide points, remove, add link them :) ^^ amazing job that is not native :/
My very best regard to give a relative stable and free program. (I live you close so)
Ano

**Comment by Axel32019** [comment]
@Anonymous-any Now included in BETA. #1663

**Comment by Anonymous-any** [comment]
Hello @Axel32019,

Yeah done ok confirmed it's working perfect I just tried it yesterday, many thank again :)

Best regard Ano
