### ISSUE TITLE
[Feature Request] Ordner anklickbar

### ISSUE THREAD

**Issue by andreasthu** [Stephan-S/FS19_AutoDrive#1632]
**Is your feature request related to a problem? Please describe.**  
es wäre schön, wenn man den Ordner auch durch Klick auf den Namen öffnen bzw. schliessen könnte
nicht nur über die pfeil-Schaltflächen ^ oder v ganz rechts

**Describe the solution you'd like**  
---

**Describe alternatives you've considered**  
---

**Additional context**  
![fsScreen_2020_10_23_00_09_46](https://user-images.githubusercontent.com/24860501/96935708-ea2e9900-14c4-11eb-9081-68336ccaee85.png)

lg
andreas

**Comment by Anonymous-any** [comment]
I was understand and thinking it was a request to simply clic the folder as destination who included the routes inside.

**Comment by andreasthu** [comment]
no problem,
1st white text:
Folders can only be opened or closed by clicking on the "^" or "v" arrow ion
2nd yellow text:
It would be nice to open / close the folder also by clicking on the name
3rd white text:
vehicles can be selected by clicking on the name

i think it was comfortable to fold / unfold the folders also by klick on the name ( in example on the text  "03.Verkaufsstellen") and not only on the up-down-arrow on the right edge

lg
andreas

**Comment by Axel32019** [comment]
@andreasthu @Anonymous-any See here / Wenn Interesse hier entlang: #1663

**Comment by andreasthu** [comment]
Spitze, danke, 
Werde ich dann gerne testen wenn ich wieder kann.
Lg
Andreas

**Comment by Iwan1803** [comment]
Da in 1.1.0.6 integriert, mach ich hier mal zu 😎
