### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by LSMT-elMatador** [Stephan-S/FS19_AutoDrive#1633]
**AutoDrive Version:** 1.1.0.5 RC6   
**Release or Custom Zip:** Release  
**Map (If applicable):Mitteldeutschland
**Vehicle / Type (If applicable):**   
**Multiplayer or Singleplayer:** Multiplayer / DEDI server

**Describe the bug**  
Der Server stürzt in letzter Zeit immer wieder ab, wenn AD keinen Weg findet! 6 Spieler auf DEDI Server mit 16 Slots
[message.txt](https://github.com/Stephan-S/FS19_AutoDrive/files/5430803/message.txt)

**Comment by Axel32019** [comment]
Hallo @LSMT-elMatador 
Wäre es möglich den log vor dem Auftreten dieser Meldungen zu bekommen?
Für mich sieht das nach einem Folgefehler aus, die eigentliche Ursache vermute ich davor.

**Comment by LSMT-elMatador** [comment]
Hallo Axel, leider ist es nicht mein Server und ich bekomme auch die gesamte log kaum zu Gesicht. Aber wenn es wieder passiert, werde ich um diese bitten und sie Dir zukommen lassen.

**Comment by Axel32019** [comment]
@LSMT-elMatador Wenn erforderlich bitte neuen issue aufmachen.
