### ISSUE TITLE
[Question] How to add waypoints?

### ISSUE THREAD

**Issue by Mike1977** [Stephan-S/FS19_AutoDrive#1634]
**Question:**   
In older Versions i could just leftclick on the terrain to create new waypoints. This doesn't work anymore, and the keymapping setting doesn't even show something like "create new waypoint"
Was this removed, or remapped to another keybinding?

PS: I can delete waypoints via [leftALT] + leftclick without a problem, but i can't create new points though.

**Comment by andreasthu** [comment]
shift+leftklick, or strg+leftklick
(not on pc but it works with one of the combis)
btw, you must open the editor mode before
(you can see the red dots and the lines)
lg
andreas

**Comment by Mike1977** [comment]
Works great with shift+leftclick.
Thank you very much. :)
