### ISSUE TITLE
[BUG]Dedicated Server

### ISSUE THREAD

**Issue by DerPechvogel93** [Stephan-S/FS19_AutoDrive#1635]
AutoDrive Version: 1.1.0.4
Release or selbsterstelltes zip: Release
Karte (falls relevant): Ellerbach
Fahrzeug(art) (falls relevant):

**Beschreibe den Bug**
Ich habe den Mod auf meinen Dedicated Server hochgeladen und auch installiert. Mein Freund hat den selben Mod auch installiert, kann jedoch nicht joinen, da der Mod rot hinterlegt wird.

**Falls anwendbar - Schritte mit denen ich den Bug nachstellen kann**

**Screenshots**
Falls relevant, bitte Screenshots beifügen

**Comment by Axel32019** [comment]
Hallo @DerPechvogel93 
Ihr nutzt die sehr veraltete Version. Bitte die aktuelle Version, speziell auf dedi, verwenden: https://github.com/Stephan-S/FS19_AutoDrive

**Comment by Axel32019** [comment]
@DerPechvogel93 
Gibt es schon was neues? Schon auf die aktuelle Version gewechselt?
