### ISSUE TITLE
Wasser/Milch entladen

### ISSUE THREAD

**Issue by MisterCookie1234** [Stephan-S/FS19_AutoDrive#1636]
Moin!

Sag mal.. wie verhindere ich denn, dass zb. der volle Wasser Transporter dem leeren Milchtransporter bei Begegnung auf der Straße, Wasser übergibt? 

Nutze noch 1.0.4.. ist das in 1.0.5 schon behoben? 
LG

**Comment by Iwan1803** [comment]
Das habe ich bei mir mit Wasser- & Dieseltransporten noch nie erlebt.
Was für Fahrzeuge und Anhänger sind das denn?

Und ja, probier es ruhig mit der aktuellen 1.1.0.5-RC6 aus.

**Comment by MisterCookie1234** [comment]
Jeweils nen Fendt + Dolly + MK32 Milchtank (der ja Wasser und Milch transportieren kann).

Folgendes Szenario - Wasserhänger lädt sich voll am Wassertank in der Stadt -> fährt weil er keine andere Route hat richtung Raiffeisen (In der Route Wasser eingestellt). Von Raiffeisen kommend kommt grade der Milchlaster (Lastwagen + MK32 Milchtank) leer zurück. Begegnung auf der Straße -> Trigger Punkt wird erkannt und der Wasser Tank gibt dem Milch Laster nen Schuss Wasser beim vorbeifahren. Der Milchlaster fährt weiter (mit Wasser) und der Wassertrecker bleibt stehen weil er nur marginal, 1-2% verloren hat und drauf wartet, sich weiter zu entladen. Komplett komisch..

Und ich hab bemerkt das im RC den ich drin hab sich die ausgewählte Strecke nach nem Game Neustart nicht speichert und man die neu eingeben muss. Gewollt?

**Comment by Axel32019** [comment]
@MisterCookie1234 Halllo,
Hast Du jetzt schon auf die aktuelle Version 1.1.0.5-RC6 gewechselt oder immer noch 1.1.0.4?
Mit nur "RC" kann ich leider nicht viel anfangen.

**Comment by MisterCookie1234** [comment]
Bin auf den 1.1.0.5-RC6 gewechselt.

**Comment by Iwan1803** [comment]
1.1.0.6 wurde released und ein Feedback, ob das Problem nun weg ist, wäre schön.
