### ISSUE TITLE
Modhub Mod Huddig - autodrive 1.1.0.5- RC6

### ISSUE THREAD

**Issue by robjana** [Stephan-S/FS19_AutoDrive#1637]
Hallo zusammen,

Sorry, ich weiß das die Autodrive RC 6 eine Beta Funktion ist und vielleicht nicht über all funktioniert.
Ich habe mir den Mod Huttig von Mofhub herutergezogen und installiert, imShop gibt es zwei Versionen davon, eine mit Korb und eine ohne Korb, den mit Korb lässt nicht öffnen. der andere schon.

Kann mir jemand helfen, danke.

**Comment by Iwan1803** [comment]
Mod Huttig von Mofhub?

**Comment by robjana** [comment]
Hallo,

Sorry Schreibfehler, meinte Modhub.
ja der Mod heist Huddig 1260 E von North Modding Company

Sorry

**Comment by Axel32019** [comment]
@robjana Hallo, Was ist jetzt das Problem mit AD?

**Comment by robjana** [comment]
Guten Abend,
ja das ist das Problem, der Mod wird angezeigt, im Shop mit zwei Fahrzeuge, einmal mit Fahrzeug mit Korb und einmal Fahrzeug ohne Korb im Bild, das Fahrzeug mit Korb kann man zwar auswählen, wird geladen usw usw, erscheint aber im Shop dann nicht.
Fahrzeug ohne Korb erscheint dann sofort.

**Comment by Axel32019** [comment]
@robjana Hallo, Alles was Du bisher geschrieben hast stellt kein Problem mit AutoDrive dar. 
Bist Du hier richtig oder möchtest Du Dein Problem an den Modder des Fahrzeugs adressieren?

**Comment by robjana** [comment]
An Axel 32019, danke für deine Rückinfo.
Im Test konnte ich Auto Drive auch nutzen, vielleicht war meine Frage hier falsch.
