### ISSUE TITLE
[Feature Request] Statt Anzahl an Runden, bestimmte Anzahl an Liter

### ISSUE THREAD

**Issue by Lars-LS17** [Stephan-S/FS19_AutoDrive#1638]
Hallo Zusammen,

ich wollte mal fragen, ob es möglich ist, bei dem Modus "Abholen und Abliefern" eine Option einzubauen, dass man nicht eine bestimmte Anzahl an Runden fährt (Wie es jetzt möglich ist), sondern eine bestimmte Anzahl an Litern. 
Dabei müsste AutoDrive natürlich prüfen, wie groß mein Anhänger ist. 

Bsp: Ich habe eine Produktion, wo ich 500.000 Liter Weizen brauche. Ich habe ein Anhänger mit 60.000 l Volumen.
Jetzt akutell kann ich den 8x fahren lassen, dann wären 480.000 Liter drin. 

Bei dem neuen Feature wäre es cool, wenn ich 500.000 Liter einstellen kann, dass er bei der 9. Fahrt automatisch nur 20.000 Liter einfüllt und dann zur Produktion fährt und ablädt. 

Wenn ich ziemlich alleine mit der neuen Funktion stehe oder das nicht machbar ist, dann ist es halt so.
Vielen Dank an euch allen für den Super mod.
Ich warte auf eure Rückmeldung.

**Comment by Axel32019** [comment]
@Lars-LS17 Hallo,
Nach erster Einschätzung würde ich sagen das das sehr aufwändig wird: Man muss (verschiedene?) Füllmengen im Fahrzeug /Anhänger(n) berücksichtigen, die Füllmenge benutzerfreundlich im HUD unterbringen, ....
Wir lassen es mal als feature-request so stehen, kommt Zeit kommt vielleicht ein Ansatz dafür....
