### ISSUE TITLE
[Question] Is there any non-tedious method for developing AutoDrive routing data for a new modded map?

### ISSUE THREAD

**Issue by MisterFister2016** [Stephan-S/FS19_AutoDrive#1639]
**Question:**   

Guten tag everyone!  I recently began playing a new heavily-modded playthrough on the MVP-19 map.  I also decided that this was going to be the playthrough where I finally delve into learning how to use both the AutoDrive and CoursePlay mods at the same time (neither of which I'd felt confident enough to attempt to use before.)

Things are going well, but one of the reasons I chose MVP-19 specifically was because it was a large map.  I'm still somewhat confused with the "Save" functions of AutoDrive, or how to locate the file where that data is stored.  My reason for asking is that I'm hopeful that FS19 players might already trade AutoDrive datafiles, even partial ones, where some of the work is already completed.  If I were to enlist a friend or co-player to assist me with this, each of us offline in separate singleplayer sessions, would there be a reliable method for consolidating and combining the results so that each person had access to the other player's progress?

**Comment by Axel32019** [comment]
@MisterFister2016 Hello,
From my understanding this is pointing to the same issue: #1641
So we handle all in this issue and close here.
