### ISSUE TITLE
[Question] Is there a non-tedious method for developing AutoDrive route data for recently-created modded maps?

### ISSUE THREAD

**Issue by MisterFister2016** [Stephan-S/FS19_AutoDrive#1641]
**Question:**   
I've got a question...

I've recently begun a new singleplayer playthrough on the heavily-modded friendly map MVP-19.  Before I started this save, I'd never before worked up the nerve to attempt to use either the AutoDrive or CoursePlay mods, whereas for this map I decided that this would be my first attempt, and both at the same time no less.

Is it realistic for me to hope for a full-map route network, on any map let alone one so huge as MVP-19?  Where does my AutoDrive data get stored on my WIndows10 system?  Would someone else be able to see or edit my AutoDrive data on their machine if they were to download my copy of such an AutoDrive savefile?  Is there a separate AutoDrive savefile outside of the larger savegame of the entire map?  Would there be any method by which I could split sections of the map for different people to lay rout information, and then assemble all contributions to a total map-wide effort?

**Comment by Axel32019** [comment]
@MisterFister2016 Hello,
For networks of maps you may ask the community in DC:
The AD network is saved in you savegame folder, file "AutoDrive_...MapName...._config.xml", see D:\Users\... \Documents\My Games\FarmingSimulator2019\savegame...
You may share this file with someone else, it is not encrypted, machine or user dependend or else.
It is not possible to split, assemble and so on... as the waypoints of the network are linked, which you will not be able to manage in separate AD config files!
In case you want to build a network with several people involved you can do in a Multiplayer, BUT: Only one person should record, modify etc. at the same time !!!

**Comment by MisterFister2016** [comment]
First of all, my sincere apologies for accidentally duplicating my post.  I recall thinking that my first attempt didn't upload properly, so I re-composed the same message, and it's obvious now that the first one was in fact submitted.

Second, thank you for advising me that assembling config files would generally not be possible.  My own speculation, then, is that if collaborating players were thorough enough to ensure that their routing networks never overlapped, I suppose it might theoretically be possible (likely after much trial and error) to cut and paste them into the same folder, and then go in-game to manually finalize the final connections / intersections / etc., yes?

**Comment by Mike1977** [comment]
>My own speculation, then, is that if collaborating players were thorough enough to ensure that their routing networks never >overlapped, I suppose it might theoretically be possible (likely after much trial and error) to cut and paste them into the same >folder, and then go in-game to manually finalize the final connections / intersections / etc., yes?

As i understand it, if you start to record a track, every point gets a unique ongoing id (1,2,3 ect) with its coordinates (x,y,z) associated. So you have a list with points from 1 up to several thousands on a huge map. Everyone who starts recording on a map has a list of points starting with 1,2,3 ect but with separate coordinates associated to them. So if you combine two of these lists, you get multiple instances of the same id wich will lead to the skript beeing very confused i guess ;)
