### ISSUE TITLE
[Question]

### ISSUE THREAD

**Issue by Lactobacillus82** [Stephan-S/FS19_AutoDrive#1642]
**Question:**   
Hallo, hoffe mal dass deutsche Fragen hier gelesen werden können. Zunächst ein mal muss ich sagen dass Autodrive ein Absolut toller Mod ist und ich ziehe den Hut vor allen die sowas im Stande sind zu programmieren und Mods zur Verfügung stellen.  Allerdings habe ich laufend das problem dass mir der Traktor beim Rüben abfahren wenn er zur Entladung fahren soll dem Rübenroder ( Holmer TerraDos) in den Weg fährt. Vielleicht könnte Courseplay das lösen aber ich habe das Problem dass ich wegen Schichtarbeit, Kinder usw. oft nur kurze Spielzeit habe und in dieser kurzen Zeit fahre ich die Riesenfelder der NF Marsch nicht in CP ein was dann auch nix bringt. Aber beim Dreschen und Gras mähen funktioniert es eigentlich auch so. LG

**Comment by Axel32019** [comment]
@Lactobacillus82 Hallo,
Deutsch oder Englisch ist alles OK.
Versuch doch bitte immer erst ausreichend Vorgewende (20...30m) zu ernten, dann hat AD auch die Chance diese geerntete Fläche zum Verlassen des Feldes zu verwenden. Noch ein Tip: Zwischen Feld-Ziel des Abfahrers und der Erntemaschine sollte abgeerntet sein, dann muß er nicht durch die Frucht und vor der Erntemaschine den Weg kreuzen.
Mit dem o.g. VG kann dann auch der Standart-Helfer gut ernten und kommt selten mit dem AD-Fahrer in die Quere.

**Comment by Lactobacillus82** [comment]
Die Probleme treten bei mir aber häufig mitten auf dem Feld auf vom wenden her gibts keine probleme. Die Frage ist eher warum wählt der abfahrer nach dem abbunkern den Weg dass er dem Roder ins Gehege fährt

**Comment by Axel32019** [comment]
Das liegt an der Pfad-Findung auf dem geernteten Feld - die kompliziertesten Algorithmen im ganzen AD!
Ist sehr schwierig zu lösen, aber mit o.g. Tips hab ich selten Probleme mit den Abfahrern...

**Comment by Stephan-S** [comment]
Cleaning up old issues.
