### ISSUE TITLE
[BUG] "Distance Pipe" always set to -5.0 for new vehicles.

### ISSUE THREAD

**Issue by Mike1977** [Stephan-S/FS19_AutoDrive#1643]
**AutoDrive Version:** aktueller RC   
**Release or Custom Zip:** Release  
**Map (If applicable):** All  
**Vehicle / Type (If applicable):** All
**Multiplayer or Singleplayer:** Singleplayer  

**Describe the bug**  
Jedesmal wenn ich ein neues Fahrzeug kaufe, oder für eine Mission ausleihe, steht die Variable "Abstand Rohr" auf -5.0 Meter, was dazu führt das der Abfahrer hinter den Drescher fährt und dort blockiert wird. 
Diese Variable in den Einstellungen, muss ich wirklich bei jedem neuen Fahrzeug ändern... 

**Screenshots**  

![AD_Bugreport 5](https://user-images.githubusercontent.com/5852750/98393920-4adbdb00-205a-11eb-818a-127de22cd961.jpg)

**Comment by Axel32019** [comment]
@Mike1977 Hallo,
Welche Version ist das? Woher hast Du diese?

**Comment by Mike1977** [comment]
Das ist die 1.1.0.5-RC6 und ich habe die von hier geladen. 
Allerdings ist das schon seiot einigen Versionen so, ich weis nur nicht mehr genau wann das angefangen hat.

**Comment by Axel32019** [comment]
Würdest Du bitte die AutoDrive...config.xml aus dem savegame mal als .zip hier anhängen, dann kann ich mir das mal anschauen.

**Comment by Mike1977** [comment]
"Something went really wrong, and we can't process that file. Try harder next time"

Wie kann ich das denn hier anhängen?

**Comment by Axel32019** [comment]
Nur als .zip, oder hast Du versucht die .xml direkt anzuhängen?

**Comment by Mike1977** [comment]
Nein, wenn ich die xml reinhänge, dann erzählt er mir das der nur bestimmte Anhänge erlaubt. Die Zip ergibt den Fehler den ich oben gepostet hab...

**Comment by Mike1977** [comment]
[AutoDrive_Felsbrunn_config.zip](https://github.com/Stephan-S/FS19_AutoDrive/files/5505541/AutoDrive_Felsbrunn_config.zip)

**Comment by Mike1977** [comment]
Sorry... da war der Scriptblocker schuld...

**Comment by Axel32019** [comment]
Das sieht nach einem MischMasch aus sehr alter config und neuer AD Version aus. Lösungsvorschlag:
1. **Das savegame sichern**
2. AutoDrive....config.xml im savegame löschen
3. Spiel starten, speichern und beenden
4. In die neu erzeugte AutoDrive....config.xml  nur die Zeilen aus der gesicherten zwischen
     `<Felsbrunn>`  
und     
`</Felsbrunn> `
einfügen
Dann sollte alles OK sein.

**Comment by Mike1977** [comment]
Ok, das war ja ne schwere Geburt... Zum Glück gibts die Config noch in den Backups des savegames ;)
Da die neue Config keine <Felsbrunn> Tags enthält, musste ich dann erstmal eine kurze Strecke einfahren, damit ich weis was ich ersetzen muss, bzw wohin die Tags müssen. Denn in der alten config waren die ja zwischen den ganzen anderen Tags, jetzt ganz am Ende.

Jedenfalls steht jetzt beim Kauf eines neuen Fahrzeuges 0.75 als Abstand, statt -5.0 ... Sollte das nicht 0 sein? 

Dann hab ich noch zwei kleinere issues im Hud, soll ich da jeweils ein neues aufmachen, oder kann ich das gleich hier rein posten?

**Comment by Axel32019** [comment]
Die 0.75 sind die Standardeinstelllung - funktioniert meist gut.
Für die issues mit HUD bitte neue aufmachen.
Danke & viel Erfolg....

**Comment by Mike1977** [comment]
Ok, dann danke nochmal. :)
