### ISSUE TITLE
Probleme beim finden von Wegen[Question]

### ISSUE THREAD

**Issue by TOPPERHARLEY86** [Stephan-S/FS19_AutoDrive#1644]
**Question:**   
I've got a question...

Hallo,

ich habe seitdem dem Update auf die neueren Version Probleme, dass meine Fahrzeuge oft keine Weg zu ihren Zielen finden. Vorher klappte alles bestens und jetzt leider nicht mehr. Wenn ich dann ein Stück in die Richtung des Zieles fahre, dann findet er wieder einen Weg. Daher gehe ich davon aus, dass es sich um eine Einstellungssache handelt.

Hat jemand eine Idee ?

Während der Suche nach einem passend Weg stockt das Spiel neuerdings auch.

Mit freundlichen Grüßen:

TOPPER

**Comment by Axel32019** [comment]
@TOPPERHARLEY86 Hallo, 
Welche Versionen vergleichst Du hiermit? 
Ein log, Map usw. wäre evtl. auch hilfreich.

**Comment by TOPPERHARLEY86** [comment]
Version Alt: 1.0.7.1
Version Neu: 1.1.0.5

Nachdem ich wieder die "alte" Version verwende, klappt wieder alles reibungslos.

**Comment by Axel32019** [comment]
Würdest Du bitte mal die Autodrive...config.xml als zip hier anhängen.

**Comment by Axel32019** [comment]
Keine Rückmeldung -> Closed.
