### ISSUE TITLE
[BUG] Drescher cannot call the driver

### ISSUE THREAD

**Issue by kferrano** [Stephan-S/FS19_AutoDrive#1645]
AutoDrive Version: 1.1.0.5-RC6
Release or selbsterstelltes zip: Release
Karte (falls relevant): NFMarsch
Fahrzeug(art) (falls relevant): 

**Beschreibe den Bug**
Eine klare Beschreibung des Bugs.

Ich habe angefangen Mais zu Häckseln und mit AD abzufahren (Häcksler fährt mit CP), am Anfang klappte alles auch noch Problemlos, alle 3 Abfahrer konnten gerufen werden, aber seitdem der Häcksler auf der gegenüberliegenden seite des Feldes 19 wartet wird kein Abfahrer mehr gerufen, obwohl sie auf den Ruf warten.

**Falls anwendbar - Schritte mit denen ich den Bug nachstellen kann**

wenn ich das wüsste, wüsste ich evtl. auch die Lösung

**Screenshots**
Falls relevant, bitte Screenshots beifügen
https://i.imgur.com/SGp9lOp.png
https://i.imgur.com/KoD4MG1.png
https://i.imgur.com/iVUAjdh.png
https://i.imgur.com/FM20Y4F.png
https://i.imgur.com/nhWQHor.png
https://i.imgur.com/oyzAaHK.png

**Comment by Axel32019** [comment]
@kferrano Hallo,
Bitte folgendes in den AD Einstellungen einstellen:
Häcksler: Abfahrer finden auf Nein, im AD HUD: Modus Fahren und Auswahl des selben Ziels wie beim Abfahrer (Feld 19 Abfahrer), aber AD nicht einschalten - nur mit CP fahren lassen
Die Einstellung "Abfahrer finden" ist auf ca. 300 m begrenzt, die Zuordnung der selben Ziele bei Abfahrer und Ernter funktioniert auf der kompletten Map

**Comment by Iwan1803** [comment]
Da 1.1.0.6 released wurde, mach ich hier mal zu // As 1.1.0.6 was released, i'll close here 😎
