### ISSUE TITLE
[BUG] small issues with Settings Menu

### ISSUE THREAD

**Issue by Mike1977** [Stephan-S/FS19_AutoDrive#1646]
**AutoDrive Version:** 1.1.0.5-RC6

Im Settings Menü gibt es ein paar kleinere Problemchen die man beim nächsten RC mal mit berücksichtigen könnte.

1.  zweite Zeile im User Settings Tab: keine Übersetzung verfügbar (tooltip inklusive) 
![AD_Bugreport 6](https://user-images.githubusercontent.com/5852750/98454127-4817dd80-2161-11eb-8f88-568a6f824bc0.jpg)

2. Experimentelle Features Tab: beide Punkte auch ohne Übersetzung und Tooltip fehlt komplett.
![AD_Bugreport 7](https://user-images.githubusercontent.com/5852750/98454148-81e8e400-2161-11eb-9aaa-f601b259374f.jpg)

3. Wenn man an einem Punkt Einstellungen vorgenommen hat (ist dann gelb markiert), dann bekommt man beim überfahren mit der Maus dort keinen Tooltip mehr angezeigt. 
Lässt sich leider nicht auf einem Sceenshot zeigen, weil man keinen Mauspfeil mit drauf bekommt. Sollte aber klar sein was ich meine.

**Comment by Axel32019** [comment]
@Mike1977 Hallo,
1. Gerne mal Reviewen:
Titel:
"Meldungen"
Werte:
"Ausgeschaltet" / "Kurz" / "Standard" / "Lang" / "Sehr lang" / "Dauerhaft"
Tooltip:
"Anzeige-Zeit für Meldungen: keine Anzeige / ca. 2,5s / 5s / 10s / 25s / Anzeige bis zum Schliessen"

2. Hier werden wir keine weiteren Übersetzungen und Tooltip einbauen, da das hart kodiert ist. Sollte auch vom Normal-Anwender nicht geändert werden, nur nach Aufforderung / eigenes Risiko etc.

3. Schauen wir uns mal an...

**Comment by Mike1977** [comment]
zu 1. Titel könnte auch "Benachrichtigungen" sein. Aber "Meldungen" geht auch.
Danke fürs Reply

**Comment by Axel32019** [comment]
In 1.1.0.6 umgesetzt -> closed
