### ISSUE TITLE
Betrifft die Version 1.1.0.5-RC6 und allgemeines

### ISSUE THREAD

**Issue by Wayper-170** [Stephan-S/FS19_AutoDrive#1647]
Hallo Autodrive Team

Bin das erste mal hier und weiß nicht ob ich hier richtig bin.
Ich habe mal ein paar Anmerkungen/Fragen.

1. Betrifft die Version 1.1.0.5-RC6
   Dort habe ich gemerkt , daß das Entladen an Mehreren Zielen (Modus Abholen u. Abliefern)
   nicht richtig funktioniert. Es klappt ein o. zwei mal, doch dann hält das Fahrzeug nicht mehr
   an sondern fährt ganz langsam weiter und entlät dabei etwas. Ab einer bestimmten Menge Ladegut im Fahrzeug
   wird dann auch nicht mehr entladen. Bis Version 1.1.0.5-RC4 klappt das alles wunderbar. Version
   1.1.0.5-RC5 hab ich leider nicht mehr.
   
2. Autodrive allgemein
   Warum werden Solo LKW's mit fest verbautem Aufbau, (z.B der FS19_MAN_18500Kipper u.v.a),
   von Autodrive nicht automatisch beladen?

3. Gab es früher nicht mal eine Option mit der man einstellen konnte daß Streckenabschnitte mit Wegpunkten
   bei der Routenberechnung nicht berücksichtigt werden? Wenn ja warum gibt es die nicht mehr?
   
   
   MfG
   FrankD

**Comment by Mike1977** [comment]
Zu 3. : Die Funktion "Maximaler Umweg" gibt es noch. Die macht ja keinen Sinn, ohne die andere "Zielpunkte vermeiden". Also entweder ist letztere aus versehen raus genommen worden, oder erstere aus versehen drin geblieben. 
Schade finde ich das aber dennoch, denn ich habe überall Behilfspunkte eingebaut, um den Verkehr zb nicht quer durch den Hof zu leiten, sondern außen herum auf der Straße. Das funktioniert jetzt leider nicht mehr.

**Comment by Axel32019** [comment]
Hallo,
1. Haben wir schon gelöst - kommt in RC7. Bei Interesse kannst Du gerne die beta-Version testen, aber nur wenn wir dazu das OK geben - ist immer eine Baustelle, die auch mal Löcher aufweist!

2. Wenn nicht schon ein issue existiert, bitte einen separaten erstellen

3. Es wurden noch nie Streckenabschnitte mit Wegpunkten nicht berücksichtigt! Die Wegstrecke zum Ziel wird in jedem Zielpunkt "virtuell" um den Wert max. Umweg verlängert. Das führt dazu das parallele Verbindungen dann kürzer erscheinen und somit bevorzugt werden. Und wie Mike1977 schon angemerkt hat, waren die Optionen Umweg und Zielpunkte vermeiden am Ende das Gleiche, daher machen 2 Optionen keinen Sinn.

**Comment by Iwan1803** [comment]
@Wayper-170 
hat dir meine Antwort in Discord nicht gefallen oder warum machst du ein Issue auf?

Da alles beantwortet ist, mach ich hier mal zu.

**Comment by Mike1977** [comment]
>     3\. Es wurden noch nie Streckenabschnitte mit Wegpunkten nicht berücksichtigt! Die Wegstrecke zum Ziel wird in jedem Zielpunkt "virtuell" um den Wert max. Umweg verlängert. Das führt dazu das parallele Verbindungen dann kürzer erscheinen und somit bevorzugt werden. Und wie Mike1977 schon angemerkt hat, waren die Optionen Umweg und Zielpunkte vermeiden am Ende das Gleiche, daher machen 2 Optionen keinen Sinn.

Vorher gab es ja den Button "Ziele vermeiden" und als einstelloption die "Maximaler Umweg" Ich sehe das nicht als zwei gleiche funktionen, sondern das erste schaltet das ganze ein, bzw aus und das zweite lässt einstellmöglichkeiten zu.

So wie du das beschrieben hast, ist das nicht sehr untuitiv würde ich sagen. 

Man muss also nur bei "maximaler Umweg" 200 Meter eingeben, und schon fährt er nicht mehr durch Punkte durch? Oder hat das jetzt mit den Zielpunkten garnichts mehr zu tun? Ich bin etwas verwirrt...

**Comment by Wayper-170** [comment]
Hallo

OK, danke an alle für die Antworten.

Am Di., 10. Nov. 2020 um 02:34 Uhr schrieb Mike1977 <
notifications@github.com>:
