### ISSUE TITLE
[BUG] AD stuck on exiting a field to reload

### ISSUE THREAD

**Issue by Chico0008** [Stephan-S/FS19_AutoDrive#1648]
**AutoDrive Version:** 1.1.0.5-RC6 (had it too on RC4 and RC5) 
**Release or Custom Zip:** Release  
**Map (If applicable):** All  
**Vehicle / Type (If applicable):**   All
**Multiplayer or Singleplayer:** Singleplayer  

**Describe the bug**  
AD still stuck when used with CP to reload a seder or anything else
CP give hand to AD, but AD get stuck, and nothing happen

**If applicable - Steps to reproduce the behavior**  
Get a course with CP, set AD correctly, wait for CP to stop, AD goes ON but stuck

**Screenshots**  
https://nsa40.casimages.com/img/2020/11/08/201108030614287321.png
[log.txt](https://github.com/Stephan-S/FS19_AutoDrive/files/5506455/log.txt)

**Comment by Axel32019** [comment]
@Chico0008 Is this issue still valid?
Have you checked if vehicle can reach fill station from pojected field border waypoint in normal drive mode?

**Comment by Axel32019** [comment]
No further news -> Closed.
