### ISSUE TITLE
Sammlung Karten

### ISSUE THREAD

**Issue by Bandesss** [Stephan-S/FS19_AutoDrive#165]
Hello what do you think of a network of cards to provide
I have 2 cards for it.
Multimap and Dondiego Map
Is there any intresting?
Sorry that is not a problem, but I did not know where to ask for it?
Greeting Bandes

**Comment by Stephan-S** [comment]
Hey,
there is an extra folder for courses in the repository.
If you want to add something to it, just make a Pull request, if you know how to :-)
If not, I can send you some tutorial on how to do it.

The folder is over here: https://github.com/Stephan-S/FS19_AutoDrive/tree/master/courses

If the course file does not contain any destinations which would only be used in your savegame, such as destinations to your placeable barns, silos and animals, I could also add them to the main mod afterwards :-)

Best regards,
Stephan

**Comment by Bandesss** [comment]
Hallo Stephan du hast mich falsch verstanden. Sie könnten hier einen Punkt oder Thread machen. Wo User zu den jeweiligen Karten in Ls machen können. So hätten alle Benutzer was ohne selber groß einzufahren. Wie schon gesagt habe ich 2 Karten komplett fertig mit Kursen

**Comment by Stephan-S** [comment]
Aber genau das ist doch auch der Sinn von dem Ordner.
Dort kann jeder User Strecken hochladen und jeder User kann sich die Strecken laden und in seinem Spiel nutzen.
Ich denke Thread würde hier nur unübersichtlich sein.
Wenn du 2 fertige config Dateien hast, lade sie doch einfach hier hoch und dein Ziel ist erreicht :-)
Oder was verstehe ich hier falsch?

**Comment by Bandesss** [comment]
Ok auch gut, wo muss ich die hochladen ?

**Comment by Bandesss** [comment]
Hallo die Karten die hochgeladen, sind alles angebunden Punkte der ganzen Karte komplett .

**Comment by Stephan-S** [comment]
Hallo,
bisher ist noch kein Pull Request erschienen.
Falls sie noch keine Erfahrungen mit Github haben, würde ich GitHub desktop empfehlen:
https://desktop.github.com/
Damit sollte es gut zu erledigen sein :-)

**Comment by Bandesss** [comment]
Das kapier ich nicht sorry, sehen Sie nun was ?

**Comment by Bandesss** [comment]
OK passt ? dann können wir schließen ?
