### ISSUE TITLE
[BUG] Kamera springt bei Fzg Innenansicht

### ISSUE THREAD

**Issue by Dueesberch** [Stephan-S/FS19_AutoDrive#1650]
Bei Fahrzeuginnenansicht springt die Kamera, wenn unter Dächern oder Toren durchgefahren wird.
Festgestellt bei Hof Bergmann und Kandelin. Weitere Maps habe ich nicht getestet.
Fahrzeug war/ist egal. Getestet mit JCB Fastrac, Case IH Puma, Agco Ideal

Schritte zum Nachstellen:
1. leeren Modordern erzeugen
2. CP (V6.02.00076), AD (V1.1.0.5-RC6) und Map Kandelin (V1.4.0.2) einfügen
3. neuen Spielstand anlegen / starten
2. Traktor kaufen (Keiner Einstellung ändern. Weder am Spiel noch am Fzg, noch an AD oder CP)
3. Bei der BGA Kandelin durch das linke Tor der rechten Halle fahren (Video
[Farming Simulator 19 2020-11-09 17-03-39.zip](https://github.com/Stephan-S/FS19_AutoDrive/files/5511780/Farming.Simulator.19.2020-11-09.17-03-39.zip))

Manchmal hängt die Kamera nachdem sie gesprungen ist. Man kann sie zwar noch drehen, aber kommt nicht mehr hoch in die Kabine. Ghet man auf Außenansicht und wieder zurück auf hängt die Ansicht immer noch irgendwo unter dem Fahrzeug.

Bei abgeschaltetem AD Mod tritt das Kamera springen nicht auf.

Logfile: [log.txt](https://github.com/Stephan-S/FS19_AutoDrive/files/5511950/log.txt)

PS: Auch wenn eigentlich der falsche Ort. Autodrive ist ein super Mod

**Comment by Dueesberch** [comment]
Nachtrag:
Hab jetzt nochmal mit Standard (Default) Material getestet.
Map Felsbrunn
Traktor Fendt 1050, JCB Fastrac 8330
Halle Easy Shed 1
Mir ist aufgefallen, dass es in der vorliegenden Konfiguration funktioniert, wenn die Maus eingeblendet ist. Ist sie nicht eingeblendet springt die Kamera. Auf der Map Kandelin passiert dies unabhängig davon ob die Maus ein- / ausgeblendet ist.
Zum Testen mal die Savegame und der mod-Ordner. Die Logg Datei zeigt weder Fehler, noch AD Einträge (außer die zum Laden des Mods) an.
[AD_test_camera.zip](https://github.com/Stephan-S/FS19_AutoDrive/files/5535265/AD_test_camera.zip)

**Comment by blue-painted** [comment]
I get this as well on Greenwich and Somerset Farms maps, some tractors or combines are worse than others.

**Comment by Stephan-S** [comment]
Fixed in latest alpha
