### ISSUE TITLE
Wendekreis einstellbar/ Turning Circle set manually[Feature Request]

### ISSUE THREAD

**Issue by CmdrTiri** [Stephan-S/FS19_AutoDrive#1651]
**Is your feature request related to a problem? Please describe.**  
Wenn ich mit Doppelzug (z.B. Randon Zuckerrohr-Auflieger + Hänger) unterwegs bin um Zuckkerrohr, oder Häckselgut abzufahren, versucht der AD-Abfahrer oft zu kleine Kurven zu fahren und verheddert sich dabei mit dem 2. Hänger.

**Describe the solution you'd like**  
Wenn man jetzt einen Mindest-Wendekreis für die Feldarbeit einstellen könnte, so wie bereits die Geschwindigkeit einstellbar ist, könnte man das Problem wahrscheinlich eliminieren.

**Describe alternatives you've considered**  
Alternativ müsste AD automatisch einen größeren Wendekreis berechnen, wenn mehr als ein Gerät angehängt wird. Das wird aber nicht so allgemein für alle Kombinationen möglich sein, daher wäre die manuelle Einstellung zumindest als zusätzliche Option bombastisch!

**Additional context**  
![fsScreen_2020_11_09_22_53_31](https://user-images.githubusercontent.com/70349981/98600852-7f5fc900-22de-11eb-9a71-9a0411e3a0b4.png)

**Comment by CmdrTiri** [comment]
Also so ähnlich, wie man auch bei CouresPlay den Wendekreis manuell festlegen kann...

**Comment by Iwan1803** [comment]
Bei einem Sattelzug ist der Wenderadius nun mal so klein wie der von der Zugmaschine.
Was ist, wenn man nun einen Radius einstellen könnte? Wann sollte der greifen? Immer oder nur auf dem Feld, wie in deinem speziellen Fall?
Ich denke, so eine Option wird zu einem deutlich erhöhten Rechenaufwand in der eh schon sehr komplexen Pfadberechnung führen und ob sich das lohnt, nur um ganz seltene Spezialfälle abzudecken....

**Comment by Stephan-S** [comment]
Ich muss hier leider auch absagen.
Die manuelle Eingabe würde unsere komplette Kursplanung auf dem Feld potentiell ganz schön aus dem Tritt bringen, da hier vermutlich zu oft (versehentlich) falsche Werte landen würden ohne dass dem Nutzer die Konsequenzen wirklich bewusst sind.
