### ISSUE TITLE
[BUG] Route not found

### ISSUE THREAD

**Issue by Dueesberch** [Stephan-S/FS19_AutoDrive#1652]
AutoDrive Version: 1.1.0.5-RC6
Alle Karten
Alle Fahrzeuge

**Beschreibe den Bug**
Autodrive findet routen nicht, wenn 2-Richtungsabschnitte (dunkelblaue Linie) dazwischen liegt.
Aufgefallen ist mir dies bei dem Setup, Rundkurs auf dem Hof - Hofausfahrt 2-Richtungsabschitt - Strecke auf Straße hin/zurück - Shopeinfahrt 2-Richtungsabschnitt - Rundkurs auf Shopgelände. Steht das Fahrzeug auf der Straße in Richtung Hof und das Ziel ist der Shop findet er keine Route.

**Falls anwendbar - Schritte mit denen ich den Bug nachstellen kann**
1. 2 Kreise fahren
2. Straßenabschnitt fahren
3. Kreise jeweils an einer Seite des Straßenabschnitts anbinden
4. Haltepunkte einfügen
(Siehe Screenshot 1)
Die einzelnen Fahrten ergeben vom Start (Spalte 1) zu den jeweiligen Zielen
`S 1 2 3 4 5 6`
`1 - o o o o x`
`2 o - o o o x`
`3 o o - o x o`
`4 o o o - x v`
`5 x x o o - x`
`6 o o x x x -`
`o` Route gefunden
`x` Keine Route gefunden
`-` irrelevant

**Screenshots**
Screenshot 1: Netz bei dem Routen nicht gefunden werden 
<img width="960" alt="Screenshot1" src="https://user-images.githubusercontent.com/69029565/98723440-a7a8ff80-2392-11eb-8008-64f718cc6d2b.png">

Screenshot 2: Netz bei dem von allen Punkten die Routen gefunden werden
<img width="960" alt="Screenshot2" src="https://user-images.githubusercontent.com/69029565/98723480-babbcf80-2392-11eb-9fcf-733472ad23b2.png">

Screenshot 3: Netz mit 2-Richtungsverbindung bei dem alle Routen gefunden werden
<img width="960" alt="Screenshot3" src="https://user-images.githubusercontent.com/69029565/98723509-c6a79180-2392-11eb-92ae-a0975e7c16ed.png">

**Comment by Axel32019** [comment]
@Dueesberch Hallo,
Welche Meldungen stehen im log wenn keine Route gefunden werden kann?
Taucht vielleicht "AutoDrive:dijkstraLiveShortestPath ERROR count > 50000" auf?
Oder kommt dann immer das Popup "Fahrer xy kann keinen Pfad .... finden"?
Ein log kann auch helfen...

**Comment by Dueesberch** [comment]
@Axel32019 Moin,
hier der Log. Dieser ist aber sowohl Error als auch Warning frei. Es kommt immer das PopUp das er keinen Weg finden würde.
Hab zusätzlich mal den mods-Ordner und das Savegame zum testen angefügt.
[log.txt](https://github.com/Stephan-S/FS19_AutoDrive/files/5535188/log.txt)
[AD_test.zip](https://github.com/Stephan-S/FS19_AutoDrive/files/5535187/AD_test.zip)

**Comment by Anonymous-any** [comment]
Hi, yup I saw as well sometime I need to add connections when the vehicle must reach some destination in his back maybe more hard when crossing blue line finished by a white depends...

**Comment by Stephan-S** [comment]
Cleaning up old issues.
