### ISSUE TITLE
Have vehicle return to initial location after program finishes

### ISSUE THREAD

**Issue by mricher-git** [Stephan-S/FS19_AutoDrive#1653]
**Is your feature request related to a problem? Please describe.**  
90% of the time when I want to deliver something, I want to vehicle to return back to where it started. Currently, in delivery mode, once it reaches its destination, we need to change to that vehicle and set the program to bring the vehicle back home.

It's actually currently easier to use CP to do this, because the AutoDrive autogenerated routes include (and return), but AD doesn't offer the same "and return" option that it exposes to CP.

**Describe the solution you'd like**  
A checkbox indicating "Return to initial position" for delivery mode

**Describe alternatives you've considered**  

**Additional context**

**Comment by Iwan1803** [comment]
FYI: on pickup and deliver mode it will return automatically to the pickup location when the job is done.

**Comment by mricher-git** [comment]
Oh ya? Well that's good, my last two attempts I found them just sitting at the deliver locatio, but they hadn't unloaded, due to a different problem (location needed to be pushed out further or something).

**Comment by mricher-git** [comment]
Re-opening. This doesn't solve my issue. I've got a trailer full of sugarcane. I just want to deliver it and have it return. If I pick deliver mode... it won't come back. If I select Pickup and Deliver, and give it the field location or even my silo as the pickup with "Wait for silo" configured for Drive On... it just sits at the pickup location, and won't deliver.

So, I'm still asking for the pure delivery mode to have an option for return, so when I offload a combine of any time, I can just send it to market, and have it return to the field.

**Comment by Axel32019** [comment]
@mricher-git Have you tried with the setting "Unload fill level" less the full, i.e. 10%? Then it will deliver if this level is reached.

**Comment by Axel32019** [comment]
@mricher-git Any update?

**Comment by mricher-git** [comment]
Yes, it's working as you described. The solution I have adopted is to use pickup and deliver and then immediately hit continue so that it skips directly to the delivery leg and then comes back.
