### ISSUE TITLE
[Feature Request] Cover bzw. Planensteuerung

### ISSUE THREAD

**Issue by andreasthu** [Stephan-S/FS19_AutoDrive#1654]
**Is your feature request related to a problem? Please describe.**  
Könnte man in AD such eine art Planensteuerung einbauen wie in CP?

**Describe the solution you'd like**  
Also mit automatisch oder manuell Abdeckung öffnen bzw schließen. 

**Describe alternatives you've considered**  

**Additional context**  

Lg
Andreas

**Comment by Mike1977** [comment]
OMG ich hasse es wenn AD immer die Planen der Anhänger schließt und ich nich mit dem Drescher hinfahren und abtanken kann zum Schluss. 
Ich würde es sehr begrüßen, wenn es in den Settings einen Schalter dafür gäbe, umd dieses Verhalten ein/aus schalten zu können...

**Comment by Axel32019** [comment]
@andreasthu @Mike1977 Wenn Interesse hier entlang: #1663

**Comment by andreasthu** [comment]
Spitze, cool, danke.
Kann das Angebot aber leider erst nächste oder übernächste Woche annehmen.
Aber dann gerne.
Wurde diese Woche an der Wirbelsäule operiert und liege noch einige Zeit nutzlos herum.
Nichtmal Erlengrat hab ich schon besuchen können.
Lg
Andreas

**Comment by Iwan1803** [comment]
Da in 1.1.0.6 enthalten -> geschlossen 😎
