### ISSUE TITLE
Driver does not leave on Dediserver.

### ISSUE THREAD

**Issue by Biebe83** [Stephan-S/FS19_AutoDrive#1655]
AutoDrive Version: 1.1.0.4
Release or selbsterstelltes zip: Release
Karte (falls relevant): Irgentwo in Thüringen
Fahrzeug(art) (falls relevant):

**Beschreibe den Bug
Der Abfahrer fährt nicht zum Drescher abtanken obwohl das Feld am Drescher und Abfahrer das gleiche ist. Es steht immer Blocking beim Abfahrer. Im Singelplayer funktioniert es. Die Strecken abfahren klappt alles nur der Abfahrer auf den Feld nicht. Könnte es an der Version liegen?
**Falls anwendbar - Schritte mit denen ich den Bug nachstellen kann**

**Screenshots**
Falls relevant, bitte Screenshots beifügen

**Comment by Axel32019** [comment]
@Biebe83 Hallo,
Die Version 1.1.0.4 ist nicht gerade Dedi-tauglich, bitte die aktuelle Version 1.1.0.5-RC6 verwenden. Da haben wir viel für Dedi gemacht! 
Siehe hier: https://github.com/Stephan-S/FS19_AutoDrive

**Comment by Biebe83** [comment]
Danke für die Info. MFG

**Comment by Axel32019** [comment]
Wenn OK, dann darfst Du hier gerne schließen :-)

**Comment by Biebe83** [comment]
Bei mir zeigt es den Fehler auf dedi an. Fehler: Die Dateianzahl pro Store-Element ist zu hoch. Gefunden 272 (max. 128) Hat das eine auswirkung das der Server nicht startet weil bei uns startet er nicht mehr. Irgentwas mit der Serverlog.

**Comment by Biebe83** [comment]
Keine Ahnung woran es liegt, am AD wohl nicht. Hab es mal deaktiviert und sogar die kurse aus dem savegame genommen und er startet nicht. Müssen wir wohl mal beim Support melden.

**Comment by Axel32019** [comment]
@Iwan1803 Das hattet ihr doch auch mal, oder?

**Comment by Biebe83** [comment]
Also unser Server läuft wieder nach neu installation. Aber das mit den Abfahrer geht immer noch nicht auch bei 1.1.0.5 RC6.

**Comment by Axel32019** [comment]
Abfahrer finden auf Nein gestellt?

**Comment by Iwan1803** [comment]
Das mit der Anzahl an Dateien hatten wir auch, aber deswegen ist der Server nicht abgekackt. Er meckert es zwar an, aber funktionieren tut trotzdem alles.
"Blocking" klingt nach VehicleExplorer oder ähnlichem, wobei das immer da steht, wenn der Abfahrer auf den Ruf wartet.
Was sagt denn AD selber? Warte auf Ruf, Berechne Pfad, ...? Ist beim Drescher in den AD-Drescher-Einstellungen "Abfahrer finden" auf "Nein" gestellt (wie Axel schon schrieb)?

**Comment by Biebe83** [comment]
Also im AD steht warte auf Ruf. Er fährt auch nicht los wenn man auf 60 prozent früher rufen stellt. Was sollte den eingestellt sein? Bei Drescher Einstellung auf Abfahrer finden "Ja" oder "Nein"?

**Comment by Iwan1803** [comment]
Stell es auf "Nein" und versuch es damit.

**Comment by Biebe83** [comment]
Also wir haben jetzt nochmal alles geprüft und sämtliche Einstellungen versucht auch abfahrer auf nein gestellt.  Der fährt einfach nicht los und im SP funktioniert es aber. Wir haben auch kein VehicleExplorer drauf.   Wir verzweifeln schon.

**Comment by Iwan1803** [comment]
Aktualisiert bitte mal auf 1.1.0.6 und probiert es dann erneut.

**Comment by Biebe83** [comment]
Hab Aktualisiert auf 1.1.0.6 und er fährt immer noch nicht los. Es steht weiterhin "Warte auf Ruf". Hab auch schon 10 min. gewartet. Passiert nix.

**Comment by Axel32019** [comment]
Bitte mal Screenshots von Ernter, Abfahrer und die AutoDrive..config.xml (umbenannt in .txt) hier anhängen.

**Comment by Iwan1803** [comment]
"Warte auf Ruf" heißt genau das, was die Meldung aussagt: er wartet darauf, vom Drescher gerufen zu werden.
Meine AD-Einstellungen vom Drescher:
![image](https://user-images.githubusercontent.com/47528836/100638623-8786b380-3334-11eb-915c-083430438786.png)
In AD stelle ich für den Drescher einfach den Fahrmodus ein und als Ziel das gleiche, was der Abfahrer auch hat (z.Bsp. "Feld 10 Abfahrer"), aber starte AD nicht.
Wenn du den Drescher selber fährst, dann brauchst du eine Tastenkombi, um den Drescher zu rufen NACHDEM das Rohr vollständig ausgefahren ist. Die Tastenkombi ist nicht vorbelegt und heißt in den Einstellungen "AD: Abfahrer rufen".
Fährt der Drescher per Giants-Helfer, AIVE oder CP, dann rufen diese den Abfahrer von alleine.

**Comment by Biebe83** [comment]
Danke Danke Danke. Es funktioniert jetzt über CP. Das wäre meine nächste Frage gewesen warum er nicht losfährt wenn ich selber den Drescher fahre. Das habt ihr ja jetzt schon beantwortet. Danke nochmal. Schöne Weihnachten und rutscht gut ins neue Jahr.

**Comment by Iwan1803** [comment]
Super, freut mich wenn es nun klappt. Dann mach ich hier mal zu und wünschen wir natürlich auch.
