### ISSUE TITLE
 No further travel after unloading[BUG]

### ISSUE THREAD

**Issue by Froym92** [Stephan-S/FS19_AutoDrive#1657]
AutoDrive Version: 1.1.0.4/5   
Release or selbsterstelltes zip: Release
Karte (falls relevant): Alle
Fahrzeug(art) (falls relevant): Alle

**Beschreibe den Bug**
Nach dem mein Abfahrer vom Feld Richtung Silo fährt lädt er am Silo ganz normal ab aber bleibt dann stehen und fährt nicht weiter zum Feld.
Das selbe Problem habe ich auch wenn ich von Silo zu Silo liefere oder an Verkaufspunkten was verkaufe.
Vorher hat alles super geklappt nur seit gestern klappt nix mehr. 
ist auch nicht meine erste Map mit Autodrive 

Edit: Ich habe die Version 1.1.0.4 versucht und die Version 1.1.0.5 RC

**Falls anwendbar - Schritte mit denen ich den Bug nachstellen kann**
Kurs von Silo zu Verkaufspunkt kurz hinterm Trigger ein Zielpunkt setzen und Kurs zurück

**Screenshots**
Falls relevant, bitte Screenshots beifügen

**Comment by dziuch** [comment]
I have the same issue. Tested extensively and found out it's because of the Alpine Farming DLC. If you disable it when selecting the mods there's no such problems.

**Comment by Froym92** [comment]
I also noticed that it's only been since yesterday.
I almost thought it was because of that, but I've heard of a case since it was before the DLC.

**Comment by Froym92** [comment]
it works. simply deactivate the dlc.

**Comment by dziuch** [comment]
That's not a solution. AutoDrive must be fixed. Please reopen the issue.

**Comment by Iwan1803** [comment]
Try the latest AD version (1.1.0.5-RC6) and try again as we don't support older versions.
The download can be found at the bottom of the github page.

@dziuch 
Buy us the DLC and also pay the time we are working on AD as we don't **must** fix anythin, but maybe we can do it if we have time in our free time.

**Comment by morpheuz87** [comment]
@Iwan1803 : I tested this with RC6 and its the same problem, see following link to your dc
https://discordapp.com/channels/640957956027973633/690252595700302195/776594744754438194
i just didnt open an issue yet, tested some stuff before I bug you guys.

**Comment by dziuch** [comment]
@Iwan1803 I have codes for the DLC for you and rest of dev team. Respond to my invite on Steam (my username on Steam is different).

**Comment by dziuch** [comment]
OK, I investigated further and found the issue. It appears that the Alpine DLC changes the fillType's numbers (I think they added electricity for the electric tractors). For example: without DLC diesel has number 32 and with the DLC - number 33 thus breaking the calculation of the fillLevel of the tractor+trailer combo.

I fixed it by changing the line 298 in `scripts\Utils\TrailerUtils.lua` from
`if (fillType == 1 or fillType == 34 or fillType == 33 or fillType == 32) then --1:UNKNOWN 34:AIR 33:AdBlue 32:Diesel`
to
`if (fillType == 1 or fillType == 35 or fillType == 34 or fillType == 34) then --1:UNKNOWN 35:AIR 34:AdBlue 33:Diesel`

But this will only work when you have DLC enabled and it'll break again when you disable it. Also I don't know if there are more places in the code that reference those fillType numbers.

**Comment by Iwan1803** [comment]
Regular keys? Nice, but sorry, i'll ignored your request on steam as i didn't know that it was you.

@Axel32019 
Seems like Giants has changed something for the ids.

**Comment by dziuch** [comment]
@Iwan1803 Currently Steam has some kind of error when I try to resend the invite. I'll try later.

Also I think/hope I fixed the issue. I'm preparing PR at the moment.

**Comment by iljarogoff** [comment]
Tried this fix, does not work for me. Stops at selling point and not driving further

**Comment by Clay80** [comment]
hi guys, I wanted to know if someone can explain me how to fix this problem .. thanks

**Comment by Iwan1803** [comment]
@Clay80 maybe take a little look at the pinned issues....

**Comment by Iwan1803** [comment]
Please update to the latest version 1.1.0.6
