### ISSUE TITLE
Seeds fill type not showing anymore after Farming Simulator update. [BUG]

### ISSUE THREAD

**Issue by masneoquil** [Stephan-S/FS19_AutoDrive#1658]
**AutoDrive Version:** 1.1.0.5 RC6  
**Release or Custom Zip:** Release  
**Map (If applicable):** All  
**Vehicle / Type (If applicable): All
**Multiplayer or Singleplayer:** Singleplayer  

The seeds fill type not showing anymore on the list of fill types for any tool that accepts seeds. It started yesterdays, with the FM update. Don't know if any other fill type is not showing.

**Comment by masneoquil** [comment]
I just also found out that Herbicide is also missing

**Comment by Iwan1803** [comment]
FM update?

**Comment by Speedyls19** [comment]
After FM update i have same problem

**Comment by masneoquil** [comment]
@Iwan1803  Farming Simulator update. It has an update due to the newest DLC.

**Comment by Iwan1803** [comment]
I,m on the latest update and got no problems. Are you using the Alpine DLC?

**Comment by masneoquil** [comment]
@Iwan1803 Yes I am. Could that be the problem? I'll test it

**Comment by masneoquil** [comment]
Confirmed! Without the Alpine DLC, the fill types are showing again.

**Comment by Iwan1803** [comment]
Maybe you should try the latest beta: https://github.com/Stephan-S/FS19_AutoDrive/issues/1663

**Comment by masneoquil** [comment]
I can confirm that the issue is resolved with the RC7 Beta.

**Comment by Iwan1803** [comment]
Please update to the latest version 1.1.0.6
