### ISSUE TITLE
Course Init config for Map

### ISSUE THREAD

**Issue by Kartikai** [Stephan-S/FS19_AutoDrive#166]
i have a Estancia Lapacho course build for init_config if you want.
I could build other if you want for all map.
[AutoDrive_Estancia_Lapacho_init_config.zip](https://github.com/Stephan-S/FS19_AutoDrive/files/3237150/AutoDrive_Estancia_Lapacho_init_config.zip)

**Comment by Bandesss** [comment]
Hello can you make for the Map HofBergmann ?

Thanks for you Help

**Comment by Stephan-S** [comment]
Hey, thank you for your submission.
But since all your waypoints are in french, I will not add them to this repository. But feel free to post your file over here:
https://www.reddit.com/r/farmingsimulator/comments/byvx0t/autodrive_road_networks/

Best regards,
Stephan
