### ISSUE TITLE
Autodrive Editor

### ISSUE THREAD

**Issue by N3kr0E** [Stephan-S/FS19_AutoDrive#1661]
Hallo,

gibt es seit der neuesten Version keine zwei Editor-Stufen mehr?
Ich hatte bis vor kurzem noch die Vorgängerversion und dort gab es zwei verschiedene Editor Modi.

Im ersten habe ich "nur" die Linien gesehen, im zweiten dann auch auch die entsprechenden Wegpunkte.
Nun sehe ich entweder gar nichts oder direkt die Linien inkl. Wegpunkte.
Auch die Funktion, einen Wegpunkt mit (ich glaube es war) STRGL und LMB zu löschen, finde ich nicht mehr.
Habe ich irgendwas in den Einstellungen übersehen?

LG N3kr0e

**Comment by Iwan1803** [comment]
Schau mal hier rein: https://github.com/Stephan-S/FS19_AutoDrive/wiki/Edit-Mode

**Comment by N3kr0E** [comment]
Danke Iwan1803!
Das hat mir weitergeholfen 👍 
Hier kann somit dicht gemacht werden
