### ISSUE TITLE
Was mache ich Fasch?

### ISSUE THREAD

**Issue by RudiBergfeld** [Stephan-S/FS19_AutoDrive#1662]
*Hallo,
AD findet sein Ziel nicht was mache ich falsch
![fsScreen_2020_11_14_12_25_28](https://user-images.githubusercontent.com/10323527/99146158-d31f3900-2675-11eb-853f-eed79fb1ffaf.png)
[log.txt](https://github.com/Stephan-S/FS19_AutoDrive/files/5540594/log.txt)
**   
I've got a question...

**Comment by Axel32019** [comment]
@RudiBergfeld Hallo,
1. Du hast Dir die beta-Version herangezogen -> kein Support, da immer in Arbeit, muß nicht funktionieren usw.
2. Fahrzeug ist schon am Ziel
