### ISSUE TITLE
BETA Test - How to

### ISSUE THREAD

**Issue by Axel32019** [Stephan-S/FS19_AutoDrive#1663]
Helllo,
This is how to test the actual Beta Version of AutoDrive. 
Hier die Anleitung wie man die Beta-Version vorab testen kann.

**Before you start / Unbedingt vor Beginn beachten!
Make a backup-Copy of the savegame you want to test with AutoDrive BETA !!!
Mach eine Sicherung des savegame in welchem Du AutoDrive BETA testen willst !!!**

To get the BETA: 
Wie bekommt man die BETA:

https://github.com/Stephan-S/FS19_AutoDrive/tree/beta-testing

Code -> Download ZIP
Extract the downloaded zip "FS19_AutoDrive-beta-testing.zip"! Do not put it into the mod folder, this will not work !!!
In the extract you find the folder "FS19_AutoDrive" -> zip and put to mod folder -> the zip must have the name "FS19_AutoDrive.zip" -> start the game

Code -> Download ZIP
Die herunter geladene zip-Datei "FS19_AutoDrive-beta-testing.zip" auspacken! Nicht in den mod Ordner verschieben/kopieren, das funktioniert nicht !!!
In der entpackten Datei den Ordner "FS19_AutoDrive" neu als zip packen -> zip in mod Ordner kopieren -> Die zip-Datei muss "FS19_AutoDrive.zip" heißen ->  Spiel starten

**Comment by Axel32019** [comment]
**Vehicle-specific settings: / Fahrzeugspezifische Einstellungen:**

Park at Job finished
Only available in Modes Pickup and Deliver, Deliver: If Job is finished, stored parking position of vehicle / attachment will be driven to. On Dedi-Server only available for vehicle parking place!

Am Ende Parken
Nur in Modi Abholen und Abliefern, Abladen: Wenn Aufgabe beendet, wird die gespeicherte Parkposition des aktuell gewählten Fahrzeug / Anhänger / Anbaugerät angefahren. Auf Dedi-Servern nur für Fahrzeug-Parkplatz!

Automatic Tip Side
Yes - AutoDrive select tip side automatically / No - the already selected tip side will be used

Automatische Abladeseite
Ja - AutoDrive wählt Abladeseite automatisch / Nein - die gewählte Abladeseite wird verwendet

Automatic Trailer Covers
Yes - AutoDrive open and close trailer covers as needed / No - trailer covers will not be opened or closed by AutoDrive

Automatische Abdeckungen
Ja - AutoDrive öffnet und schließt Abdeckungen von Anhängern wenn notwendig / Nein - die Abdeckungen werden von AutoDrive nicht geöffnet oder geschlossen

Beacon lights
Yes - Use beacon lights automatic outside of fields / No - beacon lights will not be turned on or off automatically

Rundumleuchten
Ja - Außerhalb des Felds automatisch eingeschaltet / Nein - Rundumleuchten werden nicht automatisch ein- oder ausgeschaltet

**Overall / Allgemeines:**
Map Name removed - New always: AutoDrive_config.xml
Kein Karten-Name mehr in der config, jetzt immer: AutoDrive_config.xml

Mark previous and next points of selected one with another color -> mouse-over waypoint, pink=previous waypoint, yellow=next waypoint
Wegpunkte für Vorwärts- und Rückwärtskurse unterscheiden -> Mauszeige ohne Klick auf Wegpunkt bewegen, Pink=vorheriger Wegpunkt, Gelb=nächster Wegpunkt

HUD:
open and close folders by click on folder name
Ordner öffnen und schließen durch Anklicken des Ordners

Alpine DLC support

**Comment by Iwan1803** [comment]
**IMPORTANT / WICHTIG**
Wer ein Problem oder einen Fehler findet, öffnet bitte ein Issue und vermerkt bitte im Titel, das es sich um die Beta-RC handelt, danke!
If you find a problem or an error, please open an issue and note in the title, that it is the beta RC, thank you!
