### ISSUE TITLE
[BUG] Beta RC - park place problem

### ISSUE THREAD

**Issue by Anonymous-any** [Stephan-S/FS19_AutoDrive#1664]
**Question:**   
I don't know where that happen but when I try to go to another park place, the game hang without log error... I must kill the game...and it redo the same thing... I tried to disable Alpine dlc to exclude it so it's the same ...continuing investigate

**Comment by Anonymous-any** [comment]
I really hope this is not linked to this https://github.com/Stephan-S/FS19_AutoDrive/issues/1582 where it was literally the war @Mike1977 ?
And hope too this will never merge into the public master...

**Comment by Axel32019** [comment]
@Anonymous-any Hello,
Could you please post the AutoDrive_config.xml and vehicles.xml?

**Comment by Anonymous-any** [comment]
Hi np I forgot I was copy 2 same park in 2 different folder I hope this not the culprit...I've not tested to remove them.
[AutoDrive_config.xml.txt](https://github.com/Stephan-S/FS19_AutoDrive/files/5543261/AutoDrive_config.xml.txt)
[vehicles.xml.txt](https://github.com/Stephan-S/FS19_AutoDrive/files/5543262/vehicles.xml.txt)
Br

**Comment by Axel32019** [comment]
@Anonymous-any Hi Ano,
There are 2 cases where 2 different targets pointing to the same waypoint - which should be impossible to generate.
So at the moment I am not sure if this situation is caused by the BETA or was already in the config before.
I hope you made a backup before running the BETA!
It would be helpful if you can post the config from the backup as well!
BR

**Comment by Anonymous-any** [comment]
Hi @Axel32019 ,

Yes Alex, ! I'm not sure I made myself understood about the "2 different targets pointing to the same waypoint - which should be impossible to generate" you say me. Yes I know because "I made it" !
I said I was forgot to say you I have made myself copy of 2 destination in 2 folder you know for make 2 different job like delivery animals hay and straw folder :) I hope it's better clear I never would say the Beta cause this !! do not mix :) (my bad english).

Ok for now I got new investigation which makes me understand less and less...it is complicated for me.
I write this in same time of my steps I try to solve for explain I'm confusing OMG ! my fault it seem somewhere...<s>Maybe I found a BUG like the tittle say.</s> This issue is somewhere from my route file. I have to back from date 13.11 (a bit less wp) but no issue with Beta so...I must add to say too there few days ago I remember, I tried to switch btw the beta versions and save without pay attention to that can cause issues, but to thinking now it's really not a good thing to do !!
So my steps:

- Tried to remove inside copy of (folders waypoints the route file you know by the 2 way from import file and in savegame file from bad files) then It was the same issue hanging the game. <U>So that is cannot the copy of 2 wp/folders made be the culprit.</U>
- Tried the 1.1.0.5-RC6 and his old date 11.11.20 file config that work fine ! but I've no modded the file (no copy folders/2 wp). Less less wp :/
- Tried this same old route import with the Beta this work fine but it does not import the folders maybe linked to the click folder option idk (so it's a problem with my route file finally not the Beta !).
- Tried with a file it already has the 2 copy wp/folder from date 13.11.20 it work with Beta. (so I think it's confirmed that a route file issue not the Beta bug so ?) a bit more wp from the one above...<U>So that is cannot the copy of 2 wp/folders made be the culprit.</U>

So I give you both: the buggy and the good but so sorry idk why I Failed bug. I will close this for not tired you.
The name converted from date 13.11 with Beta:
[AutoDrive_config_Le13betaOk.xml.txt](https://github.com/Stephan-S/FS19_AutoDrive/files/5549175/AutoDrive_config_Le13betaOk.xml.txt)
And the bad from my shit made Beta switch's:
[AutoDrive_config.xml.buggy.txt](https://github.com/Stephan-S/FS19_AutoDrive/files/5549191/AutoDrive_config.xml.buggy.txt)

Please guys don't declare me as disturbs ^^
Sorry again BR

**Comment by Mike1977** [comment]
> 
> 
> I really hope this is not linked to this #1582 where it was literally the war @Mike1977 ?
> And hope too this will never merge into the public master...

First, i don't get why you are referencing me again without any information on why... If you talk about the heated argument between me and @Iwan1803, that should be nothing of your concern. 
Second, why do you repeatedly say you hope this beta "will never merge into puplic master"? I mean, it's the whole idea behind a beta, to test changes befor merging them into the master branch.

**Comment by Anonymous-any** [comment]
Ok absolutely yes I tested it.

**Comment by Anonymous-any** [comment]
Hello the Maestro,
That shit happen me again ! but this time I can't backup I mean I do lots route and change since !! so I to avoid to lost my route work and improvement, it's a 4k map or more ! and continue to use it (fully),  I need to know what is the way to reset all park place only please ? because I can't do that and it's my only way out it seem...I see in vehicle.xml there data's seem liked to this but they have no change from a good backup. So the issue seem come from the config.xml file directly or his encrypted name load backup you know ? because even I load what I saved that not solve the issue...
I hope that help :/

**Comment by Axel32019** [comment]
Hello Ano,
The park positions of vehicles and tools are stored in vehicles.xml. You may search for parkDestination=
Does this help?

**Comment by Anonymous-any** [comment]
Hello Axel :),
Ok yes I saw that.
But because I tried to load backup encrypted I will think there a park storage inside this file too ? how AD can remember where are the park place at loading backup so ?
Ok so I will try to delete the full linked lines this is this the best and safe cleanly remove park attribution so ? or I have to set them to -1 values right ? and re-add park attribution to the concerned vehicles later ingame then... idk

Thanks Al :)
