### ISSUE TITLE
[Question] Bale Delivery?

### ISSUE THREAD

**Issue by jspring0811** [Stephan-S/FS19_AutoDrive#1666]
Does AutoDrive support delivery of bales using the standard or DLC bale movers (RBMPRO 2000, or StackPro)?

I would like to have CP handoff delivery when the stacker is full, deliver/unload, and then return to the field to continue collection.

Thanks!

**Comment by Iwan1803** [comment]
Sorry, no, but maybe you can use CP to do the delivery using the AD routes.
