### ISSUE TITLE
Field Sensor Gras / Feld Sensor Gras

### ISSUE THREAD

**Issue by Rumspringa90** [Stephan-S/FS19_AutoDrive#1667]
Moin,

kann mir jemand erklären, warum beim Feldsensor das Gras direkt ausgeschlossen wird? So werden Felder auf denen Gras angesät ist nicht als Feld erkannt. 
https://github.com/Stephan-S/FS19_AutoDrive/blob/6734da2a2e117332dd2418536b33dcf4792e0e17/FS19_AutoDrive/scripts/Sensors/FieldSensor.lua#L20
Wenn ich den Part "densityType ~= g_currentMission.grassValue" entferne, dann erkennt er auch ein Grasfeld als Feld.

Hat aber bestimmt ein Grund das ihr das da eingetragen habt.

Gruß Henne

**Comment by Axel32019** [comment]
Hallo,
Der Sensor wird dazu verwendet festzustellen ob sich das Fahrzeug auf dem Feld oder daneben befindet.
Felder sind meist von Gras umgeben und nicht z.B. von Kartoffeln, daher wird auf Gras geprüft.
densityType liefert die erkannte Frucht für den Sensor, d.h. auch Straßen, Wege ohne Frucht werden entsprechend erkannt.
Wenn Du eine bessere Möglichkeit kennst wie man Felder sonst erkennen kann, immer her damit - schauen wir uns gerne an!

**Comment by Iwan1803** [comment]
@Axel32019 
CP scannt die Felder ja am Anfang und vielleicht haben die eine Routine, die wir nutzen könnten.

**Comment by Rumspringa90** [comment]
Ich habe dies nochmal weiter getestet indem ich mir einfach mal den densityType in die Log schmeißen lasse.
![image](https://user-images.githubusercontent.com/50840355/99664735-ed3b8b80-2a68-11eb-9035-8dcc7e6ec410.png)
Wenn ich neben dem Feld auf der Wiese bin, gibt er mit den densityType 0 aus. Gras hat den densityType 5.
Hab das auch kurz aufgenommen. https://youtu.be/MB8i8FlAxH0

**Comment by Stephan-S** [comment]
Cleaning up old issues.
