### ISSUE TITLE
[BUG] Drive do not continue to the point he is

### ISSUE THREAD

**Issue by Chico0008** [Stephan-S/FS19_AutoDrive#1668]
**AutoDrive Version:** 1.1.0.5-RC6 - but got this since 1.1.0.5 RC1
**Release or Custom Zip:** Release  
**Map (If applicable):** All  
**Vehicle / Type (If applicable):**   all
**Multiplayer or Singleplayer:** Singleplayer  

**Describe the bug**  
When the driver is going to a point (loading or unloading)
instead of continue from the point he is, he well search a farrer point to continue
on small farm it could be dangerous, are making long detour for nothing
Same when unloading and have several route above, it will often take the wrong one because starting from a farer point instead of where he is

Ex on the screen attached
the driver load Slurry at the point, but instead of taking the green path (shorter to the filed) it il take the red path, continuing from the red circle

Don't know what log can i provide to help

**Screenshots**  
![AD_BUG2](https://user-images.githubusercontent.com/58886243/99427595-e6e0ce80-2905-11eb-9a07-2e2af34a82b6.png)

**Comment by Axel32019** [comment]
If the route continue more in the direction of the green trailer and then turn to the left, it will be catched.

**Comment by Chico0008** [comment]
what do you mean ?
from the loading point, the shortest route to the destination is going to left, but instead it's going to right making a huge detour

**Comment by Axel32019** [comment]
Make the left turn a little bit wider in diameter - so it nearly touch the back of the green trailer in front.

**Comment by Chico0008** [comment]
Added more point, like in  the screen attached
works now, but still
after loading, driver continue to the point (blue circle) and then jump to the green circle to continue, all dots between are ignored, why ? the driver should take dots from the point given, and not jump several dots above

for now it's ok because i have some space, but on small farm it could be bloking

![AD_3](https://user-images.githubusercontent.com/58886243/99557903-78624600-29c3-11eb-9330-8ff76eaaf563.png)

**Comment by Axel32019** [comment]
If you start the right turn at the green circle it will work in any direction.
AD always looks in front of the vehicle, not at the position it stands. This prevent selecting a start point to close and first try to reach this point, which might end up in endless circles...

**Comment by Chico0008** [comment]
It was the case on earlier version of AD, but now it's too far
maybe considering adding a setting, and let the player choose the distance where the driver chose the dot to start from ?

**Comment by Axel32019** [comment]
The approach to start is not changed since many versions. If you make the route as suggested there will be no issue. A special setting is not our plan!

**Comment by Axel32019** [comment]
No further change planned for this -> Closed.
