### ISSUE TITLE
[BUG] Alpine DLC

### ISSUE THREAD

**Issue by betrox007** [Stephan-S/FS19_AutoDrive#1669]
**AutoDrive Version:** 1.1.0.5 RC6
**Release or Custom Zip:** Release  
**Map (If applicable):** All  
**Vehicle / Type (If applicable):**   
**Singleplayer  

**Describe the bug**  
when using farming simulator19 Alpine expansion when using seeder at the autodrive hud, the fill type locked to Diesel, this is not happen at Platinum Expansion farming simulator19
here screen capture from both series, same equipment, same save game, same map.. but different fill type.. so strange..
![fsScreen_2020_11_18_19_06_08](https://user-images.githubusercontent.com/56646850/99532989-b9fcec00-29d7-11eb-9f57-30d90d731f47.png)
![fsScreen_2020_11_18_19_13_06](https://user-images.githubusercontent.com/56646850/99533000-bec1a000-29d7-11eb-8ea6-34ec6d120aef.png)

**If applicable - Steps to reproduce the behavior**  

**Screenshots**

**Comment by Axel32019** [comment]
Hello @betrox007, As you already mentioned - fixed in Beta #1663

**Comment by betrox007** [comment]
yes its solved.. thanks axel

Pada tanggal Rab, 18 Nov 2020 pukul 21.02 Axel32019 <
notifications@github.com> menulis:
