### ISSUE TITLE
Zuweisung von Abladern

### ISSUE THREAD

**Issue by Knowen** [Stephan-S/FS19_AutoDrive#167]
Hallo,

ich habe heute zwei Felder nebeneinander abgeerntet und das Abtanken der Drescher von AD machen lassen, die Feldarbeit von CP.
Damit das überhaupt funktioniert muss man ja auch beim Drescher AD einstellen (Modus, Abfahrort und Lieferort) ohne es letztendlich anzuschalten, damit der Abfahrer durch CP gerufen werden kann. 

Nun kam es mehrfach vor das der angedachte Abfahrer von Feld 1(Weizen, davon schon was in Anhänger) den Drescher von Feld 2 (Gerste) abtanken wollte, nur weil er näher dran war als der eigentliche Abfahrer von Feld 2. Natürlich konnte Drescher 2 nicht abgetankt werden.

Ist es möglich dem Feld/Drescher einen Abfahrer zuzuweisen? Quasi machen wir das schon in dem wir beim Drescher ebenfalls AD einstellen. Kann man ein check einfügen, was beim Drescher eingestellt ist, ohne das AD eingeschaltet ist?

Grüße,
Knowen

**Comment by Stephan-S** [comment]
![findDriver](https://user-images.githubusercontent.com/5493976/58645061-e237ed00-8302-11e9-914c-17f28ec03901.png)

Mit dieser Einstellung kannst du auswählen ob Fahrer anhand der Distanz gefunden werden sollen.
In deinem Fall möchtest du das also ausschalten, dann wird nur nach dem eingestellten Ziel ausgewählt.
Im Drescher musst du übrigens keinen Modus einstellen, nur das Ziel. Alles andere wird hier nicht beachtet :-)

Beste Grüße,
Stephan

**Comment by Knowen** [comment]
Ah, alles klar! Vielen Dank :)
