### ISSUE TITLE
Drescher Erkennung

### ISSUE THREAD

**Issue by Paul2510** [Stephan-S/FS19_AutoDrive#1670]
Kann sein das der Abfahrer den Drescher bei grösseren Feldern z.B. Kernstadt nicht findet oder mach ich was falsch?? LG

**Comment by Mike1977** [comment]
Du machst wahrscheinlich was falsch, denn bei mir fahren die Abfahrer sogar quer über die Map zu einem drescher der mehrere felder weit weg steht, wenn ich vergessen habe dem Drescher im AD Hud ein neues Feld zuzuweisen.

**Comment by Paul2510** [comment]
ok mach ich! Bin Neuling was Auto Drive anbelangt! LG

**Comment by Paul2510** [comment]
![Uploading photo_2020-11-19_18-33-38.jpg…]()

**Comment by Paul2510** [comment]
![photo_2020-11-19_18-33-19](https://user-images.githubusercontent.com/10115244/99702393-00188500-2a96-11eb-80c6-9c337e341fa8.jpg)

**Comment by Paul2510** [comment]
![photo_2020-11-19_18-33-29](https://user-images.githubusercontent.com/10115244/99702424-0b6bb080-2a96-11eb-9c2e-13082af89a8f.jpg)

**Comment by Paul2510** [comment]
![Uploading photo_2020-11-19_18-33-38.jpg…]()

**Comment by Paul2510** [comment]
![photo_2020-11-19_18-37-08](https://user-images.githubusercontent.com/10115244/99702590-453cb700-2a96-11eb-99ea-27322a66f9a0.jpg)

**Comment by Axel32019** [comment]
Hallo @Paul2510 ,
Bitte "Abfahrer finden" auf Nein stellen. Am Abfahrer und Drescher das gleiche Ziel einstellen, für Drescher aber AD NICHT aktivieren!

**Comment by Paul2510** [comment]
Vielen Dank funktioniert!! 
LG
