### ISSUE TITLE
[BUG] Helper choosing wrong course

### ISSUE THREAD

**Issue by Rubenstein2021** [Stephan-S/FS19_AutoDrive#1671]
AutoDrive Version: 1.1.0.5-RC6
Release or selbsterstelltes zip: Release
Karte (falls relevant): Alle
Fahrzeug(art) (falls relevant):

**Beschreibe den Bug**
Ich habe 2 Routen (A+B) programmiert, bei denen der Helfer am Startpunkt beladen wird und am Zielpunkt entlädt.
Route A, ausgeführt mit Wiederholungen, läuft.
Danach Route B, ausgeführt mit Wiederholungen, läuft.
Wenn ich dann erneut Route B aktiviere, fährt der Helfer immer erst Route A einmal ab, kommt zum Startpunkt zurück und fährt dann erst Route B.

**Falls anwendbar - Schritte mit denen ich den Bug nachstellen kann**

**Screenshots**
Falls relevant, bitte Screenshots beifügen

**Comment by Axel32019** [comment]
Hallo @Rubenstein2021,
Ist evtl. Rotieren aktiviert? Ein paar mehr Infos zu den Einstellungen, Screenshots etc. wären hilfreich!

**Comment by Rubenstein2021** [comment]
rotierendes Be- und Entladen ist deaktiviert
Ergänzung zu oben:
Wenn ich nach Route B erneut Route A starte, beläd der Helfer, fährt dann Route A einmal ab ohne zu entladen (also genau wie oben), und beginnt dann mit Route A wie geplant.

**Comment by Rubenstein2021** [comment]
![fsScreen_2020_11_19_22_22_48](https://user-images.githubusercontent.com/74567994/99727556-762de380-2ab8-11eb-9959-1812448dd041.png)

**Comment by Axel32019** [comment]
@Rubenstein2021 Bitte mal ein paar Screeshots der beiden Ziele der beiden Routen anhängen - mit o.g. komme ich nicht weiter.

**Comment by Rubenstein2021** [comment]
Der Beladepunkt war ein Wasserrohr aus dem Modhub.
Der erste Entladepunkt ist oben auf dem Screenshot zu sehen. Es ist der Befüllpunkt dieser Dirtwash-Anlage.
Der zweite Entladepunkt war der Befüllpunkt der zweiten Dirtwash-Anlage auf dieser Map unweit davon.

Gespielt wurde auf der Map Yukon River Valley v1.1.
Fahrzeug war der Case 1455 aus dem Modhub mit dem Giants Standard Wasseranhänger Joskin 7500 l.
Es wurde zuerst der Kurs A programmiert (Sreenshot oben), dann Kurs B daran angehängt.

Weitere Screenshots kann ich leider mehr nicht liefern, der Spielstand wurde bereits gelöscht.
Außerdemkam ja kurz danach eine neuere Version von Autodrive, mit der ich momentan spiele.
Wenn ich diesen Vorgang nochmal erlebe, melde ich mich wieder, auch mit mehr Screenshots.

Dnke für die ganze Mühe, die ihr euch macht, und das tolle Programm.

**Comment by Axel32019** [comment]
Da nicht mehr nachvollziehbar -> Closed.
