### ISSUE TITLE
[BUG] AD Conflict with last DLC Alpine ?

### ISSUE THREAD

**Issue by Chico0008** [Stephan-S/FS19_AutoDrive#1672]
**AutoDrive Version:** 1.1.0.5-RC
**Release or Custom Zip:** Release  
**Map (If applicable):** All  
**Vehicle / Type (If applicable):**   all
**Multiplayer or Singleplayer:** Singleplayer  

**Describe the bug**  
When i activate the last DLC (Alpine) on a map, i can't select anymore Seeds nor Herbicide in AD menu to load my device or trailers
If i deactivate the DLC, all is fine, if i activate it back on, seeds/herbicide no more selectable in list

**Comment by Iwan1803** [comment]
Is the search function so hard to find or use?
Check the pinned issue: https://github.com/Stephan-S/FS19_AutoDrive/issues/1663

**Comment by Iwan1803** [comment]
Please update to the latest version 1.1.0.6
