### ISSUE TITLE
[BUG] Alpine DLC

### ISSUE THREAD

**Issue by MisterFister2016** [Stephan-S/FS19_AutoDrive#1673]
**AutoDrive Version:** v1.1.0.0 via ModHub in-game portal, isssue persists across manual upgrades to both v1.1.0.4 and 1.1.0.5-RC6
**Release or Custom Zip:** Release  
**Map (If applicable):** [MVP-19 FA Edition], not yet tested to attempt to reproduce on other maps
**Vehicle / Type (If applicable):**   Issue at first gameload of FS19 client-session
**Multiplayer or Singleplayer:** Singleplayer  

**Describe the bug**  
Gameload from save freezes, Sometimes this partially prevents alt tabbing (control-focus can be shifted to another open process, but the FS19 loading screen is still stuck on the screen) and sometimes alt-tabbing is fully allowed.  When alt-tabbing is fully allowed, FS19 game client does respond to alt+F4, which was used to generate log.txt attached.  I have no programming ability to speak of, but the last line of log.txt indicates that the client froze during gameload because of a failed if/then argument comparison in [mod_zipfile]\scripts\Specialization.lua:156, also attached.
[Specialization_dot_lua.zip](https://github.com/Stephan-S/FS19_AutoDrive/files/5578344/Specialization_dot_lua.zip)

**If applicable - Steps to reproduce the behavior**  
I am tentative to speculate that this primarily (maybe exclusively) takes place on the first gameload attempt of the Windows desktop session.

**Screenshots**  
A tentative workaround 
[log.txt](https://github.com/Stephan-S/FS19_AutoDrive/files/5578339/log.txt)

is to first load the save WITH AUTODRIVE SUPPRESSED, save the game again, exit the save, and re-attempt to load the savegame again but this time with all mods enabled including AutoDrive.  Apparently, loading the save with AutoDrive running "for the first time" seems to prevent this particular conflict.

**Comment by Iwan1803** [comment]
Alpine DLC? If yes: https://github.com/Stephan-S/FS19_AutoDrive/issues/1663

**Comment by Iwan1803** [comment]
Please update to the latest version 1.1.0.6
