### ISSUE TITLE
Not able to create two way route [Question]

### ISSUE THREAD

**Issue by taffybach** [Stephan-S/FS19_AutoDrive#1675]
**Question:**   
Hi,
I am trying to create a two way route, but when I right click on the record button, I only get the one way route symbol. I have deleted all the right click settings in the keybinding, with the exception of record route.

Can you help please? Bigtaff

**Comment by Iwan1803** [comment]
Which AD-version are you using?
Right click on the record button is the way to record 2 way lines (dark blue).

**Comment by taffybach** [comment]
I have got it working now, uppgraded from 1.1.04 to 06, also found another key bind that was conflicting

Thanks, Bigtaff
