### ISSUE TITLE
Autodrive 1.1.0.5

### ISSUE THREAD

**Issue by OstseeFarmer** [Stephan-S/FS19_AutoDrive#1677]
Hi habe die Version 1.1.0.5-6 vom Autodrive. Funktioniert soweit auch ganz gut. Mein Problem ist nur dass immer nach einem Restart des Games alle Einstellungen zurückgesetzt werden. Gibt es da eine Lösung?

**Comment by rmn18** [comment]
versuch mal diese vers. 1.1.0.6

**Comment by rmn18** [comment]
versuche mal diese Vers. 1.1.0.6

**Comment by OstseeFarmer** [comment]
Habe 1.1.0.6 runtergeladen aber kann es nicht installieren

**Comment by 60erjonny** [comment]
Hallo

Installieren musst du da nicht !
Alte Version löschen und neue Verison in den Mod-Ordner kopieren und alles ist gut...
Oder wo ist das Problem ?

**Comment by Iwan1803** [comment]
Einfach für den Download einen der Button unten auf der Startseite vom AD-github benutzen, die ZIP in den mods-Ordner speichern und eine vorhandene ZIP überschreiben.
Am besten auch mal prüfen, ob nicht mehr AD-ZIPs da liegen.

**Comment by OstseeFarmer** [comment]
Hab jetzt die 1.1.0.4 mit der neuen 1.1.0.6 überschrieben aber im Modordner wird mir trotzdem die 1.1.0.4 angezeigt

**Comment by Iwan1803** [comment]
Im Ingame-Modhub vielleicht, aber was steht in der Mod-Übersicht, wenn du einen Spielstand starten möchtest?

**Comment by OstseeFarmer** [comment]
Auch nur 1.1.0.4

**Comment by Iwan1803** [comment]
Dann behaupte ich jetzt einfach mal, das du mehrere AD-Dateien oder -Ordner noch im mods-Ordner liegen hast.
Das solltest du noch mal ganz genau kontrollieren.

**Comment by OstseeFarmer** [comment]
Ok das mache ich mal. Danke

**Comment by Axel32019** [comment]
Nicht neues -> Closed.
