### ISSUE TITLE
[BUG] Autodrive courses are solved in the savegame folder

### ISSUE THREAD

**Issue by Zimty86** [Stephan-S/FS19_AutoDrive#1679]
AutoDrive Version: 1.1.0.6
Release or selbsterstelltes zip: Release
Karte (falls relevant): Alle
Fahrzeug(art) (falls relevant):

**Beschreibe den Bug**
Wenn ich Autodrive Kurse im Savegame Ordner kopiere (zb, in savegame1) sind in der Map die kurse nicht da,
auch wenn ich welche erstelle und das Spiel Speichere,
ist die autodrive xml mit den kursen gelöscht.

ich benutze die aktuelle LS Patch und alle DLC

**Screenshots**
Falls relevant, bitte Screenshots beifügen

**Comment by Iwan1803** [comment]
Du hast die Release Notes nicht gelesen, oder?
https://github.com/Stephan-S/FS19_AutoDrive/wiki/Release-Notes#changelog-for-release-1106-22112020

> ADDED: map name removed for the config file, now will be always: AutoDrive_config.xml
> - the previous map config will be read and on 1st save then converted automatically
> - in the new format the map name will no longer be evaluated, but as info at the beginning of config file written in the tag MapName

Wenn du eine Config im alten Format hast, dann kopier sie ins Savegame und lösch die AutoDrive_config.xml falls vorhanden. Starte anschließend das Spiel und die Strecken & Zielpunkte sollten vorhanden sein.
Beim ersten Speichern wird dann automatisch die alte in die neue Config überführt.

**Comment by Axel32019** [comment]
@Zimty86 Hallo,
Bitte die log.txt und AutoDrive_config.xml in .txt umbenennen und hier hochladen.

**Comment by RicciM-CZ** [comment]
Hey guys, my German is poor but GTransl shows me this thread is what I´m looking for...I have same problem Zimty faces into. Currently with Porta_Westfalica map. I´ve read and did what Iwan1803 recommended and more with AD config files but all failed. I understood from Stephan-S´ changelog AD1106 should deal with "mapped-named" config files well but it seems to me not with Porta_Westfalica. Attaching my config.txt file. Result of the situation is AD is unable to entitle new points, unable to change HUD setting and perhaps more. On the other hand Porta_Westfalica is only the second map I´ve meet same issue ( also Canadian production ), other maps work well with AD.... 
[AutoDrive_config.txt](https://github.com/Stephan-S/FS19_AutoDrive/files/5679285/AutoDrive_config.txt)
Well, thanks for focusing and cheers!

**Comment by Axel32019** [comment]
Keine Rückmeldung -> Closed.
