### ISSUE TITLE
[BUG] Java Editor kann die neuen Autodrive_config.xml nicht mehr speichern

### ISSUE THREAD

**Issue by rellek010682** [Stephan-S/FS19_AutoDrive#1680]
AutoDrive Version: 1.1.0.5 RC7 Beta + 1.1.0.5   
  Map (If applicable):All     
 Singleplayer  
Beim Bearbeiten der neuen Autodrive_config.xml- Dateien ohne den Kartennamen mit dem Java-Editor ist mir aufgefallen, dass der Editor zwar die Datei mit den Kursen öffnet und man sie auch bearbeiten kann, jedoch kommt beim Speicherversuch eine Fehlermeldung: "The AutoDrive Config could not be saved" .
Kann es sein, dass der Java-Editor mit den neuen Dateinamen nicht zurecht kommt?

**Comment by betrox007** [comment]
you still can edit with ad course editor.. copy the Autodrive_config.xml you want edit to what ever folder you want it, then rename for example AutoDrive_FS19_Elergrant_config.xml the open with ad course editor edit it and save.
after finish editing the course then rename it to autodrive_Cofig.xml and put to your save game folder.. CMIIW
