### ISSUE TITLE
improved tractor tracking during silage harvesting

### ISSUE THREAD

**Issue by Crinouche** [Stephan-S/FS19_AutoDrive#1681]
Hello,
First of all thank you for your mod which is great. I use it to do all my freight transport. I use Couseplay for work in the fields and crops combined with AD, even for silage (as in the photo) I still use the AD 1105 RC6 version, because the 1106 version is bugging my game.

But my request is different:
Would it be possible to improve the tracking of tractors next to forage harvesters, especially at the end of the field during back and forth maneuvers. On photo 1, the tractor waits for the forage harvester to turn and takes a long time to reposition itself next to it. In photo 2, as the tractor positions itself next to the forage harvester, it reverses, stops and comes back to the side of the forage harvester after a while. On photo 3, these are my settings.
I would like there to be more fluidity in the maneuvers of the tractor. Is it possible?
thank you,
![Photo 1](https://user-images.githubusercontent.com/36656729/100135447-eefeb800-2e89-11eb-873a-7133e6be2aad.png)
![Photo 2](https://user-images.githubusercontent.com/36656729/100135462-f58d2f80-2e89-11eb-98a6-c42326f5e960.png)
![Photo 3](https://user-images.githubusercontent.com/36656729/100135478-faea7a00-2e89-11eb-8d0c-15f58db4d670.png)

**Comment by Iwan1803** [comment]
-5.0m to the pipe and 3.5m behind?
Remove the front weight as this could cause problems.

**Comment by Crinouche** [comment]
-5.0 m from the pipe, otherwise the tractor is positioned too far from the forage harvester when it rolls alongside
3.5 m behind, otherwise the tractor will run into the forage harvester as it follows behind.
I have tried several settings, with different forage harvester front cuts, and this is the setting that works best.

I will try without the weights in front, but I'm not sure that will change much.
thanks anyway

**Comment by Axel32019** [comment]
no update -> closed
