### ISSUE TITLE
[Question] Vehicle Requirements to use autodrive

### ISSUE THREAD

**Issue by dozerjz** [Stephan-S/FS19_AutoDrive#1682]
**Question:**   
I've got a question...
Hello, I am trying to get a modded vehicle to work with autodrive... can you tell me what a vehicle needs to work?  I have tried to copy other vehicles with no luck.  Here is the download to the vehicle in question...

https://mega.nz/file/2vpRFabQ#vTD_Yp6rX33iycbJREmGbrFIrbnFARo-zi6xi65xWw0

**Comment by Axel32019** [comment]
Hello @dozerjz May be this helps:
SpecializationUtil.hasSpecialization(AIVehicle, specializations) and SpecializationUtil.hasSpecialization(Motorized, specializations) and SpecializationUtil.hasSpecialization(Drivable, specializations) and SpecializationUtil.hasSpecialization(Enterable, specializations)
