### ISSUE TITLE
Ablade kurs wechselt selbständig

### ISSUE THREAD

**Issue by Paul2510** [Stephan-S/FS19_AutoDrive#1683]
Hallo! Hab das Problem auf der Kernstadt das der Abfahrer ständig den Ablade Kurs selbständig wechselt! Drescher läuft auf Courseplay!  LG

**Comment by Axel32019** [comment]
Hallo @Paul2510 ,
Was sollen wir mit diesen Informationen anfangen? Ein bisschen mehr darf es schon sein -> https://github.com/Stephan-S/FS19_AutoDrive/issues/1071

**Comment by Paul2510** [comment]
Morgen! Sorry aber in der Log schreibt er nichts!  Er fährt den eingestellten kurs Ober halb Den Kurs zum Drescher und unterhalb die Ablade staion! Während des Befahrens des Ablade Kurses wechselt er eigenständig den Abkipp kurs z.B. Vom HofSilo auf Herbecid ladekurs!
[log.txt](https://github.com/Stephan-S/FS19_AutoDrive/files/5600431/log.txt)

**Comment by Iwan1803** [comment]
https://github.com/Stephan-S/FS19_AutoDrive/wiki/Buttons-with-short-description
Button 9 zeigt vermutlich bei dir den Trecker mit 3 Pfeilen nach rechts, oder?

**Comment by Paul2510** [comment]
Ok! Sorry tut mir leid hab ich übersehn! Muss noch viel lernen! Danke!! LG

**Comment by Paul2510** [comment]
Ok! Eine Frage hätte ich noch das mit den Kursen passt jetzt perfekt! Hab noch das Problem das der Abfahrer abläd ein kleines stück hinter die Abladestation fährt und dann stehn bleibt! und sich nicht mehr bewegt

**Comment by Iwan1803** [comment]
Zielpunkt zu nah am Abladetrigger? Hier sollte mind. 1,5x Gespannlänge dazwischen liegen.

**Comment by Paul2510** [comment]
ok Vielen Dank werde es probieren!

**Comment by Axel32019** [comment]
Denke Frage ist beantwortet -> Closed.

**Comment by Paul2510** [comment]
Sorry vergessen! Ja klappt einwandfrei! LG und Schönes neues Jahr! Viel Gesundheit und Erfolg im Jahr 2021!!!  LG
