### ISSUE TITLE
[AD 1.1.0.6] how to use old configs / alte Config verwenden

### ISSUE THREAD

**Issue by Iwan1803** [Stephan-S/FS19_AutoDrive#1684]
If you want to use a config in the old format (map name in file name) with the new version 1.1.0.6 you have to do the following:
- check the savegame folder if there is a file named "AutoDrive_config.xml" and if so, delete or rename it
- copy the config into that savegame folder, start the game and load this savegame
- with the first saving the config is automatically converted from the old format to the new format
and that's all 😎

Wenn du eine Konfig im alten Format (Mapname im Dateinamen) mit der neuen Version 1.1.0.6 verwenden willst, musst du folgendes machen:
- im Savegame-Ordner nachsehen, ob es eine Datei mit dem Namen "AutoDrive_config.xml" gibt, und wenn ja, diese löschen oder umbenennen
- die alte Konfiguration in diesen Savegame-Ordner kopieren, das Spiel starten und dieses Savegame laden
- beim ersten Speichern wird die Konfiguration automatisch vom alten in das neue Format konvertiert
und das ist alles 😎

**Comment by Anonymous-any** [comment]
Hi, this is not for back to use the old format (map name in file name) with 1.1.0.6 right ? that I've understand 1st :/
Br

**Comment by ralfrhoen** [comment]
Hallo. Ich habe bemerkt das es Probleme bei Konvertieren auf diese Art bei der Steamversion des Spieles gibt. Anscheinend holt sich dort das Savegame immer die alten Daten aus der Steam Cloud.
Habe es dann so gemacht das ich den Spielstand einmal ohne AD gestartet und dann gespeichert habe.
Danach habe ich die alten AD Kursdaten ins Savegame kopiert und den Spielstand wieder mit AD gestartet. Nach dem Abspeichern waren die Daten dann richtig konvertiert.

**Comment by Iwan1803** [comment]
Ich habe die Steam-Cloudspeicherung aktiv und kann dieses Problem nicht bestätigen, zum Steam ja erst in die Cloud hochlädt, wenn das Spiel beendet wird.

**Comment by Farmboy0726** [comment]
How do you add AD courses to CP like sell bales and refill fert/seed tanks

**Comment by Iwan1803** [comment]
@Farmboy0726 please open a new issue because that has nothing to do with this topic.
