### ISSUE TITLE
[Feature Request] Fuel button

### ISSUE THREAD

**Issue by azbest1992** [Stephan-S/FS19_AutoDrive#1685]
Please, adde in Autodrive hud button "Fuel".
When we us it, worker automatically drive to nearest Fuel Trigger and refuel.
The option with automatic fuel refilling means that the tractor often goes to petrol stations with a full trailer ...

**Comment by Axel32019** [comment]
Hello @azbest1992 ,
If you disable automatic refuel in vehicle settings, it should not drive to a petrol station.
Did you try this already?

**Comment by Iwan1803** [comment]
Or remove any target point which are at a petrol station (within a radius of 15m).

**Comment by Mike1977** [comment]
> 
> 
> Hello @azbest1992 ,
> If you disable automatic refuel in vehicle settings, it should not drive to a petrol station.
> Did you try this already?

I think he was talking about a button similar to the park button. So you can automate the refueling like you can automate the parking. 
I like the automated process of refueling but sometimes autodrive decides to refuel exactly when hes on the opposite site of the map, with two heavy trailers filled to the rim. 
So with such a button, you could send the unloader to the gas station when its more convenient, while he continues to do whatever he was doing after that. Sure, you could set a course to the gas station, refill and again set the course to the field to continue unloading the combine, but you also could manually send him to the parking slot, without the button :)

**Comment by azbest1992** [comment]
> 
> 
> > Hello @azbest1992 ,
> > If you disable automatic refuel in vehicle settings, it should not drive to a petrol station.
> > Did you try this already?
> 
> I think he was talking about a button similar to the park button. So you can automate the refueling like you can automate the parking.
> I like the automated process of refueling but sometimes autodrive decides to refuel exactly when hes on the opposite site of the map, with two heavy trailers filled to the rim.
> So with such a button, you could send the unloader to the gas station when its more convenient, while he continues to do whatever he was doing after that. Sure, you could set a course to the gas station, refill and again set the course to the field to continue unloading the combine, but you also could manually send him to the parking slot, without the button :)

Yes! I meant it! Thank you.

**Comment by Stephan-S** [comment]
Would a key binding suffice?
I don't really want to add yet another button :-)

**Comment by Stephan-S** [comment]
Keybinding included in latest alpha
