### ISSUE TITLE
[Question]

### ISSUE THREAD

**Issue by Speedyls19** [Stephan-S/FS19_AutoDrive#1687]
**Question:** 
Servus, Hätte mal eine Frage an alle die Autodrive benutzen um Gülle zu Transportieren, Wenn sich meine beiden Gülle Transporter auf der Straße treffen und aneinander vorbeifahren füllt es automatisch von dem vollen Fass in das leere über und das vollere Fass bleibt automatisch stehen ist das eine reine einstellungssache? Würde mich Freuen wenn jemand eine lösung dafür hat.
MFG Speedy

**Comment by Mike1977** [comment]
Sieht aus wie das hier: https://github.com/Stephan-S/FS19_AutoDrive/issues/1636

**Comment by Speedyls19** [comment]
wäre nur schön wenn derjenige geschrieben hätte ob das geklappt hat mit dem Update

**Comment by Iwan1803** [comment]
In welchen Modi sind die Fahrzeuge unterwegs? Modfahrzeuge oder Vanilla?
Irgendwelche anderen Mods, die in irgendeiner Art und Weise in Fahrzeuge und bes. Hänger eingreifen? 
Auf welcher Map passiert das? Kann es z.Bsp. auf Felsbrunn nachgestellt werden?

PS: sind die angepinnten Beiträge wirklich so leicht zu übersehen? -> https://github.com/Stephan-S/FS19_AutoDrive/issues/1071

**Comment by Speedyls19** [comment]
hat sich geklärt war der meinung ich habe die aktuelle Version von autodrive habe mic haber vertan
ja habe alles nachgestellt und ausprobiert bis ich mal nach der Version geschaut hatte aber trotzdem danke 👍

**Comment by Iwan1803** [comment]
Ok, dann mach ich mal hier zu 😎
