### ISSUE TITLE
Häcksler abfahren geht nicht

### ISSUE THREAD

**Issue by Liam-0408** [Stephan-S/FS19_AutoDrive#1688]
Hi
ich will mit Autodrive Mais häckseln, hab dem Häcksler das Feld zugewiesen und den Standardhelfer aktiviert. dann beim Abfahrer normal Drescher abtanken. wenn ich auf start drücke, fährt der Abfahrer zu dem Startpunkt, sagt "Drescher folgen Seite rechts/links", macht den Motor aus und fährt mit <0km/h richtung Häcksler. 

https://youtu.be/cDAwXFcJkXw   Hier mal ein YT-Video davon

Hilfe!!!

**Comment by 60erjonny** [comment]
Hallo

Welche Version hast du drauf ? 
Versuche es natürlich, mit der aktuellesten mal...
Hat der Hächsler ein langes Abladerohr?
Wenn nicht, versuche es mit einem andern Mod...

**Comment by Liam-0408** [comment]
Hab mir mal die neueste Version runtergeladen, jetzt geht es !!!! Danke für den Hinweis!!
