### ISSUE TITLE
[Question] Dynamic storages compatibility

### ISSUE THREAD

**Issue by MAOGAMI** [Stephan-S/FS19_AutoDrive#1689]
**Question:**   
I've got a question about compatibility with dynamic storages (GlobalCompany) like grain and potato available on official modhub.

Do AD supports dynamic storages and i just can't find that option or it doesn't?

When I set a course to sell grain from X to Y the driver stops under unloading pipe of X and waits for the load instead of loading it at his own.

Similar problem is with Courseplay except that, the CP driver drives under the pipe, tries to load but then GC "select a box for unloading" appears and then the driver goes to Y without load (and of course repeats the process)

So, is there an option for unloading from dynamic storages or not?

If there's not such an option, then will u plan to add that functionality in near/further future?

**Comment by MAOGAMI** [comment]
I'm using latest version from official modhub.

I have also received reply from Courseplay team that CP doesn't support dynamic storages and it wont be anytime soon.

**Comment by Tensuko** [comment]
To put this into a more pricise answer:
The time we have with CP untill a next FS might comes out is short.
Implemnting something that might not work anymore in the next FS is a bit waste of time for us, as we got other things to do.
So maybe you find a way that AD can access this GrainStorage, when GC got an interface for this.

**Comment by Axel32019** [comment]
As far as I understand the GC Dynamic Storage there will be always an GUI interaction required with the user to select "the slot" from where to load something. 
With the current implementation in GC it is not possible to automate this loading, not only with AD but also with any other automated loading approaches (CP...).

**Comment by Axel32019** [comment]
Question answered -> Closed.
