### ISSUE TITLE
[BUG] Trailer cover

### ISSUE THREAD

**Issue by Anonymous-any** [Stephan-S/FS19_AutoDrive#1691]
**AutoDrive Version:** 1.1.0.6 
**Release or Custom Zip:** Release  
**Map (If applicable):** All  
**Vehicle / Type :**   Trailer
** Singleplayer  

**Describe the bug**

Hi,
**at Pickup and Deliver mode** I see after loading at the 1st time the cover is ok, but after 2nd step and above all other steps the cover won't cover.
![1](https://user-images.githubusercontent.com/25174503/100553153-69657880-328c-11eb-8245-eda0f851372b.png)
And also, I didn't want open a new for this 2nd where:
![2](https://user-images.githubusercontent.com/25174503/100553223-e8f34780-328c-11eb-9f90-4931e5f2f8e0.png)
Import/Export section seem missing.

Br

**Comment by Axel32019** [comment]
@Anonymous-any Hello Ano,
Are you aware of the trailer cover setting? What is going wrong? cover not open / always open / auto open or close
To your second topic: This will be removed in the next release as it is very out-dated and we do not plan to update.

**Comment by Anonymous-any** [comment]
Hi @Axel32019 yes sorry, set on auto open/close !
Well I can't say better I think for answering you, the cover blinking sometime at restart after going to reach another destination, I think when we see it it seem not know what it must do ^^, but like the picture the more time it stay open on route...if I remember good, when approaching near the new dest it close faster then open.. Bref it is not without issue (I think more about the contain in winter snowing with Seasons:) ).

Ok for the 2nd it was just to observe it.
Br

**Comment by Axel32019** [comment]
@Anonymous-any Hi Ano, Can we close this?

**Comment by Anonymous-any** [comment]
Hello @Axel32019 sure if you have see it and confirmed ?Thank
Br
