### ISSUE TITLE
[Question] Drescher abfahren bei gezogenen Erntemaschinen

### ISSUE THREAD

**Issue by MP3Turtle** [Stephan-S/FS19_AutoDrive#1692]
**Question:**   
Hallo zusammen,
ich habe die Funktion Drescher abfahren nun mehrmals erfolgreich eingestellt und genutzt.
Nun habe ich ein Problem bei dem gezogenen Ernter z.B. Ropa Keiler 2, wenn er voll ist wird der Abfahrer scheinbar nicht gerufen. Der Füllstand ist erreicht und CP meldet auch, dass entladen werden muss.
Beim Drescher o.ä. würde mein Abfahrer nun auch losfahren, hier leider nicht, Autodrive wartet auf den "Ruf".
Ich vermute mal, dass es an dem Traktor liegt, der vorne dran hängt :), oder mache ich etwas falsch?
Danke und Gruß,
MP3Turtle

**Comment by Iwan1803** [comment]
Es werden nur selbstfahrende Erntemaschinen unterstützt (keine Anhänger mit Erntefunktion).

**Comment by Axel32019** [comment]
@MP3Turtle Hallo, Das ist gerade in Arbeit...
Wenn Du es ausprobieren möchtest, Anleitung für beta-Version siehe hier: #1663

**Comment by MP3Turtle** [comment]
@Axel32019 Vielen Dank für den Tipp. Jetzt fährt er tatsächlich zum abfahren. Leider ist der LS während des Abladens abgestürzt, bleibe aber da am Ball... 
Das lag glaube ich an AD weil der Traktor vom Ropa ein wenig im Weg stand und ich ihn ein Stück zur Seite fahren musste. AD ist dann nachgezogen und hat das Abladen gestartet, dabei ist das Bild dann eingefrorern, erst konnte ich noch ins Menü danach ging nix mehr. Log anbei
[log.txt](https://github.com/Stephan-S/FS19_AutoDrive/files/5638600/log.txt)

**Comment by Axel32019** [comment]
@MP3Turtle Danke für die Rückmeldung. Leider konnte ich das bis jetzt noch nicht nachvollziehen. log ist auch soweit OK, vom Fehler mal abgesehen. Bitte weiter beobachten.

**Comment by Axel32019** [comment]
no update -> closed
