### ISSUE TITLE
AutoDrive_config.xml disappear while saving the game / AutoDrive_config.xml verschwindet beim Speichern/Zwischenspeichern

### ISSUE THREAD

**Issue by stein01** [Stephan-S/FS19_AutoDrive#1694]
AutoDrive Version: 1.1.0.6
Release or selbsterstelltes zip: Release
Karte (falls relevant): reproduzierbar auf Goldcrest Valley für LS19 (Mod-Map), andere nicht getestet
Fahrzeug(art) (falls relevant): -

**Beschreibe den Bug**
Ursprüngliche Beobachtung: nach 3-4 "Sessions" a 1h-3h, bei denen alles korrekt funktionierte (Kursaufzeichnungen, Fahrzeuge Routen fahren lassen inkl. Kombination mit CP) fehlten bei einem erneuten Aufruf sämtliche AD-Kurse.
Im savegame-Ordner war keine AutoDrive_config.xml und keine AutoDriveUsersData.xml mehr vorhanden. Im savegamebackup war im backup vom Vor-Vortag diese Dateien noch vorhanden. Diese habe ich wieder in den savegame-Ordner kopiert und das Spiel gestartet. Die Kurse waren wieder da. Wenn ich aber das Spiel speichere (manchmal speichert LS19 auch schon automatisch, wenn ich über <esc> die Karte oder Einstellungen aufrufe) verschwinden AutoDrive_config.xml und AutoDriveUsersData.xml aus dem savegame Ordner. (ich spare mir jetzt das Jammern, dass die Änderungen, die ich an dem Vortag gemacht habe, natürlich damit auch hinfort waren...)
Über den Trick des Umbenennens (natürlich beide Richtungen) habe ich die AutoDrive_config.xml auch mal im Editor geöffnet und gespeichert. Damit werden dann aber auch keine "Kurse" mehr im LS19 angezeigt. Im Editor wurden die Kurse aber noch angezeigt.
Habe auch mal probiert (mit der Backup-Version) gleich nach dem Start sämtliche Einstellungen zurückzusetzen. Hat auch nicht geholfen.
Wie komme ich da weiter, um herauszufinden, was jetzt dazu führt, dass die AutoDrive_config.xml, die ich noch aus dem Backup habe, zwar eingelesen wird, aber (so würde ich es vermuten) nicht mehr gespeichert werden kann und da wohl beim Speichern die alten Dateien erst gelöscht werden, diese dann auch verschwinden.
Soll ich die AutoDrive_config.xml hier mit reinhängen.... ist aber für die (Goldcrest Valley) Mod_map, daher wohl nur damit reproduzierbar, oder welche Debugging / Logging Funktionen kann/soll ich wie einschalten und welche Daten wo und wie abgreifen? Hatte vorher LS17 und spiele LS19 erst seit Mitte November (inkl. Alpine..) kenne daher noch nicht alles... Console öffnen hatte ich mir jedoch mal in einem Video angeschaut.. sollte bei Bedarf auch bei mir möglich sein.

Im Spiel selber gibt es keine "Hänger" oder "Blocker", lief/läuft mit AD sonst unauffällig. Andere "Sachen" werden normal gespeichert.
Es sind einige Mods aktiviert, würde aber behaupten tendenziell handelt es sich um die "üblichen Verdächtigen", die man auch oftmals bei den LS19-Youtubern (z.B. FedAction) sehen kann.

**Falls anwendbar - Schritte mit denen ich den Bug nachstellen kann**

**Screenshots**
Falls relevant, bitte Screenshots beifügen

**Comment by Axel32019** [comment]
@stein01 Hallo,
Bitte die AutoDrive_config.xml und AutoDriveUsersData.xml in .txt umbenennen und hier hochladen.
Helfen würde auch die log.txt

**Comment by stein01** [comment]
[AutoDrive_config.xml.txt](https://github.com/Stephan-S/FS19_AutoDrive/files/5644352/AutoDrive_config.xml.txt)
[AutoDriveUsersData.xml.txt](https://github.com/Stephan-S/FS19_AutoDrive/files/5644353/AutoDriveUsersData.xml.txt)
[log.txt](https://github.com/Stephan-S/FS19_AutoDrive/files/5644354/log.txt)

Hi,

log.txt erstellt mit: Start LS19 mit der AutoDrive_config.xml -> Map geöffnet (Kurse wieder da) -> Spiel gespeichert -> Map geschlossen -> LS19 wieder zu. (die xml waren danach nicht mehr im savegame-Ordner)

**Comment by stein01** [comment]
Hi, hatte noch etwas rumprobiert. Scheint wohl aus dem Bereich der <waypoints> in der AutoDrive_config.xml zu kommen. Hatte eine neue angelegt und dort einfach nur durch rumkurven auch die ähnliche Anzahl Wegpunkte erzeugt um dann den mapmarkers Bereich aus der "alten" reinzukopieren. Machte damit keine Probleme. Hatte daraufhin auch den <waypoints> Bereich rüberkopiert (alles mit Notepad++), dann trat das Problem wieder auf... seltsam die AutoDrive_config.xml, die jetzt rumzickt hatte Autodrive selber noch rausschreiben können, nun kann es Autodrive nicht mehr. Ich hatte keinen Grund die Datei zwischendurch irgendwie anders zu öffnen.... wie oben beschrieben, kann Autodrive sie ja auch immer noch öffnen bzw. auch der Editor könnte es auch, nur scheint der beim Schreiben(in der Hoffnung, das er vielleicht die fehlerhafte Stelle "glattbügelt") so viel zu ändern, dass die _config nicht mehr von AD eingelesen werden kann. Hatte noch versucht ein wenig die gleiche Form reinzubringen (vermeintliche Leerzeilen raus, Header raus --- führte dann aber zum Totalabsturz von LS19 beim Speichern). Denke dieser Weg hilft mir nicht weiter..

**Comment by Axel32019** [comment]
Halllo @stein01 Das wirst Du so nicht lösen können. Da sind einige ungültige Wegpunkte enthalten die dann die Probleme machen.
Versuch mal die korrigierte hier:
[AutoDrive_config.xml.txt](https://github.com/Stephan-S/FS19_AutoDrive/files/5645708/AutoDrive_config.xml.txt)

**Comment by stein01** [comment]
Hallo @Axel32019 danke werde es gleich probieren. Wollte aber gerade reinschreiben, dass ich es doch noch hinbekommen habe. Hatte nur die zwei ungünstigen Zeilen (in und out) aus der mit dem Editor geschriebenen xml-Version getauscht, die ev. mit den '-1' die ungünstigen/ungülten Werte enthalten hatten....
habe gerade noch schnell deine probiert: geht auch - Danke
Soll ich schließen? Ist hier jedoch eine individual Lösung. Im Prinzip hat der Editor (wie oben gehofft) die ungünstige Stelle schon fixen können, da aber wohl anderes nicht so recht passt, wäre der "noch" kein allgemeines Heilmittel für solche Fälle.

**Comment by Axel32019** [comment]
Hallo @stein01 Hab das in AD angepasst. Der externe Editor kann noch nicht richtig mit dem neuen Format umgehen - ist bei uns nicht Prio, dafür ist ingame da.
Wenn OK darfst Du gerne schließen - Viel Spaß noch...

**Comment by stein01** [comment]
Läuft wieder... super. Danke
