### ISSUE TITLE
[Question] blue Lines

### ISSUE THREAD

**Issue by envikowaty** [Stephan-S/FS19_AutoDrive#1695]
**Question:**   
I've got a question...
 Hope you all doing well , auto drive is a super tool ! 

My question is, when I’m editing route and I’m trying to connect two points; pressing shift on keyboard I get blue line instead of green like rest of the track, why it’s like that ?

**Comment by Williwillswisse** [comment]
Light blue lines are for reverse driving. For a green connection start edit mode and simply klick LMB the two points.
Take a look at:
https://github.com/Stephan-S/FS19_AutoDrive/wiki/Edit-Mode

**Comment by envikowaty** [comment]
Thank you !
