### ISSUE TITLE
[Feature Request] Fuel saving mode

### ISSUE THREAD

**Issue by kferrano** [Stephan-S/FS19_AutoDrive#1696]
**Is your feature request related to a problem? Please describe.**  
No.

**Describe the solution you'd like**  
As with Courseplay, a fuel-saving mode that the vehicle switches off the engine if it has to wait longer.

**Describe alternatives you've considered**  
are none

**Additional context**  
are none

**Comment by Axel32019** [comment]
@kferrano Hello,
In which situations the engine is not switched off?
Are you using the latest release version 1.1.0.6?

**Comment by kferrano** [comment]
Yes, I use 1.1.0.6

when unloading e.g. when the silo is full and he waits

**Comment by Iwan1803** [comment]
From the release notes, which can be found here: https://github.com/Stephan-S/FS19_AutoDrive/wiki/Release-Notes#changelog-for-release-1106-22112020

> the motor is not switched off during unloading

**Comment by kferrano** [comment]
But that's stupid, because if the silo is full, the tractor just stands there with the engine running and does nothing more.

**Comment by Axel32019** [comment]
@kferrano This was improved in 1.1.0.7 - now the engine is switched of if no unloading operation is ongoing, i.e. close trailer.
