### ISSUE TITLE
[Feature Request]Continue unloading automatically

### ISSUE THREAD

**Issue by kferrano** [Stephan-S/FS19_AutoDrive#1697]
**Is your feature request related to a problem? Please describe.**  

**Describe the solution you'd like**  
The tractor currently ends the unloading mode as soon as the silo or the BGA is full. It would be nice if he would continue unloading as soon as there is space again and not wait until I intervene and unload myself.

**Describe alternatives you've considered**  

**Additional context**

**Comment by Axel32019** [comment]
@kferrano Hello,
I had a look at this, but if a trigger is full the Giants engine hide it. So it is not possible to detect it.
In near future I do not see a feasible solution for this.

**Comment by kferrano** [comment]
What if you do a timer like loading? the quasi when during the unloading the trigger disappears, but there are still residues in the trailer that it 1. asks whether the trigger is back and 2. switches off the engine during this time.

I hope you understand what or how I mean it.

**Comment by Axel32019** [comment]
I did a first imlementation in beta branch, but with limitations. You may have a look at it: https://github.com/Stephan-S/FS19_AutoDrive/commit/8e5ea1cc3391675e24fe47d5ec4038e1e8daef4b

**Comment by kferrano** [comment]
So far it works fine. it waits until there is space in the silo or the color and refills as it should.

**Comment by Axel32019** [comment]
OK - closed.
