### ISSUE TITLE
[BUG] "Driver of x can't reach y", despite having a simple connected route to and from

### ISSUE THREAD

**Issue by realskudd** [Stephan-S/FS19_AutoDrive#1699]
**AutoDrive Version:** 1.1.0.6
**Release or Custom Zip:** Release  
**Map (If applicable):** All, mainly playing on County Line though
**Vehicle / Type (If applicable):**   All
**Multiplayer or Singleplayer:** Singleplayer  

**Describe the bug**  
When I started adding more routes to my network after a fresh new game, my drivers kept complaining that they couldn't find a route to the target destination. I've tried positioning them on various points along the route, and there are clearly positions that are happier in this regard than others, but once they move on in the cycle they get back to the amnesia mode and give up. I have the pathfinder max time set to max (x3), and it doesn't seem to help.

**Screenshots**  
![image](https://user-images.githubusercontent.com/4642150/101233235-e3c33d80-367c-11eb-95a7-ec8f92305a74.png)

**Comment by realskudd** [comment]
After poking around at it a bit, it seems like this happens with auto-connected ends, but not with manually connected.

**Comment by realskudd** [comment]
Deleted the suspect section of the route and re-recorded it, manually connecting the end. It seems to be working now.

**Comment by Axel32019** [comment]
@realskudd Hello,
If you need further investigation please add log.txt and AutoDrive_config.xml renamed to .txt here.

**Comment by Axel32019** [comment]
not reproducible -> closed.
