### ISSUE TITLE
[Question] change the direction of several waypoints simultaneously in the ingame editor? - gleichzeitige Richtungsänderung von mehreren Wegpunkten im ingame-Editor?

### ISSUE THREAD

**Issue by haamic** [Stephan-S/FS19_AutoDrive#1700]
**Question:**   
Hello, 
will it ever be possible to change the direction for several waypoints at the same time in the ingame editor? So to change a green route into a blue route?
It happens sometimes, that you enter a green route and then, because of lack of space, you realize that it would be better to change a part of it to blue. With many points this is a bit tedious ingame because every connection between 2 points has to be changed separately. 
One click on the 1st point and the last point and it is changed.  Is that difficult to implement? AD actually "knows" which point to click on, if the end point is more than 1 point away, all points up to that point are changed. or do I imagine this to be too easy? Or does such a possibility already exist and I just do not know it.
Also deleting routes by clicking on the starting point and end point would be nice.

Greetings Micha

+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Hallo, 
wird es mal im ingame-Editor möglich sein, für mehrere Wegpunkte gleichzeitig die Richtung zu ändern? Also eine grüne Strecke in eine blaue Strecke zu ändern?
Es kommt schon mal vor, man fährt eine grüne Strecke ein und stellt dann, wegen Platzmangel, fest, das es doch besser wäre einen Teil in blau zu ändern. Bei vielen Punkten ist das ingame etwas langwierig da ja jede Verbindung zwischen 2 Punkten separat geändert werden muss. 
Ein Klick auf den 1. Punkt und den letzten Punkt und schon ist es geändert.  Ist das schwer umsetzbar? AD "weiss" doch eigentlich, auf welchen Punkt man klickt, wenn der Endpunkt weiter als 1 Punkt entfernt ist, werden alle Punkte bis dahin geändert. oder Stelle ich mir das zu einfach vor? Oder gibts so eine Möglichkeit bereits und ich kenne sie nur nicht.
Auch das Löschen von Strecken durch Klick auf den Anfangspunkt und Endpunkt wäre schön.

Gruss Micha

**Comment by Mike1977** [comment]
Sowas habe ich mir auch schonmal gewünscht, als ich Felder zusammengelegt habe, und danach Strecken umbauen musste. Aber dann habe ich festgestellt das es einfach viel schneller geht, diese Strecke schnell neu einzufahren, und den Anfang und das Ende an das Netz anzubinden.

**Comment by Iwan1803** [comment]
Wenn ich Punkt A anklicke und dann irgendwo anders Punkt B, muss AD ja alle Wegpunkte zwischen den beiden selektierten ermitteln. Was ist dannn, wenn da eine Kreuzung oder Abweichung zwischen ist? 
AD dürfte also nicht die aktuelle sondern eine weitere Wegberechnung bekommen, um Probleme durch sowas auszuschließen.
Ich denke, das der Programmieraufwand hierfür unnötig hoch wäre und der Anwendungsfall jetzt nicht so oft vorkommt, das es sich lohnen würde.

Mein Tip: vorher mehr Zeit in die Streckenplanung investieren und dann muss man nachher weniger bis gar nichts korrigieren.
Wie Mike schon sagt, ist ein Neueinfahren meistens recht schnell erledigt.

**Comment by Th301** [comment]
Moin zusammen,
meine Frage passt evtl. nicht 100% hier dazu aber es bezieht sich auf das gleiche Feature.

Wie nimmt man mit der aktuellen Version eine blaue Strecke auf? Hab gerade erst wieder angefangen und das Wiki bezieht sich wohl noch auf eine ältere HUD-Version.

Vielen Dank im Voraus! 👍 

P.s.: Der Mod ist einfach unverzichtbar, vielen Dank für die Arbeit!

**Comment by Iwan1803** [comment]
Grüne Linie = vorwärts fahren = Linksklick auf den Record-Button
Dunkelblaue Linie = beidseitig befahrbar = Rechtsklick auf den Record-Button
Hellblaue Linie = rückwärts fahren = Linksklick auf den Record-Button und dann rückwärtsfahren

**Comment by Th301** [comment]
Besten Dank!! @Iwan1803 :)

**Comment by Iwan1803** [comment]
Da keine weitere Rückmeldung -> geschlossen 😎
