### ISSUE TITLE
[Question] Distance to harvester

### ISSUE THREAD

**Issue by envikowaty** [Stephan-S/FS19_AutoDrive#1701]
**Question:**   
I've got a question...regarding distance to the working harvester from the unloaded tractor ? Even though the tractor is parked next to the field the tractor instead of driving to the full harvester is waiting. The debug is showing that tractor is in IdleUnloders

**Comment by envikowaty** [comment]
Ok problem solved, I forgot to setup the position/ waypoint on the harvester ( setup waypoint but don't start the ad on harvester) - all works fine now

**Comment by Axel32019** [comment]
Enjoy learning AD :-) -> closed.
