### ISSUE TITLE
Awning.

### ISSUE THREAD

**Issue by Blackmankot** [Stephan-S/FS19_AutoDrive#1702]
Good afternoon! Thanks for your hard work! A much needed mod!
Suggestion - I suggest translating the following settings into Russian.

First parameter -
![2020-12-06_13-02-35](https://user-images.githubusercontent.com/26131714/101272029-6f46e680-37c3-11eb-85db-d4bad245489e.jpg)
Translation - "Да - AutoDrive автоматически выбирает сторону разгрузки /
Нет - будет использована уже выбранная сторона разгрузки"

Second parameter -
![2020-12-06_13-06-18](https://user-images.githubusercontent.com/26131714/101272067-e67c7a80-37c3-11eb-866a-7600439eab9d.jpg)
Translation - "Да - AutoDrive открывает и закрывает тент кузова по мере необходимости /
Нет - AutoDrive не управляет тентом кузова"

Sincerely, Alexander.

**Comment by Axel32019** [comment]
@Blackmankot Hello Alexander, Thanks for the contribution!
As I expierienced issues with translations in the past I would like to ask you:
Please add your changes in the file https://github.com/Stephan-S/FS19_AutoDrive/blob/beta-testing/FS19_AutoDrive/translations/translation_ru.xml renamed to .txt
Add the changed file here or create a pull request.

**Comment by Blackmankot** [comment]
Good! I approached the question more carefully and did not change my first translation a lot. And also corrected the spelling in several places.

Thanks for your hard work!
[translation_ru.txt](https://github.com/Stephan-S/FS19_AutoDrive/files/5649049/translation_ru.txt)

**Comment by Axel32019** [comment]
Merged into beta branch.
@Blackmankot If you find the time please check if all is in and correct.
Thanks!

**Comment by Blackmankot** [comment]
Yes, of course, I'll check everything again.

I am glad to help!

**Comment by Blackmankot** [comment]
Hello. I checked, everything is ok, thanks.

Question - are you planning to add a message if the transport saw a barrier and got stuck, stopped?
This message is badly missing for transport control.

**Comment by Axel32019** [comment]
Hello Alexander, This is already a feature request for future: #1649

**Comment by Blackmankot** [comment]
Hello Axel32019! Thanks, I will look forward to this feature.

**Comment by Axel32019** [comment]
Last point already present as feature request -> Closed.

**Comment by Blackmankot** [comment]
Yes of course.
