### ISSUE TITLE
CoursePlay Custom field Integration

### ISSUE THREAD

**Issue by betrox007** [Stephan-S/FS19_AutoDrive#1703]
**Question:**   
I've got a question.. Hi AD Team.. first of all thanks for effort and hard working to develop  such a great mod, is the integration with Course play, especially course play field work for tractor hauling loading wagon to picking Grass or Hay on custom field is not working anymore? since what i know until RC6 this feature still working great.
so the case is I'm creating a custom field and moving, tedding and patching grass with windrower and then using course play field work mode and setting using auto drive for refill/unload, on auto drive i'm using pickup and delivery mode, set pickup point at nearby custom field created with course play, and unload point at multi silo, after loading wagon get  full load picking up grass with CP field work, CP transfer driver to Auto drive for unload, until here the integration is still fine, but the auto drive then drive to load point and not drive to unload point, once he reach load point instead drive to unload point , he trigger the course play and deactivated auto drive, so course play take over control and return to work again, but when course play activated and detected the loading wagon is full again course play transferred again the driver to Auto drive for unload, again auto drive driving to load point and not to unload point, and trig course play to work again...and this continue loop, the auto drive never drive full loaded loading wagon to unloading point.. except we press next on auto drive hud

here the link for recording video i have made https://youtu.be/UNxPjlx5cbU

 and here some screen shoot
![fsScreen_2020_12_06_16_05_43](https://user-images.githubusercontent.com/56646850/101276273-46801a80-37de-11eb-91db-e06bbf902ace.png)
![fsScreen_2020_12_06_16_05_56](https://user-images.githubusercontent.com/56646850/101276279-4c75fb80-37de-11eb-90ad-79bf9655e292.png)
![fsScreen_2020_12_06_16_06_23](https://user-images.githubusercontent.com/56646850/101276282-50098280-37de-11eb-8ddc-b4ad61907371.png)
![fsScreen_2020_12_06_16_06_29](https://user-images.githubusercontent.com/56646850/101276284-53047300-37de-11eb-98c5-0046f4e31c83.png)

thanks in advance

**Comment by Axel32019** [comment]
@betrox007 Hello,
I assume you set the unload level in AD to 100% - or not?
CP will fill up to 99% and pass to AD, AD detect less then requested 100% and pass back to CP to collect -> endless.
Please set AD unload level to 90 or 95%!

**Comment by betrox007** [comment]
okay thanks i will try that.. i set AD 100%.. maybe that's the problem.. i will reduce AD load to 95 or 99 %

**Comment by betrox007** [comment]
thanks @Axel32019 , it solved.. so the problem is the difference setting for load because CP default capacity is always 99% so we can't set AD fill capacity to 100 % for this mode...
