### ISSUE TITLE
Light when backing up, at night, at bga and triggers

### ISSUE THREAD

**Issue by Crinouche** [Stephan-S/FS19_AutoDrive#1704]
Hello,

Would it be possible to turn on the lights when the tractors arrive at the bga, outlets, storage points and loading points? because at night, you don't see much. On the road it is not useful
AD is a great mod. THANK YOU
![IMAGE1](https://user-images.githubusercontent.com/36656729/101290553-5d853380-3803-11eb-9bb0-d99dd1a1f56f.png)
![IMAGE2](https://user-images.githubusercontent.com/36656729/101290559-5f4ef700-3803-11eb-8957-39634382dae6.png)

**Comment by Crinouche** [comment]
![image](https://user-images.githubusercontent.com/36656729/102712325-9839a200-42c0-11eb-9971-b0f60acac00a.png)

**Comment by Axel32019** [comment]
follow-up in #1820
