### ISSUE TITLE
[BUG] Problem with HUD

### ISSUE THREAD

**Issue by azbest1992** [Stephan-S/FS19_AutoDrive#1705]
**AutoDrive Version:** 1.1.0.6   
**Release or Custom Zip:** Release  
**Map (If applicable):** Felssburn
**Vehicle / Type (If applicable):All
**Multiplayer or Singleplayer:** Singleplayer  

Hello. I have problem with autodrive.
When I turn on the AautoDrive HUD, the speedometer HUD disappears. There are also no waypoints and AD is not working.
```
2020-12-06 22:58 C:/Users/Mikolaj/Documents/My Games/FarmingSimulator2019/mods/FS19_AutoDrive/scripts/Specialization.lua:501: attempt to index local 'wp' (a nil value)
2020-12-06 22:58 Error: Running LUA method 'draw'.
```
![20201206230428_1](https://user-images.githubusercontent.com/74253047/101294521-0d649c00-3818-11eb-95e0-b36741c52177.jpg)
![20201206230422_1](https://user-images.githubusercontent.com/74253047/101294522-0e95c900-3818-11eb-9507-2ff216b43efd.jpg)

**Comment by Axel32019** [comment]
@azbest1992 Hello,
Please attach log.txt and AutoDrive_config.xml renamed to .txt.

**Comment by azbest1992** [comment]
Here you are.
[AutoDrive_config.txt](https://github.com/Stephan-S/FS19_AutoDrive/files/5649679/AutoDrive_config.txt)
[log.txt](https://github.com/Stephan-S/FS19_AutoDrive/files/5649680/log.txt)

**Comment by Axel32019** [comment]
Looks like you merged an older version of the config with a new one -> do not do this!
In case follow these instructions: https://github.com/Stephan-S/FS19_AutoDrive/issues/1684
Try this after rename to .xml.
[AutoDrive_config.txt](https://github.com/Stephan-S/FS19_AutoDrive/files/5649687/AutoDrive_config.txt)

**Comment by azbest1992** [comment]
Does't work.

**Comment by Axel32019** [comment]
That it looks like if no waypoints are recorded and game saved.
What is the issue with the corrected version I added above?

**Comment by Pioner912** [comment]
@Axel32019 

Ich habe das selbe Problem könntest du mir ebenfalls helfen?
Ich habe schon ein paar sachen versucht aber nichts bringt etwas


[AutoDrive_config.txt](https://github.com/Stephan-S/FS19_AutoDrive/files/5694971/AutoDrive_config.txt)

**Comment by Axel32019** [comment]
@Pioner912 Hallo,
Ich weiß nicht wie Du das hinbekommen hast, aber das lässt sich nicht reparieren: Da fehlt eine große Anzahl der Wegpunkte.
Bitte auf einer Version vor diesen Änderungen aus savegameBackup aufsetzen!

**Comment by Pioner912** [comment]
![Unbenannt](https://user-images.githubusercontent.com/65849562/102254857-84c9b800-3f09-11eb-9ff0-141e8fa6fe90.jpg)

Hallo @Axel32019 was komisch ist in dem Ordner Die Datei "Autodrive_config" komplett gelöscht und eine aus einem früherem Backup eingefügt, dann Spiel gestartet wieder fest gestellt das es nicht geht und dann war auf einmal auch noch diese Datei erstellt "AutoDrive_NF_Marsch_4fach_oG_2_4_config.xml" worden ist das nicht geändert worden?

**Comment by Pioner912** [comment]
![Unbenannt](https://user-images.githubusercontent.com/65849562/102272869-bd758b80-3f21-11eb-8cf1-a63a35044670.jpg) 

Hallo @Axel32019  die Config Datei war doch nicht defekt Sie funktioniert! 
Aber wie oben im Bild zu sehen habe ich mirt mal die mod desc von der Marsch angesehen und anscheinend ist hier der Fehler zu finden. Als Version wird hier 2.3 angegeben aber als Beschreibung 2.4 als ich das in der Config Datei für autodrive auf Version 2.3 geändert habe funktionierte alles wieder, ich kann die Kurse alle sehen und anfahren und zu ihnen Springen. 

Wäre es möglich das ihr die Versionsnummer der Map aus der Config Datei in Autodrive heraus nehmt? 

Mit freundlichen Grüßen und besten Weihnachtswünschen 

Pionier912

**Comment by Axel32019** [comment]
@Pioner912 Hallo,
Die Version der Map wird automatisch entfernt wenn eine korrekte config (Map-Version) vom Spiel geladen und gespeichert wird.
Danach gibt es nur noch die AutoDrive_config.xml. Du solltest Release 1.1.0.6 oder höher verwenden.

**Comment by Pioner912** [comment]
@Axel32019 Das mache ich sowieso immer mit der aktuellen Version 
komischerweise ging die ad Datei auch bis zum nächsten Update der mal wieder, nach dem Update wieder error und lua Fehler. 

Hatte dann keinen Bock mehr und habe mir die ad Datei von Holger-70 geladen und die entsprechenden Änderungen vorgenommen. Aber erst als ich von Version 1.xx7 auf die 6er gewechselt bin hat er die Datei richtig konvertiert! 

Danach direkt wieder auf die 7er. 

Denke das man den Thread hier auch schließen kann.

**Comment by Axel32019** [comment]
@Pioner912 Ich hab das xml-Handling schon verbessert, kommt im nächsten Release.
Mache hier erstmal zu.
