### ISSUE TITLE
Problem beim „Automatischen Tanken“[BUG]?

### ISSUE THREAD

**Issue by roland45** [Stephan-S/FS19_AutoDrive#1706]
**AutoDrive Version:** 1.1.0.6  
**Release or Custom Zip:** Release  
**Map (If applicable):** All  
**Vehicle / Type (If applicable):**   
**Multiplayer or Singleplayer:** Singleplayer  

**Describe the bug**  
Während eines mehrstündigen Spiels ohne Probleme, sackte plötzlich die FPS auf einen dauerhaften Wert  von 2 FPS ab. Nichts ging mehr.  In der Log war nichts zu bemerken.  Nach längerem Suchen und Überprüfung der aktiv beschäftigten Fahrzeuge,  kam ich zu einem  Fahrzeug,  welches sich im Modus „Mehrere Ziele anfahren (rotierendes Abladen)“ befand und geringen Dieseltreibstoff hatte. Nach „Stop“ dieses Modus ging die FPS wieder auf Normalwert und das Fahrzeug  trat sofort „Fahre Tanken“ an. Danach funktionierte wieder alles reibungslos. Vermute daher, daß das Zusammentreffen „rotierendes  Abladen“ mit dazwischen auftretendem Wunsch  „Fahre Tanken“ zu diesem Problem geführt haben könnte.

**Comment by Iwan1803** [comment]
Das Phänomen konnte ich so bisher nicht beobachten und ich habe so einige Fahrzeuge, welche in den diversen Modi immer unterwegs sind. Ab und zu finden sie zwar den Weg zur nächsten Tankmöglichkeit nicht, aber dies führte weder zu Lags noch FPS-Einbrüchen.
War dies ein Einzelfall oder lässt sich das Problem reproduzieren?

> Map (If applicable): All
Vehicle / Type (If applicable):

**Comment by roland45** [comment]
Dieser Dauereinbruch auf 2 FPS war bis jetzt ein Einzelfall und hat sich nicht wiederholt. Ansonsten läuft das Spiel einwandfrei, zeitweise mit kurzen FPS Rückgängen bis ung. 15 FPS aber nur von kurzer Dauer (max 10 sec). Habe einen Screen von dem Vorfall und die log beigelegt. Möglicherweise könnt Ihr daraus was ablesen. Wenn nicht, kein Problem, es läuft derzeit ja wieder alles OK.
[201207_log.txt](https://github.com/Stephan-S/FS19_AutoDrive/files/5667187/201207_log.txt)
![Screenshot (77)](https://user-images.githubusercontent.com/62171868/101655844-5dbf4200-3a42-11eb-89c4-35d47fa5af14.png)

**Comment by roland45** [comment]
[log.txt](https://github.com/Stephan-S/FS19_AutoDrive/files/5667243/log.txt)

**Comment by Iwan1803** [comment]
`2020-12-07 09:47   =C:/Users/Roland/Documents/My Games/FarmingSimulator2019/mods/FS19_Courseplay_6/register.lua (133) : superFunc
2020-12-07 09:47   dataS/scripts/i3d/I3DManager.lua (118) : asyncCallbackFunction
2020-12-07 09:47   Error: Index not found: 0>16|9`
Diese Meldung gab es mal in einer früheren Version von CoursePlay und deutet auf einen Fehler in den Kursdateien hin.

Einige Mods werfen zudem ein paar Error und Warning, was du dir ggfs. mal genauer ansehen solltest.
Ansonsten entdecke ich jetzt aber nichts, was auf Probleme mit AD hindeutet.

**Comment by roland45** [comment]
Danke für Deine schnelle Analyse. War doch kein BUG von AD. Habe aber seitdem Einträge in der Log, die vorher nicht waren. zB: heute 10 Felder mit 2 Feldspritzen bearbeitet, in Kombination AD und CP, keine Spielbeeintächtigungen festgestellt und alles OK, aber Einträge siehe im beiliegende Auszug der log Datei.
Habe die Vermutung, daß hier ausschließlich CoursePlay verantwortlich ist. (CP jeweils in letzter Version 0013). Lässt sich das bestätigen?
[201210_Auszug_log.txt](https://github.com/Stephan-S/FS19_AutoDrive/files/5672838/201210_Auszug_log.txt)

**Comment by Iwan1803** [comment]
Da scheint jemand vom CP-Team ein "Debugging" nicht auskommentiert zu haben 😂

Wenn du nichts weiter AD-mäßig zu melden hast, würde ich hier erstmal zu machen.

**Comment by roland45** [comment]
Ja, danke Dir. 
Daumen hoch für Euer Projekt AutoDrive. Benutze es schon seit einigen Jahren, aber der Sprung bis zu heute ist gewaltig. Die rasante Berechnung der Kurse, das einfache und schnelle Editieren der Routen, das Parken, usw, usw..... macht es zu einem unverzichtbaren Teil des LS19.

**Comment by Iwan1803** [comment]
Vielen Dank, dann mach ich hier erstmal dicht 😎
