### ISSUE TITLE
[Feature Request] refill trailer from water plane

### ISSUE THREAD

**Issue by Anonymous-any** [Stephan-S/FS19_AutoDrive#1707]
**AutoDrive Version:** 1.1.0.6
**Release or Custom Zip:** Release  
**Map (If applicable):** Yagodnoe <s>1</s>2.5.1 (I can provide few translations files)
**Vehicle / Type (If applicable):**   water trailer
**Multiplayer or Singleplayer:** Singleplayer  

**Describe the bug**  
I'm in pickup&deliver mode and the vehicle simply wait at refill trigger like water plane. If I stop AD then launch refill manually then enable AD again, then AD can start after full refilled it go do his route.
But as well I tried with some exotic filltypes and on exotic map "Yagodnoe <s>1</s>2.5.1" with concrete or workers to load as filltypes for example, where FS show you have menu to choose what filltype you know ? then AD is waiting as well at this refill.
Maybe that come from bad mapmaker idk because it seem that depend as well of vehicle type or the trigger i follow...
**Screenshots**  
![1](https://user-images.githubusercontent.com/25174503/101699287-2ae57000-3a7b-11eb-8bea-08050f7ca6c9.png)

Edit :
Hello @Axel32019 ,
Back to you and reopened this to add it seem that do the same waiting but as rear maneuver (clear blue line)...
![1](https://user-images.githubusercontent.com/25174503/102251133-af654200-3f04-11eb-9066-b768151f72b6.jpg)
and please can you answer for the others picture I put for exotic fillType ?
Regard

**Comment by Axel32019** [comment]
Hello Ano, AD is handling only fixed triggers for loading and unloading (yet). So I would make this from bug to feature request.

**Comment by Axel32019** [comment]
@Anonymous-any You may test it in the beta -> #1663

**Comment by Anonymous-any** [comment]
Hello Axl,

Sure ! thank it's done in beta I keep it ^^.
Regard

**Comment by Axel32019** [comment]
@Anonymous-any Hello Ano,
The feature is included in 1.1.0.7.
For your last topic please create a bug!
