### ISSUE TITLE
[BUG]Lau Fehler sobald im Spiel der Editor /Draw Modus aufgerufen wird

### ISSUE THREAD

**Issue by FlohObb** [Stephan-S/FS19_AutoDrive#1708]
AutoDrive Version: 1.1.0.6
Release or selbsterstelltes zip: Release
Karte (falls relevant): Kernstadt
Fahrzeug(art) (falls relevant):Alle

**Beschreibe den Bug**
Sobald der Editor bzw der Draw Modus aufgerufen wird verschwinden alle Huds im Spiel und die Log füllt sich mit lua Fehlern 
[log.txt](https://github.com/Stephan-S/FS19_AutoDrive/files/5675504/log.txt)
[AutoDrive_config.txt](https://github.com/Stephan-S/FS19_AutoDrive/files/5675524/AutoDrive_config.txt)

**Falls anwendbar - Schritte mit denen ich den Bug nachstellen kann**

**Screenshots**
Falls relevant, bitte Screenshots beifügen

**Comment by Axel32019** [comment]
@FlohObb Hallo,
Die config ist nicht in Ordnung. Bitte diese Anleitung nutzen: #1684

**Comment by rooymans** [comment]
I'm having the same error messages on a different map (Hof Bergmann).
[log.txt](https://github.com/Stephan-S/FS19_AutoDrive/files/5719156/log.txt)

**Comment by Axel32019** [comment]
@rooymans Hello, This looks like the same defect config. Please follow instructions here: #1684

**Comment by N3kr0E** [comment]
Hallo,

habe das gleiche Problem. 
Ich habe aber kein Update oder ähnliches durchgeführt. Spiel gestartet, ein paar Kurse eingefahren,  LKW losgeschickt und nach ner Weile das Spiel beendet. Nach dem Restart dann plötzlich dieser Fehler. Ist aufgefallen, weil ich ein Zielpunkt nicht auswählen konnte und mir die Waypoints ansehen wollte. Diese werden im Editor nicht angezeigt. Es werden nur die Namen der Ziele angezeigt, aber auch hier keine Punkte.

Log anbei, falls Screenshots benötigt werden, einfach Bescheid geben.
[log.txt](https://github.com/Stephan-S/FS19_AutoDrive/files/5731196/log.txt)

**Comment by Axel32019** [comment]
@N3kr0E Hallo,
Bitte mal die AutoDrive_config.xml in .txt umbenennen und hier hochladen.
Noch etwas: Du nutzt eine beta-Version, die kann noch fehlerhaft sein - bitte auf die Release-Version aktualisieren!

**Comment by N3kr0E** [comment]
Oh, alles klar, werde mal die Version aktualisieren,
Hier aber noch die Datei.
[Uploading AutoDrive_config.txt…]()

**Comment by Axel32019** [comment]
@N3kr0E Irgendwie scheint der Upload zu klemmen - bitte nochmal versuchen...

**Comment by N3kr0E** [comment]
[AutoDrive_config.txt](https://github.com/Stephan-S/FS19_AutoDrive/files/5731683/AutoDrive_config.txt)
Dann der nächste Versuch

**Comment by Axel32019** [comment]
@N3kr0E Hast Du nur AD im mods-Ordner aktualisiert und danach das Spiel gestartet oder auch die AutoDrive...config umbenannt/geändert?
Probier mal diese:
[AutoDrive_config.txt](https://github.com/Stephan-S/FS19_AutoDrive/files/5732119/AutoDrive_config.txt)

**Comment by N3kr0E** [comment]
@Axel32019 Ich habe nur ingame was geändert, dann gespeichert. Es wurden seit dem auch keine neuen Mods installiert.
Ich teste mal die Datei

**Comment by Axel32019** [comment]
@N3kr0E Hast Du noch 1,2,3... Vorgänger der config aus den savegameBackup? 
Vielleicht hilft mir das weiter die Ursache zu finden.
In der letzten config wurden die letzten Wegpunkte nicht gespeichtert, aber die Ziele - die hab ich mal rausgenommen:
[AutoDrive_config.txt](https://github.com/Stephan-S/FS19_AutoDrive/files/5736888/AutoDrive_config.txt)

**Comment by N3kr0E** [comment]
[AutoDrive_config_2020-12-19.txt](https://github.com/Stephan-S/FS19_AutoDrive/files/5744428/AutoDrive_config_2020-12-19.txt)
[AutoDrive_config_2020-12-21.txt](https://github.com/Stephan-S/FS19_AutoDrive/files/5744430/AutoDrive_config_2020-12-21.txt)
[AutoDrive_NF_Marsch_4fach_V2_2_config_2020-12-12.txt](https://github.com/Stephan-S/FS19_AutoDrive/files/5744431/AutoDrive_NF_Marsch_4fach_V2_2_config_2020-12-12.txt)
[AutoDrive_NF_Marsch_4fach_V2_2_config_2020-12-16.txt](https://github.com/Stephan-S/FS19_AutoDrive/files/5744432/AutoDrive_NF_Marsch_4fach_V2_2_config_2020-12-16.txt)

@Axel32019 hoffe, du hattest ein ruhiges Weihnachtsfest!
Hier die gewünschten Dateien. Habe sie umbenannt, damit man sie besser unterscheiden kann. Im Svegame Ordner heißen die Dateien natürlich nicht so ;)

Soll ich die letzte config von Dir einmal testen?

**Comment by N3kr0E** [comment]
@Axel32019 
Also Deine Datei hat auch nicht funktioniert. 
Ich habe mir jetzt mal die .xml vom 19.12.2020 ins Savegame gezogen und das klappt.
Nun sind zwar einige Punkte verschwunden, aber immerhin kann ich wieder in den Editormodus.
Würde das Thema aber noch ganz gerne offen lassen, um zu sehen, ob es auch wirklich funktioniert.

**Comment by N3kr0E** [comment]
Frohes Neues!

Habe gestern ja mal mit meiner alten Datei getestet... Anfangs hat es funktioniert, ich konnte auch Kurse einfahren etc., nach einem Restart vom Spiel, dann wieder LUA-Fehler, Punkte nicht gespeichert bzw. zum Teil massiv verschoben, außerdem waren die Ziele bei allen aktiven AD-Abfahrern komplett durcheinander.
Brauchst Du irgendwelche Dateien von mir?

**Comment by Axel32019** [comment]
Danke und gleichfalls Frohes Neues.
Die üblichen Dateien würden helfen: log.txt, AutoDrive_config.xml und vehicles.xml

**Comment by N3kr0E** [comment]
Moin,

vielen Dank!
Hier die gewünschten Dateien.
Gestern wieder probiert, alte Datei reingeladen, Kurse eingefahren, Spiel neu gestartet, Kurse weg..
[log.txt](https://github.com/Stephan-S/FS19_AutoDrive/files/5761810/log.txt)
[AutoDrive_config.txt](https://github.com/Stephan-S/FS19_AutoDrive/files/5761813/AutoDrive_config.txt)
[vehicles.txt](https://github.com/Stephan-S/FS19_AutoDrive/files/5761815/vehicles.txt)

**Comment by DonBolli** [comment]
Ich weiss nicht genau ob das selbe Problem ist, aber ich vermute es.
AD: 1.1.0.7-RC1
Map: Multimap
Fahrzeuge: alle

![image](https://user-images.githubusercontent.com/43571844/103547443-b0a2e280-4ea4-11eb-8343-12013e37f5bd.png)

Sobald ich etwas ändern möchte oder neue Strecken einfahren, verschwindet alles ausser dem AD HUD und den Namen der Punkte.

**Comment by Axel32019** [comment]
@N3kr0E Das sieht danach aus als ob die config Datei umbenannt wurde und dann das Spiel gestartet - das geht schief.
AD benennt sie automatisch um und konvertiert ins neue Format.
@DonBolli Auch selbst umbenannt?

**Comment by DonBolli** [comment]
ich habe gar nichts gemacht, es ging immer und plötzlich waren alle Linien weg

**Comment by N3kr0E** [comment]
@Axel32019 Was meinst Du mit umbenannt und dann das Spiel gestartet?
Ich habe eigentlich auch nichts geändert...
Habe mir nun eine Savegame von einem anderen gezogen, die AD-Kurse gelöscht und neu eingefahren. Auch nach Restart funktioniert noch alles.

Mir ist allerdings auch in meiner xml aufgefallen, dass die ganzen Waypoints etc. doppelt aufgeführt sind.. Allerdings sind im "2. Durchgang" mehr Ziele.

**Comment by Stephan-S** [comment]
Cleaning up old issues.
