### ISSUE TITLE
Fahrzeugwechsel schließt Auswahlmenü (DediServer)

### ISSUE THREAD

**Issue by Dwarfbare** [Stephan-S/FS19_AutoDrive#1709]
AutoDrive Version: 1.1.0.6
Release or selbsterstelltes zip: Release
Karte (falls relevant): Fed Action March 4x
Fahrzeug(art) (falls relevant): Alle

**Beschreibe den Bug**
Wir haben auf einem Dedi Server im Multiplayer festgestellt: wenn man das Fahrzeug mit TAB oder eine anderen Belegung wechselt so schließt sich das Auswahlmenü(abgespeicherte Kurse) im Autodrive beim jeweiligen anderen Mitspieler (wir spielen nur zu zweit).

[gamelog.txt](https://github.com/Stephan-S/FS19_AutoDrive/files/5676125/gamelog.txt)

Wenn ihr noch was braucht so gebt bescheid

**Comment by Iwan1803** [comment]
Problem ist bekannt, aber danke für die Meldung 😉

**Comment by Kitekater** [comment]
Das Problem ist leider bei der 1.1.1.4 immernoch. Und wenn man mit 4-5 Leuten spielt, kann das schon ganz schön nervig sein.
Gibts da schon einen Lösungsansatz?
