### ISSUE TITLE
[Question]Bale storage

### ISSUE THREAD

**Issue by envikowaty** [Stephan-S/FS19_AutoDrive#1710]
**Question:**   
Question about the Bale Storage: 

https://www.farming-simulator.com/mod.php?lang=pl&country=pl&mod_id=150708

It's possible to unload the trailer with the autodrive ?

**Comment by Axel32019** [comment]
Hello,
Not automatic. The reason is that a trailer with bales are not "filled" into the trailer and could not be discarged like loose material.

**Comment by envikowaty** [comment]
Thank you ! 😀
