### ISSUE TITLE
[Waypoint Speed]

### ISSUE THREAD

**Issue by betrox007** [Stephan-S/FS19_AutoDrive#1711]
Hello Dear AD Team.. first of all Thanks for great mod that you have created, my question is.. it is possible to add feature driving speed on straight road with speed as per recorded speed?
i know in the AD Hud there have feature to set up road speed and chasing combine speed, also at the AD GUI have setting for corner speed, but what i mean is, when we setting for Road speed (at straight road not turn) for example 70 km/h but the recording speed is below 70 km/h then the driver will reduce the speed as per recorded speed.
or maybe add option at AD editor for user to setting each waypoint node speed as needed. i think this feature will made realistic driving especially for the bumpy road.
for current feature its working great we can adjust what speed we need for vehicle to driving, or what speed while turn and what speed when chasing combine it really great.
but the only problem is when the driver from smooth asphalt road then enter the bumpy road, its speed constant same as the preferred speed we set on HUD, it's only reduce speed when approach turn section.

i think it's all, if this possible it will be great, like in CP they have option to set speed with recoding speed option or with max speed

thanks and best regards

**Comment by magicmana** [comment]
an alternate solution i use on ponctually  some area with bump  , for prevent fling vehicle at 70km/h   is to add a point with big direction change at the bump entrance.
![fsScreen_2020_12_12_08_48_20](https://user-images.githubusercontent.com/32802279/101979004-a00e9c00-3c59-11eb-9cc5-90b8295e8391.jpg) 
on this sample the angle is soo big , that , the tractor reduce speed a 3km/h

**Comment by betrox007** [comment]
actualy i did like that but after that point the driver will return to the speed  we set on HUD, but thanks for the suggestion i will try to tricking course on bumpy road using that method, maybe add some direction change every 3 or 4 waypoint

**Comment by betrox007** [comment]
Thank's mate. i think this will be a great solution.. it is work
