### ISSUE TITLE
[BUG] Steuerung des Krangreifers mit XBOX Controller nicht mehr möglich / Controlling the crane grabber with a XBOX Controller isnt possible anymore.

### ISSUE THREAD

**Issue by JonasFovea** [Stephan-S/FS19_AutoDrive#1715]
AutoDrive Version: 1.1.0.5
Release or selbsterstelltes zip: Release
Karte (falls relevant): Alle
Fahrzeug(art) (falls relevant):

**Beschreibe den Bug**
Autodrive scheint mit der Steuerung des Greifers von diversen Greifern zu interferieren.
Diese war nur noch mit der Maus möglich.
Ich konnte den Fehler durch Deinstallieren weiterer Mods auf Autodrive zurückführen.
Auch ein Update von Autodrive auf 1.1.0.7-RC1 konnte das Problem nicht lösen.

**Falls anwendbar - Schritte mit denen ich den Bug nachstellen kann**
+ Autodrive installieren
+ Fahrzeug mit z.B. dem Fliegl Long Neck Combi Plus ausrüsten
+ LB+RB auf dem Controller drücken -> siehe Screenshot
+ Durch bewegen des rechten Sticks müsste hier eigentlich der Greifer zu öffnen und schließen sein.

**Screenshots**
![image](https://user-images.githubusercontent.com/30690893/102375866-4c86b000-3fc3-11eb-9e01-6a2130c486c7.png)

**Comment by Anonymous-any** [comment]
Hi there,

I saw for me too from the latest game update I got some controls (regressions) issues as well...

**Comment by Axel32019** [comment]
@JonasFovea Hallo,
Bitte prüfen ob die Einstellung LB+RB auf dem Controller schon in AD: zugeordnet ist. Wenn ja testweise ändern und  ausprobieren.
Die Tasten-Zuordnungen wurden in AD schon ewig nicht mehr geändert, wenn wurden Tasten ohne Vorbelegung hinzugefügt, die erst funktionieren wenn der Nutzer sie belegt.

**Comment by JonasFovea** [comment]
@Axel32019 Hi,
ich habe gerade alle AD Befehle, die RB, LB und RS Y(+-) verwenden entfernt, jedoch ändert dies nichts an der Problematik....

**Comment by Axel32019** [comment]
Bitte mal die log.txt hier hochladen.

**Comment by Axel32019** [comment]
Keine Reaktion -> Closed.
