### ISSUE TITLE
AutoDrive Version 1.1.0.7 und LS Version 1.6.0

### ISSUE THREAD

**Issue by Lars-LS17** [Stephan-S/FS19_AutoDrive#1718]
Hallo Zusammen,

ich habe gerade festgestellt, dass die AutoDrive Version 1.1.0.7 nur mit dem aktuellen Patch von LS funktioniert. 
Ich hatte vorher noch die vorherige Version drauf. Wenn man dann AutoDrive updatet kommt beim Spielstand starten die Fehlermeldung, dass AutoDrive nicht vorhanden wäre.

Scheinbar bin ich aber auch der einzige, der noch die alte LS-Version hatte und auf die neuste AutoDrive Version upgedatet hab, denn ich habe nirgendswo ein Issue dazu gefunden.

Wenn ich wirklich der einzige bin, dann kann man das ignorieren, ansonsten ist es eventuell hilfreich, beim Release-Version eine Info abzulegen, dass man den LS-Patch 1.7.1 installiert haben muss.

**Comment by Iwan1803** [comment]
Da wir die 1.1.0.7 bei Modhub eingereicht haben, ist eine aktuelle LS-Version eine Voraussetzung. Zudem können wir nicht x Versionen des Spiels supporten, nur die aktuellste.
Gibt es einen bestimmten Grund, das du LS19 noch nicht auf den aktuellen Stand gebracht hast?

**Comment by Lars-LS17** [comment]
Diesen Zusammehang wusste ich gar nicht. 

Nein, überhaupt kein Grund. Ich habe jetzt upgedatet und es läuft tadellos. Ich habe halt nur 30 - 45 min nach den Fehler gesucht, etliche male AD heruntergeladen und konnte mir nicht erklären, wieso diese Meldung kam. 

Wäre jetzt nur eine Idee, ob man irgendwo notieren kann (Release-Notes oder ähnliches), dass man den neusten Patch installiert haben muss. 
Vielleicht haben anderen LS-Spieler das selbe Problem. Oder ich bin einfach der einzige gewesen, der den neusten Patch installiert hatte.
Könnt ihr ja drüber nachdenken, ob das sinnig ist. Ansonsten hat sich das Thema erledigt. 
Bei mir läuft es auf jeden fall nach dem installierten Patch.

**Comment by Iwan1803** [comment]
Ich habe es mal hier im Wiki in die Release Notes aufgenommen.
Danke auf jeden Fall für den Hinweis.
