### ISSUE TITLE
[BUG] Verlassen der Parkposition klappt nicht einwandfrei / Leaving parkposition does not work well

### ISSUE THREAD

**Issue by TripleX1978** [Stephan-S/FS19_AutoDrive#1720]
AutoDrive Version: 1.1.0.7

Beim Verlassen der Parkposition folgt das Fahrzeug nicht dem vorgegebenen Pfad sondern...

1.) folgt erstmal dem Rückwärtskurs zur Parkposition bis zum Anfang, fährt dann erneut zurück zur Parkposition und fährt dann erst auf dem korrekten Pfad.

2.) folgt erstmal dem Rückwärtskurs zur Parkposition bis zum Anfang, fährt von da aus Luftlinie zu irgendeinem Punkt auf dem Pfad den er eigentlich hätte nehmen sollen.

Siehe auch #1438.
Seitdem hat sich egal bei welcher Version nichts geändert.

**Comment by Iwan1803** [comment]
AD sucht sich einen Wegpunkt vor der Front des Fahrzeuges, um seinen Weg zu berechnen. Steht das Fahrzeug "ungünstig", kann auch der "falsche" Weg genommen werden.
Ich würde den Trick mit der dunkelblauen Linie probieren, welche ich ab 14:49 erkläre: https://www.youtube.com/watch?v=nWL6UYMYzq0

**Comment by TripleX1978** [comment]
Danke für den Tipp.
Werde ich mal testen.
Macht es eigentlich einen Unterschied ob eine Strecke aus mehreren Segmenten besteht wenn man die mit einem Fahrzeug einfährt oder nur aus einem wenn man von Hand Anfang und Ende festlegt?

**Comment by Iwan1803** [comment]
Ich fahre meine Strecken immer mit einem Traktor ein und versuche dabei gleich, lange Anhänger oder Überbreiten zu berücksichtigen.
Die Parkplätze aus dem Video sind in mehreren Teilstrecken mit Hilfe von GPS eingefahren und dann verbunden worden.

**Comment by TripleX1978** [comment]
Hab jetzt mal die Kurse so angelegt wie du es in deinem Video gezeigt hast.
Das Einparken klappt, wie zuvor auch, ohne Probleme.
Beim Ausparken ist es immer noch so, dass der Traktor geradeaus fährt bis zu dem Punkt, wo er anfängt rückwärts einzuparken.
Von dort aus sucht er sich dann irgendeinen Punkt um auf den richtigen Kurs zu kommen.
Ich habe dann folgendes ausprobiert.
Nachdem das Einparken erfolgreich abgeschlossen wurde, habe ich manuell versucht den Traktor noch ein Stück rückwärts zu fahren.
Das ging nicht, weil ich mit dem Anhänger bereits an der Hallenwand stand.
Obwohl sich die Position des Traktors somit nicht verändert hat, hat danach das Ausparken immer auf Anhieb auf dem richtigen Kurs funktioniert.

**Comment by eric4072** [comment]
Hallo!
Hatte das Problem auch, und ganz einfach gefixt (übrigens geht das auch beim rückwärts ins Silo fahren):

Ziehe eine grüne Linie vom Beginn des Rückwärtskurses mit einer Verbindung zu deinem gesamten Netz.

AD nimmt nur den Rückwärtskurs wenn er zu dem Punkt will.

Habe seitdem kein einziges Mal das Problem dass er Kurse fährt, die er nicht soll.

LG
Eric

**Comment by TripleX1978** [comment]
Hallo!
Kann dir leider nicht ganz folgen.
Könntest du evtl. ein Foto posten?

Gruß 
André

**Comment by eric4072** [comment]
Pk, ich habs mal versucht am Handy zu zeichnen, da ich schon im Bett liege 🤣🤣
![Screenshot_20210105-233015_Autodesk SketchBook](https://user-images.githubusercontent.com/60355129/103707024-32cafe00-4fae-11eb-99a4-b3e769eb9a46.jpg)

**Comment by Iwan1803** [comment]
Es geht auch mit dunkelblauen Linien und dann braucht man keine Fanglinie mehr:
![fsScreen_2020_12_14_12_29_19](https://user-images.githubusercontent.com/47528836/103710114-7fb1d300-4fb4-11eb-9670-cc7806ca9602.jpg)

Ab ca. 14:30 Minute habe ich es ausführlich erklärt:
https://www.youtube.com/watch?v=nWL6UYMYzq0

**Comment by TripleX1978** [comment]
Danke Eric für die Hilfe.
Kann das bei meinen Strecken leider so nicht anwenden.

**Comment by TripleX1978** [comment]
@Iwan1803 
Habe die Kurse ja bereits so wie in deinem Video beschrieben angelegt (siehe oben).
Funktioniert leider immer noch nicht wirklich.
Siehe auch meine restlichen Anmerkungen dazu.

**Comment by Iwan1803** [comment]
Kannst du mal einen aktuellen Screenshot posten?

**Comment by TripleX1978** [comment]
Hier der Screenshot.
Das kuriose ist, dass ich es gerade nochmal getestet habe und von 5 Versuchen es 2mal funktioniert hat und 3mal nicht.

![LS19 - Screenshot 8](https://user-images.githubusercontent.com/63108228/104203904-f4f62b80-542c-11eb-869a-79d8529a87d3.jpg)

**Comment by Iwan1803** [comment]
Das hängt vermutlich davon ab, wie weit in die Halle reinfährt. Die Punkte zum Verlassen sind vermutlich etwas zu nah an der Halle und deswegen findet er mal den Weg raus und mal nicht.

**Comment by TripleX1978** [comment]
Habs jetzt glaube ich ganz gut hinbekommen.
Eine Frage hätte ich wohl noch...im Streckennetz wird ja ein ganzes Stück vor dem Fahrzeug der als nächstes angefahrene Streckenabschnitt weiß markiert.
Spielt dabei die Entfernung eine Rolle wie weit er vorausschauend das anzeigt oder die Anzahl an Abschnitten?
Würde es also Sinn machen in solchen Situationen viele kleinere Abschnitte anzulegen anstatt wenig große?

**Comment by KarlGutenberg** [comment]
So habe ich das gelöst!
Nicht in der Mitte rausfahren,
sondern oben rausfahren!
https://youtu.be/te4O4FZJfNo

**Comment by TripleX1978** [comment]
Hallo nochmal,
habe jetzt nochmal verschiedene Abfahrkurse ausprobiert, aber leider mit mittelmäßigem Erfolg.

Hier nochmal eine kurze Beschreibung.
- AD-Version 1.1.0.8
- Auf allen 5 Parkbuchten stehen identische Gespanne
- Wurde mit Mods und mit Standard ausprobiert
- Abfahrkurs rot fängt am Übergang von hellblau nach dunkelblau an.
  (der Startpunkt wurde mehrfach zur Halle hin oder weg versetzt)
- Abfahrkurs grün fängt am Übergang von hellblau nach dunkelblau an.
  (auch hier habe ich mehrere Startpositionen getestet)
- Abfahrkurs blau fängt am Wendepunkt oder kurz davor an (hab beides ausprobiert)

Folgendes passiert:
- Kurs rot : 1+2 fahren auf dem Kurs zum Ziel, 3+4+5 fahren geradeaus bis zum Wendepunkt und suchen sich irgendeine Linie
- Kurs grün : 1+2 können keinen Weg zum Ziel finden (erst nachdem man ein ganzes Stück rausgefahren ist geht es)
                     3+4+5 fahren auf dem Kurs zum Ziel
- Kurs blau : siehe Kurs grün

Egal was ich verändere, wenn es bei den einen funktioniert geht es bei den anderen nicht und umgekehrt.
Noch zur Info: Die Bögen die von unten kommen gehören zu der Halle gegenüber und da gibt es keine Probleme.

![LS19 - Screenshot 11](https://user-images.githubusercontent.com/63108228/114694659-0f38f180-9d1b-11eb-9c5e-f173ba62b8f9.jpg)

**Comment by TripleX1978** [comment]
Habe mittlerweile meinen Hof komplett umgebaut und das Netz nochmal überarbeitet.
Bis jetzt scheint alles zu funktionieren.
