### ISSUE TITLE
Autodrive1.1.0.7 (16.12.2020)

### ISSUE THREAD

**Issue by derbazi777** [Stephan-S/FS19_AutoDrive#1722]
Hi, 
habe folgendes Problem:

habe gestern  den  Mod installiert, verschiedene Strecken eingefahren. Heute wird der Editormodus nicht mehr angezeigt!
Was kann ich tun? Wer kann mir helfen?

**Comment by Axel32019** [comment]
@derbazi777 Hallo,
Bitte log.txt und AutoDrive....config.xml umbenannt in .txt hier hochladen.

**Comment by Axel32019** [comment]
Keine Reaktion -> Closed.
