### ISSUE TITLE
[BUG] Middle click snaps waypoint to vehicle in edit mode

### ISSUE THREAD

**Issue by mricher-git** [Stephan-S/FS19_AutoDrive#1723]
**AutoDrive Version:** 1.1.0.7

**Describe the bug**  
When editing a course, when I middle click to hide cursor so I can pan the camera around, if I happen to middle click when the mouse is near a red waypoint, that waypoint snaps to a location under the tractor. It's quite annoying, as you have to drag the waypoint around and find out where it belongs and put it back.

**If applicable - Steps to reproduce the behavior**  
Enter edit mode. Place cursor over red waypoint bubble. Middle click. The waypoint to move to a location under the vehicle.

**Comment by Axel32019** [comment]
Fix will be included in next release.

**Comment by mricher-git** [comment]
Hi Axel32019,

I downloaded and tested the fix. The point no longer snaps under the vehicle, but it certainly still moves. Given that the middle mouse is primarily used to show/hide the cursor, is there a reason why you allow both middle and right click to move points?

`                if (button == 2 or button == 3) and isDown and not AutoDrive.leftALTmodifierKeyPressed and not AutoDrive.leftCTRLmodifierKeyPressed then
                    -- middle or right mouse button to move points - waypoint at mouse position selected to move`

Assuming my middle mouse is bound to input_toggleMouse, it will move the point slightly, and then give control back to the camera.

**Comment by Axel32019** [comment]
Hello @mricher-git,
Yes, there is a reason: Mac user do only have button 1 and 2, so right mouse button is 2.
I have not found a method to detect if running on Windows or Mac - if you have any idea it will be wellcome!

**Comment by mricher-git** [comment]
Ah, makes sense. So I suppose in the mac world, they don't use button 2 for for toggling the mouse cursor, or is this causing a issue for them as well?

Anway, I took a look and the real issue IMHO is that the AutoDriveHud:mouseEvent fires before the ActionEvent for ToggleHud. Otherwise g_inputBinding:getShowMouseCursor() would already be false and we wouldn't have this problem. This new world of ActionEvents and mixing with "legacy" MouseEvent is a PITA for sure, I just re-wrote my mod to exclusively use ActionEvents for this reason. Anyway, I suppose there are a couple ways to skin cat here.

1. Perhaps move your code up to where you test "isUp" and add a check for g_inputBinding:getShowMouseCursor() is false, then we know the hud has toggled between the isDown and isUp events,, and we should just ignore the change:
Old:
```
if (button == 2 or button == 3) and isUp and not AutoDrive.leftALTmodifierKeyPressed and not AutoDrive.leftCTRLmodifierKeyPressed then
                if vehicle.ad.nodeToMoveId ~= nil then
                    -- middle or right mouse button to move points - end of move -> change waypoint coordinates now
                    ADGraphManager:changeWayPointPosition(vehicle.ad.nodeToMoveId)
                    vehicle.ad.nodeToMoveId = nil
                end
            end
```
New:
```
if (button == 2 or button == 3) and isUp and not AutoDrive.leftALTmodifierKeyPressed and not AutoDrive.leftCTRLmodifierKeyPressed then
	if g_inputBinding:getShowMouseCursor() == false then --HUD has toggled, ignore change
		vehicle.ad.selectedNodeId = nil
		vehicle.ad.nodeToMoveId = nil
		vehicle.ad.hoveredNodeId = nil
		vehicle.ad.newcreated = nil
                return; -- or add "not" to the if statement above and wrap all the code for the rest of the function.
	end
        if vehicle.ad.nodeToMoveId ~= nil then
            -- middle or right mouse button to move points - end of move -> change waypoint coordinates now
            ADGraphManager:changeWayPointPosition(vehicle.ad.nodeToMoveId)
            vehicle.ad.nodeToMoveId = nil
        end
 end
```

I don't know about testing for PC/MAC per say, but second way to fix it would be to test if button == 2 and if button 2 == input_toggleHud, and just don't allow dragging points when button 2 is also assigned as the toggle. It would be treated as a binding conflict.

Third way would be overhaul event system to use action events. It sucks, as it only does one axis at a time, so you would store posX and posY during the mouseEvent, but perform the action on button 2/3 during the action event callback. Certainly not the "quick fix" ;)

**Comment by Axel32019** [comment]
g_inputBinding:getShowMouseCursor() == false is already considered as invers logic on top of the function:
local mouseActiveForAutoDrive = (g_gui.currentGui == nil) and (g_inputBinding:getShowMouseCursor() == true)
if mouseActiveForAutoDrive then
...
So I think your change will not have no effect - did you test it already?

**Comment by mricher-git** [comment]
> So I think your change will not have no effect - did you test it already?

Wow, facepalm for me. I see your point, and you're correct. It didn't help. Now that I'm awake, I see the problem and yes, I tested it this time ;)

Because MouseEvent fires before ActionEvent, when you middle click the sequence is:
MouseEvent, button == 2, isDown, getShowMouseCursor == true
ActionEvent, setShowMouseCursor = false
MouseEvent button == 2, isUp, getShowMouseCursor == false

The issue is here:
```
if vehicle.ad.nodeToMoveId ~= nil then
    -- move point at mouse position
    AutoDrive.moveNodeToMousePos(vehicle.ad.nodeToMoveId)
end
```

This code runs after we check for button 2 down on the first run through the code, and the mouse is never exactly over the bubble/waypoint, so this code causes the bubble/waypoint to shift a little bit... this is what I'm witnessing. So the fix is easy... leave in your fix, but move the code I just posted above to before the check for button 2/3. That way, it will only attempt to move the bubble on subsequent passes, and not nudge the bubble on the first pass. Works great from my testing.

I should do a pull request, but just to be clear, I moved:
```
if vehicle.ad.nodeToMoveId ~= nil then
    -- move point at mouse position
    AutoDrive.moveNodeToMousePos(vehicle.ad.nodeToMoveId)
end
```

to line 417, just before
` if vehicle.ad.hoveredNodeId ~= nil then`

So that it only attempts to move the bubble/waypoint on subsequent runs of MouseEvent, ensuring this wasn't a toggleMouse action event.

**Comment by Muenze** [comment]
I can confirm this behaviour although I don't know how exactly to reproduce it.
I am running the game in window mode and i switch to the browser on the 2. monitor quite often, also I leave the editor open all the time.
When pressing the middle mouse button (to get the mouse pointer) and then switching to the browser and back, sometimes points were moved to a different place on the map (maybe bound by the display when it happened, but i never observed it while it happened. I only see points on paths that are near my vehicle, that are somehow moved randomly, sometimes they are in buildings and i have to remove them somehow and remake the path.

**Comment by Axel32019** [comment]
@Muenze Hello,
Did you used the fix in beta branch or the release version?

**Comment by Muenze** [comment]
I use the current release version 1.1.0.7, did I miss that it is only fixed in beta?

**Comment by Axel32019** [comment]
Yes, it is only fixed in beta - see the 2 lines above your first entry :-)
The release is dated 21th Dec.

**Comment by Muenze** [comment]
As a hotfix...
Remove the middle click binding, bind it instead to the keyboard.
I have it now on NumPad+, it's not that comfortable as middle click, but rescueing points from inside of buildings is even less comfortable ;-). I am thrilled for the new version
