### ISSUE TITLE
Fps drawdown up to 20

### ISSUE THREAD

**Issue by mechanicFS** [Stephan-S/FS19_AutoDrive#1724]
Hi! Tell me why the fps drops to 20, when it works on AutoDrive loading and unloading, it happens on the on-Board equipment

**Comment by Axel32019** [comment]
@mechanicFS Hello,
Could you please provide the log.txt and config renamed to .txt.
Ther are many topics which may influence the FPS drop...

**Comment by mechanicFS** [comment]
> @mechanicFS Hello,
> Could you please provide the log.txt and config renamed to .txt.
> Ther are many topics which may influence the FPS drop...

Yes everything is fine in the log, when it works on AutoDrive loading and unloading, it happens on the on-Board equipment

**Comment by Axel32019** [comment]
May I have a look into the log and the config?
