### ISSUE TITLE
Working with a shovel truck

### ISSUE THREAD

**Issue by mechanicFS** [Stephan-S/FS19_AutoDrive#1725]
Hi! When driving a truck-scoop AutoDrive (loading-unloading) and it is the fps that sags to 20 when it goes to unload, and everything is stable back. With tractors and trailers stable. What can this be related to?? Log without errors and so many shows.

**Comment by Axel32019** [comment]
@mechanicFS Hello,
Could you please provide the log.txt and config renamed to .txt.
There are many topics which may influence the FPS drop...
