### ISSUE TITLE
[BUG]beacon dont trun off after reaching park

### ISSUE THREAD

**Issue by bibifr** [Stephan-S/FS19_AutoDrive#1726]
**AutoDrive Version:** 1.1.0.7 RC1
**Release or Custom Zip:** Release  
**Map (If applicable):** All  
**Vehicle / Type (If applicable):**   All
**Multiplayer or Singleplayer:** both

**Describe the bug**  

The Autodrive Never turn off the beacon when reach the parking defined, So you can have 10 Tractor whit Beacon on untill you turn off them.

Thank you

**Comment by Axel32019** [comment]
Hello @bibifr ,
Could you please add your AutoDrive_config renamed to .txt here - I will have a look at it.

**Comment by bibifr** [comment]
of course it's original Tractor only ;) The only mod i have it's courseplay, autodrive and map

[vehicles.txt](https://github.com/Stephan-S/FS19_AutoDrive/files/5743370/vehicles.txt)

Best regard and merry Christmas

**Comment by Axel32019** [comment]
1. First of all you are using a beta-Version which might have issues - Please update to the Release-Version 1.1.0.7, available also ingame
2. some vehicle are set beacon controlled by AD, some not, but nethertheless it should always be switched of if AD is deactivated
If AD is still active the lights will stay ON, see button 1 description: https://github.com/Stephan-S/FS19_AutoDrive/wiki/Buttons-with-short-description
Also wish you a Merry Christmas

**Comment by bibifr** [comment]
Hello thanks for reply 

not sure about the version since it's the link i get here but ill redownload it.

AD is only system who park vehicle so it's still on when going to park and beacon is on but AD Turn off at end (button 1 is off) And beacon still stay on untill i disable it myself.

I could make a video if im not explain it properly 
but it's simple Tractor run to Parking set and turn off engine and AD but not beacon.

**Comment by Axel32019** [comment]
Screenshots from inside of the vehicles should help at the moment.

**Comment by bibifr** [comment]
![Uploading fsScreen_2020_12_26_23_20_34.png…]()

**Comment by Axel32019** [comment]
You still using 1.1.0.7 RC1 ? This is not helpful as I do not know what is in or not in this beta version.
This vehicle has still beacon disabled in the setting?
If you disable beacon manual, send the vehicle to parking, will the beacon then still be ON?

**Comment by bibifr** [comment]
Hello,
I still download it in this website lol 

There is the link in down of the page 
https://github.com/Stephan-S/FS19_AutoDrive

beacon is still Activated on Settings 
![fsScreen_2020_12_27_13_00_09](https://user-images.githubusercontent.com/9522188/103170279-7a7db700-4843-11eb-9b81-bf510feb28c9.png)

If i disable The beacon manualy (home key) he still reactivate it when go on Road but don't turn it off when arrive at parking

**Comment by bibifr** [comment]
The problem happend only in multiplayer I just tested in solo and everything works fine sorry i thinked it's was working on multi too

**Comment by Axel32019** [comment]
I observed the issue as well and found the problem - fixed already in beta branch.

**Comment by bibifr** [comment]
perfect :) thanks you ;)
