### ISSUE TITLE
[Question] I have no Map points

### ISSUE THREAD

**Issue by Kobra299** [Stephan-S/FS19_AutoDrive#1728]
**Question:**   
I've got a question... on my Ravenport map it does not show any autodrive places I am wondering what I can do to get the locations working I have tried uninstalling and removing the mod from the main save area but when I redownloaded it, it still showed no Locations

**Comment by 60erjonny** [comment]
Hay

Did you add a Ravenport road network for this too?

**Comment by Axel32019** [comment]
Hello @Kobra299 ,
Please add log.txt and AutoDrive...config.xml renamed to .txt here

**Comment by Kobra299** [comment]
[AutoDrive_config.txt](https://github.com/Stephan-S/FS19_AutoDrive/files/5752497/AutoDrive_config.txt)
[log.txt](https://github.com/Stephan-S/FS19_AutoDrive/files/5752498/log.txt)
 here are the files youasked for

**Comment by Axel32019** [comment]
Hello @Kobra299 ,
You have no road network for your map in the game - please use a G o o g le to find it.
AD does not provide any network as there are too many maps available.

**Comment by Kobra299** [comment]
[AutoDrive_Ravenport_config.txt](https://github.com/Stephan-S/FS19_AutoDrive/files/5752636/AutoDrive_Ravenport_config.txt)
this is from a older one and backup save game

**Comment by betrox007** [comment]
@Kobra299 maybe this can help to solve your question https://github.com/Stephan-S/FS19_AutoDrive/issues/1684
