### ISSUE TITLE
Kann mir jemand helfen

### ISSUE THREAD

**Issue by OstseeFarmer** [Stephan-S/FS19_AutoDrive#1729]
**Question:**   
Ich habe folgende Fehlermeldung in meiner Log. 

_AutoDrive/scripts/Specialization.lua:501: attempt to index local 'wp' (a nil value)
2020-12-27 16:57 Error: Running LUA method 'draw'.

**Comment by Axel32019** [comment]
Hallo @OstseeFarmer ,
Bitte mal die log.txt und AutoDrive....config.xml umbenannt in .txt hier anhängen.

**Comment by Axel32019** [comment]
Keine Reaktion -> Closed.
