### ISSUE TITLE
[BUG] AutoDriveVehicleData:getWorkToolParkDestination vehicle 625 X LogSpam

### ISSUE THREAD

**Issue by kferrano** [Stephan-S/FS19_AutoDrive#1731]
AutoDrive Version: 1.1.0.7-RC1
Release or selbsterstelltes zip: Release
Karte (falls relevant): Alle
Fahrzeug(art) (falls relevant): 

**Beschreibe den Bug**
Siehe Screenshot. der Logerror entstand plötzlich beim Ernten eines Feldes mit CP und der Abfahrer steht an der Parkposition und wartet gerufen zu werden mit AD

Log wird permagespammt damit

**Falls anwendbar - Schritte mit denen ich den Bug nachstellen kann**
Wenn ich wüsste was es verursacht wüsste ich auch wie man den Bug nachstellen kann
**Screenshots**
Falls relevant, bitte Screenshots beifügen
https://i.imgur.com/dITTrcM.jpg

**Comment by Axel32019** [comment]
Hallo @kferrano , Das ist eine Debug-Ausgabe. Du hast wahrscheinlich einen Debug-Haken gesetzt - bitte prüfen.

**Comment by kferrano** [comment]
Jap, das wars, versehentlich einen Haken gesetzt
