### ISSUE TITLE
[BUG] Route marker disappeared

### ISSUE THREAD

**Issue by kferrano** [Stephan-S/FS19_AutoDrive#1732]
AutoDrive Version: 1.1.0.7-RC1
Release or selbsterstelltes zip: Release
Karte (falls relevant): Alle
Fahrzeug(art) (falls relevant):

**Beschreibe den Bug**
Eine klare Beschreibung des Bugs.
Streckenmarker verschwunden. Die Streckenpunkte werden mir nicht mehr angezeigt, außer ich drücke STRG aber sobald ich STRG loslasse sind die wieder weg.
**Falls anwendbar - Schritte mit denen ich den Bug nachstellen kann**

**Screenshots**
Falls relevant, bitte Screenshots beifügen
blob:https://imgur.com/2d060501-1dc2-485c-95fb-32d66fde5f37

**Comment by haamic** [comment]
Probier mal rechte STRG-Taste. Die schaltet bei mir die "Bubbles" wieder dauerhaft ein

**Comment by kferrano** [comment]
Ah, jo danke hat geklappt
