### ISSUE TITLE
Version 1.1.0.7, 

### ISSUE THREAD

**Issue by mechanicFS** [Stephan-S/FS19_AutoDrive#1733]
Dear developers! Why on the version of AutoDrive 1.1.0.5, everything is stable with fps and work, and on the version 1.1.0.7 terrible friezes when the truck goes to unload, and when it returns, the friezes disappear. IT's NOT ABOUT MODS AND THE LOG, but about version 1.1.0.7

**Comment by Axel32019** [comment]
Dear @mechanicFS ,
How should we find out what is going wrong if you do not provide us with informations to investigate the issues, as already requested in #1724 #1725?
If you do not know where to find the requested files - we can help you.
If you do not know how to provide them to us - we can help you.
So please support us to investigate.

**Comment by mechanicFS** [comment]
> Dear @mechanicFS ,
> How should we find out what is going wrong if you do not provide us with informations to investigate the issues, as already requested in #1724 #1725?
> If you do not know where to find the requested files - we can help you.
> If you do not know how to provide them to us - we can help you.
> So please support us to investigate.

Do you understand the essence of the question at all???

**Comment by Mike1977** [comment]
> 
> 
> > Dear @mechanicFS ,
> > How should we find out what is going wrong if you do not provide us with informations to investigate the issues, as already requested in #1724 #1725?
> > If you do not know where to find the requested files - we can help you.
> > If you do not know how to provide them to us - we can help you.
> > So please support us to investigate.
> 
> Do you understand the essence of the question at all???

Do you even read his reply? He was asking for your help to investigate your issue. You have NO IDEA how important it is for a dev to see the log. Its not just about error messages. Since not everyone has issues like you, it must be something specific on your side. So don't be a sissy and provide your log.
