### ISSUE TITLE
CP mit AD

### ISSUE THREAD

**Issue by DrVirus666** [Stephan-S/FS19_AutoDrive#1734]
Hallo zusammen,
Ich lasse gerne AD und CP miteinander arbeiten. Mir ist schon vor längerer Zeit Aufgefallen, dass bei diversen Feldbearbeitungsfahrzeugen, wenn die das Feld zum Entladen (bsp. Ladewagen zum Gras entleeren) oder zum Nachladen (bsp. Saatgut, Dünger,..) die Geschwindigkeit vom AD (Feld) an CP (Straße) übergeben. Bsp. Feldarbeitsgeschwindigkeit 20km/h. Ich habe bei AD im Kästchen die Geschwindigkeit aufs höchste gestellt. CP und AD sind auf der Aktuellen Version.
Kann ich das irgendwo einstellen das die Fahrzeuge dann automatisch die Richtige Straßen Geschwindigkeit fahren?

**Comment by Axel32019** [comment]
Hallo @DrVirus666 ,
So ganz klar ist mir das Problem aus der Beschreibung noch nicht, daher:
- AD fährt auf dem Feld max. die Feld-Geschwindigkeit, oder weniger wenn Pfade gesucht/gefahren werden, Kurven etc.
- erkennt AD das Fahrzeug nicht mehr auf dem Feld ist, wird Straßen-Geschwindigkeit gefahren, oder weniger bei Kurven etc.
- AD bekommt keine Geschwindigkeitsvorgabe von CP und umgekehrt
- Grasfelder können mitunter nicht als Feld erkannt werden
Kannst Du Dein Problem auf einen un-/genannten Bereich eingrenzen?

**Comment by DrVirus666** [comment]
Hallo Axel32019,
danke für deine Hilfe.
Hier ist ein Beispiel:
Auf dem Feld (kein Grasfeld) muss Hafer angesät werden. Traktor mit Säemaschine am Feld Arbeitsgeschwindigkeit 15km/h mit CP. Wenn die Maschine leer ist und vom Feld runterfährt, ist die Feldfahrgeschwindigkeit 20km/h, wechselt der Traktor vom CP zum AD, aber die Geschwindigkeit bleibt bei 20km/h und nicht auf die im AD eingestellte Geschwindigkeit mit 53km/h.

**Comment by Axel32019** [comment]
Hallo @DrVirus666 ,
Das ist normal - siehe oben -> Pfad vom Feld wird gesucht, hier ist die Geschwindigkeit geringer, wieviel weiß ich gerade nicht.
Wenn Du eine Abfahrline auf dem Feld hättest, würde diese mit eingestellter Geschwindigkeit befahren.

**Comment by DrVirus666** [comment]
Hallo Axel32019,

dass bedeutet ich muss nicht nur Rund ums Feld einen Pfad zum Abfahren haben sondern durchs Feld auch?
Auch bei kleinen Feldern?
Ich werde es gleich morgen mal ausprobieren.
Vielen Dank nochmal für deine Hilfe.

**Comment by Axel32019** [comment]
Hallo @DrVirus666 ,
Immer mal langsam! Das ganze ist nicht so einfach...
Schau dir mal die Tutorials in Youtube an wie man mit Feldern umgeht. Da gibt es mehrere Möglichkeiten, je nach persönlichem Geschmack...
Den Pfad ums Feld kann man haben, muß aber nicht, AD findet mit der Standart-Einstellung auch so vom Feld...

**Comment by DrVirus666** [comment]
Hallo Axel32019,
ich kenne die Tutorials vom Hirschfeld und Willi, und an die habe ich mich gehalten. Da Hirschfeld fährt auf seiner WildWest seit ein paar Folgen auch CP in Verbindung mit AD für die Aussaat. 
Die Abfahrer bei mir fahren mit AD und die Fahren mit der eingestellten Geschwindigkeit.

**Comment by DrVirus666** [comment]
Hallo Axel32019,
Problem gefunden, habe den CP-Botton im AD Fenster vergessen zu aktivieren.
Vielen Dank für die Hilfe und die Zeit.
LG

**Comment by Axel32019** [comment]
OK -> closed.
