### ISSUE TITLE
[BUG] No route network visible any more - keine Streckennetz mehr sichtbar

### ISSUE THREAD

**Issue by haamic** [Stephan-S/FS19_AutoDrive#1735]
AutoDrive Version: 1.1.0.7
Release or selbsterstelltes zip: Release C 1
Karte (falls relevant): Alle
Fahrzeug(art) (falls relevant):

**Beschreibe den Bug**
Hilfe!  Ich bin eigentlich vertraut mit dem Ein-/Ausblenden der Wegpunkte in AD-Editor Modus, aber jetzt weiss ich keine Lösung mehr.
Wodurch auch immer,  sehe ich plötzlich im Editor Modus nur noch die Namen von Zielpunkten, keine Pfeile, weder Grün, Blau hellblau, noch die "Bubbles".
STRG-R im Editormodus hat keine Auswirkungen, darüber konnte ich die Bubbles sonst einblenden, aber nun fehlen ja die Pfeile auch. Das hatte ich noch nie.
Die Fahrzeuge fahren auch noch zu den Zielen, also vorhanden sind die Wegpunkte noch, aber bekomme keine Anzeige dieser hin.
Habe auch einen älteren Spielstand versucht, als es noch ging, aber auch hier wird nichts mehr angezeigt.
Woran kann das liegen? Es wurde nichts geändert. Evtl. versehentlich eine mir nicht bekannte Tastenkombination gedrückt, die das alles ausblendet?

Gruss Micha

**Falls anwendbar - Schritte mit denen ich den Bug nachstellen kann**

**Screenshots**

![streckennetz](https://user-images.githubusercontent.com/28841989/103346267-cfb00780-4a93-11eb-992a-e61c5c4d36ca.jpg)

**Comment by Axel32019** [comment]
@haamic Hallo Micha,
Bitte die üblichen Dateien hier anhängen: log.txt, vehicles.xml, AutoDrive...config.xml umbenannt in .txt hier anhängen.

**Comment by haamic** [comment]
@Axel32019 
daran liegt es nicht. es ist ein problem in meiner items.xml. 
hatte eine neues Savegame testweise gestartet, sobald ich aber die Items.xml vom anderen spielstand  einfüge, sehe ich kein streckennetz mehr. nun füge ich item für item in der xml hinzu, irgendwann bekomme ich heraus, welches item das Problem mit dem Streckennetz verursacht. ich gebe rückmeldung, wenn ich was gefunden habe.
dauert nur lange, da ich ja nach jeder Änderung den LS neu starten muss.

**Comment by haamic** [comment]
gefunden! 
Problem trat mit einem Kuhstall in verbindung mit dem Mod animalhud auf. Da ich  LS nach Bau des Kuhstalles noch nicht neu gestartet hatte, fiel das Problem mit dem Streckennetz nicht auf. Erst nach neuladen des Spielstandes. habe nun den animalhud-mod rausgehauen und nun läuft es. sehe wieder alles.
