### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Gibbanator** [Stephan-S/FS19_AutoDrive#1736]
**AutoDrive Version:** 1.1.0.7
**Release or Custom Zip:** zip (installed ingame mod area)
**Map (If applicable):** All  
**Vehicle / Type (If applicable):**   
**Multiplayer or Singleplayer:** Singleplayer  

**Describe the bug**  
using semi and trailer with autoddrive from field to bunker. Works great but does not detect the vehicle that is leveling the bunker. Runs into the vehicle. Was working good until the new upgrade not does not detect the vehicle at all.

**If applicable - Steps to reproduce the behavior**  
The vehile that is leveling the bunker is not given anytime to pull out of bunker to park to let the semi (on autodrive) in to unload. The vehicle that is leveling is on a CP course but radias is 50m to detect courseplay or autodrive vehicles.

**Screenshots**  
https://i.gyazo.com/5996d95666be3870e287890a896e1dc3.jpg

**Comment by Axel32019** [comment]
Hello @Gibbanator ,
Which CP version do you use?
CP is controlling the AD vehicle, i.e. AD vehicle will stop at radius set in CP, until CP worker is in park position. When CP reached park position AD will drive in bunker and leave. If AD is away CP will continue.

**Comment by Gibbanator** [comment]
I always keep my CP up to date and I get notified when new version is released so I am currently running 6.03.0019 along with autodrive 1.1.0.7. do you think there is a problem with CP? they have put out 2 releases since 1.1.0.7 of autodrive.

no matter what I do I can not get Autodrive to wait until the tractor with blade moves out of bunker. the semi and trailer with Autodrive backs into the bunker to unload. 

The tractor with the blade that is leveling the bunker is set up with CP course for bunker I have tried 50m and up to 100m radius detection but the Autodrive semi and trailer are not detecting the tractor and runs into it each load.

as I mentioned it was working before. rebooting computer and game does nothing to correct this problem.

**Comment by Axel32019** [comment]
As already told: CP hold the driving of AD vehicle - AD is not detecting any tractor with blade.
If I see it correct CP function has changed in 0019. Could you test the following:
- set up CP to detect all vehicles (not only CP)
- drive manually in the range -> the tractor with blade should go to park
If not, there is an issue in CP...

**Comment by Tom20214** [comment]
[https://github.com/Courseplay/courseplay/issues/6587](url)

Hier ist die Issue von CP.

**Comment by Tom20214** [comment]
`https://github.com/Courseplay/courseplay/issues/6587

Hier ist die Issue von CP.

**Comment by Tom20214** [comment]
https://github.com/Courseplay/courseplay/issues/6587

Hier ist die Issue von Courseplay.

**Comment by Gibbanator** [comment]
tried it with Detect All. Tractor will go to park as it did before but does not stay it starts bunker course again when semi starts dumping.

I will post in Courseplay. I am sure they will say its a Auto Drive problem.. Thanks for trying to help.

**Comment by Axel32019** [comment]
Most likely CP issue, so closed here.
