### ISSUE TITLE
Parking Button 

### ISSUE THREAD

**Issue by arp77** [Stephan-S/FS19_AutoDrive#1737]
Hi, when I assign a parkinglot for a vehicle, the "P" button is not highlighted anymore.
So I don't know, if a vehicle has already assigned a parkinglot. 
And when I hover over the "P" button, I could not see anymore which parkinglot is assigned to the vehicle.

AD Version: 1.1.0.7. RC1

**Comment by 60erjonny** [comment]
Hallo
This is normal when you attach a tool to this vehicle. You can then also assign a parking space to this device. When you uncouple again, the car park can be seen from the vehicle.
Please also read the Release - Info`s on the Git-Hub page.
mfg
jonny

**Comment by arp77** [comment]
Ah, ok, thank you.
Mfg
Arp77
