### ISSUE TITLE
[Question] connection point for the cours

### ISSUE THREAD

**Issue by kferrano** [Stephan-S/FS19_AutoDrive#1738]
**Question:**   
Do I have to move more than just this trigger so that the connection point for the cours is further forward?

Trigger is moved
https://prnt.sc/wef6xi

but he still takes the old position
https://i.imgur.com/1NmKPOC.jpg

**Comment by Axel32019** [comment]
Hello @kferrano ,
AD takes "components[1].node" as reference - in your case ...main_component1

**Comment by kferrano** [comment]
oh ok, and you can't move this position, can you?

**Comment by Axel32019** [comment]
No, this is the reference for everything - Sorry.
