### ISSUE TITLE
[BUG]save route

### ISSUE THREAD

**Issue by envikowaty** [Stephan-S/FS19_AutoDrive#1739]
**AutoDrive Version:** 1.1.0.7 
**Release or Custom Zip:** Release  
**Map (If applicable):** All  
**Vehicle / Type (If applicable):**   
**Multiplayer or Singleplayer:** Singleplayer  

**Describe the bug**  
Saving route network

**If applicable - Steps to reproduce the behavior**  

To reproduce the bug, create a network of routes and try to save it (put your name for the network), press save and then press icon to leave the menu - game will freeze and switch off.
But if you press ESC on the keyboard the menu will close and the game will still work without any problem 

**Screenshots**

**Comment by Axel32019** [comment]
Hello @envikowaty ,
Please add log.txt and AutoDrive_config.xml renamed to .txt here.

**Comment by envikowaty** [comment]
Here you go:

[AutoDrive_config.txt](https://github.com/Stephan-S/FS19_AutoDrive/files/5760358/AutoDrive_config.txt)

**Comment by Axel32019** [comment]
What about log.txt ?

**Comment by envikowaty** [comment]
ohh sorry. here you go:

[log.txt](https://github.com/Stephan-S/FS19_AutoDrive/files/5760554/log.txt)

**Comment by Axel32019** [comment]
You did not start the game and saved the routes with this log, right?

**Comment by envikowaty** [comment]
Well I did not start the game after crash, I just came straight here to post that bug

**Comment by Axel32019** [comment]
This log gives no information - please add the log if you see the issue.

**Comment by envikowaty** [comment]
I found the problem, one of the mods was somehow corrupted, I've replaced it and now it's all ok.👌

**Comment by Axel32019** [comment]
OK -> Closed.
