### ISSUE TITLE
[BUG] Path calculation fails directly after trailer is filled with chaff by a chopper.

### ISSUE THREAD

**Issue by Th301** [Stephan-S/FS19_AutoDrive#1740]
**AutoDrive Version:** 1.1.0.7   
**Release or Custom Zip:** Release  
**Map (If applicable):** Nordfriesische Marsch 4-fach  
**Vehicle / Type (If applicable):** Variuous  
**Multiplayer or Singleplayer:** Singleplayer  

**Describe the bug** 

First of all: Happy new year to the whole team and the community! :)
 
I know, there was already an issue regarding this  (#1420 ) but it is closed with the comment, that it is fixed in the version 1.1.0.6.
I am using version 1.1.0.7 and it worked fine on the fields I already harvested. On the bigger field 16 it is now a bit annoying. There is one chopper and 4 tractor-trailer combinations to transport the chaff to the farm. In the moment, the trailer is completely filled, the AD-Driver reports that he can not find a path to the target and directly quits his job. This happens even if the tractor stands directly next to a part of the AD network. Clicking on "Start Autodrive" directly employs a driver and the path calculation is no problem at all.

Do you need a lod ? Or are you perhaps already in this issue?

Best regards

**Comment by Iwan1803** [comment]
Da du in dem anderen Beitrag auf deutsch geantwortet hast... 😎
Sind die Einstellungen noch identisch oder wie sehen sie für die Abfahrer aktuell aus?

**Comment by Th301** [comment]
Hallo @Iwan1803 ,

danke für deine Reaktion.
Leider komme ich aktuell nicht dazu entsprechende Screenshots zu machen. Man muss ja irgendwie wieder arbeiten jetzt ;)

Die Einstellungen habe ich aber eigentlich nicht verändert. Die Felder wurden kurz nacheinander geerntet.

Gäbe es denn spezielle Einstellungen an die du denken würdest, wenn das Verhalten auftritt?

**Comment by Iwan1803** [comment]
Die Option "Feldausfahrt" steht bei mir immer auf "nächstgelegen", wobei ich eine blaue Fanglinie rund ums Feld habe.
Ansonsten könnte auch eine aktivierte Fruchtumfahrung für Probleme sorgen (kann, muss aber nicht).
Was mir schon passiert ist: ich habe neue Fahrzeuge gekauft und einfach vergessen, die Einstellungen anzupassen.

**Comment by Th301** [comment]
Die blaue Fanglinie habe ich auch um die Felder! Selbst wenn die Fahrzeuge direkt neben dieser Fanglinie standen, die natürlich auch ans normale Straßennetz angebunden ist, wurde kein Pfad berechnet. Erst nach dem Neustart von AD.

Deinen Hinweis mit den Einstellungen probiere ich aus, sobald der Winter auf der Marsch vorbei ist ;)

**Comment by Anonymous-any** [comment]
Hello @Iwan1803 ,

I get too no path for reach the combine by CP drived, I try to search what is not correct, I use a dl AD file that I've not made myself for a map who contain blue line's inside and around all fields is it this culprit of the problem ?
So I saw you say about Field exit so what is must set for avoid this please ?

Br

**Comment by realskudd** [comment]
> I get too no path for reach the combine by CP drived, I try to search what is not correct, I use a dl AD file that I've not made myself for a map who contain blue line's inside and around all fields is it this culprit of the problem ?

I have started using the bi-directional paths (blue line) around my fields on certain maps. Maybe that's part of the issue?

**Comment by Anonymous-any** [comment]
Idk waiting for the boss's I related this because of my reads and waiting for see.

**Comment by Axel32019** [comment]
Hallo @Th301 , @realskudd , @Anonymous-any , Gibt es hier noch Neuigkeiten?

**Comment by ThLoser** [comment]
Any updates on this, still having this issue and its not even far from the path to the silo :/ 
![bild](https://user-images.githubusercontent.com/9365662/118399059-91d70880-b65b-11eb-9e23-bc350973b1b8.png)

**Comment by Iwan1803** [comment]
Wrong issue or what problem do you have?

**Comment by ThLoser** [comment]
> 
> 
> Wrong issue or what problem do you have?

Cant find the path on fields

**Comment by Iwan1803** [comment]
And from this one sentence and the cut screenshot we are now supposed to see the problem?
Wait, i'll consult my crystal ball or call my psychic....

**Comment by ThLoser** [comment]
> And from this one sentence and the cut screenshot we are now supposed to see the problem?
> Wait, i'll consult my crystal ball or call my psychic....

You do that. Found out that Therese was a new version that is not on modhub and that one almost worked. Now there is a new problem. That doesn't affect this topic. But check your ball.

**Comment by Th301** [comment]
Sorry for being absent for so long.
Yesterday I dowloaded version 1.1.1.2 and started working on the fields of NF Marsch. At first, everything worked fine. After some rounds, the error from the initial post occurred again.

The truck drove to the harvester, was loaded and than stopped working with the error, that he could not calculate a path to the target location.

It is a bit confusing because it worked for some rounds before and than suddenly, without changing any settings it stoped working.

I saw, that there was a similar issue only 2 days ago but the solution was not really described.

**Comment by Iwan1803** [comment]
And again: should i consult my crystal ball or call my psychic?
Which settings are set for the truck to unload? Are there lines around the field with several exists to the road network? Etc. etc. etc.

**Comment by Th301** [comment]
Du brauchst keine Glaskugel, sorry. Ich dachte ich hatte es im initialen Post schon beschrieben.

Es gibt die blaue Fanglinie um das Feld. Die Feldausfahrtstrategie ist auf "nächstgelegen" eingestellt.

Was mich so wundert ist, dass es normal lief und dann plötzlich, ohne etwas zu ändern nicht mehr. Ein möglicher Unterschied ist, dass das Abladen des Dreschers jetzt weiter in der Mitte des Feldes passiert, der Truck ist also weiter von der Fanglinie entfernt. Aber das sollte ja eigentlich kein Problem sein?

In einem anderen Thread hab ich gelesen, dass bei dem User die Config ein Problem hatte, was genau nun dahinter steckte hat er aber nicht geschrieben und der Thread ist geschlossen.

**Comment by Th301** [comment]
Eine kleine Ergänzung:

Karte: NF Marsch 4-fach 2.8
Feld: 41
Fanglinie: rundherum
Die Fanglinie habe ich erweitert an einer Stelle mit einem kleinen Loop um einen Überladepunkt anzufahren.
Feldausfahrtstrategie: Nächstgelegen

Kann es sein, dass es mit der Entfernung des Fahrzeugs zur Fanglinie zu tun hat? Folgende Situation habe ich beobachtet:
Die Arbeit wurde auf dem Feld begonnen. Der Überlader (Autodrive) fuhr wie gewünscht die Drescher an, hat das Getreide abgetankt und fuhr dann zum Überladepunkt. Als sich die Arbeit der Mitte des Feldes näherte, trat das Problem wie beschrieben auf. Nach dem Abtanken der Drescher schaltet Autodrive mit der Meldung "Der Fahrer von XXX konnte keinen Pfad zum Ziel berechnen" ab. Ich musste dann manuell sehr dicht an die Fanglinie fahren, erst dort konnte ich AD wieder aktivieren.
Das musste ich eine ganze Weile so machen, als die Arbeit in der Nähe der Feldmitte stattfand. Als sich die Drescher der anderen Feldseite, und damit auch der Fanglinie, wieder genähert haben, lief Autodrive wieder problemlos und hat abgetankt und anschließend den Überladepunkt über die Fanglinie angefahren.

**Comment by Iwan1803** [comment]
Kann es vielleicht sein, das irgendwo der Weg "fehlerhaft" ist und er deshalb keinen Weg findet? Vielleicht irgendwo eine Unterbrechung oder eine Linie falschrum verbunden?
Nimm einfach mal ein Vanilla-Fahrzeug, stell es an verschiedene Stellen auf dem Feld und lass es dann einfach nur runter vom Feld fahren.

**Comment by realskudd** [comment]
> Could it be that the path is "flawed" somewhere and therefore it cannot find a way? Maybe a break somewhere or a line connected the wrong way round?

This is most likely the issue. I found later that my issues were due to the path either having a sudden switch back the other direction, or it was broken at some point. Your best bet is to carefully drive the path manually, inspecting each node. It's even more helpful to look where you have junction nodes, as those are usually what cause the headache.

In my case, it wasn't anything to do with the bi-directional path around my field, but rather, was an unreasonable junction somewhere between the silo and the field entrance. Once I fixed that, all was well.

**Comment by Axel32019** [comment]
@Th301 Schon etwas gefunden?

**Comment by Th301** [comment]
@Axel32019  Nein, leider kam ich seither nicht mehr auf die Farm 😞

**Comment by Axel32019** [comment]
@Th301 Wenn's was Neues gibt bitte wieder aufmachen.
