### ISSUE TITLE
[BUG]Fahrer erkennt Trigger nicht

### ISSUE THREAD

**Issue by lutionx** [Stephan-S/FS19_AutoDrive#1741]
AutoDrive Version: 1.1.0.7
Release or selbsterstelltes zip: Release
Karte (falls relevant): Gemeinde Rade
Fahrzeug(art) (falls relevant):

**Beschreibe den Bug**
Eine klare Beschreibung des Bugs.
Ich habe für die BGA auf der Gemeinde Rade für die Fahrsilos abladepunkte und Kurse erstellt, wie auf den anderen Maps bisher auch. Der Abfahrer fährt die Kurse auch wie gewünscht ab, allerdings lädt er im Silo nicht ab. Er durchfährt das Silo bis zum Wegpunkt und schäldt dann wieder auf den Wegpunkt des Feldes. Habe im Silo daneben getestet mit rückwerts abladen. Leider das selbe Problem.
Auf den anderen Karten hatte ich damit keine Probleme. Habe auch die selben Fahrzeuge genutzt.
Leider bin ich noch kein Profi was Autodrive angeht, daher die Frage hier.
Ansonsten wirklich ein geniales System.
Grüße

**Falls anwendbar - Schritte mit denen ich den Bug nachstellen kann**

**Screenshots**
Falls relevant, bitte Screenshots beifügen

**Comment by Axel32019** [comment]
Hallo @lutionx ,
Bitte Screenshot vom Silo, AutoDrive_config.xml umbenannt in .txt und genaue Version / Link der Map hier einfügen.

**Comment by Iwan1803** [comment]
Dann werden wohl die Durchfahrsilos nicht als solche erkannt oder musst du das Gelände, auf dem sie stehen, ggfs. erst kaufen?

**Comment by lutionx** [comment]
Habe es gerade noch mal getestet. Das Land gehört mir. Habe es auch noch mal verkauft und wieder gekauft. Leider ohne Erfolg.

Ich würde gerne mal einen Screenshot und was sonst noch nötig ist Hochladen. Leider komme ich mit Github noch nicht ganz klar. Kann mir jemand das kurz erklären :)
Werde parallel es mal mit anderen Silos testen

**Comment by Axel32019** [comment]
Dateien einfach in das Eingabefeld ziehen, jedoch von den xml Dateien vorher eine Kopie machen und die Endung .txt hinzufügen.

**Comment by Axel32019** [comment]
Ohne die Dateien können wir leider nichts machen -> closed.
