### ISSUE TITLE
[BUG] AD wants to refuel vehicle with deactivated Automatic Refuel

### ISSUE THREAD

**Issue by bojanh66** [Stephan-S/FS19_AutoDrive#1742]
**AutoDrive Version:** 1.1.0.7 RC1
**Release or Custom Zip:** Release  1.1.0.7 RC1
**Map (If applicable):** All  
**Vehicle / Type (If applicable):**   
**Multiplayer or Singleplayer:** Singleplayer  

**Describe the bug**  
In courseplay, i have selected to use Autodrive for unload/refill.
In Autodrive options, Automatic refueling is No (disabled).
But when the tractor is low at fuel, Autodrive will stop CP course and retake vehicle and drive it to fuel station, even if i have enough fuel for at least 10 minutes of work.
It doesnt make a difference if i use Yes or No at option Automatic Refueling.
So i guess this is a bug.

**If applicable - Steps to reproduce the behavior**  

**Screenshots**

**Comment by 60erjonny** [comment]
Hallo
I'm not so sure now, but there are settings under CP that could be responsible for this.
![fsScreen_2021_01_05_13_31_37](https://user-images.githubusercontent.com/63659182/103646923-c1159480-4f5a-11eb-80bf-d27617124f46.png)

**Comment by bojanh66** [comment]
Yes i know for that, those settings are at default and tractor continue to work even with low fuel as long as "use Autodrive for unload/refill" is disabled in Courseplay.
Here is the video, take a closer look:
https://youtu.be/NEf0fjgdI78

**Comment by 60erjonny** [comment]
Ok yes, but you can only switch this function off in AD.
In CP, as far as I know, that is not possible ...

**Comment by Axel32019** [comment]
The refuel is directly called by CP and executed by AD. You are right the setting for automatic refuel will not affect this and therefor could not be avoided by the AD setting.
May be you could adress your request to CP...

**Comment by Axel32019** [comment]
Fixed in Coursplay -> closed.
