### ISSUE TITLE
Silo Abstand als Fzg spezifische einstellung [Feature Request]

### ISSUE THREAD

**Issue by Dueesberch** [Stephan-S/FS19_AutoDrive#1743]
Ich arbeite gerne mit Überladewagen am Feld. Wenn ich den Siloabstand auf zb 100m setze, wird das Rohr entsprechend früh ausgeklappt und bleibt gerne in Bäumen etc. hängen. Setze ich den Abstand aber auf zB 25m passt es nicht mit dem Arbeit ein Fahrsilo zu befüllen, da er dann zu spät den Trigger erkennt.

Wenn der Silo Abstand Fzg spezifisch gesetzt werden kann, ist es möglich diesen an die entsprechende aktuelle Arbeit anzupassen.

**Comment by Axel32019** [comment]
Hallo @Dueesberch ,
Danke für den Hinweis. Das Abladen im Silobunker war leider noch nicht ganz optimal umgesetzt - hab das gleich noch mit den anderen Sachen angepasst. Wenn Du möchtest kannst Du die beta ja mal testen...
Bin mir sicher Du weißt wie Du sie bekommst :-)

**Comment by Dueesberch** [comment]
Hallo @Axel32019,
ich hab mal getestet (Du hast nicht gesagt ich soll mal probieren :D ). Hat leider etwas länger gedauert und ist bis jetzt auch nur der Fahrsilotest (Fahrsilo befüllen), aber Rest kommt noch. Hab etwas gebraucht das Setup für einen vollautomatischen Test auszutüffteln, weshalb es auch nicht der letzte Stand beim Test ist. Commit ID hab ich ins PDF aufgenommen.

[auswertung_fahrsilo_distanz_test.pdf](https://github.com/Stephan-S/FS19_AutoDrive/files/5926376/auswertung_fahrsilo_distanz_test.pdf)

Ich denke Aufbau etc. geht aus den Videos ganz gut hervor. Die Entfernungswerte von EasyDevControls nicht beachten. Die X/Y Koordinaten in der Minimap waren einfacher. Ist mir aber erst beim Auswerten der Videos aufgefallen.
Da ich es als Blackboxtest ohne Vorgabe des erwarteten Resultats ausgeführt habe, habe ich auf eine Pass/Fail Bewertung verzichtet. Aber, dass Extrarunden gedreht werden ist wahrscheinlich nicht gewollt.

Überladewagen in Trailer, Befüllen / Entleeren am Silo sind die nächsten in der Pipeline.

**Comment by Axel32019** [comment]
Hallo @Dueesberch,
Da hast Du Dir aber verdammt viel Arbeit gemacht - Danke für die Unterstützung dieses Projektes, auch im DC!

Hier einige Anmerkungen:
Bei AD Start wird geprüft ob am Ende zum Parkplatz zu fahren ist oder nicht.
Der Anhänger hat einen Parkplatz zugewiesen.
Aus den Videos vermute ich das ist deaktiviert, sonst würde immer das gleiche Ziel am Ende angefahren.
Der ParkTask wird nach dem Abladen aufgerufen und prüft ob zu einem Parkplatz zu fahren ist, wenn nicht wird zum 1. Ziel gefahren.
Da dies ein neuer Task ist wird ein Weg dahin gesucht, was vorausschauend vor dem Fahrzeug beginnt und damit das schon erreichte Ziel "übersehen" wird.
Somit wird am Ende immer noch eine Runde gedreht.
Könnte man noch optimieren...

Für Tests emfehle ich eher den Modus Abholen/Abladen zu verwenden, dann wird deutlicher wohin es nach dem Abladen geht. (keine Kritik!!!)

Die Abdeckungen werden ab "Silo-Abstand" und wenn zu Be-/Entladen ist angesteuert. Verzögerungen können natürlich durch Animationen entstehen.

Die Geschwindigkeit wird ab "Silo-Abstand" und wenn zu Be-/Entladen ist angepasst, im Durchfahrsilo noch komplizierter entsprechend Länge und Ablade-Durchfluß (oder wie man es nennen mag).

Beim Abladen "Test 10m Siloabstand - 143m Marker" kommt noch eine Zusatzbedingung zur Anwendung:
(trigger.bunkerSiloArea ~= nil and distanceToTarget < 100)
Somit beginnt das Abladen im Bunker und zieht sich dann hinaus.

Ich hoffe das hilft etwas zum Verständnis.
Der generelle Ansatz von AD ist ja: Immer so einfach wie möglich für den Anwender.

**Comment by Dueesberch** [comment]
Moin @Axel32019,

so viel Arbeit ist es nicht, wenn man es automatisiert ;). Das Setup einrichten macht man ja zum Glück nur einmal. 
Den Punkt Modus sehe ich nicht als Kritik. Geht ja darum etwas zu testen und da sollten die Einstellungen schon passen, um valide aussagekräftige Ergebnisse zu erhalten.

Hab den Test jetzt nochmal stellvertretend, da es ja reporduzierbar ist, für alle mit 50m Siloabstand und dem letzten Build (heute morgen frisch von Github gezogen) gemacht.
Parkplatz ist nicht zugewiesen. Modus aber noch Abladen. Er dreht auch ohne Parkplatzzuweisung, sowie Einstellung "Am Ende Parken = Nein" eine extra Runde (Doppeltes Du-darfst-nicht-parken :) ). 
Hab bei YT den erneuten Test mit 78m Marker / 50m Siloabstand hochgeladen. https://youtu.be/iXOZe6Dn7SI Die anderen verhalten sich analog.
Im HUD steht "Fahre zu Abladepunkt", er läd ab, fährt weiter bis zum Marker, welcher hinter dem Abladeende liegt, springt dann im HUD auf "Fahre zum Zielpunkt" und dreht die extra Runde. Sollte im Falle, dass es keinen Parkplatz gibt, bzw. dieser nicht angefahren werden soll, der Abladepunkt = Zielpunkt sein? 
Modus Abholen / Abladen kann ich heute abend nochmal laufen lassen. Jetzt wo das Setup steht muss ich nur die Grundeinstellungen machen und in Rennen lassen.

**Comment by Axel32019** [comment]
Hallo @Dueesberch ,
Im HUD steht "Fahre zu Abladepunkt", er läd ab, fährt weiter bis zum Marker, welcher hinter dem Abladeende liegt, springt dann im HUD auf "Fahre zum Zielpunkt" und dreht die extra Runde. Sollte im Falle, dass es keinen Parkplatz gibt, bzw. dieser nicht angefahren werden soll, der Abladepunkt = Zielpunkt sein?

Das bestätigt o.g. Anmerkung:
Der ParkTask wird nach dem Abladen aufgerufen und prüft ob zu einem Parkplatz zu fahren ist, wenn nicht wird zum 1. Ziel gefahren.
Da dies ein neuer Task ist wird ein Weg dahin gesucht, was vorausschauend vor dem Fahrzeug beginnt und damit das schon erreichte Ziel "übersehen" wird.
Somit wird am Ende immer noch eine Runde gedreht.
Könnte man noch optimieren...

In anderem Modus sollte es so laufen wie vorher geschrieben.
Bin mal gespannt ob Du das bestätigt bekommst...

**Comment by TripleX1978** [comment]
Hallo zusammen,

habe ein ähnliches Problem wie @Dueesberch .

Lasse ich den Wert auf 100m stehen, haben z.B. die Fahrzeuge auf dem Weg zu meinem Düngersilo das "Problem", dass der Kalk-Trigger schon erkannt wird und sich das Fahrzeug bis zum eigentlichen Ziel einen mit 5km/h abstottert. Stelle ich den Wert auf z.B. 10m fahren diese flüssig daran vorbei bis zum eigentlichen Ziel.

![LS19 - Screenshot 14](https://user-images.githubusercontent.com/63108228/114850562-33f79c80-9de1-11eb-97de-5be125d1ab5a.jpg)

Da der Fall ja schon was älter ist, welche AD-Version habt ihr genutzt?
Wie sollte man den Wert denn am besten in am Zukunft einstellen?
