### ISSUE TITLE
Non-preferred routes

### ISSUE THREAD

**Issue by SpiderTash** [Stephan-S/FS19_AutoDrive#1745]
Is there a way to set preferred and not preferred routes for vehicles to use?  There are times a tractor might take a cultivator through a sale point because it is the quickest route and it gets stuck.  So want to set that route as a non-preferred route so it will only use that route if it needs to in order to get to that waypoint.
Thank you

**Comment by Iwan1803** [comment]
To avoid driving over target point, you should enlarge "maximum detour" in the AD settings.

**Comment by Iwan1803** [comment]
@SpiderTash is that enough of an answer or do you need further help?
Otherwise just have a look on Discord: https://discord.gg/9D4B5hX
There is normally always someone there who can help 😉
