### ISSUE TITLE
Zwei-Wege Transport

### ISSUE THREAD

**Issue by GulliGriff** [Stephan-S/FS19_AutoDrive#1746]
Hallo AD-Team,
ich fände es super, wenn AD nicht nur was hinbringen sondern auch was mit zurück nehmen könnte. Gerade wenn es darum geht Produktionen zu befüllen, denn diese haben oftmals fertige Produkte die mit zurück genommen werden könnten. 
Das würde ein weiteres Fahrzeug sparen. Mal abgesehen spart das natürlich auch Fahrzeug- und Lohnkosten ;)
Vielleicht ist das ja eine interessante Geschichte, in meiner Com fanden die Leute die Idee gar nicht mal so schlecht.
LG

**Comment by Iwan1803** [comment]
Nicht falsch verstehen, aber bei manchen "Wünschen" glaube ich, das ein Simulator vielleicht das falsche Spiele für den einen oder anderen ist.... 🤪

@Axel32019 
ich bin mir fast sicher, das wir das Thema "Auftragsliste" schon mal hatten, oder?

**Comment by GulliGriff** [comment]
doch, verstehe ich falsch. dann frage ich mich wenn du so auf "simulator" gehst warum es dann überhaupt CP und AD gibt und du es auch so rege beim spielen benutzt. 
also passt dein spruch hier ja nu ganz und gar nicht! 
Ganz ehrlich Iwan, geht nicht, will ich nicht und ich kann dir nicht helfen... was anderes kam von Dir noch nie in meine richtung. Komisch andere helfen, aber du... naja, dann schliess ich das hier und werd nix mehr schreiben dann musst du mir auch nicht wieder sagen, geht nicht, will ich nicht und ich kann dir nicht helfen... Wirklich schade

**Comment by Axel32019** [comment]
Mal bitte nicht so schnell die jungen Herren. Bis zum nächsten LS wird wohl noch etwas Zeit vergehen - mal sehen was wir bis dahin noch alles machen können...

**Comment by GulliGriff** [comment]
@Axel32019 Sorry Axel, aber ich habe wirklich gedacht dass das gar nicht so verkehrt wäre, wenn der auf dem Rückweg auch was mitnehmen könnte und dann muss ich mir wieder sowas von Iwan anhören. Da vergeht es einem echt Euch was zu Fragen. Ein Auftragsbuch wäre für mich was anderes und das fände ich tatsache too mutch aber ein button für hin- und rückweg und das ja auch nur für be- und entladen mit dem jeweiligem fillType wäre sicher nicht so aufwändig (dachte ich) als so ein auftragsbuch.
Aber vielleicht gehe ich da zu blauäugig an die Sache, habe ja auch keine ahnung vom skripten. Da es die funktion be- und entladen gibt müsste das nicht als neue funktion eingebaut werden, lediglich (wenn man es wünscht) eine wiederholung im kompletten arbeitsgang nur für den rückweg eben... klar bräuchte man dann in der maske irgendwie dass man die haltepunkte für den rückweg und das ziel und die frucht einstellen kann, aber selbst die gibt es ja eigentlich schon.

**Comment by Iwan1803** [comment]
@GulliGriff 
Ich bin nur verantwortlich für das, was ich schreibe, aber nicht für das was du verstehst. Und wem der Schuh passt....
Also komm mal wieder runter 😉

**Comment by Dueesberch** [comment]
@GulliGriff wie genau sollte den der ablauf dann sein? fahre zu ziel a und lade dort ab und lade an ziel a auch auf? wird imho selten (gar nicht) funktionieren da es ja immer unterschiedliche trigger sind. zb einmal abladetrigger am silo und beladetrigger am selben silo. also müsste AD erst zu ziel a abladen, dann zu ziel b aufladen und dann zurück. die frage ist wie lang willst du diese kette machen? schlussendlich ist es doch dann ein kleines auftragsbuch.

**Comment by Tensuko** [comment]
Mal zu dem Punkt Automatisierung im LS:
Wir von CP haben uns auch mit voller Absicht gegen eine komplette Automatisierung entschieden.

Morgens auf den Knopf drücken und Abends mit höherem Kontostand, reparierten, geputzten und getankten Fahrzeugen alles stehen haben ist nicht zielführend unserer Meinung nach und hat dann auch nichts mehr mit einem Simulator zu tun.

Eher geht es darum, die Fahrer zu nutzen um parallel andere Dinge zu erledigen, Dinge die man sonst zu zweit macht und die Fahrer zu managen (neue Aufgaben verteilen, Arbeiten starten usw). Zusammen mit AD ist mit CP auch bereits viel mehr automatisierung möglich, als was wir uns vorgestellt hatten (nicht negativ gemeint).

Ich finde aber man sollte mal den Ball flach halten und sich fragen was man eigentlich will und da muss ich @Iwan1803 recht geben.

**Comment by GulliGriff** [comment]
ich rede lediglich davon, dass er auf dem Rückweg was mitnehmen kann. was interpretiert ihr denn da alles rein? Wäre es denn so sinnfrei wenn der nicht leer zurückfahren muss? Wenn das so abwegig ist, warum hat dann @Axel32019 hier wieder auf gemacht?

@Dueesberch habe ich eigentlich geschrieben, theoretisch müsste er den Modus abholen und abliefern 2x hintereinander ausführen nur eben mit anderen haltepunkten und frucht. So kann der am abladetrigger abladen und am beladetrigger wieder beladen.

@Tensuko ich sehe den LS nicht wirklich als Simulator (dazu fehlt einfach noch viel zu viel) sondern als Spiel das mir halt mega spass macht und Schuld daran seit ihr (die Macher von CP und AD) und das meine ich äusserst positiv! ich glaube dass ich nicht der einzige bin der die beiden so rege nutzt wie ich. 
Ich mag es eben wenn es auf der Map wuselt und da ordentlich Bewegung ist. Ne komplette Automatisierung finde ich nu auch nicht so toll... da kann ich dann auch Anno o.ä. zocken...

**Comment by eric4072** [comment]
Möchte da gern mal mit einsteigen:

Seit der hervorragenden Versionen von AD und CP kamen ganz neue Möglichkeiten, wie wir "Spieler" den LS nutzen können. Das solltet Ihr Scripter mal nicht vergessen 😉 vor allem wart Ihr es, die diese Tür mit eurer hervorragenden Arbeit geöffnet haben...

Ich persönlich fahre eigentlich gar nichts selbst, ausser beim einfahren. Alles andere macht CP und AD. soll heissen, ich spiele LS als reine, vollautomatisierte Landwirtschafts-Wirtschaftssimulation, weshalb es auch wirklich schwer ist, es so im MP zu spielen...

worauf ich raus will: Ich kann mir gut vorstellen, dass es mehr wie mich gibt. Aus diesem Stil den LS zu spielen, kamen ja auch schon richtig gute Ideen, die jetzt in den aktuellen Versionen auch enthalten sind.

Daher finde ich die Idee, die Fahrzeuge sinnvoll auszulasten, gar nicht so schlecht. Vorallem da der LS trotz meines wirklich starken Rechners bei 15 Fahrzeugen in die Knie geht 😂

just my 2 cents 😉
nochmals danke für Eure Arbeit
Eric

**Comment by Dueesberch** [comment]
Wow. Das ist, trotz deines Dankes und des Hinweises auf deine unbedeutende Meinung, der frecheste feature request den ich bis jetzt gesehen habe. Weil die Scripter, was ich schon mal eine herablassende Bezeichnung für einen Programmierer finde, AD und CP entwickelt haben sind sie jetzt scheinbar in der Pflicht alle Wünsche, und seien sie noch so Absurd und / oder gegen die Gedanken und Meinung der Entwickler, zu erfüllen. Die Leute die hinter allen Mods, nicht nur AD, stecken entwickeln diese in ihrer Freizeit, ohne Bezahlung. Das sollten wir Nutzer mal nicht vergessen und akzeptieren wenn ein request abgelehnt wird. Warum auch immer.

**Comment by Iwan1803** [comment]
Natürlich sind wir auf die Ideen von euch Spielern angewiesen und AD (und CP) wollen sich auch weiterentwickeln, aber das heißt noch lange nicht, das wir auch alles umsetzen werden (aus welchen Gründen auch immer). Wir sind hier schließlich nicht bei "wünsch dir was" 😉
Die Resourcen "Mensch" und "Zeit" sind nun mal begrenzt und wenn eine Idee einfach zu komplex in der Ausarbeitung und Umsetzung ist, dann muss halt auch mal ein "nein" akzeptiert werden (was hier ja noch nicht gesagt worden ist).
Wir haben leider schon einige gute und interessante Ideen ablehnen müssen, weil sie entweder nicht dem Sinn von AD entsprachen oder einfach zu viel Zeit in Anspruch genommen hätten. Wenn man viel Zeit für die Umsetzung einer Idee aufbringt, bleiben dafür andere Sachen nun mal liegen, welche aber vielleicht eine deutlich höhere Prio hätten (z.Bsp. Bugfixing).
Hätten wir alle Ideen immer sofort umgesetzt, könnte AD wahrscheinlich immer noch nicht rückwärts fahren 😎

Mag sein, das es viele gibt, welche die Idee unterstützen würden, aber vielleicht ist die Anzahl derer, die es nicht brauchen noch viel höher. Wir wissen es nicht und werden es auch nie erfahren, aber so eine Behauptung aufzustellen, finde ich schon etwas dreist (um es vorsichtig zu sagen).

So, und nun kommen alle wieder runter. Hier wird weder beleidigt noch sonst etwas in der Art. Wir werden sehen, ob die Idee in einer akzeptablen Art und Weise und vor allem Zeit umsetzbar ist oder nicht.

PS: jeder darf sich gerne mal die ganzen Feature Request ansehen, welche hier so eingegangen sind:
https://github.com/Stephan-S/FS19_AutoDrive/issues?q=label%3Afeature-request+

**Comment by GulliGriff** [comment]
Ich finde es schon krass zu was sich das hier entwickelt hat. Ich habe lediglich einen Vorschlag gemacht und da habe ich tatsächlich erwartet, dass ein "gute Idee wir denken drüber nach ob wir das umsetzen können" oder "das wird leider zu aufwändig" oder irgend sowas, statt dessen entflammt hier ne Diskussion. Warum?

Ist mir schon oft aufgefallen dass sich Leute angegriffen fühlen, obwohl sie nicht angegriffen werden. Ist hier in den Postings auch so. Einfach mal **nur das Lesen was da steht** wäre gut und nicht irgendwas da rein interpretieren (hab ich auch schon mal geschrieben hier), denn ich sehe nirgends einen angriff und auch keinen der irgendwas behauptet.

Auf jeden Fall würde ich mich freuen, wenn Ihr darüber nachdenkt und noch mehr wenn die Umsetzung in Betracht käme. Wie @Axel32019 schon geschrieben hat,"Bis zum nächsten LS wird wohl noch etwas Zeit vergehen - mal sehen was wir bis dahin noch alles machen können..." ich bin jedenfalls gespannt.

**Comment by GulliGriff** [comment]
Hi, vielleicht wäre das ja ein machbarer Ansatz..
Wäre es möglich die Möglichkeit zu schaffen einen weiteren Filltype anzugeben? So könnte man das ganze auf rotierend be- und entladen stellen, mit den entsprechenden wegpunkten natürlich, und wenn der erste filltype nicht vorhanden ist versucht er den zweiten? 
Könnte mir vorstellen das sowas weniger umfangreich ist und vielleicht sogar machbar. Was denkt ihr darüber?
