### ISSUE TITLE
Automatische Reperatur

### ISSUE THREAD

**Issue by GulliGriff** [Stephan-S/FS19_AutoDrive#1747]
Hallo liebes AD-Team,
das habe ich mir auch schon gewünscht, eine automatische Reperatur. In CP ist es mittlerweile umgesetzt, wäre es möglich das auch in AD zu implementieren? Wir haben auf unserer Karte doch so einige Produktionen bei denen Fahrzeuge schon mal die ganze Nacht auf dem Server unterwegs sind und morgens teilweise bei 100% liegen, da wäre es natürlich super wenn der sich selber bei X Prozent reparieren würde.
LG

**Comment by Iwan1803** [comment]
Was soll AD nicht noch alles machen?
Wenn ihr eine automatische Reparatur braucht, dann gibt es dafür einen Mod:
https://www.farming-simulator.com/mod.php?lang=de&country=de&mod_id=170833&title=fs2019

**Comment by GulliGriff** [comment]
anstatt vernünftig zu antworten mal wieder schnippisch. bin ich von dir mittlerweile gewohnt. der mod repariert ein mal um mitternacht, macht keinen sin für mich!

**Comment by Iwan1803** [comment]
Man könnte den Mod auch ganz erweitern, das er mehrfach am Tag alle Fahrzeuge repariert und wenn man sich schlau macht, dann bestimmt auch eine Abfrage nach dem Status des Fahrzeugs mit reinbringen.
Das AD nun auch noch Fahrzeuge reparieren soll, macht aber für mich dennoch keinen Sinn - außer AD würde wie beim Tanken auch Werkstatt-Trigger erkennen und diese dann anfahren.

**Comment by GulliGriff** [comment]
ich dachte da auch nur daran weil CP es mit rein genommen hat. machbar ist sicher vieles, aber ich bin einfach zu alt um noch lua zu lernen, folglich bin ich darauf angewiesen was eben so an mods gezaubert wird und fragen kostet ja nix.

**Comment by Iwan1803** [comment]
Nur weil CP was macht, müssen wir das noch lange nicht 😉
LUA müsste man nur dann erlernen, wenn man eigene Skripte schreiben möchte, aber das ist für das Autorepair-Skript nicht notwendig, da in gerade mal 2 Zeilen die Uhrzeit abgefragt wird. Frag doch einfach mal auf Discord nach, ob dir da jemand behilflich sein.

**Comment by GulliGriff** [comment]
Versuch macht Klug, vielleicht habe ich ja Glück

**Comment by Bobster82** [comment]
> Wat moet AD anders niet doen?
> Als je een automatische reparatie nodig hebt, is er een mod voor:
> https://www.farming-simulator.com/mod.php?lang=de&country=de&mod_id=170833&title=fs2019

Hey Nice mod ;) I never looked at it how its doing or even thinking about expending it hehe.
