### ISSUE TITLE
[Feature Request] collision detection per vehicle

### ISSUE THREAD

**Issue by Anonymous-any** [Stephan-S/FS19_AutoDrive#1748]
Hi !

**Is your feature request related to a problem? Please describe.**  
I saw depending of how is build the vehicle or size it is, and some maps with height difference where the vehicle wait because for ground detection as example, the collider setting is global.

**Describe the solution you'd like**  
If the collider can be stored for each vehicle that can fix this sort of problem.

**Describe alternatives you've considered**  
Made the collider detector higher but it can hit traffic vehicles after.

Br AD-Team

**Comment by Axel32019** [comment]
Hi Ano,
To have a setting for the collision height will not solve your issue:
The collision detection for each vehicle start at the same height. If it hit the ground and you change it, you may hit other traffic as you stated. So there is no difference if stored for each vehicle:
- vehicle 1: 2m -> hit ground, but stop for traffic
- vehicle 2: 3m -> do not hit ground, but hit traffic

What is the advantage of this?
I hope you understand what I mean :-)

**Comment by Anonymous-any** [comment]
Hello,

Ok, yes I was thinking it can to be each independent could solve it.
In fact I've not must have to change to 3m ! but 2.5m max to by-pass the ground but what is weird that is not for all vehicle. To another location, I put sand for enhance the ground ^^, but I've think only now I could use the ground modification integrated in game. Most of em seem don't need tweak for it (what made me think they are not made all same build...) but true, of course I need more test different vehicles.
True too that is less perfect with traffic when modified but same, seem also depend of vehicles for me and same, need more test.
For this point, again I was thinking the map maker can make mistakes and my 1st think was about some bad mask collider or simply not have, because some traffic vehicle most of em are detected but a few are not.

Thank @Axl
