### ISSUE TITLE
[Feature Request]Wegpunkte manuell erstellen! 

### ISSUE THREAD

**Issue by Rosl777** [Stephan-S/FS19_AutoDrive#1749]
Ich fahre meine Strecken erst immer auf den Geraden ein.
Kreuzungsbereiche wären sehr einfach zu erstellen indem man manuelle Wegpunkte setzt und diese dann verbindet und verschiebt damit eine schöne Kurve rauskommt. Heute muss ich mein Fahrzeug in die Kreuzung stellen und mehrmals Aufnahme an/aus klicken um einen alleinstehenden Wegpunkt zu bekommen.

**Comment by Iwan1803** [comment]
Öhm, man kann Wegpunkte manuell erstellen und auch verbinden und das schon seit sehr vielen Version 😉
https://github.com/Stephan-S/FS19_AutoDrive/wiki/Edit-Mode

**Comment by Iwan1803** [comment]
@Rosl777 reicht das als Anwort oder benötigst du weitere Hilfe?
Ansonsten schau doch einfach mal bei uns auf Discord vorbei: https://discord.gg/9D4B5hX
Da ist eigentlich immer jemand da, der helfen kann 😉

**Comment by Rosl777** [comment]
Vielen Dank. 
Die Antwort hat mir weitergeholfen. 

⁣BlueMail for Android herunterladen ​
