### ISSUE TITLE
Why I can't see initial waypoints config for Felsbrunn and Ravenport in the autodrive hud anymore?

### ISSUE THREAD

**Issue by Maikerus1** [Stephan-S/FS19_AutoDrive#1750]
I have just uploaded Autodrive mod to the last version and I noticed that all initial waypoints like selling points, fields etc. are missing. I can only draw my own route. Is there an option to recover this feature or it is intended removal?

**Comment by Iwan1803** [comment]
We removed the initial routes with 1.1.0.5-RC3 (20.05.2020).
If you want routes for Felsbrunn: https://ls19.crazy-iwan.de

**Comment by TyKonKet** [comment]
Hey @Iwan1803 , why did we removed them?

**Comment by Iwan1803** [comment]
They were outdated and they would have been very time-consuming to update.
