### ISSUE TITLE
[Feature Request] Create smooth connections in in-game editor

### ISSUE THREAD

**Issue by Exceptionfault** [Stephan-S/FS19_AutoDrive#1751]
I really like the in-game editor for creating and manipulating waypoints, because it provides maximum control. Hower especially creating curves and T-Shapes is a pain. Also driving over crossways and and afterwards connecting them is tedious, especially if you want those green lines look somehow nice.

**Describe the solution you'd like**  
I've extended the "connect two waypoints" functionality and applied a smoothing algorithm, which creates nice curves by adding additional waypoints inbetween. When selecting the source point and hovering over the target point it now shows a preview of the connection to be created. With this preview being active, you can adjust the smoothing or roundness with 2 hotkeys. You can also move the source or the target waypoints and the curve will adjust. If you're happy with the result, click the target node and the waypoints will be created.

![autocurves](https://user-images.githubusercontent.com/1003878/104057111-dbb56b00-51f1-11eb-8dca-43eb84ce0c1a.gif)

**Additional context**  
The fork already works as you can see in the pictures but of course has some open topics. For example
- make input keys bindable (KEY_dot and KEY_dash right now...)
- prevent some weird constellations and sharp angles
- does not work right now with two-way connections or reverse driving 
- does not yet work if start waypoint has multiple incoming paths or end waypoint has multiple outgoing path due to tangent calculation of the curve 
- more testing, testing, testing....

It should be easy to create a PR out of this, however I first wanted to see if there is any interest in such functionality. Also it might be a good idea to first move it into an _experimental_ branch or create a feature toggle in the settings first.

** Planned features **
- show the maximum angle of the curve in the preview - even better the maximum speed AD would be able to drive (like some other sim-games do when planning tracks ;-) 

@Devs - code is available here: https://github.com/Exceptionfault/FS19_AutoDrive/tree/feature-curve-creation

**Comment by haamic** [comment]
Super Feature

**Comment by TyKonKet** [comment]
@Exceptionfault that's so great :D
Anyway I agree with you, maybe we should make that feature as "Experimental" so that it can be turned on and off during it's first testing versions.

**Comment by Exceptionfault** [comment]
@haamic - thanks for the positive feedback and testing. With the latest commit, you can now switch the smooth connections and preview on and off as an experimental feature in the AD settings dialog.

**Comment by andreasthu** [comment]
Hello.
Is this also available in the standard AD Version?
Lg
Andreas

**Comment by skjatala** [comment]
@Exceptionfault : Nice and excellent Job mate . I am really enjoying this feature. I also recommended to AutoDrive's Author for adding this feature.

**Comment by Exceptionfault** [comment]
> @andreasthu:  Is this also available in the standard AD Version?

No, it's not (yet). But I want to create a pull request as soon as I got some things fixed and improved like for example configurable keybindings. I also want to support connecting points with multiple inbound/outgoing connections. And last, not least, I definitely need to test two-way and reverse driving.

If you got any suggestions or bugs so far - please report here - and only here....  😄  _Again, this not an official feature and therefore not supported by AD so far._

**Comment by andreasthu** [comment]
Ok, thanks.
I downloadet your version from the link.
This is a cool thing for many situations. 
Works fine at the moment.
Lg
Andreas

**Comment by Anonymous-any** [comment]
Hi there,
just dl the beta for test it :) and I go try to get used to this functionality.
Thank for the work and that is also submit evidence of wp go underground and fix it with mask's that sort from no where ^^. (That I couldn't explain well so I was thinking other ppl can have this issue's.)
Lots of my research for other things about mask's does not give no really table from the manufacturer nowhere...
HACKKERS :p

thanks again programmers

**Comment by Exceptionfault** [comment]
Hey everyone, thanks for the positive feedback. I'm still working on that and just made a tiny new test version available. 

**Changes**
- I've decided to remove the keyboard input for changing the roundness. Instead you can now hold LSHIFT and scroll your mouse wheel to increase or decrease the roundness. Feels much more convenient to me.
- If you reduce the roundness to it's lowest value, the alogithm will fallback to a straight line with no intermediate waypoints.
- Make sure to enable the roundness and preview in the "experimental features" settings of the AD settings dialog.

**Open topics**
- Make a keybind to enable or disable smoothing quickly.

And just to be aware: This version is based on the very latest changes of the `beta-testing` branch from AD - so you will also get other modifications as well...

**Comment by Anonymous-any** [comment]
Hello, tested a bit and this is very cool. (I was dl beta in AD repo ^^).

Because it can't connect to blue line, clear blue, do you think it will came to do it ? also the fix you made for don't have a wp underground is so good too. I had a wp under a building map as parking vehicle, just touch and move it, then it became fine rise to the surface ! so its not just correcting the roads only :) +1: 
Br

**Comment by flattergaul** [comment]
Hi,

just tested this feature. Works nice, i like it.
It makes it much more easier to set up a nice looking and good-to-drive network.

Hope, this feature will find it's way into AD :-)

**Comment by SnoopBok** [comment]
This looks great, I will try it soon. I hope such a feature will be included in the future.

**Comment by TyKonKet** [comment]
@Exceptionfault I think it's not working on MP, to be honest everything about creating routes doesn't work greatly on MP

**Comment by Exceptionfault** [comment]
@TyKonKet doesn't it work at all? Or is it more like "if two players in MP try to create paths in parallel something's broken?"
I really tried to make use of existing functionality to create and connect WPs as those functions already contain the eventing with client<=> server stuff.
However I've seen some situations in existing code (and I copied that logic as well) which does something like that
```lua
self:createWayPoint(p.x, p.y, p.z)
-- HACK: we assume that we created the last WP here, ignoring MP and parallel events... :(
bWP = self:getWayPointById(self:getWayPointsCount())
```
And btw - I've added this comment already... 

If the above sample is the issue in MP, i guess it requires a bit more refactoring to return the actual created waypoint from the server instead of reliying that it just was the last one in the list...

**Comment by TyKonKet** [comment]
No, to be honest I haven't investigated too much, I got a report from a friend who says that both preview and "mouse wheel" works fine but when you "click" to connect the two points, it just connects the two points directly without creating the smoothed curve.

**Comment by Axel32019** [comment]
@Exceptionfault , @TyKonKet What is the current status with this?

**Comment by TyKonKet** [comment]
Don't know, it's a while since I'm not in contact with @Exceptionfault

**Comment by Exceptionfault** [comment]
Sorry for not posting updates - has been a busy time at work.
Current state is unchanged to last postings, meaning that the current version unfortunately does not work in multiplayer. 
I have a very good idea why that is, but I don't have the possibility to test in a MP game myself.

**Comment by Axel32019** [comment]
If you need some tests on a server please let us know. Just put in as much log messages as you need.

**Comment by skjatala** [comment]
@Exceptionfault  ! No further  improvement in new Release 1.1.0.8 ?  Sorry to say . I think you will leave your project in the middle of the  way . Cos " you has been a busy time at work" . lol
