### ISSUE TITLE
[Question/bug]

### ISSUE THREAD

**Issue by envikowaty** [Stephan-S/FS19_AutoDrive#1752]
**AutoDrive Version:** 1.1.0.7 beta
I'm running some test on beta version and I've notice: 
Harvest mode:
Setup, call tractor 🚜 when it's 30% ( basically whatever) load 

= tractor 🚜 starts driving  but starts Unloading the combine only when it's full and stoped.

Shouldn't it working like with CP - tractor and combine drive together up to the moment when harvester is empty.

**Comment by Axel32019** [comment]
Hello @envikowaty ,
It is not the same in CP and AD: AD is only driving to combine if it has opened the pipe, which CP will not initiate during harvest.
CP will only open the pipe if filllevel reached ~95%, as far as I know.

**Comment by envikowaty** [comment]
Would be nice to make a option that harvester opens the pipe so the tractor 🚜 can drive in and take the harvested stuff
