### ISSUE TITLE
Spielstand startet nicht mehr / Savegame does not start 

### ISSUE THREAD

**Issue by tobi694** [Stephan-S/FS19_AutoDrive#1754]
AutoDrive Version: 1.1.0.7
Release or selbsterstelltes zip: Release
Karte (falls relevant): NF Marsch 4fach OG
Fahrzeug(art) (falls relevant):

**Beschreibe den Bug**
Ich kann den Spielstand nicht laden. 
Den Spielstand kann ich ohne Autodrive starten. 

Mein aktuelles vorgehen, damit ich spielen kann. 
1. Ich kopiere mir die beiden Dateien "AutoDriveUserData" und "AutoDrive_config" aus dem Spielstand auf den Desktop.
2. Starte den Spielstand ohne Autodrive
3. Anschließen speichere ich den Spielstand und verlasse den Spielstand. 
4. Nun kopiere ich die beiden Dateien aus "1" wieder in den Spielstand-Order und starte den Spielstand neu. 
5. Jetzt kann ich wieder spielen, jedoch sind alle Autodrive Einstellungen zurückgesetzt. 

Dies muss ich jedes mal machen, damit ich den Spielstand starten kann. 

In der LOG habe ich folgenden Fehler "2021-01-11 09:36 Error: Running LUA method 'loadSharedI3DFileFinished'"
Kann das evtl. mit einem anderen Mod zusammenhängen?
Log habe ich angefügt. 
[log.txt](https://github.com/Stephan-S/FS19_AutoDrive/files/5794647/log.txt)

Bitte um Hilfe, da dieses Vorgehen immer ziemlich umständlich ist. 

Danke. 

**Falls anwendbar - Schritte mit denen ich den Bug nachstellen kann**

**Screenshots**
Falls relevant, bitte Screenshots beifügen

**Comment by Tom20214** [comment]
#1071

**Comment by Tom20214** [comment]
Placeanythere raus da in GC enthalten

**Comment by tobi694** [comment]
Danke aber ich finde die Keybinding xml nicht. In welchem Ordner befindet sich diese? 

Danke

**Comment by Tom20214** [comment]
Documents\My Games\FarmingSimulator2019

**Comment by Tom20214** [comment]
Sorry mein Fehler die heißt inputBinding.xml

**Comment by tobi694** [comment]
Ich habe nun die Datei entfernt, jedoch funktioniert es immer noch nicht. Er meldet in der LOG immer noch den gleichen Fehler. 

Ich werde mal alle Mods raus nehmen und immer wieder weitere mods hinzufügen mal sehen ob das hilft. 

Danke

**Comment by Tom20214** [comment]
Probiere bitte mal diese Version: https://github.com/Stephan-S/FS19_AutoDrive/releases/tag/1.1.0.7

**Comment by tobi694** [comment]
Ich habe nun alle mods entfernt und nacheinander mit einer Standard Map ausprobiert und es funktioniert immer. 
Als nächstes habe ich einen neuen Spielstand mit der NF Marsch gemacht und es funktioniert auch. 

Nur sobald ich meinen aktuellen Spielstand mit über 200h öffnen möchte dann geht es nicht. 

Was könnte ich noch ausprobieren? 

Danke

**Comment by tobi694** [comment]
Guten Morgen, also ich habe die Version (Link oben) aktualisiert und es funktioniert immer noch nicht. 

Danke.

**Comment by tobi694** [comment]
Ich habe nun sogar eine ältere AutoDrive Version 1.1.0.6 ausprobiert und es ist der gleiche Fehler...

**Comment by Tom20214** [comment]
Irgendwelche Mods beißen sich.

**Comment by Tom20214** [comment]
Moin!
FS19_Horsehelper bitte Raus da ebenfalls in GC enthalten 

Und den Mod FS19_Heliodor_Flug aus den Modordner verbannen.

**Comment by haamic** [comment]
Also bei mir hat der mod "animalhud" Probleme gemacht in Verbindung mit dem ingame platzieren eines Kuhstalles. Dadurch hat AD kein Steckennetz bei mir mehr angezeigt. Andere Auswirkungen auf AD und den Start des Spielstandes sind nicht ausgeschlossen. Ich habe die items.XML eines neuen spielstandes Stück für Stück mit den items des alten spielstandes gefüllt und konnte so sehen welches Objekt/Mod da die Ursache ist. Könnte durchaus sein, das ein von dir platziertes Objekt, auch dein Problem verursacht.

**Comment by tobi694** [comment]
Also ich habe nun die anderen beiden Mods ebenfalls entfernt und keine Besserung. 

Zudem habe ich einen neuen Spielstand mit allen Mods gestartet und habe alle Gebäude aufgebaut, welche ich hatte und daraufhin kam der Fehler nicht mehr. 

Naja dann werde ich wohl mit diesem Fehler leben müssen oder einen neuen Spielstand anfangen. 

Danke für eure Anregungen. 
Falls jemand noch eine Idee hat kann er sie mir gerne übermitteln. 

Ich bin für alles offen um meine 220h zu retten.

**Comment by haamic** [comment]
Wenn jetzt alles läuft, dann nimm Datei für Datei aus dem alten savegame und übertrage sie in den neuen Spielstand. Irgendeine Datei davon muss den Spielstart blockieren. 
ich würde mich ja gern mal daran versuchen, weiß aber nicht ob du dein gezipptes savegame (evtl. umbenannt als TXT) hier anhängen darfst.
Oder du speicherst es online und teilst den Link dahin. Gruss Micha

**Comment by tobi694** [comment]
Danke für den Tipp. 
Ich habe es nun so gemacht und habe zwei XML-Dateien herausgefunden, welche das Problem verursachen. 
Zum einen ist es die "AutoDriveUserData" und zum anderen "vehicles"

[Problem.zip](https://github.com/Stephan-S/FS19_AutoDrive/files/5804488/Problem.zip)

Vllt könnt Ihr mir hier weiterhelfen und herausfinden, was an den beiden Dateien nicht stimmt. 

Danke schon mal.

**Comment by haamic** [comment]
und nun in einer leeren vehicle.xml, nach und nach die vehicles des alten savegame einfügen, aber mit den ID´s aufpassen.
es dürfen gleiche ID´s vorhanden sein. ich hatte immer fürs eingefügte die ID 999 genommen, wird beim Start des Spielstandes id-mässig von LS neu geschrieben.
auch hier wirst du irgendwann herausfinden, welches Fahrzeug die Probleme verursacht. 
die AD user data wird nicht das problem sein, die ist genau wie bei mir, eigentlich leer.

**Comment by haamic** [comment]
und nun in einer leeren vehicle.xml, nach und nach die vehicles des alten savegame einfügen, aber mit den ID´s aufpassen.
es dürfen keine gleichen ID´s vorhanden sein. immer nur änderungen in der xml und nicht im LS speichern ,da die id´s unter umständen verändert werden. aber wenn du es der alten reihenfolge nach tust, sollte es passen. Die Vehicle sollten dann beim erfolgeichen Laden auf der Map da stehen wo sie beim Speichern standen.
auch hier wirst du irgendwann herausfinden, welches Fahrzeug die Probleme verursacht.
die AD user data wird nicht das problem sein, die ist genau wie bei mir, eigentlich leer.
Was ich auf die schnelle herausgefunden habe, ich habe deine Vehicle xml genommen und die Mod Fahrzeuge ($moddir$... ) entfernt, so das nur die standardfahrzeuge des LS drin waren. mit der XML startete auch bei mir mein Testspielstand nicht. nach identifizieren der problematischen Fahrzeuge (bisher ID 16+ ID 24+ ID 27) und deren löschung hat das spiel geladen. (standard-Fahrzeuge bis ID 27 in der XML, andere noch nicht getestet)  .
Vielleicht liegts auch an der Map, da ich auf einer anderen teste, als du spielst. werde sie mir morgen laden. 
kann aber jetzt nicht weiter machen, ist doch etwas aufwändiger, was durch die mods noch rein kommt weiss ich nicht, müsste ich mir erst alle laden. morgen könnte ich weiter machen, oder du  machst es selbst.

**Comment by haamic** [comment]
ich hab mich mal dran versucht etwas zu finden. die AutoDriveUserData scheint wohl nicht das Problem zu sein, denn diese ist, wie bei mir, leer. (**Frage ans AD-Team, wozu dient diese eigentlich?)**
Deine Map hab ich mir geladen und deine vehicles.xml in einen neuen Spielstand eingefügt. in der xml habe ich nur die Standard vehicle des LS drin gelassen. Die Map lädt nicht zu ende, startet also nicht. Das Problem ist, das die Traktoren/LKW in der vehicles.xml die Einträge von AD drin haben. in der Art von:

"_**<FS19_AutoDrive>
< AutoDrive mode="2" firstMarker="4" secondMarker="151" fillType="47" loopCounter="0" speedLimit="83" fieldSpeedLimit="83" parkDestination="-1" driverName="TGS 18.500 4x4" followDistance="8" parkInField="2" pipeOffset="52" unloadFillLevel="10" cornerSpeed="11" exitField="1" preCallLevel="7" autoTrailerCover="2" autoRefuel="2" useBeaconLights="1" autoTipSide="2" enableParkAtJobFinished="1" avoidFruit="2" followOnlyOnField="1" callSecondUnloader="1" rotateTargets="1" restrictToField="1" groups="Kuhstall_Groß,0;Verkaufsstellen,0;Fermentierer,0;Schweinefutter,0;Dieselherstellung,0;Felder 01-33,0;BGA_Keilsilo,0;Hof,1;Felder 34-66,0;All,0;BGA,1;Gülle, Gärreste,1;Durchfahrtshalle,0;Kuhstall,0;Hühnerstall,0;Dünger,Saat,Kalk,0;Mischfutterfabrik,0"/>
</FS19_AutoDrive>**_"

Da ich deine AD-Ziele nicht habe, kommt es dazu, das die Map nicht lädt. Ich habe die AD Einträge bei jedem fahrbaren Fahrzeug entfernt und die Map startet. 

Da liegt übrigens noch ein Eierkarton im Norden von Feld 31 rum, aber das nur am Rande... ;-)

Kann es vielleicht sein, das du die **AutoDrive_config.xml** im Savegame nicht drin hast, oder eine falsche/alte ?
sobald ich nämlich bei einem Fahrzeug die <FS19_Autodrive>-Inhalte drin lasse, kommt es bei mir zu dem von dir beschriebenen
**Error: Running LUA method 'loadSharedI3DFileFinished**

häng doch bitte mal die AutoDrive_config.xml als TXT hier an


Gruss Micha

**Comment by tobi694** [comment]
Hallo,
Danke für das ausprobieren. 
Ich werde die Themen auch nochmal ausprobieren. 
Hier ist meine AutoDrive_config. 

[AutoDrive_config.txt](https://github.com/Stephan-S/FS19_AutoDrive/files/5807351/AutoDrive_config.txt)

**Comment by tobi694** [comment]
Ich habe es gerade ausprobiert. 
Wenn ich alle AutoDrive Einträge aus vehicles lösche und das Spiel starte geht es. 
Sobald ich aber aus dem Spiel raus und wieder rein möchte geht es nicht mehr. 

Ich werde jetzt mal nach und nach die Einträge löschen und nachsehen, welches meiner Fahrzeuge das Problem ist. 

Danke.

**Comment by haamic** [comment]
du speicherst im LS den spielstand und dann beim neu laden gehts nicht?

**Comment by haamic** [comment]
Schade, download geht hier wohl grade nicht oder nur sehr langsam, sind ja nur 1800KB, bin bei 40% und es soll noch Stunden dauern

**Comment by tobi694** [comment]
ja richtig. Sobald ich gespeichert habe und neu starten möchte geht nichts mehr.

ich habe nun bei jedem Fahrzeug nacheinander die AutoDrive Einträge herausgelöscht (zwischendurch immer wieder das Spiel gestartet) und ich kann den Spielstand erst laden, wenn alle gelöscht sind. -> somit kann ich kein Fahrzeug herausfinden an welchem es liegt.

**Comment by haamic** [comment]
ich probier es trotzdem auch nochmal, wenn deine autodrive.txt endlich mal fertig geladen ist

**Comment by haamic** [comment]
mit deiner autodrive.xml und der vehicles.xml incl. der AD-Tags, worin nur deine Standard-LS-fahrzeuge sind ,lädt die Karte bei mir.
auch nach speichern, startet die Map.
Ich versuche nun den download deiner Mod-Fahrzeuge und einsetzen in die Vehicles.xml

**Comment by haamic** [comment]
ich geb dir recht, wenn die AD-Tags in der vehicle.xml entfernt sind, startet die Map. nach einem speichern stehen sie wieder drin und die Map startet nicht mehr.
keine Ahnung warum das so ist.  
habe die Vehicles.xml mal in Felsbrunn geladen, mit einer AD-config aus einer ganz anderen map von mir, da geht beides. ich seh in Felsbrunn die Kurse aus meiner anderen Karte und deine Vehicle. Auch nach dem Speichern und Spielstand laden unktioniert das. nehme ich aber deine AD-Config , geht nach dem Speichern des Spielstandes nichts mehr. entweder findet noch jemand vom Team hier eine Lösung, oder du musst leider die Kurse neu einfahren. Tut mir leid.  So kannst du aber wenigstens deinen 200h Spielstand nutzen, "nur" neue Kurse werden benötigt.

**Comment by tobi694** [comment]
Hey danke das du mich hier unterstützt hast. Zumindest wissen wir jetzt etwas mehr. 

Ich hoffe jemand aus dem Team kann nich weitere Anregungen geben. 

Danke nochmals

**Comment by jala15** [comment]
The error might be caused by the comma ( , ) in some of your folder names ("Gülle, Gärreste" and "Dünger,Saat,Kalk")
Please try again whith the commas of those names deleted in AutoDrive_config.xml and vehicles.xml
Here are your files whith the comma deleted for you: [Problem comma deleted.zip](https://github.com/Stephan-S/FS19_AutoDrive/files/5809833/Problem.comma.deleted.zip)

Sorry for English in a German issue but I don´t speak German

**Comment by tobi694** [comment]
Hey @jala15 and @haamic  many thanks for your comment. I add the three files to my savegame and the game will start again.

Many, many thanks for your support
