### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Gibbanator** [Stephan-S/FS19_AutoDrive#1757]
**AutoDrive Version:** 1.1.0.7
**Release or Custom Zip:** Release  
**Map (If applicable):** All  
**Vehicle / Type (If applicable):Man 18.500 4x4 Semi with Krampe SBII 30/170 Trailer  
**Multiplayer or Singleplayer:** Singleplayer  

**Describe the bug**  
I uploaded a video to youtube: https://youtu.be/x68Q_vQKmgk
Using AutoDrive collecting Chaff from corn and dumping it in bunker. The trailer is right next to Harvester but unable to plot a path. It does not do this every row but seems to do it every 2nd or 3rd row so have to baby sit the field to complete harvesting it. 
Using CP with race track course on field with harvester. 
**If applicable - Steps to reproduce the behavior**  

**Screenshots**

**Comment by Iwan1803** [comment]
Restrict unloader to field = yes, but the harvester is not on it.
Avoid fruit maybe could also cause problems like shown in the video.

**Comment by Gibbanator** [comment]
I have done both of those settings and it still did not work. (I can take more video if you like with those settings) I restart autodrive each time I make changes on settings.

It is working corn into shaft so the harvester has no hold. It has to dispense right away so each turn it will be off field to start each row.

**Comment by Axel32019** [comment]
Hello @Gibbanator Are you still using version 1107 or just upgraded to 1108? In 1108 the pathfinding on field was reworked.
