### ISSUE TITLE
Verbesserung Vorschlag für den Drescher abfahrer

### ISSUE THREAD

**Issue by Daniel78-art** [Stephan-S/FS19_AutoDrive#1759]
Hallo wäre es möglich den Drescher abfahrer noch ein bisschen zu verbessen so das er mit einem Drehschemelanhänger auch gerade zurückfahren kann oder einfach ein Stück vorwärts fahrt wenn platz ist.

Gruß 

![fsScreen_2021_01_12_10_41_19](https://user-images.githubusercontent.com/72348662/104299120-1a367880-54c5-11eb-9370-29be5e6e9e8f.png)

**Comment by Iwan1803** [comment]
Das wird wohl nicht möglich sein, da man für Drehschemel dann eigene Routine fürs Rückswärtsfahren schreiben müsste. Sie verhalten sich nun mal komplett anders als normale Anhänger.

**Comment by Daniel78-art** [comment]
Achso okay und danke für die Info.

**Comment by rohne83** [comment]
Ich denke aber es wäre schon recht hilfreich, wenn die Rückwärtsfahrt im Feld mit etwas weniger Tempo (auf keinen Fall mehr als 10km/h) und möglichst schnurgerade, und vielleicht einfach nicht ganz so weit wie bisher, stattfindet. Müsste dann nicht mehr als eigene Routine gemacht werden, sondern kann auch generell gelten. Dann sollte in den meisten Fällen der Anhänger am Ende auch mit Drehschemel noch relativ gerade ausgerichtet sein.

**Comment by Axel32019** [comment]
Geschwindigkeit und Abstand wurden in neueren Versionen angepasst -> closed
