### ISSUE TITLE
Sprache

### ISSUE THREAD

**Issue by Bandesss** [Stephan-S/FS19_AutoDrive#176]
Hallo im Singel Player sind die Meldungen von ankommenden Fahrzeugen auf Deutsch.
Wenn ich mein Kurs hochlade zum Mulitplayer sind die Texte Englisch ?
Was kann das sein ?
Habe die BGA kann am schluss eingefahren wie kann ich die Code nach oben bekommen?
https://pastebin.com/jQGAUn46

  <mm76>
        <id>5967</id>
        <name>Bga Silo</name>
      </mm76>
Den code meine ich

**Comment by Bandesss** [comment]
Hallo wie kenn ich die Bga im Code nach oben versetzen
`        <mapmarker>
      <mm1>
        <id>5</id>
        <name>Hof Huehner</name>
      </mm1>
      <mm2>
        <id>38</id>
        <name>Hof Abfahrt grosse Maschienen</name>
      </mm2>
      <mm3>
        <id>321</id>
        <name>Viehandel Verkauf</name>
      </mm3>
      <mm4>
        <id>327</id>
        <name>Viehhandel Silo</name>
      </mm4>
      <mm5>
        <id>813</id>
        <name>Kuhweide B</name>
      </mm5>
      <mm6>
        <id>1295</id>
        <name>Hof</name>
      </mm6>
      <mm7>
        <id>1473</id>
        <name>Feld 14 Unten Abfahrer</name>
      </mm7>
      <mm8>
        <id>1591</id>
        <name>Abdeckerei</name>
      </mm8>
      <mm9>
        <id>1889</id>
        <name>Hof Silo</name>
      </mm9>
      <mm10>
        <id>2163</id>
        <name>Schreinerei</name>
      </mm10>
      <mm11>
        <id>2262</id>
        <name>Kornmuehle Einkauf</name>
      </mm11>
      <mm12>
        <id>2287</id>
        <name>Kornmuehle Verkauf</name>
      </mm12>
      <mm13>
        <id>2301</id>
        <name>Kornmuehle Einkauf 1</name>
      </mm13>
      <mm14>
        <id>2382</id>
        <name>Molkerei Verkauf</name>
      </mm14>
      <mm15>
        <id>3372</id>
        <name>Pferdehof</name>
      </mm15>
      <mm16>
        <id>3516</id>
        <name>Pferdekoppel A</name>
      </mm16>
      <mm17>
        <id>3777</id>
        <name>Gasthaus Verkauf</name>
      </mm17>
      <mm18>
        <id>3820</id>
        <name>Raifeisen Guelle</name>
      </mm18>
      <mm19>
        <id>3825</id>
        <name>Raifeisen Fluessigduenger Einkauf</name>
      </mm19>
      <mm20>
        <id>3833</id>
        <name>Raifeisen Silos Einkauf</name>
      </mm20>
      <mm21>
        <id>3849</id>
        <name>Raifeisen Verkauf</name>
      </mm21>
      <mm22>
        <id>3909</id>
        <name>Raifeisen Einkauf</name>
      </mm22>
      <mm23>
        <id>3953</id>
        <name>Haendler</name>
      </mm23>
      <mm24>
        <id>4007</id>
        <name>Weberei</name>
      </mm24>
      <mm25>
        <id>4047</id>
        <name>Tankstelle Dorf</name>
      </mm25>
      <mm26>
        <id>4547</id>
        <name>Kuhweide A</name>
      </mm26>
      <mm27>
        <id>4589</id>
        <name>Schafweide und Ziegen</name>
      </mm27>
      <mm28>
        <id>4888</id>
        <name>Feld 1 Unten Abfahrer</name>
      </mm28>
      <mm29>
        <id>4900</id>
        <name>Feld 1 Rechts Abfahrer</name>
      </mm29>
      <mm30>
        <id>4912</id>
        <name>Feld 2 Links Abfahrer</name>
      </mm30>
      <mm31>
        <id>4922</id>
        <name>Feld 2 Unten Abfahrer</name>
      </mm31>
      <mm32>
        <id>4930</id>
        <name>Feld 3 Unten Abfahrer</name>
      </mm32>
      <mm33>
        <id>4942</id>
        <name>Feld 3 Rechts Abfahrer</name>
      </mm33>
      <mm34>
        <id>4960</id>
        <name>Feld 2 Oben Abfahrer</name>
      </mm34>
      <mm35>
        <id>4972</id>
        <name>Feld 2 Rechts Abfahrer</name>
      </mm35>
      <mm36>
        <id>4980</id>
        <name>Feld 3 Links Abfahrer</name>
      </mm36>
      <mm37>
        <id>4993</id>
        <name>Feld 4 Unten Abfahrer</name>
      </mm37>
      <mm38>
        <id>5008</id>
        <name>Feld 4 Links Abfahrer</name>
      </mm38>
      <mm39>
        <id>5025</id>
        <name>Feld 4 Oben Abfahrer</name>
      </mm39>
      <mm40>
        <id>5037</id>
        <name>Feld 4 Rechts Abfahrer</name>
      </mm40>
      <mm41>
        <id>5054</id>
        <name>Feld 5 Unten Abfahrer</name>
      </mm41>
      <mm42>
        <id>5063</id>
        <name>Feld 5 Rechts Abfahrer</name>
      </mm42>
      <mm43>
        <id>5075</id>
        <name>Feld 5 Oben Abfahrer</name>
      </mm43>
      <mm44>
        <id>5087</id>
        <name>Feld 5 Links Abfahrer</name>
      </mm44>
      <mm45>
        <id>5200</id>
        <name>Feld 6 Oben Abfahrer</name>
      </mm45>
      <mm46>
        <id>5240</id>
        <name>Feld 6 Rechts Abfahrer</name>
      </mm46>
      <mm47>
        <id>5270</id>
        <name>Feld 6 Unten Abfahrer</name>
      </mm47>
      <mm48>
        <id>5281</id>
        <name>Feld 6 Links Abfahrer</name>
      </mm48>
      <mm49>
        <id>5292</id>
        <name>Feld 7 Unten Abfahrer</name>
      </mm49>
      <mm50>
        <id>5317</id>
        <name>Feld 7 Links Abfahrer</name>
      </mm50>
      <mm51>
        <id>5344</id>
        <name>Feld 7 Oben Abfahrer</name>
      </mm51>
      <mm52>
        <id>5357</id>
        <name>Feld 7 Rechts Abfahrer</name>
      </mm52>
      <mm53>
        <id>5373</id>
        <name>Feld 8 Oben Abfahrer</name>
      </mm53>
      <mm54>
        <id>5395</id>
        <name>Feld 8 Links Abfahrer</name>
      </mm54>
      <mm55>
        <id>5418</id>
        <name>Feld 8 Unten Abfahrer</name>
      </mm55>
      <mm56>
        <id>5436</id>
        <name>Feld 8 Rechs Abfahrer</name>
      </mm56>
      <mm57>
        <id>5487</id>
        <name>Feld 9 Abfahrer</name>
      </mm57>
      <mm58>
        <id>5624</id>
        <name>Feld 10 Rechts Abfahrer</name>
      </mm58>
      <mm59>
        <id>5775</id>
        <name>Feld 10 Links Abfahrer</name>
      </mm59>
      <mm60>
        <id>5787</id>
        <name>Fels 10 Oben Abfahrer</name>
      </mm60>
      <mm61>
        <id>5801</id>
        <name>Feld 10 Rechts Abfahrer</name>
      </mm61>
      <mm62>
        <id>5812</id>
        <name>Feld 11 Links Abfahrer</name>
      </mm62>
      <mm63>
        <id>5823</id>
        <name>Feld 10 Unten Abfahrer</name>
      </mm63>
      <mm64>
        <id>5834</id>
        <name>Feld 12 Unten Abfahrer</name>
      </mm64>
      <mm65>
        <id>5845</id>
        <name>Feld 12 Links Abfahrer</name>
      </mm65>
      <mm66>
        <id>5854</id>
        <name>Feld 13 Oben Abfahrer</name>
      </mm66>
      <mm67>
        <id>5862</id>
        <name>Feld 13 Links Abfahrer</name>
      </mm67>
      <mm68>
        <id>5870</id>
        <name>Feld 13 Unten Abfahrer</name>
      </mm68>
      <mm69>
        <id>5879</id>
        <name>Feld 13 Rechts Abfahrer</name>
      </mm69>
      <mm70>
        <id>5892</id>
        <name>Feld 14 Links Abfahrer</name>
      </mm70>
       <mm71>
        <id>1473</id>
        <name>Feld 14 Unten Abfahrer</name>
      </mm71>
	  <mm72>
        <id>5903</id>
        <name>Feld 15 Links Abfahrer</name>
      </mm72>
	  <mm73>
        <id>5912</id>
        <name>Feld 15 Oben Abfahrer</name>
      </mm73>
      <mm74>
        <id>5924</id>
        <name>Feld 15 Rechts Abfahrer</name>
      </mm74>
      <mm75>
        <id>5932</id>
        <name>Feld 15 Unten Abfahrer</name>
      </mm75>
      <mm76>
        <id>5967</id>
        <name>Bga Silo</name>
      </mm76>
    </mapmarker>
    </HOF_BERGMANN>
</AutoDrive>`

**Comment by Stephan-S** [comment]
Du kannst den Server auf Deutsch stellen, dann sind auch die Nachrichten auf Deutsch.
Die werden auf dem Server erzeugt und dementsprechend wir die Sprache genutzt die dort eingestellt wird.

**Comment by Bandesss** [comment]
Ich wollte alles nach der reihe einfahren im SP gehts aber nicht im Mp 
https://abload.de/img/20190531195701_1o0kki.jpg
Siehe Bild Sp 
Im Mulitplayer sieht es so aus 
https://abload.de/img/20190531204735_1emj01.jpg

Was kann das sein ?
