### ISSUE TITLE
[Question]

### ISSUE THREAD

**Issue by RedMonster-HUN** [Stephan-S/FS19_AutoDrive#1760]
**Question:**   
I've got a question...

Hi, can you pls tell me how can I alter the keybinding for this function:
- connecting two points in forward drive
The default keys are left shift for backward and right shift for forward drive.

I looked in game settings but didnt find anything. I'd like to change those.

**Comment by Axel32019** [comment]
Hello @RedMonster-HUN , This is not possible to change.
For actual mouse- / key- actions have a look here: https://github.com/Stephan-S/FS19_AutoDrive/wiki/Edit-Mode
