### ISSUE TITLE
[Feature Request]die Hauptstraße.

### ISSUE THREAD

**Issue by xZLOx** [Stephan-S/FS19_AutoDrive#1761]
**Is your feature request related to a problem? Please describe.**  

**Describe the solution you'd like**  

**Describe alternatives you've considered**  

**Additional context**

**Comment by xZLOx** [comment]
Добрый день.Сейчас когда прокладываешь маршруты по картам получается курс прокладывается в обьезд точек и как можно быстрей чтоб добралась техника до конечной точки маршрута.Но до пустим мне надо чтобы техника ехала не через поля  по грунтовке а по шоссе.Это имеет смысл когда техника ездит в режими доставки допустим на хранилище или на производства.  Сейчас я получаю такой результат ставля точки на путях по дороге которая идет через поля.И техника едет по шоссе не съезжая на грунтовку.Так вот что меня интересует не льзя ли сделать так чтоб у некоторых путей приоритет на проезд был бы выше чем у других.И цвет был бы свой.Спасибо за понимание.
![fsScreen_2021_01_13_03_41_56_LI](https://user-images.githubusercontent.com/77365919/104392683-aa230380-5553-11eb-98d7-d4501014e210.jpg)

**Comment by Iwan1803** [comment]
German or english please as we can't speak Russian.

**Comment by xZLOx** [comment]
Guten Tag. Wenn Sie nun Routen auf die Karten legen, stellt sich heraus, dass der Kurs durch Umgehen der Punkte und so schnell wie möglich festgelegt wird, damit die Ausrüstung den Endpunkt der Route erreichen kann. Angenommen, die Ausrüstung muss nicht auf einer unbefestigten Straße, sondern auf einer Autobahn durch Felder fahren. Dies ist sinnvoll, wenn die Ausrüstung fährt Nehmen wir im Liefermodus beispielsweise die Lagerung oder Produktion an. Jetzt erhalte ich ein solches Ergebnis, indem ich Punkte auf die Wege entlang der Straße setze, die durch die Felder führt. Und die Ausrüstung fährt die Autobahn entlang, ohne den Feldweg hinunterzufahren. Ich frage mich also, ob ich es so machen soll, dass einige Straßen eine höhere Priorität für das Reisen haben als andere. Und die Farbe wäre meine eigene. Vielen Dank für Ihr Verständnis.
 Good afternoon. Now, when you lay routes on the maps, it turns out that the course is laid by bypassing the points and as quickly as possible so that the equipment can reach the final point of the route. But let’s say, I need the equipment to drive not through fields on a dirt road, but along a highway. This makes sense when the equipment drives in delivery modes, let's say for storage or production. Now I get such a result by putting points on the paths along the road that goes through the fields. And the equipment drives along the highway without going down the dirt road. So what I'm wondering is whether to make it so that some roads have a higher priority for travel than others. And the color would be my own. Thanks for your understanding.

**Comment by GitTomahawk** [comment]
There is currently no option to raise the priority of a road, but there is one you can use to lower its priority.
If you can set the distance AD will accept avoid map markers.
This leads to the fact that if you place target map markers you have on a path it will be used more rarely.
You can fine tune this by placing aditional markers and changing the distance to the best matching value.

**Comment by xZLOx** [comment]
Danke, ich habe alles verstanden.
