### ISSUE TITLE
[Feature Request] pickup at different places before unload

### ISSUE THREAD

**Issue by Dueesberch** [Stephan-S/FS19_AutoDrive#1762]
**Is your feature request related to a problem? Please describe.**  
stopping annoying discussion at discord

**Describe the solution you'd like**  
AD should be able to pick up at different places before unloading at final place.
All pickup place could be put together into one folder. AD is driving to all the place and loading set fruit or else. than driving to unload.

**Comment by Iwan1803** [comment]
Es geht um den Abholen&Abliefern-Modus und ich hänge mal was aus Discord an:

> er möchte aber, das die Ladestationen so lange direkt nacheinander angefahren werden, bis der Anhänger voll ist und AD erst dann zur Abladestelle fährt
> das macht aber auch nur dann Sinn, wenn die Ladestationen nicht quer über die Map verteilt sind, sondern relativ nah bei einander stehen
> wie gesagt macht das in meinem Augen nur Sinn, wenn die Ladestellen recht konzentriert an einer Stelle auf der Map sind und nicht kreuz und quer verteilt
> sonst fährt ja er u.U. schon x Mal an der Abladestelle ohne abzuladen vorbei

Die Option sollte also eher optional aktivierbar sein.
