### ISSUE TITLE
[BUG]Streckennetz lässt sich nicht einfügen 

### ISSUE THREAD

**Issue by streubeheubar** [Stephan-S/FS19_AutoDrive#1764]
AutoDrive Version: 1.1.0.7
Release or selbsterstelltes zip: Release
Karte (falls relevant): Felsbrunn Orginal
Fahrzeug(art) (falls relevant):

**Beschreibe den Bug**
Kann das Streckennetz nicht einfügen .

**Falls anwendbar - Schritte mit denen ich den Bug nachstellen kann**
Habe aktuelle Version geladen 
Alles nach dem Video gemacht https://www.youtube.com/watch?v=NS4VSkbVWbc&t=12s

Neues Savegame ohne Mods nur Autodrive
Kurz ingame ,abgespeichert  und dann 
AutoDrive_Willkommen_auf_Felsbrunn_config in Savegame  eingefügt.

Wieder ingame und abgespeichert.

Keine Streckenetz ingame 
AutoDrive_Willkommen_auf_Felsbrunn_config ist nicht mehr in Savegame
AutoDrive_config ist unverändert --2kb

Link zum Streckennetz
https://www.modhoster.de/mods/autodrive-kurse-fur-felsbrunn-by-mc#images

Log ist sauber 

Für Hilfe wäre ich sehr dankbar

**Screenshots**
Falls relevant, bitte Screenshots beifügen

**Comment by Iwan1803** [comment]
Die AD-Datei hat einen falschen Namen. Für die Originalmap muss sie AutoDrive_Felsbrunn_config heißen.

**Comment by streubeheubar** [comment]
Hallo 

Danke für die Hilfe...... werde einen Kaffee  überweisen  :)))

Hätte noch eine Frage:  wie kann blaue Strecken machen,  solche wie ich sie auf fertigen Strecken immer wieder sehe fie zu Felder führen. 



Mfg streubeheubar

**Comment by Iwan1803** [comment]
Linksklick auf Record-Button:
- vorwärtsfahren = grüne Linie aufzeichnen
- rückwärtsfahren = hellblaue Linie aufzeichnen
Rechtsklick auf Record-Button:
- vorwärtsfahren = blaue Linie aufzeichnen

**Comment by streubeheubar** [comment]
Hallo 

Danke für die Hilfe. 

Rab mal 3 Cafe auf github rüber lassen,  weiß nicht ob du was davon hast. 

Bin im übrigen der streubeheubar der seit ls 11 mods umbaut ( sollte dir der Name nicht's sagen,  frag mal Google  )

Die Kurse von mh taugen nix und mit dem Controller ist das nur unschön. 


Daher die Frage: du hast nicht zufällig kurse von der Felsbrunn oder kennst wen wo welche hat  ?


Mfg der streubeheubar

**Comment by Iwan1803** [comment]
Der Kaffee geht komplett an Stephan, mein Spendenlink ist ein Stück tiefer.

Falls es um die Standard-Felsbrunn geht, hatte ich mal angefangen, das AD-Netz zu "optimieren". Es fehlen zwar noch ein paar Feldanbindungen, aber der Rest funktioniert soweit: https://ls19.crazy-iwan.de/

**Comment by streubeheubar** [comment]
Hallo

Habe deinen kurs geladen...... der ist top.

Da ich an der map kein Gebäude verändert habe , geht eine route durch ein Gebäude am  Hof. 

Hab die route verschoben..... aber nach speichern und wieder ins Spiel gehen...... ist sie wieder im Gebäude. 

Muss ich irgendwie abspeichern oder hast du da einen schreibschutz drauf ?


Mfg streubeheubar 


.

**Comment by Iwan1803** [comment]
Da ist kein Schreibschutz drauf, wie auch?
Da die Config ja noch im alten Format vorliegt:
https://github.com/Stephan-S/FS19_AutoDrive/issues/1684

**Comment by streubeheubar** [comment]
Hallo 


Wie kann ich Routen ändern und speichern?

Deine Routen sind Top  , aber es nervt das sie bei jedem Neustart wieder aus dem gebäude gezogen werden müssen 


Mfg

Streubeheubar 


.

**Comment by streubeheubar** [comment]
Hallo

 

deine Kurse sind echt top............... nur 

 

 

ich bekomm Änderungen einfach nicht gespeichert

 

Bei Neustart  sind neue Routen weg .....geänderte sind wie sie beim ersten mal waren .

 

 

Kannst du mir mal bitte helfen ?

 

 

 

 

mfg

 

Martin

 

Gesendet: Donnerstag, 21. Januar 2021 um 12:11 Uhr
Von: "Iwan1803" <notifications@github.com>
An: "Stephan-S/FS19_AutoDrive" <FS19_AutoDrive@noreply.github.com>
Cc: "streubeheubar" <streubeheubar@web.de>, "Author" <author@noreply.github.com>
Betreff: Re: [Stephan-S/FS19_AutoDrive] [BUG]Streckennetz lässt sich nicht einfügen (#1764)


 

Da ist kein Schreibschutz drauf, wie auch?
Da die Config ja noch im alten Format vorliegt:
#1684

**Comment by Iwan1803** [comment]
Ich hab meine Config jetzt mal aktualisiert auf 1.1.0.7 und neu hochgeladen.
Editieren kann ich sie problemlos.
Bitte prüf mal nach dem Entpacken, ob sie einen Schreibschutz hat.
Editier danach die Linien mal in einem leeren Savegame und auf mittlerer Schwierigskeitsstufe, damit keine Gebäude im Weg sind.

**Comment by Iwan1803** [comment]
Da kein weiteres Feedback -> geschlossen!
