### ISSUE TITLE
[Question] Geschwindigkeit vor Radarfallen verringern ? / Reduce speed before speed traps ?

### ISSUE THREAD

**Issue by MacMoore** [Stephan-S/FS19_AutoDrive#1767]
**Question:**   
I've got a question...
Hallo, 
ist es möglich in Autodrive die Geschwindigkeit vor Radarfallen zu verringern ?
Ich habe ein YT-Video von Holger-70 gesehen, wo er vor der Radarfalle mehrer Wegpunkte einfügte worauf an dieser Stelle Autodrive die Geschwindigkeit automatisch verringerte.
Das Video ist aus dem März 2020, mit der Version1.0.7.1 - zu sehen ab ca. 2:40
https://youtu.be/oAwVa1ziD8Y?list=PLKiJKe32B_edmW4ZBC8Vn0RTmApSWXd_X

Ich habe die neueste Version 1.1.0.7, habe das auf der Map "Grünfelder Land" versucht mit den zusätzlichen Wegpunkten einfügen, das Fahrzeug wird aber nicht langsamer.
Klappt das mit der neueren Version nicht mehr oder hab ich was falsch gemacht, bzw. gibt es eine andere Möglichkeit Autodrive abzubremsen ?
Danke für Info !

Lg....

**Comment by Axel32019** [comment]
Hallo @MacMoore , Die Punkte im Zickzack anordnen, nicht gerade, dann verringert AD die Geschwindigkeit.
Einfach probieren...

**Comment by MacMoore** [comment]
Hi @Axel32019 ,
danke für den Tip, klappt eigentlich recht gut.
Wenn man zwei Wegpunkte eng zusammenfügt und auch nicht zu viel seitlich zueinander versetzt schaut das recht gut aus beim fahren.
Mit ein wenig Spielerei kann man auch die Geschwindigkeit ziemlich gut einstellen, bin jetzt bei ca. 30 - 35 km/h bei den 50ziger Radarkästen.
Lg...
