### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Posmatrac** [Stephan-S/FS19_AutoDrive#1768]
AutoDrive Version: 1.1.0.7
Release or selbsterstelltes zip: Release
Karte (falls relevant): Nordfriesische Marsch 4fach ohne Gräben v2.5
Fahrzeug(art) (falls relevant):

**Beschreibe den Bug**
Eine Klare beschreibung habe ich im endeffekt nicht. Das Savegame startet einfach nicht. Im Log steht einfach nur:

Error: Running LUA method 'loadSharedI3DFileFinished'.
C:/Users/b0snaX/Documents/My Games/FarmingSimulator2019/mods/FS19_AutoDrive/scripts/Specialization.lua:157: attempt to compare number with nil

**Falls anwendbar - Schritte mit denen ich den Bug nachstellen kann**
Ich weis nicht wie man es nachstellen könnte. Ich habe nur eine Nacht im spiel überschlafen und danach ausgemacht und dann startet es einfach nicht mehr.

**Screenshots**
Kein Screenshot. Das Spiel lädt und es lädt sich zu tode. Hier aber mal die komplette Log.

[log.txt](https://github.com/Stephan-S/FS19_AutoDrive/files/5823691/log.txt)

Wie kann man diesen Fehler beheben?

**Comment by haamic** [comment]
Hast du evtl. Satzzeichen in deinen Ziel- oder Ordnernamen? Erst kürzlich hatte @jala15 im Issue #1754 die Lösung.
Hier die Übersetzung:

@jala15 kommentierte vor 3 Tagen
Der Fehler könnte durch das Komma ( , ) in einigen Ihrer Ordnernamen ("Gülle, Gärreste" und "Dünger,Saat,Kalk") verursacht werden
Bitte versuchen Sie es noch einmal, indem Sie die Kommas in diesen Namen in AutoDrive_config.xml und vehicles.xml löschen

Funktionierte AD bereits mit deiner Map und erst nach dem Speichern lädt die Karte nicht zu Ende, wie in dem Issue #1754?

**Comment by Posmatrac** [comment]
Hallo @haamic 

Gestern habe ich noch den Beitrag gelesen nur eben nicht zu ende.

Tatsächlich verwende ich kommas. Ich habe einige selbsteingefahrene ziele in ordner umsortiert. Vorher hatte ich alle Produktionen auf der Marsch Map in einem Ordner Produktionen. Und autodrive hat wunderbar funktioniert. Aber nun hat jede Produktion einen eigenen ordner, da mir alles in einem so unübersichtlich wurde.

Hier wird wahrscheinlich der fehler sein

Zementfabrik, Kiesgrube und Erdhaufen sind in einem ordner, da si thematisch zu einander passen, habe ich beschlossen diese 3 Produktionen in einem ordner zu belassen, Und den habe ich so genannt:

"P - Zem., Kies, Erde"

Ich war der annahme, das Autodrive gegen Satzzeichen nix hat, da ich ja bindestirich schon immer verwendet habe auch als die Ziele alle in einem ordner waren habe ich das "P - " verwendet. Also in etwa so:

"P - Diesel - beladen"
"P - Diesel - ausladen"
usw. usf.

Autodrive hat sich da auch ein wenig komisch verhalten zurerst ging es wie in dem von dir getaggten Beitrag nach dem Speicher nicht. Als ich dann auf version 1.1.0.6 Release gedowngraded habe, konnte ich so oft speichern wie ich wollte und neu laden es ging ohne probleme. Nur wenn ich in game eine Nacht geschlafen habe, dann speichern und beende, dann konnte ich nicht mehr rein.

Ich werde es mal nachher ausprobieren ob ich es mit Umbennen auch hinkrige und sag dann bescheid ob es geklappt hat.

**Comment by haamic** [comment]
okay, probiers mal aus. aber auch in beiden dateien umbenennen, wie beschrieben, da evtl. gerade ein Fahrzeug in der vehicles.xml einen Kurs zu einem Ziel mit Komma hat.

**Comment by Posmatrac** [comment]
Hallo.

ich hätte niemals gedacht, das tatsächlich Punkt und Komma ein Problem darstellen können. Also beim erstmal hatte ich in verdacht, das dieser Handmäher aus dem Alpin DLC eventuell problem verursacht, aber nachdem ich Profil Backup geladen habe, hatte ich ihn nicht mehr und es ging trozdem nicht, dann hatte ich Bäume im verdacht. Ich habe ein paar Bäume neben dem Stall der Tiere Platziert damit es schöner aussieht und die Tiere ein Schaten haben, das kommt aus dem MW Placeble Hof Pack, aber was könnte AD schon mit Bäumen zu tun haben, dachte ich mir, sind ja keine Geräte im eigentlichen Sinne,

Aber das Punkt und Komma das problem sind, habe in keiner Sekunde in erwägung gezogen. Zumal man ja Bindestriche und ÄÖÜ usw. problemlos verwenden kann...

Nun, nachdem ich nun die AutoDrive_Config.xml und vehicles.xml bereinigt habe. Läuft es nun. Dir @haamic danke für deine nette unterstützung. Und an alle entschuldigt für meinen Bug report. Ein Bug im eigentlichen Sinne war es ja nicht, sondern eher mein fehler. Entschuldigt dafür!

Was mich angeht, kann das Team nun den Report schliessen, mein fehler habe ich behoben.

**Comment by haamic** [comment]
Freut mich das es nun läuft. 
Du kannst auch selber schliessen, oder jemand vom Team macht das später.
