### ISSUE TITLE
[BUG] Ziele und Wegpunkte werden nicht gespeichert

### ISSUE THREAD

**Issue by Stew4u** [Stephan-S/FS19_AutoDrive#1769]
[log.txt](https://github.com/Stephan-S/FS19_AutoDrive/files/5824301/log.txt)
[gamelog.txt](https://github.com/Stephan-S/FS19_AutoDrive/files/5824296/gamelog.txt)
AutoDrive Version: 1.1.0.7
Release or selbsterstelltes zip: Release
Karte (falls relevant): HoF 2021
Fahrzeug(art) (falls relevant):

**Beschreibe den Bug**
Ich arbeite mit einem bereits bestehenden Netz für die Karte. Die Wegpunkte und Ziele aus diesem werden geladen, allerdings wenn ich neue Wegpunkte oder Ziele setzen will, sind diese beim nächsten Laden verschwunden. 
Ich spiele auf einem Dedi-Server. Spiel wurde immer vor dem Verlassen gespeichert

**Falls anwendbar - Schritte mit denen ich den Bug nachstellen kann**
nicht nachvollziehbar.

**Comment by Iwan1803** [comment]
Logifle vom Client und vom Server könnten hilfreich sein.

**Comment by Stew4u** [comment]
Sorry, Dateien sind angehängt an den Eröffnungsbeitrag. 

Auf anderen Kartn habe ich übrigens genau dasselbe Problem.

**Comment by Axel32019** [comment]
Hallo @Stew4u ,

`2021-01-16 07:44 Joined network game (777)`
`2021-01-16 07:44   Error: [AutoDriveSync] Error receiving marker Stew Inc. Hof (23387)`

Das sieht nach einem Synchronisationsfehler aus. Ich nehme mal an das kommt von einem mod den ihr neu hinzugefügt habt.
Bitte mal einen Spielstand ohne mods im mod-Ordner, deaktivieren reicht nicht, nur mit Karte und AD ausprobieren.

**Comment by rohne83** [comment]
Mir ist gestern abend noch etwas anderes aufgefallen, das hier vielleicht auch die Ursache sein kann:
wenn man sein Routennetz bereits mit AD 1.1.0.6 oder niedriger eingefahren hat, und danach mit 1.1.0.7 bearbeitet, dann sind beim nächsten Laden die Änderungen ebenfalls nicht mehr vorhanden. Zumindest wenn man die AD-Funktion zum Speichern und Laden des Streckennetzes nutzt.
Grund sind wohl die Änderungen am xml-Format der AutoDrive_config.xml im savegame. Abgesehen davon, dass die xmls jetzt nicht mehr den Namen der Map im Dateinamen beinhalten, waren die waypoints bei den alten Versionen ja innerhalb eines Tags der ebenfalls den Mapnamen trug. Nach manuellem Bearbeiten der xml auf das neue Format, geht alles wieder.

**Comment by Axel32019** [comment]
@Stew4u Hallo, gibt es hierzu noch etwas Neues?

**Comment by Stew4u** [comment]
Hallo. Leider nicht. 
Ich habe es noch mal mit 1.1.0.6. versucht. Leider hat er die Wegpunkte da auch nicht übernommen. 
Ich habe mir das Wegenetz direkt von der HoT-Seite herunter geladen. Werde aber heute noch mal mit der 1.1.0.7 und einem neuen Routennetz testen.

**Comment by Axel32019** [comment]
Keine neuen Infos -> closed
