### ISSUE TITLE
Error: Running LUA method update

### ISSUE THREAD

**Issue by Knowen** [Stephan-S/FS19_AutoDrive#177]
Hey,

ich hatte das gestern und heute schon ein paar mal das mein Spiel "eingefroren" ist. Auf ESC und rechte Maustaste wird noch reagiert, aber alles andere steht still.

Folgendes steht in der log.txt:
`2019-05-31 12:33 D:/LS19 Mods/FS19_AutoDrive/scripts/AutoDriveGraphHandling.lua:366: attempt to index a nil value
2019-05-31 12:33 Error: Running LUA method 'update'.`
[log.txt](https://github.com/Stephan-S/FS19_AutoDrive/files/3240920/log.txt)

EDIT: Jetzt kam ein anderer Fehler hinzu (kein Änderung an Mods oder ähnlichem seit erster Meldung) 
`2019-05-31 13:26 D:/LS19 Mods/FS19_AutoDrive/scripts/AutoDriveDriveFuncs.lua:288: attempt to index a nil value
2019-05-31 13:26 Error: Running LUA method 'update'.`

Das hält zwischen einer und fünf minuten an. Danach läuft alles wieder ohne Probleme.

Hoffe das ist kein allzu großer Aufwand :)

Grüße,
Knowen

**Auf Englisch für mitleser:**
Hey,

I had this yesterday and today already a few times that my game is "frozen". On ESC and right mouse button is still reacted, but everything else stands still.

The following can be found in the log.txt:
`2019-05-31 12:33 D:/LS19 Mods/FS19_AutoDrive/scripts/AutoDriveGraphHandling.lua:366: attempt to index a nil value
2019-05-31 12:33 Error: Running LUA method 'update'.`
It lasts between one and five minutes. After that everything runs again without problems.

**Comment by Stephan-S** [comment]
Hey,

ist das beim Drescher abladen passiert?
Wenn ja, welche Strategie für das Feld verlassen hast du eingestellt?

Ich kann den Fehler zwar abfangen, aber mir ist noch nicht ganz klar wie er entstehen kann.

Hast du zu der Zeit auch gerade den Kurs bearbeitet/neu berechnen lassen?

**Comment by Knowen** [comment]
Beim ersten Freez kann es durchaus sein das ein Drescher gerade abgeladen wurde, während ich das Straßennetz an einer anderen stelle bearbeitet und gespeichert habe. 
Beim zweiten mal lief kein Drescher und es passierte beim abtanken von einem Silo. Dabei habe ich den Kurs nicht bearbeitet oder gespeichert.

**Comment by Knowen** [comment]
Nabend, ich glaube du musst das hier nochmal aufmachen.

Habe vor einer Stunde auf die aktuellste Version geupdated und seit dem Laden die Trailer nicht mehr am Silo. Es kommt nicht direkt zu einem Freez. Vielmehr bleibt die Kamera kurz stehen während der Trailer weiter über den Ladepunkt fährt und springt dann wieder in die gewohnte position, nachdem der Ladepunkt überfahren wurde.

Habe das mehrach probiert, mit verschiedenen Trailern und Fruchtsorten, aber es kam immer das gleiche Ergebnis. Es war kein anderer Helfer, CP oder sonstwas aktiv.

In der Log steht folgendes:
`2019-06-02 21:28 D:/LS19 Mods/FS19_AutoDrive/scripts/AutoDriveTrailerUtil.lua:93: bad argument #1 to 'pairs' (table expected, got nil)
2019-06-02 21:28 Error: Running LUA method 'update'.`

Log liegt bei.

Grüße,
Knowen
[log.txt](https://github.com/Stephan-S/FS19_AutoDrive/files/3245131/log.txt)

**Comment by Gyffes** [comment]
Grüße ich schreib das mal hier mit hin.
Ich  habe auch mit der Aktuellen Version 100fach den Error

`2019-06-08 20:41 D:/home/sid_1063501/farmingSim_2019/profile/mods/FS19_AutoDrive/scripts/AutoDriveDriveFuncs.lua:259: attempt to index a nil value 2019-06-08 20:41 Error: Running LUA method 'update'`. 


vielleichts hilf.

PS Super Arbeit

**Comment by Stephan-S** [comment]
Hey,
danke für die Meldung. Der Lua Fehler taucht in der nächsten Version nicht mehr auf. Aber trotzdem steckt da vermutlich ein anderer Fehler irgendwo dahinter.
Ist das nur bei einem bestimmten Zielpunkt aufgetaucht?
Oder hast du das Fahrzeug gestartet und er konnte keinen Weg finden? 
Hier steckt wie gesagt eine andere Ursache dahinter und ich habe erstmal nur das Symptom bekämpft :-)

**Comment by Gyffes** [comment]
Hi Danke für die schnelle Rückmeldung. Kann dir aber leider  nicht sagen was den process ausgelöst hat. habe mir heute morgen nur das log angeschaut und da ist es mir aufgefallen. 
Aktuell spiele n wir zu zweit seit ca 15 min keine Probleme.
Ich halte die augen offen.

**Comment by Stephan-S** [comment]
Ach ihr spielt auf einem Dedi-Server? Alles klar. das kann die Situation erklären. Wenn ein Fahrer an seinem Ziel ankommt, während gerade die Routen neu berechnet/hochgeladen wurden könnte so etwas vorkommen.
Dann reicht der Fix an der Stelle völlig aus.
Danke für die kurze Rückmeldung!

**Comment by Gyffes** [comment]
Ah ok super.  Weis nicht ob es eine rolle Spielt oder damit zusammen hengt.
So ein Routen Neuberechnen dauert aktuell ca 3 Minuten.
Beim Spielstand Speichern macht er dann auch 
2019-06-09 11:55 AD: Set to recalculating routes
in dieser Zeit habe ich dann 3 minuten Standbild.

Map DonDiego Probiert im Singel und MP

**Comment by Stephan-S** [comment]
Das ist aber wirklich sehr lange.
Wie viele Wegpunkte hast du denn?
Also einmal meine ich die Anzahl Wegpunkte und die Anzahl Ziele.
Beim neuberechnen hängt es hauptsächlich von der Anzahl Ziele ab.
Beim Speichern ist beides relevant und kann vor allem dann lange dauern wenn du Zielpunkte hast die nicht von überall erreichbar sind, also quasi ein losgelöstes Streckennetz vom Hauptnetz.

Schick mir auch gerne mal die config.xml.

Ansonsten habt ihr einfach einen sehr sehr schwachen Dedi-Server bekommen ;-)

**Comment by Gyffes** [comment]
Gute Frage, ich weis nicht wo ich die Anzahl der Wegpunkte sehen kann. 
Sende mal die Datei mit.
Das es auf dem Server Schlechter ist hatte ich vermutet. 
Bearbeite deshalb die Wegpunkte bei mir am Rechner (starte eine Kopie vom Savegame als MP)
Dachte das nen i5-8600k mit einer gtx 1080ti 8gb und SSD platte ausreicht :) aber selbst da. Dauert es 2min. Einen Wegpunkt löschen ca 30 sekunden.
Warscheinlich hab ich einfach zu viele wegpunkte. 

Danke dir vielmals für deine mühe.

[AutoDrive_FS19_Dondiego_Map_config.zip](https://github.com/Stephan-S/FS19_AutoDrive/files/3269433/AutoDrive_FS19_Dondiego_Map_config.zip)

**Comment by Stephan-S** [comment]
Hey,

ich habe ein paar Verbesserungen vorgenommen, in Bezug auf das Löschen von Wegpunkten und das Abspeichern.
Das ist nun beides um ein Vielfaches schneller. So ein großes Netzwerk habe ich bisher noch nicht gesehen und daher die starken Probleme noch nicht erkannt, danke für deine Meldung dazu!

Das Neuberechnen ist schon stark optimiert und kann kaum beschleunigt werden.

**Comment by Gyffes** [comment]
Super Danke hoffe. Konnte mit meinen Problemen dir helfen deine Mod besser zu machen.

Ich find Sie jedenfalls super. Selbst für Beta Status.
