### ISSUE TITLE
Linien sind nicht zu sehen[BUG]

### ISSUE THREAD

**Issue by Stoecki1979** [Stephan-S/FS19_AutoDrive#1770]
AutoDrive Version: 1.1.0.7
Release or selbsterstelltes zip: Release
Karte (falls relevant): Alle
Fahrzeug(art) (falls relevant):

**Beschreibe den Bug**
Bei mir sind im Editor Modus nur die Wegpunkte zu sehen und keine Linien auch der Abfahrer tut manchmal so als wenn er keine Linien findet

**Falls anwendbar - Schritte mit denen ich den Bug nachstellen kann**

**Screenshots**
Falls relevant, bitte Screenshots beifügen

**Comment by Stoecki1979** [comment]
Ist immer erst wenn ich ein neues Spiel anfange und Autodrive Kurse importiere sind die da erst wenn ich das Game Speicher und beende und ein anderes mal Weiterspiele sind die Linien zwischen den Zielpunkten verschwunden

**Comment by Iwan1803** [comment]
Welche Map? Woher sind die Kurse? Log?

**Comment by Stoecki1979** [comment]
Map sind Kernstadt und Nordfriesische Marsch 4fach ohne Gräben .
Die Kurse hab ich vom LS-Mapping Team für die Kernstadt und für die Marsch von Modhoster vom Holger70
Log hab ich keine mehr hab die AD Version auf 1.1.0.5 downgegraded bis jetzt läufts so

**Comment by Andy2612** [comment]
Versuch jetzt einmal das Game zu Speicher (zur Sicherheit auch ein Backup) und lade über ModHub die neue Version. Dein Problem scheint damit zusammenzuhängen, das die Kurse mit einer älteren Version eingefahren wurden und dort die Datei noch anders benannt worden. Wenn es jetzt mit 1.1.0.5 geht, müsste es nach dem Update über ModHub auch wieder mit der 1.1.0.7 gehen.

**Comment by Axel32019** [comment]
Nichts neues -> closed
