### ISSUE TITLE
[Question] Parkplatzzuweisung entfernen / Remove parking allocation

### ISSUE THREAD

**Issue by MacMoore** [Stephan-S/FS19_AutoDrive#1771]
**Question:**   
I've got a question...
Hi,
gibt es die Möglichkeit im HUD einen versehentlich zugewiesenen Parkplatz wieder zu entfernen, sodas gar kein Parkplatz zugewiesen ist ?
Oder geht das nur über löschen des Wegpunktes ?

Lg....

**Comment by Iwan1803** [comment]
Entweder den Wegpunkt löschen, einen anderen zuweisen oder in der verhicles.xml den Wert von "parkDestination" auf "-1" setzen.

**Comment by MacMoore** [comment]
Danke !
