### ISSUE TITLE
Änderungen Speichern

### ISSUE THREAD

**Issue by Mib83** [Stephan-S/FS19_AutoDrive#1776]
Hallo Stephan,

erstmal Danke für diese schöne Mod.

Ich Spiel jetzt ca 1 Monat und habe vor kurzem den Mod Installiert.
Ich spiele auf der Map Slowakisches Dorf.

Hab das Straßen Netz online Runtergeladen und ins Savegame mit dem Namen AutoDrive_config.xml kopiert.

Er findet das Straßennetz und wenn ich jetzt das Ändere Speichert er es nicht.
Er sollte es doch Automatisch mit Speichern des Spieles Speichern dies macht er aber nicht.

Wenn ich das Spiel Starte und das Savegame Lade sind alle Änderungen weg und es ist wie zuvor.

was mache ich falsch?
Habe die Version 1.1.07-RC1

Danke und Grüße Michael

**Comment by Anonymous-any** [comment]
Hallo, haben Sie versucht, 

- nach Ihren Änderungen zu exportieren und anschließend erneut zu importieren, wenn es nicht angewendet wird?
- Beenden Sie das Spiel normal, nachdem Sie es wie gewohnt gespeichert haben?

weil ich glaube, ohne sicher zu sein, dass die AD-Datei zu diesem Zeitpunkt aktualisiert wird ...

**Comment by rohne83** [comment]
Würde mich nicht wundern, wenn das das selbe ist wie #1769 Siehe dort meine Beobachtung im letzten Kommentar. Könnte von daher ganz hilfreich sein wenn du mal deine log und auch die AutoDrive_config aus dem savegame anhängst.

**Comment by Mib83** [comment]
Hallo,

@Anonymous-any 
Danke für den Tipp das geht.

Ich habe die Strecken geändert und mit der Diskette eine Neue Route Erstellt.
Ich muss zwar bei jedem Start die Route Laden aber es geht.

Danke

**Comment by Anonymous-any** [comment]
Hallo, ich bin froh, dass es dir ein bisschen helfen kann, aber ich verstehe, dass dies nur einen Teil des Problems behebt.
Es sollte nach jedem Neustart danach gespeichert werden ... und Sie sollten nicht jedes Mal neu laden müssen, es ist wirklich nicht praktisch!
Ich habe das Thema @ Stew4u gelesen, das bestätigt, dass Sie in diesem Fall nicht allein sind.

Wenn Sie einmal (mit Sicherungskopien) andere AD-Routen von anderen Karten haben, die korrekt gespeichert wurden, versuchen Sie, alle Einstellungs-Tags zu kopieren und in die AD config.xml-Datei einzufügen, ohne die Wegpunkte zu berühren. noch der Zielpunkt natürlich? Sehen Sie, ob es den Rest Ihrer Sorgen in der Zwischenzeit beheben kann?
Br

**Comment by Mib83** [comment]
Ich habe jetzt ein neues Spiel gestartet und gespeichert und wieder raus.
Dann die neue Autodrive Kopf kopiert und in der alten oberhalb eingefügt.
Jetzt sind aber auch keine Strecken da.

Bin aber auch gerade am überlegen auf eine andere Map zu wechseln und da sind die Kurse schon mit der neuen Version eingefahren. 

Denke man kann dies erst mal zu machen. DANKE

**Comment by kstruessmann** [comment]
Ich bin auch über das Problem und dann diesen Issue gestolpert. Für mich schein es als Wäre die XML Zwischen 1.1.06 und 1.1.07 unterschiedet. Undzwar gibt es in der 1.1.07 den xml tag mit dem Namen der map nicht mehr. Beim speichern sind die Punkten dann doppelt in der xml. es werden aber die mit dem 'alten' geladen und dann scheint es so als wären die neuen punkte nicht gespeichert.
