### ISSUE TITLE
[Question] What does AutoDrive.experimentalFeatures.dynamicChaseDistance do?

### ISSUE THREAD

**Issue by GitTomahawk** [Stephan-S/FS19_AutoDrive#1777]
**Question:**   
What does AutoDrive.experimentalFeatures.dynamicChaseDistance do?
This option seems to be turned on by default but i didnt find any comments her what it is for.

**Question:**   
Wofür ist die experimentelle Funktion AutoDrive.experimentalFeatures.dynamicChaseDistance?
Sie scheint seit einigen Versionen standardmäßig aktiviert zu sein - durch Ausprobieren konnte ich jedoch die Funktion nicht herausfinden.

**Comment by TyKonKet** [comment]
It changes the algorithm used to calculate the tractor chasing position (with forage harvesters), you can give it a try, in my opinion it makes the chasing a bit more realistic but not always and not in all situations it works fine.
