### ISSUE TITLE
[Feature Request] Zwei Richtungsstraße Be und Entladen

### ISSUE THREAD

**Issue by Mib83** [Stephan-S/FS19_AutoDrive#1778]
Ich habe 2 Silos die ich gerne mit einer Zwei Richtungsstraße befahren will und Be und Entladen möchte.

Im ersten versuch habe ich in der Mitte den Punkt gesetzt. Und in den Einstellungen habe ich bei Silo 200m eingestellt.
Aber er bleibt am Anfang vom Traktor/LKW am Punkt stehen und Befühlt und Entladet nicht.

Im zweiten versuch habe ich die Punkte davor und danach gesetzt so das in beide Richtungen Be und Entladen kann.
Habe das in einen Ordner verschoben. In den Einstellungen habe ich mehrere Ziele anfahren eingestellt.
Aber er bleibt immer an dem Vordersten Punkt stehen und Be und Entladen nicht.

Mache ich was Falsch oder geht das nicht?

Wenn das nicht geht wäre das eine schöne Funktion.

**Comment by Axel32019** [comment]
Hallo @Mib83 , Bitte mal einen Screenshot der Situation posten.

**Comment by Axel32019** [comment]
Keine Rückmeldung -> closed
