### ISSUE TITLE
[BUG] Unable to find route

### ISSUE THREAD

**Issue by kaddyuk** [Stephan-S/FS19_AutoDrive#1779]
**AutoDrive Version:** 1.1.07
**Release or Custom Zip:** Release  
**Map (If applicable):** GreenRiver 2019
**Vehicle / Type (If applicable):**   All
**Multiplayer or Singleplayer:** Singleplayer  

**Describe the bug**  
When i create a junction (connect two seperate paths together) in Autodrive, it causes routes to not be found. Am I doing this correctly?

**If applicable - Steps to reproduce the behavior**  

**Screenshots**  
https://vimeo.com/502553544

**Comment by Roby1164** [comment]
It does not say it does not find the routes, but it does not find the destination, so probably, and the section of the route at the destination, or along the road, that there is a problem.

**Comment by jala15** [comment]
Are you connecting the routes with reverse (light blue) lines? Just click the first and then the second waypoint, without pressing Shift key [Wiki - Edit mode](https://github.com/Stephan-S/FS19_AutoDrive/wiki/Edit-Mode#mouse-and-key-actions)

**Comment by kaddyuk** [comment]
@jala15 Correct! I'm pressing shift. Must have got confused in the tutorial I watched at 3am. Thanks for the tip! 

Can close this issue.

**Comment by Iwan1803** [comment]
As you wish.... 😎
