### ISSUE TITLE
Error: Running LUA method 'mouseEvent'.

### ISSUE THREAD

**Issue by docgaming** [Stephan-S/FS19_AutoDrive#178]
[log.txt](https://github.com/Stephan-S/FS19_AutoDrive/files/3242412/log.txt)
 on the new map the pacific north west i keep getting  the same repeating error when i am in the train. it's a long log the errors are at 17:12.

**Comment by Stephan-S** [comment]
Hey,
ist schon gefixed :-)
Kopie von #157 

Bitte updaten, danke
