### ISSUE TITLE
[Question] Hungarian Translation 

### ISSUE THREAD

**Issue by Dueesberch** [Stephan-S/FS19_AutoDrive#1780]
Hi,
Gozmozdony hat eine ungarisch Übersetzung für v1.1.0.7 gemacht. Ich habe sie getestet und kleiner Bugfixes gemacht. Techn. jetzt fehlerfrei.
translation_hu.xml anbei, da ich verständlicherweise keine Berechtigung für git push besitze.
[translation_hu.xml.zip](https://github.com/Stephan-S/FS19_AutoDrive/files/5850400/translation_hu.xml.zip)

**Comment by Axel32019** [comment]
Hallo @Dueesberch , Darfst  Du keinen Pull Request aufmachen?

**Comment by Dueesberch** [comment]
Nope. Vllt ist mein workflow auvh falsch. Project clone - branch create - do changes - commit - push - open pull request. Der push ist mir nicht erlaubt und somit kann ich beim new pr nicht den compare auf beta / master und meinen branch machen

**Comment by Axel32019** [comment]
Bin da auch nicht der Experte, liegt vielleicht daran das es mit Fork losgeht... https://www.youtube.com/watch?v=rgbCcBNZcdQ

**Comment by Dueesberch** [comment]
Pull Request ist gemacht. Ist halt ein anderer Weg. Aber auch verständlich im aktuellen Umfeld (öffentliche Repos). So wird die Last der Repo-Pflege auf den Nutzer umgelegt. Hab Git bis jetzt nur Arbeitsumfeld bzw auf priv. Server genutz und da ist ein Fork eher unüblich.
