### ISSUE TITLE
[BUG]AD Lua call Stack

### ISSUE THREAD

**Issue by Instanz1** [Stephan-S/FS19_AutoDrive#1781]
AutoDrive Version: 

1.1.0.7
--
Release or selbsterstelltes zip: Release
Karte (falls relevant): Hot online F4rm (Multiplayer)
Fahrzeug(art) (falls relevant):

**Beschreibe den Bug**
Kann leider keine genaue Beschreibung nennen, wir haben nur die komplette Log voll mit den Lua call Stack das der Server die Log kürzt, ab und an haben vereinzelt allerdings Leute das, das HUD weg ist und man das Spiel neu Starten muss.

Da leider Log Datei 35MB groß ist habe ich diese gezippt, leider steht auch nicht mehr alles drin vom Server weil die Datei so groß ist.

[log.zip](https://github.com/Stephan-S/FS19_AutoDrive/files/5851625/log.zip)

**Comment by Axel32019** [comment]
Hallo @Instanz1 , Der Eintrag "xMapPos" stammt nicht von AD, das gibt es in AD nicht.
Vermutung: Precision Farming DLC drauf?

**Comment by Instanz1** [comment]
Hallo @Axel32019,
danke für die Antwort, nein den DLC haben wir nicht drauf, habe mal die neue Log angehängt, hier sieht man jetzt auch alle Mods.

Gruß
[log.txt](https://github.com/Stephan-S/FS19_AutoDrive/files/5856752/log.txt)

**Comment by Axel32019** [comment]
Hallo @Instanz1 , Bitte noch die AutoDriveUsersData.xml und AutoDrive_config.xml anhängen, ggf. notwendig in .txt umbenennen.

**Comment by Instanz1** [comment]
Hallo @Axel32019 , hier die Config und die UsersData. 

[AutoDrive_config.txt](https://github.com/Stephan-S/FS19_AutoDrive/files/5857766/AutoDrive_config.txt)
[AutoDriveUsersData.txt](https://github.com/Stephan-S/FS19_AutoDrive/files/5857767/AutoDriveUsersData.txt)

**Comment by Axel32019** [comment]
Hallo @Instanz1 ,
Sorry für die späte Rückmeldung!
Ob das auf AD zurückzuführen ist kann ich noch nicht definitv sagen, jedoch ist folgender Eintrag in AutoDriveUsersData.xml nicht gut - keine Ahnung wie dies zustande kommen konnte:
`guiScale="22"`
Bitte ändern in "2" und ausprobieren...

**Comment by Instanz1** [comment]
Hallo @Axel32019 ,

danke für die Rückmeldung, brauchst dich nicht zu entschuldigen ist ja deine Freizeit :)

habe es mal geändert, allerdings muss ich sagen bisher ist dieser Fehler auch nicht mehr aufgetreten.

**Comment by Axel32019** [comment]
Hallo @Instanz1 , Ich mach hier mal zu, falls es wieder auftritt einfach aufmachen.
