### ISSUE TITLE
[Question] STRAW and BALE delivery?

### ISSUE THREAD

**Issue by huseyinsayar** [Stephan-S/FS19_AutoDrive#1782]
**Question:**   
I've got a question...
STRAW and BALE delivery?
In the training videos I watched, hay, bales etc. It was said that the delivery / storage of products could not be done with AD. Has this changed?
Is it possible to add?
It is boring to go the same route with CP after creating a route with AD.

**Comment by Dueesberch** [comment]
isn't in/added. but you can select AD routes at CP routes list too. I combine field course to collect bales and AD route to deliver at CP to do the job. but CP isn't searching for trigger. you need to set an extra trigger to unload where CP can unload
