### ISSUE TITLE
[Feature Request] Turkish language

### ISSUE THREAD

**Issue by huseyinsayar** [Stephan-S/FS19_AutoDrive#1783]
Can you add Turkish language support? I translated it, put it in the zip file to try it out. When I enter the game it gives MISSING error.

<?xml version="1.0" encoding="utf-8" standalone="no" ?>
<l10n>
	<translationContributors>HSayar</translationContributors>
	<texts>
          <text name="UNKNOWN"                                                                                text="Bilinmeyen"  />
          <text name="input_ADToggleHud"                                                                      text="AD: HUD'yi aç / kapat"  />
          <text name="input_ADToggleMouse"                                                                    text="AD: Fareyi Değiştir"  />
          <text name="input_ADEnDisable"                                                                      text="AD: Etkinleştir / Devre Dışı Bırak"  />
          <text name="input_ADSilomode"                                                                       text="AD: Modu değiştir"  />
          <text name="input_ADRecord"                                                                         text="AD: Kaydet"  />
          <text name="input_ADSelectTarget"                                                                   text="AD: Sonraki Hedefi Seçin"  />
          <text name="input_ADSelectPreviousTarget"                                                           text="AD: Önceki Hedefi Seçin"  />
          <text name="input_AD_Speed_up"                                                                      text="AD: Hızı Artırın"  />
          <text name="input_AD_Speed_down"                                                                    text="AD: Hızı Azaltın"  />
          <text name="input_AD_routes_manager"                                                                text="AD: Yol yöneticisini aç"  />
          <text name="input_AD_open_notification_history"                                                     text="AD: Bildirim geçmişini aç"  />
          <text name="input_AD_continue"                                                                      text="AD: Devam et"  />
          <text name="input_ADSelectTargetUnload"                                                             text="AD: Sonraki Boşaltmayı Seçin"  />
          <text name="input_ADSelectPreviousTargetUnload"                                                     text="AD: Önceki Boşaltmayı Seçin"  />
          <text name="input_ADActivateDebug"                                                                  text="AD: Düzenleme Modu"  />
          <text name="input_ADDebugSelectNeighbor"                                                            text="AD: Komşu Noktayı Seçin"  />
          <text name="input_ADDebugChangeNeighbor"                                                            text="AD: Sonraki Komşu Noktasını Seçin"  />
          <text name="input_ADDebugCreateConnection"                                                          text="AD: Bağlantıyı değiştir."  />
          <text name="input_ADDebugCreateMapMarker"                                                           text="AD: Hedef Ekle / Düzenle"  />
          <text name="input_ADRenameMapMarker"                                                                text="AD: Seçili Hedefi düzenleyin"  />
          <text name="input_ADDebugDeleteWayPoint"                                                            text="AD: Ara Noktayı Sil"  />
          <text name="input_ADDebugDeleteDestination"                                                         text="AD: En yakın Hedefi Sil"  />
          <text name="input_ADSelectNextFillType"                                                             text="AD: Sonraki Dolum Türünü Seçin"  />
          <text name="input_ADSelectPreviousFillType"                                                         text="AD: Önceki Dolum Türünü Seçin"  />
       [https://drive.google.com/file/d/1HiXK5g5QDnRUgpU9sn51rDooF-u40bmK/view?usp=sharing](url)

**Comment by Dueesberch** [comment]
I fixed your translation. Do you got discord accound? So I can send you the file and you can check and create the pull request if everything is ok

**Comment by huseyinsayar** [comment]
huseyinsayar#8629

**Comment by Axel32019** [comment]
@huseyinsayar , @Dueesberch Could this be closed, as PR is merged?

**Comment by Dueesberch** [comment]
Can be closed.
