### ISSUE TITLE
[Question] Modus Abholen Abliefern mit Ladewagen, Frucht ausschalten bzw. automatisch ändern +++ Mode Pick-up Deliver with Loader wagon, switch off fruit or change automatically

### ISSUE THREAD

**Issue by haamic** [Stephan-S/FS19_AutoDrive#1785]
**Question:**   
Szenario:
-Per CP mit Ladewagen auf Feld unterwegs
-wenn voll, Fahrt mit AD (Abholen Abliefern) zum Abladeziel
-unmittelbar neben dem Abladeziel ist ein anderer Silo, der Ladewagen unbeabsichtigt wieder befüllt, da gleiche Frucht enthalten, wie im HUD eingestellt (bei Ladewagen nicht erforderlich)

Ist es möglich, das AD erkennt, wenn ein Ladewagen angehangen ist und die "Input-Frucht" "abschaltet" bzw. auf eine nicht mit dem Ladewagen ladbare Frucht ändert?  In dem Fall nimmt ja der Ladewagen selber auf was auf dem Feld liegt und wird nicht an einem Silo befüllt, wo man die Frucht selbst auswählen muss.

Der Ladewagen kippt in meinem Beispiel am Ziel ab, fährt dann aber an dem anderen Silo vorbei und lädt Frucht auf, die im AD Hud (noch) drin steht, von evtl. früheren "Jobs".
Ich hab nun die Frucht auf z.b. Kalk gestellt, damit der Ladewagen ablädt, aber nicht befüllt wird, da im Silo kein Kalk drin ist.

Bevor jetzt Antworten kommen, etwas am Streckennetz zu ändern , die Silos umzubauen/Abstand ändern, oder aufzupassen, was im HUD steht....
Stop....das ist ja nicht meine Frage. 
Möchte einfach nur wissen, ob es relativ einfach wäre, den Ladewagen in AD in dem speziellen Transportmode fruchtmässig anders zu behandeln, als normale Anhänger. Das kann bestimmt jemand, der den AD-Code gut kennt, wie z.b. @Axel32019 gut beantworten.
Ein Ja, relativ einfach machbar, oder ein Nein, zu viel Aufwand reicht mir. Danke.
Gruss Micha
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Scenario:
-Per CP with loader wagon on the way to the field
-If full, drive with AD (pick up deliver) to the unloading destination.
-Another silo is immediately next to the unloading destination, the loader wagon is unintentionally filled again because it contains the same fruit as set in the HUD (not necessary for loader wagons).

Is it possible that AD recognises when a loader wagon is attached and "switches off" the "input fruit" or changes it to a fruit that cannot be loaded with the loader wagon?  In this case, the loader wagon itself picks up what is in the field and is not filled at a silo where you have to select the fruit yourself.

In my example, the loader wagon tips off at the destination, but then drives past the other silo and loads fruit that is (still) in the AD Hud, from possible earlier "jobs".
I have now set the fruit to e.g. lime, so that the loader wagon unloads but is not filled, as there is no lime in the silo.

Before people start replying about changing the route network, rebuilding the silos/changing the spacing, or paying attention to what the HUD says....
Stop....that's not my question. 
Just want to know if it would be relatively easy to treat the loader wagon in AD in the special transport mode fruitwise differently than normal trailers. I'm sure someone who knows the AD code well, like e.g. @Axel32019 can answer it well.
A yes, relatively easy to do, or a no, too much effort is enough for me. Thank you.
Greetings Micha

**Comment by Axel32019** [comment]
Hallo @haamic , Würdest Du bitte einen Screenshot von Deinen Abladestellen anhängen damit ich mir das besser vorstellen kann.
Habe im beta-Zweig einiges zum Be-/Entladen geändert, kann also gut sein das das damit schon funktioniert - kannst Du das bitte mal bei Dir ausprobieren?

**Comment by haamic** [comment]
Screenshot kann ich morgen erst machen. Ich nutze ständig die Beta um jede Neuerung auszutesten. oder hast du jetzt erst was geändert? 
Das ich die Beta nutze, vergess ich nur meist, da sie ja prima läuft.
Aber vielleicht liegt's ja gerade an der Beta , das er lädt wo er kann (Silo) und nicht ausschließlich nur da, wo er soll. 
Dabei fällt mir ein , das auch mal ein normaler Anhänger abgeladen hat, wo er konnte, auf der Fahrt zum eigentlichen Ziel und nicht wo er sollte. Müsste ich morgen mal mit dem aktuellen offiziellen Release probieren.

**Comment by Axel32019** [comment]
Bitte beachten das innerhalb des max. Siloabstandes immer versucht wird zu be- und entladen.
Da ich ja nicht weiß von wann Deine beta ist, bitte mal mit der aktuellen ausprobieren.

**Comment by haamic** [comment]
Also die Beta ist immer aktuell, ich schau ja jeden Tag, ob Änderungen gemacht wurden. 
Das hat mir jetzt aber keine Ruhe gelassen. ich hab jetzt nochmal mit der aktuellen Releaseversion getestet. da klappt es. 
Mit der Beta hat er wie im Bild zu sehen, an (1) abgeladen, ist wieder gestartet (2) zum Feld und hat aber gleich beim überfahren von (3) wieder z.b. Gras geladen, weil Gras im HUD stand. 
Nun macht er das nicht. Lädt ab und fährt zum Feld. Das ursprüngliche Verhalten kam also durch die Beta zustande. 
![image](https://user-images.githubusercontent.com/28841989/105615098-3b08a300-5dce-11eb-842c-13291cc473dd.jpeg)
