### ISSUE TITLE
Frage zu einem Mod  der nicht mit Autodrive geht

### ISSUE THREAD

**Issue by streubeheubar** [Stephan-S/FS19_AutoDrive#1788]
**Question:**   
I've got a question...

Hallo

Ich habe immer wieder mal Mods  bei denen das mit dem Klick auf die mittlere Maustast nicht klappt

Ich kann die mittlere Maustast so of ich will , ich komme nicht mit der Maus auf den AD hud.

Log ist sauber

Um Auszuschliessen das es ein anderer Mod ist ....... hatte ich nur den Traktor und Autodrive drinnen im Modsordner

Das ist der Mod

https://www.modhoster.de/mods/fendt-favorit-600-lsa-pack--2

Wäre schön wenn ihr mir helfen könntet

mfg

Streubeheubar

**Comment by Bormbo** [comment]
Moin,

der Fendt hat IC Steuerung verbaut, denke dort gibt es doppelte Tastenbelegungen. Am besten prüfen.

Mfg,
Bormbo

**Comment by streubeheubar** [comment]
Hallo 

Das hatte ich auch vermutet. 
Ist es aber nicht.
Ist aber nicht mehr so wichtig,... danke für die Antwort 

Kennst du dich gut mit dem Autodrive aus ?

Bei mir fährt der ad immer Umwege...... auch wenn ich in der Einstellung  Umwege auf 0 stelle.

,mfg Martin
