### ISSUE TITLE
[Feature Request] Route presets

### ISSUE THREAD

**Issue by Siginek** [Stephan-S/FS19_AutoDrive#1789]
Hello, i would like to have some kind of "route presets"
Basically you could set route (start, destination, mode, transported goods) and then save it.
Later when it would be selected, it would set all parameters of route - mode, goods, start and destination - automatically, instead of selecting each.

It would really make it easier to do periodical tasks like animal feeding, transporting of crop between silos etc.

How it could look like:
In edit menu there would be 2 new buttons - one to Save preset and another to delete selected preset
If user would save preset with name, that already exists, old preset would be overwritten
Generally in AD UI would be new dropdown for presets, which could be enabled/disabled in options

**Comment by mricher-git** [comment]
+1 very nice idea

**Comment by TripleX1978** [comment]
Good idea!
