### ISSUE TITLE
[Feature Request] Remove parking position

### ISSUE THREAD

**Issue by bojanh66** [Stephan-S/FS19_AutoDrive#1790]
**Is your feature request related to a problem? Please describe.**  
I'm always frustrated when i accidentally assign parking position to implement instead of vehicle.

**Describe the solution you'd like**  
Option to remove Parking Position from implement/vehicle, maybe with LShift + clicking on "P" or something like that

**Describe alternatives you've considered**  

**Additional context**

**Comment by Bobster82** [comment]
I vote on this issue too... I like the "extra" button needed to assign parking spots... I always assign random spots to vehicles when i right click to activate the mouse (courseplay) and the mouse is exactly over the "P" button... I asked a while back, but I hope we get this working ;)
