### ISSUE TITLE
Problems with AD and CP in combi mode

### ISSUE THREAD

**Issue by ninjayx02** [Stephan-S/FS19_AutoDrive#1794]
Well,  It must be me,  but since updating both CP and AD I cannot fathom out how to use the CP combi mode with AD.  Granted,  I haven't used it for a while, but last time I used it was on the Western Australia map and had no problems at all.  Pointers on how to resolve this would be greatly appreciated as CP and AD are 2 of the best mods available

**Comment by 60erjonny** [comment]
hallo
It was a great help for me, at the beginning of the service ... 
https://github.com/Stephan-S/FS19_AutoDrive/wiki

**Comment by Tensuko** [comment]
CP Combi Mode is not able to work with AD yet, see https://github.com/Courseplay/courseplay/issues/5284

**Comment by Axel32019** [comment]
So far clear -> closed.
