### ISSUE TITLE
Whats the reason why AD sometimes cant find a way off the field [Question]

### ISSUE THREAD

**Issue by Gariot** [Stephan-S/FS19_AutoDrive#1795]
**Question:**   
Hey,

i wonder whats the reason an AD driver sometimes cant find a way off the field to its target location after he reached his load limit. Its kinda strange that it works properly most of the time and sometimes AD just says "nope, i cant find a way" and quits. I already made blue internal lines in my fields with several exits to make sure he always finds a way. But it still happens. Is there a way i can avoid that?

**Comment by Crinouche** [comment]
I too have this problem. If there is a way to fix this problem, I'm interested!

**Comment by leo32128fs** [comment]
I decided to draw an internal line in the field and solved the problem

**Comment by Gariot** [comment]
Yea, i did that too. I edited my post to make it more clear, sorry. It still happens every now and then. I dont understand why since i cant even replicate it reliable.

**Comment by Axel32019** [comment]
Hello @Gariot @Crinouche @leo32128fs 
To find a way is dependend on many influences:
- settings fruit, restrict to field, pathFinderTime
- terrain outline, water, slopes, obstacles, road network
- fruit, vehicles, size of field
and some more...
If you are interested in details, feel free to look into PathFinderModule.lua :-)
We made some improvements here, which took over 4 weeks , so you may test the beta version of AD to find it out - see #1663

**Comment by Gariot** [comment]
Thanks for your reply. I hoped you may know a way to make it more easy for AD to always find a way without quiting (other than whats already suggested) :)

Good to know that you made some improvements. I will wait for a release :)

**Comment by Crinouche** [comment]
YES, thank you for your answer
