### ISSUE TITLE
AD erkennt den Schlepper nicht als Traktor/ Fahrzeug  ------ AD does not recognize the tractor as a tractor / vehicle 

### ISSUE THREAD

**Issue by Schmidi79** [Stephan-S/FS19_AutoDrive#1796]
AutoDrive Version: 1.1.0.7
03.02.21 im GitHub aktuellen datei runtergeladen

Karte (falls relevant): Alle
Fahrzeug(art) (falls relevant):Deutz-Fahr Serie 6
https://www.farming-simulator.com/mod.php?lang=de&country=de&mod_id=193173&title=fs2019

servus
Das Problem bei dem Mod ist, das der AD den Schlepper nicht als Traktor/ Fahrzeug erkennt, und daher kein AD Fenster einschalten, bezw, Aktivieren kann

Hab beim Googeln nach dem Problem erfahren, das der  Traktor in der xml datei  in der Zweiten zeile folgendes  drinnen steht
vehicle type="series6"

Anscheinend ist es so das AD den Type "series6" nicht als Fahrzeug erkennt,
wenn ich aber **"series6"** durch **"tractor"** ersetz hab ich zwar dann AD, aber Probleme mit der Config vom Mod

jetzt hab ich mehrere Fragen dazu, bezw was ist machbar ist für euch

1. gibts demnächst ein Update von euch, das ich diesen Traktor auch mit AD benutzen kann

2. Gibts ne Möglichkeit, Im Ad im Scrip was einzutragen, das der AD den Traktor erkennt

3.welche Tipps könnt ihr mir geben, was ich am Mod "noch" ändern muss, wenn ich 
<vehicle type="series6">	 duch <vehicle type="tractor">	ersetze, das die srcip funktionieren

MFG Schmidi

**Comment by Iwan1803** [comment]
Nicht falsch verstehen, aber warum sollen wir AD "verbiegen", wenn Modder der Meinung sind, sich eigene Fahrzeugtypen ausdenken zu müssen, damit ihre Mods funktionieren? Dann müssten wir eine große Liste von solchen Non-Standards einpflegen.
Leider kann ich dir nicht sagen, wie der Mod angepasst werden müsste oder ob das überhaupt möglich ist.

**Comment by Schmidi79** [comment]
servus.
Danke erstmal für eure Antwort

Ja klar kann ich euch gut verstehen, das ihr nicht auf alles eingehen könnt, wenn die Modder eigene Typen erstellen, 
was für euch  genauso ärgerlich ist, weil da ihr nur am Nacharbeiten seid was die Frage 1betrifft

zu frage 3 habe ich mir fast gedacht das, ihr evtl nicht weiterhelfen könnt, 
dachte nur das ihr da vieleicht schon öfter das Problem hattet und soweit Tipps habt, mit dem Problem des schnell und Leicht abzuändern

jetzt bleibt für mich nur noch die Frage übrig
Gibts ne Möglichkeit, Im Ad im Scrip was einzutragen, das der AD den Traktor erkennt
mir ist dann zwar schon klar, das ich bei jeder neuen version von euch ich des nachtragen mus
und des macht ja dann ja nur Sinn, wenn es um 1 oder 2 dateien  sind wo ich ne **kleinigkeit** ändern mus,

bei gröseren aufwand macht es natürlich auch keinen Sinn des , des zu ändern, 
und ich muss mich halt damit abfinden, dann ist halt eben so,

**Comment by Iwan1803** [comment]
Das logischste zu Frage 2 hast du ja schon probiert, indem du den richtigen Fahrzeugtypen eingetragen hast, was dann aber wieder zu anderen Problemen führt. Vielleicht kannst du hier einfach mal Kontakt zum Modder aufnehmen. Es soll tatsächlich welche geben, die nicht auf stur schalten und beratungsresistent sind 😉
Zu Frage 3 kann ich nur sagen, das der Quellcode ja offen ist, aber ich kenn dir nicht genau sagen, wo und wie oft der Fahrzeugtyp abgefragt wird und an welcher Stelle überall was zu ändern ist. Problem ist nur, das wenn du was änderst, das mit jeder neuen Version ja wieder ändern müsstest, damit gewisse Mods wieder mit AD funktionieren. Ob du den Aufwand betreiben möchtest, liegt dann an dir.
Ich an deiner Stelle würde auf den Mod verzichten und mir eine Alternative zu dem o.g. Mod suchen, welcher dann auch mit AD out-of-the-box funktioniert, falls der Modder des o.g. Mods nichts ändern möchte oder kann.

**Comment by Schmidi79** [comment]
Danke für die schnellen Antworten, 
Wird mir nichts anderes übrigbleiben ihn Auszutauschen, gibt leider zu wenig von der sorte

wünsche euch trotzdem weiterhin viel erfolg mit AD auch in zukunft

Mfg Schmidi
