### ISSUE TITLE
Downhill driver 1 jumps when setting to downhill driver 2 

### ISSUE THREAD

**Issue by KarlGutenberg** [Stephan-S/FS19_AutoDrive#1797]
AutoDrive Version: 1.1.07
Release or selbsterstelltes zip: Release 50
Karte (falls relevant): Alle
Fahrzeug(art) (falls relevant): Fendt

**Beschreibe den Bug**
"Es stehen mehrere Abfahrer nebeneinander"
Wenn ich auf dem Abfahrer 1 eine Einstellung vornehmen will
springt AD auf den Abfahrer 2, wenn dieser
direkt daneben steht! 
**Falls anwendbar - Schritte mit denen ich den Bug nachstellen kann**
zwei oder 3 Abfahrer nebeneinander stellen und den ersten versuchen einzustellen!
geht nur, denn der einzustellende weiter vorgezogen wird!
Also etwas weiter weg von den anderen.

Sorry ich bin neu hier und konnte noch keine solche Meldung finden
was ich da anders einstellen muss!

**Comment by 60erjonny** [comment]
Hallo

CP auch im Einsatz...?
Wenn ja, die Einstellung "Klick zum einsteigen" aktiviert...?
Dann kann es unter Umständen passieren, das man durch das AD-HUD in das andere Fahrzeug einsteigt, wenn sich dieses AD-HUD im Bild über das andere Fahrzeug befindet.
![Screenshot (36)](https://user-images.githubusercontent.com/63659182/107113599-41802b80-6860-11eb-8388-1c944474d5fe.png)
Ja ist irgendwie blöd, habe die Einstellung aber wieder deaktiviert, um das zu vermeiden...

**Comment by KarlGutenberg** [comment]
Nicht bei den Abfahrer

Am Sa., 6. Feb. 2021 um 09:49 Uhr schrieb 60erjonny <
notifications@github.com>:

**Comment by Gariot** [comment]
Wie, nicht bei dem Abfahrer? CP ist in allen Fahrzeugen wenn es im Spielstand ist und die Option "Klicken zum einsteigen" ist eine Globale CP einstellung die du ggf. einfach mal ausstellen solltest. 
Dein Problem hatte ich naemlich auch und es lag definitiv an dieser Option ;)

**Comment by KarlGutenberg** [comment]
Stimmt!!
Wenn ich Klick für das Einsteigen deaktiviere
funktioniert es
Danke Dir für diesen Tipp

**Comment by 60erjonny** [comment]
Hallo @KarlGutenberg 
Die Switch - Einstellung von CP an sich wäre ja nicht schlecht, aber in Verbindung mit AD, dann doch irgentwie blöd.
Ich glaube und meine zu wissen, es ist nicht so einfach umsetztbar, das man das AD-HUD, ich nenne es man so "undurchklickbar " macht...:-)
