### ISSUE TITLE
[route speed]

### ISSUE THREAD

**Issue by leo32128fs** [Stephan-S/FS19_AutoDrive#1798]
hello I wonder if it is not possible for AD to control the recording speed of the route as the CP does

**Comment by leo32128fs** [comment]
It's just a curiosity! because it would be interesting, I love this mod

**Comment by Axel32019** [comment]
Hello @leo32128fs ,
The basic aspect of AD is that vehicles may drive as fast/slow as they can, i.e. faster or slower than the route was recorded.
It would be not nice if you record at 30 kph and a truck, which is able for 90 kph, will then drive at 30 kph.
The max. speed could be adjusted in HUD, the courve speed in the settings of each vehicle.

**Comment by Crinouche** [comment]
> Bonjour @ leo32128fs ,
> L'aspect de base de l'AD est que les véhicules peuvent rouler aussi vite / lentement que possible, c'est-à-dire plus vite ou plus lentement que l'itinéraire a été enregistré.
> Ce ne serait pas bien si vous enregistrez à 30 km / h et qu'un camion, capable de rouler à 90 km / h, roulera alors à 30 km / h.
> Le max. la vitesse peut être ajustée dans le HUD, la vitesse de course dans les paramètres de chaque véhicule.

Hello,

I understand what you mean, but what is a shame is that vehicles go as fast on dirt tracks as they do on roads

**Comment by Michael170978** [comment]
Ich glaube das Thema wird nie aussterben. Ich denke es ist jedem klar, dass Autodrive ein Hilfsmittel ist Fahrzeuge von A nach B zu bringen. Aber wenn man sieht, dass ein Vehicle auf eigenem Bauernhof mit 40km/h drüber fliegt, dann wünscht man sich schon, auf diesem kurzen Teil das Fahrzeug "künstlich" zu reduzieren. Deshalb liebe Moder von Autodrive kann man nicht über der Route  ala Verkehrsschilder anbauen, die besagen hier gilt reduzierte Fahrgeschwindigkeit? Dadurch könnten auch Holztransporter in den Wälder schön mit 10km/h fahren und nicht wie wild gewordene Sau mit 60km/h. Ich hoffe dieser Traum geht irgendwann in Erfüllung.

**Comment by Axel32019** [comment]
Hier kann ich nur auf bekannte Youtuber verweisen die zeigen wie z.B. bei Radar-Fallen die Geschwindigkeit mit Hilfe entsprechender Wegpunkte im "Zick-Zack" reduziert werden kann.
In absehbarer Zeit und in Anbetracht von LS22 in Sicht werden wir das wohl nicht mehr angehen.
