### ISSUE TITLE
Gleichzeitige Befüllung und Abkippen

### ISSUE THREAD

**Issue by RedOhne** [Stephan-S/FS19_AutoDrive#18]
Hi, 

habe heute ausgiebiger den AutoDrive Mod auf der New Woodshire Karte getestet. Beim dortigen Hofsilo befindet sich der Trigger zum Abkippen unter dem Trigger zum Beladen der Hänger. Der Hänger steht also Zeitgleich in beiden Triggern. Autodrive startet nun, sobald der Hänger leer aber noch beim Abkippen ist die Befüllung, so dass sich das ganze in ein Endlosschleife befindet. Kannst du einmal prüfen, warum die Befüllung gestartet wird, obwohl als Modus lediglich liefern und nicht abholen und beliefern gewählt wurde?

Kann ich das irgendwie loggen, oder wir weitere Hilfe zur Verfügung stellen?

Danke Tim

**Comment by Stephan-S** [comment]
Hey, danke für's Melden. Wird mit dem nächsten Update behoben
