### ISSUE TITLE
[Feature Request] Exactfillnode

### ISSUE THREAD

**Issue by jobyrns72** [Stephan-S/FS19_AutoDrive#1800]
Hello I was wondering if there was anyway of ad recognizes an exactfillnode as a trigger?

**Comment by Iwan1803** [comment]
What does "exactfillnode" mean?

**Comment by jobyrns72** [comment]
What I'm wanting to do is basically unload into a trailer. I believe the exactfillnode is like a trailer's trigger to unload into it

**Comment by jobyrns72** [comment]
This is what I'm trying to do but would in other instances. In the USA we have upright silage silo which you use a implement called a silo blow which offloads a trailer and uses air to blow it up a pipe to the top of the silo. My silo blower is set up as an auger wagon and auto drive doesn't recognize it but I could see unloading in a trailer in other times that could be useful

**Comment by Axel32019** [comment]
Hello @jobyrns72 , Please give the beta-Version a try, as we have implemented overloading to other trailers. Just set it up as usual at triggers.

**Comment by jobyrns72** [comment]
Thanks a lot works perfect!!
