### ISSUE TITLE
[Question] can’t calculate path?

### ISSUE THREAD

**Issue by matty2123** [Stephan-S/FS19_AutoDrive#1801]
Hello what am I doing wrong I keep getting can’t calculate path?

**Comment by Iwan1803** [comment]
Wait, let me ask my crystal ball....
Some more informations, screenshots, etc. could help us to help you 😎

**Comment by Iwan1803** [comment]
Problem gone as reported in Discord.

**Comment by matty2123** [comment]
It’s not working I’ll get some screenshots I’m using a premaid course with courseplay when it’s empty to go and refill it’s saying planning route and then it comes up with can’t calculate path and then it turns it’s self off
