### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Crinouche** [Stephan-S/FS19_AutoDrive#1803]
![image](https://user-images.githubusercontent.com/36656729/107269010-4227e600-6a49-11eb-9579-b0acf10bab80.png)
Hello,

A few days ago, I informed you of some silage harvesting problems in the fields, in particular the fact that the tractor takes a long time to find its route in the round trips.
But here I have another problem. If I put the forage harvester with the worker (H key) the tractor moves forward to the forage harvester, then suddenly backs up. It does not roll alongside.

**Comment by Iwan1803** [comment]
Is it a grass field?

**Comment by Iwan1803** [comment]
Dublicate #1804
