### ISSUE TITLE
[BUG]the tractor does not drive alongside the forage harvester

### ISSUE THREAD

**Issue by Crinouche** [Stephan-S/FS19_AutoDrive#1804]
![image](https://user-images.githubusercontent.com/36656729/107269010-4227e600-6a49-11eb-9579-b0acf10bab80.png)
Hello,

A few days ago, I informed you of some silage harvesting problems in the fields, in particular the fact that the tractor takes a long time to find its route in the round trips.
But here I have another problem. If I put the forage harvester with the worker (H key) the tractor moves forward to the forage harvester, then suddenly backs up. It does not roll alongside.

**Comment by Iwan1803** [comment]
Looks like a grass field. What are the settings of the tractor? Does it have a front weight?

**Comment by Crinouche** [comment]
Yes, it is a field of grass.
No weight at the front as you advised me in another post.
In the photo, the settings.
![image](https://user-images.githubusercontent.com/36656729/107336379-50ade600-6ab9-11eb-8e38-e2a144ceeab0.png)

**Comment by jala15** [comment]
Try setting avoid crops (Éviter les cultures) to no. Giants tells AD that cut grass is also a crop

**Comment by envikowaty** [comment]
The problem is also with the forage harvester pipe, when you take a model with sort pipe there will be definitely a problem to reach it by tractor

**Comment by Crinouche** [comment]
This is a long pipe !!

**Comment by Crinouche** [comment]
> Essayez de régler éviter les cultures (Éviter les cultures) sur no. Giants dit à AD que l'herbe coupée est aussi une culture

i will test this as soon as possible

**Comment by Tensuko** [comment]
Chopped/mowed grass is reported as fruit, that might be a problem here and is the same problem for us on CP.

Long Pipe doesn't help.
There are 2 Values on a Chopper, that determins how far they can throw their stuff:

maxDistance (wich we modifie to 40 when running the Chopper with CP)

`<dischargeNode node="pipeRaycastNode" emptySpeed="1000" fillUnitIndex="1" maxDistance="40" stopDischargeOnEmpty="false">`

and maxRotationLimits is modified to "- - -"

`<pipeNode node="pipeBase" rotationSpeeds="0 35 0" autoAimYRotation="true" autoAimInvertZ="true" minRotationLimits="- -100 -" maxRotationLimits="- 100 -" foldPriority="1">`

**Comment by jobyrns72** [comment]
I'm having the same problem driver pulls up a little then backs up saying combine is turning and it keeps doing this in a loop

**Comment by Stephan-S** [comment]
I think that is resolved now. If not, please reopen and we will check this again.
