### ISSUE TITLE
Can’t calculate a path 

### ISSUE THREAD

**Issue by matty2123** [Stephan-S/FS19_AutoDrive#1805]
Hello I’m having trouble using autodrive I’m using a premade course with courseplay when it’s empty to go and refill it’s saying planning route and then it comes up with can’t calculate path and then it turns it’s self off can’t see what I’m doing wrong?

**Comment by Iwan1803** [comment]
Same like here: https://github.com/Stephan-S/FS19_AutoDrive/issues/1801 ?
and same here:

> Wait, let me ask my crystal ball....
> Some more informations, screenshots, etc. could help us to help you 😎

**Comment by matty2123** [comment]
There is no screenshots that can show the problem and info is the same as last

**Comment by Iwan1803** [comment]
How should we help without any information from your site? 🤔

**Comment by matty2123** [comment]
Right here goes I’m using courseplay to do my field work and using autodrive to collect some more seeds or whatever I’m doing. I’m enable autodrive in the courseplay hud. Right the tractor gets to 0% and then obviously autodrive should take over but I’ll get a little box saying xxx can’t calculate a path and then the autodrive hud on/off button will go off. If I then manually turn autodrive on again it will then set off on the route selected. So my question and problems is why is it failing to find a path? You guys develop this mod what could be the cause for this problem? I’m using a premade course available on datalands discord channel and not being an expert on autodrive I don’t know if it’s me or the shared course or autodrive.

**Comment by Axel32019** [comment]
Hello @matty2123 ,
You may have a look here #1795 as well.

**Comment by matty2123** [comment]
Thanks for the reply @Axel32019 i shall have a go on the beta

**Comment by matty2123** [comment]
https://vimeo.com/511744960?ref=em-share This is what is happening I’ve got a course from lime station it proceeds to fill up and then not going to lime tip what i made as you can see it says can’t reach lime station

**Comment by Axel32019** [comment]
At least for me it is very hard to figure out what is not OK from your video.
Could you please provide screenshots from the AD settings and the AutoDrive_config.xml?

**Comment by Axel32019** [comment]
no information -> closed.
