### ISSUE TITLE
[BUG]no Path to waypoint over blue lines

### ISSUE THREAD

**Issue by Rumspringa90** [Stephan-S/FS19_AutoDrive#1807]
AutoDrive Version: 1.1.1.6 / 1.1.1.7 / aktuelle Beta
Release or selbsterstelltes zip: beides

**Beschreibe den Bug**
"Der Fahrer von xx hat keinen Weg gefunden zu Abf. Feld 38"
Ich habe auf einem Schmalen Feldweg eine beidseitig befahrbare blaue Linie von der eine grüne Linie zu dem Wegpunkt. (siehe Screenshot) Ich komme dort von rechts und links am ende der blauen Linie befindet sich ein Wendekreis.
Ich vermute, er will direkt zum Wegpunkt ohne über den Wendekreis zu fahren und findet dann kein Weg weil der Winkel zu groß ist.
Ich hab das mal versucht zu skizzieren:
Ich vermute wie gesagt das er den roten weg folgen will anstatt den orangenen. Kann man das irgendwie umgehen?
![skizze](https://user-images.githubusercontent.com/50840355/107849955-e66dac00-6dfe-11eb-8f24-b317e1259a74.jpg)

**Screenshots**
![Pathfinding](https://user-images.githubusercontent.com/50840355/107849588-92fa5e80-6dfc-11eb-8466-bd0a5852ebda.jpg)

**Comment by 60erjonny** [comment]
Hallo
Wie hoch hast du in AD den maximalen Umweg eingestellt...?
Verbinde mal den Zielpunkt 38 mit der blauen Linie wieder zurück, evtl. hilft das Ad auch...

**Comment by Rumspringa90** [comment]
Nabend,
Max Umweg ist bei 1000m
genau, links ist nur der Wendekreis. ist quasi eine Einbandstraße. Und weil es nur eine enger Feldweg ist, eine blaue Linie.

**Comment by jala15** [comment]
AD is not able to drive over the same waypoint twice yet, so it can´t go forward and backwards on the same blue line.

> ![bosquejo](https://user-images.githubusercontent.com/50840355/107849955-e66dac00-6dfe-11eb-8f24-b317e1259a74.jpg)

**Comment by 60erjonny** [comment]
Hallo

Habe es selber versucht nach zu stellen, bin auch damit gescheitert...

Zitat: Kann man das irgendwie umgehen?

So wie ich das auch hier sehe, du fährst doch auch wo anders wieder ab von diesem Feld 38...?
Mach statt der blauen eine seperate grüne Linie von der Öse und schließe dann, direkt sperat wieder an die Zufahrt " Ziel" an...
Also das Ziel nicht direkt an die blaue Linie anschließen, sondern direkt an die Öse...

**Comment by Stephan-S** [comment]
Improved algorithm in current beta already included.
