### ISSUE TITLE
[Featurerequest] Anpassen der Wegpunkthöhe nach Verwendung des Landscaping-Tools / Adjust waypoint height after using the landscaping tool

### ISSUE THREAD

**Issue by flattergaul** [Stephan-S/FS19_AutoDrive#1809]
Hallo AD-Team, 

**Das Problemchen:**
Wenn das Gelände mit dem Landscaping-Tool verändert wird, bleiben die Geländehöhen der AD-Wegpunkte so wie das Gelände bei der Erstellung des Wegpunktes war.
Erst wenn die einzelnen Wegpunkte angeklickt werden, erfolgt eine Höhenanpassung.
Das kann natürlich bei größeren Geländeänderung mühsam werden.

**Eine mögliche Lösung:**
Eine Funktion in den Einstellungen, mit der die Geländehöhen der Wegpunkte gecheckt und ggf. angepasst werden.

**Eine andere mögliche Lösung:**
Bei Start des LS checkt AD automatisch die Höhen und passt sie gegebenenfalls an. Vermutlich ist es da sinnvoll, das in den Einstellungen aktivier-/deaktivierbar (so wie Feldscan/Kurse laden bei Courseplay) zu machen.

Beste Grüße aus Wien & danke für AD
Michael

--- ENGLISH ---
Hi AD-Team,

**The little problem:**
When adapting the terrain with the landscaping-tool, the terrain heights of the AD-waypoints stay unchanged.
Only when the individual waypoints are clicked the altitude will be adjusted.
When making bigger terrain adjustments, this can be pretty hard.

**A possible solution:**
A function in the settings that checks the terrain heights of the waypoints will be checked and adjusted automatically if necessary.

**Another possible solution:**
When the LS starts, AD automatically checks the heights and adjusts them if necessary.
Presumably it makes sense to have a function to activate/deactivate this in the settings (like field scan / loading courses in Courseplay).

Best wishes from Vienna & thanks for AD
Michael

**Comment by Stephan-S** [comment]
Hey, I just answered to another issue of yours.
I guess you already see the problem here right?
You can either have one or the other. Meaning, we cant check for the ground height for every node on startup and yet allow you to manually set the height of each point.
So in favor of the manual mode, I will close this one.
