### ISSUE TITLE
non useable fill types

### ISSUE THREAD

**Issue by docgaming** [Stephan-S/FS19_AutoDrive#181]
there are some non useable fill types can you remove some of them to help clean up the drop down menu. 
chickens x4, cow x8, horse x8, pig x4, sheep x4, weed, bales, oilseed radish, unknown, trap (i don't know what this is), tree saplings and there is 3 for grass.
![Screenshot_8](https://user-images.githubusercontent.com/48932718/58746882-803ecb00-845b-11e9-80f7-9f9bee4cdb5a.png)
 
when it was not in alphabetical order it was not to bad as most of that was at the end

**Comment by Stephan-S** [comment]
Mache ich gerne.
Hast du Lust mich dabei zu unterstützen?
Ich würde die ungewünschten Ids ausfiltern.
Hier ist ein Version die, die IDs neben den Namen auflistet:

[FS19_AutoDrive.zip](https://github.com/Stephan-S/FS19_AutoDrive/files/3243698/FS19_AutoDrive.zip)

kannst du mir alle unnützen IDs auflisten, dann mache ich damit einen Filter.

Vielen Dank!

**Comment by docgaming** [comment]
I will love to help but i don't think i know enough about programming. i have had a look at the files but i can not find where AD gets the fill type names or ID's from

**Comment by Stephan-S** [comment]
hey, no problem.
but I didn't mean you have to look into the code, sorry :-)
The version I send you displays the id next to the fillytpye when you open the pull down list in the game.

**Comment by Stephan-S** [comment]
and sorry for writing back to you in german :-D switching back and forth here in the issue comments^^

**Comment by docgaming** [comment]
ok i will have a look then and let you know.
I have auto translate so use what ever lounge you like :)

**Comment by docgaming** [comment]
Air 34 (no mods use this yet that i know of) but keep it
Cotton 11 ( some silos can store it but i don't know how) it's up to you on that
chicken 77,78,79,80   remove
Cow 61,62,63,64,65,66,67,68 remove
Eggs 14 remove
Grass 27,28,29 (only need one) remove two
Horse 53,54,55,56,57,58,59,60 remove
Oilseed Radish 25 remove
Pig 73,74,75,76  remove
Round bale 36,37,39,38,35  remove
Sheep 69,70,71,72 remove
Square bale 42,41,40 remove
Tarp 49 ( i don't even know what this is in game)
Tree Saplings 22 remove
Unknown 1 remove
weed 52 remove
wool 15 remove
i think thats all of them

on a side note i can't get AD to load Digestate into a slurry container

**Comment by Anonymous-any** [comment]
Hi do you really think that some like Eggs, Bale could not be used with an appropriate trailer later ?
