### ISSUE TITLE
[Question] Does Multiple Target work with unload combine mode

### ISSUE THREAD

**Issue by krambc** [Stephan-S/FS19_AutoDrive#1811]
I've set multiple points in a field for the pickup as its a big field and i've some problems with de pathfinder.

I've enabled multiple targets for pickups and doesn't change.

The multiple target doesn't work with unload combine mode or is that i'm setting something brong?

**Comment by Axel32019** [comment]
Hello @krambc ,
In harvester unload mode it is not possible to set multiple pickup's.
You only may set multiple unload destinations.

**Comment by krambc** [comment]
Ok, thank you!

Enviat des del meu iPhone
