### ISSUE TITLE
[Question] Does AD have a mouseOverHud boolean?

### ISSUE THREAD

**Issue by Bobster82** [Stephan-S/FS19_AutoDrive#1813]
**Question:**   
Hello AD def team,
Do you have sort of a mouseOverHud boolean? 
The reason im asking is for the Courseplay option "ClickToSwitch". Many times when i want to click something in the AD menu, CP switches to the vehicle under the hud. I know CP checks if the mouse is over the hud.
I like to "give" CP the mouseOverHud from AD, so it wont switch to the vehicle if its under the hud.

**Comment by Axel32019** [comment]
Hello @Bobster82 ,
No, there is no sort of OverHUD. The only ways to avoid switch to vehicle are:
- deactivate switch to vehicle in CP
- move AD HUD to a position where most likely no vehicle is in the background

**Comment by Bobster82** [comment]
Thanks!
Then im going to make my own checks for it. Closing it now
