### ISSUE TITLE
Traffic stop

### ISSUE THREAD

**Issue by jobyrns72** [Stephan-S/FS19_AutoDrive#1817]
Hello I've noticed that traffic detection can be turned off in setting but even with turned off it still stops while close but not touching something. What I'm doing is my trailer has to get close to another trailer to overload into but tractor stops before being able to reach it. Thanks a lot!

**Comment by Axel32019** [comment]
Hello @jobyrns72 , Please provide some screenshots with collision view (F5) enabled.
If not yet enabled please change in game.xml:
`   <development>
        <controls>true</controls>
    </development>
`

**Comment by jobyrns72** [comment]
![fsScreen_2021_02_24_21_49_33](https://user-images.githubusercontent.com/4283225/109100413-6abb0b80-76ea-11eb-95e6-b68132c7c222.png)

**Comment by Axel32019** [comment]
There seem to be some yellow collis hit the vehicle - try to move your route away and try it.
