### ISSUE TITLE
[BUG] Game crashes when activating AD

### ISSUE THREAD

**Issue by krambc** [Stephan-S/FS19_AutoDrive#1819]
**AutoDrive Version:** 1.1.0.7   
**Release or Custom Zip:** Release
**Map (If applicable):** The Great Stump
**Vehicle / Type (If applicable):Any
**Multiplayer or Singleplayer:** Singleplayer  

I've been playing this map with AD for the last 6-8 months without problem. One week ago i've start having problems when activating AD. The game freezes and I've to restart the computer.

The game doesn't always freeze, but in the last few days when I want to drive to WP "Field 75" (for example) it crashes and I have to reset the computer.

I have tried removing all mods except the map and the Autodrive and it keeps crashing.

The log does not show any Autodrive errors ...
Maybe it's some problem with the Autodrive_config .....

attached both.

Thanks in advance.
[log.txt](https://github.com/Stephan-S/FS19_AutoDrive/files/6031938/log.txt)

[Autodrive_config.txt](https://github.com/Stephan-S/FS19_AutoDrive/files/6031944/Autodrive_config.txt)

**Comment by Axel32019** [comment]
Hello @krambc , There are some strange waypoint connections which cause an endless loop in path calculation.
No idea how this was possible to create, but look at your destination "Combi_pk" for instance. There are forward an backward connections at the same 2 waypoints. To see this you have to move 1 waypoint to see the colors for forward and reverse.
Anyhow will be prevented in next release.

**Comment by krambc** [comment]
Thank you for your answer! I'll fix it.

**Comment by krambc** [comment]
By the way, how can I find these "bad" points? Do I have to look point by point in the game? Is there a way to detect them in the xml?

**Comment by Axel32019** [comment]
You may try debug "Road Network", it will show roads with open ends in the map display. The destiation list will contain entries with only digits for this, which you can give a try to reach with a vehicle, but not 100% sure to find a way to it!

**Comment by krambc** [comment]
I've fixed all the open ends. When activating "Road Network" debug I don't have the debug folder, but the game still crashes sometimes. I don't know what else can I do to fix the problem....
[AutoDrive_config.txt](https://github.com/Stephan-S/FS19_AutoDrive/files/6056749/AutoDrive_config.txt)

**Comment by Axel32019** [comment]
Please try the beta Version, which will be the next release.

**Comment by krambc** [comment]
It works!!!! Tank U
