### ISSUE TITLE
xml Größenunterschied?

### ISSUE THREAD

**Issue by andreasthu** [Stephan-S/FS19_AutoDrive#182]
Hallo
ich habe mir mit autodrive nun schon für fast ganz Felsbrunn Strecken eingefahren.
nun hab ich den editor probiert, etwas geändert, gespeichert - und war überrascht.
meine ursprüngliche AD xml war etwa 4MB gros, die aus dem editor gespeicherte hatte nur 1/8el der originalen. schien aber alles da zu sein.
also hab ich die ursprüngliche datei nochmal mit dem editor geöffnet und OHNE ÄNDERUNG gespeichert, die Dateigrößenänderung war aber trotzdem dieselbe.

hier die datei aus dem savegame, ca 4,2MB:
[AutoDrive_my_Felsbrunn_MF_config.xml.txt](https://github.com/Stephan-S/FS19_AutoDrive/files/3243684/AutoDrive_my_Felsbrunn_MF_config.xml.txt)

und hier die gleiche Datei nach dem speichern im AD-Editor, 0,7MB: 
[AutoDrive_my_Felsbrunn_MF_config2.xml.txt](https://github.com/Stephan-S/FS19_AutoDrive/files/3243686/AutoDrive_my_Felsbrunn_MF_config2.xml.txt)

https://abload.de/img/unbenanntiljio.jpg
noch ein bild beider dateien in notepad++ mit der dateiinfo

lg
andreas

**Comment by Stephan-S** [comment]
Hi,

die großen Dateien kommen zustande, wenn du Zielpunkte hast, die nicht von jedem Punkt aus erreichbar sind.
Du hast hier also ein teilweise abgekoppeltes Steckennetz, das nicht korrekt verbunden ist.
Der Editor berechnet keine neuen Routen und wenn du die aus dem Editor geladene config nutzt, solltest du ingame die Strecken neu berechnen lassen.

Hier ein kleiner Ausschnitt aus der großen Config:
<markerID>2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,-1,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2; ...

Das ist die Weginformation für Knoten 1 zu jedem Zielpunkt. Mit Komma getrennt, Das Semikolon ist hier das Ende für Knoten 1 und danach geht Knoten 2 weiter.
Wie du siehst, ist die Information sehr redundant. Aber da hier ein Wegpunkt (mm35) nicht erreichbar ist, muss es so abgelegt werden.
Und hier die config, die der Editor erzeugt:
<markerID>=,2;
was soviel heißt wie alle Wegpunkte sind von Knoten 1 aus erreichbar indem zuerst Knoten 2 angefahren wird.
Also quasi eine Komprimierung der Informationen. 
Und die zwei Dateien die du hier hochgeladen hast, stimmen auch nicht überein. Daher kann ich nicht ganz nachvollziehen warum der Editor die Informationen zusammenfassen kann, die ingame funktion aber nicht.

Aber ich hoffe du verstehst zumindest warum große Dateien erzeugt werden und was man dagegen tun kann (Alle punkte korrekt verbinden).

Beste Grüße,
Stephan

**Comment by andreasthu** [comment]
ok, danke
der Editor, ist mir aufgefallen, sortiert die Zielpunkte wieder nach der id-nummer, 
ich hatte sie mir damals ja wegen der reihenfolge in der xml geändert.
daher sind i nden beiden dateien die <mm> nicht in derselben reihenfolge.
aber ja, nach laden und speichern des spielstandes ist die datei wieder 4,3mb groß
hab mir nur gedacht, wieso der große unterschied zustandekommt, oder der editor ev. etwas "vergisst"
aber danke, alles ok
lg
andreas

**Comment by Stephan-S** [comment]
Ah, okay.
dann sollte ich trotzdem nochmal beim Editor drüber schauen, das er die Reihenfolge nicht durcheinander bringt, sorry dafür.

**Comment by Bandesss** [comment]
Ja hatte ich ich auch alles der Reihe nach angefahren nun ist alles durcheinander. Könntest du uns bitte ein Beispiel zeigen, wie wir es in der XML wieder ändern können?

**Comment by Stephan-S** [comment]
![changeMM](https://user-images.githubusercontent.com/5493976/58749884-a67c5f00-848b-11e9-9a54-821028c87a71.PNG)

Und danach ingame neu berechnen lassen :-)

**Comment by Bandesss** [comment]
Das heißt ich brauch nur die Punkte bei mm und /mm ändern und dann passt es wieder ?vielen danke klasse.

**Comment by Stephan-S** [comment]
@Bandesss 
Das hat mit SP/MP nichts zu tun. Du hast vermutlich in der Zwischenzeit AD aktualisiert und dort habe ich alphabetische Sortierung eingebaut.
Wenn du dir aus den aktuellen Sourcen eine .zip File machst, berücksichtigt die Sortierung auch Zahlen korrekt. Also 13 nach 2 und nicht hinter der 1

**Comment by Bandesss** [comment]
Aso ja, ist gut jeden Tag Updates sehr schön.
Also müsste er das selber sortieren ?
1,2,3 und so?

**Comment by Stephan-S** [comment]
Close
