### ISSUE TITLE
Paramètre de véhicules

### ISSUE THREAD

**Issue by PapyFaitMumuse** [Stephan-S/FS19_AutoDrive#1821]
Bonjour à tous,
Version 1.1.07 utilisée.

Dans les paramètres de véhicules ne s'enregistrent pas. Si je modifie les paramètres , je clique sur "Appliquer". Là pas de soucis les paramètres sont bien enregistrer. Par contre lors de la relance de Farming les modifications n'apparaissent pas. Il faut tout recommencer......

**Comment by Iwan1803** [comment]
SP, hosted MP or dedi server? Which map? Write protection on files? Log file?
Some more informations would be nice...

**Comment by Axel32019** [comment]
no information -> closed.
