### ISSUE TITLE
[Question] click on HUD activates vehicle behind it

### ISSUE THREAD

**Issue by PapyFaitMumuse** [Stephan-S/FS19_AutoDrive#1822]
Bonjour à tous,

Je rencontre un problème avec la transparence du HUD. Lorsque je clique sur une fonction ou d'une sélection de trajet, cela clique aussi sur le ou les objet en arrière plan. Si c'est un véhicule on va dessus. Si c'est un point de tracer , cela le sélection et on peut modifier un trajet sans se rendre compte de la modification.

**Comment by Iwan1803** [comment]
In the meantime, I have also heard this from someone else. So far, however, I have not been able to reproduce the problem.
I suspect that another mod is responsible for this, but without sufficient info and the log....

**Comment by crcarmichael** [comment]
This is the "click to switch" feature in Courseplay.  It can be turned if in the CP settings.

It would be helpful, though, if the AD HUD could be "clicked through".

**Comment by Ralf254** [comment]
Habe das Problem mit dem HUD auch. Befindet sich ein Fahrzeug "hinter" dem HUD, wir dieses beim Klick auf den HUD ausgewählt. Gibt es eine Lösung für dieses Problem?

**Comment by haamic** [comment]
Steht doch hier schon drin. 
In CP Einstellung "klick zum einsteigen" deaktivieren
