### ISSUE TITLE
[BUG] parking place dont save in savegame. Nach den laden vom Savegame sind wieder alle zugewiesenen Parkpositionen weg

### ISSUE THREAD

**Issue by FritzHugo3** [Stephan-S/FS19_AutoDrive#1823]
AutoDrive Version: aktueller Release
Karte (falls relevant): unterschieldiche
Fahrzeug(art) (falls relevant): alle

**Beschreibe den Bug**
[BUG] parking place dont save in savegame sometimes. Nach den laden vom Savegame sind manche zugewiesenen Parkpositionen weg. Ich weiß niccht ob es mit dem ähnlichen Phänomen von Coursdeplay zu tun hat, hier werden mal die Kurse nach dem laden weiter genommen und manchmal sind die alle verschwunden. Ich konnte nicht herausfinden, mit was es zusammen hängen könnte.

**Comment by 60erjonny** [comment]
Hallo

Prüfe bitte nach, ob du auch wirklich für alle ( Traktoren, Drescher und aber auch Anbaugeräte wie Pflug, Düngerstreuer Sähmaschine usw. ) eine Parkplatz zuggewiesen hast. Denn wenn du an einem Traktor mit Parkplatz einen Wender ohne Parkplatz anhängst, dann erkennt AD das aktivierte Gerät keine Parkplatz hat...

**Comment by FritzHugo3** [comment]
Anbaugeräte haben/brauchen nen Parkplatz? Sollte das angehngte Werkzeug nicht egal sein beim parken? Ich wechsel natürlich ständig irgendwelche Anbauten.

**Comment by 60erjonny** [comment]
Hallo

Nun brauchen oder nicht, du kannst ihnen einen Parkplatz zuweisen, um dieses Werkzeug so aufzuräumen...:-)
Ist glaube ich ab 1.1.0.6 Release möglich...https://github.com/Stephan-S/FS19_AutoDrive/wiki/Release-Notes

**Comment by FritzHugo3** [comment]
Ok, dann werd ich mal drauf achten und werde mich dann ggf. wieder hier melden. 
Danke dir erst Mal. 

(Weißt du ob man das deaktivieren kann mit den Geräten? Für mich fährt in meiner Logik immer nur das Fahrzeug, was dann parkt, egal was drann hängt. Steht das in ner config?)

**Comment by 60erjonny** [comment]
Hi

Deaktivieren, weiß nicht...
Logik, nun das sehe ich schon so...bei dir hat ja wohl das Gerät nicht den selben Platz wie der Traktor...
Ich habe nur bleibende Gespanne im LS 19 und die haben bei mir beide den selben Parkplatz.

**Comment by Bobster82** [comment]
Both vehicle and attachement can have a parking spot. If you press park, the parking destination is "the selected tool or vehicle" 
Fs19 has a "bug" that you can select all vehicles (some can) so when u have, for example, a seeder attached, the parking spot most likely is from the seeder (if that doesnt has a parkingspot, you cant press that button)

**Comment by TobiHH78** [comment]
> Ok, dann werd ich mal drauf achten und werde mich dann ggf. wieder hier melden.
> Danke dir erst Mal.
> 
> (Weißt du ob man das deaktivieren kann mit den Geräten? Für mich fährt in meiner Logik immer nur das Fahrzeug, was dann parkt, egal was drann hängt. Steht das in ner config?)

Das ist ja das schöne. Du kannst sowohl dem Traktor wie auch dem jeweiligen Anbaugerät einen Parkplatz zuweisen.
Je nachdem, was mit "G" ausgewählt ist, kannst du den Traktor entweder zu seiner zugewiesenen Position schicken, oder wenn das Anbaugerät ausgewählt ist, fährt der Traktor zur Parkposition des Anbaugeräts.

**Comment by FritzHugo3** [comment]
Na ja, ich bräuchte es nicht. Ich knall die Geräte dahin, wo grad Platz is grins. Na ja, muss ich dann damit leben, jedesmal zu schauen, was ausgewählt ist. Dann danke ich euch mal.
