### ISSUE TITLE
[BUG] Issue with the HoT_Transport System unloading a Harvester

### ISSUE THREAD

**Issue by Beondal** [Stephan-S/FS19_AutoDrive#1827]
AutoDrive Version: 1.1.0.8
Release or selbsterstelltes zip: Release
Karte (falls relevant): HoF21 (HoT Online F4rm 2k21)
Fahrzeug(art) (falls relevant): Wechselbrücken aus dem karteneigenen Transportsystem

Hallo, zuerst ein paar Vorabinfos: Ich bin seit einiger Zeit selbst Teil des HoT Teams. Da wir auf unserem Server kein AD,CP oder dergleichen benutzen, wurde unsere Karte nie gezielt für diese Art von Helfer optimiert. Ich selbst spiele die Karte jedoch auch sehr oft im Single Player und verwende dort AD/CP, was grundsätzlich auch problemlos funktioniert. Seit ich im Team bin versuche ich daher ua auch so gut es geht Support für AD Probleme auf unserer Karte anzubieten.
Bislang konnte ich auch für jedes "Problem" zumindest die Ursache finden und wenigstens einen Workaround anbieten. Zur Not auch mal ein "Sry, das liegt an xyz und wird nicht geändert". 
Nun aber zum Eigentlichen, denn ich stehe nun vor einer vermeintlichen Inkompatibilität für die ich keine genaue Ursache finden kann. Da ich Willi bereits vorher aus dem Discord kannte, hab ich mich zuerst an ihn gewandt und er hatte mich gebeten hier dazu ein Issue zu eröffnen und hier bin ich.

**Beschreibe den Bug**
Beschrieben ist das Ganze recht einfach: Courseplay steuert den Drescher auf einem beliebigen Feld mit beliebiger Frucht (--> Art des Schneidwerks/Dreschermodell egal). AD soll den Drescher abtanken. Problem tritt auf, sobald dafür der LKW bzw der Anhänger (Tandem) aus unserem Transportsystem zusammen mit einer der dazu gehörenden Wechselbrücken (ebenfalls aus dem Transport System) genutzt wird. 

**Falls anwendbar - Schritte mit denen ich den Bug nachstellen kann**

Abtanken läuft wie folgt:
Drescher ruft den Abfahrer; Abfahrer fährt zum Drescher und wird beladen. Bis hierhin alles einwandfrei. Sobald das Abladen beendet ist sollte der Abfahrer in den Task "zurücksetzen vom Drescher" wechseln. Laut Anzeige im AD HUD bzw. auch laut Debug-Info, tut er das auch. Das Fahrzeug bewegt sich jedoch nicht und verbleibt im Status "zurücksetzen vom Drescher". Wäre grundsätzlich nicht schlimm, solang der Abfahrer den Drescher nicht beim weiterfahren blockiert. Allerdings wird der Task auch nach einiger Zeit nicht gecanceld, sodass er Abfahrer nicht auf den nächsten Drescher Ruf reagieren kann, weil er noch im anderen Task festhängt.
Soweit ich das testen konnte lässt sich das nur auf 2 Arten lösen --> 1.) AD beim Abfahrer aus-/einschalten; 2.) CP beim Drescher aus-/einschalten (also sobald CP im Drescher deaktiviert wird, springt AD in den Task "auf Ruf warten")
Soweit ich das noch in Erinnerung habe, gab es ein ähnliches Problem in Version 1.1.0.4 oder einem 5er RC in Verbindung mit VCA (da passierte ähnliches beim Zurücksetzen wenn VCA aktiv war und AD rückwärts fahren wollte, auch mit Vanilla Fahrzeugen).
Kollisionserkennung, VCA und andere gängige Verdächtige konnte ich als Fehlerquelle ausschließen. Der letzte Test fand nur mit den Mods die unsere Map zwingend erfordert + AD + CP statt. 
Ich denke, dass es an den Wechselbrücken liegt (Nimmt man den LKW aus unserem Transportsystem ohne Wechselbrücke und hängt hinten einen Vanilla Anhänger dran, funktioniert alles einwandfrei). Ich hab in diversen .xml's nach entscheidenden Unterschieden gesucht und mit den Wechselbrücken verglichen, konnte aber nichts finden das eventuell die Ursache ist. Auch in den AD Scripten habe ich nach Anhaltspunkten gesucht was ggf bei den Wechselbrücken fehlen könnte. Da ich aber nun kein Scripter bin, konnte ich dort mit meinem allenfalls Basiswissen nichts finden, dass mir weiterhilft.

Abschließend noch 1 Sache: Ich weiß natürlich, dass es nicht eure Aufgabe ist andere Mods mit AD kompatibel zu machen und das will ich natürlich auch gar nicht von euch verlangen. Meine Bitte ist im Grunde hauptsächlich, mir zu helfen die genaue Ursache für dieses Verhalten zu finden, sodass ich das Ganze (soweit meinerseits möglich) kompatibel machen kann.

Falls ihr eine Log von meinen Tests haben wollt kann ich diese noch nachreichen. Da kürzlich AD Version 1.1.0.8 rauskam, hab ich spontan nochmal damit getestet allerdings mit teils falschem Modset (kann ich noch nicht spoilern).
Also falls nötig bau ich mir nochmal die öffentlichen Versionen zusammen und schick eine Log. Ich denke aber nicht, dass es damit zu tun hat, denn ursprünglich aufmerksam gemacht wurde ich auf diese Sache von einem User in unserem Forum, der keinen Zugang zu internen Modversionen hat.
Die Karte und dazu gehöhrende/notwendige Mods sind natürlich auf unserer Seite [http://hot-hq.de/](url) zu finden.
Natürlich werd ich in nächster Zeit immer wieder mal hier rein schauen, aber ansonst bin ich auch in diversen Discords (auch AD-Discord) zu erreichen falls noch fragen offen sind.

**Comment by Iwan1803** [comment]
In Kurzfassung:
mit einer Wechselbrücke auf einem Anhänger fährt er nicht zurück, mit einem Vanilla-Anhänger schon?
Kannst du mit der Wechselbrücke per AD überhaupt rückwärts fahren, also z.Bsp. rückwärts in eine Halle einparken lassen?

Mir ist in 1.1.0.8 heute nur aufgefallen, das er manchmal nicht weit genug zurückfährt und der CP-Drescher dann nicht aus seiner Abladebucht raus kann bzw. beide kollidieren.

**Comment by Beondal** [comment]
Ja das hatte ich vergessen, rückwärts fahren (hellblaue Linie) funktioniert sonst einwandfrei.

Ansonst ja. Sobald eine Wechselbrücke im Spiel ist (in welcher Form auch immer) wechselt er den Modus nicht.
Die Kollision die du meinst wäre ansich nur im Vorgewende ein Problem. Aber da er den Modus nicht wechselt, reagiert er auch nicht mehr auf den nächsten Ruf (außer man greift selbst ein, was ja nicht Sinn der Sache ist).
Und ja sry ich glaub der ganze Post ist etwas zu lang geworden.

**Comment by rgoe** [comment]
Ist schon eine Zeit her, aber da hatte ich ein ähnliches Problem mit einem Wechselbrücken-mod, in meinem Fall war es das "Trucks and AR Frames Pack" von Modsby5nine. Das Problem war  - soweit ich es nachvollziehen kann - im wesentlichen folgendes: 
Beim Zurücksetzen vom Drescher nutzt AD eine rückwärtigen Collision-Trigger/Sensor, dessen Position AD anhand der Fahrzeuglänge aus der Fahrzeug-XML berechnet (in VirtualSensors.lua, Funktion ADSensor:getLocationByPosition). Dazu nimmt AD die Hälfte der Länge des Fahrzeugs als Z-Koordinate (location.z = - vehicle.sizeLength / 2) - da bei den meisten Fahrzeugen 0/0/0 in der Fahrzeug-/Mod-Mitte liegt, ist der Sensor somit am Heck positioniert.
Bei euren Wechselnbrücken und bei denen aus dem o.g. Pack liegt 0/0/0 jedoch nicht in der Mitte sondern ziemlich weit vorn, so dass die Berechnung von AD für die Sensorposition mitten im Fahrzeug landet und der Sensor quasi das eigene Fahrzeug als Hindernis detektiert - somit AD nicht losfährt. Im Screenshot ist das rote Rechteck mitten in der Ladefläche der rückwärtige Sensor von AD.

![fsScreen_2021_03_05_00_59_37](https://user-images.githubusercontent.com/21224499/110048001-37fabe00-7d4f-11eb-830f-e53edeeaf048.png)

Hoffe, das war verständlich und hilft euch ggf. das Problem in den Griff zu bekommen. Da mir damals der Umbau des Mods zu kopliziert war, hatte ich für mich einfach die AD-Funktion modifiziert und ein if-statement eingefügt, dass bei dem betreffenden mod (vehicle.name="XXX") die Z-Position des Sensors = (-)Fahrzeuglänge setzt.

**Comment by Beondal** [comment]
Ob's im Endeffekt funktioniert kann ich zwar jetzt nicht sagen, aber vielen Dank für den Hinweis.
Zumindest Mal etwas wo ich die nächsten Tage Mal ansetzen kann.

**Comment by Beondal** [comment]
So, ich hab inzwischen etwas experimentiert. Die einfachste Lösung auf meiner Seite ist ... in der xml der Wechselbrücken den length Wert solange erhöhen bis die Sensorposition dann tatsächlich hinter dem Fahrzeug liegt.
Was ich allerdings bisher noch nicht harausfinden konnte ist, wo dieser Wert in der xml eigentlich herkommt (oder ob er willkürlich ist) und inwiefern sich eine Veränderung auf andere Bereiche des Spiels auswirkt.
Für die Wechselbrücke ansich war bzw ist es so ... Der LKW hat eine length Wert von 11. Die Wechselbrücke hat 7. Der Punkt, der bei der Wechselbrücke laut GE die Mitte ist liegt soweit vorne damit sie mit dem Mittelpunkt des LKW übereinstimmt wenn verbunden. Setzte ich nun die Länge der Wechselbrücke in der xml Info auf 11 (also gleich wie der LKW) dann funktioniert es weil der Sensor dann hinter dem LKW ist.

Inwieweit das nun für das AD Team eine Hilfe ist kann ich nicht sagen, im Grunde kann ich das Problem so lösen (sofern es keine Auswirkung auf andere Dinge des Spiels hat).
Bzgl AD kann ich in diesem Zusammenhang nur den Vorschlag bringen: AD müsste sich für den Fall, dass derartige Wechselbrücken im Einsatz sind, die Länge des Fahrzeugs (bzw des Anhängers wo die Wechselbrücke drauf soll) holen. Da aber die Wechselbrücke laut xml auch als Trailer zählt, greift AD vermutlich auf die xml der Wechselbrücke zu statt auf die xml des Fahrzeugs oder des Tandems.
Um der Frage "Und wie stellst du dir das vor" vorzubeugen ... Weiß ich leider nicht da ich keine Ahnung hab was Script-technisch alles machbar ist. Das sind nur meine 2 cent wie es Ad-seitig funktionieren könnte :)

**Comment by Axel32019** [comment]
Danke @rgoe für den Hinweis!
Hallo @Beondal,
Da die meisten Fahrzeuge, Anhänger, Anbauten etc. von der Mitte weg konstruiert sind, verwendet AD und möglicherweise auch andere mods sizeLength / 2 zur Bestimmung wo etwas zu Ende ist.
AD verwendet diesen Wert für Sensoren vorn und hinten, ausgehend natürlich vom "Nullpunkt" -> @rgoe Richtig erkannt!
Der Wert der Länge steht in der XML: `<size width="3.00" length="7.1"/>` und sollte mit den Dimensionen in der i3d zusammenpassen.
Er wird für viele Berechnungen verwendet. Eine Änderung der Länge kann also negative Auswirkungen an anderer Stelle haben.
Die Wechselbrücken werden als semitrailer angekoppelt und somit als Anhänger angesehen. Eine Erkennung als "Wechselbrücke" in AD halte ich für zu fehleranfällig.
Die Wechselbrücken anzupassen halte ich für zukunftsicherer:
Habe leider nur die Version 2.0.0.1, sollte jedoch auch für aktuellere gelten:
Beispielhaft für HoT_WBK.i3d
Die Z-Verschiebungen ändern:
name="attacherJoint" translation="0 1.464 0" -> name="attacherJoint" translation="0 1.464 1.4"
name="support" translation="0 0.2 -1.421" -> name="support" translation="0 0.2 0" 
name="supportcollis" translation="-0.004 1.58 -1.416" -> name="supportcollis" translation="-0.004 1.58 0"
name="Aufbau" translation="0 1.584 -1.423" -> name="Aufbau" translation="0 1.584 0"
Dann sollte alles funktionieren.
Ich hoffe das hilft Dir/Euch weiter.
Gruß Axel

**Comment by Beondal** [comment]
So endlich komm ich dazu nochmal zu antworten.
Danke @Axel32019 auch für deine Rückmeldung. Nachdem mich rgoe erleuchtet hat wo der relevante Punkt im Script ist war mir sofort klar, dass es an den verschobenen Z Werten liegt. Leider lässt sich das Modintern nicht so leicht beheben ohne das wir andere Dinge auch ändern müssten (genaueres müsste der Chef erklären, spielt aber keine Rolle). Jedenfalls haben wir beschlossen im LS19 nichts mehr daran zu verändern. GgF werde ich bei Anfragen aber auf dieses Issue verweisen, dann kann jeder selbst entscheiden ob er etwas verändern will.
Trotzdem Danke an alle, Ziel war es die Problematik zu verstehen bzw die Ursache zu kennen, was nun der Fall ist.

P.S.: Die Lösung mit der Länge ist zwar Pfusch (darum bauen wir es auch nicht fix ein), aber sie funktioniert in diesem Fall ohne negative Auswirkungen weil es durch die Änderung eben ident mit den Abmessungen des LKW ist. Daher auch kein Einfluss auf andere AD Abfragen (soweit ich gesehen hab). Nur der Spawn am Shop sieht danach etwas komisch aus.

**Comment by Axel32019** [comment]
Sehe hier somit keinen weiteren Handlungsbedarf für AD -> closed
