### ISSUE TITLE
Parkposition zuweisen

### ISSUE THREAD

**Issue by Dera351** [Stephan-S/FS19_AutoDrive#1828]
Ich habe von v -07 auf v -08 upgedatet in v08 kann ich keine Paprkposition mehr zuweisen. Mit STRGL + re Maustaste (wie bei den Releasenotes beschrieben) auch nicht.
Habe v -07 wieder installiert und es klappt.
Hat noch jemand dieses Problem oder kennt jemand die Lösung dafür?

danke

**Comment by andreasthu** [comment]
ALT + re.Maustaste funktioniert bei mir.#denke da ist ein fehler in der releasenote.
lg
andreas

**Comment by Axel32019** [comment]
Bitte Release-Notes beachten: https://github.com/Stephan-S/FS19_AutoDrive/wiki/Release-Notes

**Comment by Dera351** [comment]
@Axel32019
Du hast ja so Recht!! Es klappt nur im EDIT-MODUS.

danke dir

**Comment by DaObabayer** [comment]
Also ich hab nun alles mögliche versucht und schaffe es nicht mehr eine Parkposition zuzuweisen seit der 1.1.0.8er Version.
Liegts evtl. daran das es ein Dedicated Server ist?

**Comment by KarlGutenberg** [comment]
Blöd ist nur, wenn ich

Editormode (red bubbles) + LCTRL + right-mouse on P -> set/override P with 1st destination in HUD
Editormode (red bubbles) + LALT + right-mouse on P -> delete assigned parking space

gedrückt habe, habe ich auch gleichzeitig den 1 Aufnahmepunkt (red bubbles) gesetzt!
den ich dann wieder löschen muss!

**Comment by Axel32019** [comment]
@KarlGutenberg Das kann zumindest ich nicht nachvollziehen. Der Aufnahmepunkt wird nur mit LCTRL + linke Maustaste gesetzt.
Bist Du sicher das Du das mit der rechten Maustaste hinbekommst? Doppelbelegung geprüft?
An alle: Die dedi-Problematik ist gefixt und wird im nächsten Release drin sein.

**Comment by KarlGutenberg** [comment]
Nur mit der linken Maustaste wird aufgenommen!
Oder was meinest du mit Aufnahmepunkt?

Axel32019 ***@***.***> schrieb am Mo. 26. Apr. 2021 um 15:21:

**Comment by KarlGutenberg** [comment]
@Stephan kannst du mir mal sagen, was du mit Aufnahmepunkt meinst?
mit LCTRL + linke Maustaste habe ich keine Funktion
was soll aufgenommen werden?
Gruß

Am Mo., 26. Apr. 2021 um 15:31 Uhr schrieb Karl Gutenberg <
***@***.***>:

**Comment by Axel32019** [comment]
> 
> 
> Blöd ist nur, wenn ich
> 
> Editormode (red bubbles) + LCTRL + right-mouse on P -> set/override P with 1st destination in HUD
> Editormode (red bubbles) + LALT + right-mouse on P -> delete assigned parking space
> 
> gedrückt habe, habe ich auch gleichzeitig den 1 Aufnahmepunkt (red bubbles) gesetzt!
> den ich dann wieder löschen muss!

Hallo @KarlGutenberg , Wird nun ein Aufnahmepunkt gesetzt oder nicht - bin jetzt verwirrt.

**Comment by KarlGutenberg** [comment]
Hallo!
Hat sich wieder was geändert hinsichtlich Parkposition zuweisen?
v. 1.1.1.1 RC1
ich kann meine Fahrzeuge nicht mehr Parken trotz
Editormode (red bubbles) + LCTRL + right-mouse on P -> set/override P with 1st destination in HUD
Editormode (red bubbles) + LALT + right-mouse on P -> delete assigned parking space

Gibt es da wieder neue Einstellungen?
Für Hilfe wehre ich dankbar!

**Comment by Stephan-S** [comment]
Da hatte sich glaube ich kurz ein Fehler eingeschlichen, der aber in den nächsten RCs schon behoben ist.
