### ISSUE TITLE
Hello how can I import or export courses. Were i have to do the courses to import? (AutoDrive_NF_Marsch_4fach_V2_4_config)

### ISSUE THREAD

**Issue by elkra54** [Stephan-S/FS19_AutoDrive#1829]
**Is your feature request related to a problem? Please describe.**  

**Describe the solution you'd like**  

**Describe alternatives you've considered**  

**Additional context**

**Comment by 60erjonny** [comment]
https://github.com/Stephan-S/FS19_AutoDrive/issues/1684#issue-751585159

**Comment by elkra54** [comment]
When I did that, then the courses weren't shown in the Autodrive HUD. How can I make that they show.

**Comment by Iwan1803** [comment]
If you did it as described in the linked instruction, it would work.
Don't edit or rename the config file (except the version of the NFM map in the file name and at 2 positions inside).

**Comment by elkra54** [comment]
Thanks 👍👍
