### ISSUE TITLE
[BUG]Parking Issue

### ISSUE THREAD

**Issue by mzaliac14** [Stephan-S/FS19_AutoDrive#1834]
**AutoDrive Version:** 1.1.x.x   
**Release or Custom Zip:** Release  
**Map (If applicable):** All  
**Vehicle / Type (If applicable):**   
**Multiplayer or Singleplayer:** Singleplayer  

**Describe the bug**  
I updated to the latest version and after that I'm unable to set up a parking point. Even after right clicking nothing happens. It just doesn't set the parking spot

**If applicable - Steps to reproduce the behavior**  

**Screenshots**

**Comment by TobiHH78** [comment]
https://github.com/Stephan-S/FS19_AutoDrive/issues/1828#issuecomment-789214006

ADDED: remove assigned parking space:
Editormode (red bubbles) + LCTRL + right-mouse on P -> set/override P with 1st destination in HUD
Editormode (red bubbles) + LALT + right-mouse on P -> delete assigned parking space

**Comment by mzaliac14** [comment]
Thank you. It works. Yay!!

**Comment by KarlGutenberg** [comment]
Blöd ist nur, wenn ich
Editormode (red bubbles) + LCTRL + right-mouse on P -> set/override P with 1st destination in HUD
Editormode (red bubbles) + LALT + right-mouse on P -> delete assigned parking space

drücke habe, habe ich auch gleichzeitig den 1 Aufnahmepunkt (red bubbles) gesetzt!
den ich dann wieder löschen muss!
