### ISSUE TITLE
не отображается в подсказках ф1 длина распила лесозаготовительной техники [Question]

### ISSUE THREAD

**Issue by kapatyh** [Stephan-S/FS19_AutoDrive#1837]
**Question:**   
I've got a question...

**Comment by haamic** [comment]
Кажется, я помню, что длина пилы отображается только тогда, когда я нахожусь внутри кабины, а не снаружи автомобиля. Однако, похоже, что это не является проблемой для Autodrive. Пожалуйста, проверьте.

Пожалуйста, пишите по-немецки или по-английски, спасибо.

--------

Ich meine mich zu erinnern, dass die Sägelänge nur angezeigt wird, wenn ich mich innen in der Cockpit Ansicht befinde und nicht in der Aussenansicht des Fahrzeuges. Dies scheint jedoch kein Problem mit Autodrive zu sein. Bitte prüfen.

**Comment by kapatyh** [comment]
> Кажется, я помню, что длина пилы отображается только тогда, когда я нахожусь внутри кабины, а не снаружи автомобиля. Однако, похоже, что это не является проблемой для Autodrive. Пожалуйста, проверьте.
> 
> Пожалуйста, пишите по-немецки или по-английски, спасибо.
> 
> Ich meine mich zu erinnern, dass die Sägelänge nur angezeigt wird, wenn ich mich innen in der Cockpit Ansicht befinde und nicht in der Aussenansicht des Fahrzeuges. Dies scheint jedoch kein Problem mit Autodrive zu sein. Bitte prüfen.

alas it's about the auto drive

**Comment by kapatyh** [comment]
> > Кажется, я помню, что длина пилы отображается только тогда, когда я нахожусь внутри кабины, а не снаружи автомобиля. Однако, похоже, что это не является проблемой для Autodrive. Пожалуйста, проверьте.
> > Пожалуйста, пишите по-немецки или по-английски, спасибо.
> > Ich meine mich zu erinnern, dass die Sägelänge nur angezeigt wird, wenn ich mich innen in der Cockpit Ansicht befinde und nicht in der Aussenansicht des Fahrzeuges. Dies scheint jedoch kein Problem mit Autodrive zu sein. Bitte prüfen.
> 
> увы все дело в автоприводе



> Кажется, я помню, что длина пилы отображается только тогда, когда я нахожусь внутри кабины, а не снаружи автомобиля. Однако, похоже, что это не является проблемой для Autodrive. Пожалуйста, проверьте.
> 
> Пожалуйста, пишите по-немецки или по-английски, спасибо.
> 
> Ich meine mich zu erinnern, dass die Sägelänge nur angezeigt wird, wenn ich mich innen in der Cockpit Ansicht befinde und nicht in der Aussenansicht des Fahrzeuges. Dies scheint jedoch kein Problem mit Autodrive zu sein. Bitte prüfen.

the length of the saw was displayed in f1 outside the cab
