### ISSUE TITLE
Aufladen an unerlaubten stellen

### ISSUE THREAD

**Issue by Dragonfly1982** [Stephan-S/FS19_AutoDrive#1838]
AutoDrive Version: 1.1.0.8
Release or selbsterstelltes zip: Release
Karte (falls relevant): Altkirsch im Elsass v2
Fahrzeug(art) (falls relevant):

Nach Aktualisierung von Version .0.7 auf Version .0.8 Laden Fahrzeuge, im Modus Abholen und Abliefern, an nicht erlaubten stellen.
 
Sobald als Ziel ein Belade-Wegpunkt eingestellt ist füllt er am erstbesten Trigger, den er auf der Route passiert und der dieses Produkt bietet, auf unabhängig ob es einen AD Ladepunkt hat oder nicht. Wenn der Trigger für Kauf und Verkauf am selben Punkt ist, füllt er sich direkt wieder auf. Auch bei eigenen Silos auf dem Hof die so einen Trigger haben.

**Falls anwendbar - Schritte mit denen ich den Bug nachstellen kann**

**Screenshots**
Falls relevant, bitte Screenshots beifügen

**Comment by 60erjonny** [comment]
Hallo

Was ist bei dir aktuell bei "maximaler Siloabstand" eingestellt ?

**Comment by Dragonfly1982** [comment]
Aktueller Siloabstand 25 bei der .0.7 hat es mit diesem Wert funktioniert

**Comment by 60erjonny** [comment]
Hallo

Nun versuch noch weiter runter zu gehen...

**Comment by 19BlueDragon83** [comment]
> Hallo
> 
> Nun versuch noch weiter runter zu gehen...

Das hat nix mit dem Siloabstand zu tun. Da kannst du noch so weit runtergehen wie du willst das bringt nichts. Habe das gleiche Problem an einer Stelle wo der Entladetrigger unter dem Beladetrigger ist. Erst entlädt er und dann lädt er es wieder auf. Das Problem ist seit die 8 Version raus gekommen ist.

**Comment by Axel32019** [comment]
@19BlueDragon83 @Dragonfly1982  Bitte mal mit der beta-Version probieren, da sind Anpassungen zum Be- und Entladen drin

**Comment by 19BlueDragon83** [comment]
> @19BlueDragon83 @Dragonfly1982 Bitte mal mit der beta-Version probieren, da sind Anpassungen zum Be- und Entladen drin

Geht wieder danke

**Comment by Axel32019** [comment]
Dann mach ich hier mal zu.
