### ISSUE TITLE
[BUG]Cannot call auto drive

### ISSUE THREAD

**Issue by torty42** [Stephan-S/FS19_AutoDrive#1839]
AutoDrive Version: 1.1.0.7
Release or selbsterstelltes zip: Release
Karte (falls relevant):Kernstadt
Fahrzeug(art) (falls relevant):

**Beschreibe den Bug**
Also normaler weisse Ruf ich den autodrive ja über alt+0 auf das funktioniert aber auf der karte nicht 

**Falls anwendbar - Schritte mit denen ich den Bug nachstellen kann**

**Screenshots**
Falls relevant, bitte Screenshots beifügen

**Comment by torty42** [comment]
[autodrive config.txt](https://github.com/Stephan-S/FS19_AutoDrive/files/6118580/autodrive.config.txt)
[log.txt](https://github.com/Stephan-S/FS19_AutoDrive/files/6118597/log.txt)


bitte

**Comment by Axel32019** [comment]
Hallo @torty42 , Du hast AD zwar im mod Ordner, aber nicht für den Spielstand aktiviert -> Häkchen setzen...

**Comment by torty42** [comment]
[log.txt](https://github.com/Stephan-S/FS19_AutoDrive/files/6121089/log.txt)


die aktuelsierte log auto drive is akteviert kann es aber immer noch nicht öffnen

**Comment by Axel32019** [comment]
Bitte Mehrfachbelegung der Tastenkombination prüfen.

**Comment by Axel32019** [comment]
Keine neuen Infos -> closed
