### ISSUE TITLE
Multiplayer Kurse

### ISSUE THREAD

**Issue by Bandesss** [Stephan-S/FS19_AutoDrive#184]
Hallo habe alle Kurse für die Bergmann Map eingefahren im Singel Player, nun wollte ich Sie auf meinen Server kopiern.
Die Punkte werden angezeigt in der Liste, aber keine Striche vorhanden auf der Strasse?
Was habe ich falsch gemacht ?
Gruss Bandes
[AutoDrive_HOF_BERGMANN_config.zip](https://github.com/Stephan-S/FS19_AutoDrive/files/3243757/AutoDrive_HOF_BERGMANN_config.zip)

**Comment by Stephan-S** [comment]
hast du eine Minute gewartet?
Die Kurse werden synchronisiert wenn du auf den Server gehst, das kann je nach Größe des Netzes ca 1 Minute dauern. Dann sollte alles angezeigt werden

**Comment by Bandesss** [comment]
ja habe länger gewartet als eine Minute, wie gesagt im sp eingefahren und ins Save game kopiert.
Es kommt keine Striche nichts...

**Comment by Stephan-S** [comment]
hm,
kannst du mir die log schicken? Vom server und von dir wenn du joinst?

**Comment by Bandesss** [comment]
Ja kann ich machen
[log.zip](https://github.com/Stephan-S/FS19_AutoDrive/files/3243779/log.zip)

**Comment by Stephan-S** [comment]
Wo hast du die config auf dem Server denn abgelegt?
Und schick mir doch bitte die komplette log vom Server.
Hier ist nur zu sehen das du anscheinen probierst Kurse zu 'importieren', es aber diese Datei gar nicht gibt

**Comment by Bandesss** [comment]
[url=https://abload.de/image.php?img=1eujof.jpg][img]https://abload.de/thumb/1eujof.jpg[/img][/url]
[log.zip](https://github.com/Stephan-S/FS19_AutoDrive/files/3243791/log.zip)
Hoffe du hast was du brauchs?

**Comment by Stephan-S** [comment]
Also so wie es aussieht hat er es um 15:12 ja geschafft die config zu laden und sagt er hätte 6042 Punkte geladen.
Wenn du jetzt auf den Server joinst klappt es trotzdem noch nicht?

In der Log ist leider auch nicht ersichtlich was er am Start des Servers macht, also ob er dann schon die Datei lädt

**Comment by Bandesss** [comment]
Jupp alle da. Vielen Dank. 
Der beste mod in ls19. Nochmal danke.

**Comment by Stephan-S** [comment]
hm, trotzdem etwas seltsam.
Schade das wir nicht herausfinden konnten woran es lag.

Aber, viel Spaß dann ab jetzt :-)
