### ISSUE TITLE
[BUG] Error: Running LUA method 'loadSharedI3DFileFinished'. --> Spielstand lädt nicht mehr

### ISSUE THREAD

**Issue by Heinersteff** [Stephan-S/FS19_AutoDrive#1842]
AutoDrive Version: 1.1.0.7
Release or selbsterstelltes zip: Release
Karte (falls relevant): Felsbrunn
Fahrzeug(art) (falls relevant):

**Beschreibe den Bug**
Wenn ich meinen Spielstand lade, lädt er, jedoch kommt kein Start Button. In der Log erscheint dann folgender Fehler: 
Error: Running LUA method 'loadSharedI3DFileFinished'. 
Update auf Version 1.0.0.8 hat das Problem nicht gelöst. Ebenso neuinstallation des LS 19
 oder des AD Mods. Ohne AD Mod startet der Spielstand ganz normal. 

[log.txt](https://github.com/Stephan-S/FS19_AutoDrive/files/6125884/log.txt)

Woran kann das liegen?

**Falls anwendbar - Schritte mit denen ich den Bug nachstellen kann**

**Screenshots**
Falls relevant, bitte Screenshots beifügen

**Comment by Axel32019** [comment]
Hallo @Heinersteff , Bitte AutoDrive_config.xml umbenannt in .txt hier einfügen.

**Comment by Heinersteff** [comment]
[AutoDrive_config.txt](https://github.com/Stephan-S/FS19_AutoDrive/files/6126453/AutoDrive_config.txt)

**Comment by Heinersteff** [comment]
[vehicles.txt](https://github.com/Stephan-S/FS19_AutoDrive/files/6132659/vehicles.txt)

**Comment by Axel32019** [comment]
Bitte kein Komma in Zielen verwenden - hier die angepassten Dateien, bitte mal probieren:
[AutoDrive_config.txt](https://github.com/Stephan-S/FS19_AutoDrive/files/6133141/AutoDrive_config.txt)
[vehicles.txt](https://github.com/Stephan-S/FS19_AutoDrive/files/6133142/vehicles.txt)

**Comment by Heinersteff** [comment]
Habe Sie getestet. Bis jetzt läuft alles einwandfrei. Vielen, Vielen Dank für deine Hilfe.
Heißt in Zukunft keine Sonderzeichen, Kommas o.ä. bei der Bennenung der Ziele?

**Comment by rellek82** [comment]
Guten Morgen. Kommt der Fehler nur bei Sonderzeichen wie Komma oder so?
Ich beschrifte Zielpunkte mit den Tiefstrich (z.B. BGA Silo 1_2 [für Silo 1, Spur 2]) und hatte bisher keine Probleme.

**Comment by Axel32019** [comment]
Hallo, Das Komma wird AD-intern verwendet. Leider ist noch nicht überall eine Prüfung auf nicht erlaubte Zeichen implementiert.
@rellek82 Solange alles läuft, ist ja alles gut, wenn nicht weisst Du wonach Du suchen kannst :-)
