### ISSUE TITLE
Route priority

### ISSUE THREAD

**Issue by fuggo2** [Stephan-S/FS19_AutoDrive#1843]
Hello, First of all, respect for your work, AD helps a lot in the game. However, there would be a question, if I set a route to the silo but there is a combine parking lot next to the road, then the AD will always "shorten" it through the parking lot, how can this be filtered out? I attach a screenshot where I tested this. now the parking lot is on a blue line and the silo road is green. it was the other way around before and it was abbreviated even then! The question might be to give some priority to one of the paths that AD should take, even if there is an abbreviation directly. or is this nonsense? Thanks for the reply!

![Farming Park](https://user-images.githubusercontent.com/66201069/111069467-79b50280-84cd-11eb-828d-62e7adc62d8d.jpg)

**Comment by 60erjonny** [comment]
Hallo
Wie hoch ist bei dir, die Einstellung..." maximaler Umweg" ...?
![Screenshot (43)](https://user-images.githubusercontent.com/63659182/111073603-a83bd900-84df-11eb-8dff-7868894055e3.png)

**Comment by fuggo2** [comment]
Default , 0m

do I need to change this? Do you have anything else tipped on what to change from the default settings?

Thx

**Comment by 60erjonny** [comment]
Hallo

Testen sie umbedingt, mit einem höheren Wert als 0...

**Comment by chris1601** [comment]
I managed to work around that exact Problem by not connecting the Parking Bay directly to the Courses again. I added one point right after the Parking Positions but didn't connect it to the Point marked as Parking Position.
This way AD won't drive through my Vehicle Halls but I can send Vehicles from the Parking Position just fine.

Hope that helps for now.

**Comment by 60erjonny** [comment]
Hallo @chris1601 

Can you take a picture here ... ?
