### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by JonasGHansen** [Stephan-S/FS19_AutoDrive#1844]
**AutoDrive Version:** 1.1.0.7   
**Release or Custom Zip:** Release  
**Map (If applicable):** Eiersholt (Editet)  
**Vehicle / Type (If applicable):** Truck+Trailer  
**Multiplayer or Singleplayer:** Dedicated server  

**Describe the bug**  
I have few troubles on dedicated server, where the trucks transporting either manure or slurry, when driving to different destinations does not seem to be able to actually calculate the shortest route... or sometimes stops driving even tho its clear path. 

**If applicable - Steps to reproduce the behavior**  

**Screenshots**

**Comment by Axel32019** [comment]
@JonasGHansen Please provide some more info, i.e. Screenshot with network.

**Comment by Axel32019** [comment]
no further information -> closed.
