### ISSUE TITLE
[Feature Request] command AD without sitting in a vehicle

### ISSUE THREAD

**Issue by puppryde** [Stephan-S/FS19_AutoDrive#1845]
one thing that bugs me about autodrive, and CP as well, is having to get into a vehicle to start it on a route, i'd love if there was some way to command a vehicle i'm not driving, it would make controlling multiple vehicles at once much easier.

**Comment by Iwan1803** [comment]
I know that everyone has their own way of playing this simulator, but we are not going to make a manager out of the game.
**Ich weiß, das jeder seine Art hat, diesen Simulator zu spielen, aber wir werden keinen Manager aus dem Spiel machen.**
