### ISSUE TITLE
[BUG] Setting up parking positions

### ISSUE THREAD

**Issue by Kitekater** [Stephan-S/FS19_AutoDrive#1846]
AutoDrive Version: 1.1.0.8
Release or selbsterstelltes zip: Release
Karte (falls relevant): NF_ Marsch 4 fach
Fahrzeug(art) (falls relevant):

**Beschreibe den Bug**
Wir spielen im Multiplayer auf einem dedicated Server.
Hier ist es nicht möglich einen Parkplatz zuzuweisen.
Egal üb Anbauteil oder Fahrzeug selber.

Im Editor-Modus:
STRG+ re Maus oder ALT+re Maus bringen kein Ergebnis

**Falls anwendbar - Schritte mit denen ich den Bug nachstellen kann**

**Screenshots**
Falls relevant, bitte Screenshots beifügen

**Comment by Iwan1803** [comment]
Problem ist bekannt und betrifft nur Dedi-Server. 
An einem Fix wird bereits gearbeitet.

**Comment by KarlGutenberg** [comment]
Ich spiele auf kein Server und kann auch kein Parkplatz zuweisen!
1.1.0.7 geht noch!

**Comment by Iwan1803** [comment]
@KarlGutenberg 
Du weißt, das sich in der 1.1.0.8 was bzgl. Tastenkombis geändert hat?

**Comment by KarlGutenberg** [comment]
Iwan1803 ***@***.***> schrieb am Sa. 20. März 2021 um 11:57:

**Comment by KarlGutenberg** [comment]
Iwan1803 ***@***.***> schrieb am Sa. 20. März 2021 um 11:57:

**Comment by UnknwnArtst** [comment]
> @KarlGutenberg
> Du weißt, das sich in der 1.1.0.8 was bzgl. Tastenkombis geändert hat?

Wo kann man den Changelog einsehen damit das ersichtlich ist? Habe nämlich das gleiche Problem in Singleplayer

**Comment by Iwan1803** [comment]
Hier im Wiki unter Release Notes:
https://github.com/Stephan-S/FS19_AutoDrive/wiki/Release-Notes

**Comment by Ralf254** [comment]
@Iwan1803 
Habe in der Changelog zwar den o.a. Hinweis gefunden, aber welche Taste ist es denn nun, mit der man einen Parkplatz zuweist? Habe im FS-19-Menü bei der Tastenbelegung nichts gefunden.

**Comment by KarlGutenberg** [comment]
Verstehe jetzt nicht?

Ralf254 ***@***.***> schrieb am Fr. 2. Apr. 2021 um 18:23:

**Comment by Ralf254** [comment]
Mein Problem: nach update auf AD 1.1.08 konnte ich mit der rechten Maustaste keinen Parkplatz mehr zuweisen (s.o.). In den oben erwähnten Releases-Notes steht: 
"ADDED: new key+mouse combination to set/delete P destination
left-mouse -> no change, will send vehicle to park in every AD Mode"

Daher meine Frage: welche "new key+mouse combination" muss ich betätigen um einen Parkplatz zu definieren?

**Comment by Axel32019** [comment]
@Ralf254 Das steht im Release-Note genau 2 Zeilen tiefer.
