### ISSUE TITLE
[BUG] Railroad Gates collision?

### ISSUE THREAD

**Issue by andreasthu** [Stephan-S/FS19_AutoDrive#1847]
AutoDrive Version: 1.1.0.8
Release or selbsterstelltes zip: Release
Karte (falls relevant): Alle, derzeit Erlengrad 
Fahrzeug(art) (falls relevant):

**Beschreibe den Bug**
Eine klare Beschreibung des Bugs.
Der AD Fahrer hält vor dem geschlossenen Bahnübergang nicht an.
**Falls anwendbar - Schritte mit denen ich den Bug nachstellen kann**
Collisipn AN, collisionshöhe 1,75 oder 2m
**Screenshots**
Falls relevant, bitte Screenshots beifügen
Lg
Andreas

**Comment by Axel32019** [comment]
Hallo @andreasthu , Dann hat die Schranke wohl keine Colli, oder? Kannst Du von Hand durchfahren?

**Comment by andreasthu** [comment]
Hallo Axel. 
Doch, die Schranke hat collisipn.
Ist die map aus dem Alpine dlc, Erlengrat.
Der Traktor fährt an die Schranke bis zum Kontakt, die Räder drehen durch, und wenn die schranke hochgeht bleibt der Traktor daran hängen und der vordere Teil wird hochgehoben.
Lg
Andreas

**Comment by andreasthu** [comment]
Hallo Axel
ich hab hier noch zwei Videos davon gemacht:
https://youtu.be/Gyd4xHpj5Rc
und
https://youtu.be/ELchMATXACI
in einem "steht" der Zug hinter dem Schranken, der AD Traktor bleibt vor dem Schranken stehen - ev weil er den Zug bemerkt
im zweiten ist der zug etwas weg, und der AD Traktor crasht voll gegen die Schranke.
lg
andreas

**Comment by Axel32019** [comment]
Hallo @andreasthu,
Das liegt an der eingestellten Kollisions-Höhe. Standart sind 2m, damit "schaut" die Kollisions-Erkennung jedoch über die Schranken.
Setzt Du diese auf < 1.75m halten die Fahrzeuge an. Man kann hier leider keinen allgemein funktionierenden Wert finden, hängt immer von den konkreten Gegebenheiten auf den Karten ab.

**Comment by andreasthu** [comment]
Ja, gerade auf erlengrat blöd mit der collisionshöhe.
Bei unter 2m bleibt man da bei jeder Mulde stehen.
Aber es gibt bei den bahnschranken doch auch eine unsichtbare collision, die da mit hoch fährt.
Die fährt höher aus als 2m. Die hat aber eine andere collimask, müsste in  Felsbrunn mal nachsehen welchen Wert die hat. Ev könnte AD auch auf diese reagieren und stoppen?
Lg
Andreas

**Comment by andreasthu** [comment]
Hallo @Axel32019 
ich hab mir das ganze mal auf Felsbrunn angesehen.
da gibt es eine collibox "trafficBlocker", die von y -2 auf y 1.5 hochfährt, wenn sich der Schranken schließt:
![Unbenannt](https://user-images.githubusercontent.com/24860501/112064371-22fd9780-8b63-11eb-9c23-4f45e71cefcd.png)
diese hat aber die collimask "100000" bzw den Haken bei Kästchen 20, keine "ff".
diese Box ragt auch 3meter über den Grund wenn sie ausgefahren ist (daneben habe ich nur zum vergleich eine GE-Plane auf 2m höhe hingestellt=.
wenn nun AD auch die Kollision 100000 "erkennen" würde und stehenbleiben täte wäre das super, auch mit höheren AD einstellungen vom Boden aus.
lg
andreas

**Comment by Axel32019** [comment]
Hallo @andreasthu ,
Diese Colli-Mask ist der "trigger_player", dieser wird z.B. bei vielen/allen GC Produktionen verwendet um den Spieler zu detektieren und die Anzeige zu aktivieren. Hier würde somit jedes Fahrzeug davor anhalten, da die Höhe vom Map-/Modder festgelegt wird.
Ich halte es daher nicht für sinnvoll AD-Fahrzeuge hierauf reagieren zu lassen.
Trotzdem Danke für Deine Bemühungen bei der Untersuchung - gerne weiter so!
