### ISSUE TITLE
[BUG] Unerlaubtes Aufladen

### ISSUE THREAD

**Issue by NeonRider1999** [Stephan-S/FS19_AutoDrive#1848]
AutoDrive Version: 1.1.0.9
Release or selbsterstelltes zip: Selbständige Zip
Karte (falls relevant): Alle
Fahrzeug(art) : Anhänger/Güllezubringer

**Beschreibe den Bug**
Hallo
Mir ist folgendes Problem aufgefallen. Ich möchte Gülle zum Feld mit zwei Güllezubringern fahre lassen. Das Problem ist wenn einer das Ziel z.b BGA Befüllen hat und der andere Voll entgegen kommt füllen sich die beiden Fahrzeuge mitten auf der Straße gegenseitig auf.

2 Beispiel ich habe einen Globalen Markt (Irgendwo in Thüringen V3) wo Entlade Trigger und Belade Trigger genau hintereinander sind. Möchte ich nun von meinem Lager z.b Weizen im Global Market Verkaufen so Kippt er erst ab (Was absolut richtig ist) aber sobald er unter das Rohr zum Beladen fährt füllt er sich wieder Voll auf da er als Nächstes Ziel wieder meinen Hof hat. Das heißt er lädt nicht dort auf wo er soll sondern schnappt sich die Nächstegelegene Stelle wo er das bekommt was er will in dem Fall Weizen oder Gülle

**Comment by Mannie313** [comment]
Welchen Globalmarkt hast du?

Ich hab den von Global Company und da funtioniert es.

MFG Mannie313

**Comment by NeonRider1999** [comment]
Habe ich doch Geschrieben. Es ist der Fest verbaute auf der Irgendwo in Thüringen V3. Dort sind Entlade Trigger und Lade Trigger hintereinander. Wenn ich Dünger Abgebe fährt er die 20m vor und Läd sie dann wieder auf

**Comment by UnknwnArtst** [comment]
Ich habe ein sehr ähnliches Problem, fahre zb Mist von den Kühen oder Schweinen in das entsprechende Lager und nach dem abladen füllt sich der Hänger seit dem Update auf die aktuelle GitHub Version wieder auf und steht dann so erneut bei den Tieren.

**Comment by Axel32019** [comment]
@NeonRider1999 @UnknwnArtst Bitte mal mit der beta-Version probieren.

**Comment by NeonRider1999** [comment]
Hallo nach langer Zeit am Pause vom PC habe ich es auch mal geschafft es zu Testen.
Also in bei mir funktioniert es jetzt wieder ohne Probleme
