### ISSUE TITLE
Überladewagen Rufen

### ISSUE THREAD

**Issue by gottdi** [Stephan-S/FS19_AutoDrive#1849]
Hallo 

Ich habe eine frage , wir haben alles eingestellt damit wir den überlade Wagen rufen können. Ich bzw wir fahren beide gerne selber Drescher . Nun meine frage wenn ich den Drescher mit Helfer fahren lasse , findet der ülw den Drescher immer ( berechnet den Kurs sehr schnell). Sobald ich selber fahre und den ülw rufen dauert es recht lange bis er die gleiche strecke berechnet. Ab wann bzw. wie ruft ihr den ülw ? ich fahre immer bis 100% halte an fahre das Rohr aus und rufe erst dann den ülw. Gibt es sonst eine bessere Methode ? 

währe für Tipps dankbar 

p.s wir spielen auf einen Server 

mfg dirk

**Comment by Axel32019** [comment]
Hallo @gottdi , Es gibt da keinen Unterschied bei Ablader rufen durch Helfer oder selbst. Die unterschiedliche Berechnungszeit kann sich jedoch z.B. durch Fruchtumfahrung ergeben: Der Helfer fährt aus der Frucht, Du evtl. nicht - dann wird erst versucht Frucht zu umfahren und wenn das nicht möglich ist neu berechnet - dauert dann möglicherweise länger.

**Comment by gottdi** [comment]
Danke für die rückantwort.
