### ISSUE TITLE
Drescher abfahren Berechnung dauert ewig

### ISSUE THREAD

**Issue by Mib83** [Stephan-S/FS19_AutoDrive#1850]
AutoDrive Version: 1.1.0.8
Release
Karte Wild West v1.9
Drescher JD X9 und S790
Abfahrer JD 9620 und LKW Roadruner

Wir Spielen im MP zu 3 und haben seit dem Update von 1.1.0.7 auf die 1.1.0.8 das Problem das die Abfahrer mehr als 1 Stunde brauchen zum losfahren zum Drescher.

Fruchtumfahrung ist aus. 
Am Anfang hatten wir 2-3 Drescher auf einen Punkt gestellt mit 4-5 Abfahrer.
Dann haben wir pro Punkt 1 Drescher und 2 Abfahrer.
Als allerletzten test war ich alleine auf der Karte und auf Feld 44 mit 1 Drescher und 2 Abfahrer waren aktiv die Berechnung hat 1h und 20min gedauert.

Gibt es eine neue Einstellung das die Berechnung schneller geht?
Sonst werden wir wieder auf die 1.1.0.7 zurück gehen.

Danke und Grüße Michael

**Comment by Axel32019** [comment]
Hallo @Mib83 , Solche Berechnungszeiten sind nicht normal.
Bitte mal die Autodrive_config.xml und vehicles.xml umbenannt in .txt hier posten.

**Comment by Mib83** [comment]
Hallo Alex, 
anbei die Dateien.
[https://drive.google.com/file/d/1XamshDa3MTlWhXXMLRuN1Fy9UVgl_Uay/view?usp=sharing](url)
[https://drive.google.com/file/d/1Do6DS_VDzZY5GLy5mJCrf9TZVX7tCeEn/view?usp=sharing](url)

**Comment by Axel32019** [comment]
Hallo @Mib83 , Dafür wird ein Zugriff benötigt - bitte die Dateien als .txt einfach hier in den Kommentar ziehen.

**Comment by Mib83** [comment]
[AutoDrive_config.txt](https://github.com/Stephan-S/FS19_AutoDrive/files/6191800/AutoDrive_config.txt)
[vehicles.txt](https://github.com/Stephan-S/FS19_AutoDrive/files/6191803/vehicles.txt)

**Comment by Axel32019** [comment]
Die Drescher-Einstellung Abfahrer finden auf nein setzen (begrenzt "Such"-Radius auf <= 300m).
Beim Drescher das gleiche Ziel wie beim Abfahrer einstellen, aber im Drescher AD nicht aktivieren!

**Comment by Mib83** [comment]
Danke werden wir am Montag testen.

**Comment by Mib83** [comment]
Hallo also haben jetzt folgendes gemacht.
Wir haben an dem Drescher die Einstellung Abfahrer finden auf nein gestellt. 

Test 1
Wir haben dann erst 4 Drescher mit CP eingeschaltet und AD auf den Punkt Feld 60 gestellt, und dazu 6 Traktoren  zum abfahren. Die erste Runde abfahrer sind nach 1 Min Berechnung abgefahren nach und nach. nach dem die Abfahrer das 2 mal zum entladen angefahren sind und dann im Silo abgeladen haben sind sie auch wieder schön brav zum Feld 60 Punkt gefahren. Aber beim 2 mal wo sie los fahren sollten kam Punkt 1 / 3 Berechnen und hat dan auch nicht mehr aufgehört auch nach 2 Stunden. Dann haben wir die Abfahrer ins Feld gestellt hier das gleiche wieder.

Test 2
4 Drescher aber aufgeteilt in Feld 60A 2 Stück und Feld 60B 2 Stück.
Hier das gleiche wieder erst geht es 1 mal beim 2 mal nicht mehr.

Test 3 
Wiederholung von Test 1 mit AD version 1.1.0.7 und hier geht alles ohne Probleme und Berechnung dauert nur paar Sekunden.

Gerne kann ich euch auch mal das komplette Savegame und Mods zur verfügung stellen.

**Comment by Axel32019** [comment]
Hallo @Mib83 , Sorry für die späte Reaktion - viel zu tun...
Würdest Du mir bitte mal das Savegame und wenn vorhanden Client- / Serverlog hier anfügen.
Die mods sollte ich so finden, wenn nicht komme ich auf Dich zurück.

**Comment by Mib83** [comment]
Hallo Axel,

hier sind alle Daten http://berghammer.be/mib83.zip

Allerdings ist mir heute morgen aufgefallen das bei der 1.1.0.8 auf einmal alle Autodrive punkte weg waren bei der 1.1.0.7 waren noch alle da. Wir sind jetzt nur 2 Tage Beruflich weg.

**Comment by Axel32019** [comment]
Hallo @Mib83, Hab mal F60 mit 4 Dreschern und 4-5 9er und 2 Roadrunner-Abfahrern einige Stunden laufen lassen - funktioniert bei mir.
Das Berechnen auf solch großen Feldern dauert natürlich etwas, es wird immerhin das komplette Feld und ca. 30m um den Feldrand untersucht.
Ich würde Dich um folgendes bitten:
- Die FS19_AutoDrive.zip anbei verwenden
- Die Tastenbelegung "AD: Entwickler Aktion" zuweisen, ich hab dafür CTRL ALT D gewählt
- Sollte jetzt ein Abfahrer länger als ca. 5 min rechnen, in dieses Fahrzeug wechseln und die o.g. Tastenbelegung aktivieren
- Dies schreibt ins log die Berechnungsschritte für dieses Fahrzeug
- Da viele gleich heißen, bitte das log kopieren, sichern o.ä.
- Log(s) hier anhängen
Danke & Gruß
[FS19_AutoDrive.zip](https://github.com/Stephan-S/FS19_AutoDrive/files/6273207/FS19_AutoDrive.zip)

**Comment by Mib83** [comment]
Hallo Alex,

danke wir haben jetzt paar mal getestet und jedesmal ging es mit der Obrigen Version.

Danke das lägste was er mal berechnet hat war 1,5 Minuten.

Grüße Michael

**Comment by Axel32019** [comment]
Hallo Michael,
Das ist schon eigenartig. Die obige Version ist genau die Version 1108, einzig die fahrzeugspezifische Protokollierung ist aktiviert, was ca. 15% mehr Berechnungszeit bewirkt.

**Comment by Mib83** [comment]
Das ist echt merkwürdig. Wir können grad nicht Spielen aber wir werden in ein Paar Tagen uns nochmal paar Tagen was Testen und melden uns wieder.

**Comment by Stephan-S** [comment]
Da hat sich inzwischen wieder einiges getan. Daher mache ich hier zu und verweise mal auf die aktuelle alpha bzw. den nächsten anstehenden Release.
