### ISSUE TITLE
[BUG] Güllefass von Kotte-FRC oder Transportfass befüllen - spammt log voll

### ISSUE THREAD

**Issue by andreasthu** [Stephan-S/FS19_AutoDrive#1853]
AutoDrive Version: 1.1.0.9.rc1
Release or selbsterstelltes zip: selbsterstelltes zip
Karte (falls relevant): Erlengrat
Fahrzeug(art) (falls relevant): Güllefasss, Güllezubringer oder Kotte FRC

**Beschreibe den Bug**
2021-03-22 04:03 C:/Users/******/Documents/My Games/FarmingSimulator2019/mods/FS19_AutoDrive/scripts/Utils/TrailerUtil.lua:606: attempt to index global 'self' (a nil value)
2021-03-22 04:03 Error: Running LUA method 'update'.

**Falls anwendbar - Schritte mit denen ich den Bug nachstellen kann**
ich stelle den Kotte FRC neben dem AD kursnetz hin und lasse ihn vom Steyr mit dem Güllezubringer befüllen - das funktioniert super.
den claas mir dem Güllefass will ich nun mit AD beim Kotte FRC befüllen lassen - dann spammt es mir die log mit:  
```
Games/FarmingSimulator2019/mods/FS19_AutoDrive/scripts/Utils/TrailerUtil.lua:606: attempt to index global 'self' (a nil value)
2021-03-22 04:03 Error: Running LUA method 'update'.
```
voll.
genauso, wenn ich den Kotte FRC wegnehme und den Steyr mit dem Güllezubringer anstelle des FRC hinstelle.
auch wenn der claas mit Güllefass vom Güllezubringer entnehmen sollte, der gleiche log-spam.
manuell befüllen funktioniert.

**Screenshots**
![fsScreen_2021_03_22_04_25_35](https://user-images.githubusercontent.com/24860501/111936797-b7fe8300-8ac6-11eb-8756-affa9821d641.png)

lg
andreas

**Comment by Iwan1803** [comment]
Das kann passieren, wenn man die Beta benutzt 😉

@Axel32019 
kannst du das exzessive Logging zumindest in der Beta rausnehmen?

**Comment by andreasthu** [comment]
ok,
ich dachte der sinn der beta ist diese zu testen und fehler zu melden.
normal spielen mit der offiziellen 1.1.0.8 kann ja jeder.
lg
andreas

**Comment by Iwan1803** [comment]
Das Logging ist absichtlich in die Pre-Beta eingebaut worden, um gewisse Sachen zwecks Fehlersuche zu protokollieren.
So gesehen ist es kein "Fehler", außer das es vor dem Upload in den Beta-Tree nicht wieder rausgenommen worden ist 😉

**Comment by Axel32019** [comment]
Hallo @andreasthu , Danke für den Hinweis - weiter so!

**Comment by andreasthu** [comment]
Ich sage danke für AD - weiter so
:-)
