### ISSUE TITLE
[BUG] autodrive will not load into CP

### ISSUE THREAD

**Issue by Gibbanator** [Stephan-S/FS19_AutoDrive#1854]
**AutoDrive Version:** 1.1.0.8   
**Release or Custom Zip:** Release  
**Map (If applicable):** All  
**Vehicle / Type (If applicable):**   
**Multiplayer or Singleplayer:** Singleplayer  

**Describe the bug**  
I load a CP field course than I attempt to load a AutoDrive route to barn and Return to field but it will not load into CP.. I try loading any autoDrive route and non will load.
Here is My Log: 
[log.txt](https://github.com/Stephan-S/FS19_AutoDrive/files/6185807/log.txt)
Here is a Video: https://youtu.be/UJRfQf5jvBg

**If applicable - Steps to reproduce the behavior**  

**Screenshots**

**Comment by Roby1164** [comment]
??? I don't have that method to use CP and AD together .....
Better to use the CP. for the loading path, and activate the item "Use AD for unloading / Loading", while in the AD set the delivery function, setting it as the starting point. the number of the field, for the unloading the unloading triger and the type of product, in AD also click on the button with the hexagon and the C, and the C becomes yellow, at that point start the CP, and the vehicle will do the his collection work, when full he starts the AD and will go to deliver ....
Right now I can't make screenshots, as soon as I can I see to put them.

**Comment by andreasthu** [comment]
Maybe you are to wide away from an AD coursepoint. So this dont work then for me.
Drive with the tractor near a AD point and try again, so then this works for me, CP v 6.03.00051 and AD 1.1.0.8 or 1.1.0.9-rc1
Lg
Andreas

**Comment by Tensuko** [comment]
> 
> 
> ??? I don't have that method to use CP and AD together .....
> Better to use the CP. for the loading path, and activate the item "Use AD for unloading / Loading", while in the AD set the delivery function, setting it as the starting point. the number of the field, for the unloading the unloading triger and the type of product, in AD also click on the button with the hexagon and the C, and the C becomes yellow, at that point start the CP, and the vehicle will do the his collection work, when full he starts the AD and will go to deliver ....
> Right now I can't make screenshots, as soon as I can I see to put them.

Got nothing to do with loading an AD course into CP...

**Comment by Axel32019** [comment]
No Bug in AD - just try to use driveto in AD to check if the route network is OK or not.
