### ISSUE TITLE
[BUG]AutoDrive:dijkstraLiveShortestPath ERROR count > 50000

### ISSUE THREAD

**Issue by xGloryJx** [Stephan-S/FS19_AutoDrive#1855]
**AutoDrive Version:** 1.1.0.8
**Release or Custom Zip:** Release  
**Map (If applicable):** Lakeland_Vale_By_Stevie_V1_50_1_11
**Vehicle / Type (If applicable):**   Fendt 900
**Multiplayer or Singleplayer:** Singleplayer  

**Describe the bug**  
The dijkstra algorithm has problems finding a route. 
`Axel: AutoDrive:dijkstraLiveShortestPath ERROR count > 50000`
see screenshot
dijkstra doesn't find a route from A to F
dijkstra finds a rout if i start at B1, B2, C1, C2 to F
if i cut the network a the red line  dijkstra  finds a route from A to F

I saw that the DijkstraLive.lua was changed with verstion 1.1.0.8. I added a print before line 20.
`return false, false --something went wrong. prevent overflow here`
I didn't see that print in the log --> The problem must be somewhere else.

Is there a way to get more debug information? Maybe print more to the log?

**Screenshots**  
![map](https://user-images.githubusercontent.com/81217221/112113197-ccba4400-8bb6-11eb-9888-d057e87fe3c1.jpg)

**Comment by Axel32019** [comment]
Hello @xGloryJx , Could you please attach Autodrive_config.xml and vehicles.xml renamed to .txt here.

**Comment by xGloryJx** [comment]
@Axel32019 here are the files. Please tell me if i just configured something wrong.
[AutoDrive_config.txt](https://github.com/Stephan-S/FS19_AutoDrive/files/6192600/AutoDrive_config.txt)
[vehicles.txt](https://github.com/Stephan-S/FS19_AutoDrive/files/6192601/vehicles.txt)

A in the picture is
`<id>394.000000</id>`

F in the picture is
`<id>471.000000</id>`

**Comment by xGloryJx** [comment]
I newly created the route to C1 using auto connect at end, now it works -> [AutoDrive_config - works.txt](https://github.com/Stephan-S/FS19_AutoDrive/files/6192951/AutoDrive_config.-.works.txt)
Now i deleted one point and made the connection between to points by holding down lshift, now it's broken again -> [AutoDrive_config - broken.txt](https://github.com/Stephan-S/FS19_AutoDrive/files/6192952/AutoDrive_config.-.broken.txt)

I didn't have to change the other connections where i manually connection two points by holding down lshift.

Do i still connect tow points by holding down lshift?  If i do it like that the path is in a light blue not green is that correct? 
![fsScreen_2021_03_23_22_36_18](https://user-images.githubusercontent.com/81217221/112221837-36bf0180-8c28-11eb-8e19-ac7c13e32376.png)

**Comment by xGloryJx** [comment]
@Axel32019 It was my fault i used left shift instead of left ctrl to connect two points. I closed the bug hope that's okay for you.
