### ISSUE TITLE
Abfahrer fährt beim dreschen nicht weit genug zurück

### ISSUE THREAD

**Issue by oldmicha** [Stephan-S/FS19_AutoDrive#1856]
AutoDrive Version: 1.1.0.8
Release or selbsterstelltes zip: Release
Karte (falls relevant): Lösshügelland, MVP19, Hof Bergmann
Fahrzeug(art) (falls relevant): Claas 8900 mit 12,3m Schneidwerk, Verschiedene Abfahrer mit Tandemanhänger
Im Single und Multiplayer/Dediserver
Curseplay 6.03.00051

**Beschreibe den Bug**
Der Drescher Claas 8900 fährt mit CP und 12,3 m Schneidwerk  - ist zu 95% voll und drischt sich eine Abladebucht für den Abfahrer. Der Abfahrer kommt - es wird abgetankt - der Drescher kehrt in seiner Position von CP wieder in seine Spur. Abfahrer fährt in der Version 1.1.0.8 nicht weit genug zurück und der Drescher fährt mit dem Schneidwerk in den Abfahrer. Bei dem Tucano von Claas mit 7,7m Schneidwerk passiert das nicht mehr!

In der AD 1.1.0.7 fährt der Abfahrer mit Anhänger weit genug zurück!

**Comment by Axel32019** [comment]
Hallo @oldmicha , Das haben wir mit dem Lexion 8900 im speziellen auch schon festgestellt - bei Interesse gern mit der beta-Version probieren.

**Comment by Stephan-S** [comment]
Soweit ich mich erinnere, ist der Abstand inzwischen erhöht und das Thema erledigt. Falls nein, bitte neu aufmachen, danke.
