### ISSUE TITLE
Funktion Routen-Manager

### ISSUE THREAD

**Issue by TripleX1978** [Stephan-S/FS19_AutoDrive#1857]
Kann mir jemand bitte mal die Funktionsweise des Routenmanagers erklären.
Konnte bisher nichts passendes finden.

Ich habe das so verstanden, dass ich zum Beispiel ein Fahrzeug Gülle von A nach B liefern lasse.
Diese Route würde ich dann im Manager z.B. als Gülle A-B abspeichern.
Wenn ich jetzt auf der selben Route noch ein Fahrzeug fahren lassen möchte, dann würde ich von dem Fahrzeug aus den Routenmanager öffnen und die Route laden.
Bei mir passiert aber nichts.
Alle Einstellungen bleiben unverändert.

**Comment by 60erjonny** [comment]
https://github.com/Stephan-S/FS19_AutoDrive/issues/1120

**Comment by TripleX1978** [comment]
Sorry...aber das hilft mir nicht wirklich weiter.

**Comment by 60erjonny** [comment]
Hallo

Ok ich benutze diese Funktion nicht, aber so weit ich weiß kann man ganze Straßennetze speichern oder laden.
Einzelne Touren so wie du sie beschreibst, kann man nicht damit nicht verwalten...

**Comment by TripleX1978** [comment]
Danke für die Info.
Schade...wäre auch ein nettes Feature gewesen.
