### ISSUE TITLE
Güllefass Befühlt Falsch [BUG]

### ISSUE THREAD

**Issue by BlackStar153** [Stephan-S/FS19_AutoDrive#1858]
AutoDrive Version: 1.1.0.8
Karte (falls relevant): NF Marsch 4 Fach

**Beschreibe den Bug**
Der Fahrer Tankt die Gülle hin und her was nicht sein solte  leider kann ich das nicht fixen 

Nach dem Testen der 1.1.0.7 hab ich denn fehler gefunden es liegt an der 1.1.0.8  denn dort ist das güllefass ständig an und versucht immer zu laden  auch getestet ohne mods gleicher fehler   wär super wenn ihr das abschalten könntet 
https://drive.google.com/file/d/1YaEUR_dIU9H8q9HiJvJfML11rVFRKj50/view?usp=sharing

[log.txt](https://github.com/Stephan-S/FS19_AutoDrive/files/6191914/log.txt)

**Comment by Axel32019** [comment]
Hello @BlackStar153 , Wir haben hierfür eine Verbesserung gefunden und in der beta-Version implementiert.
Wichtig: Den Belade-Zielpunkt vor das Belade-Fahrzeug setzen, dann sollte auch nicht wieder zurück gefüllt werden.
Gerne mal die beta probieren.

**Comment by BlackStar153** [comment]
oke versteh jetzt gerade nicht wie du das meinst

**Comment by BlackStar153** [comment]
Wo soll was stehn habt ihr Bild? kann mir das gerade nicht vorstellen

**Comment by BlackStar153** [comment]
das mit denn Laden wurde gefixt aber nicht das er davor anhöt der bug bleibt bestehn
