### ISSUE TITLE
Güllezubringer bleibt einfach stehn[BUG]

### ISSUE THREAD

**Issue by BlackStar153** [Stephan-S/FS19_AutoDrive#1859]
**AutoDrive Version:** 1.1.0.8
Problem beim Überladen von Gülle LKW fährt nicht weiter wenn er in denn verladetrigger kommt

![grafik](https://user-images.githubusercontent.com/79724679/112369892-071e0100-8cdd-11eb-885c-d8e65a1f6fb2.png)

**Comment by 60erjonny** [comment]
Hallo
Versuche mal, das der Güllezubringer, von der anderen Seite her den Feldpunkt anfährt.
Warum ist der eine Punkt so verschoben...?

**Comment by BlackStar153** [comment]
problem is das er ständig das fass pumpen läst das tut er in der 0.7 nicht weiß nicht warum er denn auf dauerschleife laufen läst

**Comment by BlackStar153** [comment]
Problem besteht weiter hin

![20210325182750_1](https://user-images.githubusercontent.com/79724679/112516752-e36bc100-8d97-11eb-9954-866dcdb5a32d.jpg)

**Comment by 60erjonny** [comment]
Hallo
Kann mich auch irren, aber der Güllezubringer fährt doch genauso wie auf den oberen Bild den Feldpunkt an...???
Hat es überhaupt schon mal funktioniert ?
Erhöhe mal die Kollisionshöhe über Grund...2,25m oder 2,5 m...
Versuche auch mal die neue Version...1.1.0.8,,,
Evtl. mal einen anderen LKW versuchen...

**Comment by BlackStar153** [comment]
Nein ist es nicht schau genau hin
fahre erst seit gestern Gülle
neie version geht nicht da sie auch verbbugt ist mit Gülletechnik siehe  #1858

**Comment by 60erjonny** [comment]
Sorry, aber der LKW steht doch bei beiden Bilder gleich da und die Strecke ist genau wie oben, nur der eine Punkt ist verschoben....

**Comment by BlackStar153** [comment]
man sieht doch das ich  die Strecke des  Gülleausbringer gedreht habe und egal ist wie rum er heran fährt es geht nichts

**Comment by 60erjonny** [comment]
Langsam, du hast doch von Anfang an den Zubringer gemeint und nicht des Ausbringer oder...???
Und den meinte ich auch...

**Comment by BlackStar153** [comment]
Es ist doch egal welche von beiden ich drehe der fehler ist das er stehb bleibt zu zeitig wenn er in denn Trigger des Ausbringers Fährt 
Also ist das Thema schon mal Abgehackt mit denn Anfahrten daran liegt es nicht sondern An AD das er warum auch immer dort stehen bleibt auch wenn ich die Kolisionshähen ab ändere

**Comment by 60erjonny** [comment]
Sorry, nochmal hast du es getestet, das du es weißt ob es egal ist ? 
Evtl.mal ein Standart-fass versuchen...
Und sorry, ich will hier nur helfen...

**Comment by BlackStar153** [comment]
Ich habe beide Richtungen getestet ja 
Hm Standart...

**Comment by BlackStar153** [comment]
@60erjonny teste gerade die beta  scheint alle probleme gelöst zu sein

**Comment by BlackStar153** [comment]
fehler bleibt bei der 0.8. bestehn

**Comment by 60erjonny** [comment]
Hallo

Also ich habe es jetzt auch Mal versucht. 
Bin auf Feld 4 am Gährreste ausbringen, bei mir geht es mit der 1.1.0.8 Vers.
Ist erst ein Test, aber es ging bis jetzt...

**Comment by 60erjonny** [comment]
Nun, ich habe es weiter getestet, auf Feld 57 und jetzt auch auf Feld 16...bei mir geht es...ohne Probleme...
![Screenshot (46)](https://user-images.githubusercontent.com/63659182/112691679-f2c53a00-8e7d-11eb-9775-0b43df1c924a.png)
![Screenshot (47)](https://user-images.githubusercontent.com/63659182/112691688-f658c100-8e7d-11eb-9c31-bc8a6864d714.png)

**Comment by 60erjonny** [comment]
@BlackStar153 Darf ich erfahren, was für einen Fehler du gefunden hast...?

**Comment by 60erjonny** [comment]
Schaden das du nicht antwortest...
