### ISSUE TITLE
LUA-Fehler nach Update 1.1.0.8/ LUA-Errors after update 1.1.0.8

### ISSUE THREAD

**Issue by TripleX1978** [Stephan-S/FS19_AutoDrive#1860]
AutoDrive Version: 1.1.0.8

Seit dem Update werden mir LUA-Fehler angezeigt sobald ich nach dem Neustart in das erste Fahrzeug einsteige.
Die Zielpunkte sind noch alle vorhanden, aber das Streckennetz ist auch weg.
Hinzu kommt auch noch, dass das CP-Menü nicht mehr aufgerufen werden kann.
CP scannt am Anfang zwar die Felder, drauf zugreifen kann man aber nicht mehr.
Auf nach dem Aufspielen der 1.1.0.7 ist CP nicht mehr erreichbar.

Hier die log-Datei.
[log.txt](https://github.com/Stephan-S/FS19_AutoDrive/files/6210720/log.txt)

Zur Info - Die Errors bzgl. Xerion 5000 waren schon immer da und haben nie Probleme verursacht.

Update:
Das Streckennetz ist noch da, man kann es nur nicht mehr sehen.
Die Fahrzeuge finden noch alle ihre Ziele.
Die LUA-Fehler treten erst auf wenn man den Editormodus aktiviert.
Habe das ganze auch nochmal mit einem neuen Spielstand ohne Mods außer AD und CP ausprobiert.
Das Ergebnis war das selbe.
CP läuft jetzt wieder...warum auch immer...ich habe nichts geändert.

Update:
Habe jetzt mal ein Backup von gestern eingespielt.
Da funktioniert alles ganz normal, obwohl die gleichen Mods etc. geladen sind.

**Comment by Axel32019** [comment]
Hallo @TripleX1978 , Das sieht nach dem bekanntem Phänomen aus: #1684.
Bitte mal die Autodrive_config.xml, umbenannt in .txt hier einfügen.

**Comment by TripleX1978** [comment]
Hallo @Axel32019 ,
hier die config.
Bin aber, wie gesagt, wieder auf die 1.1.0.7 zurück.

[AutoDrive_config.txt](https://github.com/Stephan-S/FS19_AutoDrive/files/6254407/AutoDrive_config.txt)

**Comment by Axel32019** [comment]
Hallo @TripleX1978 , Die Config wurde mit 1.1.0.7 gespeichert und sieht OK aus, sollte auch mit 1.1.0.8 funktionieren.
Hast Du die ursprüngliche config zum Fehler noch?

**Comment by TripleX1978** [comment]
Hallo @Axel32019 ,
denke nicht.
Die 1.1.0.8 lief zuerst auch ohne Probleme. 
Von einem Tag wurden das Streckennetz nicht mehr angezeigt...war aber noch vorhanden. Die Zielpunkte konnten noch angefahren werden,  aber das Netz nicht mehr bearbeitet werden.
Kann ja nochmal die Umstellung auf 1.1.0.8 wagen. ;-)

**Comment by TripleX1978** [comment]
Hallo @Axel32019 ,
Bin nochmal auf 1.1.0.8 gegangen.
LUA-Fehler werden zwar immer noch sporadisch angezeigt, aber das Streckennetz ist wieder ok. 
Werde später nochmal eine aktuelle Log hochladen.

**Comment by TripleX1978** [comment]
Und hier nochmal eine Log mit Fehlern während des Spiels.

[log.txt](https://github.com/Stephan-S/FS19_AutoDrive/files/6304168/log.txt)

**Comment by Axel32019** [comment]
Hallo @TripleX1978 , Aus den letzten beiden logs:
- min. 3 Karten im mod-Ordner -> Regel: immer nur eine
- uralte CP Version: (Version: 6.02.00026) FS19_CoursePlay6 ,ursprünglich war es:(Version: 6.03.00051) FS19_Courseplay
- 2021-04-13 12:56 Error: Running LUA method 'update'.
2021-04-13 12:56 dataS/scripts/AchievementManager.lua(257) : attempt to index local 'farm' (a nil value)
ist keine AD Fehlermeldung -> siehe 1.Anmerkung
- sehe sonst keine AD Fehlermeldungen

**Comment by TripleX1978** [comment]
@Axel32019 : Danke für die Hilfe.
Hab jetzt die beiden Karten deinstalliert.
Wie stelle ich denn am besten auf die aktuelle CP-Version um?
Bei meinem letzten Versuch funktionierte danach nichts mehr.
Gibt das keine Probleme wenn ich das CP-Verzeichnis ohne "6" verwende?

**Comment by Axel32019** [comment]
Hier die FS19_Courseplay.zip Datei herunterladen und ins mod-Verzeichnis kopieren, nicht umbennen o.ä.
https://github.com/Courseplay/courseplay/releases
Nur eine CP Version im mod-Ordner!

**Comment by Axel32019** [comment]
@TripleX1978 Gibt es noch LUA Fehler von AD?

**Comment by TripleX1978** [comment]
@Axel32019 
Ich habe leider immer noch diverse Error- und Warnmeldungen in der Log.
Bin gerade noch dabei herauszufinden was die Ursache sein könnte.
Stelle nachher nochmal eine Log rein.
Was ich aber bereits feststellen konnte ist, dass es früher oder später ein Problem gibt wenn ich z.B. mit AD im Silo abkippen lasse. Wenn AD versucht die Abdeckung zu öffnen,  wird diese ganz schnell in einer Dauerschleife geöffnet und geschlossen. Der Anhänger wird dann nicht entleert. Das ist bisher bei einem Mod vom Krampe-Trailer und Krohne Sammel- und Ladewagen vorgekommen. Das seltsame ist nur, dass ich jedes Gespann 6-10mal im Einsatz habe, der Fehler aber immer nur bei einem Auftritt.

**Comment by TripleX1978** [comment]
@Axel32019 
Hier nochmal ein aktuelle Log.

[log.txt](https://github.com/Stephan-S/FS19_AutoDrive/files/6371752/log.txt)

Die Meldungen der Mods Fastrac 8330 und Ideal9 erscheinen erst seit ein paar Tagen.
Nutze diese Mods schon seit über einem Jahr und liefen bisher problemlos.

**Comment by Axel32019** [comment]
@TripleX1978 
Sehe keine AD-Fehlermeldungen im log.
Bitte versuch mal die automatische Abdeckungs-Einstellung auf aus zu lassen, tritt dann das Problem noch auf?
[info lp164311] Fastrac 8330 SPEED .... und [info lp11159] IDEAL 9T ... das kommt von CP

**Comment by TripleX1978** [comment]
@Axel32019 
Danke für die Info...werde es mal testen und berichten.
Vom Fastrac und IDEAL gibt es aber auch noch ein paar Errors...

Error (C:/Users/André/Documents/My Games/FarmingSimulator2019/mods/FS19_Agco_Ideal/IDEAL9.xml): Failed to update suspension node 1610048. Node does not exist anymore!

Error (C:/Users/André/Documents/My Games/FarmingSimulator2019/mods/fs19_MP_Fastrac8330_big/fastrac8330.xml): Failed to update suspension node 3149731. Node does not exist anymore!

Was hat es denn damit auf sich?
Tauchen auch erst seit kurzem auf.

**Comment by Axel32019** [comment]
@TripleX1978 Mit Suspensions kenn ich mich nicht aus, schau mal hier: https://gdn.giants-software.com/documentation_scripting_fs19.php?version=script&category=32&class=399

**Comment by Stephan-S** [comment]
Fixed in next release.
