### ISSUE TITLE
Entladen/Laden bei Flüssigkeiten / Unloading/Loading fluids

### ISSUE THREAD

**Issue by TripleX1978** [Stephan-S/FS19_AutoDrive#1861]
AutoDrive Version: 1.1.0.7

Beim Umladen von z.B Milch vom Fahrzeug in den Tank wird die Entladestelle angefahren, sobald der Trigger erkannt wurde wird abgeladen, dann fährt er das Stück bis zum eingestellten Zielpunkt und fängt wieder an zu laden.
Hab jetzt schon mehrere Milchtanks ausprobiert, bei allen das gleiche Verhalten.
Es spielt auch keine Rolle ob Traktor+Anhänger oder Lkw mit Tank.
Beim Beladen kommt es manchmal vor, dass der Zielpunkt angefahren wird aber nicht geladen wird.
Man muss dann ins Fahrzeug wechseln, die R-Taste drücken und danach wird geladen und abgefahren.

**Comment by 60erjonny** [comment]
Hallo

Kannst du mal hier von, ein Bild machen mit angezeigten Streckenpunkten...
Welches Silo ist das genau...?

**Comment by TripleX1978** [comment]
Es ist bei verschiedenen Silos der Fall, unter anderem bei dem Flüssigkeitssilo von FedAction.

Hier mal ein Screenshot von einer anderen Silo.

![image](https://user-images.githubusercontent.com/63108228/112737647-4443f680-8f5c-11eb-865f-21b0273e0bb4.png)

**Comment by RalfGorden** [comment]
hallo verschiebe mal den Abladepunkt(AD) weiter nach hinten,bei mir ging es dann

**Comment by TripleX1978** [comment]
Hatte ich auch schon alles versucht.

**Comment by 60erjonny** [comment]
Hallo
Hier mal mein Lager ( das von Fed )...bei mir fuktioniert es so...
![Screenshot (49)](https://user-images.githubusercontent.com/63659182/112745872-cc052180-8fab-11eb-9667-fd3735bbef15.png)
![Screenshot (50)](https://user-images.githubusercontent.com/63659182/112745879-d1626c00-8fab-11eb-968e-7815c91cfb4e.png)
Drücke F5 und mache bei Tag mit dem AD Kurs ein neues Bild davon...dann sieht man mehr...evtl. wenn möglich das Lager von der anderen Seiote anfahren...ein Versuch ist es wert...

**Comment by Axel32019** [comment]
@TripleX1978 Bitte mal mit Version 1.1.0.8 oder beta versuchen.

**Comment by TripleX1978** [comment]
@Axel32019 Hatte ich vorher auch schon aufgespielt, aber wieder deinstalliert...siehe #1860.
Vielleicht kannst mir da ja auch weiterhelfen bevor ich nochmal den ganzen Ärger habe.

**Comment by TripleX1978** [comment]
Nachdem ich alle Punkte nochmal neu gesetzt und verbunden habe scheint es jetzt zu funktionieren.
