### ISSUE TITLE
Autom. Aufladen nach Abladen

### ISSUE THREAD

**Issue by FendtFan1987** [Stephan-S/FS19_AutoDrive#1863]
Moin,
habe seit gestern die die neusten Versionen von AD und CP. Wenn ich mit AD den Ladewagen abfahren lasse lädt er im Futterlager (Kernstadt) ab aber direkt danach auch Gras wieder unter dem Laderohr ein?! Habe gestern etwas rumgespielt und kann den Fehler nicht finden, wäre sehr dankbar für Hilfe. Vorher lief es. LG

**Comment by Iwan1803** [comment]
@Axel32019 
den Fehler kann ich bestätigen. Nähere Details gerne in Discord.

**Comment by Axel32019** [comment]
Hallo @FendtFan1987 , Hast Du mal versucht den Zielpunkt hinter das Beladerohr zu verschieben, sodas der Anhänger bei Erreichen nicht darunter steht?
@Iwan1803 dito?

**Comment by Iwan1803** [comment]
Die Zielpunkte sind korrekt gesetzt. Das Problem ist, das mit einem Meter Abstand direkt hinter dem Abladetrigger direkt das Beladerohr kommt.
Der Fahrer lädt korrekt ab, fährt dann das Stück vor, lädt sofort wieder auf und erreicht dann den Zielpunkt.
Das passiert sowohl im Drescher- als auch im Abholen-/Liefernmodus.
![fsScreen_2021_04_01_00_34_03](https://user-images.githubusercontent.com/47528836/113219767-55ee0c80-9282-11eb-95e9-0d119071d3a6.png)
![fsScreen_2021_04_01_00_34_18](https://user-images.githubusercontent.com/47528836/113219768-57b7d000-9282-11eb-918f-35c3d2d06f6c.png)

**Comment by Schillershi** [comment]
Ich habe die AD Strecke andersrum verlegt...

**Comment by Iwan1803** [comment]
Damit er dann beim Abholen sofort wieder ablädt? 😉
AD dürfte nach dem Abladen nicht wieder beladen, bevor der Zielpunkt für das Abladen nicht erreicht worden ist (und umgekehrt).

**Comment by Schillershi** [comment]
Nein, das war als lösungsweg gedacht, bzw. Bis zu überbrückung, bis es eine Problemlösung gibt.

**Comment by 60erjonny** [comment]
Hallo
Hat nicht die Länge des Anhänger auch evtl. eine Auswirkung...?
![Screenshot (53)](https://user-images.githubusercontent.com/63659182/113297787-5a0a4080-92fb-11eb-8703-15bfbd566f1d.png)
![Screenshot (52)](https://user-images.githubusercontent.com/63659182/113297800-5e365e00-92fb-11eb-9c17-c01fb36b1fde.png)

**Comment by Axel32019** [comment]
@FendtFan1987 , @Iwan1803 Bitte mal mit der beta-Version überprüfen, da hat sich etwas geändert.

**Comment by FendtFan1987** [comment]
Moin
@Axel32019 so bin heute zum Testen gekommen und es funktioniert wieder einwandfrei mit der aktuellen beta ;) Danke!
