### ISSUE TITLE
Filllevel limiter

### ISSUE THREAD

**Issue by TheDukeOne** [Stephan-S/FS19_AutoDrive#1864]
Hallo, at first thx for this great mod. For a single player like me on 4x maps is a must have.

My request is a option to limit filllevels of transporters.

For example: i have a manure spreader with fillcap of 20000 liter and 2 transporters with 24000 and 26000 liter.
So now it would b cool to limit both transporters to 20000 liter. So that the transporter not waits when i tank over 20000 liter and left 4000 or 6000 liter. 

Hope you guys know what i mean. If not i could wright in german.
Anyway thx for the great mod.

**Comment by Iwan1803** [comment]
Maybe you should try this mod:
https://www.farming-simulator.com/mod.php?lang=en&country=de&mod_id=150303&title=fs2019

**Comment by TheDukeOne** [comment]
> Maybe you should try this mod:
> https://www.farming-simulator.com/mod.php?lang=en&country=de&mod_id=150303&title=fs2019

I know this mod. But it does not work with autodrive. When i adjust a limit they don't start after loading. Only when they are fully loaded.

**Comment by Stephan-S** [comment]
Sorry, I don't currently see a real need for this.
I don't want to include code and user interface just for that option.
