### ISSUE TITLE
Gülle Feldrandcontainer

### ISSUE THREAD

**Issue by gottdi** [Stephan-S/FS19_AutoDrive#1865]
Moin

meine frage ist kann man mit AD den Feldrandcontainer beladen ? ich fahre selber Gärreste auf den Feld und der Container steht am Feldrand .  Jetzt kommt der AD stellt sich daneben ,aber es passiert nichts . ich habe Manure System installiert .

mfg dirk

**Comment by Iwan1803** [comment]
AD kann mit den Schläuchen vom Manure System nicht umgehen.
