### ISSUE TITLE
Pfad berechnen bei großen Feldern

### ISSUE THREAD

**Issue by Machtl11** [Stephan-S/FS19_AutoDrive#1866]
Hallo, ich spiele auf der MVP 19 und habe alles dafür eingerichtet um auf Feld 5 Mais zu Häckseln. Am Anfang geht auch noch alles glatt doch dann wenn der Häcksler erst mal ein bisschen weiter weg ist, können die Abfahrer die Pfade zum Häcksler nicht mehr berechnen. Ich habe ums ganze Feld eine Blaue Linie gezogen, Da müssten sie ja ganz leicht drauf finden oder? Oder liegt es an etwas anderem?

MFLG Martin

**Comment by Mib83** [comment]
Hallo Martin habe ein ähnliches Problem.
https://github.com/Stephan-S/FS19_AutoDrive/issues/1850

**Comment by Franky72** [comment]
mach am Häcksler die gleichen Einstellungen wie beim Abfahrer dann findet er ihn auch, also auch Dreschermodus , Feld 5 und Z.B BGA
