### ISSUE TITLE
Train[BUG]

### ISSUE THREAD

**Issue by fuggo2** [Stephan-S/FS19_AutoDrive#1867]
**AutoDrive Version:** 1.1.0.8   
**Release or Custom Zip:** Release  
**Map (If applicable):** Dondiego  
**Vehicle / Type (If applicable):**   
**Multiplayer or Singleplayer:** Singleplayer  

**Describe the bug**  
Hello. i don't know how to put it in a BUG or question section!
 My question would be how to solve in AD that the train detects a gateway if it closes the barrier? bevan setting the collision detection is currently 4m but i tried every distance and always go for every vehicle that goes with AD, I tested that if i drive the vehicle then i can go through this but if i drive it still gets stuck as with the AD. Could you know of a solution?
Thanks for the reply

**If applicable - Steps to reproduce the behavior**  

**Screenshots**

**Comment by fuggo2** [comment]
yes i tried to drive there on the same barrier and i can't go through it

**Comment by fuggo2** [comment]
I just ran a test on another track as well, the situation is as follows. By setting the collision sensor to 4m, collision detection on, the AD will start to slow down for a moment with the barrier closed, but after that it will still want to go further and go to the barrier. when the train leaves, the AD-driven auto gets stuck on the barrier and overturns or gets stuck. I always led it to the barrier manually first, which I can’t manually cross if it’s locked.

**Comment by Axel32019** [comment]
Hello @fuggo2 , Some screenshots with F5 collisions shown would be helpful to understand the issue.

**Comment by fuggo2** [comment]
Okay, but what exactly does the f5 screenshot mean? for me, f5 doesn't do anything, maybe I can make a video of the collision, or do I need to set something on f5?

**Comment by Axel32019** [comment]
The default setting of collision height is 2m, which is to high for these barrier's - please set to 1.5 m and try again.
This might have other impact, i.e. stuck at road bump - it is somehow difficult to find a solution for all cases!

**Comment by fuggo2** [comment]
I see, thank you, I'll try. otherwise, I thought the distance was to be understood horizontally and not object height. I'll test it anyway! Thanks

**Comment by fuggo2** [comment]
> The default setting of collision height is 2m, which is to high for these barrier's - please set to 1.5 m and try again.
> This might have other impact, i.e. stuck at road bump - it is somehow difficult to find a solution for all cases!

helo, i finally tested the suggested value, it works now, the AD stops in front of the closed barrier, but like you said unfortunately it also stops on the roads if there is an ascent or a bridge in front of it. So I'm either looking for a flat map or I have no idea. But the solution worked
Thx
