### ISSUE TITLE
Fahrverbote / Driving bans

### ISSUE THREAD

**Issue by Chucky1982** [Stephan-S/FS19_AutoDrive#1868]
Hallo Stephan,

ich habe da ein Anliegen....
wäre es möglich Fahrverbote einzufügen? Zumindest nach Fahrzeug Typen?
Grund:
Ich habe mein Hof eher am Karten Rand, um an eines meiner Felder zu kommen such sich Autodrive immer brav den kürzesten Weg - was prinzipiell ja ne super Sache ist ABER.... :-)
Der Weg führt an einer Tankstelle vorbei und Durch eine kleine Ortschaft mit zwei Verkaufsstationen. Mit dem Traktor und Hänger nicht das Problem. Große Drescher hingegen bleiben in der Ortschaft immer entweder aufgrund der Breite oder mit dem Schneidewerkhänger stecken. Auch das Immer alle ganz brav über die Tankstelle abkürzen ist zwar ok, da dort zum Glück genug Platz ist, ist aber unschön.

Wäre es möglich auf Strecken, die, wenn es alternativen gibt zu Sperren? Das der Drescher erst gar nicht 
in die Ortschaft fährt sondern den Alternativweg? oder das der Tankstellen weg nur genutzt wird denn der Punkt angefahren werden soll?

Ich selbst bin ein großer Fan von Autodrive habe aber selbst null Ahnung von sowas und weiß daher nicht ob sowas überhaupt umsetzbar ist. Wäre aber echt Cool wenn Du es irgendwie hin bekommen könntest das bestimme Fahrzeuge oder Fahrzeug Typen gewisse Wege meiden würden.

Ich danke für deine Mühen und verbleibe mit höchstem Respekt vor deiner Arbeit mit Freundlichen Grüßen

Chucky

**Comment by 60erjonny** [comment]
Hallo

Versuche mal, bei der Einstellung maximaler Umweg den Wert zu erhöhen. Uns schau mal ob sich das bemerkbar macht...

**Comment by Chucky1982** [comment]
Hallo 60erjonny,
ja habe ich bereits versucht, leider will der Drescher dennoch nicht ums Dorf fahren auch bei maximalem Wert der Umweg-Einstellung. Trotzdem vielen dank für die Hilfe.

Grüße Chucky.

**Comment by eric4072** [comment]
Es sieht so aus als würde AD einen freien Weg durchs Dorf finden. Versuche mal beim Ortseingang einen Wegpunkt zu setzen, dann dürfte er bei max. Umweg-einstellungen nicht mehr durchfahren, ausser er findet keinen altenativen Weg...

**Comment by StukaRT** [comment]
Ergänzend dazu wäre es schön Wege "teurer" zu machen oder als Nebenstrasse zu deklarieren, so das AD nur dort einfährt wenn der Zielpunkt in der Strecke liegt oder keine alternative Route zu finden ist. Auf Karten wie Walchen mit vielen Waldwegen wäre das ein Segen, dass er für die Ziele die Hauptstrassen nutzt und wirklich nur in die Wald/Feldwege einbiegt wenn er dahin muss.

**Comment by wallsingham** [comment]
@StukaRT gerade für solche Maps mit vielen schmalen Wegen hatte ich mal Ausweichbuchten / Nebenstrecken als Lösung vorgeschlagen #1449 
Ich erstelle gerade die Kurse für die Italia Light Map und da vermisst man eine solche Lössung total.

**Comment by Chucky1982** [comment]
Hallo eric4072, 
ich habe das jetzt zwar nicht getestet aber ich bin mich dennoch recht sicher was passieren wird :-) Der Drescher wird um die Ortschaft rum fahren - genau was ich gerne hätte, ja. Aber... dann würden auch die Abfahrer das Dorf auch meiden und wären recht lange unterwegs, dass wäre wiederum nicht das was ich wollte.... In den Wald gebieten habe ich das so gelöst damit nicht Forstfahrzeuge nicht einfahren da auch dieser zwei Zugänge hat. Ein Verbot wäre hat einfach was schönes, richtig klasse wäre natürlich wenn man das für jedes Fahrzeug selbst wählen könnte (z.B. LKW 1 mit Kampe Hänger darf LKW 2 mit Tieflader ist zulange und darf nicht... Reichen würde mir aber eigentlich wenn man es Gattungen Verbieten könnte. wie zB LKW, Traktor, Auto, Drescher/Hechsler....) 
Meine Tankstellen durchfahrt hat sich geklärt. Ich hab die ganze Ecke neu eingefahren und jetzt geht es wunderbar - vielleicht hatte ich ein fehler im Streckennetz denn ich einfach nicht gefunden habe.....

**Comment by Stephan-S** [comment]
Wer möchte kann ja mal den neuesten beta branch testen. Dort kann man  nun explizit Nebenstraßen erstellen. Entweder neu aufnehmen indem man mit Mausrad nach oben auf den Aufzeichnen Button geht oder alte Strecken mit strg+alt gedrückt anklicken.

Die Wege sollten dann orange werden und ab dann als Nebenstraßen nur im Notfall befahren werden, wenns keinen anderen Weg gibt bzw. die anderen Wege sehr sehr viel länger wären

**Comment by wallsingham** [comment]
Tolle Sache . Danke dir @Stephan-S . Das werde ich gleich mal testen. Habe echt sehr lange auf sowas gewartet.

**Comment by wallsingham** [comment]
Ich habe auf der Felsbrunn getestet. Die Strecken werden tatsächlich nur dann  befahren wenn es keinen anderen Weg gibt.
Sie werden nicht befahren wenn es einen anderen Weg gibt der nur etwas länger ist.
Auch das Händling ist fehlerfrei. Wenn ein Wegepunkt aus einer grünen oder blauen Strecke mit Strg+Alt angeklickt wird, werden alle abgehenden Verbindungen orange. Mir ist nur aufgefallen dass wenn ein Wegepunkt aus einer blauen Strecke mit Strg+Alt angeklickt wird,  die blauen Strecken stehenbleiben und man erkennt nur schwer dass "darunter" noch die orangene Strecke sich befindet. Das könnte vielleicht noch verfeinert werden. 
Alles in allem eine super Lösung die auf Anhieb funktioniert. Und auf jeden Fall eine gute Grundlage für noch mehr in dieser Richtung.

**Comment by iljarogoff** [comment]
Tolles Feature, hoffentlich findet es bald Einzug ins Release. Was mir aufgefallen ist, wenn ich Kreuzungspunkte str-alt-klicke, werden alle abgehenden orange - leider auch der, der eigentlich bspw geradeaus weitergeht und eigentlich grün bleiben sollte.
