### ISSUE TITLE
Rückwärts einparken

### ISSUE THREAD

**Issue by KarlGutenberg** [Stephan-S/FS19_AutoDrive#1869]
AutoDrive Version: <version>1.1.0.9-RC1</version>
    
Release or selbsterstelltes zip: Release
Karte (falls relevant): <MapName>NF_Marsch_4fach_V2_7</MapName>
Fahrzeug(art) (falls relevant):

**Beschreibe den Bug**
Folgendes Problen:
Ich habe (siehe Bild) eine Parkroute auf der Hagenstedt erstellt
![Screenshot (3)](https://user-images.githubusercontent.com/78603817/113418515-eed97080-93c5-11eb-8dea-ab1eae314894.png)
Hier fährt der Traktor vom Feld unter das Dach und wenn ich möchte auch wieder zum Feld!
Alles gut

Aber auf der NF_Marsch_4fach_V2_7 sieht das anders aus
![Screenshot (4)](https://user-images.githubusercontent.com/78603817/113418807-7de68880-93c6-11eb-8e13-35bdb9cd0868.png)

Da fährt der Traktor zwar auch unters Dach, aber wenn ich ihn dann zum Feld entsende
fährt er erst raus bis zum Ende, dann wieder unters Dach und dann erst auf die Feldlinie!
Was mache ich falsch?

Auch habe ich die Gleiche Route wie auf der Hagenstedt 
eingefahren, gleiches Problem

Ich habe mal ein Video gemacht:
https://youtu.be/aRKxuebO-KU
https://youtu.be/VYBBqUX11xc

Danke! Habe ich alles richtig gemacht?

**Comment by 60erjonny** [comment]
Hallo

1. Deine Video`s kann ich nicht abspielen...???
2. Die Bilder deuten aber schon, auf verschiedene Routen hin und nicht auf " Gleiche Route " ...???
3. Wo ist eigentlich das Problem, es ist eben nur ein " Schöhnheitsfehler ", den hatte ich auch mal...
4. Ich habe mit das Video von Ivan1803 meine Parkkurse neu eingefahren...musst du dir mal ansehen...!    
   https://www.youtube.com/watch?v=nWL6UYMYzq0

**Comment by KarlGutenberg** [comment]
Zu 1. Verstehe ich nicht das du die Video´s nicht abspielen kannst!
         Ich kann sie beim klick auf dem Link jedenfalls abspielen
Zu 2. Ja sicher sind das zwei verschiedene Routen! (Lesen)
         Das eine Bild (1) ist aus der Hagenstedt wo alles Funktioniert wie es soll
         Das andere aus der NF_Marsch Bild (2) wo es mit Schönheitsfehler funktioniert.

**Comment by KarlGutenberg** [comment]
So Video´s sollten jetzt gehen!
Sorry

**Comment by 60erjonny** [comment]
Hallo

Lesen ??? Habe ich...
Zitat: Auch habe ich die Gleiche Route wie auf der Hagenstedt
eingefahren, gleiches Problem...
Mich würde ja die Route interessieren, wo du nicht weißt warum es so ist...
Nun, egal...schaue dir das Video von Ivan1803 an...musst du etwas suchen...da wird es anders eingefahren...

**Comment by KarlGutenberg** [comment]
Route NF_Marsch Bild 2 funktioniert nicht, 
auch wenn ich die Route so einfahre wie auf Bild 1

**Comment by 60erjonny** [comment]
Hallo

Und genau "das" hätte ich gern gesehen...in Video oder Bild...

**Comment by KarlGutenberg** [comment]
> Hallo
> 
> Und genau "das" hätte ich gern gesehen...in Video oder Bild...

Siehe dir doch das Video an! sind beide von er NF
Einmal wie der Traktor reinfährt
Einmal wie er rausfährt (wo er vor und wieder zurück fährt)
Oder meinst du wo es Funktioniert (Hagen)

**Comment by 60erjonny** [comment]
Hallo

Genau, ich meine die " Hagen-Version" auf der Marsch...
Aber versuche doch Mal meine Version...mit der blauen Linie...!

**Comment by KarlGutenberg** [comment]
Auf der Hagen geht es jetzt merkwürdigerweise auch nicht mehr! Liegt es an der neuen Version?
Ich werde mal die Versionen austauschen!
Wenn es wieder geht, mach ich ein Video
Ja ich mach mal mit der blauer Linie.

**Comment by KarlGutenberg** [comment]
Video 1 Hagen funktioniert mit v1.1.0.7
https://youtu.be/XMHSAicW6_Q

Video 2 Hagen  funktioniert nicht mit v1.1.0.9 RC neuste Version
https://youtu.be/pdZsBxtns-o

**Comment by KarlGutenberg** [comment]
Funktioniert nicht

60erjonny ***@***.***> schrieb am Sa. 3. Apr. 2021 um 15:21:

**Comment by KarlGutenberg** [comment]
Lade grade hoch mit blauer linie
https://youtu.be/Pxhh92ZQrVc

**Comment by 60erjonny** [comment]
Hallo

Für meine Geschmack ist die blaue Linie noch zu kurz...siehe auch mein Bild...aber es ist doch schon etwas besser geworden, er fährt nicht mehr in den Unterstand...

**Comment by KarlGutenberg** [comment]
Das stimmt
Ich mach morgen noch ein Versuch und ein Video
Bis dann

60erjonny ***@***.***> schrieb am Sa. 3. Apr. 2021 um 18:09:

**Comment by 60erjonny** [comment]
Hallo

Gut, dann lage es nicht an der Version...aber wie ich vermutet habe, an der etwas zu kurzen Strecke...

**Comment by KarlGutenberg** [comment]
Hallo,
kann geschlossen werden!
Danke.
MfG
