### ISSUE TITLE
MODE PICK UP AND DELIVER

### ISSUE THREAD

**Issue by garo73** [Stephan-S/FS19_AutoDrive#1870]
Thank you all for the work you are doing! I would like to report a problem I have: farm silo unloading point, field 1 loading point, at the loading point I have a mother bin overloader that is supplied by other overloaders. The track is correct, the truck with the trailer goes to both points without error but, it never does it cyclically, I always have to start it from each point or it doesn't load or unload and then it continues cyclically! what am I doing wrong??? Thanks!

**Comment by Axel32019** [comment]
Hello @garo73 , Some screenshots, AD version, map would be helpful to understand the issue

**Comment by garo73** [comment]
> 
> 
> Hello @garo73 , Some screenshots, AD version, map would be helpful to understand the issue

Yes you are right! My aplogize!
AD version 1.1.0.8, map Western Australia 16x and MOD test map, mother bin Coolamont... after some test without any other mod, AD works... now try to find mod conflict!

**Comment by garo73** [comment]
Maybe there is something with this truck:

FS19_DATREECUTTER_T408SAR

**Comment by Axel32019** [comment]
Try to change the xml:
``<vehicle` type="tractorT408">``
to
``<vehicle type="tractor">``

**Comment by garo73** [comment]
> 
> 
> Try to change the xml:
> `` <vehicle` type="tractorT408"> ``
> to
> `<vehicle type="tractor">`

Ok! I try as soon as possible and refer! Thanks!

**Comment by garo73** [comment]
> 
> 
> Try to change the xml:
> `` <vehicle` type="tractorT408"> ``
> to
> `<vehicle type="tractor">`

no, it doesn't work!

**Comment by Vegtvet** [comment]
I got the same problem with the exact same truck. And it is the truck itself that is causing the problem. I tried to run the same course with the same trailer (BSM semi tipper), but with the Warrior in game truck, and it worked perfectly. Removing "t408" didnt work for me either. I am using AD version 1.1.07, and the map I am playing on is Western Australia 4X.

**Comment by garo73** [comment]
> 
> 
> I got the same problem with the exact same truck. And it is the truck itself that is causing the problem. I tried to run the same course with the same trailer (BSM semi tipper), but with the Warrior in game truck, and it worked perfectly. Removing "t408" didnt work for me either. I am using AD version 1.1.07, and the map I am playing on is Western Australia 4X.

Yes, is the FS19_DATREECUTTER_T408SAR the problem, i try with MOD Test Map, Western Australia 16X, Millennial Farm Map, AD version 1.1.0.7 and 1.1.0.8!

**Comment by Axel32019** [comment]
I do not see this as a bug of AD -> closed.
