### ISSUE TITLE
Rotierend Be-/Entladen mit Wiederholungen / Rotate load/unload with repetitions

### ISSUE THREAD

**Issue by TripleX1978** [Stephan-S/FS19_AutoDrive#1871]
AutoDrive Version: 1.1.0.7

Beispiel:
Ich möchte bei Punkt A beladen und bei B und C im Wechsel entladen und das ganze 4mal wiederholen und danach zurück zur Parkposition.
Läuft auch alles soweit bis auf das zurückfahren zur Parkposition.
Die Punkte werden in einer Endlosschleife immer wieder angefahren.
Noch zur Info...es kann nicht immer zu 100% bei B und C abgeladen werden. 
Wie sollte es denn bei 4 eingestellten Wiederholen richtigerweise ablaufen?
Wäre eine Wiederholung einmal den Ordner kompletten durchrotieren oder würde jeder Zielpunkt als eine Wiederholung zählen?
Das gleiche Problem habe ich auch wenn ich bei mehreren Punkten beladen und nur bei einem entladen.

**Comment by TripleX1978** [comment]
Update:

Ich habe an meinem Streckennetz nochmal was verändert und wieder die 1.1.0.8 aufgespielt.
Zu dem bereit oben beschriebenen Problem habe ich jetzt noch eins bei einer anderen Route.

Ich habe 2 Produktionen Flüssigdünger am laufen.
Wenn ich Dünger vom Silo zu Produktion A bringe funktioniert das.
Das gleiche wenn ich zur Produktion B liefere.
Wenn ich jetzt beide Produktionen in einen Ordner packe um rotierend zu beladen, fährt der Traktor zwar zum Silo, lädt dort auf, fährt dann noch ein Stück weiter zum entsprechenden Beladepunkt am Silo und gibt mir dann die Meldung aus, dass er keinen Weg zum Silo finden kann.
Wenn ich AD dann neu starte findet er den wieder.

![LS19 - Screenshot 9](https://user-images.githubusercontent.com/63108228/114165437-c654f780-992c-11eb-8bfd-ee610d60ca9c.jpg)

**Comment by Axel32019** [comment]
@TripleX1978 Bitte mal mit der beta Version von heute probieren.

**Comment by TripleX1978** [comment]
@Axel32019 Ist das der Stand von vor 16 Stunden?

**Comment by Axel32019** [comment]
@TripleX1978 Heute neu runterladen bitte! Hab gestern einiges geändert.

**Comment by TripleX1978** [comment]
@Axel32019 Dann musst du mir mal auf die Sprünge helfen. Wenn ich über den Link zur Beta gehe finde ich den letzten Eintrag vor 22 Stunden. Kannst du mir den Link evtl. hier mal einstellen?

**Comment by TripleX1978** [comment]
@Axel32019 Ich steh jetzt gerade auf der Leitung glaube ich. Bin über den Fall gegangen. Wenn ich dann auf den Link klicke, ist der letzte Eintrag von gestern und der heißt auch nicht, wie vorher beschrieben, "FS19_AutoDrive-beta-testing.zip" sondern nur "FS19_AutoDrive.zip"

**Comment by Axel32019** [comment]
@TripleX1978 ??? Einfach die Schritte ab "Wie bekommt man die BETA:" durchführen.

**Comment by TripleX1978** [comment]
@Axel32019 Hab den grünen Code-Button oben rechts übersehen.:-)
Ich habe jetzt wie beschrieben heute die Beta runtergeladen und im Mod-Ordner ausgetauscht.
Wenn ich das Spiel starte, erscheint AD auch in bei den installierten Mods.
Wenn ich jetzt meinen Spielstand starten möchte bekomme ich den Hinweis, dass dieser Autodrive verwendet, es aber nicht installiert ist. Wenn die Meldung dann übergehe steht AD in der Mod-Liste des Spielstands nicht mehr drin.

**Comment by Axel32019** [comment]
@TripleX1978 Bitte mal die log posten.

**Comment by TripleX1978** [comment]
@Axel32019 
[log.txt](https://github.com/Stephan-S/FS19_AutoDrive/files/6406339/log.txt)

**Comment by Axel32019** [comment]
@TripleX1978 Ich vermute mal Du hast die zip-Datei direkt in den mod-Ordner kopiert - das funktioniert für die beta nicht.
Wie es geht siehe hier #1276 Code -> Download ZIP

**Comment by Axel32019** [comment]
@TripleX1978 Bitte füge mal die FS19_AutoDrive.zip hier ein die Du verwenden möchtest.

**Comment by TripleX1978** [comment]
@Axel32019 Hier die Daten.

[FS19_AutoDrive.zip](https://github.com/Stephan-S/FS19_AutoDrive/files/6409437/FS19_AutoDrive.zip)

**Comment by Axel32019** [comment]
@TripleX1978 Du hast ein Unterverzeichnis im zip, daher wird das nicht gefunden. Bitte ohne einpacken.

**Comment by TripleX1978** [comment]
@Axel32019 Jetzt läuft es.
Das mit dem Be- und Entladen scheint jetzt auch einwandfrei zu laufen.
Der Fahrer fährt die einzelnen Zielpunkte der Reihe nach ab, wenn er leer ist geht es zum Silo beladen.
Die Anzahl der Wiederholungen, die man einstellt sind also die Anzahl wie oft am Silo beladen werden soll?

**Comment by Axel32019** [comment]
@TripleX1978 Ja, die Wiederholungne sind die Anzahl der Beladungen.

**Comment by TripleX1978** [comment]
@Axel32019 Wie erfährt man denn ob eine neue Beta-Version vorhanden ist und was sich da geändert hat?
Was hat es denn mit dem Blue-Line-Route-Finder auf sich?
Der ist glaube ich neu.

**Comment by Axel32019** [comment]
@TripleX1978 Dies ist ein neuer Algorithmus zur Routenfindung über blaue Verbindungen - noch im Test, daher als Option.
Ich denke mal das ursprüngliche Thema ist damit auch geklärt -> closed.
