### ISSUE TITLE
höhe von wegpunkten - elevation of waypoints

### ISSUE THREAD

**Issue by sashaman** [Stephan-S/FS19_AutoDrive#1873]
nachdem versinkende wegpunkte immer wieder mal problematisch sind hier viell. 2 lösungsansätze

1. vorschlag: eine tastenkombination die es erlaubt, einen wegpunkt ohne änderung der höhe zu verschieben, also sozusagen mit gesperrter y achse - das würde in vielen fällen schon ausreichen oder zumindest hilfreich sein
2. vorschlag: ist die maus über dem wegpunkt dann mit (viell. shift-)mousewheel in der vertikalen rauf und runter verschieben

![2021-04-06_171910](https://user-images.githubusercontent.com/1388895/113737469-57925700-96fe-11eb-96ca-878d1079ab43.jpg)
lG

**Comment by Iwan1803** [comment]
Sauberer (und einfacher) wäre es natürlich, einfach die Wegpunkte zu löschen und neu einzufahren.

Interessant wäre mal zu wissen, warum er beim Aufzeichnen die Straße/Brücke als Höhe erkennt, beim Verschieben aber nicht.
Ich denke mal, das beim Aufzeichnen das Fahrzeug die entscheidende Rolle spielt.

**Comment by sashaman** [comment]
ja was jetzt besser oder weniger gut wär sei jetzt mal dahingestellt, 
es geht ja rein um die möglichkeit bzw. machbarkeit des editierens der höhe wegpunkte 
weshalb das beim aufzeichnen klappt kann ich nicht wirklich beurteilen, viell. benutzt er da als referenzpunkt die höhe auf der sich das fahrzeug bewegt?

**Comment by sashaman** [comment]
p.s. was mal als "bug" gefixt wurde war das springen von wegpunkten zum fahrzeug wenn ein wegpunkt mit mw-click gegrabbed wurde, 
vielleicht kann man das als so ne art feature einbauen, also mw-click setzt den waypoint zum fahrzeug, damit ließe sich ein verschwinden im grund auch überlisten

**Comment by Stephan-S** [comment]
Ist jetzt im alpha-branch so eingebaut.
LShift beim Verschieben -> Höhe bleibt
