### ISSUE TITLE
[BUG Beta] Failed to open xml (modDesc.xml)

### ISSUE THREAD

**Issue by BlackStar153** [Stephan-S/FS19_AutoDrive#1874]
Fehler in der Betaversion

Error: Failed to open xml file 'C:/Users/OneDrive/Dokumente/My Games/FarmingSimulator2019/mods/FS19_AutoDrive/modDesc.xml'.
Available mod:  FS19_AutoDrive

**Comment by Tom20214** [comment]
logfile?

**Comment by Axel32019** [comment]
Hello @BlackStar153 , Please add the downloaded file here.

**Comment by Axel32019** [comment]
Hallo @BlackStar153 , Funktioniert es wieder oder nicht?

**Comment by Tom20214** [comment]
@Axel32019  Also bei mir funktioniert die Beta Version einwandfrei!
