### ISSUE TITLE
[Feature Request]

### ISSUE THREAD

**Issue by rento112** [Stephan-S/FS19_AutoDrive#1875]
Would it be possible to setup multiple  refill points to be selected on the Loading option. I'm using a Seeder/Planter that has 2 fill options, seeds and fertilizer. Would it be possible to have a load option to do both? Or will  I need to rely on Course play for this?

**Comment by Mannie313** [comment]
Es geht doch mit AD. Man darf Saatgut und Dünger Ladestation nicht zu nahe aber auch nicht zu weit auseinander stellen.

MFG Mannie313

**Comment by Iwan1803** [comment]
Oder man nutzt ein Silo, was beides kann.

**Comment by rento112** [comment]
It would seem that works, but it's a bit finicky. The second fill doesnt trigger much, making it move past the trigger point. It ends up filling a tiny bit or not at all.

**Comment by jobyrns72** [comment]
Definitely be helpful to load at two locations for filling for seed and fertilizer in one trip

**Comment by Axel32019** [comment]
I can not understand the issue. If 2 fill stations are in silo trigger range they will be used to fill seeds and fertilizer.
You may post (some) screenshot here to help to understand.

**Comment by crcarmichael** [comment]
> I can not understand the issue. If 2 fill stations are in silo trigger range they will be used to fill seeds and fertilizer.
> 
> You may post (some) screenshot here to help to understand.

Example: My seed dispenser and my liquid fertilizer dispenser are in different locations.  My seeder can only be set to refill at one of these.  

In the event that they're close together, it seems that both get refilled regardless of wether seed or fert is selected.

**Comment by Stephan-S** [comment]
Hey, I understand what you want here, but for now we will only allow the one target location for simplicity and usability reasons.
So you will have to make due with what AutoDrive currently offers in that regard.
