### ISSUE TITLE
[BUG] 1.1.0.8 - Truck stops after unloading in silo

### ISSUE THREAD

**Issue by Firebuster1974** [Stephan-S/FS19_AutoDrive#1877]
**AutoDrive Version:** 1.1.0.8   
**Release or Custom Zip: downloaded yesterday from GH  
**Map (If applicable):** All  
**Vehicle / Type (If applicable): Semi & Tractors 
**Multiplayer or Singleplayer:** Singleplayer  

**Describe the bug**  
After the Update from 1.1.0.7 to 1.1.0.8 the Unloader is not leaving the silo after unloading, after the unloading the unloader drives the last few meters to the defined spot and stops. After clicking the double arrow in the GUI the unloader is back on track.

**If applicable - Steps to reproduce the behavior** - ALL the time

**Comment by Axel32019** [comment]
Hello @Firebuster1974 , Please provide some screenshots from the situation and attach the AutoDrive_config.xml and vehicles.xml, renamed to .txt here.

**Comment by Nik0194** [comment]
Same thing is happening to me when the unloader goes to the sell point, it just stops after it's done unloading and doesn't loop

**Comment by Stephan-S** [comment]
No input from user -> Closed.
