### ISSUE TITLE
[Question] Fehler beim DL der Beta-Version

### ISSUE THREAD

**Issue by andreasthu** [Stephan-S/FS19_AutoDrive#1878]
**Question:**   
I've got a question...
Hallo Leute
ich kann zwar die Beta version vom AD runterladen, beim öffnen bzw entpacken per winrar kommt aber eine Fehlermeldung, und der Inhalt ist nicht vollständig:
![error](https://user-images.githubusercontent.com/24860501/114259875-901d8380-99d1-11eb-8f64-e60611b396ba.png)
die zip enthält nur die .github und Autodrive CourseEditor Ordner und die .gitignore
der Autodrive Ordner selber fehlt.
auch hat die zip nur 28.346 KB, sollte die normal nicht so um die 50-60MB haben?
lade mir schon monatelang die beta ist mir aber so noch nie passiert.
lg
andreas

**Comment by 60erjonny** [comment]
Hallo
Habe es auch versucht zu downloaden und kann es nicht bestätigen oder es wurde schon behoben...

**Comment by Axel32019** [comment]
Hallo, auch gerade versucht und kein Problem festgestellt mit Firefox 87.0

**Comment by andreasthu** [comment]
Ok, danke für die info. 
Hatte es mit ca 10x chrome gemacht.
Probiere es einmal mit edge.
Bin derzeit auf reha und hab arg langsames Internet, 60kb/s, dauert immer extrem lang der dl.
Ev ist es wegen dem.
Lg
Andreas
