### ISSUE TITLE
Wages?

### ISSUE THREAD

**Issue by stangman04** [Stephan-S/FS19_AutoDrive#188]
Does the Autodrive use the in game hired worker back end at all that charges wages? I think I saw wages being paid for using autodrive, is there any way to turn that off? Just curious.

**Comment by docgaming** [comment]
yes now AD pays there workers. you can change there wages in the settings menu.

**Comment by stangman04** [comment]
Thanks, I must have an old version since I don't see that option in settings. I will try to update.

**Comment by stangman04** [comment]
Yup, I was on version 1.0.1.9 from the modhub. I downloaded 1.0.2.5 from github and many more settings now including wages. Closing this.
