### ISSUE TITLE
Autom. Nachfüllen von Kalk und Dünger / Automatic refill lime & fertilizer

### ISSUE THREAD

**Issue by TripleX1978** [Stephan-S/FS19_AutoDrive#1880]
AutoDrive Version: 1.1.0.8

Wenn Kalk/Dünger auf dem Feld aufgebraucht sind kommt immer die Meldung, dass kein Weg zum Zielpunkt (Silo) gefunden wurde.
Es gibt dann 2 Möglichkeiten.
1.) In 90% der Fälle - Wenn ich dann manuell AD nochmal starte ohne das Fahrzeug bewegt zu haben, wird das Ziel sofort gefunden
2.) In 10% der Fälle - Ich muss das Fahrzeug vom Feld fahren und dann AD aktivieren damit das Ziel gefunden wird.

**Comment by 60erjonny** [comment]
Hallo
Etwas zu wenig Info`s...
Welche Karte?
Passiert das auf allen Feldern so...?
90% + 10%  = 100% ...Er fährt wirklich also nie automatisiert ab zum auffüllen...?
welche Fahrzeuge ...? Sind das Standart oder Mod...?

**Comment by Iwan1803** [comment]
Du hast 3 Issues geöffnet und in allen 3 fehlen Infos. Wie sollen wir helfen, wenn wir nicht mal ausreichende Infos bekommen, obwohl das auch schon im Template steht?
Wir brauchen Infos zur Map, den Fahrzeugen, Infos zum Feld (Fanglinie drumherum?), welcher AD-Modi und welche AD-Einstellungen, etc.

**Comment by TripleX1978** [comment]
Hallo!
Hier noch ein paar Infos.

AD : 1.1.0.8 (1.1.0.6/7 funktionierten ohne Probleme)
Map : NF Marsch 4-fach 
Betroffene Felder : 2, 3, 4, 16 (46 funktioniert z.B. einwandfrei)
Fanglinie : umlaufend
Fahrzeug-Mods : 900er Fendt + Anhänger (siehe Anhang)

Auf den betroffenen Feldern fährt er nie von alleine zum Auffüllen.

https://www.modhoster.de/mods/fendt-pack-oy
https://ls-portal.eu/de/new-leader-nl345-john-deere-dn345/

![LS19 - Screenshot 10](https://user-images.githubusercontent.com/63108228/114531496-3eccf880-9c4c-11eb-9a6b-64cb9aebae5e.jpg)

**Comment by Axel32019** [comment]
Hallo @TripleX1978 ,
Wenn der Abfahrer auf F46 funktioniert, auf den anderen aber nicht würde ich mal prüfen ob er überhaupt von den Feldern findet.
Wenn nicht Streckennetz prüfen, Fruchtumfahrung / Feldbegrenzung mal testweise deaktivieren.

**Comment by 60erjonny** [comment]
Hallo @TripleX1978 

Die Map ist die Marsch, ja da bin ich auch zu Hause. Nun habe es hier auch getestet, mit den angegebenen Mod`s.
Ich glaube nicht das es am Streckennetz liegt, auch denke ich nicht, das man das auf bestimmte Felder begrenzen kann.
Hatte mit meinen Test auf F46 auch Probleme...
Nun meine ich auch, es liegt nicht an AD oder CP, wenn dann vieleicht indirekt.
Ich vermute es liegt am Fendt-Pack, der ist auch schon mit den neuesten Update über 1,5 jahre alt.
Mit Standart-Fendt haber ich aber keine Probleme. Das habe ich gerade getestet und mir liegen dabei auch noch weitere Erfahrungen von ein paar tausend Missionen auf der Marsch vor.
Ja gut es ging mit Ad 1.1.0.6/7 Version wie du schreibst, aber auch hier bitte bedenken mit welche CP-Version war das...
Den die spielt ja hier auch eine Rolle und ist entscheidend.
Vieleicht ist ja nur CP an den Problem daran Schuld, denn evtl. übergibt CP nicht sauber an AD und da hackt es.
Aber nochmal, mit den Standart-Fendt geht es bei mir, also dann doch wieder nicht...CP...AD...???
Ok, es geht nicht immer problemlos...aber ein Eingreifen ist auch hin und wieder nötig, bleibt ja ein Spiel...oder...
Nun, versuche mal einen andern Traktor und versuchte dein Glück...

**Comment by TripleX1978** [comment]
@60erjonny @Axel32019 Hab jetzt die Beta aufgespielt. Die Felder die ich bisher testen konnte funktionieren nun.
