### ISSUE TITLE
Autom. Nachfüllen von Saatgut bei Amazone Condor / Autom. refill of seed Amazone Condor

### ISSUE THREAD

**Issue by TripleX1978** [Stephan-S/FS19_AutoDrive#1881]
AutoDrive Version: 1.1.0.8

Beim autom. Nachfüllen von Saatgut wird nur bis 90% aufgefüllt.
Danach bleibt das Fahrzeug stehen und fährt nicht mehr zurück zum Feld.
Wenn ich dann manuell bis 100% auffülle und AD danach wieder aktiviere fährt er das Silo erneut an um nachzufüllen und bleibt dann wieder stehen.
Düngefunktion ist in CP ausgestellt und der Tank für Dünger ist leer.

**Comment by 60erjonny** [comment]
Hallo
Auch hier dürftige Info`s von dir...
Ein Bild mit den Kursen von der Stelle, von wo du auffüllen willst, wäre gut.
Karte,Standartfahrzeuge, Mod`s...
Generell im ein Problem oder nur hin und wieder ?
Andere Sähmaschine versucht...?...eine ohne Düngefuktion...

**Comment by Axel32019** [comment]
siehe #1884
Wenn der Level beim Auffüllen nicht erreicht wird, geht's nicht zum Feld.
Screenshot?

**Comment by Iwan1803** [comment]
siehe #1880 
Liefere Infos oder wir können dir nicht helfen.

**Comment by TripleX1978** [comment]
@Axel32019 : Danke für die Infos. Hab die Werte für "Abladen ab Level" nochmal geändert und jetzt scheint es zu laufen.

**Comment by andreasthu** [comment]
Mit abladen ab 100% habe ich dieses problem auch manchmal.
Ich stelle das immer auf abladen ab 99%, dann funktioniert es immer.
Lg 
Andreas
