### ISSUE TITLE
[Question] Server meldet getIsClient=true

### ISSUE THREAD

**Issue by Dragonfly1982** [Stephan-S/FS19_AutoDrive#1882]
Hallo, habe eine Frage wegen Ad.
Info: [AD] Info: g_server table: 0x022ee38b6c28 g_client table: 0x022ee38b6f40 g_dedicatedServerInfo table: 0x022edce8b440 getUserProfileAppPath C://gameservers//s1397242//ls2019//gameProfile/ **getIsClient true getIsServer true isMasterUser true**

Ist es normal das auf einem Server getIsClient true ist, da es eigendlich ein Server ist und kein Client.
Hoffe ihr könnt mir Helfen.

Mit freundlichem Gruß

**Comment by Axel32019** [comment]
Hallo @Dragonfly1982 , Das sind die Mysterien des LS / Dedi-Server etc.  - macht uns immer mal wieder das Leben schwer.
Ja, ein Dedi meldet sich auch als "Client".
