### ISSUE TITLE
[Question] Wie entscheidet AD ob vor dem Ansäen aufgefüllt werden muss

### ISSUE THREAD

**Issue by TripleX1978** [Stephan-S/FS19_AutoDrive#1884]
Wann schickt AD eine Sämaschine zum Auffüllen?

Folgendes ist passiert.

1.) Meine Sähmaschine ist nur noch zu 15% gefüllt und das Feld ist mittelgroß.
     AD beginnt direkt mit dem Ansäen und die Menge hat auch gerade so gereicht.

2.) Meine Sähmaschine ist zu 78% gefüllt und das Feld ist ähnlich groß wie das vorige.
     AD schickt das Gespann erst zum Auffüllen. 

Ich komm noch nicht ganz dahinter wann AD die Entscheidung trifft, dass aufgefüllt werden muss.
Kann man das irgendwie beeinflussen?

**Comment by 60erjonny** [comment]
Hallo
Wenig Info`s dafür...
Und soweit ich weiß beginnt nicht AD die Ansaat sonder CP oder...?
Und CP schickt dann wieder zu aufüllen zurück, das AD dann wohl übernimmt...
Ist in beiden Fällen, vom selben Punkt aus angefangen worden?
Hast du das Gespann am Hof losgeschickt mit Ad...?
Warst du da jeweils näher zum Silo oder zum Feld?
Und hast du da die selbe Frucht angesäht ?
Diese beiden Fälle sind hier sehr ungenau beschrieben und evtl. so auch nicht vergleichbar...

**Comment by Axel32019** [comment]
Hallo,
Folgendermaßen wird entschieden:
- Gesamt-Füllstand (%) > Abladen ab Level -> zum Feld
- Gesamt-Füllstand (%) < Abladen ab Level -> zum Beladen

**Comment by Iwan1803** [comment]
AD entscheidet höchstens auf dem Weg zum Feld, ob nachgefüllt werden muss oder nicht (richtiger Modus vorausgesetzt = Abholen). Die Berechnung hat Axel ja aufgeführt.
Da AD keine Feldarbeit beherrscht, kommt hier wohl ein Helfer zum Einsatz (CP, AIVE, etc.). Wenn dieser aktiv ist, ist AD pausiert bzw. abgeschaltet. Diese Helfer reaktivieren AD normalerweise erst dann, wenn der Tank leer ist (so kenn ich es zumindest von CP).

**Comment by TripleX1978** [comment]
Danke für die Info.

@Axel32019 : Mit Gesamtfüllstand ist also Dünger + Saatgut gemeint?

**Comment by Axel32019** [comment]
@TripleX1978 Genau.
