### ISSUE TITLE
Warum kann der Fahrer keinen Weg zum Ziel berechnen?

### ISSUE THREAD

**Issue by TripleX1978** [Stephan-S/FS19_AutoDrive#1885]
Warum kann der Fahrer keinen Weg zum Ziel berechnen?

AD 1.1.0.8

Von der Hauptroute geht ein Abzweig in Richtung Silo ab.
Nach dem Entladen fährt der Fahrer noch bis zum Zielpunkt und gibt mir dann die Meldung aus, dass kein Weg zum Ziel gefunden wurde.
Egal wie ich den Abladepunkt verschiebe oder wie groß oder klein ich die Ausfahrkurve ziehe, es passiert nichts.
Ein Silo daneben funktioniert es, auch wenn dann nicht dem Kurs gefolgt wird sondern geradeaus über das nächste Silo gefahren wird. Aber zumindest findet er sein Ziel, was übrigens das gleiche ist.
Setze ich den Fahrer auf die Hauptroute findet er sein Ziel sofort.

![LS19 - Screenshot 12](https://user-images.githubusercontent.com/63108228/114710701-54b2ea00-9d2e-11eb-8503-7139f1e943a3.jpg)

**Comment by 60erjonny** [comment]
Hallo
Du versuchst das Problem an der falschen Stelle zu lösen.
Die Punkte zu verschieben bringt gar nichts.
Und das auf der Hauptroute weiter fährt, hat ja nichts damit zu tun.
Wichtig ist die Anbindung an die Hauptroute und das sieht man auf den Bild leider nicht genau...

**Comment by Axel32019** [comment]
Hallo @TripleX1978 , Stimme @60erjonny zu: Entscheidend sind die Verbindungen die vom HUD verdeckt sind!

**Comment by Iwan1803** [comment]
Stell mal einen Trecker aufs Silo und starte AD. Klappt das nicht, dann der Linie 1 Wegpunkt weiter folgen und erneut probieren. Irgendwo wird da wohl ein Fehler im Streckennetz sein.
Wenn man Strecken nicht aufzeichnet sondern selber die Wegpunkte setzt, passiert es ganz leicht, das man welche einfach mal in die falsche Richtung verbindet.

**Comment by TripleX1978** [comment]
Hallo zusammen,

habe nochmal was experimentiert.

@60erjonny , @Axel32019 : hier nochmal ein Screenshot mit den Anbindungen.

![LS19 - Screenshot 13](https://user-images.githubusercontent.com/63108228/114831731-00f7dd80-9dce-11eb-95d9-227a142e7a62.jpg)

@Iwan1803 : Die doppelte Linie habe ich bereits entfernt, sollte aber darauf keinen Einfluss haben, weil es ein Ausfahrkurs von einer Halle war. Habe das ganze auch mal mit einem Traktor getestet. Das gleiche Problem. Nach dem Punkt "Hof - Silo Kalk abl." geht es nicht weiter. Stelle ich aber den Lkw oder Traktor links auf den Kurs zum Kalksilo und schicke ihn dann direkt zum Aufladepunkt, dann findet er das Ziel und fährt über das Kalksilo zum Ziel. Bin dann vom Abladepunkt Stück für Stück weitergefahren und habe getestet ab wann AD das Ziel wieder findet. Sobald man über den Kreuzungspunkt mit den anderen Silokurs rechts hinweg ist, findet AD das Ziel wieder. Verstehe nur nicht wo da jetzt das Problem ist. Habe solche Verläufe X-mal auf meinem Hof und es gab nie ein Problem.

**Comment by Iwan1803** [comment]
Wenn er vom Zielpunkt aus keinen Weg bis zur Kreuzung findet, scheint da der Fehler zu liegen.
Zieh mal testweise eine Linie vom Punkt "Hof - Silo Kalk abl." rüber zur Strecke vom Düngersilo. Dann würde er halt über das Silo wegfahren.
Ansonsten könntest du hinter dem Zielpunkt einen weiteren Wegpunkt setzen, wie es beim Düngersilo auch der Fall ist.

**Comment by TripleX1978** [comment]
@Iwan1803 : Danke für den Tipp, hab es aber mittlerweile anders gelöst und es läuft perfekt. Werde bei zukünftigen Kursen das mal testen.

![LS19 - Screenshot 14](https://user-images.githubusercontent.com/63108228/114848946-8f288f80-9ddf-11eb-9431-0f3a2dfc1c04.jpg)

In dem Zusammenhang ist mir noch was zum Thema "max. Siloabstand" auf-/eingefallen.
Wenn es da noch keinen passenden Fall gibt erstellen ich einen.
