### ISSUE TITLE
[BUG] Combine cp ad hud mouse control #1862 - several issues

### ISSUE THREAD

**Issue by Axel32019** [Stephan-S/FS19_AutoDrive#1886]
AutoDrive Version: 1.1.0.9 - RC 1
Release or selbsterstelltes zip: beta
Karte (falls relevant): Alle
Fahrzeug(art) (falls relevant): alle

**Beschreibe den Bug**

1. Wenn CP nicht im mod-Ordner und/oder aktiviert ist gibt es LUA-Callstack und komplette Bedienung (auch Spiel normal beenden) ist nicht mehr möglich:
  testActionName is NIL COURSEPLAY_MOUSEACTION_SECONDARY
 LUA call stack:
   dataS/scripts/input/InputBinding.lua (780) : printCallstack
   dataS/scripts/input/InputBinding.lua (719) : checkEventCollision
   =../HIP_Niedersachsen21/FS19_AutoDrive/scripts/Specialization.lua (73) : registerActionEvent
   dataS/scripts/vehicles/SpecializationUtil.lua (30)
   dataS/scripts/vehicles/Vehicle.lua (1910) : raiseEvent
   dataS/scripts/vehicles/specializations/AttacherJoints.lua (2306) : superFunc
   dataS/scripts/vehicles/Vehicle.lua (1889) : registerActionEvents
   dataS/scripts/vehicles/Vehicle.lua (1303) : updateActionEvents
   dataS/scripts/network/NetworkNode.lua (98) : update
   dataS/scripts/network/Client.lua (66) : updateActiveObjects
   dataS/scripts/BaseMission.lua (1503) : update
   dataS/scripts/FSBaseMission.lua (1979) : update
   dataS/scripts/missions/mission00.lua (469) : update
   dataS/scripts/main.lua (1944) : update
 Error: Running LUA method 'update'.
 dataS/scripts/input/InputBinding.lua(783) : attempt to index local 'testAction' (a nil value)
  testActionName is NIL COURSEPLAY_MOUSEACTION_SECONDARY
 LUA call stack:
   dataS/scripts/input/InputBinding.lua (780) : printCallstack
   dataS/scripts/input/InputBinding.lua (719) : checkEventCollision
   =../HIP_Niedersachsen21/FS19_AutoDrive/scripts/Specialization.lua (73) : registerActionEvent
   dataS/scripts/vehicles/SpecializationUtil.lua (30)
   dataS/scripts/vehicles/Vehicle.lua (1910) : raiseEvent
   dataS/scripts/vehicles/specializations/AttacherJoints.lua (2306) : superFunc
   dataS/scripts/vehicles/Vehicle.lua (1889) : registerActionEvents
   dataS/scripts/vehicles/Vehicle.lua (1303) : updateActionEvents
   dataS/scripts/network/NetworkNode.lua (98) : update
   dataS/scripts/network/Client.lua (66) : updateActiveObjects
   dataS/scripts/BaseMission.lua (1503) : update
   dataS/scripts/FSBaseMission.lua (1979) : update
   dataS/scripts/missions/mission00.lua (469) : update
   dataS/scripts/main.lua (1944) : update
 Error: Running LUA method 'update'.
 dataS/scripts/input/InputBinding.lua(783) : attempt to index local 'testAction' (a nil value)
Hier ist die Action-Binding von CP nicht bekannt und führt zum Fehler

2. Die AD Rechts-Klick-Aktionen funktionieren nur nach 2. Rechts-Klick - wobei der Mauszeiger nicht sichtbar ist
Beispiel: Parkplatz zuweisen/löschen
Dies sollte auch weiterhin wie gewohnt möglich sein.

**Falls anwendbar - Schritte mit denen ich den Bug nachstellen kann**
Für 1. CP nicht in mod-Ordner
Für 2. AD Bedienung der Funktionen mit rechter Maustaste

**Screenshots**
nicht relevant

**Comment by Axel32019** [comment]
Hallo @Dueesberch, Bitte mal ansehen - Danke.

**Comment by Dueesberch** [comment]
Moin @Axel32019,
hab nochmal einen PR erstellt um auch die Anpassung in der ADInputManager.actionsToInputs{} abzuschalten.
Ein erster Test hat ergeben, dass der Fehler durch die Änderung im "fix table settings" entstanden ist.
Ich hatte da ja COURSEPLAY_MOUSEACTION_SECONDARY in AutoDrive.actions und ADInputManager.actionsToInputs aufgenommen. Dadurch sind die aber 2 mal im 'System'.
Eine Lösung wäre nun, die modDesc.xml entsprechend zu erweitern. Das löst dann den LUA Stack Fehler bei fehlendem CP, aber fügt gleichzeit einen Input ein. Da für mich nicht nachvollziehbar ist, wass dann LS intern schief laufen kann denke ich nicht das die wirklich die Lösung ist. Zumal der Input auch bestehen bleibt wenn CP vorhanden ist. Also weiterhin 2 mal vergeben und der User kann dem dann auch noch Tasten zuweisen.
Die zweite Lösung wäre die beiden Einträge default zu habenund diese dynamisch zu löschen oder hinzuzufügen.
Da gebe es die Möglichkeit das direkt in der AutoDrive:loadMap() zu machen. Ist CP nicht vorhanden / geladen werden die Einträge für COURSEPLAY_MOUSEACTION_SECONDARY gelöscht. Ist CP vorhanden / geladen wird ADToggleMouse gelöscht. Somit gibt es nur ein Binding für Mouse Toggle. Nachteil ist hier, dass die User-Settings noch nicht vorhanden / geladen sind und somit die Auswahl combineCPAD 'aus' nicht ausgewertet werden kann. Es wäre also hart gesetzt das AD auch das CP Hud steuert. Außerdem wird loadMap ja nicht nochmals durchlaufen wenn der User Änderungen in den Settings macht.
Dritte Möglichkeit wäre die erste Version, die ich implementiert hatte, zu nutzen in der das Setzen der Tabelleneinträge in der AutoDriveHud:createHudAt() erfolgt. Somit bleiben alle Einstellmöglichkeiten erhalten. Das hattest du aber bemängelt.
Wäre es hier ggf. möglich das Setzen in eine Funktionen in der AutoDrive.lua zu verlagern und default alle Einträge in AutoDrive.actions und ADInputManager.actionsToInputs zu haben und diese je nach Nutzerauswahl zu löschen oder falls im aktuellen Spiel bereits gelöscht wieder hinzuzufügen. Im Test hat das funktioniert. Ich hoffe ich hab mich jetzt nicht zu kompliziert ausgedrückt.
Wie ist deine Mainung dazu? Wäre es möglich das per discord zu klären. Ich hab das Gefühl, dass man dort schneller die beste Lösung klären kann.

Das Problem mit Pkt 2. tritt auf, wenn die secondary mouse für CP auf rechts (default) eingestellt ist. Setzt man SECONDARY zb auch auf mitte läuft es fehlerfrei in meinen Tests. Da muss ich nochmal tiefer forschen wie man CP abgewöhnt die Mouse zu togglen wenn das CP Hud zu ist aber combineCPAD eingeschaltet.

**Comment by Axel32019** [comment]
Hallo @Dueesberch , Meld Dich doch mal im DC - dann können wir das mal bereden...

**Comment by Dueesberch** [comment]
Hallo @Axel32019, Hab einen bugfix commited und dich im Discord angeschrieben ;)

**Comment by Stephan-S** [comment]
Ich nehme an das Thema ist erledigt?
Falls ja, würde ich hier gerne zumachen und du könntest deinen PR schließen.
Ansonsten melde dich nochmal im Discord bei uns, danke.

**Comment by Dueesberch** [comment]
Hallo Stephan-S, keine Ahnung welcher Kanal im discord der richtige wäre, bzw. wen ich da anschreiben soll. Deshalb noch mal kurz hier. Ja das Issue ist gelöst und kann geschlossen werden. Schließe ich daraus, dass PR #1888 es nicht geschafft hat?

**Comment by Axel32019** [comment]
Hallo @Dueesberch,
Hilf uns doch nochmal etwas auf die Sprünge...
In CP war die Zuweisung / Funktion der rechten Maustaste noch unklar, oder?
In AD muß die rechte Maustaste funktional geändert werden damit das ganze funktioniert?
Hattest Du das nicht für Dich auf eine Sonder-Taste Deiner Maus gelegt?
Hier aus DC,  04.05.2021
so. bei dir war der taste AD hud ein/ausblende für die maus nix zugewiesen und CP secondary mouse action war auf der rechten maustaste
hab AD hud gesetzt und dann läuft es auch. die rechte raste bei cp knallt natürlich dann mit der rechten maustaste bei ad für zb parkplatz. das mit dem focus der huds ist von giants nicht gut gelöst. deshalb funktionieren mehrfachbelegungen auch nicht wirklich gut
bei mir liegt AD hud ein/aus auf einer der seitentasten der maus und auf LALT+KEY0 und cp secondary mouse auf der mittleren taste
jetzt ist natürlich die frage, ob man den nutzern so stark vorschreiben kann und will wie sie ihre tasten zu belegen haben

**Comment by Dueesberch** [comment]
Hallo @Axel32019 , Hallo @Stephan-S,
ich versuch es nochmal. 
Beginnen wir mit der ist Situation. Sprich AD in 1.1.1.0 und CP in 6.4.0.0, default Inputbindings. Also AD Maus ein/aus auf mittlerer Taste und Secondary Mouse Action auf rechter Maustaste. AD Hud ein / aus ist für die Maus nichts zugewiesen. Außerdem ist in CP Rechtsklick HUD ist für Fzg und erweiterte Einstellungen aktiviert. (Das sollte auch eher "open hud at secondary mouse action" heißen, aber anderes Thema)
1. bei Rechtsklick erscheint das HUD, auch wenn man nur einen Parkplatz zuweisen / löschen will
2. ist CP Hud offen und man klickt erneut rechts um P zuzuweisen oder zu löschen wird die AD aktion ausgeführt, aber auch  der Mauszeiger verschwindet
2. läßt sich lösen, wenn man Secondary Mouse Action auf middle legt. Damit laufen beide HUD's und die entsprechenden Aktionen (zB P zuweisen fehlerfrei / ohne Seiteneffekte)

Meine Änderung bewirkt, dass mit der AD Funktion Hud an/aus (Tastatur und auch Maus) beide Hud's ein- / ausgeschaltet werden können. Das Toggeln des Mauszeigers wird aber durch CP gesteuert. Ziel ist nun natürlich das Verhalten von 2. zu erhalten. Um das zu erreichen muss wie in der default Version die Sec. Mouse Action auf eine andere Taste als Rechts gelegt werden. Um das ganze abzurunden (nur AD steuert die HUD's) ist es erforderlich in den CP "Rechtsklick HUD" in den erweiterten Einstellungen zu deaktivieren.
Schlussendlich ist es aber keine Pflicht. AD steuert die HUD's auch bei default Belegung. Nur dann eben mit diesen unschönen Seiteneffekten. Aber Axel, du meintest ja man sollte das lieber als eine Pflicht in die Tooltips schreiben. Ich hatte das am Anfang ja als Proposal im Tooltip stehen.

Meine Überlegung wäre noch, in AD die P-Zuweisung nicht fix auf Rechts zu setzen, sondern auf die Maus ein/aus Taste. Das erfordert dann zwar einen Check ob ein Parkplatz zugewiesen / gelöscht wurde, um dann entsprechend die Maus wieder einzublenden, da diese ja bei einer P-Set Aktion ausgeblendet werden würde. Wenn dann jemand die AD Maus ein/aus und die CP Secondary Mouse Action auf die selbe Taste legt, tja was soll man dazu sagen.
Weiterhin könnte man, wenn man Combine HUD's control in den AD Settings auswählt das Rechtsklick HUD in CP abschalten. Aber da bin ich mir nicht sicher, ob Das dann nicht  zuviel Einfluss auf den User nimmt. Ggf müsste man das auch mit dem CP Team klären. Kann mir vorstellen, dass es da ein paar gibt die bei CP dann Bug Reports einkippen, weil das immer deaktiviert wird, sie aber ja offensichtlich nichts geändert haben.

PS: das Feld für die Tooltips ist zu klein. Gibt es da nicht die Möglichkeit bei Mouseover ein PopUp zu machen? :)

**Comment by Iwan1803** [comment]
Wie wäre es denn, wenn man das mit dem P in AD so wie bei den Wegpunkten löst?
Bei dem Button für das Umbenennen von Wegpunkten kommt ja auch dieses Popup bzgl. Umbenennen, Zurücksetzen und Löschen.
Im Popup für das P bräuchte man ja nur Zuweisen und Zuweisung löschen.

**Comment by Dueesberch** [comment]
Also Linksklick auf P und dann ein PopUp mit der Auswahl Zuweisen, Löschen, Fahren? Finde ich gut und würde sich auch in das Konzept einfügen. Sprich mehrere Optionen auf einer Taste werden über ein PopUp gelöst. Aktuell gibt es ja 2 Bedienkonzepte. PopUp und mehrere Tastenkombis auf einem UI-Button. Was eigentlich eher schlecht ist. Und Parken scheint ja immer wieder ein Problem darzustellen, weil es nicht intuitiv ist. Oder soll das PopUp sich bei Rechtsklick öffnen, weil du nur Zuweisen und Löschen aufführst? Ich denke das würde ja die feste Zuweisung auf die rechte Maustaste nicht lösen oder? Dann besteht ja immer noch die Gefahr der Doppelzuweisung und der indirekte "Zwang" eine Tastenzuweisung eines anderen Mod's zu ändern um die Doppelbelegung zu lösen

**Comment by Iwan1803** [comment]
Man macht einen Linksklick auf das P und dann öffnet sich das Popup, wo ich dem ausgewählten Fahrzeug oder Gerät ein P zuweisen oder löschen kann. Somit besteht kein Bedarf, einen Rechtsklick einzubauen.

**Comment by Stephan-S** [comment]
Ich sehe das ganze Thema ja ehrlich gesagt komplett anders und hätte wenn ich zu der Zeit dagewesen wäre schon den ganzen Maus Kram nicht gemerged.

Die einzige sinnvolle und nötige Änderung wäre doch gewesen auf CP Seite einzubauen, dass sie einfach immer mit dem Mauszeiger arbeiten, egal wer ihn getoggled hat, genau wie wir es bei AD ja auch machen.

Und das Thema mit dem gemeinsamen HUD umschalten ist ja dann nochmal ein ganz anderes.
Da verstehe ich den Wunsch, aber es gehört nach meiner Meinung auch nicht in unseren Code rein!

**Comment by Dueesberch** [comment]
@Iwan1803 Klar. Ich hatte jetzt nicht an den Editmode gedacht. Also im Editmode bei Linksklick ein PopUp und im Normalmode bei Linksklick "Fahre zu Parkplatz". Ich persönlich finde die Lösung besser, als Zusatztaste + Rechtsklick.

Auch wenn ich jetzt meine eigene Arbeit torpediere stimme ich Stephan zu. Das Arbeit / das Feature am Durchschalten beider HUD's ist erst durch die Parkfunktion und damit die Nutzung der rechten Maustaste und der daraus folgenden Seiteneffekte entstanden. Zu der Zeit habe ich auf Kandelin einen Lohnunternehmer gespielt mit entsprechendem Fuhrpark und es hat mich irgendwann verrückt gemacht, dass CP sich ungewollt öffnet. Ja, ich hätte auch die CP Tastenzuweisung ändern können. Aber in den Settings von CP steht halt explizit "Rechtsklick HUD". Naja, hinterher ist man immer schlauer.
Lange Rede kurzer Sinn. Ich denke die sauberste Lösung wäre es, das Parken (Zuweisen, Löschen, Fahren) in das Bedienkonzept von AD zu ändern und das Durchschalten der HUD's nicht aufzunehmen. Privat kann ich AD ja immer noch Patchen. :)
Schlussendlich müsst ihr dies entscheiden. Wenn ihr das Feature nicht aufnehmen wollt, sagt mir kurz bescheid, dann würde ich einen PR erstellen, der die Codefragmente aus dem ersten Merge entfernt.

**Comment by Dueesberch** [comment]
Bitte schließen
