### ISSUE TITLE
[BUG] Crash after using Hud

### ISSUE THREAD

**Issue by Sadbraiin** [Stephan-S/FS19_AutoDrive#1887]
AutoDrive Version: 1.1.0.8
Karte (falls relevant): Steffishausen
Fahrzeug(art) (falls relevant): Drescher, Claas 200 aus einer Mod

Spiel ist abgestürzt nach Interaktion mit dem Hud ich wollte das Feld einstellen im Autodrive damit der Abfahrer verbindet.

[log.txt](https://github.com/Stephan-S/FS19_AutoDrive/files/6313282/log.txt)

**Comment by Tom20214** [comment]
@Sadbraiin Kamnst du einmal die Autodrive.config in.txt hier hochladen.

**Comment by Sadbraiin** [comment]
Hey, wo ist die denn? Bzw. hilft die dir überhaupt noch da ich erstmal AutoDrive deaktiviert hatte, weiß jetzt nicht ob sich da was verstellt hat schon.

**Comment by Iwan1803** [comment]
@Sadbraiin 
ca. 240 Mods und etliche Warnings im Log.... 🙄
Da sind bestimmt welche dabei, welche für die Probleme verantwortlich sind. Vielleicht solltet ihr testweise mal die ganzen Mods deaktivieren, welche alle ins HUD und/oder UI eingreifen (z.Bsp. FS19_VehicleInfo, TSX_EnhancedVehicle, SimpleIC, etc.).
Außerdem scheinen da so einige Fahrzeuge vorhanden zu sein, welche alle ihr eigenes Autoload-Skript mitbringen.

**Comment by Sadbraiin** [comment]
Hey Iwan, ja bin lost was das angeht ich gehe gerade selber step für step durch. FS19_VehicleInfo, TSX_EnhancedVehicle, SimpleIC sind alle schon raus, ich gehe davon inzwischen davon aus das es was anderes verursacht hatte. Naja am Ende bleibt mir nix anderes als testen und bescheid geben. Dennoch danke für den Hinweis.

**Comment by Iwan1803** [comment]
Deswegen knallt man nicht einfach jeden Mod auf einen Server rauf 😏
Wir bei uns testen jeden Mod recht ausgiebig erstmal lokal im SP und/oder gehosteten MP, bevor er überhaupt auf den Server kommt. Tauchen Fehler oder Warnings auf, wird geschaut was es ist und wenn es als gravierend eingeschätzt wird, kommt der Mod nicht auf den Server und fertig.
Weniger ist manchmal mehr und unser Server rennt fehlerfrei.
Von daher kannst du nur testen, testen, testen... was bei 240 Mods, wohl recht lange dauern wird. Wie geschrieben solltest du dich erstmal auf alles konzentrieren, was irgendwelche Zusatzanzeigen ins Spiel bringt.
Wir hatten damals auch Probs mit VehicleExplorer und FruitHUD oder wie das heißt. Ergo flog es runter und gut war's.

**Comment by Sadbraiin** [comment]
Ja da muss ich zugeben, dass ich wohl einfach zu unwissend bin, ich komm von 4 Jahren nur r6 zocken da ist die Birne halt Matsch
Wie gesagt danke wir machen das jetzt step by step mit einem Ersatz Server und dann sollte es passen.
Soll ich das hier schließen?

**Comment by Iwan1803** [comment]
Neu aufsetzen klingt nach einem guten Plan, aber das testen und prüfen nicht vergessen. Nicht, das dann wieder irgendwelche Mods das Log mit Fehlern zu knallen 😉
Du kannst hier ja erstmal schließen und bei Bedarf auch wieder öffnen.
