### ISSUE TITLE
[BUG] First person erratic camera movement when passing below low ceiling

### ISSUE THREAD

**Issue by Jean-LouisVandewalle** [Stephan-S/FS19_AutoDrive#1889]
**AutoDrive Version:** 1.1.0.7 & 1.1.0.8
**Release or Custom Zip:** Release & Custom ZIp
**Map (If applicable):** detected on Felsbrunn
**Vehicle / Type (If applicable):**   Any
**Multiplayer or Singleplayer:** Singleplayer (not tested in multiplayer)  

**Describe the bug**  
When passing below a low ceiling (eg. with a pickup in the farm garage in Felsbrunn), the first person camera is pushed down through the bottom of the car. This also occurs with any other vehicle when passing below a low ceiling (eg: when passing the doorway of a shed)
It seems to be related to the presence of the AD interface.
If the camera movements are freezed (mouse is visible), then the camera stays stabel when passing below the low ceiling.
If you enter for the first the vehicle time (after loading a game) and the AD window is not present, the camera makes no weird movement. But as soon the AD interfaces has been activated once, the camera movement occurs again and again (hiding it doesn't solve the issue).

**If applicable - Steps to reproduce the behavior**  
Just start a new game (new farmer) on Felsbrunn, activate AD Mod. buy a pick-up car and try to enter the farm garage in first person mode.

**Screenshots**  
A short video of the behaviour is available here:
https://youtu.be/M762YGWayLk

**Comment by Jean-LouisVandewalle** [comment]
It seems I could solve the issue by adding the mod "Disable Vehicle Camera Collision".

I will make some extra tests to see if it appears again on the long term.

Keep you posted.

**Comment by Stephan-S** [comment]
Thanks for the info!
I think I found the issue on our site, so this should be fixed with the next release.
