### ISSUE TITLE
[BUG] Ziele und Modus weg - No target and mode

### ISSUE THREAD

**Issue by kurtlohnunternehmen** [Stephan-S/FS19_AutoDrive#1890]
AutoDrive Version: 1.1.0.8
Release or selbsterstelltes zip: Release
Karte (falls relevant): Alle
Fahrzeug(art) (falls relevant):

SP (Karriere)

Wenn ich den jeweiligen Fahrzeugen einen Kurs (also Modus und Ziele) angebe, werden die Ziele und Modus nicht mit den jeweiligen Fahrzeugen gespeichert. Lade ich das Savegame neu ist alles weg (dieses Problem gab es doch schon Mal). Dann steht wieder bei allen Fahrzeugen das selbe Ziel und Modus - das zuvor eingestellte ist futsch. Es ist egal welche Karte oder Mod - habe auch ein jungfräulichen Spiel (also ohne Mods) probiert - immer das selbe Ergebnis.

If I give the respective vehicles a course (mode and target), the target and mode are not saved with the respective vehicles. If I reload the savegame everything is gone (this problem has existed before). Then all vehicles have the same target and mode again - the one previously set is gone. It doesn't matter which map or mod - I also tried a virgin game (iwithout mods) - always the same result.

**Comment by Tom20214** [comment]
#1071

**Comment by Axel32019** [comment]
Hallo @kurtlohnunternehmen , Bitte log.txt, AutoDrive_config.xml, vehicles.xml und hilfreiche Screenshots anhängen, das hilft ungemein. Die xml-Dateien ggf. in .txt umbenennen.

**Comment by kurtlohnunternehmen** [comment]
Mein Fehler! Im Modordner waren zwei Autodrive Versionen - die haben es wohl verursacht. Jetzt keine Speicherprobleme mehr. Blöder Anfängerfehler - sorry.
