### ISSUE TITLE
Drescher/Häcksler abtanken mit Überladewagen

### ISSUE THREAD

**Issue by TripleX1978** [Stephan-S/FS19_AutoDrive#1892]
AD 1.1.0.8
Map : NF Marsch 4fach

Ich versuche meine Drescher/Häcksler mit einem Holmer Terra Variant abzutanken.
Dieser soll dann am Feldrand überladen.
Habe jetzt schon mehrere Lösungsansätze ausprobiert.
Bei einem Feld funktioniert es, bei einem anderen bekomme ich immer die Meldung, dass der ÜLW keinen Weg zum Ziel finden konnte.
Wenn jemand eine funktionierende Lösung hat, wäre es super wenn er mir ein paar Screenshoots einstellt oder Tipps gibt.
Am liebsten von der Marsch, muss aber nicht.
Nur damit ich evtl. nachvollziehen kann wie das aufgebaut werden muss.

Vielen Dank schonmal.

**Comment by Iwan1803** [comment]
Wenn du eine Lösung hast, welche auf einem Feld funktioniert aber auf einem anderen nicht, dann solltest du mal nach den Unterschieden beider Felder schauen.
Vielleicht sind auch einfach 2 Wegpunkte falsch herum miteinander verbunden.

**Comment by TripleX1978** [comment]
@Iwan1803 
Also an falschen Wegpunkten kann es nicht gelegen haben.
Hab da aber noch eine Idee die ich mal testen werde.

**Comment by Axel32019** [comment]
@TripleX1978 Wenn Du #1628 versuchs wird das wohl nichts.

**Comment by TripleX1978** [comment]
@Axel32019 Das Überladen in den Holmer mit MB35 funktioniert bei mir eigentlich problemlos. Das Anfahren des Überladepunkts am Feldrand ist das Problem.
Bei einem Feld funktioniert es (z.B. Feld 46) bei einem anderen (Feld 2) geht's nicht.

**Comment by Axel32019** [comment]
@TripleX1978  Bitte mal Screenshot(s) posten.
