### ISSUE TITLE
Abfahrer schaltet sich nach den Beladen aus!  [BUG]

### ISSUE THREAD

**Issue by KarlGutenberg** [Stephan-S/FS19_AutoDrive#1894]
AutoDrive Version: 1.1.0.9 aktuell
Release or selbsterstelltes zip: Release
Karte NF_Marsch_4fach_V2_7
Fahrzeug(art) (falls relevant):

**Beschreibe den Bug**
Der Abfahrer fährt nicht ab, er schaltet sich einfach aus!
Video / Log anbei
[log.txt](https://github.com/Stephan-S/FS19_AutoDrive/files/6357180/log.txt)
Video hierzu:
https://youtu.be/j1kdXpm8gdE

**Comment by jala15** [comment]
Lines around the field are totally useless unless you choose the field exit option: closest point (Feldausfahrt: Nachstgelegen) 
If you use the other options, the field waypoint must  have a exit to continue from there.
![Captura de pantalla (2)_LI](https://user-images.githubusercontent.com/52028079/115760375-916f8880-a3a1-11eb-9372-fd96d36aad27.jpg)

**Comment by KarlGutenberg** [comment]
Habe ich ja eingestellt!
Nächstgelegener!!
Mit passende Ausgänge
Grüße

jala15 ***@***.***> schrieb am Do. 22. Apr. 2021 um 19:41:

**Comment by KarlGutenberg** [comment]
Neuer Versuch auf einer anderen Map (WildWest), wo es schon mal Funktionierte!
Auch hier geht nichts mit der neuen Version.

[log.txt](https://github.com/Stephan-S/FS19_AutoDrive/files/6376437/log.txt)

Hierzu ein Video
https://youtu.be/rayb-QSLwmM

**Comment by jala15** [comment]
Let's do a test. Take a car, go a few waypoints before "Feld 42", set it to drive with destination "HofSilo abladen". Does it drive? make sure the car calculates the path to "HofSilo abladen" driving through "Feld 42"

**Comment by KarlGutenberg** [comment]
I do not quite understand now what you mean!
But when I set the car on course, it goes to the yard!
I have times, from my savegame loaded a backup copy
and it goes now again zm. on the WildWest


Am Mo., 26. Apr. 2021 um 13:21 Uhr schrieb jala15 ***@***.***

**Comment by jala15** [comment]
What are the differences between working and not working savegames? 
Route changes... Tractor settings... Different fields...

**Comment by KarlGutenberg** [comment]
Here mal that both config
[AutoDrive_config geht nicht.txt](https://github.com/Stephan-S/FS19_AutoDrive/files/6376792/AutoDrive_config.geht.nicht.txt)
[AutoDrive_Wild_West_config Funktioniert.txt](https://github.com/Stephan-S/FS19_AutoDrive/files/6376793/AutoDrive_Wild_West_config.Funktioniert.txt)

**Comment by KarlGutenberg** [comment]
Only an older backup copy

Am Mo., 26. Apr. 2021 um 13:46 Uhr schrieb jala15 ***@***.***

**Comment by Axel32019** [comment]
Hello @jala15 @KarlGutenberg ,
Do not try to find the reason why it is not working. 
Yesterday night I figured out that the status of the AD Modes are not reset if mode is activated -> fixed in beta branch.
@KarlGutenberg With the setting "Feldausfahrt" "Standard" the unloaders will not find a way from field, because:
You have a dead end for the field destination and setting "Feldausfahrt" "Standard" will try to find a way from field destination to unload destination, which is not possible.
It is no longer a difference if AD search a way from field or you initiate it!
You may test it with the beta version.

**Comment by KarlGutenberg** [comment]
Hello @Axel32019
ich habe die "nächstliegende Ausfahrt" ausgewählt!
Und mit meiner Sicherungskopie funktioniert das abfahren ja wieder!
Es scheint als, wenn die config irgendwie defekt ist!
Auch habe ich die Bettaversion geladen!

Hello @Axel32019
I have selected the "nearest exit"!
And with my backup the exit works again!
It seems as if the config is somehow defective!
I have also loaded the betta version!

**Comment by Axel32019** [comment]
Hallo @KarlGutenberg ,
Im ersten Vide hatte ich noch "Standard" gesehen...
Die Debug-Funktion für Streckennetz kennst Du?
Die beta version ist sehr dynamisch :-)

**Comment by KarlGutenberg** [comment]
Wie du im Video gesehen haben müsstest habe ich auch auf
Nächstliegende umgestellt!
Aber ich habe ja den Fehler gefunden!
Es lag an der config
Jetzt geht es ja wieder.
Und ich lade mir immer die Betta.

Am Mo., 26. Apr. 2021 um 14:48 Uhr schrieb Axel32019 <
***@***.***>:

**Comment by KarlGutenberg** [comment]
Die Debug-Funktion für Streckennetz kennst Du?
Kenne ich nicht!

Am Mo., 26. Apr. 2021 um 14:48 Uhr schrieb Axel32019 <
***@***.***>:

**Comment by KarlGutenberg** [comment]
@Axel32019
Die Debug-Funktion für Streckennetz kennst Du?
Nein, erkläre mir bitte!
