### ISSUE TITLE
Autodrive is not working with vehicles from OK USED MODS & J&M FARMS

### ISSUE THREAD

**Issue by YungFras85** [Stephan-S/FS19_AutoDrive#1895]
I have been searching online and couldn't find a straight answer so I figured I would post here. AD works perfectly fine for me except on certain vehicles. In this case it happens to be for all of **OK USED MODS & J&M FARMS** vehicles. Is there a fix I can implement in the files of those vehicles to get them to work?

**Comment by crcarmichael** [comment]
I use several of Glen's vehicles with no issue.

**Comment by YungFras85** [comment]
> I use several of Glen's vehicles with no issue.
 Have you used this one? It’s the one I’m currently trying to use. I’m going to redownload it and try it on a new save and map.  https://mod-network.com/detail/19231/The+Chevy+C70+Deluxe+Tanker+Truck

**Comment by Iwan1803** [comment]
Sometimes modders use their own "special" vehicle types or category or other non-standard variables, which can then lead to problems with AD.
Sometimes it helps to correct this, but sometimes this leads to the fact that this vehicle then no longer works.

What exactly doesn't work?

**Comment by YungFras85** [comment]
The hud does not open and AD does not activate when pressing the assigned key binds for certain vehicles. It is as if AD isn’t installed when you enter those vehicles but works perfectly fine for others.
