### ISSUE TITLE
[BUG] pathfinding

### ISSUE THREAD

**Issue by crcarmichael** [Stephan-S/FS19_AutoDrive#1896]
**AutoDrive Version:** 1.1.0.8  
**Release or Custom Zip:** Release  
**Multiplayer or Singleplayer:** Singleplayer  

**Describe the bug**  
After installing 1.1.0.8, pathfinding from within a field almost always fails, even when quite close to a route... with the debugger on, I can that it does find a path, but does not execute it.  After downgrading to 1.1.0.7, pathfinding works as expected.

**Comment by Iwan1803** [comment]
With next release there will be another update for the pathfinding routines.

**Comment by Axel32019** [comment]
Hello @crcarmichael , Could you please provide screenshot(s) of the situation(s), your Autodrive_config.xml and vehicles.xml.

**Comment by crcarmichael** [comment]
seems to be working as expected now.  Not sure what was going on when I first upgraded to 1.1.0.8. pls disregard
