### ISSUE TITLE
[BUG] combine won't overload anymore into second trailer

### ISSUE THREAD

**Issue by rohne83** [Stephan-S/FS19_AutoDrive#1897]
AutoDrive Version: 1.1.0.8
Release or selbsterstelltes zip: Release
Karte (falls relevant): Alle
Fahrzeug(art) (falls relevant): alle Abfahrer mit mehreren Getreide-fillUnits

**Beschreibe den Bug**
Hi, seit 1.1.0.8 hat AutoDrive Probleme beim Dreschen auf mehrere Trailer. Bis einschließlich 1.1.0.7 ist der AD-Abfahrer ja von selbst immer ein Stück vorgefahren sobald der erste Trailer voll war. Damit war es möglich zB LKWs mit Pritsche + Anhänger oder Traktoren mit zwei Anhängern einzusetzen, oder auch Sattelschlepper mit dem Wilson oder Lode King. Das ist jetzt scheinbar nicht mehr möglich, da der Abfahrer mit der ersten FillUnit auf Rohrhöhe verharrt auch wenn Diese voll ist. Womit das Entladen auch nie abgeschlossen werden kann, da weder der Drescher vollständig abtanken kann noch der Abfahrer seinen Abfahrfüllstand erreicht.

**Screenshots**
![fsScreen_2021_04_23_13_49_28](https://user-images.githubusercontent.com/71030138/115955639-18367980-a4f8-11eb-97bd-8e9bbde46174.png)

**Comment by Iwan1803** [comment]
Bitte mit dem aktuellen Release 1.1.1.0 probieren und dann ein Feedback hier hinterlassen

**Comment by rohne83** [comment]
Klappt leider doch noch nicht. Jetzt wird auch vorne nicht mehr richtig befüllt, sondern direkt so weit vorgefahren, dass das Rohr sich zwischen den fillUnts befindet... 
![fsScreen_2021_05_10_11_22_29](https://user-images.githubusercontent.com/71030138/117722018-db999c00-b1e0-11eb-8cbf-7626b7c9aee1.png)

**Comment by rohne83** [comment]
Nochmal mit anderen Fahrzeugen probiert. Also grundsätzlich scheint es wieder richtig zu gehen. Das Verhalten dass das Rohr über der Deichsel ist tritt nur beim Wechselbrücken-LKW auf. Aus irgendeinem Grund fährt AD da für die Pritsche zu weit nach vorne. Habt ihr da irgendwas geändert wie der vertikale Abstand ermittelt wird? Im ersten Screenshot im Eröffnungsbeitrag das war haargenau der selbe Mod und da wurde der vertikale Abstand für den LKW selbst ja noch völlig korrekt ermittelt.

**Comment by Axel32019** [comment]
Hallo @rohne83 , Bitte stell mal die Feld-Geschwindigkeit auf ~40 ein. Ich vermute der LKW schiesst über das Ziel hinaus.

**Comment by rohne83** [comment]
Hi, das hat leider nichts geholfen, selbes Verhalten wie im letzten Screenshot. Ich schätze mal das ist irgendein Seiteneffekt eurer überarbeiteten Abstandskalkulierung. Bis einschließlich Version 1.1.0.7 lief das noch komplett perfekt, bei 1.1.0.8 wurde zwar der LKW noch beladen aber der Anhänger nicht mehr vorgezogen, und seit der 1.1.1.0 passt bei den LKW der vertikale Abstand nicht mehr.

**Comment by Iwan1803** [comment]
Hast du es mit der 1.1.1.2 (aktueller Release) schon mal probiert?

**Comment by rohne83** [comment]
Ja, der letzte Versuch war sogar mit jener Version. Nur mit der aktuellen RC hab ichs noch nicht probiert

**Comment by DonBolli** [comment]
Ich habe das Release zip 1.1.1.6, habe aber auch diesen Fehler.

**Comment by rohne83** [comment]
Kann ich bestätigen. Mit der 1.1.1.6 ist wieder dieser Fehler da. Ich meine zwischenzeitlich war der mal weg gewesen (meine es war so um Version 1.1.1.4, auch wenn LKWs da zuerst den Anhänger beladen haben und erst danach ihren eigenen Aufbau), aber aktuell ist das Verhalten wieder wie oben beschrieben. Interessanterweise aber nur bei LKWs wie es scheint. Traktoren mit zwei Anhängern haben zuletzt keine Probleme gemacht.

**Comment by Iwan1803** [comment]
Da kein weiteres Feedback -> geschlossen.
Ansonsten: https://github.com/Stephan-S/FS19_AutoDrive/issues/2147
