### ISSUE TITLE
Kollision bei Rückwärtskursen mit mehreren Fahrzeugen / Collision reverse courses with multiple vehicles

### ISSUE THREAD

**Issue by TripleX1978** [Stephan-S/FS19_AutoDrive#1898]
Ich würde gerne die Fahrzeuge rückwärts an einen Trigger zum befüllen fahren lassen.

![LS19 - Screenshot 16](https://user-images.githubusercontent.com/63108228/115996141-61f98f80-a5de-11eb-8b9c-6c0e0f377f9b.jpg)

Das funktioniert auch soweit.
Habe jetzt nur das Problem, dass ich auf diesem Kurs mehrere Fahrzeuge eingesetzt habe und dann passiert schonmal folgendes.

![LS19 - Screenshot 15](https://user-images.githubusercontent.com/63108228/115996166-7b024080-a5de-11eb-94f0-95322a909fad.jpg)

Der rechte Lkw versucht rückwärts einzuparken, während die beiden linken schon nachgerückt sind und diesen blockieren.
Was auch schon vorkam ist, dass ein Lkw links auf dem Trigger steht und die anderen beiden vorbeifahren, den Rückwärtsgang einlegen und sich davor setzen.

Lässt sich das irgendwie bewerkstelligen, dass der nächste Lkw erst den Trigger anfährt wenn der Bereich wieder frei ist?

**Comment by Axel32019** [comment]
@TripleX1978 Ich weiss @Iwan1803 wird mich hierfür "verprügeln", aber einen Versuch wäre es wert:
Die Strecke 2 Punkte hinter "...Milch abl." bis 1 Punkt vor dem Abzweig links mal blau machen - dann könnte die Priorisierung greifen.

**Comment by Iwan1803** [comment]
Warum sollte ich dich verprügeln? 😂
Meine Strecke an der Stelle hätte vermutlich etwas anders ausgesehen, aber ob sie funktioniert hätte, wenn da x Fahrzeuge gleichzeitig ankommen.... 🤔

**Comment by TripleX1978** [comment]
@Axel32019 Danke für den Tipp. Hab es mal getestet, aber leider ohne Erfolg.

**Comment by Stephan-S** [comment]
Ich kann den Fehler aktuell nicht nachstellen.
Hier ist eigentlich schon ein Check drinnen der das verhindern sollte, insofern die zwei dahinter auch in die Rückwärtspassage rein wollen. Ansonsten wird sowas natürlich deutlich schwerer zu prüfen.

Kannst du mir mal deine AutoDrive_config dazu schicken? 
Das würde ich mir gerne bei Gelegenheit mal anschauen.

**Comment by TripleX1978** [comment]
@Stephan-S Ich habe mittlerweile alles anders aufgebaut und diese Situation anders gelöst. Denke dann bringt dir meine Config nichts mehr oder?
Könnte aber die Tage nochmal die Situation nachstellen wenn dir das hilft.

**Comment by Axel32019** [comment]
@Stephan-S Ist das noch aktuell? Wenn nicht schließen wir das.

**Comment by Iwan1803** [comment]
Da kein weiteres Feedback -> geschlossen.
