### ISSUE TITLE
Emplimenting driver salary option 

### ISSUE THREAD

**Issue by RUGhost** [Stephan-S/FS19_AutoDrive#19]
Can you please add the option if driver get salary or not like courseplay? In courseplay you have a option at the first loading of courseplay to select if driver get salary or not.

**Comment by Stephan-S** [comment]
For now, the drivers are handled just as every ai helper is. So they will cost money.
Changing this into a more flexible payment for the helpers is a nice idea but for now not on the top of my priority list, so I can't promise that this will come any time soon, sorry

**Comment by RUGhost** [comment]
One more request. If you get time then add the option to how many time a tractor repeat "Load and Unload" loop. By this option i can tell a tractor to perform the loop 1/2/3/4/5...... or infinite time (untill grain sillo become empty).
