### ISSUE TITLE
HUD and Settings Not Launching for 1 Tractor

### ISSUE THREAD

**Issue by stangman04** [Stephan-S/FS19_AutoDrive#190]
I have a modded John Deere 8R that I can not launch the HUD or settings from. All other vehicles work fine. Any ideas of what could be causing this?

**Comment by docgaming** [comment]
if the hud is not loading then it maybe a issues with the john deere mod. open the XML file for the john deere mod at the top it will have vehicle type=  
what does it say after that

**Comment by docgaming** [comment]
if it has tractor8r or JD8r or something like that then change it to tractor.
i just downloaded 3 mods for the 8r and 2 of them had the wrong vehicle type

**Comment by stangman04** [comment]
I figured it was something with the tractor and that you had come across it before. It had JD8R in there, all fixed now. Thanks, closing this issue.
