### ISSUE TITLE
[BUG] beta RC 1.1.0.9 Error: Running LUA method 'loadMapFinished'.

### ISSUE THREAD

**Issue by xGloryJx** [Stephan-S/FS19_AutoDrive#1902]
**AutoDrive Version:** 1.1.0.9 (downloaded today)
**Release or Custom Zip:** Custom Zip
**Map (If applicable):** All (not tested)  
**Vehicle / Type (If applicable):** not relevant
**Multiplayer or Singleplayer:** Singleplayer  

**Describe the bug**  
Can't load map
`2021-04-27 18:45   Info: [AD] Start register later loaded mods...
2021-04-27 18:45   Info: [AD] Start register later loaded mods end
2021-04-27 18:45 Error: Running LUA method 'loadMapFinished'.
2021-04-27 18:45 G:/FS19/LakeLandVale/FS19_AutoDrive/scripts/Manager/GraphManager.lua:391: attempt to index field 'Hud' (a nil value)`

If i delete AutoDrive_config.xml i can load the map
I then can load an saved route an use autodrive (route war created using 1.1.0.9 (beta downloaded some days ago)
If i save the game and try to reaload the map i get Error: Running LUA method 'loadMapFinished' 

[AutoDrive_config.xml.txt](https://github.com/Stephan-S/FS19_AutoDrive/files/6386359/AutoDrive_config.xml.txt)
[log.txt](https://github.com/Stephan-S/FS19_AutoDrive/files/6386355/log.txt)
[route.xml.txt](https://github.com/Stephan-S/FS19_AutoDrive/files/6386378/route.xml.txt)

**Comment by Axel32019** [comment]
Hello @xGloryJx Could you please add your FS19_AutoDrive.zip here as well?

**Comment by xGloryJx** [comment]
[FS19_AutoDrive.zip](https://github.com/Stephan-S/FS19_AutoDrive/files/6387916/FS19_AutoDrive.zip)

After i deleted the debug waypoints 1,2,3 and 1_1 i can load the map without problems

**Comment by Axel32019** [comment]
Hello @xGloryJx , How did you manage to save the debug markers? Did you exported via route manager, import and then save?

**Comment by xGloryJx** [comment]
@Axel32019 yes i think that's what i did. I activated debug mode to find lose ends in my network. I save the the game while debug mode was active.  If i am not mistaken autodrive save the network when i save the game?

**Comment by Axel32019** [comment]
@xGloryJx Thanks for the hint(s) - fixed in beta-Branch.

**Comment by haamic** [comment]
@Axel32019 
ich konnte auch plötzlich die Map nicht mehr laden, auch mit der aktuellsten  1.1.0.9 beta nicht.
da scheint noch nichts gefixt zu sein.
Erst als ich die DEBUG-Wegpunkte mit der normalen 1.1.0.8 löschte bzw. unsinnig mit dem Netz verbunden habe, damit ich keine offenen Stellen mehr hatte, konnte ich mit der 1.1.0.9 beta wieder die Karte laden.
