### ISSUE TITLE
[BUG] Impossible Toggle Mouse

### ISSUE THREAD

**Issue by Vanquish081** [Stephan-S/FS19_AutoDrive#1904]
**AutoDrive Version:** 1.1.0.8
**Release or Custom Zip:** Release  
**Map (If applicable):** PC
**Vehicle / Type (If applicable):**   ALL
**Multiplayer or Singleplayer:** Singleplayer  & Multiplayer

**Describe the bug**  
I cannot toggle mouse with any keys. I used key of keyboard, different combinations, with other mouse ... but nothing.

[log.txt](https://github.com/Stephan-S/FS19_AutoDrive/files/6409364/log.txt)

Edit:
The mouses works fine...
https://www.onlinemictest.com/mouse-test/

**Comment by Iwan1803** [comment]
Sorry, but I don't really understand what you mean.
Don't you know what key combination to use in conjunction with the mouse, or do you want to change it?

**Comment by Vanquish081** [comment]
No matter the combination, with the default key MMB (Middle Mouse Button) I cannot activate the mouse for AD.
I tried other keys by changing them in the game menu, but they don't work either.

**Comment by Iwan1803** [comment]
Maybe an other mod is catching the click?

**Comment by Axel32019** [comment]
Hello @Vanquish081 , Could you please provied log.txt, AutoDrive_config.xml, inputBinding.xml?

**Comment by Vanquish081** [comment]
@Axel32019 in the first post have a Log, but here have other.


[Test_AD.zip](https://github.com/Stephan-S/FS19_AutoDrive/files/6432210/Test_AD.zip)

**Comment by Axel32019** [comment]
@Vanquish081 
Please check the input bindings for middle mouse button:
I see an assignments with "X_CRUISE_ACTIVATE" and "PS_TOGGLE_MOUSE_CURSOR", do not know what it is, but these may catch the mouse event before it reaches AD.
Keep only "MOUSE_ALT_COMMAND3_BUTTON" and "ADToggleMouse".

**Comment by Vanquish081** [comment]
Sorry but no work...

The resolution (2560 x 1080) isn't problem?

**Comment by Axel32019** [comment]
Please do not only delete some lines. As we do not see such issue beside you, we assume a special issue with your setup.
Do you have other devices connected like controller, graph tablet etc.?
Disconnect all, delete inputBinding.xml after backup copy, only try with mouse and keyboard.

**Comment by Vanquish081** [comment]
The lines deletes are "X_CRUISE_ACTIVATE" and "PS_TOGGLE_MOUSE_CURSOR" only.

The keyboard and mouse are connected only.

**Comment by Axel32019** [comment]
Do these lines come back if you save and quit the game?

**Comment by Vanquish081** [comment]
Well.... reset all configuration after backup copy, and now work, I don't know what is the conflict...
