### ISSUE TITLE
Falsche Fruchtsorte wird geladen / Loading wrong filltyp

### ISSUE THREAD

**Issue by TripleX1978** [Stephan-S/FS19_AutoDrive#1905]
**AutoDrive Version:** 1.1.0.8   

Ich habe auf meinem Hof mehrere Fahrer mit einem Tankanhänger, der verschiedene Flüssigkeiten laden kann, im Einsatz.
Es ist jetzt schon öfters vorgekommen, dass der Wasserfahrer z.B. Gärreste geladen hatte oder der Güllefahrer Milch.
Da ich es immer erst sehen wenn der jeweilige Fahrer gerade versucht z.B. Milch bei Gülle abzuladen und alles blockiert, ist meine Vermutung, dass der Fahrer, warum auch immer, gezwungen war eine Strecke zu nehmen, die an einem falschen Trigger vorbeiführt und dann beladen wird.
Vielleicht wäre es möglich, falls das nicht schon gemacht wird, zu überprüfen, ob die Fruchtsorte am Trigger mit der eingestellten Fruchtsorte übereinstimmt und dann erst geladen wird.

**Comment by TripleX1978** [comment]
Update:

Gerade eben hatte ich den Fall, dass der Fahrer, der Gärrest von der BGA zum Klärwerk bringen soll plötzlich mit einem vollen Milchtank am Klärwerk stand. Ich spiele die NF4fach und Klärwerk und BGA liegen direkt beieinander, sodass der Fahrer praktisch immer nur im Kreis fährt und nicht mal in die Nähe der Milch kommt.

**Comment by TripleX1978** [comment]
Update:

Ich habe die Ursache gefunden.
Während der Fahrer die Gärreste von der BGA zum Klärwerk bringt kommt es immer mal wieder vor, dass er den Fahrern begegnet, die Milch vom Hof zur Molkerei bringen.
Sobald diese aneinander vorbei fahren, wird für einen kurzen Zeitraum Milch übergeladen.
Vermute mal, dass das auch der Grund ist warum auf meinem Hof die Fahrer plötzlich mit dem falschen Zeug durch die Gegend fahren.

**Comment by Axel32019** [comment]
Ist in beta Version behoben.
