### ISSUE TITLE
[BUG] AD fährt auf falsche Seite zum abladen

### ISSUE THREAD

**Issue by Matze9876** [Stephan-S/FS19_AutoDrive#1907]
AutoDrive Version: 1.1.0.9 RC1 (beta vom 03.05.2021)
Release or selbsterstelltes zip: Release
Karte (falls relevant): Kandelin, Multiplayer
Fahrzeug(art) (falls relevant): Standard Trecker, Krone Premos aus dem Strohbergungs Addon

Ich fahre den Trecker mit der Premos 5000 manuell und "rufe" AD zum abladen.
AD kommt, fährt aber auf die linke Seite zum abladen.
Ich kann ihn erneut rufen, aber er fährt nicht auf die rechte Seite. (siehe Screenshot)

Beide Log-Dateine (server und client) sind fehlerfrei!
![fsScreen_2021_05_03_12_41_19](https://user-images.githubusercontent.com/57115689/116868004-4b6ebc00-ac0e-11eb-867e-f3082707348f.png)

Falls noch weitere Info´s benötigt werden, gerne melden!

**Comment by rellek82** [comment]
Hast du mal versucht, den Rohrabstand beim Abfahrer auf Minus-Werte zu stellen? Ich kann dir nicht genau sagen, ob das funktioniert. Ein Versuch wäre es ha mal wert.

**Comment by Iwan1803** [comment]
siehe auch #1627 and #1422

**Comment by Matze9876** [comment]
@rellek82: negative Werte funktioniert leider nicht

**Comment by rellek82** [comment]
@Matze9876 Ok, dann weiß ich es leider auch nicht.
Les mal die von Iwan1803 verlinkten Issues durch, vielleicht hilft dir das ja weiter.

**Comment by Axel32019** [comment]
@Matze9876 Im Singleplay funktioniert das bei mir.
Würdest Du bitte auch mal den MP-Spielstand als SP ausprobieren.

**Comment by Matze9876** [comment]
@Axel32019 also im Singleplay läuft es einwandfrei

**Comment by Matze9876** [comment]
Ich habe in diesem zusammenhang auch noch folgendes Problem:
ich hatte bei diesem Scenario ursprünglich das Feld durch CP bearbeiten lassen
und AD sollte dieses abfahren. Beim Starten von CP beendetet er ihnen diesen sofort wieder und warf mir einen LUA call stack in die LOG. Natürlich hatte ich CP im Verdacht, aber als ich ohne AD getestet habe, lief CP fehlerfrei.
Ich habe nun wieder eine ältere Beta Version (vom 06.04.) im Spiel und alles funktioniert wieder.

Anbei noch die LOG mit call stack.
(allerdings im Singleplayer auf der Felsbrunn)
[log.txt](https://github.com/Stephan-S/FS19_AutoDrive/files/6421776/log.txt)

**Comment by Axel32019** [comment]
@Matze9876 Bitte beta Version aktualisieren und ausprobieren. Danke!
