### ISSUE TITLE
Pathing Issue

### ISSUE THREAD

**Issue by stangman04** [Stephan-S/FS19_AutoDrive#191]
I am playing on Midwest Horizon which is a 4x map. I built custom courses but for some reason my vehicles are taking a long path back to the home farm when they should be taking a much shorter route. 
Now if I start them from the farm, they will go to the spot fine in the fastest path but coming back they are not. I will attach a screenshot from the autodrive course editor with some paint to show the quicker path (green) vs the longer path (red).

I have attached my config (zipped) and the pda png which is resized to 2048x2048. Also attached a picture of my settings. *Note I have had the "Use fastest route" set to yes and no change in behavior.* *Also I use 100m for the look ahead braking due to the speeds of trucks reaching 65mph on the roads*
![settings](https://user-images.githubusercontent.com/47079766/58768585-bb302400-856b-11e9-9e49-1369625cfe00.png)

![bad path](https://user-images.githubusercontent.com/47079766/58768562-5c6aaa80-856b-11e9-9a52-320fd6c9683a.png)
![Midwest_Horizon](https://user-images.githubusercontent.com/47079766/58768564-67253f80-856b-11e9-8c1e-e56b32220332.png)

[AutoDrive_Midwest_Horizon_config.zip](https://github.com/Stephan-S/FS19_AutoDrive/files/3245343/AutoDrive_Midwest_Horizon_config.zip)

**Comment by docgaming** [comment]
I can not find where to down load this map so i can test it.
the area on the map with the black dots has no destination there.
so what are you telling the driver todo what mode it's in etc

**Comment by stangman04** [comment]
I am just using the default Drive mode and I tried deliver as well. But just telling the driver to drive to the home farm is all.

See if this link works to download the map.... https://www.mediafire.com/folder/bym2jqxrgx4q6/OfficalLinks#nmxuwm2md9m9c

**Comment by docgaming** [comment]
ok so i tested it and for me it go's the correct way just change your setting to what you have posted and then recalculate the routes and it will work ok.

when use fastest route is on yes it will go the wrong way( long way round) i am not 100% sure why but i think it's cuz of the corner in the bottom right (see pic) fastest route don't like sharp corners so it avoids them.
![Screenshot_9](https://user-images.githubusercontent.com/48932718/58769993-f2222c00-85a3-11e9-8631-8305e1875679.png)

tip if you change anything in the setting menu make sure you recalculate the routes.

**Comment by stangman04** [comment]
I don't have the option to recalculate the course since I am not editing anything. But here is a video

https://drive.google.com/open?id=1OYjRA-5TyO3_DS8CsX8umPfHjD0JTOFr

**Comment by stangman04** [comment]
Well it seems the angles fixed the issue. Attached the new config with that corner corrected.
[AutoDrive_Midwest_Horizon_config.zip](https://github.com/Stephan-S/FS19_AutoDrive/files/3245507/AutoDrive_Midwest_Horizon_config.zip)

**Comment by docgaming** [comment]
did you recalculate the routes after changing to/from fastest route if you don't it will not change. if you don't have the option  to do it then rec 1 waypoint then delete it.

**Comment by stangman04** [comment]
I recalculated the routes after i edited that corner. I figured I was going to edit that anyways so I would do it then. But, yeah that was another option to get the recalculate showing.
