### ISSUE TITLE
Beta-RC : Spielabsturz / Game crash

### ISSUE THREAD

**Issue by TripleX1978** [Stephan-S/FS19_AutoDrive#1911]
AutoDrive Version: 1.1.0.9-RC neueste
Karte (falls relevant): NF Masch 4fach

Seitdem ich die Beta-Version installiert habe hängt sich das Spiel immer wieder komplett auf.
Nicht wie sonst, dass nach und nach Funktionen ausfallen, sondern es friert von einer auf die andere Sekunde komplett ein und kann nur noch über den Taskmanager beendet werden.
Verwende ich die 1.1.0.8 passiert das nicht.

[log.txt](https://github.com/Stephan-S/FS19_AutoDrive/files/6442901/log.txt)

**Comment by Axel32019** [comment]
Hallo @TripleX1978 , Die log ist unauffällig, der lua Fehler sollte nicht zum Einfrieren führen.
Daher bitte wie üblich config und vehicles.xml anfügen.

**Comment by jala15** [comment]
#1910 Same issue? More than 10 helpers?

**Comment by TripleX1978** [comment]
@jala15 I don't think it's the number of helpers cause it happens also when I use less than 10 helpers. With 1.1.0.8 I can use lot more than 10 and it never freezes.

@Axel32019 Daten kommen nachher.

**Comment by TripleX1978** [comment]
@Axel32019 Hier die Daten.

[savegame1.zip](https://github.com/Stephan-S/FS19_AutoDrive/files/6445886/savegame1.zip)

**Comment by TripleX1978** [comment]
Update:
AD : 1.1.1.0
CP : 6.03.00058

Ich lasse einen Häcksler die Grasschwad einsammeln und direkt auf einen Abfahrer überladen.
Das Spiel friert zu dem Zeitpunkt ein wenn der Abfahrer die 100% erreicht hat und versucht das Feld zu verlassen.
Ich habe es mit Mods und Standards getestet.
Bei 5 von 5 Versuchen friert das Spiel ein und es spielt keine Rolle ob zu dem Zeitpunkt 2 oder 20 Helfer im Einsatz sind.
Hier auch nochmal die Log.

[log.txt](https://github.com/Stephan-S/FS19_AutoDrive/files/6453547/log.txt)

**Comment by Axel32019** [comment]
@TripleX1978 Bitte mal mit CP Version 52 probieren.

**Comment by TripleX1978** [comment]
@Axel32019 Die hatte ich vorher auch schon installiert gehabt.

**Comment by Iwan1803** [comment]
Ich nutze immer noch die CP-Version 48 und habe keinerlei Abstürze.
Probier die vorgeschlagene Version doch mal bitte aus.

**Comment by KarlGutenberg** [comment]
Habe auch das Problem das sich mein Spiel aufhängt!
Sobald ich das Streckennetz aktiviere
version 1.1.1.0 RC1

siehe Video
https://youtu.be/WhxukTnXLzE
[log.txt](https://github.com/Stephan-S/FS19_AutoDrive/files/6471642/log.txt)

**Comment by TripleX1978** [comment]
@Axel32019 
@Iwan1803 

Habe die Ursache gefunden, weiß aber nicht warum das ein Problem war, da es mit den Vorgängern ja funktioniert hatte.
Hatte auf Feld 28 noch einen kleinen Rundkurs mit Ablade- und Wartepunkt für den Holmer Terra Variant angelegt. Als ich den gelöscht hatte gabs auch keinen Absturz mehr.

**Comment by TripleX1978** [comment]
@KarlGutenberg Bekomme die gleichen Meldungen sobald ich das Streckennetz aktiviere.

**Comment by Axel32019** [comment]
Beta-Version -> closed
