### ISSUE TITLE
[Question] Clearing crop - What does this mean?

### ISSUE THREAD

**Issue by Gonimy-Vetrom** [Stephan-S/FS19_AutoDrive#1914]
**Question:**   
text name="AD_task_clearcrop" text="Clearing crop"
When and in what cases is this message used? I never met him. Therefore, I can not understand how to translate it correctly and check.

**Comment by sashaman** [comment]
from CombineUnloaderMode.lua

```lua
            -- If we are in fruit, we should clear it
            if AutoDrive.isVehicleOrTrailerInCrop(self.vehicle, true) then
                AutoDrive.debugPrint(self.vehicle, AutoDrive.DC_PATHINFO, "[AD] CombineUnloaderMode:getTaskAfterUnload ClearCropTask...")
```

**Comment by sashaman** [comment]
ClearCropTask.lua
my guess is depending if there is enough room it clears crop area to "make room" so to say

**Comment by Gonimy-Vetrom** [comment]
Is it like CP probably when the pipe over the fruits is?

**Comment by Stephan-S** [comment]
After unloading a combine, the driver will try to leave the crop if he is currently standing inside it because the pipe was over the fruit.
