### ISSUE TITLE
[BUG] Version 1.1.1.0 AD does not transfer at the field to CP or CP does not take over at the field from AD - Version 1.1.1.0 AD übergibt am Feld nicht an CP bzw. CP übernimmt am Feld nicht von AD

### ISSUE THREAD

**Issue by haamic** [Stephan-S/FS19_AutoDrive#1915]
AutoDrive Version: 1.1.1.0
Release or selbsterstelltes zip: Release
Karte (falls relevant): Alle
Fahrzeug(art) (falls relevant): Alle

**Beschreibe den Bug**
seit 1.1.1.0 übergibt AD im Modus "Abholen Abliefern" am Feld nicht wieder an CP bzw. CP übernimmt am Feld nicht von AD.
Ich sammel mit dem Ladewagen und fahre zum Silo, nach Rückkehr am Feld bleibt das Fahrzeug stehen. AD aktives Ziel grün, schaltet nicht zu CP, welches seit verlassen des Feldes zum Abladen aktiv ist.

![AD-CP](https://user-images.githubusercontent.com/28841989/117576306-b96f2380-b0e5-11eb-8a97-5e58debbedf7.jpg)

Desweiteren, erfolgt die Wendung bei vollem Ladewagen neuerdings zur Feldgrenze hin, wodurch ständig gegen Hindernisse gefahren wird. In früheren Versionen erfolgte die Wendung zum Feld hin.

![wendung](https://user-images.githubusercontent.com/28841989/117576735-4cf52400-b0e7-11eb-9775-369583999cc0.jpg)

**Falls anwendbar - Schritte mit denen ich den Bug nachstellen kann**

**Screenshots**
siehe oben

**Comment by Axel32019** [comment]
Hallo @haamic , Bitte Debug Externe Schnittstelle aktivieren, probieren und log posten.

**Comment by haamic** [comment]
ich kann es mir nicht erklären, habe nichts verändert, plötzlich startet CP wieder ordnungsgemäss am Feld, auch hat sich das Wenden gebessert,  je weiter ich vom Start weg bis desto häufiger wendet er im Feld.
