### ISSUE TITLE
Abladen im Silo mit 2 Drehschemel (seitliches entleeren) [BUG]

### ISSUE THREAD

**Issue by eric4072** [Stephan-S/FS19_AutoDrive#1920]
AutoDrive Version: 1.1.1.0
Release or selbsterstelltes zip: Release
Karte (falls relevant): Alle
Fahrzeug(art) (falls relevant): alle Drehschemel

**Beschreibe den Bug**
Hallo,
habe die neueste Version von AD getestet. Das Gespann nähert sich dem Durchfahrsilo, bremst ab, berechnet die richtige Geschwindigkeit und beginnt beim durchfahren den ersten Hänger abzuladen. Am Ende bleibt dann das Gespann stehen, und im Stand wird dann erst der 2. Hänger abgeladen. Die Log ist fehlerfrei, aufgefallen ist es mir auf der MVP19-Karte beim Grashäckseln. Hatte aber noch keine Zeit es auf anderen Karten zu testen.

Ansonsten sscheint ja AD schon richtig gut zu funktionieren :-) Hoffe dass ihr dann in Zukunft noch die Kraft und Zeit habt, AD in den 22er zu holen.

LG
Eric

translated via google:

Hello,
have tested the latest version of AD. The combination approaches the drive-through silo, brakes, calculates the correct speed and begins to unload the first trailer as it drives through. At the end, the combination then stops, and only the second trailer is unloaded when it is standing. The log is error-free, I noticed it at MVP19.

Otherwise AD seems to be working really well :-) Hope that in the future you will still have the strength and time to bring AD into the 22s.

LG
Eric

**Falls anwendbar - Schritte mit denen ich den Bug nachstellen kann**

**Screenshots**
Falls relevant, bitte Screenshots beifügen

**Comment by Iwan1803** [comment]
Man kann schon per Hand nicht beide Anhänger vernünftig und gleichmäßig entladen. Warum sollte AD das dann können?

**Comment by Tensuko** [comment]
Wird sowas überhaupt in der realen Landwirtschaft praktiziert ?
Kann ich mir kaum vorstellen, mehrfache Bodenverdichtung, mehr Leistung um die 2 Trailer über den Acker zu ziehen...

**Comment by eric4072** [comment]
https://m.youtube.com/watch?v=QwTpu5nB8ZM

**Comment by rohne83** [comment]
HW80 ist dafür das Paradebeispiel, egal ob das Original aus der DDR oder die neueren Exemplare von u.a. Conow. Traktoren fahren damit fast immer im Doppelpack. Einfachtraktion sieht man eigentlich nur wenn er von LKW gezogen wird, der dann aber fast immer auch ne eigene Kipppritsche hat (IFA, Unimog, MAN und andere), also auch da im Endeffekt zwei Trailer abzuladen.
Im Prinzip das gleiche ist auch bei #1621 noch offen.

**Comment by Tensuko** [comment]
Ok das Video ist sehr interessant.
Ihr dürft nur eine Sache nicht vergessen.
Das was das menschliche Auge + Gehirn im stande ist zu leisten was die Aufnahme und Verarbeitung von Informationen angeht ist um ein vielfaches höher, als das was man im Code abbilden kann.

Rauf und Runter und 'einfach nur umdrehen' mag noch einfach sein, aber es gibt noch so viel mehr Situationen und Faktoren, die berücksichtigt werden müssen. Das wird auch teils gemacht, aber die Schwierigkeit steigert sich mit einem weiteren Trailer.

Man muss um einiges weiter vorausschauen, wo der Häcksler hin fährt um das Gespann richtig um die Kurve zu kriegen ohne irgendwo an zu ecken.

Jetzt könnte man sagen, das wird doch eh nur bei up/down rows so gemacht, aber es wird dann auch User geben, die das auf runden Feldern um Inseln rum, mehrfach im Kreis machen wollen und dabei muss natürlich das Gespann immer auf der richtigen Seite vom Häcksler fahren. Könnte euch ja mal überlegen, was da alles eine Rolle spielt. (Abstände, Wenderadius, turns, noReverse das heist auch in keine Situation geraten wo es nötig wäre etc).

**Comment by rohne83** [comment]
Du hast natürlich recht, dass das Häckseln und Dreschen bei zwei Anhängern deutlich schwieriger ist als mit einem, deswegen lass zB ich die CP/AD Helfer in solchen Situationen auch nicht allein sondern pass immer auf dass ich rechtzeitig eingreifen kann zum "baby sitten". Bei dem Issue hier gehts ja aber um das Abkippen der Ladung (auf in der Regeln schnurgerader Strecke) im Fahrsilo.
Wobei bei mir der Effekt ein klein wenig anders ist als bei eric4072. Er berichtet dass der zweite Trailer im Stand abgekippt wird, bei mir dagegen (mit HW80 auf der Felsbrunn) wird auch der in der Fahrt abgekipp. Allerdings wird der erste Trailer ebenfalls zusammen mit dem zweiten nochmal in Abkippstellung gebracht und nicht wieder zurückgekippt.

**Comment by Stephan-S** [comment]
Eigentlich ein interessantes Thema.
Wenn ich Zeit habe, schaue ich mir das vielleicht mal an.

Mein Lösungsansatz wäre aktuell folgender Check und Ablauf:
1.) Abfahrer merkt, dass er in ein Fahrsilo ablädt
2.) Abfahrer checkt ob er 2 Hänger hat
3.) Abfahrer dreht eine extra Runde nachdem er den ersten entladen hat.

Aber das weicht vom Ablauf her schon ziemlich vom allgemeinen Ablauf ab und ich müsste für Punkt 3 an verschiedensten Stellen checks einführen um den Normalablauf zu umgehen, die ich nur schwer für so einen Randfall rechtfertigen möchte, da es den Code nun mal komplexer und damit schwerer zu maintainen macht.

Ich schiebe es vorest mal auf die Hinterbank ;-)

**Comment by rohne83** [comment]
Also so aufwändig muss man das meines Erachtens gar nicht machen, würde je nach Streckennetz auch ziemlich viel Zeitverlust bedeuten dasselbe Silo zweimal anzufahren. Ich hab das jetzt nochmal auf mehreren Maps mit verschiedenen Anhängern probiert (HW80 SHA vom Modhub, und In-game Kröger HKD) und das Abladen beider Anhänger an sich funktioniert soweit auch schon heute: der Abfahrer fährt rein, kippt erst den ersten Anhänger ab bis ungefähr zur Hälfte der Länge des Fahrsilos, hält kurz um den Anhänger zurückzuklappen, und startet für die verbliebene Silolänge dann das Abladen des zweiten Anhängers. Das einzige was jedesmal auftritt ist, dass eben der vordere Anhänger (oder die LKW-Pritsche) beim Abladen des zweiten Anhängers ebenfalls nochmal mit in Abkippposition gebracht, aber eben am Ende des Silos dann nicht mehr zurückgekippt wird. Wenn das Silo verlassen wird, ist der vordere Anhänger also immer noch in Abkippstellung. Wenn dieser kleine "Bug" noch behoben werden könnte, würde das in meinen Augen schon völlig ausreichen.

Bilder sagen mehr als tausend Worte. So sieht das bei mir bei bisher allen Versuchen unabhängig von Map und Anhänger aus:
1. Abkippen des vorderen Anhänger bis ungefähr zur Hälfte der Silolänge, dort erstmal Zurückklappen dieses Anhängers
![fsScreen_2021_05_20_17_55_23](https://user-images.githubusercontent.com/71030138/120998743-a903a480-c788-11eb-841d-b935a039f6e4.png)

2. in der zweiten Hälfte Abkippen des hinteren Anhängers, aber leider auch nochmal Abkippen des bereits leeren vorderen Anhängers
![fsScreen_2021_05_20_17_55_43](https://user-images.githubusercontent.com/71030138/120998828-bc167480-c788-11eb-8a55-f54221155651.png)

3. nur der hintere Anhänger wird beim Verlassen des Silos zurückgekippt, der vordere bleibt in Abkippstellung
![fsScreen_2021_05_20_17_56_01](https://user-images.githubusercontent.com/71030138/120998877-c769a000-c788-11eb-997e-83cb142e1662.png)

**Comment by Iwan1803** [comment]
Diese Aussage ist nun aber eine andere als deine erste.
Entlädt er nun immer beide nacheinander, aber lässt den einen Anhänger immer in Kippstellung oder klappt es nur mit bestimmten Anhängern und mit anderen gar nicht?

**Comment by rohne83** [comment]
Ich selbst konnte bisher nur das eben beschriebene beobachten, egal mit welcher Abfahrkombination und auf welcher Map. Der vordere Anhänger bleibt beim Silo verlassen immer in Abkippstellung, ansonsten keine weiteren Auffälligkeiten/Probleme.
Das Verhalten das @eric4072 im Ursprungsbeitrag beschrieben hat, mit dem Abkippen des zweiten Anhängers nur im Stand, konnte ich dagegen noch gar nicht reproduzieren. Ist bei ihm vielleicht irgendein Sonderfall, evtl wegen der Map, dem Silo oder dem verwendeten Anhänger. Da kann er vielleicht noch ein paar mehr Informationen liefern.

**Comment by Iwan1803** [comment]
Gerade mal getestet (Vanilla-Fahrzeuge und -Anhänger) und ich habe das gleiche Phänomen wie @rohne83
Der erste Anhänger wird mit dem 2. noch mal entladen, obwohl er leer ist und bleibt dann in der Entladeposition.

**Comment by Iwan1803** [comment]
Poste den Vorschlag gerne auf der neuen github-Seite / Feel free to post the proposal on the new github page: https://github.com/Stephan-S/FS19_AutoDrive/issues/2147
