### ISSUE TITLE
Не едет к комбайну на разгрузку

### ISSUE THREAD

**Issue by Tocik** [Stephan-S/FS19_AutoDrive#1921]
Автомобили не едут к комбайну на разгрузку, пишет "планирование пути 1/2" иногда переключается на "2/2" и потом снова 1/2. Скриншоты прикрепил.  Пробовал перезапускать, ситуация не изменилась. Красный автомобиль перегнал на поле, запустил и он тут же поехал на разгрузку. С синим автомобилем этот фокус не сработал.
Помогите разобраться. 
Ранее в версии 1.1.07 и 1.1.0.8 эти же машины подъезжали, но только один раз, далее стояли в ожидании пока их вызовут, хотя комбайн был полон. А когда различными манипуляциями удавалось загрузить автомобиль, то он после разгрузки останавливался и чего-то ждал. 
![1](https://user-images.githubusercontent.com/65189100/118161243-06c1fc80-b428-11eb-921c-64ab02362cb5.jpg)
![2](https://user-images.githubusercontent.com/65189100/118161249-07f32980-b428-11eb-8019-bb30df128096.jpg)
![3](https://user-images.githubusercontent.com/65189100/118161251-088bc000-b428-11eb-8816-7188ef8f2aad.jpg)

**Comment by Iwan1803** [comment]
Sorry, english maybe?

**Comment by Tocik** [comment]
После нескольких повторных запусков синий автомобиль всё же поехал на загрузку, но вот разгружатсья он не спешит, пишет что ждёт пока отъедет комбайн. 
![4](https://user-images.githubusercontent.com/65189100/118161898-cd3dc100-b428-11eb-93f9-abbac6075a2d.jpg)

**Comment by Tocik** [comment]
> Sorry, english maybe?

Yes, one moment

**Comment by Tocik** [comment]
> Автомобили не едут к комбайну на разгрузку, пишет "планирование пути 1/2" иногда переключается на "2/2" и потом снова 1/2. Скриншоты прикрепил. Пробовал перезапускать, ситуация не изменилась. Красный автомобиль перегнал на поле, запустил и он тут же поехал на разгрузку. С синим автомобилем этот фокус не сработал.
> Помогите разобраться.
> Ранее в версии 1.1.07 и 1.1.0.8 эти же машины подъезжали, но только один раз, далее стояли в ожидании пока их вызовут, хотя комбайн был полон. А когда различными манипуляциями удавалось загрузить автомобиль, то он после разгрузки останавливался и чего-то ждал.

Cars do not go to the combine for unloading, writes "route planning 1/2" sometimes switches to "2/2" and then 1/2 again. Attached screenshots. Tried restarting, the situation didn't change. He overtook the red car on the field, started it up and immediately drove off to unload. This trick didn't work with the blue car.
Help me to understand.
Earlier, in version 1.1.07 and 1.1.0.8, the same cars arrived, but only once, then they stood waiting for them to be called, although the harvester was full. And when it was possible to load the car with various manipulations, then after unloading it stopped and waited for something.

**Comment by Tocik** [comment]
> После нескольких повторных запусков синий автомобиль всё же поехал на загрузку, но вот разгружатсья он не спешит, пишет что ждёт пока отъедет комбайн.
> ![4](https://user-images.githubusercontent.com/65189100/118161898-cd3dc100-b428-11eb-93f9-abbac6075a2d.jpg)

After several repeated starts, the blue car still went to load, but he was in no hurry to unload, he wrote that he was waiting for the combine to drive off.

**Comment by Tocik** [comment]
the third car made one trip and now stands and tries to find a way to the combine
![5](https://user-images.githubusercontent.com/65189100/118164451-cfede580-b42b-11eb-9538-5593029f1ab3.jpg)

**Comment by Tocik** [comment]
Based on my observations, in version 1.1.1.0, vehicles with mod trailers do not go to unload.

**Comment by Stephan-S** [comment]
Same as your other issue.
We greatly improved pathfinder capabilities.
So either wait for the next release or checkout our beta and alpha branches if you are interested.
