### ISSUE TITLE
[Pergunta] Parking

### ISSUE THREAD

**Issue by leo32128fs** [Stephan-S/FS19_AutoDrive#1922]
**Question:**   
I've got a question...
Hello, I would like to know how I can define a car park, I managed to do it in previous versions because parking P was lit when the routes were completed, now it is no longer lit, someone could help me! Sorry for the Inglês, I'm using the translator because I'm from Brazil

**Comment by 60erjonny** [comment]
Hallo

ADDED: CP park vehicle now use the park position from selected vehicle/attachment
ADDED: new key+mouse combination to set/delete P destination

left-mouse -> no change, will send vehicle to park in every AD Mode

**Comment by leo32128fs** [comment]
Thanks! helped me a lot
