### ISSUE TITLE
AD turns off after Trailer is full [BUG]

### ISSUE THREAD

**Issue by Gibbanator** [Stephan-S/FS19_AutoDrive#1923]
**AutoDrive Version:** 1.1.0.7
[log.txt](https://github.com/Stephan-S/FS19_AutoDrive/files/6487691/log.txt)

   
**Release or Custom Zip:** Release  
**Map (If applicable):** All  
**Vehicle / Type (If applicable):**   
**Multiplayer or Singleplayer:** Singleplayer  

**Describe the bug**  
I am running 2 trailers. After Trailer is full Auto Drives turns off. Have to manually turn it back on to continue to unload point. 
Here is video:
https://youtu.be/WqG8hV_Yq78
**If applicable - Steps to reproduce the behavior**  

**Screenshots**

**Comment by Stephan-S** [comment]
He is basically saying he can't find a way to the target.
The field exit strategy is set to 'Default' which means he will start from your First Target 'Field 7' and look for a way to 'Bunker 2' and then start planning a path off the field to reach Field 7 and continue on this path.

So it's likely that your Field 7 point is not properly connected and a dead end?

**Comment by Gibbanator** [comment]
why does it find it when I turn it back on.. as shown in video?

**Comment by Axel32019** [comment]
This is due to a fallback to closest network waypoint which is not intended - corrected with 1.1.1.0.
