### ISSUE TITLE
[BUG] After loading the "backup file" from the route manager, the huds of CP and AD disappear - Nach Laden der Backup-Datei" vom Routenmanager, verschwinden die Huds von CP und AD und können nicht wieder aktiviert werden

### ISSUE THREAD

**Issue by haamic** [Stephan-S/FS19_AutoDrive#1924]
AutoDrive Version: 1.1.1.0
Release or selbsterstelltes zip: Release
Karte (falls relevant): NewLands
Fahrzeug(art) (falls relevant):

**Beschreibe den Bug**
Nach Laden der Backup-Datei" vom Routenmanager, verschwinden die Huds von CP und AD und Streckennetz,welches geladen wurde , wird nicht angezeigt. Die huds können nicht wieder aktiviert werden, ich komme nur noch in die AD-Einstellungen mit der Tastenkombination.
das log füllt sich mit den Meldungen:
**D:/mod/LS2019-mods/FS19_AutoDrive/scripts/Hud/PullDownList.lua:434: bad argument #1 to 'insert' (table expected, got nil)**
auf Felsbrunn beispielsweise funktioniert es. und wird sofort aktualisiert.
Woran liegt das? sonst sind keine Fehler im log ersichtlich. Auch keine anderen Mods aktiv, ausser AD und die Map.
Erst nach Neuladen der Map ist das geladenen Streckennetz zu sehen.

[log.txt](https://github.com/Stephan-S/FS19_AutoDrive/files/6488988/log.txt)

**Falls anwendbar - Schritte mit denen ich den Bug nachstellen kann**

**Screenshots**
Falls relevant, bitte Screenshots beifügen

**Comment by Stephan-S** [comment]
Könntest du mir mal bitte die Backup Datei zukommen lassen die du probierst zu laden?
Entweder besteht der Fehler beim Laden oder schon beim Schreiben der Datei.

**Comment by haamic** [comment]
hallo, hier die Datei. Habs eben noch mal aktuell getestet. Spiel läuft weiter,  beide Huds von AD und CP verschwinden und man kann sie nicht mehr anzeigen lassen

[q3KMHwXr8vaTPVrb.xml.txt](https://github.com/Stephan-S/FS19_AutoDrive/files/6603708/q3KMHwXr8vaTPVrb.xml.txt)

Mir ist auch aufgefallen, das genau in der Mitte der Map ein einzelner Streckenpunkt erzeugt wird. Er erscheint als "Sackgasse" nach dem man debug Streckennetz eingeschalten hat. an dem Punkt hab ich aber nie einen Punkt erzeugt. und wenn man den löscht und das spiel speichert, ist er nach dem Neustart immer wieder da. Wo kann ich den in der AD.xml händisch löschen?

![sackgasse](https://user-images.githubusercontent.com/28841989/120914482-c8be9e00-c69e-11eb-8f43-4f7ed7cf7426.jpg)

[AutoDrive_config.xml.txt](https://github.com/Stephan-S/FS19_AutoDrive/files/6603722/AutoDrive_config.xml.txt)

**Comment by Stephan-S** [comment]
Hi, das ist ein Bug den wir schon gefixt haben. Mit der aktuellen alpha läuft  es wieder wie es soll
