### ISSUE TITLE
[BUG] CP -> Send AD park -> crash

### ISSUE THREAD

**Issue by Bobster82** [Stephan-S/FS19_AutoDrive#1925]
**AutoDrive Version:** 1.1.1.0   
**Release or Custom Zip:** Release  
**Map (If applicable):** USA Legend 2.1  
**Vehicle / Type (If applicable):** All   
**Singleplayer**  

**Describe the bug**  
Game crashes occasionally. Can be after 5min ingame or after 30min.

When used a modified version 1.1.0.7 from andremeyer123 (to work with latest CP version) no more crashes (did test over 2 hours)
I dont know where to start or to look, but AD triggers something on load(switch) of the vehicle that causes the crash.
This was my log when the game crashed:
[log (3).txt](https://github.com/Stephan-S/FS19_AutoDrive/files/6489338/log.3.txt)

I hope we can figure this out. If you need something from me, let me know.

Didnt know where the problem was, so 1st we contacted CP team.
See Thread with more info at CP where it started:
https://github.com/Courseplay/courseplay/issues/7198

edit:
I see I used 1.1.1.1-RC2 from @Stephan-S  ... but I used this version to see if "the problem" was solved, but it wasnt.
I had the same problem with the official 1.1.1.0, also another user, as seen in the CP thread, has the same problem.

**Comment by geka79** [comment]
had the same issue, unfortunatelly posted at the CP thread.

**Comment by Bobster82** [comment]
I hoped we had some reaction to this. Its been 4 days without anything happening. I really liked the 1.1.1.0 release, but now im stuck with the modified 1.1.0.7 release :(

**Comment by Stephan-S** [comment]
Sorry, but I don't see anything related to AD in the error messages. So there is absolutely nothing to work with here for me.
I never had this issue in my savegames and there are only the two of you who have reported this issue. So I don't really see where I should start looking for an issue.
Have you tried playing without CP for a while? Maybe it's still an issue with the interface between AD and CP.

**Comment by Bobster82** [comment]
Ah, thanks Stephan for reacting. It is strange that only a few have this problem. U might say its related to us ;)
I thought i had tested AD solo, but might have missed that test for some reason. Going for the 1.1.1.0 release without CP.

But it is strange that the 1.1.0.7 version didnt crash... might some things change in the interface between AD and CP as u said.
Can u point me in the direction where that has changed? or is it too much? 

Anyway thanks for AD again, still loving it... the new release is a real improvement, i really miss it haha

**Comment by Bobster82** [comment]
I have the latest CP v6.03.00060
So how do u have 6.04? :P

**Comment by Blackkappa** [comment]
On the CP Github page!
https://github.com/Courseplay/courseplay/releases/tag/6.04

**Comment by Bobster82** [comment]
> On the CP Github page!
> https://github.com/Courseplay/courseplay/releases/tag/6.04

*facepalm*   I thought I had the latest version, but urs is 2 days newer :P 
Only changes are with the speed... O well, can always try and see if that helps out. thx ;)

**Comment by Bobster82** [comment]
Nope, Still crashes with the same problem.

**Comment by 60erjonny** [comment]
Hallo
Diverse "Abstürze" habe ich AD1.1.1.0 sowohl, auch mit der "modified version 1.1.0.7 from andremeyer123" gehabt.
Dabei fing es mit der CP Versionen...6.03.00058 schon an bei mir und ging mit allen weiteren Versionen weiter.
Ich dachte es liegt an meinem Savegame und deswegen wollte ich hier nicht`s melden.
Nun, dabei friert mein PC ein...und es hilft nur noch ein Kaltstart...
Stelle hier mal 2 Log`s rein, weiß aber nicht ob die hilfreich sind...

**Comment by 60erjonny** [comment]
Hallo
Diverse "Abstürze" habe ich AD1.1.1.0 sowohl, auch mit der "modified version 1.1.0.7 from andremeyer123" gehabt.
Dabei fing es mit der CP Versionen...6.03.00058 schon an bei mir und ging mit allen weiteren Versionen weiter.
Ich dachte es liegt an meinem Savegame und deswegen wollte ich hier nicht`s melden.
Nun, dabei friert mein PC ein...und es hilft nur noch ein Kaltstart...

**Comment by Blackkappa** [comment]
Hallo Jonny, hast du schonmal die inputBinding.xml in deinem Dokumente/My Games/FarmingSimulator19 gelöscht?
Die XML wird bei Neustart vom Spiel neu erstellt und dadurch sind die Warnings bei mir verschwunden.

**Comment by Bobster82** [comment]
After more testing (for my crashes) I disabled parking after CP has finished and manual push the park button... No more crashes.
The bug happend when CP finished fieldwork and then AD parks the vehicle.
So AD or CP does something that generate that error... Who's bug is this? AD or CP ? (else I need to go back to CP team :P )

**Comment by Stephan-S** [comment]
Thanks for putting the analyzing effort in yourself!
To me it sounds like CP might not switch something off before they pass control back to AD and there is some CP stuff still active on the vehicle which causes this issue.
But that is just a guess! Could just as well be something in AD.
Although AD doesn't do anything with the vehicle nodes which seems to me as a root cause given the error messages.
So please pass this info back to the CP thread and then they can check if there is anything different when they send AD to park.
I don't really see any special behaviour in the AD code for the parking so it's unlikely to be on that side.

**Comment by andremeyer123** [comment]
@60erjonny 
inpubinding löschen und jeden mod wo error vorsteht  dann dürfte die log schon viel kleiner werden

**Comment by 60erjonny** [comment]
Hi
Oh danke für den Tipp, bis jetzt lief alles gut...!

**Comment by andremeyer123** [comment]
Dann schicke mal bitte eine log wenn du noch was hast .

**Comment by 60erjonny** [comment]
Hallo @andremeyer123 
Es passierte wieder...was mir dabei aufgefallen ist...
Es ging jetzt lange gut, bis ich einen Abfahrer mit mehreren Aufladepunkten ich los schickte.
Wenig später craschte das Spiel. Oder war es nur Zufall...
Die Log hat 34 MB...zu groß, für hier...?

**Comment by andremeyer123** [comment]
Lasse den Mod mal raus zum testen  \FS19_VehicleExplorer.zip\

**Comment by andremeyer123** [comment]
Kopiere mal den ersten teil der log bis der fehler anfängt.

**Comment by 60erjonny** [comment]
ok...habe den oberne Teil kopiert und eine neue Datei erstellt..
[Log.txt](https://github.com/Stephan-S/FS19_AutoDrive/files/6528511/Log.txt)

**Comment by andremeyer123** [comment]
Warning: Can't find barrier, something may have changed in the map hierarchy, the object will be restored.
wurde was an der karte geändert hast schon lua fehler bevor du ins spiel kommst
  Error: Index not found: 7|1   Error: Index not found: 7|2

**Comment by 60erjonny** [comment]
ja, habe wohl damit etwas übertrieben...

**Comment by geka79** [comment]
hab jetzt einen paar stunden das Game nebenbei laufen lassen.
CP und AD aktuell.
das einzige das ich nicht aktiviert habe, was das automatische Parken nach Beendigung der Arbeit in CP.
das Spiele läuft bis jetzt ohne Probleme.
Sobald ich jedoch das Parken aktiviere, crash nach ein paar Minuten (15-45min)

**Comment by Bobster82** [comment]
> heb het spel nu een paar uur aan de kant laten draaien.
> CP en AD up-to-date.
> het enige dat ik niet heb geactiveerd, dat is automatisch parkeren na het afronden van werkzaamheden in CP.
> het spel loopt tot nu toe zonder problemen.
> Zodra ik echter parkeren activeer, crasht het na een paar minuten (15-45 minuten)
> 
> Sorry, helaas is LOG niet opgeslagen :(

**Comment by Bobster82** [comment]
> hab jetzt einen paar stunden das Game nebenbei laufen lassen.
> CP und AD aktuell.
> das einzige das ich nicht aktiviert habe, was das automatische Parken nach Beendigung der Arbeit in CP.
> das Spiele läuft bis jetzt ohne Probleme.
> Sobald ich jedoch das Parken aktiviere, crash nach ein paar Minuten (15-45min)
> 
> Sorry, leider LOG nicht gespeichert :(

Hi,

Yes, thats what is happening with me too... The game aint crashing anymore when i turn that option down. So thats the problem we have ;)
Thanks for commenting too

**Comment by andremeyer123** [comment]
cp übergibt nur ad in 2 modis

**Comment by 60erjonny** [comment]
So jetzt verstehe ich überhaupt nichts mehr, nach weiteren erzungenen PC-Neustart zeigt CP keine eingefahrenen Kurse und Ordner nicht mehr an.

**Comment by Tocik** [comment]
I have a similar problem, when changing transport, the game freezes forever.

**Comment by Axel32019** [comment]
see #1945 -> closed
