### ISSUE TITLE
As of version 1.1.1.0 "all" settings are reset

### ISSUE THREAD

**Issue by KarlGutenberg** [Stephan-S/FS19_AutoDrive#1927]
AutoDrive Version: 1.1.1.0
Release or selbsterstelltes zip: Release
Karte (falls relevant): Alle
Fahrzeug(art) (falls relevant):

**Beschreibe den Bug**
Ab Version 1.1.1.0 werden "alle" Einstellungen zurückgesetzt
Das heißt:
Ich stelle mein:
Abfaher Feld 66---
abladen Hofsilo---
Ausfahrt Nächstgelegen usw....

Nach beenden des Spiels (Speichern) - Nach Neustart des Spiels sind alle Einstellungen weg!
Was mache ich da falsch?

![Screenshot (42)](https://user-images.githubusercontent.com/78603817/118782041-fd082100-b88d-11eb-9c01-5984e4362732.png)
![Screenshot (43)](https://user-images.githubusercontent.com/78603817/118782048-fe394e00-b88d-11eb-858e-297a4ef05ec6.png)
![Screenshot (44)](https://user-images.githubusercontent.com/78603817/118782050-fed1e480-b88d-11eb-9076-8c104d75399f.png) 

"Nach neustart"

[log.txt](https://github.com/Stephan-S/FS19_AutoDrive/files/6507129/log.txt)

**Comment by Axel32019** [comment]
Zip-Datei umbenannt - keine gute Idee!!!
Available mod: (Hash: dfa5ec6f2817bc11c6ace00d7f1c8208) (Version: 1.1.1.0) FS19_AutoDrive_1_1_1_0

**Comment by KarlGutenberg** [comment]
Habe die v.1.1.1.0 nochmals geladen
Geht wieder, warum auch immer!
Die Betitelung FS19_AutoDrive_1_1_1_0 war nicht aktiviert worden!
war nur um zu sehen wie es mit der v. FS19_AutoDrive_1_1_0_8 funktioniert.
