### ISSUE TITLE
Route Markers Are Missing. How to get them to return?[Question]

### ISSUE THREAD

**Issue by JayLawler** [Stephan-S/FS19_AutoDrive#1929]
**Question:**   
I've got a question...
somehow i've made my route markers disappear when i'm in edit mode. I can still see my landmarks and autodrive is working but I just can't see the route dots. I've tried making them appear on the ground and above the tractor.

**Comment by Iwan1803** [comment]
https://github.com/Stephan-S/FS19_AutoDrive/wiki/Edit-Mode

> Toggle showing waypoint bubbles = press RCTRL
