### ISSUE TITLE
Nur ne Frage

### ISSUE THREAD

**Issue by Mannie313** [Stephan-S/FS19_AutoDrive#193]
Hallo @Stephan-S 

Wäre es möglich das AD nicht nur einen Hänger nimmt sondern das mann auch nen Zweiten hinten drann hängen kann. Für weite strecken eignen sich manchmal 2 abfahrer mit 2 hängern.

Beim Dreschen, Früchte kaufen oder Verkaufen.

MFG Mannie313

**Comment by Stephan-S** [comment]
Hallo,

derzeit ist es bei mir keine Priorität, aber langfristig möchte ich auch mehrere Anhänger unterstützen.

Beste Grüße,
Stephan
