### ISSUE TITLE
[Feature Request]

### ISSUE THREAD

**Issue by tinyjudoka** [Stephan-S/FS19_AutoDrive#1930]
**Is your feature request related to a problem? Please describe.**  
The unload combine feature works great, I love it, however it needs a bit of work. What I am getting at in this request is that my truck and trailer "binds up" when it reverses from a combine, and therefore getting stuck in the mud, or just trying to reverse for all of eternity never getting anywhere.

**Describe the solution you'd like**  
My main suggestion right now is an option to disable the "reversing from combine" part of the unloading sequence.

**Describe alternatives you've considered**  
I have tried and will try a bit more to alter the scripts myself to just try and remove this from the unloading sequence but I haven't succeeded with this as of writing this.

**Comment by Stephan-S** [comment]
We changed the behaviour for the next release to properly reverse without jackknifing the trailer.
This should fix your issue.
