### ISSUE TITLE
[Question] Refueling the sower with fertilizer

### ISSUE THREAD

**Issue by erksartori** [Stephan-S/FS19_AutoDrive#1931]
**Question:**   
I've got a question...

Neste caso , estou utilizando uma semeadeira com fertilizante, e ao passar para reabastecer o implemento ele nao abastece corretamente, essa semeadeira em questao ela abre o compartimento da semente primeiro e quando ela fecha logo em seguida ele abre a do fertilizante, porem neste video ela nao esta fazendo corretamente.

In this case, I'm using a seeder with fertilizer, and when passing to replenish the implement it does not supply properly, this sowinger in question it opens the seed compartment first and when it closes soon after it opens the fertilizer, but in this video it is not doing correctly.

Video: https://www.youtube.com/watch?v=JKU5cg2Prxc

Agradeço a atenção

I appreciate the attention

**Comment by Stephan-S** [comment]
Place the marker a few meters farther back, so that the vehicle reaches it after it has already reached the seed loading trigger

**Comment by erksartori** [comment]
Mas o marcador esta depois dos silos de reabastecimento se eu colocar ele mais pra tras ele nao para nos outros, e tenho um mapa que esta funcionando perfeito mas nao com esse tipo de implemento

But the marker is after the refueling silos if I put it more behind it not to the others, and I have a map that is working perfect but not with this type of implement

**Comment by erksartori** [comment]
Bom, eu fiz um vídeo do mesmo mapa, com outro implemento da mesma categoria, sementes e fertilizante. Note que esta na mesma posição e nao ocorre o mesmo problema.

Well, I made a video of the same map, with another implement of the same category, seeds and fertilizer. Note that it is in the same position and the same problem does not occur.

Video:  https://www.youtube.com/watch?v=-PIyq0R0EUk

**Comment by Stephan-S** [comment]
Have you tried setting the max silo distance higher? Default is 25m and that could just be too short for that case.

**Comment by erksartori** [comment]
Não fiz video agora, mas ocorre o seguinte:
1- Mudei o gatilho para 10m, e ao passar pelo silo de semente, nem abriu o compartimento. 
2 - Mudei o gatilho para 50m, ele abre o compartimento mas so o do fertilizante, ele nao abre o da semente. 
3 -  fiz um teste e mudei a configuracao para fertilizante, onde estava semente, e nada.

I did not make video now, but the following occurs:
1- I changed the trigger to 10m, and when passing through the seed silo, did not even open the compartment. 
2 - I changed the trigger to 50m, it opens the compartment but only the fertilizer, it does not open the seed. 
3 - I did a test and changed the configuration to fertilizer, where it was seed, and nothing.

**Comment by Axel32019** [comment]
no update -> closed
