### ISSUE TITLE
Zielpunkte werden nicht richtig angezeigt / Target points are not displayed correctly

### ISSUE THREAD

**Issue by Andy2612** [Stephan-S/FS19_AutoDrive#1932]
Es ist zwar nur ein Schönheitsfehler aber dennoch ein Fehler.
Ich nutze die Version 1.1.1.0 und bei dieser Version werden neue Zielpunkte nicht direkt in der PDA oder MiniMap angezeigt, erst nach Neustart des Game werden sie wieder korrekt angezeigt.
Gleiches trifft auch zu wenn ein Zielpunkt gelöscht wird, er ist zwar In Game gelöscht wird aber weiterhin auf der PDA und MiniMap angezeigt.

![20210523091709_1](https://user-images.githubusercontent.com/61479274/119251636-de649b80-bba7-11eb-9dcd-27a502e28757.jpg)

Hier auf dem Bild ist zu sehen das ich den Zielpunkt "Feld 21/22" gesetzt habe,aber er nicht in der MiniMap nicht angezeigt wird.

It's just a blemish, but it's a flaw nonetheless.
I use version 1.1.1.0 and with this version new target points are not displayed directly in the PDA or MiniMap, they are only displayed correctly again after restarting the game.
The same applies if a target point is deleted, although it is deleted in game, it is still displayed on the PDA and MiniMap.

Here on the picture you can see that I have set the target point "Field 21/22", but it is not displayed in the MiniMap.

**Comment by Stephan-S** [comment]
Kommen dabei Fehler im Log?
Ich kann den Fehler auf die Schnelle nicht nachstellen. Entweder das Problem besteht in der aktuellen Beta nicht mehr oder es ist etwas speziell an deinem Spielstand.

Wenn du möchtest, teste es doch mal auf anderen Spielständen und/oder teste mal die AD Version aus dem Alpha- bzw- Beta Branch und bericht dann nochmal.
Und bitte mit Log Datei, falls der Fehler noch besteht.

**Comment by Andy2612** [comment]
Hallo, 
der Fehler tritt bei mir nur auf wenn ich die 1.1.1.0 verwende. Wenn ich dann wieder zurück auf eine ältere Version gehen z. B. die aus dem ModHub geht alles wieder(also das die Zielpunkte angezeigt werden). 

Habe jetzt ein Testgame auf der Felsbrunn und auch nur mit AD 1.1.1.0 und CP 6.4. 

Habe einmal eine AD.Zip erstellt darin sind einmal die AutuDrive_config und ...UserData, vielleicht helfen die auch weiter und natürlich die log ist auch dabei.

[AD.zip](https://github.com/Stephan-S/FS19_AutoDrive/files/6603127/AD.zip)


[log.txt](https://github.com/Stephan-S/FS19_AutoDrive/files/6603110/log.txt)

**Comment by Axel32019** [comment]
@Stephan-S Das ist doch das Telemetry-Thema, oder?

**Comment by Stephan-S** [comment]
Vermutlich ist es der Fehler der damit reinkam, ja.
Dann hat sich das Thema also mit dem nächsten Release erledigt. Sehr gut

**Comment by Andy2612** [comment]
Fehler ist nach dem ersten Test mit der Version 1.1.1.2 nicht mehr vorhanden.
