### ISSUE TITLE
The car does not go to unload to the combine.

### ISSUE THREAD

**Issue by Tocik** [Stephan-S/FS19_AutoDrive#1935]
**AutoDrive Version:** 1.1.1.0   
**Release or Custom Zip:** Release  
**Map (If applicable):** All  
**Vehicle / Type (If applicable):*all*   
**Multiplayer or Singleplayer:** Singleplayer  
**Describe the bug**  
Everything was done correctly, the car drove up several times, loaded, transported products from the combine. But at some point he stopped doing it. He stood waiting for more than 15 hours. 
**If applicable - Steps to reproduce the behavior**  
**Screenshots**  An example of how it looks
![1](https://user-images.githubusercontent.com/65189100/119373647-4eb31000-bcc1-11eb-9342-5762f3d31d69.jpg)

**Comment by Stephan-S** [comment]
This should be resolved with the next release.
But please note, that AD is not a human driver and cannot always guarantee to find a path.
You are welcome to use the version currently in the beta branch and check if that works better for you.
