### ISSUE TITLE
Spiel startet nicht mehr

### ISSUE THREAD

**Issue by IchDummer** [Stephan-S/FS19_AutoDrive#1939]
**AutoDrive Version:** 1.1.x.x   
**Release or Custom Zip:** Release  
**Map (If applicable):** All  
**Vehicle / Type (If applicable):**   
**Multiplayer or Singleplayer:** Singleplayer  

**Describe the bug**  

**If applicable - Steps to reproduce the behavior**  

**Screenshots**  
Spiel startet nicht mehr
[log.txt](https://github.com/Stephan-S/FS19_AutoDrive/files/6554963/log.txt)

**Comment by Iwan1803** [comment]
Super... ich befrage mal meine Glaskugel... 🙄
Was genau passiert wann? Was wurde vorher zuletzt gemacht? Wurde was an Mods & Co. verändert?
Laut Log schmeißt zuerst UniversalPassenger einen Fehler und danach dann AD.

**Comment by IchDummer** [comment]
wie ich gerade geshen habe gibt es unter #1934 das gleiche Problem.

**Comment by Stephan-S** [comment]
Sieht so aus als gebe es ein Problem mit einem/allen Fahrzeug Konfigurationen in der vehicles.xml
Dort stehen die Ordnernamen von AD eingetragen unter "groups" bei jedem Fahrzeug.
Hast du zufälligerwiese ein Komma in einem deiner AutoDrive Ordner genutzt?
Dann würde es das Problem erklären.

Falls ja, starte das Spiel mal ohne AD und speichere dir vorher die AD Konfig aus dem Savegame ab.
Dann schaust du mal in der Konfig ob dort irgendwo ein verdächtiger Gruppenname auftaucht und änderst ihn entsprechend in jedem Ziel ab.

<mapmarker>
        <mm1>
            <id>333.000000</id>
            <name>Shop</name>
            <group>**All**</group>
        </mm1>
        
        ...
        
        
     Dann kannst du die AD Datei wieder einfügen und beim nächsten Start AD als Mod wieder einschalten.

**Comment by IchDummer** [comment]
Vielen Dank für die Hilfe. hatte tatsächlich beim letzten Gruppennamen ein Komma statt einem Punkt gesetzt. Spiel läuft wieder. Nochmals vielen Dank.
