### ISSUE TITLE
[Question] Version 1.1.1.0 zum Modhub

### ISSUE THREAD

**Issue by Sacred-Shadow** [Stephan-S/FS19_AutoDrive#1941]
**Question:**   
Im Modhub haben wir aktuell noch die Version 1.1.0.7.
Nun ist auch CP auf Modhub erschienen und verweist auf die AD 1.1.1.0, die man nur auf Github findet. 

Wäre doch gerade nicht verkehrt, die 1.1.1.0 mal gleich in den Modhub zu heben. :)

**Comment by Stephan-S** [comment]
Ich möchte noch auf den nächsten Release warten. Also dann wohl die 1.1.1.2
Die solle auch in Kürze erscheinen und dann gibts auch nochmal einen Modhub Release
