### ISSUE TITLE
AD-Beta : Auftanken funktioniert nicht weil keine Adblue-Station vorhanden ist / Refuel does not work cause adblue-Station is missing

### ISSUE THREAD

**Issue by TripleX1978** [Stephan-S/FS19_AutoDrive#1942]
AutoDrive Version: 1.1.1.1-RC3

Hatte vor Ewigkeiten mal eine Tankstelle mit Adblue installiert und sofort wieder deinstalliert ohne Adblue auch nur einmal verwendet zu haben.
Jetzt habe ich das Problem, dass AD nicht mehr autom. zum Auftanken fährt, weil keine Tankstelle mit Adblue vorhanden ist.
Wenn ich manuell zur Tankstelle fahre wird ohne Probleme nachgetankt.

**Comment by Iwan1803** [comment]
Der AdBlue-Mod schreibt einen neuen Eintrag für die Fahrzeuge in die vehicles.xml.
Im Tag "fillUnit" jedes Fahrzeugs gibt es dann einen _fillType="DEF"_. Wenn du den überall rauslöschst, sollte das Problem verschwunden sein.

**Comment by TripleX1978** [comment]
@Iwan1803 
Danke für den Tipp. Hab es überall gelöscht, das Spiel neu gestartet und das Problem war immer noch da.
Die zuvor gelöschten Einträge waren auch alle wieder vorhanden.

**Comment by Iwan1803** [comment]
Hast du alle Mods, welche irgendwie mit AdBlue zu tun haben, aus dem mods-Ordner gelöscht?

**Comment by TripleX1978** [comment]
Meines Wissens nach war es nur die Tankstelle.
Oder wird auch irgendwas in die Map geschrieben?

**Comment by Iwan1803** [comment]
Keine Ahnung, da du da ja (mal wieder) kaum Infos lieferst.

**Comment by TripleX1978** [comment]
Welche Infos bräuchtest du denn?

**Comment by Stephan-S** [comment]
Bist du sicher dass du das Spiel geschlossen hattest also du die Datei bearbeitet hast? Sonst hat es das Spiel natürlich gleich wieder überschrieben.
Ansonsten brauchen wir natürlich immer ein Log, dann kann man wenigstens sehen, welche Mods du beispielsweise installiert hast.

Aber da das ganze ja kein AutoDrive-Problem an sich ist, würde ich hier gerne zu machen.
Bei weiteren Problem mit dem Thema, meld dich doch mal im Discord bei uns, da wird dir sicher weiter geholfen.
https://discord.gg/9D4B5hX
