### ISSUE TITLE
[Question] neuerungen 1.1.1.1 rc3 ?

### ISSUE THREAD

**Issue by andreasthu** [Stephan-S/FS19_AutoDrive#1944]
**Question:**   
I've got a question...
Hallo Leute 
Hab nun die aktuelle beta, 1.1.1.1 rc3 runtergeladen.
Mir ist aufgefallen,  das man mit Shift + Mausklick keine rückwärtskurse machen kann.
In den Hilfe-popups habe ich was von niederrangigeren Strecken gelesen und von Start der Aufzeichnung mit mausrad hoch,...
Gibts wo einen thread oder ein Wiki mit den Änderungen und neuen Features?
Check das diesmal überhaupt nicht. 
(Iwan macht ja immer so hübsche news-videos)
Es gibt aber leider nix .
Lg
Andreas

**Comment by Iwan1803** [comment]
Es wird (wie immer) eine Releasenote geben, wenn die Beta in den Release übernommen worden ist, weil sich bis dahin ja noch Dinge verändern können 😉
Ansonsten gilt #1247

**Comment by andreasthu** [comment]
Hallo Iwan.
Ich 
Möchte die beta ja testen und Feedback geben.
Wenn ich aber nicht weiß was neu ist oder geändert, kann ich das ja nicht explizit ausprobieren.
Eine kleine Textdatei z.b. mit Notizen würd schon reichen, oder ein thread bei den issues.
Ich hab heute z.b. gemerkt das man mit shift und linksklick keine Punkte mit heölblauem rückwärtsfahrt-pfeil verbinden kann.
Und das man mit alt und linke maustaste einen dunkelblauen 2wege kurs erzeugt hab ich dadurch erst rausgefunden.
Dann hab ich in den tastatureinstellungen den info Popup key gesehen, aktiviert, und hab gelesen das man einen niederrangigen Kurs auch erstellen kann. Dieser soll mit Maustaste rauf aktiviert werden können. Aber was ist die maustaste rauf?
Und solche Dinge eben.
Lg
Andreas

**Comment by wallsingham** [comment]
Hallo @Stephan-S ,
danke für die ausführliche Aufstellung. 
Ich bin auch gern dabei die letzten Commits zu testen. ;-)
Mit der letzten Alpha und generell bei eingeschalteter "Blue Line Route Finder" gibt es Collisonen auf den blauen Linien. Sich entgegenkommende Fahrzeuge warten nicht bis die Strecke von Gegenverkehr frei ist. Muss irgendwo noch etwas eingestellt werden oder ist das eine Sache die im Code angepasst werden muss. 
![grafik](https://user-images.githubusercontent.com/56741972/120603179-05df2200-c44c-11eb-91f6-ee4f72c4b113.png)

Viele Grüße
Hektor

**Comment by wallsingham** [comment]
hab's grad noch mal mit dem letzten Commit 4d265cb getestet. Es verhält sich genauso. 

![grafik](https://user-images.githubusercontent.com/56741972/120633850-e86d8080-c46a-11eb-8867-be7b231eeab5.png)

**Comment by andreasthu** [comment]
Danke dir für die Notizen
:-)
Lg
Andreas

**Comment by andreasthu** [comment]
> hab's grad noch mal mit dem letzten Commit [4d265cb](https://github.com/Stephan-S/FS19_AutoDrive/commit/4d265cbcc2fbb577a9112ed68b3f4ecc6791bf21) getestet. Es verhält sich genauso.
> 
> ![grafik](https://user-images.githubusercontent.com/56741972/120633850-e86d8080-c46a-11eb-8867-be7b231eeab5.png)

Hallo hector
Irgendwie fehlen mir auf diesem Bild zwei AD punkte, statt und Ende des einen Fahrzeuges ist da, statt und Ende vom 2. Fahrzeug fehlen mir irgendwie, müssten ja auf den anderen zwei grünen Linien auch Punkte sein.
Lg
Andreas

**Comment by wallsingham** [comment]
Hallo Andreas,

Route Fendt:  A > Anfang
Route Fiat:  B > Ende
![grafik](https://user-images.githubusercontent.com/56741972/120637786-9bd87400-c46f-11eb-9c0d-b5c5aae72d1a.png)
LG Hektor

**Comment by wallsingham** [comment]
Ich habe nun durch ausprobieren lokaliesieren können dass es am Commit 7b9da05 liegt.
Dort wurde die Datei FS19_AutoDrive/scripts/Modules/CollisionDetectionModule.lua angepasst.
Wenn man die vorige Version dieser Datei nihmt, funktioniert die Erkennung vom Gegenverkehr sogar auch mit aktuellen Commit 4d265cb (Vorrausgesetzt man ersetzt die CollisionDetectionModule.lua). 
Vielleicht kann @Axel32019  da mal nachsehen.
LG Hektor

**Comment by andreasthu** [comment]
> Hallo Andreas,
> 
> Route Fendt: A > Anfang
> Route Fiat: B > Ende
> ![grafik](https://user-images.githubusercontent.com/56741972/120637786-9bd87400-c46f-11eb-9c0d-b5c5aae72d1a.png)
> LG Hektor

Achja, sorry, Denkfehler meinerseits.
Bei AD braucht man ja keinen Startpunkt.
Werd es auch mal testen

Btw, spiele ebenfalls auch auf spectacle Island
Lg
Andreas

**Comment by Stephan-S** [comment]
Probiers mal mit etwas längeren grünen Anfahrtswegen.
AD prüft es nicht mehr, wenn der Fahrer schon über den Stopppunkt (~3-5 Punkte oder so vor der blauen Linie) drüber ist.
Dann ist es halt schon zu spät.

Genau so wenn du blaue Linien direkt am Feldrand als Abfahrt hast, dann ist er ja auch direkt schon auf dem Kurs und es macht eh keinen Sinn mehr zu prüfen.

Die Änderungen in dem commit sollten die Überprüfung nur etwas unregelmäßiger machen um die Performance zu verbessern. Daher kann es unter Umständen ohne den commit noch gerade so gereicht haben bei deinen Kurzen grünen Strecken.

**Comment by Stephan-S** [comment]
Alles klar, Fehler gefunden. Danke für die Meldung :-)

**Comment by wallsingham** [comment]
Große Klasse. Danke dir. :-)

**Comment by Stephan-S** [comment]
Ich mache dann mal hier zu. 
Wenn ihr was unter euch oder auch gerne mit mir/uns diskutieren/besprechen wollt, bietet sich für so etwas unser Discord viel besser an:
https://discord.gg/9D4B5hX
