### ISSUE TITLE
Streckennetz wir im Edit-Modus nicht mehr angezeigt.

### ISSUE THREAD

**Issue by HappyCow2020** [Stephan-S/FS19_AutoDrive#1948]
Auf all meinen Maps wird das Streckennetz im edit-modus nicht mehr angezeigt. Die Namen der Haltepunkte sind zu sehen. AutoDrive kann auch normal benutzt werden. Aber im editor kann man nichts mehr ändern oder neu anlegen. Trat plötzlich bei 3 verschiedenen maps auf. Keine neuen mods eingefügt. Egal ob Version 1.0.0.8 oder 1.1.0.0.

**Comment by Iwan1803** [comment]
Vermisst du nur die roten Bubbles, welche man mit der rechten STRG-Taste ein-/ausblenden kann oder was genau ist das Problem?
Screenshots, Logfiles und die AD-Configs könnten ansonsten vielleicht helfen....

**Comment by HappyCow2020** [comment]
Wie oben geschrieben, werden nur noch die Namen der Haltepunkte angezeigt. Weder Linien, noch Punkte
![ScreenHunter 335](https://user-images.githubusercontent.com/85451114/121006872-aeb1b800-c791-11eb-911a-5f114a84c678.jpg)

**Comment by HappyCow2020** [comment]
Da mir wohl nicht mehr zu helfen war, hab ich nun LS neu installiert, AutoDrive heruntergeladen und in den Mods-Ordner verschoben. Aber Autodrive wird mir im Spiel nicht angezeigt, auch taucht es nicht als mod in der Übersicht auf.

**Comment by Iwan1803** [comment]
...und nun sollen wir raten, was du wo runtergeladen hast?
Entweder lädst du AD 1.1.0.7 aus dem Ingame-Modhub runter oder die aktuelle Version hier von github.
Für letzteres muss man nur auf der Startseite runterscrollen, dem Downloadlink folgen und dann einfach die FS19_AutoDrive.zip im mods-Ordner abspeichern.

**Comment by HappyCow2020** [comment]
Raten braucht man da nicht. Natürlich den neuesten AutoDrive (1.1.1.0) bei Github. Sonst würde ich ja hier auch nicht fragen. Und wie oben geschrieben, in den Mods-Ordner geschoben. Aber danke für die nette Aufnahme hier.

**Comment by Iwan1803** [comment]
Es gibt leider viele, welche den falschen Download machen und deshalb frage ich nach: hast du über den roten Weg runtergeladen?
![image](https://user-images.githubusercontent.com/47528836/121529849-16b80680-c9fd-11eb-880c-793a1027328e.png)
Wenn ja, dann ist das leider falsch und du musst über den grünen gehen.
Lad die Datei hier bitte runter und versuch es dann noch mal: https://github.com/Stephan-S/FS19_AutoDrive/releases/download/1.1.1.0/FS19_AutoDrive.zip
Achte bitte auch drauf, das keine andere AutoDrive-Datei mehr im mods-Ordner liegt.

**Comment by HappyCow2020** [comment]
Genau das hab ich gemacht. War aber auch nicht das Problem. Nach der Neu-Installation vom LS und neu Herunterladen aller mods habe ich übersehen, daß der LS selber zwischenzeitlich ein update bekommen hat. Und ohne dieses laufen einige Sachen einfach nicht. aber am Ende hat sich ja alles geklärt und ich bin wieder glücklich.

**Comment by Axel32019** [comment]
@HappyCow2020 Dann schließe ich hier mal.
