### ISSUE TITLE
AIVE Functions

### ISSUE THREAD

**Issue by NdMoreSpd** [Stephan-S/FS19_AutoDrive#1949]
**Is your feature request related to a problem? Please describe.**  
No

**Describe the solution you'd like**  
I find the function (and reliability) of AD to exceed that of CP in so many ways. The only place I find it falls short is helping in the field (which I understand CP is designed to handle, though I find it clunky and unreliable). While AIVE appears to have died on the vine (I can not seem to find a full version of it was ever released and what I find appears outdated) some of it's simpler functions (circle field work for example) would be an AMAZING addition to AD in that I could rely on AD without having to try to integrate CP. 

**Describe alternatives you've considered**  
As CP has recently appeared on the In-Game Giants Mod-Hub I decided to try to both use it in stand alone (no AD) as well as tried to implement it in conjunction with my existing AD courses. So far I have only dealt with random glitches on both accounts. I find CP works pretty decent for field work alone but fails miserably when it comes to those things AD works wonderfully on, transit and simple harvester servicing.

**Additional context**  
None.

**Comment by Iwan1803** [comment]
AIVE can be downloaded her: https://github.com/Mogli12/AIVehicleExtension
Last update was 2 month ago.
AD will never intergrate feature for doing fieldwork as there are CP and AIVE the specialist for.
Or have I misunderstood something?

**Comment by NdMoreSpd** [comment]
Thank you for the super fast reply, sorry kids+bedtime distracted me.
I downloaded the latest you linked above, I do wish it was a little cleaner (very minor things, what version is it now in particular) and please do not misunderstand I think it is great but I think if AD and AIVE were on mod together they would be a good alternative to CP as a whole. I simply find CP to be more difficult to use and more prone to random hiccups than I find AD (near flawless in operation, rarely making any problems for me). 

CP tries to do some of the things that AD does, I didn't think suggesting AD doing some of the simpler things CP can do would be bad. My apologies if it sounded that way.

Mike

**Comment by Iwan1803** [comment]
No further comment -> closed.
