### ISSUE TITLE
parameter "maximum silo area"

### ISSUE THREAD

**Issue by Crinouche** [Stephan-S/FS19_AutoDrive#1950]
In the Autodrive parameters, at the level of the "maximum silo area", would it be possible that there is a function that allows us to define:
- either all vehicles at once (as is currently the case)
- or each vehicle independently. With some tractors attached to a seed drill, it takes me 200 m to load the seed and fertilizer (photo 2), but with a trailer, to deliver cereals, for example, 50 m is sufficient. By leaving 200 m for all vehicles, they slow down to 3 km / h much too early before reaching the delivery point.
- 
![image](https://user-images.githubusercontent.com/36656729/121064416-d91e6800-c7c7-11eb-8ef4-a9daa6e0571d.png)
![image](https://user-images.githubusercontent.com/36656729/121064572-0d922400-c7c8-11eb-991a-32404b001036.png)

**Comment by Iwan1803** [comment]
Poste den Vorschlag gerne auf der neuen github-Seite / Feel free to post the proposal on the new github page: https://github.com/Stephan-S/FS19_AutoDrive/issues/2147
