### ISSUE TITLE
[Question] problems with FS19

### ISSUE THREAD

**Issue by matty2123** [Stephan-S/FS19_AutoDrive#1952]
Hello can anyone help me please I’m having big problems with fs19 and I noticed this in my log can anyone shed some light 
`Info: [AD] Info: g_server table: 0x015cd2aa49c8 g_client table: 0x015cd2aa4dc8 g_dedicatedServerInfo nil getUserProfileAppPath C:/Users/matty/OneDrive/Documents/My Games/FarmingSimulator2019/ getIsClient true getIsServer true isMasterUser true`
regards Matt

**Comment by Iwan1803** [comment]
This is not an error or warning line.
Some more informations about your problems maybe could help: a description of the problems, maybe screenshots, the log file,...

**Comment by matty2123** [comment]
[log4.txt](https://github.com/Stephan-S/FS19_AutoDrive/files/6613404/log4.txt)
I’m getting xml blank document never had it before

**Comment by matty2123** [comment]
Found issue closed
