### ISSUE TITLE
[Feature Request]

### ISSUE THREAD

**Issue by Crinouche** [Stephan-S/FS19_AutoDrive#1955]
Hello,

Could it be possible that the tractor with the trailer is a little further forward? because the forage harvester does not detect the trailer. (photo 1 & 4) I have this problem with the trailed forage harvester. And with the Krone X1100, if the trailer is a little further forward, it's better too! (photo3)
I tested all the possible settings but the tractor with the trailer does not advance any further! (photo 2)
In general, in real life, the 2 tractors drive side by side ...
Thanks in advance,
![image](https://user-images.githubusercontent.com/36656729/121551391-e5950180-ca0f-11eb-9626-efb58dea7103.png)
![image](https://user-images.githubusercontent.com/36656729/121553424-8afca500-ca11-11eb-84a4-ff7b497b3c89.png)
![image](https://user-images.githubusercontent.com/36656729/121558048-9782fc80-ca15-11eb-813c-4159a76a4f63.png)
![image](https://user-images.githubusercontent.com/36656729/121559158-a28a5c80-ca16-11eb-9d35-b2392516c708.png)

**Comment by Dzi4d3k** [comment]
For me it looks like front of tractor with trailer is aligned with swath picker, therefore for trailed thresher example is little too far. behind

**Comment by Crinouche** [comment]
_> Pour moi, il semble que l'avant du tracteur avec la remorque soit aligné avec le ramasseur d'andains, donc pour l'exemple de la batteuse traînée est un peu trop loin derrière._

I don(t understand what you want to say?

**Comment by Gibbanator** [comment]
> _> Pour moi, il semble que l'avant du tracteur avec la remorque soit aligné avec le ramasseur d'andains, donc pour l'exemple de la batteuse traînée est un peu trop loin derrière._
> 
> I don(t understand what you want to say?

he said:
To me it seems that the front of the tractor with the trailer is aligned with the swath pick-up, so for the example the trailed threshing machine is a bit too far behind

**Comment by Dzi4d3k** [comment]
Apologies for confusion, seems Google won't help to translate what I meant.
From you screenshoot, it looks like AutoDrive-ed tractor is trying to align with thresher's swath picker (front of thresher). Therefore pulled thresher has longer distance to trailer than self-propelled version. May observation is rather an observation for developer, than helpful comment for user.

**Comment by Iwan1803** [comment]
No further post -> closed.
