### ISSUE TITLE
[Feature Request] Nebenstrecken individuell pro Fahrzeug berechnen/erlauben/sperren

### ISSUE THREAD

**Issue by GulliGriff** [Stephan-S/FS19_AutoDrive#1959]
Erst mal ein dickes Lob, dass Ihr trotzt der angekündigten neuen Spielversion LS22 weiter macht ... Fettes Danke dafür.
Jetzt aber zu den Nebenstrecken. Ich finde das mit den Nebenstrecken echt Mega, aber könntet Ihr es auch implementieren, dass Fahrzeuge die benutzen dürfen oder nicht und wenn sie es dürfen ohne Berechnung? 
Vielleicht optional: Nebenstrecken nutzen 1 Berechnung | 2 Erlauben | 3 Verbieten oder so..?
So könnte ich alle Feldwege zu Nebenstrecken machen und bräuchte nicht mehr die Angst haben dass sich da ein LKW (haben bei uns alle Straßenbereifung) oder gar ein Bus die Wege nutzen. Im Moment habe ich an allen Feldeinfahrten ein Wegpunkt gesetzt und Umweg auf 10km... so funktioniert es meistens. Allerdings fahren so natürlich auch die Abfahrer den teilweise riesen Umweg.
Wäre schön wenn Ihr darüber nachdenkt.

**Comment by Iwan1803** [comment]
Nebenstrecken werden nur benutzt, wenn....
1. der "normale" Weg nicht mehr als 20x so lang wie die Nebenstrecke ist
Der LKW, welcher Getreide von Start A zu Ziel B fährt, wird sie also nur nutzen, wenn sie entsprechend kürzer ist.
2. das Erreichen eines Zielpunktes es erfordert
Der Abfahrer wird die Nebenstrecke also benutzen, wenn er nur dadurch seinen Zielpunkt am Feld erreicht.

**Comment by GulliGriff** [comment]
Über eine Antwort hätte ich mich gefreut. Wie es derzeit funktioniert weiß ich, sonst hätte ich den letzten Text nicht geschrieben.
liest Du eigentlich was ich schreibe?
Ich sag es so wie es ist, die Lösung mit den Nebenstrecken ist derzeit nix anderes als würde ich einen Haltepunkt irgendwo setzen und sagen dass er einen Umweg fahren soll. Ich würde mir Nebenstrecken wünschen wo ICH selbst beeinflussen kann ob da ein AD-Fahrer lang fahren darf oder nicht, es sei denn auf der Strecke befindet sich ein Haltepunkt den er anfahren soll. Dann wären es für mich wirklich Nebenstrecken!

**Comment by Iwan1803** [comment]
Ja, ich habe es oben korrigiert - man kann sich wohl ja mal vertun, vor allem wenn man nachträglich noch mal was umschreibt oder den ganzen Tag schon etliche Texte verfasst und übersetzt hat (siehe Release Notes). Sorry, bin leider auch nur ein Mensch, aber scheinbar darf man hier keine Fehler machen....

Wenn du ein neues Feature haben möchtest, wäre die Vorlage "Feature Request" die korrekte gewesen und nicht "Question" - das aber nur mal so als Tipp fürs nächste mal. Ich habe das mal entsprechend geändert.

Das Nebenstrecken anders gehandhabt und vor allem bewertet werden als Strecken mit einem Wegpunkt stellst du also in Frage. 
Wenn du meinst, das dem so ist, dann nutz sie einfach nicht - wird ja keiner zu gezwungen.
Genaueres können dir aber sicher Stephan oder Axel erklären, um den Unterschied klar zu machen.

Ich finde es immer wieder erstaunlich, das neue Features kommen und sofort mehr verlangt wird anstatt erstmal abzuwarten, wie es sich entwickelt. Es mag sein, das für jemand irgendwas Sinn macht, aber AD wird nicht auf Wunsch von einzelnen Personen programmiert sondern für die breite Masse.
Jede Erweiterung oder Änderung birgt auch immer Risiken, welche es abzuwägen gilt. Zudem soll AD nicht hunderten Optionen überladen wird, so das kaum einer noch durchblickt. Dies macht auch die Fehlersuche enorm aufwendig.
Außerdem kostet das alles Zeit und keiner wird dir hier innerhalb weniger Minuten eine Auskunft geben können, ob sowas in unseren Augen auch Sinn macht und vor allem, wie groß der Umsetzungsaufwand ist und ob es sich lohnt. 
Es wäre also schön, wenn du dich einfach ein bisschen gedulden könntest.

**Comment by GulliGriff** [comment]
Naja, es war halt nur ne Frage und so wie es jetzt ist, ist es für mich eben keine Nebenstrecke vielmehr ne Abkürzung und ne Meinung wird man ja wohl haben dürfen.
Auch wenn ich mich hier wiederhole, **Danke für so eine tolle Mod** und Danke dass Ihr nicht aufhört weiter zu machen obwohl der LS22 angekündigt ist. Es wäre schön, wenn Du meinen Dank auch an die anderen vom Team tragen würdest...
Dann werde ich wohl einfach noch ein bisschen auf eine Antwort warten, ich habe Geduld.

**Comment by Iwan1803** [comment]
Poste den Vorschlag gerne auf der neuen github-Seite / Feel free to post the proposal on the new github page: https://github.com/Stephan-S/FS19_AutoDrive/issues/2147
