### ISSUE TITLE
[Question] fill level

### ISSUE THREAD

**Issue by leo32128fs** [Stephan-S/FS19_AutoDrive#1961]
Set the fill level to 30% even so the vehicle fills 100%, is that a bug or is it like that

**Comment by Iwan1803** [comment]
It's not a max. fill level - it's a min. one.

**Comment by leo32128fs** [comment]
I found it strange, because I put it to fill only 30% in an unloader and I sent it to go on when it returned it was at 100%

**Comment by leo32128fs** [comment]
Sorry for the bad English , it's because I'm in the translator of the language is portuues brazil , and i don't understand almost anything in english

**Comment by Iwan1803** [comment]
If you send a driver to a silo and the fill level is 30%, then it will not leave the silo unless it has at least 30% loaded. If possible, it loads up to 100%.
Fill level is a minimum value, not a maximum!

**Comment by leo32128fs** [comment]
ok , thanks for explaining , keep up the good work , i love this mod
