### ISSUE TITLE
Fahrzeuge nehmen nicht die kürzeste Strecke / vehicles do not use shortest path

### ISSUE THREAD

**Issue by TripleX1978** [Stephan-S/FS19_AutoDrive#1966]
AutoDrive Version: 1.1.1.2

Bereits seit der 1.1.1.1 ist es bei mir so, dass die Fahrzeuge, die über die Hauptstrecke (A-B) fahren sollen immer einen Schlenker über die Strecke zum Milchlager machen, obwohl dies offensichtlich nicht die kürzeste Strecke ist und sich da auch noch ein Wegpunkt befindet.
Hab das mit den Nebenstrecken dann meistens in den Griff bekommen.
Zum erstellen der Nebenstrecken hätte ich auch noch einen Verbesserungsvorschlag  (#1967).
Das gleiche Phänomen habe ich auch noch an anderen Stellen in meinem Streckennetz beobachtet.

**Comment by Iwan1803** [comment]
Hast du in den AD-Einstellungen auch hinterlegt, wie groß ein Umweg sein darf?

**Comment by TripleX1978** [comment]
@Iwan1803 
Hab den Wert auf 10000 stehen, wie vorher auch.
Hab gerade gesehen, dass mein Screenshot nicht dabei ist. Kommt gleich noch.

**Comment by TripleX1978** [comment]
@Iwan1803 

![LS19 - Screenshot 20](https://user-images.githubusercontent.com/63108228/121817266-91448880-cc80-11eb-82cf-c96723b91832.jpg)

**Comment by Stephan-S** [comment]
Dazu müsste ich mal die config sehen, dann kann ich das mal untersuchen

**Comment by TripleX1978** [comment]
@Stephan-S Hier die config.

[AutoDrive_config.zip](https://github.com/Stephan-S/FS19_AutoDrive/files/6656400/AutoDrive_config.zip)

**Comment by Stephan-S** [comment]
Ach klasse, das war genau das richtige Testszenario um einen Bug zu finden.
Wird im nächsten RC behoben sein bzw. ist im alpha branch gerade hochgeladen worden.
