### ISSUE TITLE
Nebenstrecken über Anfang und Ende anlegen

### ISSUE THREAD

**Issue by TripleX1978** [Stephan-S/FS19_AutoDrive#1967]
Wäre es möglich, dass wenn man eine Strecke nachträglich als Nebenstrecke verwenden möchte, man nur den ersten und letzten Punkt anklicken muss und alle Zwischensegmente sich automatisch ändern?

**Comment by Axel32019** [comment]
Hallo @TripleX1978 , Das ist in der alpha-Version schon drin: Abzweig auswählen, 1. Punkt auf Zweig-Strecke mit Mauszeiger annähern, LCRTL oder LSHIFT ist Vorschau, Aktion mit Mausklick ausführen.

**Comment by haamic** [comment]
Also in der aktuellen Alpha 1.1.1.3 RC1 sehe ich zwar meine aus der Release Version erstellten Orangen stecken, kann aber keine neuen erzeugen, bzw. lt. Deiner Anleitung hier Strecken umfärben.

**Comment by Axel32019** [comment]
@TripleX1978 @haamic Das ist in der Release 1.1.1.4 drin -> siehe Release Doku
