### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by Tocik** [Stephan-S/FS19_AutoDrive#1968]
**Is your feature request related to the issue? Please describe it.**
It is no secret that the AD has difficulties with reversing with trailers. That does not make it possible to comfortably use a transport with a trailer when working with a combine, since after unloading the transoprt moves back and at the same time rests on the counter.

** Describe the solution you would like to receive.**
An excellent solution would be an additional option, when enabled, which would remain in place after unloading, and after the combine leaves, depending on other options, it would move on to the next action: go to unload or load to the durgom tarnsoprt, return to the starting point. .

** Describe the alternatives you have considered**
Alternatively, the unloader can move forward and to the left instead of moving backwards.

** Additional context**
It looks like this in the end.

![1](https://user-images.githubusercontent.com/65189100/121819384-73355300-cc95-11eb-9245-21f64670c02a.jpg)
![2](https://user-images.githubusercontent.com/65189100/121819385-73cde980-cc95-11eb-89bd-050c2cee0a73.jpg)

**Comment by Iwan1803** [comment]
Please update to the latest version 1.1.1.2 and also take a look at the release notes in the wiki.

**Comment by Tocik** [comment]
Thats problem in 1.1.1.2 ver.
In evening do photo

**Comment by Axel32019** [comment]
@Tocik Any update?

**Comment by Axel32019** [comment]
No update -> closed
