### ISSUE TITLE
Fahrzeug zu Langsam

### ISSUE THREAD

**Issue by Protenimus** [Stephan-S/FS19_AutoDrive#1969]
Hallo, das Fahrzeug nähert sich viel zu langsam seinem Ziel oder sagen wir es so: die Distanz die das Fahrzeug mit 5 km/h zurücklegen muss ist zu lang. Diesen weg sollte man verkürzen. 
Grund: Ich Spiele die Karte Altkirch2. Wenn ich ein Fahrzeug mit Auto Drive ins Klärwerk schicke, verlangsamt er schon sein Tempo auf der Straße bevor er abbiegt ins Klärwerk. Auf diesem weg muss das Fahrzeug noch Gleise überqueren. Da er aber nur mit 5 km/h fährt wird wird er jedesmal vom Zug erwischt und weggeschleudert. Das Klärwerk ist also unmöglich mit Auto Drive an zu fahren. Hier könnte eine einstellung weiter helfen wo man einstellen kann bei welcher entfernung vom Ziel er sein Tempo verlangsamen soll.

**Comment by Crinouche** [comment]
Haben Sie versucht, die Einstellung zu verringern "Maximale Silofläche" ?
Ich bin Franzose und benutze Google Translate. Entschuldigung, wenn die Übersetzung nicht perfekt ist.
![image](https://user-images.githubusercontent.com/36656729/122026974-fc9a7180-cdca-11eb-8299-7abbe62f7b1d.png)

**Comment by Protenimus** [comment]
Hallo Danke der Typ war gut. Er verlangsamt sein Tempo nicht so früh. Der Nachteil ist aber das er jetzt einige Trigger nicht findet so das ich Auto Drive überarbeiten muss und einige Punkte hinzufügen muss. Bei den älteren Versionen ( zb. 1.1.0.7 ) spielte diese Einstellung nicht in die Anfahrt ein regelte lediglich die Spanne in der er Trigger findet.
