### ISSUE TITLE
Working with harvesters

### ISSUE THREAD

**Issue by Tocik** [Stephan-S/FS19_AutoDrive#1970]
****Automatic drive version:** 1.1.1.2
** Release
** Single player game

**Describe the error**
The car again does not want to go to the combine for unloading. As you drive a car to the field and start the AD, it quickly finds the route and goes. But it drives up so that the semi-trailer passes under the pipe sideways and the harvester does not unload. Then the car returns to the parking lot and so on in a circle.

**Comment by Protenimus** [comment]
Also bei mir Funktioniert es. Versuch mal mit anderem Fahrzeug. Ich habe da auch ein Mod von einem Unimog da geht auch nichts mit anderem Fahrzeug geht es.

**Comment by Gibbanator** [comment]
same problem. Semi does not find Forester on field continue to say "Waiting for call" 
[log.txt](https://github.com/Stephan-S/FS19_AutoDrive/files/6647717/log.txt)

**Comment by Iwan1803** [comment]
"Waiting for call" means exactly that: the driver waits for a harvester to call him. As long as he is not called, he continues to wait.
In AD you must set the same target for the harvester as for the driver.

**Comment by Tocik** [comment]
There is a function that would make the car drive closer to the combine during unloading, because they often pass near the pipe and do not unload it

**Comment by Axel32019** [comment]
Change "Pipe Offset" in vehicle settings.

**Comment by Axel32019** [comment]
@Tocik If OK please close.
