### ISSUE TITLE
AutoDrive Editor problem

### ISSUE THREAD

**Issue by Albatrozs112** [Stephan-S/FS19_AutoDrive#1971]
Hello
I can not open editor on new version

![1](https://user-images.githubusercontent.com/79331061/121821826-2e64e880-cca4-11eb-8ccc-873b4868e3eb.png)
![2](https://user-images.githubusercontent.com/79331061/121821827-2f961580-cca4-11eb-9092-1e082c3734d1.png)

**Comment by Iwan1803** [comment]
Check the release notes: https://github.com/Stephan-S/FS19_AutoDrive/wiki/Release-Notes#new-branch-lines-orange--brown-instead-of-green--blue

**Comment by Albatrozs112** [comment]
> Check the release notes: https://github.com/Stephan-S/FS19_AutoDrive/wiki/Release-Notes#new-branch-lines-orange--brown-instead-of-green--blue

No i see 
Also the external editor cannot be used until it has been updated.
