### ISSUE TITLE
"Error: Can't change money of spectator farm"

### ISSUE THREAD

**Issue by iEBPO** [Stephan-S/FS19_AutoDrive#1972]
**AutoDrive Version:** 1.1.1.2   
**Release or Custom Zip:** Release  
**Map (If applicable):** GoldenSpike
**Vehicle / Type (If applicable):**   
**Multiplayer or Singleplayer:** Multiplayer 

**Describe the bug**  
After updating to the latest version, there was a problem when working with unloading the combine.
"Error: Can't change money of spectator farm"

Rolled back to version 1.1.1.0 - everything works fine.
[log.txt.2021-06-13_17.28.16.zip](https://github.com/Stephan-S/FS19_AutoDrive/files/6645617/log.txt.2021-06-13_17.28.16.zip)

**Comment by Stephan-S** [comment]
Hey, could you help us narrow down the problem?

This is caused by AD not correctly identifying who actually started AutoDrive on a certain vehicle.
Could you check if this happens only with specific vehicles (such as mission vehicles).

**Comment by iEBPO** [comment]
this happens with cars that are owned and happens with different cars

**Comment by iEBPO** [comment]
Strange, but I could not repeat a similar situation anymore, so for now the question is being closed. And I tried it with the same car.

**Comment by iEBPO** [comment]
The error appeared again. To recreate it, you need to be a customer in MP, be inside the combine, call the unloader and when he pulls up jump out of the combine. This error appears, and will not disappear until you disable the unloader.

**Comment by GulliGriff** [comment]
Habe das gleiche Problem seit 1.1.1.2 , allerdings wird der fehler nur in die log vom server geschrieben. dachte erst, dass an nem fehlerhaften trigger lag. nachdem ich den aber gefunden und geändert hatte ist der fehler nich immer da. auch die farmlands habe ich sicherheitshalber noch mal überprüft.
[log.txt.2021-06-16_09.02.17.zip](https://github.com/Stephan-S/FS19_AutoDrive/files/6661065/log.txt.2021-06-16_09.02.17.zip)
Habe auch kurzzeitig die CP version 6.4.0.2 probiert, wenn beide versionen aktuell sind hält auch der radlader an den triggern an. er scheint die gar nicht mehr zu erkennen. ich vielleicht was anderes aber ich dachte ich erwähne es mal.
Der aktuelle fehler ist scheinbar bei verschiedenen fahrzeugen aufgetreten. habe mit der horsch-drille und nem deutz angesät bzw. gras mit cp und ad aufsammeln lassen. ergebnis war dass die drille kein saatgut mehr am trigger aufgenommen hat und der grassammler nicht mehr abgekippt hat. Nach zurücksetzen der jeweiligen fahrzeuge konnte man zumindest manuaell wieder be- bzw. entladen.

**Comment by Axel32019** [comment]
Fixed in alpha-Version - feel free to test it @iEBPO @GulliGriff

**Comment by Axel32019** [comment]
Fixed in Release 1.1.1.4
