### ISSUE TITLE
[BUG] 5km/h an Triggern

### ISSUE THREAD

**Issue by KarlGutenberg** [Stephan-S/FS19_AutoDrive#1973]
AutoDrive Version: 1.1.1.2
Release or selbsterstelltes zip: Release
Karte (falls relevant): Hagenst.
Fahrzeug(art) (falls relevant): Standard

**Beschreibe den Bug**
https://youtu.be/yBvt3zilGIo
Abfahrer bleibt vor dem Waage-Trigger stehen!
https://youtu.be/7qnxgs-L6X0
Schalte ich die Kollision aus,
fährt der Abfahrer durch die Waage - Trigger

Problem gelöst! Trigger von der Waage flacher gemacht!
Nur das der Abfahrer mit 5 km/h durch die BGA fährt, ist nicht so schön!
https://youtu.be/bteK1K3NRTQ

**Comment by Iwan1803** [comment]
Die 5km/h müssen leider (aktuell) sein, damit auch jedes Fahrzeug an jedem Trigger beladen werden kann.
Z.Bsp. ist bei Saatmaschinen die Einfüllöffnung recht klein und die Trigger zum beladen meist ja nur ein Rohr. Würde er zu schnell fahren, könnte es passieren, das er vorbei fährt.

**Comment by KarlGutenberg** [comment]
Ok danke dir
Kann hier dann zu gemacht werden!
Grüße

Iwan1803 ***@***.***> schrieb am Mo. 14. Juni 2021 um 23:23:
