### ISSUE TITLE
AD- kann im Feld den Pfad zum Ziel nicht berechnen und schaltet ab / AD can´t calculate path to destination while on field and shuts off 

### ISSUE THREAD

**Issue by TMac063** [Stephan-S/FS19_AutoDrive#1974]
AutoDrive Version: 1.1.1.2
Release or selbsterstelltes zip: Release
Karte (falls relevant): NF Marsch 4-Fach V 2.8 (**MP mit dedi Server**)
Fahrzeug(art) (falls relevant): 

Symptom 1 (Feld Nr. 19):
Wenn der Abfahrer (AD) durch den Roder(CP) fertig beladen ist. Fährt dieser nicht zum Abladepunkt. AD schaltet sich ab

Symptom 2 (Feld Nr. 46):
Die Sämaschine arbeitet mit CP und soll mit AD nachfüllen, wenn leer (Option in CP ist ausgewählt)
Wenn Dünger oder Saatgut leer, bleibt die Sämaschine stehen. AD schaltet sich ab.

Bei beiden Symptomen erscheint bevor AD sich abschaltet die Meldung: "Der Fahrer von XXX konnte den Pfad zum Ziel nicht berechnen,"
Wenn man jetzt manuell AD startet, fahren der Abfahrer bzw. die Sämaschine sofort los.
Ein wechsel der Fahrzeuge führte zu keinem anderen Ergebnis
Mit diesem Fehler haben wir auf die aktuellen Versionen von AD und CP (6.4.0.2) gewechselt.

Symptome sind geblieben, zudem hilft der manuelle Start des AD nicht mehr.
Es kommt wieder die o.a. Meldung.
Ich kann noch nicht mit Bestimmtheit sagen ob es auf allen Feldern der Karte passiert.
Ich probiere da gerade dran herum

Ich hoffe, es gibt einen Lösungsansatz.

Vielen Dank im Voraus
TMac063

**Comment by Iwan1803** [comment]
Die Frage ist ja: welche Einstellungen bzgl. Feldarbeit haben eure Fahrzeuge? Welche Ausfahrt soll genommen werden, Fruchtumfahrung, Fahrtberechung, etc.? Gibt es Fanglinien rund um die Felder oder nicht?

**Comment by TMac063** [comment]
Vielen Dank für die schnelle Antwort,
anbei füge ich Screens der AD-Einstellungen bei.
Zur Fanglinie: 
Es läuft eine blaue Linie ohne Lücken (komisch vorher waren Lücken da, die habe ich geschlossen) mit Verbindungen zu richtungsgebundenen Zu- und Ausfahrten.
![AD Einstellungen HUD](https://user-images.githubusercontent.com/62108471/122258920-e3301d00-ced1-11eb-908e-b9aca778bb4d.jpg)
![AD Fanglinie F 19](https://user-images.githubusercontent.com/62108471/122258932-e62b0d80-ced1-11eb-95f4-d83cb7287695.jpg)
![AD-Einstellungen 1](https://user-images.githubusercontent.com/62108471/122258934-e6c3a400-ced1-11eb-9a86-a1e10b8a0349.jpg)
![AD-Einstellungen 2](https://user-images.githubusercontent.com/62108471/122258935-e6c3a400-ced1-11eb-954a-2ffc2fb64d73.jpg)
![AD-Einstellungen 3](https://user-images.githubusercontent.com/62108471/122258938-e75c3a80-ced1-11eb-89c8-23d7b88f6237.jpg)
![AD-Einstellungen 4](https://user-images.githubusercontent.com/62108471/122258942-e7f4d100-ced1-11eb-8de0-e1dcfc5af4c9.jpg)

**Comment by Axel32019** [comment]
Ist der Zielpunkt "F19 Überladen" eine Sackgasse? 
Wenn davon kein Weg zum Streckennetz führt kann das nicht funktionieren, da Feldausfahrt hinter Start einen Weg von "F19 Überladen" zum Ziel sucht.

**Comment by Iwan1803** [comment]
Auf gut deutsch: "Feldausfahrt" auf "nächstgelegene" umstellen.

**Comment by TMac063** [comment]
Danke für die schnellen Antworten,
@ Axel32019:
nein, der Punkt F19 Überladen ist keine Sackgasse, er ist mit einer Feldausfahrt verbunden.
@Iwan1803 :
habe "Feldausfahrt" auf "default" umgestellt. Nun funktioniert es.
Gibt es eine etwas ausführlichere Erklärung für die Schalter als im Wiki "Buttons with short description"?

Nochmals vielen Dank

TMac063

**Comment by Axel32019** [comment]
@TMac063 Ist hier noch etwas offen? Wenn OK bitte schließen!
