### ISSUE TITLE
not driving the entire way to a combine pipe, using courseplay

### ISSUE THREAD

**Issue by kingslycamben** [Stephan-S/FS19_AutoDrive#1976]
![image](https://user-images.githubusercontent.com/79064555/122266696-aea36d80-ce9f-11eb-95a0-559250b9f35a.png)
It seems to stop too early, im using the bizon super, the cheapest harvester,

**Comment by kingslycamben** [comment]
Forgot to put a label again, sorry.

**Comment by Stephan-S** [comment]
I haven't tried this combination but it is probably the collision detection that is a bit skeptical about that low hanging pipe there

**Comment by kingslycamben** [comment]
That might be it, i need to use it because the ai likes to crash into trees.

**Comment by kingslycamben** [comment]
And also for some reason workers like to drive infront of harvesters.

**Comment by Tensuko** [comment]
It would be helpful to have more information (also for AD...)
Who is driving with CP, who with AD ?
If AD is the unloader, then there must be a simple traffic conflict with the pipe, but thats a problem of the vehicle, not of CP (and I would also say not a problem of AD).

**Comment by Axel32019** [comment]
no update -> closed
