### ISSUE TITLE
[Feature Request] Unterordner erstellen - Create sub-folders

### ISSUE THREAD

**Issue by kurtlohnunternehmen** [Stephan-S/FS19_AutoDrive#1977]
Listenmenü - Zielpunkte: Es wäre sehr hilfreich, wenn man im jeweiligen Hauptordner einen weiteren Unterordner anlegen könnte. Z.B. lege ich den Hauptordner "Hof1" an und im selben Ordner lege ich einen weiteren Ordner mit dem Namen "Tierfütterung" an. So hätte man mehr Ordnung und die vielen Hauptordner würden rationalisiert werden. Also mir persönlich würde es sehr helfen - ist halt nur ein Mini - Vorschlag.

**Comment by Iwan1803** [comment]
Poste den Vorschlag gerne auf der neuen github-Seite / Feel free to post the proposal on the new github page: https://github.com/Stephan-S/FS19_AutoDrive/issues/2147
