### ISSUE TITLE
Vorschlag: Parken im Feld erweitern + eine Frage

### ISSUE THREAD

**Issue by Knowen** [Stephan-S/FS19_AutoDrive#198]
Hi, 
ich hab da mal eine Idee/Vorschlag. Vorab Info: Einstellung "Parken im Feld" ist an.

Also wenn der Abfahrer beim Abladen vom Drescher in der Frucht steht, will er danach zurück zum Start. Dafür hat man mittlerweile Einstellungsmöglichkeiten für um das Verhalten dafür anzupassen 💯 Leider dauert das Berechnen vom Weg teilweise solange das der Drescher in den LKW fährt, der immer noch seinen Weg berechnet. 
Wäre es möglich bevor der finale Weg berechnet wird, erstmal links und rechts vom Trailer zu schauen ob da schon geerntet wurde/freie Fläche ist, dann dahin zu fahren, warten und weg berechnen? Dann ist der Abfahrer schonmal aus der Frucht und kann, wenn er nicht schon losmuss zum Abladen, dort parken. 

Noch eine Frage:
Ist es möglich Helfer Namen zu geben? Ich habe teilweise viele Helfer am arbeiten, mit einheitlichen Geräten und wenn dann die Meldung kommt: "Fahrer Case IH 9240 ist....." weiß ich nicht immer welcher der 4 Fahrer gemeint ist. Ich stelle mir das so vor das, wenn man AD startet, ähnlich wie bei der benennung von Zielpunkten immer ein Schreibfeld kommt in dem man ein Namen eintragen kann zB Silagefahrer. Wenn das geht, wäre das göttlich.

Grüße,
Knowen

**Comment by Stephan-S** [comment]
Hey, du kannst jetzt Namen vergeben (noch nicht in .zip release verpackt, aber schon hochgeladen).
Dazu musst du allerdings eine neue Tastenkombination vergeben in den Einstellungen.

Zu deiner ersten Anmerkung wollte ich noch fragen ob du das Problem immer noch hast, das es zu lange dauert den Weg zu berechnen. Ich habe in den letzten commits ein paar Verbesserungen beim pathfinder eingebaut und eigentlich sollte die Berechnung sehr schnell sein. 
Die Hauptwartezeit sollten die 15 Sekunden sein, die er nach dem Abladen wartet um den Drescher vorbeizulassen

**Comment by Knowen** [comment]
Vielen Dank für dein super Arbeit!
Ich werde das gleich mal alles testen und bericht erstatten.

**Comment by Knowen** [comment]
**1. Namen vergeben:** 
Funktioniert super. Bei Fehlermeldungen oder allgemeinen Meldungen von AD wird der Name super angezeigt. Ein kleiner Fehler hat sich aber eingeschlichen. Ich benenne Fahrer1 zB. Test1. Dann später will ich einen anderen Fahrer (Fahrer2) ebenfalls benennen. Öffne ich dann für Fahrer2 das Eingabefenster steht Test1 im Schriftfeld und verschwindet erst, wenn ich in da Feld klicke. Ist ein kleiner Fehler, als nicht mit der höchsten Prio bearbeiten.

**2. Wege berechnen:** 
In 7 von 10 Fällen klappt alles super. Nur in Ausnahmefällen parkt der Abfahrer noch in der Frucht, wenn der Drescher auf dem Rückweg ist. Da kann man aber nix dran ändern, außer man reduziert die 15 Sekunden Zeitspanne. Wenn CP irgendwann mal die Kollisionsabfrage wieder drin hat, wird das behoben sein.
_Fallbeschreibung:_
Kurz vor Ende der Bahn die der Drescher gerade bearbeitet muss abgeladen werden. Der Abfahrer kommt, lädt ab und steht dann in der Frucht. Der Abfahrer wartet 15 Sekunden und will dann Parken. Da es aber kurz vor Ende der Bahn ist, braucht der Drescher weniger als 15 Sekunden um in den Abfahrer zu fahren. 

Ich lass das erstmal offen und teste in laufe der Woche/Wochenende nochmal bisschen mehr. Vielleicht bekomm ich noch ein paar andere Lösungsansätze/Verbesserungsvorschläge. Trotzdem erstmal 👍 für deine Arbeit!

**Comment by Knowen** [comment]
Hab das nun mal länger getestet. Läuft alles reibungslos.
