### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by renynX** [Stephan-S/FS19_AutoDrive#1982]
**AutoDrive Version:** 1.1.1.2   
**Release or Custom Zip:** Release  
**Map (If applicable):** Chamberg Valley
**Vehicle / Type (If applicable):**   
**Multiplayer or Singleplayer:** Multiplayer

**Describe the bug**  
Autodrive is working perfectly for me both as a solo player and as a multiplayer host, but my multiplayer guests cannot play at all.
- Movement on foot continues in each direction.  Cannot stop.
- Cannot TAB between vehicles
- ESC menu is frozen
- They need to use the task manager to quit the game.
Only multiplayer guests see these problems - disabling AD solves all.

** UPDATE ** It was one of the experimental features - turned all those off and it's all good - I guess those things aren't for multiplay

**Comment by Stephan-S** [comment]
Hey, would you have a log file for us? That would be really interesting!

**Comment by renynX** [comment]
Do you mean the main game log file?  Or does AD make it's own?

**Comment by Axel32019** [comment]
Yes the game log: log.txt

**Comment by renynX** [comment]
There you go.

As you can see I'm pushing my luck, using a shedload of mods on a map that isn't supposed to support multiplayer.
By the way, it took a frigging age to set up the autodrive routes for this map :p

[log.txt](https://github.com/Stephan-S/FS19_AutoDrive/files/6707396/log.txt)

**Comment by cpsherwood** [comment]
The odd thing is me and another friends game was affected by the issue but renynX's game was fine so I uploaded my log just in case this helps.

[log.txt](https://github.com/Stephan-S/FS19_AutoDrive/files/6708557/log.txt)

**Comment by cpsherwood** [comment]
The odd thing is me and another friends game was affected by the issue but renynX's game was fine so I uploaded my log just in case this helps.

[log.txt](https://github.com/Stephan-S/FS19_AutoDrive/files/6708589/log.txt)

**Comment by Axel32019** [comment]
@renynX You have min.  3 Maps in your mods-Folder! This might cause several issues, so only use 1 map!
Also I do not see any issue caused by AD. Suggest you clean up and try again.

**Comment by Axel32019** [comment]
@renynX Any update, news, etc. here?
