### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by kingslycamben** [Stephan-S/FS19_AutoDrive#1989]
**AutoDrive Version:** 1.1.1.2
**Release or Custom Zip:** Release  
**Map (If applicable):** fellsbrun
**Vehicle / Type (If applicable):**  john deere 7R series stock 
**Multiplayer or Singleplayer:** Singleplayer  

**Describe the bug**  
had a couse setup to sell wheat, clicked the start button and my game froze, it refused to close had to go into task manager to close it, there were still sounds.

**If applicable - Steps to reproduce the behavior**

**Screenshots**  

Should i switch to the release on github?, also this was updated from 1.1.1.0 i thinki from the github when i was having problems with 1.1.1.7 i think.
I do have courseplay, but it was not being used at the time it happened, i used it earlier for a harvest but that was a bit ago.
it did not save, contary to what the log said.
[log.txt](https://github.com/Stephan-S/FS19_AutoDrive/files/6712890/log.txt)

**Comment by kingslycamben** [comment]
I do have courseplay, but it was not being used at the time it happened, i used it earlier for a harvest but that was a bit ago.

**Comment by kingslycamben** [comment]
it just happened again... 
![image](https://user-images.githubusercontent.com/79064555/123357311-e610ba80-d52e-11eb-8135-884a4e7435a1.png)
this is where the tractor was when i clicked the button.

**Comment by kingslycamben** [comment]
sounds and everything, but its frozen.

**Comment by kingslycamben** [comment]
[log.txt](https://github.com/Stephan-S/FS19_AutoDrive/files/6712999/log.txt)
i think collision detecting is somehow detecting something and crash my game, the path is clear. i have traffic off.

**Comment by Clakus** [comment]
Yes same thing has been happening to me. I was hoping it was the modhub version. Is the new Github version different?

**Comment by kingslycamben** [comment]
> Yes same thing has been happening to me. I was hoping it was the modhub version. Is the new Github version different?

I don't think the release version on github is different.

**Comment by kingslycamben** [comment]
I think starting on corners kills the game.

**Comment by kingslycamben** [comment]
[log.txt](https://github.com/Stephan-S/FS19_AutoDrive/files/6719732/log.txt)
happened again, but i wasn't on a turn, and the game stop responding instead of freezing.

**Comment by TobiHH78** [comment]
You have not the best system, but use a lot of mods. I would suggest to clean up your modfolder first. It`s always recommended to use only one map, and remove mods you don`t use in the actual save.

**Comment by kingslycamben** [comment]
The only lacking part i would say would be ram otherwise everything else should be good, especially the 16gb gpu. and most of my mods are vehicle mods, the non vehicle mods are lets say my must need mods for every playthrough. The only thing i think that could be causing issues would be courseplay, as i have had issues with it before.

**Comment by Iwan1803** [comment]
`Error: Invalid mod name 'TSX_EnhancedVehicle-master'! Characters allowed: (_, A-Z, a-z, 0-9). The first character must not be a digit`
Unfortunately there is nothing else in the log that directly indicates the crash. 412 mods and maybe is causing the problems.
If there is more than 1 map in that folder, then delete or move that files. Also delete or move all other files, which are not used.

**Comment by kingslycamben** [comment]
> `Error: Invalid mod name 'TSX_EnhancedVehicle-master'! Characters allowed: (_, A-Z, a-z, 0-9). The first character must not be a digit`
> Unfortunately there is nothing else in the log that directly indicates the crash. 412 mods and maybe is causing the problems.
> If there is more than 1 map in that folder, then delete or move that files. Also delete or move all other files, which are not used.
> You should also download AD 1.1.1.4 and check the other mods for updates.

Oh I have a bit too many mods... That sucks that it is being caused by ehanced vehicle, there are other versions out there ill look for a new one. thx for the help even tho its not related wtih autodrive.

**Comment by Dzi4d3k** [comment]
But that only a wrong name of mod - it mustn't contain "-" sign (you probably downloaded Git repo and not repacked it to destination zip file). I use Enhance Vehicle mod and it works fine.

**Comment by kingslycamben** [comment]
> But that only a wrong name of mod - it mustn't contain "-" sign (you probably downloaded Git repo and not repacked it to destination zip file). I use Enhance Vehicle mod and it works fine.

I deleted the master, but i already had the other out i guess i forgot to remove it.

**Comment by kingslycamben** [comment]
No reason to keep this open, as my problem was solved.
