### ISSUE TITLE
Tutorial

### ISSUE THREAD

**Issue by Bandesss** [Stephan-S/FS19_AutoDrive#199]
Hallo vielleicht findet sich jemand, der ein Tutorial erstellt wie man Kurse importiert?
Ich bin leider Video Technisch nicht visiert.
Wäre klasse, wenn sich dem jemand anehmen könnte.
Falls der Thread nicht passt, bitte löschen
Gruss Bandes

**Comment by Anonymous-any** [comment]
https://github.com/Stephan-S/FS19_AutoDrive/issues/82
