### ISSUE TITLE
Autodrive and Tardis teleport [BUG]

### ISSUE THREAD

**Issue by garo73** [Stephan-S/FS19_AutoDrive#1992]
AutoDrive Version: 1.1.1.2   
Release or Custom Zip: Release  
Map (If applicable): All  
Vehicle / Type (If applicable): All 
Multiplayer or Singleplayer: Singleplayer, maybe both

When I use Tardis Teleport (Latest version 0.9.1.7), the cam freeze and can not move... I have made the same issue at both author!

[log.txt](https://github.com/Stephan-S/FS19_AutoDrive/files/6720266/log.txt)

**Comment by sperrgebiet** [comment]
Hey folks

It seems the issue is within the  AutoDrive:toggleMouse() function within FS19_AutoDrive/scripts/Specialization.lua

I just tried to find a workaround on my side. But without success, at least not for a quick-win. Within Tardis I alter the isRotatable property, same as you do. Logically I don't know why we interfer, as we both do a backup of the value and restore it afterwards. Anyways, I've to do some more digging if I can handle it within Tardis.

Cheers
_Hans

**Comment by Stephan-S** [comment]
Until very recently, AD didnt store a backup and instead always set it to true.
So, that is probably the change that is causing this bug.
I can check Our Code in the weekend. But is it possible that one of us stores as Backup the value the other mod set as temporary value?

**Comment by sperrgebiet** [comment]
Just pushed a new version which should fix the camera freeze. Seems I screwed some things up before and it would have never worked as intended. Nevertheless, I'd blame AD, just to feel better ;)

Seriously, I'm pretty confident that there is no regression. Let me know if you encounter any issues, so far it looks good on my side with the latest AD version.

https://github.com/sperrgebiet/FS19_Tardis/blob/master/FS19_Tardis.zip?raw=true

**Comment by garo73** [comment]
Ok! With the new Teleport, all works fine! Thanks to all, good Job!

**Comment by Iwan1803** [comment]
Great 😎

**Comment by AlexBig101** [comment]
> Just pushed a new version which should fix the camera freeze. Seems I screwed some things up before and it would have never worked as intended. Nevertheless, I'd blame AD, just to feel better ;)
> 
> Seriously, I'm pretty confident that there is no regression. Let me know if you encounter any issues, so far it looks good on my side with the latest AD version.
> 
> https://github.com/sperrgebiet/FS19_Tardis/blob/master/FS19_Tardis.zip?raw=true

Thank you so much. Now FS19_Tardis 0.9.2.1 and FS19_AutoDrive 1.1.1.4 does not have the problem
