### ISSUE TITLE
[BUG]Targets are changing by its own

### ISSUE THREAD

**Issue by Kitekater** [Stephan-S/FS19_AutoDrive#1994]
AutoDrive Version: 1.1.1.0
Release or selbsterstelltes zip: Release
Karte (falls relevant): NF Marsch
Fahrzeug(art) (falls relevant): alle

**Beschreibe den Bug**
Hallo,
Ziele ändern sich selbständig im HUD.
Beim durch-tabben der Fahrzeuge kommt es vor, dass sich mehrfach die Ziele der aktiven Abfahrer verändert haben.
Anstatt Ziel A, steht Ziel B drin, ohne dass was angefasst wurde.

Beim nächsten durchklicken der Fahrzeuge kann es wieder ein anderes Ziel sein. 
Es ändert sich aber immer nur das Ziel, nicht der Startpunkt.

Gruß Marc

**Comment by Iwan1803** [comment]
Klingt danach, als ob du das verteilte Be-/Entladen aktiviert hast und er deshalb durch die Ziele in einem Ordner wechselt.
![image](https://user-images.githubusercontent.com/47528836/123763010-a7c72280-d8c3-11eb-8c06-0886fde1219d.png)

**Comment by Bobster82** [comment]
I can confirm this 'bug'
Sometimes the destinations are changed, so i find a vehicle on a diff side of the map sometims. 

p.s. I dont use the 'cycle and deliver' option.
any debug settings what can help? The log is free of errors/pointers

**Comment by Iwan1803** [comment]
Did this maybe happen if you selected an AD target at the map?

**Comment by Bobster82** [comment]
> Did this maybe happen if you selected an AD target at the map?

Yes, I can confirm this.
Jumping to those hotspots aint working either.

**Comment by Bobster82** [comment]
![image](https://user-images.githubusercontent.com/47780758/123939397-62285980-d998-11eb-90b5-d86af837a5ef.png)

I had switch to markers 'on' ... I thought it was for jumping to those spots on the map, but they are for setting destination of the vehicle when clicked on the map.... Didnt know it was that... cleared that out for me..
I can jump to markers on the map, didnt know why it wouldnt let me do that last time

**Comment by Iwan1803** [comment]
That was exactly what i had in mind 😉

@Kitekater 
bitte prüf das bei dir auch mal bitte.

**Comment by Kitekater** [comment]
Ich hab die Ziel anwählbar Option nicht aktiv.
Bei mir war die Rotierende Ordner Auswahl aktiv. Habe es jetzt bei jedem Fahrzeug das mal händisch auf die " Einzieloption" geändert.
Werde es testen, gestern war es nicht mehr

30.06.2021 13:31:46 Iwan1803 ***@***.***>:

**Comment by Iwan1803** [comment]
Ok, dann warten wir mal auf dein Feedback.

**Comment by Kitekater** [comment]
Sorry für das späte Feedback.
Problem waren die Ordner.
Issue kann geschlossen werden.
