### ISSUE TITLE
[Question] 2 crossing paths [possible feature request]

### ISSUE THREAD

**Issue by kingslycamben** [Stephan-S/FS19_AutoDrive#1995]
**Question:**   
Lets say I have 2 crossing paths, would one tractor stop and let the other go? Or would both tractors just drive into eachother, as im staying away from collision detection as it is causing crashes.

**Comment by Axel32019** [comment]
Yes, only enabled collisiion detection will take care, if disabled you will see crashes.

**Comment by Axel32019** [comment]
@kingslycamben , OK so far?

**Comment by kingslycamben** [comment]
> @kingslycamben , OK so far?

I havn't tried it yet, havn't beenable to play fs19.

**Comment by Axel32019** [comment]
no update -> closed
