### ISSUE TITLE
[BUG] stuck at silo bug

### ISSUE THREAD

**Issue by kingslycamben** [Stephan-S/FS19_AutoDrive#1996]
**AutoDrive Version:** 1.1.1.2
**Release or Custom Zip:** Release  
**Map (If applicable):** No Mans Land
**Vehicle / Type Truck with built in tipper
**Multiplayer or Singleplayer:** Singleplayer  

**Describe the bug**  
The truck just sits there trying to fill voer and over.

**Try to use a silo to fill a truck with a built in tipper,might not happen for you **  

**Screenshots**  
![image](https://user-images.githubusercontent.com/79064555/123737258-42921380-d868-11eb-9099-85779d4aa5ee.png)
![image](https://user-images.githubusercontent.com/79064555/123737319-5f2e4b80-d868-11eb-8f36-4d7dfc6b7b68.png)

The particles appear like its trying to fill but as you can see there is nothing in the silo.

**Comment by TobiHH78** [comment]
I would say your silo is empty...

**Comment by kingslycamben** [comment]
> I don`t get it. Where is the bug here? The silo is empty, so of course truck will not be loaded. but that would be same for every other truck.

It loaded then just sat there trying to load over and over.

**Comment by Axel32019** [comment]
This happens if silo is empty with requested fill type.

**Comment by Iwan1803** [comment]
Check the AD settings. There is an option what should happen if an silo is empty.

**Comment by kingslycamben** [comment]
> Check the AD settings. There is an option what should happen if an silo is empty.

Oh, did not know that thank you, sorry for taking so long to respond.
