### ISSUE TITLE
Kann AD Ziele auslassen

### ISSUE THREAD

**Issue by RudiBergfeld** [Stephan-S/FS19_AutoDrive#1999]
**Question:**   
Kann AD Ziele auslassen. Ist es möglich das ich AD sagen kann welch Ziele er nicht anfahren soll.
Leider  habe ich die erfahrung gemacht  das AD immer den Kürzesten weg nimmt (das ist ja auch richtig), wenn nun auf dem weg ein zielpungt ligt nimmt er den mit op da einer Steht oder nicht oder op er da nicht duch past (tür zu klein). Kann ich ihm irgentwo sagen das er da nich hinn fahren soll.

**Comment by TobiHH78** [comment]
Ja, indem man die Nebenstrecken nutzt.

**Comment by RudiBergfeld** [comment]
TobiHH78 danke
kannst du mit auch sagen wi das geht

**Comment by Iwan1803** [comment]
Wenn da ein Zielpunkt auf der Strecke ist, dann kannst du in den AD-Einstellungen auch mal einstellen, das er Umwege fahren darf.
