### ISSUE TITLE
Befüllung des Falschen Getreides.

### ISSUE THREAD

**Issue by ZeroxxBoy** [Stephan-S/FS19_AutoDrive#20]
Servus,
Erstmal danke für den geile Mod, macht echt Laune damit zu arbeiten und finde ich persönlich leichter zu bedienen als Courseplay wenn es ums Netzwerken geht :)

Nun zu meinem bzw unserem Problem:
Auf unserem Server funktioniert dei Fruchtsorten-auswahl nicht. Soll heißen egal was wir ihm zum wegbringen einstellen, ob Hafer, Raps o.ä, er füllt den Hänger immer mit Weizen und fährt diesen Dan ab. Es ist egal auf welcher Map, mit welchem Silo oder ob mein Kollege auch auf dem Server ist oder nicht. Das lustige allerdings ist dass die Textur die vom Silo runter kommt immer dem entspricht was er ursprünglich laden sollte, also schwarz wenn wir ihm Raps zb eingestellt haben, aber es dann im Hänger immer wieder zu Weizen wird.

Im Singleplayer funktioniert es einwandfrei und macht da auch keine Probleme.
 
Wir haben auch schon versucht den Mod neu zu installieren hat aber nix gebracht.

Hoffentlich kannst du uns helfen,
Lg Robin

**Comment by Stephan-S** [comment]
Servus,

an dem Problem habe ich jetzt doch länger gesessen als gehofft. Mir ist es tatsächlich nicht aufgefallen, da ich beim Testen tatsächlich oft nur eine Art im Silo hatte :-)
Ist aber jetzt behoben und ich werde in den nächsten Tagen ein Update hier hochladen!
Vielen Dank für die Meldung

**Comment by ZeroxxBoy** [comment]
Oh das erklärt dass natürlich auch :D 
Cool danke, keep up the good work 👍 :)
