### ISSUE TITLE
was ist das für ein fehler ?

### ISSUE THREAD

**Issue by gottdi** [Stephan-S/FS19_AutoDrive#200]
C://gameservers//s648103//ls2019//gameProfile/mods/FS19_AutoDrive/scripts/AutoDriveTrailerUtil.lua:119: bad argument #1 to 'pairs' (table expected, got nil) 2019-06-06 17:22 Error: Running LUA method 'update'.

**Comment by Knowen** [comment]
Siehe #192 
Mit der aktuellsten Version sollte der nicht mehr auftreten.

**Comment by gottdi** [comment]
welche ist die aktuellste Version?

**Comment by Knowen** [comment]
1.0.2.7, kannst du dir hier runterladen.

**Comment by gottdi** [comment]
ja habe ich, lag da dran. danke

**Comment by Stephan-S** [comment]
Danke für deine Hilfe @Knowen
