### ISSUE TITLE
Nur noch Fehler[BUG]

### ISSUE THREAD

**Issue by whiccy** [Stephan-S/FS19_AutoDrive#2000]
**AutoDrive Version:** 1.1.x.x   
**Release or Custom Zip:** Release  
**Map (If applicable):** All  
**Vehicle / Type (If applicable):**   
**Multiplayer or Singleplayer:** Singleplayer  

**Describe the bug**  
Beim beladen von Fermentern hängt sich der PC auf. Bei Drescher abfahren (Mais) hängt sich der PC auf.. Bei der alten Version ging das alles noch.. Da ist noch etliches nachzubessern oder gar die Finger davon lassen... Never Stop A Running System.. 
Course Play funktioniert wunderbar.. Ich werde das AD wieder löschen.. 
Um für sowas einen Coffee zu betteln ist unverschämt.. 

**If applicable - Steps to reproduce the behavior**  

**Screenshots**

**Comment by Iwan1803** [comment]
AD läuft problemlos bei tausenden Nutzern und wir versuchen immer, Lösungen zu finden. Natürlich kann es aufgrund verschiedenster Umstände auch mal zu Problemen kommen, da du ja scheinbar kein Interesse an einer Lösung hast, mache ich dann hier mal wieder zu.
Es wird schließlich niemand gezwungen, AD zu benutzen und ebenso wird hier nicht um Spenden gebettelt.

**Comment by whiccy** [comment]
Ne. Ich hab kein Interesse

Course Play ist eben besser

Von: Iwan1803 ***@***.***>
Gesendet: Donnerstag, 1. Juli 2021 09:37
An: Stephan-S/FS19_AutoDrive ***@***.***>
Cc: whiccy ***@***.***>; Author ***@***.***>
Betreff: Re: [Stephan-S/FS19_AutoDrive] Nur noch Fehler[BUG] (#2000)


AD läuft problemlos bei tausenden Nutzern und wir versuchen immer, Lösungen zu finden. Natürlich kann es aufgrund verschiedenster Umstände auch mal zu Problemen kommen, da du ja scheinbar kein Interesse an einer Lösung hast, mache ich dann hier mal wieder zu.
Es wird schließlich niemand gezwungen, AD zu benutzen und ebenso wird hier nicht um Spenden gebettelt.
