### ISSUE TITLE
Autodrive Tastenkombination Rückwärtsfahren

### ISSUE THREAD

**Issue by allright85** [Stephan-S/FS19_AutoDrive#2004]
Hallo, wie kann ich zwei Punkte per Tastenkombination verbinden für die Funktion Rückwärts fahren (hellblaue Linie)

Vielen Dank im Voraus.

**Comment by Rumspringa90** [comment]
Waypoint to waypoint:
```
LMB = A>B = one way (green)
LMB = B>A = in both directions (blue)
LShift + LMB = A>B = one-way branch line (orange)
LShift + LMB = B>A = in both directions (brown)
RShift + LMB = A>B = backward route (light blue)
```
Description:
```
LMB = left mouse button
RMB = right mouse button
LShift = left shift key
RShift = right shift key
```

**Comment by Iwan1803** [comment]
Release Notes lesen kann helfen 😉
https://github.com/Stephan-S/FS19_AutoDrive/wiki/Release-Notes#attention

**Comment by allright85** [comment]
> 
> 
> Waypoint to waypoint:
> 
> ```
> LMB = A>B = one way (green)
> LMB = B>A = in both directions (blue)
> LShift + LMB = A>B = one-way branch line (orange)
> LShift + LMB = B>A = in both directions (brown)
> RShift + LMB = A>B = backward route (light blue)
> ```
> 
> Description:
> 
> ```
> LMB = left mouse button
> RMB = right mouse button
> LShift = left shift key
> RShift = right shift key
> ```

Danke für die schnelle Antwort (;
