### ISSUE TITLE
[Feature Request] Braking while the motor is starting / Bremsen während Motor gestartet wird

### ISSUE THREAD

**Issue by Rumspringa90** [Stephan-S/FS19_AutoDrive#2005]
**Is your feature request related to a problem? Please describe.**  
An einer Schrägen, wenn ein AD Fahrer den Motor abgestellt hat und wieder starten möchte, rollt er die Schräge hinab solange der Motor noch nicht gestartet ist.

**Describe the solution you'd like**  
Solange die "motorStartDuration" noch nicht abgelaufen ist, sollte er auf der Bremse stehen bleiben und erst nach Ablauf dieser Zeit losfahren.

**Additional context**  
https://youtu.be/8JXEZ8NP5g8

**Comment by Axel32019** [comment]
Hallo @Rumspringa90 , Wenn CP mit im Spiel ist, wird die Funktion AIVehicleUtil.driveInDirection von CP überschrieben. Diese berücksichtigt, im Gegensatz zu AD, die MotorStartTime nicht und somit kommt es zu diesem Effekt.
Ohne CP bleibt der Fahrer stehen bis der Motor läuft.
Thema daher bitte bei CP adressieren.
