### ISSUE TITLE
AutoDrive Abfahrer grüne oder braune Linie?

### ISSUE THREAD

**Issue by allright85** [Stephan-S/FS19_AutoDrive#2007]
Hallo zusammen,
für die Abfahrer ziehe ich eine komplette Linie um das Feld, dass der Abfahrer immer einen Weg findet.
Würdet Ihr da eine Standardstrecke (güne Linie) machen oder besser eine braune Linie benutzen??
Was macht aus Eurer Sicht mehr Sinn oder ist es egal?

Vielen Dank im Voraus.

**Comment by Iwan1803** [comment]
braun = Nebenstrecke
Du meinst blau, oder?

**Comment by allright85** [comment]
> 
> 
> braun = Nebenstrecke
> Du meinst blau, oder?

Die Frage was ich habe ist, ob ich den Feldkurs wo einmal komplett um das Feld für die Abfahrer geht ( und die Fahrer das Feld an verschiedenen Punkten verlassen können ), als Haupt- oder Nebenstrecke einfahren soll??

**Comment by Iwan1803** [comment]
Solange es keine Möglichkeit gibt, über den Feldrandkurs andere Ziele zu erreichen, ist es vollkommen egal.
Dennoch würde ich die blaue Linie nutzen und die Ausfahrten entsprechend aufzeichnen.

**Comment by TobiHH78** [comment]
Grün gar nicht, da er sonst immer nur in eine Richtung fahren kann. Entweder blau oder (dunkel)braun.
Um zu verhindern, dass die Fangkurse um das Feld auch für andere Routen als Abkürzung genommen werden, nutze ich seitdem es sie gibt nur noch die braunen Linien.

**Comment by allright85** [comment]
Super, danke für Eure Antworten. Ich teste mal die dunkelbraune aus.

**Comment by Axel32019** [comment]
Hallo @allright85 , Ist die Frage damit beantwortet?
