### ISSUE TITLE
AutoDrive and MotherBin [BUG]

### ISSUE THREAD

**Issue by garo73** [Stephan-S/FS19_AutoDrive#2008]
**AutoDrive Version:** 1.1.1.4   
Release or Custom Zip: Release  
Map (If applicable): All  
Vehicle / Type (If applicable): All Tractors, truck, Trailer 
Multiplayer or Singleplayer: Singleplayer, maybe both

If I use a overloader at Mother Bin (Mod and no), the AD loader can´t stop under the pipe if Mother Bin are empty... Old version can do it properly!

[log.txt](https://github.com/Stephan-S/FS19_AutoDrive/files/6766147/log.txt)
![Senza nome](https://user-images.githubusercontent.com/25790192/124515974-04a16c00-dde1-11eb-9549-907c01a3f1f5.jpg)

**Comment by Axel32019** [comment]
Hello @garo73 , At least I could not remember that an loader stopped at an empty overloader in the past.
If you need help to set-up this use-case please have a look here: https://www.youtube.com/watch?v=SBKBh-ODSHM

**Comment by garo73** [comment]
Hi @Axel32019 , Thank you for the reply, The video you linked is interesting (the combine that empty on the move I've never been able to with AD) and I already use these set-ups but this is not the case I am talking about... with version 1.1.1.0 the loader is stopped under the empty motherbin tube, maybe I remember correctly... if I could get the old 1.1.1.0 release I would do some tests!

**Comment by garo73** [comment]
Ok @Axel32019 I have tested various releases and yes, you are right, it does not ... Evidently I have been mistaken ... I apologize to everyone! But it would be interesting to implement this function to be able to use the motherbin and roadtrain on extended maps and fields!

**Comment by Axel32019** [comment]
@garo73 What do you mean by "implement this function to be able to use the motherbin and roadtrain on extended maps and fields" ?

**Comment by garo73** [comment]
@Axel32019 : I mean that the AD loader behaves, under the motherbin pipe, as it behaves under the load point of a silo, waiting for the load trigger if there is nothing to load and then filling all the wagons when the load arrives!

**Comment by Axel32019** [comment]
This is not possible, as the motherbin does not have a static trigger, like a silo.
A silo trigger is detected by AD and the loading is initiated. If empty and setting to wait if empty the loader stops at this position until the selected filltype could be loaded.
The motherbin trigger is only at its position, so if it is away for refill or whatever, AD could not detect any trigger and drive to destination.

**Comment by garo73** [comment]
@Axel32019 Thank you for the reply... let us hope that in the future it will become possible!

**Comment by Iwan1803** [comment]
Was allready implemented...
