### ISSUE TITLE
[2x Feature Request] [1] Assign Combine to Tractor & Trailer [2] Multi Combine

### ISSUE THREAD

**Issue by D4RKKNIGH7** [Stephan-S/FS19_AutoDrive#2009]
[FIRST]
I am currently having issues with the combine unload mode, I have two fields close to each other, both growing different fruits.  The issue I have is sometimes both tractors go to unload the combine at the set percentage, sometimes the wrong one gets called even though the correct one is closer and various other mix matched problems evolving the wrong trailer/tractor going to the wrong combine,

It would be a great idea if you could assign a tractor to a specific combine, this would avoid this issue all together.

[SECOND]
Using Couseplay you can have multiple harvesters on the same field, the issue I have is they fill up at similar rates, so the first combine hits 70% which is my unload trigger, then the second combine hits 70% while the tractor is driving over to the first.  This triggers the tractor to then redirect and drive to the second combine.  The tractor then drives back to the start location and ignores the first combine and never goes back to it.

It would be good to see the tractor queue these requests from the combine and execute them one after the other.
Sort of a similar idea, if the tractor is on route back to the start location after unloading the first combine, and then the second combine calls for an unload the tractor should re-direct back to the second harvestor

Any questions please ask.

**Comment by TobiHH78** [comment]
You can assign a tractor to a specific combine. Especially in your scenario. You have two combines on two different fields, so if you use same target point (field A) with your combine 1 and unloader 1, and use other target point (field B) with combine 2 and unloader 2 this should work just fine.

**Comment by envikowaty** [comment]
> You can assign a tractor to a specific combine. Especially in your scenario. You have two combines on two different fields, so if you use same target point (field A) with your combine 1 and unloader 1, and use other target point (field B) with combine 2 and unloader 2 this should work just fine.

Yes that's correct but ... if the fields are really close to each other then the 🚜 go crazy

**Comment by rohne83** [comment]
you have to set Find Driver to no, then each tractor will only unload the combine(s) assigned to its field point. If you also set Restrict unloader to field, your unloaders wouldn't leave the field during unloading (just need enough headlands then). This should work just fine.
For your second point, not sure whether this happens always. But if you're using CP for the combines anyways your best choice might be to also use CP for your unloaders. Either a grain cart which unloads to AD drivers at the edge of the field, or since CP 6.4.0.4 even the normal mode 2 CP unloaders can use AD for transporting the grain to the silo. To my experience CP unloaders are running really great on the fields now.

**Comment by envikowaty** [comment]
> you have to set Find Driver to no, then each tractor will only unload the combine(s) assigned to its field point. If you also set Restrict unloader to field, your unloaders wouldn't leave the field during unloading (just need enough headlands then). This should work just fine.
> 
> For your second point, not sure whether this happens always. But if you're using CP for the combines anyways your best choice might be to also use CP for your unloaders. Either a grain cart which unloads to AD drivers at the edge of the field, or since CP 6.4.0.4 even the normal mode 2 CP unloaders can use AD for transporting the grain to the silo. To my experience CP unloaders are running really great on the fields now.

Right ! Works well, thank you.

**Comment by Axel32019** [comment]
Hello @D4RKKNIGH7 , [FIRST] should be claryfied with the previous comments, right?
[SECOND] set the park in field enabled, which will prevent the unloader to drive to start point and wait for next call, instead it will take up the next harvester which needs unloading.

**Comment by D4RKKNIGH7** [comment]
> you have to set Find Driver to no, then each tractor will only unload the combine(s) assigned to its field point
This worked.  Having 'Find Driver' appears to disregard the selection of Harvester and Unloader.

As for the second point, I don't want the tractor to park on the field, as it gets in the way of the cultivator/other equipment on the field.  So I like it to drive off the field, but sometimes it takes the super long route and won't unload a second harvester until he gets back to the start point.  So the ability for the unloader to stop if a harvester requests to be unloaded would be cool.

However I just have 2 unloaders.

**Comment by Iwan1803** [comment]
Poste den Vorschlag gerne auf der neuen github-Seite / Feel free to post the proposal on the new github page: https://github.com/Stephan-S/FS19_AutoDrive/issues/2147
