### ISSUE TITLE
[BUG]Rückwärts aufladen fährt nicht weiter / Charging backwards does not continue

### ISSUE THREAD

**Issue by Rumspringa90** [Stephan-S/FS19_AutoDrive#2010]
AutoDrive Version: 1.1.1.4
Release or selbsterstelltes zip: Release
Karte (falls relevant): HoF 2021
Fahrzeug(art) (falls relevant): Fendt 1050 + HoT Transport Anhänger

**Beschreibe den Bug**
Es wird Rückwärts ein einen Trigger zum aufladen gefahren, es lädt auf und wenn der Anhänger voll ist fährt er aber nicht mehr weiter.

**Screenshots**
https://youtu.be/ljZINHIYupY

**Comment by Axel32019** [comment]
Hallo @Rumspringa90 , Bitte versuch es mal mit der Einstellung "Abladen ab Level" 95 oder 99%
Wenn's nicht funktioniert bitte log mit Debug "Pfadfindung" hier anhängen.

**Comment by pulimatrix** [comment]
Genau das passiert mir auch aber auch wenn ich 95 einstell derselbe Effekt!

**Comment by Axel32019** [comment]
@Rumspringa90 @pulimatrix Wenn's nicht funktioniert bitte log mit Debug "Pfadfindung" hier anhängen.

**Comment by Axel32019** [comment]
Nichts Neues hier -> closed
