### ISSUE TITLE
Entladen im Bunkersilo[BUG]

### ISSUE THREAD

**Issue by eric4072** [Stephan-S/FS19_AutoDrive#2012]
AutoDrive Version: 1.1.1.4
Release or selbsterstelltes zip: Release
Karte (falls relevant): NF - Marsch 2.2
Fahrzeug(art) (falls relevant):

**Beschreibe den Bug**
Hallo, erstmal ein ganz großes "daumen-nach-oben". AD läuft mit 15 aktiven Abfahrer und 4 CP-Häcksler wirklich gut, wenn Platz am Feld ist wirklich fehlerfrei. Auch die Auslastung des Spiels beim Pfad finden merkt man kaum noch.

Jedoch ist mir was aufgefallen: Beim rückwärts abkippen im Bunkersilo (wenn schon soviel im Silo liegt dass das Zugfahrzeug den Hänger nach oben schieben muß) beginnen mit der Zeit manche Fahrzeuge, anstatt zu bremsen, nach rechts einzuschlagen.  Was ja grundsätzlich kein Problem wär, aber bei mehreren Fahrzeugen am selben Kurs laden auch sehr oft mehrere Fahrzeuge nebeneinander ab, und wenn einer davon nicht seine Spur hält, kommt alles zum stehen.

Ich habe davon keine Log, damit ich eine erstellen kann muß ich erst die Felder wieder vorbereiten und meine Silo´s leeren...

Eine kurze Info, was ich da aktivieren muß, damit alles aufgezeichnet wird, wär hilfreich.

Sonst sind mir keine Fehler aufgefallen, außer ein paar nicht ganz so verständlichen turns bei der Pfadfindung :-)

Wirklich gute Arbeit, LG
Eric

google translate:

Hello, first of all a big "thumb up". AD runs really well with 15 active downhill drivers and 4 CP forage harvesters, if space in the field is really error-free. You hardly notice the load on the game at Find Path either.

However, I noticed something: When tipping backwards in the bunker silo (when there is already so much in the silo that the towing vehicle has to push the trailer up), some vehicles start turning to the right instead of braking. Which in principle wouldn't be a problem, but with several vehicles on the same track, several vehicles very often unload side by side, and if one of them does not keep its lane, everything comes to a standstill.

I don't have a log of it, so that I can create one I have to prepare the fields again and empty my silos ...

A short info about what I have to activate so that everything is recorded would be helpful.

Otherwise I did not notice any errors, except for a few not so understandable turns in the path finding :-)

**Falls anwendbar - Schritte mit denen ich den Bug nachstellen kann**

**Screenshots**
Falls relevant, bitte Screenshots beifügen

**Comment by Axel32019** [comment]
Hallo @eric4072 , ein paar Screenshots und die verwendeten Fahrzeuge und Anhänger wären schon mal hilfreich - dann sehen wir weiter...

**Comment by eric4072** [comment]
Hi, alles klar, dauert aber noch ein wenig bis ich soweit bin...

**Comment by Axel32019** [comment]
Nichts Neues hier -> closed
