### ISSUE TITLE
[Request] unload at a point with without a trigger

### ISSUE THREAD

**Issue by envikowaty** [Stephan-S/FS19_AutoDrive#2014]
**Question:**   
Is there any chance to force discharge trailer exactly at a given point ? 

I'm playing on HoF Bergman map and I would like to discharge trailer in a point where there is not a trigger point.

**Comment by Axel32019** [comment]
Hello @envikowaty, Chances are always there, but to investigate how to do it needs: time, an idea/concept how to integrate in UI -> as this need a special definition because there will be no trigger at this place, ... etc.
So from my point of view you might change it to a feature request.

**Comment by envikowaty** [comment]
What if you add a button or options in the settings thanks to which the waypoint we create has a forced landing.  instead of pressing key combinations on the keyboard to force a landing, the script would do it for us at that point,

**Comment by Iwan1803** [comment]
Poste den Vorschlag gerne auf der neuen github-Seite / Feel free to post the proposal on the new github page: https://github.com/Stephan-S/FS19_AutoDrive/issues/2147
