### ISSUE TITLE
Ordnerliste schließt sich immer wieder automatisch / Folder list is closing automatically

### ISSUE THREAD

**Issue by TripleX1978** [Stephan-S/FS19_AutoDrive#2019]
AutoDrive Version: 1.1.1.4

Wenn Fahrzeuge mit AD unterwegs sind und ich in der Ordnerliste z.B. Zielpunkte verschieben möchte oder für ein weiteres Fahrzeug Ziele auswählen möchte, dann kommt es immer wieder vor, dass beim Durchscrollen der Liste diese von alleine geschlossen wird und ich von vorne beginnen muss.
Je mehr Fahrzeuge mit AD laufen, umso kürzer ist die Zeitspanne.

**Comment by Iwan1803** [comment]
Multi- oder Singleplayer?

**Comment by TripleX1978** [comment]
Singleplayer

**Comment by Axel32019** [comment]
@TripleX1978 Bitte mal mit der alpha-Version testen.

**Comment by TripleX1978** [comment]
@Axel32019 Bei der Alpha-Version passiert genau das gleiche.

**Comment by Axel32019** [comment]
@TripleX1978 Sind AD-Fahrzeuge mit rotierendem Be- und/oder Entladen unterwegs?

**Comment by TripleX1978** [comment]
Ja

**Comment by Axel32019** [comment]
@TripleX1978 Sollte mit alpha RC3 behoben sein.

**Comment by Axel32019** [comment]
Fixed in Release 1.1.1.6
