### ISSUE TITLE
what are these crosses

### ISSUE THREAD

**Issue by ploughedfieldman123** [Stephan-S/FS19_AutoDrive#202]
I just went into the game and noticed these crosses  on the route, what do they mean, and how did they get there 

<a href="https://ibb.co/q7LtGj3"><img src="https://i.ibb.co/wBZ9HgF/crosses.jpg" alt="crosses" border="0"></a>

**Comment by andreasthu** [comment]
this are lonesome waypoints
https://github.com/Stephan-S/FS19_AutoDrive/issues/150

with the x markers you can find them easyly and delete them

lg
andreas

**Comment by ploughedfieldman123** [comment]
> this are lonesome waypoints
> #150
> 
> with the x markers you can find them easyly and delete them
> 
> lg
> andreas

I dont understand what you mean lonesome waypoints. how did they get there. and why do you delete them

**Comment by Stephan-S** [comment]
Thanks you  @andreasthu 
Closing this now

**Comment by rogeriodec** [comment]
This issue is a practical example I mentioned in https://github.com/Stephan-S/FS19_AutoDrive/issues/661#issuecomment-544276350.
I was opening a new issue to understand what are those "x" near the waypoints.
Once this issue is written in English, I GitHub easily suggested the currently closed issue, where I could find the solution for my question and it avoided to create a new and unnecessary issue.

**Comment by raxtor** [comment]
Just for your info you can use 1 bi-direction (blue) course instead of 2 one-direction (green) courses in that case above.

**Comment by rogeriodec** [comment]
@raxtor the problem of using a bi-direction course in the case above is that if there, for example, two trucks passing at the same time on the same course but in opposite directions, it will make a collision.

**Comment by Stephan-S** [comment]
No, one will wait for the other to clear the blue section

**Comment by rogeriodec** [comment]
Wow, this is much smarter! 
Indeed I experienced this collision issue with CoursePlay, not with Autodrive. I'll adjust the routes for the bi-direction. Thanks!
