### ISSUE TITLE
[Feature Request] Kurse als Favoriten speichern 

### ISSUE THREAD

**Issue by CptRog** [Stephan-S/FS19_AutoDrive#2020]
**Is your feature request related to a problem? Please describe.**  
Erstellungen von vor definierten Kursen als Favoriten, um die Kurserstellung schneller zu definieren. 
Menü wie bei dem Routen Manager nur als Favoriten Liste.
**Describe the solution you'd like**  
Wenn mann z.B. auf dem Feld mit CP Mist streut und das Automatische Auffüllen per AD aktiviert hat, das der Kurs mit dem Abholkurs als Favorit gespeichert werden kann und bei erneutem Starten der Kurses nur noch den Favorit z. B. Feld1 Mist Laden auswählen muss und nicht die jeweilingen Punkte auswählen.

**Comment by Iwan1803** [comment]
Poste den Vorschlag gerne auf der neuen github-Seite: https://github.com/Stephan-S/FS19_AutoDrive/issues/2147
