### ISSUE TITLE
[Feature Request] Optional recording of 2 waypoints with specified offset - optionale Aufzeichnung von 2 Wegpunkten mit angegebenem Versatz

### ISSUE THREAD

**Issue by haamic** [Stephan-S/FS19_AutoDrive#2021]
Hello,
it is now very easy to recolour or change the direction of waypoints.
Would it be possible to optionally integrate a function that creates a 2nd waypoint parallel to the actual point with an adjustable offset? 
So one enters a route as usual and in addition, e.g. at a distance of 3m, a parallel route is created.
You would then only change the direction and the two-sided road network is finished.
In principle, I do this now via a diversion with CP. Drive into AD with a tractor and implement (e.g. front mower) on one side in blue, name the starting point beforehand, e.g. S1. Drive to the end, stop the recording in AD, turn and set a course in CP to the S1 point with 3m offset (only works with implement). Start a normal green AD recording and CP moves me in the opposite direction. When I arrive at my destination, I delete S1, connect both routes with the existing route network and change the 1st blue route to green in the right direction.
This makes sense on long routes that may cover the whole map. I've done it this way several times on maps. For small sections, the effort is too great.
If it could be possible to create this 2nd opposite direction via AD, that would be great. Maybe even with reversed direction arrows.
Greetings Micha
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Hallo,
es ist nun sehr einfach , Wegstrecken umzufärben oder deren Richtung zu ändern.
Wäre es möglich, eine Funktion optional zu integrieren, die einen 2. Wegpunkt parallel zum eigentlichen Punkt mit anpassbarem Versatz erzeugt? 
Also man fährt wie immer eine Strecke ein und zusätzlich entsteht z.b. in 3m Abstand eine parallele Strecke.
bei dieser würde man dann nur die Richtung ändern und fertig ist das beidseitige Strassennetz.
Ich mach das im Prinzip jetzt über Umweg mit CP. Fahre in AD mit einem Traktor mit Gerät (z.b. Frontmähwerk) eine Seite blau ein, benenne zuvor den Startpunkt z.b. S1. Fahre zum Ende, Stoppe die Aufnahme in AD, wende und stelle in CP einen Kurs zum S1-Punkt ein mit 3m Versatz (geht nur mit Anbaugerät). Starte eine normal Grüne AD-Aufnahme und CP fährt mir die Gegenrichtung  ein. Am Ziel angekommen lösche ich S1, verbinde ich beide Strecken mit dem Vorhandenen Streckennetz und wechsel die 1. Blaue Strecke zu grün in die richtige Richtung.
Das macht Sinn auf langen Strecken, die evtl. über die ganze Map gehen. Hab ich schon öfter auf Maps so gemacht. Bei kleinen Abschnitten ist der Aufwand zu gross.
Wenn es per AD gleich möglich sein könnte diese 2. Gegenrichtung zu erzeugen wäre das super. Vielleicht sogar schon mit umgekehrten Richtungspfeilen.
Gruss Micha

**Comment by Iwan1803** [comment]
Poste den Vorschlag gerne auf der neuen github-Seite: https://github.com/Stephan-S/FS19_AutoDrive/issues/2147
