### ISSUE TITLE
[BUG]pay money when i have set payment to 0% 

### ISSUE THREAD

**Issue by k4r3l01** [Stephan-S/FS19_AutoDrive#2023]
**AutoDrive Version:** 1.1.1.4   
**Release or Custom Zip:** Release  
**Map (If applicable):** All  
**Multiplayer or Singleplayer:** Singleplayer  

**Describe the bug**  
When i activate AD with combine or any other vehicle to drive my money tears down 
i tried if is problem with any other mod so i played map only with AD and its same
here is video where its seen only mod i used is new currencies
last words i have set payment to hired workers to 0%
thanks in advance for any help
https://youtu.be/LEQ-nQdUqTw

**Comment by Iwan1803** [comment]
You must deactivate the payment also in the AD settings.

**Comment by k4r3l01** [comment]
in AD settings is only Driver wages in my language is mzdy zaměstnance and nothing else so where to deactivate payment ???

**Comment by k4r3l01** [comment]
@Axel32019 thanks its working
