### ISSUE TITLE
function error  with wood crane 

### ISSUE THREAD

**Issue by chris196** [Stephan-S/FS19_AutoDrive#2024]
i have the issue with auto drive  
it is  wen i use a wood crane  it disables te function of the clamp 
it dosnt rotate and open and colse any more 
i have to unhook the trailer and then it works normaly 
only if the crane is intergated in the veihcle  it wont work 

gr CSS modding

**Comment by Axel32019** [comment]
What shall we do with this??? -> https://github.com/Stephan-S/FS19_AutoDrive/issues/1071
