### ISSUE TITLE
[BUG] fuel station on Hof Bergmann

### ISSUE THREAD

**Issue by envikowaty** [Stephan-S/FS19_AutoDrive#2025]
**AutoDrive Version:** 1.1.1.4   
**Release or Custom Zip:** Release  
**Map (If applicable):** Hof Bergman   
**Vehicle / Type (If applicable):**   
**Multiplayer or Singleplayer:** Singleplayer  

**Describe the bug**  
Hello,

The map has already few fuel stations setup where the main one (fuel station) works well with auto drive but the tanks which are on the farm unfortunately not. Even though you set up the route next to the tanks ( tanks are top up with fuel) drive still goes to the main fuel station to refill. Is there any chance to repair that ?

**Comment by Iwan1803** [comment]
Is there a target point at the tanks on the farm?

**Comment by k4r3l01** [comment]
its similiar for me but on map vidhostice #2011 i have on my farm fuel station with fuel but machines going to rafinery for fuel and ignoring station on farm currently i playing and my driver going for fuel to rafinery and driving around farm where is fuel station

**Comment by envikowaty** [comment]
I will setup waypoints just on top of the trigger and do some tests

**Comment by envikowaty** [comment]
> its similiar for me but on map vidhostice #2011 i have on my farm fuel station with fuel but machines going to rafinery for fuel and ignoring station on farm currently i playing and my driver going for fuel to rafinery and driving around farm where is fuel station

Yes it's all the same.
Even setting up a waypoint on the trigger it's not working.

Manual option for adding refilling point would be great

**Comment by k4r3l01** [comment]
i have question you have before waypoint for refuel Adblue station or not? maybe its because that

**Comment by envikowaty** [comment]
> i have question you have before waypoint for refuel Adblue station or not? maybe its because that

I've made 3 options

Before 
In
After 

Not working any of them but:

If you make a waypoint on the refilling station 🚉 / fuel station ⛽️ everything works fine but only for that waypoint.

So the tanks which I have on my farm are not corespondenting with waypoints

**Comment by Axel32019** [comment]
Please attach the following files:
AutoDrive_config.xml, items.xml, onCreateObjects.xml, vehicles.xml

**Comment by envikowaty** [comment]
> Please attach the following files:
> AutoDrive_config.xml, items.xml, onCreateObjects.xml, vehicles.xml

hello,

please see attached files:
https://gist.github.com/envikowaty/df9cb3988449832d9e291b7c17a7b6de

**Comment by Axel32019** [comment]
As many other things in map HofBergman, here these fuel stations are vehicles, i.e. similar as FST 990. They are not detected by AD as stations because they are vehicles and so will not be used to refill fuel.
So this issue is more a feature request (to refuel from movable vehicles) than a bug.

**Comment by Iwan1803** [comment]
If still needed, post it again on the new github page: https://github.com/Stephan-S/FS19_AutoDrive/issues/2147
