### ISSUE TITLE
[Feature Request] Consider vehicle yaw angle for collision detection height

### ISSUE THREAD

**Issue by H34dl3ss** [Stephan-S/FS19_AutoDrive#2026]
The following screenshot shows the issue.
At this specific location the truck stops because the collision detection triggers as it detects the ground as an obstacle.

The improvement that I propose is to include the yaw angle of the vehicle to always "look" at the same height above ground.
This should also help setting a better height in general.
The situation shown can be solved by setting a higher obstacle detection but that will lead to collisions with small cars traffic.

![obstacle](https://user-images.githubusercontent.com/57181552/126229083-0b0c1007-c9be-438d-9497-4c7ea5005ffe.jpg)

I understand that predicting the ahead terrain is tricky, but when following a course, the upcoming terrain is known by evaluating the course markers.

![obstacle2](https://user-images.githubusercontent.com/57181552/126234313-b691a56a-3beb-4019-b8be-4734c644fc04.jpg)

**Comment by Iwan1803** [comment]
If still needed post it again on the new github page: https://github.com/Stephan-S/FS19_AutoDrive/issues/2147
