### ISSUE TITLE
[Feature Request] Pause combine unloader

### ISSUE THREAD

**Issue by blue-painted** [Stephan-S/FS19_AutoDrive#2028]
**Is your feature request related to a problem? Please describe.**  
When I am driving the combine and AD is running the unloader and I reach the end of a work, the unloader will keep following the combine while I am manoeuvring, often getting entangled.

**Describe the solution you'd like**  
A command to "pause" the unloader where he is, so that I can toggle un-pause'ed which re-starts the unloader finding my combine and coming alongside to take the rest of the load.

**Describe alternatives you've considered**  
I thought about having the unloader automatically pause when the combine header is lifted: that seems messy.

**Additional context**  
My workaround is to jump of the combine, that (seems to?) disconnect the unloader. Then I jump back on the combine, make the manoeuvre and then manually call the unloader.

**Comment by Iwan1803** [comment]
If needed post it on the new github page again: https://github.com/Stephan-S/FS19_AutoDrive/issues/2147
