### ISSUE TITLE
[Feature Request] NOT have unloader "disconnect" if I leave the combine

### ISSUE THREAD

**Issue by blue-painted** [Stephan-S/FS19_AutoDrive#2029]
**Is your feature request related to a problem? Please describe.**  
I am driving the combine, AD is running the unloader: I get off the combine for any reason and the unloader will then (seems to?) stop dead and forget about my combine.

**Describe the solution you'd like**  
Once the unloader is coming to my combine, he continues until he gets there.

**Describe alternatives you've considered**  
None really, sorry.

**Additional context**  
My work-around: stay on the combine or if I forget call the unloader manually.

**Comment by Iwan1803** [comment]
If a combine is not "active" because you or a helper is not inside, why should AD drive to it?

**Comment by blue-painted** [comment]
In RL practice, it would be because the combine still needs emptying. It may be he draws up to the combine and waits.

**Comment by Iwan1803** [comment]
In RL a person is driving the unloader - not a script. So if you want to play like in RL, why do you use scripts and not play with others?
So again: why should AD drive to an inactive combine? What is the big advantage of it?

**Comment by blue-painted** [comment]
I use scripts to mimic RL as much as possible, playing single-player as it suits me best. 

To me it's the other way around: why should the unloader stop driving to the combine?

The most recent scenario was this: I was playing on Nowa Bruzda, using old Polish and Russian equipment, carting the grain from the field to sell-points. It's a long haul for slow tractors and sometimes my combine is full while the unloader is still on the road. If I want to walk over to my tanker truck to refuel the combine, the unloader stops dead in the road, or if I'm waiting I want to walk into the next field to check the moisture, or the hay or anything ... ... I can only wait for the unloader to get to the combine, to be under the pipe

However, this was only a suggestion.

**Comment by Iwan1803** [comment]
If you have to wait for the unloader, then you might need more unloader.
When you refuel the combine, it might get in the way of the AD driver.
What if there is more than 1 inactive combine on the field or somewhere else (all with the same settings)?
How should AD know, that an inactive combine should be unloaded?
Please don't get me wrong, but I see a few problems and a lot of time spent programming for a very small benefit.

**Comment by blue-painted** [comment]
I wasn't thinking that this would not affect **finding** a combine to unload, or pathfinding to it: just the drive-to task. I assume that the unloader makes periodic checks to detect that the combine has become inactive, or maybe the combine notifies the unloader that it has become inactive, but in either case it would **not** reacting to that change and continuing to the combine.
However, you know the code and I don't.

**Comment by Iwan1803** [comment]
Let's wait and see what our coders have to say about it 😉

**Comment by Iwan1803** [comment]
If needed, post it on the new github page: https://github.com/Stephan-S/FS19_AutoDrive/issues/2147
