### ISSUE TITLE
1.0.2.9 und Courseplay

### ISSUE THREAD

**Issue by SledgeHammer75** [Stephan-S/FS19_AutoDrive#203]
Hallo, 

Autodrive in 1.0.2.9 funktioniert grundsätzlich, aber sobald ich einen Courseplay-Fahrer einstellen möchte bekomme ich die Fehlermeldung 

`Error: Running LUA method 'update'.
.../Documents/My Games/FarmingSimulator2019/mods/FS19_AutoDrive/scripts/AutoDrive.lua:381: attempt to compare number with nil`

im Log. Der Courseplay-Fahrer macht keine Bewegung, die Autodrive-Fahrer ziehen unbeeindruckt ihre Bahnen.

**Comment by Stephan-S** [comment]
Schon gefixed in 1.0.3.0
Leider war 1.0.2.9 damit ein sehr kurzer Release :D

**Comment by SledgeHammer75** [comment]
funktioniert wieder, danke für den schnellen Fix. 👍
