### ISSUE TITLE
[Feature Request] Command to send combine unloader to unload point - send home

### ISSUE THREAD

**Issue by blue-painted** [Stephan-S/FS19_AutoDrive#2030]
**Is your feature request related to a problem? Please describe.**  
When I've reached the end of the a field but the unloader's load isn't complete.

**Describe the solution you'd like**  
A command to make the AD unloader drive to the Unload point now, regardless of how loaded it is, and stop there maybe.

**Describe alternatives you've considered**  
See work-around.

**Additional context**  
My work-around: Swap from combine to unloader and change the mode to "drive to"

**Also**
Apologies if you would rather have had all three of these under one issue instead of three separate ones.

**Comment by Iwan1803** [comment]
You can send the unloader by using this button:
![image](https://user-images.githubusercontent.com/47528836/126563048-496f7a6b-c1e2-4353-8c12-ea749af5a0e7.png)

**Comment by blue-painted** [comment]
Thanks. I was thinking of a command that can be issued from the combine but thanks anyway.
