### ISSUE TITLE
[BUG] In game parking location changes for tractor to parking location seeder

### ISSUE THREAD

**Issue by JustDen1234** [Stephan-S/FS19_AutoDrive#2034]
**AutoDrive Version:** 1.1.1.4 (also checked 1.1.1.2 and 1.1.1.0)   
**Release or Custom Zip:** Release  
**Map (If applicable):** All
**Vehicle / Type (If applicable):**   
**Multiplayer or Singleplayer:** Singleplayer  

**Description**  
In game the parking location of a tractor (or combine) is changed to the parking location of the implement attached to the tractor. When closing FS, and starting it again, it has it's own parking location again.

**If applicable - Steps to reproduce the behavior**  
1. Create two points; 'Park Tractor' and 'Park Seeder'
2. Attach an implement (I used a seeder), select the implement, and set it's parking location to 'Park Seeder'.
3. Detach the implement, and set the parking location of the tractor to 'Park Tractor'. 
4. (optional) send Tractor to parking location and it will start to drive to "Park Tractor', and stop AD (this way I tested that the tractor has indeed the right parking location).
5. Attach the seeder, and detach the seeder again. Start sending the tractor to its parking location 
  => it will start to drive to the 'Park Seeder' location instead of it's own parking location.

N.B. after saving, closing FS19 and starting it again, the initial parking location of the tractor is 'Park Tractor'.

Tested this on map 'Felsbrunn' 
And with mods installed:
- AutoDrive
- AI Vehicle Extension 0.0.7.5
- Bourgault Pack 1.1.0/0
- Claas Pack (platinum expansion) 1.3.0.0
- CoursePlay 6.4.0.5
- Follow Me 1.6.0.29
- Guidance Steering 1.0.0.0
- Holmer Terra Variant DLC 1.0.2.0

**Comment by Bobster82** [comment]
You don't have to exit the game to get the original parking spot back... just leave vehicle and enter again, then it is ok.
I think they need to trigger the actual park destination when detaching a implement to refresh the actual parking position ;)

**Comment by JustDen1234** [comment]
> You don't have to exit the game to get the original parking spot back... just leave vehicle and enter again, then it is ok.
> I think they need to trigger the actual park destination when detaching a implement to refresh the actual parking position ;)

Nice to know this 'workaround'. Still like it to be fixed tho 👍

**Comment by Axel32019** [comment]
I assume you have automatic engine start active, right?
If so it is not possible to select the vehicle, hence here the onSelect event is not present for the tractor and so the park position is not updated.
Feel free to test in alpha branch.

**Comment by JustDen1234** [comment]
> I assume you have automatic engine start active, right?
Yes, automatic engine start is active.

> If so it is not possible to select the vehicle, hence here the onSelect event is not present for the tractor and so the park position is not updated.
Sorry, not really understanding what you mean with this. Are you saying it is not possible that the park position is set to the tractor park position on the de-attach of the implement? 
I'm pretty sure in the past this was not a problem at all (not completely sure but thinking back, the V1.1.0.5 worked fine).

> Feel free to test in alpha branch.
Does this mean it is fixed in the alpha branch?

**Comment by JustDen1234** [comment]
I just tested the alfa branch, and this solves this isue.
