### ISSUE TITLE
[BUG] Unloader did not find Combine on large Fields

### ISSUE THREAD

**Issue by MiMiNator** [Stephan-S/FS19_AutoDrive#2035]
AutoDrive Version: 1.1.1.2
Release or selbsterstelltes zip: Release
Karte (falls relevant): Big Fields Farm
Fahrzeug(art) (falls relevant): Krone Big X als Häcksler fährt mit CP, als Abfahrer MAN TGS 18.500

Ich habe auf der Karte die Felder 20, 21, 23, 24, 28 und 29 zu einem großen Feld verbunden. Der Startpunkt befindet sich oben links unterhalb der BGA Silos.
Ich weiss das dieses Feld unrealistisch gross ist, allerdings habe ich festgestellt das ich die Abfahrer von Hand relativ nah zum Häcksler fahren muss, damit sie auf den Ruf des Häckslers reagieren. Es würe vermutlich auch nicht reichen wenn ich an jeden Feldrand einen Startpunkt setze auf dem dann ein Abfahrer wartet. 
Wie gross ist denn die maximale Distanz, die zwischen Häcksler und Abfahrer liegen darf, damit die beiden kommunuzieren können?

Folgende Einstellungen habe ich bereits in allen Variationen erfolglos ausprobiert:
Pfadplanung begrenzt, Abfaher auf Feld begrenzen und Fruchtumfahrung.
Beim Häcksler ist folgendes eingestellt:
Abfahrer finden = Ja
Früher rufen ab 0%
Rufe 2. Ablader = Ja

Habe ich vielleicht irgendetwas übersehen?

Viele Grüße 
MiMiNator

**Comment by Iwan1803** [comment]
Abfahrer finden = Ja = die Suche ist auf einen begrenzten Radius beschränkt
Stell beim Häcksler den Zielpunkt von den Abfahrern in AD ein (einfacher Fahrmodus, aber AD nicht aktivieren).
Dann setz Abfahrer finden auf Nein und schon werden die Abfahrer über die ganze Map gerufen.
Die Abfahrer müssen dann nur den gleichen Startort wie der Drescher/Häcksler in AD haben, damit sie gefunden werden.

Du kannst dir auch gerne meine Howtos zum Thema Abfahrer anschauen:
Drescher: https://youtu.be/gAHR8QC6uUM
Häcksler: https://youtu.be/FiKmXgiJCGs

**Comment by MiMiNator** [comment]
Hallo Iwan,

vielen Dank für Deine schnelle Antwort. Das war genau die Antwort die ich gebraucht habe, es funktioniert jetzt einwandfrei!

vg
MiMiNator
