### ISSUE TITLE
lost my Orange nodes

### ISSUE THREAD

**Issue by devilboy123** [Stephan-S/FS19_AutoDrive#2036]
hi just woudering if someone could tell me how to get my orange nodes back on autodrive 
![fsScreen_2021_07_27_17_46_14](https://user-images.githubusercontent.com/13384366/127196929-72424ddb-8db8-42d1-9692-5bea4af85d2b.png)

**Comment by Axel32019** [comment]
see RCTRL here: https://github.com/Stephan-S/FS19_AutoDrive/wiki/Edit-Mode
