### ISSUE TITLE
Übergabe ab CP[BUG]

### ISSUE THREAD

**Issue by ChrisBS91** [Stephan-S/FS19_AutoDrive#2042]
AutoDrive Version: 1.1.1.4
Release or selbsterstelltes zip: Release
Karte (falls relevant): Alle
Fahrzeug(art) (falls relevant): diverse

**Beschreibe den Bug**
Wenn ich mit einem Fahrzeug mit ausgeklappten Anbaugeräten auf einem Feld unterwegs bin (z.B. Feldspritze) und am Ende automatisch von CP an AD übergebe zum Parken oder allgemein vom Feld zu fahren passiert folgendes: AD übernimmt sofort am Pfadende von CP und macht sich sofort auf den Weg obwohl beispielsweise noch das Spritzengestänge ausgefahren ist bzw. noch einklappt. Dieses führt dazu, das das Fahrzeug überall hängen bleibt (Bäume, Masten, ect.)

Könnt Ihr das vielleicht so programmieren, das AD erst übernimmt wenn die Anbaugeräte oder diverse Fahrzeuge komplett zusammengeklappt sind??  

**Falls anwendbar - Schritte mit denen ich den Bug nachstellen kann**
Traktor mit breiter Feldspritze düngen lassen über CP und ihn am Ende automatisch über CP mit AD parken lassen

**Screenshots**
Falls relevant, bitte Screenshots beifügen

**Comment by Axel32019** [comment]
Hallo @ChrisBS91, AD steuert hier keine Anbaugeräte in dieser Situation. Wenn CP übergibt wird nur zum Ziel gefahren.
Hier sollte das Einklappen der Geräte von CP abgewartet werden, bevor die Übergabe an AD erfolgt.
Bitte als issue in CP einspeisen.

**Comment by ChrisBS91** [comment]
Hi Axel

Prima, danke für die Info
Mir war nicht klar, wer wie was steuert.

Dann mach ich das mal bei CP

Thx :-)
Am 1. Aug. 2021, 19:59 +0200 schrieb Axel32019 ***@***.***>:

**Comment by Iwan1803** [comment]
Dann mach ich hier erstmal zu, da der Punkt bei CP vorhanden ist:
https://github.com/Courseplay/courseplay/issues/7392

**Comment by ChrisBS91** [comment]
Ja, genau. Kann geschlossen werden.
Hatte ich bei den Jungs von CP auch eingereicht
Am 2. Aug. 2021, 10:17 +0200 schrieb Iwan1803 ***@***.***>:
