### ISSUE TITLE
[BUG] Modconflict: advanced tip function for trailers / Erweiterte Kippfunktion Für Anhänger

### ISSUE THREAD

**Issue by Evilbolzen** [Stephan-S/FS19_AutoDrive#2043]
AutoDrive Version: 1.1.1.4
Release or selbsterstelltes zip: Release
Karte (falls relevant): All / Alle
Fahrzeug(art) (falls relevant): Kipper u. Ladewagen / Tipper and loading wagon

Kleiner "Bug" Report im Sinne eines Modkonflikts, die Lösung ist schon bekannt -> Mod entfernen (Solution: Remove mod)

Dachte mir ich geb das mal kund weil das bei mir in einem Spielstand eine ganze Zeit unentdeckt blieb, AD gibt kein Signal den Entladevorgang zu beenden was bei dieser Mod aber benötigt wird.

**Beschreibe den Bug**
EN:
"Advanced tip function for trailer" is causing a conflict with AD when unloading into bunker-silos. After successful driving through the silo and hence unloading the trailer, the trailer won't go back to resting position/closing. Occurs on some of the selling triggers as well, but not all of them. AD will then drive back to the fields with open/unloading trailer and won't go back to normal "loading position".

DE:
Die Mod "Erweiterte Kippfunktion für Anhänger" aus dem Modhub sorgt für einen Konflikt mit Autodrive beim entladen in Bunkersilos. Nach erfolgreicher Durchfahrt und dem Entladevorgang durch den AD-Fahrer wird der Kipper nicht mehr herabgelassen/geschlossen. Tritt auch bei einigen (aber nicht allen) Verkaufspunkten auf. AD fährt danach mit offenem/entladenen Hänger zurück zum Feld und geht nicht zurück in die normale "Ladeposition".

**Falls anwendbar - Schritte mit denen ich den Bug nachstellen kann**
EN:
Install and activate "advanced tip function for trailers" mod. Then try to unload into bunker silo etc.

DE:
Die Mod "Erweiterte Kippfunktion Für Anhänger" installieren und aktivieren. Tritt beim entladen in Bunker-Silos auf.

**Comment by Iwan1803** [comment]
> Kipper bleiben mit dieser Erweiterung nach dem Kippen in Kippstellung und müssen manuell abgesenkt werden.

Der erste Satz aus der Mod-Beschreibung sagt ja schon alles.
https://www.farming-simulator.com/mod.php?lang=de&country=de&mod_id=210220&title=fs2019

**Comment by Evilbolzen** [comment]
> > Kipper bleiben mit dieser Erweiterung nach dem Kippen in Kippstellung und müssen manuell abgesenkt werden.
> 
> Der erste Satz aus der Mod-Beschreibung sagt ja schon alles.
> https://www.farming-simulator.com/mod.php?lang=de&country=de&mod_id=210220&title=fs2019

Wohl war, da es aber an einigen Verkaufspunkten dennoch den Kipper gesenkt hatte bin ich wohl unbewusst davon ausgegangen das AD ein Signal gibt um den Kipper zu senken/schließen.

Erst beim Häckseln ist es mir aufgefallen, denn das Häckselgut war überall auf dem Feld verteilt und nicht im Bunkersilo angekommen. Beim beobachten der Fahrt dachte ich dann ja auch zuerst die Silopunkte seien vom Netzersteller falsch gesetzt worden und hab zuerst da dran gefummelt....da hab ich wohl zu weit gedacht durch die Probleme die ich selbst erlebe auf einer anderen Map.

Denke trotzdem es ist nicht verkehrt das Fehlerbild hier mal zu posten......denn es ist schon irgendwie hart verwirrend wenn man nach einer Stunde häckseln das Häckselgut überall auf dem Feld verteilt sieht ;)
