### ISSUE TITLE
Ich habe ein Problem bei der Ernte

### ISSUE THREAD

**Issue by OstseeTimo** [Stephan-S/FS19_AutoDrive#2044]
Ich spiele auf der Mvp mit Cursplay und Autodrive,
In der der Letzten Ernte hat noch alles so funktioniert wie ich das gerne haben wollte. Jetzt fährt der Abfahrer aber nach dem abbunkern, immer zum start Punkt zurück, aber dies war bei der letzen ernte nicht so und das führt aber zu problemen, weil sie nicht schnell genug sind.
Kann mir da vielleicht einer helfen und sagen was das problem ist? oder sein könnte weil an den einstellungen habe ich nichts verändert

**Comment by Bobster82** [comment]
Without any logs, screenshots or recordings its hard to guess what is happening ;)

**Comment by BigBlackBahamut** [comment]
Also, nach dem letzten Update funktioniert so einiges nicht mehr. Meine Bubbles verschwinden immer beim bearbeiten. Ich zerstöre gerade mehr als ich was einrichten kann. Und ja, das abfahren lassen wenn ich am Dreschen bin funktioniert auch nicht mehr. Der Abfahrer der fährt einfach nicht zu mir um meinen Ernter zu leeren.

**Comment by OstseeTimo** [comment]
Ich gucke mal das ich das mal aufnehme heute wenn ich ihn der Ernte bin dann könnt ihr das besser nachvollziehen

**Comment by OstseeTimo** [comment]
> Without any logs, screenshots or recordings its hard to guess what is happening ;)

i try to give you more Information 
And where i can found the Log, because i was the First time here and dosent have problems bevor

**Comment by Iwan1803** [comment]
> Jetzt fährt der Abfahrer aber nach dem abbunkern, immer zum start Punkt zurück...

Das macht der Abfahrer, wenn Feldausfahrt auf "Standard" eingestellt ist. Dies ist eine Einstellung, welche für jedes Fahrzeug einzeln eingestellt werden muss. Falls du einen Feldrandkurs hast, dann stell es mal auf "Nächstgelegen" um.

@BigBlackBahamut 
Die Bubbles im Edit-Mode verschwinden oder werden wieder angezeigt, wenn man die rechte STRG-Taste benutzt (seit AD 1.1.0.6).
Das mit dem Drescher klingt nach falschen Einstellungen und das mit dem Abladetrigger nach einem zu nah am Trigger gesetzten Zielpunkt.
Du solltest aber für deine Fragen vielleicht ein eigenes Issue aufmachen, denn das hat alles irgendwie nicht direkt was mit Timo seiner Frage zu tun.

Es gibt übrigens schöne Howto- & Release-Videos zu AD auf meinem Kanal und hier im Wiki sollte man sich auch mal die Release Notes durchlesen:
https://www.youtube.com/playlist?list=PL5cOkXj5iscpEZSnI-w1jv3p304IRzZZP
https://github.com/Stephan-S/FS19_AutoDrive/wiki/Release-Notes

**Comment by OstseeTimo** [comment]
@Iwan1803 ich bin mir nicht mehr sicher aber ich habe glaube die Ausfahrten auf nächstgelegen weil ich einen Feldrandkurs gefahren habe aber das kann ich nochmal gucken

**Comment by BigBlackBahamut** [comment]
> > Jetzt fährt der Abfahrer aber nach dem abbunkern, immer zum start Punkt zurück...
> 
> Das macht der Abfahrer, wenn Feldausfahrt auf "Standard" eingestellt ist. Dies ist eine Einstellung, welche für jedes Fahrzeug einzeln eingestellt werden muss. Falls du einen Feldrandkurs hast, dann stell es mal auf "Nächstgelegen" um.
> 
> @BigBlackBahamut
> Die Bubbles im Edit-Mode verschwinden oder werden wieder angezeigt, wenn man die rechte STRG-Taste benutzt (seit AD 1.1.0.6).
> Das mit dem Drescher klingt nach falschen Einstellungen und das mit dem Abladetrigger nach einem zu nah am Trigger gesetzten Zielpunkt.
> Du solltest aber für deine Fragen vielleicht ein eigenes Issue aufmachen, denn das hat alles irgendwie nicht direkt was mit Timo seiner Frage zu tun.
> 
> Es gibt übrigens schöne Howto- & Release-Videos zu AD auf meinem Kanal und hier im Wiki sollte man sich auch mal die Release Notes durchlesen:
> https://www.youtube.com/playlist?list=PL5cOkXj5iscpEZSnI-w1jv3p304IRzZZP
> https://github.com/Stephan-S/FS19_AutoDrive/wiki/Release-Notes


Ok, Danke. Ich schau noch mal. Bisher hat alles geklappt. Aber ich schau mal. Sollte es wieder auftretten bei 2 Spielern mache ich ne neuen Issue ;-)

**Comment by Iwan1803** [comment]
> @Iwan1803 ich bin mir nicht mehr sicher aber ich habe glaube die Ausfahrten auf nächstgelegen weil ich einen Feldrandkurs gefahren habe aber das kann ich nochmal gucken

Manchmal passiert es, das ich mir ein neues Fahrzeug kaufe und dann vergesse, die Abfahrer-Einstellungen zu ändern 😉

**Comment by Axel32019** [comment]
Sollte alles geklärt sein -> closed
