### ISSUE TITLE
[Question] Cannot reach destination

### ISSUE THREAD

**Issue by ThatDefender90** [Stephan-S/FS19_AutoDrive#2045]
**AutoDrive Version:** 1.1.1.2   
**Release or Custom Zip:** Release  
**Map (If applicable):** All  
**Vehicle / Type (If applicable):** All
**Multiplayer or Singleplayer:** Singleplayer  

**Describe the bug**  
I have set up a couple of junctions on my savegame, just for the places that I want the tractor to drive to. When I set my tractor or my harvester to drive to any of my points it just says it cannot reach the destination. I have tried all the different mode's and it just says the same thing for all of them. everything is set up right from what I know.

**If applicable - Steps to reproduce the behavior**  
I can Leave my XML file in this
[Autodrive xml files.zip](https://github.com/Stephan-S/FS19_AutoDrive/files/6940896/Autodrive.xml.files.zip)

**Comment by Bobster82** [comment]
Hey Defender,

Thanks for attaching your routes. I had a drive around and found some issues. You miss some connections, some routes dont ever connect. So you need to drive around and see if your vehicle can access that place.
For example, you miss a exit to the shop from where I came from:
<img width="1434" alt="2021-08-05 211422" src="https://user-images.githubusercontent.com/47780758/128407950-35c231a9-3fc2-48f5-8fe9-381df1b1a737.png">

p.s. You know u can use 2 way roads? I see you go back and forth over the same road ;)

**Comment by ThatDefender90** [comment]
Hi mate,

Thank you so much for your reply!

Will have another look with everything again, also what do you mean by 2 way roads?

**Comment by ThatDefender90** [comment]
> Hey Defender,
> 
> Thanks for attaching your routes. I had a drive around and found some issues. You miss some connections, some routes dont ever connect. So you need to drive around and see if your vehicle can access that place.
> For example, you miss a exit to the shop from where I came from:
> <img alt="2021-08-05 211422" width="1434" src="https://user-images.githubusercontent.com/47780758/128407950-35c231a9-3fc2-48f5-8fe9-381df1b1a737.png">
> 
> p.s. You know u can use 2 way roads? I see you go back and forth over the same road ;)

Would also just say that when I set the destination to Sunderlandwick stores it says it cannot reach destination but then goes when i drive to this point in the route, any chance you could check this out as I have checked it over and to me it seems like it should work
![image](https://user-images.githubusercontent.com/88293767/128424736-e812b83a-ccaa-4c87-9cf2-2c3615f7d513.png)

**Comment by Iwan1803** [comment]
There is a route debug function in the AD settings. Maybe you should check your routes with that.
This howto is in german, but maybe it will help:
https://youtu.be/2UjT0fAWORg

**Comment by Bobster82** [comment]
> Will have another look with everything again, also what do you mean by 2 way roads?

(I don't know if my mousebuttons are standard, so yours might do different)
If I press record route with my leftMouseButton, it records the standard 1 way line.
If I press record route with my middleMouseButton, it records the 2 way line. (see picture)
![fs19](https://user-images.githubusercontent.com/47780758/128477851-db89e379-f581-4baf-ae60-a77d7af19d5a.jpg)



> Would also just say that when I set the destination to Sunderlandwick stores it says it cannot reach destination but then goes when i drive to this point in the route, any chance you could check this out as I have checked it over and to me it seems like it should work.

It depends where you start your route from. I just follow the lines manually(if AD can't find it) to the destination and see if I see missing lines or not connected ones. 
Next example your "Farm" , can't reacht it, because of missing connection:
![fs19_2](https://user-images.githubusercontent.com/47780758/128478316-62f61573-8e0f-4991-b286-5ab958577442.jpg)

**Comment by Iwan1803** [comment]
Check the wiki -> Release Notes: 
https://github.com/Stephan-S/FS19_AutoDrive/wiki/Release-Notes#click-on-record-button

**Comment by ThatDefender90** [comment]
> Check the wiki -> Release Notes:
> https://github.com/Stephan-S/FS19_AutoDrive/wiki/Release-Notes#click-on-record-button

Will do thank you!

**Comment by ThatDefender90** [comment]
> > Will have another look with everything again, also what do you mean by 2 way roads?
> 
> (I don't know if my mousebuttons are standard, so yours might do different)
> If I press record route with my leftMouseButton, it records the standard 1 way line.
> If I press record route with my middleMouseButton, it records the 2 way line. (see picture)
> ![fs19](https://user-images.githubusercontent.com/47780758/128477851-db89e379-f581-4baf-ae60-a77d7af19d5a.jpg)
> 
> > Would also just say that when I set the destination to Sunderlandwick stores it says it cannot reach destination but then goes when i drive to this point in the route, any chance you could check this out as I have checked it over and to me it seems like it should work.
> 
> It depends where you start your route from. I just follow the lines manually(if AD can't find it) to the destination and see if I see missing lines or not connected ones.
> Next example your "Farm" , can't reacht it, because of missing connection:
> ![fs19_2](https://user-images.githubusercontent.com/47780758/128478316-62f61573-8e0f-4991-b286-5ab958577442.jpg)

Awesome thank you! So last night after you said to have a look I found the problem with the farm and went to fix them as well :)

**Comment by ThatDefender90** [comment]
> There is a route debug function in the AD settings. Maybe you should check your routes with that.
> This howto is in german, but maybe it will help:
> https://youtu.be/2UjT0fAWORg

Awesome ok will do thank you!
