### ISSUE TITLE
[Feature Request] Intelligentes Management von Zweiweg-Routen

### ISSUE THREAD

**Issue by atemnot** [Stephan-S/FS19_AutoDrive#2048]
Ich habe so meine Probleme bei Karten mit vielen schmalen Wegen und Straßen, die nur einspurig befahrbar sind.
Wenn man eine Zweiweg-Route mit nur zwei Endpunkten hat funktioniert alles super. Weitere Fahrzeuge warten, bis die Spur von einem anderen Fahrzeug geräumt wurde und fahren dann erst los. 
Dieser Erschließung funktioniert aber nicht, wenn es sehr viele einspurige Straßen gibt und die Zweiweg-Routen Abzweigungen haben sollen. Dann kann es vorkommen, dass Fahrzeuge mit unterschiedlichen Start-/Zielpunkten gleichzeitig in die Route einfahren und kollidieren. Bestenfalls muss man die Fahrzeuge von Hand entwirren. Schlimmstenfalls waren es schnelle Fahrzeuge, die nicht mehr bremsen konnten und man findet nur noch einen verkeilten Haufen von Schleppern, Sattelschleppern und Anhängern vor.

Ich würde mir daher wünschen, dass man auch ganze Netze von Zweiweg-Routen besser genutzt werden können.
Konkret hätte ich folgende Vorschläge:
Vor der Einfahrt in ein zusammenhängendes Netz von Zweiweg-Routen checkt das Fahrzeug, ob im Netz auf der geplanten Durchfahrtsroute ein Fahrzeug in entgegengesetzter Richtung unterwegs ist, d.h. die Route wäre reserviert. Ist das der Fall wartet das Fahrzeug bis der Routenabschnitt vom vorhandenen Fahrzeug durchfahren wurde. Die Abfrage erfolgt in der Reihenfolge in der neue Fahrzeuge das Netzwerk erreichen (FIFO). Wird die Route von einem anderen Fahrzeug bereits in gleicher Richtung befahren, kann das neue Fahrzeug einfahren. Die Einfahrt ist ebenfalls möglich, wenn sich zwar bereits ein oder mehrere andere Fahrzeug im Netzwerk befindet, aber eine andere Route reserviert hat/haben.

**Comment by Iwan1803** [comment]
Komplette Streckennetze aus blauen Wegen sind suboptimal, um es vorsichtig zu sagen und es gibt eigentlich immer Möglichkeiten, auch mal Einwegstrecken einzubauen, um dieses Problem zu lösen.
Ansonsten poste den Vorschlag gerne auf der neuen github-Seite: https://github.com/Stephan-S/FS19_AutoDrive/issues/2147
