### ISSUE TITLE
AD biegt scharf ab/crash nach laden/entladen

### ISSUE THREAD

**Issue by sdl112** [Stephan-S/FS19_AutoDrive#205]
Hallo,

ich habe diverse Verkaufskurse mit dem laden/abladen Modus programmiert. Ich habe hierbei immer wieder das Problem, dass die Fahrzeuge unmittelbar nach dem Laden/Entladen scharf abbiegen und dann in irgendetwas reinfahren/hängen bleiben. Woran liegt das, wie kann ich es verhindern?

schöne Grüße, Simmal

**Comment by Stephan-S** [comment]
Hallo,

benutzt du die aktuellste Version? Das Problem ist in einer früheren Version kurz vorhanden gewesen, sollte aber derzeit nicht mehr vorhanden sein.

Beste Grüße,
Stephan

**Comment by sdl112** [comment]
Ja ich habe 2.8. Obwohl esmir in Game anzeigt, es sei Version 2.7?

**Comment by Stephan-S** [comment]
Ok,

es wäre super wenn du mir ein savegame hochladen kannst, wo alles vorbereitet ist zum abladen (das Probleme bereitet), so dass ich nur noch abfahrer einstellen muss um zu sehen, was schief läuft.

Das würde mir auf jeden Fall sehr helfen!

Vielen Dank und viele Grüße,
Stephan

**Comment by sdl112** [comment]
[savegame2.zip](https://github.com/Stephan-S/FS19_AutoDrive/files/3269928/savegame2.zip)

Hier das savegame. Vor dem Ladepunkt des Multisilos am Hof stehen drei Abfahrer mit je drei Kursen vorprrogrammiert, auf denen Beispielhaft das Problem aufgetreten ist.

**Comment by Stephan-S** [comment]
Hey,
ersteimal sorry, dass ich mich erst jetzt zurück melde.
Vielen Dank für das super vorbereitete Savegame!!

Das Problem war schnell gefunden:
Distanz Vorausschauen (Lenkung) -> wieder von 15m auf 6m runterdrehen.

Hier werde ich im nächsten Update Werte löschen, die Probleme bereiten, damit das nicht mehr bei dir und anderen auftreten kann!
