### ISSUE TITLE
Waypoints and Route disappear below road. [BUG]

### ISSUE THREAD

**Issue by ghost** [Stephan-S/FS19_AutoDrive#2054]
**AutoDrive Version:** 1.1.1.4  
**Release or Custom Zip:** Release not available  
**Map (If applicable):** Valley View but has happened on F
![IMG_20210817_223102](https://user-images.githubusercontent.com/47851063/129729392-4ec4ebe8-1f14-4b11-bf49-1ba68cdecb91.jpg)
![IMG_20210817_223126](https://user-images.githubusercontent.com/47851063/129729408-939e8e47-d38e-4efe-bb79-b9c3b4e680f6.jpg)
elsbrunn 
**Vehicle / Type (If applicable):**   N/A
**Multiplayer or Singleplayer:** Singleplayer  

**Describe the bug**  
I was moving waypoints using right mouseclick and the waypoint and some others before it disappeared below road surface when track was at ground level. The route is visible when the track is set above vehicle but the route will not work. 
If I can bridge the section of road without the track going belpw the surface the route works but if like in the screen shots shown it is on a hill crest  the track is blocked.

**If applicable - Steps to reproduce the behavior**  
The problem has occured 3 times and each time I was moving waypoint using RMB 
**Screenshots**  
I have 
![IMG_20210817_223126](https://user-images.githubusercontent.com/47851063/129729577-0790956c-88c0-4e4a-9c46-83fa7e337d10.jpg)
![IMG_20210817_223102](https://user-images.githubusercontent.com/47851063/129729585-35d18b7d-41b5-47b6-9880-0e809e58e576.jpg)

**Comment by Iwan1803** [comment]
That's a problem of the map.
Since 1.1.1.2: 
> if LShift is pressed when moving a waypoint, it remains at its original height and cannot sink into the ground

**Comment by Evadtheawesome** [comment]
With the LShift key held I am able to move the waypoint at road height to new location but I am unable to release the point at the new location. 
You mentioned it was a map problem so is the mapmaker able to fix the problem easily?

BTW I think your Mod is amazing and every time I play and appreciate its development.

**Comment by Dzi4d3k** [comment]
I'm not sure, but maybe the map ground (adjustable terrain) under asphalt road is not properly layered. Especially on screens it looks like road is an object placed between other object (mountains) so under it there is probably empty space instead of map terrain.

**Comment by Axel32019** [comment]
It is not possible to release the moved point with LSHIFT hold -> fixed in alpha branch
