### ISSUE TITLE
Abfahrer Fährt nicht oder falschen Drescher an.

### ISSUE THREAD

**Issue by Gyffes** [Stephan-S/FS19_AutoDrive#206]
So und da bin ich wieder :-)

Geht im Folgenden im die DonDiegoMap im MP

Drescher erntet auf Feld 14 mit hilfe des Helfers.
Angefangen von unten Links (SW) immer fein hoch runter hoch runter. Im AD ist Feld 14 Eingestellt. Der Abfahrer hat eine Parkposition am Feldrand von Feld 14.  Eingestellt auf Abfahren Feld 14 -> Bahnsilo. 

Das selbe auf Feld 13 was sich links neben Feld 14 befindet.  Anfangs Lief alles wunderbar keine klagen. Hier allerdings der Abfahrer startunkt rechts vom Feld.

Als das Feld 13 zu 3/4 abgeerntet war. Meinte dann plötzlich der Abfahrer von Feld 14 sich zu Feld 13 zum Abernten zu Fahren wenn der Drescher voll war.  Ok dankte ich mir vielleicht liegen die Punte zu nah an einander.
Also erstmal Abfahrer und Helfer auf 14 Pausiert bis Feld 13 Abgerntet war.
Auf Feld 14 Abfahrer und Helfer aktiviert.
Aber der Abfahrer fährt nicht los.
Im Hud von AD steht Abfahrer F14 - Fahre zu Drescher grünn hinterlegt. Es dauert eine weil dann schaltet sich der AD beim Abfahrer aus.

Meldung im Log 
`2019-06-09 16:16 Going into fallback mode - no fruit free path found in reasonable time 2019-06-09 16:17 Stop searching - no path found in reasonable time 2019-06-09 16:17 Autodrive hat ein Problem beim Initialisieren festgestellt`

Hoffe ich bin nicht zu blöd zum einstellen da es eigentlich einfach zu verstehen ist.

Danke. Dir.

**Comment by Stephan-S** [comment]
Mit der folgenden Einstellungen legst du fest ob der Drescher Fahrer suchen darf die sich in der Nähe befinden (Fahrer finden = Ja) oder ob nur Fahrer gerufen werden, die das selbe Ziel eingestellt haben (Fahrer finden = Nein)

![findDriver](https://user-images.githubusercontent.com/5493976/59160343-12d31000-8ad5-11e9-859b-6fbe5f886d80.png)

> Meldung im Log
> `2019-06-09 16:16 Going into fallback mode - no fruit free path found in reasonable time 2019-06-09 16:17 Stop searching - no path found in reasonable time 2019-06-09 16:17 Autodrive hat ein Problem beim Initialisieren festgestellt`

Ok, genau nach dieser Meldung suche ich. Wie gesagt, ich brauche das Savegame um die Situation nachstellen zu können. Sonst finde ich den Fehler nicht. In meinen Tests läuft es eigentlich immer problemlos

**Comment by Gyffes** [comment]
Juhu also Abfahrer finden ist auf nein gestellt.

hier das gewünschte Zip 
[savegame7.zip](https://github.com/Stephan-S/FS19_AutoDrive/files/3269721/savegame7.zip)

Vielen Dank

**Comment by Stephan-S** [comment]
Hey, mit diesem Savegame fange ich leider nichts an, da nichts vorbereitet ist, nichts fertig eingestellt parat steht.

Bitte lade ein savegame hoch mit dem ich die Situation habe die du beschreibst.
Also gleiches Feld (erntereif), gleiche Abfahrer, Drescher schon an/auf dem Feld. Alles so eingestellt wie du es startest.
Und zwar auf einem Stand von dem du weißt das es in dem Moment schief geht.

Sprich spielstand speichern, Abfahrer & Drescher starten und wenn es damit ein Problem gibt, lad genau diesen Spielstand hoch. Also von VOR dem Problem. Dann kann ich es analysieren :-)

Wenn dir das zu viel Aufwand ist, verstehe ich das :-) 
Aber das ist der Beste Weg um zu einer schnellen Lösung zu kommen.

**Comment by Gyffes** [comment]
naja eigentlich habe ich genau das gemacht? wundert mich. 

ich schau mir das saveg ame eben mal an.

**Comment by Stephan-S** [comment]
ah okay. Der Abfahrer hatte bei mir keinen Anhänger, da ich dem Mod 'Krone ZX 560' nicht installiert habe.

Aber ich glaube es waren auch keine Drescher auf dem Feld oder habe ich das falsch gesehen?

**Comment by Gyffes** [comment]
Ok das du die fahrzeuge nicht siehst liegt wohl daran das entsprechende mods nicht aktiv sind.
Habe nun Fahrzeuge ersetzt das einzige was ich nicht ersetzten kann ist der ernter dazu brauchst 
https://www.modhoster.de/mods/fs19_carrot_onion_pack

Allessteht bereit feld 14 unten links abfahrer mit anhänger oben rechts Ernter.

[savegame8.zip](https://github.com/Stephan-S/FS19_AutoDrive/files/3269760/savegame8.zip)

Danke

**Comment by Gyffes** [comment]
Grüße und schönen guten Morgen, 

hab das ganze mal mit deiner Version 1.3.1 getestet auf dem Spielstand denn du von mir bekommen hattest.  Das Positive der Abfahrer Fährt los und Richtung Ernter. Negativ er fährt beim Ernter vorbei.  Fährt mit 14km/h im halbkreis durch das gesamte Feld 15 wiede rauf Feld 144 zurück Richtung Ernter. 
an im Vorbei langsam im Halbkreis durch Feld 6 und 7 und so weiter und wo weiter.....

In diesem Fall habe ich zuerste den Abfahrer Aktiviert der dann auch direkt gemerkt hat das da noch ein Ernter mot offenen Rohr steht. Danach habe ich den Helfer Aktiviert.

Hab nach einer weile abgebrochen und per hand die hälfte abgeladen.  Den Ablader wieder zur Strase gefahren und Aktiviert. Danach Funktionierte es richtig. 

Als nächstes habe ich das Savegame nochmals geladen und zuerst den Helfer gestartet danach erst den Ablader und es Funktioniert nun erst mal alles. ( 3x Abfahren)

Danke dir vielmals für den super Support. 
p.s. Ich habe dem Fahrer einen Namen gegeben, bekomme aktuell aber keine Meldung mehr wie Fahrer hat abgeladen oder Fahrer ist angekommen usw.

**Comment by Gyffes** [comment]
So da bin ich wieder, soweit Funktioniert alles hin und wieder kommt es vor das das Spielt lagt ohne ende. Schlimmer als im Daumenkino.

habe festgestellt das es immer Anfängt wenn AD in Fallback mode geht.
nach 2 Minuten beruhigt sich das wieder und man kann auch wieder Spielen.

Einsavegame kann ich leider diesmal nicht bieten da es nicht immer Auftritt und ich nochnicht weis bei welchen Abfahrer. Hoffe ich kann noch ein Savegame erstellen dafür.


Schönen abend noch.
 


```
2019-06-10 18:56 Going into fallback mode - no fruit free path found in reasonable time 
2019-06-10 18:58 Stop searching - no path found in reasonable time 
2019-06-10 18:58 Autodrive hat ein Problem beim Initialisieren festgestellt
2019-06-10 20:15 Going into fallback mode - no fruit free path found in reasonable time 
2019-06-10 20:18 Stop searching - no path found in reasonable time 
2019-06-10 20:18 Autodrive hat ein Problem beim Initialisieren festgestellt
2019-06-10 20:23 Going into fallback mode - no fruit free path found in reasonable time
2019-06-10 20:25 Stop searching - no path found in reasonable time 
2019-06-10 20:25 Autodrive hat ein Problem beim Initialisieren festgestellt
```

**Comment by Stephan-S** [comment]
Alles klar,
vielen Dank für dein Feedback.
Wahrscheinlich wäre es besser hier früher einen Schnitt zu machen, bevor das Spiel aufgrund der aufwendigen Berechnungen zum Daumenkino wird. Das werde ich nochmal feinjustieren, danke.

Aber schade das es immer noch häufiger zu dieser Situation kommt.
Bzw. kannst du dir aus den aktuelle sourcen selber ein .zip File bauen? Dann nutzte doch bitte die aktuellsten Dateien. Ich habe heute morgen noch ein kleines Update hochgeladen, nachdem ich das Savegame eines anderen Users bekommen habe.
Das sollte auch nochmal einige Schwachstellen ausbügeln.

**Comment by Gyffes** [comment]
Denke die zip bekomme ich hin. Werd ich nach dem Abendbrot mal schauen Danke


Häufig ist realativ mal mehrfach in der stunde dann wieder stundenlang nichts.
Wird schon werden :-) ist ja auch noch beta fehler gehören dazu .-)

**Comment by Gyffes** [comment]
So ich hab nun mir die Zip zusammen gebaut hoff ich hab alles erwischt. Diese eingespielt und Speicherpunkt gestartet und wollte loslegen. Wie der Zufall so will direkt einen Streikenden Ablader gefunden. :-)

Hier erst mal die Log Einträge und dann der Speicherpunkt Ansicht außerdem meinen modifizierten Aperion (erster Mod versuch) so das ich nicht erst den Anhänger wechseln muss. 
Grund hierfür ist das, wenn ich den Ablader 5 m zurückfahre, und erneut AD starte beim Abfahrer er zum Startpunkt fährt und dann direkt auch weiter zum Drescher. Ohne rum zu zicken.

Das ganze spielt sich übrigens auf Feld 15 ab. Abfahrer unten Link Drescher mittlerweile oben Rechts.

Grüße und schönne Abend.
[FS19_SAP3401.zip](https://github.com/Stephan-S/FS19_AutoDrive/files/3277727/FS19_SAP3401.zip)
[savegame9.zip](https://github.com/Stephan-S/FS19_AutoDrive/files/3277729/savegame9.zip)



`2019-06-11 19:09 Going into fallback mode - no fruit free path found in reasonable time
2019-06-11 19:09 Stop searching - no path found in reasonable time
2019-06-11 19:09 Autodrive hat ein Problem beim Initialisieren festgestellt
2019-06-11 19:12 Going into fallback mode - no fruit free path found in reasonable time
2019-06-11 19:13 Stop searching - no path found in reasonable time
2019-06-11 19:13 Autodrive hat ein Problem beim Initialisieren festgestellt`

**Comment by Stephan-S** [comment]
Vielen Dank.
Da habe ich in einem der letzten commits etwas verschlimmbessert.
Release 1.0.3.2 fixt das Verhalten in der Situation

**Comment by Gyffes** [comment]
Ok werd es Testen kann allerdings bis nächste Woche dauern. 

Danke dir.

**Comment by Gyffes** [comment]
Also bei mir scheint es Aktuzell zu Funktionieren also schließe ich die Issue mal.
Hoffe es bleibt so:-)

Dankeee
