### ISSUE TITLE
[BUG] ladewagen klappe Schließt nicht nach dem Leer machen

### ISSUE THREAD

**Issue by b3zge** [Stephan-S/FS19_AutoDrive#2060]
AutoDrive Version: 1.1.1.4
Release or selbsterstelltes zip: Release
Karte (falls relevant): Alle
Fahrzeug(art) (falls relevant): alle LAdewagen

**Beschreibe den Bug**
moin habe mal ne Frage ich fahre Mit AD die grass silage in silo rein der laded ab alles schön und gut aber wiso wen der wagen leer ist wiso schließt er dann die klappe nicht

**Falls anwendbar - Schritte mit denen ich den Bug nachstellen kann**

**Comment by Iwan1803** [comment]
Bei mir schließt er die Klappe fehlerfrei. Ist der Zielpunkt vielleicht zu nah am/im Silo?
Screenshots von der Situation und dem AD-Netz sowie das Log könnten hilfreich sein.

**Comment by b3zge** [comment]
![ls](https://user-images.githubusercontent.com/60016575/130289216-ea72e8a7-303e-47e6-b9eb-915ad2de95e3.png)
![ls2](https://user-images.githubusercontent.com/60016575/130289230-16b3b199-9c3a-4b36-9c73-f10b4504e185.png)
[log.txt](https://github.com/Stephan-S/FS19_AutoDrive/files/7023945/log.txt)
so nur kanst was damit anfangen

**Comment by rohne83** [comment]
Könnte am Trailer liegen. Was ähnliches hab ich ganz selten mal aber auch schon gehabt, das lag bei mir dann daran, dass er noch nicht ganz leer war. Ist auf deinen Screenshots leider nicht zu erkennen. Abfahrer entlassen, nochmal manuell abladen, und dann wieder einstellen, hat mir da geholfen.

**Comment by Iwan1803** [comment]
Ist das ein Vanilla-Anhänger? Falls nicht, dann bitte mal mit einem testen.

**Comment by b3zge** [comment]
Habe die weg Punkte schon weiter nach hinten gesetzt und verschiedene Wagen ausprobiert hat leider nix gebracht

**Comment by Iwan1803** [comment]
Du hast mehrere Maps im mods-Ordner liegen (z.Bsp. Bergisch Land, Frankenmap, Ellerbach, etc.), was man schon mal nicht machen sollte, da LS19 jeden Mod einliest, auch wenn er dann im savegame nicht aktiviert ist.
FS19_AdvancedTrailerTipping <- mal testweise deaktivieren
FS19_curseplay <- umbenennen in FS19_Courseplay.zip
Dann sehe ich zwar die Mods von FedAction, aber nicht die Map dazu.
Sorry, aber der mods-Ordner ist das reine Chaos und da auf Anhieb rauszufinden, welcher Mod querschiesst... 🙄

**Comment by b3zge** [comment]
Danke für den Tipp es lag an den FS19_AdvancedTrailerTipping Mod

Das problem ist geklärt

**Comment by Iwan1803** [comment]
Zu, auf, zu, auf? Ich mach mal zu...
