### ISSUE TITLE
[Feature Request] During load option the continue button does not respond

### ISSUE THREAD

**Issue by JustDen1234** [Stephan-S/FS19_AutoDrive#2076]
**AutoDrive Version:** 1.1.1.6   
**Release or Custom Zip:** Release  
**Map (If applicable):** All  
**Vehicle / Type (If applicable):**   
**Multiplayer or Singleplayer:** Singleplayer  

**Describe the bug**  
If you have a tractor with an implement (seeder/furtilizer/etc) that is not fully filled, use load mode, then start, it will always drive to the loading point. The continue button did work in the past, when usint it, it did not drive to the loading point but to the field.
Now it does not.

**Steps to reproduce the behavior**  
1. Use tractor with implement (seeder or whatever) that is not completely filled (at your farm)
2. Use Load Mode, setup target to a field, the loading point to a selling point (and off course what to load)
3. Start AD => it will start to drive to the loading point 
4. Click the 'Continue' button.

Expected result: drive to the field.
Actual result: keeps driving to the loading point.

![image](https://user-images.githubusercontent.com/68871402/131388247-cd939d60-ac2f-4c9e-a654-0ebc8a0fc513.png)

**Comment by Iwan1803** [comment]
Same like reported in #2059

**Comment by Axel32019** [comment]
In load mode it never was and is not possible use continue -> Feature Request.

**Comment by Axel32019** [comment]
no update -> closed
