### ISSUE TITLE
[BUG] only autoload objects can be selected as loads, instead of the normal loads - nur Autoload Objekte als Ladegut wählbar, statt der normalen Ladegüter

### ISSUE THREAD

**Issue by haamic** [Stephan-S/FS19_AutoDrive#2079]
AutoDrive Version: 1.1.1.6
Release or selbsterstelltes zip: Release
Karte (falls relevant): Alle
Fahrzeug(art) (falls relevant): Pickup 82s_TLX2020 mit Flatbed attachment + Wasseranhänger

**Beschreibe den Bug**
Am Zugfahrzeug wurde eine Autoload Pritsche angekoppelt, daran dann ein Wasseranhänger.

Möchte ich nun Wasser laden funktioniert das nicht , da nur Autoload Objekte als Filltype wählbar sind und kein Wasser.
Koppel ich den Anhänger und auch die Pritsche ab, bleiben die Autoload Objekte erhalten.
Steige ich aus und wieder ein, sind wieder die normalen Ladegüter da.

Wäre es möglich die Autoloadfunktion abschaltbar zu machen, also nicht das die Entladung ausgestellt werden kann, so wie es jetzt im Menü möglich ist, sondern generell, damit der Wasseranhänger wieder Wasser laden kann. Man stellt es aus, wenn man gerade kein autoload braucht.
Oder AD bietet alle Ladegüter an, inklusive der Autoload Objekte, so das trotz Autoload Fahrzeug, noch anderes geladen werden kann.

**Falls anwendbar - Schritte mit denen ich den Bug nachstellen kann**

**Screenshots**

![EAL](https://user-images.githubusercontent.com/28841989/131891619-08348b0d-1a5e-4cdb-a812-8376b7717911.jpg)

**Comment by haamic** [comment]
auch hatte ich mal zum Testen verschiedene Autoload Güter geladen, auf Fahrzeug Ladegut 1 auf einem Autoload Anhänger Ladegut 2, es wurden am Ziel alle Objekte abgeladen, obwohl im AD HUD nur Ladegut 1 ausgewählt war.

**Comment by Axel32019** [comment]
Hallo @haamic , Hast Du die Release-Notes gelesen???
https://github.com/Stephan-S/FS19_AutoDrive/wiki/Release-Notes
"Important: mixed operation with other material loads is not supported!"
Weiterhin sind die Limitierungen auch erläutert worden: https://www.youtube.com/watch?v=95_m1pZLVjI
Anders ist das derzeit nicht machbar.
