### ISSUE TITLE
Eigene Abladestelle im Kurs platzieren ?

### ISSUE THREAD

**Issue by D3ltorohd** [Stephan-S/FS19_AutoDrive#208]
Hallo,

gibt es die Möglichkeit, beim Kurs einfahren, eigene Abladestellen zu erstellen, so wie ich die Ziele setzte. Grad gut für Erdfrüchte die man in Hallen lagert, da gibt es ja keine Trigger zum drüber fahren, man schüttet davor ab und schiebt dann mit dem Radlader oder dem Föba die Früchte in die Halle.

Hierfür, wäre es eben gut im Kurs zu sagen, so hier abladen.

Grüße

**Comment by Stephan-S** [comment]
Hallo, das ist nicht momentan nicht geplant.

Ich sehe das auch nicht besonders gut integrierbar mit dem restlichen Konzept des Mods.
Da jedes Fahrzeug potentiell diese Strecke fahren will, wäre es schlecht wenn dort plötzlich abgeladene Waren lagern und die Wege blockieren.

Für solche Fälle bietet sich Courseplay dann vermutlich einfach besser an, da die Kurse/Strecken hier losgelöster sind und nicht gleich potentiell den ganzen Verkehr stören.

Da du ja eh nach jeder Tour manuell eingreifen musst und die Haufen verschieben musst, reicht es vielleicht hier einen normalen Zielpunkt zu erstellen und manuall abzuladen und ihn danach weiterzuschicken.
