### ISSUE TITLE
[BUG] Unloading the harvester

### ISSUE THREAD

**Issue by iEBPO** [Stephan-S/FS19_AutoDrive#2080]
**AutoDrive Version:** 1.1.1.6   
**Release or Custom Zip:** Release  
**Map (If applicable):** All  
**Vehicle / Type (If applicable):**   
**Multiplayer or Singleplayer:** Multiplayer 

--- Sorry for my English ---

**Describe the bug**  
Hello.
When the bunker is full, even up to 100%, the cars that are driving up stopped driving up to the combine themselves, they just stand in standby mode. Only on call via a key. In a single game, it works as before.
Version 1.1.1.4 - no such problem.

**Comment by Axel32019** [comment]
@iEBPO Could you please add some screenshots - at least to me the situation is not clear.

**Comment by iEBPO** [comment]
> @iEBPO Could you please add some screenshots - at least to me the situation is not clear.

okay, I'll record a video.

**Comment by iEBPO** [comment]
Here I recorded a video. Where it can be seen that the unloading vehicle arrives only after a manual call.

https://youtu.be/riIH3u5XETI

LOG from server
[log.txt](https://github.com/Stephan-S/FS19_AutoDrive/files/7111271/log.txt)

**Comment by Axel32019** [comment]
@iEBPO Fixed in alpha branch - feel free to test it.

**Comment by iEBPO** [comment]
Good day!
Combines began to arrive, but the server log is filled with an error and significantly slows down the server. Log below.

[log.txt](https://github.com/Stephan-S/FS19_AutoDrive/files/7140842/log.txt)

**Comment by Axel32019** [comment]
Sorry, its a bug. Fixed already in alpha branch - please update your Version.

**Comment by iEBPO** [comment]
> Извините, это ошибка. Исправлено уже в альфа-ветке - обновите свою версию.

It works fine now. Tell me what conditions need to be met so that the unloading takes place on the go? Sometimes it works, but more often they stand and wait until I stop.
