### ISSUE TITLE
Different speeds

### ISSUE THREAD

**Issue by HAKL1958** [Stephan-S/FS19_AutoDrive#2082]
Will it be possible to set different speeds for individual sections of the route? E.g. entrances to halls or from road to field access.

**Comment by Iwan1803** [comment]
At the moment no and it is actually not planned for the future.
If there is a need for a braking maneuver, you can draw a small zigzag line in front of the "obstacle".

**Comment by Hellspawnxxx** [comment]
Hi Iwan,

danke erstmal für die tollen Erklärvideos zu AD, absolut super gemacht! TOP!
Ich hab bezüglich es "Speedlimit" Themas folgendes Problem wo das eventuell helfen könnte. Auf meinem Hof steht ein Silo wo ich ablade. Leider kommt es auf der Abladestelle immer wieder zu Auffahrunfällen weil die LKW´s viel zu schnell darauf zufahren und nicht mehr rechtzeitig bremsen können. Auch kommt es auf meinen Strecken immer wieder mal vor das LKW´s (vor allem wenn voll und schwer) zu schnell in die Kurve fahren, sich drehen und in irgendwelchen Bäumen/Hindernissen festfahren.

Die einfachste Variante für ein Speedlimit die ich mir vorstellen kann wäre einfach ein "Wegpunkt" wo alle Fahrzeuge drüber fahren eine entsprechendes Limit bekommen. Aber ob das machbar ist etc überlasse ich euch, war nur eine Idee.

Der Hinweis mit dem "zickZack" Kurs finde ich gut, habe ich auch schon versucht, war aber nicht in allen Fällen die Lösung (vermutlich hab ich das einfach nicht richtig gemacht..). Wäre das nicht eine Thema für ein neues AD Video? Thema "Advanced Tips für die AD Strecke". "ZickZack" Kurse, Kurvengeschwindigkeiten beeinflussen etc..

**Comment by Iwan1803** [comment]
Ich musste meine LKW fast alle auf 90% Kurvengeschwindigkeit einstellen, damit sie nicht umkippen.
Was mir aufgefallen ist: der erste Winkel einer Kurve sollte relativ steil sein, damit sie rechtzeitig vorher bremsen.
Je "runder" die Kurve ist, desto schneller fahren sie auch.
