### ISSUE TITLE
[BUG] Abfahrer rufen, Problem in Verbindung mit CP

### ISSUE THREAD

**Issue by eric4072** [Stephan-S/FS19_AutoDrive#2083]
AutoDrive Version: 1.1.1.6
Release or selbsterstelltes zip: Release
Karte (falls relevant): Alle
Fahrzeug(art) (falls relevant): Traktoren

**Beschreibe den Bug**
Hallo, wenn ich in CP dem Modus Drescher selbst abtanken wähle, also dass sich der Drescher am Feldrand einen dort stehenden Anhänger selbst sucht und dort hinfährt, beginnt AD am Feld daneben diesen Drescher anzufahren, obwohl in Autodrive ein ganz anderer Wegpunkt eingestellt ist. Funktioniert natürlich nicht, weil der Drescher ja immer in Bewegung ist und auf keinen Abfahrer wartet. 

in der log hab ich keine Fehlermeldungen...

Bzgl. eines älteren posts, es ging um das nach links oder rechts einschlagen beim abladen in einem Keilsilo: bin leider lange nicht zum spielen gekommen und der Beitrag wurde geschlossen... habe das Problem lokalisieren können. es tritt nur auf wenn ein Frontgewicht am Traktor hängt. Ja ich weiß, man sollte keine Gewichte in Verbindung mit AD dranhängen... jedoch in Verbindung mit dem "real weights mod" und grossvolumigen Anhängern schiessen immer wieder Fahrzeuge aus der Kurve, kippen um und liegen dann ohne Warnmeldung irgendwo neben der Strecke. Mit Frontgewichten passiert das nicht...

Ansonsten läuft AD wirklich perfekt...

LG
Eric

**Falls anwendbar - Schritte mit denen ich den Bug nachstellen kann**

**Screenshots**
Falls relevant, bitte Screenshots beifügen

**Comment by Iwan1803** [comment]
Zu den Frontgewichten: ich nutze "Agribumper" und habe 0 Probs damit.
Zu den Kurven: schon mal die Kurvengeschwindigkeit auf 90% oder weniger runtergesetzt?

Zum "selber abtanken" kann ich nichts sagen, aber versuch doch mal beim Abfahrer den "Abholen&Abliefern"-Modus, weil der Drescher-Modus mit Sicherheit falsch an der Stelle ist.

**Comment by eric4072** [comment]
Hallo, du scheinst mich da falsch verstanden zu haben, es passiert bei folgenden Szenario:

Map: Geiselsberg
AD und CP auf letzter Githubversion
Traktoren: aus dem John Deere Pack und aus dem Claas DLC 
Häckseln auf dem zusammengelegten Feld 44, 2 Abfahrer + Häcksler aus dem John Deere Pack.

funktioniert einwandfrei, ohne Fehler...

Dann habe ich einen Rostelmasch Drescher auf dem Nebenfeld (56 glaub ich) gestartet. im CP den Modus selbst abtanken gewählt. ich stelle einen leeren Hänger am Feldrand ab, ohne Zugfahrzeug. Wenn der CP Drescher 100% erreicht, erkennt er den Hänger am Feldrand, fährt dort hin und beginnt das überladen. Beim Drescher im AD habe ich Feld 56 eingestellt. Nochmals zur Erinnerung: die Häckselkette am Nebenfeld arbeitet mit dem Wegpunkt "Feld 44 häckseln"...

und jetzt kommt das Problem: der Abfahrer vom Häcksler  steuert dann den Drescher am Nachbarfeld an, versucht in abzutanken, obwohl dort Feld 56 eingestellt ist. kann ja nicht funktionieren, da 1. der Drescher immer in Bewegung ist und Aufgrund der CP Einstellungen auf keinen Abfahrer wartet und 2. der Abfahrer der Häckselkette einen Silagewagen drann hat der keinen Weizen laden kann...

Ergebnis: der Drescher und der Abfahrer verkeilen sich in Verbindung mit dem abgestellten Anhänger...

Es scheint so als würde diese CP Funktion bei AD das eingestellte Ziel deaktivieren... erinnert irgendwie an die ehemalige Funktion "Abfahrer finden"...

bzgl. den Gewichten: ist ja kein Problem, wollte nur nochmals Bezug zu dem geschlossenen Threat nehmen..

LG Eric

**Comment by Iwan1803** [comment]
Nur zu Sicherheit: "Abfahrer finden" ist bei allen auf "nein" eingestellt?
Du könntest mal versuchen, das Abfahrer rufen in AD auf das max. % für den Drescher einzustellen.

**Comment by eric4072** [comment]
Einstellungen mehrmals überprüft... wenn ich diese Funktion aus CP rausnehme, besteht das Problem nicht mehr... habe halt z.Z. nur 3 Traktoren und die Erträge zum Investieren sind auf dieser Map auch nicht so hoch... darum bin ich auf diese Möglichkeit gekommen...

100% probiere ich gerne, dauert ein wenig da ich gerade auf Urlaub bin

LG
Eric

**Comment by Axel32019** [comment]
@eric4072 Bitte folgende Dateien einfügen: log.txt, AutoDrive_config.xml, items.xml, vehicles.xml

**Comment by eric4072** [comment]
bin  im urlaub, dauert noch 2 Tage...

**Comment by eric4072** [comment]
so habe es versucht nochmal zu reproduzieren: kaum zu glauben, aber es tritt nicht mehr auf... habe echt keine Ahnung wo das her gekommen ist...

**Comment by Iwan1803** [comment]
Ok, dann mach ich erstmal hier zu.
Sollten noch Fragen sein, kannst du es ja noch mal öffnen.
