### ISSUE TITLE
[BUG] Beim umschalten von CP auf AD beim säen keinen Lohn

### ISSUE THREAD

**Issue by Pilllemann** [Stephan-S/FS19_AutoDrive#2086]
AutoDrive Version: 1.1.1.6
Release or selbsterstelltes zip: Release

Nutze ich CP und AD zum auftanken nimmt sich sobald CP auf AD umschaltet AD keinen Lohn mehr. Lohn steht bei beiden auf 100%. Steht er bei AD auf 50% oder 0% bekomme ich sogar Geld.

**Comment by Axel32019** [comment]
Das ist ein Problem bei der Abfrage an AD von CP Seite, der PR löst das.
