### ISSUE TITLE
[Question] Verständnisfrage zur Wartezeit

### ISSUE THREAD

**Issue by TobiHH78** [Stephan-S/FS19_AutoDrive#2087]
**Question:**   
Moin,
kurze Frage zum Verständnis. Was ist der Grund für die Einführung der Wartezeit beim Autoload abladen? Bringt das einen Vorteil, den ich gerade nicht erkenne? Bisher hat er am Trigger abgeladen und ist anschließend weitergefahren. Im Grunde genau so, wie es sein sollte. Was ist der Mehrwert, wenn er da noch länger stehen bleibt?

Das ihr die Autoload Funktion reingebracht habt ist übrigens saustark. Für Leute wie mich, die mit einigen Produktionen und vielen Paletten und Ballen spielen, ist das im SP eine enorme Erleichterung. Funktioniert echt tadellos, danke dafür!

**Comment by Iwan1803** [comment]
Deine Frage zielt wohl auf die Alpha 1.1.1.7-RC.
Wenn man einen geschlossenen Auflieger hat und AD mittig auf der Ladefläche abladen muss, dann ist er dennoch sofort losgefahren. Das führte dann dazu, das er z.Bsp. die Paletten einfach mitnimmt/mitschleift, wenn der Trigger diese nicht in Millisekunden verarbeitet hat. Daher wurde diese Pause eingebaut.

**Comment by TobiHH78** [comment]
Alles klar, so macht das Sinn. Das abladen auf der Ladefläche habe ich nicht bedacht.
Bei mir sind die Trigger so angeordnet, dass ich immer daneben fahre und rechts oder links von der Ladefläche abladen lasse. Das funktioniert auch wunderbar ohne Wartezeit,. Aber logisch, es dauert natürlich im Trigger eine gewisse Zeit, bis die Paletten verarbeitet werden.

**Comment by Iwan1803** [comment]
Man könnte natürlich auch hinter dem Auflieger abladen lassen, aber auf vielen Maps hat man den Platz dafür nicht 😉

**Comment by TobiHH78** [comment]
Stimmt,, das wäre auf meiner Map auch nicht praktikabel. Daher wird bei mir immer nur links oder rechts abgeladen.

Ist auf jeden Fall ein Feature mit einem enormen Mehrwert, der mir bei den GC-Produktionen viel manuelles eingreifen erspart.

**Comment by Maggal76** [comment]
Servus!
Wie lange beträgt denn die Wartezeit?
Konnte es wohl offenbar bei meinem ersten Versuch nicht erwarten...
Super Job und tollen Video sübrigens!!!

**Comment by Iwan1803** [comment]
Sie wird einstellbar sein.

**Comment by Maggal76** [comment]
Dann habe ich das wohl missverstanden. Ich dachte, die Wartezeit wäre jetzt schon enthalten?!
Habe gestern versucht mit einem Autoloader Stroh abladen zu lassen. Hat auch funktioniert, allerdings ist er nach dem Abladen stehen geblieben und nicht zurück zum Feld. Hab ihn dann manuell weitergeschickt...

**Comment by TobiHH78** [comment]
Die ist auch schon enthalten, wenn du die Alpha runtergeladen hast. Da gibt es in den Fahrzeugeinstellungen die Möglichkeit die Abladeseite und die Wartezeit auszuwählen. Ich glaube das geht von 0 über 1, 5 und 10 Sekunden bis hoch zu 10 Minuten. Auf jeden Fall genug Auswahlmöglichkeiten um alle Eventualitäten abzudecken.

Bei mir funktioniert das bei einigen GC Produktionen mit Paletten ganz wunderbar.

**Comment by Maggal76** [comment]
Habe die 1.1.1.6 Was kann noch der Grund sein, warum es bei mir nicht klappt?

**Comment by Iwan1803** [comment]
1.1.1.6 ist der letzte Release und da ist es noch nicht enthalten.
Entweder besorgst du dir die letzte Alpha oder wartest bis zum Release der 1.1.1.8

**Comment by Maggal76** [comment]
Danke für die Mühen!

Vielleicht habe ich auch etwas falsch eingestellt...

Ganz konkret: ich möchte mit einem Autoload-Anhänger ein Feld mit Strohballen abfahren lassen und diese an einem Verkaufspunkt abladen. Ich benutze Autodrive und CP. Wie muss ich vorgehen bzw. ist dies möglich? Was ist bei den Einstellungen zu beachten (habe schon Dutzende Videos angesehen, aber zu diesem konkreten Fall leider nichts gefunden). Bisher hatte ich eingestellt: CP: Feldarbeit, Kurs des Dreschers, Autodrive zum Be- und Entladen AD: Abholen und Abliefern, Feld 1, Verkauf Stroh, Ballen 1,8m, Autoload Abladeseite links. Ist da grundsätzlich was falsch?

**Comment by TobiHH78** [comment]
Wüsste nicht, wie das gehen soll. CP lädt keine Ballen mit EAL, und AD kann ja nicht gleichzeitig aktiv sein. 
Die AD Funktion kannst du nutzen, wenn du an einem Punkt im AD Streckennetz etwas laden möchtest, und an einem anderen Zielpunkt ablädst.
CP hat aber einen Ballensammelmodus, der auch an einer Verkaufsstelle oder Ballenlager abladen kann. Dafür brauchst du aber kein AD.
