### ISSUE TITLE
[BUG] / oder doch Future-Request abladen Strohballen

### ISSUE THREAD

**Issue by Zugross** [Stephan-S/FS19_AutoDrive#2088]
AutoDrive Version: 1.1.1.6
Release or selbsterstelltes zip: Release
Karte (falls relevant): Alle / spiele aktuell Mountain Hill 2021
Fahrzeug(art) (falls relevant): vanilla-Ballensammler / Autoload-Anhänger

**Beschreibe den Bug**
Wenn es nicht vorgesehen ist, oder ich zu doof bin bitte Rückmeldung geben 

Wenn ich mit dem Ballensammler Strohballen via „Abholen und Abliefern“ zum Viehhändler bringe fährt er die Route und kommt mit den Strohballen zum Feld zurück. Gleiche Einstellung mit dem Ladewagen fährt er das Stroh zum Händler und läd es ab. Manuelles Abladen am Trigger nach Autodrive „Fahren“ funktioniert. 

Warum läd der Ballenwagen nicht ab. Ist das ein Bug oder nicht vorgesehen? 
Zumindest Abladen via Autoload sollte ja gehen. Das stand in der Release-Note. Die Abladeposition ist in den Fahrzeugeinstellungen auf „Abladen mittig“

**Comment by Iwan1803** [comment]
AD kann nur nicht Easy Auto Load umgehen und deshalb steht das auch so explizit in den Release Notes drin.
wenn der Ballensammler und Anhänger nicht nutzt, wird es mit AD nicht funktionieren.

**Comment by Zugross** [comment]
Auch mitreden EasyAutoLoad funktioniert es nicht.

**Comment by Iwan1803** [comment]
Abladen mittig hat aktuell das Problem, das das Fahrzeug nicht wartet, bis die Sachen auch vom Trigger verarbeitet worden.
Dies wird in der nächsten Version mit einer Pause verbunden sein.
Teste einfach mal, ob er links oder rechts korrekt ablädt, auch wenn dann es erstmal nicht im Trigger liegt.

**Comment by TobiHH78** [comment]
Auch wenn es hier vielleicht nicht reingehört. Aber das gewünschte Szenario funktioniert mit dem Ballenwagen auf jeden Fall mit CP.
https://github.com/Courseplay/courseplay/issues/6859

**Comment by Axel32019** [comment]
@Zugross Die vanilla-Ballensammler / Autoload-Anhänger arbeiten nicht mit EasyAutoLoad und werden somit von AD nicht unterstützt. Es werden nur Fahrzeuge/Anhänger unterstützt die EasyAutoLoad benötigen.
@TobiHH78 Stimmt.

**Comment by Zugross** [comment]
@Axel32019 das ist mir jetzt soweit klar. Es funktioniert auch mit EasyAutoLoad-Anhängern (Fliegl Transport-Pack) nicht.

**Comment by Iwan1803** [comment]
Das Fliegl-Transportpack von LSFM nutzt wohl nicht EasyAutoLoad, denn es steht davon nichts auf der Modpage und in der Zip selber finde ich auch keinen Hinweis darauf.
