### ISSUE TITLE
[BUG] translation_it.xml

### ISSUE THREAD

**Issue by garo73** [Stephan-S/FS19_AutoDrive#2089]
AutoDrive Version: 1.1.1.6   
Release or Custom Zip: Release  
Map (If applicable): All  
Vehicle / Type (If applicable): All  
Multiplayer or Singleplayer: All

Describe the bug
The "translation_it.xml" is empy

If applicable - Steps to reproduce the behavior
Open AD in Italian game language

Screenshots
![Farming Simulator 19 Screenshot 2021 09 09 - 16 44 38 37](https://user-images.githubusercontent.com/25790192/132707908-e50e64bc-56a1-444e-b69f-bcf7f61ad297.png)
![Farming Simulator 19 Screenshot 2021 09 09 - 16 45 40 10](https://user-images.githubusercontent.com/25790192/132707956-1cf16b77-b1ee-4494-91cc-79415ab560e6.png)
![Farming Simulator 19 Screenshot 2021 09 09 - 16 46 00 54](https://user-images.githubusercontent.com/25790192/132708020-c8f6b4c5-f45e-450e-939a-2cf085962f70.png)
![Farming Simulator 19 Screenshot 2021 09 09 - 16 46 09 63](https://user-images.githubusercontent.com/25790192/132708089-ca28a41e-21bf-4eac-b419-75df475ac0ed.png)
![Farming Simulator 19 Screenshot 2021 09 09 - 16 46 19 11](https://user-images.githubusercontent.com/25790192/132708140-22544b46-ead4-4be6-99f8-7bc1f74a3347.png)

**Comment by Iwan1803** [comment]
Thanks, i fixed it und updated the released ZIP.
Could you please download it again and verify my changes?
https://github.com/Stephan-S/FS19_AutoDrive/releases/tag/1.1.1.6

**Comment by garo73** [comment]
Now it works fine! Thank you so much!

**Comment by Iwan1803** [comment]
Thanks for help 😉
