### ISSUE TITLE
Vehicle does not stop at destination

### ISSUE THREAD

**Issue by aviator64** [Stephan-S/FS19_AutoDrive#209]
With 1.0.3.1 - if the speed is set above 40, vehicles approach their destination too fast and go past it before stopping, then try to turn back and get stuck. This happens consistently.

Perhaps the system should detect the upcoming destination and start slowing down in advance, like it does for turns?

**Comment by Stephan-S** [comment]
I cannot reproduce the behaviour.
Vehicles are set to slow down to 12 km/h on the second last waypoint and 8 km/h when approaching the last waypoint.
Have you changed any of the ingame settings dramatically. Most importantly, the two look ahead distances?
Or is there anything else special about your destinations? Only with full and heavy trailers?

**Comment by Stephan-S** [comment]
Well okay, I guess I can see the problem. If you have a heavy trailer and the path leading to the destination is a straight line with full speed, then it might be too late to slow down at the last few waypoints. I will make some improvements for that. Thank you for bringing it up

**Comment by aviator64** [comment]
It was behaving the same with a tractor alone (no trailer) or a pickup truck.

I had increased the look ahead distances. Putting them back to the defaults seems to have fixed the issue - that seems counter-intuitive though! What are the best settings?

My game is set for mph rather than kph - could that make a difference?

**Comment by Stephan-S** [comment]
You should be very careful with increasing the lookahead distance for turning.
It basically determines when the tractor is supposed to switch to the next waypoint.
You can play around with it and observer how it handles corners.
The lookahead distance for breaking can be set as high as you want, it will cause the tractor too slow down earlier. But setting it too low will cause it too fly out of corners. This setting is useful so you can adjust it if you for example use the realistic weight mod or generally use heavier trailers.

**Comment by aviator64** [comment]
FYI, with lookahead for braking set to maximum some large vehicles (Lizard sleeper cab truck with Wilson grain trailer) still go into turns too fast and overshoot/get stuck. I've made the turns as smooth and gradual as possible.
