### ISSUE TITLE
[BUG] Alpha- & Beta-Download funktioniert nicht

### ISSUE THREAD

**Issue by andreasthu** [Stephan-S/FS19_AutoDrive#2093]
**Question:**   
I've got a question...
Hallo Leute
versuche heute schon 5x die neue alpha runterzuladen, funktioniert aber nicht.
ich sehe es, da in der scripts/autodrive.lua:
AutoDrive.version = "1.1.1.6"
steht.
öffne ich die Datei hier (https://github.com/Stephan-S/FS19_AutoDrive/tree/alpha-testing) im browser steht :
AutoDrive = {}
AutoDrive.version = "1.1.1.7-RC6"

lg
andreas

**Comment by Iwan1803** [comment]
Ich habe es mit Edge, Chrome & Firefox probiert. In allen Branches wird ein falscher Downloadlink generiert.
Der Fehler liegt daher scheinbar bei github und da können wir leider auch nichts machen.

**Comment by andreasthu** [comment]
DANKE

**Comment by Iwan1803** [comment]
Scheint so, als ob github das Problem gefixt hat.
Kann das bitte jemand mal prüfen und bestätigen?

**Comment by andreasthu** [comment]
hallo iwan
scheint gefixt zu sein,
(mit chrome browser)
alpha: 1.1.1.7-rc8
beta: 1.1.1.4
lg
andreas

**Comment by Iwan1803** [comment]
Super, dann mach ich hier mal zu 😎
