### ISSUE TITLE
Problem with AutoDrive 

### ISSUE THREAD

**Issue by MilanPali** [Stephan-S/FS19_AutoDrive#2096]
Hi,

I'm solving a problem with AutoDrive 1.1.1.4. I am using version 1.1.0.7 and I wanted to wish for a new version. I don't see any saved route in the game and the machine won't start. I always rewrote AutoDrive and everything worked (Courseplay I use version 6.4.0.4). I tried the Green Valley map even in the base without MODs. Only with Seasons, Courseplay, AutoDrive, Global Company. AutoDrive 1.1.1.4 and other new versions do not work. I will automatically see Autodrive in the game, but I will not see the routes. When I try to turn routes on and off, the map and other hints even disappear from the monitor. I have the latest version of PATCH.
I wanted to find an email to the author of AutoDrive somewhere, but I didn't find it anywhere. Until one youtuber who focuses on Farming sent me this Forum.

I will be happy if someone advises me or the owner of AutoDrive answers directly.

I don't want to stay with the old version. I want the new version because there is a function option for the "DO NOT DRIVE THERE" machine. He will not choose a shorter route but will go only where he can.

Thank you all, Milan, Czech Republic

Sorry, all translated by translator.

**Comment by Axel32019** [comment]
Hello @MilanPali , For a first look in your issues we need the following files: log.txt, AutoDrive_config.xml, items.xml, vehicles.xml
Then we could ask you for more information to find the cause for it.
Hint: rename .xml files to .txt to add them here.

**Comment by MilanPali** [comment]
I am sending the necessary documents. 
[AutoDrive_config.txt](https://github.com/Stephan-S/FS19_AutoDrive/files/7191692/AutoDrive_config.txt)
[items.txt](https://github.com/Stephan-S/FS19_AutoDrive/files/7191693/items.txt)
[log.txt](https://github.com/Stephan-S/FS19_AutoDrive/files/7191695/log.txt)
[vehicles.txt](https://github.com/Stephan-S/FS19_AutoDrive/files/7191697/vehicles.txt)

**Comment by Axel32019** [comment]
Hi, not a solution, but prevention, which is already included in alpha-version. As Github has some issue, you find here a link how to get: #2093

**Comment by MilanPali** [comment]
Hi,

I finally deleted everything and started the game from the beginning. everything works as it should and no MOD causes any problems. But I have to re-create the routes. Perhaps other versions will normally rewrite.

Thanks for your time and effort.
