### ISSUE TITLE
[Feature Request] Specific (numeric or alphabetical) order for rotating filling- and unloading stations

### ISSUE THREAD

**Issue by XPiRiJenZ** [Stephan-S/FS19_AutoDrive#2100]
First of all let me say thank you for your effort and this great mod!
It makes a lot more easier and is a very mighty tool in FS19! :)

My suggestion is that if you **only** enable **rotating filling- and unloading stations** AD does the following:

**example: transport of water for different productions**

Directory 1 - Filling stations:
01 water well near bakery
02 water well near cow husbandry
03 water well near fertilizer

Directory 2 - Unloading stations:
01 bakery
02 cow husbandry
03 liquid fertilizer production

**Description:**
From today's perspective, AD doesn't care whether the stations are numbered (or in an alphabetical order) or not.
In the beginning, the driver loads water at filling station 01 and unloads at unloading station 01.
But instead of now choosing filling- and unloading station 02, it chooses filling station 02 and unloading station 03 instead which means, that in the worst case the driver has to drive from the lower south-west corner to the upper north-easters corner of the map for its water delivery.

**Suggestion:**
What if you implement a feature for only this specific mode (rotating both), so that AD chooses the points in the specific order?

I'm looking forward to your feedback and suggestions!

**Comment by Axel32019** [comment]
Hallo @XPiRiJenZ , Wir können das gerne in Deutsch diskutieren...
Ich nehme an Du beziehst Dich auf: https://www.youtube.com/watch?v=XuNbt_7urFE
Hilfreich wäre mehr Einstellungen im HUD zu aktivieren, Wide-HUD ist nicht nötig, so sieht man auch in welchem Ziel-Modus die Fahrzeuge fahren.
Wenn ich das richtig gesehen habe war da noch ein Wasser-Transporter unterwegs - Hatte dieser die gleichen Einstellungen?
Rotieren, Be- und Entlade-Ordner?
Wenn ja, so werden die Ziele nach jedem Beladen neu zugewiesen. War schon ein Fahrzeug an einem Ziel, bekommt das nächste Fahrzeug nicht das gleiche sondern das nächste Ziel im Ordner. Das liegt im Ursprung dieser Funktion im Füllen von Bunkersilos, wo jedes Ziel gleichmäßig oft angefahren werden soll, egal von welchem Fahrzeug.
Bitte aktiviere mal Debug Pfadfindung und poste dann das log hier.

**Comment by Axel32019** [comment]
Keine Reaktion -> closed.
