### ISSUE TITLE
[Feature Request] Wasser Verteiler Modus

### ISSUE THREAD

**Issue by Achimobil** [Stephan-S/FS19_AutoDrive#2105]
**Is your feature request related to a problem? Please describe.**  
Ich habe alle Produktionen die Wasser benötigen in einem Ordner. Ein Verteiler holt an einem Wasserbecken C das Wasser ab und bringt dieses schon nach und nach zu den Produktionen. Die Reihenfolge hab ich mit Zahlen festgelegt, damit er bei z.B. 2 Produktionen A und B die weiter weg sind diese nacheinander auffüllt. Wenn jetzt der Tank nach A leer ist, dann fährt er den weiten Weg zu C. Das dauert dann so 4 Minuten hin und 4 Minuten zurück und dann setzt er seine tour fort.

**Describe the solution you'd like**  
Es wäre schön beim "Chaos Modus" sagen zu können, dass er immer an der nächstgelegenen Station Wasser holen soll. Also ich würde ein Wasserbecken D in der nächste von A und B aufstellen, so das der Tanker dann nicht so weit fahren muss.

**Describe alternatives you've considered**  
Man könnte mehrere Einzelne Kurse machen, Einen Kurs Nord und einen Kurs Süd wo dann eine Zentrale Wasserstelle ist. Da der LS aber mir mehr Fahrern immer langsamer wird wäre es besser, nur einen Wasserfahrer unterwegs zu haben.

**Additional context**  
--

**Comment by Iwan1803** [comment]
Die Alternative von dir ist doch eine schöne Lösung: lass den Wassertransporter erst die eine und dann die andere Strecke fahren. Wenn du nicht gerade auf 5x spielst, sollte es auch kein Problem darstellen und Produktionen leer laufen.
Und 1 Transporter mehr oder weniger sollte auch kein Problem darstellen. Bei mir sind gerne auch mal 15-20 Fahrzeuge im Einsatz und ich merke davon so gut wie nichts.

Ob sich der Aufwand für die vorgeschlagene Lösung lohnt und umsetzbar ist, muss @Axel32019 mal prüfen (Stichwort "Diesel tanken").

**Comment by Axel32019** [comment]
@Iwan1803 Tanken ist eine andere Geschichte!
@Achimobil Das Szenario nur für Wasser umzusetzen wäre nicht sinnvoll. 
Wenn man das richtig machen wollte:
- müssten die Füllstände der "Quellen" geprüft & berücksichtigt werden
- das für den gewählten Fülltyp
- entfernungsabhängig
- resistent gegenüber "Dieben", die von gleichen Quellen abholen

.... sind nur einige der Punkte die mir gerade einfallen
Fazit: Halte ich derzeit für (mich) zu zeitaufwendig / und wieder mehr Einstellungen...
