### ISSUE TITLE
[Feature Request] Zugangsberechtigung für MP

### ISSUE THREAD

**Issue by LSMaxx** [Stephan-S/FS19_AutoDrive#2109]
Wie wäre es das man den AD den Bearbeitungsmodus nur ab Status Farm-Manager bekommt, somit können nicht alle Player in das Streckensystem rumpfuschen.

**Comment by Axel32019** [comment]
Im MP redet man doch auch miteinander, oder nicht?
Da sollte es doch möglich sein festzulegen wann, wer, wo ... Änderungen macht, nicht-, darf
Die Berechtigungen verhalten sich leider auf verschiedenen Server auch immer mal sehr eigenartig, das zuverlässig umzusetzen ist mit viel Testzeit und -aufwand verbunden!

**Comment by Iwan1803** [comment]
Interessant wäre das schon, aber das würde auch bedeuten, das ich und auch ein AD-Unerfahrener als einzige bei uns auf dem Server das Streckennetz und Zielpunkte editieren sowie Parkplätze zuweisen kann. Es hat also nicht nur Vorteile 😉
Daher klären wir Änderungen untereinander ab und einer führt sie dann durch, wobei wir vorher ein Backup der AD-Config machen (sicher ist sicher).
Da würde ich mir eher wünschen, das der Editor-Modus nicht mehr per einfachem Linksklick aktiviert werden kann, damit man ihn nicht "aus Versehen" aktivieren kann.

**Comment by Iwan1803** [comment]
Closed -> https://github.com/Stephan-S/FS22_AutoDrive/issues/25
