### ISSUE TITLE
Suggestion: Look for init_config in mod map folder

### ISSUE THREAD

**Issue by aviator64** [Stephan-S/FS19_AutoDrive#211]
I am creating a map which will have an AutoDrive network included. At present, when you start a new game, your script looks for the map's init_config in the AutoDrive folder/ZIP file. Would it be possible for it to check there first, and if not found then look in the mod map folder?

That way the network can be packaged with the mod map and the player doesn't have to move it.

Thanks for all your hard work!

**Comment by Stephan-S** [comment]
Hey,
sounds like a good idea and I will see what I can do about that.
