### ISSUE TITLE
Eingestellte Wiederholungen werden ignoriert / Chosen repetitions are ignored

### ISSUE THREAD

**Issue by TripleX1978** [Stephan-S/FS19_AutoDrive#2115]
AutoDrive Version: 1.1.1.8

Stellt man z.B. im Modus "Beliefern und Abladen" die Anzahl der Wiederholungen auf einen Wert X, dann wird dieser nicht runtergezählt und der Fahrer fährt in einer Dauerschleife immer wieder die Ziele an.

**Comment by Iwan1803** [comment]
Ist ein verteilteltes Be-/Entladen aktiviert?

**Comment by TripleX1978** [comment]
Es ist rotierend entladen eingestellt. 
So wie man mir das damals erklärt hatte ist der eingestellte Wert die Anzahl wie oft ein Anhänger beladen wird, unabhängig davon ob rotierend beladen wird oder nicht.
Hat sich das wieder geändert?

**Comment by Iwan1803** [comment]
Das Runterzählen wurde für das verteilte Be- und/oder Entladen in 1.1.1.8 deaktiviert.

**Comment by TripleX1978** [comment]
Ok...danke für die Info.
Warum hat man das denn wieder geändert?
War für mich sinnvoll wenn ich eine Produktion leerfahren und an mehrere Stellen verteilen möchte. 
Hat doch ganz gut funktioniert.

**Comment by Achimobil** [comment]
Komisch, also bei mir funktioniert das verteilte Entladen noch mit den Wiederholung.
Also mein Wasserverteiler, wenn ich den 3 mal Wiederholen lasse, dann fährt er 3 mal zum Aufladen und dann von einer entladestelle zur nächsten. Funktioniert hier gut. Oder liegt das am flüssigkeitstransport dass es noch funktioniert?
Mir ist nur aufgefallen, dass wenn ein Fahrer mit wiederholungen einen unfall, also crash mit einem anderen hatte, dann setzt sich der Zähler auch bei ohne verteilen zurück.

Nur wenn ich mehrere Ladestellen habe, z.B. Milch von 3 Ställen abholen und zur Molkerei bringen, funktioniert das runterzählen nicht. Hier würde ich erwarten, dass er eine Ladestelle nach der anderen anfährt bis er voll ist und dann die volle Ladung zum abladepunkt gibt. das wäre die logische interpretation des wasserverteilers halt anders herum. Wenn ich 3 Wiederholungen mache fährt er 3 volle ladungen zu einem Ziel, so wie er beim verteilten entladen 3 volle ladungen auf die Ziele verteilt.

Beim gleichzeitigen Be und Entladen könnte man das dann genau so machen. Er fährt so lange von einem ladeort zum nächsten, bis er voll ist und dann von einem entlade ort zum nächsten bis er leer ist, das wäre dann ein zähler. 

Wäre das so nicht machbar?

**Comment by TripleX1978** [comment]
Ich meine, dass das genau so vorher gelaufen ist.
Fände es auch besser wenn man die Änderung wieder Rückgängig macht. Zumal ich noch nicht verstanden habe warum das überhaupt geändert wurde. Hatte bei mir immer ohne Probleme funktioniert. Ohne diese Funktion wird auf meinem Hof ganz schön stressig;-)

**Comment by Iwan1803** [comment]
Bitte poste den Vorschlag gerne auf der neuen github-Seite: https://github.com/Stephan-S/FS19_AutoDrive/issues/2147
