### ISSUE TITLE
Bremse ab wegen Verkehr[BUG]

### ISSUE THREAD

**Issue by eric4072** [Stephan-S/FS19_AutoDrive#2119]
**AutoDrive Version:** 1.1.x.x   
**Release or Custom Zip:** Release  
**Map (If applicable):** All  
**Vehicle / Type (If applicable): Drescher und Häcksler
**Multiplayer or Singleplayer:** Singleplayer  

**Describe the bug**  
Hallo, seit dem umstellen der setlichen Abstände kommt bei jedem Abfahrer die Meldung bei CP: bremse ab wegen Verkehr. der Häcksler reduziert dann auf die halbe Geschwindigkeit. Kolliboxen schlagen nicht an. 
Das komische: setzt man sich in den von AD gesteuerten Abfahrer, geht die Meldung weg und beide Fahrzeuge beschleunigen wieder.

habe jetzt die vorige Version wieder installiert, da tritt das nicht auf.Habe auch bei div. Youtubern das selbe Problem gesehen. Justieren des Rohrabstandes hilft gar nicht....

**If applicable - Steps to reproduce the behavior**  

**Screenshots**

**Comment by Axel32019** [comment]
Hallo @eric4072 , siehe: https://github.com/Courseplay/courseplay/issues/7564

**Comment by eric4072** [comment]
Danke ✌
