### ISSUE TITLE
Suggestion: Turn angle / Lenkeinschlag

### ISSUE THREAD

**Issue by sdl112** [Stephan-S/FS19_AutoDrive#212]
Hallo Stephan, 

bei bestimmten Fahrzeug/Anhänger Kombinationen kommt es immer wieder vor, dass sich diese "einklappen" und somit selbst blockieren (Klappmessereffekt).  Dies betrifft vor allem Anhänger mit Dolly, wie z.b. den Krampe SB3060, aber auch Sattelauflieger mit Zugmaschine. 
Wäre es möglich, bei solchen Fahrzeugkombis den Lenkeinschlag auf z.b. 90° zu beschränken?

Weiterhin: Wäre es viel Aufwand, die Futtermischwägen (z.b. Strautmann Vertimix 1702 SF) AD tauglich zu machen, da ich diesen gerne zum Futter ausfahren verwenden möchte. Aktuell erkennt er keine Trigger und Haltepunkte unter AD. Ich verwende den mod aus diesen pack:

[LS19_StrautmannPack_OY.zip](https://github.com/Stephan-S/FS19_AutoDrive/files/3274090/LS19_StrautmannPack_OY.zip)

**Comment by Stephan-S** [comment]
Hey,
in welchen Situationen kommt denn der 'Klappmessereffekt' vor?
Auf normalen Routen oder beim Drescher abtanken?

**Comment by sdl112** [comment]
Sowohl als auch, aber hauptsächlich beim Drescherabfahren. Der Fehler kommt immer dann vor, wenn das Fahrzeug neben der Strecke steht und einen wegpunkt sucht. Wenn er dann hierzu umkehren will, wird bei standard trailern der max Einschlagswinkel durch den Anschlag begrenzt. Bei Drehschemel oder Dolly Anhängern (Auflieger ebenso, da es mit Sattelzumaschine möglich ist, weiter als 90° einzuschlagen) kann je nach Deichsellänge der Einschlag fast 180° betragen. Dnn blockiert sich der Tractor mit dem Hänger selbst und fährt sich fest. 

Da beim Drescherabfhren/Rübenernter diese starken Richtungswechsel naturgemäß häufiger vorkommen,
tritt hier das Problem häufiger zu Tage.

Probier einfach mal mit dem Krampe SB3060 + Dolly in >Verbindung mit einem Traktor einen Rübenernter abzufahren. In der Regel dauert es nur 2-3 Versuche und er fährt sich fest.

**Comment by Stephan-S** [comment]
Ich schau es mir morgen mal an.
Was hast du als Wert für die 'Lookahead distance (turning)' eingestellt?

**Comment by sdl112** [comment]
Lookahead Bremse 40m, Lenkung 6m (seit dem hab ich das problem mit dem Abbiegen nach dem Laden übrigens nicht mehr, vielen Dank schon mal dafür!)
