### ISSUE TITLE
Verhalten Drescher abtanken mit Autodrive Fehler oder falsche Einstellung? [Question]

### ISSUE THREAD

**Issue by Achimobil** [Stephan-S/FS19_AutoDrive#2120]
**Question:**   
Situation:
Drescher auf dem Feld mit CP und Lands. Füllstand 90% in einer langen gerade. Rohr auf freier Seite. 
Einstellung Abfahrer rufen steht auf 80%. 

Mit Autodrive:
Abfahrer wird jetzt eingestellt mit AD für das Feld.
Abfahrer fährt los zum Drescher und Tanke diesen ab. Drescher startet bei Ankunft des Abfahrers den Motor und senkt das Schneidwerk. Bleibt aber stehen.

Selbst den Abfahrer spielen:
Ich fahre wie AD von hinten an den Drescher an. Auch hier startet der Motor des Dreschers und er senkt das Schneidwerk.
Unterschied hier: Sobald das Überladen beginnt, fährt der Drescher beim überladen weiter.

Hab ich da was falsch eingestellt oder ist das ein Bug?

**Comment by Axel32019** [comment]
Hallo @Achimobil,
Ich würde es sehr begrüßen wenn Du uns wissen lassen würdest welche CP- und AD-Version verwendet wurde!
Mit Autodrive:
AD hält den Drescher für die Dauer des Entladens an, ob dabei Motor etc. an oder aus sind hängt dann eher von CP und/oder Fahrzeug ab
Fährt der Abfahrer rückwärts, hält AD den Drescher an bis Abfahrer seine Rückfahr-Position erreicht oder 30s vergangen sind
Selbst den Abfahrer spielen:
Hier hat AD keinen Einfluß - Verhalten hängt von CP-Einstellungen ab.

**Comment by Achimobil** [comment]
AutoDrive: 1.1.1.8
Courseplay: 6.4.1.3

Ich meine da wäre in AD oder CP mal eine Option gewesen um ein zu stellen ob während der Fahrt überladen wird oder nicht. Ich finde die aber nicht mehr. Ist wohl raus genommen oder ich bin Blind.
Wenn es aktuell das ist was passieren soll, das der Drescher beim überladen anhalten soll und das nicht eingestellt werden kann, dann frage ich mich warum das geändert wurde und ob das wieder zurück kommt.

**Comment by rohne83** [comment]
> Mit Autodrive: AD hält den Drescher für die Dauer des Entladens an

das ist des Pudels Kern. Ist soweit ich mich erinnern kann auch schon immer so gewesen, dass der CP-Drescher bei AD-Abfahrern erst wieder losfährt wenn das Überladen abgeschlossen ist. Nur wenn der Abfahrer den Drescher noch in der Fahrt erreicht, wird auch im Fahren übergeladen. Works as designed also.

Wen das stört, der kann auch seine Abfahrer ganz bequem von CP steuern lassen. Für den Straßentransport können die ja mittlerweile trotzdem an AD übergeben.

**Comment by Achimobil** [comment]
>  Nur wenn der Abfahrer den Drescher noch in der Fahrt erreicht, wird auch im Fahren übergeladen. 
Genau darum geht es, So wich ich das gesehen habe, passiert das nicht mehr, aber ich werde mir das in der kommenden Ernte noch mal anschauen. So wie ich es gesehen habe fährt der AD zum Drescher, der jetzt bei 90% ist, fährt aber nicht bis ran sondern bleibt kurz vorher stehen und wartet dann, bis er voll ist. Erst wenn der Drescher voll ist, fährt der AD ran.

Melde mich, wenn ich das noch mal im Detail getestet habe.

**Comment by Achimobil** [comment]
NAch mehrstündigem Test funktioniert es genau so, wenn die Bahn noch lang genug ist, ich close deshalb das hier.
