### ISSUE TITLE
[Question] manual connect waypoints

### ISSUE THREAD

**Issue by MADxHAWK** [Stephan-S/FS19_AutoDrive#2123]
**Question:**   
I've got a question...

I havent played for quite some time. after updating to 1.1.1.2 from Github and later to 1.1.1.8 from Github i noticed the Button to manualy connect 2 wayponts is missing when adding / editting routes. 
So  is there any way to still select 2 waypoints and connect them with eachother beside enabeling autoconnect at Start / End?

**Comment by KillBait** [comment]
When in edit mode click on the start node (it should turn green) and then on the end node.

The Edit Mode section on the Wiki explains all the things edit mode can do now

**Comment by MADxHAWK** [comment]
thanks a lot
