### ISSUE TITLE
Adjustment for distance driver longitudinally to the pipe? + Einstellung für Abstand Abfahrer längs zum Rohr?

### ISSUE THREAD

**Issue by haamic** [Stephan-S/FS19_AutoDrive#2124]
**Question:**   
Hello,
I'm using a different thresher/driver combination than usual. The driver sometimes drives a bit too far forward under the pipe and the pipe is then no longer above the unloading surface. Is there another setting to adjust this? In the past, this distance was adjustable in addition to the pipe spacing.
Greetings Micha
++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Hallo,
ich nutze gerade eine andere Drescher/Abfahrer Kombination, als sonst. der Abfahrer fährt manchmal bisschen zu weit unter dem Rohr durch nach vorn und das Rohr ist dann nicht mehr über der Abladefläche. Gibts noch eine Einstellung um das anzupassen? Früher war doch zusätzlich zum Rohrabstand noch dieser Abstand anpassbar.
Gruss Micha

**Comment by Axel32019** [comment]
Hallo @haamic , Bitte mal einen Screenshot und die genauen Fahrzeuge, Geräte posten!

**Comment by rohne83** [comment]
Klingt sehr nach dem selben wie in  #1897 (Screenshot vom 10. Mai ist das bis zuletzt auch von mir beobachtete Verhalten)

**Comment by haamic** [comment]
nutze nun andere Fahrzeuge, womit es funktioniert.
