### ISSUE TITLE
Wartezeit für Flüssigkeits Transport

### ISSUE THREAD

**Issue by Daniel78-art** [Stephan-S/FS19_AutoDrive#2126]
Hallo liebes Autodrive Team eine Frage kann man eine Wartezeit einfügen für dem AD Zubringer Fahrer von Gülle, Gärreste sowie bei easy Autoload gibt?
Problem wenn der CP Fahrer voll ist fährt er gleich los und wenn der AD Fahrer leer ist auch gleich deswegen eine Wartezeit für den AD Fahrer.

![fsScreen_2021_11_21_18_37_50](https://user-images.githubusercontent.com/72348662/142773262-d7827d35-8a87-4884-aec9-df3112c35994.png)
t?

Gruß Daniel

**Comment by Iwan1803** [comment]
Wir sollen eine Wartezeit einbauen? Frag doch mal CP, ob sie eine integrieren 😉
Spaß beiseite, aber für dein Problem gibt es eine einfache Lösung: lass AD in dem Kreis andersrum fahren und verschieb den Zielpunkt entsprechend.

**Comment by Daniel78-art** [comment]
HI
okay ja das ist eine gute Idee das könnte man machen. danke schön 

Gurß Daniel

**Comment by Iwan1803** [comment]
Dann mach ich hier erstmal zu 😉
