### ISSUE TITLE
[Feature Request] Kreuzungsregelung (LS22)

### ISSUE THREAD

**Issue by eric4072** [Stephan-S/FS19_AutoDrive#2130]
Hallo,

in der Hoffnung dass ihr AD in den LS22 bringt, hätte ich einen Vorschlag bzgl. Kreuzungen.

AD läuft wirklich hervorragend. Bei höherer Verkehrsdichte kommt es aber immer wieder vor, dass sich Fahrzeuge beim abbiegen mit dem Gegenverkehr verkeilen. Ein herumspielen mit der blauen Linie hat leider keinen Erfolg gebracht. Klar ist diese dafür nicht da, jedoch die Hoffnung stirbt zuletzt...

Daher ist mir eine Idee gekommen:

Ist es möglich über Kreuzungen einen Kreis zu ziehen, welcher immer innerhalb nur von einem Fahrzeug befahren werden kann?

Sozusagen eine selbst einstellbare Fläche, welche von einem Fahrzeug blockiert wird bis es diese Fläche wieder verlässt.

Ich habe AD 100e Stunden am laufen und bis auf ein paar wirklich fragwürdige turns im Dreschermodus ist das "verkeilen" bei Kreuzungen das einzige wirklich störende Problem.

Ansonsten könnt ihr euch wirklich auf die Schulter klopfen. Ohne AD gibts für mich keinen LS mehr.

LG

Eric

**Comment by Iwan1803** [comment]
Das Problem ist grundsätzlich, das jede Implementierung egal welcher Lösung auch immer Rechenpower benötigt und für LS19 wird da nichts mehr kommen, da es die Engine auch einfach nicht mehr hergibt.
In LS22 gibt es vielleicht andere Möglichkeiten und Ideen für eine Umsetzung, wie man das Kreuzungsproblem "umgehen" kann, nehmen wir gerne entgegen.

**Comment by Iwan1803** [comment]
Bitte poste den Vorschlag gerne auf der neuen github-Seite: https://github.com/Stephan-S/FS19_AutoDrive/issues/2147
