### ISSUE TITLE
[BUG]unload bunker task to trailer is creating issue

### ISSUE THREAD

**Issue by moodid** [Stephan-S/FS19_AutoDrive#2131]
**AutoDrive Version:** 1.1.1.8
**Release or Custom Zip:** Release  
**Map (If applicable):** All  
**Vehicle / Type (If applicable):**   
**Multiplayer or Singleplayer:** Singleplayer  

**Describe the bug**  
While using autodrive to unload bunker to a trailer.  I am facing issue. When we switch on the autodrive shevole height is not getting adjust on time, the unloader is clashing with the trailer. Special when unloader is unloading the silage in second round. For first round it is working fine. But for next round it is creating issue.

**If applicable - Steps to reproduce the behavior**  
Start autodrive to unload bunker into trailer.
Wait for 2 to 3 round of unload. 
You will see the trailer is being run over by the unloader due to shovel height was not adjusted on time.

**Screenshots**

**Comment by Iwan1803** [comment]
The BGA mode is still a beta. Maybe later in FS22 we will work on it again.

**Comment by Iwan1803** [comment]
Closed -> https://github.com/Stephan-S/FS19_AutoDrive/issues/2147
