### ISSUE TITLE
[Question] Course Editor? 

### ISSUE THREAD

**Issue by yaitsbilly** [Stephan-S/FS19_AutoDrive#2134]
Will Course Editor be updated as well?

**Comment by KillBait** [comment]
I'm the one currently updating the editor, my plan is to update it for the FS22 version of AD.

How much work that will take is unknown at the moment, i would like to point out that i am
not part of the AD dev team, so i will have wait for the release like everybody else to see what
has/hasn't changed. 

In the meantime, i am currently adding things that will be helpful for both the old and new
versions.

**Comment by KillBait** [comment]
I get home from work to find AD for FS22 is released :) , after a quick look it doesn't seem like a major update is needed, so i will post again when i have it working

**Comment by Stephan-S** [comment]
Hey @KillBait 
this is great wwork you are doing with the Editor.
Should we maybe change the approach here?
You just create your own repo with only the editor inside and we will add a link on both the FS19 and now the FS22 repo to your Editor repo?
This way you gain full control over the editor updates and it's clear for the players where they can get updates and contact you.

Sorry I haven't really checked in with you before!
This is long overdue and my apologies. I wasn't as active during the end phase of 19 and haven't really processed the merge request myself.

Best,
Stephan

**Comment by KillBait** [comment]
Hi @Stephan-S

I would be happy to do that if everybody is ok with that decision. and no apologies are needed, real life stuff happens 

I have to admit, i have gone a lot further adding stuff than i intended ( in fact, it's a great example of extreme feature
creep lol )

**Comment by KillBait** [comment]
i just pushed another commit  ( about 20 minutes ago ) to add FS22 PDA image import and did some testing, also
not exactly the right place, but are the node flags = 2 or 4 anything special or are they due to the auto generation
from the map splines?.. i did a quick look through the source but couldn't see anything obvious?

**Comment by Stephan-S** [comment]
Yeah, marks them as autogenerated directly from the splines = 2 or auto generated crossing section = 4

**Comment by KillBait** [comment]
I have created the repository for the editor and put the last commit from today as the newest release

link is [here](https://github.com/KillBait/AutoDrive_Course_Editor), when you get around to swapping all
the links over i will close the pull request here

**Comment by Stephan-S** [comment]
I added your link at the Readme of both repos.
Thank you for your work on it!

**Comment by Iwan1803** [comment]
As it is now linked -> closed 😉
