### ISSUE TITLE
Vorschläge:

### ISSUE THREAD

**Issue by LarsCSA** [Stephan-S/FS19_AutoDrive#2135]
1.) Ein Maschinen Parkplatz:
Einer Maschine, Anhänger, etc., einen Parkplatz zuweißen, so das man diesen drücken kann, und die Maschine auf die exakte Position
zurück gestellt wird. (Wird erst sinnvoll, mit den zwei weitern Vorschlägen.)

2.) Folgebefehle:
Beispiel: Man möchte eine Maschine Parken lassen und anschließend soll auch das Fahrzeug Parken.
Man drücke Shift oder ähnliches, drückt das Symbol für die Maschinen Park Position, hält Shift weiter gedrückt und drückt das Symbol um das fahzeug zu parken.
Der Traktor fährt zu dem Maschinen Parkplatz (Hängt mit hilfe von Vorschlag 3 die Maschine ab) und fährt Automatisch, auf seinen Parkplatz. Mit den Funktionen von
Vorschlag 3 ist hier großes Potenzial.

3.) Eine Funktion die in AutoDrive meiner Meinung nach mit am nützlichten sein könnte ist folgende:
An jedem Wegpunkt eine Befehlskette anzubringen. Sprich wenn man über diesen Punkt fährt (muss kein Wegpunkt sein den man als Ziel auswählen kann
(normaler Wegpunkt)) wird eine Kette von befehlen abgearbeitet.

Beispiel: Traktor fährt vor ein Tor, der zu erreichende Wegpunkt liegt dahinter. Die Befehlskette an einem der "Fahrpunkte" vor dem Tor besagt,
"Tor >Wodden door 1< (oder wie auch immer man das in dem Code benannt hat), öffnen" 
2. Befehl-> "3 Sekunden warten", 
>Befehlskette ende<

Nach dem Tor an einem "Fahrpunkt":
1. Befehl-> "Wodden door 1, schließen".
>Befehlskette ende<

(In dem Fall bei 2 Weg Kursen für jede mögliche Fahrtrichtung eine Befehlskette).

Beispiel 2:
Mit Hilfe von Vorschlag 2 währe dann folgendes möglich:
Man halte Shift und befielt ihm zu "Feld 21 abladen" zu fahren (fährt dann z.B.: eine Zuckerrübenernte ab, die ihm ein Überladewagen übergibt.)
Mit Folgebefehl zum Silo schicken mit der Modi "abladen".
Man drückt nun (mit gehaltener Shift Taste) die Anhängerparkposition und anschließend, den Befehl zu dem anderen Wegpunkt, wo eine Sämaschine steht.
Weiter Shift gehalten und Wegpunkt "Feld 33" setzten, sowie Cousplay aktivieren.
(Diese ganze Aktion dauert 30 Sekunden, wenn man schon weiß was die Maschine machen soll->jedoch sollte sie nun einem mindestens 3min Arbeit ersparen)

Durchführung:

Fährt zu "Feld 21 abladen", dort erwartet ihn dann eine Befehlskette, mit den Punkt -> "Wenn zu 80% voll, weiter in der Befehls kette" in dem Fall
währe die Befehlskette zu ende und er würde weiter Fahren, bei dem Silo abladen, die Parkpostition des Anhängers erreichen und dort mit dem Befehl 
"Gerät am Heck abhängen/anhängen" den Anhänger (da einer vorhaden, abhängen, sonst würde der Traktor sie anhängen).
Befehlkette zu ende-> es geht weiter, der nöchste Folgebfehl lässt den Traktor zu der Parkposition der Sämaschine fahren, wo wieder eine Befehlskette wartet.
die besagt -> "Gerät am Heck abhängen/anhängen" in dem Fall wird die Sämaschine angehängt. -> Er fähr weiter zu Feld 33 und startet Cousplay.
Ende des Folgebefehls. Und hier könnte man halt extrem erweitern, indem man zB.: noch ein Befehl mit aufladen (der Sämaschine) dazwischen setzt usw.

Mit freundlichen Grüßen

Lars

**Comment by kferrano** [comment]
Punkt 1: gibt es schon. Einfach via G das Gerät auswählen und dann ganz normal wie beim Fahrzeug die Parkposition bestimmen.

Punkt 2: Folgebefehle stell ich mir etwas schwierig vor, jedenfalls was das Parken angeht, da  ia da wiederum eingebaut werden muss dass AD das Gerät automatisch abhängt.

**Comment by Iwan1803** [comment]
Mal abgesehen davon, das wir an AD für LS19 nichts mehr machen werden:

zu 2.: 
Automatismus schön und gut, aber irgendwo sollte dann auch mal Schluss bzw. eine Grenze sein. Wir bieten schon so viele Funktionen an und es gibt immer wieder Leute, die noch mehr fordern, um dem Spiel am Ende nur noch wie ein Manager zu zuschauen oder was soll das Ziel einer "Auftragskette" sein? Wie groß soll das HUD werden, damit man dies alleine einstellen kann?
Sorry, allein die Komplexität und der Programmieraufwand sprengen den Rahmen und ich glaube nicht, das die beiden Programmierer das anders sehen werden.

zu 3.:
Für Tore & Co. hat HoT mal ein Skript geschrieben, damit sich diese automatische öffnen, wenn man davor fährt und sich auch wieder automatisch schließen.
In den AD-Einstellungen kann man einstellen, das im Anschluss eines Jobs der Parkplatz für das selektierte Gerät angefahren wird, aber abkuppeln müsste man dennoch selber.

**Comment by LarsCSA** [comment]
Danke für die Rückmeldung.
Es tut mir leid, das es so gewirkt hat, dass meine Vorschläge wie Forderungen rüber kamen, dies war nicht meine Absicht (wusste nicht wo ich sonst schreiben sollte). 

AD ist ein extrem tolles Tool was sehr viel Lob verdient hat, keine Frage. Auch ich als angehender Programmierer bin mir der Arbeit durchaus bewusst.
 
Ich stimme zu das alles von einer KI machen lassen nicht Sinn und Zweck von LS ist (Finde Automation halt extrem cool). 

Über die bereits vorhanden Funktionen die ich erwähnt habe wusste ich nicht bescheid. Ihr seid die Modder, ihr macht das was ihr wollt.

(PS: Meinte eh LS 22) 

Mit freundlichen Grüßen 

Lars

**Comment by Iwan1803** [comment]
Nicht falsch verstehen, denn wir sind für Vorschläge immer offen, welche AD verbessern, aber es gibt halt immer wieder Vorschläge, welche aus dem Spiel eher einen Manager machen und das kann nicht der Sinn von AD sein 😉
Wir müssen zum bewerten, wie sinnvoll ein Vorschlag ist und dann aber natürlich auch, welche Zeit investiert werden müsste, um das ganze auch zu programmieren und zu testen (kennst du ja sicher). Leider gibt es immer wieder Leute, welche mit unserer Entscheidung nicht einverstanden sind und sich dementsprechend aufführen.
Ich lasse das ganze hier mal offen, was nicht heißt, das wir es auch umsetzen werden, aber dann geht es zumindest nicht verloren.

**Comment by Iwan1803** [comment]
Falls du noch einen Vorschlag hast, dann poste den gerne auf der neuen github-Seite: https://github.com/Stephan-S/FS19_AutoDrive/issues/2147
