### ISSUE TITLE
Namen Vergeben Fehlermeldung

### ISSUE THREAD

**Issue by Gyffes** [Stephan-S/FS19_AutoDrive#214]
Hi habe gerade mal dem Fahrer bei mir einen Namen Vergeben "Weizen Feld 15"

Erhaltee im Log dann die Fehlermeldung:

`2019-06-11 20:06 Error: Running LUA method 'update'. 

2019-06-11 20:06 D:/home/sid_1063501/farmingSim_2019/profile/mods/FS19_AutoDrive/gui/enterDriverNameGUI.lua:22: attempt to index field 'controlledVehicle' (a nil value)`

Edit:
Die Namen werden auch nicht übernommen, oder unten Angezeigt. 
Wobei die Anzeige mittig unten am Bildschirm, wenn der Fahrer z.B. sein Ziel erreicht hat, noch in Englisch ist. 

Siehe Screens. 
![fsScreen_2019_06_11_20_33_16](https://user-images.githubusercontent.com/51527134/59297568-ce887100-8c88-11e9-88de-33ac6417cd7e.png)
![fsScreen_2019_06_11_20_34_01](https://user-images.githubusercontent.com/51527134/59297573-d1836180-8c88-11e9-9e2d-11822c42bb19.png)

**Comment by Stephan-S** [comment]
Danke für die Meldung.
Ich muss die Funktion noch Multiplayer-ready machen

**Comment by Gyffes** [comment]
Ah ok danke dir.

**Comment by Gyffes** [comment]
Grüßee und guten Moren wa ds eiegentlichh schon gfixt? im MP

Danke. schönen Tag allen.

**Comment by Stephan-S** [comment]
In der Theorie ja, in der Praxis warte ich auf dein Feedback, da ich derzeit keinen Server laufen habe :-)

**Comment by Gyffes** [comment]
Ah sooo Ja dann kann ich dir sagen. In 1.3.3 Läuf es nicht Anzeig unten immer nochh in English. 
Namen kann man Zwar veergeben. Werden aber Ignoriert. Allerdings kleine Fehleermeldungen :-)

> 2019-06-22 09:45 Sommy joined the game 2019-06-22 09:46 data/firstPerson/highPressureWasherLances/kaercher/hds9184MLance.i3d (2.99 ms) 2019-06-22 09:47 attacherRotFactor 1 2019-06-22 09:47 table: 0x2d7a09a0 == table: 0x2d7a09a0 2019-06-22 09:49 attacherRotFactor 1 2019-06-22 09:49 table: 0x0bfc9be8 == table: 0x0bfc9be8 2019-06-22 09:50 Game saved successfully. 2019-06-22 09:57 attacherRotFactor 1 2019-06-22 09:57 table: 0x2d825e70 == table: 0x2d825e70 2019-06-22 09:58 attacherRotFactor 1 2019-06-22 09:58 table: 0x33585e68 == table: 0x33585e68 2019-06-22 09:58 attacherRotFactor 1 2019-06-22 09:58 table: 0x33585e68 == table: 0x33585e68 

![fsScreen_2019_06_22_10_07_47](https://user-images.githubusercontent.com/51527134/59961285-fa4ff600-94d5-11e9-9a87-5edd94bb404f.png)
![fsScreen_2019_06_22_10_09_53](https://user-images.githubusercontent.com/51527134/59961287-fc19b980-94d5-11e9-9c0e-a7009277dbfb.png)

**Comment by Gyffes** [comment]
Grüße Aktuell bei Version 1.3.5 erscheint das Menu zum eingeben des Namens für eine sekundee und verschwindet direkt wieder. 

Fehlermeldung lt Log

> 2019-07-08 17:28 Error: Running LUA method 'update'.
2019-07-08 17:28 C:/Users/webma/Documents/My Games/FarmingSimulator2019/mods/FS19_AutoDrive/gui/enterDriverNameGUI.lua:23: attempt to call method 'setTexts' (a nil value)


Danke Vielmals

**Comment by Gyffes** [comment]
Zur Info Lua Fehler ist Behoben. 
Die Funktion aber noch nicht gegeben. Text weiterhin auf English eingegebene Namen werden nicht übernommen.
Grüße.

**Comment by Stephan-S** [comment]
Danke für die Erinnerung.
Ich habe mir das Ganze gerade nochmal schnell angesehen und einen Fehler behoben.
Kannst du die Version mal auf dem Server testen bei Gelegenheit?

In die letzte Release Version hat es die Änderung ja leider nicht geschafft und da ich nicht nach 30 Minuten schon den nächsten Release erstellen möchte, wäre es super wenn du es mit den src Files testen könntest.

Vielen Dank :-)

**Comment by Gyffes** [comment]
ok welche Datei muss ich austauschen 
:)

**Comment by Stephan-S** [comment]
Hab dir hier mal eine Version gepackt :-)
[FS19_AutoDrive.zip](https://github.com/Stephan-S/FS19_AutoDrive/files/3387914/FS19_AutoDrive.zip)

**Comment by Gyffes** [comment]
So hatte grad schon eine Version zusammen gestellt und vermuten ich hab nen fehler gemacht. 
Habs dirkt nochmal mit deinere gepackten Version probieert. Danke fürs hochladen übrigens.

Leider kein Erfolg. Siehe Log und Bilder. 

> 2019-07-12 22:42 dataS2/character/crow/crow.i3d (14.12 ms) 2019-07-12 22:43 dataS2/character/humans/player/player02.i3d (306.58 ms) 2019-07-12 22:43 ShaderId envmap_blending.cg:1 2019-07-12 22:43 ShaderId envmap_blending.cg:2 2019-07-12 22:43 ShaderId envmap_blending.cg:4 2019-07-12 22:43 ShaderId envmap_blending.cg:8 2019-07-12 22:43 ShaderId envmap_blending.cg:16 2019-07-12 22:43 ShaderId envmap_blending.cg:32 2019-07-12 22:43 Error: Running LUA method 'packetReceived'. 2019-07-12 22:43 D:/home/sid_1063501/farmingSim_2019/profile/mods/FS19_AutoDrive/scripts/Events/AutoDriveUpdateNameEvent.lua:17: attempt to index local 'vehicle' (a nil value) 2019-07-12 22:43 data/shared/ai/trafficCollision.i3d (0.48 ms) 2019-07-12 22:44 Error: Running LUA method 'packetReceived'. 2019-07-12 22:44 D:/home/sid_1063501/farmingSim_2019/profile/mods/FS19_AutoDrive/scripts/Events/AutoDriveUpdateNameEvent.lua:17: attempt to index local 'vehicle' (a nil value) 2019-07-12 22:44 Error: Running LUA method 'packetReceived'. 2019-07-12 22:44 D:/home/sid_1063501/farmingSim_2019/profile/mods/FS19_AutoDrive/scripts/Events/AutoDriveUpdateNameEvent.lua:17: attempt to index local 'vehicle' (a nil value) 2019-07-12 22:45 Error: Running LUA method 'packetReceived'. 2019-07-12 22:45 D:/home/sid_1063501/farmingSim_2019/profile/mods/FS19_AutoDrive/scripts/Events/AutoDriveUpdateNameEvent.lua:17: attempt to index local 'vehicle' (a nil value) 2019-07-12 22:45 Error: Running LUA method 'packetReceived'. 2019-07-12 22:45 D:/home/sid_1063501/farmingSim_2019/profile/mods/FS19_AutoDrive/scripts/Events/AutoDriveUpdateNameEvent.lua:17: attempt to index local 'vehicle' (a nil value) 2019-07-12 22:46 Error: Running LUA method 'packetReceived'. 2019-07-12 22:46 D:/home/sid_1063501/farmingSim_2019/profile/mods/FS19_AutoDrive/scripts/Events/AutoDriveUpdateNameEvent.lua:17: attempt to index local 'vehicle' (a nil value)
![fsScreen_2019_07_12_22_48_23](https://user-images.githubusercontent.com/51527134/61157835-8a8ec300-a4f7-11e9-8f61-9ee98a29f64d.png)
![fsScreen_2019_07_12_22_35_00](https://user-images.githubusercontent.com/51527134/61157837-8b275980-a4f7-11e9-9d8c-1b4173ae9f73.png)

**Comment by Gyffes** [comment]
moin habe da mal bissel getestet und festgestellt. SP Funktioniert gut. MP wenn ich es selber hoste funktioniert auch gut. 
Nutzte ich den gemieteten Server. Funktioniert es nicht.  Es scheint also ein Problem mit dem übertragen oder Speichen der Daten zusammen hängen. 
Vielleicht hilft das bei der fehler Suche. 

vielen Dank.

**Comment by Gyffes** [comment]
Hi und schönes Wochenende, 
Kurze Info 
Auch in der Aktuellen Version auf Dedi Server Funktioniert das mit den Namen bei mir nicht.
Ansonsten Top Arbeit und super Neuerungen. 

2019-08-17 11:25 D:/home/farmingSim_2019/profile/mods/FS19_AutoDrive/scripts/Events/AutoDriveUpdateNameEvent.lua:17: attempt to index local 'vehicle' (a nil value)

Euch allen noch nen schönen Tag.

**Comment by Gyffes** [comment]
Ich gehe mal davon aus das es hier mit zu tun hat. Falls nicht mach ich gern ein neuen post auf. 

Ich habe grad mal Version 1.04.8 drauf gemacht und 2 Fahrzeuge mit AD zu einem Ziel geschickt.

Es lief soweit ganz gut nur auf einmal schlugen sie die Lenkung ein Fuhren langsam und blibeen stehen. Ok dachte ich  mir beende ich halt AD und schicke sie wieder auf die reise leider läst sich AD  für die Fahrzeuge nicht beenden oder bei anderen Fahrzeugen Starten. 

Allerdings wird mein Logg zugespammt mit Folgender Meldung. 

> 2019-08-18 10:46 D:/home/farmingSim_2019/profile/mods/FS19_AutoDrive/scripts/AutoDriveDriveFuncs.lua:519: attempt to concatenate field 'driverName' (a nil value)
> 2019-08-18 10:46 Error: Running LUA method 'update'.
> 2019-08-18 10:46 D:/home/farmingSim_2019/profile/mods/FS19_AutoDrive/scripts/AutoDriveDriveFuncs.lua:519: attempt to concatenate field 'driverName' (a nil value)
> 2019-08-18 10:46 Error: Running LUA method 'update'.
> 2019-08-18 10:46 D:/home/farmingSim_2019/profile/mods/FS19_AutoDrive/scripts/AutoDriveDriveFuncs.lua:519: attempt to concatenate field 'driverName' (a nil value)
> 2019-08-18 10:46 Error: Running LUA method 'update'
> 
> 
> 
>

**Comment by Gyffes** [comment]
Moin kleine Info für zwischen durch. 

Auch in Version 1.0.4.9 im MP Steam Dedi Server besteht die Fehlermeldung weiterhin. Danke.

> 2019-08-21 19:54 D:/home/sid_1063501/farmingSim_2019/profile/mods/FS19_AutoDrive/scripts/AutoDriveDriveFuncs.lua:519: attempt to concatenate field 'driverName' (a nil value)
2019-08-21 19:54 Error: Running LUA method 'update'.

**Comment by Gyffes** [comment]
Wunderbar 1000 dank. Die Namens Vergabe fuunktioniert endlich wie sie soll. 
Bis darauf das er noch den Englischen Text anzeigt aber das ist nicht so wild.. 

Dank die vielmals. 


![fsScreen_2019_08_27_19_22_16](https://user-images.githubusercontent.com/51527134/63793709-8d574300-c900-11e9-9f1f-d045ac8d13ff.png)

**Comment by Stephan-S** [comment]
war ja auch ne schwere Geburt :D 
Hast du mal versucht den Server auf Deutsch umzustellen?
Der Text wird ja wie gesagt im MP vom Server vorgegeben. Wenn du dort die Sprache einstellen kannst, wird er auch Deutsche Texte liefern.

**Comment by Gyffes** [comment]
das war auch schon mal meine vermutung gewesen.  Und er ist auf deusch gestellt zumindest lt LS Server Oberfläche. Mir ist gerade noch ein anderen Problem aufgefallen wa vermutlich mit dem Dedi zusammen hängt dazu mach ich einen Extra post. zum Aus einander halten. 
Danke. 


Matchmaking Server
Germany
Game Language
Deutsch

**Comment by Gyffes** [comment]
Hier ein kleiner Nachtrag: Also der Hoster ist Schuld. 
Habe mich mal bissel kundig gemacht in der log.txt gibt es den Eintrag 

> Available Languages: en de jp pl cz fr es ru it pt hu nl cs ct br tr ro kr

dieser Zeigt an welche Sprachen verfügbar sind. bei mir steht nur 

> Available Languages: en

was bedeutet Server ist English und nur Englisch und nur Englisch möglich.

Da mein Client auf Deutsch gestellt ist,  Zeigt er die Menüs usw alles in Deutsch an. Nur halt solche "Server"meldungen nicht. 
Insoweit Frage ich mal beim Hoster nach, :-) 
Danke dir.
