### ISSUE TITLE
[Feature Request]

### ISSUE THREAD

**Issue by Cola7777** [Stephan-S/FS19_AutoDrive#2144]
Für eine stärkere Automation wäre es schön wenn Fahrten getriggert werden könnten, ähnlich dem Abholer der auf den Ruf des Dreschers wartet.

Bsp.  Ein Fahrzeug hat eine Route vom Silo zur Mühle und bekommt in der Route neben Ziel und Start eben auch noch den Trigger eingetragen. Meldet sich die Mühle, fährt das Fahrzeug zum Silo - zur Mühle und auf seine Parkposition zurück. Auch eine Anwendungsmöglichkeit wäre bsp.: das sich Ställe melden etc.

Vielen Dank für die tolle Mod und das ihr auch einen Support Discord dafür eingerichtet habt. Das kenne ich so nicht. Respekt.

**Comment by Iwan1803** [comment]
Bitte poste den Vorschlag gerne auf der neuen github-Seite: https://github.com/Stephan-S/FS19_AutoDrive/issues/2147
