### ISSUE TITLE
Shortcut for rep. and fuel[Feature Request]

### ISSUE THREAD

**Issue by Baltusar** [Stephan-S/FS19_AutoDrive#2145]
Hallo zusammen und danke erstmal für euren tollen job den ihr macht!

Gibt es Überlegungen auf das HUD zwei Buttons einziehen zu lassen die das ausgewählte Fahrzeug direkt zur Tankstelle bzw. Reparatur schicken?
Da AD schon Fahrzeuge eigenständig zu diesen Stellen schicken kann wenn der Tank bzw. die Beschädigungen zu nieder/hoch sind müsste es doch umsetzbar sein. 
Eigentlich so eine Art wie eure Parkfunktion die ihr drin habt.
LG
Baltusar

**Comment by Iwan1803** [comment]
Mal abgesehen davon, das es für LS19 keine Weiterentwicklung mehr geben wird:
in AD für LS22 kann man hierfür Tastenkombinationen hinterlegen.
https://github.com/Stephan-S/FS22_AutoDrive

**Comment by Iwan1803** [comment]
Geschlossen: https://github.com/Stephan-S/FS19_AutoDrive/issues/2147
