### ISSUE TITLE
[BUG] Waypoint 

### ISSUE THREAD

**Issue by Evadtheawesome** [Stephan-S/FS19_AutoDrive#2146]
**AutoDrive Version:** 1.1.x.x     <version>2.0.0.0</version>
**Release or Custom Zip:** Release  - Unknown but downloaded 23/12
**Map (If applicable):** All  No Mans Land
**Vehicle / Type (If applicable):**   Happened on multiple vehicles
**Multiplayer or Singleplayer:**  Singleplayer  

**Describe the bug** 
1. While editing the course I am able to click on a waypoint and move it. I then release thewaypoint and it shows released but if  Iclick amywhere else the waypoint becomes activeand moves to that point.
2. Sometimes I am unable to release the waypoint at all.

**If applicable - Steps to reproduce the behavior**  
I have made a few couses and even a single waypoint and the problem always occurs.

**Screenshots**  
![3  re-attach](https://user-images.githubusercontent.com/54986991/147304810-015914ab-3f95-48b6-8181-2894e4a889f6.jpg)
![1 right click](https://user-images.githubusercontent.com/54986991/147304812-4bc1ba51-b54c-4845-95d0-1d67ee70ca51.jpg)
![2 release](https://user-images.githubusercontent.com/54986991/147304813-f5f08e9c-d61e-485d-aa86-5b1324df1fab.jpg)

**Comment by Iwan1803** [comment]
Wrong page -> https://github.com/Stephan-S/FS22_AutoDrive
