### ISSUE TITLE
[Feature Request]

### ISSUE THREAD

**Issue by marlogamer** [Stephan-S/FS19_AutoDrive#2149]
Hallo liebes Autodrive Team,
Ich würde mir eine Funktion wünschen das Abfahrer beim Häckseln Hupen wenn sie ihr eingestelltes Trailer Volumen ausgeschöpft haben, damit wenn man AD abfahren lässt aber selber häckselt weiß wann man anhalten muss um auf den nächsten Abfahrer zu warten. 
Danke für eure tolle Arbeit und ich hoffe das ich bald meinen Vorschlag schon umgesetzt nutzen darf.
Liebe Grüße

**Comment by Iwan1803** [comment]
Bitte poste den Vorschlag gerne auf der neuen github-Seite: https://github.com/Stephan-S/FS19_AutoDrive/issues/2147
