### ISSUE TITLE
Hinweis, wenn ein Helfer blockiert ist / Notice when al helper is blocked

### ISSUE THREAD

**Issue by Pit-Ffm** [Stephan-S/FS19_AutoDrive#2150]
Moin, zuerst einmal vielen Dank für die superschnelle Umsetzung. Was mir aber im 19er schon gefehlt hat, ist eine Meldung wenn sich der Fahrer (warum auch immer) festgefahren hat. Schickt man einen Fahrer los, und arbeitet dann woanders weiter, wäre es prima, wenn eine Meldung aufploppen würde, wenn sich die Räder durchdrehen (steht vor geschlossenem Tor, ist gegen einen Baum gefahren, ist umgekippt...), ähnlich dem Hinweis beim Ankommen am Zielpunkt.
Danke und schönes neues Jahr euch allen und:  BLEIBT GESUND
Peter (Pit-Ffm)

**Comment by Iwan1803** [comment]
Bitte poste den Vorschlag gerne auf der neuen github-Seite: https://github.com/Stephan-S/FS19_AutoDrive/issues/2147
