### ISSUE TITLE
Fahrzeuge selbstständig auftanken

### ISSUE THREAD

**Issue by Mannie313** [Stephan-S/FS19_AutoDrive#217]
Hallo @Stephan-S wäre es möglich die Fahrzeuge an Tankstellen und Befüllbaretankstellen diese ab einen prozentsatz von 20% zu betanken.

MFG Mannie313

**Comment by Stephan-S** [comment]
Hey, ich habs auf dem Schirm. Aber ich fass es mal mit #365 zusammen und mache hier zu
