### ISSUE TITLE
AD und Anhänger mit Autoload

### ISSUE THREAD

**Issue by Williwillswisse** [Stephan-S/FS19_AutoDrive#22]
Hallo Stephan,
ich habe heute zum ersten Mal einen Anhänger mit Autoload Funktion angehängt.
Danach erhalte ich die folgende Meldung im Log.
mods/FS19_AutoDrive/scripts/AutoDriveFunc.lua:32: attempt to call method 'getFillUnits' (a nil value)
2019-04-02 07:45 Error: Running LUA method 'update'.
Die Anhänger kommen aus dem Mod AUTOLOAD PACK V1.3.

**Comment by Stephan-S** [comment]
Danke für die Meldung.
Die Fehlermeldung kann ich beim nächsten Update umgehen. Das automatische Abladen oder Beladen wird damit allerdings nicht unterstützt. Ich habe mich mit den AutoLoad Trailern auch noch gar nicht auseinander gesetzt, also kann ich nicht gut abschätzen ob das leicht in AutoDrive zu integrieren ist oder nicht.

**Comment by Williwillswisse** [comment]
Die Meldung ist nicht das Problem. Das Fahrzeug fährt dann nicht mit AutoDrive.

**Comment by Stephan-S** [comment]
Ja, sorry. Das meinte ich natürlich damit :-)
