### ISSUE TITLE
Update Ways key binding does not work

### ISSUE THREAD

**Issue by aviator64** [Stephan-S/FS19_AutoDrive#220]
Tried assigning a couple of different keyboard bindings to "Update Ways" - no conflicts with other assignments, but it just doesn't do anything. All the other ones I've assigned for AD work fine.

**Comment by Stephan-S** [comment]
Oh yeah,
that was never properly ported over from the FS17 version of the mod.
Thanks for noticing :-D
Will fix it in the next release
