### ISSUE TITLE
Misses turn when joining the network from far away

### ISSUE THREAD

**Issue by aviator64** [Stephan-S/FS19_AutoDrive#221]
When a vehicle is assigned a destination and starts driving to the closest waypoint, if it is not already close to the waypoint, and if it approaches the course at a sharp angle (at or close to 90 degrees) it does not slow down, overshoots, and turns in endless circles.

This happens consistently when in unload combine mode and the vehicle starts in the middle of a field, a long distance from the nearest waypoint.

**Comment by Stephan-S** [comment]
Should be fixed with previous release. If not, please reopen. Thanks
