### ISSUE TITLE
Park on field not working under certain circumstances

### ISSUE THREAD

**Issue by aviator64** [Stephan-S/FS19_AutoDrive#222]
Combine working a field running under Courseplay
If the pipe is in fruit and the combine fills, Courseplay has it back up and turn slightly so that the pipe is out of the fruit.
The tractor, running under AD, unloads the combine OK, but even though the tractor is not in the fruit, it still returns to the start point.
Park on field works correctly if the combine pipe is already out of the fruit when the combine fills up.
Hope that made sense!

**Comment by aviator64** [comment]
Update - the issue above occurred on north-south rows but not on east-west rows, at least so far. Strange!

**Comment by Stephan-S** [comment]
hey, yeah I get what you mean :-)

this can happen if the grid cell that the driver is standing in when unloading is 'marked' as contains fruit/crop.

As I explained, the pathfinding algorithm splits all field into cells and checks for each grid if the amount of fruit is above a certian level.
Now depending on the starting point of the algorithm and the angle (North-South, east-west) it can happen that the space between combine and fruit is flagged as containing fruit/crop.

I guess that is not a high priority issue for me. And I'm not sure I will invest the time to fix this. But you never know^^
