### ISSUE TITLE
Fehler MP

### ISSUE THREAD

**Issue by Bandesss** [Stephan-S/FS19_AutoDrive#223]
Wollte heute den Punkt Tankstelle anfahren HofBergmann...
Dann kamen viele Fehler und server stockte
[log.txt](https://github.com/Stephan-S/FS19_AutoDrive/files/3293428/log.txt)
Hoffe du kannst uns helfen?
Gruss Ronny

**Comment by Stephan-S** [comment]
Hab hier mal überall wo es passieren kann noch checks eingebaut. Besser spät als nie :D
