### ISSUE TITLE
Fail to load grass from silo

### ISSUE THREAD

**Issue by bkoster** [Stephan-S/FS19_AutoDrive#226]

**Comment by bkoster** [comment]
Load grass from silo does no work, the rest of fruit types works great,only no grass

**Comment by aviator64** [comment]
When you cycle through the fruit types, there are actually three entries for grass. They all say just "grass", but only one of them (on my system, the second one) will work to load from a silo.

The correct fruit type is actually grass_windrow. Yes, it would be helpful if the different sub-types were shown on the AD HUD :-)

**Comment by bkoster** [comment]
> When you cycle through the fruit types, there are actually three entries for grass. They all say just "grass", but only one of them (on my system, the second one) will work to load from a silo.
> 
> The correct fruit type is actually grass_windrow. Yes, it would be helpful if the different sub-types were shown on the AD HUD :-)

Not by me only 1 grass and iT wont load by al my maps

**Comment by aviator64** [comment]
The three "grass" entries are all next to each other in the AD HUD. If you click to advance to the next fruit, do you notice that it takes three clicks before it changes to "hay"?

Can you manually load grass from the silo into the same trailer?

**Comment by bkoster** [comment]
> The three "grass" entries are all next to each other in the AD HUD. If you click to advance to the next fruit, do you notice that it takes three clicks before it changes to "hay"?
> 
> Can you manually load grass from the silo into the same trailer?

Manualy no problem but i have only 1 grass

**Comment by Stephan-S** [comment]
Hey,
i used a filter to remove two of the three grass entries. I will have to adjust this filter in the next release.

**Comment by bkoster** [comment]
Problem solied with last update
Thank you for the update
