### ISSUE TITLE
Problem mit Big X

### ISSUE THREAD

**Issue by seeske123** [Stephan-S/FS19_AutoDrive#227]
Die Abfahrer erkant nicht die Big X oder ein andere Häcksler. Bleibt in modus " Warte auf Drescher" Forher hat es geklapt. Sonst ein tolles Program. Love it. Gr Hans

**Comment by seeske123** [comment]
Big X war CP Abfahrer AD

**Comment by Mannie313** [comment]
Der Häcksler hat keinen Bunker deshalb erkennt AD ihn nicht.

MFG Mannie313

**Comment by seeske123** [comment]
trigger von CP ist dasz Rohr ausgefaren ist. Hat nichts mit Bunker zu tun. AD abfahrer reagiert nur aud das Rohr. Und Rohr von Hacksler ist immer ausgefahren. CP mit Cp funkioniert. Nur teuer fur die Verschigerunf von Bauer.

**Comment by Mannie313** [comment]
Schau mal bei geschlossen #83  an.

**Comment by seeske123** [comment]
Danke Mannie

**Comment by Bigdaddy-KP** [comment]
Nutze doch einfach einen Häcksler mit Tank dann geht es z.b. den vom Yogi

**Comment by seeske123** [comment]
Danke Bigdaddy

**Comment by Opa-Andre** [comment]
Ich nutze das je nach Feld / Größe wie folgt:

1. AD Abfahrer am Feldrand, welche aber nicht als "Drescher abfahren" eingerichtet sind, sondern einen normalen "Be-/Entladen" Kurs nutzen.
2. Häcksler 
3. Entweder einen passendes Überladewagen-Gespann, oder die transportable Überladestation von modding-welt.com sowie normales Transportgespann zum Abtanken der Häcksler / Drescher.
2. und 3. werden von CP gesteuert. Somit befüllt das Transportgespann entweder die Überladestation, oder der ÜLW befüllt die am Feldrand stehenden AD Transportgespanne direkt (mittels Pause- / Haltepunkt). Die AD Gespanne fahren die Ernte ab und die ÜLW Gespanne entladen den Drescher / Häcksler.
