### ISSUE TITLE
Abfahrer Feldausfahrt hinter Start

### ISSUE THREAD

**Issue by SledgeHammer75** [Stephan-S/FS19_AutoDrive#228]
Die Einstellung Abfahrer "Feldausfahrt hinter Start" hat bei mir noch nie wirklich funktioniert. Der Abfahrer kommt sich immer mit anderen wartenden Abfahrern ins Gehege. 

Kannst Du die Anfahrroute für die Feldausfahrt nochmal überarbeiten?

**Comment by SledgeHammer75** [comment]
Screenshot

**Comment by Stephan-S** [comment]
Hey, probier die Wegpunkte nach dem Ziel/Start etwas früher und schärfer abbiegen zu lassen.
Bei dem Screenshot ist das Problem, dass er die Wegpunkte anpeilt, die quasi den gleichen Winkel haben.

Ich hoffe du verstehst wie ich es meine :-)

Er probiert immer den Winkel kurz vorm Ziel anzupassen, daher stößt er in diesem Fall trotzdem noch mit den wartenden Fahrern an Probleme.
Wenn die 3 oder 4 nächsten Wegpunkte direkt in eine Kurve führen, sieht das besser aus.

**Comment by SledgeHammer75** [comment]
Stimmt. Ich habe jetzt nach der Startposition noch 2 gerade Teile und gehe dann wieder Richtung Weg. Jetzt funktioniert es einwandfrei. Danke.
