### ISSUE TITLE
Editor und in beide Richtungen befahrbare Strecken

### ISSUE THREAD

**Issue by stueja** [Stephan-S/FS19_AutoDrive#229]
Ich habe gerade versucht, zwei violette (in beide Richtungen befahrbare) Routenstücke mit der Editor-/Verbinden-Funktion zu verbinden. Ich konnte sie immer nur mit einem grünen Pfeil verbinden, was die Route vermutlich einseitig befahrbar macht. 
Wie kann ich zwei in beide Richtungen befahrbare Routenstücke so miteinander verbinden, daß sie in beide Richtungen befahrbar bleiben?

**Comment by haamic** [comment]
Einfach nochmal entgegengesetzt verbinden. Also die grüne pfeilspitze markieren (roter Strich) und zum Ende des Pfeiles verbinden. Dann wird's violett

**Comment by haamic** [comment]
Bezieht sich auf den Editor im mod selbst. Ob das im separaten Editor dort auch so geht, weiß ich nicht.

**Comment by stueja** [comment]
Kreuzbirnbaumhollerstaude, da wäre ich nie draufgekommen. Tausend Dank, das probiere ich gleich.
