### ISSUE TITLE
AD Editor

### ISSUE THREAD

**Issue by RedOhne** [Stephan-S/FS19_AutoDrive#23]
HI Stephan,

ich wollte heute mal den Editor, der auch im Git ist testen. Nur leider zeigt er für die Karte nur einen Balken. Wenn ich deine PNGs richtig sehe, sind es ja exports der PDA DDS Karte, korrekt? Welche Größe müssen diese haben und welche Eigenschaften?

Kannst du dazu ggf. ein wenig Input liefern?

Gruß
Tim

**Comment by Stephan-S** [comment]
Servus,

ich habe es in einerm vorigen Issue schon mal erwähnt, das der Editor derzeit nicht kompatibel mit den aktuellen config Files ist. Da muss ich noch irgendwann das neue Kursformat einpflegen, wozu ich momentan einfach nicht komme.

Aber ja, die Map ist prinzipiell einfach die konvertierte DDS Version der PDA. Hat also die selben Dimensionen. 2048x2048 wenn ich es richtig im Kopf habe.

Viele Grüße,
Stephan

**Comment by RedOhne** [comment]
Hi Stephan, 

sorry. Hatte die alten Issues nicht durchgeschaut. Ich schließe dann diesen wieder und warte einfach auf ein update des anderen Issues.

Gruß TIm
