### ISSUE TITLE
Probleme mit den Kursen

### ISSUE THREAD

**Issue by RudiBergfeld1** [Stephan-S/FS19_AutoDrive#230]

**Comment by RudiBergfeld1** [comment]
ich habe das Problem das mir dass Spiel abstürst  wenn ich einen neuen Kurs erstellen möchte auch ohne mods Was mache ich falsch

**Comment by Stephan-S** [comment]
Hi,

kannst du mir bitte ein log file hier hochladen, damit ich sehe was schief läuft?

Vielen Dank!

**Comment by RudiBergfeld1** [comment]
[log.txt](https://github.com/Stephan-S/FS19_AutoDrive/files/3302117/log.txt)
meine log bei der der Alten Version geht es

**Comment by RudiBergfeld1** [comment]
Version 1.0.1.9

**Comment by Stephan-S** [comment]
hey,
in der log wird kein Fehler geworfen und 2 Sekunden nach Laden des Spiels wieder ausgeschaltet.
Das ist doch sicher nicht was du mir schicken möchtest oder :-)
Ich brauche das log file, nach dem ein Fehler aufgetreten ist.

**Comment by RudiBergfeld1** [comment]
ich würde dir gerne mehr schicken aber Auto drive bringt das Spiel sofort zum Abstürzen mehr ist leider nicht möglich

**Comment by RudiBergfeld1** [comment]
[log.txt](https://github.com/Stephan-S/FS19_AutoDrive/files/3303112/log.txt)
Ich habe den Fehler noch einmal Provoziert er tritt auf sobald ich AD den Editor  auf Aufname stelle und einen Kurs erstellen möchte  auch ohne Mods und auf anderen  Maps

**Comment by Stephan-S** [comment]
Hey, hast du das Problem immer noch? Ich habe dein Issue leider aus den Augen verloren, aber ich konnte es weder reproduzieren, noch hat ein andere User etwas vergleichbares gemeldet. Ich mache hier erstmal zu. Wenn das Problem noch besteht, mach wieder auf und schick mir mal ein komplettes Savegame bitte. :-)
