### ISSUE TITLE
Problemchen mit der Fruchtumfahrung

### ISSUE THREAD

**Issue by Mannie313** [Stephan-S/FS19_AutoDrive#231]
Hallo @Stephan-S 

Ich habe heute fünf mal den Ad Abfahrer neu einstellen müssen und zwar bekomme ich folgende meldung.

Going into fallback mode - no fruit free path found in reasonable time
Stop searching - no path found in reasonable time
Autodrive hat ein Problem beim Initialisieren festgestellt

Der helfer kann auch von der anderen seite ans feld fahren.

Kannst du mir da vielleicht helfen.

MFG Mannie313

**Comment by Stephan-S** [comment]
Hallo Mannie,

ich kann das Ganze am Besten bearbeiten, wenn du mir ein Savegame hochladen kannst, mit deinem Stand **bevor** das Problem auftritt. 
Sprich alles soweit auf dem Feld stehend, fertig eingestellt und ich muss nur noch den Fahrer anstellen und auf die Fehlermeldung warten.

Das wäre super. Jedes hochgeladene Savegame hilft mir dabei die Pfadfindung zu verbessern.
Ich kann leider bei weitem nicht alle möglichen Szenarien testen, daher sind User savegames hier absolut notwendig!

Vielen Dank und viele Grüße,
Stephan

**Comment by Mannie313** [comment]
ok mus ich dir dann mal schicken wen es wieder passiert. Spiele die umgebaute Dondiegomap und meine eigenen modpacks. das größte hat 1,2 gb. versuche es aber mal mit den originalen fahrzeugen und schick dir dann alles zu. 

MFG Mannie313

**Comment by Gariot** [comment]
Also bei mir kommt das Problem auch hin und wieder vor. Ich kann es leider ueberhaupt nicht reproduzieren, aber es passiert meistens wenn er vorher keinen weg zum drescher gefunden hat (also mit frucht umfahren) und dann halt das "backup" startet und durch die frucht fahren wuerde. Dann schaltet er sich allerdings mit der Meldung ab das er keinen weg finden wuerde.

Ist schon sehr merkwuerdig weil AD seinen weg eigentlich ziehmlich gut findet, selbst mit hindernissen. Siehe dazu mein verlinktes Video ;) [https://www.youtube.com/watch?v=9aeGrTbPjFo](url)

Ich kann nur mutmaßen das beim Drescher in der ungefaehren naehe zu viele dinge stehen wie Baeume usw so das AD einfach aufgibt.

**Comment by Stephan-S** [comment]
Hier hat sich viel geändert in letzter Zeit. Ich mache hier mal der Übersicht halber zu :-)
