### ISSUE TITLE
Mal Danke sagen! und vl ein paar Wünsche ;)

### ISSUE THREAD

**Issue by koppi99** [Stephan-S/FS19_AutoDrive#232]
hi Stephan, 

zu aller erst einmal Danke für den tollen Mod! habe den seit LS17 in gebrauch, jedoch ist Autodrive auf dem LS19 einfach nur TOP! Bin selbst modder (Seit LS19) (animals Hud, Animals Clean 100%, Field Data, Schaufel usw. ) jedoch ist dein Autodrive MOD einfach mächtig! 

Was ich mir wünsche (falls du es umsetzen kannst oder in einer testversion schon hast) wäre:

1.) wenn ein Fahrzeug den Standpunkt oder ein Ziel besetzt, dass dort der Name vom Fahrzeug oder Kipper usw. aufscheint. Da man kein weiteres Fahrzeug dorthin schicken kann da es ja blockiert ist. 

2. Irgend eine Vorschau wo die Standpunkte der Routen bzw die Map verläuft. CP hat es bei der Kursgenerierung. 

3. Eine Übersicht der Standpunkte bei der Auswahl der Ziele, oder eine Suche einbauen, oder Scrollbox. 

Wäre Toll wenn du was zum Testen hast oder so! Hilf dir gerne dabei! 

Gruß xDeekay :)

**Comment by Stephan-S** [comment]
Hey Deekay,

danke für die netten Worte :-)
Ich bereue es ja immer noch, dass ich den 17er Mod nie auf einen ähnlich guten Stand gebracht habe, wie jetzt den 19er.

Zu 1.) Hm, wo meinst du genau soll ich es anzeigen? In der Drop-down liste oder eine extra Liste für jedes Fahrzeug das gerade angekommen und noch nicht bewegt wurde?
So lange es kein Abladepunkt ist, kannst du ja trotzdem Fahrzeuge hinschicken, die sich dann eben dahinter einreihen (aber ja, ohne 'angekommen' Meldung).
Wenn du allgemein vermeiden willst, das ein Fahrzeug auf seinem Weg zu einem eigentlich anderen Ziel blockiert wird, kannst du vorm Berechnen der Kurse die Einstellung 'Zielpunkte vermeiden' und einen entsprechenden maximalen Umweg eingeben, dann werden Ziele auf 'Durchfahrtsstraßen' umfahren.

2.) Das klingt interessant. Vielleicht ja so etwas wie einblendbare maphotspots, die dann am Besten noch anwählbar sind.

3.) Was genau meinst du mit Scrollbox? Eine Dropdown-Liste ist ja schon seit ein paar Versionen integriert. Oder was stellst du dir vor?
Auch eine 'Suche' ist ja eingebaut gewesen in den früheren Versionen (ohne Dropdown liste). Da konnte man in die Labels klicken und lostippen und wie von Konsolen gewöhnt mit Tab vervollständigen :-)

Viele Grüße,
Stephan

**Comment by Nendel** [comment]
Zu Punkt 3 ich glaube er meint eine listbox das würde mir auch gefallen.

Könntest du einbauen, dass ich an Feld einen Punkt setze, dass dann der Helfer angeht.

Danke an der klasse Arbeit.

**Comment by koppi99** [comment]
hi @all, 
also ich hatte noch nicht die letzte version geladen. 

1.) das war so gemeint, ich hab eine halle mit 6 plätze wo ich hindurchfahren kann. dort hab ich überall die autodrive route durchgezogen. 
wenn ich jetzt an einem feld steh kann ich nicht sagen ob dort der platz frei ist oder nicht. da wäre toll eine übersicht ob was frei ist oder nicht. 

2. genau am besten das ganze streckennetz als miniatur das wäre mega cool 

3. hast du bei der letzten version gut gelöst!

**Comment by haamic** [comment]
Hallo,
Da hier gerade über Wünsche und Vorschläge geschrieben wird, hätte ich auch noch was. Meine Fahrzeuge haben alle eine Parkposition am Hof. Es wäre prima, wenn es im HUD einen extra Parkbutton gäbe, wo man das jeweilige Park-Ziel des Fahrzeugs hinterlegt und es sich dann einparkt wenn man drauf klickt. 
Und der Name des aktuellen Fahrzeugs, den man ja seit kurzem vergeben kann, könnte auch im HUD stehen. 
Ansonsten super Arbeit. Macht Riesen Spaß mit AD zu arbeiten.  Gruß Micha
