### ISSUE TITLE
Update 1.4

### ISSUE THREAD

**Issue by Gyffes** [Stephan-S/FS19_AutoDrive#235]
Grüße bin endlich wieder zu Hause und wollte nun alles Testen, 
und dachte mir ohh fein ein Update von Gains. Also Installiert gestartet. 
und wupp ein Ping von 9000+ mit konnte es auf ein Ping von 100-200 runter bekommen aller dings unspielbar. 

Also mal ins Log geschaut und eine neue Fehlermeldung gefunden. Direkt mal bei Giants nach geschaut im Forum in einem Post von Gaints wird hier der grund angegen.

> [Der garbage collector wurde mit dem Patch optimiert, wenn er auf Grund zu viel Speicherverbrauchs nicht mehr nach kommt,](https://forum.giants-software.com/viewtopic.php?f=874&t=147846&start=90)

Vielleicht kann dir die Fehlermeldung helfen. 
Vielen Dank. 

`2019-06-18 21:39 AD: Loading xml file from D:/home/sid_1063501/farmingSim_2019/profile/savegame2/AutoDrive_FS19_Dondiego_Map_config.xml 

2019-06-18 21:39 AD: Loaded Waypoints: 20953 

2019-06-18 21:39 D:/home/sid_1063501/farmingSim_2019/profile/mods/FS19_AutoDrive/lineDrawing/Line.i3d (0.32 ms) 

2019-06-18 21:39 WARNING: performing emergency garbage collection pass - memory went from 73540 KB to 163896 KB in less than one frame 

2019-06-18 21:39 INFO: usage is now 146968 KB; full GC took 176.292678ms 

2019-06-18 21:39 WARNING: performing emergency garbage collection pass - memory went from 73540 KB to 147880 KB in less than one frame 

2019-06-18 21:39 INFO: usage is now 147143 KB; full GC took 137.485387ms 

2019-06-18 21:39 WARNING: performing emergency garbage collection pass - memory went from 73540 KB to 147890 KB in less than one frame 

2019-06-18 21:39 INFO: usage is now 147297 KB; full GC took 131.513429ms 

2019-06-18 21:39 --> loaded AutoDrive version 1.0.3.1 (by Stephan) <--`

**Comment by Stephan-S** [comment]
Hey, thanks for showing me this.
Are there any more of these messages in the Log?

I am not surprised about it. Loading over 20000 waypoints from the config file requires a lot of string handling and temporary values which have to be cleaned up by the garbage collector.
So as long as there are no errors during the Game, I am not corncerned.

Are the pings definitely related to AutoDrive?

**Comment by Gyffes** [comment]
Moin danke für die schnelle Antwort. 
Ich antworte mal lieber in Deutsch, wenn ich das auf Englisch schreibe versteht keiner mehr was ;).

Der Ping wird von verschiedenen Mods verursacht. Größter verursacher aktuell wohl die Don Diego Map. Danach zur Zeit AD. Bei den beiden sind allerdings  hunderte  dieser Einträge. Nach der Deaktivierung von AD wurde der ping merklich besser. Aber auf Grund der Menge an Meldungen der Map diese immer noch unspielbar.
 Denke das einige ihre Mods Anpassen müssen.

Vielen Dank.

**Comment by Mannie313** [comment]
An der Don Diego Map liegt es nicht. Es liegt zur zeit nur am CP und AD.

Ich spiele auch die Don Diego Map und habe extra früchte eingebaut.

MFG Mannie313. 

PS: Als anhang mal meine spiele log. CP und AD sind nicht aktiv.

[log.txt](https://github.com/Stephan-S/FS19_AutoDrive/files/3307604/log.txt)

**Comment by Stephan-S** [comment]
Gyffes, lad mir doch bitte mal ein log file hoch, damit ich sehe woran es liegt.
@Mannie313 dein logfile ist wie immer völlig fehlerfrei und bringt mich so nicht weiter :-)

**Comment by Gyffes** [comment]
Hab bei mir mal aufgräumt alles raus geschmissen und die Sync mit Steam abgeschalten. Neuen Spielstand erstellt mit der DonDiego ohne weitere Mods bis auf die COMPOUND fehler läuft es. 

Schalte ich AD (Ohne Streckennetz) dazu. Kann ich meist nur alt+F4 nutzten. 

Desweiteren ist mir aufgefallen das meine MS akutell bei ca80-90 liegen vor Patch 1.4 waren sie bei 20-30. Da kann allerdings kein Mod was für  ist auch ohne Mods und Standartkarte so. :)

Dann bleibt mir erstmal nur AD auszulassen :-(

Kann aber nicht genug Danke sageen für die sonst so Tolle Mod :-)

**Comment by Gyffes** [comment]
da war ich wohl grad am schreiben als du geschrieben hast. 

Hier das Log vom Server (hab AD auch noch schnell auf V1.3.3 bebracht.)

Danke.
[log.txt](https://github.com/Stephan-S/FS19_AutoDrive/files/3310576/log.txt)

**Comment by Stephan-S** [comment]
hm in dem log ist kein Fehler zu erkennen. Ich weiß nicht was dort schief läuft.
Passiert gar nichts mehr wenn du das Spiel startest oder erst wenn du ein Fahrzeug mit AD startest?

**Comment by Gyffes** [comment]
Das es mehr oder minder einfriert ist nicht mehr, könnte an einer veralteten Version gelegene haben.
Aktuell kann ich keine Wegpunkte auswählen übeer das drodown menue nur über die Pfeile.

und die ms gehen weit über 100ms so das immer wieder stand bild ist und dann das ffahrzeuch nach vorne springt.

Kannst dich gern Einloggen Server Deutschland Sommys farm

**Comment by Gyffes** [comment]
Moin ich Teste gerade was.  Melde mich zum ergebniss. :)

**Comment by Gyffes** [comment]
Soo also es Lag an der Verbindung zum Server. Anscheinend Gab es wohl Routing Probleme. 
Auf jeden fall haben diesse den Ping von 80+ beim still stehen verursacht. 
Selber fahren ging aber wenn wenn AD noch berechnete bzw Daten hin und her schickte war vorbei mega legs.
Jetzt is der Ping wieder bei 20-30 und Tada es geht wieder.

Issue kann somit geschlossen werden Danke vielmals.
