### ISSUE TITLE
1 Wunsch und einen Tipp

### ISSUE THREAD

**Issue by gerrit0476** [Stephan-S/FS19_AutoDrive#236]
Hallo Stephan,

erstmal viele Dank für diesen tollen MOD. Im 17er habe ich ihn nicht genutzt aber im 19er gefällt er mir sehr gut! Nochmal vielen Dank.
2 Dinge würde ich gerne mal Fragen ob du das ändern oder einbauen kannst:

1. Wenn ich den Fahrer los schicke im dunkeln schaltet er die komplette Beleuchtung an. Kann man bei dem Modus " Zu einem Ziel fahren" nicht nur Normales Fahrlicht einschalten?

2. Kannst du es einbauen das man beim Modus "Anhänger befüllen und zu einem Ziel fahren" nicht ein Trigger erwartet sondern einfach auch z.B. am Feld stehen bleibt? (Gülle Zubringer)

Ich habe das getestet, er befüllt das Fass und fährt zum Feld Punkt aber dort bleibt er nicht stehen und wartet bis das Fass leer ist sondern fährt  langsam weiter.

Das wäre der Hammer.

Danke für deine Arbeit!
Grüße Gerrit

**Comment by gerrit0476** [comment]
@Stephan-S hast du schon einen neuen Modus installiert in der neuen Version? Da gibt es jetzt den Modus abholen. Ich konnte noch nicht testen aber ich glaube damit kann ich mir Waren(Gülle, Saatgut,..) zum Feld liefern lassen! Oder?

**Comment by Stephan-S** [comment]
Korrekt :-)

**Comment by Stephan-S** [comment]
Achso, zum Licht: Das wird vom Helfer automatisch eingeschaltet. Intern setze ich den Helfer als aktiv. Da ist es etwas 'fummelig', wenn ich hier das Licht nochmal überschreiben möchte. Also bleibt es erstmal so, sorry
