### ISSUE TITLE
Import courses from courseplay.

### ISSUE THREAD

**Issue by PromGames** [Stephan-S/FS19_AutoDrive#24]
Hello, it is my first time I am using your system and I would like to investigate with you the possibility of exporting courses from courseplay and import to auto drive. 

We are currently developing the courseplay editor and in addition to modify courses in game, we can also export courses as splines and we can also import splines as courses.

Could be a good feature if I can add compatibility among auto drive and courseplay in both directions.

I was testing with Holzermap  from my team lsmodcompany where we have a good set of courses of courseplay and I wanted to convert some of them in auto drive config. 

If you want to have access to the courseplayeditor and get splines from maps in course format, just llet me know and I will invite you to the group.

Prom

I

**Comment by RUGhost** [comment]
@PromGames can I test your course editor as a beta tester?

**Comment by Stephan-S** [comment]
Hey, sorry for getting back to you so late.
I would definitely like to see some compatibility between Courseplay and AutoDrive in the future.
In the meantime though, I am quite busy with polishing the exisiting feautures, adding other new features I would like to include in AutoDrive as well as hunting down bugs.
I haven't even managed to update the Course Editor to the current AutoDrive file format.
So unfortunately I do not see myself working on Courseplay course import/export functions in the next few weeks.

I will keep it in mind and as a long term feature request though.

But one thing to notice is that courseplay courses and the AutoDrive network are quite different in concept and I am not quite sure how the Courseplay courses could really be imported into an AutoDrive network. I feel like this could be more work than actually recording new ones.

Best regards,
Stephan

**Comment by Anonymous-any** [comment]
Hi :) CP twin AD what a cute dream... from my view point I will prefer CP can import AD splines but CP had they say somewhere that never go happen...
sad

**Comment by PromGames** [comment]
There is a new program published recently called OSM editor, open street map, is able to import, edit and export. Maybe is able also to import auto drive. The program is at GitHub.

**Comment by PromGames** [comment]
https://github.com/yankee42/courseplay-osm-converter

**Comment by Merlin110480** [comment]
Hi,

Wenn du es dir einfacher machen willst, ermögliche das importieren im OSM Format
Und mit einer export Funktion brauchst du den Editor nicht selbst bauen und hast mehr Zeit für andere Funktionen.

Hier hat das einer für Courseplay gemacht: 

https://github.com/yankee42/courseplay-osm-converter

gruß Christian

**Comment by Stephan-S** [comment]
Hey, der Editor ist schon gebaut und seit einem der letzten Commits auch wieder auf dem Stand der aktuellen config Datei. Feature-complete ist er noch nicht, aber ihr könnt ja gerne Issues aufmachen für alle gewünschten Funktionen :-)
