### ISSUE TITLE
AD editor not working right 

### ISSUE THREAD

**Issue by ploughedfieldman123** [Stephan-S/FS19_AutoDrive#241]
I have always just clicked on Load Config file and map and pda loads fine, but now it wont and if I say load map which is in same place as its always been, I just get a small part at top of screen image below

Hope someone can help as its always loaded up fine

**EDIT:  All working find again now as I copied 1 from a backup savegame   But what do you do if this happens again is there anyway we can fix problem ourselves** 

<a href="https://ibb.co/KNym7rT"><img src="https://i.ibb.co/hX8CHm3/2019-06-19-154320.jpg" alt="2019-06-19-154320" border="0"></a>

**Comment by Stephan-S** [comment]
I can only fix this if you would have send me the file which was not working right. If that happens again, please send me that file and reopen this issue. Thanks

**Comment by ploughedfieldman123** [comment]
> I can only fix this if you would have send me the file which was not working right. If that happens again, please send me that file and reopen this issue. Thanks

Hi 
  I did make a copy of the bad config file here it is. but is it not possible you can show us how to fix this if it happens again, as we have to wait until you come on each time.


http://www.filedropper.com/autodrivemarwellmanorfarmconfig_1
