### ISSUE TITLE
Neuberechnung bricht manchmal bei 99% ab

### ISSUE THREAD

**Issue by HawkPat** [Stephan-S/FS19_AutoDrive#243]
Mehrere tausend Log-Einträge (evtl. pro Wegpunkt einer?) mit diesem Error:

Error: Running LUA method 'update'.
.../My Games/FarmingSimulator2019/mods_multimap/FS19_AutoDrive/scripts/AutoDriveGraphHandling.lua:289: attempt to index local 'wp_ahead' (a nil value)

**Comment by Stephan-S** [comment]
Benutzt du eine aktuelle Version von AutoDrive? Der Fehler ist an der Stelle bereits behoben und abgefangen

**Comment by HawkPat** [comment]
Ich war auf 1.0.2.7
Mit der neuen Version scheint es den Fehler nicht mehr zu geben. Sorry, dass ich dadurch Deine Zeit gestohlen habe. Nichts für Ungut. Sehr gute Arbeit.
