### ISSUE TITLE
AD editor not working 

### ISSUE THREAD

**Issue by ploughedfieldman123** [Stephan-S/FS19_AutoDrive#245]
> I can only fix this if you would have send me the file which was not working right. If that happens again, please send me that file and reopen this issue. Thanks

Hi 
  I did make a copy of the bad config file here it is. but is it not possible you can show us how to fix this if it happens again, as we have to wait until you come on each time.

http://www.filedropper.com/autodrivemarwellmanorfarmconfig_1

**Comment by Stephan-S** [comment]
I generally try to incorporate the fix into the editor.
I will check your config and fix the editor if there is an error reading the file correctly.
