### ISSUE TITLE
Pathfinding issues

### ISSUE THREAD

**Issue by aviator64** [Stephan-S/FS19_AutoDrive#246]
When approaching a combine which has pulled back away from the fruit, the pathfinding often causes the tractor to collide with the combine. This happens consistently when approaching from a shallow angle in front of the combine.

![fsScreen_2019_06_20_07_52_26](https://user-images.githubusercontent.com/19857526/59876843-865e0280-939c-11e9-9c5d-5d53d91376a4.png)
![fsScreen_2019_06_20_07_52_35](https://user-images.githubusercontent.com/19857526/59876844-865e0280-939c-11e9-80ca-972080645d10.png)

**Comment by Stephan-S** [comment]
Hey,
yeah I just noticed that I am currently only checking for collission with the combine but not with the header.
Thanks for showing me that!
