### ISSUE TITLE
Autodrive Editor

### ISSUE THREAD

**Issue by gerrit0476** [Stephan-S/FS19_AutoDrive#248]
Hi Stephan,

gibt es irgendwo eine Anleitung wie ich den Editor nutzen kann?

Danke gruß Gerrit

**Comment by Martinnygaard** [comment]
I figured out how to connect two points as a one-way route - bou how do i  connect them as a two-way route?

**Comment by Knowen** [comment]
@Martinnygaard First you connect point A with point B. Now it is a one-way route. To make it a two-way route simple connect point B with point A.

@gerrit0476 Was klappt bei dir den nicht? Wobei brauchst du Hilfe?

**Comment by gerrit0476** [comment]
@Stephan-S es geht nicht um die Bedienung im Spiel sondern die Kurse extern mit Java bearbeiten. Ich habe den jetzt auch schon zum laufen gebracht. werde mal weiter testen. Denke ich komme zurecht. Danke
