### ISSUE TITLE
Connect a loop of a two-way route

### ISSUE THREAD

**Issue by Martinnygaard** [Stephan-S/FS19_AutoDrive#249]
Hi,

I am using AD together with CP, and it is brilliant - never have to be bothered with creating refill routes again.

Hovever, i figured that for it to work optimal, i need to record a loop arround the map to "catch" the tractor when CP releases it to AD. Then AD will go th the nearest waypoint, now being the loop i created.

BUT, when i have a almost complete loop, i cannot connect the two ends (only with a one-way section). 
I did this by driving around the field, and when i reached the beginning, i stopped recording and pressed "Select neighbouring point" ![image](https://user-images.githubusercontent.com/26490587/59976945-9871b800-95cb-11e9-925f-0132c8d3e091.png) then selected the beginnig WP ![image](https://user-images.githubusercontent.com/26490587/59976946-9d366c00-95cb-11e9-836c-1700168608f3.png) and finally clicked "toggle connection".
But this toggle was only "one-way" - if i pressed it again it dissapeares. 
I am almost certain that previoulsy i saw it toggle first "one-way", then "two-way" and then remove.

Am i missing something, or how should this be done?

Best regards,

![image](https://user-images.githubusercontent.com/26490587/59976875-8c392b00-95ca-11e9-8067-313dba0fa37c.png)

**Comment by Stephan-S** [comment]
Same answer as for the editor:
Do the same but now select the other point first (it now being the closest point) and select the first point as neighbor.
You always create (toggle) connections in a directed fashion, so from start to end point.

**Comment by Stephan-S** [comment]
So just to clarify some more. A two way street is now 'one' street with a property that it can be driven both ways, but actually two streets that point the other way.

**Comment by Martinnygaard** [comment]
That works like a charm! thanks for explainig.

What about this loop i create arround a field for making sure the tractor follows the correct path out of the fields, and not going through the woods. Is this the correct way of doing it?

If yes, A suggestion is that you can make som "field scanning" like CP, and make sure it doesnt exit the field unless it's next to the field destination?

**Comment by Stephan-S** [comment]
Hey,

it is certainly one way of solving the problem. Although one way streets should also suffice.
Certainly depends on your map. If you have many trees around the field, then you have to do something like that.

I already talked to the courseplay devs and suggested that they should only switch to AutoDrive after driving back to the starting point. That way you would always leave the field on the same location.

**Comment by Martinnygaard** [comment]
That sounds really great.
Another benefit of doing the circle around the field is that i can map
every entry and exit of the field, and therefor use the most sufficient
one, instead of driving all the way to the other side to exit.

Den tir. 25. jun. 2019 kl. 08.57 skrev Stephan Schlosser <
notifications@github.com>:
