### ISSUE TITLE
AI vehicle detection problem 

### ISSUE THREAD

**Issue by RUGhost** [Stephan-S/FS19_AutoDrive#25]
Autodrive driver can't detect ai vehicle. It detect stationary obstacles bt not running ai vehicle.

**Comment by Stephan-S** [comment]
Hey, do you mean ai driven cars or your own helpers?
You are right if you are talking about traffic cars, since this is not yet implemented.
Your helpers and other AutoDrive vehicles should be detected though. Did you have other experiences?
Best regards,
Stephan

**Comment by RUGhost** [comment]
My own helper can't detect ai driven vehicle. If any ai driven vehicle drive infront of my driver, my driver don't reduce the speed. As a result he hit the ai driven vehicle from behind.
