### ISSUE TITLE
Kurse Importieren

### ISSUE THREAD

**Issue by ArnoKister** [Stephan-S/FS19_AutoDrive#251]
Hallo,
erst mal vielen vielen Dank für den super mod. 
Ich habe gerade nur ein kleines Problem. 
Ich hab in meinem 2. Savegame Kurse auf der NFoG Version 1.8 eingefahren. Jetzt habe ich die Karte auf Version 1.9 geupdatet.  Die map fuktioniert. Doch leider sind alle meine Kurse weg.

Als ich die Kurse auf 1.8 eingefahren hab habe ich sie exportiert. Leider verstehe ich nicht wie ich sie wieder Importieren kann. 

Habe die Datei schon von 
AutoDrive_NF_Marsch_V1_8_oG_config
AutoDrive_NF_Marsch_V1_91_oG_config
umbenant. Die Exportierte Datei in den Importier Ordner Kopiert. 

Leider alle ohne Erfolg.

Vieleicht kannst du mir helfen. Danke schon mal und ein schönen Sonntag.
MfG
Arno

**Comment by koppi99** [comment]
hi! schau mal in den keybindings vom game dort steht AD import und Export als tastenkombination. 
glaub es ist strg+alt+1 auf dem ziffernblock 

Mfg 
xDeekay

**Comment by ArnoKister** [comment]
Hi koppi99. Danke für deine Antwort. 
Das hab ich vergessen mit rein zu schreiben. Das hab ich natürlich auch versucht. 
Leider funktioniert das bei mir auch nicht. Es werden im Spiel keine Ziele angezeigt. Auch nach mehrmaligem Drücken nicht. Aktualliesiert habe ich auch.
In der XML Datei steht alles schön sauber drin. Doch wie gesagt ich bekomme kein Ziel angezeigt. Wenn es vieleicht auch gefragt wird. Die Version 1.3.2 von Autodrive war Installiert. Jetzt versuche ich die neue 1.3.3 noch einmal. 

Lg Arno

**Comment by ArnoKister** [comment]
Ich benutze FS 19 Version 1.4.0.0 auf Steam. 

Auch mit AutoDrive Version 1.3.3 funktioniert leider nichts.

**Comment by koppi99** [comment]
probiere mal eine kleine strecke zu exportieren dann die files vergleichen. vl steht dort was anderes drinnen ;) gerade am Anfang vom file 

mfg

**Comment by ArnoKister** [comment]
Danke koppi99 du hast mir den Abend gerettet. Es funktioniert super. 

Ich wünsche dir noch einen schönen Abend.

**Comment by Gariot** [comment]
Hm, wie exportiert man ueberhaupt? In der steuerung steht STRG + ALT + Numpad2 aber wenn ich das mache tut sich nichts. Wo soll das denn dann erscheinen, im savegame bestimmt, oder? Da hab ich nichts gefunden. Waere nett wenn man mich da mal aufklaeren koennte :D

**Comment by koppi99** [comment]
gerne @arnokister ;) 
was war jetzt der unterschied? 😉 

PS spielst am server!? weil ich würde einen suchen

**Comment by koppi99** [comment]
@gariot im hud auf die diskette drücken. dann im dokumente Ordner under MyGames usw dort autdrive Export schauen. ist eine config datei

**Comment by Gariot** [comment]
Ohh.... 🤦‍♂ 

Danke dir @koppi99 - aus irgendeinen Grund hab ich das ding wohl permanent ausgeblendet bzw nicht wahrgenommen haha. Oh man

**Comment by koppi99** [comment]
gerne! kein problem ;)

**Comment by ArnoKister** [comment]
Den Unterschied kann ich nicht genau sagen. 
Auch warum es mit dem normalen Exportieren und Importieren nicht funktioniert hat.
Vermute da wirklich das Kartenupdate von 1.8 auf 1.9.
Ich habe einfach auf einem neuen savegame ein Kurs erstellt und diesen exportiert. Anschließend hab ich zwischen 
<waypoints> 
und 
</waypoints> die alten eingefügt.
genauso hab ich es zwischen 
<mapmarker>
und
 </mapmarker>
Als das in dem Neuen Savegame funktioniert hat. Habe ich die XML einfach in mein Original Savegame verschoben. 

Ich Spiele nicht auf einem Server. Hatte mir im 17 mal ein Eingerichtet doch das gab immer nur Ärger.

**Comment by ArnoKister** [comment]
Warum wurde beim Senden die komandozeilen weg gelassen?

**Comment by Gariot** [comment]
Mir ist gerade aufgefallen das STRG - ALT - Numpad 1 erst funktioniert wenn man kurz vorher exportiert hat. Vorher tut die tastenkombi nichts.

Ansonsten ist der weg wie schon beschrieben. Bei einem map update einfach ein neuen spielstand machen, eine kurze strecke einfahren, speichern und exportieren. Dann in der alten export datei, also in der vorgaenger version, alles zwischen "waypoints" und "mapmarker" kopieren und in die datei von der neuen mapversion an die selbe stelle kopieren bzw ueberschreiben. Dann einfach im spiel kurz im "richtigen" spielstand exportieren und wieder importieren, dann sollten alle alten strecken wieder da sein. Aber vergesst nicht immer eine sicherungskopie eurer strecken irgendwo zu machen.


Was man aber vermutlich auch machen kann, hab ich aber nicht getestet, ist folgendes. Man kann vermutlich auch einfach in der exportierten Datei, also wo alle funktionierenden wegpunkte usw sind, einfach:
`<NF_Marsch_V1_91_oG>`
und
`</NF_Marsch_V1_91_oG>`
in folgendes aendern:
`<NF_Marsch_V2_0_oG>`
und
`<NF_Marsch_V2_0_oG>`

Ausserdem muss, oder sollte, natuerlich der Dateiname entsprechend angepasst werden. Wenn man die Datei dann in den Import ordner packt muesste das eigentlich auch funktionieren. Aber das ist jetzt wie gesagt nur eine vermutung, ich habs nicht selbst getestet. MACHT IMMER NEN BACKUP! :D

**Comment by Stephan-S** [comment]
Gut das ihr euch hier in meiner Abwesenheit selber helfen konntet :-)

Deinen angemerkten Fix. Also die Anpassung des Mapnamens in der Datei und im Dateinamen ist hier der einzige Weg die Kurspunkte mit in die neue/aktualisierte Map zu nehmen.
Wenn man ein Backup gemacht hat, kann man das aber auch direkt in der config Datei innerhalb des Savegames vornehmen.

Wenn ich es noch einmal neu machen würde, würde ich es ohne Mapnamen in der config Datei lösen, aber dafür ist es jetzt zu spät :D

**Comment by Opa-Andre** [comment]
> Mir ist gerade aufgefallen das STRG - ALT - Numpad 1 erst funktioniert wenn man kurz vorher exportiert hat. Vorher tut die tastenkombi nichts.

@Gariot : Doch das geht - wichtig ist nur, dass man vor Drücken der Import-Tastenkombi den Editier-Modus aktiviert hat. Im normalen "Benutzermodus" kommt da nichts - ist mir auch schon ein paar Mal passiert.
