### ISSUE TITLE
Im Fahrzeug eingesperrt

### ISSUE THREAD

**Issue by Gariot** [Stephan-S/FS19_AutoDrive#252]
Hi,

ich wurde eben, vermutlich von AutoDrive, in meinem Fahrzeug eingesperrt. Ich konnte nichts mehr machen. Weder aussteigen, ESC nutzen oder irgendetwas anderes. Nicht mal meine Maus funktionierte.

Es passierte als ich AD losgeschickt hab. Ab da war ich gefangen. Ich konnte AD nicht mal mit dem hotkey ausschalten. Ich bin nur rausgekommen weil ich auf irgendwelche Tasten gehaemmert hab. Ich haenge natuerlich den Log an, aber die Console hat immer folgendes rausgeschmissen wenn ich z.b. Tab gedrueckt hab:

> F:/Users/Gariot/Documents/My Games/FarmingSimulator2019/mods/FS19_AutoDrive/scripts/AutoDriveKeyEvents.lua:118: attempt to index a nil value

[log.txt](https://github.com/Stephan-S/FS19_AutoDrive/files/3318598/log.txt)

**Comment by Stephan-S** [comment]
Danke für die Meldung.
Du hast scheinbar einen Rechtsklick auf den Zielnamen der Abladestelle gemacht.
Dann kannst du einen Namen eingeben und mit der Return Taste bestätigen.
Alle anderen eingaben sind in dieser Zeit blockiert.

Da sollte ich nochmal drüber schauen und vermutlich ein 'echtes' Eingabefenster aufrufen, wie auch beim Namen vergeben der Fahrer derzeit genutzt wird.

**Comment by haamic** [comment]
Hallo,
ich war auch mal wieder eingesperrt. Ich wollte eine "Abholen/ Abliefern" Fahrt starten. dann ging nichts mehr, kein Tasteneingabe und das "F1-Menü" war auch weg. Nebenbei liefen noch 2 Feldarbeiten per CP.
Es war kein Blockieren der Eingabe im AD-HUD, wie oben beschrieben. Ich konnte mittels AD-Maus aber dennoch das Fahrzeug bewegen, nur eben weder aus-/umsteigen.
Einzig, der Aufruf der Console mit der Taste "^" ging und ich konnte mich befreien.
Erst beendete ich die Arbeiten von CP mittels "cpStoppAll". Ob das notwendig war weiss ich nicht, denn nach dem Befehl "gsReloadVehicle" funktionierte alles wieder. Das F1-Menü war wieder da und die Tasten taten das, was sie tun sollten.
Vielleicht hilft das anderen, die es auch mal erwischt. 
Ohne Consolenzugriff scheint es ausweglos zu sein und man kommt um einen Neustart von LS nicht herum. Wenn automatisches Speichern nicht aktiv war, dann ist das leider auch mit Verlust des Spielfortschritts verbunden.
Was genau nun zu dem Verhalten führte, weiss ich nicht. AD, CP oder beide....log.txt konnte ich nicht anschauen, die Datei war zu riesig, war nicht zu öffnen, hab sie gelöscht.

**Comment by Opa-Andre** [comment]
Den "Fehler" - naja, eigentlich ist es kein richtiger Fehler, kann man leicht beheben, indem man einfach die Enter Taste drückt... damit schließt Du die leere "Sucheingabe" ab. Anschließend nochmal prüfen, ob die Ziele korrekt sind und du kannst weiterspielen...

**Comment by Gariot** [comment]
Das Problem ist schlicht das man kaum bis gar nicht sieht oder bemerkt das da irgendeine Eingabe stattfinden soll ;) Es ist, wie so vieles, auch nirgendwo dokumentiert was AD eigentlich so wirklich kann und wie es funktioniert. Ich habe auch erst hier gelernt das man fahrer wohl namen geben kann. Darum kommt man auch nicht drauf das man gerade vielleicht irgendeine Eingabe gestartet hat ;)

Naja, ist ja auch egal nu.

**Comment by Opa-Andre** [comment]
Wenn der "Fehler" auftritt, kann man das dadurch erkennen, das die Bezeichnung eines der Strecken- / Zielpunkte für die geplante Fahrt "leer" ist, also dort kein Text steht. Drückt man dann die Enter Taste, dann steht wieder ein Name drin und man kann weitermachen... Ich weiss, ist nicht ideal, aber es funktioniert. :)
