### ISSUE TITLE
Need a Help

### ISSUE THREAD

**Issue by RUGhost** [Stephan-S/FS19_AutoDrive#253]
I don't know how to open pulldown menu for filltype selection. Can someone tell me how to open  pulldown menu for filltype selection?

**Comment by jala15** [comment]
You have to click the right part of the second row:

![Autodrive fruit](https://user-images.githubusercontent.com/52028079/60007935-7895cf00-9673-11e9-9057-71a7d79e4186.jpg)

**Comment by RUGhost** [comment]
Thanks a lot
