### ISSUE TITLE
AD und Multimap AD erkent keine Baumen und andere Objecten in Multimap. Problem AD oder Multimap.

### ISSUE THREAD

**Issue by seeske123** [Stephan-S/FS19_AutoDrive#254]

**Comment by Stephan-S** [comment]
Muss ich mir mal genauer ansehen.
Nutzt du die aktuellste Version von AutoDrive?

Du meinst sicher im Drescher abladen Modus oder?
Dann liegt es vermutlich an der Map. Gut möglich das die Kollisionsmasken nicht stimmen bzw. nicht zu denen passen, die AutoDrive überprüft.

**Comment by seeske123** [comment]
Moin Stephan. Stimt was Du sagts. Ist im Drescher abladen. Suche mal ein andere weg von Feld weg zukommen. Danke für Deine tolle Arbeit.
Hab immer die aktuellste Version.
Hans
