### ISSUE TITLE
AD kann Ropa 2 + Tiger sowie Holmer nicht Lenken.

### ISSUE THREAD

**Issue by Gyffes** [Stephan-S/FS19_AutoDrive#256]
Grüße mir ist soeben aufgefallen das AD den Ropa Phanter 2 und Tiger 6XL sowie den Holmer Terra Dos nicht Lenken kann, Er fährt immer geradeaus. 
Multiplayer 
Patch 1.4 
keine Fehlermeldung im Log. 
Andere Fahrzeuge funktionieren.

Einen schönen Abend noch.

**Comment by Opa-Andre** [comment]
Kann ich zumindest beim Ropa Panther 2 nicht bestätigen - bei mir fährt der ganz normal auch um die Kurven, wenn ich ihn zum Feld schicke. Die anderen beiden verwende ich nicht. Kann es vielleicht sein, dass Du MOD-Versionen dieser Fahrzeuge nutzt? Der Panther 2 wurde z. Bsp. im Patch 1.4 von Giants verändert, worauf ich mir meine MOD-Version ebenfalls auf die Verwendung der neuen i3d angepaßt habe. Könnte also sein, dass es an einer veralteten Mod-Version des Fahrzeuges liegt, ist aber nur eine Vermutung.

**Comment by Gyffes** [comment]
Hi Andre dankee für deine Antwort.  Hatte ich mir auch gedacht und extra mir die Originalfahrzeuge gekauft. 
Leider gab es auch da dieses Problem. Was ich noch veersuchen kann die mods abzuschalten und dann die original Fahrzeuge zu nutzten Vielleicht. Grätschen die Mods ja doch ihrgendwo zwischen.

**Comment by Opa-Andre** [comment]
Schick mal trotzdem Deine Logdatei - ich habe gestern bei mir noch auf der Multimap2019 mit 4 Panther2 ein großes Feld abgearbeitet und bin dazu mit Autodrive ohne Probleme vom Hof zum Feld und auch zurück gefahren. Dein Savegame habe ich nicht ausprobiert, da fehlt noch eine Beschreibung, was Du genau machen willst (wohin fahren etc.)

**Comment by Gyffes** [comment]
Das savegame ist ein frisches Spiel auf ravenport nur 1 Fahrzeug am Shop hab wahllos ein Ziel im AD genommen nur zum test. 
Log steht zwar nichts drin postete ich aber sobald ich zuhause bin.

Danke.

**Comment by Gyffes** [comment]
So hier noch die Log :-)

Danke Euch

[log.txt](https://github.com/Stephan-S/FS19_AutoDrive/files/3374202/log.txt)

**Comment by Opa-Andre** [comment]
Ehrlich, inzwischen bin ich ratlos. Ich verwende auch die Stream Version 1.4 von Giants wie Du und benutze noch AD Version 1.0.3.4 (Du hast inzwischen lt. Log die 1.0.3.5), aber den Fehler ja schon vorher gehabt. Hast Du wirklich mal nur mit AD getestet, ohne weitere Mods? Und mit "ohne weitere Mods" meinte ich nicht nur das deaktivieren, sondern für einen neuen Testspielstand mal wirklich aus dem Modordner herausnehmen. Sehe da z. Bsp. einige Maps bei Dir drin, welche man ja nicht wirklich deaktivieren kann... Nur AD rein, neues Savegame starten, AD in den Editormodus schalten, mittels CRTL+Alt+1 (oder selbst definierter Key-Kombi) ggf. die Standard Strecken für die Map importieren, sodass Du sie sehen kannst, neu Berechnen lassen, Ziel auswählen und starten...

**Comment by Opa-Andre** [comment]
Ehrlich, inzwischen bin ich ratlos. Ich verwende auch die Stream Version 1.4 von Giants wie Du und benutze noch AD Version 1.0.3.4 (Du hast inzwischen lt. Log die 1.0.3.5), aber den Fehler ja schon vorher gehabt. Hast Du wirklich mal nur mit AD getestet, ohne weitere Mods? Und mit "ohne weitere Mods" meinte ich nicht nur das deaktivieren, sondern für einen neuen Testspielstand mal wirklich aus dem Modordner herausnehmen. Sehe da z. Bsp. einige Maps bei Dir drin, welche man ja nicht wirklich deaktivieren kann... Nur AD rein, neues Savegame starten, AD in den Editormodus schalten, mittels CRTL+Alt+1 (oder selbst definierter Key-Kombi) ggf. die Standard Strecken für die Map importieren, sodass Du sie sehen kannst, neu Berechnen lassen, Ziel auswählen und starten...

**Comment by Gyffes** [comment]
soo da bin ich wieder. :)

Jup habe nur AD getestet. Habe dazu den Mod ordnere umbenannte. 
Sowie einen neuen Modordner erstellt. In diesem ist auch nur AD drin. 
Danach habe ich das Spiel gestartet und im SP Modus ein neues Game erstellt. 
Nur eins diesere Fahrzeuge gekauft und ihn dann per AD losgeschickt. 
Selbe ergebniss wie bisher.
Weis auch nicht woran es liegt. Aber Danke für deine  mühen. 
Habe eine Lösung gefunden diese ist nicht schön Funktioniert aber. 
Meine Lösung ist.:

Ich fahre die Betroffenen Fahrzeuge per Hand dahin wohin sie sollen. :-)

[log.txt](https://github.com/Stephan-S/FS19_AutoDrive/files/3387697/log.txt)
