### ISSUE TITLE
Setting up autodrive for my farm

### ISSUE THREAD

**Issue by gigilal** [Stephan-S/FS19_AutoDrive#257]
Hey, I am setting up all the lines to my farm and silo and so on, but the otherfamrs can use my waypoints ? And if they can see and use mine and create their own it will just be a mess ?

Great mod, love it 100%. and thank you.

**Comment by Roby1164** [comment]
In MultiPlayer, everyone sees everything and can use everything.

**Comment by gigilal** [comment]
Will it always stay like this? Or can it be changed?

**Comment by Roby1164** [comment]
I think it will remain like this, I don't think it is possible to separate the tracks, then it is better all in common, less waypoints to calculate, etc. For the go points, such as silos etc .. just put the name of the owner, to identify them.
