### ISSUE TITLE
Serverwarnung: xml too big

### ISSUE THREAD

**Issue by Gariot** [Stephan-S/FS19_AutoDrive#26]
Moin,

Habe heute mal AutoDrive ausprobiert und mein Server hat mir 2 fehler ausgeschmissen bezueglich xml files. Wobei die zweite ggf. nur auftritt weil es neu installiert wurde. Dazu mach ich ggf. dann einen neuen Report.

Mein Server meldet jedenfalls:
XML file 'AutoDrive_Ravenport_init_config.xml' is too big. Size 0.34 MB (max. 0.25 MB) 

Was nebenbei gesagt etwas komisch ist weil ich nicht mal auf Ravenport spiele :D Aber naja. Warscheinlich einfach zu viele mitgelieferte Strecken auf der Map? Vielleicht kann man das ja auslagern um die xml klein zu halten.

Version  	1.0.0.4

**Comment by Stephan-S** [comment]
Servus,
das ist nur eine Warning und kein Fehler in der Mod, und die Strecken werde ich auf jeden Fall in der zip Datei belassen. Damit muss man als Server Admin in dem Fall leben oder warten ob Giants die vermutlich willkürlich gesetze Grenze von 0,25MB mal ändert. So oder so, keine Bearbeitung von mir an der Stelle :-)
