### ISSUE TITLE
Erfordernis Export

### ISSUE THREAD

**Issue by Th301** [Stephan-S/FS19_AutoDrive#260]
Hallo Stephan,

Autodrive ist eine richtig coole Sache!! Ein Straßen- und Locationnetz ist absolut top und effektiv.

Meine Frage ist, wann ein Export der Strecken erforderlich ist? Jedes Mal zu einem Versionsupdate von AutoDrive? Oder nur wenn man ein Update der Map durchführt?

Beste Grüße
Theo

**Comment by JLConradie** [comment]
Th301
Hello.. In Edit mode of your AutoDrive Hud you will find a button with and very old storage disk "Stiffy/Floppy" disc picture.  Press on it.. What it does is, it makes a backup of your current game AutoDrive routes. Look in your documents farmsimulator19 folder and you will find an folder of autodrive.. open it.. that is where all your backup files are.  Now if you start a new map with previously recorded AutoDrive routes, save the map and exit the game totally..  Then you simply copy that map file "Auto Drive file" into your new game map folder.. Start the game and open the map, and see.. all your routes are back from the old to the new. Hope it helps.
Regards


Th301
Hallo .. Im Bearbeitungsmodus Ihres AutoDrive Hud finden Sie eine Schaltfläche mit einem sehr alten Speicherdiskettenbild "Stiffy / Floppy". Drücken Sie darauf. Es erstellt eine Sicherungskopie Ihrer aktuellen AutoDrive-Routen. Suchen Sie in Ihrem Ordner "documents farmsimulator19" nach einem Ordner mit dem Namen "autodrive". Öffnen Sie ihn. Dort befinden sich alle Ihre Sicherungsdateien. Wenn Sie nun eine neue Karte mit zuvor aufgezeichneten AutoDrive-Routen starten, speichern Sie die Karte und beenden Sie das Spiel vollständig. Dann kopieren Sie einfach die Kartendatei "Auto Drive-Datei" in Ihren neuen Kartenordner. Starten Sie das Spiel und öffnen Sie die Karte , und siehe .. alle Ihre Routen sind zurück von der alten auf die neue. Ich hoffe es hilft.
Grüße

**Comment by Opa-Andre** [comment]
@Th301 Also ein Export ist eigentlich "nie" erforderlich, aber dennoch ratsam - nicht nur bei Versionsupdate. 

Hintergrund: Beim Ändern / Erweitern des Streckennetzes wird diese Information mehr oder weniger "live" in Deinem Savegameordner abgelegt. Ein direktes Backup erfolgt nicht. Hast Du also hier eine größere Änderung gemacht, kann es also sein, das sich dabei auch mal ein Fehler eingeschlichen hat. Die ganzen Teile dann wieder herauszulöschen ist ziemlich zeitaufwendig. Auch kann es hin und wieder vorkommen, dass durch andere Mods sich FS verabschiedet und das Savegame nur noch "Müll" ist. Daher mache ich immer einen Export, sobald ich ein paar Änderungen am AD Streckennetz durchgeführt und festgestellt habe, dass das Ergebnis für mich passt. Beim Export legt AD dann eine aktuelle Kopie in den Export Ordner ab - und überschreibt damit das vorher bestehende "Backup". 

Tritt ein Fehler auf, dann diese Datei einfach in den Importordner kopieren und in einem neuen Savegame wieder importieren, bzw. die im Savegame vorhandene Datei löschen.. somit bist Du ziemlich schnell wieder auf dem aktuellen Stand. Der Export dauert ja auch nur einen Augenblick...

**Comment by Th301** [comment]
Moin @Opa-Andre, danke dir! So habe ich es auch gedacht, war aber nicht sicher ob ich etwas übersehen habe.

@JLConradie : Thx for your response. I think the translation lead to a wrong understanding of my question. I already understood, how it shall work. The question was regarding the necessity of using the Export-function.
