### ISSUE TITLE
Anfrage an NEUE Entwickler, da Stephan sich wohl leider zurückzieht :-(

### ISSUE THREAD

**Issue by haamic** [Stephan-S/FS19_AutoDrive#261]
Hallo,
Meine Fahrzeuge haben alle eine Parkposition am Hof. Es wäre prima, wenn es im HUD einen extra Parken-Button **"P"** gäbe.
Man könnte dort das jeweilige Park-Ziel des Fahrzeugs **fest** hinterlegen und das Fahrzeug dann parken lassen, wenn man drauf klickt.
Vielleicht ist das ja evtl. nicht so schwierig, den Button zu integrieren. 
Ich würde mich freuen. 
Und noch etwas, der Name des aktuellen Fahrzeugs, den man ja seit kurzem vergeben kann, könnte auch im HUD stehen. Das wäre noch eine gute Zusatzinfo.
Ansonsten super Arbeit, Stephan. Es macht Riesen Spaß mit AD zu arbeiten. 

Wurde beim Abfahrer /Drescher abtanken das zurücksetzen nach Leeren des Dreschers geändert? Er fährt jetzt nur noch **ganz wenig** zurück, was unweigerlich zum Zusammenstoss des Dreschern mit dem Abfahrer führt. Betrifft nur den Fall, wenn das Rohr in der Frucht steht und der Drescher vorher Platz für den Abfahrer geschaffen hat.
Gruß Micha

**Comment by Knowen** [comment]
Habe gestern Abend versucht Parkpositionen für meine Fahrzeuge zu hinterlegen. Ich checke wohl noch nicht ganz, wie man das genau machen muss. Also in welcher Reihenfolge die Knöpfe gedrückt werden müssen. Kannst du da kurz was zu schreiben? Danke!

**Comment by haamic** [comment]
Ich weiß nicht was du meinst. 
Es war nur eine Frage meinerseits, ob es möglich wäre eine extra Park-Funktion einzubauen. Also einen Button zu erstellen und mit einem festen Ziel zu versehen. Worüber man dann zb die Fahrzeuge "nach Hause" schicken kann, ohne erst in einer längeren Liste den Parkplatz zu wählen.

**Comment by Saarlonz** [comment]
Diese Funktion wurde mit dem Update gestern eingefügt, die Frage deines
Vorredners ging an Stephan.

haamic <notifications@github.com> schrieb am Fr., 9. Aug. 2019, 09:07:

**Comment by haamic** [comment]
Oh sorry das ist mir diese Info leider entgangen.

**Comment by Stephan-S** [comment]
Hey, ich hab ja extra einen Hilfetext eingebaut, der auftaucht wenn noch keine Parkposition definiert ist.
Der Knopf fürs Parken kann entweder mit der linke. Maustaste genutzt werden um ihn Parken zu schicken, oder mit der rechten Maustaste. Wenn du die rechte Maustaste nutzt legt er das aktuell angewählte Ziel als Parkposition fest und speichert das auch für dieses Fahrzeug dauerhaft ab. Ebenfalls mit Meldung auf dem Bildschirm :-)

Wenn es damit Probleme gibt, gerne wieder melden. Ich habe es nur auf die Schnelle testen können und dort hat es wie erwartet funktioniert :-)

Beste Grüße,
Stephan

**Comment by haamic** [comment]
Funktioniert prima mit dem Parken. Vielen Dank Stephan. 

Was ich noch fragen möchte...
Die Fabriken mit dem Global Company Script, die es seit kurzem gibt, verweigern das automatische Beladen (wird manuell mit R-Taste ausgelöst).
Weder AD noch CP funktionieren.
Gibts da eine vielleicht mal eine Lösung? 
An anderen triggern die mittels R beladen, da funktioniert es eigentlich ohne Probleme. 
Gruß Micha
