### ISSUE TITLE
Exit Strategie: Hinterm Start

### ISSUE THREAD

**Issue by Gariot** [Stephan-S/FS19_AutoDrive#262]
Hi,

ich habe heute mal die im Titel stehende exit Strategie getestet. Im groben funktioniert sie ganz gut, wenn aber das Fahrzeug nicht den besten Lenkeinschlag hat oder am Start ein Fahrzeug steht (z.b. weil man 2 abfahrer braucht) dann kann es passieren das der, der vom feld kommt in das wartende fahrzeug faehrt. Vielleicht wuerde es helfen wenn er etwas weiter hinter den start guckt und versucht dahin zu fahren?

Ich habe vorher die Strategie "Naechstgelegen" benutzt. Allerdings dauert es unter umstaenden sehr lange bis er sich entscheidet auf nahegelegene strecken zu fahren. Waerend er sich also entscheidet faehrt er dann gemuetlich gegen Haeuser, Baeume, in Graeben, Huegel hoch und bleibt dementsprechend natuerlich einfach haengen. :/ Allgemein hat er wohl ein paar probleme mit der erkennung von Baeumen bei der Routenplanung. Koennte aber natuerlich an der map liegen.

Also dann, hau rein.

Version: Aktuellste

**Comment by andreasthu** [comment]
du kannst ja an den neuralgischen punkten eigene routen für die Feldausfahrt anlegen, z.b. von jedem eck aus zur Strasse, oder bei grösseren feldern auch mittig.
lg
andreas

**Comment by sdl112** [comment]
Hierfür wäre evtl eine option "vor dem Startpunkt" hilfreich. Habe das selbe problem mit mehreren Abfahrern.

**Comment by andreasthu** [comment]
> Hierfür wäre evtl eine option "vor dem Startpunkt" hilfreich. Habe das selbe problem mit mehreren Abfahrern.

ist auch nicht sinnvoll, da der Abfahrer dann erst recht hinter dem zweiten abfahrer feststeckt.
lg
andreas

**Comment by sdl112** [comment]
Ok, dann verstehe ich evtl. die Definition von "hinter" und "vor" falsch. "Hinter" heist für mich in Fahrtrichtung "hinter" dem Startpunkt, oder sehe ich das falsch?

**Comment by andreasthu** [comment]
ja, ev ein definitionsproblem, hinter dem Startpunkt heißt wohl, die Punkte NACH dem Punkt in Fahrtrichtung gesehen, also in der Fahrtrichtung
man kann es leicht mit HINTER dem Traktor stehen verwechseln.
lg
andreas

**Comment by Gariot** [comment]
Ich hab das jetzt uebrigends mal so gemacht wie du vorgeschlagen hast, @andreasthu. Ich habe rund um "Problemfelder" eine route gefahren damit, wenn ich auf "Naechstgelegen" stelle, er diese nimmt und dann "sicher" sein ziel erreichen kann. Leider nimmt er die jedoch nicht, sondern irgendeine andere die er nicht erreichen kann (z.b. wegen starker steigung usw). Also ist das leider keine Loesung :) Eventuell liegt es daran das ich eingestellt habe das er die schnellste strecke bevorzugen soll. Muesste man nochmal testen.

**Comment by andreasthu** [comment]
@Gariot
kannst du mal ein Bild davon reinsetzen?
ja das mit den steigungen führt imer zu problemen.

ich hätte es so gemacht, bzw hab vor es so zu machen, bin auch erst am anfang von AD
![autodrive](https://user-images.githubusercontent.com/24860501/60589252-58fc5600-9d99-11e9-8dd1-97928c69c9de.png)
also entweder aussen rum (siehe links Feld1+2, Felsbrunn), oder von jeder ecke aus zu den Strassen wie bei feld3 rechts
wenn sie länger sind auch mittig eine Ausfahrt reinsetzen, wie bei Feld1 oben mitte zu sehen

lg
andreas

**Comment by haamic** [comment]
So in etwa mach ich das auch. 
Meist wo es möglich ist einen kompletten Ring um das Feld von dem es ins Straßennetz geht und zusätzlich von der Feldmitte diagonale Teilstücke zu den Ecken. Klappt bisher prima. LG Micha

**Comment by Gariot** [comment]
Ich muss das wie gesagt nochmal testen, aber wenn das bei euch funktioniert - was habt ihr denn bei "Schnellste Strecke bevorzugen" eingestellt? Ja oder Nein?

Im prinzip habe ich aehnliche Kurse eingefahren wie Andreas, einmal rund ums Feld rum halt. Es kann aber vorkommen das parallel, natuerlich in gewisser entfernung, eine weitere route verlaeuft, die aber so map bedingt nicht erreichbar ist. Sie waere auch NICHT die naechstgelegene Strecke, aber vermutlich die schnellste. Darum werde ich das wie gesagt nochmal testen muessen weil ich die vermutung habe das AD die naechstgelegene und schnellste strecke nimmt - vorrausgesetzt man hat "Ja" in der Option gesetzt.

**Comment by haamic** [comment]
Ich hab nächstgelegen und schnellste Strecke gewählt. Wie schon geschrieben hab ich einen "Rundkurs" in violett,also beidseitig befahrbar. Damit das Fahrzeug im schlechtesten Fall nicht eine komplette Runde ums Feld fahren muss, falls er sich schon in der Nähe der Ausfahrt befindet. Ich hab ich gute Erfahrung mit den zusätzlichen Diagonalen von der Feldmitte gemacht. Diese normal in grün von innen nach außen, im Rundkurs endend.

**Comment by Gariot** [comment]
Hm, hab jetzt mal die Option "Schnellste Strecke bevorzugen" auf Nein gesetzt. Trotzdem nimmt er zeitweise NICHT die naechstgelegenste Strecke wenn 2 strecken parallel laufen. Keine Ahnung was AD da macht.
