### ISSUE TITLE
Abfahren wenn < 50% (Sofort)

### ISSUE THREAD

**Issue by Gariot** [Stephan-S/FS19_AutoDrive#263]
Waere cool wenn man neben der % einstellung auch einfach "Sofort" einstellen koennte. Also tankt der abfahrer einmal ab und faehrt dann direkt weg.

**Comment by Stephan-S** [comment]
hm, was wäre dir lieber. Die Prozentzahlen bis meinetwegen 0% runterzuschrauben oder direkt nach der 50% ein 'Sofort'? Ich denke ich werde einfach kleinere Prozente erlauben, dann ist es gar kein Aufwand und du hast die gewünschte Funktion :-)
