### ISSUE TITLE
Hinweis,  Abholen/Abladen + neue Lademodus (Auffüllkurs)

### ISSUE THREAD

**Issue by haamic** [Stephan-S/FS19_AutoDrive#264]
Hallo Stephan und andere LS Spieler,
ich war heut schon am verzweifeln, hab einige Zeit verbracht den Fehler zu finden...
Ich hatte eine neue Karte gestartet, paar Strecken eingefahren, ein Silo gebaut ... usw... zwischendurch immer mal gespeichert und wollte nun testen, ob das mit dem Laden/Abladen funktioniert. Also Modus Abholen und Abladen gewählt, Start,Ziel und Frucht ausgewählt und Los gings....
Der Test ergab, das das Fahrzeug zwar die Strecke abfuhr, aber weder etwas geladen bzw. wieder abgeladen hat. Obwohl die Frucht im Silo drin war, die er holen sollte.
Bei meiner zuletzt bespielten Map funktionierte das super.
Testweise alte Map geladen...funktioniert wie gewollt.
Wieder die neue Map geladen, und siehe da, nun ging es auch.
Gab es mal irgendeinen Hinweis, das diese Modi erst nach Beenden des Spieles und neu Laden klappen? 
Frage an den Entwickler, wie kann das sein? Was ist für AD anders, wenn man den Spielstand neu lädt, als direkt im laufenden Spiel zu Testen?
Ich habe auch andere Maps probiert, selber Effekt.
Silo gebaut und einen Kurs drum rum mit Lade- und Entladepunkt, Wege berechnet, Fahrzeug gestartet....dreht zwar Kreise durch Lade und Entladepunkt, aber mehr auch nicht, erst nach dem neuladen, lädt und entlädt er.
Gruss Micha

**Comment by Opa-Andre** [comment]
@haamic: In einem anderen Issue hatte Stefan beschrieben, dass AD "nur" beim Spielstart die auf der Karte befindlichen Triggerpunkte scannt / liest, daher kommt das Verhalten bei Dir, wenn Du in der Session neue Trigger (z. Bsp. durch Aufstellen eines neuen Silos) erstellst...
