### ISSUE TITLE
AD does not start when goods are strapped to flat deck

### ISSUE THREAD

**Issue by ZerwasMOD** [Stephan-S/FS19_AutoDrive#265]
Hi Stephan,
I am using this [1948 Chevy Truck](http://www.modhub.us/farming-simulator-2019-mods/chevy-coe-1948-custom-1-0/)  and when I strap anything on its flatdeck, AutoDrive won't drive truck any longer. Its only related when using the lashing strap. Otherswise the truck works just fine with AD.
I know it is most probably caused by the truck mod, I also contacted the creator of this mod, but it is maybe also useful for you to know what hinders this mod from performing normally.

Best regards

**Comment by aviator64** [comment]
The in-game pickup truck exhibits similar, although not identical, behaviour.

With items (ten egg crates) strapped into the truck bed, the truck will drive OK in a straight line, but when it goes to make a turn it will come to a stop and won't drive further.

I suspect it is seeing a collision with an item in the bed. This is probably the same reason why a tractor with a pallet on the front loader won't drive. See my earlier thread on that topic.

**Comment by Stephan-S** [comment]
Correct analyzes by @aviator64 
I haven't implemented any detection of strapped on materials.
They register as normal 'vehicles' and are not 'attached' to the driver, so they register a collision and stop AD.

Oh and sorry for the late reply^^

**Comment by ZerwasMOD** [comment]
Thanks for the input. At least it makes it understandable !
