### ISSUE TITLE
AD im Hilfefenster ausblenden ?

### ISSUE THREAD

**Issue by MaLouPa** [Stephan-S/FS19_AutoDrive#266]
Hi Stephan,

gibt es eine möglichkeit deine AD Tastenbelegungen im Hilfefenster auszublenden?
Wer ja mittlerweise halbwegs versiert ist, braucht die Tipps dort eigentlich nicht mehr oder?

**Comment by Gariot** [comment]
Mit STRG - ALT - Numpad 0 kannst du die Optionen fuer AD oeffnen und, unter anderem, auch die Hilfe ausblenden lassen.

**Comment by MaLouPa** [comment]
Perfekt ! Vielen Dank !
