### ISSUE TITLE
Brauche hilfe bei kombi Cp-Ad, kalken/düngen

### ISSUE THREAD

**Issue by andreasthu** [Stephan-S/FS19_AutoDrive#268]
Hallo Leute.
Versuche nun schon einige zeit die Kombination courseplay u autodrive beim düngen u kalken zum laufen zu bekommen.
Mit cp funktioniert auch erstmal alles soweit, nur wenn der streuer leer ist, fährt cp/ad entweder zum feldpunkt und bleibt dort stehen, oder zum düngeraufladepunkt und bleibt dort stehen,  oder Cp will gleich wieder zum felbg
Bearbeitungskurs fahren wo er vorhin aufgehört hatte (quer über die karte)
Ich verstehe es nicht, welche def 4 kursarten soll ich da wählen in AD?
Welcher punkt soll unten beim kippersymbol eingestellt werden, Feldpunkt oder auffüllpunkt?
Welcher kurspunkt soll oben beim (ka wie ich das symbol nennen soll) Kartenpunkt eingetragen werden, ich nehme an das, das nicht beim kippsymbol ist.
Frucht Kalk ist klar.

Bitte um hilfe
Lg
Andreas

**Comment by haamic** [comment]
Hallo,
4 Kursarten? Sollten jetzt 5 sein. Neu hinzugekommen ist der load-Modus. Ich glaube das Symbol nach dem Drescher, mit dem Pfeil der zum kipper zeigt. Wenn nicht vorhanden dann mal updaten, kann sein im letzten Release ist das noch nicht drin. Ich hab das glaub ich selber aus dem Master Download zum zip gebastelt. 
Bei diesem Modus sind Ziel und Start glaub ich vertauscht,als bei "abholen und abladen". Kann es jetzt nicht genau sagen. Einfach mal testen, entweder Oben das Feld und unten der auffüllpunkt, oder umgekehrt. Nur dieser neue load-Modus funktioniert bei mir, zum Auffüllen mit cp. 
Viel Erfolg. LG Micha

**Comment by andreasthu** [comment]
hallo @haamic 
hab mir jetzt das ganze als zip runtergeladen,entpackt und den inhalt von
master/FS19_AutoDrive
( https://github.com/Stephan-S/FS19_AutoDrive/tree/master/FS19_AutoDrive )
als zip gepackt.
habe aber trotzdem nur 4 modi
Fahren (der Pfeil)
Abholen und Abliefern (kleiner Pfeil mit Kipper) 
Abladen (nur der Kipper)
Drescher Abfahren (Drescher mit Rohr)

wo gibts das fünfte?

lg
andreas

**Comment by Mannie313** [comment]
[FS19_AutoDrive.zip](https://github.com/Stephan-S/FS19_AutoDrive/files/3357891/FS19_AutoDrive.zip)
hier bitte sehr @andreasthu

**Comment by andreasthu** [comment]
schönen Dank
nun hab ich auch den 5. modus "Abholen"
aber wie hast du das gemacht,
ich hab auf der github seite rechts oben auf das grüne "clone or download" geklickt, die zip runtergeladen und daraus den inhalt des "FS19_Autodrive" ordners gezippt und in den mods ordner.
das sollte ja die aktuellste version sein, oder?

lg
andreas

**Comment by haamic** [comment]
Eigentlich hätte das bei dir so funktionieren müssen, wie du das gemacht hast. Vielleicht hiess das zip doch anders und du hattest nun 2 im Modordner und nur das alte war aktiviert beim laden.

**Comment by andreasthu** [comment]
Kann  ich ausschließen. 
Ich achte bei sowas immer, ob windows die meldung ausgibt, datei vorhanden  - ersetzen?
Das war gestern abend definitiv der Fall.
Aber egal, jetzt hab ich die version mit 5 modi.
Eerde die beim kalken demnöchst trsten.
Lg
Andreas

**Comment by Opa-Andre** [comment]
Danke für die Info @haamic. Ich hatte den 5. Modus auch nicht. Stellte sich heraus, dass ich einfach nach dem Download aus dem Master file immer nur im Ordner "releases" die aktuellste Zip herausgeholt hab (also aktuell die 1.0.3.3) und die in den Modordner gepackt hab. Hat ja auch lt. moddesc.xml die Version 1.0.3.3. Im Ordner "FS19_Autodrive" der Master ist es ebenfalls Version 1.0.3.3 - ist allerdings eine andere, neuere Version. Hab das grad verglichen - hier gibt es die autodrive.lua mit 5 Modi, während die andere nur 4 Modi hat...

**Comment by haamic** [comment]
Schön, wenn's geholfen hat. Gruß Micha
