### ISSUE TITLE
Beladen / Entladen Modus belädt nicht bei Gras?

### ISSUE THREAD

**Issue by Opa-Andre** [Stephan-S/FS19_AutoDrive#269]
Hallo zusammen,
habe ein kleines, spezifisches Problem mit dem Modus Be-/ und Entladen am Silo. 
Habe einen Kurs, wo das Gespann am Silo lädt und die Stoffe zum Verkauf fährt. Dies funktioniert soweit auch ohne Probleme - ausser, wenn ich vom Silo Gras laden will. Hier fährt der Traktor dann an das Silo heran und bleibt stehen - lädt aber nicht. Steige ich in den Traktor ein und drücke "R" zum Beladen, kann ich Gras auswählen und die Beladung manuell starten. Sobald das Gespann voll ist, fährt der Traktor ganz normal via AD weiter. 

Nun ist mir in dem Zusammenhang noch etwas aufgefallen: Klicke ich beim gewählten Kurs in den rechten Bereich des Beladepunktes, bekommt man ja eine Drop-Down Liste mit möglichen Filltypes angezeigt, welche von der jeweiligen Map unterstützt werden. Hier findet man alphabetisch alle Filltypen 1x aufgeführt - bis auf den "Grass" Eintrag - den gibt es 3x untereinander.

Erst dachte ich dass es ggf. an einem anderen Mod liegt und habe daher das ganze in einem neuen Savegame auf der Felsbrunn ohne weitere Mods ausprobiert`. Also als einzigster Mod AD im Ordner... auch hier erscheint "Grass" 3x im Auswahlmenü. 

FS 19 Version 1.4
AD Version 1.0.3.3 
Log fehlerfrei

Irgendeine Idee, woran das liegen könnte?

**Comment by haamic** [comment]
Hast du die anderen Gras Einträge auch probiert? Ich selber habs noch nicht getestet. Dazu hat Stephan glaub ich mal was geschrieben, womit das 3fache Gras zusammenhängt, ich erinnere mich aber leider nicht mehr.

**Comment by Opa-Andre** [comment]
Ja, hatte ich - war aber kein Unterschied.

**Comment by Stephan-S** [comment]
Kann es sein das du Heu laden möchtest?

**Comment by HawkPat** [comment]
Soweit ich mich erinnere, werden auch die fillTypes Grasschwad und Heuschwad als "Gras" im AD-Menü angezeigt. Die werden nämlich dann in der entsprechenden XML der ModMap alle als _fillType_grass_ betitelt und von AD mit "Gras" übersetzt.. Ich hatte das Problem ebenfalls: drei Einträge "Gras" im AD-Dropdown-Menü. Da funktionierten die ersten beiden nicht, aber der dritte. War glaube ich auf der Multimap 2019 und definitiv auch auf der NF Marsch. Warum keiner der Einträge bei Dir funktioniert, ist mir allerdings ein Rätsel.

**Comment by Opa-Andre** [comment]
@Stephan-S : Nein, Heu funktioniert.
@HawkPat : Würde ich bei der Multimap 2019 ja evtl. verstehen, aber da es ja auch bei der Original Felsbrunn auftritt...

**Comment by Opa-Andre** [comment]
@Stephan-S : Hier ein Bild (neues Spiel auf Felsbrunn ohne andere Mods): Heu hat einen separaten Eintrag, der auch funktioniert. Konnte jetzt beim "Schnelltest" für den Screenshot nicht nochmal den 3. Gras-Eintrag testen, weil im Originalspiel ja kein Silo dabei ist, in welchem man Gras (grass_windrow) lagern kann und ich ausschließen wollte, das es durch einen Mod verursacht wird...
![Bildschirmfoto 2019-07-04 um 18 03 12](https://user-images.githubusercontent.com/38733952/60679043-9e4a8180-9e86-11e9-8518-dd4cec691c62.png)

**Comment by HawkPat** [comment]
Also ich habe mir schnell mal die xml der NF Marsch und der Original-Maps angesehen. Die fillTypes sind überall gleich betitelt: _grass_, _grass_windrow_ und _drygrass_ als **grass** und _drygrass_windrow_ als **drygrass**. Frag mich nicht, warum der fillType _drygrass_, also Heu, ebenfalls als **grass** betitelt ist.  

Ich habe auf der NF Marsch ein paar Liter Gras im Silo und in der Savegamedatei items.xml wird das als GRASS_WINDROW aufgeführt. Macht ja auch Sinn, da das Gras ja normalerweise mit dem Ladewagen als Grasschwad aufgenommen und so in das Silo abgeladen wird. Der funktionierende dritte Eintrag bei meinem AD-Dropdown muss also grass_windrow sein.

**Comment by Opa-Andre** [comment]
Ok, wenn drygrass zur Grasgruppe gezählt wird, ist klar woher die 3 Einträge kommen. Auch wenn es m. Meinung nach wenig Sinn macht, es überhaupt als Fruchttyp zu definieren, weil es ja nirgendwo eingesetzt wird. Beim Gras selbst sind die beiden Fruchttypen ( Grass und Grass_windrow) verständlich. Der erstere "Grass" ist für die Feldbestellung (also z. Bsp. "gsSetFieldfruit 1 grass 4" für die höchste Wachstumsstufe - Heu hingegen wird nicht angesät :) Und die "windrow" typen sind die Schwadversionen beim Ernten & Trocknen. Werde nachher auch nochmal auf der Multimap2019  mit dem allen 3 Versionen testen, vielleicht klappts ja doch...

**Comment by Opa-Andre** [comment]
So, habe es nochmal getestet - jetzt funktionierte es auf der Multimap komischerweise doch - mit dem zweiten Graseintrag. Da muss mir bei den ersten Versuchen doch irgend ein Mod noch mit dazwischen gefunkt haben. Als es mir das erste mal auffiel, hatte ich nämlich aufgrund der Multimap ein paar der von mir verwendeten Mods auch hinsichtlich Fülltypen etc. angepaßt, erst den Fehler wegen mir selbst gesucht und nachdem dies nichts geholfen hat, die alle herausgenommen... mit dem Ergebnis das der 3-fache Eintrag dennoch drin blieb und ich mir das nicht mehr erklären konnte.

Vielen Dank an alle für die Aufklärung.
