### ISSUE TITLE
Field exit bug, Load mode or manual continue

### ISSUE THREAD

**Issue by aviator64** [Stephan-S/FS19_AutoDrive#271]
I have my AD set to always exit a field "behind start". However, when in Load mode (refilling a spreader, for instance) it will instead exit via the nearest point on the network. This often involves crossing other fields and joining a road going the wrong direction.

Also, when in Combine Unload mode, if I click the "Continue" button (to send the tractor to the delivery point before it is full), it does the same thing - exits via the nearest point instead of returning to the start point.

**Comment by Stephan-S** [comment]
I think both issues are adressed by now. Cleaning up some old issues today
