### ISSUE TITLE
Wasser beladen?

### ISSUE THREAD

**Issue by haamic** [Stephan-S/FS19_AutoDrive#274]
Hallo, kann mir bitte jemand erklären, wieso ich kein Wasser laden kann? 
wollte mit "Abholen und Abliefern" einen Stall mit Wasser versorgen.
An der Wasserstelle (zb Teich oder Hydrant) tankt AD nicht das Wasser auf. Lasse ich einen selbst befüllten Anhänger mit AD zur Abladestelle fahren, wird er geleert, wie gewünscht.
Gruss Micha

**Comment by Stephan-S** [comment]
Probiere es Mal mit einer platzierbaren Wasserquelle aus. 
Und denk daran nach dem Aufstellen einmal das Spiel neu zu starten, da AutoDrive nur beim Laden der Karte nach Lade/Entlade-Triggern sucht.

**Comment by haamic** [comment]
der Hydrant ist eine platzierbare Wasserquelle gewesen
 okay ,das mit dem Neustart probier ich jetzt, danke

**Comment by haamic** [comment]
funktioniert, recht vielen Dank Stephan

**Comment by haamic** [comment]
da ich dich auf kurzen weg hier erreiche, nimmst du dich bitte noch dem Rückwärtsfahren nach dem Abtanken des Dreschers an? Das geht nicht mehr so wie in älteren Releasen. Gefühlt sind das nur noch Zentometer statt vorherigem grössen zurücksetzten des Abfahrers.
