### ISSUE TITLE
LUA Fehler: AutoDriveGraphHandling.lua:345: attempt to index a nil value

### ISSUE THREAD

**Issue by Gariot** [Stephan-S/FS19_AutoDrive#275]
Kann nicht genau sagen wann das passiert ist, aber die Log haeng ich ran.

Aber mal ne Frage: Sollten die Trailer die ne Plane haben nicht immer ihre plane an/aus machen? Oder ist perma aus so gewollt?

edit: Version: Aktuellste

[log.txt](https://github.com/Stephan-S/FS19_AutoDrive/files/3367027/log.txt)

**Comment by Stephan-S** [comment]
Danke für die Meldung. Wird im nächsten release behoben.
Die Source Files haben gerade den Fix bekommen, falls du dir die zip selber packst.
