### ISSUE TITLE
Kurse Exportieren geht nicht

### ISSUE THREAD

**Issue by Bandesss** [Stephan-S/FS19_AutoDrive#277]
Hallo zusammen,ich drücke Diskette aber exportiert nichts.
Auch mit dem Tastenbefehlt STRG links ALT liks Numpad2 geht es nicht.
Hat jemand eine Idee
Gruss Bandes

**Comment by Gariot** [comment]
Woher weisst du das er nichts exportiert? Normalerweise legt er eine Datei an und packt sie in den Ordner "FS19_AutoDrive_Export" der sich im selben ordner befindet wie "mods", "savegame1 (usw)" etc. Damit er Kurse exportiert muessen natuerlich auch welche vorhanden sein. Stell auch sicher das du vorher einmal die Kurse neu berechnet hast. Wenn das alles komplett frische kurse sind, also vorher garnichts vorhanden war, hilft eventuell kurse neu berechnen, spiel speichern und einmal das spiel neu starten. Spaetestens dann muesste Export funktionieren.

Hab gerade Kurse exportiert, funktioniert also ;)
