### ISSUE TITLE
Parken im Feld

### ISSUE THREAD

**Issue by Gariot** [Stephan-S/FS19_AutoDrive#280]
Hi,

man kann als Option ja einstellen das AD im Feld parkt nach dem Drescher abtanken wenn er nicht in der Frucht steht. Bis vor kurzen funktionierte das auch noch, jetzt scheint er aber die Frucht nicht mehr zu erkennen und parkt froehlich in der Frucht. Bis auf weiteres stelle ich natuerlich einfach wieder die option aus, waere aber toll wenn das behoben wird. 

Version: Aktuellstes Release

**Comment by hoefti10** [comment]
Bei mir auch mit der aktuellsten Version
