### ISSUE TITLE
something isn't right 

### ISSUE THREAD

**Issue by ploughedfieldman123** [Stephan-S/FS19_AutoDrive#281]
I cant understand why this trailer which says only 76% wants to go to unload place. when it should go to unload combine marked in red at 100% a T560 combine

<a href="https://ibb.co/5MPkPcQ"><img src="https://i.ibb.co/Bz9G9sh/unload.jpg" alt="unload" border="0"></a><br /><a target='_blank' href='https://imgbb.com/'>

**Comment by Gariot** [comment]
Probably because AD is set to unload when the trailer is > 70% (or even > 50%). Check your settings with CTRL - ALT - Numpad 0.

**Comment by ploughedfieldman123** [comment]
No its not that as I checked its on 100%

<a href="https://ibb.co/gJnwvq1"><img src="https://i.ibb.co/HqJYNwv/100.jpg" alt="100" border="0"></a><br />

**Comment by Stephan-S** [comment]
If AD is started and the trailer is almost full, it will first unload, independent of the setting in the GUI. I will have to adjust that
