### ISSUE TITLE
Abfahrer losschicken unter 50%

### ISSUE THREAD

**Issue by Andii1980** [Stephan-S/FS19_AutoDrive#284]
Hallo, 

Ich benutze AD erste seit ein Paar Tage und bin damit bis jetzt sehr Zufrieden und Dankbar für die Super Mod.

Gibt es bei der Drescher Abtanken und wegbringen Funktion auch die Möglichkeit irgendwie dem Abfahrer zu Sagen das er Abfahren soll. Es kommt ja öfter mal vor das am Ende des Feldes die Eingestellte Abliefer Menge noch erreicht ist. Ich finde es recht umständlich immer dem Abfahrer den Ablade Modus dann zu geben. damit der Rest unter 50% Abgefahren wird.

Mit bestem Dank
Andii

**Comment by HawkPat** [comment]
Versuchs mal mit der Option "Weiterfahren". Bin mir aber nicht sicher, ob das für Abfahrer auch funktioniert.
![01](https://user-images.githubusercontent.com/52010642/61108512-bc197700-a482-11e9-9edd-1b4e84415817.jpg)

**Comment by Andii1980** [comment]
Hallo, Ich hab es jetzt mal getestet mit dem Weiterfahren. Und musste feststellen das der Button irgendwie nichts bringt. Weder beim Abfahrer noch beim Beladen am Startpunkt und Entladen.

**Comment by HawkPat** [comment]
Also ich habe das jetzt auch mal probiert. Hat geklappt.
Szenario: Abfahrer teilgefüllt, steht am Startpunkt mit Hinweis "Warte auf Drescher" in grün, "Weiterfahren" gedrückt, Ziel wird grün und Fahrer fährt los zum Abladepunkt.
Wenn Du es erst ein paar Tage nutzt, wird die AD-Version wohl relativ aktuell sein? Ansonsten weiß ich da auch nicht weiter.

**Comment by Andii1980** [comment]
Auch Fu... . Ich hab hier AD Runtergeladen gehabt und es in LS richtig Eingefügt, was auch geklappt hatte. bei einem Erneuten Start von LS und dem Updaten der Mods über ModHub hab ich jetzt wieder die Version 1.0.1.9 drauf. Da hatte ich gar nicht auf die Version geachtet beim Updaten. *Face meets Tischplatte* :D

Ich werd mal hier erneut die Version runterladen und es damit Testen.

**Comment by Gariot** [comment]
Das is soweit korreckt. Der Abfahrer kann nur "weitergeschickt" werden wenn er am startpunkt steht und auf den Drescher wartet. Ansonsten ist das minimum wo der Abfahrer wegfaehrt bei 50%. Eine niedrigere Option oder "sofort" gibt es leider nicht und habe ich auch schon vorgeschlagen. #263

**Comment by Stephan-S** [comment]
Das sollte seit einigen Versionen eigentlich funktionieren, also mache ich hier mal zu. Danke für euer Feedback!
