### ISSUE TITLE
Feldausfahrt von CP-Fahrern

### ISSUE THREAD

**Issue by HawkPat** [Stephan-S/FS19_AutoDrive#285]
Ich finde die Zusammenarbeit von CP und AD echt schon fast perfekt.  Da haben die Modder saubere Arbeit geleistet.
Zur Perfektion fehlt mir nur noch eine Sache: die Feldausfahrt-Optionen funktionieren zwar für Drescher-Abtanker, leider aber nicht für Ladewagen oder -Dünge- bzw Säemaschinen, die die Feldarbeit mit CP durchführen.
Wenn die CP-Fahrer geleert bzw. befüllt werden müssen, wird bei der Übergabe des Fahrzeugs von CP an AD immer der nächstmögliche Wegpunkt für die Ausfahrt gewählt, unabhängig davon, welche Feldausfahrts-Option man auswählt. Das führt in vielen Fällen unweigerlich zu Begegnungen mit Bäumen, Mauern, Gräben, etc.
Ich habe diesen Punkt auch schon im CP-Forum erläutert, wo man sich noch nicht sicher ist, ob das ein CP- oder ein AD-Issue ist.
Es wäre toll, wenn man da noch am Code werkeln könnte, sodass diese Fahrer ebenso handeln, wie es in der Feldausfahrts-Option ausgewählt ist.

Ansonsten wie gesagt: tolle Arbeit.

**Comment by sootysax** [comment]
you should record a perimeter of purple colored course around the inside of the field that is connected to the road network..   this way when it is time to leave the field, the tractor will drive to that perimeter and then to the exit instead of crashing into any trees or fences trying to get to the road

**Comment by HawkPat** [comment]
Thanks. That's what I did already so far. But of course it would much easier for us players if there would be a solution in the code so we don't have to do it the way you mentioned. Exiting on the starting point works fine for unloader of CP or Giant helper combines though.

**Comment by Stephan-S** [comment]
Inzwischen sollte die korrekte Strategie auch bei von CP gestarteten Fahrten aktiv sein. Ich mache hier mal zu :-)
