### ISSUE TITLE
LS19 erkennt die neueste Version nicht

### ISSUE THREAD

**Issue by HerrchenChris** [Stephan-S/FS19_AutoDrive#286]
Huhu,

habe mir hier auf Github die 1.0.3.5 herunter geladen und in den mods-Ordner von LS19 verschoben.

Allerdings will der LS die nicht laden, sondern wieder auf die 1.0.1.9 runter patchen, oder mir die Mod verweigern.

Muss man da irgendwas einstellen?

**Comment by Andii1980** [comment]
Das Problem hatte ich auch gehabt. Ich mach jetzt im Modhub kein Update mehr von AutoDrive ;)

**Comment by HerrchenChris** [comment]
Und wie kann ich es deaktivieren? Irgendwie habe ich es da nicht gefunden und wenn ich das Spiel so starten möchte, dann wird mir AD bei der Mod-Auswahl nicht angezeigt :-(

**Comment by Andii1980** [comment]
Hast du dir hier AutoDrive Runtergladen? wenn ja
1. Entpacken
2. den Entpackten Ordner öffnen und in das Verzeichnis FS19_AutoDrive wechseln.
3. den Inhalt Markieren und das Markierte als zip Datei packen.
4. die daraus Entstandene FS19_AutoDrive.zip Datei in dein LS19 Mods Ordner kopieren.

dann sollte bei dir auch AutoDrive vorhanden sein. darfst halt dann nur kein "Update" von AutoDrive machen.

So hat es bei mir geklappt

**Comment by HawkPat** [comment]
Es geht auch noch einen Ticken schneller: nicht in den Ordner "FS19_AutoDrive" gehen, sondern in "releases". Da sind alle Versionen drin und die sind da bereits als zip vorhanden. So spart man sich das Auswählen und erneut Zippen.
Es führen halt viele Wege nach.... naja...ihr wisst schon ;-)

**Comment by Andii1980** [comment]
Ah ok. Danke für den Tipp. das war mir selbst auch noch nicht bekannt.

**Comment by HerrchenChris** [comment]
Upps, hier wollte ich doch auch noch antworten *schäm*
Also, AutoDrive läuft bei mir, hatte den hier herunter geladenen Ordner "standardmäßig" wie bei anderen Mods auch, direkt so in das Mod-Verzeichnis gepackt.
Nachdem ich mir dann aus den releases das passende gezogen habe, hat es dann auch geklappt.

**Comment by tomy852** [comment]
> Upps, hier wollte ich doch auch noch antworten _schäm_
> Also, AutoDrive läuft bei mir, hatte den hier herunter geladenen Ordner "standardmäßig" wie bei anderen Mods auch, direkt so in das Mod-Verzeichnis gepackt.
> Nachdem ich mir dann aus den releases das passende gezogen habe, hat es dann auch geklappt.

**Comment by tomy852** [comment]
Bei mir hat es die neue Version trotz allem nicht übernommen. Erst als ich den Namen von der neuen Zip-Datei abgeändert habe, so das er nicht gleich ist wie die alte. 
Aus "FS19_AutoDrive" habe ich "FS19_AutoDrive1" gemacht dann erst hatte ich im Spiel die neuste Version.
