### ISSUE TITLE
release v1.0.3.6

### ISSUE THREAD

**Issue by ploughedfieldman123** [Stephan-S/FS19_AutoDrive#287]
is there any help on how to do this new thing, as dont see any extra button

**Comment by Stephan-S** [comment]
No, I just added a new function for the CP developers to call. You will have to wait for a new update of CP. They have to integrate it first.

**Comment by ploughedfieldman123** [comment]
> No, I just added a new function for the CP developers to call. You will have to wait for a new update of CP. They have to integrate it first.

oh i see ok thanks
