### ISSUE TITLE
Refill Problem

### ISSUE THREAD

**Issue by RUGhost** [Stephan-S/FS19_AutoDrive#291]
If You select seed as fill type then it fill the seeder with seed and stay idle instead of filling fertilizer. If You select fertilizer as fill type then it fill the seeder with fertilizer and stay idle instead of filling seed.

![Farming Simulator 19 V1 4 0 0 Screenshot 2019 07 19 - 20 26 00 90](https://user-images.githubusercontent.com/48012198/61543335-1018f280-aa65-11e9-8faa-a09a24c6723e.png)

**Comment by aviator64** [comment]
I have seen that too. It appears that Load mode does not support multiple fill types.

Ideally, it should work like Courseplay in that regard, where it will fill at any usable fill point it happens to pass on the route. I'm guessing that would require a significant rewrite though.

**Comment by fudoido** [comment]
agree with aviator, could also be usefull to refill at gas stations.

**Comment by alpha117** [comment]
Also I would like to add  it will not refill from a 'multi Silo'  that has seed AND fert

Thanks
