### ISSUE TITLE
Frage: Texteingabe in DropDown

### ISSUE THREAD

**Issue by kleba78** [Stephan-S/FS19_AutoDrive#292]
Hey,

kann man noch irgendwie eine Texteingabe im DropDown Menü machen, gerade bei vielen Zielen scrollt man doch ne Weile hin und her?

Kann man Wegpunkte auch im nachhinein umbenennen? Reicht der Edit der autodrive config im savegame.

Danke und "good job" 
Sven

**Comment by Opa-Andre** [comment]
Im angepinnten Thread steht, dass keine neuen Features mehr erstellt werden - also wird das mit der Texteingabe im Dropdown eher nichts. Aber du kannst ja anstelle des Dropdowns die Texteingabe direkt nutzen...derzeit mehren sich aber wieder die Meldungen von Usern, welche das nicht bemerken und glauben, dass dann ihr komplettes Spiel hängt. Dabei reicht es, einfach mal die Enter-Taste zu betätigen, und/oder zusätzlich mit der Maus nochmal das "leere" Zielfeld anzuwählen, um weiterspielen zu können.

Das mit der Wegpunkt Umbenennung in der XML Datei funktioniert problemlos. Mache ich auch ab und zu, wenn ich mich mal vertippt habe oder die Bezeichnungen vereinheitlichen will. Geht ohne Probleme. Solange Du nur den Text innerhalb der Gänsefüßchen änderst, passiert nichts...

**Comment by kleba78** [comment]
danke opa-

**Comment by kleba78** [comment]
Hey,

ganz ehrlich, ich bekomme das nicht hin, die Texteingabe direkt zu nutzen und nicht das DropDown, kannst du mir bitte erklären wie das funktioniert, ich lange irgendwie immer im DropDown.

**Comment by haamic** [comment]
Also bei mir klappt das prima. Ich klicke mit der mittleren Maustaste in die Zeile und da verschwindet der Text, wenn schon was drin stand. Jetzt kann man die Texteingabe nutzen

**Comment by kleba78** [comment]
ja die mittlere Maustaste hat es dann gebracht - vielen Dank
