### ISSUE TITLE
Problems in the field

### ISSUE THREAD

**Issue by MacedonskyAlex** [Stephan-S/FS19_AutoDrive#294]
Tractor a trailer properly drives up to the combine. But the trucks for some reason pass on. It also happens that you have to restart the game, as the tractor refuses to go to the combine.
![fsScreen_2019_07_20_22_01_07](https://user-images.githubusercontent.com/52257646/61582983-be429c00-ab3a-11e9-875b-da4c5ba194e5.png)

**Comment by MacedonskyAlex** [comment]
![fsScreen_2019_07_22_22_58_06](https://user-images.githubusercontent.com/52257646/61661196-34c6d180-acd4-11e9-9adb-50d14494c625.png)

**Comment by Stephan-S** [comment]
If this issue is still ongoing for you, please reopen. This has changed quite a lot in the last few releases
