### ISSUE TITLE
All vehicles lock up - requires restart to clear

### ISSUE THREAD

**Issue by Flashsolutions** [Stephan-S/FS19_AutoDrive#295]
If you move a vehicle during the update paths process, it locks you out of ever being able to get out of the vehicle or tab to another vehicle.   With the open and update buttons so close together, it is very easy to accidentally hit the open button when updating.

**Comment by Stephan-S** [comment]
I think this has to do with you clicking into the name field and activating the text input.
This should otherwise not be a problem.
