### ISSUE TITLE
Spiel friet ein

### ISSUE THREAD

**Issue by Arpad81** [Stephan-S/FS19_AutoDrive#296]
Hallo, ab und zu friert das Spiel ein, sobald an mit AD in den Aufnahmemodus wechselt. Man kann dann nicht mehr die Fahrzeuge wechseln oder ins Hauptmenü. Es bleibt nur die Möglichkeit über die Konsole das Spiel zu verlassen. In der Log.txt ist nichts eingetragen.

**Comment by Opa-Andre** [comment]
Sicher, dass Du dabei nicht ggf. mal auf die Suchen-Funktion gekommen bist? Wenn der Fehler auftritt, schau mal ob die Zeile(n) (je nach ausgewähltem Modus) keine Ziele mehr anzeigen. Ist dass der Fall, dann mal die Enter-Taste drücken - wenn dies allein nicht hilft, dann mit der Maus nochmal in den Bereich klicken, wo das bzw. die Ziele angezeigt werden. Passiert mir auch ab und zu, aber über diesen Weg komm ich wieder zurück ins Spiel, ohne die Konsole zum Beenden nutzen zu müssen.

**Comment by Stephan-S** [comment]
Da inzwischen ja das 'Suchen' per Optionen standardmäßig aus ist, nehme ich an das ich hier zu machen kann :-)
