### ISSUE TITLE
Mp dedicated server bug

### ISSUE THREAD

**Issue by FS-UK-TheMan1988** [Stephan-S/FS19_AutoDrive#297]
when i play with friends on my ded. server.

it starts to lagg when we use AD

**Comment by fudoido** [comment]
i think this was a issue also with fs17, and also with courseplay. its like the mods on dedi server hoard all resources from server to make the calculations. i also had issues like this with the advanced vehicle a.i. from mogli on fs17.

**Comment by FS-UK-TheMan1988** [comment]
how can i make AD work with a forager? now i use a auger wagon and a krone forager, can i add something to the overload etc?  maybe this? 

                        <alarmTriggers>
                            <alarmTrigger minFillLevel="1" maxFillLevel="1" turnOffInTrigger="true"/>
                        </alarmTriggers>
