### ISSUE TITLE
Question, not an issue. Sorting destinations

### ISSUE THREAD

**Issue by auddie2015** [Stephan-S/FS19_AutoDrive#298]
Is there a way to rearrange the order that the destinations rotate through by editing the data file?

**Comment by auddie2015** [comment]
I found a way. I am not sure it's the right way but... for anyone else interested, the destinations are between <mm></mm> tags were it is incremented to <mm1>, <mm2> etc. You have to carefully move the data between the tags around to the order you want them OR you can rearrange them and renumber the mm tag.

If there is another way, Stephan-S, I would love to not have to do it this way. :-P

**Comment by fudoido** [comment]
for me so far it has organized them alphabetical and caps priority. something like 

CASTEL
DOCKS
Barn
Field 2
Grain Mills
Shop
field 1
train station

So, all caps get arranged firts alphabetically, then only 1 letter caps, then no caps, but all in aplhabetic order.
due this, i started to create the names in all caps so it keep alphabetic order for everything, easy to search.

**Comment by auddie2015** [comment]
Good info. I will start using all caps. I have mixed case like crazy!

**Comment by Opa-Andre** [comment]
If you're using the arrows to switch from one target to the next (right arrow) or to the previous one (left arrow), the destinations are "unsorted", which means they appear in the list as they were created. Thus when creating a new AD network for a new map I always start with the "Farm" destination, so it will be the initially selected waypoint when using a new vehicle.

Using right click with your mouse will arrange all waypoints in alphabetical order in the drop down list as described above (CAPS, no CAPS etc...). As during creating the AD network the list of Targets is growing more and more, I'm Always using the same starting words, so all Transport Mission destinations start with "T-Mission" - for example "T-Mission Ranch" or "T-Mission Castle", or all selling stations start with "Selling ...". That way I have only a few categorizing words, like "Load"; "Unload": "Buy"; "Sell"; "T-Mission" and "Field" for all field destinazions as well as "Z-Other" for uncategorized destinations. 

That way (categorizing start words) its more easy to scroll through a long list of destination entries to find the one you're Looking for.

Last but not least, if I mistakenly created an wrong destination name (typo etc.) then its easy to correct the name itself in the XML file... Going through the destination name list I then just rename the destination names as needed by using / starting with one of the above categorizing words.

**Comment by raxtor** [comment]
> for me so far it has organized them alphabetical and caps priority. something like
> 
> CASTEL
> DOCKS
> Barn
> Field 2
> Grain Mills
> Shop
> field 1
> train station
> 
> So, all caps get arranged firts alphabetically, then only 1 letter caps, then no caps, but all in aplhabetic order.
> due this, i started to create the names in all caps so it keep alphabetic order for everything, easy to search.

Wouldnt be better use underscore system
__aa
_aa

Capslok sensitive sorting is not very good..
