### ISSUE TITLE
Wegpunkt-Markierung im Editor

### ISSUE THREAD

**Issue by HawkPat** [Stephan-S/FS19_AutoDrive#299]
Kann mir jemand erklären, was es bedeutet, wenn ein Wegpunkt im Editor wie im Bild zu sehen mit roten Pfeilen markiert ist?
![rote_Pfeile](https://user-images.githubusercontent.com/52010642/61801068-74093580-ae2e-11e9-8773-0455885116c6.JPG)

**Comment by HawkPat** [comment]
...im Editor

**Comment by haamic** [comment]
Ich nutze den externen Editor zwar nicht, aber wahrscheinlich ist das wie im Spiel selber ,im edit Modus, ein einzelner Punkt der keine Verbindung mehr irgendwohin hat. Zur besseren Erkennung mit "x" markiert.

**Comment by HawkPat** [comment]
Nein, der Punkt ist mit den beiden benachbarten oben und unten verbunden. Das kann ich daran erkennen, dass sich die Verbindungslinien mitbewegen, wenn ich den Punkt verschiebe.

**Comment by Opa-Andre** [comment]
Da ich den externen Editor auch nicht nutze, auch nur eine Vermutung, wenn es sich nicht um ein "nicht verbunden" Symbol handelt, welches selbst im Edit Modus mit einem "x" gekennzeichnet wird. Wenn Du den "x" Punkt mal deutlich herausziehst - ist dann ggf. die Linie vom vorherigen Punkt (darunter) zum Punkt mit dem "x" eine "blaue" Linie anstatt einer grünen? D.h. das das Teilstück zwischen den Punkten in beide Richtungen befahrbar ist?

**Comment by Stephan-S** [comment]
Sieht fast so aus als würde hier der Punkt auf sich selber zeigen. Sprich da ist eine Strecke von Punkt X zu Punkt X. Also einfach mal den Punkt löschen und die Sache sollte erledigt sein :-)

**Comment by HawkPat** [comment]
Wenn ich den Punkt lösche, fehlt die Verbindung zwischen den benachbarten Wegpunkten. Die kann ich dann natürlich wieder verbinden. Dachte, dass das eine spezielle und programmierte Markierung ist.
Ich schließe den Thread.
