### ISSUE TITLE
Löschen mit Kurs abfahren

### ISSUE THREAD

**Issue by masurpilami** [Stephan-S/FS19_AutoDrive#30]
Danke erstmal mal für den Mod.

Habe da eine kleine Anregung fürs löschen von Punkten.
Ist es möglich wie bei der Aufzeichnung eine "Lösch" Aufzeichnung zu starten, die jeden Punkt in der nahen Umgebung durch einfaches durchfahren löscht?
Ich hoffe es ist verständlich was ich meine.

**Comment by Stephan-S** [comment]
Hallo,

ich denke ich verstehe was du meinst aber bei so einer Funktion habe ich dann doch eher Sorge das man versehentlich mehr Schaden anrichtet als Gutes zu tun :-)
Solange keine perfektes Undo-Feature eingebaut ist, sehe ich diese Funktion nicht als gute Option.
Trotzdem vielen Dank für deinen Input.

Wenn du das gleiche jetzt erreichen willst, leg dir die Punkt löschen Taste auf einen gut erreichbaren Button/Taste und fahre deinen Kurs ab während du diese Taste dementsprechend oft genug drückst
