### ISSUE TITLE
Kipper entlädt nicht (hält auch zu spät am Drescher)

### ISSUE THREAD

**Issue by haamic** [Stephan-S/FS19_AutoDrive#300]
Hallo,
ich hab schon etliche "Kipper" , also LKW mit direktem Aufbau, ohne Anhänger, getestet.
Diese lassen sich bei mir nicht entladen. Werden zwar befüllt, z.b. am Drescher, am Silo aber nicht. es funktioniert definitiv kein entladen. Alle getesteten Fahrzeuge fahren durch den Abladepunkt zurück zum Start. oder halten einfach an. Fahre ich händisch erscheint auch die "I...Fruchttyp"-Meldung am Abladetrigger. Woran liegt das?
Ausserdem ist mir aufgefallen, das bei kleinen Anhängern oder eben bei Kippern, das Fahrzeug am Drescher zu spät hält, weil Anhänger oder Ladefläche zu Kurz.
Hat jemand eine Idee, dies zu umgehen, ausser einen längeren anhänger zu nehmen?
welcher Parameter, evtl aus der .i3d / .xml müsste verschoben/geändert werden, das es passt?
Das ganze scheint ein generelles Ablade-Problem der Fahrzeuge/Kipper/LKW zu sein. mit CP funktioniert das bei mir auch nicht.
Gruss Micha

**Comment by Gram90** [comment]
Ich habe das selbe Problem...
