### ISSUE TITLE
Erorr Meldung Server

### ISSUE THREAD

**Issue by Bandesss** [Stephan-S/FS19_AutoDrive#301]
Hallo zusammen bekommen einen Erorr auf dem Server
[log.txt](https://github.com/Stephan-S/FS19_AutoDrive/files/3430140/log.txt)
Hoffe es kann mir jemand Helfen?
Gruss Ronny

**Comment by Opa-Andre** [comment]
Wenn es der Fehler ist, welcher in der Log angezeigt wird, der ist normal und zu ignorieren. Ist ja selbsterklärend. :)

**Comment by Bandesss** [comment]
Gibt es dafür ne lösung ?
19-10-20 10:00 Error: Failed to open xml file 'D:/Games/modsls19/Root Server/FS19_AutoDrive/AutoDrive_Willkommen_auf_Felsbrunn_init_config.xml'.

**Comment by Stephan-S** [comment]
Das heißt er sucht nach einer initialien Konfiguration. Das heißt eine Konfiguration die schon beim Mod enthalten ist. Für diese Karte gibt es diese natürlich nicht.
Ist also keine Fehlermeldung sondern nur eine Notiz

**Comment by Bandesss** [comment]
Dann habe ich es falsch gemacht in den Mod rein ?
![1](https://user-images.githubusercontent.com/50829319/67157043-befbf180-f326-11e9-8a92-fb0a8670592e.JPG)

**Comment by Stephan-S** [comment]
Achso, du hast es versucht in den Mod zu integrieren? Ja dann musst du die Datei umbenennen. Und zwar genau so wie in der Fehlermeldung auch beschrieben ;-)
Also 'AutoDrive_Willkommen_auf_Felsbrunn_init_config.xml' statt 'AutoDrive_Willkommen_auf_Felsbrunn_config.xml'

Dann sollte es so klappen wie du dir das vorstellst. Zumindest wenn du einen neuen Spielstand startest. Genau dann nutzt er ja die init config.
Wenn du das im laufenden Spielstand laden willst, musst du eben die Upload Funktion nutzen die ich dir ja extra mal gezeigt habe :-)

**Comment by Bandesss** [comment]
Ok vielen dank
