### ISSUE TITLE
HI Stephan

### ISSUE THREAD

**Issue by Bluebirdonline** [Stephan-S/FS19_AutoDrive#302]
Ich habe ein sicher kleineres Problem mit Deinem Autodrive Mod. Jedoch möchte Ich Dir als erstes sagen, das er mir sehr gut gefällt. Du hast die Möglichkeit einprogrammiert, den Fahrer, bzw. das Fahrzeug zu benennen. Das finde ich sehr gut, jedoch funktioniert dies bei mir nicht. Ich besitze einen MAC und kann alle anderen Funktionen gut benutzen. Ich habe die Taste "-" mit dieser Funktion belegt, rufe ich diese auf, erscheint für 1 Sekunde der Bildschirm, wo ich den Namen sicher ändern könnte und schließt sich dann sofort wieder. Könntest Du diese Funktion prüfen? Kontaktieren kannst Du mich über meine Mailadresse (info@0bq.de). Danke.

**Comment by Opa-Andre** [comment]
Hallo @Bluebirdonline , da muss Dir irgend etwas anderes dazwischen funken. Ich nutze ebenfalls ein Macbook Pro zum spielen und habe das Problem nicht. Allerdings nutze ich für die Umbenennen Funktion die Tastenkombi Option+Keypad 9 auf einer externen MAC Tastatur (entspricht in Windows <ALT>+<Keypad9>) mit der Steam Version des LS19. Würde empfehlen, Du testest das mal, indem Du a) ALLE Mods außer Autodrive aus deinem Spiel entfernst (also wirkllich den Mod-Ordner leer machen und nur Autodrive drin lassen) auf der Map Felsbrunn.

**Comment by Bluebirdonline** [comment]
Danke für deine schnelle Antwort. Ich werde das nachher probieren....

Von meinem iPad gesendet

Am 29.07.2019 um 06:06 schrieb Opa-Andre <notifications@github.com>:

Hallo @Bluebirdonline , da muss Dir irgend etwas anderes dazwischen funken. Ich nutze ebenfalls ein Macbook Pro zum spielen und habe das Problem nicht. Allerdings nutze ich für die Umbenennen Funktion die Tastenkombi Option+Keypad 9 auf einer externen MAC Tastatur (entspricht in Windows +) mit der Steam Version des LS19. Würde empfehlen, Du testest das mal, indem Du a) ALLE Mods außer Autodrive aus deinem Spiel entfernst (also wirkllich den Mod-Ordner leer machen und nur Autodrive drin lassen) auf der Map Felsbrunn.

**Comment by Bluebirdonline** [comment]
Nein, das tut mir leid. Ich habe alles versucht, es geht nicht. Auch Deine Hinweise befolgt. Ich sende Dir auch gern mal einen kurzen Ausschnitt zu. Sogar FS19 neu installiert. 

Mit freundlichen Grüßen

Burkhard Quenzler


___________________________________________________________________________________________________
HINWEIS | CONFIDENTIAL NOTICE

Daten, Texte und Bilder in dieser E-Mail sind urheberrechtlich geschützt und dürfen ohne Einwilligung des Urhebers nicht verwertet werden. Diese Mail kann vertrauliche Informationen enthalten. Falls Sie fälschlicherweise angeschrieben wurden, mache ich Sie ausdrücklich darauf aufmerksam, jede Weitergabe an Dritte zu unterlassen. Löschen Sie bitte anschließend E-Mail und Anhänge.

Bitte handeln Sie umweltbewusst. Drucken Sie diese E-Mail nur wenn Sie es wirklich müssen.

Scripts, Data and Pictures are copywritten. Not for use without permission. This message is confidential. If you have received this e-mail in error please delete it immediately. Unauthorised use, copying or disclosure of any of it is strictly unlawful.

Be nice to the world. Please don't print this e-mail unless you really need to.
___________________________________________________________________________________________________

**Comment by CairoAmun** [comment]
Hallo Stephan,
ich hoffe, es ist niemand böse, wenn ich mich hier einklinke. Ich habe einen Windows PC und kann diese Funktion auch nicht nutzen. Ich habe für diese Funktion die Kombi strg und alt links + die 9 auf dem Numpad vergeben. Wie bei Bluebird blinkt es kurz auf dem Monitor in der Mitte und verschwindet sofort wieder. Die Idee mit der Vergabe eines Namens finde ich super und es wäre toll, wenn Du uns weiterhelfen könntest.
Ich bin mir nicht sicher, ob Dir ein Savegame helfen würde, aber wenn ja, würde ich Dir eins vorbereiten.

Liebe Grüße

**Comment by Opa-Andre** [comment]
@Bluebirdonline & @CairoAmun : 

Bitte postet mal, welches Fahrzeug ihr "umbenennen" wolltet und ob das Umbenennen auch ohne angehängte Trailer, Gewichte etc. bei Euch nicht funktioniert. Zusätzlich dazu noch die vollständige log.txt Datei aus Eurem Spiel mit posten. Bei mir funktioniert das nämlich mit der Umbenennung ohne Probleme - hab es gerade nochmal mit der aktuellsten AutoDrive (1.0.3.6) - nicht die "Release"-Version, sondern die Dateien und Unterverzeichnisse im Ordner FS19_Autodrive der Masterdatei selbst gepackt und bei mir ohne Probleme getestet. Bleibt also noch herauszufinden, ob das Problem "fahrzeugspezifisch" oder Mod spezifisch ist.

Die Umbenennen Funktion macht dabei nur folgendes. In der Vehicles.XML des Savegames hat jedes Fahrzeug am Ende einen Abschnitt für Autodrive. Darin steht in der Konfigurationszeile standardmäßig der beim Kauf konfigurierte Name des Fahrzeuges, i.d. Regel die Motorkonfiguration (z. Bsp.: **driverName="1050"** beim Kauf eines Fendt 1000 mit 1050er Motorisierung). Die Umbenennen Funktion ermöglicht, diesen Eintrag zu ändern. Man könnte also theoretisch in die XML auch direkt reinschreiben: **driverName="Gugel Hupf"** - dann würde bei den AD-Statusmeldungen im Spiel dann eine Ausgabe in der Art stehen, wie "Der Fahrer von Gugel Hupf hat Feld 16 erreicht."

**Comment by Stephan-S** [comment]
@Opa-Andre Vielen Dank für deine Unterstützung hier in den Issues!
@Bluebirdonline &  @CairoAmun 
Ich habe nach dem letzten Release einen Bugfix hochgeladen der die Namensanpassung wieder ermöglicht hat. Aber ich wollte nicht extra dafür ein neues Release packen. Falls ihr sehen wollt was seit dem letzten Release passiert ist, könnt ihr die commits anschauen und wenn es dort noch neue Commits seit dem letzten Release gibt, lohnt es sich vielleicht wie @Opa-Andre beschrieben hat, sich selber die .zip Datei aus den aktuellen Sources zu basteln. Derzeit komme ich leider kaum dazu Bugfixes zu schreiben und daher gab es seitdem leider noch kein neues Release mit dem Fix

**Comment by Opa-Andre** [comment]
@Stephan-S Vielen Dank für die Aufklärung. Muss zugeben, dass ich mir die Commits selbst seit der letzten Version nicht angeschaut hatte. Bei mir hatte es ja funktioniert (nehme immer die letzte Version aus den Sources).

**Comment by Bluebirdonline** [comment]
Hi Stephan, leider ist es nach Einarbeitung der geänderten Funktionen genau so wie vorher. Habe auch geprüft, ob die Änderungen wirklich in der Datei sind. Trotzdem keine Änderung. Hier die eingearbeitete Änderung:

local adEnterDriverNameGui_mt = Class(adEnterDriverNameGui, ScreenElement);

function adEnterDriverNameGui:new(target, custom_mt)
    local self = ScreenElement:new(target, adEnterDriverNameGui_mt);
    self.returnScreenName = "";
    self.textInputElement = nil;
    return self;	
end;

function adEnterDriverNameGui:onOpen()
    adEnterDriverNameGui:superClass().onOpen(self);
	FocusManager:setFocus(self.textInputElement);
	if g_currentMission.controlledVehicle ~= nil and g_currentMission.controlledVehicle.ad ~= nil then
	    self.textInputElement:setTexts(g_currentMission.controlledVehicle.ad.driverName);
	    self.textInputElement:setText(g_currentMission.controlledVehicle.ad.driverName);
	    self.textInputElement:onFocusActivate()
	end;
end;
	
function adEnterDriverNameGui:onClickOk()
    if enteredName:len() > 1 then
	    if g_currentMission.controlledVehicle ~= nil and g_currentMission.controlledVehicle.ad ~= nil then            
	        g_currentMission.controlledVehicle.ad.driverName = self.textInputElement.text;        
	        AutoDriveUpdateNameEvent:sendEvent(vehicle);
	        AutoDriveUpdateNameEvent:sendEvent(g_currentMission.controlledVehicle);
	    end;
end;

**Comment by Gyffes** [comment]
Hi klinke mich  auch mal ein. Schaut doch mal issue #214 an. Da ist eine Version drin die  das schließen des Fensters für die Namens Vergebung behebt. 
Funktioniert im SP gut. 
Allerdings hat AD weiterhin ein Problem im MP die Statusmeldungen auf Deutsch anzuzeigen und die vergebenen Namen zu nutzen. 
Vielleicht hängt das mit eurem Problem zusammen.

Grüse

**Comment by CairoAmun** [comment]
Hallo Stephan, Opa-Andre und Gyffes,
vielen Dank für eure Hilfe. 
Bei mir haben die Tipps von Opa-Andre leider nicht funktioniert. Ich bin mir allerdings auch nicht sicher, ob ich die empfohlene Vorgehensweise richtig verstanden habe, so das ich nicht ausschließen kann, ob mir dabei ein Fehler unterlaufen ist oder nicht.
Die Zip-Datei die Gyffes in seinem Kommentar verlinkt hat, habe ich heruntergeladen und so, wie sie ist, in den Modordner kopiert. Jetzt funktioniert das mit dem Namen vergeben einwandfrei, auch in meinem Hauptspiel mit der Multimap und den ganzen anderen Mods, die ich installiert habe. Kein Fehler in der Log. Vielen Dank dafür Gyyfes.

Stephan, Dir möchte ich sagen, echt Klasse, was Du uns da mit Deinem Mod AutoDrive zur Verfügung stellst. Ich kann mir LS19 ohne AutoDrive überhaupt nicht mehr vorstellen.
Vielen Dank dafür.

**Comment by Bluebirdonline** [comment]
Genau, so klappt es. Soeben haben Cairo und ich das ausprobiert, auf Windows und auch auf dem MAC klappt es jetzt ohne Probleme. Danke für die Hilfe… 

Grüße an alle, die mitgeholfen haben…
