### ISSUE TITLE
Ausblenden / Deaktivierung der Anzeige der nächsten Fahrstrecke

### ISSUE THREAD

**Issue by Opa-Andre** [Stephan-S/FS19_AutoDrive#303]
Hallo @Stephan-S , 
ich habe mal zwei Fragen: 
1. Ist man "im Fahrzeug", wird einem während der Fahrt immer das nächste / aktive Streckenstück angezeigt. Bin auf der Suche, wo diese kurze weiße Linie angezeigt wird, um diese entweder ebenfalls auszublenden oder "durchsichtig" zu machen, damit man bei Videoaufnahmen während der Mitfahrt diese Linie nicht sieht. Leider finde ich dies nicht im Code, um diese "Debug-"Anzeige zu deaktivieren oder die Farbe auf durchsichtig zu stellen. Hättest Du da einen Tip für mich?
2. Würde Dir gerne eine PN zukommen lassen bzgl. eines anderen Themas (hat nicht direkt mit AutoDrive zu tun, jedoch viel mit dessen Funktionalität). Möchte das ungern hier öffentlich posten, jedoch habe ich keine Möglichkeit gefunden, Dir eine PN zu schicken. Daher hier mal meine Mailadresse, falls Deinerseits Interesse besteht: xxxx

Danke
Andre

**Comment by Stephan-S** [comment]
Hi,

zu 1.) Direkt im 'Haupt'-Script in der onDraw Methode: https://github.com/Stephan-S/FS19_AutoDrive/blob/17b6a16fc52ffc8c02ddfb8a3d90b76d05c3d539/FS19_AutoDrive/scripts/AutoDrive.lua#L415

zu 2.) Melde ich mich heute Abend mal auf deiner Mail-Adresse :-)

**Comment by Opa-Andre** [comment]
Danke Dir für beides, @Stephan-S 
Habe Dir am Montag gleich geantwortet - hoffe, die Mail ist nicht in Deinem Spam Ordner untergegangen.,

**Comment by Opa-Andre** [comment]
@Stephan-S : Vielen Dank für die Erweiterung der Funktionalität im Konfigurationsmenü... funktioniert spitze. Ich mach dann mal hier zu.
