### ISSUE TITLE
Editor Reihenfolge

### ISSUE THREAD

**Issue by Bandesss** [Stephan-S/FS19_AutoDrive#304]
Hallo habe die Strecken von Modhoster.
Nun wollte ich die Wiesen hinzufügen
WIe bekomm ich das hin, dass die Wiesen nach den Feldern kommen?
![20190731112850_1](https://user-images.githubusercontent.com/50829319/62201010-d4482c00-b386-11e9-911c-b4fb1b42dd27.jpg)
![20190731112922_1](https://user-images.githubusercontent.com/50829319/62201012-d4e0c280-b386-11e9-815d-5991548a4081.jpg)

[AutoDrive_Suedhemmern_config.zip](https://github.com/Stephan-S/FS19_AutoDrive/files/3450914/AutoDrive_Suedhemmern_config.zip)
Das muss doch irgendwie gehen

**Comment by Opa-Andre** [comment]
Hi Ronny,

bitte versuch doch zumindest mal bei Deinen Fragen einfach mal selbst darüber nachzudenken, und zumindest die Themen, welche "ähnlich" oder gar gleich sind, mal durchzulesen. Siehe zu Deinem Thema hier nach: #298

**Comment by Bandesss** [comment]
Das Hilft mir leider garnicht.
Ich wollte einfach, die Wiesen nach den Felder machen... wie auf meinem Bild beschrieben.
Danke trotzdem

**Comment by Opa-Andre** [comment]
Wie Du siehst, sind die Einträge alphabetisch sortiert. Also musst Du Dir was ausdenken dass die Bezeichnung Deiner Felder und Wiesen so von Dir benannt wird, dass sie im Alphabet aufeinanderfolgen.

Benennst also als Beispiel Deine Feldereinträge alle um - am Beispiel von  "43" -> "Abfahrer Feld 43" und die Wiese von "Wiese 1" -> "Abfahrer Wiese 1"

dann findest Du alle diese Einträge mit "Abfahrer" als Startwort gemeinsam gelistet, und da "Wiese" im Alphabet nach "Feld" kommt, kommen halt in der Liste erst alle Feldeinträge und danach die Wieseneinträge. Was ist daran so schwer eine "einheitliche" Namenskonvention zu erstellen und diese Namen in die XML Datei reinzuschreiben?

**Comment by Bandesss** [comment]
Vielen lieben dank für die ausführliche erklärung Danke
Erledigt
