### ISSUE TITLE
Course Editor Problem

### ISSUE THREAD

**Issue by gfa4711** [Stephan-S/FS19_AutoDrive#305]
Erstmal: super Mod, vielen Dank für Deine Mühe.

Da mir immer wieder Mal Fehler beim Einfahren passieren und das ausbessern im Spiel sehr aufwendig ist, habe ich mich sehr gefreut, dass es einen Editor gibt.
Allerdings gibt es da ein Problem mit der Map, die ich spiele (Saxonia 2019 v 1.1.1.0)
![Course_editor](https://user-images.githubusercontent.com/53525488/62215778-da9ad000-b3a7-11e9-9e68-61ca52d10704.png)

Wie man sieht ist die Karte total verschoben zu den Kursen. Außerdem  gehen auch Kurse oben aus dem Bildschirm heraus und man kann dort nicht hinscrollen. Das Drücken des "Four times Map" hat auch nichts gebracht.

Das png der Map scheint das korrekte Format zu haben (2048x2048), auch das Laden anderer Bilder hat nichts gebracht, an die Kurse die oben hinaus gehen, komme ich nicht ran.

Habe ich etwas vergessen einzustellen oder ist das ein Bug?

Config und png hänge ich an.

Viele Grüße
gfa4711

[AutoDrive_Saxonia_2019_config.zip](https://github.com/Stephan-S/FS19_AutoDrive/files/3452090/AutoDrive_Saxonia_2019_config.zip)
![Saxonia_2019](https://user-images.githubusercontent.com/53525488/62216757-a7594080-b3a9-11e9-865f-17ce9615213d.png)

**Comment by Bandesss** [comment]
Saxonia ist ne 4 Fach Map oder`?
Muss dann die Karte nicht 4.096x4.096 haben ?
Kann mich täuschen, versuch es mal ;)

**Comment by Stephan-S** [comment]
Hast du 'Four times Map' vorm Laden der Karte/Config angehakt?

**Comment by game455** [comment]
Darf ich hier mal fragen, wie der Course Editor überhaupt installiert/gestartet wird? ich bekomm ihn einfach nicht hin :(.

**Comment by gfa4711** [comment]
Ah, ok. Ich habe es immer vor dem Laden der Map angeklick oder danach und nicht vor dem Laden der Config.
Jetzt hat es geklappt. Vielen Dank!

> Saxonia ist ne 4 Fach Map oder`?
> Muss dann die Karte nicht 4.096x4.096 haben ?
> Kann mich täuschen, versuch es mal ;)

Ist eine 4-Fach-Map, aber mit 2048x2048 hat es geklappt.
Ich hatte es auch vorher mit 4096x4096 probiert, as das hatte nicht funktioniert.
