### ISSUE TITLE
Mp Bug

### ISSUE THREAD

**Issue by LsFreak13** [Stephan-S/FS19_AutoDrive#306]
Wenn ich autodrive auf meinem dedi server bei nitrado aktiviere Stürzt das spiel von jedem ab der den mp betritt dies ist ohne AD nicht der fall. Ich kann leider nicht mal die log zeigen da diese sich dabei löscht

**Comment by Stephan-S** [comment]
Hey, ohne log kann ich leider nicht viel machen. Wenn du für mich ein Log hast, schau ich mir das gerne mal an. Anonsten musst du mal probieren eine saubere Kursdatei aus dem Singleplayer auf dem Server savegame abzulegen
