### ISSUE TITLE
Missing function to assign a specific combine or field for the search

### ISSUE THREAD

**Issue by Th301** [Stephan-S/FS19_AutoDrive#309]
Hey there,

yesterday I had an issue with 2 combines working on fields next to each other. On both fields I had one driver to unload the combines. When one combine was full, the wrong tractor drove over to him, although he had another type of fruit on its trailer.

It would be nice, if there was a feature to assign a field, where the driver should search for the right combine, like it is in CP perhaps :)

Greetings
Theo

**Comment by Stephan-S** [comment]
Hey there,

this function exists. Just select the same target in the combine (e.g. 'Field 13') as you have for the unload driver. And then go into the AutoDrive settings and disable the 'Find driver' setting.

The 'Find driver' settings makes the combine look in a certain radius for unload drivers. If this is switched off, only drivers with the same assigned target will be used.

Best regards,
Stephan

**Comment by Th301** [comment]
Hey Stephan,

nice, thank you! One more thing about that: Which mode do I have to select in the combine?

"Use AD for unload/refill" in CP must not be activated?

Best regards,
Theo

**Comment by Stephan-S** [comment]
The mode in the combine doesn't affect anything. So no reason to change it :-)

And the CP setting can also be ignored or left deactivated. This is just for fieldwork where you can use it to pass to AutoDrive for unload/refill courses. But for combines, this isn't used as they wait to be unloaded.

**Comment by Th301** [comment]
Ah, ok. Thanks again! :)

I will try this out asap :)

**Comment by Th301** [comment]
Hello Stephan,

after testing what you told me, I can confirm this solution! :)

One thing that occurs than is: When "find driver" is switched to "no", the driver drives back to his initial position (e.g. field 13), after unloading the combine. This would not be an issue but it seems as if there is no usage of existing routes. the driver always leaves the field and gets often stuck in ditches. Is there a way to keep him on the field?

**Comment by Stephan-S** [comment]
I think you are mixing up two options here.
Check for 'Park in field'. This is used to determine if the driver stays on the field after unloading.

**Comment by Th301** [comment]
Yes, this is mixed up a bit. But it happend only since I started to use the manual search for combine. It makes no difference, if "park in field" is turned on or off.
