### ISSUE TITLE
help tutorial

### ISSUE THREAD

**Issue by ploughedfieldman123** [Stephan-S/FS19_AutoDrive#31]
is there any help tutorials on this also is it possible to have a English video tutorial as well

**Comment by mdbguy** [comment]
Looks like Iain Robson has just completed some videos: (hopefully the modhub source he references is official release by Stephan-S / developers)
Farming Simulator 19 - Autodrive, let's have a look -#FS19 https://www.youtube.com/watch?v=OGACcr-2GHU
Farming Simulator 19 - Autodrive - How to make a course https://www.youtube.com/watch?v=VHSPNRrUU_Y

**Comment by ploughedfieldman123** [comment]
is there any autodrive editors
