### ISSUE TITLE
KI-verkehr

### ISSUE THREAD

**Issue by andreasthu** [Stephan-S/FS19_AutoDrive#310]
Hallo stephan
Ich finde es toll,  das du für AD wieder zeit findest. 
Ich hätte eine Frage:
 und zwar, gibt es das problem, da ja der KI Verkehr in einem bestimmten umkreis um den AD Fahrer stoppt, und wieder weiterfährt, nachdem der AD fahrer diesen raduus verlassen hat.
Ist der AD fahrer jedoch am ziel angekolmme und hält, oder wird er manuell dealtiviert, bleiben alle KI Fahrzeuge, die in diesem umkreis gestoppt haben weiterhin stehen.
Hast du dafür schon eine lösung in aussicht, oder muss man damit leben?
Lg
Andreas

**Comment by Stephan-S** [comment]
Hallo Andreas,
tut mir Leid, da habe ich keine neuen Erkentnisse. Ich brauche dringend die Eigenschaft 'Helfer eingestellt' und diese sorgt fürs Ausschalten des Verkehrs.

**Comment by andreasthu** [comment]
Ja ok, das ist mir schon klar, das das während des Fahrens aktiv sein soll.
Nur eben wenn das Fahrzeug stehen bleibt, oder der AD Fahrer entlassen wird, könnte das "helfer eingestellt" ja wieder deaktivuert werden

**Comment by Knowen** [comment]
Wenn ich das richtig sehe, hat CP mitlerweile eine Kollisionserkennung. Kannst du da nicht mal reinschauen und für AD adaptieren?

**Comment by Stephan-S** [comment]
Erledigt :-)
