### ISSUE TITLE
'Share' mouse cursor with Courseplay and/or others

### ISSUE THREAD

**Issue by Stephan-S** [Stephan-S/FS19_AutoDrive#311]

**Comment by Bobster82** [comment]
Would love to see that, I always struggle with the mouse between cp and ad

**Comment by andreasthu** [comment]
ja, das wäre eine super sache,
lg
andreas

**Comment by Stephan-S** [comment]
Well, AD is now able to work with any mod that enables the mouse cursor. So from my side I see it as fixed and done.
