### ISSUE TITLE
Pick-up and delivery suggestion

### ISSUE THREAD

**Issue by Proximo303** [Stephan-S/FS19_AutoDrive#312]
Hello,  I have been testing around with Auto drive and been working on using over loaders to pull crop off the fields to waiting trailers.  The issue I am finding and wondering if something could be done, is that the carters I have set along the field are in pick-up and delivery mode.  This means they will only start if they are at 100%.   This is difficult to achieve all the time, when there are many different size combines, and several different sized over load wagons.  It would be nice to have the ability to set a start value at less then 100% to balance these incoming loads from the over loaders.

If your interesting in testing what I am doing here is my set-up.  
1) Combine, with or without courseplay, with auto drive set to request driver from Field Start point.
2) Over loader hooked to tractor at Field Start, already with pipe out, adjusted for height of trailer, in combine unload mode.  top line set to Field Start, second point to an unloading point.  I have found that these can not be that close, or the tractor will start to do a slow circle and say it gets stuck. 
3) A parallel course runs next to unloading point, with Loading point next to unloading point
4) Carting driver on the parallel course with pick-up delivery deliver option.  Top selection is set for loading point, second selection is to delivery point.   
5) I add a course for the over loader tractor to leave the unloading point and go back to the starting point, so it resets quicker.

**Comment by Th301** [comment]
Very cool idea! I will try out this, when the next fruit is ready!

Did you find any solution to do this with maize and a chopper aswell?
