### ISSUE TITLE
Accident

### ISSUE THREAD

**Issue by MacedonskyAlex** [Stephan-S/FS19_AutoDrive#313]
He goes around trees, but now he crashes into fences
![fsScreen_2019_08_03_20_05_37](https://user-images.githubusercontent.com/52257646/62414893-4a1ff200-b62a-11e9-9fe1-01313efb022a.png)
![fsScreen_2019_08_03_20_08_03](https://user-images.githubusercontent.com/52257646/62414902-5906a480-b62a-11e9-952d-fcc64fdbde66.png)

**Comment by MacedonskyAlex** [comment]
Downloaded an older version 1.0.3.6
In version 1.0.3.8 the Tractor is looking for long ways.

**Comment by Stephan-S** [comment]
Hey, so you only have that problem with the fence in version 1.0.3.8?
And what do you mean with He is looking for Long ways. Is it taking longer?

**Comment by MacedonskyAlex** [comment]
Yes, in fences crashes in version 1.0.3.8. And it began to take more time before arrival to the combine. Tractor rides zigzagging, the long way

**Comment by Stephan-S** [comment]
You can disable fruit avoiding. Second Option from the top on the right

**Comment by MacedonskyAlex** [comment]
All tried to change and disconnect, does not help

**Comment by Stephan-S** [comment]
Hey, I changed a lot regarding the path finding code. If this error is still happening to you, please reopen this issue. I am optimisitc here and close this for now :-)
