### ISSUE TITLE
Feature Request 

### ISSUE THREAD

**Issue by RUGhost** [Stephan-S/FS19_AutoDrive#315]
1. Adding cycle number for grain sell: If you use pickup and deliver mod to sell grain, it perform the cycle again and again untill it imptying the sillo. It would be nice if you add the option how many time i want AD to perform the cycle (like CP) for selling grain. 

2. Refill seed and fertilizer in seeder: Some seeder have compartment for both seed and fertilizer. But AD only fill one type either seed or fertilizer. I request to add the feature that AD refill both like CP. 

Many many thanks to you for your work which gives us the fantastic Autodrive.

**Comment by Knowen** [comment]
I would love to see both features in AD.
