### ISSUE TITLE
Autodrive Course Editor

### ISSUE THREAD

**Issue by auddie2015** [Stephan-S/FS19_AutoDrive#318]
Autodrive Course Editor will no longer open my courses. They are in game and work but the editor has no points and does not even load the map any longer.

I have no error log. All I get is the menu bar and no map area.

**Comment by Stephan-S** [comment]
Hey, could you send me the config file? Maybe there is Something irregular with the Name of the map or some of your destinations that is causing Problems for the config Parser of the Editor.

**Comment by auddie2015** [comment]
I think there was a problem with the config file structure. I was going to come in the morning and post that I have resolved it. I would have answered you sooner but I didn't check my mail until I was getting ready for bed. 

What I did was save a new temporary course file and then copied and pasted the waypoints and destinations into it where it normally resides and it loaded. The one that would not load had a lot of blank lines between each entry. I don't know if that is normal or not but the fields all looked the same other than the amount of blank lines. But what I could do is send you the fixed one. You might want to add it to your collection. It's complete and seems to work for both tractors and trucks, not including modded ones that might have wonky collision boxes.

I always do this... report something then fiddle with a while and manage to fix it. I hope sending you a working map course makes up for it!


[AutoDrive_Estancia_Lapacho_config.zip](https://github.com/Stephan-S/FS19_AutoDrive/files/3466061/AutoDrive_Estancia_Lapacho_config.zip)

![Estancia_Lapacho](https://user-images.githubusercontent.com/15572587/62440972-69994680-b720-11e9-9559-daea21780ec1.png)

**Comment by Saarlonz** [comment]
[AutoDrive_HOF_BERGMANN_config.zip](https://github.com/Stephan-S/FS19_AutoDrive/files/3469554/AutoDrive_HOF_BERGMANN_config.zip)

Hello, I have the same problem. I can no longer open and edit a map with the editor. I attach a test export config, I hope this helps to find the error.

**Comment by Th301** [comment]
In my case, the map-picture and the courses are shown in the editor but I can't select or delete or add anything. Any ideas?

**Comment by Saarlonz** [comment]
The problem with loading the map I could fix now, I can also edit the map again, but if I now add a navigation point is no longer alphabetically arranged but the last point created always appears at the end of the dropdwon, whether ingame or im editor created.

**Comment by auddie2015** [comment]
Saarlonz, I think it is an xml discrepancy after the update or maybe when saving the game, I have not figure it out yet. But here is how I fixed it.

I moved the one I could not load out of the savegame directory and reloaded my save gave. I started recording and drove a couple of meters then saved the game and exited the save. I opened the one I moved out of the folder and the new one that was created with the couple of meters I drove.

I use Notepad++ that allows you to collapse down the xml delimiters so that I had <waypoints> and <markers> both collapsed to make it easier to copy everything inside them. I selected them and ctrl-c. Then I went to the one I had just created and pasted ctrl-v over top of the <waypoints> in the new file. Saved it (should be in your savegame folder since the new one you made was there) and the points could once again be loaded.

I hope I explained this clearly. I am not good at instructions.

**Comment by auddie2015** [comment]
> In my case, the map-picture and the courses are shown in the editor but I can't select or delete or add anything. Any ideas?

I have not seen that problem. Could be java related? Did you try restarting the computer? Java can get wonky at times.

**Comment by Saarlonz** [comment]
I think error is due to the class <markerID>, this is not available after the first export. I once tried to export my course, then re-input then export again the then saved file in the export folder, I can edit again as usual.

**Comment by alpha117** [comment]
@Saarlonz , I can't open your Bergmann files either. So, can you upload the original PDA_map_h.dds file, the one in the map zip.  Thanks

**Comment by wlfheart** [comment]
Are there instructions on how to use this thing? where do i put it?

**Comment by alpha117** [comment]
leave it where you extracted the zip to. No instructions. 
1. Make sure the png is 2048X2048


Have a play around and you will find it easy to be honest

If you get stuck let me know

**Comment by alpha117** [comment]
Here is part of my Fenton Forest 4X so far

![image](https://user-images.githubusercontent.com/30005040/63184891-68391980-c050-11e9-95bf-394d932c2d75.png)

**Comment by auddie2015** [comment]
> Are there instructions on how to use this thing? where do i put it?

How I do it is that I copy the file that I want to edit or tweak because mistakes happen. 

I have my AutoDrive Course Editor folder on my desktop for easy access. You can put it anywhere of course. It's on your preference where.

When you look inside that folder, there is a subfolder named "src". This is the source code for the addon and unused but the folder for your maps is nested here as well - subfolder is "mapImages"

To get your map image to load in with your courses, you copy the PDA into this folder and name it exactly the name that AutoDrive uses for your map in the course file. To make sure you have the right name, you can open your course file in any text editor and scroll down into it a bit until you find **waypoints** - it is inside greater/less than symbols but they don't show for me here and I don't know to make them show. You will know you found it because below it is a huge amount of numbers.  Just above it will be the name of the map. In the case of my map that I posted earlier in the thread, it would be <**Estancia_Lapacho**>. Your map's PDA file, once copied into the mapImages folder, should be renamed to this with the tags. Once done, the editor should just load your map image for you from now on.

I hope I made this understandable. I am horrible with instruction. :-P

**Comment by alpha117** [comment]
The editor cannot use the 'PDA' picture from the map, as it is a DDS file and the editor can only use a PNG file. This PNG file has to be 2048x2048 in size. You have to convert the DDS to PNG. The PNG file can be named whatever you want. I name mine the same as the map (OakField,Fenton Forest etc etc)
The file that needs converting is 'pda_map_H.dds'

**Comment by auddie2015** [comment]
Yeah, I'm no good with instructions. Thanks for the correction. I knew I missed a step just not where.
