### ISSUE TITLE
Feld Linie

### ISSUE THREAD

**Issue by Fuzzy86** [Stephan-S/FS19_AutoDrive#319]
Hallo Stephan!
Hätte da mal so einen Gedankengang. 
Ich Spiele auf der Saxonia Map und bei manchen Feldern (wenn ich z.B. mit CP Stroh einfahre) findet der Abfahrer dann mit AD den weg nicht. Jetzt habe ich um das Feld mit der Linie was für beide Seiten ist nen Kurs rund ums Feld gemacht. "Problem" ist nur das auch andere Abfahrer jetzt dann auch diesen Weg nutzen um an ihr Ziel zu kommen. Kann man da evtl. eine 3. Farblinie einbinden die nur für Feldränder ist? Super wäre dann noch wenn sie auch für beide seiten befahrbar ist. Dann könnte der abfahrer wenn er im Feld ist sich nach dieser z.B. farblich Roten Linie orientieren um auf das Strassennetz zu gelangen. 

Würde mich über eine Antwort freuen

Lg

**Comment by Opa-Andre** [comment]
Bin mir jetzt nicht sicher, ob ich Dein Problem genau verstanden habe... aber wenn, dann braucht man dafür keine 3. Art an Linien. Wenn ein Feld Hindernisse hat (z. Bsp. Bäume / Bachläufe etc. welche die Gefahr bieten, dass der Abfahrer sich darin verfangen kann, dann mache ich es bei solchen Feldern wie folgt:

1. An der Stelle, wo die Straße vorbeifährt, hab ich normalerweise eine "kurze Abzweigung" näher ans Feld heran, wo der Wartepunkt der Abfahrer ist. Nach dem Wartepunkt fahre ich diese Strecke noch 2-3 Punkte weiter, bevor ich wieder auf die Straße zurückkehre, um das normale Streckennetz zu nutzen. 

2. Jetzt stelle ich mir eine gedachte Gerade vom Abfahrerpunkt zum gegenüberliegenden Feldrand vor (Teile das Feld damit sozusagen in 2 Hälften). Z. Bsp. der Abfahrerpunkt ist Mittig im Westen des Feldes, dann denke ich mir die Gerade zum Osten des Feldes.

3. Vom gedachten "Zielpunkt" im Osten, fahre ich nun zwei Richtungsstrecken ein am Feldrand. Eine vom Osten über den Norden zum Westen im Gegenuhrzeigersinn und eine vom Osten über den Süden zum Westen im Uhrzeigersinn. Die beiden Strecken schließen dann 1-2 Punkte nach dem Abfahrerpunkt an der Abfahrerstrecke an und führen über diesen Weg wieder auf die Straße.

Damit ist sichergestellt:
1. Das ein Abfahrer, der z. Bsp. ein Feld mit CP düngt und nun mittels AD neuen Dünger holen will, von seiner Position aus den kürzeren Weg nimmt, um am Feldrand nicht in Hindernissen hängen zu bleiben. 
2. Da die beiden Streckenstarts (Feldrandstrecken) an ihrem Anfang nicht von einer Straße aus eingebunden sind, werden die Feldrandstrecken nicht durch andere Abfahrer "mißbraucht".
3. Durch die Einbindung der Enden der beiden Feldrandstrecken 2 Punkte nach dem Abfahrerhaltepunkt, können Sie bei Unterbrechung einer automatischen Abfahrt auch manuell dazu genutzt werden, dass ein Abfahrer wieder "auf den Weg gebracht wird", ohne dass der evtl. am Haltepunkt zusätzliche. nächste Abfahrer den "Abfahrts-" Weg blockiert.

Ich hoffe, dass macht es etwas verständlich.

**Comment by Stephan-S** [comment]
Hey, probier doch mal bitte die neuesten Versionen von Courseplay und AutoDrive aus.
Courseplay nutzt jetzt die bereitgestellte Funktion und schickt AutoDrive mit Pfadsuche los, so wie es auch beim Drescher abladen genutzt wird. Damit sollten sich solche Probleme eigentlich gelöst haben.

Bei negativem Feedback gerne wieder aufmachen!
