### ISSUE TITLE
Preference when bifurcation

### ISSUE THREAD

**Issue by PromGames** [Stephan-S/FS19_AutoDrive#32]
I have been setting up tracks and my question is related to recalculation.

I understand how is recalculating and gets the best (shortest?) track to reach the desired waypoint.

Sometimes, a auxiliar road to a farm and exit is shorter than the principal road, what is happening is that is going through the shortest path, means through a farm.

Is there any way to avoid it. All tracks are the same, and I do not know if the order you make the bifurcation affect to the preference for recalculation.

Thanks

Prom

**Comment by Stephan-S** [comment]
Hey, you are right with the assumption that the "fastest" route is calculated by looking for the shortest one. Internally, the recorded network is handled as a graph structure and the weights between the nodes are given by their euclidian distance in the game world.
Changing how the weights are calculated is not something I want to do without being sure that it wont affect the way, the typical user expects the pathfinding to behave.
So I could for example come up with several ways how the user could setup special weights for certain links but that would complicate the gui/button mapping into a level I feel not comfortbale imposing on every user. Also I would have to store the weights in the xml file as well, which again adds to time and process requirements each time the network is loaded or stored.

What I am currently considering after your question, is to add the option of weighing target points with an additional x meters. This could help in avoiding these auxiliary roads, as they should usually contain a target point I assume.

The next thing I would like to add to AutoDrive is a settings page to configure certain parameters to the user's preference.
What I could see there are two settings:
   1. Toggle option: Avoid pathing through target locations
   2. Value: Maximum detour in meters (e.g. 100m or 1000m)

These two values can easily be added to the xml file and are also rather simple to respect in the recalculation procedure.

Any thoughts from you on this suggestion? :-)
Thank you for your input! This was not on my todo list before

**Comment by PromGames** [comment]
Hi, from the options you said:

Set a value for minimum distance to be taken in consideration for recalculation
If the system would be able to discriminate the distance among nodes to make recalculation and we know we need shorter distance among nodes when making detours, we could try that, but this means a lot of effort in designing and changing paths.

A toggle option to avoid going through target locations.
This sounds very good, why instead a toggle button for selecting yes or no to select some type of nodes, will be better if we can mark with some XML attribute that the target is an allowed pass-through (pass_on) or not (pass-off), and then, we can force every recalculation to get only through the pass on targets. This can be easy and editable in-game easily just deleting and creating Target marks

Other possibility is to mark the first node of the detour to be avoided in case of two options, this also could work doing some edit ingame.

Prom
