### ISSUE TITLE
script bug V 1.0.3.9

### ISSUE THREAD

**Issue by koppi99** [Stephan-S/FS19_AutoDrive#320]
hi Stephan, 

bekomme einen fehler in der log und es lässt sich nichts mehr steuern. beim abkippen modus sobald ich umschalten möchte..
/My Games/FarmingSimulator2019/mods/FS19_AutoDrive/scripts/AutoDriveHud.lua:599: attempt to concatenate local 'text' (a nil value)
2019-08-08 23:12 Error: Running LUA method 'draw'.

 gruß xDeekay

**Comment by Stephan-S** [comment]
Hey, danke für die Meldung.
Ich habe nie abgefangen, das möglicherweise gar kein Abladepunkt gewählt ist.
Hast du einen neuen Spielstand angefangen? Oder einen neuen Zielpunkt erzeugt?
Schick mir gerne mal deine AutoDrive config falls du diese noch von vor dem Vorfall gespeichert hattest.

Vielen Dank und viele Grüße,
Stephan

**Comment by koppi99** [comment]
Gerne! Ja alles neu wollte nur das update testen :) hab die config nicht gespeichtert.. ich lade mal das neue update von dir rein :) 
Gruß

**Comment by koppi99** [comment]
habs jetzt die V 1.0.4. getestet. geht leider auch nicht. 
wenn ich auf das "P" drücke kommt ein script fehler. 
/My Games/FarmingSimulator2019/mods/FS19_AutoDrive/scripts/AutoDriveInputFunctions.lua:247: attempt to index a nil value
2019-08-09 08:40 Error: Running LUA method 'update'.

**Comment by Stephan-S** [comment]
Hast du schon eine Parkposition definiert? Bzw auf diesem Spielstand schon einen Zielpunkt eingefahren ?

**Comment by koppi99** [comment]
nein noch keinen punkt definiert... ich hab nur ein paar punkte gemacht dann auf Parken gedrückt..

**Comment by Stephan-S** [comment]
Ok. Da hast du die Schwachstelle im System gefunden :D
Probier's doch nochmal wenn du ein Ziel definiert hast.
Ich behebe dann aber noch deinen gefundenen Fehler für den nächsten Patch :-)

**Comment by Stephan-S** [comment]
Achso. Erst mit rechter Maustaste auf Parken drücken um das Ziel einzuspeichern als Parkposition. (Nachdem du dann endlich eins erstellt hast^^)

**Comment by koppi99** [comment]
es kommt auch ein script fehler wenn ich garnichts gemacht habe und dann auf den modus abladen komme da geht mein HUD weg. der log: 
/My Games/FarmingSimulator2019/mods/FS19_AutoDrive/scripts/AutoDriveHud.lua:556: attempt to concatenate local 'text' (a nil value)
2019-08-09 16:23 Error: Running LUA method 'draw'.

**Comment by Stephan-S** [comment]
So, der sollte sich ja eigentlich erledigt haben :-)
