### ISSUE TITLE
Сombine is too close

### ISSUE THREAD

**Issue by MacedonskyAlex** [Stephan-S/FS19_AutoDrive#321]
If the combine stands as shown in the screenshot 1 , AD does not go to it and shuts down. If the combine drive away a little further, the AD will begin its work. screenshot 2 
![fsScreen_2019_08_09_13_10_29](https://user-images.githubusercontent.com/52257646/62771944-fe949a80-baa6-11e9-8089-e5438f46b12f.png)
![fsScreen_2019_08_09_13_14_32](https://user-images.githubusercontent.com/52257646/62772191-8e3a4900-baa7-11e9-8625-61743e5e2edb.png)

**Comment by Stephan-S** [comment]
Well yeah, what do you expect? AutoDrive is Not an  artificial intelligence. So it requires some room to maneuveur. And at the start, it needs a few meters to get going. And in your second Image, you See exactly how much Space. And do you notice that this is exactly the Spot where your Combine ist standing in, in the First Image? :-)
So you could try to Setup the map Marker more aligned with the field borders, to prevent this in the Future.

Best regards,
Stephan
