### ISSUE TITLE
The Parking

### ISSUE THREAD

**Issue by Squibbb** [Stephan-S/FS19_AutoDrive#323]
Would be nice to see the parking, could be saved for each Individual Vehicle on exit, so you don't have to redo them when you restart the same game

**Comment by haamic** [comment]
Hallo Stephan,
bei mir bleibt auch das Parken-Ziel nicht dauerhaft gespeichert.
Nach Spielstand laden sind alle Parken-Ziele nicht mehr auf den Fahrzeugen vorhanden.
die "parkDestination" nummern stehen korrekt in der vehicles.xml, werden aber wahrscheinlich beim Laden nicht wieder den Fahrzeugen korrekt zugewiesen.
Gruss Micha

**Comment by haamic** [comment]
funktioniert mit Release 1.0.4.1, danke
