### ISSUE TITLE
Spiel absturz

### ISSUE THREAD

**Issue by gerrit0476** [Stephan-S/FS19_AutoDrive#324]
Hallo Stefan,

wenn mit der rechten MT auf die Parkfunktion klicke stürzt das Spiel ab. Folgendes steht in der LOG.
C:/Users/XXXXX/Documents/My Games/FarmingSimulator2019/mods/FS19_AutoDrive/scripts/AutoDriveInputFunctions.lua:239: attempt to index a nil value
Error: Running LUA method 'update'.

**Comment by koppi99** [comment]
hi gerrit, ja ist bei mir auch. 
wurde hier auch schon geschrieben. 
https://github.com/Stephan-S/FS19_AutoDrive/issues/320

**Comment by gerrit0476** [comment]
Ah ok sorry
Dann schließe ich den Post
