### ISSUE TITLE
Feldrandcontainer wird nicht als Füll-Trigger erkannt

### ISSUE THREAD

**Issue by Th301** [Stephan-S/FS19_AutoDrive#326]
Moin,
mir scheint es so, als wenn AD die Feldrandcontainer, egal ob Giants oder Mod, nicht als Fülltrigger erkennt. 

Hat jemand ähnliche Erfahrungen? Und evtl. eine Lösung parat?

Grüße
Th30

**Comment by Stephan-S** [comment]
Cleaning up old issues.
