### ISSUE TITLE
4X map not loading

### ISSUE THREAD

**Issue by alpha117** [Stephan-S/FS19_AutoDrive#328]
Hi Stephan,

I can't get the 4X maps to load in the editor

Thanks

**Comment by Martinnygaard** [comment]
I am playing on Fenton forrest  (and now fenton forrest 4x) and i cant get any of them to load in the editor.

It is propperly me, but i have tried loading the PDA map first and then the config file, and i have tried the other way arround.

For the standard maps that comes with AD editor, it works fine.

**Comment by Roby1164** [comment]
I was able to load it, reducing the size, but then they bust the coordinates ...

**Comment by alpha117** [comment]
Yep, it will load the PNG, but as you have said the co-ordinates of the network get busted

**Comment by Stephan-S** [comment]
Have you selected the checkbox "Four times map" before loading the config? And what size are you png files? Expected size is 2048x2048

**Comment by Roby1164** [comment]
Ok, I solved, the "Four times map" checkbox was missing

**Comment by alpha117** [comment]
fantastic, great work

**Comment by alpha117** [comment]
Will there be a update with the fix?


Thanks

**Comment by Stephan-S** [comment]
There is no fix, you simply have to check the checkbox before loading the config :-)

**Comment by alpha117** [comment]
There is no checkbox

**Comment by Roby1164** [comment]
![Screenshot_5](https://user-images.githubusercontent.com/24955554/62975796-84a04080-be1b-11e9-854b-ca3d5455e44b.jpg)

**Comment by alpha117** [comment]
Yep, pressing that also
