### ISSUE TITLE
Triggerproblem Produktionen

### ISSUE THREAD

**Issue by altbier1** [Stephan-S/FS19_AutoDrive#329]
Autodrive übersieht oder ignoriert in der Version 1.0.4.0 bei mir diverse Lade- und Abladetrigger. 
Bei den Ladetriggern muss ich öfter der Ladevorgang mit R starten, sowohl bei den GC-Produktionen als auch bei den "alten" Farmer Schubi Produktionen.
Bei Abladetriggern fährt Autodrive darüber hinweg (die Trigger werden am Abladepunkt von CP erkannt und es wird abgeladen). Verkaufstrigger werden erkannt, Ladetrigger in Ställen z.B. Milch auch. 
Ich bin von 1.0.3.8 auf 1.0.4.0 gewechselt, bei 1.0.3.8 gab es mit den "alten" Farmer Schubi Produktionen und den Ställen keine Probleme
Evtl hilft dir der Tread https://github.com/Courseplay/courseplay/issues/4049 bei der Problemlösung weiter

**Comment by Stephan-S** [comment]
Kurze Frage: Hast du die Trigger/Gebäude neu aufgestellt?
Da AutoDrive ja nur beim Spielstand einmal nach Triggern sucht, ist das ein typisches Problem. Ansonsten muss ich mal schauen was sich da geändert haben soll. Eigentlich hat sich in der Version ja nur geändert. das bei der Auswahl Saatgut/Dünger beide Trigger genuttz werden um Sähmaschinen aufzufüllen.

**Comment by altbier1** [comment]
Das sind alte Produktionen / stehen schon länger. 
Kevin98 schreibt im anderen / verlinkten Thread dass es besser wäre die Trigger aus der TriggerManager.lua herauszulesen (Für die GC Trigger als Antwort von Kevin der LS-Modcompany
g_company.triggerManager -> Da werden alle Trigger registriert. (utils/GC_TriggerManager.lua)
Liegt in der Hauptmod drin) 
hoffe die Info hilft  weiter, keine Ahnung ob es für den Spielstand eine Datei mit allen Triggern gibt; wäre in diesem Fall sehr hilfreich. Bei Start einlesen und das Problem wäre behoben - wäre zu schön um da / war zu sein

**Comment by Stephan-S** [comment]
Falls du einen Spielstand für mich hättest, am Besten mit eingestellten AutoDrive Fahrern, wäre das eine riesen Hilfe. Dann könnte ich mich gleich ans Debuggen begeben ohne noch Produktionen aufzustellen und vollzupackem, Trecker hinzufahren, etc.
Gerne auch mit Links zu Mods die es nicht im Modhub gibt, so dass ich es auch schnell ans Laufen bekommen kann :-)

**Comment by haamic** [comment]
Hallo Stephan,
 ich häng mich da mal mit rein. Habe ein Testspielstand erstellt. Savegame 14 auf Felsbrunn mit einem Global Company Silo. Abladen funktioniert , Laden geht nicht. Weder im Modus "abholen und abliefern" noch "abholen".
vielleicht hilft dir das. hier der link, dieser enhält auch benötigte GC-mods

https://www.magentacloud.de/lnk/dziAHQ2k

Gruss Micha

**Comment by haamic** [comment]
Eben hat courseplay die GC trigger hinzugefügt. 

https://github.com/Courseplay/courseplay/releases/tag/6.01.00275

**Comment by Stephan-S** [comment]
Danke schon mal für deine Hilfe. Ich probiers mir morgen mal anzuschauen. Bis dann

**Comment by Marko230** [comment]
@haamic 
@Stephan-S 
Das Befüllen des Trailers funktionier leider nicht... Man muß bei jeder Produktion zum beladen des Anhängers die R Taste drücken... Automatisch beladet CoursePlay nicht ...

siehe Courseplay  #4049
MfG Marko

**Comment by haamic** [comment]
Ja leider, auch mit dem neuesten CP Update (275) kann noch nicht automatisch geladen werden.

**Comment by haamic** [comment]
neuer link wenn du testen magst, Stephan
https://www.magentacloud.de/lnk/dziAHQ2k

hab auch ein Testkurs von CP drin, geht bisher auch noch nicht mit aktueller v6.01.00276

**Comment by Stephan-S** [comment]
wunderbar, pünktlich zum Feierabend :-) Ich schaus mir gleich mal an

**Comment by Stephan-S** [comment]
erledigt :-)

**Comment by Marko230** [comment]
@Stephan-S 
habe es gerade getest und funktioniert  ( Abholen Kompost > Belieferung Düngerherstellung )
                                                              ( Abholung Dünger > Belieferung Saatgutherstellung )
auf der NfMarsch 2.2 fix
vielen Dank

**Comment by haamic** [comment]
super arbeit

**Comment by Stephan-S** [comment]
@altbier1 Wie sieht es bei dir aus? Gibt es noch Probleme? Ich habe nur die Global Company Trigger hinzugefügt. Wenn  die alten 'Farmer Schubi Produktionen' noch Probleme machen, schick mir wie gesagt gerne mal ein Savegame mit den Mods, dann schau ich da noch nach.

**Comment by altbier1** [comment]
Danke läuft wieder wie zuvor - super arbeit und Danke für deine Mühe
GC und Farmer Schubi lassen be- und entladen.

**Comment by Stephan-S** [comment]
Na wunderbar. Dann mache ich hier mal zu :-)
