### ISSUE TITLE
Dedicated server

### ISSUE THREAD

**Issue by Nokiafyr28** [Stephan-S/FS19_AutoDrive#332]
I have a Dedicated server and it say there is a Issues
-- | --
XML file 'AutoDrive_Ravenport_init_config.xml' is too big. Size 0.34 MB (max. 0.25 MB)
 I have version 1.0.4.1

**Comment by Stephan-S** [comment]
Don't worry. This is just a warning and can be ignored.
The server is just complaining about an unusually large xml file.
The recorded network is simply a bit larger than your typical vehicle xml files, which is quite reasonable.

Best regards,
Stephan
