### ISSUE TITLE
Server hängt sich auf

### ISSUE THREAD

**Issue by Bandesss** [Stephan-S/FS19_AutoDrive#333]
Hallo habe die Kurse von der Marsch
Leider hängt sich mein Server auf. 
Wie kann ich rausfinden, an was das liegt
[AutoDrive_NF_Marsch_V2_2_oG_config.zip](https://github.com/Stephan-S/FS19_AutoDrive/files/3492971/AutoDrive_NF_Marsch_V2_2_oG_config.zip)
[log.txt](https://github.com/Stephan-S/FS19_AutoDrive/files/3492973/log.txt)

Gruss Bandes

**Comment by Stephan-S** [comment]
Servus,
dein Logfile enthält keine Fehler, also ist das wohl nur der Teil nach dem Absturz und seit dem Neustarten des Spiels. 
Wenn du mir ein Logfile vom Fehler zukommen lässt, schau ich gerne nochmal drüber.

Grüße,
Stephan

**Comment by Bandesss** [comment]
Ich habe nun den Fehler, es passiert beim Importieren kurz dann hängt der server
Danke für deine Hilfe
[log.txt](https://github.com/Stephan-S/FS19_AutoDrive/files/3499089/log.txt)
