### ISSUE TITLE
einige fragen

### ISSUE THREAD

**Issue by andreasthu** [Stephan-S/FS19_AutoDrive#334]
Hallo stephan
du hast mit der v1.0.4.1 ja einige tolle funktionen eingebaut, leider versteh ich einiges davon nicht.
- kann man ein eingestelltes "Parkziel" wieder ändern, wie?
- was ist die "erweiterte Zieleingabe per Tastatur" ?
-einige befehle sind neu in der Tastenbelegung,
AD: abfahrer rufen, z.b. - und wie funktioniert das? 

ev. eine anregung für die zukunft:
- eine tastaturbelegung für "automatisch verbinden Start" und "automatisch verbinden Ende" wäre beim kurseinfahren sinnvoll.
- wäre schön, wenn man ziele auch in ordner packen könnte, die durchscrollbaren zielliste wird ziemlich lange.

sorry, aber ev gibts ja eh eine readme oder sowas, ich finde sie leider nicht.
lg
andreas

**Comment by kleba78** [comment]
1. Ziel für  das Fahrzeug auswählen und wieder mit der rechten Maustaste bestätigen, einfach die erste Bestimmung des Parkziels wiederholen, die erste Eingabe wird dann überschrieben.
2. Habe ich auch nicht gefunden, allerdings kann man  im LS19 die Tastaturbelegung frei einstellen, einfach unter Einstellungen von LS19 gucken, da findest du auch deine gewünschten Optionen.

Gruß kleba

**Comment by Saarlonz** [comment]
AD: Abfahrer rufen ist nicht neu. Hiermit kannst du eine wartenden Abfahrer frühzeitig z.b zu deinem Drescher rufen zwecks umladen.

**Comment by Saarlonz** [comment]
Normal sollte es funktionieren wenn du mit dem Drescher das Rohr ausfährst und dann den wartenden Abfahrer rufst.

**Comment by andreasthu** [comment]
ok, habs jetzt, derdrescher muss stehen.
lg
andreas

**Comment by Stephan-S** [comment]
Ja genau. Er muss stehen und das Rohr draußen haben.
AutoDrive berechnet ja einen statischen Pfad zum aktuellen Drescherort und fährt ihm nicht dynamisch hinterher, daher habe ich eine Prüfung ob der Drescher auch schon stillsteht eingebaut.
