### ISSUE TITLE
Request: Durchlaufzähler reduzieren

### ISSUE THREAD

**Issue by kleba78** [Stephan-S/FS19_AutoDrive#335]
Hey,

wirklich erstaunlich cool, wie sich AD entwickelt hat - der Durchlaufzähler ist ein cooles Feature, kann man den Zähler in der GUI nach jedem Durchlauf -1 zählen , so dass man erkennen kann - wie viele Fahrten noch zu machen sind.

Trotz deinem Fokus auf Themen neben LS19 und AD - wirklich ein toller Job.

Gruß kleba

**Comment by Stephan-S** [comment]
Hey, 
ich habe intern 2 Variablen. Den herunterzählenden Zähler und die Einstellung die in der GUI angezeigt wird. Diese wird ja bei jedem Neueinstellen des Fahrzeugs wieder übernommen, daher habe ich sie getrennt gespeichert.
Hältst du es für sinnvoller daraus eine zu machen? Wenn ja, soll nach der letzten Tour wieder zurück auf 1 oder auf unendlich gesprungen werden?

Grüße,
Stephan

**Comment by kleba78** [comment]
Hi,

für Verkaufsfahrten und Versorungungsfahrten macht es aus meiner Sicht einmal Sinn einzustellen, wir oft er verkaufen soll  - die noch offenen Fahrten (noch nicht erledigt) - bleiben dann relevant. Wie oft ich ihn Ursprünglich mal eingestellt hab, sind durch veränderte Silo Stände dann irrelevant.

Ich würde dafür plädieren, das du die Variablen wieder zusammenlegst oder zumindest die Anzeige in der GUI so änderst das du "eingestellte Touren - gefahre Touren " rechnest, wenn man es dann so kann, dann behälst du dir ja vielleicht auch die Flexibilität.

Danach sollte er wieder auf unendlich gehen - der Job ist erledigt.

PS: Mir kommt gerade die Idee, das es natürlich mega wäre, wenn man optional oder über die grundlegenden Settings einstellen könnte, das AD danach wieder auf die ParkPosition fährt. Diese Features zu koppeln, wäre glaube ich ein echter Bringer.

Gruß´Sven
