### ISSUE TITLE
Refilling from a Multi Silo

### ISSUE THREAD

**Issue by alpha117** [Stephan-S/FS19_AutoDrive#337]
If you have an implement that requires 2 products, then AD will not refill from a 'multi product' silo

Thanks

**Comment by FforFarm** [comment]
I think that a MultiSIlo will only let you refill of the type there is allready in your implement.

Lets say you have 2 tanks - 5000L of fertilizer and 5000L of seed.
When you have filled the fertilizer, and want to change to seed, then the silo see that you allready have fertilizer and will not allow to choose another type.

This is also the case if you do it manually. Therefore i think it is a bug in the Multi silo scripts. :-)

**Comment by alpha117** [comment]
Many Thanks
