### ISSUE TITLE
How to join two twoway roads

### ISSUE THREAD

**Issue by redrummed1** [Stephan-S/FS19_AutoDrive#338]
How do you link twoway roads together, once I record one near the existing one it only gives me the one way option to join,

**Comment by alpha117** [comment]
You then have to go to the other end of the one way link and join it, then it creates the 2 way road way

**Comment by Stephan-S** [comment]
Thanks @alpha117

**Comment by redrummed1** [comment]
Not getting this. OK here's what I am doing
1, entrance to farm is narrow so I record 2way route in to farm yard, creating various locations. Refill points etc. 

2. I loop around in the yard and try to join two-way route.  All I get is the one way green line when I toggle connection???

**Comment by alpha117** [comment]
Correct, you have to move the tractor so it's red line is on the arrow end of the green node. Now you can make the 'second' join back to the base of the green arrow. Now you have a 2 way node.

Or do it the editor, which takes seconds.

**Comment by redrummed1** [comment]
Thank you, got very frustrating.  Another stupid question where do i find the application for editor, i do not see it in the folder???
I have pds converted. 
Thanks

**Comment by alpha117** [comment]
https://github.com/Stephan-S/FS19_AutoDrive

**Comment by redrummed1** [comment]
Whats the file name??? I go in to the autodrive editor and i do not see an application!

**Comment by alpha117** [comment]
AD.jar

**Comment by redrummed1** [comment]
![Capture](https://user-images.githubusercontent.com/23707135/63179167-6cab0580-c043-11e9-98c7-60e0bcb77cf2.JPG)

Ye didnt make this easy??  :)

**Comment by alpha117** [comment]
You should have this
![image](https://user-images.githubusercontent.com/30005040/63179251-9f54fe00-c043-11e9-91fc-be7d03b44bb7.png)
 not sure what you have there to be honest

**Comment by alpha117** [comment]
did you download from here?

![image](https://user-images.githubusercontent.com/30005040/63179381-df1be580-c043-11e9-8485-0034cc5de38d.png)

**Comment by redrummed1** [comment]
Ah yes for some reason the AD .jar is showing up as a rar file in mine. what do  i need to do

![Capture33](https://user-images.githubusercontent.com/23707135/63179774-c8c25980-c044-11e9-83d3-28b78a63ae80.JPG)

**Comment by alpha117** [comment]
extract the rar file, what do you get?

**Comment by redrummed1** [comment]
![Capture44](https://user-images.githubusercontent.com/23707135/63180097-70d82280-c045-11e9-94bd-3f709103d288.JPG)

**Comment by alpha117** [comment]
delete them. Have you got Java installed?

That looks like your problem. 
Install Java and then let me know how it goes

**Comment by alpha117** [comment]
from here
https://java.com/en/download/help/download_options.xml

**Comment by redrummed1** [comment]
Got it, cheers man, 
Greatly appreciated.

**Comment by alpha117** [comment]
Cool, any issues with the editor then let me know

**Comment by Stephan-S** [comment]
@alpha117 As always, thank you very much. You are a life saver here :-) Will work on bugs now :D

**Comment by alpha117** [comment]
No problems, I'll help where I can, this allows you to work on the real issues and move AD forward, without worrying about support issues
