### ISSUE TITLE
A Question from curiosity 

### ISSUE THREAD

**Issue by RUGhost** [Stephan-S/FS19_AutoDrive#339]
If you don't mind i just want to know why ai trafic car get stuck when AD driver detect any ai car? In cp, ai car does not stuck when cp driver detect ai car.

**Comment by Stephan-S** [comment]
Thanks for getting me back to this topic.
I included it in the newest release. Please check it out and give me some feedback :-)

**Comment by andreasthu** [comment]
works perfekt, thanks
lg
andreas

**Comment by RUGhost** [comment]
A lot of thanks
