### ISSUE TITLE
4X map course loads incorrectly on the map

### ISSUE THREAD

**Issue by alpha117** [Stephan-S/FS19_AutoDrive#341]
The network should be bottom left not where the editor loads it.
I have attached both files so you can have a look

many Thanks
[AutoDrive_Fenton_Forest_4X_By_Stevie_V1_42__config.zip](https://github.com/Stephan-S/FS19_AutoDrive/files/3498549/AutoDrive_Fenton_Forest_4X_By_Stevie_V1_42__config.zip)

![image](https://user-images.githubusercontent.com/30005040/62971331-71847500-be09-11e9-9851-9a694f37c607.png)

**Comment by Roby1164** [comment]
You have to resize the file, at 2048 X 2048

**Comment by alpha117** [comment]
I've tried 2048 x 2048 and also 4096 x4096, still not working

**Comment by alpha117** [comment]
This is at 4096 x 4096
Netywork should be down where the arrow points to

![image](https://user-images.githubusercontent.com/30005040/62976544-be217d80-be14-11e9-82e6-c16f894acf89.png)

**Comment by alpha117** [comment]
attached is the 2048 x 2048 version
[AutoDrive_Fenton_Forest_4X_By_Stevie_V1_42__config.zip](https://github.com/Stephan-S/FS19_AutoDrive/files/3498921/AutoDrive_Fenton_Forest_4X_By_Stevie_V1_42__config.zip)

**Comment by alpha117** [comment]
Finally sorted. issue was that the PDA DDS file was 4096x4096.  Converted it to 2048x2048 DDS then converted it to a 2048 PNG and all loaded Ok...phew!!

![image](https://user-images.githubusercontent.com/30005040/62980712-30975b00-be1f-11e9-89da-d2fbccc2c28e.png)

**Comment by hiddit** [comment]
> Finally sorted. issue was that the PDA DDS file was 4096x4096. Converted it to 2048x2048 DDS then converted it to a 2048 PNG and all loaded Ok...phew!!
> 
> ![image](https://user-images.githubusercontent.com/30005040/62980712-30975b00-be1f-11e9-89da-d2fbccc2c28e.png)

do you maby have the right PNG file and you AD config off this map for me? 
i can't get it in the right format, if i follow your steps it still doesn't match up.

**Comment by Roby1164** [comment]
![Fenton_Forest_4X_By_Stevie_V1_42_](https://user-images.githubusercontent.com/24955554/65240965-b8d5e380-dae2-11e9-9304-b40861376318.png)

**Comment by Roby1164** [comment]
https://drive.google.com/open?id=1vEBimfEladVm_XOzroDopETYKB_4HBrO
