### ISSUE TITLE
Combine unloading - tractor is circling around waiting point

### ISSUE THREAD

**Issue by raxtor** [Stephan-S/FS19_AutoDrive#342]
I have trouble with "Combine unloading". When tractor reached waiting point for searching a combine than starts turn around waypoint.. I think he should be only waiting on specific point, not move around.
It seems last working version for me is 1.0.3.1

Similar trouble I have with "Pick and Delivery" when empty trailer is going through pick point.

My scenario is 1 overloader for combines which is delivering grain to truck. Truck after full loading continues to silo. But it doesnt work for me. and version 1.0.3.1 gives me error:
```
FS19_AutoDrive/scripts/AutoDriveDriveFuncs.lua:308: attempt to index a nil value
2019-08-14 02:48 Error: Running LUA method 'update'.
```
and crashed game.

![fsScreen_2019_08_14_00_30_49](https://user-images.githubusercontent.com/831266/62982021-40b53780-be2b-11e9-9651-01c4ce7ebcbe.png)

**Comment by Stephan-S** [comment]
Alright, three things:

Make Sure you are recalculating routes and that there is a Connection from field to unload Point!

Please attach a Screenshot of your AutoDrive settings and your config file, so I can Check this Out myself.

Make Sure you are using the latest Version :-)

**Comment by raxtor** [comment]
Ok.. PickUp and Delivery seems ok in 1.0.4.4 but Combine unload doesnt work..
I attached whole game save 
[savegame2.zip](https://github.com/Stephan-S/FS19_AutoDrive/files/3500254/savegame2.zip)

![fsScreen_2019_08_14_09_19_09](https://user-images.githubusercontent.com/831266/63002218-af1ee780-be75-11e9-9e73-e6ad1a438c58.png)

**Comment by raxtor** [comment]
I found it happens where there is no active combine. When there is hired combine worker and 100% full grain bin, it works fine... I am not sure if it works as was intendant...
Also I noticed when you turn off AD on field (crash to combine etc) than tractor cant find way back to course from field because distance is too long. Would be nice whn you start AD on filed he will switch to mode "waiting on filed" instead of going back to start point, if isnt fully loaded.

Do you plan combine unloading on the fly?

**Comment by Stephan-S** [comment]
Well, that was a nasty bug.
The vehicle didn't stop properly because the unload point was so close that the condition for releasing the brakes already kicked in and didn't really check for the current state :-) Now the overloading mode you build should work I hope :-)



> Do you plan combine unloading on the fly?

Not currently. I want it to be stable so you basically can run the game as spectator. Until we reach that state, I don't think I will go for that route yet.

**Comment by raxtor** [comment]
Many thx, great job!
