### ISSUE TITLE
Traktor bleibt vor dem zugewiesenen Parkplatz stehen

### ISSUE THREAD

**Issue by iljarogoff** [Stephan-S/FS19_AutoDrive#343]
![fsScreen_2019_08_14_21_59_40](https://user-images.githubusercontent.com/21023840/63052296-41a7a100-bedf-11e9-8fcf-6374558c3c06.png)
Habe einen Punkt in einer Halle als Parkplatz definiert. Leider fährt der Traktor nicht bis zum Wegpunkt sondern bleibt vorher schon stehen - und steht damit im Weg. Ist das so gewollt?
Noch eine Frage: habe gelesen, dass man einem Fahrzeug einen Namen zuweisen kann... nur wie geht das?

**Comment by altbier1** [comment]
Interessante Idee, mit Durchfahrhallen sehr praktisch. Stellplatz zuweisen und nach der Arbeit wird aufgeräumt...
Ich vermute Autodrive erkennt eine Kollision des Unterstandes

**Comment by Stephan-S** [comment]
Hey, da hat @altbier1 sicher recht. Da schlägt die Kollisionserkennung an. Du kannst probieren diese auszuschalten, falls du keinen Verkehr eingeschaltet hast, denn da ist sie zwingend nötig.

Oder probier es mit einem geraderen Anfahrweg. So schaut er ja scheinbar auf den Pfeiler.
Du kannst dir übrigens mit F5 die Box anzeigen die er zur Kollisionserkennung nutzt anzeigen lassen.

Zum Namen vergeben musst du eine Taste in den Spieleinstellungen dafür zuweisen.

**Comment by iljarogoff** [comment]
Kollisionserkennung ist ausgeschaltet, daran lags nicht. Habe dann die Zufahrt zum Parkplatz weiträumiger gestaltet, dann funktioniert es, danke.
Dabei ist mir aufgefallen, wenn man den Wegpunkt löscht, der auf den Parkplatz zeigt, bleibt die Zuordnung als Parkplatz beim Fahrzeug erhalten. Lässt man dann das Fahrzeug zum Parkplatz fahren, stürzt das Spiel ab. Wäre super, wenn man die Zuordnung als Parkplatz löschen könnte, wenn man dem Fahrzeug keinen neuen Parkplatz geben will. Oder automatisch löschen sobald der entsprechende Wegpunkt nicht mehr existiert.

**Comment by Stephan-S** [comment]
Sollte im nächsten Release gefixed sein. Ich mach hier schon mal ganz optimistisch zu :-)
