### ISSUE TITLE
Not Finding Combine

### ISSUE THREAD

**Issue by PsyberMind** [Stephan-S/FS19_AutoDrive#345]
I'm not sure if I'm missing something here.. I'm trying to set up an AD Course to offload a combine. But the Offloader won't find the combine. It's a relatively large field, and based on other issues of the same nature, It would APPEAR as though it's too far a distance.

Now, is there a way to change that limit to beyond 300m? 

If not, I'm not exactly sure what you mean by setting the combine to start at the field.. Here's the layout..

I'm on County Line Map, have a premade course that someone else created.. It seems to work just fine. I've run other AD functions on it. I'm on Field 10, which is fairly large.. Using a Semi/Trailer combination for the offload. Courseplay is running the field with the harvester. 

You stated in other reports that AD Looks for an extended pipe, but Courseplay will not extend the pipe unless there is an offloader in close proximity to it (Unless I'm missing something)

And I apologize if this has been repeated.. I've been scouring the web, and sadly the only Video Tutorials for using the two together are not in english.. I'm attaching my AD Config just in case you need it.. 

[AutoDrive_County_Line_Seasons_FS19_config.xml.txt](https://github.com/Stephan-S/FS19_AutoDrive/files/3504281/AutoDrive_County_Line_Seasons_FS19_config.xml.txt)

**Comment by PsyberMind** [comment]
Bah, I was using an older version of CP.. Updated it, and it worked just fine

**Comment by Stephan-S** [comment]
Alright, glad you found the problem so fast.
Two things though, I wanted to clarify:
The unloader will find the combine either by distance <300m if 'Find driver' option is set to true or by assigning the same start location in the combine as you have selected for the unloader.
So both should for example have "Field 13" or "Field 12 unloader" selected.

And then there is the option to select how long he is allowed to calculate a path. It's deault to a factor of 1, but for really large fields, he might run into problems. But you can notice that this is the problem, if AutoDrive shuts down and throws a messge in the log.

**Comment by uded** [comment]
@Stephan-S - can you explain the combine finding logic a bit more? I am using three combines on a 140ha field with CoursePlay, and unloaders have a bit of a struggle finding the combine. I thought that if it is within the boundaries of the field then they will do so, but my results are mixed. I would appreciate some more details on how to work with that.

**Comment by Stephan-S** [comment]
https://github.com/Stephan-S/FS19_AutoDrive/wiki/3-AutoDrive-modes:#351-basics

**Comment by uded** [comment]
Found the reason - after saving and loading the game again AD goes back to default destination for me. Combines go back to a default whatever location and I do not set them back to the field they're on. Got it, now it seems better, I will observe it and try to figure out the perfect setting for me. Thank you, @Stephan-S!
