### ISSUE TITLE
Abfahrer beläd nicht

### ISSUE THREAD

**Issue by Patrick007-de** [Stephan-S/FS19_AutoDrive#348]
Hallo 

bin heute auf Auto-Drive gestoßen und habe mir viele YT-Videos drüber angeschaut …. dann natürlich runtergeladen und ausprobiert … soweit so gut … habe dann aber mitbekommen das er bei Silos so seine Probleme hat bzw an seine grenzen kommt … 
Spiele die Hof Bergmann und dort ist ein großes Multifrucht silo auf dem Nebenhof … wenn ich dort jetzt ein Ziel setze weiß er nie ...soll er abladen oder aufladen … und vorallem welche frucht … oder liegt es gar an mir … 

mfg

**Comment by haamic** [comment]
Wird das denn in den YT-Videos ordentlich erklärt? Welche AD-Version nutzt du? Eigentlich klappt das gut. Es sei denn dieses Silo auf der Karte ist zu speziell. Kenne die Karte nicht nicht. AD brauch schon paar Infos, was  ab- oder aufgeladen werden soll. 
Wie verhält sich AD denn am Silo? Bleibt stehen? Welchen Modus und Ziele hast du eingestellt. Die Reihenfolge ist wichtig bei den unterschiedlichen Modi.

**Comment by haamic** [comment]
Habs mal getestet, meinst du das grosse Silo ? Hab ein 3 min Video gemacht. 
Laden und Entladen, funktioniert.
hier der Link, wenn du schauen magst (download ca 220MB)
https://www.magentacloud.de/lnk/DIigH4yF

**Comment by Patrick007-de** [comment]
Ja ich meine da große ... ich schau mal rein 

Gesendet mit der GMX Mail App

Am 15.08.19 um 19:47 schrieb haamic
