### ISSUE TITLE
Global Company Triggers

### ISSUE THREAD

**Issue by alpha117** [Stephan-S/FS19_AutoDrive#350]
The vehicle stops short and will not load

![image](https://user-images.githubusercontent.com/30005040/63105985-c6df9400-bf79-11e9-8328-a273fa9061e1.png)

This example is using the Diesel manufacturing. 

Stop AD and manually drive to the correct position and all is good
![image](https://user-images.githubusercontent.com/30005040/63106260-5edd7d80-bf7a-11e9-97cb-8b6d6e0da537.png)

**Comment by altbier1** [comment]
May be the loadingpoint is to close and the trigger of the container is outside. 
I think the loadingpoint should be one or two steps / points futher - for example where the first frontwheel is 
You use the dieselproduction fron mali?

**Comment by Stephan-S** [comment]
Hey @alpha117 I can recreate this with your savegame from earlier.
It is a problem with the collision detection. Or rather with the GC buildings. They use a big collision box all around the trigger. If you press F5 you can actually see them yourself.
If you disable vehicle collsion it will work just fine for the GC triggers.

I will see if I can make some contact to the GC devs and see if we can do something about it.
Easisest solution on my part would be to disable collision detection near triggers but that should really be addressed by the GC team.

**Comment by alpha117** [comment]
cool, how do I disable vehicle collision?

**Comment by Stephan-S** [comment]
last option in the AutoDrive settings

**Comment by alpha117** [comment]
thanks..should have known that one!

**Comment by alpha117** [comment]
this will also affect the AI traffic?

**Comment by Stephan-S** [comment]
yeah. As I said. This is not ideal :( But GC buildings use the same collision mask for some reason
