### ISSUE TITLE
Abfahrer wartet nach Abladen

### ISSUE THREAD

**Issue by fischbesuch** [Stephan-S/FS19_AutoDrive#351]
Hallo
Meine Abfahrer laden am Trigger ab und bleiben dann stehen, bis ich weiter fahren anklicke ? An was liegt das ?

Danke für Antwort

**Comment by Frodo65** [comment]
Hi
Habe seit dem Update auf die 1.0.4.5 das selbe Problem

Der Anhänger wird am Getreide Silo abgeladen und fährt nicht weiter.
Bei der 1.0.4.3 klappte das

Die Map  ist die porta Westfalica

Gruß Frank

fischbesuch <notifications@github.com> schrieb am Do., 15. Aug. 2019, 18:04:
