### ISSUE TITLE
ITRunner Pack

### ISSUE THREAD

**Issue by SirGarnet** [Stephan-S/FS19_AutoDrive#352]
Hi Stephan,

ich habe das [ITRunner Pack](https://www.farming-simulator.com/mod.php?lang=de&country=de&mod_id=49828&title=fs2017) von GIANTS drauf.

Ich habe den Anhänger angehangen, aber keine Container drauf. Da ich zum Shop wollte und meinen neuen Container holen. Leider fährt AutoDrive den Anhänger nicht ohne Container drauf.

**Logfile:**
`2019-08-15 21:02 [...]/mods/FS19_AutoDrive/scripts/AutoDriveTrailerUtil.lua:204: attempt to index field 'attachedContainer' (a nil value)
2019-08-15 21:02 Error: Running LUA method 'mouseEvent'.
2019-08-15 21:02 [...]/mods/FS19_AutoDrive/scripts/AutoDriveTrailerUtil.lua:204: attempt to index field 'attachedContainer' (a nil value)
2019-08-15 21:02 Error: Running LUA method 'mouseEvent'.`

Gruß Flow

**Comment by Stephan-S** [comment]
Hi,
kann es sein das du eine sehr alte Version nutzt? In der aktuellen ist das abgefangen und sollte nicht vorkommen.

Grüße,
Stephan

**Comment by SirGarnet** [comment]
Hi,

ja da hast du recht, diese veralteten Mod-Seiten tse...

Schade das du dein Repo so aufgebaut hast wie es ist, da kann ich deinen Unterordner für AD nicht direkt in LS19 auschecken :-D

Danke für den schönen Mod, die schnelle Hilfe, mach weiter so und close
Gruß Flow
