### ISSUE TITLE
Not only 1.0.4.6 issues

### ISSUE THREAD

**Issue by raxtor** [Stephan-S/FS19_AutoDrive#354]
- Park on field seems not working from this version. Tried both options, none work. Tractor always go back to start position after unloading.
- Also I have feel tractor is going from field always to start point instead of unload point when reached unload fill level. Than he is traying unloading point for  short time, going back to start point and if he reached unloading fill level, is going again to unload point and unload. I am not sure if it is working as was intended or if it is only "Auger wagon case"...?
- Performance drop when way is calculated. There is displayed some color grid.
![fsScreen_2019_08_16_02_24_41](https://user-images.githubusercontent.com/831266/63137640-5d8e6e00-bfd7-11e9-8f7e-688afdb8fddf.png)
- AD reverse manuver after unloading needs to be a bit longer now when pipe position over trailer was fixed. When I use CP for field work, combine is doing maneuver to make place for unloader (pipe over crop). After unloading combine is going back to original path, but crashing into vehicle set.
![fsScreen_2019_08_16_01_23_06](https://user-images.githubusercontent.com/831266/63137552-06889900-bfd7-11e9-9ad6-e7ecf9788ba1.png)
- Unloader is lost on field after AD off/on and cant reach XY point.
![fsScreen_2019_08_16_01_57_41](https://user-images.githubusercontent.com/831266/63137740-af36f880-bfd7-11e9-9b74-d05150d8aab7.png)
- Unload fill level doenst work for mode "Pickup and Deliver". Always waiting for 100%.
- From some reason tractor sometimes leave field when is going from combine to trailer.
![fsScreen_2019_08_16_05_53_02](https://user-images.githubusercontent.com/831266/63143140-3cd11300-bfed-11e9-8714-7ed84bbf9d15.png)
- Course network is not saved when "Update ways". I think it shoudnt be stored only when game is saving but always when you call "Update ways". Maybe I did mistake somewhere, but I lost part of ways when game crashed so maybe it works correctly.
- Text cursor in GUI for "Save waypoint" is not active and u have to click to field and than you can set name. Its only annoying, not bug :-) I thought reset button will remove waypoint name but it not working as I want. No possibility how edit/remove name of waypoint? Just only by course edit?
- Would be nice use flat triangle instead of arrow as direction of course. For more complicated crossroads construction it will improve orientation imho.
- Not sure if AD is able refuel vehicle, but would be nice have such possibility if course is going through fuel trigger. AD would start refueling if fuel is under 25% or so. Or maybe another skill for "Pickup and Deliver" mode.

Thats all! Auger wagon and his pipe works perfectly now!

**Comment by Stephan-S** [comment]
First of all, thank you so much for your feedback here. Really, really helpful!

>     * Park on field seems not working from this version. Tried both options, none work. Tractor always go back to start position after unloading.

Fixed.

>     * Also I have feel tractor is going from field always to start point instead of unload point when reached unload fill level. Than he is traying unloading point for  short time, going back to start point and if he reached unloading fill level, is going again to unload point and unload. I am not sure if it is working as was intended or if it is only "Auger wagon case"...?

Could not really replicate this. But your field exit strategy decides how he leaves the field.

>     * Performance drop when way is calculated. There is displayed some color grid.

Fixed

>     * AD reverse manuver after unloading needs to be a bit longer now when pipe position over trailer was fixed. When I use CP for field work, combine is doing maneuver to make place for unloader (pipe over crop). After unloading combine is going back to original path, but crashing into vehicle set.

Increased reversing distance and also adjusted the pipe distance again.

>     * Unloader is lost on field after AD off/on and cant reach XY point.

Are your unloader points connected to the rest of the AutoDrive network? Otherwise he might not find a way from the closest waypoint he starts from.




>     * Unload fill level doenst work for mode "Pickup and Deliver". Always waiting for 100%.

Never has, but will probably include a new setting for this in the next days. Good suggestion!


>     * From some reason tractor sometimes leave field when is going from combine to trailer.

Yeah, but he finds it's way, right? :p 



>     * Course network is not saved when "Update ways". I think it shoudnt be stored only when game is saving but always when you call "Update ways". Maybe I did mistake somewhere, but I lost part of ways when game crashed so maybe it works correctly.

This is actually by design. I only want the network to be permanent if you save the game. If you want a backup of the current network, click the export icon on the Hud to create a new file in the export folder.

>     * Text cursor in GUI for "Save waypoint" is not active and u have to click to field and than you can set name. Its only annoying, not bug :-) I thought reset button will remove waypoint name but it not working as I want. No possibility how edit/remove name of waypoint? Just only by course edit?

Damn, I can't find out how to set the focus on the text element :( But I changed the reset button to delete the waypoint number text.



>     * Would be nice use flat triangle instead of arrow as direction of course. For more complicated crossroads construction it will improve orientation imho.

Hm, a flat triangle. Will see if I can play aroundd with that idea, but no promises, sorry :-)

>     * Not sure if AD is able refuel vehicle, but would be nice have such possibility if course is going through fuel trigger. AD would start refueling if fuel is under 25% or so. Or maybe another skill for "Pickup and Deliver" mode.

I would see it as Auto refill when fuel level below x% and I know there is a waypoint close to a refuel trigger. But will take some time. Would you mind writing a seperate issue for that idea so it won't get lost?

So thanks again!

**Comment by raxtor** [comment]
Wow, fast and furious! 
I am going check new version and than I will let you know... maybe in new topic...

**Comment by raxtor** [comment]
I did new issue #364 so I cant test all changes which were fixed...
-  Also I have feel tractor is going from field always to start point...
- Unloader is lost on field after AD off/on....
_I will test it again, cuz I used separated network for auger wagon.. I thought I dont need completely connected network when I dont use other waypoints from main network... can you confirm that its needed?_
- From some reason tractor sometimes leave field....
_Not always, fences are big problems_
- Text cursor in GUI for "Save waypoint" is not active
_Ask CP devs, they had same problem when started use FS GUI text input._
- Would be nice use flat triangle... 
_Not every route uses asphalt, there is grass etc. so flat triangle could be more visible for ground level. I like more route over tractor. Flying rout has a bit less contrast and there it could help too._
- Not sure if AD is able refuel vehicle, but...
_new issue #365_

You can close it after you will read it.... I will test it again after more stable version... 1.0.4.7 seems has hard isssue.. but what I was able test... Field Parking wasnt working... normal trailer and auger wagon tested..

**Comment by Stephan-S** [comment]
>     * From some reason tractor sometimes leave field....
>       _Not always, fences are big problems_

Fences should be avoided by the pathfinder. Are you having issues with that? If so, on which map? So I can check if the collision triggers are properly defined for these fences or if this is an issue in the path finder.



>     * Also I have feel tractor is going from field always to start point...

Can't confirm. Is this a new issue for you? What are your settings for field exit, parking and unload level?



>     * Text cursor in GUI for "Save waypoint" is not active

Yeah, thanks. I found a solution now, before reading your comment :-)



>     * I will test it again, cuz I used separated network for auger wagon.. I thought I dont need completely connected network when I dont use other waypoints from main network... can you confirm that its needed?

AutoDrive always starts from the closest/most suitable (by heading) point it can find and starts from there to the destination. If your auger path is disconnected it can't find a way.
I might build the pathfinder into that mode in time, but for now it will stay that way :-)

**Comment by raxtor** [comment]
I had troubles with fences on County Line Map 2.0.. will open issue when I will have troubles again.. was filed 17 and 22 what I remember when tractor left filed and tried find way aorund.. but forgoet it.. I will open new if needed...

For field I use default, so I dont know what is default :-) sure when I have trouble I am trying other possibilities... but I will test it again and will open also new issue when it comes again...
