### ISSUE TITLE
Trailer too far forward to unload harvester 1.0.46

### ISSUE THREAD

**Issue by eddiem54** [Stephan-S/FS19_AutoDrive#359]
As can be seen, harvester can't unload. Happens with various standard trailers
![fsScreen_2019_08_16_19_17_13](https://user-images.githubusercontent.com/2765885/63189384-c7e8f200-c05b-11e9-80b8-3f4974a5052a.png)

**Comment by Obsiana2019** [comment]
I have the same Problem, after update to Version 1.0.47.

Ich habe das selbe Problem nach Update von 1.0.4 auf 1.0.47

**Comment by eddiem54** [comment]
Working OK now 1.0.47
