### ISSUE TITLE
Startpunkt Automatik

### ISSUE THREAD

**Issue by LS19PEEB** [Stephan-S/FS19_AutoDrive#36]
Hallo, wäre es möglich den Startpunkt bei einer Strecken Aufnahme automatisch an einer nächstliegenden Punkt anzuhängen, so das man nicht mehr vorhandenen Strecken-Netz mit dem neue Strecke noch extra verbinden muss.

**Comment by Stephan-S** [comment]
Ich werde es als Option ermöglichen. Vielleicht beim nächsten Release. Die Idee finde ich gut, aber ich wollte das nicht zwangsläufig machen. Mit dem neuen Einstellungsmenü kann ich es aber ja an und abwählbar machen.
Auf jeden Fall eine sinnvolle Idee!
