### ISSUE TITLE
Wegpunkte löschen ?!?

### ISSUE THREAD

**Issue by kleba78** [Stephan-S/FS19_AutoDrive#360]
Hey,

ich habe immer wieder das Problem, das wenn ich Wegpunkte löschen und dann auch neu berechnen, quasi alle auf den Fahrzeugen gespeicherten Wegpunkte ( im HUD eingestellt ) nicht mehr Grün hinterlegt sind und die Fahrzeuge auch nicht mehr an diesen eingestellten Wegpunkt fahren, sondern an einen anderen.

Mir kommt es vor als wenn der eingestellte Wegpunkt verrutschen würde, eben auf einer früher oder später eingefahren Wegpunkt.

Gleiches Verhalten erkenne ich auch bei den Parkplätzen. Kann das jemand bestätigen?

**Comment by alpha117** [comment]
If you delete a waypoint(node), then you will 'break the network'. You have to join the 'break' back to the network either in game or in the editor.

**Comment by Stephan-S** [comment]
Hast du die Wege neu berechnen lassen, nachdem du ein Ziel/einen Punkt entfernt hast?
Ansonsten kann das durchaus so passieren.

**Comment by kleba78** [comment]
Ja, das hab ich getan und habe es nun noch einmal ausprobiert. Es verhält sich nicht logisch.

Ich habe auf der Map eine ganzes Netz eingefahren. Nun und einen Node habe ich zur Destination "Verkauf" gemacht - nun stelle ich aber fest, dsa der Verkauf leider zu früh oder zu spät ist und möchte ihn löschen. ( Nodes inklusive Destination ) wird gelöscht. Das unterbrochene Netz ( unverbundene Nodes ) verbinde ich wieder über die HUD und setze einen schon bestehenden Wegpunkt wieder auf Destination Verkauf. Lasse alles neu durchrechnen und kann den Verkauf wieder anfahren.

Jetzt das Problem, bei allen Fahrzeugnen bei denen bereits eine Destination eingestellt ist (und sogar aktiv angefahren wird) und allen die eine Parkposition eingestellt haben verschiebt sich diese, anhand der Speicherreihenfolge würde ich vermuten.

Das ist reproduzierbar.
Gruß Sven
