### ISSUE TITLE
Request: automatisches Parken - nach Beendigung von Durchlauffahrten

### ISSUE THREAD

**Issue by kleba78** [Stephan-S/FS19_AutoDrive#361]
Hey,

ich hatte das schon einmal so als nebenbei Idee hier erwähnt, wäre es möglich das Fahrzeug nach Beendigung seiner Durchlauffahrten, wieder auf seine Parkposition zurück zuschicken?

Gruß Sven

**Comment by Stephan-S** [comment]
Sorry, zuviel Aufwand für zu wenig Nachfragen danach :(
