### ISSUE TITLE
Filling Planter with seed and fert

### ISSUE THREAD

**Issue by alpha117** [Stephan-S/FS19_AutoDrive#363]
Guys, I must be missing something, but I cannot get this to happen. 
Any pointers would be good

Thanks

**Comment by alpha117** [comment]
Morning All
Here is what I've also tried.  On the left is 'liquid fert refill', center is 'fert refill' and right is 'seed refill'

I've setup the 'liquid fert refill' target, after some trial and error that will work,BUT it does not continue automatically after the refill has completed. 

it will not fill up seeds as you can only select one refill type in the GUI.

Stephan, would be possible to allow a vehicle to drive through this network and 'auto refill' ALL types?
Thanks

![image](https://user-images.githubusercontent.com/30005040/63208421-c22af500-c0cb-11e9-92fd-67dad7fa1ba0.png)

**Comment by Stephan-S** [comment]
Yeah sorry, I actually wasn't aware that there are seeders with liquid fertilizer tanks, so I only check for the combination of 'seed' and 'fertilizer' (solid). They should work in the current version though.
I will update this to include liquid fertilizer as well.
If you have a moment, could you verify though that the combination 'seed' and 'fertilizer' is working. You just have to select one of these filltypes and have a vehicle that is 100% full when both types are loaded. Thank you

**Comment by alpha117** [comment]
Sure will, stand by

**Comment by alpha117** [comment]
Perfect, well nearly. Refill seed selected at filltype, it also filled fert also, BUT did not go onto the seed refill automatcally, had to press continue. When it got to the seed refill, finished and then automatically continue on network. Nor sure what would happen if fert refill was AFTER seed refill on network

![image](https://user-images.githubusercontent.com/30005040/63209555-5ac87180-c0da-11e9-9a54-a71d84f12852.png)

**Comment by alpha117** [comment]
This test was to have 'seeds' full  and fert empty, then drive refill course. it drove straight through but filled a small amount (see below) and continue on course to the field

![image](https://user-images.githubusercontent.com/30005040/63209930-391db900-c0df-11e9-9ea3-c52e7616864a.png)

**Comment by alpha117** [comment]
Final test was Fert full and seed empty, then drive refill course. This time stopped at FERT but again had to press continue to move onto seed refill, refilled seed and continued onto field

**Comment by alpha117** [comment]
retested with the fixes and ALL works PERFECTLY...great work.  

Just need to test the liquid fert

**Comment by Stephan-S** [comment]
Phew, that's a release :-) Thanks for the feedback!

**Comment by alpha117** [comment]
Liquid Fert also fixed

**Comment by raxtor** [comment]
How it works whn I need load Seed in place 1 and Fertilzer in place 2 lets 100m from place 1?

**Comment by alpha117** [comment]
I would have thought it should work. Have you tried it?

**Comment by raxtor** [comment]
Not yet... so load point is last trigger? and AD autodetect fill triggers during way?

**Comment by alpha117** [comment]
yes, so if you have FERT > Field > Seed then I don't thing it would work.

**Comment by alpha117** [comment]
u have FERT>>>>>>>>>>>>>>>>>>>seed  >>>>>>>field it should work

**Comment by raxtor** [comment]
well, go try it.. rather I asked if ability exits... some list of AD skills would be nice :-)

**Comment by alpha117** [comment]
make sure you use the correct mode in the GUI

**Comment by alpha117** [comment]
This might help:

As you say refilling, I assume you want to fertilize / lime your field…
First make sure you're using the actual versions of the CP & AD mods.
You already should have created an AD network created with defined named network points to your field and to your refilling station. In AD select Mode 5 (loading course - its the next one after "combine unload"). In the upper line you select your stop point near the field, in the lower line you select your loading station (for example fertilizer sellpoint or silo) and depending of your used equipment what you want to refill (fertilizer, lime, seeds, etc.). Now start running the AD course. If your vehicle attachments (seeder, fertilizer etc.) are currently completely empty, it will drive to the refill Station, refill and then drive to your field Destination. If it's not empty, it will drive directly to your field.
When arriving at the field destination, AD will wait - so this time you'll have to switch off AD.
Now use CP to create your field work route. Before starting the course, select in the CP Options menu that you want to use AD for refilling.
Now start the CP fieldwork course.
What will happen:
CP is doing the fieldwork. As soon as your implements are empty, CP will "internally" make a note of the actual fieldwork position and will switch on AD automatically. AD will then check for the closest AD waypoint in its driving network and steer directly to it. As it reaches the network it then will drive its own route from it to the refill Station, refill and drive back to the field destination. Then it will signal that it reached "the end" of its course. CP will then take over again, driving straight from this point to the before noted fieldwork position and continue with the fieldwork.
Two notes:
1.	Make sure in your AD driving network that you are able to reach the network from any place / location in the field without obstacles being in your way. The same of course applies for the way from the fieldborder (AD field destination point) to any location within the field.
2.	Plan your setup on beforehand because when you run into problems (for example obstacles in the way during the time while CP is using AD for refilling) then stop CP first, before stopping AD. Otherwise if you just stop AD manually, CP will interpret this as "refill done" and will use a straight way from the current position of your vehicle back to the current field work points.(OPA-ANDRE)

...AD +CP works perfectly together, what a great combination

**Comment by alpha117** [comment]
> well, go try it.. rather I asked if ability exits... some list of AD skills would be nice :-)

What skills to you mean?

**Comment by raxtor** [comment]
![fsScreen_2019_08_17_18_35_46](https://user-images.githubusercontent.com/831266/63214849-ef07f800-c11d-11e9-9064-04f45c474b23.png)
Not working for me... in house seed trigger just open seeder cover and tractor continues in course to filling point

**Comment by alpha117** [comment]
Are you using the latest 'updated' version. Stephan made the changes a few hours ago, just before I tested it

**Comment by raxtor** [comment]
sure..1.0.4.8

**Comment by alpha117** [comment]
You are a version in front of me already...lol.  better update

**Comment by raxtor** [comment]
btw.. would be nice when we are talking about seeding... imagine this scenario... seeder is filled and coming back to field...tahn AD script will start CP and CP doing his job till some tank needs refill.. than CP stops his job and easy just start AD for refil course .-) isnt seems so hard...

**Comment by alpha117** [comment]
It's nearly there already, see my post above of how to get them working together, currently you have to 'start them off, but after that they will work together, doing what you said

**Comment by raxtor** [comment]
but its too far from auto seeding :-)

**Comment by raxtor** [comment]
Just a part from AD whn there would be ability start CP for that vehicle would be nice.. Maybe than guys from CP imolments similar bridge to AD

**Comment by alpha117** [comment]
1. Start   AD refill course
2 When back at field stop AD
3. Start CP, making sure 'use AD' is selected in CP GUI

When seed runs out CP will return to correct point  and auto start AD refill.  
Refill returns to field, auto stops and auto start CP who will continue where it left off.


This auto process will continue until field work is complete.

What else do you want it to do?

**Comment by raxtor** [comment]
> making sure 'use AD' is selected in CP GUI
I dint know CP supports AD.. wow!

**Comment by alpha117** [comment]
Again you must be running the latest development version of CP

**Comment by raxtor** [comment]
yep.. good news! I didnt read your previous article too closely..THX!

**Comment by raxtor** [comment]
But is possible refill seeder/fertilizer from 2 different sources or I made something wrong?

**Comment by alpha117** [comment]
Here is the 'link' that makes CP and AD work together
![image](https://user-images.githubusercontent.com/30005040/63215161-7eaba780-c11a-11e9-8af7-5d353d213dad.png)

Yes, my tests were from two different points (see above)

**Comment by raxtor** [comment]
[savegame1.zip](https://github.com/Stephan-S/FS19_AutoDrive/files/3512236/savegame1.zip)
well, can you try ma savegame? Its [CountyLine 2.0](http://modsfile.com/jc53k1467gvs/FS19_CountyLine_Seasons.zip.html)

I found it in CP already, but thx.. will start playing with it soon...

**Comment by raxtor** [comment]
Definitely it seems I can't fill my Liquid fertilizer in any mode...
"R" key for manual filling is active but AD doesnt fill....
![fsScreen_2019_08_17_21_14_02](https://user-images.githubusercontent.com/831266/63216348-22ee1800-c134-11e9-9b17-11c4e865e23b.png)

**Comment by alpha117** [comment]
Ok, are you trying to fill from you  'Farm Silo'  and your Seeder filling; if so it will never work as you have currently 2 separate networks. Silo is on one and the Seeder filling is on the other

![image](https://user-images.githubusercontent.com/30005040/63216362-d7377080-c12b-11e9-8c4e-0bfbdd829030.png)

Also your network is broken near the shop
![image](https://user-images.githubusercontent.com/30005040/63216376-fdf5a700-c12b-11e9-8d01-01fe1e0d2d32.png)

**Comment by raxtor** [comment]
I know, I dont use those parts of network, its just for testing purposes... I am interested only for Seeder filling and in-house seeder. Farm Silo network is for combine and unloaders. Yes, broken route near shop can be trouble..anyway is working it for you if you?

**Comment by raxtor** [comment]
Feel free delete routes and make own..

**Comment by raxtor** [comment]
btw Seeder filling is in house, that tank in corner is fertilizer

**Comment by alpha117** [comment]
looks like the issue is with 1.0.4.8, I've just gone back to 1.0.4.7  and all is fine and works like it should

**Comment by raxtor** [comment]
Well... Load mode not works for me.. tell me what is wrong?
There is default network for Ravenport and I did only small circle where I want refill seeder and than go to next waypoint... Seeder just opened cover and staying there. R key for manual filling is inactive but when I turn off  AD manual refilling is possible. I dont want use CP, just refill seeder...
![fsScreen_2019_08_19_03_15_36](https://user-images.githubusercontent.com/831266/63233386-2bc41400-c230-11e9-8541-4e7b6e6af943.png)
![fsScreen_2019_08_19_03_15_48](https://user-images.githubusercontent.com/831266/63233387-2bc41400-c230-11e9-95ee-2dba74f42835.png)

**Comment by Stephan-S** [comment]
You still have to select 'seed' or 'fertilizer' as filltype. When Google translate is right, you choose 'wheat', which might be what your seeder is telling you below, but is not the actual filltype :-)

**Comment by Stephan-S** [comment]
I think this is a Common mistake, so I will Change the Implementation in one of the next updates, so that If you have a seeder connected, it will always fill seed

**Comment by raxtor** [comment]
Ah, next hidden function for me...!!! 
I found this #253 but when I click to right side, its only opening waypoint list. Probably I know why... its because translation... see where I am able open filltype list (red area).. next problem is,. I havent option (seed) in Czech translation.. huh.. but I can set 3 types of grass...
![filltype](https://user-images.githubusercontent.com/831266/63257453-1bd12200-c27a-11e9-8615-ffe17258b519.png)
![filltype2](https://user-images.githubusercontent.com/831266/63257900-0f00fe00-c27b-11e9-9ebc-29281571d2eb.png)
In Czech translation is only Liquid Fertilizes and Lime... no Seed, no fertilizer...

**Comment by raxtor** [comment]
No idea if its bug of FS or AD... anyways for BFU it seems he is not able change filltype if you understand me...

**Comment by raxtor** [comment]
![hud8](https://user-images.githubusercontent.com/831266/63259100-c6970f80-c27d-11e9-977b-72e302eb45fb.png)

**Comment by raxtor** [comment]
btw  Iassumed Ad is smart enough to find what can fill,,, I have attachement which accept some filltypes and source which offer 1 or more fill types. Should be nice has AUTO fill function by filltype and when AD is not able make decision than ask user for input for filltype

**Comment by raxtor** [comment]
I switched to ENG version but still no success
![fsScreen_2019_08_19_17_37_55](https://user-images.githubusercontent.com/831266/63278718-1a1e5300-c2a8-11e9-8e50-d00ec51f893c.png)

**Comment by alpha117** [comment]
I think your are trying to fill from the wrong side?  Have you tried from the other side?

**Comment by raxtor** [comment]
Ween I turn off AD, R for manual refill is active, so it doesnt mean there is trigger?

**Comment by alpha117** [comment]
The reason I asked was that I have used that same seeder with AD, but filled from the otherside and work OK

**Comment by raxtor** [comment]
Thx for input, but no success from other side too :-/
![fsScreen_2019_08_19_18_26_02](https://user-images.githubusercontent.com/831266/63282333-e2ff7000-c2ae-11e9-9075-b0b7b7c49b3b.png)

**Comment by alpha117** [comment]
Thought I best check to make sure it still works and it does

![image](https://user-images.githubusercontent.com/30005040/63289806-e3e8cf80-c2b7-11e9-9ae3-08acd9fb1353.png)

**Comment by alpha117** [comment]
On your screenshot, it looks like you are not on a network and also the pallets looks way to far from the network. Look how close the refill pallets are to the network in my shot and that works

**Comment by raxtor** [comment]
Can I be more close?
![shot_005](https://user-images.githubusercontent.com/831266/63300507-aba5b900-c2d8-11e9-9661-cf97ebd3d4fc.jpg)

**Comment by raxtor** [comment]
Well, its seems like trigger acceptation problem. Some triggers are OK for AD, some not.. eg 
County Line
Liquid fertilizer: 
At CPS for AD and FS are both OK
Moore Co-op (Anhydrous Ammonia tanks) bad for AD, but OK for FS
buyable seeds are problem everywhere... bad for AD, OK for FS
