### ISSUE TITLE
Refueling ability

### ISSUE THREAD

**Issue by raxtor** [Stephan-S/FS19_AutoDrive#365]
Not sure if AD is able refuel vehicle, but would be nice has such possibility if course is going through fuel trigger. AD would start refueling if fuel is under 25% or so. Or maybe another skill for "Load" mode?

**Comment by Stephan-S** [comment]
I told you I would do it one day @raxtor 
Done!

**Comment by raxtor** [comment]
Doesnt it mean I should provide new collection of Elon Musk ideas for AD?
