### ISSUE TITLE
Spiel friert beim Speichern ein

### ISSUE THREAD

**Issue by FunFarmer1** [Stephan-S/FS19_AutoDrive#366]
[log.txt](https://github.com/Stephan-S/FS19_AutoDrive/files/3511813/log.txt)

Hallo Stephan,

wenn ich das Spiel speichern möchte friert das Spiel plötzlich ein und ich muss es mit Alt + F4 beenden, und gespeichert wurde es auch nicht.

Gruß Dennis

**Comment by FunFarmer1** [comment]
Und nach dem Neustarten des Spieles ist mein gesamter Spielstand gelöscht.

**Comment by Stephan-S** [comment]
Hey, tut mir Leid. Da hat sich in der aktuellen Version ein Bug eingeschlichen.
Deinen letzten Spielstand findest du aber zum Glück immer in savegamesBackup Ordner.
Damit solltest du alles wieder zurücksetzten können.

Ich lade heute noch ein Update hoch, um das Problem zu beheben. Bzw. in den aktuellen Quelldaten habe ich es schon behoben, aber ich werde es erst im Laufe des Tages zu einem Release zusammen packen, da ich noch an ein paar anderen Baustellen arbeite.

Grüße,
Stephan

**Comment by FunFarmer1** [comment]
Also danke für die Sehr schnelle Antwort!
ich habe die neue bzw.  die geänderte Version der letzten Stunde schon bei mir in dem Mod Ordner und es eben gerade wieder Versucht und es ist leider wieder passiert. 

Gruß Dennis

**Comment by Stephan-S** [comment]
Ich habe schnell hintereinander zwei commits gemacht. Und erst der zweite hat das Speichern behoben. Der erste nur das Flackern im Einstellungsmenü.
Hast du auf jeden Fall die Version vom zweiten commit probiert? Eigentlich muss es da behoben sein :(

**Comment by FunFarmer1** [comment]
ok ich werde es nochmal versuchen und sage dir dann gerne nochmal bescheid!;)
danke für die Info.

Gruß Dennis

**Comment by Stephan-S** [comment]
Sorry, da hatten sich doch ein paar Fehler mehr eingeschlichen. Aber so langsam sollte ich sie alle erwischt haben

**Comment by FunFarmer1** [comment]
Das freut mich zuhören! Ich hatte es vorhin auch nochmal getestet und es lief ohne Probleme !;)
Danke für deine Bemühung!
