### ISSUE TITLE
 Code Issues 103 Pull requests 3 Projects 5 Wiki Security Insights Request: Mouse Share with other Mods for example Courseplay

### ISSUE THREAD

**Issue by kleba78** [Stephan-S/FS19_AutoDrive#367]
Hi there, 

is there any possibility to share the Mouse Pointer for these two mods, after your collaboration there is a litte bit of hope, that this is possible.

This will take the usability and gameplay of Courseplay and autodrive to a next level.

Thx for your Work.
kleba

PS: The same Request ist posted in Git Courseplay

**Comment by Stephan-S** [comment]
I already included this. If you only have the courseplay mouse toggle, AutoDrive will also happily accept any mouse input.
Basically AutoDrive is now set to always accept the mouse cursor if one is visible and also disables camera rotation when a mouse cursor is enabled.

**Comment by kleba78** [comment]
I think i have to check my inputbindings first, actually this is not working in my installation.
CP wrote the same answer, so i think it s my fault .

Thx.
