### ISSUE TITLE
Editor Problem

### ISSUE THREAD

**Issue by Bandesss** [Stephan-S/FS19_AutoDrive#368]
Hallo wenn ich die Kurse Downloade bei Modhoster
https://www.modhoster.de/external/sI0Zq
Sind die Kurse 5 MB, wenn ich nun den Kurs im Editor bearbeite im Windows, sind die Kurse nur noch unter 1 MB.
Aber die Kurse mit 1 MB nach dem bearbeiten scheinen nicht richtig zu gehen.
Ist das ein Fehler im EDITOR?
Gruss

**Comment by Stephan-S** [comment]
> Aber die Kurse mit 1 MB nach dem bearbeiten scheinen nicht richtig zu gehen.

Was heißt denn sie scheinen nicht richtig zu gehen ? Hast du nach dem Bearbeiten im Spiel nochmal neuberechnen lassen?

**Comment by Bandesss** [comment]
Jupp habe ich gemacht, aber wieso wird die Datei durch den Editor soviel kleiner ?

**Comment by Stephan-S** [comment]
Hab zwischendurch das Kursformat verbessert, so dass es etwas kleiner wurde. Wenn die Kurse beim Modhoster mit einer älteren Version erstellt wurden kann das durchaus sein.
Das verkleinern funktioniert immer dann, wenn alle Ziele von überall erreichbar sind. Ansonsten wird die Datei wieder etwas größer.
Also gibt es keine Probleme mit den Kursen im Spiel?

**Comment by Bandesss** [comment]
Ja, er findet die Punkte nicht mehr so wie ohne den Editor.

**Comment by Stephan-S** [comment]
Hast du neuberechnen lassen?

**Comment by Bandesss** [comment]
Ja habe ich zum vergleich 
[AutoDrive_NF_Marsch_V2_2_oG_config.zip](https://github.com/Stephan-S/FS19_AutoDrive/files/3512048/AutoDrive_NF_Marsch_V2_2_oG_config.zip)

[1MBAutoDrive_NF_Marsch_V2_2_oG_config.zip](https://github.com/Stephan-S/FS19_AutoDrive/files/3512049/1MBAutoDrive_NF_Marsch_V2_2_oG_config.zip)
Ich finde keine Fehler, aber von 5MB auf 1 MB komisch

**Comment by Stephan-S** [comment]
Welche Punkte findet er denn nicht? Hab deine Config eben ausprobiert und nur mal zum Händler gefahren. Alles ohne Probleme bei dem 1Mb variante

**Comment by Bandesss** [comment]
OK dann schau ich nochmal danke
komisch

**Comment by sootysax** [comment]
is it me?  or does it take twice as long as it did before to recalculate?
