### ISSUE TITLE
Global Company trigger not filling trailers

### ISSUE THREAD

**Issue by Stephan-S** [Stephan-S/FS19_AutoDrive#369]
Hier ein kleiner Fix für die GlobalCompany Triggers.
Damit werden die Fahrzeuge auch geladen, wenn kein Spieler im Fahrzeug sitzt.

Einfach im Unterordner triggers im GlobalCompany mod ersetzen:
https://www.dropbox.com/s/b2w9035mfw8ldnb/GC_LoadingTrigger.lua?dl=0

Lösung ist bereits bei der LS-Modcompany vorgestellt und wird also wohl im nächsten Release enthalten sein nehme ich an.

**Comment by alpha117** [comment]
Thanks
