### ISSUE TITLE
Anfrage - Laden Saat+Dünger abschaltbar machen?

### ISSUE THREAD

**Issue by haamic** [Stephan-S/FS19_AutoDrive#370]
Hallo Stephan,
viele wünschten sich das, aber wäre es möglich, die Doppelbefüllung einer Saatmaschine in den Optionen abschaltbar zu machen?
Ich nutze eine Saatmaschine mit Düngertank, aber habe die Düngefunktion in CP abgeschalten, weil ich separat dünge.
Nun wird beim Auffüllen aber auch der Dünger aufgefüllt, weil die Silos auf einer Strecke liegen. Wenns nicht so viel Arbeit für dich ist, wäre es möglich, diese Option einzubauen? 
Ansonsten mach ich halt den Kurs anders, so das er wirklich nur am Saatgut-SIlo vorbeikommt, oder ich lass den Düngetank ständig voll , damit nichts nachgetankt wird.
Gruss Micha

**Comment by Stephan-S** [comment]
Kommt dann im nächsten Release. Dann muss ich doch endlich eine zweite Seite in den Einstellungen basteln :D

**Comment by haamic** [comment]
ja nur eine Seite ist auch zu wenig ;-)
