### ISSUE TITLE
Anderson Group Hybrid X Xtractor

### ISSUE THREAD

**Issue by sootysax** [Stephan-S/FS19_AutoDrive#371]
Having this wrapper attached to a tractor and enabling AutoDrive locks up the game and will not allow you to save the game (even though you can get to the menu and click save and it looks like its saving).  Upon reloading the last savegame was from 1 hour ago instead of 1 minute ago.

**Comment by raxtor** [comment]
1.0.4.7 version was bigged... try latest release

**Comment by alpha117** [comment]
> 1.0.4.7 version was bugged... try latest release

The intial release was, but Stephan fixed 6 big issues in the final 1.0.4.7, which works just fine.

Other item were added and released as 1.0.4.8, which now looks like has broken the items that were fixed in 1.0.4.7...if that makes sense

**Comment by Stephan-S** [comment]
Could you please confirm that this is not an issue in the current version? I don't have that DLC yet, so I can't check myself right now :-)

**Comment by alpha117** [comment]
Sure will, stand by

**Comment by alpha117** [comment]
Works perfectly on Fenton Forest...just going to check County lines

**Comment by alpha117** [comment]
Works on County lines @raxtor I can load FERT AND SEED AUTOMATICALLY, on your network. Your network needs sorting out to be honest.

**Comment by Stephan-S** [comment]
Thanks for testing @alpha117 !
