### ISSUE TITLE
Text input cursor

### ISSUE THREAD

**Issue by raxtor** [Stephan-S/FS19_AutoDrive#375]
Seems focus is working only for 1st opening. If you open it next time, again you have to click to text filed... it hasnt priority but just for you info.
![fsScreen_2019_08_17_20_20_15](https://user-images.githubusercontent.com/831266/63215831-92f8a000-c12c-11e9-9e58-3158b9e50b44.png)

**Comment by raxtor** [comment]
btw what should do "reset"? Isnt possible use it for delete name of waypoint and set him to regular node?

**Comment by Stephan-S** [comment]
Hey, thanks for the info.
I'm not sure I now exactly what you want with the reset:
1) Just reset the text to 'regular node'? What is regular node in that case
or
2) Delete the waypoint from the course network. If so, just use the provided function, which is right or middle mouse click on the create destination button in the HUD :-)

**Comment by raxtor** [comment]
Hmm.. maybe I am stupid, but can you explain me how rename existing waypoint Field 15 when this node is active? My idea was:
- click to "new waypiont"
- if GUI is opened I see there existing name of waypiont (now there is blank field)
- I can edit name of waypopint (now text input field is empty and when I press OK, nothing changed for name)
- Reset button provides function remove waypoint and set him to standard node (now reset has no function for me)

**Comment by Stephan-S** [comment]
Sorry, was mistaken earlier.

Right/middle mouse click on 'Create Destination' allows you to rename it.
Right/midlle mouse click on 'Delete waypoint' allows you to just delete the destination.

I don't think that deletion should be handled inside the naming GUI. Or am I not understanding your request right? :-)

**Comment by raxtor** [comment]
It doesnt work for me. When I choose Field 15 and click to name of wayipoint in GUI, text disappears, I can set some red text but nothing changed. Right mouse click just open CP panel.
Also its a bit hidden function for new users, should be done in other way... My idea was text input... like you set new waypoint... what about "scroll menu"? Is possible in FS? than you can use waypoint button in stright way, cuz alway it will open "scroll input" with existing waypoints...

**Comment by raxtor** [comment]
Anway text input isnt focused also in 1.0.4.9 fyi

**Comment by raxtor** [comment]
well, I go it finally.. rly I am stupid.. but for new user its a bit comlicated and hidden function....

**Comment by Anonymous-any** [comment]
Can you finalizing by explain what to do when the red text do nothing ? I'm in same situation... and asked this to Stephan.
Br

**Comment by raxtor** [comment]
Go here.. https://github.com/Stephan-S/FS19_AutoDrive/issues/363#issuecomment-522505971

**Comment by Anonymous-any** [comment]
?? srry too I've not the answer I leave.

**Comment by raxtor** [comment]
Just dont click to waypoint text and use buttons for network editing.. (mid or right click when waypoint node is selected by red line)

**Comment by Anonymous-any** [comment]
Thank you for answer me again. Because of your tittle opened, I was thinking it was about another thing I search but look not same as you I expose you mine.
When activated in menu option then we can get this:
![1](https://user-images.githubusercontent.com/25174503/63541460-7094c700-c51e-11e9-94ed-b61c7be0ce6f.png) then you can middle mouse here...but what this is used to do ? is my question
![2](https://user-images.githubusercontent.com/25174503/63541476-77233e80-c51e-11e9-90de-6b4b8858d3e4.png)
Ps: AD-FS17 had same input red text but I never understood what it can be used for.
Regard
