### ISSUE TITLE
No refill happening on County Lines

### ISSUE THREAD

**Issue by alpha117** [Stephan-S/FS19_AutoDrive#379]

**Comment by alpha117** [comment]
@Stephan-S  using latest version, it will not refill when trigger is inside of building. There is a 'flash', like it has triggered a fill, but nothing. Press 'continue' and it will move on

![image](https://user-images.githubusercontent.com/30005040/63216683-ebca3780-c130-11e9-9265-903a7db71166.png)

**Comment by alpha117** [comment]
@Stephan-S I think something has changed between 1.0.4.8  and the latest changes you made in 1.0.4.7, as I cannot get any refill at all to work. It might be County lines, not sure.  All was OK on Fenton Forest earlier this afternoon when you made the changes.  Thoughts?

**Comment by alpha117** [comment]
Just went back to Fenton Forest and can confirm that 1.0.4.8  does not work there either.

**Comment by Roby1164** [comment]
Be careful with seed refills, etc. If the seeder does not stop in the right position, it will never reload, when you make the points, calculate that the vehicle stops before the point, so make the point slightly later.

**Comment by raxtor** [comment]
#363

**Comment by alpha117** [comment]
Can confirm that with 1.0.4.7  all is back to normal and works fine.

**Comment by alpha117** [comment]
> Be careful with seed refills, etc. If the seeder does not stop in the right position, it will never reload, when you make the points, calculate that the vehicle stops before the point, so make the point slightly later.

Correct, but in this case it looks like there is an issue with 4.8, which Stephan will sort out

**Comment by Stephan-S** [comment]
@alpha117 You have to select 'seed' or 'fertilizer' to make it work. You have selected corn which is not what he should actually load.
I found yet another loading related bug,  but what you were trying there should already work as expected in 1.0.4.8

**Comment by alpha117** [comment]
Morning, I know, was due to me being to quick, but on my other test as before 4.8 did not work with the correct selection. Sorry to be as pain

**Comment by alpha117** [comment]
@Stephan-S  works perfectly with the latest 'fixes'...great work
