### ISSUE TITLE
Straßebausteine automatisch erkennen?

### ISSUE THREAD

**Issue by kleba78** [Stephan-S/FS19_AutoDrive#380]
Hey,

eine Frage die ich mir schon etwas länger stelle ist, ob es nicht möglich ist, Straßen automatisch zu erkennen und entsprechend mit Wegpunkten zu belegen?

Habe natürlich keine Einschätzung wie aufwendig sowas ist, für das Gameplay wäre es nach meiner Meinung ein echter bringer. Vielleicht ist das hier auch nur ein Denkanstoss - wollte es aber gerne mal loswerden.

Danke

**Comment by Stephan-S** [comment]
Hey,
klar die Idee liegt natürlich nahe. Aber erstens habe ich noch keinen Weg gefunden, das so umzusetzen und wenn es doch irgrendwie möglich wäre, ist es auch wieder alles andere als trivial, durch den erkannten Straßenbelag korrekte Fahrwege zu errechnen und festzulegen :-)

Guter Vorschlag, aber leider nicht (nicht von mir) umsetzbar. Also mache ich hier mal zu
