### ISSUE TITLE
Auto close cover after refill

### ISSUE THREAD

**Issue by ddiis** [Stephan-S/FS19_AutoDrive#381]
Hi! Release 1.0.4.8
After refilling (Courseplay field work + Autodrive refill mode) tractor continue with opened cover. 

![fs19 cover](https://user-images.githubusercontent.com/4257956/63217816-a409d700-c155-11e9-9311-8aa8ce8b7ef2.png)

**Comment by alpha117** [comment]
Can also confirm this, was OK in 1.0.4.7

**Comment by alpha117** [comment]
@Stephan-S  Just tested with the latest 'fixes' from this morning(Sunday), still an issue.

**Comment by Stephan-S** [comment]
it closes after 105meters from loading/unloading currently. Have you waited that long?^^ Will reduce it next time.

**Comment by ddiis** [comment]
No, tractor went to field far away and continue working with opened cover :( 
And one more thing
1. Tractor enter trigger area from another side, open cover
2. Leave trigger, make turn and return to it from with open cover.
3. Fill and go away with opened cover.
![fs-ad-1](https://user-images.githubusercontent.com/4257956/63222960-21b1ff00-c1b7-11e9-9900-6ffb6c7ac401.png)

**Comment by Roby1164** [comment]
I add myself to this post, saying that, actually there is that problem, but it doesn't even close after 105 meters, as you say.
In addition to this, I am having other problems with the load, first of all with the lime, if you are on board the vehicle, the load does not start automatically, but waits for the manual pressure of the button, instead it loads if on its own, while concerning for the seed drills, with the one I use, a mod goes to load, opens the lids, positions itself correctly under the load point, but does not load, whether it is to load the seeds or the fertilizer, I do not know if the problem is the AD or both of the CP, also in this case, if you proceed with loading by manually pressing the button, then it no longer closes the covers.

**Comment by raxtor** [comment]
![fsScreen_2019_08_27_03_36_11](https://user-images.githubusercontent.com/831266/63734311-05c7f080-c87c-11e9-826b-9d5430d4c157.png)
I can confirm that cover doesnt close after refilling.

@Roby1164 Make sure you have set right fillType?

**Comment by Roby1164** [comment]
@raxtor I am trying in every way, if the products are regularly selected, it has happened only a few times, that, trying to send the trotter with a seeder, to load, without CP, only provamdo from point A to the silos loaded with seeds or fertilizer, which has loaded, while, while working with CP, as mentioned, when empty, partly, it arrives at the loading silo, opens any doors, but does not start the load. The problem of doors that do not close is still present, at least on the lime spread, which is the only one that just loads by itself.

**Comment by raxtor** [comment]
I have strange experience, it happened to me too.. just opened cover and no refill. I had seeds in house and fertilizer 50m far away.. no way to make it work... than I changed route and it works. I fill seed from other side of seeder.. no idea why it wasnt woking before. (maybe any multiple trigger detection so maybe a bit different route fixed it).

**Comment by Stephan-S** [comment]
It will only load in a range of 20m to the loading destination. So if you have multiple triggers which are that far away, it won't work

**Comment by Roby1164** [comment]
> It will only load in a range of 20m to the loading destination. So if you have multiple triggers which are that far away, it won't work

What do you mean with 20 meters from the destination ?? The triggers, in most cases, are more distant than 20 meters ...

**Comment by Stephan-S** [comment]
You have target 'Field X' and loading target 'Fill seeder'
Now AD will only accept triggers that are <=20 in front of target 'Fill seeder'
Why should they be further away? I understand this is possible if you have two triggers seed+fertilizer,
but if you have only one trigger, it should be close to the loading destination.

**Comment by raxtor** [comment]
In many cases you have eg silo with seed in 1 corner of farm and fertilizer is in other part of farm... more frewquently than seed silo and fertiliyer <= 20m. 
What about this scenario for Load mode?
- Set waypoint for load seeds or fertilizer. 
- During way to that point search second unset filltype trigger (fertilize/seeds). 
- Close cover if any when seeds or fertilizer reached 100%.

Also would be nice suppoer for buyable seeds/fert/lime etc and also possibility refill from mobile triggers, like fertilizer tank trailer...
