### ISSUE TITLE
"Unload here" ability

### ISSUE THREAD

**Issue by raxtor** [Stephan-S/FS19_AutoDrive#382]
Firstly I have to say AD works very good as unloader for CP and is not comparable with CP in mode2. Crashes to combines or objects are very exceptional (1 fence collision, 1 NPC traffic collision and 1 front collision with CP combine). In additon AD is able handles mode 3 (overloading) now which is not working in CP!

I was playing around sugar beat harvesting... probably you already know what I want. Its unloading onto ground like FS can do it by LCTRL+I.. I would like use ROPA Maus 5 for overloading to trucks. It can be useful also in other situations when you want use loader etc..

What do you think?

**Comment by TAColomb** [comment]
I, very much, would love to see this as well so I can unload at a conveyer belt to load my root crop shed. 

Great work on this mod too by the way. Love the entire network vs individual courses.
