### ISSUE TITLE
Question about modes

### ISSUE THREAD

**Issue by raxtor** [Stephan-S/FS19_AutoDrive#384]
@Stephan-S can you explain technical diferencies? 
In cursive is how I understand it when we have 2 waypionts where I am staying on waypoint1.
Load
_(means: go to waypoint2 - load, waypoint1 - unload and go back to waypoint2)_
Load and Deliver
_(means: go to waypoint1 - load, waypoint2 - unload and go back to waypiont1)_
Deliver
_(means: go to waypoint2 - unload and stop)_

Correct me if I am wrong eventually provide some additional info about differences between these 3 modes for whose jobs were mainly intended.
Thx in advance.

**Comment by raxtor** [comment]
Because I am plazing with more interactive HUD.. example for Load and Deliver
![hud](https://user-images.githubusercontent.com/831266/63225697-2f757d80-c1d3-11e9-97c7-e13a4d2fb810.png)

**Comment by raxtor** [comment]
More campact HUD...
![hud3](https://user-images.githubusercontent.com/831266/63225873-bfb4c200-c1d5-11e9-8cce-3ffc11eee190.png)
![hud4](https://user-images.githubusercontent.com/831266/63225874-bfb4c200-c1d5-11e9-83f6-f334734a9255.png)

**Comment by Stephan-S** [comment]
I like your ideas and your level of involvement here. Thank you for that!
One thing I see as a concern here, is the handling of longer destination names.
So these buttons will have to move to the right or actually completely left and before the names.

Sorry, for the brief reaction. I will get back to you on this when I have some time again!

**Comment by raxtor** [comment]
![hud6](https://user-images.githubusercontent.com/831266/63229390-0ddebb00-c200-11e9-8dd2-5fe14280dc8c.png)
Its just concept... can be done improved icons, like I added speedmeter...

**Comment by Martinnygaard** [comment]
I like your idea, Raxtor!

**Comment by RUGhost** [comment]
![63229590-56977380-c202-11e9-9c9c-fffeaa6c96c9](https://user-images.githubusercontent.com/48012198/63242892-aade3a00-c27a-11e9-967e-0d6ac84248d5.png)
I think you can modified this ui( if you like my idea). Place the parking icon below the loop icon. Then move the unload icon beside (left side)  the park icon. Add a new load icon for refill course and place it beside (left side)  the loop icon. Then move the combine and load icon to right ( beside load icon for refill course ). In this way you will  find more space for longer destination name.

**Comment by raxtor** [comment]
![hud8](https://user-images.githubusercontent.com/831266/63259122-d9114900-c27d-11e9-92da-c1698f4623b6.png)
I think space for target name is big enough... just I added filltype control..

**Comment by RUGhost** [comment]
@raxtor it looks awesome in sense. Fantastic work. But i can't understand that battery icon (85%).

**Comment by RUGhost** [comment]
Its a fantastic work. Looks awesome. But I dought the filltype box space  won't be sufficient for "liquid manure" "liguid fertilizer".

**Comment by raxtor** [comment]
you can use L. Fertilizer :-).. no need see whole name when there will be shown list after click with full names... not? Its just informative... I am limited by space when we want use same size. Of course @Stephan-S will make it be wider... it depends on him

**Comment by raxtor** [comment]
amd yeah... icon for fill level shoub be different... now its more like fuel level...

**Comment by raxtor** [comment]
Probably loop button shoud be moved down to same row like start and continue from logic view...

**Comment by RUGhost** [comment]
@raxtor 
>you can use L. Fertilizer 

Then i'll happy if i can see this in fs19

**Comment by Tensuko** [comment]
That is my biggest problem with AD.
It don't find it very clear, what AD does where in wich Mode, where load and where unload.
The GUI like @raxtor shown there would be very good, also when the fruit you select, is at the position where it actually loads.
As I saw, in one mode the loading is at the 1st target, in an other mode it is at the 2nd target.

For longer Target Names: your drop down menu should stay, but when selected, display it with like up to 10 or maybe 12 characters, then go for '...' as we do in CP Mini-HUD.

**Comment by Stephan-S** [comment]
I would love to include some Tutorial Pages in the game itself to explain all those 'hidden' or not quite intuitive features of the mod.
But I am just to busy with so many other things that I keep pushing this goal further away..

@raxtor I still like your ideas. Keep it up! I will get to it in the next weeks and see what distills out of it :-)

**Comment by raxtor** [comment]
Thx @Stephan-S and I understand you are under pressure. NP, its just game :-) I would like help you but my LUA and FS LUUDOC knowledge is near to zero. I have an idea for field work course generating when would be possible use more AI driver. A little diffrent way than uses CP, but I am not sure if all data what I need are presented in FS LUADOC.. maybe we can consult it via email.

**Comment by Tensuko** [comment]
Field work is been worked on at CP for a very long time. I can promise you that is a very very big project, if xou just think about how long cp works on fields, there is still some tweaking ongoing to work more perfect :)

**Comment by Stephan-S** [comment]
Yeah, fieldwork is not really something I would like to include. CP is doing a fine job there. And it really is a big challenge given the complexity and variety of machines in FS. Starting this from scratch would be pointless if a mod like CP is still in active development.
So If you have any great ideas for fieldwork, your first contact should be with the CP devs. But feel free to always post and discuss your ideas here If you accept my earlier points ;-)

**Comment by raxtor** [comment]
Sure, CP offer the best what we can do on field, I am sure you spent many hours for field works. Maybe my idea is bullshit. Maybe not.. its not about if I prefer CP or AD. In fact I still didnt get, why CP didnt offer you membership in thier team and didnt integrate AD to CP as part of mode 1/2/3.. but its your bussines.. I will add some picture about my idea just for clarify if its stupidity or can be developed.

**Comment by Tensuko** [comment]
CP is nothing closed. Everyone can bring in a part, as long as it fits into CP and use a similar style of programming. And AD and CP working closer and closer together! Both bring a lot of good features into fs19 and I use AD now for driving arround. So both teams did a good job on their mods and the cooperation even helps both mods to improve.

**Comment by raxtor** [comment]
![field_gen](https://user-images.githubusercontent.com/831266/63304135-52db1e00-c2e2-11e9-9627-6adfd57cefea.png)
1. generate filed border
2. set width for attachment
3. set angle of rows (2 options only shortest or longest side of field)
4. set number of vehicles
5. set number of headlands (must be devided by number of vehicles)
6. starting point is auto set for closest point to vehicle position from border
7. generate headlands and row grid for attachment


- for collision avoiding will be used AI driver
- when you restart course AI drive will find closest point from course (depends on angel of actual vehicle, grid can be done visible for better situation awareness) and set direction by previous point. Than its need manuver to get to right postion. (picture bellow)
- there should be set of some headland maneuvers for handling vehicle turning radius
So you need only a few course points, not like CP whole grid also u can use AI driver on filed. Thats all
![field_ge1n](https://user-images.githubusercontent.com/831266/63305101-dba78900-c2e5-11e9-9a04-670c69fc3479.png)

**Comment by raxtor** [comment]
For 2 vehicles its just skip 1 row or headlend... etc

**Comment by Tensuko** [comment]
'thats all'
No it is not. Tool lifting, reverse turn, turn for the right angle, depending on field border, when should be what part worked on, differen tool handle etc etc.

You cant imagine how much more there is ongoing to work on a field.
That Course pattern is just done by an internal cp tool called course generator, wich already got a lot of functions for different pattern.
But the whole tool and drive handling is a complete other story, trust me.

**Comment by raxtor** [comment]
_No it is not. Tool lifting, reverse turn, turn for the right angle, depending on field border, when should be what part worked on, differen tool handle etc etc._

Many of them AD already do as unloader for CP and belive me is very good. So I assume whole move on field is less/more prepared because it has do tractor for CP unloading.  
Also probably is possible use many of that code from CP for this new approach for course generating. Thx you said me your opnion. I could save my time too..

**Comment by Tensuko** [comment]
I just tell you that there is much more behind it then you think.
Beside that. I understand AD as a Waypoint Network, no Idea how to integrate Extra Course into this.
And I don't see why you should do it.
AD works perfect for the Job, sending Tracktors arround and also the Refilling in combination with CP is very nice. The biggest issue of CP is creating all the Course and the problem of can't edit them, thats what AD does right and is made for.

BTW: Is it possible to make 'record on/of' and an extra button to change the recorded WP ? Same for connecting 2 open ends, can it be done with that violet 2-way route ?

**Comment by raxtor** [comment]
Sorry, If you want tell me in every answer there is a lot of work and we spent a lot of time than discussion is a little bit needless. I am not so stupid to imagine as PHP programmer what is posssible, what is reusable and how many time itwill consume.

Read 1.0.4.8 release description, about 2 way route adding I have no  expirience. I assume is not possible by interface and you have make firstli violet route and than join it with network.

**Comment by hoefti10** [comment]
Violet lines is possible to make, just connected the lines in both directions after that you have a violet line.

**Comment by Tensuko** [comment]
@raxtor 
I never said you are stupid and I never said it is impossible.
If you are so smart and know how it can be made, why not show it to us and create it ?
Once again: It is a lot of work, no matter what you say, you will see it if you try it on your own.
I just don't see the reason behind it to create something new, wich already exists.....

And one thing more: This is not a CP vs AD thingy, this is a CP + AD, to get the most out of every mod....

@hoefti10 thx, I will try it out.

**Comment by raxtor** [comment]
Probablly u missed context... I said I will present some idea. Read whole thread pls. And no, I havent time to learn how LUA and FS LUA works. Just I shown you other way how to solve field work. AD and his waypoint solution is simply better approach to that thing from my point of view. And my idea is more close to AD solution, when you should able generate course more flexibile. No more , no less. Instead of opinion to that solution you just argue with time and a lot of work. I didnt hear that CP static grid is better solution or my idea is bad because...

Sry, I dont want continue in this tone if u havent any constructive to that idea.

**Comment by Tensuko** [comment]
_AD and his waypoint solution is simply better approach to that thing from my point of view._
For what Kind of work ? Driving arround, yes. Fieldwork, I don't think so. Where are the Turn Points, how does AD know when, where and how to turn the tool ? Reverse ? Stay on Field ? You need more Information at your Points then just direction. Sure in the rows we could skip Waypoints, but why should it ? What about Island bypass ? You can't handle that with only 2 Waypoints.

---

_when you should able generate course more flexibile._
What kind of flexibility do you want then ? CP offers a lot of Settings, what are you missing ?
We are always open for new (and realistic) Ideas.

---

_I didnt hear that CP static grid is better solution or my idea is bad because..._
Well, you only got one argument for your own Idea and that is: " _So you need only a few course points (red points in picture), not like CP whole grid of points. Also u can use AI driver on field. Thats all_ ". isn't it the same, when I say, CP does a good job and no need a new one in my eyes ? And just for your information, CP use the AI Driver on the Field already.

---

_Sry, I dont want continue in this tone if u havent any constructive to that idea._
Oh wow... come on, this is a discussion, I never attacked you or something, I just tell you my opinion to your work and I find it unnecessary to create something, what already exists. Nothing against the Idea itself, but why should it be in AD? Just becouse you think, AD does a better WP job ? Thats not an actual reason.... but ok.... do what you want, but don't ask me for arguments, when you don't have clear arguments why this one is a better solution, becosue I don't see any...

**Comment by raxtor** [comment]
> _AD and his waypoint solution is simply better approach to that thing from my point of view._
> For what Kind of work ? Driving arround, yes. Fieldwork, I don't think so. Where are the Turn Points, how does AD know when, where and how to turn the tool ? Reverse ? Stay on Field ? You need more Information at your Points then just direction. Sure in the rows we could skip Waypoints, but why should it ? What about Island bypass ? You can't handle that with only 2 Waypoints.

> Turn points? You have course from start point to end point for vehicle. Headland is 1 part of course and rows is second part and u can generate route between start/end points of rows by any pattern (than 1st point is always start implment, second stop and make turn to next row by pattern. Havent CP done reverse routine and all around? I think yes, so why you say it would be done again...
Island bypass is "easy" too. Just row will be composed from 2 parts or more, when vehicle will catch end point of 1st part, will make pathfinding like AD tractor when is going to combine. Doesnt matter if I have turn to next row after last point of previous point or I have to go around Iland. AD knows find way. Test it with 3 combines and 2 unloaders. I did it. CP crashes during harvesting 20+ times (eg County Lines field 17), AD has no problem. I said its idea. In addition u dont need Conwoy, u dont need set left/mid/right combine because simply its not needed.
Example: I have 2 combines, 2 headlands (headland 1 and 2), I will start him... he will go by pattern 1 hadland, than go row 1, row 3, row 5 etc, Second one going same patern but +1... its simpliest example. Just I can count waypoints where implement will be used and where will be turn manuver. 
If there will be Island, than point will have indication "dont change implment mode and make turn with implement on and pls dont call unloader when I am turning".
(headland - course 1 / yellow color - maeuver with implement up / blue color manuver with implement down)
![field_gen2](https://user-images.githubusercontent.com/831266/63350534-e7369680-c35d-11e9-8dcf-d6e1796f9f88.png)

> _when you should able generate course more flexibile._
> What kind of flexibility do you want then ? CP offers a lot of Settings, what are you missing ?
> We are always open for new (and realistic) Ideas.
> Define own pattern how cut field? No troubles with multiple machines? No field collisions cuz CP combine just going course and crashing to all what is around and every tree stop him cuz turn manuever simply doesnt count in trees around field? Maybe I should think a bit longer...

> _I didnt hear that CP static grid is better solution or my idea is bad because..._
> Well, you only got one argument for your own Idea and that is: " _So you need only a few course points (red points in picture), not like CP whole grid of points. Also u can use AI driver on field. Thats all_ ". isn't it the same, when I say, CP does a good job and no need a new one in my eyes ? And just for your information, CP use the AI Driver on the Field already.
> CP uses AI and thats why he is not able unload combine on headland when fences are close, ah.. 

> _Sry, I dont want continue in this tone if u havent any constructive to that idea._
> Oh wow... come on, this is a discussion, I never attacked you or something, I just tell you my opinion to your work and I find it unnecessary to create something, what already exists. Nothing against the Idea itself, but why should it be in AD? Just becouse you think, AD does a better WP job ? Thats not an actual reason.... but ok.... do what you want, but don't ask me for arguments, when you don't have clear arguments why this one is a better solution, becosue I don't see any...
> I never said its hould be part of AD.. I just wanted share some idea with @Stephan-S and you joined to discussion. and really I dont care if it will be part of AD or CP or it wont be never realized. Just I wanted to know if that idea has any potential. And if you dont see any, maybe some other with different view can see many..

**Comment by Tensuko** [comment]
It simply won't work what you try to do here.
You would have to generate always a new course for every type of vehicle, even with the same work width, just becouse you can't turn with every vehicle the same way....

You got a ton of options to create a Fieldpattern to cut it down, even to solve your 'crashes' into fences. Try to create a course like this with your way:
![fsScreen_2019_08_19_21_51_27](https://user-images.githubusercontent.com/27344744/63365506-0e9a5d00-c378-11e9-9fc3-d4ca3e5b4237.png)

And I know what Issue you had on CP GitHub, it works as it should, I showed you there in screenshots that 3 Combine can easy work together and I let them finish the Fieldwork, no Crashes at all.

Keep on working on your Idea, but you will notice where the problems are, when you try to put that into the game, it is NOT that simple as you think... keep on thinking, then you will maybe notice it...
