### ISSUE TITLE
More of a request than issue. concerning speeds settings.

### ISSUE THREAD

**Issue by P3G4SuSuOuT** [Stephan-S/FS19_AutoDrive#389]
Would it be possible to add a function to the mod whereby you can pick a "start" waypoint and an "end" waypoint and have that bit of the course at a set speed? For instance send truck along at 60kmh but when i get to the place I am dropping good/crops off at can it have it automatically lower the speeds, kind of like speed limit signs along a roadside. ooo thats an idea, placeable roadsigns that limit the speeds of vehicles on that stretch of road.

**Comment by Stephan-S** [comment]
Hey, I don't really see the need for that in AutoDrive.
The speeds are calculated while driving and are already adapting to the given road.
So on straight lines, the vehicle will reach it's set top speed and in corners it will slow down.
It will also already slow down next to the start/target locations.

Do you have any problems with the speed AD uses? I'm always happy to get some feedback :-)

**Comment by P3G4SuSuOuT** [comment]
Thanks for the reply. :~) btw, amazing mod and works awesome with courseplay I love it. Not usually however the speed doesn't seem to be dependant on the vehicle being driven in question. For instance my car can go around corners fine at a lot higher speed than a combine or a truck/tractor pulling a 40 ton load in a big trailer plus It would be nice if my drivers knew they were in a 15-20 ton combine as opposed to a quad bike. Sometimes this can cause issue when following a route and the driver" getting lost". In Courseplay that is a setting you can use, which obviously you know lol.  The reason I mentioned about the speed limit signs was partly for this specific reaon. If you could have multiple speed limits set by the signs you place you would enable different vehicles towing different attachments work easier. on straight road sure I can have my tractor trailer drive fast but when it gets to the farm or coming onto a "2 way" route, ie with the purple/pink line in route setup, I would like them to automatically limit the speeds to be able to handle the road easier. I know there are speed signs that are in game on the roads and that may control the ai but I have found no problem doing 60 or 70 down "35" roads. It happens enough that it is noticeable, but not to an annoying level, that even with the limits already imposed on the speeds, as you mentioned, that the change either doesn't happen quickly enough or the system doesn't take into account the already mentioned car and tractor/trailer combo and apply the change earlier to manage the difference in the sheer weight differences involved. 
Also I spend an awful lot of time travelling with the drivers and monitoring the routes, I usually have the routes on display all the time. I think I have noticed that when following a set route the system checks the next chunk of route to take, you get it even with routes not displayed ie the light line on the next waypoint bit, and sometimes they are close together or near other routes. Might it not be possible for it to check the next 2 or even 3 chunks of the route so it can follow more capably? I have noticed sometimes that, especially on my farm around the grain loading silos and other routes that travel on from there but are set up quite close so as not to waste space or enable more pathing etc, when the vehicle pulls up at a waypoint, for drop off etc, when it goes to move on the waypoint sensor can jump across to a different route if it is close enough so it doesn't follow the route you set exactly. One last thing that is actually driving me a little crazy lol is the way a vehicle on the "2 way" route can turn around anywhere along the route. This leads to major issues of my tractors etc turning randomly along the route and driving into fences or buildings. This occurs due to using the 2 way route for driving into the farm from different directions and for big delivery points. I have a lot of fairly complex connections and routes being utilised. Can you make it so that when a vehicle has started along the 2 way route that it can only turn around at the end of it as designated by either a total stop or loop or changing back into the 1 way route so that the turning circles or junctions made can actually do the thing they were placed there for?
Again, please do not see this as complaint whinging or moaning or anything else. The mod is great and as I say it helps me set up the courseplay routes a great thing, given that they are the same all the time ie not reliant on my driving setting up the route lol. That is why I don't mind setting the routes up at 1-5 kmh and it taking maybe 20 minutes real time to drive down the road. I get seriously neat routes so when making a decent courseplay setup it is very much worth the time.
