### ISSUE TITLE
Driver switches between two un-connected roads 

### ISSUE THREAD

**Issue by Martinnygaard** [Stephan-S/FS19_AutoDrive#390]
Hi

During my CP Unload route, i drive from field 25 to unload point. On the way back, it drives towards field 02 (Not on the route to field 25), and suddently crossover to the correct path.

This problem suddently occured (it worked fine before) maybe it is related to editing some parts of the network near F25.
I have tried to restart several times, recalculate and nothing happened.
When i removed the path around field 02 (To block access to this "shortcut") it worked, but it should not cross between two parallel paths that is not connected.

![AD1](https://user-images.githubusercontent.com/26490587/63327909-6c568700-c32f-11e9-9006-489fe443655a.png)

![ad2](https://user-images.githubusercontent.com/26490587/63327912-6f517780-c32f-11e9-8b82-60f9b300c19e.png)

![ad3](https://user-images.githubusercontent.com/26490587/63327919-72e4fe80-c32f-11e9-9a68-4c20dcfadd4e.png)

![ad editor](https://user-images.githubusercontent.com/26490587/63327925-77111c00-c32f-11e9-860a-d9efcb08c7ea.png)

**Comment by Roby1164** [comment]
Did you select the fastest route in the settings? That could be the problem, since it is going to calculate which one is the fastest way, and it changes path. It is never ideal, to put two parallel two-way paths, to create these problems, see the case of modifying them, making them one-way or joining paths ...

**Comment by Martinnygaard** [comment]
No, i am using following settings:
![image](https://user-images.githubusercontent.com/26490587/63358147-d9d3d900-c36a-11e9-8b6e-89f6b6ed6070.png)

How should AD be able to just out of nowhere (in the middle of the course) change from one path to another? Don't it need to be connected to be able to work? 
I thought that was the whole point in AD.

**Comment by Stephan-S** [comment]
Hey @Martinnygaard , the only time where this could happen, is if you changed something in the AutoDrive network but did not yet recalculate the routes. In this state, all the precalculated routes may point to wrong waypoints.
Have you had this problem after a proper recalculation?

**Comment by Martinnygaard** [comment]
Yes, i have recalculated several times. 
I think it started after i deleted another waypoint (not directly effecting this route)
I cut down the tree, and then just went with it as it was - it functioned, but crossed.

Right now i am in the middle of an AD network make-over, so i di not know if i the problem is still present.

**Comment by Martinnygaard** [comment]
Cleaning up in my open issues.
This was in a old version - in my savegame, it is not present anymore.
