### ISSUE TITLE
Not refilling from seed pallets

### ISSUE THREAD

**Issue by alpha117** [Stephan-S/FS19_AutoDrive#392]
I've tried it all, but no luck with this seeder

![image](https://user-images.githubusercontent.com/30005040/63352506-24e4f080-c359-11e9-9aee-7bcc9c02df91.png)

**Comment by Stephan-S** [comment]
Hey, have you tried it after saving and restarting the game. I actually haven't tested it with pallets, So it's absolutely possible that this won't work right now.
But you can try restarting the game after placing the pallets. AutoDrive still only finds triggers on startup.
