### ISSUE TITLE
AD Course is the wrong way when using CP

### ISSUE THREAD

**Issue by alpha117** [Stephan-S/FS19_AutoDrive#393]
The CP 2D display show the correct route, but the route is at the back of the vehicle. It's like it is 180 out

![image](https://user-images.githubusercontent.com/30005040/63366425-a21c5f80-c371-11e9-9262-b6a7def7b906.png)

**Comment by alpha117** [comment]
..but it drives correctly...strange...to monitor

**Comment by alpha117** [comment]
@Stephan-S  with the latest 'PI'  fix it now look worse??

![image](https://user-images.githubusercontent.com/30005040/63370959-1b6c8000-c37b-11e9-9fbf-83db96bd3144.png)

**Comment by Bobster82** [comment]
> @Stephan-S with the latest 'PI' fix it now look worse?? but still drives the correctly
> 

Not worse, ur standing on then other side of the back line... still the same ;)

**Comment by alpha117** [comment]
cheers Bob

**Comment by Stephan-S** [comment]
Today I had some time to start the Game and check the values myself.
Courseplay is passing the yRot only from [-0.5PI, 0.5PI]

@pvaiko Can you either send values in [-PI, PI] or I will update the Interface so you just Pass me the vehicle instead and I get the values myself.

Really not a great GDN Documentation about the getWorldRotation function, If it doesn't even specify the correct return value range..

**Comment by alpha117** [comment]
FYI CP (288)  still starts the route behind the vehicle

![image](https://user-images.githubusercontent.com/30005040/63492352-36d9a700-c4b1-11e9-9895-5e4df96548f4.png)

**Comment by alpha117** [comment]
...But if the vehicle is facing 180 from the start direction then it all lines up perfectly

![image](https://user-images.githubusercontent.com/30005040/63493027-94babe80-c4b2-11e9-972c-cccaaea469d4.png)

**Comment by Stephan-S** [comment]
@alpha117 we are on it. The issue is identified. Will keep you guys updated :-)

**Comment by alpha117** [comment]
fantastic as always Thanks

**Comment by pvaiko** [comment]
@Stephan-S if you need the direction vectors then we already have something like
	local nx, _, nz = localDirectionToWorld( vehicle.cp.DirectionNode, 0, 0, 1 )
or there's a MathUtil.getDirectionFromYRotation().

Do whatever you think is best, I'll work around it. Consider the compatibility though if you change the interface, there'll be all kinds of CP/AD version combinations out there...

**Comment by hoefti10** [comment]
Where is the benefit for this work ? I can’t imagine what I can do with the courses from AD in CP. sorry I’ll guess I am blind 😂
I can start cap from wherever I want, drive to the field and Beginn with the work Automatically?

**Comment by sootysax** [comment]
> Where is the benefit for this work ? I can’t imagine what I can do with the courses from AD in CP. sorry I’ll guess I am blind 😂
> I can start cap from wherever I want, drive to the field and Beginn with the work Automatically?

for starters, if you are doing a silage run that needs to back into a silage bunker, you will need to use CP instead of AD

**Comment by alpha117** [comment]
Let compare where the Current integration of CP and AD are, bearing in mind that the 'teams' are still working on this an is work in progress .

CP:  Currently the best for Field work and the other modes that it has. If you want to create  routes around the map then you have to do each one individually. For example, you have  the main farm(Yard), Shop and Field 3.  In CP you have to create a route to get to each of these locations. Yard> Shop and Yard > Field 3. If you want to get from Shop to Yard then you will have to create a Shop > Yard route.  What if you want to get from Field 3 to Shop, again you have to create another route Field 3 > Shop. Nothing wrong with that, if you only have a few 'destinations'. What happens if you have 30 locations on your map and want to be able to go to and from ALL of these, how many routes would you have to create?
AD: Will create a 'network'  and you create 'destinations' on that network. You do not need to create individual routes on that network.  If I'm at 'Yard' then I just tell AD to go to 'Shop', if I'm at the 'Shop', then I tell AD to take me to Field 3. AD is the 'SatNav' and just like a SatNav it will take you anywhere providing it knows about that destinations.

CP +AD:   again work in progress, but currently AD can run the 'refill' course and then 'hand over' the field work to CP. CP does field work, then hands back to AD for the Refill and so the process continues until the field work is completed.

What is the short. long term integration  going to be?, have a search for Peter's response as the question has already been asked. Hopefully AD and CP will work together in ALL of CP modes.

Also the AD editor is so easy to use to modified the AD network.

It's horses for courses to be honest, CP and AD are both very good in what they do individually, but integrate both of these great programs together, then that will move both into another dimension.

Thee also needs to be a secure repository to be able to share AD networks, anyone have an ideas how that could be achieved?

**Comment by Stephan-S** [comment]
> @Stephan-S if you need the direction vectors then we already have something like
> local nx, _, nz = localDirectionToWorld( vehicle.cp.DirectionNode, 0, 0, 1 )
> or there's a MathUtil.getDirectionFromYRotation().

If you just pass math.atan2(nx, nz), we can keep the interface as it is.
I wanted it to be as universal as possible, so you can also get a path from any position, not just the vehicle position. Otherwise I would have implemented it with you just passing the vehicle instead of startx, startz and startYRot. But changing it now is not ideal, I agree with you!
But I think if you pass the atan2, we should be good with the current interface :-)
I really like where we are going with this and apparantly the community here thinks so too. Always nice to work together and pull in the same direction. Cheers 👍

**Comment by pvaiko** [comment]
@Stephan-S thanks, have the atan2() in CP 291, see how it works out.

I enjoy working on this too, hope the community is more than these two guys here :)

**Comment by alpha117** [comment]
Morning Guys,

So do I..lol!    I think a lot of user what until the programs are updated and on ModHub, for some strange reason. I'll post on the giants forum to let users know about what you guys are currently doing and the massive progress that AD and CP has made over the last few weeks; that might get more users, not just using what is on ModHub

**Comment by Bobster82** [comment]
@alpha117 , O boy... He's calling us "these guys" ... Time to pack our bags ;)

I hope and I think a lot of players like and want CP, AD .. but not much are active in testing or reporting ;)
I think we try every change in code out. Not many people will do that.
Keep up coders, we love ya! ;)
