### ISSUE TITLE
Combine Unload - tractor sometimes makes turn too tight

### ISSUE THREAD

**Issue by aviator64** [Stephan-S/FS19_AutoDrive#394]
This seems to have started happening with the last couple of versions.

When approaching a combine from the front, the tractor sometimes turns around too close to the combine and the trailer does not have a chance to straighten out. When the tractor stops, the trailer is not under the pipe so the combine does not unload.

This happened multiple times this morning with different types of combines.

![fsScreen_2019_08_21_08_31_08](https://user-images.githubusercontent.com/19857526/63423886-23710200-c405-11e9-8c22-d3c1d7ff737f.png)
![fsScreen_2019_08_21_08_24_06](https://user-images.githubusercontent.com/19857526/63423898-29ff7980-c405-11e9-96d9-8c9d0cece7ae.png)

**Comment by raxtor** [comment]
Did you try set different distance from pipe? use that 0.75m from default settings.. 0 meters makes troubles

**Comment by aviator64** [comment]
I did not change the distance, it is still set to 0.75m. The pipe distance is not the problem, it is the fact that the tractor does not turn wide enough for the trailer to get straight. If the tractor is approaching the combine from behind and does not need to turn around, everything is fine.

**Comment by raxtor** [comment]
I understand.. just for sure set 0m if something will change.. maybe this value has impact to wide of turn maneuver...

**Comment by Stephan-S** [comment]
I will adjust the distance of the last waypoint before the pipe a bit, so the trailer will align better.

I reduced the grid size in one of the last Updates, so the vehicle will generally make sharper turns and requires less space to navigate

**Comment by wlfheart** [comment]
what is the appropriate way to make a combine unload course? I play on seasons and can't seem to get it to work with the overloader. do you make a separate circular track next to the truck? Can fields be too big and tractor cant pickup the combine?

**Comment by raxtor** [comment]
Check log if there isnt that problem... #396 
Maybe County Line has too big fields for AD, but was working in 1.0.4.8 
Now unloader has trouble with unfinished headland. You can make own circle for Auger Wagon, but join it to main network.

**Comment by BrewingCoder** [comment]
I'm running into this problem as well; It is especially noticeable when using a longer trailer  like one being pulled behind a semi rather than a tipper behind a trailer.  I've tried different pipe offsets and it only makes things worse.  Basically I have to use a tractor/tipper combo that is shorter and has a tighter turning radius to get this to work.   I'm really not sure of the version I was running previously but it is definitely present in the current code base.
