### ISSUE TITLE
Export and Import Folders  Question

### ISSUE THREAD

**Issue by alpha117** [Stephan-S/FS19_AutoDrive#395]
How should these folders be used correctly?
FS19_AutoDrive_Export
FS19_AutoDrive_Import

Thanks

**Comment by Morgferd** [comment]
I am by no means and expert more like a half notch above novice. Bur here is what I have learned about the Export and Import folders.
In the keybindings I have found three functions related to course files. Export, Import and Upload. Those functions only seem to work when you are in Course Edit mode. (You have clicked the triangular warning sign in the lower left of the AutoDrive HUD.)
You can export a file containing all the recorded courses and destinations by either clicking the disk icon on the HUD or pressing the correct key combination. That file will be placed in the "FS19_AutoDrive_Export" folder. I have done a file compare between that file and the AutoDrive course file found in the savegame folder. They are the same.
If you put a properly named and formatted file in the "FS19_AutoDrive_Import" folder and press the correct key combination (in edit mode) AutoDrive will import the courses and destinations in that file into the current game. (I am pretty sure it replaces all courses and destinations currently defined in that game.
I have yet to discover what the upload function I found in the keybindings file does.

I hope this helps.

**Comment by Stephan-S** [comment]
@Morgferd perfect explanation. Thank you! 
Upload routes can be used on dedicated servers. That way, a player (Admin) can Upload his course File from the import folder to the server

**Comment by alpha117** [comment]
thanks @Morgferd, that closes this one.

**Comment by Morgferd** [comment]
Note: After doing an import it appears that you must click the "Update Ways" button to have the game know about the changes.
