### ISSUE TITLE
Stop searching - no path found in reasonable time

### ISSUE THREAD

**Issue by raxtor** [Stephan-S/FS19_AutoDrive#396]
AD cant find route when is collaborating with CP.. but waypoint is 10m far from him. Without CP it works and path is found. Tried all exit strategy.
```
2019-08-21 19:52 Going into fallback mode - no fruit free path found in reasonable time
2019-08-21 19:52 Stop searching - no path found in reasonable time
2019-08-21 19:52 Autodrive encountered a problem during initialization - shutting down
```
![fsScreen_2019_08_21_19_52_25](https://user-images.githubusercontent.com/831266/63455705-93a37600-c44d-11e9-9296-aa7b822e3a79.png)
[log.txt](https://github.com/Stephan-S/FS19_AutoDrive/files/3526622/log.txt)

**Comment by Roby1164** [comment]
The problem is precisely the proximity, at that distance, thinks it has already arrived, and does not move.

**Comment by raxtor** [comment]
No, I just originally was wayopint in roner of that way. Same result.. its trouble only when CP turns on AD...

**Comment by raxtor** [comment]
Same problem also for non finished headland... unloader cant find way to combine from same reason.. also pathfinding seems not work correctly and crashin to objects around field...
