### ISSUE TITLE
Setting to disable the menu in the left top menu

### ISSUE THREAD

**Issue by fresH229a** [Stephan-S/FS19_AutoDrive#397]
Hi,

is it possible to add a setting to disable the menu entries in the top left menu.
It makes it a bit confusing with the lot of AD entries :)

Thanks

**Comment by haamic** [comment]
you can disable the help in the AD menu

**Comment by fresH229a** [comment]
Did that, its still displayed

**Comment by haamic** [comment]
that was the same with me. i changed to another vehicle and the help was deactivated. probably small bug in AD
