### ISSUE TITLE
Änderung der Mapversion - Keine AD Kurse mehr

### ISSUE THREAD

**Issue by Fuzzy86** [Stephan-S/FS19_AutoDrive#398]
Hy! Ich bräuchte eure Hilfe!

Habe gerade die NF Marsch auf 2.3 aktualisiert und jetzt habe ich das Problem das meine ganzen Kurse von der V 2.2 Fix nicht geladen werden können!

Muss ich jedesmal bei einer neuen Mapversion das Straßennetz neu einfahren oder gibt es da eine Lösung?

Ich bitte um Hilfe

mfg

**Comment by Andii1980** [comment]
Geh in deinen savegame ordner. Dort ist die autodrive xml mit deinem map namen. Mach eine kopie davon zur Sicherheit. Dann den namen der xml anpassen, Aus 2.2 machst du 2.3. Die datei dann öffnen und ich glaube ziemlich weit unten war was mit der map version in solchen klammern < >, dort drin auch von 2.2 auf 2.3 wechseln. Zum schluss speichern und ls starten. Dann sollte es wieder gehen

**Comment by Fuzzy86** [comment]
Hy! Danke für die schnelle Antwort! Das geht eben leider nicht :-(
-- 
Diese Nachricht wurde von meinem Android Mobiltelefon mit GMX Mail gesendet.Am 23.08.19, 10:41, Andii1980 <notifications@github.com> schrieb:
Geh in deinen savegame ordner. Dort ist die autodrive xml mit deinem map namen. Mach eine kopie davon zur Sicherheit. Dann den namen der xml anpassen, Aus 2.2 machst du 2.3. Die datei dann öffnen und ich glaube ziemlich weit unten war was mit der map version in solchen klammern < >, dort drin auch von 2.2 auf 2.3 wechseln. Zum schluss speichern und ls starten. Dann sollte es wieder gehen



—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.

[

{

"@context": "http://schema.org",

"@type": "EmailMessage",

"potentialAction": {

"@type": "ViewAction",

"target": "https://github.com/Stephan-S/FS19_AutoDrive/issues/398?email_source=notifications\u0026email_token=AM2SDZQBVIQZPCMDQLHHNYLQF6PCPA5CNFSM4IO5CXSKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD47RRWA#issuecomment-524228824",

"url": "https://github.com/Stephan-S/FS19_AutoDrive/issues/398?email_source=notifications\u0026email_token=AM2SDZQBVIQZPCMDQLHHNYLQF6PCPA5CNFSM4IO5CXSKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD47RRWA#issuecomment-524228824",

"name": "View Issue"

},

"description": "View this Issue on GitHub",

"publisher": {

"@type": "Organization",

"name": "GitHub",

"url": "https://github.com"

}

}

]

**Comment by Andii1980** [comment]
Ich bin in ca ner stunde am PC dann schau ich es mir nochmal genau an. Muss ja selbst auch wieder von 2.2 auf 2.3 wecsheln. Du hast auf von mit gräben auf mit gräben. Und ohne auf ohne gewechselt?

**Comment by Fuzzy86** [comment]
Ok super. Die alte und neue Version sind mit gräben
-- 
Diese Nachricht wurde von meinem Android Mobiltelefon mit GMX Mail gesendet.Am 23.08.19, 10:50, Andii1980 <notifications@github.com> schrieb:
Ich bin in ca ner stunde am PC dann schau ich es mir nochmal genau an. Muss ja selbst auch wieder von 2.2 auf 2.3 wecsheln. Du hast auf von mit gräben auf mit gräben. Und ohne auf ohne gewechselt?



—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.

[

{

"@context": "http://schema.org",

"@type": "EmailMessage",

"potentialAction": {

"@type": "ViewAction",

"target": "https://github.com/Stephan-S/FS19_AutoDrive/issues/398?email_source=notifications\u0026email_token=AM2SDZWC4TNB4IMAYVG4O6LQF6QF7A5CNFSM4IO5CXSKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD47SKKA#issuecomment-524231976",

"url": "https://github.com/Stephan-S/FS19_AutoDrive/issues/398?email_source=notifications\u0026email_token=AM2SDZWC4TNB4IMAYVG4O6LQF6QF7A5CNFSM4IO5CXSKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD47SKKA#issuecomment-524231976",

"name": "View Issue"

},

"description": "View this Issue on GitHub",

"publisher": {

"@type": "Organization",

"name": "GitHub",

"url": "https://github.com"

}

}

]

**Comment by Andii1980** [comment]
Ich selbst hab ohne gräben aber ist ja ansich egal.
Auf der Datei AutoDrive_NF_Marsch_V2_2_config.xml machst du AutoDrive_NF_Marsch_V2_3_config.xml

dann in die Datei und dort dann <NF_Marsch_V2_2> in <NF_Marsch_V2_3> & und unten </NF_Marsch_V2_3> in </NF_Marsch_V2_3>.

**Comment by Fuzzy86** [comment]
Super danke. Jetzt geht es! Hab in der AD xml ganz unten vergessen auf 2_3 zu ändern! 

Danke vielmals
Lg
-- 
Diese Nachricht wurde von meinem Android Mobiltelefon mit GMX Mail gesendet.Am 23.08.19, 11:20, Andii1980 <notifications@github.com> schrieb:
Ich selbst hab ohne gräben aber ist ja ansich egal.

Auf der Datei AutoDrive_NF_Marsch_V2_2_config.xml machst du AutoDrive_NF_Marsch_V2_3_config.xml

dann in die Datei und dort dann <NF_Marsch_V2_2> in <NF_Marsch_V2_3> & und unten </NF_Marsch_V2_3> in </NF_Marsch_V2_3>.



—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.

[

{

"@context": "http://schema.org",

"@type": "EmailMessage",

"potentialAction": {

"@type": "ViewAction",

"target": "https://github.com/Stephan-S/FS19_AutoDrive/issues/398?email_source=notifications\u0026email_token=AM2SDZSBUZNWSELCM7OPZTTQF6TULA5CNFSM4IO5CXSKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD47UWKA#issuecomment-524241704",

"url": "https://github.com/Stephan-S/FS19_AutoDrive/issues/398?email_source=notifications\u0026email_token=AM2SDZSBUZNWSELCM7OPZTTQF6TULA5CNFSM4IO5CXSKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD47UWKA#issuecomment-524241704",

"name": "View Issue"

},

"description": "View this Issue on GitHub",

"publisher": {

"@type": "Organization",

"name": "GitHub",

"url": "https://github.com"

}

}

]

**Comment by Andii1980** [comment]
hehe... dacht ich mir ;)

Dann viel Spaß auf der 2.3

**Comment by Fuzzy86** [comment]
Danke Dir auch :-)
