### ISSUE TITLE
Abtank position ändern.

### ISSUE THREAD

**Issue by Andii1980** [Stephan-S/FS19_AutoDrive#402]
Hallo. Gibt es die Möglichkeit dem abfahrer zu sagen das er nicht so weit an dem Drescher vorbei fahren soll zum abtanken? Normal ist es ja so das der Abfahrer immer bis zur hälfte vom Anhänger Vorfährt und dann erst stehen bleibt. Was zu Probleme führt wenn die Fruchtumfahrung an ist beim CP Drescher und AD Abfahrer.

Gruß und Danke
Andii

**Comment by hoefti10** [comment]
Gibt es in den Einstellung, Entfernung zum Drescherrohr oder so ähnlich heißt der Punkt, standardmäßig auf 0,75 m.

**Comment by Andii1980** [comment]
Ist damit nicht gemeint der seitliche Abstand zum drescher?

**Comment by haamic** [comment]
Ja das ist nur der seitliche Abstand. Da hat hoefti10 wohl nicht richtig gelesen. 
Die Längsrichtung kann man (noch) nicht justieren. Wünsche ich mir aber auch, vielleicht kommt's ja noch. Der Abfahrer fährt mit kurzen Anhängern bei mir auch zu weit vor und ehe er stehenbleibt ist der Hänger aus den Trigger raus.

**Comment by Andii1980** [comment]
Schade. Ich dachte mir schon das hoefti10 was falsch verstanden hat.

Dann werd ich mal die xml Dateien durch Forsten. Es würde ja auch reichen wenn der Drescher etwas länger stehen bleibt, damit der Abfahrer genug zeit hat zum wegfahren.

**Comment by Stephan-S** [comment]
Ich bau demnächst einen Offset in die Optionen rein. Vlt schon beim nächsten Update.
In der XML kannst du hier eigentlich nichts dazu einstellen.
Ich fahre einen festen Abstand vor, der nur von der Fahrzeuglänge beeinflusst wird.

**Comment by Andii1980** [comment]
Ah okay. Danke für die info. Dann bleibt die fruchtumfahrung solange aus. 🤣

**Comment by hoefti10** [comment]
Ups, sorry 😁
