### ISSUE TITLE
Anfrage erweiterte Funktion Parken-Button  -  Inquiry advanced function parking button

### ISSUE THREAD

**Issue by haamic** [Stephan-S/FS19_AutoDrive#403]
Hallo Stephan,
wäre es möglich die Funktion den Parkens zu erweitern? Ich meine den angehangenen Geräten eine Parkposition zuzuweisen, die dann an der Zugmaschine auswählbar (entweder P-Zugmachine oder P-Gerät) ist und angefahren werden kann?
Wer nicht für jedes Gerät, z.b. Pflug, Saatmaschine, usw., eine eigene Zugmaschine hat, könnte so anhand der angehangenen Geräte, diese parken. Weiterführend evtl. sogar dort automatisch abkoppeln (Q) und auf seine eigene Parkposition fahren....
Ist nur so eine Idee, ob das umsetzbar ist, weiss ich nicht
Gruss Micha
------------------------------------------------------------------------------
Hello, Stephan,
would it be possible to extend the function of parking? I mean to assign a parking position to the attached devices, which can then be selected on the tractor (either P tractor or P device) and can be approached?
If you do not have your own tractor for every implement, e.g. plough, seed drill, etc., you could park it using the attached implements. Continuing, you might even uncouple (Q) automatically there and drive to your own parking position....
If only such an idea is, whether this is convertible, I do not know
Greetings Micha

Translated with www.DeepL.com/Translator

**Comment by Stephan-S** [comment]
Sorry, but I won't implement this. Too much work for too few users who would use that
