### ISSUE TITLE
Server Fehler

### ISSUE THREAD

**Issue by Bandesss** [Stephan-S/FS19_AutoDrive#404]
Hallo Stefan, ein ganz neuer Fehler auf unseren Server
Hab das Log beigepackt
Gruss Bandes
[log.txt](https://github.com/Stephan-S/FS19_AutoDrive/files/3537090/log.txt)

**Comment by Stephan-S** [comment]
Hey, du meinst den Mouseevent Error? Ja, da kommt im nächsten Release ein fix für. Ist auch im SP.
Wie läuft AD denn sonst auf dem Server für euch? Das ist leider ein Aspekt den ich kaum selber testen kann

**Comment by Bandesss** [comment]
Ja. wenns erstmal läuft dann ist es ok.

Danke für die Information

**Comment by J0hnHawk** [comment]
Ich häng' mich hier mal wegen der Frage dran: 
> Wie läuft AD denn sonst auf dem Server für euch? Das ist leider ein Aspekt den ich kaum selber testen kann

Leider fängt das Spiel bei mehreren Autodrivefahrern bei uns mal mehr mal weniger an zu laggen (bei 'nem Ping um die 35ms - die Internetverbindung würde ich daher ausschließen). 

Leider lässt es sich nicht so recht einordnen. Wir haben schon mehrere andere Mods herunter geschmissen. Lagfrei wird es aber eigentlich erst, wenn man Autodrive deaktiviert. Fakt ist, dass wenn man alleine auf dem Server ist, es eigentlich ok ist. Sobald ein 2. Spieler dazu kommt und man mehrere Fahrer los schickt wirds ruckelig. Meine Vernutung war zunächst, dass Autodrive beim Fahren ja ständig die Geschwindigkeit und den Lenkeinschlag berechnen müsste. Wir haben daher mal die Routenkalkulation auf 0,5 gestellt. Einen Unterschied zu der voreingestellten 1,0 merke ich jedoch nicht. Dazu passt auch, dass es auch laggt, wenn die Autodrivefahrer gerade auf den Drescher warten und gar nicht selber fahren.

Allerding nehmen wir die Lags dann doch gerne in Kauf. Die ganzen Überführungsfahrten sind mit Autodrive eine wahre Erleichterung. Und ein Rübenfeld ohne automatischen Abfahrer abzuernten ist schon dröge.

**Comment by Bandesss** [comment]
Ich habe immer noch Probleme auf dem Server kein Importieren der Kurse.
Mal geht mal nicht
