### ISSUE TITLE
Missing .lua

### ISSUE THREAD

**Issue by eddiem54** [Stephan-S/FS19_AutoDrive#405]
Hi,
Getting this error in log.
Error: Can't load resource 'C:/Users/eddie/OneDrive/Documents/My Games/FarmingSimulator2019/mods/FS19_AutoDrive/gui/settingsGui.lua'

**Comment by Stephan-S** [comment]
Danke. Ganz vergessen die gelöschte lua nicht mehr laden zu lassen.
