### ISSUE TITLE
type of product 

### ISSUE THREAD

**Issue by Duveleir** [Stephan-S/FS19_AutoDrive#406]
how do i chance the product that you want to pick up and deliver ?
i cant findt it

**Comment by alpha117** [comment]
make sure you change to the correct mode

![image](https://user-images.githubusercontent.com/30005040/63646424-4c95d900-c70a-11e9-883a-679a286a2839.png)

**Comment by Bobster82** [comment]
I think he meant where he can change the product type.
You need to click in the yellow area @Duveleir 
![ad menu select product](https://user-images.githubusercontent.com/47780758/63650326-ca2d0980-c749-11e9-855e-8370d569cfaa.png)

**Comment by Duveleir** [comment]
Thx i already figured it out

**Comment by Bobster82** [comment]
> Thx i already figured it out

Ah ok, then this can be closed ;)
