### ISSUE TITLE
Was für ein Fehler ist das ?

### ISSUE THREAD

**Issue by rmn18** [Stephan-S/FS19_AutoDrive#407]
Habe diesen Fehler hier in meiner Log Datei :  /FarmingSimulator2019/mods/FS19_AutoDrive/gui/settingsGui.lua:101: attempt to index a nil value

hänge mal meine Log mit dran hier ,fllt kuck wer mal drüber ob nen Mod vllt dran Schuld ist.
[log.txt](https://github.com/Stephan-S/FS19_AutoDrive/files/3541129/log.txt)

**Comment by rmn18** [comment]
Moin 

Ich bekomme diesen Fehler hier : /FarmingSimulator2019/mods/FS19_AutoDrive/gui/settingsGui.lua:101: attempt to index a nil value

finde ich in der Log Datei bei mir .Ich hänge mal meine komplette Log Datei dran hier .

**Comment by plexten** [comment]
Der fehler wurde bereits behoben. Entweder auf die neue Version warten oder selst packen.

**Comment by Stephan-S** [comment]
Genau. Ich bin gerade noch an einem anderen Feature dran, wenn ich damit soweit bin, packe ich einen neuen Release :-)
