### ISSUE TITLE
Unloading Combine before 100%?

### ISSUE THREAD

**Issue by sootysax** [Stephan-S/FS19_AutoDrive#409]
Is it possible that AD can send the tractor to unload the combine before reaching 100%?  Maybe a toggle to set it at 50% or 80%?

**Comment by Bobster82** [comment]
@sootysax , you can adjust that in the autodrive menu by pressing ctr+alt+kepad0

![ad menu](https://user-images.githubusercontent.com/47780758/63705468-814e8100-c82d-11e9-9711-14bc4a686c80.jpg)

**Comment by Stephan-S** [comment]
@Bobster82 this setting is only used to determine whether a driver drives to the unloading destination (not the combine) after unloading the combine or whether it should park/wait for another call from a combine.

@sootysax Now, with the current implementation, the drivers who get called are assigned a specific static target, which is the pipe of the combine. So if the combine is still moving, this won't work.
But you can always manually call a driver if you sit in a combine. Just have to assign a keybinding in the menu

**Comment by Bobster82** [comment]
Sorry,.. I misread it

**Comment by Stephan-S** [comment]
No problem. I'm always happy if someone is helping out here. Thank you for that 👍

**Comment by Stephan-S** [comment]
have you extended the pipe on the combine?
And if 'drive to combine' and then AD shuts off, the pathfinding couldn't find a path.
Could you send me the savegame so I can investigate this?
For starters, you can disable fruit detection in the AD options and see if that helps.

**Comment by auddie2015** [comment]
Since forage harvesters must move while unloading, may I suggest this as a possible future feature? Though you said "current implementation" so I guess you had plans at some point. heh
