### ISSUE TITLE
Untermenüs für die Zielpunkte

### ISSUE THREAD

**Issue by CairoAmun** [Stephan-S/FS19_AutoDrive#410]
Hallo Stephan,
ich hätte eine Frage, bzw. einen Vorschlag. Die Liste meiner Zielpunkte im AD - Menü ist inzwischen sehr lang geworden und es kommen sicher noch einige dazu.
Wäre es möglich in diesem Drop-Down-Menü Ordner einzubauen in denen man dann Zielpunkte einer bestimmten Kategorie ablegen könnte? Das wäre eine echte Bedienungserleichterung. Vielleicht siehst Du eine Möglichkeit, das zu realisieren.

Viele Grüße
Cairo / Michael

**Comment by Stephan-S** [comment]
Hey Cairo,

ja den Vorschlag habe ich aus deinem Video aufgeschnappt :-)
Danke für's Erstellen des Issues, so vergesse ich es hoffentlich nicht :-)

Ich bin gerade noch an einem anderen Feature dran und dann wollte ich hier mal ein paar Issues abarbeiten. Aber deins ist ja nicht ganz trivial, also muss ich mal schauen wann bzw. wie schnell ich das umsetzen kann.

Viele Grüße,
Stephan

**Comment by CairoAmun** [comment]
Hi Stephan,
vielen Dank, hat ja keine Eile, ich komme ja auch so gut zurecht, wenn ich Dich recht verstehe ist das aber möglich. Also freue ich mich und warte einfach.
Danke übrigens, das Du meine Videos verfolgst. 
Viele Grüße 
Cairo

**Comment by Stephan-S** [comment]
Hey Cairo, bin jetzt mit meinem neuen Feauture (BGA entladen) soweit durch.
Ich überlege nun wie ich die Ordnerstruktur am Besten integrieren kann.
Mein aktueller Plan:
 
1.) Wenn die Pulldown-Liste geöffnet wird, gibt es ganz oben ein neues Icon (+) um einen neuen Ordner zu erzeugen. 
2.) Beim ersten Erstellen landen alle Ziele im Ordner 'All' / 'Alle'
3.) Ordner sind standardmäßig entweder auf oder zugeklappt und der Zustand wird pro Fahrzeug und Ordner gespeichert.
4.) Jedes Ziel hat zwei kleine Pfeile ^/v mit denen sie in den Ordner darüber/darunter verschoben werden können.
5.) Das ganze System sollte wahlweise in den Optionen abstellbar sein.

Da HUD-Designen etwas anstrengend im LS ist, würde ich gerne vorher ein bisschen Ideen hin und herwerfen bevor ich mich an die 'fummelige' Implementierung dazu mache :-)
Also wenn du Kritiken/Verbesserungsvorschläge zu dem Plan hast, meld dich doch gerne.

Alternativplan: Ich passe die Größe des Pulldown Menüs an die Anzahl Zielpunkte an und füge dementsprechend mehrere Spalten hinzu. Dann wäre alles auf einen Blick angezeigt aber ohne Ordnerstruktur. Dann müsste die Sortierung über die Namen ausreichen.

P.S.: Deine Videos schaue ich doch immer gerne und nehme das Feedback dankend mit. Allerdings schaffe ich natürlich auch nicht immer alles :-)

Viele Grüße,
Stephan

**Comment by CairoAmun** [comment]
Hallo Stephan,

wenn ich ehrlich bin gefällt mir die erste Variante deutlich besser. Genau so hatte ich mir das Vorgestellt, um die verschiedenen Zielpunkte zu sortieren.
Bei der zweiten Variante hab ich gewisse Zweifel. Wenn ich meine Karte mit 42 Feldern mal nehme und die Karte vollständig vernetze, mit allen Fabriken und Verkaufsstellen plus Parkplätze und diverse Ziele für Tankstellen und Waldgebiete, wäre am Ende mein Bildschirm zugepflastert, wenn ich das Menü öffne. 
Das man das Menü in dieser Form in den Einstellungen wahlweise ein- und abschalten kann ist eine tolle Idee. Also, wenn ich mir das wünschen könnte, würde ich mich voll und ganz für die erste Lösung mit allen den 5 Punkten entscheiden.

Nochmals vielen Dank, das Du für die Ideen der User Deines Mods immer ein offenes Ohr hast. Das ist sehr viel wert.

Beste Grüße
Cairo

**Comment by CairoAmun** [comment]
Hallo Stephan,

ich habe gesehen, das Du die Ordnerstruktur eingebaut hast. Ich habe diese in den Einstellungen auch aktivert. Ich kann aber keine Ordner erstellen oder Zielpunkte verschieben. Bin ich nur verpeilt oder ist das nur eine Vorbereitung, die derzeit ohne Funktion ist. Sobald ich auf das Plus klicke, verschwinden alle Huds vom Bildschirm, ich kann aber nirgendwo einen neuen Namen für einen Ordner eingeben. Mit der ESC Taste kommen dann alle Huds wieder. Kannst Du mir sagen, was ich da für einen Denkfehler drin habe?
Dann sind mir noch einige andere Dinge aufgefallen, die nicht mehr richtig funktionieren.
Meine Frage, soll ich mal in einem Sammelbeitrag alles auflisten, oder möchtest Du für jedes Problem ein eigenes Issue damit es nicht zu unübersichtlich wird?
Wenn Du mir nochmal Deine E-Mailadresse zukommen lassen würdest, könnte ich dir das auch per Mail senden.
Das wäre vielleicht der bessere Weg.

Beste Grüße Cairo

**Comment by Stephan-S** [comment]
Hey Cairo,

Mach am Besten ein neues Issue mit allen Punkten auf. Dann sieht auch jeder das sie gemeldet sind.
Ich hab schon den Fehler wegen dem nicht öffnenden HUD beim Erstellen einer Gruppe/Ordner gefunden und behoben. Ich lade heute Abend dann den Fix hoch.

Viele Grüße,
Stephan

**Comment by CairoAmun** [comment]
Moin Stephan,
nach dem neuen Update ( 1.0.5.4 friert das Spiel direkt nach dem Start ein. Es passiert im Grunde das, was ich gestern schon beschrieben hatte, als ich versucht habe im AD Menü auf das Pluszeichen zu klicken, um einen neuen Ordner zu erstellen. Danach waren ja alle Huds weg und man musste neu starten. Jetzt passiert das bereits beim Start. Es werden keine Huds angezeigt und beim ersten Tab um in ein Fahrzeug zu steigen stürzt das Spiel ab. 
Das Zurücksetzten auf die Version 1.0.5.3 funktioniert aber ohne Probleme, so dass man das Spiel dann wieder nutzen kann.

Viele Grüße Michael

**Comment by CairoAmun** [comment]
Hallo Stephan,
mit der letzten Version 1.0.5.6 funktioniert das Menü einwandfrei. Ich kann problemlos Ordner erstellen und Zielpunkte in die entsprechenden Ordner verschieben. Ich bin richtig happy, das Du das hinbekommen hast.
2 Fragen hätte ich noch:
1. Wäre es möglich, das die Ordner alphabetisch angezeigt werden können? Derzeit erfolgt die Sortierung ja in der Reihenfolge, wie sie erstellt werden.
2. Kann man es so einrichten, das die Ordner generell bei Start des Spieles geschlossen sind?

Wenn das klappen würde, würde ich mich riesig freuen. Danke nochmal dafür, das Du das Menü eingebaut hast.

Viele Grüße Cairo/Michael
