### ISSUE TITLE
Generate turn speeds for Courseplay courses

### ISSUE THREAD

**Issue by sootysax** [Stephan-S/FS19_AutoDrive#411]
Is there any way that AD can generate speed information for use when Courseplay generates an AD course?   I cannot make any deliveries because CP loses the path around turns, then snakes back and forth until it crashes into something.

**Comment by Stephan-S** [comment]
The courseplay devs are already working on something similar as AD does.
I think they want to caclulate this themselves and not drive exactly as AD :-)
