### ISSUE TITLE
Neues Course Editor Problem

### ISSUE THREAD

**Issue by gfa4711** [Stephan-S/FS19_AutoDrive#414]
Ich habe nochmal ein Problem mit dem Course Editor.
Inzwischen bin ich auf die Multimap 2019 umgestiegen und habe die beigepackten Kurse als Basis in meinem Spiel genommen. Diese habe ich deutlich erweitert und ich konnte die auch wunderbar editieren.
Seit zwei Tagen lädt aber der Course Editor meine Kurse nicht mehr richtig (siehe Bild).
Ich kann nichts verschieben, anklicken oder erstellen.
![Course_Editor_Multimap](https://user-images.githubusercontent.com/53525488/63771353-528ce500-c8d7-11e9-9be6-529b5ad6a215.PNG)

Im Spiel selber funktioniert alles ohne Probleme.
Ich habe versucht die Config-Datei selber zu untersuchen. Dazu habe ich die mapmarker von mir entfern, leider ohne Erfolg. Ich vermute, dass die Datei zu groß geworden ist (die Ladezeiten des Course Editor sind schon recht lang geworden) oder es bei den waypoints ein Problem gibt.
Die konnte ich leider nicht wirklich analysieren, das Datenformat zwar sehr platzsparend ist, aber leider auch sehr unübersichtlich.

Danke schon Mal und viele Grüße
gfa4711

[AutoDrive_Multimap_2019_config.zip](https://github.com/Stephan-S/FS19_AutoDrive/files/3546029/AutoDrive_Multimap_2019_config.zip)

**Comment by Stephan-S** [comment]
Hey, I quickly tested you config. I don't have the pda map file available. But at least it loaded fine.
But given the large config file, it took a moment to load all nodes.
Could you send me the pda file, I will update the editor, so the map should be properly shown when loading the config. Thank you!

**Comment by gfa4711** [comment]
Here is the Map File.

Thanks for your help!


[Multimap_2019.zip](https://github.com/Stephan-S/FS19_AutoDrive/files/3546416/Multimap_2019.zip)

**Comment by Stephan-S** [comment]
Done. please check the new version of the editor :-)

**Comment by gfa4711** [comment]
Now it works, thank you very much.

I also had to change another thing.
My Java installation was for some unknown reasons 32 bit and the old error occurred.
Java postet a OutOfMemoryError.
To get it work, I wrote a batch file to start the course editor with extended memory:

`java.exe -Xmx512M -Xms64M -jar .\AD.jar`

Alternatively I changed to Java 64 bit and there it worked out of scratch.

Maybe it is useful for other users to document this somewhere.

Have a nice day
gfa4711
