### ISSUE TITLE
Error Log: Open xml file

### ISSUE THREAD

**Issue by biomex81** [Stephan-S/FS19_AutoDrive#415]
On start mission:
Error: Failed to open xml file 'C:/Users/Jo Real/Documents/my games/FarmingSimulator2019/mods/FS19_AutoDrive/modDesc.xml'.
Load mod: FS19_AutoDrive (Hash: c14fb44b84edade64e00182c1b1b3309)
Error: Missing descVersion attribute in mod FS19_AutoDrive

**Comment by Stephan-S** [comment]
Servus, lad dir den Mod mal neu runter. Da scheint bei dir was an der Datei defekt zu sein

**Comment by biomex81** [comment]
Ok, solved, THX ;)
