### ISSUE TITLE
Autodrive course editor cannot save

### ISSUE THREAD

**Issue by Martinnygaard** [Stephan-S/FS19_AutoDrive#416]
Hi,

Somehow when I click "Save" and choose a filename "AutoDrive_Fenton_Forest_4X_By_Stevie_V1_42__config" nothing happens.

It does not create a new file.

The Map is fenton forrest 4x
The editor part of the program works just fine - only save does not work for me.

[AutoDrive_Fenton_Forest_4X_By_Stevie_V1_42_2_config.txt](https://github.com/Stephan-S/FS19_AutoDrive/files/3546400/AutoDrive_Fenton_Forest_4X_By_Stevie_V1_42_2_config.txt)
(File is named .txt in order to upload to Github - it is ofcourse a .xml-file)

This is the PDA (2048x2048 .PNG file) 
![FentonForrest](https://user-images.githubusercontent.com/26490587/63776345-81a85400-c8e1-11e9-83ac-3b49163d04c4.png)

**Comment by Stephan-S** [comment]
hm, strange.
I just tested it with your config and map file and everything loads and saves just fine. Doesn't matter if I choose a new file or update the currently loaded one.
Could you try the new AD.jar I just uploaded?

**Comment by Martinnygaard** [comment]
Thanks for you fase response - that's what makes it worth raising these issues :)

No, it does still not work.


I do as follow:

1. Open AD.jar
2. Click "four times maps"
3. Load config file
4. Load Map
5. Change a bit - move and connect some points
6. Click save (It automatically enter the name of the last file - en this case, the map image (FentonForrest.png)
7. Change name to "AutoDrive_Fenton_Forest_4X_By_Stevie_V1_42__config.xml"
8. Click save again

Nothing happend.

**Comment by alpha117** [comment]
just tried and all OK here

**Comment by Stephan-S** [comment]
>     8\. Click save again

This is obviously the save button in the filemanager where you select the file and not the save button of the editor, right ? :-)

Are you sure you have the rights to save the file there?

**Comment by alpha117** [comment]
@Stephan, have you made any changes to the editor, as it still shows version 0.1?

**Comment by Stephan-S** [comment]
Just a minor fix to rescale the map after loading the config. Not really worth updating the versioning on the editor for that :-)

**Comment by alpha117** [comment]
cool, thanks

**Comment by Roby1164** [comment]
have another problem, save saves, but not completely, if I open the editor, make even a small change, then save, the file it creates is smaller and incomplete, but to be more precise, on the map of the editors you see all the paths and they look right, but then on the map, there aren't really connections. Now what I've noticed is that the file saved is always 1.728KB, and it doesn't go further, there is a limit somewhere ?? I attach two images, the first the file, before editing with the editor, the second the saved file, as you can see, the size is clearly different.
![Screenshot_1](https://user-images.githubusercontent.com/24955554/63795382-1fad1600-c904-11e9-9e22-ff403d2f33e8.jpg)
![Screenshot_2](https://user-images.githubusercontent.com/24955554/63795389-220f7000-c904-11e9-8d14-e2e90501a5a3.jpg)

**Comment by Stephan-S** [comment]
Hey, just load the smaller file into the game and then hit 'recalculate'. The small file doesn't contain the paths to the destinations that you create when pressing recalculate.
The editor can't calculate them, so he doesn't save them -> smaller file size

**Comment by Roby1164** [comment]
> Hey, just load the smaller file into the game and then hit 'recalculate'. The small file doesn't contain the paths to the destinations that you create when pressing recalculate.
> The editor can't calculate them, so he doesn't save them -> smaller file size

Ok.... Ty

**Comment by Martinnygaard** [comment]
> > ```
> > 8\. Click save again
> > ```
> 
> This is obviously the save button in the filemanager where you select the file and not the save button of the editor, right ? :-)
> 
> Are you sure you have the rights to save the file there?

Yes, of course :-) 
The pop-up where i type in file name (or select old) and press save :-)

**Comment by badfly** [comment]
I also do not save (google translate)

**Comment by Dzi4d3k** [comment]
@Martinnygaard did you came to solution? If yes, then it may be useful for further reference instead of empty closure.

**Comment by Martinnygaard** [comment]
No, i did not. 
after some time (and some updates on the editor part) i tried again, and now it works.
(I only use the one with command prompt to show log duing all steps.

Its working for me, and i don't know why ;-)

**Comment by badfly** [comment]
https://github.com/Stephan-S/FS19_AutoDrive/issues/521
