### ISSUE TITLE
It no longer opens the seeder doors

### ISSUE THREAD

**Issue by Roby1164** [Stephan-S/FS19_AutoDrive#418]
With 1.0.5.0, the problems already existed, which did not load the seeder from the silo, in combination with the CP, but now with this release, it no longer opens the doors / covers, as well as not automatically loading.

**Comment by Stephan-S** [comment]
How close are the loading triggers to the destination?

**Comment by Roby1164** [comment]
I'm next to the field I'm working on ....
Look at the picture, I point you more or less where I am, keep in mind that field 25 on the Fenton is pretty big.
![Screenshot_3](https://user-images.githubusercontent.com/24955554/63796896-386afb00-c907-11e9-93e6-0de5f352114d.jpg)

**Comment by Stephan-S** [comment]
The question is not where you are, but where the destionation point is, relative to the triggers.
Could you send me the savegame if you don't mind?
Would like to check that out for myself and fix the code, if something is wrong in the current release

**Comment by Roby1164** [comment]
The problem with passing the savegame, is that there are custom mods, which you don't find on the net, mostly for the translations done, in addition to the mod of which I use.
But I don't understand what you mean by destination?
The vehicle is sowing the field with the CP, when the seeds finish, they usually end, and not the fertilizer, he leaves to go and load, but coem said, up to 1.0.4.9, the lids opened, but then not loaded, now with 1.0.5.0 they don't even open anymore, but the destination, the loading point, reaches it regularly, first with the open kopecks, it stopped, waiting for the load that didn't happen, now, with the covers closed, immediately restarts and begins to go around, going back to the work point, and repeating the operation.
![Screenshot_1](https://user-images.githubusercontent.com/24955554/63799995-81be4900-c90d-11e9-8466-7577300d32e5.jpg)

**Comment by Stephan-S** [comment]
Okay, Roby you are really confusinbg me now.
Are you using CP for the refill courses or AD?
If you are using AD, then your settings in the HUD (Which you only partially show) are not correct.
1.) Your destination (Upper name) should probably be 'Campo 25' or whatever field you are letting CP work on.
2.) Your loading destination (Lower one) should be 'Semi C25' if you want to refill seeds. Then your fertilizer triggers on the road ahead won't load, but seeds will. If you want both to load, your triggers have to be IN FRONT of the loading destination and NO MORE THAN 20 METERS away.
So best place the triggers close together if you already placed some freely on the map.

3.) You filltype should not be Soybeans but 'Seeds' or 'Fertilizer'

If you set everything up as I said, this should work flawlessly :-)

**Comment by Roby1164** [comment]
Then I use the CP for planting the field, but AD for reloading, activating the option present in the CP.
Ok, the image I sent you before, had the wrong points, since I had modified with the editor, and when you then save, he resets the points, and sets the last one you created with that medium.
I have always put the first point of destination the field to be worked, and in the second, the destination where the loading silo is, but if with 1.0.4.9, it opened the doors but did not load, now it just does not even open the in addition, if I try to position myself before the first point, field 25, and only with AD I order him to start the path, to go to load, now comes the first point and stops, does not go further, even pressing the continue key, I am attaching another photo, of the AD test only, but it does not go, not even manually opening the lids, first opening the lids manually and starting AD, he started and went to load, if you did not open the covers, he opened them, but it didn't load.
![Screenshot_3](https://user-images.githubusercontent.com/24955554/63801965-de236780-c911-11e9-969a-0c94e1e89e7c.jpg)

**Comment by Stephan-S** [comment]
Your seeder is almost full. If you activate AD in this state, he will skip the loading part and head directly for the field destination. If this path happens to take him by the refill triggers, he will open the covers, as this is sort of decoupled, but he will not load anything.
Man, this must be frustrating for you :-)

**Comment by Roby1164** [comment]
Ok now it's all sown, tomorrow I will do other tests, and I'll let you know, but today, the only difference was the fruit in the second row, which I put the seed I was using, and not the generic "seeds", and how said, with 1.0.4.9, it started, when it reached a certain distance of the loading silo, it opened the covers, but then it didn't load, while I repeat with this release, it no longer opens the covers, besides not loading ...
I'll update you tomorrow ...

**Comment by Stephan-S** [comment]
@Roby1164 I'm so sorry. I was so focused on finding out what setting you might have set wrong, that I didn't really check the feature for myself.
And you were right. The covers did not open and thus they didn't reload.

I already pushed release 1.0.5.1 with the fix included.

Is there anyway I can offer you a coffee? :D Sorry again :-)

**Comment by Roby1164** [comment]
No problem, we collaborate, and sooner or later we come to a solution .....;)

**Comment by Roby1164** [comment]
Ok, I tried, by unloading the seeder, and now it works, the lids open, and it loads, and leaving it closes again, at least only with AD, tomorrow I'll try in combination with the CP.
I have yet to figure out how to load both the seeds and the fermenter, hoping to get near the two silos, but it only loads seeds, and then it goes away, without loading the fertilizer, even if empty, the option in the menu is active. ..
