### ISSUE TITLE
Amount to load

### ISSUE THREAD

**Issue by Roby1164** [Stephan-S/FS19_AutoDrive#42]
Is it possible to enter the amount of product to be loaded?
For example now, if you want to make a journey that the tractor with a trailer goes to the silos, load a product to feed the cows, you can do it, but load the whole trailer, and if there isn't enough product in the silo, to fill it it stops, while if it were possible to insert a quantity to load, this problem would not exist, moreover it would be possible to use it to load only the necessary quantity ... Ok, maybe I expect a little, but asking doesn't hurt .... .: D

**Comment by Stephan-S** [comment]
Well you can always ask :-)
My goal is to keep the HUD as simple as possible.
But I could implement an automatic "drive if silo is empty/unload point full" function
Is that sufficient?

**Comment by Roby1164** [comment]
Yes, it could already be something, if one of the problems solves, that of the vehicle that does not start, if the trailer is not full ....
