### ISSUE TITLE
ConfigXML verkleinern

### ISSUE THREAD

**Issue by Berios** [Stephan-S/FS19_AutoDrive#421]
Hallo Stephan!

Erst einmal vielen Dank für die super Arbeit - Autodrive ist ein super Mod und Deine Schnelligkeit bei Problembehebungen auch in Bezug auf Fremdprogramme wie Courseplay oder GC ist wirklich beeindruckend. Ich ziehe den Hut vor Dir und Deiner super Arbeit.

Ich hätte aber mal eine Frage:
Da die Multimap meine nächste Karte wird, habe ich sie jetzt in mühsamer Kleinarbeit genau so eingefahren, wie ich sie haben möchte. Leider ist meine ConfigXML mittlerweile knapp 20 MB groß. Gibt es eine Möglichkeit, die Datei zu verkleinern (ohne die Daten zu darin zu löschen :-))?

Danke für Deine Hilfe schon jetzt im Voraus.

**Comment by Stephan-S** [comment]
Hey, danke für die netten Worte :-)
Kann es sein, dass du Ziele hast, die nicht von jedem Punkt aus erreichbar sind?
Wenn das Netz ein großes zusammenhängendes Streckennetz ist, habe ich ein paar Optimierungen eingebaut die greifen können und die Datei kleiner machen.
Beispielsweise ist ja bei einer langen Strecke ohne Abzweigungen, immer der nächste Knoten auch gleichzeitig der 'nächste' Knoten egal zu welchem Ziel man navigiert. Dann muss ich dafür genau eine Zahl speichern.
Wenn nun aber eins oder mehrere Ziele nicht erreichbar sind von diesem Knoten, falle ich zurück auf das Muster: 'Für jedes Ziel, genau speichern, welcher Knoten mein Nachfolgeknoten ist'
Wenn du also bereits 100 Ziele hast, sind es dann plötzlich 100 Zahlen statt einer.
Wenn wir das nun auf 20000 Punkte hochrechnen, sind wir bei 2 Millionen Zahlen statt 20 Tausend.

Das er optimiert, siehst du wenn in der Config die Zeile
    <markerID>=,2;=,3;=,4;=,5;=,6;=,7;=,8;=,9;=,10;=,11 so oder so ähnlich anfängt.
Falls hier bei dir zwischen zwei Semikolons ( ; ) immer viele Zahlen stehen, dann sind nicht alle Ziele gleich/ bzw. überhaupt erreichbar.
Dann lohnt es sich das mal zu überprüfen.
Einen kleinen Hinweis kann dir in dieser Zeile die Zahl '-1' geben. Das heißt das entsprechende Ziel konnte nicht erreicht werden.

Kannst mir auch gern mal die Log schicken und ich werf mal einen Blick rein. Das klingt ja nach einem wahnsinnigen Netzwek bei 20Mb :D

**Comment by Berios** [comment]
Hallo Stephan! 

Vielen Dank für die schnelle Antwort. :-)
Und die netten Worte waren wirklich ernst gemeint und nicht nur so dahin gesagt.

Naja, 42 Felder a 20 Anfahrpunkte (beide gleichzeitig Anfahr- und Abfahrpunkte) sind schon 84 Locations. Dazu die fixen Abladepunkte, der Hof und einige "freie" Punkte. Ich habe eigentlich (nach meinem Ermessen und meiner Meinung fast gar keinen Punkt, der nicht "fließend" verbunden ist. Allerdings habe ich auch sehr viel gelöscht und dann neu eingefahren. Aber Du siehst das wahrscheinlich sofort, wenn Du in die Log schaust. Da sind tatsächlich viele "-1" drin. Aber in der Karte sind alle Punkte "verbunden" (sieht zumindest für einen Laien wir mich so aus).

Vielen Dank, daß Du Dich der Sache annimmst - Du hast bestimmt auch besseres zu tun. 

[AutoDrive_Multimap_2019_config.zip](https://github.com/Stephan-S/FS19_AutoDrive/files/3547820/AutoDrive_Multimap_2019_config.zip)

**Comment by Stephan-S** [comment]
Oh ja, das ist ein großes Netzwerk 🗡 

![Unbenannt](https://user-images.githubusercontent.com/5493976/63803778-ec738280-c915-11e9-8877-eb2a764b2e3e.PNG)

Also die config sieht soweit sauber aus. Klar ein paar Punkte scheinen noch etwas losgelöst zu sein, aber der wichtige Punkt ist ja, dass alle Ziele immer erreichbar sind. Und das ist gegeben. Dementsprechend ist die Datei schon soweit optimiert, wie ich es derzeit vorgesehen habe.

Aber sie ist ja auch 'nur' 3,2 MB, nicht 20 ;-) 
Macht die Größe denn Probleme beim Arbeiten mit dem Mod?
Das Laden und Schreiben an sich sollte sich ja eigentlich trotzdem in Grenzen halten beim Starten bzw. Speichern des Spiels. Da habe ich auch schon einige Zeit investiert.

Beste Grüße,
Stephan

**Comment by Berios** [comment]
Ich wollte eigentlich noch die Felder alles "umranden". :-)
Habe es dann aber gelassen - dann würde die xml nochmal doppelt so groß sein.
Das Arbeiten mit dem Mod ist super. Läuft perfekt. Das einzige Manko ist die Zeit beim Neubrechnen. 
Ich lasse die Berechnung schon auf 100fach laufen, sie dauert aber auf meinem Rechner ca. 4-5 Minuten. Deshalb auch die Frage nach der "Verkleinerung". :-)
Irgendwie habe ich in Bezug auf die Größe der Datei entweder einen Rechenfehler gemacht oder bin blind. :-) Sorry für die falsche Angabe. 
Aber wenn die config soweit sauber ist, dann nehme ich die längere Neuberechnungszeit sehr gerne in Kauf. Wenn alles berechnet ist, dann ist das Spielen mit Autodrive einfach nur genial. Und seit ihr die Schnittstelle zu CP installiert habt, macht es noch viel mehr Laune (was allerdings sehr schwer ist, da schon vorher genial). :-)

Vielen Dank für Deine Mühe und mache so weiter. Ich freue mich schon auf das, was Du noch aus dem Hut zauberst. :-)

Berios

**Comment by Stephan-S** [comment]
Super, freut mich!

Dann aber ganz kurz. Die Größe der Datei hat tatsächlich quasi nichts mit der Berechnungszeit zu tun.
Die ergibt sich grob gesagt aus: Ziele * Wegpunkte * X
Sprich wenn du 25000 Wegpunkt aber nur 10 Ziele hast, geht's noch recht schnell. Bei 100 Zielen dauerts dann zehnmal so lange. Da bekomme ich auch glaube ich nichts mehr rausgekitzelt.



> Ich freue mich schon auf das, was Du noch aus dem Hut zauberst. :-)

Kannst mir ja bei Gelegenheit und bei Lust und Laune mal Feedback zum BGA Entlader geben, den ich heute als Modus mit in den Release gepackt habe. Das ist mein aktuelles Projektchen :-)

**Comment by Berios** [comment]
Mache ich gerne - muß mich aber erst mal eben damit beschäftigen.
Die Vorlage für die Karte ist jetzt fertig. Jetzt gehe ich mal ans Spielen. Dabei werde ich ihn dann super gerne ausprobieren und Dir ein Feedback geben. Erst einmal brauche ich jetzt Gras und Häckselgut. Viel Gras und viel Häckselgut. :-)

**Comment by Berios** [comment]
Hallo Stephan!

Ich habe die BGA Entladung mal auf den Prefab Silos der Multimap versucht
(sprich den fest verbauten Silos).
Leider hat das nicht geklappt. Es kann aber an der ungünstigen Lage der
Silos liegen. Meine bisherigen Feststellungen sind wie folgt:

1.) Knicklenker nimmt AD irgenwie gar nicht an. Der Knicklenker (bei mir
Radlader) bleibt nach dem Einstellen hinten stehen und vollführt mit dem
     forderen Teil eine Art "rumgehüpfe" :-) Sprich der fordere Teil bewegt
sich immer hin und her - leider bewegt sich der Radlader dabei aber weder
nach vorne noch nach hinten.
2.) Danach habe ich es mit einem Telelader versucht - dieser fährt korrekt
in der Silo und nimmt auch Material auf. Danach fährt er auf der Multimap
aber Richtung Südpol, ohne das
     Gespann zu finden. Da ich das linke Silo versucht habe, mußte ich das
Gespann am Rand in die Lücke zwischen Silo und Gebäude stellen. eventuell
lag es daran. Auf jeden Fall hat der Lader das
     Gespann so nicht gefunden (Traktor + Anhänger).

Ich werde die Sache auch noch mit einem freistehenden Silo versuchen,
sobald ich Ingame soweit bin (das liebe Geld :-)). Sobald ich hier ein
Ergebnis habe, melde ich mich wieder bei Dir.

Übrigens machen die LKW seit der letzten Version (1.0.5.5) Probleme - sie
finden die Wegpunkte scheinbar nicht mehr immer und fahren einfach durch.
Ich bin jetzt wieder auf die Version 1.0.5.1 zurück gegangen.
Da funktioniert alles soweit (bis auf die BGA - aber wie gesagt, momentan
noch nicht zu 100% durchgetestet). Außerdem funktioniert das Auffüllen von
Saatgut und Dünger in einer Tour nicht mehr (auch bei 1.0.5.1 nicht).
Die Sache mit den Ordnern ist super. Vielleicht findest Du noch einen
anderen Weg, die Wegpunkte in die Ordner zu verschieben. Das Durchschieben
von Oben nach Unten ist bei der Benutzung von mehreren Ordnern und
vielen Wegpunkten sagen wir mal "lästig" - man schiebt halt x - Wegpunkte
durch mehrere Ordner. Aber das ist "heulen" auf sehr hohem Niveau. :-)
Ansonsten wie immer top. :-)

Vielen Dank für den super Job.

Thomas




Am Di., 27. Aug. 2019 um 22:17 Uhr schrieb Stephan Schlosser <
notifications@github.com>:
