### ISSUE TITLE
New BGA mod

### ISSUE THREAD

**Issue by raxtor** [Stephan-S/FS19_AutoDrive#423]
So how it works... I did that 1 magic click and nothing :-)
![fsScreen_2019_08_27_23_28_59](https://user-images.githubusercontent.com/831266/63809465-a96bdc00-c922-11e9-9ba3-fe53348e3f54.png)

**Comment by Stephan-S** [comment]
He should tell you what's Missing.
But from your pic I assume He is Missing a Trailer :-) try that again with a tractor and a Trailer behind.

For now, AutoDrive doesn't handle Trucks without Trailers. Something I should really put in the todo list

**Comment by raxtor** [comment]
Tried tractor + trailer too... :-/ in whihc mode should be working trailer? Load and Delivery?

**Comment by Stephan-S** [comment]
Shouldn't Matter. I Just built in a Check If the trailer is standing still which only works If AD is active or you are sitting in it. Have to do something about that.
But it really should Print a message on the Screen If you start it and it can't find a shovel, a Bunker and a Trailer.
Is there No Message?

**Comment by raxtor** [comment]
Well, after game reloading (probably no course/waypoint defined or not refreshed), it works but...
![fsScreen_2019_08_28_00_39_08](https://user-images.githubusercontent.com/831266/63813073-c1e0f400-c92c-11e9-880a-82d11d3e312e.png)
- 1stly he crashed to bunker silo (red line)
- I adjusted shovel width to 2m
- tractor going closely to wall bud missed heap, nothing loaded.
- in reversing crashed to fences..

Are you thinking about loading from any heap on ground, would be nice too...

**Comment by raxtor** [comment]
its County Line BGA silo...if u want test it...

**Comment by raxtor** [comment]
btw can you move warning msg up and in red color? Always I have it in CP HUD.. also longer time for displaying would be nice mainly if its warning msg... maybe it should disappear after some user action, like click to mouse or so...

**Comment by Martinnygaard** [comment]
just two notes:

> For now, AutoDrive doesn't handle Trucks without Trailers. Something I should really put in the todo list

Is this also the case for normal AD stuff? I just planned to use the same truck as Raxtor, with a trailer (total of two trailers) to silo work - will that work?

> btw can you move warning msg up and in red color? Always I have it in CP HUD.. also longer time for displaying would be nice mainly if its warning msg... maybe it should disappear after some user action, like click to mouse or so...

What about moving the notification text up in the top right corner along with giants own notifications? in the same boxes as Giants do it? Would make it look more ginuine.

**Comment by Stephan-S** [comment]
It should work better now. Here's a little image that explains the 'fixed' points that should be freely reacheable by the driver. So generally, it will handle trailers better that are aligned 90° to the bunker, which I thought would be the natural way of pointing them in most cases.

![20190828093019_1](https://user-images.githubusercontent.com/5493976/63841801-bff64f80-c983-11e9-94fe-00cd5ab03a44.png)

**Comment by raxtor** [comment]
Tested.. morning version had some trouble to find trailer or maker proper turn manuver... latest update seems ok... 
![fsScreen_2019_08_28_11_24_19](https://user-images.githubusercontent.com/831266/63843789-43657000-c987-11e9-87f0-c9dfcae61b32.png)

but
![fsScreen_2019_08_28_11_07_46](https://user-images.githubusercontent.com/831266/63843745-2e88dc80-c987-11e9-96f6-203c44a73835.png)

also turning maneuver with shovel fully up seems a bit risky and heavy shovels can overturn vehicle... should be adjusted yet
![fsScreen_2019_08_28_11_25_50](https://user-images.githubusercontent.com/831266/63843819-4fe9c880-c987-11e9-8a90-e7c1231e3e2f.png)

Default wheel loader Volvo doesnt work in any mode with AD.. seems like bug.
![fsScreen_2019_08_28_11_28_15](https://user-images.githubusercontent.com/831266/63843830-55471300-c987-11e9-904f-693ebb8af74d.png)

**Comment by Stephan-S** [comment]
Thank you! But what it is the 'Default wheel loader Volvo'. I only have a New Holland in my current game. And a JCB which is flagged as mod

**Comment by raxtor** [comment]
Sry... its New Holland... yellow is Volvo for me :-) my fault

**Comment by raxtor** [comment]
Now pls add "Unload here" and abillity for load heap with loader like BGA mod is doing it. .-)  and truck support.. (btw id supported Wilson two bin trailers already for silo unloading?)

**Comment by kleinerblauer** [comment]
Leider hebt der Radlader beim Einfahren in das Silo die Schaufel so weit an, dass sie nur teilweise oder gar nicht gefüllt wird und er versucht dann durch das gesamte Silo zu fahren. Ich habe mehrere Radlader und Schaufeln probiert.

![2019-09-14 13_45_23-Farming Simulator 19](https://user-images.githubusercontent.com/48803564/64907741-d415ad00-d6f6-11e9-937e-3b66fc06ed32.png)
![2019-09-14 13_46_48-Farming Simulator 19](https://user-images.githubusercontent.com/48803564/64907742-d4ae4380-d6f6-11e9-805d-245ab58ee833.png)
