### ISSUE TITLE
Refill now not working

### ISSUE THREAD

**Issue by alpha117** [Stephan-S/FS19_AutoDrive#424]
Cover opens and closes just fine, but now does not stop at refill and only refills to 2% as it drives through the trigger(Fert).   Cannot get seed refill to work at all, was OK on previous version

![image](https://user-images.githubusercontent.com/30005040/63842042-d1d3f480-c97b-11e9-99b5-03855e1ac072.png)

**Comment by Stephan-S** [comment]
are you using version 1.0.5.1 or 1.0.5.0 ?

**Comment by alpha117** [comment]
1.0.5.1

**Comment by Stephan-S** [comment]
Hm, working just fine on my save, both 'Pickup & Delivery' and Load mode

![20190828111506_1](https://user-images.githubusercontent.com/5493976/63842672-5b3bf480-c985-11e9-99c9-f849a4bff758.jpg)
![20190828111654_1](https://user-images.githubusercontent.com/5493976/63842673-5b3bf480-c985-11e9-8195-b5ab4c032b8a.jpg)

**Comment by alpha117** [comment]
Strange 1, Changed destination and it filled OK, but it stopped at the fill destination before the one set

![image](https://user-images.githubusercontent.com/30005040/63843783-e06fdb00-c97e-11e9-9749-048d12a81f55.png)

**Comment by Stephan-S** [comment]
It stops as soon as a refill trigger is detected. When this is the point, then your first 'Fert Refill' point was simply too close.
AutoDrive only refills on approach to the destination. If your driver reached the destination it becomes inactive and waits to be manually loaded. Like if you send it to a field and want to refill it from an overloader etc

**Comment by alpha117** [comment]
cool, also just noticed the 'loop' counter does not seem to work, if you set it to '1', then during the course AD sets it back to 'infinity',  and will just keep driving the course, until you stop it

![image](https://user-images.githubusercontent.com/30005040/63844505-43ae3d00-c980-11e9-83ff-81aa369de795.png)
