### ISSUE TITLE
2 ways route - how properly use

### ISSUE THREAD

**Issue by raxtor** [Stephan-S/FS19_AutoDrive#425]
I have problem with blue line route integration to network. As you can see in image, AD uses splited 2 ways route as classic route node and doing there turning maneuver... Did I make wrong something or there is some trick?
![fsScreen_2019_08_28_09_11_41](https://user-images.githubusercontent.com/831266/63846826-df45aa80-c98c-11e9-9dac-a136fdfc9ed4.png)

@Stephan-S btw some **idea**.. what do u think about adding 2 ways route with possibility "set Left/Right distance" from course? 2m meters (should be editable) or so could be good for most of roads in FS. Than you should be able make many of road routes more easier :-) Just 1 route for both directions :-) Where u will need proper distance from object, like seeds, silos etc, u just switch route to classic "blue" with no distance.

And if there is possibility use splines from map, that you can pre-generate main roads...

**Comment by Stephan-S** [comment]
Hey, I included some adjustment in the recalculation process. So if you recalculate the routes with this update, the process will 'ignore' connections with an angle of more than 90°.
This could break some other connections which people may have done manually but it shoud definitely stop these issues with the two way roads

**Comment by raxtor** [comment]
Will test it later and let you know...

**Comment by raxtor** [comment]
Seems fixed... ty

**Comment by Stephan-S** [comment]
Hey, I included some adjustment in the recalculation process. So if you recalculate the routes with this update, the process will 'ignore' connections with an angle of more than 90°.
This could break some other connections which people may have done manually but it shoud definitely stop these issues with the two way roads
