### ISSUE TITLE
Zugmaschine und Hänger entleeren

### ISSUE THREAD

**Issue by Mombl** [Stephan-S/FS19_AutoDrive#427]
Hallo zusammen!
Ich weiß nicht, ob es das Thema schon gab, aber ich hab`s übersehen. Hat von euch einer eine Möglichkeit gefunden, wie man an einem Silo oder dgl. Zugmaschine und Hänger in einem Rutsch beladen und an einer Verkaufsstelle auch wieder nacheinander entladen kann? 

Danke
Mombl

**Comment by CairoAmun** [comment]
Hi Mombl
Du meinst einen LKW mit Kipper plus Anhänger oder Traktor mit 2 Anhängern? 
Falls ja, geht das mit Autodrive im Modus "Abholen und Abliefern"
Also ganz genauso, wie mit nur einem Anhänger oder Kipper. Da gibt es nichts besonderes herauszufinden 

![fsScreen_2019_08_29_12_22_07](https://user-images.githubusercontent.com/49886740/63933427-7c6e1500-ca59-11e9-939f-d56a0d3258db.png)
Beladung erster Anhänger:

![fsScreen_2019_08_29_12_22_17](https://user-images.githubusercontent.com/49886740/63933457-8d1e8b00-ca59-11e9-84fa-2241351dbb21.png)
Dann fährt der Traktor ein Stück vor und der zweite Anhänger wird beladen

![fsScreen_2019_08_29_12_27_06](https://user-images.githubusercontent.com/49886740/63933476-9b6ca700-ca59-11e9-8f21-48a153ed22f5.png)
Bei Ankunft am Zielort entlädt er den ersten Anhänger, fährt dann ein Stück weiter

![fsScreen_2019_08_29_12_27_09](https://user-images.githubusercontent.com/49886740/63933482-9e679780-ca59-11e9-8bcb-3b997be55346.png)
und entlädt den zweiten Anhänger.

Mit besten Grüßen
Cairo

**Comment by SledgeHammer75** [comment]
Argh, warum erfahre ich das erst jetzt? Danke Cairo.

**Comment by Mombl** [comment]
Danke Cairo für die schnelle Antwort. Wenn er nicht zuerst die Zugmaschine ablädt, liegt es wohl daran, dass der Trigger zu weit vorne, oder? Ich werde mal probieren, den Trigger zu verschieben.

**Comment by CairoAmun** [comment]
Wenn die Zugmaschine nicht abgeladen wird, der Anhänger aber schon, liegt das nicht am Trigger. Das Abladen funktioniert bei bestimmten Fahrzeugen nicht, wenn beim ersten Fahrzeug "abladen hinten" eingestellt ist. Stell auf seitlich abladen um und dann solltes es klappen.

**Comment by Mombl** [comment]
Hallo Cairo. Liegt an der Zugmaschine 👍

**Comment by Stephan-S** [comment]
Hey, ich lade gleich ein Update hoch bei dem auch Zugmaschinen mit aufgebautem Speicher korrekt erkannt werden und be/entladen werden.
Das sollte auch das Problem lösen, das Selbstfahrerspritzen bisher nicht aufgefüllt wurden.

**Comment by CairoAmun** [comment]
Hi Stephan,
vielen Dank. Immer wieder klasse, wie schnell Du auf Probleme oder Wünsche zu AutoDrive reagierst.
