### ISSUE TITLE
Problem with Course editor

### ISSUE THREAD

**Issue by Roby1164** [Stephan-S/FS19_AutoDrive#428]
I think there is a problem with the editor, after having modified some points, saved, entered the game reloaded, it seems that some destination points and some intersections are lost, I attach photos where you can see that, the vehicle, does not find the destination, but it is not far away, I realized, working the field with the CP, that when he finished the seeds, he went to position himself at the beginning of the CP path, as if he didn't find the required destination, in fact, provanmdo manually, he doesn't find it, I had to redo both the destination of the field, and that of the silo loading seeds, in that way it all started up again regularly. Now I will have to check all the other points, and they are many, I think it is really due to the Course Editor, since up until now evening everything worked, and this morning, it is the only change I made.
![Screenshot_1](https://user-images.githubusercontent.com/24955554/63929628-0c0fc580-ca52-11e9-8921-eb1fb3221d9c.jpg)

**Comment by eddiem54** [comment]
#416
Have you tried 'recalculate' , see reply 9 in above issue. Hope that helps

**Comment by Roby1164** [comment]
Yes, tried several times, and even more, but nothing to do, it only recovers after having deleted and redone the destination point and part of the route.

**Comment by Stephan-S** [comment]
@Roby1164 In the lates update, I made sure that connections with an angle of more than 90° are ignored in the recalculation process. Is it possible that your modifications created some higher angles?
So if you redid them, they were less than 90° and therefore the destinations was reacheable again.

I marked some connections in your image that already show quite high angles. So seeing this, I guess it's very likely that you had some connections with even higher angles :-)

![63929628-0c0fc580-ca52-11e9-8921-eb1fb3221d9c](https://user-images.githubusercontent.com/5493976/64042868-271e2a80-cb63-11e9-820e-9228ba39e0ab.jpg)

**Comment by Roby1164** [comment]
Let's start from the fact that, the tractor, no need to go that way, that is the exit, but strange things are happening, today, the sower went regularly, without having done anything, while always in that stretch of paths, I have the same problem with the spreader manure ... The only thing I will do is try to erase all that trait and do it again ... It will be possessed by some demon, I don't understand what happens, since in the rest of the map and fields, everything works .... :(

**Comment by Roby1164** [comment]
As I suspected, canceled the path, and redone, but in play, not with the Course Editor, and now everything works again ....
