### ISSUE TITLE
Trouble with the French translation file?

### ISSUE THREAD

**Issue by saku05** [Stephan-S/FS19_AutoDrive#429]
Hi and thanks for the work you do
Question: In the FS19_autoDrive folder, the French file (translation) is incomplete. It is missing about ten lines.
Thank you.
Sam

**Comment by Stephan-S** [comment]
I rely on translators to update the files with the correct translations. If you are up to it, feel free to either send me an updated file or if you know how, make a pull request here in Github with an updated  file :-)

**Comment by Stephan-S** [comment]
Thanks for the mail Sam
