### ISSUE TITLE
unload combine

### ISSUE THREAD

**Issue by enisbr** [Stephan-S/FS19_AutoDrive#43]
How does the new unload function work?

**Comment by Stephan-S** [comment]
You setup a target close to a field. It doen't have to be on the field itself or even on the same property, but it should be in way that the driver can reach the field without any collisions.
Then switch to the unload mode, and set the field as startpoint and a desired unloading location like a sell point or your silo as target/unload point (the lower one).
Then just start AutoDrive and the driver will wait at the start location until a combine calls it.

The combine calls the Driver if it is 100% full and has the pipe extended. No need to enable AutoDrive on the combine. But if the distance between driver and combine is too long (300m) the combine won't call the driver unless you also set the target of the combine to the same target as the driver has. So for example "Field 30".

So recap:
Driver settings:
   Start: "Field X"
   Unload: "Silo / Sell Y"
   Activate AutoDrive
 
Combine settings:
   Start: "Field X" (if distance >300m)
   Don't start AutoDrive

Start trigger is if combine 100% full and pipe extended.
