### ISSUE TITLE
Global Company

### ISSUE THREAD

**Issue by FunFarmer1** [Stephan-S/FS19_AutoDrive#431]
Hallo Stephan,

Kann es sein das AutoDrive die Global Company Trigger als Objekt sieht und deshalb immer davor stoppt und nicht weiter fährt bzw. sie überfährt ?
![fsScreen_2019_08_29_18_04_39](https://user-images.githubusercontent.com/49120617/63956842-8870cb80-ca87-11e9-9b2d-fa80d231db89.png)

Gruß Dennis

**Comment by plexten** [comment]
Das hatte ich auch schon. Es liegt am "playerTrigger" des Mods er muss die Collisions Mask von 300000 haben dann geht es. Schau mal mit F5 dann siehst du es. Oder du schaltest im AD Menü die Kollisionserkennung aus, dann fährt er auch weiter.

**Comment by FunFarmer1** [comment]
Ok alles klar nur das Problem ist die Produktionen sind fest auf der Karte verbaut.

**Comment by alpha117** [comment]
Does this help?

https://github.com/Stephan-S/FS19_AutoDrive/issues/369

**Comment by FunFarmer1** [comment]
i will try it alpha thank you

**Comment by Stephan-S** [comment]
Hallo @FunFarmer1 , plexten hat es schon korrekt erkannt. Die Global Company Gebäude haben einen 'falschen' Kollisionstrigger. Ich habs schon bei den Machern angestoßen und es wird sicher in zukünftigen Releases behoben sein.
In der Zwischenzeit habe ich einen Fix eingebaut, der die Kollisionserkennung im Umkreis von 15m um die Start/Zielpositionen ausschaltet. Wenn der Punkt allerdings mitten auf der Strecke durchfahren wird, kann ich auch nur raten die Kollisionserkennung von AutoDriver auszuschalten oder beim Mapersteller melden und nach Updates fragen :-)

**Comment by FunFarmer1** [comment]
Hallo Stephan,
jaa ich habe deinen fix für das GC eingefügt und schon geht es mit den triggern!

Vielen Danke für die Hilfe und Antwort.
