### ISSUE TITLE
Wilson trailer support

### ISSUE THREAD

**Issue by raxtor** [Stephan-S/FS19_AutoDrive#433]
I would like use 2 bin Wilson trailer but it seems AD not supports it yet.

![fsScreen_2019_08_29_22_27_51](https://user-images.githubusercontent.com/831266/63979787-03eb7080-caba-11e9-81d6-b4ac9582295b.png)
- Trailer only unloads 1 bin in Silo (depends which 1 is selected)
- Auger wagon detects 2 bins unreliably
![fsScreen_2019_08_29_22_41_22](https://user-images.githubusercontent.com/831266/63979991-9b50c380-caba-11e9-82ea-4cfb62519dc3.png)
![fsScreen_2019_08_29_22_42_36](https://user-images.githubusercontent.com/831266/63980003-a3a8fe80-caba-11e9-9284-d13e4705c128.png)
![fsScreen_2019_08_29_23_09_31](https://user-images.githubusercontent.com/831266/63980023-b6233800-caba-11e9-846b-5a77c3f19cd6.png)
a) firstly he missed trailer totally and went back to wait for combine but was over unload limit (85%)
It seems that Auger is opened too late or tractor is too fast...
b) than he filled 1st and 2nd bin correctly
c) next round he didnt find 2nd bin is able take some load yet

**Comment by raxtor** [comment]
Similar problem for truck.. jsut not opne/close cover and doednt unload truck
![fsScreen_2019_08_30_03_02_28](https://user-images.githubusercontent.com/831266/63986189-2d64c600-cad3-11e9-8b6f-66f163758e21.png)

- just thinking, isnt possible send unloader back to field to last position after unloading when "Field parking" is active. It saves some time for bigger fields. Also would be good let wait Auger vagon 30 sec on unloading point, because truck can be filled to eg 98% and second truck in queue is missed and than tractor is going back to field almost full. I know its only because Auger vagon.. maybe fill level for Load and Delivery mode would solve it too..

**Comment by aviator64** [comment]
I have found that multiple trailers (or multiple-compartment trailers) will unload at a silo IF they are completely full. If the second trailer/compartment is partially full then it will not unload.

**Comment by RUGhost** [comment]
@aviator64 I did not found it work in coarseplay. 100% full Wilson trailer just unload only one compartment.

**Comment by Stephan-S** [comment]
Hey,
could you please provide a link to the 2-bin trailer?
@raxtor Trucks and self driving vehicles will be supported with the next patch :-)

**Comment by raxtor** [comment]
Its default FS19 trailer...

**Comment by Stephan-S** [comment]
Oh, alright :D
I really don't get to play enough myself..
I'm on it.

**Comment by raxtor** [comment]
If you want savegame for faster process...
[savegame2.zip](https://github.com/Stephan-S/FS19_AutoDrive/files/3561152/savegame2.zip)

**Comment by aviator64** [comment]
@RUGhost maybe the destination marker is too close to the silo. I had to move mine forward so that the vehicle did not reach the marker before the second trailer/compartment could unload.

**Comment by raxtor** [comment]
It seems like Auger Vagon -> Any Trailer is broken again.. 
![fsScreen_2019_08_31_00_33_14](https://user-images.githubusercontent.com/831266/64054391-17184200-cb87-11e9-9e39-455e80373861.png)

**Comment by Stephan-S** [comment]
Should work with the newest commits. Release will be packed later

**Comment by raxtor** [comment]
Just tested...
a) firstly he missed trailer totally It seems that Auger is opened too late or tractor is too fast...
... 
![fsScreen_2019_08_31_14_58_32](https://user-images.githubusercontent.com/831266/64064352-6484c580-cc00-11e9-96b0-59098131a9fa.png)
and problem is still present in addition AD is lagging game when Auger wagon course is active.

You can use last savegame attached in post upper..

**Comment by raxtor** [comment]
@Stephan-S I tested 1.0.5.4. and Wilson loading/unloading works almost nicely!
2 problems.. 
- when I have set "Exit path from field to Default", than AW is unloading back cart and than first.. for "Beheind start" he is unloading to 1st cart.. is possibůe it has any influnce to unloading procedure?
- Trailer doesnt want move to Silo after reaching 100%.. Off/On AD solves it...
![fsScreen_2019_09_06_05_26_53](https://user-images.githubusercontent.com/831266/64400012-e3e42000-d06a-11e9-85b1-db851d666171.png)
![fsScreen_2019_09_06_05_50_05](https://user-images.githubusercontent.com/831266/64400013-e3e42000-d06a-11e9-8d3f-b89e2aa181eb.png)
I tested also truck+trailer.. seems working too.. just is possible use for trailer behind truck also side unloading in silo? Many Silos are in some house and not all are such tall as is needed for trailer up unloading.

Also I was playing with vehicle speed... for 80km/h and fully loaded truck isnt enough 5m "Look ahead for turning". I know is possible set 7m.. not sure how it works, but 10m for breaking would be better... anyway I think you can do it automatically and you dont need value in Settings menu... Lets say speed under 30km/h - 3m, 50km/h - 5m, 50km/h+ - 10m. I am talking about speed set in HUD.

**Comment by raxtor** [comment]
@Stephan-S 
- Trailer doesnt want move to Silo after reaching 100%.. Off/On AD solves it...
still stucked after full loading.. 1.0.5.5

**Comment by raxtor** [comment]
@Stephan-S I tested unoffical 1.0.5.6 (downloaded at midnight)
- truck in full loading is going to silo /fixed
- I again found problem with Auger Wagon unloading to Wilson or Truck+trailer.. is possible it is somehow connected to "Trailer offset"? I was playing with that and for 5m it missed back cart always (also truck trailer), with 3m. It worked a bit better..in 1.0.5.5 it looked like fixed. So something was changed...
- Also I noticed that unloader when is going back from field, uses stright way only through crop. Is it intended?

**Comment by raxtor** [comment]
> I tested also truck+trailer.. seems working too.. just is possible use for trailer behind truck also side unloading in silo? Many Silos are in some house and not all are such tall as is needed for trailer up unloading.

Thx for fix..
![fsScreen_2019_09_08_23_18_04](https://user-images.githubusercontent.com/831266/64494586-2ede7d00-d28f-11e9-92b2-e5189c33e2eb.png)

**Comment by raxtor** [comment]
Tested last github version and all seems ok... so I close it, thx! GJ!
