### ISSUE TITLE
Suggestion - exit field at named map marker

### ISSUE THREAD

**Issue by aviator64** [Stephan-S/FS19_AutoDrive#434]
The situation: Harvesting a field with multiple harvesters and multiple tractor/tippers. When a full trailer goes to exit the field "behind start" it often gets held up behind an empty trailer in front of it waiting its turn to go to a harvester.

There are many situations in which exiting a field "closest point" will not work due to obstructions.

I would like to suggest that there is an option to exit the field at a different, named waypoint. For example, have empty trailers wait at "Field 1 Enter" but have full trailers go to "Field 1 Exit" and thence to their destination.

That would make operations with multiple pieces of equipment much smoother.

**Comment by raxtor** [comment]
Maybe full trailers would can have 1st joining point lets say 50m behind start point. Than maybe it can miss queue of empty trailers or maybe AD AI driver can find way around these vehicles.

**Comment by Stephan-S** [comment]
just make sure your course makes a turn right after the field destination. Than the unloader won't align with the waiting drivers, but with the new course direction ;-)
