### ISSUE TITLE
Fahrzeuge kommen Steigung nicht hoch

### ISSUE THREAD

**Issue by Fideldu** [Stephan-S/FS19_AutoDrive#440]
Moin,

auf der NF March 2.3 habe ich das Problem, dass einige Fahrzeuge (z. B. LKW vom Friesenjung Transport Pack) die Steigung nicht rauffahren. Der LKW bleibt stehen und fährt nicht weiter. Manuell fährt er die Steigung ohne Probleme. 

Getestet habe ich das ganze ebenfalls nur mit der Karte, Courseplay  6.01.00294 und Autodrive 1.0.5.0 und dem LKW vom Friesenjung. Hier trat der Fehler ebenfalls auf.

LG und mach weiter so

Andreas

**Comment by Andii1980** [comment]
Hallo,

Bei mir kommt kein Drescher mehr eine Auffahrt hoch.

**Comment by N1T3C0R3** [comment]
Moin, 
bei mir ist es tatsächlich Fahrzeug abhängig:
Der LKW wird zwar langsamer aber schafft es noch genauso wie die meisten Traktoren, allerdings hat der Pickup zu kämpfen um Steigungen zu meistern.
Nur mein 7810 kommt zumindest die Steigungen der Hauptstraßen nicht rauf.

LG Jonas

**Comment by worker2419** [comment]
Hallo Stephan, gleiches Problem besteht auf der Map Südhemmern, hier schafft der Drescher die Steigungen zu den Brücken nicht. Trecker und LKW sind nicht betroffen.

**Comment by Stephan-S** [comment]
Ich mache hier mal zu. #529 wird weitergeführt
