### ISSUE TITLE
Save Ordner

### ISSUE THREAD

**Issue by Andii1980** [Stephan-S/FS19_AutoDrive#442]
Hallo,

wie wäre es wenn die AutoDrive_KARTENNAME_config.xml nicht im savegame ordner gespeichert wird sonder in einem AutoDriveKurs Ordner außerhalb der savegame?

Der Vorteil daran wäre das nicht die ganzen Kurse immer weg sind wenn man die SaveGame gelöscht hat.

Gruß Andii

**Comment by Stephan-S** [comment]
Hey, dafür gibt es ja die Export Funktion. Damit landet eine Kopie der config im Export Ordner außerhalb der Savegames :-)
