### ISSUE TITLE
ungeplante Kursänderung dank neuem Ziel im System

### ISSUE THREAD

**Issue by Andii1980** [Stephan-S/FS19_AutoDrive#443]
Hallo, 

Mir ist seit dem Letzen Update aufgefallen das man keine neuen Ziele dem Streckennetz hinzufügen kann ohne das sich was an alle Aktiven Fahrer und deren eingestelltes Ziel ändert und sie dann vollkommen verkehrte Sachen anfahren.

Ich konnte bis jetzt darin aber noch kein System der Zieländerung erkennen.

Gruß Andii

**Comment by gfa4711** [comment]
Bei mir passiert so etwas ähnliches mit den Parkpositionen. Plötzlich haben alle Fahrzeuge irgend welche Ziele als Parkplatz.

**Comment by Andii1980** [comment]
Man könnte das Gefühl haben das sich die ID des ziels ändert wenn ein neues gespeichert wird.
