### ISSUE TITLE
Feldhaecksler abtanken mit Autodrive funktioniert nicht 

### ISSUE THREAD

**Issue by Pipel19** [Stephan-S/FS19_AutoDrive#444]
Hallo zusammen,

ich versuche den Feldhäcksler automatisch mit Autodrive ab zutanken. Funktioniert bei mir nicht. Versuche es mit dem Drescher abtanken Modus. Geht es nicht weil der Häcksler kein Rohr ausfährt? 
Gibt es dazu eine Erklärung oder gibt es die Funktion nicht? Wenn nicht, wird Sie kommen? Vielen Dank

Gruß
Philipp

**Comment by Andii1980** [comment]
Hallo,  schau dir mal das hier an #227

**Comment by Pipel19** [comment]
Besten Dank Andi. Werde es so einmal probieren. 
Ist denn geplant das irgendwann bei Autodrive zu implementieren, so dass man es ohne workaround nutzen kann?
