### ISSUE TITLE
Probleme mit dem PlayerTrigger

### ISSUE THREAD

**Issue by Andii1980** [Stephan-S/FS19_AutoDrive#445]
Hallo,

ich habe ein einer Map das Problem das AD nicht in Fabriken fahren möchte wo an der Stelle ein PlayerTrigger gesetzt ist.

Es ist vollkommen egal ob er als Visibility oder nicht Visibility ist.

Hat da evtl. jemand eine Idee was man da am besten machen kann ohne diesen Trigger zulöschen?

Gruß Andii

**Comment by plexten** [comment]
[Global Company #431](https://github.com/Stephan-S/FS19_AutoDrive/issues/431)
