### ISSUE TITLE
Frage zur beidseitig befahrbaren Strecke (violett)

### ISSUE THREAD

**Issue by haamic** [Stephan-S/FS19_AutoDrive#446]
Hallo Stephan,
die Fahrzeuge warten ja brav, bis eine violette Strecke frei ist und befahren diese dann.
Wäre es möglich, das sie nur auf den Gegenverkehr achten und nicht auch warten, bis in die selbe Richtung Fahrende von der Strecke runter sind? also sie könnten ja bequem hintereinander herfahren, da ja nichts aus der Gegenrichtung kommen kann, wenn das vorherige Fahrzeug auf dem selben Kurs bereits unterwegs ist.
Gruss Micha

**Comment by Stephan-S** [comment]
Erledigt :-) Danke für die Erinnerung
