### ISSUE TITLE
keine Kurse sichtbar

### ISSUE THREAD

**Issue by ws1967** [Stephan-S/FS19_AutoDrive#447]
Auf der "Canadian Production Map Season v3.1" - und nur auf dieser Map (!!) - habe ich das Problem, dass ich zwar Kurse einfahren und Wegpunkte anlegen kann, sobald ich das Spiel allerdings neu starte sind sowohl die Kurse als auch die Wegpunkte nicht mehr verfügbar. In der config.xml werden sie allerdings aufgeführt. Ich verwende derzeit die Version 1.0.5.1. Auf anderen Maps funktioniert diese Version einwandfrei.

**Comment by Stephan-S** [comment]
Servus, wenn das Problem noch besteht, bitte mal die config hier hochladen und einen Link zur Map, damit ich mir das mal ansehen kann. Danke
Und sorry, dass ich das Issue ganz übersehen habe
