### ISSUE TITLE
Reihenfolge der Kurspunkte

### ISSUE THREAD

**Issue by Bruno5028** [Stephan-S/FS19_AutoDrive#45]
Hallo, danke für dieses super Tool.
Es wäre perfekt, wenn die Kurspunkte in der Auswahl automatisch alphabetisch sortiert würden.

**Comment by Stephan-S** [comment]
Ich überlege mal das als Option einzurichten, ob es alphabetisch oder nach Zeit der Einrichtung sortiert sein soll.
Falls du mit der Tastatur spielst und wirklich viele Ziele hast lohnt es sich für dich möglicherweise die Funktion zu nutzen den Zielnamen einfach einzugeben. Dazu musst du einfach in den Bereich klicken indem das Ziel steht und anfangen zu tippen. 
Wenn du dabei noch die Tab-Taste drückst bietet er eine Autovervollständigung an, die du wie bei der Erstellung der Ziele, mit der Return Taste bestätigen kannst

**Comment by Bruno5028** [comment]
Vielen Dank für die schnelle Rückmeldung, ich finde eine Sortierung sinnvoll. Natürlich teste ich auch deine Empfehlung.

**Comment by Bandesss** [comment]
Hello can you tell me how I get the course points of the row sorted
On the mulitmap you can see what I mean

[AutoDrive_Multimap_2019_config.zip](https://github.com/Stephan-S/FS19_AutoDrive/files/3197533/AutoDrive_Multimap_2019_config.zip)
[AutoDrive_FS19_Dondiego_Map_config.zip](https://github.com/Stephan-S/FS19_AutoDrive/files/3197535/AutoDrive_FS19_Dondiego_Map_config.zip)

So as it is in the Multimap I would like it.
Greeting Bandes

**Comment by Stephan-S** [comment]
Hey,
for now you can manually change the order in the xml file.
So change all the <mmX> </mmX> entries to your desire.

Then after loading this in the game, make sure to recalculate the routes.
