### ISSUE TITLE
Trucks not driving properly 1.0.5.3

### ISSUE THREAD

**Issue by aviator64** [Stephan-S/FS19_AutoDrive#455]
Since the last release or two, trucks are no longer following the course correctly.

They are not driving on the centerline, rather the course line appears to be aligned with their left wheel.

They make right turns OK, but when making left turns they always overshoot and lose their track, end up turning in circles.

Farm tractors/trailers are still driving OK, it is just trucks that seem to have this issue. Both default and mod trucks behave the same.

![fsScreen_2019_09_05_10_35_14](https://user-images.githubusercontent.com/19857526/64332505-9b762500-cfcc-11e9-87d9-c6babfc042d2.png)

**Comment by Mike1977** [comment]
I can confirm this. This is a game breaking bug, because the truck now stucks on every lamp post, tree, or pretty much everything that's near the street.

**Comment by Alkoholix** [comment]
Same here, it looks like the steering wheel follows the line.

**Comment by Stephan-S** [comment]
Are you still having this issue with release 1.0.5.5?

**Comment by Alkoholix** [comment]
No,  new release 1.0.5.5 worked for me, thank you.

**Comment by geo-luchs** [comment]
maybe this issue can be closed now, since Alkoholix has agreed that it works in 1.0.5.5

**Comment by Mike1977** [comment]
Works for me too now since 1.0.5.6 
I never tried 1.0.5.5 but i guess that worked too...
