### ISSUE TITLE
Saat und Dünger holen, BGA und Radlader, Fahrzeug ID und Parkpositionen

### ISSUE THREAD

**Issue by CairoAmun** [Stephan-S/FS19_AutoDrive#456]
Hallo Stephan,

wie besprochen liste ich Dir mal die Punkte auf, bei denen mir aufgefallen ist, dass sich irgendwo ein Fehler eingeschlichen hat, oder etwas, was vorher funktioniert hat nun nicht mehr funktioniert.
Bei der Durchsicht der noch offenen Issues habe ich gesehen, dass einige Fehler, bzw. Fehlfunktionen bereits von anderen Nutzern beschrieben worden sind.

1.	Die Fehlbelegung der Module „Drescher abtanken“ ist mit „Abholen“ vertauscht.
Dies verursacht aber keine Fehler, man muss es nur wissen. Die Funktionen an sich sind einwandfrei.

2.	Wenn man für seine Fahrzeuge eine feste Parkposition zugewiesen hat und ein neues Fahrzeug erwirbt, verschieben sich die Parkpositionen der Fahrzeuge, so dass man die Zuweisungen für alle Fahrzeuge neu vornehmen muss. Es scheint so als würden die ID der Fahrzeuge bei Neukauf eines Fahrzeuges neu vergeben.

3.	Fügt man im Spiel neue Streckenpunkte mit einem neuen Zielpunkt ein, erhalten die Fahrzeuge die währenddessen im Einsatz sind, nach der Neuberechnung andere Zielpunkte, als sie ursprünglich hatten. Aber eben nur, wenn auch ein neuer Zielpunkt dazu kommt. Bei einer  Streckenänderung, zum Beispiel um einen Radius zu verändern oder ähnliches, ohne dabei an den Zielpunkten etwas zu ändern, passiert das nicht.

4.	Die Abfahrer fahren seit dem Update 1.0.5.3 streckenweise nur 23 km/h, obwohl im Hud 50 km/h eingestellt ist.

Worüber ich nichts in den Issues gefunden habe, bzw. es vielleicht übersehen habe sind 2 Dinge.

1.	Die Funktion Saat und Dünger holen funktioniert nicht mehr. Bislang habe ich die Sämaschine mit CP auf einen Säkurs gesetzt und in CP bei den fahrzeugspezifischen Einstellungen „Use AutoDribe for refill/unload“ aktiviert und im Autodrive Hud das Modul „Abholen“ gewählt. Ersten Ziel z.B. Feld 10 und als zweites Ziel die Silos für Saat und Dünger. Bei Fruchttyp dann Saat eingestellt.
Das hat zumindest bislang in soweit funktioniert, das die Sämaschine zu den Silos gefahren ist und dort das aufgenommen hat, was bei Fruchttyp angegeben war. In diesem Beispiel also Saatgut, aber eben keinen Dünger. War Dünger eingestellt, hat die Maschine Dünger geholt, aber eben kein Saatgut. Ich habe hier gelesen, das die Trigger im Grunde im vorbeifahren gefüllt werden, aber egal, wo ich den Zielpunkt bislang auch hingelegt habe, es wurde niemals beides geladen.
Nach irgendeinem Update; - ich kann Dir leider nicht sagen ab welchem Update, fährt die Sämaschine nun nicht mehr vom Feld zum Silo, sondern nur noch zum ersten Ziel, in dem oben beschrieben Beispiel also zum Punkt „Feld 10“ und dann wieder auf das Feld zu dem Punkt, an dem zuletzt gesät wurde. Da die Tanks aber leer sind, wiederholt sich das Spiel, bis man das Fahrzeug aus dem Kurs herausnimmt.

2.	Die Radladerfunktion an der BGA bekomme ich auch nicht wirklich ans laufen. Mein Radlader erkennt zwar das Fahrsilo und holt auch Silage heraus, aber den Traktor mit dem Trailer erkennt der Radlader nicht sondern fährt weiter rückwärts aus dem Silo, bis er irgendwann am Zaun der BGA hängen bleibt. Traktor und Trailer stehen parallel zur Silowand. Hier bin ich mir aber nahezu sicher, dass ich da etwas falsch mache, ich weiß nur nicht was. 

So, das ist jetzt etwas lang geworden, ich hoffe sehr, dass Du mir bei dem einen oder anderen Problem weiterhelfen kannst.
Übrigens vielen Dank für den Einbau des neuen Menüs, das wird mir die Arbeit enorm erleichtern.

Viele Grüße Cairo

**Comment by worker2419** [comment]
Punkt 3 kann ich bestätigen. Dies passiert auch, wenn ein Zielpunkt gelöscht wird. Schaut man im laufendem Spiel in die Config.XML sind die Veränderungen noch nicht geschrieben. Beendet man das Spiel und startet neu, sind alle Änderungen in der Config.XML vorhanden. Folgenden Fehler sieht man in der Log.txt: Autodrive encountered a problem during initialization - shutting down

**Comment by geo-luchs** [comment]
Hallo 

Bei ( noch nicht in den Issues gefunden) Punkt 1: Abholen Modus in Verbindung mit CP:
Ich habe es gerade mit Kalk gemacht. Es hat funktioniert. Ih hatte irgendwo mal gehört/gesehen/gelesen, dass man erstmal den AD Kurs einmal fahren lassen muss.
Er stand dann beim Feld, fuhr dann den Kalk aus, als er leer war, fuhr er den AD Kurs, um aufzuladen, und dann wieder zum Feld.
Ist zwar jetzt nur Kalk, also ein wenig anders, aber der Modus hat zumindest für Kalk funktioniert.
Mir ist dabei aber aufgefallen, dass er am Ziel (also am Feld) die Abdeckung geöffnet hatte, und dann mit offener Abdeckung den Kalk auf dem Feld verstreut hat.
Hier scheint ein "öffne Abdeckung" zuviel drin zu sein.

Gruß
Carsten

**Comment by geo-luchs** [comment]
leider wollte meine Saatgut/Düngermaschine auch nicht zum Aufladen fahren. Er fährt nur kurz am Zielpunkt vom AD vorbei, noch nicht mal direkt auf die AD Strecke. Und fährt dann mit Vollspeed geradeaus übers Feld ins Nirwana :-(

**Comment by Stephan-S** [comment]
Hey @geo-luchs ,
nutzt du die aktuellste Version von AutoDrive? Was die Thematik angeht, habe ich in den letzten Tagen ein paar kleiner Bugfixes rausgebracht. Auch die 'Übergabe' zurück an CP wird nur aufgerufen wenn der Kurs erfolgreich beendet wurde

**Comment by geo-luchs** [comment]
Hi Stephan

ich benutze die 1.0.5.6. ich denke, das sollte die aktuell sein.
Dann muss ich beim nächsten Mal nochmal drauf  achten, vorhe rden AD Kurs erfolgreich abgefahren zu haben.
