### ISSUE TITLE
Game Freezes, Tons of Errors After Update

### ISSUE THREAD

**Issue by stangman04** [Stephan-S/FS19_AutoDrive#458]
Just updated to the latest release and game is unplayable. Attached log..
[log.txt](https://github.com/Stephan-S/FS19_AutoDrive/files/3581466/log.txt)

**Comment by stangman04** [comment]
I have reverted to 1.5.0.2 for now. Seems to work fine.

**Comment by raxtor** [comment]
Seems line 31 and 37 use variable trailer instead of vehicle.. if you replace it, than it works...

**Comment by raxtor** [comment]
@Stephan-S morning hotfix for Bugfix for trailers not starting at 100% load
```
AutoDrive.lua:448: attempt to call method 'handleCombineHarvester' (a nil value)
Error: Running LUA method 'update'.
```
[log.txt](https://github.com/Stephan-S/FS19_AutoDrive/files/3582318/log.txt)

**Comment by wlfheart** [comment]
I also am experiencing game freeze at the very start.

**Comment by Roby1164** [comment]
1.0.5.4 not work, freeze and error LUA...

**Comment by worker2419** [comment]
Errors in Log.txt
Error: Running LUA method 'update'.
My Games/FarmingSimulator2019/mods/FS19_AutoDrive/scripts/AutoDriveCombineMode.lua:31: attempt to index global 'trailer' (a nil value)

**Comment by Emilioso007** [comment]
[log.txt](https://github.com/Stephan-S/FS19_AutoDrive/files/3584432/log.txt)
Freezes too
