### ISSUE TITLE
Error Meldungen

### ISSUE THREAD

**Issue by FunFarmer1** [Stephan-S/FS19_AutoDrive#463]
Hallo Stephan,

Hier mal meine Log.
[log.txt](https://github.com/Stephan-S/FS19_AutoDrive/files/3583691/log.txt)

seit den letzten neuen Realeses habe ich immer diese Felhermeldungen.
Gruß Dennis

**Comment by SledgeHammer75** [comment]
bei mir hängt es beim Spielstand laden noch bevor Courseplay die Felder scannen kann

> 2019-09-06 17:03 C:/Users/Christian/Documents/My Games/FarmingSimulator2019/mods/FS19_AutoDrive/scripts/AutoDrive.lua:448: attempt to call method 'handleCombineHarvester' (a nil value)
2019-09-06 17:03 Error: Running LUA method 'update'.
