### ISSUE TITLE
No Error but "Continue on full trailer/fillUnit continueAfterLoadOrUnload" 

### ISSUE THREAD

**Issue by eddiem54** [Stephan-S/FS19_AutoDrive#465]
Hi Again,
Above message 2000 times, 
[log.txt](https://github.com/Stephan-S/FS19_AutoDrive/files/3585591/log.txt)

**Comment by Squibbb** [comment]
Hi Stephen
I'm having the same Trouble aswell.

**Comment by Bandesss** [comment]
Ich habe auch was neues
[logls19.txt](https://github.com/Stephan-S/FS19_AutoDrive/files/3586426/logls19.txt)

**Comment by eddiem54** [comment]
Hi,
No errors for some days now,
Thanks again.
