### ISSUE TITLE
Abkippseite mit Zufallsgenerator

### ISSUE THREAD

**Issue by plexten** [Stephan-S/FS19_AutoDrive#468]
Hallo Stephan,
ein kleiner Fehler ist mir mit der Apkippseite aufgefallen. Etwa 10 sec. vorm erreichen der Entladestelle startet ein Zufallsgenerator der die Appkippseite permanent durchläuft. Von Abkippseite (Links), Abkippseite (Rechts), Abkippseite (Hinten) und Abkippseite (Kornschieber) solange bis das Fahrzeug mit Anhänger von der Entladestelle wieder weit genug weg ist. Beim Abkippen ist kurz stillstand.
Grüssle plexten

**Comment by Stephan-S** [comment]
Hi,
das war eigentlich als Feature gedacht, so dass man nicht darauf achten muss die korrekte Abladeseite einzustellen.
Ich schau mal ob ich das anders gelöst bekomme

**Comment by plexten** [comment]
Das es z.B. im Menü aktiviert oder deaktiviert werden kann, wenn es als Feature gedacht war...

**Comment by Stephan-S** [comment]
Hab das wilde verändern der Tipseite gerade beseitigt. Allerdings wird er aktuell trotzdem den zuerst im Trigger stehenden Abkipppunkt nutzen.
Muss es dafür eine Option in den Einstellungen geben? Wahrscheinlich schon. Es gibt ja Abkipppositionen an denen es wichtig ist, das der Hänger nich hoch oder zur Seite kippt.
Hm, eigentlich habe ich gehofft hier nicht noch eine Option hinzubauen zu müssen. So wird das Einstellungsmenü ja immer komplexer

**Comment by plexten** [comment]
Mir persönlich hat es vorher mit der Abkippseite besser gefallen, so kann ich erst einmal damit leben. 

Danke Stephan für den exzellenten Support den du uns Usern hier täglich zur Verfügung stellst.
