### ISSUE TITLE
calculated ways are not working anymore beginning with 1.0.5.5

### ISSUE THREAD

**Issue by geo-luchs** [Stephan-S/FS19_AutoDrive#470]
Hi Stephan

first of all: great job this mod. It's very helpful.

But now, with 1.0.5.5 and 1.0.5.6  I'm getting problems after recalculation of the ways.
With 1.0.5.1 it works fine.

I've the same ways, nothing changed, no ways added, no stops added.
I'm only recalculating the ways, and then I can't reach a lot of stops anymore.

But when switching back to 1.0.5.1, recalculating the ways, I can reach the target.
Always the vehicle is staying on the same position, not moved.

If I'm close to the target , target can be reached.  
It's hard to reproduce, but it seems, if more splits of the way are between, it can't be reached.
If only 1 split is between, it can be reached.

And the xml file is much bigger with 1.0.5.5 and 1.0.5.6  (806 kb) than with 1.0.5.1 (303 kb)

[AutoDrive_1.0.5.5_NF_Marsch_V2_3_config.txt](https://github.com/Stephan-S/FS19_AutoDrive/files/3586970/AutoDrive_1.0.5.5_NF_Marsch_V2_3_config.txt)
[AutoDrive_1.0.5.1_NF_Marsch_V2_3_config.txt](https://github.com/Stephan-S/FS19_AutoDrive/files/3586971/AutoDrive_1.0.5.1_NF_Marsch_V2_3_config.txt)

Kind regards
Carsten

**Comment by Stephan-S** [comment]
Hey Carsten,

I prohibited angles of more than 90° in one of the latest releases.
So If you have manually connected some waypoints which leads to angles > 90° between the two segments, you will have to redo them.

This change was required too properly use the Dual way roads and prevent them from being used as turn around points at the entries.

Best regards,
Stephan

**Comment by geo-luchs** [comment]
Hi Stephan

thanks a lot for this hint.
I've redesigned it with your Autodrive Course Editor, which is a big help in this case.

Now it works.
Even the file is much bigger , when calculating it ingame, as it is with the editor saved.
And much bigger than with older version 1.0.5.1.

But for now, it seems to work.
Kind regards
Carsten
