### ISSUE TITLE
Update 1.0.5.6 noch immer Probleme mit Flüssigkeitstransport

### ISSUE THREAD

**Issue by Fuzzy86** [Stephan-S/FS19_AutoDrive#472]
Hy! Super Update, jedoch funktioniert der Flüssigkeitstransport noch immer nicht! Hab es mit den Standart Fässern und mit MOD's, auf originalkarten und auf NF Marsch und auch ohne Mods im Modortner.

Ich bitte um Hilfe
mfg

ps.: Es geht seit Update 1.0.5.0 nicht mehr

**Comment by Keven-Fendt** [comment]
Das Problem habe ich auch . er öffnet die Klappe vom Fass aber er fährt einfach weiter ohne zu laden und beim abladen genau das gleiche 
mfg. Keven Fendt

**Comment by Stephan-S** [comment]
Servus, von was für Fässern sprecht ihr denn?
Ich habe es eben mit einem Lizard MKS 32 ausprobiert und er hat einwandfrei Milch und Wasser be- unt entladen.
Ich probiers mal noch mit den kleinen Fässern aus.
Bzw. was transportiert ihr denn und von wo wollt ihr laden?

**Comment by Fuzzy86** [comment]
Also auf der NF Marsch wollte ich mit dem Universal auflieger
1.  Von der Raffinerie Diesel holen und in der Heutrocknung abladen

2. Vom Ackerschacht wasser zum Kalkwerk bringen.

Jetzt habe ich alle mods außer Autodrive rausgehauen und auf der Felsbrunn nen Wassertank zum abholen Schweinestall mit 30 Tieren zum abliefern gebaut und versucht mit dem kleinen Standart Lizart Fass das wasser zu transportieren aber leider ohne Erfolg. 

Mit der Version 1.0.4.9 geht das alles

**Comment by Stephan-S** [comment]
Hey Fuzzy,
was ist der 'Universal auflieger' ?

**Comment by Stephan-S** [comment]
Und hast du bei deinem Versuch auf der Felsbrunn mal gespeichert und neugestartet nachdem du die Gebäude gesetzt hast?
Die Trigger werden nur beim Spielstart von Autodrive gescannt. Neugebaute Gebäude erkennt er also erstmal gar nicht

**Comment by Fuzzy86** [comment]
Den Lizard MKS 32 auflieger (Mod).

Nein das hab ich nicht versucht mit nen neustart. Aber wie gesagt mit der 1.0.4.9 Version funktioniert ja alles. Bei der neuen Version geht ja alles andere auch abholen und abliefern außer die Flüssigkeiten.

**Comment by Stephan-S** [comment]
Ich glaub ich hab den Fehler gefunden.
Ich habe gerade neuen Code hochgeladen aber nicht zum Release gepackt.
Kannst du es damit mal probieren oder brauchst du das release zip ?

**Comment by Fuzzy86** [comment]
Alles klar. Mach ich dann wenn ich zu Hause bin. Brauch keinen release zip. Brauch eh nur das zipen was in dem ordner ist, oder?

**Comment by Stephan-S** [comment]
genau. Super. Danke

**Comment by Fuzzy86** [comment]
Habe es soeben gestestet.

NF Marsch:
Original MKS32 Auflieger - Transport Wasser - Funktioniert
Original Joskin Fass - Transport Wasser - Funktioniert
Wasser Transport Auflieger (Mod) - Transport Wasser - funktioniert

Original Diesel Transport Hänger - Transport Diesel - Funktioniert Nicht
MKS32 Auflieger Universal (Mod) - Transport Wasser und Diesel - Funktioniert Nicht

Felsbrunn ohne Mods außer Autodrive:
Original Joskin Fass - Transport Wasser - Funktioniert


Was mir auch aufgefallen ist, wenn man den Abfahrer startet fahrt er fast immer als erstes den Abladeort an und nicht den Beladezielpunkt.

Hoffe das hilft dir soweit

**Comment by Keven-Fendt** [comment]
Hallo Stephan
NF Marsch:
Original MKS32 Auflieger - Transport Wasser - Funktioniert
ich benutze den LSFM Universal Tank Pack da geht es nicht auch nicht wenn ich deine Änderung reinmache , bei der 1.0.5.1 geht es einwandfrei mit dem LSFM 
mfg. Keven Fendt

**Comment by Stephan-S** [comment]
Sollte jetzt aber wirklich klappen :-)

**Comment by Keven-Fendt** [comment]
Hallo Stephan
Vielen vielen dank jetzt klappt es einwandfrei, auch für das schnelle antworten und das Skript
Danke mfg. Keven Fendt
