### ISSUE TITLE
Probleme beim Befüllen eines Abfahrers aus dem Hofsilo.

### ISSUE THREAD

**Issue by Spielbauer** [Stephan-S/FS19_AutoDrive#473]
Hallo Stephan,
das Fahrzeug fährt unter das Silo hält für einen Bruchteil einer Sekunde und fährt dann weiter an das gedachte Ziel. Dabei startet der Füllvorgang. Allerdings wird der Hänger natürlich nicht voll. 

AD-Version 1.0.5.5
Multimap 2019 1.1.1

2019-09-08 13:42 FoliageTransformGroup: blown max instance count (144), increasing to 162
2019-09-08 13:43 continueIfAllTrailersClosed

**Comment by Stephan-S** [comment]
Biit updaten. Danke :-)
