### ISSUE TITLE
Cannot put special charset

### ISSUE THREAD

**Issue by Anonymous-any** [Stephan-S/FS19_AutoDrive#48]
When saving a name destinations the specials charset cannot be write like `é è ï ô` if something can fix it.
Br

**Comment by Merlin110480** [comment]
Hatte dazu auch ein Problem, mein Mitspieler hat es geschafft ein Sonderzeichen in den Namen zu packen:

2019-04-11 15:47 Warning: Character '18917' not found in texture font (äge in Sägeaegewerk - Weizen).

            <mm23>
                <id>3951.000000</id>
                <name>S娥aegewerk</name>
            </mm23>

**Comment by Anonymous-any** [comment]
True

**Comment by Stephan-S** [comment]
Same as #127 
Added as long term goal
