### ISSUE TITLE
Zielpunkte nicht auf alle Fahrzeugen vorhanden

### ISSUE THREAD

**Issue by haamic** [Stephan-S/FS19_AutoDrive#480]
Hallo Stephan, 
ich bin jetzt auch mal auf die Version 1.0.5.6 umgestiegen, da geht ja einiges nicht mehr bei mir.
Fahrzeuge haben nicht identische Ziellisten. Bei manchen gibts nur 1 Ziel andere haben mehrere.
Neu gespeicherte Ziele erscheinen erst gar nicht in der Liste. 
Wie soll das mit den Ordnern funktionieren, kann da nichts erkennen?
bin nun zurück auf 1.0.5.1
Gruss Micha

**Comment by worker2419** [comment]
Hallo,

ein ähnliches Problem hatte ich aus. Ich verwende folgende Version, dort hat Stephan noch etwas angepasst.
![Autodrive](https://user-images.githubusercontent.com/47278102/64594244-f08caf00-d3af-11e9-892f-ecd8c06b591a.png)

**Comment by haamic** [comment]
@worker2419 
diese version hatte ich genutzt und hab eben die oben beschriebenen Probleme

**Comment by worker2419** [comment]
@haamic 
Würdest Du bitte deine Log posten. Evtl. ist dort ein Zusammenhang zu sehen

Das mit den Ordnern geht wie folgt:

In den Eigenschaften umstellen auf
![AD_01](https://user-images.githubusercontent.com/47278102/64625798-12585700-d3ed-11e9-89bb-a23c162cd0e8.png)

Im Zielmenü erscheint dann ganz oben
![AD_02](https://user-images.githubusercontent.com/47278102/64625828-256b2700-d3ed-11e9-9dc1-c39a657088c3.png)

mit dem + werden neue Ordner angelegt
![AD_03](https://user-images.githubusercontent.com/47278102/64626073-8692fa80-d3ed-11e9-9587-f7fafff667b7.png)
diese erscheine am Ende der Liste
![AD_04](https://user-images.githubusercontent.com/47278102/64626185-b93cf300-d3ed-11e9-9a90-ef1957b2267f.png)
Ist der Ordner leer, kann er mit - gelöscht werden. Die Einträge werden mit den Pfeilen verschoben

**Comment by haamic** [comment]
@worker2419 
oje, das war aber ein blöder Fehler...... habs rausgefunden
Stand ja nirgend das man in der Liste scrollen muss, oder habs überlesen.
Bei mir wird der letzte Eintrag der Ziele angezeigt, also für mich als erste Zeile in der Liste, das die anderen aber durch scrollen nach oben erscheinen, weil quasi das Ende der Liste angezeigt wird, hat sich mir nicht erschlossen. Alles gut, hab meine Ziele und das mit den Ordnern geht auch, weil ich ja nie zum Anfang oben gescrollt hatte und die (+/-) sah.
Deine letzte Beschreibung kann ich nicht bestätigen, ich kann immer einen Ordner löschen, auch wenn Ziele darin sind, diese Stehen dann wieder im Standart Ordner und der vorherige Ordner ist gelöscht.
Aber mühsehlig ist das schon noch, die Ziele in die Ordner zu packen. Aber Hauptsache es geht.

**Comment by worker2419** [comment]
@haamic jupp das ist doof, hatte ich auch mehr zufällig gelesen. :-(

Um die Ziele schneller in die Ordner zu bekommen, habe ich folgenden Weg gefunden:
1 Sicherung der Autodrive-Config.xml anlegen (Steht im jeweiligen Savegame Ordner)
2 Prüfen, ob der Parameter auf 2 steht 
![AD_05](https://user-images.githubusercontent.com/47278102/64633590-c52fb180-d3fb-11e9-9ab3-103b84258df9.png) und dann die Group Bezeichnung anpassen 
![AD_06](https://user-images.githubusercontent.com/47278102/64633611-d1b40a00-d3fb-11e9-8051-2a6fe396dd96.png)
Daraus werden die Ordner gebildet, das mit dem Löschen schau ich mir an.
