### ISSUE TITLE
Restrict route segment to Target?

### ISSUE THREAD

**Issue by manierim** [Stephan-S/FS19_AutoDrive#481]
Hello Stephan.

Greetings from Italy and thank you so much for this great addition to our beloved game!

I often ran in situation where a specific segment of a network should only be used to reach and then leave a specific Target. Most commonly, a silo unload trigger.

I try to also draw alternative routes for traffic transiting in the area but they often choose to instead go through that "reserved" segment being it shorter.

I tried to make it not continuous, stopping it at the Target and then leaving a "gap" before the "leaving" part of the route but this seems to confuse AD drivers after they unloaded at the silo. They often try to reach directly other nearby segments often impacting on structures. This does not seem to happen if the route is continuous through the unload Target.

Do you think it might be possible to somehow "restrict" given nodes/segments to selected targets only so that traffic looking for routes to other targets "do not see" them?

**Comment by Roby1164** [comment]
Ciao Marco, effettivamente c'è quel problema, ma è dovuto al fatto che, il mezzo prende la strada più diretta verso la destinazione, proprio in linea d'aria, anche impostando di non usare la strada più veloce. se nel mezzo ce quel tuo percorso del silos, normale che passa di li. Il consiglio è di creare percorsi lineari e poi le deviazioni che facciano la fermata al silos, in questo modo, non passano da silos, ma sul percorso lineare a fianco, questo specialmente se si usa percorsi blu, quelli a doppio senso. Ora vediamo se Stephan ha qualche idea diversa, ma non credo sia di facile risoluzione.

**Comment by Stephan-S** [comment]
Hey, for exactly this purpose there is the built in function to 'Avoid targets' and a setting for the 'Maximum detour'.
If you set this and recalculate the network, it will add a cost to driving through destinations. 
So If you have a destination at the shortcut and add a maximum detour of 100meters, it will take the main road if it is no more than 100meters longer and has no destinations on it.

Best regards,
Stephan

**Comment by manierim** [comment]
Ah... That's great.

I honestly completely misunderstood the avoid targets and maximum detour options. Never tried to use it, I thought they were relevant to other vehicles on the route!

I will try, thanks a lot!
