### ISSUE TITLE
Probleme mit aktueller Version

### ISSUE THREAD

**Issue by Caliban2017** [Stephan-S/FS19_AutoDrive#482]
Hallo,

zunächst mal riesen Respekt für die Mod, funktioniert mit ein paar kleinen Problemchen hier und da an sich aber doch sehr gut! 

zu den Dingen die mir aufgefallen sind - ich benutze die aktuelle Version, also runtergeladen und selbst gezippt, bei der 10.5.6 funktionierte bei mir das beladen an den Silos nicht, der Fahrer fuhr über den Trigger einfach hinweg. In der selbst gezippten Version geht dies. Ich möchte nun am gleichen Silo (Map ist Hof Bergmann) Weizen abtanken und dies zu einer Verkaufsstelle fahren. Ich hab in den Fahrzeug Optionen eingestellt das er bei einem leeren Silo weiterfahren soll. Nun fährt der Traktor an das Silo, belädt es bis ca. 75% mit dem Weizen, danach ist das Silo leer. Allerdings bleibt der Fahrer einfach auf dem Trigger stehen und fährt trotzdem nicht weiter. Habe es mit einer anderen Fruchtart probiert, wo der Hänger zu 100% gefüllt wird. Sobald der Hänger voll ist, fährt der Abfahrer los. Also scheint hier die "Weiterfahren bei leeren Silo" Funktion nicht zu klappen.

**Vielleicht hier noch als Nachtrag:** die Weiterfahren Funktion scheint generell nicht zu klappen. Selbst wenn ich in den Traktor switche und dort den Weiterfahren Button drücke, die Grüne schrift bleibt beim Ziel, springt nicht über zum Ablieferpunkt und der Traktor rührt sich eben auch nicht vom Fleck.

Zu meinem zweiten Punkt - man kann ja mit den blauen Linien sozusagen exklusive Kurse erstellen. Das funktioniert soweit ganz gut allerdings bin ich hier auf ein Problem gestoßen, vielleicht gibt es dazu ja schon eine Lösung. Wenn ich inmitten eines blauen Kurses einen Wegpunkt lösche, dann kann ich diesen hinterher aber nicht wieder mit einer blauen Linie verschließen. Wähle ich hier die nachbar Knotenpunkt Funktion und möchte die Lücke schließen, wird immer eine grüne Linie erstellt. Hier fehlt eine Option um zu der blauen wechseln zu können. Ich hab ebenfalls versucht hier ein wenig zu tricksen und habe den letzten Teil dieser Unterbrechnung gelöscht und dachte an der Lücke könnte ich einfach mit der Aufzeichnen Funktion mit der blauen Linie an dieser wieder ansetzen. Aber auch das geht nicht, wenn bei Start das automatische Verbinden an ist, wird immer eine grüne Linie erzeugt. 

Mein nächster Punkt wäre der automatische Abfahrer beim Drescher im Multiplayer. Ich habe gestern eine Runde mit meinem Bruder im MP gespielt (ich habe das Spiel erstellt, kein Dedi Server) und wir hatten bis vorgestern noch eine ältere Version aus dem Modhub drin, ich glaube 1.0.19. Dort konnte mein Bruder (der Mitspieler auf dem Server) problemlos vom Drescher aus den Abfahrer rufen, der am Feldrand steht. Seit gestern hatten wir die 10.5.6 probiert aber dort hat der Abfahrer einfach nicht auf ihn reagiert und blieb am Feldrand stehen. Wir haben sämtliche Optionen durchprobiert wie Fruchtumfahrung aus, das automatische Abfahrer suchen aus etc. Ging alles nicht. Was jedoch komischerweise funktionierte - wenn ich in den Drescher eingestiegen bin, dann kam er nach dem Tastendruck sofort angefahren. Ich hab meinen Bruder mehrfach gebeten die Tastenbelegung für die Ruffunktion zu prüfen, daran scheint es nicht zu liegen. 

und zum Schluss vielleicht noch ein kleiner Feature-Wunsch, den es ja im Courseplay bereits gab: zum testen wäre eine Funktion nützlich, um im Dreschmodus den Abfahrer auf Kommando zum Silo zu schicken. Leider muss man immer warten bis sein Füllstand erreicht ist, bis er los fährt. Ich hab diese Funktion damals im Courseplay auch immer ganz gerne benutzt, um den Abfahrer weg zu schicken, wenn er mir auf dem Feld im Weg stand. Ich weiss man kann den Abfahrer auch sagen das er nicht auf dem Feld parken soll. Leider fällt Courseplay dafür eben weg, da wir nur im Multiplayer spielen. Und CP ist ja bekanntlich nicht MP tauglich. Haben es getestet aber dabei scheint die Server Synchronisierung abzustürzen, daher fällt CP komplett weg. 

Ich hoffe ich konnte damit ein wenig Feedback beisteuern! :) 

Viele Grüße

**Comment by kleinerblauer** [comment]
Auch von mir ein riesen Dankeschön für den Mod!

Leider kann auch ich in der aktuellen Version (1.0.5.6) ein paar kleine Fehler feststellen:

1. Wie bereits von Anderen beschrieben das Weiterfahren bei leerem Silo.
2. Wenn ich nicht im Editor-Modus bin, ist zwar das Zeichen zum Neuberechnen der Wege nicht vorhanden, der Button kann aber trotzdem gedrückt werden. Da er direkt über "Ein-Aus" liegt, kommt man schnell mal darauf.
3. Der Flüssigkeitstransport funktioniert gar nicht mehr. Weder Wasser, noch Milch oder Gülle. AD fährt zwar zur Entnahmestelle und bleibt stehen, aber er füllt nicht auf.
4. Das Warten im Feld funktioniert nicht.

Noch ein Wort zum Course-Editor:
Es wäre schön, wenn du dazu eine kleine Anleitung schreibst.
Ich habe es dann mit Hilfe von langem Suchen im Netz hinbekommen, dass die Kurse geladen werden und habe auch eine Map im Hintergrund, aber leider passen die Kurse nicht zur Map, d.h. sie liegen nicht auf den Straßen. Map ist Saxonia.

**Comment by haamic** [comment]
Punkt 4 kann ich nicht bestätigen.
Ich ernte gerade ein riesiges Feld ab, mit 4 Dreschern im Verband und mehreren Abfahrern. Diese parken/warten brav im Feld auf den nächsten vollen Drescher. 
Aktuelle AD Version 1.0.5.6 selbst geZIPt

**Comment by geo-luchs** [comment]
Punkt 3 kann ich wiederum nicht bestätigen.
Ich hole Milch am Kuhstall ab.
Die Milch wird ordnungsgemäß abgepumpt.
Version 1.0.5.6
Modus (Abholen und Abliefern)
oben : Kuhstall - Entnahmestelle
unten Verkaufsstelle 
rechts : Milch

Dafür tritt Punkt 1 auch bei mir noch auf. Er fährt nicht weiter, wenn das Silo(hier der Kuhstall) leergepumpt ist. In den AD Settings ist "Weiterfahren bei leerem Silo" eingestellt

**Comment by Stephan-S** [comment]
Punkt 1 ist mit anderen Issues zusammen noch in Bearbeitung/Beobachtung
