### ISSUE TITLE
Pfad zum Drescher, Gebiete ausschliessen ???

### ISSUE THREAD

**Issue by haamic** [Stephan-S/FS19_AutoDrive#483]
Hallo,
hat jemand eine Idee, wie ich folgendes Problem umgehen kann?
Ich spiele auf einer Karte, worauf es ein riesiges sehr unregelmässiges Feld gibt (selbst angelegt).
In einer Art Tal, begrenzt durch Hügel/Berge/Erhebungen...
Stellt Euch z.b. ein "U"  vor, umringt von den nicht befahrbaren höheren Gebieten.
AD (1.0.5.6) tankt im linken Flügel des "U" den Drescher ab und wartet dann bis er wieder voll ist. Inzwischen ist er aber im rechten Flügel und soll dort abgetankt werden. Bei mir Startet nun der Abfahrer und fährt aber nicht den Bogen zum linken Flügel, sondern will die Berge hoch fahren. Also quer rüber und hängt dann natürlich fest. Müsste er nicht bei Fruchtumfahrung an, dem Pfad des Dreschers folgen und ihn dann erreichen? Hab schon verschiedene Einstellungen probiert, aber zufriedenstellend war das nicht. Ich habe nun "Parken im Feld" deaktiviert. Zwar fährt der Abfahrer nun nach jedem Abtanken zum Startpunkt (im Bogen des "U", aber er erreicht so den Drescher, ohne über die Feldgrenzen hinaus fahren zu wollen. Dauert natürlich alles länger, weil er mehr Fahrweg hat. Betrifft wahrscheinlich nur die Vorgewende-Runden die CP anlegt, bei normaler "hoch runter" Fahrt, könnte es dann wieder klappen, da der Drescher sich dann nicht so weit vom Abfahrer weg bewegt.
Kann man aber trotzdem AD irgendwie "zwingen" nur den Feldbereich zu nutzen und nicht das Umfeld, um das Ziel zu erreichen bzw.  
@Stephan-S 
ist sowas evtl mal geplant? Also quasi die Feldgrenze zu erkennen um sich zu orientieren.
Gruss Micha

Hier ein Bild vom Feld um es sich noch besser vorstellen zu können.
![Feld](https://user-images.githubusercontent.com/28841989/64846044-e666ec80-d60b-11e9-9865-49a7293ee339.jpg)

**Comment by Stephan-S** [comment]
Ich werde als ersten Ansatz Mal die Hangerkennung schärfer schalten, sodass er die Berge nicht als befahrbaren Weg erkennen sollte. 

Du könntest Mal eine Einstellung für mich testen, wenn sich die Gelegenheit ergibt. Wenn du 'Feldstrecken glätten' oder wie es nochmal exakt heißt, ausstellst. Möglicherweise findet er einen schönen Weg durch die Berge, da er für jeden Einzelschritt (~8m) die Steigung überprüft. Aber beim glätten zu einem sanften Pfad schlägt diese Überprüfung fehl.

Ich schau es mir bei Gelegenheit Mal an, komme aber leider diese Woche kaum dazu

**Comment by haamic** [comment]
kein Problem Stephan, danke für den Tip, ich probiere es mal bei Gelegenheit.
Vielleicht könnte AD ja irgendwann auch anhand der Feldgrenzen, solche speziellen Sonderfälle lösen.
Wenn AD wüsste, wo das Feld zu Ende ist, "Halt, hier darf ich nicht weiter, da muss ich links oder rechts fahren und weiter suchen"

**Comment by haamic** [comment]
Habs nochmal probiert. Die glätten Funktion aus und er will trotzdem den kürzesten Weg zum Drescher die Felsen hoch. 
Ich fürchte nur, wenn du die hangerkennung änderst, kommt in meinem Fall kein Fahrzeug mehr die Auffahrt von Tal hoch. Besser wäre es irgendwie wirklich nur auf das Feld zu begrenzen. Die hänge sind an Manchen stellen flacher und würden befahren, da stehen aber soviel Bäume, wo er zwar durchpasst aber durch die enge dann doch hängen bleibt. Es hat keine Priorität, musst nicht extra an dem Spezialfall daran arbeiten. Wäre eine Grenzlinie in anderer Farbe evtl einfacher umsetzbar, als eine Felderkennung einzubauen? Also man fährt die Grenzen in "rot" ab und steckt so gesperrte Gebiete ab.

**Comment by Stephan-S** [comment]
Erledigt bzw. ist noch in Bearbeitung :-)
