### ISSUE TITLE
Parken im Feld, Anhänger

### ISSUE THREAD

**Issue by IcemanGSXR** [Stephan-S/FS19_AutoDrive#484]
Hallo und guten Tag.
Also bei mir funktioniert das Parken im Feld nicht, oder ich verstehe etwas falsch. Abfahrer hat seinen Parkpunkt im Feld, fährt Drescher abtanken, bleibt aber nicht stehen (wie bei CP) sondern fährt wieder zu seinen Wartepunkt zurück. Zumindest bei mir macht er das.

Unterstützt eigentlich der Abfahrer auch mehrere Anhänger oder nur einen? Ich schaffe es nicht das er den 2. Hänger auch belädt.

Danke für deine Hilfe.

Der Mod selbst ist für mich als Singleplayer inzwischen wichtiger geworden als CP, super Arbeit, weiter so.  :-)

**Comment by haamic** [comment]
Also das hat schon mal jemand geschrieben, aber bei mir funktioniert das. Ernte gerade ein riesiges Feld ab mit 4 dreschern und 2 abfahrern. Diese warten im Feld bis wieder eine Drescher geleert werden muss. Allerdings nur , wenn der Abfahrer nicht in der Frucht bzw im Weg steht.

**Comment by worker2419** [comment]
da es bei mir auch funktioniert, ist die Option aktiviert?
![AD_01](https://user-images.githubusercontent.com/47278102/64912069-45228800-d72a-11e9-9f68-82baeeff7549.png)

**Comment by Brummi01** [comment]
Hallo,
obwohl bei mir " Parken im Feld " eingeschaltet ist, fährt mein abfahrer auch jedes mal wieder auf seinen wartepunkt.  Ich benutze die Version 1.0.5.6. verstehe nicht das das bei anderen funktioniert. Da muß ich wohl was Falsch machen.

**Comment by IcemanGSXR** [comment]
Benutze auch die Version 1.0.5.6 Abladerohr ist außerhalb der Frucht. Option ist aktiv. Habe es auch mit mehreren Dreschern, keine Mod-Drescher, und verschiedenen Traktoren mit Hänger versucht. Drescher fährt bei mir mit den "normalen Giants Helfer". Aber es funktioniert nicht.

**Comment by haamic** [comment]
Vielleicht geht der Giants Helfer nicht ? 
Ich nutze für Feldarbeit CP und das klappt in Verbindung mit AD. Vielleicht können ja andere noch schreiben, bei denen es geht, womit sie auf dem Feld arbeiten.

**Comment by worker2419** [comment]
Auf der Südhemmern unterwegs. Standard-Helfer in einem Mod-Fahrzeug mit Multi-Frucht Spargel und Mod-Schlepper mit Mod-Anhänger ohne Probleme.

**Comment by Stephan-S** [comment]
Hey @IcemanGSXR 
Nur nochmal um ganz sicher zu gehen. Stellst du die Option bei jedem Abfahrer ein? Diese 'Parken im Feld' Option ist ja fahrzeugbezogen.

Dann sagst du fahren die Fahrzeuge zu ihrem Wartepunkt zurück. Verstehe ich das also richtig, dass sie dort warten und nicht direkt abfahren fahren oder? Dann würde es nämlich die 'Abfahren ab x%' Einstellung sein, die du entsprechend anpassen müsstest.

Wie sehen ansonsten deine Einstellungen aus? Hast du einen besonders hohen seitlichen oder in längsrichtung Abstand von/zum Rohr eingestellt? Das könnte auch erklären warum er bei dir vielleicht denkt er würde in der Frucht stehen, wenn du entsprechend das Ziel soweit verschoben hast, das er wieder etwas in der Frucht steht.

Ansonsten fällt mir erstmal nichts weiter ein :-)

**Comment by IcemanGSXR** [comment]
Also, mein Kurs ist eine violette Linie in das Feld weit hinein, das Ziel heißt z.B: 01. Drescher hat natürlich das gleiche Ziel eingegeben. 
Drescher beginnt mit normalen Helfer seine Arbeit, bis er 100% erreicht hat, Abladerohr ist außerhalb der Frucht, Fruchtumfahrung auf "Nein".
Helfer hat auch Ziel vom Drescher und seinen Abladetrigger drinnen. Fährt bis zum Ziel 01 und wartet das der Drescher seine 100% erreicht. Fährt dann zum Drescher, tankt in ab und fährt wieder zum Ziel 01 zurück. 
Eingestellt ist "Parken im Feld JA", Abladen ab Level 90%, Fruchtumfahrung NEIN. seitlichen Abstand oder längsrichtung von/zum Rohr habe ich nicht geändert.
Wenn er nun mehr als 90% im Anhänger hat fährt er zum Abladetrigger. Das passt eh alles.
Ich dachte halt das der Abfahrer, so wie CP, nach dem Abtanken vom Drescher halt gleich dort stehen bleibt und dann von dort zum nächsten Abtanken vom Drescher fährt, und nicht jedes mal dazwischen zum Ziel 01 fährt, wartet, und dann wieder zum Drescher fährt, Abtankt und wieder zum Ziel 01 fährt und wieder wartet.
Oder ist das so das er immer zurück zum Ziel 01 fährt und aufs Abtanken wartet?

Danke vielmals für eure Unterstützung.

**Comment by worker2419** [comment]
@IcemanGSXR Es ist genau so wie Du das gewünschte Verhalten beschreibst. Gespann fährt auf die Warteposition bis der Drescher den Abfahrer anfordert. Nach dem Abtanken setzt das Gespann ein Stück zurück und wartet an der Position mit laufendem Motor bis der Drescher den Abfahrer erneut  anfordert und es wird abgetankt. Ist das Füll-Level erreicht, geht es zum abgeladen. Wird das Füll-Level nicht erreicht, kann man mit der Funktion Weiterfahren das Fahren auf die Warteposition und das Abladen erreichen. Warum geht deine Linie in das Feld. Es reicht nach meiner Kenntnis, dem Wartepunkt am Feldrand zu haben. Macht das Probleme? 
@Stephan-S kann es evtl an der Map liegen? Hilft evtl. ein Sceenshot der die Situation zeigt mit HUD und die Log?

**Comment by Stephan-S** [comment]
Ne, hier ist das Problem echt einfach.
Wenn du die Fruchtumfahrung aus hast, wird natürlich nicht mehr auf das Vorhandensein von Frucht überprüft. Der Abfahrer weiß also nicht ob er in oder außerhalb der Frucht steht.
Also fahre ich ihn dementsprechend zurück auf seine Warteposition um zu verhindern, dass er in der Frucht stehen bleibt und dem Drescher im Weg steht.

Also einfach Fruchtumfahrung aktivieren oder damit leben, dass der Abfahrer auf die Warteposition zurück will. Daran werde ich auch im Code nichts ändern. Fruchtumfahrung aus deaktiviert hier jegliche Fruchtabfragen und Fruchttyperkennung etc.

Beste Grüße,
Stephan

**Comment by IcemanGSXR** [comment]
Okay, verstehe. Werde es morgen testen, heute kann ich nicht mehr. Der Dienst ruft.
Danke vielmals für eure Hilfe.

**Comment by IcemanGSXR** [comment]
So wie du es nun beschrieben hast funktioniert es :-).
Meine zweite Frage wäre nun aber ob ich was falsch mache, wieder einmal, oder unterstützt der Abfahrer wirklich nur einen Anhänger.

**Comment by worker2419** [comment]
@IcemanGSXR Habe deine zweite Frage wie folgt im Spiel nachgestellt. Drescher mit 12800 Liter Tank, ein Traktor mit zwei Anhänger je 4000 Liter. Drescher mit CP ruft den Abfahrer und es werden beide Anhänger nacheinander beladen. Abfahrer fährt danach zum Silo und lädt beide Anhänger an.
![AD_Zwei_Anhaenger](https://user-images.githubusercontent.com/47278102/64971549-277b2d00-d8a8-11e9-824b-bcef9dffeaae.png)

**Comment by IcemanGSXR** [comment]
Danke @worker2419 für diese bildliche Erklärung. Ich verwende halt Hänger mit mehr Volumen wo der Drescher halt mehrfach Abtanken muß. Funktioniert auch einmal das er am 2.Hänger abtankt bleibt aber beim nächsten mal so stehen das der 1.Hänger beim Abtankrohr ist, der natürlich schon voll ist, und fährt halt nicht weiter zum 2. Aber was solls, muß ich halt öfters fahren was halt ein großer Zeitverlust ist.

**Comment by IcemanGSXR** [comment]
Hier ein Bild. Wie bereits erwähnt. Einmal Abtanken am 2.Hänger funktioniert, beim nächsten Abtanken bleibt der Abfahrer dann in dieser Position stehen.

![fsScreen_2019_09_17_18_24_56](https://user-images.githubusercontent.com/6430509/65064465-d3904700-d980-11e9-858d-a70326e8eecd.png)

**Comment by IcemanGSXR** [comment]
Ich muß dich leider enttäuschen, er bleibt nach wie vor beim 1.Hänger stehen und wartet.

**Comment by worker2419** [comment]
Drescher mit 17.100 Liter Tank und LKW mit Anhänger (Fliegel Transport Pack) zusammen 60.000 Liter. Erstes Abtanken in den Anhänger 17.100 Liter, Zweites Abtanken in den Anhänger bis 30.000 Liter erreicht, LKW fährt Rückwärts, Rest in LKW entladen, Drittes Abladen funktioniert nicht mehr, LKW fährt soweit vor, dass das Entladerohr über dem vollem Anhänger steht.
![AD_Drescher](https://user-images.githubusercontent.com/47278102/65160430-fa5c8500-da35-11e9-8cdb-fe3524ee37dc.png)

**Comment by IcemanGSXR** [comment]
Was mir nun leider auch aufgefallen ist, selbst wenn ich nur einen Hänger habe bleibt der Abfahrer am Feld stehen und wartet, obwohl er seine Abladegrenze schon erreicht hat.

**Comment by Williwillswisse** [comment]
Hallo Stephan, ich habe mit dieser Version immer noch den Fall, dass der Abfahrer mit vollem Anhänger stehen bleibt. Das Ziel zum Abladen ist zwar grün, aber er fährt nicht los.

![image](https://user-images.githubusercontent.com/47098121/65227455-ef9f0000-dac8-11e9-9f65-fa63d5273e0d.png)

**Comment by IcemanGSXR** [comment]
Der Abfahrer hat noch immer den gleichen Fehler. Erstes Abtanken am 2.Hänger passt, dann bleibt er wieder beim 1.vollen Hänger stehen. Und wie durch @Williwillswisse beschrieben, mit nur einen Anhänger fährt er nicht Abladen.

**Comment by geo-luchs** [comment]
Stephan, du hattest hier in einem Post geschrieben, dass man "Parken im Feld" für jeden Traktor einzeln einstellt.
Dm ist bei mir nicht so. Wenn ich das einstelle, habe ich bei jedem Traktor die gleiche Einstellung. Wenn ich das dann bei einem ändere, ist es auch bei allen anderen geändert.

**Comment by geo-luchs** [comment]
Habe aktuell "Parken im Feld" = Ja  UND "Fruchtumfahrung" = Ja

Aber er ist wieder zum Wartepunkt am Feldrand rausgefahren

**Comment by worker2419** [comment]
@Stephan-S Hallo Stephan, anbei ein kleines Feedback. Parken im Feld pro Fahrzeug gespeichert, kann ich bestätigen. Das Thema Fruchtumfahrung und Parken im Feld funktioniert bei mir ohne Probleme, auch das Fallback, falls es mal nicht anders geht. jetzt zum Thema mehrerer Anhänger. Ich habe das Fliegl Transport Pack nicht weiter genutzt, weil hier folgendes passiert. Es wird erst der Anhänger beladen und danach fährt AD zum Silo entladen, egal was in den Parametern eingestellt ist. Nach Umstellung auf die Kröger TKD 302 sieht das viel besser aus. Warten auf den Drescher, Fahren, Entladen, Parken im Feld Es wird erst der vordere Anhänger befüllt, wenn das nicht reicht, fährt AD vor und befüllt den hinteren, im nächsten Durchgang wird dann der hintere befüllt. Bis voll bzw. Prozent Füllgrad erreicht. Nur die Planen lässt AD (wieder) offen. 
![AD_Abtanken](https://user-images.githubusercontent.com/47278102/65392807-fb185280-dd78-11e9-9638-f26ee45070ec.png)
![AD_Planen](https://user-images.githubusercontent.com/47278102/65392808-fb185280-dd78-11e9-9147-73501941849c.png)

**Comment by IcemanGSXR** [comment]
Ja die Anhänger sind aus diesen Mod-Pack aber die funktionieren einwandfrei. Habe nun am WE ausgiebig (Nachtdienst) getestet. Von meiner Seite her kann ich nur sagen das nun alles einwandfrei funktioniert. Man kann von meiner Seite her diesen Fehler schließen.

Danke vielmals für deine Aufopferung damit dies funktioniert, @Stephan-S 

:-) :-) 🥇
