### ISSUE TITLE
Farben ändern??

### ISSUE THREAD

**Issue by ws1967** [Stephan-S/FS19_AutoDrive#485]
Wäre es möglich, das dunkle violett durch eine andere Farbe zu ersetzen? Dunkelviolett vor braunem oder dunkelgrünem Hintergrund (Feldweg, etc) ist für meine Augen leider eine immer größere Herausforderung - nicht jeder LS19-Spieler ist ein Teenager mit der Sehkraft eines Wanderfalken (bin Generation 50+,) !

**Comment by Stephan-S** [comment]
Hey,
prinzipiell ist das kein Problem. Hast du einen guten Vorschlag welche Farbe besser passt?
Alternativ könnte es auch helfen, wenn du dir die Linien oberhalb der Fahrzeuge anzeigen lässt, anstatt auf dem Boden. Dazu gibt es eine Option in den AutoDrive - Einstellungen :-)

**Comment by haamic** [comment]
Evtl. Farbe in Einstellungen wählbar machen?

**Comment by ws1967** [comment]
Der Vorschlag von haaamic ist mir auch schon durch den Kopf gegangen - dann kann jeder nach seinem Geschmack wählen und es gibt keine Zwangsbeglückung. Das mit dem anzeigen über Kopf mache ich ohnehin meistens - ein schönes kräftiges Rot könnte ich mir aber doch vorstellen.

**Comment by Stephan-S** [comment]
Ich habe die Farben etwas angepasst. Bist du damit schon glücklich? Ich finde die Farbauswahl in den Einstellungen einfach etwas 'übertrieben'. Das Einstellungsmenü möchte ich demnächst eh noch etwas entschlacken :-)

**Comment by ws1967** [comment]
Das Blau ist definitiv eine Verbesserung - allerdings sind die meisten Strecken nach wie vor violett. Für mich eigentlich unlogisch - ev. ein Grafikkartenproblem ??

**Comment by Stephan-S** [comment]
Sorry, ich mache hier mal zu. Eine RGB-Auswahl ist mir zu viel des Guten und ansonsten gab es hier nicht viel Feedback das es wirklich nötig ist.
