### ISSUE TITLE
Änderungen im Kurs-Editor lassen sich nicht speichern

### ISSUE THREAD

**Issue by franky-b08** [Stephan-S/FS19_AutoDrive#486]
Hallo,
erst einmal ein riesen Dankeschön für den Autodrive Mod.
Ich habe seit AD 1.0.5.5 das gleiche Problem (wie schon in Issues #416 beschrieben) das Änderungen der Kurspunkte im Kurs-Editor sich nicht speichen lassen.
Habe es auch mit den im Editor enthaltenen Kursdateien der NF Marsch und Multimap versucht, funtioniert auch nicht.
Mache ich etwas falsch? ..... 
Spiele auf der NF-Marsch 2.3_oG

Viele Grüße

Update 17.09.19
es liegt wohl am Umzug auf mein neues Laptop, 
auf meinem alten Laptop funktioniert das speichern (habe ich gestern Abend getestet).
auf dem Alten war Win10 Home instaliert,
jetzt ist jetzt Win10 Pro drauf.
Ich vermutet das Einstellungen an den Zugriffrechten schuld sind,  sieht auf den ersten Blick aber alles identisch aus.
Habe keinen Schimmer an welchen Knöpfchen ich da drehen muss.

Kann mir da vielleicht jemand einen Tipp geben.

**Comment by Stephan-S** [comment]
Hey, bitte bei Problemen erstmal hier #544 vorbeischauen und eventuell dort deine Probleme nochmal beschreiben wenn sie weiterhin bestehen. Danke
