### ISSUE TITLE
Absturz nachdem man Wegpunkte löscht und neu berechnet

### ISSUE THREAD

**Issue by Caliban2017** [Stephan-S/FS19_AutoDrive#487]
Hallo,

leider hab ich einen weiteren Fehler zu vermelden bei der aktuellen selbst gezippten Version. Wenn ich bei meiner erstellten Strecke einige Wegpunkte raus lösche, weil ich die gerne neu einfahren will, dann funktioniert dies manchmal problemlos. Löscht man jedoch relativ viele Punkte und man klickt dann auf neu berechnen, dann bleibt die Berechnung bei 10% stehen und in die Log wird endlos folgender Fehler geschrieben:

`2019-09-15 01:52 01:52:40 - Recalculating started
2019-09-15 01:52 Error: Running LUA method 'update'.
2019-09-15 01:52 C:/Users/Caliban/Documents/My Games/FarmingSimulator2019/mods/FS19_AutoDrive/scripts/AutoDriveDijkstra.lua:46: attempt to index local 'point' (a nil value)`

Dieser Fehler wiederholt sich dann immer wieder, man kann im Spiel nichts mehr machen, es stürzt also mehr oder weniger ab. 

**Nachtrag:** Ich hab das ganze mal versucht einzugrenzen mit Erfolg, es passiert genau dann der Fehler, wenn ich einen Zielpunkt lösche. Ich hab eine Zielmarkierung an einem Feld gesetzt für einen Abfahrer. Wenn ich diesen lösche, dann kommt obige Fehlermeldung und das Spiel hängt sich auf nachdem ich auf neu berechnen klicke.

**Comment by Stephan-S** [comment]
Hm. ich versuche das gerade nachzustellen.
Zielpunkt löschen alleine kann eigentlich nicht dazu führen.

Die einzige Situation die Probleme erzeugt ist, wenn du Wegpunkte löschst 'während' der Neuberechnung.

Wenn du eine Kursdatei mit einer klaren wie von dir beschriebenen Schwachstelle hast, schick sie mir hier doch mal, dann kann ich das Problem vielleicht finden.
Aber wie gesagt, es kann eigentlich nicht passieren wenn du einfach nur ein Ziel entfernst, dann hätten sich hier schon viele Leute deshalb gemeldet. Da muss noch irgendwas anderes mit reinspielen.

**Comment by Stephan-S** [comment]
Ich mache hier mal zu. Wenn du noch neue Infos für mich hast, immer her damit. Das sollte ja eigentlich nicht passieren. Also bitte melden wenn das Problem noch besteht!
