### ISSUE TITLE
All courses have disappeared after map update

### ISSUE THREAD

**Issue by rebirth101** [Stephan-S/FS19_AutoDrive#488]
I used AutoDrive with NORDFRIESISCHE MARSCH V2.3
Now a new version came out with some small bug fixes, so I replaced the map files with the ones from V2.4, but now all my courses I made in V2.3 are gone. Is this normal? Can I get my courses back somehow?

**Comment by Bobster82** [comment]
You can get them back. Go to ur "C:\Users\Bobster\Documents\My Games\FarmingSimulator2019\savegameBackup"
There would be backups from last couple of times

**Comment by Woife1** [comment]
You had to change the "AutoDrive_NF_Marsch_V2_3_oG_config.xml" in your savegame
In this xml stands 2 time "NF_Marsch_V2_3_oG" this must be "NF_Marsch_V2_4_oG" than it works with the new update

i had played the version without trenches
if you had trenches than the name is "NF_Marsch_V2_4"

**Comment by geo-luchs** [comment]
and I've changed the Filename itself :
AutoDrive_NF_Marsch_V2_3_oG_config.xml  -->AutoDrive_NF_Marsch_V2_4_oG_config.xml

or

AutoDrive_NF_Marsch_V2_3_config.xml  -->AutoDrive_NF_Marsch_V2_4_config.xml

**Comment by Roby1164** [comment]
You should use the editor, open the old xml file, and then save it with the new name ...

**Comment by FS-UK-TheMan1988** [comment]
how do you use the editor?

**Comment by geo-luchs** [comment]
Hello Roby

it is now working with the new AD.jar from 28.9.2019.See here:
Stephan has worked on one of my requests
https://github.com/Stephan-S/FS19_AutoDrive/issues/537#issuecomment-536165088
With this the needed change within the XML file will be done.
