### ISSUE TITLE
Mehr Status anzeigen

### ISSUE THREAD

**Issue by Merlin110480** [Stephan-S/FS19_AutoDrive#49]
Hi,

Es währe schön, mehr zu sehen was Autodrive gerade macht.

Abfahren: welcher Punkt gerade angefahren wird. (Farblich Markieren)

Drescher abtanken: anzeigen ob ein Drescher gefunden wurde

evt. macht es im Moment sinn einen Debug-Modus in den Optionen einschaltbar zu machen, 
um dann mehr Informationen ausgeben zu können.

grüße Christian

**Comment by Stephan-S** [comment]
Servus,
das Anzeigen des aktuellen Zielpunkts macht auf jeden Fall Sinn, bei den kombinierten Modi.
Ob der Drescher gefunden wurde, sieht man ja daran ob er losfährt oder nicht, aber du hast schon Recht, das könnte man durchaus im HUD mit einblenden.
Ich nehme es mal mit in die ToDo-Liste auf

**Comment by Merlin110480** [comment]
Genau so hatte ich mir das für den Zielpunkt vorgestellt. Prima!

Beim Drescher Modus könnte ich noch nicht testen, 
Wenn ich das richtig verstanden habe, ruft der Drescher den abfahrer, richtig?
Dann währe es denke ich schon mal gut zumindest zu sehen wenn er das nicht kann.
Dann weiß man zumindest wenn die 200m erreicht sind und man den Abfahrer Punkt einstellen sollte.
