### ISSUE TITLE
Combine issues

### ISSUE THREAD

**Issue by corbyf** [Stephan-S/FS19_AutoDrive#490]
Love your mod, but having issues with unloading combine.  I've followed your youtube series etc.  I must have a newer version of autodrive as I have drop down menu in hud.

I set combine through courseplay to combine field.  When it gets to unload, autodrive kicks in and will then follow whatever route is selected in drop down, like field 10 for example.
The reason I need to use courseplay for combine as I need headlands done.

When I use the generic  "helper" it seems to wait in field for tractor and trailer to unload then continues its job.

Does Autodrive not work with combine and unloading or am I doing something wrong?

**Comment by andejx** [comment]
Make sure you have the latest courseplay [https://github.com/Courseplay/courseplay/releases](url) and the latest autodrive. 

Have you got autodrive in combine unload mode, there's a button in the new ui that switches between modes like "load", "deliver", "drive", "combine" etc.

Basically, you build your autodrive network, or at the very least one "field" point (usually off to the side near the road, not actually on the field) where autodrive will wait for the combine, and at least one place to unload (eg silo).

Start up your courseplay course combine to go, but make sure you have it set to stop moving while unloading, its in the courseplay options. Or just let the AI helper drive the combine. 

Set your autodrive to combine mode, select the field point as the first target, set the silo or other dropoff location as the second target and enable Autodrive.

What should happen is the autodrive should go to the first target, the field point you set, wait there until courseplay or the normal AI helper says it needs unloading, then it will automatically chart a course from its wait point to the combine, unload, then depending on if you have "wait in field" and "avoid fruit" set to enabled, it will either wait where it unloaded the combine last, or it will return to its starting field wait point, OR if its hit its fill limit it will drive back to the start THEN move to the second waypoint you set, unload, then return to the first point again to wait.

Hope that makes sense. Works fine for me.

**Comment by Ontragon** [comment]
combine stops and wait for the unloder with open tube and nothing happend?
i had this too and i must change the cutter to gets its working.

**Comment by Bobster82** [comment]
! Make sure ur combine has the same 1st target in autodrive (no need to start, just select) as ur unloader 1st point (field point)

**Comment by corbyf** [comment]
Combine seems to be working now that in Autodrive, I have the "unload bunker silo"  No idea why this one works.  Every other option I choose, the combine takes off after its full

**Comment by andejx** [comment]
https://github.com/Stephan-S/FS19_AutoDrive/issues/457

Could be related to this where the mode you're actually in doesn't line up with what the ui says?

**Comment by andejx** [comment]
Try reverting to 1.0.5.1 and see if it all works again.

**Comment by Stephan-S** [comment]
@corbyf You should not enable AutoDrive in the combine and do not select 'Use autodrive for refill/unload" in the courseplay settings. This is probably what's causing your combine to drive off when it's full.
You don't have to set anything AutoDrive related in Courseplay for the combine mode to work.
