### ISSUE TITLE
Frage Mode Drescher abfahren.

### ISSUE THREAD

**Issue by Williwillswisse** [Stephan-S/FS19_AutoDrive#491]
Hi Stephan, das wird ja immer abgefahrener was du AutoDrive so beibringst. Respekt !
Ich hätte mal eine Frage zum Abfahren von Dreschern: wenn der Abfahrer am Feldrand wartet: Bis zu welcher Entfernung erkennt er den Drescher. Ist das Feld zu groß müsste ich mir dann wohl einen zweiten Wartepunkt schaffen, oder?

**Comment by Stephan-S** [comment]
Bis zu 300 Metern mit der Einstellung 'Suche Abfahrer'
Wenn du die gleichen Ziele eingestellt hast in Abfahrer und Drescher, über die ganze Karte

**Comment by Williwillswisse** [comment]
Danke für die schnelle Antwort und den super Mod.

Holen Sie sich Outlook für Android<https://aka.ms/ghei36>

________________________________
