### ISSUE TITLE
Problem mit PonsseScorpion

### ISSUE THREAD

**Issue by siggiblue** [Stephan-S/FS19_AutoDrive#494]
Hallo,
sobald Autodrive im Modordner ist, wird die Funktion "Z=Schnittlänge" nicht mehr im F1-Menü angezeigt. Es sind nur noch Stämme in der Standardlänge von 1m möglich.
Im Modordner befindet sich nur eine Map, Autodrive,PonsseScorpion und Global Company.

Eine Logdatei ist beigefügt.

SiggiBlue
[log.txt](https://github.com/Stephan-S/FS19_AutoDrive/files/3617041/log.txt)
![mit Autodrive 1507](https://user-images.githubusercontent.com/49618984/64972336-63fb5880-d8a9-11e9-8e38-593716c46daa.png)
![ohne AutoDrive](https://user-images.githubusercontent.com/49618984/64972354-6cec2a00-d8a9-11e9-89ec-fe1b2f1a1e8e.png)

**Comment by Keven-Fendt** [comment]
Stehle die AD Hilfe aus dann kannst du die länge einstehlen 
Gruß Keven Fendt

**Comment by siggiblue** [comment]
keven-fendt
vielen dank für die Antwort; ich habe es auch gerade gemerkt 
machmal ist man einfach zu dämlich

gruß
siggiblue
