### ISSUE TITLE
Symbole im HUD

### ISSUE THREAD

**Issue by Woife1** [Stephan-S/FS19_AutoDrive#495]
Hi Stephan,

erstmal super arbeit mit AutoDrive.
Jetzt mal um das Thema um das es mir geht ;)
Könntest du die Symbole im oberen Teil des Huds so konfigurieren das sie passen.
Ich meine die passenden Symbole für aufladen, abholen und den Waypoint.

Zum Beispiel das beim Modus "Abholen und Anliefern" am Abholort das Ladensymbol steht und beim Abkipport das Entladensymbol, bei den anderen Modis entsprechend angepasst. 

Falls nur ich mit den Orten durcheinander komme kannst du das ignorieren.

![Unbenannt](https://user-images.githubusercontent.com/55350545/64983646-42a66680-d8c1-11e9-85e0-ae8e7f4eb81f.png)

**Comment by worker2419** [comment]
liegt im Auge des Betrachters, komme persönlich gut damit zurecht

**Comment by Tensuko** [comment]
Im Modus Abliefern steht das Abladeziel aber oben wenn ich mich nicht irre.
Auch das die 'Ware' die man eigentlich abholt beim Ziel ausgewählt wird finde ich nach wie vor etwas verwirrend.

Verwirrt schon alles etwas ich kann das gut nachvollziehen.
Wäre schon Sinniger, wenn das Ziel immer oben ist und man eher ein 'Aufladeort' unten hat, oder ein Feld Symbol beim Drescher abtanken usw.

**Comment by worker2419** [comment]
Wenn eine Anpassung machbar ist und Stephan das umsetzt sicher eine Vereinfachung für alle. :-)

**Comment by geo-luchs** [comment]
Moin.

ich habe  jetzt die Version 1.0.5.8, und da gibt es nun andere Symbole
![grafik](https://user-images.githubusercontent.com/53658780/65402381-41e46780-ddce-11e9-97fd-18b1e9c961b8.png)

**Comment by Tensuko** [comment]
ja sehr nice. vlt komme ich dann auch besser klar

**Comment by Stephan-S** [comment]
Erledigt. Oder gibt's noch Wünsche? :-)
