### ISSUE TITLE
Frage: Kurs zum Auffüllen richtig einstellen

### ISSUE THREAD

**Issue by Knowen** [Stephan-S/FS19_AutoDrive#496]
Hallo,

ich war eine zeitlang inaktiv beim LS und habe nur am Rande mitbekommen, dass einige Funktionen dazu gekommen sind.

Eine davon soll sein, Saatgut und Dünger bei einer Sämaschine auffüllen zu lassen.

Ich habe gestern Abend ein wenig rumprobiert und denke, dass ich einiges nicht richtig eingestellt habe. Das Säen und Düngen habe ich CP machen lassen. In CP habe ich die Nutzung von AD zum unload/refill aktiviert. In AD habe ich den Modus "Abholen" gehabt. Dort Als Start den Feldpunkt und als Ziel das Saatgutsilo.

Er ist aber nicht zum auffüllen losgefahren. Ich frage mich nun, wie stelle ich das richtig ein?

Grüße,
Knowen

**Comment by Stephan-S** [comment]
Hey,

von deinen Einstellungen her klingt alles richtig.

> Er ist aber nicht zum auffüllen losgefahren

Er fährt natürlich nicht von alleine los, falls du das erwartet hast. Aber sobald du Courseplay mit einem normalen Feldkurs startest und er dabei merkt, dass einer der Tanks (Dünger/Saatgut) leer ist, wird AutoDrive aktiv und sollte laden fahren. Dann wieder zurück zum Zielpunkt und an CP übergeben.

Beste Grüße,
Stephan

**Comment by Knowen** [comment]
Moin,

klar habe ich nicht erwartet, dass er sofort los fährt. Er soll natürlich nur dann zum Aufladen fahren, wenn Saatgut oder Dünger alle ist. Das war gestern Abend auch einmal der Fall. Dann ist er trotzdem nicht zum Auffüllen gefahren. 

Wenn die Einstellungen richtig waren, ist es vllt ein Bug. Habe gerade keine Log von gestern Abend zur Hand. Ich teste das heute Abend nochmal und melde mich dann ggf. mit einer Log zurück.

Grüße

**Comment by Stephan-S** [comment]
Alles klar.
Möglicherweise hat AutoDrive auch Probleme einen Weg zu berechnen. Dann würde es auf jeden Fall einen Fehler in der log Datei dazu geben und falls du im Fahrzeug sitzt, erkennst du es daran, dass AutoDrive eine kurze Zeit aktiv ist und berechnet, aber nicht losfährt. Wenn dann kein Weg gefunden wird, schaltet er sich wieder ab.

**Comment by worker2419** [comment]
Moin, kann ich bestätigen. Die Einstellungen im HUD habe ich genau so: 
![AD_02](https://user-images.githubusercontent.com/47278102/65044098-95812c00-d95c-11e9-96c9-cbec8f336df9.png)
Habe den Helfer dann ein wenig geärgert und er hat keinen Weg gefunden, so wie Stephan geschrieben hat. 
2019-09-17 14:41 Going into fallback mode - no fruit free path found in reasonable time
2019-09-17 14:41 Stop searching - no path found in reasonable time
2019-09-17 14:41 Autodrive encountered a problem during initialization - shutting down
2019-09-17 14:43 Going into fallback mode - no fruit free path found in reasonable time
2019-09-17 14:43 Stop searching - no path found in reasonable time
2019-09-17 14:43 Autodrive encountered a problem during initialization - shutting down
Das kommt dann dabei raus.

**Comment by Knowen** [comment]
Okay, danke.
Melde mich heute Abend.

**Comment by RudiBergfeld** [comment]
Bei mir findet er den Weg Ladert  aber nichts weder Dünger noch Saatgut

**Comment by Huskiel** [comment]
Habe das gleiche Problem wie Rudi.
Fährt zum refillpunkt läd nichts und bleibt stehen.

**Comment by Knowen** [comment]
Guten Morgen,

habe gestern Abend die Sämaschine mal laufen lassen. 
Einstellung bei AD war auf das Saatgutsilo mit Saatgut als Befüllung. 

Nach ein paar Minuten war dann Dünger leer und die Maschine machte sich auf den Weg zum auffüllen. Ich habe Kalk, Dünger und Saatgut in dieser Reihenfolge als Silos entlang einer Linie bei AD. Am Düngertrigger blieb die Maschine stehen und hat sich aufgefüllt. Dann fuhr sie ein paar Meter weiter zum Saatgutsilo, öffnete die andere Klappe und dann war Stillstand. 

Saatgut und Dünger befüllen war in den Einstellungen aktiviert.
Leider habe ich keine Log mehr davon. Habe die, mit diesem Fehler, ausversehen überschrieben. Hoffe die Beschreibung reicht aus, ansonsten versuche ich den Fehler zu reproduzieren.

Grüße,
Knowen

**Comment by worker2419** [comment]
Hallo zusammen, ich habe den Fehler nicht. Map ist die Südhemmern. Trecker MOD Schlepper, Sähmaschine MOD Horsch Pronto mit angepasstem Fruit-Typ. Feldarbeit macht CP, bei leerem Saatgut-Tank fährt AD brav auf den Hof und füllt denn Saatgut Tank auf, setzt ein Stück vor und füllt auch den Dünger nach. Anschließend wieder auf das Feld und führt seine Arbeit weiter aus. 
LOG:
 AD: Set to recalculating routes
2019-09-20 18:24 Game saved successfully.
2019-09-20 18:28 CourseGeneratorScreen:onCreate()
2019-09-20 18:35 Game saved successfully.
2019-09-20 18:37 CourseGeneratorScreen:onCreate()
2019-09-20 18:50 AD: Set to recalculating routes
2019-09-20 18:50 Game saved successfully.
2019-09-20 18:58 CourseGeneratorScreen:onCreate()
2019-09-20 18:58 CourseGeneratorScreen:onCreate()
2019-09-20 19:03 Game saved successfully.
2019-09-20 19:14 AD: Set to recalculating routes
2019-09-20 19:14 Game saved successfully.
2019-09-20 19:27 CourseGeneratorScreen:onCreate()
2019-09-20 19:29 AD: Set to recalculating routes
2019-09-20 19:29 Game saved successfully.
2019-09-20 19:40 AD: Set to recalculating routes
2019-09-20 19:40 Game saved successfully.

@Stephan-S kann es evtl. an den verbauten Fill-Triggern liegen in Kombination mit den Geräten?

**Comment by RudiBergfeld** [comment]
Hallo,
ich glaube das Problem gefunden zu haben ich spiele auf Suedhemmern und habe die Silos aus dem Hofpack ich denke es ist wichtig das der Zielpunkt an der richtigen stelle ist , ich habe den Zielpunk ein Wegpunkt weiter gesetzt  so das der Tracktor über das eigentliche Ziel hinausfährt un dann geht es er hält am Trigger und füllt die Maschine. versucht es mal
LG Rudi

**Comment by geo-luchs** [comment]
Hallo zusammen

gibt es eine Maximalentfernung zwischen dem ersten  Ladepunkt und dem eigentlichen Wegpunkt?
Ich habe auf der NF Marsch die Düngerherstellung und die Saatgutherstellung nebeneinander, und danach den Wegpunkt.

Aber er rauscht bei der Düngerbefüllung vorbei und lädt nur das Saatgut.
![Saatgut-Dünger](https://user-images.githubusercontent.com/53658780/65456713-39317700-de4a-11e9-85cc-9bfa12197dd5.png)

**Comment by geo-luchs** [comment]
Nabend.

Habe jetzt mit verschiedenen Test-Savegames getestet. Kurz bevor ich wahnsinnig geworden bin, weil es immer wieder ein anderes Verhalten gab, hat es dann auf einmal geklappt, wo es vorher nicht geklappt hatte.

Meine Saatmaschine war bei 0% / 0%.
Ich habe das Gefühl, dass man, bevor man den CP Kurs startet, einmal kurz den AD Kurs anstarten muss. Einfach nur an und wieder aus, er muss den Kurs nicht abfahren.
Wenn ich dann CP einschalte,  aktiviert er sofort AD und fährt zum Befüllen. und diesmal werden auch beide Kammern befüllt.

**Comment by geo-luchs** [comment]
ich kann es leider nicht verlässlich reproduzieren.
Jetzt fährt er am ersten Silo relativ schnell vorbei, öffnet aber die Abdeckung, fängt an Saatgut zu befüllen, aber hat noch soviel Schwung, dass er am Trigger vorbeirollt, und dann stehenbleibt.

Oder er rollt am ersten Silo vorbei, und lädt am 2. Silo, dem Dünger auf.
Das scheint jedesmal anders zu sein :-(

ich hab auch schon den vorausschauenden Wert (Bremse) hochgesetzt, auf 90m.
Dann hat er auf einmal länger befüllt, aber auch nicht auf 100%

Beim nächsten Versuch mit 100m rauscht er auf einmal wieder vorbei,, und befüllt beim 1. Silo nur 2% und bleibt zwischen den Silos stehen.

Ich erkenn keine Logik darin, wann er stehenbleibt  :-(

**Comment by geo-luchs** [comment]
Stephan, wäre es möglich, dass Du die Entfernung zwischen dem Zielpunkt und dem ersten Ladepunkt in den Einstellungen konfigurierbar machst?

Ich vermute, du erkennst die Ladepunkt ab einem definierten Punkt vor dem Zielpunkt.

Gruß
Carsten

**Comment by geo-luchs** [comment]
Hallo Stephan, hallo zusammen

habe mich jetzt mal etwas intensiver damit beschäftigt.
@Stephan-S  : bitte korrigiere mich, falls ich es nicht ganz richtig darstelle.

Ich habe es jetzt nur mit einer Saat-Maschine ausgiebig getestet: 
Kann sein, dass der Befülltrigger der Saat-Maschine auch eine Rolle spielt, aber ich möchte kurz versuchen zu erläutern, was meiner Meinung nach aus AD Sicht eine Rolle spielt:

a) zum Befüllen muss die Abdeckung offen sein, das steuert Stephan mit einer Entfernung vor dem Ziel-Wegpunkt. --> aktuell 25m, da öffnet er aktiv die Abdeckung

b) der Zielwegpunkt muss HINTER dem letzten Trigger sein, sodass der Traktor eigentlich weiterfahren muss am Beladetrigger.

c) die Geschwindigkeit ist wohl auch entscheidend. Wenn die Befüllung anfängt, fährt der Traktor noch. 
Es sieht so aus, als ob das Spiel (LS19 oder AD, ich weiß es nicht) die Befüllung erkennt, und den Traktor anhalten will. Aber wenn er zu schnell unter dem Beladetrigger durchrollt, nimmt er wieder Fahrt auf, und befüllt teilweise nur kurz.

d) die Geschwindigkeit steuert Stephan abhängig von den Wegpunkten vor dem Ziel-Wegpunkt.
5 Punkte vor Ziel : 30
4 und 3 Punkte vor Ziel : 24
2 Punkte vor Ziel: 12
 
Ich habe nun festgestellt, das bei mir bei Tempo 24 nur beim Vorbeifahren kurz befüllt wird, aber er weiterfährt. also ist 24 zu schnell.


Für mein spezielles Problem mit den FED Produktionen, die ich etwas weiter auseinander stellen muss, habe ich überden AD Course Ditor folgenden Work-around gefunden:

Ich habe zwischen Ziel-Wegpunkt und vor der Düngerproduktion nur max. 2 Wegpunkte, damit er langsam genug bei der Düngerproduktion fährt.

Aber Stephan müsste noch das Öffnen der Abdeckung auf 75m vorher hochsetzen, damit es bei mir funktioniert.
Ich hoffe, dass das nicht was anderem kollidiert.

**Comment by worker2419** [comment]
Hallo zusammen, was mir im Spiel aufgefallen ist, 2 Kammer Sämaschinen die beide Klappen zur gleichen Zeit öffnen, lassen sich bei mir ohne Probleme befüllen. 2 Kammer Sämaschinen, wo sich die Klappen nacheinander öffnen (sollen) haben das Problem , das nur eine Kammer befüllt wird.

**Comment by BraveBavarian** [comment]
Als Workaround eventuell zweimal durch den Trigger fahren?
-- 
Sent from my Android phone with GMX Mail. Please excuse my brevity.On 9/30/19, 9:17 AM worker2419 <notifications@github.com> wrote:
Hallo zusammen, was mir im Spiel aufgefallen ist, 2 Kammer Sämaschinen die beide Klappen zur gleichen Zeit öffnen, lassen sich bei mir ohne Probleme befüllen. 2 Kammer Sämaschinen, wo sich die Klappen nacheinander öffnen (sollen) haben das Problem , das nur eine Kammer befüllt wird.



—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.

[

{

"@context": "http://schema.org",

"@type": "EmailMessage",

"potentialAction": {

"@type": "ViewAction",

"target": "https://github.com/Stephan-S/FS19_AutoDrive/issues/496?email_source=notifications\u0026email_token=ANFXGKCVLLP3TE2A6MRYYILQMGRXDA5CNFSM4IXOIQ22YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD74VSWY#issuecomment-536435035",

"url": "https://github.com/Stephan-S/FS19_AutoDrive/issues/496?email_source=notifications\u0026email_token=ANFXGKCVLLP3TE2A6MRYYILQMGRXDA5CNFSM4IXOIQ22YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD74VSWY#issuecomment-536435035",

"name": "View Issue"

},

"description": "View this Issue on GitHub",

"publisher": {

"@type": "Organization",

"name": "GitHub",

"url": "https://github.com"

}

}

]

**Comment by geo-luchs** [comment]
2mal Trigger fahren ändert leider nichts.
bei einem 2 Klappen-Gerät öffnet er anscheinend immer nur die Saatgut-Klappe.

Ich habe nun einige verschiedene Saat-Maschinen , original aus dem Giants LS19, keine Mods getestet.

1 Kammer : Pronto DC 9 :   klappt wunderbar, sofern der Zielwegpunkt nicht zu früh gesetzt ist, und Saatgut und Dünger-Beladung nicht zu weit auseinander

2 Kammer : Tempo L16 :  er öffnet immer nur die kleinere hintere Klappe fürs Saatgut. Dünger geht nicht.

1 Kammer??,  Ceres Master 3570 :  ich kann auf meinem kleinen Rundkurs nicht mal den Abladewegpunkt anfahren. Er will immer nur den oberen Wegpunkt anfahren, und macht auch nie die Klappen auf.

Für alle 3 Maschinen habe ich natürlich den gleichen Rundkurs benutzt.

Ds mit der Ceres Master 3570 ist echt merkwürdig.

Bei der 2-Kammer Maschine stellt sich die Frage, ob man lua-technisch die beiden Klappen einzeln steuern kann.

**Comment by Stephan-S** [comment]
KLappt das alles jetzt soweit seit den letzten Updates? Ich beschränke ja nicht mehr wie groß das Füllvolumen sein muss.

**Comment by geo-luchs** [comment]
Ich teste heute Abend nochmal

**Comment by geo-luchs** [comment]
Hi Stephan

klappt leider noch nicht. Habe jetzt auf 100m vor Silo eingestellt. Damit öffnet er zwar die Abdeckung, fährt aber leider zu schnell unterm Rohr durch. Der Dünger, wo er zuerst vorbeikommt, füllt nur beim Vorbeifahren ganz wenig ein, aber der Traktor ist zu schnell, als dass er fürs Beladen stoppen würde. Erst beim 2. TRigger (Saatgut), der kurz vorm Zielpunkt ist, ist er langsam genug.

Die Frage ist: erkennst du das mit AD, ob ein Befüllvorgang läuft, und versuchst abzubremsen, und sobald der Befüllvorgang gestoppt ist, zu beschleunigen?
Dann ist es so, dass Du ihn einfach nicht schnell genug abbremsen kannst beim 1. Trigger, wo er aber noch zu schnell ist.

Hast Du eine Idee, wie man das lösen kann?

Letztendlich müsste er mit Öffnen der Abdeckung bereits deutlich langsamer werden.

**Comment by geo-luchs** [comment]
wie könnte ich die Entfernung messen?
Ich habe AD jetzt mal testweise so definiert, dass er bei 50m auf 12Kmh runterbremsen soll. Ist aber beim Befüllen noch ca. bei 15 Kmh. Das ist zu schnell, als dass er rechtzeitig anhält zum beladen. Danach rollt er allerdings mit nur  8Kmh weiter, ist allerdings noch einige Meter entfernt gewesen vom 2. TRigger.

**Comment by geo-luchs** [comment]
@Stephan-S   ich komm irgendwie überhaupt nicht mit dem Inhalt von DistanceToTarget zurecht.

Ich habe in 
function AutoDrive:driveToNextWayPoint(vehicle, dt) 

ein print eingebaut:
    local distanceToTarget = AutoDrive:getDistanceToLastWaypoint(vehicle, 10);
	print ("DEBUG-CARSTEN :    Entfernung :  " .. distanceToTarget);

Aber die Werte, die ich da sehe, sind sehr merkwürdig, und entsprechen für mich keineswegs irgendeiner Entfernung zum Zielpunkt.
Ich fahre eine gerade Strecke auf den Zielpunkt hin, bin relativ weit weg, und  ich sehe im Output 30.x .
Ich nähere mich, der Wert geht aber hoch bis 60, danach dann langsam wieder runter.
Zuletzt bleibt er dann bei 6.84, obwohl er dem Zielpunkt immer näher kommt.

Was ist das genau für ein Wert? Ist das eine Art Entfernung per Luftlinie? oder  errechnet anhand der grünen Fahrlinie?

**Comment by Stephan-S** [comment]
Das ist die Summe der Länge der einzelnen Segmente bis zum Ziel aber eben maximal '10' Schritte voraus um die Berechnung nicht unnötig lange zu gestalten.

Ich habe aber eben einen Fehler entdeckt. Hier habe ich noch 25m genutzt statt die maxTriggerRange.
Also im letzten commit

**Comment by geo-luchs** [comment]
Hi Stephan

prima, also mit dem Pronto DC 9 geht es jetzt damit. Allerdings muss ich die 100m einstellen.
Wäre es möglich, noch ein 75   zwischen die 50 und die 100m zu setzen? ;-)

Allerdings kam es mir komisch vor, dass er mit 50m nicht mal den 2. TRigger geschafft hatte anzubremsen.

**Comment by Lars-LS17** [comment]
Hallo,

scheinbar testen die meisten das mit der 2 Triggern (1x für Saatgut, 1x für Dünger)
Gibt es auch eine Möglichkeit die Sähmaschine über das Hofsilo  (Ein Trigger für Saatgut&Dünger) aufzufüllen?
Aktuell fährt AD einfach durch den Trigger durch.

**Comment by Iwan1803** [comment]
Da kein weiteres Feedback -> geschlossen.
Bitte mit der neuesten Version erneut versuchen und bei Bedarf ein neues Issue erstellen, danke!
_Since no further feedback -> closed.
Please try with the latest version and create a new issue if necessary, thanks!_
