### ISSUE TITLE
AD Editor

### ISSUE THREAD

**Issue by FunFarmer1** [Stephan-S/FS19_AutoDrive#497]
Hallo, 
ich wollte mal Fragen wie man einen AD Kurs in diesem editor aufmacht bzw. wo ich diesen editor herbekomme ?

**Comment by worker2419** [comment]
@FunFarmer1 hier der Weg, den ich beschritten habe, solltes es einen einfacheren Weg geben, gerne posten

1. Die aktuelle Version von Autodrive herunterladen (Reiter Code / rechts Clone or Download / Download ZIP
2. Die Datei FS19_AutoDrive-master.zip entpacken, das ein Ordner FS19_AutoDrive-master entsteht
3. Aus deiner Map die Datei pda_map_H.dds exportieren und als PNG Datei mit sprechenden Namen im Ordner FS19_AutoDrive-master\AutoDrive Course Editor\src\mapImages anlegen (zB. meineMap.png)
4. Den Ordner FS19_AutoDrive-master\courses öffnen und darin eine Ordner anlegen (zB. meineMap)
5. Aus dem Savegame Ordner die Datei AutoDrive_xxxxxxxxx_config.xml im Ordner  FS19_AutoDrive-master\courses\meineMap ablegen
6. Die Datei ad.jar starten und über Load Config die AutoDrive_xxxxxxxxx_config.xml laden
7. Über Load Map Das Bild meineMap.png dazu laden
Etwas Geduld haben, je nach System dauert das Laden etwas

**Comment by FunFarmer1** [comment]
Vielen Dank worker das hat mir sehr geholfen!
