### ISSUE TITLE
Abfahrer Bugs

### ISSUE THREAD

**Issue by Merlin110480** [Stephan-S/FS19_AutoDrive#50]
Hallo,

- Silo voller als Anhänger Volumen 
Alles einwandfrei, lässt sich auch mit ">>" unterbrechen und fährt ab

- Silo leer oder Anhänger Volumen größer als Silo Inhalt
Bleibt bei leeren Silo einfach stehen und lässt sich auch durch ">>" nicht dazu bewegen abzufahren

Außerdem hatten kam es schon mal vor das das abladen nicht funktioniert hat, also:

An Trigger angekommen
Die ablade Animation ist zu sehen
In der Hilfe oben links steht auch das er ablädt

-> Hänger Füllstand ändert sich aber nicht.

Dach auch kein manuelles abladen mehr möglich.
Hilft nur noch neustart des Spiels oder Servers

Kam mit Mods und Original Fahrzeugen und auch auf Original Karten vor.

Werde versuchen das weiter einzugrenzen, lässt sich leider nicht reproduzieren.

gruß Christian

**Comment by Stephan-S** [comment]
Servus,

bei leerem Silo habe ich im letzten Patch (1.0.0.8) eingebaut, dass er weiterfährt. Das werde ich noch als Option in das Einstellungsmenü rausziehen und etwas verfeinern.

Den Triggerbug habe ich bisher noch nicht gesehen. Kannst du das noch irgendwie weier beschreiben eingrenzen? Erstens, mit welcher Version habt ihr gespielt? Die offizielle Modhub-Version? Dann kann es tatsächlich passieren, da er dort noch immer versucht, den ersten Filltype, also das erste Füllgut aus dem Silo abzuladen, egal welcher im HUD eingestellt ist. Wenn das aber bei einem der aktuelleren Patches passiert ist, wäre noch interessant ob es erstens auf dem Server oder im SP passiert und ob ein bestimmtest Silo betroffen ist. Eventuell falls das auftritt auch bitte mal das Log kopieren. Das wäre sehr hilfreich.

Vielen Dank!

**Comment by Merlin110480** [comment]
Hi,

Im MP auf dem Dedi hatten 1.0.0.4 im SP aber auch mit 1.0.0.6

Werde das weiter beobachten. Aus dem Bauch raus würde ich sagen, nach einem Neustart.

falls es dabei Auffälligkeiten im Log gibt hänge ich die hier an.

gruß Christian

**Comment by Merlin110480** [comment]
Hallo Stephan,

Hab jetzt noch mal mit 1.0.0.8 und dann heute mit 1.0.0.9 getestet, das ablade Problem ist nicht wieder aufgetaucht.

Wenn es wieder vor kommen sollte melde ich mich wieder, aber jetzt klappt das laden seit der 1.0.0.8
ohne das ich im Fahrzeug sitze nicht mehr, egal welcher Füllstand im Silo.
Wenn ich im Fahrzeug bin und der Hänger voll wird fährt er einwandfrei weiter.
Wenn der Hänger nicht voll wird bleibt er stehen, lässt sich aber mit ">>" abfahren.

Wenn er an einem leeren Silo ankommt, bleibt er stehen, danach passiert aber nichts mehr.
Auch wenn das Silo danach gefüllt wird. Erst mit ">>" fängt er wieder an zu Füllen und fährt dann ganz normal seine runde.

Hoffe da ist noch was zu machen.

Unterschied von 1.0.0.8 zu 1.0.0.9 war auch das er am Trigger bis zum Haltepunkt weiter gefahren ist.
Das macht er jetzt in der 0.9 nicht mehr, was ich besser finden.
Hatte einen Haltepunkt zu weit gesetzt und dann ist er während dem Füllen drunter durch gefahren.

Hast du geplant mehr als einen Hänger zu unterstützen, scheint mir im Moment nicht zu klappen.
Müsste mir mal anschauen wie Courseplay das macht. Da hatte das befühlen und entladen soweit geklappt. Bei Autodrive müsste ja Theoretisch der Haltepunkt soweit weg sein das bis dahin alle Hänger be oder entladen hat, richtig?

gruß Christian
