### ISSUE TITLE
Abfahrer in autodrive

### ISSUE THREAD

**Issue by RudiBergfeld** [Stephan-S/FS19_AutoDrive#501]
ist es möglich die Afahrer eine Maschine oder ein Feld zuzuweisen. Wenn 2 Maschinen auf den Nachbarfeldern sind Fahren die Abfahrer durchein ander. Ich meine der Abfahrer mit Getreide im Anhänger fährt auch zum Kartoffelroder und andersrum. Beim Afahren mit eimen LKW  erkennnt er nicht das das Zugfahrzeug auch einen Laderaum hat , beim Entladen erkennt er es richtig oder muss mann damit Leben. Die Sähmaschinen werden nicht am Silo Gefüllt das kann aber an Giantis liegen Das war im 17er auch schon ein Problem.

**Comment by Knowen** [comment]
Guten Morgen,

in den Einstellungen von AD musst du die Option "Abfahrer finden" auf Nein stellen.

Nun zum Fahrzeugsetup:
Ich nehme an, dass du ein Wegpunkt beim Feld hast, bei dem die Abfahrer warten z.B. _Feld_3_. Natürlich auch ein Wegpunkt für das _Hofsilo_. Also stellst du bei den Abfahrern im Modus "**Drescher abfahren**" als Start _Feld_3_ ein und als Ziel _Hofsilo_. Das kannst du bei mehreren Abfahrern machen. Beim Drescher, egal im welchen Modus (ich nehme immer "**Fahren**", aber das ist egal), gibst du ebenfalls _Feld_3_ an. Somit ist die Verbindung hergestellt. 

Grüße,
Knowen

**Comment by RudiBergfeld** [comment]
Gutem Morgen, 
danke für den Hinweis hat Prima geklappt .
LG Rudi

Gesendet von Mail für Windows 10

Von: Knowen
Gesendet: Freitag, 20. September 2019 06:43
An: Stephan-S/FS19_AutoDrive
Cc: RudiBergfeld; Author
Betreff: Re: [Stephan-S/FS19_AutoDrive] Abfahrer in autodrive (#501)

Guten Morgen,
in den Einstellungen von AD musst du die Option "Abfahrer finden" auf Nein stellen.
Nun zum Fahrzeugsetup:
Ich nehme an, dass du ein Wegpunkt beim Feld hast, bei dem die Abfahrer warten z.B. Feld_3. Natürlich auch ein Wegpunkt für das Hofsilo. Also stellst du bei den Abfahrern im Modus "Drescher abfahren" als Start Feld_3 ein und als Ziel Hofsilo. Das kannst du bei mehreren Abfahrern machen. Beim Drescher, egal im welchen Modus (ich nehme immer "Fahren", aber das ist egal), gibst du ebenfalls Feld_3 an. Somit ist die Verbindung hergestellt.
Grüße,
Knowen

**Comment by Stephan-S** [comment]
Danke Knowen :-)
