### ISSUE TITLE
"Abladen ab Level" wird ignoriert

### ISSUE THREAD

**Issue by Knowen** [Stephan-S/FS19_AutoDrive#502]
Hallo,

im Modus "Drescher abfahren" wird anscheinend die Einstellung von "Abladen ab Level" ignoriert. Ich habe dort 80% stehen und der Abfahrer fährt erst bei 100% los Richtung Abladeort. 

In der Log wird kein einzieger Fehler eingetragen.

Grüße,
Knowen

**Comment by geo-luchs** [comment]
habe das gleiche Verhalten:
Abladen ab Level: 90%
Er hat jetzt 97% und wartet auf Drescher, anstatt abzufahren

**Comment by Stephan-S** [comment]
Servus,
besteht der Fehler aktuell immer noch? Danke fürs Feedback. Ich werde es auch versuchen heute noch mit zu testen.
