### ISSUE TITLE
Abfahrer starten nicht  mehr

### ISSUE THREAD

**Issue by Alkoholix** [Stephan-S/FS19_AutoDrive#503]
Hallo, mit der neuesten selbst gezippten Version fahren bei mir die Abfahrer nicht mehr von selbst ab wenn der Anhänger voll ist. Abtanken funktioniert, der Abfahrer setzt ein Stück zurück und wartet bis die Erntemaschine (hier Rübenroder) sich entfernt hat. Der Zielpunkt wird grün, jedoch fährt der Abfahrer nicht selbständig los. Mit Autodrive beenden und neu starten fährt der Abfahrer dann normal durch bis zum nächsten abtanken.

**Comment by eddiem54** [comment]
Hi,
Same issue here, with combine. "Unload target" turns green and I select continue, tractor returns to field target at 15kph and carries on to tip. If tractor is too far from field target, "Unload target" stays white and it tries to go direct to road route at 8kph and usually crashes.

**Comment by worker2419** [comment]
kann das für die Kombination (Rübenroder / Abfahrer mit Joskin Anhänger) bestätigen. In Kombination Drescher / Abfahrer hat AD folgende Sachen gemacht:
Erster Durchgang Abtanken, Füll-Lever missachtet und direkt zum Silo gefahren, danach Verhalten wie bekannt. Abtanken, warten, Abtanken, warten, Silo abladen
