### ISSUE TITLE
help on new HUD

### ISSUE THREAD

**Issue by ploughedfieldman123** [Stephan-S/FS19_AutoDrive#504]
I have not played fs2019 for a while and also I see this AutoDrive has been updated a lot, But I dont know what the loops are or this P parking is about, can someone do a short English video tutorial it would be most appreciated. or help me on it

**Comment by OnkelH0tte** [comment]
there are a lot of tutorials by "cairo amun" on YT in german. He speaks  slow and very clearly, perhaps the subtitle can translate it good enough.

on the other hand we say in germany "pictures can tell more than 1000 words" ;)

**Comment by ploughedfieldman123** [comment]
> there are a lot of tutorials by "cairo amun" on YT in german. He speaks slow and very clearly, perhaps the subtitle can translate it good enough.
> 
> on the other hand we say in germany "pictures can tell more than 1000 words" ;)

Hi thanks for the help,  yes its all in German, maybe someone can do English ones

**Comment by Stephan-S** [comment]
see the wiki :-)
