### ISSUE TITLE
Berechnen bei großen Maps

### ISSUE THREAD

**Issue by thfeu58** [Stephan-S/FS19_AutoDrive#505]
Hallo Stephan, zunächst einmal mein Danke an Deine großartige Mod.
Ich nutze diese seit etwas über einer Woche in Zusammenarbeit mit Courseplay. Nach einigen Übungsstunden, habe ich nun für meine 16 fach Map ein Streckennetz erstellt, das schon recht weit gediehen, jedoch noch nicht final ist. 
Das Berechnen dauert jetzt aber schon einige Zeit. 
Frage, siehst Du eine Möglichkeit bei besonders vielen Knoten, das Berechnen zu beschleunigen?
Du brauchst ja auch mal ne Pause, hab dir einen Kaffee spendiert.

**Comment by Stephan-S** [comment]
Hey,
erstmal Danke für den Kaffee :-)
Das Berechnen ist schon sehr stark optimiert. Da bekomme ich nichts mehr rausgeholt.
Was du allerdings ausprobieren kannst, ist als erstes Mal in den AutoDrive Einstellungen die Berechnungsgeschwindigkeit hochschrauben. Dann laggt das Spiel zwar während der Berechnung, aber es geht natürlich wesentlich schneller.

Wenn das alles nichts hilft, gibt es als einzige Alternative noch die Möglichkeit, ein paar der Ziele zu entfernen, die du aktuell nicht brauchst. Löschen der Ziele funktioniert mit Mittlerer/Rechter Maustaste auf den 'Lösche Knoten' Button im HUD. Damit löschst du dann nur das Ziel, aber der Wegpunkt bleibt bestehen.

Wenn du 10.000 Wegpunkte hast und 100 Ziele brauchst du grob gesagt 10.000 * 100 Zeit.
Das heißt weniger Ziele können die Zeit deutlich beeinflussen. Ein paar Wegpunkte mehr oder weniger machen nicht allzuviel aus.

Ich hoffe das kann dir etwas helfen :-)

Beste Grüße,
Stephan
