### ISSUE TITLE
Änderung bei Durchlaufzähler möglich?

### ISSUE THREAD

**Issue by haamic** [Stephan-S/FS19_AutoDrive#506]
Hallo Stephan,
Das mit dem Durchlaufzähler ist eine schöne Sache, damit nicht endlos z.b. eine Verkaufsschleife abgefahren wird. 
Ich weiss nicht ob das schon immer so ist, oder evtl. nur ein Fehler in der aktuellen Version.
Es ist leider so, das wenn man z.b. ein Ende nach "X" Durchläufen einstellt, das Fahrzeug dann aber am Ziel stehen bleibt. Ich weiss nicht, wie das andere sehen, aber ich fände es sinnvoller, das das Fahrzeug zum Startpunkt zurück fährt, wo der Durchlauf begann und dann die Fahrt beendet. Es fährt ja eigentlich eine komplette Runde, (von A nach B zurück zu A). 
Ein Pizzafahrer fährt ja auch eine Runde von der Pizzeria zum Kunden und zurück zur Pizzeria und bleibt nicht zum Ende seiner Runde beim Kunden. ;-) .... Spass
Wäre es möglich, das umzusetzen? Evtl. ja als Einstellung im Menü, "nach Durchlauf-Ende zurück zum Start" (Ja/Nein)
Schönes Wochenende
Gruss Micha

**Comment by kleba78** [comment]
Hey,

gedacht habe ich mir das auch schonmal - in meiner Welt wäre es auch cool, wenn man ihn auf seine ParkPosition zurückschicken könnte.

Ich glaube hier gibt es aber kein falsch oder richtig - einige wird es sicherlich auch nicht schmecken, wenn der "Pizzafahrer" die ganze Zeit am Start rumlungert. :-)
Ich würde mir auch eine Option wünschen ( Start - Ziel - Parken )

PS: immer wieder erstaunlich was dieser MOD das Spiel beeinflusst.

Gruß Sven

**Comment by haamic** [comment]
Mir ging es ja nicht ums parken, sondern dass er wirklich seine Runde beendet da wo er angefangen hat

**Comment by Stephan-S** [comment]
Im nächsten Release wird er zum Start zurückfahren. Falls dort noch etwas im Silo ist, wird er es aber aufladen und dann dort warten

**Comment by haamic** [comment]
Trotzdem die Durchläufe beendet sind? 
Okay, damit kann man leben, ist wahrscheinlich nicht anders machbar. 
Da lädt man eben das überflüssige wieder ab. Danke Stephan 
Noch eine Frage dazu, muss das Ende/der Start punktgenau getroffen werden, um zu beenden oder könnte das Fahrzeug evtl 1-2 Wegpunkte bzw. eine Fahrzeuglänge vorher stoppen ohne nochmal auf den Trigger zu kommen?
Nur so eine Idee, man kann nicht immer alles haben. Danke für deine tolle Arbeit, es jedem recht machen zu wollen. 
Gruß Micha
