### ISSUE TITLE
Not avoiding fruit when "Drive to Unload"

### ISSUE THREAD

**Issue by eddiem54** [Stephan-S/FS19_AutoDrive#507]
Hi Stephan,
As the subject says, when driving to combine, tractor follows a route to avoid fruit but when driving to unload drives a perfect straight line to closest point on the unload route, crashing into anything in the way.
Eddie.

**Comment by Stephan-S** [comment]
Hey,
this is his fallback behaviour.
He tries to calculate a fruit free path and if he fails to do so in a reasonable time, he takes a path through the fruit

**Comment by eddiem54** [comment]
Hi,
I understand about fallback but this seems more of an issue. When "Driving to combine" tractor will drive full length of field to avoid fruit as expected. When "Driving to unload" after selecting "Continue" #503  it drives in a straight line every time. no mention of fallback in console.
![fsScreen_2019_09_20_19_41_37](https://user-images.githubusercontent.com/2765885/65352389-73004480-dbe2-11e9-89dc-b18f4e3810c8.png)
![fsScreen_2019_09_20_19_42_04](https://user-images.githubusercontent.com/2765885/65352409-7f849d00-dbe2-11e9-8956-a3c083e10a08.png)
![fsScreen_2019_09_20_19_42_15](https://user-images.githubusercontent.com/2765885/65352436-92976d00-dbe2-11e9-9286-5c6c76478fcb.png).

**Comment by eddiem54** [comment]
Hi Stephan,
Much better now and #503.
Thanks again
