### ISSUE TITLE
Diesel auf der NF Marsch befüllt nicht und lädt nicht ab automatisch

### ISSUE THREAD

**Issue by geo-luchs** [Stephan-S/FS19_AutoDrive#508]
Hallo Stephan

ich spiele auf der NF Marsch 2.4 von FedAction. Die kennst Du vermutlich auch.
Er hat dort zum einen Tankstellen verbaut, zum anderen hat er eine platzierbare Hoftanke ,und eine Dieselproduktion.

AD fukntioniert mit seinen GC kompatibel Produktionsstätten soweit gut.
Seit GC 1.1.0.0 ist dort auch der Fix drin.
Nur Diesel lädt nicht automatisch und lädt dann auch nicht ab (nachdem ich es manuell befüllt habe).
Der Lastzug fährt bis zum Ladetrigger / Abladetrigger, bleibt stehen, dann passiert nichts mehr.
Schalte ich AD ab, kann ich sofort mit R befüllen / I abladen , er steht also wirklich innerhalb des TRiggers.

Ich weiß nicht weiter.

Was kann ich tun, um dir irgendwie mehr nützliche Infos zu beschaffen?
Logfile? da steht so erst mal nichts drin, muss ich irgendein Debugmode einschalten?

Gruß
Carsten

**Comment by Stephan-S** [comment]
Hey,
zuerst einmal währe interessant welche AD Version du aktuell nutzt.
Die aktuelle 1.0.5.7? Eine selbst gezippte aus den Aktuellen Dateien? Oder noch eine ältere Version?
Das Problem mit Diesel beladen hatte ich in einer der aktuellen Versionen eigentlich behoben.

Wenn das Problem weiterhin besteht, trotz aktueller Version, dann wäre eine Logfile trotzdem nützlich und wenn da eh nichts drin steht, gerne auch ein fertiges Savegame, bei dem du alles so eingestellt hast und ich nur noch auf Start drücken muss um alles nachzustellen.
Vielleicht liegt es ja auch an einem Fahrzeug/Anhänger/Trigger den ich nicht korrekt abfrage :-)

Beste Grüße,
Stephan

**Comment by geo-luchs** [comment]
Hi

ich hatte eine gezippte Version zwischen 1.0.5.7 um dem aktuell verfügbaren. (vom 18.9., glaube ich)
Habe jetzt das neueste Zip File genommen.
Auf einem Testspielstand funktionierte es dann.
Im richtigen Spielstand musste ich den Haltepunkt nochmal ändern, obwohl der Trigger scheinbar erkannt wurde (die Tankklappen gingen auf, und ohne AD konnte ich auch laden)

Aber jetzt scheint es zu gehen.

Tausend Dank, dass du immer so schnell reagierst.
Dafür habe ich Dir erst mal 3 Kaffee spendiert. ;-)

Gruß
Carsten
