### ISSUE TITLE
Ordner Problem

### ISSUE THREAD

**Issue by Bandesss** [Stephan-S/FS19_AutoDrive#509]
Hallo Stehan habe das Problem, wenn ich bei einstellungen Ordner auf JA habe, geht mein AD Fenster weg.... auch mit Tastenkombi kommt es nicht wieder.
Erst wenn ich Ordner bei den einstellungen wieder auf nein mach, kommt das AD Fenster wieder.
Hoffe DU kannst mir helfen.

Gruss Bandes

[log.txt](https://github.com/Stephan-S/FS19_AutoDrive/files/3637705/log.txt)

Also diese Config ist im Editor gespeichert,
[AutoDrive_Multimap_2019_config Ohne Editor.zip](https://github.com/Stephan-S/FS19_AutoDrive/files/3638369/AutoDrive_Multimap_2019_config.Ohne.Editor.zip)
Diese ist im Editor bearbeite, aber da gehen die Ordner nicht.
 am am anfang hat sie 15 MB nach dem Editor bearbeiten hat sie 2 MB
Diese ist ist bearbeitet, aber da gehen die Ordner nicht
[AutoDrive_Multimap_2019_confi_mitEDITORg.zip](https://github.com/Stephan-S/FS19_AutoDrive/files/3638371/AutoDrive_Multimap_2019_confi_mitEDITORg.zip)
Getest im SP gehts mit den Ordner im MP nicht.
Bild vom MP
![20190920221329_1](https://user-images.githubusercontent.com/50829319/65369124-b93cbe80-dc49-11e9-8f13-b9104b860fca.jpg)

**Comment by Bandesss** [comment]
Neue Log

**Comment by Bandesss** [comment]
anbei die neue Log
[log.txt](https://github.com/Stephan-S/FS19_AutoDrive/files/3637704/log.txt)

**Comment by Stephan-S** [comment]
Hallo Bandess?
Das Problem besteht also nur im MP? Auf einem dedizierten Server?

**Comment by Bandesss** [comment]
Ja genau nur MP

**Comment by Bandesss** [comment]
Ist es egal ob ich die

**Comment by Stephan-S** [comment]
Ja die Datei ist egal. Du musst mit der aus dem Editor nur nochmal die Kurse neuberechnen lassen.

Ich hab mir mal angesehen was ich machen muss um das Ganze für den MP auch zu ermöglichen und das ist ne ganze Menge :(
Ich habe einen kleinen Fix eingebaut den ich später hochlade. Damit sollte eine bereits mit Ordnern erstellt config auf dem Server korrekt funktionieren.
Aber das Bearbeiten von Ordnern, also erstellen/löschen und verschieben funktioniert dann erstmal nicht.
Aber ich nehme an, du bearbeitest deine Kurse sowieso im SP oder? Ich müsste leider wieder viel Zeit investieren, damit hier alles synchron gehalten wird zwsichen allen Spielern. Für's Erste ist mir dass zuviel Arbeit, wenn eh jeder nur im SP Kurse bearbeitet.

Ich lad später den kleinen Fix hoch, den könntest du ja dann zumindest mal kurz testen, ob die Ordnerstruktur dann korrekt angezeigt wird :-)

**Comment by Bandesss** [comment]
Passt bearbeite nur im Sp
Danke für deine Hilfe

**Comment by Bandesss** [comment]
Neue Version installiert. Spiel hängt beim Starten
Verbinde bitte warten....
Ohne AD startet es....

**Comment by Stephan-S** [comment]
wenn du mir jetzt noch eine log Datei vom Client und Server schicken könntest, kann ich direkt was machen

**Comment by Stephan-S** [comment]
Hey,
ich kann nicht ganz erkennen woher der Fehler kommt. Kannst du bitte nochmal verifizieren ob es definitiv am AD Update liegt.
Probier es doch nochmal mit der Release 1.0.5.7 Version aus ob es damit noch klappt und dann nochmal mit der aktuellen selbst gezippten Version.
Eigentlich sollten die zwei Zeilen die ich an der Client-Server Kommunikation geändert habe nicht das Problem sein.
Seltsam

**Comment by Bandesss** [comment]
Naja die Ordner gehen immer noch nicht. Also ins Spiel bin ich gekommen.
Aber immer gehen die Ordner noch nicht.

**Comment by Bandesss** [comment]
Egal welche Version, sobal ich Ordner einblenden kommt die Fehlermeldung.
Und das Fenster von AD ist weg.
[log.txt](https://github.com/Stephan-S/FS19_AutoDrive/files/3639091/log.txt)

**Comment by Bandesss** [comment]
Weiterhin fehler im MP
werden Ad erstmal deaktivieren

[log neu 158.txt](https://github.com/Stephan-S/FS19_AutoDrive/files/3639970/log.neu.158.txt)

**Comment by Bandesss** [comment]
Hallo Stephan neuer Fehler.
[logneu.txt](https://github.com/Stephan-S/FS19_AutoDrive/files/3648204/logneu.txt)

**Comment by Bandesss** [comment]
Hallo hier ein neuer LOG
aktuellste Version, Ordner gehen immer noch nicht.
[log.txt](https://github.com/Stephan-S/FS19_AutoDrive/files/3665839/log.txt)

**Comment by Bandesss** [comment]
Also habe nun wieder 
AutoDrive | 1.0.5.1
Da kommen meine Kurse wieder im Mulitplayer... bei der 1,5,8 wurden die Kurse nicht mehr geladen.
Ich hoffe es Hilft dir,? mag den MOD 

Gruss
[log.txt](https://github.com/Stephan-S/FS19_AutoDrive/files/3667748/log.txt)

**Comment by Bandesss** [comment]
Gibts was neues? Zu dem Ordner Problem

**Comment by Stephan-S** [comment]
Also Ordner sollten jetzt um MP korrekt funktionieren. (Aktuelle Source Version, noch nicht Released)
