### ISSUE TITLE
Heu auf Feld einsammeln und Abladen im Hofsilo - komischer Fahrweg

### ISSUE THREAD

**Issue by geo-luchs** [Stephan-S/FS19_AutoDrive#510]
Hallo Stephan

ich habe das ja schon benutzt und es ging, aber jetzt verzweifel ich.

Habe einen Traktor mit Ladewagen, der mit CP Heu auf einem Feld einsammelt.
AD Use ist aktiviert.
Dazu habe ich im AD den Modus "Abladen" eingestellt.
Ziel Hofsilo abladen.

Aber sobald CP an AD übergeben hat, nimmt sich das Gespann irgendeinen Weg, der aber nichts mit dem AD-Netz zu tun hat, er fährt quer über Strassen und Gräben.

Könnte sein, dass das im Logfile dazugehört.
2019-09-21 08:48 Going into fallback mode - no fruit free path found in reasonable time
2019-09-21 08:48 Stop searching - no path found in reasonable time
2019-09-21 08:48 Autodrive encountered a problem during initialization - shutting down

Kann es mit "Fruchtumfahrung = aktiv" zu tun haben?

Die Einstellung gilt ja leider für alle Fahrzeuge zugleich.

Gruß
Carsten

**Comment by Stephan-S** [comment]
Hey, du musst hier den 'Aufnehmen und abladen' Modus nutzen. Du brauchst ja zwei Ziele. Eins zum Abladen und dann das obere wieder um zum Feld zurück zukommen.

Hier sollte ich vielleicht noch eine Überprüfung einführen, die nur von CP übernimmt wenn der korrekte Modus eingestellt ist.

Beste Grüße,
Stephan

**Comment by geo-luchs** [comment]
Hallo Stephan

danke. Das War mein Denkfehler. mit "Abholen und Abliefern" geht es.

Ich war so fokussiert, dass ich ja bereits was im Ladewagen hatte, und mich daran "gestört" hatte, bei dem AD Modus "Abholen und Abliefern" nochmal eine Fruchtsorte auszuwählen.
Aber die Einstellung der Fruchtsorte wird einfach ignoriert, weil er ja bereits was im Ladewagen hat, und aus keinem Multifrucht-Silo was abholen muss.

Ich schau mal, ob ich die verschiedenen Möglichkeiten mit CP&AD zusammenfassen kann. ich such immer wieder , und vielen anderen geht es auch so denke ich.
