### ISSUE TITLE
Frage: Wegpunkt-ID als Ziel der Parkfunktion

### ISSUE THREAD

**Issue by Knowen** [Stephan-S/FS19_AutoDrive#511]
Moin,

ich habe die letzten Tage über die Parkenfunktion nachgedacht. Man muss ja einen Zielpunkt erstellen und dann diesen einem Fahrzeug zuweisen. 
Bei einer großen Karte mit vielen Wegpunkten und auch vielen Zielen kann das dann schon sehr Umfangreich werden im Drop-Down Menü.

Jeder Wegpunkt hat eine ID, kann man diese ID nicht verwenden um den Wegpunkt als Parkziel zuzuweisen? 

Grüße,
Knowen

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by haamic** [comment]
Was erhoffst du dir davon? Es ist doch eigentlich gar nicht aufwändig, ein Parkziel zu erstellen und es dem Fahrzeug mit Rechtsklick zuzuweisen. Dann evtl das Ziel in einen Parken Ordner verschieben. Fertig. Wieviele Fahrzeuge hast du, die geparkt werden sollen? 
Sehe da keinen Unterschied du deiner "ID(ee)", die ja auch zugewiesen werden muss. 
Erklär doch bitte mal genauer. 
Gruß Micha

**Comment by Stephan-S** [comment]
Hey,
verstehe ich das richtig, dass du keine Ziele erstellen möchtest, sondern einfach 'normale' Wegpunkte als Ziele zuweisen möchtest?
Wenn ja, das ist leider so ohne weiteres nicht möglich. Während der Berechnungsphase, werden nur die Wege von allen Wegpunkten zu allen Zielen berechnet und entsprechend abgespeichert. Es ist also nicht möglich einen beliebigen Wegpunkt anzufahren.

Aber wie @haamic schon meint. Eigentlich sollte es doch keine große Unordnung geben, wenn du Ordner benutzt und darin deine Parkziele einsortierst. Dann kannst du 100 Parkziele haben und sie nehmen dir nur genau eine Zeile im Dropdown Menü weg.

Oder habe ich dich hier irgendwie falsch verstanden?

P.S.: Mit IDs wird hier ja natürlich eh schon gearbeitet. Aber mit den Ziel-IDs, nicht mit Wegpunkt-IDs :-)

**Comment by geo-luchs** [comment]
Frage zu der Parkfunktion:
Wie bekommt man die wieder abgeschaltet?
Habe die zugeordnet, aber jetzt hat er als oberes Ziel nur noch den Park-Wegpunkt

**Comment by Knowen** [comment]
Hey,
an die neue Ordnerfunktion hab ich gar nicht gedacht. Stimmt, damit ist das DropDown ja nicht überladen.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
