### ISSUE TITLE
Verständnissfrage Ablade-Trigger oder doch fehlerhaft?

### ISSUE THREAD

**Issue by Caliban2017** [Stephan-S/FS19_AutoDrive#512]
Moin,

ich hab da noch mal ein Anliegen mit dem Auto-Drive, wo ich durch Google keine wirklich eindeutige Lösung für bekomme. Vielleicht ist das aber auch doch einfach fehlerhaft. 

Wie genau wird ein Ablade/Verkaufs-Trigger bei Auto-Drive erkannt? Wie muss dieser genau festgelegt werden? Mein bisheriger Weg war immer mit dem Gespann von Traktor und Hänger über den Trigger zu fahren, als wenn ich selbst abkippen möchte. An dieser Position hab ich ein Marker gesetzt, beispielsweise mit Name "Kornmühle abladen". 

Wenn ich diesen Kurs nun im Abholen und Abliefern benutze, dann klappt das Abholen meist auch soweit aber beim Abliefern gibt es immer wieder schwierigkeiten, entweder steht das Gespann zu weit hinten vom Trigger oder zu weit vorne. Meistens handelt es sich da nur um ein paar Centimeterchen aber es reicht immer aus, das der Abfahrer außerhalb des Verkaufstriggers ist und somit nicht ablädt. 

Daher meine Frage, wie wird das erkannt? Anhand des Markers oder erkennt Autodrive intern den Trigger selbst und steuert diesen an? Denn die erste Methode würde für mich irgendwie keinen Sinn ergeben, da ja jedes Gespann unterschiedlich lang ist, je nach Hänger, je nach Traktor etc etc. Da müsste ich ja für jegliche Kombination von Fahrzeugen einen eigenen Abladekurs einfahren. 

Aber wenn es die zweite Methode ist,  woran liegt das, das der Abfahrer halt teilweise nicht den Abladepunkt präzise anfährt? 

Mir ist ebenfalls letztens aufgefallen, wenn sich eine zu kleine Menge in dem Kipper befindet, z.B. der Rest aus einem Silo den man mit verkaufen möchte, dann wird dieser nicht verkauft. Als Beispiel mal so 3000l. Die kippt er einfach nicht ab, muss man leider immer von Hand machen.

Würde mich über eine Erklärung sehr freuen.

Viele Grüße

**Comment by Stephan-S** [comment]
Servus,

beim Spielstart lädt AutoDrive alle Trigger und speichert diese. Wenn er nun in einem entsprechenden Modus über einen Trigger fährt überprüft er ob er nah genug am Ziel/Startpunkt ist (Radius 25m) und lädt ab bzw. probiert zu beladen.

Er macht das aber nicht vorausschauend. Sprich wenn du dein Ziel mit einem kurzen Gespann einfährst und er damit gerade so abladen kann aber das nächste Mal ein großen Gespann nutzt, kommt er ja nicht am Trigger an. Wenn er dann sein Start/Zielpunkt erreicht hat, kommt es auf den Modus an. Beim reinen Abladen Modus bleibt er stehen. (Er schaut ja nicht vorraus und sieht das er 2 Meter weiter abladen kann). Beim Beladen ist es das gleiche. Er weiß nicht ob er hier automatisch laden sollte oder warten soll beladen zu werden -> wartet am Startpunkt.
Beim 'Aufladen und entladen' bleibt er beim Aufladen am Start stehen und beim Abladen sollte er einfach über sein Ziel hinwegfahren und dabei dann den Trigger erreichen.
Grundsätzlich ist es also sinnvoll die Zielpunkte ein gutes Stück hinter den eigentlichen Trigger zu setzen, so dass dein größtes Gespann abladen/aufnehmen kann. Die kleineren Gespanne erkennen den Trigger und bleiben automatisch stehen.

Beste Grüße,
Stephan

**Comment by Caliban2017** [comment]
Super, danke dir :) Nun hab ich das verstanden und eben einmal getestet und den Abladezielpunkt einfach weiter nach vorne gesetzt und ein kurzes Gespann hat den Trigger auf Anhieb gefunden und dort dann abgeladen...
