### ISSUE TITLE
Rückwärts-Fahr-Funktion

### ISSUE THREAD

**Issue by Fuzzy86** [Stephan-S/FS19_AutoDrive#514]
Hy! Wollte nur mal Interessehalber nachfragen ob es geplant ist ist rückwärts fahr funktion zu machen? Z.b fürs einparken in Fahrzeughallen.

Lg

**Comment by Stephan-S** [comment]
Hey,
das habe ich schon in mehreren Issues beantwortet. Bitte mit etwas Eigeninitiative selber informieren :-)
Danke.

**Comment by Stephan-S** [comment]
Beispiel: https://github.com/Stephan-S/FS19_AutoDrive/issues/340
