### ISSUE TITLE
Frage: Abfahrer erst, wenn Drescher bei 100%

### ISSUE THREAD

**Issue by Iwan1803** [Stephan-S/FS19_AutoDrive#517]
Hallo und erstmal super Projekt!
Ich nutze es als Ergänzung zu CP und das ist einfach genial, wenn man nicht hunderte Kurse einfahren muss.

Nun aber meine Frage...
Meinen Drescher lasse ich per CP ein Feld abernten und der Ablader wird von AD gesteuert, was soweit auch gut funktioniert.
Ich vermute, du nutzt den Trigger "XX muss entladen werden", damit der Ablader dann losfährt oder warum werden die Ablader erst gerufen, wenn der Drescher wegen vollem Tank stehen geblieben ist? Gibt es hier keinen andere Möglichkeit, den Füllstand abzufragen, damit der Abfahrer sich früher auf den Weg macht?
Ob es von CP oder AD kommt, weiß ich nicht, aber ab 80% macht der Drescher seine RUL an. Vielleicht kann man darauf einen Trigger setzen

**Comment by Woife1** [comment]
Hi 
AD nutzt einen statischen Abtankpunkt. Du kannst auch wenn du selber den Drescher fährst einen AD-Abbfahrer rufen in dem du das Rohr ausfährst, was auch der Trigger zum Abfahren ist.
Wenn du noch fährst oder nochmal nen Stück Fährst bleibt der Abfahrer an der Stelle stehen an der das Rohr ausgeklappt war.

Die RUL macht Courseplay bzw der Helfer an um dir zu zeigen das er bald voll ist.

**Comment by Stephan-S** [comment]
Hab gerade ein Update rausgebracht, bei dem es möglich ist einzustellen ab wann der Abfahrer losfährt und ob er dem Drescher folgen soll.
Das Abtanken selber findet allerdings noch im Stillstand statt

**Comment by Woife1** [comment]
Demnächst mal schauen ob das funktioniert was du da gebastelt hast ;)

Sehr gute arbeit bisher mach weiter so 👍

**Comment by Iwan1803** [comment]
Das klingt doch super. So kann man den Abfahrer eher losfahren lassen und verringert den Stillstand, was besonders bei großen Feldern eine Erleichterung sein wird.
Der Download läuft gerade, Feedback kommt.

**Comment by worker2419** [comment]
Von meiner Seite auch noch mal Danke für deine Arbeit. Interessante Funktion, macht bei mir noch nicht was es soll. Parameter sind auf Ja, 85%, Ja. Erst einmal fuhr AD auf dem falschem Feld im Kreis, obwohl im Abfahrer und im Drescher das Feld eingegeben sind. Nachdem ich früher abfahren auf Nein gesetzt habe bzw. in einem zweitem Test den zu 90% gefüllten Terra DOS vom Feld genommen habe blieb das Kreise fahren aus. Ungeachtet ist AD bei 85% in Richtung richtiges Feld gefahren. Nach erneutem Starten passierte folgendes: AD fuhr bei 85% los und fuhr Richtung Drescher, am Drescher öffnete und schloss sich kurz das Abtank-Rohr, bei 100% blieb der Drescher stehen, wieder Ablade-Rohr raus, rein. AD stand und fuhr nicht weiter.

**Comment by Iwan1803** [comment]
Also gestern war es etwas "hakelig". Greift eine gesetzte Option eigentlich sofort oder müsste ich z.Bsp. einen Ablader stoppen und neu starten, damit es klappt?
Das Abfahren bei 85% hat meistens geklappt, aber ab und zu blieb entweder der Drescher oder der Ablader stehen, ohne das noch was passiert ist.

**Comment by Stephan-S** [comment]
Ich mache hier mal zu und erstelle ein Sammel-Issue für alle Probleme mit dem aktuellen Drescher verfolgen
