### ISSUE TITLE
Drescher abfahren funktioniert nicht mehr. Abfahrer und Drescher bleiben nebeneinander stehen

### ISSUE THREAD

**Issue by geo-luchs** [Stephan-S/FS19_AutoDrive#518]
Hallo Stephan

ich habe am 21.9. um ca. 19:20 das Zip File heruntergeladen. (also 1.0.5.7.x)
Nun funktioniert das "Drescher abfahren" nicht mehr.
Der Abfahrer fährt zum Drescher, tankt ihn ab, und dann bleiben beide stehen.
Drescher ist leer.
Wenn ich AD ausschalte, fährt der Drescher weiter.

Ich habe das Savegame bei Drescher 94% gesichert.
Und habe dann an der exakt gleichen Stelle das Gleiche nochmal mit AD 1.0.5.6 Release gemacht.
Da geht es. Der Abfahrer setzt zurück, der Drescher fährt weiter.

Sorry, ist jetzt 1:30, sonst hätte ich noch andere AD Versionen getestet,

Hoffe , Du hast ne Idee, woran es liegen könnte.

Gute Nacht

**Comment by geo-luchs** [comment]
so, hab jetzt noch die Released Version 1.0.5.7 getestet.
Die geht noch.

**Comment by Stephan-S** [comment]
Hey,
könntest du mir mal schnell ein Savegame schicken?
Ich habe gestern ja ein paar Änderungen eingespielt die bei mir problemlos funktioniert haben.
Vielen Dank!

Beste Grüße,
Stephan

**Comment by geo-luchs** [comment]
Hi Stephan

 

Wie lase ich dir das Savegame am besten zukommen?

 

Gruß

Carsten

 

Von: Stephan Schlosser <notifications@github.com> 
Gesendet: Sonntag, 22. September 2019 08:24
An: Stephan-S/FS19_AutoDrive <FS19_AutoDrive@noreply.github.com>
Cc: geo-luchs <geo-luchs@e.mail.de>; Author <author@noreply.github.com>
Betreff: Re: [Stephan-S/FS19_AutoDrive] Drescher abfahren funktioniert nicht mehr. Abfahrer und Drescher bleiben nebeneinander stehen (#518)

 

Hey,
könntest du mir mal schnell ein Savegame schicken?
Ich habe gestern ja ein paar Änderungen eingespielt die bei mir problemlos funktioniert haben.
Vielen Dank!

Beste Grüße,
Stephan

**Comment by Stephan-S** [comment]
Am Besten als .zip Datei einfach hier hochladen.
Du kannst Dateien einfach hier in das Eingabefenster schieben

**Comment by geo-luchs** [comment]
[savegame12.zip](https://github.com/Stephan-S/FS19_AutoDrive/files/3639439/savegame12.zip)

Problem ist auf Feld 9.
Standarddrescher + Standard-Traktor+Standard-Anhänger.
Solltest Du also keine Probleme haben, wenn Dir Mods fehlen ;-)

Drescher ist bei 96%, Abfahrer sollte also bald kommen


Ich bin jetzt leider dann erst mal weg, am späten Nachmittag wieder da. Hoffe , das Savegame reicht so

**Comment by geo-luchs** [comment]
Hi Stephan

kann es sein, das Du da was durcheinander gebracht hast?
Der Issue hier hat ja nichts mit meiner Frage nach dem Diesel abholen zu tun,, und somit vermutlich auch nicht mit dem referenzierten Bugfix.

Ich teste gleich mal 1.0.5.8, damit das Drescher abfahren bei mir funzt.

**Comment by Stephan-S** [comment]
Doch doch. Der Drescher wurde nicht als leer erkannt, da der Dieseltank mit einberechnet wurde.
Alles ne komplexe Geschichte :D 
Und Drescher nicht leer -> Abtanken nicht beendet

**Comment by geo-luchs** [comment]
Ohjee
Ich zieh echt den Hut vor Dir.
Habs gerade getestet, und ja, es funzt wieder mit 1.0.5.8.

Hab mal beim Release 1.0.5.8 reingeschaut, was so alles an Code verändert wurde.
Grundsätzlich sind mir Programmiersprachen nicht fremd, aber das hier, ich hab echt Respekt, was Du hier an Arbeit reingesteckt hast.

Du kannst den Issue hiermit schließen.

**Comment by Stephan-S** [comment]
Schön zu hören :-)

Ja, das ist ein Fass ohne Boden und jeder schreit immer nach neuen Features und Verbesserungsvorschlägen :D

**Comment by geo-luchs** [comment]
getestet erfolgreich mit 1.0.5.8- kann geschlossen werden
