### ISSUE TITLE
1.0.5.7 Abholen und Abliefern - Abfahrer hält nicht

### ISSUE THREAD

**Issue by MADxHAWK** [Stephan-S/FS19_AutoDrive#519]
Ich habe einen Kusrspunkt neben einem Bunkersilo, an dem ein Abfahrer von einem Radlader beladen werden soll. 
Der Abfahrer fährt den Kurspunkt an, bremst kurz ab und fährt anschließend weiter zum abladepunkt ohne auf die beladung zu warten. 
Da ich bisher keinerlei Infos gefunden habe, wie ich autodrive mit einem Radlader benutze, läuft der Radlader über CP. 
Selbst wenn der Radlader mit beladener Schaufel in Warteposition auf den Abfahrer steht, fährt dieser einfach weiter. 

Die Option "Wenn Silo Leer" ist auf "Warten" gesetzt.

**Comment by OnkelH0tte** [comment]
falls dein problem noch nicht gelöst ist.....
du musst bei AD den Befehl "Drescher abtanken" einstellen, damit es geht.

**Comment by MADxHAWK** [comment]
Oh, ok danke werde ich versuchen :)

**Comment by Stephan-S** [comment]
Sollte inzwischen auch wieder im normalen Abholen / Abliefern Modus laufen. Da war ein Bug drin.
