### ISSUE TITLE
1.0.5.7 Abfahrer fährt ncht entladen

### ISSUE THREAD

**Issue by hathor1411** [Stephan-S/FS19_AutoDrive#520]
Erstmal dickes Lob an Stephan. 

Heute ist mir aufgefallen, das im Drescher abtanken Modus, der abfahrer nicht zum entladen fährt. Er steht mit vollem Anhänger auf dem Feld. Der Entladeort ist grün eingefärbt, aber er fährt nicht los.

MfG

**Comment by worker2419** [comment]
Hallo @hathor1411,
ich habe gerade versucht deinen Fehler nachzustellen, ohne Erfolg. Welche Version benutzt Du? Ich verwende die Version, welche man selber in ein ZIP Archiv überführen muss, damit hab ich keine Probleme feststellen können. Gerade ist auch 1.0.5.8 erschienen.
@Stephan-S damit ist der Fehler aus #503 behoben, wei es aussieht, zumindest tritt er bei mir nicht auf. Abgefahren wurden Weizen mit MOD-Trecker und MOD Anhänger sowie Zuckerrüben.

**Comment by hathor1411** [comment]
Ich hatte die 1.0.5.7 mit den Updates von anfang voriger Woche drin.
Es wurden nur Standartfahrezeuge genommen. Hatte es auf verschiedenen Feldern versucht, er wollte einfach nicht weiter fahren. Ich probiere es jetzt nochmal mit der 1.0.5.8
Mal schauen.

**Comment by Mike1977** [comment]
Habe das selbe Problem, allerdings nur Sporadisch und nicht reproduzierbar. Also manchmal geht es und manchmal geht es nicht. Ich weis das das absolut nicht nützlich ist, aber ich habe keine Ahnung wo ich da ansetzen soll. Es sind Standartfahrzeuge mit Standartanhängern betroffen und auch mit Modanhängern. Meistens geht es dann nach einem Neustart wieder für eine Weile. Die Console zeigt da keine Fehler an.

**Comment by Stephan-S** [comment]
@Mike1977 Hast du dir schon die aktuellste Version 1.0.5.8 geladen?

**Comment by Mike1977** [comment]
Habe ich gerade und bin am testen. Bisher ist das noch nicht aufgetreten, aber ich kann auch nicht so lange zocken wie am Sonntag, wo ich das Spiel einige Stunden lief.

**Comment by Knowen** [comment]
Hallo,
habe die aktuellse Version(1.0.5.8) und er fährt nicht abladen, wenn er 100% voll ist und das Ziel grün ist. Des weiteren wird die Prozentangabe "Abladen ab Level" ignoriert.

In der Log steht nix.

**Comment by Stephan-S** [comment]
Hey, besteht das Problem immer noch? Das konnte ich bisher nicht nachstellen. Danke für die Info
