### ISSUE TITLE
A problem and a question

### ISSUE THREAD

**Issue by Roby1164** [Stephan-S/FS19_AutoDrive#522]
Hi Stephan
The problem is, when a vehicle is told to drive, it always tries to use the closest trajectory as the crow flies, but in some cases, as shown in the attached photos, even if it has the best trajectory and should follow the direction, in particular with two-way paths (the blues), as part, the second point that goes to take is the one behind, and no one ahead, which would be better, in this way often, the medium, trying to reverse the direction of travel , finds himself blocked by any obstacles, or makes many turns in circles, before being able to take the next point. I believe that if possible, you should make sure that the vehicle follows and always takes the trajectory of travel, not calculating any points already exceeded ....

![Screenshot_1](https://user-images.githubusercontent.com/24955554/65408254-0b661700-dde5-11e9-8c6b-890036533cfc.jpg)
![Screenshot_2](https://user-images.githubusercontent.com/24955554/65408259-0c974400-dde5-11e9-80f9-c390b8c28370.jpg)

The question instead is, what do you mean with the new commands entered?

the "preCallDriver_tooltip" and the "preCallLevel_tooltip"

They look like two identical commands, since I don't understand where the difference is, as it always seems to refer to the driver's early call for unloading the Combine Harvester .....
Among other things in the text of the commands in English, the description is identical ...

**Comment by Stephan-S** [comment]
Hey @Roby1164 
I will see what I can do about the two way road starts. Thanks fo opening the issue.

As to the translation. Yeah they are the same, but since the basically refer to the same thing I thought this was alright. Anyways, the tooltips are loaded dynamically by their name. That's why I need both translations in the file :-)

**Comment by Roby1164** [comment]
ok

**Comment by Stephan-S** [comment]
Wont fix this for now. As I don't see an easy way to fix this. If the shortest path points in the opposite direction, there is nothing I can do about it at that time.
