### ISSUE TITLE
Autodrive editor

### ISSUE THREAD

**Issue by aerogamis** [Stephan-S/FS19_AutoDrive#523]
Hallo.
Hab das problem das der editor nur ein streifen von der map anzeigt.
Hat jemand ne Idee?
Danke im voraus

**Comment by Stephan-S** [comment]
Hey,
hast du dir schon die aktuellste Version des Editors geladen?
Hast du mal versucht das Bild groß zu ziehen beziehungsweise mal mit der Maus im Bild herumgezogen. Normalerweise sollte sich dann alles korrekt aktualisieren

**Comment by aerogamis** [comment]
hi.
ja hab alles versucht leider ohne erfolg

**Comment by aerogamis** [comment]
welche is die neueste version?
bei mir steht 0.1

**Comment by gkleinfe** [comment]
I, too, am having the same issue where I only see a strip at the top and zooming/panning doesn't help.  I'm running AD.jar from a batch file and am able to get some debugging info from the open window.  I've included it in the attached zip file.  I'm also including the config xml file and the png file.
 
[AutoDrive Loading Problem.zip](https://github.com/Stephan-S/FS19_AutoDrive/files/3648702/AutoDrive.Loading.Problem.zip)

**Comment by Stephan-S** [comment]
@gkleinfe 
Hey, I think you could solve your problem by recalculating the paths first in the game. This should create the entry 'markerID' which is currently missing in your config.

**Comment by aerogamis** [comment]
Was meinst du mit Pfade neu berechnen? Und was hat das damit zu tun das die Karte nicht richtig dargestellt wird?
Danke im voraus. 
Und sag mir bitte welche die neueste Version von AD ist

**Comment by gkleinfe** [comment]
That was it.  I can't believe I forgot that step.  I've included an image of the button in game that recalculates the path in game.  Of course, don't forget the save the game after you do this to make sure it get's stored in the config.

As a feature request for the editor, maybe have the editor check for the 'markerID' in the config.  If it's not found, have an error that might include the graphic I'm sending explaining to recalculate.

I even knew I was supposed to do that, but still forgot to.  Thanks.

![recalculate](https://user-images.githubusercontent.com/3876224/65539188-ebaf1b80-ded6-11e9-8a4a-362b1d56c88b.png)

**Comment by aerogamis** [comment]
Was meinst du mit Pfade neu berechnen? Und was hat das damit zu tun das die Karte nicht richtig dargestellt wird?
Danke im voraus. 
Und sag mir bitte welche die neueste Version von AD ist

**Comment by Mombl** [comment]
Ich schlage mich auch länger mit dem Editor rum. Ich kriege einfach nicht hin, dass die Kurse ordentlich über der Map liegen. Ich spiele die Multimap2019. Gibt es da "draußen" irgendjemand, der ein Tutorial hat (Youtube wäre geil, ich denke da an "Cairo" :-))?

**Comment by hjnk** [comment]
Ja, gibt es, Ein Lenkrad verwenden, möglichst sehr langsam fahren, besonders in den Kurven, möglichst mit Zugmaschine und Auflieger (Anhänger) die Kurse einfahren, Meine Erfahrung ist mit Zugmaschine und Auflieger, oder Traktor mit Anhänger, so sieht man gleich ob man auch um die Ecken kommt, damit ein Hängenbleiben von vorn heraus ausgeschlossen werden kann.

**Comment by Mombl** [comment]
> Ja, gibt es, Ein Lenkrad verwenden, möglichst sehr langsam fahren, besonders in den Kurven, möglichst mit Zugmaschine und Auflieger (Anhänger) die Kurse einfahren, Meine Erfahrung ist mit Zugmaschine und Auflieger, oder Traktor mit Anhänger, so sieht man gleich ob man auch um die Ecken kommt, damit ein Hängenbleiben von vorn heraus ausgeschlossen werden kann.

Hi,
ich meine nicht das Einfahren an sich. Das mache ich schon mit Lenkrad. Ich meine den AutoDrive Course Editor. Das ist ein eigenständiges Java- Programm, mit dem man eingefahrene Kurse editieren kann (grade wenn man mal etwas eckig gefahren ist).
