### ISSUE TITLE
Idee - CP + AD Crossover

### ISSUE THREAD

**Issue by FritzHugo3** [Stephan-S/FS19_AutoDrive#524]
### **(English Translation are down )**

In German
CoursePlay (CP) und AutoDrive (AD), sind zwei total tolle Mods.

Courseplay hat ganz klar seine Stärke auf dem Feld und AutoDrive auf der Straße. 
Es wäre wundervoll, gäbe es eine Crossmöglichkeit. 

Ich glaube ich habe eine Idee, die einigermaßen einfach umzusetzen sein könnte (so Die Spielengine es ermöglicht, Tastendrucke zu simulieren bzw. Befehle/Werte von einem zum anderen Mod übergeben kann).

Ich stelle mir das so vor, man hat ganz normal seine CP Maschinen auf dem Feld, der LKW (Abfahrer) parkt am Feldrand, fährt dann mit CP los um den Drescher ab zu laden und macht das so lange, bis er eben X-voll ist. Also der ganz normale CP Zustand. Der volle Laderaum lässt den CP Fahrer dann zurück zum Feldrand Fahren und sagt dann (entweder per Tastensimulation oder direkter Wert/Befehlsübergabe) AD bescheid, aktiviere dich (natürlich ist hier die Wegstrecke vorher eingefahren worden und der Feldhaltepunkt ist unmittelbar vor dem CP Feldrandpunkt (Man fährt die Strecken also so ein, das ein direkter Streckenübergang problemlos von dem Pathfinder funktioniert). AutoDrive fährt dann sein gewohntes Streckennetz ab

Zusammenfassung:
CP Abfahrer tankt Drescher ab bis voll, sagt AD es soll aktiviert werden und schalte CP ab), kommt wieder beim Feld an – AD sagt zu CP schalte dich an (die ganzen Einstellungen sind ja noch vorhanden) und schalte AD ab.

Somit hätte man zwei völlig unabhängige Mods, die super zusammenarbeiten würden ohne das man tiefgründig was am eigentlichen Code beider Mods verändern müsste. Es ist quasi, „nur“ ein Switchschalter bei beiden Mods nachzurüsten bei der Aufnahme.

Was dazu vom Spieler notwendig wäre – während der Aufnahme an den Endpunkten einen neuen Button drücken „Übergabe an CP“/ “Übergabe an AD“ (Ein erweiterter Aufnahmestop Button quasi).

(Was für euch notwendig wäre, vermutlich viele Stunden Mehrarbeit, Kopfzerbrechen, Schlafentzug…. *duck*)

Beide Projekte haben ihre absolute Berechtigung und Nutzen, seht die Mods nicht als Konkurenten, beide haben ihre Stärken und nicht so starken Bereiche. 

(Mir ist bewusst, es gibt per Überladewagen einen Workaround, womit es jetzt schon geht, braucht aber ein zusätzliches Fahrzeug, es ist umständlicher, unsauberer, gibt einfach mehr Fehlerquellen und Probleme in der Praxis und nicht alles funktioniert mit einem Überladewagen)

**Ich habe den aller größten Respekt vor euren beiden Projekten und bedanke mich für beide Mods, die den Landwirtschaftssimulator auf eine ganz andere Ebene bringt (Wäre ich Giants, würde ich euch beide Anwerben als freie Mitarbeiter). 
Vielen Dank für die sicherlich vielen hunderten von Stunden Freizeit, die ihr in diese Projekte gesteckt habt. (Und dann kommt da so ein Trottel wie ich daher und möchte mehr grins, Spaß).**

Ich sage vielen Dank für eure Aufmerksamkeit, eure tollen Mods und seht es als kleine Anregung, lasst es euch mal durch den Kopf gehen.

Einen tollen Tag euch beiden 
FritzHugo3

### **In English (sorry ist only a translation software, my english is very bad ;-) ).**

CoursePlay (CP) and AutoDrive (AD) are two great mods.

Courseplay clearly has its strength in the field and AutoDrive on the road.
It would be wonderful if there was a cross option.

I think I have an idea that could be reasonably simple to implement (like the game engine makes it possible to simulate keystrokes or pass commands / values from one mod to another).

I imagine that way, you have your CP machines on the field as usual, the truck (Abfahrer) parks at the edge of the field, then starts with CP to load the Drescher and does that until he just X-full is. So the normal CP condition. The full load space then lets the CP driver drive back to the edge of the field and then tells AD (either by key simulation or direct value / command transfer), activate (of course the distance has been retracted and the field stop point is immediately before the CP field margin point (Man drives the tracks so that a direct route crossing easily from the Pathfinder works.) AutoDrive then departs its usual route network

Summary:
CP Abfahrer refuels Drescher until full, says AD it should be activated and switch off CP), arrives back at the field - AD says to CP switch on (all the settings are still there) and turn off AD.

Thus one would have two completely independent mods, which would work super without the profound what would have to change the actual code of both mods. It is almost, 'only' a switch switch in both mods retrofit when recording.

What would be necessary for the player - during the recording at the end points press a new button 'Transfer to CP' / 'Transfer to AD' (An extended recording button Button quasi).

(Which would be necessary for you, probably many hours extra work, headache, sleep deprivation .... * Duck *)

Both projects have their absolute justification and utility, do not see the mods as competitors, both have their strengths and not so strong areas.

(I am aware that there is a workaround by means of a transfer vehicle, which already works, but it needs an additional vehicle, it is more complicated, more unclean, it simply gives more sources of error and problems in practice and not everything works with a transfer vehicle)

**I have the utmost respect for your two projects and thank you for both mods that take the farming simulator to a whole new level (If I were Giants, I would hire both of you as freelancers).
Thank you for the many hundreds of hours of free time that you have put into these projects. (And then there's such a jerk like me and would like more smile, joke).**

I say thanks for your attention, your great mods and see it as a small suggestion, let it go through your head.

Have a great day both of you
FritzHugo3

**Comment by FritzHugo3** [comment]
(Same Text are here at the other mod)
https://github.com/Courseplay/courseplay/issues/4291

**Comment by Roby1164** [comment]
???? Watch that, the CP and AD, are already collaborating, in the CP, there is the option to activate, to integrate the AD ???

**Comment by haamic** [comment]
@FritzHugo3
Mit welcher Version bist du denn unterwegs?  AD arbeitest schon Länger mit  CP super zusammen und das Drescher abtanken funktioniert genau so wie du es gern hättest.

**Comment by FritzHugo3** [comment]
FS19_AutoDrive_1.0.5.8 (gerade erst geupdated)
CoursePlay_6.01.00288 

Danke für den Hinweis haamic, ich habe mir den Mod erst vor ca. zwei Wochen gezogen, scheinbar wird die Wuelle nicht aktuell gehalten ^^. Ich versuchs jetzt mal mit der 
Courseplay for FS19 v6.01.00300

Sollte das dann meinen Wunsch/Idee bereits erfüllen, bitte ich um entschuldigung (ist mein Versäumnis die Version noch mals neu zu prüfen, es gibt einfach zu viele Quellen mit unterschiedlichsten Versionen, wenn man nicht direkt nach der Entwicklerversion von hier ausschau hällt). Ich würde das dann entweder ergänzen oder schließen, je nachdem, was der Versuch dann erbracht hat.

**Comment by FritzHugo3** [comment]
@haamic Habs gerade angeschaut, also ich sehe da beim Aufnehmen nicht wirklich einen neuen Button für die Übergabe. Gibts da irgendwo ein Tutorial zu der neuen Funktion?

**Comment by worker2419** [comment]
Hallo @FritzHugo3 youtube hat einige sehr schöne Tutorials zu bieten, was AD und dessen Nutzung angeht, auch mit CP
![AD_CP](https://user-images.githubusercontent.com/47278102/65544708-1a97b280-df14-11e9-9b52-96966ce49b7a.png)
. Die Verbindung zu CP findest Du hier

**Comment by FritzHugo3** [comment]
Ja ok, wenn ich das richtig verstehe fährt dann aber Der Abfahrer per AD zum Drescher und das ist eben genau das, was ich eigentlich nicht haben wollte (meine Idee war eben, das man die ganzen Einstellmöglichkeiten von CP nutzen kann, damit den Drescher abtankt und erst ab Feldrand AD übernimmt) aber ich versuche es so. 

Ich habe ne ganze Menge Turtorials gesehen, stundenlang aber was in der einen Version so geht, funktioniert in der anderen Version schon wieder anders. 
Danke worker2419

**Comment by worker2419** [comment]
Das mit dem Drescher und AD geht leider so nicht. Unter den geschlossen Problemen gibt es eine Lösung mit Überladewagen die den Drescher abtanken zum Feldrand fahren und dann an AD übergeben. Hab ich aber nie ausprobiert.

**Comment by Woife1** [comment]
Ich hatte sowas schonmal ausprobiert gab aber nur nen Absturz.
der Mode2 von CP ist immer noch WIP und für die Häcksler wäre so eine Übergabe toll.

**Comment by FritzHugo3** [comment]
So ist es Worker und Woife, das verursacht bei mir auch noch einen Spielabsturz.

Also nur das da kein Missverständnis auftritt. Ich finde beide Mods klasse, ich sehe halt die Stärken von AD nicht auf den Feld und möchte da keinen Fahrer drauf haben (CP hat hier ganz klare Einstell und andere Vorzüge auch dem Acker). 
Das heißt nicht, das ich da jetzt das eine schlecht finde oder schlecht reden möchte. beide haben starke Stärken in ihren Breichen. Es sind beides grandios tolle mods

Aus dem Grund würde ich meinen Vorschlag weiterhin als gültig sehen. Als Anregung an den Modder (so er denn die Lust hat, meinen langen Text in Post 1 zu lesen).

Danke euch aber allen für die freundliche Hilfe und Antwort.

**Comment by Fuzzy86** [comment]
Hey! Schau dir die Videos von Cairo auf Youtube an. Der macht so Tutorials.

https://www.youtube.com/channel/UCqQhmo7yyaKDsXQDLgNV39A

**Comment by FritzHugo3** [comment]
Danke Fuzzy86, kenne ich schon, ist nicht so der Hit als Tutorial, als Lets Play ok aber na ja. 
Er macht quasi learning by doing ;-). Mit einem geplanten und knakigen Tutorial hat das wenig zu tun. (Zumindest ist so meine private Auffassung und ich schaue zu allen möglichen sehr oft Tutorials für viele Spiele, für RL. Sachen, habe auch schon eigene gemacht vor langer Zeit). Hab jetzt nur in zwei Folgen rein geschaut aber ich vermute mal, die sind ähnlich aufgebaut. 

Wie ich es mir wünschen würde, gibt es das schlicht noch nicht in den beiden Mods, da würden auch keine besseren Tutorials nutzen. AD hat nunmal lange nicht die Möglichkeiten auf dem Feld zum Abtanken, wie das der CP Fahrer hat. (Alleine das AD erst bei 100% los fahren und man es nicht einstellen kann, wie bei CP. - CP gehört auf die Straße, nicht aufs Feld aus meienr Sicht)

Da der zweite Modus bei CP noch sehr buggy ist und er das ganze Spiel abstürzen lässt, wenn kein Abladetrigger mit im Kurs ist. werde ich morgen mal Silos setzen. 
Also Silo neben allen Felder setzen (kostz halt bissle was grins) ein CP LKW Tankt die Drescher ab und ladet das ins Feldsilo ab. Der AD Fahrer fährt das Silo an, Tankt dort ab und verkauft es. 
(Automatische Übergabe vom CP Übergabewagen zu einem am Feldrand geparkten AD LPW funktioniert einfach nicht - Ergebnis ist immer ein kaputtes Game.

**Comment by worker2419** [comment]
nicht falsch verstehen, aber für mich ist die Kombination aus CP und AD eine Super Kombi. Bei uns in der Gegend kenne ich es nur so, dass die Abfahrer zum Drescher fahren und abtanken. Danach geht es zum Silo und wieder zurück

(Alleine das AD erst bei 100% los fahren und man es nicht einstellen kann, wie bei CP.  Stimmt nicht, ist in 1.0.5.8 neu dazu gekommen, Ansonsten, es ist immer noch ein Spiel :-)

Ich denke, Stephan liest wie immer mit und wir machen hier zu.

**Comment by FritzHugo3** [comment]
@Worker "(Alleine das AD erst bei 100% los fahren und man es nicht einstellen kann, wie bei CP. Stimmt nicht, ist in 1.0.5.8 neu dazu gekommen."
Hab ich dann nicht gefunden, hatte den Ad LKW voll bis 98 und er blieb stehen grins. 
Wegen 2%, dann steht man da und würde ihn halt gerne Abfahren sehen automatisch grins. 
Aber selbst wenn das zukünftig funktioniert hat CP halt noch mehr Möglichkeiten beim Drescher. (größerer/kleinerer Abstand in beiden Achsen, mehrere Drescher oder exclusive Drescher, im Verband und so weiter, du kennst die Möglichkeiten sicherlich selber). 


Na wie dem auch sei, ich habe meinen Vorschlag im ersten Post beschrieben. Aus meienr Sicht gibt es das in der Form eben noch nicht und hätte ganz klare Vorteile, von daher kann ich hier auch zu machen, wenn das dein Wunsch ist ;-).

**Comment by Tensuko** [comment]
Wie ich bereits bei CP schrieb, die Funktion ist schon lange da, nur eben der CP Mode2 driver noch nicht bereit. Ein Workarround habe ich dir erklärt, damit du keine CP Kurs einfahren musst, sondern das AD netzwerk nutzen kannst um einen CP kurs zu laden. Einfach mal ein wenig abwarten, Mode2 ist auf dem weg...

**Comment by Stephan-S** [comment]
@FritzHugo3 
Was macht AutoDrive dir denn für Probleme auf dem Feld? Das Abtanken dauert zwar etwas länger, da es noch nicht während der Fahrt passiert, aber ansonsten sollte er das Ganze eigentlich sehr zuverlässig schaffen.

Hier mal ein kleines Demonstrationsvideo vom Pfadfindealgorithmus in AutoDrive :D 
https://youtu.be/zdZBToD0bBE?t=1533

Was verlangst du denn noch? :D 

Ne, aber ohne Spaß, die meisten der von dir gewünschten Einstellmöglichkeiten sind doch in AutoDrive enthalten. Hast du das Einstellungsmenü schon mal geöffnet?

Du kannst den Abstand vertikal/horizontal einstellen. Du kannst einen Fahrer direkt einem Drescher zuweisen indem du das gleiche Ziel einstellst. Du kannst einstellen ab wann er zum Entladen des Hänger soll, ab wann er sich zum Drescher bewegen soll. Ob er den Drescher bis zum Erreichen des Füllstands verfolgen soll, ob er im Feld parken soll etc.

Aber wenn du dafür auf CP beharrst, musst du hier auch tatsächlich auf den neuen Mode2 warten. Auf AutoDrive Seite ist ja die Schnittstelle vorbereitet und wird von CP ja auch in den anderen Modi super verwendet.

Beste Grüße,
Stephan
