### ISSUE TITLE
Trouble with 1.0.5.7 or 1.0.5.8

### ISSUE THREAD

**Issue by Yoshi-01** [Stephan-S/FS19_AutoDrive#528]
Hallo Stephan,
wenn ich die version 1.0.5.7 - .8 verwende verschwinden die Zielpunkte per zufall aus dem Dropdown Menü.
Ich kann zwar mit den Pfeiltasten durchschalten (dort sind alle anwählbar) jedoch funktionieren die Pfeiltasten nur für das obere Dropdown Menü.
Beim unteren hab ich keine Möglichkeit zum auswählen.
Mit der älteren Version 1.0.5.1 sind alle Zielpunkte da und im Dropdown Menü anwählbar.

Ich habe auch versucht ein neues Spiel mit den letzen beiden Versionen zu beginnen, aber der Fehler ist der gleiche.

**Comment by geo-luchs** [comment]
Ich dachte am Anfang , dass mir auf einmal auch Wegpunkte fehlen würden auf einmal. Aber da war mir  noch nicht klar,  dass ich mit dem Mausrad scrollen kann, und dachte erst da fehlen Wegpunkte, dabei war ich nur am Ende der Liste.

Desweiteren hat Stephan ein zusätzliches Icon eingebaut. man kann den, ich glaube, zuletzt ausgewählten Wegpunkt in einen beliebigen Ordner verschieben , mit dem dicken Pfeil nach rechts.

Kann das vielleicht sein, dass Du den Wegpunkt in einen anderen Ordner verschoben hast?

**Comment by Yoshi-01** [comment]
Hallo geo-luchs,

dein Tip mit dem Mausrad war goldrichtig. Ordner hatte ich nicht aktiv, aber die Liste wurde so weit nach unten gescrollt das man nur mehr den letzten Eintrag sah. Super danke dafür!!

Vielleicht kannst du mir bei noch was helfen. Ich weiß wie ich einen Zielpunkt erstellen und umbenennen kann. Kann man aber auch einen Zielpunkt löschen ohne das ich vor Ort die Wegstrecke lösche?
Lg Yoshi

**Comment by geo-luchs** [comment]
Moin Yoshi

Ja, kann ich. Fahr bis zum Wegpunkt, dass die rote Linie am Wegpunkt hängt.
Auf den LÖSCHEN Button mit
LINKE Maustaste=  Knoten /Wegstrecke löschen
RECHTE Maustaste = nur Zielpunkt löschen.

Alternativ kann man sein Streckennetz auch sehr gut im größeren Stil  im AD Course Editor AD.jar  bearbeiten.
Gruß  Carsten

**Comment by geo-luchs** [comment]
Yoshi:  falls damit dein Issue hier beantwortet ist, kannst du es bitte schließen.
Damit entlasten wir Stephan ein wenig, der hier einen super Job macht, aber auch viele Issues auf dem Schirm haben muss

**Comment by Yoshi-01** [comment]
OK mach ich sobald ich von der Arbeit komme. Wie funktioniert dieser editor und wo finde ich ihn? Von meinem Huawei-Telefon gesendet-------- Ursprüngliche Nachricht --------Betreff: Re: [Stephan-S/FS19_AutoDrive] Trouble with 1.0.5.7 or 1.0.5.8 (#528)Von: geo-luchs An: Stephan-S/FS19_AutoDrive Cc: Yoshi-01 ,Author Yoshi:  falls damit dein Issue hier beantwortet ist, kannst du es bitte schließen.

Damit entlasten wir Stephan ein wenig, der hier einen super Job macht, aber auch viele Issues auf dem Schirm haben muss

**Comment by geo-luchs** [comment]
Ad.jar ist hier im GITHUB zu finden.
https://github.com/Stephan-S/FS19_AutoDrive/tree/master/AutoDrive%20Course%20Editor
Im src/mapimages Unterverzeichnis findest du einige Maps. Wie man eigene .png Files seiner Map erstellt weiß ich leider nicht.

LS19 Spielstand am besten vorher schließen. 
AD.jar starten. Dann mit Load Map das .png FILE seiner Map Laden.
Mit Load config sein .XML FILE vom AD Laden, welches du im Savegame Ordner findest.

Kann sein, dass du dann nur einen schmalen waagerechten Streifen siehst. Dann Fenster nach unten größer  ziehen.
Dann solltest du dein Streckennetz sehen.
Oben gibt es dann die Funktionen als Buttons.
Button anklicken, was man machen will, und dann den jeweiligen Wegpunkt anklicken.

Delete node :  löscht einen Punkt komplett
Created node:  erzeugt einen neuen Punkt
Connect node: verbindet 2 Punkte
Move node: verschiebt Wegpunkt, ohne Verbindungen zu lösen
Delete Destination  :  Zielpunkt löschen
Created dsstination: neues Ziel auf einem vorhandenen Wegpunkt erzeugen -> Name eingeben

Hoffe, das hilft dir ein wenig

**Comment by Woife1** [comment]
Der Editor ist auch mit dabei wenn du auf Code gehst und das Projekt als zip herunter lädst

**Comment by Yoshi-01** [comment]
ok, danke euch beiden. Ich schließe nun diesen Thread
