### ISSUE TITLE
Steigungen

### ISSUE THREAD

**Issue by OnkelH0tte** [Stephan-S/FS19_AutoDrive#529]
Hallo Stephan,

wäre es vielleicht möglich, dass AD es schafft auch etwas steilere Steigungen hoch zu kommen?

Zum Beispiel habe ich auf der Nordfriesischen Marsch das Problem, dass AD es nicht (bzw. nicht immer) schafft die Deiche hoch zu kommen. CP hat damit keine Probleme. Selbst ein 500 PS Traktor schafft es nicht.

**Comment by worker2419** [comment]
hab mir Erlaub dies mit #440 zu verknüpfen.

**Comment by Woife1** [comment]
die #440 ist die identische Meldung
ich vermute sehr stark das da die Kollisionsabfrage dem Fahrer in die Quere kommt

**Comment by Stephan-S** [comment]
Könnt ihr bestätigen, dass das Problem in der selbst gezippten Version für euch behoben ist?
Ansonsten gibt es spätestens Sonntag einen neuen Release.
Danke!

**Comment by worker2419** [comment]
Hallo Stephan, das Problem ist noch nicht vom Tisch, leider. Was ich aber sagen kann, ist das es eine Veränderung gegeben hat. Zwar kommt der Drescher noch nicht nach oben, aber er bewegt sich mm für mm vorwärts. Interessant finde ich, schaltet man AD ab und sofort wieder ein schafft er die Steigung ohne Probleme.
Dieser Eintrag erscheint als letztes in der Log, wenn der Drescher an der Steigung hängt: 
data/shared/ai/trafficCollision.i3d (19.55 ms)

**Comment by geo-luchs** [comment]
Hallo

ich spiele auch auf der NF_marsch (jetzt 2.5).
Habe soeben das neueste ZIP File vom AD heruntergeladen.

Habe den Drescher RSM 161, Schneidwerk wird hinterhergezogen.
Kommt es vielleicht auch auf den Drescher an?

Ich komme die Deichsteigung in der Mitte der Karte zwischen Feld 21 und Feld 9 ohne Probleme hoch.
Habe auch nicht den Eintrag im Logfile

**Comment by OnkelH0tte** [comment]
> die #440 ist die identische Meldung
> ich vermute sehr stark das da die Kollisionsabfrage dem Fahrer in die Quere kommt
> Die einfache und schnelle Lösung dafür ist:
> kauf dir die Straßen und entschärf die Auffahrten dann geht es ohne Probleme
> FED hat darayuf auch reagiert, nicht sein Problem wenn ein Mod Probleme macht der nicht von ihm ist

ja, das habe ich auch von ihm gehört, leider. Aber mit der 4 fach will er ja auch auf AD umsteigen, mal sehen was er dann sagt, wenn stephan nicht vorher das problem gelöst hat.

die straßen möchte ich nur als aller letzte lösung entschärfen. bin mir sicher das stephan das gelöst bekommt, bei dem was er hier schon geleistet hat.

**Comment by Woife1** [comment]
Die Frage ist nur ob Stephan das mit der Kollisionsabfrage richtig hinbekommt.
Nicht das zum Schluss die Fahrer überall reindonnern....

hab es auf der NF schon hinbekommen mit dem Pickup über das halbe Feld 9 zu springen
die Auffahrten sind auch extrem steil
Wenn FED umsteigt wird er die Auffahrten definitiv ändern weil er dann damit auch nicht mehr klar kommt ;)

Aber nicht vergessen Danke an Stephan für die tolle Arbeit

**Comment by worker2419** [comment]
Dem Hinweis von @geo-luchs folgend habe ich verschiedene Drescher ausprobiert. Es ist tatsächlich so, dass je nach dem welchen Drescher man verwendet Steigungen erklimmt oder auch nicht.

**Comment by geo-luchs** [comment]
> Dem Hinweis von @geo-luchs folgend habe ich verschiedene Drescher ausprobiert. Es ist tatsächlich so, dass je nach dem welchen Drescher man verwendet Steigungen erklimmt oder auch nicht.

Kannst du herausfinden, ob die Drescher , die du getestet hast, stark unterschiedlich schwer sind? Ich glaube, jedes Fahrzeug hat ein definiertes Gewicht.

**Comment by Stephan-S** [comment]
Hey, das Gewicht sollte hier keine Rolle spielen. Hier ist das Problem mit Sicherheit nur die Kollisionserkennung.
Wenn ihr F5 drückt, seht ihr einige Debug Boxen. Die Box vorm Fahrzeug die sich mit der Fahrgeschwindigkeit ändert und nur bei aktivem AD-Fahrer zu sehen ist, ist die Kollisionsabfrage von AD. Wenn sie schwarz ist, ist alles gut und bei erkannter Kollision wird sie rot/orange.

**Comment by geo-luchs** [comment]
Moin

Wieder was gelernt. Mit F5  und den roten und schwarzen Boxen 
Werde es mal beobachten
Danke

**Comment by geo-luchs** [comment]
Hi Stephan

hab es jetzt mal getestet mit BigBags im Weg eines Traktors. Ich sehe zwar die schwarze Box, die je nach Geschwindigkeit unterschiedlich lang ist. Aber wenn ein BigBag im Weg steht, wird da nichts orange/rot, sie bleibt schwarz, wird nur auf eine flache Ebene reduziert, weil der Traktor ja dann 0Kmh hat.

**Comment by Woife1** [comment]
Teste das mal mit einem Fahrzeug im Weg und schau mal ob die erweiterte Kollisionserkennung an ist.

**Comment by geo-luchs** [comment]
![Kollosion](https://user-images.githubusercontent.com/53658780/65830184-88920000-e2ad-11e9-8903-b2fe1ef86d2b.PNG)

ja, in den AD Settings ist Kollisionserkennung an.
Hier ein Bild mit Traktor im Weg

**Comment by worker2419** [comment]
habe das mit dem Drescher an der Steigung getestet Je nach dem aus welcher Richtung und mit welchem Winkel man die Steigung anfährt wird die  Box rot und der Drescher steht, 

![AD_Steigung](https://user-images.githubusercontent.com/47278102/65830245-035b1b00-e2ae-11e9-879f-f8ca2135bf15.png)

**Comment by Stephan-S** [comment]
Hey, nur noch mal kurz als Ergänzung.
AD nutzt zwei verschiedene Methoden die Kollision zu erkennen.
Für statische Objekte und KI-Verkehr ist die gezeigte Box zuständig.
Bei dynamischen Fahrzeugen und alles was als 'vehicle' eingetragen ist (ja, da zählen bixboxes, paletten etc. auch dazu^^) nutze ich eine ähnliche Erkennung, die ich allerdings nicht zeichnen lasse. Aber diese funktioniert ja wie in den Bildern oben ersichtlich ist auch eigentlich problemlos und ist seit Release fast unverändert soweit ich mich erinnern kann

**Comment by OnkelH0tte** [comment]
hmmm, also irgendwie funktioniert es bei mir seit dem neuen patch wieder einwandfrei, zu mindestens bisher ist an den Steigungen kein Fahrzeug hängen geblieben.
