### ISSUE TITLE
Kreuzungserkennung / Vorfahrt regeln

### ISSUE THREAD

**Issue by SisSim** [Stephan-S/FS19_AutoDrive#530]
Hi, währe es möglich, das man einen Stop/Halt Punkt mit einbauen könnte?
Das problem ist, das der ADfahrer bei einer X Kreuzung einfach drüberfahrt, ohne an Geschwindigkeit zu verlieren  und auch bei T Kreuzungen nur ein bisschen die Geschwindigkeit drosselt. Mit einem Stop/Halt Punkt könnte man den ADfahrer dann  zum Halten bringen.
gruss
SirSim

**Comment by Stephan-S** [comment]
Hm,
da würde ich lieber automatisch vor Wegüberschneidungen abbremsen. Natürlich auswählbar in den Einstellungen.
Das klingt nicht verkehrt. Extra Haltepunkte würde ich allerdings nicht einbauen. Das passt nicht ganz ins Konzept :-)

Ich schreibs mal auf die ToDo-Liste

Beste Grüße,
Stephan

**Comment by Bigdaddy-KP** [comment]
Wenn ich mich hier mal anhängen darf. Spiele auf der Multimap da gibt es automatische Tore und Schranken wo er dran stößt da sie nicht so schnell aufgehen, da habe ich mir auch schon so einen, warte 2 Sekunden, punkt gewünscht.
