### ISSUE TITLE
Problem im MP

### ISSUE THREAD

**Issue by gerrit0476** [Stephan-S/FS19_AutoDrive#531]
Hallo Stephan,

bei mir läuft AD im MP (Dedi) nicht mehr. Die kompletten UI im Spiel verschwinden während ich einen Kurs einfahre. Folgende Meldung ist in der LOG:

 dataS/scripts/network/ConnectionManager.lua (28) : func
 Warning (script): 'setXMLString': Argument 2 has wrong type. Expected: String. Actual: Nil 
 ..\..\..\src\base\scripting\lua\LuaScriptSystem.cpp (882): expectedType == Value::VoidType || expectedType == Value::ClassType
 LUA call stack:
=config/mods/FS19_AutoDrive/scripts/AutoDriveXML.lua (448) : setXMLString
 =config/mods/FS19_AutoDrive/scripts/AutoDrive.lua (164) : saveToXML
dataS/scripts/utils/Utils.lua (382) : newFunc
 dataS/scripts/utils/Utils.lua (381) : oldFunc
 dataS/scripts/FSBaseMission.lua (2838) : saveSavegame
dataS/scripts/MessageCenter.lua (132) : callback
 dataS/scripts/events/SaveEvent.lua (23) : publish
 dataS/scripts/network/Server.lua (440) : readStream
dataS/scripts/network/ConnectionManager.lua (28) : func

Das tritt auf wenn ich im rechts Im AD UI ein Ziel anwählen will! 

Grüße Gerrit

**Comment by GitTomahawk** [comment]
Hallo Stephan,

Ich habe auch Probleme im MP und habe mir mal die logs und zugehörigen lua genauer angesehen.
Bei mir crasht z.B. das HUD weil die Groups nicht angezeigt werden können.
 z.B. getTextWidth': Argument 2 has wrong type. Expected: String. Actual: Nil 
Die Ursache dafür scheint darin zu liegen dass sie vom Server nicht übermittelt werden.
 'streamWriteString': Argument 1 has wrong type. Expected: Int. Actual: Nil
Ich denke das wiederum liegt daran, dass du in der dich bei Groß- und Kleinschreibung vertippt hast, da du mal "StreamID" und mal "StreamId" benutzt (Beispiel: "AutoDriveEventUtil.lua Zeile 185ff function AutoDrive:readGroupsFromStream(streamID)")

Wenn das nicht aus irgend einem Grund den ich nicht durchblicke Absicht war, dann würde vermutlich ein Search&Replace den Fehler beheben.

Grüße
Tomahawk

**Comment by Stephan-S** [comment]
Super, danke für die Hilfe.
So kann ich das auch mal schnell in der Mittagspause bearbeiten :-)
Dankeschöne @GitTomahawk 

Beste Grüße,
Stephan

**Comment by Bandesss** [comment]
Leider immer noch fehler 
[log.txt](https://github.com/Stephan-S/FS19_AutoDrive/files/3663134/log.txt)

**Comment by Stephan-S** [comment]
@Bandesss vor 15 Minuten behoben.  Sollte weg sein. Ob es was neues gibt kann ich nicht sagen.
Aber wenn dein Server gerade zur Verfügung steht, wäre es natürlich super wenn du die Version nochmal testen kannst :-)
Sorry, dass mein MP-Support so schwach ausfällt.

**Comment by Bandesss** [comment]
Ja Hallo, Teste gerade die Neue Version Meld mich

**Comment by gerrit0476** [comment]
Hallo Stephan,

habe jetzt ne Zeit lang gespielt. Läuft super! Vielen Dank

Grüße Gerrit

**Comment by Moitzbert** [comment]
Hallo Stephan,

habe das selbe Problem. Wie kann ich denn dein neues Update installieren sprich einfügen ?

Mfg 
Christof

**Comment by GitTomahawk** [comment]
Hi,
Einfach die AutoDriveEventUtil.lua herunterladen und austauschen
Falls du auch Probleme mit Gruppen/Ordnern hast sieh dir mal [https://github.com/Stephan-S/FS19_AutoDrive/issues/540] an

**Comment by Moitzbert** [comment]
Vielen Dank 

Mit freundlichen Grüßen 

Mit freundlichen Grüßen 
Christof Maitz

**Comment by Bandesss** [comment]
@GitTomahawk was genau muss ich da austauschen ?
Bei mir geht das Fenster weg, wenn ich Ordner auf JA mache.

**Comment by GitTomahawk** [comment]
Du nimmst die aktuelle Version AutoDriveEventUtil.lua und dann den folgenden Workaround-Code vom Github. Wenn du darin nach der Zeile 187:  "local numberOfGroups = streamReadFloat32(streamId);" den folgenden Code einfügst (Hof1,2,3 kannst du mit deinen Ordnernamen ersetzen), dann sollte der Hud auch mit akiven Ordnern funktionieren, wenn die Übermittling vom Server nicht klappt.
`if` (numberOfGroups == nil) then
		-- Use Default Groups if none received. This prevents empty group list.
		AutoDrive.groups["All"] = 1;
		AutoDrive.groups["Hof1"] = 2;
		AutoDrive.groups["Hof2"] = 3;
		AutoDrive.groups["Hof3"] = 4;
	end;`
Die Ursache des Übermillungsproblems konnte ich noch nicht ergründen, dafür habe ich zu wenig Erfahrung mit den Scripten. Vielleicht hat Stephan ja demnächst dafür eine Lösung.

**Comment by Bandesss** [comment]
Hmm danke aber das ist mir zu schwer.
Ja ich hoffe auf ein Fix von Stephan

**Comment by Bandesss** [comment]
Wie baue ich es , hier ein?
function AutoDrive:readGroupsFromStream(streamId)
    AutoDrive.groups = {};
    local numberOfGroups = streamReadFloat32(streamId);
    local loopCounter = 1;
    while loopCounter <= numberOfGroups do
		local groupName = streamReadStringOrEmpty(streamId);
        local groupID = streamReadFloat32(streamId);
        if groupName ~= nil and groupName ~= "" then
            AutoDrive.groups[groupName] = groupID;
        end;
        loopCounter = loopCounter + 1;
    end;
end;
Meine Ordner sind All, Feld,Hof, Produktionen
Wäre super, wenn du mir Helfen würdest ?
Gruss Ronny

**Comment by Bandesss** [comment]
Vielen Dank @GitTomahawk hat geklappt 👍👍👍
