### ISSUE TITLE
Auto-Drive HUD 

### ISSUE THREAD

**Issue by indo389** [Stephan-S/FS19_AutoDrive#532]
Hallo,habe ein Problem wenn ich Auto-drive aktiviert habe,wird oben links in der HUD nicht mehr die Schnittlängen Einstellung von meinem Harvest angezeigt.Wenn ich AD wieder herausnehme funktioniert wieder alles normal,und kann die Schnittlänge wieder einstellen.
Hoffe ihr könnt mir da weiterhelfen,möchte nicht immer AD herausnehmen um Bäume zu fällen.
Gruß Volker

**Comment by geo-luchs** [comment]
Hallo, das Problem hate ich auch gerade.
Ich vermute, das liegt daran, dass das HUD oben lins nur eine begrenzte Anzahl von Tasten anzeigen kann.
Ich hatte ncoh einige andere Mods, und alle wollen da oben was anzeigen.
Jemand gab mir den Tipp einige nicht benötigte Tastenbelegungen zu löschen.
Aber richtig geholfen hat es nicht, denn das hängt ab von den Mods die du so installiert hast.
Ich hab noch Vehicle Addon, und VCA will da auch was anzeigen.

Letztlich hat Fed mir den Tipp gegeben, wenn man IM Fahrzeug sitzt, sieht man die Shnittlänge in einem Display. und dann mit Z ändern. Das ist Gerätefunktion 3

**Comment by Stephan-S** [comment]
Hey, du kannst die AutoDrive Hilfen in den Einstellungen ausschalten. Nach dem nächsten Fahrzeugwechsel sind sie weg

**Comment by indo389** [comment]
Vielen Dank an euch für die schnelle Hilfe,werde ich gleich mal testen.👍
________________________________
Von: geo-luchs <notifications@github.com>
Gesendet: Donnerstag, 26. September 2019 20:17
An: Stephan-S/FS19_AutoDrive <FS19_AutoDrive@noreply.github.com>
Cc: indo389 <indo1959@live.de>; Author <author@noreply.github.com>
Betreff: Re: [Stephan-S/FS19_AutoDrive] Auto-Drive HUD (#532)


Hallo, das Problem hate ich auch gerade.
Ich vermute, das liegt daran, dass das HUD oben lins nur eine begrenzte Anzahl von Tasten anzeigen kann.
Ich hatte ncoh einige andere Mods, und alle wollen da oben was anzeigen.
Jemand gab mir den Tipp einige nicht benötigte Tastenbelegungen zu löschen.
Aber richtig geholfen hat es nicht, denn das hängt ab von den Mods die du so installiert hast.
Ich hab noch Vehicle Addon, und VCA will da auch was anzeigen.

Letztlich hat Fed mir den Tipp gegeben, wenn man IM Fahrzeug sitzt, sieht man die Shnittlänge in einem Display. und dann mit Z ändern. Das ist Gerätefunktion 3
