### ISSUE TITLE
Neue Ziel-Punkte werden bei anderen Mitspielern nicht aktualisiert

### ISSUE THREAD

**Issue by Onkel2000** [Stephan-S/FS19_AutoDrive#535]
Hallo,

ich spiele mit meiner Freundin mit der aktuellen AutoDrive Version im MP zusammen, es läuft auch sehr gut. Doch wenn ich neue Zielpunkte einfüge und den Kurs neu berechne, taucht der Punkt nur bei mir im Menü auf, strecken Änderungen jedoch bei uns beiden.  erst wenn sie das Spiel verlässt und wieder rein geht, tauchen die Punkte im Menü auf.

Wenn sie versucht einfach mal neu zu berechnen wird der Button rot. 

Hoffe ihr versteht, was ich meine. Weiß jemand einen Rat?

**Comment by Stephan-S** [comment]
Hey, hab gerade einen kleinen Fix hochgeladen.
Allerdings nur in der selbst gezippten Version. Ein fertiges Release wird es spätestens Sonntag wieder geben.
MP-Support kann ich leider nur bedingt geben, da ich einerseits alleine entwickle, keinen Dedi-Server habe und es immer sehr viel Zeit kostet.
Ich hoffe also der Fix sollte das Problem lösen. Also ein kurzes Feedback wenn ihr zum Testen gekommen seid, wäre super.

Beste Grüße,
Stephan

**Comment by Onkel2000** [comment]
> 
> 
> Hey, hab gerade einen kleinen Fix hochgeladen.
> Allerdings nur in der selbst gezippten Version. Ein fertiges Release wird es spätestens Sonntag wieder geben.
> MP-Support kann ich leider nur bedingt geben, da ich einerseits alleine entwickle, keinen Dedi-Server habe und es immer sehr viel Zeit kostet.
> Ich hoffe also der Fix sollte das Problem lösen. Also ein kurzes Feedback wenn ihr zum Testen gekommen seid, wäre super.
> 
> Beste Grüße,
> Stephan

Hey, danke für denn schnellen fix. Es funktioniert jetzt super :)

Wirklich vielen Dank :)

**Comment by Stephan-S** [comment]
Super. Danke für das schnelle Feedback!
