### ISSUE TITLE
Abfahrer rufen ab x% Bug bei mehr als einem Drescher

### ISSUE THREAD

**Issue by C43AMG** [Stephan-S/FS19_AutoDrive#536]
Wenn 1 Drescher und 1 Abfahrer fahren funktioniert das mit dem früher los fahren gut, bei 2 Dreschern und 1 Abfahrer ist er verwirrt wenn beide Drescher die x% erreichen, dann tankt der Abfahrer nicht ab

**Comment by Stephan-S** [comment]
Leider etwas ungenau beschrieben.
Klingt eher als würde er den Weg zu einem der Drescher nicht berechnen können.

Ich schau mir das Thema mehrere Abfahrer / Drescher aber eh nochmal genauer an.
