### ISSUE TITLE
Autodrive Editor - Save unter neuem Namen --> XML Tag ändern

### ISSUE THREAD

**Issue by geo-luchs** [Stephan-S/FS19_AutoDrive#537]
Hallo Stephan

ich bin mir nicht sicher, warum Du es so gelöst hast, aber Autodrive liegt zwar immer direkt in einem Savegame, aber trotzdem hast Du 
a) den Mapnamen im Autodrive_...xml File
b) in der Datei einen XML Tag, wo der Map Name drin steht.

Wenn Fed seine NF_Marsch Map updatet, ändert er immer den Mapnamen, zählt die Version hoch.

In diesem Fall muss deine Autodrive_XYZ_config.xml Datei verändert werden.
Leider geht das nicht mit deinem Autodrive Editor.

Mit Save kann ich zwar den Dateinamen angeben,  aber der Tag in der XML Datei bleibt auf dem alten Namen stehen, und somit wird nach Update der Map die AD Infos nicht mehr gelesen.

Mein Vorschlag:
Beim Save im AD.jar : Weiterhin den neuen Dateinamen angeben.
Syntax ist ja IMMER  Autodrive_XYZ_config.xml , wobei XYZ der Map Name sein MUSS.

Wenn Du beim Save einfach den String XYZ aus dem angebenen Filenamen auslöst, und noch in die beiden Tags in der XML Datei reinschreibst, muss niemand mehr die Datei manuell anpassen.

Oder aber komplett auf den Tag verzichten? Warum muss der Mapname im Filenamen und im Tag überprüft werden?

Gruß
Carsten

**Comment by Stephan-S** [comment]
Carsten, 
du hast absolut Recht :-)

Nur ändern kann ich das für die aktuelle Version (LS19) nicht mehr ohne hier jegliche Kompatibilität zu brechen.
Ich werde es für eine LS21 Version definitiv anders lösen und die Tags in der Datei entfernen. Das Problem ist das ich nicht auf die Kinder-Elemente des Mapnamen-Tags zugreifen kann ohne zu wissen, wie der (gespeicherte) Mapname ist. Ansonsten würde ich die Überprüfung jetzt schon herausnehmen.

Und für alle die noch AutoDrive-Versionen nutzen bevor meine Anpassung läuft, sollte es ja auch wie gewohnt weiter funktionieren.

Also müssen wir hier leider damit leben, bis ich für LS21 die Änderung vornehmen kann und dort auch, falls es portierte Maps geben wird, einen Import von LS19-Files erlauben werde.

Aber deinen Vorschlag für den Editor nehme ich gerne an, um hier eine etwas leichtere Anpassung an neue Mapversionen zu erlauben.

Viele Grüße,
Stephan

**Comment by geo-luchs** [comment]
Hallo Stephan

super, danke fürs schnelle Umsetzen. Es funktioniert.
Damit kann man jetzt gut leben.

Viele Grüße
Carsten
