### ISSUE TITLE
Distanz Vorausschauen (Lenkung)

### ISSUE THREAD

**Issue by hjnk** [Stephan-S/FS19_AutoDrive#538]
Ist es möglich, diesen Wert im Skript zu ändern? Es kommt oft vor, das Traktoren vom Lenkeinschlag her einen kleineren Wendekreis fahren können, als es der angehängte Anhänger zulässt, folge ist, der Wendekreis wird grösser, der Traktor schiebt über die Vorderräder, folge es kommt zur Kollision mit der eingesetzten Erntemaschine, diese wird dann nicht ab getankt, weil der Traktor in folge des nun größeren Wendekreises der Erntemaschine ins Heck gefahren ist. Diesen Wert kann man nur auf maximal 8 stellen, ist es möglich, das man diesen Wert erhöhen kann auf 10 oder sogar bis auf 20, um zu gewährleisten, das der Traktor mit dem angehängten Anhänger auch den Wendekreis zur Erntemaschine problemlos und ohne Crash sein Ziel, nämlich die Abtankung der Erntemaschine erreicht.

**Comment by Stephan-S** [comment]
Servus, ich hab in der letzten Version den Radius an die Arbeitsgeräte/Anhänger angepasst.
Damit sollte sich das Problem größtenteils erledigt haben.
Wenn er jetzt keine Kurven schafft, liegt es an der aktuell etwas verbuggten Version meinder Pfadsuche, aber da bin ich aktuell dran.
Also mache ich hier mal zu um das Theme klar trennen zu können :-)
