### ISSUE TITLE
Ich  habe nun 60 Stunden mit AD garbeitet ich finde es ist ein toller Mod.

### ISSUE THREAD

**Issue by RudiBergfeld** [Stephan-S/FS19_AutoDrive#539]
Ich habe nun 60 Stunden auf der Suedhemmern gespielt ich find den Mod eigendlich ganz toll. Ich habe immer wider das problem das der Abfahrer den weg zu seinen Ziehlpunkten findet und 10 min Später nicht . Ist vieleicht der Rechner überlastet ich dach ich hätte son einen Guten.

**Comment by worker2419** [comment]
@RudiBergfeld poste doch bitte einmal die Log vom Spiel. AD schreibt in die Log, wenn er einen Weg nicht finden kann. Spiele die SH auch und kenne das Verhalten nur wenn das Fahrzeug absolut in der Botanik steht.

**Comment by Bandesss** [comment]
Ja ist aber bei mir auch seit ein paar Minuten, er findet keine Wege mehr.

**Comment by geo-luchs** [comment]
welche Version habt ihr? das letzte verfügbare Zip file?

**Comment by Bandesss** [comment]
Ich habe die letze selber gepackt

**Comment by worker2419** [comment]
zur letzten selbst gepackten hat Stephan geschrieben: 
Added first iteration of active unloading
Please be aware that this is a work in progress version.
Use this developer version only if you like to try out the new functions and if you are prepared to see things fail :-)

Erste Iteration der aktiven Entladung hinzugefügt

Bitte beachten Sie, dass es sich um eine Work in Progress-Version handelt.
Verwenden Sie diese Entwicklerversion nur, wenn Sie die neuen Funktionen ausprobieren möchten und wenn Sie bereit sind, zu sehen, dass Dinge scheitern :-)

**Comment by geo-luchs** [comment]
mit dem Zip file, welches ich gestern um 21:07 gepackt habe, gibt es das Problem nicht. Bei mir läuft es auch nach 20 min noch ohne probleme. (auf der NF Marsch, aber ich denke die Karte sollte nicht das problem sein)

**Comment by RudiBergfeld** [comment]
Ich habe den AD noch einmal auf der Multimap getestet das selbe Problem aber schon nach 6 Zielpunkten. Es ist schon kalr das es sich hir um eine entwikler Version handelt aber wie soll der Entwikler die Probleme finden wenn es niemand Testet und und die Probleme mitteilt. Ich habe die Version 1.58 von gestern. Ich habe versucht die Log einzufügen wie geht das .

**Comment by Bandesss** [comment]
Bei Attach File :)

**Comment by geo-luchs** [comment]
Du kannst die Datei einfach mit der Maus per Drag&Drop hier in das Kommentar Fenster ziehen

**Comment by Stephan-S** [comment]
Servus, wenn du mir ein logfile schicken könntest, kann ich hier gerne unterstützen.
Außerdem wäre die AutoDrive_config sicher auch interessant. 
Wenn du sagst er findet keine Wege, muss ich eher davon ausgehen, dass hier ein Fehler beim Kurs erstellen/einfahren vorliegt.
Außer du redest vom Pfadfind-Algorithmus auf dem Feld.
Damit ich hier mal wieder mehr Ordnung rein bekomme mache ich hier erstmal zu. Wenn sich das Problem nicht erledigt hat, mach bitte wieder auf und schick mir ein Log file und die Config. Danke :-)

**Comment by RudiBergfeld** [comment]
Gesendet von Mail für Windows 10

Von: Stephan Schlosser
Gesendet: Donnerstag, 3. Oktober 2019 12:50
An: Stephan-S/FS19_AutoDrive
Cc: RudiBergfeld; Mention
Betreff: Re: [Stephan-S/FS19_AutoDrive] Ich habe nun 60 Stunden mit ADgarbeitet ich finde es ist ein toller Mod. (#539)

Servus, wenn du mir ein logfile schicken könntest, kann ich hier gerne unterstützen.
Außerdem wäre die AutoDrive_config sicher auch interessant.
Wenn du sagst er findet keine Wege, muss ich eher davon ausgehen, dass hier ein Fehler beim Kurs erstellen/einfahren vorliegt.
Außer du redest vom Pfadfind-Algorithmus auf dem Feld.
Damit ich hier mal wieder mehr Ordnung rein bekomme mache ich hier erstmal zu. Wenn sich das Problem nicht erledigt hat, mach bitte wieder auf und schick mir ein Log file und die Config. Danke :-)
