### ISSUE TITLE
HUD verschwindet bei Mitspielern im MP

### ISSUE THREAD

**Issue by Caliban2017** [Stephan-S/FS19_AutoDrive#540]
Moin, hab leider wieder einmal ein Fehler zu vermelden, ich dachte es ging hier um den Fehler der letztens schon mal bezüglich der HUD Probleme gepostet wurde aber offenbar ist das hier ein anderer Fehler. 

Wenn ein Mitspieler auf meinem MP Server (kein Dedi Server) bestimmte Fahrzeuge betritt, verschwand bei ihm immer das HUD. Nur die Karte war noch da, der ganze Rest war wohl weg und erst nach einem Reconnect wieder da.

Ich bat ihn mal seine Log zu schicken und es kommt dieser Fehler:

2019-09-28 20:25 Error: Running LUA method 'draw'.
2019-09-28 20:25 C:/Users/BlackScorpion/Documents/My Games/FarmingSimulator2019/mods/FS19_AutoDrive/scripts/HudElements/PullDownList.lua:361: bad argument #1 to 'insert' (table expected, got nil)

Dieser Fehler trat bei ihm bei jedem Fahrzeug auf in der aktuellen gezippten Version. Sind jetzt erstmal auf das letzte Release zurück, da geht es offenbar wieder. 

Viele Grüße

**Comment by Moitzbert** [comment]
habe das selbe Problem ! 

es gibt bei einem geschlossenen Thema anscheinend eine Lösung, kann diese aber nicht installieren.
Bzw kann ICH das nicht...

bitte um Hilfe

**Comment by Caliban2017** [comment]
Welche Lösung meinst du denn...?

**Comment by GitTomahawk** [comment]
Bei uns lag der Fehler dran, das die Gruppennamen nicht vom Server zu den Clients synchronisiert werden.
Ich hab als workarount erstmal "default" Gruppennamen eingefügt.
AutoDriveEventUtil.lua Zeile 188ff

`if (numberOfGroups < 1 or numberOfGroups == nil) then
	-- Use Default Groups if none received. This prevents empty group list.
	AutoDrive.groups["All"] = 1;
	AutoDrive.groups["Hof1"] = 2;
	AutoDrive.groups["Hof2"] = 3;
	AutoDrive.groups["Hof3"] = 4;
end;`

@Stephan-S : 
Ich würde vorschlagen die Gruppennamen nicht separat zu übertragen.
Stattdesen die Gruppen und deren Sortierung lokal bei jedem user speichern.
Die Sortierung der Gruppen will eh jeder Spieler anders haben. (z.B. seinen Hof ganz oben)
Du überträgst ja schon mit jedem Marker zu welcher Gruppe er gehört.
Wenn der Gruppenname eines Markers noch nicht in der (lokalen) Liste steht, dann wird er einfach am Ende hinzufügt und lokal gespeichert.
