### ISSUE TITLE
Fehler in der übersicht

### ISSUE THREAD

**Issue by Bandesss** [Stephan-S/FS19_AutoDrive#541]
Hallo
das mit den Karten ist mir klar. Aber was ist der dritter Fehler ?

XML-Datei 'AutoDrive_Ravenport_init_config.xml' ist zu groß. Größe 0,34 MB (max. 0,25 MB)
XML-Datei 'AutoDrive_Eiersholt_init_config.xml' ist zu groß. Größe 1,19 MB (max. 0,25 MB)
Anzahl der Dateien pro Store-Artikel zu hoch. 140 gefunden (max. 128)
Gruss
[log.txt](https://github.com/Stephan-S/FS19_AutoDrive/files/3665870/log.txt)

**Comment by vertigoogle** [comment]
Ich vermute du hast einen Mod (oder mehrere) geladen, die sich eine Store-Kategorie teilen. Darin sind aber nur 128 Waren/Artikel/Items erlaubt.
Ich habe allerdings die Fehlermeldung nicht deiner log gefunden und kann daher nur vermuten.

**Comment by Bandesss** [comment]
Ne das zeigt es,auf der Server Seite  an als Fehler vom Mod :(
Sorry schlecht erklärt .

**Comment by Stephan-S** [comment]
Liegt wohl daran das ich inzwischen eine ganze Menge Dateien im Mod habe (145 einzelne Dateien)
Sollte aber wieder nur eine Warnung/Notiz sein, die man einfach ignorieren kann :-)
