### ISSUE TITLE
Auto Drive Editor HELP

### ISSUE THREAD

**Issue by JohnnyFriel08** [Stephan-S/FS19_AutoDrive#544]
Hi...... I have downloaded the zip file from the main page here. I have then extracted the zip and placed "FS_AutoDrive" in my mods folder, I have also placed "AutoDrive Course Editor" on my desktop.

I play the game (any map) and i can use the mod. I have saved OakfieldFarm PDA as .png file 2048x2048 and placed within "AutoDrive Course Editor\src\mapImages" file.

How do I now edit my course(s)??? I can not figure it out at all after many hours searching web for ideas??? Do I need to download some kind of software or program? I have downloaded java but no joy....... Any help would be great!!!

**Comment by worker2419** [comment]
Hallo @JohnnyFriel08 here are the Steps starting the editor

 editor need time to work

1. created a folder on a drive with write access Name FS19_AutoDrive_Editor
2. Copy the AutoDrive Course Editor folder from the Master ZIP and remove the spaces from the folder name. Then insert the PNG file into the subfolder src\mapImages.
This file is in the ZIP file of your map and always has the name pda_map_H.dds. Export this file and open it with an image editor and save it as PNG, name without spaces e.g. MyMap.PNG
3. Copy the folder courses from the Master ZIP and create a subfolder. E.g. mymap name without spaces
4. copies the file AutoDrive_xxxxxxxx_config.xml from the current savegame into the created subfolder xxxxx= name of the map
AD.jar start the editor

In the ZIP file as help the file Aufruf.cmd. If you start the editor above, the DOS window shows the steps the program does, but also errors if it doesn't work.
Translation by deepl
[Aufruf.zip](https://github.com/Stephan-S/FS19_AutoDrive/files/3666426/Aufruf.zip)

**Comment by JohnnyFriel08** [comment]
Where/What is the AD.jar start the editor? I have completed all the other steps as described?

Pictures for reference.

Johnny

<img width="960" alt="Pic 1" src="https://user-images.githubusercontent.com/50154481/65830871-862ea680-e2ab-11e9-9b0f-432cd261bf75.png">
<img width="960" alt="Pic 2" src="https://user-images.githubusercontent.com/50154481/65830873-89c22d80-e2ab-11e9-96b1-3adae5ac2b9d.png">
<img width="960" alt="Copied course" src="https://user-images.githubusercontent.com/50154481/65830874-8cbd1e00-e2ab-11e9-9d92-cfe13e9b0aa5.png">
<img width="960" alt="Map PNG correct size" src="https://user-images.githubusercontent.com/50154481/65830877-8fb80e80-e2ab-11e9-9c16-9cafdf0dd9bf.png">

**Comment by badfly** [comment]
<img width="960" alt="65830873-89c22d80-e2ab-11e9-96b1-3adae5ac2b9d" src="https://user-images.githubusercontent.com/9772203/65833364-5ea20300-e2d8-11e9-8612-fad3ebe17104.png">

Вам нужно скачать java с официального сайта, и убрать ассоциацию файлов "jar" с WinRar (наст
ройки- интеграция)

You need to download java from the official site, and remove the association of "jar" files with WinRar (settings - integration)

**Comment by JohnnyFriel08** [comment]
I have already downloaded Java from official website JAVA Oracle I think it was? So I need to go into WinRar settings to remove association yes?

**Comment by badfly** [comment]
yes

**Comment by JohnnyFriel08** [comment]
@badfly thanks got it to work 😀 my only issue now is that some of the routes don't appear on the roads, they appear slightly off the track so changing them may be difficult to ensure they are correctly aligned. Any ideas?

**Comment by ploughedfieldman123** [comment]
what is the latest version of the editor as I have version 0.1  and where can I download it if there is a newer one

**Comment by worker2419** [comment]
the lastet version is from 2 days ago. version number was not changed. You can download from section code on the right side "Clone or Download.

**Comment by ploughedfieldman123** [comment]
> the lastet version is from 2 days ago. version number was not changed. You can download from section code on the right side "Clone or Download.

Ok many thanks. I see latest says at right hand side 4x and 16x  is that map sizes. if so how can i tell what oakfields map is

**Comment by worker2419** [comment]
yes,  4x and 16x are map sizes. oakfields map is a normal map, i think. So you don't have to change the size because it is default.

**Comment by ddewar** [comment]
I followed the instructions above trying to load Felsbrunn. I'm running into the following error: 

![image](https://user-images.githubusercontent.com/15822357/65929210-c171c800-e3c6-11e9-802f-5753aa6e32c2.png)

Any tips? 

Thanks

**Comment by vertigoogle** [comment]
This Tutorial should be a sticky 😉

**Comment by Lexamot** [comment]
Hi! im new to this. I followed all the steps written above. Downloaded java etc. But i cant figure out what program to start it with? Because if i just click AD file winrar will open even if i have done the integration part. And if i choose open with java a black window just pops up for a milisecond then nothing. Would be nice with some help. Im a total noob at this.

**Comment by ddewar** [comment]
@Lexamot I believe if you right click on the AD file and chose "open with..." you should be able to pick java there.

**Comment by Lexamot** [comment]
@ddewar i've tried that, a black windows pops up and disappears instantly.

**Comment by wlfheart** [comment]
This happens with me as well.
