### ISSUE TITLE
Manual 1-click target swap? - Manueller 1-Klick Zieltausch?

### ISSUE THREAD

**Issue by haamic** [Stephan-S/FS19_AutoDrive#545]
Hello, Stephan,
in the "Collect and Deliver" + "Collect" modes, the two "Store" destinations are each submerged in each other (for reasons that are certain).
If I don't pay attention to which mode I'm using and have entered the load and unload destinations from my now very long destination list, I notice that the mode was still wrong or was chosen wrongly when I started the game.
It would be nice, if there would be a "swap button", with which you can swap the two entered destinations with each other with one click.
This saves you having to re-enter the correct target order manually.
Maybe you can implement this sometime. This has no priority, I would only find it helpful sometimes.
Have a nice Sunday
Greetings Micha

Translated with www.DeepL.com/Translator

Hallo Stephan,
in des Modi "Abholen und Abliefern" + "Abholen" sind je die beiden "Laden"-Ziele miteinander vertaucht (hat bestimmt Gründe). 
Wenn ich nicht aufpasse, welchen Modus ich gerade nutze und die Lade- und Entlade-Ziele aus meiner nun doch sehr langen Zielliste eingetragen habe, stelle ich spätestens beim Starten fest, das der Modus noch falsch stand, oder falsch gewählt wurde.
Es wäre schön, wenn es einen "Tausch-Button" gäbe, womit man mit einem Klick, die beiden eingegebenen Ziele miteinander vertauschten kann. 
So spart man sich die erneute manuelle Eingabe der richtigen Zielreihenfolge.
Vielleicht kannst du das irgendwann mal so implementieren. Das hat keine Priorität, ich fände es nur manchmal hilfreich.
Schönen Sonntag
Gruss Micha

**Comment by vertigoogle** [comment]
+1
Ich wollte gerade einen Issue für die gleiche Idee aufmachen.
Hintergrund ist, dass ich öfters mal zwischen zwei Ziele hin- und herfahren möchte, aber an den Zielpunkten manuelle Arbeit zu verrichten habe. Die normale Überführungsfahrt hat nur ein Ziel verständlicherweise, also wollte ich "Abholen und Abliefern" nutzen. Hier wäre ein Button zum Tauschen der Ziele sehr hilfreich.

**Comment by Stephan-S** [comment]
Reicht euch ein neues Keybinding dafür? Ein extra Button im HUD sehe ich für die Funktion als etwas 'Overkill', da sicher bei weitem nicht jeder den Bedarf dafür hat nehme ich an :-)

**Comment by vertigoogle** [comment]
Klar, warum nicht 😄 

Wenn du das HUD allerdings zu überladen findest, dann habe ich ein paar Ideen wie man da aufräumen könnte: 
- Die beiden Buttons für die Geschwindigkeit sind implizit doppelt vorhanden, da man die ja durch einen Klick auf die Zahl oben rechts (linke oder rechte Maustaste) ebenfalls einstellen kann.
- Ähnliches für die Zielwahl: Die meisten werden direkt das Dropdown benutzen (dank der Ordnerstruktur - danke dafür!) also warum noch eine Manuelle Zielwahl + FillType anzeigen?

**Comment by haamic** [comment]
Ja würde reichen. Sind wir 2 wirklich die einzigen die sich das wünschen? 
Um Button zu sparen, wäre ein extra keybinding hilfreich. Das mit dem +- ist mir auch aufgefallen, das man die eigentlich nicht braucht.
Oder noch besser, ohne Button und binding, die Ziele tauschen sich anhand der Modi selber, so wie es richtig ist. Ein Abladeziel ist nun mal ein Abladeziel und sollte auch dort bleiben wo es je nach Modus hingehört, wenn man von abholen+Abliefern auf abholen wechselt. 
wieso ist der verwirrende Wechsel eigentlich vorhanden? Zwar wurde das durch die neuen Bildchen Etwas entwirrt, aber worin besteht der Sinn? Ist keine Kritik, möchte nur verstehen warum. 
Gruß Micha

**Comment by haamic** [comment]
@Stephan-S 
what about this now? is it solved as keybinding or does the HUD automatically exchange targets with each other?

@Stephan-S 
wie siehts damit inzwischen aus? wird das als keybinding gelöst oder tauschen sich im HUD die Ziele miteinander automatisch?

**Comment by haamic** [comment]
@Stephan-S 
durch Zufall entdeckt, das es nun geht, Danke für die Umsetzung

**Comment by vertigoogle** [comment]
@Stephan-S 
Danke ebenfalls für die Umsetzung!
