### ISSUE TITLE
DebugMode an/Aus?

### ISSUE THREAD

**Issue by geo-luchs** [Stephan-S/FS19_AutoDrive#546]
Hallo Stephan

ich habe gesucht, und gesucht, aber es nicht geschafft, den Debugmode für AD zu aktivieren.
Momentan spiel ich nur über Tastatur.
In deiner moddesc.xml ist zwar was drin, über nur für Gamepad.
Un über die Belegungseinstellungen im Spiel finde ich keine Möglichkeit, dem ActivateDebug eine Taste zuzuordnen.

Kannst Du mir nen kurzen Hint geben, wo ich den DeubgMode einschalten kann, um mehr Infos im Logfile zu sehen?

Gruß
Carsten

**Comment by Stephan-S** [comment]
Servus,
der Debug Modus den du im Code gefunden hast, ist der 'Edit Mode' also der den du mit dem Ausrufezeichen aktivierst.
Es gibt keinen dedizierten Debug Modus in Autodrive der vergleichbar wäre mit dem CP Modus.

Der Name hat sich eher durch 'Legacy' Code seit der aller ersten LS17 Version durchgezogen :-)
