### ISSUE TITLE
Ordnerstruktur

### ISSUE THREAD

**Issue by Rheingauner** [Stephan-S/FS19_AutoDrive#548]
Hallo Stephan,
Ich möchte mich zunächst bei Dir für die tolle Arbeit bedanken! Im 17er hab ich nur CP genutzt & von AD nur mal gelesen, aber nicht angeguckt. Das war ein Fehler ;-) Ich bin begeistert.

Ich habe ein Problem mit der Reihenfolge meiner Ordner. Ich hab beim Erstellen der Ordner berücksichtigt, dass der zuerst erstellte ganz oben (nach dem "Standard" Ordner) steht und jeder weitere dann darunter.
Nachdem ich meine Zielpunkte zugeordnet hab, verändert sich die Reihenfolge. Außerdem ist mir unklar, was das erste Dreieck nach dem Ordnernamen für eine Funktion hat. Das andere (zum ausklappen des Ordners) ist mir bewusst.

![AD-Ordner](https://user-images.githubusercontent.com/55962209/65840519-887c1980-e31a-11e9-836f-87dcefe1d60d.png)

Grüße

**Comment by Fuzzy86** [comment]
Hy! Der 1. Pfeil zieht dir den ausgewählten Zielpunkt in den Ordner. Du musst dazu nur den Zielpunkt den du verschieben willst im normalen Überführungs Modus auswählen und dann auf dem Pfeil neben den Ordner drücken worin du das haben willst. 

Lg

**Comment by Stephan-S** [comment]
> Nachdem ich meine Zielpunkte zugeordnet hab, verändert sich die Reihenfolge.

Hey, was genau meinst du damit? Welche Reihenfolge ändert sich?
P.S.: Im der aktuellsten source Version ordne ich die Ordner jetzt alphabetisch. Nur der Standard Ordner bleibt ganz oben

**Comment by Rheingauner** [comment]
Hi, also ich habe zuerst den Ordner "01 Hof" dann den "02 Felder" usw. erstellt. Ich dachte die werden dann in der Reihenfolge angezeigt, in der sie erstellt wurden. Das ist bei mir zumindest nicht so. Ich hab auch mal alle Ordner gelöscht und neu gemacht und die Zielpunkte erneut in die Ordner geschoben, aber das hat leider nicht geklappt.
Ne alphabetische Sortierung klingt super. Sollte dann ja auch mit Zahlen funktionieren. 👍
