### ISSUE TITLE
Fehlermeldung beim erstellen von Kurs auf der Multimap

### ISSUE THREAD

**Issue by BauerEnni** [Stephan-S/FS19_AutoDrive#549]
Hallo 

Und zwar folgendes...

Ich habe bzw die MultiMap im Singleplayer,und seit dem Wochenende(mitn Kumpel auch im Multiplayer,mit extra gemietenden Server)...

Nun folgendes Problem.Im Singleplayer funktioniert der AutoDrive sehr gut.Nur im Multiplayer,geht er kurz,und dann garnet mehr.Und er schmeisst mir dann folgende Fehlermeldung in die Log...

Games/FarmingSimulator2019/mods/FS19_AutoDrive/scripts/HudElements/PullDownList.lua:355: bad argument #1 to 'insert' (table expected, got nil)...

An was könnte das liegen?

Info!! Hab die aktuellste Version vom AutoDrive druff.

Wäre cool wenn mir da einer eventuell helfen könnte.

Lg Enni

**Comment by Bandesss** [comment]
Also wir Spielen auch auf der Multimap.
Fehler, gibt es erst wenn ich versuche die Ordner zu benutzen.
Aktuelle Version 1.5.9
Gruß 
Welche Version nutzt du ? Versuch mal 1.5.6
