### ISSUE TITLE
Drescher abtanken Modus

### ISSUE THREAD

**Issue by Chlous11** [Stephan-S/FS19_AutoDrive#55]
erstmal Danke für die Tolle Sache.
Ich möchte den Drescher abtanken aber der Abfahrer registriert sich nicht.Geht das nur auf den Originalen MAP`s ?Ich spiele auf der NF-Marsch.

**Comment by Merlin110480** [comment]
Bei mir ging es erst mit der 1.0.0.8 richtig, davor geht es nur mit der Englischen version wenn ich das richtig verstanden habe.

**Comment by masurpilami** [comment]
Das Feature ist toll, habe es ohne Erklärung sofort verstanden und gleich getestet.
2 Dinge sind mir aufgefallen:
1. Verkehr bleibt im Umkreis des Feldes stehen weil ein Helfer fährt. Führt zu gewaltigen Staus ;)
2. Traktor fährt erst bei 100% vom Drescher Richtung Drescher, ist hier geplant dass er bereits ab 80% dorthin fährt?

**Comment by Stephan-S** [comment]
Hey, schön das der Modus dann doch nicht ganz unverständlich ist.
Zu 1.: Da AutoDrive keinen KI-Verkehr erkennt, habe ich diesen immer ausgeschaltet. Aber ich verstehe nicht ganz den Zusammenhang. Das der Verkehr anhält ist doch unabhängig von AutoDrive. Oder verstehe ich dich da falsch?

Zu 2.: Da die Wegfindung derzeit zu einem festen Zielpunkt führt und nicht etwa einen fahrenden Drescher 'begleitet', ist das noch nicht in Arbeit. Ich bin schon mal froh wenn es in der Form stabil läuft. Und bis dahin möchte ich die Strategien noch etwas feinschleifen, bevor da an erweiterte Funktionen gedacht wird

**Comment by masurpilami** [comment]
Zu 1 als Erklärung.
Wenn ein normaler Helfer Richtung Strasse kommt dann bleiben die Autos stehen damit der Helfer wenden kann. Das ist im Spiel standard.
Wenn nun der Traktor mit AutoDrive im "Drescher abtanken Modus" unterwegs ist und auf den vollen Drescher wartet. Dann steht in großem Umkreis der Verkehr still ;)
So weit ich das verstehe benutzt AutoDrive ja den "Helfer", zumindest wird ja der Lohn bezahlt und irgendwie dürfte in dem Modus der AI-Verkehr den Helfer sehr großflächig erkennen.
Keine Ahnung ob du das nachstellen kannst oder willst aber Drescher ist im Helfermodus auf Feld 20 in Felsbrunn unterwegs. AutoDrive Traktor steht mittig zwischen Feld 20 und 21 und wartet. Verkehr steht still im gesamten Bereich Feld 20.

**Comment by Stephan-S** [comment]
Darauf habe ich erstmal keinen Einfluss, bzw. habe ich mich noch nicht mit beschäftigt.
Solange der KI-Verkehr allerdings von AutoDrive ignoriert und nicht erkannt wird, werde ich dem Ganzen nicht nachgehen, da meine Empfehlung ganz klar ist, dem Verkehr und am Besten auch den Zug (LocoStop) auszuschalten. Ich hoffe das ist verständlich :-)
