### ISSUE TITLE
Translation to Polish language

### ISSUE THREAD

**Issue by criss20ster** [Stephan-S/FS19_AutoDrive#550]
Hi Stefan. I have a question, could I translate your mod into Polish? Because the great thing is with this modem but there is no Polish

**Comment by Stephan-S** [comment]
Hey,
that would be great!
You can just take one of the already available translations and create a new one from it and then upload it here :-)

Here is the link to the other translations in the mod:
https://github.com/Stephan-S/FS19_AutoDrive/tree/master/FS19_AutoDrive/translations

**Comment by criss20ster** [comment]
And how do I chew this xml file. Sorry to ask, but I didn't cheat on my git hub and I don't know how to do it without mixing it up

**Comment by Stephan-S** [comment]
Thank you for your contribution!
