### ISSUE TITLE
Infinite loading screen when using Courseplay and AutoDrive

### ISSUE THREAD

**Issue by Bravo21Niner** [Stephan-S/FS19_AutoDrive#551]
Hey guys, i've ran into an issue using both Courseplay and Autodrive at the same time.  If I load up one or the other on a new map, I can load in just fine.  But if I have both mods selected, the loading screen loops infinitely.  The longest i've waited was 38 minutes, and the game doesn't respond to any inputs.  I have to Alt F4 out every time I try it.  

https://gist.github.com/Bravo21Niner/4faf6c27a6ad195b1e2a4cd01b81a133#file-log-txt

**Comment by andejx** [comment]
"Load mod: FS19_AutoDrive (Version: 1.0.1.9)"
that's an OLD version of autodrive. try a newer version.

**Comment by Bravo21Niner** [comment]
That's the current version from the in game mod hub, I've tried multiple times to get the Github version installed but it never works.

**Comment by Woife1** [comment]
The easy way is go on https://github.com/Stephan-S/FS19_AutoDrive/releases
download the 1.0.5.7 or 1.0.5.8 (both stable testet, just click on the version)
take the .zip in your mods folder 
normaly:
Windows:
... / my documents / My Games / FarmingSimulator2019 / mods
or
... / documents / My Games / FarmingSimulator2019 / mods
than it works
it is the same way like the install of courseplay

**Comment by vertigoogle** [comment]
@Bravo21Niner Listen to the posts please. The version on Modhub is outdated and will not work in any way with courseplay. Nor am I sure if it will work with the actual version of FS19.

@Stephan-S You should make a sticky for that deprecated version in modhub ;)
Cairo Amun could make a tape with the same answer like mine every episode in yt 😄

**Comment by Bravo21Niner** [comment]
@vertigoogle that version was from the in game mods section. It was working perfectly fine up until I updated Courseplay.  Updated Autodrive to 1.0.5.8 and it's all working fine now.

Thanks for all the help everyone :D
