### ISSUE TITLE
AD Findet den weg nicht

### ISSUE THREAD

**Issue by RudiBergfeld** [Stephan-S/FS19_AutoDrive#552]
ich habe die multimap genommen und das Entsprechende AD Konfig genommen nach einger Zeit findet AD fahrer keinen Weg mehr was mache ich Falsch. anbei die Log vom Spiel
[log.txt](https://github.com/Stephan-S/FS19_AutoDrive/files/3676432/log.txt)

**Comment by Bandesss** [comment]
Hast du sie mal neu berechnen lassen?

**Comment by RudiBergfeld** [comment]
Auch an der Hauptstrecke ging es nicht aber danke für den hinweis. Vertigoogle ich habe dein anmerkungen befolgt kann es aber erst nacher testen meinst du diese datei  ich kann sie leider nicht anhängen send sie per email

**Comment by rmn18** [comment]
@vertigoogle eine Map nur im Modordner oder ? Weil hab es schon gehabt 3 Maps im Modordner und mit mal hat sich was gebisssen mit einer Map auf der ich grade aktiv gespielt hatte .

**Comment by RudiBergfeld** [comment]
Ich habe Euren Rat befolgt und habe nur noch 1 Map im Ordner und naja machmal findet der Abfahrer das Ziel und manch mal nicht 
[log.txt](https://github.com/Stephan-S/FS19_AutoDrive/files/3678102/log.txt) mein Log von Heute abend  ich hab die neuste Version des AD s 
Das Neuste ist das er mir in der Raffenerin sagt das dor ein Strohlager ist 
![fsScreen_2019_10_01_20_05_26](https://user-images.githubusercontent.com/10323527/65992961-8f2c9d00-e490-11e9-805f-c55d20b03f6d.png)
Was nun

**Comment by Woife1** [comment]
es kann sein das sich gerade ein Fahrer an deinem Strohlager ein bischen bugged

**Comment by vertigoogle** [comment]
Ja, das gleiche Problem habe ich auf der Multimap auch. Nur mit Mais-Silage 😆 
Schuld ist ein Fahrer unter dem Überladerohr des Silagelagers, der auf Nachschub wartet und virtuell alle paar ms "R" drückt. Der Befehl ist anscheinend global sichtbar, sodass alle Fahrzeuge dann versuchen von diesem Trigger zu laden, wenn ich manuell überladen möchte. Egal wo sie stehen.

Entweder den wartenden Fahrer am Strohlager entfernen oder den Trigger an der Raffinerie genauer treffen.
