### ISSUE TITLE
V 1.0.5.9 Drescher abtanken funktioniert nicht mehr

### ISSUE THREAD

**Issue by Eelijah666** [Stephan-S/FS19_AutoDrive#553]
Hello!

Gerade auf die V1.0.5.9 upgedatet aber leider funktioniert damit das Drescher abtanken nicht mehr, der Abtanker fährt einfach mit 8 km/h gerade übers Feld. Neu berechnen hat nichts gebracht! 

Zurück auf die V 1.0.5.8 und alles läuft wieder top!

lG
Chris

**Comment by vertigoogle** [comment]
In welchem Modus versuchst du abzutanken? Früher rufen oder Standard?

**Comment by Bandesss** [comment]
Bei mir kommt er mit dem LKW, bleiibt aber ca 50 cm zu weite weg stehen.

**Comment by Eelijah666** [comment]
Früher rufen "Nein"

**Comment by Stephan-S** [comment]
Hey, bitte auf die 1.0.6.0 updaten :-)

**Comment by Eelijah666** [comment]
Funkt auch nicht so recht, beim ersten mal fuhr der Drescher nicht mehr los nach dem Abtanken, beim zweiten mal fand der Traktor nicht unters Rohr sonder stand am Drescher an.

lG

**Comment by C0pasalli0r** [comment]
Hallo  das Problem hab/hatte ich auch , das liegt am Drescher bzw Traktor/Kipper Combo . Sie fahren nicht weit genug vor , damit das Rohr ausfährt bei CP oder Helfer Fahrer .  
Lange Deichsel und Überladerohr erschweren das ganze . Die Trigger der Drescher sind bei jedem anders .
![fsScreen_2019_10_05_20_34_47](https://user-images.githubusercontent.com/56047951/66259568-c82b8100-e7b2-11e9-99d8-39978aacf178.png)
![fsScreen_2019_10_05_16_59_15](https://user-images.githubusercontent.com/56047951/66259576-d5e10680-e7b2-11e9-90de-455cf81b1ce7.png)
