### ISSUE TITLE
Suggestions for longer trailers 

### ISSUE THREAD

**Issue by Tadeloach** [Stephan-S/FS19_AutoDrive#554]
When I use a trailer like the Lodeking, I have an issue with it lining up with the combine in offload and delivery  mode. If the truck is approaching from behind all is well, but if coming from in front and having to make a turn, the trailer is turned away from the pipe and offload doesn't work. Any ideas?

**Comment by raxtor** [comment]
Using overloader like Auger wagon for long trailers? Also try to adjust front/back offset for unloader..

**Comment by Tadeloach** [comment]
Overloaded would defeat the purpose in my mind, but we you say the offsets,
which way do you suggest changing them?

**Comment by raxtor** [comment]
I assume plus values, u need get him a bit to front imho.. u can set 0-5m there, not sure if it helps, but you can try...

**Comment by Tadeloach** [comment]
I can try that tomorrow. If he would drive further behind then turn it
wouldn't be an issue, but I don't know how to make him do it. I thought of
having course play run that part, but the mode 2 is still a little buggy so
I don't know. AD works great as long as it isn't a long trailer or you
aren't offloading the potatoe harvesters.

**Comment by raxtor** [comment]
Its seems @Stephan-S will have to fix it in script for wider turn.. try to play with offset for this specific situation, it can help a little but maybe some screenshot would help for better imagination.

**Comment by Tadeloach** [comment]
I will try the offsets and get a screen shot the next time I can play.

**Comment by Tadeloach** [comment]
First Shot is 0 Offset
![image](https://user-images.githubusercontent.com/56048034/66003757-9772e100-e46c-11e9-91fc-75f48011480a.png)
Second: Positive offset of 3m
![image](https://user-images.githubusercontent.com/56048034/66003835-ca1cd980-e46c-11e9-96a5-dc24778971c4.png)
Third is Negative offset of 3m
![image](https://user-images.githubusercontent.com/56048034/66003901-f9cbe180-e46c-11e9-968a-0221836389cc.png)

Option 3 is obviously better, but how do I fill up the back hopper if I can't line it up?  I am going to use a trailer with a single hopper, but I think this is something that should be addressed for other users.

**Comment by Woife1** [comment]
2. hopper should get filled after 1. hopper is full.
or I missunderstand an update a few days ago

**Comment by raxtor** [comment]
correct, but he is not able fill 1st bin when truck is coming from front direction...

**Comment by Woife1** [comment]
you can try the last stable version 1.0.5.7 if it works then with the long trailer
i had normaly only the krampe trailer on a truck and it works to 1.0.5.8

**Comment by Tadeloach** [comment]
OK, I will try 1.0.5.7 in the morning and see how it goes.

**Comment by Tadeloach** [comment]
I can't remember which version I was on. I'll make sure and try 1.0.5.7.

**Comment by Woife1** [comment]
if 1.0.5.7 didn't work go up to 5.8 and after that the 6.0 just testing 
all versions newer than 1.0.5.7 are all in alpha, they may work well but could have a lot of bugs

**Comment by Woife1** [comment]
if it works in no version well than must Stephan works on it ;)

**Comment by Tadeloach** [comment]
Roger that, I'll give it a go and let you all know.

**Comment by Tadeloach** [comment]
Here are screen shots from the approaches VS. Each version.
1.0.5.7
![image](https://user-images.githubusercontent.com/56048034/66046026-849ef180-e4ea-11e9-907b-640609952d4b.png)

1.0.5.8
![image](https://user-images.githubusercontent.com/56048034/66046675-deec8200-e4eb-11e9-925a-2323f81db34e.png)

1.0.5.9
![image](https://user-images.githubusercontent.com/56048034/66046935-6639f580-e4ec-11e9-94ff-7b5b8e080233.png)

1.0.6.0
![image](https://user-images.githubusercontent.com/56048034/66047356-3e975d00-e4ed-11e9-8e2c-a0f3fa283be5.png)


So I can see I need to come up to at least 1.0.5.8.  I will try some more and see If I have any other issues.

**Comment by Tadeloach** [comment]
@Woife1 
So I decided to do an infield approach from close to the fruit in 1.0.6.0 and this is what I got
![image](https://user-images.githubusercontent.com/56048034/66048369-042ebf80-e4ef-11e9-9e87-84851833f3b2.png)
He is still trying to turn around and line up correctly but is in traffic even though he is offloading.

Tried same thing in 1.0.5.9 and it was way better.  Lined up, and stopped!  Think I am going to play on 1.0.5.9 for now.
![image](https://user-images.githubusercontent.com/56048034/66048837-e150db00-e4ef-11e9-8e1f-5d118f78101e.png)

**Comment by raxtor** [comment]
> Here are screen shots from the approaches VS. Each version.
> 1.0.5.7
> ![image](https://user-images.githubusercontent.com/56048034/66046026-849ef180-e4ea-11e9-907b-640609952d4b.png)
> 
> 1.0.5.8
> ![image](https://user-images.githubusercontent.com/56048034/66046675-deec8200-e4eb-11e9-925a-2323f81db34e.png)
> 
> 1.0.5.9
> ![image](https://user-images.githubusercontent.com/56048034/66046935-6639f580-e4ec-11e9-94ff-7b5b8e080233.png)
> 
> 1.0.6.0
> ![image](https://user-images.githubusercontent.com/56048034/66046935-6639f580-e4ec-11e9-94ff-7b5b8e080233.png)
> 
> So I can see I need to come up to at least 1.0.5.8. I will try some more and see If I have any other issues.

1.0.5.8/1.0.5.9/1.0.6.0 seems like same pictures? Have you pre-call unloader active or off?

**Comment by Tadeloach** [comment]
@raxtor,  They are different, just all lined up correctly.   Pre call is off.  It hasn't worked well for me yet.  But if you notice below, 1.0.6.0 flubbed an infield approach from closer to the fruit where 1.0.5.9 unloaded it like I would have instead of looping, just ran right under the pipe and stopped.

> @Woife1
> So I decided to do an infield approach from close to the fruit in 1.0.6.0 and this is what I got
> ![image](https://user-images.githubusercontent.com/56048034/66048369-042ebf80-e4ef-11e9-9e87-84851833f3b2.png)
> He is still trying to turn around and line up correctly but is in traffic even though he is offloading.
> 
> Tried same thing in 1.0.5.9 and it was way better. Lined up, and stopped! Think I am going to play on 1.0.5.9 for now.
> ![image](https://user-images.githubusercontent.com/56048034/66048837-e150db00-e4ef-11e9-8e1f-5d118f78101e.png)

**Comment by raxtor** [comment]
I know 1.0.6.0 has troubles... I am testing active unloading for every patch, u can join here https://github.com/Stephan-S/FS19_AutoDrive/issues/542
Are you sure about pictures because all 3 has same time and same fill level... its strange for 3 different pictures..

**Comment by Tadeloach** [comment]
Yes, I was reloading the same save game with the different ad releases so I had same field position etc and was taking a screen shot.

> I know 1.0.6.0 has troubles... I am testing active unloading for every patch, u can join here #542
> Are you sure about pictures because all 3 has same time and same fill level... its strange for 3 different pictures..

**Comment by Tadeloach** [comment]
Here is a bad lineup with 1.0.5.9.  This is a small field, but this is also when most unloaders have an issue, when the combine is near the edge of the field.
![image](https://user-images.githubusercontent.com/56048034/66052567-6dfe9780-e4f6-11e9-86ce-fcc9f2512051.png)

However I changed the offsets in this Tractor's menu to 0 on both pipe and trailer and it lined up.  All new tractors for Contracts line up to my Trucks offsets which screw them up.

**Comment by raxtor** [comment]
Its just in 1.0.5.9 version.. 1.0.6.0 is working again with previous offsets. No idea why it was again changed, because 0m offset in 1.0.5.9 worked well...

**Comment by Tadeloach** [comment]
I'm marking as closed. This seems to be working better now.
