### ISSUE TITLE
V 1.0.5.8 wiederbefüllen von Düngemaschienen

### ISSUE THREAD

**Issue by Astanorr** [Stephan-S/FS19_AutoDrive#555]
Hallo, 

ich habe folgendes Problem bei mir erkannt. Jedesmal wenn ich mit CP einen Helfer das Feld Düngen lasse und ihn mit AD wieder befüllen lassen will,  fährt er im Modus "Abholen" nur einmal im Kreis zu meinem Startpunkt am Feld, anstatt wie gewünscht zum Trigger um sich dort Dünger/Kalk zu holen. 

Ich kann  mir das Problem aktuell nicht erklären, vielleicht gibt es mehrere mit diesem Problem?

Grüße Asta 0/

**Comment by Woife1** [comment]
hast du auch den richtigen Modus in AD ausgewählt? Abholen 
die Ziele richtig zugeordnet? (danke an Stephan für die richtigen Bilder daneben ;) )
auch in CP Dünger als zu ladendes Gut eingestellt? Dünger Flüssigdünger Pflanzenschutzmittel ...

**Comment by Astanorr** [comment]
Ich habe bei AD den Modus Abholen zugeordnet, oben steht bei mir das Feld unten die Verkaufsstation für den Dünger und ja bei CP habe ich auch den Dünger eingestellt. Wenn er zum auffüllen fahren will steuert er aber immer gleich wieder den Feldpunkt an, also der obere Punkt. Danach fährt er wieder auf´s Feld und will neu beginnen, da er aber leer ist fängt er wieder von vorne an.

**Comment by Woife1** [comment]
mhh...
stop mal alle Helfer (vorallem die von AD) lass alle Kurse neu berechnen
und starte das Spiel neu (kann sein das AD den Trigger nicht drin hat)

bei mir fährt er zumindest zum abholen (1.0.6.0 Sähmaschine nur hat nich geladen da das Silo leer war)

**Comment by geo-luchs** [comment]
Welche Saatmaschine hast du dran? 
Es gibt noch ein anderes Issue, wo ich detailliert Infos reingeschrieben habe. U.a. dass ich Probleme mit der Saatmaschine Ceres  habe.
Da will er auch nicht den Befülltrigger anfahren.

**Comment by geo-luchs** [comment]
Welche Saatmaschine benutzt du?

Ein ähnliches Verhalten habe ich bei der Saatmaschine Ceres

**Comment by Astanorr** [comment]
Naja ich habe einen neuen Spielstand gestartet um Seasons in Verbindung mit CP und AD zu testen, bin also auf der standart EU Map und benutze aktuell die billigste Amazone Sähmaschiene und den Kleinen Düngstreuer aus dem Modcontest- Pack also die Spipma RN 610 Antek.

**Comment by Astanorr** [comment]
@Woife1 ich habe jetzt auch über Nacht sogra meinen PC neu gestartet und werde schauen ob es geholfen hat ;-)

**Comment by Astanorr** [comment]
Aktuell keine Veränderung... ich kann mir das Problem nicht erklären.^^

**Comment by Astanorr** [comment]
Also naschdem ich ein wenig rumgetestet habe, fand ich heraus, dass es mit der Feldspritze wohl klappt nur nicht mit dem/der Düngestreuer/Sähmaschiene.

**Comment by Woife1** [comment]
es kann sein das der Düngerstreuer einfach zu klein ist 
einzigste Möglichkeit die log.txt nach einem Fehler durchsuchen 
wenn Fehlerfrei dann funktionieren die Kleingeräte nicht mit AD

**Comment by geo-luchs** [comment]
@Woife1 zu klein?  Du meinst, das Einfüllfeld an der Maschine? Oder sie Ladekapazität?

Das Problem ist ja, dass er gar nicht erst zum Ladepunkt fährt.
Ich hab das Problem ja auch mit der Kombisaatnaschine Ceres Master 3570.

Gab mir einen einfachen Testkreis ohne CP aufgebaut.

Nur AD.  Saatgutbeladung, düngerbeladung, dahinter der AD Zielpunkt zum beladen.
Und auf dem Kreis einen weiteren Wegpunkt für's Feld.

Alle Maschinen sind leer.
Bei einigen Maschinen fährt er immer beim Einschalten von AD (abholen modus)  zum beladungszuelpunkt.

Bei der Ceres Master3570 aber immer zum Feldwegpunkt. 
Das könnte man nochmal mit dem Düngerstreuer testen.

Ich hab das Gefühl das @Stephan-S  beim Einschalten von AD die Maschine überprüft  und anhand irgendeines Merkmals entscheidet, ob der Beladepunkt angesteuert werden muss. Z.B. maschine<voll
Und vielleicht klappt das bei einigen Geräten nicht.

Ich schau mal, ob ich das heute Nachmittag im Code finden kann.

**Comment by Woife1** [comment]
Ich meinte die Ladekapazität
in der 1.0.5.8 gabs was für kleine Füllvolumen (Fix for small fill units.)

evtl ist in der Füllstandsprüfung das fehlende Volumen ausschlaggebend und nicht die Prozente der Geräte.
das genaue kann wohl nur Stephan beantworten

**Comment by geo-luchs** [comment]
@Astanorr Wo genau kann ich die sipma rn 610 antek downloaden? Finde sie nirgends

**Comment by Woife1** [comment]
die gibts im offiziellem Modhub in einem Pack
https://farming-simulator.com/mod.php?lang=de&country=de&mod_id=135314&title=fs2019

**Comment by geo-luchs** [comment]
Danke, ich hatte immer direkt nach dem Namen gesucht, und nichts gefunden.
