### ISSUE TITLE
Help about load/seve

### ISSUE THREAD

**Issue by MerlinCheater** [Stephan-S/FS19_AutoDrive#556]
How to save and load the roude frome old game to new with same map.

**Comment by raxtor** [comment]
- go to savegame folder and copy and store your AutoDrive_mapName_config.xml somewhere
- make new game and save it
- copy your stored AutoDrive_mapName_config.xml to new savegame and load savegame

**Comment by MerlinCheater** [comment]
thx

**Comment by Stephan-S** [comment]
You can also click the save icon in the HUD which creates a backup of your courses in the export folder.
On your new game you can bind a key to "Import courses" in your keybindings settings of FS and then click this to import the course which you first transferred manually from the export to the import folder^^ Yeah sorry not that convenient now that I descive it out loud :D
