### ISSUE TITLE
Mauszeiger im Multiplayer

### ISSUE THREAD

**Issue by Onkel2000** [Stephan-S/FS19_AutoDrive#559]
Hallo,  mir ist aufgefallen das der Mauszeiger im Multiplayer verschwindet wenn der Mitspieler in ein anderes Fahrzeug switcht. Das ist ziemlich anstrengend. Bin mir nicht sicher ob es an AD liegt, denke aber schon. 

Außerdem ist läuft es im Multiplayer echt gut wenn ich selbst ein Spiel hoste. Auf einem gemieteten Server fängt es aber schnell an an zu stottern, mit dem selben Spielstand. Der Mod zeigt auch "fehler" an.

![Screenshot_2019-10-02 Farming Simulator Dedicated Server Mod](https://user-images.githubusercontent.com/53871930/66078563-899f8780-e562-11e9-88af-335333fd497c.png)

**Comment by Stephan-S** [comment]
Hey, die Warnungen kann man entspannt ignorieren und liegen nur an den mitgelieferten Kursen im Mod selber. Haben keinerlei Auswirkungen.
Wegen dem Mauszeiger, das muss ich mir mal anschauen.

**Comment by Onkel2000** [comment]
> 
> 
> Hey, die Warnungen kann man entspannt ignorieren und liegen nur an den mitgelieferten Kursen im Mod selber. Haben keinerlei Auswirkungen.
> Wegen dem Mauszeiger, das muss ich mir mal anschauen.

Danke, der Mauszeiger verschwindet nicht mehr. Jetzt ist es das dropdown Menü was zugeht sobald einer switcht.

Vielen Dank schonmal. Machst wirklich eine tolle Arbeit :)

**Comment by Caliban2017** [comment]
Das ist mir ebenfalls aufgefallen. Ich hatte ja vor einiger Zeit schon mal einen Fehler gemeldet, dass der Mauszeiger immer erscheint wenn andere Spieler auf dem Server AD öffnen. Es scheint tatsächlich auch anders herum der Fall zu sein, dass der Cursor verschwindet wenn ein anderer Spieler etwas macht. Etwas auffällig daran - er verschwindet auch in anderen Menüs wie z.B. Tierübersicht oder im Shop.... geht man dann einmal zurück ins Spiel und wieder in den Shop ist der Cursor wieder da.

**Comment by Onkel2000** [comment]
> 
> 
> Das ist mir ebenfalls aufgefallen. Ich hatte ja vor einiger Zeit schon mal einen Fehler gemeldet, dass der Mauszeiger immer erscheint wenn andere Spieler auf dem Server AD öffnen. Es scheint tatsächlich auch anders herum der Fall zu sein, dass der Cursor verschwindet wenn ein anderer Spieler etwas macht. Etwas auffällig daran - er verschwindet auch in anderen Menüs wie z.B. Tierübersicht oder im Shop.... geht man dann einmal zurück ins Spiel und wieder in den Shop ist der Cursor wieder da.

Nach dem Fix heute, bleibt er zumindest da. nur noch das dropdown menü geht immer zu wenn jemand switcht. Mir ist auch aufgefallen das wenn der Mauszeiger aktiv ist und man aus dem Fahrzeug geht, spinnt die Kamera, sobald man wieder in ein Fahrzeugt geht und denn Mauszeiger deaktiviert gehts normal mit der Kamera weiter. Wichtiger  empfinde ich es aber mit dem dropdown menü.

**Comment by Onkel2000** [comment]
Hey Stephan, habe mir gerade die neuste Version geholt und festgestellt das nun alles funktioniert was mir auf gefallen war. Echt klasse von dir.

Vielen Dank.
