### ISSUE TITLE
MP 1.0.0.8 kann keine Haltepunkte mehr erstellen

### ISSUE THREAD

**Issue by Merlin110480** [Stephan-S/FS19_AutoDrive#56]
Hallo Stephan,

Hab heute den Tag mit Testen verbracht, dabei ist mir aufgefallen das ich in der Version 1.0.0.8
auf dem MP keine Haltepunkte mehr erstellen kann.
Der Button hat keine Funktion mehr.
Im SP gehts ohne Probleme.

gruß Christian

PS: Hättest du gerne pro Bug/FR ein Issue oder einfach alles was zu dem Zeitpunkt aktuell ist?

**Comment by Stephan-S** [comment]
Am liebsten pro Bug/FR ein eigenes, da dann die Gefahr sehr gering ist, das ich versehentlich etwas überlese bzw. voreilig schließe wenn ich einen commit hochlade.
Danke :-)

Ah achso, ja. Das war ein Bug. Ich habs eben auch gemerkt :D Patch kommt heute noch. Sorry dafür :-)
