### ISSUE TITLE
HUD verschwindet im MP wenn Ordnermodus aktiviert wird

### ISSUE THREAD

**Issue by Moitzbert** [Stephan-S/FS19_AutoDrive#560]
Nachdem ich bereits ein paar Wegpunkte per Autodrive angelegt habe und das mit der Zeit ziemlich unübersichtlich geworden ist, wollte ich jetzt ein paar ordner erstellen. Wenn ich jedoch den Ordnermodus einschalte verschwindet beim nächsten Klicken der HUD vom AD und das Hilfefenster links oben. Wenn ich wieder zurück wechsle funktioniert wieder alles. 
Kann mir jemand sagen was ich falsch mache ? Hätte ich den Ordnermodus zu beginn aktivieren müssen ? 
Ich verwende den Release: 1.0.6.0

Mfg Christof

**Comment by Stephan-S** [comment]
Hey, für einen temporären Bugfix schau doch mal die #562 an, da gibt es eine Lösung von @GitTomahawk
Ich setz mich aber heute mal dran und teste den MP selber und schau es mir an.

**Comment by Caliban2017** [comment]
Kann ich bestätigen, hatte vor einigen Tagen ja den gleichen Fehler gemeldet hier. Habe den Fix von GutTomahawk getestet und eingebaut ins Script und haben es gestern Abend getestet und das HUD bleibt nun beim Mitspieler vorhanden...

**Comment by GitTomahawk** [comment]
Im Release 1.0.6.1 funktionierts bei mir jezt einwandfrei
