### ISSUE TITLE
Abfahrer fährt nicht bei eingestelltem Füllstand los bei manueller Beladung

### ISSUE THREAD

**Issue by ThisPf** [Stephan-S/FS19_AutoDrive#561]
Hallo zusammen

Ich habe einen Abfahrer eingerichtet, der am Feldrand mit dem Überladewagen befüllt wird. Ich wollte einstellen, dass er ab einer gewissen Füllmenge los fährt, wie dies ja möglich ist, wenn man mit AD direkt den Drescher abtankt. Geht das im Modus Abholen und Abliefern nicht oder übersehe ich diese Funktion?
Das Problem ist, dass der Abfahrer z.B. zu 99% voll ist aber immer noch wartet. Dann kommt der volle Überladewagen und kann kaum was überladen. Schon habe ich einen vollen Drescher auf dem Feld stehen, der nicht abgetankt werden kann.

Version 1.0.5.8

Grüsse

**Comment by Woife1** [comment]
Im Modus Abholen und Abliefern wird immer bis 100% gefüllt (ist auch dafür gedacht sachen aus einem Silo zu verteilen)

der Drescher Abtank Modus müsste auch funktionieren dafür ist auch die Einstellung abfahren ab X%

**Comment by ThisPf** [comment]
Meinst du, dass wenn der Abfahrer im Drescher Abtank Modus am Feldrand steht, ich diesen trotzdem mit dem Überladewagen befüllen kann und er dann bei den eingestellten x% los fährt?

**Comment by Stephan-S** [comment]
Hey, eigentlich sollte das so funktionieren aber da hat sich scheinbar in einer der letzten Versionen ein Fehler eingeschlichen. Ich kümmere mich drum
