### ISSUE TITLE
Dialogboxen für Zielauswahl funktionieren nicht mehr

### ISSUE THREAD

**Issue by SledgeHammer75** [Stephan-S/FS19_AutoDrive#563]
Hallo Stephan, 

bei der aktuellen Version funktioniert die Zielauswahl per Dialogbox nicht mehr (die Dialogbox erscheint gar nicht, betroffen sind sowohl Start und Ende). Per Tastatur kann ich die Ziele durchschalten.

Die Dialogbox für die Auswahl des Tranportgutes funktioniert.

**Comment by kleinerblauer** [comment]
Hallo Stephan,
ich kann die Aussage von SledgeHammer75 bestätigen, auch bei mir funktioniert es nicht mehr.

**Comment by Stephan-S** [comment]
Hey, habe gerade einen Fix hochgeladen der das Problem für euch beheben sollte.
Release Version werde ich nach ein paar anderen Bugfixes wieder zusammen packen
