### ISSUE TITLE
Unload combine mode unsuspectingly cancel

### ISSUE THREAD

**Issue by Martinnygaard** [Stephan-S/FS19_AutoDrive#566]
Hi,

Due to CP not ready with their new mode two, i have started to use AD instead - and it does work great.

But some time ago (not long) is started to "cancel the job" unsuspectingly and leave the tractor in the middle of the field, without AD on. (There is no status - It is not saying "waiting for combine", "driving to combine" or anything like that.) 
At this point the combine(CP controlled) is full and waiting for the unloader.

As soon as i press the AD start button, it goes into "Waiting for combine"-mode - and then "Driving to combine".

First it did this once or twice for a field, but recently i started to do this very often.

Maybe it is some sort of timeout for the AD driver calculating path to the combine?

**Comment by Stephan-S** [comment]
Hey,

yeah sounds like the path calculation timed out.
What kind of settings are you using?
Can you copy the config file for me, so I can check it out?

Is it possible that there are multiple combines active on the map and he is trying to find a way to some distant combine which still has the same target in the AD Hud?

If he starts going to the combine if you reenable it, it shouldn't have timed out for the same path before. So he was searching for a path to another location before.

Are you using the new options for precall Driver and chase combine?

Best regards,
Stephan

**Comment by SledgeHammer75** [comment]
Noticed that too, probability seems to increase with distance to the starting point. 

Calculation speed an time both set to 2x. 
4x map (Kandelin), 1 combine, 2-3 unloaders on the field. 1 other driver selling stuff.

**Comment by OnkelH0tte** [comment]
the same problem here. after the trailer is full and the tractor has unloaded, he turns back to the field and cancel the job. and yes there is another job to pick up the straw with the same starting and end point to unload the trailer.

**Comment by Martinnygaard** [comment]
> What kind of settings are you using?

![Screenshot_1](https://user-images.githubusercontent.com/26490587/66213926-fdf03d00-e6c0-11e9-8396-ee2c2718926d.png)

> Can you copy the config file for me, so I can check it out?

[AutoDrive_Fenton_Forest_4X_By_Stevie_V1_42__config.zip](https://github.com/Stephan-S/FS19_AutoDrive/files/3690878/AutoDrive_Fenton_Forest_4X_By_Stevie_V1_42__config.zip)

> Is it possible that there are multiple combines active on the map and he is trying to find a way to some distant combine which still has the same target in the AD Hud?

i have only one combine in the savegame. (and two krone big m - not running?)


> If he starts going to the combine if you reenable it, it shouldn't have timed out for the same path before. So he was searching for a path to another location before.

Im not sure - i think i've experinced both - start again right away, or needed to move it a bit.


> Are you using the new options for precall Driver and chase combine?

Nope.

**Comment by Martinnygaard** [comment]
Some update:
I have updated Autodrive to 1.0.6.1 and enabled all the new features. (Chasing combine and precall driver)
My setup is currently:
Two Ideal harvesters on a large square field. Both driven in convoy by Courseplay.
One Case IH with a Krone trailer (that cannot do tight radius) (Set to precall at 50% and avoid fruit = no


Now i get a lot of messages in my log from AD:

First this:

> 2019-10-06 13:43 Error: Running LUA method 'update'.
> 2019-10-06 13:43 C:/Users/Martins Stationære/Documents/My Games/FarmingSimulator2019/mods/FS19_AutoDrive/gui/settings.lua:102: attempt to index local 'self' (a nil value)

Then a little later this:

> 2019-10-06 14:04 Going into fallback mode - no fruit free path found in reasonable time
> 2019-10-06 14:14 Going into fallback mode - no fruit free path found in reasonable time
> 2019-10-06 14:33 AD: Set to recalculating routes
> 2019-10-06 14:33 Game saved successfully.
> 2019-10-06 14:37 Going into fallback mode - no fruit free path found in reasonable time
> 2019-10-06 14:38 Going into fallback mode - no fruit free path found in reasonable time
> 2019-10-06 14:50 AD: Set to recalculating routes
> 2019-10-06 14:50 Game saved successfully.
> 2019-10-06 14:53 Going into fallback mode - no fruit free path found in reasonable time
> 2019-10-06 14:53 CourseGeneratorScreen:onCreate()
> 2019-10-06 14:54 Stop searching - no path found in reasonable time
> 2019-10-06 14:54 Autodrive encountered a problem during initialization - shutting down

After i saw this message (no fruit free path found in reasonable time) i dissabled the "avoid fruit".

**Comment by Martinnygaard** [comment]
I think 1.0.6.1 has fixed this issue.
It has not cancled since i updated.
Thanks.
