### ISSUE TITLE
Dutch translation v1.0.6.1

### ISSUE THREAD

**Issue by Bobster82** [Stephan-S/FS19_AutoDrive#567]
Hi @Stephan-S ,

Got an updated translation dutch ;)

[translation_nl_1.0.6.1.zip](https://github.com/Stephan-S/FS19_AutoDrive/files/3689769/translation_nl_1.0.6.1.zip)

**Comment by joshvzeyl** [comment]
it's maybe better to create an pull request, but thx for the translation work

**Comment by Bobster82** [comment]
> it's maybe better to create an pull request, but thx for the translation work

I dont know how to do that, so I just post it here... Maybe stephan didnt see it...
Need to update it again, there are some new things added... wil do that this week

**Comment by Stephan-S** [comment]
Hey @Bobster82 
Is this still the latest translation file?

**Comment by Bobster82** [comment]
Hi @Stephan-S  ,
That was an older version, here is the latest v1.0.6.6:
[translation_nl_1.0.6.6.zip](https://github.com/Stephan-S/FS19_AutoDrive/files/3779529/translation_nl_1.0.6.6.zip)
