### ISSUE TITLE
Ordner speichern

### ISSUE THREAD

**Issue by Moitzbert** [Stephan-S/FS19_AutoDrive#568]
Hey kann mir jemand sagen wie ich die angelegte Ordnerstruktur speichern kann ? Sobald ich die Kurse einmal aktualisiere löschen sich die gerade erstellten Ordner. 

Mfg Christof

**Comment by newbie-near-cologne** [comment]
Hi, wir nutzen die 1.0.6.3 auf einem Nitrado Dedi Server. Leider haben wir dort auch das Problem das die Ordner nicht gespeichert bleiben. Ich kann Ordner anlegen und Kurse hinein schieben, aber nach einer Aktualisierung sind die Ordner wieder weg. Ich bin als Admin eingeloggt, aber auch dies löst das Problem nicht. Gibt es eine Abhilfe dafür? Ansonsten ein super Mod, auch im MP. Danke für die bisherige Arbeit.

**Comment by Stephan-S** [comment]
Ordner Funktionalität gibt es aktuell nur im SP. Dort können Ordner erstellt werden und die config dann auf den Server übertragen werden.
