### ISSUE TITLE
Lkw mit Ladefläche und Anhänger

### ISSUE THREAD

**Issue by SledgeHammer75** [Stephan-S/FS19_AutoDrive#569]
Ich habe heute mal 2 Mods als Abfahrer getestet, beides Lkw mit Ladefläche und Anhänger. Die Ladefläche der Lkw wurde jeweils beim Abtanken des Dreschers nicht befüllt. 
Traktor mit 2 Anhängern funktioniert. 

https://www.yesmods.com/fs19-mods/trucks/european-trucks/fliegl-transport-pack-ir/
https://www.yesmods.com/fs19-mods/trucks/european-trucks/man-tgx-26-640-grain-truck-kl/

**Comment by Stephan-S** [comment]
Hey, hast du den 'Abstand Hänger' mal so angepasst, das er mit der Ladefläche unter dem Rohr stehen bleibt?

**Comment by haamic** [comment]
Kann ich so nicht bestätigen. Mein LKW mit Ladefläche und Hänger wurde anstandslos am Drescher beladen. 
Auch das laden am Silo funktioniert mit diesem Gespann.  
@Stephan-S
Aber mir ist aufgefallen, das das einfache abladen nicht mehr korrekt funktioniert. Hat sich da ein Fehler eingeschlichen? Aktuelle Version von vor 4 Stunden.
Egal ob Schlepper oder lkw, wenn dieser den abladetrigger erreicht, wird abgeladen. wenn er leer ist, bleibt er auf dem trigger stehen. Abladeziel bleibt grün und fährt nicht weiter, da der eigentliche Zielpunkt hinter dem trigger liegt.  Somit wird auch ein eventueller 2. Anhänger nicht entleert. 
Betrifft wie geschrieben nur den ablade Modus. Im Drescher abtanken Modus klappt das und fährt zum Feld zurück.

**Comment by haamic** [comment]
@Stephan-S 
hier ein video wenn du mal gucken möchtest. AD bleibt eingeschalten und Ziel grün nach abladen.
[https://www.magentacloud.de/lnk/6KCAHAFv](url)

**Comment by GitTomahawk** [comment]
Bei mir wird am Drescher auch nur der Anhänger beladen.
Beim Silo funktionierts mit Zugmaschine und Anhänger.
Abstand anpassen brachte bei mir keine Veränderung.

**Comment by Lars-LS17** [comment]
Hallo,

erstmal vielen Dank für deinen Mod. Der ist echt klasse und mittlerweile unverzichtbar für LS19.

Ich habe jedoch auch das Problem, dass ich mit zwei verschiedenen LKWs inkl. 2. Anhänger nicht weiter fährt. Er füllt einfach den Anhänger vom LKW nicht auf. Ich muss Rechts im Menü auf die Doppel-Pfeile klicken, damit der LKW weiter vorwärts fährt und dann auch den Anhänger auffüllt.

![fsScreen_2019_10_07_21_01_59](https://user-images.githubusercontent.com/31773176/66340598-cb0aab00-e945-11e9-907f-05f7e8c22e2e.png)
