### ISSUE TITLE
Upload der Kurse auf einen Server

### ISSUE THREAD

**Issue by Merlin110480** [Stephan-S/FS19_AutoDrive#57]
Du hattes in dem anderen Issue geschrieben:

> Ich habe auch von Anfang an die Option eingebaut, Kurse auf den Server hochzuladen. Wenn du als Admin eingeloggt bist, kannst du über die Tastenbelegung "Kurs hochladen", den Kurs im ImportFolder automatisch an den Server hochladen. Quasi der umgekehrte Prozess, der sonst beim Verbinden auf den Server stattfindet :-) Aber wenn du leicht FTP Zugriff hast, ist das wahrscheinlich trotzdem die einfacherer Variante, mit mehr Kontrolle über die Daten.

Wo finde ich diesen Ordner?
Hab bei Nitrado leider nur Zugriff auf den Mod Ordner

_Originally posted by @Stephan-S in https://github.com/Stephan-S/FS19_AutoDrive/issues/39#issuecomment-481971246_

**Comment by Stephan-S** [comment]
Hey, in deinem eigenen PC, im FarmingSimulator2019 Ordner befindet sich ein "FS19_AutoDrive_Import" Ordner. Wenn du da eine config.xml reinkopierst, kannst du dich dann auf deinen Server verbinden, als Admin einloggen und die Tastenkombi für Kurs hochladen drücken.
Das ist ja gerade für die Leute gedacht, die keinen direkten Dateizugriff auf ihren Server haben.

Ich hoffe das ist so verständlich :-)

**Comment by Merlin110480** [comment]
Hm, ok dann hatte ich es richtig verstanden, nur gibts den ordner bei mir nicht, hab nur den "export" Ordner.
Einfach anlegen oder ist es ein Problem das er nicht da ist?

**Comment by Stephan-S** [comment]
Den Ordner kannst du selber erstellen. Ich habe gerade im Code gesehen, das er den Ordner erst erstellst wenn du das erste Mal einen Kurs importieren willst. Dann erzeugt er den Ordner, falls er noch nicht vorhanden ist und sucht dann darin. 
Also entweder einmal import drücken und den Ordner erzeugen lassen oder warten bis ich ein Update hochladen, bei dem er den Ordner auch beim Drücken der Speichern Taste erstellt, also beim Exportieren der Routen.

**Comment by Anonymous-any** [comment]
Thank for explain and clarify that "upload option", when I translated that I was thinking there a button appear added on the HUD when in multiplayers but I can not host a server for test due to (android phone connection restricted for NAT ports).
 :)

**Comment by Stephan-S** [comment]
Seems resolved.

**Comment by Anonymous-any** [comment]
Back to this, I been tried to upload but seem not work, and I explain my steps:
as admin in the server login, must open the edit mode then the message appear like
`User is admin and allowed to upload course` (if not edit mode no message appear)
Then because I got FTP access then where must the uploaded file go ?
Looking in every folder server seem not got the uploaded file...
