### ISSUE TITLE
Doppelte Zielnamen verhindern

### ISSUE THREAD

**Issue by HerrchenChris** [Stephan-S/FS19_AutoDrive#570]
Huhu,
ich habe jetzt bei mir die Zielpunkte in Ordner gepackt.
Unter anderem habe ich einen Ordner "Schweinehof" und einen Ordner "Pferdezucht".
In jedem Ordner sind dann die u.a. die Zielpunkte "Futteranlieferung", "Strohanlieferung"... (siehe Screenshot)
Halt jeweils für die passenden Orte.

![20191004143659_1](https://user-images.githubusercontent.com/52828429/66209977-fa58b800-e6b8-11e9-9e83-3e3c66b55990.jpg)

Jetzt habe ich eben einen Traktor losgeschickt zum Zielpunkt "Futteranlieferung" beim "Schweinehof", allerdings hat er dann den Zielpunkt "Futteranlieferung" bei der "Pferdezucht" angefahren.
Überprüft AD nur den Namen und fährt diese dann an?
Version ist die aktuelle.

Gruss Chris

**Comment by vertigoogle** [comment]
Die Ziele müssen eindeutig heißen. Ist mir auch schon passiert (gleiche Map).
Umbenennen (gibt ein Binding dafür, geht aber auch über anpassen des xml), neuberechnen und dann funktionierts wieder.

**Comment by Stephan-S** [comment]
Zielnamen sollten tatsächlich eindeutig sein. Sie haben zwar eine ID aber trotzdem muss das Mapping Name<->ID hier immer eindeutig sein damit alles problemlos läuft. Sollte ich eigentlich noch beim Erstellen überprüfen..

**Comment by Stephan-S** [comment]
Hallo, da wir gerade die neue restrukturierte Version von AutoDrive released haben, können wir leider keine Bugs und Issues die sich noch auf die alte Codebasis beziehen mehr bearbeiten.
Wenn das Problem bzw. dein Anliegen in der atkuellen Version weiterhin besteht, mache doch bitte ein neues Issue mit allen benötigten Informationen auf.
Oder melde dich bei kleineren Themen und Fragen auch gerne direkt im Discord:
https://discord.gg/sUQtKhB

Vielen Dank für dein Verständniss und ich hoffe du hast weiterhin Spaß am AutoDrive Mod :-)

Und hier noch ein Link zur aktuellen Version:
https://github.com/Stephan-S/FS19_AutoDrive/releases/tag/1.1.0.0
