### ISSUE TITLE
Abholen und abliefern - Wiederholungen

### ISSUE THREAD

**Issue by Corona01** [Stephan-S/FS19_AutoDrive#571]
Hallo, 
Modus: Abholen und abliefern:
in der Version 1.0.5.8, die ich bis heute installiert hatte, war es möglich das bei der Einstellung 1 bei den Wiederholungen 1 Fuhre erledigt wurde und das Fahrzeug dann am letzt eingestellten Zielpunkt nach dem abliefern stehen blieb.
Version 1.0.6.1: Die grüne Anzeige der 1 bei den Wiederholungen erlischt nach dem abliefern, das Fahrzeug fährt aber wieder zum Startpunkt der eingestellten Tour laden und beginnt von vorne. 
Ob es dass dann endlos macht kann ich nicht sagen da nicht soviel im Silo ist und ich eigentlich nur 1 Fuhre machen wollte.
Programmierfehler, Bedienfehler ?
Lg

**Comment by Stephan-S** [comment]
Servus,

einige User haben sich gewünscht, dass der Fahrer wieder zum Ausgangs/Startpunkt fährt anstatt am Ziel stehen zu bleiben.
Ich habe die Funktion tatsächlich seit der Änderung noch nicht getestet, aber er sollte am Startpunkt stehen bleiben. Er wird zwar noch aufladen, sollte aber nicht weiterfahren.

**Comment by haamic** [comment]
Ja das ist so. Fährt nun zum Start der Tour zurück, und lädt nochmal auf. Ist wohl anders nicht machbar.  Diese Funktion ist eigentlich für verteil-/Verlaufsfarten gedacht. Warum sollte er also am Ziel stehen bleiben. 
Danke Stephan das du das so schnell umgesetzt hast.

**Comment by Corona01** [comment]
Hallo Stephan,
Danke für die Info !!
Habe es jetzt getestet, Fahrzeug fährt zum Startpunkt zurück, wird beladen und bleibt dann stehen.
Ich finde diese Aktion aber nicht sonderlich sinnvoll.
Brauchte zuerst eine Fuhre Silage (75000 Liter) für Mischfutter, diese Fuhre hat das Fahrzeug auch erledigt, es fuhr zurück zum Startpunkt und wurde mit 2000 Liter beladen weil nicht mehr in der Produktion war.
So jetzt ist dieses Fahrzeug blockiert, man muß sehen wo man das Ladegut wieder los wird und mit 2000 Liter in der Gegend rumfahren um nach dem Abladen das Fahrzeug weiter verwenden zu können.
Keine Ahnung ob es auf jeder Map Lagermöglichkeiten für jedes Ladegut gibt. 
Wenn man das alles nicht möchte muß man ständig darauf schauen das man das Fahrzeug rechtzeitig abfängt bevor es wieder beladen wird, dann könnte man das Fahrzeug aber auch gleich selbst steuern.
Wäre es möglich das weitere Beladen wenigstens zu unterbinden ?
Ab welcher Version wurde das so programmiert (wegen vorläufigem Downgrade)

In jedem Fall sag ich mal DANKE für dieses Super Script und die tolle Programmierarbeit, auch wenns da und dort noch manchmal hackt, ich verwende AD zusamen mit CP sehr gerne !!!!

**Comment by Woife1** [comment]
Nimm dann die 1.0.5.8 wieder oder die .7 die is stable
die Änderung am Loop wurde in 6.0 oder 6.1 gemacht 
zum reinen spielen reicht die letzte stable Version 
wenn du testen willst musst du noch damit leben das er nochmal füllt

Stephan wäre es möglich den Loop zum Start als Option einzufügen das jeder selber wählen kann?

**Comment by OnkelH0tte** [comment]
Hallo Stephan,

das der Fahrer zum Startpunkt zurück fährt finde ich super, dass er jedoch noch einmal auflädt ist irgendwie kontraproduktiv, da man das Zeug ja wieder los werden muss.

**Comment by Corona01** [comment]
@Woife1 
Danke !
Habe gestern noch getestet, bei Version 1.0.6.0 bleibt das Fahrzeug am Zielpunkt stehen.

> Stephan wäre es möglich den Loop zum Start als Option einzufügen das jeder selber wählen kann?

Das wäre natürlich die optimalste Lösung !
Auf einer Map wo ich nur vom Hofsilo zu Verkaufspunkten fahre finde ich es ok wenn das Fahrzeug zum Startpunkt zurückfährt.
Auf einer Map wie die MultiMap 2019, wo die Produktionen über die ganze Map verteilt sind und somit auch die Ladepunkte, kommen so wie jetzt allerdings unnötige Kilometer zusammen, wobei das fahren eher nicht das Problem ist, sondern das nochmalige beladen.

**Comment by haamic** [comment]
aktuell wird nun doch wieder nur am ziel gestoppt, ohne rückfahrt?

**Comment by Stephan-S** [comment]
korrekt. Bis ich eine Lösung gefunden habe ohne Nachtanken am Ziel habe ich es erstmal wieder geändert.

**Comment by haamic** [comment]
Dann wärs doch besser diese Funktion, wählbar zu machen. So kann jeder für sich entscheiden, wie er es möchte. Im hud ein Button oder in den Einstellungen. Zum HUD muss ich sagen, das für mich 4 Button überflüssig sind. Die beiden für die Geschwindigkeit und die Links/rechts für die Ziele. Vielleicht könnte man mal eine Art Umfrage machen, ob diese für andere Spieler auch verzichtbar sind. Dann könnte das HUD aufgeräumt werden. Ich glaube du meintest mal, das du es eher minimalistisch magst. Auch gäbe es dadurch theoretisch Platz für neue Funktionen, beispielsweise eben die Rückfahrt zum Start nach dem Durchlauf. Oder manueller "1-Klick-Tausch" der Zieleingaben anhand der Modi. 
Zum Problem des nochmaligen Beladens, könnte evtl der filltype bei der letzten Runde auf etwas springen, was nicht beladen werden kann? Ich kann ja auch während der Durchläufe die Fruchtsorte wechseln ohne AD beenden und neu starten zu müssen. 
Gibts da nicht im Spiel zb. "AIR", den man nicht beladen kann? wenn er den am Start nochmal laden will, passiert nichts.
