### ISSUE TITLE
AD bremst zu spät ab

### ISSUE THREAD

**Issue by OnkelH0tte** [Stephan-S/FS19_AutoDrive#572]
Hallo Stephan,

kann es sein, dass seit dem neuen update die Option mit dem "vorausschauend Bremsen" weggefallen ist?
Habe seit dem das Problem, dass die Fahrer zum Teil über ihren Zielpunkt hinausschießen und sich dann festfahren, so dass man die max. Geschwindigkeit viel zu weit runterschrauben muss.

LG

**Comment by Onkel2000** [comment]
Bei mir das gleiche. Ist da was in Planung?

**Comment by Stephan-S** [comment]
Servus,
nur bei Zielpunkten also am Ende der Route oder?
Ja ich habe da etwas geändert um nicht allzu früh abzubremsen, aber das war dann wohl zuviel des Guten :-)
Ändere ich in der nächsten Version wieder etwas ab.

Viele Grüße,
Stephan

**Comment by Onkel2000** [comment]
> 
> 
> Servus,
> nur bei Zielpunkten also am Ende der Route oder?
> Ja ich habe da etwas geändert um nicht allzu früh abzubremsen, aber das war dann wohl zuviel des Guten :-)
> Ändere ich in der nächsten Version wieder etwas ab.
> 
> Viele Grüße,
> Stephan

Bis jetzt ist es mir nur an Zielpunkte aufgefallen, also wo er abladen soll.
Klingt gut, danke :)

**Comment by sebi1987** [comment]
Hallo,
bei mir ist es genau so auch mit der neuesten Version.
Habe dann den Mod "VehicleControlAddon" raus genommen und dann funktioniert es!
Kann man da vielleicht noch was machen?
 Benutze nämlich beide Mods gerne!

**Comment by Onkel2000** [comment]
> 
> 
> Hallo,
> bei mir ist es genau so auch mit der neuesten Version.
> Habe dann den Mod "VehicleControlAddon" raus genommen und dann funktioniert es!
> Kann man da vielleicht noch was machen?
> Benutze nämlich beide Mods gerne!
> Habt ihr auch den Mod "VehicleControlAddon" im Modordner?

Nein, kenne den Mod auch nicht.

**Comment by sebi1987** [comment]
Hier zu finden:        https://github.com/Mogli12/VehicleControlAddon

**Comment by OnkelH0tte** [comment]
> Hallo,
> bei mir ist es genau so auch mit der neuesten Version.
> Habe dann den Mod "VehicleControlAddon" raus genommen und dann funktioniert es!
> Kann man da vielleicht noch was machen?
> Benutze nämlich beide Mods gerne!
> Habt ihr auch den Mod "VehicleControlAddon" im Modordner?

kenne und nutze ich auch nicht. liegt als demnach wohl nicht daran.

@ Stephan. Ist mir bisher auch nur an zielpunkten aufgefallen und auch nur mit dem LKW

**Comment by geo-luchs** [comment]
> 
> 
> Servus,
> nur bei Zielpunkten also am Ende der Route oder?
> Ja ich habe da etwas geändert um nicht allzu früh abzubremsen, aber das war dann wohl zuviel des Guten :-)
> Ändere ich in der nächsten Version wieder etwas ab.
> 
> Viele Grüße,
> Stephan

hi Stephan


hast du noch nicht wieder zurück geändert, oder?
Hab ein Zip file von heute ca. 11 Uhr. Er rauscht immer noch durch, und schießt sogar über den 
zielpunkt hinaus.

**Comment by Stephan-S** [comment]
Also im Moment sieht es so aus:

 if distanceToTarget < 5 then
        vehicle.ad.speedOverride = math.min(8, vehicle.ad.speedOverride);
    end;
    if distanceToTarget < 9 then
        vehicle.ad.speedOverride = math.min(15, vehicle.ad.speedOverride);
    end;
    if distanceToTarget < 12 then
        vehicle.ad.speedOverride = math.min(24, vehicle.ad.speedOverride);
    end;
    if distanceToTarget < 16 == nil then
        vehicle.ad.speedOverride = math.min(30, vehicle.ad.speedOverride);
    end;

und das ist immer noch zu schnell am Ende? Schade

**Comment by geo-luchs** [comment]
![AD-Bremsen](https://user-images.githubusercontent.com/53658780/66271840-f36da900-e862-11e9-9810-e124f576a30b.PNG)
Hi Stephan

hab es mal mit einem kurzen Anhänger getestet. Er kommt bei mir aufn Hof mit 37 KmH angerauscht, bevor  dein Algorithmus oben ihn abbremst.
Aber damit schießt er über den Ladepunkt hinaus.

Es scheint ja so zu sein, dass das Befüllen selbst durch LS gemacht wird, und keine aktive Aktion von AD ist, oder?
Und wenn er beim vorbeifahren befüllt wird, kann das Fahrzeug nicht mehr schnell genug abgebremst werden.

Gibt es da eigentlich ein Erkennen, ob befüllt wird, und wird dann irgendwie zusätzlich abgebremst?

**Comment by geo-luchs** [comment]
![AD-Bremsen_16kmh](https://user-images.githubusercontent.com/53658780/66271954-12b90600-e864-11e9-9359-f61dd431c969.PNG)
und so hält er an, wenn ich mit 16 Kmh Höchstgeschw. komme.

**Comment by geo-luchs** [comment]
jetzt ist man auf der sicheren Seite, auch für kurze Anhänger.
der kleine Anhänger wird jetzt genau mittig beladen.
Danke Stephan
