### ISSUE TITLE
Frage: Möglichkeit zum Auftanken + Ordnererweiterung/Ziele + Pfadfindung

### ISSUE THREAD

**Issue by haamic** [Stephan-S/FS19_AutoDrive#573]
Hallo Stephan, 
soll ich lieber 3 Issue aufmachen, oder kannst du die Fragen hier kurz beantworten?

Zu meiner 1.Frage gibts geschlossene Issues, aber ohne konkrete Aussage.
Siehst du eine Möglichkeit, bei einem festgelegten Mindesttankinhalt, die Fahrt zum Ziel zu unterbrechen, automatisch die naheliegendste Tankstelle (aus einem Tankstellenordner) anzufahren und von dort dann zum eigentlichen Ziel zu gelangen? Oder ähnlich wie CP im Vorbeifahren zu stoppen, aufzutanken und Fahrt fortsetzen. 
(baue ja meist an der Strecke einen Tankpunkt, dessen Trigger immer überfahren wird)

Der zweite Teil der Frage, bezieht sich auf die Ordner und angefahrene Ziele.
Wäre es möglich, in dem Standard Ordner, oder in einem anderen, der immer der erste in der Liste ist, die letzten 3-5 angefahrenen Ziele pro Fahrzeug zu hinterlegen?
Also somit die schnellere Auswahl, der häufig verwendeten Ziele zu ermöglichen. 
Bei grossen Karten mit vielen Zielen und Ordnern ist das hilfreich, sonst scrollt man ewig.
Ich vermisse die Texteingabe, der Ziele, so wie in alten Versionen vor der neuen Liste.
Oder gibts diese doch noch versteckt, die mir nur nicht bekannt ist?

3.Teil
Wenn ich AD starte, tritt es bei mir nun öfter auf, das das Fahrzeug sich im Kreis dreht, und sich festfährt, weil es den Punkt nicht trifft, den es anfahren soll. 
Zwar lenkt es mal in die andere Richtung, aber fährt dann genauso im Kreis. 
Möglicherweise ist das nur der Fall, wenn es zu nah an der Strecke steht und in die entgegengesetzte Richtung fahren soll.
Ich glaube du hast etwas an der Pfadfindung geändert, oder hab ich das falsch gelesen?
Kann es daran liegen?  Eine niedrigere Geschwindigkeit des Fahrzeuges bracht keine Besserung.
Ich vermute, es wird einfach ein zu naher Wegpunkt versucht anzusteuern. Der Wechsel auf einen anderen Wegpunkt, erscheint mir jetzt auch länger als früher, der aber auch anscheinend zu nah ist. Wie schon erwähnt, wendet das Fahrzeug, versucht es erneut und fährt sich aber ebenso fest. Ich glaube die Geschwindigkeit wurde früher im "Suchmodus" auch mal runtergeregelt? jetzt sieht es so aus als fährt es Vollgas im Kreis. 
Da hilft nur AD stoppen und neu zu Starten, meist gibts dann einen Punkt der weiter weg ist und besser erreicht werden kann. Ich werde es weiter beobachten.

Schönes Wochenende
Gruss Micha

**Comment by Stephan-S** [comment]
Hey haamic,

zu 1.) Habe ich noch auf dem Schirm aber noch immer keine Zeit für gefunden.
zu 2.) Das werde ich so nicht umsetzen. Dafür hast du ja nun mal die Ordner. Wenn du 5 Ziele hast, die logisch zusammen gehören, pack sie doch gleich zusammen in einen Ordner :-)
zu 3.) Wo/wann genau passiert das? Ist das vielleicht das selber Problem wie in #522 ? Also nur bei beidseitig befahrenen Strecken? Oder passiert das allgemein?

Viele Grüße,
Stephan

**Comment by haamic** [comment]
Stimmt jetzt wo du es erwähnst, wo ich es festgestellt habe, betraf es eine beidseitig befahrbare Strecke. 
Hab ich so um die Felder angelegt. Meinem Empfinden nach, aber nur wenn der Fahrer zu nah an der blauen Linie steht und starten soll

**Comment by Stephan-S** [comment]
Tanken steht auf der Todo-Liste :-)
