### ISSUE TITLE
AD erscheint bei einem Modfahrzeug nicht

### ISSUE THREAD

**Issue by Fuzzy86** [Stephan-S/FS19_AutoDrive#574]
Hey! Ich bräuchte mal euer Wissen!
Habe mir gestern einen Fendt 900 runter geladen aber wenn ich in dem einsteige kommt nicht das AD Fenster. Hatte das Problem auch schon mal bei einen JD Drescher. Jetzt wollte ich fragen ob man den Mod raus hauen sollte oder kann man das selber auch irgendwie in der XML ändern das das Fahrzeug dann mit AD funktioniert?

Ich bitte um Antwort und bedanke mich im voraus
lg Fuzzy

**Comment by OnkelH0tte** [comment]
mal "ALT+0" versucht? Damit öffnest/schliesst du das Fenster, sofern du keine andere Tastaturbelegung hast.

**Comment by Fuzzy86** [comment]
Jop aber geht bei dem nicht
-- 
Diese Nachricht wurde von meinem Android Mobiltelefon mit GMX Mail gesendet.Am 05.10.19, 09:50, OnkelH0tte <notifications@github.com> schrieb:
mal "ALT+0" versucht? Damit öffnest/schliesst du das Fenster, sofern du keine andere Tastaturbelegung hast.



—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.

[

{

"@context": "http://schema.org",

"@type": "EmailMessage",

"potentialAction": {

"@type": "ViewAction",

"target": "https://github.com/Stephan-S/FS19_AutoDrive/issues/574?email_source=notifications\u0026email_token=AM2SDZQH6MHQD7V2EQUTIFDQNBBMBA5CNFSM4I5WMKKKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEANMXKQ#issuecomment-538626986",

"url": "https://github.com/Stephan-S/FS19_AutoDrive/issues/574?email_source=notifications\u0026email_token=AM2SDZQH6MHQD7V2EQUTIFDQNBBMBA5CNFSM4I5WMKKKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEANMXKQ#issuecomment-538626986",

"name": "View Issue"

},

"description": "View this Issue on GitHub",

"publisher": {

"@type": "Organization",

"name": "GitHub",

"url": "https://github.com"

}

}

]

**Comment by Fuzzy86** [comment]
Kann das sein das es mit dem IC Control zu tun hat?

**Comment by Stephan-S** [comment]
sorry, keine Zeit mich darum zu kümmern :(

**Comment by Fuzzy86** [comment]
Kein Problem. Der Fendt S4 hat der Modder schon umgebaut. Er hat die IC Steuerung konfigurierbar gemacht und jetzt funktioniert er auch mit AD und CP. 
Habe es vergessen hier zu schreiben und zu achließen.
