### ISSUE TITLE
1.0.6.1 - Kornschieber beim Abladen

### ISSUE THREAD

**Issue by GitTomahawk** [Stephan-S/FS19_AutoDrive#576]
In der aktuellen Version verwendet der Abfahrer häufig den Kornschieber, auch wenn vorher manuell die große Klappe eingestellt war.
In Version 1.0.5.x hat das Abladen einwandfrei funktioniert.

**Comment by Stephan-S** [comment]
Da hat sich in den letzen Versionen nichts dran geändert. Er probiert alle ab Abladepunkte des Trailers zyklisch aus, ob sie aktuell entladen können und nutzt den ersten der dabei ein true zurück liefert.

Hier fehlt noch eine Überprüfung bzw. eine kurze Wartezeit ob es dann auch mit dem vom Nutzer eingestellten Punkt gehen würde.

Aber leider wieder einer der Punkte für den ich aktuell keine Zeit habe..
Zuviele Baustellen^^
