### ISSUE TITLE
Größe von Sechseck und Schrift auf der Karte

### ISSUE THREAD

**Issue by GitTomahawk** [Stephan-S/FS19_AutoDrive#577]
Hallo,
erstmal vielen Dank für das Feature dass die Abfahrer mit Namen auf der Karte angezeigt werden.
Funktioniert auch im MP bei uns.
Uns sind allerdings die Sechsecke und die Schriftgröße auf der Map etwas zu groß. 
(auch die Marker vom originalen Helfer sind schon immer viel zu groß)
Kannst du mir schreiben wo im Code du die generierst bzw. welche Variable deren Größe festlegt?

**Comment by Stephan-S** [comment]
https://github.com/Stephan-S/FS19_AutoDrive/blob/eb24c87da0c9c1152827283fa154b44f62b9a97c/FS19_AutoDrive/scripts/AutoDriveHud.lua#L362

**Comment by GitTomahawk** [comment]
thx

**Comment by Stephan-S** [comment]
Wenn ihr eine gute Größe gefunden habt und/oder die Textposition angepasst habt, kannst du mir gerne mal kurz deine Version schicken.
Wenns mir so auch besser gefällt, kommt es so in den Mod :-)

**Comment by GitTomahawk** [comment]
Ich habs jetzt bei uns etwa so gross wie die originalen Fahrzeugpunkte.
![grafik](https://user-images.githubusercontent.com/55877391/66270312-2bb8bb80-e852-11e9-979d-986fc307c904.png)
Wir benutzen die Fahrzeugnamen "T_" auch um zu unterscheiden wem das Fahrzeug gehört.
Das passt dann genau mit dem Textabstand so dass der Punkt genua in der Mitte ist.
Folgende Werte habe ich geändert:
	local _, textSize = getNormalizedScreenValues(0, 6) --Textsize
	local _, textOffsetY = getNormalizedScreenValues(0, 10) --Abstand zum Icon
	local width, height = getNormalizedScreenValues(10, 10) --Triggersize
	vehicle.ad.mapHotspot:setIconScale(0.4) --Iconsize

**Comment by GitTomahawk** [comment]
Ich habs jetzt bei uns etwa so gross wie die originalen Fahrzeugpunkte.
![grafik](https://user-images.githubusercontent.com/55877391/66270312-2bb8bb80-e852-11e9-979d-986fc307c904.png)
Wir benutzen die Fahrzeugnamen "T_" auch um zu unterscheiden wem das Fahrzeug gehört.
Das passt dann genau mit dem Textabstand so dass der Punkt genua in der Mitte ist.
Folgende Werte habe ich geändert:
	local _, textSize = getNormalizedScreenValues(0, 6) --Textsize
	local _, textOffsetY = getNormalizedScreenValues(0, 10) --Abstand zum Icon
	local width, height = getNormalizedScreenValues(10, 10) --Triggersize
	vehicle.ad.mapHotspot:setIconScale(0.4) --Iconsize
