### ISSUE TITLE
1.0.6.1 - MP Hud crash beim Anlegen neuer Marker wenn Ordner==AN

### ISSUE THREAD

**Issue by GitTomahawk** [Stephan-S/FS19_AutoDrive#578]
**Client:**
Error: Running LUA method 'draw'.
.../FS19_AutoDrive/scripts/HudElements/PullDownList.lua:363: bad argument #1 to 'insert' (table expected, got nil)

**Server:**

AD: Set to recalculating routes
Warning (script): 'setXMLString':   Argument 2 has wrong type. Expected: String. Actual: Nil
..\..\..\src\base\scripting\lua\LuaScriptSystem.cpp   (882): expectedType == Value::VoidType \|\| expectedType
LU .../mods/FS19_AutoDrive/scripts/AutoDriveXML.lua (4
= .../mods/FS19_AutoDrive/scripts/AutoDrive.lua (168)
dataS/scripts/utils/Utils.lua (382) :   newFunc
dataS/scripts/FSBaseMission.lua (2838) :   saveSavegame
dataS/scripts/MessageCenter.lua (132) :   callback
dataS/scripts/events/SaveEvent.lua (23) :   publish
dataS/scripts/network/Server.lua (440) :   readStream
dataS/scripts/network/ConnectionManager.lua   (28) : func

Im Savegame fehlt bei dem neu angelegten Marker der "group"-Tag.
`
... 
 <mm62>
  <id>14319.000000</id>
   <name>BGASued</name>
   <group>All</group>
 </mm62>
 <mm63>
     <id>14337.000000</id>
      <name>Hof1SiloRum</name>
  </mm63>
 </mapmarker>
`

**Comment by Stephan-S** [comment]
Hey, ich komm aktuell nicht dazu das Ordner anlegen auch für den MP fertig zu machen. Aber wenn du Lust hast dich etwas damit auseinander zu setzen, kannst du ja gerne mal versuchen dich daran zu setzen :-)
Ich gebe dir auch gerne ein parr 'pointer' in die richtige Richtung.
Aber ich will mich aktuell auf das aktive Abfahren konzentrieren :-)

**Comment by GitTomahawk** [comment]
Hi,
kein Problem, dein mod, deine Prios.

Ich vermute du legst beim Anlegen neuer marker keine "default"-gruppe fest.
Dadurch kommt es dann bei der übertragung im MP zu einer "nil"-Value

Ich würde vorschlagen jeder Marker bekommt per default die Gruppe "All":
Ich denke hier wäre der richtige Ort?:
function AutoDriveCreateMapMarkerEvent:new(vehicle, id, name)
    local self = AutoDriveCreateMapMarkerEvent:emptyNew()
    self.vehicle = vehicle;
    self.id = id;
    self.name = name;
	self.group = "All"; --seting default group name for new Markers
	return self;
end;

Alternativ oder zusätzlich könnte man auch "nil" als Gruppenname "All" interpretieren:
function AutoDrive:readMapMarkerFromStream(streamId, numberOfMapMarkers)
...
		   marker.node=node;
			if markerGroup == "" or markerGroup == nil then
				markerGroup="All"; --use default GroupName if none transmitted
			end;
		    marker.id = markerId;
		    marker.name = markerName;
		    marker.group = markerGroup;

Ene Kombination aus beiden würde die Sache doppelt absichern und auch bei übertragungsproblemen helfen.

**Comment by GitTomahawk** [comment]
Wenn man die Marker ohne Gruppe im Savegame mauell anpasst, dann funktioniert es jetzt.
Danke

**Comment by Stephan-S** [comment]
Alles klar. Neue Marker sollten jetzt auch im MP in der Standard / 'All' Gruppe landen
