### ISSUE TITLE
Abfahrer bleiben in der Frucht stehen

### ISSUE THREAD

**Issue by Onkel2000** [Stephan-S/FS19_AutoDrive#579]
Hallo, 

wenn ein Abfahrer den  Drescher abtankt fährt er ein Stück zurück und bleibt in der Frucht stehen und blockiert in der nächsten Bahn den Drescher. Die Option "im Feld parken" ist ausgestellt.

![fsScreen_2019_10_05_17_16_54](https://user-images.githubusercontent.com/53871930/66257072-f13d1900-e794-11e9-9ddc-cdb051f66e39.png)

**Comment by Stephan-S** [comment]
Hey, ist die Option Drescher verfolgen eingestellt oder war es ein klassisches Abtanken?

**Comment by Onkel2000** [comment]
klassich, verfolgen ist aus.

**Comment by RalfGorden** [comment]
bei mir ist das  gleiche Problem,Option Drescher verfolgen ist aus

**Comment by Stephan-S** [comment]
wird bearbeitet. ich mache hier aber mal zu, da es noch in anderen neueren Issues vertreten ist.
