### ISSUE TITLE
Ad Kurse

### ISSUE THREAD

**Issue by Bandesss** [Stephan-S/FS19_AutoDrive#580]
![20191005191639_1](https://user-images.githubusercontent.com/50829319/66258365-afb46a00-e7a4-11e9-81d0-e613a5f0d726.jpg)
Hallo Ad zeigt seit Heute keine punkte mehr an.
Kurse sind im import Ordner auch die Linien erscheinen im Spiel
Aber auswählen im Feld geht nicht mehr..
Gruss Bandes
[log.txt](https://github.com/Stephan-S/FS19_AutoDrive/files/3693523/log.txt)
![20191005191554_1](https://user-images.githubusercontent.com/50829319/66258351-97444f80-e7a4-11e9-85b0-afa1227088ce.jpg)

**Comment by Stephan-S** [comment]
Servus,
da hab ich nichts mehr geändert heute oder gestern.
Hast du auch abgewartet bis die Kurse synchronisiert waren?

**Comment by Bandesss** [comment]
Das ging immer so .... 
Du meinst neu Berechnen? Es ging Heute Morgen Heute Mittag hat es angefangen 
Gruss und danke

**Comment by Stephan-S** [comment]
Nein, ich meine die Kurse werden doch wenn du dem Server beitrittst heruntergeladen.

**Comment by Bandesss** [comment]
Die Kurse sind teils da also ein teil sieht man aber nicht alles.
Komisch Fahrzeuge fahren....

[AutoDrive_Multimap_2019_config.zip](https://github.com/Stephan-S/FS19_AutoDrive/files/3693549/AutoDrive_Multimap_2019_config.zip)

Vielleicht ist die Datei zu gross ?
Kann sie auch nicht im Editor öffnen, also funktioniert hatten die Kurse.
Das mit dem Editor ist seit dem Update vom Editor 
Gruss
[log.txt](https://github.com/Stephan-S/FS19_AutoDrive/files/3693551/log.txt)

**Comment by Bandesss** [comment]
Gerade gekommen
Map title: Multimap 2019
2019-10-05 19:44 map Multimap_2019 was loaded
2019-10-05 19:44 AD: Loading xml file from C:/Users/S3LS19/Documents/My Games/FarmingSimulator2019/savegame1/AutoDrive_Multimap_2019_config.xml
2019-10-05 19:44 AD: Loaded Waypoints: 1800
2019-10-05 19:44 Error: Running LUA method 'loadMapFinished'.
2019-10-05 19:44 C:/Users/S3LS19/Documents/My Games/FarmingSimulator2019/mods/FS19_AutoDrive/scripts/AutoDriveXML.lua:284: attempt to index a nil value

**Comment by Stephan-S** [comment]
Und das ist die config die du mir geschickt hast? Oder liegt auf dem Server noch eine andere?

**Comment by Bandesss** [comment]
Jepp die mit 16 MB genau...

**Comment by Stephan-S** [comment]
hättest du nochmal kurz einen Link für mich zu der Map? Dann schau ich mir das gleich mal an. Auf den ersten Blick seh ich keinen Fehler in der Datei, aber er lädt nur 1800 Punkte statt ~20000

**Comment by Bandesss** [comment]
klar gerne 
https://www.modhoster.de/mods/multimap2019--2

**Comment by Stephan-S** [comment]
2019-10-05 20:05 Map title: Multimap 2019
2019-10-05 20:05 map Multimap_2019 was loaded
2019-10-05 20:05 AD: Loading xml file from C:/Users/Steph/OneDrive/Dokumente/My Games/FarmingSimulator2019/savegame20/AutoDrive_Multimap_2019_config.xml
2019-10-05 20:05 AD: Loaded Waypoints: 19346
2019-10-05 20:05 C:/Users/Steph/OneDrive/Dokumente/My Games/FarmingSimulator2019/mods/FS19_AutoDrive/lineDrawing/Line.i3d (0.65 ms)
2019-10-05 20:05 --> loaded AutoDrive version 1.0.6.1 (by Stephan) <--

Läuft bei mir einwandfrei mit deiner config

**Comment by Stephan-S** [comment]
Es werden auch im Hud alle Zielpunkte wie gewohnt aufgelistet

**Comment by Bandesss** [comment]
Ja top, im SP ?

**Comment by Stephan-S** [comment]
Ja genau

**Comment by Bandesss** [comment]
Merkst was... .Mp soviel probleme.... echt ärgerlich.
Dann werde ich den Thread schliesen.
Danke für die Hilfe

**Comment by Stephan-S** [comment]
> War aber im SP

Du hast mir eben noch gesagt der Fehler war im SP..
Deinen Kommentar danach habe ich verpasst, dass nun im SP alles laufen soll.

Sieht so aus als hätte das Importieren/Uploaden der Kurse auf den Server nicht funktioniert. Probier das doch einfach nochmal. Oder hast du das schon getan?

**Comment by Bandesss** [comment]
Der 2 Fehler war im SP ja....
Oben auf den Bilder siehst du Server an der Ping
Import Fuktion geht nicht, keine ahnung warum.......
Es zeigt keine Punkte auf den Bildern oben an, aber die Fahrzeuge fahren, wie schon oben gesagt.
Wir haben keinen direkten Zugriff auf den Server, ich lade die hoch über Import, als Admin eingelogt.

**Comment by Stephan-S** [comment]
Darf ich mal auf den Server kommen und mir das Importieren live ansehen?

**Comment by Bandesss** [comment]
Ja bitte
![20191005201328_1](https://user-images.githubusercontent.com/50829319/66259024-a7f8c380-e7ac-11e9-96c6-37c737dc1685.jpg)

**Comment by Bandesss** [comment]
wir sind auch im DIscord
https://discord.gg/Tv6RgZW

**Comment by Bandesss** [comment]
Vielen Dank Kaffe ist unterwegs. TOP
