### ISSUE TITLE
Kurse im Abholen- Abliefern Modus und Abholen

### ISSUE THREAD

**Issue by Frodo65** [Stephan-S/FS19_AutoDrive#581]
Hallo Stefan,

ich habe Probleme mit den Kursen im Abholen/Abladen und im Abholen Modus.

Ich spiele im Moemnt die DonDiego Map mit Seasons. Das Problem ist auch auf der Projekt NDS aufgetreten.

Iregndwann im Laufe des Spieles verlässt der Trecker mit dem Hänger nachdem er im Silo abgeladen hat den Kurs und fährt irgendwo hin. Das selbe passiert irgendwann auch nachdem er Saatgut oder Dünger oder Kalk am Silo aufgeladen hat. In der Log steht nichts drin.

Benutze zur Zeit wieder 1.0.5.1 da ich mit den aktuellen Versionen Probleme mit meinen kleinen Maschinen habe.

Gruß Frank

**Comment by Frodo65** [comment]
Hi Staefan,

hier noch die config und meine log

[AutoDrive_FS19_Dondiego_Map_config.zip](https://github.com/Stephan-S/FS19_AutoDrive/files/3693606/AutoDrive_FS19_Dondiego_Map_config.zip)
[log.zip](https://github.com/Stephan-S/FS19_AutoDrive/files/3693607/log.zip)

**Comment by Stephan-S** [comment]
Hey,
kann es sein, dass du in der Zwischenzeit Kurse verändert und neuberechnet hast?
Da ist aktuell noch ein Bug im Code, der dann bei aktiven Fahrern andere Kurse/Wegpunkte ansteuert, was zu deinem Fehlerbild passen würde.

Viele Grüße,
Stephan

**Comment by Frodo65** [comment]
Nein
Habe keine Kurse neu erstellt und nicht neu berechnet. Wenn er am Silo
ablädt dann bleibt der abkipppunkt grün und ändert auch nicht das Ziel nur
der nächste Zielpunkt zeigt dann ganz woanders hin.
Kann es sein dass da ein Problem mit dem season Mod gibt?

Gruß Frank

Stephan Schlosser <notifications@github.com> schrieb am Sa., 5. Okt. 2019,
21:19:

**Comment by Frodo65** [comment]
Hi,

habe mal 2 Screenshots gemacht. Beim ersten kommt er am Silo an. Wenn er
stehen bleibt um abzuladen erkennt man jetzt den Wegpunkt nach rechts.

Das tritt unregelmäßig auf, manchmal erst nach 10 erfolgreichen Abladen,
dann wieder mal relativ häufig, erkenne kein Muster

[image: 20191005212750_1.jpg]


[image: 20191005212754_1.jpg]

Gruss Frank

Am Sa., 5. Okt. 2019 um 21:24 Uhr schrieb Frank Börner <
frank.boerner.1965@gmail.com>:

**Comment by raxtor** [comment]
@Frodo65 no images added when email reply.

**Comment by Frodo65** [comment]
Hier nun die beiden Screenshots

![20191005212750_1](https://user-images.githubusercontent.com/23238103/66260664-b7ced280-e7c1-11e9-80b6-d21d9cd0ca33.jpg)

![20191005212754_1](https://user-images.githubusercontent.com/23238103/66260666-c6b58500-e7c1-11e9-9bc9-6d7a894ae54c.jpg)


Gruss Frank

**Comment by Woife1** [comment]
So einen Fehler im Zusammenhang mit CP hatte ich auch mal
so wie es ausschaut wechselt er nach dem abladen sofort auf den Zielpunkt als Fahrtziel ohne die AD-Kurse zu beachten 
nach einem Neustart gings wieder

dieser Fehler ist mir in 1.0.6.1 noch nicht aufgefallen 
werde es aber bbeobachten ob er noch auftritt

**Comment by Frodo65** [comment]
Hi
Habe auch Mal die aktuelle Version im Einsatz.
Werde berichten


Gruß Frank

Woife1 <notifications@github.com> schrieb am So., 6. Okt. 2019, 06:50:

**Comment by Frodo65** [comment]
Scheint mit der aktuellen Version zu gehen
Können zu machen
Gruß Frank
