### ISSUE TITLE
v1.0.6.1 - MP, DediServer, Lags bei AD nutzung

### ISSUE THREAD

**Issue by SkidRock** [Stephan-S/FS19_AutoDrive#583]
Moin,

erst einmal muss ich dich Loben. AutoDrive als solches finde ich sehr gut, es funktioniert auch relativ zuverlässig im SingePlayer. Des Weiteren finde ich deine Reaktionsgeschwindigkeit auf neue Issues echt vorbildlich. So, genug rumgeschleimt ;)

**Nun zu unserem Problem:**
Wir haben einen **dedizierten Server**, 16 Slots, beim Anbieter Dawn-Server. Wir spielen die Map Multimap 2019 v2.2. Wir haben einige Mods auf dem Server laufen (bei Bedarf schick ich dir eine Liste). Hier fällt es sehr starkt auf, dass sobald wir einen **Helfer mit AD** nutzen, alle Mitspieler **extreme Lags** haben. Fahrzeuge und Anzeigen springen wie wild vor und zurück. Leider sagt die Log vom Server nichts aus. Vielleicht gibt es ja noch andere Spieler, die das selbige Problem haben und ggf. schon eine Abhängigkeit mit anderen Mods als Ursache ausmachen konnten. Das selbe tritt **auch bei lokal gehosteten Servern** auf.

**Comment by Bandesss** [comment]
Habt ihr mal auf Eure Latenz geschaut bei der Minikarte? Ob die sehr nach oben geht ?

**Comment by Onkel2000** [comment]
Habe auch einen 4 Slots Server bei Nitrado. Läuft da leider auch sehr bescheiden und wir sind nur zu zweit. Wenn ich ein lokales Spiel aufmache läuft es gut. Hab schon alles mögliche ausprobiert z.b. alle Mods aus bis auf AD, anderen Server anbieter... Latenz ist Super ist bei 22-30.

Und dem Lob kann ich nur zustimmen :)

**Comment by Stephan-S** [comment]
Servus,
ich komme selten dazu mir selber mal den MP auszuprobieren.
Aber AD ist natürlich recht CPU-lastig, unabhängig vom Netzwerkverkehr.

Die gehosteten Server sind ja meist nur virtuelle Maschinen, die wenig CPU-Power mitbringen bzw. wenig von der eigentlichen starken CPU nutzen dürfen. Vermutlich liegt es dann wohl daran

**Comment by Bandesss** [comment]
Wir haben einen Rootserver, ab und an hakt es minimal. 
Zu 5 drauf wobei nur 2 Leute ad nutzen.
Die ms auf der minikarte gehen von 20-28 wenn Ad aktiv ist.
G-Portal und Nitrado laufen,mit Ad nicht so gut.

**Comment by Stephan-S** [comment]
> Das selbe tritt **auch bei lokal gehosteten Servern** auf.



> Wenn ich ein lokales Spiel aufmache läuft es gut.

Beim einen so beim Anderen so :D Grundsätzlich kann ich nur sagen, habe ich schon vorm ersten Modhub-Release eine Menge Arbeit in den MP-Modus gesteckt und probiert die Netzwerkauslastung so gering wie möglich zu bekommen. Aber man merkt es natürlich trotzdem, da das Fahrzeug ja ständig neue Steuerbefehle bekommt.
Aber seit dem ersten Release und der aktuellen Version hat sich auch viel getan und durch viele neue Funktionen, braucht AD auch deutlich mehr CPU-Power als am Anfang.

Ich befürchte ich kann an der Perfomance auf die schnelle nichts ändern. Tut mir Leid

**Comment by Onkel2000** [comment]
> 
> 
> Servus,
> ich komme selten dazu mir selber mal den MP auszuprobieren.
> Aber AD ist natürlich recht CPU-lastig, unabhängig vom Netzwerkverkehr.
> 
> Die gehosteten Server sind ja meist nur virtuelle Maschinen, die wenig CPU-Power mitbringen bzw. wenig von der eigentlichen starken CPU nutzen dürfen. Vermutlich liegt es dann wohl daran

Die Vermutung hatte ich auch schon. Hatte auch schon überlegt mir einen richtigen Root-Server zumieten, wäre halt deutlich teurer... blöd wäre es wenns nicht den gewünschten Effekt hätte.


> Ich befürchte ich kann an der Perfomance auf die schnelle nichts ändern. Tut mir Leid

Das ist klar, da gibt es auch wichtigere Baustellen. Lass dich nicht stressen, wir teilen ja auch nur mit, was nicht ganz rund läuft :)

**Comment by Bandesss** [comment]
@Onkel2000 die leistung von nem Root zu einem der anbieter ist schon extrem.
Allerdings musst du, nen key fürs Spiel kaufen und für alle kostenpflichten DLCs... wir hatten key 32 Euro bezahlt und für DLC nochmal 20 Euro.... Ist schon nen Geld Frage... aber Performance ist viel besser.

**Comment by SkidRock** [comment]
> Hatte auch schon überlegt mir einen richtigen Root-Server zumieten, wäre halt deutlich teurer

Mit dem Gedanken habe ich ebenfalls schon gespielt. Dedizierte Server mit einer Intel CPU (i7 oder XEON) sind aber auch mittlerweile recht erschwinglich geworden (ab 40-50 EUR aufwärts im Monat). Ist nur die Frage, ob einem das Wert ist ;) Wobei ich halt kein Freund von einem Windows-Server im Netz bin ;)

Ich werde es ggf. die Tage mal testen und hier Bericht erstatten ob's damit besser läuft. 

@Stephan-S und den anderen : Trotzdem vielen Dank für euer schnelles Feedback.

**Comment by Onkel2000** [comment]
> 
> 
> @Onkel2000 die leistung von nem Root zu einem der anbieter ist schon extrem.
> Allerdings musst du, nen key fürs Spiel kaufen und für alle kostenpflichtige DLCs... wir hatten key 32 Euro bezahlt und für DLC nochmal 20 Euro.... Ist schon nen Geld Frage... aber Performance ist viel besser.

Genau das ist es, nochmal das Spiel kaufen, dann ist die frage ob Windows (kostet ja doch nochmal ca. 20 € mehr) oder obs auch gut auf einer Linux version läuft?

**Comment by Bandesss** [comment]
das kann ich dir nicht sagen, unserer läuft auf einen Windows Server 2016.
