### ISSUE TITLE
Problem Fehler mit Getreidelager von VertexDezign

### ISSUE THREAD

**Issue by gerrit0476** [Stephan-S/FS19_AutoDrive#584]
Hallo Stephan,

ich habe Probleme mit dem Dynamic Grain Storage von VertexDezign.
1. Autodrive fährt mit aktiver Kollisonserkenneug nicht durch das Silo zum entladen. (Kann man das anpassen?)
2. Wenn ich Getreide Abbholen und liefern lassen möchte crasht die Funktion und folgender Fehler ist in der Log:
Error: Running LUA method 'update'.
config/mods/FS19_AutoDrive/scripts/AutoDriveTrailerUtil.lua:38: attempt to index field 'providedFillTypes' (a nil value)
Das Spiel friert kurz am Ladetrigger ein!

Version 1.0.6.1 
Gruß Gerrit

**Comment by Stephan-S** [comment]
Servus,
zu 1.) wenn es wie bei GC die Kollisionsmasken gesetzt hat. Bzw. wie GC bevor ich mit ihnen in Kontakt getreten bin, dann sitzt hier noch Bit 25, wo eigentlich nur Bit 20 sitzen sollte:
AD schaut auf Bit 25 für die Kollisionserkennung. Hier mal ein kurzer Link zur Referenz: https://www.dummies.com/computers/pcs/computer-games/how-to-set-correct-collisions-in-your-farming-simulator-mod/
Wenn du das für dich anpassen kannst: super. Ansonsten bzw. generell wäre es super wenn du dich bei Vertex Design melden kannst, wenn es denn an den Bits liegt. Hast du den Giants Editor und die Möglichkeit/Wissen oder soll ich mir das mal ansehen?

zu 2.) Da haben sie wohl auch wieder einen custom Trigger gebastelt der nicht das Standard-Interface nutzt..Nicht cool. Schick mir doch mal kurz einen Link zum Mod. Danke :-)

Viele Grüße,
Stephan

**Comment by gerrit0476** [comment]
Moin,

hier der Link:
https://www.farming-simulator.com/mod.php?lang=de&country=de&mod_id=140589&title=fs2019

Punkt 1. kann ich dann selber lösen vielen Dank. 

Mir ist noch aufgefallen das ich generell gerade mir AD Probleme beim entladen habe z.B. Wasser holen Kühe oder Getreide vom Drescher zum Verkaufspunkt bringen. Er kippt dort aber entlädt nix und die abkipp Animation fehlt auch. Und kein Fehler!

Grüße Gerrit

**Comment by Stephan-S** [comment]
Aktuell habe ich keine Zeit Modsilos extra einzubinden. Ich schiebe das also mal nach ganz weit hinten auf der Todo-Liste. Tut mir Leid

**Comment by Iwan1803** [comment]
Please update to 1.1.0.5-RC5, try again and then give us a feedback.
*Bitte aktualisiere auf 1.1.0.5-RC5, versuche es erneut und gib uns dann eine Rückmeldung.*
