### ISSUE TITLE
Empty combine: endless loop

### ISSUE THREAD

**Issue by Martinnygaard** [Stephan-S/FS19_AutoDrive#585]
Hi,

My tractor have a trailer (krone TX560D) that has a wider turning angle.

When AD during pathfinding to the combine tries to do a narrower turning circle than the tractor and trailer can do, it ends up in a endless loop, trying to reach the waypoint.

Will an automatic turning radius feature like CP (or manual) be possible to implement?

![autodrive turning circle](https://user-images.githubusercontent.com/26490587/66266474-c2bb4e80-e825-11e9-89a5-23fc95b4264e.png)
The red circle is ADs aim.
Green is trailers min diameter.

![autodrive turning circle 2](https://user-images.githubusercontent.com/26490587/66266466-b6cf8c80-e825-11e9-994f-c7d28d65bf66.png)

**Comment by Stephan-S** [comment]
Hey,

I built in an automatic detection of the turning radius in the last version. If you use the version from the current source files and not the release version, you should already see a better perfomance on these maneuvers.
The last corner though is a bit problematic, as this is sort of a cut over between the path finding algorithm which now definitely respects the turn radius and the 'target point' or target line to the pipe. This can sometimes unfortunately end in some tight turns.

Once again, in the current source files, he will retrigger a new pathfinding process when he gets stuck which should help in these situations. Just make sure to enable 'precall driver' and 'chase combine' for all of it to work together.
This way, a lot less babysitting should hopefully be required

**Comment by Martinnygaard** [comment]
Thanks for the quick reply. 
I have tried to download the repository including your latest changes from today. :-)
