### ISSUE TITLE
V1.0.6.0 - AD schaltet sich ständig aus

### ISSUE THREAD

**Issue by Corona01** [Stephan-S/FS19_AutoDrive#586]
Hallo,
in der Version 1.0.6.0 schaltet sich AD laufend aus - Abfahrer beim zufahren zum Drescher, genauso wie beim abfahren vom Drescher - Drescher CP gesteuert.
Absolut freies Feld rundherum, keinerlei Hindernisse. Fruchtumfahrung und parken auf dem Feld aktiviert, klassisches Drescher abtanken ohne früher rufen.
Fehlermeldung: 
Going into fallback mode - no fruit free path found in reasonable time
Stop searching - no path found in reasonable time
Autodrive encountered a problem during initialization - shutting down

Beim fahren gibt es keine Probleme, beim "unload and refill" in Verbindung mit CP gibt es auch keine Probleme

Anbei die aktuelle Log.

Gruß

[log.txt](https://github.com/Stephan-S/FS19_AutoDrive/files/3694134/log.txt)

**Comment by Bandesss** [comment]
Benutze mal bitte das Aktuelle Build 1.0.6.1

**Comment by Stephan-S** [comment]
@Corona01 ich bin immer wieder dabei, den Pfadfinde-Algorithmus hier und da ein wenig anzupassen.
In der aktuellsten Source Version sollte er mit schmaleren Wegen klar kommen.

Wenn du dir die zip File mal selber baust oder auf den nächsten Release heute wartest und dann immer noch so Probleme auftreten, dann kopier mir doch gerne mal das Savegame, damit ich genau die Situation nachstellen kann und herausfinden kann woran es scheitert.

P.S.: Wenn du Feldausfahrt auf 'Nächstgelegen' stehen hast und um das Feld herum Kurse liegen die er vom Feld nicht erreichen kann wegen Gebäuden, Gräben, Waldstreifen etc. ist das auch immer ein guter Fehlerkandidat. Er probiert ja dann einen Weg zu dem Punkt zu berechnen, der dir mit der Roten Linie vom Traktor aus angezeigt wird, wenn du den Editor Modus öffnest an dieser Stelle.

Viele Grüße,
Stephan

**Comment by Corona01** [comment]
@Bandesss 
von V1.0.6.1 bin ich wieder runter auf 1.0.6.0 weil in der 6.1 das mit dem zurückfahren an den Start und wieder beladen nichts für mich ist.
Siehe #571

@Stephan-S 
Danke,  dann warte ich mal auf das Release.
Feldausfahrt ist Standart

Gruß

**Comment by Woife1** [comment]
Und wenn du eine stärkere CPU hast kannst du auch im Drescher-Reiter die Berechnungszeit höher stellen und AD dadurch mehr Zeit zur Kursberechnung geben
