### ISSUE TITLE
Abholen-Modus: größerer Abstan zwischen Abdeckung öffnen und Zielwegpunkt

### ISSUE THREAD

**Issue by geo-luchs** [Stephan-S/FS19_AutoDrive#587]
Hallo Stephan

ich habe 2 Produktionen, Saatgut und Dünger, die etwas weiter auseinanderstehen, also mehr als 25m.

Wäre es möglich, in der Function:
AutoDrive:checkTrailerStatesAndAttributes

den Schwellenwert für den getDistanceToUnloadPosition(vehicle) auf 75 zu setzen?
` if vehicle.ad.mode == AutoDrive.MODE_PICKUPANDDELIVER or vehicle.ad.mode == AutoDrive.MODE_LOAD then
        if getDistanceToTargetPosition(vehicle) > 25 and getDistanceToUnloadPosition(vehicle) > 75 then
            AutoDrive:setTrailerCoverOpen(trailers, false);
        else
            if vehicle.ad.mode ~= AutoDrive.MODE_LOAD or getDistanceToUnloadPosition(vehicle) <= 75 then
                AutoDrive:setTrailerCoverOpen(trailers, true);
`

Damit öffnet er die Abdeckung eher, und meine Kombisaatgutmaschine wird befüllt. (Vorausgesetzt ich setze nur 1-2 Wegpunkte vorher, weil du ja die Geschwindigkeit in Abhängigkeit der Wegpunkte drosselst ;-) )

Wäre klasse, wenn du dsa umsetzen könntest mit dem größeren Wert. 

Gruß
Carsten

**Comment by Stephan-S** [comment]
Macht vielleicht Sinn das ganze in eine eigene Einstellung auszulagern. So kann jeder für sich selbst bestimmen ob es ok ist, wenn ein Fahrer wenn er entsprechend früher einen Trigger erkennt entlädt bzw. auflädt.

Du scheinst dich ja mit dem Code auseinander zu setzen. Wenn du Lust hast, kannst du dich ja mal daran versuchen ;-)
AutoDrive:getSetting("maxTriggerDistance", vehicle) statt der 25 nutzen und die Einstellung erstellen :D 
Ich nehms sonst mal ins nächste Wochenende mit. Vielleicht auch mal gründlicher mit korrekter Triggererkennung, also Abbremsen unabhängig vom Wegpunkt.



> (Vorausgesetzt ich setze nur 1-2 Wegpunkte vorher, weil du ja die Geschwindigkeit in Abhängigkeit der Wegpunkte drosselst ;-) )

In der aktuellen Codebasis habe ich das zumindest mal auf Distanz angepasst ;-)
Aber wie gesagt, nächstes WE, für dieses lange Wochenende hab ich die ****** voll :D 

Jetzt mach ich mal Feierabend :-)

Schönen Sonntag noch und viele Grüße,
Stephan

**Comment by geo-luchs** [comment]
Hi Stephan

Ja bin in den Code eingestiegen.
Leider entnervt aufgegeben. 
Hat jetzt komischerweise mit meinem Test in der 1.0.5.8 num ich nicht mehr geladen.
Klappe ist aufgegangen.
Bin jetzt leider 2 Tage weg und ab Freitag ic Urlaub.

Und es scheint , selbst wenn es mit 1.0.5.8 klappen würde, mit deiner letzten großen Änderung bzfl. Abbremsen zu kollidieren.
Da hast du ja umgestellt gehabt von Anzahl wegpunkte auf Entfernung zum Zielpunkt. 

Daher muss man das im Zusammenhang sehen als größeres issue. Aber ich bleibe dran. Falls ich was brauchbares hab werde ich es mit dir mal durchsprechen

**Comment by Stephan-S** [comment]
Das Beladen sollte ja nun auch it größeren Abständen klar kommen (Einstellbar). Ich mache hier mal zu
