### ISSUE TITLE
AD findet den Weg nicht

### ISSUE THREAD

**Issue by RudiBergfeld** [Stephan-S/FS19_AutoDrive#589]
Hallo Stepahn,
ich muss dich leider Entteuschen der AD Fahrer auf der Multimap findet den weg manchmal nicht das setsame ist das das eine Fahrzeug den Weg findet und das andere nicht obwohl das Fahrzeug gade vorher an dem Ziehl war. Also Fehler in der Curse aufzeichnung würde ich asschlißen.
[log.txt](https://github.com/Stephan-S/FS19_AutoDrive/files/3694300/log.txt)

**Comment by FarmerLupo** [comment]
Hi Stephan und Rudi,
ich erlebe das auch mit Fahrzeugen aus dem "FS19_lsfmTransportpack":
Der MAN 26.nnn kann keinen Weg berechnen und der 18.nnn fährt zwar los, zieht dann aber selbst bei auf 20km reduzierte Geschwindigkeit nur Kreise.
Beide sollen einen HOLMER TT4-40 abladen.
[log - Kopie.txt](https://github.com/Stephan-S/FS19_AutoDrive/files/3743269/log.-.Kopie.txt)

**Comment by FarmerLupo** [comment]
Hallo zusammen, 
das von mir oben beschriebene Irrfahrtproblem ist mit Release 1.0.6.4 behoben, die betreffenden Fahrzeuge fahren jetzt prinzipiell korrekt, aber ein bisschen zu weit über das Abladerohr hinaus....
Release 1.0.6.5 habe ich noch nicht getestet.
