### ISSUE TITLE
Abfahrer hinter Häcksler bleiben stehen

### ISSUE THREAD

**Issue by Spielbauer** [Stephan-S/FS19_AutoDrive#590]
Hallo an das AD Team. Meine Abfahrer schalten sich aus, siehe Issue #586  und bleiben hinter dem Häcksler stecken da sie zur falschen Seite abfahren. D.h. sie fahren während dem laden links vom Häcksler, wollen aber dann rechts vorbei zum abfahren. Da der Häcksler dann aber schon steht gehts auch mit dem Abfahrer nicht mehr weiter. Habe daher schon den Füllgrad heruntergesetzt was aber auch nicht immer funktioniert.

Version 1.0.6.1
[log.txt](https://github.com/Stephan-S/FS19_AutoDrive/files/3694302/log.txt)

**Comment by Stephan-S** [comment]
Stell mal das Abfahren ab Level auf 100%. Dann fängt er nicht mit der Wegberechnung an, während der Häcksler noch fährt und sollte sich einen entsprechend freien Weg suchen

**Comment by Spielbauer** [comment]
OK, probiere ich aus und melde mich dann wieder. Die ganze Sache ist auf dem Vorgewende passiert und ich hatte da als Grundeinstellung die 100% gewählt. Erst danach habe ich den Füllgrad reduziert.

**Comment by Spielbauer** [comment]
So, ich habe es jetzt nochmal mit der Grundeinstellung 100% probiert. Die Abfahrer fahren jetzt bis auf ein paar Kreise gut an den Häcksler und auch wieder weg. Das ist jetzt auf den normalen Feldreihen. Nur am Reihenanfang, beim wenden, kommt es immer wieder mal zu Problemen, da der Abfahrer nicht am Häcksler vorbei  kommt (siehe Bild). Ich probiere das mal mit einem kürzeren Gespann. Allerdings schalten sich die Abfahrer bei bald jeden 3. Ladevorgang ab. 
![fsScreen_2019_10_06_15_21_42](https://user-images.githubusercontent.com/54139649/66270182-92d57080-e850-11e9-8da9-7322b561daa8.png)

**Comment by Stephan-S** [comment]
Danke für das Feedback. Du nutzt also mehrere Abfahrer gleichzeitig, korrekt?
Welche Einstellung nutzt du dann für die Feldausfahrt?

**Comment by Spielbauer** [comment]
Hallo, für die Feldausfahrt nutze ich "Hinterm Start". Ich nutze 3 Abfahrer. Es geht manchmal eine Zeit lang. Dann bleibt ein Abfahrer nachdem er voll ist stehen und blockiert.
Habe noch mal auf einem Vorgewende angefangen. Der Abfahrer hat Fruchtumfahrung "Nein". Er will hinter dem Häcksler durch das Feld und bleibt wieder stecken (siehe Foto).
![fsScreen_2019_10_06_16_53_21](https://user-images.githubusercontent.com/54139649/66271062-0a5bcd80-e85a-11e9-8b25-7c6c4e923095.png)
Bei diesem Abfahrer habe ich Fruchtumfahrung "Ja". Er biegt direkt vor dem Häcksler ab und schiebt ihn aus der Bahn.
![fsScreen_2019_10_06_17_05_40](https://user-images.githubusercontent.com/54139649/66271227-c9fd4f00-e85b-11e9-98b0-36e711eef327.png)
Hier bleibt der Abfahrer ohne erkennbaren Grund stehen. Vielleicht wg. dem Gelände (F10 Multimap 2019)
![fsScreen_2019_10_06_17_02_17](https://user-images.githubusercontent.com/54139649/66271244-0e88ea80-e85c-11e9-86ee-4c983d61e05c.png)
Hoffe du kannst daraus etwas für dich gebrauchen. Übrigens, der Abfahrer fuhr hinter dem Häcksler her wenn auf beiden Seiten die Frucht stand.

**Comment by Spielbauer** [comment]
Eine Frage an die Programmierer. 
Ist es überhaupt notwendig bzw. von Nutzen, einen Kurs rund um ein Feld anzulegen, um die Abfahrer schneller einen Kurs finden zu lassen. Manchmal habe ich das Gefühl als würde gerade dieser Kurs die Abfahrer noch mehr verwirren und die Berechnung dauert länger. Zudem sie dann den naheliegendsten Kurs trotzdem nicht nehmen.

**Comment by Stephan-S** [comment]
Also ich habe noch nie einen Weg um die Felder aufgezeichnet. Sollte normalerweise nicht nötig sein. Aber es gibt sicher auch Situationen in denen es Sinn macht

**Comment by Spielbauer** [comment]
Letzte Frage, danach kann man zumachen.
Ist es eigentlich notwendig, dass der Abfahrer wenn er am Drescher bzw. Häcksler abgetankt hat, immer zuerst an den Startpunkt zurückfährt und erst ab da zum Ziel. Er könnte doch sofort den nächsten Weg zum Ziel nehmen.  Die Wegpunkte sind ja da.
Danke und danke für die viele Arbeit die ihr euch macht.

**Comment by haamic** [comment]
Welchen Modus für das Feld verlassen hast du denn eingestellt? Es gibt ja Standard, hinterm Start, nächstgelegenen. Ich glaube beobachtet zu haben bei mir wenn ich Einstellung habe nächstgelegenen, dann schreibt er zwar , er fährt zum Start zurück , aber sobald er einen Wegpunkte Findet der ihn zum Ziel bringt nimmt er den und fährt dahin. Deswegen  mache ich auch meist einen Rundkurs in blau mit AD ums Feld

**Comment by Spielbauer** [comment]
@haamic , ich habe als Feldausfahrt "Hinterm Start" gewählt, da ich nicht alle Felder mit blauer Linie umfahren hab.  Die Frage hab ich an Stephan gerichtet. Siehe 4 Beiträge höher. Ich würde das ja auch machen hab aber immer das Gefühl die Abfahrer juckt die blaue Linie nicht. Heute hab ich mit Häcksler ein Feld nur mit Anfahrkurs eingerichtet und die Abfahrer sind einige zeit ohne Probleme gefahren.  Am besten wäre es wenn man einen Anfahr- oder Startpunkt für die Abfahrer und einen Abfahrpunkt für die Abfahrer angeben könnte. Aber ich denke dass lässt sich nicht umsetzen.
