### ISSUE TITLE
Zweiten Abfahrer frühzeitig rufen

### ISSUE THREAD

**Issue by bgo1973** [Stephan-S/FS19_AutoDrive#591]
Beim letzten Video von Cairo kam mir die Idee, das es ja von Vorteil wäre, wenn der gerade am Drescher aktive Abfahrer die Möglichkeit hätte, einen etwaigen Kollegen auch bei einem gewissen Füllstand zu rufen. Gerade beim Häcksler Abfahren würde das dann ein unterbrechungsfreies Abfahren ermöglichen.
Auch sollte der Abfahrer beim Anfahren an den Drescher, wenn dieser das Rohr in der Frucht hat, mehr Abstand halten, da der Drescher ja zum Entladen dann zurücksetzt.
Und der Abfahrer sollte, wenn der Drescher am Ende der Spur angelangt ist, also keine Frucht mehr vor sich hat, rechtzeitig abdrehen.

**Comment by FS-UK-TheMan1988** [comment]
+1

**Comment by Iwan1803** [comment]
Da es für Drescher/Häcksler seit ein paar Versionen in den Einstellungen vorhanden ist -> closed.
