### ISSUE TITLE
1.0.6.1 bugs so far

### ISSUE THREAD

**Issue by FS-UK-TheMan1988** [Stephan-S/FS19_AutoDrive#592]
Bugs. on dedicated server.

fill level is not working when using the forager. driver leaving at 43% 

avoid fruit not working at all. if i says no, it still tries to go around

offset inc. pipe not working at all. its very far away from the pipe

the A Ihave a lot of trouble finding the forager driver and stay with him.

The precall does not work. driver stays until fill level 100% or 43% is reached

**Comment by FS-UK-TheMan1988** [comment]
so the current source files fixes a lot, but fill level is still not working(when the driver leaves the field) the precall when using forager is only calling one driver, so there is a lot of waiting for the next trailer.

**Comment by gigilal** [comment]
I can also post what issue I have found on my dedicated server. when using "Pickup and deliver" 
The AI picks up the grain and drives to the location - when he is close to the "Sellpoint" he just Stops and wont drive anymore.

On my other Sellpoint he drives to the sellpoint and just stops and I need to manually Sell the Grain.

**Comment by gigilal** [comment]
![20191012182635_1](https://user-images.githubusercontent.com/47475839/66704642-23fb8a00-ed1e-11e9-9310-360c8f852a69.jpg)

**Comment by FS-UK-TheMan1988** [comment]
i have that issue as well.

plus whn using the forager and a pickup(for grass) the tractor wont chase the forager

**Comment by gigilal** [comment]
Noticed something new today is that I have "Park in Field on" But when he has unloaded the Combine he drives to start. FYI :)

**Comment by FS-UK-TheMan1988** [comment]
> Noticed something new today is that I have "Park in Field on" But when he has unloaded the Combine he drives to start. FYI :)

what is the fill level?

**Comment by Stephan-S** [comment]
All these bugs are also contained in other open issues, so I#m closing this one for now. Thanks for your input!
