### ISSUE TITLE
Unload combine: unload destination changes

### ISSUE THREAD

**Issue by Martinnygaard** [Stephan-S/FS19_AutoDrive#593]
Hi,

I think this issue happend after updating til 1.0.6.1.
I have a tractor driving betweek "Field 22 - NW" and "MainFarm - Silo Unload".
![ad2](https://user-images.githubusercontent.com/26490587/66299374-ad145a80-e8f3-11e9-84ae-12d60d6b7301.png)

As soon as the driver reaches "MainFarm - Silo Unload", the target destination for unloading changes to "MainFarm - Silo - LoadPoint". (That is thew target directly above "silo unload" in my dropdown menu)

![AD1](https://user-images.githubusercontent.com/26490587/66299627-2a3fcf80-e8f4-11e9-8410-05430f608391.png)

I have no idea why, but it happens at every unload trip.

**Comment by Stephan-S** [comment]
Do you have the option "Multiple targets" enabled in the settings?
This is a new feature, which selects a new target after each unload to distribute between silos, sell points or multiple lanes in a drive through bunker silo

**Comment by Martinnygaard** [comment]
Ohh dammit... Yes i had. Sorry.
I thought that meant multiple combines on the field.....
