### ISSUE TITLE
XML file 'AutoDrive_Ravenport_init_config.xml' is too big

### ISSUE THREAD

**Issue by Absolomx** [Stephan-S/FS19_AutoDrive#594]
I have a dedicated server and it says that it has 1 issue with the autodrive mod: XML file 'AutoDrive_Ravenport_init_config.xml' is too big

It's 0.32 mb so above the 0.25 mb it should be max.

**Comment by Stephan-S** [comment]
Can be safely ignored. Just a warning that would apply to for example a vehicle mod. But with the script mod, this is nothing to worry about
