### ISSUE TITLE
3x "Gras" im Drop-Down Menü

### ISSUE THREAD

**Issue by TobiHH78** [Stephan-S/FS19_AutoDrive#595]
Hallo,
mal eine Verständnisfrage. Bei den Ladegütern gibt es im Auswahlmenü 3x die Sorte Gras. Ich habe bislang noch keinen Unterschied festgestellt.  Gibt es einen Grund, warum Gras mehrfach aufgeführt wird?

**Comment by Martinnygaard** [comment]
I have noticed that issue for a very long time. (as long as i can remember, i think?)

**Comment by Ralf-B** [comment]
Das es 3x Gras Gibt liegt an GIANTS, es wenden im Spiel auf fast allen Karten drei Grassorten aufgeführt.
AutoDrive zeigt im Auswahl Menü nur an was auf der akuellen Karte verfügbar ist.
![Screenshot (1)](https://user-images.githubusercontent.com/54984457/66473357-60658680-ea8f-11e9-9da6-7444ba9acad1.png)
![Screenshot (2)](https://user-images.githubusercontent.com/54984457/66473523-b6d2c500-ea8f-11e9-9bca-de263680f339.png)
