### ISSUE TITLE
Pickup and deliver: Drops silage in BGA bunker, instead of sell point

### ISSUE THREAD

**Issue by Martinnygaard** [Stephan-S/FS19_AutoDrive#596]
I have for a long time been selling silage from my farm at the BGA.
A truck is driving a "pickup and deliver" route from "MainFarm - Fermenter" to BGA sellpoint.
![AD BGA sellpoint](https://user-images.githubusercontent.com/26490587/66334548-909b1100-e939-11e9-9020-eb36d873755a.png)

But sometimes, he drives pass it, through the bunker (which i use as exit) and as soon as it exits the bunker, it starts to unload on the ground while driving.

![AD BGA sell](https://user-images.githubusercontent.com/26490587/66334613-af99a300-e939-11e9-9c95-a06c3ccf6232.png)

Also, when reacing the loading target, the trailer does not remove the cover automaticly anymore.
![cover](https://user-images.githubusercontent.com/26490587/66334851-1f0f9280-e93a-11e9-845d-9f0930590f37.png)

**Comment by Stephan-S** [comment]
Sorry, but could you verify that both issues (cover and not unloading at correct point) are still valid? Thank you!

**Comment by Martinnygaard** [comment]
Hi,

I am not sure what happened. 
I cant reproduce it as of now.
I will reopen if i see the problem again - untill then: Closed :-)
