### ISSUE TITLE
Drescher abfahren funktioniert nicht mehr richtig

### ISSUE THREAD

**Issue by Caliban2017** [Stephan-S/FS19_AutoDrive#597]
Hallo, 

habe nun mal die neuste Version 1.0.6.2 probiert und auch die 1.0.6.1 war schon entsprechend fehlerhaft. Leider ist es uns nicht mehr möglich den Drescher abfahrer zu benutzen. Früher ging es noch ohne probleme in den Versionen, in denen das Drescher folgen noch nicht gab. Wenn man den Drescher so einstellt, das der Abfahrer folgen soll, dann fährt der Abfahrer einfach am Drescher vorbei und am nächsten Pfad auf den er trifft (außerhalb des Feldes) biegt er plötzlich ab und sucht sich wieder seinen Ausgangspunkt am Feldrand. Bei einem anderen versuch ist der Abfahrer losgefahren und er war nicht mal auf dem Feld und fuhr plötzlich nur noch im Kreis mit der Meldung das sich der Abfahrer festgefahren hat. 

Leider zieht sich das auch in die klassische Art rein abzuladen, indem man einfach per Tastenkombination den Abfahrer ruft. Ging früher noch ohne Probleme, jetzt fährt er zwar los aber entweder er hält viel zu weit vom Rohr des Dreschers weg (Abstand wurde bereits korrigiert) oder er schafft es zwar den Drescher abzutanken aber statt zum Feldrand zurück zu fahren, fängt er mittem auf dem Feld wieder an nur im Kreis zu fahren mit der Meldung das er sich festgefahren hat.

 Also leider macht der Abfahrer nur noch Probleme in der aktuellen Version leider und ist nicht mehr nutzbar.

Einen Fehler im Log produziert er nicht...

Viele Grüße

**Comment by Stephan-S** [comment]
Danke für die Meldung! Da habe ich beim Code aufräumen übersehen die Kollisionserkennung für's Schneidwerk auszuschalten beim Abfahrer
