### ISSUE TITLE
Autodrive speichert immer nur einen Haltepunkt

### ISSUE THREAD

**Issue by Zottel33** [Stephan-S/FS19_AutoDrive#598]
Ich habe das Problem das Autodrive (1.0.6.2) immer nur einen Haltepunkt speichert.
Beispiel. Ich lege den Haltepunkt "Händler" an. Diesen kann ich dann auswählen und jede Maschine findet den Weg dahin.
Dann lege ich den Haltepunkt "Hof Silo" an. Nun hab ich im Menü die Auswahl zwischen "Händler" und "Hof Silo". Wenn ich nun "Hof Silo" auswähle fährt die entsprechende Maschine dort hin.
Der Haltepunkt "Händler" ist nun nicht mehr in der Liste. 

Es scheint so als hätte das Dropdown Menü einen Fehler... Über der Pfeile rechts und links finde ich die Haltepunkte

Gibt es hierfür eine Lösung oder mache ich einfach nur einen Fehler?

**Comment by Stephan-S** [comment]
Hast du mal in der Liste gescrollt? Einfach mit dem Mausrad ;-)

**Comment by Zottel33** [comment]
Sorry für meine Dummheit! Ich habe alles versucht nur das blöde Mausrad nicht gedreht....

Ach ja super Arbeit was du hier leistest!!! 
Das ist eine große Bereicherung für das ganze Spiel!
