### ISSUE TITLE
(Um)Frage: Abladen eines mittels Überladewagen befüllten Abfahrers komplett mit AD??

### ISSUE THREAD

**Issue by haamic** [Stephan-S/FS19_AutoDrive#599]
Hallo ,
ich teste gerade bisschen mit einem Überladewagen.
Ich habe da eine Frage zum Handhabung eines Überladewagens und dem Abfahrer zum Silo.
Wie macht ihr das, wenn ihr ein Feld mit Drescher (D) aberntet, 
der in einen Überladewagen (Ü) entlädt und dieser den, am Feldrand wartenden, 
Abfahrer (A) zum Silo belädt?
Soweit ist es klar, das der Drescher mit CP fährt und der Überladewagen mit AD den Drescher entlädt und die Ladung zum Abfahrer fährt. Muss der Abfahrer dann wieder CP gesteuert sein, oder gibts mit AD eine Möglichkeit ? Hatte zumindest keinen Erfolg.
Hat jemand eine andere funktionierende Variante als meine D=CP , Ü=AD, A=CP ?
Schönen Abend
Micha

**Comment by Knowen** [comment]
Moin,
also ich teste da selber gerade etwas rum.
Drescher(D) fährt bei mir mit CP, der Überladewagen(Ü) ebenfalls mit CP (Mode2) und final der Abfahrer(A) Richtung Silo mit AD.
Funktiniert zu 80% reibungslos. Ab und an fährt Ü in D.
A ist bei AD mit dem Modus "Abholen und Abliefern" unterwegs. Abholen ist der Punkt am Feld und Abliefern halt am Silo. Das funktioniert super. 
Den Ü via AD fahren zu lassen habe ich noch nicht probiert und wüsste auf anhieb gar nicht, wie man das einstellen sollte. Also von dem Netzaufbau usw.

**Comment by Woife1** [comment]
für den Überladewagen mit AD brauchst du eigentlich nur 2 Wegpunkte am Feld
einen als Wartepunkt und einen zum entladen

ob sich AD gegen Überladewagen wehrt keine Ahnung müsstest mal ausprobieren


ohne Trigger im Kurs streikt doch CP in Mode 2 oder nicht?

**Comment by haamic** [comment]
@Knowen
A mit AD hab ich probiert, verschiedene Modi hat aber nicht geklappt. Gibts ja kein Silo trigger den AD erkennen kann. Oder wird das Überladerohr nach Neustart erkannt? Da kann vielleicht @Stephan-S etwas dazu sagen. 
Bei A mit CP in Mode 2 fuhr er zumindest los, das war mein Test. Ob er tatsächlich am Silo abgeladen hätte hab ich nicht probiert. Über die AD Kurse im CP Ordner hab ich es aber nicht hinbekommen, da findet er streckenmässig nicht zurück. Bzw legt die Strecke komisch, nicht da wo momentan der Abfahrer steht. Aber da kenn ich mich nicht aus, wie CP mit den enthaltenen AD zielen umgeht. Nur wenn ich selber mit CP den Kurs zum Silo und zurück einfahre geht es.

**Comment by ThisPf** [comment]
> für den Überladewagen mit AD brauchst du eigentlich nur 2 Wegpunkte am Feld
> einen als Wartepunkt und einen zum entladen
> 
> ob sich AD gegen Überladewagen wehrt keine Ahnung müsstest mal ausprobieren
> 
> ohne Trigger im Kurs streikt doch CP in Mode 2 oder nicht?

Es geht, wenn du einen Wartepunkt setzt. Ich mache das zurzeit auch so.

**Comment by Knowen** [comment]
Der Kurs für den Ü ist nur 12 Wegpunkte oder so lang. 
Aufnahme starten, zu A fahren und wenn das Rohr vom Ü über dem Anhänger von A ist, einen Wartepunkt setzen und dann weiter fahren. total easy. Wenn man dann Ü startet muss man nur noch die Haltezeit einstellen.

**Comment by haamic** [comment]
Wie schon geschrieben, mache ich den Ü mit AD. da hat es eigentlich funktioniert das er den A belädt. Nur den A hab ich mit AD nicht zum Abfahren Richtung Silo gebracht.

**Comment by Knowen** [comment]
A stellst du auf "Abholen und Abliefern" ein. Abholen soll er am Feld, also dein Feldpunkt z.B. Feld_1. Ziel ist dann dein Silo oder Verkaufsstelle. Dann natürlich noch den Fruchttyp auswählen, den du gerade erntest und transportieren willst.
A wartet dann solange am Feldpunkt bis er seine prozentualle Füllung (die du in den Einstellungen von AD einstellst) erreicht hat.

**Comment by haamic** [comment]
So hab ich es eigentlich probiert, denke ich.
Ich hab gedacht, es geht deswegen am Feld nicht, weil da ja kein trigger ist, wo er theoretisch wartet bis er den füllstand erreicht, so wie sonst eigentlich am Silo. 
Oder hatte ich die Option bei Silo leer weiterfahren an? Ich teste es noch mal.

**Comment by ThisPf** [comment]
Du kannst die Wartezeit schätzen oder messen (beim Kinze Überladewagen mit 30'000 lt. Inhalt ziemlich genau 30 Sek.) oder du machst es so, dass der Abfahrer am Endpunkt unter dem Rohr steht. Der Haltepunkt ist dann nur dazu da, dass sich CP nicht aufhängt, weil kein Abladetrigger auf dem Kurs liegt. Haltezeit auf eine Sekunde einstellen dass er dort gleich wieder los fährt.

**Comment by haamic** [comment]
> A stellst du auf "Abholen und Abliefern" ein. Abholen soll er am Feld, also dein Feldpunkt z.B. Feld_1. Ziel ist dann dein Silo oder Verkaufsstelle. Dann natürlich noch den Fruchttyp auswählen, den du gerade erntest und transportieren willst.
> A wartet dann solange am Feldpunkt bis er seine prozentualle Füllung (die du in den Einstellungen von AD einstellst) erreicht hat.

@Knowen 
Also ich hab es probiert wie du geschrieben hast. A fährt erst los, wenn 100% voll, egal ob man weniger in AD einstellt . ich hatte zum Test nur 10 % probiert, da passierte nichts. 
Soweit gehts also mit D=CP, Ü=AD, A=AD. Allerdings dreht der Ü unnötige Kreise auf dem Weg um Wege zu finden. Sieht so aus, als will er Punkte erreichen, die mit dem Wendekreis des Fahrzeuges nicht zu erreichen sind. Drescher folgen klappt gar nicht.  da fährt der Ü mit ausgeklappten rohr rum, aber nicht hinter dem Drescher. Per alter methode, fährt er zum Drescher wenn er voll ist, und klappt am start das rohr ein und erst am Drescher aus.
Damit kann ich leben. Solang die alte Methode erfolgreich ist.
Danke für eure tipps.
Gruss Micha

**Comment by Knowen** [comment]
Also die Wartezeit stelle ich immer grob ein. Ich fange mit 30 Sek an und wenn ich merke, dass das zu wenig ist erhöhe ich oder halt verringere ich die zeit, wenn es zu viel ist. Letztendlich kommt es aber nicht auf 5 Sek an.

**Comment by Stephan-S** [comment]
Ich mache hier mal zu, damit ich Übersicht behalte.
Falls ich hier was wichtiges überlesen habe, bitte melden.
