### ISSUE TITLE
Mouse and HUD

### ISSUE THREAD

**Issue by Williwillswisse** [Stephan-S/FS19_AutoDrive#6]
Hallo Stephan,
seit deiner letzten Änderung kann ich im SP das HUD und die Maus nicht mehr ein-/ausblenden.

**Comment by Anonymous-any** [comment]
Hi, and if you click the X of HUD for close, then right click mouse is glued on the window without it can leave it :)
I also got Courseplay maybe a conflict with both.
<s>I just try your last version change but without mouse to click idk how we can use AD ^^.</s>
I did have too a issue yesterday and 2 day ago (I did not keep the logs error linked I'm bad) I did try to investigate a bit for it, and my route file contained doubles destinations that go on wrong destination with wrong name of it, and more I was try to delete the wrong double destinations I've not put to try to solve this and more I had doubles dest. in at the end of file.
After that I tried to import a save from an export file I made before (I add I was deleted the route file in savegame) and it seem AD do not recreate the file ?
Now continuing my path for investigate more.

BR

**Comment by Anonymous-any** [comment]
Back again late :/
It seem when import folder is created after savegame and quitting game like "q" console AD file_config in savegame is writed into import folder for me where I see it was updated... strange

**Comment by Anonymous-any** [comment]
Followed,
I don't know if I must open a new issue or continue here for this one ?

Edit: 
and if you click the X of HUD for close, then right click mouse `"input_ADToggleMouse"` nothing happen. But if we do showing HUD `"input_ADToggleHud"` make mouse glued on the window without it can leave it :) <- and this state never come back, we need to reload the game session to it work back.
I was thinking Courseplay maybe a conflict with both. <- Then it's not a conflict cause I did not load it but another mouse issue exist with both... (I think it came from Courseplay) where we need to open 2 times click mouse to have access to AD but it not the about of this X HUD close.

Br
