### ISSUE TITLE
2 beidseitig befahrbare Strecken verbinden

### ISSUE THREAD

**Issue by Rumspringa90** [Stephan-S/FS19_AutoDrive#600]
Moin,

ich hab eine Frage:
Ich habe eine beidseitig befahrbare Strecke angelegt und wollte diese dann verlängern. Aber beim verbinden hat er immer nur eine einseitig befahrbare Strecke angelegt. Ist das Momentan nicht möglich? Oder mach ich etwas falsch?

Gruß Henne

**Comment by Caliban2017** [comment]
Falls du damit meinst, dass zwischen den Pfaden ein grüner Pfeil erstellt wird, statt einem blauen/lila Pfeil, das ist normal aber dafür gibt es eine Lösung. Beim verlängern ist wichtig das natürlich der Record Modus auf den blauen Punkt steht, damit ein blauer Pfad erstellt wird. Der grüne Pfeil der am Anfang entsteht kann zu einem blauen umgewandelt werden. Dazu ans Ende des Pfeils fahren, damit der rote Marker auf die Pfeilspitze zeigt. Von dort aus muss dann als Ziel zum verbinden von Wegpunkten zum start des grünes Pfeils gewählt werden. Anschließend verbinden, dann wird der grüne Pfeil zu einem blauen. Es muss also aus einem -> Pfeil ein <-> Pfeil gemacht werden.

**Comment by Stephan-S** [comment]
Danke @Caliban2017
