### ISSUE TITLE
Blaue und Grüne Linen 

### ISSUE THREAD

**Issue by FarmingPower** [Stephan-S/FS19_AutoDrive#601]
Hallo, 

ich habe mal eine frage bezüglich den Einfahrten von den grünen auf die blauen Linien.
Ich bespiele eine 4Fach Map mit relativ vielen schmalen Feldwegen, da ich aber auch an solchen Wegen mehrere ein und ausfahrten auf die Hauptstrassen gemacht habe bleiben die Maschinen ja bekanntlich vor der Blauen Linie Stehen wenn ein Fahrzeug sich auf diesem Kurs befindet ( Bild ist beigefügt).
Jetzt meine Frage besteht dort eine Möglichkeit etwas einzubauen das, dass entgegenkommende Fahrzeug mehrere Meter vor der Einfahrt stehen bleiben kann so das eine Kollision vermieden werden kann ?

![fsScreen_2019_10_08_14_52_38](https://user-images.githubusercontent.com/46539798/66397473-31420d00-e9dc-11e9-98a6-99e77ce103e8.png)

**Comment by Stephan-S** [comment]
Derzeit halten die Fahrer ~5 Wegpunkte (die genaue Zahl müsste ich nachlesen, aber man sieht es ja in deinem Bild).
Wenn du hier keine Überlappung zwischen den grünen und blauen Strecken einbaust, sollte der Abstand ja reichen.

![66397473-31420d00-e9dc-11e9-98a6-99e77ce103e8](https://user-images.githubusercontent.com/5493976/66401431-73bb1800-e9e3-11e9-963f-9eca6f4d4130.png)

Ich habs dir mal ganz grob da reingemalt wie es funktionieren würde

**Comment by FarmingPower** [comment]
Vielen dank für die Rückmeldung. Werde die grüne Linie mal bearbeiten und dann nochmal Testen.
