### ISSUE TITLE
Combine Offload Question, Suggestion.

### ISSUE THREAD

**Issue by Tadeloach** [Stephan-S/FS19_AutoDrive#602]
So I was curious?  What makes the combine call the driver.  The reason I ask is if you are using a hired driver or Course Play to operate the combine, when they reach the end of the field work, they just chill there and don't call the drive to offload.  You have to manually take control of the offload vehicle, drive him to the combine, offload, then power Autodrive back up and send him to the sell point.  Is there anyway to get the combine to call the driver automatically when he is done with the fieldwork?

**Comment by wlfheart** [comment]
I would think there would be a way to expand the scan range or whatever it
uses. CP has no problem with this in mode 2. But field 5 is not that big of
a field. Possibly LOS issue? Maybe add an ability to search the field
manually as in CP?

**Comment by Tadeloach** [comment]
See, Here is an example.  The combine drive is done, has reached the end of the field work, the autodrive unloader is just chillin there waiting for the combine to call, or me to send him on his merry way.  It would be cool if we could figure out a way for the combine drive to call him when he is done, fill him up, then send him on to the sell point.  I know its not a big deal to do myself, but it would mean less babysitting.

![image](https://user-images.githubusercontent.com/56048034/66412166-9c7ae780-e9ba-11e9-9906-af60e139a737.png)

**Comment by Stephan-S** [comment]
You can call the unloader manually. Auto calling would have to be done by CP not AD in this case.
