### ISSUE TITLE
Add negative values to pipe offset / check correct direction of offset for potato harvesters

### ISSUE THREAD

**Issue by Tadeloach** [Stephan-S/FS19_AutoDrive#603]
So here is my next issue.  Can a negative pipe offset be added for harvesters that have an unload point on the right side of the vehicle?  I am having this issue every time I have to use the Potato harvester.
I set the offset to 0, but he still collides, go higher and its worse.

The only way I can get this to work is to use Courseplay in Mode 2 which I hate the way it drives the autodrive courses on the street.

![image](https://user-images.githubusercontent.com/56048034/66418231-3ea0cc80-e9c7-11e9-95c9-5cdc6adeb771.png)

**Comment by Bandesss** [comment]
Abstand einstellen :) 1.0 meters

**Comment by Triple5soul89ny** [comment]
For this Problem I use Autodrive to make CP Courses to the unloadpoint. Just Start a nee course for CP an let AD drive. Thema save the CP course. Now CP uses the Speed and Brakepoints form AD

**Comment by Tadeloach** [comment]
Hey that makes perfect sense. I never though about letting autodrive run
its route while letting courseplay record it! Good stuff!!  I hope they
eventually figure out a way to have courseplay run mode 2 and hand off to
autodrive to unload.

**Comment by Tadeloach** [comment]
@Stephan-S,
I was able to do this by changing the following in the AutoDriveSettings.lua

AutoDrive.settings.pipeOffset = {  
    values= {-5.0, -4.75, -4.5, -4.25, -4.0, -3.75, -3.5, -3.25, -3.0, -2.75, -2.5, -2.25, -2.0, -1.75, -1.5, -1.25, -1.0, -0.75, -0.5, -0.25, 0,
     0.25, 0.5, 0.75, 1.0, 1.25, 1.5, 1.75, 2.0, 2.25, 2.5, 2.75, 3.0, 3.25, 3.5, 3.75, 4.0, 4.25, 4.5, 4.75, 5.0},
    texts= {"-5.0m", "-4.75m", "-4.5m", "-4.25m", "-4.0m", "-3.75m", "-3.5m", "-3.25m", "-3.0m", "-2.75m", "-2.5m", "-2.25m", "-2.0m", "-1.75m", "-1.5m",
     "-1.25m", "-1.0m", "-0.75m", "-0.5m", "-0.25m", "0 m",
     "0.25 m", "0.5 m", "0.75 m", "1.0 m", "1.25 m", "1.5 m", "1.75 m", "2.0 m", "2.25 m", "2.5 m", "2.75 m", "3.0 m", "3.25 m",
     "3.5 m", "3.75 m", "4.0 m", "4.25 m", "4.5 m", "4.75 m", "5.0 m"},
    default= 4,
    current= 4,
    text= "gui_ad_pipe_offset",
    tooltip= "gui_ad_pipe_offset",
    translate= false,
    isVehicleSpecific = true
};

It has worked like a charm and now I don't have to baby sit the potato harvester anymore!!
