### ISSUE TITLE
CP and AIVehicleExtension are using driver wage from AD

### ISSUE THREAD

**Issue by bojanh66** [Stephan-S/FS19_AutoDrive#605]
My courseplay and AIVehExtension workers are using driver wage from AD option driver wage %.
Is this a bug in AD ?

**Comment by Stephan-S** [comment]
Thank you for pointing this out to me. I totally overlooked this fact. This is fixed in the latest sources now. Thank you!

**Comment by bojanh66** [comment]
I have updated AD to latest version and tested again, AI Vehicle Extension is still using driver wage from AD :/

**Comment by Stephan-S** [comment]
Release version or current source files?

**Comment by bojanh66** [comment]
Current source files.

**Comment by Stephan-S** [comment]
I will have to check myself, but I added ' and self.ad.isActive' before any money is deducted and therefore this should not be possible.
Are you sure it's the AD wages that are deducted?

**Comment by bojanh66** [comment]
Yes, because when i have active combine harvester AIVehicleExtension and when i change driver wage from AD options, it reduced my money.
If you could please check it again, tnx.
