### ISSUE TITLE
Trailer cover closing when unloading combine.

### ISSUE THREAD

**Issue by eddiem54** [Stephan-S/FS19_AutoDrive#607]
Hi Stephan,
Trailer pulls up alongside combine which starts to unload. Trailer cover closes immediately.
TDK1600 trailer, RSM161 combine

Regards.

**Comment by rgoe** [comment]
Same happened to me with TDK16000 and CR10.90 combine. I used latest version from github-repository at that point. Reverted back to 1.0.6.3 release and it's working again. May have something to do with latest commit yesterday.

**Comment by eddiem54** [comment]
Hi again,
I reverted back to 1.0.6.3 without the latest commit - "Improved trigger detection" and the unload works OK.

**Comment by pCornetto** [comment]
Hi there,

also have the issue with closing trailer cover.
Trailer departs from starting/waiting point and opens cover.
Once trailer stopped alongside combine for unloading, cover closes immediately.

Happend to me with regular TerraDos T4-40 and Krampe SB II trailer.
AD-Version 1.06.3 with "Improved trigger detection" was used.

Regards

**Comment by eddiem54** [comment]
Hi again Stephan,
Latest commit appears to have fixed this issue.
Thanks again.
