### ISSUE TITLE
Baumwolle fehlt mir

### ISSUE THREAD

**Issue by RudiBergfeld** [Stephan-S/FS19_AutoDrive#608]
Hallo 
in welcher Datei oder Wie kann ich Bamwolle hinzu Fügen

**Comment by Stephan-S** [comment]
Eigentlich wird jeder registrierte FillType aufgelistet. Mit Baumwolle habe ich mich bisher nicht beschäftigt. In was für Fahrzeuge kann man die denn überhaupt laden?

**Comment by worker2419** [comment]
Hallo Stephan, Baumwolle wird mir als Ladung auch nicht angezeigt, obwohl auf der Map vorhanden. Die Anhänger findest Du Baumwolltechnik

**Comment by Stephan-S** [comment]
Ja aber das sind doch Ballen die damit geladen werden. Kein normaler Filltype.
Kann man das irgendwo einfach beladen? Wie genau ist da der Ablauf? Das sind doch Ballen die vom Ernter kommen oder nicht? Stroh und Heuballen kann ich ja auch mit AD nicht laden.
Danke für die Infos :-)

**Comment by RudiBergfeld** [comment]
Das ist so nicht richtig,
Baumwolle Ballen lassen sich mit dem Cotten Tag Trailer und CP super Automatisch laden aber nicht mit AD verkaufen. Ich vermute Weil es keine möglichkeit im AD gibt ihm zu sagen das er Ballen mit Baumwolle hat

**Comment by Stephan-S** [comment]
Ballen werden vorerst nicht unterstützt.
