### ISSUE TITLE
Wendekreis zu groß für Pfadfindung, anpassen???

### ISSUE THREAD

**Issue by haamic** [Stephan-S/FS19_AutoDrive#610]
Hallo Stephan,
ich glaube du hattest letztens mal was geschrieben, wie gross der Wendekreis ist, der standardmässig von AD genutzt wird, wenn kein Wert vom Fahrzeug geliefert wird.
Ich finde dieses Issue leider nicht mehr, um nachzulesen.
Ich vermute, mein Überladewagen, den ich gerade teste, liefert keine Daten für den Wendekreis.
Er dreht Kreise auf dem Feld und findet den Pfad zum Drescher, oder zum nächsten Punkt in der Pfadfindung **nicht**, bricht sogar dann ergebnislos ab. AD nutzt eventuell einen zu Kleinen Wendekreis.
Ich habe nun mit dem Metermaß-Mod so einen Kreis mal gemessen und komme auf rund **18m** Durchmesser.
So wie sich der Fahrer verhält, sieht es so aus, als ist der Wendekreis viel zu gross, um den anvisierten Punkt zu treffen und seinen Weg zu finden.
Welche Lösung für dieses Problem würde helfen, ausser keinen Überladewagen zu nutzen?
Wo kommt der Wert für den Wendekreis normalerweise her? Wird der Berechnet, oder kann man den irgendwo eintragen (ÜL-Wagen.xml)? 
Hab das gleiche mit meinem grossen Anhänger gemacht, nachgemessen und der hat etwa 22m. Damit kommt AD super klar, sicher weil dieser Wert auch geliefert bzw. korrekt berechnet wird.

Weiterhin ist mir aufgefallen, das der ÜL mit **offenem** Rohr am Feldrand auf den Drescher wartet. Ruft der Drescher ihn früher, fährt er mit offenem Rohr los und versucht den Drescher zu erreichen. 
Lass ich das frühere Rufen weg und der Drescher ist voll, klappt der ÜL-Wagen das Rohr ein **bevor** er zum Drescher fährt. Das mit dem Rohr nur am Rande, scheint aber nicht die eigentliche Funktionalität zu beeinflussen.
Schönen Abend.
Gruss Micha

**Comment by Stephan-S** [comment]
Servus,
hab nicht viel Zeit aber hier mal auf die Schnelle aus der Giants Skript Doku, die Zeile die den Radius einliest für das jeweilige Fahrzeug/Gerät:
spec.turningRadiusLimitation.radius = getXMLFloat(self.xmlFile, baseName .. ".turningRadiusLimitation#radius")

Falls du sowas in der XML in anderen Hängern findest aber beim ÜLW nicht, kannst du dich ja mal an einem Fix probieren.

Achso und bist du dir sicher, dass du hier nicht teilweise Radius mit Durchmesser verwechselst? Das würde die 22m/11m erklären ;-)

Beste Grüße,
Stephan

**Comment by haamic** [comment]
im Anhängerverzeichnis gibts keine script datei nur die normale fahrzeug.xml und da steht sowas nicht drin.
Trotzdem danke für deine Antwort.

lt. wörterbuch: Wendekreis
Kreis, der durch die am weitesten nach außen vorstehenden Teile eines Fahrzeugs beschrieben wird, wenn das Fahrzeug mit größtmöglichem Einschlag des Lenkrads vorwärtsrollt, und dessen **Durchmesser** ein Maß für die Wendigkeit des Fahrzeugs ist.

Da scheint bei CP wohl was nicht zu stimmen, wenns da die hälfte ist. Egal. Fakt ist leider das die ÜLW in AD irgendwie Probleme zu machen scheinen. Gibt aber sicher wichtigere Issues, die mehr Priorität haben.
Kannst du ja vielleicht aber mal im Hinterkopf behalten. Danke erstmal

Gruss Micha

**Comment by Stephan-S** [comment]
Um welchen Hänger geht's denn genau?
Hab mir mal eben den Fliegl ASW 288 angesehen und der hat es in seiner xml Datei im Mod drin stehen.

Also fehlt die Info sicher bei dem von dir genutzten und könnte durchaus eingetragen werden.

Hier mal ein Auszu aus der "ASW288.xml" aus dem Mod "FS19_FlieglASW288"

 <pipe unloadInfoIndex="2">
        <dischargeNode index="1" />
        <states num="2" unloading="2" />
        <animation name="foldPipe" speedScale="1" />
		
        <unloadingTriggers>
            <unloadingTrigger node="0>0|5|12" />
        </unloadingTriggers>
    </pipe>   
	
	
	
    <ai>
        <allowTurnBackward value="false"/>
        **<turningRadiusLimitation radius="9"/>**
		<needsLowering value="false" />
        <areaMarkers leftNode="aiLeftMarker" rightNode="aiRightMarker" backNode="aiBackMarker" />
        <sizeMarkers leftNode="sizeMarkerLeft" rightNode="sizeMarkerRight" backNode="sizeMarkerBack" />
        <allowTurnBackward value="false" />
        <toolReverserDirectionNode node="sizeMarkerBack" />
    </ai>

**Comment by haamic** [comment]
Ich hab 3 getestet. Einen der bei Giants dabei war so ein blauer kinze Und 2 mods, annaburger und noch einen anderen. Bei allen kam AD nicht klar, falls es doch mal geklappt hatte und er zum Abfahrer fuhr, hat er abgeladen, blieb dann aber stehen, trotz ausgeschalteter kollision. Durch das kurze rohr müssen die Fahrzeuge relativ nah beieinander stehen und irgendwie wird die Weiterfahrt dadurch blockiert. 
Ich glaub ich geb es erstmal auf mit dem überladewagen. Habe damit leider keinen Erfolg. Zuviel geht da bei mir schief. In der Zeit der langen kreisfahrten und hängen bleiben an Hindernissen oder dem Drescher, auch das passiert mit überladewagen öfters, wäre ein normaler Abfahrer bereits wieder zurück.

**Comment by haamic** [comment]
hey Stephan, deine Änderungen waren sehr erfolgreich. der Überlader fährt nun korrekt ohne kreise zu drehen. Super, danke. Die Plane flattert zwar 1000mal in der sekunde beim fahren zum Drescher oder zum Abfahrer, aber das stört mich nicht.
Hast du sonst noch was geändert?
hab neuerdings das Phänomen, beim modus Abholen abliefern, will er zuerst zum entladeziel, obwohl er leer ist.
Schönes Wochenende
Gruss Micha
