### ISSUE TITLE
Fronthäcksler (Baum + Baumstumpf) - Kollosion

### ISSUE THREAD

**Issue by geo-luchs** [Stephan-S/FS19_AutoDrive#611]
Hallo Stephan

ich habe den Mod FS19_Bruks_All_in_one.
das ist ein Holzhäcksler zum Baumstümpfe entfernen und Bäume in Häckselgut umwandeln.
Wenn ich den vorne angebaut habe, kann ich nicht mehr mit AD fahren, da er eine Kollosion erkennt.
Mit F5 sehe ich ein rotes Rechteck.

![Häcksler_Kollosion](https://user-images.githubusercontent.com/53658780/66514318-2ae78a00-eadd-11e9-8a34-518376aa6385.PNG)

**Comment by Stephan-S** [comment]
Besteht das Problem in der aktuellen Version noch?

**Comment by geo-luchs** [comment]
Nein, geht nicht. Hab jetzt mal mit F5 geschaut. Der Mod hat 2 sehr merkwürdige Kollosionsboxen. Auch wenn ich die Fräse abkoppel, fährt der Traktor nicht, solange er in einer der 2 großen Boxen ist. Wenn ich den Mod mit "starker Bauer" einfach wegbewege, fährt der Traktor irgendwann los, wenn die Box weg ist.

Da wirst Du vermutlich nichts machen können. Da müsste man sich mal von dem Mod die Kollisionsboxen ansehen

![kollisionsbox](https://user-images.githubusercontent.com/53658780/67699374-522eca00-f9ac-11e9-835f-efcadeed20a1.PNG)

**Comment by geo-luchs** [comment]
Brauchst du noch mehr Info?

**Comment by Iwan1803** [comment]
Da kein weiteres Feedback -> geschlossen.
Bitte mit der neuesten Version erneut versuchen und bei Bedarf ein neues Issue erstellen, danke!
_Since no further feedback -> closed.
Please try with the latest version and create a new issue if necessary, thanks!_
