### ISSUE TITLE
Hud verschwindet mit AD + CP beim Stroh Sammeln

### ISSUE THREAD

**Issue by Onkel2000** [Stephan-S/FS19_AutoDrive#612]
Wenn ich mit Courseplay und AD (beides die neueste Version) Stroh einsammel und abfahren möchte. Sind viele Modi im Hub völlig zerschossen, es wird keine Schrift angezeigt + Courseplay und Ingame Hud verschwindet. Es kommt auch nur wenn ein Ladewagen angehängt ist.

im log ist folgender Error "FarmingSimulator2019/mods/FS19_AutoDrive/scripts/HudElements/PullDownList.lua:474: attempt to index a nil value
2019-10-09 22:43 Error: Running LUA method 'draw'."

![fsScreen_2019_10_09_22_53_36](https://user-images.githubusercontent.com/53871930/66519562-d39ae700-eae7-11e9-8689-dcf0ad2e382b.png)

**Comment by Stephan-S** [comment]
Hm, der Fehler würde passieren wenn der aktuell gewähle fillType keinen Namen hat.
Hast du Mods geladen, die zusätzliche FillTypes hinzufügen?

**Comment by Onkel2000** [comment]
> 
> 
> Hm, der Fehler würde passieren wenn der aktuell gewähle fillType keinen Namen hat.
> Hast du Mods geladen, die zusätzliche FillTypes hinzufügen?

Nein, daran kann es leider nicht liegen.

**Comment by Onkel2000** [comment]
Es ist ziemlich merkwürdig, hab jetzt noch ein bisschen getestet und musste feststellen, das es nur den einen Fendt 1050 zerschossen hat. (hab mehrere).
