### ISSUE TITLE
Tutorial Videos

### ISSUE THREAD

**Issue by Stephan-S** [Stephan-S/FS19_AutoDrive#613]
This issue is a collection of all the tutorials/youtubers which can be used to learn about the mod:

Let's start with Cairo Amun (german):
https://www.youtube.com/channel/UCqQhmo7yyaKDsXQDLgNV39A

And a nice french youtuber, Sam. I really like his newest video :-)
https://www.youtube.com/watch?v=_D1jm8D1IXA
channel:
https://www.youtube.com/channel/UC9zXrkiLL-GV1SMDFdc9WCQ

Then there is a really nice guy, called Datalund who makes Let's play streams and is a great content maker (FS19 Eiersholt). So please check him out as well:
https://www.youtube.com/channel/UCy3_voJUZfNDIf3PBNiis7A

If you have any good tutorials, feel free to link them in this issue.

Best regards,
Stephan

**Comment by ploughedfieldman123** [comment]
I couldnt see any help for AutoDrive  on the last video by Datalund.  its a pity no english help on AD

**Comment by Iwan1803** [comment]
Ich nutze und erkläre AD, CP & anderes auch in meinem Streams. Darf ich dafür auch "Werbung" machen?

**Comment by ploughedfieldman123** [comment]
> Ich nutze und erkläre AD, CP & anderes auch in meinem Streams. Bei Fragen aus dem Chat werden diese auch gleich geklärt. Darf ich für meinen Kanal auch "Werbung" machen?
> Falls nicht, dann bitte löschen:
> ➡️ Twitch: https://www.twitch.tv/iwan1803
> ➡️ Youtube: http://yt.vu/+iwan1803

Im from UK so dont understand you

**Comment by Knowen** [comment]
@ploughedfieldman123 I'm currently working on a tutorial series in english. Right now i have a lot to do at work so i havent much time to capture videos etc. If it's ready i'll leave a link here.

**Comment by ploughedfieldman123** [comment]
> @ploughedfieldman123 I'm currently working on a tutorial series in english. Right now i have a lot to do at work so i havent much time to capture videos etc. If it's ready i'll leave a link here.

thanks that would be most appreciated

**Comment by saku05** [comment]
Hi
I did a tutorial, but with 2 plows. Maybe it can help you.
sat
https://sharemods.com/38kw1tqtlv25/ZZZ_courseplay.zip.html

**Comment by saku05** [comment]
Hello
I did a tutorial, but for 2 plows. I hope this will help you.
Sat.
https://www.youtube.com/watch?v=dc44Q0Mk-ZU

**Comment by ploughedfieldman123** [comment]
> Hello
> I did a tutorial, but for 2 plows. I hope this will help you.
> Sam.
> In French with translation
> https://www.youtube.com/watch?v=dc44Q0Mk-ZU

I am on about AutoDrive, you have posted a tutorial about CoursePlay

**Comment by Iwan1803** [comment]
Wo und wie lädt und installiert man AutoDrive? 
Außerdem erkläre ich die Unterschiede zwischen der Release- und der Dev-Version.
https://youtu.be/LfR0ZkFjMWI

Wie kann man AD & CP für die Drescher- & Häckslerarbeit nutzen?
Ich erkläre euch, auf was man achten sollte und die Tücken.
https://youtu.be/mqzcw8CZWFU

**Comment by ploughedfieldman123** [comment]
I am in the UK so only english I know

**Comment by Iwan1803** [comment]
Discord: https://discord.gg/sUQtKhB

**Comment by Stephan-S** [comment]
Cleaning up old issues.
