### ISSUE TITLE
vehicles don't get onto hills

### ISSUE THREAD

**Issue by rebirth101** [Stephan-S/FS19_AutoDrive#615]
I play NORTH FRISIAN MARCH. On that map, there are some roads that have a small short climb. Almost all vehicles I use, don't get to the top of the climb, the get stuck almost every time. They just stop, and I have to stop the drive, and drive manually to the top, and then resume.

![Nieuwe afbeelding (3)](https://user-images.githubusercontent.com/55347044/66596478-41551a80-eb9d-11e9-9ba6-95159e26f738.jpg)

**Comment by Stephan-S** [comment]
hey, please update to the newest version 1.0.6.3.
Te problem still exists but only with very few vehicles, as far as I know

**Comment by Woife1** [comment]
a workaround for this issue is 
bye the streets an use the modelling tool to make it smoother to get up

**Comment by rebirth101** [comment]
> hey, please update to the newest version 1.0.6.3.
> Te problem still exists but only with very few vehicles, as far as I know

Hello Stephan-S, I had the latest version, but I had many troubles with vehicles that did not find their way anymore, always got a message they could not find the route, so I put back this older version which does not have the problem with pathfinding.

Woife1, good idea, I will try this! Thank you.

**Comment by Woife1** [comment]
i had done this a month ago or so couse all drivers stops at that hill ;) 

do have recalculated the courses with the new version 
it helps sometimes

**Comment by raxtor** [comment]
Didnt test it long time, but this problem disappear when I turned off "Collision detection".

**Comment by GitTomahawk** [comment]
turn of collision detection workeed for me as well also on ramps, bridges etc.

**Comment by Stephan-S** [comment]
I just commited a fix that should help this even more by angling the collision box slightly upwards

**Comment by rebirth101** [comment]
Thank you Stephan-S!
Also thank you raxtor for your tip, I can confirm it solved it for now for me.
