### ISSUE TITLE
Feld warte punkt hofsilo

### ISSUE THREAD

**Issue by pulimatrix** [Stephan-S/FS19_AutoDrive#616]
Hey Steffan,

Habe seit 1.0.6.3 das Problem das der ABF zum warte punkt am feld fährt aber nicht zum drescher, bei 1.0.6.0 Ging Alles fuhr alles ab ging alles aber selbst erneutes ansetzen plane auf plane zu brachte nix mal klappt es dann wieder dann nicht, habe mais probiert ab und zu macht er genauso wie bei Roggen oder weizen keine ahnung woran das liegt bei 1.0.6.0 ging es reibungslos lg

**Comment by GitTomahawk** [comment]
Ich habe das Problem auch beobachtet,
Auch das Rufen des Abfahrers per Tastenkombination bringt nichts.

**Comment by pulimatrix** [comment]
Hab mal bissel rumgespielt, mal gehts flüssig dann wieder mal nicht, ob der explorer dazwichen funt?! oder coursplay weis ich noch nicht so genau, den nutze ich nur coursplay geht soweit alles bis das wieder passiert nutze ich coursplay mit tritt es verstärkt auf lässt sich garnicht mehr rufen genauso wenn ich das alleine spiele ob das vllt auch am save game liegt? hat das einer schon mal probiert?

**Comment by Stephan-S** [comment]
Hey, ich kann das Problem aktuell nicht nachstellen.
Wenn ihr ein Szenario habt indem der Abfahrer nicht losfährt, schickt mir am Besten mal das Savegame.

Ich habe gerade nochmal schnell sowohl mit "Pre call" und ohne ausprobiert und konnte nichts feststellen.

Beste Grüße,
Stephan

**Comment by pulimatrix** [comment]
in der log zeigt er nix an weder das er scannt oder shot douwn nix, oke lade dir mal das save game hoch

**Comment by pulimatrix** [comment]
https://filehorst.de/d/cwcEkGFr das savegame von mir

**Comment by Stephan-S** [comment]
Welchen Mod Drescher muss ich laden?
Wenn ich dein Savegame lade stehen da bei mir keine Abfahrer und Drescher bereit.
Ich habe jetzt schon extra das Claas Drescher Pack heruntergeladen. Welchen hast du denn genutzt? Und stehen die in dem Savegame so dass es das Problem gibt?

**Comment by pulimatrix** [comment]
ne leider nicht, ich kann dir den hänger plus schlepper und drescher dan hochladen, bin aktell letzten Herbst, wenn das wieder vorkommt speichere ich und lad dir dann das save game wäre das oke?

**Comment by GitTomahawk** [comment]
Ich habe jetz mal den Abfahrer genauer beobachtet:
Ab dem Zeitpunkt, wo er vom Drescher gerufen wird Zeigt er an "fahre zum Drescher", fährt aber nicht los.
Nach einer Weile kommt die Meldung "Der Fahrer hat keinen Pfad zum Ziel berechnen können"
Ich hatte promt die Fruchtumfahrung in Verdacht, aber auch mit Fruchtumfahrung "aus" ist es das gleiche Fehlerbild.
Die Einstellungen für "Abladen ab Level" und "Parken im Feld" scheinen übrigens auch nicht zu greifen.

**Comment by Stephan-S** [comment]
Ich mache hier erstmal zu.

> Die Einstellungen für "Abladen ab Level" und "Parken im Feld" scheinen übrigens auch nicht zu greifen

Das habe ich im Blick und ist in anderen Issues auch ein offener Punkt. Wird bearbeitet
