### ISSUE TITLE
Refill not working.

### ISSUE THREAD

**Issue by eddiem54** [Stephan-S/FS19_AutoDrive#617]
Hi Stephan,
One of the commits after 1.0.6.3 seems to be preventing the refill function working. 
Using Lime Station from "Placeable Buying Stations" on Modhub with the standard Bredal spreaders.

**Comment by Stephan-S** [comment]
hey, have you restarted the game after buying the placeable?

**Comment by eddiem54** [comment]
Hi Stephan,
Sorry, my mistake.
Regards.
