### ISSUE TITLE
LKW Erkennt keine Autos.

### ISSUE THREAD

**Issue by Mannie313** [Stephan-S/FS19_AutoDrive#619]
Hallo @Stephan-S . Die Collisionserkennung für die Trucks ist zu hoch. Sie erkennen den Verkehr nicht.

MFG Mannie313

**Comment by Stephan-S** [comment]
Sollte mit dem letzten commit besser funktionieren.

**Comment by Mannie313** [comment]
ok teste es dann mal

MFG Mannie313

**Comment by Mannie313** [comment]
Hallo @Stephan-S. Die LKW halten jetzt abstand zu den KI autos. Aber ich hab da ein kleines neues problem. Ich komme nicht die Brücke rauf.
![fsScreen_2019_10_12_18_14_43](https://user-images.githubusercontent.com/3021040/66704458-6b811680-ed1c-11e9-8e26-b2455f69250f.png)

MFG Mannie313

**Comment by Stephan-S** [comment]
Sollte sich mit dem letzten Update auch erledigt haben, aber ich hab es nicht testen können da die NF Marsch 4x ja stundenlang geladen wird auf uploaded...

**Comment by Mannie313** [comment]
das ist die Dondiego map.

MFG Mannie313
