### ISSUE TITLE
Editor geht nicht mehr 

### ISSUE THREAD

**Issue by Bandesss** [Stephan-S/FS19_AutoDrive#620]
Hallo möchte gern diese Kurse Importieren im Editor 
Es kommen aber fehler Meldungen
Kurse

[AutoDrive_Multimap_2019_config.zip](https://github.com/Stephan-S/FS19_AutoDrive/files/3718944/AutoDrive_Multimap_2019_config.zip)
Hoff mir kann jemand Helfen ?
Gruss 
![^1](https://user-images.githubusercontent.com/50829319/66674467-3795ea80-ec63-11e9-8777-34d3849fce63.JPG)

**Comment by Bandesss** [comment]
hat jemand ne Info?

**Comment by Bandesss** [comment]
Immer noch Probleme mit dieser datei

[AutoDrive_Multimap_2019_config.zip](https://github.com/Stephan-S/FS19_AutoDrive/files/3763531/AutoDrive_Multimap_2019_config.zip)
Wenn sie jemand für mich öffnen könnte und neu speichern wäre super
Gruss Bandes

**Comment by Stephan-S** [comment]
Moin Bandess. Spiel mal mit den Zahlen in der start Editor Datei. Möglicherweise sind die 2080 zu hoch und du solltest es mal mit 1024 probieren.

**Comment by Bandesss** [comment]
Hallo Stephan es ging als ich Java 64 Bit runter geladen habe. 
Als Info
