### ISSUE TITLE
Ordner anlegen?

### ISSUE THREAD

**Issue by Iwan1803** [Stephan-S/FS19_AutoDrive#622]
Guten abend zusammen,
ich weiß nicht, ob ich einfach zu müde bin oder einen Denkfehler mache.
Auf Estancia Lapacho habe ich AD zusammen mit CP erfolgreich eingesetzt und dort funktioniert auch noch alles. Ich kann in AD Ordner erstellen und sie auch aus- und einblenden. Auf der Nordfriesischen Marsch kriege ich es einfach nicht hin bzw. es wird mir nichts bezüglich Ordnererstellung angeboten. In den Optionen scheint es auch keine Rolle zu spielen, ob ich Ordner de- oder aktiviere.
In der Liste sehe ich auch nicht alle meine Zielpunkte, aber ich kann sie mit den Pfeil-Buttons durchblättern und auch auswählen.
Ich habe gerade noch mal die neueste Version runtergeladen. Auf Estancia geht alles, auf NFM nicht.
Wo ist mein Denkfehler?

![fsScreen_2019_10_12_03_39_05](https://user-images.githubusercontent.com/47528836/66692803-3a640000-eca2-11e9-8034-62061e42335e.png)
![fsScreen_2019_10_12_03_39_12](https://user-images.githubusercontent.com/47528836/66692804-3a640000-eca2-11e9-8495-be75fcef4127.png)
![fsScreen_2019_10_12_03_39_17](https://user-images.githubusercontent.com/47528836/66692805-3a640000-eca2-11e9-823e-33d2a415c6cd.png)

**Comment by Stephan-S** [comment]
Hey hast du schon mit dem Mausrad in der Liste nach oben gescrolled? :-)

**Comment by Iwan1803** [comment]
Ja, es war eindeutig Müdigkeit.... danke für den Tip, es funzt wieder 👍 
Vermutlich hat mich iritiiert, das es keine Scrollleiste gibt, sonst wäre ich eventuell vielleicht selber drauf gekommen. Ich vermute mal, das es keine Möglichkeit gibt, die einzubauen, oder?

**Comment by Stephan-S** [comment]
Klar ist das möglich aber es würde mich wahrscheinlich einen halben Tag kosten das zu implementieren.
Das ganze HUD und Verhalten des HUDs ist komplett selbst geschrieben. Es gibt hier keine fertigen Vorlagen die ich einfach drauf schmeißen kann und damit eine Scrollleiste leicht hinzufügen könnte :-)

**Comment by Iwan1803** [comment]
Es ist also eher ein "nice²have" ;-)
Nochmals danke!
