### ISSUE TITLE
Map Markers (Targets) disappearing from the selection dropdown

### ISSUE THREAD

**Issue by GeorgeEarslight** [Stephan-S/FS19_AutoDrive#623]
Hello and thanks for the mod.

I'm having an issue where if I click on the target dropdown menu some entries are disappearing.
This is just visual (no XML deletions). When I use Select Next/Previous target buttons, they cycle normally.
One thing I have observed is that the entries disappear depending on their alphabetical order.
Example:

Assume 3 entries: Alpha, Bravo, Charlie.
- If I select Alpha from the dropdown, nothing disappears.
- If I select Bravo from the dropdown, Alpha disappears.
- If I select Charle from the dropdown, Alpha and Bravo disappear.
- If I select Alpha from the buttons, Alpha and Bravo reappear on the dropdown.

Tell me if you need any logs, XML, etc.

**Comment by Stephan-S** [comment]
Use your mousewheel to scroll ;-)

**Comment by GeorgeEarslight** [comment]
> Use your mousewheel to scroll ;-)

OH MY! 
Closing this, thanks and sorry for the dumb issue post :P
