### ISSUE TITLE
Destination in maps auto close (suggestion)

### ISSUE THREAD

**Issue by Bobster82** [Stephan-S/FS19_AutoDrive#624]
Hi stephan,

When creating map in destination, u have the "standard" and user defined maps where u can store ur destinations.
Is it possible to leave the user defined maps closed everytime u switch vehicles?
It annoys me when I have maps, but still cant use the full benefit of it, cuz i still need to scroll trough all destinations or close the maps everytime.
When standard map is always open is ok (u can store there freq used destinations)
But when I have a park destination map, I dont select those destinations ever (using park button, so not needed to select destination ;) )

I hope u understand what im suggesting.
Thanks in advance!

**Comment by Stephan-S** [comment]
I store the folder settings (opened/closed) per vehicle.
But I changed the default from opened to closed for new vehicles and new folders.

**Comment by Bobster82** [comment]
thanks! and btw, where can i find that code line? maybe i can change that for myself if i want
