### ISSUE TITLE
Abladen Modus-bleibt nach Abladen aktiv

### ISSUE THREAD

**Issue by haamic** [Stephan-S/FS19_AutoDrive#626]
Hallo Stephan,
das Fahrzeug fährt zum Abladen, erledigt das und bleibt am Trigger stehen. AD bleibt aktiv, grün. Da mein Abladepunkt hinter dem eigentlichen Trigger liegt, sollte es eigentlich nach dem Abladen bis dahin fahren und beenden. So wars jedenfalls vor einigen Updates.
Kannst du bei Gelegenheit danach nochmal schauen?
Gruss Micha

**Comment by GitTomahawk** [comment]
Ich habe das gleiche Problem beobachtet.

**Comment by haamic** [comment]
noch keine Veränderung. Bleibt immer noch stehen und aktiv, beendet nicht

**Comment by Stephan-S** [comment]
Besteht das Problem noch? Ist es begrenzt auf bestimmt Fahrzeuge/Anhänger?
Im normalen Ablauf konnte ich es noch nicht beobachten.

Bitte soviele Details wie möglich liefern damit ich hier mal nachforschen kann. Vielen Dank!

**Comment by haamic** [comment]
Werde es heute nochmal genau testen, bin aber der Meinung es kommt immer noch vor, bei jedem Fahrzeug, wo es vorher schon mal einwandfrei geklappt hatte. Ist schon etliche Release her. 
Gruß Micha

**Comment by haamic** [comment]
Hallo Stephan, also das klappt nicht. im reinen Ablademodus, bleibt er aktiv,/grün am ersten Punkt wo er abkippen kann, eigentlicher Abladepunkt liegt hinter dem Silo. Geld wird weiter abgezogen, wenn man den Lohn aktiviert hat.
Test besteht aus Karte Felsbrunn, einfacher giants traktor+Anhänger und Giants silo, keine mods ausser AD . Spielstand (savegame11) anbei, log zeigt nichts an

![aktiv nach abladen](https://user-images.githubusercontent.com/28841989/67708158-f66c3d00-f9bb-11e9-81b1-23691a7576a9.jpg)

[savegame11.zip](https://github.com/Stephan-S/FS19_AutoDrive/files/3780197/savegame11.zip)

**Comment by GitTomahawk** [comment]
Ich habe es mit Version 1.0.6.7 gestern auch beobachtet.
Es passiert bei mir haupsächlich bei langen Auflieger-Anhängern. (z.B. das große Wasserfass)
Der AD-Marker ist aber immer no ein ganzes Stück vor dem Punkt bei dem er stehen bleibt.
Bei 2 Anhängern ist der hintere mal leer und mal nicht. (wenn ich AD dann beende steht er genau so, dass der hintere abladen kann)
Im Abfahrmodus fährt er einwandfrei weiter und zurück zum Feld.

**Comment by Stephan-S** [comment]
Should be fixed now :-)

**Comment by GitTomahawk** [comment]
Bei nur einem Anhänger (bzw. Ladefläche funktioniert es jetzt. (1.0.6.7-9) bei Ladefläche+Anhänger (IT-Runner) bleibt der Anhänger voll und der Abfaher aktiv ohne weiter zu fahren.
