### ISSUE TITLE
Abfahrer bleibt im Feld stehen

### ISSUE THREAD

**Issue by Moitzbert** [Stephan-S/FS19_AutoDrive#627]
Abfahrer bleibt nach dem Abtanken des Dreschers im Feld schon obwohl Parken im Feld ausgeschalten ist. Kann mir jemand einen Tipp  geben wie ich das hin bekomme das der Abfahrer wieder zu seinem Startpunkt fährt ?

**Comment by GitTomahawk** [comment]
Ich habe das Problem auch beobachtet. 
Erst wenn ich auf Weiterfahren klicke, dann fährt er weg.

**Comment by pulimatrix** [comment]
Hab das Problem immer noch bin im herbst grade am dreschen, habe die die nötigen mods bei gelegt karte ist auch mit bei, hab verschiedende varianten durch, linke feld seite rechte feld seite, mit frucht ohne fruchtumfahrung drescher folgen nicht folgen wirklich alles durch, ab und an fährt er los findet aber nicht den punkt fährt sich fest etc. weis echt kei rat mehr :/ aktuell teste ich grade wieder mit einem standart anhänger bzw mod anhänger von modhub! bis jetzt aktuell läufts aber ebend nicht mit diesem lkw :7 lg
https://filehorst.de/d/ceyDgrmI

https://filehorst.de/d/caotomIu

**Comment by Stephan-S** [comment]
@pulimatrix Danke für deinen Spielstand.

Der Abfahrer fährt nicht los weil du nicht die selben Zielpunkte eingestellt hast. Abfahrer stand auf 'Abfahrer F15a', der Drescher aber auf 'Abfahrer F15'. Das funktioniert nur wenn du die Option 'Abfahrer suchen' einschaltest und auch dann nur bis 200 oder 300m. Müsste ich nachschauen.

Danach hat er den Drescher gefunden und angefahren. Kann sein dass er sich bei der 1.0.6.3 noch festgefahren hat. Dann einfach mal auf die 1.0.6.4 updaten, da habe ich einen Wenderadius Bug gefixed.

Allerdings fährt er trotzdem zu weit vor. Ich lade gleich einen Fix hoch damit LKWs mit Ladefläche hier besser unterstützt werden und nicht soweit vor fahren

**Comment by pulimatrix** [comment]
Das Wäre super, mir ist auch aufgefallen das der mittel punkt wo der rote leitstrich ist bei lkws zu weit mittig sitzt nutzt er da den mittelpunkt des fahrzeugs? oke warte, den mau auf fix und berrichte dann noch mal

**Comment by pulimatrix** [comment]
achsu dazu nutze ich aber noch coursplay zum dreschen ja? wusste nicht das ich beim AD auch angeben muss :/ oder hab ich da was falsch verstanden?
