### ISSUE TITLE
Not able to record, Button never goes red

### ISSUE THREAD

**Issue by H8DCarnifeX** [Stephan-S/FS19_AutoDrive#628]
Title
Not able to record, Button never goes red
when i click on record, the warning lights of the vehicle starts turning, but thats it.

**Comment by Dzi4d3k** [comment]
Standard or mod vehicle? Could you post log?

**Comment by H8DCarnifeX** [comment]
Some Mod ones, i'll test it on a standard one later, forgot to test this.
Then i'll reply here.

**Comment by Knowen** [comment]
You have to enable the Editor-Mode first. Only then the recording button is clickable.
