### ISSUE TITLE
Feature Request: Suchfunktion

### ISSUE THREAD

**Issue by Rheingauner** [Stephan-S/FS19_AutoDrive#629]
Hi,
ich hab inzwischen sehr viele Zielpunkte und verbringe viel Zeit mit dem Scrollen durch das Dropdown-Menü, um einen bestimmten Zielpunkt auszuwählen. 😄  Dabei hab ich eine gute Ordnung, es geht also nicht darum, dass ich nicht weiß in welchem Ordner der gesuchte Zielpunkt ist. Vielleicht ist meine Ordnerstruktur auch zu grob & dadurch hab ich ziemlich viele Punkte in dem ein oder anderen Ordner. 😜 

**Kannst du eine Suchfunktion in AD integrieren mit der man Zielpunkte finden kann?**

**Comment by Stephan-S** [comment]
Klingt sinnvoll. Hast du einen guten Vorschlag wie das UI-technisch aussehen sollte? :-)

**Comment by Rheingauner** [comment]
Hi, ich hab mich mal kurz hingesetzt und ein bisschen paint.net gespielt. Grob hab ich 3 Vorschläge. Dazu hab ich Bilder angehängt. Zu sehen ist das Hud und ich hab nen weißes Piktogramm von ner Lupe eingefügt.
**1.** Man fügt die Funktion **in die Übersicht der Ordner** ein. Ich hab das einfach mal ganz nach unten geschoben. Denkbar und vermutlich sinnvoller wäre es sie ganz oben über/neben den Standardordner einzufügen. Jetzt fällt mir gerade ein, dass man die Ordnerstruktur ja deaktivieren kann, da müsste man dann überlegen, wie man das in diesem Fall macht (falls überhaupt jemand keine Ordner nutzt).
**2.** Man fügt die Funktion **links vor das Anzeigefeld des Zielpunktes** ein. Mit einem Klick auf das Such-Symbol erscheint ein Eingabefenster (wie wenn man einen neuen Zielpunkt hinzufügt) und kann dort dann seinen Ort suchen.
**3**. Man fügt die Funktion **rechts im Zielpunkt-Feld** ein. Also ähnlich wie Option 2.
Man muss jedoch beachten, dass sowohl durch Option 2 & 3 die Anzahl der angezeigten Zeichen eines Zielpunktes durch das Hinzufügen des Suchen-Symbols verringert wird. Kann man vorher z.B. den Zielpunkt "Hofsilo 1 abkippen" vollständig lesen, steht da nun nur noch "Hofsilo 1 abkip" ich hoffe das versteht man ;-)
**4.** Man fügt die Funktion **nicht in das UI** ein. Es gibt ja einige Funktionen, wie Fahrzeug umbenennen oder Zielpunkt umbenennen, die nicht im Hud aufgeführt sind. Also könnte man das so auch mit der Suche machen. Generell ist es ja zu empfehlen sich mal alle Eingabemöglichkeiten über die Tastatureinstellungen anzusehen. Kam ich auch nicht direkt drauf und nutze jetzt gerne die Funktion zum Umbenennen der Zielpunkte. Dann muss ich das nicht mehr über die xml machen.

Wenn du Fragen dazu hast immer her damit. Es ist manchmal etwas schwer zu erläutern, was man meint.

Grüße
Rheingauner
