### ISSUE TITLE
setting bug

### ISSUE THREAD

**Issue by magicmana** [Stephan-S/FS19_AutoDrive#630]
hello  good  job.
autodrive is  so powerfull on big  map.

i have a margin  bug  with the lastest version.
(see attachment)
![Sans titre](https://user-images.githubusercontent.com/32802279/66713207-dfb4cc00-eda7-11e9-8017-6c9590f36c04.png)

not easy to change first option
regards

**Comment by geo-luchs** [comment]
Hello

I have  seen this issue in all versions before, too.

It is an overlay wird Thema grey title bar.

Only The lower small Area of the arrows can be used  which are overlayed  with  Black background.

**Comment by Dzi4d3k** [comment]
Maybe this is related to screen resolution/aspect ration. What values do you use, as I don;t have this kind of issue?

**Comment by Stephan-S** [comment]
@magicmana Which resolution are you playing on?
Can you please send me a log file?

Thank you!

**Comment by DeckerMMIV** [comment]
I have the same problem. - My aspect ratio is 4:3, running in 1600 x 1200 pixels.
![fsScreen_2019_10_18_21_49_29](https://user-images.githubusercontent.com/2834184/67123860-a938e000-f1f1-11e9-84e3-894e55630336.png)

Also, the <kbd>Q</kbd> and <kbd>E</kbd> keys seems to "not work", as pressing them does not switch to another page.

**Comment by magicmana** [comment]
hello  if can help , is not specific to  autodrive  : 
i using  1680x1050  (16:10)

on    courseplay advanced setting   have the same  bug  
but on seasons mod   when the  menu in  extend to all  screen that  work : 


![fsScreen_2019_10_19_18_03_27](https://user-images.githubusercontent.com/32802279/67148148-5b2ce680-f29c-11e9-84d5-e173398052e5.png)
![fsScreen_2019_10_19_18_04_02](https://user-images.githubusercontent.com/32802279/67148149-5bc57d00-f29c-11e9-8cfb-827262669453.png)

**Comment by Stephan-S** [comment]
Courseplay might have looked at my code for their advanced settings from the looks of it :D 
So you can open an issue on their github and maybe link to my latest commit if that fixes it for you :-)
