### ISSUE TITLE
calulate the reverse point

### ISSUE THREAD

**Issue by magicmana** [Stephan-S/FS19_AutoDrive#631]
hello , on big  map  on road  with  two way is  long to create the revert  way. could  you put a  option button to create a revert point if is possible ? 
when i  played on fs17  i used a  local only php script for parse courseplay xml file and create a reverse way.
my  idea was to create a  single  way  on road , at each crossing i put a "P" point .
after i splited array  at each "P" point for create segment , and revert segment.

 i had good result  ,the idea  was to create way with no  frontal collision in courseplay.

if you are interrested  i put  some low quality vids  here :  

https://youtu.be/ihCZUmNf4AA
( test of crossing)

https://youtu.be/avxE0NBFZxs
(aggregate  segment)

https://youtu.be/x4lGj6E_o1M
(using the segment)

and   i put a part of the PHP code i used  , if you are  interrested by create a reverted parallel way.

`-------------------------------------------------------------`

$ecart=3.4;`
//distance in meter to the revert way

$posx=312;
//current x position on the map

$posy=981;
//current y position on the map

$angle=45.96;
//current direction of vehicle

$angle2=$angle+180-90;
// change the  direction at 90° (need change "+"  to "-"  of  UK map  with  driver who  drive at the other side)

$radangle=deg2rad($angle2);
// convert direction in  radian

$newposx1=number_format($posx+$decal2 * sin($radangle) ,2, '.', '') ;
$newposy1=number_format($posy+$decal2 * cos($radangle) ,2, '.', '') ;
//create x-y position  and  format result .

-------------------------------------------------------------

**Comment by raxtor** [comment]
@magicmana some time ago I proposed add new course, similar to blue (two ways route), lets say highway/highspeed course with configuration of vehicle offset (+/-) from this course.

**Comment by Stephan-S** [comment]
@magicmana and @raxtor 
I prefer the idea of @raxtor to the one you are proposing.
But even raxtor's idea has it's problems.
The main problem lies in the offset/distance setting which will have to be adjusted for each and every different street you are recording on.
Then you will have to connect all the start and end point correctly.
And these are just the two main problem popping up in my head.

Another aspect is that you just confuse people even more who are new to AutoDrive if you add a third way to record routes.
And I just don't think the gained value from this addition is really worth the implementation effort and the possible confusion for new players.

Best regards,
Stephan

**Comment by raxtor** [comment]
@Stephan-S 
- my original idea was re-use blue course with abbility use some global value of distance from this course. Because this course will be in mid of road so I assume you can find optimal value for 2-3 type of road width.
- end points cant work in the same way like blue course? Why? 
- anyway if isnt possible only re-use blue course and add configuration like offset and  disable collision detection than we can live without that :-)
- I will try prepare some solution for HUD if you will change opinion

**Comment by Iwan1803** [comment]
Obsolote....
