### ISSUE TITLE
Ziel ändert sich seit patch 1.0.6.3

### ISSUE THREAD

**Issue by OnkelH0tte** [Stephan-S/FS19_AutoDrive#632]
Hallo Stephan,

ich meine es zwar hier schon einmal gelesen zu haben, finde aber das Thema nicht mehr.

Wenn ich einem Fahrzeug "Abhol und Abliefernmodus" sage wo es hinfahren soll, ändert es den Zielpunkt, dies geschieht ständig, so dass der Modus unbrauchbar ist. Alles original Giants Traktoren und Anhänger.

Log ist bis auf "2019-10-13 11:56 WARNING: static shape 'baleStraw240' is marked COMPOUND
2019-10-13 11:56 These are not compatible settings and may cause a crash; COMPOUND flag will be removed" fehlerfrei.

**Comment by Woife1** [comment]
schau mal in den Einstellungen ob mehrere Ziele auf "Nein" steht 
wenn auf "Ja" nutzt er alle Ziele in dem Ordner

**Comment by OnkelH0tte** [comment]
Ich habe keine Ziele in einem Ordner

**Comment by rgoe** [comment]
Schließe mich an, folgendes Setup:
Multimap 2019 v2.2, AD (1.0.6.3) Ziele in Ordnern strukturiert
Drei Abfahrer "kümmern" sich um einen Drescher. Sie verrichten ihren Dienst, aber wenn ich nach einer gewissen Zeit wieder nachschaue haben sie teilweise andere Abladepunkte bekommen und ja, es sind bis dato immer Ziele aus dem gleichen Ordner. Die Einstellung "Mehrere Ziele" ist bei allen dreien definitiv auf Nein.
Aber...ich habe zeitgleich auf einem anderen Feld zwei weitere Abfahrer für einen Hächsler, bei diesen beiden ist "Mehrere Ziele" auf Ja (Bunkersilo-Routen, funktioniert auch wie gewünscht). Kann es sein, dass hier irgendwo was querschießt und er die "Mehrere Ziele" Einstellung global anwendet bzw. mit den Fahrzeugen durcheinander kommt?
