### ISSUE TITLE
Ordner sortieren

### ISSUE THREAD

**Issue by Berios** [Stephan-S/FS19_AutoDrive#633]
Hallo Stephan!

Schöne Ausbauten, welche Du in AD integriert hast. :-)

Ich hätte aber eine Bitte / Frage an Dich:

Wenn ich das richtig verstehe, sortiert AD die Ordnerstruktur nach der niedrigsten ID der im Ordner befindlichen Wegpunkte. Leider führt das bei mir zu einem vollkommenen Durcheinander in den Ordnern. Mittlerweile bin ich auf der Don Diego und spiele die Karte mit ca. 25 Wegpunktordnern. Durch die Sortierung stellen sich die Ordner "kreuz - und quer" dar. Bedeutet, ich nummeriere meine Ordner durch (nach meiner Logik) - leider steht jetzt Ordner "01 - Haupthof (HH)" (so von mir benannt) an 12ter Stelle anstatt an 1ter Stelle. Ich habe die Ordner in Reihenfolge der vorstehenden Zahlen angelegt - als 01 als erstes, 25 als letztes. 

Kannst Du hier noch etwas machen, damit das Programm die Ordner entsprechend der Benennung sortiert?

Danke für Deine Hilfe - spitzenmäßige Arbeit. :-)

Berios

**Comment by Rheingauner** [comment]
ich hab meinen Ordnern auch Nummern gegeben und den Produktionen noch eine weitere Nummer. Durch die Sortierung, die mit AD Version 1.0.6.2 glaub kam, sollte das eigentlich so funktionieren, wie du dir das vorstellst.
![Ordner](https://user-images.githubusercontent.com/55962209/66716716-4ac6c880-edd1-11e9-8ad9-65a08831676f.png)

**Comment by Berios** [comment]
Miau!!

Ich habe nicht gesehen, daß ich noch auf 1.0.6.0 bin. 
Danke für die Info. Ich tausche mal gegen 1.0.6.2 aus und schaue dann weiter. 

Vielen Dank für die Hilfe. :-)

Berios
