### ISSUE TITLE
Zielpunkt-Rotation bleibt stecken

### ISSUE THREAD

**Issue by HawkPat** [Stephan-S/FS19_AutoDrive#635]
Hallo, die neue Zielpunkt-Rotation bleibt ab und zu stecken, heißt: der Fahrer arbeitet die Zielpunkte in einem Ordner ab und bleibt dann bei einen hängen und fährt diesen dann immer an.

Weitere Punkt: ab und zu fangen auch andere Fahrer an, die Rotation zu benutzen, obwohl die Option bei ihnen ausgeschaltet ist.

**Comment by Woife1** [comment]
gibt schon einen Fix dafür muss aber noch selbst gepackt werden

**Comment by Rheingauner** [comment]
cool, hab das auch beobachtet, war mir aber nicht ganz sicher, ob es die Schuld von AD war, da meine Zielpunkte auf einer Strecke nacheinander lagen und AD deswegen immer über den ersten Trigger fahren musste. Aber der wird dann einfach ignoriert, wenn das zweite Ziel ausgewählt ist oder?

**Comment by Woife1** [comment]
wird nur ignoriert wenn der Trigger weit genug vom Zielpunkt entfernt ist 

kann sein das Stephan da schon was gedreht hat ist mir gerade nur nichts bekannt

**Comment by Rheingauner** [comment]
danke, dann bau ich die Strecken ein bisschen um

**Comment by Woife1** [comment]
Ich hab grad selber nochmal geschaut
Ablade Trigger gehen in einer Reihe nur bei Belade Triggern muss man auf den Abstand achten bzw eigene Anfahrten nutzen

**Comment by HawkPat** [comment]
> gibt schon einen Fix dafür muss aber noch selbst gepackt werden

Was meinst Du mit "muss noch selbst gepackt werden"?

**Comment by Woife1** [comment]
es gibt noch kein "Release" dafür 
du musst deine eigen FS19_Autodrive.zip erzeugen aus den geupdateten Dateien

**Comment by HawkPat** [comment]
Ah, ok, danke

**Comment by unlimited78** [comment]
> es gibt noch kein "Release" dafür
> du musst deine eigen FS19_Autodrive.zip erzeugen aus den geupdateten Dateien

Hi, blöde Frage: **deine eigene FS19_Autodrive.zip erzeugen aus den geupdateten Dateien** 
aber Wie? ich glaub ich steh grad auf der Leitung... 
Danke!
lg

**Comment by Woife1** [comment]
lade dir das Projekt herunter (einfach auf Code oben klicken dann download als .zip)

öffne/entpacke die ZIP geh in den Ordner 
und such in deinem alten AD.zip was du alles brauchst (sollte nur der Inhalt aus dem Ordner FS19_AutoDrive sein)

**Comment by unlimited78** [comment]
Danke!
