### ISSUE TITLE
Feature Request: Helfer beim Ziel starten

### ISSUE THREAD

**Issue by ReallyNotBad** [Stephan-S/FS19_AutoDrive#636]
Hallo Stephan,

ich konnte nicht herausfinden ob es den Modus schon gibt. Kann leider nicht so oft wie ich möchte LS spielen.

Aber vielleicht gefällt dir und auch ein paar anderen die Idee einen Drescher oder einen Traktor mit Grubber etc. ans Ziel fahren zu lassen und dann automatisch den Helfer zu starten. (H drücken)

Dann fängt er automatisch an zu arbeiten. Ich weiß das es mit Courseplay wohl möglich sein soll aber wegen mp kann ich diesen Mod nicht nutzen.

Premiumvariante wäre wenn er nach erfolgreicher Arbeit an den 2ten Zielpunkt "Abladepunkt" fährt.

Vielleicht finden andere die Idee ja auch gut.

Gruß aus der Eifel
Tim

**Comment by Stephan-S** [comment]
Servus Tim,

Die Funktion wird es nicht geben. Mir gefällt das Konzept nicht, da dein Zielpunkt am Feld ja für jedes Gerät ein anderes sein müsste. Ich finde das passt nicht wirklich zum AutoDrive Mod. Tut mir Leid.
Aber danke für deinen Vorschlag.
Falls hier Nutzer einer anderen Meinung sind können wir nochmal drüber sprechen, aber mir persönlich sagt das nicht wirklich zu einfach nur stupide den Helfer zu starten wenn man am Ziel ankommt. Das klappt so einfach nicht.

Beste Grüße,
Stephan
