### ISSUE TITLE
Rundumleuchte und Diesel tanken

### ISSUE THREAD

**Issue by cjb67** [Stephan-S/FS19_AutoDrive#639]
Hallo, und riesen Lob für den Autodrive.
Kann es möglich werden dass Autodrive die Rundumleuchten einschaltet auf der Strasse und dass das Fahrzeug Diesel tanken an einem Dieseltrigger??

MFG
Christophe aus dem Elsass

**Comment by Stephan-S** [comment]
Rundumleuchten hat bei mir keine Priorität. Vielleicht kommt es mal als auswählbare Einstellung aber vermutlich nicht, da 99% der Spieler das vermutlich eh nicht wünschen. Sorry.

Diesel Tanken ist auf meiner ToDo-Liste :-) Mal schauen wann ich dazu komme

Viele Grüße,
Stephan
