### ISSUE TITLE
Spiel läuftt nicht mehr mit AD nach Giants Update

### ISSUE THREAD

**Issue by Spielbauer** [Stephan-S/FS19_AutoDrive#640]
Moin, bei mir geht gar nichts mehr. Ich hab ständiges ruckeln, einmal eingelenkt bleibt die Lenkung für 20 sek so stehen und der Traktor fährt im Kreis weil auch das Gaspedal stehen bleibt usw., das Mausrad geht nur ab und zu, Fieldmanager. lua gibt z.B. Fehler 541, 564 aus. Bei gleichem Spielstand und gleichen Mods keine Fehlermeldung im Log bei der Vorversion. Kann man so nicht mehr spielen. Ich habe jetzt Autodrive deaktiviert und danach läuft alles wieder normal.
Vielleicht könnt ihr was finden.

Gruß Spielbauer

Log mit Autodrive und Fehlermeldung
[log.zip](https://github.com/Stephan-S/FS19_AutoDrive/files/3733441/log.zip)

Log ohne Autodrive
[log.txt](https://github.com/Stephan-S/FS19_AutoDrive/files/3733451/log.txt)

**Comment by HawkPat** [comment]
Mache nach dem Start des Spiels mal eine Neuberechnung der AD-Kurse. Das atte bei einem Twitch-Streamer heute nachmittag ein ähnliches, wenn auch nicht so gravierendes Problem behoben.

**Comment by Spielbauer** [comment]
Hallo HawkPat,
danke für deinen Hinweis, es war genau der Fehler. Bedienerfehler meinerseits, habe das Spiel einfach gestartet und dann ging nix mehr. Jetzt läuft es wieder ohne Probleme.

Sorry für den falschen Alarm
