### ISSUE TITLE
Fahrzeuge stoppen nicht beim manuellen Fahren / Laggy beim Laufen

### ISSUE THREAD

**Issue by 8odycount** [Stephan-S/FS19_AutoDrive#641]
Ich habe das Problem, dass die Fahrzeuge einfach von alleine geradeaus und rückwärts fahren, wenn man einmal "W" oder eben "S" drückt bzw. für einen Moment gedrückt hält. Erst wenn ich dann lenke, bleiben sie stehen. 

Außerdem kann man sich, sobald Helfer auf Autodrive Kursen unterwegs sind, nicht mehr per Fuß bewegen, da der Charakter ständig wieder zurückgezogen wird. 

Dies alles passiert auf unserem Server. Nicht im SP getestet.

**Comment by Stephan-S** [comment]
Servus, bitte die log posten. Falls hier lua Fehler von AutoDrive enthalten sind kann ich was machen. Ansonsten hat das entweder nichts mit AD zu tun oder eure Serverhardware kommt nicht mit den AD Fahrern zu recht.

**Comment by geo-luchs** [comment]
Dass ich mehrmals bremsen muss bis das Fahrzeug richtig steht habe ich bei mir im SP auch seit kurzem.

Werde heut Abend mal schauen ob ich Lua Fehler finde.

**Comment by worker2419** [comment]
Ist evtl. ein  Zusammenhang mit dem aktuellem Patch zu erkennen? Bin noch auf 1.4 und habe die Probleme nicht

**Comment by geo-luchs** [comment]
Guten Morgen zusammen

hab den neuen Patch Freitag Abend installiert. Aber ich glaube, ich habe das auch vorher schon bemerkt.
Allerdings bin ich gerade dabei, einen Umzug auf eine andere Karte zu machen, und habe bei der Gelegenheit mal ohne alle möglichen Mods getestet.

Da habe ich nun gesehen, dass das Problem auch ohne AD auftritt. Ich  habe das Problem, sobald ich den Mod Vehicle Control AddOn v0.0.6.9 aktiviere.

@8odycount  hast du den Mod auch aktiv?

**Comment by Stephan-S** [comment]
@geo-luchs Vielen Dank für die Info!

**Comment by worker2419** [comment]
Moin, aktuell ist die Version 0.0.79 https://github.com/Mogli12/VehicleControlAddon. Die Bremskraft kannst Du wenn ich es richtig sehe unter niedrige Bremskraft einstellen.

**Comment by geo-luchs** [comment]
Danke worker, aber leider ist es das nicht.
Hab jetzt die 0.0.7.9 genommen, und die Bremskraft auf 100% gesetzt.
Das ist nur, damit er SCHNELL bremst, also direkter.
Aber wenn er steht, und ich zu schnell von der Bremse runtergehe, rollt er wieder leicht los.

Aber mein Problem ist definitiv hier fehl am Platze, daher werde ich das bei Mogli einstellen.

@8odycount  könntest Du bitte mal testen, ob du das Problem ohne Vehicle Control Add On auch hast.

Und wenn bei mir ein Traktor mit AD fährt, und ich aussteige, kann ich ganz normal umherlaufen.

**Comment by geo-luchs** [comment]
Bei mir trat das Problem nur auf mit dem Mod Vehicle Control AddOn und auch nur wenn ich IM Fahrzeug gesessen habe.

Von außerhalb gab es absoluten Stillstand.

Mogli12 meinte, es müsste ein autoAiEnd oder so ähnlich aufgerufen werden:

Stephan: machst du beim Abbremsen einen Unterschied ob man im Fahrzeug sitzt oder man Außerhalb ist?

  Für mich habe ich es erst mal gelöst, indem ich im Vehicle Control AddOn das Getriebe auf Off gestellt habe
