### ISSUE TITLE
Drescher driving with Mod Drescher does not work

### ISSUE THREAD

**Issue by Zimty86** [Stephan-S/FS19_AutoDrive#642]
If I have a Mod Drescher and want to leave with a downhill driver, the Abfahrer does not recognize the Drescher.  With the standard thresher is working.

**Comment by Stephan-S** [comment]
Are you sure you set everything up correctly? Assigned the same target in the combine as for the unloader?

**Comment by Zimty86** [comment]
Da ich gesehen habe das manche auch deutsch schreiben mach ich dies auch Mal so kann ich es besser beschreiben.

Ja der Abfahrer das den Modus Drescher abfahren das Feld und den Silo als abladepunkt, und der Drescher hat das Feld auch angewählt, so wie das auch funktioniert mit den Standart Drescher, aber bei Mod Drescher passiert nuchts, der Drescher öffnet zwar sein Rohr aber der Abfahrer fährt nicht.

Wie eben schon gesagt das ist nur bei Mod Drescher so.

------

Yes, the Abfahrer the mode Drescher depart from the field and the silo as unloading point, and the thresher has also selected the field, as well as with the standard Drescher, but with Mod Drescher also happens, the Drescher opens his tube but the  Downhill driver does not drive.

 As already said that is only with Mod Drescher.

**Comment by Zimty86** [comment]
Okay habe es getestet nochmal mit einen anderen Drescher es hat funktioniert, Dan lag es wohl am Drescher
