### ISSUE TITLE
Drescher unerklärliches Verhalten

### ISSUE THREAD

**Issue by haamic** [Stephan-S/FS19_AutoDrive#643]
Hallo,
Hab neuerdings, wahrscheinlich nach dem LS Update, das Problem, das der Drescher manchmal anhält wenn er voll ist, manchmal mit 100% vollem Tank, den CP-Feldkurs weiter fährt. 
Dabei klappt er bei 100% das Rohr aus und fährt das schneidwerk hoch. Fährt aber stur seinen Kurs weiter. So erreicht der Abfahrer ihn nicht. 
Drescher = CP
Abfahrer = AD 
Einstellung früher rufen und Drescher folgen auf "ja" 
Kann das jemand auch bestätigen? 
Das 1.Abtanken läuft wie es soll,das Problem tritt dann erst später auf. 
Gruß Micha

**Comment by Stephan-S** [comment]
Hey, das ist leider kein AD Thema. AD steuert nicht den Drescher. Wenn was im Log steht, das von AutoDrive kommt, kannst du dich gerne nochmal damit melden. Ansonsten bitte beim CP Github melden.

Grüße,
Stephan
