### ISSUE TITLE
Sort destinations on display

### ISSUE THREAD

**Issue by rogeriodec** [Stephan-S/FS19_AutoDrive#644]
It seems that this is a recurring suggestion and I don't know why the plugin author doesn't implement it.
As the destination list grows, the interface becomes disorganized and difficult to find a destination.
Better would be a simple alphabetical sorting before showing the destination list.
A simple [Lua's Sort](https://www.lua.org/pil/19.3.html) instruction would solve this...

**Comment by Stephan-S** [comment]
It's already sorted. It has been for a Long Time. Please Update your Mod version

**Comment by rogeriodec** [comment]
The previous/next target is not showing in sorted order:
![a](https://user-images.githubusercontent.com/11199752/67133025-6838cf80-f1e1-11e9-9153-49301a1e0e64.gif)

**Comment by rogeriodec** [comment]
@Stephan-S although you have close this issue, could you fix this problem, please?
Pagination of destinations not sorted alphabetically makes them very difficult to locate.
