### ISSUE TITLE
Autodrive Course Editor öffnet nicht richtig

### ISSUE THREAD

**Issue by VatriXxX** [Stephan-S/FS19_AutoDrive#645]
Hallo,
ich wollte meine Kurse mal mit dem Course Editor ändern, jedoch öffnet sich dieser nicht richtig.
![grafik](https://user-images.githubusercontent.com/2685763/67110156-57349200-f1d2-11e9-839e-4a6bec31a8bb.png)
So sieht das aus, wenn er sich öffnet. Größer machen kann ich ihn auch nicht, dann sieht er nur so aus.
![grafik](https://user-images.githubusercontent.com/2685763/67110222-7f23f580-f1d2-11e9-9429-a83af5914e62.png)
Hat jemand eine Lösung woran das liegen könnte?

**Comment by Dzi4d3k** [comment]
Just use command line option form attached CMD batch file:
https://github.com/Stephan-S/FS19_AutoDrive/blob/master/AutoDrive%20Course%20Editor/Open%20Editor%20with%20Console%20to%20see%20errors.cmd

**Comment by VatriXxX** [comment]
> 
> 
> Just use command line option form attached CMD batch file:
> https://github.com/Stephan-S/FS19_AutoDrive/blob/master/AutoDrive%20Course%20Editor/Open%20Editor%20with%20Console%20to%20see%20errors.cmd

Sorry, i have used the cmd batch file, but it doesn't work too.... It's the same problem

**Comment by Stephan-S** [comment]
but is it showing an error in the cmd window?

**Comment by VatriXxX** [comment]
No, there aren't any problems.
![grafik](https://user-images.githubusercontent.com/2685763/67122903-23b43080-f1ef-11e9-8959-afac5e12eca6.png)

**Comment by VatriXxX** [comment]
If i open it with Java.exe and not with Javaw.exe there are some unknown sources?
![grafik](https://user-images.githubusercontent.com/2685763/67123111-afc65800-f1ef-11e9-9df0-29b14ab901ec.png)

**Comment by worker2419** [comment]
@VatriXxX kannst Du bitte einmal die Leerzeichen aus dem Ordnernamen Autodrive Course Editor entfernen und dann das Programm starten

**Comment by VatriXxX** [comment]
> 
> 
> @VatriXxX kannst Du bitte einmal die Leerzeichen aus dem Ordnernamen Autodrive Course Editor entfernen und dann das Programm starten

Funktioniert leider trotzdem nicht.

> 
> 
> but is it showing an error in the cmd window?

Do you have any idea?

**Comment by newbie-near-cologne** [comment]
Habe eben für die Hof Bergmann auch mal den Editior benutzt. Wenn man den Zoom benutzt, also das Mausrad, dann justiert sich die Map neu und passt sich der Fenstergröße an. Mit der linken Maustaste kann man die Map verschieben.

**Comment by VatriXxX** [comment]
> 
> 
> Habe eben für die Hof Bergmann auch mal den Editior benutzt. Wenn man den Zoom benutzt, also das Mausrad, dann justiert sich die Map neu und passt sich der Fenstergröße an. Mit der linken Maustaste kann man die Map verschieben.

@newbie-near-cologne War nen guter Ansatz, aber auch dies funktioniert leider nicht, das Fenster bleibt trotzdem so, bzw. die Map

**Comment by Dzi4d3k** [comment]
Have you tried to run it with admin privilidges (run as administrator)?

**Comment by VatriXxX** [comment]
> 
> 
> Have you tried to run it with admin privileges (run as administrator)?

@Dzi4d3k If i run as adminstrator, comes the message "Error: Unable to access jarfile .\AD.Jar"

I tried to run this on my other computer and there are the same problem...

**Comment by VatriXxX** [comment]
@Stephan-S Do you have any solution for my problem?

**Comment by VatriXxX** [comment]
Has anyone an solution for my problem?

**Comment by worker2419** [comment]
@VatriXxX you can follow the export steps and then start the editor? Look at Case #667

**Comment by Stephan-S** [comment]
@VatriXxX 
Sorry I didn't get to it sooner. Could you send me the config file that doesn't work and if the image is not already included, the PDA png you are loading?
Thank you

**Comment by VatriXxX** [comment]
Oh sorry i forgot to answer,

It works now, i don't know whats the problem was.
@Stephan-S

**Comment by Stephan-S** [comment]
Alright. Then I will close here for now.

**Comment by VatriXxX** [comment]
Ah wait, one question the map is not passed on the coursed, how can i make the map bigger?

**Comment by Stephan-S** [comment]
Select 4x or 16x button before loading the config. This will scale the points if you work with a 4 times map or 16 times map

**Comment by VatriXxX** [comment]
Ah okay, thank you :)
