### ISSUE TITLE
map is smaller than the ad courses in editor

### ISSUE THREAD

**Issue by anonimo2311** [Stephan-S/FS19_AutoDrive#650]
![Unbenannt](https://user-images.githubusercontent.com/56744138/67133849-1313b280-f20f-11e9-9898-39e362cb4e76.PNG)
 the courses is not 1 on 1 to the map
map too small for createt courses
and now?

**Comment by pcdoc69** [comment]
click the 4x4 button before loading the xml file. Also is the map pic 2048x2048
