### ISSUE TITLE
Alle Ordner offen im Dropdown Fenster

### ISSUE THREAD

**Issue by Fuzzy86** [Stephan-S/FS19_AutoDrive#653]
Hy Stephan!

Eine Frage, ist es möglich das beim öffnen des Dropdown Fensters die Ordner geschlossen bleiben? Wenn man nämlich ein neues Fahrzeug kauft und dann einen Wegpunkt oder so einstellen will sind immer alle Ordner Offen. Wenn man dann recht viele Ordner hat ist man schon ne Zeit beschäftigt sie zu schließen:-)

Vielleicht kann man das auch einstellen, das man beim  Öffnen des Fensters ganz oben ist und nicht erst rauf scrollen muss.

lg

**Comment by Spielbauer** [comment]
Hallo Fuzzy86, du sprichst mir von der Seele. Ich wollte genau dass selbe schon schreiben.

**Comment by Fuzzy86** [comment]
Na dann bin ich nicht der einzige den das etwas stört. Zum glück

**Comment by Stephan-S** [comment]
Ist im nächsten Update dann angepasst. Jedes neue Fahrzeug startet mit zugeklappten Ordnern.
Aber ich speichere dann weiterhin den letzten Status für jedes Fahrzeug ab. So dass bei jedem Fahrzeug immer die passendsten Ordner offen sein sollten

**Comment by Fuzzy86** [comment]
Super danke! 

Dein Support ist ja echt der Hammer 
👍👍👍👍
