### ISSUE TITLE
Motor stellt sich ab

### ISSUE THREAD

**Issue by Fuzzy86** [Stephan-S/FS19_AutoDrive#654]
Hey Stephan!

Wenn einem Fahrzeug ein Parkplatz zugewiesen wurde und ich dann mit diesem Fahrzeug einen Kurs einfahren will, stellt sich der Motor ab wenn man die Rekord Taste drückt.

Weiß nicht ob das evtl. ein Bug ist oder das nur bei mir auftritt.

Lg

**Comment by worker2419** [comment]
Guten Abend Stephan,
habe mir den aktuellen Code heruntergeladen und die ZIP mit der Änderung zu #654 selbst erstellt. Danach fährt AD auf den Warteplatz. Der Motor bleibt aber an. Auch das Löschen der Parkplatzzuweisung in der Vehicle.xml, erneutes Zuweisen ändert nichts am Verhalten.

**Comment by worker2419** [comment]
Hallo Stephan,
hab es heute mit der Version vor Path Planning noch einmal geestet und es funktioniert wieder wie gewollt.
@Fuzzy86 kannst Du bitte mit der aktuellen Version testen, die Du selbst zippen must?
