### ISSUE TITLE
f1 bug with  ponsse 

### ISSUE THREAD

**Issue by magicmana** [Stephan-S/FS19_AutoDrive#655]
hello  i have  found a  little  bug with autodrive
i test with version 1.0.6.4 on ravenport with  only autodrive.

when autodrive is active .  on ponsse  cutter ,  the  Y   pass to  hidden  in F1 menu.
Y key work to change  cutting length  but , i not see the  current setting.

![fsScreen_2019_10_19_17_27_18](https://user-images.githubusercontent.com/32802279/67147560-4e0cf900-f296-11e9-819d-449c195311a0.png)
![fsScreen_2019_10_19_17_28_59](https://user-images.githubusercontent.com/32802279/67147561-4e0cf900-f296-11e9-9e4f-cd127cccea0c.png)

thanks for  your great job.

**Comment by worker2419** [comment]
please turn off the AD help, then you can adjust the length

**Comment by Stephan-S** [comment]
You can disable the F1 help entries of AutoDrive in the AutoDrive settings ;-)
