### ISSUE TITLE
HUD Inhalte werden nicht angezeigt

### ISSUE THREAD

**Issue by worker2419** [Stephan-S/FS19_AutoDrive#656]
Hallo Stephan, habe die Position des HUD mit der Maus weiter nach oben verschoben. Ab einer gedachten Linie (etwa Mitte Monitor) werden die Inhalte der Listenfelder nicht mehr angezeigt. Version ist die selbst erzeugte ZIP ohne "Better Support..." Log ist ohne Einträge. Schiebt man das HUD wieder nach unten, erscheinen die Listeneinträge wieder. Die Inhalte sind vorhaden, wenn man den Pfeil nach unten wählt. Einzelschicksal :-(
![AD_01](https://user-images.githubusercontent.com/47278102/67151586-76155000-f2c8-11e9-9bee-dec95712f481.png) 
![AD_02](https://user-images.githubusercontent.com/47278102/67151590-7ca3c780-f2c8-11e9-8741-fb009775f446.png)

**Comment by haamic** [comment]
das Problem habe ich leider auch seit dem neuen HUD #657 
Stephan schaut sicher nochmal drüber

**Comment by worker2419** [comment]
Funktioniert mit der aktueleln selbst gezippten Datei, Danke für die schnelle Korrektur

**Comment by haamic** [comment]
bei mir gehts leider immer noch nicht
