### ISSUE TITLE
Abfahrer fährt Drescher immer wieder an, ohne zum Abladen zu starten

### ISSUE THREAD

**Issue by haamic** [Stephan-S/FS19_AutoDrive#658]
Hallo, 
mir ist aufgefallen, ( auch schon vor dem gestrigen Update mit dem kleineren Hud) das der Abfahrer den Drescher ( in dem Fall Roder) immer wieder anfährt, obwohl er voll ist und zum Silo fahren sollte. 
Erst wenn ich ihn beende und neu einstelle fährt er zur Abladen. Ist auch nicht immer so, kein Muster erkennbar, warum er sich so verhält.
Im Log ist nichts zu sehen. Hat jemand sowas auch beobachtet?
Gruss Micha

**Comment by Woife1** [comment]
mir kam der Abfahrer gstern auch ein bischen aggressiv gegen über dem Drescher vor

**Comment by worker2419** [comment]
Nein, konnte ich mit der allerneusten Version (selbst gezippt) nicht beobachten. 3 Felder in Folge mit Drescher abtanken und abfahren ohne Probleme. Habe die Funktion Vorab losfahren und folgen nicht aktiv

**Comment by Woife1** [comment]
Ohne früher rufen und folge Drescher funktionierts auch tadellos

**Comment by pulimatrix** [comment]
also das Der abfahrer seid der neuen version Sehr agresiv ist beobachte ich, er fäht drescher rohr an bremst den beschleinigt er plötzlich rasst im drescher und verkeilen sich :/ verfolgen und früher rufen hab ich aus, also nix Tadellos

**Comment by Stephan-S** [comment]
Das mehrmals Anfahren sollte sich erledigt haben. Hier war eine Überprüfung ob der Hänger voll ist oder noch nicht ganz, etwas unscharf definiert und an verschiedenen Stellen anders genutzt.

Ich mache hier mal zu. Allgemine Fehler zum aktiven Abladen sind ja noch an anderen Stellen vermerkt
