### ISSUE TITLE
How to delete a destination?

### ISSUE THREAD

**Issue by rogeriodec** [Stephan-S/FS19_AutoDrive#659]
I created a destination name in the wrong place. 
How can I delete it?

**Comment by raxtor** [comment]
Right button and click to delete waypoint

**Comment by rogeriodec** [comment]
Right click where exactly? 
Also, I'm using CoursePlay mod and the Right Click is reserved to open this mod.

**Comment by Woife1** [comment]
you can change the CP opening funktion (from right click to ctrl+del) in the CP setting 

delete waypoint is the icon in the top row the second from the right side (next to the floppydisk sign)

**Comment by rogeriodec** [comment]
@Woife1 I'm talking about deleting a destination, now waypoint.
Or I'm confused about the difference between these two terms:
![image](https://user-images.githubusercontent.com/11199752/67161655-f375aa80-f332-11e9-857c-c4b1fd2d2294.png)

**Comment by raxtor** [comment]
![del](https://user-images.githubusercontent.com/831266/67162073-fc7d7080-f360-11e9-86db-bfa76e3914d2.png)
I assume you have AD course and some waypoint named MyPointA.
Go to MyPointA, right click to "yellow square". It removes waypoint MyPointA. Then create new waypoint in different place. Dont forget recalculate routes.

**Comment by rogeriodec** [comment]
Thank you all
