### ISSUE TITLE
Minor improvement: focus the cursor inside the field when naming a new mark

### ISSUE THREAD

**Issue by rogeriodec** [Stephan-S/FS19_AutoDrive#662]
It seems to be similar to https://github.com/Stephan-S/FS19_AutoDrive/issues/375.
When I click to create a new mark, the cursor is not automatically focused inside the title field:
![image](https://user-images.githubusercontent.com/11199752/67163806-b537b580-f349-11e9-8264-2f23b5fbc8c0.png)
So I have first to click inside that field to start typing.

**Comment by Dzi4d3k** [comment]
Looks, like it can but improved but adding focus on text filed in GUI configuration. Tips for @Stephan-S that, Seasons is using (at least in FS17 was) some XML property to add focus (pre-focused) text field.

**Comment by Stephan-S** [comment]
@Dzi4d3k Thanks for the info!
I already tried a few things out and it didn't really work out. I'm not quite sure how the focus manager works to be honest.
So if you have some knowledge about this and want to contribute you could try finding out what property to set to get this to work.
I will add this as to do on my part but I don't have the time to prioritize it right now :-)
