### ISSUE TITLE
Mark angles > 90°

### ISSUE THREAD

**Issue by rogeriodec** [Stephan-S/FS19_AutoDrive#666]
I created a route from a field to refill plow and return, and as the image below, I created a crossing route between the two routes (round trip) so that the tractor goes directly to the destination through this crossing route.
However, even updating the routes, the tractor is not making this return and is heading straight for the street.

![image](https://user-images.githubusercontent.com/11199752/67165505-444dc900-f35c-11e9-8697-e89ff8466e4a.png)

What did I do wrong?

**Comment by raxtor** [comment]
There is 90 degree limit for course calculating. You have too sharp angel...

**Comment by Stephan-S** [comment]
Thanks @raxtor 
Yeah that angle is Impossible to Drive.
But that reminds me that I have to Mark These sections (at least after the recalculation step) as not being used somehow.

**Comment by raxtor** [comment]
And what only warning message after re-calculating? Eg. Warning: 2 joining will not be used becuase angel is higher than 90...?

**Comment by Stephan-S** [comment]
I was thinking more about changing the color of the Line to Red.

**Comment by raxtor** [comment]
Still problem that user has no idea what is wrong...

**Comment by Iwan1803** [comment]
Anyone who uses AD should find out pretty quickly that too tight curve radii can not be used.
There are enough videos explaining how AD works and what to look for.

**Comment by rogeriodec** [comment]
If a warning message in addition to a colored indication were placed, as mentioned above, this doubt would not occur.
I support the constant improvement of the mod.

**Comment by raxtor** [comment]
In fact if you know about that limitation, you dont need any warning at all. So warninig msg is enough for understanding to problem. 
Partly its due to the lack of tutorials and some things are hidden. I will try prepare some list of hidden things when I will get more free time.

**Comment by rogeriodec** [comment]
That would be fantastic!
I know all this work is voluntary and always done willingly, especially for a game whose purpose is just fun.
Even so, all goodwill is somehow rewarded at some point, one way or another.
Thank you for all your attention.
