### ISSUE TITLE
How to connect to bi-directional waypoints?

### ISSUE THREAD

**Issue by rogeriodec** [Stephan-S/FS19_AutoDrive#668]
I'm trying to create a bi-direction (blue) route and when I deleted some blue waypoint, after trying to link them again, AD is creating a green waypoint.
![image](https://user-images.githubusercontent.com/11199752/67166349-b88c6a80-f364-11e9-9795-b3a30a3a9269.png)
How to do this?

**Comment by raxtor** [comment]
Delete point by green arrow and than join 2 blue course?

**Comment by Dzi4d3k** [comment]
Nope, note that red line form tractor points begin of vector, and yellow lint points end of vector. Yellow line can be switched to different waypoints so you can chose ending where you like.
Now if you point red line to end of new vector (on arrow of green arrow), and yellow line point to beginning of vector and connect you will make bi-diectional vector (blue one).
Kind of messed explanation but I hope it helps.

**Comment by raxtor** [comment]
Its bit complicated...:
Let green course how you have it, than move tractor like you want join course from opposite direction. Than join it and AD will switch it to blue course. (Two opposite green courses in same place make blue)

**Comment by rogeriodec** [comment]
I have always understood that the red line indicates the point of ORIGIN and the yellow line indicates the point of DESTINY.
So what I did was this:
1) This is the original blue line:
![image](https://user-images.githubusercontent.com/11199752/67166966-fd1b0480-f36a-11e9-9eab-eb71a16d8c87.png)

2) Then I clicked on the icon to delete this segment:
![image](https://user-images.githubusercontent.com/11199752/67166975-1754e280-f36b-11e9-9a51-1fd7584a641f.png)

3) Then click on the icon to rewire the segments:
![image](https://user-images.githubusercontent.com/11199752/67166984-263b9500-f36b-11e9-8284-915901aabebd.png)

But as you can see, the green line was created and not the blue one ...

**Comment by raxtor** [comment]
ad 3rd pic.: Now move tractor in front till red line wont be switched to yellow, than join it again and grren course will be blue.

**Comment by Dzi4d3k** [comment]
And now you have to switch positions red with yellow by driving tractor closer to end of green arrow, and point yellow to begin of green arrow, and toggle connection

PS. @raxtor was first :)

**Comment by rogeriodec** [comment]
Done:
![image](https://user-images.githubusercontent.com/11199752/67167061-df01d400-f36b-11e9-929d-f9f06be196ec.png)
Man, AD is not for the weak, huh?

**Comment by Dzi4d3k** [comment]
The tough task is to achieve complicated functionality with few buttons :)

**Comment by raxtor** [comment]
There is a few tricks hidden for newbies :-) I want to make full tutorial, but Ia m busy too now... not earlier tahn January 2020..

**Comment by andejx** [comment]
yeah took me a while to understand that when you create the "multi-directional" paths, all its really doing is linking the two points in both directions, instead of just one way. So its technically two paths you have to create to manually if you need to edit it.
