### ISSUE TITLE
Probleme im Zusammenspiel mit courseplay

### ISSUE THREAD

**Issue by siggiblue** [Stephan-S/FS19_AutoDrive#67]
Hallo Stephan,
zunächst mal möchte ich mich bedanken für diesen supertollen Mod
Es gibt allerdings ein paar Unstimmigkeiten:
COURSEPLAY
Ich benutze die CP-Version 6.00189 und lasse den Drescher ein Feld bearbeiten. Als Abfahrer benutze ich Deinen MOD. CP hat die Eigenheit das wenn der Drescher voll ist ihn anhält und wartet das ein Abfahrer kommt. Er fährt aber nicht das Abladerohr raus, was für den Abfahrer ja das Signal wäre zu starten; der Abfahrer bleibt also stehen und wartet endlos. Wenn man selber fährt oder den Giants-Helfer benutzt ist alles ok, dann verstehen sich Drescher und Abfahrer.
VERBESSERUNGS-VORSCHLÄGE
Die Meldungen wie "ABFAHRER IST AM .... ANGEKOMMEN" etc werden oben links in der Ecke angezeigt. Dort werden sie sehr schnell übersehen zumal sie auch sehr schnell wieder verschwinden. Eine etwas plakativere Darstellung wäre nicht schlecht.
Die Auswahl der zu verkaufenden Früchte ist bei einer Multifruit-Map sehr groß. Vielleicht läßt sich die Anzeige und Auswahl mit einem Dropdown-Menü vereinfachen.

Ich mache mich mal wieder an mein Streckennetz und bin sehr gespannt was noch alles so kommt.
Gruß
SiggiBlue

**Comment by Stephan-S** [comment]
Servus, danke für dein Feedback.
Das CP Problem werde ich demnächst angehen. Versprochen ;-)

Die Meldungen wurden jetzt schon öfter bemängelt. Über Vorschläge wie es besser wahrgenommen wird bin ich natürlich froh. Einfach nur unten mittig? Die Zeit habe ich derzeit auf 6 Sekuden Anzeigedauer gestellt. Ist das noch zu wenig?

Die Früchte kannst du per Mausrad scrollen. Einfach in die rechte Hälft des Zielfensters (Abladen) mit der Maus und mit dem Mausrad die Frucht einstellen. So lassen sich auch die Ziele einstellen.

**Comment by siggiblue** [comment]
Hallo,
zur Farbe der Meldungen: gelb oder rot wäre gut und dann größer als zur Zeit. Die Farbe weiß geht unter dass kennen wir ja vom Standard schon (Z.B beim Preis etc. oben rechts)
Die Position unten mittig ist nicht schlecht.
Ich habe aber noch etwas anderes festgestellt zum Thema Laden und Verkaufen:
Das Silo war gefüllt mit 185.000 Ltr. Sonnenblumen. Zum Verkauf wurde ein Hänger mit einer Kapazität von 80.000 Ltr. benutzt. Er hat also 2 Touren super erledigt. Beim dritten Mal fährt er wieder das Silo an und lädt den Rest, also 25.000 Ltr. und dann bleibt es stehen und wartet offenbar bis er wieder voll ist. Geht aber nicht, da das Silo für diese Frucht leer ist. Kann man das programtechnisch abfragen was von der gewählten Frucht noch da ist und wenn diese leer ist auch mit einem nicht vollen Hänger losfahren und einen weiteren Durchlauf verhindern ? Oder man schafft die Möglichkeit das man, sowie bei CP, die Anzahl Durchläufe vorgibt. Das kann man sich ja vorher ausrechnen.
Gruß
SiggiBlue

**Comment by siggiblue** [comment]
sorry, falsche Taste erwischt. wollte das gar nicht schliessen.
