### ISSUE TITLE
Can't change de delivery location / drop-down doesn't show all destinations

### ISSUE THREAD

**Issue by rogeriodec** [Stephan-S/FS19_AutoDrive#671]
I'm trying to use Pickup and Deliver.
With the new https://github.com/Stephan-S/FS19_AutoDrive/tree/master/releases/1.0.6.5 version, the navigation buttons were removed, however, I can use the Ctrl+Alt+Left (or Right) arrows, but it just work for the first (pickup) field:
The second (delivery) doesn't move:
![image](https://user-images.githubusercontent.com/11199752/67171686-898aee80-f38e-11e9-99a8-02f1720c632c.png)
Also, if I open the dropdown list of delivery field, it brings just one item:
![image](https://user-images.githubusercontent.com/11199752/67171719-aa534400-f38e-11e9-8689-1ae0c1c6d08c.png)

(The problem above also happens with other modes).

And now?

**Comment by Woife1** [comment]
easy way to fix it
just scroll up with your mouse-wheel (you can enable mouse by clicking on the wheel or enable it with CP)

**Comment by Martinnygaard** [comment]
But why does it so often show only the buttom destination? The first would make much more sense.

**Comment by rogeriodec** [comment]
Yes, I put the second problem in the title also.

**Comment by rogeriodec** [comment]
> easy way to fix it
> just scroll up with your mouse-wheel (you can enable mouse by clicking on the wheel or enable it with CP)

Thanks, the list was there, but it's tricky and will continue to mislead new users until the interface is improved by inserting, for example, a scrollbar to let the user realize that there are more items above the current item and furthermore allow the key up and down keys to scroll through the list. , which today is not allowed.

**Comment by kbrandwijk** [comment]
@Woife1 Honestly, that simple remark was a lifesaver. I installed AD for the first time, and only saw the first waypoint as well. Tried everything (I thought): scrolling down, opening the XML, opening and resaving it in the editor, refreshing paths etc. If only all things would be that simple.

And I agree it could do with some UI work :)

**Comment by Woife1** [comment]
But don't forget Stephan build this mod alone and he makes a very good work

UI work will be done when he hasn't other things to manage/do
