### ISSUE TITLE
Multi bin trailer / overloader support - 'Combine unloading'

### ISSUE THREAD

**Issue by Martinnygaard** [Stephan-S/FS19_AutoDrive#672]
Hi,

I am driving two combines (Fendt Ideal, Vanilla) in convoy.
One Vanilla Case IH Magnum with a Annaburger HTS 34.16 overloader (With two bins)

When it drives for empty the combine, it fills the 1st compartment, and then when that is full, it just stops there. 
I do not know you how it behave when it needs to unload the two compartment in one truck trailer.

![AD](https://user-images.githubusercontent.com/26490587/67185481-38a6e480-f3e6-11e9-8aca-73e2822edad6.png)

**Comment by raxtor** [comment]
https://github.com/Stephan-S/FS19_AutoDrive/issues/542#issuecomment-540838446

**Comment by Martinnygaard** [comment]
> [#542 (comment)](https://github.com/Stephan-S/FS19_AutoDrive/issues/542#issuecomment-540838446)

I know about your threat, and it is very simular - but i think the difference is that your issue is the wilson trailer is two bin (while i use a one bin) - and your overloading is 1 bin (while my is 2 bin).

Maybe it's the same - i do not know.

**Comment by raxtor** [comment]
I know that mod, not sure if its mod problem because bad triggers or AD doenst support such kind of triggers. Maybe link that mod here for Stephan..

**Comment by Martinnygaard** [comment]
I intented to add the link - must have forgotten.
It's from modhub: [LINK](https://www.farming-simulator.com/mod.php?lang=en&country=dk&mod_id=140029&title=fs2019)

**Comment by Stephan-S** [comment]
Hey guys,
I recognize the problem and I am sorry it exists, but I will add this as long-term goal since it is not relevant to as many players as some of the other open issues that I would like to work on.
This includes all multi-bin support.

Thanks for your understanding :-)
