### ISSUE TITLE
Ponse

### ISSUE THREAD

**Issue by Reiko40** [Stephan-S/FS19_AutoDrive#673]
Hallo 
Kann es sein das Auto Drive ein Problem mit dem Ponse hat? Wenn ich Auto Drive Mod aktiviere kann ich beim Ponse keine Schnittlängen mehr ein stellen und wird auch nicht mehr angezeigt.

**Comment by worker2419** [comment]
You can disable the F1 help entries of AutoDrive in the AutoDrive settings
Du kannst die F1-Hilfe-Einträge von AutoDrive in den AutoDrive-Einstellungen deaktivieren.

**Comment by Woife1** [comment]
nutz wenn dein F1-Menü zu voll ist einfach die Innenansicht und drücke "Z" auf dem Display im Fahrzeug müssten sich die Zahlen ändern (100, 200,... hier sind es cm)

if the F1-menu is not large enough 
switch inside the vehicle (camera position)
press "Z" 
look at the vehicle display if the numbers changes
