### ISSUE TITLE
Pause / Stop recalculation when clicking button again

### ISSUE THREAD

**Issue by spielera** [Stephan-S/FS19_AutoDrive#674]
Was hast du aus den Hud draus gemacht??
Ich finde es zu klein und unübersichtlich. 
Vorher war es besser.

Könntest du noch eine Abfrage einarbeiten, und zwar bevor man die Strecken aktualisiert.
Ob man es machen will oder nicht.
Bin jetzt schon mehrmals aus versehen drauf gekommen.

Könntest du eventuell ein toll einbauen, wo man die Strecke nach Links oder Rechts verschieben kann?

Ich will nicht nur meckern.
Ich muß dich auch loben, für die viele Arbeit, die du dir machst.
Mach bitte weiter so.

**Comment by worker2419** [comment]
> Könntest du eventuell ein toll einbauen, wo man die Strecke nach Links oder Rechts verschieben kann?

@spielera hast Du dich schon einmal mit dem Autodrive Editor auseinander gesetzt?  #544

**Comment by spielera** [comment]
Nein, habe ich noch nie gemacht.
Damit kann man wo die Strecken verschieben?

**Comment by Woife1** [comment]
das soll man damit machen können sowie Kurse von Grund auf erstellen

bisher noch nicht selber versucht....

**Comment by Stephan-S** [comment]
Die 'Abfrage' ist der Schalter auf den Editor Modus ;-)
Was ich mir mal anschauen kann, ist das Abbrechen des Berechnens ohne Datenverlust.

**Comment by geo-luchs** [comment]
> Nein, habe ich noch nie gemacht.
> Damit kann man wo die Strecken verschieben?

Mit dem Editor kann man einzelne Wegpunkte wunderbar verschieben.
Zielpunkte setzen oder auch löschen ohne den Wegpunkt zu löschen.
Neue Wegpunkte setzen.
Verbindungslinien setzen.

Ein Klasse Tool.
Holger-70 hat dazu ein YouTube Video erstellt.

**Comment by Stephan-S** [comment]
Done
