### ISSUE TITLE
How to use AD with Courseplay to unload combine?

### ISSUE THREAD

**Issue by rogeriodec** [Stephan-S/FS19_AutoDrive#675]
Although I've seen there is a "use Autodrive" option in the CP HUD, I can't get how can I use it to replace the CP Mode 2, ie, unload the harvester in a field to a truck and transport and unload it to a silo and then return to the original field to wait for more load.
Any tutorial?

**Comment by Iwan1803** [comment]
Yesterday in my stream we found a way if a tractor should collect straw from the field and then take it away:
- select the CP course
- activate in CP AutoDrive: change "Don't use" to "For unload/refill"
- set AD to "Pick up and deliver" 
- set in AD the start point, the deliver point and what to deliver
- don't start AD
- start only the CP course
When the trailer is full, CP automatically activates AD (can see it at the power button fom AD). It then drives from the field to the AD start point, from there to the unloading destination, does the unloading and drives then back to the field. Then CP will continue.

**Comment by loeschknecht** [comment]
Several combines don´t unload with AD. For example the Claas DLC combines.

**Comment by Iwan1803** [comment]
Looks like the problem is the thresher, which doesn't extend the pipe. So the trigger will not be activated.
I will test it later with several combinations.

**Comment by Woife1** [comment]
the new DLC is not supported yet
wait a few days then they will

**Comment by rogeriodec** [comment]
> you could use AD alone for unload combine (AD Mode with the harvester icon)
> 
> the combination of CP and AD is for refill a seeder or so
> CP only use the fieldcourse (option for use AD to refill/unload must be set) and AD is set to pick up
> the same you could do for pick up gras (AD-Mode pick up and deliver)

The truck keeps in "Wait for combine" even if the combine is stopped and full...
What could be?

**Comment by Martinnygaard** [comment]
> the new DLC is not supported yet
> wait a few days then they will

I noticed that aswell - i'm waiting patient for a fix someday :-)

**Comment by geo-luchs** [comment]
#682 here you can find also some information.
Stephan has fixed the problem with Claas DLC

**Comment by Martinnygaard** [comment]
Claas fix is done.
AD/CP tutorial i given.
I think this issue can be closed :-)

**Comment by Stephan-S** [comment]
@rogeriodec If you still have any questions that aren't answered in wiki and tutorials, feel free to reopen :-)

**Comment by aletheist** [comment]
I'm new to Farming Simulator and to Autodrive and to Courseplay, so please forgive me if I'm missing something obvious.

I am trying to combine using courseplay for fieldwork and autodrive for trucking things around, including combine unloading. I have gotten Autodrive to mostly work fine when using an AI combine worker; I do sometimes have issues where the tractor with tipper seems to be out of range of the combine.

I have been completely unsuccessful in combining CP and AD. I have tried the following unsuccessfully.

1. Setting things up the same way I would with the default AI - i.e. set an AD trailer next to a tried and set it to unload combine.
2. Enabling AD with unload combine and CP set tounload with autodrive.
3. Setting a trailer next to a field with AD disabled but wait point and unload point selected with CP's AD integration enabled.

When I use CP combine workers, it seems to either wander off at unload time, or just halt.

[I do not see any documentation in the wiki](https://github.com/Stephan-S/FS19_AutoDrive/wiki/8-Courseplay-integration), nor have I found any integration tutorials.

**Comment by Iwan1803** [comment]
Why did you post that in a closed issue?
You can post the question in a new issue or join Discord: https://discord.gg/sUQtKhB
