### ISSUE TITLE
The new UHD is really bad ..

### ISSUE THREAD

**Issue by Roby1164** [Stephan-S/FS19_AutoDrive#676]
I don't know why you made this change, but the old UHD was much better.
If there is no particular reason, it would be nice to go back to the old one.

**Comment by Dzi4d3k** [comment]
Could you leave any more precise input than "bad"?
What resolution do you uses. Some screenshoot would be useful for author to look which part of GUI need adjustment.

**Comment by Roby1164** [comment]
I don't like it, I preferred the previous structure, the arrows have also been removed to quickly select, the button to import / export the save, etc. I think it was more readable. Indeed, it would be better to extend it even more horizontally. in some cases, with some languages, for example Italian, some words are longer and not completely displayed.

**Comment by raxtor** [comment]
I have no problem with new HUD, maybe needs some adjustment but I really like idea hide all elemnts which are needed for course manipulation a and show only buttons for AD driving control... **Good step forward** for me...

**Comment by Bandesss** [comment]
Ich fand das alter besser, einfach von der grösse her.
Vielleicht kann es Stephan ein bischen länger machen... das es nicht aussieht wie ein würfel?

**Comment by Roby1164** [comment]
What software do you use to create or modify the Uhd ??

**Comment by Stephan-S** [comment]
How do you like the updated look? Does it improve the usability?

**Comment by Roby1164** [comment]
I do not know, at first glance I do not like very much, I prefer that the HUDs are more linear and not square, even that of before, it was not the top, but being the first, it was that, then it depends on the tastes ..
I would see it better if it is long and narrow in height, and perhaps with more colorful icons and a more transparent background so that positioned below or above, in the center of the monitor, would be less invasive, for those who keep it open and under eye ..

**Comment by Bandesss** [comment]
Gute Idee Stephan nun ist zu Quadratisch.

**Comment by geo-luchs** [comment]
More transparent it is already
