### ISSUE TITLE
Unloaders do not stay assigned to combines / stay idle in field

### ISSUE THREAD

**Issue by gigilal** [Stephan-S/FS19_AutoDrive#679]
Hi Stephan I am loving your mod more than any other mod in the game and I just want it to improve. 

I have a suggestion for you to the mod, so right now I am using 3 combines on one field and to get these combines unload quickly and not to have to much waiting time I need to have two tractors with Auger's attached, my only problem here is that when one combine is full it calls for both Tractors with Auger attached so both of them drive to the same target to unload and the first one to arrive wins but the secound one will be stuck there with "unloading combine" untill I restart it. Is there something you can do here?

I am running it on dedicated server fyi.

Hope to hear from you.

**Comment by Farmer89** [comment]
You can make for example more routes for auger tractors...i have Unload-1, Unload-2 and for Combine-1 call Unload-1 etc. It works very well.

**Comment by gigilal** [comment]
@Farmer89 Not a bad ideal at all I will try it.

**Comment by raxtor** [comment]
@gigilal active unloading is still in progress. Version 1.0.5.9 or 1.0.5.7 works well with multiple unloaders a and combines... stay tune, I am sure it will get to birilliant stage too. #542

**Comment by Iwan1803** [comment]
Try to uncheck the option, that the thresher chooses the unloader.
