### ISSUE TITLE
BGA mode

### ISSUE THREAD

**Issue by Huskiel** [Stephan-S/FS19_AutoDrive#681]
Hey,
der BGA mode funktioniert nicht mehr.
Wenn ich AD anschalte kommt nur die Meldung das er keinen weg zum zum Zielpunkt gefunden hat.

**Comment by HerrchenChris** [comment]
Und bei mir schafft er es im BGA-Modus, dass mein Radlader mit Silageschaufel regelmäßig links oder rechts an der Wand des Fahrsilos hängen bleibt beim Einfahren in Selbiges.

**Comment by Stephan-S** [comment]
@HerrchenChris Einfach mal die Schaufelgröße in den AutoDrive - Fahrzeugeinstellungen etwas hochdrehen. Vermutlich liegt die Silodefinition bis in die Wände hinein.
Damit kannst du hier etwas Abstand von der Wand erzwingen.
@Huskiel Das klingt aber eigentlich als wärst du einfach im falschen Modus.. Seltsam

**Comment by HerrchenChris** [comment]
@Stephan-S also, ich habe jetzt die Schaufelbreite +2,0m gestellt, habe es mit der Silageschaufel und der normalen Schaufel probiert, sowohl mein Radlader wie auch der Teleskoplader rammen die Wand teilweise immer noch wie gestern. Ist auch nicht weniger geworden.

**Comment by Stephan-S** [comment]
Welche Map bzw was für Fahrsilos? Schließt das Silo bündig mit der Mauer vorne ab oder sitzt das eigentliche Silo versetzt weiter innen? Dann würden die Mauern sich noch im Rangierweg befinden

**Comment by Iwan1803** [comment]
Da kein weiteres Feedback -> geschlossen.
Bitte mit der neuesten Version erneut versuchen und bei Bedarf ein neues Issue erstellen, danke!
_Since no further feedback -> closed.
Please try with the latest version and create a new issue if necessary, thanks!_
