### ISSUE TITLE
Drescher wird nicht abgetankt

### ISSUE THREAD

**Issue by betjal** [Stephan-S/FS19_AutoDrive#682]
Traktor (Axion 870) steht auf freiem Feld (Feld 1, NF Marsch), Drescher (Lexion 890), Traktor (AD aktiv, soll Drescher abtanken und in Silo speichern) steht auf "Blocking", Drescher ist voll.

**Comment by betjal** [comment]
Sorry, did not read the issue of posting new issues. My Axion 870 is on field 1 (map "NF Marsch"), the harvester (Lexion 870) is fully loaded but the Axion does not empty it.

**Comment by raxtor** [comment]
Are you sure you set same waiting point by combine like uses unloader?

**Comment by betjal** [comment]
Yes, I am sure, because there are only two targets at the moment: field and silo. Both machines are set to field one, the Axion in addition to that on the silo as second target

**Comment by hathor1411** [comment]
I have the same problem. Maybe it's the Claas DLC. The Lexion, Tucano does not pull out the overload tube.

**Comment by Onkel2000** [comment]
Bei mir das gleiche Problem.

**Comment by Twetch** [comment]
I have same problem DLC combines not calling unloading tractor

**Comment by Woife1** [comment]
leider werden nur die größeren Youtuber mit dem DLC vorab ausgestattet und nicht die sehr guten Modder
wird noch ein paar Tage dauern bis die neuen Maschinen unterstützt werden 

It could take a few days until the new machines are supported by Mods

**Comment by Iwan1803** [comment]
It should be nothing new, that new vehicle mods like to have something in itself or changes, so that other mods do not work properly with them.
So we'll have to wait a bit for the modders to figure out what was changed and to fix it then.

**Comment by Twetch** [comment]
> It should be nothing new, that new vehicle mods like to have something in itself or changes, so that other mods do not work properly with them.
> So we'll have to wait a bit for the modders to figure out what was changed and to fix it then.

But if we don't  tell him than he can't  fix it, so all this coments are pointless.

**Comment by Iwan1803** [comment]
He now knows about the problem. So we have to wait now ;-)

**Comment by Andii1980** [comment]
ist bei mir genau das selbe Problem. Drescher: Claas Lexion 8900, Abfahrer: Claas Axion 960, Anhänger: ist egal welcher.

**Comment by andejx** [comment]
Had this issue with the modded Ideal Combines too. 
https://www.yesmods.com/fs19-mods/harvesters/combine-harvesters/agco-ideal-combine-extension-mu/ 
They won't call the waiting tractors in combine mode.

**Comment by loeschknecht** [comment]
Ich habe das gleiche Problem. Wird nur schwierig Giants davon zu überzeugen Ihre DLC Drescher umzuscripten.

**Comment by geo-luchs** [comment]
I've tested it  now, too. Claas DLC Combine is driven by CP.
Unloader is Claas DLC Xerion.

With Claas combine, it's not working, with vanilla combine, it'S working. Both tests with Yerion unloader

Claas DLC is not extending the pipe.
I believe, that AD is waiting for this pipe.

Then I tried to stop CP, extended the pipe manually, but unfortunately AD didn't started.

**Comment by Stephan-S** [comment]
Thanks for the Info! AD is only called at 100% fill Level. If CP was driving before it was probably at ~95%. So If CP is No longer actively requesting an unloader, this isn`t working. 
But the Pipe Not extending is probably the Problem, yes.
I'll get too it as soon as I can. Probably next week.

Btw: If you have extended the Pipe, you can call the unloader manually. Just assign a keybinding in the game Options for it. If this is also Not working, than it might be something more complicated

**Comment by Iwan1803** [comment]
I tried the Claas tresher and nothing happens if i extend the pipe or if i call the unloader by the keybinding. You can see it in last 10 or 15 minutes of my stream.

**Comment by wallsingham** [comment]
I tried it with a new Game on the Felsbrunn Map.
The Claas Harvesters and the Forage Harvesters can't call any unloader, neither automatically nor manually. 
The Claas Tractors can work fine with AD as unloaders.

**Comment by Tensuko** [comment]
Since CP treats all Combines the same, I don't see why CP wouldn't be able to call AD for unload unless GIANTS did something that we don't know.

**Comment by wallsingham** [comment]
This problem may be related to the pipe or the pipe marker of the new Claas Harvesters and the Forage Harvesters. It is not even possible  to call the unloader manually!

**Comment by wallsingham** [comment]
This problem may be related to the pipe or the pipe marker of the new Claas Harvesters and the Forage Harvesters. It is not even possible to call the unloader manually!

**Comment by Iwan1803** [comment]
@wallsingham did you read all?
It's not only the pipe as the unloader can also not be called by key binding.
Let's wait for Stephan and a solution.

**Comment by geo-luchs** [comment]
Hello @tensuko  and @Stephan:

One question : Who ist extending the Pipe of the combine?

Because: i Made some Tests. With a Giants combine CP was stopping the combine and extended the pipe.

Afterwards the AD unloader started.

With Claas DLC  the combine stopped, too. But didn't extended the pipe. 

Is that a function of CP to extend the pipe? 

And did someone tested it with a cp unloader? I've never used CP for unloaders, so i can't test it, sorry.

**Comment by wallsingham** [comment]
@Iwan1803 > Let's wait for Stephan and a solution.
Yes ;-) this will be the best

**Comment by Farmer89** [comment]
Its not CP problem, cuz im not using it and have same problem..All base game combines work, but there is problem with moded/DLC combines.This one dont work also http://www.farmingsimulator19mods.com/john-deere-s600-2012-2017-series-official-v1-0-0-0-fs19/

**Comment by geo-luchs** [comment]
My test with a RSM 161
CP is not extending the pipe, I've seen now.
CP is only driving in parking position, and gives the hint, that it needs to be unloaded.
Only when activating AD of the unloader, the pipe wil be extended.
So it seems to be an action by AD itself.

And AD is somehow not detecting the full harvester info

**Comment by Iwan1803** [comment]
We did a test in my stream today. There is no possibility to use CP to unload the tresher and then AD to unload the unloader 😄 
CP has only 2 or 3 modes where you can activate AD and "unloading the tresher" is none of them 😢 
CP has closed the request in the meantime as it is not a CP problem.
So we need to wait for Stephan and a solution.

**Comment by Corona01** [comment]
Also das Drescher abtanken mit den Claas Traktoren Axion 870 und 960 aus dem DLC funktioniert nicht.
Ich habe aber auch einen anderen Axion 960 Mod, da funktioniert es ebenfalls nicht.
Wollte heute auf der DonDiego beginnen, hab mit den Axion Traktoren rumprobiert und jetzt klappt gar kein Drescher abtanken mehr auf dieser Map, Drescher John Deere mit Giants Helfer gesteuert, Abfahrer Fendt 1050 Vario oder New Holland T8 klappt nun auch nicht mehr.
Werde mal wieder auf der MultiMap weiterspielen, mal sehen ob dort noch alles klappt.
Bin von AD 1.0.6.5 wieder auf 1.0.6.3 zurück.

**Comment by geo-luchs** [comment]
Sounds good. 
I will test it in the evening , too

Great work Stephan that you fixed it so fast. I've seen your Code changes. 
How you are getting this Information? Unbelievable.

**Comment by Tensuko** [comment]
> There is no possibility to use CP to unload the tresher

There is, but Mode2 is not working good thats why it gets a rework :) and even that Version you can try out and I did it and they work very well, with all Claas Tools.

> CP has only 2 or 3 modes where you can activate AD and "unloading the tresher" is none of them

Becouse you don't need to tell CP to use AD for unloading a Combine. Later when our Mode2 rework is done, I am sure we add the same option to use CP on the Field for unload and AD to drive on the AD Network, like you do in Mode4 and Mode5.

**Comment by Stephan-S** [comment]
@geo-luchs 
I knew what to look for after I started the game with the new platinum extension :D 
But honestly, it was bad code to limit this function by typeName anyway, so I already changed it again and incompatibilies like this should be a thing of the past.
Well I learn every day :-)

@Tensuko I am really eager to see CPs reworked Mode2 and I am sure you will enable AD roadwork for it. It really is a lot of work to write a proper unloader that works for almost all cases and mine is currently not where I would like it to be.
I just enjoy working on it and I hope you guys at CP don't see it as a competition or challenge from me that I added the unloader function to AD. I like working together on getting the best experience for the players while also enjoying the coding as it is a hobby and should be enjoyed :D
And the unloader is a lot more fun than just following and editing waypoints ;-)

**Comment by geo-luchs** [comment]
@Stephan-S  great. unfortunately I can't find the commit. 

and I am a user of both, CP  + AD, I'm happy to have both. For me it's also not a challenge between both mods. I'm using both.
And some users will only work 1 mod, others the other mod.

So, please continue with your work in  the same way. It looks really good, how you are working together.

Thanks to both

**Comment by Corona01** [comment]
Danke Stephan,
jetzt läuft es mit den Claas Traktoren und dem Drescher abtanken.

**Comment by Martinnygaard** [comment]
I think this issue can be closed :-)
