### ISSUE TITLE
Bad HUD adjustment

### ISSUE THREAD

**Issue by Twetch** [Stephan-S/FS19_AutoDrive#683]
After last update i have this.. resolution 3840x1080
![fsScreen_2019_10_22_18_36_17](https://user-images.githubusercontent.com/22034856/67308960-5a45c000-f4fb-11e9-95ae-75c0e34e34b9.png)

**Comment by Stephan-S** [comment]
Thanks, I will check it out as sonn as I can. Will take some time though. Busy week, sorry

**Comment by DeckerMMIV** [comment]
Perhaps my pull-request #736 can help a bit with that? - Though unfortunately not the top-bar, as that seems to be a reoccurring problem even in the default in-game menu.

I just tested, by manually editing the `Game.XML` file, as the in-game options won't allow me to choose such a width.
```
<?xml version="1.0" encoding="utf-8" standalone="no" ?>
<game>
    <language>0</language>
    <graphic>
        <display>
            <width>3840</width>    <------
            <height>1080</height>  <------
            <gamma>1</gamma>
            <fullscreen>false</fullscreen>
            <vsync adaptive="true">true</vsync>
            <userConfirmed>true</userConfirmed>
            <previousWidth>1366</previousWidth>
            <previousHeight>768</previousHeight>
            <scaling>1.000000</scaling>
            <brightness>1.000000</brightness>
        </display>
```
Result:
(32:9)
![fsScreen_aspect_ratio_32x9](https://user-images.githubusercontent.com/2834184/67895540-f5254680-fb5a-11e9-95a1-cfc982d5c8bd.png)

**Comment by Twetch** [comment]
Looks good to me :) thx guys good job!
![fsScreen_2019_10_31_19_18_48](https://user-images.githubusercontent.com/22034856/67974852-688a8f00-fc13-11e9-898b-fe605f066833.png)
