### ISSUE TITLE
Steigungen und Mauszeiger im Multiplayer

### ISSUE THREAD

**Issue by Onkel2000** [Stephan-S/FS19_AutoDrive#684]
Hey, haben mit der neusten Version von AD das Problem das die Fahrzeuge bei steigungen (z.b. auffahrt einer Brücke) hängen bleiben und nichts mehr machen.

Dann gibt es wieder das Problem im Multiplayer mit dem Mauszeiger der verschwindet, wenn der andere Spieler das Fahrzeug wechselt.

**Comment by Woife1** [comment]
poste mal ein Bild von der Auffahrt an der AD hängen bleibt
die Rampen zu den Deichen auf der NF Marsch funktionieren mittlerweile wunderbar ohne selbst Hand anzulegen und das sind schon rischtige Sprungschanzen

**Comment by Onkel2000** [comment]
Es ist auf der "Der pazifische Nordwesten" Map. Funktionierete sonst wunderbar.

![fsScreen_2019_10_22_19_41_01](https://user-images.githubusercontent.com/53871930/67313815-f07de400-f503-11e9-9138-b6cfc28a63a3.png)

**Comment by Iwan1803** [comment]
Auf der Nordfriesischen Marsch ist es bekannt, das so manche Auffahrt zu den Brücken oder Deichen für einige Trecker und bes. für LKW gerne mal zu einem Problem werden.
Gerade eben konnte bei mir ein Trecker mit vollbeladenem Hänger auf eine Brücke auffahren, wo ein LKW (vollbeladen) stehen blieb. Den LKW konnte ich dann von der Position aus manuell hochfahren, so das es wohl nicht an fehlenden PS liegen sollte.

**Comment by Woife1** [comment]
probier mal die "Kollisionerkennung" umzuschalten (kann helfen, muss aber nicht)

**Comment by Iwan1803** [comment]
Es liegt an der Kollisionserkennung.
Schalte ich sie aus, dann fährt der LKW in voller Geschwindigkeit über die Brücke und ebenso die Trecker.
Ist sie aktiv, bleibt der LKW stehen und die Trecker bremsen bis auf 5-8 km/h runter.

**Comment by Onkel2000** [comment]
Probiere ich nacher mal aus. Danke Euch beiden schonmal :)

**Comment by Onkel2000** [comment]
Okay, so funktioniert es. Wenn ich es aus machen, erkennt er dann auch keine anderen Fahrzeuge mehr?

**Comment by Woife1** [comment]
Andere Fahrzeuge von dir, CP oder AD gesteuert bzw parkende Fahrzeuge werden erkannt sowie einige andere Hindernisse
Der KI-Verkehr bei ausgeschaltener Kollisionserkennung auf jedenfall nicht (bin mir nicht sicher ob dieser überhaupt noch registriert wird)

**Comment by Iwan1803** [comment]
Meine Trecker rammten den KI-Fahrzeugen das Heck ein, wenn die Erkennung aus war.
Stephan weiß auf jeden Fall schon mal darüber Bescheid und wird nach einer Lösung schauen.

**Comment by Woife1** [comment]
meine fahren eher so auf die KI-Fahrzeuge auf das sie oben drauf stehen XDD

**Comment by Onkel2000** [comment]
> Andere Fahrzeuge von dir, CP oder AD gesteuert bzw parkende Fahrzeuge werden erkannt sowie einige andere Hindernisse
> Der KI-Verkehr bei ausgeschaltener Kollisionserkennung auf jedenfall nicht (bin mir nicht sicher ob dieser überhaupt noch registriert wird)

Alles klar, Danke. Spiele meistens eh mit KI aus. Dann ist da nur noch die Sache mit dem Mauszeiger. Wichtiger ist erstmal das er sich um die Claas Fahrzeuge kümmert.

**Comment by Stephan-S** [comment]
Ich komme leider nicht allzu schnell dazu. Bin die Woche unterwegs und am Wochenende auch schon einige Termine.
Ich kümmere mich so schnell wie möglich drum.
Das Class DLC muss ich mir allerdings auch erst besorgen. Vielleicht finde ich ja einen netten Giants Mitarbeiter. Zum Spielen komme ich ja eh schon lange selber nicht mehr :( Daher bin ich bei den DLCs meistens etwas zurückhaltend :D 

@Onkel2000 Ist das Mauszeigerproblem noch das alte und nie weg gewesen oder ist es wieder da, nach einem der letzten Updates? Ich dachte das hätte ich schon mal bearbeitet.

Beste Grüße,
Stephan

**Comment by Onkel2000** [comment]
> Ich komme leider nicht allzu schnell dazu. Bin die Woche unterwegs und am Wochenende auch schon einige Termine.
> Ich kümmere mich so schnell wie möglich drum.
> Das Class DLC muss ich mir allerdings auch erst besorgen. Vielleicht finde ich ja einen netten Giants Mitarbeiter. Zum Spielen komme ich ja eh schon lange selber nicht mehr :( Daher bin ich bei den DLCs meistens etwas zurückhaltend :D
> 
> @Onkel2000 Ist das Mauszeigerproblem noch das alte und nie weg gewesen oder ist es wieder da, nach einem der letzten Updates? Ich dachte das hätte ich schon mal bearbeitet.
> 
> Beste Grüße,
> Stephan

Es war mal weg, ist jetzt wieder da. Bearbeitet hattest du es auch schon mal.

**Comment by raxtor** [comment]
@Stephan-S Just a thought: Isnt possible add collision cube around NPC vehicles?

**Comment by Onkel2000** [comment]
Der Mauszeiger verschwindet nur wenn einer im Menü (shop, Spielmenü) ist, wenn jemand das Fahrzeug wechselt.

**Comment by Stephan-S** [comment]
Alles klar. Die Info hilft mir sicherlich wenn ich dazu komme danach zu schauen. Danke!
