### ISSUE TITLE
Unloader crashing or blocking harvester

### ISSUE THREAD

**Issue by betjal** [Stephan-S/FS19_AutoDrive#687]
Hi there,

another problem: If the harvester is full and the tractor must empty it on the grain, the tractor remains on the corn and is blocking the harvester on the next line.

Sometimes it seems as the tractor does not recognize the harvester as a vehicle and collides with it while driving.

Tested with New Holland harvester and some John Deere/Fendt tractors (no modded ones).

**Comment by Iwan1803** [comment]
Check if you set the unloader to park on the field.

**Comment by wallsingham** [comment]
Maybe Stefan can fix that. If "park in the field" is activated, the unloader parks (also) in the fruit, if he allready is there. If possible, the unlaoder should not park in the fruit after unloading.

**Comment by Stephan-S** [comment]
This should all be working a lot smoother with the current source files.
Has anyone tried the updates since last week and can confirm this?

Especially park on field should work as expected now
