### ISSUE TITLE
Suggestion for auto connect - two way line green/purple

### ISSUE THREAD

**Issue by bojanh66** [Stephan-S/FS19_AutoDrive#689]
Take a look at video: https://youtu.be/s4XXnb8PkR0
I choosed purple recording (two way line), but it always create green line and i have to return and make it purple with reconnecting, which is annoying.

Is it possible to improve this to become purple line when we start recording (purple button rec) ??

**Comment by Ontragon** [comment]
the problem ist that recording start with a green line and then with purple.
only better way is 2 recoding buttons for each line.

**Comment by bojanh66** [comment]
Yes, i dont want it to start with green line, but with purple line.
Is it possible to fix this ?

**Comment by Woife1** [comment]
you can direct make a purple line after start recording
just connect your startpont with the point you come from and then drive your course 

ok it is just 2 clicks more but it is possible ;)

**Comment by bojanh66** [comment]
I know i can do that, but i am asking, is it possible to start recording with purple line instead a green line :)
It would make things much easier when reconnecting some routes, so i dont have to come back just for 1 line.

**Comment by Stephan-S** [comment]
I agree. If you directly select Dual way recording, I could adapt the Auto Connect Route to also bei Dual. 
I'll add this to my todo list

**Comment by Stephan-S** [comment]
I was also thinking about moving the two way recording to the secondary function. But I am not sure everyone is yet aware of these functions.
Oh and you can also use the middle mouse button for this. Not only right-click. So this should not interfere with CP at all

**Comment by TobiHH78** [comment]
I guess whatever key you will use, it can be changed  in the keybindings, so everybody can put it on the key he prefers.
