### ISSUE TITLE
unload combine mode is it just wheat and barley

### ISSUE THREAD

**Issue by ploughedfieldman123** [Stephan-S/FS19_AutoDrive#69]
in combine unload mode dont it work on other crops like canola as I have tractor in field with combine at 100% with canola but nothing happens

**Comment by Stephan-S** [comment]
It should not depend on the fruit type. Are you sure there is nothing else goign wrong? Any log errors?

**Comment by ploughedfieldman123** [comment]
> It should not depend on the fruit type. Are you sure there is nothing else goign wrong? Any log errors?

Well I will try once more, and try to send a screenshot.  Plus i will also remove all mods except ones I am using also will send log

**Comment by Stephan-S** [comment]
Should be fixed with latest release (was not fruit type related though)
