### ISSUE TITLE
Using the loop button

### ISSUE THREAD

**Issue by Highlander1965** [Stephan-S/FS19_AutoDrive#690]
Can someone please explain what the loop button is for and how it is used?

**Comment by pcdoc69** [comment]
By loop do you mean the one that looks like a number 8 on its side? It means infinity ie it just keeps going. Click it to change number of journeys.

**Comment by Highlander1965** [comment]
Yes that's the one, do you mean for example if I want to collect lime from
a location and deliver it to my farm I can you this to collect 2 or 3 times
from lime station

**Comment by pcdoc69** [comment]
Yes if you have a route set. For instance, if I want to sell soyabean to a sellpoint I set AD to load and deliver, then decide how many loads. If its 5 loads I click the "loop" button until it says 5 start it off and it will deliver 5 loads providing there is enough soyabean or whatever you set it for to do so.

**Comment by Highlander1965** [comment]
That's perfect thank you so much for your help and explaining the procedure
