### ISSUE TITLE
Error: Running LUA method 'update

### ISSUE THREAD

**Issue by Highlander1965** [Stephan-S/FS19_AutoDrive#692]
Since version 1.0.6.4 my course for my map is haveing the following error and crashes the game 

2019-10-25 19:46 Error: Running LUA method 'update'.
2019-10-25 19:46 C:/Users/macmi/Documents/My Games/FarmingSimulator2019/mods/FS19_AutoDrive/scripts/AutoDriveTrailerUtil.lua:52: attempt to index field 'providedFillTypes' (a nil value)

It happens when I'm collecting lime from the sale point just off to the right in the attached picture before it reaches the sale point the machines cut back on the other course.
![AD error](https://user-images.githubusercontent.com/56995066/67597345-de4db100-f762-11e9-8819-3f64da2a52cd.png)

**Comment by Woife1** [comment]
did you recalculate the routes?

**Comment by Highlander1965** [comment]
Yes I have recalculated the course. When I use it with version 1.0.6.3
everything works that's what is puzzling. I'm wondering is it something to
do with new menu that the lime is not been found when selecting it from the
menu

**Comment by andejx** [comment]
It has something to do with these changes : https://github.com/Stephan-S/FS19_AutoDrive/commit/aaf53e41a8bc4ab7d187c0c8efecb8febd6610ad

If i revert those changes myself by editing the lua file then i no longer get that error.

Think its something to do with modded maps sell points or modded silos. I don't get any errors on vanilla stuff.

**Comment by Highlander1965** [comment]
Thanks for the information unfortunately I don't understand Lua code so I
will have to wait till next version comes out to see if that one works for
me, I will keep using version 1.0.6.3 for the moment. Thanks again
