### ISSUE TITLE
Abladen mit HKD 302 im Multiplayer

### ISSUE THREAD

**Issue by Onkel2000** [Stephan-S/FS19_AutoDrive#693]
Nabend, 

Mir ist aufgefallen wenn ein Abfahrer mit dem Anhänger HKD/TKD 302 im Multiplayer bei meinem Mitspieler nicht immer funktioniert.

![fsScreen_2019_10_26_00_07_58](https://user-images.githubusercontent.com/53871930/67608039-d9025d80-f786-11e9-8b1c-8c177c9a32f7.png)

Die Log sagt : 2019-10-26 00:20 Validity check failed in TransformGroup_setRotation:  
2019-10-26 00:20   ..\..\..\src\engine\app\ReflectionAndScriptBinding.cpp (6382): MathUtil::isFinite(pArgs->arg[0].f)

Bis an diese stelle fährt er, bei mir (als Host) läd er ab, machmal auch nicht, bei anderen aber nicht ( oder nur ganz selten). Vielleicht habt ihr ja einen Rat für mich. Es ist die aktuellste Version.

**Comment by Stephan-S** [comment]
Könnte an der automatischen Auswahl der Abkippseite liegen. Da fehlt vielleicht noch ein Event um das an die Spieler zu verteilen. Ich schaus mir mal an.
Danke für die Meldung!
