### ISSUE TITLE
DLC Claas Harvester don't call AutoDrive tractor

### ISSUE THREAD

**Issue by fcelsa** [Stephan-S/FS19_AutoDrive#694]
When DLC harvester on fields don't call the AutoDrive driver for discharge in any conditions.
Except for the bonus Mega 108, that appear to be ok.

**Comment by Woife1** [comment]
you need the fix that Stephan made yesterday
than it should work

**Comment by Dzi4d3k** [comment]
Yes, but, there is no 1.0.6.6 release, so it have to be cerated manually form Git repository.

**Comment by geo-luchs** [comment]
1.0.6.6 is now released and available

**Comment by Dzi4d3k** [comment]
Having this repository, as watched, helps being up to date :)
