### ISSUE TITLE
Autodrive Problem

### ISSUE THREAD

**Issue by joneay** [Stephan-S/FS19_AutoDrive#696]
Hi
ich hab die aktuelle Version drauf und versuche die Multimap einzufahren.
Wenn ich neue Punkte setze, werden diese gespeichert (kann diese über die Pfeiltaste auswählen) diese tauchen aber nicht im pulldown menu auf.
Ferner geht die Zuweisung in Ordnern nicht, obwohl dieses im Menu aktiviert ist.
Wenn ich vorgefertigte config lade, funktioniert alles wie es soll.
Wollte aber meine Routen selbst einfahren und bekomme dies irgendwie nicht gebacken.
hoffe, es gibt Hilfe hierfür
Gruss
Jo

**Comment by Woife1** [comment]
die "Punkte" die du auf den Boden malst sind nur für die Wegstrecken Berechnung
für das Menü musst du Zielpunkte festlegen (über das Icon das wie die POI's in Google aussehen (Wassertropfen falschherum)) 
das beste ist du schaust dir auf Youtube die Tutorials von Cairo Amun an die helfen aufjedenfall

**Comment by Huskiel** [comment]
> Wenn ich neue Punkte setze, werden diese gespeichert (kann diese über die Pfeiltaste auswählen) diese tauchen aber nicht im pulldown menu auf.

> 

hast du mal nach oben gescrollt?


> Ferner geht die Zuweisung in Ordnern nicht, obwohl dieses im Menu aktiviert ist.

> 

hast du den Zielpunkt im oberen pulldown menü ausgewählt und bei dem gewünschten Ordner auf den Pfeil nach rechts geklickt?

**Comment by RalfGorden** [comment]
https://www.youtube.com/channel/UCqQhmo7yyaKDsXQDLgNV39A
da kannste viel lernen hab ich auch gemacht

**Comment by Stephan-S** [comment]
Ich mache hier mal zu. Wenn es Fragen gibt die nicht durch Youtube Tutorials und Lesen des Wikis beantwortet werden können, einfach wieder aufmachen. Danke
