### ISSUE TITLE
Neuberechnung der Kurse - Geschwindigkeit

### ISSUE THREAD

**Issue by kleba78** [Stephan-S/FS19_AutoDrive#697]
Hey, 

habe mir mal deine Berechnung der Wegstrecken angesehen und ohne das ich Wissen vorteuschen möchte, frage ich mich ob es notwendig ist, immer alle Wegpunkte neu zu berechnen? Würde es nicht ausreichen "neue" zu merken und diese in das Netz einzurechnen?

Gruß 
PS: Wie könnte man im SP eine 4fach Karte ohne AD spielen - eigentlich unvorstellbar.

**Comment by Woife1** [comment]
Es wird sehr komplex die Programmierung so zu schreiben das nur neue Punkte berechnet werden und ob sich die Berechnungsgeschwindigkeit dadurch wirklich senken lässt ist fraglich da jeder bestehende Kurs ja gecheckt werden muss

ohne AD isses im SP mitlerweile unmöglich (oder wir zu faul ;) )

**Comment by Iwan1803** [comment]
Nein, es würde nicht ausreichen, sich nur "neue" zu merken, sondern jede Änderung und das in einer chronologischen Reihenfolge. Es könnte ja passieren, das 1 Wegpunkt lösche und sofort an der exakt gleichen Stelle einen neue setze.
Würde Multi-Threading (optimal) unterstützt, dann wären die Berechnungen kein wirkliches Problem (solange man keine Kartoffelkiste besitzt).

**Comment by geo-luchs** [comment]
ich sag mir immer: lieber mal konzentriert an der Überarbeitung des Netzes arbeiten, auch mit dem Course Editor, um z.B. überflüssige (alleinstehende) Wegpunkte zu löschen.
Dann im Spiel einmal auf berechnen klicken, und kurz nen Kaffee holen, oder aufs Örtchen gehen.

Ich denke, das ist eine Funktion, die man nicht zwingend ständig durchführen muss.
Stephan hat noch viele offene Issues, die das tägliche Bespielen betrifft.

**Comment by Stephan-S** [comment]
@kleba78 
Eine neue Verbindunng hinzufügen kann potenziell alle Kurse verändern wenn dadurch eine neue 'Abkürzung' entsteht.
Also komm ich nicht drum herum nochmal alle Pfade zu prüfen.

Es wäre natürlich kein großer Aufwand sich nur die neuen Punkte/Ziele zu merken aber es bringt leider nichts.

Zugrunde liegt der Dijkstra-Algorithmus, falls du dich mal selber schlau machen möchtest -)

Ich mache hier aber mal zu. Falls du neue Erkenntnisse für mich hast, fühl dich frei wieder auf zu machen.

Beste Grüße,
Stephan
