### ISSUE TITLE
AD-Fahrzeug Blockade, möglicher Lösungsversuch ganz hinten auf ToDo-Liste

### ISSUE THREAD

**Issue by haamic** [Stephan-S/FS19_AutoDrive#699]
Hallo Stephan
hier ein Problemchen, welches evtl. mal auf die To-Do Liste könnte, ganz ganz weit hinten.
Bei mehreren Abfahrern auf einem Feld kommt es bei mir häufiger vor, das sich Abfahrer selber blockieren, weil sie entweder zu nah aneinander vorbei fahren wollen oder direkt aufeinander zu fuhren und sich nun frontal gegenüber stehen. 
Leider gibt es für so einen Fall keine Hinweismeldung. Man wundert sich nur, das der Drescher ewig auf den Abfahrer wartet und muss das Problem erstmal finden. Gleiches passiert, wenn der CP-Drescher mal den Abfahrer über den Haufen fährt, ihn sogar auf dem Schneidwerk mitnimmt, oder ähnliche Konstellationen einer Blockade des AD-Fahrers. Zwar kommt evtl von CP eine Blockiert-Meldung für den Drescher, woran man sieht das eingegriffen werden muss, manchmal kommt auch keine Meldung.
Ist es möglich, irgendwann, dafür mal eine Lösung zu integrieren? Vielleicht eine Meldung, wenn sich Fahrzeuge mit zu sehr abweichenden Fahrrichtungen zu nahe kommen ? 
Mir kam bei dem Problem, ein Spielzeug von früher in den Sinn. Ein selbstfahrendes Auto fuhr gegen ein Hindernis und fuhr dann durch einen Lenkmechanismus seitlich weg, entkam somit dem Hindernis. 
Oder ein Staubsaugroboter. Er fährt irgendwo dagegen, befreit sich selber wieder.
Luxus wäre diese Art "Intelligenz" den Fahrzeugen zu geben.
z.B. Wenn kein Weiterkommen möglich, das AD ein Fahrzeug, ein Stück zurückfährt, wie nach einem Abtankvorgang. 
Dann, je nachdem wo mehr Platz (kein Hindernis) ist, in diese Richtung einlenkt, wegfährt und evtl. so der Blockade entkommt.
Weiss nicht, ob es anderen Nutzern auch manchmal so geht und sich so eine "Problembehebung" in ferner Zukunft wünschen.
Wenn es gar nicht möglich ist, weder die 
"Achtung, ich komm hier nicht weiter und muss ausweichen-Intelligenz" der Fahrzeuge, 
noch eine Meldung über eine Blockade, dann ist das auch kein Problem. 
Muss man, oder nur ich, damit leben.
Toller Mod, Stephan. Danke für dein schnelles Beheben von neu auftretenden Problemen, trotzdem du sehr beschäftigt bist. Was Du als einzelner dafür leistest ich schon beachtlich. 
Leider scheinen wohl so manche Nutzer zu denken, hinter dem Mod steht ein grosses Team und nicht nur Du allein.
Schönen Sonntag
Gruss Micha

**Comment by FarmerLupo** [comment]
Hallo Micha,
du sprichst mir aus der Seele mit diesem Anliegen!

@Stephan:
Ich mach mal einen zweiten Strich auf die Liste der Interessenten ;-)

**Comment by Iwan1803** [comment]
Ein Großteil der Probleme liegt an nicht ganz sauberen Kursen, was man ja selber beheben kann. Ich nutze z.Bsp. die Kurse von Holger auf der Nordfriesischen Marsch (4-fach Map) und muss da an einigen Stellen auch nachbessern. Die Ein- & Ausfahrten zu und von Feldern sind fast alle so angelegt, das man mit 2 Abfahrern nicht arbeiten kann oder die Abfahrer teilweise auf der Straße stehen.
Gestern hatte ich es einige male, das der Abfahrer (AD-gesteuert) auf dem Schneidwerk vom Drescher (CP-gesteuert) "mitgefahren" ist, aber es gar keine Meldung dazu gab. Vermutlich liegt es dann daran, das beide Fahrzeuge sich ja eigentlich noch bewegen, auch wenn sie sich nicht mehr wirklich von der Stelle bewegen (Reifen drehen durch und sie bewegen sich gefühlt 1-2 Centimeter pro Minute weiter).
Natürlich wäre es schön, wenn man eine Info erhält, wenn sich irgendwo Fahrzeuge blockieren. Ich weiß nur nicht, inwieweit es Trigger im Spiel selber gibt, auf die man dann mit Meldungen reagieren kann oder inwieweit die Mods die Fahrzeuge auf Probleme abfragen können.

**Comment by VatriXxX** [comment]
Gut das es jemand anspricht, es ist mir auch schon des öfteren aufgefallen.
Da die selber (ohne vorgegebenen Kurs) zum Drescher fahren, fahren die dann echt öfters ineinander.
Wäre auch an einer Lösung interessiert.

**Comment by geo-luchs** [comment]
Wie ist das eigentlich mit 2 abfahren auf einem Feld?
Wird erst einer komplett gefüllt, bevor der 2. Abfahrer gerufen wird? 
Der 2. Muss ja erst aktiv werden wenn der 1. Gerade die Ladung weg bringt? 
Ich hab es bisher noch nicht versucht.
Auf was müsste ich achten? 
Beide warten ja irgendwo am Feldrand. Der 1. Fährt dann zum Drescher,  der 2. Rückt auf Haltepunkt vor.
Wie geht es dann weiter? Der 1. Hat noch Platz für 2 Drescherladungen.

Stellt der sich hinter Abfahrer 2?
Oder muss ich den 1. Dann zwingend auf dem Feld parken lassen?
Hab das auch im Wiki so genau nicht nachlesen können oder einfach nur nicht verstanden.

**Comment by haamic** [comment]
Also ich habe große Felder und ernte mit 4 Dreschern und 4 Abfahrern auf dem Feld. Haben alle den selben Startpunkt bzw.  Ziel im Drescher. 
Die Abfahrer fahren eigentlich überall hin, wo abgetankt werden soll. Geht manchmal schon bisschen drunter und drüber aber auch lange Zeit mal gut ohne Probleme. Und da kommt es halt auch vor, das sich die Abfahrer im Wege stehen. Darum die bitte hier an Stephan, so eine Blockade evtl. Automatisch lösen zu können. 
Du kannst auch den abfahren getrennte wartepunkte am Feld geben und den dreschern entsprechend auch, aber da wartet der Drescher manchmal eben lange, wenn der Abfahrer gerade zum Silo unterwegs ist. Hatte ich auch mal getestet, aber es geht bei mir auch anders, mit der Methode  alle auf ein Ziel und gucken wie sie übers Feld wuseln ;-)
Ich empfinde die Wartezeiten nicht so gravierend, da diese minimiert sind, auf den Weg vom einem leeren Drescher zum nächsten vollen. Muss halt jeder für sich rausfinden, was am besten ist.

**Comment by haamic** [comment]
Eine Reihenfolge des Abtankens gibt es nicht bei mir. Wer zuerst da ist bekommt die Ladung. Da ich die Drescher im Verband fahren lasse mit genug automatischem Abstand und die Feldkurse immer als "Spirale" im Uhrzeigersinn (da Drescher ja links abladen) mache, können die Abfahrer auch im Feld parken ohne die anderen Drescher zu behindern. Sie fahren ja dann aber eh immer weiter dem Drescher hinterher, wenn "folgen" aktiv ist.

**Comment by Stephan-S** [comment]
Hallo, da wir gerade die neue restrukturierte Version von AutoDrive released haben, können wir leider keine Bugs und Issues die sich noch auf die alte Codebasis beziehen mehr bearbeiten.
Wenn das Problem bzw. dein Anliegen in der atkuellen Version weiterhin besteht, mache doch bitte ein neues Issue mit allen benötigten Informationen auf.
Oder melde dich bei kleineren Themen und Fragen auch gerne direkt im Discord:
https://discord.gg/sUQtKhB

Vielen Dank für dein Verständniss und ich hoffe du hast weiterhin Spaß am AutoDrive Mod :-)

Und hier noch ein Link zur aktuellen Version:
https://github.com/Stephan-S/FS19_AutoDrive/releases/tag/1.1.0.0
