### ISSUE TITLE
config.xml save path

### ISSUE THREAD

**Issue by Anonymous-any** [Stephan-S/FS19_AutoDrive#7]
Hi balu maestro^^, I confirm when import folder is created and then after saving the game, AD file_config.xml disappear from savegame directory (GIANT system) but it is updated/writed into AD import folder.
Delete the import folder then AD file_config.xml is write back into savegame directory.

Regard

**Comment by Stephan-S** [comment]
Hey, thanks again. Porblem should be fixed

**Comment by Anonymous-any** [comment]
Confirmed :)
