### ISSUE TITLE
Meldungen von AutoDrive

### ISSUE THREAD

**Issue by siggiblue** [Stephan-S/FS19_AutoDrive#70]
Hallo Stephan,
aus Versehen habe ich gestern den bisherigen Thread geschlossen. Deswegen jetzt hier ein neuer.

Zur Farbe der Meldungen: gelb oder rot wäre gut und dann größer als zur Zeit. Die Farbe weiß geht unter dass kennen wir ja vom Standard schon (Z.B beim Preis etc. oben rechts)
Die Position unten mittig ist nicht schlecht.
Ich habe aber noch etwas anderes festgestellt zum Thema Laden und Verkaufen:
Das Silo war gefüllt mit 185.000 Ltr. Sonnenblumen. Zum Verkauf wurde ein Hänger mit einer Kapazität von 80.000 Ltr. benutzt. Er hat also 2 Touren super erledigt. Beim dritten Mal fährt er wieder das Silo an und lädt den Rest, also 25.000 Ltr. und dann bleibt es stehen und wartet offenbar bis er wieder voll ist. Geht aber nicht, da das Silo für diese Frucht leer ist. Kann man das programtechnisch abfragen was von der gewählten Frucht noch da ist und wenn diese leer ist auch mit einem nicht vollen Hänger losfahren und einen weiteren Durchlauf verhindern ? Oder man schafft die Möglichkeit das man, sowie bei CP, die Anzahl Durchläufe vorgibt. Das kann man sich ja vorher ausrechnen.
Gruß
SiggiBlue

**Comment by Stephan-S** [comment]
Hallo, die Farben werde ich vielleicht übernehmen. Klingt nicht schlecht.
Bezüglich des Abfahrers: Geh mal in die Optionen (L-ctrl + l-alt + numpad 0), da kannst du einstellen, ob er bei leerem Silo warten oder weiterfahren soll.

**Comment by siggiblue** [comment]
super, vielen Dank für die Info

**Comment by siggiblue** [comment]
vielen Dank für jetzt super lesbaren Meldungen.
Gibts in der Version 1.0.1.4 sonst noch was neues ?

Angenehme Ostertage
