### ISSUE TITLE
V1.0.6.5 - ohne Export Button 

### ISSUE THREAD

**Issue by Corona01** [Stephan-S/FS19_AutoDrive#700]
Hallo Stephan,
Hallo Community,
bei der V1.0.6.5 ist der Export Button nicht mehr vorhanden.
Daraus ergibt sich das ich das aktuelle AD Streckennetz das ich eingefahren habe nur über das Savegame gespeichert bekomme.
Oder gibt es noch eine andere Möglichkeit ?

**Comment by Onkel2000** [comment]
Mit strg + alt + 2 (numpad) sollte es funktionieren. Damit sollte dein Netzwerk im AD Export Ordner erscheinen.

**Comment by worker2419** [comment]
@Corona01 schau bitte einmal in  #667 Da ist der gesamte Prozess mit Export, Buttons, Ordner 
 und Import beschrieben.

**Comment by Corona01** [comment]
Danke für eure Antorten !!
Hat mit "Strg (links) + Alt (links) + 2 (Numpad) geklappt.

**Comment by worker2419** [comment]
Supper dann mach bitte zu hier
