### ISSUE TITLE
Zuckerrohrtransporter abladen funktioniert nicht

### ISSUE THREAD

**Issue by VatriXxX** [Stephan-S/FS19_AutoDrive#701]
Mir ist aufgefallen, dass er beim eigentlichen Abladen eines gutes aus dem Zuckerrohrtransporters, in meinen Fall der MF3012, er es nicht tut.
Er fährt zu den angegebenen Ablade Ort, hält dort an und fährt kurze Zeit später einfach weiter mit dem vollen Transporter.

Liegt es vielleicht daran, das dieser nicht gekippt wird (über der Taste "I"), sondern über die Klappe 2 (Taste "K" öffnen, Taste "M" schließen")?

**Comment by Stephan-S** [comment]
Ja, aktuell wird nur Schüttgut unterstützt

**Comment by Stephan-S** [comment]
Hallo, da wir gerade die neue restrukturierte Version von AutoDrive released haben, können wir leider keine Bugs und Issues die sich noch auf die alte Codebasis beziehen mehr bearbeiten.
Wenn das Problem bzw. dein Anliegen in der atkuellen Version weiterhin besteht, mache doch bitte ein neues Issue mit allen benötigten Informationen auf.
Oder melde dich bei kleineren Themen und Fragen auch gerne direkt im Discord:
https://discord.gg/sUQtKhB

Vielen Dank für dein Verständniss und ich hoffe du hast weiterhin Spaß am AutoDrive Mod :-)

Und hier noch ein Link zur aktuellen Version:
https://github.com/Stephan-S/FS19_AutoDrive/releases/tag/1.1.0.0
