### ISSUE TITLE
AD / HUD Probleme mit eingeschaltetem Controller

### ISSUE THREAD

**Issue by Evilbolzen** [Stephan-S/FS19_AutoDrive#702]
Hatte bis jetzt nichts in den Issues gelesen daher dachte ich mir ich schreibe das mal hier rein.

Sobald ich einen Controller aktiv verbunden habe (Bluetooth/Kabel, Dualshock 4 mit Inputmapper oder Xbox One S Controller) scheint AD nicht damit klar zu kommen. Das HUD zeigt größtenteils nichts an (keine Ziele, Kurse etc.) und reagiert auch nicht immer auf Eingabe mit der Maus oder auf die meisten Tastenbefehle. Ich kann lediglich AD einschalten, aber z.B. nicht das Ziel sehen/festlegen/ändern.

Auch die direkten Tastenbefehle funktionieren nur bedingt, ich komme in das Einstellungsmenü, aber das HUD selbst kann ich nicht aufrufen wenn ich es mal geschlossen hatte. Auch Zielort-Änderung geht nicht.

Sobald der Controller ausgeschaltet ist/nicht mehr aktiv verbunden ist funktionieren Tastenbefehle/Mausbefehle und es wird auch alles korrekt angezeigt. Hatte das zunächst auf einen Bug in der ("alten") Modhub Version abgetan, aber auch in der aktuellsten Version hier ist dieses Phänomen zu sehen.
Ist das Problem soweit bekannt oder habe ich irgendwas übersehen/falsch gemacht? Habe den LS einmal sauber aufgesetzt und nur AD als Mod verwendet und die Inputbinding für meinen Controller Ingame neu erstellt, das Problem bleibt bestehen.

Als Bild mal beigefügt wie das Menü bei eingeschaltetem Controller bei mir aussieht
![20191027171613_1](https://user-images.githubusercontent.com/57069516/67637768-19282400-f8de-11e9-8e48-513f8ec0c6f0.jpg)

**Comment by Stephan-S** [comment]
Hey,
das war mir so noch nicht bekannt, nein.

Da sicherlich viele Spieler einen Controller und/oder Lenkrad nutzen ist das sehr seltsam.

Kannst du mir mal deine log dazu posten? Sieht eher aus als würde hier Fehler entstehen.

**Comment by Evilbolzen** [comment]
[log.txt](https://github.com/Stephan-S/FS19_AutoDrive/files/3776234/log.txt)

Hier die log Datei, nicht wundern über die Meldung zum Mod "narf", das ist ein Subverzeichnis wo ich meine Mods zwischengespeichert habe damit er sie nicht aufrufen kann.

Die kurzfristig angelegte Input-Binding hatte ich nun leider nicht mehr parat sondern nur die dauergenutzte mit allen Mods drin. Die Log entstand wie folgt:

1. Neuen Spielstand mit Controller angelegt, als Mod nur Autodrive ausgewählt auf Fellsbrunn
2. In ein Fahrzeug gesprungen, versucht mit LAlt+Num0 Hud aufzurufen -> geht nicht
3. Controller aus, Hud aufgerufen und bei den Zielen im Dropdown 3 Einträge vorgefunden
4. Controller wieder an, mit der Maus ein anderes Ziel ausgewählt, das zuvor ausgewählte Ziel verschwindet aus der Liste (auch nicht im blanken anklickbar)
5. Nachdem alle Ziele weg waren aktives Spiel über Menü beendet, Hauptprozess dann (aus Gewohnheit) mit Alt+F4 beendet

**Comment by Stephan-S** [comment]
Danke für die Beschreibung, Ich bin leider trotzdem noch nicht sicher woran es liegt aber ich schreibe es mir auf die Todo-Liste das schon mal selber mit einem Controller zu testen.

Welchen Controller nutzt du?

**Comment by Evilbolzen** [comment]
Sowohl Xbox One Controller (Bluetooth / wired) als auch Dualshock4 (Bluetooth mit Software Input Mapper)

**Comment by Stephan-S** [comment]
Ich habe meinen XBox Controller mal wieder angeschlossen und kann hier keinerlei Probleme feststellen.

Vielleicht ist es ja wirklich etwas mit dem InputMapping und/oder einem anderen Mod den du im Modordner liegen hast, der ja trotzdem Einfluss auf Buttonbelegung etc. hat.

Da auch keinerlei Fehlermeldung kommt ist das doch etwas verwunderlich.
Schau dir mal insbesondere an ob es eine Doppelbelegung beim Hud öffnen oder so gibt.

Nochmal alle Mods aus dem Modordner raus, InputBinding Datei mal sichern und entfernen und dann neustarten.

Oder hat sich das Problem zufällig in der Zwischenzeit erledigt?

**Comment by Stephan-S** [comment]
Da hier keine Rückmeldung mehr kam und ich das Problem nich nachstellen kann, mache ich hier mal zu.
Bitte wieder öffnen, falls es noch besteht bzw. es neue Infos gibt!

**Comment by Evilbolzen** [comment]
Sry dass ich mich jetzt erst wieder melde, hatte mit einer großen Prüfung zu kämpfen aber bin nun wieder da.

Habe die Input Binding gelöscht, alle Mods bis auf AD rausgeschmissen und dann mal ausprobiert, das Ergebnis ist unverändert geblieben. **Allerdings:** Ich habe festgestellt dass nach löschen des InputDevices Verzeichnis' sich das ganze anders verhält. Es bleibt (bei mir)leider noch immer dabei dass AD nicht funktionieren will mit Controller, is dieser disconnected funktioniert es. 

Habe die Log eines neuen Spielstands angehangen, Inputbinding war gelöscht, alles was ich gemacht hab war in ein Fahrzeug und dann versucht das AD Hud anzeigen zu lassen. Geht nicht also Controller aus und erneut probiert: geht.

Ich habe so jetzt noch keinen Schimmer was das Problem ist, ich werde aber mal in einer VM mit sauberem OS den LS neu installieren und schauen was passiert, denn ich habe den Verdacht es liegt daran dass ich andere Controller an diesem Rechner verwendet habe (Dualshock4 mit Inputmapper und einen selbstgebauten mit generischen HID Driver)

[log.txt](https://github.com/Stephan-S/FS19_AutoDrive/files/3848172/log.txt)
