### ISSUE TITLE
Wiki is now live

### ISSUE THREAD

**Issue by Stephan-S** [Stephan-S/FS19_AutoDrive#703]
I started typing a Wiki for AutoDrive.
It is not finished but it already contains a lot of information for new users.

Here is the direct link to the wiki: https://github.com/Stephan-S/FS19_AutoDrive/wiki

So this should be the first starting point for before opening a new issue.

To all active users here in this repository: Thank you for everything and I really appreciate everyone who helps out others here and thereby helps me focusing on working the issues and adding new features. I still read every issue and every post because I reveive an email and I am really happy to see you guys responding and helping out! Thank you!

So if new users post something that is already contained in the wiki, please help direct them there. Thank you :-)

I will add to the wiki whenever I can.

**Comment by worker2419** [comment]
Hallo @Stephan-S,
thank you again for your work. 
wouldn't it be easier if the following information were listed with the error?
Basic information for open an Issue
Map Name and Version
AD version
Which source code (Releases or FS19_Autodrive)
Vehicles which are used
maybe as a page in the Wiki

**Comment by Iwan1803** [comment]
That's really great @Stephan-S !
Maybe there should be a also german part as not all users are able to talk english or are able to use a translator.
if I can help you with something, then just write me

**Comment by Andii1980** [comment]
Hallo Stephan-S,

wird es von der wiki auch eine Deutsche version geben?

**Comment by Justice-Molton** [comment]
Man schreibt es ja in Englisch, da es die Weltsprache ist. So muss man nicht alles in Sprach X übersetzten. Die Arbeit die er da macht, macht er kostenlos. So ein bisschen Anstrengung von der User Seite kann man da schon erwarten.

**Comment by Andii1980** [comment]
> Man schreibt es ja in Englisch, da es die Weltsprache ist. So muss man nicht alles in Sprach X übersetzten. Die Arbeit die er da macht, macht er kostenlos. So ein bisschen Anstrengung von der User Seite kann man da schon erwarten.

Ich weiß das er es kostenlos macht und keine Bezahlung dafür bekommt.
Es war ja auch nur eine allgemeine Frage von mir gewesen.

**Comment by geo-luchs** [comment]
Hi Stephan

thanks a lot for your work.

**Comment by Martinnygaard** [comment]
Thanks a lot for your work.
You are doing such a bog work, developing and debugging this script all by yourself. 
When players (my self included) report a bug, we have a fix in a very short time - while you at the same time add a lot of new features - some also suggested by us.

The feeling of getting heard, and actions is taken from the issue list here at github inspires, and it motivates to help you as much as possible. Mainly by playing with your awesome mod, and give you feedback ;-)

Thanks!

**Comment by Soydab** [comment]
Hello @Stephan-S 

I'm a player of FS 19 and user (since yesterday) of your mod but I'm also a DevOps Engineer with a good background of developments. I have some personal projects too. Ten years ago, I've made some bots for known MMORPG (pathfinding, IA, ...). 

I noticed some problems/bugs in your mod (and it's totally normal), and I was wondering if it was possible to help you. I already checked the code, I'm trying to understand it, and instead of doing the modifications on my side only, I would prefer to work with you and share with your community.

Sorry, I know it's not the subject, but I didn't know where to contact you.
I would like to exchange with you about AutoDrive. 

You can contact me : dubois.arsene1@gmail.com

Bye ;)

**Comment by Stephan-S** [comment]
Hello @Soydab 
you are more than welcome to participate here :-)

If you see anything that you want to improve in the code base, then create the fix and upload a pull request.
Then I and/or @TyKonKet will look over it and if it works and is something we like, it will be merged into the repository.

If you want to become a 'member' of the team, this would be the way to go :-)

If you have any question about the code that you can't seem to answer via Wiki, closed/open issues, I am always available to explain my code.

Are you interested in a certain area of the mod? Or just general bugs?

**Comment by TyKonKet** [comment]
@Soydab I'm new in this project but I'll do my best to help you understand what I have already understood :D

**Comment by Soydab** [comment]
Firstly, I would prefer to fix some bugs maybe, but after, improve or develop some new features, yes ;)

Do you have a Discord or something like that @TyKonKet @Stephan-S ?

**Comment by Martinnygaard** [comment]
If there is a discord, i would very much like to join!
I've been trying to understand the script, and would very much like to help. 
However, i am still in a very steep learning curve.

**Comment by Stephan-S** [comment]
I opened a discord server.
Feel free to join.
But I am away for work this week, so I won't be able to join voice chat until the weekend :-)

https://discord.gg/sUQtKhB

**Comment by Soydab** [comment]
No problem, text messages are good enough for the moment. I'll join the server after work ;)

**Comment by TyKonKet** [comment]
I think we can close this issue since the wiki is now moved on in game helpline
