### ISSUE TITLE
Two way recording button is missing

### ISSUE THREAD

**Issue by bojanh66** [Stephan-S/FS19_AutoDrive#704]
With newest release, we can only record 1 way line (green color), but not 2 way line (purple)

Edit: nevermind, purple button is actually no longer on left mouse click, but instead on middle and right click :)

**Comment by geo-luchs** [comment]
Hi Stephan

in this case, we are now using the right mouse button on the record button for 2-way purple line, would be it good /possible, to use right mouse button also on the button for create a connection between 2 way points for purple connection.
Currently only left mouse button is possible, but creates a green line.

**Comment by Stephan-S** [comment]
@geo-luchs Good idea!
I think I will add the secondary function to create the reverse direction. So from yellow line to red line.
This is adding more options and creating a dual way path is as simple as clicking the button twice.
