### ISSUE TITLE
Support for localized destination names

### ISSUE THREAD

**Issue by Dzi4d3k** [Stephan-S/FS19_AutoDrive#705]
Currently there is only one name for destination entered during creation.
It can be renamed (translated) by edit, but it has to be done by each player himself.

How about adding low priority goal to add localized destinations. Default maps are good example of one that have localized names.

**Comment by TyKonKet** [comment]
> It can be renamed (translated) by edit, but it has to be done by each player himself.

@Dzi4d3k do you mean in MP?

**Comment by Dzi4d3k** [comment]
No, by player I meant every user, as destination names are put in routes config file, and their names are set during creation. Now shared config has the same destinations name regardless of localization. That is not a problem for mod maps, where POIs (Points Of Interest) have names set by map's author, but on Gianats' Ravenport POIs are localized, yet in config https://github.com/Stephan-S/FS19_AutoDrive/blob/master/courses/Ravenport/AutoDrive_Ravenport_config.xml they are all EN.

**Comment by TyKonKet** [comment]
@Stephan-S what do you think?

**Comment by Stephan-S** [comment]
I don't really like the Idea. The destination names are usually to unique to be translated automatically.
And manually doesn't really make sense in my opinion

**Comment by Dzi4d3k** [comment]
I have idea to add language tag in destination names with following workflow (if possible)
- new destination name will get two tag default EN and game currently localized
- renaming destination will rename only current game language version or adding new localization if edited on different localization than the one that originally created
- renaming EN would be possible only on game set to EN or directly in xml file

If above is to much to code (I suppose) then maybe only support adding tag manually in xml?
