### ISSUE TITLE
v1.0.6.6 fährt nicht durch weight trigger

### ISSUE THREAD

**Issue by andreasthu** [Stephan-S/FS19_AutoDrive#706]
hallo stephan

hab seit der neuen v 1.0.6.6 von autodrive das problem, das der ad-fahrer nicht mehr durch waagestations trigger, die auf map verbaut sind durchfährt
![fsScreen_2019_10_28_15_24_40](https://user-images.githubusercontent.com/24860501/67687249-54872900-f998-11e9-8bb3-7c30acd33949.png)
hier im GE:
![editor](https://user-images.githubusercontent.com/24860501/67687261-5a7d0a00-f998-11e9-81ff-b053f3ef5ce1.jpg)

anmerkung, bei der originalen map ist der channel 5 der colli aktiv ( collisionmask 7fffffff ), den hab ich aber vor einigen wochen ausgeschaltet, der trigger hat bei mir 7fffffdf, da es da auch schon nicht ging, ohne channel 5 funktionierte es dann, AD fuhr durch (die strassen habe ja auch die colli "df", anstelle "ff", da fehlt auch der channel 5, deshalb wendet die ki auch auf strassen)
aber seit heute bleibt der AD fahrer vorm trigger stehen
kannst du da mal drüber schauen,
k.a. wieviele maps mit waage es gibt, aber manche würden da gerne durchfahren.
(btw, diese map ist die minibrunn vom modhub, waage bei der einfahrt zur BGA, falls du eine map mit waage zum testen suchst)
lg
andreas

**Comment by Stephan-S** [comment]
Should be fixed in latest source files.
There was an error with the collision mask AD used.

**Comment by andreasthu** [comment]
Danke, funktioniert
lg
andreas
