### ISSUE TITLE
AD Abfahrer rammt Drescher

### ISSUE THREAD

**Issue by Andii1980** [Stephan-S/FS19_AutoDrive#707]
Hallo,

Seit dem letzten Update habe ich das Problem das der AD Abfahrer in den Drescher reinfährt. Egal von welcher Seite. Es ist auch immer unterschiedlich ob er vorne, seite oder hinten direkt rein fährt. Welcher Drescher und Abfahrer ist dabei auch vollkommen egal. 

Die Kollisionserkennung habe ich wie immer ausgeschaltet.
Sonst habe ich an den Einstellungen was das Abladen und Drescherverhalten betrifft alles auf Standard. 

Drescher fährt mit CP (mit und ohne Fruchtumfahrung) oder mit dem Giantshelfer.

**Comment by pulimatrix** [comment]
Hey Andii.
Hatte das Problem ab der version, 1.0.5.4, zeig mal die einstellungen die du gemacht hast?! vllt kann ich dir da Helfen! hast mal in die Log geschaut was er dort sagt? lg

**Comment by Andii1980** [comment]
> Hey Andii.
> Hatte das Problem ab der version, 1.0.5.4, zeig mal die einstellungen die du gemacht hast?! vllt kann ich dir da Helfen! hast mal in die Log geschaut was er dort sagt? lg

Hallo @pulimatrix 
so schaut es bei mir aus.

![20191029011124_1](https://user-images.githubusercontent.com/23103565/67724866-bb303500-f9e0-11e9-89d2-8ebf1792c68e.jpg)
![20191029011153_1](https://user-images.githubusercontent.com/23103565/67724877-bff4e900-f9e0-11e9-8b78-e33a826d7330.jpg)
![20191029011136_1](https://user-images.githubusercontent.com/23103565/67724879-c08d7f80-f9e0-11e9-8a1c-88a9e2409f0e.jpg)
![20191029011149_1](https://user-images.githubusercontent.com/23103565/67724880-c08d7f80-f9e0-11e9-9f14-191afc1c1e5d.jpg)

**Comment by Andii1980** [comment]
In diesem Fall ist der Abfahrer grade unter dem Drescherrohr durchgefahren und dann davor.

![20191029023255_1](https://user-images.githubusercontent.com/23103565/67728030-f4ba6d80-f9eb-11e9-93ef-69350ef889c0.jpg)

**Comment by GitTomahawk** [comment]
Ich habe den Fehler auch beobachtet.
Die Drescher fahren bei mir mit Moglis AI VehicleExtension (da CP ja leider kein MP unterstützt) immer mit Rohr nach außen im Kreis. Dass der Abfahrer manchmal den Drescher von vorn rammt z.b. kurz nach einer Feldecke hatte ich schon in vorherigen Versionen, aber in der aktuellen rammt er ihn auch von hinten oder in die Seite an langen geraden Stellen.

**Comment by Stephan-S** [comment]
@GitTomahawk welche Version nutzt du?
Und wann genau passiert das? Beim normalen Abladen bei vollem Drescher oder beim aktiven Abladen?
Vor einigen Versionen habe ich den Pfadplaner so angepasst, das er beim 'Früher rufen' nicht mehr durch die Frucht fahren darf, da er sonst oft einen Pfad durch die Frucht im Drescherpfad geplant hatte, wenn er keinen fruchtfreien Weg gefunden hat

**Comment by pulimatrix** [comment]
Laut einstellung schaut soweit gut aus, bei mir ist auch oft das Problem das wenn er von hinten kommt den roder/Drescher schiebt! oder auch zurseite schiebt:/ Bremst kurs vorm rohr ab und dann wenn er unterm rohr ist beschleunigt er und setzt sich vorm drescher :/. Passiert immer wenn drescher anhält lade rohr ausfährt dan fährt abfahrer los zum abtanken und dan beginnt der spass ?!

AUch wenn ich auf früher abfahren einstelle, reagiert er nicht mal drauf, drescher/roder fahren das rohr nicht aus zum abtanken , feld kurse laufen mit cp, hmm lg

**Comment by Stephan-S** [comment]
@pulimatrix Nutzt du die aktuellen Quelldateien? Dieses vor den Drescher setzen wollen war ein Bug den ich vor Kurzem erst gefunden und behoben hatte.

Früher Abfahren sollte aber eigentlich funktionieren. Du musst natürlich auch das Level einstellen ab dem er früher rufen soll. Und das gleiche Ziel sollte natürlich auch eingetragen sein.
Mit welchem Fahrzeug funktioniert das denn angeblich nicht?
Das Rohr wird dabei erst ausgefahren, wenn der Abfahrer in der Nähe ist, nicht so wie beim 'normalen' rufen, wenn der Drescher schon voll ist und steht

**Comment by GitTomahawk** [comment]
Aktuell nutze ich die GIT Version von gestern. Ich werde aber gleich auf 1.0.6.7-3 updaten um den Fehler mit dem "bleibt aktiv nach Abladen" zu beheben.
Beim Abfahrermodus benutze ich meistens Abfahrer früher rufen "nein", denn da treten grundätzlich die wenigsten Kollisionen mit dem Drescher auf. Sobald ich den Drescher nicht zum abladen auf der Stelle halten lasse, sondern versuche im fahren abzuladen oder früher rufen lasse kommt es bei fast jedem zweiten Mal zu kollisionen. 
Ich hätte da als Ursache noch den vehicle Turnradius in Verdacht, weil er vielleicht den berecheten Pfad nicht genau folgen kann - spielt es eine Rolle ob der radius im Fahrzeug oder im Anhänger gesetzt ist? Bei mir inst nämlich der Wenderadius des LKW der begrenzende part? (hast du nen Tip wie man den am präzisesten nachmessen kann?)

**Comment by geo-luchs** [comment]
Ich hatte das Problem in älteren Versionen auch. Aber zuletzt ist das Problem nicht mehr aufgetaucht.
Einfach bitte nochmal die aktuelle 1.0.6.8 testen und Feedback geben.
Danke😊
