### ISSUE TITLE
Fruchtumfahrung buggy?

### ISSUE THREAD

**Issue by Andii1980** [Stephan-S/FS19_AutoDrive#708]
Hallo,

Kann es seit das seit dem Letzten Update die Fruchtumfahrung außer Betrieb ist?
Wenn sie an ist fahren die Abfahrer trotzdem immer durch die Frucht. Was sie aber auch bei Aus machen.

**Comment by Corona01** [comment]
Das die Fruchtumfahrung komplett ausser Betrieb ist, glaube ich nicht.
Bei mir fährt der Abfahrer nur beim ersten zufahren zum Drescher und beim abfahren vom Drescher, wenn er sich auf den Weg zum abladen macht, durch die Frucht, trotz aktivierter Fruchtumfahrung.
Weg im Feld suchen aktiviert oder nicht macht da auch keinen Unterschied.
Wenn der Abfahrer nach dem ersten abtanken im Feld parkt und dann zum zweiten oder dritten abtanken zum Drescher fährt, umfährt er die Frucht.
