### ISSUE TITLE
MP Kurse hochladen

### ISSUE THREAD

**Issue by MaLouPa** [Stephan-S/FS19_AutoDrive#709]
Moin moin,

Wir haben probiert auf unserem Dedi ubsere Kurse hochzuladen. 

Jeweils auf unterschiedliche weisen. 

„Funktioniert“ hatte es mit dem Import und als Admin hochladen ganz gut.

Er lädt auch nach und nach die WegPunkte, jedoch verschwinden die immer wieder.

Wir vermuten dass die fertigen Kurse wohl zu Gross sind für den Import 🤷🏼‍♂️

Wir spielen die 4Fach NF Marsch, und haben die aktuellen Kurse von Modhoster zb. Geladen wo schon fast alles eingefahren ist.

Vielleicht sind wir aber auch zu doof 😄

Werde es heute Abend noch einmal ohne jegliche weitere Mods probieren.

**Comment by Bandesss** [comment]
Das beste ist wenn ihr FTP zugang habt und es so aussieht
Denn so klappt, es zu 100%
![1](https://user-images.githubusercontent.com/50829319/67704837-29abcd80-f9b6-11e9-81d9-6ecb69cd8755.JPG)

**Comment by MaLouPa** [comment]
Ja das haben wir, aber dann lädt er sich auch dumm und dusselig :(

**Comment by Bandesss** [comment]
Komisch ich habe eine Datei mit fast 60Mb für die Multimap.
Direkt im Ordner, so gehts tadellos 
Sorry das ich nicht helfen kann.

**Comment by MaLouPa** [comment]
Ok. Dann sind unsere 2,5mb ein Witz.

Merkwürdig 😃

**Comment by MaLouPa** [comment]
Also, wir können aus ner bestehenden Kurse Datei, keine Punkte anfahren. Auch keine neuen abspeichern

**Comment by Bandesss** [comment]
Das macht man aber im Singelplayer und nicht auf einem Server :)
Wir haben nen Root und das berchnen dauert ewig. Im Singelplayer ohne Probleme

**Comment by MaLouPa** [comment]
Jap, haben wir ja auch gemacht. 

Allerdings mal probiert nur die entsprechenden mapmarker zu löschen, aber ging halt auch nicht :/

**Comment by Bandesss** [comment]
Ok dann muss Euch Stephan helfen, da bin ich nun überfragt.
Sorry

**Comment by Matze9876** [comment]
Hallo zusammen.
Gleiches Problem habe ich auch.
Ich habe die bereits eingefahrenen Kurse von Modhoster importiert.
Im Singleplayer funzt es tadellos, im Multiplayer scheint er immer wieder auf´s neue die Kurse neuzuberechnen?!?
In der Log erscheint kein Fehler, ich verwende momentan noch die Ver. 1.0.6.4

Über Hilfe würde ich mich freuen...

P.S. großes Lob für die bisherige Leistung, auch an das Forum...

**Comment by MaLouPa** [comment]
> Ok dann muss Euch Stephan helfen, da bin ich nun überfragt.
> Sorry

Darf ich Fragen mit welcher Version ihr spielt?
Wir sind auf der ganz aktuellen.

**Comment by Matze9876** [comment]
Gestern Abend habe ich noch die Ver. 1.0.6.5 getestet,
aber hier das gleiche Problem.

**Comment by MaLouPa** [comment]
> Ok dann muss Euch Stephan helfen, da bin ich nun überfragt.
> Sorry

Hilfe :-)

Welche Version spielt ihr?

**Comment by Stephan-S** [comment]
Ich bin heute dran. Sorry das es etwas länger dauert bis ich mich um MP Themen kümmere :-)

**Comment by MaLouPa** [comment]
Kein Problem 😄

**Comment by Stephan-S** [comment]
Ich nehme an ihr nehmt die Kurse von Holger oder?
Oder habt ihr eigene? Dann schickt mir die gerade gerne mal

**Comment by MaLouPa** [comment]
Wir nutzen die hier:

https://www.modhoster.de/mods/autodrive-kurse-fur-die-map-nf-marsch-4fach-mit-graben-ab-v1-0#images


Sobald wir die eigens eingefahrenen Kurse nehmen gibts keine Probleme

**Comment by MaLouPa** [comment]
Hm. 
Für mich fühlt sich das so an, als ob er einfach dauerhaft immer wieder von neuem die kurse einlesen würde.
In der 1.0.6.6b zeigt er oben im AD fenster auch dauerhaft an „kurse vom server laden..“ das geht aber auch nicht weg bei mir
