### ISSUE TITLE
Sort display order for previous/next target

### ISSUE THREAD

**Issue by rogeriodec** [Stephan-S/FS19_AutoDrive#710]
As described in https://github.com/Stephan-S/FS19_AutoDrive/issues/644#issuecomment-543993697, currently using Ctrl+Alt+Left or Ctr+Alt+Right, the destinations are being shown in an unsorted way.

**Comment by rogeriodec** [comment]
I saw that this issue was solved with the latest version, so I'm closing this issue.
Thank you!

**Comment by rogeriodec** [comment]
Sorry for reopening this issue, but it seems the problem is back, at least with 1.1.0.2 version...

**Comment by Iwan1803** [comment]
Please try 1.1.0.5-RC3. If the problem still exists, just open a new issue.
