### ISSUE TITLE
Suggestion: Improve HUD to fit the description inside header

### ISSUE THREAD

**Issue by rogeriodec** [Stephan-S/FS19_AutoDrive#711]
Some translations will not fit inside the HUD's header:
![image](https://user-images.githubusercontent.com/11199752/67709914-b4340300-f99d-11e9-9ad4-324f54427813.png)

I suggest, as an improvement, to create a header with a **flexible** height, and create an auto-wrap of the text inside the header, so if the text can't fit in just one line, the header width will increase one or more lines to fit the entire text.

**Comment by Stephan-S** [comment]
Good suggestion!

**Comment by raxtor** [comment]
@Stephan-S do you think its good idea with flexi-height without any user input? What about remove "Autodrive" and "mode name" when other info text is active? And for rly long texts just scroll text to left and back?
