### ISSUE TITLE
Güllezubringer

### ISSUE THREAD

**Issue by sergant-bilco** [Stephan-S/FS19_AutoDrive#712]
Hallo Stefan,

Habe auf meiner Karte mal das Gülle Zubringen mit 2 Fahrzeugen simuliert, klappt soweit ganz gut bis auf den Punkt das Autodrive nicht am Ziel wartet bis entleert wurde, vielleicht der falsche Modus? Sonst würde es mich freuen wenn da noch was machbar wäre damit sie am Feld warten.
Dann sah ich in den Einstellungen den Punkt mehrere Ziele, könnte man da nachher dann einen Art Ablaufplan erstellen und die Zubringer führen dann die Felder der Reihe nach ab, das wäre die Krönung, wird aber so wahrscheinlich nicht realisierbar sein ohne grossen Aufwand.

Sonst muss ich sagen, Top Arbeit bis jetzt

**Comment by Andii1980** [comment]
Hallo, ich habe das Problem das er meine Gülle / Gärreste gar nicht entlädt aber dort stehen bleibt.

**Comment by wallsingham** [comment]
@sergant-bilco 
>klappt soweit ganz gut bis auf den Punkt das Autodrive nicht am Ziel wartet bis entleert wurde

Wie genau hast du das Gülle Zubringen simuliert. Wäre interessant zu lesen mit welchen Fahrzeuge und welchen Arbeitsmodis jeweils.

**Comment by sergant-bilco** [comment]
Hallo,

 

Fahrzeuge sind 724 und 930 Standardfahrzeuge, beide mit Reifengewicht, Fass Zunhammer 18500 Standard mit Schleppschlauch, Zunhammer Zubringerfass 15500 als Mod, der 930 hat ein Standard 2500 Gewicht vorne drauf: 930 zieht das Fass der 724 das Zubringerfass.

 

also beim Befehl Abholen und Abliefern bei 2 mal wiederholen, hält er nicht am Feld, er wendet um das 2. Mal zu fahren ohne leer zu sein.

         beim Befehl Abholen mit 2 mal wiederholen, hält er auf dem Feld an, löscht das 2 mal fahren und bleibt stehen, also muss er wieder manuell losgeschickt werden.

 

Da ich auf meiner Karte viele kleine Felder aber auch große habe, wäre es interessant entweder das Fass wie einen Drescher zu behandeln und der/die Zubringer findet/finden ihn auf dem Feld oder gar das der/die Zubringer ihn immer findet/finden egal welches Feld man gerade angefahren hat und er/sie dann die beste strecke dahin berechnet/berechnen, somit kann ich mit einem Zubringer auf vielen kleinen Feldern mit dem Fass einfach umsetzen und würde trotzdem gefunden und beliefert. Das wird aber vielleicht so nicht umzusetzen sein, da er sich ja auch teilweise wie ein Follow me verhalten müsste wenn ich ihn nicht ganz leer machen könnte bevor ich umsetzte er aber noch zu voll ist um wieder auftanken zu fahren.

Der Part mit den Ordnern kann hier bedingt funktionieren denn er würde ja alle Felder anfahren bis er mich finden würde. Spiele zur Zeit mit +- 40 Wiesen die ich alle für den ersten Grünschnitt dünge, da sind Felder bei die er alleine 8x anfahren müsste damit alles voll ist und andere gerade 1x.

 

Lasst eure Gedanken mal etwas spielen damit, vielleicht geht es nicht so aber anders, ihr kennt den Code oder habt a vielleicht eine Lösung für mich mit dem bestehenden Code.

 

Danke für euer Interesse, der Mod ist so schon ganz Klasse, Hut ab.

 

 

 

Von: wallsingham [mailto:notifications@github.com] 
Gesendet: Montag, 4. November 2019 01:30
An: Stephan-S/FS19_AutoDrive
Cc: sergant-bilco; Mention
Betreff: Re: [Stephan-S/FS19_AutoDrive] Güllezubringer (#712)

 

@sergant-bilco <https://github.com/sergant-bilco> 

klappt soweit ganz gut bis auf den Punkt das Autodrive nicht am Ziel wartet bis entleert wurde

Wie genau hast du das Gülle Zubringen simuliert. Wäre interessant zu lesen mit welchen Fahrzeuge und welchen Arbeitsmodis jeweils.

**Comment by wallsingham** [comment]
Eine mögliche Lössung wäre vielleicht wenn AD den Triger vom Gülle Feldcontainer oder den von den Flüssigkeitstanks als Auflade-Triger erkennen würde.

**Comment by sergant-bilco** [comment]
Hallo, ja und nein, bei großen Flächen ist das eine Lösung, bei kleinen Flächen zu viel Aufwand denke ich.
null

**Comment by Iwan1803** [comment]
Da kein weiteres Feedback -> geschlossen.
Bitte mit der neuesten Version erneut versuchen und bei Bedarf ein neues Issue erstellen, danke!
_Since no further feedback -> closed.
Please try with the latest version and create a new issue if necessary, thanks!_
