### ISSUE TITLE
Wrong truck being selected for unload combine

### ISSUE THREAD

**Issue by Voidheartd** [Stephan-S/FS19_AutoDrive#716]
I had 2 fields next to each other being worked at the same time for different contracts. Is it not correct that a vehicle on the unload combine mode will choose a harvester based on the waypoint selected on the harvester? The reason I ask is that the truck for field 20 kept going to the harvester in field 19.

The harvester for field 20 had the field 20 waypoint selected and 19 was selected on the other one. I have included a screenshot of the map showing the locations of the waypoints as red dots. The field 20 truck went to field 19 even when it had a partial load of soybeans from field 20. This was a bit of an issue considering field 19 was sugar beets.

![image](https://user-images.githubusercontent.com/3398909/67740884-c9d11900-f9ed-11e9-9e30-3664a4d09f7a.png)

**Comment by Stephan-S** [comment]
https://github.com/Stephan-S/FS19_AutoDrive/wiki/3-AutoDrive-modes:#351-basics
:-)
