### ISSUE TITLE
need info

### ISSUE THREAD

**Issue by ploughedfieldman123** [Stephan-S/FS19_AutoDrive#717]
Apologies, but this is not really an issue, but I didnt know where to ask this question

When the vehicle is moving along a route, I have noticed that there are these numbers  at the top of menu  example below

2.26 2.25 2.24 2.23 2.22        which obviously mean you are getting close to your destination 

cant these numbers be added to the nodes in the editor, and then if a line is a bit crooked or not straight you could then locate and move them in the editor, as it would be the exact place on map in game when the route needs adjusting a bit.

**Comment by Woife1** [comment]
Do you mean the "numbers" in the top line of the HUD?
this is the time the driver needs to his destination

![Unbenannt](https://user-images.githubusercontent.com/55350545/67794706-6393d700-fa7d-11e9-8d34-47b48fc23a6d.jpg)

**Comment by ploughedfieldman123** [comment]
Yes thats exactly what numbers I mean I know they are how far you away from destination, but couldn't those numbers be added to the blue dots in the editor. as that way then if you need to change line you will have the exact spot in the editor

**Comment by Woife1** [comment]
This is not a waypointnumber this is a Time so this "number" can be at every waypoint ;)

**Comment by ploughedfieldman123** [comment]
Oh I see, but a pity, you cant locate same spot in editor as in game to straighten lines or what ever else

**Comment by Woife1** [comment]
I edit my courses ingame (it is easier for me) 
and you have to recalculate the courses ingame if you edit with the editor (you can see in editor the PDA-Map thats normaly enough to locate spots)

**Comment by ploughedfieldman123** [comment]
> the exact waypoint ID you only need in the XML

where is that then. 

> and you have to recalculate the courses ingame if you edit with the editor

Oh I never realised that.

I have also noticed the routes in CoursePlay for AD, but I had 1 yesterday saying  shop and return. so I was in this field  sent tractor on its way to shop and return. when it got to shop it never stopped just carried on back to field.  so whats point in that dont make sense. I would have thought it would stop then  you say attach something to tractor then off it goes back to field.  but seems silly to just go to shop dont stop but just carry on back

**Comment by Woife1** [comment]
i mean the AD_XX_config.xml (the save-xml from AD for your savegame)
CP drives on the AD courses you select (only unload or refill works on the "and return" courses)
but if you want that CP stops only use drive to without return (but AD could make it as good or even better ;) )

**Comment by ploughedfieldman123** [comment]
> i mean the AD_XX_config.xml (the save-xml from AD for your savegame)

Oh am with you now

> (only unload or refill works on the "and return" courses)

got you now

like you said probably best to edit lines in game, But I have noticed in the editor some parts a bit crooked but how can I find that part in game. this is what puzzles me

**Comment by Woife1** [comment]
you see the crooked lines in the editor with the pda in the background 
the orientation is like ingame 
the editor should look like:
https://user-images.githubusercontent.com/30005040/63292593-ea7a4580-c2bd-11e9-9066-578798aff092.png

**Comment by ploughedfieldman123** [comment]
> you see the crooked lines in the editor with the pda in the background
> the orientation is like ingame
> the editor should look like:
> https://user-images.githubusercontent.com/30005040/63292593-ea7a4580-c2bd-11e9-9066-578798aff092.png

Yes my editor is like that.  but i notice you have some red lines, which means traffic can go both ways.  as its for narrow roads. but in the AD in game I dont seem to have the option of making red lines no more and my AD version is the very latest

<version>1.0.6.6</version>

**Comment by Woife1** [comment]
the red line in editor are the blue ones ingame
you make them by pressing the right mousbotten or the mousewheel on the recordbutton

**Comment by ploughedfieldman123** [comment]
> the red line in editor are the blue ones ingame
> you make them by pressing the right mousbotten or the mousewheel on the recordbutton

Dam I just discovered my using RMB  it will make blue lines in game. red in editor. where do you find out all this info. is there a help topic on it or what keys do what functions

**Comment by ploughedfieldman123** [comment]
dam urgent hope you still about but i cant now load up my editor config file in savegame all i get is this 

<a href="https://ibb.co/tXLbczH"><img src="https://i.ibb.co/BNngjGf/1.jpg" alt="1" border="0"></a><br />

**Comment by ploughedfieldman123** [comment]
> dam urgent hope you still about but i cant now load up my editor config file in savegame all i get is this
> 
> [![1](https://camo.githubusercontent.com/372bcbb0010e8c986a355d810ca3dcc1e09b5bf2/68747470733a2f2f692e6962622e636f2f424e6e676a47662f312e6a7067)](https://ibb.co/tXLbczH)

**Its ok now Woife1  I have fixed it, I hadn't joined up a route**

**Comment by Woife1** [comment]
the most information i get from the commits and read a lot of issues ;)

you need the pda.png from your map than it work a lot better
i didn't really know much about the editor but on youtube you could find some tutorials (maybe in a "false" language but youtube can translate it)
