### ISSUE TITLE
Two or more vehicles on a blue line in the same direction

### ISSUE THREAD

**Issue by VS-Honk** [Stephan-S/FS19_AutoDrive#718]
Thanks for the great work.

If two vehicles run on a blue line in the same direction the vehicle in front is stoping at the end of the blue line. I have to stop AD in the back one(s) manually, then the first vehicle drives on.
https://youtu.be/jl7tAzIGDIQ Sorry for hide the mouse in the video.

**Comment by Woife1** [comment]
I think the problem is 
on the blue line only 1 vehicle is allowed
the 2. vehicle had to stop about 5 waypoints before getting on the blue line

**Comment by Stephan-S** [comment]
Could you retest your scenario with the current source files? Thank you!

**Comment by Stephan-S** [comment]
I'm going to set this as closed. If the issue is still present with the current source files, please confirm
