### ISSUE TITLE
Improvement: Drive to More Destinations/Mehrere Ziele anfahren

### ISSUE THREAD

**Issue by Woife1** [Stephan-S/FS19_AutoDrive#719]
Hi Stephan wäre es möglich im Modus Fahren mehrere Ziele herzunehmen?
Also fahre zu Ziel 1 und dann zu Ziel 2
Quasi wie die Transportmodis aber als Lösung für Ballen/Palettentransporte

Is it possible to get more destinations in mode Drive?
As drive to destination 1 then to destination 2

Vielen Dank für die ganze Arbeit und diesen wunderbaren Mod

**Comment by Iwan1803** [comment]
Ist ja nun schon länger vorhanden -> closed.
