### ISSUE TITLE
settings for AutoDrive 

### ISSUE THREAD

**Issue by ploughedfieldman123** [Stephan-S/FS19_AutoDrive#720]
https://github.com/Stephan-S/FS19_AutoDrive/wiki/6-Settings

where are these settings for  6.1.1 Lookahead distance turning. how do increase value.  also 6.1.2 to 6.1.4

**Comment by Woife1** [comment]
6.1.1 is in Settingsmenu (Ctrl+Alt+Num0) left row 1.
6.1.4 is left row 2.
6.1.2 is middle row 1.

**Comment by ploughedfieldman123** [comment]
> 6.1.1 is in Settingsmenu (Ctrl+Alt+Num0) left row 1.
> 6.1.4 is left row 2.
> 6.1.2 is middle row 1.
> 
> This is german version but you can see where
> ![20191029180009_1](https://user-images.githubusercontent.com/55350545/67790416-08121b00-fa76-11e9-8eee-076c2574a07c.jpg)

Wow never even knew that menu was there thanks.  

I dont suppose you would know anything here as well

  https://github.com/Stephan-S/FS19_AutoDrive/issues/717
