### ISSUE TITLE
Feature request "Live Mode" (real time routes navigation)

### ISSUE THREAD

**Issue by Axel32019** [Stephan-S/FS19_AutoDrive#721]
Hallo
Erstmal ein großes Dankeschön an Stephan und alle Beteiligten für diesen super Mod.
Ich nutze ihn nun schon eine Weile und habe mir mal ein paar Gedanken zur Routenkalkulation gemacht:
Basis ist aktuell die Map Nordfriesische Marsch 4fach V1.0 mit dem AD Netz von Holger70 mit der Anbindung einiger zusätzlicher MapMarker.
Aus meiner AutoDrive...config.xml im savegame lese ich folgendes heraus:
Anzahl Wegpunkte (x,y,z): 39440
Anzahl MapMarker (markerID): 141
Es wird für jeden Wegpunkt die Start-Ziel Berechnung zu jedem MapMarker durchgeführt und in der xml gespeichert / von AD verwendet.
Das ergibt 39440 * 141 = 5561040 Start-Ziel Berechnungen (Dijkstra-Algorithmus).
Auf meinem PC dauert die Neuberechnung der Routen aktuell ca. 1500s.
Macht ca. 3600 Routen / Sekunde im groben Durchschnitt.

**Jetzt die spannende Frage: 
Wäre es nicht sinnvoll die Start(aktueller Wegpunkt)-Ziel(MapMarker)-Berechnung beim Aktivieren von AD durchzuführen???**

Das hätte, wenn überhaupt möglich/sinnvoll, folgende Auswirkungen:
- kein Warten / geringe Beeinträchtigung des Spielverlaufs (FPS etc.)
- neue Strecken und Ziele sind sofort verwendbar

Ich nehme weiter an das die Grafikkarte hierfür keine Rolle spielt, da es sich um die Berechnung von Entfernungen zwischen Punkten handelt.
Bitte korrigiert mich wenn meine Annahmen falsch sind!
Mein PC: 6 Kerne, ca. 3 GHz, 16 GB RAM
Würde mich über Rückmeldungen, Kommentare etc. freuen!
Sorry for the english speaking readers - translation might come later...

**Comment by Woife1** [comment]
Wenn ich die aktuelle "Denkweise" von AD verstanden hab wäre dein Ansatz zu rechenintensiv, weil dann bei jeder Routenberechnung alle Punkte abgefragt wird (also bevor dein Fahrer losfährt legt er erstmal 5 min das Spiel lahm)

machbar wäre es wenn die Berechnung perfekt paralellisierbar wäre 
nur dein PC ist auch dafür ein bischen schwach auf der Brust ;) 
selbst meiner würde ein ordentlich in die Knie gehen (8 Kerne @ 5GHz und 32GB Ram)

**Comment by Axel32019** [comment]
So wie ich es bisher verstehe müsste nur eine Route berechnet werden - die vom aktuellen Wegpunkt den das Fahrzeug "anvisiert" zum Zielpunkt und eben nicht alle Punkte. Das ist ja genau der Hintergrund beim Dijkstra-Algorithmus.

**Comment by Stephan-S** [comment]
Hey, ich melde mich hier Mal kurz zu Wort.

Zu den ersten LS17 Zeiten habe ich es genau so gemacht und bei wachsendem Streckennetz wurde die Verzögerung bis die Fahrt begonnen hatte (0 FPS in diesem Moment) immer spürbarer.

Inzwischen laufen die Berechnungen zwar schon deutlich schneller aber ohne es aktuell ausprobiert zu haben würde ich behaupten, dass man die Verzögerung deutlich spüren bzw messen könnte wenn ich die Berechnung zum aktuellen Ziel live mit Dijkstra berechne.

Mir persönlich ist es wichtiger, dass während der Hauptnutzungszeit möglichst keine Wartezeiten oder gar Ruckler entstehen und daher nehme ich die Berechnungszeit in Kauf.
Allerdings haben die Streckennetze auch inzwischen extreme Dimensionen angenommen :D

**Comment by Iwan1803** [comment]
Nordfriesische Marsch, 4-fach Map, genutzt mit Holgers AD-Kursen, dazu noch ein paar kleinere Strecken auf dem Hof
Berechnungszeit auf 100x: ca. 15 Minuten
In der Zeit ist definitiv kein Spielen möglich, weil die FPS auf 10 und drunter sinken, da ja das gesamte Streckennetz durchgerechnet wird. Lieber mache ich in der Zeit etwas anderes und muss nachher nicht bei jeder AD-Aktivierung auf eine Berechnung warten.
Es ist halt nur etwas "ätzend", wenn man einen Kurs aufgezeichnet hat, dann die Berechnung laufen lässt und nachher feststellt, das man einen Fehler gemacht hat und somit das Spiel/die Wartezeit von vorne beginnt. Aber gut, so lernt man besser aufzupassen :stuck_out_tongue_winking_eye:

@Stephan-S 
auf was erfolgt die Berechnung eigentlich? Ich erinnere mich an ca. 2k Berechnungen pro FPS, aber übernimmt die GPU die Berechnung?

**Comment by Axel32019** [comment]
Hallo zusammen,

Ich hab das jetzt mal implementiert, probiert und bisschen "gemessen":

Setup:
NF Marsch, 4-fach, AD: Loaded Waypoints: 39520, basiert auf AD Netz von Holger70
Berechnung Kurs von "V - Hafen" nach "V - Aldi" ergibt 870 Waypoints

1. Berechnung Dijkstra komplett "nach Lehrbuch"
	Rechenzeit:	63 sec
2. Optimierung der "longLine"-Verbindungen
	Rechenzeit:	13 sec
3. "Meine" Optimierungen (for-Schleifen, Tables, nur Voraus-Suche etc.)
	Rechenzeit:	jetzt wirds kompliziert für meinen "schwach auf der Brust"-Rechner @Woife1 ;-)
	Leider kann man in LS nur mit getDate() Zeiten messen und das max. mit 1 sec Auflösung :-(
	In mehreren Versuchen einen Kurs von F62 Nordwest im Feld nach "Feld 51 Abfahrer" zu berechnen komme ich damit manchmal auf eine Berechnungszeit von 1 sec, sonst 0 sec.
	Fahrzeit ca. 9 min

4.	Offen ist noch die Optimierung der Initialisierung - lerne noch immer LUA ;-)

Wie hört sich das für Euch an?

Werde mal sehen ob ich das dieses WE irgendwie auf Github bekomme, bin damit noch nicht so fit...
Dann sind natürlich Leute zum Testen gefragt, sofern @Stephan-S nichts dagegen hat.

**Comment by Iwan1803** [comment]
Aktuell brauche ich für die gesamte Streckenberechnung auf der NFM mit Holgers Vorgabe + eigenen Wegen ca. 10-12 Minuten. Es wäre schon geil, wenn alleine diese Zeit drastisch reduziert werden könnte.

Wenn dies damit gelingt, das jeder Abfahrer seine Strecke erst berechnet, wenn man ihn losschickt und eine Gesamtberechnung damit wegfallen könnte, hätte ich auch nichts dagegen, aber so ganz verstehe ich deine gemessenen Zeiten nicht.
Dein 1. kann ja keine komplette Berechnung des gesamten Netzes sein sondern nur dieser einen Route, oder?
Ist dein 2. eine Optimierung der Dijkstra-Methode oder was eigenes?
Dein 3. klingt natürlich ziemlich "geil", aber wie sieht es während der Rechenzeiten mit den FPS aus?
Und was mich natürlich auch noch interessiert:
- wirken sich die ständigen Berechnungen irgendwie auf andere AD-Fahrer aus, welche gerade unterwegs sind?
- was passiert, wenn ich eine Punkt auf einer Strecke löschen, die ein AD-Fahrer für sich errechnet hat?

**Comment by Axel32019** [comment]
Die 1. ist, richtig, die Berechnung einer Route mit dem Algo: Start nach Ziel. Das sind bei insgesamt ~40000 Wegpunkten natürlich eine Menge, daher diese Zeit.

Die 2. hab ich ein bisschen von der derzeitigen Implementierung von @Stephan-S  abgeguckt: viele 1:1 verbundene Wegpunkte muß man nicht immer wieder neu berechnen.

Die 3. spiele ich im Augenblick. Da 4. noch fehlt sehe ich momentan nur max. ein ganz kurzes Rucken wenn ein AD Fahrer einen neuen Kurs berechnet. Bei den FPS sehe ich gar nichts, da die Berechnung <1 sec dauert 👍 Wirkt sich somit auch nicht auf andere CP/AD-Fahrer aus.

Probiere gerade neue Ziele ohne Neuberechnung !!! anzubinden - sieht bisher gut aus...

Zu "was passiert, wenn ich eine Punkt auf einer Strecke löschen, die ein AD-Fahrer für sich errechnet hat?": Wenn ich es richtig aus dem Code verstanden habe ist die Wegpunkte-Liste eines AD-Fahrers eine Kopie aus allen Wegpunkten. Es sollte somit keinen Einfluß auf schon fahrende/aktive AD-Fahrer haben - das kann sicher @Stephan-S genauer beantworten.

**Comment by Iwan1803** [comment]
Das klingt doch schon mal super.
Ich biete mich da gerne als Versuchsperson an, da ich gerade einige Zielpunkte immer wieder neu setzen muss, weil AD sonst irgendwie die Trigger nicht richtig anfährt. Wenn ich mind. 3 Änderungen zusammen habe, mache ich die dann und erst im Anschluss daran erfolgt dann die notwendige Neuberechnung, so das mit jeder Änderung locker 15 Minuten in Anspruch nimmt. Obendrauf kommt dann natürlich noch die Zeit fürs testen, dann ggfs. noch mal ändern, usw.
Wenn sichergestellt ist, das aktive AD-Fahrer durch Änderungen in der Strecke nicht beeinflusst werden, wäre das grandios.

**Comment by Woife1** [comment]
Dein Ansatz hört sich auf jedenfall vielversprechend an 👍 
Melde mich auch mal als Tester

Nur aus Interesse bei deiner Version würde ein Abfahrer (Abholen und Anliefern) den Weg bei jedem Stop neuberechnen oder nur einmal den gesamten Weg und den dann immer wieder fahren?

**Comment by Axel32019** [comment]
@Iwan1803 Zitat: Wenn sichergestellt ist, das aktive AD-Fahrer durch Änderungen in der Strecke nicht beeinflusst werden, wäre das grandios.
Genau solche Fälle sollten getestet werden - allein schaff ich das nie!

@Woife1 Zum Verständnis: Das grundsätzliche Verhalten von AD ändert sich nicht!
Wenn ein Abfahrer aktiviert wird, wird die Route zum Ziel neu berechnet - bisher aus den komplett vorberechneten Daten, bei meiner Implementierung aus den aktuellen Wegpunkten, Verbindungen und Zielen. 
Es trifft also der 2. Punkt aus 1. Post zu. Man kann also einem Abfahrer vom Feld ein Ziel zuweisen welches gerade erst "eingefahren" wurde. Der Weg wird nach meinem Verständnis vom Abfahrer nur solange behalten wie er fährt (grün), wenn er angekommen ist (weiß) wird der Weg weggeschmissen - normales AD-Verhalten. Hoffe das ist halbwegs verständlich.

**Comment by Axel32019** [comment]
@Iwan1803 @Woife1 So dann mal ran ihr Tester: https://github.com/Axel32019/FS19_AutoDriveLive

**Comment by Iwan1803** [comment]
Verdammt.... zu spät gesehen.... lasse gerade neu berechnen.... 
aber ich finde bestimmt gleich noch Strecken, die ich manipulieren kann 😂

**Comment by Woife1** [comment]
Ich denke Fehler die auf deiner Änderung beruhen sollten wir auf deiner Github seite durchgehen
Wir müssen Stephan ja nicht komplett vollspammen ;)

Ich mach mich Morgen an die Arbeit des testens RL ruft ....

**Comment by Axel32019** [comment]
Heute hab ich mal zwei neue "Messwerte". Zum verständlichen Vergleich in Prozent:
Vorgänger-Version Routen-Rechenzeit: 100 %
Aktuell mit oben erwähnter 4. Optimierung:          ca.8 %
Aktuelle Version gerade in Github hochgeladen.
Das ist kein Schreibfehler - 8 Prozent. Damit bin ich dann auch mal mit meinem "Latein" am Ende...

**Comment by Woife1** [comment]
also neue Rechenzeit nur noch max 0,08 sek?

**Comment by Axel32019** [comment]
Solche Zeiten sind berechnet!!! Konkret: neue Version 6sec für 100x die o.g. Beispielroute berechnen.
Was ich gefühlt sehe ist die spontanere Anzeige der Linie vorraus "Zeige nächsten Pfad" 😃

**Comment by Woife1** [comment]
erster kurz Test ❤️ 😍 ❤️ 👍 👍

**Comment by Iwan1803** [comment]
Die Neuberechnung der Routen auf der NFM dauert bei mir ca. 12-15 Minuten, die nun wegfallen.
Dank dieses "Mods" zeichnet man eine neue Strecke auf, erstellt neue Ziele und kann ohne Neuberechnung sofort die Strecken nutzen und die Ziele anfahren. Die Berechnung der Strecken dauert <1 Sekunde.

**Comment by Woife1** [comment]
in der neusten Version fällt die Berechnung gefühlt weg

**Comment by Axel32019** [comment]
Danke fürs Testen. Ihr dürft auch gerne weitere Tester einladen 👍 
Kleine Bitte: Ich habs per Code zwar geprüft, aber noch nicht "Live": Was passiert wenn ein Abfahrer eine Route fährt und bevor er ankommt einige Wegpunkte dazwischen gelöscht werden?

**Comment by Woife1** [comment]
Hab grad den Test gemacht 
quer über die NF 4fach (Feld 41 -> Testpunkt zwischen F62 und F64) Fahrtzeit ~10mins
keine Berechnungshänger feststellbar (Spiel bleibt flüssig und Fahrer fährt einfach direkt ab)

gelöschte Punkte (kurz vorm Ziel) hat der Fahrer einfach ignoriert und die "alten" Punkte einfach weiterhin genutzt, auch als ich ihm neue Punkte (Umfahrung der gelöschten Stelle) gegeben hatte blieb er auf den alten Punkten

einzigste "Fehlfunktion" hatte ich am Startpunkt der Fahrer als ich ihm den nicht mehr verbundenen Punkt anfahren lassen wollte
Fahrer setzte sich mit ca 10 Kmh in direkter Linie (Luftlinie) zum Ziel (so in etwa 4fach ist einfach riesig)  in Bewegung
Fahrer in der nähe gab Fehlermeldung: kein Weg gefunden   aus

**Comment by Stephan-S** [comment]
@Axel32019 Hut ab, das hast du wirklich klasse umgesetzt!
Ich habe es gerade mal ausprobiert und bin erstaunt das es wirklich so verzögerungsfrei läuft.
Mir ist nur aufgefallen, dass du den Winkel nicht berücksichtigst, wenn die Einstellung "Use Fastest Route" nicht gesetzt ist (und auch dann nur mit kleiner Änderung in meinem Code). Daher probiert er beispielsweise bei Holger's NF Marsch Netz immer an den blauen Feldrandkurs-Einfahrten zu drehen, da die Winkel >90° Prüfung fehlt.

Ansonsten eine super Leistung was die Dijkstra Optimierung angeht! Wenn die Tests soweit durch sind, nehme ich das gerne in den Mod mit auf und lasse die 'Vorher Berechnen' Version nur noch als wählbare Option am Leben. 

Durch das Nutzen der "out" Verbindungen, sparst du hier natürlich eine Menge Zeit, wenn du nicht alle Wege zum Ziel berechnen musst. Ich muss zugeben, dass hatte ich in meinen ersten Überlegungen als du das Issue eröffnet hast nicht bedacht. So lies sich ja noch einiges optimieren und zusammen mit den LongLine Optimierungen ist das ja wirklich kein Problem mehr in Echtzeit. Super!

Viele Grüße,
Stephan

**Comment by Iwan1803** [comment]
Das mit den 90° erklärt dann auch, warum heute mein Abfahrer mehrfach verkehrt herum an der Feldeinfahrt stand. Ich hatte mich schon etwas gewundert 😄

**Comment by Axel32019** [comment]
Hallo Stephan,
Danke für das Lob, bin ich gar nicht gewöhnt.

Jetzt zurück zur "Arbeit":
Die Winkelberechnung war eine der ersten Optimierungen. Die hatte ich schon wieder vergessen - ich werd alt!
In AutoDrive:getDriveTimeBetweenNodes wird der Winkel ja schon berechnet, es ist somit nicht notwendig dies im Dijkstra für die gleichen Punkte nochmals zu tun.
Und wie Du richtig festgestellt hast, ist eine kleine Anpassung in dieser Funktion notwendig um den berechneten Winkel zurück zu liefern -> TODO
4 Augen sehen eben mehr als 2.

Ich bin bei der Implementierung auf einen neuen "Betriebs-Fall" gestoßen, daher hat es etwas länger gedauert die Details herauszufinden...
Wenn ein zu großer Winkel die Verbindungen auf der Route zum Ziel unterbricht, d.h. es wird nicht mit dem Vorgänger verlinkt, kann keine Route in FastShortestPath zusammengestellt werden.

Eines ist mir bisher noch nicht klar geworden: Der Aufruf von AutoDrive:getSetting("useFastestRoute") liefert immer nil zurück. Ist das gewünscht / richtig?

Gruß
Axel

**Comment by Axel32019** [comment]
Hallo @Stephan-S , @TyKonKet ,
Könnt ihr mir einen Tip geben woran es liegen könnte das AutoDrive:getSetting("..") für alle Settings immer nil liefert?
Irgendwie komme ich nicht dahinter.

**Comment by TyKonKet** [comment]
You have to call it with dot instead of colon
```lua
-- The second parameter 'vehicle' is optional
-- You have to send it only if you are trying to retrieve a vehicle specific setting
AutoDrive.getSetting("settingName", [vehicle])
```

**Comment by Axel32019** [comment]
Hello,

From my perspective the module is ready for an integration in AD.
As I don't know how the strategy will be, I cannot provide a ready-to-use pull-request.
That's why I will give you some hints:
The main entry point to the route calculation is the function "AutoDrive:dijkstraLiveShortestPath".
I added in the comment a simple explanation on the use of the parameters and the return values.
The return values I orientated to the use-cases in "AutoDrive:FastShortestPath" as far as I understood them.
The function "AutoDrive:FastShortestPath" was only taken to the file for easier implementation and testing, so this should be removed when integrated in AD.

At this point I want to thank @iwan1803 for the intensive test support during the last days!

If you have questions, remarks, concerns etc. feel free to contact me.
[https://github.com/Axel32019/FS19_AutoDriveLive](url)
Regards  Axel

**Comment by TyKonKet** [comment]
Hi @Axel32019, I don't have enough time to translate all the above messages, but that's how I think 'Live Mode' should work:
1) Obviously there must be an option to switch between 'Normal' and 'Live' Mode, or at least we should enable it based on the amount of waypoints and markers.
2) We must make sure that this doesn't have problem with MP ( especially with dedicated servers )
3) When a new path is calculated, it must be cached to improve speed of following calls, this also requires a method to invalidate already calculated paths when a change to the network happens ( a good start point should be what we do when "Auto Recalculations" is enabled ) 

Let me know what do you think about that.

**Comment by Woife1** [comment]
To your point 3
We have testet what happens when you delete some Waypoints from the route -> The driver use the points from the calculation (before you deleted some)

**Comment by Axel32019** [comment]
to 1.
To have an option to enable it is a good approach. 
The amount of waypoints / markers should not be an issue. 
As mentioned above a calculation of a Route diagonal throgh a 4x Map takes ~ 60 ms.

to 2.
I am not aware what will be different in MP / dedi to a single play.
Is it related to the synchronisation of waypoints, markers?

to 3.
Not sure if a cached path is necessary, see 1. and comment from Woife1

**Comment by TyKonKet** [comment]
Ok, if in this situation it takes only 60ms, we definitely don't need a cache.
About  MP, since most of dedi servers have low hardware specs I think we should do some tests to prevent lag issues.

**Comment by Axel32019** [comment]
Hello @TyKonKet, @Stephan-S,
Many thanks for the confidence to integrate this into AutoDrive!
A small suggestion I have in the moment:
The recalculation button is still active and visible even if Live-mode is set ON.
From user perspective I would recommend
- disable the recalculation button if Live-mode is set ON, add tooltip like "see Live-mode" or
- return from recalculation call immediate and give a message to user that this is not required to be done

I expect many user will use recalculation as they do not know Live-mode is available and does not require recalculation.
