### ISSUE TITLE
Sometimes a vehicle turn in circles

### ISSUE THREAD

**Issue by rogeriodec** [Stephan-S/FS19_AutoDrive#722]
I saw similar questions in closed issues. 
Depending on the vehicle speed and the angle of the curve, it will turn in circles infinitely.
What I do: I manually disable AD and I reposition the vehicle and a more comfortable angle so that the vehicle can follow its route normally. 
So I suggest an improvement to the algorithm, if possible: If you realize that the vehicle can't get on the route normally, slow it down a bit until it can, then return to its previous speed.

**Comment by Stephan-S** [comment]
There is already an algorithm running in the background that kicks in when a stuck driver is detected.
It will start looking ahead on it's route and switch to the next point when the angle is best suited for that maneuver.
This is not always able to get the driver back on it's track but it is working well quite often.

But vehicles gettings stuck in loops on normal AD routes should not be a normal thing.
Can you pin point this to any type of situation? Breaking too late? Breaking hard for traffic?
With heavy vehicles etc. ?
Thanks for your feedback

**Comment by rogeriodec** [comment]
Please see this [video](https://youtu.be/pLmb6FIckdU), 
The truck is going to unload at Restaurant, but after the curve, instead of going on in the straight line, it continues in a circle,  colliding with the pole

**Comment by Stephan-S** [comment]
You can easily fix this by recording this with a Turn Radius that this Truck can actually follow.
He Skipped a few Point before He reached the target Line again and is therefore Not registering that He could indeed Continue but is rather trying to reach the point He skipped

**Comment by rogeriodec** [comment]
[This video](https://youtu.be/Tqwa7y_VsTo) shows a more serious situation. The tractor cannot follow the straight path. 
My suggestion is, in a similar situation, AD could simply slow down the vehicle until it can get on the path, then it can increase the speed again.

**Comment by TyKonKet** [comment]
@rogeriodec is that still an issue?

**Comment by rogeriodec** [comment]
@TyKonKet I didn't see any improvement that solved this issue...

**Comment by TyKonKet** [comment]
I saw your video and the problem is simply that the first way point was too much far away, so the tractor had time to gain speed, then when it have to turn or follow the line, the speed is too much high.
But after the commits of yesterday, many things have changed in driving so the problem could be fixed.

**Comment by rogeriodec** [comment]
Good to know! When a new release is available, I'll test this issue. Tks

**Comment by TyKonKet** [comment]
Ok, thanks, let me know

**Comment by rogeriodec** [comment]
The problem persists in 1.0.7.0

**Comment by Iwan1803** [comment]
Da kein weiteres Feedback -> geschlossen.
Bitte mit der neuesten Version erneut versuchen und bei Bedarf ein neues Issue erstellen, danke!
_Since no further feedback -> closed.
Please try with the latest version and create a new issue if necessary, thanks!_
