### ISSUE TITLE
Problems with Hotspots when AD driver is waiting while loading at an empty silo

### ISSUE THREAD

**Issue by geo-luchs** [Stephan-S/FS19_AutoDrive#723]
Hello Stephan
Fed from NF Marsch reported today in his daily video, that he can't jump to any hotspot of productions or shops on his map.
I could reproduce it.

It happens, when a driver has reached a silo, want's to load something, but silo is empty and he shall wait.
In this case, it's not possible, to jump to hotspots on the map.
Only jumps to vehicles are possible.

When AD drivers are driving, it's not a problem to jump to hotspots. Also not when normal loading at silo.

**Comment by Woife1** [comment]
@Stephan-S wenn du dir das Verhalten im Video anschauen willst hier ist die Stelle:
https://youtu.be/2ABvR0llos0?list=PLvDA61SR3lBTOAdyslX-YvXrw1rvtGNiC&t=1189

**Comment by Stephan-S** [comment]
@geo-luchs @Woife1 could you try this with the current source files? I made some changes to the load mode behaviour and it might have resolved this issue. Thank you!

**Comment by Woife1** [comment]
also die hotspots funktionieren mit der neusten selbstzip 👍 
der ganze test zwar mit Mods, sollte in diesem Fall keinen Unterschied machen

ich weis gerade nicht ob es beabsichtigt ist das er im Abholen und Anliefern Modus mit Teilfüllungen los fährt (trotz Einstellung wenn Silo leer -> Warten) meine Meinung ist nicht schlimm bzw sogar gut um Silos zu entleeren (er bleibt stehen wenn nichts ladbar ist und der Anhänger leer ist)

**Comment by geo-luchs** [comment]
Habs auch getestet. 
Scheint zu funktionieren. 
Danke Stephan
