### ISSUE TITLE
Improvement: showing driving route without dev mode

### ISSUE THREAD

**Issue by Iwan1803** [Stephan-S/FS19_AutoDrive#726]
Sometimes it happens if dev mode is active, that i do a calculation instead of starting an AD route.
It would be nice, if there is a button which turns on/off the route lines without activating the dev mode.

Manchmal passiert es bei aktiviertem Dev-Modus, das man aus Versehen eine Kalkulation startet anstatt einen Fahrer loszuschicken.
Es wäre schön, wenn man sich die Streckenlinie bei Bedarf über einen neuen Button ein-/ausblenden lassen könnte, ohne das man den Dev-Mode aktivieren muss.

**Comment by Stephan-S** [comment]
Geht es dir um den aktuellen Fahrkurs des Fahrzeugs, dass du davon mehr siehst oder um das gesamte Streckennetz?
Vielleicht auch wieder als 'Sekundär' Funktion auf den Edit Mode button legen

**Comment by Iwan1803** [comment]
Ich hab auf der Map einige Wege, welche nur in eine Richtung befahrbar sind. Nun kann man sich ja nicht immer alle Strecken merken und um zu sehen, wo welche Fahrwege sind, muss man dann wieder den Dev-Mode aktivieren.
Wenn man die Wege anzeigen lassen können, indem man einen Rechtsklick auf den Edit-Button macht, dann würde das schon reichen und du musst keinen neuen Button einbauen.

**Comment by Stephan-S** [comment]
Erledigt
