### ISSUE TITLE
Improvement: in order list move button and button to fold up/in

### ISSUE THREAD

**Issue by Iwan1803** [Stephan-S/FS19_AutoDrive#727]
Sometimes it happens that you move a target point instead of folding up/in a folder.
Maybe on button can be moved in front of the folder name to avoid this problem.

Manchmal passiert es, das man einen Zielpunkt verschiebt anstatt einen Ordner auf- oder zu zuklappen.
Vielleicht könnte man einen der Button vor den Ordnernamen verschieben.

**Comment by Woife1** [comment]
Wie wäre es das Ziele verschieben nur möglich zu machen wenn man im Editormodus ist?

**Comment by Stephan-S** [comment]
Da es schneller und einfacher ist, übernehme ich hier @Woife1 's Vorschlag. Das klingt sowieso sinnvoll und wurde glaube ich auch schon mal angemerkt :-)
@Iwan1803 reicht dir das ? Vielleicht noch etwas mehr Abstand zwischen den Buttons? Aber komplett auf die andere Seite zerreisst mir das HUD wieder etwas finde ich

**Comment by Iwan1803** [comment]
Das reicht mir aus. Mir geht es nur darum, das das versehentliche Verschieben ein Ende hat.

**Comment by Woife1** [comment]
@Stephan-S ein bischen Abstand zwischen den 2 Pfeilen schadet auch nicht
