### ISSUE TITLE
Multiplayer - Synchronisierung anzeigen

### ISSUE THREAD

**Issue by WestfalenerAgrarvideos** [Stephan-S/FS19_AutoDrive#728]
Moin,

Wie haben das Problem das wenn wir fertige kurse auf unsern Server Laden. Lädt er diese nicht richtig
Ich habe die bereits eingefahrenen Kurse von Modhoster importiert.
Im Singleplayer funzt es tadellos, im Multiplayer scheint er immer wieder auf´s neue die Kurse neuzuberechnen?!?

Hab auch schon verschiedenen Versionen von AutoDrive getestet.

Bitte um hilfe bin echt am verzweifeln.

**Comment by Stephan-S** [comment]
Servus,

sobald sich ein neuer Spieler auf den Server verbindet werden alle Kurse neu vom Server aus mit allen Spielern synchronisiert.
Das sieht dann bei jedem Spieler so aus, dass erstmal alle Punkte verschwinden und nach und nach, so wie die Pakete vom Server eintreffen (und von allen Spielern als empfangen zurückgemeldet werden) werden mehr Punkte angezeigt.
Die Ziele werden alle zusammen im letzten Paket übertragen und sind also erst am Ende dieses Prozesses wieder vorhanden.

Das Ganze kann sicherlich noch optimiert werden. Aber das bedeutet viel Arbeit und vor allem sehr viel Testaufwand, den ich aktuell nicht für eine reine Optimierung investieren kann.

Also nach dem ein neuer Spieler / Du dich verbunden hast, einfach mal ein paar Minuten warten, bis alles synchronisiert ist (Naja gut eine Anzeige dass das gerade passiert sollte ich noch einbauen) warten.

Wenn es danach Probleme gibt, einfach nochmal melden.

**Comment by WestfalenerAgrarvideos** [comment]
Mh ok ich probier es heute Abend noch mal aber als ich das getestet habe war ich komplett alleine auf dem Server.
Ich teste das heute noch mal und warte ma so 10 min bevor ich dann was mache

**Comment by WestfalenerAgrarvideos** [comment]
So ich hab es jetzt noch einmal getestet Version 1.0.6.6.
Test 1
Habe den Kurs in den savegame ordner gepackt auf dem Server hochgeladen.
Server gestartet.
Bin auf dem Server gegangen und hab mich in einen Tecker gesetzt und habe 30min gewartet. (War alleine auf dem Server kein anderer konnte rein kommen)
Immer noch das gleiche Problem.
Ich kann keine Haltepunkt auswählen und das Steckennetz wird immer wider neu geladen also die Linien verschwinden und kommen neu wieder.

Test 2
Kurs vorher in meine Farming Simulator ordner FS19_AutoDrive_Import kopiert
Savegame ohne Kurs hochgeladen
Server gestartet.
Bin auf den Server gegangen und hab mich in einem Trecker gesetzt. Habe dann mit offenen AD fenster die Tasten Strg+Alt+1 gedrückt.
Da waren dann wohl alle Punkte da aber Ich konnte keine Ad einstellen und sobald ich was ergänzen wollte also eine Route erweitern waren alle linien weg und kamen auch nicht wieder.
Wartezeit auch 30min

Was mache ich falsch?

**Comment by WestfalenerAgrarvideos** [comment]
Bekommt man hier auch noch mal eine Antwort

**Comment by Steffen878** [comment]
Habe das selbe Problem. Vermute das es an der Größe der Datei liegen könnte.

**Comment by Stephan-S** [comment]
So, 
heute komme ich mal dazu den MP zu testen.
Könnt ihr mir mal kurz eure Kursdatei schicken die nicht funktioniert?
Danke

**Comment by WestfalenerAgrarvideos** [comment]
Das sind die Kurse von der NF Marsch 4fach V1.1
[AutoDrive_NF_Marsch_4fach_V1_1_config.zip](https://github.com/Stephan-S/FS19_AutoDrive/files/3800282/AutoDrive_NF_Marsch_4fach_V1_1_config.zip)

**Comment by WestfalenerAgrarvideos** [comment]
Besten dank es läfut jetzt Danke danke danke

**Comment by Steffen878** [comment]
darf ich fragen was ihr gemacht habt, das es jetzt geht

**Comment by Stephan-S** [comment]
Na klar darfst du das :-)

https://github.com/Stephan-S/FS19_AutoDrive/commit/3ac0f50b8fcffebb52f0d9411f54570c89eb50dc

**Comment by Stephan-S** [comment]
Ein neues Release mache ich spätestens morgen fertig.
In der Zwischenzeit kannst du dir selber eine zip aus dem aktuellen Repository bauen und nutzen

**Comment by Steffen878** [comment]
Dumme Frage und wie?

**Comment by Steffen878** [comment]
ok habe jetzt die Version 1.0.6.6c

**Comment by Steffen878** [comment]
Er zeigt mir jetzt alle Haltepunkte an, kann ihn aber nicht starten.

**Comment by Steffen878** [comment]
Super. Es funktioniert!!!! DANKE

**Comment by Steffen878** [comment]
Er hat scheinbar Probleme beim Abladen

**Comment by Steffen878** [comment]
Kurze Info
Drescher abtanken: Fahrer fährt gegen Drescher
Einige Abladepunkte lädt er nicht ab
Aufladepunkte gehen bis jetzt ganz gut

**Comment by Steffen878** [comment]
Ich teste weiter

**Comment by Steffen878** [comment]
Was mir gerade auffällt das die Haltestellen teilweise verschoben sind
