### ISSUE TITLE
Still problems in MP on Dedi Server.

### ISSUE THREAD

**Issue by Roby1164** [Stephan-S/FS19_AutoDrive#73]
Unfortunately, the problems in MP continue, this morning I was trying to make new tracks, and everything seemed to be going well, but then, in creating a new unloading point, at a sales point, the game stopped, and now trying to get back, after a few seconds it stops, I have to wait tonight, when there will be the administrator of the server, to check the log and unlock the game, removing the mod ..
I can't understand where the problem is, in the MP game, we don't have many mods, the map and original, of functional scripts, we have the GPS mod, the RealDirt, Ai Vheicle Extension and the TSXEnhancedVehicle, which until now have not given problems.

**Comment by Stephan-S** [comment]
If you get the logs, please post them here, so I can identify the problem! I am always playing on a dedicated server and I currently have zero issues with the mod. So I am really interested in the log file. Thank you

**Comment by Roby1164** [comment]
I think I found the problem, it was another mod, strange that though the AutoDrive, we never had any blocks !!!
This is the incriminated part of the log:
2019-04-18 10:02 Roby joined the game
2019-04-18 10:02 Error: Running LUA method 'packetReceived'.
2019-04-18 10:02 d: /servers/service14325/home/games/FarmingSimulator19/mods/FS19_Autoloadpack/scripts/easyAutoLoader.lua: 726: attempt to index field 'markerObject'
2019-04-18 10:02 Error: Running LUA method 'packetReceived'.
2019-04-18 10:02 d: /servers/service14325/home/games/FarmingSimulator19/mods/FS19_Autoloadpack/scripts/easyAutoLoader.lua: 726: attempt to index field 'markerObject'
2019-04-18 10:04 Roby left the game

**Comment by Stephan-S** [comment]
Hey, I'm, glad you found the error. I checked the code of the Autoloader and could not find any reason that the AutoDrive mod had anything to do with it. Seems like there is merely a 'nil' check required to prevent this error in the AutoLoader mod. Although I can't see why it is necessary to be honest. But then again. It is not my mod.

**Comment by FS-UK-TheMan1988** [comment]
when i play with friends on my ded. server.

it starts to lagg when we use AD
