### ISSUE TITLE
CP worker still use wage from AD

### ISSUE THREAD

**Issue by bojanh66** [Stephan-S/FS19_AutoDrive#730]
As the title say.
Even if i put driver wage to 0% in options, it still use money.
When i disable AD during mod selection, it works fine.

**Comment by Stephan-S** [comment]
I don't really see how that is possible.
Here is the current code, which is the only section that has anything to do with wages or money in AutoDrive:

https://github.com/Stephan-S/FS19_AutoDrive/blob/bded0a740e67e680a57834f81ca69511974485db/FS19_AutoDrive/scripts/AutoDrive.lua#L475-L483

So as long as AutoDrive is not active, it never reaches any code that deducts money from your account.
And if AutoDrive is active, it will only deduct what you set in the settings.
The minus 1 here is to offset the base cost of any AI driven vehicle.

I don't know how Courseplay handles the driver wages, but this is the only part of AutoDrive related to wages.

**Comment by bojanh66** [comment]
I am sorry, after lots of testing and enabling/disabling AD,CP and AIVE, i found that its a bug in CP.
It conflicts somehow with normal worker wage :/
