### ISSUE TITLE
Driver doesn't properly stop at last waypoint and drives circles

### ISSUE THREAD

**Issue by Iwan1803** [Stephan-S/FS19_AutoDrive#733]
Hallo @Stephan-S 
beim Drescher abtanken taucht eine Zeile auf, die mit "ahre abladen" anfängt, wenn er zum Drescher fahren will. Darf ich dir das fehlende "F" schenken? 😄 
Außerdem reagiert der Abfahrer bei sehr großen Feldern teilweise gar nicht auf das Signal vom Drescher. Ich habs per Rohr probiert und auch per Tastenkombi, aber selbst nach 5 Minuten fuhr er nicht los, obwohl er den o.g. kurzen Satz angezeigt hat. Auch eine Neuberechnung der Routen brachte keine Besserung.
Und ja, er steht schon am Abfahrpunkt. Warum dieser dann grün angezeigt wird, kann ich nicht sagen.
![fsScreen_2019_10_30_17_53_33](https://user-images.githubusercontent.com/47528836/67880143-6d314380-fb3e-11e9-82d7-23d782666b90.png)

*update*
Nachdem ich ich nun einmal entladen habe und dann wieder auf den Kurs gesetzt habe, hat er nun den Drescher auch abgetankt. Allerdings ist das Feld so groß, das er meistens den Weg zum Abfahrpunkt nicht mehr findet.

*update²*
Er fährt entladen, kommt zurück, kann den Drescher finden und abtanken, fährt zum Abfahrpunkt zurück und findet den Drescher danach scheinbar nicht mehr wieder.

**Comment by Iwan1803** [comment]
Es fehlt übrigens auch ein "E" bei "ntlade Drescher".

**Comment by Iwan1803** [comment]
@Stephan-S 
gibt es hierzu schon etwas neues? Auch mit der aktuellen Version fährt der Trecker über den Werkstattpunkt drüber und macht dann den Kreisel.

**Comment by Stephan-S** [comment]
@Iwan1803 Ich konnte das Problem mit dem Werkstattpunkt noch nicht nachstellen. Ich lasse das mal so lange offen bis ich was Nuees weiß

**Comment by Iwan1803** [comment]
Ich hab es übrigens nicht nur am Werkstatt-Punkt, sondern auch am Heizkraftwerk, der Gärtnerei und an noch 1 oder 2 Punkten.
Mal fährt er direkt über den Punkt hinweg und fängt dann an zu kreiseln oder er hat am Punkt gehalten, abgeladen und gleich nach dem Losfahren geht das Chaos los.

**Comment by Stephan-S** [comment]
Hey, kannst du mir ein komplettes Savegame zukommen lassen, inklusive Mods die du nutzt?
Ich weiß das ist etwas aufwendig, aber ich kann das Problem bisher nie nachstellen bei mir. Bzw ich konnte es noch nie beobachten.

**Comment by Iwan1803** [comment]
Das Savegame ist nicht das Problem, aber mein Mod-Ordner ist über 2,5 GB groß.
Ja, ich weiß, ich sollte mal aufräumen...
Kannst du vielleicht irgendwie was einbauen, was ein Log generiert, wenn ich einen Zielpunkt anfahre oder kann ich selbst was "aktivieren"? Es tritt ja hauptsächlich auf Feldern auf, wenn der Abfahrer mit dem Abtanken fertig ist oder wenn ich meinen Werkstatt-Zielpunkt anfahre.

**Comment by Iwan1803** [comment]
Neue Erkenntnis: das Problem mit dem Kreiseln taucht hautpsächlich bei meinen Abfahrer auf, welche alle aus folgender Kombi bestehen:
- Trecker: Fendt Vario 939
- Anhänger: Strautmann Aperion 3401

**Comment by Stephan-S** [comment]
Im Feld oder an regulären Zielpunkten?
Auf dem Feld ist es ja prinzipiell eine ganz andere Thematik und betrifft den Pfadfinder.
Auf der normalen Strecke ist es ein noch unbekanntes Problem.
Standard Fendt oder ein Mod? Möglicherweise ist ein ähnliches Phänomen wie #715 
Dann sollte ich mal versuchsweise die minDistance (ab der er akzeptiert/erkennt das er einen Wegpunkt erreicht hat), etwas hochdrehen bzw, dynamisch an die Fahrzeuglänge anpassen.

Auf dem Feld sollten die Dreher aber auch wieder etwas reduziert sein. Habe heute morgen nochmal einen fiesen Bug gefunden, der dafür sorgen konnte das gerade kurz vorm Drescher ein unmöglicher Winkel verlangt wurde

**Comment by Iwan1803** [comment]
Die o.g. Kombi besteht soweit rein aus dem Standard. Am Drescher habe ich zwar vorne ein Mod-Gewicht angebracht, aber auch ohne oder mit einem Standardgewicht tritt das Problem auf. GlobalCompany hat den Anhänger wohl lediglich um die zusätzliche Erntesorten erweitert.
Auf dem Weg zum Drescher passiert es eher unregelmäßig und nicht rekonstruierbar. Man sieht die weiße Linie und er kreiselt um den Startpunkt von dieser Linie. Vielleicht ist der Wendekreis zu klein berechnet, kA.
An Zielpunkten kreiselt er häufiger und das betrifft hauptsächlich ein paar bestimmte Felder und ganz besonders oft meinen Werkstattpunkt. Dabei scheint es auch keine Rolle zu spielen, ob der Abfahrer eine lange oder kurze Anfahrt hatte.

**Comment by Iwan1803** [comment]
*update*
Ich hatte es gerade am Werkstattpunkt mit einem Deutz (Mod) mit Ladewagen (Mod) als auch mit einem Case Puma 240 (Standard) mit Bredal-Düngewagen (Standard).

**Comment by geo-luchs** [comment]
Kannst du bitte mal Screenshots machen? Auf normalen Routen beim Abladen oder auch Parkplätzen habe ich sowas noch nicht erlebt dass er auf einmal Kreise gefahren ist.

Wenn er mal merkwürdig gefahren ist , hatte ich zwischendurch mal irgendwo Wegpunkte gelöscht.
Dann habe ich alle Fahrzeuge angehalten , neu berechnen lassen, ind dann sind alle wieder ordentlich gefahren.
Nur wenn er aufm Feld mit CP arbeitet und an AD übergeben wird, dreht er teilweise endlos Kreise weil er nicht gerade auf die AD Strecke kommt.

Würde bei mir mal versuchen dein Problem nachzustellen.

**Comment by Iwan1803** [comment]
Ich habe @Stephan-S schon meinen Spielstand gegeben, weil er sich das auch nicht erklären kann.
Du kannst dir die Probleme gerne in meinem Live-Stream bzw. den Videos anschauen. Im letzten ist es regelmäßig passiert, das Abfahrer kreiselten oder an einem Zielpunkt vorbeigefahren sind und dann in den Kreiselwahnsinn verfallen sind.
Dabei passiert es an den Zielpunkten mit unterschiedlichen Trecker-Anhänger-Kombis, wobei meine Abfahrer alle identisch sind (wie oben beschrieben). Ich habe diese auch schon mal gelöscht und neu gemacht, aber es ändert nichts.
https://youtu.be/79tmWS-Yvnw

**Comment by geo-luchs** [comment]
Danke für den Video Link . Werde ich mir mal anschauen.

**Comment by geo-luchs** [comment]
Hi Iwan

äähmm, darf ich mal nen Einwand geben? Ein Livestream von 2,5h, da hättest Du mir schon mal die eine oder andere Zeitstelle nennen können. 
Ganz ehrlich? 2,5h Meckerfreitag anhören ist nicht spaßig .

Das der Abfahrer auf dem Feld nicht zum Drescher fährt ( bei ca. 1h:27/28 min) :  
Seit CP 320 ist die Funktion ja integriert, dass CP vorm Ende den Abfahrer ruft, dieser den Drescher abtankt, und dann sogar die Ladung zum Silo bringt.
An der besagten Stelle ist dein CP beim Drescher allerdings gar nicht aktiv. Somit kann AD vermutlich auch gar nicht erkennen, dass der Drescher wartet. AD erkennt einen speziellen Status vom CP.
 
Zumindest so habe ich das mit CP&AD verfolgt, da genau dieses Abtanken ein Request von mir war.

Das Kreisen am Werkstattpunkt oder anderen Zielpunkten suche ich noch.
Sorry, mir kreiselt im Moment mehr der Kopf von deinen wiederholten Erzählungen im Stream, was alles nicht geht, ohne dass Du das auch bildlich zeigst (zumindest nicht den eigentlichen Werdegang zum Problem).
Das erschwert es ungemein.

Bei 24/25 min: so etwas habe ich bei mir auch noch nicht gesehen, dass er da auf die grüne Linie einbiegt, und auf einmal stehenbleibt.

Das deine Fahrzeuge woanders stehen:  Das hat FedAction auf seiner NF Marsch auch des öfteren , dass in der einen Halle einige Sähmaschinen sich heimlich bewegt hatten. Und da hatter er noch GAR KEIN AD aktiviert. Das ist in einer der alten Hallen, die Du nicht hast. 


OK, das Kreisen bei 29 min habe ich auch. Das kann ich bestätigen. Ich vermute genauso wie Du, dass er das mit dem Wendekreis nicht hinbekommt.


Bei 32 min:  da wäre interessant, von wo der Abfahrer überhaupt gekommen ist. Er ist ja leer und er sollte zu "Feld 19 Abfahrer".  Leider sieht man fast nie den gesamten Werdegang.
Wenn er von der Strasse gekommen ist, dann würde ich auch erwarten, dass er einfach von dort wartend zum Drescher fährt.

nur eine Vermutung:  Falls er aber, warum auch immer, vom Feld 19 gekommen ist, um zum Wartepunkt "FEld 19 Abfahrer" zu fahren, dann ist es klar dass er in den Graben fährt. Denn AD berechnet vermutlich nur den Weg direkt zum Wegpunkt "FEld 19 Abfahrer" und versucht einen Kreis hinzubekommen. Links und rechts vom Wegpunkt ist aber der Graben.

**Comment by Iwan1803** [comment]
Sorry, hätte die Stellen raussuchen sollen, aber da war ich noch auf Arbeit....
Und ja, war wohl ein bisschen viel Gemecker, aber nach den Cheat-Vorwürfen durch einen anderen Streamer, gepaart mit meiner Grippe und den aufgetretenen Problemen musste an dem Tag einfach mal alles raus 🙄

Wenn der CP-Drescher das Ende vom Feld erreicht hat, ruft er den Abfahrer. Ist dieser nicht da, geht der Ruf aber scheinbar manchmal ins Leere und selbst wenn der Abfahrer zurückkehrt, fährt er dennoch nicht immer zum Drescher. Daher beende ich zur Zeitersparnis CP an der Stelle, fahre das Rohr aus und rufe dann den Abfahrer per Tastenkombi (was ich aber nicht immer im Stream ansage).

Das die Fahrzeuge sich scheinbar geisterhaft bewegen, scheint dann ja eher ein Map-Problem zu sein, wenn es FED auch schon ohne AD hatte. Ist nicht weiter tragisch, aber bei sowas rebelliert mein innerer Monk immer ein wenig 😄

Das bei 32 Minuten habe ich bei einigen Feldern immer wieder mal. Dabei spielt es keine Rolle, ob er vom Feld oder vom Hof kommt. AD ist bei mir so eingestellt, das er die nächste Ausfahrt vom Feld nehmen soll, aber ich bin mir nicht sicher, was genau das nun bedeutet und wie er die nächste Ausfahrt findet oder wie man eine Feldausfahrt überhaupt definieren kann. Manchmal fährt er auch zwischen Bäumen durch auf die Straße, wo definitiv keinerlei Ausfahrt ist.

Vielleicht muss ich bei einigen Feldern mal den Abfahrerpunkt weiter aufs Feld verlegen, aber dann steht er auf jeden Fall bei mind. 1, eher 2 Vorgewenden im Weg.

Sobald mein Inet wieder zuverlässig stabil läuft, werde ich noch mal einen Stream machen und dann auf die Probleme und den Werdegang deutlicher hinweisen. Das Kreiseln am Werkstattpunkt lässt sich mit meinen Abfahrer relativ zuverlässig rekonstruieren 😉

**Comment by geo-luchs** [comment]
Hi
Dieser Text lässt sich wesentlich angenehmer lesen 😉.

Das der Abfahrer nicht immer den Pfad zum Drescher findet und deshalb nicht losfährt , kenne ich auch. Das manuelle Rufen habe ich noch nie gemacht. Ich fahre eher den Abfahrer näher ran, und starte AD wieder.

Also : nächstgelegene Punkt bedeutet, er nimmt den Punkt, wo die rote Linie vom Traktor hinzieht.
 Wenn ich Holger richtig verstanden habe, sind genau dafür die blauen Linien, die nur zu einer Ausfahrt führen. Man kommt aber nicht von außen auf die blaue Linie.
Aber ich denke ich hatte ein ähnliches Verhalten auch mal, wo er relativ schnell in einem 90° Winkel auf die Linie zugefahren ist, und er dann nicht schnell genug die Kurve bekommen hat. Erst mal drüber kann er schon im Graben sein, und kommt dann in einen Kreis,  wo er nicht mehr schafft auf die Linie zu kommen.


Dann gibt's noch hinterm Start, oder Standard, dass ist der Startpunkt selbst, glaube ich.
Die letzten beiden funktionieren bei deinem Feld 19 Abfahrer gar nicht, weil die grüne Linie dort endet.
Er will eigentlich dabei versuchen, dort weiterzufahren, aber natürlich in der entsprechenden Richtung der Grünen Linie.


Iwan, ein Vorschlag von mir, weil ich diesen Issue auch etwas zerschrieben habe, und auch von Dir diverse issues  hier zusammengefasst wurden:
Können wir diesen schließen  und du schaust mal,  1 oder 2 neue einzeln zu öffnen, falls sie nicht schon existieren?
Das mit den fehlenden Buchstaben z.b. hatte ich eh nicht mehr gesehen in der neuesten Version, glaube ich zumindest.
Du meintest du bist auch Programmierer.
Meinst du nicht auch, dass Stephan bei DIESEM Issue hier keine Chance mehr hat, noch durchzublicken, was tatsächlich noch ein Fehler ist?

**Comment by Iwan1803** [comment]
Wie schon gesagt hat Stephan von mir meine AD-Config und meinen Speicherstand in Discord bekommen. Er hatte nur am WE keine Zeit mehr, sich das auch noch anzusehen.

@Stephan-S 
Falls du noch was an Infos brauchst, dann schreib mich in Discord an.
Ich mach dann erstmal hier zu.
