### ISSUE TITLE
Help display option not working

### ISSUE THREAD

**Issue by Dzi4d3k** [Stephan-S/FS19_AutoDrive#735]
It seems that this option:
![AD_help_1](https://user-images.githubusercontent.com/12050055/67892724-9f9a6b00-fb55-11e9-8ad8-7f01e33479ca.png)
is not working for me:
![AD_help_2](https://user-images.githubusercontent.com/12050055/67892737-a88b3c80-fb55-11e9-8737-75f5f81498c3.png)
as help entries stay regardless of setting.

**Comment by Woife1** [comment]
if you turned it off go out of your current car and go back in again the help should be gone then

**Comment by Dzi4d3k** [comment]
Indeed, that helps. Thank you for pointing this tip. I'm ashamed that I didn't figure it out :-)
