### ISSUE TITLE
Claas DLC - Driver can't calculate path.

### ISSUE THREAD

**Issue by eddiem54** [Stephan-S/FS19_AutoDrive#739]
Good evening Stephan,
I'm having an issue trying to unload combine, DLC tractor tries and fails to find route. Changing to standard in-game tractor works.

![fsScreen_2019_10_30_21_45_11](https://user-images.githubusercontent.com/2765885/67903497-a6c87580-fb63-11e9-9be6-2dd1e2f6f74d.png)
![fsScreen_2019_10_30_22_12_32](https://user-images.githubusercontent.com/2765885/67903505-ac25c000-fb63-11e9-8771-5fb4163f9314.png)

[log.txt](https://github.com/Stephan-S/FS19_AutoDrive/files/3791327/log.txt)

Regards.

**Comment by Woife1** [comment]
Try set time for path calculation to 2x

**Comment by Stephan-S** [comment]
I tested the Claas Arion 460 and it generally works. So this was probably another issue.
Or due to the rather large field a problem with the calculation time as @Woife1 suggested.

**Comment by Stephan-S** [comment]
If the problem persists with the Claas tractor, please reopen this issue. Otherwise I will close it for now since I couldn't confirm the bug
