### ISSUE TITLE
Beschreibung der Änderungen

### ISSUE THREAD

**Issue by siggiblue** [Stephan-S/FS19_AutoDrive#74]
Hallo Stephan,
es wäre vielleicht ganz hilfreich, wenn bei einem neuen Release-Stand eine kurze Beschreibung in einem Textfile dazu legen würde. Besonders wenn es um neue Funktionen geht; was sie tuen, welche Tasten etc.

Ansonsten läuft alles ziemlich gut, bis auf die bekannten Sachen wie Abfahrer und Drescher

**Comment by Stephan-S** [comment]
Servus siggiblue,
ich habe leider einfach nicht die Zeit (und Muße) das auch noch bei jedem Release beizufügen.
Ich probiere bei den Commit-Nachrichten die man hier im Github nachlesen kann, relativ deutlich zu beschreiben was ich geändert habe. Ich hoffe das hilft meistens weiter.
Ansonsten werde ich, wie beim Drescher abfahr Modus, auch sicher wieder ein Video hochladen, wenn eine große Neuerung dazu kommt :-)
