### ISSUE TITLE
Abfahrer bleibt im Feld stehen

### ISSUE THREAD

**Issue by Moitzbert** [Stephan-S/FS19_AutoDrive#740]
Abfahrer bleibt im Feld stehen obwohl parken im Feld auf Nein gestellt ist. Kann mir jemand weiter helfen ?

Mfg Christof

**Comment by Iwan1803** [comment]
Ist es ein sehr großes Feld und er findet den Weg raus nicht mehr?

**Comment by Moitzbert** [comment]
Nein den Weg findet er. Wenn ich auf ‚weiterfahren‘ klicke fährt er zum Startpunkt zurück.

**Comment by Moitzbert** [comment]
Nein leider, der Abfahrer schiebt nach dem Abtanken ein Stück zurück und bleibt dann in der Frucht stehen. Das Problem ist, dass der Drescher dann in der nächsten Reihe von dem Abfahrer blockiert wird. 
Hab vorher auf der Candian Farm Map gespielt und dort hat es komischerweise funktioniert. 
Jetzt auf der NF Marsch 4fach klappt es einfach nicht.
Falls es bei euch funktioniert, könnte mir jemand seine Einstellungen (AD Abfahrer usw..) hier rein Posten ? 

Danke für die Antworten!

**Comment by Iwan1803** [comment]
Klingt für mich so, als ob Parken im Feld für diesen Abfahrer aktiviert ist.
Auf welchem Feld ist es denn?
Ich spiele die NFM 4x selber.

**Comment by Moitzbert** [comment]
Bewirtschafte derzeit Feld 1, 2, 14, 15 und 19 und habe das Problem bis jetzt auf allen Feldern. Könnte das Problem eventuell am Multiplayer liegen ?

**Comment by Iwan1803** [comment]
Du spielst also mit mehreren? Haben denn alle die gleiche AD-Version?
Tritt das Problem nur bei dir auf oder auch bei anderen?

**Comment by Moitzbert** [comment]
Ja wir spiele auf einem gemieteten Server, alle haben die 1.0.6.5 Version. Tritt bei allen auf.

**Comment by Iwan1803** [comment]
Dann solltet ihr mal auf die aktuelle Version wechseln.

**Comment by Moitzbert** [comment]
Ja werden wir demnächst machen, hoffe es klappt dann. Gib hier dann eine Rückmeldung.

**Comment by Wienet** [comment]
Hallo, ich habe auch das Problem, dass die Abfahrer nach dem Abtanken in der Frucht stehen bleiben und den Drescher blockieren. Mit der 1.0.5.8 funktionierte das noch, wie ich gestern getestet habe.
Auch passt der Abstand zum Abtanken nicht mehr und ich kann ihn nicht passend einstellen. Der Abstand variiert sogar zwischen von vorne und von hinten anfahren. Was läuft hier falsch???

**Comment by alex2ruote** [comment]
Hi, I have the same issue on Multimap. The truck stays in the same position after the unloading and the harvester crashes in it when it comes back.  Both Courseplay and Autodrive are updated to the last version available. Also, if the harvester backs up from the fruit, with the pipe opening and closing the truck gets "confused" quite easily, so I disabled the fruit protection option in CP and allowed the truck to drive in it, which is not an ideal thing, even if I don't have crop destruction enabled.

**Comment by Wienet** [comment]
And what's with the space between truck and harvester? Does it fit everytime or are there crashes?

**Comment by alex2ruote** [comment]
I only noticed that with a corn header the truck wouldn't get close enough to go underneath the pipe, but I haven't experienced crashes for a while now, other than the truck being stuck.

**Comment by Stephan-S** [comment]
Driver should now properly detect if he is standing in the fruit and act accordingly (either wait or drive back to start pos to park).
I close this issue now. If the problem still exists in the latest soruces, please reopen. Thank you!
