### ISSUE TITLE
Blue Line

### ISSUE THREAD

**Issue by Iab72** [Stephan-S/FS19_AutoDrive#742]
i can't record with the blue line, if i want to press two time to record with the blue line the icon <___> it don't appear

**Comment by Iab72** [comment]
Oh yes you must point the mouse course to the record icon and press the left mouse button.
Thanks

**Comment by Iwan1803** [comment]
https://github.com/Stephan-S/FS19_AutoDrive/wiki/5-Record-and-edit-the-network

> When the record button is clicked with the middle or right mouse button, it switches to a dual-way recording mode. This mode can be used to record ‘blue’ paths which can be driven in both directions.
