### ISSUE TITLE
Frage zu Drescher abtanken mit Claas Traktor

### ISSUE THREAD

**Issue by Corona01** [Stephan-S/FS19_AutoDrive#743]
Hallo Stephan,
Hallo Community,
Dondiego Map - Drescher Ideal, gesteuert mit AI.
Abfahrer Claas Xerion, gesteuert mit AD
Auf Feld 15 hat das Drescher abtanken einwandfrei funktioniert, auf Feld 50 klappt da nichts mehr.
Der Abfahrer steht und wartet auf den Drescher, der Drescher ist voll und wartet auf den Abfahrer und nichts tut sich.
Ist die selbe Situation wie vor dem Claas Fix von Stephan.
Versionen von AD, AI und Map sind allesamt die aktuellsten.
Muß dazu sagen das auch AI auf einigen Feldern Probleme hat die Spur zu finden.
Kann das auch an der Map liegen dass das abtanken auf einem Feld funktioniert und auf einem anderen wieder nicht ?

**Comment by Iwan1803** [comment]
Hast den Drescher so eingestellt, das sich nicht automatisch einen Abfahrer sucht?
Das führte bei mir schon mal zu Problemen, wenn auf einem Nachbarfeld ein weiterer Abfahrer war. Dies sollte aber mit der aktuellen Version und richtigen Einstellungen kein Problem mehr sein.

**Comment by Corona01** [comment]
@Iwan1803 
In AD ist Abfahrer finden auf Nein, in AI (damit wird der Drescher gesteuert) gibt es diese Option nicht.
Da ich die Map erst neu begonnen habe sind derzeit nur ein Drescher und ein Abfahrer unterwegs.
Habe es heute mit einem Fendt Abfahrer vesucht und es hat einwandfrei funktioniert, danach habe ich nochmal begonnen und wieder mit einen Claas Abfahrer, hat diesmal auch beide male funktioniert.
Vermutlich hat der Neustart des Games den Fehler beseitigt.
Abfahren mit Claas läuft jetzt einwandfrei.
