### ISSUE TITLE
1.0.6.6b: several error

### ISSUE THREAD

**Issue by Iwan1803** [Stephan-S/FS19_AutoDrive#747]
I've updated to the latest version and found some problems:

1. "Pipe Offset" was set for all vehicles to 5.0m, but i set them to 0.5m days ago

2. repeated error in log.txt:
> 2019-10-31 19:53 Error: Running LUA method 'update'.
2019-10-31 19:53 D:/Dokumente/My Games/FarmingSimulator2019/mods/FS19_AutoDrive/scripts/AutoDriveTrailerUtil.lua:886: attempt to call method 'getAllFillLevels' (a nil value)

**Comment by Iwan1803** [comment]
I downloaded the whole mod again and till now No. 2 is gone.

**Comment by Stephan-S** [comment]
Alright, thanks for the info.
I added negative pipe offset values which caused a shift in the used settings

**Comment by Iwan1803** [comment]
@Stephan-S 
Ok, der Fehler ist doch noch da und taucht auf, wenn man statt "Abholen & Abliefern" nur "Abholen" ausgewählt hat. Das Spiel hängt sich dann langsam aber sicher weg, bis nichts mehr geht.
Da fiel mir gerade auf, das 3x Gras in der Liste steht. Das 1. ist das aus dem Silo, das 3. scheinbar das von den Wiesen und Feldern und das 2.? 
![fsScreen_2019_10_31_23_51_34](https://user-images.githubusercontent.com/47528836/67991471-9da9d800-fc39-11e9-9574-646d89688470.png)

**Comment by Roling51** [comment]
Moin zusammen
Auch bei mir friert das Spiel ein wenn ich "abholen und liefern" Kurse aktiviere.
Spiele auf der Multimap ver. 2.3
[log.txt](https://github.com/Stephan-S/FS19_AutoDrive/files/3796697/log.txt)

Gruss Roling

**Comment by TobiHH78** [comment]
> I've updated to the latest version and found some problems:
> 
> 1. "Pipe Offset" was set for all vehicles to 5.0m, but i set them to 0.5m days ago
> 2. repeated error in log.txt:
> 
> > 2019-10-31 19:53 Error: Running LUA method 'update'.
> > 2019-10-31 19:53 D:/Dokumente/My Games/FarmingSimulator2019/mods/FS19_AutoDrive/scripts/AutoDriveTrailerUtil.lua:886: attempt to call method 'getAllFillLevels' (a nil value)

Kann ich bestätigen. Habe die gleichen Fehler in der LOG und das Spiel hängt sich auf.
Problem tritt bei mir auf, sobald ich den Modus "Abholen und Abliefern" auswähle.

**Comment by RalfGorden** [comment]
bei mir ist in der Version 1.0.6.6 alles eingefroren bin zurück zur 1.0.6.5 da geht alles wieder

**Comment by Stephan-S** [comment]
Der Fehler sollte in der aktuellen Version 1.0.6.6c nicht auftauchen.
Ein fertiges Release kommt vermutlich wieder am Ende des Wochenendes :-)

**Comment by RalfGorden** [comment]
vielen Dank werde  es gleich mal testen

**Comment by Roling51** [comment]
Habe den Fehler auch unter 1.0.6.6c. Version steht zumindest im HUD so.

> 2019-11-01 14:01 Error: Running LUA method 'update'.
2019-11-01 14:01 C:/Users/sschw_000/Documents/my games/FarmingSimulator2019/mods/FS19_AutoDrive/scripts/AutoDriveTrailerUtil.lua:809: attempt to call method 'getAllFillLevels' (a nil value)

**Comment by RalfGorden** [comment]
hab gerade getestet geht bei mir auch mit der 1 .0.6.6c nicht sehr schade  werde erstmal wieder die 1.0.6.5 nehmen 

2019-11-01 14:09 C:/Users/Ralf/Documents/My Games/FarmingSimulator2019/mods/FS19_AutoDrive/scripts/AutoDriveTrailerUtil.lua:809: attempt to call method 'getAllFillLevels' (a nil value)
2019-11-01 14:09 Error: Running LUA method 'update'.

**Comment by Roling51** [comment]
Ein erster kurzer Test = läuft

**Comment by Iwan1803** [comment]
Bei mir läuft es aktuell 👍

**Comment by RalfGorden** [comment]
mit der 1.0.6.5 läuft es bei mir auch super nur halt mit der 1.0.6.6 nicht ,  wird schon wieder werden

**Comment by worker2419** [comment]
Update auf 1.0.6.6c und 2 Stunden im Test, der Fehler ist nicht wieder aufgetreten. 3x Gras habe ich auch  in der Anzeige. MAP ist die Felsbrunn Edit by MC in der aktuellen Version.
![AD_01](https://user-images.githubusercontent.com/47278102/68046215-a2bf6380-fcdb-11e9-8c98-47c690299542.png)

**Comment by Stephan-S** [comment]
Ich mache hier mal zu. Das 3x Gras Thema wurde schon öfter angesprochen.
Hier handelt es sich um eine Unterscheidung von der Giants Engine her.

Ich habe mich noch nicht im Detail damit beschäftigt welcher dieser 3 Filltypes der ist, den man aus dem Silo entladen kann.
Es sind auf jeden Fall 3 verschiedene IDs dahinter, die alle auf der Karte in verschiedenen Zuständen des Grases vorkommen können.

**Comment by Iwan1803** [comment]
Wie oben bereits zum Gras geschrieben:
> Das 1. ist das aus dem Silo, das 3. scheinbar das von den Wiesen und Feldern und das 2.?
