### ISSUE TITLE
Proper mouse click handling

### ISSUE THREAD

**Issue by TyKonKet** [Stephan-S/FS19_AutoDrive#748]
@Stephan-S , maybe I understood why we have to delay the opening of dialogs to prevent glitches.
How do you handle the mouse inputs for the HUD?
Commonly the mouse click is defined as the sequence of two lower level events ( mouse button down & mouse button up )
So we should abstract all with 3 events:
1) Mouse button down on a HUD element
2) Mouse button up on a HUD element
3) Mouse click on a HUD element (only if previous events have been on the same element)

If you are just listening at the mouse down event, here is the problem because the following mouse up event triggers on the dialog/GUI and cause the loss of focus and even the 'onEnterPressed' event.
To be honest, in that case, even the delayed opening  of the GUI doesen't really solve the problem at all, because if the delta time between 'down' and 'up' is larger then the opening delay, the mouse button up event triggers again on the GUI.

_Originally posted by @TyKonKet in https://github.com/Stephan-S/FS19_AutoDrive/pull/746#issuecomment-548546821_

**Comment by Stephan-S** [comment]
That sounds very plausible.
I'm currently using the mouse button down event to trigger actions on the HUD.
So for a quick fix without much rework I can switch this to the mouse button up event.

But you are right, this should be properly handled by checking if both events occured on the same button.

**Comment by TyKonKet** [comment]
Yes switching to the mouse button up event can quickly fix the problem, at least until a mejor rework will happen.

P.S.
If you want, you can grant me some rights on this repo so that I can help you deal with issues.

**Comment by TyKonKet** [comment]
619f5ed0968347038a31c476a00afcbab7a2e0b9

**Comment by Iwan1803** [comment]
Da kein weiteres Feedback -> geschlossen.
Bitte mit der neuesten Version erneut versuchen und bei Bedarf ein neues Issue erstellen, danke!
_Since no further feedback -> closed.
Please try with the latest version and create a new issue if necessary, thanks!_
