### ISSUE TITLE
Can't creat 2 way path

### ISSUE THREAD

**Issue by Tritura2** [Stephan-S/FS19_AutoDrive#752]
Hey,

i cant create a violett 2 way path by recording.
When i am recording i can only use the one way path, the mode for 2 ways is gone.

**Comment by geo-luchs** [comment]
You have  already one of the newer versions of AD HUD.
You have to use right Mouse Button on the Record Button. 
Left is now 1 way only.
Right  is now 2way only

**Comment by Tritura2** [comment]
thanks :)
