### ISSUE TITLE
Would be nice if "Bunker silo"mode would be able load heap from ground

### ISSUE THREAD

**Issue by TyKonKet** [Stephan-S/FS19_AutoDrive#753]
I suggested it some time ago... also would be nice if "Bunker silo"mode would be able load heap from ground, not only from silo, but no idea if it is possible..

_Originally posted by @raxtor in https://github.com/Stephan-S/FS19_AutoDrive/issues/749#issuecomment-548591091_

**Comment by raxtor** [comment]
@Stephan-S Response to your question in #749 
CP has some ability load material from heap, but u have to define exact route for loading and unloading.. AD could only go to destination with heap where is waiting transport vehicle and than start similar job like bunker silo mode does. There is missing your genial 1 click magic solution :-)
