### ISSUE TITLE
AD im Multiplayer

### ISSUE THREAD

**Issue by Steffen878** [Stephan-S/FS19_AutoDrive#755]
ich habe den Savegame hoch geladen. Diesen habe ich im SP erstellt. Dort geht Autodrive ohne Probleme. Auf dem Server ist die gleiche Autodriveversion wie in meinem Pc. Wenn ich mich in den Server einlogge wird aber im Autodrive-Fenster keine Zielpunkte aufgeführt.
Die Streckenlinien sind aber sichtbar

**Comment by Onkel2000** [comment]
Versuchs mal im Editor-modus mit strg + alt + 2 . Musst wahrscheinlich erst deine kursdatei in Import Ordner von autodrive legen.

**Comment by Steffen878** [comment]
im Spiel?

**Comment by Steffen878** [comment]
Kursdatei ist im Importordner

**Comment by Onkel2000** [comment]
> 
> 
> im Spiel?

Ja.

**Comment by Steffen878** [comment]
Ich habe jetzt im Spiel mal die Tasten strg+alt+2 gedrückt. es passiert nichts

**Comment by Steffen878** [comment]
Es handelt sich um Multimap 2019 und die Kurse habe ich bei Modhoster runtergeladen. Die Datei ist ca. 60MB gross

**Comment by Steffen878** [comment]
Ich vermute einfach mal das die Datei zu groß ist.
