### ISSUE TITLE
1.0.6.6c: missing text / Texte fehlen

### ISSUE THREAD

**Issue by Iwan1803** [Stephan-S/FS19_AutoDrive#756]
Hallo @Stephan-S 
hast du aus Versehen Textbausteine gelöscht?
![fsScreen_2019_11_01_18_34_42](https://user-images.githubusercontent.com/47528836/68057307-c7c0d000-fcf5-11e9-816b-466977c70778.png)

**Comment by Dzi4d3k** [comment]
That's because @TyKonKet changed only EN and IT versions. I propose you to create pull request with DE, rather than creating new issue :)

**Comment by TyKonKet** [comment]
> That's because @TyKonKet changed only EN and IT versions. I propose you to create pull request with DE, rather than creating new issue :)

You are right bro, that's because I saw my boss working on EN & DE only so, since I'm lazy, I've changed only EN ;D

**Comment by Dzi4d3k** [comment]
That was suggestion for @Iwan1803, as anyone can help :)

**Comment by Stephan-S** [comment]
Don't you dare calling me your boss :D 
I'll get to the german translation tomorrow.
But I like your approach better.
Pasting the default english translations into aech file makes it easier for all translators and makes for a better user experience while translators catch up :-)

**Comment by Iwan1803** [comment]
Pasting new text params only in some language file is not the best way 😉
Before releasing such files all other translations should be done to avoid such unneeded "error".
Maybe next time f.e. an issue should be raised to get the needed translations and if i can help, i'll do it.

**Comment by raxtor** [comment]
@Stephan-S does it mean you will start paste EN text to all lang translatons? Cool, I have saved work :-) Just question.. isnt posssible use EN text by script when translation is missing instead of copy EN line to every single file? Just I want save your  wrok now :-)

**Comment by Stephan-S** [comment]
@raxtor Yeah, EN for everyone :-)
I think it makes it easier for the translators to provide the default translation, so I will go that route from now on.
I was also thinking about using the EN translation as backup in the code but I like the above approach better

@Iwan1803 Oh you are lucky you are playing the german version which I always translate myself :D This is the standard problem for all players in other languages :D 
And I add new translations every other day for one thing or another, so waiting for all translators to catch up before releasing the new feature is not ideal. I'll go with the default EN from now on :-)

**Comment by TyKonKet** [comment]
Okay I agree too, so if we decide do paste EN on all langs, I'll update my building tool to diff l10n files and make sure all languages are always updated.
Anyway this approach could prevent GIT, much more frequently, from making automatic merges.

**Comment by Bobster82** [comment]
Lol, if @Stephan-S reads my language update posts earlier then a few weeks, the dutch would be updated as well hahahaha. 
Still need to find out how to make a pull request, if someone can help would be nice ;)

and its a nice way to add eng to the missing text in all languages... so i dont have to check what is changed, just edit the english lines. thanks for that!

**Comment by raxtor** [comment]
@Bobster82 try this tutorial how to make pull request https://www.youtube.com/watch?v=rgbCcBNZcdQ

**Comment by Bobster82** [comment]
> @Bobster82 try this tutorial how to make pull request https://www.youtube.com/watch?v=rgbCcBNZcdQ

Thanks, I did my 1st pull... hope its ok ;)
The vid was 50% helpfull, as i dont use the command line for it

**Comment by Stephan-S** [comment]
Thanks to @Bobster82  and @raxtor
