### ISSUE TITLE
Autodrive on Load mode, wont refill fertilizer , bug? or Am I doing something stupid?

### ISSUE THREAD

**Issue by evansv2** [Stephan-S/FS19_AutoDrive#758]
I'm using 1.0.6.6c 

refills everything else but fertilizer and seeds
this is a sample video, But I tried empty, partially loaded , versions 5.7 this new 1.0.6.6c nothing seems to work, hope its me been dumb, I've even tried it on fresh loaded map with no mods, and it just does not want to reload the fertilizer nor seed

video
https://www.youtube.com/watch?v=YPTtFCrFPZQ&feature=youtu.be

**Comment by Iwan1803** [comment]
"Shop" is a wapyoint. Why should it stop at that bag?

**Comment by evansv2** [comment]
Why not? its the load mode used for refilling fertilizer , waypoint im guessing can be anything as long as it has some trigger to fill the fertilizer,  i tried it also on fertilizer tanks, doesnt fill anything, how you supposed to use the Load mode then ? I got it to work once, dont know how , but its just quit working

**Comment by evansv2** [comment]
here is another example, of a liquid fertilizer that wont refill, it slows down to 8kmh than picks up speed and dissapears into the abbys :) 


https://www.youtube.com/watch?v=UG6DLQ65eeI

**Comment by raxtor** [comment]
You can check trigger function by F1 menu. if R (refill) is active near bag or tank than AD shoud refill your device

**Comment by plexten** [comment]
Hi Stephan, leider funktioniert der Modus "Abholen" mit Version 1.0.6.6c bei mir auch nicht mehr.
Getestet mit GC FermenterSilo und Giants Fahrzeugen, am Giants HofSilo funktioniert es noch.

Google Translate:
Hi Stephan, Unfortunately, the mode "pick up" with version 1.0.6.6c does not work for me anymore.
Tested with GC FermenterSilo and Giants vehicles, it still works on the Giants HofSilo.

**Comment by evansv2** [comment]
> You can check trigger function by F1 menu. if R (refill) is active near bag or tank and you are able refill it manually than AD shoud refill your device. What I know AD has trouble with buyable triggers like moded silos etc and need map reload to register triggers correctly.. no idea if also it is problem for new bought bags and etc.

Yeah I just checked the R is definetley there

![image](https://user-images.githubusercontent.com/55886626/68070688-6f83df80-fd82-11e9-9635-9baeb45f31f8.png)

**Comment by evansv2** [comment]
BTW Courseplay seems to catch the Refill Trigger, 
but Autodrive just doesnt want to catch it, it actually slows down cause it knows the trigger is there, but for some reason, rght when it needs to make vaginal contact it just does not want to budge for nothing 

Courseplay example 
https://www.youtube.com/watch?v=fWfJaVASNgY

**Comment by raxtor** [comment]
"vaginal contact" - good one  :1st_place_medal:

**Comment by evansv2** [comment]
> "vaginal contact" - good one 🥇

Another way of saying it, sprayer does not want to make love to the liquid fertilizer )))

**Comment by raxtor** [comment]
I think "vaginal contact" for successful trigger contact would can become meme for AD and @Stephan-S will add it to [Wiki terminology ](https://github.com/Stephan-S/FS19_AutoDrive/wiki/2-Terminology):-)

**Comment by Stephan-S** [comment]
Pallets and big bags are not yet supported by AutoDrive.
You can only use LoadTriggers such as placeable refill stations.
I never have put much focus on supporting Pallets and BigBags since it doesn't quite fit into the AutoDrive Network in my opinion.
But nevertheless I will try to include them in the future

**Comment by evansv2** [comment]
> Pallets and big bags are not yet supported by AutoDrive.
> You can only use LoadTriggers such as placeable refill stations.
> I never have put much focus on supporting Pallets and BigBags since it doesn't quite fit into the AutoDrive Network in my opinion.
> But nevertheless I will try to include them in the future

Stephen could you please tell me which function in AutoDriveTrailerUtil.lua is reponsible for the load mode for the fill triggers, I'm gonna try to code it in myself , so it can also load from the bags

If you could pin point me in the right direction I would appreciate it

-Vlad

**Comment by evansv2** [comment]
BTW guys if anyone know which refill stations work I tried the following to no success 
![image](https://user-images.githubusercontent.com/55886626/68073785-dc0fd600-fda4-11e9-8da1-dcc604b553b7.png)

**Comment by evansv2** [comment]
Just a video reference, that its not loading from the  placeable refill station, this example is the liquid fert tank.
 

https://www.youtube.com/watch?v=ERK_6bD78GE

**Comment by Stephan-S** [comment]
Restart the game after placing the Station or Download the latest version

**Comment by evansv2** [comment]
> Restart the game after placing the Station or Download the latest version

Works great with the new version, Please I beg you, please include the bags and pallets!!! , because by the time I learn .lua I will be in,  bottom of a lake with a brick tied to my nuts, lol
