### ISSUE TITLE
Max Größe der Autodrive-Kurse

### ISSUE THREAD

**Issue by Steffen878** [Stephan-S/FS19_AutoDrive#760]
Wie gross darf die Datei der erstellen Kurse für einen Dediserver max sein?
Habe versucht eine Datei mit einer größe von 60MB (Für die Multimap 2019 geladen bei Modhoster) zu importieren. Leider ohne Erfolg. Die Strecken wurden zwar angezeigt aber nicht die wählbaren Haltepunkte.

**Comment by Stephan-S** [comment]
Hallo Steffen,
ich habe das Problem jetzt öfter hier gehört und schau mir das Ganze mal an.
MP Tests sind leider immer etwas aufwendig, daher mache ich so etwas nicht jeden Tag sondern höchstens mal an einem ruhigen Wochenende :-)

**Comment by Stephan-S** [comment]
Kann ich kurz einen Link bekommen? Die 60MB Datei finde ich auf die Schnelle nicht. Danke

**Comment by Bandesss** [comment]
Die Multimap Kurse haben ohne Editor 58MB
https://www.modhoster.de/mods/autodrive-kurse-fur-multimap2019
