### ISSUE TITLE
Fehler im AutoDrive

### ISSUE THREAD

**Issue by Engelchen1989** [Stephan-S/FS19_AutoDrive#763]
Guten Tag,
ich habe ein kleines/großes Problem und hoffe das mir hier jemand helfen kann.
Ich habe autoDrive bei mir auf dem FS19 Server und habe auch schon strecken eingefahren.
1. wenn ich Neues Ziel erstellen machen habe ich nicht alle Ziele in meiner liste wo ich mich dann frage wo sind die? Weil ist komisch auf der Map sehen ich sie aber im HUB nicht.
2. Wenn ich Ordner erstelle sehe ich die im HUB leider auch nicht und das bei der großen Karte die wir nutzen wäre das schon sinnvoll. 
Wir nutzen die NF Marsch 4Fach.
Über schnelle Hilfe würde ich mich sehr freuen danke schon mal im voraus

**Comment by worker2419** [comment]
@Engelchen1989 Hast Du mit dem Mausrad schon mal durch die Liste gescrollt? Schau bei den geschlossenen Fehlern, darin findest Du Antworten dazu.
![AD_01](https://user-images.githubusercontent.com/47278102/68070703-dcdb4480-fd71-11e9-8cfc-b0c1567fd2ed.png)

**Comment by Engelchen1989** [comment]
Die ziele finde ich nun aber die Ordner macht der mir immer wieder weg

**Comment by Iwan1803** [comment]
Sind in den Ordnern auch Ziele eingeordnet worden?

**Comment by Stephan-S** [comment]
Ordner erstellen und einordnen geht aktuell nur im SP.
Wenn du es dort erstellst und die Kurse auf den Server lädst kannst du sie dort aber so nutzen.
