### ISSUE TITLE
Mähdrescher Abstand

### ISSUE THREAD

**Issue by Bandesss** [Stephan-S/FS19_AutoDrive#766]
Hallo aktuellste Version von AD,
egal was ich einstelle ist der LKW zu weit weg vom Drescher
Eingestellt ist 0,75meter das hatte immer gut gepasst.
Anbei ein Bild, wie er steht trotz der einstellung.
![Drescher](https://user-images.githubusercontent.com/50829319/68071196-6ee64b80-fd78-11e9-8585-f517238c818b.jpg)

**Comment by Stephan-S** [comment]
Du musst die 0.75m beim Abfahrer einstellen, nicht beim Drescher.
Und der Wert muss dort stehen bevor er losfährt. Während der Fahrt hat es keinen Einfluss mehr

**Comment by Bandesss** [comment]
Hatte ich so eingestellt.... mit 0.75m passt es nicht mehr. 
Gestern gings noch

**Comment by Woife1** [comment]
probier mal nen paar Abstände aus 

bei mir funktioniert die Abstandseinstellung

**Comment by Stephan-S** [comment]
Sollte gefixed sein. Läuft auf meinem Testspielstand alles problemlos

**Comment by Bandesss** [comment]
Also neueste Version immer noch 0.75 eingestellt und es geht immer noch nicht.
komisch wenn ich ad auf den Server mache ist -4,75 eingestellt von Haus aus
WIr spielen auf einem Server im MP
![Unbenannt](https://user-images.githubusercontent.com/50829319/68086711-e4245000-fe4e-11e9-8e64-199bb85dd6bf.JPG)
![2](https://user-images.githubusercontent.com/50829319/68086716-f7cfb680-fe4e-11e9-883c-a470f3ce92ea.JPG)

**Comment by Stephan-S** [comment]
Eigentlich sollten die Settings auf den Server übertragen werden sobald du 'Ok' drückst.

Muss ich aber leider auf nächstes Wochenende verschieben. Vorher komme ich nicht zu erneuten MP Tests. Tut mir Leid

**Comment by Bandesss** [comment]
Alles klar, dann lasse ich mal Offen für eine Lösung.
Mein Fehler ist,  dass ich immer gleich aktuailisiere mit der Version 1.0.6.6 lief es bestens.

**Comment by geo-luchs** [comment]
Ist übrigens kein Fehler, wenn du immer gleich updatest  😉
Je früher jemand Fehler findet und meldet, umso besser .
Stephan kann nun mal nicht alles selbst finden , lösen, und auch noch testen.
Und je genauer es beschrieben ist, umso besser für Stephan.

**Comment by Bandesss** [comment]
Also Fehler ist immer noch aktuellste Version 1.6.0.7 
Rohr abstand auf einem Server passt nicht

**Comment by Bandesss** [comment]
Gibts was neues ?

**Comment by MartinPajak** [comment]
Gibt es zu dem Problem was neues oder eine Einstellung, die es ermöglicht den Drescher während der Fahrt abzutanken? 
In AD 1.1.0.4 sieht es immer noch so aus, wie auf dem Bild ganz oben.
