### ISSUE TITLE
Jenz BA 725 verursacht Fehler

### ISSUE THREAD

**Issue by 820fahrer** [Stephan-S/FS19_AutoDrive#767]
Hallo,

wir haben bei uns auf dem Dedi Server den Jenz BA 725 gekauft und daraufhin friert das Spiel ein.
Laut Log kann ich den Fehler auf den Jenz eingrenzen. 
Vielleicht sollte hier eine extra Prüfung erfolgen dass der anders behandelt wird.

Wie immer häuft sich der Fehler danach natürlich

Auszug aus der game.log des Servers.
Die Client Log wirft den gleichen Fehler aus.
> 2019-11-02 16:06 data/vehicles/jenz/jenzBA725/jenzBA725.i3d (17.73 ms)
> 2019-11-02 16:06 data/shared/wheels/trelleborg/T404/R22_5_T404.i3d (4.94 ms)
> 2019-11-02 16:06 data/shared/assets/lights/lizard/rear4ChamberLight_01.i3d (1.59 ms)
> 2019-11-02 16:06 data/shared/assets/lights/lizard/workingLightSquare_02.i3d (1.44 ms)
> 2019-11-02 16:06 data/shared/assets/lights/lizard/rearLightOvalLEDWhite_01.i3d (1.44 ms)
> 2019-11-02 16:06 Error: Running LUA method 'update'.
> 2019-11-02 16:06 C://gameservers//***//ls2019//gameProfile/mods/FS19_AutoDrive/scripts/AutoDriveCombineMode.lua:49: attempt to call method 'getIsBufferCombine' (a nil value)
> 2019-11-02 16:06 Error: Running LUA method 'update'.

**Comment by Iwan1803** [comment]
Welche Version von AD wird genutzt?

**Comment by 820fahrer** [comment]
Die vermutlich aktuellste: 1.0.6.6c
