### ISSUE TITLE
Maschinen können gefahren werden ohne Motorstart

### ISSUE THREAD

**Issue by 820fahrer** [Stephan-S/FS19_AutoDrive#770]
Hi,

hab noch einen Fehler gefunden.
https://ibb.co/sQDhp8P
https://ibb.co/gRV0Lm4

Fehler ist wie folgt reproduzierbar:
Wenn AutoDrive das Ende einer Transferroute erreicht hat kommt unten regulär die Meldung.
Geht man dann zum Fahrzeug oder tabbt rein kann man los fahren ohne den Motor zu starten. Auch nach dem aussteigen kann man weiterhin ohne Motorstart fahren.

Hab noch nicht ausprobiert ob das mit anderen Mods kollidiert. Motorstart ist ja mittlerweile ein Standardfeature.

Ist wieder auf nem Dedi Server passiert.

**Comment by geo-luchs** [comment]
AD scheint also automatisch den Motor beim losfahren anzuschalten, aber am Ende nicht mehr auszuschalten.  Jetzt wo ich es lese, ja das habe ich auch bemerkt

**Comment by geo-luchs** [comment]
it's fixed now.
Can not reproduced anymore with 1.0.6.8.

Please download release version 1.0.6.8
Bitte die Release version 1.0.6.8 herunterladen, damit wird sowohl der Motor als auch das Licht ausgeschaltet.
