### ISSUE TITLE
MP Reload after delete

### ISSUE THREAD

**Issue by rintiny2k** [Stephan-S/FS19_AutoDrive#772]
Would it be possible not to reload all the way points after each delete, it makes it take a long time to edit a path, We could do it manually after we have finished editing.

**Comment by TyKonKet** [comment]
@rintiny2k are you talking of MP?

**Comment by rintiny2k** [comment]
I should have mentioned that, yes in MP

**Comment by TyKonKet** [comment]
@rintiny2k are you talking of 'Way Points' or 'Targets / Markers / Destinations'?

**Comment by TyKonKet** [comment]
@Stephan-S , I have an idea to fix that on 'targets' with a small rework of them managment.
I think we should just sync the 'Create', 'Rename' and 'Delete' events of targets, without triggering the full Graph resync, this will give to all users an immediate feedback of changes.
The full Graph resync will happen only after the routes reloading, when all the changes will really takes effect.

I will try to implement that on a new brach, that should make the integration work and testing easier.

About 'Way Points' deletion, I think that routes recording (so way points creation) works well, and we should refer to that even for way points deletion.

**Comment by TyKonKet** [comment]
This has been fixed with 7b0cb03
