### ISSUE TITLE
CP can't load destinations from AD

### ISSUE THREAD

**Issue by Iwan1803** [Stephan-S/FS19_AutoDrive#773]
Moin @Stephan-S 
Da sich in CP nichts geändert hat, vermute ich das Problem mal in AD und zwar hängt sich das Spiel beim Laden eines Spielstands auf, wenn CP versucht, die Ziele von AD zu lesen:
> 2019-11-03 12:35 D:/Dokumente/My Games/FarmingSimulator2019/mods/FS19_CoursePlay6/course_management.lua:1714: attempt to call method 'GetAvailableDestinations' (a nil value)

Vielleicht liege ich mit meiner Vermutung auch falsch, aber kannst du da mal einen Blick drauf werfen?

**Comment by Stephan-S** [comment]
Ja, da hat unser neuer Mitarbeiter Mist gebaut und das Interface zu CP gelöscht weil er gesehen hat das wird ja in AutoDrive nirgendwo genutzt also muss es raus aus dem Code :D
Habs wieder eingebaut.
Da hst du dir aber echt zur falschen halben Stunde die Dateien neu geladen^^

**Comment by Iwan1803** [comment]
Das gibt aber Abzüge im Gehalt, oder? 😂
Dann lad ich noch mal neu runter und berichte dann, ob nun wieder alles klappt.

**Comment by evansv2** [comment]
Yea i was wondering why it dissapeared, then appeared in this fresh new version, nice to see that option back, CP does a poor Job thought because it goes full throtlle on all way points, vehicle flip over on turns, thats why I stick to Autodrive , and hope it improves

**Comment by Iwan1803** [comment]
@Stephan-S 
Funktioniert wieder, so das ich hier mal zu mache.

@evansv2 
 I've got no problems with CP and AD. Most of the time i'm using CP for fieldwork and AD for driving the routes between 2 targets (moving, pickup and deliver,...) and sometimes i'm using CP for driving on AD routes, which also works great.

**Comment by evansv2** [comment]
> @Stephan-S
> Funktioniert wieder, so das ich hier mal zu mache.
> 
> @evansv2
> I've got no problems with CP and AD. Most of the time i'm using CP for fieldwork and AD for driving the routes between 2 targets (moving, pickup and deliver,...) and sometimes i'm using CP for driving on AD routes, which also works great.

Yeah same here, I used to use CP to deliver as well, using routes from AD, but CP lays out those waypoints so screwed up, cars flip etc, AD is best for delivering, because of its speed change algorithm, if CP dont change this strategy on speedy crazy turns, AD will take over the field work LOL
