### ISSUE TITLE
Would love to see AD Unload Trailored Harvesters such as Rootster 604

### ISSUE THREAD

**Issue by evansv2** [Stephan-S/FS19_AutoDrive#774]
Would be nice, if AD could not only unload from the Full harvesters, but also from the trailored ones such as this 

![image](https://user-images.githubusercontent.com/55886626/68085574-69116880-fe53-11e9-8b51-16a7763a5902.png)

**Comment by TyKonKet** [comment]
ec4d142daa22602e9eaff9fe454946d6b558d267
