### ISSUE TITLE
[MP Dedicated Server] Stutters with multiple Players

### ISSUE THREAD

**Issue by PapaTim68** [Stephan-S/FS19_AutoDrive#775]
We play with 3 Players on Hof Bergmann on a Dedicated Server when using AD 1.0.6.6, while multiple Players are online the games begins to stutter for everyone. This happens when a driver is active, even when he is not driving. The stutter show in driving vehicles speeding up and coming to a full stop rapidly, during normal driving. Neither FPS nor Ping seem to be affected. Also there are no log messages generated on server or client. The server doesn't show any form of stress in ram/CPU usage during this time according to the Dedicated Server Interface

Grüße PapaTim68

**Comment by TyKonKet** [comment]
Did you noticed that only with 1.0.6.6 or even on previous versions?

**Comment by PapaTim68** [comment]
We didn't used it before 1.0.6.6 so i don't know.

**Comment by PapaTim68** [comment]
If I would like to test if this is Version related to which Version should I try to roll back to, to test it most efficiently? Other question is rolling back and keeping current network even possible?

**Comment by Stephan-S** [comment]
The network is independent of the version.
You might lose some new settings but they will revert to default when you upgrade again.

But I don't think this is version related. AutoDrive is quite heavy on the CPU and on your typical rented server you only get very little actual CPU power for the game.
Even if the driver is only waiting to be valled by the combine or filled up etc. there are still a lot of checks going on in the background that might result in these stutters.

I also noticed some network traffic that I can't yet determine the source of when AutoDrive is activated. This might also be an issue and I will look further into this topic when I get time.

@TyKonKet We could try approaching the network traffic topic next weekend if you feel like it.
It might be easier to work together on MP issues. It's always a hassle running two instances of FS. One on my PC and the other one on the Laptop :D

**Comment by PapaTim68** [comment]
Thanks for the reply I will test. As it only occurs if more than one player is online it shouldn't be CPU related, right? Just guessing.

**Comment by Dzi4d3k** [comment]
I suggest to test on dedicated server, as form my experience on other mods, if something works correctly on dedicated server then is works also on hosted multiplayer (the one when server is one of players).
Of course there can be differences in performance. Note that having two license it is possible to have own dedicated server without renting any game server form providers.

**Comment by Stephan-S** [comment]
The important thing is to also have to players present.
So when I test this alone, I would need 3 instances to test it on a dedicated server mode :-)

But we could go for this next weekend, yes.
@TyKonKet You are all alone this week. I will be away for work and only have some minutes/hours in the evening to work with the laptop in the hotel :D 
So not much progress on my site during the week.

**Comment by PapaTim68** [comment]
I was courios and made a test with wireshark. Driving around for 35sec on a Dedicated Server with and without AD active with intotal 3 active players. In package count alone there is a big increase in Driving with AD active.
without AD: 2464 Packets per 35sec
with AD: 9904 Packets per 35sec 
this is between me and the server, zip contains both wireshark outputs and a cpu graph for last 30 min

[Test_AD_dedicated.zip](https://github.com/Stephan-S/FS19_AutoDrive/files/3802098/Test_AD_dedicated.zip)

**Comment by TyKonKet** [comment]
@Stephan-S No problem, for our luck I have a dedicated server and two friends, If we find some free time we can start taking a look at during this week.

**Comment by Stephan-S** [comment]
Alright guys. Nice work.
@PapaTim68 This aligns with my testing (before initial modhub release)

So just as a quick summary of findings:
I reduced the amount of UpdateEvents AutoDrive sents to a bare minimum without having to put too much thought into which variables absolutely need to be synced between clients and server.
But event after doing that, the network traffic, which you can view ingame, increased for every AutoDrive driver.
And I could not relate this increase to any Events AutoDrive itself creates. So this must be related to existing events that AutoDrive triggers and which are then sent as a side effect.
My candidate would be the 'AIVehicleUtil.driveInDirection' which is also called with speed 0 when the vehicle is idle.

**Comment by V0LLMER** [comment]
I am not a huge help, but I have been trying to use AD on a dedicated server for quite awhile.  It seems to work a little better with older, more simple versions, but still has all of the same issues as stated above.

I have tried multiple versions.

Best of luck, and if I can be of any help, I am happy to do so.

**Comment by SnackyWell** [comment]
For me its delay also if you wish, if necessary I can send a video where you can see that the km/h goes up and down when the driver stops the km/h is stable

**Comment by V0LLMER** [comment]
For us, in multiplayer, we still use it, but only to haul grain.  You cannot do much of anything else while there is machines using AD, as it gets quite jumpy/laggy.  

I am happy to help test, if needed.

**Comment by TyKonKet** [comment]
I'm working to fix this issues, don't worry

**Comment by TyKonKet** [comment]
Hopefully the problem is solved, please guys test it and let me know.

**Comment by Mannie313** [comment]
[log.txt](https://github.com/Stephan-S/FS19_AutoDrive/files/3815318/log.txt)
 Neuestes Update.

MFG Mannie313

**Comment by V0LLMER** [comment]
Just an initial test, with myself, and one other, and a clear improvement.  
Quite smooth.  
This is just an initial test, and I'll test further, but I wanted to keep you updated.

**Comment by TyKonKet** [comment]
@V0LLMER OK, thanks, go ahead with your tests 😃

**Comment by PapaTim68** [comment]
From my testing Package count has about halfed, but sadly performance has not significantly increased for us. Will looking at the in game network traffic graph while ad is active there is an continued line of event package. This also continues in the lag phases will during lag every other traffic stops. I hope you can further investigate the problem.

**Comment by TyKonKet** [comment]
We have tested yesterday on a dedicated server and then on an hosted game, even with 40-50 vehicles runned by AD there was 0 lag.
Moreover, the continuous line of event packages is gone, even when AD is driving.
So, to be honest, I don't understand how you can still have this problem.

**Comment by PapaTim68** [comment]
okay thanks for Feedback i will have look. On ging is we are running seasons but that shouldn't be a problem. One thing did you have normal traffic enabled during testing?

**Comment by TyKonKet** [comment]
@PapaTim68 that's a good point, no I didn't tried with traffic enabled, unfortunately until tomorrow night I will not be able to try, if you can, let me know if you find differences between enabled traffic and disabled traffic.
Thanks in advance for the help.

**Comment by PapaTim68** [comment]
so I tested and enabled traffic and it changed a little bit there wasnt any lag but I'm not 10 sure it stayed like that even after reenabling traffic.
One thing just came to mind the changes were released in 1.0.6.7 right?

**Comment by TyKonKet** [comment]
No

**Comment by PapaTim68** [comment]
well than I know what I will do tomorrow... and I know why the event is still showing up... 
I get back to you when I tested with last commit

**Comment by TyKonKet** [comment]
ok

**Comment by V0LLMER** [comment]
This update certainly made things better.  There is still a little bit of lag while an autodrive vehicle is making a turn, or slowing down for a stop.  In addition, vehicles do not seem to kick themselves out of autodrive after reaching their destination, which will create a mild amount of lag.  If I jump in the vehicle, and back out of it the lag disappears, almost as if I needed to do that to end that vehicles autodrive process?

**Comment by TyKonKet** [comment]
I'll perform further investigations.

**Comment by V0LLMER** [comment]
I noticed that, if a machine has been used to drive an autodrive route, their "AD: machine title" stays on them on the minimap and main map.  Even if they are no longer running an AD route.  Even if you are driving it yourself.

**Comment by TyKonKet** [comment]
That should help with lag 03a4a7d2c37610ecc110b6c62423a903628fb6d2

**Comment by TyKonKet** [comment]
> I noticed that, if a machine has been used to drive an autodrive route, their "AD: machine title" stays on them on the minimap and main map. Even if they are no longer running an AD route. Even if you are driving it yourself.

af03c1282b3534e8653f0b5daa7ff26cc0281b02
