### ISSUE TITLE
Autodrive conflicts with Crane function on Xbox360 controller.

### ISSUE THREAD

**Issue by hakare4** [Stephan-S/FS19_AutoDrive#776]
When right trigger + left trigger + right thubstick is used (rotating and open/Close Crane) autodrive uses these commands for inputs and makes the functions unavailable for craning.

Encountered it with the Jenz woodchipper, but I guess that other cranes are affected as well.

**Comment by Woife1** [comment]
try to set no AD funktion on the controler in your gamesetting (where you set funktions on keys)

**Comment by hakare4** [comment]
Thanks, I didn't know that the mod controls landed in the game settings! I never use the controller to control AD anyways.

I accidentally removed my custom courses (quite a lot) for my Ravenport play when disabling AD for doing some chipping.
Just found out what file to backup for the future.

Still, an ingame function to disable/enable AD controls when using the controller would be useful.
