### ISSUE TITLE
Multiple waypoints and folders

### ISSUE THREAD

**Issue by jcmbennett** [Stephan-S/FS19_AutoDrive#780]
I know this is not so much an issue but I could not find a suggesting area. Would it be possible to make a mode like the normal drive to destination but with multiple destination waypoints? I use the lizard autoloader and a fleet of trucks to pickup from my many factories and deliver to various sell points. Being able to have multiple destinations selected would help greatly in automating this process.

Also, I play on a multiplayer server and just between a few of us we have a long list of waypoints with most of them being personal to each farm. If it would be possible to have a file tree structure for waypoints that would be amazing. 

This mod is amazing and I greatly appreciate the hard work you have put in. It has made my farming empire possible. :)

**Comment by Stephan-S** [comment]
Hey,

folders are already implemented but can currently only be edited in Singleplayer. But they can be used in MP as well if you upload the config file from your SP game.

Regarding multiple destinations: This is currently possible in the 'Pickup & Deliver' mode and can be set for each vehicle. It will then iterate over all unload destinations in the same folder.

So please update your AutoDrive version :-)

**Comment by jcmbennett** [comment]
Awesome and thank you for the quick response. I will give that a try. In the past I tried the pickup and delivery but with the autoloader already picking up product on its route to pickup destination, like down a line of greenhouses, it is already full and then makes a mess of pallets as it tries to then load. Updating my server with the new version now and will test it out.

**Comment by Stephan-S** [comment]
I never really work with autoloaders myself and I haven't used them to test any features yet.
Keep me updated :-)

**Comment by TyKonKet** [comment]
@Stephan-S what do you think if I add, as part of my MP sync rework, even the ability to edit folders in MP?

**Comment by jcmbennett** [comment]
With the autoloader no action is required at each destination as it will pick up anything it passes that it has been selected. This is way a simple multi destination option came to mind. I could tell a driver to drive to a-b-c-then park, so he get all the products at a and b, drops off at c then parks. All the pickup and drop off actions are performed by the autoloader so the autodrive only needs to handle driving to each waypoint.

**Comment by jcmbennett** [comment]
Thanks again, the folders work great, just what I needed and used the course editor for the first time as I didn't even know about it until today. :) The editor will save me lots of time but I have one request/idea for making the blue circle waypoints smaller in the editor. They are so big I can distinguish what goes where in intersections with several routes intersecting.

**Comment by TyKonKet** [comment]
You should be able to zoom enough to avoid this problem :D 
Let me know if I'm wrong

**Comment by jcmbennett** [comment]
This is full zoom of an intersection but i think my issue is that this is a 16x map, PV Industries, so when i load it the routes show up as if they were on a 4x. I tried selecting the 16x option but does nothing. I imagine if the routes were blown up to fit the full map size I would see them better. I am missing a step or doing something wrong. lol
![autodrive](https://user-images.githubusercontent.com/25438829/68093752-d28e7880-fe4d-11e9-80a9-4e909619abcf.png)

**Comment by jcmbennett** [comment]
Any advice on how I can get the editor to work right on my 16x map? I cant get the routes to line up with my map and messing around with the 4x 16x option does not help. Maybe I am doing something wrong?

**Comment by TyKonKet** [comment]
@jcmbennett sorry, I never tried to use it with bigger maps, I think we should ask @Stephan-S

**Comment by Roby1164** [comment]
> Any advice on how I can get the editor to work right on my 16x map? I cant get the routes to line up with my map and messing around with the 4x 16x option does not help. Maybe I am doing something wrong?

First thing, sure that the map file you use is the correct size for the editor?
I press the 16X button before opening the flie config?
![16X](https://user-images.githubusercontent.com/24955554/68196334-be1abf00-ffb8-11e9-9051-66a736471ca2.jpg)
