### ISSUE TITLE
Feature request* One click sends all vehicles to any location pre specified prior

### ISSUE THREAD

**Issue by evansv2** [Stephan-S/FS19_AutoDrive#782]
for example send all vehicles or selected vehicles to the gas station to refill gas for instance, or any other location, and comeback to the way point they started from, or one close by, Basically one mega preset function for all vehicles, or selected few , this would be some nice stuff :)))

**Comment by Iwan1803** [comment]
Automatic refuel was implemented. So there is no need for this.
Cost/benefit calculation: negative.
It takes too much time to implement this feature and the benefit is too small.
