### ISSUE TITLE
Auffahren auf wartende Abfahrer

### ISSUE THREAD

**Issue by kurtlohnunternehmen** [Stephan-S/FS19_AutoDrive#783]
Ich habe drei Abfahrer für Drescher abtanken eingestellt. Der Zielpunkt bzw. Haltestelle ist großzügig eingestellt, so das gut drei Traktoren mit Anhänger ohne Platzprobleme in der Reihe warten können (bei CP funktioniert es ohne Probleme). Doch nachdem der erste Abfahrer am Zielpunkt/Wartepunkt hält, fahren die nachfolgenden Abfahrer immer hinten auf den ersten Abfahrer drauf und schieben ihnen einige Meter weiter, wobei sich oft das Gewicht des auffahrenden in den Anhänger verkantet! Nun muss ich jedenfalls eingreifen, obwohl ich bei den Bremseneinstellungen usw. Eintragungen gemacht habe - also den Wert erhöht. Was nun?

**Comment by Stephan-S** [comment]
Ach, jetzt weiß ich wieder warum ich die Kollisionsbox so weit vor den Traktoren hatte.

Ich habe letzte Tage einen 'Fix' gebaut, damit die Traktoren auch vor den Bahnschranken korrekt anhalten und habe die Kollisionsbox etwas näher an die Traktoren ran geschoben um keine Lücke zu haben in die sonst die Schranken gerade so passen konnten und daher überfahren wurden.

Ich passe es an und mache die Box entsprechend auch im Stand so weit das sie bis über die Gewichte schaut.

Wenn du aktuell F5 drückst bei aktivem AD, siehst du die Kollisionsbox vermutlich in den Gewichten wenn der Fahrer stillsteht

**Comment by Michael170978** [comment]
Es wäre super wenn man  Bremseinstellungen wieder selber einstellen könnte. Im Moment ist es so, dass Fahrzeuge bei weichen Kurven zu extrem abbremsen.

**Comment by Stephan-S** [comment]
@Michael170978 Bitte mach mal ein extra Issue auf, dann können wir dort darüber sprechen :-)
Hier mache ich mal zu, da sich das aktuell erledigt haben sollte. Falls es mit den aktuellen Quelldateien noch zu Problemen führt, einfach wieder melden. Danke

**Comment by kurtlohnunternehmen** [comment]
Now I have the same problem with the trucks.
