### ISSUE TITLE
1.0.6.7: Pickup&Deliver - problems with Global Company

### ISSUE THREAD

**Issue by Iwan1803** [Stephan-S/FS19_AutoDrive#785]
Moin zusammen,
Abholen & Abliefern scheint nicht mit Global Company zu funktionieren. Ich kann weder vom Fermenter Silage, von der Dieselfabrik Kompost noch vom Sägewerk Hackschnitzel abholen. Der Trecker bleibt zwar beim Abholpunkt stehen, aber dann passiert einfach nichts mehr.
CoursePlay schafft es und auch per Hand kann ich beladen. Lade ich ihn per Hand voll, dann fährt er auch von alleine los und lädt ab.
Habe ich hier was übersehen?

**Comment by bojanh66** [comment]
I google-translated your post and it seems you have same issue as i do :
https://github.com/Stephan-S/FS19_AutoDrive/issues/781

It seems Pickup&Deliver is broken in 1.0.6.7 and we need to wait for a fix.

**Comment by Woife1** [comment]
a fix is already there  (didn't know yet if it works)
you had to zip it by yourself

**Comment by Iwan1803** [comment]
I'm allways using the latest version as i do a git download before starting the game and the problem exists since several versions.

@bojanh66 
No, it's not like your problem as i don't have error messages in the log. 
My problem is that it doesn't load the trailer at the start point. If i load it manually then AD continues driving to the goal point and does the unload also. Then it drives back to the start point and stays there without the next loading.

**Comment by RalfGorden** [comment]
> Moin zusammen,
> Abholen & Abliefern scheint nicht mit Global Company zu funktionieren. Ich kann weder vom Fermenter Silage, von der Dieselfabrik Kompost noch vom Sägewerk Hackschnitzel abholen. Der Trecker bleibt zwar beim Abholpunkt stehen, aber dann passiert einfach nichts mehr.
> CoursePlay schafft es und auch per Hand kann ich beladen. Lade ich ihn per Hand voll, dann fährt er auch von alleine los und lädt ab.

hab genau das selbe Problem

**Comment by geo-luchs** [comment]
I've the same problem with a global company compatible prod.
A "normal" silo works, but not global company related production.

problem exists ( tested) with
1.0.6.6c
and latest github zip

I've only an additional version from 28.10. 19:45,  where it works fine.
But this is a version, where no version information is written in the title bar.

So somehow behind this date, something was implemented, what prevents to load from production trigger

**Comment by Woife1** [comment]
Maybe the GC make this Issue itself
there were some Updates too

**Comment by geo-luchs** [comment]
I don't Think so.

Because I tested now several versions of AD with always Samen Version of GC 1.1.2.

And until AD Fromm 28.10. It works, but Not with AD 1.0.6.6c and later

**Comment by Stephan-S** [comment]
I just updated the code.
For infos, see the commit message :-)

**Comment by RalfGorden** [comment]
hallo alles wieder okay , vielen Dank für deine Mühe immer die du dir machst mach weiter so
