### ISSUE TITLE
Combine Issue on MP

### ISSUE THREAD

**Issue by jcmbennett** [Stephan-S/FS19_AutoDrive#786]
So on my multiplayer server when trying to do the unload combine my truck keeps lining up with the back side of the header instead of the pipe. Twice when trying a semi with trailer as soon as the cab hit the back of the header there was major glitch and my semi ended up miles in the sky and off the map while the harvester was well into the ground and trailer not to be found. I downloaded a backup copy of the server prior the incident and tested in single player and both the semi/trailer and truck worked fine. They found the pipe, unloaded and went to the silo. I duplicated the  AD settings on the server and get different results.
![20191103192355_1](https://user-images.githubusercontent.com/25438829/68149467-ce686680-fef2-11e9-87e9-0ac28fb5cef8.jpg)
![20191103192131_1](https://user-images.githubusercontent.com/25438829/68149476-d1fbed80-fef2-11e9-977f-a1d47de22212.jpg)

![20191104101815_1](https://user-images.githubusercontent.com/25438829/68149227-5bf78680-fef2-11e9-9343-f0fafd19a79d.jpg)
![20191104102257_1](https://user-images.githubusercontent.com/25438829/68149233-5e59e080-fef2-11e9-8c36-1d85f2035077.jpg)

**Comment by jcmbennett** [comment]
Any ideas or advise would great as I would really like to make the unload combine work on my server. I read any posts here relating to combine and watched all the videos I could find but no luck.

**Comment by Stephan-S** [comment]
Sorry, I wont't get to test MP related function until the weekend. But it seems like the settings are not properly used, transferred to the server. I will look into it
