### ISSUE TITLE
Extremeley sensitive collisions when aproaching semi tight spaces

### ISSUE THREAD

**Issue by evansv2** [Stephan-S/FS19_AutoDrive#787]
here is a video reference
https://www.youtube.com/watch?v=HqkhQN967Zk

@Stephan-S  space is not that tight but collision sensors, are complaining and wont let the vehicle drive   anyway to adjust them, or maybe show where this is in code, so I can increase them a little and submit a pull request after testing

**Comment by Stephan-S** [comment]
Well I wouldn't call this overly sensitive.
The collision boxes are based on the vehicles/implements dimension and I don't intend to reduce this size.
This could only be improved by editing the implement / vehicle's size definition in the xml to exactly match it's physical size.
Right now there is some border around some but not all object. So I can't generall reduce this size for every object
