### ISSUE TITLE
Issues loading saves with autodrive

### ISSUE THREAD

**Issue by Lefurjah** [Stephan-S/FS19_AutoDrive#788]
I updated autodrive a few days ago and since then I have not been able to load any games (save games or new) where I have the mod enabled.  I have deleted autodrive and reinstalled (from ingame modhob, modhub.us, and from github) and even completed uninstalled game and reloaded but i get the same issue.  Any help in resolving this would be appreciated.

**Comment by Woife1** [comment]
the AD version from ingame Modhub is to old 
only here on github is the newest

and without a log i would say there is an other mod thats destroy your savegame ;)
