### ISSUE TITLE
Reverse gear... !!!

### ISSUE THREAD

**Issue by Roby1164** [Stephan-S/FS19_AutoDrive#789]
It would be nice and useful to be able to reverse the vehicles,
There are situations, such as parking, or if you load a trailer or a tool, in closed road situations, particularly on small maps, with farms and narrow roads, if I'm not mistaken the CP already has a reverse function, example , when leveling a silage bunker, maybe you can see the code it uses ....

**Comment by Michael170978** [comment]
A very good idea. I support it. Sometimes you have a trigger where you need to drive backward to fill your trailer. Right now we have green track line for one way, blue line for 2 way. What is about red track line for reverse?

**Comment by TyKonKet** [comment]
@Michael170978 where did u see a red line?

**Comment by Roby1164** [comment]
> @Michael170978 where did u see a red line?

Credo intenda che, inserendo la retromarcia, si potrebbe usare la linea rossa.... :D

**Comment by Michael170978** [comment]
red line was an idea to include into AD for reversing

**Comment by Woife1** [comment]
AD couldn't really drive reverse couse AD ignores the trailer and get stuck

**Comment by Roby1164** [comment]
> AD couldn't really drive reverse couse AD ignores the trailer and get stuck

I understand, in fact I said to see how the CP works, to see if you can even take it on AD. I do not believe that the problem is to identify any trailer or connected implement, but rather to make routes in reverse, since the CP uses a registration and not a simple point-to-point step.

**Comment by Iwan1803** [comment]
Implemented in 1.1.0.5-RC1.
