### ISSUE TITLE
Abfahrer bleibt immer noch in der Frucht stehen (MP)(re-opened)

### ISSUE THREAD

**Issue by Moitzbert** [Stephan-S/FS19_AutoDrive#790]
Abfahrer bleibt weiterhin nach dem Abtanken in der Frucht stehen und blockiert in weiterer Folge den Drescher. Hat schon jemand eine Lösung ?

**Comment by RalfGorden** [comment]
ich spiele SP meiner bleibt nicht stehen

**Comment by Moitzbert** [comment]
@RalfGorden könntest du mir eventuell deine Einstellungen hier rein posten ? Also von Drescher und Abfahrer ?

**Comment by Woife1** [comment]
versuch mal Parken im Feld abzuschalten

**Comment by RalfGorden** [comment]
![fsScreen_2019_11_05_18_07_59](https://user-images.githubusercontent.com/56214377/68229788-28068900-fff8-11e9-8ca1-6ce92cf0c543.png)
![fsScreen_2019_11_05_18_08_08](https://user-images.githubusercontent.com/56214377/68229791-28068900-fff8-11e9-8ffc-127e2efe4b1b.png)

**Comment by Moitzbert** [comment]
Danke, werd ich gleich mal ausprobieren.

**Comment by Stephan-S** [comment]
Die Fahrzeugspezifischen Einstellungen wurden im aktuellen Release nicht korrekt auf dem Server übernommen.
Mit den aktuellen Quelldateien bzw. mit dem kommenden Release sollte dieser Fehler behoben sein und die Einstellungen korrekt übertragen werden.
