### ISSUE TITLE
Ruckeln im Mp Mehrere fahrer mit ad

### ISSUE THREAD

**Issue by Mannie313** [Stephan-S/FS19_AutoDrive#791]
Hallo Stephan ich habe AD neueste Version auf dem dedi Drauf und wen ich zwei oder mehr abfahrer hab ruckelt es wie nix. Die ms anzeige und FPS bleiben konstannt.

MFG Mannie313

**Comment by Woife1** [comment]
Der Server scheint mit AD überlastet zu sein
Das "Problem" wurde schon in einigen Issues behandelt

**Comment by Stephan-S** [comment]
Servus, probiere doch mal die neueste selbstgepackte zip aus oder warte auf das nächste Release, da wurde einiges an den MP Problemen angegangen :-)

**Comment by GitTomahawk** [comment]
Meine Mitspieler und ich habe den Eindruck das Ruckeln ist mir den letzten Releases schlimmer geworden. (die Helfer insgesamt beanspruchen mehr Server CPU)
Die Fahrer belegen jetzt auch oft einen "Helfer-Slot" - auch dann wenn sie garnicht aktiv sind.
(Ich hoffe das löst sich wennBug #626 gefixt ist)
Was aktuell aber deutlich besser funktioniert ist der sync der clients wenn jemand einsteigt oder Wegpunkte geändert/neu berechnet wurden. (das hat früher ewig gedauert und geht jetzt recht fix)
Großes Lob von mir auch für die Statusmeldungen wärend der Übertragung/neuberechnung -jetzt weiss man besser woran es hängt bzw. wie lange es noch dauert.

**Comment by Mannie313** [comment]
ok werde ich machen.

MFG Mannie313

**Comment by TyKonKet** [comment]
We are closing this issue because of a long time inactivity, If the issue still persists with the latest versions, feel free to open it again.
