### ISSUE TITLE
Routes editor issues with bigger maps

### ISSUE THREAD

**Issue by TyKonKet** [Stephan-S/FS19_AutoDrive#792]
This is full zoom of an intersection but i think my issue is that this is a 16x map, PV Industries, so when i load it the routes show up as if they were on a 4x. I tried selecting the 16x option but does nothing. I imagine if the routes were blown up to fit the full map size I would see them better. I am missing a step or doing something wrong. lol
![autodrive](https://user-images.githubusercontent.com/25438829/68093752-d28e7880-fe4d-11e9-80a9-4e909619abcf.png)

_Originally posted by @jcmbennett in https://github.com/Stephan-S/FS19_AutoDrive/issues/780#issuecomment-549190957_

**Comment by TyKonKet** [comment]
> Any advice on how I can get the editor to work right on my 16x map? I cant get the routes to line up with my map and messing around with the 4x 16x option does not help. Maybe I am doing something wrong?

**Comment by TyKonKet** [comment]
> First thing, sure that the map file you use is the correct size for the editor?
> I press the 16X button before opening the flie config?
> 
> What map is it ??
> 
> ![16X](https://user-images.githubusercontent.com/24955554/68196334-be1abf00-ffb8-11e9-9051-66a736471ca2.jpg)

**Comment by TyKonKet** [comment]
@jcmbennett @Roby1164 
Guys, please keep talking here about issues with the editor.

**Comment by Martinnygaard** [comment]
the in general, i would love it to be able to zoom more.
for example a cross like the picture above would be nice if we could zoon so it fill the entire screen, only that cross.

**Comment by jcmbennett** [comment]
I got my 16x map to work. I had to reduce the bmp image from 4096 to 2048 then loading it set at 16x in editor fit perfect. So the only issue now is the zoom and/or small waypoint dots.
