### ISSUE TITLE
Teilweise keine Zielübernahme

### ISSUE THREAD

**Issue by Woife1** [Stephan-S/FS19_AutoDrive#797]
Bei der Zielauswahl wird kein Ziel übernommen wenn das Ziel im Dropdown Menü noch innerhalb des HUDs ist, sobald man ein Ziel oberhalb des HUD-Bereichs wählt wird das übernommen.

ich mach Morgen noch ein Screenshot dazu falls nötig.

If you select a destination that is in the dropdown even in the HUD-area it will not set as destination, is the destination above the HUD-area it is set as destination.

**Comment by Iwan1803** [comment]
Das ist mir auch schon aufgefallen und hat ein paar Mal für Verwirrung gesorgt.

@Stephan-S 
kann das was mit der Mouse-down/-up-Änderung zu tun haben? Ich meine nämlich, das es vorher problemlos ging.

**Comment by Woife1** [comment]
Fix works 👍
