### ISSUE TITLE
Kein abladen an Global Camany Möglich

### ISSUE THREAD

**Issue by pulimatrix** [Stephan-S/FS19_AutoDrive#798]
Hey Großer, seit 1.0.6.7 ist kein abladen an GC mehr Möglich, auch fehlen mir die spuren für, beim aufzeiuchen von kursen die blaue/lila Linie fürs beitseitige befahren! hast da vllt was geändert? oder ist da was schief gelaufen? den mit 1.0.6.6 gehts komicher weise wieder hab fast ne stunde grbaucht bis ich herraus fand das das neue Ubdate gewesen ist! lg

**Comment by geo-luchs** [comment]
GC  geht wieder mit einem der letzten Updates im source Code zip.
Nicht das offizielle 1.0.6.7 release.
Lila linie:  rechte Maus Taste auf den Recordbutton.
Links ist nur noch grün

**Comment by geo-luchs** [comment]
Ach ja, und mal in die Issues gucken.
Das mit den blauen Linien wurde vor 17 Stunden gemeldet und die Lösung wurde dort bereits gepostet 😉
