### ISSUE TITLE
Voraussetzungen für AutoDrive

### ISSUE THREAD

**Issue by Williwillswisse** [Stephan-S/FS19_AutoDrive#8]
Hallo Stephan,
welche Bedingungen muss ein Fahrzeug erfüllen, damit es per AutoDrive fahren kann?
Ich habe jetzt schon mehrere Mod-Fahrzeuge gefunden, bei denen ich das HUD nicht öffnen kann.
z.B.: https://forbidden-mods.de/filebase/file/5899-scania-r-series-hooklift/
Auch die jetzt neu rausgekommenen Claas Xerion lassen ein Öffnen des HUD nicht zu.

**Comment by Stephan-S** [comment]
Hallo, 
ich nehme an das liegt an der Reihenfolge wie die Mods geladen werden. Du kannst ja gerne mal ausprobieren den AutoDrive Mod umzubennen in zzzzFS19_AutoDrive.zip
Dann sollte er erst nach den Fahrzeugen laden. In der Zwischenzeit baue ich eine Funktion ein um AutoDrive auch bei später geladenen Mods zu aktivieren.
Das ist zumindest meine erste Vermutung.

**Comment by Bluebirdonline** [comment]
Ich habe mir in den Einstellungen/Tastenzuweisungen die Taste für die Einrichtung Änderung des Namens eingestellt. Nach betätigen dieser Taste wird kurz das Formular eingeblendet und schon ist wieder Schluss.
