### ISSUE TITLE
english video on combine unload needed

### ISSUE THREAD

**Issue by ploughedfieldman123** [Stephan-S/FS19_AutoDrive#80]
would anyone here from UK make a english video of the above title.  as I am finding it real hard to sort out. maybe Stephan could do one too. 

thanks in advance

**Comment by Roby1164** [comment]
t is not difficult to understand and make the combine's exhaust work, I don't speak English and I can't make a video, but keep in mind that, it's not the combine to set, that can go with the worker or manually, but it's the trailer to be set, creating the route and points, at the silo and a point near the field to be worked, then starting the Autodrive, the latter will position itself waiting at the field, when the combine is full, stops and extend the tube, the operator on the tractor or truck, will leave and unload the combine harvester, stopping there, if it is not full, otherwise he will proceed towards the silo, to unload, and then return to the field, waiting to unload again the combine ...

**Comment by ploughedfieldman123** [comment]
> t is not difficult to understand and make the combine's exhaust work, I don't speak English and I can't make a video, but keep in mind that, it's not the combine to set, that can go with the worker or manually, but it's the trailer to be set, creating the route and points, at the silo and a point near the field to be worked, then starting the Autodrive, the latter will position itself waiting at the field, when the combine is full, stops and extend the tube, the operator on the tractor or truck, will leave and unload the combine harvester, stopping there, if it is not full, otherwise he will proceed towards the silo, to unload, and then return to the field, waiting to unload again the combine ...

Hi yes thanks for answering.  I had spoke to Stephan yesterday he said to make sure combine is saying same field as target start it off.  which it was full 100% I then go to tractor in same field with trailer set it to same field plus go to silo.  start it going but it just wont go to combine. to unload. sometimes it will after about 4 to 5 minutes. so why dont it unload soon as its 100% why wait 4 to 5 minutes

**Comment by Roby1164** [comment]
The problems can be various, but first, it could be the path.
Let's start from the fact that, you don't need to set up the combine, that one does its job, manual or automatic, if it is automatic, when it is full it stops, extends the tube and waits, in manual, it can be called when you want. But it is the tractor with trailer that must be set correctly. First, it depends on the map and the size of the field, to find the best place to start, then in configurations, if you want it to go to the silo, when the trailer is full or at a percentage what you want, then if you use the combine harvester automatically, be careful where it is when it is full, which side is the pipe, if it is on the side of the field still to be harvested, then it would be better to set the tractor, which does not park in the field, in that way always returns to the starting point, avoiding that collisions and blocking of the vehicles may occur. Regarding the track, it must be as linear as possible, if the field is not large, and there is space along the perimeter, you can opt, for a path around the field itself, in this way, the tractor will not make strange turns to return to the starting point, to then do other maneuvers, to go towards the silo, if instead you prefer, you can do, a kind of roundabout, after the starting point, I use this system, that is, the path to enter of the field, it is two-way, up to the starting point, then I continue with a one-way stretch, making a hairpin, in this way it does not take too long in maneuvers.

**Comment by Anonymous-any** [comment]
After searching a bit Ytb I found from the Maestro:
https://www.youtube.com/watch?v=cC50lfNVmxs
using trad subtitle gone better to understand what to do.
Thank you Balu !

**Comment by ploughedfieldman123** [comment]
> The problems can be various, but first, it could be the path.
> Let's start from the fact that, you don't need to set up the combine, that one does its job, manual or automatic, if it is automatic, when it is full it stops, extends the tube and waits, in manual, it can be called when you want. But it is the tractor with trailer that must be set correctly. First, it depends on the map and the size of the field, to find the best place to start, then in configurations, if you want it to go to the silo, when the trailer is full or at a percentage what you want, then if you use the combine harvester automatically, be careful where it is when it is full, which side is the pipe, if it is on the side of the field still to be harvested, then it would be better to set the tractor, which does not park in the field, in that way always returns to the starting point, avoiding that collisions and blocking of the vehicles may occur. Regarding the track, it must be as linear as possible, if the field is not large, and there is space along the perimeter, you can opt, for a path around the field itself, in this way, the tractor will not make strange turns to return to the starting point, to then do other maneuvers, to go towards the silo, if instead you prefer, you can do, a kind of roundabout, after the starting point, I use this system, that is, the path to enter of the field, it is two-way, up to the starting point, then I continue with a one-way stretch, making a hairpin, in this way it does not take too long in maneuvers.

Ok thanks will play about with AD more then try a different path in fields. Im wondering if it pays to go all around edge of field then back out. like course play do when making a route, see if that helps

**Comment by ploughedfieldman123** [comment]
> After searching a bit Ytb I found from the Maestro:
> https://www.youtube.com/watch?v=cC50lfNVmxs
> using trad subtitle gone better to understand what to do.
> Thank you Balu !

Thanks But I have already seen that video, its hard when its not in english, but can use subs like you said

**Comment by Stephan-S** [comment]
Hello,

I started an english tutorial video series on youtube. Here is the link to the first one:
https://www.youtube.com/watch?v=2icMaSXAmYw

The third one also describes the combine unload mode: 
https://www.youtube.com/watch?v=uOO4tBcBKAs

**Comment by Anonymous-any** [comment]
Thank again for time made;)
