### ISSUE TITLE
Errors while saving setting in MP

### ISSUE THREAD

**Issue by TyKonKet** [Stephan-S/FS19_AutoDrive#800]
`AutoDriveUpdateSettingsEvent.lua:51: attempt to index local 'vehicle' (a nil value)]`

`Warning (script): 'streamWriteInt16': Argument 1 has wrong type. Expected: Int. Actual: Nil `

```
LUA call stack: AutoDriveUpdateSettingsEvent.lua (26) : streamWriteInt16
```

`Warning (script): Function 'streamWriteInt16' called with invalid number of arguments. 0 instead of 1.`

```
LUA call stack: AutoDriveUpdateSettingsEvent.lua (31) : streamWriteInt16
```

**Comment by Mannie313** [comment]
[log.txt](https://github.com/Stephan-S/FS19_AutoDrive/files/3813614/log.txt)
Grade erst aktualisiert.

MFG Mannie313

**Comment by Bandesss** [comment]
Die zahlen bleiben stehen... 
Beim Laden von Kuser vom Server......
