### ISSUE TITLE
Fieldwork question?

### ISSUE THREAD

**Issue by Farmer89** [Stephan-S/FS19_AutoDrive#801]
Hi,are you guys planning to add in future fieldwork mode, like in courseplay for making this mod more standalone, or it will be for transport only? I prefer this mod, because CP lack of mp.

**Comment by raxtor** [comment]
Hi, 
@Stephan-S rejected FW some time ago.
I have completely done approach to fieldwork. I called him Improved Helper. I was asking @TyKonKet via emal, if he is interested to look over my solution, which is much better than CP approach and offer user same freedom like FS default helper but is supporting multiple machines, headlands and of course AD pathfinding system and network. I did get any reply yet. I can prepare complet documentation for programmer because I am still not familiar with LUA script and LUADOC because lack of time.

**Comment by raxtor** [comment]
But personally I prefer to remove all bugs before FW implementation and AD has still has some bugs and some features which would ne nice have in AD, like badly working Active unloading, Rail crossing crashes, ability to refueling etc...

**Comment by Twetch** [comment]
AIVehicleExtension is nice mod, which work very well with AD, if you play on map with non shaped field.Also he support more combines and has few path options, like headland or rows.Maybe its something similar to your idea raxtor.

**Comment by raxtor** [comment]
btw here are major shortcomings of default FS19 helper:
- multiple machine support
- headland support
- avoiding obstacles in the field like powegrid, trees, green island
- limited turn maneuvers pallet
- follow some defined pattern with posiibility find path to next uncuted crop

**Comment by raxtor** [comment]
But @Stephan-S still didnt get I am something like Elon Musk for Tesla for his mod. I am AD visionary.. :-)

**Comment by Iwan1803** [comment]
Sounds to me like "i reinvented the wheel... you must use this". 
A swiss army knife has many tools, but all are limited. If i want to cut off a sprig, it's ok, but for a tree i need good saw. 
I think AD should continue to do the stuff it can and not become a multi-tool. This maybe can be done, if there enough specialists for specific things.

**Comment by raxtor** [comment]
@Iwan1803  as always you are smartest guy here and its not only thx to your name. Thx you resolved it. We need more such smart ppl like you are.

**Comment by Stephan-S** [comment]
Don't be mad @raxtor :p we are all friends here 👍

**Comment by Iwan1803** [comment]
@raxtor 
i didn't want to attack anyone, but just wanted to write my opinion and my point of view. I apologize if that came out wrong.
I just mean that it would be unwise to turn AD into a multimod. AD is the mod for calculating routes without using static ones like CP does. If AD works "perfectly" and if there are enough fieldwork specialists here who have the time for coding, then perhaps one could still think about an extension.

**Comment by Farmer89** [comment]
This mod already cover all transport modes and it work awesome,so why dont expand to something bigger :) If Stephan love coding ,its just annother challenge for him make this mod even greater.

**Comment by Dzi4d3k** [comment]
I also agree that AD mod shouldn't duplicate functions like CP or AIVE.

**Comment by Farmer89** [comment]
ok i don't care anymore, so lets end this theme.
