### ISSUE TITLE
Maus Probleme nach "Fixed Typo"

### ISSUE THREAD

**Issue by Wienet** [Stephan-S/FS19_AutoDrive#802]
Hi
mit dem neusten Update stimmt was nicht. Fahrzeuge fahren nicht los, Maus spinnt rum.
Mal nachkucken?
Gruß Marc

**Comment by C0pasalli0r** [comment]
Hab ich auch .
.../FarmingSimulator2019/mods/FS19_AutoDrive/scripts/AutoDrivePathFinder.lua:1147: attempt to call method 'BoxesIntersect' (a nil value)
Error: Running LUA method 'update'.

**Comment by Wienet** [comment]
Funzt wieder.
Danke für die schnelle Hilfe. Super Job!

**Comment by Wienet** [comment]
Sorry, funktioniert doch noch nicht wieder

**Comment by TyKonKet** [comment]
#804

**Comment by TyKonKet** [comment]
Have been fixed with 9dddaff71d476295ac24f4967615cf17e706a092
