### ISSUE TITLE
Fehler beim abfahren

### ISSUE THREAD

**Issue by ratze68** [Stephan-S/FS19_AutoDrive#806]
Hallo zusammen,

Spiele schon länger mit AutoDrive vielen Dank dafür!

Bis zum Claas DLC und andere Updates hat es auch immer alles prima Funktioniert.

Jetzt möchte mein Ladewagen der auf den CP Mähdrescher Kurs auflädt nicht mit AutoDrive abfahren
Alles hundertmal überprüft, da ich annahm der Fehler Macher Sitz vor dem Monitor.

Zum besseren Verständnis hänge ich mal ein paar Bilder an

![20191106152448_1](https://user-images.githubusercontent.com/53152008/68336462-c10fcf80-00de-11ea-835e-419111ebda00.jpg)

![20191106152542_1](https://user-images.githubusercontent.com/53152008/68336475-c79e4700-00de-11ea-9437-9b9f93170599.jpg)

![20191106152640_1](https://user-images.githubusercontent.com/53152008/68336514-dc7ada80-00de-11ea-8cca-6fbd89761297.jpg)

![20191106152659_1](https://user-images.githubusercontent.com/53152008/68336523-e00e6180-00de-11ea-876d-c736fa1c786f.jpg)

Vielleicht mache ich ja wirklich ein Fehler oder von CP oder AD

Log ist Fehlerfrei

Lg stefan

**Comment by Woife1** [comment]
auf deinen Bildern macht CP und AD was es soll
nur gibt es keinen Weg vom Abfahrerpunkt zu irgendeinem Ziel 

probier mal die Einstellung nächstgelegen bei Feldausfahrt
und/oder verbinde den Punkt Feld 52 Abfahrer mit dem Streckennetz

**Comment by Stephan-S** [comment]
Könnte auch am Abladelevel liegen das du in AD ja einstellen kannst. Ich sehe das er nicht 100% voll ist, dann kann es je nach Einstellung sein, dass er wieder zum Auflade punkt fährt.

Also "Abladen ab Level" in den Einstellungen mal überprüfen. Nur wenn das erreicht ist, fährt er zum Abladepunkt

**Comment by ratze68** [comment]
Hallo
ich habe eben gerade Upgedatet und bekomme eine lua Fehler siehe Foto!

Woife@ ist es nicht so, wenn er Voll ist wird im AD das Ziel gleich grün? Er doch nicht auf den Abfahrer Platz?

Stephan-S @ Ich habe jetzt 4 Verschiedene Ladewagen getestet. Allen wird nur bis 99% geladen, bei der Einstellung "Abladen ab Level" bei 100%

![20191107115606_1](https://user-images.githubusercontent.com/53152008/68383846-b8f37680-0156-11ea-8c39-15a3a91d7706.jpg)

![20191107120159_1](https://user-images.githubusercontent.com/53152008/68383860-bc86fd80-0156-11ea-93a9-cfafbc1b8372.jpg)

Lg Stefan

**Comment by Woife1** [comment]
bisher hat es auch bei über 99% funktioniert 
ich hab auch die Einstellung abladen ab auf 85-90%
CP sieht den Ladewagen als voll an wenn nur noch nen paar Liter fehlen (kann auch an Rundungen liegen)

**Comment by Stephan-S** [comment]
@TyKonKet You just killed the external interface to CP once again :-)
Please fix the spec_autodrive variable back to what it was

**Comment by ratze68** [comment]
Hallo,

da ist nichts mehr......
![20191107125250_1](https://user-images.githubusercontent.com/53152008/68387038-ac265100-015d-11ea-8d20-ba642beea47e.jpg)

**Comment by ratze68** [comment]
Jetzt bleibt er stehen und sagt mir das er entladen werden muss

![20191107125921_1](https://user-images.githubusercontent.com/53152008/68387629-0673e180-015f-11ea-98b5-7fa173e9063c.jpg)

**Comment by Stephan-S** [comment]
Fixed

**Comment by ratze68** [comment]
Hallo Stephan, 
mit den Standard Fahrzeugen Funktioniert alles wie es soll !!

Ich habe eine John Deere Mod der will net, ist auch nicht schlimm dann halt mit Standard Fahrzeuge.

Danke für die schnelle hilfe!!!

Lg Stefan

**Comment by Stephan-S** [comment]
Alles klar @ratze68 dann mache ich hier mal zu.
Falls du das mit dem John Deere noch bearbeitet haben willst, mach mal ein neues Issue auf mit allen Infos die wir brauchen können um dran zu arbeiten, also auch ein Link zum Mod.
Aber das hat dann verständlicherweise nicht die höchste Priorität. Danke :-)
