### ISSUE TITLE
Kein Beladen bei Produktionen von GC; Kursziele springen um

### ISSUE THREAD

**Issue by Spielbauer** [Stephan-S/FS19_AutoDrive#807]
Hallo an die AD Crew,

habe heute mit der Version 1.0.6.7 gespielt. Dabei ist mir aufgefallen das die Fahrzeuge an den GC Produktionen nicht mehr von alleine laden sondern nur mit "R". Desweiteren springen bei mir die angefahrenen Ziele im Ordner durch, ohne dass ich die Option "mehrere Ziele" ausgewählt habe.

Gruß Spielbauer
P.S. Log reiche ich nach

**Comment by Woife1** [comment]
update mal auf eine selbzip version 
Fix für GC existiert bereits
was meinst du genau mit Kursziele springen um? meinst du die Ziele werden nicht immer übernommen? ein Fix dafür ist auch schon fertig

**Comment by Spielbauer** [comment]
Ich meine damit das ein Fahrzeug z.B. zum Martinshof auf der Multimap 2019 fährt und dort Kartoffeln in die Produktion liefert. Das macht der Abfahrer auch, aber sobald der Hänger geleert ist springt das Abladeziel um auf eine andere Abladestelle z.B. Kartoffel einlagern. Und das alles obwohl keine Option "Mehrere Ziele" angewählt ist. Das ist mir mit mehreren Abladestellen und Fahrzeugen passiert.

**Comment by Stephan-S** [comment]
Im MP oder SP? 
Die mehrere Ziele Einstellung ist übrigens Fahrzeug spezifisch und muss bei jedem Fahrzeug eingestellt werden.

**Comment by Spielbauer** [comment]
Kurzes Update: 
Habe heute morgen nochmal eine Savegame von gestern gespielt. SP Modus, ein Kartoffelernter, zwei Abfahrer mit verschiedenen Zielen. Keines der Fahrzeuge stand auf "Mehrere Ziele". Ich konnte den Fehler leider nicht reproduzieren. Das einzige was mir auffiel, es hatten alle Traktoren den Abstand vom Rohr auf -4,25 verstellt.
Und als ich heute das Spiel das erste mal gestartet hab konnte ich keinen Traktor nach rechts lenken sondern nur nach links. Aber das hat sicher nichts mit euch zu tun.
Als letztes eine Bitte, ich hab das mit dem Patch für GC nicht hinbekommen. Welche Datei genau muss ich runterladen damit dort wieder be- und entladen werden kann.

Vielen Dank für eure Hilfe
Gruß Spielbauer

[savegame1_backup2019-11-06_17-32.zip](https://github.com/Stephan-S/FS19_AutoDrive/files/3819440/savegame1_backup2019-11-06_17-32.zip)
[log.txt](https://github.com/Stephan-S/FS19_AutoDrive/files/3819441/log.txt)

**Comment by iljarogoff** [comment]
Das mit dem Abstand zum Rohr -4,25m hab ich auch

**Comment by Woife1** [comment]
das war mit einem der letzten Updates durch die Erweiterung des Rohrabstandes kam es zu diesem "Fehler"
einmal Ändern und es ist wieder gut

**Comment by Stephan-S** [comment]
Korrekt, das Abstandsproblem ist nur durch die Erweiterung der Option gekommen, dass man nin auch negative Werte einstellen kann.
Wenn sich das Problem mit mehreren Zielen offensichtlich erledigt hat, mache ich hier mal zu :-)
