### ISSUE TITLE
Immernoch: Maus Probleme nach "Fixed Typo"

### ISSUE THREAD

**Issue by Wienet** [Stephan-S/FS19_AutoDrive#808]
Sorry, aber auch nach fixed #802 + #804 habe ich erhebliche Probleme:
- Maus verschwindet
- Funktionen streiken
- Bildschirm friert komplett ein
- ein ordentliches Beenden des Spiels ist nicht mehr möglich

Ich spiele inzwischen wieder mit der Version von gestern Abend, 5.11.19, 22:35. Die läuft.

**Comment by Iwan1803** [comment]
Eine genauere Beschreibung, wann was passiert sowie das Log könnten hilfreich sein.
Kannst du das noch liefern?

**Comment by Wienet** [comment]
Folgt später

**Comment by Wienet** [comment]
So, neues Update von heute geladen.
Nach Spielstart 1x weitergeschaltet zur Eisenbahn, danach kein weiteres umschalten möglich.
Nach Aufruf des Menüs wird die Landkarte immer kleiner (als wenn ich sie zoomen würde) und bei den Fruchtarten läuft die Markierung ständig von oben nach unten (als wenn ich scrollen würde).
Diesmal konnte ich noch ordentlich beenden.
Irgend eine Idee???

**Comment by Wienet** [comment]
Wie kann ich Euch das Log zeigen? Die ganze log.txt hier rein kopieren?

**Comment by Wienet** [comment]
2019-11-07 16:14 Error: Running LUA method 'update'.
2019-11-07 16:14 C:/Users/Papa/Documents/My Games/FarmingSimulator2019/mods/FS19_AutoDrive/scripts/AutoDrive.lua:225: attempt to index field 'ad' (a nil value)

**Comment by haamic** [comment]
Du startest ein neues Spiel ohne vorherigen gespeicherten Spielstand? Oder ist der vorhanden? Also ich hab das Problem schon länger, das wenn ich eine neue Karte beginne, solche Fehler habe wie du sie beschreibst. Da hat mir geholfen, das Spiel ohne jegliche mods zu starten und das erste mal zu speichern. Dann beenden und nun mit mods den gespeicherten Spielstand laden. Dann funktioniert alles wie es soll. Gruß Micha

**Comment by Wienet** [comment]
@haamic Danke für den Hinweis, aber ich spiele noch meine erste Karte und mit dem mod von vor 2 Tagen läuft ja alles bestens.

Ich habe mal 2 Logs verglichen und eine Zeile gefunden, die nur im fehlerhaften Spiel vorkommt:

dataS2/character/humans/characterAnimation.i3d (279.72 ms)

Kann mir jemand sagen, was diese Zeile bedeutet und warum sie in der funktionierenden Version nicht enthalten ist?
