### ISSUE TITLE
FS19_AutoDrive/scripts/AutoDrive.lua:258: attempt to index field 'Trigger' (a nil value)

### ISSUE THREAD

**Issue by Mannie313** [Stephan-S/FS19_AutoDrive#809]
Die N
[log.txt](https://github.com/Stephan-S/FS19_AutoDrive/files/3818264/log.txt)

Ist die Neueste version.

Neuer Spielstand und Spiel hängt sich komplett auf.

MFG Mannie313

**Comment by TyKonKet** [comment]
@Mannie313 I need more info, I've tried both in SP and MP but I'm not able to reproduce the error.

**Comment by Mannie313** [comment]
Mit vorhandenem spielstand oder neuem im sp.

MFG Mannie313

**Comment by Mannie313** [comment]
So nur auf der standartmap ohne mods ausser AD


und der fehler kommt wieder.

MFG Mannie313

**Comment by TyKonKet** [comment]
Send the log again, It's not possible that the error is the same.
And please, can you write in english? You don't see I don't understand German?
