### ISSUE TITLE
Gespeicherte Kurse gehen auf einmal verloren

### ISSUE THREAD

**Issue by SeiliDaniel** [Stephan-S/FS19_AutoDrive#81]
Hallo Stephan, ich habe einen Fehler (in Version 1.0.1.3), bei dem beim speichern der Kurse die Datei "AutoDrive_Felsbrunn_config.xml" im savegame Ordner verschwindet und folgende Fehlermeldung auftaucht (das erscheint, wenn man auf Spiel speichern drückt & wenn man auf Kurse exportieren klickt):

AD: Set to not recalculating routes
Error: Running LUA method 'update'.
C:/FarmingSimulator2019/mods/FS19_AutoDrive/scripts/AutoDriveXML.lua:373: invalid value (nil) at index 1 in table for 'concat'

Wäre schön wenn du dich um diesen Fehler kümmern könntest. Es nerft mich nämlich ein bisschen, dass dadurch viele eingefahrene Kurse verloren gegangen sind und ich jetzt alle wieder neu einfahren muss. Danke schonmal im Voraus. Trotzdem ein super cooler Mod.

Grüße Daniel

**Comment by haamic** [comment]
Hallo, ich hatte auch gestern plötzlich keine Kurse mehr, aber zum Glück gibts ja den savegame BackUp Ordner, da war zum Glück die XML noch vorhanden. Nach rüberkopieren in den eigentlichen savegame Ordner war alles wieder da. Schau mal ob du die Kurse nicht auch so zurückholen kannst.

**Comment by SeiliDaniel** [comment]
Danke hat funktioniert mit dem rüberkopieren. Jetzt ist alles wieder da.

**Comment by haamic** [comment]
super
