### ISSUE TITLE
Folders are not saved on Dediserver

### ISSUE THREAD

**Issue by Justice-Molton** [Stephan-S/FS19_AutoDrive#810]
Yesterday I put all our courses in Folders, and today the folders are gone and the courses are back in a huge List.

**Comment by TyKonKet** [comment]
@Justice-Molton are you sure you saved the game?
Because I've tested this feature and it's  working for me...

**Comment by Justice-Molton** [comment]
Yes I saved, but the folders are gone.

**Comment by TyKonKet** [comment]
@Justice-Molton the folders were filled with at least one destination or were empty

**Comment by Justice-Molton** [comment]
More or less.

Von meinem iPhone gesendet

**Comment by TyKonKet** [comment]
Only folders with at least one destination are saved

**Comment by Justice-Molton** [comment]
I try it later again. Ill let you know

**Comment by TyKonKet** [comment]
Thanks

**Comment by Moitzbert** [comment]
I have the same problem, the dedicated Server can‘t save the folders and is restting after every syncro..

**Comment by Justice-Molton** [comment]
Exacly. It dosent save the folders, even if i have just one course in a folder.

**Comment by MiSpA51** [comment]
Same for me, but it also doesnt save edits in the names of the destinations.

**Comment by TyKonKet** [comment]
@Justice-Molton are you playign with the latest stable release (download from release section) or are you playing with latest files (zip built by yourself)?

**Comment by Justice-Molton** [comment]
latest release

**Comment by TyKonKet** [comment]
Ok, so the problem should be fixed with the next release.

**Comment by Justice-Molton** [comment]
any eta?

**Comment by TyKonKet** [comment]
[FS19_AutoDrive.zip](https://github.com/Stephan-S/FS19_AutoDrive/files/3824579/FS19_AutoDrive.zip)
 Try with this version and let me know pls.

**Comment by Justice-Molton** [comment]
Gimme 5sec

**Comment by Justice-Molton** [comment]
Works so far. it saved the folders and also a renamed destination.
Solved!

**Comment by Justice-Molton** [comment]
But if I try to save a new blank Folder like LU Meier it dosnt saves the folder. If I write it like LUMeier it works. So it looks like that space isn't supported

**Comment by Moitzbert** [comment]
TyKonKet - the God

**Comment by Justice-Molton** [comment]
and even if I write the names without space, I could save a course to the new builded folder

**Comment by TyKonKet** [comment]
Yes, spaces are not supported and you need to put into it at least a destination if you want it to get saved, we will improve that later, the important thing is that it now works.

**Comment by Justice-Molton** [comment]
So i try a bit around and let you know. Its a bit strange at the moment. I guess you need to safe after creating a folder

**Comment by TyKonKet** [comment]
If you find new problems, please open a new issue, it will help us tracking errors better.
