### ISSUE TITLE
2nd unloading goal / 2. Abladestelle

### ISSUE THREAD

**Issue by Iwan1803** [Stephan-S/FS19_AutoDrive#812]
Hallo zusammen,
in #719 geht es ja nur um den Fahren-Modus, aber warum kann man nicht bei allen Modi, wo eine Abladestelle angefahren werden soll, noch ein 2. Ziel ergänzen?

Bsp. 1: ich tanke einen Drescher ab und und die Ernte wird direkt an einer Produktion abgeladen. Wenn dort aber kein Platz mehr ist, dann kehrt der Abfahrer mit vollem Hänger zurück und das Spiel beginnt von vorne. Könnte ich hier nun mein Silo als 2. (optionales) Ziel eingeben, würde er nach der Produktion dort noch vorbeifahren und den Rest abladen, um dann mit einem (hoffentlich) leeren Anhänger wieder zum Drescher zurückzukehren.

Bsp. 2: ich habe mehrere Produktionen, die Weizen benötigen. Aktuell muss ich 2 Fahrzeuge für den Transport einsetzen, damit beide beliefert werden. Könnte ich die 2. Produktion als 2. Ziel eintragen,  würde er die 1. solange anfahren, bis sie voll ist (oder im Wechsel?) und im Anschluss dann direkt die 2. Produktion.

Ich hoffe die Beispiele machen klar, welche Vorteile ein 2. Ziel bringen würde. 
Vielleicht kann man auch per Einstellung definieren, wie viel Ladung an Ziel 1 und der Rest dann halt an Ziel 2 abgeliefert wird.

**Comment by TobiHH78** [comment]
Es gibt doch schon die Einstellung "Ziele im Ordner rotieren". Wenn du die Lieferziele der Produktionen in einen Ordner packst, fährt der Abfahrer bei jeder Lieferung ein anderes Ziel an. Das Hofsilo könntest du ebenfalls als möglichen Zielort in den gleichen Ordner verschieben.
So hast du nur einen Abfahrer der automatisch mehrere Ziele ansteuert.

**Comment by Iwan1803** [comment]
Ja, die gibt es, aber die hilft mir in meinen Augen nicht, zumal die Ziele ja auch rotiert werden und ich erst ein Ziel voll machen möchte und das 2. Ziel quasi als Ersatzziel dient. 
Gestern habe ich z.Bsp. 4 Felder gleichzeitig abgeerntet und damit 4 Produktionen befüllt. Als die voll waren, musste ich die AD-Routen anpassen, aber in der Zwischenzeit hatten die Abfahrer schon ein paar unnötige Runden gedreht.
Hätte ich mein Silo als 2. Ziel angeben können, wäre der Überschuss dort abgeladen worden, nachdem die Produktionen gefüllt waren.
Würde ich Ordner verwenden, müsste ich pro Produktion einen anlegen und pro Ordner auch ein eigenes Silo bauen, da man Ziele ja nicht "klonen" kann. Außerdem würde ja dann auch die Ernte gesplittet verteilt werden, was nicht zwingend zielführend ist.

**Comment by Alkoholix** [comment]
Für dein Beispiel 1, wenn du die Abladestellen in Reihe hast und eine Route durch bzw. an den Abladetriggern vorbei hast, werden die Trigger genutzt, auch wenn es nicht das angegebene Ziel ist.

Als Beispiel habe ich drei Hochsilos nacheinander stehen und eine Autodrive Route die nacheinander an allen Abladetriggern vorbeiführt, mit den Zielen Hochsilo 1, Hochsilo 2, Hochsilo 3. Wenn jetzt als Ziel Hochsilo 1 angegeben ist, dieses jedoch voll ist, fährt der Abfahrer weiter bis zum nächsten Trigger und entlädt da.

**Comment by Michael170978** [comment]
> Für dein Beispiel 1, wenn du die Abladestellen in Reihe hast und eine Route durch bzw. an den Abladetriggern vorbei hast, werden die Trigger genutzt, auch wenn es nicht das angegebene Ziel ist.
> 
> Als Beispiel habe ich drei Hochsilos nacheinander stehen und eine Autodrive Route die nacheinander an allen Abladetriggern vorbeiführt, mit den Zielen Hochsilo 1, Hochsilo 2, Hochsilo 3. Wenn jetzt als Ziel Hochsilo 1 angegeben ist, dieses jedoch voll ist, fährt der Abfahrer weiter bis zum nächsten Trigger und entlädt da.

Also wenn ich ihn richtig verstanden hab, möchte er, dass der Schlepper erstmal nur z.B. Silo 1 ansteuert und wieder zum Drescher zurückkehrt. Wer sagt den dass Silo 1 und Silo 2 gleich nebeneinander stehen. Stell dir mal vor Silo 1 ist im Süden und Silo 2 ist im Norden. Der Schlepper bräuchte viel Zeit um beide Ziele anzufahren. Ich denke Mal er möchte dem Drescher und Schlepper eine Aufgabe übergeben um ihn Ruhe andere Tätigkeiten ausführen und nicht ständig überprüfen ob alles OK ist. Da muss ich ihn aber entäuschen. Autodrive ist gut aber nicht so gut, dass du was einstellst und dann z.B. essen machen gehst oder was weiß ich.

**Comment by Iwan1803** [comment]
@Alkoholix 
dann müsste ich alle Produktionen in Reihe nacheinander bauen und im Anschluss das Silo (oder mehrere), damit das für alle Abfahrer und alle Ernten greift. Außerdem fände ich es nicht so toll, wenn AD einfach Trigger nutzt, die nicht am Zielpunkt sind.

@Michael170978 
ich überprüfe ständig meine ganzen Maschinen, aber könnte natürlich mehr Zeit in andere Sachen investieren, wenn volle Abfahrer nicht einfach sinnlos im Kreis fahren, sondern dann ihre Waren einfach an einem 2. Zielpunkt abliefern. Dieser soll auch nur dann angefahren werden, wenn der 1. voll oder warum auch immer nicht erreichbar ist.
Das es keine 100%ige Automatisierung geben wird, ist mir auch klar, aber ich möchte so nah wie möglich rankommen. Allerdings verhindern Abfahrer, die sinnlos um den Zielpunkt kreisen oder keinen Weg mehr vom Feld runter finden oder in Drescher krachen, dies deutlich häufiger als das sie nicht abladen können.

**Comment by Stephan-S** [comment]
Ich bin mir noch nicht sicher bzw. noch nicht ganz einig wie ich so etwas am liebsten umsetzen würde. Ich schiebs für's Erste mal auf die lange Bank aber lasse es nicht untergehen :-)
