### ISSUE TITLE
AutoDriveUtilFuncs.lua:98: bad argument #1 to 'atan2' (number expected, got nil)

### ISSUE THREAD

**Issue by eddiem54** [Stephan-S/FS19_AutoDrive#813]
Hi Stephan,
Getting above error and unable to tab between vehicles.
Regards.
[log.txt](https://github.com/Stephan-S/FS19_AutoDrive/files/3820509/log.txt)

**Comment by iljarogoff** [comment]
same here, breaks game completely

**Comment by TyKonKet** [comment]
@iljarogoff this kind of comments makes absolutely no sense, since that those who find this kind of errors are deliberately choosing to use a version, of the mod, still in the development.
If you are bored of find errors, you can safely download the latest official release.

**Comment by TyKonKet** [comment]
Should be fixed with 712078f8492927a37da76fbb61906368ccd0d23b
Let us know.

**Comment by eddiem54** [comment]
Fixed, thank you.
