### ISSUE TITLE
Punkte löschen - Kurse vom Server laden

### ISSUE THREAD

**Issue by Moitzbert** [Stephan-S/FS19_AutoDrive#814]
Gibt es eine Möglichkeit die Funktion abzustellen, die nach jedem Löschen eines Punktes die gesamten Kurse mit dem Server synchronisiert ?
Dauert ansonsten sehr lange wenn man auch nur ein paar Punkte löschen möchte.

Mfg
Christof

**Comment by Iwan1803** [comment]
Offline machen und dann erst online hochladen?

**Comment by Bandesss** [comment]
Ja auf einem Server dauert es einfach zu lange.

**Comment by TyKonKet** [comment]
Hey guys, what version of the mod are u using?
The last released https://github.com/Stephan-S/FS19_AutoDrive/releases/tag/1.0.6.7 ?

**Comment by Moitzbert** [comment]
Using the latest release

**Comment by TyKonKet** [comment]
Ok, the problem have been fixed, I think this weekend a new version will be released with all the MP improvements done this week

**Comment by Moitzbert** [comment]
perfect, thx TyKonKet !
