### ISSUE TITLE
AutoRecalculate setting not applied on server

### ISSUE THREAD

**Issue by Bandesss** [Stephan-S/FS19_AutoDrive#815]
Hallo nutzte die neuste Version von ad
Wir spielen auf einenm Server und das Auto Neu Berechnen steaht auf an
Auf einem Server ist das sehr von Nachteil, könnt ihr das wieder ändern das es auf nein steht ?
Danke für den Mod

**Comment by Stephan-S** [comment]
Die Einstellung für's Autoneuberechnen sollten eigentlich mit dem Server synchronisiert werden. Sprich wenn du oder ein anderer Spieler es ausstellen, sollte es auch auf dem Server aus sein.
Ist das nicht der Fall?

**Comment by TyKonKet** [comment]
We are closing this issue because of a long time inactivity, If the issue still persists with the latest versions, feel free to open it again.
