### ISSUE TITLE
After last commit, you cant start autodrive anymore

### ISSUE THREAD

**Issue by Bobster82** [Stephan-S/FS19_AutoDrive#816]
Hey @Stephan-S ,

After ur last commit (continue after 0,01) I cant start any route.. pressing start and nothing happens

edit: I used a version that I downloaded yesterday, so I dont know what commits u done in the mean time :P

**Comment by pCornetto** [comment]
Hi,

got the same issue.

AD is not starting when pressing the start button.
Only once the selected destination point is switched to another and then back, the start button is working properly again.

I've also tried the commit released approx. 1 hour ago (Trailer will continue after unload is done now).

Greetings

**Comment by Bobster82** [comment]
Thanks for the fix @TyKonKet

**Comment by TyKonKet** [comment]
No problem, it was my fault and I had no time to fix it yesterday, I'm so sorry.

**Comment by Bobster82** [comment]
> No problem, it was my fault and I had no time to fix it yesterday, I'm so sorry.

I do like you say its your fault, but the excuse is too much ;) I know its easy to make mistakes (just starting to learn a bit of programming, as I want to understand what u guys do and maybe one day even help out ;) )
You do a pretty good job! I like the way you work!

**Comment by TyKonKet** [comment]
Thanks
