### ISSUE TITLE
Editor and Autodrive

### ISSUE THREAD

**Issue by badfly** [Stephan-S/FS19_AutoDrive#817]
Good day Stephan! There is a small request from the editor:
1: Make the mode selection buttons change color when turned on. For example, red when turned on, blue when turned off. Now it is, but it does not always work.
2. Make it possible to select a folder when editing a destination.

 And by AutoDrive. Is it possible to somehow reduce the speed when the driver goes to the nearest point. In this version, he goes there at maximum speed, and when he reaches it, he does not have time to turn, after which he stray from the course. Sorry for my English, I hope you understand me)) (google translator)

**Comment by TyKonKet** [comment]
Have you tried reloading the routes?

**Comment by badfly** [comment]
> Have you tried reloading the routes?

Sure

That's what I meant

[https://youtu.be/avBRt_RVx4Y](url)

**Comment by TyKonKet** [comment]
Try to disable 4-wheels stearing on the JCB

**Comment by Bobster82** [comment]
> Try to disable 4-wheels stearing on the JCB

Its a common problem for all vehicles... when AD drives straight to a line it doesnt slow down and goes in circles or just like the vid above ;)

**Comment by TyKonKet** [comment]
Is that a problem of recent versions or is it a long time problem?

**Comment by badfly** [comment]
long time problem

**Comment by SerGo84** [comment]
I have the same problem

**Comment by raupach** [comment]
@TyKonKet  I think we can close this improvement as I implemented it some time ago.

**Comment by Bobster82** [comment]
It works great now... @TyKonKet , u used pathfinder from current pos to closest waypoint when not close to a waypoint?
Thanks btw!
