### ISSUE TITLE
On streets only the Drive Lights should be on

### ISSUE THREAD

**Issue by Justice-Molton** [Stephan-S/FS19_AutoDrive#819]
Would it be easy to change, that only the main lights are on, on streets? Because it is forbidden to drive on streets with workinglights on.

**Comment by TyKonKet** [comment]
@Justice-Molton I agree with you, but someone esle asked to turn on all lights on streets...

**Comment by Iwan1803** [comment]
> ... it is forbidden ...

Then don't forget the turn signal and especially that it's just a game 😉

**Comment by Justice-Molton** [comment]
Yes it is, and this is just a suggestion.

**Comment by Justice-Molton** [comment]
@TyKonKet maybe this could be an option to tuen on or off.

**Comment by TyKonKet** [comment]
Yes, it could.

**Comment by Stephan-S** [comment]
Would need some overriding of default AI helper's use of lights I think.
But we can figure something out.

**Comment by Justice-Molton** [comment]
That would be cool

**Comment by SerGo84** [comment]
On my opinion, would be very good, if @Stephan-S add a few buttons to the main panel for manage ligts or add some switches in options /sorry for my English, don*t using any translators
