### ISSUE TITLE
Target added not showing up in dropdown menu.

### ISSUE THREAD

**Issue by MiSpA51** [Stephan-S/FS19_AutoDrive#820]
Hi,

When i add a target to AD it doesnt show up.
I only see the first target I made. Even after updatting the ways.

![image](https://user-images.githubusercontent.com/57526601/68470522-86ac4c80-021c-11ea-8bd1-318c99967ff5.png)

Its on a Dedicated Multiplayer server.

**Comment by TyKonKet** [comment]
MP or SP?

**Comment by TyKonKet** [comment]
And is it a brand new savegame?
On a map without basic routes setup, right?
What version of the AD are you using?

**Comment by raxtor** [comment]
@MiSpA51 use mouse scroll wheel... anyway should be fixed too..roll up list to firs point of list automatically...

**Comment by MiSpA51** [comment]
Hey Guys,

Very fast responce! Awesome.
raxtor his advice worked. Scrolling did the trick.

TyKonKet, its latest version and MP/Dedicated server.
