### ISSUE TITLE
Bugs in Autodrive FS 19 mod

### ISSUE THREAD

**Issue by raxtor** [Stephan-S/FS19_AutoDrive#821]
Guys, its just for fun... 
I was playing with Open AI here https://talktotransformer.com/
Its a "fake news" software in new version 2.

My input was **"Bugs in Autodrive FS 19 mod"**

See the result:
Bugs in Autodrive FS 19 mod

If you are having issues with Autodrive FS 19 mod, the following will fix it for you:
1: Download the file with the fix.
2: Download the file and unpack the folder that is there.
3: Place the Autodrive FS19_Fix folder inside the Autodrive FS19 folder.
This will fix the bugs and make the mod functional.
Autodrive FS 19 mod on steam.
In Autodrive FS 19 mod, you will get to the main menu.
There you will see two options: "Change Settings" and "Start Autodrive".
Select "Change Settings".
Select "Auto Drive" option.
Select "Launch Autodrive" option.
Autodrive FS 19 mod will start.
If you want to play multiplayer games, select the "Multiplayer" tab and then click the...

Isnt it impressive? :-)

**Comment by Bobster82** [comment]
But what does it do exactly? does it write some code? , does it change some names, does it archive it the correct way?

**Comment by Stephan-S** [comment]
Interesting :D 
But I'm working on closing issues, so this one has to go as well @raxtor :D

**Comment by raxtor** [comment]
If it will improve your score, why not.. :-)
