### ISSUE TITLE
New setting: On route finished: -Return to start / stay / park

### ISSUE THREAD

**Issue by Bobster82** [Stephan-S/FS19_AutoDrive#823]
A suggestion/enhancement for pickup and deliver mode:
When I use that mode, for example 2 loops, it stops at the deliver point. Is it possible that the vehicle can be brought back to the pickup point and then print the stop message?
After every loop runs I need to call my drivers back ;)

Thanks in advance!

**Comment by Iwan1803** [comment]
And i don't want that they drive back 😋
But a message would be nice 🤩

**Comment by Bobster82** [comment]
Maybe a setting then... So you can choose if u want it returned or not ;)

**Comment by jala15** [comment]
And what about sending it to parking? It seems logical for me, but other people would prefer another option. The ideal, but harder to be done, would be by making it choosable by everyone

**Comment by Stephan-S** [comment]
So you want a new setting:
On route finished: -Return to start / stay / park

Makes sense!

**Comment by geo-luchs** [comment]
question would be: since the pickup destination is after the load trigger, how it could be avoid to load the trailer again? is the any chance to set the fruit to " empty"?? so it doesn't match to any fruit in the silo?

**Comment by geo-luchs** [comment]
for which modes it could be?

It would be nice also for unload tresher to have this function.
Stephan and CP already improved the working together, that harvester is waiting for unload before his end point. AD is unloading the not full harvester, and AD is driving back to silo even the filling level is not reached.
But then he is driving back to field. This makes no sense.

So such option to end at silo unload or load trigger makes sense for more than 1 mode.

**Comment by Stephan-S** [comment]
Quick solution, as used for park mode: Switch to drive mode and then sent him on it's way
