### ISSUE TITLE
Write english issues or at least titles!

### ISSUE THREAD

**Issue by KCHARRO** [Stephan-S/FS19_AutoDrive#826]
Guys, there are many issues that are in a language other than English, simply could we not all speak in the same language, English? We would understand each other better.

My language is Spanish and I simply use Google translate, so that this looks a bit more organized,

Just a suggestion ... mainly to the guys from Germany, who create the issues in their own language ...

**Comment by Bobster82** [comment]
Yup, would be my suggestion too... But I know stephan is german and thats why people just write in german ;)
Im from the netherlands and write english here, but I can understand german a bit

**Comment by raxtor** [comment]
In first step would be nice just use English title rule at least...

**Comment by RalfGorden** [comment]
ihr könnt doch auch den Google translate nehmen

**Comment by raxtor** [comment]
@RalfGorden Google is inaccurate in some technical terms. In addition AD dev team has new member and he is not speaking in German lang. Also for other non German AD users is hard to get which bug is reported by our german friends.

**Comment by Iwan1803** [comment]
It's sometimes very hard to explain a problem in english if you are not a native english speaker. So i think it's ok if you write it in an language Stephan and the other can understand.
The title should be in english and if someone is interested: use a translator (Google, DeepL.com, ...). 
And yes, i know, the translation is not the best, but should help to get an understand of the problem.

**Comment by Justice-Molton** [comment]
You’re absolutely right. English is the Language that most of the people are speaking. Is someone Not able to understand, it’s on his side get the homework done!!

**Comment by Stephan-S** [comment]
I appreciate if everyone who is able to properly write english and to communicate his issue/ideas to do so.
We could use some bot that automatically translates all german posts and adds the translation to the post :D

**Comment by Stephan-S** [comment]
I just added two templates for bug reports and the german one includes the directive to please translate at least the title :-)

**Comment by worker2419** [comment]
this tool also does a good job 
dieses Webseite funktioniert auch gut
https://www.deepl.com/translator

**Comment by geo-luchs** [comment]
Since  this issue is pinned in top and WE now have the new Templates everything should be Clear how to create  new issues.
I'closing now this issue
