### ISSUE TITLE
UI disappears after saving some Folders, and trying to store a new folder (MP, Dedi)

### ISSUE THREAD

**Issue by Justice-Molton** [Stephan-S/FS19_AutoDrive#827]
After I could manage to save some Folder, the UI is disappear if I hit the plus button. Only a reconnet bring the ui back.

**Comment by TyKonKet** [comment]
No errors in the log?

**Comment by Justice-Molton** [comment]
I need to look later. Now I'm off to work. In case I found something I'll  let you know

**Comment by Justice-Molton** [comment]
2019-11-08 16:07 C:/Users/justu/Documents/My Games/FarmingSimulator2019/mods/FS19_AutoDrive/scripts/HudElements/PullDownList.lua:360: bad argument #1 to 'insert' (table expected, got nil)
2019-11-08 16:07 Error: Running LUA method 'draw'.

**Comment by Stephan-S** [comment]
Just for clarification: You are using the current source files, right? Not the 1.0.6.7 release version.
Should be obvious since you can save folders, but just to make sure :-)

**Comment by Justice-Molton** [comment]
Yes I do

**Comment by raxtor** [comment]
@Stephan-S sry for next input, but isnt possible add any index for every commit done? like 1.0.6.8 or 1.0.6.7a etc.. cuz all github versions have old release number and it makes troubles for you and also for bug reporters how to identify their installation

**Comment by Stephan-S** [comment]
we are working on that @raxtor 
This will either happen by creating a script that automatically increments the version number for every commit (The one displayed in the HUD - not in the Mod manager)
Or as we will do it for now by incrementing an appended index. I just updated a version with 1.0.6.7-1
And now back to topic :-)

**Comment by raxtor** [comment]
You are better and better with every day!

**Comment by Dzi4d3k** [comment]
@Stephan-S I think that there is so much places in version numbering that we can cope without adding another number. Now we have 4 places call them A.B.C.D so:
- A is major version (maybe 2 will be for FS21)
- B for minor version, like huge new functionality
- C - patch version solves lot of issue, maybe smal changes in functionalities
- D - hotfix, fixes at least one issue, and can go even up to 999
What you thing about this?

**Comment by Justice-Molton** [comment]
https://en.m.wikipedia.org/wiki/Software_versioning
