### ISSUE TITLE
GUI (SP) moving wrong destination to folder

### ISSUE THREAD

**Issue by geo-luchs** [Stephan-S/FS19_AutoDrive#828]
Hello

In Edit Mode there are 2 buttons to move destinations to folder.
in line of first target and in line of second target.

But always it moved the destination of first target. This is confusing.

If I open the list for the unload destination:
![gui_bild_1](https://user-images.githubusercontent.com/53658780/68505795-67d3a780-0268-11ea-85a4-457764c01648.PNG)

and select to move the destination, I would expect that " Milch/Eierverkauf) would be moved.
![gui_bild_2](https://user-images.githubusercontent.com/53658780/68505861-905ba180-0268-11ea-8806-41c44c7afffb.PNG)

But it always moving the destination from 1. target , in this case "Feld 2"
![gui_bild_3](https://user-images.githubusercontent.com/53658780/68505890-a2d5db00-0268-11ea-8b52-a6d14e8c21ae.PNG)

several proposals:
a) give this button to move only in mode "drive"
b) if move is possible in all modes, show this button only once right of the first target
c) or assign the 2nd button to the 2nd target instead of always the 1st target

**Comment by Stephan-S** [comment]
Yeah you are right. I will go for a) I think.
Or dou you have a preference?
c) is also a good option!

**Comment by geo-luchs** [comment]
c) would be easier for users.
Otherwise everybody needs the knowledge to change first to Mode "drive". It's additional step.
with c) it's not important in which mode you are. 

Also I'm not so happy at all with the process to move a destination.

Because:
I'm creating a destination. It will be shown in Standard.
Then I'm selecting the destination, but the list will be closed again. Then I've to open the list again for reaching the move button. But currently I've no idea how to improve it. Only that in CP it's handled userfriendly ;-)

**Comment by worker2419** [comment]
You're right, but making the changes directly in the XML file is more for the "experts"

**Comment by Stephan-S** [comment]
A dedicated menu to sort/rename/delete folders would be nice.
I don't like to make the standard HUD to complicated by inserting all kinds of special functions into it.
But this is something for the longterm list

c) is on the short term list for now :-)

**Comment by Stephan-S** [comment]
c) is done :-) forgot to mention it in the commit message

**Comment by geo-luchs** [comment]
Test ok :-)
