### ISSUE TITLE
Seeder tank support with dedicated loading pipe position

### ISSUE THREAD

**Issue by raxtor** [Stephan-S/FS19_AutoDrive#829]
It seems AD still doesnt support big seeder tanks. 
Seeder tank only opened covers but refilling didnt start and vehicle continues to next point.
![fsScreen_2019_11_08_21_35_07](https://user-images.githubusercontent.com/831266/68509104-7756ee80-0270-11ea-85bf-28c4b95f93ff.png)
![fsScreen_2019_11_08_21_34_21](https://user-images.githubusercontent.com/831266/68509108-7aea7580-0270-11ea-84a6-1dd6db725c22.png)

**Comment by Woife1** [comment]
Work this seeder in this position with manuell refill?
it looks like the fill trigger is not under the pipe

**Comment by raxtor** [comment]
@Woife1 Hm, you are right, this tanks has triggers ony from pipe side! BUt here is other hidden problem. Seeder tank missed Seeds silo. I seems pipe is opened too late so he is only taking fertilizer.
![tank](https://user-images.githubusercontent.com/831266/68516501-7fb92480-0284-11ea-9b4e-5736a5a0e5c4.png)

**Comment by Woife1** [comment]
try a closer point to the seeds may this works   
you have also set seeds for filling? (don't know which language you use)

**Comment by raxtor** [comment]
Yes, tried both fillTypes.. fert and seeds too, works only fertilizer.. Amozon 1500 works ok in this config and he has also 2 tanks. 
I cant go closer because 2nd part of seeder is too wide, but its not problem when I know it now, I have extra route for testing.

**Comment by Woife1** [comment]
i meant destination point closer to the seeds 
maybe for this seeder you could use in the settings a longer range for trigger (50m or so)

**Comment by raxtor** [comment]
Its working ok, I had contact for manual refill for Seeds silo. R was active so AD detected trigger corectlly... but pipe is unfolded too late imho
![fsScreen_2019_11_09_00_20_08](https://user-images.githubusercontent.com/831266/68517183-ce67be00-0286-11ea-825a-90e45e96499e.png)
![fsScreen_2019_11_09_00_20_13](https://user-images.githubusercontent.com/831266/68517184-cf005480-0286-11ea-9d78-db80e2dfc960.png)

**Comment by raxtor** [comment]
Well, it help for pipe unfolding timing. Now its pipe unfolded, but I found problem. Seeder always open as 1st fertilizer tank, so thats why he is always misssing Seeds trigger.. also no "R" in menu. No idea if its bug and can be fixed somehow or I ahve always 1st silo fertilizer and 2ns seeds.
![tank](https://user-images.githubusercontent.com/831266/68517544-4e425800-0288-11ea-8fd7-a4faa7506461.png)

**Comment by raxtor** [comment]
Anyway thx for input @Woife1

**Comment by Woife1** [comment]
you can switch them when you get this as mod 
there are only a few changes in the xml ;)

**Comment by Woife1** [comment]
have you already test the next bigger seeder car? maybe this works 
(i didn't test/use this big seeder until now)

**Comment by raxtor** [comment]
sure, its one of solutions.. anyway if AD devs will get any idea if is able check trigger fillType and than change pipe postion by AD.
Still I tested this one FS default and one moded CaseIH.

**Comment by Stephan-S** [comment]
Yeah should be possible by script but it's one of those features that is only related to few vehicles and few players. So I put this in as 'long-term for now'
Btw: @raxtor you haven't commented on the Auto-recalculation :p

**Comment by raxtor** [comment]
I tested it when it was commited and nothing happened to me when I did new part of network and start AD (ofc was allowed in settings). I tried add new waypoint and atrach it to another vehicle and auto recalculation wasnt triggered too, so I thought its not finished yet.
I still didnt test it properly but will let you know here. Thx 👍

**Comment by raxtor** [comment]
@Stephan-S Auto recalc seems working perfecly, Thx, good job.

**Comment by Iwan1803** [comment]
Please update to 1.1.0.5-RC5, try again and if the problem still exists, then open a new issue.
*Bitte aktualisiere auf 1.1.0.5-RC5, versuche es erneut und und wenn das Problem weiterhin besteht, erstelle ein neues Issue.*
