### ISSUE TITLE
Nur ein Paar fragen

### ISSUE THREAD

**Issue by Mannie313** [Stephan-S/FS19_AutoDrive#83]
Ich wollte mal fragen ob es möglich ist Courseplay als helfen mitanzusehen wie den Originalen Helfer. Das man die Autos vom spiel nicht immer zum stehen bringt wen man AutoDrive an hat.
Zählen Häcksler auch als drescher oder werden die seperat behandelt.

MFG Mannie313

**Comment by Stephan-S** [comment]
Da AutoDrive den Verkehr nicht unterstützt, empfehle ich den Verkehr auszuschalten. AutoDrive könnte ihn zwar erkennen, aber das automatische Anhalten der Fahrzeuge kann ich leider nicht verhindern.

Häcksler haben keinen internen Speicher den AutoDrive abtanken könnte, also werden sie auch nicht unterstützt.
