### ISSUE TITLE
Mode unloading combine with forage Harvester

### ISSUE THREAD

**Issue by Alkoholix** [Stephan-S/FS19_AutoDrive#831]
I don´t know, maybe i had the wrong search terms, i haven´t found anything to my problem with crop cutters like Claas DirectDisc or Krone XDisc and any other similar tools. 
AutoDrive seems to not detect a waiting combine harvester (or spfh in this case) with a mounted direct disc cutter, regardless of whether cutting grain or grass.

My regards,

**Comment by Stephan-S** [comment]
Are you talking about standard forage harvesters?
They should be supported if you enable precall and chase combine in the settings menu.

**Comment by Alkoholix** [comment]
Thank you for your reply.
I tried and after some testing i found out that only one mod map creates the issue. The settings are correct, but no harvester could be found. I try circling the problem but it will take some time.
