### ISSUE TITLE
Cotton trailer support

### ISSUE THREAD

**Issue by Mannie313** [Stephan-S/FS19_AutoDrive#835]
Hallo @Stephan-S. ist es möglich das ich beim Abholen und Abliefern auch Baumwolle auswählen kann. Ich kann Baumwolle auch alternativ mit dem Drescher ernten.

MFG Mannie313

**Comment by Stephan-S** [comment]
Nein, AutoDrive unterstützt aktuell kein Transportgut, das nicht als Schüttgut transportiert und mit 'R' geladen bzw. 'I' abgeladen werden kann.
Das kann irgendwann in ferner Zukunft mal angedacht werden, ist aber aktuell nicht implementiert

**Comment by Stephan-S** [comment]
Und nutze doch bitte aussagekräftige Titel. So fängt niemand was damit an ;-)

**Comment by Mannie313** [comment]
Ich hab es ja als loses schüttgut auf meiner map. Kann es auch im Hofsilo lagern und als solches auch verkaufen.

MFG Mannie313

**Comment by Stephan-S** [comment]
wenn es auf der Karte als fillType eingetragen ist, taucht es auch im AD Menü auf eigentlich

**Comment by Mannie313** [comment]
<fillType name="COTTON" title="$l10n_fillType_cotton" showOnPriceTable="true" pricePerLiter="1.252" >
            <image hud="hud/hud_fill_cotton.png" hudSmall="hud/hud_fill_cotton_sml.png" />
            <physics massPerLiter="0.23" maxPhysicalSurfaceAngle="15" />
            <pallet filename="$data/objects/pallets/fillablePallet/fillablePallet.xml" />
        </fillType>

So steht es bei mir drin. Wird beim ad aber nicht angezeigt.

MFG Mannie313

**Comment by Stephan-S** [comment]
Hab gerade gesehen das AD Baumwolle noch auf der gestrichenen Liste stehen hatte.
Ich habe es davon runtergenommen. Wenn du dir selber das zip aus den aktuellen Quelldateien baust, sollte es gehen

**Comment by Mannie313** [comment]
Danke Sehr. Ist ein sehr gelungerner mod geworden.

MFG Mannie313
