### ISSUE TITLE
Automatisches Auftanken / automatic refueling

### ISSUE THREAD

**Issue by altbier1** [Stephan-S/FS19_AutoDrive#836]
Ist es möglich bei Autodrive wie bei CP eine Auftankfunktion zu integrieren? Diese Funktion wäre vorallem beim Transport von grossen Mengen sehr praktisch und das Fahrzeug bleibt nicht leer auf der Karte stehen.

Is there any possibility to add a feature for automatic refueling into Autodrive like it works at CP? It would be a nice feature ...

**Comment by HerrchenChris** [comment]
Auftanken im Sinne von Diesel nachtanken ab x% Tankinhalt?
Ja, das würde mir auch zusagen :-)

**Comment by haamic** [comment]
Ist wohl bereits auf der todo Liste, hat aber keine priorität. Tanken ab x% oder immer im vorbeifahren, wenn man gerade an einer Tankmöglichkeit vorbei fährt, wäre schon eine gute Erweiterung. Üben wir uns in Geduld, das wird schon.

**Comment by Stephan-S** [comment]
Korrekt. Steht auf meine Todo Liste. Bin leider immer noch nicht dazu gekommen, bei den ganzen Bugs die ich aktuell bearbeite.
Ich mache dann aber hier mal zu um Übersicht zu behalten.
