### ISSUE TITLE
AD wont refuel with the latest version 

### ISSUE THREAD

**Issue by evansv2** [Stephan-S/FS19_AutoDrive#838]
don't want to bug too much, but for some reason it doesnt refill for fuel any more
its as if though its trying to refuel to the trailer , because when Unhooking equipment, it doesnt even go to the gas station.... 

https://www.youtube.com/watch?v=mlYtBO1LyKw

**Comment by evansv2** [comment]
or refuel was never implemented? I snooped through the code, just saw that trailers for the most got filled but the vehicles I didnt see none, so this may be my mistake

**Comment by Stephan-S** [comment]
AD never did refuel the vehicle.
I have this on my todo list though.
But with automatic route planning to the closest fuel station.

So I close this issue here in favor of the longterm todo item :-)
