### ISSUE TITLE
Enhancement: Show targets on map and make clickable for target transfer - Ziele auf Karte anzeigen und klickbar machen für Zielübernahme

### ISSUE THREAD

**Issue by haamic** [Stephan-S/FS19_AutoDrive#839]
Translated with www.DeepL.com/Translator

Hello 
is it possible to display the saved destinations in the ESC menu on the large map view? maybe even make them clickable there for the destination transfer to AD? Right click target A, left click target B.
With large maps and many destinations, you lose the overview of whether you already have a destination for the field you want to drive to. ("Contract Mission"). 
Maybe Todo for later
Greetings Micha

Hallo 
ist es möglich die gespeicherten Ziele im ESC-Menü auf der grossen Kartenansicht anzeigen zu lassen? evtl. sogar dort klickbar für die Zielübernahme nach AD zu machen? Rechtsklick Ziel A, Linksklick Ziel B.
Bei grossen Karten und vielen Zielen, verliert man die Übersicht, ob man bereits ein Ziel für das jeweilige Feld hat, das man anfahren möchte. ("Verträge-Mission"). 
Vielleicht Todo für später
Gruss Micha

**Comment by Stephan-S** [comment]
Sounds like a good idea. I'm not sure it is possible yet, but I would also like to look into it

**Comment by geo-luchs** [comment]
you mean : it should be like  the hotspots for the productions we have in NF marsch prods e.g.
sounds good.

**Comment by Iwan1803** [comment]
I don't think that this is possible on the minimap, but maybe on the map if you press ESC.
For that it must be possible to see the targets.

**Comment by haamic** [comment]
Hello, 
The destinations are now displayed on the small map.  Are they really only visible, or somehow clickable, for target takeover in AD?  Will they be shown on the big map (ESC menu) later? 
Greetings Micha 
++++++++++++++++++++++++++++++++++++++++
Hallo,
die Ziele Werden jetzt auf der kleinen Karte angezeigt. Sind sie wirklich nur zu sehen, oder irgendwie auch klickbar, Für Zielübernahme in AD? Werden sie auch später mal in der grossen Karte (ESC-Menü) angezeigt?
Gruss Micha

**Comment by Iwan1803** [comment]
Sie sind wie alle Ziele nur sichtbar. In der großen Karte (ESC) kann man dort auch hin springen.
Ich vermute mal, das die Spielmechanik eine Erweiterung in der großen Karte nicht zu lässt.
Aber die Anzeige ist schon echt nice und hilfreich 👍

**Comment by haamic** [comment]
So hatte ich mir das ja auch vorgestellt, als ich das vor 1 Monat vorgeschlagen hatte.
Zur zielübernahme draufklicken wäre noch super, aber man kann eben nicht alles haben.
@TyKonKet  Danke für die Umsetzung
+++++++++++++++++++++++++++++++++++++++
That's how I had imagined it when I suggested it 1 month ago.
Clicking on it to adopt the target would still be great, but you can't have everything.
@TyKonKet Thanks for the implementation

**Comment by haamic** [comment]
Hello,
would it be possible to display the destination of the current vehicle on the map in colour and flashing?
+++++++++++++++++++++++++++++++++++++++
hallo,
wäre es umsetzbar, das das Ziel des aktuelle Fahrzeuges auf der Karte farbig und blinkend angezeigt wird?
