### ISSUE TITLE
Mit AutoDrive Maishäcksler entladen/With AutoDrive Unload corn chopper

### ISSUE THREAD

**Issue by kferrano** [Stephan-S/FS19_AutoDrive#840]
AutoDrive Version: 1.0.6.7
Release or selbsterstelltes zip: Release
Fahrzeug(art) (falls relevant): Traktor mit Anhänger und Maishäcksler

**Beschreibe den Bug**
Ich möchte mit AD meinen Mais Häcksler abfahren, aber er lässt sich nicht beladen, sondern fährt kurz hin, der Häcksler fährt los und kurz darauf fährt er wieder weg. 

Der Mais-Häcksler fährt mit CoursePlay und das Abfahren mach ich mit AutoDrive,

**Falls anwendbar - Schritte mit denen ich den Bug nachstellen kann**
AD Course mit Drescher Abfahren und Häcksler CoursePlay Feldkurs ernten

**Screenshots**
https://youtu.be/ExaKOjKKeHU

**Comment by RalfGorden** [comment]
hallo ich ernte auch gerade mit dem Mais Häcksler  fahre ihn aber selber , hab 6 Abfahrer im Einsatz mit AD bis jetzt einfach super keine Probleme

**Comment by Stephan-S** [comment]
Should be fixed now. There was a problem with the front collision sensor triggering right after the approach to the combine. This is now ignored when the chase side is behind the combine
