### ISSUE TITLE
MP: unloader can't find way back to goal at the field

### ISSUE THREAD

**Issue by Bandesss** [Stephan-S/FS19_AutoDrive#841]
AutoDrive Version: Aktuellste Version
Hallo zusammen stell den Abfahrer ein.... aber wenn er seinen Punkt erreicht.... schaltet sich ad ab
Wir spielen Mulitplayer.
Siehe Bild
![20191110120709_1](https://user-images.githubusercontent.com/50829319/68543078-cd33af80-03b2-11ea-9942-deccd9c838c1.jpg)
Es kommt die Meldung konnte keine Route zum Drescher finden.
Keine ahnung was das ist 
Hoffe auf Hilfe

**Comment by RalfGorden** [comment]
ich nehme die 1.0.6.7 selbst gepackt von gestern da geht es

**Comment by Bandesss** [comment]
Hallo @RalfGorden hab die aktuellste Version von 2-3 Stunden

**Comment by RalfGorden** [comment]
wie soll das hier gehen

**Comment by Bandesss** [comment]
In dem du es bei Filehost.de hoch ladest und hier verlinkst ;) 
VIelen dank, wie gesagt wir haben das Problem auf einem Server

**Comment by Iwan1803** [comment]
Hello,
i've downloaded latest version as Github Zip some minutes ago and started 3 unloader. All reached the start point at the field and stayed active, but this was in Singleplayer.
Are you sure, that the versions on the server and local are the same?

**Comment by RalfGorden** [comment]
[url=https://filehorst.de/d/deDeppyk]Datei von filehorst.de laden[/url]

**Comment by Bandesss** [comment]
Ja sind gleich sonst würde ich ja nicht auf den Server kommen bei verschiedenen mods

**Comment by RalfGorden** [comment]
https://filehorst.de/d/deDeppyk

also bei mir geht sie super

**Comment by Bandesss** [comment]
Danke

**Comment by Bandesss** [comment]
Das Problem ist das Ad sich ausschaltet

**Comment by Iwan1803** [comment]
So the problem is now, that the uploader can't find a way back to the point at the field?

**Comment by Bandesss** [comment]
Kurse sind slle vorhanden und es funktionierte immer.....

**Comment by Iwan1803** [comment]
Then downgrade to an older version and check again, please.

**Comment by Bandesss** [comment]
Ok mit der Verison @RalfGorden scheint es zu gehen.
Danke @RalfGorden
