### ISSUE TITLE
Question: settings for a corn choppern

### ISSUE THREAD

**Issue by kferrano** [Stephan-S/FS19_AutoDrive#842]
Which values do I have to change so that the tractor drives next to the corn chopper and not behind it?

https://steamuserimages-a.akamaihd.net/ugc/759348058675123628/89C38253DFDC9BE42BC5759DF26CC6B9F44F3C4D/

https://steamuserimages-a.akamaihd.net/ugc/759348058675123811/BD5E4F70DC6F97E9F55A7013023C670779F23694/

**Comment by RalfGorden** [comment]
![fsScreen_2019_11_10_12_43_06](https://user-images.githubusercontent.com/56214377/68543468-c8bdc580-03b7-11ea-937e-78dd8d9c5398.png)
![fsScreen_2019_11_10_12_43_15](https://user-images.githubusercontent.com/56214377/68543469-c9565c00-03b7-11ea-9292-0aa10ab60311.png)
so sind meine bin zufrieden damit

**Comment by kferrano** [comment]
aber wieso Abfahrer finden: nein? muss der nicht auf Ja stehen damit einer Abfahren kommt?

**Comment by Iwan1803** [comment]
Wenn das auf "Ja" steht, dann sucht der Drescher sich seinen Abfahrer selber aus und das muss nicht unbedingt der sein, den du gerne zuordnen möchtest.

**Comment by kferrano** [comment]
ok und wie ordne ich im AD einen Drescher zu?

**Comment by Iwan1803** [comment]
Das einzige, was ich weiß: sie müssen das gleiche Ziel eingestellt haben.
Wenn da mehrere stehen und ein Abfahrer von einem Drescher etc. gerufen wird, dann müsste der erste losfahren (wenn das Abfahrer finden auf "nein" steht).
Da ich für die Feldarbeit (und bes. für Häcksler) CoursePlay nutze, kann ich dir da leider nicht helfen.
Hast du die Einstellungen von Ralf denn mal ausprobiert?

**Comment by kferrano** [comment]
Bei den einstellungen von ralf fährt der Traktor dem Drescher immer hinten drauf. oder das ist so ein Stop and Go von beiden das zwar geerntet wird aber der Anhänger sich nicht füllt

**Comment by Stephan-S** [comment]
Bitt Version 1.0.6.7-3 ausprobieren.
Da habe ich nochmal einen Fehler behoben bei dem beim dem Abfahrer die Frontkollision durch den Drescher angeschlagen hat und er erst wieder pausiert hat.

**Comment by kferrano** [comment]
Ich benutze die 1.0.6.7-3   hab beim Claas jetzt das entlade rohr verlängert und jetzt klappt es. Nur wenn der Abfahrer voll ist fährt er nicht am Drescher vorbei sondern bleibt dahinter, da anscheinend der Abstand zum Häcksler zu gering ist

![image](https://user-images.githubusercontent.com/28959314/68544363-b39a6400-03c2-11ea-9bb3-116ff7c019a5.png)


So stehen die schon ne weile, der Trecker ist voll aber fährt nicht vorbei, erst wenn ich den Drescher etwas vorfahre klappt es
`

**Comment by RalfGorden** [comment]
also bei mir fährt keiner hinten drauf  und und das ja bei Drescher folgen hab ich nur wenn ich Mais häckseln tue  mit ein Häcksler

**Comment by RalfGorden** [comment]
> 
> 
> Bei den einstellungen von ralf fährt der Traktor dem Drescher immer hinten drauf. oder das ist so ein Stop and Go von beiden das zwar geerntet wird aber der Anhänger sich nicht füllt

dann hast du die falsche Version von AD

**Comment by kferrano** [comment]
Ralf hat sich schon erledigt, aktuell ist es halt das problem

> Ich benutze die 1.0.6.7-3 hab beim Claas jetzt das entlade rohr verlängert und jetzt klappt es. Nur wenn der Abfahrer voll ist fährt er nicht am Drescher vorbei sondern bleibt dahinter, da anscheinend der Abstand zum Häcksler zu gering ist
> 
> ![image](https://user-images.githubusercontent.com/28959314/68544363-b39a6400-03c2-11ea-9bb3-116ff7c019a5.png)
> 
> So stehen die schon ne weile, der Trecker ist voll aber fährt nicht vorbei, erst wenn ich den Drescher etwas vorfahre klappt es
> `

**Comment by Stephan-S** [comment]
kurze Frage: Ist die Fruchtumfahrung aktiviert oder nicht?

**Comment by kferrano** [comment]
Nein ist nicht aktiv, sobald ich den Drescher ein stück vorfahre fährt der Trecker los, auch durch die Frucht

**Comment by Stephan-S** [comment]
Dann schalte die Fruchtumfahrung an, damit er einen Kurs berechnet der nicht durch die Frucht führt. Dann steht auch der Drescher hoffentlich nicht mehr im geplanten Weg

**Comment by kferrano** [comment]
Hab ich getan, dennoch steht der Drescher im weg, der Trecker fährt halt lediglich in die andere Richtung, aber im selbigen winkel. kannst du sonst vllt. einbauen das er Z.B. 1-2 Meter zurück setzt damit er abfahren kann.
