### ISSUE TITLE
Q: range in which the combine is looking for a tractor?

### ISSUE THREAD

**Issue by kferrano** [Stephan-S/FS19_AutoDrive#843]
Would it be possible to increase the range in which the combine is looking for a tractor?

**Comment by Iwan1803** [comment]
If the tresher and the unloader has the same goal, there should be no problem to find him.

**Comment by geo-luchs** [comment]
@kferrano : if tresher is nearly full, please sit in unloader. What AD is telling you in title bar? Does he says: drive to tresher? or still waiting?

As @Iwan1803 already wrote, both needs the same destination.

But I habe seen several times, that unloader tells me :  drive to tresher, but then he couldn't find any path and AD stops.

Then I was driven manually in front of start point, and started AD again, and then he found the path.
This is sometimes strange, that he can't find the path.

So for now, your response is important, if you already set both upper targets in AD (for tresher and unloader) to same destination

**Comment by Woife1** [comment]
if AD stops while calculating a path to the combine it is only couse AD had not the time the calculation needs 
there is an option in the combine menu with this you could set a higher or less time to calculate (just test it, i have it @ 1.5/2x)

**Comment by geo-luchs** [comment]
yes, I tried also 3x, but sometimes it doesn't find the path anyway

**Comment by Woife1** [comment]
@ 3x it shouldn't stop in 99,99% 
couse there is always time for fallback mode
