### ISSUE TITLE
The driver does not drive properly for unloading

### ISSUE THREAD

**Issue by Mannie313** [Stephan-S/FS19_AutoDrive#846]
![fsScreen_2019_11_10_17_11_27](https://user-images.githubusercontent.com/3021040/68547209-2b768780-03df-11ea-8d43-fd0b0488c2af.png)
Driver does not drive properly unloading remains in front of the trigger and after unloading he stops station point and stops driving. Turn it off and immediately it comes back as the screenshot in the message.Driver does not drive properly unloading remains in front of the trigger and after unloading he stops station point and stops driving. Turn it off and immediately it comes back as the screenshot in the message.

MFG Mannie313

**Comment by Mannie313** [comment]
Sorry @TyKonKet

**Comment by TyKonKet** [comment]
@Mannie313 Oh don't worry, no problem

**Comment by Iwan1803** [comment]
Please add the missing informations as described in this template:
https://github.com/Stephan-S/FS19_AutoDrive/blob/master/.github/ISSUE_TEMPLATE/default-bug-report.md

**Comment by Iwan1803** [comment]
A new version was released. Please do the update and then try again.

**Comment by bojanh66** [comment]
If i have 2 trailers attached to tractor in Pickup and Delivery mode, tractor will not unload 2nd trailer at delivery point, unless i press Continue.
Version is latest 1.0.6.8
