### ISSUE TITLE
MP: Load mode -Driver does not stop when loading trailer & trailer doesnt get fully filled

### ISSUE THREAD

**Issue by GitTomahawk** [Stephan-S/FS19_AutoDrive#848]
AutoDrive Version: 1.0.6.7-9
Release or selbsterstelltes zip: GIT
Karte (falls relevant): Alle
Fahrzeug(art) (falls relevant):

Pickup and deliver und Load mode beladen die Ladefläche und Anhänger nur teilweise.
Der Abfahrer hält an der Beladestelle nicht komplett an und fährt wärend des Beladens langsam weiter.

**Comment by Iwan1803** [comment]
Bitte auf die aktuelle Version 1.0.6.8 aktualisieren und dann erneut probieren.

**Comment by GitTomahawk** [comment]
Tritt bei 1.0.6.8 auch auf - aber nur im MP

**Comment by GitTomahawk** [comment]
keine Veränderung in 1.0.6.8

**Comment by GitTomahawk** [comment]
Fehler besteht in release 1.0.6.9 noch

**Comment by TyKonKet** [comment]
We are closing this issue because of a long time inactivity, If the issue still persists with the latest versions, feel free to open it again.
