### ISSUE TITLE
1.0.6.8 zip wrong Version number displayed

### ISSUE THREAD

**Issue by GitTomahawk** [Stephan-S/FS19_AutoDrive#849]
AutoDrive Version: 1.0.6.8
Release or custom zip: Release
Map (if applicable): All
Vehicle / type (applicable):

Version im Moddesc is 1.0.6.7

**Comment by Iwan1803** [comment]
modDesc.xml contains the old version number, but i corrected it.

@Stephan-S 
Don't know if there is a process to create a new ZIP file, but could you recreate it?

**Comment by Flashsolutions** [comment]
@Stephan-S I think the author only meant that he edited the modDesc.xml to update the version number and then recreated the zip file that is loaded into the mods folder?
