### ISSUE TITLE
Unloader does not find the corn chopper

### ISSUE THREAD

**Issue by RalfGorden** [Stephan-S/FS19_AutoDrive#850]
hallo hab die 1.0.6.8 getestet bei mir läuft sie nicht ,wenn der Abfahrer zum Maishäcksler fahren will startet er kurz  und fährt dann nur im Kreis hab es mit verschiedenen Traktoren getestet überall das gleiche, hab jetzt wieder die 1.0.6.7 drauf von vorgestern da läuft alles wunderbar

**Comment by Iwan1803** [comment]
Ist es ein Claas-Häcksler oder ein anderer Mod oder alles nur Standardfahrzeuge? Welcher Anhänger wird genutzt?
Ich habe es mit einer bestimmten Kombi auch, das der Abfahrer am Start der weißen Linie kreiselt, aber bei mir ist es unabhängig von der AD-Version.

**Comment by RalfGorden** [comment]
hallo ich hab doch geschrieben das es mit 1.0.6.7 geht ,es ist ein Krone Mod

**Comment by KCHARRO** [comment]
It doesn't work with CLAAS either: Tucano and Lexion 8900.

With Dominator 108 if it works perfect.

**Comment by Stephan-S** [comment]
Hallo,
habe eben noch einen Bug den ich mit der 1.0.6.8 eingebaut habe behoben und noch ein paar Kleinigkeiten angepasst. Könntet ihr bitte die aktuellen Quelldateien probieren Also di 1.0.6.8-2
Vielen Dank
