### ISSUE TITLE
Unload loaded

### ISSUE THREAD

**Issue by pulimatrix** [Stephan-S/FS19_AutoDrive#852]
![fsScreen_2019_11_11_15_06_05](https://user-images.githubusercontent.com/46344269/68593372-984c5900-0495-11ea-903a-68395ad34b71.png)
AutoDrive Version: 1.0.6.8
Karte Multimap
Claas Axion960 DLC Hänger Cargo trailer MOD nicht DLC
Mit Version 1.0.6.6 ging das laden entladen wunder
mit der Version 1.0.6.8 Auch aber er biegt stänigt falsch ab, hat seinen kurs, habe nach versieben im mod ordner kurse neu berechnen lassen, ergab auch keinen erfolg.
habe aktuell auf version 1.0.6.6 zurück wo es ging.
Es ergab sich auch nicht aus der Log das da was Falsch Läuft lg

**Comment by pulimatrix** [comment]
Selbst bei Drescher abtanken verkeilen sie sich und zum abladen fährt er Über denn Trigger weiter ohne anzuhalten. ALso entweder läuft auf mein Rechner nix Richtig oder Irgendwas ist Schiefgegangen bei AD :/

**Comment by geo-luchs** [comment]
Komisch. Solch Verhalten hatte ich nur letzte Woche mit einigen 1.0.6.7er Versionen. Da war leider wirklich der Wurm drin.
Aber zum WE hin, zur 1.0.6.8 ist es wieder stabiler geworden.

Auf keinen Fall lasse ich neu berechnen, während auch nur 1 AD fährt. Damit hatte ich echte Probleme.
Oder wenn man , während AD aktiv war, am Streckennetz weiter Punkte gelöscht hat z.B.
Bin der Meinung, so was immer kurz vorher gemacht zu haben, wenn mal wieder nen Traktor völlig neben der Spur war.

Mal bitte bewusst  beobachten, nach einem Neustart vom LS 19, ohne Kurse bearbeiten oder neu berechnen, ob er dann immer noch falsch abbiegt, oder am Trigger überfährt.

**Comment by pulimatrix** [comment]
Ja macht er nach wie vor

![fsScreen_2019_11_11_22_26_25](https://user-images.githubusercontent.com/46344269/68622405-5beb1e00-04d2-11ea-962f-0ab76b31980c.png)
Rasst rein nur weil er hängen bleibt stoppt er -.-

Fährt voller KAnne durch die frucht war voher nicht!

![fsScreen_2019_11_11_22_09_53](https://user-images.githubusercontent.com/46344269/68622477-8341eb00-04d2-11ea-9e77-59ee3eea71d0.png)


er fährt an kurve langsamer dan beschleunigt er aus unerfindlichen grund!
![fsScreen_2019_11_11_22_04_17](https://user-images.githubusercontent.com/46344269/68622519-9a80d880-04d2-11ea-984b-f9736aa859ce.png)
![fsScreen_2019_11_11_22_14_30](https://user-images.githubusercontent.com/46344269/68622528-a076b980-04d2-11ea-916b-da873ccef699.png)

ich gebs heute auf!

**Comment by Stephan-S** [comment]
Lade Mal bitte deine config bzw Screenshots von den Einstellungen hoch. Danke

**Comment by pulimatrix** [comment]
https://filehorst.de/d/dIaqEJhJ die confic
![fsScreen_2019_11_11_22_48_28](https://user-images.githubusercontent.com/46344269/68623914-dcf7e480-04d5-11ea-8989-b2d30a4b377a.png)
![fsScreen_2019_11_11_22_48_30](https://user-images.githubusercontent.com/46344269/68623918-e08b6b80-04d5-11ea-9669-7949b3f06202.png)
![fsScreen_2019_11_11_22_48_33](https://user-images.githubusercontent.com/46344269/68623925-e4b78900-04d5-11ea-859b-2e578f8d9b4a.png)

**Comment by Stephan-S** [comment]
Gut, also bezüglich er fährt in den Drescher: Schau dir Mal deine Rohrabstand an. Den musst du unbedingt korrigieren. So zielt er ja in den Drescher rein.

Das Abladen scheint er ja anzufangen aber nicht korrekt zu pausieren. Das muss ich mir Mal anschauen

**Comment by pulimatrix** [comment]
Das ablade rohr hab ich auf 5 gestellt, aber das pausieren, der rast einfach durch, egal ob ich zurück peatche irgend wie ist der wurm drinnen, hab heute geupdatet und schwupp tauchten diese fehler auf weis ni zum geier was da los ist log ist fehler frei zeigt nix an :/

**Comment by Iwan1803** [comment]
@pulimatrix 
Stell das Abladerohr mal auf 0,5 oder 0,25m ein.

@Stephan-S 
mir ist am WE aufgefallen, das der Rohrabstand wieder auf 5m zurückgesetzt worden ist, wobei ich vorher bei allen den Abstand auf 0,25m gesetzt hatte.

**Comment by pulimatrix** [comment]
Iwan Hab ich gemacht dennoch hucht er dran vorbei, nur vom hänger ende wird er dan erprumbt gebremst :/

**Comment by pulimatrix** [comment]
So nach dem ich jetzt mal bissel probiert habe, hab die einstellung auf 1,5 meter abstand zum abladen gehts wunder bar, nur beim abladen fährt er mit vollem speed weiter, er ignoriert es völlig das er wo ich beschieftet hab zu halten fährt 3 pfeile weiter warum auch immer! lg

**Comment by Stephan-S** [comment]
@Iwan1803 Du hast vermutlich zwischendurch die Versionen gewechselt. In der 1.0.6.7 ist eine Abfrage auf versionsUnterschied drin, die dann den Abstand anpasst.

Damit wollte ich eigentlich abfangen, dass sich der Wert für User ändert, die nur die Release Versionen nutzen. Ich habe ja die Auswahl an Abständen erhöht und damit hat sich ja der gespeicherte Index verschoben.

@pulimatrix Er fährt also immer noch über den Abladepunkt drüber, korrekt?
Liegt dieser vor oder hinter deinem definierten Zielpunkt?

**Comment by pulimatrix** [comment]
Um es mal zu sagen habe z.b. Abladen Erdfrucht silo hinter dem trigger quasi 2 pfeile dahinter

<<Abladen Erdfrucht<<<Stillstand dess schleppers.

**Comment by pulimatrix** [comment]
wie du sehst, die klappe ist noch leicht geöffnet da fuhr er grade drüber, auch wenn ich zurück auf 1.0.6.6  mache keine veränderung :/ war vorher anders da hatte ich karotten geerntet mit dem selben schlepper da ging alles wunder bar :/
![fsScreen_2019_11_11_22_14_30](https://user-images.githubusercontent.com/46344269/68719500-86110e80-05ac-11ea-9dda-27e9014920de.png)

**Comment by Anger85** [comment]
Hallo ich habe die 1.0.6.8 mir gezogen aber leider kann er nicht mehr zwei Hänger entladen und die Fahrzeuge verlieren ihren kurs wenn er auf großen feldern unter wegs ist

**Comment by TyKonKet** [comment]
We are closing this issue because of a long time inactivity, If the issue still persists with the latest versions, feel free to open it again.
