### ISSUE TITLE
ingame-editor needs lot of power - Performance Einbrüche beim Editor Modus

### ISSUE THREAD

**Issue by kferrano** [Stephan-S/FS19_AutoDrive#853]
AutoDrive Version: 1.0.6.8
Release or selbsterstelltes zip: selbsterstelltes 
Karte (falls relevant): Alle
Fahrzeug(art) (falls relevant):

**Beschreibe den Bug**
Editor Modus zieht Performance runter. wenn ich den Editor Modus verwende brechen meine FPS extrem ein, meist um die 50%

**Falls anwendbar - Schritte mit denen ich den Bug nachstellen kann**
Editor Modus an/aus machen

**Comment by Iwan1803** [comment]
Die FPS brechen ein, sobald du den Editor-Modus aktivierst?
Single- oder Multiplayer?
Hast du in den Optionen vielleicht die automatische Neuberechnung aktiviert?

**Comment by kferrano** [comment]
Ja
Single
nein

**Comment by Stephan-S** [comment]
Welche Karte bzw. wieviele Wegpunkte hast du schon aufgezeichnet?
Er sucht in jedem Frame durch alle Punkte durch um zu entscheiden ob sie nah genug sind um gezeichnet zu werden oder nicht. Das könnte bei sehr großen Netzwerken schon etwas Perfomance kosten

**Comment by TyKonKet** [comment]
We are closing this issue because of a long time inactivity, If the issue still persists with the latest versions, feel free to open it again.
