### ISSUE TITLE
Q: liquid transport / refill - how to ?

### ISSUE THREAD

**Issue by bojanh66** [Stephan-S/FS19_AutoDrive#855]
I am using two tractors for this job, one is doing fieldwork (CP) with slurry tanker, other is transporting slurry from slurry pit to the field entrance and refilling the 1st one.

How do i make this to work without issues?

I tried to use Pickup and Delivery mode, start point is Slurry pit, delivery point is field entrance (also marked as slurry refill point).
This will work only under 2 conditions:
-if 1st tractor is empty, he will go straight to the refill point near the field and wait for 2nd tractor...2nd tractor approaches (detects unload trigger) and refill 1st tractor....but if 1st tractor is still doing fieldwork and 2nd tractor comes, he will not stop and wait for 1st tractor, he will just continue back to the slurry pit because he didnt detect any unload point
-if i have parked Kotte Garant FRC slurry container and if its not full (100%), 2nd tractor will refill it...but if Kotte FRC is full at 100%, 2nd tractor will not refill FRC (because its full) and will go back to slurry pit

Is there any easier way to use 2nd tractor for refilling slurry or to make it stop at field entrance and wait until 1st tractor comes for refill?

I know i can use CP Liquid Transport mode, but that would require to record route for each field separately, which can be a pain when you play on bigger map and have lots of fields.

So if someone can help me and explain, am i doing something wrong or Autodrive just cant stop at field entrance point, unless there is something with trigger for unload (Kotte FRC or tractor with empty slurry tanker waiting)

**Comment by geo-luchs** [comment]
maybe it could be an enhancement, to have an option  similar to "waiting at empty silo", but : waiting at full container?
But I don't know, which side effects it could have.

**Comment by bojanh66** [comment]
Does Autodrive have option to mark a Wait Point?
That would solve this, 2nd tractor would wait at Wait Point until its empty, then he will go back to slurry pit to refill and comeback to Wait Point at field.

**Comment by raxtor** [comment]
It could work in mode Delivery together with reapeat counter, but problem will be mobile trigger by slurry tank, which is not supported yet probably. Would be nice for seeders and fertilizers whose can be reffiled from trailers, pallets, heaps...

**Comment by Bobster82** [comment]
I used an container for a buffer between them...
But its using CP to do the fieldwork and the refill route is using CP over AD network...

I place a container next to the refill route, a truck is refilling the container and the tractor is refilling from the container... 

I had a vid made about it, but cant find it anymore 😋

**Comment by bojanh66** [comment]
I tried that too, to use CP over AD network, but the problem is, if container is full, truck wont stop to refill it, because there is no Wait Point in AD network.

Truck will stop only if container is not full, which means if fill level is 0-99%

Atm i think its not possible to 100% automatize this process unless we use only CP, that way we could record a route with CP and put Wait Point.

What i do atm is use Drive only mode or Delivery mode, wait until refill truck is empty, then send it back to slurry pit, then send back to field refill point...it require some manual work, but better than driving manually.

**Comment by Bobster82** [comment]
@bojanh66 , O I'm sorry... I used CP too over AD network to drive the truck... used the map autodrive in CP, then a return course... So u dont have to make a new route, just use the AD network ;)

**Comment by bojanh66** [comment]
I figured this out.
To make a refill tanker stop at delivery point, course needs to look like this :
![fsScreen_2019_11_12_17_31_34](https://user-images.githubusercontent.com/32069662/68690949-32ce9a00-0573-11ea-8e78-e6170f9fdd81.jpg)

Basically, when i connected point Field 39 with blue line, then it wont stop at Field 39, but continue back to BGA Refill even if its full at 100%.

So, to make "Wait Point" in AD network, just dont connect last delivery point with anything.
Once the tanker is empty, it will automatically continue to BGA Refill without any issues.
