### ISSUE TITLE
Truck stopping right before unloading on Central Grain Elevator

### ISSUE THREAD

**Issue by rogeriodec** [Stephan-S/FS19_AutoDrive#857]
AutoDrive Version: 1.0.6.8.
Map (if applicable): RavenPort.
Vehicle / type (applicable): Lizard RoadRunner

**Describe the bug**
This path is old, but now, when the truck arrives to unload at the Central Grain Elevator, it stops for no apparent reason.
What can I do?

**Screenshots**
![image](https://user-images.githubusercontent.com/11199752/68610682-14936c00-0497-11ea-9234-cd4fce157cbb.png)

**Comment by raxtor** [comment]
Turn off collision..? I have feel that AD has now more wide collision mask than before, no idea  why, if yes.

**Comment by Bobster82** [comment]
I think it stops at the waypoint and there is no trigger to load/unload... Move ur waypoint beyond the trigger, maybe thats helping ;)

**Comment by Stephan-S** [comment]
The collison box length was increased a little, yes.
If you press F5 you will see a box in front of the truc that is hitting the wall.

So if you want to use this road with the truck, either disable collision detection or re-record this path so there is less angle in front of the wall

**Comment by rogeriodec** [comment]
Ok, just out of curiosity, pressing F5 shows nothing. 
How to use it?

**Comment by Dzi4d3k** [comment]
You have to enable developments controls in game.xml
`    <development>
        <controls>true</controls>
    </development>`

**Comment by rogeriodec** [comment]
Tks

**Comment by rogeriodec** [comment]
I moved some points with AD Editor, but the problem persists.
Apparently, nothing to collide:
![image](https://user-images.githubusercontent.com/11199752/68711240-049f8900-0578-11ea-904e-77b7693d02a0.png)
But looking aside, it seems the path is a little underneath of the access ramp:
![image](https://user-images.githubusercontent.com/11199752/68711419-56e0aa00-0578-11ea-84ad-3bd66f9a2c72.png)


Was that the reason for the stop?

**Comment by Dzi4d3k** [comment]
Maybe ramp is too steep or became too steep for updated version. You should take a screenshot from the same side like last one but from ground level. Then you may see if orange box is hitting ramp before front wheels can drive on ramp.

**Comment by rogeriodec** [comment]
I closed this issue, but I ask to be reopened. 
[This video](https://youtu.be/ASQgkb38lsY) shows the exact problem.
There is no collision ahead, however, AD is interpreting that ramp as a collision.
And there were no maps changes for RavenPort.
So, something changed in AD collision detection.

**Comment by TyKonKet** [comment]
We are closing this issue because of a long time inactivity, If the issue still persists with the latest versions, feel free to open it again.

**Comment by rogeriodec** [comment]
This issue persists with the latest version

**Comment by rogeriodec** [comment]
I don't have the privileges to reopen this issue.

**Comment by TyKonKet** [comment]
**Hello, Thank you for opening this issue!**
Since we have just released [the new refactored version of AutoDrive](https://github.com/Stephan-S/FS19_AutoDrive/releases/tag/1.1.0.0), we can no longer provide any feedback or support for open bug reports related to the old code base.
If the problem persists, please reopen a new issue with all the required details.
Thank you for understanding and we hope you continue enjoying our mod 😄
