### ISSUE TITLE
Dropdown Menu doesnt appear

### ISSUE THREAD

**Issue by PapaTim68** [Stephan-S/FS19_AutoDrive#858]
AutoDrive Version: 1.0.6.9
Release or custom zip: Release
Map (if applicable): All
Vehicle / type (applicable):

**Describe the bug**
The Downtown Menu for destinations seems to be bugged.
Clicking on the destination hides the key menu on the left, but the Drop down Menu that is supposed to show up doesn't come up. Scrolling through the destinations does work.

**Screenshots**
![NoDropdown](https://user-images.githubusercontent.com/29522870/68611947-9f865d80-04bb-11ea-8f6c-0cc9145ee08f.jpg)

**Comment by raxtor** [comment]
You have ptretty old version.. dont use version from modhub, its not updated.. use this one link https://github.com/Stephan-S/FS19_AutoDrive/releases/download/1.0.6.8/FS19_AutoDrive.zip and AD release page https://github.com/Stephan-S/FS19_AutoDrive/releases

**Comment by PapaTim68** [comment]
good i miss read the modhub version beeing 1.0.6.9 not 1.0.1.9

**Comment by Iwan1803** [comment]
Maybe @Stephan-S should remove the old version from the Modhub....

@PapaTim68 
problem is gone with the new version?

**Comment by PapaTim68** [comment]
Yes problem gone!

**Comment by Iwan1803** [comment]
Thx. for the feeback, i will close it 😎
