### ISSUE TITLE
How to record a two-way segment of traffic?

### ISSUE THREAD

**Issue by KCHARRO** [Stephan-S/FS19_AutoDrive#859]
AutoDrive Version: 1.0.6.8
Release or custom zip: Release
Map (if applicable): All
Vehicle / type (applicable): All

I'm still using version 1.0.6.5, because since 1.0.6.6 - 1.0.6.8 when I'm going to record a course, I can't do a two-way route (Blue segments), the purple record button doesn't appear anymore, can you make it come back? This is very useful...

**Comment by raxtor** [comment]
https://github.com/Stephan-S/FS19_AutoDrive/wiki/4-AutoDrive-HUD#411-standard-buttons

**Comment by SavageMkII** [comment]
You need to click the record button with the secondary mouse button. I think by default it's middle mouse button.

**Comment by KCHARRO** [comment]
Thanks guys....... I didn't know, I already tried and it works ....
