### ISSUE TITLE
Different lines for different vehicles (suggestion)

### ISSUE THREAD

**Issue by Moitzbert** [Stephan-S/FS19_AutoDrive#862]
Hallo Stephan, 

Hatte letztens das Problem, dass größere Fahrzeuge (LKW, Tieflader usw..) an nicht extra dafür eingefahrenen Kurven immer wieder hängen geblieben sind.
Dabei ist mir die Idee gekommen ob es nicht möglich wäre, 1 oder 2 weitere Linienarten hinzuzufügen. 

Je nachdem wie aufwändig es ist, dies zu programmieren, wäre es nützlich, wenn man diese Linien dann gewissen Fahrzeugen zuweisen kann. 
 
Nur ein kleiner Einfall meinerseits. ;) 

Wirklich hilfsbereite Community und tolles Team! Macht weiter so! 

Mit freundlichen Grüßen 
Christof

**Comment by Iwan1803** [comment]
Das mit den schlecht eingefahrenen Kurven kenne ich nur zu gut, aber dafür extra neue Linien erstellen? 
Ich stelle mir gerade eine Kreuzung oder Abzweigung vor, wo dann für Abbiegespuren mehrere (farblich unterschiedliche) Linien existieren:
- Trecker mit Anhänger = 1 Linie gelb
- Drescher mit Anhänger = 1 Linie grün
- großer LKW mit langem Auflieger = 1 Linie orange
- usw.
Die muss man ja auch erstmal alle zusätzlich aufzeichnen UND dann auch noch den Fahrzeugen zuweisen.
Sorry, aber das halte ich persönlich für unnötig und kompliziert, denn da nehme ich lieber einmal ein Gespann mit großem Wenderadius, mache die Kurve einmal neu und bin fertig.

**Comment by Moitzbert** [comment]
Ja sowas in die Richtung hab ich mir auch vorgestellt. Jeden Kurs für jedes Fahrzeug extra einzufahren wäre ja eine Zumutung. 

Aber prinzipiell eine Linie für alle Fahrzeuge zu haben und dann noch spezifische für die Kreuzungen wäre schonmal ein Ansatz. 
Mal schauen was Stephan dazu sagt.

**Comment by Iwan1803** [comment]
Aber welche Vorteile sollen denn mehrere Linien an Kreuzungen gegenüber einer einzigen bringen?
Ich sehe da nur einen: ggfs. Minimierung von Kollisionen, aber vielleicht übersehe ich da auch etwas...

**Comment by Moitzbert** [comment]
Geht prinzipiell nur um die Vermeidung von Kollisionen bzw. um das ‚Ausholen‘ eines längeren Gespanns damit es ohne hängen zu bleiben und die Kurven kommt. Habe da ansonsten keinen Aspekt für gefunden..

**Comment by geo-luchs** [comment]
Und warum benutzen dann nicht alle Gespanne die Linie?

Der einzige Grund wäre dass dadurch die Kollisionsgefahr höher ist wenn mehr Fahrzeuge den weiten Weg in der Kirve fahren. 
Habt ihr so oft Gegenverkehr in den Kreuzungskurven?

**Comment by Iwan1803** [comment]
Wenn denn viel Verkehr unterwegs wäre, dann vielleicht, aber bisher bin ich von Kreuzungskollisionen eigentlich verschont geblieben.
Von daher brauche ich (persönlich) keine zusätzlichen Linien und zum Glück gibt es auf der NFM auch nicht so viele Ecken, wo ein Gespann mit größerem Wenderadius hängenbleiben könnte. Die 2-3 Ecken, wo es mal aufgetreten ist, habe ich gelöscht und einfach neu aufgezeichnet.

**Comment by RalfGorden** [comment]
ich spiele die Multimap hab dort auch keine Kreuzungskollisionen  hab auch alles großzügig eingefahren wie es ging

**Comment by Brombee42** [comment]
At the NFM I drove in at the bottlenecks with guardrail with blue track and at the two bridges these also made blue and thus no Drescher or potato harvester is left hanging.

**Comment by Tensuko** [comment]
Glaub sowas rechtfertigt den Aufwand dahinter nicht.
Da kann man eher schauen, ob man für Kurven einen einstellbaren Offset einbaut.
z.B. die nächsten X Wepunkte im Winkel/Radius von Y, dann nimm diese Wegpunkte mit einem Offset von Z.

Das wäre bei einer Rechtskurve vlt die nächsten 5 Wegpunkte ergeben einen Winkel/Radius der dem Fahrer sagt, er soll diese Wegpunkte mit einem Offset nach links fahren, somit fährt er weiter außen, folgt aber der Linie bis die nächsten Wegpunkte wieder gerade verlaufen.

Wie praktikabel das je nach Situation ist, weis ich nicht, da ich zugeben muss, AD eher weniger zu Nutzen (eher CP), das kommt aber immer auf die Mapgröße bzw das Streckennetzt drauf an (Kann AD mitlerweile rückwärts fahren ?)
