### ISSUE TITLE
Autodrive Drive mode turn on implement Horsch Slurry tank

### ISSUE THREAD

**Issue by bojanh66** [Stephan-S/FS19_AutoDrive#863]
AutoDrive Version: 1.0.6.8
Release or custom zip: custom zip
Map (if applicable): All
Vehicle / type (applicable): Horsch Slurry Tank 21.000 tracks + this mod https://www.farming-simulator.com/mod.php?lang=en&country=us&mod_id=135293&title=fs2019

**Describe the bug**
When i turn on Autodrive, mode Drive only, it will turn on PTO on Horsch slurry tank

**If applicable - Steps to reproduce the behavior**
Attach Horsch Slurry tank 21.000 + Zunhammer Farmlandfix 15 and start AutoDrive, it will turn on implement

**Screenshots**

**Comment by TyKonKet** [comment]
Ok, I've done some testing and I found that the problem occurs with all the slurry tanks (not just the Horsch) when they have attached a spreading tool.

**Comment by TyKonKet** [comment]
Ok, bug spotted, now we need @Stephan-S to decide how to solve it:
That's the call stack of 'setIsTurnedOn'
```
LUA call stack:
  dataS/scripts/vehicles/specializations/Sprayer.lua (826) : setIsTurnedOn
  dataS/scripts/vehicles/SpecializationUtil.lua (30)
  dataS/scripts/vehicles/specializations/WorkArea.lua (143) : raiseEvent
  dataS/scripts/vehicles/SpecializationUtil.lua (30)
  dataS/scripts/vehicles/Vehicle.lua (1397) : raiseEvent
  dataS/scripts/network/NetworkNode.lua (105) : updateTick
  dataS/scripts/network/Server.lua (71) : updateActiveObjectsTick
  dataS/scripts/BaseMission.lua (1500) : update
  dataS/scripts/FSBaseMission.lua (1977) : update
  dataS/scripts/missions/mission00.lua (469) : update
  dataS/scripts/main.lua (1896) : update
```
Which brings us to the source of the problem, the specialization 'Sprayer', more precisely to these lines of code:

```lua
-- if the ai is active we try to activate the source to activate the fill unit
if self:getIsAIActive() then
    if vehicle.setIsTurnedOn ~= nil then
        if not vehicle:getIsTurnedOn() then
            vehicle:setIsTurnedOn(true)
        end
    end
end
```

**Comment by DeckerMMIV** [comment]
I was notified of the [same problem, in my Follow Me mod](https://github.com/DeckerMMIV/FarmSim_Mod_FollowMe/issues/40).

My "[solution](https://github.com/DeckerMMIV/FarmSim_Mod_FollowMe/commit/509b958b0400d8c1608bd30b03af2e1f23449d99#diff-5d2fc73ce6b7e4cf56171cb5ca15d8af)", which isn't quite a proper solution, is to override the `getIsAIActive` method, but only for the Sprayer specialization, so it returns `false` if my mod is active.

I have not yet found a "better method", which I suppose is needed, to reduce the performance-impact of having this more expensive `getIsAIActive` check.

**Comment by TyKonKet** [comment]
Another possible solution would be to completely overwrite the **onStartWorkAreaProcessing** function (since we have the actual source code) and add some extra checks in the incriminated if statement.
But the problem with this solution is that it would easily conflict with other mods and with any minimal change, on the function code, by GIANTS, so I think that the solution suggested by @DeckerMMIV , is the only one plausible at lest for the moment.

**Comment by Stephan-S** [comment]
I agree. I don't see any way of doing this without possibly conflicting with other mods or with less perfomance impact.
Sadly every mod that uses AI helpers has to do this, which results in a cascade of calls if I'm not mistaken about your implementation @DeckerMMIV
