### ISSUE TITLE
drive to multiple destinations in folder does not work

### ISSUE THREAD

**Issue by RalfGorden** [Stephan-S/FS19_AutoDrive#864]
hallo mehrere Ziele anfahren im Ordner geht bei mir nicht , fahre am Wassertrigger los zur Entladestelle  1 dort ladet er ab bleibt aber stehen mache kurz aus wieder an fährt er wieder zum Wassertrigger läd auf und fährt zur Entladestelle 2 ladet ab und bleibt dann stehen und das ist dann bei jeder Entladestelle so
mehrere ziele abfahren ist auf ja hab auch mehrere Fahrzeuge getestet

**Comment by Iwan1803** [comment]
Niemand erwartet, das jemand eine Sprache perfekt beherscht, aber es wäre dennoch schön, wenn ab und zu Satzzeichen verwendet werden. Das macht das Lesen und Verstehen deutlich einfacher 😉
Der Wassertrigger ist also dein Startort und im Zielordner liegen 2 Entladestellen. Beim AD-Start fährt er zum Wassertrigger, lädt auf und steuert dann Entladestelle 1 an. Dort wird zwar abgeladen, aber dann bleibt das Gespann stehen.
Wenn du AD dann stoppst und wieder startest, fährt er zurück zum Wassertrigger, lädt auf und fährt dann Zielpunkt 2 an. Dort wird dann zwar noch abgeladen, aber das Gespann bleibt wieder stehen.
Bleibt er dann direkt am Abladetrigger oder am Zielpunkt oder dahinter irgendwo stehen?

**Comment by Iwan1803** [comment]
@RalfGorden 
ist das Problem verschwunden oder war das Schliessen ein Versehen?

**Comment by RalfGorden** [comment]
hab ausversehen geschlossen , er bleibt dann immer direkt am Abladetrigger stehen

**Comment by RalfGorden** [comment]
hab festgestellt das wenn ich ein Fahrzeug auf mehrere Ziele anfahren gestellt habe, die anderen Abfahrer es auch tun obwohl bei ihn nein steht

**Comment by rgoe** [comment]
Diesen Fehler konnte ich gestern auch kurz beobachten, war leider noch nicht in der Lage zu testen bzw. nachzustellen  - werde ich heute abend versuchen. Sah von der Symptomatik aus wie schon bei #632 beschrieben. AD Version 1.0.6.8-2 (vom 12.11.): 1. Feld mit Feldhächsler und 4 Abfahrern bei denen "Mehrere Ziele" gesetzt ist, 2. Feld mit 3 Abfahrern, bei denen "Mehrere Ziele" nicht gesetzt ist. Dennoch ändert sich das Ziel bei den Abfahrern des 2. Feldes von Zeit zu Zeit ohne Vorwarnung oder erkennbaren Grund. In einem Fall konnte ich auch live beobachten, dass sich das Ziel eines Abfahrers des 1. Feldes, nach erreichen des vorgesehenen Zielpunktes nicht auf den nächsten änderte, obwohl hier "Mehrere Ziele" gesetzt war. 
Wie gesagt, habe ich noch keine Regelmäßgkeit erkennen können - als ich es nach Neustartg mit Screenshots dokumentieren wollte, lief es wieder sauber - Vorführeffekt.
Schaue heute abend mal weiter.

**Comment by rgoe** [comment]
Leider konnte ich das Ganze nicht wirklich nachstellen. Ich habe zwar einige wenige Male festgestellt, dass ein Abfahrer (ohne "Mehrere Ziele" gesetzt) auf einmal ein anderes Ziel hatte (aus dem gleichen Ordner, wie sein eigentliches Ziel), konnte aber keine Ursache oder Zusammenhang erkennen. Setup wie oben mit mehreren Abfahrern/Feldern. Log ist sauber.

**Comment by RalfGorden** [comment]
![fsScreen_2019_11_13_20_57_38](https://user-images.githubusercontent.com/56214377/68977309-4474a380-07f8-11ea-97ba-5f1ba9e45c0f.png)
![fsScreen_2019_11_15_21_41_14](https://user-images.githubusercontent.com/56214377/68977310-4474a380-07f8-11ea-8a94-f402c792123f.png)
![fsScreen_2019_11_15_21_44_53](https://user-images.githubusercontent.com/56214377/68977311-4474a380-07f8-11ea-8797-be2135422e81.png)
fahren an der Entladestelle nicht weiter

**Comment by RalfGorden** [comment]
hallo hab immer noch das Problem, das er an den Abladestelle das Wasser abläd, aber nicht weiterfährt, erst wenn ich AD kurz aus und wieder anmache

**Comment by haamic** [comment]
Das scheint aber ein generelles Problem zu sein, nicht wegen "mehrere Ziele".
Bei mir hält er auch beim Gülle fahren am Abladeziel, obwohl er noch paar Runden drehen soll. Das Abholziel ist aber bereits grün, fährt aber erst weiter wenn ich auf den Butten "weiterfahren" drücke. Mehrere Ziele sind nicht aktiviert.

**Comment by Iwan1803** [comment]
Wenn ich das richtig gesehen habe, dann wurde in einer der letzten beiden Versionen beim Abladen eine Verzögerung eingebaut. Er bleibt also nach dem Abladen noch eine gewisse Zeit stehen, bevor er weiterfährt.

**Comment by haamic** [comment]
@Iwan1803 
Welcher Sinn steckt dahinter?

**Comment by Iwan1803** [comment]
Das kann nur Stephan sagen.

**Comment by RalfGorden** [comment]
> 
> 
> Wenn ich das richtig gesehen habe, dann wurde in einer der letzten beiden Versionen beim Abladen eine Verzögerung eingebaut. Er bleibt also nach dem Abladen noch eine gewisse Zeit stehen, bevor er weiterfährt.

werde es nochmal testen ,aber denke es liegt nicht daran , wenn ich normal  abholen und abliefern hab fährt er auch gleich weiter

**Comment by RalfGorden** [comment]
> 
> 
> > Wenn ich das richtig gesehen habe, dann wurde in einer der letzten beiden Versionen beim Abladen eine Verzögerung eingebaut. Er bleibt also nach dem Abladen noch eine gewisse Zeit stehen, bevor er weiterfährt.
> 
> werde es nochmal testen ,aber denke es liegt nicht daran , wenn ich normal abholen und abliefern hab fährt er auch gleich weiter

gerade nochmal versucht, an der Verzögerung liegt es nicht , er fährt nicht weiter

**Comment by RalfGorden** [comment]
hallo hab immer noch das Problem mit den mehreren Zielen in einen Ordner,er fährt einfach nicht weiter ,er läd ab schaltet  nicht um auf das nächste Ziel aber ist grün siehe Fotos. Das andere Problem ist immer noch ,das auch andere Abfahrer bei denen  mehrere Ziele anfahren auf nein steht , ihre Ziele wechseln .

**Comment by Stephan-S** [comment]
The switching of destinations is fixed (will be uploaded soon) but the issue of driving on when the current destination is filled up is still an open issue. But to keep this things seperated, I would say we should open a new issue for that one.
