### ISSUE TITLE
Unloading combine stops to early when filllevel of chaser bin is reached 

### ISSUE THREAD

**Issue by TobiHH78** [Stephan-S/FS19_AutoDrive#867]
AutoDrive Version: 1.0.6.8
Release or custom zip: Custom Zip
Map (if applicable): All
Vehicle / type (applicable):

When I use AD for unloading the combine and set a fill level of the chaser bin to (for example) 80%, the chaser bin start driving to the silo during the unloading process of the combine directly once the 80% are reached. So the combine is often not unloaded completly bcause the chaser starts to early and don`t finish the unloading of the combine first.
Would be better if the chaser bin first unload the combine completely and check afterwards if the filllevel of the trailer is reached to go to the silo.

**Comment by TyKonKet** [comment]
We are closing this issue because of a long time inactivity, If the issue still persists with the latest versions, feel free to open it again.
