### ISSUE TITLE
Autodrive encountered a problem during initialization - shutting down

### ISSUE THREAD

**Issue by MacedonskyAlex** [Stephan-S/FS19_AutoDrive#868]
When working with the combine, the tractor cannot find the way to the combine. The settings were different, the path is always the same - **Autodrive encountered a problem during initialization - shutting down** 

**Video**
https://youtu.be/bEdnOuL1Iyg

**Comment by MacedonskyAlex** [comment]
It turns out that the harvester is close to the tractor, so the tractor cannot find a way, I can’t move the waiting area

**Comment by KCHARRO** [comment]
This usually happens when the combine is outside the limits of the field and in the configuration of the driver is to look for the road within the limits of the field.

**Comment by MacedonskyAlex** [comment]
in version 1.0.6.1 did not notice such a problem

**Comment by KCHARRO** [comment]
It happened to me last night, when I saw the error, I realized that the combine went back to the filling and was out of the field, I entered it manually and the driver could then calculate the route to it.

**Comment by raxtor** [comment]
There is an option in settings panel if path will be calculated only for field, try change that value.

**Comment by MacedonskyAlex** [comment]
I wrote in the beginning that all settings were changed and combined and the result is the same

**Comment by TyKonKet** [comment]
@MacedonskyAlex Mod version please.

**Comment by MacedonskyAlex** [comment]
> @MacedonskyAlex Мод версии, пожалуйста.

1.0.6.8, but in the modDesc.xml file is version 1.0.6.7
![290RZDUmlWg](https://user-images.githubusercontent.com/52257646/68860598-e746f800-06fa-11ea-88b0-b4135ea4f8bd.jpg)

**Comment by TyKonKet** [comment]
@MacedonskyAlex we have fixed the issue with the work of this week, you can both zip the mod yourself or wait until the next release.
