### ISSUE TITLE
AD stopped saving the current status of the vehicles

### ISSUE THREAD

**Issue by KCHARRO** [Stephan-S/FS19_AutoDrive#869]
AutoDrive Version: 1.0.6.8
Release or custom zip: Release

AD does not save the current state of each vehicle, when you load the game it restarts the state of the vehicles and it is annoying when you have more than 7-8 to reconfigure all to continue with what they were doing, before it was just to load the game , press ctrl + alt + up and work, it also does not save the place assigned to them for parking, and you have to reassign everyone.

**Comment by Stephan-S** [comment]
Cannot recreate this problem.
All vehicles properly store their destinations and modes.

Can you explain in more details what you are setting, waht your settings are and what is not working when you restart the game (and save it first)

**Comment by KCHARRO** [comment]
This weekend I was watching and AD saves the selected settings and destinations in each vehicle, if parking, work mode, or everything is selected.

But when loading the game, the vehicles appear with the settings such as when you shop at the store, with no parking set, and the selected destination 1 and mode 1 (driving) in some way AD does not read those values when loading the game.

The settings set in the settings menus load correctly.

Now with 1.0.6.8: Custom ZIP

**Comment by Stephan-S** [comment]
Can you try disabling all other mods?
I still haven't seen this issue once.
Maybe something is conflicting before AD can load/write the vehicle settings.
Any errors in the log?

**Comment by KCHARRO** [comment]
I tried now with the 1.0.7.0-10 CustomZip, in Felsbrunn with the original equipment and it did load the configurations well, I see that autodrive problem has already been solved, now I will start activating the other MODS one by one to rule out what is that of the conflict ...

You can now close this issue

The log does not give errors ....

**Comment by KCHARRO** [comment]
Somehow the problem was solved, it already works with MOD activated too, I also saw that it creates a file: AutoDriveUsersData.xml What is it for? does not put anything inside, only on the first line: <AutoDriveUsersData />

**Comment by TyKonKet** [comment]
@KCHARRO AutoDriveUsersData.xml is used to save users personal data on MP (e.g. the HUD position)
