### ISSUE TITLE
1-Click possibility to set a fieldwork speed

### ISSUE THREAD

**Issue by TobiHH78** [Stephan-S/FS19_AutoDrive#870]
I have set all vehicles to a standard speed of 50 km/h. It would be a nice feature to have the possibility to define a 2nd different speed if you do the fieldwork for example.

It`s a little unrealistic that the vehicles drive 50 km/h on the field, and it hppens quite often that due to the high speed the unloading tractors drive in circles when they can`t reach the corret point after unloading the combine.
As I play on a 4x map, I use several vehicles simultaneously. and it`s a little bit long-winded to change the speed from every vehicle manually to 20-24. Especially as the reduction of speed is done with right click which also opens the CP menu.
So I always have to change the CP setting first tp STRG + Entf. and than click for every vehicle 25 times the right click. Once the fieldwork is done, I have to click 25 times again (for 10-15 vehicles) to set speed back to 50.

If there would be an option to set a 2nd different speed whcih can be set with one click or one key tht would save a lot of clicks.

**Comment by Stephan-S** [comment]
Currently the field speed is limited to 37km/h.
Is this really too fast?
I might add this into the vehicle specific settings in the settings menu.

**Comment by TobiHH78** [comment]
I think it`s still a bit too fast. When the fieldwork is done, my tractor is somewhere on the field, I have a AD circle around every field. When I then start AD the vehicle drives to the first AD point outside of the field. Usually it reaches it in nearly a 90° position. That`s often to fast to get on the track and it starts drive in circles.
Maybe a speed not more than 30 would work better.
Would be really great if there would be a quick option to set a 2nd speed. Drop down the speed for fieldwork and raise it afterwards is actually only possible with a lot of clicks.

**Comment by raxtor** [comment]
@TobiHH78 is hard set max speed in HUD?

**Comment by TobiHH78** [comment]
Yes I think it takes too long. My regular speed is 50, when I want to change it to 25 for example to have a realistic fieldwork speed, I have to click 25 times for every single vehicle. Once the fieldwork is done I have to click again 25 times. If I use 10 vehicles simultaneously that means 500 clicks.

**Comment by raxtor** [comment]
use mouse wheel for speed set... u sawill save some clicks :-)

**Comment by raxtor** [comment]
Btw can you post image where are yuo using together 25 vehicles on fiield. Can be interesting view.

**Comment by TobiHH78** [comment]
Not 25 vehicles, but as I wrote maybe 10.
I play on a big 4x map. When I harvest two fields same time I have two combines, 4 unloading tractors an 2-4 tractors collecting straw.

Thanks for the hint with the mouse wheel, did not try that before. That helps a lot!!

**Comment by jala15** [comment]
> I think it's still a bit too fast. When the fieldwork is done, my tractor is somewhere on the field, I have a AD circle around every field. When I then start AD the vehicle drives to the first AD point outside of the field. Usually it reaches it in nearly a 90° position. That`s often to fast to get on the track and it starts drive in circles.
> Maybe a speed not more than 30 would work better.
> Would be really great if there would be a quick option to set a 2nd speed. Drop down the speed for fieldwork and raise it afterwards is actually only possible with a lot of clicks.

@Stephan-S Would it be possible to start AutoDrive with pathfinding to nearest waypoint when pressing start button in the middle of a field to avoid this problem?

**Comment by Stephan-S** [comment]
Yes it is. I have to do some changes in the code, but I wanted to do that as well.

**Comment by TobiHH78** [comment]
I noticed that when I use AD for unload/refill, they drive with the max speed from the field which is set in the hud. Maybe it`s possible to reduce the speed on the field to 25-30 and use the speed on the hud only once the driver is on the first waypoint outside of the field?

**Comment by TobiHH78** [comment]
Still have this problem. In this case I had a fertilizing job on a field. Once finished the driver was in the middle of the field (I did headlands first). I send him to my fuel station and he tried to reach the first AD point in reach. I have a full AD circle around the field, and he reaches the first point again in nearly 90°. With 38 km/h he drove over the point and was not able to get to the 2nd point from there. He start driving in circles without success.
After a few circles he try to reach the next point, but he was again too quick and only starts the circle other way round...

Maybe it`s a solution that he didn`t try to reach directly the 2nd point once he drove over the first one but get a point 3-4 points beyond?

![1](https://user-images.githubusercontent.com/56259322/69438999-6618e200-0d46-11ea-8654-394757e15e18.JPG)
