### ISSUE TITLE
Doesn`t unload 2nd attached trailer

### ISSUE THREAD

**Issue by TobiHH78** [Stephan-S/FS19_AutoDrive#872]
AutoDrive Version: 1.0.6.8 (1.0.6.8-3)
Release or custom zip: custom Zip
Map (if applicable): All
Vehicle / type (applicable): 

When I have two trailers attached and send AD to an unloading point, only the first trailer will be 
unloaded. The tractor didn`t drive further and don`t unload the 2nd trailer.
Tried different vehicle combinations and different unloading points. The result is always the same, only the first trailer is unloaded and then the tractor stops and don`t do anything further.
If I click manually to "go" button the tractor starts and also unload the 2nd trailer once the trigger is reached.

![Screenshot](https://user-images.githubusercontent.com/56259322/68876264-786e9c80-0704-11ea-8db4-7f331b2fc0e2.JPG)

**Comment by RalfGorden** [comment]
hab genau das selbe Problem

**Comment by kurtlohnunternehmen** [comment]
Also have the same problem.

**Comment by Woife1** [comment]
the destination is to close to the trigger   

the destination is the latest point to load or unload when the driver has passed the point he uses the next target

**Comment by TobiHH78** [comment]
No, I changed the position of the unloading point various times. Had also a few positions clearly beyond that point, but it still did not work. Only the first trailer is unloaded and the tractor did not move.

**Comment by Stephan-S** [comment]
It's fixed in the latest sources!
