### ISSUE TITLE
Abdeckplane: Keine Beladung / Tarpaulin - No loading

### ISSUE THREAD

**Issue by kurtlohnunternehmen** [Stephan-S/FS19_AutoDrive#875]
AutoDrive Version: 1.0.6.8
Release or selbsterstelltes zip: Release
Fahrzeug(art) (falls relevant): Fahrzeuge mit Abdeckplane

Es werden Fahrzeuge/Anhänger mit Abdeckplane in keiner Weise beladen - die Abdeckplane wird von Autodrive nicht automatisch entfernt.

Vehicles/trailers with tarpaulins are not loaded in any way - the tarpaulin is not automatically removed by Autodrive.

**Comment by Iwan1803** [comment]
Ich hatte das auch schon mal, aber da ich eh auf größere Anhänger (ohne Plane) umgestiegen bin, war das Problem mehr für mich.
Allerdings bin ich mir nicht sicher, ob das Problem nicht eigentlich schon mal gefixt war...

**Comment by TobiHH78** [comment]
Bei mir öffnet AD die Plane automatisch, sobald der Trigger erkannt wird. Dieses Problem kann ich so nicht bestätigen.

**Comment by Iwan1803** [comment]
Bei mir hat er sie geöffnet, als er zum Drescher hin gefahren ist und am Drescher angekommen hat er sie dann wieder geschlossen.

**Comment by worker2419** [comment]
gerade mit Version getestet
AutoDrive Version: 1.0.6.9
Release or selbsterstelltes zip: selbst erstellt
Fahrzeug(art) (falls relevant): Fahrzeuge mit Abdeckplane

identisches Verhalten wie @Iwan1803 berichtet. Plane wird zur richtigen geöffnet und geschlossen. Anhänger sind aus dem Mod Metaltech TG Pack

**Comment by kurtlohnunternehmen** [comment]
Kann es vielleicht daran liegen, dass ich versucht habe die AD Abfahrer manuell mit dem Drescher bzw. Häcksler (mit Tank) zu beladen. Denn die normale AD Beladung läuft auch bei mir ohne Probleme!

**Comment by worker2419** [comment]
Ja, das kann gut sein. Zumindest habe ich das auch schon gehabt als ich manuell eingegriffen habe. Als wenn die Reihenfolge nicht mehr stimmt.
