### ISSUE TITLE
Harvester Problems

### ISSUE THREAD

**Issue by Lionking1010** [Stephan-S/FS19_AutoDrive#876]
AutoDrive Version: 1.0.
Release or selbsterstelltes zip: Release
Karte (falls relevant): Multimap 4x 
Fahrzeug(art) (falls relevant): Harvester 

**Beschreibe den Bug**
Wenn man in einen Harvester einsteigt kann man die Schnittlänge der Bäume nicht mehr bestimmen. und wenn man dann auf die Map geht verschwindet der maus zeiger und man kann in kein fahrzeug über die map mehr einsteigen. Danach funktioniert der maus zeiger im normalen spielen nicht mehr und die Tempo anzeige verschwindet auch.

**Falls anwendbar - Schritte mit denen ich den Bug nachstellen kann**
eine Mod Map mit mods spielen dann in den harvester und schauen bei mir gehts dann nicht das ich die schnitt weite verstelle
**Screenshots**
Falls relevant, bitte Screenshots beifügen

**Comment by Iwan1803** [comment]
Ist das die AD-Version vom Modhub oder von hier?
Falls von Modhub: die ist gnadenlos veraltet und sollte nicht mehr verwendet werden.
Also am besten immer die Version von hier laden.

Ich habe übrigens gestern selber in einem Harvester (Standard, kein Mod) gesessen und konnte ihn problemlos einstellen und bedienen.
Falls du zufällig noch CoursePlay nebenbei nutzt, dann stell es für den Harvester so ein, das rechte STRG + Del drücken muss. Ansonsten funkt CP nämlich dazwischen.

**Comment by Lionking1010** [comment]
Ich habe die Version von github also die neusete 1.0.6.7 und CP nutze ich nicht. Ich nutze das ganze auch auf einem server und im singleplayer als auch auf dem server habe ich die gleichen probleme.

**Comment by Iwan1803** [comment]
Ist der Harvester denn ein Mod oder ein Standard?
Besteht das Problem sowohl im MP als auch SP nur auf dieser Map oder auch auf einer Standardkarte?

**Comment by Lionking1010** [comment]
Ich habe es jetzt nur auf dieser karte getestet und es besteht im SP und im MP mit standard und mod harvester

**Comment by worker2419** [comment]
Rufe einmal die Settings von AD auf Standard ist Strg Links Alt und 0 auf dem NumPad Hier den Parameter Hilfe anzeigen prüfen und ggf. auf Nein stellen. Dann sollte die Länge der Schnitte wieder aktiv sein.
![AD_01](https://user-images.githubusercontent.com/47278102/68897743-64d82b80-072e-11ea-80d4-bf2d44458056.png)

**Comment by Lionking1010** [comment]
ok danke das könnte funktionieren das muss ich mal austesten dankeschön

**Comment by worker2419** [comment]
ansonsten schau einmal hier #673, Woife1 hat dazu noch etwas geschrieben

**Comment by Lionking1010** [comment]
Das mit der Hilfe aus schalten funktioniert aber ob das mit dem tacho verschwinden und dem verschwinden des maus zeigers muss ich noch testen

**Comment by Woife1** [comment]
Wenn die Anzeigen im Spiel verschwinden ist entweder ein Mod dafür aktiv oder ein Mod schmeist mit Fehlern um sich die sich meistens im Log wiederfinden lassen (ein Upload hier her hilft uns dir bei der Fehlersuche zu helfen ;) )

Die Schnittlängen Einstellung ist immer aktiv nur die F1 Anzeige ist manchmal nur zu klein (Abhilfe gibt die Anzeige im Cockpit des Fahrzeuges)

**Comment by TyKonKet** [comment]
We are closing this issue because of a long time inactivity, If the issue still persists with the latest versions, feel free to open it again.
