### ISSUE TITLE
Error: Running LUA method 'loadMapFinished (AutoDriveXML.lua:475)

### ISSUE THREAD

**Issue by Mannie313** [Stephan-S/FS19_AutoDrive#878]
AutoDrive Version: 1.0.6.8
Release or selbsterstelltes zip: # 819
Karte (falls relevant): Alle
Fahrzeug(art) (falls relevant):

**Beschreibe den Bug**
Eine klare Beschreibung des Bugs.
Kann kein neues spiel erstellen. Im Singleplayer geht es nicht, ob es im Multiplayer nicht geht weiß ich nicht. 

Can not create a new game. In the single player it is not, if it does not work in multiplayer, I do not know.
**Falls anwendbar - Schritte mit denen ich den Bug nachstellen kann**
AutoDrive is starting a new configuration file
Error: Running LUA method 'loadMapFinished'.
C:/Users/Manni/Documents/My Games/FarmingSimulator2019/mods_test/FS19_AutoDrive/scripts/AutoDriveXML.lua:475: attempt to concatenate field 'modDirectory' (a nil value)
**Screenshots**
Falls relevant, bitte Screenshots beifügen

[log.txt](https://github.com/Stephan-S/FS19_AutoDrive/files/3849173/log.txt)

MFG Mannie313

**Comment by TyKonKet** [comment]
Hey, @Mannie313 try to start the new savegame with the AutoDrive disabled and then restart the game with the AD activated, I'll fix this error tomorrow.
