### ISSUE TITLE
Drescher Abtanken im MP (Dedi)

### ISSUE THREAD

**Issue by FunFarmer1** [Stephan-S/FS19_AutoDrive#879]
AutoDrive Version: 1.0.6.8.7
Selbsterstellte Zip 
Karte : NF Marsch 4-Fach

**Beschreibe den Bug**
AD tankt den Drescher ganz normal ab nur findet er manchmal keinen weg aus dem Feld heraus und das Fahrzeug bleibt stehen wo er den Drescher abgeladen hat und der AD helfer verschwindet aus dem Fahrzeug. Desweiteren falls er mal den weg in Richtung Hofsilo findet, fährt er einfach durch und wieder zurück zu seinem Feld ohne das er abgeladen hat.

**Falls anwendbar - Schritte mit denen ich den Bug nachstellen kann**
ich habe den ganz normalen Drescher abtank modus eingestellt und lasse ihn vom Feld ins Hofsilo abladen.

**Comment by Iwan1803** [comment]
Nur im MP?

**Comment by FunFarmer1** [comment]
Im SP kann ich leider nicht´s sagen da ich nur MP spiele

**Comment by Moitzbert** [comment]
Passiert im SP genauso

**Comment by TyKonKet** [comment]
We are closing this issue because of a long time inactivity, If the issue still persists with the latest versions, feel free to open it again.
