### ISSUE TITLE
Game can not be restarted after creating roundabouts

### ISSUE THREAD

**Issue by Vaelin-al-Sorna** [Stephan-S/FS19_AutoDrive#880]
AutoDrive Version: 1.0.6.8
Release or selbsterstelltes zip: Release
Karte (falls relevant): Multimap2019 V2.3 einzig getestet.
Fahrzeug(art) (falls relevant):

**Beschreibe den Bug**
**Spielstand kann nach dem Erstellen von Kreisverkehren nicht mehr gestartet werden.**

LS19 startet nach Erstellung von Kreisverkehren auf auf der Multimap2019 beim Fruchthof nicht mehr.  Ich habe beim Fruchthof 2 Kreisverkehre erstellt und diese anschließend an das Streckennetz angebunden. Hierfür habe ich alte Wegpunkte gelöscht (ohne danach die Routen neu zu berechnen)
Ich konnte nach erstellen der Wegpunkte und Kreisverkehre noch weiterspielen. Ebenfalls konnte die Route und Wegpunkte berechnet werden. 

Nach dem Beenden des Spiels ist kein Laden des letzten Speicherstands mehr möglich. 

Laden ist nur möglich wenn CP  (Version 335) deaktiviert wird. Das Spiel kann gestartet werden. Wenn ich das Spiel schließe und mit aktiven CP erneut öffne sind alle Autodrive Kurse weg.
Starte ich das Spiel ohne CoursePlay  und ohne irgendwelche anderen Mods neu und berechne die Routen, stoppt das Laden bei 98% oder 99% und das Spiel hängt sich auf. (Siehe Screenshot + Log
![Fehler wenn versucht wird Routen neu zu berechnen ohne CP](https://user-images.githubusercontent.com/57787118/68921898-70e9da80-077a-11ea-9b73-75a260cc1b20.jpg)
[log.txt](https://github.com/Stephan-S/FS19_AutoDrive/files/3850113/log.txt)
)   
 

[log.txt](https://github.com/Stephan-S/FS19_AutoDrive/files/3850133/log.txt)
[AutodriveXML.zip](https://github.com/Stephan-S/FS19_AutoDrive/files/3850124/AutodriveXML.zip)

Ich habe alle XML mit den Kursen angehängt.
Einmal eine ohne Kreisverkehre (lädt ohne Probleme)
Eine mit den Kreisverkehren, sowie eine XML welche gestern plötzlich 17MB hatte.

Das Spiel kann erst wieder gestartet werden wenn ein älterer Spielstand genommen wird.

Übersicht der Fehlermeldungen
scripts/AutoDriveExternalInterface.lua:80: attempt to index local 'point' (a nil value)
scripts/AutoDriveDijkstra.lua:281: bad argument # 1 to 'pairs' (table expected, got nil)

**Falls anwendbar - Schritte mit denen ich den Bug nachstellen kann**
Nachdem es erst nach dem erstellen der 2 Kreisverkehre probleme gab denke ich es liegt daran.

**Screenshots**
siehe oben

**Comment by Stephan-S** [comment]
AutoDrive sagt dir in der Log sogar was verkehrt ist:

2019-11-15 07:38 AD: Loading xml file from C:/Users/Micha/Documents/My Games/FarmingSimulator2019/savegame5/AutoDrive_Multimap_2019_config.xml
2019-11-15 07:38 AD: Loaded Waypoints: 21636
2019-11-15 07:38 AutoDrive.mapMarker[145] : F03 Abfahrer points to a non existing waypoint! Please repair your config file!

Lösche mal den Eintrag 145 aus der config bzw. noch besser, trage dort einen Wegpunkt ein der auch exisitiert.

Wie das passieren konnte, kann ich leider nicht nachvollziehen. Den Fehler habe ich bisher erst einmal sonst gesehen und dann diese Warnung ins Log mit eingebaut

**Comment by Vaelin-al-Sorna** [comment]
Fehler hab ich behoben und nicht mehr aufgetaucht. -> Close

**Comment by Vaelin-al-Sorna** [comment]
Fehler hab ich behoben und nicht mehr aufgetaucht. -> Close
