### ISSUE TITLE
Langsamfahr-Stellen - reduced-speed-sections

### ISSUE THREAD

**Issue by ws1967** [Stephan-S/FS19_AutoDrive#881]
Da ich KEIN Modder oder Programmierer bin habe ich keine Ahnung wie aufwändig eine allfällige Umsetzung meiner Idee wäre:

Es wäre sehr hilfreich, wenn es die Möglichkeit der Einrichtung von Langsamfahrstellen mit individuell festlegbarem Tempolimit gäbe. Nach dem Motto " egal wie schnell das Fahzeug normal fahren darf - zwischen Punkt X und Punkt Y fahren ALLE Fahrzeuge maximal soundsoviel km/h". Das wäre sowohl bei Straßenhindernissen (schmalen Brücken, engen Straßen) als auch auf Grund der immer zahlreicher werdenden "Sittenwächter" - die auf ihren Maps Tempolimits mit Blitzern überwachen und ordentlich abkassieren - hilfreich.
Nur so als Anregung gedacht.
PS: Für Kaffeenachschub wurde bereits gesorgt. :)

**Comment by Stephan-S** [comment]
Ich sehe leider nicht wie ich das sinnvoll im Spiel umsetzen kann.
Einerseits ist das Anwendungsgebiet (Blitzer) nun eher eine Ausnahme und andererseits die Umsetzung recht tiefgreifend.
Daher sehe ich hier leider den Kosten/Nutzen Faktor aktuell nicht ausreichend.
Tut mir wirklich Leid!
