### ISSUE TITLE
Fahrsilo entladen, Schaufel zu tief

### ISSUE THREAD

**Issue by kferrano** [Stephan-S/FS19_AutoDrive#882]
AutoDrive Version: 1.0.6.8.-10
Release or selbsterstelltes zip: selbsterstelltes zip
Karte (falls relevant): Alle
Fahrzeug(art) (falls relevant): egal

**Beschreibe den Bug**
Schaufel zu tief für Fahrsilo entladen, da die Vorderreifen angehoben werden und der Traktor/Radlader nicht mehr richtig lenken kann

**Comment by kferrano** [comment]
Lösungsvorschlag, selfmade:
in der Datei: AutoDriveBGAUnloader.lua die Zeile 471 `vehicle.bga.shovelTargetHeight = -0.20` zu `vehicle.bga.shovelTargetHeight = 0` ändern und schon klappt alles

**Comment by Iwan1803** [comment]
Das müsste @Stephan-S machen, wenn es denn generell ein Fehler ist.

**Comment by kferrano** [comment]
sollte es weil die schaufel ja unter 0 geht und somit ja das fahrzeug angehoben wird.

**Comment by Stephan-S** [comment]
Die Schaufeln und Fahrzeuge haben hier teilweise recht starke Unterschiede in ihrer Definition für '0'.
Daher habe ich das Ziel etwas herabgesetzt, da sonst nicht alle Schaufeln am Boden angekommen sind und oft noch eine kleine Schicht Silo liegen lassen.

Es ist aber auch eine Überwachung eingebaut, ob mindestens zwei Reifen keinen Bodenkontakt mehr haben (für einige hundert Millisekunden). Wenn das zuschlägt, wird die Schaufel etwas angehoben.

Wie sieht es denn in deinem Fall aus? Haben die Räder gar keinen Bodenkontakt mehr oder ist es eher so ein abwechselnd Kontakt/ kein Kontakt? 
Das Problem ist wenn ich das zu sensibel mache, hebt er bei jeder kleinsten Bodenwelle oder starker Beschleunigung gleich wieder die Schaufel hoch, lässt Silo liegen und wenn er da wieder drüber fährt hebt er sie beim nächsten Mal noch höher, bis man eine richtige Treppe ins Silo fährt

**Comment by kferrano** [comment]
Die Lenkräder (also die Vorderen) haben nur noch ganz minimal Bodenkontakt, zu wenig um zu lenken. Hab es mit Radlader und Frontlader Probiert mit '0' und da klappt alles problemlos
