### ISSUE TITLE
Request: Saving system

### ISSUE THREAD

**Issue by Woife1** [Stephan-S/FS19_AutoDrive#884]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always frustrated when [...] I save some new destinations/Waypoints the destinations from the drivers changes.

**Describe the solution you'd like**
In my opinion the drivers get there destinations from the position in the config not the point directly. (you are free to correct me ;) )

**Describe alternatives you've considered**
The driver take the destination directly, not the position in the config

**Additional context**
If this is false forget this

**Comment by TyKonKet** [comment]
We are closing this issue because of a long time inactivity, If the issue still persists with the latest versions, feel free to open it again.
