### ISSUE TITLE
Request: Abfahrer manuell beladen - Manually load unloader 

### ISSUE THREAD

**Issue by kurtlohnunternehmen** [Stephan-S/FS19_AutoDrive#885]
Ich würde gerne die AD Abfahrer manuell beladen - also ich selber fahre den Mähdrescher oder den Häcksler (Mod mit Tank) - und wenn der jeweilige Tank voll ist, fahre ich zum Wartepunkt der AD Abfahrer und belade sie dementsprechend. Danach fahren die Abfahrer wie üblich selber zur Abladestelle und kehren wieder zurück. Habe so einen Modus bei AD nicht entdeckt: Vielleicht umsetzbar?

I'd like to load the AD unloader manually - so I drive the combine harvester or the forage harvester (Mod with tank) myself - and when the respective tank is full, I drive to the waiting point of the AD unloader and load them accordingly. Afterwards the unloader drive as usual to the unloading point and return again. I have not discovered such a mode at AD: Maybe convertible?

**Comment by haamic** [comment]
Das sollte im Modus "abholen" gehen. 
Zumindest hatte ich damit mal Erfolg. die Abfahrer warteten am Feldrand und wurden in diesem Modus mit dem überladewagen beladen. Ist ja quasi so als würdest du sie selbst Befällen. Sie warten nur bis sie voll sind und starten.

**Comment by Stephan-S** [comment]
Abholen & Abliefern ist der gewünschte Modus.
Alternativ kannst du auch den Drescher Modus nutzen und einfach im selbstgefahrenen Drescher ein anderes Ziel einstellen und 'Abfahrer finden' in den Einstellungen auf Nein.
Dann wartet er auch bis er manuell geladen wurde und fährt dann los
