### ISSUE TITLE
Change of parking function - even attached devices get independent parking destinations / Änderung Parkfunktion - auch angehangene Geräte bekommen eigenständige Parkziele

### ISSUE THREAD

**Issue by haamic** [Stephan-S/FS19_AutoDrive#887]
**Is your feature request related to a problem? Please describe.**
no

**Describe the solution you'd like**

Da man nicht für jedes angehangene Gerät eine eigene Zugmaschine hat, wäre es gut, für die Geräten auch eine Parkposition zu speichern. 
Mal hat man am Traktor einen Pflug, mal ein Güllefass. Ich möchte den Pflug parken, aber nicht den Traktor. Ist das verständlich, wie ich das meine ? Der Parkbutton, greift dabei auf die mit "G" gewählte Komponente zu, entweder Fahrzeug oder Gerät. AD fährt dann den entsprechenden Parkplatz an.
Gruss Micha
---------------------------------------------------------------------------------------------------------
Translated with www.DeepL.com/Translator

Since you don't have your own tractor for every attached device, it would be good to store a parking position for the devices as well. 
Sometimes you have a plough on the tractor, sometimes a liquid manure barrel. I want to park the plough, but not the tractor. Is that understandable, how I mean that? The park button accesses the component selected with "G", either vehicle or implement. AD then drives to the corresponding parking lot.
Greetings Micha

Translated with www.DeepL.com/Translator

**Comment by Stephan-S** [comment]
I personally don't like the idea. I don't want to overload the parking button.
What does the rest of the active guys think here?

**Comment by Woife1** [comment]
Das ist ein 2seitiges Schwert 
auf der einen Seite ist es super wenn man mehr Anbaugeräte/Anhänger hat als Zugmaschinen

nur wohin mit der Option
auf dem Parkbutton ist ja eigentlich kein Platz mehr
Wenn wäre es eigentlich nur möglich das der Anhänger den Traktor überschreibt bei der Parkposition *denk*

**Comment by worker2419** [comment]
Ich finde die Idee zwar interessant, benötige die Funktion aber nicht. Die Anbaugeräte stehen an Positionen oder in Hallen, da komme ich mit AD nicht hin. Also parke ich lieber zentral und fahre die Geräte manuell auf die Parkposition 

Interesting Idea, but don't need the function. The attached Devices are in positions or in halls, I can't get there with AD. So I prefer to park centrally and move the equipment manually to the parking position.

**Comment by haamic** [comment]
Der Button soll ja nicht verändert werden. Nur das, je nachdem was mit "G" gewählt ist, die entsprechende Parkposition vom Gerät oder Fahrzeug gespeichert und angefahren werden kann.

**Comment by Bobster82** [comment]
I like the Idea somehow....
I have some parking destinations to front of a shed "park tools" .... , when arived in front of a shed, I park the implement manually and press the park to park the vehicle...

What I would like to see is a 2nd park button... "park tools" ;)

**Comment by TobiHH78** [comment]
Ich fände das durchaus hilfreich. Ich habe deutlich mehr Geräte als Fahrzeuge, und mein Hof ist weit verzweigt. Da wäre es schon praktisch, wenn ich jedem Gerät eine fest definierte Parkposition zuordnen könnte.

**Comment by Iwan1803** [comment]
Ich benötige sowas eigentlich nicht.
Die Parkplätze haben entsprechende Namen bekommen, wenn dort statt einem Trecker/Gespann nur ein Anhänger steht, z.Bsp. "P - Halle 01 Grubber". Außerdem sind alle Parkplätze in einem Ordner untergebracht.

**Comment by MaGGuS3206** [comment]
Tipp:
Fahr nen CP Kurs ein für dein jeweiliges Anbaugerät( auch rückwärts möglich). Dies machst du für jedes Anbaugerät von einem festem Autodrive-Hofpunkt.(Also zB mit AD in die Hofeinfahrt rein, da in Autodrive einen Punkt speichern.(zB "Parken Hof") Wichtig ist, dass der Punkt über Autodrive angelegt ist, damit CP den findet. Dann kannste von egal wo du bist, Solange ein Wegpunkt vom Autodrive Netz in der Nähe ist, einfach in CP im Autodrive Ordner den Punkt "Hof parken" mit dem Parkplatzkurs des Gerätes kombinieren und den Abfahrer einstellen und er fährt dahin und parkt.

**Comment by haamic** [comment]
@MaGGuS3206 
Klingt kompliziert. Es soll aber nichts erst kombiniert werden, was dann über CP gestartet werden muss. 
"Einfach" mit "G" Fahrzeug oder Gerät auswählen Klick in AD auf "P" und los gehts....

**Comment by TyKonKet** [comment]
We are closing this issue because of a long time inactivity, If the issue still persists with the latest versions, feel free to open it again.
