### ISSUE TITLE
Fahrsilo entladen Modus, berechnet Fahrsilo zu breit.

### ISSUE THREAD

**Issue by kferrano** [Stephan-S/FS19_AutoDrive#888]
AutoDrive Version: 1.0.6,8,-10
Release or selbsterstelltes zip: selbsterstelltes zip
Karte (falls relevant): Alle

**Beschreibe den Bug**
Fahrsilo entladen Modus, berechnet Fahrsilo zu breit.

**Falls anwendbar - Schritte mit denen ich den Bug nachstellen kann**

**Screenshots**
![image](https://user-images.githubusercontent.com/28959314/69003999-036db380-090c-11ea-9708-a7eb68bd043a.png)

**Comment by Stephan-S** [comment]
Dazu kannst du die Schaufelbreite in den Einstellungen etwas erhöhen.
Oft liegt das Silo aus optischen Gründen etwas in der Wand.

**Comment by kferrano** [comment]
wo kann ich die Schaufelbreite erhöhen?

**Comment by Stephan-S** [comment]
Im Einstellungsmenü von AutoDrive natürlich ;-)
