### ISSUE TITLE
Driver could not calculate a path

### ISSUE THREAD

**Issue by spielera** [Stephan-S/FS19_AutoDrive#890]
AutoDrive Version: 1.0.6.8
Release or selbsterstelltes zip: Release
Karte (falls relevant): Alle
Fahrzeug(art) (falls relevant):

**Beschreibe den Bug**
Fahrzeug wartet am Feldrand, daß der Mähdrescher voll wird.
Wenn es so weit ist, kommt die Fehlermeldung(Fahrer konnte keinen Pfad berechnen). AD geht dann aus.

**Falls anwendbar - Schritte mit denen ich den Bug nachstellen kann**

**Screenshots**
<a href="https://www.bilder-upload.eu/bild-1a553d-1574006724.png.html" target="_blank"><img src="https://www.bilder-upload.eu/thumb/1a553d-1574006724.png" border="1" alt="Bilder-Upload.eu - share DEINE Bilder" /></a>

Danke, für die viele arbeit, die ihr euch macht. Macht weiter so.

**Comment by Woife1** [comment]
Geh ins AD Menü und stell im Drescher Menü (Combine Unload Settings, rechter Tab) die Pfadfindungsdauer auf einen höheren Wert (musst nen bischen testen welcher passt)

**Comment by Stephan-S** [comment]
Ist ein Fehler in der 1.0.6.8. Ist schon in den aktuellen Quellen behoben.
Neues Release kommt vielleicht heute noch

**Comment by spielera** [comment]
HI Stephan-S ,
danke für die schnelle Antwort.
Macht weiter so.
