### ISSUE TITLE
Autodrive settings more saved vehicle specific than globally for all

### ISSUE THREAD

**Issue by geo-luchs** [Stephan-S/FS19_AutoDrive#891]
**Is your feature request related to a problem? Please describe.**
There are some settings for Autodrive, which are currently stored globally for all vehicles.
So, If I'm setting "Filed exist" to "nearest by", it will be valid for all vehicles.

But for me it depends on each geometry of the field, if I would like to use "nearest by" or "behind start"
So if I'm working with 2 or more vehicles as unloader on different fields, on one field it is ok, but for another field it could be the wrong setting for me.

**Describe the solution you'd like**
Please move settings from AD globally (shown on havester tab) to the vevicles tab and store it for each vehicle
e.g.:
Field exit
fruit check
follow dresher

but perhaps all others, too.

if there are any doubts, please I'm open for it ;-)

**Comment by raxtor** [comment]
Personally I dont like individual vedhicle settings mixed with global settings. In more than 3 vehicles you will lose very fast overview. In case there will be posssibility set individual settings for every vehicle than HUD should inform you about all important vehicle settings. Something like extended HUD or reworked HUD.

**Comment by geo-luchs** [comment]
at least the exit position should be defined for each vehicle. because it depends on the field, where the vehicle is working.
2 or more vehicles are working in parallel on different fields, which  needs different settings.

**Comment by Stephan-S** [comment]
I added 4 of the combine unloader related settings to the vehicle specific page in the 1.0.7.0 release
