### ISSUE TITLE
reversing

### ISSUE THREAD

**Issue by ploughedfieldman123** [Stephan-S/FS19_AutoDrive#895]
I dont know if this is correct place to ask as I cant seem to find no where now to ask. so I apologise for this.  my question is below. and I seem to get both routes together, but tractor drives only 6mph

I use Autodrive mod for routes, and just use CP for field work. my question is AutoDrive dont have a reversing option, where as CP does. what I need to know is if I do a short CP route to dump straw, which requires a reversing into trigger. can this be linked up with AutoDrive, so say like on AD I set it to go to barn. this is on GreenWich Valley map  will CP auto take over to dump trailer of straw where its required. or will I have to start CP course myself

**Comment by Woife1** [comment]
with reverse tipping you need a CP course 
you can use AD curses with CP to (AutoDrive folder in CP) you make the reverse tipping course and save it
than take a course from the AD folder adding the reverse tipp course and add a course to come back or let it end at the tipping course

**Comment by ploughedfieldman123** [comment]
> with reverse tipping you need a CP course
> you can use AD curses with CP to (AutoDrive folder in CP) you make the reverse tipping course and save it
> than take a course from the AD folder adding the reverse tipp course and add a course to come back or let it end at the tipping course

Hi Woife1,

thanks for replying back to me its most appreciated. But I cant seem to find where to ask for help on AutoDrive, so asked here

Im a bit confused how to do all this, I play on GreenWich valley map, and want to dump straw at Barn place on map near GreenWich Mill I think it is. I dont suppose you could make a route showing how this is done. I did try once. I opened CP opened AD folder added barn, then looked in CP for tip route with reversing, added that 2 so it said 2 combined courses. started CP and it started going along route towards barn, but was only going very slow at say 6 mph 9.65KMH  and I couldnt see how to speed it up also when it got to tip trigger it didnt tip just went off again back

**Comment by Woife1** [comment]
you could change the speed settings in CP (the tab with the tachometer)
and your course sounds like CP didn't recognize teh trigger

Autodrive did not get the reverse feature couse it will go wrong with the actuall working 
AD only drives your tractor/truck/car and didn't recognize any trailor (you could test it when you put a trailor on the front (if the collision detection allows to drive))

**Comment by ploughedfieldman123** [comment]
> you could change the speed settings in CP (the tab with the tachometer)
> and your course sounds like CP didn't recognize teh trigger
> 
> Autodrive did not get the reverse feature couse it will go wrong with the actuall working
> AD only drives your tractor/truck/car and didn't recognize any trailor (you could test it when you put a trailor on the front (if the collision detection allows to drive))
I did check the CP tab where speed on road was. but nothing what I did made any difference.  when I do the reverse should I make a unload point. or do nothing

**Comment by Woife1** [comment]
A unload point is to tip on ground
when set a waiting point

**Comment by ploughedfieldman123** [comment]
> A unload point is to tip on ground
> when set a waiting point

so I don't say unload point. as it's a trigger  so what do i say

**Comment by tozedascoves** [comment]
@ploughedfieldman123 sorry to ask this question here but do you have a course for Greenwich valley?
Can you share it please?

**Comment by Woife1** [comment]
where does the muddy way goes?

either you build a reverse course with CP from the Waypoint Barn
or you can try to build a AD "course" through the tip place (check the size of the trigger before)

**Comment by ploughedfieldman123** [comment]
> @ploughedfieldman123 sorry to ask this question here but do you have a course for Greenwich valley?
> Can you share it please?

Hi  yes I will send to you tommoro. as it's on my PC.    I also was wondering how others here do there routes on Greenwich valley map.  so if there is anymore here who have made routes on this map they could share too. as I like to know if I have done them right

**Comment by ploughedfieldman123** [comment]
> where does the muddy way goes?
> 
> either you build a reverse course with CP from the Waypoint Barn
> or you can try to build a AD "course" through the tip place (check the size of the trigger before) it will have a few sharp curves

what do you mean. where does the muddy way go.  if you mean the path the tractor is on it's just came from the main road

how can I build a AD course through tip place. as AD cannot do reverse.  also the tip place isn't like a drive through it's a dead end.   when I do the reverse route from barn back to trigger.  what do I add at trigger is it a crossing or unload point or just nothing. as when I tried 1 thing it didn't tip just say in F1 menu press I  as in name India I to unload

**Comment by Woife1** [comment]
i take my paint skills to show what i mean ;)
![2019-11-19-094230](https://user-images.githubusercontent.com/55350545/69191223-5f118a00-0b22-11ea-9750-10dae680f5a7.jpg)

**Comment by ploughedfieldman123** [comment]
> i take my paint skills to show what i mean ;)
> ![2019-11-19-094230](https://user-images.githubusercontent.com/55350545/69191223-5f118a00-0b22-11ea-9750-10dae680f5a7.jpg)

Oh so you mean use AD to go through trigger. yes it will be very tight. but can give it a go.  I believe that muddy track leads into a big field

**Comment by ploughedfieldman123** [comment]
> @ploughedfieldman123 sorry to ask this question here but do you have a course for Greenwich valley?
> Can you share it please?

As  Promised            http://www.filedropper.com/autodrivegreenwichvalleyconfig

**Comment by tozedascoves** [comment]
Just looked at it. It's great, can't thank you enough.

Btw do you do the course ingame or do you use the editor?

Looks so perfect.

**Comment by ploughedfieldman123** [comment]
> Just looked at it. It's great, can't thank you enough.
> 
> Btw do you do the course ingame or do you use the editor?
> 
> Looks so perfect.

No I make the routes in the game.  But if you use Blue line drive down middle of roads, you can also  use blue lines to mark edges of roads too both side. then in the editor. you have a rough idea if you green lines are nice and straight. if not just move them to middle of road more using those blue lines you made for reference and side ones. when done just delete the blue lines you made. dont delete normal blue lines where roads are narrow

**Comment by TyKonKet** [comment]
We are closing this issue because of a long time inactivity, If the issue still persists with the latest versions, feel free to open it again.
