### ISSUE TITLE
Abfahrer fahren bei 100% nicht ab

### ISSUE THREAD

**Issue by kferrano** [Stephan-S/FS19_AutoDrive#898]
AutoDrive Version: 1.0.6.9-1
Release or selbsterstelltes zip: selbsterstelltes zip
Karte (falls relevant): Alle
Fahrzeug(art) (falls relevant):

**Beschreibe den Bug**
Seit heutigem Update (download von 18:00Uhr) fahren die Abfahrer bei 100% nicht mehr ab sondern bleiben stehen. und Ja die haben den Kurs gefunden, den wenn ich manuell auf Weiterfahren klicke fahren die zum zielort, laden ab und kommen wieder.

**Falls anwendbar - Schritte mit denen ich den Bug nachstellen kann**
z.b. BGA Silage abfahren aus Fahrsilo, trecker bleiben stehen trotz 100% und AD aktiv.

**Screenshots**
Falls relevant, bitte Screenshots beifügen
https://www.youtube.com/watch?v=p4II36s9COY&feature=youtu.be

relevant nur bis 19 sekunden.

**Comment by Woife1** [comment]
Video nicht verfügbar
ändere mal die Einstellung von dem Video (wird als Privat gekennzeichnet)

**Comment by Drummer30876** [comment]
Im Multiplayer klappt das entladen und beladen nicht, hält bei den Punkten an aber es passiert nichts
Im Singleplayer klappt alles

**Comment by Iwan1803** [comment]
@kferrano 
Stephan hat eine kleine Verzögerung eingebaut. Warte mal ein paar Sekunden, ob er wirklich nicht von alleine abfährt.

**Comment by kferrano** [comment]
@Iwan1803 video sollte jetzt verfügbar sein

**Comment by kferrano** [comment]
@Stephan-S bin auf die aktuelle release version 1.0.6.9 gewechselt und auch da fährt er Silage nicht ab, nachdem er vom Radlader beladen wurde (Fahrsilo entladen Modus)

**Comment by Stephan-S** [comment]
Ist in 1.0.7.0 erledigt :-)
