### ISSUE TITLE
Load & Unload not working in MP

### ISSUE THREAD

**Issue by Drummer30876** [Stephan-S/FS19_AutoDrive#899]
AutoDrive Version: 1.0.6.9
Release or selbsterstelltes zip: Release
Karte (falls relevant): Alle
Fahrzeug(art) (falls relevant):

**Beschreibe den Bug**
Eine klare Beschreibung des Bugs.

**Falls anwendbar - Schritte mit denen ich den Bug nachstellen kann**

**Screenshots**
Falls relevant, bitte Screenshots beifügen

Im Multiplayer klappt das entladen und beladen nicht, hält bei den Punkten an aber es passiert nichts
Im Singleplayer klappt alles

**Comment by Drummer30876** [comment]
ist ein Dedi Server

**Comment by WarchildTW** [comment]
Same issue here.
AutoDrive Version: 1.0.6.9
Release or selbsterstelltes zip: Release
Karte (falls relevant): Alle
Fahrzeug(art) (falls relevant):

Im Multiplayer klappt das entladen und beladen nicht, hält bei den Punkten an aber es passiert nichts
Im Singleplayer klappt alles

Die enzelnen Trigger werden korrekt angefahren, Fahrzeuge bleiben aber nicht stehen.

**Comment by Stephan-S** [comment]
@TyKonKet I just pull you into all MP related issue. And if only to confirm that the bug exists while you have the time :-) But I will look into it when I get to it

**Comment by TyKonKet** [comment]
@Stephan-S I'll test also that 😄

**Comment by TyKonKet** [comment]
Unload works fine for me, the problem is with 'Load Mode', trigger is approached correctly, the loading is started but the vehicle never stops so it leave the trigger before he gets full.
