### ISSUE TITLE
Wrong destination+ config_file.xml size changed

### ISSUE THREAD

**Issue by Anonymous-any** [Stephan-S/FS19_AutoDrive#9]
Hi,
Today I launch my savegame and I see, the log when AD set recalculation to true, while I'm start load game.
Of course, I did not have time to change anything in my routes because I start :)
I add you the config_file.xml changed size too at starting game, I lose something like 230Ko of 1.30Mo inside and I can't compare the diff with my tool and because of the structure of the file.
Of course if the file lose information's I think it's the cause the destination go wrong after that.
Picture joined:
```
dataS2/character/humans/player/player01.i3d (792.52 ms)
  Setting 'Radio Volume': 0.5
  Setting 'Vehicle Volume': 0.80000001192093
  Setting 'Environment Volume': 0.80000001192093
  Setting 'GUI Volume': 0.5
  Info: Savegame Setting 'dirtInterval': 3
  Info: Savegame Setting 'plantGrowthRate': 1
  Info: Savegame Setting 'fuelUsageLow': false
  Info: Savegame Setting 'plowingRequiredEnabled': false
  Info: Savegame Setting 'weedsEnabled': true
  Info: Savegame Setting 'limeRequired': true
data/objects/pallets/missions/transportPalletBottles.i3d (107.48 ms)
data/objects/pallets/missions/transportPalletCrates.i3d (58.60 ms)
data/objects/pallets/missions/transportPalletBottles.i3d (1.44 ms)
dataS2/character/crow/crow.i3d (46.09 ms)
dataS2/character/humans/player/player02.i3d (527.91 ms)
AD: Set to recalculating routes            <- At loading savegame...
Game saved successfully.
Saving screenshot: C:/Users/xx/Downloads/My Games/FarmingSimulator2019/screenshots/ 
```
I tried to do load - unload functionality :)
![1](https://user-images.githubusercontent.com/25174503/53834722-14e47a80-3f8c-11e9-8a96-f93dcce1d258.png)
Edit: Damn after a new try to loading game with good config_file.xml backup, this time I get `"AD_cannot_reach"`
Hope you got all
Br

**Comment by Anonymous-any** [comment]
Back to say, for some unknown reasons, i tried more time different method to manage to export from a good file then the exported file became very low size few ko to after time (dunno why) but a bit like Fs17, and seem to work fine after re-import that It back to 1mb or more after saving the game (I add routes more now) and export it every time i made change, export file always stay few size now, destinations inside not became for some double (double seem happen when you remove a destination name), and It seem not need always to recalculate just after load game now.

Regard

**Comment by Stephan-S** [comment]
Hey sorry I was busy the last week and had no time for AutoDrive.
Can you please send me your config files?
Also because I changed the structure of the config files in a previous commit, you could try exporting a working config. Then closing the game and replace the exisiting config with the exported one.
The new format is quite a bit smaller in size.

**Comment by Anonymous-any** [comment]
Hi, omg sorry i've not keep what is not work, but I think you can reproduce issue when you start with a unknown map for AD then, do some path and waypoints destinations name (a few not only one) then save, reload the game continue to add waypoints and destinations then remove a destination you made the 1st time (maybe work with last time you add dest. too), and try to recalculate adding new destination name and normally your savegame became incorrect for the last destinations you made like double  `<mmXX>` number. Also you can try to delete a destination then back to choose with <- arrow HUD another destination then you go see the console show issue too, I don't know if these are linked to but FS17 version had made the same.

Ps: The new format is quite a bit smaller in size. Yes I see that ;)
It look like a bit to Fs17 but because I remember now to it, I was got the same issue on Fs17 version like double or incorrect `<mmXX>` number same method I explained. And I had the same the proceed method export import you explain to solve it but that implicate to manage with button to attribute to export import commands, but I think young players or lots players don't want to solve with issue's.

Hope you go found

**Comment by Stephan-S** [comment]
Hey, finally found and fixed the issue :-)

**Comment by Anonymous-any** [comment]
Hi :) my bad past life won't me I sleep.
Oh yea you so good I am in a hurry going to test ^-^
Many many many thanks
