### ISSUE TITLE
Liquid-Transporter didn't driver after unloading/hangs in unloading

### ISSUE THREAD

**Issue by Woife1** [Stephan-S/FS19_AutoDrive#900]
AutoDrive Version: 1.0.6.9
Release or custom zip: Release+Axel's Code
Map (if applicable): NF 4fach
Vehicle / type (applicable): Truck with MKS 32 (modded) @ GC trigger (didn't yet testet other)

**Describe the bug**
The driver stays in unloading even if he is empty 
he drives off if you hit go forward (weiterfahren)

**If applicable - Steps to reproduce the behavior**
use a liquidtransporter and set him on a pick up and deliever route 
i test later or tomorrow other trigger and tools

**Screenshots**
a standing truck is not this interessting ;) 

@Axel32019 you could take a look too if this in your code

**Comment by Iwan1803** [comment]
@Stephan-S hat wohl eine kleine Verzögerung eingebaut. Warte mal ein paar Sekunden, ob er dann los fährt.

**Comment by Woife1** [comment]
10 Sekunden sind vertretbar nur bei 1 Minute dauerts doch ein bischen lang ;)

**Comment by Iwan1803** [comment]
Die Frage ist ja, warum @Stephan-S eine so lange Verzögerung eingebaut hat.

**Comment by Woife1** [comment]
ich hab noch nicht herausgefunden wie lange die Verzögerung ist aufjedenfall >1 Minute

**Comment by Murtlock** [comment]
Hi Stephan.I`m having the same problem with liquid trailers as Woife1
playing NF Marsch 2.6 map used vanilla transporters as well as modded ones result still the same on all maps i might include

**Comment by Stephan-S** [comment]
I already added the duplicate issue to my todo list. So I'm closing this one but I will look into it.
