### ISSUE TITLE
Invoke CP when reaching destination

### ISSUE THREAD

**Issue by MaGGuS3206** [Stephan-S/FS19_AutoDrive#902]
Hallo, 

Ich hab mich jetz ne ganze weile damit beschäftigt wie Autodrive mit Courseplay kombinierbar ist. Erstmal cool, dass es überhaupt möglich ist dass CP das AD-Streckennetz zur Kursgenerierung nutzen kann. Jetzt zu meiner Frage:

Ist es möglich einen Modus einzubauen, bei dem man Autodrive zB sagt Fahr zu Punkt "Feld 20 Start" und stelle dann in Courseplay den Abfahrer ein.

Damit könnte man dann einen Feldkurs, zB "Feld 20 Grubbern" laden und Autodrive dann sagen fahr zu "Feld 20 Start" und starte den Abfahrer. Habs mit Kurs kombinieren versucht, Courseplay findet zwar dank Autodrive den weg zum Feld, aber fährt halt auch direkt mit gesenktem Grubber los. Daher meine Idee mit der Abfahrer einstellen Funktion in Autodrive...

Gruß MaGGuS :)

Edit: 
Mir ist gerade noch ne Verbesserung eingefallen:

Cool wäre zB auch, wenn man mehrere Feldkurse "abarbeiten" könnte. Fahr zu Feld 3 starte dort Courseplay Kurs Grubbern und wenn fertig, fahr zurück zum Hof. Quasi so ähnlich wie Courseplay Autodrive zum tanken nutzt...

Mein Gedankengang zum Verständnis: Ich würde gerne auf dem Hof das Gerät zB den Grubber anhängen, Autodrive sagen fahr zu Feld 20 starte dort CP mit Kurs "Feld 20 Grubbern" und wenn du fertig bist fahr zum Hofpunkt und park da den Grubber wieder(deshalb der 2. Kurs, da Autodrive den Hänger nicht Rückwärts parken kann.

Das wäre aber nur eine Ergänzung/Verbesserung. Mir würde es vollkommen reichen wenn Autodrive den Knopf "Abfahrer einstellen" in CP drückt wenn der den Feldpunkt erreicht^^

**Comment by MaGGuS3206** [comment]
Mir ist gerade noch ne Verbesserung eingefallen:

Cool wäre zB auch, wenn man mehrere Feldkurse "abarbeiten" könnte. Fahr zu Feld 3 starte dort Courseplay Kurs Grubbern und wenn fertig, fahr zurück zum Hof. Quasi so ähnlich wie Courseplay Autodrive zum tanken nutzt...

Mein Gedankengang zum Verständnis: Ich würde gerne auf dem Hof das Gerät zB den Grubber anhängen, Autodrive sagen fahr zu Feld 20 starte dort CP mit Kurs "Feld 20 Grubbern" und wenn du fertig bist fahr zum Hofpunkt und park da den Grubber wieder(deshalb der 2. Kurs, da Autodrive den Hänger nicht Rückwärts parken kann.

Das wäre aber nur eine Ergänzung/Verbesserung. Mir würde es vollkommen reichen wenn Autodrive den Knopf "Abfahrer einstellen" in CP drückt wenn der den Feldpunkt erreicht^^

**Comment by Iwan1803** [comment]
Man kann in CP einstellen, das er im Anschluss z.Bsp. an eine Feldarbeit AD nutzen soll, um das Fahrzeug auf seinen Parkplatz zu schicken.

**Comment by MaGGuS3206** [comment]
Ja ich weiß, das bringt mir aber nichts, weil ich den feldkurs ja nach der Überführung starten will und nicht danach :) Deine Möglichkeit klappt super und ich hab da auch schon ne Möglichkeit, dass ich den Fahrer vom Feld zum Hof schicke und er dort dann auf seinen Parkplatz fährt. Ich würde aber gerne einen Kurs in CP laden und Autodrive sagen, fahr zu feld 2 und starte dann den geladenen CP-Kurs.

**Comment by Iwan1803** [comment]
Die Idee wäre also:
1. du konfigurierst CP für den nächsten Einsatz, z.Bsp. grubbern auf Feld X mit Kurs Y
2. du lässt per AD das Gespann zum Einsatzort fahren, z.Bsp. Startpunkt A auf Feld X
3. wenn es angekommen ist, startet AD automatisch CP
Dann lehnst du dich entspannt zurück, schaust zu und wartest auf das Ende, wobei CP das Gespann nach Abschluss der Arbeit per AD auf seinen Parkplatz zurückschickt.

@Stephan-S 
Sollte doch machbar sein, oder? Immerhin schafft es CP ja auch, AD anzusprechen.

**Comment by Stephan-S** [comment]
Prinzipiell kein großes Problem. CP müsste mir ein Interface anbieten, so wie AD es ja auch CP anbietet, damit sie die Kontrolle übergeben können.

Dann stellen sich noch zwei Fragen:
1. Ist es sinnvoll? Liegen die Feldziele immer so dass man CP problemlos von dort starten kann? AD wird auch nicht verifizieren ob die CP Einstellungen Sinn machen. Es wird wenn dann einfach dort 'Fahrer einstellen' oder was CP als Interface anbieten wird, aufrufen.
2. Wie soll es gestaltet werden? Wie soll AD wissen, dass es CP am Ziel aufrufen soll?
Vielleicht wieder so eine sekundäre Belegung für den Start Knopf. Rechte oder mittlere Maustaste auf den Startknopf aktiviert am Ende des Kurses CP

**Comment by Iwan1803** [comment]
zu 1. das muss jeder, der es nutzen möchten, selber prüfen
zu 2. Sekundärfunktion auf dem Start-Button finde ich gut

**Comment by raxtor** [comment]
@Stephan-S I was thinking about it too... Elegant and clear solution would be new working mod similar to Drive mode but after reaching target point it will start CP with current configuration. No idea if there wont be conflict for Load mode (seeders, fertilizers).
But do we realy need this one all for 1 manual click which start CP fieldwork? Not sure...

**Comment by MaGGuS3206** [comment]
Genau, Ich dachte mir man stellt sich wie Iwan richtig erkannt hat in CP nen Kurs ein um eine Feldarbeit zu erledigen, wie ich es auch am Feld machen würde bevor ich den Abfahrer einstelle. Natürlich muss der Feldkurs immer an dem Punkt anfangen an dem Autodrive dann ankommt. In Autodrive dann einfach nen Modus wie "CP-Kurs starten". Wenn Autodrive dann am Feld ankommt soll er lediglich den "Abfahrer einstellen" und Autodrive abschalten. In Courseplay kann ich ja wieder einstellen, dass er dann tanken und sowas von AD übernehmen lässt.

**Comment by haamic** [comment]
@Stephan-S 
Zu deiner 1.Frage, ob es sinnvoll ist, das muss jeder für sich entscheiden (siehe Vorschlag Speicherung Parkposition für Geräte). Manche brauchen das, manche nicht. 
Meine Feldziele, liegen so, das ich dort die erstellten CP Feldarbeitskurse problemlos starten kann. 
Aber ich persönlich bräuchte die Funktion nicht. Bisschen was tun sollte man schon noch selbst. Da könnte man ja gleich weitergehen und sagen. Das eine Art Tagesplan integriert wird wo man ...zig Fahrzeugen Aufgaben zuweist, wohin sie fahren sollen, was sie dort arbeiten sollen, was danach passieren soll. Vielleicht sogar anhand des Feldes erkennen ob gedüngt, gepflügt, gekalkt, gesät, geerntet werden soll. 
Zu viel Automatismus, muss ich nicht haben. Meine Meinung. Da ginge der Spielspaß flöten...
Wenn alle noch vorhandenen Probleme beseitigt sind, bin ich voll zufrieden. 
Danke für die bisherige super Arbeit. Gruß Micha

**Comment by Iwan1803** [comment]
Wenn CP schon in der Lage ist, AD zu starten (Fill/Unload und Parking), warum sollte dann AD nicht auch einfach CP starten können?
Ich fände es nützlich, besonders wenn man mit vielen Maschinen nahezu gleichzeitig hantieren muss.
Es klingt nach einer Kleinigkeit, aber ich kann nicht beurteilen, wie lange eine Implementierung dauern würde.

**Comment by KCHARRO** [comment]
Ich bin zufrieden, dass sie die verbleibenden Probleme beseitigen und keine weiteren Funktionen hinzufügen, da dies die Dinge komplizieren und neue Probleme erzeugen würde und wir FS21 ohne eine endgültige Version von AD verlassen würden.

Obwohl mir die hier vorgestellten Ideen gefallen.

@ Stefan-S: Du bist großartig, großartige Arbeit ....

**Comment by MaGGuS3206** [comment]
Okay die Idee von haamic hört sich schon sehr cool an...irgendwie... :D Aber wie gesagt, es würde ersteinmal vollkommen ausreichen, wenn AD den Abfahrer startet. Man spart sich damit zB einiges hin und her switchen. Beispiel: Bin am Holz hacken, schick 3 Arbeiter zu 3 unterschiedlichen Feldern und brauch mich erst wieder um die kümmern wenn die fertig sind und nicht jeden noch einmal extra anwählen zum starten, wenn er am Feld angekommen ist. 

Alles andere hört sich zwar super an, aber denke ich sprengt den Rahmen. Ich denke eine einfache Zusatzfunktion beim Überführen würde völlig ausreichen. 

Aber danke schonmal für die schnellen Antworten :)

**Comment by pvaiko** [comment]
> Liegen die Feldziele immer so dass man CP problemlos von dort starten kann?

Wenn die nah genug am Feld sind und pathfinding in CP eingeschaltet ist dürfte das kein Problem sein.
