### ISSUE TITLE
Delete Waypoints , return after recalculation. Dedicated Server

### ISSUE THREAD

**Issue by Justice-Molton** [Stephan-S/FS19_AutoDrive#903]
AutoDrive Version: 1.0.6.9
Release or custom zip: Release
Map (if applicable): Kandelin
Vehicle / type (applicable): any

**Describe the bug**
If we try to delete already recorded waypoints, they are back after recalculation of the courses

**If applicable - Steps to reproduce the behavior**
Go on a Dedicated Server record some waypoints, safe, and after that try to delete some of them. After a recalculation the deleted waypoints are back.
**Screenshots**

**Comment by c0p3y** [comment]
I see this is closed, was there a resolution to this issue as we are having the same problem on our dedicated servers?
Tested versions: 1.0.6.9, 1.0.7.0

Thanks.
