### ISSUE TITLE
driver too fast, overdriving load trigger

### ISSUE THREAD

**Issue by geo-luchs** [Stephan-S/FS19_AutoDrive#904]
AutoDrive Version: 1.0.6.9-7
Release or selbsterstelltes zip: Zip
Karte (falls relevant): Alle
Fahrzeug(art) (falls relevant):

I've again the problem, that my drivers drives too fast (often).
e.g. Tractor with Seeder, which shall load both seed and fertilizer, is reaching the triggers, but speed is too high at the first load trigger. Then he is getting only a few fertilizer, vehicle stops, but between fertilizer and seed load trigger.

![too_fast](https://user-images.githubusercontent.com/53658780/69182939-4600dd00-0b12-11ea-8a9b-5cba503e9ff6.png)

Similar problem on the field for unloading harvester.
If unloader has a longer straight route to harvester, speed is too high, and he drives through, and doesn't match the pipe.

This was already better in older versions.

**Comment by Woife1** [comment]
it looks like the trigger detection is to small
do you try a longer distance for this (50m than 25m)?

a workaround could be to take seed and fertilizer in your silo and let AD pick it from there ;)

**Comment by geo-luchs** [comment]
I've set it to 100m
unfortunately it doesn't happen each time.
currently I had it that it worked fine.
Also on the field, when combine the harvester, it works.
I really don't know, why it sometimes happens, and sometimes not.

**Comment by Woife1** [comment]
can you try a few runs and watch the speedOverride
maybe the override comes to late

**Comment by geo-luchs** [comment]
I've tried it now several times, no problem anymore.
I've no idea.
So I will close it for now.
