### ISSUE TITLE
Unloading of forage wagon stops for no apparent reason

### ISSUE THREAD

**Issue by rgoe** [Stephan-S/FS19_AutoDrive#905]
AutoDrive Version: 1.0.6.9-1
Release or custom zip: custom zip
Map (if applicable): MultiMap 2019 2.3
Vehicle / type (applicable): Forage wagon Rapide 580V

**Describe the bug**
AD invoked from CP. Forage wagon collecting Gras - delivering to storage (GC).
Trailer starts unloading via "right side" although "back" was selected initially. Unloading stops after 25-30% for no apparent reason and tractor doesn't move, from this point: 
- Stopping and immediate restart of AD => unloading finishes either via back/left/right (selection of unloading side seems random). Continues on route after pressing continue on HUD or restart of AD. 
- Pressing continue on AD HUD => tractor continues on route without unloading further.

Same situation using another forage wagon (Krone ZX560GD) - everything works as expected (Stops, unloads, continues) This one has no option to unload to the sides.

**If applicable - Steps to reproduce the behavior**
Setup used: MF7700 tractor with Schuitemaker Rapide 580V
Map MultiMap 2019 2.3 - Collecting  grass on Field 09 using CP (6.01.00337) and delivering to grass storage on farm yard.

**Screenshots**
Unloading via right side after approaching GC trigger
![fsScreen_2019_11_19_21_59_40](https://user-images.githubusercontent.com/21224499/69188085-21116780-0b1c-11ea-8927-c006600283e2.png)

Stops unloading after 25-30% unloaded
![fsScreen_2019_11_19_21_59_51](https://user-images.githubusercontent.com/21224499/69188161-47370780-0b1c-11ea-9f10-8a155564ade2.png)

Continuing unloading after restarting AD (but not continuing on route)
![fsScreen_2019_11_19_22_21_14](https://user-images.githubusercontent.com/21224499/69188213-60d84f00-0b1c-11ea-9082-c821843b36b3.png)

Continue on route without finishing unloading after pressing continue on HUD:
![fsScreen_2019_11_19_22_32_37](https://user-images.githubusercontent.com/21224499/69188501-f247c100-0b1c-11ea-919f-f7c0a0612448.png)

**Comment by Stephan-S** [comment]
Should be fixed with the latest release :-)
