### ISSUE TITLE
Request: AutoDrive_Greenwich_Valley_config.xml

### ISSUE THREAD

**Issue by ploughedfieldman123** [Stephan-S/FS19_AutoDrive#906]
AutoDrive  version 1.0.6.9

Anyone here who plays GreenWich Valley Map, wont mind sharing there  AutoDrive_Greenwich_Valley_config.xml file   so I can see how there routes are done.   in English if possible 

thanks in advance

**Comment by Stephan-S** [comment]
Since no one is reacting, I will close this one. Sorry @ploughedfieldman123
