### ISSUE TITLE
Start direction 

### ISSUE THREAD

**Issue by Martinnygaard** [Stephan-S/FS19_AutoDrive#908]
Hi,

When I start a route, i think it used to limit the startdirection to the way the tractor is pointing.
In this case, the tractor is aligned perfect with the route, and AD chose the opposite direction. (It is a few nodes shorter, but both way leads to my destination.

In this case, the tractor went circle because it could never reach that point directly behind it.

![image](https://user-images.githubusercontent.com/26490587/69251625-fa057500-0bb1-11ea-8479-40fd409bbdb9.png)

**Comment by Woife1** [comment]
Do you have selectet "fastets route"?
it could be the route "backwards" is shorter and/or a faster way

**Comment by Martinnygaard** [comment]
No, fastest route is set to "off" :-)

**Comment by Stephan-S** [comment]
AD cannot take your direction into consideration.
If you have a Dual way Road, there is only one Route calculated for each Point/node. And If this Points the other way, it will take this path.

**Comment by Martinnygaard** [comment]
Okay, i thought this 90 degree angle rule to the wanted angle was supposed to apply here as well. :-) 
Issue closed.
