### ISSUE TITLE
Entire Network is gone after install new update of AD

### ISSUE THREAD

**Issue by BlitzKrieg-76** [Stephan-S/FS19_AutoDrive#909]
AutoDrive Version: 1.0.6.9
Map (if applicable): New WoodShire

**Describe the bug**
Yesterday I installed a new update of AD and now the entire network of tracks created by me on the map is gone.

**Comment by Iwan1803** [comment]
Maybe an update of the map? Check if the XML is still in the save game folder.

**Comment by BlitzKrieg-76** [comment]
The network is create by me, and the xml file is still in the save game folder..
![File](https://user-images.githubusercontent.com/53381846/69271620-14008100-0bcd-11ea-9815-f61ad45e6fc9.png)

the routes are still in xml
![Courses](https://user-images.githubusercontent.com/53381846/69271675-309cb900-0bcd-11ea-996a-893d84178a8e.png)

but do not appear in the game
![Game](https://user-images.githubusercontent.com/53381846/69271722-49a56a00-0bcd-11ea-8c1e-0758082d1de6.png)

**Comment by TyKonKet** [comment]
SP or MP?
Why the xml is not in the savegame folder?

**Comment by BlitzKrieg-76** [comment]
you were right. I don't know why, but the file disappeared from the game folder and was only in the AD folder. It's already solved. thank you

**Comment by TyKonKet** [comment]
😄 no problem
