### ISSUE TITLE
Frage: Zuckerrohrernter abtanken? harvest sugar cane, not chopping it?

### ISSUE THREAD

**Issue by Iwan1803** [Stephan-S/FS19_AutoDrive#910]
Ich wollte heute mal mein erstes Zuckerrohrfeld abernten (nicht häckseln!), aber ich bekomme es einfach nicht hin.
Als Ernter habe ich 2* Case Austoft 8800 (Standard von LS19) eingesetzt, den Kurs mit Courseplay eingestellt und erstmal nur 1 gestartet (AD-Ziel: das Feld).
Die 2 Abfahrer habe ich auf den Dreschermodus eingestellt: als Startpunkt das Feld, als Ziel mein Silo. Sie fahren auch brav zum Feld hin, aber dann passiert einfach nichts mehr.
Abfahrer früher rufen ja/nein, Drescher folgen ja/nein, .... nichts scheint zu helfen.
Leider finde ich nur Videos zum Häckseln, aber nicht für die Ernte.
Jemand einen Tip?

**Comment by Wienet** [comment]
Hi,
bin selbst kein Experte, aber bist du sicher, dass du Zuckerrohr im Silo lagern kannst? Ging bei mir nicht, ich verkaufe es gleich.
Mit der Standart-Erntemaschine von LS19 bin ich überhaupt nicht klar gekommen (nur AD, kein CP); habe mir eine modifizierte Version "besorgt". Damit klappt es super.
Gruß Marc

**Comment by Michael170978** [comment]
Hi

Soweit ich weiß gilt der Zuckerrohrernter im AD bzw. in CP nicht als Drescher. Somit wundere ich mich auch nicht warum dein Abfahrer zum Ernter nicht hingefahren ist. Bei frühren Version von CP da war es sogar so, dass sich das Spiel aufhängte wenn man versuchte den Ernter mit CP abzuernten. Bei der kleinen Grimme Erntemaschine bzw. Zuckerrübenmaschine ist es genauso.

**Comment by Michael170978** [comment]
Edit: Es gibt einen umgebauten  New Holland Häcksler als Mod der in der Lage ist Zuckerrohr zu ernten. Mit dem müsste AD klar kommen. Ist zwar unrealistisch aber das ist im Moment die einzige Möglichkeit die ich kenne

**Comment by Iwan1803** [comment]
Das komische ist, das selbst CP nicht korrekt funktioniert hat. Ich habe eine kleine CP-Testteststrecke am Feldrand erstellt, den Ernter eingestellt und er fährt dann dahinter oder nur wild im Kreis.
Ich werde mich mal nach dem Mod umschauen und dann berichten.

**Comment by Michael170978** [comment]
Probiere bitte den hier 
https://farmingsimulator19mods.de/hacksler-zuckerrohr-modpack-v1-1-fs19/

Damit dürftest du keine Probleme mehr haben

**Comment by Iwan1803** [comment]
https://forbidden-mods.de/filebase/file/4849-h%C3%A4cksler-zuckerrohr-pack/
Mit dem Holland klappt es gar nicht. Genau das gleiche wie gestern: der Abfahrer bleibt einfach stehen und nichts passiert.
https://forbidden-mods.de/filebase/file/5784-fs19-big-x-1180-sugarcane-pack/
Daher habe ich es jetzt mit einem BigX (65k L Tank) probiert und der Abfahrer fährt auch hin, aber fährt dem Häcksler dann hinten drauf und bleibt nicht dahinter oder daneben stehen.
Vielleicht ist es nur eine Einstellung, aber ich finde nicht raus, welche.

**Comment by Michael170978** [comment]
Naja ich kann dir sagen warum der Abfahrer dem Häcksler drauf fährt. Ich vermute AD denkt es ist ein Drescher. In Wirklichkeit ist es ein Häcksler mit eingebauten Bunker und somit erkennt AD das Rohr von dem Häcksler nicht.

**Comment by Iwan1803** [comment]
Aber es klappt ja auch mit dem New Holland nicht und wie ich heute bei FED Action sehen konnte, so irgendwie mit keinem Häcksler.
Hast du denn Einstellungen gefunden, wo es funktioniert?

**Comment by Wienet** [comment]
Versuch den mal:
https://www.modhoster.de/mods/holmer-terra-dos-t4-holmer-hr12-fur-zuckerrohr--2
Den fahre ich auch, und der funktioniert.

**Comment by Michael170978** [comment]
Kannst du evtl. ein Screenshot machen wie du Autodrive eingestellt hast?. Ich meine welche Option hast du bei dem Abfahrer genommen und welche Wegpunkte hast du angegeben? Genauso interessiert mich wie du AD und CP beim Häcksler eingestellt hast. Falls es kein Problem für dich ist, würde es mich freuen wenn du die Screenshots hier einfügen würdest.

**Comment by Iwan1803** [comment]
@Michael170978 
Der Abfahrer hat seinen Startpunkt (wie auch der Häcksler) am Feldrand und das Ziel ist das Silo. Für den Häcksler habe ich die gleichen Optionen eingestellt wie für einen normalen Drescher. In AD habe ich es mit früher abfahren ab 0% und Drescher folgen ausprobiert gehabt.
Screenshots kann ich heute abend posten.

**Comment by Michael170978** [comment]
Mich interessieren hauptsächlich die Einstellungen beim Häcksler. Von ihm hängt es ab ob der Abfahrer losfährt oder nicht. Ich denke Mal du hast alles richtig gemacht. Dennoch. Du weißt schon. Vier Augen sind besser als 2 Augen.

**Comment by Iwan1803** [comment]
So, hier die Screenshots.... ich hab die Größe mal ein wenig angepasst.

Beim Krone BigX fahren die Abfahrer hinten drauf:
![fsScreen_2019_11_22_20_52_46](https://user-images.githubusercontent.com/47528836/69457223-e0f4f380-0d6c-11ea-9fd0-f0bb92cf4c3d.jpg)
![fsScreen_2019_11_22_20_52_52](https://user-images.githubusercontent.com/47528836/69457224-e0f4f380-0d6c-11ea-8927-0efacb7f3b0d.jpg)
![fsScreen_2019_11_22_20_53_00](https://user-images.githubusercontent.com/47528836/69457226-e18d8a00-0d6c-11ea-95ac-1797f7f712b3.jpg)

Beim New Holland passiert gar nichts, der Abfahrer zuckt nicht mal:
![fsScreen_2019_11_22_21_09_27](https://user-images.githubusercontent.com/47528836/69457258-f36f2d00-0d6c-11ea-99f6-ac2208c653dd.jpg)
![fsScreen_2019_11_22_21_09_32](https://user-images.githubusercontent.com/47528836/69457259-f407c380-0d6c-11ea-8708-432cbe944b0b.jpg)
![fsScreen_2019_11_22_21_10_35](https://user-images.githubusercontent.com/47528836/69457260-f407c380-0d6c-11ea-8320-58022e542ee3.jpg)

**Comment by Iwan1803** [comment]
Ich habe noch einen funktionierenden Mod gefunden, welcher einen "richtigen" Drescher beinhaltet, aber aufgrund fehlender Anitmationen ein paar Fehler ins Log schreibt, was aber bisher keine negativen Auswirkungen hat:
https://www.modhoster.com/mods/zuckerrohr-ernter-pack

**Comment by Michael170978** [comment]
Das letze Bild mit dem Abfahrer verwirrt mich etwas. Du hast doch nicht etwa bei dem Abfahrer CB und AD gleichzeitig laufen, oder? Weil das wäre falsch

**Comment by Iwan1803** [comment]
Wie kann CP aktiv sein, wenn kein Kurs geladen ist? 😉

**Comment by Michael170978** [comment]
Das ist mir schon klar. Mich wundert, dass die Maske von CP auf war als du Screenshot gemacht hast. Ich würde dir raten bei Zuckerrohrernte auf AD zu verzichten. AD ist ein mächtiges Tool aber CP erledigt das Abernten besser. Zu mal würde ich dir empfehlen im Kreis abzuernten und nicht hoch/runter. Das Ergebnis sieht besser aus und die Fahrzeuge kommen sich nicht in die Quere. Das ist meine Erfahrung, die ich in den letzen 10 Monaten gesammelt hab.

**Comment by Iwan1803** [comment]
Die CP-Maske ist bei mir genauso wie das AD-HUD immer offen, aber immer nur eins von beidem aktiv 😉
Das Abtanken mit AD klappt bei Dreschern bestens. Daher benötige ich CP an der Stelle eigentlich nicht. Das Team von CP möchte aber die Anbindung von AD beim Abtanken wohl noch ergänzen, so das man das dann auch kombinieren kann.
Normalerweise ernte ich immer mit mind. 3 Vorgewenden ab, aber da das nur ein Test war, habe ich erstmal drauf verzichtet.

**Comment by Iwan1803** [comment]
Nachdem ich gestern das Tutorial von Cairo gesehen habe, wollte ich heute mal Mai häckseln.
Ich habe erst den Standard-Claas-Häcksler versucht und da stockt es dann einfach nur, weil der Abfahrer **hinter** den Häcksler fährt statt daneben. Also habe ich den gleichen Classe aber langem Rohr probiert und dann klappt es, aber soll das so sein?
Lustig ist auch, das der Abfahrer nicht stehen bleibt, wenn der Häcksler stoppt - nein, er schiebt ihn dann ganz langsam weiter.
Langsam verzweifle ich....

**Comment by TyKonKet** [comment]
We are closing this issue because of a long time inactivity, If the issue still persists with the latest versions, feel free to open it again.
