### ISSUE TITLE
Include the bags and pallets as supported refill stations

### ISSUE THREAD

**Issue by TyKonKet** [Stephan-S/FS19_AutoDrive#912]
Please I beg you, please include the bags and pallets as supported refill stations

_Originally posted by @evansv2 in https://github.com/Stephan-S/FS19_AutoDrive/issues/758#issuecomment-549062867_

**Comment by evansv2** [comment]
Was this added , or am i getting excited too soon

**Comment by TyKonKet** [comment]
You are getting excited too soon 😄

**Comment by evansv2** [comment]
ok I'll wait as long as I have to, the pallets are needed bad, storeitem.node.fill lol
