### ISSUE TITLE
strange route from start point to shredder, and no path found back to start point

### ISSUE THREAD

**Issue by geo-luchs** [Stephan-S/FS19_AutoDrive#914]
AutoDrive Version: 1.0.6.9-12
Release or custom zip: custom zip
Map (if applicable): All
Vehicle / type (applicable):

**Describe the bug**
I've an unloader, who is unloading a shredder. He was full, driven to silo, and when back to the field (start point) he searched for the path to shredder on the field again.

2 tries, he was not able to reach correctly the shredder, the third time, he got it, but it was luck, I believe.

Please have a look on the screenshots.

on screenshots track_1  - track_3    you can see: there is already a fruit free line on the field, but the driver is driving a path on the street, but not on the field.
Shortly before the shredder, there is a barrier between street and field.
Sometimes he is coming from street, and tries to cross the barrier.
and sometimes he got the right way to shredder, and could follow the shredder

it would be really good, to get a path as a stright line on the fruit free lane on the fuild. There is enough space.

Finally, if he is full, he is driving in the back of the shredder:

Track_5 + Track_6

Debug mode:
Track_7 when unloading shredder
Track_8 when trailer is full, but he is driving into Shredder

Track_9  way back to start point??? Mode is "behind start". 

Track_10: overview: 
   top: shredder position
   bottom: start point
   left: position from Track_9 , where he is trying to exit field.

**Screenshots**
track_1
![track_1](https://user-images.githubusercontent.com/53658780/69369699-cf441b00-0c9c-11ea-945c-585312e54a59.png)
track_2
![track_2](https://user-images.githubusercontent.com/53658780/69369700-cf441b00-0c9c-11ea-8ba1-e4ba95b228b7.png)
Track_3
![track_3](https://user-images.githubusercontent.com/53658780/69369701-cfdcb180-0c9c-11ea-8067-748cb9b74e27.png)

Track_5
![track_5](https://user-images.githubusercontent.com/53658780/69370431-36ae9a80-0c9e-11ea-9075-18612548560d.png)

track_6
![track_6](https://user-images.githubusercontent.com/53658780/69370430-36ae9a80-0c9e-11ea-9dc1-2c730bcf773c.png)

Track 7

![track_7](https://user-images.githubusercontent.com/53658780/69373643-914af500-0ca4-11ea-84d4-25189316a7be.png)

Track 8

![track_8](https://user-images.githubusercontent.com/53658780/69373653-94de7c00-0ca4-11ea-9f4d-1ef6bd7fdecb.png)

Track 9

![Track_9](https://user-images.githubusercontent.com/53658780/69373657-97d96c80-0ca4-11ea-99b3-76fbeb6e63e0.png)

Track_10
![track_10](https://user-images.githubusercontent.com/53658780/69373833-fd2d5d80-0ca4-11ea-920d-74af5a93492a.png)

**Comment by TyKonKet** [comment]
We are closing this issue because of a long time inactivity, If the issue still persists with the latest versions, feel free to open it again.
