### ISSUE TITLE
AutoDrive with courseplay, pressing tab key spawns you under map

### ISSUE THREAD

**Issue by Siryes** [Stephan-S/FS19_AutoDrive#915]
AutoDrive Version: 1.0.
Release or custom zip: Release
Map (if applicable): All
Vehicle / type (applicable):

**Describe the bug**

**If applicable - Steps to reproduce the behavior**

**Screenshots**

**Comment by Iwan1803** [comment]
Describe the bug
If applicable - Steps to reproduce the behavior
Screenshots

**Comment by worker2419** [comment]
@Siryes  is it really Version 1.0? which download did you use? Version 1.0 is too old

**Comment by Siryes** [comment]
Only Two Mods installed Courseplay and Autodrive.
Steps to reproduce:

Load Map, Turn off Switch Trains, Buy Tractor, Reset Tractor , Press Tab Key
You are now under the map.
This will happen on every Map no matter if Modded map or just Default map.

Here is the log file:

[FS19-Spawn.txt](https://github.com/Stephan-S/FS19_AutoDrive/files/3882634/FS19-Spawn.txt)

**Comment by Iwan1803** [comment]
So, don't reset the tractor 😋

**Comment by Siryes** [comment]
After a fresh install and input from Tensuko over at courseplay everything working fine. 

-close
