### ISSUE TITLE
Unload liquid manure, vehicle does not continue driving - Gülle abladen, Fahrzeug fährt nicht weiter

### ISSUE THREAD

**Issue by haamic** [Stephan-S/FS19_AutoDrive#916]
AutoDrive Version: 1.0.6.9-13
Release or selbsterstelltes zip: **selbsterstelltes zip**
Karte (falls relevant): Alle
Fahrzeug(art) (falls relevant): **Güllefass**

**Beschreibe den Bug**
Fahrzeug bleibt nach Leerung am Entladeziel stehen, schaltet auf Grün beim Ladeziel.
Angeblicher Einbau einer absichtlichen Verzögerung der Weiterfahrt kann ich nicht bestätigen.
Nach 20min immer noch keine Reaktion, erst nach Klick auf Weiterfahr-Button.
Entladeziel ist eine GC Düngeproduktion.
https://fs19.net/download-mod/38661

**Falls anwendbar - Schritte mit denen ich den Bug nachstellen kann**

**Screenshots**
![Farming Simulator 19 22 11 2019 05_12_16](https://user-images.githubusercontent.com/28841989/69397669-75b50e00-0ce7-11ea-8a87-35ac31d167b7.png)

**Comment by Iwan1803** [comment]
Gleiche Problem wie hier: https://github.com/Stephan-S/FS19_AutoDrive/issues/900
Flüssigkeiten scheinen irgendwie ein Problem zu sein. Mein Tanker hat z.Bsp. Probleme, Diesel zu laden und dann nach dem Abladen wieder loszufahren.

**Comment by TobiHH78** [comment]
I have the same issue with water for the cows. Only unload once and don`t drive to loading point again.

![1](https://user-images.githubusercontent.com/56259322/69414572-4caa7280-0d13-11ea-8bce-bf54e15c35bd.JPG)

![2](https://user-images.githubusercontent.com/56259322/69414600-57fd9e00-0d13-11ea-9ed7-be0fb5713405.JPG)

**Comment by raxtor** [comment]
@TobiHH78 +1

**Comment by kasp943d** [comment]
![fsScreen_2019_11_22_21_39_43](https://user-images.githubusercontent.com/54898283/69458885-b3aa4480-0d70-11ea-8d71-0f777221fba0.png)
I have the same problem. before the truck will continue, i manually have to press the continue button

**Comment by Roby1164** [comment]
I confirm the problem, today, I had to sell the diesel, taking it from a refinery and bringing it to a distributor, at the first start, it loaded half the load, but then arrived at the distributor, it did not unload automatically, but asked to do it manually, then from that moment he no longer even automatically loads, arrives at the destination point and waits for loading or unloading to start.
