### ISSUE TITLE
LUA Error with newest version

### ISSUE THREAD

**Issue by TobiHH78** [Stephan-S/FS19_AutoDrive#919]
AutoDrive Version: 1.0.6.9
Release or custom zip: custom zip
Map (if applicable): All
Vehicle / type (applicable):

With the newest version I zipped this morning my game always crashes after a few minutes of play. Log is attached.

[log.txt](https://github.com/Stephan-S/FS19_AutoDrive/files/3878984/log.txt)

**Comment by Iwan1803** [comment]
Does this happen on a special action?

**Comment by TobiHH78** [comment]
No, I`m in late summer and started the harvest already. When I start the game and set a few AD drivers shortly after a few minutes the camera make strange things, zoom out, and I can`t switch to a vehicle or do anything else. I can only close the game via the task manager.

I use a CP combine and set two unloading tractors with AD to unload the combine. Also start two vehicles collecting straw with fieldwork course of CP and use AD for unloading at my straw storage.
Set another vehicle to drive from my straw storage to compost factory.

So I have 6 vehicles running with CP / AD same time.

I switched back to a AD version I zipped on 17th in the evening and can finish everything without any problem.
So something whcih was changed between 17th 9 pm and today 8 am is causing the problem I guess.

**Comment by TyKonKet** [comment]
Hey @TobiHH78 the error is given from one of your trailers, are you using some mod trailers?

**Comment by TobiHH78** [comment]
Yes, I`m using mod trailers, but didn`t change anything past few days. Only thing I updated was AD and Courseplay.
With the AD version from 17th, these crashes didn`t occur. I played two hours without problem and do exactly the same things than before with the newest version which cause my problems.

**Comment by TyKonKet** [comment]
Yes yes it's a problem related to the new version, but I need to understand what's the trailer that is causing the error to fix it.

If you have some time to test it, you will see that the problem starts happening when a given trailer is reaching the unload point, if you are able to understand who is it, you can really help me.

**Comment by Roby1164** [comment]
In that log file there are too many errors, in addition to those of AD, which added up can lead to blocking the game.

**Comment by TobiHH78** [comment]
> @TobiHH78 Yes yes it's a problem related to the new version, but I need to understand what's the trailer that is causing the error to fix it.
> 
> If you have some time to test it, you will see that the problem starts happening when a given trailer is reaching the unload point, if you are able to understand who is it, you can really help me.

I will try it later today. Problem is that fieldwork is done for this year, so it can take a while to have same Szenario and reproduce it.

**Comment by Stephan-S** [comment]
I think this bug should be gone with 1.0.7.0 release. If it's still there on your next harvest, please reopen this issue.
Thank you
