### ISSUE TITLE
AutoDrive 1.0.1.6

### ISSUE THREAD

**Issue by CairoAmun** [Stephan-S/FS19_AutoDrive#92]
Hallo Stephan,
Die neue Version 1.0.1.6 funktioniert inzwischen schon sehr gut. Auch der Verkaufsfahrer bleibt jetzt nicht mehr am Silo stehen, sondern verkauft, wenn gewünscht seine Ware zuverlässig. Inzwischen ist aber aufgefallen, zum Beispiel Rotkohl/Weißkohl, Karotten und Zwiebeln nicht mit Autodrive funktionieren. Sowohl der Ropa als auch der Grimme werden vom Abfahrer nicht erkannt. Man kann den Abfahrer auch nicht mit einer zugewiesenen Tastenkombination anfordern. Ich vermute mal, weil diese beiden Fahrzeuge kein Überladerohr haben, sondern ein Förderband zum überladen nutzen. Meinst Du, es gibt eine Möglichkeit, das Du AutoDrive so coden kannst, das diese Dreschertypen auch erkannt werden? 
Dann habe ich gesehen, das die Meldung jetzt unten im Bildschirm angezeigt wird, wenn ein Fahrzeug sein Ziel erreicht hat. Das finde ich eine super Lösung. Frage 1: Gibt es eine Möglichkeit, die Meldung etwas länger anzeigen zu lassen? Frage 2: Kann man es so einrichten, dass diese Meldung klickbar erscheint und man dann direkt in dieses Fahrzeug einsteigen kann?
Ich hoffe, Du hattest ein schönes Osterfest und fühlst Dich jetzt nicht von mit überfallen.
Beste Grüße Cairo

**Comment by Stephan-S** [comment]
Servus Cairo,

das mit dem Grimme und Ropa muss ich mir die Tage mal anschauen. Mit denen bin ich selber eigenlich nie gefahren im 19er. Ich habe es letztens aber mit einem der beiden mal getestet und das hatte funktioniert.
Das Förderband ist spielintern auch eine 'Pipe', daher hat das keine Probleme gemacht.
Aber wie gesagt, ich schau es mir nochmal an.

Soll die Meldung wirklich noch länger auftauchen? Hab es ja schon von 4s auf 10s hochgeschraubt :-)
Vielleicht bau ich das besser mit in die Einstellungen mit ein, dann kann jeder entscheiden ob er es kurz, normal, oder extra lang eingeblendet haben will.

Das wechseln in dieses Fahrzeug finde ich interessant. Ich habe es mal implementiert, allerdings nicht per Mausklick sondern als Tastenkombination. Sprich sobald die Nachricht erscheint, wird dich die Tastenkombination immer zu dem entsprechenden Fahrzeug springen lassen. (Default lasse ich es aber mal unbelegt).

Das hat mich auf die Idee gebracht, eine ganze Liste von aktiven Fahrzeugen anzeigen zu lassen, so dass man viel leichter zwischen den Fahrzeugen wechseln kann ohne dieses völlig aus dem Spiel bringende tabben durch etliche Fahrzeuge.
Dabei bin ich über den wundervollen Mod "Vehicle Explorer" von sperrgebiet gestoßen:
https://github.com/sperrgebiet/FS19_VehicleExplorer
Damit kann man fast genau das umsetzen. Ich lade später mal einen Screenshot hoch, wie ich mir den etwas umgebastelt habe und meinen Wünschen exakt angepasst habe^^

Viele Grüße,
Stephan
