### ISSUE TITLE
Drive to multiple destinations In folder 

### ISSUE THREAD

**Issue by RalfGorden** [Stephan-S/FS19_AutoDrive#920]
hallo mehrere Ziele anfahren in einen Ordner geht bei mir immer noch nicht , auch das andere Abfahrer ihre Ziele ändern  ,obwohl mehrere Ziele anfahren auf nein steht,haben denn noch andere das selbe Problem 
siehe auch den Beitrag #864
1.0.6.9-13

**Comment by Stephan-S** [comment]
Das Verhalten sollte mit dem 1.0.7.0 Release soweit korrekt sein. Nur das Warten an vollen Abladestellen ist noch ein seperater offener Punkt
