### ISSUE TITLE
Seed is no longer filled (condor 15001) - Saatgut wird nicht mehr befüllt (condor 15001)

### ISSUE THREAD

**Issue by haamic** [Stephan-S/FS19_AutoDrive#925]
AutoDrive Version: **1.0.6.9-13**
Release or selbsterstelltes zip: selbsterstelltes zip
Karte (falls relevant): Alle
Fahrzeug(art) (falls relevant): **Saatmaschine Condor 15001 (Düngefunktion in CP abgeschalten)**

**Beschreibe den Bug**
Saatmaschine Condor 15001 wird im AD-Auffüllkurs von CP heraus nicht mehr mit Saatgut befüllt. 
hatte in früheren Versionen von AD problemlos geklappt
händisch mit "R" funktioniert es.
Fahrzeug fährt durch den Trigger ohne zu beladen

**Falls anwendbar - Schritte mit denen ich den Bug nachstellen kann**

**Screenshots**
Falls relevant, bitte Screenshots beifügen

**Comment by RalfGorden** [comment]
ist bei mir genauso , bin wieder zur 1.0.6.8 zurück da geht es

**Comment by geo-luchs** [comment]
AD Version custom zip 1.0.6.9-12
(habs aber auch mit den custom zips von 1.0.6.8 probiert)

Ich steig auch mal wieder ein ins Testen.
Ich teste zwar immer mit einer Saatgüt-Dünge Kombi, aber bei mir rauscht er meistens auch wieder durch.

Leider kann ich beim besten Willen keine Steps to Reproduce liefern.

Was benutze ich:
a) Fendt 1050 + Pronto 9 DC
b) Fastrac 4220 + Tempo L 16


Erst Dünger abholen, danach Saatgut.

AD Setting: Silo bis 100m vorher erkennen.

Modus : Abholen.

Beide fahren die gleiche Strecke. 
In meinem Fall spare ich mir das mit CP, sondern starte direkt AD im abholen Modus.
Erst fahren sie ein Stück auf der Strasse. Biegen dann auf den Hof. Dort wird nochmal bis auf 38 KmH beschleunigt. (Stimmt auch mit dem SpeedOverride Wert überein)

Kurz vor der Düngerbefüllung wird Speedoverride = 5 gesetzt
Allerdings bremsen die Traktoren nicht wirklich auf 5 ab. Damit sind sie zu schnell für die Befüllung.
Außerdem wird auch die Abdeckugn erst sehr kurzfristig vorher geöffnet. In Kombination mit der hohen Geschwinigkeit (>20 KmH) kann beim Dünger befüllen nicht mehr angehalten werden. Selbst beim Saatgut ist er noch ~ 20 KmH schnell, und kann auch dort nicht richtig befüllt werden.

Nun das große Problem: Es gibt durchaus wenige Versuche, wo er es dann doch schafft, mit 5 KmH beim Dünger zu fahren, und befüllt dann auch beide korrekt.

Habe auch immer wieder mal LS neu gestartet. Testspielstand ist immer der Gleiche (ohne Speichern) damit starte ich immer wieder am selben Punkt.

Hab auch schon gedacht, dass er erst x - mal  nicht belädt, und ab da dann immer richtig belädt.
Leider auch nicht.
Mal war es gleich beim 1. Mal wo er beladen hat, beim nächsten Start, ist er 5 mal ohne richtig beladen durchgefahren.

Keine Wiederholbarkeit zu erkennen.

**Comment by geo-luchs** [comment]
wenn im Debug Mode oben links auf dem Bildschirm, speedoverride = 5 angezeigt wird, aber der Traktor trotzdem schneller fährt, übernimmt der Traktor die Vorgabe etwa nicht korrekt?

Mal macht er es, mal nicht.
Hab auch das VehicleControll addon deaktiviert, welches ich benutze. 
LS neu gestartet, und er hat mehrmals beladen.
Beim 3. oder 4. beladen dann aber wieder das fehlerhafte Verhalten. Also kann es nicht wirklich am Vehicle Addon liegen.

**Comment by geo-luchs** [comment]
@haamic ; @RalfGorden  Habt ihr auch das VehicleControl AddOn im Einsatz?
Hab jetzt noch ein paar mal den Spielstand neu gestartet.
Immer mit VehicleControl AddOn tritt der Fehler direkt beim 1. Versuch auf.
Ohne VehicelControlAddon war der 1. Versuch immer erfolgreich.

Der Fokus bei diesem Test lag  auf 1mal Abolen Vorgang starten.

**Comment by geo-luchs** [comment]
Ich glaube, ich kann den Fehler reproduzieren, wenn ich im VehicleControl Addon das Getriebe "IVT" einstelle.

Bzw.: der Fehler tritt anscheinend nicht auf, wenn ich das Getriebe "Off" einstelle.
Andere Getriebe habe ich nicht getestet.

wäre gut zu wissen, ob ihr den Mod ebenfalls benutzt

**Comment by haamic** [comment]
@geo-luchs 
nein dieses addon nutze ich nicht

**Comment by RalfGorden** [comment]
> VehicleControl AddOn

hallo nein ich nutze es auch nicht

**Comment by haamic** [comment]
Problem gelöst, auf meine Art. 
Es hängt mit der Kombination Dünger+Saatgut der Saatmaschine Condor 15001 zusammen!
Gab es nicht in einer früheren Version von AD eine Einstellung in den AD-Setting, wo Dünger ausgeschaltet werden konnte?
Ich habe jetzt an meiner Condor in der **"condor15001.xml"** alles was mit Dünger zu tun hat auskommentiert. Ich nutze diese Funktion nicht.  Das Saatgut wird nun wieder beladen.
**Daher meine Bitte an die Herren Entwickler. Bitte Einstellung für Dünger wieder "einbauen", oder dafür sorgen, das das mit dem Füllen einer **"fertilizingSowingMachine"** richtig funktioniert. Vielen Dank**.
-------------------------------------------------------------------------
Problem solved in my way. 
It has to do with the combination fertilizer + seed of the seed drill Condor 15001!
Wasn't there a setting in the AD setting in a previous version of AD where fertilizer could be switched off?
I have now commented out on my Condor in the **"condor15001.xml "** everything that has to do with fertilizer. I don't use this function.  The seed is now loaded again.
**Therefore my request to the developers. Please "reinstall" the setting for fertilizer, or make sure that it works correctly by filling a **"fertilizingSowingMachine "**. Many thanks**.

Translated with www.DeepL.com/Translator

**Comment by haamic** [comment]
#932

**Comment by Stephan-S** [comment]
@haamic I still can't reproduce this issue. The Condor15001 works flawlessly on my save.  With both seed and fertilizer.
Are you playing Singleplayer or Multiplayer?

What are your settings for 'Maximum trigger distance'?
What kind of refill triggers are you using?

**Comment by haamic** [comment]
@Stephan-S  Das ist schade, das du das nicht reproduzieren konntest. Ich spiele SP und nutze zum Auffüllen einen Mod-Silo (FS19_Placeable_AIO_Fill_Station.zip V1.2 von masterblack), dieser hatte aber sonst auch funktioniert. 

https://modsbase.com/9dxrs8wvxftw/FS19_Placeable_AIO_Fill_Station.zip.html

Habe alle möglichen Triggerabstände probiert, keine Erfolg. Das Fahrzeug macht die Klappe auf,fährt langsam über den Trigger und dann zurück zum Feld ohne aufzufüllen.
Ich kann es mir nicht erklären, aber wie geschrieben, hab ich die Düngefunktion an der Condor lahmgelegt. dann gehts wieder. Wieso ist die Einstellung in AD fürs Dünger laden verschwunden? Hätte es gern mal versucht, dort diese auszuschalten.
-----------------------------------------------------------------
@Stephan-S That's too bad you couldn't reproduce that. I play SP and use a mod silo (FS19_Placeable_AIO_Fill_Station.zip V1.2 from masterblack) to fill it up, but it worked otherwise. 

https://modsbase.com/9dxrs8wvxftw/FS19_Placeable_AIO_Fill_Station.zip.html

Tried all possible trigger distances, no success. The vehicle opens the flap, drives slowly over the trigger and then back to the field without refilling.
I can't explain it to myself, but as written, I paralyzed the fertilizer function on the Condor. then it works again. Why has the setting in AD for loading fertilizer disappeared? It would have liked to have tried to switch it off there.

Translated with www.DeepL.com/Translator

**Comment by TyKonKet** [comment]
**Hello, Thank you for opening this issue!**
Since we have just released [the new refactored version of AutoDrive](https://github.com/Stephan-S/FS19_AutoDrive/releases/tag/1.1.0.0), we can no longer provide any feedback or support for open bug reports related to the old code base.
If the problem persists, please reopen a new issue with all the required details.
Thank you for understanding and we hope you continue enjoying our mod 😄
