### ISSUE TITLE
"Drive-by-overload" not happening anymore

### ISSUE THREAD

**Issue by SledgeHammer75** [Stephan-S/FS19_AutoDrive#928]
AutoDrive Version: 1.0.6.9-14 custom zip
Map (if applicable): All
Vehicle / type (applicable): Combine CR10.90, Truck MAN TGS 18.500 with Krampe KS 950

Combine driven by courseplay, on fieldrow, not headland
AD-settings are precall at 20%, follow combine = yes,

in earlier versions, the truck would follow the combine for a while and then move to overload position, start overloading while combine still driving (the combine stopped for overloading only when full and pipe facing the crop).

this behaviour stopped, truck just follows combine till combine ist full.

**Comment by SledgeHammer75** [comment]
just updated to -17 and tested on a different map with different vehicles, combine driven by standard helper

unloader drives to overload position but fumbles while beside the combine, drives reverse and jackknifes, then starts a new approach with same result

MAN TGS 18.500 with Krampe KS 950 shows same behaviour

**Comment by SledgeHammer75** [comment]
<div style="width: 100%; height: 0px; position: relative; padding-bottom: 62.473%;"><iframe src="https://streamable.com/s/o4ddn/dsryac" frameborder="0" width="100%" height="100%" allowfullscreen style="width: 100%; height: 100%; position: absolute;"></iframe></div>

**Comment by Stephan-S** [comment]
Can you try the 1.0.7.0 release? I made some adjustments to the approaching speed. He was too fast and was overshooting there.
Thank you

**Comment by SledgeHammer75** [comment]
Looks better, but end result still the same. When the unloader is almost under the pipe, he pull to the right almost crashing into the combine. 
https://streamable.com/zvztu

Might be related: when I began testing with 1.0.7.0 I the combine turned lanes (pipe now in crop) and the unloader following the combine made a beeline to a position left the combine (maybe 1 m distance) under the pipe and behind the header.

**Comment by Stephan-S** [comment]
What are your settings for the Pipe Offset in the unload Driver? This is probably where He is heading to when He Turns right

**Comment by SledgeHammer75** [comment]
For some reason the pipe offset was at -4,25m for every vehicle on the Saxonia map. Changed it back to +0,75 and problem seems gone. Odd, didn't touch that savegame for a month. Will test NF Marsch now.

**Comment by SledgeHammer75** [comment]
I can't get it to work on NF Marsch 4x oG, works fine on Saxonia. On Marsch the unloader stupidly follows the combine till the combine is full. Tested combines CRC10.90, 8T and 8Tmodded, and unloaders Truck MAN TGS 18.500 with Krampe KS 950 and Fendt 824 modded with vanilla Krampe trailer. 

Differences I can think of: 
- on Marsch the combine left straw behind, on Saxonia it did not
- AD-Network on Marsch is "from the internet", Saxonia is my own creation

**Comment by SledgeHammer75** [comment]
Works fine on Multimap with downloaded AD-network and combine leaving straw. Can't get it working on NF Marsch 4x oG with own network and even without straw.

**Comment by SledgeHammer75** [comment]
Works fine on regular sized Map NF Marsch 2.3 oG.
config files for comparison
NF Marsch 4x
`<AutoDrive>
    <Version>1.0.7.0-10</Version>
    <Recalculation>false</Recalculation>
    <HudX>0.858854</HudX>
    <HudY>0.269259</HudY>
    <HudShow>true</HudShow>
    <lastSetSpeed>60.000000</lastSetSpeed>
    <exitField>3.000000</exitField>
    <pathFinderTime>6.000000</pathFinderTime>
    <guiScale>1.000000</guiScale>
    <autoConnectEnd>1.000000</autoConnectEnd>
    <useFastestRoute>1.000000</useFastestRoute>
    <parkInField>2.000000</parkInField>
    <enableTrafficDetection>1.000000</enableTrafficDetection>
    <lookAheadBraking>7.000000</lookAheadBraking>
    <shovelWidth>1.000000</shovelWidth>
    <pipeOffset>24.000000</pipeOffset>
    <refillSeedAndFertilizer>2.000000</refillSeedAndFertilizer>
    <useFolders>2.000000</useFolders>
    <trailerOffset>7.000000</trailerOffset>
    <driverWages>3.000000</driverWages>
    <showNextPath>2.000000</showNextPath>
    <unloadFillLevel>10.000000</unloadFillLevel>
    <avoidFruit>2.000000</avoidFruit>
    <autoConnectStart>2.000000</autoConnectStart>
    <recalculationSpeed>7.000000</recalculationSpeed>
    <smoothField>2.000000</smoothField>
    <findDriver>1.000000</findDriver>
    <lineHeight>1.000000</lineHeight>
    <avoidMarkers>2.000000</avoidMarkers>
    <mapMarkerDetour>6.000000</mapMarkerDetour>
    <showHelp>2.000000</showHelp>
    <lookAheadTurning>4.000000</lookAheadTurning>
    <continueOnEmptySilo>2.000000</continueOnEmptySilo>
    <NF_Marsch_4fach_oG_V1_1>
        <waypoints>
snipped
        </waypoints>
        <mapmarker>
snipped
        </mapmarker>
    </NF_Marsch_4fach_oG_V1_1>
    <preCallLevel>3.000000</preCallLevel>
    <chaseCombine>2.000000</chaseCombine>
    <preCallDriver>2.000000</preCallDriver>
    <distributeToFolder>1.000000</distributeToFolder>
    <maxTriggerDistance>2.000000</maxTriggerDistance>
    <restrictToField>2.000000</restrictToField>
    <useBeaconLights>1.000000</useBeaconLights>
    <showTooltips>2.000000</showTooltips>
    <autoRefuel>2.000000</autoRefuel>
    <autoRecalculate>1.000000</autoRecalculate>
    <shovelHeight>26.000000</shovelHeight>
    <experimentalFeatures>
        <smootherDriving enabled="true"/>
    </experimentalFeatures>
    <fuelSaving>2.000000</fuelSaving>
</AutoDrive>
`

on regular size 2.3
`<AutoDrive>
    <Recalculation>false</Recalculation>
    <Version>1.0.7.0-10</Version>
    <HudX>0.869271</HudX>
    <HudY>0.285926</HudY>
    <HudShow>true</HudShow>
    <lastSetSpeed>50.000000</lastSetSpeed>
    <enableTrafficDetection>1.000000</enableTrafficDetection>
    <guiScale>1.000000</guiScale>
    <showTooltips>2.000000</showTooltips>
    <useFastestRoute>1.000000</useFastestRoute>
    <parkInField>2.000000</parkInField>
    <lookAheadBraking>7.000000</lookAheadBraking>
    <avoidMarkers>1.000000</avoidMarkers>
    <refillSeedAndFertilizer>2.000000</refillSeedAndFertilizer>
    <showNextPath>2.000000</showNextPath>
    <unloadFillLevel>10.000000</unloadFillLevel>
    <recalculationSpeed>2.000000</recalculationSpeed>
    <smoothField>2.000000</smoothField>
    <continueOnEmptySilo>1.000000</continueOnEmptySilo>
    <lineHeight>1.000000</lineHeight>
    <showHelp>2.000000</showHelp>
    <shovelWidth>1.000000</shovelWidth>
    <exitField>1.000000</exitField>
    <pathFinderTime>3.000000</pathFinderTime>
    <preCallLevel>7.000000</preCallLevel>
    <autoConnectEnd>1.000000</autoConnectEnd>
    <chaseCombine>1.000000</chaseCombine>
    <restrictToField>2.000000</restrictToField>
    <useBeaconLights>1.000000</useBeaconLights>
    <fuelSaving>2.000000</fuelSaving>
    <avoidFruit>2.000000</avoidFruit>
    <useFolders>1.000000</useFolders>
    <autoRefuel>2.000000</autoRefuel>
    <autoRecalculate>1.000000</autoRecalculate>
    <maxTriggerDistance>2.000000</maxTriggerDistance>
    <autoConnectStart>2.000000</autoConnectStart>
    <distributeToFolder>1.000000</distributeToFolder>
    <lookAheadTurning>4.000000</lookAheadTurning>
    <findDriver>2.000000</findDriver>
    <pipeOffset>24.000000</pipeOffset>
    <preCallDriver>1.000000</preCallDriver>
    <driverWages>3.000000</driverWages>
    <trailerOffset>21.000000</trailerOffset>
    <mapMarkerDetour>1.000000</mapMarkerDetour>
    <shovelHeight>26.000000</shovelHeight>
    <experimentalFeatures>
        <smootherDriving enabled="true"/>
    </experimentalFeatures>
    <NF_Marsch_V2_3_oG>
        <waypoints>
snipped
        </waypoints>
        <mapmarker>
snipped
        </mapmarker>
    </NF_Marsch_V2_3_oG>
</AutoDrive>
`

**Comment by TyKonKet** [comment]
**Hello, Thank you for opening this issue!**
Since we have just released [the new refactored version of AutoDrive](https://github.com/Stephan-S/FS19_AutoDrive/releases/tag/1.1.0.0), we can no longer provide any feedback or support for open bug reports related to the old code base.
If the problem persists, please reopen a new issue with all the required details.
Thank you for understanding and we hope you continue enjoying our mod 😄
