### ISSUE TITLE
FR: Add option to save fuel when waiting for combine

### ISSUE THREAD

**Issue by cristiancundari** [Stephan-S/FS19_AutoDrive#93]
Add a feature to turn off engine when tractor are in parking position waiting for combine; and turn back on only when needed.

Also I think the button "Next unloading point" (which should be the right arrow) and "Previous unloading point" (which should be the left arrow) are flipped.

**Comment by Stephan-S** [comment]
Hey @cristiancundari , 
sorry for getting back to you so late.

The fuel saving option is now on my priority list as long term goal (or medium).

And thanks for noticing the buttons. I fixed it right after your post :-)

Best regards,
Stephan

**Comment by Sim-ian** [comment]
Would also be an idea to shut off engine when vehicle reaches a Drive way point, so engine not left running  if player off doing other stuff.

**Comment by TyKonKet** [comment]
#764
