### ISSUE TITLE
Ingame editor connects random points

### ISSUE THREAD

**Issue by GitTomahawk** [Stephan-S/FS19_AutoDrive#930]
![AD-ingame_editor_issue1](https://user-images.githubusercontent.com/55877391/69483432-bb78f000-0e27-11ea-9e01-020d88135a38.png)
AutoDrive Version: 1.0.6.9-14 MP
Release or selbsterstelltes zip: GIT
Karte (falls relevant): Alle
Fahrzeug(art) (falls relevant):

**Beschreibe den Bug**
Der Ingame Editor verbindet Punkte nicht mehr richtig.
Es werden scheinbar zufällige Punkte in der näheren Umgebung verbunden.
Es entstehen dadurch unsinnige Pfade (siehe Screenshot)

**Comment by GitTomahawk** [comment]
Der Fehler tritt auch in der Release 1.0.6.9 auf

**Comment by Stephan-S** [comment]
Ich kann das Problem nicht nachstellen.
Geht es dir um die automatische Verbindung beim Start/Ende vom Aufzeichnen oder um das manuelle Erstellen?
Beim manuellen Erstellen konnte ich bisher kein Problem feststellen. Er hat stets die Punkte verbunden die mit den beiden orangen und gelben Linien angezeigt waren

**Comment by Stephan-S** [comment]
@TyKonKet Can I pull you into this discussion? Apparently in MP, creating connections between two points is bugged.
Can you already confirm this?

@GitTomahawk Does this happen consistenly. So if you start the game and haven't edited/recorded/deleted anything yet? Or only after you made some changes?

**Comment by TyKonKet** [comment]
@Stephan-S I'll check it in the next days

**Comment by GitTomahawk** [comment]
Es geht um das manuelle Verbinden von Punkten.
Im Screenhot habe ich den Punkt an dem das Fahrzeug steht mit dem Punkt Hof1FS2a verbunden.
Den Screenshot habe ich nach dem Neuberechnen der Routen gemacht (weil ich erst dachte es wäre nur ein Anzeigefehler).
Eventuell hat es etwas mit #949 zu tun -Den Bug habe ich ebenfalls bemerkt als ich versucht habe die fehlerhaftn Verbindungen wieder zu löschen.

**Comment by GitTomahawk** [comment]
I just tried to straighten one track.
But when I tried to connect red and yellow wp it created two connections, connected to one of the deleted wp.
![2019-11-27_connect_wp](https://user-images.githubusercontent.com/55877391/69733296-6beb3a80-112d-11ea-9750-f831eb865cd4.png)
