### ISSUE TITLE
Vehicles lose their track and start driving circles

### ISSUE THREAD

**Issue by GitTomahawk** [Stephan-S/FS19_AutoDrive#931]
AutoDrive Version: 1.0.6.9-14 MP
Release or selbsterstelltes zip: GIT
Karte (falls relevant): Alle
Fahrzeug(art) (falls relevant):

**Beschreibe den Bug**
Die Fahrzeuge kommen auch an fast graden Stellen häufig von der Straße ab.
Wenn sie dabei nicht gegen ein Hindernis fahren, dann beginnen sie im Kreis zu fahren.
Die Kurse fahren sie seit Version 1.0.5.6 unfallfrei.

Im Release 1.0.6.9 tritt der Fehler noch nicht auf.

**Comment by GitTomahawk** [comment]
Der fehler tritt in 1.0.6.9-14 auch auf, wenn ich "AutoDrive.experimentalFeatures.smootherDriving = false" setze

**Comment by TyKonKet** [comment]
@GitTomahawk thanks, that helps a lot.

**Comment by GitTomahawk** [comment]
I tried recalcalc with smootherdriving=true but not after disabling it.
I just downgraded to release and erverithing seems ok.

**Comment by TyKonKet** [comment]
I've tested it on MP, it works fine for me...

**Comment by TyKonKet** [comment]
Hey @GitTomahawk with a9dc33805634c1beffd93b6a2f0b990a7f16c9a0, now you can disable the 'Smoother Driving' feature even in MP, so if you keep having issues you can keep play with the latest version by disabling that feature.

**Comment by Stephan-S** [comment]
@GitTomahawk if you had some time to test the new version, we would sure appreciate some feedback if it was related to the smootherDriving or is still present

**Comment by TyKonKet** [comment]
We have tested 'smootherDriving' on MP with the small JCB (4 wheels steering) and big JCB in many extreme situations:
- very high speed (65 / 73 km/h)
- with heavy cargos
- badly registered routes
- and many others

They never failed, so that's really strange.

**Comment by GitTomahawk** [comment]
I just tested Release 1.0.7.0.
Vehicels still loose their path.
Driver in Screenshot came from top-right and lost path on the straight line from top-left to bottom-left
![2019-11-26 10-LS19](https://user-images.githubusercontent.com/55877391/69619274-a4aae700-103b-11ea-8d80-200283fe8f0c.png)

I also noticed that smaller vehicles seem to drive "schlangenlinien" even on almost straight paths.
I'll downgrade our server to 1.0.6.9 because this makes AD unusable.

**Comment by TyKonKet** [comment]
@GitTomahawk did u tried to disable 'smootherDriving' now that it can be disable even in MP with 1.0.7.0?

**Comment by GitTomahawk** [comment]
Hi, i just tried 1.0.7.0-3 and AutoDrive.experimentalFeatures.smootherDriving = false
Edited some paths in Singleplayer (because of bug #949) and recalculated paths.
It took less than 5 minutes until the next vehicle got stuck on straight path.
![2019-11-26 offtrack](https://user-images.githubusercontent.com/55877391/69641473-8e635200-1060-11ea-80ff-88e41d5e9b21.png)

**Comment by GitTomahawk** [comment]
It's about 1 crash per 10min

**Comment by TyKonKet** [comment]
Ok, that helps a lot, now I know that is not a problem related to smootherDriving

**Comment by TyKonKet** [comment]
Does it happens when you are looking at the vehicle or when u are not?

**Comment by GitTomahawk** [comment]
The issue started with commit ce1228f3662c8feabedb0fb7cb89c5215fabb3a6 1.0.6.9-11
1.0.6.9-10 does not cause this issue.
Usually it happens while I'm doing something else but once i saw it "live" the vehicle suddently started to steer left-right-left right.. and then crashed into a tree.

**Comment by TyKonKet** [comment]
ok, thanks, another detail that helps a lot

**Comment by GitTomahawk** [comment]
I just noticed that it seems not to be disabled at all if i just change the paramteer in Autodrive.lua.
If i save the game it looks as it is aktive in savegame:
    <experimentalFeatures>
        <smootherDriving enabled="true"/>
    </experimentalFeatures>

**Comment by TyKonKet** [comment]
That's because when the game loads, it will overwrite the value in AutoDrive.lua with the one saved in the settings, so, if you want you can just try to open the commands console after you enter the game and you should be able to see the loaded state of the feature (at least if you are on MP).

**Comment by TyKonKet** [comment]
Hey @GitTomahawk does this issue happen on random points of the routes or does it happen always on the same points?

**Comment by TyKonKet** [comment]
With 4a7227573fe865f8769aa0a0bcf64054f620a040 I've changed 'smootherDriving' when you have time, please take it a test and let me know, if you can please test it both MP and SP.

**Comment by GitTomahawk** [comment]
Disabling it in .lua AND in Savegame fixed the issue.

**Comment by TyKonKet** [comment]
@GitTomahawk let me know 😄

**Comment by GitTomahawk** [comment]
Do I need to manually set it to enable it in savegame before server starts to test your fix?

**Comment by TyKonKet** [comment]
Nono, now it is enabled and can't be disabled.

**Comment by GitTomahawk** [comment]
I've been testing 1.0.7.0-9 since 35 min now and no vehicle crashed into scenery but something is decreasing MP performance. Even if im currently the only one connected to our server I notice a lot of lags (that usually start when 3 players are connected using a lot of helpers.
Server CPU is at 40-45% (2cores each at 20-25% oter cores are idle)

**Comment by Murtlock** [comment]
Hi TyKonKet,i tested your fix in single with smoother driving on and of and my vehicle are still crashing and swerving right to left from the routes

**Comment by GitTomahawk** [comment]
I'm runing 1.0.7.0-10 since 50mins - 1st vehicle just lost track and crashed in tree.

**Comment by TyKonKet** [comment]
@GitTomahawk Let me know

**Comment by BigHatte** [comment]
I have the same Issue. Most Time if the vehicle drives a curve. After that the vehicle drives left right left right and so on until the radius is to big. Than the vehicle starts driving in cycle. I'm using latest release. Some times it happens on straight way.

**Comment by TyKonKet** [comment]
**Hello, Thank you for opening this issue!**
Since we have just released [the new refactored version of AutoDrive](https://github.com/Stephan-S/FS19_AutoDrive/releases/tag/1.1.0.0), we can no longer provide any feedback or support for open bug reports related to the old code base.
If the problem persists, please reopen a new issue with all the required details.
Thank you for understanding and we hope you continue enjoying our mod 😄
