### ISSUE TITLE
fertilizingSowingMachine possible troubleshooting- Combined sowingmachine is not filled with seed (fertilizer function not used)

### ISSUE THREAD

**Issue by haamic** [Stephan-S/FS19_AutoDrive#932]
AutoDrive Version: 1.0.6.9-14
Release or custom zip: C-zip
Map (if applicable): All
Vehicle / type (applicable): 
**fertilizingSowingMachine- in my example Condor15001 (fertilizer function switched off in CP)**

**Describe the bug**
in my example Condor 15001 sowingmachine is no longer filled with seed during the AD filling course from CP.
had worked without any problems in earlier versions of AD.
manually with "R" it works.
The vehicle drives through the trigger without loading seeds.

**If applicable - Steps to reproduce the behavior**

**Resolution!**
Problem solved in my way.
It has to do with the combination fertilizer + seed of the seed drill Condor 15001!
Wasn't there a setting in the AD setting in a previous version of AD where fertilizer could be switched off?
I have now commented out on my Condor in the "condor15001.xml " everything that has to do with fertilizer. I don't use this function. The seed is now loaded again.
Therefore my request to the developers. Please "reinstall" the setting for fertilizer, or make sure that it works correctly by filling a "fertilizingSowingMachine ". Many thanks.

Translated with www.DeepL.com/Translator

**Comment by haamic** [comment]
#925

**Comment by Stephan-S** [comment]
Are you using "Pickup % Deliver" or "Load" mode?
In Load mode I can not reproduce the issue

**Comment by haamic** [comment]
Load Mode to refill Seeds from CP
----------------
CP startet den Laden-Kurs wenn Saat leer ist.   Das ging ja alles schon mal in früheren Versionen nur jetzt halt nicht mehr .  Warum ist die Dünger Einstellung in den AD Einstellungen  wieder verschwunden?

**Comment by Rumspringa90** [comment]
Ich hatte gestern da gleiche Problem mit einer anderen Saatmaschine mit Düngefunktion. Er fährt zum Silo, macht die Klappe auf und fährt ohne aufzufüllen zurück zum Feld.

**Comment by Stephan-S** [comment]
Hallo, da wir gerade die neue restrukturierte Version von AutoDrive released haben, können wir leider keine Bugs und Issues die sich noch auf die alte Codebasis beziehen mehr bearbeiten.
Wenn das Problem bzw. dein Anliegen in der atkuellen Version weiterhin besteht, mache doch bitte ein neues Issue mit allen benötigten Informationen auf.
Oder melde dich bei kleineren Themen und Fragen auch gerne direkt im Discord:
https://discord.gg/sUQtKhB

Vielen Dank für dein Verständniss und ich hoffe du hast weiterhin Spaß am AutoDrive Mod :-)

Und hier noch ein Link zur aktuellen Version:
https://github.com/Stephan-S/FS19_AutoDrive/releases/tag/1.1.0.0
