### ISSUE TITLE
Mode and destination changes automatically on start

### ISSUE THREAD

**Issue by Martinnygaard** [Stephan-S/FS19_AutoDrive#933]
AutoDrive Version: 1.0.6.9-12
Release or custom zip: Custom
Map (if applicable): All
Vehicle / type (applicable): All

**Describe the bug**
This bug has started happenning recently.
Sometimes (not alltimes) when I start a route (Unload combine mode) is instantly changes to drive mode and set destination to the very first destination in the default folder.

**If applicable - Steps to reproduce the behavior**
I have not figured out the pattern yet - but often first time i start a tractor. (But not limited to first time)

**Screenshots**
I setup this:
![AD start 1](https://user-images.githubusercontent.com/26490587/69493317-b8c0de00-0ead-11ea-9575-18529acee4d3.png)

When i press start, it changes to this:
![AD start 2](https://user-images.githubusercontent.com/26490587/69493318-ba8aa180-0ead-11ea-9274-5e7d15d0e69f.png)

Which is the only destination in my Default folder:
![image](https://user-images.githubusercontent.com/26490587/69493346-253bdd00-0eae-11ea-9597-b84e698bfbd3.png)

**Comment by Woife1** [comment]
Do you have checked the fueltank from the vehicle?
your naming says AD drives to this destination to refuel a vehicle

**Comment by Martinnygaard** [comment]
That could make sense - i would have a look for that next time it happens.

**Comment by Woife1** [comment]
do you have the whole Screenshot? there you could take look to the fuel

the easiest way to reproduce it is empty a fueltank of a vehicle and set it on a course

**Comment by Martinnygaard** [comment]
Unfortunatly not - but i will look reproduce soon. :-)
Will it do this during a route too?
Let's say a driver is unloading a combine for three hours and then gets low on fuel. Will it pause the job to go refill then?

As i wrote on Discord, that did not happen for the tractor that ran out of fuel this morning (while AD drove)

**Comment by Woife1** [comment]
i think AD check the fuel every time he starts a job or switches between the destinations (pick up & deliver, combine mode...) when exactly AD checks the fueltank could Stephan say

I saw AD a couple of times refueling while he drives of a combine

**Comment by TyKonKet** [comment]
Yes, if you have auto refueling enabled and the fuel tank is below 15% he will first go to refuel and then resume the previous job.

**Comment by Martinnygaard** [comment]
Hi again,

Most likely, this is just the case. I did not pay attention on the fuel level.
I will reopen, if i discover it was not the case.
