### ISSUE TITLE
MP: Probleme mit dem AutoDrive /  Problems with the AutoDrive

### ISSUE THREAD

**Issue by Engelchen1989** [Stephan-S/FS19_AutoDrive#935]
AutoDrive Version: 1.0.6.7
Release or selbsterstelltes zip: Release
Karte (falls relevant): NF Marsch

Guten Tag,
wir haben auf unserem Srever ein Problem, ich habe fast die hälfte der Karte schon an AD angebunden aber wenn wir jetzt auf den Server gehen und er die "Kurse lädt" sind bei uns
1. das AD Fester weg
2. die Anzeige von LS selber die man über F1 an und ausschalten kann
3. auch die ganzen anderen Fenster.
4. das neue AD geht bei uns garnicht erst

Nun Frage ich euch mal woran kann das liegen? 
Würde mich über eine antwort freuen

**Comment by Iwan1803** [comment]
Please try the latest version.

**Comment by Engelchen1989** [comment]
Mit dem AD 1.0.6.9 habe ich das Problem das sich beim Verbinden meine ganzen Bahnen die ich schon eingefahren habe kaput machen und woanders hin gehen.

**Comment by Iwan1803** [comment]
Versuch mal die aktuellste Version:
![image](https://user-images.githubusercontent.com/47528836/69499308-e9763700-0ef0-11ea-8811-e73a638ddfdd.png)

**Comment by Engelchen1989** [comment]
Das habe ich

**Comment by Stephan-S** [comment]
Passiert das Problem beim Verbinden nur im MP?

**Comment by Engelchen1989** [comment]
ja leider und nun haben wir auch das problem das der AD uns nicht mehr zu unseren abladepunken schickt genau so das er die strecken nicht mehr so fähr wie sie eingefahren worden sind

**Comment by Engelchen1989** [comment]
Unsere Abfahrer fahren auch nicht neben den Drescher sondern den Dreschern hinten rein oder aber Kilometer weit weg. was kann ich da machen?

**Comment by TyKonKet** [comment]
We are closing this issue because of a long time inactivity, If the issue still persists with the latest versions, feel free to open it again.
