### ISSUE TITLE
MP: Vanishing hud/options W/ Gypsum, Limestone, CCarbonate & others.

### ISSUE THREAD

**Issue by jcmbennett** [Stephan-S/FS19_AutoDrive#938]
AutoDrive Version: 1.0.6.9
Release or custom zip: Release
Map (if applicable): PV Industries
Vehicle / type (applicable): Any

**Describe the bug**
When trying to use any load/unload several of the PV filltypes like gypsum, limestone, calcium carbonate and others as soon as I select the fill type in the drop down menu of AD the help window, driving hud and fill type option disappear. If I click in the area where the option for fill type is and select a regular item like lime or coal it all comes back. 

So currently I cant use AD to fill any of these additional fill types. I don't know if this is an AD issue or an issues with the added fill types for the PV map.

**If applicable - Steps to reproduce the behavior**

**Screenshots**

**Comment by Iwan1803** [comment]
Please try latest beta release.

**Comment by jcmbennett** [comment]
Sorry but where do I find the beta releases?

**Comment by jcmbennett** [comment]
Never mind, I see I just have to download the raw files and zip them.

**Comment by Iwan1803** [comment]
![image](https://user-images.githubusercontent.com/47528836/69499312-f4c96280-0ef0-11ea-9b83-53fa6f2ab9e4.png)

**Comment by jcmbennett** [comment]
After updating to the latest beta 1.0.6.9-17 the results are the same as seen in the screenshots.

![image](https://user-images.githubusercontent.com/25438829/69500125-40f2b380-0ead-11ea-880b-8c84062bf1fa.png)

**Comment by jcmbennett** [comment]
![New Bitmap Image](https://user-images.githubusercontent.com/25438829/69500206-fa518900-0ead-11ea-81c5-f5244f6e0f3f.jpg)

**Comment by jcmbennett** [comment]
Let me also add that this is on a multiplayer dedicated server.

**Comment by Mannie313** [comment]
@Iwan1803 

Can you do anything with this mistake? It's exactly the same problem as with me.

Error: Running LUA method 'draw'.
C:/Users/Manni/Documents/My Games/FarmingSimulator2019/mods/FS19_AutoDrive/scripts/HudElements/PullDownList.lua:488: attempt to index a nil value

MFG Mannie313

**Comment by Mannie313** [comment]
@Stephan-S  leider ein neuer fehler aufgetreten.

Error: Running LUA method 'draw'.
C:/Users/Manni/Documents/My Games/FarmingSimulator2019/mods/FS19_AutoDrive/scripts/HudElements/PullDownList.lua:486: attempt to index a nil value

MFG Mannie313

**Comment by Mannie313** [comment]
@TyKonKet bei dieser version: 
Merge Pull Request # 948 von DeckerMMIV / AdHud

kommt dieser fehler:

Error: Running LUA method 'draw'.
C:/Users/Manni/Documents/My Games/FarmingSimulator2019/mods/FS19_AutoDrive/scripts/HudElements/PullDownList.lua:499: attempt to index a nil value

auszug aus der PullDownList.lua

self.text = g_fillTypeManager:getFillTypeByIndex(vehicle.ad.unloadFillTypeIndex).title

MFG Mannie313

**Comment by Mannie313** [comment]
@Stephan-S bei mir funktioniert dieses jetzt.

MFG Mannie313

**Comment by jcmbennett** [comment]
I have tested out these changes and so far it is working great! No more vanishing hud and the pickup and delivery works for those filltypes now. Thank you very much!
