### ISSUE TITLE
Abholen und Abladen klappt nicht MP

### ISSUE THREAD

**Issue by Drummer30876** [Stephan-S/FS19_AutoDrive#939]
AutoDrive Version: 1.0.7.0
Release or selbsterstelltes zip: Release
Karte (falls relevant): NF Marsch 4fach mit Gräben 1.1
Fahrzeug(art) (falls relevant):

**Beschreibe den Bug**
Der Modus Abholen und Abladen klappt nicht wirklich. Das Fahrzeug fährt zwar zu den Punkten,
aber weder die Befüllung noch das automatische Abladen klappt. 
Die Punkte sind richtig gesetzt. Das Icon "überladen starten" leuchtet auf.
Mit mehreren Fahrzeugen und Anhängern probiert, auch mit mehreren Fruchtsorten. Will nicht klappen.
Spiele auf einen Dedi Server im Miltiplayer

**Falls anwendbar - Schritte mit denen ich den Bug nachstellen kann**

**Screenshots**
Falls relevant, bitte Screenshots beifügen

**Comment by Stephan-S** [comment]
Duplicate of #899
