### ISSUE TITLE
Use Courseplay field edge to circle field to exit

### ISSUE THREAD

**Issue by sootysax** [Stephan-S/FS19_AutoDrive#941]
Is it possible to adopt the courseplay field edge so that AD doesn't make a beeline for the nearest AD course, but uses the courseplay edge to circumnavigate the field until it gets to where the field exit is?

**Comment by Stephan-S** [comment]
You can select the field exit strategy for each vehicle.
By choosing the default ('Back to start') or 'Behind start' options, you tell them to return to their start location which should result in the desired behaviour.

You probably have selected 'Closest', which is what you are getting right now :-)

I hope that solves your issue. If so, please close it afterwards. Thank you

**Comment by SledgeHammer75** [comment]
I noticed that on somewhere downloaded AD-networks for NF Marsch and Multimap. The original creator did a blue "catch" circle-line around each field and connected this at a few points to the rest of the network, thereby creating field exits that feel real (e.g. bridges, gravel roads, etc).

Instead of creating this catch-course for each field individually, it would be great to automate that.

**Comment by Stephan-S** [comment]
If you field destination is on your exit location (bridge, gravel road etc.) AutoDrive will try to reach this point and if this point is also located on the field, he will try to plan a path that completely remains on the field.
What is missing right now is a clever way of getting the closest point on the field if your destination is outside of it to use this as an intermediate target

**Comment by SledgeHammer75** [comment]
When you set the field exit location to a choke point, things tend to get messy when you use more than one unloader ...

Take a look at this network in the editor: 
http://www.modhub.us/farming-simulator-2019-mods/autodrive-route-network-nf-march-4-way-with-trenches-v1-1/

**Comment by Anonymous-any** [comment]
lol Guys you are lazy to create routes ?
![1](https://user-images.githubusercontent.com/25174503/69582541-1ef64f80-0fd9-11ea-9b9b-515640e4eadc.png)

**Comment by Mr-Cake** [comment]
Using behind/back to start doesn't work if a second unloader is waiting at the start.
