### ISSUE TITLE
Hud Issue

### ISSUE THREAD

**Issue by Mr-Cake** [Stephan-S/FS19_AutoDrive#942]
AutoDrive Version: 1.0.
Release or custom zip: 1.0.67
Map (if applicable): All
Vehicle / type (applicable):

When using the mouse to select locations if you choose the one that fall on top of the title bar it will not select. Menu disappears but location stays the same.

Might already be fixed

**Comment by Iwan1803** [comment]
Please use a newer version as that was fixed.
