### ISSUE TITLE
Driver moves too fast through the BGA / Unload Process

### ISSUE THREAD

**Issue by Trigger87** [Stephan-S/FS19_AutoDrive#946]
I use autodrive with a tractor with trailer. 

It is moving from the field to the BGA. Yesterday (Release 1.0.6.9) the unload process was ok, but the driver was constantly too slow after unloading the trailer into the BGA.

Today **(Release 1.0.7.0)** the driver moves much too fast through the BGA while unloading the trailer and the half of the trailer is outside of the BGA. Is there a hotfix?.

Have a nice day.

**Comment by Brandjuh** [comment]
It's not only the BGA, its also the route, they drive like they are drunk.

**Comment by TyKonKet** [comment]
@Trigger87 @Brandjuh Is that still an issue?

**Comment by TyKonKet** [comment]
We are closing this issue because of a long time inactivity, If the issue still persists with the latest versions, feel free to open it again.
