### ISSUE TITLE
AD transfers in the refilling course after loading directly back to CP without going back to the field - AD übergibt im Auffüllkurs nach beladen direkt wieder an CP ohne zum Feld zurück zu fahren

### ISSUE THREAD

**Issue by haamic** [Stephan-S/FS19_AutoDrive#947]
AutoDrive Version: 1.0.7.0-1
Release or selbsterstelltes zip: selbst-zip
Karte (falls relevant): Alle
Fahrzeug(art) (falls relevant):

**Beschreibe den Bug**
AD übergibt im Auffüllkurs (abholen Modus) nach beladen direkt wieder an CP ohne zum Feld zurück zu fahren
keine AD-Fehler im Log zu sehen. Anbei Log von CP mit debug 14, wenn helfen sollte.
[log2.txt](https://github.com/Stephan-S/FS19_AutoDrive/files/3888729/log2.txt)

siehe auch:
https://github.com/Courseplay/courseplay/issues/4605

**Falls anwendbar - Schritte mit denen ich den Bug nachstellen kann**

**Screenshots**
Falls relevant, bitte Screenshots beifügen

**Comment by Iwan1803** [comment]
Das gleiche Probleme habe ich mit Ladewagen, welche Stroh auf dem Feld per CP laden und per AD am Heizkraftwerk abladen sollen.
AD scheint sich ab und zu (nicht immer) nach dem Abladen abzuschalten, dann wird CP wieder aktiv und das Gespann landet im Zaun oder sonstwo.

**Comment by geo-luchs** [comment]
Das würde meinen Heuladewagen auf Abwegen nach dem Entladen "erklären". Der ist nach dem Abladen immer vom AD Kurs weg und wollte ab durch die Sträucher/Bäume/Gebäude

**Comment by RudiBergfeld** [comment]
ich habe die neuen Fixes runtergeladen aber das Problem ist noch da
[log.txt](https://github.com/Stephan-S/FS19_AutoDrive/files/3892537/log.txt)

**Comment by haamic** [comment]
mit 1.0.7.0-5 scheint es wieder zu gehen. 
keine vorzeitige Übergabe an CP nach Befüllen festzustellen, Fahrt zum Feld wird wieder fortgesetzt.
Danke
