### ISSUE TITLE
Deleted Waypoints return after recalculation. Dedicated Server

### ISSUE THREAD

**Issue by c0p3y** [Stephan-S/FS19_AutoDrive#949]
AutoDrive Version: 1.0.7.0 and 1.0.6.9
Release or custom zip: Release
Map (if applicable): All
Vehicle / type (applicable): All
MP Dedicated server
#903 is same issue but was closed without explanation.

**Describe the bug**
When deleting wayponts on MP Dedicated server the waypoints visually disappear from route but return after a recalculate is initiated.
Tested on several maps including stock maps with and without other mods. Works fine in single player.

**Screenshots**
**Before deleting waypoints**
![DeleteWaypointBug_BeforeEdit](https://user-images.githubusercontent.com/13108537/69595880-60c9ca80-0fc6-11ea-86c1-b5312ffaf61c.png)
**After deleting waypoints before recalculating**
![DeleteWaypointBug_AfterEdit](https://user-images.githubusercontent.com/13108537/69595914-77702180-0fc6-11ea-9223-49acef78a988.png)
**After recalculating**
![DeleteWaypointBug_AfterRecalculate](https://user-images.githubusercontent.com/13108537/69595930-86ef6a80-0fc6-11ea-84d6-e2e45bcfd02a.png)

**Comment by GitTomahawk** [comment]
Deleted waypoints still re-appear after path calculation

**Comment by c0p3y** [comment]
Tested, confirmed fixed on dedi MP 1.0.7.0-10.
