### ISSUE TITLE
Course Editor not working 

### ISSUE THREAD

**Issue by ploughedfieldman123** [Stephan-S/FS19_AutoDrive#95]
its now not working on version 1.0.1.7

<a href="https://ibb.co/SPv5BZ7"><img src="https://i.ibb.co/c1TkQsX/Error-AD-Editor.jpg" alt="Error-AD-Editor" border="0"></a>

image dont load anymore, and it is a .png file

**Comment by Roby1164** [comment]
resize the window, or zoom in or out, you'll see that it appears ...

**Comment by ploughedfieldman123** [comment]
> resize the window, or zoom in or out, you'll see that it appears ...

wow you a genius as its working again now lol. 

anyway another problem  trailer is 100%  full it leaves combine heads to parking stop field 5 even though its 100% full.  waits until combine is 100% and still goes to stand beside combine with a full trailer weird or what 

<a href="https://ibb.co/k249H44"><img src="https://i.ibb.co/d4PLWPP/AD-Unload-C.jpg" alt="AD-Unload-C" border="0"></a>

**Comment by haamic** [comment]
Hallo, ich habe auch das problem, das ich nur einen schmalen streifen der Karte sehe. 
Ein Vergrössern des Fensters bringt keinen Erfolg. Java ist aktuell.
hat jemand eine Lösung?
Gruss Michael

translate deepl....

Hello, I also have the problem that I only see a narrow stripe of the map. 
Enlarging the window does not bring success. Java is up to date.
does anyone have a solution?
Greetings Michael

![editor-error](https://user-images.githubusercontent.com/28841989/56750190-83230d80-6783-11e9-8857-4b9d93cdf15e.jpg)

**Comment by ploughedfieldman123** [comment]
> Hallo, ich habe auch das problem, das ich nur einen schmalen streifen der Karte sehe.
> Ein Vergrössern des Fensters bringt keinen Erfolg. Java ist aktuell.
> hat jemand eine Lösung?
> Gruss Michael
> 
> translate deepl....
> 
> Hello, I also have the problem that I only see a narrow stripe of the map.
> Enlarging the window does not bring success. Java is up to date.
> does anyone have a solution?
> Greetings Michael
> 
> ![editor-error](https://user-images.githubusercontent.com/28841989/56750190-83230d80-6783-11e9-8857-4b9d93cdf15e.jpg)

do what I was told above try zooming in or out with middle mouse wheel its working for me ok now

**Comment by haamic** [comment]
nein, das habe ich schon versucht.
nichts funktioniert. zoom, resize, mausrad, alle maustasten.
der Editor zeigt mir nur den Streifen der Karte.
--------------------------------------------------------------------
No, I've already tried that.
nothing works. zoom, resize, mouse wheel, all mouse buttons.
the editor only shows me the stripe of the map.

**Comment by ploughedfieldman123** [comment]
> ## nein, das habe ich schon versucht.
> nichts funktioniert. zoom, resize, mausrad, alle maustasten.
> der Editor zeigt mir nur den Streifen der Karte.
> No, I've already tried that.
> nothing works. zoom, resize, mouse wheel, all mouse buttons.
> the editor only shows me the stripe of the map.

try downloading it all again  

https://github.com/Stephan-S/FS19_AutoDrive

**Comment by haamic** [comment]
auch das habe ich bereits probiert.kein erfolg.
ich geb es auf....wenn man ordentlich im spiel arbeitet, braucht man ja keinen editor  ;-)
------------------------
i've already tried that, too. no success.
i give it up....if i work properly in the game, i don't need an editor...   ;-)

**Comment by ploughedfieldman123** [comment]
> resize the window, or zoom in or out, you'll see that it appears ...

Dam now my editor isn't working again now. as It did. I have resized it zoomed in and out but nothing

**Comment by Stephan-S** [comment]
Hey guys, sorry I haven't reacted before.
Can you send me the config.xml files which are not working?
The editor works with my config files, so I can't really say what the problem is without trying to load one of your config files.

I only encountered one problem, where I had a special char in one of my marker names.
Thanks for your help :-)

**Comment by haamic** [comment]
Hey Stephan. Es hat mit dem Config file nichts zu tun. Der Editor lädt ja schon die  map nicht. Nur so ein kleinen Streifen sehe ich, wie auf den Bildern zu sehen. 
Auch deine png im src Ordner funktionieren genauso wenig. 
Gruß Micha

**Comment by Stephan-S** [comment]
Hey, die map alleine laden hat auch keinen Zweck im Editor.
Die Vorgehensweise sollte folgende sein: 
1.) Load config -> wenn eine png dazu im src Ordner liegt, lädt er sie automatisch und wenn nicht, dann kannst du über
2.) "Load map" auch die png dazu laden.
Die Anzeige aktualisiert sich erst wenn eine entsprechende config Datei geladen wurde.
Hast du das probiert?


So in english:
It is of no use, if you only click on "Load map". You also have to click on "Load Config" first and open a valid config.xml file. Otherwise the editor won't work and won't update the editor window which results in you only seeing part of the map.
So only use the editor with an existing config file and not to start from scratch.
Does that resolve your issues?

**Comment by ploughedfieldman123** [comment]
hi Stephan 

I do load config 1st then load map. it's been working ok.  I can't send you my config file yet as not on pc. but I will tomorrow.

**Comment by haamic** [comment]
> Die Vorgehensweise sollte folgende sein:
1.) Load config -> wenn eine png dazu im src Ordner liegt, lädt er sie automatisch und wenn nicht, dann kannst du über
2.) "Load map" auch die png dazu laden.
----------------------------------
Hallo Stephan,
die Reihenfolge hab ich so abgearbeitet.
Und nun hatte ich Erfolg.
Ich hatte zum Test sonst immer die XML geladen, und war wahrscheinlich zu ungeduldig. ich erhielt keine Anzeige. Habe bemerkt, der Load Config-Button hat während des Ladens nur den Blauen Rand, nach dem Laden zusätzlich wieder den Grauen/Schwarzen Rand. 

![config button](https://user-images.githubusercontent.com/28841989/56845542-35adba00-68c3-11e9-81a7-1996b1109b1b.jpg)

Dies dauert bei mir schon mal ca. 15s.
danch kann ich meine PNG laden und bekomme zwar immer noch den schmalen Streifen angezeigt, aber mit zoomen bzw. Fenster vergrössern seh ich das Streckennetz und die Karte.
Warum die Karte nicht automatisch lädt weiss ich nicht, diese liegt auch im src/mapImages Ordner, wie die anderen mitgelieferten. 
Lösche ich dort alle PNG und benenne meine Config in....AutoDrive_Felsbrunn_config.xml, lädt er trotzdem die Felsbrunn.PNG, obwohl ja keine PNG mehr im Auto Drive Editor-Ordner da ist.
Merkwürdig....
Gruss Micha

**Comment by Stephan-S** [comment]
Hey, gut das es ja doch alles klappt :-)
Die Usability könnte ich sicher noch etwas verbessern, indem ich vor allem deutlich mache wenn das Programm aktiv ist und gerade die Kurspunkte einlädt.

Zu den Map pngs: Die Dateien im src Ordner sind die Quelldateien, sprich der unkompilierte Programmcode. 
Was du öffnest, ist die AD.jar, also die kompilierte Version. Dort sind die Bilder bereits fest enthalten. Er schaut also nicht wirklich in den mapImages Ordern rein, sondern hat diesen quasi integriert in der .jar File mit drin. Daher musst du sie immer manuell laden.

Was du gerne machen kannst, ist entweder, insofern du dich mit Github etwas auskennst, ein Pull Request mit deiner Map png machen. Dann kompilier ich das Ganze nochmal und deine Map ist enthalten.
Oder du sagst mir welche map du nutzt bzw. schickst mir die png, dann mache ich das auch :-)

**Comment by ploughedfieldman123** [comment]
> Hey, gut das es ja doch alles klappt :-)
> Die Usability könnte ich sicher noch etwas verbessern, indem ich vor allem deutlich mache wenn das Programm aktiv ist und gerade die Kurspunkte einlädt.
> 
> Zu den Map pngs: Die Dateien im src Ordner sind die Quelldateien, sprich der unkompilierte Programmcode.
> Was du öffnest, ist die AD.jar, also die kompilierte Version. Dort sind die Bilder bereits fest enthalten. Er schaut also nicht wirklich in den mapImages Ordern rein, sondern hat diesen quasi integriert in der .jar File mit drin. Daher musst du sie immer manuell laden.
> 
> Was du gerne machen kannst, ist entweder, insofern du dich mit Github etwas auskennst, ein Pull Request mit deiner Map png machen. Dann kompilier ich das Ganze nochmal und deine Map ist enthalten.
> Oder du sagst mir welche map du nutzt bzw. schickst mir die png, dann mache ich das auch :-)

Hi Stephan did you get my config file as mine isnt working

**Comment by Stephan-S** [comment]
Hey, I did not get a config file. where did you send it?
You can just copy it over here for example: https://pastebin.com/

**Comment by ploughedfieldman123** [comment]
> Hey, I did not get a config file. where did you send it?
> You can just copy it over here for example: https://pastebin.com/

I sent it here  did you not see the link I posted above        http://www.filedropper.com/autodrivemarwellmanorfarmconfig

**Comment by ploughedfieldman123** [comment]
I have just signed up to pastebin but what do you click on to send you the paste

**Comment by Stephan-S** [comment]
Hey, sorry I missed your post with the config file earlier.
There was a bug in the editor. You added some waypoint in the game without recalculating and this causes some issues in the editor. I fixed it and also included some more map images in the new release.
Thank you for your help.

**Comment by ploughedfieldman123** [comment]
Stephan  where is the updated cfg file
