### ISSUE TITLE
Duplicate names and an error on deletion

### ISSUE THREAD

**Issue by Mannie313** [Stephan-S/FS19_AutoDrive#950]
AutoDrive Version: 1.0.
Release or selbsterstelltes zip: selbsterstelltes 
Karte (falls relevant): Alle
Fahrzeug(art) (falls relevant):

**Beschreibe den Bug**
Eine klare Beschreibung des Bugs.
Doppelte Namen obwohl bloß einmal eingegeben worden ist. und Beim löschen bekomme ich diesen Error

Warning (script): 'removeXMLProperty': Argument 1 has wrong type. Expected: Int. Actual: Nil 
..\..\..\src\base\scripting\lua\LuaScriptSystem.cpp (882): expectedType == Value::VoidType || expectedType == Value::ClassType
LUA call stack:
=C:/Users/Manni/Documents/My Games/FarmingSimulator2019/mods/FS19_AutoDrive/scripts/AutoDriveGraphHandling.lua (238) : removeXMLProperty
=C:/Users/Manni/Documents/My Games/FarmingSimulator2019/mods/FS19_AutoDrive/scripts/Events/AutoDriveDeleteMapMarkerEvent.lua (37) : removeMapMarker
=C:/Users/Manni/Documents/My Games/FarmingSimulator2019/mods/FS19_AutoDrive/scripts/Events/AutoDriveDeleteMapMarkerEvent.lua (24) : run
dataS/scripts/network/Client.lua (432) : readStream
dataS/scripts/network/ConnectionManager.lua (28) : func
dataS2/character/humans/player/player02.i3d (554.74 ms)
**Falls anwendbar - Schritte mit denen ich den Bug nachstellen kann**

**Screenshots**
Falls relevant, bitte Screenshots beifügen
![fsScreen_2019_11_26_18_15_09](https://user-images.githubusercontent.com/3021040/69656690-47358b00-1079-11ea-9a1a-83a9a2d7b1e8.png)

[log.txt](https://github.com/Stephan-S/FS19_AutoDrive/files/3893161/log.txt)

MFG Mannie313

**Comment by jcmbennett** [comment]
I just started getting this same issue as of 1.0.6.7, at least that was when I noticed the duplicate and sometimes triple entries. 

Map PV Industries
Multiplayer
Current AD vr. 1.0.7.0

**Comment by TyKonKet** [comment]
I noticed a similar bug some days ago, I was on SP

**Comment by jcmbennett** [comment]
Also when trying to delete one duplicate it actually deletes a previous destination, not one of the duplicates.
