### ISSUE TITLE
Pink button when creating ways

### ISSUE THREAD

**Issue by gigilal** [Stephan-S/FS19_AutoDrive#953]
So I believe this button can make a car/tractor go into reverce mode? Or am I wrong? Ive tested it but I do not find out how to use it.

![image](https://user-images.githubusercontent.com/47475839/69680878-9812a700-10ac-11ea-9ea6-bd167fef4b7e.png)

**Comment by Iwan1803** [comment]
This will create a route, which can be driven on from both sides.
