### ISSUE TITLE
Combi mode overloading

### ISSUE THREAD

**Issue by Mr-Cake** [Stephan-S/FS19_AutoDrive#954]
AutoDrive Version: 1.0.6.9+
Release or custom zip: Release/Github
Map (if applicable): All
Vehicle / type (applicable): Auger Wagons

1.0.6.9/1.0.7.0 and lastest commits seems to have broken auger wagon overloading in combi mode. I use a auger wagon to unload harvesters and then overload that to a truck. AD no longer stops when it starts overloading to the truck it just plows right through. It also does not give enough time for the auger arm to extend which causes it to drive right past the truck. 

Secondary bug related to auger wagons, if you stop the unloading process and retract arm and send it back to start to test again on the next attempt AD will sit there waiting for the arm to extend I think. Some variable not set properly if AD doesn't retract the arm itself.

Steps
Send a full auger wagon to offload in combi mode.

**Comment by stro1rob** [comment]
I have been doing the same thing. When recording the course place a "Pause" where you want the tractor to stop and unload. Then set the wait time to  the amount of time it takes to unload the cart. This has worked somewhat for me. However I am now getting an error in my log about something to do with foliage when I start the course.  I have not used the debugging channels before and I will try that to see what else the mod can tell me.

**Comment by Mr-Cake** [comment]
Is that with courseplay? I haven't really tried using cp to unload yet. Generating all the courses is a drag.

**Comment by stro1rob** [comment]
Yes this is courseplay. Apparently AutoDrive is different?

**Comment by raxtor** [comment]
yes, its different. I can confirm overloading is broken in latest versions.. Auger vageon just missing truck trailer (in my case 2 bins Wilson trailer).

**Comment by Tensuko** [comment]
> Generating all the courses is a drag.

Overloading is the most simply course you would have to create :)
Start on Field, drive to trailer (waitpoint) and back on the Field :)
Just not working yet for CP :/
But you can ofc use both CP+AD and we want to continue the combination, that CP Driver can switch over to AD and back :)

**Comment by Mr-Cake** [comment]
This is the commit that broke it.

https://github.com/Stephan-S/FS19_AutoDrive/commit/e73071f24e537b1d40a497b34f6e9f5d085ee41b

**Comment by Skigy** [comment]
I have the same issue on the versions 1.0.7.0 and 1.0.7.0-33. Auger wagons do not stop at the point they should be unloading, they just bypass the trailer.

**Comment by TyKonKet** [comment]
**Hello, Thank you for opening this issue!**
Since we have just released [the new refactored version of AutoDrive](https://github.com/Stephan-S/FS19_AutoDrive/releases/tag/1.1.0.0), we can no longer provide any feedback or support for open bug reports related to the old code base.
If the problem persists, please reopen a new issue with all the required details.
Thank you for understanding and we hope you continue enjoying our mod 😄
