### ISSUE TITLE
Filling seeds and fertilizer

### ISSUE THREAD

**Issue by RudiBergfeld** [Stephan-S/FS19_AutoDrive#955]
Frage ist es möglich mit Ad Saatgut und Dünger Auffüllen oder ist nur 1 möglich

**Comment by CairoAmun** [comment]
Hallo Rudi, zu diesem Thema habe ich gestern ein Video veröffentlicht.
Du kannst mit AD beides auffüllen.
https://youtu.be/xVhFVJIhHCw

**Comment by Zottel33** [comment]
Das Video ist sehr hilfreich bezüglich des Ladens von Dünger und Saatgut.
Ich habe das ganze mal nachgestellt und es funktioniert auch.

Allerdings nur unter der Bedingung das ich die "Amazone Condor" verwende.
Mit einer anderen Sämaschine z.B. "Salvis 3800" oder "Ceres Master 3570" hat es leider nicht funktioniert.

Ich vermute das Problem liegt darin das die "Amazone Condor" nur eine "Klappe" für Dünger und Saatgut hat.
Die anderen beiden Sämaschienen haben je eine "Klappe" für Saatgut und eine "Klappe" für Dünger.
Ich konnte beobachten das Autodrive immer nur die "Klappe" für den Dünger öffnet. 
Selbst wenn Autodrive den Saatgut Trigger anfährt. 

Kann das jemand bestätigen?

**Comment by TyKonKet** [comment]
Duplicate of #932
