### ISSUE TITLE
Error: Unsupported mod description version in mod FS19_AutoDrive

### ISSUE THREAD

**Issue by Marty-DD** [Stephan-S/FS19_AutoDrive#956]
HI,

since I updated AD and Courseplay to the newest Version - I get this error in my log and AD is not been loaded.
[log.txt](https://github.com/Stephan-S/FS19_AutoDrive/files/3898661/log.txt)

Version CP: v6.01.00342
Version AD: 1.0.7.0

Load mod: FS19_AutoDrive (Version: 1.0.7.0) (Hash: 669bbf95f9da5c93a432d724c4398301)
Error: Unsupported mod description version in mod FS19_AutoDrive

**Comment by TyKonKet** [comment]
Update the game pls.

**Comment by Marty-DD** [comment]
Thanks for your help. I have the steam version and thought it will be updated automatically.  But that isn't so.
I don't know how to update, it seems that Steam doesn't find an update. I did that:

Rechtsklick auf das Spiel in der Bibliothek –> Eigenschaften auswählen –> Im neuen Fenster den Reiter Lokale Dateien anklicken –> Button Dateien auf Fehler überprüfen anklicken.

Sorry, I can'T translate...

**Comment by TyKonKet** [comment]
What's the version of the game? you can see it from the first screen on the game:
![image](https://user-images.githubusercontent.com/7534621/69765554-ac21db80-1174-11ea-86f1-ecd389abbcba.png)

**Comment by Marty-DD** [comment]
Hey,

i've 1.4.1.0 b5334.

Unfortunately, I can not force Steam to update that game. I've deleted the game.xml, as well as the contents of the "shaders" (?) Folder. I also checked the local files and gave LS19 the highest update priority.

**Comment by Roby1164** [comment]
On Steam, you have to go to the game's properties, then Beta, and put No Beta, as you can see in the picture
![Screenshot_2](https://user-images.githubusercontent.com/24955554/69805804-c2b24c00-11e1-11ea-9c34-361b54299aeb.jpg)

**Comment by Roby1164** [comment]
In this way it reloads the game to the latest official version, you now have a Beta version, the b5334 of 1.4.1.0

**Comment by Marty-DD** [comment]
AH, thanks. I will test it in later. Ich think I have choosen the patch/beta
