### ISSUE TITLE
MP: Pickup but No Delivery 1.0.7.0

### ISSUE THREAD

**Issue by jcmbennett** [Stephan-S/FS19_AutoDrive#958]
AutoDrive Version: 1.0.7.0-4 and up
Release or custom zip: custom zip 
Map (if applicable): PV Industries (MP Dedi)
Vehicle / type (applicable): All

**Describe the bug**
I had the duplicate destination and deletion issue which was fixed with the 1.0.7.0-4 but then all vehicles when doing a pickup and delivery or delivery no longer trigger at the drop off. They all pickup just fine but only slow down at the drop off and then continue on. Tested the save in single player and works fine. 

**If applicable - Steps to reproduce the behavior**

**Screenshots**

**Comment by jcmbennett** [comment]
Also to add, this function was working most of the time prior to the duplicate fix.

**Comment by jcmbennett** [comment]
After testing I found that the issue was only with destinations on routes created recently. I was able to create new destinations on older routes created in 1.0.6.8 and earlier. Seems that the config got corrupted beyond some point. So in single player I loaded up a config from a 1.0.6.8 save and downgraded the mod to same version and recreated the routes that were corrupted. Then upgraded the mod to current 1.0.7.0-10 and everything started working again, mostly.

This is where my question regarding limitations comes in. While I was testing I had over a dozen drivers doing continuous pickup and delivery jobs. All of the drivers would completed their circuit but not without random issues. Sometimes the drivers would finish the job when at the delivery point even with infinite repeat selected. Also at times they wouldn't trigger the drop off or pickup and instead just sit at the destination as if blocked. Turning the AD off then on again and they would continue as normal.

So the mod seems to be working in calculating routes and actions but the random issues makes me wonder about limitations. All of the issues are as if the driver has lost its connection with the AD and it usually only effects 1 or 2 drivers at a time while the rest continue to operate normal. This leads me to think the problem is either a limitation of the mod or the server hardware.

Question 1: Is there a limit to how big I can make an AD network? 30,000 nodes, 40,000 node, etc
Question 2: How many AD operations can I have going at one time in MP?
Question 3: Is the AD accuracy dependent on the speed of the server hardware itself? For example, having a better server would make AD run smoother without as many issues.

**Comment by TyKonKet** [comment]
I'm not sure about your questions, so I think is better to wait an answer from @Stephan-S 

At the moment I can confirm that we have many small issues in MP.
As you noticed some times during 'Pickup and Deliver' vehicles get stuck without any apparent reason and so on, I'm doing some tests and I will write an accurate report and when @Stephan-S will be back we will talk about that.
