### ISSUE TITLE
Abfahrer does not drive off

### ISSUE THREAD

**Issue by RalfGorden** [Stephan-S/FS19_AutoDrive#962]
AutoDrive Version: 1.0.7.0-10
Release or selbsterstelltes zip: Release
Karte (falls relevant): Alle
Fahrzeug(art) (falls relevant):

**Beschreibe den Bug**
hallo meine Abfahrer fahren nach beladen oder entladen nicht los, obwohl das Ziel auf grün steht

**Falls anwendbar - Schritte mit denen ich den Bug nachstellen kann**

**Screenshots**
![fsScreen_2019_11_28_14_26_50](https://user-images.githubusercontent.com/56214377/69812975-90a8e600-11f1-11ea-9219-eb6106dccd33.png)

**Comment by Roby1164** [comment]
Logical. are you telling him to unload the combine ......
![Screenshot_2](https://user-images.githubusercontent.com/24955554/69820920-90fdad00-1202-11ea-9d6a-19da328a8929.jpg)

**Comment by RalfGorden** [comment]
er wurde ja von einen Radlader beladen , da stellt man das doch so ein oder nicht
![fsScreen_2019_11_28_14_24_07](https://user-images.githubusercontent.com/56214377/69826611-38371000-1214-11ea-813d-00d9ccc8a1f0.png)

**Comment by Woife1** [comment]
normalerweise bekommt der Abfahrer den Modus Abholen und Anliefern

**Comment by RalfGorden** [comment]
hallo vielen Dank , in diesen Falle lag es an der Einstellung , damit kann ich den Betrag schliesen
