### ISSUE TITLE
Beladen Anhänger,, Loaded trailer

### ISSUE THREAD

**Issue by Despopanda** [Stephan-S/FS19_AutoDrive#963]
Hallo zusammen,

Gibt es eine Möglichkeit, wenn man 2 Anhänger am Trecker dran hat, auf jeweils 1 Anhänger verschiedene Sachen zu Laden?, und wenn nicht könnte man das eventuell irgendwie mit einbauen.

LG

Hello everybody,

Is there a way, if you have two trailers on the turn of it, on each trailer different things to shop ?, and if not you could possibly somehow incorporate.

LG

**Comment by Woife1** [comment]
this is not possible with AutoDrive in the mode pick up & deliver
you can manualy load the 2 trailer with different things and send it with AD with the unload mode

**Comment by Despopanda** [comment]
Danke !!!  Thank you
