### ISSUE TITLE
No lines visible in MP

### ISSUE THREAD

**Issue by Mannie313** [Stephan-S/FS19_AutoDrive#964]
AutoDrive Version: 1.0.7.0-10
Release or selbsterstelltes zip: selbsterstelltes
Karte (falls relevant): Alle
Fahrzeug(art) (falls relevant):

**Beschreibe den Bug** Keine linien im MP sichtbar

Eine klare Beschreibung des Bugs.

**Falls anwendbar - Schritte mit denen ich den Bug nachstellen kann**

**Screenshots**
Falls relevant, bitte Screenshots beifügen
![fsScreen_2019_11_29_11_48_28](https://user-images.githubusercontent.com/3021040/69863911-30bc4900-129e-11ea-9778-1a3792b952ef.png)

Wie bekomme ich die wieder sichtbar. ist so blöd ne strecke einzufahren ohne das man was sieht.

MFG Mannie313

**Comment by Woife1** [comment]
da das nach einem sehr örtlichem Problem aussieht im zusammenspiel mit anderen Mods
empfehle ich die erstmal viel mit der Kamera zu spielen 
klappt bei mir zumindest

kann aber auch irgendeine falsche coli in der Map sein

**Comment by Bigdaddy-KP** [comment]
Hatte das gleiche Problem mit der gleichen Version, nach einer Neuberechnung war bei mit auf dem Server wieder alles da

**Comment by Mannie313** [comment]
ja das weiß ich. aber beim einfahren ist es blöd keine linien zu sehen. 

MFG Mannie313
