### ISSUE TITLE
Question- Folders? How to keep bigger equipment from using certain linework?

### ISSUE THREAD

**Issue by dozerjz** [Stephan-S/FS19_AutoDrive#966]
Hello, 
I have been searching online to see what you are supposed to do with the Folders option in the GUI menu.  I also want to know if there is a way to keep larger equipment off of certain line work?  Would you just split the line work and keep different closed circuits?  Looking for any input.  You guys are doing one hell of a job on this, keep up the great work.

**Comment by Woife1** [comment]
If you set folders on, you could create folders in the destination drop off and sort your destinations in them (you could name the folders how you like)
If i understand the 2. question right
such a feature is not planed in the near future
use your brain while you create your courses  😎 😜

**Comment by dozerjz** [comment]
Roger that, I thought I was missing something. For Question #2, I am going to make a "closed" Circuit for the little stuff i want to run around the farm with.  Thanks again for all the great work you guys are doing!
