### ISSUE TITLE
Drivers bumping into each other at waiting point

### ISSUE THREAD

**Issue by JanCraymer** [Stephan-S/FS19_AutoDrive#967]
AutoDrive Version: 1.0.7.0-10
Release or custom zip: custom zip
Map (if applicable): All
Vehicle / type (applicable): Trucks (did not test other vehicles)

**Describe the bug**
Since one of the recent updates drivers bump into each other when reaching the waiting point.
As you can see in the video (link below) the first truck already arrived and is waiting to be loaded when the second truck arrives and bumps into the first trucks trailer.

It is possible that it startet with the changes for smoother driving but I'm not sure.

**If applicable - Steps to reproduce the behavior**
Start at least two drivers and let them wait at the same point.

**Video**
https://youtu.be/_7t4YkQ0l_w

**Comment by TyKonKet** [comment]
Let me know please 😄

**Comment by JanCraymer** [comment]
Just testet with 1.0.7.0-21 and it looks fine now, thanks! :)
