### ISSUE TITLE
Problem with Folder/Courses move

### ISSUE THREAD

**Issue by zockparadies** [Stephan-S/FS19_AutoDrive#968]
AutoDrive Version: 1.0.7.0
Release or selbsterstelltes zip: Release
Karte (falls relevant): Alle
Fahrzeug(art) (falls relevant):

**Beschreibe den Bug**
Ich habe die "Ordner verwenden" Funktion eingestellt und kann die Kurse nicht in die Ordner verschieben. Das einzige was bis jetzt geht ist dass ich in der xml unter Groups umstelle. Würde es dennoch gern ingame machen.
Gibt es dazu eine Lösung?

**Screenshots**
![farmingsimulator2019game exe Screenshot 2019 11 30 - 22 46 00 57](https://user-images.githubusercontent.com/23559232/69906422-6018a600-13c3-11ea-97ab-425b5783b288.png)

**Comment by Mannie313** [comment]
den kurs auswählen und dann bei dem jeweiligen ordner auf das dreieck wo nach rechts zeigt klicken.

MFG Mannie313

**Comment by Highlander1965** [comment]
https://m.youtube.com/watch?v=0Y2_fBy2g7M
