### ISSUE TITLE
Problem with liquid loading / unloading.

### ISSUE THREAD

**Issue by Roby1164** [Stephan-S/FS19_AutoDrive#969]
There is a problem with all the liquids, I have tried with various versions, from 1.0.6.8 to the last, and all have that problem, no type of liquid is loaded or discharged, from water to fertilizers or fuel, the vehicle stops and awaits manual command. No error in the log file, no kind of error in the game, just does not execute the command.
I'm trying to find the latest version where everything worked, since I'm sure it worked, but I don't remember which one.

**Comment by TyKonKet** [comment]
f69722411e53f54a4b81e29ffdeec62c8e7423eb
