### ISSUE TITLE
Auto Drive funktioniert bei der Porta Westfalica nicht

### ISSUE THREAD

**Issue by marihe70** [Stephan-S/FS19_AutoDrive#97]
Hallo, 

wenn ich bei der Map Porta Westfalica Kurse einfahre, funktioniert alles. Nach dem Speichern und beenden des Spieles lässt es ssich nicht wieder öffnen. Erst wenn Autodrive deaktiviert ist startet das Spiel wieder. Im Discord der Porta habe ich mal die Log hochgeladen. Da wurde ein Fehler ausfindig gemacht, welchen ich hier mal weitergebn wollte.

Error:Running LUA method 'loadMapFinished'"  und "C:/Users/mario/Desktop/Spielstände LWS 19/Papa/ST 19 Test/FS19_AutoDrive/scripts/AutoDriveXML.lua:153: attempt to index local 'markerIDString' (a nil value)"

Gruß marihe70

**Comment by Stephan-S** [comment]
Servus,
Den Fehler habe ich eigentlich schon vor einer Weile behoben. Mit welcher Version hast du es denn probiert?

**Comment by marihe70** [comment]
Guten Morgen,
Ich kenne mich hier auf der Seite leider nicht aus. Da ich den Mod von Modhub habe, war ich der Meinung dass dieser aktuell ist. Dort ist noch die Version 1.0.0.0 vorhanden. Nachdem ich hier her geschrieben habe, habe ich die neue Version gefunden und geladen. Damit funktioniert es jetzt. Ich danke für die prompte Reaktion und vor allem für den wirklich coolen Mod. Spitze. Ich kann so was leider nicht. Leider konnte ich dies nicht früher mitteilen.

**Comment by Stephan-S** [comment]
Super, freut mich das wir das Problem schnell lösen könnten.
Der Update Prozess auf Modhub ist leider etwas langwieriger. Aber es ist bereits eine neue Version eingereicht, die hoffentlich in den nächsten Wochen auch live gehen wird.

Freut mich, dass der Mod dir gefällt :-)
