### ISSUE TITLE
GUI buttons shortcuts not working

### ISSUE THREAD

**Issue by ws1967** [Stephan-S/FS19_AutoDrive#970]
Kann es sein, dass seit der Version 1.0.7.0 die Return-Taste nicht mehr funktioniert? Beim Umbenennen von Fahrzeugen bzw. Bestätigen von Zielpunkten wird die Return-Taste bei mir neuerdings vollkommen ignoriert - ich muss immer auf "Bestätigen" klicken. Im übrigen Spiel funktioniert die Return-Taste einwandfrei.

**Comment by haamic** [comment]
Das ging in AD bei mir noch nie. Muss auch immer auf bestätigen drücken.

**Comment by TyKonKet** [comment]
So they never worked?
