### ISSUE TITLE
AutoDrive.lua:304: attempt to index field 'cp' (a nil value)

### ISSUE THREAD

**Issue by Mannie313** [Stephan-S/FS19_AutoDrive#972]
AutoDrive Version: 1.0.7.0.12
Release or selbsterstelltes zip: Release
Karte (falls relevant): Alle
Fahrzeug(art) (falls relevant):

**Beschreibe den Bug**
Eine klare Beschreibung des Bugs.
Beim starten mit der neuen version kommt dieser fehler und schreibt die log voll. ist kein dediserver. es ist ein selbstgehostetes server spiel. So teste ich die mods.

Error: Running LUA method 'update'.
2019-12-01 15:03 C:/Users/Manni/Documents/My Games/FarmingSimulator2019/mods/FS19_AutoDrive/scripts/AutoDrive.lua:304: attempt to index field 'cp' (a nil value)

[log.txt](https://github.com/Stephan-S/FS19_AutoDrive/files/3908284/log.txt)

**Falls anwendbar - Schritte mit denen ich den Bug nachstellen kann**

**Screenshots**
Falls relevant, bitte Screenshots beifügen

MFG Mannie313

**Comment by Mannie313** [comment]
Mir ist aufgefallen das der obengenannte Fehler auftritt wen man sich ein fahrzeug  kauft oder eins besitzt.

MFG Mannie313

**Comment by Woife1** [comment]
du kannst auf die schnelle mal die Zeile 304 in der lua mit "--" auskommentieren und testen ob es so erstmal funktioniert

**Comment by Mannie313** [comment]
Ja hat geklappt es waren zeile 303 und 304. Aber ist keine Dauerlösung. Ich spiel auch Singlepayer und da dann jedesmal umschreiben ist auch nicht so toll.

**Comment by Woife1** [comment]
Das ist mir schon klar das es so keine gute Lösung ist 
wäre ja auch nur für Teste ob die Änderungen funktionieren 

in den früheren Versionen klappt es ohne CP?
