### ISSUE TITLE
Coloured dots/nodes for editor

### ISSUE THREAD

**Issue by wickedset** [Stephan-S/FS19_AutoDrive#973]
A problem I find with the editor, is tracing the route on a 3 or 4 way 2 lane road junction, you very often get dots bunched together, making it difficult to trace, I often have to move the nodes  to find the route. I also find the length of the arrows doesn't help in these situations.

**Describe the solution you'd like**
Could a manual colour feature be added, by manual I mean, click a menu button and the click the node to colour it, for no other reason but to highlight these nodes for just ease of vision, then maybe a cancel menu button to get rid of all the colour, returning them to the blue. Don't need many colours, 3 or 4 is plenty. 
Thanks

**Comment by Axel32019** [comment]
see Release Version 1.1.0.7
