### ISSUE TITLE
Problem with loading of liquids

### ISSUE THREAD

**Issue by Mannie313** [Stephan-S/FS19_AutoDrive#975]
AutoDrive Version: 1.0.7.0-15
Release or selbsterstelltes zip: Release
Karte (falls relevant): Alle
Fahrzeug(art) (falls relevant):

**Beschreibe den Bug**
Eine klare Beschreibung des Bugs.

**Falls anwendbar - Schritte mit denen ich den Bug nachstellen kann**
Es ist ein originalsilo wo ich alles lagern kann.
**Screenshots**
Falls relevant, bitte Screenshots beifügen
https://www.youtube.com/watch?v=qDMFcL8yi1E

**Comment by Woife1** [comment]
Dieses Video ist privat

**Comment by Mannie313** [comment]
> Dieses Video ist privat

probier es nochmal. Und danke für den Hinweiß

**Comment by TyKonKet** [comment]
So @Mannie313 the issue is with loading of liquids?

**Comment by Mannie313** [comment]
Yes sorry

**Comment by TyKonKet** [comment]
@Mannie313 no problem thanks for clarification 👍

**Comment by Mannie313** [comment]
- 👍

**Comment by ratze68** [comment]
Hallo
Version 1.06.09 geht es. Nur mal als info

**Comment by Mannie313** [comment]
@TyKonKet 

Ich weiß hat zwar nicht ganz hiermit was zu tun aber beim beladen fängt er doch ganz am anfang vom trailer normal an und nicht in der mitte. und wie auf dem Video zu sehen ist fährt er bei 80 prozent drescherabfahren einstellung los.

https://youtu.be/HuYHcCOAS2Y

MFG Mannie313

**Comment by TyKonKet** [comment]
@Mannie313 You are on SP right?

**Comment by Mannie313** [comment]
Dediserver. Sorry

MFG Mannie313

**Comment by TyKonKet** [comment]
Ok, in SP I tried it some days ago and it was working, I'll test it also on MP as soon as I can.

**Comment by Mannie313** [comment]
ok

**Comment by Mannie313** [comment]
@TyKonKet I can help you somehow to test on a Dediserver. who yes let me know.

MFG Mannie313

**Comment by Mannie313** [comment]
Kann es sein das Autodrive bei den Flüssigkeits und Normaler Transport irgendwie versucht eine Route zu berechnen. den sobald der Abfahrer voll ist und zu dem Punkt fährt hab ich nur noch 20 FPS entlasse ich den AD fahrer hab ich wieder über 60 FPS.

MFG Mannie313

**Comment by TyKonKet** [comment]
**Hello, Thank you for opening this issue!**
Since we have just released [the new refactored version of AutoDrive](https://github.com/Stephan-S/FS19_AutoDrive/releases/tag/1.1.0.0), we can no longer provide any feedback or support for open bug reports related to the old code base.
If the problem persists, please reopen a new issue with all the required details.
Thank you for understanding and we hope you continue enjoying our mod 😄
