### ISSUE TITLE
"Enter" doesn't work

### ISSUE THREAD

**Issue by haamic** [Stephan-S/FS19_AutoDrive#983]
AutoDrive Version: 1.0.7.0.-25
Release or selbsterstelltes zip: self-zip
Karte (falls relevant): Alle
Fahrzeug(art) (falls relevant):

**Beschreibe den Bug**
Hallo, 
es können keine Zielnamen mehr gespeichert werden. Der Eingabedialog bleibt offen und nichts passiert. Der Name wird nicht an den entsprechenden Wegpunkt geschrieben/gespeichert.
Beim überfahren des "Erstellen"-Button mit der Maus wird diese nicht mehr gelb, wie bei "zurück".
Daher bestimmt auch keine Funktion.
Ebenso funktioniert die Enter/Return Taste immer noch nicht. Das konnte beim Anlegen/ändern des Fahrer Name getestet werden, man muss immer auf Okay klicken, ist das so gewollt?
Falls deswegen kürzlich etwas geändert wurde, wodurch es nun nicht mehr geht, wäre es schön, wenn dies vorher mal getestet wird, bevor ein Update der AD Dateien hochgeladen wird. Es ist mühselig hinterher wieder eine alte funktionierende Version zu finden. Ich hoffe auf schnelle Behebung des Problems. Danke.
Gruss Micha

**Falls anwendbar - Schritte mit denen ich den Bug nachstellen kann**

**Screenshots**
Falls relevant, bitte Screenshots beifügen
------------------------------------------------------------------------------------------------------
AutoDrive Version: 1.0.7.0.-25
Release or self-created zip: self-zip
Map (if relevant): All
Vehicle (type) (if relevant):

**Describe the bug**
Hello, 
no more target names can be saved. The input dialog remains open and nothing happens. The name is not written/stored to the corresponding waypoint. When you move the mouse over the "Create" button, it no longer turns yellow, as with "Back".
Therefore no function is defined.
Also the Enter/Return key still does not work. This could be tested when creating/changing the driver name, you always have to click on Okay, is that what you want?
If something has been changed recently, which makes it impossible, it would be nice if this is tested before an update of the AD files is uploaded. It's hard to find an old working version afterwards. I hope for a quick fix. Thank you.
Greetings Micha

**Comment by haamic** [comment]
ich habe noch die ältere version 1.0.7.0.-13, da ist es genau andersherum, Ziel speichern geht, Fahrer name geht nicht, wird aber gelb. 
----------------------------------------------------------------------------------------------------------------
i still have the older version 1.0.7.0.-13, there it is exactly the other way around, save target goes, driver name doesn't work, but turns yellow.

**Comment by RalfGorden** [comment]
ich habe die 1.0.7.0-10 da geht beides noch

**Comment by TyKonKet** [comment]
@haamic do you have any error in the logs?

**Comment by haamic** [comment]
na bitte, geht doch. in version 1.0.7.0-27 funktioniert beides wieder. 
Aber "Enter" funktioniert nicht. Drücke ich "enter", passsiert nichts, drücke ich "return" verschwindet der Textcursor, aber Eingabedialog bleibt offen.
--------------------------------------------------------------------------------------------
well please, it works. in version 1.0.7.0-27 both works again. 
But "Enter" doesn't work.  If I press "enter", nothing fits, if I press "return", the text cursor disappears, but the input dialog remains open.

**Comment by TyKonKet** [comment]
When you the text field is selected, you have first to "remove the focus" from it, you have three option to do that:
1) You can click outside the text field
2) You can press 'enter'
3) You can press 'esc'
Now that the field is unfocused, you can use keyboard shortcuts (esc, enter, space, return) to perform actions.
That's the way GIANTS have made GUI, I can't do nothing about that.

**Comment by haamic** [comment]
Was ist bei CP anders? Da funktioniert das doch beim Kurs abspeichern ganz normal mit Return. Sind die Eingabedialoge so unterschiedlich?
---------------------------------
What is different about CP? So it works normally when saving a course with Return. Are the input dialogs so different?

**Comment by TyKonKet** [comment]
@haamic in the course saving dialog of CP, the save action is called
 even if you just click out from the text input element (you can test it yourself), I could even do the same , but I don't think that that's the right way a dialog should work.
This would easily bring to not wanted input (e.g. if you click out of the text field for an error) and in any case it wouldn't work on dialogs where you have more than one action (e.g. 'rename', 'reset' and 'delete')
Let me know your opinion about that.

**Comment by haamic** [comment]
In my opinion, it is a habit to get a result as the completion of an input. And not to confirm it again. If you make mistakes during the input, you can correct these again. But if it is so wanted, it should just remain so.

**Comment by TyKonKet** [comment]
@haamic yes, that makes sense, but we still have to consider the technical problem, if I would enable this function, you will never be able to press 'reset' and 'delete' buttons, since with this 'function' enabled, every time you click out of the text field is equivalent to press the confirm button.

**Comment by TyKonKet** [comment]
Maybe I'll find some solution sooner or later, in that case I'll let you know

**Comment by TyKonKet** [comment]
Oh sorry, I forgot to say that for the moment you can just perform the following:
1) Write the text
2) Unfocus the text field, you can do it by pressing 'enter' or pressing 'esc' or clicking out of text field
3) Press the needed keyboard button to perform the desired actions

If I have to cancel, I press 'esc' twice, if instead I have to confirm, I press 'enter' twice

**Comment by TyKonKet** [comment]
@haamic when you have time, please test the new version (1.0.7.0-30) and let me know :)

**Comment by haamic** [comment]
this works perfectly now, thank you.
"Return" after input, driver name is saved or waypoint is displayed in the route network and input dialog disappears.
--------------------------------------------------------
das funktioniert jetzt perfekt, danke
"Return" nach Eingabe, Fahrername wird gespeichert, bzw. Wegpunkt wird im Streckennetz angezeigt und Eingabedialog verschwindet.
