### ISSUE TITLE
vergebene Namen Ändern und einstellung speichern MP Dedi / assigned names Change and save settings MP Dedi

### ISSUE THREAD

**Issue by Gyffes** [Stephan-S/FS19_AutoDrive#984]
AutoDrive Version: 1.0.7
Release or selbsterstelltes zip: Release

**Beschreibe den Bug**
Grüße mir ist nun nach längeren Spielen aufgefallen. Das zwar das Namen Vergeben Funktioniert allerdings. Kann ich diesen nicht mehr ändern Resetten oder überschreiben. im MP mit Dedi-Server

Auserdem ist mir aufgefallen das Einstellungen nicht gespeichert werden.
ich stelle den Rohabstand auf 0,5m was gut funktioniert. Nach dem ein und ausloggen. ist der wert resettet und steht wieder auf. -4,5m Das selbe ist mit dem Abladen Level.

Danke Euch.

**Comment by TyKonKet** [comment]
@Gyffes that should have been fixed with the work of this week.
Please let me know when the next release will be public.

**Comment by Gyffes** [comment]
ok danke dann warte ich auf version 1.7.1 und gebe dann bescheid.
ok thank you then I'm waiting for version 1.7.1 and then give notice

**Comment by Gyffes** [comment]
Grüße. 
ich habe das ganze mit mit V1.7.1 getestet. 
Das ändern des Names der Fahrzeuge Funktioniert. 
Auch das Speichern der Einstellungen wie z.B. der Rohrabstand. 
Funktioniert also wunderbar.

Kleine Frage bei den Namen. 
Ist es gewollt, das er die Namen nach dem Ausloggen wieder Resetet. 
Sprich, setztze ich den Namen für Fahrzeug 1050 auf Zwiebel wird nach dem Ausloggen und wieder einloggen wieder 1050 Angezeigt.  Dies passiert auch wenn man das Spiel vor dem Ausloggen speichert. 

Alles im Allem aber eine Super Arbeit. DANKE


Greetings.
I tested the whole thing with V1.7.1.
Changing the name of the vehicles works.
Also saving the settings such as the pipe spacing.
So it works wonderfully.

Little question about the names.
Is it wanted that he resets the names after logging out.
In other words, if I set the name for vehicle 1050 to Onion, after logging out and logging in again, 1050 will be displayed. This also happens if you save the game before logging out.

All in all a great job. THANK YOU

**Comment by Gyffes** [comment]
scheint nach mehrmaligen neustarten nun zu Funktionieren DANKe Schließe das Hier
