### ISSUE TITLE
Häcksler abfahren nicht mehr möglich

### ISSUE THREAD

**Issue by Phippsi** [Stephan-S/FS19_AutoDrive#985]
AutoDrive Version: 1.0.7.0
Release or selbsterstelltes zip: Release
Karte (falls relevant): NF Marsch 4fach
Fahrzeug(art) (falls relevant): Claas Jaguar, Claas Axion

Wenn man AD in Kombination mit CP benutzt, ruckelt der Abfahrer nur mehr in kleinen Schritten hinterher, anstatt neben dem Häcksler zu fahren. Konkret funktioniert die Abfahrt vom Häcksler mit AD in Kombination von CP nicht mehr.
Häcksler: CP
Abfahrer: AD

Laut anderen Nutzern haben die das selbe Problem. Da ich diese Kombi erst seit kurzem kenne, hat es bei mir noch nie funktioniert, vlt könnte mir jemand eine genaue Anleitung der Einstellungen geben, damit ich es überprüfen kann.

Mit freundlichen Grüßen!
Und danke für den tollen Mod :-)

**Comment by Iwan1803** [comment]
Das "Problem" tritt bei Feldern auf, wo der Abfahrer neben dem Feld keinen Platz mehr hätte, um neben  dem Häcksler herzu fahren. Daher fährt er hinterher.
Hier hilft vorerst leider nur ein kurzer Anhänger.

@Stephan-S 
hast du das noch auf deiner Todo-Liste?

**Comment by Phippsi** [comment]
Welcher Anhänger müsste da gehen? Von den Standard...dann kann ich das probieren.

**Comment by Iwan1803** [comment]
https://youtu.be/2EW5jVGQjIQ (ab ca. 19. Minute)
Ich habe es mit einem Claas-Häcksler mit langem Rohr (wichtig!), einem Fendt und einem Strautmann-Anhänger geschafft. Als Gewicht vorne am Trecker setze ich auf den Mod "AgriBumper", denn dadurch wird das Gespann nochmal etwas kürzer.

**Comment by Phippsi** [comment]
Hast du das mit der 1.0.7.0 gemacht?

Am 04.12.2019 08:06 schrieb Iwan1803 <notifications@github.com>:

https://youtu.be/2EW5jVGQjIQ (ab ca. 19. Minute)
Ich habe es mit einem Claas-Häcksler mit langem Rohr (wichtig!), einem Fendt und einem Strautmann-Anhänger geschafft. Als Gewicht vorne am Trecker setze ich auf den Mod "AgriBumper", denn dadurch wird das Gespann nochmal etwas kürzer.

**Comment by Iwan1803** [comment]
Wenn ich es in meinem Video richtig erkenne: 1.0.7.0-10

**Comment by Phippsi** [comment]
-10?? Hab ja gesehen dass du AD Live hast. Wo liegt da der Unterschied, Vor oder Nachteile zum normalen AD?
(Hab grad auf YT auch gepostet wegen AD Live^^)

Gesendet von Mail<https://go.microsoft.com/fwlink/?LinkId=550986> für Windows 10

Von: Iwan1803<mailto:notifications@github.com>
Gesendet: Mittwoch, 4. Dezember 2019 08:38
An: Stephan-S/FS19_AutoDrive<mailto:FS19_AutoDrive@noreply.github.com>
Cc: Phippsi<mailto:leibetseder@live.at>; Author<mailto:author@noreply.github.com>
Betreff: Re: [Stephan-S/FS19_AutoDrive] Häcksler abfahren nicht mehr möglich (#985)


Wenn ich es in meinem Video richtig erkenne: 1.0.7.0-10

**Comment by Iwan1803** [comment]
Ich nutze immer die ZIP von AD hier aus Github, also den manuellen Download und nicht die ZIP aus dem Release-Ordner. Daher kommt die verlängerte Versionsnummer.
Wenn man in AD neue Routen anlegt, muss man immer eine komplette Neuberechnung des gesamten Streckennetzes machen. Das kann bei mir dann schon mal 10-15 Minuten dauern udn in der Zeit kann man auch nicht spielen. AD Live hingegen berechnet die Strecken "on the fly" - also quasi immer erst dann, wenn man ein Fahrzeug losschickt. Dadurch entfällt die komplette Neuberechnung.
Ich hoffe, das AD Live bald soweit ist, das es in AD direkt integriert wird.

**Comment by Phippsi** [comment]
Kannst mir mal den Link schicken? Damit ich weiß dass wir vom selben sprechen^^
Das heißt du hast das normale AD und AD Live im ModOrdner oder?


Gesendet von Mail<https://go.microsoft.com/fwlink/?LinkId=550986> für Windows 10

Von: Iwan1803<mailto:notifications@github.com>
Gesendet: Mittwoch, 4. Dezember 2019 09:14
An: Stephan-S/FS19_AutoDrive<mailto:FS19_AutoDrive@noreply.github.com>
Cc: Phippsi<mailto:leibetseder@live.at>; Author<mailto:author@noreply.github.com>
Betreff: Re: [Stephan-S/FS19_AutoDrive] Häcksler abfahren nicht mehr möglich (#985)


Ich nutze immer die ZIP von AD hier aus Github, also den manuellen Download und nicht die ZIP aus dem Release-Ordner. Daher kommt die verlängerte Versionsnummer.
Wenn man in AD neue Routen anlegt, muss man immer eine komplette Neuberechnung des gesamten Streckennetzes machen. Das kann bei mir dann schon mal 10-15 Minuten dauern udn in der Zeit kann man auch nicht spielen. AD Live hingegen berechnet die Strecken "on the fly" - also quasi immer erst dann, wenn man ein Fahrzeug losschickt. Dadurch entfällt die komplette Neuberechnung.
Ich hoffe, das AD Live bald soweit ist, das es in AD direkt integriert wird.

**Comment by Mannie313** [comment]
woher bekommt man AD Live eigendlich. Ich finde es nirgends.

MFG Mannie313

**Comment by Iwan1803** [comment]
AD Live muss man in AD integrieren:
https://github.com/Axel32019/FS19_AutoDriveLive

**Comment by Phippsi** [comment]
Bekommste auch auf github

Am 04.12.2019 09:35 schrieb Manfred Merkle <notifications@github.com>:

woher bekommt man AD Live eigendlich. Ich finde es nirgends.

MFG Mannie313

**Comment by Tensuko** [comment]
Das Problem mit dem hinterher fahren beim Häcksler hat nicht nur AD, das ist auch bei CP der Fall.
Je nach Füllstand des Trailers ändert sich der Zielpunkt für das Rohr.
Es soll gehen, dass man den Punkt festsetzen kann, sieht aber halt etwas doof aus.
Das Problem bleibt aber, ist das Gespannt Trecker+Trailer zu groß und dann ein Häcksler der nicht weit genug werfen kann, dann klappt es nicht mit dem hinterher fahren.

**Comment by Iwan1803** [comment]
Wie oben bereits geschrieben:

> Ich habe es mit einem Claas-Häcksler mit langem Rohr (wichtig!), einem Fendt und einem Strautmann-Anhänger geschafft. Als Gewicht vorne am Trecker setze ich auf den Mod "AgriBumper", denn dadurch wird das Gespann nochmal etwas kürzer.

**Comment by Justice-Molton** [comment]
Wo muss ich den in einem Fahrsilo das Ziel setzten? An der Einfahrt oder am Ende??

**Comment by Iwan1803** [comment]
Version 1.07.0-35:
Abstand Abfahrer zu Häcksler kann nun in AD eingestellt werden.
_The distance from the driver to the chopper can now be set in AD._
