### ISSUE TITLE
Pick up & deliver didn't drive after loading

### ISSUE THREAD

**Issue by Woife1** [Stephan-S/FS19_AutoDrive#987]
AutoDrive Version: 1.0.7.0-28
Release or custom zip: custom zip
Map (if applicable): NF MArsch 4fach 1.2
Vehicle / type (applicable): Any @ GC Trigger

**Describe the bug**
In the Mode Pick up & deliver the driver pick up but he stops at the pick up destination and didn't drive to the deliver point

**If applicable - Steps to reproduce the behavior**
just use the mode pick up & deliver @ GC loading trigger 
i saw it first and to now only at this pick up point

**Screenshots**
![20191203234218_1](https://user-images.githubusercontent.com/55350545/70096445-65762a80-1627-11ea-9d5c-46c0a3ae61ac.jpg)
![20191204010053_1](https://user-images.githubusercontent.com/55350545/70100327-aa9f5a00-1631-11ea-8efe-59f7c2d5e4fc.jpg)

@axel32019 i hope that's not your fault (live from yesterday)

**Comment by Iwan1803** [comment]
Das ist mir gestern auch aufgefallen, aber vorgestern ging es noch. Die AD Live-Version hat sich nicht geändert, aber die AD-Version schon.
Bei mir hat sich dann teilweise AD selber beendet oder das Gespann blieb halt einfach stehen und wollte scheinbar den Weg zum Ladepunkt berechnen. Bei letzterem hat es bei mir geholfen, den AD-Zielpunkt ein kleines Stück weiter weg vom Trigger neu zu setzen.

_The AD Live version has not changed, but the AD version did. 
Sometimes AD has ended itself or the vehicle just stopped, maybe to calculate the way to the charging point.
In the 2nd case, it helped me to set the AD target a little further away from the trigger._

**Comment by Woife1** [comment]
Wenn das Gespann von LKW und Anhänger zwischen Trigger und Zielpunkt passt sollte es weit genug weg sein ;)

**Comment by Iwan1803** [comment]
GC ist da manchmal etwas "speziell", habe ich so das Gefühl und wie gesagt, es hilft nicht immer.

**Comment by Woife1** [comment]
Das diverse Mods ein bischen Speziell sind ist ja normal ;)

aber der Fehler kam irgendwann in den letzten ca. 20 builds in AD rein

**Comment by Iwan1803** [comment]
Auch heute wieder ganz oft gehabt: 
Ein Trecker mit Anhänger wird zum Abholen von Produkt X geschickt und lädt am Trigger voll. Der Ladepunkt ist noch grün und er fährt dann zum Ladepunkt vor. Dort angekommen, wird der Zielpunkt grün und dann beendet sich AD sofort.
Das geht teilweise so schnell, das man es kaum sieht.

**Comment by haamic** [comment]
Ich wollte Gras aufsammeln und dann im Silo abkippen
Sammelkurs=CP , Abladen=AD
Nach dem der Anhänger voll war übergab CP an AD, AD schaltete das Ziel auf Grün und fuhr aber nicht los. 
--------------------------------------------------------------------
I was gonna pick up weed and dump it in the silo.
Collective course=CP , Unload=AD
After the trailer was full CP handed over to AD, AD switched the finish to green and did not start.

**Comment by haamic** [comment]
jetzt mit version-32 schaltet AD aufs falsche Ziel um, will dahin wo beladen wurde, anstatt zum abladen

**Comment by haamic** [comment]
version -33 
Habe festgestellt, wenn ich einen Anhänger mit Autoload (nutze ich für Missionen) dran habe, dann steuert AD zuerst das Entlade Ziel an anstatt das Lade Ziel, mit einem normalen Anhänger zuerst das Lade-Ziel, so wie es richtig ist.
++++++++++++++++++++++++++++++++++++++++++++++++++++++
version -33 
I noticed that if I have a trailer with autoload (I use it for missions) on it, then AD first drives to the unloading destination instead of the loading destination, with a normal trailer first to the loading destination, as it is correct.

**Comment by Iwan1803** [comment]
Das Problem habe ich mit Flüssigkeitstransporten.

**Comment by haamic** [comment]
selbst ohne anhänger, also nur mit einem traktor, sollte doch die Reihenfolge eingehalten werden, oder nicht? Wieso denkt AD, wenn man es ohne Anhänger versucht, das dieser "voll" wäre und beginnt zum entladen zu fahren?
@Iwan1803  Dann geht das mit den Flüssigkeiten immer noch nicht? wieso wurde dann Issue #900 geschlossen?
+++++++++++++++++++++++++++++++++++++++++
even without a trailer, i.e. only with a tractor, the order should be kept, shouldn't it? Why does AD think, if you try it without a trailer, that the trailer is "full" and starts to unload?
@Iwan1803 Then it still doesn't work with the liquids? why was Issue #900 closed?

**Comment by Lars-LS17** [comment]
Ich habe das selbe Problem mit Flüssigkeiten transportieren. 
Teilweise wird der Anhänger noch aufgefüllt mit Wasser und wenn er dann zum Ziel fahren möchte, beendet sich der AD nach 3m fahren. 
Ein weiteres Problem ist, das teilweise beim Entladen der Anhänger ablädt, jedoch fährt der AD einfach weiter und überfährt den Entladepunkt. Somit wird nur 5% entladen und er fährt wieder zum Startpunkt. 
@Stephan-S gibt es da schon eine Lösung oder Lösungsansatz?

**Comment by TyKonKet** [comment]
**Hello, Thank you for opening this issue!**
Since we have just released [the new refactored version of AutoDrive](https://github.com/Stephan-S/FS19_AutoDrive/releases/tag/1.1.0.0), we can no longer provide any feedback or support for open bug reports related to the old code base.
If the problem persists, please reopen a new issue with all the required details.
Thank you for understanding and we hope you continue enjoying our mod 😄
