### ISSUE TITLE
Pick up mode does not end at destination, vehicle remains active (green)

### ISSUE THREAD

**Issue by haamic** [Stephan-S/FS19_AutoDrive#988]
AutoDrive Version: 1.0.7.0-28
Release or selbsterstelltes zip: self-zip
Karte (falls relevant): Alle
Fahrzeug(art) (falls relevant):

**Beschreibe den Bug**
Im normalen Modus **"Abholen"** wird AD am Ziel nicht beendet, Fahrzeug bleibt aktiv (grün).
Das betrifft nicht den Modus in Verbindung mit CP, da übergibt AD ordnungsgemäss an CP und schaltet AD inaktiv.
-------------------------------------------------------
In normal mode **"Pick-up "** AD is not terminated at destination, vehicle remains active (green).
This does not apply to the mode in conjunction with CP, since AD properly hands over to CP and switches AD to inactive.

**Falls anwendbar - Schritte mit denen ich den Bug nachstellen kann**
Fahrzeug mit z.b. Dünger/Kalkstreuer zum Dünger/Kalk abholen schicken, dann zum Ziel X.
--------------------------------------------------------
Send vehicle with e.g. fertiliser/lime spreader to collect fertiliser/lime, then to target X.

**Screenshots**
![Abholen](https://user-images.githubusercontent.com/28841989/70161452-5f7e5900-16bc-11ea-9ecc-6ebb512d97c9.jpg)

**Comment by TyKonKet** [comment]
@haamic Are you on MP or SP?

**Comment by haamic** [comment]
@TyKonKet    i play only SP
