### ISSUE TITLE
Pipe position over trailer varies depending on unloading mode

### ISSUE THREAD

**Issue by SledgeHammer75** [Stephan-S/FS19_AutoDrive#989]
AutoDrive Version: 1.0.7.0-28 custom zip

The position of the pipe above the trailer differs between "drive-by" and while standing unloading of the combine. 
**Screenshots** created with 0,75 m distance pipe, 0,00 m distance trailer. 

drive-by
![driveby](https://user-images.githubusercontent.com/50592123/70171371-e1777d80-16ce-11ea-9439-92e69c771088.png)

while standing
![standing](https://user-images.githubusercontent.com/50592123/70171378-e50b0480-16ce-11ea-8ee8-86a5edd89740.png)

**Comment by TyKonKet** [comment]
Is that a bug? or just "bad to see"?
I'm asking so that I can assign the correct label :)

**Comment by SledgeHammer75** [comment]
Right now it's just an optical issue. Just want to make sure it does not bite me in the ass later.

**Comment by BloodyRain2k** [comment]
Since when can AD do drive by? All it does for me when the pre-call fires is try to catch up with the combine and after it's _done_ with that is just goes back to _waiting for call_ <.<
