### ISSUE TITLE
Unloader to clingy when corn chopper turns 

### ISSUE THREAD

**Issue by SledgeHammer75** [Stephan-S/FS19_AutoDrive#990]
AutoDrive Version: 1.0.7.0-28 custom zip

When the chopper turns on field lanes, the unloader tries to stay in range of the pipe, blocking the turn of the chopper. 

https://streamable.com/6j3pu

**Comment by Iwan1803** [comment]
Version 1.07.0-35:
Abstand Abfahrer zu Häcksler kann nun in AD eingestellt werden.
_The distance from the driver to the chopper can now be set in AD._
