### ISSUE TITLE
Add different speed limits to waypoints/paths

### ISSUE THREAD

**Issue by cyberndj** [Stephan-S/FS19_AutoDrive#991]
**Is your feature request related to a problem? Please describe.**

1) It gets annoying when an AD path is with traffic and the vehicles on AD will rear-end the AI traffic going a set speed. This can cause either a "jitter" effect or the driving vehicle to go off course and drive in circles to re acquire the path.
2) Some roads/paths can be narrower or there may be tight turns and long straights. Having a single speed can have a vehicle going too slow on a long straight away and/or way to fast going around a bend/corner. Going to fast around corners may cause the vehicle to spin out or tip over. 

Eg. a paved road may be 25Miles/Kilometers from point A to point B that can be traveled at 50Mph/Kph. A dirt path from point A to point B may only be 5M/K long, but can only be travel at 9Mph/Kph.  Which path would be best/fastest? (Yes, the max speed of the vehicles is not considered...) 

**Describe the solution you'd like**

Two ideas for a solution:
1) Set  a speed limit for a section of nodes during course recording in the options.
2) Add an edit method like the named waypoints to set the speed limit (after course recording)

**Describe alternatives you've considered**

Since AD uses the Dijkstra algorithm, it may be easy to set a default weight of 100 (or any other value) and then the speed limits just make a node more less weighted Example, a 50mph/kph speed limit would set the node to a weighted value of 50 of 100 and a 15mph/kph node would set the weighted value to 15 of 100.

**Additional context**

**Comment by PromGames** [comment]
Also would be nice to detect radar in the cities and reduce speed to 50 km to avoid a lot of fines we are having. Example in hop fach lsmodcompany

**Comment by ws1967** [comment]
I mentioned something similar about 2 weeks ago - the answer was "too much work for too little effort". Maybe our wish is more successful, now that not only 1 person has this idea/wish ??
