### ISSUE TITLE
Truck and trailer is loaded but stops at the point and does not continue driving

### ISSUE THREAD

**Issue by Mannie313** [Stephan-S/FS19_AutoDrive#994]
AutoDrive Version: 1.0.7.0-31
Release or selbsterstelltes zip: selbsterstellte Zip
Karte (falls relevant): Alle
Fahrzeug(art) (falls relevant):Alle

**Beschreibe den Bug**
Eine klare Beschreibung des Bugs.
Die LKW's oder Traktoren Werden beladen bleiben dann aber an dem eingestellten punkt stehen. Ist ein Kaufstrigger. Hat die gleichen bits wie die Silotrigger. Getestet im SP.

The trucks or tractors are loaded but then stop at the set point.  Is a purchase trigger. Has the same bits as the silo triggers. Tested in SP. 

**Falls anwendbar - Schritte mit denen ich den Bug nachstellen kann**

**Screenshots**
Falls relevant, bitte Screenshots beifügen
![fsScreen_2019_12_05_21_23_12](https://user-images.githubusercontent.com/3021040/70270842-7d73b880-17a5-11ea-89f5-a6552f29ba7c.png)

MFG Mannie313

**Comment by Mannie313** [comment]
Habs jetzt nochmal getestet. Die Fahrzeuge bleiben alle an dem punkt stehen wo man zum beisspiel hier laden hinschreibt. ob Kauftrigger oder Silotrigger.

Tested it again now. The vehicles all stop at the point where you write to for example load here. whether purchase trigger or silo trigger.

MFG Mannie313

**Comment by TobiHH78** [comment]
I have the ame issue.
For me it happen, when I have two vehicles on same course. When I use only one vehicle, it works fine.
It seems that it makes no differenc where on the course the 2nd vehicle is.

**Comment by bojanh66** [comment]
I have same problem with 2 or 3 vehicles.

**Comment by unlimited78** [comment]
i have also the same problem...

**Comment by Kaljitos** [comment]
I have the same problem , but even when I send a tractor or truck along the route 1, it still becomes 2 laps

**Comment by TyKonKet** [comment]
**Hello, Thank you for opening this issue!**
Since we have just released [the new refactored version of AutoDrive](https://github.com/Stephan-S/FS19_AutoDrive/releases/tag/1.1.0.0), we can no longer provide any feedback or support for open bug reports related to the old code base.
If the problem persists, please reopen a new issue with all the required details.
Thank you for understanding and we hope you continue enjoying our mod 😄
