### ISSUE TITLE
Problem with harvester finding on big fields

### ISSUE THREAD

**Issue by SerGo84** [Stephan-S/FS19_AutoDrive#997]
AutoDrive Version: 1.0.7.0-30
Release or custom zip: Release 1.0.7.0-30
Map (if applicable): All
Vehicle / type (applicable):

**Describe the bug**
The tractor cannot find harvester on big fields.
I have two connected fields on ravenport map: 4+5 and 8+11
Red dots it's a AD points. From this points tractors can't find havester on other side of field.

**If applicable - Steps to reproduce the behavior**

**Screenshots**
![Ravenport1](https://user-images.githubusercontent.com/57571120/70352168-33590880-1873-11ea-8c43-9a616c820ab9.png)

**Comment by geo-luchs** [comment]
I believe, I've the same problem.
![grafik](https://user-images.githubusercontent.com/53658780/70832992-e9ce6780-1df6-11ea-99cd-d3ca47d64d2b.png)

Unloader is telling "drive to Harvester",  but he is not starting.
I've activated Debug mode "path finding". What tells me the "x" with 2 different colors ?

**Comment by geo-luchs** [comment]
It seems to depend on the length of the path.
When switching off the fruitfruit bypass, ti works fine. Tractor is finding a patch through the fruit to the harvester

**Comment by raxtor** [comment]
Yes, its long time problem when headland is unfinished.. I reported it already 2 months ago...

**Comment by rebirth101** [comment]
I was just going to post something simular, when I noticed your post. I have the same problem, does not drive to the harvester when he is over half the field. The first part of the field is not a problem, but once he gets further away, the problem starts. And on my field, it's just one field, not a combined field.
![ad-prob](https://user-images.githubusercontent.com/55347044/71475080-f7b0bf00-27de-11ea-9e6d-ade49b49cd0b.png)

**Comment by SerGo84** [comment]
For *fix* this problem i am using 4-5-6 tractors in differents corners of field ))

**Comment by TyKonKet** [comment]
**Hello, Thank you for opening this issue!**
Since we have just released [the new refactored version of AutoDrive](https://github.com/Stephan-S/FS19_AutoDrive/releases/tag/1.1.0.0), we can no longer provide any feedback or support for open bug reports related to the old code base.
If the problem persists, please reopen a new issue with all the required details.
Thank you for understanding and we hope you continue enjoying our mod 😄
