### ISSUE TITLE
Error: [AutoDrive] 

### ISSUE THREAD

**Issue by Bandesss** [Stephan-S/FS19_AutoDrive#998]
AutoDrive Version: Aktuellste Version
Release or custom zip: Selber gepackt
Map (if applicable): Saxonia
Hallo ist das was neues ?
Kenne diesen Fehler noch nicht 
 Error: [AutoDrive] Encountered a problem during initialization - shutting down

**Comment by Iwan1803** [comment]
Wann trat dieser Fehler genau auf?

**Comment by Bandesss** [comment]
Ich sah es einfach im Log sorry
