### ISSUE TITLE
Combine harvesters follow + call earlier without function? - Mähdrescher folgen + früher rufen ohne funktion?

### ISSUE THREAD

**Issue by haamic** [Stephan-S/FS19_AutoDrive#999]
AutoDrive Version: 1.0.7.0.-33
Release or selbsterstelltes zip: self-zip
Karte (falls relevant): Alle
Fahrzeug(art) (falls relevant):

**Beschreibe den Bug**
Mähdrescher folgen + früher rufen ohne funktion? Ich hatte lange Zeit nicht geerntet.
Der Ablader bleibt stehen und fährt erst bei 100% Füllstand des Mähdreschers los.
Trotzdem früher rufen und Mähdrescher folgen eingestellt ist. Wurde etwas an der Einstellung geändert, warum es nicht mehr geht oder ist das ein schon bekannter Fehler?
+++++++++++++++++++++++++++++++++
Combine harvesters follow + call earlier without function? I hadn't harvested for a long time.
The unloader stops and does not start until the combine is 100% full.
Nevertheless, calling earlier and following the combine harvester is set. Has anything been changed in the setting, why it is no longer possible or is this an already known error?

**Falls anwendbar - Schritte mit denen ich den Bug nachstellen kann**

**Screenshots**
Falls relevant, bitte Screenshots beifügen

**Comment by Iwan1803** [comment]
Sicher, das du diese Optionen beim Abfahrer und Drescher entsprechend eingestellt hast?

**Comment by SledgeHammer75** [comment]
hier ist's ähnlich. Maishäckseln mit 1.0.7.0-28 funktioniert bis auf einige Kinderkrankheiten klasse mit 3 Abfahreren, mit -33 dauert es einige Minuten bis sich ein Abfahrer bequemt zum Häcksler zu fahren (meist aber auch nur, wenn ich mit einem manuellen Abfahrer zusätzlich auf dem Feld bin). 

Zeitgleiche Rübenernte läuft aber ohne Verzögerungen.

**Comment by haamic** [comment]
> Sicher, das du diese Optionen beim Abfahrer und Drescher entsprechend eingestellt hast?

Ja da bin ich mir sicher.  Ist merkwürdig, mal fährt der Drescher das Rohr während dem fahren aus, mal überhaupt nicht. Beim Abfahrer steht "fahre zum Drescher" aber nix passiert. Erst wenn der Drescher voll ist.

**Comment by geo-luchs** [comment]
Kann es sein, dass der Drescher bei den 10% einfach wieder näher beim Abfahrer ist, und dadurch der Path berechnet werden kann?
Wir haben ja den anderen Issue, dass der Abfahrer auf großen Feldern, wo der Weg zum Drescher weiter ist, den path nicht findet.

Stell mal bitte Fruchtumfahrung : Nein zum Testen ein.
Damit findet mein häckselabfahrer auch auf dem großen Feld immer sofort den Path.

**Comment by Stephan-S** [comment]
Hallo, da wir gerade die neue restrukturierte Version von AutoDrive released haben, können wir leider keine Bugs und Issues die sich noch auf die alte Codebasis beziehen mehr bearbeiten.
Wenn das Problem bzw. dein Anliegen in der atkuellen Version weiterhin besteht, mache doch bitte ein neues Issue mit allen benötigten Informationen auf.
Oder melde dich bei kleineren Themen und Fragen auch gerne direkt im Discord:
https://discord.gg/sUQtKhB

Vielen Dank für dein Verständniss und ich hoffe du hast weiterhin Spaß am AutoDrive Mod :-)

Und hier noch ein Link zur aktuellen Version:
https://github.com/Stephan-S/FS19_AutoDrive/releases/tag/1.1.0.0
